AzerothCore Doxygen
WaypointMovementGenerator.cpp File Reference
#include "WaypointMovementGenerator.h"
#include "Creature.h"
#include "CreatureAI.h"
#include "CreatureGroups.h"
#include "GameTime.h"
#include "MapMgr.h"
#include "MoveSpline.h"
#include "MoveSplineInit.h"
#include "ObjectMgr.h"
#include "Player.h"
#include "Spell.h"
#include "Transport.h"
#include "SmartScriptMgr.h"
#include "World.h"
Macros
#define SKIP_SPLINE_POINT_DISTANCE_SQ (40.0f * 40.0f)
#define PLAYER_FLIGHT_SPEED 32.0f
Functions
G3D::Vector3 PositionToVector3 (Position const &p)
void UpdateHomePosition (Creature *creature, WaypointNode const &waypointNode)
bool IsNodeIncludedInShortenedPath (TaxiPathNodeEntry const *p1, TaxiPathNodeEntry const *p2)
Macro Definition Documentation
PLAYER_FLIGHT_SPEED
#define PLAYER_FLIGHT_SPEED 32.0f
SKIP_SPLINE_POINT_DISTANCE_SQ
#define SKIP_SPLINE_POINT_DISTANCE_SQ (40.0f * 40.0f)
Function Documentation
IsNodeIncludedInShortenedPath()
bool IsNodeIncludedInShortenedPath (TaxiPathNodeEntry const * p1, TaxiPathNodeEntry const * p2)
{
    return p1->mapid != p2->mapid || std::pow(p1->x - p2->x, 2) + std::pow(p1->y - p2->y, 2) > SKIP_SPLINE_POINT_DISTANCE_SQ;
}
References TaxiPathNodeEntry::mapid, SKIP_SPLINE_POINT_DISTANCE_SQ, TaxiPathNodeEntry::x, and TaxiPathNodeEntry::y.
Referenced by FlightPathMovementGenerator::LoadPath().
PositionToVector3()
G3D::Vector3 PositionToVector3 (Position const & p) inline
{ return { p.GetPositionX(), p.GetPositionY(), p.GetPositionZ() }; }
References Position::GetPositionX(), Position::GetPositionY(), and Position::GetPositionZ().
Referenced by WaypointMovementGenerator< Creature >::StartMove().
UpdateHomePosition()
void UpdateHomePosition (Creature * creature, WaypointNode const & waypointNode) inline
{
    float x = waypointNode.X;
    float y = waypointNode.Y;
    float z = waypointNode.Z;
    float o = creature->GetOrientation();
    bool transportPath = creature->HasUnitMovementFlag(MOVEMENTFLAG_ONTRANSPORT) && creature->GetTransGUID();
    if (!transportPath)
        creature->SetHomePosition(x, y, z, o);
    else
    {
        if (Transport* trans = (creature->GetTransport() ? creature->GetTransport()->ToMotionTransport() : nullptr))
        {
            o -= trans->GetOrientation();
            creature->SetTransportHomePosition(x, y, z, o);
            trans->CalculatePassengerPosition(x, y, z, &o);
            creature->SetHomePosition(x, y, z, o);
        }
    }
}
References Position::GetOrientation(), Unit::GetTransGUID(), WorldObject::GetTransport(), Unit::HasUnitMovementFlag(), MOVEMENTFLAG_ONTRANSPORT, Creature::SetHomePosition(), Creature::SetTransportHomePosition(), GameObject::ToMotionTransport(), WaypointNode::X, WaypointNode::Y, and WaypointNode::Z.
Referenced by WaypointMovementGenerator< Creature >::DoUpdate(), and WaypointMovementGenerator< Creature >::ProcessWaypointArrival().