AzerothCore Doxygen
OPvPCapturePointZM_Graveyard Class Reference
#include "OutdoorPvPZM.h"
Public Member Functions
OPvPCapturePointZM_Graveyard (OutdoorPvP *pvp)
bool Update (uint32 diff) override
void ChangeState () override
void FillInitialWorldStates (WorldPackets::WorldState::InitWorldStates &packet) override
void UpdateTowerState ()
int32 HandleOpenGo (Player *player, GameObject *go) override
void SetBeaconState (TeamId controlling_teamId)
bool HandleGossipOption (Player *player, Creature *creature, uint32 gossipid) override
bool HandleDropFlag (Player *player, uint32 spellId) override
bool CanTalkTo (Player *player, Creature *creature, GossipMenuItems const &gso) override
uint32 GetGraveyardState () const
Public Member Functions inherited from OPvPCapturePoint
OPvPCapturePoint (OutdoorPvP *pvp)
virtual ~OPvPCapturePoint ()=default
void SendUpdateWorldState (uint32 field, uint32 value)
void SendObjectiveComplete (uint32 id, ObjectGuid guid=ObjectGuid::Empty)
virtual bool HandlePlayerEnter (Player *player)
virtual void HandlePlayerLeave (Player *player)
bool IsInsideObjective (Player *player) const
virtual bool HandleCustomSpell (Player *player, uint32 spellId, GameObject *go)
virtual void ChangeTeam (TeamId)
virtual void SendChangePhase ()
virtual void DeleteSpawns ()
void AddGO (uint32 type, ObjectGuid::LowType guid, uint32 entry=0)
void AddCre (uint32 type, ObjectGuid::LowType guid, uint32 entry=0)
bool SetCapturePointData (uint32 entry, uint32 map, float x, float y, float z, float o=0, float rotation0=0, float rotation1=0, float rotation2=0, float rotation3=0)
void SetSlider (float slider)
float GetSlider () const
Protected Attributes
TeamId m_BothControllingFactionId
ObjectGuid m_FlagCarrierGUID
Protected Attributes inherited from OPvPCapturePoint
std::array< PlayerSet, 2 > _activePlayers
float _maxValue {}
float _minValue {}
float _maxSpeed {}
float _value {}
TeamId _team { TEAM_NEUTRAL }
ObjectiveStates _oldState { OBJECTIVESTATE_NEUTRAL }
ObjectiveStates _state { OBJECTIVESTATE_NEUTRAL }
uint32 _neutralValuePct {}
OutdoorPvP * _pvp {}
std::unordered_map< uint32, ObjectGuid::LowType > _objects
std::unordered_map< uint32, ObjectGuid::LowType > _creatures
std::unordered_map< ObjectGuid::LowType, uint32 > _objectTypes
std::unordered_map< ObjectGuid::LowType, uint32 > _creatureTypes
Private Attributes
uint32 m_GraveyardState
Additional Inherited Members
Public Attributes inherited from OPvPCapturePoint
ObjectGuid::LowType m_capturePointSpawnId {}
GameObject * _capturePoint {}
Protected Member Functions inherited from OPvPCapturePoint
bool AddObject (uint32 type, uint32 entry, uint32 map, float x, float y, float z, float o, float rotation0, float rotation1, float rotation2, float rotation3)
bool AddCreature (uint32 type, uint32 entry, uint32 map, float x, float y, float z, float o, uint32 spawntimeDelay=0)
bool DelCreature (uint32 type)
bool DelObject (uint32 type)
bool DelCapturePoint ()
Detailed Description
Constructor & Destructor Documentation
OPvPCapturePointZM_Graveyard()
OPvPCapturePointZM_Graveyard::OPvPCapturePointZM_Graveyard (OutdoorPvP * pvp)
    : OPvPCapturePoint(pvp)
{
    m_BothControllingFactionId = TEAM_NEUTRAL;
    m_GraveyardState = ZM_GRAVEYARD_N;
    m_FlagCarrierGUID.Clear();
    // add field scouts here
    AddCreature(ZM_ALLIANCE_FIELD_SCOUT, ZM_AllianceFieldScout.entry, ZM_AllianceFieldScout.map, ZM_AllianceFieldScout.x, ZM_AllianceFieldScout.y, ZM_AllianceFieldScout.z, ZM_AllianceFieldScout.o);
    AddCreature(ZM_HORDE_FIELD_SCOUT, ZM_HordeFieldScout.entry, ZM_HordeFieldScout.map, ZM_HordeFieldScout.x, ZM_HordeFieldScout.y, ZM_HordeFieldScout.z, ZM_HordeFieldScout.o);
    // add neutral banner
    AddObject(0, ZM_Banner_N.entry, ZM_Banner_N.map, ZM_Banner_N.x, ZM_Banner_N.y, ZM_Banner_N.z, ZM_Banner_N.o, ZM_Banner_N.rot0, ZM_Banner_N.rot1, ZM_Banner_N.rot2, ZM_Banner_N.rot3);
}
References OPvPCapturePoint::AddCreature(), OPvPCapturePoint::AddObject(), ObjectGuid::Clear(), go_type::entry, creature_type::entry, m_BothControllingFactionId, m_FlagCarrierGUID, m_GraveyardState, go_type::map, creature_type::map, go_type::o, creature_type::o, go_type::rot0, go_type::rot1, go_type::rot2, go_type::rot3, TEAM_NEUTRAL, go_type::x, creature_type::x, go_type::y, creature_type::y, go_type::z, creature_type::z, ZM_ALLIANCE_FIELD_SCOUT, ZM_AllianceFieldScout, ZM_Banner_N, ZM_GRAVEYARD_N, ZM_HORDE_FIELD_SCOUT, and ZM_HordeFieldScout.
Member Function Documentation
CanTalkTo()
bool OPvPCapturePointZM_Graveyard::CanTalkTo (Player * player, Creature * creature, GossipMenuItems const & gso) override virtual
Reimplemented from OPvPCapturePoint.
{
    auto itr = _creatureTypes.find(c->GetSpawnId());
    if (itr != _creatureTypes.end())
    {
        if (itr->second == ZM_ALLIANCE_FIELD_SCOUT && player->GetTeamId() == TEAM_ALLIANCE && m_BothControllingFactionId == TEAM_ALLIANCE && !m_FlagCarrierGUID && m_GraveyardState != ZM_GRAVEYARD_A)
            return true;
        else if (itr->second == ZM_HORDE_FIELD_SCOUT && player->GetTeamId() == TEAM_HORDE && m_BothControllingFactionId == TEAM_HORDE && !m_FlagCarrierGUID && m_GraveyardState != ZM_GRAVEYARD_H)
            return true;
    }
    return false;
}
References OPvPCapturePoint::_creatureTypes, Creature::GetSpawnId(), Player::GetTeamId(), m_BothControllingFactionId, m_FlagCarrierGUID, m_GraveyardState, TEAM_ALLIANCE, TEAM_HORDE, ZM_ALLIANCE_FIELD_SCOUT, ZM_GRAVEYARD_A, ZM_GRAVEYARD_H, and ZM_HORDE_FIELD_SCOUT.
ChangeState()
void OPvPCapturePointZM_Graveyard::ChangeState () inline override virtual
Implements OPvPCapturePoint.
{}
FillInitialWorldStates()
void OPvPCapturePointZM_Graveyard::FillInitialWorldStates (WorldPackets::WorldState::InitWorldStates & packet) override virtual
Reimplemented from OPvPCapturePoint.
{
    packet.Worldstates.reserve(7);
    packet.Worldstates.emplace_back(WORLD_STATE_OPVP_ZM_MAP_GRAVEYARD_N, (m_GraveyardState & ZM_GRAVEYARD_N) != 0 ? 1 : 0);
    packet.Worldstates.emplace_back(WORLD_STATE_OPVP_ZM_MAP_GRAVEYARD_H, (m_GraveyardState & ZM_GRAVEYARD_H) != 0 ? 1 : 0);
    packet.Worldstates.emplace_back(WORLD_STATE_OPVP_ZM_MAP_GRAVEYARD_A, (m_GraveyardState & ZM_GRAVEYARD_A) != 0 ? 1 : 0);
    packet.Worldstates.emplace_back(WORLD_STATE_OPVP_ZM_MAP_ALLIANCE_FLAG_READY, m_BothControllingFactionId == TEAM_ALLIANCE ? 1 : 0);
    packet.Worldstates.emplace_back(WORLD_STATE_OPVP_ZM_MAP_ALLIANCE_FLAG_NOT_READY, m_BothControllingFactionId != TEAM_ALLIANCE ? 1 : 0);
    packet.Worldstates.emplace_back(WORLD_STATE_OPVP_ZM_MAP_HORDE_FLAG_READY, m_BothControllingFactionId == TEAM_HORDE ? 1 : 0);
    packet.Worldstates.emplace_back(WORLD_STATE_OPVP_ZM_MAP_HORDE_FLAG_NOT_READY, m_BothControllingFactionId != TEAM_HORDE ? 1 : 0);
}
References m_BothControllingFactionId, m_GraveyardState, TEAM_ALLIANCE, TEAM_HORDE, WORLD_STATE_OPVP_ZM_MAP_ALLIANCE_FLAG_NOT_READY, WORLD_STATE_OPVP_ZM_MAP_ALLIANCE_FLAG_READY, WORLD_STATE_OPVP_ZM_MAP_GRAVEYARD_A, WORLD_STATE_OPVP_ZM_MAP_GRAVEYARD_H, WORLD_STATE_OPVP_ZM_MAP_GRAVEYARD_N, WORLD_STATE_OPVP_ZM_MAP_HORDE_FLAG_NOT_READY, WORLD_STATE_OPVP_ZM_MAP_HORDE_FLAG_READY, WorldPackets::WorldState::InitWorldStates::Worldstates, ZM_GRAVEYARD_A, ZM_GRAVEYARD_H, and ZM_GRAVEYARD_N.
GetGraveyardState()
uint32 OPvPCapturePointZM_Graveyard::GetGraveyardState () const
{
    return m_GraveyardState;
}
References m_GraveyardState.
Referenced by OutdoorPvPZM::HandlePlayerEnterZone().
HandleDropFlag()
bool OPvPCapturePointZM_Graveyard::HandleDropFlag (Player * player, uint32 spellId) override virtual
Reimplemented from OPvPCapturePoint.
{
    switch (spellId)
    {
        case ZM_BATTLE_STANDARD_A:
            m_FlagCarrierGUID.Clear();
            return true;
        case ZM_BATTLE_STANDARD_H:
            m_FlagCarrierGUID.Clear();
            return true;
    }
    return false;
}
References ObjectGuid::Clear(), m_FlagCarrierGUID, ZM_BATTLE_STANDARD_A, and ZM_BATTLE_STANDARD_H.
HandleGossipOption()
bool OPvPCapturePointZM_Graveyard::HandleGossipOption (Player * player, Creature * creature, uint32 gossipid) override virtual
Reimplemented from OPvPCapturePoint.
{
    auto itr = _creatureTypes.find(creature->GetSpawnId());
    if (itr != _creatureTypes.end())
    {
        // if the flag is already taken, then return
        if (m_FlagCarrierGUID)
            return true;
        if (itr->second == ZM_ALLIANCE_FIELD_SCOUT)
        {
            creature->CastSpell(player, ZM_BATTLE_STANDARD_A, true);
            m_FlagCarrierGUID = player->GetGUID();
        }
        else if (itr->second == ZM_HORDE_FIELD_SCOUT)
        {
            creature->CastSpell(player, ZM_BATTLE_STANDARD_H, true);
            m_FlagCarrierGUID = player->GetGUID();
        }
        UpdateTowerState();
        player->PlayerTalkClass->SendCloseGossip();
        return true;
    }
    return false;
}
References OPvPCapturePoint::_creatureTypes, Unit::CastSpell(), Object::GetGUID(), Creature::GetSpawnId(), m_FlagCarrierGUID, Player::PlayerTalkClass, PlayerMenu::SendCloseGossip(), UpdateTowerState(), ZM_ALLIANCE_FIELD_SCOUT, ZM_BATTLE_STANDARD_A, ZM_BATTLE_STANDARD_H, and ZM_HORDE_FIELD_SCOUT.
HandleOpenGo()
int32 OPvPCapturePointZM_Graveyard::HandleOpenGo (Player * player, GameObject * go) override virtual
Reimplemented from OPvPCapturePoint.
{
    int32 retval = OPvPCapturePoint::HandleOpenGo(player, go);
    if (retval >= 0)
    {
        if (player->HasAura(ZM_BATTLE_STANDARD_A) && m_GraveyardState != ZM_GRAVEYARD_A)
        {
            if (m_GraveyardState == ZM_GRAVEYARD_H)
                _pvp->GetMap()->SendZoneText(ZM_GRAVEYARD_ZONE, sObjectMgr->GetAcoreStringForDBCLocale(LANG_OPVP_ZM_LOSE_GY_H).c_str());
            m_GraveyardState = ZM_GRAVEYARD_A;
            DelObject(0);   // only one gotype is used in the whole outdoor pvp, no need to call it a constant
            AddObject(0, ZM_Banner_A.entry, ZM_Banner_A.map, ZM_Banner_A.x, ZM_Banner_A.y, ZM_Banner_A.z, ZM_Banner_A.o, ZM_Banner_A.rot0, ZM_Banner_A.rot1, ZM_Banner_A.rot2, ZM_Banner_A.rot3);
            sGraveyard->RemoveGraveyardLink(ZM_GRAVEYARD_ID, ZM_GRAVEYARD_ZONE, TEAM_HORDE);          // rem gy
            sGraveyard->AddGraveyardLink(ZM_GRAVEYARD_ID, ZM_GRAVEYARD_ZONE, TEAM_ALLIANCE, false);   // add gy
            _pvp->TeamApplyBuff(TEAM_ALLIANCE, ZM_CAPTURE_BUFF, 0, player);
            player->RemoveAurasDueToSpell(ZM_BATTLE_STANDARD_A);
            _pvp->GetMap()->SendZoneText(ZM_GRAVEYARD_ZONE, sObjectMgr->GetAcoreStringForDBCLocale(LANG_OPVP_ZM_CAPTURE_GY_A).c_str());
        }
        else if (player->HasAura(ZM_BATTLE_STANDARD_H) && m_GraveyardState != ZM_GRAVEYARD_H)
        {
            if (m_GraveyardState == ZM_GRAVEYARD_A)
                _pvp->GetMap()->SendZoneText(ZM_GRAVEYARD_ZONE, sObjectMgr->GetAcoreStringForDBCLocale(LANG_OPVP_ZM_LOSE_GY_A).c_str());
            m_GraveyardState = ZM_GRAVEYARD_H;
            DelObject(0);   // only one gotype is used in the whole outdoor pvp, no need to call it a constant
            AddObject(0, ZM_Banner_H.entry, ZM_Banner_H.map, ZM_Banner_H.x, ZM_Banner_H.y, ZM_Banner_H.z, ZM_Banner_H.o, ZM_Banner_H.rot0, ZM_Banner_H.rot1, ZM_Banner_H.rot2, ZM_Banner_H.rot3);
            sGraveyard->RemoveGraveyardLink(ZM_GRAVEYARD_ID, ZM_GRAVEYARD_ZONE, TEAM_ALLIANCE);          // rem gy
            sGraveyard->AddGraveyardLink(ZM_GRAVEYARD_ID, ZM_GRAVEYARD_ZONE, TEAM_HORDE, false);   // add gy
            _pvp->TeamApplyBuff(TEAM_HORDE, ZM_CAPTURE_BUFF, 0, player);
            player->RemoveAurasDueToSpell(ZM_BATTLE_STANDARD_H);
            _pvp->GetMap()->SendZoneText(ZM_GRAVEYARD_ZONE, sObjectMgr->GetAcoreStringForDBCLocale(LANG_OPVP_ZM_CAPTURE_GY_H).c_str());
        }
        UpdateTowerState();
    }
    return retval;
}
References OPvPCapturePoint::_pvp, OPvPCapturePoint::AddObject(), OPvPCapturePoint::DelObject(), go_type::entry, OutdoorPvP::GetMap(), OPvPCapturePoint::HandleOpenGo(), Unit::HasAura(), LANG_OPVP_ZM_CAPTURE_GY_A, LANG_OPVP_ZM_CAPTURE_GY_H, LANG_OPVP_ZM_LOSE_GY_A, LANG_OPVP_ZM_LOSE_GY_H, m_GraveyardState, go_type::map, go_type::o, Unit::RemoveAurasDueToSpell(), go_type::rot0, go_type::rot1, go_type::rot2, go_type::rot3, Map::SendZoneText(), sGraveyard, sObjectMgr, TEAM_ALLIANCE, TEAM_HORDE, OutdoorPvP::TeamApplyBuff(), UpdateTowerState(), go_type::x, go_type::y, go_type::z, ZM_Banner_A, ZM_Banner_H, ZM_BATTLE_STANDARD_A, ZM_BATTLE_STANDARD_H, ZM_CAPTURE_BUFF, ZM_GRAVEYARD_A, ZM_GRAVEYARD_H, ZM_GRAVEYARD_ID, and ZM_GRAVEYARD_ZONE.
SetBeaconState()
void OPvPCapturePointZM_Graveyard::SetBeaconState (TeamId controlling_teamId)
{
    // nothing to do here
    if (m_BothControllingFactionId == controlling_factionId)
        return;
    m_BothControllingFactionId = controlling_factionId;
    switch (controlling_factionId)
    {
        case TEAM_ALLIANCE:
            // if ally already controls the gy and taken back both beacons, return, nothing to do for us
            if (m_GraveyardState & ZM_GRAVEYARD_A)
                return;
            // ally doesn't control the gy, but controls the side beacons -> add gossip option, add neutral banner
            break;
        case TEAM_HORDE:
            // if horde already controls the gy and taken back both beacons, return, nothing to do for us
            if (m_GraveyardState & ZM_GRAVEYARD_H)
                return;
            // horde doesn't control the gy, but controls the side beacons -> add gossip option, add neutral banner
            break;
        default:
            // if the graveyard is not neutral, then leave it that way
            // if the graveyard is neutral, then we have to dispel the buff from the flag carrier
            if (m_GraveyardState & ZM_GRAVEYARD_N)
            {
                // gy was neutral, thus neutral banner was spawned, it is possible that someone was taking the flag to the gy
                if (m_FlagCarrierGUID)
                {
                    // remove flag from carrier, reset flag carrier guid
                    Player* p = ObjectAccessor::FindPlayer(m_FlagCarrierGUID);
                    if (p)
                    {
                        p->RemoveAurasDueToSpell(ZM_BATTLE_STANDARD_A);
                        p->RemoveAurasDueToSpell(ZM_BATTLE_STANDARD_H);
                    }
                    m_FlagCarrierGUID.Clear();
                }
            }
            break;
    }
    // send worldstateupdate
    UpdateTowerState();
}
References ObjectGuid::Clear(), ObjectAccessor::FindPlayer(), m_BothControllingFactionId, m_FlagCarrierGUID, m_GraveyardState, Unit::RemoveAurasDueToSpell(), TEAM_ALLIANCE, TEAM_HORDE, UpdateTowerState(), ZM_BATTLE_STANDARD_A, ZM_BATTLE_STANDARD_H, ZM_GRAVEYARD_A, ZM_GRAVEYARD_H, and ZM_GRAVEYARD_N.
Referenced by OutdoorPvPZM::Update().
Update()
bool OPvPCapturePointZM_Graveyard::Update (uint32 diff) override virtual
Reimplemented from OPvPCapturePoint.
{
    bool retval = _state != _oldState;
    _state = _oldState;
    return retval;
}
References OPvPCapturePoint::_oldState, and OPvPCapturePoint::_state.
UpdateTowerState()
void OPvPCapturePointZM_Graveyard::UpdateTowerState ()
{
    _pvp->SendUpdateWorldState(WORLD_STATE_OPVP_ZM_MAP_GRAVEYARD_N, uint32(bool(m_GraveyardState & ZM_GRAVEYARD_N)));
    _pvp->SendUpdateWorldState(WORLD_STATE_OPVP_ZM_MAP_GRAVEYARD_H, uint32(bool(m_GraveyardState & ZM_GRAVEYARD_H)));
    _pvp->SendUpdateWorldState(WORLD_STATE_OPVP_ZM_MAP_GRAVEYARD_A, uint32(bool(m_GraveyardState & ZM_GRAVEYARD_A)));
    _pvp->SendUpdateWorldState(WORLD_STATE_OPVP_ZM_MAP_ALLIANCE_FLAG_READY, uint32(m_BothControllingFactionId == TEAM_ALLIANCE));
    _pvp->SendUpdateWorldState(WORLD_STATE_OPVP_ZM_MAP_ALLIANCE_FLAG_NOT_READY, uint32(m_BothControllingFactionId != TEAM_ALLIANCE));
    _pvp->SendUpdateWorldState(WORLD_STATE_OPVP_ZM_MAP_HORDE_FLAG_READY, uint32(m_BothControllingFactionId == TEAM_HORDE));
    _pvp->SendUpdateWorldState(WORLD_STATE_OPVP_ZM_MAP_HORDE_FLAG_NOT_READY, uint32(m_BothControllingFactionId != TEAM_HORDE));
}
References OPvPCapturePoint::_pvp, m_BothControllingFactionId, m_GraveyardState, OutdoorPvP::SendUpdateWorldState(), TEAM_ALLIANCE, TEAM_HORDE, WORLD_STATE_OPVP_ZM_MAP_ALLIANCE_FLAG_NOT_READY, WORLD_STATE_OPVP_ZM_MAP_ALLIANCE_FLAG_READY, WORLD_STATE_OPVP_ZM_MAP_GRAVEYARD_A, WORLD_STATE_OPVP_ZM_MAP_GRAVEYARD_H, WORLD_STATE_OPVP_ZM_MAP_GRAVEYARD_N, WORLD_STATE_OPVP_ZM_MAP_HORDE_FLAG_NOT_READY, WORLD_STATE_OPVP_ZM_MAP_HORDE_FLAG_READY, ZM_GRAVEYARD_A, ZM_GRAVEYARD_H, and ZM_GRAVEYARD_N.
Referenced by HandleGossipOption(), HandleOpenGo(), and SetBeaconState().
Member Data Documentation
m_BothControllingFactionId
TeamId OPvPCapturePointZM_Graveyard::m_BothControllingFactionId protected
Referenced by CanTalkTo(), FillInitialWorldStates(), OPvPCapturePointZM_Graveyard(), SetBeaconState(), and UpdateTowerState().
m_FlagCarrierGUID
ObjectGuid OPvPCapturePointZM_Graveyard::m_FlagCarrierGUID protected
Referenced by CanTalkTo(), HandleDropFlag(), HandleGossipOption(), OPvPCapturePointZM_Graveyard(), and SetBeaconState().
m_GraveyardState
uint32 OPvPCapturePointZM_Graveyard::m_GraveyardState private
Referenced by CanTalkTo(), FillInitialWorldStates(), GetGraveyardState(), HandleOpenGo(), OPvPCapturePointZM_Graveyard(), SetBeaconState(), and UpdateTowerState().
The documentation for this class was generated from the following files:
azerothcore-wotlk/src/server/scripts/OutdoorPvP/OutdoorPvPZM.h
azerothcore-wotlk/src/server/scripts/OutdoorPvP/OutdoorPvPZM.cpp