AzerothCore Doxygen
LuaPacket Namespace Reference
Functions
int GetOpcode (lua_State *L, WorldPacket *packet)
int GetSize (lua_State *L, WorldPacket *packet)
int SetOpcode (lua_State *L, WorldPacket *packet)
int ReadByte (lua_State *L, WorldPacket *packet)
int ReadUByte (lua_State *L, WorldPacket *packet)
int ReadShort (lua_State *L, WorldPacket *packet)
int ReadUShort (lua_State *L, WorldPacket *packet)
int ReadLong (lua_State *L, WorldPacket *packet)
int ReadULong (lua_State *L, WorldPacket *packet)
int ReadFloat (lua_State *L, WorldPacket *packet)
int ReadDouble (lua_State *L, WorldPacket *packet)
int ReadGUID (lua_State *L, WorldPacket *packet)
int ReadString (lua_State *L, WorldPacket *packet)
int WriteGUID (lua_State *L, WorldPacket *packet)
int WriteString (lua_State *L, WorldPacket *packet)
int WriteByte (lua_State *L, WorldPacket *packet)
int WriteUByte (lua_State *L, WorldPacket *packet)
int WriteShort (lua_State *L, WorldPacket *packet)
int WriteUShort (lua_State *L, WorldPacket *packet)
int WriteLong (lua_State *L, WorldPacket *packet)
int WriteULong (lua_State *L, WorldPacket *packet)
int WriteFloat (lua_State *L, WorldPacket *packet)
int WriteDouble (lua_State *L, WorldPacket *packet)
Function Documentation
GetOpcode()
int LuaPacket::GetOpcode (lua_State * L, WorldPacket * packet)
Returns the opcode of the [WorldPacket].
Returns
uint16 opcode
    {
        Eluna::Push(L, packet->GetOpcode());
        return 1;
    }
References WorldPacket::GetOpcode(), and Eluna::Push().
GetSize()
int LuaPacket::GetSize (lua_State * L, WorldPacket * packet)
Returns the size of the [WorldPacket].
Returns
uint32 size
    {
        Eluna::Push(L, packet->size());
        return 1;
    }
References Eluna::Push(), and ByteBuffer::size().
ReadByte()
int LuaPacket::ReadByte (lua_State * L, WorldPacket * packet)
Reads and returns a signed 8-bit integer value from the [WorldPacket].
Returns
int8 value
    {
        int8 _byte;
        (*packet) >> _byte;
        Eluna::Push(L, _byte);
        return 1;
    }
References Eluna::Push().
ReadDouble()
int LuaPacket::ReadDouble (lua_State * L, WorldPacket * packet)
Reads and returns a double-precision floating-point value from the [WorldPacket].
Returns
double value
    {
        double _val;
        (*packet) >> _val;
        Eluna::Push(L, _val);
        return 1;
    }
References Eluna::Push().
ReadFloat()
int LuaPacket::ReadFloat (lua_State * L, WorldPacket * packet)
Reads and returns a single-precision floating-point value from the [WorldPacket].
Returns
float value
    {
        float _val;
        (*packet) >> _val;
        Eluna::Push(L, _val);
        return 1;
    }
References Eluna::Push().
ReadGUID()
int LuaPacket::ReadGUID (lua_State * L, WorldPacket * packet)
Reads and returns an unsigned 64-bit integer value from the [WorldPacket].
Returns
ObjectGuid value : value returned as string
    {
        ObjectGuid guid;
        (*packet) >> guid;
        Eluna::Push(L, guid);
        return 1;
    }
References Eluna::Push().
ReadLong()
int LuaPacket::ReadLong (lua_State * L, WorldPacket * packet)
Reads and returns a signed 32-bit integer value from the [WorldPacket].
Returns
int32 value
    {
        int32 _long;
        (*packet) >> _long;
        Eluna::Push(L, _long);
        return 1;
    }
References Eluna::Push().
ReadShort()
int LuaPacket::ReadShort (lua_State * L, WorldPacket * packet)
Reads and returns a signed 16-bit integer value from the [WorldPacket].
Returns
int16 value
    {
        int16 _short;
        (*packet) >> _short;
        Eluna::Push(L, _short);
        return 1;
    }
References Eluna::Push().
ReadString()
int LuaPacket::ReadString (lua_State * L, WorldPacket * packet)
Reads and returns a string value from the [WorldPacket].
Returns
string value
    {
        std::string _val;
        (*packet) >> _val;
        Eluna::Push(L, _val);
        return 1;
    }
References Eluna::Push().
ReadUByte()
int LuaPacket::ReadUByte (lua_State * L, WorldPacket * packet)
Reads and returns an unsigned 8-bit integer value from the [WorldPacket].
Returns
uint8 value
    {
        uint8 _ubyte;
        (*packet) >> _ubyte;
        Eluna::Push(L, _ubyte);
        return 1;
    }
References Eluna::Push().
ReadULong()
int LuaPacket::ReadULong (lua_State * L, WorldPacket * packet)
Reads and returns an unsigned 32-bit integer value from the [WorldPacket].
Returns
uint32 value
    {
        uint32 _ulong;
        (*packet) >> _ulong;
        Eluna::Push(L, _ulong);
        return 1;
    }
References Eluna::Push().
ReadUShort()
int LuaPacket::ReadUShort (lua_State * L, WorldPacket * packet)
Reads and returns an unsigned 16-bit integer value from the [WorldPacket].
Returns
uint16 value
    {
        uint16 _ushort;
        (*packet) >> _ushort;
        Eluna::Push(L, _ushort);
        return 1;
    }
References Eluna::Push().
SetOpcode()
int LuaPacket::SetOpcode (lua_State * L, WorldPacket * packet)
Sets the opcode of the [WorldPacket] to the specified opcode.
Parameters
[Opcodes] opcode : see Opcodes.h for all known opcodes
    {
        uint32 opcode = Eluna::CHECKVAL<uint32>(L, 2);
        if (opcode >= NUM_MSG_TYPES)
            return luaL_argerror(L, 2, "valid opcode expected");
        packet->SetOpcode((OpcodesList)opcode);
        return 0;
    }
References luaL_argerror(), NUM_MSG_TYPES, and WorldPacket::SetOpcode().
WriteByte()
int LuaPacket::WriteByte (lua_State * L, WorldPacket * packet)
Writes a signed 8-bit integer value to the [WorldPacket].
Parameters
int8 value : the int8 value to be written to the [WorldPacket]
    {
        int8 byte = Eluna::CHECKVAL<int8>(L, 2);
        (*packet) << byte;
        return 0;
    }
WriteDouble()
int LuaPacket::WriteDouble (lua_State * L, WorldPacket * packet)
Writes a 64-bit floating-point value to the [WorldPacket].
Parameters
double value : the double value to be written to the [WorldPacket]
    {
        double _val = Eluna::CHECKVAL<double>(L, 2);
        (*packet) << _val;
        return 0;
    }
WriteFloat()
int LuaPacket::WriteFloat (lua_State * L, WorldPacket * packet)
Writes a 32-bit floating-point value to the [WorldPacket].
Parameters
float value : the float value to be written to the [WorldPacket]
    {
        float _val = Eluna::CHECKVAL<float>(L, 2);
        (*packet) << _val;
        return 0;
    }
WriteGUID()
int LuaPacket::WriteGUID (lua_State * L, WorldPacket * packet)
Writes an unsigned 64-bit integer value to the [WorldPacket].
Parameters
ObjectGuid value : the value to be written to the [WorldPacket]
    {
        ObjectGuid guid = Eluna::CHECKVAL<ObjectGuid>(L, 2);
        (*packet) << guid;
        return 0;
    }
WriteLong()
int LuaPacket::WriteLong (lua_State * L, WorldPacket * packet)
Writes a signed 32-bit integer value to the [WorldPacket].
Parameters
int32 value : the int32 value to be written to the [WorldPacket]
    {
        int32 _long = Eluna::CHECKVAL<int32>(L, 2);
        (*packet) << _long;
        return 0;
    }
WriteShort()
int LuaPacket::WriteShort (lua_State * L, WorldPacket * packet)
Writes a signed 16-bit integer value to the [WorldPacket].
Parameters
int16 value : the int16 value to be written to the [WorldPacket]
    {
        int16 _short = Eluna::CHECKVAL<int16>(L, 2);
        (*packet) << _short;
        return 0;
    }
WriteString()
int LuaPacket::WriteString (lua_State * L, WorldPacket * packet)
Writes a string to the [WorldPacket].
Parameters
string value : the string to be written to the [WorldPacket]
    {
        std::string _val = Eluna::CHECKVAL<std::string>(L, 2);
        (*packet) << _val;
        return 0;
    }
WriteUByte()
int LuaPacket::WriteUByte (lua_State * L, WorldPacket * packet)
Writes an unsigned 8-bit integer value to the [WorldPacket].
Parameters
uint8 value : the uint8 value to be written to the [WorldPacket]
    {
        uint8 byte = Eluna::CHECKVAL<uint8>(L, 2);
        (*packet) << byte;
        return 0;
    }
WriteULong()
int LuaPacket::WriteULong (lua_State * L, WorldPacket * packet)
Writes an unsigned 32-bit integer value to the [WorldPacket].
Parameters
uint32 value : the uint32 value to be written to the [WorldPacket]
    {
        uint32 _ulong = Eluna::CHECKVAL<uint32>(L, 2);
        (*packet) << _ulong;
        return 0;
    }
WriteUShort()
int LuaPacket::WriteUShort (lua_State * L, WorldPacket * packet)
Writes an unsigned 16-bit integer value to the [WorldPacket].
Parameters
uint16 value : the uint16 value to be written to the [WorldPacket]
    {
        uint16 _ushort = Eluna::CHECKVAL<uint16>(L, 2);
        (*packet) << _ushort;
        return 0;
    }