AzerothCore Doxygen
cs_misc.cpp File Reference
#include "AccountMgr.h"
#include "ArenaTeamMgr.h"
#include "BattlegroundMgr.h"
#include "CellImpl.h"
#include "CharacterCache.h"
#include "Chat.h"
#include "CommandScript.h"
#include "Common.h"
#include "GameGraveyard.h"
#include "GameTime.h"
#include "GridNotifiers.h"
#include "GridTerrainLoader.h"
#include "Group.h"
#include "GuildMgr.h"
#include "IPLocation.h"
#include "InstanceSaveMgr.h"
#include "LFG.h"
#include "LFGMgr.h"
#include "Language.h"
#include "MapMgr.h"
#include "MiscPackets.h"
#include "MMapFactory.h"
#include "MovementGenerator.h"
#include "ObjectAccessor.h"
#include "Pet.h"
#include "Player.h"
#include "Realm.h"
#include "ScriptMgr.h"
#include "SpellAuras.h"
#include "TargetedMovementGenerator.h"
#include "Tokenize.h"
#include "WeatherMgr.h"
#include "WorldSessionMgr.h"
#include "GridNotifiersImpl.h"
Classes
struct AccountFlagText
class misc_commandscript
Functions
std::string const GetLocalizeCreatureName (Creature *creature, LocaleConstant locale)
void AddSC_misc_commandscript ()
Variables
constexpr auto SPELL_STUCK = 7355
constexpr auto SPELL_FREEZE = 9454
AccountFlagText const accountFlagText [MAX_ACCOUNT_FLAG]
Function Documentation
AddSC_misc_commandscript()
void AddSC_misc_commandscript ()
{
    new misc_commandscript();
}
Referenced by AddCommandsScripts().
GetLocalizeCreatureName()
std::string const GetLocalizeCreatureName (Creature * creature, LocaleConstant locale)
{
    auto creatureTemplate = sObjectMgr->GetCreatureTemplate(creature->GetEntry());
    auto cretureLocale = sObjectMgr->GetCreatureLocale(creature->GetEntry());
    std::string name;
    if (cretureLocale)
    {
        name = cretureLocale->Name[locale];
    }
    if (name.empty() && creatureTemplate)
    {
        name = creatureTemplate->Name;
    }
    if (name.empty())
    {
        name = "Unknown creature";
    }
    return name;
}
References Object::GetEntry(), and sObjectMgr.
Referenced by misc_commandscript::HandleFreezeCommand(), and misc_commandscript::HandleUnFreezeCommand().
Variable Documentation
accountFlagText
AccountFlagText const accountFlagText[MAX_ACCOUNT_FLAG]
{
    { ACCOUNT_FLAG_GM, "ACCOUNT_FLAG_GM" },
    { ACCOUNT_FLAG_NOKICK, "ACCOUNT_FLAG_NOKICK" },
    { ACCOUNT_FLAG_COLLECTOR, "ACCOUNT_FLAG_COLLECTOR" },
    { ACCOUNT_FLAG_TRIAL, "ACCOUNT_FLAG_TRIAL" },
    { ACCOUNT_FLAG_CANCELLED, "ACCOUNT_FLAG_CANCELLED" },
    { ACCOUNT_FLAG_IGR, "ACCOUNT_FLAG_IGR" },
    { ACCOUNT_FLAG_WHOLESALER, "ACCOUNT_FLAG_WHOLESALER" },
    { ACCOUNT_FLAG_PRIVILEGED, "ACCOUNT_FLAG_PRIVILEGED" },
    { ACCOUNT_FLAG_EU_FORBID_ELV, "ACCOUNT_FLAG_EU_FORBID_ELV" },
    { ACCOUNT_FLAG_EU_FORBID_BILLING, "ACCOUNT_FLAG_EU_FORBID_BILLING" },
    { ACCOUNT_FLAG_RESTRICTED, "ACCOUNT_FLAG_RESTRICTED" },
    { ACCOUNT_FLAG_REFERRAL, "ACCOUNT_FLAG_REFERRAL" },
    { ACCOUNT_FLAG_BLIZZARD, "ACCOUNT_FLAG_BLIZZARD" },
    { ACCOUNT_FLAG_RECURRING_BILLING, "ACCOUNT_FLAG_RECURRING_BILLING" },
    { ACCOUNT_FLAG_NOELECTUP, "ACCOUNT_FLAG_NOELECTUP" },
    { ACCOUNT_FLAG_KR_CERTIFICATE, "ACCOUNT_FLAG_KR_CERTIFICATE" },
    { ACCOUNT_FLAG_EXPANSION_COLLECTOR, "ACCOUNT_FLAG_EXPANSION_COLLECTOR" },
    { ACCOUNT_FLAG_DISABLE_VOICE, "ACCOUNT_FLAG_DISABLE_VOICE" },
    { ACCOUNT_FLAG_DISABLE_VOICE_SPEAK, "ACCOUNT_FLAG_DISABLE_VOICE_SPEAK" },
    { ACCOUNT_FLAG_REFERRAL_RESURRECT, "ACCOUNT_FLAG_REFERRAL_RESURRECT" },
    { ACCOUNT_FLAG_EU_FORBID_CC, "ACCOUNT_FLAG_EU_FORBID_CC" },
    { ACCOUNT_FLAG_OPENBETA_DELL, "ACCOUNT_FLAG_OPENBETA_DELL" },
    { ACCOUNT_FLAG_PROPASS, "ACCOUNT_FLAG_PROPASS" },
    { ACCOUNT_FLAG_PROPASS_LOCK, "ACCOUNT_FLAG_PROPASS_LOCK" },
    { ACCOUNT_FLAG_PENDING_UPGRADE, "ACCOUNT_FLAG_PENDING_UPGRADE" },
    { ACCOUNT_FLAG_RETAIL_FROM_TRIAL, "ACCOUNT_FLAG_RETAIL_FROM_TRIAL" },
    { ACCOUNT_FLAG_EXPANSION2_COLLECTOR, "ACCOUNT_FLAG_EXPANSION2_COLLECTOR" },
    { ACCOUNT_FLAG_OVERMIND_LINKED, "ACCOUNT_FLAG_OVERMIND_LINKED" },
    { ACCOUNT_FLAG_DEMOS, "ACCOUNT_FLAG_DEMOS" },
    { ACCOUNT_FLAG_DEATH_KNIGHT_OK, "ACCOUNT_FLAG_DEATH_KNIGHT_OK" },
    { ACCOUNT_FLAG_S2_REQUIRE_IGR, "ACCOUNT_FLAG_S2_REQUIRE_IGR" },
    { ACCOUNT_FLAG_S2_TRIAL, "ACCOUNT_FLAG_S2_TRIAL" },
    // { ACCOUNT_FLAG_S2_RESTRICTED, "ACCOUNT_FLAG_S2_RESTRICTED" }
};
Referenced by misc_commandscript::HandlePInfoCommand().
SPELL_FREEZE
constexpr auto SPELL_FREEZE = 9454 constexpr
Referenced by misc_commandscript::HandleFreezeCommand(), and misc_commandscript::HandleUnFreezeCommand().
SPELL_STUCK
constexpr auto SPELL_STUCK = 7355 constexpr
Todo:
: this import is not necessary for compilation and marked as unused by the IDE
Referenced by misc_commandscript::HandleUnstuckCommand().