AzerothCore Doxygen
BindingMap< K > Class Template Reference
#include "BindingMap.h"
Classes
struct Binding
Public Member Functions
BindingMap (lua_State *L)
uint64 Insert (const K &key, int ref, uint32 shots)
void Clear (const K &key)
void Clear ()
void Remove (uint64 id)
bool HasBindingsFor (const K &key)
void PushRefsFor (const K &key)
Public Member Functions inherited from ElunaUtil::Lockable
LockType & GetLock ()
Private Types
typedef std::vector< std::unique_ptr< Binding > > BindingList
Private Attributes
lua_State * L
uint64 maxBindingID
std::unordered_map< K, BindingList > bindings
std::unordered_map< uint64, BindingList * > id_lookup_table
Additional Inherited Members
Public Types inherited from ElunaUtil::Lockable
typedef std::mutex LockType
typedef std::lock_guard< LockType > Guard
Detailed Description
template<typename K>
class BindingMap< K >
Member Typedef Documentation
BindingList
template<typename K > typedef std::vector< std::unique_ptr<Binding> > BindingMap< K >::BindingList private
Constructor & Destructor Documentation
BindingMap()
template<typename K > BindingMap< K >::BindingMap (lua_State * L) inline
                             :
        L(L),
        maxBindingID(0)
    { }
Member Function Documentation
Clear() [1/2]
template<typename K > void BindingMap< K >::Clear () inline
    {
        Guard guard(GetLock());
        if (bindings.empty())
            return;
        id_lookup_table.clear();
        bindings.clear();
    }
References BindingMap< K >::bindings, ElunaUtil::Lockable::GetLock(), and BindingMap< K >::id_lookup_table.
Clear() [2/2]
template<typename K > void BindingMap< K >::Clear (const K & key) inline
    {
        Guard guard(GetLock());
        if (bindings.empty())
            return;
        auto iter = bindings.find(key);
        if (iter == bindings.end())
            return;
        BindingList& list = iter->second;
        // Remove all pointers to `list` from `id_lookup_table`.
        for (auto i = list.begin(); i != list.end(); ++i)
        {
            std::unique_ptr<Binding>& binding = *i;
            id_lookup_table.erase(binding->id);
        }
        bindings.erase(key);
    }
References BindingMap< K >::bindings, ElunaUtil::Lockable::GetLock(), and BindingMap< K >::id_lookup_table.
Referenced by LuaGlobalFunctions::ClearBattleGroundEvents(), LuaGlobalFunctions::ClearCreatureEvents(), LuaGlobalFunctions::ClearCreatureGossipEvents(), LuaGlobalFunctions::ClearGameObjectEvents(), LuaGlobalFunctions::ClearGameObjectGossipEvents(), LuaGlobalFunctions::ClearGroupEvents(), LuaGlobalFunctions::ClearGuildEvents(), LuaGlobalFunctions::ClearInstanceEvents(), LuaGlobalFunctions::ClearItemEvents(), LuaGlobalFunctions::ClearItemGossipEvents(), LuaGlobalFunctions::ClearMapEvents(), LuaGlobalFunctions::ClearPacketEvents(), LuaGlobalFunctions::ClearPlayerEvents(), LuaGlobalFunctions::ClearPlayerGossipEvents(), LuaGlobalFunctions::ClearServerEvents(), LuaGlobalFunctions::ClearUniqueCreatureEvents(), and Eluna::FreeInstanceId().
HasBindingsFor()
template<typename K > bool BindingMap< K >::HasBindingsFor (const K & key) inline
    {
        Guard guard(GetLock());
        if (bindings.empty())
            return false;
        auto result = bindings.find(key);
        if (result == bindings.end())
            return false;
        BindingList& list = result->second;
        return !list.empty();
    }
References BindingMap< K >::bindings, and ElunaUtil::Lockable::GetLock().
Referenced by Eluna::FreeInstanceId(), Eluna::GetAI(), and Eluna::GetInstanceData().
Insert()
template<typename K > uint64 BindingMap< K >::Insert (const K & key, int ref, uint32 shots) inline
    {
        Guard guard(GetLock());
        uint64 id = (++maxBindingID);
        BindingList& list = bindings[key];
        list.push_back(std::unique_ptr<Binding>(new Binding(L, id, ref, shots)));
        id_lookup_table[id] = &list;
        return id;
    }
References BindingMap< K >::bindings, ElunaUtil::Lockable::GetLock(), BindingMap< K >::id_lookup_table, BindingMap< K >::L, and BindingMap< K >::maxBindingID.
Referenced by Eluna::Register().
PushRefsFor()
template<typename K > void BindingMap< K >::PushRefsFor (const K & key) inline
    {
        Guard guard(GetLock());
        if (bindings.empty())
            return;
        auto result = bindings.find(key);
        if (result == bindings.end())
            return;
        BindingList& list = result->second;
        for (auto i = list.begin(); i != list.end();)
        {
            std::unique_ptr<Binding>& binding = (*i);
            auto i_prev = (i++);
            lua_rawgeti(L, LUA_REGISTRYINDEX, binding->functionReference);
            if (binding->remainingShots > 0)
            {
                binding->remainingShots -= 1;
                if (binding->remainingShots == 0)
                {
                    id_lookup_table.erase(binding->id);
                    list.erase(i_prev);
                }
            }
        }
    }
References BindingMap< K >::bindings, ElunaUtil::Lockable::GetLock(), BindingMap< K >::id_lookup_table, BindingMap< K >::L, lua_rawgeti(), and LUA_REGISTRYINDEX.
Referenced by Eluna::SetupStack().
Remove()
template<typename K > void BindingMap< K >::Remove (uint64 id) inline
    {
        Guard guard(GetLock());
        auto iter = id_lookup_table.find(id);
        if (iter == id_lookup_table.end())
            return;
        BindingList* list = iter->second;
        auto i = list->begin();
        for (; i != list->end(); ++i)
        {
            std::unique_ptr<Binding>& binding = *i;
            if (binding->id == id)
                break;
        }
        if (i != list->end())
            list->erase(i);
        // Unconditionally erase the ID in the lookup table because
        //   it was either already invalid, or it's no longer valid.
        id_lookup_table.erase(id);
    }
References ElunaUtil::Lockable::GetLock(), and BindingMap< K >::id_lookup_table.
Referenced by cancelBinding().
Member Data Documentation
bindings
template<typename K > std::unordered_map<K, BindingList> BindingMap< K >::bindings private
Referenced by BindingMap< K >::Clear(), BindingMap< K >::Clear(), BindingMap< K >::HasBindingsFor(), BindingMap< K >::Insert(), and BindingMap< K >::PushRefsFor().
id_lookup_table
template<typename K > std::unordered_map<uint64, BindingList*> BindingMap< K >::id_lookup_table private
Referenced by BindingMap< K >::Clear(), BindingMap< K >::Clear(), BindingMap< K >::Insert(), BindingMap< K >::PushRefsFor(), and BindingMap< K >::Remove().
L
template<typename K > lua_State* BindingMap< K >::L private
Referenced by BindingMap< K >::Insert(), and BindingMap< K >::PushRefsFor().
maxBindingID
template<typename K > uint64 BindingMap< K >::maxBindingID private
Referenced by BindingMap< K >::Insert().
The documentation for this class was generated from the following file:
mod-eluna/src/LuaEngine/BindingMap.h