AzerothCore Doxygen
ThreatReference Class Reference
#include "ThreatManager.h"
Public Types
enum TauntState : uint32 {
TAUNT_STATE_DETAUNT = 0 ,
TAUNT_STATE_NONE = 1 ,
TAUNT_STATE_TAUNT = 2
}
enum OnlineState {
ONLINE_STATE_ONLINE = 2 ,
ONLINE_STATE_SUPPRESSED = 1 ,
ONLINE_STATE_OFFLINE = 0
}
Public Member Functions
Creature * GetOwner () const
Unit * GetVictim () const
float GetThreat () const
OnlineState GetOnlineState () const
bool IsOnline () const
bool IsAvailable () const
bool IsSuppressed () const
bool IsOffline () const
TauntState GetTauntState () const
bool IsTaunting () const
bool IsDetaunted () const
void AddThreat (float amount)
void ScaleThreat (float factor)
void ModifyThreatByPercent (int32 percent)
void UpdateOffline ()
void ClearThreat ()
ThreatReference (ThreatReference const &)=delete
ThreatReference & operator= (ThreatReference const &)=delete
Protected Member Functions
ThreatReference (ThreatManager *mgr, Unit *victim)
virtual ~ThreatReference ()=default
void UnregisterAndFree ()
bool ShouldBeOffline () const
bool ShouldBeSuppressed () const
void UpdateTauntState (TauntState state=TAUNT_STATE_NONE)
void HeapNotifyIncreased ()
void HeapNotifyDecreased ()
Static Protected Member Functions
static bool FlagsAllowFighting (Unit const *a, Unit const *b)
Protected Attributes
Creature *const _owner
ThreatManager & _mgr
Unit *const _victim
OnlineState _online
float _baseAmount
int32 _tempModifier
TauntState _taunted
Friends
class ThreatManager
struct CompareThreatLessThan
Detailed Description
Member Enumeration Documentation
OnlineState
enum ThreatReference::OnlineState
Enumerator
ONLINE_STATE_ONLINE
ONLINE_STATE_SUPPRESSED
ONLINE_STATE_OFFLINE
{ ONLINE_STATE_ONLINE = 2, ONLINE_STATE_SUPPRESSED = 1, ONLINE_STATE_OFFLINE = 0 };
TauntState
enum ThreatReference::TauntState : uint32
Enumerator
TAUNT_STATE_DETAUNT
TAUNT_STATE_NONE
TAUNT_STATE_TAUNT
: uint32 { TAUNT_STATE_DETAUNT = 0, TAUNT_STATE_NONE = 1, TAUNT_STATE_TAUNT = 2 };
Constructor & Destructor Documentation
ThreatReference() [1/2]
ThreatReference::ThreatReference (ThreatManager * mgr, Unit * victim) inline explicit protected
                                                               :
        _owner(reinterpret_cast<Creature*>(mgr->_owner)), _mgr(*mgr), _victim(victim),
        _baseAmount(0.0f), _tempModifier(0), _taunted(TAUNT_STATE_NONE)
    {
        _online = ONLINE_STATE_OFFLINE;
    }
~ThreatReference()
virtual ThreatReference::~ThreatReference () protected virtual default
ThreatReference() [2/2]
ThreatReference::ThreatReference (ThreatReference const &) delete
Member Function Documentation
AddThreat()
void ThreatReference::AddThreat (float amount)
{
    if (amount == 0.0f)
        return;
    _baseAmount = std::max<float>(_baseAmount + amount, 0.0f);
    if (amount > 0.0f)
        HeapNotifyIncreased();
    else
        HeapNotifyDecreased();
    _mgr._needClientUpdate = true;
}
References _baseAmount, _mgr, ThreatManager::_needClientUpdate, HeapNotifyDecreased(), and HeapNotifyIncreased().
Referenced by ThreatManager::AddThreat().
ClearThreat()
void ThreatReference::ClearThreat ()
{
    _mgr.ClearThreat(this);
}
References _mgr, and ThreatManager::ClearThreat().
FlagsAllowFighting()
bool ThreatReference::FlagsAllowFighting (Unit const * a, Unit const * b) static protected
{
    if (a->IsCreature() && a->ToCreature()->IsTrigger())
        return false;
    if (a->HasUnitFlag(UNIT_FLAG_PLAYER_CONTROLLED))
    {
        if (b->HasUnitFlag(UNIT_FLAG_IMMUNE_TO_PC))
            return false;
    }
    else
    {
        if (b->HasUnitFlag(UNIT_FLAG_IMMUNE_TO_NPC))
            return false;
    }
    return true;
}
References Unit::HasUnitFlag(), Object::IsCreature(), Creature::IsTrigger(), Object::ToCreature(), UNIT_FLAG_IMMUNE_TO_NPC, UNIT_FLAG_IMMUNE_TO_PC, and UNIT_FLAG_PLAYER_CONTROLLED.
Referenced by ShouldBeOffline().
GetOnlineState()
OnlineState ThreatReference::GetOnlineState () const inline
{ return _online; }
Referenced by ThreatManager::AddThreat().
GetOwner()
Creature * ThreatReference::GetOwner () const inline
{ return _owner; }
Referenced by debug_commandscript::HandleDebugHostileRefListCommand().
GetTauntState()
TauntState ThreatReference::GetTauntState () const inline
{ return IsTaunting() ? TAUNT_STATE_TAUNT : _taunted; }
GetThreat()
float ThreatReference::GetThreat () const inline
{ return std::max<float>(_baseAmount + static_cast<float>(_tempModifier), 0.0f); }
Referenced by ThreatManager::CompareReferencesLT(), debug_commandscript::HandleDebugHostileRefListCommand(), and ThreatManager::MatchUnitThreatToHighestThreat().
GetVictim()
Unit * ThreatReference::GetVictim () const inline
{ return _victim; }
Referenced by boss_hazzarah::CanAIAttack(), boss_renataki::boss_renatakiAI::CanAIAttack(), ThreatManager::GetCurrentVictim(), ThreatManager::GetFixateTarget(), ThreatManager::GetLastVictim(), ThreatManager::SendThreatListToClients(), and UpdateOffline().
HeapNotifyDecreased()
void ThreatReference::HeapNotifyDecreased () protected
{
    _mgr._sortedThreatList->decrease(static_cast<ThreatReferenceImpl*>(this)->_handle);
}
References _mgr, and ThreatManager::_sortedThreatList.
Referenced by AddThreat(), ScaleThreat(), UpdateOffline(), and UpdateTauntState().
HeapNotifyIncreased()
void ThreatReference::HeapNotifyIncreased () protected
{
    _mgr._sortedThreatList->increase(static_cast<ThreatReferenceImpl*>(this)->_handle);
}
References _mgr, and ThreatManager::_sortedThreatList.
Referenced by AddThreat(), ThreatManager::AddThreat(), ScaleThreat(), UpdateOffline(), and UpdateTauntState().
IsAvailable()
bool ThreatReference::IsAvailable () const inline
{ return (_online > ONLINE_STATE_OFFLINE); }
Referenced by ThreatManager::GetCurrentVictim(), ThreatManager::MatchUnitThreatToHighestThreat(), and ThreatManager::ReselectVictim().
IsDetaunted()
bool ThreatReference::IsDetaunted () const inline
{ return _taunted == TAUNT_STATE_DETAUNT; }
IsOffline()
bool ThreatReference::IsOffline () const inline
{ return (_online <= ONLINE_STATE_OFFLINE); }
Referenced by debug_commandscript::HandleDebugHostileRefListCommand(), ThreatManager::ReselectVictim(), and UpdateOffline().
IsOnline()
bool ThreatReference::IsOnline () const inline
{ return (_online >= ONLINE_STATE_ONLINE); }
Referenced by ThreatManager::AddThreat().
IsSuppressed()
bool ThreatReference::IsSuppressed () const inline
{ return (_online == ONLINE_STATE_SUPPRESSED); }
Referenced by debug_commandscript::HandleDebugHostileRefListCommand().
IsTaunting()
bool ThreatReference::IsTaunting () const inline
{ return _taunted >= TAUNT_STATE_TAUNT; }
Referenced by ThreatManager::MatchUnitThreatToHighestThreat(), and ShouldBeSuppressed().
ModifyThreatByPercent()
void ThreatReference::ModifyThreatByPercent (int32 percent) inline
{ if (percent) ScaleThreat(0.01f * float(100 + percent)); }
operator=()
ThreatReference & ThreatReference::operator= (ThreatReference const &) delete
ScaleThreat()
void ThreatReference::ScaleThreat (float factor)
{
    if (factor == 1.0f)
        return;
    _baseAmount *= factor;
    if (factor > 1.0f)
        HeapNotifyIncreased();
    else
        HeapNotifyDecreased();
    _mgr._needClientUpdate = true;
}
References _baseAmount, _mgr, ThreatManager::_needClientUpdate, HeapNotifyDecreased(), and HeapNotifyIncreased().
ShouldBeOffline()
bool ThreatReference::ShouldBeOffline () const protected
{
    if (!_owner->CanSeeOrDetect(_victim))
        return true;
    if (!_owner->_IsTargetAcceptable(_victim) || !_owner->CanCreatureAttack(_victim))
        return true;
    if (!FlagsAllowFighting(_owner, _victim) || !FlagsAllowFighting(_victim, _owner))
        return true;
    return false;
}
References Creature::_IsTargetAcceptable(), _owner, _victim, Creature::CanCreatureAttack(), WorldObject::CanSeeOrDetect(), and FlagsAllowFighting().
Referenced by ThreatManager::GetCurrentVictim(), ThreatManager::GetLastVictim(), and UpdateOffline().
ShouldBeSuppressed()
bool ThreatReference::ShouldBeSuppressed () const protected
{
    if (IsTaunting()) // a taunting victim can never be suppressed
        return false;
    if (_victim->IsImmunedToDamage(_owner->GetMeleeDamageSchoolMask()))
        return true;
    if (_victim->HasAuraType(SPELL_AURA_MOD_CONFUSE))
        return true;
    if (_victim->HasBreakableByDamageAuraType(SPELL_AURA_MOD_STUN))
        return true;
    return false;
}
References _owner, _victim, Creature::GetMeleeDamageSchoolMask(), Unit::HasAuraType(), Unit::HasBreakableByDamageAuraType(), Unit::IsImmunedToDamage(), IsTaunting(), SPELL_AURA_MOD_CONFUSE, and SPELL_AURA_MOD_STUN.
Referenced by ThreatManager::AddThreat(), and UpdateOffline().
UnregisterAndFree()
void ThreatReference::UnregisterAndFree () protected
{
    _owner->GetThreatMgr().PurgeThreatListRef(_victim->GetGUID());
    _victim->GetThreatMgr().PurgeThreatenedByMeRef(_owner->GetGUID());
    delete this;
}
References _owner, _victim, Object::GetGUID(), Unit::GetThreatMgr(), ThreatManager::PurgeThreatenedByMeRef(), and ThreatManager::PurgeThreatListRef().
Referenced by ThreatManager::ClearThreat().
UpdateOffline()
void ThreatReference::UpdateOffline ()
{
    bool const shouldBeOffline = ShouldBeOffline();
    if (shouldBeOffline == IsOffline())
        return;
    if (shouldBeOffline)
    {
        _online = ONLINE_STATE_OFFLINE;
        HeapNotifyDecreased();
        _mgr.SendRemoveToClients(_victim);
    }
    else
    {
        _online = ShouldBeSuppressed() ? ONLINE_STATE_SUPPRESSED : ONLINE_STATE_ONLINE;
        HeapNotifyIncreased();
        _mgr.RegisterForAIUpdate(GetVictim()->GetGUID());
    }
}
References _mgr, _online, _victim, GetVictim(), HeapNotifyDecreased(), HeapNotifyIncreased(), IsOffline(), ONLINE_STATE_OFFLINE, ONLINE_STATE_ONLINE, ONLINE_STATE_SUPPRESSED, ThreatManager::RegisterForAIUpdate(), ThreatManager::SendRemoveToClients(), ShouldBeOffline(), and ShouldBeSuppressed().
Referenced by ThreatManager::AddThreat(), and ThreatManager::ReselectVictim().
UpdateTauntState()
void ThreatReference::UpdateTauntState (TauntState state = TAUNT_STATE_NONE) protected
{
    // Check for SPELL_AURA_MOD_DETAUNT (applied from owner to victim)
    if (state < TAUNT_STATE_TAUNT && _victim->HasAuraTypeWithCaster(SPELL_AURA_MOD_DETAUNT, _owner->GetGUID()))
        state = TAUNT_STATE_DETAUNT;
    if (state == _taunted)
        return;
    std::swap(state, _taunted);
    if (_taunted < state)
        HeapNotifyDecreased();
    else
        HeapNotifyIncreased();
    _mgr._needClientUpdate = true;
}
References _mgr, ThreatManager::_needClientUpdate, _owner, _taunted, Object::GetGUID(), HeapNotifyDecreased(), HeapNotifyIncreased(), SPELL_AURA_MOD_DETAUNT, and TAUNT_STATE_DETAUNT.
Friends And Related Symbol Documentation
CompareThreatLessThan
friend struct CompareThreatLessThan friend
ThreatManager
friend class ThreatManager friend
Member Data Documentation
_baseAmount
float ThreatReference::_baseAmount protected
Referenced by AddThreat(), and ScaleThreat().
_mgr
ThreatManager& ThreatReference::_mgr protected
Referenced by AddThreat(), ClearThreat(), HeapNotifyDecreased(), HeapNotifyIncreased(), ScaleThreat(), UpdateOffline(), and UpdateTauntState().
_online
OnlineState ThreatReference::_online protected
Referenced by ThreatManager::AddThreat(), ThreatManager::CompareReferencesLT(), and UpdateOffline().
_owner
Creature* const ThreatReference::_owner protected
Referenced by ShouldBeOffline(), ShouldBeSuppressed(), UnregisterAndFree(), and UpdateTauntState().
_taunted
TauntState ThreatReference::_taunted protected
Referenced by ThreatManager::CompareReferencesLT(), and UpdateTauntState().
_tempModifier
int32 ThreatReference::_tempModifier protected
_victim
Unit* const ThreatReference::_victim protected
Referenced by ThreatManager::ClearThreat(), ThreatManager::ReselectVictim(), ShouldBeOffline(), ShouldBeSuppressed(), UnregisterAndFree(), and UpdateOffline().
The documentation for this class was generated from the following files:
azerothcore-wotlk/src/server/game/Combat/ThreatManager.h
azerothcore-wotlk/src/server/game/Combat/ThreatManager.cpp