AzerothCore Doxygen
lmarshal.h File Reference
#include "lua.h"
Functions
int mar_encode (lua_State *L)
int mar_decode (lua_State *L)
Function Documentation
mar_decode()
int mar_decode (lua_State * L)
{
    size_t l, idx, len;
    const char *p;
    const char *s = luaL_checklstring(L, 1, &l);
    if (l < 1) luaL_error(L, "bad header");
    if (*(unsigned char *)s++ != MAR_MAGIC) luaL_error(L, "bad magic");
    l -= 1;
    if (lua_isnoneornil(L, 2)) {
        lua_newtable(L);
    }
    else if (!lua_istable(L, 2)) {
        luaL_error(L, "bad argument #2 to decode (expected table)");
    }
    lua_settop(L, 2);
    len = lua_rawlen(L, 2);
    lua_newtable(L);
    for (idx = 1; idx <= len; idx++) {
        lua_rawgeti(L, 2, idx);
        lua_rawseti(L, SEEN_IDX, idx);
    }
    p = s;
    mar_decode_value(L, s, l, &p, &idx);
    lua_remove(L, SEEN_IDX);
    lua_remove(L, 2);
    return 1;
}
References lua_isnoneornil, lua_istable, lua_newtable, lua_rawgeti(), lua_rawlen(), lua_rawseti(), lua_remove(), lua_settop(), luaL_checklstring(), luaL_error(), mar_decode_value(), MAR_MAGIC, and SEEN_IDX.
Referenced by ElunaInstanceAI::Load(), and mar_clone().
mar_encode()
int mar_encode (lua_State * L)
{
    const unsigned char m = MAR_MAGIC;
    size_t idx, len;
    mar_Buffer buf;
    if (lua_isnone(L, 1)) {
        lua_pushnil(L);
    }
    if (lua_isnoneornil(L, 2)) {
        lua_newtable(L);
    }
    else if (!lua_istable(L, 2)) {
        luaL_error(L, "bad argument #2 to encode (expected table)");
    }
    lua_settop(L, 2);
    len = lua_rawlen(L, 2);
    lua_newtable(L);
    for (idx = 1; idx <= len; idx++) {
        lua_rawgeti(L, 2, idx);
        if (lua_isnil(L, -1)) {
            lua_pop(L, 1);
            continue;
        }
        lua_pushinteger(L, idx);
        lua_rawset(L, SEEN_IDX);
    }
    lua_pushvalue(L, 1);
    buf_init(L, &buf);
    buf_write(L, (const char*)&m, 1, &buf);
    mar_encode_value(L, &buf, -1, &idx);
    lua_pop(L, 1);
    lua_pushlstring(L, buf.data, buf.head);
    buf_done(L, &buf);
    lua_remove(L, SEEN_IDX);
    return 1;
}
References buf_done(), buf_init(), buf_write(), mar_Buffer::data, mar_Buffer::head, lua_isnil, lua_isnone, lua_isnoneornil, lua_istable, lua_newtable, lua_pop, lua_pushinteger(), lua_pushlstring(), lua_pushnil(), lua_pushvalue(), lua_rawgeti(), lua_rawlen(), lua_rawset(), lua_remove(), lua_settop(), luaL_error(), mar_encode_value(), MAR_MAGIC, and SEEN_IDX.
Referenced by mar_clone(), and ElunaInstanceAI::Save().