AzerothCore Doxygen
ObjectMgr.h File Reference
#include "Bag.h"
#include "ConditionMgr.h"
#include "Creature.h"
#include "DatabaseEnv.h"
#include "GameObject.h"
#include "ItemTemplate.h"
#include "Log.h"
#include "Mail.h"
#include "Map.h"
#include "NPCHandler.h"
#include "Object.h"
#include "ObjectAccessor.h"
#include "ObjectDefines.h"
#include "QuestDef.h"
#include "TemporarySummon.h"
#include "VehicleDefines.h"
#include <functional>
#include <limits>
#include <map>
#include <string>
Classes
struct PageText
struct TempSummonGroupKey
Key for storing temp summon data in TempSummonDataContainer.
struct GameTele
struct ScriptInfo
struct SpellClickInfo
struct AreaTriggerTeleport
struct AreaTrigger
struct BroadcastText
struct CellObjectGuids
struct ModuleString
struct AcoreString
struct PetLevelInfo
struct MailLevelReward
struct RepRewardRate
struct ReputationOnKillEntry
struct RepSpilloverTemplate
struct PointOfInterest
struct QuestGreeting
struct GossipMenuItems
struct GossipMenus
struct QuestPOIPoint
struct QuestPOI
struct LanguageDesc
struct DungeonEncounter
class ObjectMgr
struct ObjectMgr::GameobjectInstanceSavedState
Macros
#define MIN_ACORE_STRING_ID 1
#define MAX_ACORE_STRING_ID 2000000000
#define MIN_CREATURE_AI_TEXT_STRING_ID (-1)
#define MAX_CREATURE_AI_TEXT_STRING_ID (-1000000)
#define ACORE_TRAINER_START_REF 200000
#define MAX_PLAYER_NAME 12
#define MAX_INTERNAL_PLAYER_NAME 15
#define MAX_PET_NAME 12
#define MAX_CHARTER_NAME 24
#define MAX_CHANNEL_NAME 50
#define sObjectMgr ObjectMgr::instance()
Typedefs
typedef std::map< uint32, PageText > PageTextContainer
typedef std::unordered_map< uint16, InstanceTemplate > InstanceTemplateContainer
typedef std::unordered_map< uint32, GameTele > GameTeleContainer
typedef std::multimap< uint32, ScriptInfo > ScriptMap
typedef std::map< uint32, ScriptMap > ScriptMapMap
typedef std::multimap< uint32, uint32 > SpellScriptsContainer
typedef std::pair< SpellScriptsContainer::iterator, SpellScriptsContainer::iterator > SpellScriptsBounds
typedef std::multimap< uint32, SpellClickInfo > SpellClickInfoContainer
typedef std::pair< SpellClickInfoContainer::const_iterator, SpellClickInfoContainer::const_iterator > SpellClickInfoMapBounds
typedef std::unordered_map< uint32, BroadcastText > BroadcastTextContainer
typedef std::set< ObjectGuid::LowType > CellGuidSet
typedef std::unordered_map< uint32, CellObjectGuids > CellObjectGuidsMap
typedef std::unordered_map< uint32, CellObjectGuidsMap > MapObjectGuids
typedef std::map< ObjectGuid, ObjectGuid > LinkedRespawnContainer
typedef std::unordered_map< ObjectGuid::LowType, CreatureData > CreatureDataContainer
typedef std::unordered_map< ObjectGuid::LowType, GameObjectData > GameObjectDataContainer
typedef std::map< TempSummonGroupKey, std::vector< TempSummonData > > TempSummonDataContainer
typedef std::unordered_map< uint32, CreatureLocale > CreatureLocaleContainer
typedef std::unordered_map< uint32, GameObjectLocale > GameObjectLocaleContainer
typedef std::unordered_map< uint32, ItemLocale > ItemLocaleContainer
typedef std::unordered_map< uint32, ItemSetNameLocale > ItemSetNameLocaleContainer
typedef std::unordered_map< uint32, QuestLocale > QuestLocaleContainer
typedef std::unordered_map< uint32, QuestOfferRewardLocale > QuestOfferRewardLocaleContainer
typedef std::unordered_map< uint32, QuestRequestItemsLocale > QuestRequestItemsLocaleContainer
typedef std::unordered_map< uint32, NpcTextLocale > NpcTextLocaleContainer
typedef std::unordered_map< uint32, PageTextLocale > PageTextLocaleContainer
typedef std::map< std::pair< std::string, uint32 >, ModuleString > ModuleStringContainer
typedef std::unordered_map< int32, AcoreString > AcoreStringContainer
typedef std::unordered_map< uint32, GossipMenuItemsLocale > GossipMenuItemsLocaleContainer
typedef std::unordered_map< uint32, PointOfInterestLocale > PointOfInterestLocaleContainer
typedef std::unordered_map< uint32, VehicleSeatAddon > VehicleSeatAddonContainer
typedef std::multimap< uint32, uint32 > QuestRelations
typedef std::pair< QuestRelations::const_iterator, QuestRelations::const_iterator > QuestRelationBounds
typedef std::list< MailLevelReward > MailLevelRewardList
typedef std::unordered_map< uint8, MailLevelRewardList > MailLevelRewardContainer
typedef std::multimap< uint32, GossipMenus > GossipMenusContainer
typedef std::pair< GossipMenusContainer::const_iterator, GossipMenusContainer::const_iterator > GossipMenusMapBounds
typedef std::pair< GossipMenusContainer::iterator, GossipMenusContainer::iterator > GossipMenusMapBoundsNonConst
typedef std::multimap< uint32, GossipMenuItems > GossipMenuItemsContainer
typedef std::pair< GossipMenuItemsContainer::const_iterator, GossipMenuItemsContainer::const_iterator > GossipMenuItemsMapBounds
typedef std::pair< GossipMenuItemsContainer::iterator, GossipMenuItemsContainer::iterator > GossipMenuItemsMapBoundsNonConst
typedef std::vector< QuestPOI > QuestPOIVector
typedef std::unordered_map< uint32, QuestPOIVector > QuestPOIContainer
typedef std::map< std::pair< uint32, uint8 >, QuestGreeting > QuestGreetingContainer
typedef std::unordered_map< uint32, VendorItemData > CacheVendorItemContainer
typedef std::unordered_map< uint32, TrainerSpellData > CacheTrainerSpellContainer
typedef std::vector< uint32 > CreatureCustomIDsContainer
typedef std::list< DungeonEncounter const * > DungeonEncounterList
typedef std::unordered_map< uint32, DungeonEncounterList > DungeonEncounterContainer
typedef std::map< std::pair< SummonSlot, Races >, uint32 > PlayerTotemModelMap
typedef std::map< std::tuple< ShapeshiftForm, uint8, uint8, uint8 >, uint32 > PlayerShapeshiftModelMap
typedef std::array< uint32, MAX_QUEST_MONEY_REWARDS > QuestMoneyRewardArray
typedef std::unordered_map< uint32, QuestMoneyRewardArray > QuestMoneyRewardStore
Enumerations
enum ScriptCommands {
SCRIPT_COMMAND_TALK = 0 ,
SCRIPT_COMMAND_EMOTE = 1 ,
SCRIPT_COMMAND_FIELD_SET = 2 ,
SCRIPT_COMMAND_MOVE_TO = 3 ,
SCRIPT_COMMAND_FLAG_SET = 4 ,
SCRIPT_COMMAND_FLAG_REMOVE = 5 ,
SCRIPT_COMMAND_TELEPORT_TO = 6 ,
SCRIPT_COMMAND_QUEST_EXPLORED = 7 ,
SCRIPT_COMMAND_KILL_CREDIT = 8 ,
SCRIPT_COMMAND_RESPAWN_GAMEOBJECT = 9 ,
SCRIPT_COMMAND_TEMP_SUMMON_CREATURE = 10 ,
SCRIPT_COMMAND_OPEN_DOOR = 11 ,
SCRIPT_COMMAND_CLOSE_DOOR = 12 ,
SCRIPT_COMMAND_ACTIVATE_OBJECT = 13 ,
SCRIPT_COMMAND_REMOVE_AURA = 14 ,
SCRIPT_COMMAND_CAST_SPELL = 15 ,
SCRIPT_COMMAND_PLAY_SOUND = 16 ,
SCRIPT_COMMAND_CREATE_ITEM = 17 ,
SCRIPT_COMMAND_DESPAWN_SELF = 18 ,
SCRIPT_COMMAND_LOAD_PATH = 20 ,
SCRIPT_COMMAND_CALLSCRIPT_TO_UNIT = 21 ,
SCRIPT_COMMAND_KILL = 22 ,
SCRIPT_COMMAND_ORIENTATION = 30 ,
SCRIPT_COMMAND_EQUIP = 31 ,
SCRIPT_COMMAND_MODEL = 32 ,
SCRIPT_COMMAND_CLOSE_GOSSIP = 33 ,
SCRIPT_COMMAND_PLAYMOVIE = 34 ,
SCRIPT_COMMAND_MOVEMENT = 35
}
enum ScriptsType {
SCRIPTS_FIRST = 1 ,
SCRIPTS_SPELL = SCRIPTS_FIRST ,
SCRIPTS_EVENT ,
SCRIPTS_WAYPOINT ,
SCRIPTS_LAST
}
enum eScriptFlags {
SF_TALK_USE_PLAYER = 0x1 ,
SF_EMOTE_USE_STATE = 0x1 ,
SF_TELEPORT_USE_CREATURE = 0x1 ,
SF_KILLCREDIT_REWARD_GROUP = 0x1 ,
SF_REMOVEAURA_REVERSE = 0x1 ,
SF_CASTSPELL_SOURCE_TO_TARGET = 0 ,
SF_CASTSPELL_SOURCE_TO_SOURCE = 1 ,
SF_CASTSPELL_TARGET_TO_TARGET = 2 ,
SF_CASTSPELL_TARGET_TO_SOURCE = 3 ,
SF_CASTSPELL_SEARCH_CREATURE = 4 ,
SF_CASTSPELL_TRIGGERED = 0x1 ,
SF_PLAYSOUND_TARGET_PLAYER = 0x1 ,
SF_PLAYSOUND_DISTANCE_SOUND = 0x2 ,
SF_PLAYSOUND_DISTANCE_RADIUS = 0x4 ,
SF_ORIENTATION_FACE_TARGET = 0x1
}
enum SkillRangeType {
SKILL_RANGE_LANGUAGE ,
SKILL_RANGE_LEVEL ,
SKILL_RANGE_MONO ,
SKILL_RANGE_RANK ,
SKILL_RANGE_NONE
}
Functions
std::string GetScriptsTableNameByType (ScriptsType type)
ScriptMapMap * GetScriptsMapByType (ScriptsType type)
std::string GetScriptCommandName (ScriptCommands command)
SkillRangeType GetSkillRangeType (SkillRaceClassInfoEntry const *rcEntry)
bool normalizePlayerName (std::string &name)
LanguageDesc const * GetLanguageDescByID (uint32 lang)
Variables
ScriptMapMap sSpellScripts
ScriptMapMap sEventScripts
ScriptMapMap sWaypointScripts
LanguageDesc lang_description [LANGUAGES_COUNT]
static constexpr uint32 MAX_QUEST_MONEY_REWARDS = 10
Macro Definition Documentation
ACORE_TRAINER_START_REF
#define ACORE_TRAINER_START_REF 200000
MAX_ACORE_STRING_ID
#define MAX_ACORE_STRING_ID 2000000000
MAX_CHANNEL_NAME
#define MAX_CHANNEL_NAME 50
MAX_CHARTER_NAME
#define MAX_CHARTER_NAME 24
MAX_CREATURE_AI_TEXT_STRING_ID
#define MAX_CREATURE_AI_TEXT_STRING_ID (-1000000)
MAX_INTERNAL_PLAYER_NAME
#define MAX_INTERNAL_PLAYER_NAME 15
MAX_PET_NAME
#define MAX_PET_NAME 12
MAX_PLAYER_NAME
#define MAX_PLAYER_NAME 12
MIN_ACORE_STRING_ID
#define MIN_ACORE_STRING_ID 1
MIN_CREATURE_AI_TEXT_STRING_ID
#define MIN_CREATURE_AI_TEXT_STRING_ID (-1)
sObjectMgr
#define sObjectMgr ObjectMgr::instance()
Typedef Documentation
AcoreStringContainer
typedef std::unordered_map<int32, AcoreString> AcoreStringContainer
BroadcastTextContainer
typedef std::unordered_map<uint32, BroadcastText> BroadcastTextContainer
CacheTrainerSpellContainer
typedef std::unordered_map<uint32, TrainerSpellData> CacheTrainerSpellContainer
CacheVendorItemContainer
typedef std::unordered_map<uint32, VendorItemData> CacheVendorItemContainer
CellGuidSet
typedef std::set<ObjectGuid::LowType> CellGuidSet
CellObjectGuidsMap
typedef std::unordered_map<uint32, CellObjectGuids> CellObjectGuidsMap
CreatureCustomIDsContainer
typedef std::vector<uint32> CreatureCustomIDsContainer
CreatureDataContainer
typedef std::unordered_map<ObjectGuid::LowType, CreatureData> CreatureDataContainer
CreatureLocaleContainer
typedef std::unordered_map<uint32, CreatureLocale> CreatureLocaleContainer
DungeonEncounterContainer
typedef std::unordered_map<uint32, DungeonEncounterList> DungeonEncounterContainer
DungeonEncounterList
typedef std::list<DungeonEncounter const*> DungeonEncounterList
GameObjectDataContainer
typedef std::unordered_map<ObjectGuid::LowType, GameObjectData> GameObjectDataContainer
GameObjectLocaleContainer
typedef std::unordered_map<uint32, GameObjectLocale> GameObjectLocaleContainer
GameTeleContainer
typedef std::unordered_map<uint32, GameTele > GameTeleContainer
GossipMenuItemsContainer
typedef std::multimap<uint32, GossipMenuItems> GossipMenuItemsContainer
GossipMenuItemsLocaleContainer
typedef std::unordered_map<uint32, GossipMenuItemsLocale> GossipMenuItemsLocaleContainer
GossipMenuItemsMapBounds
typedef std::pair<GossipMenuItemsContainer::const_iterator, GossipMenuItemsContainer::const_iterator> GossipMenuItemsMapBounds
GossipMenuItemsMapBoundsNonConst
typedef std::pair<GossipMenuItemsContainer::iterator, GossipMenuItemsContainer::iterator> GossipMenuItemsMapBoundsNonConst
GossipMenusContainer
typedef std::multimap<uint32, GossipMenus> GossipMenusContainer
GossipMenusMapBounds
typedef std::pair<GossipMenusContainer::const_iterator, GossipMenusContainer::const_iterator> GossipMenusMapBounds
GossipMenusMapBoundsNonConst
typedef std::pair<GossipMenusContainer::iterator, GossipMenusContainer::iterator> GossipMenusMapBoundsNonConst
InstanceTemplateContainer
typedef std::unordered_map<uint16, InstanceTemplate> InstanceTemplateContainer
ItemLocaleContainer
typedef std::unordered_map<uint32, ItemLocale> ItemLocaleContainer
ItemSetNameLocaleContainer
typedef std::unordered_map<uint32, ItemSetNameLocale> ItemSetNameLocaleContainer
LinkedRespawnContainer
typedef std::map<ObjectGuid, ObjectGuid> LinkedRespawnContainer
MailLevelRewardContainer
typedef std::unordered_map<uint8, MailLevelRewardList> MailLevelRewardContainer
MailLevelRewardList
typedef std::list<MailLevelReward> MailLevelRewardList
MapObjectGuids
typedef std::unordered_map<uint32, CellObjectGuidsMap> MapObjectGuids
ModuleStringContainer
typedef std::map<std::pair<std::string, uint32>, ModuleString> ModuleStringContainer
NpcTextLocaleContainer
typedef std::unordered_map<uint32, NpcTextLocale> NpcTextLocaleContainer
PageTextContainer
typedef std::map<uint32, PageText> PageTextContainer
PageTextLocaleContainer
typedef std::unordered_map<uint32, PageTextLocale> PageTextLocaleContainer
PlayerShapeshiftModelMap
typedef std::map<std::tuple<ShapeshiftForm , uint8 , uint8 , uint8 >, uint32 > PlayerShapeshiftModelMap
PlayerTotemModelMap
typedef std::map<std::pair<SummonSlot , Races >, uint32 > PlayerTotemModelMap
PointOfInterestLocaleContainer
typedef std::unordered_map<uint32, PointOfInterestLocale> PointOfInterestLocaleContainer
QuestGreetingContainer
typedef std::map<std::pair<uint32, uint8>, QuestGreeting> QuestGreetingContainer
QuestLocaleContainer
typedef std::unordered_map<uint32, QuestLocale> QuestLocaleContainer
QuestMoneyRewardArray
typedef std::array<uint32, MAX_QUEST_MONEY_REWARDS> QuestMoneyRewardArray
QuestMoneyRewardStore
typedef std::unordered_map<uint32, QuestMoneyRewardArray> QuestMoneyRewardStore
QuestOfferRewardLocaleContainer
typedef std::unordered_map<uint32, QuestOfferRewardLocale> QuestOfferRewardLocaleContainer
QuestPOIContainer
typedef std::unordered_map<uint32, QuestPOIVector> QuestPOIContainer
QuestPOIVector
typedef std::vector<QuestPOI> QuestPOIVector
QuestRelationBounds
typedef std::pair<QuestRelations::const_iterator, QuestRelations::const_iterator> QuestRelationBounds
QuestRelations
typedef std::multimap<uint32, uint32> QuestRelations
QuestRequestItemsLocaleContainer
typedef std::unordered_map<uint32, QuestRequestItemsLocale> QuestRequestItemsLocaleContainer
ScriptMap
typedef std::multimap<uint32, ScriptInfo> ScriptMap
ScriptMapMap
typedef std::map<uint32, ScriptMap > ScriptMapMap
SpellClickInfoContainer
typedef std::multimap<uint32, SpellClickInfo> SpellClickInfoContainer
SpellClickInfoMapBounds
typedef std::pair<SpellClickInfoContainer::const_iterator, SpellClickInfoContainer::const_iterator> SpellClickInfoMapBounds
SpellScriptsBounds
typedef std::pair<SpellScriptsContainer::iterator, SpellScriptsContainer::iterator> SpellScriptsBounds
SpellScriptsContainer
typedef std::multimap<uint32, uint32> SpellScriptsContainer
TempSummonDataContainer
typedef std::map<TempSummonGroupKey, std::vector<TempSummonData> > TempSummonDataContainer
VehicleSeatAddonContainer
typedef std::unordered_map<uint32, VehicleSeatAddon> VehicleSeatAddonContainer
Enumeration Type Documentation
eScriptFlags
enum eScriptFlags
Enumerator
SF_TALK_USE_PLAYER
SF_EMOTE_USE_STATE
SF_TELEPORT_USE_CREATURE
SF_KILLCREDIT_REWARD_GROUP
SF_REMOVEAURA_REVERSE
SF_CASTSPELL_SOURCE_TO_TARGET
SF_CASTSPELL_SOURCE_TO_SOURCE
SF_CASTSPELL_TARGET_TO_TARGET
SF_CASTSPELL_TARGET_TO_SOURCE
SF_CASTSPELL_SEARCH_CREATURE
SF_CASTSPELL_TRIGGERED
SF_PLAYSOUND_TARGET_PLAYER
SF_PLAYSOUND_DISTANCE_SOUND
SF_PLAYSOUND_DISTANCE_RADIUS
SF_ORIENTATION_FACE_TARGET
{
    // Talk Flags
    SF_TALK_USE_PLAYER          = 0x1,
    // Emote flags
    SF_EMOTE_USE_STATE          = 0x1,
    // TeleportTo flags
    SF_TELEPORT_USE_CREATURE    = 0x1,
    // KillCredit flags
    SF_KILLCREDIT_REWARD_GROUP  = 0x1,
    // RemoveAura flags
    SF_REMOVEAURA_REVERSE       = 0x1,
    // CastSpell flags
    SF_CASTSPELL_SOURCE_TO_TARGET = 0,
    SF_CASTSPELL_SOURCE_TO_SOURCE = 1,
    SF_CASTSPELL_TARGET_TO_TARGET = 2,
    SF_CASTSPELL_TARGET_TO_SOURCE = 3,
    SF_CASTSPELL_SEARCH_CREATURE  = 4,
    SF_CASTSPELL_TRIGGERED      = 0x1,
    // Playsound flags
    SF_PLAYSOUND_TARGET_PLAYER  = 0x1,
    SF_PLAYSOUND_DISTANCE_SOUND = 0x2,
    SF_PLAYSOUND_DISTANCE_RADIUS = 0x4,
    // Orientation flags
    SF_ORIENTATION_FACE_TARGET  = 0x1,
};
ScriptCommands
enum ScriptCommands
Enumerator
SCRIPT_COMMAND_TALK
SCRIPT_COMMAND_EMOTE
SCRIPT_COMMAND_FIELD_SET
SCRIPT_COMMAND_MOVE_TO
SCRIPT_COMMAND_FLAG_SET
SCRIPT_COMMAND_FLAG_REMOVE
SCRIPT_COMMAND_TELEPORT_TO
SCRIPT_COMMAND_QUEST_EXPLORED
SCRIPT_COMMAND_KILL_CREDIT
SCRIPT_COMMAND_RESPAWN_GAMEOBJECT
SCRIPT_COMMAND_TEMP_SUMMON_CREATURE
SCRIPT_COMMAND_OPEN_DOOR
SCRIPT_COMMAND_CLOSE_DOOR
SCRIPT_COMMAND_ACTIVATE_OBJECT
SCRIPT_COMMAND_REMOVE_AURA
SCRIPT_COMMAND_CAST_SPELL
SCRIPT_COMMAND_PLAY_SOUND
SCRIPT_COMMAND_CREATE_ITEM
SCRIPT_COMMAND_DESPAWN_SELF
SCRIPT_COMMAND_LOAD_PATH
SCRIPT_COMMAND_CALLSCRIPT_TO_UNIT
SCRIPT_COMMAND_KILL
SCRIPT_COMMAND_ORIENTATION
SCRIPT_COMMAND_EQUIP
SCRIPT_COMMAND_MODEL
SCRIPT_COMMAND_CLOSE_GOSSIP
SCRIPT_COMMAND_PLAYMOVIE
SCRIPT_COMMAND_MOVEMENT
{
    SCRIPT_COMMAND_TALK                  = 0,                // source/target = Creature, target = any, datalong = talk type (0=say, 1=whisper, 2=yell, 3=emote text, 4=boss emote text), datalong2 & 1 = player talk (instead of creature), dataint = string_id
    SCRIPT_COMMAND_EMOTE                 = 1,                // source/target = Creature, datalong = emote id, datalong2 = 0: set emote state; > 0: play emote state
    SCRIPT_COMMAND_FIELD_SET             = 2,                // source/target = Creature, datalong = field id, datalog2 = value
    SCRIPT_COMMAND_MOVE_TO               = 3,                // source/target = Creature, datalong2 = time to reach, x/y/z = destination
    SCRIPT_COMMAND_FLAG_SET              = 4,                // source/target = Creature, datalong = field id, datalog2 = bitmask
    SCRIPT_COMMAND_FLAG_REMOVE           = 5,                // source/target = Creature, datalong = field id, datalog2 = bitmask
    SCRIPT_COMMAND_TELEPORT_TO           = 6,                // source/target = Creature/Player (see datalong2), datalong = map_id, datalong2 = 0: Player; 1: Creature, x/y/z = destination, o = orientation
    SCRIPT_COMMAND_QUEST_EXPLORED        = 7,                // target/source = Player, target/source = GO/Creature, datalong = quest id, datalong2 = distance or 0
    SCRIPT_COMMAND_KILL_CREDIT           = 8,                // target/source = Player, datalong = creature entry, datalong2 = 0: personal credit, 1: group credit
    SCRIPT_COMMAND_RESPAWN_GAMEOBJECT    = 9,                // source = WorldObject (summoner), datalong = GO guid, datalong2 = despawn delay
    SCRIPT_COMMAND_TEMP_SUMMON_CREATURE  = 10,               // source = WorldObject (summoner), datalong = creature entry, datalong2 = despawn delay, x/y/z = summon position, o = orientation
    SCRIPT_COMMAND_OPEN_DOOR             = 11,               // source = Unit, datalong = GO guid, datalong2 = reset delay (min 15)
    SCRIPT_COMMAND_CLOSE_DOOR            = 12,               // source = Unit, datalong = GO guid, datalong2 = reset delay (min 15)
    SCRIPT_COMMAND_ACTIVATE_OBJECT       = 13,               // source = Unit, target = GO
    SCRIPT_COMMAND_REMOVE_AURA           = 14,               // source (datalong2 != 0) or target (datalong2 == 0) = Unit, datalong = spell id
    SCRIPT_COMMAND_CAST_SPELL            = 15,               // source and/or target = Unit, datalong2 = cast direction (0: s->t 1: s->s 2: t->t 3: t->s 4: s->creature with dataint entry), dataint & 1 = triggered flag
    SCRIPT_COMMAND_PLAY_SOUND            = 16,               // source = WorldObject, target = none/Player, datalong = sound id, datalong2 (bitmask: 0/1=anyone/player, 0/2=without/with distance dependency, so 1|2 = 3 is target with distance dependency)
    SCRIPT_COMMAND_CREATE_ITEM           = 17,               // target/source = Player, datalong = item entry, datalong2 = amount
    SCRIPT_COMMAND_DESPAWN_SELF          = 18,               // target/source = Creature, datalong = despawn delay
    SCRIPT_COMMAND_LOAD_PATH             = 20,               // source = Unit, datalong = path id, datalong2 = is repeatable
    SCRIPT_COMMAND_CALLSCRIPT_TO_UNIT    = 21,               // source = WorldObject (if present used as a search center), datalong = script id, datalong2 = unit lowguid, dataint = script table to use (see ScriptsType)
    SCRIPT_COMMAND_KILL                  = 22,               // source/target = Creature, dataint = remove corpse attribute
    // AzerothCore only
    SCRIPT_COMMAND_ORIENTATION           = 30,               // source = Unit, target (datalong > 0) = Unit, datalong = > 0 turn source to face target, o = orientation
    SCRIPT_COMMAND_EQUIP                 = 31,               // soucre = Creature, datalong = equipment id
    SCRIPT_COMMAND_MODEL                 = 32,               // source = Creature, datalong = model id
    SCRIPT_COMMAND_CLOSE_GOSSIP          = 33,               // source = Player
    SCRIPT_COMMAND_PLAYMOVIE             = 34,               // source = Player, datalong = movie id
    SCRIPT_COMMAND_MOVEMENT              = 35                // soucre = Creature, datalong = MovementType, datalong2 = MovementDistance (wander_distance f.ex.), dataint = pathid
};
ScriptsType
enum ScriptsType
Enumerator
SCRIPTS_FIRST
SCRIPTS_SPELL
SCRIPTS_EVENT
SCRIPTS_WAYPOINT
SCRIPTS_LAST
{
    SCRIPTS_FIRST = 1,
    SCRIPTS_SPELL = SCRIPTS_FIRST,
    SCRIPTS_EVENT,
    SCRIPTS_WAYPOINT,
    SCRIPTS_LAST
};
SkillRangeType
enum SkillRangeType
Enumerator
SKILL_RANGE_LANGUAGE
SKILL_RANGE_LEVEL
SKILL_RANGE_MONO
SKILL_RANGE_RANK
SKILL_RANGE_NONE
{
    SKILL_RANGE_LANGUAGE,                                   // 300..300
    SKILL_RANGE_LEVEL,                                      // 1..max skill for level
    SKILL_RANGE_MONO,                                       // 1..1, grey monolite bar
    SKILL_RANGE_RANK,                                       // 1..skill for known rank
    SKILL_RANGE_NONE,                                       // 0..0 always
};
Function Documentation
GetLanguageDescByID()
LanguageDesc const * GetLanguageDescByID (uint32 lang)
{
    for (uint8 i = 0; i < LANGUAGES_COUNT; ++i)
    {
        if (uint32(lang_description[i].lang_id) == lang)
            return &lang_description[i];
    }
    return nullptr;
}
References lang_description, and LANGUAGES_COUNT.
Referenced by WorldSession::HandleMessagechatOpcode(), ObjectMgr::LoadBroadcastTexts(), and CreatureTextMgr::LoadCreatureTexts().
GetScriptCommandName()
std::string GetScriptCommandName (ScriptCommands command)
{
    std::string res = "";
    switch (command)
    {
        case SCRIPT_COMMAND_TALK:
            res = "SCRIPT_COMMAND_TALK";
            break;
        case SCRIPT_COMMAND_EMOTE:
            res = "SCRIPT_COMMAND_EMOTE";
            break;
        case SCRIPT_COMMAND_FIELD_SET:
            res = "SCRIPT_COMMAND_FIELD_SET";
            break;
        case SCRIPT_COMMAND_MOVE_TO:
            res = "SCRIPT_COMMAND_MOVE_TO";
            break;
        case SCRIPT_COMMAND_FLAG_SET:
            res = "SCRIPT_COMMAND_FLAG_SET";
            break;
        case SCRIPT_COMMAND_FLAG_REMOVE:
            res = "SCRIPT_COMMAND_FLAG_REMOVE";
            break;
        case SCRIPT_COMMAND_TELEPORT_TO:
            res = "SCRIPT_COMMAND_TELEPORT_TO";
            break;
        case SCRIPT_COMMAND_QUEST_EXPLORED:
            res = "SCRIPT_COMMAND_QUEST_EXPLORED";
            break;
        case SCRIPT_COMMAND_KILL_CREDIT:
            res = "SCRIPT_COMMAND_KILL_CREDIT";
            break;
        case SCRIPT_COMMAND_RESPAWN_GAMEOBJECT:
            res = "SCRIPT_COMMAND_RESPAWN_GAMEOBJECT";
            break;
        case SCRIPT_COMMAND_TEMP_SUMMON_CREATURE:
            res = "SCRIPT_COMMAND_TEMP_SUMMON_CREATURE";
            break;
        case SCRIPT_COMMAND_OPEN_DOOR:
            res = "SCRIPT_COMMAND_OPEN_DOOR";
            break;
        case SCRIPT_COMMAND_CLOSE_DOOR:
            res = "SCRIPT_COMMAND_CLOSE_DOOR";
            break;
        case SCRIPT_COMMAND_ACTIVATE_OBJECT:
            res = "SCRIPT_COMMAND_ACTIVATE_OBJECT";
            break;
        case SCRIPT_COMMAND_REMOVE_AURA:
            res = "SCRIPT_COMMAND_REMOVE_AURA";
            break;
        case SCRIPT_COMMAND_CAST_SPELL:
            res = "SCRIPT_COMMAND_CAST_SPELL";
            break;
        case SCRIPT_COMMAND_PLAY_SOUND:
            res = "SCRIPT_COMMAND_PLAY_SOUND";
            break;
        case SCRIPT_COMMAND_CREATE_ITEM:
            res = "SCRIPT_COMMAND_CREATE_ITEM";
            break;
        case SCRIPT_COMMAND_DESPAWN_SELF:
            res = "SCRIPT_COMMAND_DESPAWN_SELF";
            break;
        case SCRIPT_COMMAND_LOAD_PATH:
            res = "SCRIPT_COMMAND_LOAD_PATH";
            break;
        case SCRIPT_COMMAND_CALLSCRIPT_TO_UNIT:
            res = "SCRIPT_COMMAND_CALLSCRIPT_TO_UNIT";
            break;
        case SCRIPT_COMMAND_KILL:
            res = "SCRIPT_COMMAND_KILL";
            break;
        // AzerothCore only
        case SCRIPT_COMMAND_ORIENTATION:
            res = "SCRIPT_COMMAND_ORIENTATION";
            break;
        case SCRIPT_COMMAND_EQUIP:
            res = "SCRIPT_COMMAND_EQUIP";
            break;
        case SCRIPT_COMMAND_MODEL:
            res = "SCRIPT_COMMAND_MODEL";
            break;
        case SCRIPT_COMMAND_CLOSE_GOSSIP:
            res = "SCRIPT_COMMAND_CLOSE_GOSSIP";
            break;
        case SCRIPT_COMMAND_PLAYMOVIE:
            res = "SCRIPT_COMMAND_PLAYMOVIE";
            break;
        default:
            {
                char sz[32];
                snprintf(sz, sizeof(sz), "Unknown command: %d", command);
                res = sz;
                break;
            }
    }
    return res;
}
References SCRIPT_COMMAND_ACTIVATE_OBJECT, SCRIPT_COMMAND_CALLSCRIPT_TO_UNIT, SCRIPT_COMMAND_CAST_SPELL, SCRIPT_COMMAND_CLOSE_DOOR, SCRIPT_COMMAND_CLOSE_GOSSIP, SCRIPT_COMMAND_CREATE_ITEM, SCRIPT_COMMAND_DESPAWN_SELF, SCRIPT_COMMAND_EMOTE, SCRIPT_COMMAND_EQUIP, SCRIPT_COMMAND_FIELD_SET, SCRIPT_COMMAND_FLAG_REMOVE, SCRIPT_COMMAND_FLAG_SET, SCRIPT_COMMAND_KILL, SCRIPT_COMMAND_KILL_CREDIT, SCRIPT_COMMAND_LOAD_PATH, SCRIPT_COMMAND_MODEL, SCRIPT_COMMAND_MOVE_TO, SCRIPT_COMMAND_OPEN_DOOR, SCRIPT_COMMAND_ORIENTATION, SCRIPT_COMMAND_PLAY_SOUND, SCRIPT_COMMAND_PLAYMOVIE, SCRIPT_COMMAND_QUEST_EXPLORED, SCRIPT_COMMAND_REMOVE_AURA, SCRIPT_COMMAND_RESPAWN_GAMEOBJECT, SCRIPT_COMMAND_TALK, SCRIPT_COMMAND_TELEPORT_TO, and SCRIPT_COMMAND_TEMP_SUMMON_CREATURE.
Referenced by ScriptInfo::GetDebugInfo(), and ObjectMgr::LoadScripts().
GetScriptsMapByType()
ScriptMapMap * GetScriptsMapByType (ScriptsType type)
{
    ScriptMapMap* res = nullptr;
    switch (type)
    {
        case SCRIPTS_SPELL:
            res = &sSpellScripts;
            break;
        case SCRIPTS_EVENT:
            res = &sEventScripts;
            break;
        case SCRIPTS_WAYPOINT:
            res = &sWaypointScripts;
            break;
        default:
            break;
    }
    return res;
}
References SCRIPTS_EVENT, SCRIPTS_SPELL, SCRIPTS_WAYPOINT, sEventScripts, sSpellScripts, and sWaypointScripts.
Referenced by ObjectMgr::LoadScripts(), and Map::ScriptsProcess().
GetScriptsTableNameByType()
std::string GetScriptsTableNameByType (ScriptsType type)
{
    std::string res = "";
    switch (type)
    {
        case SCRIPTS_SPELL:
            res = "spell_scripts";
            break;
        case SCRIPTS_EVENT:
            res = "event_scripts";
            break;
        case SCRIPTS_WAYPOINT:
            res = "waypoint_scripts";
            break;
        default:
            break;
    }
    return res;
}
References SCRIPTS_EVENT, SCRIPTS_SPELL, and SCRIPTS_WAYPOINT.
Referenced by ScriptInfo::GetDebugInfo(), and ObjectMgr::LoadScripts().
GetSkillRangeType()
SkillRangeType GetSkillRangeType (SkillRaceClassInfoEntry const * rcEntry)
{
    SkillLineEntry const* skill = sSkillLineStore.LookupEntry(rcEntry->SkillID);
    if (!skill)
    {
        return SKILL_RANGE_NONE;
    }
    if (sSkillTiersStore.LookupEntry(rcEntry->SkillTierID))
    {
        return SKILL_RANGE_RANK;
    }
    if (rcEntry->SkillID == SKILL_RUNEFORGING)
    {
        return SKILL_RANGE_MONO;
    }
    switch (skill->categoryId)
    {
        case SKILL_CATEGORY_ARMOR:
            return SKILL_RANGE_MONO;
        case SKILL_CATEGORY_LANGUAGES:
            return SKILL_RANGE_LANGUAGE;
    }
    return SKILL_RANGE_LEVEL;
}
References SkillLineEntry::categoryId, SKILL_CATEGORY_ARMOR, SKILL_CATEGORY_LANGUAGES, SKILL_RANGE_LANGUAGE, SKILL_RANGE_LEVEL, SKILL_RANGE_MONO, SKILL_RANGE_NONE, SKILL_RANGE_RANK, SKILL_RUNEFORGING, SkillRaceClassInfoEntry::SkillID, SkillRaceClassInfoEntry::SkillTierID, sSkillLineStore, and sSkillTiersStore.
Referenced by Player::_LoadSkills(), Player::LearnDefaultSkill(), and Player::UpdateSkillsForLevel().
normalizePlayerName()
bool normalizePlayerName (std::string & name)
{
    if (name.empty())
        return false;
    if (name.find(" ") != std::string::npos)
        return false;
    std::wstring tmp;
    if (!Utf8toWStr(name, tmp))
        return false;
    wstrToLower(tmp);
    if (!tmp.empty())
        tmp[0] = wcharToUpper(tmp[0]);
    if (!WStrToUtf8(tmp, name))
        return false;
    return true;
}
References Utf8toWStr(), wcharToUpper(), wstrToLower(), and WStrToUtf8().
Referenced by ChatHandler::extractLowGuidFromLink(), ChatHandler::extractPlayerNameFromLink(), PlayerNameMapHolder::Find(), character_commandscript::GetDeletedCharacterInfoList(), ChatHandler::GetPlayerGroupAndGUIDByName(), WorldSession::HandleAddFriendOpcode(), WorldSession::HandleAddIgnoreOpcode(), WorldSession::HandleArenaTeamInviteOpcode(), WorldSession::HandleArenaTeamLeaderOpcode(), WorldSession::HandleArenaTeamRemoveOpcode(), ban_commandscript::HandleBanCharacterCommand(), ban_commandscript::HandleBanHelper(), WorldSession::HandleChannelBan(), WorldSession::HandleChannelInvite(), WorldSession::HandleChannelKick(), WorldSession::HandleChannelModerator(), WorldSession::HandleChannelMute(), WorldSession::HandleChannelSetOwner(), WorldSession::HandleChannelUnban(), WorldSession::HandleChannelUnmoderator(), WorldSession::HandleChannelUnmute(), character_commandscript::HandleCharacterRenameCommand(), WorldSession::HandleCharCreateOpcode(), WorldSession::HandleCharCustomizeCallback(), WorldSession::HandleCharFactionOrRaceChangeCallback(), WorldSession::HandleCharRenameOpcode(), deserter_commandscript::HandleDeserterAdd(), ticket_commandscript::HandleGMTicketAssignToCommand(), ticket_commandscript::HandleGMTicketGetByNameCommand(), WorldSession::HandleGroupInviteOpcode(), WorldSession::HandleGroupSwapSubGroupOpcode(), WorldSession::HandleGroupUninviteOpcode(), WorldSession::HandleGuildDemoteOpcode(), WorldSession::HandleGuildInviteOpcode(), WorldSession::HandleGuildLeaderOpcode(), WorldSession::HandleGuildPromoteOpcode(), WorldSession::HandleGuildRemoveOpcode(), WorldSession::HandleGuildSetOfficerNoteOpcode(), WorldSession::HandleGuildSetPublicNoteOpcode(), WorldSession::HandleMessagechatOpcode(), WorldSession::HandleSendMail(), WorldSession::HandleSetPlayerDeclinedNames(), ban_commandscript::HandleUnBanCharacterCommand(), ban_commandscript::HandleUnBanHelper(), message_commandscript::HandleWhispersCommand(), WorldSession::HandleWhoisOpcode(), PlayerDumpReader::LoadDump(), Acore::ChatCommands::PlayerIdentifier::TryConsume(), and character_commandscript::ValidatePDumpTarget().
Variable Documentation
lang_description
LanguageDesc lang_description[LANGUAGES_COUNT] extern
{
    { LANG_ADDON,           0, 0                       },
    { LANG_UNIVERSAL,       0, 0                       },
    { LANG_ORCISH,        669, SKILL_LANG_ORCISH       },
    { LANG_DARNASSIAN,    671, SKILL_LANG_DARNASSIAN   },
    { LANG_TAURAHE,       670, SKILL_LANG_TAURAHE      },
    { LANG_DWARVISH,      672, SKILL_LANG_DWARVEN      },
    { LANG_COMMON,        668, SKILL_LANG_COMMON       },
    { LANG_DEMONIC,       815, SKILL_LANG_DEMON_TONGUE },
    { LANG_TITAN,         816, SKILL_LANG_TITAN        },
    { LANG_THALASSIAN,    813, SKILL_LANG_THALASSIAN   },
    { LANG_DRACONIC,      814, SKILL_LANG_DRACONIC     },
    { LANG_KALIMAG,       817, SKILL_LANG_OLD_TONGUE   },
    { LANG_GNOMISH,      7340, SKILL_LANG_GNOMISH      },
    { LANG_TROLL,        7341, SKILL_LANG_TROLL        },
    { LANG_GUTTERSPEAK, 17737, SKILL_LANG_GUTTERSPEAK  },
    { LANG_DRAENEI,     29932, SKILL_LANG_DRAENEI      },
    { LANG_ZOMBIE,          0, 0                       },
    { LANG_GNOMISH_BINARY,  0, 0                       },
    { LANG_GOBLIN_BINARY,   0, 0                       }
};
Referenced by GetLanguageDescByID(), and learn_commandscript::HandleLearnAllLangCommand().
MAX_QUEST_MONEY_REWARDS
constexpr uint32 MAX_QUEST_MONEY_REWARDS = 10 static constexpr
Referenced by ObjectMgr::GetQuestMoneyReward(), and ObjectMgr::LoadQuestMoneyRewards().
sEventScripts
ScriptMapMap sEventScripts extern
Referenced by MotionTransport::DoEventIfAny(), FlightPathMovementGenerator::DoEventIfAny(), WorldSession::DoLootRelease(), Spell::EffectSendEvent(), GetScriptsMapByType(), ObjectMgr::LoadEventScripts(), and GameObject::Use().
sSpellScripts
ScriptMapMap sSpellScripts extern
Referenced by Spell::EffectDummy(), Spell::EffectScriptEffect(), GetScriptsMapByType(), and ObjectMgr::LoadSpellScripts().
sWaypointScripts
ScriptMapMap sWaypointScripts extern
Referenced by GetScriptsMapByType(), ObjectMgr::LoadWaypointScripts(), and WaypointMovementGenerator< Creature >::OnArrived().