AzerothCore Doxygen
WorldGlobals Class Reference
#include "WorldGlobals.h"
Public Member Functions
void LoadAntiDosOpcodePolicies ()
AntiDosOpcodePolicy const * GetAntiDosPolicyForOpcode (uint16 opcode)
Static Public Member Functions
static WorldGlobals * instance ()
Private Attributes
std::array< std::unique_ptr< AntiDosOpcodePolicy >, NUM_OPCODE_HANDLERS > _antiDosOpcodePolicies
Detailed Description
Member Function Documentation
GetAntiDosPolicyForOpcode()
AntiDosOpcodePolicy const * WorldGlobals::GetAntiDosPolicyForOpcode (uint16 opcode)
{
    if (opcode >= NUM_OPCODE_HANDLERS)
        return nullptr;
    return _antiDosOpcodePolicies[opcode].get();
}
References _antiDosOpcodePolicies, and NUM_OPCODE_HANDLERS.
instance()
WorldGlobals * WorldGlobals::instance () static
{
    static WorldGlobals instance;
    return &instance;
}
References instance().
Referenced by instance().
LoadAntiDosOpcodePolicies()
void WorldGlobals::LoadAntiDosOpcodePolicies ()
{
    uint32 oldMSTime = getMSTime();
    _antiDosOpcodePolicies = {};
    QueryResult result = WorldDatabase.Query("SELECT Opcode, Policy, MaxAllowedCount FROM antidos_opcode_policies");
    if (!result)
    {
        LOG_WARN("server.loading", ">> Loaded 0 AntiDos Opcode Policies. DB table `antidos_opcode_policies` is empty!");
        LOG_INFO("server.loading", " ");
        return;
    }
    uint32 count = 0;
    do
    {
        Field* fields = result->Fetch();
        uint16 opcode = fields[0].Get<uint16>();
        if (opcode >= NUM_OPCODE_HANDLERS)
        {
            LOG_ERROR("server.loading", "Unkown opcode {} in table `antidos_opcode_policies`, skipping.", opcode);
            continue;
        }
        std::unique_ptr<AntiDosOpcodePolicy> policy = std::make_unique<AntiDosOpcodePolicy>();
        policy->Policy = fields[1].Get<uint8>();
        policy->MaxAllowedCount = fields[2].Get<uint16>();
        _antiDosOpcodePolicies[opcode] = std::move(policy);
        ++count;
    } while (result->NextRow());
    LOG_INFO("server.loading", ">> Loaded {} AntiDos Opcode Policies in {} ms", count, GetMSTimeDiffToNow(oldMSTime));
    LOG_INFO("server.loading", " ");
}
References _antiDosOpcodePolicies, Field::Get(), getMSTime(), GetMSTimeDiffToNow(), LOG_ERROR, LOG_INFO, LOG_WARN, NUM_OPCODE_HANDLERS, and WorldDatabase.
Member Data Documentation
_antiDosOpcodePolicies
std::array<std::unique_ptr<AntiDosOpcodePolicy>, NUM_OPCODE_HANDLERS> WorldGlobals::_antiDosOpcodePolicies private
Referenced by GetAntiDosPolicyForOpcode(), and LoadAntiDosOpcodePolicies().
The documentation for this class was generated from the following files:
azerothcore-wotlk/src/server/game/Globals/WorldGlobals.h
azerothcore-wotlk/src/server/game/Globals/WorldGlobals.cpp