AzerothCore Doxygen
SpellProcFullCoverageTest.cpp File Reference
Data-driven tests for ALL 869 spell_proc entries.
#include "ProcChanceTestHelper.h"
#include "ProcEventInfoHelper.h"
#include "SpellProcTestData.h"
#include "AuraStub.h"
#include "gtest/gtest.h"
Classes
class SpellProcFullCoverageTest
class SpellProcCoverageStatsTest
Functions
TEST_P (SpellProcFullCoverageTest, CooldownBlocking_WhenCooldownSet)
TEST_P (SpellProcFullCoverageTest, Level60Reduction_WhenAttributeSet)
TEST_P (SpellProcFullCoverageTest, AttributeMask_ValidFlags)
TEST_P (SpellProcFullCoverageTest, UseStacksForCharges_Behavior)
TEST_P (SpellProcFullCoverageTest, TriggeredCanProc_FlagSet)
TEST_P (SpellProcFullCoverageTest, ReqManaCost_FlagSet)
TEST_P (SpellProcFullCoverageTest, ChanceValue_InValidRange)
TEST_P (SpellProcFullCoverageTest, ChanceCalculation_WithEntry)
TEST_P (SpellProcFullCoverageTest, ProcFlags_NotEmpty)
TEST_P (SpellProcFullCoverageTest, CooldownValue_Reasonable)
TEST_P (SpellProcFullCoverageTest, SpellId_NonZero)
INSTANTIATE_TEST_SUITE_P (AllSpellProcEntries, SpellProcFullCoverageTest, ::testing::ValuesIn(GetAllSpellProcTestEntries()), [](const ::testing::TestParamInfo< SpellProcTestEntry > &info) { int32_t id=info.param.SpellId;if(id< 0) return "NegId_"+std::to_string(-id);return "SpellId_"+std::to_string(id);})
TEST_F (SpellProcCoverageStatsTest, CountEntriesWithCooldown)
TEST_F (SpellProcCoverageStatsTest, CountEntriesWithChance)
TEST_F (SpellProcCoverageStatsTest, CountEntriesWithLevel60Reduction)
TEST_F (SpellProcCoverageStatsTest, CountEntriesWithUseStacks)
TEST_F (SpellProcCoverageStatsTest, CountEntriesWithTriggeredCanProc)
TEST_F (SpellProcCoverageStatsTest, CountEntriesWithReqManaCost)
TEST_F (SpellProcCoverageStatsTest, TotalEntryCount)
Detailed Description
Data-driven tests for ALL 869 spell_proc entries.
Tests proc calculations for every spell_proc entry:
Cooldown blocking behavior
Chance calculation with level reduction
Attribute flag validation
This complements SpellProcDataDrivenTest.cpp which tests CanSpellTriggerProcOnEvent().
DESIGN NOTE: Why Tests Skip Certain Entries
This test file uses parameterized tests that run against ALL 869 spell_proc entries. Each test validates a specific feature (cooldowns, level reduction, attribute flags, etc.). Tests use GTEST_SKIP() for entries that don't have the feature being tested.
For example (current counts from test output):
CooldownBlocking_WhenCooldownSet: Tests 246 entries with Cooldown > 0 (skips 623)
Level60Reduction_WhenAttributeSet: Tests entries with PROC_ATTR_REDUCE_PROC_60 (0 currently)
UseStacksForCharges_Behavior: Tests entries with PROC_ATTR_USE_STACKS_FOR_CHARGES (0 currently)
TriggeredCanProc_FlagSet: Tests 73 entries with PROC_ATTR_TRIGGERED_CAN_PROC (skips 796)
ReqManaCost_FlagSet: Tests 5 entries with PROC_ATTR_REQ_MANA_COST (skips 864)
This is INTENTIONAL. Running parameterized tests against all entries ensures:
Every entry is validated for applicable features
Statistics show exact coverage (X entries with feature Y)
New entries added to spell_proc are automatically tested
Regression detection if an entry unexpectedly gains/loses a feature
The statistics tests at the bottom output the exact counts: "[ INFO ] Entries with cooldown: 85 / 869" "[ INFO ] Entries with REDUCE_PROC_60: 15 / 869" etc.
SKIPPED tests are expected and correct. Each skip message includes:
The SpellId being skipped
- The reason (e.g., "has no cooldown", "doesn't have REDUCE_PROC_60")
Definition in file SpellProcFullCoverageTest.cpp.
Function Documentation
INSTANTIATE_TEST_SUITE_P()
INSTANTIATE_TEST_SUITE_P (AllSpellProcEntries , SpellProcFullCoverageTest , ::testing::ValuesIn(GetAllSpellProcTestEntries()) , [] (const ::testing::TestParamInfo< SpellProcTestEntry > &info) { int32_t id=info.param.SpellId;if(id< 0) return "NegId_"+std::to_string(-id);return "SpellId_"+std::to_string(id);})
TEST_F() [1/7]
TEST_F (SpellProcCoverageStatsTest , CountEntriesWithChance)
{
    size_t withChance = 0;
    for (auto const& entry : _allEntries)
    {
        if (entry.Chance > 0.0f)
            ++withChance;
    }
    std::cout << "[  INFO    ] Entries with chance > 0: " << withChance
              << " / " << _allEntries.size() << std::endl;
}
TEST_F() [2/7]
TEST_F (SpellProcCoverageStatsTest , CountEntriesWithCooldown)
{
    size_t withCooldown = 0;
    for (auto const& entry : _allEntries)
    {
        if (entry.Cooldown > 0)
            ++withCooldown;
    }
    std::cout << "[  INFO    ] Entries with cooldown: " << withCooldown
              << " / " << _allEntries.size() << std::endl;
    EXPECT_GT(withCooldown, 0u);
}
TEST_F() [3/7]
TEST_F (SpellProcCoverageStatsTest , CountEntriesWithLevel60Reduction)
{
    size_t withReduction = 0;
    for (auto const& entry : _allEntries)
    {
        if (entry.AttributesMask & PROC_ATTR_REDUCE_PROC_60)
            ++withReduction;
    }
    std::cout << "[  INFO    ] Entries with REDUCE_PROC_60: " << withReduction
              << " / " << _allEntries.size() << std::endl;
}
References PROC_ATTR_REDUCE_PROC_60.
TEST_F() [4/7]
TEST_F (SpellProcCoverageStatsTest , CountEntriesWithReqManaCost)
{
    size_t withReqManaCost = 0;
    for (auto const& entry : _allEntries)
    {
        if (entry.AttributesMask & PROC_ATTR_REQ_MANA_COST)
            ++withReqManaCost;
    }
    std::cout << "[  INFO    ] Entries with REQ_MANA_COST: " << withReqManaCost
              << " / " << _allEntries.size() << std::endl;
}
References PROC_ATTR_REQ_MANA_COST.
TEST_F() [5/7]
TEST_F (SpellProcCoverageStatsTest , CountEntriesWithTriggeredCanProc)
{
    size_t withTriggered = 0;
    for (auto const& entry : _allEntries)
    {
        if (entry.AttributesMask & PROC_ATTR_TRIGGERED_CAN_PROC)
            ++withTriggered;
    }
    std::cout << "[  INFO    ] Entries with TRIGGERED_CAN_PROC: " << withTriggered
              << " / " << _allEntries.size() << std::endl;
}
References PROC_ATTR_TRIGGERED_CAN_PROC.
TEST_F() [6/7]
TEST_F (SpellProcCoverageStatsTest , CountEntriesWithUseStacks)
{
    size_t withUseStacks = 0;
    for (auto const& entry : _allEntries)
    {
        if (entry.AttributesMask & PROC_ATTR_USE_STACKS_FOR_CHARGES)
            ++withUseStacks;
    }
    std::cout << "[  INFO    ] Entries with USE_STACKS_FOR_CHARGES: " << withUseStacks
              << " / " << _allEntries.size() << std::endl;
}
References PROC_ATTR_USE_STACKS_FOR_CHARGES.
TEST_F() [7/7]
TEST_F (SpellProcCoverageStatsTest , TotalEntryCount)
{
    std::cout << "[  INFO    ] Total spell_proc entries tested: " << _allEntries.size() << std::endl;
    EXPECT_EQ(_allEntries.size(), 869u)
        << "Expected 869 entries but got " << _allEntries.size();
}
TEST_P() [1/11]
TEST_P (SpellProcFullCoverageTest , AttributeMask_ValidFlags)
{
    // Valid attribute flags
    constexpr uint32 VALID_ATTRIBUTE_MASK =
        PROC_ATTR_REQ_EXP_OR_HONOR |
        PROC_ATTR_TRIGGERED_CAN_PROC |
        PROC_ATTR_REQ_MANA_COST |
        PROC_ATTR_REQ_SPELLMOD |
        PROC_ATTR_USE_STACKS_FOR_CHARGES |
        PROC_ATTR_REDUCE_PROC_60 |
        PROC_ATTR_CANT_PROC_FROM_ITEM_CAST;
    // Check for invalid bits (skip 0x20 and 0x40 which are unused/reserved)
    uint32 invalidBits = _entry.AttributesMask & ~VALID_ATTRIBUTE_MASK & ~0x60;
    EXPECT_EQ(invalidBits, 0u)
        << "SpellId " << _entry.SpellId << " has invalid attribute bits: 0x"
        << std::hex << invalidBits;
}
References PROC_ATTR_CANT_PROC_FROM_ITEM_CAST, PROC_ATTR_REDUCE_PROC_60, PROC_ATTR_REQ_EXP_OR_HONOR, PROC_ATTR_REQ_MANA_COST, PROC_ATTR_REQ_SPELLMOD, PROC_ATTR_TRIGGERED_CAN_PROC, and PROC_ATTR_USE_STACKS_FOR_CHARGES.
TEST_P() [2/11]
TEST_P (SpellProcFullCoverageTest , ChanceCalculation_WithEntry)
{
    // SKIP REASON: This test validates proc chance calculation with level reduction.
    // Entries with Chance = 0 rely on DBC defaults or use PPM (procs per minute) instead.
    // We can only test explicit chance calculation for entries that define a Chance value.
    // PPM-based procs are tested separately in SpellProcPPMTest.cpp.
    if (_entry.Chance <= 0.0f)
        GTEST_SKIP() << "SpellId " << _entry.SpellId << " has no base chance";
    // Calculate chance at level 80 (typical max level)
    float calculatedChance = ProcChanceTestHelper::SimulateCalcProcChance(
        _procEntry, 80, 2500, 0.0f, 0.0f, false);
    if (_entry.AttributesMask & PROC_ATTR_REDUCE_PROC_60)
    {
        // With level 60+ reduction at level 80
        float expectedReduced = _entry.Chance * (1.0f - 20.0f/30.0f);
        EXPECT_NEAR(calculatedChance, expectedReduced, 0.5f)
            << "SpellId " << _entry.SpellId << " reduced chance mismatch";
    }
    else
    {
        // Without reduction
        EXPECT_NEAR(calculatedChance, _entry.Chance, 0.01f)
            << "SpellId " << _entry.SpellId << " base chance mismatch";
    }
}
References PROC_ATTR_REDUCE_PROC_60, and ProcChanceTestHelper::SimulateCalcProcChance().
TEST_P() [3/11]
TEST_P (SpellProcFullCoverageTest , ChanceValue_InValidRange)
{
    // Chance should be in valid range (0-100 normally, but some can exceed)
    // Just verify it's not negative
    EXPECT_GE(_entry.Chance, 0.0f)
        << "SpellId " << _entry.SpellId << " has negative chance";
    // And not absurdly high (>500% would be suspicious)
    EXPECT_LE(_entry.Chance, 500.0f)
        << "SpellId " << _entry.SpellId << " has suspiciously high chance";
}
TEST_P() [4/11]
TEST_P (SpellProcFullCoverageTest , CooldownBlocking_WhenCooldownSet)
{
    // SKIP REASON: This test validates cooldown blocking behavior.
    // Only entries with Cooldown > 0 can be tested for ICD (Internal Cooldown).
    // Entries without cooldowns proc on every valid trigger, so there's nothing
    // to test here. The skip count shows how many entries lack cooldowns.
    if (_entry.Cooldown == 0)
        GTEST_SKIP() << "SpellId " << _entry.SpellId << " has no cooldown";
    ProcTestScenario scenario;
    scenario.WithAura(std::abs(_entry.SpellId));
    // Set 100% chance to isolate cooldown testing
    SpellProcEntry testEntry = _procEntry;
    testEntry.Chance = 100.0f;
    testEntry.Cooldown = Milliseconds(_entry.Cooldown);
    // First proc should succeed
    EXPECT_TRUE(scenario.SimulateProc(testEntry))
        << "SpellId " << _entry.SpellId << " first proc should succeed";
    // Second proc immediately after should fail (on cooldown)
    EXPECT_FALSE(scenario.SimulateProc(testEntry))
        << "SpellId " << _entry.SpellId << " should be blocked during "
        << _entry.Cooldown << "ms cooldown";
    // Wait for cooldown to expire
    scenario.AdvanceTime(std::chrono::milliseconds(_entry.Cooldown + 1));
    // Third proc after cooldown should succeed
    EXPECT_TRUE(scenario.SimulateProc(testEntry))
        << "SpellId " << _entry.SpellId << " should proc after cooldown expires";
}
References ProcTestScenario::AdvanceTime(), SpellProcEntry::Chance, SpellProcEntry::Cooldown, ProcTestScenario::SimulateProc(), and ProcTestScenario::WithAura().
TEST_P() [5/11]
TEST_P (SpellProcFullCoverageTest , CooldownValue_Reasonable)
{
    // SKIP REASON: This test validates cooldown values are within reasonable bounds.
    // Entries without cooldowns (Cooldown = 0) can proc on every trigger with no
    // internal cooldown. 623 entries have no ICD and this is intentional - they
    // rely on proc chance alone to limit frequency.
    // Only 246 entries with explicit cooldowns need range validation.
    if (_entry.Cooldown == 0)
        GTEST_SKIP() << "SpellId " << _entry.SpellId << " has no cooldown";
    // Cooldowns should be reasonable (not too short, not too long)
    // Shortest reasonable cooldown is ~1ms
    // Longest reasonable cooldown is ~15 minutes (900000ms) - some trinkets have 10+ min ICDs
    EXPECT_GE(_entry.Cooldown, 1u)
        << "SpellId " << _entry.SpellId << " has suspiciously short cooldown";
    EXPECT_LE(_entry.Cooldown, 900000u)
        << "SpellId " << _entry.SpellId << " has suspiciously long cooldown ("
        << _entry.Cooldown << "ms = " << _entry.Cooldown/60000 << " minutes)";
}
TEST_P() [6/11]
TEST_P (SpellProcFullCoverageTest , Level60Reduction_WhenAttributeSet)
{
    // SKIP REASON: This test validates the level 60+ proc chance reduction formula.
    // Only entries with PROC_ATTR_REDUCE_PROC_60 attribute have their proc chance
    // reduced at higher levels. Spells like old weapon procs (Fiery, Crusader)
    // use this to prevent them from being overpowered at level 80.
    // Entries without this attribute maintain constant proc chance at all levels.
    if (!(_entry.AttributesMask & PROC_ATTR_REDUCE_PROC_60))
        GTEST_SKIP() << "SpellId " << _entry.SpellId << " doesn't have REDUCE_PROC_60";
    // Use a meaningful base chance for testing
    float baseChance = _entry.Chance > 0 ? _entry.Chance : 30.0f;
    // Level 60: No reduction
    float chanceAt60 = ProcChanceTestHelper::ApplyLevel60Reduction(baseChance, 60);
    EXPECT_NEAR(chanceAt60, baseChance, 0.01f)
        << "SpellId " << _entry.SpellId << " should have no reduction at level 60";
    // Level 70: 33.33% reduction
    float chanceAt70 = ProcChanceTestHelper::ApplyLevel60Reduction(baseChance, 70);
    float expectedAt70 = baseChance * (1.0f - 10.0f/30.0f);
    EXPECT_NEAR(chanceAt70, expectedAt70, 0.5f)
        << "SpellId " << _entry.SpellId << " should have 33% reduction at level 70";
    // Level 80: 66.67% reduction
    float chanceAt80 = ProcChanceTestHelper::ApplyLevel60Reduction(baseChance, 80);
    float expectedAt80 = baseChance * (1.0f - 20.0f/30.0f);
    EXPECT_NEAR(chanceAt80, expectedAt80, 0.5f)
        << "SpellId " << _entry.SpellId << " should have 66% reduction at level 80";
    // Verify reduction is correct
    EXPECT_LT(chanceAt80, chanceAt70)
        << "SpellId " << _entry.SpellId << " chance at 80 should be less than at 70";
    EXPECT_LT(chanceAt70, chanceAt60)
        << "SpellId " << _entry.SpellId << " chance at 70 should be less than at 60";
}
References ProcChanceTestHelper::ApplyLevel60Reduction(), and PROC_ATTR_REDUCE_PROC_60.
TEST_P() [7/11]
TEST_P (SpellProcFullCoverageTest , ProcFlags_NotEmpty)
{
    // Most entries should have proc flags OR spell family filters
    // Skip validation if both are zero (some entries use only SchoolMask)
    if (_entry.ProcFlags == 0 && _entry.SpellFamilyName == 0 && _entry.SchoolMask == 0)
    {
        // This is a potential configuration issue, but not necessarily an error
        // Some entries are passive effects that don't proc from events
    }
    // Just verify ProcFlags is valid (no invalid bits)
    // All valid proc flags are defined in SpellMgr.h
    // This is a basic sanity check
}
TEST_P() [8/11]
TEST_P (SpellProcFullCoverageTest , ReqManaCost_FlagSet)
{
    // SKIP REASON: This test validates the PROC_ATTR_REQ_MANA_COST attribute.
    // Only 5 entries require the triggering spell to have a mana cost.
    // This prevents free spells (instant casts with no cost) from triggering procs.
    // Example: Illumination should only proc from actual heals, not free procs.
    // 864 entries don't care about mana cost, so this test is skipped for them.
    if (!(_entry.AttributesMask & PROC_ATTR_REQ_MANA_COST))
        GTEST_SKIP() << "SpellId " << _entry.SpellId << " doesn't have REQ_MANA_COST";
    // Just verify the flag is properly set in the entry
    EXPECT_TRUE(_procEntry.AttributesMask & PROC_ATTR_REQ_MANA_COST)
        << "SpellId " << _entry.SpellId << " REQ_MANA_COST should be set";
}
References PROC_ATTR_REQ_MANA_COST.
TEST_P() [9/11]
TEST_P (SpellProcFullCoverageTest , SpellId_NonZero)
{
    // SpellId should never be zero
    EXPECT_NE(_entry.SpellId, 0)
        << "Entry has zero SpellId which is invalid";
}
TEST_P() [10/11]
TEST_P (SpellProcFullCoverageTest , TriggeredCanProc_FlagSet)
{
    // SKIP REASON: This test validates the PROC_ATTR_TRIGGERED_CAN_PROC attribute.
    // Most proc auras (796 entries) do NOT allow triggered spells to trigger them,
    // preventing infinite proc chains. Only 73 entries explicitly allow triggered
    // spells to proc (e.g., some talent effects that should chain-react).
    // Entries without this flag block triggered spell procs for safety.
    if (!(_entry.AttributesMask & PROC_ATTR_TRIGGERED_CAN_PROC))
        GTEST_SKIP() << "SpellId " << _entry.SpellId << " doesn't have TRIGGERED_CAN_PROC";
    // Just verify the flag is properly set in the entry
    EXPECT_TRUE(_procEntry.AttributesMask & PROC_ATTR_TRIGGERED_CAN_PROC)
        << "SpellId " << _entry.SpellId << " TRIGGERED_CAN_PROC should be set";
}
References PROC_ATTR_TRIGGERED_CAN_PROC.
TEST_P() [11/11]
TEST_P (SpellProcFullCoverageTest , UseStacksForCharges_Behavior)
{
    // SKIP REASON: This test validates stack consumption instead of charge consumption.
    // Currently 0 entries use PROC_ATTR_USE_STACKS_FOR_CHARGES (attribute data may
    // need population). When set, this causes procs to decrement the aura's stack
    // count rather than its charge count.
    // Example: Druid's Eclipse - each proc reduces stacks until buff expires.
    // Most proc auras use charges (consumed individually) not stacks.
    if (!(_entry.AttributesMask & PROC_ATTR_USE_STACKS_FOR_CHARGES))
        GTEST_SKIP() << "SpellId " << _entry.SpellId << " doesn't use stacks for charges";
    auto aura = AuraStubBuilder()
        .WithId(std::abs(_entry.SpellId))
        .WithStackAmount(5)
        .Build();
    SpellProcEntry testEntry = _procEntry;
    testEntry.Chance = 100.0f;
    // Consume should decrement stacks
    bool removed = ProcChanceTestHelper::SimulateConsumeProcCharges(aura.get(), testEntry);
    EXPECT_EQ(aura->GetStackAmount(), 4)
        << "SpellId " << _entry.SpellId << " should decrement stacks";
    EXPECT_FALSE(removed);
}
References AuraStubBuilder::Build(), SpellProcEntry::Chance, PROC_ATTR_USE_STACKS_FOR_CHARGES, ProcChanceTestHelper::SimulateConsumeProcCharges(), AuraStubBuilder::WithId(), and AuraStubBuilder::WithStackAmount().