AzerothCore Doxygen
npc_toc5_player_vehicle::npc_toc5_player_vehicleAI Struct Reference
Public Member Functions
npc_toc5_player_vehicleAI (Creature *creature)
void Reset () override
void OnCharmed (bool apply) override
Called when unit is charmed.
void PassengerBoarded (Unit *who, int8, bool apply) override
== Fields =======================================
bool BeforeSpellClick (Unit *clicker) override
Public Member Functions inherited from VehicleAI
VehicleAI (Creature *creature)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void MoveInLineOfSight (Unit *) override
void AttackStart (Unit *) override
void OnCharmed (bool apply) override
Called when unit is charmed.
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
int32 VisualizeBoundary (uint32 duration, Unit *owner=nullptr, bool fill=false, bool checkZ=false) const
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Additional Inherited Members
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from VehicleAI
static int32 Permissible (Creature const *creature)
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
npc_toc5_player_vehicleAI()
npc_toc5_player_vehicle::npc_toc5_player_vehicleAI::npc_toc5_player_vehicleAI (Creature * creature) inline
: VehicleAI(creature) { }
Member Function Documentation
BeforeSpellClick()
bool npc_toc5_player_vehicle::npc_toc5_player_vehicleAI::BeforeSpellClick (Unit * clicker) inline override virtual
Reimplemented from CreatureAI.
        {
            if (!clicker->IsPlayer())
                return true;
            if (clicker->IsInDisallowedMountForm())
                clicker->RemoveAurasByType(SPELL_AURA_MOD_SHAPESHIFT);
            if (clicker->HasAura(SPELL_LANCE_EQUIPPED))
                return true;
            WorldPacket data(SMSG_CAST_FAILED, 1 + 4 + 1);
            data << uint8(0); // single cast or multi 2.3 (0/1)
            data << uint32(VEHICLE_SPELL_RIDE_HARDCODED);
            data << uint8(SPELL_FAILED_CUSTOM_ERROR);
            data << uint32(SPELL_CUSTOM_ERROR_MUST_HAVE_LANCE_EQUIPPED);
            clicker->ToPlayer()->GetSession()->SendPacket(&data);
            return false;
        }
References Player::GetSession(), Unit::HasAura(), Unit::IsInDisallowedMountForm(), Object::IsPlayer(), Unit::RemoveAurasByType(), WorldSession::SendPacket(), SMSG_CAST_FAILED, SPELL_AURA_MOD_SHAPESHIFT, SPELL_CUSTOM_ERROR_MUST_HAVE_LANCE_EQUIPPED, SPELL_FAILED_CUSTOM_ERROR, SPELL_LANCE_EQUIPPED, Object::ToPlayer(), and VEHICLE_SPELL_RIDE_HARDCODED.
OnCharmed()
void npc_toc5_player_vehicle::npc_toc5_player_vehicleAI::OnCharmed (bool apply) inline override virtual
Called when unit is charmed.
Reimplemented from CreatureAI.
        {
            if (me->IsDuringRemoveFromWorld())
                return;
            if (apply)
            {
                me->RemoveUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
                me->SetSpeed(MOVE_RUN, 2.0f, false);
                me->CastSpell(me, SPELL_TRAMPLE_AURA, true);
            }
            else
            {
                me->SetUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
                me->StopMoving();
                me->RemoveAura(SPELL_TRAMPLE_AURA);
            }
        }
References Unit::CastSpell(), Unit::IsDuringRemoveFromWorld(), CreatureAI::me, MOVE_RUN, Unit::RemoveAura(), Unit::RemoveUnitFlag(), Unit::SetSpeed(), Unit::SetUnitFlag(), SPELL_TRAMPLE_AURA, Unit::StopMoving(), and UNIT_FLAG_NON_ATTACKABLE.
PassengerBoarded()
void npc_toc5_player_vehicle::npc_toc5_player_vehicleAI::PassengerBoarded (Unit * , int8 , bool) inline override virtual
== Fields =======================================
Reimplemented from CreatureAI.
        {
            if (me->IsDuringRemoveFromWorld())
                return;
            if (!apply)
            {
                me->RemoveAura(SPELL_PLAYER_VEHICLE_DEFEND);
                who->RemoveAura(SPELL_PLAYER_VEHICLE_DEFEND);
                for (uint8 i = 0; i < 3; ++i)
                    who->RemoveAura(SPELL_SHIELD_LEVEL_1_VISUAL + i);
            }
        }
References Unit::IsDuringRemoveFromWorld(), CreatureAI::me, Unit::RemoveAura(), SPELL_PLAYER_VEHICLE_DEFEND, and SPELL_SHIELD_LEVEL_1_VISUAL.
Reset()
void npc_toc5_player_vehicle::npc_toc5_player_vehicleAI::Reset () inline override virtual
Reimplemented from UnitAI.
        {
            me->SetReactState(REACT_PASSIVE);
            me->getHostileRefMgr().setOnlineOfflineState(false);
        }
References Unit::getHostileRefMgr(), CreatureAI::me, REACT_PASSIVE, HostileRefMgr::setOnlineOfflineState(), and Creature::SetReactState().
The documentation for this struct was generated from the following file:
azerothcore-wotlk/src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/boss_grand_champions.cpp