AzerothCore Doxygen
LuaCorpse Namespace Reference
Functions
int GetOwnerGUID (lua_State *L, Corpse *corpse)
int GetGhostTime (lua_State *L, Corpse *corpse)
int GetType (lua_State *L, Corpse *corpse)
int ResetGhostTime (lua_State *, Corpse *corpse)
int SaveToDB (lua_State *, Corpse *corpse)
Function Documentation
GetGhostTime()
int LuaCorpse::GetGhostTime (lua_State * L, Corpse * corpse)
Returns the time when the [Player] became a ghost and spawned this [Corpse].
Returns
uint32 ghostTime
    {
        Eluna::Push(L, corpse->GetGhostTime());
        return 1;
    }
References Corpse::GetGhostTime(), and Eluna::Push().
GetOwnerGUID()
int LuaCorpse::GetOwnerGUID (lua_State * L, Corpse * corpse)
Returns the GUID of the [Player] that left the [Corpse] behind.
Returns
ObjectGuid ownerGUID
    {
#if defined TRINITY || AZEROTHCORE
        Eluna::Push(L, corpse->GetOwnerGUID());
#else
        Eluna::Push(L, corpse->GetOwnerGuid());
#endif
        return 1;
    }
References Corpse::GetOwnerGUID(), and Eluna::Push().
GetType()
int LuaCorpse::GetType (lua_State * L, Corpse * corpse)
Returns the [CorpseType] of a [Corpse].
enum CorpseType
{
    CORPSE_BONES             = 0,
    CORPSE_RESURRECTABLE_PVE = 1,
    CORPSE_RESURRECTABLE_PVP = 2
};
Returns
[CorpseType] corpseType
    {
        Eluna::Push(L, corpse->GetType());
        return 1;
    }
References Corpse::GetType(), and Eluna::Push().
ResetGhostTime()
int LuaCorpse::ResetGhostTime (lua_State * , Corpse * corpse)
Sets the "ghost time" to the current time.
See [Corpse:GetGhostTime].
    {
        corpse->ResetGhostTime();
        return 0;
    }
References Corpse::ResetGhostTime().
SaveToDB()
int LuaCorpse::SaveToDB (lua_State * , Corpse * corpse)
Saves the [Corpse] to the database.
    {
        corpse->SaveToDB();
        return 0;
    }
References Corpse::SaveToDB().