AzerothCore Doxygen
PreparedStatementBase Class Reference
#include "PreparedStatement.h"
Public Member Functions
PreparedStatementBase (uint32 index, uint8 capacity)
virtual ~PreparedStatementBase ()
template<typename T >
Acore::Types::is_default< T > SetData (const uint8 index, T value)
template<typename T >
Acore::Types::is_enum_v< T > SetData (const uint8 index, T value)
void SetData (const uint8 index, std::string_view value)
void SetData (const uint8 index, std::nullptr_t=nullptr)
template<std::size_t Size>
void SetData (const uint8 index, std::array< uint8, Size > const &value)
template<class _Rep , class _Period >
void SetData (const uint8 index, std::chrono::duration< _Rep, _Period > const &value, bool convertToUin32=true)
template<typename... Args>
void SetArguments (Args &&... args)
uint32 GetIndex () const
std::vector< PreparedStatementData > const & GetParameters () const
Protected Member Functions
template<typename T >
Acore::Types::is_non_string_view_v< T > SetValidData (const uint8 index, T const &value)
void SetValidData (const uint8 index)
void SetValidData (const uint8 index, std::string_view value)
template<typename... Ts>
void SetDataTuple (std::tuple< Ts... > const &argsList)
PreparedStatementBase (PreparedStatementBase const &right)=delete
PreparedStatementBase & operator= (PreparedStatementBase const &right)=delete
Protected Attributes
uint32 m_index
std::vector< PreparedStatementData > statement_data
Friends
class PreparedStatementTask
Detailed Description
Constructor & Destructor Documentation
PreparedStatementBase() [1/2]
PreparedStatementBase::PreparedStatementBase (uint32 index, uint8 capacity) explicit
                                                                         :
    m_index(index),
    statement_data(capacity) { }
~PreparedStatementBase()
PreparedStatementBase::~PreparedStatementBase () virtual
{ }
PreparedStatementBase() [2/2]
PreparedStatementBase::PreparedStatementBase (PreparedStatementBase const & right) protected delete
Member Function Documentation
GetIndex()
uint32 PreparedStatementBase::GetIndex () const inline
{ return m_index; }
Referenced by MySQLConnection::_Query(), MySQLPreparedStatement::AssertValidIndex(), MySQLPreparedStatement::BindParameters(), and MySQLConnection::Execute().
GetParameters()
std::vector< PreparedStatementData > const & PreparedStatementBase::GetParameters () const inline
{ return statement_data; }
Referenced by MySQLPreparedStatement::BindParameters(), and MySQLPreparedStatement::getQueryString().
operator=()
PreparedStatementBase & PreparedStatementBase::operator= (PreparedStatementBase const & right) protected delete
SetArguments()
template<typename... Args> void PreparedStatementBase::SetArguments (Args &&... args) inline
    {
        SetDataTuple(std::make_tuple(std::forward<Args>(args)...));
    }
Referenced by Player::_SaveSeasonalQuestStatus(), and wp_commandscript::HandleWpShowCommand().
SetData() [1/6]
template<std::size_t Size> void PreparedStatementBase::SetData (const uint8 index, std::array< uint8, Size > const & value) inline
    {
        std::vector<uint8> vec(value.begin(), value.end());
        SetValidData(index, vec);
    }
SetData() [2/6]
template<class _Rep , class _Period > void PreparedStatementBase::SetData (const uint8 index, std::chrono::duration< _Rep, _Period > const & value, bool convertToUin32 = true) inline
    {
        SetValidData(index, convertToUin32 ? static_cast<uint32>(value.count()) : value.count());
    }
SetData() [3/6]
void PreparedStatementBase::SetData (const uint8 index, std::nullptr_t = nullptr) inline
    {
        SetValidData(index);
    }
SetData() [4/6]
void PreparedStatementBase::SetData (const uint8 index, std::string_view value) inline
    {
        SetValidData(index, value);
    }
SetData() [5/6]
template<typename T > Acore::Types::is_default< T > PreparedStatementBase::SetData (const uint8 index, T value) inline
    {
        SetValidData(index, value);
    }
Referenced by Guild::_CreateDefaultGuildRanks(), Guild::_CreateNewBankTab(), Guild::_DeleteMemberFromDB(), Player::_LoadBrewOfTheMonth(), Player::_LoadHomeBind(), Player::_LoadItem(), Player::_LoadMailedItem(), Player::_LoadSkills(), Guild::_ModifyBankMoney(), InstanceSaveMgr::_ResetOrWarnAll(), InstanceSaveMgr::_ResetSave(), Player::_SaveActions(), Pet::_SaveAuras(), Player::_SaveAuras(), Player::_SaveCharacter(), Player::_SaveDailyQuestStatus(), Player::_SaveEntryPoint(), Player::_SaveEquipmentSets(), Player::_SaveGlyphs(), Player::_SaveInstanceTimeRestrictions(), Player::_SaveInventory(), Player::_SaveMail(), Player::_SaveMonthlyQuestStatus(), Player::_SaveQuestStatus(), Player::_SaveSeasonalQuestStatus(), Player::_SaveSkills(), Pet::_SaveSpellCooldowns(), Player::_SaveSpellCooldowns(), Pet::_SaveSpells(), Player::_SaveSpells(), Player::_SaveStats(), Player::_SaveTalents(), lfg::LFGMgr::_SaveToDB(), Player::_SaveWeeklyQuestStatus(), Guild::_SetLeaderGUID(), World::_UpdateRealmCharCount(), AppenderDB::_write(), AccountActionIpLogger::AccountIPLogAction(), Player::ActivateSpec(), Channel::AddChannelBanToDB(), ObjectMgr::AddGameTele(), Graveyard::AddGraveyardLink(), Guild::AddMember(), ArenaTeam::AddMember(), Group::AddMember(), LootItemStorage::AddNewStoredLoot(), ObjectMgr::AddProfanityPlayerName(), ObjectMgr::AddReservedPlayerName(), Pet::addSpell(), PlayerSocial::AddToSocialList(), ObjectMgr::AddVendorItem(), BanMgr::BanAccount(), BanMgr::BanAccountByPlayerName(), BanMgr::BanCharacter(), BanMgr::BanIP(), AccountMgr::ChangeEmail(), Group::ChangeLeader(), Guild::ChangeMemberRank(), Group::ChangeMembersGroup(), AccountMgr::ChangePassword(), Guild::Member::ChangeRank(), AccountMgr::ChangeUsername(), Channel::Channel(), CharacterActionIpLogger::CharacterIPLogAction(), AccountMgr::CheckPassword(), Channel::CleanOldChannelsInDB(), Item::ClearSoulboundTradeable(), AchievementGlobalMgr::CompletedAchievementForOfflinePlayer(), Group::ConvertToLFG(), Group::ConvertToRaid(), ArenaTeam::Create(), Group::Create(), Guild::Create(), AccountMgr::CreateAccount(), Guild::RankInfo::CreateMissingTabsIfNeeded(), Player::Customize(), OPvPCapturePoint::DelCreature(), AccountMgr::DeleteAccount(), Map::DeleteCorpseData(), Creature::DeleteFromDB(), GameObject::DeleteFromDB(), GmTicket::DeleteFromDB(), AuctionEntry::DeleteFromDB(), Item::DeleteFromDB(), Corpse::DeleteFromDB(), Pet::DeleteFromDB(), AchievementMgr::DeleteFromDB(), Player::DeleteFromDB(), Item::DeleteFromInventoryDB(), ObjectMgr::DeleteGameTele(), MailDraft::deleteIncludedItems(), InstanceSaveMgr::DeleteInstanceSavedData(), InstanceSaveMgr::DeleteInstanceSaveIfNeeded(), CharacterDeleteActionIpLogger::DeleteIPLogAction(), Player::DeleteOldCharacters(), Player::DeleteOldRecoveryItems(), Item::DeleteRefundDataFromDB(), Map::DeleteRespawnTimesInDB(), DeleteSpellFromAllPlayers(), ArenaTeam::DelMember(), Player::DestroyItem(), ArenaTeam::Disband(), Guild::Disband(), Group::Disband(), ArenaTeam::Disband(), ArenaTeamMgr::DistributeArenaPoints(), Battleground::EndBattleground(), Arena::EndBattleground(), BGQueueRemoveEvent::Execute(), Player::GetArenaTeamIdFromDB(), AccountMgr::GetCharactersCount(), character_commandscript::GetDeletedCharacterInfoList(), AccountMgr::GetId(), AccountMgr::GetName(), AccountMgr::GetSecurity(), AccountMgr::GetSecurity(), Player::GetZoneIdFromDB(), account_commandscript::HandleAccountAddonCommand(), account_commandscript::HandleAccountCommand(), account_commandscript::HandleAccountLockIpCommand(), account_commandscript::HandleAccountOnlineListCommand(), account_commandscript::HandleAccountSetAddonCommand(), account_commandscript::HandleAccountSetGmLevelCommand(), disable_commandscript::HandleAddDisables(), WorldSession::HandleAuctionPlaceBid(), WorldSocket::HandleAuthSession(), WorldSocket::HandleAuthSessionCallback(), autobroadcast_commandscript::HandleAutobroadcastAddCommand(), autobroadcast_commandscript::HandleAutobroadcastListCommand(), autobroadcast_commandscript::HandleAutobroadcastLocaleCommand(), autobroadcast_commandscript::HandleAutobroadcastRemoveCommand(), ban_commandscript::HandleBanInfoCharacterCommand(), ban_commandscript::HandleBanListAccountCommand(), ban_commandscript::HandleBanListCharacterCommand(), ban_commandscript::HandleBanListIPCommand(), WorldSession::HandleBattleFieldPortOpcode(), WorldSession::HandleBugOpcode(), WorldSession::HandleBuybackItem(), WorldSession::HandleCalendarComplain(), character_commandscript::HandleCharacterChangeFactionCommand(), character_commandscript::HandleCharacterChangeRaceCommand(), character_commandscript::HandleCharacterCustomizeCommand(), character_commandscript::HandleCharacterRenameCommand(), WorldSession::HandleCharCreateOpcode(), WorldSession::HandleCharCustomize(), WorldSession::HandleCharCustomizeCallback(), WorldSession::HandleCharEnumOpcode(), WorldSession::HandleCharFactionOrRaceChange(), WorldSession::HandleCharFactionOrRaceChangeCallback(), WorldSession::HandleCharRenameCallBack(), WorldSession::HandleCharRenameOpcode(), WorldSession::HandleComplainOpcode(), debug_commandscript::HandleDebugFactionChangeCommand(), deserter_commandscript::HandleDeserterAdd(), gobject_commandscript::HandleGameObjectNearCommand(), gear_commandscript::HandleGearStatsCommand(), gm_commandscript::HandleGMListFullCommand(), WorldSession::HandleGMSurveySubmit(), item_commandscript::HandleItemRefundCommand(), item_commandscript::HandleItemRestoreCommand(), item_commandscript::HandleItemRestoreListCommand(), list_commandscript::HandleListItemCommand(), AuthSession::HandleLogonChallenge(), AuthSession::HandleLogonProof(), lookup_commandscript::HandleLookupPlayerAccountCommand(), lookup_commandscript::HandleLookupPlayerEmailCommand(), lookup_commandscript::HandleLookupPlayerIpCommand(), mail_commandscript::HandleMailReturnCommand(), WorldSession::HandleMailReturnToSender(), misc_commandscript::HandleMuteCommand(), misc_commandscript::HandleMuteInfoHelper(), npc_commandscript::HandleNpcAddFormationCommand(), npc_commandscript::HandleNpcAddMoveCommand(), npc_commandscript::HandleNpcMoveCommand(), npc_commandscript::HandleNpcNearCommand(), npc_commandscript::HandleNpcSetFactionIdCommand(), npc_commandscript::HandleNpcSetFlagCommand(), npc_commandscript::HandleNpcSetSpawnTimeCommand(), npc_commandscript::HandleNpcSetWanderDistanceCommand(), WorldSession::HandleOpenItemOpcode(), WorldSession::HandleOpenWrappedItemCallback(), WorldSession::HandlePetitionBuyOpcode(), WorldSession::HandlePetitionRenameOpcode(), WorldSession::HandlePetitionSignOpcode(), WorldSession::HandlePetRename(), misc_commandscript::HandlePInfoCommand(), WorldSession::HandlePlayerLoginFromDB(), quest_commandscript::HandleQuestAdd(), quest_commandscript::HandleQuestComplete(), GameEventMgr::HandleQuestComplete(), quest_commandscript::HandleQuestRemove(), quest_commandscript::HandleQuestReward(), AuthSession::HandleRealmList(), AuthSession::HandleReconnectChallenge(), reload_commandscript::HandleReloadCreatureTemplateCommand(), disable_commandscript::HandleRemoveDisables(), Guild::HandleRemoveRank(), WorldSession::HandleReportLag(), reset_commandscript::HandleResetAllCommand(), reset_commandscript::HandleResetSpellsCommand(), reset_commandscript::HandleResetTalentsCommand(), server_commandscript::HandleServerSetMotdCommand(), Guild::HandleSetInfo(), Guild::HandleSetMOTD(), WorldSession::HandleSetPlayerDeclinedNames(), WorldSession::HandleSetSavedInstanceExtend(), WorldSession::HandleStablePet(), WorldSession::HandleStableSwapPet(), tele_commandscript::HandleTeleNameCommand(), WorldSession::HandleTurnInPetitionOpcode(), misc_commandscript::HandleUnFreezeCommand(), misc_commandscript::HandleUnmuteCommand(), WorldSession::HandleUnstablePet(), misc_commandscript::HandleUnstuckCommand(), WorldSession::HandleWhoisOpcode(), wp_commandscript::HandleWpAddCommand(), wp_commandscript::HandleWpEventCommand(), wp_commandscript::HandleWpLoadCommand(), wp_commandscript::HandleWpModifyCommand(), wp_commandscript::HandleWpShowCommand(), wp_commandscript::HandleWpUnLoadCommand(), WorldSession::HandleWrapItemOpcode(), LoginQueryHolder::Initialize(), AccountInfoQueryHolderPerRealm::Initialize(), InstanceSave::InsertToDB(), Player::LeaveAllArenaTeams(), Player::LeaveBattleground(), AutobroadcastMgr::LoadAutobroadcasts(), AutobroadcastMgr::LoadAutobroadcastsLocalized(), ChannelMgr::LoadChannels(), InstanceSaveMgr::LoadCharacterBinds(), AchievementGlobalMgr::LoadCompletedAchievements(), Map::LoadCorpseData(), ObjectMgr::LoadCreatures(), World::LoadDBAllowedSecurityLevel(), PlayerDumpReader::LoadDump(), rbac::RBACData::LoadFromDB(), Player::LoadFromDB(), Item::LoadFromDB(), AchievementMgr::LoadFromDB(), rbac::RBACData::LoadFromDBAsync(), ObjectMgr::LoadGameobjects(), Group::LoadGroupFromDB(), InstanceScript::LoadInstanceSavedGameobjectStateData(), Guild::BankTab::LoadItemFromDB(), Group::LoadMemberFromDB(), MotdMgr::LoadMotd(), MotdMgr::LoadMotdLocale(), PlayerSettingsStore::LoadPlayerSettings(), Player::LoadPositionFromDB(), AccountMgr::LoadRBAC(), ObjectMgr::LoadReferenceVendor(), Map::LoadRespawnTimes(), Guild::LogHolder< Guild::EventLogEntry >::LogHolder(), WorldSession::LogoutPlayer(), lookup_commandscript::LookupPlayerSearchCommand(), Player::ModifyArenaPoints(), Player::ModifyHonorPoints(), Player::OfflineResurrect(), ServerMailReward::OnPlayerLogin(), PetLoadQueryHolder::PetLoadQueryHolder(), InstanceSaveMgr::PlayerBindToInstance(), InstanceSaveMgr::PlayerUnbindInstance(), PlayerSettingsStore::PrepareReplaceStatement(), AchievementMgr::ProcessOfflineUpdatesQueue(), WorldSession::recoveryItem(), WaypointMgr::ReloadPath(), Player::RemoveAtLoginFlag(), BanMgr::RemoveBanAccount(), BanMgr::RemoveBanAccountByPlayerName(), BanMgr::RemoveBanCharacter(), BanMgr::RemoveBanIP(), Channel::RemoveChannelBanFromDB(), Map::RemoveCreatureRespawnTime(), LootItemStorage::RemoveEntryFromDB(), CalendarMgr::RemoveEvent(), PlayerSocial::RemoveFromSocialList(), Map::RemoveGORespawnTime(), Graveyard::RemoveGraveyardLink(), CalendarMgr::RemoveInvite(), Group::RemoveMember(), Player::RemovePet(), Player::RemovePetitionsAndSigns(), LootItemStorage::RemoveStoredLoot(), ObjectMgr::RemoveVendorItem(), World::ResetEventSeasonalQuests(), ObjectMgr::ReturnOrDeleteOldMails(), rbac::RBACData::RevokePermission(), AddonMgr::SaveAddon(), Map::SaveCreatureRespawnTime(), Player::SaveGoldToDB(), Map::SaveGORespawnTime(), WorldState::SaveHelper(), rbac::RBACData::SavePermission(), Pet::SavePetToDB(), Player::SavePositionInDB(), Player::SavePositionInDB(), PoolMgr::SaveQuestsToDB(), Item::SaveRefundDataToDB(), GameObject::SaveStateToDB(), Corpse::SaveToDB(), InstanceScript::SaveToDB(), ArenaTeam::SaveToDB(), AchievementMgr::SaveToDB(), Item::SaveToDB(), ReputationMgr::SaveToDB(), AuctionEntry::SaveToDB(), Guild::Member::SaveToDB(), Guild::RankInfo::SaveToDB(), GmTicket::SaveToDB(), Guild::EventLogEntry::SaveToDB(), Guild::BankEventLogEntry::SaveToDB(), EmblemInfo::SaveToDB(), Creature::SaveToDB(), GameObject::SaveToDB(), WorldSession::SaveTutorialsData(), GameEventMgr::SaveWorldEventStateToDB(), AuctionHouseMgr::SendAuctionWonMail(), MailDraft::SendMailTo(), MailDraft::SendReturnToSender(), ServerMailMgr::SendServerMail(), WorldSession::SetAccountData(), Guild::RankInfo::SetBankMoneyPerDay(), Guild::RankInfo::SetBankTabSlotsAndRights(), ArenaTeam::SetCaptain(), InstanceScript::SetCompletedEncountersMask(), ObjectMgr::SetCreatureLinkedRespawn(), Group::SetDungeonDifficulty(), PlayerSocial::SetFriendNote(), Group::SetGroupMemberFlag(), Player::SetHomebind(), Guild::BankTab::SetInfo(), World::SetInitialWorldSettings(), Guild::BankTab::SetItem(), ArenaTeam::SetName(), Guild::SetName(), Guild::RankInfo::SetName(), Guild::Member::SetOfficerNote(), Guild::Member::SetPublicNote(), Group::SetRaidDifficulty(), Player::SetRandomWinner(), Guild::RankInfo::SetRights(), Guild::BankTab::SetText(), WorldState::setWorldState(), Player::SpawnCorpseBones(), AuthSession::Start(), WorldSocket::Start(), StartDB(), GameEventMgr::StopEvent(), Player::StoreNewItem(), World::Update(), Player::Update(), AccountMgr::UpdateAccountAccess(), WorldSession::UpdateAccountFlag(), AchievementGlobalMgr::UpdateAchievementCriteriaForOfflinePlayer(), Guild::Member::UpdateBankWithdrawValue(), Channel::UpdateChannelInDB(), Channel::UpdateChannelUseageInDB(), CalendarMgr::UpdateEvent(), CalendarMgr::UpdateInvite(), World::UpdateRealmCharCount(), and Player::UpdateSpecCount().
SetData() [6/6]
template<typename T > Acore::Types::is_enum_v< T > PreparedStatementBase::SetData (const uint8 index, T value) inline
    {
        SetValidData(index, std::underlying_type_t<T>(value));
    }
SetDataTuple()
template<typename... Ts> void PreparedStatementBase::SetDataTuple (std::tuple< Ts... > const & argsList) inline protected
    {
        std::apply
        (
            [this](Ts const&... arguments)
            {
                uint8 index{ 0 };
                ((SetData(index, arguments), index++), ...);
            }, argsList
        );
    }
SetValidData() [1/3]
void PreparedStatementBase::SetValidData (const uint8 index) protected
{
    ASSERT(index < statement_data.size());
    statement_data[index].data.emplace<std::nullptr_t>(nullptr);
}
References ASSERT, and statement_data.
SetValidData() [2/3]
void PreparedStatementBase::SetValidData (const uint8 index, std::string_view value) protected
{
    ASSERT(index < statement_data.size());
    statement_data[index].data.emplace<std::string>(value);
}
References ASSERT, and statement_data.
SetValidData() [3/3]
template<typename T > Acore::Types::is_non_string_view_v< T > PreparedStatementBase::SetValidData (const uint8 index, T const & value) protected
{
    ASSERT(index < statement_data.size());
    statement_data[index].data.emplace<T>(value);
}
References ASSERT, and statement_data.
Friends And Related Symbol Documentation
PreparedStatementTask
friend class PreparedStatementTask friend
Member Data Documentation
m_index
uint32 PreparedStatementBase::m_index protected
statement_data
std::vector<PreparedStatementData> PreparedStatementBase::statement_data protected
Referenced by SetValidData(), SetValidData(), and SetValidData().
The documentation for this class was generated from the following files:
azerothcore-wotlk/src/server/database/Database/PreparedStatement.h
azerothcore-wotlk/src/server/database/Database/PreparedStatement.cpp