AzerothCore Doxygen
BfGraveyard Class Reference
#include "Battlefield.h"
Public Member Functions
BfGraveyard (Battlefield *bf)
virtual ~BfGraveyard ()=default
void GiveControlTo (TeamId team)
TeamId GetControlTeamId () const
float GetDistance (Player *player)
void Initialize (TeamId startControl, uint32 graveyardId)
void SetSpirit (Creature *spirit, TeamId team)
void AddPlayer (ObjectGuid playerGuid)
void RemovePlayer (ObjectGuid playerGuid)
void Resurrect ()
void RelocateDeadPlayers ()
bool HasNpc (ObjectGuid guid)
bool HasPlayer (ObjectGuid guid) const
uint32 GetGraveyardId () const
Protected Attributes
TeamId ControlTeam
uint32 GraveyardId
ObjectGuid SpiritGuide [2]
GuidUnorderedSet ResurrectQueue
Battlefield * Bf
Detailed Description
Constructor & Destructor Documentation
BfGraveyard()
BfGraveyard::BfGraveyard (Battlefield * bf)
                                        :
    ControlTeam(TEAM_NEUTRAL),
    GraveyardId(0),
    Bf(bf)
{
}
~BfGraveyard()
virtual BfGraveyard::~BfGraveyard () virtual default
Member Function Documentation
AddPlayer()
void BfGraveyard::AddPlayer (ObjectGuid playerGuid)
{
    if (!ResurrectQueue.count(playerGuid))
    {
        ResurrectQueue.insert(playerGuid);
        if (Player* player = ObjectAccessor::FindPlayer(playerGuid))
            player->CastSpell(player, SPELL_WAITING_FOR_RESURRECT, true);
    }
}
References ObjectAccessor::FindPlayer(), ResurrectQueue, and SPELL_WAITING_FOR_RESURRECT.
Referenced by Battlefield::AddPlayerToResurrectQueue().
GetControlTeamId()
TeamId BfGraveyard::GetControlTeamId () const inline
{ return ControlTeam; }
References ControlTeam.
GetDistance()
float BfGraveyard::GetDistance (Player * player)
{
    GraveyardStruct const* safeLoc = sGraveyard->GetGraveyard(GraveyardId);
    return player->GetDistance2d(safeLoc->x, safeLoc->y);
}
References WorldObject::GetDistance2d(), GraveyardId, sGraveyard, GraveyardStruct::x, and GraveyardStruct::y.
Referenced by Battlefield::GetClosestGraveyard().
GetGraveyardId()
uint32 BfGraveyard::GetGraveyardId () const inline
{ return GraveyardId; }
References GraveyardId.
Referenced by Battlefield::GetClosestGraveyard().
GiveControlTo()
void BfGraveyard::GiveControlTo (TeamId team)
{
    ControlTeam = team;
    // Teleport to other graveyard, players which were on this graveyard
    RelocateDeadPlayers();
}
References ControlTeam, and RelocateDeadPlayers().
Referenced by WGWorkshop::GiveControlTo(), and WGWorkshop::UpdateGraveyardAndWorkshop().
HasNpc()
bool BfGraveyard::HasNpc (ObjectGuid guid) inline
    {
        if (!SpiritGuide[0] && !SpiritGuide[1])
            return false;
        return (SpiritGuide[0] == guid || SpiritGuide[1] == guid);
    }
References SpiritGuide.
HasPlayer()
bool BfGraveyard::HasPlayer (ObjectGuid guid) const inline
{ return ResurrectQueue.find(guid) != ResurrectQueue.end(); }
References ResurrectQueue.
Initialize()
void BfGraveyard::Initialize (TeamId startControl, uint32 graveyardId)
{
    ControlTeam = startControl;
    GraveyardId = graveyardId;
}
References ControlTeam, and GraveyardId.
Referenced by BattlefieldWG::SetupBattlefield().
RelocateDeadPlayers()
void BfGraveyard::RelocateDeadPlayers ()
{
    GraveyardStruct const* closestGrave = nullptr;
    for (ObjectGuid const& guid : ResurrectQueue)
    {
        Player* player = ObjectAccessor::FindPlayer(guid);
        if (!player)
            continue;
        if (closestGrave)
            player->TeleportTo(player->GetMapId(), closestGrave->x, closestGrave->y, closestGrave->z, player->GetOrientation());
        else
        {
            closestGrave = Bf->GetClosestGraveyard(player);
            if (closestGrave)
                player->TeleportTo(player->GetMapId(), closestGrave->x, closestGrave->y, closestGrave->z, player->GetOrientation());
        }
    }
}
References Bf, ObjectAccessor::FindPlayer(), Battlefield::GetClosestGraveyard(), WorldLocation::GetMapId(), Position::GetOrientation(), ResurrectQueue, Player::TeleportTo(), GraveyardStruct::x, GraveyardStruct::y, and GraveyardStruct::z.
Referenced by GiveControlTo().
RemovePlayer()
void BfGraveyard::RemovePlayer (ObjectGuid playerGuid)
{
    ResurrectQueue.erase(ResurrectQueue.find(playerGuid));
    if (Player* player = ObjectAccessor::FindPlayer(playerGuid))
        player->RemoveAurasDueToSpell(SPELL_WAITING_FOR_RESURRECT);
}
References ObjectAccessor::FindPlayer(), ResurrectQueue, and SPELL_WAITING_FOR_RESURRECT.
Resurrect()
void BfGraveyard::Resurrect ()
{
    if (ResurrectQueue.empty())
        return;
    for (ObjectGuid const& guid : ResurrectQueue)
    {
        // Get player object from his guid
        Player* player = ObjectAccessor::FindPlayer(guid);
        if (!player)
            continue;
        // Check if the player is in world and on the good graveyard
        if (player->IsInWorld())
            if (Unit* spirit = ObjectAccessor::GetCreature(*player, SpiritGuide[ControlTeam]))
                spirit->CastSpell(spirit, SPELL_SPIRIT_HEAL, true);
        // Resurrect player
        player->CastSpell(player, SPELL_RESURRECTION_VISUAL, true);
        player->ResurrectPlayer(1.0f);
        player->CastSpell(player, 6962, true);
        player->CastSpell(player, SPELL_SPIRIT_HEAL_MANA, true);
        player->SpawnCorpseBones(false);
    }
    ResurrectQueue.clear();
}
References Unit::CastSpell(), ControlTeam, ObjectAccessor::FindPlayer(), ObjectAccessor::GetCreature(), Object::IsInWorld(), Player::ResurrectPlayer(), ResurrectQueue, Player::SpawnCorpseBones(), SPELL_RESURRECTION_VISUAL, SPELL_SPIRIT_HEAL, SPELL_SPIRIT_HEAL_MANA, and SpiritGuide.
SetSpirit()
void BfGraveyard::SetSpirit (Creature * spirit, TeamId team)
{
    if (!spirit)
    {
        LOG_ERROR("bg.battlefield", "BfGraveyard::SetSpirit: Invalid Spirit.");
        return;
    }
    SpiritGuide[team] = spirit->GetGUID();
    spirit->SetReactState(REACT_PASSIVE);
}
References Object::GetGUID(), LOG_ERROR, REACT_PASSIVE, Creature::SetReactState(), and SpiritGuide.
Member Data Documentation
Bf
Battlefield* BfGraveyard::Bf protected
Referenced by BfGraveyardWG::BfGraveyardWG(), and RelocateDeadPlayers().
ControlTeam
TeamId BfGraveyard::ControlTeam protected
Referenced by GetControlTeamId(), GiveControlTo(), Initialize(), and Resurrect().
GraveyardId
uint32 BfGraveyard::GraveyardId protected
Referenced by GetDistance(), GetGraveyardId(), and Initialize().
ResurrectQueue
GuidUnorderedSet BfGraveyard::ResurrectQueue protected
Referenced by AddPlayer(), HasPlayer(), RelocateDeadPlayers(), RemovePlayer(), and Resurrect().
SpiritGuide
ObjectGuid BfGraveyard::SpiritGuide[2] protected
Referenced by HasNpc(), Resurrect(), and SetSpirit().
The documentation for this class was generated from the following files:
azerothcore-wotlk/src/server/game/Battlefield/Battlefield.h
azerothcore-wotlk/src/server/game/Battlefield/Battlefield.cpp