AzerothCore Doxygen
httplib Namespace Reference
Namespaces
namespace detail
Classes
class Client
class ClientImpl
class ContentReader
class DataSink
struct MultipartFormData
struct MultipartFormDataProvider
struct Request
struct Response
class Result
class Server
class Stream
class TaskQueue
class ThreadPool
Typedefs
using Headers = std::multimap< std::string, std::string, detail::ci >
using Params = std::multimap< std::string, std::string >
using Match = std::smatch
using Progress = std::function< bool(uint64_t current, uint64_t total)>
using ResponseHandler = std::function< bool(const Response &response)>
using MultipartFormDataItems = std::vector< MultipartFormData >
using MultipartFormDataMap = std::multimap< std::string, MultipartFormData >
using ContentProvider = std::function< bool(size_t offset, size_t length, DataSink &sink)>
using ContentProviderWithoutLength = std::function< bool(size_t offset, DataSink &sink)>
using ContentProviderResourceReleaser = std::function< void(bool success)>
using MultipartFormDataProviderItems = std::vector< MultipartFormDataProvider >
using ContentReceiverWithProgress = std::function< bool(const char *data, size_t data_length, uint64_t offset, uint64_t total_length)>
using ContentReceiver = std::function< bool(const char *data, size_t data_length)>
using MultipartContentHeader = std::function< bool(const MultipartFormData &file)>
using Range = std::pair< ssize_t, ssize_t >
using Ranges = std::vector< Range >
using Logger = std::function< void(const Request &, const Response &)>
using SocketOptions = std::function< void(socket_t sock)>
Enumerations
enum class Error {
Success = 0 ,
Unknown ,
Connection ,
BindIPAddress ,
Read ,
Write ,
ExceedRedirectCount ,
Canceled ,
SSLConnection ,
SSLLoadingCerts ,
SSLServerVerification ,
UnsupportedMultipartBoundaryChars ,
Compression ,
ConnectionTimeout ,
SSLPeerCouldBeClosed_
}
Functions
void default_socket_options (socket_t sock)
const char * status_message (int status)
std::string to_string (const Error error)
std::ostream & operator<< (std::ostream &os, const Error &obj)
std::string hosted_at (const std::string &hostname)
void hosted_at (const std::string &hostname, std::vector< std::string > &addrs)
std::string append_query_params (const std::string &path, const Params &params)
std::pair< std::string, std::string > make_range_header (Ranges ranges)
std::pair< std::string, std::string > make_basic_authentication_header (const std::string &username, const std::string &password, bool is_proxy=false)
std::pair< std::string, std::string > make_bearer_token_authentication_header (const std::string &token, bool is_proxy=false)
Typedef Documentation
ContentProvider
using httplib::ContentProvider = typedef std::function<bool(size_t offset, size_t length, DataSink &sink)>
ContentProviderResourceReleaser
using httplib::ContentProviderResourceReleaser = typedef std::function<void(bool success)>
ContentProviderWithoutLength
using httplib::ContentProviderWithoutLength = typedef std::function<bool(size_t offset, DataSink &sink)>
ContentReceiver
using httplib::ContentReceiver = typedef std::function<bool(const char *data, size_t data_length)>
ContentReceiverWithProgress
using httplib::ContentReceiverWithProgress = typedef std::function<bool(const char *data, size_t data_length, uint64_t offset, uint64_t total_length)>
Headers
using httplib::Headers = typedef std::multimap<std::string, std::string, detail::ci>
Logger
using httplib::Logger = typedef std::function<void(const Request &, const Response &)>
Match
using httplib::Match = typedef std::smatch
MultipartContentHeader
using httplib::MultipartContentHeader = typedef std::function<bool(const MultipartFormData &file)>
MultipartFormDataItems
using httplib::MultipartFormDataItems = typedef std::vector<MultipartFormData>
MultipartFormDataMap
using httplib::MultipartFormDataMap = typedef std::multimap<std::string, MultipartFormData>
MultipartFormDataProviderItems
using httplib::MultipartFormDataProviderItems = typedef std::vector<MultipartFormDataProvider>
Params
using httplib::Params = typedef std::multimap<std::string, std::string>
Progress
using httplib::Progress = typedef std::function<bool(uint64_t current, uint64_t total)>
Range
using httplib::Range = typedef std::pair<ssize_t, ssize_t>
Ranges
using httplib::Ranges = typedef std::vector<Range>
ResponseHandler
using httplib::ResponseHandler = typedef std::function<bool(const Response &response)>
SocketOptions
using httplib::SocketOptions = typedef std::function<void(socket_t sock)>
Enumeration Type Documentation
Error
enum class httplib::Error strong
Enumerator
Success
Unknown
Connection
BindIPAddress
Read
Write
ExceedRedirectCount
Canceled
SSLConnection
SSLLoadingCerts
SSLServerVerification
UnsupportedMultipartBoundaryChars
Compression
ConnectionTimeout
SSLPeerCouldBeClosed_
                 {
  Success = 0,
  Unknown,
  Connection,
  BindIPAddress,
  Read,
  Write,
  ExceedRedirectCount,
  Canceled,
  SSLConnection,
  SSLLoadingCerts,
  SSLServerVerification,
  UnsupportedMultipartBoundaryChars,
  Compression,
  ConnectionTimeout,
  // For internal use only
  SSLPeerCouldBeClosed_,
};
Function Documentation
append_query_params()
std::string httplib::append_query_params (const std::string & path, const Params & params) inline
{
  std::string path_with_query = path;
  const static std::regex re("[^?]+\\?.*");
  auto delm = std::regex_match(path, re) ? '&' : '?';
  path_with_query += delm + detail::params_to_query_str(params);
  return path_with_query;
}
References append_query_params(), and params.
Referenced by append_query_params(), httplib::ClientImpl::Get(), and httplib::ClientImpl::Get().
default_socket_options()
void httplib::default_socket_options (socket_t sock) inline
{
  int yes = 1;
#ifdef _WIN32
  setsockopt(sock, SOL_SOCKET, SO_REUSEADDR,
             reinterpret_cast<const char *>(&yes), sizeof(yes));
  setsockopt(sock, SOL_SOCKET, SO_EXCLUSIVEADDRUSE,
             reinterpret_cast<const char *>(&yes), sizeof(yes));
#else
#ifdef SO_REUSEPORT
  setsockopt(sock, SOL_SOCKET, SO_REUSEPORT,
             reinterpret_cast<const void *>(&yes), sizeof(yes));
#else
  setsockopt(sock, SOL_SOCKET, SO_REUSEADDR,
             reinterpret_cast<const void *>(&yes), sizeof(yes));
#endif
#endif
}
hosted_at() [1/2]
std::string httplib::hosted_at (const std::string & hostname) inline
{
  std::vector<std::string> addrs;
  hosted_at(hostname, addrs);
  if (addrs.empty()) { return std::string(); }
  return addrs[0];
}
References hosted_at().
Referenced by hosted_at(), and hosted_at().
hosted_at() [2/2]
void httplib::hosted_at (const std::string & hostname, std::vector< std::string > & addrs) inline
{
  struct addrinfo hints;
  struct addrinfo *result;
  memset(&hints, 0, sizeof(struct addrinfo));
  hints.ai_family = AF_UNSPEC;
  hints.ai_socktype = SOCK_STREAM;
  hints.ai_protocol = 0;
  if (getaddrinfo(hostname.c_str(), nullptr, &hints, &result)) {
#if defined __linux__ && !defined __ANDROID__
    res_init();
#endif
    return;
  }
  for (auto rp = result; rp; rp = rp->ai_next) {
    const auto &addr =
        *reinterpret_cast<struct sockaddr_storage *>(rp->ai_addr);
    std::string ip;
    auto dummy = -1;
    if (detail::get_ip_and_port(addr, sizeof(struct sockaddr_storage), ip,
                                dummy)) {
      addrs.push_back(ip);
    }
  }
  freeaddrinfo(result);
}
References hosted_at().
make_basic_authentication_header()
std::pair< std::string, std::string > httplib::make_basic_authentication_header (const std::string & username, const std::string & password, bool is_proxy = false) inline
{
  auto field = "Basic " + detail::base64_encode(username + ":" + password);
  auto key = is_proxy ? "Proxy-Authorization" : "Authorization";
  return std::make_pair(key, std::move(field));
}
References make_basic_authentication_header().
Referenced by make_basic_authentication_header(), and httplib::ClientImpl::write_request().
make_bearer_token_authentication_header()
std::pair< std::string, std::string > httplib::make_bearer_token_authentication_header (const std::string & token, bool is_proxy = false) inline
{
  auto field = "Bearer " + token;
  auto key = is_proxy ? "Proxy-Authorization" : "Authorization";
  return std::make_pair(key, std::move(field));
}
References make_bearer_token_authentication_header().
Referenced by make_bearer_token_authentication_header(), and httplib::ClientImpl::write_request().
make_range_header()
std::pair< std::string, std::string > httplib::make_range_header (Ranges ranges) inline
{
  std::string field = "bytes=";
  auto i = 0;
  for (auto r : ranges) {
    if (i != 0) { field += ", "; }
    if (r.first != -1) { field += std::to_string(r.first); }
    field += '-';
    if (r.second != -1) { field += std::to_string(r.second); }
    i++;
  }
  return std::make_pair("Range", std::move(field));
}
References make_range_header().
Referenced by make_range_header().
operator<<()
std::ostream & httplib::operator<< (std::ostream & os, const Error & obj) inline
{
  os << to_string(obj);
  os << " (" << static_cast<std::underlying_type<Error>::type>(obj) << ')';
  return os;
}
References to_string().
status_message()
const char * httplib::status_message (int status) inline
{
  switch (status) {
  case 100: return "Continue";
  case 101: return "Switching Protocol";
  case 102: return "Processing";
  case 103: return "Early Hints";
  case 200: return "OK";
  case 201: return "Created";
  case 202: return "Accepted";
  case 203: return "Non-Authoritative Information";
  case 204: return "No Content";
  case 205: return "Reset Content";
  case 206: return "Partial Content";
  case 207: return "Multi-Status";
  case 208: return "Already Reported";
  case 226: return "IM Used";
  case 300: return "Multiple Choice";
  case 301: return "Moved Permanently";
  case 302: return "Found";
  case 303: return "See Other";
  case 304: return "Not Modified";
  case 305: return "Use Proxy";
  case 306: return "unused";
  case 307: return "Temporary Redirect";
  case 308: return "Permanent Redirect";
  case 400: return "Bad Request";
  case 401: return "Unauthorized";
  case 402: return "Payment Required";
  case 403: return "Forbidden";
  case 404: return "Not Found";
  case 405: return "Method Not Allowed";
  case 406: return "Not Acceptable";
  case 407: return "Proxy Authentication Required";
  case 408: return "Request Timeout";
  case 409: return "Conflict";
  case 410: return "Gone";
  case 411: return "Length Required";
  case 412: return "Precondition Failed";
  case 413: return "Payload Too Large";
  case 414: return "URI Too Long";
  case 415: return "Unsupported Media Type";
  case 416: return "Range Not Satisfiable";
  case 417: return "Expectation Failed";
  case 418: return "I'm a teapot";
  case 421: return "Misdirected Request";
  case 422: return "Unprocessable Entity";
  case 423: return "Locked";
  case 424: return "Failed Dependency";
  case 425: return "Too Early";
  case 426: return "Upgrade Required";
  case 428: return "Precondition Required";
  case 429: return "Too Many Requests";
  case 431: return "Request Header Fields Too Large";
  case 451: return "Unavailable For Legal Reasons";
  case 501: return "Not Implemented";
  case 502: return "Bad Gateway";
  case 503: return "Service Unavailable";
  case 504: return "Gateway Timeout";
  case 505: return "HTTP Version Not Supported";
  case 506: return "Variant Also Negotiates";
  case 507: return "Insufficient Storage";
  case 508: return "Loop Detected";
  case 510: return "Not Extended";
  case 511: return "Network Authentication Required";
  default:
  case 500: return "Internal Server Error";
  }
}
Referenced by httplib::Server::process_request(), and httplib::Server::write_response_core().
to_string()
std::string httplib::to_string (const Error error) inline
{
  switch (error) {
  case Error::Success: return "Success (no error)";
  case Error::Connection: return "Could not establish connection";
  case Error::BindIPAddress: return "Failed to bind IP address";
  case Error::Read: return "Failed to read connection";
  case Error::Write: return "Failed to write connection";
  case Error::ExceedRedirectCount: return "Maximum redirect count exceeded";
  case Error::Canceled: return "Connection handling canceled";
  case Error::SSLConnection: return "SSL connection failed";
  case Error::SSLLoadingCerts: return "SSL certificate loading failed";
  case Error::SSLServerVerification: return "SSL server verification failed";
  case Error::UnsupportedMultipartBoundaryChars:
    return "Unsupported HTTP multipart boundary characters";
  case Error::Compression: return "Compression failed";
  case Error::ConnectionTimeout: return "Connection timed out";
  case Error::Unknown: return "Unknown";
  default: break;
  }
  return "Invalid";
}
References BindIPAddress, Canceled, Compression, Connection, ConnectionTimeout, ExceedRedirectCount, Read, SSLConnection, SSLLoadingCerts, SSLServerVerification, Success, Unknown, UnsupportedMultipartBoundaryChars, and Write.
Referenced by HttpManager::HttpWorkerThread(), and operator<<().