AzerothCore Doxygen
ProcEventInfoBuilder Class Reference
Builder class for creating ProcEventInfo test instances.
#include "ProcEventInfoHelper.h"
Public Member Functions
ProcEventInfoBuilder ()
ProcEventInfoBuilder & WithActor (Unit *actor)
ProcEventInfoBuilder & WithActionTarget (Unit *target)
ProcEventInfoBuilder & WithProcTarget (Unit *target)
ProcEventInfoBuilder & WithTypeMask (uint32 typeMask)
ProcEventInfoBuilder & WithSpellTypeMask (uint32 spellTypeMask)
ProcEventInfoBuilder & WithSpellPhaseMask (uint32 spellPhaseMask)
ProcEventInfoBuilder & WithHitMask (uint32 hitMask)
ProcEventInfoBuilder & WithSpell (Spell const *spell)
ProcEventInfoBuilder & WithDamageInfo (DamageInfo *damageInfo)
ProcEventInfoBuilder & WithHealInfo (HealInfo *healInfo)
ProcEventInfoBuilder & WithTriggeredByAuraSpell (SpellInfo const *spellInfo)
ProcEventInfoBuilder & WithProcAuraEffectIndex (int8 index)
ProcEventInfo Build ()
Private Attributes
Unit * _actor
Unit * _actionTarget
Unit * _procTarget
uint32 _typeMask
uint32 _spellTypeMask
uint32 _spellPhaseMask
uint32 _hitMask
Spell const * _spell
DamageInfo * _damageInfo
HealInfo * _healInfo
SpellInfo const * _triggeredByAuraSpell
int8 _procAuraEffectIndex
Detailed Description
Builder class for creating ProcEventInfo test instances.
This helper allows easy construction of ProcEventInfo objects for unit testing the proc system without requiring full game objects.
Constructor & Destructor Documentation
ProcEventInfoBuilder()
ProcEventInfoBuilder::ProcEventInfoBuilder () inline
        : _actor(nullptr), _actionTarget(nullptr), _procTarget(nullptr),
          _typeMask(0), _spellTypeMask(0), _spellPhaseMask(0), _hitMask(0),
          _spell(nullptr), _damageInfo(nullptr), _healInfo(nullptr),
          _triggeredByAuraSpell(nullptr), _procAuraEffectIndex(-1) {}
Member Function Documentation
Build()
ProcEventInfo ProcEventInfoBuilder::Build () inline
    {
        return ProcEventInfo(_actor, _actionTarget, _procTarget, _typeMask,
                             _spellTypeMask, _spellPhaseMask, _hitMask,
                             _spell, _damageInfo, _healInfo,
                             _triggeredByAuraSpell, _procAuraEffectIndex);
    }
References _actionTarget, _actor, _damageInfo, _healInfo, _hitMask, _procAuraEffectIndex, _procTarget, _spell, _spellPhaseMask, _spellTypeMask, _triggeredByAuraSpell, and _typeMask.
Referenced by AuraScriptProcTestFixture::CreateEventInfo(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and AuraScriptProcTestFixture::TestCanProc().
WithActionTarget()
ProcEventInfoBuilder & ProcEventInfoBuilder::WithActionTarget (Unit * target) inline
    {
        _actionTarget = target;
        return *this;
    }
References _actionTarget.
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
WithActor()
ProcEventInfoBuilder & ProcEventInfoBuilder::WithActor (Unit * actor) inline
    {
        _actor = actor;
        return *this;
    }
References _actor.
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
WithDamageInfo()
ProcEventInfoBuilder & ProcEventInfoBuilder::WithDamageInfo (DamageInfo * damageInfo) inline
    {
        _damageInfo = damageInfo;
        return *this;
    }
References _damageInfo.
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
WithHealInfo()
ProcEventInfoBuilder & ProcEventInfoBuilder::WithHealInfo (HealInfo * healInfo) inline
    {
        _healInfo = healInfo;
        return *this;
    }
References _healInfo.
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
WithHitMask()
ProcEventInfoBuilder & ProcEventInfoBuilder::WithHitMask (uint32 hitMask) inline
    {
        _hitMask = hitMask;
        return *this;
    }
References _hitMask.
Referenced by ProcScenarioBuilder::Build(), SpellProcDatabaseTest::CreateEventInfo(), AuraScriptProcTestFixture::CreateEventInfo(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and AuraScriptProcTestFixture::TestCanProc().
WithProcAuraEffectIndex()
ProcEventInfoBuilder & ProcEventInfoBuilder::WithProcAuraEffectIndex (int8 index) inline
    {
        _procAuraEffectIndex = index;
        return *this;
    }
References _procAuraEffectIndex.
WithProcTarget()
ProcEventInfoBuilder & ProcEventInfoBuilder::WithProcTarget (Unit * target) inline
    {
        _procTarget = target;
        return *this;
    }
References _procTarget.
WithSpell()
ProcEventInfoBuilder & ProcEventInfoBuilder::WithSpell (Spell const * spell) inline
    {
        _spell = spell;
        return *this;
    }
References _spell.
WithSpellPhaseMask()
ProcEventInfoBuilder & ProcEventInfoBuilder::WithSpellPhaseMask (uint32 spellPhaseMask) inline
    {
        _spellPhaseMask = spellPhaseMask;
        return *this;
    }
References _spellPhaseMask.
Referenced by ProcScenarioBuilder::Build(), SpellProcDatabaseTest::CreateEventInfo(), AuraScriptProcTestFixture::CreateEventInfo(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and AuraScriptProcTestFixture::TestCanProc().
WithSpellTypeMask()
ProcEventInfoBuilder & ProcEventInfoBuilder::WithSpellTypeMask (uint32 spellTypeMask) inline
    {
        _spellTypeMask = spellTypeMask;
        return *this;
    }
References _spellTypeMask, and spellTypeMask.
Referenced by ProcScenarioBuilder::Build(), SpellProcDatabaseTest::CreateEventInfo(), AuraScriptProcTestFixture::CreateEventInfo(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and AuraScriptProcTestFixture::TestCanProc().
WithTriggeredByAuraSpell()
ProcEventInfoBuilder & ProcEventInfoBuilder::WithTriggeredByAuraSpell (SpellInfo const * spellInfo) inline
    {
        _triggeredByAuraSpell = spellInfo;
        return *this;
    }
References _triggeredByAuraSpell.
WithTypeMask()
ProcEventInfoBuilder & ProcEventInfoBuilder::WithTypeMask (uint32 typeMask) inline
    {
        _typeMask = typeMask;
        return *this;
    }
References _typeMask.
Referenced by ProcScenarioBuilder::Build(), SpellProcDatabaseTest::CreateEventInfo(), AuraScriptProcTestFixture::CreateEventInfo(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and AuraScriptProcTestFixture::TestCanProc().
Member Data Documentation
_actionTarget
Unit* ProcEventInfoBuilder::_actionTarget private
Referenced by Build(), and WithActionTarget().
_actor
Unit* ProcEventInfoBuilder::_actor private
Referenced by Build(), and WithActor().
_damageInfo
DamageInfo* ProcEventInfoBuilder::_damageInfo private
Referenced by Build(), and WithDamageInfo().
_healInfo
HealInfo* ProcEventInfoBuilder::_healInfo private
Referenced by Build(), and WithHealInfo().
_hitMask
uint32 ProcEventInfoBuilder::_hitMask private
Referenced by Build(), and WithHitMask().
_procAuraEffectIndex
int8 ProcEventInfoBuilder::_procAuraEffectIndex private
Referenced by Build(), and WithProcAuraEffectIndex().
_procTarget
Unit* ProcEventInfoBuilder::_procTarget private
Referenced by Build(), and WithProcTarget().
_spell
Spell const* ProcEventInfoBuilder::_spell private
Referenced by Build(), and WithSpell().
_spellPhaseMask
uint32 ProcEventInfoBuilder::_spellPhaseMask private
Referenced by Build(), and WithSpellPhaseMask().
_spellTypeMask
uint32 ProcEventInfoBuilder::_spellTypeMask private
Referenced by Build(), and WithSpellTypeMask().
_triggeredByAuraSpell
SpellInfo const* ProcEventInfoBuilder::_triggeredByAuraSpell private
Referenced by Build(), and WithTriggeredByAuraSpell().
_typeMask
uint32 ProcEventInfoBuilder::_typeMask private
Referenced by Build(), and WithTypeMask().
The documentation for this class was generated from the following file:
azerothcore-wotlk/src/test/mocks/ProcEventInfoHelper.h