AzerothCore Doxygen
ElunaObject Class Reference
#include "ElunaTemplate.h"
Public Member Functions
template<typename T >
ElunaObject (T *obj, bool manageMemory)
~ElunaObject ()
void * GetObj () const
bool IsValid () const
bool CanInvalidate () const
const char * GetTypeName () const
void SetObj (void *obj)
void SetValid (bool valid)
void SetValidation (bool invalidate)
void Invalidate ()
Private Attributes
uint64 callstackid
bool _invalidate
void * object
const char * type_name
Detailed Description
Constructor & Destructor Documentation
ElunaObject()
template<typename T > ElunaObject::ElunaObject (T * obj, bool manageMemory)
                                                   : callstackid(1), _invalidate(!manageMemory), object(obj), type_name(ElunaTemplate<T>::tname)
{
    SetValid(true);
}
References SetValid().
~ElunaObject()
ElunaObject::~ElunaObject () inline
    {
    }
Member Function Documentation
CanInvalidate()
bool ElunaObject::CanInvalidate () const inline
{ return _invalidate; }
References _invalidate.
Referenced by Invalidate(), and SetValid().
GetObj()
void * ElunaObject::GetObj () const inline
{ return object; }
References object.
Referenced by ElunaTemplate< T >::Check(), and ElunaTemplate< T >::CollectGarbage().
GetTypeName()
const char * ElunaObject::GetTypeName () const inline
{ return type_name; }
References type_name.
Referenced by Eluna::CHECKTYPE().
Invalidate()
void ElunaObject::Invalidate () inline
    {
        if (CanInvalidate())
            callstackid = 1;
    }
References callstackid, and CanInvalidate().
IsValid()
bool ElunaObject::IsValid () const inline
{ return !callstackid || callstackid == sEluna->GetCallstackId(); }
References callstackid, and sEluna.
Referenced by ElunaTemplate< T >::Check().
SetObj()
void ElunaObject::SetObj (void * obj) inline
    {
        ASSERT(obj);
        object = obj;
        SetValid(true);
    }
References ASSERT, and SetValid().
SetValid()
void ElunaObject::SetValid (bool valid) inline
    {
        ASSERT(!valid || (valid && object));
        if (valid)
            if (CanInvalidate())
                callstackid = sEluna->GetCallstackId();
            else
                callstackid = 0;
        else
            callstackid = 1;
    }
References ASSERT, callstackid, CanInvalidate(), and sEluna.
Referenced by ElunaObject(), and SetObj().
SetValidation()
void ElunaObject::SetValidation (bool invalidate) inline
    {
        _invalidate = invalidate;
    }
References _invalidate.
Referenced by ElunaTemplate< T >::SetInvalidation().
Member Data Documentation
_invalidate
bool ElunaObject::_invalidate private
Referenced by CanInvalidate(), and SetValidation().
callstackid
uint64 ElunaObject::callstackid private
Referenced by Invalidate(), IsValid(), and SetValid().
object
void* ElunaObject::object private
Referenced by GetObj().
type_name
const char* ElunaObject::type_name private
Referenced by GetTypeName().
The documentation for this class was generated from the following file:
mod-eluna/src/LuaEngine/ElunaTemplate.h