AzerothCore Doxygen
npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI Struct Reference
Public Member Functions
npc_high_overlord_saurfang_igbAI (Creature *creature)
void sGossipSelect (Player *, uint32, uint32) override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void EnterEvadeMode (EvadeReason) override
void DoAction (int32 action) override
void SetData (uint32 type, uint32 data) override
void DamageTaken (Unit *, uint32 &damage, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void AttackStart (Unit *victim) override
bool CanAIAttack (Unit const *target) const override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportPlayer (Unit *unit, Position pos)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool IsUniqueTimedEventDone (uint32 id) const
void SetUniqueTimedEventDone (uint32 id)
void ResetUniqueTimedEvent (uint32 id)
void ClearUniqueTimedEventsDone ()
void ScheduleTimedEvent (Milliseconds timerMin, Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0ms, uint32 uniqueId=0)
void ScheduleTimedEvent (Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0ms, uint32 uniqueId=0)
void ScheduleUniqueTimedEvent (Milliseconds timer, std::function< void()> exec, uint32 uniqueId)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
void SetInvincibility (bool apply)
bool IsInvincible () const
void SetAutoAttackAllowed (bool allow)
bool IsAutoAttackAllowed () const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0ms)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void OnSpellCastFinished (SpellInfo const *, SpellFinishReason)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
int32 VisualizeBoundary (uint32 duration, Unit *owner=nullptr, bool fill=false, bool checkZ=false) const
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
virtual void DistancingStarted ()
virtual void DistancingEnded ()
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual void InitializeAI ()
virtual uint32 GetData (uint32) const
virtual void SetGUID (ObjectGuid const &, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage to any victim (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Private Attributes
EventMap _events
PassengerController _controller
InstanceScript * _instance
time_t _firstMageCooldown
time_t _axethrowersYellCooldown
time_t _rocketeersYellCooldown
uint16 checkTimer
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from ScriptedAI
Creature * me
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
npc_high_overlord_saurfang_igbAI()
npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::npc_high_overlord_saurfang_igbAI (Creature * creature) inline
                                                             : ScriptedAI(creature), _instance(creature->GetInstanceScript())
        {
            _events.Reset();
            _controller.ResetSlots(TEAM_HORDE, creature->GetTransport()->ToMotionTransport());
            me->SetRegeneratingHealth(false);
            me->m_CombatDistance = 70.0f;
            _firstMageCooldown = GameTime::GetGameTime().count() + 45;
            _axethrowersYellCooldown = time_t(0);
            _rocketeersYellCooldown = time_t(0);
            checkTimer = 1000;
        }
References _axethrowersYellCooldown, _controller, _events, _firstMageCooldown, _rocketeersYellCooldown, checkTimer, GameTime::GetGameTime(), WorldObject::GetTransport(), Creature::m_CombatDistance, ScriptedAI::me, EventMap::Reset(), PassengerController::ResetSlots(), Creature::SetRegeneratingHealth(), TEAM_HORDE, and GameObject::ToMotionTransport().
Member Function Documentation
AttackStart()
void npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::AttackStart (Unit * victim) inline override virtual
Reimplemented from UnitAI.
        {
            if (victim && me->Attack(victim, true))
            {
                if (victim->GetPositionZ() < 478.0f)
                    me->GetMotionMaster()->MoveChase(victim);
                else
                {
                    float x, y, z, o;
                    me->GetHomePosition(x, y, z, o);
                    me->GetMotionMaster()->MovePoint(0, x, y, z, FORCED_MOVEMENT_NONE, 0.f, false);
                }
            }
        }
References Unit::Attack(), FORCED_MOVEMENT_NONE, Creature::GetHomePosition(), Unit::GetMotionMaster(), Position::GetPositionZ(), ScriptedAI::me, MotionMaster::MoveChase(), and MotionMaster::MovePoint().
CanAIAttack()
bool npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::CanAIAttack (Unit const * target) const inline override virtual
Reimplemented from UnitAI.
        {
            if (_instance->GetBossState(DATA_ICECROWN_GUNSHIP_BATTLE) != IN_PROGRESS)
                return false;
            if (target->GetEntry() == NPC_SKYBREAKER_MARINE || target->GetEntry() == NPC_SKYBREAKER_SERGEANT)
                return target->ToCreature()->GetReactState() != REACT_PASSIVE;
            return target->GetTransport() == me->GetTransport() && target->GetPositionY() < (_instance->GetData(DATA_TEAMID_IN_INSTANCE) == TEAM_HORDE ? 2431.0f : 2025.0f);
        }
References _instance, DATA_ICECROWN_GUNSHIP_BATTLE, DATA_TEAMID_IN_INSTANCE, InstanceScript::GetBossState(), ZoneScript::GetData(), Object::GetEntry(), Position::GetPositionY(), Creature::GetReactState(), WorldObject::GetTransport(), IN_PROGRESS, ScriptedAI::me, NPC_SKYBREAKER_MARINE, NPC_SKYBREAKER_SERGEANT, REACT_PASSIVE, TEAM_HORDE, and Object::ToCreature().
Referenced by UpdateAI().
DamageTaken()
void npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::DamageTaken (Unit * , uint32 & , DamageEffectType , SpellSchoolMask) inline override virtual
Called at any Damage from any attacker (before damage apply)
Note
It use for recalculation damage or special reaction at damage for attack reaction use AttackedBy called for non DOT damage in Unit::DealDamage also
Reimplemented from UnitAI.
        {
            if (me->HealthBelowPctDamaged(65, damage) && !me->HasAura(SPELL_TASTE_OF_BLOOD))
                me->CastSpell(me, SPELL_TASTE_OF_BLOOD, true);
            if (damage >= me->GetHealth())
                damage = me->GetHealth() - 1;
        }
References Unit::CastSpell(), Unit::GetHealth(), Unit::HasAura(), Unit::HealthBelowPctDamaged(), ScriptedAI::me, and SPELL_TASTE_OF_BLOOD.
DoAction()
void npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::DoAction (int32 action) inline override virtual
Reimplemented from UnitAI.
        {
            if (action == ACTION_ENEMY_GUNSHIP_TALK)
            {
                _instance->SetBossState(DATA_ICECROWN_GUNSHIP_BATTLE, IN_PROGRESS);
                me->GetMap()->SetZoneMusic(AREA_ICECROWN_CITADEL, MUSIC_ENCOUNTER);
                if (Creature* muradin = me->FindNearestCreature(NPC_IGB_MURADIN_BRONZEBEARD, 200.0f))
                    muradin->AI()->DoAction(ACTION_SPAWN_ALL_ADDS);
                Talk(SAY_SAURFANG_INTRO_5);
                _events.ScheduleEvent(EVENT_INTRO_H_5, 4s);
                _events.ScheduleEvent(EVENT_INTRO_H_6, 11s);
                _events.ScheduleEvent(EVENT_KEEP_PLAYER_IN_COMBAT, 1ms);
                if (Creature* skybreaker = _instance->GetCreature(DATA_THE_SKYBREAKER))
                    _instance->SendEncounterUnit(ENCOUNTER_FRAME_ENGAGE, skybreaker, 1);
                if (Creature* orgrimsHammer = _instance->GetCreature(DATA_ORGRIMS_HAMMER))
                {
                    _instance->SendEncounterUnit(ENCOUNTER_FRAME_ENGAGE, orgrimsHammer, 2);
                    orgrimsHammer->CastSpell(orgrimsHammer, SPELL_CHECK_FOR_PLAYERS, true);
                }
            }
            else if (action == ACTION_SPAWN_MAGE)
            {
                time_t now = GameTime::GetGameTime().count();
                if (_firstMageCooldown > now)
                    _events.ScheduleEvent(EVENT_SUMMON_MAGE, Seconds(_firstMageCooldown - now));
                else
                    _events.ScheduleEvent(EVENT_SUMMON_MAGE, 1ms);
            }
            else if (action == ACTION_SPAWN_ALL_ADDS)
            {
                _events.ScheduleEvent(EVENT_ADDS, 12s);
                _events.ScheduleEvent(EVENT_CHECK_RIFLEMAN, 13s);
                _events.ScheduleEvent(EVENT_CHECK_MORTAR, 13s);
                if (Is25ManRaid())
                    _controller.SummonCreatures(me, SLOT_MAGE_1, SLOT_MORTAR_4);
                else
                {
                    _controller.SummonCreatures(me, SLOT_MAGE_1, SLOT_MAGE_2);
                    _controller.SummonCreatures(me, SLOT_MORTAR_1, SLOT_MORTAR_2);
                    _controller.SummonCreatures(me, SLOT_RIFLEMAN_1, SLOT_RIFLEMAN_4);
                }
            }
            else if (action == ACTION_EXIT_SHIP)
            {
                G3D::Vector3 points[SaurfangExitPathSize];
                for (uint8 i = 0; i < SaurfangExitPathSize; ++i)
                {
                    points[i].x = SaurfangExitPath[i].GetPositionX();
                    points[i].y = SaurfangExitPath[i].GetPositionY();
                    points[i].z = SaurfangExitPath[i].GetPositionZ();
                }
                Movement::PointsArray path(points, points + SaurfangExitPathSize);
                me->SetWalk(true);
                Movement::MoveSplineInit init(me);
                init.DisableTransportPathTransformations();
                init.MovebyPath(path, 0);
                init.Launch();
                me->DespawnOrUnsummon(18s);
            }
        }
References _controller, _events, _firstMageCooldown, _instance, ACTION_ENEMY_GUNSHIP_TALK, ACTION_EXIT_SHIP, ACTION_SPAWN_ALL_ADDS, ACTION_SPAWN_MAGE, AREA_ICECROWN_CITADEL, DATA_ICECROWN_GUNSHIP_BATTLE, DATA_ORGRIMS_HAMMER, DATA_THE_SKYBREAKER, Creature::DespawnOrUnsummon(), Movement::MoveSplineInit::DisableTransportPathTransformations(), ENCOUNTER_FRAME_ENGAGE, EVENT_ADDS, EVENT_CHECK_MORTAR, EVENT_CHECK_RIFLEMAN, EVENT_INTRO_H_5, EVENT_INTRO_H_6, EVENT_KEEP_PLAYER_IN_COMBAT, EVENT_SUMMON_MAGE, WorldObject::FindNearestCreature(), InstanceScript::GetCreature(), GameTime::GetGameTime(), WorldObject::GetMap(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), IN_PROGRESS, ScriptedAI::Is25ManRaid(), Movement::MoveSplineInit::Launch(), ScriptedAI::me, Movement::MoveSplineInit::MovebyPath(), MUSIC_ENCOUNTER, NPC_IGB_MURADIN_BRONZEBEARD, SaurfangExitPath, SaurfangExitPathSize, SAY_SAURFANG_INTRO_5, EventMap::ScheduleEvent(), InstanceScript::SendEncounterUnit(), InstanceScript::SetBossState(), Creature::SetWalk(), Map::SetZoneMusic(), SLOT_MAGE_1, SLOT_MAGE_2, SLOT_MORTAR_1, SLOT_MORTAR_2, SLOT_MORTAR_4, SLOT_RIFLEMAN_1, SLOT_RIFLEMAN_4, SPELL_CHECK_FOR_PLAYERS, and PassengerController::SummonCreatures().
EnterEvadeMode()
void npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::EnterEvadeMode (EvadeReason) inline override virtual
Reimplemented from CreatureAI.
        {
            if (!me->IsAlive())
                return;
            me->GetThreatMgr().ClearAllThreat();
            me->CombatStop(true);
            me->GetMotionMaster()->MoveTargetedHome();
            Reset();
        }
References ThreatMgr::ClearAllThreat(), Unit::CombatStop(), Unit::GetMotionMaster(), Unit::GetThreatMgr(), Unit::IsAlive(), ScriptedAI::me, MotionMaster::MoveTargetedHome(), and ScriptedAI::Reset().
JustEngagedWith()
void npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::JustEngagedWith (Unit *) inline override virtual
Called for reaction when initially engaged.
Reimplemented from CreatureAI.
        {
            if (_instance->GetData(DATA_TEAMID_IN_INSTANCE) == TEAM_HORDE && !me->HasAura(SPELL_FRIENDLY_BOSS_DAMAGE_MOD))
                me->CastSpell(me, SPELL_FRIENDLY_BOSS_DAMAGE_MOD, true);
            if (!me->HasAura(SPELL_BATTLE_FURY))
                me->CastSpell(me, SPELL_BATTLE_FURY, true);
            _events.CancelEvent(EVENT_CLEAVE);
            _events.ScheduleEvent(EVENT_CLEAVE, 3s, 6s);
        }
References _events, _instance, EventMap::CancelEvent(), Unit::CastSpell(), DATA_TEAMID_IN_INSTANCE, EVENT_CLEAVE, ZoneScript::GetData(), Unit::HasAura(), ScriptedAI::me, EventMap::ScheduleEvent(), SPELL_BATTLE_FURY, SPELL_FRIENDLY_BOSS_DAMAGE_MOD, and TEAM_HORDE.
SetData()
void npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::SetData (uint32 type, uint32 data) inline override virtual
Reimplemented from UnitAI.
        {
            if (type == ACTION_CLEAR_SLOT)
            {
                _controller.ClearSlot(PassengerSlots(data));
                if (data == SLOT_FREEZE_MAGE)
                    _events.ScheduleEvent(EVENT_SUMMON_MAGE, 30s, 33s + 500ms);
            }
        }
References _controller, _events, ACTION_CLEAR_SLOT, PassengerController::ClearSlot(), EVENT_SUMMON_MAGE, EventMap::ScheduleEvent(), and SLOT_FREEZE_MAGE.
sGossipSelect()
void npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::sGossipSelect (Player * , uint32 , uint32) inline override virtual
Reimplemented from UnitAI.
        {
            if (!me->HasNpcFlag(UNIT_NPC_FLAG_GOSSIP))
                return;
            me->RemoveNpcFlag(UNIT_NPC_FLAG_GOSSIP);
            me->GetTransport()->setActive(true);
            me->GetTransport()->ToMotionTransport()->EnableMovement(true);
            _events.ScheduleEvent(EVENT_INTRO_H_1, 5s);
            _events.ScheduleEvent(EVENT_INTRO_H_2, 16s);
            _events.ScheduleEvent(EVENT_INTRO_SUMMON_SKYBREAKER, 24s + 600ms);
            _events.ScheduleEvent(EVENT_INTRO_H_3, 29s + 600ms);
            _events.ScheduleEvent(EVENT_INTRO_H_4, 39s + 200ms);
        }
References _events, MotionTransport::EnableMovement(), EVENT_INTRO_H_1, EVENT_INTRO_H_2, EVENT_INTRO_H_3, EVENT_INTRO_H_4, EVENT_INTRO_SUMMON_SKYBREAKER, WorldObject::GetTransport(), Unit::HasNpcFlag(), ScriptedAI::me, Unit::RemoveNpcFlag(), EventMap::ScheduleEvent(), WorldObject::setActive(), GameObject::ToMotionTransport(), and UNIT_NPC_FLAG_GOSSIP.
UpdateAI()
void npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Implements UnitAI.
        {
            if (_instance->GetBossState(DATA_ICECROWN_GUNSHIP_BATTLE) == IN_PROGRESS)
            {
                if (me->GetVictim())
                {
                    if (me->GetMotionMaster()->GetCurrentMovementGeneratorType() == CHASE_MOTION_TYPE)
                    {
                        if (me->GetVictim()->GetPositionZ() >= 478.0f)
{
                            float x, y, z, o;
                            me->GetHomePosition(x, y, z, o);
                            me->GetMotionMaster()->MovePoint(0, x, y, z, FORCED_MOVEMENT_NONE, 0.f, false);
                        }
                    }
                    else
                    {
                        if (me->GetVictim()->GetPositionZ() < 478.0f)
                            me->GetMotionMaster()->MoveChase(me->GetVictim());
                    }
                }
                if (checkTimer <= diff)
                {
                    checkTimer = 1000;
                    Map::PlayerList const& pl = me->GetMap()->GetPlayers();
                    for (Map::PlayerList::const_iterator itr = pl.begin(); itr != pl.end(); ++itr)
                        if (Player* p = itr->GetSource())
                            if (CanAIAttack(p) && me->IsValidAttackTarget(p))
{
                                me->SetInCombatWith(p);
                                p->SetInCombatWith(me);
                                me->AddThreat(p, 0.0f);
                            }
                }
                else
                    checkTimer -= diff;
            }
            UpdateVictim();
            _events.Update(diff);
            switch (_events.ExecuteEvent())
            {
                case 0:
                    break;
                case EVENT_INTRO_H_1:
                    Talk(SAY_SAURFANG_INTRO_1);
                    break;
                case EVENT_INTRO_H_2:
                    Talk(SAY_SAURFANG_INTRO_2);
                    break;
                case EVENT_INTRO_SUMMON_SKYBREAKER:
                    sTransportMgr->CreateTransport(GO_THE_SKYBREAKER_H, 0, me->GetMap());
                    break;
                case EVENT_INTRO_H_3:
                    Talk(SAY_SAURFANG_INTRO_3);
                    break;
                case EVENT_INTRO_H_4:
                    Talk(SAY_SAURFANG_INTRO_4);
                    break;
                case EVENT_INTRO_H_5:
                    if (Creature* muradin = me->FindNearestCreature(NPC_IGB_MURADIN_BRONZEBEARD, 200.0f))
                        muradin->AI()->Talk(SAY_MURADIN_INTRO_H);
                    break;
                case EVENT_INTRO_H_6:
                    Talk(SAY_SAURFANG_INTRO_6);
                    break;
                case EVENT_KEEP_PLAYER_IN_COMBAT:
                    if (_instance->GetBossState(DATA_ICECROWN_GUNSHIP_BATTLE) == IN_PROGRESS)
                    {
                        //_instance->DoCastSpellOnPlayers(SPELL_LOCK_PLAYERS_AND_TAP_CHEST);
                        Map::PlayerList const& pl = me->GetMap()->GetPlayers();
                        for (Map::PlayerList::const_iterator itr = pl.begin(); itr != pl.end(); ++itr)
                            if (Player* p = itr->GetSource())
                                if (!p->IsGameMaster())
                                    p->SetInCombatState(true);
                        _events.ScheduleEvent(EVENT_KEEP_PLAYER_IN_COMBAT, 4s);
                    }
                    break;
                case EVENT_SUMMON_MAGE:
                    Talk(SAY_SAURFANG_MAGES);
                    _controller.SummonCreatures(me, SLOT_FREEZE_MAGE, SLOT_FREEZE_MAGE);
                    break;
                case EVENT_ADDS:
                    Talk(SAY_SAURFANG_ENTER_SKYBREAKER);
                    _controller.SummonCreatures(me, SLOT_MAGE_1, SLOT_MAGE_2);
                    _controller.SummonCreatures(me, SLOT_MARINE_1, Is25ManRaid() ? SLOT_MARINE_4 : SLOT_MARINE_2);
                    _controller.SummonCreatures(me, SLOT_SERGEANT_1, Is25ManRaid() ? SLOT_SERGEANT_2 : SLOT_SERGEANT_1);
                    if (MotionTransport* orgrimsHammer = (me->GetTransport() ? me->GetTransport()->ToMotionTransport() : nullptr))
                    {
                        float x, y, z, o;
                        OrgrimsHammerTeleportPortal.GetPosition(x, y, z, o);
                        orgrimsHammer->CalculatePassengerPosition(x, y, z, &o);
                        me->SummonCreature(NPC_TELEPORT_PORTAL, x, y, z, o, TEMPSUMMON_TIMED_DESPAWN, 21000);
                    }
                    if (Transport* transport = _instance->instance->GetTransport(_instance->GetGuidData(DATA_ICECROWN_GUNSHIP_BATTLE)))
                        if (MotionTransport* skybreaker = transport->ToMotionTransport())
{
                            float x, y, z, o;
                            SkybreakerTeleportExit.GetPosition(x, y, z, o);
                            skybreaker->CalculatePassengerPosition(x, y, z, &o);
                            me->SummonCreature(NPC_TELEPORT_EXIT, x, y, z, o, TEMPSUMMON_TIMED_DESPAWN, 23000);
                        }
                    _events.ScheduleEvent(EVENT_ADDS_BOARD_YELL, 6s);
                    _events.ScheduleEvent(EVENT_ADDS, 1min);
                    break;
                case EVENT_ADDS_BOARD_YELL:
                    if (Creature* muradin = me->FindNearestCreature(NPC_IGB_MURADIN_BRONZEBEARD, 200.0f))
                        muradin->AI()->Talk(SAY_MURADIN_BOARD);
                    break;
                case EVENT_CHECK_RIFLEMAN:
                    if (_controller.SummonCreatures(me, SLOT_RIFLEMAN_1, Is25ManRaid() ? SLOT_RIFLEMAN_8 : SLOT_RIFLEMAN_4))
                    {
                        if (_axethrowersYellCooldown < GameTime::GetGameTime().count())
{
                            Talk(SAY_SAURFANG_AXETHROWERS);
                            _axethrowersYellCooldown = GameTime::GetGameTime().count() + 5;
                        }
                    }
                    _events.ScheduleEvent(EVENT_CHECK_RIFLEMAN, 1500ms);
                    break;
                case EVENT_CHECK_MORTAR:
                    if (_controller.SummonCreatures(me, SLOT_MORTAR_1, Is25ManRaid() ? SLOT_MORTAR_4 : SLOT_MORTAR_2))
                    {
                        if (_rocketeersYellCooldown < GameTime::GetGameTime().count())
{
                            Talk(SAY_SAURFANG_ROCKETEERS);
                            _rocketeersYellCooldown = GameTime::GetGameTime().count() + 5;
                        }
                    }
                    _events.ScheduleEvent(EVENT_CHECK_MORTAR, 1500ms);
                    break;
                case EVENT_CLEAVE:
                    if (me->GetVictim())
                        me->CastSpell(me->GetVictim(), SPELL_CLEAVE, false);
                    _events.ScheduleEvent(EVENT_CLEAVE, 4s, 8s);
                    break;
                default:
                    break;
            }
            if (!me->GetVictim() || me->HasUnitState(UNIT_STATE_CASTING))
                return;
            if (me->IsWithinMeleeRange(me->GetVictim()))
                DoMeleeAttackIfReady();
            else if (me->isAttackReady())
            {
                me->SetOrientation(me->GetAngle(me->GetVictim()));
                me->CastSpell(me->GetVictim(), SPELL_RENDING_THROW, false);
                me->resetAttackTimer();
            }
        }
References _axethrowersYellCooldown, _controller, _events, _instance, _rocketeersYellCooldown, Unit::AddThreat(), MapRefMgr::begin(), CanAIAttack(), Unit::CastSpell(), CHASE_MOTION_TYPE, checkTimer, DATA_ICECROWN_GUNSHIP_BATTLE, UnitAI::DoMeleeAttackIfReady(), MapRefMgr::end(), EVENT_ADDS, EVENT_ADDS_BOARD_YELL, EVENT_CHECK_MORTAR, EVENT_CHECK_RIFLEMAN, EVENT_CLEAVE, EVENT_INTRO_H_1, EVENT_INTRO_H_2, EVENT_INTRO_H_3, EVENT_INTRO_H_4, EVENT_INTRO_H_5, EVENT_INTRO_H_6, EVENT_INTRO_SUMMON_SKYBREAKER, EVENT_KEEP_PLAYER_IN_COMBAT, EVENT_SUMMON_MAGE, EventMap::ExecuteEvent(), WorldObject::FindNearestCreature(), FORCED_MOVEMENT_NONE, Position::GetAngle(), InstanceScript::GetBossState(), MotionMaster::GetCurrentMovementGeneratorType(), GameTime::GetGameTime(), InstanceScript::GetGuidData(), Creature::GetHomePosition(), WorldObject::GetMap(), Unit::GetMotionMaster(), Map::GetPlayers(), Position::GetPosition(), Position::GetPositionZ(), WorldObject::GetTransport(), Map::GetTransport(), Unit::GetVictim(), GO_THE_SKYBREAKER_H, Unit::HasUnitState(), IN_PROGRESS, InstanceScript::instance, ScriptedAI::Is25ManRaid(), Unit::isAttackReady(), Unit::IsValidAttackTarget(), Unit::IsWithinMeleeRange(), ScriptedAI::me, MotionMaster::MoveChase(), MotionMaster::MovePoint(), NPC_IGB_MURADIN_BRONZEBEARD, NPC_TELEPORT_EXIT, NPC_TELEPORT_PORTAL, OrgrimsHammerTeleportPortal, Unit::resetAttackTimer(), SAY_MURADIN_BOARD, SAY_MURADIN_INTRO_H, SAY_SAURFANG_AXETHROWERS, SAY_SAURFANG_ENTER_SKYBREAKER, SAY_SAURFANG_INTRO_1, SAY_SAURFANG_INTRO_2, SAY_SAURFANG_INTRO_3, SAY_SAURFANG_INTRO_4, SAY_SAURFANG_INTRO_6, SAY_SAURFANG_MAGES, SAY_SAURFANG_ROCKETEERS, EventMap::ScheduleEvent(), Unit::SetInCombatWith(), Position::SetOrientation(), SkybreakerTeleportExit, SLOT_FREEZE_MAGE, SLOT_MAGE_1, SLOT_MAGE_2, SLOT_MARINE_1, SLOT_MARINE_2, SLOT_MARINE_4, SLOT_MORTAR_1, SLOT_MORTAR_2, SLOT_MORTAR_4, SLOT_RIFLEMAN_1, SLOT_RIFLEMAN_4, SLOT_RIFLEMAN_8, SLOT_SERGEANT_1, SLOT_SERGEANT_2, SPELL_CLEAVE, SPELL_RENDING_THROW, sTransportMgr, WorldObject::SummonCreature(), PassengerController::SummonCreatures(), TEMPSUMMON_TIMED_DESPAWN, GameObject::ToMotionTransport(), UNIT_STATE_CASTING, EventMap::Update(), and CreatureAI::UpdateVictim().
Member Data Documentation
_axethrowersYellCooldown
time_t npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::_axethrowersYellCooldown private
Referenced by npc_high_overlord_saurfang_igbAI(), and UpdateAI().
_controller
PassengerController npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::_controller private
Referenced by DoAction(), npc_high_overlord_saurfang_igbAI(), SetData(), and UpdateAI().
_events
EventMap npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::_events private
Referenced by DoAction(), JustEngagedWith(), npc_high_overlord_saurfang_igbAI(), SetData(), sGossipSelect(), and UpdateAI().
_firstMageCooldown
time_t npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::_firstMageCooldown private
Referenced by DoAction(), and npc_high_overlord_saurfang_igbAI().
_instance
InstanceScript* npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::_instance private
Referenced by CanAIAttack(), DoAction(), JustEngagedWith(), and UpdateAI().
_rocketeersYellCooldown
time_t npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::_rocketeersYellCooldown private
Referenced by npc_high_overlord_saurfang_igbAI(), and UpdateAI().
checkTimer
uint16 npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::checkTimer private
Referenced by npc_high_overlord_saurfang_igbAI(), and UpdateAI().
The documentation for this struct was generated from the following file:
azerothcore-wotlk/src/server/scripts/Northrend/IcecrownCitadel/boss_icecrown_gunship_battle.cpp