AzerothCore Doxygen
LuaQuery Namespace Reference
Functions
static void CheckFields (lua_State *L, ElunaQuery *result)
int IsNull (lua_State *L, ElunaQuery *result)
int GetColumnCount (lua_State *L, ElunaQuery *result)
int GetRowCount (lua_State *L, ElunaQuery *result)
int GetBool (lua_State *L, ElunaQuery *result)
int GetUInt8 (lua_State *L, ElunaQuery *result)
int GetUInt16 (lua_State *L, ElunaQuery *result)
int GetUInt32 (lua_State *L, ElunaQuery *result)
int GetUInt64 (lua_State *L, ElunaQuery *result)
int GetInt8 (lua_State *L, ElunaQuery *result)
int GetInt16 (lua_State *L, ElunaQuery *result)
int GetInt32 (lua_State *L, ElunaQuery *result)
int GetInt64 (lua_State *L, ElunaQuery *result)
int GetFloat (lua_State *L, ElunaQuery *result)
int GetDouble (lua_State *L, ElunaQuery *result)
int GetString (lua_State *L, ElunaQuery *result)
int NextRow (lua_State *L, ElunaQuery *result)
int GetRow (lua_State *L, ElunaQuery *result)
Function Documentation
CheckFields()
static void LuaQuery::CheckFields (lua_State * L, ElunaQuery * result) static
    {
        uint32 field = Eluna::CHECKVAL<uint32>(L, 2);
        uint32 count = RESULT->GetFieldCount();
        if (field >= count)
        {
            char arr[256];
            snprintf(arr, sizeof(arr), "trying to access invalid field index %u. There are %u fields available and the indexes start from 0", field, count);
            luaL_argerror(L, 2, arr);
        }
    }
References luaL_argerror(), and RESULT.
Referenced by GetBool(), GetDouble(), GetFloat(), GetInt16(), GetInt32(), GetInt64(), GetInt8(), GetString(), GetUInt16(), GetUInt32(), GetUInt64(), GetUInt8(), and IsNull().
GetBool()
int LuaQuery::GetBool (lua_State * L, ElunaQuery * result)
Returns the data in the specified column of the current row, casted to a boolean.
Parameters
uint32 column
Returns
bool data
    {
        uint32 col = Eluna::CHECKVAL<uint32>(L, 2);
        CheckFields(L, result);
        Eluna::Push(L, RESULT->Fetch()[col].Get<bool>());
        return 1;
    }
References CheckFields(), Eluna::Push(), and RESULT.
GetColumnCount()
int LuaQuery::GetColumnCount (lua_State * L, ElunaQuery * result)
Returns the number of columns in the result set.
Returns
uint32 columnCount
    {
        Eluna::Push(L, RESULT->GetFieldCount());
        return 1;
    }
References Eluna::Push(), and RESULT.
GetDouble()
int LuaQuery::GetDouble (lua_State * L, ElunaQuery * result)
Returns the data in the specified column of the current row, casted to a 64-bit floating point value.
Parameters
uint32 column
Returns
double data
    {
        uint32 col = Eluna::CHECKVAL<uint32>(L, 2);
        CheckFields(L, result);
        Eluna::Push(L, RESULT->Fetch()[col].Get<double>());
        return 1;
    }
References CheckFields(), Eluna::Push(), and RESULT.
GetFloat()
int LuaQuery::GetFloat (lua_State * L, ElunaQuery * result)
Returns the data in the specified column of the current row, casted to a 32-bit floating point value.
Parameters
uint32 column
Returns
float data
    {
        uint32 col = Eluna::CHECKVAL<uint32>(L, 2);
        CheckFields(L, result);
        Eluna::Push(L, RESULT->Fetch()[col].Get<float>());
        return 1;
    }
References CheckFields(), Eluna::Push(), and RESULT.
GetInt16()
int LuaQuery::GetInt16 (lua_State * L, ElunaQuery * result)
Returns the data in the specified column of the current row, casted to a signed 16-bit integer.
Parameters
uint32 column
Returns
int16 data
    {
        uint32 col = Eluna::CHECKVAL<uint32>(L, 2);
        CheckFields(L, result);
        Eluna::Push(L, RESULT->Fetch()[col].Get<int16>());
        return 1;
    }
References CheckFields(), Eluna::Push(), and RESULT.
GetInt32()
int LuaQuery::GetInt32 (lua_State * L, ElunaQuery * result)
Returns the data in the specified column of the current row, casted to a signed 32-bit integer.
Parameters
uint32 column
Returns
int32 data
    {
        uint32 col = Eluna::CHECKVAL<uint32>(L, 2);
        CheckFields(L, result);
        Eluna::Push(L, RESULT->Fetch()[col].Get<int32>());
        return 1;
    }
References CheckFields(), Eluna::Push(), and RESULT.
GetInt64()
int LuaQuery::GetInt64 (lua_State * L, ElunaQuery * result)
Returns the data in the specified column of the current row, casted to a signed 64-bit integer.
Parameters
uint32 column
Returns
int64 data
    {
        uint32 col = Eluna::CHECKVAL<uint32>(L, 2);
        CheckFields(L, result);
        Eluna::Push(L, RESULT->Fetch()[col].Get<int64>());
        return 1;
    }
References CheckFields(), Eluna::Push(), and RESULT.
GetInt8()
int LuaQuery::GetInt8 (lua_State * L, ElunaQuery * result)
Returns the data in the specified column of the current row, casted to a signed 8-bit integer.
Parameters
uint32 column
Returns
int8 data
    {
        uint32 col = Eluna::CHECKVAL<uint32>(L, 2);
        CheckFields(L, result);
        Eluna::Push(L, RESULT->Fetch()[col].Get<int8>());
        return 1;
    }
References CheckFields(), Eluna::Push(), and RESULT.
GetRow()
int LuaQuery::GetRow (lua_State * L, ElunaQuery * result)
Returns a table from the current row where keys are field names and values are the row's values.
All numerical values will be numbers and everything else is returned as a string.
For example, the query:
SELECT entry, name FROM creature_template
would result in a table like:
{ entry = 123, name = "some creature name" }
To move to next row use [ElunaQuery:NextRow].
Returns
table rowData : table filled with row columns and data where T[column] = data
    {
        uint32 col = RESULT->GetFieldCount();
        Field* row = RESULT->Fetch();
        lua_createtable(L, 0, col);
        int tbl = lua_gettop(L);
#if !defined TRINITY && !AZEROTHCORE
        const QueryFieldNames& names = RESULT->GetFieldNames();
#endif
        for (uint32 i = 0; i < col; ++i)
        {
#if defined TRINITY || AZEROTHCORE
            Eluna::Push(L, RESULT->GetFieldName(i));
            std::string _str = row[i].Get<std::string>();
            const char* str = _str.c_str();
            if (row[i].IsNull() || !str)
                Eluna::Push(L);
            else
            {
                // MYSQL_TYPE_LONGLONG Interpreted as string for lua
                switch (row[i].GetType())
                {
#if defined TRINITY || AZEROTHCORE
                    case DatabaseFieldTypes::Int8:
                    case DatabaseFieldTypes::Int16:
                    case DatabaseFieldTypes::Int32:
                    case DatabaseFieldTypes::Int64:
                    case DatabaseFieldTypes::Float:
                    case DatabaseFieldTypes::Double:
#else
                    case MYSQL_TYPE_TINY:
                    case MYSQL_TYPE_YEAR:
                    case MYSQL_TYPE_SHORT:
                    case MYSQL_TYPE_INT24:
                    case MYSQL_TYPE_LONG:
                    case MYSQL_TYPE_LONGLONG:
                    case MYSQL_TYPE_BIT:
                    case MYSQL_TYPE_FLOAT:
                    case MYSQL_TYPE_DOUBLE:
                    case MYSQL_TYPE_DECIMAL:
                    case MYSQL_TYPE_NEWDECIMAL:
#endif
                        Eluna::Push(L, strtod(str, NULL));
                        break;
                    default:
                        Eluna::Push(L, str);
                        break;
        }
    }
#else
            Eluna::Push(L, names[i]);
            const char* str = row[i].GetString();
            if (row[i].IsNULL() || !str)
                Eluna::Push(L);
            else
            {
                // MYSQL_TYPE_LONGLONG Interpreted as string for lua
                switch (row[i].GetType())
                {
                    case MYSQL_TYPE_TINY:
                    case MYSQL_TYPE_SHORT:
                    case MYSQL_TYPE_INT24:
                    case MYSQL_TYPE_LONG:
                    case MYSQL_TYPE_FLOAT:
                    case MYSQL_TYPE_DOUBLE:
                        Eluna::Push(L, strtod(str, NULL));
                        break;
                    default:
                        Eluna::Push(L, str);
                        break;
                }
            }
#endif
            lua_rawset(L, tbl);
        }
        lua_settop(L, tbl);
        return 1;
    }
References Double, Float, Field::Get(), Int16, Int32, Int64, Int8, IsNull(), lua_createtable(), lua_gettop(), lua_rawset(), lua_settop(), Eluna::Push(), and RESULT.
GetRowCount()
int LuaQuery::GetRowCount (lua_State * L, ElunaQuery * result)
Returns the number of rows in the result set.
Returns
uint32 rowCount
    {
        if (RESULT->GetRowCount() > (uint32)-1)
            Eluna::Push(L, (uint32)-1);
        else
            Eluna::Push(L, (uint32)(RESULT->GetRowCount()));
        return 1;
    }
References Eluna::Push(), and RESULT.
GetString()
int LuaQuery::GetString (lua_State * L, ElunaQuery * result)
Returns the data in the specified column of the current row, casted to a string.
Parameters
uint32 column
Returns
string data
    {
        uint32 col = Eluna::CHECKVAL<uint32>(L, 2);
        CheckFields(L, result);
        Eluna::Push(L, RESULT->Fetch()[col].Get<std::string>());
        return 1;
    }
References CheckFields(), Eluna::Push(), and RESULT.
GetUInt16()
int LuaQuery::GetUInt16 (lua_State * L, ElunaQuery * result)
Returns the data in the specified column of the current row, casted to an unsigned 16-bit integer.
Parameters
uint32 column
Returns
uint16 data
    {
        uint32 col = Eluna::CHECKVAL<uint32>(L, 2);
        CheckFields(L, result);
        Eluna::Push(L, RESULT->Fetch()[col].Get<uint16>());
        return 1;
    }
References CheckFields(), Eluna::Push(), and RESULT.
GetUInt32()
int LuaQuery::GetUInt32 (lua_State * L, ElunaQuery * result)
Returns the data in the specified column of the current row, casted to an unsigned 32-bit integer.
Parameters
uint32 column
Returns
uint32 data
    {
        uint32 col = Eluna::CHECKVAL<uint32>(L, 2);
        CheckFields(L, result);
        Eluna::Push(L, RESULT->Fetch()[col].Get<uint32>());
        return 1;
    }
References CheckFields(), Eluna::Push(), and RESULT.
GetUInt64()
int LuaQuery::GetUInt64 (lua_State * L, ElunaQuery * result)
Returns the data in the specified column of the current row, casted to an unsigned 64-bit integer.
Parameters
uint32 column
Returns
uint64 data
    {
        uint32 col = Eluna::CHECKVAL<uint32>(L, 2);
        CheckFields(L, result);
        Eluna::Push(L, RESULT->Fetch()[col].Get<uint64>());
        return 1;
    }
References CheckFields(), Eluna::Push(), and RESULT.
GetUInt8()
int LuaQuery::GetUInt8 (lua_State * L, ElunaQuery * result)
Returns the data in the specified column of the current row, casted to an unsigned 8-bit integer.
Parameters
uint32 column
Returns
uint8 data
    {
        uint32 col = Eluna::CHECKVAL<uint32>(L, 2);
        CheckFields(L, result);
        Eluna::Push(L, RESULT->Fetch()[col].Get<uint8>());
        return 1;
    }
References CheckFields(), Eluna::Push(), and RESULT.
IsNull()
int LuaQuery::IsNull (lua_State * L, ElunaQuery * result)
Returns true if the specified column of the current row is NULL, otherwise false.
Parameters
uint32 column
Returns
bool isNull
    {
        uint32 col = Eluna::CHECKVAL<uint32>(L, 2);
        CheckFields(L, result);
#if defined TRINITY || AZEROTHCORE
        Eluna::Push(L, RESULT->Fetch()[col].IsNull());
#else
        Eluna::Push(L, RESULT->Fetch()[col].IsNULL());
#endif
        return 1;
    }
References CheckFields(), Eluna::Push(), and RESULT.
Referenced by GetRow().
NextRow()
int LuaQuery::NextRow (lua_State * L, ElunaQuery * result)
Advances the [ElunaQuery] to the next row in the result set.
Do not call this immediately after a query, or you'll skip the first row.
Returns false if there was no new row, otherwise true.
Returns
bool hadNextRow
    {
        Eluna::Push(L, RESULT->NextRow());
        return 1;
    }
References Eluna::Push(), and RESULT.