AzerothCore Doxygen
instance_ulduar::instance_ulduar_InstanceMapScript Struct Reference
Public Member Functions
instance_ulduar_InstanceMapScript (Map *pMap)
void Initialize () override
void FillInitialWorldStates (WorldPackets::WorldState::InitWorldStates &packet) override
void OnPlayerEnter (Player *player) override
bool IsEncounterInProgress () const override
void ProcessEvent (WorldObject *, uint32 eventId) override
bool SetBossState (uint32 type, EncounterState state) override
void SpawnHodirChests (Difficulty diff, Creature *hodir)
void OnCreatureCreate (Creature *creature) override
void OpenIfDone (uint32 encounter, GameObject *go, GOState state)
GameObject * GetHodirChest (bool hardmode)
void OnGameObjectCreate (GameObject *gameObject) override
void setChestsLootable (uint32 boss)
void SetData (uint32 type, uint32 data) override
ObjectGuid GetGuidData (uint32 data) const override
uint32 GetData (uint32 type) const override
void OnUnitDeath (Unit *unit) override
void ReadSaveDataMore (std::istringstream &data) override
void WriteSaveDataMore (std::ostringstream &data) override
void Update (uint32 diff) override
void SpawnLeviathanEncounterVehicles (uint8 mode)
bool CheckAchievementCriteriaMeet (uint32 criteria_id, Player const *, Unit const *, uint32) override
Public Member Functions inherited from InstanceScript
InstanceScript (Map *map)
~InstanceScript () override
virtual void Load (char const *data)
virtual void CreatureLooted (Creature *, LootType)
virtual std::string GetSaveData ()
void SaveToDB ()
void OnCreatureCreate (Creature *creature) override
void OnCreatureRemove (Creature *creature) override
void OnGameObjectCreate (GameObject *go) override
void OnGameObjectRemove (GameObject *go) override
ObjectGuid GetObjectGuid (uint32 type) const
ObjectGuid GetGuidData (uint32 type) const override
Creature * GetCreature (uint32 type)
GameObject * GetGameObject (uint32 type)
virtual void OnPlayerLeave (Player *)
virtual void OnPlayerAreaUpdate (Player *, uint32, uint32)
virtual void OnPlayerInWaterStateUpdate (Player *, bool)
void HandleGameObject (ObjectGuid guid, bool open, GameObject *go=nullptr)
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
void DoRespawnGameObject (uint32 type)
void DoRespawnCreature (ObjectGuid guid, bool force=false)
void DoRespawnCreature (uint32 type, bool force=false)
void DoUpdateWorldState (uint32 worldstateId, uint32 worldstateValue)
void DoSendNotifyToInstance (char const *format,...)
void DoUpdateAchievementCriteria (AchievementCriteriaTypes type, uint32 miscValue1=0, uint32 miscValue2=0, Unit *unit=nullptr)
void DoStartTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoStopTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoRemoveAurasDueToSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayer (Player *player, uint32 spell, bool includePets, bool includeControlled)
bool ServerAllowsTwoSideGroups ()
EncounterState GetBossState (uint32 id) const
CreatureBoundary const * GetBossBoundary (uint32 id) const
BossInfo const * GetBossInfo (uint32 id) const
uint32 GetPersistentData (uint32 index) const
void StorePersistentData (uint32 index, uint32 data)
virtual bool CheckRequiredBosses (uint32, Player const *=nullptr) const
void SetCompletedEncountersMask (uint32 newMask, bool save)
uint32 GetCompletedEncounterMask () const
void SendEncounterUnit (uint32 type, Unit *unit=nullptr, uint8 param1=0, uint8 param2=0)
uint32 GetEncounterCount () const
void MarkAreaTriggerDone (uint32 id)
void ResetAreaTriggerDone (uint32 id)
bool IsAreaTriggerDone (uint32 id) const
virtual void DoAction (int32)
void DoForAllMinions (uint32 id, std::function< void(Creature *)> exec)
void StoreGameObjectState (ObjectGuid::LowType spawnId, uint8 state)
uint8 GetStoredGameObjectState (ObjectGuid::LowType spawnId) const
void LoadInstanceSavedGameobjectStateData ()
bool IsBossDone (uint32 bossId) const
bool AllBossesDone () const
bool AllBossesDone (std::initializer_list< uint32 > bossIds) const
TeamId GetTeamIdInInstance () const
void SetTeamIdInInstance (TeamId teamId)
bool IsTwoFactionInstance () const
Public Member Functions inherited from ZoneScript
ZoneScript ()
virtual ~ZoneScript ()
virtual uint32 GetCreatureEntry (ObjectGuid::LowType, CreatureData const *data)
virtual uint32 GetGameObjectEntry (ObjectGuid::LowType, uint32 entry)
virtual void OnCreatureEvade (Creature *)
virtual void SetGuidData (uint32, ObjectGuid)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
Public Attributes
uint32 m_watchersMask
uint32 C_of_Ulduar_MASK
int m_difficulty
ObjectGuid m_leviathanVisualTowers [4][2]
ObjectGuid m_RepairSGUID [2]
bool m_leviathanTowers [4]
GuidList _leviathanVehicles
uint32 m_unbrokenAchievement
uint32 m_mageBarrier
ObjectGuid m_RazorscaleHarpoonFireStateGUID [4]
bool hmHodir
Position normalChestPosition = { 1967.152588f, -204.188461f, 432.686951f, 5.50957f }
Position hardChestPosition = { 2035.94600f, -202.084885f, 432.686859f, 3.164077f }
uint32 m_conspeedatoryAttempt
uint32 m_algalonTimer
const Position triggerAncientGatePosition = { 1883.65f, 269.272f, 418.406f }
EventMap _events
bool m_mimironTramUsed
ObjectGuid m_keepersGossipGUID [4]
Public Attributes inherited from InstanceScript
Map * instance
TaskScheduler scheduler
Additional Inherited Members
Static Public Member Functions inherited from InstanceScript
static std::string GetBossStateName (uint8 state)
Protected Member Functions inherited from InstanceScript
void SetHeaders (std::string const &dataHeaders)
void SetBossNumber (uint32 number)
void SetPersistentDataCount (uint32 number)
void LoadBossBoundaries (BossBoundaryData const &data)
void LoadDoorData (DoorData const *data)
void LoadMinionData (MinionData const *data)
void LoadObjectData (ObjectData const *creatureData, ObjectData const *gameObjectData)
void LoadSummonData (ObjectData const *data)
void SetSummoner (Creature *creature)
void AddObject (Creature *obj, bool add=true)
void RemoveObject (Creature *obj)
void AddObject (GameObject *obj, bool add=true)
void RemoveObject (GameObject *obj)
void AddObject (WorldObject *obj, uint32 type, bool add=true)
void RemoveObject (WorldObject *obj, uint32 type)
void AddDoor (GameObject *door, bool add=true)
void RemoveDoor (GameObject *door)
void AddMinion (Creature *minion, bool add=true)
void RemoveMinion (Creature *minion)
void UpdateDoorState (GameObject *door)
void UpdateMinionState (Creature *minion, EncounterState state)
bool ReadSaveDataHeaders (std::istringstream &data)
void ReadSaveDataBossStates (std::istringstream &data)
void ReadSavePersistentData (std::istringstream &data)
void WriteSaveDataHeaders (std::ostringstream &data)
void WriteSaveDataBossStates (std::ostringstream &data)
void WritePersistentData (std::ostringstream &data)
Detailed Description
Constructor & Destructor Documentation
instance_ulduar_InstanceMapScript()
instance_ulduar::instance_ulduar_InstanceMapScript::instance_ulduar_InstanceMapScript (Map * pMap) inline
                                                     : InstanceScript(pMap)
        {
            SetHeaders(DataHeader);
            SetBossNumber(MAX_ENCOUNTER);
            LoadDoorData(doorData);
            LoadObjectData(creatureData, gameobjectData);
            Initialize();
            // 0: 10 man difficulty
            // 1: 25 man difficulty
            m_difficulty = (pMap->Is25ManRaid() ? 0 : 1);
        };
References creatureData, DataHeader, doorData, gameobjectData, Initialize(), Map::Is25ManRaid(), InstanceScript::LoadDoorData(), InstanceScript::LoadObjectData(), m_difficulty, MAX_ENCOUNTER, InstanceScript::SetBossNumber(), and InstanceScript::SetHeaders().
Member Function Documentation
CheckAchievementCriteriaMeet()
bool instance_ulduar::instance_ulduar_InstanceMapScript::CheckAchievementCriteriaMeet (uint32 criteria_id, Player const * , Unit const * , uint32) inline override virtual
Reimplemented from InstanceScript.
        {
            switch (criteria_id)
            {
                case 10042:
                case 10352:
                    return (C_of_Ulduar_MASK & (1 << BOSS_LEVIATHAN)) == 0;
                case 10342:
                case 10355:
                    return (C_of_Ulduar_MASK & (1 << BOSS_IGNIS)) == 0;
                case 10340:
                case 10353:
                    return (C_of_Ulduar_MASK & (1 << BOSS_RAZORSCALE)) == 0;
                case 10341:
                case 10354:
                    return (C_of_Ulduar_MASK & (1 << BOSS_XT002)) == 0;
                case 10598:
                case 10599:
                    return (C_of_Ulduar_MASK & (1 << BOSS_ASSEMBLY)) == 0;
                case 10348:
                case 10357:
                    return (C_of_Ulduar_MASK & (1 << BOSS_KOLOGARN)) == 0;
                case 10351:
                case 10363:
                    return (C_of_Ulduar_MASK & (1 << BOSS_AURIAYA)) == 0;
                case 10439:
                case 10719:
                    return (C_of_Ulduar_MASK & (1 << BOSS_HODIR)) == 0;
                case 10403:
                case 10404:
                    return (C_of_Ulduar_MASK & (1 << BOSS_THORIM)) == 0;
                case 10582:
                case 10583:
                    return (C_of_Ulduar_MASK & (1 << BOSS_FREYA)) == 0;
                case 10347:
                case 10361:
                    return (C_of_Ulduar_MASK & (1 << BOSS_MIMIRON)) == 0;
                case 10349:
                case 10362:
                    return (C_of_Ulduar_MASK & (1 << BOSS_VEZAX)) == 0;
                case 10350:
                case 10364:
                    return (C_of_Ulduar_MASK & (1 << BOSS_YOGGSARON)) == 0;
            }
            return false;
        }
References BOSS_ASSEMBLY, BOSS_AURIAYA, BOSS_FREYA, BOSS_HODIR, BOSS_IGNIS, BOSS_KOLOGARN, BOSS_LEVIATHAN, BOSS_MIMIRON, BOSS_RAZORSCALE, BOSS_THORIM, BOSS_VEZAX, BOSS_XT002, BOSS_YOGGSARON, and C_of_Ulduar_MASK.
FillInitialWorldStates()
void instance_ulduar::instance_ulduar_InstanceMapScript::FillInitialWorldStates (WorldPackets::WorldState::InitWorldStates & packet) inline override virtual
Reimplemented from InstanceScript.
        {
            packet.Worldstates.reserve(2);
            packet.Worldstates.emplace_back(WORLD_STATE_ULDUAR_ALGALON_TIMER_ENABLED, (m_algalonTimer && m_algalonTimer <= 60) ? 1 : 0);
            packet.Worldstates.emplace_back(WORLD_STATE_ULDUAR_ALGALON_DESPAWN_TIMER, std::min<int32>(m_algalonTimer, 60));
        }
References m_algalonTimer, WORLD_STATE_ULDUAR_ALGALON_DESPAWN_TIMER, WORLD_STATE_ULDUAR_ALGALON_TIMER_ENABLED, and WorldPackets::WorldState::InitWorldStates::Worldstates.
GetData()
uint32 instance_ulduar::instance_ulduar_InstanceMapScript::GetData (uint32 type) const inline override virtual
Reimplemented from ZoneScript.
        {
            switch (type)
            {
                case TYPE_WATCHERS:
                    return m_watchersMask;
                case EVENT_TOWER_OF_LIFE_DESTROYED:
                case EVENT_TOWER_OF_STORM_DESTROYED:
                case EVENT_TOWER_OF_FROST_DESTROYED:
                case EVENT_TOWER_OF_FLAMES_DESTROYED:
                    return m_leviathanTowers[type - EVENT_TOWER_OF_LIFE_DESTROYED];
                case DATA_MAGE_BARRIER:
                    return m_mageBarrier;
                case DATA_UNBROKEN_ACHIEVEMENT:
                    return m_unbrokenAchievement;
                case DATA_CALL_TRAM:
                    return m_mimironTramUsed;
            }
            return 0;
        }
References DATA_CALL_TRAM, DATA_MAGE_BARRIER, DATA_UNBROKEN_ACHIEVEMENT, EVENT_TOWER_OF_FLAMES_DESTROYED, EVENT_TOWER_OF_FROST_DESTROYED, EVENT_TOWER_OF_LIFE_DESTROYED, EVENT_TOWER_OF_STORM_DESTROYED, m_leviathanTowers, m_mageBarrier, m_mimironTramUsed, m_unbrokenAchievement, m_watchersMask, and TYPE_WATCHERS.
GetGuidData()
ObjectGuid instance_ulduar::instance_ulduar_InstanceMapScript::GetGuidData (uint32 data) const inline override virtual
Reimplemented from ZoneScript.
        {
            switch (data)
            {
                // Flame Leviathan
                case DATA_REPAIR_STATION1:
                    return m_RepairSGUID[0];
                case DATA_REPAIR_STATION2:
                    return m_RepairSGUID[1];
                // Razorscales Harpoon Fire State GUIDs
                case DATA_HARPOON_FIRE_STATE_1:
                case DATA_HARPOON_FIRE_STATE_2:
                case DATA_HARPOON_FIRE_STATE_3:
                case DATA_HARPOON_FIRE_STATE_4:
                    return m_RazorscaleHarpoonFireStateGUID[data - 200];
            }
            return GetObjectGuid(data);
        }
References DATA_HARPOON_FIRE_STATE_1, DATA_HARPOON_FIRE_STATE_2, DATA_HARPOON_FIRE_STATE_3, DATA_HARPOON_FIRE_STATE_4, DATA_REPAIR_STATION1, DATA_REPAIR_STATION2, InstanceScript::GetObjectGuid(), m_RazorscaleHarpoonFireStateGUID, and m_RepairSGUID.
GetHodirChest()
GameObject * instance_ulduar::instance_ulduar_InstanceMapScript::GetHodirChest (bool hardmode) inline
        {
            if (hardmode)
            {
                if (GameObject* go = GetGameObject(DATA_HODIR_CHEST_HARD))
                    return go;
                return GetGameObject(DATA_HODIR_CHEST_HARD_HERO);
            }
            if (GameObject* go = GetGameObject(DATA_HODIR_CHEST_NORMAL))
                return go;
            return GetGameObject(DATA_HODIR_CHEST_NORMAL_HERO);
        }
References DATA_HODIR_CHEST_HARD, DATA_HODIR_CHEST_HARD_HERO, DATA_HODIR_CHEST_NORMAL, DATA_HODIR_CHEST_NORMAL_HERO, and InstanceScript::GetGameObject().
Referenced by setChestsLootable(), and SetData().
Initialize()
void instance_ulduar::instance_ulduar_InstanceMapScript::Initialize () inline override virtual
Reimplemented from InstanceScript.
        {
            // Bosses
            m_watchersMask = 0;
            C_of_Ulduar_MASK = 0;
            // Flame Leviathan
            for (uint8 i = 0; i < 4; ++i)
                m_leviathanTowers[i] = true;
            _leviathanVehicles.clear();
            m_unbrokenAchievement   = 1;
            m_mageBarrier           = 0;
            // Hodir
            hmHodir = true; // If players fail the Hardmode then becomes false
            // Freya
            m_conspeedatoryAttempt  = 0;
            // Algalon
            m_algalonTimer          = 0;
            // Shared
            _events.Reset();
            m_mimironTramUsed       = false;
        }
References _events, _leviathanVehicles, C_of_Ulduar_MASK, hmHodir, m_algalonTimer, m_conspeedatoryAttempt, m_leviathanTowers, m_mageBarrier, m_mimironTramUsed, m_unbrokenAchievement, m_watchersMask, and EventMap::Reset().
Referenced by instance_ulduar_InstanceMapScript().
IsEncounterInProgress()
bool instance_ulduar::instance_ulduar_InstanceMapScript::IsEncounterInProgress () const inline override virtual
Reimplemented from InstanceScript.
        {
            for (uint8 i = 0; i < MAX_ENCOUNTER; ++i)
            {
                if (GetBossState(i) == IN_PROGRESS)
                    return true;
            }
            // Leviathan does not use IN_PROGRESS type, instead SPECIAL is set and never reset,
            // Check if he is in combat.
            if (Creature* l = instance->GetCreature(GetObjectGuid(BOSS_LEVIATHAN)))
                if (l->IsInCombat())
                    return true;
            return false;
        }
References BOSS_LEVIATHAN, InstanceScript::GetBossState(), Map::GetCreature(), InstanceScript::GetObjectGuid(), IN_PROGRESS, InstanceScript::instance, and MAX_ENCOUNTER.
OnCreatureCreate()
void instance_ulduar::instance_ulduar_InstanceMapScript::OnCreatureCreate (Creature * creature) inline override virtual
These creatures are summoned by something else than Algalon but need to be controlled/despawned by him - so they need to be registered in his summon list
Reimplemented from ZoneScript.
        {
            InstanceScript::OnCreatureCreate(creature);
            switch (creature->GetEntry())
            {
                case NPC_KOLOGARN:
                    if (GetBossState(BOSS_KOLOGARN) == DONE)
                    {
                        creature->SetDisableGravity(true);
                        creature->SetPosition(creature->GetHomePosition());
                        creature->setDeathState(DeathState::JustDied);
                        creature->StopMovingOnCurrentPos();
                    }
                    break;
                case NPC_HODIR:
                    if (GetBossState(BOSS_HODIR) != DONE)
                    {
                        SpawnHodirChests(instance->GetDifficulty(), creature);
                    }
                    break;
                case NPC_ALGALON:
                    if (!m_algalonTimer)
                        creature->DespawnOrUnsummon();
                    break;
                case NPC_HARPOON_FIRE_STATE:
                    {
                        if (creature->GetPositionX() > 595 )
                            m_RazorscaleHarpoonFireStateGUID[3] = creature->GetGUID();
                        else if (creature->GetPositionX() > 585 )
                            m_RazorscaleHarpoonFireStateGUID[2] = creature->GetGUID();
                        else if (creature->GetPositionX() > 575 )
                            m_RazorscaleHarpoonFireStateGUID[1] = creature->GetGUID();
                        else
                            m_RazorscaleHarpoonFireStateGUID[0] = creature->GetGUID();
                    }
                    break;
                case NPC_ALGALON_VOID_ZONE_VISUAL_STALKER:
                case NPC_ALGALON_STALKER_ASTEROID_TARGET_01:
                case NPC_ALGALON_STALKER_ASTEROID_TARGET_02:
                case NPC_UNLEASHED_DARK_MATTER:
                    if (Creature* algalon = GetCreature(BOSS_ALGALON))
                        algalon->AI()->JustSummoned(creature);
                    break;
            }
        }
References BOSS_ALGALON, BOSS_HODIR, BOSS_KOLOGARN, Creature::DespawnOrUnsummon(), DONE, InstanceScript::GetBossState(), InstanceScript::GetCreature(), Map::GetDifficulty(), Object::GetEntry(), Object::GetGUID(), Creature::GetHomePosition(), Position::GetPositionX(), InstanceScript::instance, JustDied, m_algalonTimer, m_RazorscaleHarpoonFireStateGUID, NPC_ALGALON, NPC_ALGALON_STALKER_ASTEROID_TARGET_01, NPC_ALGALON_STALKER_ASTEROID_TARGET_02, NPC_ALGALON_VOID_ZONE_VISUAL_STALKER, NPC_HARPOON_FIRE_STATE, NPC_HODIR, NPC_KOLOGARN, NPC_UNLEASHED_DARK_MATTER, InstanceScript::OnCreatureCreate(), Creature::setDeathState(), Unit::SetDisableGravity(), Creature::SetPosition(), SpawnHodirChests(), and Unit::StopMovingOnCurrentPos().
OnGameObjectCreate()
void instance_ulduar::instance_ulduar_InstanceMapScript::OnGameObjectCreate (GameObject * gameObject) inline override virtual
Reimplemented from ZoneScript.
        {
            InstanceScript::OnGameObjectCreate(gameObject);
            switch (gameObject->GetEntry())
            {
                // Flame Leviathan
                case GO_REPAIR_STATION_TRAP:
                    {
                        if (m_RepairSGUID[0])
                            m_RepairSGUID[1] = gameObject->GetGUID();
                        else
                            m_RepairSGUID[0] = gameObject->GetGUID();
                        break;
                    }
                case GO_LIGHTNING_WALL1:
                    OpenIfDone(BOSS_LEVIATHAN, gameObject, GO_STATE_ACTIVE);
                    break;
                case GO_MIMIRONS_TARGETTING_CRYSTAL:
                    OpenIfDone(BOSS_LEVIATHAN, gameObject, GO_STATE_ACTIVE);
                    m_leviathanVisualTowers[3][0] = gameObject->GetGUID();
                    break;
                case GO_FREYAS_TARGETTING_CRYSTAL:
                    OpenIfDone(BOSS_LEVIATHAN, gameObject, GO_STATE_ACTIVE);
                    m_leviathanVisualTowers[0][0] = gameObject->GetGUID();
                    break;
                case GO_HODIRS_TARGETTING_CRYSTAL:
                    OpenIfDone(BOSS_LEVIATHAN, gameObject, GO_STATE_ACTIVE);
                    m_leviathanVisualTowers[2][0] = gameObject->GetGUID();
                    break;
                case GO_THORIMS_TARGETTING_CRYSTAL:
                    OpenIfDone(BOSS_LEVIATHAN, gameObject, GO_STATE_ACTIVE);
                    m_leviathanVisualTowers[1][0] = gameObject->GetGUID();
                    break;
                case GO_MIMIRONS_GENERATOR:
                    OpenIfDone(BOSS_LEVIATHAN, gameObject, GO_STATE_ACTIVE);
                    m_leviathanVisualTowers[3][1] = gameObject->GetGUID();
                    break;
                case GO_FREYAS_GENERATOR:
                    OpenIfDone(BOSS_LEVIATHAN, gameObject, GO_STATE_ACTIVE);
                    m_leviathanVisualTowers[0][1] = gameObject->GetGUID();
                    break;
                case GO_HODIRS_GENERATOR:
                    OpenIfDone(BOSS_LEVIATHAN, gameObject, GO_STATE_ACTIVE);
                    m_leviathanVisualTowers[2][1] = gameObject->GetGUID();
                    break;
                case GO_THORIMS_GENERATOR:
                    OpenIfDone(BOSS_LEVIATHAN, gameObject, GO_STATE_ACTIVE);
                    m_leviathanVisualTowers[1][1] = gameObject->GetGUID();
                    break;
                case GO_LEVIATHAN_DOORS:
                    if (GetBossState(BOSS_LEVIATHAN) >= DONE)
                        gameObject->SetGoState(GO_STATE_ACTIVE_ALTERNATIVE);
                    break;
                case GO_KOLOGARN_BRIDGE:
                    OpenIfDone(BOSS_KOLOGARN, gameObject, GO_STATE_READY);
                    break;
                case GO_ARCHIVUM_DOORS:
                    OpenIfDone(BOSS_ASSEMBLY, gameObject, GO_STATE_ACTIVE);
                    break;
                case GO_KEEPERS_GATE:
                    if (GetBossState(BOSS_MIMIRON) == DONE && GetBossState(BOSS_FREYA) == DONE && GetBossState(BOSS_HODIR) == DONE && GetBossState(BOSS_THORIM) == DONE)
                        gameObject->RemoveGameObjectFlag(GO_FLAG_LOCKED);
                    break;
                // Mimiron, Hodir, Vezax
                case GO_MIMIRON_ELEVATOR:
                    gameObject->EnableCollision(false);
                    break;
                case GO_HODIR_FROZEN_DOOR:
                case GO_HODIR_DOOR:
                    if (GetBossState(BOSS_HODIR) == DONE)
                        if (gameObject->GetGoState() != GO_STATE_ACTIVE )
{
                            gameObject->SetLootState(GO_READY);
                            gameObject->UseDoorOrButton(0, false);
                        }
                    break;
                case GO_VEZAX_DOOR:
                    if (GetBossState(BOSS_VEZAX) == DONE )
                        if (gameObject->GetGoState() != GO_STATE_ACTIVE )
{
                            gameObject->SetLootState(GO_READY);
                            gameObject->UseDoorOrButton(0, false);
                        }
                    break;
                case GO_SNOW_MOUND:
                    gameObject->EnableCollision(false);
                    break;
                // Mimiron Tram
                case GO_MIMIRON_TRAM:
                    if (GetBossState(BOSS_MIMIRON) == DONE)
                        m_mimironTramUsed = true;
                    break;
                // Algalon the Observer
                case GO_CELESTIAL_PLANETARIUM_ACCESS_10:
                case GO_CELESTIAL_PLANETARIUM_ACCESS_25:
                    if (m_algalonTimer)
                        gameObject->SetGameObjectFlag(GO_FLAG_IN_USE);
                    break;
                case GO_DOODAD_UL_SIGILDOOR_01:
                    if (m_algalonTimer)
                        gameObject->SetGoState(GO_STATE_ACTIVE);
                    break;
                case GO_DOODAD_UL_SIGILDOOR_02:
                    if (m_algalonTimer)
                        gameObject->SetGoState(GO_STATE_ACTIVE);
                    break;
                // Herbs
                case 191019: // Adder's Tongue
                case 190176: // Frost Lotus
                case 190171: // Lichbloom
                case 190170: // Talandra's Rose
                case 189973: // Goldclover
                    if (GetBossState(BOSS_FREYA) == DONE)
                        gameObject->SetRespawnTime(7 * DAY);
                    break;
            }
        }
References BOSS_ASSEMBLY, BOSS_FREYA, BOSS_HODIR, BOSS_KOLOGARN, BOSS_LEVIATHAN, BOSS_MIMIRON, BOSS_THORIM, BOSS_VEZAX, DAY, DONE, GameObject::EnableCollision(), InstanceScript::GetBossState(), Object::GetEntry(), GameObject::GetGoState(), Object::GetGUID(), GO_ARCHIVUM_DOORS, GO_CELESTIAL_PLANETARIUM_ACCESS_10, GO_CELESTIAL_PLANETARIUM_ACCESS_25, GO_DOODAD_UL_SIGILDOOR_01, GO_DOODAD_UL_SIGILDOOR_02, GO_FLAG_IN_USE, GO_FLAG_LOCKED, GO_FREYAS_GENERATOR, GO_FREYAS_TARGETTING_CRYSTAL, GO_HODIR_DOOR, GO_HODIR_FROZEN_DOOR, GO_HODIRS_GENERATOR, GO_HODIRS_TARGETTING_CRYSTAL, GO_KEEPERS_GATE, GO_KOLOGARN_BRIDGE, GO_LEVIATHAN_DOORS, GO_LIGHTNING_WALL1, GO_MIMIRON_ELEVATOR, GO_MIMIRON_TRAM, GO_MIMIRONS_GENERATOR, GO_MIMIRONS_TARGETTING_CRYSTAL, GO_READY, GO_REPAIR_STATION_TRAP, GO_SNOW_MOUND, GO_STATE_ACTIVE, GO_STATE_ACTIVE_ALTERNATIVE, GO_STATE_READY, GO_THORIMS_GENERATOR, GO_THORIMS_TARGETTING_CRYSTAL, GO_VEZAX_DOOR, m_algalonTimer, m_leviathanVisualTowers, m_mimironTramUsed, m_RepairSGUID, InstanceScript::OnGameObjectCreate(), OpenIfDone(), GameObject::RemoveGameObjectFlag(), GameObject::SetGameObjectFlag(), GameObject::SetGoState(), GameObject::SetLootState(), GameObject::SetRespawnTime(), and GameObject::UseDoorOrButton().
OnPlayerEnter()
void instance_ulduar::instance_ulduar_InstanceMapScript::OnPlayerEnter (Player * player) inline override virtual
Reimplemented from InstanceScript.
        {
            // mimiron tram:
            if (GameObject* MimironTram = GetGameObject(DATA_MIMIRON_TRAM))
            {
                player->UpdateVisibilityOf(MimironTram);
                if (StaticTransport* t = MimironTram->ToStaticTransport())
                {
                    if (GameObject* go = GetGameObject(DATA_MIMIRON_TRAM_ROCKET_BOOSTER))
                        if (!go->GetTransport())
                            t->AddPassenger(go, true);
                    if (GameObject* go = GetGameObject(DATA_MIMIRON_ACTIVATE_TRAM))
                        if (!go->GetTransport())
                            t->AddPassenger(go, true);
                }
            }
            if (!GetObjectGuid(BOSS_ALGALON) && m_algalonTimer && (m_algalonTimer <= 60 || m_algalonTimer == TIMER_ALGALON_TO_SUMMON))
            {
                TempSummon* algalon = instance->SummonCreature(NPC_ALGALON, AlgalonLandPos);
                if (!algalon)
                    return;
                if (m_algalonTimer <= 60)
                {
                    _events.RescheduleEvent(EVENT_UPDATE_ALGALON_TIMER, 1min);
                    algalon->AI()->DoAction(ACTION_INIT_ALGALON);
                }
                else // if (m_algalonTimer = TIMER_ALGALON_TO_SUMMON)
                {
                    m_algalonTimer = TIMER_ALGALON_SUMMONED;
                    algalon->SetImmuneToPC(false);
                }
            }
        }
References _events, ACTION_INIT_ALGALON, Creature::AI(), AlgalonLandPos, BOSS_ALGALON, DATA_MIMIRON_ACTIVATE_TRAM, DATA_MIMIRON_TRAM, DATA_MIMIRON_TRAM_ROCKET_BOOSTER, UnitAI::DoAction(), EVENT_UPDATE_ALGALON_TIMER, InstanceScript::GetGameObject(), InstanceScript::GetObjectGuid(), InstanceScript::instance, m_algalonTimer, NPC_ALGALON, EventMap::RescheduleEvent(), Unit::SetImmuneToPC(), Map::SummonCreature(), TIMER_ALGALON_SUMMONED, TIMER_ALGALON_TO_SUMMON, GameObject::ToStaticTransport(), and Player::UpdateVisibilityOf().
OnUnitDeath()
void instance_ulduar::instance_ulduar_InstanceMapScript::OnUnitDeath (Unit * unit) inline override virtual
Reimplemented from ZoneScript.
        {
            // Feeds on Tears achievement
            if (unit->IsPlayer())
            {
                if (GetBossState(BOSS_ALGALON) == IN_PROGRESS)
                    if (Creature* algalon = GetCreature(BOSS_ALGALON))
                        algalon->AI()->DoAction(ACTION_FEEDS_ON_TEARS_FAILED);
            }
            else if (unit->IsCreature() && unit->GetAreaId() == AREA_THE_CONSERVATORY_OF_LIFE)
            {
                if (GameTime::GetGameTime().count() > (m_conspeedatoryAttempt + DAY))
                {
                    DoStartTimedAchievement(ACHIEVEMENT_TIMED_TYPE_EVENT, 21597 /*CON-SPEED-ATORY_TIMED_CRITERIA*/);
                    m_conspeedatoryAttempt = GameTime::GetGameTime().count();
                    SaveToDB();
                }
            }
            // achievement Champion/Conqueror of Ulduar
            if (unit->IsPlayer())
                for (uint8 i = 0; i <= 12; ++i)
                {
                    bool go = false;
                    if (i == BOSS_LEVIATHAN)
                    {
                        if (Creature* c = GetCreature(BOSS_LEVIATHAN))
                            if (c->IsInCombat())
                                go = true;
                    }
                    else
                        go = (GetBossState(i) == IN_PROGRESS);
                    if (go && (C_of_Ulduar_MASK & (1 << i)) == 0)
                    {
                        C_of_Ulduar_MASK |= (1 << i);
                        SaveToDB();
                    }
                }
        }
References ACHIEVEMENT_TIMED_TYPE_EVENT, ACTION_FEEDS_ON_TEARS_FAILED, AREA_THE_CONSERVATORY_OF_LIFE, BOSS_ALGALON, BOSS_LEVIATHAN, C_of_Ulduar_MASK, DAY, InstanceScript::DoStartTimedAchievement(), WorldObject::GetAreaId(), InstanceScript::GetBossState(), InstanceScript::GetCreature(), GameTime::GetGameTime(), IN_PROGRESS, Object::IsCreature(), Object::IsPlayer(), m_conspeedatoryAttempt, and InstanceScript::SaveToDB().
OpenIfDone()
void instance_ulduar::instance_ulduar_InstanceMapScript::OpenIfDone (uint32 encounter, GameObject * go, GOState state) inline
        {
            if (GetBossState(encounter) == DONE)
                go->SetGoState(state);
        }
References DONE, InstanceScript::GetBossState(), and GameObject::SetGoState().
Referenced by OnGameObjectCreate().
ProcessEvent()
void instance_ulduar::instance_ulduar_InstanceMapScript::ProcessEvent (WorldObject * , uint32 eventId) inline override virtual
Reimplemented from ZoneScript.
        {
            // destory towers
            if (eventId >= EVENT_TOWER_OF_LIFE_DESTROYED && eventId <= EVENT_TOWER_OF_FLAMES_DESTROYED)
                SetData(eventId, 0);
        }
References EVENT_TOWER_OF_FLAMES_DESTROYED, EVENT_TOWER_OF_LIFE_DESTROYED, and SetData().
Referenced by SetData().
ReadSaveDataMore()
void instance_ulduar::instance_ulduar_InstanceMapScript::ReadSaveDataMore (std::istringstream & data) inline override virtual
Reimplemented from InstanceScript.
        {
            // Boss states 0-13 are read by base InstanceScript.
            data >> m_watchersMask;
            data >> m_conspeedatoryAttempt;
            data >> m_unbrokenAchievement;
            data >> m_algalonTimer;
            if (m_algalonTimer == TIMER_ALGALON_SUMMONED)
                m_algalonTimer = TIMER_ALGALON_TO_SUMMON;
            if (m_algalonTimer && m_algalonTimer <= 60 && GetBossState(BOSS_ALGALON) != DONE)
            {
                DoUpdateWorldState(WORLD_STATE_ULDUAR_ALGALON_TIMER_ENABLED, 1);
                DoUpdateWorldState(WORLD_STATE_ULDUAR_ALGALON_DESPAWN_TIMER, m_algalonTimer);
            }
            data >> C_of_Ulduar_MASK;
            data >> m_mageBarrier;
        }
References BOSS_ALGALON, C_of_Ulduar_MASK, DONE, InstanceScript::DoUpdateWorldState(), InstanceScript::GetBossState(), m_algalonTimer, m_conspeedatoryAttempt, m_mageBarrier, m_unbrokenAchievement, m_watchersMask, TIMER_ALGALON_SUMMONED, TIMER_ALGALON_TO_SUMMON, WORLD_STATE_ULDUAR_ALGALON_DESPAWN_TIMER, and WORLD_STATE_ULDUAR_ALGALON_TIMER_ENABLED.
SetBossState()
bool instance_ulduar::instance_ulduar_InstanceMapScript::SetBossState (uint32 type, EncounterState state) inline override virtual
Reimplemented from InstanceScript.
        {
            if (!InstanceScript::SetBossState(type, state))
                return false;
            switch (type)
            {
                case BOSS_LEVIATHAN:
                    if (state == DONE)
                    {
                        instance->DoForAllPlayers([&](Player* player)
{
                            if (Creature* vehicleCreature = player->GetVehicleCreatureBase())
                                vehicleCreature->DespawnOrUnsummon();
                        });
                        if (GameObject* go = GetGameObject(DATA_LEVIATHAN_DOORS))
                            go->SetGoState(GO_STATE_ACTIVE_ALTERNATIVE);
                    }
                    break;
                case BOSS_ASSEMBLY:
                    // Assembly doors handled by DoorData, archivum
                    // doors stay open only after DONE
                    if (GameObject* go = GetGameObject(DATA_ARCHIVUM_DOORS))
                        go->SetGoState(state == DONE ? GO_STATE_ACTIVE : GO_STATE_READY);
                    break;
                case BOSS_MIMIRON:
                    if (state == IN_PROGRESS)
                        m_mimironTramUsed = true;
                    [[fallthrough]];
                case BOSS_HODIR:
                case BOSS_THORIM:
                case BOSS_FREYA:
                    if (GetBossState(BOSS_MIMIRON) == DONE && GetBossState(BOSS_FREYA) == DONE && GetBossState(BOSS_HODIR) == DONE && GetBossState(BOSS_THORIM) == DONE)
                    {
                        scheduler.Schedule(45s, [this](TaskContext /*context*/)
{
                            if (GameObject* go = GetGameObject(DATA_KEEPERS_GATE))
{
                                go->RemoveGameObjectFlag(GO_FLAG_LOCKED);
                                if (Creature* trigger = instance->SummonCreature(NPC_ANCIENT_GATE_WORLD_TRIGGER, triggerAncientGatePosition, nullptr, 10 * IN_MILLISECONDS))
                                    trigger->AI()->Talk(EMOTE_ANCIENT_GATE_UNLOCKED);
                            }
                        });
                    }
                    if (type == BOSS_HODIR && state == DONE)
                        setChestsLootable(BOSS_HODIR);
                    break;
                case BOSS_ALGALON:
                    if (GameObject* go = GetGameObject(DATA_SIGILDOOR_03))
                    {
                        go->SetGoState(state != IN_PROGRESS ? GO_STATE_ACTIVE : GO_STATE_READY);
                        go->EnableCollision(false);
                    }
                    if (GameObject* go = GetGameObject(DATA_UNIVERSE_FLOOR_01))
                    {
                        go->SetGoState(state != IN_PROGRESS ? GO_STATE_ACTIVE : GO_STATE_READY);
                        go->EnableCollision(false);
                    }
                    if (GameObject* go = GetGameObject(DATA_UNIVERSE_FLOOR_02))
                    {
                        go->SetGoState(state == IN_PROGRESS ? GO_STATE_ACTIVE : GO_STATE_READY);
                        go->EnableCollision(false);
                    }
                    if (GameObject* go = GetGameObject(DATA_UNIVERSE_GLOBE))
                    {
                        go->SetGoState(state == IN_PROGRESS ? GO_STATE_ACTIVE : GO_STATE_READY);
                        go->EnableCollision(false);
                    }
                    if (GameObject* go = GetGameObject(DATA_ALGALON_TRAPDOOR))
                    {
                        go->SetGoState(state == IN_PROGRESS ? GO_STATE_ACTIVE : GO_STATE_READY);
                        go->EnableCollision(false);
                    }
                    break;
                default:
                    break;
            }
            // take care of herbs
            if (type == BOSS_FREYA && state == DONE)
            {
                std::list<GameObject*> goList;
                if (Creature* freya = GetCreature(BOSS_FREYA))
                {
                    freya->GetGameObjectListWithEntryInGrid(goList, { 191019, 190176, 190171, 190170, 189973 }, 333.0f);
                    for (GameObject* herb : goList)
                        herb->SetRespawnTime(7 * DAY);
                }
            }
            if (state == DONE)
                SaveToDB();
            if (type > BOSS_LEVIATHAN && type < MAX_ENCOUNTER && state == IN_PROGRESS)
            {
                instance->DoForAllPlayers([&](Player* player)
                {
                    if (Creature* vehicleCreature = player->GetVehicleCreatureBase())
                        vehicleCreature->DespawnOrUnsummon();
                });
            }
            return true;
        }
References BOSS_ALGALON, BOSS_ASSEMBLY, BOSS_FREYA, BOSS_HODIR, BOSS_LEVIATHAN, BOSS_MIMIRON, BOSS_THORIM, DATA_ALGALON_TRAPDOOR, DATA_ARCHIVUM_DOORS, DATA_KEEPERS_GATE, DATA_LEVIATHAN_DOORS, DATA_SIGILDOOR_03, DATA_UNIVERSE_FLOOR_01, DATA_UNIVERSE_FLOOR_02, DATA_UNIVERSE_GLOBE, DAY, Map::DoForAllPlayers(), DONE, EMOTE_ANCIENT_GATE_UNLOCKED, InstanceScript::GetBossState(), InstanceScript::GetCreature(), InstanceScript::GetGameObject(), Unit::GetVehicleCreatureBase(), GO_FLAG_LOCKED, GO_STATE_ACTIVE, GO_STATE_ACTIVE_ALTERNATIVE, GO_STATE_READY, IN_MILLISECONDS, IN_PROGRESS, InstanceScript::instance, m_mimironTramUsed, MAX_ENCOUNTER, NPC_ANCIENT_GATE_WORLD_TRIGGER, InstanceScript::SaveToDB(), TaskScheduler::Schedule(), InstanceScript::scheduler, InstanceScript::SetBossState(), setChestsLootable(), Map::SummonCreature(), and triggerAncientGatePosition.
setChestsLootable()
void instance_ulduar::instance_ulduar_InstanceMapScript::setChestsLootable (uint32 boss) inline
        {
            if (boss)
            {
                switch (boss)
                {
                    case BOSS_HODIR:
                        if (hmHodir)
{
                            if (GameObject* go = GetHodirChest(true))
{
                                go->RemoveGameObjectFlag(GO_FLAG_NOT_SELECTABLE);
                                go->SetLootRecipient(instance);
                            }
                        }
                        if (GameObject* go = GetHodirChest(false))
{
                            go->RemoveGameObjectFlag(GO_FLAG_NOT_SELECTABLE);
                            go->SetLootRecipient(instance);
                        }
                        break;
                }
            }
        }
References BOSS_HODIR, GetHodirChest(), GO_FLAG_NOT_SELECTABLE, hmHodir, and InstanceScript::instance.
Referenced by SetBossState().
SetData()
void instance_ulduar::instance_ulduar_InstanceMapScript::SetData (uint32 type, uint32 data) inline override virtual
Reimplemented from ZoneScript.
        {
            switch (type)
            {
                case TYPE_HODIR_HM_FAIL:
                    if (GameObject* go = GetHodirChest(true))
                    {
                        hmHodir = false;
                        go->Delete();
                    }
                    break;
                case TYPE_WATCHERS:
                    m_watchersMask |= 1 << data;
                    [[fallthrough]];
                case EVENT_KEEPER_TELEPORTED:
                    if (Creature* sara = GetCreature(DATA_SARA))
                        sara->AI()->DoAction(ACTION_SARA_UPDATE_SUMMON_KEEPERS);
                    break;
                case DATA_MAGE_BARRIER:
                    m_mageBarrier = data;
                    break;
                case EVENT_TOWER_OF_LIFE_DESTROYED:
                case EVENT_TOWER_OF_STORM_DESTROYED:
                case EVENT_TOWER_OF_FROST_DESTROYED:
                case EVENT_TOWER_OF_FLAMES_DESTROYED:
                    {
                        m_leviathanTowers[type - EVENT_TOWER_OF_LIFE_DESTROYED] = data;
                        for (uint8 i = 0; i < 2; ++i)
{
                            if (GameObject *gameObject = instance->GetGameObject(m_leviathanVisualTowers[type - EVENT_TOWER_OF_LIFE_DESTROYED][i]))
{
                                gameObject->SetGoState(GO_STATE_ACTIVE);
                            }
                        }
                        return;
                    }
                case DATA_VEHICLE_SPAWN:
                    SpawnLeviathanEncounterVehicles(data);
                    return;
                case DATA_UNBROKEN_ACHIEVEMENT:
                    m_unbrokenAchievement = data;
                    SaveToDB();
                    return;
                case DATA_DESPAWN_ALGALON:
                    DoUpdateWorldState(WORLD_STATE_ULDUAR_ALGALON_TIMER_ENABLED, 1);
                    DoUpdateWorldState(WORLD_STATE_ULDUAR_ALGALON_DESPAWN_TIMER, 60);
                    m_algalonTimer = 60;
                    _events.RescheduleEvent(EVENT_UPDATE_ALGALON_TIMER, 1min);
                    SaveToDB();
                    return;
                case DATA_ALGALON_SUMMON_STATE:
                case DATA_ALGALON_DEFEATED:
                    DoUpdateWorldState(WORLD_STATE_ULDUAR_ALGALON_TIMER_ENABLED, 0);
                    m_algalonTimer = (type == DATA_ALGALON_DEFEATED ? TIMER_ALGALON_DEFEATED : TIMER_ALGALON_SUMMONED);
                    _events.CancelEvent(EVENT_UPDATE_ALGALON_TIMER);
                    SaveToDB();
                    return;
                // Achievement
                case DATA_DWARFAGEDDON:
                    DoStartTimedAchievement(ACHIEVEMENT_TIMED_TYPE_SPELL_TARGET, SPELL_DWARFAGEDDON);
                    DoUpdateAchievementCriteria(ACHIEVEMENT_CRITERIA_TYPE_BE_SPELL_TARGET, SPELL_DWARFAGEDDON);
                    return;
                case DATA_CALL_TRAM:
                    if (GameObject* MimironTram = GetGameObject(DATA_MIMIRON_TRAM))
                        if (StaticTransport* t = MimironTram->ToStaticTransport())
{
                            if (data == 0 && t->GetGoState() == GO_STATE_ACTIVE && t->GetPathProgress() == t->GetPauseTime())
{
                                MimironTram->SetGoState(GO_STATE_READY);
                                if (GameObject* rocketBooster = GetGameObject(DATA_MIMIRON_TRAM_ROCKET_BOOSTER))
                                    rocketBooster->SetGoState(GO_STATE_ACTIVE);
                                if (GameObject* activateTramButton = GetGameObject(DATA_MIMIRON_ACTIVATE_TRAM))
                                    activateTramButton->SetGameObjectFlag(GO_FLAG_NOT_SELECTABLE);
                                if (GameObject* callTramCenterButton = GetGameObject(DATA_MIMIRON_CALL_TRAM_CENTER))
                                    callTramCenterButton->SetGameObjectFlag(GO_FLAG_NOT_SELECTABLE);
                                scheduler.Schedule(30s, [this](TaskContext /*context*/)
{
                                    if (GameObject* turnaround1 = GetGameObject(DATA_MIMIRON_TRAM_TURNAROUND_1))
                                        turnaround1->UseDoorOrButton();
                                    if (GameObject* rocketBooster = GetGameObject(DATA_MIMIRON_TRAM_ROCKET_BOOSTER))
                                        rocketBooster->SetGoState(GO_STATE_READY);
                                }).Schedule(60s, [this](TaskContext /*context*/)
{
                                    if (GameObject* activateTramButton = GetGameObject(DATA_MIMIRON_ACTIVATE_TRAM))
                                        activateTramButton->RemoveGameObjectFlag(GO_FLAG_NOT_SELECTABLE);
                                    if (GameObject* callTramMimironButton = GetGameObject(DATA_MIMIRON_CALL_TRAM_MIMIRON))
                                        callTramMimironButton->RemoveGameObjectFlag(GO_FLAG_NOT_SELECTABLE);
                                });
                            }
                            if (data == 1 && t->GetGoState() == GO_STATE_READY && t->GetPathProgress() == 0)
{
                                MimironTram->SetGoState(GO_STATE_ACTIVE);
                                if (GameObject* rocketBooster = GetGameObject(DATA_MIMIRON_TRAM_ROCKET_BOOSTER))
                                    rocketBooster->SetGoState(GO_STATE_ACTIVE);
                                if (GameObject* activateTramButton = GetGameObject(DATA_MIMIRON_ACTIVATE_TRAM))
                                    activateTramButton->SetGameObjectFlag(GO_FLAG_NOT_SELECTABLE);
                                if (GameObject* callTramMimironButton = GetGameObject(DATA_MIMIRON_CALL_TRAM_MIMIRON))
                                    callTramMimironButton->SetGameObjectFlag(GO_FLAG_NOT_SELECTABLE);
                                scheduler.Schedule(33s, [this](TaskContext /*context*/)
{
                                    if (GameObject* turnaround2 = GetGameObject(DATA_MIMIRON_TRAM_TURNAROUND_2))
                                        turnaround2->UseDoorOrButton();
                                    if (GameObject* rocketBooster = GetGameObject(DATA_MIMIRON_TRAM_ROCKET_BOOSTER))
                                        rocketBooster->SetGoState(GO_STATE_READY);
                                }).Schedule(63s, [this](TaskContext /*context*/)
{
                                    if (GameObject* activateTramButton = GetGameObject(DATA_MIMIRON_ACTIVATE_TRAM))
                                        activateTramButton->RemoveGameObjectFlag(GO_FLAG_NOT_SELECTABLE);
                                    if (GameObject* callTramCenterButton = GetGameObject(DATA_MIMIRON_CALL_TRAM_CENTER))
                                        callTramCenterButton->RemoveGameObjectFlag(GO_FLAG_NOT_SELECTABLE);
                                });
                            }
                        }
                    break;
                case DATA_BRANN_MEMOTESAY:
                    if (Creature* cr = GetCreature(DATA_BRANN_BASE_CAMP))
                        cr->TextEmote("Go to your vehicles!", nullptr, true);
                    break;
                case DATA_BRANN_EASY_MODE:
                    ProcessEvent(nullptr, EVENT_TOWER_OF_STORM_DESTROYED);
                    ProcessEvent(nullptr, EVENT_TOWER_OF_FROST_DESTROYED);
                    ProcessEvent(nullptr, EVENT_TOWER_OF_FLAMES_DESTROYED);
                    ProcessEvent(nullptr, EVENT_TOWER_OF_LIFE_DESTROYED);
                    break;
            }
            if (type == TYPE_WATCHERS)
                SaveToDB();
        }
References _events, ACHIEVEMENT_CRITERIA_TYPE_BE_SPELL_TARGET, ACHIEVEMENT_TIMED_TYPE_SPELL_TARGET, ACTION_SARA_UPDATE_SUMMON_KEEPERS, EventMap::CancelEvent(), DATA_ALGALON_DEFEATED, DATA_ALGALON_SUMMON_STATE, DATA_BRANN_BASE_CAMP, DATA_BRANN_EASY_MODE, DATA_BRANN_MEMOTESAY, DATA_CALL_TRAM, DATA_DESPAWN_ALGALON, DATA_DWARFAGEDDON, DATA_MAGE_BARRIER, DATA_MIMIRON_ACTIVATE_TRAM, DATA_MIMIRON_CALL_TRAM_CENTER, DATA_MIMIRON_CALL_TRAM_MIMIRON, DATA_MIMIRON_TRAM, DATA_MIMIRON_TRAM_ROCKET_BOOSTER, DATA_MIMIRON_TRAM_TURNAROUND_1, DATA_MIMIRON_TRAM_TURNAROUND_2, DATA_SARA, DATA_UNBROKEN_ACHIEVEMENT, DATA_VEHICLE_SPAWN, InstanceScript::DoStartTimedAchievement(), InstanceScript::DoUpdateAchievementCriteria(), InstanceScript::DoUpdateWorldState(), EVENT_KEEPER_TELEPORTED, EVENT_TOWER_OF_FLAMES_DESTROYED, EVENT_TOWER_OF_FROST_DESTROYED, EVENT_TOWER_OF_LIFE_DESTROYED, EVENT_TOWER_OF_STORM_DESTROYED, EVENT_UPDATE_ALGALON_TIMER, InstanceScript::GetCreature(), Map::GetGameObject(), InstanceScript::GetGameObject(), GetHodirChest(), GO_FLAG_NOT_SELECTABLE, GO_STATE_ACTIVE, GO_STATE_READY, hmHodir, InstanceScript::instance, m_algalonTimer, m_leviathanTowers, m_leviathanVisualTowers, m_mageBarrier, m_unbrokenAchievement, m_watchersMask, ProcessEvent(), EventMap::RescheduleEvent(), InstanceScript::SaveToDB(), TaskScheduler::Schedule(), InstanceScript::scheduler, SpawnLeviathanEncounterVehicles(), SPELL_DWARFAGEDDON, TIMER_ALGALON_DEFEATED, TIMER_ALGALON_SUMMONED, GameObject::ToStaticTransport(), TYPE_HODIR_HM_FAIL, TYPE_WATCHERS, WORLD_STATE_ULDUAR_ALGALON_DESPAWN_TIMER, and WORLD_STATE_ULDUAR_ALGALON_TIMER_ENABLED.
Referenced by ProcessEvent(), and Update().
SpawnHodirChests()
void instance_ulduar::instance_ulduar_InstanceMapScript::SpawnHodirChests (Difficulty diff, Creature * hodir) inline
        {
            switch (diff)
            {
                case RAID_DIFFICULTY_10MAN_NORMAL: // 10 man chest
                {
                    if (!GetObjectGuid(DATA_HODIR_CHEST_NORMAL))
                    {
                        if (GameObject* go = hodir->SummonGameObject(
                            GO_HODIR_CHEST_NORMAL,
                            normalChestPosition.GetPositionX(),
                            normalChestPosition.GetPositionY(),
                            normalChestPosition.GetPositionZ(),
                            normalChestPosition.GetOrientation(), 0, 0, 0, 0, 0))
{
                            go->SetGameObjectFlag(GO_FLAG_NOT_SELECTABLE);
                        }
                    }
                    if (!GetObjectGuid(DATA_HODIR_CHEST_HARD))
                    {
                        if (GameObject* go = hodir->SummonGameObject(
                            GO_HODIR_CHEST_HARD,
                            hardChestPosition.GetPositionX(),
                            hardChestPosition.GetPositionY(),
                            hardChestPosition.GetPositionZ(),
                            hardChestPosition.GetOrientation(), 0, 0, 0, 0, 0))
{
                            go->SetGameObjectFlag(GO_FLAG_NOT_SELECTABLE);
                            hmHodir = true;
                        }
                    }
                    break;
                }
                case RAID_DIFFICULTY_25MAN_NORMAL: // 25 man chest
                {
                    if (!GetObjectGuid(DATA_HODIR_CHEST_NORMAL_HERO))
                    {
                        if (GameObject* go = hodir->SummonGameObject(
                            GO_HODIR_CHEST_NORMAL_HERO,
                            normalChestPosition.GetPositionX(),
                            normalChestPosition.GetPositionY(),
                            normalChestPosition.GetPositionZ(),
                            normalChestPosition.GetOrientation(), 0, 0, 0, 0, 0))
{
                            go->SetGameObjectFlag(GO_FLAG_NOT_SELECTABLE);
                        }
                    }
                    if (!GetObjectGuid(DATA_HODIR_CHEST_HARD_HERO))
                    {
                        if (GameObject* go = hodir->SummonGameObject(
                            GO_HODIR_CHEST_HARD_HERO,
                            hardChestPosition.GetPositionX(),
                            hardChestPosition.GetPositionY(),
                            hardChestPosition.GetPositionZ(),
                            hardChestPosition.GetOrientation(), 0, 0, 0, 0, 0))
{
                            go->SetGameObjectFlag(GO_FLAG_NOT_SELECTABLE);
                            hmHodir = true;
                        }
                    }
                    break;
                }
                default:
                    break;
            }
        }
References DATA_HODIR_CHEST_HARD, DATA_HODIR_CHEST_HARD_HERO, DATA_HODIR_CHEST_NORMAL, DATA_HODIR_CHEST_NORMAL_HERO, InstanceScript::GetObjectGuid(), Position::GetOrientation(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), GO_FLAG_NOT_SELECTABLE, GO_HODIR_CHEST_HARD, GO_HODIR_CHEST_HARD_HERO, GO_HODIR_CHEST_NORMAL, GO_HODIR_CHEST_NORMAL_HERO, hardChestPosition, hmHodir, normalChestPosition, RAID_DIFFICULTY_10MAN_NORMAL, RAID_DIFFICULTY_25MAN_NORMAL, and WorldObject::SummonGameObject().
Referenced by OnCreatureCreate().
SpawnLeviathanEncounterVehicles()
void instance_ulduar::instance_ulduar_InstanceMapScript::SpawnLeviathanEncounterVehicles (uint8 mode)
{
    if (!_leviathanVehicles.empty())
    {
        for (ObjectGuid const& guid : _leviathanVehicles)
        {
            if (Creature* cr = instance->GetCreature(guid))
            {
                cr->DespawnOrUnsummon();
            }
        }
        _leviathanVehicles.clear();
    }
    if (mode < VEHICLE_POS_NONE)
    {
        for (uint8 i = 0; i < (instance->Is25ManRaid() ? 5 : 2); ++i)
        {
            if (TempSummon* veh = instance->SummonCreature(NPC_SALVAGED_SIEGE_ENGINE, vehiclePositions[15 * mode + i]))
            {
                _leviathanVehicles.push_back(veh->GetGUID());
            }
            if (TempSummon* veh = instance->SummonCreature(NPC_VEHICLE_CHOPPER, vehiclePositions[15 * mode + i + 5]))
            {
                _leviathanVehicles.push_back(veh->GetGUID());
            }
            if (TempSummon* veh = instance->SummonCreature(NPC_SALVAGED_DEMOLISHER, vehiclePositions[15 * mode + i + 10]))
            {
                _leviathanVehicles.push_back(veh->GetGUID());
            }
        }
    }
}
References _leviathanVehicles, Map::GetCreature(), InstanceScript::instance, Map::Is25ManRaid(), NPC_SALVAGED_DEMOLISHER, NPC_SALVAGED_SIEGE_ENGINE, NPC_VEHICLE_CHOPPER, Map::SummonCreature(), VEHICLE_POS_NONE, and vehiclePositions.
Referenced by SetData().
Update()
void instance_ulduar::instance_ulduar_InstanceMapScript::Update (uint32 diff) inline override virtual
Reimplemented from InstanceScript.
        {
            InstanceScript::Update(diff);
            if (_events.Empty())
                return;
            _events.Update(diff);
            switch (_events.ExecuteEvent())
            {
                case EVENT_UPDATE_ALGALON_TIMER:
                    if (m_algalonTimer == TIMER_ALGALON_DEFEATED)
                        return;
                    SaveToDB();
                    DoUpdateWorldState(WORLD_STATE_ULDUAR_ALGALON_DESPAWN_TIMER, --m_algalonTimer);
                    if (m_algalonTimer)
                    {
                        _events.Repeat(1min);
                        return;
                    }
                    SetData(DATA_ALGALON_DEFEATED, 1);
                    if (Creature* algalon = GetCreature(BOSS_ALGALON))
                        algalon->AI()->DoAction(ACTION_DESPAWN_ALGALON);
            }
        }
References _events, ACTION_DESPAWN_ALGALON, BOSS_ALGALON, DATA_ALGALON_DEFEATED, InstanceScript::DoUpdateWorldState(), EventMap::Empty(), EVENT_UPDATE_ALGALON_TIMER, EventMap::ExecuteEvent(), InstanceScript::GetCreature(), m_algalonTimer, EventMap::Repeat(), InstanceScript::SaveToDB(), SetData(), TIMER_ALGALON_DEFEATED, EventMap::Update(), InstanceScript::Update(), and WORLD_STATE_ULDUAR_ALGALON_DESPAWN_TIMER.
WriteSaveDataMore()
void instance_ulduar::instance_ulduar_InstanceMapScript::WriteSaveDataMore (std::ostringstream & data) inline override virtual
Reimplemented from InstanceScript.
        {
            // Boss states 0-13 are written by base InstanceScript.
            // Only write extra non-boss data here.
            data << m_watchersMask << ' '
                << m_conspeedatoryAttempt << ' '
                << m_unbrokenAchievement << ' '
                << m_algalonTimer << ' '
                << C_of_Ulduar_MASK << ' '
                << m_mageBarrier;
        }
References C_of_Ulduar_MASK, m_algalonTimer, m_conspeedatoryAttempt, m_mageBarrier, m_unbrokenAchievement, and m_watchersMask.
Member Data Documentation
_events
EventMap instance_ulduar::instance_ulduar_InstanceMapScript::_events
Referenced by Initialize(), OnPlayerEnter(), SetData(), and Update().
_leviathanVehicles
GuidList instance_ulduar::instance_ulduar_InstanceMapScript::_leviathanVehicles
Referenced by Initialize(), and SpawnLeviathanEncounterVehicles().
C_of_Ulduar_MASK
uint32 instance_ulduar::instance_ulduar_InstanceMapScript::C_of_Ulduar_MASK
Referenced by CheckAchievementCriteriaMeet(), Initialize(), OnUnitDeath(), ReadSaveDataMore(), and WriteSaveDataMore().
hardChestPosition
Position instance_ulduar::instance_ulduar_InstanceMapScript::hardChestPosition = { 2035.94600f, -202.084885f, 432.686859f, 3.164077f }
{ 2035.94600f, -202.084885f, 432.686859f, 3.164077f };
Referenced by SpawnHodirChests().
hmHodir
bool instance_ulduar::instance_ulduar_InstanceMapScript::hmHodir
Referenced by Initialize(), setChestsLootable(), SetData(), and SpawnHodirChests().
m_algalonTimer
uint32 instance_ulduar::instance_ulduar_InstanceMapScript::m_algalonTimer
Referenced by FillInitialWorldStates(), Initialize(), OnCreatureCreate(), OnGameObjectCreate(), OnPlayerEnter(), ReadSaveDataMore(), SetData(), Update(), and WriteSaveDataMore().
m_conspeedatoryAttempt
uint32 instance_ulduar::instance_ulduar_InstanceMapScript::m_conspeedatoryAttempt
Referenced by Initialize(), OnUnitDeath(), ReadSaveDataMore(), and WriteSaveDataMore().
m_difficulty
int instance_ulduar::instance_ulduar_InstanceMapScript::m_difficulty
Referenced by instance_ulduar_InstanceMapScript().
m_keepersGossipGUID
ObjectGuid instance_ulduar::instance_ulduar_InstanceMapScript::m_keepersGossipGUID[4]
m_leviathanTowers
bool instance_ulduar::instance_ulduar_InstanceMapScript::m_leviathanTowers[4]
Referenced by GetData(), Initialize(), and SetData().
m_leviathanVisualTowers
ObjectGuid instance_ulduar::instance_ulduar_InstanceMapScript::m_leviathanVisualTowers[4][2]
Referenced by OnGameObjectCreate(), and SetData().
m_mageBarrier
uint32 instance_ulduar::instance_ulduar_InstanceMapScript::m_mageBarrier
Referenced by GetData(), Initialize(), ReadSaveDataMore(), SetData(), and WriteSaveDataMore().
m_mimironTramUsed
bool instance_ulduar::instance_ulduar_InstanceMapScript::m_mimironTramUsed
Referenced by GetData(), Initialize(), OnGameObjectCreate(), and SetBossState().
m_RazorscaleHarpoonFireStateGUID
ObjectGuid instance_ulduar::instance_ulduar_InstanceMapScript::m_RazorscaleHarpoonFireStateGUID[4]
Referenced by GetGuidData(), and OnCreatureCreate().
m_RepairSGUID
ObjectGuid instance_ulduar::instance_ulduar_InstanceMapScript::m_RepairSGUID[2]
Referenced by GetGuidData(), and OnGameObjectCreate().
m_unbrokenAchievement
uint32 instance_ulduar::instance_ulduar_InstanceMapScript::m_unbrokenAchievement
Referenced by GetData(), Initialize(), ReadSaveDataMore(), SetData(), and WriteSaveDataMore().
m_watchersMask
uint32 instance_ulduar::instance_ulduar_InstanceMapScript::m_watchersMask
Referenced by GetData(), Initialize(), ReadSaveDataMore(), SetData(), and WriteSaveDataMore().
normalChestPosition
Position instance_ulduar::instance_ulduar_InstanceMapScript::normalChestPosition = { 1967.152588f, -204.188461f, 432.686951f, 5.50957f }
{ 1967.152588f, -204.188461f, 432.686951f, 5.50957f };
Referenced by SpawnHodirChests().
triggerAncientGatePosition
const Position instance_ulduar::instance_ulduar_InstanceMapScript::triggerAncientGatePosition = { 1883.65f, 269.272f, 418.406f }
{ 1883.65f, 269.272f, 418.406f };
Referenced by SetBossState().
The documentation for this struct was generated from the following file:
azerothcore-wotlk/src/server/scripts/Northrend/Ulduar/Ulduar/instance_ulduar.cpp