AzerothCore Doxygen
LuaAura Namespace Reference
Functions
int GetCaster (lua_State *L, Aura *aura)
int GetCasterGUID (lua_State *L, Aura *aura)
int GetCasterLevel (lua_State *L, Aura *aura)
int GetDuration (lua_State *L, Aura *aura)
int GetAuraId (lua_State *L, Aura *aura)
int GetMaxDuration (lua_State *L, Aura *aura)
int GetStackAmount (lua_State *L, Aura *aura)
int GetOwner (lua_State *L, Aura *aura)
int SetDuration (lua_State *L, Aura *aura)
int SetMaxDuration (lua_State *L, Aura *aura)
int SetStackAmount (lua_State *L, Aura *aura)
int Remove (lua_State *L, Aura *aura)
Function Documentation
GetAuraId()
int LuaAura::GetAuraId (lua_State * L, Aura * aura)
Returns the ID of the [Spell] that caused this [Aura] to be applied.
Returns
uint32 aura_id
    {
        Eluna::Push(L, aura->GetId());
        return 1;
    }
References Aura::GetId(), and Eluna::Push().
GetCaster()
int LuaAura::GetCaster (lua_State * L, Aura * aura)
Returns the [Unit] that casted the [Spell] that caused this [Aura] to be applied.
Returns
[Unit] caster
    {
        Eluna::Push(L, aura->GetCaster());
        return 1;
    }
References Aura::GetCaster(), and Eluna::Push().
GetCasterGUID()
int LuaAura::GetCasterGUID (lua_State * L, Aura * aura)
Returns the GUID of the [Unit] that casted the [Spell] that caused this [Aura] to be applied.
Returns
string caster_guid : the GUID of the Unit as a decimal string
    {
#if defined TRINITY || AZEROTHCORE
        Eluna::Push(L, aura->GetCasterGUID());
#else
        Eluna::Push(L, aura->GetCasterGuid());
#endif
        return 1;
    }
References Aura::GetCasterGUID(), and Eluna::Push().
GetCasterLevel()
int LuaAura::GetCasterLevel (lua_State * L, Aura * aura)
Returns the level of the [Unit] that casted the [Spell] that caused this [Aura] to be applied.
Returns
uint32 caster_level
    {
        Eluna::Push(L, aura->GetCaster()->GetLevel());
        return 1;
    }
References Aura::GetCaster(), Unit::GetLevel(), and Eluna::Push().
GetDuration()
int LuaAura::GetDuration (lua_State * L, Aura * aura)
Returns the amount of time left until the [Aura] expires.
Returns
int32 duration : amount of time left in milliseconds
    {
#if defined TRINITY || AZEROTHCORE
        Eluna::Push(L, aura->GetDuration());
#else
        Eluna::Push(L, aura->GetAuraDuration());
#endif
        return 1;
    }
References Aura::GetDuration(), and Eluna::Push().
GetMaxDuration()
int LuaAura::GetMaxDuration (lua_State * L, Aura * aura)
Returns the amount of time this [Aura] lasts when applied.
To determine how much time has passed since this Aura was applied, subtract the result of [Aura]:GetDuration from the result of this method.
Returns
int32 max_duration : the maximum duration of the Aura, in milliseconds
    {
#if defined TRINITY || AZEROTHCORE
        Eluna::Push(L, aura->GetMaxDuration());
#else
        Eluna::Push(L, aura->GetAuraMaxDuration());
#endif
        return 1;
    }
References Aura::GetMaxDuration(), and Eluna::Push().
GetOwner()
int LuaAura::GetOwner (lua_State * L, Aura * aura)
Returns the [Unit] that the [Aura] has been applied to.
Returns
[Unit] owner
    {
#if defined TRINITY || defined AZEROTHCORE
        Eluna::Push(L, aura->GetOwner());
#else
        Eluna::Push(L, aura->GetTarget());
#endif
        return 1;
    }
References Aura::GetOwner(), and Eluna::Push().
GetStackAmount()
int LuaAura::GetStackAmount (lua_State * L, Aura * aura)
Returns the number of times the [Aura] has "stacked".
This is the same as the number displayed on the [Aura]'s icon in-game.
Returns
uint32 stack_amount
    {
        Eluna::Push(L, aura->GetStackAmount());
        return 1;
    }
References Aura::GetStackAmount(), and Eluna::Push().
Remove()
int LuaAura::Remove (lua_State * L, Aura * aura)
Remove this [Aura] from the [Unit] it is applied to.
    {
#if defined TRINITY || defined AZEROTHCORE
        aura->Remove();
#else
        aura->GetTarget()->RemoveSpellAuraHolder(aura->GetHolder(), AURA_REMOVE_BY_CANCEL);
#endif
        Eluna::CHECKOBJ<ElunaObject>(L, 1)->Invalidate();
        return 0;
    }
References AURA_REMOVE_BY_CANCEL, and Aura::Remove().
SetDuration()
int LuaAura::SetDuration (lua_State * L, Aura * aura)
Change the amount of time before the [Aura] expires.
Parameters
int32 duration : the new duration of the Aura, in milliseconds
    {
        int32 duration = Eluna::CHECKVAL<int32>(L, 2);
#if defined TRINITY || defined AZEROTHCORE
        aura->SetDuration(duration);
#else
        aura->GetHolder()->SetAuraDuration(duration);
#if (defined(TBC) || defined(CLASSIC))
        aura->GetHolder()->UpdateAuraDuration();
#else
        aura->GetHolder()->SendAuraUpdate(false);
#endif
#endif
        return 0;
    }
References Aura::SetDuration().
SetMaxDuration()
int LuaAura::SetMaxDuration (lua_State * L, Aura * aura)
Change the maximum amount of time before the [Aura] expires.
This does not affect the current duration of the [Aura], but if the [Aura] is reset to the maximum duration, it will instead change to duration.
Parameters
int32 duration : the new maximum duration of the Aura, in milliseconds
    {
        int32 duration = Eluna::CHECKVAL<int32>(L, 2);
#if defined TRINITY || defined AZEROTHCORE
        aura->SetMaxDuration(duration);
#else
        aura->GetHolder()->SetAuraMaxDuration(duration);
#if (defined(TBC) || defined(CLASSIC))
        aura->GetHolder()->UpdateAuraDuration();
#else
        aura->GetHolder()->SendAuraUpdate(false);
#endif
#endif
        return 0;
    }
References Aura::SetMaxDuration().
SetStackAmount()
int LuaAura::SetStackAmount (lua_State * L, Aura * aura)
Change the amount of times the [Aura] has "stacked" on the [Unit].
If amount is greater than or equal to the current number of stacks, then the [Aura] has its duration reset to the maximum duration.
Parameters
uint32 amount
    {
        uint8 amount = Eluna::CHECKVAL<uint8>(L, 2);
#if defined TRINITY || defined AZEROTHCORE
        aura->SetStackAmount(amount);
#else
        aura->GetHolder()->SetStackAmount(amount);
#endif
        return 0;
    }
References Aura::SetStackAmount().