AzerothCore Doxygen
boss_assembly_of_iron.cpp File Reference
#include "AchievementCriteriaScript.h"
#include "CreatureScript.h"
#include "Player.h"
#include "ScriptedCreature.h"
#include "SpellAuraEffects.h"
#include "SpellScript.h"
#include "SpellScriptLoader.h"
#include "ulduar.h"
Classes
class boss_steelbreaker
struct boss_steelbreaker::boss_steelbreakerAI
class CastRunesEvent
class boss_runemaster_molgeim
struct boss_runemaster_molgeim::boss_runemaster_molgeimAI
class npc_assembly_lightning
struct npc_assembly_lightning::npc_assembly_lightningAI
class boss_stormcaller_brundir
struct boss_stormcaller_brundir::boss_stormcaller_brundirAI
class spell_shield_of_runes_aura
class spell_assembly_meltdown
class spell_assembly_rune_of_summoning_aura
class achievement_assembly_of_iron
class achievement_cant_do_that_while_stunned
Macros
#define SPELL_HIGH_VOLTAGE RAID_MODE(SPELL_HIGH_VOLTAGE_10, SPELL_HIGH_VOLTAGE_25)
#define SPELL_FUSION_PUNCH RAID_MODE(SPELL_FUSION_PUNCH_10, SPELL_FUSION_PUNCH_25)
#define SPELL_STATIC_DISRUPTION RAID_MODE(SPELL_STATIC_DISRUPTION_10, SPELL_STATIC_DISRUPTION_25)
#define SPELL_OVERWHELMING_POWER RAID_MODE(SPELL_OVERWHELMING_POWER_10, SPELL_OVERWHELMING_POWER_25)
#define SPELL_SHIELD_OF_RUNES RAID_MODE(SPELL_SHIELD_OF_RUNES_10, SPELL_SHIELD_OF_RUNES_25)
#define SPELL_RUNE_OF_DEATH RAID_MODE(SPELL_RUNE_OF_DEATH_10, SPELL_RUNE_OF_DEATH_25)
#define SPELL_LIGHTNING_BLAST RAID_MODE(SPELL_LIGHTNING_BLAST_10, SPELL_LIGHTNING_BLAST_25)
#define SPELL_CHAIN_LIGHTNING RAID_MODE(SPELL_CHAIN_LIGHTNING_10, SPELL_CHAIN_LIGHTNING_25)
#define SPELL_OVERLOAD RAID_MODE(SPELL_OVERLOAD_10, SPELL_OVERLOAD_25)
#define SPELL_LIGHTNING_WHIRL RAID_MODE(SPELL_LIGHTNING_WHIRL_10, SPELL_LIGHTNING_WHIRL_25)
#define SPELL_LIGHTNING_TENDRILS RAID_MODE(SPELL_LIGHTNING_TENDRILS_10, SPELL_LIGHTNING_TENDRILS_25)
Enumerations
enum AssemblySpells {
SPELL_SUPERCHARGE = 61920 ,
SPELL_BERSERK = 47008 ,
SPELL_HIGH_VOLTAGE_10 = 61890 ,
SPELL_HIGH_VOLTAGE_25 = 63498 ,
SPELL_FUSION_PUNCH_10 = 61903 ,
SPELL_FUSION_PUNCH_25 = 63493 ,
SPELL_STATIC_DISRUPTION_10 = 61911 ,
SPELL_STATIC_DISRUPTION_25 = 63495 ,
SPELL_OVERWHELMING_POWER_10 = 64637 ,
SPELL_OVERWHELMING_POWER_25 = 61888 ,
SPELL_ELECTRICAL_CHARGE = 61902 ,
SPELL_SHIELD_OF_RUNES_BUFF = 62277 ,
SPELL_SHIELD_OF_RUNES_10 = 62274 ,
SPELL_SHIELD_OF_RUNES_25 = 63489 ,
SPELL_RUNE_OF_POWER = 61973 ,
SPELL_RUNE_OF_DEATH_10 = 62269 ,
SPELL_RUNE_OF_DEATH_25 = 63490 ,
SPELL_RUNE_OF_SUMMONING = 62273 ,
SPELL_RUNE_OF_SUMMONING_SUMMON = 62020 ,
SPELL_LIGHTNING_BLAST_10 = 62054 ,
SPELL_LIGHTNING_BLAST_25 = 63491 ,
CREATURE_LIGHTNING_ELEMENTAL = 32958 ,
CREATURE_RUNE_OF_SUMMONING = 33051 ,
SPELL_RUNE_OF_POWER_OOC_CHANNEL = 61975 ,
SPELL_CHAIN_LIGHTNING_10 = 61879 ,
SPELL_CHAIN_LIGHTNING_25 = 63479 ,
SPELL_OVERLOAD_10 = 61869 ,
SPELL_OVERLOAD_25 = 63481 ,
SPELL_LIGHTNING_WHIRL_10 = 61915 ,
SPELL_LIGHTNING_WHIRL_25 = 63483 ,
SPELL_LIGHTNING_TENDRILS_10 = 61887 ,
SPELL_LIGHTNING_TENDRILS_25 = 63486 ,
SPELL_STORMSHIELD = 64187 ,
SPELL_LIGHTNING_CHANNEL_PRE = 61942
}
enum eEnums {
EVENT_FUSION_PUNCH = 1 ,
EVENT_STATIC_DISRUPTION = 2 ,
EVENT_OVERWHELMING_POWER = 3 ,
EVENT_RUNE_OF_POWER = 11 ,
EVENT_SHIELD_OF_RUNES = 12 ,
EVENT_RUNE_OF_DEATH = 13 ,
EVENT_RUNE_OF_SUMMONING = 14 ,
EVENT_LIGHTNING_BLAST = 15 ,
EVENT_CHAIN_LIGHTNING = 21 ,
EVENT_OVERLOAD = 22 ,
EVENT_LIGHTNING_WHIRL = 23 ,
EVENT_LIGHTNING_TENDRILS = 24 ,
EVENT_LIGHTNING_LAND = 25 ,
EVENT_LAND_LAND = 26 ,
EVENT_LIGHTNING_FLIGHT = 27 ,
EVENT_ENRAGE = 30
}
enum AssemblyYells {
SAY_STEELBREAKER_AGGRO = 0 ,
SAY_STEELBREAKER_SLAY = 1 ,
SAY_STEELBREAKER_POWER = 2 ,
SAY_STEELBREAKER_DEATH = 3 ,
SAY_STEELBREAKER_ENCOUNTER_DEFEATED = 4 ,
SAY_STEELBREAKER_BERSERK = 5 ,
SAY_MOLGEIM_AGGRO = 0 ,
SAY_MOLGEIM_SLAY = 1 ,
SAY_MOLGEIM_RUNE_DEATH = 2 ,
SAY_MOLGEIM_SUMMON = 3 ,
SAY_MOLGEIM_DEATH = 4 ,
SAY_MOLGEIM_ENCOUNTER_DEFEATED = 5 ,
SAY_MOLGEIM_BERSERK = 6 ,
SAY_BRUNDIR_AGGRO = 0 ,
SAY_BRUNDIR_SLAY = 1 ,
SAY_BRUNDIR_SPECIAL = 2 ,
SAY_BRUNDIR_FLIGHT = 3 ,
SAY_BRUNDIR_DEATH = 4 ,
SAY_BRUNDIR_ENCOUNTER_DEFEATED = 5 ,
SAY_BRUNDIR_BERSERK = 6 ,
EMOTE_BRUNDIR_OVERLOAD = 7
}
enum Misc {
ACTION_ADD_CHARGE = 1 ,
POINT_CHANNEL_STEELBREAKER = 1
}
Functions
bool IsEncounterComplete (InstanceScript *pInstance, Creature *me)
void RespawnAssemblyOfIron (InstanceScript *pInstance, Creature *me)
void RestoreAssemblyHealth (ObjectGuid guid1, ObjectGuid guid2, Creature *me)
void AddSC_boss_assembly_of_iron ()
Macro Definition Documentation
SPELL_CHAIN_LIGHTNING
#define SPELL_CHAIN_LIGHTNING RAID_MODE(SPELL_CHAIN_LIGHTNING_10, SPELL_CHAIN_LIGHTNING_25)
SPELL_FUSION_PUNCH
#define SPELL_FUSION_PUNCH RAID_MODE(SPELL_FUSION_PUNCH_10, SPELL_FUSION_PUNCH_25)
SPELL_HIGH_VOLTAGE
#define SPELL_HIGH_VOLTAGE RAID_MODE(SPELL_HIGH_VOLTAGE_10, SPELL_HIGH_VOLTAGE_25)
SPELL_LIGHTNING_BLAST
#define SPELL_LIGHTNING_BLAST RAID_MODE(SPELL_LIGHTNING_BLAST_10, SPELL_LIGHTNING_BLAST_25)
SPELL_LIGHTNING_TENDRILS
#define SPELL_LIGHTNING_TENDRILS RAID_MODE(SPELL_LIGHTNING_TENDRILS_10, SPELL_LIGHTNING_TENDRILS_25)
SPELL_LIGHTNING_WHIRL
#define SPELL_LIGHTNING_WHIRL RAID_MODE(SPELL_LIGHTNING_WHIRL_10, SPELL_LIGHTNING_WHIRL_25)
SPELL_OVERLOAD
#define SPELL_OVERLOAD RAID_MODE(SPELL_OVERLOAD_10, SPELL_OVERLOAD_25)
SPELL_OVERWHELMING_POWER
#define SPELL_OVERWHELMING_POWER RAID_MODE(SPELL_OVERWHELMING_POWER_10, SPELL_OVERWHELMING_POWER_25)
SPELL_RUNE_OF_DEATH
#define SPELL_RUNE_OF_DEATH RAID_MODE(SPELL_RUNE_OF_DEATH_10, SPELL_RUNE_OF_DEATH_25)
SPELL_SHIELD_OF_RUNES
#define SPELL_SHIELD_OF_RUNES RAID_MODE(SPELL_SHIELD_OF_RUNES_10, SPELL_SHIELD_OF_RUNES_25)
SPELL_STATIC_DISRUPTION
#define SPELL_STATIC_DISRUPTION RAID_MODE(SPELL_STATIC_DISRUPTION_10, SPELL_STATIC_DISRUPTION_25)
Enumeration Type Documentation
AssemblySpells
enum AssemblySpells
Enumerator
SPELL_SUPERCHARGE
SPELL_BERSERK
SPELL_HIGH_VOLTAGE_10
SPELL_HIGH_VOLTAGE_25
SPELL_FUSION_PUNCH_10
SPELL_FUSION_PUNCH_25
SPELL_STATIC_DISRUPTION_10
SPELL_STATIC_DISRUPTION_25
SPELL_OVERWHELMING_POWER_10
SPELL_OVERWHELMING_POWER_25
SPELL_ELECTRICAL_CHARGE
SPELL_SHIELD_OF_RUNES_BUFF
SPELL_SHIELD_OF_RUNES_10
SPELL_SHIELD_OF_RUNES_25
SPELL_RUNE_OF_POWER
SPELL_RUNE_OF_DEATH_10
SPELL_RUNE_OF_DEATH_25
SPELL_RUNE_OF_SUMMONING
SPELL_RUNE_OF_SUMMONING_SUMMON
SPELL_LIGHTNING_BLAST_10
SPELL_LIGHTNING_BLAST_25
CREATURE_LIGHTNING_ELEMENTAL
CREATURE_RUNE_OF_SUMMONING
SPELL_RUNE_OF_POWER_OOC_CHANNEL
SPELL_CHAIN_LIGHTNING_10
SPELL_CHAIN_LIGHTNING_25
SPELL_OVERLOAD_10
SPELL_OVERLOAD_25
SPELL_LIGHTNING_WHIRL_10
SPELL_LIGHTNING_WHIRL_25
SPELL_LIGHTNING_TENDRILS_10
SPELL_LIGHTNING_TENDRILS_25
SPELL_STORMSHIELD
SPELL_LIGHTNING_CHANNEL_PRE
{
    // Any boss
    SPELL_SUPERCHARGE               = 61920,
    SPELL_BERSERK                   = 47008,
    // Steelbreaker
    SPELL_HIGH_VOLTAGE_10           = 61890,
    SPELL_HIGH_VOLTAGE_25           = 63498,
    SPELL_FUSION_PUNCH_10           = 61903,
    SPELL_FUSION_PUNCH_25           = 63493,
    SPELL_STATIC_DISRUPTION_10      = 61911,
    SPELL_STATIC_DISRUPTION_25      = 63495,
    SPELL_OVERWHELMING_POWER_10     = 64637,
    SPELL_OVERWHELMING_POWER_25     = 61888,
    SPELL_ELECTRICAL_CHARGE         = 61902,
    // Runemaster Molgeim
    SPELL_SHIELD_OF_RUNES_BUFF      = 62277,
    SPELL_SHIELD_OF_RUNES_10        = 62274,
    SPELL_SHIELD_OF_RUNES_25        = 63489,
    SPELL_RUNE_OF_POWER             = 61973,
    SPELL_RUNE_OF_DEATH_10          = 62269,
    SPELL_RUNE_OF_DEATH_25          = 63490,
    SPELL_RUNE_OF_SUMMONING         = 62273,
    SPELL_RUNE_OF_SUMMONING_SUMMON  = 62020,
    SPELL_LIGHTNING_BLAST_10        = 62054,
    SPELL_LIGHTNING_BLAST_25        = 63491,
    CREATURE_LIGHTNING_ELEMENTAL    = 32958,
    CREATURE_RUNE_OF_SUMMONING      = 33051,
    SPELL_RUNE_OF_POWER_OOC_CHANNEL = 61975,
    // Stormcaller Brundir
    SPELL_CHAIN_LIGHTNING_10        = 61879,
    SPELL_CHAIN_LIGHTNING_25        = 63479,
    SPELL_OVERLOAD_10               = 61869,
    SPELL_OVERLOAD_25               = 63481,
    SPELL_LIGHTNING_WHIRL_10        = 61915,
    SPELL_LIGHTNING_WHIRL_25        = 63483,
    SPELL_LIGHTNING_TENDRILS_10     = 61887,
    SPELL_LIGHTNING_TENDRILS_25     = 63486,
    SPELL_STORMSHIELD               = 64187,
    SPELL_LIGHTNING_CHANNEL_PRE     = 61942,
};
AssemblyYells
enum AssemblyYells
Enumerator
SAY_STEELBREAKER_AGGRO
SAY_STEELBREAKER_SLAY
SAY_STEELBREAKER_POWER
SAY_STEELBREAKER_DEATH
SAY_STEELBREAKER_ENCOUNTER_DEFEATED
SAY_STEELBREAKER_BERSERK
SAY_MOLGEIM_AGGRO
SAY_MOLGEIM_SLAY
SAY_MOLGEIM_RUNE_DEATH
SAY_MOLGEIM_SUMMON
SAY_MOLGEIM_DEATH
SAY_MOLGEIM_ENCOUNTER_DEFEATED
SAY_MOLGEIM_BERSERK
SAY_BRUNDIR_AGGRO
SAY_BRUNDIR_SLAY
SAY_BRUNDIR_SPECIAL
SAY_BRUNDIR_FLIGHT
SAY_BRUNDIR_DEATH
SAY_BRUNDIR_ENCOUNTER_DEFEATED
SAY_BRUNDIR_BERSERK
EMOTE_BRUNDIR_OVERLOAD
{
    SAY_STEELBREAKER_AGGRO                      = 0,
    SAY_STEELBREAKER_SLAY                       = 1,
    SAY_STEELBREAKER_POWER                      = 2,
    SAY_STEELBREAKER_DEATH                      = 3,
    SAY_STEELBREAKER_ENCOUNTER_DEFEATED         = 4,
    SAY_STEELBREAKER_BERSERK                    = 5,
    SAY_MOLGEIM_AGGRO                           = 0,
    SAY_MOLGEIM_SLAY                            = 1,
    SAY_MOLGEIM_RUNE_DEATH                      = 2,
    SAY_MOLGEIM_SUMMON                          = 3,
    SAY_MOLGEIM_DEATH                           = 4,
    SAY_MOLGEIM_ENCOUNTER_DEFEATED              = 5,
    SAY_MOLGEIM_BERSERK                         = 6,
    SAY_BRUNDIR_AGGRO                           = 0,
    SAY_BRUNDIR_SLAY                            = 1,
    SAY_BRUNDIR_SPECIAL                         = 2,
    SAY_BRUNDIR_FLIGHT                          = 3,
    SAY_BRUNDIR_DEATH                           = 4,
    SAY_BRUNDIR_ENCOUNTER_DEFEATED              = 5,
    SAY_BRUNDIR_BERSERK                         = 6,
    EMOTE_BRUNDIR_OVERLOAD                      = 7
};
eEnums
enum eEnums
Enumerator
EVENT_FUSION_PUNCH
EVENT_STATIC_DISRUPTION
EVENT_OVERWHELMING_POWER
EVENT_RUNE_OF_POWER
EVENT_SHIELD_OF_RUNES
EVENT_RUNE_OF_DEATH
EVENT_RUNE_OF_SUMMONING
EVENT_LIGHTNING_BLAST
EVENT_CHAIN_LIGHTNING
EVENT_OVERLOAD
EVENT_LIGHTNING_WHIRL
EVENT_LIGHTNING_TENDRILS
EVENT_LIGHTNING_LAND
EVENT_LAND_LAND
EVENT_LIGHTNING_FLIGHT
EVENT_ENRAGE
{
    // Steelbreaker
    EVENT_FUSION_PUNCH          = 1,
    EVENT_STATIC_DISRUPTION     = 2,
    EVENT_OVERWHELMING_POWER    = 3,
    //EVENT_CHECK_MAIN_TANK     = 4,
    // Molgeim
    EVENT_RUNE_OF_POWER         = 11,
    EVENT_SHIELD_OF_RUNES       = 12,
    EVENT_RUNE_OF_DEATH         = 13,
    EVENT_RUNE_OF_SUMMONING     = 14,
    EVENT_LIGHTNING_BLAST       = 15,
    // Brundir
    EVENT_CHAIN_LIGHTNING       = 21,
    EVENT_OVERLOAD              = 22,
    EVENT_LIGHTNING_WHIRL       = 23,
    EVENT_LIGHTNING_TENDRILS    = 24,
    EVENT_LIGHTNING_LAND        = 25,
    EVENT_LAND_LAND             = 26,
    EVENT_LIGHTNING_FLIGHT      = 27,
    EVENT_ENRAGE                = 30
};
Misc
enum Misc
Enumerator
ACTION_ADD_CHARGE
POINT_CHANNEL_STEELBREAKER
{
    ACTION_ADD_CHARGE           = 1,
    POINT_CHANNEL_STEELBREAKER  = 1
};
Function Documentation
AddSC_boss_assembly_of_iron()
void AddSC_boss_assembly_of_iron ()
{
    new boss_steelbreaker();
    new boss_runemaster_molgeim();
    new boss_stormcaller_brundir();
    new npc_assembly_lightning();
    RegisterSpellScript(spell_shield_of_runes_aura);
    RegisterSpellScript(spell_assembly_meltdown);
    RegisterSpellScript(spell_assembly_rune_of_summoning_aura);
    new achievement_assembly_of_iron("achievement_but_im_on_your_side", 0);
    new achievement_assembly_of_iron("achievement_assembly_steelbreaker", NPC_STEELBREAKER);
    new achievement_assembly_of_iron("achievement_assembly_runemaster", NPC_MOLGEIM);
    new achievement_assembly_of_iron("achievement_assembly_stormcaller", NPC_BRUNDIR);
    new achievement_cant_do_that_while_stunned();
}
References NPC_BRUNDIR, NPC_MOLGEIM, NPC_STEELBREAKER, and RegisterSpellScript.
Referenced by AddNorthrendScripts().
IsEncounterComplete()
bool IsEncounterComplete (InstanceScript * pInstance, Creature * me)
{
    if (!pInstance || !me)
        return false;
    for (uint8 i = 0; i < 3; ++i)
    {
        ObjectGuid guid = pInstance->GetGuidData(DATA_STEELBREAKER + i);
        if (!guid)
            return false;
        if (Creature* boss = (ObjectAccessor::GetCreature(*me, guid)))
        {
            if (boss->IsAlive())
                return false;
            continue;
        }
        else
            return false;
    }
    return true;
}
References DATA_STEELBREAKER, ObjectAccessor::GetCreature(), and InstanceScript::GetGuidData().
Referenced by boss_steelbreaker::boss_steelbreakerAI::JustDied(), boss_runemaster_molgeim::boss_runemaster_molgeimAI::JustDied(), and boss_stormcaller_brundir::boss_stormcaller_brundirAI::JustDied().
RespawnAssemblyOfIron()
void RespawnAssemblyOfIron (InstanceScript * pInstance, Creature * me)
{
    if (!pInstance || !me)
        return;
    for (uint8 i = 0; i < 3; ++i)
    {
        ObjectGuid guid = pInstance->GetGuidData(DATA_STEELBREAKER + i);
        if (!guid)
            return;
        if (Creature* boss = (ObjectAccessor::GetCreature((*me), guid)))
            if (!boss->IsAlive())
                boss->Respawn();
    }
    return;
}
References DATA_STEELBREAKER, ObjectAccessor::GetCreature(), and InstanceScript::GetGuidData().
Referenced by boss_steelbreaker::boss_steelbreakerAI::Reset(), boss_runemaster_molgeim::boss_runemaster_molgeimAI::Reset(), and boss_stormcaller_brundir::boss_stormcaller_brundirAI::Reset().
RestoreAssemblyHealth()
void RestoreAssemblyHealth (ObjectGuid guid1, ObjectGuid guid2, Creature * me)
{
    if (Creature* cr = ObjectAccessor::GetCreature(*me, guid1))
        if (cr->IsAlive())
            cr->SetHealth(cr->GetMaxHealth());
    if (Creature* cr2 = ObjectAccessor::GetCreature(*me, guid2))
        if (cr2->IsAlive())
            cr2->SetHealth(cr2->GetMaxHealth());
}
References ObjectAccessor::GetCreature().
Referenced by boss_steelbreaker::boss_steelbreakerAI::JustDied(), boss_runemaster_molgeim::boss_runemaster_molgeimAI::JustDied(), and boss_stormcaller_brundir::boss_stormcaller_brundirAI::JustDied().