AzerothCore Doxygen
ProcScenarioBuilder Class Reference
Helper class for testing specific proc scenarios.
#include "AuraScriptTestFramework.h"
Public Member Functions
ProcScenarioBuilder ()
~ProcScenarioBuilder ()=default
ProcScenarioBuilder & OnMeleeAutoAttack ()
ProcScenarioBuilder & OnTakenMeleeAutoAttack ()
ProcScenarioBuilder & OnSpellDamage ()
ProcScenarioBuilder & OnTakenSpellDamage ()
ProcScenarioBuilder & OnHeal ()
ProcScenarioBuilder & OnTakenHeal ()
ProcScenarioBuilder & OnPeriodicDamage ()
ProcScenarioBuilder & OnPeriodicHeal ()
ProcScenarioBuilder & OnKill ()
ProcScenarioBuilder & OnDeath ()
ProcScenarioBuilder & WithCrit ()
ProcScenarioBuilder & WithNormalHit ()
ProcScenarioBuilder & WithMiss ()
ProcScenarioBuilder & WithDodge ()
ProcScenarioBuilder & WithParry ()
ProcScenarioBuilder & WithBlock ()
ProcScenarioBuilder & WithFullBlock ()
ProcScenarioBuilder & WithAbsorb ()
ProcScenarioBuilder & OnCast ()
ProcScenarioBuilder & OnHit ()
ProcScenarioBuilder & OnFinish ()
ProcEventInfo Build ()
uint32_t GetTypeMask () const
uint32_t GetHitMask () const
uint32_t GetSpellTypeMask () const
uint32_t GetSpellPhaseMask () const
Private Attributes
uint32_t _typeMask = 0
uint32_t _hitMask = PROC_HIT_NORMAL
uint32_t _spellTypeMask = PROC_SPELL_TYPE_MASK_ALL
uint32_t _spellPhaseMask = PROC_SPELL_PHASE_HIT
bool _needsSpellInfo = false
bool _usesDamageInfo = false
bool _usesHealInfo = false
std::shared_ptr< SpellInfo > _defaultSpellInfo
std::shared_ptr< DamageInfo > _damageInfo
std::shared_ptr< HealInfo > _healInfo
Detailed Description
Helper class for testing specific proc scenarios.
Uses shared_ptr for resource management to allow safe copying in fluent builder pattern usage.
Constructor & Destructor Documentation
ProcScenarioBuilder()
ProcScenarioBuilder::ProcScenarioBuilder () inline
    {
        // Create a default SpellInfo for spell-type procs using shared_ptr
        _defaultSpellInfo = std::shared_ptr<SpellInfo>(
            SpellInfoBuilder()
                .WithId(99999)
                .WithSpellFamilyName(0)
                .Build()
        );
    }
References _defaultSpellInfo, and Build().
~ProcScenarioBuilder()
ProcScenarioBuilder::~ProcScenarioBuilder () default
Member Function Documentation
Build()
ProcEventInfo ProcScenarioBuilder::Build () inline
    {
        auto builder = ProcEventInfoBuilder()
            .WithTypeMask(_typeMask)
            .WithHitMask(_hitMask)
            .WithSpellTypeMask(_spellTypeMask)
            .WithSpellPhaseMask(_spellPhaseMask);
        // Create DamageInfo or HealInfo with SpellInfo for spell-type procs
        if (_needsSpellInfo)
        {
            if (_usesDamageInfo)
            {
                // Create new DamageInfo if needed
                if (!_damageInfo)
                    _damageInfo = std::make_shared<DamageInfo>(nullptr, nullptr, 100, _defaultSpellInfo.get(), SPELL_SCHOOL_MASK_FIRE, SPELL_DIRECT_DAMAGE);
                builder.WithDamageInfo(_damageInfo.get());
            }
            else if (_usesHealInfo)
            {
                // Create new HealInfo if needed
                if (!_healInfo)
                    _healInfo = std::make_shared<HealInfo>(nullptr, nullptr, 100, _defaultSpellInfo.get(), SPELL_SCHOOL_MASK_HOLY);
                builder.WithHealInfo(_healInfo.get());
            }
        }
        return builder.Build();
    }
References _damageInfo, _defaultSpellInfo, _healInfo, _hitMask, _needsSpellInfo, _spellPhaseMask, _spellTypeMask, _typeMask, _usesDamageInfo, _usesHealInfo, SPELL_DIRECT_DAMAGE, SPELL_SCHOOL_MASK_FIRE, SPELL_SCHOOL_MASK_HOLY, ProcEventInfoBuilder::WithHitMask(), ProcEventInfoBuilder::WithSpellPhaseMask(), ProcEventInfoBuilder::WithSpellTypeMask(), and ProcEventInfoBuilder::WithTypeMask().
Referenced by ProcScenarioBuilder(), and TEST_F().
GetHitMask()
uint32_t ProcScenarioBuilder::GetHitMask () const inline
{ return _hitMask; }
References _hitMask.
GetSpellPhaseMask()
uint32_t ProcScenarioBuilder::GetSpellPhaseMask () const inline
{ return _spellPhaseMask; }
References _spellPhaseMask.
GetSpellTypeMask()
uint32_t ProcScenarioBuilder::GetSpellTypeMask () const inline
{ return _spellTypeMask; }
References _spellTypeMask.
GetTypeMask()
uint32_t ProcScenarioBuilder::GetTypeMask () const inline
{ return _typeMask; }
References _typeMask.
OnCast()
ProcScenarioBuilder & ProcScenarioBuilder::OnCast () inline
    {
        _spellPhaseMask = PROC_SPELL_PHASE_CAST;
        return *this;
    }
References _spellPhaseMask, and PROC_SPELL_PHASE_CAST.
Referenced by TEST_F().
OnDeath()
ProcScenarioBuilder & ProcScenarioBuilder::OnDeath () inline
    {
        _typeMask = PROC_FLAG_DEATH;
        _needsSpellInfo = false;
        return *this;
    }
References _needsSpellInfo, _typeMask, and PROC_FLAG_DEATH.
Referenced by TEST_F().
OnFinish()
ProcScenarioBuilder & ProcScenarioBuilder::OnFinish () inline
    {
        _spellPhaseMask = PROC_SPELL_PHASE_FINISH;
        return *this;
    }
References _spellPhaseMask, and PROC_SPELL_PHASE_FINISH.
OnHeal()
ProcScenarioBuilder & ProcScenarioBuilder::OnHeal () inline
    {
        _typeMask = PROC_FLAG_DONE_SPELL_MAGIC_DMG_CLASS_POS;
        _spellTypeMask = PROC_SPELL_TYPE_HEAL;
        _needsSpellInfo = true;
        _usesHealInfo = true;
        return *this;
    }
References _needsSpellInfo, _spellTypeMask, _typeMask, _usesHealInfo, PROC_FLAG_DONE_SPELL_MAGIC_DMG_CLASS_POS, and PROC_SPELL_TYPE_HEAL.
Referenced by TEST_F(), and TEST_F().
OnHit()
ProcScenarioBuilder & ProcScenarioBuilder::OnHit () inline
    {
        _spellPhaseMask = PROC_SPELL_PHASE_HIT;
        return *this;
    }
References _spellPhaseMask, and PROC_SPELL_PHASE_HIT.
Referenced by TEST_F(), TEST_F(), and TEST_F().
OnKill()
ProcScenarioBuilder & ProcScenarioBuilder::OnKill () inline
    {
        _typeMask = PROC_FLAG_KILL;
        _needsSpellInfo = false;
        return *this;
    }
References _needsSpellInfo, _typeMask, and PROC_FLAG_KILL.
Referenced by TEST_F().
OnMeleeAutoAttack()
ProcScenarioBuilder & ProcScenarioBuilder::OnMeleeAutoAttack () inline
    {
        _typeMask = PROC_FLAG_DONE_MELEE_AUTO_ATTACK;
        _needsSpellInfo = false;
        return *this;
    }
References _needsSpellInfo, _typeMask, and PROC_FLAG_DONE_MELEE_AUTO_ATTACK.
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
OnPeriodicDamage()
ProcScenarioBuilder & ProcScenarioBuilder::OnPeriodicDamage () inline
    {
        _typeMask = PROC_FLAG_DONE_PERIODIC;
        _spellTypeMask = PROC_SPELL_TYPE_DAMAGE;
        _needsSpellInfo = true;
        _usesDamageInfo = true;
        return *this;
    }
References _needsSpellInfo, _spellTypeMask, _typeMask, _usesDamageInfo, PROC_FLAG_DONE_PERIODIC, and PROC_SPELL_TYPE_DAMAGE.
Referenced by TEST_F().
OnPeriodicHeal()
ProcScenarioBuilder & ProcScenarioBuilder::OnPeriodicHeal () inline
    {
        _typeMask = PROC_FLAG_DONE_PERIODIC;
        _spellTypeMask = PROC_SPELL_TYPE_HEAL;
        _needsSpellInfo = true;
        _usesHealInfo = true;
        return *this;
    }
References _needsSpellInfo, _spellTypeMask, _typeMask, _usesHealInfo, PROC_FLAG_DONE_PERIODIC, and PROC_SPELL_TYPE_HEAL.
Referenced by TEST_F().
OnSpellDamage()
ProcScenarioBuilder & ProcScenarioBuilder::OnSpellDamage () inline
    {
        _typeMask = PROC_FLAG_DONE_SPELL_MAGIC_DMG_CLASS_NEG;
        _spellTypeMask = PROC_SPELL_TYPE_DAMAGE;
        _needsSpellInfo = true;
        _usesDamageInfo = true;
        return *this;
    }
References _needsSpellInfo, _spellTypeMask, _typeMask, _usesDamageInfo, PROC_FLAG_DONE_SPELL_MAGIC_DMG_CLASS_NEG, and PROC_SPELL_TYPE_DAMAGE.
Referenced by TEST_F(), and TEST_F().
OnTakenHeal()
ProcScenarioBuilder & ProcScenarioBuilder::OnTakenHeal () inline
    {
        _typeMask = PROC_FLAG_TAKEN_SPELL_MAGIC_DMG_CLASS_POS;
        _spellTypeMask = PROC_SPELL_TYPE_HEAL;
        _needsSpellInfo = true;
        _usesHealInfo = true;
        return *this;
    }
References _needsSpellInfo, _spellTypeMask, _typeMask, _usesHealInfo, PROC_FLAG_TAKEN_SPELL_MAGIC_DMG_CLASS_POS, and PROC_SPELL_TYPE_HEAL.
OnTakenMeleeAutoAttack()
ProcScenarioBuilder & ProcScenarioBuilder::OnTakenMeleeAutoAttack () inline
    {
        _typeMask = PROC_FLAG_TAKEN_MELEE_AUTO_ATTACK;
        _needsSpellInfo = false;
        return *this;
    }
References _needsSpellInfo, _typeMask, and PROC_FLAG_TAKEN_MELEE_AUTO_ATTACK.
Referenced by TEST_F(), TEST_F(), TEST_F(), and TEST_F().
OnTakenSpellDamage()
ProcScenarioBuilder & ProcScenarioBuilder::OnTakenSpellDamage () inline
    {
        _typeMask = PROC_FLAG_TAKEN_SPELL_MAGIC_DMG_CLASS_NEG;
        _spellTypeMask = PROC_SPELL_TYPE_DAMAGE;
        _needsSpellInfo = true;
        _usesDamageInfo = true;
        return *this;
    }
References _needsSpellInfo, _spellTypeMask, _typeMask, _usesDamageInfo, PROC_FLAG_TAKEN_SPELL_MAGIC_DMG_CLASS_NEG, and PROC_SPELL_TYPE_DAMAGE.
Referenced by TEST_F().
WithAbsorb()
ProcScenarioBuilder & ProcScenarioBuilder::WithAbsorb () inline
    {
        _hitMask = PROC_HIT_ABSORB;
        return *this;
    }
References _hitMask, and PROC_HIT_ABSORB.
Referenced by TEST_F().
WithBlock()
ProcScenarioBuilder & ProcScenarioBuilder::WithBlock () inline
    {
        _hitMask = PROC_HIT_BLOCK;
        return *this;
    }
References _hitMask, and PROC_HIT_BLOCK.
Referenced by TEST_F().
WithCrit()
ProcScenarioBuilder & ProcScenarioBuilder::WithCrit () inline
    {
        _hitMask = PROC_HIT_CRITICAL;
        return *this;
    }
References _hitMask, and PROC_HIT_CRITICAL.
Referenced by TEST_F(), TEST_F(), and TEST_F().
WithDodge()
ProcScenarioBuilder & ProcScenarioBuilder::WithDodge () inline
    {
        _hitMask = PROC_HIT_DODGE;
        return *this;
    }
References _hitMask, and PROC_HIT_DODGE.
Referenced by TEST_F().
WithFullBlock()
ProcScenarioBuilder & ProcScenarioBuilder::WithFullBlock () inline
    {
        _hitMask = PROC_HIT_FULL_BLOCK;
        return *this;
    }
References _hitMask, and PROC_HIT_FULL_BLOCK.
Referenced by TEST_F().
WithMiss()
ProcScenarioBuilder & ProcScenarioBuilder::WithMiss () inline
    {
        _hitMask = PROC_HIT_MISS;
        return *this;
    }
References _hitMask, and PROC_HIT_MISS.
Referenced by TEST_F(), and TEST_F().
WithNormalHit()
ProcScenarioBuilder & ProcScenarioBuilder::WithNormalHit () inline
    {
        _hitMask = PROC_HIT_NORMAL;
        return *this;
    }
References _hitMask, and PROC_HIT_NORMAL.
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
WithParry()
ProcScenarioBuilder & ProcScenarioBuilder::WithParry () inline
    {
        _hitMask = PROC_HIT_PARRY;
        return *this;
    }
References _hitMask, and PROC_HIT_PARRY.
Referenced by TEST_F().
Member Data Documentation
_damageInfo
std::shared_ptr<DamageInfo> ProcScenarioBuilder::_damageInfo private
Referenced by Build().
_defaultSpellInfo
std::shared_ptr<SpellInfo> ProcScenarioBuilder::_defaultSpellInfo private
Referenced by Build(), and ProcScenarioBuilder().
_healInfo
std::shared_ptr<HealInfo> ProcScenarioBuilder::_healInfo private
Referenced by Build().
_hitMask
uint32_t ProcScenarioBuilder::_hitMask = PROC_HIT_NORMAL private
Referenced by Build(), GetHitMask(), WithAbsorb(), WithBlock(), WithCrit(), WithDodge(), WithFullBlock(), WithMiss(), WithNormalHit(), and WithParry().
_needsSpellInfo
bool ProcScenarioBuilder::_needsSpellInfo = false private
Referenced by Build(), OnDeath(), OnHeal(), OnKill(), OnMeleeAutoAttack(), OnPeriodicDamage(), OnPeriodicHeal(), OnSpellDamage(), OnTakenHeal(), OnTakenMeleeAutoAttack(), and OnTakenSpellDamage().
_spellPhaseMask
uint32_t ProcScenarioBuilder::_spellPhaseMask = PROC_SPELL_PHASE_HIT private
Referenced by Build(), GetSpellPhaseMask(), OnCast(), OnFinish(), and OnHit().
_spellTypeMask
uint32_t ProcScenarioBuilder::_spellTypeMask = PROC_SPELL_TYPE_MASK_ALL private
Referenced by Build(), GetSpellTypeMask(), OnHeal(), OnPeriodicDamage(), OnPeriodicHeal(), OnSpellDamage(), OnTakenHeal(), and OnTakenSpellDamage().
_typeMask
uint32_t ProcScenarioBuilder::_typeMask = 0 private
Referenced by Build(), GetTypeMask(), OnDeath(), OnHeal(), OnKill(), OnMeleeAutoAttack(), OnPeriodicDamage(), OnPeriodicHeal(), OnSpellDamage(), OnTakenHeal(), OnTakenMeleeAutoAttack(), and OnTakenSpellDamage().
_usesDamageInfo
bool ProcScenarioBuilder::_usesDamageInfo = false private
Referenced by Build(), OnPeriodicDamage(), OnSpellDamage(), and OnTakenSpellDamage().
_usesHealInfo
bool ProcScenarioBuilder::_usesHealInfo = false private
Referenced by Build(), OnHeal(), OnPeriodicHeal(), and OnTakenHeal().
The documentation for this class was generated from the following file:
azerothcore-wotlk/src/test/mocks/AuraScriptTestFramework.h