AzerothCore Doxygen
ArenaHookDefaultsTest Class Reference
Protected Member Functions
void SetUp () override
void TearDown () override
Static Protected Member Functions
static void EnsureScriptRegistriesInitialized ()
Protected Attributes
std::unique_ptr< IWorld > previousWorld_
Detailed Description
Tests that ArenaScript and AllBattlegroundScript hooks return safe defaults when no scripts are registered, ensuring core game logic (MemberWon/MemberLost, SaveToDB, etc.) is not accidentally skipped.
Member Function Documentation
EnsureScriptRegistriesInitialized()
static void ArenaHookDefaultsTest::EnsureScriptRegistriesInitialized () inline static protected
    {
        static bool initialized = false;
        if (!initialized)
        {
            ScriptRegistry<ArenaScript>::InitEnabledHooksIfNeeded(ARENAHOOK_END);
            ScriptRegistry<BGScript>::InitEnabledHooksIfNeeded(ALLBATTLEGROUNDHOOK_END);
            initialized = true;
        }
    }
References ALLBATTLEGROUNDHOOK_END, ARENAHOOK_END, and ScriptRegistry< TScript >::InitEnabledHooksIfNeeded().
Referenced by SetUp().
SetUp()
void ArenaHookDefaultsTest::SetUp () inline override protected
    {
        previousWorld_ = std::move(sWorld);
        auto* mock = new ::testing::NiceMock<WorldMock>();
        ON_CALL(*mock, getIntConfig(::testing::_))
            .WillByDefault(::testing::Return(0));
        ON_CALL(*mock, getIntConfig(CONFIG_LEGACY_ARENA_START_RATING))
            .WillByDefault(::testing::Return(1500));
        ON_CALL(*mock, getIntConfig(CONFIG_ARENA_START_RATING))
            .WillByDefault(::testing::Return(0));
        sWorld.reset(mock);
        EnsureScriptRegistriesInitialized();
    }
References CONFIG_ARENA_START_RATING, CONFIG_LEGACY_ARENA_START_RATING, EnsureScriptRegistriesInitialized(), previousWorld_, and sWorld.
TearDown()
void ArenaHookDefaultsTest::TearDown () inline override protected
    {
        sWorld = std::move(previousWorld_);
    }
References previousWorld_, and sWorld.
Member Data Documentation
previousWorld_
std::unique_ptr<IWorld> ArenaHookDefaultsTest::previousWorld_ protected
Referenced by SetUp(), and TearDown().
The documentation for this class was generated from the following file:
azerothcore-wotlk/src/test/server/game/Battlegrounds/ArenaHookDefaultsTest.cpp