AzerothCore Doxygen
LuaQuest Namespace Reference
Functions
int HasFlag (lua_State *L, Quest *quest)
int IsDaily (lua_State *L, Quest *quest)
int IsRepeatable (lua_State *L, Quest *quest)
int GetId (lua_State *L, Quest *quest)
int GetLevel (lua_State *L, Quest *quest)
int GetMinLevel (lua_State *L, Quest *quest)
int GetNextQuestId (lua_State *L, Quest *quest)
int GetPrevQuestId (lua_State *L, Quest *quest)
int GetNextQuestInChain (lua_State *L, Quest *quest)
int GetFlags (lua_State *L, Quest *quest)
int GetType (lua_State *L, Quest *quest)
Function Documentation
GetFlags()
int LuaQuest::GetFlags (lua_State * L, Quest * quest)
Returns the [Quest]'s flags.
Returns
[QuestFlags] flags
    {
#if defined TRINITY || AZEROTHCORE
        Eluna::Push(L, quest->GetFlags());
#else
        Eluna::Push(L, quest->GetQuestFlags());
#endif
        return 1;
    }
References Quest::GetFlags(), and Eluna::Push().
GetId()
int LuaQuest::GetId (lua_State * L, Quest * quest)
Returns entry ID of the [Quest].
Returns
uint32 entryId
    {
        Eluna::Push(L, quest->GetQuestId());
        return 1;
    }
References Quest::GetQuestId(), and Eluna::Push().
GetLevel()
int LuaQuest::GetLevel (lua_State * L, Quest * quest)
Returns the [Quest]'s level.
Returns
uint32 level
    {
        Eluna::Push(L, quest->GetQuestLevel());
        return 1;
    }
References Quest::GetQuestLevel(), and Eluna::Push().
GetMinLevel()
int LuaQuest::GetMinLevel (lua_State * L, Quest * quest)
Returns the minimum level required to pick up the [Quest].
Returns
uint32 minLevel
    {
        Eluna::Push(L, quest->GetMinLevel());
        return 1;
    }
References Quest::GetMinLevel(), and Eluna::Push().
GetNextQuestId()
int LuaQuest::GetNextQuestId (lua_State * L, Quest * quest)
Returns the next [Quest] entry ID.
Returns
int32 entryId
    {
        Eluna::Push(L, quest->GetNextQuestId());
        return 1;
    }
References Quest::GetNextQuestId(), and Eluna::Push().
GetNextQuestInChain()
int LuaQuest::GetNextQuestInChain (lua_State * L, Quest * quest)
Returns the next [Quest] entry ID in the specific [Quest] chain.
Returns
int32 entryId
    {
        Eluna::Push(L, quest->GetNextQuestInChain());
        return 1;
    }
References Quest::GetNextQuestInChain(), and Eluna::Push().
GetPrevQuestId()
int LuaQuest::GetPrevQuestId (lua_State * L, Quest * quest)
Returns the previous [Quest] entry ID.
Returns
int32 entryId
    {
        Eluna::Push(L, quest->GetPrevQuestId());
        return 1;
    }
References Quest::GetPrevQuestId(), and Eluna::Push().
GetType()
int LuaQuest::GetType (lua_State * L, Quest * quest)
Returns the [Quest]'s type.
TODO: Document types available.
Returns
uint32 type
    {
        Eluna::Push(L, quest->GetType());
        return 1;
    }
References Quest::GetType(), and Eluna::Push().
HasFlag()
int LuaQuest::HasFlag (lua_State * L, Quest * quest)
Returns 'true' if the [Quest] has the specified flag, false otherwise. Below flags are based off of 3.3.5a. Subject to change.
enum QuestFlags
{
    // Flags used at server and sent to client
    QUEST_FLAGS_NONE                    = 0x0,
    QUEST_FLAGS_STAY_ALIVE              = 0x1,       // Not used currently
    QUEST_FLAGS_PARTY_ACCEPT            = 0x2,       // Not used currently. If player in party, all players that can accept this quest will receive confirmation box to accept quest CMSG_QUEST_CONFIRM_ACCEPT/SMSG_QUEST_CONFIRM_ACCEPT
    QUEST_FLAGS_EXPLORATION             = 0x4,       // Not used currently
    QUEST_FLAGS_SHARABLE                = 0x8,       // Can be shared: Player::CanShareQuest()
    QUEST_FLAGS_HAS_CONDITION           = 0x10,      // Not used currently
    QUEST_FLAGS_HIDE_REWARD_POI         = 0x20,      // Not used currently: Unsure of content
    QUEST_FLAGS_RAID                    = 0x40,      // Not used currently
    QUEST_FLAGS_TBC                     = 0x80,      // Not used currently: Available if TBC expansion enabled only
    QUEST_FLAGS_NO_MONEY_FROM_XP        = 0x100,     // Not used currently: Experience is not converted to gold at max level
    QUEST_FLAGS_HIDDEN_REWARDS          = 0x200,     // Items and money rewarded only sent in SMSG_QUESTGIVER_OFFER_REWARD (not in SMSG_QUESTGIVER_QUEST_DETAILS or in client quest log(SMSG_QUEST_QUERY_RESPONSE))
    QUEST_FLAGS_TRACKING                = 0x400,     // These quests are automatically rewarded on quest complete and they will never appear in quest log client side.
    QUEST_FLAGS_DEPRECATE_REPUTATION    = 0x800,     // Not used currently
    QUEST_FLAGS_DAILY                   = 0x1000,    // Used to know quest is Daily one
    QUEST_FLAGS_FLAGS_PVP               = 0x2000,    // Having this quest in log forces PvP flag
    QUEST_FLAGS_UNAVAILABLE             = 0x4000,    // Used on quests that are not generically available
    QUEST_FLAGS_WEEKLY                  = 0x8000,
    QUEST_FLAGS_AUTOCOMPLETE            = 0x10000,   // auto complete
    QUEST_FLAGS_DISPLAY_ITEM_IN_TRACKER = 0x20000,   // Displays usable item in quest tracker
    QUEST_FLAGS_OBJ_TEXT                = 0x40000,   // use Objective text as Complete text
    QUEST_FLAGS_AUTO_ACCEPT             = 0x80000,   // The client recognizes this flag as auto-accept. However, NONE of the current quests (3.3.5a) have this flag. Maybe blizz used to use it, or will use it in the future.
    // ... 4.x added flags up to 0x80000000 - all unknown for now
};
Parameters
[QuestFlags] flag : all available flags can be seen above
Returns
bool hasFlag
    {
        uint32 flag = Eluna::CHECKVAL<uint32>(L, 2);
#if defined TRINITY || AZEROTHCORE
        Eluna::Push(L, quest->HasFlag(flag));
#else
        Eluna::Push(L, quest->HasQuestFlag((QuestFlags)flag));
#endif
        return 1;
    }
References Quest::HasFlag(), and Eluna::Push().
IsDaily()
int LuaQuest::IsDaily (lua_State * L, Quest * quest)
Returns 'true' if the [Quest] is a daily quest, false otherwise.
Returns
bool isDaily
    {
        Eluna::Push(L, quest->IsDaily());
        return 1;
    }
References Quest::IsDaily(), and Eluna::Push().
IsRepeatable()
int LuaQuest::IsRepeatable (lua_State * L, Quest * quest)
Returns 'true' if the [Quest] is repeatable, false otherwise.
Returns
bool isRepeatable
    {
        Eluna::Push(L, quest->IsRepeatable());
        return 1;
    }
References Quest::IsRepeatable(), and Eluna::Push().