AzerothCore Doxygen
DamageInfo Class Reference
#include "Unit.h"
Public Member Functions
DamageInfo (Unit *_attacker, Unit *_victim, uint32 _damage, SpellInfo const *_spellInfo, SpellSchoolMask _schoolMask, DamageEffectType _damageType, uint32 cleanDamage=0)
DamageInfo (CalcDamageInfo const &dmgInfo)
DamageInfo (CalcDamageInfo const &dmgInfo, uint8 damageIndex)
DamageInfo (SpellNonMeleeDamage const &spellNonMeleeDamage, DamageEffectType damageType, WeaponAttackType attackType, uint32 hitMask)
DamageInfo (SpellNonMeleeDamage const &spellNonMeleeDamage, DamageEffectType damageType, WeaponAttackType attackType, SpellMissInfo missInfo)
void ModifyDamage (int32 amount)
void AbsorbDamage (uint32 amount)
void ResistDamage (uint32 amount)
void BlockDamage (uint32 amount)
Unit * GetAttacker () const
Unit * GetVictim () const
SpellInfo const * GetSpellInfo () const
SpellSchoolMask GetSchoolMask () const
DamageEffectType GetDamageType () const
WeaponAttackType GetAttackType () const
uint32 GetDamage () const
uint32 GetAbsorb () const
uint32 GetResist () const
uint32 GetBlock () const
uint32 GetHitMask () const
void AddHitMask (uint32 hitMask)
uint32 GetUnmitigatedDamage () const
Private Member Functions
DamageInfo (DamageInfo const &dmg1, DamageInfo const &dmg2)
Private Attributes
Unit *const m_attacker
Unit *const m_victim
uint32 m_damage
SpellInfo const *const m_spellInfo
SpellSchoolMask const m_schoolMask
DamageEffectType const m_damageType
WeaponAttackType m_attackType
uint32 m_absorb
uint32 m_resist
uint32 m_block
uint32 m_cleanDamage
uint32 m_hitMask
Detailed Description
Constructor & Destructor Documentation
DamageInfo() [1/6]
DamageInfo::DamageInfo (DamageInfo const & dmg1, DamageInfo const & dmg2) private
    : m_attacker(dmg1.m_attacker), m_victim(dmg1.m_victim), m_damage(dmg1.m_damage + dmg2.m_damage), m_spellInfo(dmg1.m_spellInfo), m_schoolMask(SpellSchoolMask(dmg1.m_schoolMask | dmg2.m_schoolMask)),
    m_damageType(dmg1.m_damageType), m_attackType(dmg1.m_attackType), m_absorb(dmg1.m_absorb + dmg2.m_absorb), m_resist(dmg1.m_resist + dmg2.m_resist), m_block(dmg1.m_block),
    m_cleanDamage(dmg1.m_cleanDamage + dmg1.m_cleanDamage), m_hitMask(dmg1.m_hitMask | dmg2.m_hitMask)
{
}
DamageInfo() [2/6]
DamageInfo::DamageInfo (Unit * _attacker, Unit * _victim, uint32 _damage, SpellInfo const * _spellInfo, SpellSchoolMask _schoolMask, DamageEffectType _damageType, uint32 cleanDamage = 0) explicit
    : m_attacker(_attacker), m_victim(_victim), m_damage(_damage), m_spellInfo(_spellInfo), m_schoolMask(_schoolMask),
      m_damageType(_damageType), m_attackType(BASE_ATTACK), m_cleanDamage(cleanDamage), m_hitMask(0)
{
    m_absorb = 0;
    m_resist = 0;
    m_block = 0;
}
References m_absorb, m_block, and m_resist.
DamageInfo() [3/6]
DamageInfo::DamageInfo (CalcDamageInfo const & dmgInfo) explicit
                                                    : DamageInfo(DamageInfo(dmgInfo, 0), DamageInfo(dmgInfo, 1))
{
}
DamageInfo() [4/6]
DamageInfo::DamageInfo (CalcDamageInfo const & dmgInfo, uint8 damageIndex)
    : m_attacker(dmgInfo.attacker), m_victim(dmgInfo.target), m_damage(dmgInfo.damages[damageIndex].damage), m_spellInfo(nullptr), m_schoolMask(SpellSchoolMask(dmgInfo.damages[damageIndex].damageSchoolMask)),
      m_damageType(DIRECT_DAMAGE), m_attackType(dmgInfo.attackType), m_absorb(dmgInfo.damages[damageIndex].absorb), m_resist(dmgInfo.damages[damageIndex].resist), m_block(dmgInfo.blocked_amount),
      m_cleanDamage(dmgInfo.cleanDamage), m_hitMask(0)
{
    switch (dmgInfo.hitOutCome)
    {
        case MELEE_HIT_MISS:
            m_hitMask |= PROC_HIT_MISS;
            break;
        case MELEE_HIT_DODGE:
            m_hitMask |= PROC_HIT_DODGE;
            break;
        case MELEE_HIT_PARRY:
            m_hitMask |= PROC_HIT_PARRY;
            break;
        case MELEE_HIT_EVADE:
            m_hitMask |= PROC_HIT_EVADE;
            break;
        case MELEE_HIT_BLOCK:
            m_hitMask |= PROC_HIT_BLOCK;
            [[fallthrough]];
        case MELEE_HIT_CRUSHING:
        case MELEE_HIT_GLANCING:
        case MELEE_HIT_NORMAL:
            m_hitMask |= PROC_HIT_NORMAL;
            break;
        case MELEE_HIT_CRIT:
            m_hitMask |= PROC_HIT_CRITICAL;
            break;
        default:
            break;
    }
    if (dmgInfo.damages[damageIndex].absorb)
        m_hitMask |= PROC_HIT_ABSORB;
    if (dmgInfo.blocked_amount)
        m_hitMask |= (dmgInfo.damages[damageIndex].damage == dmgInfo.blocked_amount) ? PROC_HIT_FULL_BLOCK : PROC_HIT_BLOCK;
}
References CalcDamageInfo::absorb, CalcDamageInfo::blocked_amount, CalcDamageInfo::damage, CalcDamageInfo::damages, CalcDamageInfo::hitOutCome, m_hitMask, MELEE_HIT_BLOCK, MELEE_HIT_CRIT, MELEE_HIT_CRUSHING, MELEE_HIT_DODGE, MELEE_HIT_EVADE, MELEE_HIT_GLANCING, MELEE_HIT_MISS, MELEE_HIT_NORMAL, MELEE_HIT_PARRY, PROC_HIT_ABSORB, PROC_HIT_BLOCK, PROC_HIT_CRITICAL, PROC_HIT_DODGE, PROC_HIT_EVADE, PROC_HIT_FULL_BLOCK, PROC_HIT_MISS, PROC_HIT_NORMAL, and PROC_HIT_PARRY.
DamageInfo() [5/6]
DamageInfo::DamageInfo (SpellNonMeleeDamage const & spellNonMeleeDamage, DamageEffectType damageType, WeaponAttackType attackType, uint32 hitMask)
    : m_attacker(spellNonMeleeDamage.attacker), m_victim(spellNonMeleeDamage.target), m_damage(spellNonMeleeDamage.damage),
      m_spellInfo(spellNonMeleeDamage.spellInfo), m_schoolMask(SpellSchoolMask(spellNonMeleeDamage.schoolMask)), m_damageType(damageType),
      m_attackType(attackType), m_absorb(spellNonMeleeDamage.absorb), m_resist(spellNonMeleeDamage.resist), m_block(spellNonMeleeDamage.blocked),
      m_cleanDamage(spellNonMeleeDamage.cleanDamage), m_hitMask(hitMask)
{
    if (spellNonMeleeDamage.blocked)
        m_hitMask |= PROC_HIT_BLOCK;
    if (spellNonMeleeDamage.absorb)
        m_hitMask |= PROC_HIT_ABSORB;
}
References SpellNonMeleeDamage::absorb, SpellNonMeleeDamage::blocked, m_hitMask, PROC_HIT_ABSORB, and PROC_HIT_BLOCK.
DamageInfo() [6/6]
DamageInfo::DamageInfo (SpellNonMeleeDamage const & spellNonMeleeDamage, DamageEffectType damageType, WeaponAttackType attackType, SpellMissInfo missInfo)
    : m_attacker(spellNonMeleeDamage.attacker), m_victim(spellNonMeleeDamage.target), m_damage(spellNonMeleeDamage.damage),
      m_spellInfo(spellNonMeleeDamage.spellInfo), m_schoolMask(SpellSchoolMask(spellNonMeleeDamage.schoolMask)), m_damageType(damageType),
      m_attackType(attackType), m_absorb(spellNonMeleeDamage.absorb), m_resist(spellNonMeleeDamage.resist), m_block(spellNonMeleeDamage.blocked),
      m_cleanDamage(spellNonMeleeDamage.cleanDamage), m_hitMask(PROC_HIT_NONE)
{
    // Compute hitMask from SpellMissInfo
    if (missInfo != SPELL_MISS_NONE)
    {
        switch (missInfo)
        {
            case SPELL_MISS_MISS:
                m_hitMask |= PROC_HIT_MISS;
                break;
            case SPELL_MISS_RESIST:
                m_hitMask |= PROC_HIT_FULL_RESIST;
                break;
            case SPELL_MISS_DODGE:
                m_hitMask |= PROC_HIT_DODGE;
                break;
            case SPELL_MISS_PARRY:
                m_hitMask |= PROC_HIT_PARRY;
                break;
            case SPELL_MISS_BLOCK:
                m_hitMask |= PROC_HIT_BLOCK;
                break;
            case SPELL_MISS_EVADE:
                m_hitMask |= PROC_HIT_EVADE;
                break;
            case SPELL_MISS_IMMUNE:
            case SPELL_MISS_IMMUNE2:
                m_hitMask |= PROC_HIT_IMMUNE;
                break;
            case SPELL_MISS_DEFLECT:
                m_hitMask |= PROC_HIT_DEFLECT;
                break;
            case SPELL_MISS_ABSORB:
                m_hitMask |= PROC_HIT_ABSORB;
                break;
            case SPELL_MISS_REFLECT:
                m_hitMask |= PROC_HIT_REFLECT;
                break;
            default:
                break;
        }
    }
    else
    {
        // On block
        if (spellNonMeleeDamage.blocked)
            m_hitMask |= PROC_HIT_BLOCK;
        // On absorb
        if (spellNonMeleeDamage.absorb)
            m_hitMask |= PROC_HIT_ABSORB;
        // On crit
        if (spellNonMeleeDamage.HitInfo & SPELL_HIT_TYPE_CRIT)
            m_hitMask |= PROC_HIT_CRITICAL;
        else
            m_hitMask |= PROC_HIT_NORMAL;
    }
}
References SpellNonMeleeDamage::absorb, SpellNonMeleeDamage::blocked, SpellNonMeleeDamage::HitInfo, m_hitMask, PROC_HIT_ABSORB, PROC_HIT_BLOCK, PROC_HIT_CRITICAL, PROC_HIT_DEFLECT, PROC_HIT_DODGE, PROC_HIT_EVADE, PROC_HIT_FULL_RESIST, PROC_HIT_IMMUNE, PROC_HIT_MISS, PROC_HIT_NORMAL, PROC_HIT_PARRY, PROC_HIT_REFLECT, SPELL_HIT_TYPE_CRIT, SPELL_MISS_ABSORB, SPELL_MISS_BLOCK, SPELL_MISS_DEFLECT, SPELL_MISS_DODGE, SPELL_MISS_EVADE, SPELL_MISS_IMMUNE, SPELL_MISS_IMMUNE2, SPELL_MISS_MISS, SPELL_MISS_NONE, SPELL_MISS_PARRY, SPELL_MISS_REFLECT, and SPELL_MISS_RESIST.
Member Function Documentation
AbsorbDamage()
void DamageInfo::AbsorbDamage (uint32 amount)
{
    amount = std::min(amount, GetDamage());
    m_absorb += amount;
    m_damage -= amount;
}
References GetDamage(), m_absorb, and m_damage.
Referenced by spell_mage_fire_frost_ward::Absorb(), Unit::CalcAbsorbResist(), and spell_valanar_kinetic_bomb_absorb_aura::OnAbsorb().
AddHitMask()
void DamageInfo::AddHitMask (uint32 hitMask) inline
{ m_hitMask |= hitMask; }
References m_hitMask.
Referenced by Unit::CalcAbsorbResist().
BlockDamage()
void DamageInfo::BlockDamage (uint32 amount)
{
    amount = std::min(amount, GetDamage());
    m_block += amount;
    m_damage -= amount;
}
References GetDamage(), m_block, and m_damage.
GetAbsorb()
uint32 DamageInfo::GetAbsorb () const inline
{ return m_absorb; };
References m_absorb.
Referenced by Unit::AttackerStateUpdate(), Unit::CalcAbsorbResist(), Unit::CalculateMeleeDamage(), Unit::CalculateSpellDamageTaken(), Unit::DealDamage(), Unit::DealDamageShieldDamage(), Spell::EffectEnvironmentalDMG(), Player::EnvironmentalDamage(), AuraEffect::HandlePeriodicDamageAurasTick(), and AuraEffect::HandlePeriodicHealthLeechAuraTick().
GetAttacker()
Unit * DamageInfo::GetAttacker () const inline
{ return m_attacker; };
References m_attacker.
Referenced by Unit::CalcAbsorbResist(), spell_reflective_shield_aura::HandleAfterEffectAbsorb(), spell_yogg_saron_grim_reprisal_aura::HandleProc(), spell_illidari_council_reflective_shield_aura::ReflectDamage(), and spell_pri_power_word_shield_aura::ReflectDamage().
GetAttackType()
WeaponAttackType DamageInfo::GetAttackType () const inline
{ return m_attackType; };
References m_attackType.
Referenced by Aura::CalcProcChance(), and spell_dk_dancing_rune_weapon::HandleProc().
GetBlock()
uint32 DamageInfo::GetBlock () const inline
{ return m_block; };
References m_block.
Referenced by Unit::AttackerStateUpdate().
GetDamage()
uint32 DamageInfo::GetDamage () const inline
{ return m_damage; };
References m_damage.
Referenced by spell_shield_generator_aura::Absorb(), spell_yogg_saron_protective_gaze_aura::Absorb(), spell_charge_shield_bomber_aura::Absorb(), spell_black_temple_spell_absorption_aura::Absorb(), spell_dk_anti_magic_shell_raid::Absorb(), spell_dk_anti_magic_shell_self::Absorb(), spell_dk_anti_magic_zone::Absorb(), spell_dk_spell_deflection::Absorb(), spell_dk_will_of_the_necropolis::Absorb(), spell_dru_moonkin_form_passive::Absorb(), spell_dru_primal_tenacity::Absorb(), spell_pri_guardian_spirit::Absorb(), spell_rog_cheat_death::Absorb(), spell_rog_nerves_of_steel::Absorb(), spell_sha_astral_shift::Absorb(), spell_mage_fire_frost_ward::Absorb(), spell_pal_ardent_defender::Absorb(), AbsorbDamage(), Unit::AttackerStateUpdate(), BlockDamage(), Unit::CalcAbsorbResist(), Unit::CalculateMeleeDamage(), Unit::CalculateSpellDamageTaken(), SpellProcSpellTypeMaskTest::CalculateSpellTypeMask(), spell_pri_lightwell_renew::CheckDropCharge(), AuraEffect::CheckEffectProc(), spell_deathbringer_blood_link_aura::CheckProc(), spell_deathbringer_blood_link_blood_beast_aura::CheckProc(), spell_dk_scent_of_blood_trigger::CheckProc(), spell_dk_unholy_blight::CheckProc(), spell_dk_necrosis::CheckProc(), spell_item_shadowmourne::CheckProc(), spell_pal_seal_of_righteousness::CheckProc(), spell_sha_nature_guardian::CheckProc(), spell_warl_siphon_life::CheckProc(), spell_warl_fel_synergy::CheckProc(), spell_warr_t3_prot_8p_bonus::CheckProc(), Unit::DealDamage(), Unit::DealDamageShieldDamage(), Spell::EffectEnvironmentalDMG(), Player::EnvironmentalDamage(), AuraEffect::HandleBreakableCCAuraProc(), AuraEffect::HandlePeriodicDamageAurasTick(), AuraEffect::HandlePeriodicHealthLeechAuraTick(), spell_soul_deflection::HandleProc(), spell_reliquary_of_souls_aura_of_desire_aura::HandleProc(), spell_black_temple_consuming_strikes_aura::HandleProc(), spell_gen_petrified_bark::HandleProc(), spell_gen_overlords_brand::HandleProc(), spell_gen_overlords_brand_dot::HandleProc(), spell_item_blood_draining_enchant::HandleProc(), spell_mage_ignite::HandleProc(), spell_anetheron_vampiric_aura::HandleProc(), spell_the_lich_king_dark_hunger_aura::HandleProc(), spell_oculus_temporal_rift_aura::HandleProc(), spell_yogg_saron_grim_reprisal_aura::HandleProc(), spell_twisted_reflection::HandleProc(), spell_dk_blood_gorged::HandleProc(), spell_dk_unholy_blight::HandleProc(), spell_dk_necrosis::HandleProc(), spell_dru_t10_balance_4p_bonus::HandleProc(), spell_gen_vampiric_touch::HandleProc(), spell_gen_earth_shield_toc::HandleProc(), spell_hun_piercing_shots::HandleProc(), spell_item_necrotic_touch::HandleProc(), spell_item_frozen_shadoweave::HandleProc(), spell_item_pet_healing::HandleProc(), spell_pal_righteous_vengeance::HandleProc(), spell_pri_vampiric_embrace::HandleProc(), spell_pri_blessed_recovery::HandleProc(), spell_sha_t8_electrified::HandleProc(), spell_sha_spirit_hunt::HandleProc(), spell_sha_lightning_overload::HandleProc(), spell_sha_t8_elemental_4p_bonus::HandleProc(), spell_sha_t9_elemental_4p_bonus::HandleProc(), spell_warl_seed_of_corruption_aura::HandleProc(), spell_warl_seed_of_corruption_generic_aura::HandleProc(), spell_warl_seed_of_corruption_dummy::HandleProc(), spell_warl_seed_of_corruption_generic::HandleProc(), spell_warl_soul_leech::HandleProc(), spell_dk_wandering_plague_aura::HandleProc(), spell_dk_hungering_cold::HandleProc(), spell_gen_vampiric_might::HandleProc(), spell_gen_mirrored_soul::HandleProc(), ModifyDamage(), spell_valanar_kinetic_bomb_absorb_aura::OnAbsorb(), spell_blood_queen_essence_of_the_blood_queen_aura::OnProc(), spell_pal_eye_for_an_eye::OnProc(), spell_warl_siphon_life::OnProc(), spell_warl_fel_synergy::OnProc(), Unit::ProcSkillsAndAuras(), and ResistDamage().
GetDamageType()
DamageEffectType DamageInfo::GetDamageType () const inline
{ return m_damageType; };
References m_damageType.
Referenced by spell_dk_spell_deflection::Absorb(), and Unit::CalcAbsorbResist().
GetHitMask()
uint32 DamageInfo::GetHitMask () const
{
    return m_hitMask;
}
References m_hitMask.
Referenced by Unit::AttackerStateUpdate(), Unit::CalcAbsorbResist(), Unit::DealMeleeDamage(), Spell::DoAllEffectOnTarget(), AuraEffect::HandlePeriodicPowerBurnAuraTick(), and Unit::TriggerAurasProcOnEvent().
GetResist()
uint32 DamageInfo::GetResist () const inline
{ return m_resist; };
References m_resist.
Referenced by Unit::AttackerStateUpdate(), Unit::CalcAbsorbResist(), Unit::CalculateMeleeDamage(), Unit::CalculateSpellDamageTaken(), Unit::DealDamage(), Spell::EffectEnvironmentalDMG(), Player::EnvironmentalDamage(), AuraEffect::HandlePeriodicDamageAurasTick(), and AuraEffect::HandlePeriodicHealthLeechAuraTick().
GetSchoolMask()
SpellSchoolMask DamageInfo::GetSchoolMask () const inline
{ return m_schoolMask; };
References m_schoolMask.
Referenced by Unit::CalcAbsorbResist(), ProcEventInfo::GetSchoolMask(), spell_dk_acclimation::HandleProc(), and spell_warl_nether_protection::HandleProc().
GetSpellInfo()
SpellInfo const * DamageInfo::GetSpellInfo () const inline
{ return m_spellInfo; };
References m_spellInfo.
Referenced by spell_mage_fire_frost_ward::Absorb(), Unit::CalcAbsorbResist(), spell_mage_ignite::CheckProc(), spell_mage_master_of_elements::CheckProc(), ProcEventInfo::GetSpellInfo(), spell_mage_master_of_elements::HandleProc(), and spell_pri_power_word_shield_aura::ReflectDamage().
GetUnmitigatedDamage()
uint32 DamageInfo::GetUnmitigatedDamage () const
{
    return m_damage + m_cleanDamage + m_absorb + m_resist;
}
References m_absorb, m_cleanDamage, m_damage, and m_resist.
Referenced by spell_rog_blade_flurry::HandleProc().
GetVictim()
Unit * DamageInfo::GetVictim () const inline
{ return m_victim; };
References m_victim.
Referenced by Unit::CalcAbsorbResist().
ModifyDamage()
void DamageInfo::ModifyDamage (int32 amount)
{
    amount = std::min(amount, int32(GetDamage()));
    m_damage += amount;
}
References GetDamage(), and m_damage.
Referenced by AuraEffect::HandlePeriodicHealthLeechAuraTick().
ResistDamage()
void DamageInfo::ResistDamage (uint32 amount)
{
    amount = std::min(amount, GetDamage());
    m_resist += amount;
    m_damage -= amount;
}
References GetDamage(), m_damage, and m_resist.
Referenced by Unit::CalcAbsorbResist().
Member Data Documentation
m_absorb
uint32 DamageInfo::m_absorb private
Referenced by AbsorbDamage(), DamageInfo(), GetAbsorb(), and GetUnmitigatedDamage().
m_attacker
Unit* const DamageInfo::m_attacker private
Referenced by GetAttacker().
m_attackType
WeaponAttackType DamageInfo::m_attackType private
Referenced by GetAttackType().
m_block
uint32 DamageInfo::m_block private
Referenced by BlockDamage(), DamageInfo(), and GetBlock().
m_cleanDamage
uint32 DamageInfo::m_cleanDamage private
Referenced by GetUnmitigatedDamage().
m_damage
uint32 DamageInfo::m_damage private
Referenced by AbsorbDamage(), BlockDamage(), GetDamage(), GetUnmitigatedDamage(), ModifyDamage(), and ResistDamage().
m_damageType
DamageEffectType const DamageInfo::m_damageType private
Referenced by GetDamageType().
m_hitMask
uint32 DamageInfo::m_hitMask private
Referenced by AddHitMask(), DamageInfo(), DamageInfo(), DamageInfo(), and GetHitMask().
m_resist
uint32 DamageInfo::m_resist private
Referenced by DamageInfo(), GetResist(), GetUnmitigatedDamage(), and ResistDamage().
m_schoolMask
SpellSchoolMask const DamageInfo::m_schoolMask private
Referenced by GetSchoolMask().
m_spellInfo
SpellInfo const* const DamageInfo::m_spellInfo private
Referenced by GetSpellInfo().
m_victim
Unit* const DamageInfo::m_victim private
Referenced by GetVictim().
The documentation for this class was generated from the following files:
azerothcore-wotlk/src/server/game/Entities/Unit/Unit.h
azerothcore-wotlk/src/server/game/Entities/Unit/Unit.cpp