AzerothCore Doxygen
PlayerSettingsStore Namespace Reference
Functions
PlayerSettingVector ParseSettingsData (std::string const &data)
std::string SerializeSettingsData (PlayerSettingVector const &settings)
static PlayerSettingVector LoadPlayerSettings (ObjectGuid::LowType playerLowGuid, std::string const &source)
void UpdateSetting (ObjectGuid::LowType playerLowGuid, std::string const &source, uint32 index, uint32 value)
CharacterDatabasePreparedStatement * PrepareReplaceStatement (ObjectGuid::LowType playerLowGuid, std::string const &source, PlayerSettingVector const &settings)
Function Documentation
LoadPlayerSettings()
static PlayerSettingVector PlayerSettingsStore::LoadPlayerSettings (ObjectGuid::LowType playerLowGuid, std::string const & source) static
    {
        PlayerSettingVector result;
        CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_SEL_CHAR_SETTINGS);
        stmt->SetData(0, playerLowGuid);
        PreparedQueryResult dbRes = CharacterDatabase.Query(stmt);
        if (!dbRes)
            return result;
        do
        {
            Field* fields = dbRes->Fetch();
            std::string rowSource = fields[0].Get<std::string>();
            if (rowSource != source)
                continue;
            std::string data = fields[1].Get<std::string>();
            return ParseSettingsData(data);
        } while (dbRes->NextRow());
        return result;
    }
References CHAR_SEL_CHAR_SETTINGS, CharacterDatabase, Field::Get(), ParseSettingsData(), and PreparedStatementBase::SetData().
Referenced by UpdateSetting().
ParseSettingsData()
PlayerSettingVector PlayerSettingsStore::ParseSettingsData (std::string const & data)
    {
        PlayerSettingVector result;
        std::vector<std::string_view> tokens = Acore::Tokenize(data, ' ', false);
        result.reserve(tokens.size());
        for (auto const& token : tokens)
        {
            if (token.empty())
                continue;
            if (auto parsed = Acore::StringTo<uint32>(token))
                result.emplace_back(*parsed);
        }
        return result;
    }
References Acore::Tokenize().
Referenced by Player::_LoadCharacterSettings(), and LoadPlayerSettings().
PrepareReplaceStatement()
CharacterDatabasePreparedStatement * PlayerSettingsStore::PrepareReplaceStatement (ObjectGuid::LowType playerLowGuid, std::string const & source, PlayerSettingVector const & settings)
{
    CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_REP_CHAR_SETTINGS);
    stmt->SetData(0, playerLowGuid);
    stmt->SetData(1, source);
    stmt->SetData(2, SerializeSettingsData(settings));
    return stmt;
}
References CHAR_REP_CHAR_SETTINGS, CharacterDatabase, SerializeSettingsData(), and PreparedStatementBase::SetData().
Referenced by Player::_SavePlayerSettings(), and UpdateSetting().
SerializeSettingsData()
std::string PlayerSettingsStore::SerializeSettingsData (PlayerSettingVector const & settings)
    {
        if (settings.empty())
            return "";
        std::ostringstream data;
        data << settings[0].value << ' ';
        for (size_t i = 1; i < settings.size(); ++i)
            data << settings[i].value << ' ';
        return data.str();
    }
Referenced by PrepareReplaceStatement().
UpdateSetting()
void PlayerSettingsStore::UpdateSetting (ObjectGuid::LowType playerLowGuid, std::string const & source, uint32 index, uint32 value)
    {
        if (!sWorld->getBoolConfig(CONFIG_PLAYER_SETTINGS_ENABLED))
            return;
        PlayerSettingVector settings = LoadPlayerSettings(playerLowGuid, source);
        size_t const requiredSize = static_cast<size_t>(index) + 1;
        if (settings.size() < requiredSize)
            settings.resize(requiredSize); // zero-initialized PlayerSetting::value
        settings[index].value = value;
        CharacterDatabasePreparedStatement* stmt = PlayerSettingsStore::PrepareReplaceStatement(playerLowGuid, source, settings);
        CharacterDatabase.Execute(stmt);
    }
References CharacterDatabase, CONFIG_PLAYER_SETTINGS_ENABLED, LoadPlayerSettings(), PrepareReplaceStatement(), and sWorld.