AzerothCore Doxygen
MapCollisionData Class Reference
#include "MapCollisionData.h"
Public Member Functions
MapCollisionData (Map const &map, Map const *parentMap)
~MapCollisionData ()=default
int LoadVMapTile (uint32 tileX, uint32 tileY)
int LoadMMapTile (uint32 tileX, uint32 tileY)
DynamicVMapCollisionData & GetDynamicTree ()
DynamicVMapCollisionData const & GetDynamicTree () const
StaticVMapCollisionData & GetStaticTree ()
StaticVMapCollisionData const & GetStaticTree () const
MMapData & GetMMapData ()
MMapData const & GetMMapData () const
std::shared_ptr< VMAP::StaticMapTree > const GetStaticTreeSharedPtr () const
std::shared_ptr< dtNavMesh > const GetMMapNavMeshSharedPtr () const
Private Attributes
Map const & _map
DynamicVMapCollisionData _dynamicVMapData
StaticVMapCollisionData _staticVMapData
MMapData _mmapData
Detailed Description
Constructor & Destructor Documentation
MapCollisionData()
MapCollisionData::MapCollisionData (Map const & map, Map const * parentMap)
                                                                       :
    _map(map), _staticVMapData(map.GetId())
{
    if (parentMap)
    {
        // If we have a parent map, point our static tree and mmap nav mesh to the parent maps
        _staticVMapData._staticTree = parentMap->GetMapCollisionData().GetStaticTreeSharedPtr();
        _mmapData._navMesh = parentMap->GetMapCollisionData().GetMMapNavMeshSharedPtr();
    }
    else
    {
        // If we are a base map create a new static tree and mmap nav mesh
        std::string const mapFileName = VMAP::VMapMgr2::getMapFileName(map.GetId());
        std::shared_ptr<VMAP::StaticMapTree> newTree = std::make_shared<VMAP::StaticMapTree>(map.GetId(), (sWorld->GetDataPath() + "vmaps"));
        if (newTree->InitMap(mapFileName))
            _staticVMapData._staticTree = newTree;
        _mmapData._navMesh = MMAP::MMapMgr::LoadNavMesh(map.GetId());
    }
}
References _mmapData, MMapData::_navMesh, StaticVMapCollisionData::_staticTree, _staticVMapData, Map::GetId(), Map::GetMapCollisionData(), VMAP::VMapMgr2::getMapFileName(), GetMMapNavMeshSharedPtr(), GetStaticTreeSharedPtr(), MMAP::MMapMgr::LoadNavMesh(), and sWorld.
~MapCollisionData()
MapCollisionData::~MapCollisionData () default
Member Function Documentation
GetDynamicTree() [1/2]
DynamicVMapCollisionData & MapCollisionData::GetDynamicTree () inline
{ return _dynamicVMapData; }
References _dynamicVMapData.
Referenced by Map::Balance(), Map::CheckCollisionAndGetValidCoords(), Map::ContainsGameObjectModel(), Map::GetAreaInfo(), Map::GetDynamicMapTree(), Map::GetGameObjectFloor(), Map::GetHeight(), Map::InsertGameObjectModel(), Map::isInLineOfSight(), Map::RemoveGameObjectModel(), Spell::SelectImplicitCasterDestTargets(), and Map::Update().
GetDynamicTree() [2/2]
DynamicVMapCollisionData const & MapCollisionData::GetDynamicTree () const inline
{ return _dynamicVMapData; }
References _dynamicVMapData.
GetMMapData() [1/2]
MMapData & MapCollisionData::GetMMapData () inline
{ return _mmapData; }
References _mmapData.
Referenced by misc_commandscript::HandleGPSCommand(), mmaps_commandscript::HandleMmapLoadedTilesCommand(), mmaps_commandscript::HandleMmapLocCommand(), mmaps_commandscript::HandleMmapPathCommand(), mmaps_commandscript::HandleMmapStatsCommand(), and PathGenerator::PathGenerator().
GetMMapData() [2/2]
MMapData const & MapCollisionData::GetMMapData () const inline
{ return _mmapData; }
References _mmapData.
GetMMapNavMeshSharedPtr()
std::shared_ptr< dtNavMesh > const MapCollisionData::GetMMapNavMeshSharedPtr () const inline
{ return _mmapData._navMesh; }
References _mmapData, and MMapData::_navMesh.
Referenced by MapCollisionData().
GetStaticTree() [1/2]
StaticVMapCollisionData & MapCollisionData::GetStaticTree () inline
{ return _staticVMapData; }
References _staticVMapData.
Referenced by Map::CheckCollisionAndGetValidCoords(), Map::GetAreaInfo(), Map::GetFullTerrainStatusForPosition(), Map::GetHeight(), Map::GetLiquidData(), Map::isInLineOfSight(), spell_entropius_black_hole_effect::RaycastToObstacle(), and Spell::SelectImplicitCasterDestTargets().
GetStaticTree() [2/2]
StaticVMapCollisionData const & MapCollisionData::GetStaticTree () const inline
{ return _staticVMapData; }
References _staticVMapData.
GetStaticTreeSharedPtr()
std::shared_ptr< VMAP::StaticMapTree > const MapCollisionData::GetStaticTreeSharedPtr () const inline
{ return _staticVMapData._staticTree; }
References StaticVMapCollisionData::_staticTree, and _staticVMapData.
Referenced by MapCollisionData().
LoadMMapTile()
int MapCollisionData::LoadMMapTile (uint32 tileX, uint32 tileY)
{
    if (!DisableMgr::IsPathfindingEnabled(&_map) || !_mmapData._navMesh)
        return MMAP::MMAP_LOAD_RESULT_IGNORED;
    return MMAP::MMapMgr::LoadTile(_mmapData._navMesh.get(), _map.GetId(), tileX, tileY);
}
References _map, _mmapData, MMapData::_navMesh, Map::GetId(), DisableMgr::IsPathfindingEnabled(), MMAP::MMapMgr::LoadTile(), and MMAP::MMAP_LOAD_RESULT_IGNORED.
Referenced by GridTerrainLoader::LoadMMap().
LoadVMapTile()
int MapCollisionData::LoadVMapTile (uint32 tileX, uint32 tileY)
{
    if (!VMAP::VMapFactory::createOrGetVMapMgr()->isMapLoadingEnabled() || !_staticVMapData._staticTree)
        return VMAP::VMAP_LOAD_RESULT_IGNORED;
    if (!_staticVMapData._staticTree->LoadMapTile(tileX, tileY))
        return VMAP::VMAP_LOAD_RESULT_ERROR;
    return VMAP::VMAP_LOAD_RESULT_OK;
}
References StaticVMapCollisionData::_staticTree, _staticVMapData, VMAP::VMapFactory::createOrGetVMapMgr(), VMAP::VMAP_LOAD_RESULT_ERROR, VMAP::VMAP_LOAD_RESULT_IGNORED, and VMAP::VMAP_LOAD_RESULT_OK.
Referenced by GridTerrainLoader::LoadVMap().
Member Data Documentation
_dynamicVMapData
DynamicVMapCollisionData MapCollisionData::_dynamicVMapData private
Referenced by GetDynamicTree(), and GetDynamicTree().
_map
Map const& MapCollisionData::_map private
Referenced by LoadMMapTile().
_mmapData
MMapData MapCollisionData::_mmapData private
Referenced by GetMMapData(), GetMMapData(), GetMMapNavMeshSharedPtr(), LoadMMapTile(), and MapCollisionData().
_staticVMapData
StaticVMapCollisionData MapCollisionData::_staticVMapData private
Referenced by GetStaticTree(), GetStaticTree(), GetStaticTreeSharedPtr(), LoadVMapTile(), and MapCollisionData().
The documentation for this class was generated from the following files:
azerothcore-wotlk/src/server/game/Maps/MapCollisionData.h
azerothcore-wotlk/src/server/game/Maps/MapCollisionData.cpp