AzerothCore Doxygen
GridObjectLoader Class Reference
#include "GridObjectLoader.h"
Public Member Functions
GridObjectLoader (MapGridType &grid, Map *map)
void LoadAllCellsInGrid ()
Private Member Functions
template<class T >
void AddObjectHelper (Map *map, T *obj)
void LoadCreatures (CellGuidSet const &guid_set, Map *map)
void LoadGameObjects (CellGuidSet const &guid_set, Map *map)
Private Attributes
MapGridType & _grid
Map * _map
Detailed Description
Constructor & Destructor Documentation
GridObjectLoader()
GridObjectLoader::GridObjectLoader (MapGridType & grid, Map * map) inline
        : _grid(grid), _map(map) { }
Member Function Documentation
AddObjectHelper()
template<class T > void GridObjectLoader::AddObjectHelper (Map * map, T * obj) private
{
    CellCoord cellCoord = Acore::ComputeCellCoord(obj->GetPositionX(), obj->GetPositionY());
    Cell cell(cellCoord);
    map->AddToGrid(obj, cell);
    obj->AddToWorld();
    if (obj->isActiveObject())
        map->AddToActive(obj);
}
References Map::AddToActive(), Map::AddToGrid(), and Acore::ComputeCellCoord().
LoadAllCellsInGrid()
void GridObjectLoader::LoadAllCellsInGrid ()
{
    CellObjectGuids const& cell_guids = sObjectMgr->GetGridObjectGuids(_map->GetId(), _map->GetSpawnMode(), _grid.GetId());
    LoadGameObjects(cell_guids.gameobjects, _map);
    LoadCreatures(cell_guids.creatures, _map);
    if (std::unordered_set<Corpse*> const* corpses = _map->GetCorpsesInCell(_grid.GetId()))
    {
        for (Corpse* corpse : *corpses)
        {
            if (corpse->IsInGrid())
                continue;
            CellCoord cellCoord = Acore::ComputeCellCoord(corpse->GetPositionX(), corpse->GetPositionY());
            Cell cell(cellCoord);
            if (corpse->IsWorldObject())
                _grid.AddWorldObject(cell.CellX(), cell.CellY(), corpse);
            else
                _grid.AddGridObject(cell.CellX(), cell.CellY(), corpse);
        }
    }
}
References _grid, _map, MapGrid< WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES >::AddGridObject(), MapGrid< WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES >::AddWorldObject(), Cell::CellX(), Cell::CellY(), Acore::ComputeCellCoord(), CellObjectGuids::creatures, CellObjectGuids::gameobjects, Map::GetCorpsesInCell(), MapGrid< WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES >::GetId(), Map::GetId(), Map::GetSpawnMode(), LoadCreatures(), LoadGameObjects(), and sObjectMgr.
Referenced by MapGridManager::LoadGrid().
LoadCreatures()
void GridObjectLoader::LoadCreatures (CellGuidSet const & guid_set, Map * map) private
{
    for (ObjectGuid::LowType const& guid : guid_set)
    {
        Creature* obj = new Creature();
        if (!obj->LoadFromDB(guid, map))
        {
            delete obj;
            continue;
        }
        AddObjectHelper<Creature>(map, obj);
        if (!obj->IsMoveInLineOfSightDisabled() && obj->GetDefaultMovementType() == IDLE_MOTION_TYPE && !obj->isNeedNotify(NOTIFY_VISIBILITY_CHANGED | NOTIFY_AI_RELOCATION))
        {
            if (obj->IsAlive() && !obj->HasUnitState(UNIT_STATE_SIGHTLESS) && obj->HasReactState(REACT_AGGRESSIVE) && !obj->IsImmuneToNPC())
            {
                // call MoveInLineOfSight for nearby grid creatures
                Acore::AIRelocationNotifier notifier(*obj);
                Cell::VisitGridObjects(obj, notifier, 60.f);
            }
        }
    }
}
References Creature::GetDefaultMovementType(), Creature::HasReactState(), Unit::HasUnitState(), IDLE_MOTION_TYPE, Unit::IsAlive(), Unit::IsImmuneToNPC(), Creature::IsMoveInLineOfSightDisabled(), WorldObject::isNeedNotify(), Creature::LoadFromDB(), NOTIFY_AI_RELOCATION, NOTIFY_VISIBILITY_CHANGED, REACT_AGGRESSIVE, UNIT_STATE_SIGHTLESS, and Cell::VisitGridObjects().
Referenced by LoadAllCellsInGrid().
LoadGameObjects()
void GridObjectLoader::LoadGameObjects (CellGuidSet const & guid_set, Map * map) private
{
    for (ObjectGuid::LowType const& guid : guid_set)
    {
        GameObjectData const* data = sObjectMgr->GetGameObjectData(guid);
        GameObject* obj = data && sObjectMgr->IsGameObjectStaticTransport(data->id) ? new StaticTransport() : new GameObject();
        if (!obj->LoadFromDB(guid, map))
        {
            delete obj;
            continue;
        }
        AddObjectHelper<GameObject>(map, obj);
    }
}
References GameObjectData::id, GameObject::LoadFromDB(), and sObjectMgr.
Referenced by LoadAllCellsInGrid().
Member Data Documentation
_grid
MapGridType& GridObjectLoader::_grid private
Referenced by LoadAllCellsInGrid().
_map
Map* GridObjectLoader::_map private
Referenced by LoadAllCellsInGrid().
The documentation for this class was generated from the following files:
azerothcore-wotlk/src/server/game/Grids/GridObjectLoader.h
azerothcore-wotlk/src/server/game/Grids/GridObjectLoader.cpp