AzerothCore Doxygen
LuaGuild Namespace Reference
Functions
int GetMembers (lua_State *L, Guild *guild)
int GetMemberCount (lua_State *L, Guild *guild)
int GetLeader (lua_State *L, Guild *guild)
int GetLeaderGUID (lua_State *L, Guild *guild)
int GetId (lua_State *L, Guild *guild)
int GetName (lua_State *L, Guild *guild)
int GetMOTD (lua_State *L, Guild *guild)
int GetInfo (lua_State *L, Guild *guild)
int SetBankTabText (lua_State *L, Guild *guild)
int SendPacket (lua_State *L, Guild *guild)
int SendPacketToRanked (lua_State *L, Guild *guild)
int Disband (lua_State *, Guild *guild)
int AddMember (lua_State *L, Guild *guild)
int DeleteMember (lua_State *L, Guild *guild)
int SetMemberRank (lua_State *L, Guild *guild)
Function Documentation
AddMember()
int LuaGuild::AddMember (lua_State * L, Guild * guild)
Adds the specified [Player] to the [Guild] at the specified rank.
If no rank is specified, defaults to none.
Parameters
[Player] player : the [Player] to be added to the guild
uint8 rankId : the rank ID
    {
        Player* player = Eluna::CHECKOBJ<Player>(L, 2);
        uint8 rankId = Eluna::CHECKVAL<uint8>(L, 3, GUILD_RANK_NONE);
#ifdef TRINITY
        CharacterDatabaseTransaction trans(nullptr);
        guild->AddMember(trans, player->GET_GUID(), rankId);
#else
        guild->AddMember(player->GET_GUID(), rankId);
#endif
        return 0;
    }
References Guild::AddMember(), and GUILD_RANK_NONE.
DeleteMember()
int LuaGuild::DeleteMember (lua_State * L, Guild * guild)
Removes the specified [Player] from the [Guild].
Parameters
[Player] player : the [Player] to be removed from the guild
bool isDisbanding : default 'false', should only be set to 'true' if the guild is triggered to disband
    {
        Player* player = Eluna::CHECKOBJ<Player>(L, 2);
        bool isDisbanding = Eluna::CHECKVAL<bool>(L, 3, false);
#if defined TRINITY
        CharacterDatabaseTransaction trans(nullptr);
        guild->DeleteMember(trans, player->GET_GUID(), isDisbanding);
#elif defined AZEROTHCORE
        guild->DeleteMember(player->GET_GUID(), isDisbanding);
#else
        guild->DelMember(player->GET_GUID(), isDisbanding);
#endif
        return 0;
    }
References Guild::DeleteMember().
Disband()
int LuaGuild::Disband (lua_State * , Guild * guild)
Disbands the [Guild]
    {
        guild->Disband();
        return 0;
    }
References Guild::Disband().
GetId()
int LuaGuild::GetId (lua_State * L, Guild * guild)
Returns the [Guild]s entry ID
Returns
uint32 entryId
    {
        Eluna::Push(L, guild->GetId());
        return 1;
    }
References Guild::GetId(), and Eluna::Push().
GetInfo()
int LuaGuild::GetInfo (lua_State * L, Guild * guild)
Returns the [Guild]s current info
Returns
string guildInfo
    {
#if defined TRINITY || AZEROTHCORE
        Eluna::Push(L, guild->GetInfo());
#else
        Eluna::Push(L, guild->GetGINFO());
#endif
        return 1;
    }
References Guild::GetInfo(), and Eluna::Push().
GetLeader()
int LuaGuild::GetLeader (lua_State * L, Guild * guild)
Finds and returns the [Guild] leader by their GUID if logged in
Returns
[Player] leader
    {
#if defined TRINITY || AZEROTHCORE
        Eluna::Push(L, eObjectAccessor()FindPlayer(guild->GetLeaderGUID()));
#else
        Eluna::Push(L, eObjectAccessor()FindPlayer(guild->GetLeaderGuid()));
#endif
        return 1;
    }
References eObjectAccessor, Guild::GetLeaderGUID(), and Eluna::Push().
GetLeaderGUID()
int LuaGuild::GetLeaderGUID (lua_State * L, Guild * guild)
Returns [Guild] leader GUID
Returns
ObjectGuid leaderGUID
    {
#if defined TRINITY || AZEROTHCORE
        Eluna::Push(L, guild->GetLeaderGUID());
#else
        Eluna::Push(L, guild->GetLeaderGuid());
#endif
        return 1;
    }
References Guild::GetLeaderGUID(), and Eluna::Push().
GetMemberCount()
int LuaGuild::GetMemberCount (lua_State * L, Guild * guild)
Returns the member count of this [Guild]
Returns
uint32 memberCount
    {
#if defined TRINITY || AZEROTHCORE
        Eluna::Push(L, guild->GetMemberCount());
#else
        Eluna::Push(L, guild->GetMemberSize());
#endif
        return 1;
    }
References Guild::GetMemberCount(), Guild::GetMemberSize(), and Eluna::Push().
GetMembers()
int LuaGuild::GetMembers (lua_State * L, Guild * guild)
Returns a table with the [Player]s in this [Guild]
Only the players that are online and on some map.
Returns
table guildPlayers : table of [Player]s
    {
        lua_newtable(L);
        int tbl = lua_gettop(L);
        uint32 i = 0;
#if defined(MANGOS)
        eObjectAccessor()DoForAllPlayers([&](Player* player)
        {
            if (player->IsInWorld() && player->GetGuildId() == guild->GetId())
            {
                Eluna::Push(L, player);
                lua_rawseti(L, tbl, ++i);
            }
        });
#else
        {
#if defined TRINITY || AZEROTHCORE
            std::shared_lock<std::shared_mutex> lock(*HashMapHolder<Player>::GetLock());
#else
            HashMapHolder<Player>::ReadGuard g(HashMapHolder<Player>::GetLock());
#endif
            const HashMapHolder<Player>::MapType& m = eObjectAccessor()GetPlayers();
            for (HashMapHolder<Player>::MapType::const_iterator it = m.begin(); it != m.end(); ++it)
            {
                if (Player* player = it->second)
                {
                    if (player->IsInWorld() && player->GetGuildId() == guild->GetId())
                    {
                        Eluna::Push(L, player);
                        lua_rawseti(L, tbl, ++i);
                    }
                }
            }
        }
#endif
        lua_settop(L, tbl); // push table to top of stack
        return 1;
    }
References eObjectAccessor, Player::GetGuildId(), Guild::GetId(), Object::IsInWorld(), lua_gettop(), lua_newtable, lua_rawseti(), lua_settop(), and Eluna::Push().
GetMOTD()
int LuaGuild::GetMOTD (lua_State * L, Guild * guild)
Returns the [Guild]s current Message Of The Day
Returns
string guildMOTD
    {
        Eluna::Push(L, guild->GetMOTD());
        return 1;
    }
References Guild::GetMOTD(), and Eluna::Push().
GetName()
int LuaGuild::GetName (lua_State * L, Guild * guild)
Returns the [Guild]s name
Returns
string guildName
    {
        Eluna::Push(L, guild->GetName());
        return 1;
    }
References Guild::GetName(), and Eluna::Push().
SendPacket()
int LuaGuild::SendPacket (lua_State * L, Guild * guild)
Sends a [WorldPacket] to all the [Player]s in the [Guild]
Parameters
[WorldPacket] packet : the [WorldPacket] to be sent to the [Player]s
    {
        WorldPacket* data = Eluna::CHECKOBJ<WorldPacket>(L, 2);
#ifdef CMANGOS
        guild->BroadcastPacket(*data);
#else
        guild->BroadcastPacket(data);
#endif
        return 0;
    }
References Guild::BroadcastPacket().
SendPacketToRanked()
int LuaGuild::SendPacketToRanked (lua_State * L, Guild * guild)
Sends a [WorldPacket] to all the [Player]s at the specified rank in the [Guild]
Parameters
[WorldPacket] packet : the [WorldPacket] to be sent to the [Player]s
uint8 rankId : the rank ID
    {
        WorldPacket* data = Eluna::CHECKOBJ<WorldPacket>(L, 2);
        uint8 ranked = Eluna::CHECKVAL<uint8>(L, 3);
#ifdef CMANGOS
        guild->BroadcastPacketToRank(*data, ranked);
#else
        guild->BroadcastPacketToRank(data, ranked);
#endif
        return 0;
    }
References Guild::BroadcastPacketToRank().
SetBankTabText()
int LuaGuild::SetBankTabText (lua_State * L, Guild * guild)
Sets the information of the bank tab specified
Parameters
uint8 tabId : the ID of the tab specified
string info : the information to be set to the bank tab
    {
        uint8 tabId = Eluna::CHECKVAL<uint8>(L, 2);
        const char* text = Eluna::CHECKVAL<const char*>(L, 3);
#if defined TRINITY || AZEROTHCORE
        guild->SetBankTabText(tabId, text);
#else
        guild->SetGuildBankTabText(tabId, text);
#endif
        return 0;
    }
References Guild::SetBankTabText().
SetMemberRank()
int LuaGuild::SetMemberRank (lua_State * L, Guild * guild)
Promotes/demotes the [Player] to the specified rank.
Parameters
[Player] player : the [Player] to be promoted/demoted
uint8 rankId : the rank ID
    {
        Player* player = Eluna::CHECKOBJ<Player>(L, 2);
        uint8 newRank = Eluna::CHECKVAL<uint8>(L, 3);
#ifdef TRINITY
        CharacterDatabaseTransaction trans(nullptr);
        guild->ChangeMemberRank(trans, player->GET_GUID(), newRank);
#else
        guild->ChangeMemberRank(player->GET_GUID(), newRank);
#endif
        return 0;
    }
References Guild::ChangeMemberRank().