AzerothCore Doxygen
OutdoorPvPNA.cpp File Reference
#include "OutdoorPvPNA.h"
#include "CreatureScript.h"
#include "GameGraveyard.h"
#include "GridNotifiers.h"
#include "Language.h"
#include "MapMgr.h"
#include "ObjectMgr.h"
#include "OutdoorPvPMgr.h"
#include "OutdoorPvPScript.h"
#include "Player.h"
#include "ScriptedCreature.h"
#include "World.h"
#include "WorldPacket.h"
#include "WorldSessionMgr.h"
Classes
class OutdoorPvP_nagrand
struct outdoorpvp_na_halaa_creatures
Functions
void UpdateCreatureHalaa (ObjectGuid::LowType spawnId, Map *map, float x, float y)
void FlagPlayerPvP (Player *player)
void AddSC_outdoorpvp_na ()
Variables
HalaaNPCS halaaNPCHorde
HalaaNPCS halaaNPCAlly
Function Documentation
AddSC_outdoorpvp_na()
void AddSC_outdoorpvp_na ()
{
    new OutdoorPvP_nagrand();
    RegisterCreatureAI(outdoorpvp_na_halaa_creatures);
}
References RegisterCreatureAI.
Referenced by AddOutdoorPvPScripts().
FlagPlayerPvP()
void FlagPlayerPvP (Player * player)
{
    player->SetPlayerFlag(PLAYER_FLAGS_IN_PVP);
    player->UpdatePvP(true, true);
}
References PLAYER_FLAGS_IN_PVP, Player::SetPlayerFlag(), and Player::UpdatePvP().
Referenced by OPvPCapturePointNA::HandleCustomSpell(), and OPvPCapturePointNA::HandleOpenGo().
UpdateCreatureHalaa()
void UpdateCreatureHalaa (ObjectGuid::LowType spawnId, Map * map, float x, float y)
{
    CreatureData& data = sObjectMgr->NewOrExistCreatureData(spawnId);
    sObjectMgr->AddCreatureToGrid(spawnId, &data);
    // Spawn if necessary (loaded grids only)
    if (!map->Instanceable() && !map->IsGridCreated(x, y))
    {
        Creature* creature = new Creature();
        if (!creature->LoadCreatureFromDB(spawnId, map, true, true))
        {
            LOG_ERROR("sql.sql", "AddCreature: Cannot add creature spawnId {} to map", spawnId);
            delete creature;
            return;
        }
    }
}
References Map::Instanceable(), Map::IsGridCreated(), Creature::LoadCreatureFromDB(), LOG_ERROR, and sObjectMgr.
Referenced by OPvPCapturePointNA::SpawnNPCsForTeam().
Variable Documentation
halaaNPCAlly
HalaaNPCS halaaNPCAlly
Referenced by OPvPCapturePointNA::FactionTakeOver(), OPvPCapturePointNA::Update(), and outdoorpvp_na_halaa_creatures::UpdateAI().
halaaNPCHorde
HalaaNPCS halaaNPCHorde
Referenced by OPvPCapturePointNA::FactionTakeOver(), OPvPCapturePointNA::Update(), and outdoorpvp_na_halaa_creatures::UpdateAI().