AzerothCore Doxygen
SpellProcArcanePotencyTest.cpp File Reference
Unit tests for Arcane Potency proc behavior.
#include "AuraScriptTestFramework.h"
#include "SpellMgr.h"
#include "gtest/gtest.h"
Classes
class ArcanePotencyProcTest
Functions
TEST_F (ArcanePotencyProcTest, ProcEntry_HasReqSpellmodAttribute)
TEST_F (ArcanePotencyProcTest, ProcEntry_CastPhaseOnly)
TEST_F (ArcanePotencyProcTest, ProcEntry_MageFamily)
TEST_F (ArcanePotencyProcTest, ProcEntry_BothRanksIdentical)
TEST_F (ArcanePotencyProcTest, FamilyMask_Fireball_Matches)
TEST_F (ArcanePotencyProcTest, FamilyMask_Frostbolt_Matches)
TEST_F (ArcanePotencyProcTest, FamilyMask_ArcaneBlast_Matches)
TEST_F (ArcanePotencyProcTest, FamilyMask_ArcaneExplosion_Matches)
TEST_F (ArcanePotencyProcTest, FamilyMask_FrostfireBolt_Matches)
TEST_F (ArcanePotencyProcTest, FamilyMask_FireBlast_Matches)
TEST_F (ArcanePotencyProcTest, FamilyMask_Scorch_Matches)
TEST_F (ArcanePotencyProcTest, FamilyMask_ArcaneMissiles_DoesNotMatch)
TEST_F (ArcanePotencyProcTest, FamilyMask_IceLance_DoesNotMatch)
TEST_F (ArcanePotencyProcTest, FamilyMask_ArcaneBarrage_DoesNotMatch)
TEST_F (ArcanePotencyProcTest, FamilyMask_NonMageSpell_DoesNotMatch)
TEST_F (ArcanePotencyProcTest, Phase_TriggersOnCast)
TEST_F (ArcanePotencyProcTest, Phase_DoesNotTriggerOnHit)
TEST_F (ArcanePotencyProcTest, Phase_DoesNotTriggerOnFinish)
TEST_F (ArcanePotencyProcTest, ReqSpellmod_AuraWithCharges_BlocksWithoutAppliedMod)
TEST_F (ArcanePotencyProcTest, ReqSpellmod_AuraWithoutCharges_SkipsCheck)
TEST_F (ArcanePotencyProcTest, MaskBits_CorrectBitsSet)
TEST_F (ArcanePotencyProcTest, MaskBits_CorrectBitsNotSet)
Detailed Description
Unit tests for Arcane Potency proc behavior.
Arcane Potency (57529/57531) buffs should only be consumed by the spell that was actually affected by the crit bonus, not by the same cast that triggered them. This is achieved via PROC_ATTR_REQ_SPELLMOD (0x08) which requires the proccing aura to be in the triggering spell's m_appliedMods.
The crit aura registration in SpellDoneCritChance ensures that only spells whose crit chance was actually modified by Arcane Potency will have it in their m_appliedMods set.
References:
TrinityCore commit 81f16b201b
ChromieCraft issue #9092
Definition in file SpellProcArcanePotencyTest.cpp.
Function Documentation
TEST_F() [1/22]
TEST_F (ArcanePotencyProcTest , FamilyMask_ArcaneBarrage_DoesNotMatch)
{
    auto* spell = CreateSpellInfo(44425, SPELLFAMILY_MAGE, 0, ARCANE_BARRAGE_FLAG1);
    auto procEntry = BuildArcanePotencyProcEntry();
    EXPECT_FALSE(TestSpellFamilyMatch(procEntry.SpellFamilyName, procEntry.SpellFamilyMask, spell));
}
References SPELLFAMILY_MAGE.
TEST_F() [2/22]
TEST_F (ArcanePotencyProcTest , FamilyMask_ArcaneBlast_Matches)
{
    auto* spell = CreateSpellInfo(30451, SPELLFAMILY_MAGE, ARCANE_BLAST_FLAG0);
    auto procEntry = BuildArcanePotencyProcEntry();
    EXPECT_TRUE(TestSpellFamilyMatch(procEntry.SpellFamilyName, procEntry.SpellFamilyMask, spell));
}
References SPELLFAMILY_MAGE.
TEST_F() [3/22]
TEST_F (ArcanePotencyProcTest , FamilyMask_ArcaneExplosion_Matches)
{
    auto* spell = CreateSpellInfo(1449, SPELLFAMILY_MAGE, ARCANE_EXPLOSION_FLAG0);
    auto procEntry = BuildArcanePotencyProcEntry();
    EXPECT_TRUE(TestSpellFamilyMatch(procEntry.SpellFamilyName, procEntry.SpellFamilyMask, spell));
}
References SPELLFAMILY_MAGE.
TEST_F() [4/22]
TEST_F (ArcanePotencyProcTest , FamilyMask_ArcaneMissiles_DoesNotMatch)
{
    auto* spell = CreateSpellInfo(5143, SPELLFAMILY_MAGE, ARCANE_MISSILES_FLAG0);
    auto procEntry = BuildArcanePotencyProcEntry();
    EXPECT_FALSE(TestSpellFamilyMatch(procEntry.SpellFamilyName, procEntry.SpellFamilyMask, spell));
}
References SPELLFAMILY_MAGE.
TEST_F() [5/22]
TEST_F (ArcanePotencyProcTest , FamilyMask_Fireball_Matches)
{
    auto* spell = CreateSpellInfo(133, SPELLFAMILY_MAGE, FIREBALL_FLAG0);
    auto procEntry = BuildArcanePotencyProcEntry();
    EXPECT_TRUE(TestSpellFamilyMatch(procEntry.SpellFamilyName, procEntry.SpellFamilyMask, spell));
}
References SPELLFAMILY_MAGE.
TEST_F() [6/22]
TEST_F (ArcanePotencyProcTest , FamilyMask_FireBlast_Matches)
{
    auto* spell = CreateSpellInfo(2136, SPELLFAMILY_MAGE, FIRE_BLAST_FLAG0);
    auto procEntry = BuildArcanePotencyProcEntry();
    EXPECT_TRUE(TestSpellFamilyMatch(procEntry.SpellFamilyName, procEntry.SpellFamilyMask, spell));
}
References SPELLFAMILY_MAGE.
TEST_F() [7/22]
TEST_F (ArcanePotencyProcTest , FamilyMask_Frostbolt_Matches)
{
    auto* spell = CreateSpellInfo(116, SPELLFAMILY_MAGE, FROSTBOLT_FLAG0);
    auto procEntry = BuildArcanePotencyProcEntry();
    EXPECT_TRUE(TestSpellFamilyMatch(procEntry.SpellFamilyName, procEntry.SpellFamilyMask, spell));
}
References SPELLFAMILY_MAGE.
TEST_F() [8/22]
TEST_F (ArcanePotencyProcTest , FamilyMask_FrostfireBolt_Matches)
{
    auto* spell = CreateSpellInfo(44614, SPELLFAMILY_MAGE,
        FROSTFIRE_BOLT_FLAG0, FROSTFIRE_BOLT_FLAG1);
    auto procEntry = BuildArcanePotencyProcEntry();
    EXPECT_TRUE(TestSpellFamilyMatch(procEntry.SpellFamilyName, procEntry.SpellFamilyMask, spell));
}
References SPELLFAMILY_MAGE.
TEST_F() [9/22]
TEST_F (ArcanePotencyProcTest , FamilyMask_IceLance_DoesNotMatch)
{
    auto* spell = CreateSpellInfo(30455, SPELLFAMILY_MAGE, ICE_LANCE_FLAG0);
    auto procEntry = BuildArcanePotencyProcEntry();
    EXPECT_FALSE(TestSpellFamilyMatch(procEntry.SpellFamilyName, procEntry.SpellFamilyMask, spell));
}
References SPELLFAMILY_MAGE.
TEST_F() [10/22]
TEST_F (ArcanePotencyProcTest , FamilyMask_NonMageSpell_DoesNotMatch)
{
    // Warrior spell with matching flags should NOT match due to family check
    auto* spell = CreateSpellInfo(6343, /*SPELLFAMILY_WARRIOR*/4, FIREBALL_FLAG0);
    auto procEntry = BuildArcanePotencyProcEntry();
    EXPECT_FALSE(TestSpellFamilyMatch(procEntry.SpellFamilyName, procEntry.SpellFamilyMask, spell));
}
TEST_F() [11/22]
TEST_F (ArcanePotencyProcTest , FamilyMask_Scorch_Matches)
{
    auto* spell = CreateSpellInfo(2948, SPELLFAMILY_MAGE, SCORCH_FLAG0);
    auto procEntry = BuildArcanePotencyProcEntry();
    EXPECT_TRUE(TestSpellFamilyMatch(procEntry.SpellFamilyName, procEntry.SpellFamilyMask, spell));
}
References SPELLFAMILY_MAGE.
TEST_F() [12/22]
TEST_F (ArcanePotencyProcTest , MaskBits_CorrectBitsNotSet)
{
    // Bit 11: Arcane Missiles - should NOT be set
    EXPECT_FALSE(AP_FAMILY_MASK0 & 0x00000800);
    // Bit 17: Ice Lance - should NOT be set
    EXPECT_FALSE(AP_FAMILY_MASK0 & 0x00020000);
    // Mask1 bit 15: Arcane Barrage - should NOT be set
    EXPECT_FALSE(AP_FAMILY_MASK1 & 0x00008000);
}
TEST_F() [13/22]
TEST_F (ArcanePotencyProcTest , MaskBits_CorrectBitsSet)
{
    // Verify the exact bits in our SpellFamilyMask0
    // Bit 0: Fireball
    EXPECT_TRUE(AP_FAMILY_MASK0 & 0x00000001);
    // Bit 2: Frostfire Bolt
    EXPECT_TRUE(AP_FAMILY_MASK0 & 0x00000004);
    // Bit 4: Fire Blast
    EXPECT_TRUE(AP_FAMILY_MASK0 & 0x00000010);
    // Bit 5: Frostbolt
    EXPECT_TRUE(AP_FAMILY_MASK0 & 0x00000020);
    // Bit 12: Arcane Explosion
    EXPECT_TRUE(AP_FAMILY_MASK0 & 0x00001000);
    // Bit 22: Scorch
    EXPECT_TRUE(AP_FAMILY_MASK0 & 0x00400000);
    // Bit 29: Arcane Blast
    EXPECT_TRUE(AP_FAMILY_MASK0 & 0x20000000);
    // Mask1: Bit 12 (Frostfire Bolt secondary)
    EXPECT_TRUE(AP_FAMILY_MASK1 & 0x00001000);
}
TEST_F() [14/22]
TEST_F (ArcanePotencyProcTest , Phase_DoesNotTriggerOnFinish)
{
    auto procEntry = SpellProcEntryBuilder()
        .WithProcFlags(PROC_FLAG_DONE_SPELL_MAGIC_DMG_CLASS_NEG)
        .WithSpellPhaseMask(PROC_SPELL_PHASE_CAST)
        .WithAttributesMask(PROC_ATTR_REQ_SPELLMOD)
        .Build();
    auto scenario = ProcScenarioBuilder()
        .OnSpellDamage()
        .OnFinish();
    EXPECT_PROC_DOES_NOT_TRIGGER(procEntry, scenario);
}
References SpellProcEntryBuilder::Build(), EXPECT_PROC_DOES_NOT_TRIGGER, ProcScenarioBuilder::OnFinish(), ProcScenarioBuilder::OnSpellDamage(), PROC_ATTR_REQ_SPELLMOD, PROC_FLAG_DONE_SPELL_MAGIC_DMG_CLASS_NEG, PROC_SPELL_PHASE_CAST, SpellProcEntryBuilder::WithAttributesMask(), SpellProcEntryBuilder::WithProcFlags(), and SpellProcEntryBuilder::WithSpellPhaseMask().
TEST_F() [15/22]
TEST_F (ArcanePotencyProcTest , Phase_DoesNotTriggerOnHit)
{
    auto procEntry = SpellProcEntryBuilder()
        .WithProcFlags(PROC_FLAG_DONE_SPELL_MAGIC_DMG_CLASS_NEG)
        .WithSpellPhaseMask(PROC_SPELL_PHASE_CAST)
        .WithAttributesMask(PROC_ATTR_REQ_SPELLMOD)
        .Build();
    auto scenario = ProcScenarioBuilder()
        .OnSpellDamage()
        .OnHit()
        .WithNormalHit();
    EXPECT_PROC_DOES_NOT_TRIGGER(procEntry, scenario);
}
References SpellProcEntryBuilder::Build(), EXPECT_PROC_DOES_NOT_TRIGGER, ProcScenarioBuilder::OnHit(), ProcScenarioBuilder::OnSpellDamage(), PROC_ATTR_REQ_SPELLMOD, PROC_FLAG_DONE_SPELL_MAGIC_DMG_CLASS_NEG, PROC_SPELL_PHASE_CAST, SpellProcEntryBuilder::WithAttributesMask(), ProcScenarioBuilder::WithNormalHit(), SpellProcEntryBuilder::WithProcFlags(), and SpellProcEntryBuilder::WithSpellPhaseMask().
TEST_F() [16/22]
TEST_F (ArcanePotencyProcTest , Phase_TriggersOnCast)
{
    // Test phase filtering in isolation (no family filter)
    auto procEntry = SpellProcEntryBuilder()
        .WithProcFlags(PROC_FLAG_DONE_SPELL_MAGIC_DMG_CLASS_NEG)
        .WithSpellPhaseMask(PROC_SPELL_PHASE_CAST)
        .WithAttributesMask(PROC_ATTR_REQ_SPELLMOD)
        .Build();
    auto scenario = ProcScenarioBuilder()
        .OnSpellDamage()
        .OnCast();
    EXPECT_PROC_TRIGGERS(procEntry, scenario);
}
References SpellProcEntryBuilder::Build(), EXPECT_PROC_TRIGGERS, ProcScenarioBuilder::OnCast(), ProcScenarioBuilder::OnSpellDamage(), PROC_ATTR_REQ_SPELLMOD, PROC_FLAG_DONE_SPELL_MAGIC_DMG_CLASS_NEG, PROC_SPELL_PHASE_CAST, SpellProcEntryBuilder::WithAttributesMask(), SpellProcEntryBuilder::WithProcFlags(), and SpellProcEntryBuilder::WithSpellPhaseMask().
TEST_F() [17/22]
TEST_F (ArcanePotencyProcTest , ProcEntry_BothRanksIdentical)
{
    // Both ranks should use the same proc configuration
    auto r1 = BuildArcanePotencyProcEntry();
    auto r2 = BuildArcanePotencyProcEntry();
    EXPECT_EQ(r1.SpellFamilyName, r2.SpellFamilyName);
    EXPECT_TRUE(r1.SpellFamilyMask == r2.SpellFamilyMask);
    EXPECT_EQ(r1.SpellPhaseMask, r2.SpellPhaseMask);
    EXPECT_EQ(r1.AttributesMask, r2.AttributesMask);
}
TEST_F() [18/22]
TEST_F (ArcanePotencyProcTest , ProcEntry_CastPhaseOnly)
{
    auto procEntry = BuildArcanePotencyProcEntry();
    EXPECT_EQ(procEntry.SpellPhaseMask, PROC_SPELL_PHASE_CAST)
        << "Arcane Potency should only proc on CAST phase";
}
References PROC_SPELL_PHASE_CAST.
TEST_F() [19/22]
TEST_F (ArcanePotencyProcTest , ProcEntry_HasReqSpellmodAttribute)
{
    auto procEntry = BuildArcanePotencyProcEntry();
    EXPECT_TRUE(procEntry.AttributesMask & PROC_ATTR_REQ_SPELLMOD)
        << "Arcane Potency must have PROC_ATTR_REQ_SPELLMOD to prevent "
           "same-cast consumption";
}
References PROC_ATTR_REQ_SPELLMOD.
TEST_F() [20/22]
TEST_F (ArcanePotencyProcTest , ProcEntry_MageFamily)
{
    auto procEntry = BuildArcanePotencyProcEntry();
    EXPECT_EQ(procEntry.SpellFamilyName, SPELLFAMILY_MAGE);
}
References SPELLFAMILY_MAGE.
TEST_F() [21/22]
TEST_F (ArcanePotencyProcTest , ReqSpellmod_AuraWithCharges_BlocksWithoutAppliedMod)
{
    // When PROC_ATTR_REQ_SPELLMOD is set and aura uses charges,
    // GetProcEffectMask should return 0 if aura is not in m_appliedMods.
    // We test the prerequisite: that the proc entry is configured correctly
    // so the charge-gating code path in GetProcEffectMask is reachable.
    auto procEntry = BuildArcanePotencyProcEntry();
    auto aura = AuraStubBuilder()
        .WithId(ARCANE_POTENCY_R1)
        .WithCharges(1)
        .Build();
    // The aura should be using charges (required for REQ_SPELLMOD gating)
    EXPECT_TRUE(aura->IsUsingCharges());
    EXPECT_TRUE(procEntry.AttributesMask & PROC_ATTR_REQ_SPELLMOD);
}
References AuraStubBuilder::Build(), PROC_ATTR_REQ_SPELLMOD, AuraStubBuilder::WithCharges(), and AuraStubBuilder::WithId().
TEST_F() [22/22]
TEST_F (ArcanePotencyProcTest , ReqSpellmod_AuraWithoutCharges_SkipsCheck)
{
    // If aura has no charges, PROC_ATTR_REQ_SPELLMOD check is skipped
    // (no charges to consume = no need for spellmod gating)
    auto procEntry = BuildArcanePotencyProcEntry();
    auto aura = AuraStubBuilder()
        .WithId(ARCANE_POTENCY_R1)
        .WithCharges(0)
        .Build();
    EXPECT_FALSE(aura->IsUsingCharges());
    // Even though PROC_ATTR_REQ_SPELLMOD is set, the condition
    // (IsUsingCharges() || USE_STACKS_FOR_CHARGES) would be false
    // so the spellmod check would be skipped
}
References AuraStubBuilder::Build(), AuraStubBuilder::WithCharges(), and AuraStubBuilder::WithId().