AzerothCore Doxygen
boss_skadi_grauf::boss_skadi_graufAI Struct Reference
Public Member Functions
boss_skadi_graufAI (Creature *creature)
void Reset () override
void DoAction (int32 param) override
void SpellHit (Unit *, SpellInfo const *spellInfo) override
void MovementInform (uint32 type, uint32) override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void JustDied (Unit *) override
Public Member Functions inherited from VehicleAI
VehicleAI (Creature *creature)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void MoveInLineOfSight (Unit *) override
void AttackStart (Unit *) override
void OnCharmed (bool apply) override
Called when unit is charmed.
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0ms)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
bool IsEngaged () const
Check if creature is currently engaged in combat.
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
void JustEnteredCombat (Unit *who) override
Called when the unit enters combat.
virtual void JustStartedThreateningMe (Unit *who)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged - this happens after JustEnteredCombat.
void EngagementStart (Unit *who)
void EngagementOver ()
void JustExitedCombat () override
Called when the unit leaves combat.
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void OnSpellStart (SpellInfo const *)
virtual void OnSpellCast (SpellInfo const *)
virtual void OnSpellFailed (SpellInfo const *)
virtual void OnChannelFinished (SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void PathEndReached (uint32)
virtual void WaypointPathStarted (uint32)
== Waypoints system =============================
virtual void WaypointStarted (uint32, uint32)
virtual void WaypointReached (uint32, uint32)
virtual void WaypointPathEnded (uint32, uint32)
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *attacker)
virtual void OwnerAttacked (Unit *target)
void OnOwnerCombatInteraction (Unit *target)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
int32 VisualizeBoundary (uint32 duration, Unit *owner=nullptr, bool fill=false, bool checkZ=false) const
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
virtual void DistancingStarted ()
virtual void DistancingEnded ()
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid const &, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void EvadeTimerExpired ()
Called when evade timer expires (target unreachable for too long)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Private Attributes
InstanceScript * _instance
EventMap _events
SummonList _summons
uint8 _lastSide = POINT_LEFT
bool _flyingToSide = false
Additional Inherited Members
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from VehicleAI
static int32 Permissible (Creature const *creature)
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
bool _isEngaged
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
boss_skadi_graufAI()
boss_skadi_grauf::boss_skadi_graufAI::boss_skadi_graufAI (Creature * creature) inline
                                               : VehicleAI(creature), _summons(me)
        {
            _instance = creature->GetInstanceScript();
        }
References _instance, and WorldObject::GetInstanceScript().
Member Function Documentation
DoAction()
void boss_skadi_grauf::boss_skadi_graufAI::DoAction (int32 param) inline override virtual
Reimplemented from UnitAI.
        {
            if (param == ACTION_START_ENCOUNTER)
            {
                me->setActive(true);
                me->SetCanFly(true);
                me->SetDisableGravity(true);
                me->GetMotionMaster()->Clear(true);
                me->SetAnimTier(AnimTier::Fly);
                me->GetMotionMaster()->MovePath(PATH_INITIAL, FORCED_MOVEMENT_RUN);
            }
        }
References ACTION_START_ENCOUNTER, MotionMaster::Clear(), Fly, FORCED_MOVEMENT_RUN, Unit::GetMotionMaster(), CreatureAI::me, MotionMaster::MovePath(), PATH_INITIAL, WorldObject::setActive(), Unit::SetAnimTier(), Unit::SetCanFly(), and Unit::SetDisableGravity().
JustDied()
void boss_skadi_grauf::boss_skadi_graufAI::JustDied (Unit *) inline override virtual
Reimplemented from CreatureAI.
        {
            if (Creature* skadi = _instance->GetCreature(DATA_SKADI_THE_RUTHLESS))
            {
                skadi->ExitVehicle();
                skadi->AI()->DoAction(ACTION_PHASE2);
                if (skadi->AI()->GetData(DATA_LOVE_TO_SKADI) == 1)
                    _instance->SetData(DATA_SKADI_ACHIEVEMENT, true);
            }
            me->DespawnOrUnsummon(6s);
        }
References _instance, ACTION_PHASE2, DATA_LOVE_TO_SKADI, DATA_SKADI_ACHIEVEMENT, DATA_SKADI_THE_RUTHLESS, Creature::DespawnOrUnsummon(), InstanceScript::GetCreature(), CreatureAI::me, and ZoneScript::SetData().
MovementInform()
void boss_skadi_grauf::boss_skadi_graufAI::MovementInform (uint32 type, uint32) inline override virtual
Reimplemented from CreatureAI.
        {
            if (type == ESCORT_MOTION_TYPE && me->movespline->Finalized())
            {
                if (_flyingToSide)
                {
                    _flyingToSide = false;
                    me->SetFacingTo(_lastSide == POINT_LEFT ? BreathFacingLeft : BreathFacingRight);
                    Talk(EMOTE_DEEP_BREATH);
                    _events.ScheduleEvent(EVENT_GRAUF_BREATH_START, 2s);
                }
                else
                {
                    me->SetFacingTo(BreachFacing);
                    Talk(EMOTE_ON_RANGE);
                    _events.ScheduleEvent(EVENT_GRAUF_LEAVE_BREACH, 10s);
                }
            }
        }
References _events, _flyingToSide, _lastSide, BreachFacing, BreathFacingLeft, BreathFacingRight, EMOTE_DEEP_BREATH, EMOTE_ON_RANGE, ESCORT_MOTION_TYPE, EVENT_GRAUF_BREATH_START, EVENT_GRAUF_LEAVE_BREACH, Movement::MoveSpline::Finalized(), CreatureAI::me, Unit::movespline, POINT_LEFT, EventMap::ScheduleEvent(), and Unit::SetFacingTo().
Reset()
void boss_skadi_grauf::boss_skadi_graufAI::Reset () inline override virtual
Reimplemented from UnitAI.
        {
            _events.Reset();
            _summons.DespawnAll();
            me->SetReactState(REACT_PASSIVE);
            me->SetSpeedRate(MOVE_RUN, 2.5f);
            _flyingToSide = false;
        }
References _events, _flyingToSide, _summons, SummonList::DespawnAll(), CreatureAI::me, MOVE_RUN, REACT_PASSIVE, EventMap::Reset(), Creature::SetReactState(), and Unit::SetSpeedRate().
SpellHit()
void boss_skadi_grauf::boss_skadi_graufAI::SpellHit (Unit * , SpellInfo const * spellInfo) inline override virtual
Reimplemented from CreatureAI.
        {
            if (spellInfo->Id == SPELL_LAUNCH_HARPOON)
                if (Creature* skadi = _instance->GetCreature(DATA_SKADI_THE_RUTHLESS))
                    skadi->AI()->DoAction(ACTION_HARPOON_HIT);
        }
References _instance, ACTION_HARPOON_HIT, DATA_SKADI_THE_RUTHLESS, InstanceScript::GetCreature(), SpellInfo::Id, and SPELL_LAUNCH_HARPOON.
UpdateAI()
void boss_skadi_grauf::boss_skadi_graufAI::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Implements UnitAI.
        {
            _events.Update(diff);
            switch (_events.ExecuteEvent())
            {
                case EVENT_GRAUF_LEAVE_BREACH:
                    _lastSide = RAND(POINT_LEFT, POINT_RIGHT);
                    _flyingToSide = true;
                    me->GetMotionMaster()->MovePath(
                        _lastSide == POINT_LEFT ? PATH_BREACH_LEFT : PATH_BREACH_RIGHT,
                        FORCED_MOVEMENT_RUN);
                    break;
                case EVENT_GRAUF_BREATH_START:
                    me->GetMotionMaster()->MovePath(
                        _lastSide == POINT_LEFT ? PATH_LEFT : PATH_RIGHT,
                        FORCED_MOVEMENT_RUN);
                    DoCast(me, _lastSide == POINT_LEFT
                        ? SPELL_FREEZING_CLOUD_LEFT_PERIODIC
                        : SPELL_FREEZING_CLOUD_RIGHT_PERIODIC);
                    if (Creature* skadi = _instance->GetCreature(DATA_SKADI_THE_RUTHLESS))
                        skadi->AI()->DoAction(ACTION_DRAKE_BREATH);
                    _events.ScheduleEvent(EVENT_GRAUF_REMOVE_AURA, 10s);
                    break;
                case EVENT_GRAUF_REMOVE_AURA:
                    me->RemoveAurasDueToSpell(SPELL_FREEZING_CLOUD_LEFT_PERIODIC);
                    me->RemoveAurasDueToSpell(SPELL_FREEZING_CLOUD_RIGHT_PERIODIC);
                    break;
            }
        }
References _events, _flyingToSide, _instance, _lastSide, ACTION_DRAKE_BREATH, DATA_SKADI_THE_RUTHLESS, UnitAI::DoCast(), EVENT_GRAUF_BREATH_START, EVENT_GRAUF_LEAVE_BREACH, EVENT_GRAUF_REMOVE_AURA, EventMap::ExecuteEvent(), FORCED_MOVEMENT_RUN, InstanceScript::GetCreature(), Unit::GetMotionMaster(), CreatureAI::me, MotionMaster::MovePath(), PATH_BREACH_LEFT, PATH_BREACH_RIGHT, PATH_LEFT, PATH_RIGHT, POINT_LEFT, POINT_RIGHT, RAND(), Unit::RemoveAurasDueToSpell(), EventMap::ScheduleEvent(), SPELL_FREEZING_CLOUD_LEFT_PERIODIC, SPELL_FREEZING_CLOUD_RIGHT_PERIODIC, and EventMap::Update().
Member Data Documentation
_events
EventMap boss_skadi_grauf::boss_skadi_graufAI::_events private
Referenced by MovementInform(), Reset(), and UpdateAI().
_flyingToSide
bool boss_skadi_grauf::boss_skadi_graufAI::_flyingToSide = false private
Referenced by MovementInform(), Reset(), and UpdateAI().
_instance
InstanceScript* boss_skadi_grauf::boss_skadi_graufAI::_instance private
Referenced by boss_skadi_graufAI(), JustDied(), SpellHit(), and UpdateAI().
_lastSide
uint8 boss_skadi_grauf::boss_skadi_graufAI::_lastSide = POINT_LEFT private
Referenced by MovementInform(), and UpdateAI().
_summons
SummonList boss_skadi_grauf::boss_skadi_graufAI::_summons private
Referenced by Reset().
The documentation for this struct was generated from the following file:
azerothcore-wotlk/src/server/scripts/Northrend/UtgardeKeep/UtgardePinnacle/boss_skadi.cpp