AzerothCore Doxygen
Field Class Reference
Class used to access individual fields of database query result.
#include "Field.h"
Public Member Functions
Field ()
~Field ()=default
bool IsNull () const
template<typename T >
std::enable_if_t< std::is_arithmetic_v< T >, T > Get () const
template<typename T >
std::enable_if_t< std::is_same_v< std::string, T >, T > Get () const
template<typename T >
std::enable_if_t< std::is_same_v< std::string_view, T >, T > Get () const
template<typename T >
std::enable_if_t< std::is_same_v< Binary, T >, T > Get () const
template<typename T , std::size_t S>
std::enable_if_t< std::is_same_v< Binary, T >, std::array< uint8, S > > Get () const
template<typename T >
Acore::Types::is_chrono_v< T > Get (bool convertToUin32=true) const
DatabaseFieldTypes GetType ()
Protected Member Functions
void SetByteValue (char const *newValue, uint32 length)
void SetStructuredValue (char const *newValue, uint32 length)
bool IsType (DatabaseFieldTypes type) const
bool IsNumeric () const
Protected Attributes
struct {
char const * value
uint32 length
bool raw
} data
Private Member Functions
template<typename T >
T GetData () const
std::string GetDataString () const
std::string_view GetDataStringView () const
Binary GetDataBinary () const
void LogWrongType (std::string_view getter, std::string_view typeName) const
void SetMetadata (QueryResultFieldMetadata const *fieldMeta)
void GetBinarySizeChecked (uint8 *buf, std::size_t size) const
Private Attributes
QueryResultFieldMetadata const * meta
Friends
class ResultSet
class PreparedResultSet
Detailed Description
Class used to access individual fields of database query result.
Guideline on field type matching:
MySQL type method to use
TINYINT Get<bool>, Get<int8>, Get<uint8>
SMALLINT Get<int16>, Get<uint16>
MEDIUMINT, INT Get<int32>, Get<uint32>
BIGINT Get<int64>, Get<uint64>
FLOAT Get<float>
DOUBLE, DECIMAL Get<double>
CHAR, VARCHAR, Get<std::string>, Get<std::string_view>
TINYTEXT, MEDIUMTEXT, Get<std::string>, Get<std::string_view>
TEXT, LONGTEXT Get<std::string>, Get<std::string_view>
TINYBLOB, MEDIUMBLOB, Get<Binary>, Get<std::string>
BLOB, LONGBLOB Get<Binary>, Get<std::string>
BINARY, VARBINARY Get<Binary>
Return types of aggregate functions:
Function Type
MIN, MAX Same as the field
SUM, AVG DECIMAL
COUNT BIGINT
Constructor & Destructor Documentation
Field()
Field::Field ()
{
    data.value = nullptr;
    data.length = 0;
    data.raw = false;
    meta = nullptr;
}
References data, and meta.
~Field()
Field::~Field () default
Member Function Documentation
Get() [1/6]
template<typename T > std::enable_if_t< std::is_arithmetic_v< T >, T > Field::Get () const inline
    {
        return GetData<T>();
    }
Referenced by Player::_LoadActions(), Pet::_LoadAuras(), Player::_LoadAuras(), Player::_LoadBrewOfTheMonth(), Player::_LoadCharacterSettings(), Player::_LoadDailyQuestStatus(), Player::_LoadEntryPointData(), Player::_LoadEquipmentSets(), lfg::LFGMgr::_LoadFromDB(), Player::_LoadGlyphs(), Player::_LoadHomeBind(), Player::_LoadInventory(), Player::_LoadItem(), Player::_LoadMail(), Player::_LoadMailedItem(), Player::_LoadMonthlyQuestStatus(), Player::_LoadPetStable(), Player::_LoadQuestStatus(), Player::_LoadQuestStatusRewarded(), Player::_LoadSeasonalQuestStatus(), Player::_LoadSkills(), Pet::_LoadSpellCooldowns(), Player::_LoadSpellCooldowns(), Player::_LoadSpells(), Player::_LoadWeeklyQuestStatus(), AccountInfo::AccountInfo(), Guild::AddMember(), AppendTableDump(), SecretMgr::AttemptTransition(), BanMgr::BanIP(), Player::BuildEnumData(), CharacterDatabaseCleaner::CheckUnique(), Player::DeleteFromDB(), Player::DeleteOldRecoveryItems(), npc_shattrath_daily_quest::DoAction(), Battleground::EndBattleground(), ArenaSeasonMgr::GameEventForArenaSeason(), character_commandscript::GetDeletedCharacterInfoList(), Player::GetZoneIdFromDB(), account_commandscript::HandleAccount2FARemoveCommand(), account_commandscript::HandleAccountOnlineListCommand(), ban_commandscript::HandleBanInfoCharacterCommand(), ban_commandscript::HandleBanInfoHelper(), ban_commandscript::HandleBanInfoIPCommand(), ban_commandscript::HandleBanListCharacterCommand(), ban_commandscript::HandleBanListHelper(), ban_commandscript::HandleBanListIPCommand(), WorldSession::HandleCharacterAuraFrozen(), WorldSession::HandleCharCustomizeCallback(), WorldSession::HandleCharFactionOrRaceChangeCallback(), WorldSession::HandleCharRenameCallBack(), deserter_commandscript::HandleDeserterAdd(), deserter_commandscript::HandleDeserterRemove(), gobject_commandscript::HandleGameObjectNearCommand(), gobject_commandscript::HandleGameObjectTargetCommand(), gear_commandscript::HandleGearStatsCommand(), gm_commandscript::HandleGMListFullCommand(), guild_commandscript::HandleGuildInfoCommand(), item_commandscript::HandleItemRefundCommand(), item_commandscript::HandleItemRestoreListCommand(), list_commandscript::HandleListCreatureCommand(), list_commandscript::HandleListItemCommand(), list_commandscript::HandleListObjectCommand(), npc_commandscript::HandleNpcNearCommand(), WorldSession::HandleOpenWrappedItemCallback(), misc_commandscript::HandlePInfoCommand(), quest_commandscript::HandleQuestComplete(), server_commandscript::HandleServerDebugCommand(), tele_commandscript::HandleTeleNameCommand(), tele_commandscript::HandleTeleNameNpcNameCommand(), misc_commandscript::HandleUnstuckCommand(), WorldSession::HandleWhoisOpcode(), wp_commandscript::HandleWpEventCommand(), wp_commandscript::HandleWpModifyCommand(), wp_commandscript::HandleWpShowCommand(), GameEventMgr::Initialize(), Player::LeaveAllArenaTeams(), WaypointMgr::Load(), WorldState::Load(), DBCDatabaseLoader::Load(), ObjectMgr::LoadAccessRequirements(), WorldSession::LoadAccountData(), AchievementGlobalMgr::LoadAchievementCriteriaData(), ObjectMgr::LoadAcoreStrings(), ArenaSeasonMgr::LoadActiveSeason(), WorldGlobals::LoadAntiDosOpcodePolicies(), ObjectMgr::LoadAreaTriggers(), ObjectMgr::LoadAreaTriggerScripts(), ObjectMgr::LoadAreaTriggerTeleports(), ArenaTeam::LoadArenaTeamFromDB(), AuctionHouseMgr::LoadAuctionItems(), AutobroadcastMgr::LoadAutobroadcasts(), AutobroadcastMgr::LoadAutobroadcastsLocalized(), Guild::LoadBankEventLogFromDB(), Guild::LoadBankItemFromDB(), Guild::LoadBankTabFromDB(), BattlegroundMgr::LoadBattlegroundTemplates(), BattlegroundMgr::LoadBattleMastersEntry(), ObjectMgr::LoadBroadcastTextLocales(), ObjectMgr::LoadBroadcastTexts(), ChannelMgr::LoadChannelRights(), ChannelMgr::LoadChannels(), InstanceSaveMgr::LoadCharacterBinds(), Acore::Impl::ChatCommands::ChatCommandNode::LoadCommandMap(), AchievementGlobalMgr::LoadCompletedAchievements(), ConditionMgr::LoadConditions(), Map::LoadCorpseData(), Corpse::LoadCorpseFromDB(), ObjectMgr::LoadCreatureAddons(), ObjectMgr::LoadCreatureClassLevelStats(), ObjectMgr::LoadCreatureDataFromDB(), ObjectMgr::LoadCreatureDefaultTrainers(), FormationMgr::LoadCreatureFormations(), ObjectMgr::LoadCreatureLocales(), ObjectMgr::LoadCreatureModelInfo(), ObjectMgr::LoadCreatureMovementOverrides(), ObjectMgr::LoadCreatureQuestItems(), ObjectMgr::LoadCreatures(), ObjectMgr::LoadCreatureSparring(), ObjectMgr::LoadCreatureTemplate(), ObjectMgr::LoadCreatureTemplateAddons(), ObjectMgr::LoadCreatureTemplateModels(), ObjectMgr::LoadCreatureTemplateResistances(), ObjectMgr::LoadCreatureTemplateSpells(), CreatureTextMgr::LoadCreatureTextLocales(), CreatureTextMgr::LoadCreatureTexts(), World::LoadDBVersion(), DisableMgr::LoadDisables(), ObjectMgr::LoadEquipmentTemplates(), GameEventMgr::LoadEventBattlegroundData(), GameEventMgr::LoadEventConditionData(), GameEventMgr::LoadEventConditionSaveData(), GameEventMgr::LoadEventCreatureData(), GameEventMgr::LoadEventGameObjectData(), GameEventMgr::LoadEventGameObjectQuestData(), GameEventMgr::LoadEventModelEquipmentChangeData(), GameEventMgr::LoadEventNPCFlags(), GameEventMgr::LoadEventPoolData(), GameEventMgr::LoadEventPrerequisiteData(), GameEventMgr::LoadEventQuestConditionData(), GameEventMgr::LoadEventQuestData(), GameEventMgr::LoadEvents(), GameEventMgr::LoadEventSaveData(), GameEventMgr::LoadEventSeasonalQuestRelations(), GameEventMgr::LoadEventVendors(), ObjectMgr::LoadExplorationBaseXP(), ObjectMgr::LoadFactionChangeAchievements(), ObjectMgr::LoadFactionChangeItems(), ObjectMgr::LoadFactionChangeQuests(), ObjectMgr::LoadFactionChangeReputations(), ObjectMgr::LoadFactionChangeSpells(), ObjectMgr::LoadFactionChangeTitles(), ObjectMgr::LoadFishingBaseSkillLevel(), AddonMgr::LoadFromDB(), SmartWaypointMgr::LoadFromDB(), CalendarMgr::LoadFromDB(), PoolMgr::LoadFromDB(), AuctionEntry::LoadFromDB(), EmblemInfo::LoadFromDB(), Guild::Member::LoadFromDB(), Guild::RankInfo::LoadFromDB(), Guild::BankTab::LoadFromDB(), Guild::LoadFromDB(), GmTicket::LoadFromDB(), Player::LoadFromDB(), Item::LoadFromDB(), AchievementMgr::LoadFromDB(), ReputationMgr::LoadFromDB(), SocialMgr::LoadFromDB(), ObjectMgr::LoadGameObjectAddons(), ObjectMgr::LoadGameObjectDataFromDB(), ObjectMgr::LoadGameObjectLocales(), ObjectMgr::LoadGameObjectQuestItems(), ObjectMgr::LoadGameobjects(), ObjectMgr::LoadGameObjectTemplate(), ObjectMgr::LoadGameObjectTemplateAddons(), ObjectMgr::LoadGameTele(), ObjectMgr::LoadGossipMenu(), ObjectMgr::LoadGossipMenuItems(), ObjectMgr::LoadGossipMenuItemsLocales(), ObjectMgr::LoadGossipText(), Graveyard::LoadGraveyardFromDB(), Graveyard::LoadGraveyardZones(), Group::LoadGroupFromDB(), GuildMgr::LoadGuilds(), GameEventMgr::LoadHolidayDates(), ObjectMgr::LoadInstanceEncounters(), InstanceSaveMgr::LoadInstanceSaves(), ObjectMgr::LoadInstanceTemplate(), Guild::BankTab::LoadItemFromDB(), ObjectMgr::LoadItemLocales(), ObjectMgr::LoadItemSetNameLocales(), ObjectMgr::LoadItemSetNames(), ObjectMgr::LoadItemTemplates(), lfg::LFGMgr::LoadLFGDungeons(), ObjectMgr::LoadLinkedRespawn(), LootStore::LoadLootTable(), ObjectMgr::LoadMailLevelRewards(), ServerMailMgr::LoadMailServerTemplates(), ServerMailMgr::LoadMailServerTemplatesConditions(), ServerMailMgr::LoadMailServerTemplatesItems(), Guild::LoadMemberFromDB(), ArenaTeam::LoadMembersFromDB(), ObjectMgr::LoadModuleStrings(), ObjectMgr::LoadModuleStringsLocale(), MotdMgr::LoadMotd(), MotdMgr::LoadMotdLocale(), ObjectMgr::LoadNPCSpellClickSpells(), ObjectMgr::LoadNpcTextLocales(), ObjectMgr::LoadPageTextLocales(), ObjectMgr::LoadPageTexts(), Pet::LoadPetFromDB(), PetitionMgr::LoadPetitions(), ObjectMgr::LoadPetLevelInfo(), ObjectMgr::LoadPetNames(), ObjectMgr::LoadPetNamesLocales(), ObjectMgr::LoadPetNumber(), ObjectMgr::LoadPlayerInfo(), PlayerSettingsStore::LoadPlayerSettings(), ObjectMgr::LoadPlayerShapeshiftModels(), ObjectMgr::LoadPlayerTotemModels(), ObjectMgr::LoadPointOfInterestLocales(), ObjectMgr::LoadPointsOfInterest(), Player::LoadPositionFromDB(), ObjectMgr::LoadProfanityNamesFromDB(), ObjectMgr::LoadQuestAreaTriggers(), ObjectMgr::LoadQuestGreetings(), ObjectMgr::LoadQuestGreetingsLocales(), ObjectMgr::LoadQuestLocales(), ObjectMgr::LoadQuestMoneyRewards(), Quest::LoadQuestOfferReward(), ObjectMgr::LoadQuestOfferRewardLocale(), ObjectMgr::LoadQuestPOI(), Quest::LoadQuestRequestItems(), ObjectMgr::LoadQuestRequestItemsLocale(), ObjectMgr::LoadQuests(), Quest::LoadQuestTemplateAddon(), LoadRandomEnchantmentsTable(), LoadRealmInfo(), ObjectMgr::LoadReferenceVendor(), ObjectMgr::LoadReputationOnKill(), ObjectMgr::LoadReputationRewardRate(), ObjectMgr::LoadReputationSpilloverTemplate(), ObjectMgr::LoadReservedPlayerNamesDB(), InstanceSaveMgr::LoadResetTimes(), Map::LoadRespawnTimes(), AccountInfo::LoadResult(), AchievementGlobalMgr::LoadRewardLocales(), AchievementGlobalMgr::LoadRewards(), ArenaSeasonMgr::LoadRewards(), lfg::LFGMgr::LoadRewards(), ObjectMgr::LoadScripts(), SystemMgr::LoadScriptWaypoints(), PetitionMgr::LoadSignatures(), LoadSkillDiscoveryTable(), LoadSkillExtraItemTable(), LoadSkillPerfectItemTable(), SmartAIMgr::LoadSmartAIFromDB(), SpellMgr::LoadSpellAreas(), SpellMgr::LoadSpellBonuses(), SpellMgr::LoadSpellCooldownOverrides(), SpellMgr::LoadSpellEnchantProcData(), SpellMgr::LoadSpellGroups(), SpellMgr::LoadSpellGroupStackRules(), SpellMgr::LoadSpellInfoCustomAttributes(), SpellMgr::LoadSpellLinked(), SpellMgr::LoadSpellMixology(), SpellMgr::LoadSpellPetAuras(), SpellMgr::LoadSpellProcEvents(), SpellMgr::LoadSpellProcs(), SpellMgr::LoadSpellRanks(), SpellMgr::LoadSpellRequired(), ObjectMgr::LoadSpellScriptNames(), SpellMgr::LoadSpellTargetPositions(), SpellMgr::LoadSpellThreats(), ObjectMgr::LoadTavernAreaTriggers(), ObjectMgr::LoadTempSummons(), ObjectMgr::LoadTrainers(), TransportMgr::LoadTransportTemplates(), ObjectMgr::LoadVehicleAccessories(), ObjectMgr::LoadVehicleSeatAddon(), ObjectMgr::LoadVehicleTemplateAccessories(), ObjectMgr::LoadVendors(), WardenCheckMgr::LoadWardenChecks(), WardenCheckMgr::LoadWardenOverrides(), ObjectMgr::LoadWaypointScripts(), WeatherMgr::LoadWeatherData(), WorldState::LoadWorldStates(), AuthSession::LogonChallengeCallback(), lookup_commandscript::LookupPlayerSearchCommand(), TransportMgr::PreloadGridsFromQuery(), Quest::Quest(), AuthSession::RealmListCallback(), UpdateFetcher::ReceiveAppliedFiles(), UpdateFetcher::ReceiveIncludedDirectories(), AuthSession::ReconnectChallengeCallback(), WaypointMgr::ReloadPath(), ObjectMgr::ReturnOrDeleteOldMails(), and TransportMgr::SpawnContinentTransports().
Get() [2/6]
template<typename T > std::enable_if_t< std::is_same_v< std::string, T >, T > Field::Get () const inline
    {
        return GetDataString();
    }
Get() [3/6]
template<typename T > std::enable_if_t< std::is_same_v< std::string_view, T >, T > Field::Get () const inline
    {
        return GetDataStringView();
    }
Get() [4/6]
template<typename T > std::enable_if_t< std::is_same_v< Binary, T >, T > Field::Get () const inline
    {
        return GetDataBinary();
    }
Get() [5/6]
template<typename T , std::size_t S> std::enable_if_t< std::is_same_v< Binary, T >, std::array< uint8, S > > Field::Get () const inline
    {
        std::array<uint8, S> buf = {};
        GetBinarySizeChecked(buf.data(), S);
        return buf;
    }
Get() [6/6]
template<typename T > Acore::Types::is_chrono_v< T > Field::Get (bool convertToUin32 = true) const inline
    {
        return convertToUin32 ? T(GetData<uint32>()) : T(GetData<uint64>());
    }
GetBinarySizeChecked()
void Field::GetBinarySizeChecked (uint8 * buf, std::size_t size) const private
{
    ASSERT(data.value && (data.length == length), "Expected {}-byte binary blob, got {}data ({} bytes) instead", length, data.value ? "" : "no ", data.length);
    memcpy(buf, data.value, length);
}
References ASSERT, data, and length.
GetData()
template<typename T > template double Field::GetData () const private
{
    static_assert(std::is_arithmetic_v<T>, "Unsurropt type for Field::GetData()");
    if (!data.value)
        return GetDefaultValue<T>();
#ifdef ACORE_STRICT_DATABASE_TYPE_CHECKS
    if (!IsCorrectFieldType<T>(meta->Type))
    {
        LogWrongType(__FUNCTION__, typeid(T).name());
        //return GetDefaultValue<T>();
    }
#endif
    Optional<T> result = {};
    if (data.raw)
        result = *reinterpret_cast<T const*>(data.value);
    else
        result = Acore::StringTo<T>(std::string_view(data.value, data.length));
    // Correct double fields... this undefined behavior :/
    if constexpr (std::is_same_v<T, double>)
    {
        if (data.raw && !IsType(DatabaseFieldTypes::Decimal))
            result = *reinterpret_cast<double const*>(data.value);
        else
            result = Acore::StringTo<float>(std::string_view(data.value, data.length));
    }
    // Check -1 for *_dbc db tables
    if constexpr (std::is_same_v<T, uint32>)
    {
        std::string_view tableName{ meta->TableName };
        if (!tableName.empty() && tableName.size() > 4)
        {
            auto signedResult = Acore::StringTo<int32>(std::string_view(data.value, data.length));
            if (signedResult && !result && tableName.substr(tableName.length() - 4) == "_dbc")
            {
                LOG_DEBUG("sql.sql", "> Found incorrect value '{}' for type '{}' in _dbc table.", data.value, typeid(T).name());
                LOG_DEBUG("sql.sql", "> Table name '{}'. Field name '{}'. Try return int32 value", meta->TableName, meta->Name);
                return GetData<int32>();
            }
        }
    }
    if (auto alias = GetCleanAliasName(meta->Alias))
    {
        if ((StringEqualI(*alias, "min") || StringEqualI(*alias, "max")) && !IsCorrectAlias<T>(meta->Type, *alias))
        {
            LogWrongType(__FUNCTION__, typeid(T).name());
        }
        if ((StringEqualI(*alias, "sum") || StringEqualI(*alias, "avg")) && !IsCorrectAlias<T>(meta->Type, *alias))
        {
            LogWrongType(__FUNCTION__, typeid(T).name());
            LOG_WARN("sql.sql", "> Please use GetData<double>()");
            return GetData<double>();
        }
        if (StringEqualI(*alias, "count") && !IsCorrectAlias<T>(meta->Type, *alias))
        {
            LogWrongType(__FUNCTION__, typeid(T).name());
            LOG_WARN("sql.sql", "> Please use GetData<uint64>()");
            return GetData<uint64>();
        }
    }
    if (!result)
    {
        LOG_FATAL("sql.sql", "> Incorrect value '{}' for type '{}'. Value is raw ? '{}'", data.value, typeid(T).name(), data.raw);
        LOG_FATAL("sql.sql", "> Table name '{}'. Field name '{}'", meta->TableName, meta->Name);
        //ABORT();
        return GetDefaultValue<T>();
    }
    return *result;
}
References QueryResultFieldMetadata::Alias, data, Decimal, IsType(), LOG_DEBUG, LOG_FATAL, LOG_WARN, LogWrongType(), meta, QueryResultFieldMetadata::Name, StringEqualI(), QueryResultFieldMetadata::TableName, and QueryResultFieldMetadata::Type.
GetDataBinary()
Binary Field::GetDataBinary () const private
{
    Binary result = {};
    if (!data.value || !data.length)
        return result;
#ifdef ACORE_STRICT_DATABASE_TYPE_CHECKS
    if (!IsCorrectFieldType<Binary>(meta->Type))
    {
        LogWrongType(__FUNCTION__, "Binary");
        return {};
    }
#endif
    result.resize(data.length);
    memcpy(result.data(), data.value, data.length);
    return result;
}
References data, LogWrongType(), meta, and QueryResultFieldMetadata::Type.
GetDataString()
std::string Field::GetDataString () const private
{
    if (!data.value)
        return "";
#ifdef ACORE_STRICT_DATABASE_TYPE_CHECKS
    if (IsNumeric() && data.raw)
    {
        LogWrongType(__FUNCTION__, "std::string");
        return "";
    }
#endif
    return { data.value, data.length };
}
References data, IsNumeric(), and LogWrongType().
GetDataStringView()
std::string_view Field::GetDataStringView () const private
{
    if (!data.value)
        return {};
#ifdef ACORE_STRICT_DATABASE_TYPE_CHECKS
    if (IsNumeric() && data.raw)
    {
        LogWrongType(__FUNCTION__, "std::string_view");
        return {};
    }
#endif
    return { data.value, data.length };
}
References data, IsNumeric(), and LogWrongType().
GetType()
DatabaseFieldTypes Field::GetType () inline
{ return meta->Type; }
IsNull()
bool Field::IsNull () const inline
    {
        return data.value == nullptr;
    }
Referenced by account_commandscript::HandleAccount2FARemoveCommand(), and ObjectMgr::LoadAccessRequirements().
IsNumeric()
bool Field::IsNumeric () const protected
{
    return (meta->Type == DatabaseFieldTypes::Int8 ||
        meta->Type == DatabaseFieldTypes::Int16 ||
        meta->Type == DatabaseFieldTypes::Int32 ||
        meta->Type == DatabaseFieldTypes::Int64 ||
        meta->Type == DatabaseFieldTypes::Float ||
        meta->Type == DatabaseFieldTypes::Double);
}
References Double, Float, Int16, Int32, Int64, Int8, meta, and QueryResultFieldMetadata::Type.
Referenced by GetDataString(), and GetDataStringView().
IsType()
bool Field::IsType (DatabaseFieldTypes type) const protected
{
    return meta->Type == type;
}
References meta, and QueryResultFieldMetadata::Type.
Referenced by GetData().
LogWrongType()
void Field::LogWrongType (std::string_view getter, std::string_view typeName) const private
{
    LOG_WARN("sql.sql", "Warning: {}<{}> on {} field {}.{} ({}.{}) at index {}.",
        getter, typeName, meta->TypeName, meta->TableAlias, meta->Alias, meta->TableName, meta->Name, meta->Index);
}
References QueryResultFieldMetadata::Alias, QueryResultFieldMetadata::Index, LOG_WARN, meta, QueryResultFieldMetadata::Name, QueryResultFieldMetadata::TableAlias, QueryResultFieldMetadata::TableName, and QueryResultFieldMetadata::TypeName.
Referenced by GetData(), GetDataBinary(), GetDataString(), and GetDataStringView().
SetByteValue()
void Field::SetByteValue (char const * newValue, uint32 length) protected
{
    // This value stores raw bytes that have to be explicitly cast later
    data.value = newValue;
    data.length = length;
    data.raw = true;
}
References data, and length.
SetMetadata()
void Field::SetMetadata (QueryResultFieldMetadata const * fieldMeta) private
{
    meta = fieldMeta;
}
References meta.
Referenced by ResultSet::ResultSet().
SetStructuredValue()
void Field::SetStructuredValue (char const * newValue, uint32 length) protected
{
    // This value stores somewhat structured data that needs function style casting
    data.value = newValue;
    data.length = length;
    data.raw = false;
}
References data, and length.
Friends And Related Symbol Documentation
PreparedResultSet
friend class PreparedResultSet friend
ResultSet
friend class ResultSet friend
Member Data Documentation
[struct]
struct { ... } Field::data
Referenced by Field(), GetBinarySizeChecked(), GetData(), GetDataBinary(), GetDataString(), GetDataStringView(), SetByteValue(), and SetStructuredValue().
length
uint32 Field::length
Referenced by GetBinarySizeChecked(), SetByteValue(), and SetStructuredValue().
meta
QueryResultFieldMetadata const* Field::meta private
Referenced by Field(), GetData(), GetDataBinary(), IsNumeric(), IsType(), LogWrongType(), and SetMetadata().
raw
bool Field::raw
value
char const* Field::value
The documentation for this class was generated from the following files:
azerothcore-wotlk/src/server/database/Database/Field.h
azerothcore-wotlk/src/server/database/Database/Field.cpp