AzerothCore Doxygen
Acore::PlayerRelocationNotifier Struct Reference
#include "GridNotifiers.h"
Public Member Functions
PlayerRelocationNotifier (Player &player)
template<class T >
void Visit (std::vector< T > &m)
template<class T >
void Visit (GridRefMgr< T > &m)
void Visit (PlayerMapType &)
Public Member Functions inherited from Acore::VisibleNotifier
VisibleNotifier (Player &player, bool gobjOnly)
void Visit (GameObjectMapType &)
template<class T >
void Visit (std::vector< T > &m)
template<class T >
void Visit (GridRefMgr< T > &m)
void SendToSelf (void)
Additional Inherited Members
Public Attributes inherited from Acore::VisibleNotifier
Player & i_player
std::vector< Unit * > & i_visibleNow
bool i_gobjOnly
UpdateData i_data
Detailed Description
Constructor & Destructor Documentation
PlayerRelocationNotifier()
Acore::PlayerRelocationNotifier::PlayerRelocationNotifier (Player & player) inline
: VisibleNotifier(player, false) { }
Member Function Documentation
Visit() [1/3]
template<class T > void Acore::PlayerRelocationNotifier::Visit (GridRefMgr< T > & m) inline
{ VisibleNotifier::Visit(m); }
References Acore::VisibleNotifier::Visit().
Visit() [2/3]
void PlayerRelocationNotifier::Visit (PlayerMapType & m)
{
    for (PlayerMapType::iterator iter = m.begin(); iter != m.end(); ++iter)
    {
        Player* player = iter->GetSource();
        i_player.UpdateVisibilityOf(player, i_data, i_visibleNow);
        player->UpdateVisibilityOf(&i_player); // this notifier with different Visit(PlayerMapType&) than VisibleNotifier is needed to update visibility of self for other players when we move (eg. stealth detection changes)
    }
}
References GridRefMgr< OBJECT >::begin(), GridRefMgr< OBJECT >::end(), Acore::VisibleNotifier::i_data, Acore::VisibleNotifier::i_player, Acore::VisibleNotifier::i_visibleNow, and Player::UpdateVisibilityOf().
Visit() [3/3]
template<class T > void Acore::PlayerRelocationNotifier::Visit (std::vector< T > & m) inline
{ VisibleNotifier::Visit(m); }
References Acore::VisibleNotifier::Visit().
The documentation for this struct was generated from the following files:
azerothcore-wotlk/src/server/game/Grids/Notifiers/GridNotifiers.h
azerothcore-wotlk/src/server/game/Grids/Notifiers/GridNotifiers.cpp