AzerothCore Doxygen
npc_gunship::npc_gunshipAI Struct Reference
Public Member Functions
npc_gunshipAI (Creature *creature)
void DamageTaken (Unit *, uint32 &damage, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void JustDied (Unit *) override
void UpdateAI (uint32) override
Use to start attacking a target. Called just before JustEngagedWith()
void SetGUID (ObjectGuid guid, int32 id) override
uint32 GetData (uint32 id) const override
Public Member Functions inherited from NullCreatureAI
NullCreatureAI (Creature *c)
void MoveInLineOfSight (Unit *) override
void AttackStart (Unit *) override
void UpdateAI (uint32) override
Use to start attacking a target. Called just before JustEngagedWith()
void EnterEvadeMode (EvadeReason) override
void OnCharmed (bool) override
Called when unit is charmed.
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
int32 VisualizeBoundary (uint32 duration, Unit *owner=nullptr, bool fill=false, bool checkZ=false) const
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void Reset ()
virtual void DoAction (int32)
virtual void SetData (uint32, uint32)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage to any victim (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Private Attributes
InstanceScript * _instance
TeamId _teamIdInInstance
std::map< ObjectGuid, uint32 > _shipVisits
bool _died
bool _summonedFirstMage
Additional Inherited Members
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from NullCreatureAI
static int32 Permissible (Creature const *creature)
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
npc_gunshipAI()
npc_gunship::npc_gunshipAI::npc_gunshipAI (Creature * creature) inline
                                          : NullCreatureAI(creature), _instance(creature->GetInstanceScript()), _teamIdInInstance(TeamId(creature->GetInstanceScript()->GetData(DATA_TEAMID_IN_INSTANCE))), _died(false), _summonedFirstMage(false)
        {
            me->SetRegeneratingHealth(false);
        }
References CreatureAI::me, and Creature::SetRegeneratingHealth().
Member Function Documentation
DamageTaken()
void npc_gunship::npc_gunshipAI::DamageTaken (Unit * , uint32 & , DamageEffectType , SpellSchoolMask) inline override virtual
Called at any Damage from any attacker (before damage apply)
Note
It use for recalculation damage or special reaction at damage for attack reaction use AttackedBy called for non DOT damage in Unit::DealDamage also
Reimplemented from UnitAI.
        {
            if (_instance->GetBossState(DATA_ICECROWN_GUNSHIP_BATTLE) != IN_PROGRESS)
            {
                damage = 0;
                return;
            }
            if (damage >= me->GetHealth())
            {
                JustDied(nullptr);
                damage = me->GetHealth() - 1;
                return;
            }
            if (_summonedFirstMage)
                return;
            if (me->GetTransport()->GetEntry() != uint32(_teamIdInInstance == TEAM_HORDE ? GO_THE_SKYBREAKER_H : GO_ORGRIMS_HAMMER_A))
                return;
            if (!me->HealthBelowPctDamaged(90, damage))
                return;
            _summonedFirstMage = true;
            if (Creature* captain = me->FindNearestCreature(_teamIdInInstance == TEAM_HORDE ? NPC_IGB_MURADIN_BRONZEBEARD : NPC_IGB_HIGH_OVERLORD_SAURFANG, 200.0f))
                captain->AI()->DoAction(ACTION_SPAWN_MAGE);
        }
References _instance, _summonedFirstMage, _teamIdInInstance, ACTION_SPAWN_MAGE, DATA_ICECROWN_GUNSHIP_BATTLE, WorldObject::FindNearestCreature(), InstanceScript::GetBossState(), Object::GetEntry(), Unit::GetHealth(), WorldObject::GetTransport(), GO_ORGRIMS_HAMMER_A, GO_THE_SKYBREAKER_H, Unit::HealthBelowPctDamaged(), IN_PROGRESS, JustDied, CreatureAI::me, NPC_IGB_HIGH_OVERLORD_SAURFANG, NPC_IGB_MURADIN_BRONZEBEARD, and TEAM_HORDE.
GetData()
uint32 npc_gunship::npc_gunshipAI::GetData (uint32 id) const inline override virtual
Reimplemented from UnitAI.
        {
            if (id != ACTION_SHIP_VISITS_ENEMY)
                return 0;
            for (std::map<ObjectGuid, uint32>::const_iterator itr = _shipVisits.begin(); itr != _shipVisits.end(); ++itr)
                if (itr->second == 0)
                    return 0;
            return 1;
        }
References _shipVisits, and ACTION_SHIP_VISITS_ENEMY.
JustDied()
void npc_gunship::npc_gunshipAI::JustDied (Unit *) inline override virtual
Reimplemented from CreatureAI.
        {
            if (_died || _instance->GetBossState(DATA_ICECROWN_GUNSHIP_BATTLE) != IN_PROGRESS)
                return;
            _died = true;
            bool isVictory = me->GetTransport()->GetEntry() == GO_THE_SKYBREAKER_H || me->GetTransport()->GetEntry() == GO_ORGRIMS_HAMMER_A;
            _instance->SetBossState(DATA_ICECROWN_GUNSHIP_BATTLE, isVictory ? DONE : FAIL);
            me->GetMap()->SetZoneMusic(AREA_ICECROWN_CITADEL, 0);
            if (Creature* creature = _instance->GetCreature(me->GetEntry() == NPC_ORGRIMS_HAMMER ? DATA_THE_SKYBREAKER : DATA_ORGRIMS_HAMMER))
            {
                _instance->SendEncounterUnit(ENCOUNTER_FRAME_DISENGAGE, creature);
                if (Aura* a = creature->GetAura(SPELL_CHECK_FOR_PLAYERS))
                    a->SetDuration(0);
            }
            _instance->SendEncounterUnit(ENCOUNTER_FRAME_DISENGAGE, me);
            if (Aura* a = me->GetAura(SPELL_CHECK_FOR_PLAYERS))
                a->SetDuration(0);
            uint32 explosionSpell = isVictory ? SPELL_EXPLOSION_VICTORY : SPELL_EXPLOSION_WIPE;
            if (MotionTransport* t = (me->GetTransport() ? me->GetTransport()->ToMotionTransport() : nullptr))
            {
                Transport::PassengerSet const& passengers = t->GetStaticPassengers();
                for (Transport::PassengerSet::const_iterator itr = passengers.begin(); itr != passengers.end(); ++itr)
                {
                    if (!(*itr)->IsCreature() || (*itr)->GetEntry() != NPC_GUNSHIP_HULL)
                        continue;
                    (*itr)->ToCreature()->CastSpell((*itr)->ToCreature(), explosionSpell, true);
                }
            }
            uint32 cannonEntry = _teamIdInInstance == TEAM_HORDE ? NPC_HORDE_GUNSHIP_CANNON : NPC_ALLIANCE_GUNSHIP_CANNON;
            if (GameObject* go = _instance->instance->GetGameObject(_instance->GetGuidData(DATA_ICECROWN_GUNSHIP_BATTLE)))
                if (MotionTransport* t = go->ToMotionTransport())
                {
                    Transport::PassengerSet const& passengers = t->GetStaticPassengers();
                    for (Transport::PassengerSet::const_iterator itr = passengers.begin(); itr != passengers.end(); ++itr)
                    {
                        if (!(*itr)->IsCreature() || (*itr)->GetEntry() != cannonEntry)
                            continue;
                        Creature* cannon = (*itr)->ToCreature();
                        cannon->CastSpell(cannon, SPELL_EJECT_ALL_PASSENGERS, true);
                        WorldPacket data(SMSG_PLAYER_VEHICLE_DATA, cannon->GetPackGUID().size() + 4);
                        data << cannon->GetPackGUID();
                        data << uint32(0);
                        cannon->SendMessageToSet(&data, true);
                        cannon->RemoveVehicleKit();
                    }
                }
            uint32 creatureEntry = NPC_IGB_MURADIN_BRONZEBEARD;
            uint8 textId = isVictory ? SAY_MURADIN_VICTORY : SAY_MURADIN_WIPE;
            if (_teamIdInInstance == TEAM_HORDE)
            {
                creatureEntry = NPC_IGB_HIGH_OVERLORD_SAURFANG;
                textId = isVictory ? SAY_SAURFANG_VICTORY : SAY_SAURFANG_WIPE;
            }
            if (Creature* creature = me->FindNearestCreature(creatureEntry, 200.0f))
                creature->AI()->Talk(textId);
            if (isVictory)
            {
                if (Transport * transport = _instance->instance->GetTransport(_instance->GetGuidData(DATA_ICECROWN_GUNSHIP_BATTLE)))
                    if (MotionTransport* otherTransport = transport->ToMotionTransport())
                        otherTransport->EnableMovement(true);
                me->GetTransport()->ToMotionTransport()->EnableMovement(true);
                if (Creature* ship = _instance->GetCreature(_teamIdInInstance == TEAM_HORDE ? DATA_ORGRIMS_HAMMER : DATA_THE_SKYBREAKER))
                {
                    ship->CastSpell(ship, SPELL_TELEPORT_PLAYERS_ON_VICTORY, true);
                    ship->CastSpell(ship, SPELL_ACHIEVEMENT, true);
                    ship->CastSpell(ship, SPELL_AWARD_REPUTATION_BOSS_KILL, true);
                }
                for (uint8 i = 0; i < 2; ++i)
                    if (GameObject* go = _instance->instance->GetGameObject(_instance->GetGuidData(i == 0 ? DATA_ICECROWN_GUNSHIP_BATTLE : DATA_ENEMY_GUNSHIP)))
                        if (MotionTransport* t = go->ToMotionTransport())
{
                            Transport::PassengerSet const& passengers = t->GetPassengers();
                            for (Transport::PassengerSet::const_iterator itr = passengers.begin(); itr != passengers.end(); ++itr)
{
                                if (!(*itr)->IsCreature())
                                    continue;
                                Creature* c = (*itr)->ToCreature();
                                if (c->GetEntry() == NPC_SKYBREAKER_MARINE || c->GetEntry() == NPC_SKYBREAKER_SERGEANT || c->GetEntry() == NPC_KOR_KRON_REAVER || c->GetEntry() == NPC_KOR_KRON_SERGEANT)
                                    c->DespawnOrUnsummon(1);
                            }
                        }
            }
            else
            {
                uint32 teleportSpellId = _teamIdInInstance == TEAM_HORDE ? SPELL_TELEPORT_PLAYERS_ON_RESET_H : SPELL_TELEPORT_PLAYERS_ON_RESET_A;
                me->m_Events.AddEvent(new ResetEncounterEvent(me, teleportSpellId, _instance->GetGuidData(DATA_ENEMY_GUNSHIP)), me->m_Events.CalculateTime(8000));
            }
        }
References _died, _instance, _teamIdInInstance, EventProcessor::AddEvent(), AREA_ICECROWN_CITADEL, EventProcessor::CalculateTime(), Unit::CastSpell(), DATA_ENEMY_GUNSHIP, DATA_ICECROWN_GUNSHIP_BATTLE, DATA_ORGRIMS_HAMMER, DATA_THE_SKYBREAKER, Creature::DespawnOrUnsummon(), DONE, MotionTransport::EnableMovement(), ENCOUNTER_FRAME_DISENGAGE, FAIL, WorldObject::FindNearestCreature(), Unit::GetAura(), InstanceScript::GetBossState(), InstanceScript::GetCreature(), Object::GetEntry(), Map::GetGameObject(), InstanceScript::GetGuidData(), WorldObject::GetMap(), Object::GetPackGUID(), WorldObject::GetTransport(), Map::GetTransport(), GO_ORGRIMS_HAMMER_A, GO_THE_SKYBREAKER_H, IN_PROGRESS, InstanceScript::instance, WorldObject::m_Events, CreatureAI::me, NPC_ALLIANCE_GUNSHIP_CANNON, NPC_GUNSHIP_HULL, NPC_HORDE_GUNSHIP_CANNON, NPC_IGB_HIGH_OVERLORD_SAURFANG, NPC_IGB_MURADIN_BRONZEBEARD, NPC_KOR_KRON_REAVER, NPC_KOR_KRON_SERGEANT, NPC_ORGRIMS_HAMMER, NPC_SKYBREAKER_MARINE, NPC_SKYBREAKER_SERGEANT, Unit::RemoveVehicleKit(), SAY_MURADIN_VICTORY, SAY_MURADIN_WIPE, SAY_SAURFANG_VICTORY, SAY_SAURFANG_WIPE, InstanceScript::SendEncounterUnit(), WorldObject::SendMessageToSet(), InstanceScript::SetBossState(), Map::SetZoneMusic(), PackedGuid::size(), SMSG_PLAYER_VEHICLE_DATA, SPELL_ACHIEVEMENT, SPELL_AWARD_REPUTATION_BOSS_KILL, SPELL_CHECK_FOR_PLAYERS, SPELL_EJECT_ALL_PASSENGERS, SPELL_EXPLOSION_VICTORY, SPELL_EXPLOSION_WIPE, SPELL_TELEPORT_PLAYERS_ON_RESET_A, SPELL_TELEPORT_PLAYERS_ON_RESET_H, SPELL_TELEPORT_PLAYERS_ON_VICTORY, TEAM_HORDE, Object::ToCreature(), and GameObject::ToMotionTransport().
SetGUID()
void npc_gunship::npc_gunshipAI::SetGUID (ObjectGuid guid, int32 id) inline override virtual
Reimplemented from UnitAI.
        {
            if (id != ACTION_SHIP_VISITS_ENEMY && id != ACTION_SHIP_VISITS_SELF)
                return;
            std::map<ObjectGuid, uint32>::iterator itr = _shipVisits.find(guid);
            if (itr == _shipVisits.end())
            {
                if (id == ACTION_SHIP_VISITS_ENEMY)
                    _shipVisits[guid] = ACTION_SHIP_VISITS_ENEMY;
            }
            else if (itr->second) // if 0 then achiev already failed
            {
                if (id == ACTION_SHIP_VISITS_SELF)
                {
                    if (itr->second == ACTION_SHIP_VISITS_ENEMY)
                        itr->second = ACTION_SHIP_VISITS_SELF;
                    else if (itr->second == ACTION_SHIP_VISITS_ENEMY_2)
                        itr->second = ACTION_SHIP_VISITS_SELF_2;
                }
                else
                {
                    if (itr->second == ACTION_SHIP_VISITS_SELF)
                    {
                        if (me->GetMap()->Is25ManRaid())
                            itr->second = 0;
                        else
                            itr->second = ACTION_SHIP_VISITS_ENEMY_2;
                    }
                    else if (itr->second == ACTION_SHIP_VISITS_SELF_2)
                        itr->second = 0;
                }
            }
        }
References _shipVisits, ACTION_SHIP_VISITS_ENEMY, ACTION_SHIP_VISITS_ENEMY_2, ACTION_SHIP_VISITS_SELF, ACTION_SHIP_VISITS_SELF_2, WorldObject::GetMap(), Map::Is25ManRaid(), and CreatureAI::me.
UpdateAI()
void npc_gunship::npc_gunshipAI::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Implements UnitAI.
        {
            if (!sConfigMgr->GetOption<int32>("WipeGunshipBlizzlike.Enable", 1))
                return;
            if (_instance->GetBossState(DATA_ICECROWN_GUNSHIP_BATTLE) != IN_PROGRESS)
                return;
            bool playerOnDeck = false;
            me->GetMap()->DoForAllPlayers([&](Player* player)
                {
                    if (!player->GetVehicle() && player->IsAlive())
                        playerOnDeck = true;
                });
            // Wipe if no player is on the deck
            if (!playerOnDeck)
            {
                // Script runs on enemy ship. We want to kill our ship.
                if (Creature* ship = _instance->GetCreature(_teamIdInInstance == TEAM_HORDE ? DATA_ORGRIMS_HAMMER : DATA_THE_SKYBREAKER))
                    Creature::Kill(me, ship);
            }
        }
References _instance, _teamIdInInstance, DATA_ICECROWN_GUNSHIP_BATTLE, DATA_ORGRIMS_HAMMER, DATA_THE_SKYBREAKER, Map::DoForAllPlayers(), InstanceScript::GetBossState(), InstanceScript::GetCreature(), WorldObject::GetMap(), Unit::GetVehicle(), IN_PROGRESS, Unit::IsAlive(), Unit::Kill(), CreatureAI::me, sConfigMgr, and TEAM_HORDE.
Member Data Documentation
_died
bool npc_gunship::npc_gunshipAI::_died private
Referenced by JustDied().
_instance
InstanceScript* npc_gunship::npc_gunshipAI::_instance private
Referenced by DamageTaken(), JustDied(), and UpdateAI().
_shipVisits
std::map<ObjectGuid, uint32> npc_gunship::npc_gunshipAI::_shipVisits private
Referenced by GetData(), and SetGUID().
_summonedFirstMage
bool npc_gunship::npc_gunshipAI::_summonedFirstMage private
Referenced by DamageTaken().
_teamIdInInstance
TeamId npc_gunship::npc_gunshipAI::_teamIdInInstance private
Referenced by DamageTaken(), JustDied(), and UpdateAI().
The documentation for this struct was generated from the following file:
azerothcore-wotlk/src/server/scripts/Northrend/IcecrownCitadel/boss_icecrown_gunship_battle.cpp