AzerothCore Doxygen
bosses_opera.cpp File Reference
#include "CreatureScript.h"
#include "Player.h"
#include "ScriptedCreature.h"
#include "ScriptedGossip.h"
#include "SpellInfo.h"
#include "TaskScheduler.h"
#include "karazhan.h"
Classes
struct boss_dorothee
struct npc_tito
struct boss_roar
struct boss_strawman
struct boss_tinhead
struct boss_crone
struct npc_cyclone
struct npc_grandmother
struct boss_bigbadwolf
struct boss_julianne
struct boss_romulo
Enumerations
enum Says {
SAY_DOROTHEE_DEATH = 0 ,
SAY_DOROTHEE_SUMMON = 1 ,
SAY_DOROTHEE_TITO_DEATH = 2 ,
SAY_DOROTHEE_AGGRO = 3 ,
SAY_ROAR_AGGRO = 0 ,
SAY_ROAR_DEATH = 1 ,
SAY_ROAR_SLAY = 2 ,
SAY_STRAWMAN_AGGRO = 0 ,
SAY_STRAWMAN_DEATH = 1 ,
SAY_STRAWMAN_SLAY = 2 ,
SAY_TINHEAD_AGGRO = 0 ,
SAY_TINHEAD_DEATH = 1 ,
SAY_TINHEAD_SLAY = 2 ,
EMOTE_RUST = 3 ,
SAY_CRONE_AGGRO = 0 ,
SAY_CRONE_DEATH = 1 ,
SAY_CRONE_SLAY = 2
}
enum Spells {
SPELL_WATERBOLT = 31012 ,
SPELL_SCREAM = 31013 ,
SPELL_SUMMONTITO = 31014 ,
SPELL_YIPPING = 31015 ,
SPELL_BRAIN_BASH = 31046 ,
SPELL_BRAIN_WIPE = 31069 ,
SPELL_BURNING_STRAW = 31075 ,
SPELL_CLEAVE = 31043 ,
SPELL_RUST = 31086 ,
SPELL_MANGLE = 31041 ,
SPELL_SHRED = 31042 ,
SPELL_FRIGHTENED_SCREAM = 31013 ,
SPELL_CHAIN_LIGHTNING = 32337 ,
SPELL_KNOCKBACK = 32334 ,
SPELL_CYCLONE_VISUAL = 32332
}
enum Creatures {
CREATURE_TITO = 17548 ,
CREATURE_CYCLONE = 18412 ,
CREATURE_CRONE = 18168
}
enum OZActions { ACTION_RELEASE = 1 }
enum RedRidingHood {
SAY_WOLF_AGGRO = 0 ,
SAY_WOLF_SLAY = 1 ,
SAY_WOLF_HOOD = 2 ,
SOUND_WOLF_DEATH = 9275 ,
SPELL_LITTLE_RED_RIDING_HOOD = 30768 ,
SPELL_TERRIFYING_HOWL = 30752 ,
SPELL_WIDE_SWIPE = 30761 ,
SPELL_PICNIC_BASKET_SMELL = 30755 ,
CREATURE_BIG_BAD_WOLF = 17521 ,
GRANDMOTHER_GOSSIP_MENU1 = 7441 ,
GRANDMOTHER_GOSSIP_MENU2 = 7442 ,
GRANDMOTHER_GOSSIP_MENU3 = 7443 ,
GRANDMOTHER_TEXT1 = 9009 ,
GRANDMOTHER_TEXT2 = 9010 ,
GRANDMOTHER_TEXT3 = 9011
}
enum JulianneRomulo {
SAY_JULIANNE_AGGRO = 0 ,
SAY_JULIANNE_ENTER = 1 ,
SAY_JULIANNE_DEATH01 = 2 ,
SAY_JULIANNE_DEATH02 = 3 ,
SAY_JULIANNE_RESURRECT = 4 ,
SAY_JULIANNE_SLAY = 5 ,
SAY_ROMULO_AGGRO = 0 ,
SAY_ROMULO_DEATH = 1 ,
SAY_ROMULO_DEATH2 = 2 ,
SAY_ROMULO_RESURRECT = 3 ,
SAY_ROMULO_SLAY = 4 ,
SPELL_BLINDING_PASSION = 30890 ,
SPELL_DEVOTION = 30887 ,
SPELL_ETERNAL_AFFECTION = 30878 ,
SPELL_POWERFUL_ATTRACTION = 30889 ,
SPELL_DRINK_POISON = 30907 ,
SPELL_BACKWARD_LUNGE = 30815 ,
SPELL_DARING = 30841 ,
SPELL_DEADLY_SWATHE = 30817 ,
SPELL_POISON_THRUST = 30822 ,
SPELL_UNDYING_LOVE = 30951 ,
SPELL_RES_VISUAL = 24171 ,
CREATURE_ROMULO = 17533 ,
ROMULO_X = -10900 ,
ROMULO_Y = -1758
}
enum RAJPhase {
PHASE_JULIANNE = 0 ,
PHASE_ROMULO = 1 ,
PHASE_BOTH = 2
}
enum RAJGroups {
GROUP_COMBAT = 0 ,
GROUP_RP = 1
}
enum RAJActions {
ACTION_FAKING_DEATH = 2 ,
ACTION_COMBAT_SCHEDULE = 3 ,
ACTION_CANCEL_COMBAT = 6
}
Functions
void SummonCroneIfReady (InstanceScript *instance, Creature *creature)
void DespawnAll (InstanceScript *instance)
void DoActions (InstanceScript *instance)
void PretendToDie (Creature *creature)
void Resurrect (Creature *target)
void AddSC_bosses_opera ()
Enumeration Type Documentation
Creatures
enum Creatures
Enumerator
CREATURE_TITO
CREATURE_CYCLONE
CREATURE_CRONE
{
    CREATURE_TITO           = 17548,
    CREATURE_CYCLONE        = 18412,
    CREATURE_CRONE          = 18168,
};
JulianneRomulo
enum JulianneRomulo
Enumerator
SAY_JULIANNE_AGGRO
SAY_JULIANNE_ENTER
SAY_JULIANNE_DEATH01
SAY_JULIANNE_DEATH02
SAY_JULIANNE_RESURRECT
SAY_JULIANNE_SLAY
SAY_ROMULO_AGGRO
SAY_ROMULO_DEATH
SAY_ROMULO_DEATH2
SAY_ROMULO_RESURRECT
SAY_ROMULO_SLAY
SPELL_BLINDING_PASSION
SPELL_DEVOTION
SPELL_ETERNAL_AFFECTION
SPELL_POWERFUL_ATTRACTION
SPELL_DRINK_POISON
SPELL_BACKWARD_LUNGE
SPELL_DARING
SPELL_DEADLY_SWATHE
SPELL_POISON_THRUST
SPELL_UNDYING_LOVE
SPELL_RES_VISUAL
CREATURE_ROMULO
ROMULO_X
ROMULO_Y
{
    /**** Speech *****/
    SAY_JULIANNE_AGGRO              = 0,
    SAY_JULIANNE_ENTER              = 1,
    SAY_JULIANNE_DEATH01            = 2,
    SAY_JULIANNE_DEATH02            = 3,
    SAY_JULIANNE_RESURRECT          = 4,
    SAY_JULIANNE_SLAY               = 5,
    SAY_ROMULO_AGGRO                = 0,
    SAY_ROMULO_DEATH                = 1,
    SAY_ROMULO_DEATH2               = 2,
    SAY_ROMULO_RESURRECT            = 3,
    SAY_ROMULO_SLAY                 = 4,
    SPELL_BLINDING_PASSION          = 30890,
    SPELL_DEVOTION                  = 30887,
    SPELL_ETERNAL_AFFECTION         = 30878,
    SPELL_POWERFUL_ATTRACTION       = 30889,
    SPELL_DRINK_POISON              = 30907,
    SPELL_BACKWARD_LUNGE            = 30815,
    SPELL_DARING                    = 30841,
    SPELL_DEADLY_SWATHE             = 30817,
    SPELL_POISON_THRUST             = 30822,
    SPELL_UNDYING_LOVE              = 30951,
    SPELL_RES_VISUAL                = 24171,
    CREATURE_ROMULO                 = 17533,
    ROMULO_X                        = -10900,
    ROMULO_Y                        = -1758,
};
OZActions
enum OZActions
Enumerator
ACTION_RELEASE
{
    ACTION_RELEASE          = 1,
};
RAJActions
enum RAJActions
Enumerator
ACTION_FAKING_DEATH
ACTION_COMBAT_SCHEDULE
ACTION_CANCEL_COMBAT
{
    ACTION_FAKING_DEATH     = 2,
    ACTION_COMBAT_SCHEDULE  = 3,
    //ACTION_DO_RESURRECT     = 4,
    //ACTION_RESS_ROMULO      = 5,
    ACTION_CANCEL_COMBAT    = 6
};
RAJGroups
enum RAJGroups
Enumerator
GROUP_COMBAT
GROUP_RP
{
    GROUP_COMBAT        = 0,
    GROUP_RP            = 1
};
RAJPhase
enum RAJPhase
Enumerator
PHASE_JULIANNE
PHASE_ROMULO
PHASE_BOTH
{
    PHASE_JULIANNE      = 0,
    PHASE_ROMULO        = 1,
    PHASE_BOTH          = 2,
};
RedRidingHood
enum RedRidingHood
Enumerator
SAY_WOLF_AGGRO
SAY_WOLF_SLAY
SAY_WOLF_HOOD
SOUND_WOLF_DEATH
SPELL_LITTLE_RED_RIDING_HOOD
SPELL_TERRIFYING_HOWL
SPELL_WIDE_SWIPE
SPELL_PICNIC_BASKET_SMELL
CREATURE_BIG_BAD_WOLF
GRANDMOTHER_GOSSIP_MENU1
GRANDMOTHER_GOSSIP_MENU2
GRANDMOTHER_GOSSIP_MENU3
GRANDMOTHER_TEXT1
GRANDMOTHER_TEXT2
GRANDMOTHER_TEXT3
{
    SAY_WOLF_AGGRO                  = 0,
    SAY_WOLF_SLAY                   = 1,
    SAY_WOLF_HOOD                   = 2,
    SOUND_WOLF_DEATH                = 9275,
    SPELL_LITTLE_RED_RIDING_HOOD    = 30768,
    SPELL_TERRIFYING_HOWL           = 30752,
    SPELL_WIDE_SWIPE                = 30761,
    SPELL_PICNIC_BASKET_SMELL       = 30755,
    CREATURE_BIG_BAD_WOLF           = 17521,
    GRANDMOTHER_GOSSIP_MENU1        = 7441,
    GRANDMOTHER_GOSSIP_MENU2        = 7442,
    GRANDMOTHER_GOSSIP_MENU3        = 7443,
    GRANDMOTHER_TEXT1               = 9009,
    GRANDMOTHER_TEXT2               = 9010,
    GRANDMOTHER_TEXT3               = 9011
};
Says
enum Says
Enumerator
SAY_DOROTHEE_DEATH
SAY_DOROTHEE_SUMMON
SAY_DOROTHEE_TITO_DEATH
SAY_DOROTHEE_AGGRO
SAY_ROAR_AGGRO
SAY_ROAR_DEATH
SAY_ROAR_SLAY
SAY_STRAWMAN_AGGRO
SAY_STRAWMAN_DEATH
SAY_STRAWMAN_SLAY
SAY_TINHEAD_AGGRO
SAY_TINHEAD_DEATH
SAY_TINHEAD_SLAY
EMOTE_RUST
SAY_CRONE_AGGRO
SAY_CRONE_DEATH
SAY_CRONE_SLAY
{
    SAY_DOROTHEE_DEATH          = 0,
    SAY_DOROTHEE_SUMMON         = 1,
    SAY_DOROTHEE_TITO_DEATH     = 2,
    SAY_DOROTHEE_AGGRO          = 3,
    SAY_ROAR_AGGRO              = 0,
    SAY_ROAR_DEATH              = 1,
    SAY_ROAR_SLAY               = 2,
    SAY_STRAWMAN_AGGRO          = 0,
    SAY_STRAWMAN_DEATH          = 1,
    SAY_STRAWMAN_SLAY           = 2,
    SAY_TINHEAD_AGGRO           = 0,
    SAY_TINHEAD_DEATH           = 1,
    SAY_TINHEAD_SLAY            = 2,
    EMOTE_RUST                  = 3,
    SAY_CRONE_AGGRO             = 0,
    SAY_CRONE_DEATH             = 1,
    SAY_CRONE_SLAY              = 2,
};
Spells
enum Spells
Enumerator
SPELL_WATERBOLT
SPELL_SCREAM
SPELL_SUMMONTITO
SPELL_YIPPING
SPELL_BRAIN_BASH
SPELL_BRAIN_WIPE
SPELL_BURNING_STRAW
SPELL_CLEAVE
SPELL_RUST
SPELL_MANGLE
SPELL_SHRED
SPELL_FRIGHTENED_SCREAM
SPELL_CHAIN_LIGHTNING
SPELL_KNOCKBACK
SPELL_CYCLONE_VISUAL
{
    // Dorothee
    SPELL_WATERBOLT         = 31012,
    SPELL_SCREAM            = 31013,
    SPELL_SUMMONTITO        = 31014,
    // Tito
    SPELL_YIPPING           = 31015,
    // Strawman
    SPELL_BRAIN_BASH        = 31046,
    SPELL_BRAIN_WIPE        = 31069,
    SPELL_BURNING_STRAW     = 31075,
    // Tinhead
    SPELL_CLEAVE            = 31043,
    SPELL_RUST              = 31086,
    // Roar
    SPELL_MANGLE            = 31041,
    SPELL_SHRED             = 31042,
    SPELL_FRIGHTENED_SCREAM = 31013,
    // Crone
    SPELL_CHAIN_LIGHTNING   = 32337,
    // Cyclone
    SPELL_KNOCKBACK         = 32334,
    SPELL_CYCLONE_VISUAL    = 32332,
};
Function Documentation
AddSC_bosses_opera()
void AddSC_bosses_opera ()
{
    RegisterKarazhanCreatureAI(boss_dorothee);
    RegisterKarazhanCreatureAI(boss_strawman);
    RegisterKarazhanCreatureAI(boss_tinhead);
    RegisterKarazhanCreatureAI(boss_roar);
    RegisterKarazhanCreatureAI(boss_crone);
    RegisterKarazhanCreatureAI(npc_tito);
    RegisterKarazhanCreatureAI(npc_cyclone);
    new npc_grandmother();
    RegisterKarazhanCreatureAI(boss_bigbadwolf);
    RegisterKarazhanCreatureAI(boss_julianne);
    RegisterKarazhanCreatureAI(boss_romulo);
}
References RegisterKarazhanCreatureAI.
Referenced by AddEasternKingdomsScripts().
DespawnAll()
void DespawnAll (InstanceScript * instance)
{
    if (Creature* dorothee = instance->GetCreature(DATA_DOROTHEE))
    {
        dorothee->DespawnOrUnsummon();
    }
    if (Creature* roar = instance->GetCreature(DATA_ROAR))
    {
        roar->DespawnOrUnsummon();
    }
    if (Creature* strawman = instance->GetCreature(DATA_STRAWMAN))
    {
        strawman->DespawnOrUnsummon();
    }
    if (Creature* tinhead = instance->GetCreature(DATA_TINHEAD))
    {
        tinhead->DespawnOrUnsummon();
    }
    if (Creature* tito = instance->GetCreature(DATA_TITO))
    {
        tito->DespawnOrUnsummon();
    }
}
References DATA_DOROTHEE, DATA_ROAR, DATA_STRAWMAN, DATA_TINHEAD, DATA_TITO, and InstanceScript::GetCreature().
Referenced by boss_dorothee::EnterEvadeMode(), boss_roar::EnterEvadeMode(), boss_strawman::EnterEvadeMode(), and boss_tinhead::EnterEvadeMode().
DoActions()
void DoActions (InstanceScript * instance)
{
    uint32 datas[4] = {DATA_DOROTHEE, DATA_ROAR, DATA_STRAWMAN, DATA_TINHEAD};
    for (uint32 data : datas)
    {
        if (Creature* actionCreature = instance->GetCreature(data))
        {
            actionCreature->AI()->DoAction(ACTION_RELEASE);
        }
    }
}
References ACTION_RELEASE, DATA_DOROTHEE, DATA_ROAR, DATA_STRAWMAN, DATA_TINHEAD, and InstanceScript::GetCreature().
Referenced by boss_dorothee::UpdateAI().
PretendToDie()
void PretendToDie (Creature * creature)
{
    creature->AI()->DoAction(ACTION_CANCEL_COMBAT);
    creature->InterruptNonMeleeSpells(true);
    creature->RemoveAllAuras();
    creature->SetUnitFlag(UNIT_FLAG_NOT_SELECTABLE);
    creature->SetReactState(REACT_PASSIVE);
    creature->GetMotionMaster()->MovementExpired(false);
    creature->GetMotionMaster()->MoveIdle();
    creature->SetStandState(UNIT_STAND_STATE_DEAD);
}
References ACTION_CANCEL_COMBAT, Creature::AI(), UnitAI::DoAction(), Unit::GetMotionMaster(), Unit::InterruptNonMeleeSpells(), MotionMaster::MoveIdle(), MotionMaster::MovementExpired(), REACT_PASSIVE, Unit::RemoveAllAuras(), Creature::SetReactState(), Unit::SetStandState(), Unit::SetUnitFlag(), UNIT_FLAG_NOT_SELECTABLE, and UNIT_STAND_STATE_DEAD.
Referenced by boss_julianne::DamageTaken(), boss_romulo::DamageTaken(), and boss_julianne::SpellHit().
Resurrect()
void Resurrect (Creature * target)
{
    target->RemoveUnitFlag(UNIT_FLAG_NOT_SELECTABLE);
    target->SetReactState(REACT_AGGRESSIVE);
    target->SetFullHealth();
    target->SetStandState(UNIT_STAND_STATE_STAND);
    target->CastSpell(target, SPELL_RES_VISUAL, true);
    target->AI()->DoAction(ACTION_COMBAT_SCHEDULE);
    if (target->GetVictim())
    {
        target->GetMotionMaster()->MoveChase(target->GetVictim());
        target->AI()->AttackStart(target->GetVictim());
    }
    else
        target->GetMotionMaster()->Initialize();
}
References ACTION_COMBAT_SCHEDULE, Creature::AI(), UnitAI::AttackStart(), Unit::CastSpell(), UnitAI::DoAction(), Unit::GetMotionMaster(), Unit::GetVictim(), MotionMaster::Initialize(), MotionMaster::MoveChase(), REACT_AGGRESSIVE, Unit::RemoveUnitFlag(), Unit::SetFullHealth(), Creature::SetReactState(), Unit::SetStandState(), SPELL_RES_VISUAL, UNIT_FLAG_NOT_SELECTABLE, and UNIT_STAND_STATE_STAND.
Referenced by boss_romulo::DamageTaken(), boss_julianne::DoAction(), boss_julianne::Reset(), and Battlefield::Update().
SummonCroneIfReady()
void SummonCroneIfReady (InstanceScript * instance, Creature * creature)
{
    instance->SetData(DATA_OPERA_OZ_DEATHCOUNT, SPECIAL);  // Increment DeathCount
    if (instance->GetData(DATA_OPERA_OZ_DEATHCOUNT) == 4)
    {
        if (Creature* pCrone = creature->SummonCreature(CREATURE_CRONE, -10891.96f, -1755.95f, creature->GetPositionZ(), 4.64f, TEMPSUMMON_TIMED_OR_DEAD_DESPAWN, HOUR * 2 * IN_MILLISECONDS))
        {
            if (creature->GetVictim())
                pCrone->AI()->AttackStart(creature->GetVictim());
            pCrone->RemoveUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
            pCrone->SetImmuneToPC(false);
        }
    }
}
References CREATURE_CRONE, DATA_OPERA_OZ_DEATHCOUNT, ZoneScript::GetData(), Position::GetPositionZ(), Unit::GetVictim(), HOUR, IN_MILLISECONDS, ZoneScript::SetData(), SPECIAL, WorldObject::SummonCreature(), TEMPSUMMON_TIMED_OR_DEAD_DESPAWN, and UNIT_FLAG_NON_ATTACKABLE.
Referenced by boss_dorothee::JustDied(), boss_roar::JustDied(), boss_strawman::JustDied(), and boss_tinhead::JustDied().