AzerothCore Doxygen
MapGrid< GRID_OBJECT_TYPES, FAR_VISIBLE_OBJECT_TYPES > Class Template Reference
#include "MapGrid.h"
Public Types
typedef GridCell< GRID_OBJECT_TYPES, FAR_VISIBLE_OBJECT_TYPES > GridCellType
Public Member Functions
MapGrid (uint16 const x, uint16 const y)
uint32 GetId () const
uint16 GetX () const
uint16 GetY () const
bool IsObjectDataLoaded () const
void SetObjectDataLoaded ()
template<class SPECIFIC_OBJECT >
void AddGridObject (uint16 const x, uint16 const y, SPECIFIC_OBJECT *obj)
template<class SPECIFIC_OBJECT >
void RemoveGridObject (uint16 const x, uint16 const y, SPECIFIC_OBJECT *obj)
template<class SPECIFIC_OBJECT >
void AddFarVisibleObject (uint16 const x, uint16 const y, SPECIFIC_OBJECT *obj)
template<class SPECIFIC_OBJECT >
void RemoveFarVisibleObject (uint16 const x, uint16 const y, SPECIFIC_OBJECT *obj)
template<class T , class TT >
void VisitAllCells (TypeContainerVisitor< T, TT > &visitor)
template<class T , class TT >
void VisitCell (uint16 const x, uint16 const y, TypeContainerVisitor< T, TT > &visitor)
void link (GridRefMgr< MapGrid< GRID_OBJECT_TYPES, FAR_VISIBLE_OBJECT_TYPES > > *pTo)
GridTerrainData * GetTerrainData () const
std::shared_ptr< GridTerrainData > GetTerrainDataSharedPtr ()
void SetTerrainData (std::shared_ptr< GridTerrainData > terrainData)
uint32 GetCreatedCellsCount ()
Private Member Functions
GridCellType & GetOrCreateCell (uint16 const x, uint16 const y)
GridCellType * GetCell (uint16 const x, uint16 const y)
GridCellType const * GetCell (uint16 const x, uint16 const y) const
Private Attributes
uint16 _x
uint16 _y
bool _objectDataLoaded
std::array< std::array< std::unique_ptr< GridCellType >, MAX_NUMBER_OF_CELLS >, MAX_NUMBER_OF_CELLS > _cells
GridReference< MapGrid< GRID_OBJECT_TYPES, FAR_VISIBLE_OBJECT_TYPES > > _gridReference
std::shared_ptr< GridTerrainData > _terrainData
Detailed Description
template<class GRID_OBJECT_TYPES, class FAR_VISIBLE_OBJECT_TYPES>
class MapGrid< GRID_OBJECT_TYPES, FAR_VISIBLE_OBJECT_TYPES >
Member Typedef Documentation
GridCellType
template<class GRID_OBJECT_TYPES , class FAR_VISIBLE_OBJECT_TYPES > typedef GridCell<GRID_OBJECT_TYPES, FAR_VISIBLE_OBJECT_TYPES> MapGrid< GRID_OBJECT_TYPES, FAR_VISIBLE_OBJECT_TYPES >::GridCellType
Constructor & Destructor Documentation
MapGrid()
template<class GRID_OBJECT_TYPES , class FAR_VISIBLE_OBJECT_TYPES > MapGrid< GRID_OBJECT_TYPES, FAR_VISIBLE_OBJECT_TYPES >::MapGrid (uint16 const x, uint16 const y) inline
        : _x(x), _y(y), _objectDataLoaded(false), _terrainData(nullptr) { }
Member Function Documentation
AddFarVisibleObject()
template<class GRID_OBJECT_TYPES , class FAR_VISIBLE_OBJECT_TYPES > template<class SPECIFIC_OBJECT > void MapGrid< GRID_OBJECT_TYPES, FAR_VISIBLE_OBJECT_TYPES >::AddFarVisibleObject (uint16 const x, uint16 const y, SPECIFIC_OBJECT * obj) inline
    {
        GetOrCreateCell(x, y).AddFarVisibleObject(obj);
    }
References GridCell< GRID_OBJECT_TYPES, FAR_VISIBLE_OBJECT_TYPES >::AddFarVisibleObject(), and MapGrid< GRID_OBJECT_TYPES, FAR_VISIBLE_OBJECT_TYPES >::GetOrCreateCell().
Referenced by Map::AddToGrid(), Map::AddToGrid(), and Map::AddWorldObjectToFarVisibleMap().
AddGridObject()
template<class GRID_OBJECT_TYPES , class FAR_VISIBLE_OBJECT_TYPES > template<class SPECIFIC_OBJECT > void MapGrid< GRID_OBJECT_TYPES, FAR_VISIBLE_OBJECT_TYPES >::AddGridObject (uint16 const x, uint16 const y, SPECIFIC_OBJECT * obj) inline
    {
        GetOrCreateCell(x, y).AddGridObject(obj);
    }
References GridCell< GRID_OBJECT_TYPES, FAR_VISIBLE_OBJECT_TYPES >::AddGridObject(), and MapGrid< GRID_OBJECT_TYPES, FAR_VISIBLE_OBJECT_TYPES >::GetOrCreateCell().
Referenced by Map::AddToGrid(), Map::AddToGrid(), Map::AddToGrid(), Map::AddToGrid(), and Map::AddToGrid().
GetCell() [1/2]
template<class GRID_OBJECT_TYPES , class FAR_VISIBLE_OBJECT_TYPES > GridCellType * MapGrid< GRID_OBJECT_TYPES, FAR_VISIBLE_OBJECT_TYPES >::GetCell (uint16 const x, uint16 const y) inline private
    {
        ASSERT(x < MAX_NUMBER_OF_CELLS && y < MAX_NUMBER_OF_CELLS);
        return _cells[x][y].get();
    }
References MapGrid< GRID_OBJECT_TYPES, FAR_VISIBLE_OBJECT_TYPES >::_cells, ASSERT, and MAX_NUMBER_OF_CELLS.
Referenced by MapGrid< GRID_OBJECT_TYPES, FAR_VISIBLE_OBJECT_TYPES >::GetOrCreateCell(), and MapGrid< GRID_OBJECT_TYPES, FAR_VISIBLE_OBJECT_TYPES >::VisitCell().
GetCell() [2/2]
template<class GRID_OBJECT_TYPES , class FAR_VISIBLE_OBJECT_TYPES > GridCellType const * MapGrid< GRID_OBJECT_TYPES, FAR_VISIBLE_OBJECT_TYPES >::GetCell (uint16 const x, uint16 const y) const inline private
    {
        ASSERT(x < MAX_NUMBER_OF_CELLS && y < MAX_NUMBER_OF_CELLS);
        return _cells[x][y].get();
    }
References MapGrid< GRID_OBJECT_TYPES, FAR_VISIBLE_OBJECT_TYPES >::_cells, ASSERT, and MAX_NUMBER_OF_CELLS.
GetCreatedCellsCount()
template<class GRID_OBJECT_TYPES , class FAR_VISIBLE_OBJECT_TYPES > uint32 MapGrid< GRID_OBJECT_TYPES, FAR_VISIBLE_OBJECT_TYPES >::GetCreatedCellsCount () inline
    {
        uint32 count = 0;
        for (auto& cellX : _cells)
        {
            for (auto& cellY : cellX)
            {
                if (!cellY)
                    continue;
                ++count;
            }
        }
        return count;
    }
References MapGrid< GRID_OBJECT_TYPES, FAR_VISIBLE_OBJECT_TYPES >::_cells.
Referenced by MapGridManager::GetCreatedCellsInGridCount().
GetId()
template<class GRID_OBJECT_TYPES , class FAR_VISIBLE_OBJECT_TYPES > uint32 MapGrid< GRID_OBJECT_TYPES, FAR_VISIBLE_OBJECT_TYPES >::GetId () const inline
{ return _y * MAX_NUMBER_OF_GRIDS + _x; }
References MapGrid< GRID_OBJECT_TYPES, FAR_VISIBLE_OBJECT_TYPES >::_x, MapGrid< GRID_OBJECT_TYPES, FAR_VISIBLE_OBJECT_TYPES >::_y, and MAX_NUMBER_OF_GRIDS.
Referenced by GridObjectLoader::LoadAllCellsInGrid().
GetOrCreateCell()
template<class GRID_OBJECT_TYPES , class FAR_VISIBLE_OBJECT_TYPES > GridCellType & MapGrid< GRID_OBJECT_TYPES, FAR_VISIBLE_OBJECT_TYPES >::GetOrCreateCell (uint16 const x, uint16 const y) inline private
    {
        GridCellType* cell = GetCell(x, y);
        if (!cell)
            _cells[x][y] = std::make_unique<GridCellType>();
        return *_cells[x][y];
    }
References MapGrid< GRID_OBJECT_TYPES, FAR_VISIBLE_OBJECT_TYPES >::_cells, and MapGrid< GRID_OBJECT_TYPES, FAR_VISIBLE_OBJECT_TYPES >::GetCell().
Referenced by MapGrid< GRID_OBJECT_TYPES, FAR_VISIBLE_OBJECT_TYPES >::AddFarVisibleObject(), MapGrid< GRID_OBJECT_TYPES, FAR_VISIBLE_OBJECT_TYPES >::AddGridObject(), MapGrid< GRID_OBJECT_TYPES, FAR_VISIBLE_OBJECT_TYPES >::RemoveFarVisibleObject(), and MapGrid< GRID_OBJECT_TYPES, FAR_VISIBLE_OBJECT_TYPES >::RemoveGridObject().
GetTerrainData()
template<class GRID_OBJECT_TYPES , class FAR_VISIBLE_OBJECT_TYPES > GridTerrainData * MapGrid< GRID_OBJECT_TYPES, FAR_VISIBLE_OBJECT_TYPES >::GetTerrainData () const inline
{ return _terrainData.get(); }
References MapGrid< GRID_OBJECT_TYPES, FAR_VISIBLE_OBJECT_TYPES >::_terrainData.
Referenced by Map::GetGridTerrainData(), and GridTerrainLoader::LoadMap().
GetTerrainDataSharedPtr()
template<class GRID_OBJECT_TYPES , class FAR_VISIBLE_OBJECT_TYPES > std::shared_ptr< GridTerrainData > MapGrid< GRID_OBJECT_TYPES, FAR_VISIBLE_OBJECT_TYPES >::GetTerrainDataSharedPtr () inline
{ return _terrainData; }
References MapGrid< GRID_OBJECT_TYPES, FAR_VISIBLE_OBJECT_TYPES >::_terrainData.
Referenced by Map::GetGridTerrainDataSharedPtr().
GetX()
template<class GRID_OBJECT_TYPES , class FAR_VISIBLE_OBJECT_TYPES > uint16 MapGrid< GRID_OBJECT_TYPES, FAR_VISIBLE_OBJECT_TYPES >::GetX () const inline
{ return _x; }
References MapGrid< GRID_OBJECT_TYPES, FAR_VISIBLE_OBJECT_TYPES >::_x.
Referenced by GridTerrainLoader::LoadMap(), GridTerrainLoader::LoadMMap(), GridTerrainLoader::LoadVMap(), Map::UnloadGrid(), and GridTerrainUnloader::UnloadTerrain().
GetY()
template<class GRID_OBJECT_TYPES , class FAR_VISIBLE_OBJECT_TYPES > uint16 MapGrid< GRID_OBJECT_TYPES, FAR_VISIBLE_OBJECT_TYPES >::GetY () const inline
{ return _y; }
References MapGrid< GRID_OBJECT_TYPES, FAR_VISIBLE_OBJECT_TYPES >::_y.
Referenced by GridTerrainLoader::LoadMap(), GridTerrainLoader::LoadMMap(), GridTerrainLoader::LoadVMap(), Map::UnloadGrid(), and GridTerrainUnloader::UnloadTerrain().
IsObjectDataLoaded()
template<class GRID_OBJECT_TYPES , class FAR_VISIBLE_OBJECT_TYPES > bool MapGrid< GRID_OBJECT_TYPES, FAR_VISIBLE_OBJECT_TYPES >::IsObjectDataLoaded () const inline
{ return _objectDataLoaded; }
References MapGrid< GRID_OBJECT_TYPES, FAR_VISIBLE_OBJECT_TYPES >::_objectDataLoaded.
Referenced by Map::AddToGrid(), and MapGridManager::LoadGrid().
link()
template<class GRID_OBJECT_TYPES , class FAR_VISIBLE_OBJECT_TYPES > void MapGrid< GRID_OBJECT_TYPES, FAR_VISIBLE_OBJECT_TYPES >::link (GridRefMgr< MapGrid< GRID_OBJECT_TYPES, FAR_VISIBLE_OBJECT_TYPES > > * pTo) inline
    {
        _gridReference.link(pTo, this);
    }
References MapGrid< GRID_OBJECT_TYPES, FAR_VISIBLE_OBJECT_TYPES >::_gridReference, and Reference< TO, FROM >::link().
RemoveFarVisibleObject()
template<class GRID_OBJECT_TYPES , class FAR_VISIBLE_OBJECT_TYPES > template<class SPECIFIC_OBJECT > void MapGrid< GRID_OBJECT_TYPES, FAR_VISIBLE_OBJECT_TYPES >::RemoveFarVisibleObject (uint16 const x, uint16 const y, SPECIFIC_OBJECT * obj) inline
    {
        GetOrCreateCell(x, y).RemoveFarVisibleObject(obj);
    }
References MapGrid< GRID_OBJECT_TYPES, FAR_VISIBLE_OBJECT_TYPES >::GetOrCreateCell(), and GridCell< GRID_OBJECT_TYPES, FAR_VISIBLE_OBJECT_TYPES >::RemoveFarVisibleObject().
Referenced by Map::RemoveWorldObjectFromFarVisibleMap().
RemoveGridObject()
template<class GRID_OBJECT_TYPES , class FAR_VISIBLE_OBJECT_TYPES > template<class SPECIFIC_OBJECT > void MapGrid< GRID_OBJECT_TYPES, FAR_VISIBLE_OBJECT_TYPES >::RemoveGridObject (uint16 const x, uint16 const y, SPECIFIC_OBJECT * obj) inline
    {
        GetOrCreateCell(x, y).RemoveGridObject(obj);
    }
References MapGrid< GRID_OBJECT_TYPES, FAR_VISIBLE_OBJECT_TYPES >::GetOrCreateCell().
SetObjectDataLoaded()
template<class GRID_OBJECT_TYPES , class FAR_VISIBLE_OBJECT_TYPES > void MapGrid< GRID_OBJECT_TYPES, FAR_VISIBLE_OBJECT_TYPES >::SetObjectDataLoaded () inline
{ _objectDataLoaded = true; }
References MapGrid< GRID_OBJECT_TYPES, FAR_VISIBLE_OBJECT_TYPES >::_objectDataLoaded.
Referenced by MapGridManager::LoadGrid().
SetTerrainData()
template<class GRID_OBJECT_TYPES , class FAR_VISIBLE_OBJECT_TYPES > void MapGrid< GRID_OBJECT_TYPES, FAR_VISIBLE_OBJECT_TYPES >::SetTerrainData (std::shared_ptr< GridTerrainData > terrainData) inline
{ _terrainData = terrainData; }
References MapGrid< GRID_OBJECT_TYPES, FAR_VISIBLE_OBJECT_TYPES >::_terrainData.
Referenced by GridTerrainLoader::LoadMap().
VisitAllCells()
template<class GRID_OBJECT_TYPES , class FAR_VISIBLE_OBJECT_TYPES > template<class T , class TT > void MapGrid< GRID_OBJECT_TYPES, FAR_VISIBLE_OBJECT_TYPES >::VisitAllCells (TypeContainerVisitor< T, TT > & visitor) inline
    {
        for (auto& cellX : _cells)
        {
            for (auto& cellY : cellX)
            {
                if (!cellY)
                    continue;
                cellY->Visit(visitor);
            }
        }
    }
References MapGrid< GRID_OBJECT_TYPES, FAR_VISIBLE_OBJECT_TYPES >::_cells.
Referenced by MapGridManager::UnloadGrid().
VisitCell()
template<class GRID_OBJECT_TYPES , class FAR_VISIBLE_OBJECT_TYPES > template<class T , class TT > void MapGrid< GRID_OBJECT_TYPES, FAR_VISIBLE_OBJECT_TYPES >::VisitCell (uint16 const x, uint16 const y, TypeContainerVisitor< T, TT > & visitor) inline
    {
        GridCellType* gridCell = GetCell(x, y);
        if (!gridCell)
            return;
        gridCell->Visit(visitor);
    }
References MapGrid< GRID_OBJECT_TYPES, FAR_VISIBLE_OBJECT_TYPES >::GetCell(), and GridCell< GRID_OBJECT_TYPES, FAR_VISIBLE_OBJECT_TYPES >::Visit().
Referenced by Map::Visit().
Member Data Documentation
_cells
template<class GRID_OBJECT_TYPES , class FAR_VISIBLE_OBJECT_TYPES > std::array<std::array<std::unique_ptr<GridCellType>, MAX_NUMBER_OF_CELLS>, MAX_NUMBER_OF_CELLS> MapGrid< GRID_OBJECT_TYPES, FAR_VISIBLE_OBJECT_TYPES >::_cells private
Referenced by MapGrid< GRID_OBJECT_TYPES, FAR_VISIBLE_OBJECT_TYPES >::GetCell(), MapGrid< GRID_OBJECT_TYPES, FAR_VISIBLE_OBJECT_TYPES >::GetCell(), MapGrid< GRID_OBJECT_TYPES, FAR_VISIBLE_OBJECT_TYPES >::GetCreatedCellsCount(), MapGrid< GRID_OBJECT_TYPES, FAR_VISIBLE_OBJECT_TYPES >::GetOrCreateCell(), and MapGrid< GRID_OBJECT_TYPES, FAR_VISIBLE_OBJECT_TYPES >::VisitAllCells().
_gridReference
template<class GRID_OBJECT_TYPES , class FAR_VISIBLE_OBJECT_TYPES > GridReference<MapGrid<GRID_OBJECT_TYPES, FAR_VISIBLE_OBJECT_TYPES> > MapGrid< GRID_OBJECT_TYPES, FAR_VISIBLE_OBJECT_TYPES >::_gridReference private
Referenced by MapGrid< GRID_OBJECT_TYPES, FAR_VISIBLE_OBJECT_TYPES >::link().
_objectDataLoaded
template<class GRID_OBJECT_TYPES , class FAR_VISIBLE_OBJECT_TYPES > bool MapGrid< GRID_OBJECT_TYPES, FAR_VISIBLE_OBJECT_TYPES >::_objectDataLoaded private
Referenced by MapGrid< GRID_OBJECT_TYPES, FAR_VISIBLE_OBJECT_TYPES >::IsObjectDataLoaded(), and MapGrid< GRID_OBJECT_TYPES, FAR_VISIBLE_OBJECT_TYPES >::SetObjectDataLoaded().
_terrainData
template<class GRID_OBJECT_TYPES , class FAR_VISIBLE_OBJECT_TYPES > std::shared_ptr<GridTerrainData> MapGrid< GRID_OBJECT_TYPES, FAR_VISIBLE_OBJECT_TYPES >::_terrainData private
Referenced by MapGrid< GRID_OBJECT_TYPES, FAR_VISIBLE_OBJECT_TYPES >::GetTerrainData(), MapGrid< GRID_OBJECT_TYPES, FAR_VISIBLE_OBJECT_TYPES >::GetTerrainDataSharedPtr(), and MapGrid< GRID_OBJECT_TYPES, FAR_VISIBLE_OBJECT_TYPES >::SetTerrainData().
_x
template<class GRID_OBJECT_TYPES , class FAR_VISIBLE_OBJECT_TYPES > uint16 MapGrid< GRID_OBJECT_TYPES, FAR_VISIBLE_OBJECT_TYPES >::_x private
Referenced by MapGrid< GRID_OBJECT_TYPES, FAR_VISIBLE_OBJECT_TYPES >::GetId(), and MapGrid< GRID_OBJECT_TYPES, FAR_VISIBLE_OBJECT_TYPES >::GetX().
_y
template<class GRID_OBJECT_TYPES , class FAR_VISIBLE_OBJECT_TYPES > uint16 MapGrid< GRID_OBJECT_TYPES, FAR_VISIBLE_OBJECT_TYPES >::_y private
Referenced by MapGrid< GRID_OBJECT_TYPES, FAR_VISIBLE_OBJECT_TYPES >::GetId(), and MapGrid< GRID_OBJECT_TYPES, FAR_VISIBLE_OBJECT_TYPES >::GetY().
The documentation for this class was generated from the following file:
azerothcore-wotlk/src/server/game/Grids/MapGrid.h