AzerothCore Doxygen
ElunaGlobal Class Reference
#include "ElunaTemplate.h"
Static Public Member Functions
static int thunk (lua_State *L)
static void SetMethods (Eluna *E, luaL_Reg *methodTable)
Detailed Description
Member Function Documentation
SetMethods()
static void ElunaGlobal::SetMethods (Eluna * E, luaL_Reg * methodTable) inline static
    {
        ASSERT(E);
        ASSERT(methodTable);
        lua_pushglobaltable(E->L);
        for (; methodTable && methodTable->name && methodTable->func; ++methodTable)
        {
            lua_pushstring(E->L, methodTable->name);
            lua_pushlightuserdata(E->L, (void*)methodTable);
            lua_pushcclosure(E->L, thunk, 1);
            lua_rawset(E->L, -3);
        }
        lua_remove(E->L, -1);
    }
References ASSERT, luaL_Reg::func, Eluna::L, lua_pushcclosure(), lua_pushglobaltable, lua_pushlightuserdata(), lua_pushstring(), lua_rawset(), lua_remove(), luaL_Reg::name, and thunk().
Referenced by RegisterFunctions().
thunk()
static int ElunaGlobal::thunk (lua_State * L) inline static
    {
        luaL_Reg* l = static_cast<luaL_Reg*>(lua_touserdata(L, lua_upvalueindex(1)));
        int top = lua_gettop(L);
        int expected = l->func(L);
        int args = lua_gettop(L) - top;
        if (args < 0 || args > expected)
        {
            ELUNA_LOG_ERROR("[Eluna]: {} returned unexpected amount of arguments {} out of {}. Report to devs", l->name, args, expected);
            ASSERT(false);
        }
        lua_settop(L, top + expected);
        return expected;
    }
References ASSERT, ELUNA_LOG_ERROR, luaL_Reg::func, lua_gettop(), lua_settop(), lua_touserdata(), lua_upvalueindex, and luaL_Reg::name.
Referenced by SetMethods().
The documentation for this class was generated from the following file:
mod-eluna/src/LuaEngine/ElunaTemplate.h