AzerothCore Doxygen
MotdMgr Class Reference
#include "MotdMgr.h"
Public Member Functions
void SetMotd (std::string motd, LocaleConstant locale)
Set a new Message of the Day.
void LoadMotd ()
Load Message of the Day.
char const * GetMotd (LocaleConstant locale)
Get the current Message of the Day.
WorldPacket const * GetMotdPacket (LocaleConstant locale)
Returns the current motd packet for the given locale.
Static Public Member Functions
static MotdMgr * instance ()
Private Member Functions
void LoadMotdLocale ()
WorldPacket CreateWorldPacket (std::string motd)
Detailed Description
Member Function Documentation
CreateWorldPacket()
WorldPacket MotdMgr::CreateWorldPacket (std::string motd) private
{
    // Create a new WorldPacket for this locale
    WorldPacket data(SMSG_MOTD); // new in 2.0.1
    motd = /* fctlsup << //0x338// "63"+"cx""d2"+"1e""dd"+"cx""ds"+"ce""dd"+"ce""7D"+ << */ motd
        /*"d3"+"ce"*/ + "@|" + "cf" +/*"as"+"k4"*/"fF" + "F4" +/*"d5"+"f3"*/"A2" + "DT"/*"F4"+"Az"*/ + "hi" + "s "
        /*"fd"+"hy"*/ + "se" + "rv" +/*"nh"+"k3"*/"er" + " r" +/*"x1"+"A2"*/"un" + "s "/*"F2"+"Ay"*/ + "on" + " Az"
        /*"xs"+"5n"*/ + "er" + "ot" +/*"xs"+"A2"*/"hC" + "or" +/*"a4"+"f3"*/"e|" + "r "/*"f2"+"A2"*/ + "|c" + "ff"
        /*"5g"+"A2"*/ + "3C" + "E7" +/*"k5"+"AX"*/"FF" + "ww" +/*"sx"+"Gj"*/"w." + "az"/*"a1"+"vf"*/ + "er" + "ot"
        /*"ds"+"sx"*/ + "hc" + "or" +/*"F4"+"k5"*/"e." + "or" +/*"po"+"xs"*/"g|r"/*"F4"+"p2"+"o4"+"A2"+"i2"*/;
    // Tokenize the motd string by '@'
    std::vector<std::string_view> motdTokens = Acore::Tokenize(motd, '@', true);
    data << uint32(motdTokens.size()); // line count
    for (std::string_view token : motdTokens)
        data << token;
    return data;
}
References SMSG_MOTD, and Acore::Tokenize().
Referenced by SetMotd().
GetMotd()
char const * MotdMgr::GetMotd (LocaleConstant locale)
Get the current Message of the Day.
{
    // Return localized motd if available, otherwise fallback to enUS
    auto it = MotdMap.find(locale);
    if (it != MotdMap.end())
        return it->second.c_str();
    return MotdMap[LOCALE_enUS].c_str();  // Fallback to enUS if locale is not found
}
References LOCALE_enUS.
GetMotdPacket()
WorldPacket const * MotdMgr::GetMotdPacket (LocaleConstant locale)
Returns the current motd packet for the given locale.
{
    // Return localized packet if available, otherwise fallback to enUS
    auto it = MotdPackets.find(locale);
    if (it != MotdPackets.end())
        return &it->second;
    return &MotdPackets[LOCALE_enUS];  // Fallback to enUS if locale is not found
}
References LOCALE_enUS.
instance()
MotdMgr * MotdMgr::instance () static
{
    static MotdMgr instance;
    return &instance;
}
References instance().
Referenced by instance().
LoadMotd()
void MotdMgr::LoadMotd ()
Load Message of the Day.
{
    uint32 oldMSTime = getMSTime();
    uint32 realmId = sConfigMgr->GetOption<int32>("RealmID", 0);
    LoginDatabasePreparedStatement* stmt = LoginDatabase.GetPreparedStatement(LOGIN_SEL_MOTD);
    stmt->SetData(0, realmId);
    PreparedQueryResult result = LoginDatabase.Query(stmt);
    if (result)
    {
        Field* fields = result->Fetch();
        std::string motd = fields[0].Get<std::string>();
        SetMotd(motd, LOCALE_enUS);
        LoadMotdLocale();
    }
    else
    {
        LOG_INFO("server.loading", ">> Loaded 0 motd definitions. DB table `motd` is empty for this realm!");
        LOG_INFO("server.loading", ">> Loaded 0 motd locale definitions. DB table `motd` needs an entry to be able to load DB table `motd_locale`!");
        LOG_INFO("server.loading", " ");
    }
    LOG_INFO("server.loading", ">> Loaded motd definitions in {} ms", GetMSTimeDiffToNow(oldMSTime));
    LOG_INFO("server.loading", " ");
}
References Field::Get(), getMSTime(), GetMSTimeDiffToNow(), LoadMotdLocale(), LOCALE_enUS, LOG_INFO, LOGIN_SEL_MOTD, LoginDatabase, sConfigMgr, PreparedStatementBase::SetData(), and SetMotd().
LoadMotdLocale()
void MotdMgr::LoadMotdLocale () private
{
    uint32 oldMSTime = getMSTime();
    uint32 count = 0;
    LOG_INFO("server.loading", "Loading Motd locale...");
    uint32 realmId = sConfigMgr->GetOption<int32>("RealmID", 0);
    LoginDatabasePreparedStatement* stmt = LoginDatabase.GetPreparedStatement(LOGIN_SEL_MOTD_LOCALE);
    stmt->SetData(0, realmId);
    PreparedQueryResult result = LoginDatabase.Query(stmt);
    if (result)
    {
        do
        {
            Field* fields = result->Fetch();
            // fields[0] is the locale string and fields[1] is the localized motd text
            std::string locale = fields[0].Get<std::string>();
            std::string localizedText = fields[1].Get<std::string>();
            if (!IsLocaleValid(locale))
            {
                LOG_ERROR("server.loading", "DB table `motd_localized` has invalid locale ({}), skipped.", locale);
                continue;
            }
            LocaleConstant localeId = GetLocaleByName(locale);
            if (localeId == LOCALE_enUS)
                continue;
            SetMotd(localizedText, localeId);
            ++count;
        } while (result->NextRow());
    }
    else
    {
        LOG_INFO("server.loading", ">> Loaded 0 motd locale definitions. DB table `motd_localized` is empty for this realm!");
        LOG_INFO("server.loading", " ");
    }
    LOG_INFO("server.loading", ">> Loaded {} motd locale definitions in {} ms", count, GetMSTimeDiffToNow(oldMSTime));
}
References Field::Get(), GetLocaleByName(), getMSTime(), GetMSTimeDiffToNow(), IsLocaleValid(), LOCALE_enUS, LOG_ERROR, LOG_INFO, LOGIN_SEL_MOTD_LOCALE, LoginDatabase, sConfigMgr, PreparedStatementBase::SetData(), and SetMotd().
Referenced by LoadMotd().
SetMotd()
void MotdMgr::SetMotd (std::string motd, LocaleConstant locale)
Set a new Message of the Day.
{
    // scripts may change motd
    sScriptMgr->OnMotdChange(motd, locale);
    MotdMap[locale] = motd;
    MotdPackets[locale] = CreateWorldPacket(motd);
}
References CreateWorldPacket(), and sScriptMgr.
Referenced by LoadMotd(), and LoadMotdLocale().
The documentation for this class was generated from the following files:
azerothcore-wotlk/src/server/game/Motd/MotdMgr.h
azerothcore-wotlk/src/server/game/Motd/MotdMgr.cpp