AzerothCore Doxygen
TaskScheduler::TaskQueue Class Reference
Public Member Functions
void Push (TaskContainer &&task)
TaskContainer Pop ()
Pops the task out of the container.
TaskContainer const & First () const
void Clear ()
void RemoveIf (std::function< bool(TaskContainer const &)> const &filter)
void ModifyIf (std::function< bool(TaskContainer const &)> const &filter)
bool IsGroupQueued (group_t const group)
Check if the group exists and is currently scheduled.
TaskScheduler::timepoint_t GetNextGroupOccurrence (group_t const group) const
bool IsEmpty () const
Private Attributes
std::multiset< TaskContainer, Compare > container
Detailed Description
Member Function Documentation
Clear()
void TaskScheduler::TaskQueue::Clear ()
{
    container.clear();
}
Referenced by TaskScheduler::CancelAll().
First()
auto TaskScheduler::TaskQueue::First () const
{
    return *container.begin();
}
Referenced by TaskScheduler::Dispatch().
GetNextGroupOccurrence()
TaskScheduler::timepoint_t TaskScheduler::TaskQueue::GetNextGroupOccurrence (group_t const group) const
{
    TaskScheduler::timepoint_t next = TaskScheduler::timepoint_t::max();
    for (auto const& task : container)
        if (task->IsInGroup(group) && task->_end < next)
            next = task->_end;
    return next;
}
Referenced by TaskScheduler::GetNextGroupOccurrence().
IsEmpty()
bool TaskScheduler::TaskQueue::IsEmpty () const
{
    return container.empty();
}
Referenced by TaskScheduler::Dispatch().
IsGroupQueued()
bool TaskScheduler::TaskQueue::IsGroupQueued (group_t const group)
Check if the group exists and is currently scheduled.
{
    for (auto const& task : container)
    {
        if (task->IsInGroup(group))
        {
            return true;
        }
    }
    return false;
}
Referenced by TaskScheduler::IsGroupScheduled().
ModifyIf()
void TaskScheduler::TaskQueue::ModifyIf (std::function< bool(TaskContainer const &)> const & filter)
{
    std::vector<TaskContainer> cache;
    for (auto itr = container.begin(); itr != container.end();)
        if (filter(*itr))
        {
            cache.push_back(*itr);
            itr = container.erase(itr);
        }
        else
        {
            ++itr;
        }
    container.insert(cache.begin(), cache.end());
}
Referenced by TaskScheduler::DelayAll(), TaskScheduler::DelayGroup(), TaskScheduler::RescheduleAll(), and TaskScheduler::RescheduleGroup().
Pop()
auto TaskScheduler::TaskQueue::Pop ()
Pops the task out of the container.
{
    TaskContainer result = *container.begin();
    container.erase(container.begin());
    return result;
}
Referenced by TaskScheduler::Dispatch().
Push()
void TaskScheduler::TaskQueue::Push (TaskContainer && task)
{
    container.insert(task);
}
References container.
Referenced by TaskScheduler::InsertTask().
RemoveIf()
void TaskScheduler::TaskQueue::RemoveIf (std::function< bool(TaskContainer const &)> const & filter)
{
    for (auto itr = container.begin(); itr != container.end();)
        if (filter(*itr))
        {
            itr = container.erase(itr);
        }
        else
        {
            ++itr;
        }
}
Referenced by TaskScheduler::CancelGroup().
Member Data Documentation
container
std::multiset<TaskContainer, Compare> TaskScheduler::TaskQueue::container private
Referenced by Push().
The documentation for this class was generated from the following files:
azerothcore-wotlk/src/common/Utilities/TaskScheduler.h
azerothcore-wotlk/src/common/Utilities/TaskScheduler.cpp