AzerothCore Doxygen
npcs_riverbreeze_and_silversky Class Reference
Public Member Functions
npcs_riverbreeze_and_silversky ()
bool OnGossipSelect (Player *player, Creature *creature, uint32, uint32 action) override
bool OnGossipHello (Player *player, Creature *creature) override
Public Member Functions inherited from CreatureScript
bool IsDatabaseBound () const override
virtual bool OnGossipSelectCode (Player *, Creature *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, Creature *, Quest const *)
virtual bool OnQuestSelect (Player *, Creature *, Quest const *)
virtual bool OnQuestComplete (Player *, Creature *, Quest const *)
virtual bool OnQuestReward (Player *, Creature *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, Creature *)
virtual CreatureAI * GetAI (Creature *) const
virtual void OnFfaPvpStateUpdate (Creature *, bool)
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
uint16 GetTotalAvailableHooks ()
Public Member Functions inherited from UpdatableScript< Creature >
virtual void OnUpdate (Creature *, uint32)
Additional Inherited Members
Protected Member Functions inherited from CreatureScript
CreatureScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name, uint16 totalAvailableHooks=0)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< Creature >
UpdatableScript ()=default
Detailed Description
Constructor & Destructor Documentation
npcs_riverbreeze_and_silversky()
npcs_riverbreeze_and_silversky::npcs_riverbreeze_and_silversky () inline
: CreatureScript("npcs_riverbreeze_and_silversky") { }
Member Function Documentation
OnGossipHello()
bool npcs_riverbreeze_and_silversky::OnGossipHello (Player * player, Creature * creature) inline override virtual
Reimplemented from CreatureScript.
    {
        if (creature->IsQuestGiver())
            player->PrepareQuestMenu(creature->GetGUID());
        uint32 const creatureId = creature->GetEntry();
        if (creatureId == NPC_ARATHANDRIS_SILVERSKY)
        {
            if (player->GetQuestRewardStatus(QUEST_CLEASING_FELWOOD_A))
            {
                if (!player->HasItemCount(ITEM_CENARION_BEACON, 1, true))
                   AddGossipItemFor(player, GOSSIP_MENU_SILVERSKY, GOSSIP_OPTION_BEACON, GOSSIP_SENDER_MAIN, ACTION_CREATE_CENARION_BEACON);
                SendGossipMenuFor(player, TEXT_SILVERSKY_1, creature->GetGUID());
            }
            else if (player->GetTeamId() == TEAM_HORDE)
                SendGossipMenuFor(player, TEXT_SILVERSKY_2, creature->GetGUID());
            else
                SendGossipMenuFor(player, TEXT_SILVERSKY_3, creature->GetGUID());
        }
        if (creatureId == NPC_MAYBESS_RIVERBREEZE)
        {
            if (player->GetQuestRewardStatus(QUEST_CLEASING_FELWOOD_H))
            {
                if (!player->HasItemCount(ITEM_CENARION_BEACON, 1, true))
                    AddGossipItemFor(player, GOSSIP_MENU_RIVERBREEZE, GOSSIP_OPTION_BEACON, GOSSIP_SENDER_MAIN, ACTION_CREATE_CENARION_BEACON);
                SendGossipMenuFor(player, TEXT_RIVERBREEZE_1, creature->GetGUID());
            }
            else if (player->GetTeamId() == TEAM_ALLIANCE)
                SendGossipMenuFor(player, TEXT_RIVERBREEZE_2, creature->GetGUID());
            else
                SendGossipMenuFor(player, TEXT_RIVERBREEZE_3, creature->GetGUID());
        }
        return true;
    }
References ACTION_CREATE_CENARION_BEACON, AddGossipItemFor(), Object::GetEntry(), Object::GetGUID(), Player::GetQuestRewardStatus(), Player::GetTeamId(), GOSSIP_MENU_RIVERBREEZE, GOSSIP_MENU_SILVERSKY, GOSSIP_OPTION_BEACON, GOSSIP_SENDER_MAIN, Player::HasItemCount(), Unit::IsQuestGiver(), ITEM_CENARION_BEACON, NPC_ARATHANDRIS_SILVERSKY, NPC_MAYBESS_RIVERBREEZE, Player::PrepareQuestMenu(), QUEST_CLEASING_FELWOOD_A, QUEST_CLEASING_FELWOOD_H, SendGossipMenuFor(), TEAM_ALLIANCE, TEAM_HORDE, TEXT_RIVERBREEZE_1, TEXT_RIVERBREEZE_2, TEXT_RIVERBREEZE_3, TEXT_SILVERSKY_1, TEXT_SILVERSKY_2, and TEXT_SILVERSKY_3.
OnGossipSelect()
bool npcs_riverbreeze_and_silversky::OnGossipSelect (Player * player, Creature * creature, uint32 , uint32 action) inline override virtual
Reimplemented from CreatureScript.
    {
        ClearGossipMenuFor(player);
        if (action == GOSSIP_ACTION_INFO_DEF + 1)
        {
            CloseGossipMenuFor(player);
            creature->CastSpell(player, SPELL_CENARION_BEACON, false);
        }
        return true;
    }
References Unit::CastSpell(), ClearGossipMenuFor(), CloseGossipMenuFor(), GOSSIP_ACTION_INFO_DEF, and SPELL_CENARION_BEACON.
The documentation for this class was generated from the following file:
azerothcore-wotlk/src/server/scripts/Kalimdor/zone_felwood.cpp