AzerothCore Doxygen
LuaObject Namespace Reference
Functions
int HasFlag (lua_State *L, Object *obj)
int IsInWorld (lua_State *L, Object *obj)
int IsPlayer (lua_State *L, Object *obj)
int GetInt32Value (lua_State *L, Object *obj)
int GetUInt32Value (lua_State *L, Object *obj)
int GetFloatValue (lua_State *L, Object *obj)
int GetByteValue (lua_State *L, Object *obj)
int GetUInt16Value (lua_State *L, Object *obj)
int GetScale (lua_State *L, Object *obj)
int GetEntry (lua_State *L, Object *obj)
int GetGUID (lua_State *L, Object *obj)
int GetGUIDLow (lua_State *L, Object *obj)
int GetTypeId (lua_State *L, Object *obj)
int GetUInt64Value (lua_State *L, Object *obj)
int SetFlag (lua_State *L, Object *obj)
int SetInt32Value (lua_State *L, Object *obj)
int SetUInt32Value (lua_State *L, Object *obj)
int UpdateUInt32Value (lua_State *L, Object *obj)
int SetFloatValue (lua_State *L, Object *obj)
int SetByteValue (lua_State *L, Object *obj)
int SetUInt16Value (lua_State *L, Object *obj)
int SetInt16Value (lua_State *L, Object *obj)
int SetScale (lua_State *L, Object *obj)
int SetUInt64Value (lua_State *L, Object *obj)
int RemoveFlag (lua_State *L, Object *obj)
int ToCorpse (lua_State *L, Object *obj)
int ToGameObject (lua_State *L, Object *obj)
int ToUnit (lua_State *L, Object *obj)
int ToCreature (lua_State *L, Object *obj)
int ToPlayer (lua_State *L, Object *obj)
Function Documentation
GetByteValue()
int LuaObject::GetByteValue (lua_State * L, Object * obj)
Returns the data at the specified index and offset, casted to an unsigned 8-bit integer.
E.g. if you want the second byte at index 10, you would pass in 1 as the offset.
Parameters
uint16 index
uint8 offset : should be 0, 1, 2, or 3
Returns
uint8 value
    {
        uint16 index = Eluna::CHECKVAL<uint16>(L, 2);
        uint8 offset = Eluna::CHECKVAL<uint8>(L, 3);
        Eluna::Push(L, obj->GetByteValue(index, offset));
        return 1;
    }
References Object::GetByteValue(), and Eluna::Push().
GetEntry()
int LuaObject::GetEntry (lua_State * L, Object * obj)
Returns the entry of the [Object].
[Player]s do not have an "entry".
Returns
uint32 entry
    {
        Eluna::Push(L, obj->GetEntry());
        return 1;
    }
References Object::GetEntry(), and Eluna::Push().
GetFloatValue()
int LuaObject::GetFloatValue (lua_State * L, Object * obj)
Returns the data at the specified index, casted to a single-precision floating point value.
Parameters
uint16 index
Returns
float value
    {
        uint16 index = Eluna::CHECKVAL<uint16>(L, 2);
        Eluna::Push(L, obj->GetFloatValue(index));
        return 1;
    }
References Object::GetFloatValue(), and Eluna::Push().
GetGUID()
int LuaObject::GetGUID (lua_State * L, Object * obj)
Returns the GUID of the [Object].
GUID is an unique identifier for the object.
However on MaNGOS and cMangos creatures and gameobjects inside different maps can share the same GUID but not on the same map.
On TrinityCore this value is unique across all maps
Returns
ObjectGuid guid
    {
        Eluna::Push(L, obj->GET_GUID());
        return 1;
    }
References Eluna::Push().
GetGUIDLow()
int LuaObject::GetGUIDLow (lua_State * L, Object * obj)
Returns the low-part of the [Object]'s GUID.
On TrinityCore all low GUIDs are different for all objects of the same type. For example creatures in instances are assigned new GUIDs when the Map is created.
On MaNGOS and cMaNGOS low GUIDs are unique only on the same map. For example creatures in instances use the same low GUID assigned for that spawn in the database. This is why to identify a creature you have to know the instanceId and low GUID. See [Map:GetIntstanceId]
Returns
uint32 guidLow
    {
#if defined TRINITY || AZEROTHCORE
        Eluna::Push(L, obj->GetGUID().GetCounter());
#else
        Eluna::Push(L, obj->GetGUIDLow());
#endif
        return 1;
    }
References ObjectGuid::GetCounter(), Object::GetGUID(), and Eluna::Push().
GetInt32Value()
int LuaObject::GetInt32Value (lua_State * L, Object * obj)
Returns the data at the specified index, casted to a signed 32-bit integer.
Parameters
uint16 index
Returns
int32 value
    {
        uint16 index = Eluna::CHECKVAL<uint16>(L, 2);
        Eluna::Push(L, obj->GetInt32Value(index));
        return 1;
    }
References Object::GetInt32Value(), and Eluna::Push().
GetScale()
int LuaObject::GetScale (lua_State * L, Object * obj)
Returns the scale/size of the [Object].
This affects the size of a [WorldObject] in-game, but [Item]s don't have a "scale".
Returns
float scale
    {
#ifndef AZEROTHCORE
        Eluna::Push(L, obj->GetObjectScale());
#else
        Eluna::Push(L, obj->GetFloatValue(OBJECT_FIELD_SCALE_X));
#endif
        return 1;
    }
References Object::GetFloatValue(), Object::GetObjectScale(), OBJECT_FIELD_SCALE_X, and Eluna::Push().
GetTypeId()
int LuaObject::GetTypeId (lua_State * L, Object * obj)
Returns the TypeId of the [Object].
enum TypeID
{
    TYPEID_OBJECT        = 0,
    TYPEID_ITEM          = 1,
    TYPEID_CONTAINER     = 2,
    TYPEID_UNIT          = 3,
    TYPEID_PLAYER        = 4,
    TYPEID_GAMEOBJECT    = 5,
    TYPEID_DYNAMICOBJECT = 6,
    TYPEID_CORPSE        = 7
};
Returns
uint8 typeID
    {
        Eluna::Push(L, obj->GetTypeId());
        return 1;
    }
References Object::GetTypeId(), and Eluna::Push().
GetUInt16Value()
int LuaObject::GetUInt16Value (lua_State * L, Object * obj)
Returns the data at the specified index and offset, casted to a signed 16-bit integer.
E.g. if you want the second half-word at index 10, you would pass in 1 as the offset.
Parameters
uint16 index
uint8 offset : should be 0 or 1
Returns
uint16 value
    {
        uint16 index = Eluna::CHECKVAL<uint16>(L, 2);
        uint8 offset = Eluna::CHECKVAL<uint8>(L, 3);
        Eluna::Push(L, obj->GetUInt16Value(index, offset));
        return 1;
    }
References Object::GetUInt16Value(), and Eluna::Push().
GetUInt32Value()
int LuaObject::GetUInt32Value (lua_State * L, Object * obj)
Returns the data at the specified index, casted to a unsigned 32-bit integer.
Parameters
uint16 index
Returns
uint32 value
    {
        uint16 index = Eluna::CHECKVAL<uint16>(L, 2);
        Eluna::Push(L, obj->GetUInt32Value(index));
        return 1;
    }
References Object::GetUInt32Value(), and Eluna::Push().
GetUInt64Value()
int LuaObject::GetUInt64Value (lua_State * L, Object * obj)
Returns the data at the specified index, casted to an unsigned 64-bit integer.
Parameters
uint16 index
Returns
uint64 value
    {
        uint16 index = Eluna::CHECKVAL<uint16>(L, 2);
        Eluna::Push(L, obj->GetUInt64Value(index));
        return 1;
    }
References Object::GetUInt64Value(), and Eluna::Push().
HasFlag()
int LuaObject::HasFlag (lua_State * L, Object * obj)
Returns true if the specified flag is set, otherwise false.
Parameters
uint16 index : the index of the flags data in the [Object]
uint32 flag : the flag to check for in the flags data
Returns
bool hasFlag
    {
        uint16 index = Eluna::CHECKVAL<uint16>(L, 2);
        uint32 flag = Eluna::CHECKVAL<uint32>(L, 3);
        Eluna::Push(L, obj->HasFlag(index, flag));
        return 1;
    }
References Object::HasFlag(), and Eluna::Push().
IsInWorld()
int LuaObject::IsInWorld (lua_State * L, Object * obj)
Returns true if the [Object] has been added to its [Map], otherwise false.
Returns
bool inWorld
    {
        Eluna::Push(L, obj->IsInWorld());
        return 1;
    }
References Object::IsInWorld(), and Eluna::Push().
IsPlayer()
int LuaObject::IsPlayer (lua_State * L, Object * obj)
Returns 'true' if the [Object] is a player, 'false' otherwise.
Returns
bool IsPlayer
    {
#ifdef AZEROTHCORE //AC-only
        Eluna::Push(L, obj->IsPlayer());
#endif
        return 1;
    }
References Object::IsPlayer(), and Eluna::Push().
RemoveFlag()
int LuaObject::RemoveFlag (lua_State * L, Object * obj)
Removes a flag from the value at the specified index.
Parameters
uint16 index
uint32 flag
    {
        uint16 index = Eluna::CHECKVAL<uint16>(L, 2);
        uint32 flag = Eluna::CHECKVAL<uint32>(L, 3);
        obj->RemoveFlag(index, flag);
        return 0;
    }
References Object::RemoveFlag().
SetByteValue()
int LuaObject::SetByteValue (lua_State * L, Object * obj)
Sets the data at the specified index and offset to the given value, converted to an unsigned 8-bit integer.
Parameters
uint16 index
uint8 offset : should be 0, 1, 2, or 3
uint8 value
    {
        uint16 index = Eluna::CHECKVAL<uint16>(L, 2);
        uint8 offset = Eluna::CHECKVAL<uint8>(L, 3);
        uint8 value = Eluna::CHECKVAL<uint8>(L, 4);
        obj->SetByteValue(index, offset, value);
        return 0;
    }
References Object::SetByteValue().
SetFlag()
int LuaObject::SetFlag (lua_State * L, Object * obj)
Sets the specified flag in the data value at the specified index.
If the flag was already set, it remains set.
To remove a flag, use [Object:RemoveFlag].
Parameters
uint16 index
uint32 value
    {
        uint16 index = Eluna::CHECKVAL<uint16>(L, 2);
        uint32 flag = Eluna::CHECKVAL<uint32>(L, 3);
        obj->SetFlag(index, flag);
        return 0;
    }
References Object::SetFlag().
SetFloatValue()
int LuaObject::SetFloatValue (lua_State * L, Object * obj)
Sets the data at the specified index to the given value, converted to a single-precision floating point value.
Parameters
uint16 index
float value
    {
        uint16 index = Eluna::CHECKVAL<uint16>(L, 2);
        float value = Eluna::CHECKVAL<float>(L, 3);
        obj->SetFloatValue(index, value);
        return 0;
    }
References Object::SetFloatValue().
SetInt16Value()
int LuaObject::SetInt16Value (lua_State * L, Object * obj)
Sets the data at the specified index to the given value, converted to a signed 16-bit integer.
Parameters
uint16 index
uint8 offset : should be 0 or 1
int16 value
    {
        uint16 index = Eluna::CHECKVAL<uint16>(L, 2);
        uint8 offset = Eluna::CHECKVAL<uint8>(L, 3);
        int16 value = Eluna::CHECKVAL<int16>(L, 4);
        obj->SetInt16Value(index, offset, value);
        return 0;
    }
References Object::SetInt16Value().
SetInt32Value()
int LuaObject::SetInt32Value (lua_State * L, Object * obj)
Sets the data at the specified index to the given value, converted to a signed 32-bit integer.
Parameters
uint16 index
int32 value
    {
        uint16 index = Eluna::CHECKVAL<uint16>(L, 2);
        int32 value = Eluna::CHECKVAL<int32>(L, 3);
        obj->SetInt32Value(index, value);
        return 0;
    }
References Object::SetInt32Value().
SetScale()
int LuaObject::SetScale (lua_State * L, Object * obj)
Sets the [Object]'s scale/size to the given value.
Parameters
float scale
    {
        float size = Eluna::CHECKVAL<float>(L, 2);
        obj->SetObjectScale(size);
        return 0;
    }
References Object::SetObjectScale().
SetUInt16Value()
int LuaObject::SetUInt16Value (lua_State * L, Object * obj)
Sets the data at the specified index to the given value, converted to an unsigned 16-bit integer.
Parameters
uint16 index
uint8 offset : should be 0 or 1
uint16 value
    {
        uint16 index = Eluna::CHECKVAL<uint16>(L, 2);
        uint8 offset = Eluna::CHECKVAL<uint8>(L, 3);
        uint16 value = Eluna::CHECKVAL<uint16>(L, 4);
        obj->SetUInt16Value(index, offset, value);
        return 0;
    }
References Object::SetUInt16Value().
SetUInt32Value()
int LuaObject::SetUInt32Value (lua_State * L, Object * obj)
Sets the data at the specified index to the given value, converted to an unsigned 32-bit integer.
Parameters
uint16 index
uint32 value
    {
        uint16 index = Eluna::CHECKVAL<uint16>(L, 2);
        uint32 value = Eluna::CHECKVAL<uint32>(L, 3);
        obj->SetUInt32Value(index, value);
        return 0;
    }
References Object::SetUInt32Value().
SetUInt64Value()
int LuaObject::SetUInt64Value (lua_State * L, Object * obj)
Sets the data at the specified index to the given value, converted to an unsigned 64-bit integer.
Parameters
uint16 index
uint64 value
    {
        uint16 index = Eluna::CHECKVAL<uint16>(L, 2);
        uint64 value = Eluna::CHECKVAL<uint64>(L, 3);
        obj->SetUInt64Value(index, value);
        return 0;
    }
References Object::SetUInt64Value().
ToCorpse()
int LuaObject::ToCorpse (lua_State * L, Object * obj)
Attempts to convert the [Object] to a [Corpse].
If the [Object] is not a [Corpse], returns nil.
Returns
[Corpse] corpse : the [Object] as a [Corpse], or nil
    {
        Eluna::Push(L, obj->ToCorpse());
        return 1;
    }
References Eluna::Push(), and Object::ToCorpse().
ToCreature()
int LuaObject::ToCreature (lua_State * L, Object * obj)
Attempts to convert the [Object] to a [Creature].
If the [Object] is not a [Creature], returns nil.
Returns
[Creature] creature : the [Object] as a [Creature], or nil
    {
        Eluna::Push(L, obj->ToCreature());
        return 1;
    }
References Eluna::Push(), and Object::ToCreature().
ToGameObject()
int LuaObject::ToGameObject (lua_State * L, Object * obj)
Attempts to convert the [Object] to a [GameObject].
If the [Object] is not a [GameObject], returns nil.
Returns
[GameObject] gameObject : the [Object] as a [GameObject], or nil
    {
        Eluna::Push(L, obj->ToGameObject());
        return 1;
    }
References Eluna::Push(), and Object::ToGameObject().
ToPlayer()
int LuaObject::ToPlayer (lua_State * L, Object * obj)
Attempts to convert the [Object] to a [Player].
If the [Object] is not a [Player], returns nil.
Returns
[Player] player : the [Object] as a [Player], or nil
    {
        Eluna::Push(L, obj->ToPlayer());
        return 1;
    }
References Eluna::Push(), and Object::ToPlayer().
ToUnit()
int LuaObject::ToUnit (lua_State * L, Object * obj)
Attempts to convert the [Object] to a [Unit].
If the [Object] is not a [Unit], returns nil.
Returns
[Unit] unit : the [Object] as a [Unit], or nil
    {
        Eluna::Push(L, obj->ToUnit());
        return 1;
    }
References Eluna::Push(), and Object::ToUnit().
UpdateUInt32Value()
int LuaObject::UpdateUInt32Value (lua_State * L, Object * obj)
Sets the data at the specified index to the given value, converted to an unsigned 32-bit integer.
Parameters
uint16 index
uint32 value
    {
        uint16 index = Eluna::CHECKVAL<uint16>(L, 2);
        uint32 value = Eluna::CHECKVAL<uint32>(L, 3);
        obj->UpdateUInt32Value(index, value);
        return 0;
    }
References Object::UpdateUInt32Value().