AzerothCore Doxygen
npc_overlord_drakuru_betrayal Struct Reference
Public Member Functions
npc_overlord_drakuru_betrayal (Creature *creature)
void EnterEvadeMode (EvadeReason why) override
void Reset () override
void DoAction (int32 action) override
bool IsPlayerOnQuest (Player *player)
void MoveInLineOfSight (Unit *who) override
void JustSummoned (Creature *summon) override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void DamageTaken (Unit *, uint32 &damage, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void SpellHitTarget (Unit *target, SpellInfo const *spellInfo) override
void SpellHit (Unit *, SpellInfo const *spellInfo) override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportPlayer (Unit *unit, Position pos)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool IsUniqueTimedEventDone (uint32 id) const
void SetUniqueTimedEventDone (uint32 id)
void ResetUniqueTimedEvent (uint32 id)
void ClearUniqueTimedEventsDone ()
void ScheduleTimedEvent (Milliseconds timerMin, Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0ms, uint32 uniqueId=0)
void ScheduleTimedEvent (Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0ms, uint32 uniqueId=0)
void ScheduleUniqueTimedEvent (Milliseconds timer, std::function< void()> exec, uint32 uniqueId)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
void SetInvincibility (bool apply)
bool IsInvincible () const
void SetAutoAttackAllowed (bool allow)
bool IsAutoAttackAllowed () const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0ms)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void OnSpellCastFinished (SpellInfo const *, SpellFinishReason)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
int32 VisualizeBoundary (uint32 duration, Unit *owner=nullptr, bool fill=false, bool checkZ=false) const
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
virtual void DistancingStarted ()
virtual void DistancingEnded ()
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid const &, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage to any victim (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Private Attributes
SummonList _summons
ObjectGuid _playerGUID
ObjectGuid _lichGUID
BetrayalState _state
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from ScriptedAI
Creature * me
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
npc_overlord_drakuru_betrayal()
npc_overlord_drakuru_betrayal::npc_overlord_drakuru_betrayal (Creature * creature) inline
                                                      : ScriptedAI(creature), _summons(me), _state(BETRAYAL_NOT_STARTED)
    {
        me->SetControlled(true, UNIT_STATE_ROOT);
    }
References ScriptedAI::me, Unit::SetControlled(), and UNIT_STATE_ROOT.
Member Function Documentation
DamageTaken()
void npc_overlord_drakuru_betrayal::DamageTaken (Unit * , uint32 & , DamageEffectType , SpellSchoolMask) inline override virtual
Called at any Damage from any attacker (before damage apply)
Note
It use for recalculation damage or special reaction at damage for attack reaction use AttackedBy called for non DOT damage in Unit::DealDamage also
Reimplemented from UnitAI.
    {
        if (damage >= me->GetHealth() && !me->HasUnitFlag(UNIT_FLAG_NON_ATTACKABLE))
        {
            damage = 0;
            me->RemoveAllAuras();
            me->CombatStop();
            me->SetUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
            me->SetFaction(2082);
            me->SetImmuneToPC(true);
            events.Reset();
            scheduler.CancelAll();
            events.ScheduleEvent(EVENT_BETRAYAL_EPILOGUE_1, 4200ms);
            _state = BETRAYAL_EPILOGUE;
        }
    }
References _state, BETRAYAL_EPILOGUE, TaskScheduler::CancelAll(), Unit::CombatStop(), EVENT_BETRAYAL_EPILOGUE_1, Unit::GetHealth(), Unit::HasUnitFlag(), ScriptedAI::me, Unit::RemoveAllAuras(), CreatureAI::scheduler, Unit::SetFaction(), Unit::SetImmuneToPC(), Unit::SetUnitFlag(), and UNIT_FLAG_NON_ATTACKABLE.
DoAction()
void npc_overlord_drakuru_betrayal::DoAction (int32 action) inline override virtual
Reimplemented from UnitAI.
    {
        switch (action)
        {
            case ACTION_SUMMON_DRAKURU_LAST_WISH:
                if (!me->FindNearestGameObject(GO_DRAKURUS_LAST_WISH, 80.0f))
                    me->SummonGameObject(GO_DRAKURUS_LAST_WISH, 6185.989, -2029.6979, 590.87787, 0, 0, 0, 0, 0, 0, true, GO_SUMMON_TIMED_DESPAWN);
                break;
            case ACTION_DESTROY_DRAKURU_LAST_WISH:
                if (GameObject* go = me->FindNearestGameObject(GO_DRAKURUS_LAST_WISH, 80.0f))
                    go->Delete();
                break;
            case ACTION_REMOVE_SPOTLIGHTS:
            {
                std::list<Creature*> creatures;
                me->GetCreatureListWithEntryInGrid(creatures, NPC_TOTALLY_GENERIC_BUNNY, 55.0f);
                for (Creature* creature : creatures)
                    creature->RemoveAurasDueToSpell(SPELL_SCOURGE_SPOTLIGHT);
            }
        }
    }
References ACTION_DESTROY_DRAKURU_LAST_WISH, ACTION_REMOVE_SPOTLIGHTS, ACTION_SUMMON_DRAKURU_LAST_WISH, GameObject::Delete(), WorldObject::FindNearestGameObject(), WorldObject::GetCreatureListWithEntryInGrid(), GO_DRAKURUS_LAST_WISH, GO_SUMMON_TIMED_DESPAWN, ScriptedAI::me, NPC_TOTALLY_GENERIC_BUNNY, SPELL_SCOURGE_SPOTLIGHT, and WorldObject::SummonGameObject().
Referenced by MoveInLineOfSight(), Reset(), SpellHit(), and UpdateAI().
EnterEvadeMode()
void npc_overlord_drakuru_betrayal::EnterEvadeMode (EvadeReason why) inline override virtual
Reimplemented from CreatureAI.
    {
        if (_state != BETRAYAL_EVADE)
            return;
        me->SetFaction(FACTION_UNDEAD_SCOURGE);
        me->RemoveUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
        ScriptedAI::EnterEvadeMode(why);
    }
References _state, BETRAYAL_EVADE, CreatureAI::EnterEvadeMode(), FACTION_UNDEAD_SCOURGE, ScriptedAI::me, Unit::RemoveUnitFlag(), Unit::SetFaction(), and UNIT_FLAG_NON_ATTACKABLE.
Referenced by UpdateAI().
IsPlayerOnQuest()
bool npc_overlord_drakuru_betrayal::IsPlayerOnQuest (Player * player) inline
    {
        return player->GetQuestStatus(QUEST_BETRAYAL) == QUEST_STATUS_INCOMPLETE;
    }
References Player::GetQuestStatus(), QUEST_BETRAYAL, and QUEST_STATUS_INCOMPLETE.
Referenced by MoveInLineOfSight(), and UpdateAI().
JustEngagedWith()
void npc_overlord_drakuru_betrayal::JustEngagedWith (Unit *) inline override virtual
Called for reaction when initially engaged.
Reimplemented from CreatureAI.
    {
        scheduler.Schedule(0s, [this](TaskContext context)
        {
            if (!me->IsWithinMeleeRange(me->GetVictim()))
                DoCastVictim(SPELL_SHADOW_BOLT);
            context.Repeat(2s);
        }).Schedule(5s, [this](TaskContext context)
        {
            if (Unit* target = SelectTarget(SelectTargetMethod::Random, 0, 0.0f, true))
                DoCast(target, SPELL_THROW_BRIGHT_CRYSTAL);
            context.Repeat(6s, 15s);
        }).Schedule(20s, [this](TaskContext context)
        {
            Talk(SAY_DRAKURU_4);
            context.Repeat(10s, 20s);
        });
    }
References UnitAI::DoCast(), UnitAI::DoCastVictim(), Unit::GetVictim(), Unit::IsWithinMeleeRange(), ScriptedAI::me, Random, TaskContext::Repeat(), SAY_DRAKURU_4, TaskScheduler::Schedule(), CreatureAI::scheduler, UnitAI::SelectTarget(), SPELL_SHADOW_BOLT, and SPELL_THROW_BRIGHT_CRYSTAL.
JustSummoned()
void npc_overlord_drakuru_betrayal::JustSummoned (Creature * summon) inline override virtual
Reimplemented from CreatureAI.
    {
        _summons.Summon(summon);
        switch (summon->GetEntry())
        {
            case NPC_BLIGHTBLOOD_TROLL:
                if (Creature* target = summon->FindNearestCreature(NPC_TOTALLY_GENERIC_BUNNY, 10.0f, true))
                    target->CastSpell(target, SPELL_TELEPORT_EFFECT, true);
                break;
            case NPC_LICH_KING:
                me->SetFacingToObject(summon);
                _lichGUID = summon->GetGUID();
                summon->GetMotionMaster()->MovePoint(0, 6164.2695, -2016.8978, 590.8636);
                break;
            default:
                break;
        }
    }
References _lichGUID, _summons, WorldObject::FindNearestCreature(), Object::GetEntry(), Object::GetGUID(), Unit::GetMotionMaster(), ScriptedAI::me, MotionMaster::MovePoint(), NPC_BLIGHTBLOOD_TROLL, NPC_LICH_KING, NPC_TOTALLY_GENERIC_BUNNY, Unit::SetFacingToObject(), SPELL_TELEPORT_EFFECT, and SummonList::Summon().
MoveInLineOfSight()
void npc_overlord_drakuru_betrayal::MoveInLineOfSight (Unit * who) inline override virtual
Reimplemented from CreatureAI.
    {
        if (Player* player = who->ToPlayer())
        {
            bool shouldStartEvent = (_state == BETRAYAL_NOT_STARTED) && IsPlayerOnQuest(player) && player->HasAura(SPELL_SCOURGE_DISGUISE) && player->IsWithinDistInMap(me, 80.0f) && !me->FindNearestGameObject(GO_DRAKURUS_BONE, 80.0f);
            if (shouldStartEvent)
            {
                me->SetVisible(true);
                _state = BETRAYAL_IN_PROGRESS;
                DoAction(ACTION_DESTROY_DRAKURU_LAST_WISH);
                _playerGUID = who->GetGUID();
                events.ScheduleEvent(EVENT_BETRAYAL_INTRO_1, 6s);
                events.ScheduleEvent(EVENT_BETRAYAL_EVADE_CHECK, 10s);
            }
        }
        else
            ScriptedAI::MoveInLineOfSight(who);
    }
References _playerGUID, _state, ACTION_DESTROY_DRAKURU_LAST_WISH, BETRAYAL_IN_PROGRESS, BETRAYAL_NOT_STARTED, DoAction(), EVENT_BETRAYAL_EVADE_CHECK, EVENT_BETRAYAL_INTRO_1, WorldObject::FindNearestGameObject(), Object::GetGUID(), GO_DRAKURUS_BONE, IsPlayerOnQuest(), ScriptedAI::me, CreatureAI::MoveInLineOfSight(), Unit::SetVisible(), SPELL_SCOURGE_DISGUISE, and Object::ToPlayer().
Reset()
void npc_overlord_drakuru_betrayal::Reset () inline override virtual
Reimplemented from UnitAI.
    {
        events.Reset();
        scheduler.CancelAll();
        _summons.DespawnAll();
        _playerGUID.Clear();
        _lichGUID.Clear();
        me->SetFaction(FACTION_UNDEAD_SCOURGE);
        me->SetVisible(false);
        DoAction(ACTION_SUMMON_DRAKURU_LAST_WISH);
        me->RemoveUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
        me->SetImmuneToPC(true);
        _state = BETRAYAL_NOT_STARTED;
        DoAction(ACTION_REMOVE_SPOTLIGHTS);
    }
References _lichGUID, _playerGUID, _state, _summons, ACTION_REMOVE_SPOTLIGHTS, ACTION_SUMMON_DRAKURU_LAST_WISH, BETRAYAL_NOT_STARTED, TaskScheduler::CancelAll(), ObjectGuid::Clear(), SummonList::DespawnAll(), DoAction(), FACTION_UNDEAD_SCOURGE, ScriptedAI::me, Unit::RemoveUnitFlag(), CreatureAI::scheduler, Unit::SetFaction(), Unit::SetImmuneToPC(), Unit::SetVisible(), and UNIT_FLAG_NON_ATTACKABLE.
SpellHit()
void npc_overlord_drakuru_betrayal::SpellHit (Unit * , SpellInfo const * spellInfo) inline override virtual
Reimplemented from CreatureAI.
    {
        if (spellInfo->Id == SPELL_TOUCH_OF_DEATH)
        {
            DoCastAOE(SPELL_DRAKURUS_SKULL_MISSILE, true);
            DoCastSelf(SPELL_BLOATED_ABOMINATION_FEIGN_DEATH, true);
            DoCastSelf(SPELL_BURST_AT_THE_SEAMS_BONE, true);
            DoCastSelf(SPELL_BURST_AT_THE_SEAMS_BONE, true);
            DoCastSelf(SPELL_BURST_AT_THE_SEAMS_BONE, true);
            DoCastSelf(SPELL_EXPLODE_ABOMINATION_MEAT, true);
            DoCastSelf(SPELL_EXPLODE_ABOMINATION_BLOODY_MEAT, true);
            DoCastSelf(SPELL_EXPLODE_ABOMINATION_BLOODY_MEAT, true);
            DoCastSelf(SPELL_EXPLODE_ABOMINATION_BLOODY_MEAT, true);
            DoCastSelf(SPELL_DRAKURU_DEATH, true);
            DoAction(ACTION_SUMMON_DRAKURU_LAST_WISH);
            me->SetImmuneToPC(true);
        }
    }
References ACTION_SUMMON_DRAKURU_LAST_WISH, DoAction(), UnitAI::DoCastAOE(), UnitAI::DoCastSelf(), SpellInfo::Id, ScriptedAI::me, Unit::SetImmuneToPC(), SPELL_BLOATED_ABOMINATION_FEIGN_DEATH, SPELL_BURST_AT_THE_SEAMS_BONE, SPELL_DRAKURU_DEATH, SPELL_DRAKURUS_SKULL_MISSILE, SPELL_EXPLODE_ABOMINATION_BLOODY_MEAT, SPELL_EXPLODE_ABOMINATION_MEAT, and SPELL_TOUCH_OF_DEATH.
SpellHitTarget()
void npc_overlord_drakuru_betrayal::SpellHitTarget (Unit * target, SpellInfo const * spellInfo) inline override virtual
Reimplemented from CreatureAI.
    {
        switch (spellInfo->Id)
        {
            case SPELL_THROW_PORTAL_CRYSTAL:
                if (Aura* aura = target->AddAura(SPELL_ARTHAS_PORTAL, target))
                    aura->SetDuration(77'000);
                break;
            case SPELL_DRAKURUS_SKULL_MISSILE:
                target->CastSpell(target, SPELL_SUMMON_SKULL, true);
                break;
            case SPELL_DROP_DISGUISE:
                target->CastSpell(target, SPELL_SCOURGE_DISGUISE_EXPIRING, true);
                break;
        }
    }
References Unit::AddAura(), Unit::CastSpell(), SpellInfo::Id, SPELL_ARTHAS_PORTAL, SPELL_DRAKURUS_SKULL_MISSILE, SPELL_DROP_DISGUISE, SPELL_SCOURGE_DISGUISE_EXPIRING, SPELL_SUMMON_SKULL, and SPELL_THROW_PORTAL_CRYSTAL.
UpdateAI()
void npc_overlord_drakuru_betrayal::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Implements UnitAI.
    {
        events.Update(diff);
        switch (events.ExecuteEvent())
        {
            case EVENT_BETRAYAL_EVADE_CHECK:
            {
                if (_state == BETRAYAL_IN_PROGRESS)
                {
                    float radius = 80.0f;
                    std::list<Player*> players;
                    Acore::AnyPlayerInObjectRangeCheck checker(me, radius, true, true);
                    Acore::PlayerListSearcher<Acore::AnyPlayerInObjectRangeCheck> searcher(me, players, checker);
                    Cell::VisitObjects(me, searcher, radius);
                    if (std::ranges::any_of(players, [this](Player* player)
                    {
                        return IsPlayerOnQuest(player);
                    }))
                    {
                        events.Repeat(10s);
                    }
                    else
                    {
                        _state = BETRAYAL_EVADE;
                        EnterEvadeMode(EVADE_REASON_OTHER);
                    }
                }
                break;
            }
            case EVENT_BETRAYAL_INTRO_1:
                Talk(SAY_DRAKURU_0);
                events.ScheduleEvent(EVENT_BETRAYAL_INTRO_2, 4s);
                events.ScheduleEvent(EVENT_BETRAYAL_INTRO_3, 6600ms);
                break;
            case EVENT_BETRAYAL_INTRO_2:
                me->SummonCreatureGroup(SUMMON_GROUP_BLIGHTBLOOD_TROLL);
                break;
            case EVENT_BETRAYAL_INTRO_3:
                Talk(SAY_DRAKURU_1);
                DoCastAOE(SPELL_DROP_DISGUISE);
                events.ScheduleEvent(EVENT_BETRAYAL_INTRO_4, 9600ms);
                break;
            case EVENT_BETRAYAL_INTRO_4:
            {
                Talk(SAY_DRAKURU_2);
                Talk(SAY_DRAKURU_3);
                me->SetImmuneToPC(false);
                std::list<Creature*> creatures;
                me->GetCreatureListWithEntryInGrid(creatures, NPC_TOTALLY_GENERIC_BUNNY, 55.0f);
                for (Creature* creature : creatures)
                    creature->CastSpell(creature, SPELL_SCOURGE_SPOTLIGHT, true);
                break;
            }
            case EVENT_BETRAYAL_EPILOGUE_1:
            {
                Talk(SAY_DRAKURU_5);
                events.ScheduleEvent(EVENT_BETRAYAL_EPILOGUE_2, 4800ms);
                DoAction(ACTION_REMOVE_SPOTLIGHTS);
                break;
            }
            case EVENT_BETRAYAL_EPILOGUE_2:
                Talk(SAY_DRAKURU_6);
                events.ScheduleEvent(EVENT_BETRAYAL_EPILOGUE_3, 1800ms);
                break;
            case EVENT_BETRAYAL_EPILOGUE_3:
                DoCastSelf(SPELL_THROW_PORTAL_CRYSTAL, true);
                events.ScheduleEvent(EVENT_BETRAYAL_EPILOGUE_4, 3600ms);
                break;
            case EVENT_BETRAYAL_EPILOGUE_4:
                me->SummonCreature(NPC_LICH_KING, 6140.4233, -2010.9938, 589.1911, 6.126106, TEMPSUMMON_TIMED_DESPAWN, 77'000);
                events.ScheduleEvent(EVENT_BETRAYAL_EPILOGUE_5, 8400ms);
                break;
            case EVENT_BETRAYAL_EPILOGUE_5:
                Talk(SAY_DRAKURU_7);
                events.ScheduleEvent(EVENT_BETRAYAL_EPILOGUE_6, 9600ms);
                break;
            case EVENT_BETRAYAL_EPILOGUE_6:
                if (Creature* lich = ObjectAccessor::GetCreature(*me, _lichGUID))
                {
                    lich->AI()->Talk(SAY_LICH_7);
                    lich->AI()->Talk(SAY_LICH_8, 5400ms);
                }
                events.ScheduleEvent(EVENT_BETRAYAL_EPILOGUE_7, 7800ms);
                break;
            case EVENT_BETRAYAL_EPILOGUE_7:
                if (Creature* lich = ObjectAccessor::GetCreature(*me, _lichGUID))
                    lich->CastSpell(me, SPELL_TOUCH_OF_DEATH, false);
                events.ScheduleEvent(EVENT_BETRAYAL_EPILOGUE_8, 4200ms);
                break;
            case EVENT_BETRAYAL_EPILOGUE_8:
                me->SetVisible(false);
                if (Creature* lich = ObjectAccessor::GetCreature(*me, _lichGUID))
                {
                    lich->AI()->Talk(SAY_LICH_9, 3600ms);
                    lich->AI()->Talk(SAY_LICH_10, 8400ms);
                    lich->AI()->Talk(SAY_LICH_11, 22800ms);
                    lich->AI()->Talk(SAY_LICH_12, 27600ms);
                }
                events.ScheduleEvent(EVENT_BETRAYAL_EPILOGUE_9, 32600ms);
                events.ScheduleEvent(EVENT_BETRAYAL_EPILOGUE_10, 37200ms);
                break;
            case EVENT_BETRAYAL_EPILOGUE_9:
                if (Creature* lich = ObjectAccessor::GetCreature(*me, _lichGUID))
                    lich->GetMotionMaster()->MovePoint(0, 6141.2393, -2011.2728, 589.8653);
                break;
            case EVENT_BETRAYAL_EPILOGUE_10:
                _state = BETRAYAL_EVADE;
                EnterEvadeMode(EVADE_REASON_OTHER);
                break;
        }
        if (me->GetFaction() == 2082 || me->HasUnitState(UNIT_STATE_CASTING | UNIT_STATE_STUNNED))
            return;
        if (!UpdateVictim())
            return;
        scheduler.Update(diff);
        DoMeleeAttackIfReady();
    }
References _lichGUID, _state, ACTION_REMOVE_SPOTLIGHTS, BETRAYAL_EVADE, BETRAYAL_IN_PROGRESS, DoAction(), UnitAI::DoCastAOE(), UnitAI::DoCastSelf(), UnitAI::DoMeleeAttackIfReady(), EnterEvadeMode(), CreatureAI::EVADE_REASON_OTHER, EVENT_BETRAYAL_EPILOGUE_1, EVENT_BETRAYAL_EPILOGUE_10, EVENT_BETRAYAL_EPILOGUE_2, EVENT_BETRAYAL_EPILOGUE_3, EVENT_BETRAYAL_EPILOGUE_4, EVENT_BETRAYAL_EPILOGUE_5, EVENT_BETRAYAL_EPILOGUE_6, EVENT_BETRAYAL_EPILOGUE_7, EVENT_BETRAYAL_EPILOGUE_8, EVENT_BETRAYAL_EPILOGUE_9, EVENT_BETRAYAL_EVADE_CHECK, EVENT_BETRAYAL_INTRO_1, EVENT_BETRAYAL_INTRO_2, EVENT_BETRAYAL_INTRO_3, EVENT_BETRAYAL_INTRO_4, ObjectAccessor::GetCreature(), WorldObject::GetCreatureListWithEntryInGrid(), Unit::GetFaction(), Unit::HasUnitState(), IsPlayerOnQuest(), ScriptedAI::me, NPC_LICH_KING, NPC_TOTALLY_GENERIC_BUNNY, SAY_DRAKURU_0, SAY_DRAKURU_1, SAY_DRAKURU_2, SAY_DRAKURU_3, SAY_DRAKURU_5, SAY_DRAKURU_6, SAY_DRAKURU_7, SAY_LICH_10, SAY_LICH_11, SAY_LICH_12, SAY_LICH_7, SAY_LICH_8, SAY_LICH_9, CreatureAI::scheduler, Unit::SetImmuneToPC(), Unit::SetVisible(), SPELL_DROP_DISGUISE, SPELL_SCOURGE_SPOTLIGHT, SPELL_THROW_PORTAL_CRYSTAL, SPELL_TOUCH_OF_DEATH, SUMMON_GROUP_BLIGHTBLOOD_TROLL, WorldObject::SummonCreature(), WorldObject::SummonCreatureGroup(), TEMPSUMMON_TIMED_DESPAWN, UNIT_STATE_CASTING, UNIT_STATE_STUNNED, TaskScheduler::Update(), CreatureAI::UpdateVictim(), and Cell::VisitObjects().
Member Data Documentation
_lichGUID
ObjectGuid npc_overlord_drakuru_betrayal::_lichGUID private
Referenced by JustSummoned(), Reset(), and UpdateAI().
_playerGUID
ObjectGuid npc_overlord_drakuru_betrayal::_playerGUID private
Referenced by MoveInLineOfSight(), and Reset().
_state
BetrayalState npc_overlord_drakuru_betrayal::_state private
Referenced by DamageTaken(), EnterEvadeMode(), MoveInLineOfSight(), Reset(), and UpdateAI().
_summons
SummonList npc_overlord_drakuru_betrayal::_summons private
Referenced by JustSummoned(), and Reset().
The documentation for this struct was generated from the following file:
azerothcore-wotlk/src/server/scripts/Northrend/zone_zuldrak.cpp