AzerothCore Doxygen
SpellProcDatabaseTest Class Reference
Protected Member Functions
void SetUp () override
void TearDown () override
ProcFlagScenario const * FindMatchingScenario (uint32 procFlags)
Find the first matching proc flag scenario for given flags.
uint32 GetEffectiveHitMask (SpellProcTestEntry const &entry, ProcFlagScenario const *scenario)
Get effective hit mask for an entry.
uint32 GetEffectiveSpellTypeMask (SpellProcTestEntry const &entry, ProcFlagScenario const *scenario)
Get effective spell type mask.
uint32 GetEffectiveSpellPhaseMask (SpellProcTestEntry const &entry, ProcFlagScenario const *scenario)
Get effective spell phase mask.
bool RequiresSpellFamilyMatch (SpellProcTestEntry const &entry)
Check if entry requires SpellFamily matching (which we can't test without SpellInfo) Any entry with SpellFamilyName > 0 will cause CanSpellTriggerProcOnEvent to access eventInfo.GetSpellInfo() which returns null in our test, causing a crash.
bool IsSpellTypeProc (uint32 procFlags)
Check if the proc flags indicate a spell-type event that needs SpellInfo.
ProcEventInfo CreateEventInfo (uint32 typeMask, uint32 hitMask, uint32 spellTypeMask, uint32 spellPhaseMask)
Create a ProcEventInfo with proper DamageInfo/HealInfo for spell-type procs.
Protected Attributes
IWorld * _originalWorld = nullptr
NiceMock< WorldMock > * _worldMock = nullptr
SpellInfo * _defaultSpellInfo = nullptr
DamageInfo * _damageInfo = nullptr
HealInfo * _healInfo = nullptr
std::vector< SpellProcTestEntry > _allEntries
Detailed Description
Member Function Documentation
CreateEventInfo()
ProcEventInfo SpellProcDatabaseTest::CreateEventInfo (uint32 typeMask, uint32 hitMask, uint32 spellTypeMask, uint32 spellPhaseMask) inline protected
Create a ProcEventInfo with proper DamageInfo/HealInfo for spell-type procs.
    {
        auto builder = ProcEventInfoBuilder()
            .WithTypeMask(typeMask)
            .WithHitMask(hitMask)
            .WithSpellTypeMask(spellTypeMask)
            .WithSpellPhaseMask(spellPhaseMask);
        // For spell-type procs, provide DamageInfo or HealInfo with SpellInfo
        if (IsSpellTypeProc(typeMask))
        {
            if (spellTypeMask & PROC_SPELL_TYPE_HEAL)
            {
                if (!_healInfo)
                    _healInfo = new HealInfo(nullptr, nullptr, 100, _defaultSpellInfo, SPELL_SCHOOL_MASK_HOLY);
                builder.WithHealInfo(_healInfo);
            }
            else
            {
                if (!_damageInfo)
                    _damageInfo = new DamageInfo(nullptr, nullptr, 100, _defaultSpellInfo, SPELL_SCHOOL_MASK_FIRE, SPELL_DIRECT_DAMAGE);
                builder.WithDamageInfo(_damageInfo);
            }
        }
        return builder.Build();
    }
References _damageInfo, _defaultSpellInfo, _healInfo, IsSpellTypeProc(), PROC_SPELL_TYPE_HEAL, SPELL_DIRECT_DAMAGE, SPELL_SCHOOL_MASK_FIRE, SPELL_SCHOOL_MASK_HOLY, spellTypeMask, ProcEventInfoBuilder::WithHitMask(), ProcEventInfoBuilder::WithSpellPhaseMask(), ProcEventInfoBuilder::WithSpellTypeMask(), and ProcEventInfoBuilder::WithTypeMask().
FindMatchingScenario()
ProcFlagScenario const * SpellProcDatabaseTest::FindMatchingScenario (uint32 procFlags) inline protected
Find the first matching proc flag scenario for given flags.
    {
        for (auto const& scenario : PROC_FLAG_SCENARIOS)
        {
            if (procFlags & scenario.procFlag)
                return &scenario;
        }
        return nullptr;
    }
References PROC_FLAG_SCENARIOS.
GetEffectiveHitMask()
uint32 SpellProcDatabaseTest::GetEffectiveHitMask (SpellProcTestEntry const & entry, ProcFlagScenario const * scenario) inline protected
Get effective hit mask for an entry.
    {
        if (entry.HitMask != 0)
        {
            // Return first set bit
            for (auto const& [mask, name] : HIT_MASK_SCENARIOS)
            {
                if (entry.HitMask & mask)
                    return mask;
            }
        }
        return scenario ? scenario->defaultHitMask : PROC_HIT_NORMAL;
    }
References ProcFlagScenario::defaultHitMask, HIT_MASK_SCENARIOS, SpellProcTestEntry::HitMask, and PROC_HIT_NORMAL.
GetEffectiveSpellPhaseMask()
uint32 SpellProcDatabaseTest::GetEffectiveSpellPhaseMask (SpellProcTestEntry const & entry, ProcFlagScenario const * scenario) inline protected
Get effective spell phase mask.
    {
        if (entry.SpellPhaseMask != 0)
            return entry.SpellPhaseMask;
        if (scenario && scenario->requiresSpellPhase)
            return scenario->defaultSpellPhaseMask ? scenario->defaultSpellPhaseMask : PROC_SPELL_PHASE_HIT;
        return 0;
    }
References ProcFlagScenario::defaultSpellPhaseMask, PROC_SPELL_PHASE_HIT, ProcFlagScenario::requiresSpellPhase, and SpellProcTestEntry::SpellPhaseMask.
GetEffectiveSpellTypeMask()
uint32 SpellProcDatabaseTest::GetEffectiveSpellTypeMask (SpellProcTestEntry const & entry, ProcFlagScenario const * scenario) inline protected
Get effective spell type mask.
    {
        if (entry.SpellTypeMask != 0)
        {
            if (entry.SpellTypeMask & PROC_SPELL_TYPE_DAMAGE)
                return PROC_SPELL_TYPE_DAMAGE;
            if (entry.SpellTypeMask & PROC_SPELL_TYPE_HEAL)
                return PROC_SPELL_TYPE_HEAL;
            if (entry.SpellTypeMask & PROC_SPELL_TYPE_NO_DMG_HEAL)
                return PROC_SPELL_TYPE_NO_DMG_HEAL;
        }
        return scenario ? scenario->defaultSpellTypeMask : PROC_SPELL_TYPE_MASK_ALL;
    }
References ProcFlagScenario::defaultSpellTypeMask, PROC_SPELL_TYPE_DAMAGE, PROC_SPELL_TYPE_HEAL, PROC_SPELL_TYPE_MASK_ALL, PROC_SPELL_TYPE_NO_DMG_HEAL, and SpellProcTestEntry::SpellTypeMask.
IsSpellTypeProc()
bool SpellProcDatabaseTest::IsSpellTypeProc (uint32 procFlags) inline protected
Check if the proc flags indicate a spell-type event that needs SpellInfo.
    {
        return (procFlags & (PERIODIC_PROC_FLAG_MASK | SPELL_PROC_FLAG_MASK | PROC_FLAG_DONE_TRAP_ACTIVATION)) != 0;
    }
References PERIODIC_PROC_FLAG_MASK, PROC_FLAG_DONE_TRAP_ACTIVATION, and SPELL_PROC_FLAG_MASK.
Referenced by CreateEventInfo().
RequiresSpellFamilyMatch()
bool SpellProcDatabaseTest::RequiresSpellFamilyMatch (SpellProcTestEntry const & entry) inline protected
Check if entry requires SpellFamily matching (which we can't test without SpellInfo) Any entry with SpellFamilyName > 0 will cause CanSpellTriggerProcOnEvent to access eventInfo.GetSpellInfo() which returns null in our test, causing a crash.
    {
        // Skip any entry with SpellFamilyName set - the code will try to access SpellInfo
        return entry.SpellFamilyName != 0;
    }
References SpellProcTestEntry::SpellFamilyName.
SetUp()
void SpellProcDatabaseTest::SetUp () inline override protected
    {
        _originalWorld = sWorld.release();
        _worldMock = new NiceMock<WorldMock>();
        sWorld.reset(_worldMock);
        static std::string emptyString;
        ON_CALL(*_worldMock, GetDataPath()).WillByDefault(ReturnRef(emptyString));
        // Load all entries from generated data
        _allEntries = GetAllSpellProcTestEntries();
        // Create a default SpellInfo for spell-type procs
        _defaultSpellInfo = SpellInfoBuilder()
            .WithId(99999)
            .WithSpellFamilyName(0)
            .Build();
    }
References _allEntries, _defaultSpellInfo, _originalWorld, _worldMock, SpellInfoBuilder::Build(), GetAllSpellProcTestEntries(), sWorld, SpellInfoBuilder::WithId(), and SpellInfoBuilder::WithSpellFamilyName().
TearDown()
void SpellProcDatabaseTest::TearDown () inline override protected
    {
        IWorld* currentWorld = sWorld.release();
        delete currentWorld;
        _worldMock = nullptr;
        sWorld.reset(_originalWorld);
        delete _defaultSpellInfo;
        _defaultSpellInfo = nullptr;
        delete _damageInfo;
        _damageInfo = nullptr;
        delete _healInfo;
        _healInfo = nullptr;
    }
References _damageInfo, _defaultSpellInfo, _healInfo, _originalWorld, _worldMock, and sWorld.
Member Data Documentation
_allEntries
std::vector<SpellProcTestEntry> SpellProcDatabaseTest::_allEntries protected
Referenced by SetUp().
_damageInfo
DamageInfo* SpellProcDatabaseTest::_damageInfo = nullptr protected
Referenced by CreateEventInfo(), and TearDown().
_defaultSpellInfo
SpellInfo* SpellProcDatabaseTest::_defaultSpellInfo = nullptr protected
Referenced by CreateEventInfo(), SetUp(), and TearDown().
_healInfo
HealInfo* SpellProcDatabaseTest::_healInfo = nullptr protected
Referenced by CreateEventInfo(), and TearDown().
_originalWorld
IWorld* SpellProcDatabaseTest::_originalWorld = nullptr protected
Referenced by SetUp(), and TearDown().
_worldMock
NiceMock<WorldMock>* SpellProcDatabaseTest::_worldMock = nullptr protected
Referenced by SetUp(), and TearDown().
The documentation for this class was generated from the following file:
azerothcore-wotlk/src/test/server/game/Spells/SpellProcDataDrivenTest.cpp