AzerothCore Doxygen
GameTime Namespace Reference
Functions
Seconds GetStartTime ()
Seconds GetGameTime ()
Milliseconds GetGameTimeMS ()
SystemTimePoint GetSystemTime ()
Current chrono system_clock time point.
TimePoint Now ()
Current chrono steady_clock time point.
Seconds GetUptime ()
Uptime.
void UpdateGameTimers ()
Update all timers.
Variables
Seconds const StartTime = GetEpochTime()
Seconds GameTime = GetEpochTime()
Milliseconds GameMSTime = 0ms
SystemTimePoint GameTimeSystemPoint = SystemTimePoint::min()
TimePoint GameTimeSteadyPoint = TimePoint::min()
Function Documentation
GetGameTime()
AC_GAME_API Seconds GameTime::GetGameTime ()
    {
        return GameTime;
    }
References GameTime.
Referenced by Unit::_ExitVehicle(), Player::_LoadMail(), Player::_LoadQuestStatus(), Pet::_LoadSpellCooldowns(), Player::_LoadSpellCooldowns(), InstanceSaveMgr::_ResetOrWarnAll(), Player::_SaveCharacter(), Player::_SaveQuestStatus(), Pet::_SaveSpellCooldowns(), Player::_SaveSpellCooldowns(), World::_UpdateGameTime(), InstanceSaveMgr::AddInstanceSave(), Player::AddItemToBuyBackSlot(), Player::AddNewMailDeliverTime(), InstanceMap::AddPlayerToMap(), Player::AddQuest(), WorldSessionMgr::AddSession_(), Creature::AllLootRemovedFromCorpse(), BanMgr::BanAccount(), BanMgr::BanAccountByPlayerName(), AchievementMgr::BuildAllDataPacket(), SearchableAuctionEntry::BuildAuctionInfo(), Player::CalculateCorpseReclaimDelay(), Creature::CanCreatureAttack(), Creature::CanGeneratePickPocketLoot(), Spell::CheckCast(), lfg::LFGQueue::CheckCompatibility(), GameEventMgr::CheckOneGameEvent(), GameEventMgr::CheckOneGameEventConditions(), spell_botanica_shift_form_aura::CheckProc(), PassengerController::ClearSlot(), AchievementMgr::CompletedAchievement(), Corpse::Corpse(), Player::Create(), Guild::Create(), Player::DeleteOldCharacters(), CalendarMgr::DeleteOldEvents(), Player::DeleteOldRecoveryItems(), Unit::Dismount(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::DoAction(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::DoAction(), boss_the_lich_king::boss_the_lich_kingAI::DoAction(), FlightPathMovementGenerator::DoFinalize(), Spell::EffectCharge(), Spell::EffectDummy(), Spell::EffectLeapBack(), BattlefieldWG::FillInitialWorldStates(), Pet::FillPetInfo(), GmTicket::FormatMessageString(), GetAge(), Player::GetCorpseReclaimDelay(), Group::GetDifficultyChangePreventionTime(), Unit::GetDiseasesByCaster(), Creature::GetLastLeashExtensionTimePtr(), Item::GetPlayedTime(), Creature::GetRespawnTimeEx(), GameObject::GetRespawnTimeEx(), Creature::GetVendorItemCurrentCount(), WorldSession::HandleAuctionSellItem(), AuraEffect::HandleAuraFeatherFall(), WorldSocket::HandleAuthSessionCallback(), ban_commandscript::HandleBanInfoCharacterCommand(), ban_commandscript::HandleBanInfoHelper(), WorldSession::HandleCalendarAddEvent(), WorldSession::HandleCalendarCopyEvent(), WorldSession::HandleCalendarEventRsvp(), WorldSession::HandleCalendarEventSignup(), WorldSession::HandleCalendarEventStatus(), WorldSession::HandleCalendarGetCalendar(), WorldSession::HandleCalendarUpdateEvent(), BattlegroundIC::HandleCapturedNodes(), WorldSession::HandleDuelAcceptedOpcode(), Unit::HandleDummyAuraProc(), spell_midsummer_ribbon_pole::HandleEffectPeriodic(), event_commandscript::HandleEventInfoCommand(), gobject_commandscript::HandleGameObjectTargetCommand(), WorldSession::HandleGetMailList(), instance_commandscript::HandleInstanceListBindsCommand(), instance_commandscript::HandleInstanceUnbindCommand(), BattlegroundIC::HandleKillUnit(), WorldSession::HandleLogoutRequestOpcode(), WorldSession::HandleMailCreateTextItem(), WorldSession::HandleMailReturnToSender(), WorldSession::HandleMailTakeItem(), WorldSession::HandleMailTakeMoney(), WorldSession::HandleMessagechatOpcode(), WorldSession::HandleMoveSplineDoneOpcode(), WorldSession::HandleMoveWorldportAck(), misc_commandscript::HandleMuteCommand(), npc_commandscript::HandleNpcInfoCommand(), WorldSession::HandlePetRename(), misc_commandscript::HandlePInfoCommand(), Battlefield::HandlePlayerEnterZone(), WorldSession::HandlePlayerLoginFromDB(), WorldSession::HandlePlayerLoginToCharInWorld(), WorldSession::HandleQueryNextMailTime(), quest_commandscript::HandleQuestReward(), WorldSession::HandleReclaimCorpseOpcode(), WorldSession::HandleReportLag(), Guild::HandleRoster(), WorldSession::HandleTeleportTimeout(), WorldSession::HandleTextEmoteOpcode(), WorldSession::HandleWorldStateUITimerUpdate(), WorldSessionMgr::HasRecentlyDisconnected(), BattlegroundMgr::InitAutomaticArenaPointDistribution(), lfg::LFGMgr::InitBoot(), LoginQueryHolder::Initialize(), PacketLog::Initialize(), Battlefield::InvitePlayersInZoneToWar(), Battlefield::InvitePlayerToWar(), Channel::IsBanned(), Creature::IsInvisibleDueToDespawn(), Player::IsSummonAsSpectator(), Item::Item(), lfg::LFGMgr::JoinLfg(), npc_simone::npc_simoneAI::JustDied(), Channel::KickOrBan(), boss_the_lich_king::boss_the_lich_kingAI::KilledUnit(), Player::LeaveBattleground(), GameEventMgr::LoadEvents(), Player::LoadFromDB(), AchievementMgr::LoadFromDB(), GameObject::LoadGameObjectFromDB(), Pet::LoadPetFromDB(), InstanceSaveMgr::LoadResetTimes(), AchievementCriteriaData::Meets(), Unit::Mount(), MotionMaster::MoveFall(), npc_brewfest_keg_reciver::MoveInLineOfSight(), GameEventMgr::NextCheck(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::npc_high_overlord_saurfang_igbAI(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::npc_muradin_bronzebeard_igbAI(), npc_riggle_bassbait::npc_riggle_bassbaitAI::npc_riggle_bassbaitAI(), npc_ulduar_flames_initial::npc_ulduar_flames_initialAI::npc_ulduar_flames_initialAI(), npc_wg_queue::OnGossipHello(), npc_riggle_bassbait::OnQuestReward(), AreaTrigger_at_brewfest::OnTrigger(), AreaTrigger_at_area_52_entrance::OnTrigger(), at_ring_of_law::OnTrigger(), instance_ulduar::instance_ulduar_InstanceMapScript::OnUnitDeath(), MovementInfo::OutDebug(), Player::Player(), BattlegroundIC::PostUpdateImpl(), Creature::RemoveCorpse(), Map::RemoveOldCorpses(), MotionTransport::RemovePassenger(), StaticTransport::RemovePassenger(), Corpse::ResetGhostTime(), Player::resetTalents(), Player::resetTalentsCost(), GameObject::Respawn(), Creature::Respawn(), ObjectMgr::ReturnOrDeleteOldMails(), Map::SaveCreatureRespawnTime(), Map::SaveGORespawnTime(), Pet::SavePetToDB(), OutdoorPvPTF::SaveRequiredWorldStates(), GameObject::SaveRespawnTime(), Map::ScriptCommandStart(), Map::ScriptsProcess(), Map::ScriptsStart(), WorldSession::SendAccountDataTimes(), AchievementMgr::SendAchievementEarned(), AuctionHouseMgr::SendAuctionSalePendingMail(), Player::SendBattlefieldWorldStates(), WorldSession::SendBfInvitePlayerToWar(), WorldSession::SendCalendarRaidLockout(), WorldSession::SendCalendarRaidLockoutUpdated(), AchievementMgr::SendCriteriaUpdate(), Player::SendInitialPacketsBeforeAddToMap(), WorldSession::SendLfgBootProposalUpdate(), Player::SendLoot(), MailDraft::SendMailTo(), WorldSession::SendPacket(), WorldSession::SendQueryTimeResponse(), Player::SendRaidInfo(), Player::SetCanFly(), Creature::SetCanFly(), Unit::SetCharmedBy(), Creature::SetCorpseRemoveTime(), AchievementMgr::SetCriteriaProgress(), Player::SetDailyQuestStatus(), instance_blackrock_depths::instance_blackrock_depths_InstanceMapScript::SetData(), instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::SetData(), instance_vault_of_archavon::instance_vault_of_archavon_InstanceMapScript::SetData(), Creature::setDeathState(), Group::SetDifficultyChangePrevention(), GameEventMgr::SetHolidayEventTime(), World::SetInitialWorldSettings(), GameObject::SetLootGenerationTime(), GameObject::SetLootState(), GmTicket::SetMessage(), Creature::SetPickPocketLootTime(), GameObject::SetRespawnTime(), Creature::SetRespawnTime(), Player::SetRestFlag(), Player::SetRestState(), Player::SetSummonPoint(), OutdoorPvPTF::SetupOutdoorPvP(), boss_the_lich_king::boss_the_lich_kingAI::SpellHit(), GameEventMgr::StartEvent(), GameEventMgr::StopEvent(), PassengerController::SummonCreatures(), Player::SummonIfPossible(), Player::SummonPet(), Player::TeleportTo(), AuctionHouseObject::Update(), GameEventMgr::Update(), InstanceSaveMgr::Update(), Battlefield::Update(), BattlegroundMgr::Update(), Pet::Update(), World::Update(), WorldSession::Update(), lfg::LFGMgr::Update(), GameObject::Update(), Creature::Update(), Player::Update(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::UpdateAI(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::UpdateAI(), boss_mimiron::boss_mimironAI::UpdateAI(), Player::UpdateCorpseReclaimDelay(), Player::UpdateFFAPvPState(), Player::UpdateHonorFields(), TicketMgr::UpdateLastChange(), Creature::UpdateLeashExtensionTime(), Guild::Member::UpdateLogoutTime(), Player::UpdateNextMailTimeAndUnreads(), StaticTransport::UpdatePassengerPositions(), Item::UpdatePlayedTime(), lfg::LFGMgr::UpdateProposal(), Player::UpdatePvP(), Player::UpdatePvPState(), lfg::LFGQueue::UpdateQueueTimers(), lfg::LFGMgr::UpdateRoleCheck(), WorldSessionMgr::UpdateSessions(), Player::UpdateSpeakTime(), Creature::UpdateVendorItemCurrentCount(), Guild::BankEventLogEntry::WritePacket(), and Guild::EventLogEntry::WritePacket().
GetGameTimeMS()
AC_GAME_API Milliseconds GameTime::GetGameTimeMS ()
    {
        return GameMSTime;
    }
References GameMSTime.
Referenced by Creature::_AddCreatureSpellCooldown(), Player::_AddSpellCooldown(), Pet::_SaveSpellCooldowns(), Player::_SaveSpellCooldowns(), GlobalCooldownMgr::AddGlobalCooldown(), BattlegroundQueue::AddGroup(), WorldObject::AddToNotify(), Unit::ApplyDiminishingAura(), Player::ApplyEquipCooldown(), BattlegroundQueue::BattlegroundQueueUpdate(), Unit::BuildMovementPacket(), BattlegroundQueue::CheckPremadeMatch(), DynamicObject::CreateDynamicObject(), Spell::DoAllEffectOnTarget(), Spell::EffectSanctuary(), Unit::GetDiminishing(), Creature::GetSpellCooldown(), WorldSession::HandleBattlefieldStatusOpcode(), WardenWin::HandleData(), spell_mimiron_p3wx2_laser_barrage_aura::HandleEffectPeriodic(), WorldSession::HandlePlayerLoginFromDB(), WorldSession::HandlePlayerLoginToCharInWorld(), GlobalCooldownMgr::HasGlobalCooldown(), Creature::HasSpellCooldown(), Unit::IncrDiminishing(), BattlegroundQueue::InviteGroupToBG(), Creature::IsSpellProhibited(), Unit::IsUnderLastManaUseEffect(), spell_mimiron_p3wx2_laser_barrage_aura::Load(), spell_gen_turkey_marker::OnPeriodic(), Player::PetSpellInitialize(), BattlegroundQueue::PlayerInvitedToBGUpdateAverageWaitTime(), BattlegroundEY::PostUpdateImpl(), Creature::ProhibitSpellSchool(), Player::RemoveAllSpellCooldown(), Player::RemoveArenaSpellCooldowns(), WardenWin::RequestChecks(), npc_midsummer_torch_target::SelectPosition(), Player::SendInitialSpells(), Unit::SendMonsterMove(), Spell::SendSpellGo(), boss_ignis::boss_ignisAI::SetData(), Spell::TakePower(), World::Update(), GameObject::Update(), BattlegroundSA::UpdateDemolisherSpawns(), lfg::LFGMgr::UpdateRaidBrowser(), GameObject::Use(), GameObject::UseDoorOrButton(), and Player::VehicleSpellInitialize().
GetStartTime()
AC_GAME_API Seconds GameTime::GetStartTime ()
    {
        return StartTime;
    }
References StartTime.
Referenced by World::SetInitialWorldSettings(), and World::Update().
GetSystemTime()
AC_GAME_API SystemTimePoint GameTime::GetSystemTime ()
Current chrono system_clock time point.
    {
        return GameTimeSystemPoint;
    }
References GameTimeSystemPoint.
Referenced by AchievementGlobalMgr::IsRealmCompleted(), and AchievementGlobalMgr::SetRealmCompleted().
GetUptime()
AC_GAME_API Seconds GameTime::GetUptime ()
Uptime.
    {
        return GameTime - StartTime;
    }
References StartTime.
Referenced by server_commandscript::HandleServerInfoCommand(), and World::Update().
Now()
AC_GAME_API TimePoint GameTime::Now ()
Current chrono steady_clock time point.
    {
        return GameTimeSteadyPoint;
    }
References GameTimeSteadyPoint.
Referenced by WorldSocket::ReadDataHandler().
UpdateGameTimers()
void GameTime::UpdateGameTimers ()
Update all timers.
    {
        GameTime = GetEpochTime();
        GameMSTime = GetTimeMS();
        GameTimeSystemPoint = system_clock::now();
        GameTimeSteadyPoint = steady_clock::now();
    }
References GameMSTime, GameTimeSteadyPoint, GameTimeSystemPoint, GetEpochTime(), and GetTimeMS().
Referenced by World::_UpdateGameTime().
Variable Documentation
GameMSTime
Milliseconds GameTime::GameMSTime = 0ms
Referenced by GetGameTimeMS(), and UpdateGameTimers().
GameTime
Seconds GameTime::GameTime = GetEpochTime()
Referenced by GetGameTime().
GameTimeSteadyPoint
TimePoint GameTime::GameTimeSteadyPoint = TimePoint::min()
Referenced by Now(), and UpdateGameTimers().
GameTimeSystemPoint
SystemTimePoint GameTime::GameTimeSystemPoint = SystemTimePoint::min()
Referenced by GetSystemTime(), and UpdateGameTimers().
StartTime
Seconds const GameTime::StartTime = GetEpochTime()
Referenced by GetStartTime(), and GetUptime().