AzerothCore Doxygen
PlayerScript Class Reference
#include "PlayerScript.h"
Public Member Functions
virtual void OnPlayerJustDied (Player *)
virtual void OnPlayerCalculateTalentsPoints (Player const *, uint32 &)
virtual void OnPlayerReleasedGhost (Player *)
virtual void OnPlayerSendInitialPacketsBeforeAddToMap (Player *, WorldPacket &)
virtual void OnPlayerBattlegroundDesertion (Player *, BattlegroundDesertionType const)
virtual void OnPlayerCompleteQuest (Player *, Quest const *)
virtual void OnPlayerPVPKill (Player *, Player *)
virtual void OnPlayerPVPFlagChange (Player *, bool)
virtual void OnPlayerCreatureKill (Player *, Creature *)
virtual void OnPlayerCreatureKilledByPet (Player *, Creature *)
virtual void OnPlayerKilledByCreature (Creature *, Player *)
virtual void OnPlayerLevelChanged (Player *, uint8)
virtual void OnPlayerFreeTalentPointsChanged (Player *, uint32)
virtual void OnPlayerTalentsReset (Player *, bool)
virtual void OnPlayerAfterSpecSlotChanged (Player *, uint8)
virtual void OnPlayerBeforeUpdate (Player *, uint32)
virtual void OnPlayerUpdate (Player *, uint32)
virtual void OnPlayerMoneyChanged (Player *, int32 &)
virtual void OnPlayerBeforeLootMoney (Player *, Loot *)
virtual void OnPlayerGiveXP (Player *, uint32 &, Unit *, uint8)
virtual bool OnPlayerReputationChange (Player *, uint32, int32 &, bool)
virtual void OnPlayerReputationRankChange (Player *, uint32, ReputationRank, ReputationRank, bool)
virtual void OnPlayerLearnSpell (Player *, uint32)
virtual void OnPlayerForgotSpell (Player *, uint32)
virtual void OnPlayerDuelRequest (Player *, Player *)
virtual void OnPlayerDuelStart (Player *, Player *)
virtual void OnPlayerDuelEnd (Player *, Player *, DuelCompleteType)
virtual void OnPlayerChat (Player *, uint32, uint32, std::string &)
virtual void OnPlayerBeforeSendChatMessage (Player *, uint32 &, uint32 &, std::string &)
virtual void OnPlayerChat (Player *, uint32, uint32, std::string &, Player *)
virtual void OnPlayerChat (Player *, uint32, uint32, std::string &, Group *)
virtual void OnPlayerChat (Player *, uint32, uint32, std::string &, Guild *)
virtual void OnPlayerChat (Player *, uint32, uint32, std::string &, Channel *)
virtual void OnPlayerEmote (Player *, uint32)
virtual void OnPlayerTextEmote (Player *, uint32, uint32, ObjectGuid)
virtual void OnPlayerSpellCast (Player *, Spell *, bool)
virtual void OnPlayerLoadFromDB (Player *)
virtual void OnPlayerLogin (Player *)
virtual void OnPlayerBeforeLogout (Player *)
virtual void OnPlayerLogout (Player *)
virtual void OnPlayerCreate (Player *)
virtual void OnPlayerDelete (ObjectGuid, uint32)
virtual void OnPlayerFailedDelete (ObjectGuid, uint32)
virtual void OnPlayerSave (Player *)
virtual void OnPlayerBindToInstance (Player *, Difficulty, uint32, bool)
virtual void OnPlayerUpdateZone (Player *, uint32, uint32)
virtual void OnPlayerUpdateArea (Player *, uint32, uint32)
virtual void OnPlayerMapChanged (Player *)
virtual bool OnPlayerBeforeTeleport (Player *, uint32, float, float, float, float, uint32, Unit *)
virtual void OnPlayerUpdateFaction (Player *)
virtual void OnPlayerAddToBattleground (Player *, Battleground *)
virtual void OnPlayerQueueRandomDungeon (Player *, uint32 &)
virtual void OnPlayerRemoveFromBattleground (Player *, Battleground *)
virtual void OnPlayerAchievementComplete (Player *, AchievementEntry const *)
virtual bool OnPlayerBeforeAchievementComplete (Player *, AchievementEntry const *)
virtual void OnPlayerCriteriaProgress (Player *, AchievementCriteriaEntry const *)
virtual bool OnPlayerBeforeCriteriaProgress (Player *, AchievementCriteriaEntry const *)
virtual void OnPlayerAchievementSave (CharacterDatabaseTransaction, Player *, uint16, CompletedAchievementData)
virtual void OnPlayerCriteriaSave (CharacterDatabaseTransaction, Player *, uint16, CriteriaProgress)
virtual void OnPlayerGossipSelect (Player *, uint32, uint32, uint32)
virtual void OnPlayerGossipSelectCode (Player *, uint32, uint32, uint32, const char *)
virtual void OnPlayerBeingCharmed (Player *, Unit *, uint32, uint32)
virtual void OnPlayerAfterSetVisibleItemSlot (Player *, uint8, Item *)
virtual void OnPlayerAfterMoveItemFromInventory (Player *, Item *, uint8, uint8, bool)
virtual void OnPlayerEquip (Player *, Item *, uint8, uint8, bool)
virtual void OnPlayerJoinBG (Player *)
virtual void OnPlayerJoinArena (Player *)
virtual void OnPlayerGetMaxPersonalArenaRatingRequirement (Player const *, uint32, uint32 &) const
virtual void OnPlayerLootItem (Player *, Item *, uint32, ObjectGuid)
virtual void OnPlayerBeforeFillQuestLootItem (Player *, LootItem &)
virtual void OnPlayerStoreNewItem (Player *, Item *, uint32)
virtual void OnPlayerCreateItem (Player *, Item *, uint32)
virtual void OnPlayerQuestRewardItem (Player *, Item *, uint32)
virtual bool OnPlayerCanPlaceAuctionBid (Player *, AuctionEntry *)
virtual void OnPlayerGroupRollRewardItem (Player *, Item *, uint32, RollVote, Roll *)
virtual bool OnPlayerBeforeOpenItem (Player *, Item *)
virtual bool OnPlayerBeforeQuestComplete (Player *, uint32)
virtual void OnPlayerQuestComputeXP (Player *, Quest const *, uint32 &)
virtual void OnPlayerBeforeDurabilityRepair (Player *, ObjectGuid, ObjectGuid, float &, uint8)
virtual void OnPlayerBeforeBuyItemFromVendor (Player *, ObjectGuid, uint32, uint32 &, uint8, uint8, uint8)
virtual void OnPlayerBeforeStoreOrEquipNewItem (Player *, uint32, uint32 &, uint8, uint8, uint8, ItemTemplate const *, Creature *, VendorItem const *, bool)
virtual void OnPlayerAfterStoreOrEquipNewItem (Player *, uint32, Item *, uint8, uint8, uint8, ItemTemplate const *, Creature *, VendorItem const *, bool)
virtual void OnPlayerAfterUpdateMaxPower (Player *, Powers &, float &)
virtual void OnPlayerAfterUpdateMaxHealth (Player *, float &)
virtual void OnPlayerBeforeUpdateAttackPowerAndDamage (Player *, float &, float &, bool)
virtual void OnPlayerAfterUpdateAttackPowerAndDamage (Player *, float &, float &, float &, float &, bool)
virtual void OnPlayerBeforeInitTalentForLevel (Player *, uint8 &, uint32 &)
virtual void OnPlayerFirstLogin (Player *)
virtual void OnPlayerSetMaxLevel (Player *, uint32 &)
virtual bool OnPlayerCanJoinInBattlegroundQueue (Player *, ObjectGuid, BattlegroundTypeId, uint8, GroupJoinBattlegroundResult &)
virtual bool OnPlayerShouldBeRewardedWithMoneyInsteadOfExp (Player *)
virtual void OnPlayerBeforeTempSummonInitStats (Player *, TempSummon *, uint32 &)
virtual void OnPlayerBeforeGuardianInitStatsForLevel (Player *, Guardian *, CreatureTemplate const *, PetType &)
virtual void OnPlayerAfterGuardianInitStatsForLevel (Player *, Guardian *)
virtual void OnPlayerBeforeLoadPetFromDB (Player *, uint32 &, uint32 &, bool &, bool &)
virtual bool OnPlayerCanJoinInArenaQueue (Player *, ObjectGuid, uint8, BattlegroundTypeId, uint8, uint8, GroupJoinBattlegroundResult &)
virtual bool OnPlayerCanBattleFieldPort (Player *, uint8, BattlegroundTypeId, uint8)
virtual bool OnPlayerCanGroupInvite (Player *, std::string &)
virtual bool OnPlayerCanGroupAccept (Player *, Group *)
virtual bool OnPlayerCanSellItem (Player *, Item *, Creature *)
virtual bool OnPlayerCanSendMail (Player *, ObjectGuid, ObjectGuid, std::string &, std::string &, uint32, uint32, Item *)
virtual void OnPlayerPetitionBuy (Player *, Creature *, uint32 &, uint32 &, uint32 &)
virtual void OnPlayerPetitionShowList (Player *, Creature *, uint32 &, uint32 &, uint32 &)
virtual void OnPlayerRewardKillRewarder (Player *, KillRewarder *, bool, float &)
virtual bool OnPlayerCanGiveMailRewardAtGiveLevel (Player *, uint8)
virtual void OnPlayerDeleteFromDB (CharacterDatabaseTransaction, uint32)
virtual bool OnPlayerCanRepopAtGraveyard (Player *)
virtual Optional< bool > OnPlayerIsClass (Player const *, Classes, ClassContext)
virtual void OnPlayerGetMaxSkillValue (Player *, uint32, int32 &, bool)
virtual bool OnPlayerHasActivePowerType (Player const *, Powers)
virtual void OnPlayerUpdateGatheringSkill (Player *, uint32, uint32, uint32, uint32, uint32, uint32 &)
This hook called before gathering skill gain is applied to the character.
virtual void OnPlayerUpdateCraftingSkill (Player *, SkillLineAbilityEntry const *, uint32, uint32 &)
This hook is called before crafting skill gain is applied to the character.
virtual bool OnPlayerUpdateFishingSkill (Player *, int32, int32, int32, int32)
virtual bool OnPlayerCanAreaExploreAndOutdoor (Player *)
virtual void OnPlayerVictimRewardBefore (Player *, Player *, uint32 &, uint32 &)
virtual void OnPlayerVictimRewardAfter (Player *, Player *, uint32 &, uint32 &, float &)
virtual void OnPlayerCustomScalingStatValueBefore (Player *, ItemTemplate const *, uint8, bool, uint32 &)
virtual void OnPlayerCustomScalingStatValue (Player *, ItemTemplate const *, uint32 &, int32 &, uint8, uint32, ScalingStatValuesEntry const *)
virtual void OnPlayerApplyItemModsBefore (Player *, uint8, bool, uint8, uint32, int32 &)
virtual void OnPlayerApplyEnchantmentItemModsBefore (Player *, Item *, EnchantmentSlot, bool, uint32, uint32 &)
virtual void OnPlayerApplyWeaponDamage (Player *, uint8, ItemTemplate const *, float &, float &, uint8)
virtual bool OnPlayerCanArmorDamageModifier (Player *)
virtual void OnPlayerGetFeralApBonus (Player *, int32 &, int32, ItemTemplate const *, ScalingStatValuesEntry const *)
virtual bool OnPlayerCanApplyWeaponDependentAuraDamageMod (Player *, Item *, WeaponAttackType, AuraEffect const *, bool)
virtual bool OnPlayerCanApplyEquipSpell (Player *, SpellInfo const *, Item *, bool, bool)
virtual bool OnPlayerCanApplyEquipSpellsItemSet (Player *, ItemSetEffect *)
virtual bool OnPlayerCanCastItemCombatSpell (Player *, Unit *, WeaponAttackType, uint32, uint32, Item *, ItemTemplate const *)
virtual bool OnPlayerCanCastItemUseSpell (Player *, Item *, SpellCastTargets const &, uint8, uint32)
virtual void OnPlayerApplyAmmoBonuses (Player *, ItemTemplate const *, float &)
virtual bool OnPlayerCanEquipItem (Player *, uint8, uint16 &, Item *, bool, bool)
virtual bool OnPlayerCanUnequipItem (Player *, uint16, bool)
virtual bool OnPlayerCanUseItem (Player *, ItemTemplate const *, InventoryResult &)
virtual bool OnPlayerCanSaveEquipNewItem (Player *, Item *, uint16, bool)
virtual bool OnPlayerCanApplyEnchantment (Player *, Item *, EnchantmentSlot, bool, bool, bool)
virtual void OnPlayerGetQuestRate (Player *, float &)
virtual bool OnPlayerPassedQuestKilledMonsterCredit (Player *, Quest const *, uint32, uint32, ObjectGuid)
virtual bool OnPlayerCheckItemInSlotAtLoadInventory (Player *, Item *, uint8, uint8 &, uint16 &)
virtual bool OnPlayerNotAvoidSatisfy (Player *, DungeonProgressionRequirements const *, uint32, bool)
virtual bool OnPlayerNotVisibleGloballyFor (Player *, Player const *)
virtual void OnPlayerGetArenaPersonalRating (Player *, uint8, uint32 &)
virtual void OnPlayerGetArenaTeamId (Player *, uint8, uint32 &)
virtual void OnPlayerIsFFAPvP (Player *, bool &)
virtual void OnPlayerFfaPvpStateUpdate (Player *, bool)
virtual void OnPlayerIsPvP (Player *, bool &)
virtual void OnPlayerGetMaxSkillValueForLevel (Player *, uint16 &)
virtual bool OnPlayerNotSetArenaTeamInfoField (Player *, uint8, ArenaTeamInfoType, uint32)
virtual bool OnPlayerCanJoinLfg (Player *, uint8, std::set< uint32 > &, const std::string &)
virtual bool OnPlayerCanEnterMap (Player *, MapEntry const *, InstanceTemplate const *, MapDifficulty const *, bool)
virtual bool OnPlayerCanInitTrade (Player *, Player *)
virtual bool OnPlayerCanSetTradeItem (Player *, Item *, uint8)
This hook called just before finishing the handling of the action of a player setting an item in a trade slot.
virtual void OnPlayerSetServerSideVisibility (Player *, ServerSideVisibilityType &, AccountTypes &)
virtual void OnPlayerSetServerSideVisibilityDetect (Player *, ServerSideVisibilityType &, AccountTypes &)
virtual void OnPlayerResurrect (Player *, float, bool)
virtual void OnPlayerBeforeChooseGraveyard (Player *, TeamId, bool, uint32 &)
virtual bool OnPlayerCanUseChat (Player *, uint32, uint32, std::string &)
This hook called before player sending message in default chat.
virtual bool OnPlayerCanUseChat (Player *, uint32, uint32, std::string &, Player *)
This hook called before player sending message to other player via private.
virtual bool OnPlayerCanUseChat (Player *, uint32, uint32, std::string &, Group *)
This hook called before player sending message to group.
virtual bool OnPlayerCanUseChat (Player *, uint32, uint32, std::string &, Guild *)
This hook called before player sending message to guild.
virtual bool OnPlayerCanUseChat (Player *, uint32, uint32, std::string &, Channel *)
This hook called before player sending message to channel.
virtual void OnPlayerLearnTalents (Player *, uint32, uint32, uint32)
This hook called after player learning talents.
virtual void OnPlayerEnterCombat (Player *, Unit *)
This hook called after player entering combat.
virtual void OnPlayerLeaveCombat (Player *)
This hook called after player leave combat.
virtual void OnPlayerQuestAbandon (Player *, uint32)
This hook called after player abandoning quest.
virtual bool OnPlayerCanFlyInZone (Player *, uint32, uint32, SpellInfo const *)
This hook called before other CanFlyChecks are applied.
virtual void AnticheatSetCanFlybyServer (Player *, bool)
virtual void AnticheatSetUnderACKmount (Player *)
virtual void AnticheatSetRootACKUpd (Player *)
virtual void AnticheatSetJumpingbyOpcode (Player *, bool)
virtual void AnticheatUpdateMovementInfo (Player *, MovementInfo const &)
virtual bool AnticheatHandleDoubleJump (Player *, Unit *)
virtual bool AnticheatCheckMovementInfo (Player *, MovementInfo const &, Unit *, bool)
virtual bool OnPlayerCanSendErrorAlreadyLooted (Player *)
This hook is called, to avoid displaying the error message that the body has already been stripped.
virtual void OnPlayerAfterCreatureLoot (Player *)
It is used when an item is taken from a creature.
virtual void OnPlayerAfterCreatureLootMoney (Player *)
After a creature's money is taken.
virtual bool OnPlayerCanUpdateSkill (Player *, uint32)
virtual void OnPlayerBeforeUpdateSkill (Player *, uint32, uint32 &, uint32, uint32)
virtual void OnPlayerUpdateSkill (Player *, uint32, uint32, uint32, uint32, uint32)
virtual bool OnPlayerCanResurrect (Player *)
This hook is called, to avoid player resurrect.
virtual bool OnPlayerCanGiveLevel (Player *, uint8)
This hook is called, to cancel the normal level up flow.
virtual void OnPlayerSendListInventory (Player *, ObjectGuid, uint32 &)
This hook is called whenever a player interacts with a vendor, and is then shown the vendor list.
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
uint16 GetTotalAvailableHooks ()
Protected Member Functions
PlayerScript (const char *name, std::vector< uint16 > enabledHooks=std::vector< uint16 >())
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name, uint16 totalAvailableHooks=0)
virtual ~ScriptObject ()=default
Detailed Description
Constructor & Destructor Documentation
PlayerScript()
PlayerScript::PlayerScript (const char * name, std::vector< uint16 > enabledHooks = std::vector<uint16>()) protected
    : ScriptObject(name, PLAYERHOOK_END)
{
    // If empty - enable all available hooks.
    if (enabledHooks.empty())
        for (uint16 i = 0; i < PLAYERHOOK_END; ++i)
            enabledHooks.emplace_back(i);
    ScriptRegistry<PlayerScript>::AddScript(this, std::move(enabledHooks));
}
References ScriptRegistry< TScript >::AddScript(), and PLAYERHOOK_END.
Member Function Documentation
AnticheatCheckMovementInfo()
virtual bool PlayerScript::AnticheatCheckMovementInfo (Player * , MovementInfo const & , Unit * , bool) inline virtual
{ return true; }
Referenced by ScriptMgr::AnticheatCheckMovementInfo().
AnticheatHandleDoubleJump()
virtual bool PlayerScript::AnticheatHandleDoubleJump (Player * , Unit *) inline virtual
{ return true; }
Referenced by ScriptMgr::AnticheatHandleDoubleJump().
AnticheatSetCanFlybyServer()
virtual void PlayerScript::AnticheatSetCanFlybyServer (Player * , bool) inline virtual
{ }
Referenced by ScriptMgr::AnticheatSetCanFlybyServer().
AnticheatSetJumpingbyOpcode()
virtual void PlayerScript::AnticheatSetJumpingbyOpcode (Player * , bool) inline virtual
{ }
Referenced by ScriptMgr::AnticheatSetJumpingbyOpcode().
AnticheatSetRootACKUpd()
virtual void PlayerScript::AnticheatSetRootACKUpd (Player *) inline virtual
{ }
Referenced by ScriptMgr::AnticheatSetRootACKUpd().
AnticheatSetUnderACKmount()
virtual void PlayerScript::AnticheatSetUnderACKmount (Player *) inline virtual
{ }
Referenced by ScriptMgr::AnticheatSetUnderACKmount().
AnticheatUpdateMovementInfo()
virtual void PlayerScript::AnticheatUpdateMovementInfo (Player * , MovementInfo const &) inline virtual
{ }
Referenced by ScriptMgr::AnticheatUpdateMovementInfo().
OnPlayerAchievementComplete()
virtual void PlayerScript::OnPlayerAchievementComplete (Player * , AchievementEntry const *) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerAchievementComplete().
OnPlayerAchievementSave()
virtual void PlayerScript::OnPlayerAchievementSave (CharacterDatabaseTransaction , Player * , uint16 , CompletedAchievementData) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerAchievementSave().
OnPlayerAddToBattleground()
virtual void PlayerScript::OnPlayerAddToBattleground (Player * , Battleground *) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerAddToBattleground().
OnPlayerAfterCreatureLoot()
virtual void PlayerScript::OnPlayerAfterCreatureLoot (Player *) inline virtual
It is used when an item is taken from a creature.
Parameters
player Contains information about the Player
{ }
Referenced by ScriptMgr::OnPlayerAfterCreatureLoot().
OnPlayerAfterCreatureLootMoney()
virtual void PlayerScript::OnPlayerAfterCreatureLootMoney (Player *) inline virtual
After a creature's money is taken.
Parameters
player Contains information about the Player
{ }
Referenced by ScriptMgr::OnPlayerAfterCreatureLootMoney().
OnPlayerAfterGuardianInitStatsForLevel()
virtual void PlayerScript::OnPlayerAfterGuardianInitStatsForLevel (Player * , Guardian *) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerAfterGuardianInitStatsForLevel().
OnPlayerAfterMoveItemFromInventory()
virtual void PlayerScript::OnPlayerAfterMoveItemFromInventory (Player * , Item * , uint8 , uint8 , bool) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerAfterMoveItemFromInventory().
OnPlayerAfterSetVisibleItemSlot()
virtual void PlayerScript::OnPlayerAfterSetVisibleItemSlot (Player * , uint8 , Item *) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerAfterSetVisibleItemSlot().
OnPlayerAfterSpecSlotChanged()
virtual void PlayerScript::OnPlayerAfterSpecSlotChanged (Player * , uint8) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerAfterSpecSlotChanged().
OnPlayerAfterStoreOrEquipNewItem()
virtual void PlayerScript::OnPlayerAfterStoreOrEquipNewItem (Player * , uint32 , Item * , uint8 , uint8 , uint8 , ItemTemplate const * , Creature * , VendorItem const * , bool) inline virtual
{ };
Referenced by ScriptMgr::OnPlayerAfterStoreOrEquipNewItem().
OnPlayerAfterUpdateAttackPowerAndDamage()
virtual void PlayerScript::OnPlayerAfterUpdateAttackPowerAndDamage (Player * , float & , float & , float & , float & , bool) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerAfterUpdateAttackPowerAndDamage().
OnPlayerAfterUpdateMaxHealth()
virtual void PlayerScript::OnPlayerAfterUpdateMaxHealth (Player * , float &) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerAfterUpdateMaxHealth().
OnPlayerAfterUpdateMaxPower()
virtual void PlayerScript::OnPlayerAfterUpdateMaxPower (Player * , Powers & , float &) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerAfterUpdateMaxPower().
OnPlayerApplyAmmoBonuses()
virtual void PlayerScript::OnPlayerApplyAmmoBonuses (Player * , ItemTemplate const * , float &) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerApplyAmmoBonuses().
OnPlayerApplyEnchantmentItemModsBefore()
virtual void PlayerScript::OnPlayerApplyEnchantmentItemModsBefore (Player * , Item * , EnchantmentSlot , bool , uint32 , uint32 &) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerApplyEnchantmentItemModsBefore().
OnPlayerApplyItemModsBefore()
virtual void PlayerScript::OnPlayerApplyItemModsBefore (Player * , uint8 , bool , uint8 , uint32 , int32 &) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerApplyItemModsBefore().
OnPlayerApplyWeaponDamage()
virtual void PlayerScript::OnPlayerApplyWeaponDamage (Player * , uint8 , ItemTemplate const * , float & , float & , uint8) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerApplyWeaponDamage().
OnPlayerBattlegroundDesertion()
virtual void PlayerScript::OnPlayerBattlegroundDesertion (Player * , BattlegroundDesertionType const) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerBattlegroundDesertion().
OnPlayerBeforeAchievementComplete()
virtual bool PlayerScript::OnPlayerBeforeAchievementComplete (Player * , AchievementEntry const *) inline virtual
{ return true; }
Referenced by ScriptMgr::OnPlayerBeforeAchievementComplete().
OnPlayerBeforeBuyItemFromVendor()
virtual void PlayerScript::OnPlayerBeforeBuyItemFromVendor (Player * , ObjectGuid , uint32 , uint32 & , uint8 , uint8 , uint8) inline virtual
{ };
Referenced by ScriptMgr::OnPlayerBeforeBuyItemFromVendor().
OnPlayerBeforeChooseGraveyard()
virtual void PlayerScript::OnPlayerBeforeChooseGraveyard (Player * , TeamId , bool , uint32 &) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerBeforeChooseGraveyard().
OnPlayerBeforeCriteriaProgress()
virtual bool PlayerScript::OnPlayerBeforeCriteriaProgress (Player * , AchievementCriteriaEntry const *) inline virtual
{ return true; }
Referenced by ScriptMgr::OnPlayerBeforeCriteriaProgress().
OnPlayerBeforeDurabilityRepair()
virtual void PlayerScript::OnPlayerBeforeDurabilityRepair (Player * , ObjectGuid , ObjectGuid , float & , uint8) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerBeforeDurabilityRepair().
OnPlayerBeforeFillQuestLootItem()
virtual void PlayerScript::OnPlayerBeforeFillQuestLootItem (Player * , LootItem &) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerBeforeFillQuestLootItem().
OnPlayerBeforeGuardianInitStatsForLevel()
virtual void PlayerScript::OnPlayerBeforeGuardianInitStatsForLevel (Player * , Guardian * , CreatureTemplate const * , PetType &) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerBeforeGuardianInitStatsForLevel().
OnPlayerBeforeInitTalentForLevel()
virtual void PlayerScript::OnPlayerBeforeInitTalentForLevel (Player * , uint8 & , uint32 &) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerBeforeInitTalentForLevel().
OnPlayerBeforeLoadPetFromDB()
virtual void PlayerScript::OnPlayerBeforeLoadPetFromDB (Player * , uint32 & , uint32 & , bool & , bool &) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerBeforeLoadPetFromDB().
OnPlayerBeforeLogout()
virtual void PlayerScript::OnPlayerBeforeLogout (Player *) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerBeforeLogout().
OnPlayerBeforeLootMoney()
virtual void PlayerScript::OnPlayerBeforeLootMoney (Player * , Loot *) inline virtual
{}
Referenced by ScriptMgr::OnPlayerBeforeLootMoney().
OnPlayerBeforeOpenItem()
virtual bool PlayerScript::OnPlayerBeforeOpenItem (Player * , Item *) inline virtual
{ return true; }
Referenced by ScriptMgr::OnPlayerBeforeOpenItem().
OnPlayerBeforeQuestComplete()
virtual bool PlayerScript::OnPlayerBeforeQuestComplete (Player * , uint32) inline virtual
{ return true; }
Referenced by ScriptMgr::OnPlayerBeforeQuestComplete().
OnPlayerBeforeSendChatMessage()
virtual void PlayerScript::OnPlayerBeforeSendChatMessage (Player * , uint32 & , uint32 & , std::string &) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerBeforeSendChatMessage().
OnPlayerBeforeStoreOrEquipNewItem()
virtual void PlayerScript::OnPlayerBeforeStoreOrEquipNewItem (Player * , uint32 , uint32 & , uint8 , uint8 , uint8 , ItemTemplate const * , Creature * , VendorItem const * , bool) inline virtual
{ };
Referenced by ScriptMgr::OnPlayerBeforeStoreOrEquipNewItem().
OnPlayerBeforeTeleport()
virtual bool PlayerScript::OnPlayerBeforeTeleport (Player * , uint32 , float , float , float , float , uint32 , Unit *) inline virtual
{ return true; }
Referenced by ScriptMgr::OnPlayerBeforeTeleport().
OnPlayerBeforeTempSummonInitStats()
virtual void PlayerScript::OnPlayerBeforeTempSummonInitStats (Player * , TempSummon * , uint32 &) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerBeforeTempSummonInitStats().
OnPlayerBeforeUpdate()
virtual void PlayerScript::OnPlayerBeforeUpdate (Player * , uint32) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerBeforeUpdate().
OnPlayerBeforeUpdateAttackPowerAndDamage()
virtual void PlayerScript::OnPlayerBeforeUpdateAttackPowerAndDamage (Player * , float & , float & , bool) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerBeforeUpdateAttackPowerAndDamage().
OnPlayerBeforeUpdateSkill()
virtual void PlayerScript::OnPlayerBeforeUpdateSkill (Player * , uint32 , uint32 & , uint32 , uint32) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerBeforeUpdateSkill().
OnPlayerBeingCharmed()
virtual void PlayerScript::OnPlayerBeingCharmed (Player * , Unit * , uint32 , uint32) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerBeingCharmed().
OnPlayerBindToInstance()
virtual void PlayerScript::OnPlayerBindToInstance (Player * , Difficulty , uint32 , bool) inline virtual
Reimplemented in lfg::LFGPlayerScript.
{ }
Referenced by ScriptMgr::OnPlayerBindToInstance().
OnPlayerCalculateTalentsPoints()
virtual void PlayerScript::OnPlayerCalculateTalentsPoints (Player const * , uint32 &) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerCalculateTalentsPoints().
OnPlayerCanApplyEnchantment()
virtual bool PlayerScript::OnPlayerCanApplyEnchantment (Player * , Item * , EnchantmentSlot , bool , bool , bool) inline virtual
{ return true; }
Referenced by ScriptMgr::OnPlayerCanApplyEnchantment().
OnPlayerCanApplyEquipSpell()
virtual bool PlayerScript::OnPlayerCanApplyEquipSpell (Player * , SpellInfo const * , Item * , bool , bool) inline virtual
{ return true; }
Referenced by ScriptMgr::OnPlayerCanApplyEquipSpell().
OnPlayerCanApplyEquipSpellsItemSet()
virtual bool PlayerScript::OnPlayerCanApplyEquipSpellsItemSet (Player * , ItemSetEffect *) inline virtual
{ return true; }
Referenced by ScriptMgr::OnPlayerCanApplyEquipSpellsItemSet().
OnPlayerCanApplyWeaponDependentAuraDamageMod()
virtual bool PlayerScript::OnPlayerCanApplyWeaponDependentAuraDamageMod (Player * , Item * , WeaponAttackType , AuraEffect const * , bool) inline virtual
{ return true; }
Referenced by ScriptMgr::OnPlayerCanApplyWeaponDependentAuraDamageMod().
OnPlayerCanAreaExploreAndOutdoor()
virtual bool PlayerScript::OnPlayerCanAreaExploreAndOutdoor (Player *) inline virtual
{ return true; }
Referenced by ScriptMgr::OnPlayerCanAreaExploreAndOutdoor().
OnPlayerCanArmorDamageModifier()
virtual bool PlayerScript::OnPlayerCanArmorDamageModifier (Player *) inline virtual
{ return true; }
Referenced by ScriptMgr::OnPlayerCanArmorDamageModifier().
OnPlayerCanBattleFieldPort()
virtual bool PlayerScript::OnPlayerCanBattleFieldPort (Player * , uint8 , BattlegroundTypeId , uint8) inline virtual
{ return true; }
Referenced by ScriptMgr::OnPlayerCanBattleFieldPort().
OnPlayerCanCastItemCombatSpell()
virtual bool PlayerScript::OnPlayerCanCastItemCombatSpell (Player * , Unit * , WeaponAttackType , uint32 , uint32 , Item * , ItemTemplate const *) inline virtual
{ return true; }
Referenced by ScriptMgr::OnPlayerCanCastItemCombatSpell().
OnPlayerCanCastItemUseSpell()
virtual bool PlayerScript::OnPlayerCanCastItemUseSpell (Player * , Item * , SpellCastTargets const & , uint8 , uint32) inline virtual
{ return true; }
Referenced by ScriptMgr::OnPlayerCanCastItemUseSpell().
OnPlayerCanEnterMap()
virtual bool PlayerScript::OnPlayerCanEnterMap (Player * , MapEntry const * , InstanceTemplate const * , MapDifficulty const * , bool) inline virtual
{ return true; }
Referenced by ScriptMgr::OnPlayerCanEnterMap().
OnPlayerCanEquipItem()
virtual bool PlayerScript::OnPlayerCanEquipItem (Player * , uint8 , uint16 & , Item * , bool , bool) inline virtual
{ return true; }
Referenced by ScriptMgr::OnPlayerCanEquipItem().
OnPlayerCanFlyInZone()
virtual bool PlayerScript::OnPlayerCanFlyInZone (Player * , uint32 , uint32 , SpellInfo const *) inline virtual
This hook called before other CanFlyChecks are applied.
Parameters
player Contains information about the Player
mapId Contains information about the current map id
zoneId Contains information about the current zone
bySpell Contains information about the spell that invoked the check
{ return true; }
Referenced by ScriptMgr::OnPlayerCanFlyInZone().
OnPlayerCanGiveLevel()
virtual bool PlayerScript::OnPlayerCanGiveLevel (Player * , uint8) inline virtual
This hook is called, to cancel the normal level up flow.
Parameters
player Contains information about the Player
newLevel The new level the player is about to be given
Returns
true if player is allowed to gain the new level
{ return true; }
Referenced by ScriptMgr::OnPlayerCanGiveLevel().
OnPlayerCanGiveMailRewardAtGiveLevel()
virtual bool PlayerScript::OnPlayerCanGiveMailRewardAtGiveLevel (Player * , uint8) inline virtual
{ return true; }
Referenced by ScriptMgr::OnPlayerCanGiveMailRewardAtGiveLevel().
OnPlayerCanGroupAccept()
virtual bool PlayerScript::OnPlayerCanGroupAccept (Player * , Group *) inline virtual
{ return true; }
Referenced by ScriptMgr::OnPlayerCanGroupAccept().
OnPlayerCanGroupInvite()
virtual bool PlayerScript::OnPlayerCanGroupInvite (Player * , std::string &) inline virtual
{ return true; }
Referenced by ScriptMgr::OnPlayerCanGroupInvite().
OnPlayerCanInitTrade()
virtual bool PlayerScript::OnPlayerCanInitTrade (Player * , Player *) inline virtual
{ return true; }
Referenced by ScriptMgr::OnPlayerCanInitTrade().
OnPlayerCanJoinInArenaQueue()
virtual bool PlayerScript::OnPlayerCanJoinInArenaQueue (Player * , ObjectGuid , uint8 , BattlegroundTypeId , uint8 , uint8 , GroupJoinBattlegroundResult &) inline virtual
{ return true; }
Referenced by ScriptMgr::OnPlayerCanJoinInArenaQueue().
OnPlayerCanJoinInBattlegroundQueue()
virtual bool PlayerScript::OnPlayerCanJoinInBattlegroundQueue (Player * , ObjectGuid , BattlegroundTypeId , uint8 , GroupJoinBattlegroundResult &) inline virtual
{ return true; }
Referenced by ScriptMgr::OnPlayerCanJoinInBattlegroundQueue().
OnPlayerCanJoinLfg()
virtual bool PlayerScript::OnPlayerCanJoinLfg (Player * , uint8 , std::set< uint32 > & , const std::string &) inline virtual
{ return true; }
Referenced by ScriptMgr::OnPlayerCanJoinLfg().
OnPlayerCanPlaceAuctionBid()
virtual bool PlayerScript::OnPlayerCanPlaceAuctionBid (Player * , AuctionEntry *) inline virtual
{ return true; }
Referenced by ScriptMgr::OnPlayerCanPlaceAuctionBid().
OnPlayerCanRepopAtGraveyard()
virtual bool PlayerScript::OnPlayerCanRepopAtGraveyard (Player *) inline virtual
{ return true; }
Referenced by ScriptMgr::OnPlayerCanRepopAtGraveyard().
OnPlayerCanResurrect()
virtual bool PlayerScript::OnPlayerCanResurrect (Player *) inline virtual
This hook is called, to avoid player resurrect.
Parameters
player Contains information about the Player
Returns
true if player is authorized to resurect
{ return true; }
Referenced by ScriptMgr::OnPlayerCanResurrect().
OnPlayerCanSaveEquipNewItem()
virtual bool PlayerScript::OnPlayerCanSaveEquipNewItem (Player * , Item * , uint16 , bool) inline virtual
{ return true; }
Referenced by ScriptMgr::OnPlayerCanSaveEquipNewItem().
OnPlayerCanSellItem()
virtual bool PlayerScript::OnPlayerCanSellItem (Player * , Item * , Creature *) inline virtual
{ return true; }
Referenced by ScriptMgr::OnPlayerCanSellItem().
OnPlayerCanSendErrorAlreadyLooted()
virtual bool PlayerScript::OnPlayerCanSendErrorAlreadyLooted (Player *) inline virtual
This hook is called, to avoid displaying the error message that the body has already been stripped.
Parameters
player Contains information about the Player
Returns
true Avoiding displaying the error message that the loot has already been taken.
{ return true; }
Referenced by ScriptMgr::OnPlayerCanSendErrorAlreadyLooted().
OnPlayerCanSendMail()
virtual bool PlayerScript::OnPlayerCanSendMail (Player * , ObjectGuid , ObjectGuid , std::string & , std::string & , uint32 , uint32 , Item *) inline virtual
{ return true; }
Referenced by ScriptMgr::OnPlayerCanSendMail().
OnPlayerCanSetTradeItem()
virtual bool PlayerScript::OnPlayerCanSetTradeItem (Player * , Item * , uint8) inline virtual
This hook called just before finishing the handling of the action of a player setting an item in a trade slot.
Parameters
player Contains information about the trade initiator Player
tradedItem Contains information about the item set in the trade slot
Returns
True if you want to continue setting the item in the trade slot, false if you want to cancel the trade
{ return true; }
Referenced by ScriptMgr::OnPlayerCanSetTradeItem().
OnPlayerCanUnequipItem()
virtual bool PlayerScript::OnPlayerCanUnequipItem (Player * , uint16 , bool) inline virtual
{ return true; }
Referenced by ScriptMgr::OnPlayerCanUnequipItem().
OnPlayerCanUpdateSkill()
virtual bool PlayerScript::OnPlayerCanUpdateSkill (Player * , uint32) inline virtual
{ return true; }
Referenced by ScriptMgr::OnPlayerCanUpdateSkill().
OnPlayerCanUseChat() [1/5]
virtual bool PlayerScript::OnPlayerCanUseChat (Player * , uint32 , uint32 , std::string &) inline virtual
This hook called before player sending message in default chat.
Parameters
player Contains information about the Player sender
type Contains information about the chat message type
language Contains information about the language type
msg Contains information about the message
Returns
True if you want to continue sending the message, false if you want to disable sending the message
{ return true; }
Referenced by ScriptMgr::OnPlayerCanUseChat(), ScriptMgr::OnPlayerCanUseChat(), ScriptMgr::OnPlayerCanUseChat(), ScriptMgr::OnPlayerCanUseChat(), and ScriptMgr::OnPlayerCanUseChat().
OnPlayerCanUseChat() [2/5]
virtual bool PlayerScript::OnPlayerCanUseChat (Player * , uint32 , uint32 , std::string & , Channel *) inline virtual
This hook called before player sending message to channel.
Parameters
player Contains information about the Player sender
type Contains information about the chat message type
language Contains information about the language type
msg Contains information about the message
channel Contains information about the Channel
Returns
True if you want to continue sending the message, false if you want to disable sending the message
{ return true; }
OnPlayerCanUseChat() [3/5]
virtual bool PlayerScript::OnPlayerCanUseChat (Player * , uint32 , uint32 , std::string & , Group *) inline virtual
This hook called before player sending message to group.
Parameters
player Contains information about the Player sender
type Contains information about the chat message type
language Contains information about the language type
msg Contains information about the message
group Contains information about the Group
Returns
True if you want to continue sending the message, false if you want to disable sending the message
{ return true; }
OnPlayerCanUseChat() [4/5]
virtual bool PlayerScript::OnPlayerCanUseChat (Player * , uint32 , uint32 , std::string & , Guild *) inline virtual
This hook called before player sending message to guild.
Parameters
player Contains information about the Player sender
type Contains information about the chat message type
language Contains information about the language type
msg Contains information about the message
guild Contains information about the Guild
Returns
True if you want to continue sending the message, false if you want to disable sending the message
{ return true; }
OnPlayerCanUseChat() [5/5]
virtual bool PlayerScript::OnPlayerCanUseChat (Player * , uint32 , uint32 , std::string & , Player *) inline virtual
This hook called before player sending message to other player via private.
Parameters
player Contains information about the Player sender
type Contains information about the chat message type
language Contains information about the language type
msg Contains information about the message
receiver Contains information about the Player receiver
Returns
True if you want to continue sending the message, false if you want to disable sending the message
{ return true; }
OnPlayerCanUseItem()
virtual bool PlayerScript::OnPlayerCanUseItem (Player * , ItemTemplate const * , InventoryResult &) inline virtual
{ return true; }
Referenced by ScriptMgr::OnPlayerCanUseItem().
OnPlayerChat() [1/5]
virtual void PlayerScript::OnPlayerChat (Player * , uint32 , uint32 , std::string &) inline virtual
Reimplemented in ChatLogScript.
{ }
Referenced by ScriptMgr::OnPlayerChat(), ScriptMgr::OnPlayerChat(), ScriptMgr::OnPlayerChat(), ScriptMgr::OnPlayerChat(), and ScriptMgr::OnPlayerChat().
OnPlayerChat() [2/5]
virtual void PlayerScript::OnPlayerChat (Player * , uint32 , uint32 , std::string & , Channel *) inline virtual
Reimplemented in ChatLogScript.
{ }
OnPlayerChat() [3/5]
virtual void PlayerScript::OnPlayerChat (Player * , uint32 , uint32 , std::string & , Group *) inline virtual
Reimplemented in ChatLogScript.
{ }
OnPlayerChat() [4/5]
virtual void PlayerScript::OnPlayerChat (Player * , uint32 , uint32 , std::string & , Guild *) inline virtual
Reimplemented in ChatLogScript.
{ }
OnPlayerChat() [5/5]
virtual void PlayerScript::OnPlayerChat (Player * , uint32 , uint32 , std::string & , Player *) inline virtual
Reimplemented in ChatLogScript.
{ }
OnPlayerCheckItemInSlotAtLoadInventory()
virtual bool PlayerScript::OnPlayerCheckItemInSlotAtLoadInventory (Player * , Item * , uint8 , uint8 & , uint16 &) inline virtual
{ return true; }
Referenced by ScriptMgr::OnPlayerCheckItemInSlotAtLoadInventory().
OnPlayerCompleteQuest()
virtual void PlayerScript::OnPlayerCompleteQuest (Player * , Quest const *) inline virtual
Reimplemented in QuestApprenticeAnglerPlayerScript.
{ }
Referenced by ScriptMgr::OnPlayerCompleteQuest().
OnPlayerCreate()
virtual void PlayerScript::OnPlayerCreate (Player *) inline virtual
Reimplemented in CharacterActionIpLogger.
{ }
Referenced by ScriptMgr::OnPlayerCreate().
OnPlayerCreateItem()
virtual void PlayerScript::OnPlayerCreateItem (Player * , Item * , uint32) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerCreateItem().
OnPlayerCreatureKill()
virtual void PlayerScript::OnPlayerCreatureKill (Player * , Creature *) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerCreatureKill().
OnPlayerCreatureKilledByPet()
virtual void PlayerScript::OnPlayerCreatureKilledByPet (Player * , Creature *) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerCreatureKilledByPet().
OnPlayerCriteriaProgress()
virtual void PlayerScript::OnPlayerCriteriaProgress (Player * , AchievementCriteriaEntry const *) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerCriteriaProgress().
OnPlayerCriteriaSave()
virtual void PlayerScript::OnPlayerCriteriaSave (CharacterDatabaseTransaction , Player * , uint16 , CriteriaProgress) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerCriteriaSave().
OnPlayerCustomScalingStatValue()
virtual void PlayerScript::OnPlayerCustomScalingStatValue (Player * , ItemTemplate const * , uint32 & , int32 & , uint8 , uint32 , ScalingStatValuesEntry const *) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerCustomScalingStatValue().
OnPlayerCustomScalingStatValueBefore()
virtual void PlayerScript::OnPlayerCustomScalingStatValueBefore (Player * , ItemTemplate const * , uint8 , bool , uint32 &) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerCustomScalingStatValueBefore().
OnPlayerDelete()
virtual void PlayerScript::OnPlayerDelete (ObjectGuid , uint32) inline virtual
Reimplemented in CharacterDeleteActionIpLogger.
{ }
Referenced by ScriptMgr::OnPlayerDelete().
OnPlayerDeleteFromDB()
virtual void PlayerScript::OnPlayerDeleteFromDB (CharacterDatabaseTransaction , uint32) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerDeleteFromDB().
OnPlayerDuelEnd()
virtual void PlayerScript::OnPlayerDuelEnd (Player * , Player * , DuelCompleteType) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerDuelEnd().
OnPlayerDuelRequest()
virtual void PlayerScript::OnPlayerDuelRequest (Player * , Player *) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerDuelRequest().
OnPlayerDuelStart()
virtual void PlayerScript::OnPlayerDuelStart (Player * , Player *) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerDuelStart().
OnPlayerEmote()
virtual void PlayerScript::OnPlayerEmote (Player * , uint32) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerEmote().
OnPlayerEnterCombat()
virtual void PlayerScript::OnPlayerEnterCombat (Player * , Unit *) inline virtual
This hook called after player entering combat.
Parameters
player Contains information about the Player
Unit Contains information about the Unit
{ }
Referenced by ScriptMgr::OnPlayerEnterCombat().
OnPlayerEquip()
virtual void PlayerScript::OnPlayerEquip (Player * , Item * , uint8 , uint8 , bool) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerEquip().
OnPlayerFailedDelete()
virtual void PlayerScript::OnPlayerFailedDelete (ObjectGuid , uint32) inline virtual
Reimplemented in CharacterDeleteActionIpLogger.
{ }
Referenced by ScriptMgr::OnPlayerFailedDelete().
OnPlayerFfaPvpStateUpdate()
virtual void PlayerScript::OnPlayerFfaPvpStateUpdate (Player * , bool) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerFfaPvpStateUpdate().
OnPlayerFirstLogin()
virtual void PlayerScript::OnPlayerFirstLogin (Player *) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerFirstLogin().
OnPlayerForgotSpell()
virtual void PlayerScript::OnPlayerForgotSpell (Player * , uint32) inline virtual
{}
Referenced by ScriptMgr::OnPlayerForgotSpell().
OnPlayerFreeTalentPointsChanged()
virtual void PlayerScript::OnPlayerFreeTalentPointsChanged (Player * , uint32) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerFreeTalentPointsChanged().
OnPlayerGetArenaPersonalRating()
virtual void PlayerScript::OnPlayerGetArenaPersonalRating (Player * , uint8 , uint32 &) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerGetArenaPersonalRating().
OnPlayerGetArenaTeamId()
virtual void PlayerScript::OnPlayerGetArenaTeamId (Player * , uint8 , uint32 &) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerGetArenaTeamId().
OnPlayerGetFeralApBonus()
virtual void PlayerScript::OnPlayerGetFeralApBonus (Player * , int32 & , int32 , ItemTemplate const * , ScalingStatValuesEntry const *) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerGetFeralApBonus().
OnPlayerGetMaxPersonalArenaRatingRequirement()
virtual void PlayerScript::OnPlayerGetMaxPersonalArenaRatingRequirement (Player const * , uint32 , uint32 &) const inline virtual
{}
Referenced by ScriptMgr::OnPlayerGetMaxPersonalArenaRatingRequirement().
OnPlayerGetMaxSkillValue()
virtual void PlayerScript::OnPlayerGetMaxSkillValue (Player * , uint32 , int32 & , bool) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerGetMaxSkillValue().
OnPlayerGetMaxSkillValueForLevel()
virtual void PlayerScript::OnPlayerGetMaxSkillValueForLevel (Player * , uint16 &) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerGetMaxSkillValueForLevel().
OnPlayerGetQuestRate()
virtual void PlayerScript::OnPlayerGetQuestRate (Player * , float &) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerGetQuestRate().
OnPlayerGiveXP()
virtual void PlayerScript::OnPlayerGiveXP (Player * , uint32 & , Unit * , uint8) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerGiveXP().
OnPlayerGossipSelect()
virtual void PlayerScript::OnPlayerGossipSelect (Player * , uint32 , uint32 , uint32) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerGossipSelect().
OnPlayerGossipSelectCode()
virtual void PlayerScript::OnPlayerGossipSelectCode (Player * , uint32 , uint32 , uint32 , const char *) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerGossipSelectCode().
OnPlayerGroupRollRewardItem()
virtual void PlayerScript::OnPlayerGroupRollRewardItem (Player * , Item * , uint32 , RollVote , Roll *) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerGroupRollRewardItem().
OnPlayerHasActivePowerType()
virtual bool PlayerScript::OnPlayerHasActivePowerType (Player const * , Powers) inline virtual
{ return false; }
Referenced by ScriptMgr::OnPlayerHasActivePowerType().
OnPlayerIsClass()
virtual Optional< bool > PlayerScript::OnPlayerIsClass (Player const * , Classes , ClassContext) inline virtual
{ return std::nullopt; }
OnPlayerIsFFAPvP()
virtual void PlayerScript::OnPlayerIsFFAPvP (Player * , bool &) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerIsFFAPvP().
OnPlayerIsPvP()
virtual void PlayerScript::OnPlayerIsPvP (Player * , bool &) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerIsPvP().
OnPlayerJoinArena()
virtual void PlayerScript::OnPlayerJoinArena (Player *) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerJoinArena().
OnPlayerJoinBG()
virtual void PlayerScript::OnPlayerJoinBG (Player *) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerJoinBG().
OnPlayerJustDied()
virtual void PlayerScript::OnPlayerJustDied (Player *) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerJustDied().
OnPlayerKilledByCreature()
virtual void PlayerScript::OnPlayerKilledByCreature (Creature * , Player *) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerKilledByCreature().
OnPlayerLearnSpell()
virtual void PlayerScript::OnPlayerLearnSpell (Player * , uint32) inline virtual
{}
Referenced by ScriptMgr::OnPlayerLearnSpell().
OnPlayerLearnTalents()
virtual void PlayerScript::OnPlayerLearnTalents (Player * , uint32 , uint32 , uint32) inline virtual
This hook called after player learning talents.
Parameters
player Contains information about the Player
talentId Contains information about the talent id
talentRank Contains information about the talent rank
spellid Contains information about the spell id
{ }
Referenced by ScriptMgr::OnPlayerLearnTalents().
OnPlayerLeaveCombat()
virtual void PlayerScript::OnPlayerLeaveCombat (Player *) inline virtual
This hook called after player leave combat.
Parameters
player Contains information about the Player
{ }
Referenced by ScriptMgr::OnPlayerLeaveCombat().
OnPlayerLevelChanged()
virtual void PlayerScript::OnPlayerLevelChanged (Player * , uint8) inline virtual
Reimplemented in lfg::LFGPlayerScript.
{ }
Referenced by ScriptMgr::OnPlayerLevelChanged().
OnPlayerLoadFromDB()
virtual void PlayerScript::OnPlayerLoadFromDB (Player *) inline virtual
{ };
Referenced by ScriptMgr::OnPlayerLoadFromDB().
OnPlayerLogin()
virtual void PlayerScript::OnPlayerLogin (Player *) inline virtual
Reimplemented in lfg::LFGPlayerScript, CharacterActionIpLogger, and ServerMailReward.
{ }
Referenced by ScriptMgr::OnPlayerLogin().
OnPlayerLogout()
virtual void PlayerScript::OnPlayerLogout (Player *) inline virtual
Reimplemented in lfg::LFGPlayerScript, and CharacterActionIpLogger.
{ }
Referenced by ScriptMgr::OnPlayerLogout().
OnPlayerLootItem()
virtual void PlayerScript::OnPlayerLootItem (Player * , Item * , uint32 , ObjectGuid) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerLootItem().
OnPlayerMapChanged()
virtual void PlayerScript::OnPlayerMapChanged (Player *) inline virtual
Reimplemented in lfg::LFGPlayerScript.
{ }
Referenced by ScriptMgr::OnPlayerEnterMap().
OnPlayerMoneyChanged()
virtual void PlayerScript::OnPlayerMoneyChanged (Player * , int32 &) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerMoneyChanged().
OnPlayerNotAvoidSatisfy()
virtual bool PlayerScript::OnPlayerNotAvoidSatisfy (Player * , DungeonProgressionRequirements const * , uint32 , bool) inline virtual
{ return true; }
Referenced by ScriptMgr::OnPlayerNotAvoidSatisfy().
OnPlayerNotSetArenaTeamInfoField()
virtual bool PlayerScript::OnPlayerNotSetArenaTeamInfoField (Player * , uint8 , ArenaTeamInfoType , uint32) inline virtual
{ return true; } // Whats that?
Referenced by ScriptMgr::OnPlayerNotSetArenaTeamInfoField().
OnPlayerNotVisibleGloballyFor()
virtual bool PlayerScript::OnPlayerNotVisibleGloballyFor (Player * , Player const *) inline virtual
{ return true; } // Whats that?
Referenced by ScriptMgr::OnPlayerNotVisibleGloballyFor().
OnPlayerPassedQuestKilledMonsterCredit()
virtual bool PlayerScript::OnPlayerPassedQuestKilledMonsterCredit (Player * , Quest const * , uint32 , uint32 , ObjectGuid) inline virtual
{ return true; }
Referenced by ScriptMgr::OnPlayerPassedQuestKilledMonsterCredit().
OnPlayerPetitionBuy()
virtual void PlayerScript::OnPlayerPetitionBuy (Player * , Creature * , uint32 & , uint32 & , uint32 &) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerPetitionBuy().
OnPlayerPetitionShowList()
virtual void PlayerScript::OnPlayerPetitionShowList (Player * , Creature * , uint32 & , uint32 & , uint32 &) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerPetitionShowList().
OnPlayerPVPFlagChange()
virtual void PlayerScript::OnPlayerPVPFlagChange (Player * , bool) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerPVPFlagChange().
OnPlayerPVPKill()
virtual void PlayerScript::OnPlayerPVPKill (Player * , Player *) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerPVPKill().
OnPlayerQuestAbandon()
virtual void PlayerScript::OnPlayerQuestAbandon (Player * , uint32) inline virtual
This hook called after player abandoning quest.
Parameters
player Contains information about the Player
questId Contains information about the quest id
{ }
Referenced by ScriptMgr::OnPlayerQuestAbandon().
OnPlayerQuestComputeXP()
virtual void PlayerScript::OnPlayerQuestComputeXP (Player * , Quest const * , uint32 &) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerQuestComputeXP().
OnPlayerQuestRewardItem()
virtual void PlayerScript::OnPlayerQuestRewardItem (Player * , Item * , uint32) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerQuestRewardItem().
OnPlayerQueueRandomDungeon()
virtual void PlayerScript::OnPlayerQueueRandomDungeon (Player * , uint32 &) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerQueueRandomDungeon().
OnPlayerReleasedGhost()
virtual void PlayerScript::OnPlayerReleasedGhost (Player *) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerReleasedGhost().
OnPlayerRemoveFromBattleground()
virtual void PlayerScript::OnPlayerRemoveFromBattleground (Player * , Battleground *) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerRemoveFromBattleground().
OnPlayerReputationChange()
virtual bool PlayerScript::OnPlayerReputationChange (Player * , uint32 , int32 & , bool) inline virtual
{ return true; }
Referenced by ScriptMgr::OnPlayerReputationChange().
OnPlayerReputationRankChange()
virtual void PlayerScript::OnPlayerReputationRankChange (Player * , uint32 , ReputationRank , ReputationRank , bool) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerReputationRankChange().
OnPlayerResurrect()
virtual void PlayerScript::OnPlayerResurrect (Player * , float , bool) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerResurrect().
OnPlayerRewardKillRewarder()
virtual void PlayerScript::OnPlayerRewardKillRewarder (Player * , KillRewarder * , bool , float &) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerRewardKillRewarder().
OnPlayerSave()
virtual void PlayerScript::OnPlayerSave (Player *) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerSave().
OnPlayerSendInitialPacketsBeforeAddToMap()
virtual void PlayerScript::OnPlayerSendInitialPacketsBeforeAddToMap (Player * , WorldPacket &) inline virtual
{}
Referenced by ScriptMgr::OnPlayerSendInitialPacketsBeforeAddToMap().
OnPlayerSendListInventory()
virtual void PlayerScript::OnPlayerSendListInventory (Player * , ObjectGuid , uint32 &) inline virtual
This hook is called whenever a player interacts with a vendor, and is then shown the vendor list.
Parameters
player Contains information about the Player
vendorGuid Guid of the vendor player is interacting with
vendorEntry Entry of the vendor player is interacting with
{}
Referenced by ScriptMgr::OnPlayerSendListInventory().
OnPlayerSetMaxLevel()
virtual void PlayerScript::OnPlayerSetMaxLevel (Player * , uint32 &) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerSetMaxLevel().
OnPlayerSetServerSideVisibility()
virtual void PlayerScript::OnPlayerSetServerSideVisibility (Player * , ServerSideVisibilityType & , AccountTypes &) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerSetServerSideVisibility().
OnPlayerSetServerSideVisibilityDetect()
virtual void PlayerScript::OnPlayerSetServerSideVisibilityDetect (Player * , ServerSideVisibilityType & , AccountTypes &) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerSetServerSideVisibilityDetect().
OnPlayerShouldBeRewardedWithMoneyInsteadOfExp()
virtual bool PlayerScript::OnPlayerShouldBeRewardedWithMoneyInsteadOfExp (Player *) inline virtual
{ return false; }
Referenced by ScriptMgr::OnPlayerShouldBeRewardedWithMoneyInsteadOfExp().
OnPlayerSpellCast()
virtual void PlayerScript::OnPlayerSpellCast (Player * , Spell * , bool) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerSpellCast().
OnPlayerStoreNewItem()
virtual void PlayerScript::OnPlayerStoreNewItem (Player * , Item * , uint32) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerStoreNewItem().
OnPlayerTalentsReset()
virtual void PlayerScript::OnPlayerTalentsReset (Player * , bool) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerTalentsReset().
OnPlayerTextEmote()
virtual void PlayerScript::OnPlayerTextEmote (Player * , uint32 , uint32 , ObjectGuid) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerTextEmote().
OnPlayerUpdate()
virtual void PlayerScript::OnPlayerUpdate (Player * , uint32) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerUpdate().
OnPlayerUpdateArea()
virtual void PlayerScript::OnPlayerUpdateArea (Player * , uint32 , uint32) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerUpdateArea().
OnPlayerUpdateCraftingSkill()
virtual void PlayerScript::OnPlayerUpdateCraftingSkill (Player * , SkillLineAbilityEntry const * , uint32 , uint32 &) inline virtual
This hook is called before crafting skill gain is applied to the character.
Parameters
player Contains information about the Player sender
skill Contains information about the skill line
current_level Contains the current skill level for skill
gain Contains the amount of points that should be added to the Player
{ }
Referenced by ScriptMgr::OnPlayerUpdateCraftingSkill().
OnPlayerUpdateFaction()
virtual void PlayerScript::OnPlayerUpdateFaction (Player *) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerUpdateFaction().
OnPlayerUpdateFishingSkill()
virtual bool PlayerScript::OnPlayerUpdateFishingSkill (Player * , int32 , int32 , int32 , int32) inline virtual
{ return true; }
Referenced by ScriptMgr::OnPlayerUpdateFishingSkill().
OnPlayerUpdateGatheringSkill()
virtual void PlayerScript::OnPlayerUpdateGatheringSkill (Player * , uint32 , uint32 , uint32 , uint32 , uint32 , uint32 &) inline virtual
This hook called before gathering skill gain is applied to the character.
Parameters
player Contains information about the Player sender
skill_id Contains information about the skill line
current Contains the current skill level for skill
gray Contains the gray skill level for current application
green Contains the green skill level for current application
yellow Contains the yellow skill level for current application
gain Contains the amount of points that should be added to the Player
{ }
Referenced by ScriptMgr::OnPlayerUpdateGatheringSkill().
OnPlayerUpdateSkill()
virtual void PlayerScript::OnPlayerUpdateSkill (Player * , uint32 , uint32 , uint32 , uint32 , uint32) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerUpdateSkill().
OnPlayerUpdateZone()
virtual void PlayerScript::OnPlayerUpdateZone (Player * , uint32 , uint32) inline virtual
Reimplemented in MidsummerPlayerScript.
{ }
Referenced by ScriptMgr::OnPlayerUpdateZone().
OnPlayerVictimRewardAfter()
virtual void PlayerScript::OnPlayerVictimRewardAfter (Player * , Player * , uint32 & , uint32 & , float &) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerVictimRewardAfter().
OnPlayerVictimRewardBefore()
virtual void PlayerScript::OnPlayerVictimRewardBefore (Player * , Player * , uint32 & , uint32 &) inline virtual
{ }
Referenced by ScriptMgr::OnPlayerVictimRewardBefore().
The documentation for this class was generated from the following files:
azerothcore-wotlk/src/server/game/Scripting/ScriptDefines/PlayerScript.h
azerothcore-wotlk/src/server/game/Scripting/ScriptDefines/PlayerScript.cpp