AzerothCore Doxygen
DamageInfoStubBuilder Class Reference
Builder for creating DamageInfoStub instances with fluent API.
#include "DamageHealInfoStub.h"
Public Member Functions
DamageInfoStubBuilder ()=default
DamageInfoStubBuilder & WithDamage (uint32_t damage)
DamageInfoStubBuilder & WithOriginalDamage (uint32_t damage)
DamageInfoStubBuilder & WithSchoolMask (uint32_t schoolMask)
DamageInfoStubBuilder & WithAttackType (uint8_t attackType)
DamageInfoStubBuilder & WithSpellInfo (SpellInfo const *spellInfo)
DamageInfoStubBuilder & WithAbsorb (uint32_t absorb)
DamageInfoStubBuilder & WithResist (uint32_t resist)
DamageInfoStubBuilder & WithBlock (uint32_t block)
DamageInfoStubBuilder & WithHitMask (uint32_t hitMask)
DamageInfoStub Build ()
Private Attributes
DamageInfoStub _stub
Detailed Description
Builder for creating DamageInfoStub instances with fluent API.
Constructor & Destructor Documentation
DamageInfoStubBuilder()
DamageInfoStubBuilder::DamageInfoStubBuilder () default
Member Function Documentation
Build()
DamageInfoStub DamageInfoStubBuilder::Build () inline
{ return _stub; }
References _stub.
WithAbsorb()
DamageInfoStubBuilder & DamageInfoStubBuilder::WithAbsorb (uint32_t absorb) inline
    {
        _stub.SetAbsorb(absorb);
        return *this;
    }
References _stub, and DamageInfoStub::SetAbsorb().
WithAttackType()
DamageInfoStubBuilder & DamageInfoStubBuilder::WithAttackType (uint8_t attackType) inline
    {
        _stub.SetAttackType(attackType);
        return *this;
    }
References _stub, and DamageInfoStub::SetAttackType().
WithBlock()
DamageInfoStubBuilder & DamageInfoStubBuilder::WithBlock (uint32_t block) inline
    {
        _stub.SetBlock(block);
        return *this;
    }
References _stub, and DamageInfoStub::SetBlock().
WithDamage()
DamageInfoStubBuilder & DamageInfoStubBuilder::WithDamage (uint32_t damage) inline
    {
        _stub.SetDamage(damage);
        _stub.SetOriginalDamage(damage);
        return *this;
    }
References _stub, DamageInfoStub::SetDamage(), and DamageInfoStub::SetOriginalDamage().
WithHitMask()
DamageInfoStubBuilder & DamageInfoStubBuilder::WithHitMask (uint32_t hitMask) inline
    {
        _stub.SetHitMask(hitMask);
        return *this;
    }
References _stub, and DamageInfoStub::SetHitMask().
WithOriginalDamage()
DamageInfoStubBuilder & DamageInfoStubBuilder::WithOriginalDamage (uint32_t damage) inline
    {
        _stub.SetOriginalDamage(damage);
        return *this;
    }
References _stub, and DamageInfoStub::SetOriginalDamage().
WithResist()
DamageInfoStubBuilder & DamageInfoStubBuilder::WithResist (uint32_t resist) inline
    {
        _stub.SetResist(resist);
        return *this;
    }
References _stub, and DamageInfoStub::SetResist().
WithSchoolMask()
DamageInfoStubBuilder & DamageInfoStubBuilder::WithSchoolMask (uint32_t schoolMask) inline
    {
        _stub.SetSchoolMask(schoolMask);
        return *this;
    }
References _stub, and DamageInfoStub::SetSchoolMask().
WithSpellInfo()
DamageInfoStubBuilder & DamageInfoStubBuilder::WithSpellInfo (SpellInfo const * spellInfo) inline
    {
        _stub.SetSpellInfo(spellInfo);
        return *this;
    }
References _stub, and DamageInfoStub::SetSpellInfo().
Member Data Documentation
_stub
DamageInfoStub DamageInfoStubBuilder::_stub private
Referenced by Build(), WithAbsorb(), WithAttackType(), WithBlock(), WithDamage(), WithHitMask(), WithOriginalDamage(), WithResist(), WithSchoolMask(), and WithSpellInfo().
The documentation for this class was generated from the following file:
azerothcore-wotlk/src/test/mocks/DamageHealInfoStub.h