AzerothCore Doxygen
npc_zulaman_hostage Class Reference
Classes
struct npc_zulaman_hostageAI
Public Member Functions
npc_zulaman_hostage ()
CreatureAI * GetAI (Creature *creature) const override
bool OnGossipHello (Player *player, Creature *creature) override
bool OnGossipSelect (Player *player, Creature *creature, uint32, uint32 action) override
Public Member Functions inherited from CreatureScript
bool IsDatabaseBound () const override
virtual bool OnGossipSelectCode (Player *, Creature *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, Creature *, Quest const *)
virtual bool OnQuestSelect (Player *, Creature *, Quest const *)
virtual bool OnQuestComplete (Player *, Creature *, Quest const *)
virtual bool OnQuestReward (Player *, Creature *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, Creature *)
virtual void OnFfaPvpStateUpdate (Creature *, bool)
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
uint16 GetTotalAvailableHooks ()
Public Member Functions inherited from UpdatableScript< Creature >
virtual void OnUpdate (Creature *, uint32)
Additional Inherited Members
Protected Member Functions inherited from CreatureScript
CreatureScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name, uint16 totalAvailableHooks=0)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< Creature >
UpdatableScript ()=default
Detailed Description
Constructor & Destructor Documentation
npc_zulaman_hostage()
npc_zulaman_hostage::npc_zulaman_hostage () inline
: CreatureScript("npc_zulaman_hostage") { }
Member Function Documentation
GetAI()
CreatureAI * npc_zulaman_hostage::GetAI (Creature * creature) const inline override virtual
Reimplemented from CreatureScript.
    {
        return GetZulAmanAI<npc_zulaman_hostageAI>(creature);
    }
OnGossipHello()
bool npc_zulaman_hostage::OnGossipHello (Player * player, Creature * creature) inline override virtual
Reimplemented from CreatureScript.
    {
        AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_HOSTAGE1, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 1);
        SendGossipMenuFor(player, player->GetGossipTextId(creature), creature->GetGUID());
        return true;
    }
References AddGossipItemFor(), Player::GetGossipTextId(), Object::GetGUID(), GOSSIP_ACTION_INFO_DEF, GOSSIP_HOSTAGE1, GOSSIP_ICON_CHAT, GOSSIP_SENDER_MAIN, and SendGossipMenuFor().
OnGossipSelect()
bool npc_zulaman_hostage::OnGossipSelect (Player * player, Creature * creature, uint32 , uint32 action) inline override virtual
Reimplemented from CreatureScript.
    {
        ClearGossipMenuFor(player);
        if (action == GOSSIP_ACTION_INFO_DEF + 1)
            CloseGossipMenuFor(player);
        if (!creature->HasNpcFlag(UNIT_NPC_FLAG_GOSSIP))
            return true;
        creature->RemoveNpcFlag(UNIT_NPC_FLAG_GOSSIP);
        creature->GetInstanceScript()->SetData(DATA_CHEST_LOOTED, 0);
        float x, y, z;
        creature->GetPosition(x, y, z);
        for (uint8 i = 0; i < 4; ++i)
        {
            if (HostageEntry[i] == creature->GetEntry())
            {
                GameObject* obj = creature->SummonGameObject(ChestEntry[i], x - 2, y, z, 0, 0, 0, 0, 0, 0);
                if (obj)
                    obj->RemoveFlag(GAMEOBJECT_FLAGS, GO_FLAG_LOCKED);
                break;
            }
        }
        return true;
    }
References ChestEntry, ClearGossipMenuFor(), CloseGossipMenuFor(), DATA_CHEST_LOOTED, GAMEOBJECT_FLAGS, Object::GetEntry(), WorldObject::GetInstanceScript(), Position::GetPosition(), GO_FLAG_LOCKED, GOSSIP_ACTION_INFO_DEF, Unit::HasNpcFlag(), HostageEntry, Object::RemoveFlag(), Unit::RemoveNpcFlag(), ZoneScript::SetData(), WorldObject::SummonGameObject(), and UNIT_NPC_FLAG_GOSSIP.
The documentation for this class was generated from the following file:
azerothcore-wotlk/src/server/scripts/EasternKingdoms/ZulAman/zulaman.cpp