AzerothCore Doxygen
LuaPlayer Namespace Reference
Functions
int CanTitanGrip (lua_State *L, Player *player)
int HasTalent (lua_State *L, Player *player)
int HasAchieved (lua_State *L, Player *player)
int GetAchievementCriteriaProgress (lua_State *L, Player *player)
int HasQuest (lua_State *L, Player *player)
int HasSkill (lua_State *L, Player *player)
int HasSpell (lua_State *L, Player *player)
int HasAtLoginFlag (lua_State *L, Player *player)
int HasQuestForGO (lua_State *L, Player *player)
int HasTitle (lua_State *L, Player *player)
int HasItem (lua_State *L, Player *player)
int HasQuestForItem (lua_State *L, Player *player)
int CanUseItem (lua_State *L, Player *player)
int HasSpellCooldown (lua_State *L, Player *player)
int CanShareQuest (lua_State *L, Player *player)
int CanSpeak (lua_State *L, Player *player)
int CanUninviteFromGroup (lua_State *L, Player *player)
int CanFly (lua_State *L, Player *player)
int IsInWater (lua_State *L, Player *player)
int IsMoving (lua_State *L, Player *player)
int IsFlying (lua_State *L, Player *player)
int HasTankSpec (lua_State *L, Player *player)
int HasMeleeSpec (lua_State *L, Player *player)
int HasCasterSpec (lua_State *L, Player *player)
int HasHealSpec (lua_State *L, Player *player)
int IsInGroup (lua_State *L, Player *player)
int IsInGuild (lua_State *L, Player *player)
int IsGM (lua_State *L, Player *player)
int IsInArenaTeam (lua_State *L, Player *player)
int IsImmuneToDamage (lua_State *L, Player *player)
int CanCompleteRepeatableQuest (lua_State *L, Player *player)
int CanRewardQuest (lua_State *L, Player *player)
int CanCompleteQuest (lua_State *L, Player *player)
int IsHorde (lua_State *L, Player *player)
int IsAlliance (lua_State *L, Player *player)
int IsDND (lua_State *L, Player *player)
int IsAFK (lua_State *L, Player *player)
int IsFalling (lua_State *L, Player *player)
int IsGroupVisibleFor (lua_State *L, Player *player)
int IsInSameRaidWith (lua_State *L, Player *player)
int IsInSameGroupWith (lua_State *L, Player *player)
int IsHonorOrXPTarget (lua_State *L, Player *player)
int IsVisibleForPlayer (lua_State *L, Player *player)
int IsGMVisible (lua_State *L, Player *player)
int IsTaxiCheater (lua_State *L, Player *player)
int IsGMChat (lua_State *L, Player *player)
int IsAcceptingWhispers (lua_State *L, Player *player)
int IsRested (lua_State *L, Player *player)
int InBattlegroundQueue (lua_State *L, Player *player)
int InArena (lua_State *L, Player *player)
int InBattleground (lua_State *L, Player *player)
int CanBlock (lua_State *L, Player *player)
int CanParry (lua_State *L, Player *player)
int GetSpecsCount (lua_State *L, Player *player)
int GetActiveSpec (lua_State *L, Player *player)
int GetSpellCooldownDelay (lua_State *L, Player *player)
int GetLatency (lua_State *L, Player *player)
int GetOriginalSubGroup (lua_State *L, Player *player)
int GetOriginalGroup (lua_State *L, Player *player)
int GetNextRandomRaidMember (lua_State *L, Player *player)
int GetSubGroup (lua_State *L, Player *player)
int GetGroupInvite (lua_State *L, Player *player)
int GetXP (lua_State *L, Player *player)
int GetXPRestBonus (lua_State *L, Player *player)
int GetBattlegroundTypeId (lua_State *L, Player *player)
int GetBattlegroundId (lua_State *L, Player *player)
int GetReputationRank (lua_State *L, Player *player)
int GetDrunkValue (lua_State *L, Player *player)
int GetSkillTempBonusValue (lua_State *L, Player *player)
int GetSkillPermBonusValue (lua_State *L, Player *player)
int GetPureSkillValue (lua_State *L, Player *player)
int GetBaseSkillValue (lua_State *L, Player *player)
int GetSkillValue (lua_State *L, Player *player)
int GetPureMaxSkillValue (lua_State *L, Player *player)
int GetMaxSkillValue (lua_State *L, Player *player)
int GetManaBonusFromIntellect (lua_State *L, Player *player)
int GetHealthBonusFromStamina (lua_State *L, Player *player)
int GetDifficulty (lua_State *L, Player *player)
int GetGuildRank (lua_State *L, Player *player)
int GetFreeTalentPoints (lua_State *L, Player *player)
int GetGuildName (lua_State *L, Player *player)
int GetReputation (lua_State *L, Player *player)
int GetComboTarget (lua_State *L, Player *player)
int GetComboPoints (lua_State *L, Player *player)
int GetInGameTime (lua_State *L, Player *player)
int GetQuestStatus (lua_State *L, Player *player)
int GetQuestRewardStatus (lua_State *L, Player *player)
int GetReqKillOrCastCurrentCount (lua_State *L, Player *player)
int GetQuestLevel (lua_State *L, Player *player)
int GetEquippedItemBySlot (lua_State *L, Player *player)
int GetRestBonus (lua_State *L, Player *player)
int GetChatTag (lua_State *L, Player *player)
int GetItemByPos (lua_State *L, Player *player)
int GetItemByGUID (lua_State *L, Player *player)
int GetMailCount (lua_State *L, Player *player)
int GetMailItem (lua_State *L, Player *player)
int GetItemByEntry (lua_State *L, Player *player)
int GetGossipTextId (lua_State *L, Player *player)
int GetSelection (lua_State *L, Player *player)
int GetGMRank (lua_State *L, Player *player)
int GetCoinage (lua_State *L, Player *player)
int GetGuildId (lua_State *L, Player *player)
int GetTeam (lua_State *L, Player *player)
int GetItemCount (lua_State *L, Player *player)
int GetLifetimeKills (lua_State *L, Player *player)
int GetPlayerIP (lua_State *L, Player *player)
int GetLevelPlayedTime (lua_State *L, Player *player)
int GetTotalPlayedTime (lua_State *L, Player *player)
int GetGuild (lua_State *L, Player *player)
int GetGroup (lua_State *L, Player *player)
int GetAccountId (lua_State *L, Player *player)
int GetAccountName (lua_State *L, Player *player)
int GetCompletedQuestsCount (lua_State *L, Player *player)
int GetCorpse (lua_State *L, Player *player)
int GetDbLocaleIndex (lua_State *L, Player *player)
int GetDbcLocale (lua_State *L, Player *player)
int SetPlayerLock (lua_State *L, Player *player)
int SetAtLoginFlag (lua_State *L, Player *player)
int SetSheath (lua_State *L, Player *player)
int SetDrunkValue (lua_State *L, Player *player)
int SetFactionForRace (lua_State *L, Player *player)
int SetSkill (lua_State *L, Player *player)
int SetGuildRank (lua_State *L, Player *player)
int SetFreeTalentPoints (lua_State *L, Player *player)
int SetReputation (lua_State *L, Player *player)
int SetQuestStatus (lua_State *L, Player *player)
int SetRestBonus (lua_State *L, Player *player)
int SetAcceptWhispers (lua_State *L, Player *player)
int SetPvPDeath (lua_State *L, Player *player)
int SetGMVisible (lua_State *L, Player *player)
int SetTaxiCheat (lua_State *L, Player *player)
int SetGMChat (lua_State *L, Player *player)
int SetGameMaster (lua_State *L, Player *player)
int SetGender (lua_State *L, Player *player)
int SetLifetimeKills (lua_State *L, Player *player)
int SetCoinage (lua_State *L, Player *player)
int SetBindPoint (lua_State *L, Player *player)
int SetKnownTitle (lua_State *L, Player *player)
int SetFFA (lua_State *L, Player *player)
int ResetPetTalents (lua_State *, Player *player)
int ResetAchievements (lua_State *, Player *player)
int SendShowMailBox (lua_State *L, Player *player)
int SaveToDB (lua_State *, Player *player)
int SummonPlayer (lua_State *L, Player *player)
int Mute (lua_State *L, Player *player)
int RewardQuest (lua_State *L, Player *player)
int SendAuctionMenu (lua_State *L, Player *player)
int SendTaxiMenu (lua_State *L, Player *player)
int SendSpiritResurrect (lua_State *, Player *player)
int SendTabardVendorActivate (lua_State *L, Player *player)
int SendShowBank (lua_State *L, Player *player)
int SendListInventory (lua_State *L, Player *player)
int SendTrainerList (lua_State *L, Player *player)
int SendGuildInvite (lua_State *L, Player *player)
int SendUpdateWorldState (lua_State *L, Player *player)
int LogoutPlayer (lua_State *L, Player *player)
int RemoveFromBattlegroundRaid (lua_State *, Player *player)
int UnbindInstance (lua_State *L, Player *player)
int UnbindAllInstances (lua_State *, Player *player)
int LeaveBattleground (lua_State *L, Player *player)
int DurabilityRepair (lua_State *L, Player *player)
int DurabilityRepairAll (lua_State *L, Player *player)
int DurabilityPointLossForEquipSlot (lua_State *L, Player *player)
int DurabilityPointsLossAll (lua_State *L, Player *player)
int DurabilityPointsLoss (lua_State *L, Player *player)
int DurabilityLoss (lua_State *L, Player *player)
int DurabilityLossAll (lua_State *L, Player *player)
int KillPlayer (lua_State *, Player *player)
int RemoveFromGroup (lua_State *, Player *player)
int ResetTalentsCost (lua_State *L, Player *player)
int ResetTalents (lua_State *L, Player *player)
int RemoveSpell (lua_State *L, Player *player)
int ClearComboPoints (lua_State *, Player *player)
int AddComboPoints (lua_State *L, Player *player)
int TalkedToCreature (lua_State *L, Player *player)
int KilledMonsterCredit (lua_State *L, Player *player)
int GroupEventHappens (lua_State *L, Player *player)
int AreaExploredOrEventHappens (lua_State *L, Player *player)
int FailQuest (lua_State *L, Player *player)
int IncompleteQuest (lua_State *L, Player *player)
int CompleteQuest (lua_State *L, Player *player)
int AddQuest (lua_State *L, Player *player)
int RemoveQuest (lua_State *L, Player *player)
int Whisper (lua_State *L, Player *player)
int TextEmote (lua_State *L, Player *player)
int Yell (lua_State *L, Player *player)
int Say (lua_State *L, Player *player)
int GiveXP (lua_State *L, Player *player)
int ToggleDND (lua_State *, Player *player)
int ToggleAFK (lua_State *, Player *player)
int EquipItem (lua_State *L, Player *player)
int CanEquipItem (lua_State *L, Player *player)
int UnsetKnownTitle (lua_State *L, Player *player)
int AdvanceSkillsToMax (lua_State *, Player *player)
int AdvanceAllSkills (lua_State *L, Player *player)
int AdvanceSkill (lua_State *L, Player *player)
int Teleport (lua_State *L, Player *player)
int AddLifetimeKills (lua_State *L, Player *player)
int AddItem (lua_State *L, Player *player)
int RemoveItem (lua_State *L, Player *player)
int RemoveLifetimeKills (lua_State *L, Player *player)
int ResetSpellCooldown (lua_State *L, Player *player)
int ResetTypeCooldowns (lua_State *L, Player *player)
int ResetAllCooldowns (lua_State *, Player *player)
int SendBroadcastMessage (lua_State *L, Player *player)
int SendAreaTriggerMessage (lua_State *L, Player *player)
int SendNotification (lua_State *L, Player *player)
int SendPacket (lua_State *L, Player *player)
int SendAddonMessage (lua_State *L, Player *player)
int KickPlayer (lua_State *, Player *player)
int ModifyMoney (lua_State *L, Player *player)
int LearnSpell (lua_State *L, Player *player)
int LearnTalent (lua_State *L, Player *player)
int RunCommand (lua_State *L, Player *player)
int SetGlyph (lua_State *L, Player *player)
int GetGlyph (lua_State *L, Player *player)
int RemoveArenaSpellCooldowns (lua_State *, Player *player)
int ResurrectPlayer (lua_State *L, Player *player)
int GossipMenuAddItem (lua_State *L, Player *player)
int GossipComplete (lua_State *, Player *player)
int GossipSendMenu (lua_State *L, Player *player)
int GossipClearMenu (lua_State *, Player *player)
int StartTaxi (lua_State *L, Player *player)
int GossipSendPOI (lua_State *L, Player *player)
int GossipAddQuests (lua_State *L, Player *player)
int SendQuestTemplate (lua_State *L, Player *player)
int SpawnBones (lua_State *, Player *player)
int RemovedInsignia (lua_State *L, Player *player)
int GroupInvite (lua_State *L, Player *player)
int GroupCreate (lua_State *L, Player *player)
int SendCinematicStart (lua_State *L, Player *player)
int SendMovieStart (lua_State *L, Player *player)
int UpdatePlayerSetting (lua_State *L, Player *player)
int GetPlayerSettingValue (lua_State *L, Player *player)
int GetTrader (lua_State *L, Player *player)
int SetSpellPower (lua_State *L, Player *player)
Function Documentation
AddComboPoints()
int LuaPlayer::AddComboPoints (lua_State * L, Player * player)
Adds combo points to the [Player]
Parameters
[Unit] target
int8 count
    {
        Unit* target = Eluna::CHECKOBJ<Unit>(L, 2);
        int8 count = Eluna::CHECKVAL<int8>(L, 3);
        player->AddComboPoints(target, count);
        return 0;
    }
References Unit::AddComboPoints().
AddItem()
int LuaPlayer::AddItem (lua_State * L, Player * player)
Adds the given amount of the specified item entry to the player.
Parameters
uint32 entry : entry of the item to add
uint32 itemCount = 1 : amount of the item to add
Returns
[Item] item : the item that was added or nil
    {
        uint32 itemId = Eluna::CHECKVAL<uint32>(L, 2);
        uint32 itemCount = Eluna::CHECKVAL<uint32>(L, 3, 1);
#if defined TRINITY || AZEROTHCORE
        uint32 noSpaceForCount = 0;
        ItemPosCountVec dest;
        InventoryResult msg = player->CanStoreNewItem(NULL_BAG, NULL_SLOT, dest, itemId, itemCount, &noSpaceForCount);
        if (msg != EQUIP_ERR_OK)
            itemCount -= noSpaceForCount;
        if (itemCount == 0 || dest.empty())
            return 1;
#ifndef AZEROTHCORE
        Item* item = player->StoreNewItem(dest, itemId, true, GenerateItemRandomPropertyId(itemId));
#else
        Item* item = player->StoreNewItem(dest, itemId, true, Item::GenerateItemRandomPropertyId(itemId));
#endif
        if (item)
            player->SendNewItem(item, itemCount, true, false);
        Eluna::Push(L, item);
#else
        Eluna::Push(L, player->StoreNewItemInInventorySlot(itemId, itemCount));
#endif
        return 1;
    }
References Player::CanStoreNewItem(), EQUIP_ERR_OK, Item::GenerateItemRandomPropertyId(), NULL_BAG, NULL_SLOT, Eluna::Push(), Player::SendNewItem(), and Player::StoreNewItem().
AddLifetimeKills()
int LuaPlayer::AddLifetimeKills (lua_State * L, Player * player)
    {
        uint32 val = Eluna::CHECKVAL<uint32>(L, 2);
        uint32 currentKills = player->GetUInt32Value(PLAYER_FIELD_LIFETIME_HONORABLE_KILLS);
        player->SetUInt32Value(PLAYER_FIELD_LIFETIME_HONORABLE_KILLS, currentKills + val);
        return 0;
    }
References Object::GetUInt32Value(), PLAYER_FIELD_LIFETIME_HONORABLE_KILLS, and Unit::SetUInt32Value().
AddQuest()
int LuaPlayer::AddQuest (lua_State * L, Player * player)
Tries to add the given quest entry for the [Player].
Parameters
uint32 entry : quest entry
    {
        uint32 entry = Eluna::CHECKVAL<uint32>(L, 2);
        Quest const* quest = eObjectMgr->GetQuestTemplate(entry);
        if (!quest)
            return 0;
#if defined TRINITY || AZEROTHCORE
        // check item starting quest (it can work incorrectly if added without item in inventory)
#ifndef AZEROTHCORE
        ItemTemplateContainer const& itc = sObjectMgr->GetItemTemplateStore();
        auto itr = std::find_if(std::begin(itc), std::end(itc), [quest](ItemTemplateContainer::value_type const& value)
        {
            return value.second.StartQuest == quest->GetQuestId();
        });
        if (itr != std::end(itc))
            return 0;
#else
        ItemTemplateContainer const* itc = sObjectMgr->GetItemTemplateStore();
        ItemTemplateContainer::const_iterator result = find_if(itc->begin(), itc->end(), Finder<uint32, ItemTemplate>(entry, &ItemTemplate::StartQuest));
        if (result != itc->end())
            return 0;
#endif
        // ok, normal (creature/GO starting) quest
        if (player->CanAddQuest(quest, true))
            player->AddQuestAndCheckCompletion(quest, NULL);
#else
        // check item starting quest (it can work incorrectly if added without item in inventory)
        for (uint32 id = 0; id < sItemStorage.GetMaxEntry(); ++id)
        {
            ItemPrototype const* pProto = sItemStorage.LookupEntry<ItemPrototype>(id);
            if (!pProto)
                continue;
            if (pProto->StartQuest == entry)
                return 0;
        }
        // ok, normal (creature/GO starting) quest
        if (player->CanAddQuest(quest, true))
        {
            player->AddQuest(quest, NULL);
            if (player->CanCompleteQuest(entry))
                player->CompleteQuest(entry);
        }
#endif
        return 0;
    }
References Player::AddQuest(), Player::AddQuestAndCheckCompletion(), Player::CanAddQuest(), Player::CanCompleteQuest(), Player::CompleteQuest(), eObjectMgr, Quest::GetQuestId(), and sObjectMgr.
AdvanceAllSkills()
int LuaPlayer::AdvanceAllSkills (lua_State * L, Player * player)
Advances all of the [Player]s skills to the amount specified
Parameters
uint32 skillStep
    {
        uint32 step = Eluna::CHECKVAL<uint32>(L, 2);
        if (!step)
            return 0;
        for (uint32 i = 0; i < sSkillLineStore.GetNumRows(); ++i)
        {
            if (SkillLineEntry const* entry = sSkillLineStore.LookupEntry(i))
            {
#ifdef TRINITY
                if (entry->CategoryID == SKILL_CATEGORY_LANGUAGES || entry->CategoryID == SKILL_CATEGORY_GENERIC)
                    continue;
                if (player->HasSkill(entry->ID))
                    player->UpdateSkill(entry->ID, step);
#else
                if (entry->categoryId == SKILL_CATEGORY_LANGUAGES || entry->categoryId == SKILL_CATEGORY_GENERIC)
                    continue;
                if (player->HasSkill(entry->id))
                    player->UpdateSkill(entry->id, step);
#endif
            }
        }
        return 0;
    }
References Player::HasSkill(), SKILL_CATEGORY_GENERIC, SKILL_CATEGORY_LANGUAGES, sSkillLineStore, and Player::UpdateSkill().
AdvanceSkill()
int LuaPlayer::AdvanceSkill (lua_State * L, Player * player)
Advances a [Player]s specific skill to the amount specified
Parameters
uint32 skillId
uint32 skillStep
    {
        uint32 _skillId = Eluna::CHECKVAL<uint32>(L, 2);
        uint32 _step = Eluna::CHECKVAL<uint32>(L, 3);
        if (_skillId && _step)
        {
            if (player->HasSkill(_skillId))
                player->UpdateSkill(_skillId, _step);
        }
        return 0;
    }
References Player::HasSkill(), and Player::UpdateSkill().
AdvanceSkillsToMax()
int LuaPlayer::AdvanceSkillsToMax (lua_State * , Player * player)
Advances all of the [Player]s weapon skills to the maximum amount available
    {
#ifdef TRINITY
        player->UpdateWeaponsSkillsToMaxSkillsForLevel();
#else
        player->UpdateSkillsToMaxSkillsForLevel();
#endif
        return 0;
    }
References Player::UpdateSkillsToMaxSkillsForLevel().
AreaExploredOrEventHappens()
int LuaPlayer::AreaExploredOrEventHappens (lua_State * L, Player * player)
Completes the [Quest] if a [Quest] area is explored, or completes the [Quest]
Parameters
uint32 quest : entry of a [Quest]
    {
        uint32 questId = Eluna::CHECKVAL<uint32>(L, 2);
        player->AreaExploredOrEventHappens(questId);
        return 0;
    }
References Player::AreaExploredOrEventHappens().
CanBlock()
int LuaPlayer::CanBlock (lua_State * L, Player * player)
Returns true if the [Player] can block incomming attacks, false otherwise.
Returns
bool canBlock
    {
        Eluna::Push(L, player->CanBlock());
        return 1;
    }
References Player::CanBlock(), and Eluna::Push().
CanCompleteQuest()
int LuaPlayer::CanCompleteQuest (lua_State * L, Player * player)
Returns true if the [Player] satisfies all requirements to complete the quest entry.
Parameters
uint32 entry
Returns
bool canComplete
    {
        uint32 entry = Eluna::CHECKVAL<uint32>(L, 2);
        Eluna::Push(L, player->CanCompleteQuest(entry));
        return 1;
    }
References Player::CanCompleteQuest(), and Eluna::Push().
CanCompleteRepeatableQuest()
int LuaPlayer::CanCompleteRepeatableQuest (lua_State * L, Player * player)
Returns true if the [Player] satisfies all requirements to complete the quest entry.
Parameters
uint32 questId
Returns
bool canCompleteRepeatableQuest
    {
        uint32 questId = Eluna::CHECKVAL<uint32>(L, 2);
        const Quest* quest = sObjectMgr->GetQuestTemplate(questId); // Retrieve the Quest object
        if (!quest)
        {
            Eluna::Push(L, false);
            return 1;
        }
        Eluna::Push(L, player->CanCompleteRepeatableQuest(quest));
        return 1;
    }
References Player::CanCompleteRepeatableQuest(), Eluna::Push(), and sObjectMgr.
CanEquipItem()
int LuaPlayer::CanEquipItem (lua_State * L, Player * player)
Returns true if the player can equip the given [Item] or item entry to the given slot, false otherwise.
@proto canEquip = (item, slot) @proto canEquip = (entry, slot)
Parameters
[Item] item : item to equip
uint32 entry : entry of the item to equip
uint32 slot : equipment slot to test
Returns
bool canEquip
    {
        Item* item = Eluna::CHECKOBJ<Item>(L, 2, false);
        uint32 slot = Eluna::CHECKVAL<uint32>(L, 3);
        if (slot >= EQUIPMENT_SLOT_END)
        {
            Eluna::Push(L, false);
            return 1;
        }
        if (!item)
        {
            uint32 entry = Eluna::CHECKVAL<uint32>(L, 2);
            uint16 dest;
            InventoryResult msg = player->CanEquipNewItem(slot, dest, entry, false);
            if (msg != EQUIP_ERR_OK)
            {
                Eluna::Push(L, false);
                return 1;
            }
        }
        else
        {
            uint16 dest;
            InventoryResult msg = player->CanEquipItem(slot, dest, item, false);
            if (msg != EQUIP_ERR_OK)
            {
                Eluna::Push(L, false);
                return 1;
            }
        }
        Eluna::Push(L, true);
        return 1;
    }
References Player::CanEquipItem(), Player::CanEquipNewItem(), EQUIP_ERR_OK, EQUIPMENT_SLOT_END, and Eluna::Push().
CanFly()
int LuaPlayer::CanFly (lua_State * L, Player * player)
Returns true if the [Player] can fly, false otherwise.
Returns
bool canFly
    {
        Eluna::Push(L, player->CanFly());
        return 1;
    }
References Player::CanFly(), and Eluna::Push().
CanParry()
int LuaPlayer::CanParry (lua_State * L, Player * player)
Returns true if the [Player] can parry incomming attacks, false otherwise.
Returns
bool canParry
    {
        Eluna::Push(L, player->CanParry());
        return 1;
    }
References Player::CanParry(), and Eluna::Push().
CanRewardQuest()
int LuaPlayer::CanRewardQuest (lua_State * L, Player * player)
Returns true if the [Player] satisfies all requirements to reward the quest entry.
Parameters
uint32 questId
Returns
bool canRewardQuest
    {
        uint32 questId = Eluna::CHECKVAL<uint32>(L, 2);
        const Quest* quest = sObjectMgr->GetQuestTemplate(questId); // Retrieve the Quest object
        if (!quest)
        {
            Eluna::Push(L, false);
            return 1;
        }
        Eluna::Push(L, player->CanRewardQuest(quest, true)); // Modify the second argument as needed
        return 1;
    }
References Player::CanRewardQuest(), Eluna::Push(), and sObjectMgr.
CanShareQuest()
int LuaPlayer::CanShareQuest (lua_State * L, Player * player)
Returns true if the [Player] can share [Quest] specified by ID, false otherwise.
Parameters
uint32 entryId
Returns
bool hasSpellCooldown
    {
        uint32 entry = Eluna::CHECKVAL<uint32>(L, 2);
        Eluna::Push(L, player->CanShareQuest(entry));
        return 1;
    }
References Player::CanShareQuest(), and Eluna::Push().
CanSpeak()
int LuaPlayer::CanSpeak (lua_State * L, Player * player)
Returns true if the [Player] can currently communicate through chat, false otherwise.
Returns
bool canSpeak
    {
#ifdef TRINITY
        Eluna::Push(L, player->GetSession()->CanSpeak());
#else
        Eluna::Push(L, player->CanSpeak());
#endif
        return 1;
    }
References Player::CanSpeak(), Player::GetSession(), and Eluna::Push().
CanTitanGrip()
int LuaPlayer::CanTitanGrip (lua_State * L, Player * player)
Returns true if the [Player] can Titan Grip, false otherwise.
Returns
bool canTitanGrip
    {
        Eluna::Push(L, player->CanTitanGrip());
        return 1;
    }
References Player::CanTitanGrip(), and Eluna::Push().
CanUninviteFromGroup()
int LuaPlayer::CanUninviteFromGroup (lua_State * L, Player * player)
Returns true if the [Player] has permission to uninvite others from the current group, false otherwise.
Returns
bool canUninviteFromGroup
    {
        Eluna::Push(L, player->CanUninviteFromGroup() == ERR_PARTY_RESULT_OK);
        return 1;
    }
References Player::CanUninviteFromGroup(), ERR_PARTY_RESULT_OK, and Eluna::Push().
CanUseItem()
int LuaPlayer::CanUseItem (lua_State * L, Player * player)
Returns true if the [Player] can use the item or item entry specified, false otherwise.
@proto canUse = (item) @proto canUse = (entry)
Parameters
[Item] item : an instance of an item
uint32 entry : entry of the item
Returns
bool canUse
    {
        Item* item = Eluna::CHECKOBJ<Item>(L, 2, false);
        if (item)
            Eluna::Push(L, player->CanUseItem(item) == EQUIP_ERR_OK);
        else
        {
            uint32 entry = Eluna::CHECKVAL<uint32>(L, 2);
            const ItemTemplate* temp = eObjectMgr->GetItemTemplate(entry);
            if (temp)
                Eluna::Push(L, player->CanUseItem(temp) == EQUIP_ERR_OK);
            else
                Eluna::Push(L, false);
        }
        return 1;
    }
References Player::CanUseItem(), eObjectMgr, EQUIP_ERR_OK, and Eluna::Push().
ClearComboPoints()
int LuaPlayer::ClearComboPoints (lua_State * , Player * player)
Clears the [Player]s combo points
    {
        player->ClearComboPoints();
        return 0;
    }
References Unit::ClearComboPoints().
CompleteQuest()
int LuaPlayer::CompleteQuest (lua_State * L, Player * player)
Completes the given quest entry for the [Player] and tries to satisfy all quest requirements.
The player should have the quest to complete it.
Parameters
uint32 entry : quest entry
    {
        uint32 entry = Eluna::CHECKVAL<uint32>(L, 2);
        Quest const* quest = eObjectMgr->GetQuestTemplate(entry);
        // If player doesn't have the quest
        if (!quest || player->GetQuestStatus(entry) == QUEST_STATUS_NONE)
            return 0;
        // Add quest items for quests that require items
        for (uint8 x = 0; x < QUEST_ITEM_OBJECTIVES_COUNT; ++x)
        {
#if defined TRINITY || AZEROTHCORE
            uint32 id = quest->RequiredItemId[x];
            uint32 count = quest->RequiredItemCount[x];
#else
            uint32 id = quest->ReqItemId[x];
            uint32 count = quest->ReqItemCount[x];
#endif
            if (!id || !count)
                continue;
            uint32 curItemCount = player->GetItemCount(id, true);
            ItemPosCountVec dest;
            uint8 msg = player->CanStoreNewItem(NULL_BAG, NULL_SLOT, dest, id, count - curItemCount);
            if (msg == EQUIP_ERR_OK)
            {
                Item* item = player->StoreNewItem(dest, id, true);
                player->SendNewItem(item, count - curItemCount, true, false);
            }
        }
        // All creature/GO slain/cast (not required, but otherwise it will display "Creature slain 0/10")
        for (uint8 i = 0; i < QUEST_OBJECTIVES_COUNT; ++i)
        {
#if defined TRINITY || AZEROTHCORE
            int32 creature = quest->RequiredNpcOrGo[i];
            uint32 creatureCount = quest->RequiredNpcOrGoCount[i];
            if (creature > 0)
            {
                if (CreatureTemplate const* creatureInfo = sObjectMgr->GetCreatureTemplate(creature))
                    for (uint16 z = 0; z < creatureCount; ++z)
                        player->KilledMonster(creatureInfo, ObjectGuid::Empty);
            }
            else if (creature < 0)
                for (uint16 z = 0; z < creatureCount; ++z)
                    player->KillCreditGO(creature);
#else
            int32 creature = quest->ReqCreatureOrGOId[i];
            uint32 creaturecount = quest->ReqCreatureOrGOCount[i];
            if (uint32 spell_id = quest->ReqSpell[i])
            {
                for (uint16 z = 0; z < creaturecount; ++z)
                    player->CastedCreatureOrGO(creature, ObjectGuid(), spell_id);
            }
            else if (creature > 0)
            {
                if (CreatureInfo const* cInfo = ObjectMgr::GetCreatureTemplate(creature))
                    for (uint16 z = 0; z < creaturecount; ++z)
                        player->KilledMonster(cInfo, ObjectGuid());
            }
            else if (creature < 0)
            {
                for (uint16 z = 0; z < creaturecount; ++z)
                    player->CastedCreatureOrGO(-creature, ObjectGuid(), 0);
            }
#endif
        }
        // If the quest requires reputation to complete
        if (uint32 repFaction = quest->GetRepObjectiveFaction())
        {
            uint32 repValue = quest->GetRepObjectiveValue();
            uint32 curRep = player->GetReputationMgr().GetReputation(repFaction);
            if (curRep < repValue)
                if (FactionEntry const* factionEntry = sFactionStore.LookupEntry(repFaction))
                    player->GetReputationMgr().SetReputation(factionEntry, repValue);
        }
#if defined TRINITY || AZEROTHCORE
        // If the quest requires a SECOND reputation to complete
        if (uint32 repFaction = quest->GetRepObjectiveFaction2())
        {
            uint32 repValue2 = quest->GetRepObjectiveValue2();
            uint32 curRep = player->GetReputationMgr().GetReputation(repFaction);
            if (curRep < repValue2)
                if (FactionEntry const* factionEntry = sFactionStore.LookupEntry(repFaction))
                    player->GetReputationMgr().SetReputation(factionEntry, repValue2);
        }
#endif
        // If the quest requires money
        int32 ReqOrRewMoney = quest->GetRewOrReqMoney();
        if (ReqOrRewMoney < 0)
            player->ModifyMoney(-ReqOrRewMoney);
#ifdef TRINITY
        if (sWorld->getBoolConfig(CONFIG_QUEST_ENABLE_QUEST_TRACKER)) // check if Quest Tracker is enabled
        {
            // prepare Quest Tracker datas
            CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_UPD_QUEST_TRACK_GM_COMPLETE);
            stmt->setUInt32(0, quest->GetQuestId());
            stmt->setUInt32(1, player->GetGUID().GetCounter());
            // add to Quest Tracker
            CharacterDatabase.Execute(stmt);
        }
#endif
        player->CompleteQuest(entry);
        return 0;
    }
References Player::CanStoreNewItem(), CHAR_UPD_QUEST_TRACK_GM_COMPLETE, CharacterDatabase, Player::CompleteQuest(), CONFIG_QUEST_ENABLE_QUEST_TRACKER, ObjectGuid::Empty, eObjectMgr, EQUIP_ERR_OK, ObjectGuid::GetCounter(), ObjectMgr::GetCreatureTemplate(), Object::GetGUID(), Player::GetItemCount(), Quest::GetQuestId(), Player::GetQuestStatus(), Quest::GetRepObjectiveFaction(), Quest::GetRepObjectiveFaction2(), Quest::GetRepObjectiveValue(), Quest::GetRepObjectiveValue2(), ReputationMgr::GetReputation(), Player::GetReputationMgr(), Quest::GetRewOrReqMoney(), Player::KillCreditGO(), Player::KilledMonster(), Player::ModifyMoney(), NULL_BAG, NULL_SLOT, QUEST_ITEM_OBJECTIVES_COUNT, QUEST_OBJECTIVES_COUNT, QUEST_STATUS_NONE, Quest::RequiredItemCount, Quest::RequiredItemId, Quest::RequiredNpcOrGo, Quest::RequiredNpcOrGoCount, Player::SendNewItem(), ReputationMgr::SetReputation(), sFactionStore, sObjectMgr, Player::StoreNewItem(), and sWorld.
DurabilityLoss()
int LuaPlayer::DurabilityLoss (lua_State * L, Player * player)
Damages specified [Item]
Parameters
[Item] item
double percent
    {
        Item* item = Eluna::CHECKOBJ<Item>(L, 2);
        double percent = Eluna::CHECKVAL<double>(L, 3);
        player->DurabilityLoss(item, percent);
        return 0;
    }
References Player::DurabilityLoss().
DurabilityLossAll()
int LuaPlayer::DurabilityLossAll (lua_State * L, Player * player)
Damages all [Item]s equipped. If inventory is true, damages [Item]s in bags
Parameters
double percent
bool inventory = true
    {
        double percent = Eluna::CHECKVAL<double>(L, 2);
        bool inventory = Eluna::CHECKVAL<bool>(L, 3, true);
        player->DurabilityLossAll(percent, inventory);
        return 0;
    }
References Player::DurabilityLossAll().
DurabilityPointLossForEquipSlot()
int LuaPlayer::DurabilityPointLossForEquipSlot (lua_State * L, Player * player)
Sets durability loss for an [Item] in the specified slot
Parameters
int32 slot
    {
        int32 slot = Eluna::CHECKVAL<int32>(L, 2);
        if (slot >= EQUIPMENT_SLOT_START && slot < EQUIPMENT_SLOT_END)
            player->DurabilityPointLossForEquipSlot((EquipmentSlots)slot);
        return 0;
    }
References Player::DurabilityPointLossForEquipSlot(), EQUIPMENT_SLOT_END, and EQUIPMENT_SLOT_START.
DurabilityPointsLoss()
int LuaPlayer::DurabilityPointsLoss (lua_State * L, Player * player)
Sets durability loss for the specified [Item]
Parameters
[Item] item
int32 points
    {
        Item* item = Eluna::CHECKOBJ<Item>(L, 2);
        int32 points = Eluna::CHECKVAL<int32>(L, 3);
        player->DurabilityPointsLoss(item, points);
        return 0;
    }
References Player::DurabilityPointsLoss().
DurabilityPointsLossAll()
int LuaPlayer::DurabilityPointsLossAll (lua_State * L, Player * player)
Sets durability loss on all [Item]s equipped
If inventory is true, sets durability loss for [Item]s in bags
Parameters
int32 points
bool inventory = true
    {
        int32 points = Eluna::CHECKVAL<int32>(L, 2);
        bool inventory = Eluna::CHECKVAL<bool>(L, 3, true);
        player->DurabilityPointsLossAll(points, inventory);
        return 0;
    }
References Player::DurabilityPointsLossAll().
DurabilityRepair()
int LuaPlayer::DurabilityRepair (lua_State * L, Player * player)
Repairs [Item] at specified position.
Parameters
uint16 position
bool cost = true
float discountMod = 1.0
    {
        uint16 position = Eluna::CHECKVAL<uint16>(L, 2);
        bool takeCost = Eluna::CHECKVAL<bool>(L, 3, true);
        float discountMod = Eluna::CHECKVAL<float>(L, 4, 1.0f);
#ifdef CLASSIC
        player->DurabilityRepair(position, takeCost, discountMod);
#elif defined(TRINITY)
        player->DurabilityRepair(position, takeCost, discountMod);
#else
        player->DurabilityRepair(position, takeCost, discountMod, false);
#endif
        return 0;
    }
References Player::DurabilityRepair().
DurabilityRepairAll()
int LuaPlayer::DurabilityRepairAll (lua_State * L, Player * player)
Repairs all [Item]s.
Parameters
bool takeCost = true
float discountMod = 1.0
bool guidBank = false
    {
        bool takeCost = Eluna::CHECKVAL<bool>(L, 2, true);
        float discountMod = Eluna::CHECKVAL<float>(L, 3, 1.0f);
        bool guildBank = Eluna::CHECKVAL<bool>(L, 4, false);
#ifdef CLASSIC
        player->DurabilityRepairAll(takeCost, discountMod);
#else
        player->DurabilityRepairAll(takeCost, discountMod, guildBank);
#endif
        return 0;
    }
References Player::DurabilityRepairAll().
EquipItem()
int LuaPlayer::EquipItem (lua_State * L, Player * player)
Equips the given item or item entry to the given slot. Returns the equipped item or nil.
enum EquipmentSlots // 19 slots
{
    EQUIPMENT_SLOT_START        = 0,
    EQUIPMENT_SLOT_HEAD         = 0,
    EQUIPMENT_SLOT_NECK         = 1,
    EQUIPMENT_SLOT_SHOULDERS    = 2,
    EQUIPMENT_SLOT_BODY         = 3,
    EQUIPMENT_SLOT_CHEST        = 4,
    EQUIPMENT_SLOT_WAIST        = 5,
    EQUIPMENT_SLOT_LEGS         = 6,
    EQUIPMENT_SLOT_FEET         = 7,
    EQUIPMENT_SLOT_WRISTS       = 8,
    EQUIPMENT_SLOT_HANDS        = 9,
    EQUIPMENT_SLOT_FINGER1      = 10,
    EQUIPMENT_SLOT_FINGER2      = 11,
    EQUIPMENT_SLOT_TRINKET1     = 12,
    EQUIPMENT_SLOT_TRINKET2     = 13,
    EQUIPMENT_SLOT_BACK         = 14,
    EQUIPMENT_SLOT_MAINHAND     = 15,
    EQUIPMENT_SLOT_OFFHAND      = 16,
    EQUIPMENT_SLOT_RANGED       = 17,
    EQUIPMENT_SLOT_TABARD       = 18,
    EQUIPMENT_SLOT_END          = 19
};
enum InventorySlots // 4 slots
{
    INVENTORY_SLOT_BAG_START    = 19,
    INVENTORY_SLOT_BAG_END      = 23
};
@proto equippedItem = (item, slot) @proto equippedItem = (entry, slot)
Parameters
[Item] item : item to equip
uint32 entry : entry of the item to equip
uint32 slot : equipment slot to equip the item to The slot can be [EquipmentSlots] or [InventorySlots]
Returns
[Item] equippedItem : item or nil if equipping failed
    {
        uint16 dest = 0;
        Item* item = Eluna::CHECKOBJ<Item>(L, 2, false);
        uint32 slot = Eluna::CHECKVAL<uint32>(L, 3);
        if (slot >= INVENTORY_SLOT_BAG_END)
            return 1;
        if (!item)
        {
            uint32 entry = Eluna::CHECKVAL<uint32>(L, 2);
            item = Item::CreateItem(entry, 1, player);
            if (!item)
                return 1;
            InventoryResult result = player->CanEquipItem(slot, dest, item, false);
            if (result != EQUIP_ERR_OK)
            {
                delete item;
                return 1;
            }
            player->ItemAddedQuestCheck(entry, 1);
#if (!defined(TBC) && !defined(CLASSIC))
            player->UpdateAchievementCriteria(ACHIEVEMENT_CRITERIA_TYPE_RECEIVE_EPIC_ITEM, entry, 1);
#endif
        }
        else
        {
            InventoryResult result = player->CanEquipItem(slot, dest, item, false);
            if (result != EQUIP_ERR_OK)
                return 1;
            player->RemoveItem(item->GetBagSlot(), item->GetSlot(), true);
        }
        Eluna::Push(L, player->EquipItem(dest, item, true));
        player->AutoUnequipOffhandIfNeed();
        return 1;
    }
References ACHIEVEMENT_CRITERIA_TYPE_RECEIVE_EPIC_ITEM, Player::AutoUnequipOffhandIfNeed(), Player::CanEquipItem(), Item::CreateItem(), EQUIP_ERR_OK, Player::EquipItem(), Item::GetBagSlot(), Item::GetSlot(), INVENTORY_SLOT_BAG_END, Player::ItemAddedQuestCheck(), Eluna::Push(), Player::RemoveItem(), and Player::UpdateAchievementCriteria().
FailQuest()
int LuaPlayer::FailQuest (lua_State * L, Player * player)
Sets the given [Quest] entry failed for the [Player].
Parameters
uint32 entry : entry of a [Quest]
    {
        uint32 entry = Eluna::CHECKVAL<uint32>(L, 2);
        player->FailQuest(entry);
        return 0;
    }
References Player::FailQuest().
GetAccountId()
int LuaPlayer::GetAccountId (lua_State * L, Player * player)
Returns the [Player]s account ID
Returns
uint32 accountId
    {
        Eluna::Push(L, player->GetSession()->GetAccountId());
        return 1;
    }
References WorldSession::GetAccountId(), Player::GetSession(), and Eluna::Push().
GetAccountName()
int LuaPlayer::GetAccountName (lua_State * L, Player * player)
Returns the [Player]s account name
Returns
string accountName
    {
        std::string accName;
#ifndef AZEROTHCORE
        if (eAccountMgr->GetName(player->GetSession()->GetAccountId(), accName))
#else
        if (AccountMgr::GetName(player->GetSession()->GetAccountId(), accName))
#endif
            Eluna::Push(L, accName);
        return 1;
    }
References eAccountMgr, WorldSession::GetAccountId(), AccountMgr::GetName(), Player::GetSession(), and Eluna::Push().
GetAchievementCriteriaProgress()
int LuaPlayer::GetAchievementCriteriaProgress (lua_State * L, Player * player)
Returns the progress of the [Player] for the specified achievement criteria.
Parameters
uint32 criteriaId
Returns
uint32 progress : progress value or nil
    {
        uint32 criteriaId = Eluna::CHECKVAL<uint32>(L, 2);
        const AchievementCriteriaEntry* criteria = sAchievementCriteriaStore.LookupEntry(criteriaId);
        CriteriaProgress* progress = player->GetAchievementMgr()->GetCriteriaProgress(criteria);
        if (progress)
        {
            Eluna::Push(L, progress->counter);
        }
        else
        {
            Eluna::Push(L, (void*)nullptr);
        }
        return 1;
    }
References CriteriaProgress::counter, Player::GetAchievementMgr(), AchievementMgr::GetCriteriaProgress(), Eluna::Push(), and sAchievementCriteriaStore.
GetActiveSpec()
int LuaPlayer::GetActiveSpec (lua_State * L, Player * player)
Returns the [Player]s active spec ID
Returns
uint32 specId
    {
        Eluna::Push(L, player->GetActiveSpec());
        return 1;
    }
References Player::GetActiveSpec(), and Eluna::Push().
GetBaseSkillValue()
int LuaPlayer::GetBaseSkillValue (lua_State * L, Player * player)
Returns base skill value
Parameters
uint32 skill
Returns
uint16 baseVal
    {
        uint32 skill = Eluna::CHECKVAL<uint32>(L, 2);
        Eluna::Push(L, player->GetBaseSkillValue(skill));
        return 1;
    }
References Player::GetBaseSkillValue(), and Eluna::Push().
GetBattlegroundId()
int LuaPlayer::GetBattlegroundId (lua_State * L, Player * player)
Returns the [Player]s current [BattleGround] ID
Returns
uint32 battleGroundId
    {
#if defined TRINITY || AZEROTHCORE
        Eluna::Push(L, player->GetBattlegroundId());
#else
        Eluna::Push(L, player->GetBattleGroundId());
#endif
        return 1;
    }
References Player::GetBattlegroundId(), and Eluna::Push().
GetBattlegroundTypeId()
int LuaPlayer::GetBattlegroundTypeId (lua_State * L, Player * player)
Returns the [Player]s current [BattleGround] type ID
Returns
[BattleGroundTypeId] typeId
    {
#if defined TRINITY || AZEROTHCORE
        Eluna::Push(L, player->GetBattlegroundTypeId());
#else
        Eluna::Push(L, player->GetBattleGroundTypeId());
#endif
        return 1;
    }
References Player::GetBattlegroundTypeId(), and Eluna::Push().
GetChatTag()
int LuaPlayer::GetChatTag (lua_State * L, Player * player)
Returns active GM chat tag
Returns
uint8 tag
    {
        Eluna::Push(L, player->GetChatTag());
        return 1;
    }
References Player::GetChatTag(), and Eluna::Push().
GetCoinage()
int LuaPlayer::GetCoinage (lua_State * L, Player * player)
Returns the [Player]s amount of money in copper
Returns
uint32 coinage
    {
        Eluna::Push(L, player->GetMoney());
        return 1;
    }
References Player::GetMoney(), and Eluna::Push().
GetComboPoints()
int LuaPlayer::GetComboPoints (lua_State * L, Player * player)
Returns [Player]'s combo points
Returns
uint8 comboPoints
    {
        Eluna::Push(L, player->GetComboPoints());
        return 1;
    }
References Unit::GetComboPoints(), and Eluna::Push().
GetComboTarget()
int LuaPlayer::GetComboTarget (lua_State * L, Player * player)
Returns [Unit] target combo points are on
Returns
[Unit] target
    {
#if defined TRINITY || AZEROTHCORE
        Eluna::Push(L, player->GetComboTarget());
#else
        Eluna::Push(L, player->GetMap()->GetUnit(player->GetComboTargetGuid()));
#endif
        return 1;
    }
References Unit::GetComboTarget(), WorldObject::GetMap(), and Eluna::Push().
GetCompletedQuestsCount()
int LuaPlayer::GetCompletedQuestsCount (lua_State * L, Player * player)
Returns the [Player]s completed quest count
Returns
int32 questcount
    {
        uint32 count = player->GetRewardedQuestCount();
        Eluna::Push(L, count);
        return 1;
    }
References Player::GetRewardedQuestCount(), and Eluna::Push().
GetCorpse()
int LuaPlayer::GetCorpse (lua_State * L, Player * player)
Returns the [Player]s [Corpse] object
Returns
[Corpse] corpse
    {
        Eluna::Push(L, player->GetCorpse());
        return 1;
    }
References Player::GetCorpse(), and Eluna::Push().
GetDbcLocale()
int LuaPlayer::GetDbcLocale (lua_State * L, Player * player)
Returns the [Player]s game client locale
Returns
[LocaleConstant] locale
    {
        Eluna::Push(L, player->GetSession()->GetSessionDbcLocale());
        return 1;
    }
References Player::GetSession(), WorldSession::GetSessionDbcLocale(), and Eluna::Push().
GetDbLocaleIndex()
int LuaPlayer::GetDbLocaleIndex (lua_State * L, Player * player)
Returns the [Player]s database locale index
Returns
int localeIndex
    {
        Eluna::Push(L, player->GetSession()->GetSessionDbLocaleIndex());
        return 1;
    }
References Player::GetSession(), WorldSession::GetSessionDbLocaleIndex(), and Eluna::Push().
GetDifficulty()
int LuaPlayer::GetDifficulty (lua_State * L, Player * player)
Returns raid or dungeon difficulty
Parameters
bool isRaid = true : argument is TrinityCore only
Returns
int32 difficulty
    {
#ifdef TBC
        Eluna::Push(L, player->GetDifficulty());
#elif defined(CLASSIC)
        Eluna::Push(L, (Difficulty)0);
#else
        bool isRaid = Eluna::CHECKVAL<bool>(L, 2, true);
        Eluna::Push(L, player->GetDifficulty(isRaid));
#endif
        return 1;
    }
References Player::GetDifficulty(), and Eluna::Push().
GetDrunkValue()
int LuaPlayer::GetDrunkValue (lua_State * L, Player * player)
Returns the [Player]s current level of intoxication
Returns
uint16 drunkValue
    {
        Eluna::Push(L, player->GetDrunkValue());
        return 1;
    }
References Player::GetDrunkValue(), and Eluna::Push().
GetEquippedItemBySlot()
int LuaPlayer::GetEquippedItemBySlot (lua_State * L, Player * player)
Returns a [Player]s [Item] object by gear slot specified
Parameters
uint8 slot
Returns
[Item] item
    {
        uint8 slot = Eluna::CHECKVAL<uint8>(L, 2);
        if (slot >= EQUIPMENT_SLOT_END)
            return 1;
        Item* item = player->GetItemByPos(INVENTORY_SLOT_BAG_0, slot);
        Eluna::Push(L, item);
        return 1;
    }
References EQUIPMENT_SLOT_END, Player::GetItemByPos(), INVENTORY_SLOT_BAG_0, and Eluna::Push().
GetFreeTalentPoints()
int LuaPlayer::GetFreeTalentPoints (lua_State * L, Player * player)
Returns the [Player]s free talent point amount
Returns
uint32 freeTalentPointAmt
    {
        Eluna::Push(L, player->GetFreeTalentPoints());
        return 1;
    }
References Player::GetFreeTalentPoints(), and Eluna::Push().
GetGlyph()
int LuaPlayer::GetGlyph (lua_State * L, Player * player)
Get glyphId of the glyph slot specified by slotIndex off the [Player]'s current talent specialization.`
Parameters
uint32 slotIndex
Returns
glyphId of the glyph in the selected glyph slot or 0 in case the glyph slot is empty
    {
        auto slotIndex = Eluna::CHECKVAL<uint32>(L, 2);
        Eluna::Push(L,player->GetGlyph(slotIndex));
        return 1;
    }
References Player::GetGlyph(), and Eluna::Push().
GetGMRank()
int LuaPlayer::GetGMRank (lua_State * L, Player * player)
Returns the [Player]s GM Rank
Returns
[AccountTypes] gmRank
    {
        Eluna::Push(L, player->GetSession()->GetSecurity());
        return 1;
    }
References WorldSession::GetSecurity(), Player::GetSession(), and Eluna::Push().
GetGossipTextId()
int LuaPlayer::GetGossipTextId (lua_State * L, Player * player)
Returns the database textID of the [WorldObject]'s gossip header text for the [Player]
Parameters
[WorldObject] object
Returns
uint32 textId : key to npc_text database table
    {
        WorldObject* obj = Eluna::CHECKOBJ<WorldObject>(L, 2);
        Eluna::Push(L, player->GetGossipTextId(obj));
        return 1;
    }
References Player::GetGossipTextId(), and Eluna::Push().
GetGroup()
int LuaPlayer::GetGroup (lua_State * L, Player * player)
Returns the [Player]s [Group] object
Returns
[Group] group
    {
        Eluna::Push(L, player->GetGroup());
        return 1;
    }
References Player::GetGroup(), and Eluna::Push().
GetGroupInvite()
int LuaPlayer::GetGroupInvite (lua_State * L, Player * player)
Returns [Group] invitation
Returns
[Group] group
    {
        Eluna::Push(L, player->GetGroupInvite());
        return 1;
    }
References Player::GetGroupInvite(), and Eluna::Push().
GetGuild()
int LuaPlayer::GetGuild (lua_State * L, Player * player)
Returns the [Player]s [Guild] object
Returns
[Guild] guild
    {
        Eluna::Push(L, eGuildMgr->GetGuildById(player->GetGuildId()));
        return 1;
    }
References eGuildMgr, Player::GetGuildId(), and Eluna::Push().
GetGuildId()
int LuaPlayer::GetGuildId (lua_State * L, Player * player)
Returns the [Player]s current [Guild] ID
Returns
uint32 guildId
    {
        Eluna::Push(L, player->GetGuildId());
        return 1;
    }
References Player::GetGuildId(), and Eluna::Push().
GetGuildName()
int LuaPlayer::GetGuildName (lua_State * L, Player * player)
Returns the name of the [Player]s current [Guild]
Returns
string guildName
    {
        if (!player->GetGuildId())
            return 1;
        Eluna::Push(L, eGuildMgr->GetGuildNameById(player->GetGuildId()));
        return 1;
    }
References eGuildMgr, Player::GetGuildId(), and Eluna::Push().
GetGuildRank()
int LuaPlayer::GetGuildRank (lua_State * L, Player * player)
Returns the [Player]s current guild rank
Returns
uint32 guildRank
    {
        Eluna::Push(L, player->GetRank());
        return 1;
    }
References Player::GetRank(), and Eluna::Push().
GetHealthBonusFromStamina()
int LuaPlayer::GetHealthBonusFromStamina (lua_State * L, Player * player)
Returns health bonus from amount of stamina
Returns
float bonus
    {
        Eluna::Push(L, player->GetHealthBonusFromStamina());
        return 1;
    }
References Player::GetHealthBonusFromStamina(), and Eluna::Push().
GetInGameTime()
int LuaPlayer::GetInGameTime (lua_State * L, Player * player)
Returns the amount of time the [Player] has spent ingame
Returns
uint32 inGameTime
    {
        Eluna::Push(L, player->GetInGameTime());
        return 1;
    }
References Player::GetInGameTime(), and Eluna::Push().
GetItemByEntry()
int LuaPlayer::GetItemByEntry (lua_State * L, Player * player)
Returns an [Item] from the player by entry.
The item can be equipped, in bags or in bank.
Parameters
uint32 entryId
Returns
[Item] item
    {
        uint32 entry = Eluna::CHECKVAL<uint32>(L, 2);
        Eluna::Push(L, player->GetItemByEntry(entry));
        return 1;
    }
References Player::GetItemByEntry(), and Eluna::Push().
GetItemByGUID()
int LuaPlayer::GetItemByGUID (lua_State * L, Player * player)
Returns an [Item] from the player by guid.
The item can be equipped, in bags or in bank.
Parameters
ObjectGuid guid : an item guid
Returns
[Item] item
    {
        ObjectGuid guid = Eluna::CHECKVAL<ObjectGuid>(L, 2);
        Eluna::Push(L, player->GetItemByGuid(guid));
        return 1;
    }
References Player::GetItemByGuid(), and Eluna::Push().
GetItemByPos()
int LuaPlayer::GetItemByPos (lua_State * L, Player * player)
Returns an item in given bag on given slot.
Possible and most commonly used combinations:
bag = 255
slots 0-18 equipment
slots 19-22 equipped bag slots
slots 23-38 backpack
slots 39-66 bank main slots
slots 67-74 bank bag slots
slots 86-117 keyring
bag = 19-22
slots 0-35 for equipped bags
bag = 67-74
slots 0-35 for bank bags
Parameters
uint8 bag : the bag the [Item] is in, you can get this with [Item:GetBagSlot]
uint8 slot : the slot the [Item] is in within the bag, you can get this with [Item:GetSlot]
Returns
[Item] item : [Item] or nil
    {
        uint8 bag = Eluna::CHECKVAL<uint8>(L, 2);
        uint8 slot = Eluna::CHECKVAL<uint8>(L, 3);
        Eluna::Push(L, player->GetItemByPos(bag, slot));
        return 1;
    }
References Player::GetItemByPos(), and Eluna::Push().
GetItemCount()
int LuaPlayer::GetItemCount (lua_State * L, Player * player)
Returns amount of the specified [Item] the [Player] has.
Parameters
uint32 entry : entry of the item
bool checkinBank = false : also counts the items in player's bank if true
Returns
uint32 itemamount
    {
        uint32 entry = Eluna::CHECKVAL<uint32>(L, 2);
        bool checkinBank = Eluna::CHECKVAL<bool>(L, 3, false);
        Eluna::Push(L, player->GetItemCount(entry, checkinBank));
        return 1;
    }
References Player::GetItemCount(), and Eluna::Push().
GetLatency()
int LuaPlayer::GetLatency (lua_State * L, Player * player)
Returns the [Player]s current latency in MS
Returns
uint32 latency
    {
        Eluna::Push(L, player->GetSession()->GetLatency());
        return 1;
    }
References WorldSession::GetLatency(), Player::GetSession(), and Eluna::Push().
GetLevelPlayedTime()
int LuaPlayer::GetLevelPlayedTime (lua_State * L, Player * player)
Returns the [Player]s time played at current level
Returns
uint32 currLevelPlayTime
    {
        Eluna::Push(L, player->GetLevelPlayedTime());
        return 1;
    }
References Player::GetLevelPlayedTime(), and Eluna::Push().
GetLifetimeKills()
int LuaPlayer::GetLifetimeKills (lua_State * L, Player * player)
Returns the [Player]s lifetime Honorable Kills
Returns
uint32 lifeTimeKils
    {
        Eluna::Push(L, player->GetUInt32Value(PLAYER_FIELD_LIFETIME_HONORABLE_KILLS));
        return 1;
    }
References Object::GetUInt32Value(), PLAYER_FIELD_LIFETIME_HONORABLE_KILLS, and Eluna::Push().
GetMailCount()
int LuaPlayer::GetMailCount (lua_State * L, Player * player)
Returns the amount of mails in the player's mailbox.
Returns
uint32 mailCount
    {
        const CharacterCacheEntry* cache = sCharacterCache->GetCharacterCacheByGuid(player->GetGUID());
        if (cache)
        {
            Eluna::Push(L, static_cast<uint32>(cache->MailCount));
        }
        else
        {
            Eluna::Push(L, player->GetMailSize());
        }
        return 1;
    }
References Object::GetGUID(), Player::GetMailSize(), CharacterCacheEntry::MailCount, Eluna::Push(), and sCharacterCache.
GetMailItem()
int LuaPlayer::GetMailItem (lua_State * L, Player * player)
Returns a mailed [Item] by guid.
Parameters
ObjectGuid guid : an item guid
Returns
[Item] item
    {
        ObjectGuid guid = Eluna::CHECKVAL<ObjectGuid>(L, 2);
        Eluna::Push(L, player->GetMItem(guid.GetCounter()));
        return 1;
    }
References ObjectGuid::GetCounter(), Player::GetMItem(), and Eluna::Push().
GetManaBonusFromIntellect()
int LuaPlayer::GetManaBonusFromIntellect (lua_State * L, Player * player)
Returns mana bonus from amount of intellect
Returns
float bonus
    {
        Eluna::Push(L, player->GetManaBonusFromIntellect());
        return 1;
    }
References Player::GetManaBonusFromIntellect(), and Eluna::Push().
GetMaxSkillValue()
int LuaPlayer::GetMaxSkillValue (lua_State * L, Player * player)
Returns max value of specified skill
Parameters
uint32 skill
Returns
uint16 val
    {
        uint32 skill = Eluna::CHECKVAL<uint32>(L, 2);
        Eluna::Push(L, player->GetMaxSkillValue(skill));
        return 1;
    }
References Player::GetMaxSkillValue(), and Eluna::Push().
GetNextRandomRaidMember()
int LuaPlayer::GetNextRandomRaidMember (lua_State * L, Player * player)
Returns a random Raid Member [Player] object within radius specified of [Player]
Parameters
float radius
Returns
[Player] player
    {
        float radius = Eluna::CHECKVAL<float>(L, 2);
        Eluna::Push(L, player->GetNextRandomRaidMember(radius));
        return 1;
    }
References Player::GetNextRandomRaidMember(), and Eluna::Push().
GetOriginalGroup()
int LuaPlayer::GetOriginalGroup (lua_State * L, Player * player)
Returns [Player]s original [Group] object
Returns
[Group] group
    {
        Eluna::Push(L, player->GetOriginalGroup());
        return 1;
    }
References Player::GetOriginalGroup(), and Eluna::Push().
GetOriginalSubGroup()
int LuaPlayer::GetOriginalSubGroup (lua_State * L, Player * player)
Returns [Player]s original sub group
Returns
uint8 subGroup
    {
        Eluna::Push(L, player->GetOriginalSubGroup());
        return 1;
    }
References Player::GetOriginalSubGroup(), and Eluna::Push().
GetPlayerIP()
int LuaPlayer::GetPlayerIP (lua_State * L, Player * player)
Returns the [Player]s IP address
Returns
string ip
    {
        Eluna::Push(L, player->GetSession()->GetRemoteAddress());
        return 1;
    }
References WorldSession::GetRemoteAddress(), Player::GetSession(), and Eluna::Push().
GetPlayerSettingValue()
int LuaPlayer::GetPlayerSettingValue (lua_State * L, Player * player)
Gets a setting value for the [Player]
Parameters
string source
uint32 index
    {
        std::string source = Eluna::CHECKVAL<std::string>(L, 2);
        uint32 index = Eluna::CHECKVAL<uint32>(L, 3);
        uint32 value = player->GetPlayerSetting(source, index).value;
        Eluna::Push(L, value);
        return 1;
    }
References Player::GetPlayerSetting(), Eluna::Push(), and PlayerSetting::value.
GetPureMaxSkillValue()
int LuaPlayer::GetPureMaxSkillValue (lua_State * L, Player * player)
Returns max value of specified skill without bonus'
Parameters
uint32 skill
Returns
uint16 pureVal
    {
        uint32 skill = Eluna::CHECKVAL<uint32>(L, 2);
        Eluna::Push(L, player->GetPureMaxSkillValue(skill));
        return 1;
    }
References Player::GetPureMaxSkillValue(), and Eluna::Push().
GetPureSkillValue()
int LuaPlayer::GetPureSkillValue (lua_State * L, Player * player)
Returns skill value without bonus'
Parameters
uint32 skill
Returns
uint16 pureVal
    {
        uint32 skill = Eluna::CHECKVAL<uint32>(L, 2);
        Eluna::Push(L, player->GetPureSkillValue(skill));
        return 1;
    }
References Player::GetPureSkillValue(), and Eluna::Push().
GetQuestLevel()
int LuaPlayer::GetQuestLevel (lua_State * L, Player * player)
Returns the quest level of the [Player]s [Quest] specified by object
Parameters
uint32 questId
Returns
[QuestStatus] questRewardStatus
    {
        Quest* quest = Eluna::CHECKOBJ<Quest>(L, 2);
#if defined TRINITY || AZEROTHCORE
        Eluna::Push(L, player->GetQuestLevel(quest));
#else
        Eluna::Push(L, player->GetQuestLevelForPlayer(quest));
#endif
        return 1;
    }
References Player::GetQuestLevel(), and Eluna::Push().
GetQuestRewardStatus()
int LuaPlayer::GetQuestRewardStatus (lua_State * L, Player * player)
Returns true if the [Player]s [Quest] specified by entry ID has been rewarded, false otherwise.
Parameters
uint32 questId
Returns
bool questRewardStatus
    {
        uint32 questId = Eluna::CHECKVAL<uint32>(L, 2);
        Eluna::Push(L, player->GetQuestRewardStatus(questId));
        return 1;
    }
References Player::GetQuestRewardStatus(), and Eluna::Push().
GetQuestStatus()
int LuaPlayer::GetQuestStatus (lua_State * L, Player * player)
Returns the status of the [Player]s [Quest] specified by entry ID
Parameters
uint32 questId
Returns
[QuestStatus] questStatus
    {
        uint32 entry = Eluna::CHECKVAL<uint32>(L, 2);
        Eluna::Push(L, player->GetQuestStatus(entry));
        return 1;
    }
References Player::GetQuestStatus(), and Eluna::Push().
GetReputation()
int LuaPlayer::GetReputation (lua_State * L, Player * player)
Returns the amount of reputation the [Player] has with the faction specified
Parameters
uint32 faction
Returns
int32 reputationAmt
    {
        uint32 faction = Eluna::CHECKVAL<uint32>(L, 2);
        Eluna::Push(L, player->GetReputationMgr().GetReputation(faction));
        return 1;
    }
References ReputationMgr::GetReputation(), Player::GetReputationMgr(), and Eluna::Push().
GetReputationRank()
int LuaPlayer::GetReputationRank (lua_State * L, Player * player)
Returns the [Player]s reputation rank of faction specified
Parameters
uint32 faction
Returns
[ReputationRank] rank
    {
        uint32 faction = Eluna::CHECKVAL<uint32>(L, 2);
        Eluna::Push(L, player->GetReputationRank(faction));
        return 1;
    }
References Player::GetReputationRank(), and Eluna::Push().
GetReqKillOrCastCurrentCount()
int LuaPlayer::GetReqKillOrCastCurrentCount (lua_State * L, Player * player)
Returns [Quest] required [Creature] or [GameObject] count
Parameters
uint32 quest : entry of a quest
int32 entry : entry of required [Creature]
Returns
uint16 count
    {
        uint32 questId = Eluna::CHECKVAL<uint32>(L, 2);
        int32 entry = Eluna::CHECKVAL<int32>(L, 3);
        Eluna::Push(L, player->GetReqKillOrCastCurrentCount(questId, entry));
        return 1;
    }
References Player::GetReqKillOrCastCurrentCount(), and Eluna::Push().
GetRestBonus()
int LuaPlayer::GetRestBonus (lua_State * L, Player * player)
Returns the [Player]s current resting bonus
Returns
float restBonus
    {
        Eluna::Push(L, player->GetRestBonus());
        return 1;
    }
References Player::GetRestBonus(), and Eluna::Push().
GetSelection()
int LuaPlayer::GetSelection (lua_State * L, Player * player)
Returns the [Player]s currently selected [Unit] object
Returns
[Unit] unit
    {
#if defined TRINITY || AZEROTHCORE
        Eluna::Push(L, player->GetSelectedUnit());
#else
        Eluna::Push(L, player->GetMap()->GetUnit(player->GetSelectionGuid()));
#endif
        return 1;
    }
References WorldObject::GetMap(), Player::GetSelectedUnit(), and Eluna::Push().
GetSkillPermBonusValue()
int LuaPlayer::GetSkillPermBonusValue (lua_State * L, Player * player)
Returns skill permanent bonus value
Parameters
uint32 skill
int16 bonusVal
    {
        uint32 skill = Eluna::CHECKVAL<uint32>(L, 2);
        Eluna::Push(L, player->GetSkillPermBonusValue(skill));
        return 1;
    }
References Player::GetSkillPermBonusValue(), and Eluna::Push().
GetSkillTempBonusValue()
int LuaPlayer::GetSkillTempBonusValue (lua_State * L, Player * player)
Returns skill temporary bonus value
Parameters
uint32 skill
int16 bonusVal
    {
        uint32 skill = Eluna::CHECKVAL<uint32>(L, 2);
        Eluna::Push(L, player->GetSkillTempBonusValue(skill));
        return 1;
    }
References Player::GetSkillTempBonusValue(), and Eluna::Push().
GetSkillValue()
int LuaPlayer::GetSkillValue (lua_State * L, Player * player)
Returns skill value
Parameters
uint32 skill
Returns
uint16 val
    {
        uint32 skill = Eluna::CHECKVAL<uint32>(L, 2);
        Eluna::Push(L, player->GetSkillValue(skill));
        return 1;
    }
References Player::GetSkillValue(), and Eluna::Push().
GetSpecsCount()
int LuaPlayer::GetSpecsCount (lua_State * L, Player * player)
Returns the amount of available specs the [Player] currently has
Returns
uint8 specCount
    {
        Eluna::Push(L, player->GetSpecsCount());
        return 1;
    }
References Player::GetSpecsCount(), and Eluna::Push().
GetSpellCooldownDelay()
int LuaPlayer::GetSpellCooldownDelay (lua_State * L, Player * player)
Returns the [Player]s cooldown delay by specified [Spell] ID
Parameters
uint32 spellId
Returns
uint32 spellCooldownDelay
    {
        uint32 spellId = Eluna::CHECKVAL<uint32>(L, 2);
#ifdef TRINITY
        if (SpellInfo const* spellInfo = sSpellMgr->GetSpellInfo(spellId))
            Eluna::Push(L, player->GetSpellHistory()->GetRemainingCooldown(spellInfo));
        else
            Eluna::Push(L, 0);
#else
        Eluna::Push(L, uint32(player->GetSpellCooldownDelay(spellId)));
#endif
        return 1;
    }
References Player::GetSpellCooldownDelay(), Eluna::Push(), and sSpellMgr.
GetSubGroup()
int LuaPlayer::GetSubGroup (lua_State * L, Player * player)
Returns [Player]s current sub group
Returns
uint8 subGroup
    {
        Eluna::Push(L, player->GetSubGroup());
        return 1;
    }
References Player::GetSubGroup(), and Eluna::Push().
GetTeam()
int LuaPlayer::GetTeam (lua_State * L, Player * player)
Returns the [Player]s [TeamId]
Returns
[TeamId] teamId
    {
        Eluna::Push(L, player->GetTeamId());
        return 1;
    }
References Player::GetTeamId(), and Eluna::Push().
GetTotalPlayedTime()
int LuaPlayer::GetTotalPlayedTime (lua_State * L, Player * player)
Returns the [Player]s total time played
Returns
uint32 totalPlayTime
    {
        Eluna::Push(L, player->GetTotalPlayedTime());
        return 1;
    }
References Player::GetTotalPlayedTime(), and Eluna::Push().
GetTrader()
int LuaPlayer::GetTrader (lua_State * L, Player * player)
Returns the [Player] that is currently trading with this [Player]
Returns
[Player] trader : the player trading, or nil
    {
        Eluna::Push(L, player->GetTrader());
        return 1;
    }
References Player::GetTrader(), and Eluna::Push().
GetXP()
int LuaPlayer::GetXP (lua_State * L, Player * player)
Returns the [Player]'s experience points
Returns
uint32 xp
    {
        Eluna::Push(L, player->GetUInt32Value(PLAYER_XP));
        return 1;
    }
References Object::GetUInt32Value(), PLAYER_XP, and Eluna::Push().
GetXPRestBonus()
int LuaPlayer::GetXPRestBonus (lua_State * L, Player * player)
Returns rested experience bonus
Parameters
uint32 xp
Returns
uint32 xpBonus
    {
        uint32 xp = Eluna::CHECKVAL<uint32>(L, 2);
        Eluna::Push(L, player->GetXPRestBonus(xp));
        return 1;
    }
References Player::GetXPRestBonus(), and Eluna::Push().
GiveXP()
int LuaPlayer::GiveXP (lua_State * L, Player * player)
Gives the [Player] experience
Parameters
uint32 xp : experience to give
[Unit] victim = nil
    {
        uint32 xp = Eluna::CHECKVAL<uint32>(L, 2);
        Unit* victim = Eluna::CHECKOBJ<Unit>(L, 3, false);
        player->GiveXP(xp, victim);
        return 0;
    }
References Player::GiveXP().
GossipAddQuests()
int LuaPlayer::GossipAddQuests (lua_State * L, Player * player)
Adds the gossip items to the [Player]'s gossip for the quests the given [WorldObject] can offer to the player.
Parameters
[WorldObject] source : a questgiver with quests
    {
        WorldObject* source = Eluna::CHECKOBJ<WorldObject>(L, 2);
        if (source->GetTypeId() == TYPEID_UNIT)
        {
            if (source->GetUInt32Value(UNIT_NPC_FLAGS) & UNIT_NPC_FLAG_QUESTGIVER)
                player->PrepareQuestMenu(source->GET_GUID());
        }
        else if (source->GetTypeId() == TYPEID_GAMEOBJECT)
        {
            if (source->ToGameObject()->GetGoType() == GAMEOBJECT_TYPE_QUESTGIVER)
                player->PrepareQuestMenu(source->GET_GUID());
        }
        return 0;
    }
References GAMEOBJECT_TYPE_QUESTGIVER, GameObject::GetGoType(), Object::GetTypeId(), Object::GetUInt32Value(), Player::PrepareQuestMenu(), Object::ToGameObject(), TYPEID_GAMEOBJECT, TYPEID_UNIT, UNIT_NPC_FLAG_QUESTGIVER, and UNIT_NPC_FLAGS.
GossipClearMenu()
int LuaPlayer::GossipClearMenu (lua_State * , Player * player)
Clears the [Player]s current gossip item list.
See also: [Player:GossipMenuAddItem], [Player:GossipSendMenu], [Player:GossipAddQuests], [Player:GossipComplete]
Note: This is needed when you show a gossip menu without using gossip hello or select hooks which do this automatically.
Usually this is needed when using [Player] is the sender of a Gossip Menu.
    {
        player->PlayerTalkClass->ClearMenus();
        return 0;
    }
References PlayerMenu::ClearMenus(), and Player::PlayerTalkClass.
GossipComplete()
int LuaPlayer::GossipComplete (lua_State * , Player * player)
Closes the [Player]s currently open Gossip Menu.
See also: [Player:GossipMenuAddItem], [Player:GossipAddQuests], [Player:GossipSendMenu], [Player:GossipClearMenu]
    {
#if defined TRINITY || AZEROTHCORE
        player->PlayerTalkClass->SendCloseGossip();
#else
        player->PlayerTalkClass->CloseGossip();
#endif
        return 0;
    }
References Player::PlayerTalkClass, and PlayerMenu::SendCloseGossip().
GossipMenuAddItem()
int LuaPlayer::GossipMenuAddItem (lua_State * L, Player * player)
Adds a new item to the gossip menu shown to the [Player] on next call to [Player:GossipSendMenu].
sender and intid are numbers which are passed directly to the gossip selection handler. Internally they are partly used for the database gossip handling.
code specifies whether to show a box to insert text to. The player inserted text is passed to the gossip selection handler.
money specifies an amount of money the player needs to have to click the option. An error message is shown if the player doesn't have enough money.
Note that the money amount is only checked client side and is not removed from the player either. You will need to check again in your code before taking action.
See also: [Player:GossipSendMenu], [Player:GossipAddQuests], [Player:GossipComplete], [Player:GossipClearMenu]
Parameters
uint32 icon : number that specifies used icon
string msg : label on the gossip item
uint32 sender : number passed to gossip handlers
uint32 intid : number passed to gossip handlers
bool code = false : show text input on click if true
string popup = nil : if non empty string, a popup with given text shown on click
uint32 money = 0 : required money in copper
    {
        uint32 _icon = Eluna::CHECKVAL<uint32>(L, 2);
        const char* msg = Eluna::CHECKVAL<const char*>(L, 3);
        uint32 _sender = Eluna::CHECKVAL<uint32>(L, 4);
        uint32 _intid = Eluna::CHECKVAL<uint32>(L, 5);
        bool _code = Eluna::CHECKVAL<bool>(L, 6, false);
        const char* _promptMsg = Eluna::CHECKVAL<const char*>(L, 7, "");
        uint32 _money = Eluna::CHECKVAL<uint32>(L, 8, 0);
#if defined TRINITY || AZEROTHCORE
        if (player->PlayerTalkClass->GetGossipMenu().GetMenuItemCount() < GOSSIP_MAX_MENU_ITEMS)
        {
            player->PlayerTalkClass->GetGossipMenu().AddMenuItem(-1, _icon, msg, _sender, _intid, _promptMsg, _money,
                                                                 _code);
        }
        else
        {
            return luaL_error(L, "GossipMenuItem not added. Reached Max amount of possible GossipMenuItems in this GossipMenu");
        }
#else
#ifndef CLASSIC
        player->PlayerTalkClass->GetGossipMenu().AddMenuItem(_icon, msg, _sender, _intid, _promptMsg, _money, _code);
#else
        player->PlayerTalkClass->GetGossipMenu().AddMenuItem(_icon, msg, _sender, _intid, _promptMsg, _code);
#endif
#endif//TRINITY
        return 0;
    }
References GossipMenu::AddMenuItem(), PlayerMenu::GetGossipMenu(), GossipMenu::GetMenuItemCount(), GOSSIP_MAX_MENU_ITEMS, luaL_error(), and Player::PlayerTalkClass.
GossipSendMenu()
int LuaPlayer::GossipSendMenu (lua_State * L, Player * player)
Sends the current gossip items of the player to him as a gossip menu with header text from the given textId.
If sender is a [Player] then menu_id is mandatory, otherwise it is not used for anything. menu_id is the ID used to trigger the OnGossipSelect registered for players. See [Global:RegisterPlayerGossipEvent]
See also: [Player:GossipMenuAddItem], [Player:GossipAddQuests], [Player:GossipComplete], [Player:GossipClearMenu]
@proto (npc_text, sender) @proto (npc_text, sender, menu_id)
Parameters
uint32 npc_text : entry ID of a header text in npc_text database table, common default is 100
[Object] sender : object acting as the source of the sent gossip menu
uint32 menu_id : if sender is a [Player] then menu_id is mandatory
    {
        uint32 npc_text = Eluna::CHECKVAL<uint32>(L, 2);
        Object* sender = Eluna::CHECKOBJ<Object>(L, 3);
        if (sender->GetTypeId() == TYPEID_PLAYER)
        {
            uint32 menu_id = Eluna::CHECKVAL<uint32>(L, 4);
            player->PlayerTalkClass->GetGossipMenu().SetMenuId(menu_id);
        }
        player->PlayerTalkClass->SendGossipMenu(npc_text, sender->GET_GUID());
        return 0;
    }
References PlayerMenu::GetGossipMenu(), Object::GetTypeId(), Player::PlayerTalkClass, PlayerMenu::SendGossipMenu(), GossipMenu::SetMenuId(), and TYPEID_PLAYER.
GossipSendPOI()
int LuaPlayer::GossipSendPOI (lua_State * L, Player * player)
Sends POI to the location on your map
Parameters
float x
float y
uint32 icon : map icon to show
uint32 flags
uint32 data
string iconText
    {
        float x = Eluna::CHECKVAL<float>(L, 2);
        float y = Eluna::CHECKVAL<float>(L, 3);
        uint32 icon = Eluna::CHECKVAL<uint32>(L, 4);
        uint32 flags = Eluna::CHECKVAL<uint32>(L, 5);
        uint32 data = Eluna::CHECKVAL<uint32>(L, 6);
        std::string iconText = Eluna::CHECKVAL<std::string>(L, 7);
        WorldPacket packet(SMSG_GOSSIP_POI, 4 + 4 + 4 + 4 + 4 + 10);
        packet << flags;
        packet << x;
        packet << y;
        packet << icon;
        packet << data;
        packet << iconText;
#ifdef CMANGOS
        player->GetSession()->SendPacket(packet);
#else
        player->GetSession()->SendPacket(&packet);
#endif
        return 0;
    }
References flags, Player::GetSession(), WorldSession::SendPacket(), and SMSG_GOSSIP_POI.
GroupCreate()
int LuaPlayer::GroupCreate (lua_State * L, Player * player)
Creates a new [Group] with the creator [Player] as leader.
Parameters
[Player] invited : player to add to group
Returns
[Group] createdGroup : the created group or nil
    {
        Player* invited = Eluna::CHECKOBJ<Player>(L, 2);
        if (player->GetGroup() || invited->GetGroup())
            return 0;
        if (player->GetGroupInvite())
            player->UninviteFromGroup();
        if (invited->GetGroupInvite())
            invited->UninviteFromGroup();
        // Try create new group
        Group* group = new Group;
        if (!group->AddLeaderInvite(player))
        {
            delete group;
            return 0;
        }
        // Forming a new group, create it
        if (!group->IsCreated())
        {
            group->RemoveInvite(player);
#if defined TRINITY || AZEROTHCORE
            group->Create(player);
            sGroupMgr->AddGroup(group);
#else
            if (!group->Create(group->GetLeaderGuid(), group->GetLeaderName()))
                return 0;
            sObjectMgr.AddGroup(group);
#endif
        }
#if defined TRINITY || AZEROTHCORE
        if (!group->AddMember(invited))
            return 0;
        group->BroadcastGroupUpdate();
#else
        if (!group->AddMember(invited->GetObjectGuid(), invited->GetName()))
            return 0;
#endif
        Eluna::Push(L, group);
        return 1;
    }
References Group::AddLeaderInvite(), Group::AddMember(), Group::BroadcastGroupUpdate(), Group::Create(), Player::GetGroup(), Player::GetGroupInvite(), Group::GetLeaderName(), WorldObject::GetName(), Group::IsCreated(), Eluna::Push(), Group::RemoveInvite(), sGroupMgr, sObjectMgr, and Player::UninviteFromGroup().
GroupEventHappens()
int LuaPlayer::GroupEventHappens (lua_State * L, Player * player)
Completes a [Quest] if in a [Group]
Parameters
uint32 quest : entry of a quest
[WorldObject] obj
    {
        uint32 questId = Eluna::CHECKVAL<uint32>(L, 2);
        WorldObject* obj = Eluna::CHECKOBJ<WorldObject>(L, 3);
        player->GroupEventHappens(questId, obj);
        return 0;
    }
References Player::GroupEventHappens().
GroupInvite()
int LuaPlayer::GroupInvite (lua_State * L, Player * player)
Makes the [Player] invite another player to a group.
Parameters
[Player] invited : player to invite to group
Returns
bool success : true if the player was invited to a group
    {
        Player* invited = Eluna::CHECKOBJ<Player>(L, 2);
        if (invited->GetGroup() || invited->GetGroupInvite())
        {
            Eluna::Push(L, false);
            return 1;
        }
        // Get correct existing group if any
        Group* group = player->GetGroup();
        if (group && group->isBGGroup())
            group = player->GetOriginalGroup();
        bool success = false;
        // Try invite if group found
        if (group)
            success = !group->IsFull() && group->AddInvite(invited);
        else
        {
            // Create new group if one not found
            group = new Group;
            success = group->AddLeaderInvite(player) && group->AddInvite(invited);
            if (!success)
                delete group;
        }
        if (success)
        {
#if defined(CLASSIC) || defined(TBC)
            WorldPacket data(SMSG_GROUP_INVITE, 10);                // guess size
            data << player->GetName();
#ifdef CMANGOS
            invited->GetSession()->SendPacket(data);
#else
            invited->GetSession()->SendPacket(&data);
#endif
#else
            WorldPacket data(SMSG_GROUP_INVITE, 10);                // guess size
            data << uint8(1);                                       // invited/already in group flag
            data << player->GetName();                              // max len 48
            data << uint32(0);                                      // unk
            data << uint8(0);                                       // count
            data << uint32(0);                                      // unk
#ifdef CMANGOS
            invited->GetSession()->SendPacket(data);
#else
            invited->GetSession()->SendPacket(&data);
#endif
#endif
        }
        Eluna::Push(L, success);
        return 1;
    }
References Group::AddInvite(), Group::AddLeaderInvite(), Player::GetGroup(), Player::GetGroupInvite(), WorldObject::GetName(), Player::GetOriginalGroup(), Player::GetSession(), Group::isBGGroup(), Group::IsFull(), Eluna::Push(), WorldSession::SendPacket(), and SMSG_GROUP_INVITE.
HasAchieved()
int LuaPlayer::HasAchieved (lua_State * L, Player * player)
Returns true if the [Player] has completed the specified achievement, false otherwise.
Parameters
uint32 achievementId
Returns
bool hasAchieved
    {
        uint32 achievementId = Eluna::CHECKVAL<uint32>(L, 2);
#if defined TRINITY || AZEROTHCORE
        Eluna::Push(L, player->HasAchieved(achievementId));
#else
        Eluna::Push(L, player->GetAchievementMgr().HasAchievement(achievementId));
#endif
        return 1;
    }
References Player::GetAchievementMgr(), Player::HasAchieved(), and Eluna::Push().
HasAtLoginFlag()
int LuaPlayer::HasAtLoginFlag (lua_State * L, Player * player)
Returns true if [Player] has specified login flag
Parameters
uint32 flag
Returns
bool hasLoginFlag
    {
        uint32 flag = Eluna::CHECKVAL<uint32>(L, 2);
        Eluna::Push(L, player->HasAtLoginFlag((AtLoginFlags)flag));
        return 1;
    }
References Player::HasAtLoginFlag(), and Eluna::Push().
HasCasterSpec()
int LuaPlayer::HasCasterSpec (lua_State * L, Player * player)
Returns true if the [Player] has a Caster Specialization, false otherwise.
Returns
bool HasCasterSpec
    {
        Eluna::Push(L, player->HasCasterSpec());
        return 1;
    }
References Player::HasCasterSpec(), and Eluna::Push().
HasHealSpec()
int LuaPlayer::HasHealSpec (lua_State * L, Player * player)
Returns true if the [Player] has a Heal Specialization, false otherwise.
Returns
bool HasHealSpec
    {
        Eluna::Push(L, player->HasHealSpec());
        return 1;
    }
References Player::HasHealSpec(), and Eluna::Push().
HasItem()
int LuaPlayer::HasItem (lua_State * L, Player * player)
Returns true if the [Player] has the given amount of item entry specified, false otherwise.
Parameters
uint32 itemId : entry of the item
uint32 count = 1 : amount of items the player needs should have
bool check_bank = false : determines if the item can be in player bank
Returns
bool hasItem
    {
        uint32 itemId = Eluna::CHECKVAL<uint32>(L, 2);
        uint32 count = Eluna::CHECKVAL<uint32>(L, 3, 1);
        bool check_bank = Eluna::CHECKVAL<bool>(L, 4, false);
        Eluna::Push(L, player->HasItemCount(itemId, count, check_bank));
        return 1;
    }
References Player::HasItemCount(), and Eluna::Push().
HasMeleeSpec()
int LuaPlayer::HasMeleeSpec (lua_State * L, Player * player)
Returns true if the [Player] has a Melee Specialization, false otherwise.
Returns
bool HasMeleeSpec
    {
        Eluna::Push(L, player->HasMeleeSpec());
        return 1;
    }
References Player::HasMeleeSpec(), and Eluna::Push().
HasQuest()
int LuaPlayer::HasQuest (lua_State * L, Player * player)
Returns true if the [Player] has an active [Quest] by specific ID, false otherwise.
Parameters
uint32 questId
Returns
bool hasQuest
    {
        uint32 quest = Eluna::CHECKVAL<uint32>(L, 2);
        Eluna::Push(L, player->IsActiveQuest(quest));
        return 1;
    }
References Player::IsActiveQuest(), and Eluna::Push().
HasQuestForGO()
int LuaPlayer::HasQuestForGO (lua_State * L, Player * player)
Returns true if [Player] has [Quest] for [GameObject]
Parameters
int32 entry : entry of a [GameObject]
Returns
bool hasQuest
    {
        int32 entry = Eluna::CHECKVAL<int32>(L, 2);
        Eluna::Push(L, player->HasQuestForGO(entry));
        return 1;
    }
References Player::HasQuestForGO(), and Eluna::Push().
HasQuestForItem()
int LuaPlayer::HasQuestForItem (lua_State * L, Player * player)
Returns true if the [Player] has a quest for the item entry specified, false otherwise.
Parameters
uint32 entry : entry of the item
Returns
bool hasQuest
    {
        uint32 entry = Eluna::CHECKVAL<uint32>(L, 2);
        Eluna::Push(L, player->HasQuestForItem(entry));
        return 1;
    }
References Player::HasQuestForItem(), and Eluna::Push().
HasSkill()
int LuaPlayer::HasSkill (lua_State * L, Player * player)
Returns true if the [Player] has a skill by specific ID, false otherwise.
Parameters
uint32 skill
Returns
bool hasSkill
    {
        uint32 skill = Eluna::CHECKVAL<uint32>(L, 2);
        Eluna::Push(L, player->HasSkill(skill));
        return 1;
    }
References Player::HasSkill(), and Eluna::Push().
HasSpell()
int LuaPlayer::HasSpell (lua_State * L, Player * player)
Returns true if the [Player] has a [Spell] by specific ID, false otherwise.
Parameters
uint32 spellId
Returns
bool hasSpell
    {
        uint32 id = Eluna::CHECKVAL<uint32>(L, 2);
        Eluna::Push(L, player->HasSpell(id));
        return 1;
    }
References Player::HasSpell(), and Eluna::Push().
HasSpellCooldown()
int LuaPlayer::HasSpellCooldown (lua_State * L, Player * player)
Returns true if the [Spell] specified by ID is currently on cooldown for the [Player], false otherwise.
Parameters
uint32 spellId
Returns
bool hasSpellCooldown
    {
        uint32 spellId = Eluna::CHECKVAL<uint32>(L, 2);
#ifdef TRINITY
        Eluna::Push(L, player->GetSpellHistory()->HasCooldown(spellId));
#else
        Eluna::Push(L, player->HasSpellCooldown(spellId));
#endif
        return 1;
    }
References Player::HasSpellCooldown(), and Eluna::Push().
HasTalent()
int LuaPlayer::HasTalent (lua_State * L, Player * player)
Returns true if the [Player] has a talent by ID in specified spec, false otherwise.
Parameters
uint32 spellId : talent spellId to check
uint8 spec : specified spec. 0 for primary, 1 for secondary.
Returns
bool hasTalent
    {
        uint32 spellId = Eluna::CHECKVAL<uint32>(L, 2);
#ifdef MANGOS
        uint8 maxSpecs = MAX_TALENT_SPEC_COUNT;
#else
        uint8 maxSpecs = MAX_TALENT_SPECS;
#endif
        uint8 spec = Eluna::CHECKVAL<uint8>(L, 3);
        if (spec >= maxSpecs)
            return 1;
        Eluna::Push(L, player->HasTalent(spellId, spec));
        return 1;
    }
References Player::HasTalent(), MAX_TALENT_SPECS, and Eluna::Push().
HasTankSpec()
int LuaPlayer::HasTankSpec (lua_State * L, Player * player)
Returns true if the [Player] has a Tank Specialization, false otherwise.
Returns
bool HasTankSpec
    {
        Eluna::Push(L, player->HasTankSpec());
        return 1;
    }
References Player::HasTankSpec(), and Eluna::Push().
HasTitle()
int LuaPlayer::HasTitle (lua_State * L, Player * player)
Returns true if the [Player] has a title by specific ID, false otherwise.
Parameters
uint32 titleId
Returns
bool hasTitle
    {
        uint32 id = Eluna::CHECKVAL<uint32>(L, 2);
        CharTitlesEntry const* titleInfo = sCharTitlesStore.LookupEntry(id);
        if (titleInfo)
            Eluna::Push(L, player->HasTitle(titleInfo));
        return 1;
    }
References Player::HasTitle(), Eluna::Push(), and sCharTitlesStore.
InArena()
int LuaPlayer::InArena (lua_State * L, Player * player)
Returns true if the [Player] is currently in an arena, false otherwise.
Returns
bool inArena
    {
        Eluna::Push(L, player->InArena());
        return 1;
    }
References Player::InArena(), and Eluna::Push().
InBattleground()
int LuaPlayer::InBattleground (lua_State * L, Player * player)
Returns true if the [Player] is currently in a [BattleGround], false otherwise.
Returns
bool inBattleGround
    {
#if defined TRINITY || AZEROTHCORE
        Eluna::Push(L, player->InBattleground());
#else
        Eluna::Push(L, player->InBattleGround());
#endif
        return 1;
    }
References Player::InBattleground(), and Eluna::Push().
InBattlegroundQueue()
int LuaPlayer::InBattlegroundQueue (lua_State * L, Player * player)
Returns true if the [Player] is currently in a [BattleGround] queue, false otherwise.
Returns
bool inBattlegroundQueue
    {
#if defined TRINITY || AZEROTHCORE
        Eluna::Push(L, player->InBattlegroundQueue());
#else
        Eluna::Push(L, player->InBattleGroundQueue());
#endif
        return 1;
    }
References Player::InBattlegroundQueue(), and Eluna::Push().
IncompleteQuest()
int LuaPlayer::IncompleteQuest (lua_State * L, Player * player)
Sets the given quest entry incomplete for the [Player].
Parameters
uint32 entry : quest entry
    {
        uint32 entry = Eluna::CHECKVAL<uint32>(L, 2);
        player->IncompleteQuest(entry);
        return 0;
    }
References Player::IncompleteQuest().
IsAcceptingWhispers()
int LuaPlayer::IsAcceptingWhispers (lua_State * L, Player * player)
Returns true if the [Player] is accepting whispers, false otherwise.
Returns
bool isAcceptingWhispers
    {
        Eluna::Push(L, player->isAcceptWhispers());
        return 1;
    }
References Player::isAcceptWhispers(), and Eluna::Push().
IsAFK()
int LuaPlayer::IsAFK (lua_State * L, Player * player)
Returns true if the [Player] is 'Away From Keyboard' flagged, false otherwise.
Returns
bool isAFK
    {
        Eluna::Push(L, player->isAFK());
        return 1;
    }
References Player::isAFK(), and Eluna::Push().
IsAlliance()
int LuaPlayer::IsAlliance (lua_State * L, Player * player)
Returns true if the [Player] is a part of the Alliance faction, false otherwise.
Returns
bool isAlliance
    {
#ifdef AZEROTHCORE
        Eluna::Push(L, (player->GetTeamId() == TEAM_ALLIANCE));
#else
        Eluna::Push(L, (player->GetTeam() == ALLIANCE));
#endif
        return 1;
    }
References ALLIANCE, Player::GetTeamId(), Eluna::Push(), and TEAM_ALLIANCE.
IsDND()
int LuaPlayer::IsDND (lua_State * L, Player * player)
Returns true if the [Player] is 'Do Not Disturb' flagged, false otherwise.
Returns
bool isDND
    {
        Eluna::Push(L, player->isDND());
        return 1;
    }
References Player::isDND(), and Eluna::Push().
IsFalling()
int LuaPlayer::IsFalling (lua_State * L, Player * player)
Returns true if the [Player] is currently falling, false otherwise.
Returns
bool isFalling
    {
        Eluna::Push(L, player->IsFalling());
        return 1;
    }
References Player::IsFalling(), and Eluna::Push().
IsFlying()
int LuaPlayer::IsFlying (lua_State * L, Player * player)
Returns true if the [Player] is currently flying, false otherwise.
Returns
bool isFlying
    {
        Eluna::Push(L, player->IsFlying());
        return 1;
    }
References Unit::IsFlying(), and Eluna::Push().
IsGM()
int LuaPlayer::IsGM (lua_State * L, Player * player)
Returns true if the [Player] is a Game Master, false otherwise.
Note: This is only true when GM tag is activated! For alternative see [Player:GetGMRank]
Returns
bool isGM
    {
#if defined TRINITY || AZEROTHCORE
        Eluna::Push(L, player->IsGameMaster());
#else
        Eluna::Push(L, player->isGameMaster());
#endif
        return 1;
    }
References Player::IsGameMaster(), and Eluna::Push().
IsGMChat()
int LuaPlayer::IsGMChat (lua_State * L, Player * player)
    {
        Eluna::Push(L, player->isGMChat());
        return 1;
    }
References Player::isGMChat(), and Eluna::Push().
IsGMVisible()
int LuaPlayer::IsGMVisible (lua_State * L, Player * player)
    {
        Eluna::Push(L, player->isGMVisible());
        return 1;
    }
References Player::isGMVisible(), and Eluna::Push().
IsGroupVisibleFor()
int LuaPlayer::IsGroupVisibleFor (lua_State * L, Player * player)
    {
        Player* target = Eluna::CHECKOBJ<Player>(L, 2);
        Eluna::Push(L, player->IsGroupVisibleFor(target));
        return 1;
    }
References Player::IsGroupVisibleFor(), and Eluna::Push().
IsHonorOrXPTarget()
int LuaPlayer::IsHonorOrXPTarget (lua_State * L, Player * player)
Returns true if the [Player] is eligible for Honor or XP gain by [Unit] specified, false otherwise.
Parameters
[Unit] unit
Returns
bool isHonorOrXPTarget
    {
        Unit* victim = Eluna::CHECKOBJ<Unit>(L, 2);
        Eluna::Push(L, player->isHonorOrXPTarget(victim));
        return 1;
    }
References Player::isHonorOrXPTarget(), and Eluna::Push().
IsHorde()
int LuaPlayer::IsHorde (lua_State * L, Player * player)
Returns true if the [Player] is a part of the Horde faction, false otherwise.
Returns
bool isHorde
    {
#ifdef AZEROTHCORE
        Eluna::Push(L, (player->GetTeamId() == TEAM_HORDE));
#else
        Eluna::Push(L, (player->GetTeam() == HORDE));
#endif
        return 1;
    }
References Player::GetTeamId(), HORDE, Eluna::Push(), and TEAM_HORDE.
IsImmuneToDamage()
int LuaPlayer::IsImmuneToDamage (lua_State * L, Player * player)
Returns true if the [Player] is immune to everything.
Returns
bool isImmune
    {
        Eluna::Push(L, player->isTotalImmune());
        return 1;
    }
References Player::isTotalImmune(), and Eluna::Push().
IsInArenaTeam()
int LuaPlayer::IsInArenaTeam (lua_State * L, Player * player)
Returns true if the [Player] is in an arena team specified by type, false otherwise.
Parameters
uint32 type
Returns
bool isInArenaTeam
    {
        uint32 type = Eluna::CHECKVAL<uint32>(L, 2);
        if (type < MAX_ARENA_SLOT && player->GetArenaTeamId(type))
            Eluna::Push(L, true);
        else
            Eluna::Push(L, false);
        return 1;
    }
References Eluna::Push().
IsInGroup()
int LuaPlayer::IsInGroup (lua_State * L, Player * player)
Returns true if the [Player] is in a [Group], false otherwise.
Returns
bool isInGroup
    {
        Eluna::Push(L, (player->GetGroup() != NULL));
        return 1;
    }
References Player::GetGroup(), and Eluna::Push().
IsInGuild()
int LuaPlayer::IsInGuild (lua_State * L, Player * player)
Returns true if the [Player] is in a [Guild], false otherwise.
Returns
bool isInGuild
    {
        Eluna::Push(L, (player->GetGuildId() != 0));
        return 1;
    }
References Player::GetGuildId(), and Eluna::Push().
IsInSameGroupWith()
int LuaPlayer::IsInSameGroupWith (lua_State * L, Player * player)
Returns true if the [Player] is currently in the same [Group] as another [Player] by object, false otherwise.
Parameters
[Player] player
Returns
bool isInSameGroupWith
    {
        Player* target = Eluna::CHECKOBJ<Player>(L, 2);
        Eluna::Push(L, player->IsInSameGroupWith(target));
        return 1;
    }
References Player::IsInSameGroupWith(), and Eluna::Push().
IsInSameRaidWith()
int LuaPlayer::IsInSameRaidWith (lua_State * L, Player * player)
Returns true if the [Player] is currently in the same raid as another [Player] by object, false otherwise.
Parameters
[Player] player
Returns
bool isInSameRaidWith
    {
        Player* target = Eluna::CHECKOBJ<Player>(L, 2);
        Eluna::Push(L, player->IsInSameRaidWith(target));
        return 1;
    }
References Player::IsInSameRaidWith(), and Eluna::Push().
IsInWater()
int LuaPlayer::IsInWater (lua_State * L, Player * player)
Returns true if the [Player] is currently in water, false otherwise.
Returns
bool isInWater
    {
        Eluna::Push(L, player->IsInWater());
        return 1;
    }
References Player::IsInWater(), and Eluna::Push().
IsMoving()
int LuaPlayer::IsMoving (lua_State * L, Player * player)
Returns true if the [Player] is currently moving, false otherwise.
Returns
bool isMoving
    {
        Eluna::Push(L, player->isMoving());
        return 1;
    }
References Unit::isMoving(), and Eluna::Push().
IsRested()
int LuaPlayer::IsRested (lua_State * L, Player * player)
Returns true if the [Player] is currently rested, false otherwise.
Returns
bool isRested
    {
        Eluna::Push(L, player->GetRestBonus() > 0.0f);
        return 1;
    }
References Player::GetRestBonus(), and Eluna::Push().
IsTaxiCheater()
int LuaPlayer::IsTaxiCheater (lua_State * L, Player * player)
Returns true if the [Player] has taxi cheat activated, false otherwise.
Returns
bool isTaxiCheater
    {
#ifdef MANGOS
        Eluna::Push(L, player->IsTaxiCheater());
#else
        Eluna::Push(L, player->isTaxiCheater());
#endif
        return 1;
    }
References Player::isTaxiCheater(), and Eluna::Push().
IsVisibleForPlayer()
int LuaPlayer::IsVisibleForPlayer (lua_State * L, Player * player)
Returns true if the [Player] can see anoter [Player] specified by object, false otherwise.
Parameters
[Player] player
Returns
bool isVisibleForPlayer
    {
        Player* target = Eluna::CHECKOBJ<Player>(L, 2);
        Eluna::Push(L, player->IsVisibleGloballyFor(target));
        return 1;
    }
References Player::IsVisibleGloballyFor(), and Eluna::Push().
KickPlayer()
int LuaPlayer::KickPlayer (lua_State * , Player * player)
Kicks the [Player] from the server
    {
#ifdef TRINITY
        player->GetSession()->KickPlayer("PlayerMethods::KickPlayer Kick the player");
#else
        player->GetSession()->KickPlayer();
#endif
        return 0;
    }
References Player::GetSession(), and WorldSession::KickPlayer().
KilledMonsterCredit()
int LuaPlayer::KilledMonsterCredit (lua_State * L, Player * player)
Gives [Quest] monster killed credit
Parameters
uint32 entry : entry of a [Creature]
    {
        uint32 entry = Eluna::CHECKVAL<uint32>(L, 2);
        player->KilledMonsterCredit(entry, player->GET_GUID());
        return 0;
    }
References Player::KilledMonsterCredit().
KillPlayer()
int LuaPlayer::KillPlayer (lua_State * , Player * player)
Kills the [Player]
    {
        player->KillPlayer();
        return 0;
    }
References Player::KillPlayer().
LearnSpell()
int LuaPlayer::LearnSpell (lua_State * L, Player * player)
Teaches the [Player] the [Spell] specified by entry ID
Parameters
uint32 spellId
    {
        uint32 id = Eluna::CHECKVAL<uint32>(L, 2);
#ifdef TRINITY
        player->LearnSpell(id, false);
#elif AZEROTHCORE
        player->learnSpell(id);
#else
        player->learnSpell(id, false);
#endif
        return 0;
    }
References Player::learnSpell().
LearnTalent()
int LuaPlayer::LearnTalent (lua_State * L, Player * player)
Learn the [Player] the talent specified by talent_id and talentRank
Parameters
uint32 talent_id
uint32 talentRank
    {
        uint32 id = Eluna::CHECKVAL<uint32>(L, 2);
        uint32 rank = Eluna::CHECKVAL<uint32>(L, 3);
        player->LearnTalent(id, rank);
#if (!defined(TBC) && !defined(CLASSIC))
        player->SendTalentsInfoData(false);
#endif
#if !defined TRINITY && !AZEROTHCORE
        // if player has a pet, update owner talent auras
        if (player->GetPet())
            player->GetPet()->CastOwnerTalentAuras();
#endif
        return 0;
    }
References Player::GetPet(), Player::LearnTalent(), and Player::SendTalentsInfoData().
LeaveBattleground()
int LuaPlayer::LeaveBattleground (lua_State * L, Player * player)
Forces the [Player] to leave a [BattleGround]
Parameters
bool teleToEntry = true
    {
        (void)L; // ensure that the variable is referenced in order to pass compiler checks
#ifndef AZEROTHCORE
        bool teleToEntryPoint = Eluna::CHECKVAL<bool>(L, 2, true);
        player->LeaveBattleground(teleToEntryPoint);
#else
        player->LeaveBattleground();
#endif
        return 0;
    }
References Player::LeaveBattleground().
LogoutPlayer()
int LuaPlayer::LogoutPlayer (lua_State * L, Player * player)
Forces the [Player] to log out
Parameters
bool saveToDb = true
    {
        bool save = Eluna::CHECKVAL<bool>(L, 2, true);
        player->GetSession()->LogoutPlayer(save);
        return 0;
    }
References Player::GetSession(), and WorldSession::LogoutPlayer().
ModifyMoney()
int LuaPlayer::ModifyMoney (lua_State * L, Player * player)
Adds or subtracts from the [Player]s money in copper
Parameters
int32 copperAmt : negative to remove, positive to add
    {
        int32 amt = Eluna::CHECKVAL<int32>(L, 2);
        player->ModifyMoney(amt);
        return 1;
    }
References Player::ModifyMoney().
Mute()
int LuaPlayer::Mute (lua_State * L, Player * player)
Mutes the [Player] for the amount of seconds specified
Parameters
uint32 muteTime
    {
        uint32 muteseconds = Eluna::CHECKVAL<uint32>(L, 2);
        /*const char* reason = luaL_checkstring(E, 2);*/ // Mangos does not have a reason field in database.
        time_t muteTime = GameTime::GetGameTime().count() + muteseconds;
        player->GetSession()->m_muteTime = muteTime;
        LoginDatabase.Execute("UPDATE account SET mutetime = {} WHERE id = {}", muteTime, player->GetSession()->GetAccountId());
        return 0;
    }
References WorldSession::GetAccountId(), GameTime::GetGameTime(), Player::GetSession(), LoginDatabase, and WorldSession::m_muteTime.
RemoveArenaSpellCooldowns()
int LuaPlayer::RemoveArenaSpellCooldowns (lua_State * , Player * player)
Remove cooldowns on spells that have less than 10 minutes of cooldown from the [Player], similarly to when you enter an arena.
    {
        player->RemoveArenaSpellCooldowns();
        return 0;
    }
References Player::RemoveArenaSpellCooldowns().
RemovedInsignia()
int LuaPlayer::RemovedInsignia (lua_State * L, Player * player)
Loots [Player]'s bones for insignia
Parameters
[Player] looter
    {
        Player* looter = Eluna::CHECKOBJ<Player>(L, 2);
        player->RemovedInsignia(looter);
        return 0;
    }
References Player::RemovedInsignia().
RemoveFromBattlegroundRaid()
int LuaPlayer::RemoveFromBattlegroundRaid (lua_State * , Player * player)
Forcefully removes the [Player] from a [BattleGround] raid group
    {
#if defined TRINITY || AZEROTHCORE
        player->RemoveFromBattlegroundOrBattlefieldRaid();
#else
        player->RemoveFromBattleGroundRaid();
#endif
        return 0;
    }
References Player::RemoveFromBattlegroundOrBattlefieldRaid().
RemoveFromGroup()
int LuaPlayer::RemoveFromGroup (lua_State * , Player * player)
Forces the [Player] to leave a [Group]
    {
        if (!player->GetGroup())
            return 0;
        player->RemoveFromGroup();
        return 0;
    }
References Player::GetGroup(), and Player::RemoveFromGroup().
RemoveItem()
int LuaPlayer::RemoveItem (lua_State * L, Player * player)
Removes the given amount of the specified [Item] from the player.
@proto (item, itemCount) @proto (entry, itemCount)
Parameters
[Item] item : item to remove
uint32 entry : entry of the item to remove
uint32 itemCount = 1 : amount of the item to remove
    {
        Item* item = Eluna::CHECKOBJ<Item>(L, 2, false);
        uint32 itemCount = Eluna::CHECKVAL<uint32>(L, 3);
        if (!item)
        {
            uint32 itemId = Eluna::CHECKVAL<uint32>(L, 2);
            player->DestroyItemCount(itemId, itemCount, true);
        }
        else
        {
            bool all = itemCount >= item->GetCount();
            player->DestroyItemCount(item, itemCount, true);
            if (all)
                Eluna::CHECKOBJ<ElunaObject>(L, 2)->Invalidate();
        }
        return 0;
    }
References Player::DestroyItemCount(), and Item::GetCount().
RemoveLifetimeKills()
int LuaPlayer::RemoveLifetimeKills (lua_State * L, Player * player)
Removes specified amount of lifetime kills
Parameters
uint32 val : kills to remove
    {
        uint32 val = Eluna::CHECKVAL<uint32>(L, 2);
        uint32 currentKills = player->GetUInt32Value(PLAYER_FIELD_LIFETIME_HONORABLE_KILLS);
        if (val > currentKills)
            val = currentKills;
        player->SetUInt32Value(PLAYER_FIELD_LIFETIME_HONORABLE_KILLS, currentKills - val);
        return 0;
    }
References Object::GetUInt32Value(), PLAYER_FIELD_LIFETIME_HONORABLE_KILLS, and Unit::SetUInt32Value().
RemoveQuest()
int LuaPlayer::RemoveQuest (lua_State * L, Player * player)
Removes the given quest entry from the [Player].
Parameters
uint32 entry : quest entry
    {
        uint32 entry = Eluna::CHECKVAL<uint32>(L, 2);
        Quest const* quest = eObjectMgr->GetQuestTemplate(entry);
        if (!quest)
            return 0;
        // remove all quest entries for 'entry' from quest log
        for (uint8 slot = 0; slot < MAX_QUEST_LOG_SIZE; ++slot)
        {
            uint32 logQuest = player->GetQuestSlotQuestId(slot);
            if (logQuest == entry)
            {
                player->SetQuestSlot(slot, 0);
                // we ignore unequippable quest items in this case, its' still be equipped
                player->TakeQuestSourceItem(logQuest, false);
#if defined TRINITY || AZEROTHCORE
                if (quest->HasFlag(QUEST_FLAGS_FLAGS_PVP))
                {
                    player->pvpInfo.IsHostile = player->pvpInfo.IsInHostileArea || player->HasPvPForcingQuest();
                    player->UpdatePvPState();
                }
#endif
            }
        }
#if defined TRINITY || AZEROTHCORE
        player->RemoveActiveQuest(entry, false);
        player->RemoveRewardedQuest(entry);
#else
        // set quest status to not started (will updated in DB at next save)
        player->SetQuestStatus(entry, QUEST_STATUS_NONE);
        // reset rewarded for restart repeatable quest
        player->getQuestStatusMap()[entry].m_rewarded = false;
#endif
        return 0;
    }
References eObjectMgr, Player::GetQuestSlotQuestId(), Player::getQuestStatusMap(), Quest::HasFlag(), Player::HasPvPForcingQuest(), PvPInfo::IsHostile, PvPInfo::IsInHostileArea, MAX_QUEST_LOG_SIZE, Player::pvpInfo, QUEST_FLAGS_FLAGS_PVP, QUEST_STATUS_NONE, Player::RemoveActiveQuest(), Player::RemoveRewardedQuest(), Player::SetQuestSlot(), Player::SetQuestStatus(), Player::TakeQuestSourceItem(), and Player::UpdatePvPState().
RemoveSpell()
int LuaPlayer::RemoveSpell (lua_State * L, Player * player)
Removes the [Spell] from the [Player]
Parameters
uint32 entry : entry of a [Spell]
    {
        uint32 entry = Eluna::CHECKVAL<uint32>(L, 2);
#ifdef TRINITY
        player->RemoveSpell(entry);
#elif defined (AZEROTHCORE)
        player->removeSpell(entry, SPEC_MASK_ALL, false);
#else
        player->removeSpell(entry);
#endif
        return 0;
    }
References Player::removeSpell(), and SPEC_MASK_ALL.
ResetAchievements()
int LuaPlayer::ResetAchievements (lua_State * , Player * player)
Reset the [Player]s completed achievements
    {
#if defined TRINITY || AZEROTHCORE
        player->ResetAchievements();
#else
        player->GetAchievementMgr().Reset();
#endif
        return 0;
    }
References Player::GetAchievementMgr(), AchievementMgr::Reset(), and Player::ResetAchievements().
ResetAllCooldowns()
int LuaPlayer::ResetAllCooldowns (lua_State * , Player * player)
Resets all of the [Player]'s cooldowns
    {
#ifdef TRINITY
        player->GetSpellHistory()->ResetAllCooldowns();
#else
        player->RemoveAllSpellCooldown();
#endif
        return 0;
    }
References Player::RemoveAllSpellCooldown().
ResetPetTalents()
int LuaPlayer::ResetPetTalents (lua_State * , Player * player)
Resets the [Player]s pets talent points
    {
#ifndef TRINITY
        Pet* pet = player->GetPet();
        Pet::resetTalentsForAllPetsOf(player, pet);
        if (pet)
            player->SendTalentsInfoData(true);
#else
        player->ResetPetTalents();
        player->SendTalentsInfoData(true);
#endif
        return 0;
    }
References Player::GetPet(), Player::ResetPetTalents(), Pet::resetTalentsForAllPetsOf(), and Player::SendTalentsInfoData().
ResetSpellCooldown()
int LuaPlayer::ResetSpellCooldown (lua_State * L, Player * player)
Resets cooldown of the specified spell
Parameters
uint32 spellId
bool update = true
    {
        uint32 spellId = Eluna::CHECKVAL<uint32>(L, 2);
        bool update = Eluna::CHECKVAL<bool>(L, 3, true);
#ifdef TRINITY
        player->GetSpellHistory()->ResetCooldown(spellId, update);
#else
        player->RemoveSpellCooldown(spellId, update);
#endif
        return 0;
    }
References Player::RemoveSpellCooldown().
ResetTalents()
int LuaPlayer::ResetTalents (lua_State * L, Player * player)
Resets the [Player]s talents
Parameters
bool noCost = true
    {
        bool no_cost = Eluna::CHECKVAL<bool>(L, 2, true);
#ifdef CATA
        player->ResetTalents(no_cost);
#else
#ifdef TRINITY
        player->ResetTalents(no_cost);
#else
        player->resetTalents(no_cost);
#endif
#endif
#if (!defined(TBC) && !defined(CLASSIC))
        player->SendTalentsInfoData(false);
#endif
        return 0;
    }
References Player::resetTalents(), and Player::SendTalentsInfoData().
ResetTalentsCost()
int LuaPlayer::ResetTalentsCost (lua_State * L, Player * player)
Returns the [Player]s accumulated talent reset cost
Returns
uint32 resetCost
    {
#ifdef CATA
        Eluna::Push(L, player->GetNextResetTalentsCost());
#else
#ifdef TRINITY
        Eluna::Push(L, player->ResetTalentsCost());
#else
        Eluna::Push(L, player->resetTalentsCost());
#endif
#endif
        return 1;
    }
References Eluna::Push(), and Player::resetTalentsCost().
ResetTypeCooldowns()
int LuaPlayer::ResetTypeCooldowns (lua_State * L, Player * player)
Resets cooldown of the specified category
Parameters
uint32 category
bool update = true
    {
        uint32 category = Eluna::CHECKVAL<uint32>(L, 2);
        bool update = Eluna::CHECKVAL<bool>(L, 3, true);
        (void)update; // ensure that the variable is referenced in order to pass compiler checks
#ifdef TRINITY
        player->GetSpellHistory()->ResetCooldowns([category](SpellHistory::CooldownStorageType::iterator itr) -> bool
        {
            SpellInfo const* spellInfo = sSpellMgr->GetSpellInfo(itr->first);
            return spellInfo && spellInfo->GetCategory() == category;
        }, update);
#else
#ifndef AZEROTHCORE
        player->RemoveSpellCategoryCooldown(category, update);
#else
        player->RemoveCategoryCooldown(category);
#endif
#endif
        return 0;
    }
References SpellInfo::GetCategory(), Player::RemoveCategoryCooldown(), and sSpellMgr.
ResurrectPlayer()
int LuaPlayer::ResurrectPlayer (lua_State * L, Player * player)
Resurrects the [Player].
Parameters
float healthPercent = 100.0f
bool ressSickness = false
    {
        float percent = Eluna::CHECKVAL<float>(L, 2, 100.0f);
        bool sickness = Eluna::CHECKVAL<bool>(L, 3, false);
        player->ResurrectPlayer(percent, sickness);
        player->SpawnCorpseBones();
        return 0;
    }
References Player::ResurrectPlayer(), and Player::SpawnCorpseBones().
RewardQuest()
int LuaPlayer::RewardQuest (lua_State * L, Player * player)
Rewards the given quest entry for the [Player] if he has completed it.
Parameters
uint32 entry : quest entry
    {
        uint32 entry = Eluna::CHECKVAL<uint32>(L, 2);
        Quest const* quest = eObjectMgr->GetQuestTemplate(entry);
        // If player doesn't have the quest
        if (!quest || player->GetQuestStatus(entry) != QUEST_STATUS_COMPLETE)
            return 0;
        player->RewardQuest(quest, 0, player);
        return 0;
    }
References eObjectMgr, Player::GetQuestStatus(), QUEST_STATUS_COMPLETE, and Player::RewardQuest().
RunCommand()
int LuaPlayer::RunCommand (lua_State * L, Player * player)
Run a chat command as if the player typed it into the chat
Parameters
string command: text to display in chat or console
    {
        auto command = Eluna::CHECKVAL<std::string>(L, 2);
        // In _ParseCommands which is used below no leading . or ! is allowed for the command string.
        if (command[0] == '.' || command[0] == '!') {
            command = command.substr(1);
        }
        auto handler = ChatHandler(player->GetSession());
        handler._ParseCommands(command);
        return 0;
    }
References Player::GetSession().
SaveToDB()
int LuaPlayer::SaveToDB (lua_State * , Player * player)
Saves the [Player] to the database
    {
#ifndef AZEROTHCORE
        player->SaveToDB();
#else
        player->SaveToDB(false, false);
#endif
        return 0;
    }
References Player::SaveToDB().
Say()
int LuaPlayer::Say (lua_State * L, Player * player)
Sends say text from the [Player]
Parameters
string text : text for the [Player] to say
uint32 lang : language the [Player] will speak
    {
        std::string text = Eluna::CHECKVAL<std::string>(L, 2);
        uint32 lang = Eluna::CHECKVAL<uint32>(L, 3);
#if defined(TRINITY) || defined(AZEROTHCORE)
        player->Say(text, (Language)lang);
#else
        player->Say(text, lang);
#endif
        return 0;
    }
References Player::Say().
SendAddonMessage()
int LuaPlayer::SendAddonMessage (lua_State * L, Player * player)
Sends addon message to the [Player] receiver
Parameters
string prefix
string message
[ChatMsg] channel
[Player] receiver
    {
        std::string prefix = Eluna::CHECKVAL<std::string>(L, 2);
        std::string message = Eluna::CHECKVAL<std::string>(L, 3);
        uint8 channel = Eluna::CHECKVAL<uint8>(L, 4);
        Player* receiver = Eluna::CHECKOBJ<Player>(L, 5);
        std::string fullmsg = prefix + "\t" + message;
        WorldPacket data(SMSG_MESSAGECHAT, 100);
        data << uint8(channel);
        data << int32(LANG_ADDON);
        data << player->GET_GUID();
#ifndef CLASSIC
        data << uint32(0);
        data << receiver->GET_GUID();
#endif
        data << uint32(fullmsg.length() + 1);
        data << fullmsg;
        data << uint8(0);
#ifdef CMANGOS
        receiver->GetSession()->SendPacket(data);
#else
        receiver->GetSession()->SendPacket(&data);
#endif
        return 0;
    }
References Player::GetSession(), LANG_ADDON, WorldSession::SendPacket(), and SMSG_MESSAGECHAT.
SendAreaTriggerMessage()
int LuaPlayer::SendAreaTriggerMessage (lua_State * L, Player * player)
Sends an Area Trigger Message to the [Player]
Parameters
string message
    {
        std::string msg = Eluna::CHECKVAL<std::string>(L, 2);
        if (msg.length() > 0)
            player->GetSession()->SendAreaTriggerMessage("{}", msg.c_str());
        return 0;
    }
References Player::GetSession(), and WorldSession::SendAreaTriggerMessage().
SendAuctionMenu()
int LuaPlayer::SendAuctionMenu (lua_State * L, Player * player)
Sends an auction house window to the [Player] from the [Unit] specified
Parameters
[Unit] sender
    {
        Unit* unit = Eluna::CHECKOBJ<Unit>(L, 2);
#if defined AZEROTHCORE
    AuctionHouseEntry const* ahEntry = AuctionHouseMgr::GetAuctionHouseEntryFromFactionTemplate(unit->GetFaction());
#elif defined TRINITY
    AuctionHouseEntry const* ahEntry = AuctionHouseMgr::GetAuctionHouseEntry(unit->GetFaction());
#else
    AuctionHouseEntry const* ahEntry = AuctionHouseMgr::GetAuctionHouseEntry(unit);
#endif
        if (!ahEntry)
            return 0;
        WorldPacket data(MSG_AUCTION_HELLO, 12);
        data << unit->GET_GUID();
#ifdef TRINITY
        data << uint32(ahEntry->ID);
#else
        data << uint32(ahEntry->houseId);
#endif
        data << uint8(1);
#ifdef CMANGOS
        player->GetSession()->SendPacket(data);
#else
        player->GetSession()->SendPacket(&data);
#endif
        return 0;
    }
References AuctionHouseMgr::GetAuctionHouseEntryFromFactionTemplate(), Unit::GetFaction(), Player::GetSession(), AuctionHouseEntry::houseId, MSG_AUCTION_HELLO, and WorldSession::SendPacket().
SendBroadcastMessage()
int LuaPlayer::SendBroadcastMessage (lua_State * L, Player * player)
Sends a Broadcast Message to the [Player]
Parameters
string message
    {
        const char* message = Eluna::CHECKVAL<const char*>(L, 2);
        if (std::string(message).length() > 0)
            ChatHandler(player->GetSession()).SendSysMessage(message);
        return 0;
    }
References Player::GetSession(), and ChatHandler::SendSysMessage().
SendCinematicStart()
int LuaPlayer::SendCinematicStart (lua_State * L, Player * player)
Starts a cinematic for the [Player]
Parameters
uint32 CinematicSequenceId : entry of a cinematic
    {
        uint32 CinematicSequenceId = Eluna::CHECKVAL<uint32>(L, 2);
        player->SendCinematicStart(CinematicSequenceId);
        return 0;
    }
References Player::SendCinematicStart().
SendGuildInvite()
int LuaPlayer::SendGuildInvite (lua_State * L, Player * player)
Sends a guild invitation from the [Player]s [Guild] to the [Player] object specified
Parameters
[Player] invitee
    {
        Player* plr = Eluna::CHECKOBJ<Player>(L, 2);
#if defined TRINITY || AZEROTHCORE
        if (Guild* guild = player->GetGuild())
            guild->HandleInviteMember(player->GetSession(), plr->GetName());
#else
        player->GetSession()->SendGuildInvite(plr);
#endif
        return 0;
    }
References Player::GetGuild(), WorldObject::GetName(), and Player::GetSession().
SendListInventory()
int LuaPlayer::SendListInventory (lua_State * L, Player * player)
Sends a vendor window to the [Player] from the [WorldObject] specified.
Parameters
[WorldObject] sender
    {
        WorldObject* obj = Eluna::CHECKOBJ<WorldObject>(L, 2);
        uint32 vendorId = Eluna::CHECKVAL<uint32>(L, 3, 0);
        player->GetSession()->SendListInventory(obj->GET_GUID(), vendorId);
        return 0;
    }
References Player::GetSession(), and WorldSession::SendListInventory().
SendMovieStart()
int LuaPlayer::SendMovieStart (lua_State * L, Player * player)
Starts a movie for the [Player]
Parameters
uint32 MovieId : entry of a movie
    {
        uint32 MovieId = Eluna::CHECKVAL<uint32>(L, 2);
        player->SendMovieStart(MovieId);
        return 0;
    }
References Player::SendMovieStart().
SendNotification()
int LuaPlayer::SendNotification (lua_State * L, Player * player)
Sends a Notification to the [Player]
Parameters
string message
    {
        std::string msg = Eluna::CHECKVAL<std::string>(L, 2);
        if (msg.length() > 0)
            ChatHandler(player->GetSession()).SendNotification("{}", msg);
        return 0;
    }
References Player::GetSession(), and ChatHandler::SendNotification().
SendPacket()
int LuaPlayer::SendPacket (lua_State * L, Player * player)
Sends a [WorldPacket] to the [Player]
Parameters
[WorldPacket] packet
bool selfOnly = true
    {
        WorldPacket* data = Eluna::CHECKOBJ<WorldPacket>(L, 2);
        bool selfOnly = Eluna::CHECKVAL<bool>(L, 3, true);
#ifdef CMANGOS
        if (selfOnly)
            player->GetSession()->SendPacket(*data);
        else
            player->SendMessageToSet(*data, true);
#else
        if (selfOnly)
            player->GetSession()->SendPacket(data);
        else
            player->SendMessageToSet(data, true);
#endif
        return 0;
    }
References Player::GetSession(), Player::SendMessageToSet(), and WorldSession::SendPacket().
SendQuestTemplate()
int LuaPlayer::SendQuestTemplate (lua_State * L, Player * player)
Shows a quest accepting window to the [Player] for the given quest.
Parameters
uint32 questId : entry of a quest
bool activateAccept = true : auto finish the quest
    {
        uint32 questId = Eluna::CHECKVAL<uint32>(L, 2);
        bool activateAccept = Eluna::CHECKVAL<bool>(L, 3, true);
        Quest const* quest = eObjectMgr->GetQuestTemplate(questId);
        if (!quest)
            return 0;
        player->PlayerTalkClass->SendQuestGiverQuestDetails(quest, player->GET_GUID(), activateAccept);
        return 0;
    }
References eObjectMgr, Player::PlayerTalkClass, and PlayerMenu::SendQuestGiverQuestDetails().
SendShowBank()
int LuaPlayer::SendShowBank (lua_State * L, Player * player)
Sends a bank window to the [Player] from the [WorldObject] specified.
Parameters
[WorldObject] sender
    {
        WorldObject* obj = Eluna::CHECKOBJ<WorldObject>(L, 2);
        player->GetSession()->SendShowBank(obj->GET_GUID());
        return 0;
    }
References Player::GetSession(), and WorldSession::SendShowBank().
SendShowMailBox()
int LuaPlayer::SendShowMailBox (lua_State * L, Player * player)
Shows the mailbox window to the player from specified guid.
Parameters
ObjectGuid guid = playerguid : guid of the mailbox window sender
    {
        ObjectGuid guid = Eluna::CHECKVAL<ObjectGuid>(L, 2, player->GET_GUID());
#if (defined(CLASSIC) || defined(TBC))
        WorldPacket data(CMSG_GET_MAIL_LIST, 8);
        data << guid;
        player->GetSession()->HandleGetMailList(data);
#else
        player->GetSession()->SendShowMailBox(guid);
#endif
        return 0;
    }
References CMSG_GET_MAIL_LIST, Player::GetSession(), WorldSession::HandleGetMailList(), and WorldSession::SendShowMailBox().
SendSpiritResurrect()
int LuaPlayer::SendSpiritResurrect (lua_State * , Player * player)
Sends a spirit resurrection request to the [Player]
    {
        player->GetSession()->SendSpiritResurrect();
        return 0;
    }
References Player::GetSession(), and WorldSession::SendSpiritResurrect().
SendTabardVendorActivate()
int LuaPlayer::SendTabardVendorActivate (lua_State * L, Player * player)
Sends a tabard vendor window to the [Player] from the [WorldObject] specified
Parameters
[WorldObject] sender
    {
        WorldObject* obj = Eluna::CHECKOBJ<WorldObject>(L, 2);
        player->GetSession()->SendTabardVendorActivate(obj->GET_GUID());
        return 0;
    }
References Player::GetSession(), and WorldSession::SendTabardVendorActivate().
SendTaxiMenu()
int LuaPlayer::SendTaxiMenu (lua_State * L, Player * player)
Sends a flightmaster window to the [Player] from the [Creature] specified
Parameters
[Creature] sender
    {
        Creature* creature = Eluna::CHECKOBJ<Creature>(L, 2);
        player->GetSession()->SendTaxiMenu(creature);
        return 0;
    }
References Player::GetSession(), and WorldSession::SendTaxiMenu().
SendTrainerList()
int LuaPlayer::SendTrainerList (lua_State * L, Player * player)
Sends a trainer window to the [Player] from the [Creature] specified
Parameters
[Creature] sender
    {
        Creature* obj = Eluna::CHECKOBJ<Creature>(L, 2);
#ifdef TRINITY
        player->GetSession()->SendTrainerList(obj);
#else
        player->GetSession()->SendTrainerList(obj->GET_GUID());
#endif
        return 0;
    }
References Player::GetSession(), and WorldSession::SendTrainerList().
SendUpdateWorldState()
int LuaPlayer::SendUpdateWorldState (lua_State * L, Player * player)
Sends an update for the world state to the [Player]
Parameters
uint32 field
uint32 value
    {
        uint32 field = Eluna::CHECKVAL<uint32>(L, 2);
        uint32 value = Eluna::CHECKVAL<uint32>(L, 3);
        player->SendUpdateWorldState(field, value);
        return 0;
    }
References Player::SendUpdateWorldState().
SetAcceptWhispers()
int LuaPlayer::SetAcceptWhispers (lua_State * L, Player * player)
Toggles whether the [Player] accepts whispers or not
Parameters
bool acceptWhispers = true
    {
        bool on = Eluna::CHECKVAL<bool>(L, 2, true);
        player->SetAcceptWhispers(on);
        return 0;
    }
References Player::SetAcceptWhispers().
SetAtLoginFlag()
int LuaPlayer::SetAtLoginFlag (lua_State * L, Player * player)
Sets the [Player]s login flag to the flag specified
Parameters
uint32 flag
    {
        uint32 flag = Eluna::CHECKVAL<uint32>(L, 2);
        player->SetAtLoginFlag((AtLoginFlags)flag);
        return 0;
    }
References Player::SetAtLoginFlag().
SetBindPoint()
int LuaPlayer::SetBindPoint (lua_State * L, Player * player)
Sets the [Player]s home location to the location specified
Parameters
float x : X Coordinate
float y : Y Coordinate
float z : Z Coordinate
uint32 mapId : Map ID
uint32 areaId : Area ID
    {
        float x = Eluna::CHECKVAL<float>(L, 2);
        float y = Eluna::CHECKVAL<float>(L, 3);
        float z = Eluna::CHECKVAL<float>(L, 4);
        uint32 mapId = Eluna::CHECKVAL<uint32>(L, 5);
        uint32 areaId = Eluna::CHECKVAL<uint32>(L, 6);
        WorldLocation loc(mapId, x, y, z);
#if defined TRINITY || AZEROTHCORE
        player->SetHomebind(loc, areaId);
#else
        player->SetHomebindToLocation(loc, areaId);
#endif
        return 0;
    }
References Player::SetHomebind().
SetCoinage()
int LuaPlayer::SetCoinage (lua_State * L, Player * player)
Sets the [Player]s amount of money to copper specified
Parameters
uint32 copperAmt
    {
        uint32 amt = Eluna::CHECKVAL<uint32>(L, 2);
        player->SetMoney(amt);
        return 0;
    }
References Player::SetMoney().
SetDrunkValue()
int LuaPlayer::SetDrunkValue (lua_State * L, Player * player)
Sets the [Player]s intoxication level to the level specified
Parameters
uint8 drunkValue
    {
        uint8 newDrunkValue = Eluna::CHECKVAL<uint8>(L, 2);
        player->SetDrunkValue(newDrunkValue);
        return 0;
    }
References Player::SetDrunkValue().
SetFactionForRace()
int LuaPlayer::SetFactionForRace (lua_State * L, Player * player)
Sets the [Player]s faction standing to that of the race specified
Parameters
uint8 raceId
    {
        uint8 race = Eluna::CHECKVAL<uint8>(L, 2);
#if defined TRINITY || AZEROTHCORE
        player->SetFactionForRace(race);
#else
        player->setFactionForRace(race);
#endif
        return 0;
    }
References Player::SetFactionForRace().
SetFFA()
int LuaPlayer::SetFFA (lua_State * L, Player * player)
Toggle the [Player]s FFA flag
Parameters
bool applyFFA = true
    {
        bool apply = Eluna::CHECKVAL<bool>(L, 2, true);
        player->SetFFAPvP(apply);
        return 0;
    }
SetFreeTalentPoints()
int LuaPlayer::SetFreeTalentPoints (lua_State * L, Player * player)
Sets the [Player]s free talent points to the amount specified for the current spec
Parameters
uint32 talentPointAmt
    {
        uint32 points = Eluna::CHECKVAL<uint32>(L, 2);
        player->SetFreeTalentPoints(points);
#if (!defined(TBC) && !defined(CLASSIC))
        player->SendTalentsInfoData(false);
#endif
        return 0;
    }
References Player::SendTalentsInfoData(), and Player::SetFreeTalentPoints().
SetGameMaster()
int LuaPlayer::SetGameMaster (lua_State * L, Player * player)
Toggles the [Player]s GM mode on or off
Parameters
bool setGmMode = true
    {
        bool on = Eluna::CHECKVAL<bool>(L, 2, true);
        player->SetGameMaster(on);
        return 0;
    }
References Player::SetGameMaster().
SetGender()
int LuaPlayer::SetGender (lua_State * L, Player * player)
Sets the [Player]s gender to gender specified
GENDER_MALE = 0
GENDER_FEMALE = 1
Parameters
[Gender] gender
    {
        uint32 _gender = Eluna::CHECKVAL<uint32>(L, 2);
        Gender gender;
        switch (_gender)
        {
            case 0:
                gender = GENDER_MALE;
                break;
            case 1:
                gender = GENDER_FEMALE;
                break;
            default:
                return luaL_argerror(L, 2, "valid Gender expected");
        }
        player->SetByteValue(UNIT_FIELD_BYTES_0, 2, gender);
        player->SetByteValue(PLAYER_BYTES_3, 0, gender);
        player->InitDisplayIds();
        return 0;
    }
References GENDER_FEMALE, GENDER_MALE, Player::InitDisplayIds(), luaL_argerror(), PLAYER_BYTES_3, Object::SetByteValue(), and UNIT_FIELD_BYTES_0.
SetGlyph()
int LuaPlayer::SetGlyph (lua_State * L, Player * player)
Adds a glyph specified by glyphId to the [Player]'s current talent specialization into the slot with the index slotIndex
Parameters
uint32 glyphId
uint32 slotIndex
    {
        uint32 glyphId = Eluna::CHECKVAL<uint32>(L, 2);
        uint32 slotIndex = Eluna::CHECKVAL<uint32>(L, 3);
        player->SetGlyph(slotIndex, glyphId, true);
        player->SendTalentsInfoData(false); // Also handles GlyphData
        return 0;
    }
References Player::SendTalentsInfoData(), and Player::SetGlyph().
SetGMChat()
int LuaPlayer::SetGMChat (lua_State * L, Player * player)
Toggle Blizz (GM) tag
Parameters
bool on = true
    {
        bool on = Eluna::CHECKVAL<bool>(L, 2, true);
        player->SetGMChat(on);
        return 0;
    }
References Player::SetGMChat().
SetGMVisible()
int LuaPlayer::SetGMVisible (lua_State * L, Player * player)
Toggles whether the [Player] has GM visibility on or off
Parameters
bool gmVisible = true
    {
        bool on = Eluna::CHECKVAL<bool>(L, 2, true);
        player->SetGMVisible(on);
        return 0;
    }
References Player::SetGMVisible().
SetGuildRank()
int LuaPlayer::SetGuildRank (lua_State * L, Player * player)
Sets the [Player]s guild rank to the rank specified
Parameters
uint8 rank
    {
        uint8 rank = Eluna::CHECKVAL<uint8>(L, 2);
        if (!player->GetGuildId())
            return 0;
        player->SetRank(rank);
        return 0;
    }
References Player::GetGuildId(), and Player::SetRank().
SetKnownTitle()
int LuaPlayer::SetKnownTitle (lua_State * L, Player * player)
Adds the specified title to the [Player]s list of known titles
Parameters
uint32 titleId
    {
        uint32 id = Eluna::CHECKVAL<uint32>(L, 2);
        CharTitlesEntry const* t = sCharTitlesStore.LookupEntry(id);
        if (t)
            player->SetTitle(t, false);
        return 0;
    }
References sCharTitlesStore, and Player::SetTitle().
SetLifetimeKills()
int LuaPlayer::SetLifetimeKills (lua_State * L, Player * player)
Sets the [Player]s amount of Lifetime Honorable Kills to the value specified
Parameters
uint32 honorableKills
    {
        uint32 val = Eluna::CHECKVAL<uint32>(L, 2);
        player->SetUInt32Value(PLAYER_FIELD_LIFETIME_HONORABLE_KILLS, val);
        return 0;
    }
References PLAYER_FIELD_LIFETIME_HONORABLE_KILLS, and Unit::SetUInt32Value().
SetPlayerLock()
int LuaPlayer::SetPlayerLock (lua_State * L, Player * player)
Locks the player controls and disallows all movement and casting.
Parameters
bool apply = true : lock if true and unlock if false
    {
        bool apply = Eluna::CHECKVAL<bool>(L, 2, true);
        if (apply)
        {
            player->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_PACIFIED | UNIT_FLAG_SILENCED);
            player->SetClientControl(player, 0);
        }
        else
        {
            player->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_PACIFIED | UNIT_FLAG_SILENCED);
            player->SetClientControl(player, 1);
        }
        return 0;
    }
References Object::RemoveFlag(), Player::SetClientControl(), Object::SetFlag(), UNIT_FIELD_FLAGS, UNIT_FLAG_PACIFIED, and UNIT_FLAG_SILENCED.
SetPvPDeath()
int LuaPlayer::SetPvPDeath (lua_State * L, Player * player)
Toggles PvP Death
Parameters
bool on = true
    {
        bool on = Eluna::CHECKVAL<bool>(L, 2, true);
        player->SetPvPDeath(on);
        return 0;
    }
References Player::SetPvPDeath().
SetQuestStatus()
int LuaPlayer::SetQuestStatus (lua_State * L, Player * player)
Sets [Quest] state
Parameters
uint32 entry : entry of a quest
uint32 status
    {
        uint32 entry = Eluna::CHECKVAL<uint32>(L, 2);
        uint32 status = Eluna::CHECKVAL<uint32>(L, 3);
        if (status >= MAX_QUEST_STATUS)
            return 0;
        player->SetQuestStatus(entry, (QuestStatus)status);
        return 0;
    }
References MAX_QUEST_STATUS, and Player::SetQuestStatus().
SetReputation()
int LuaPlayer::SetReputation (lua_State * L, Player * player)
Sets the [Player]s reputation amount for the faction specified
Parameters
uint32 factionId
int32 reputationValue
    {
        uint32 faction = Eluna::CHECKVAL<uint32>(L, 2);
        int32 value = Eluna::CHECKVAL<int32>(L, 3);
        FactionEntry const* factionEntry = sFactionStore.LookupEntry(faction);
        player->GetReputationMgr().SetReputation(factionEntry, value);
        return 0;
    }
References Player::GetReputationMgr(), ReputationMgr::SetReputation(), and sFactionStore.
SetRestBonus()
int LuaPlayer::SetRestBonus (lua_State * L, Player * player)
Sets the [Player]s rest bonus to the amount specified
Parameters
float restBonus
    {
        float bonus = Eluna::CHECKVAL<float>(L, 2);
        player->SetRestBonus(bonus);
        return 0;
    }
References Player::SetRestBonus().
SetSheath()
int LuaPlayer::SetSheath (lua_State * L, Player * player)
Sets the [Player]s sheathe state to the state specified
Parameters
uint32 sheatheState
    {
        uint32 sheathed = Eluna::CHECKVAL<uint32>(L, 2);
        if (sheathed >= MAX_SHEATH_STATE)
            return 0;
        player->SetSheath((SheathState)sheathed);
        return 0;
    }
References MAX_SHEATH_STATE, and Player::SetSheath().
SetSkill()
int LuaPlayer::SetSkill (lua_State * L, Player * player)
Sets (increases) skill of the [Player]
Parameters
uint16 id
uint16 step
uint16 currVal
uint16 maxVal
    {
        uint16 id = Eluna::CHECKVAL<uint16>(L, 2);
        uint16 step = Eluna::CHECKVAL<uint16>(L, 3);
        uint16 currVal = Eluna::CHECKVAL<uint16>(L, 4);
        uint16 maxVal = Eluna::CHECKVAL<uint16>(L, 5);
#ifdef TRINITY
        player->SetSkill(id, step, currVal, maxVal);
#else
        player->SetSkill(id, currVal, maxVal, step);
#endif
        return 0;
    }
References Player::SetSkill().
SetSpellPower()
int LuaPlayer::SetSpellPower (lua_State * L, Player * player)
The [Player] sets the spell power
Parameters
int value : The spell power value to set
bool apply = false : Whether the spell power should be applied or removed
    {
        int value  = Eluna::CHECKVAL<int>(L, 2);
        bool apply = Eluna::CHECKVAL<bool>(L, 3, false);
        player->ApplySpellPowerBonus(value, apply);
        return 0;
    }
References Player::ApplySpellPowerBonus().
SetTaxiCheat()
int LuaPlayer::SetTaxiCheat (lua_State * L, Player * player)
Toggles whether the [Player] has taxi cheat enabled or not
Parameters
bool taxiCheat = true
    {
        bool on = Eluna::CHECKVAL<bool>(L, 2, true);
        player->SetTaxiCheater(on);
        return 0;
    }
References Player::SetTaxiCheater().
SpawnBones()
int LuaPlayer::SpawnBones (lua_State * , Player * player)
Converts [Player]'s corpse to bones
    {
        player->SpawnCorpseBones();
        return 0;
    }
References Player::SpawnCorpseBones().
StartTaxi()
int LuaPlayer::StartTaxi (lua_State * L, Player * player)
Attempts to start the taxi/flying to the given pathID
Parameters
uint32 pathId : pathId from DBC or [Global:AddTaxiPath]
    {
        uint32 pathId = Eluna::CHECKVAL<uint32>(L, 2);
        player->ActivateTaxiPathTo(pathId);
        return 0;
    }
References Player::ActivateTaxiPathTo().
SummonPlayer()
int LuaPlayer::SummonPlayer (lua_State * L, Player * player)
Sends a summon request to the player from the given summoner
Parameters
[Unit] summoner
    {
        Unit* summoner = Eluna::CHECKOBJ<Unit>(L, 2);
#ifdef TRINITY
        player->SendSummonRequestFrom(summoner);
#else
        float x, y, z;
        summoner->GetPosition(x,y,z);
        player->SetSummonPoint(summoner->GetMapId(), x, y, z);
        WorldPacket data(SMSG_SUMMON_REQUEST, 8 + 4 + 4);
        data << summoner->GET_GUID();
        data << uint32(summoner->GetZoneId());
        data << uint32(MAX_PLAYER_SUMMON_DELAY * IN_MILLISECONDS);
#ifdef CMANGOS
        player->GetSession()->SendPacket(data);
#else
        player->GetSession()->SendPacket(&data);
#endif
#endif
        return 0;
    }
References WorldLocation::GetMapId(), Position::GetPosition(), Player::GetSession(), WorldObject::GetZoneId(), IN_MILLISECONDS, MAX_PLAYER_SUMMON_DELAY, WorldSession::SendPacket(), Player::SetSummonPoint(), and SMSG_SUMMON_REQUEST.
TalkedToCreature()
int LuaPlayer::TalkedToCreature (lua_State * L, Player * player)
Gives [Quest] monster talked to credit
Parameters
uint32 entry : entry of a [Creature]
[Creature] creature
    {
        uint32 entry = Eluna::CHECKVAL<uint32>(L, 2);
        Creature* creature = Eluna::CHECKOBJ<Creature>(L, 3);
        player->TalkedToCreature(entry, creature->GET_GUID());
        return 0;
    }
References Player::TalkedToCreature().
Teleport()
int LuaPlayer::Teleport (lua_State * L, Player * player)
Teleports a [Player] to the location specified
Parameters
uint32 mappId
float xCoord
float yCoord
float zCoord
float orientation
    {
        uint32 mapId = Eluna::CHECKVAL<uint32>(L, 2);
        float x = Eluna::CHECKVAL<float>(L, 3);
        float y = Eluna::CHECKVAL<float>(L, 4);
        float z = Eluna::CHECKVAL<float>(L, 5);
        float o = Eluna::CHECKVAL<float>(L, 6);
#if defined AZEROTHCORE
        if (player->IsInFlight())
        {
            player->GetMotionMaster()->MovementExpired();
            player->m_taxi.ClearTaxiDestinations();
        }
#elif defined TRINITY
        if (player->IsInFlight())
            player->FinishTaxiFlight();
        else
            player->SaveRecallPosition();
#else
        if (player->IsTaxiFlying())
        {
            player->GetMotionMaster()->MovementExpired();
            player->m_taxi.ClearTaxiDestinations();
        }
#endif
        Eluna::Push(L, player->TeleportTo(mapId, x, y, z, o));
        return 1;
    }
References PlayerTaxi::ClearTaxiDestinations(), Unit::GetMotionMaster(), Unit::IsInFlight(), Player::m_taxi, MotionMaster::MovementExpired(), Eluna::Push(), Player::SaveRecallPosition(), and Player::TeleportTo().
TextEmote()
int LuaPlayer::TextEmote (lua_State * L, Player * player)
Sends a text emote from the [Player]
Parameters
string emoteText
    {
        std::string text = Eluna::CHECKVAL<std::string>(L, 2);
        player->TextEmote(text);
        return 0;
    }
References Player::TextEmote().
ToggleAFK()
int LuaPlayer::ToggleAFK (lua_State * , Player * player)
Toggle the [Player]s 'Away From Keyboard' flag
    {
        player->ToggleAFK();
        return 0;
    }
References Player::ToggleAFK().
ToggleDND()
int LuaPlayer::ToggleDND (lua_State * , Player * player)
Toggle the [Player]s 'Do Not Disturb' flag
    {
        player->ToggleDND();
        return 0;
    }
References Player::ToggleDND().
UnbindAllInstances()
int LuaPlayer::UnbindAllInstances (lua_State * , Player * player)
Unbinds the [Player] from his instances except the one he currently is in.
    {
#ifdef CLASSIC
        Player::BoundInstancesMap& binds = player->GetBoundInstances();
        for (Player::BoundInstancesMap::iterator itr = binds.begin(); itr != binds.end();)
        {
            if (itr->first != player->GetMapId())
                player->UnbindInstance(itr);
            else
                ++itr;
        }
#elif defined AZEROTHCORE
        for (uint8 i = 0; i < MAX_DIFFICULTY; ++i)
        {
            const BoundInstancesMap& binds = sInstanceSaveMgr->PlayerGetBoundInstances(player->GetGUID(), Difficulty(i));
            for (BoundInstancesMap::const_iterator itr = binds.begin(); itr != binds.end();)
            {
                if (itr->first != player->GetMapId())
                {
                    sInstanceSaveMgr->PlayerUnbindInstance(player->GetGUID(), itr->first, Difficulty(i), true, player);
                    itr = binds.begin();
                }
                else
                {
                    ++itr;
                }
            }
        }
#else
        for (uint8 i = 0; i < MAX_DIFFICULTY; ++i)
        {
            Player::BoundInstancesMap& binds = player->GetBoundInstances(Difficulty(i));
            for (Player::BoundInstancesMap::iterator itr = binds.begin(); itr != binds.end();)
            {
                if (itr->first != player->GetMapId())
                    player->UnbindInstance(itr, Difficulty(i));
                else
                    ++itr;
            }
        }
#endif
        return 0;
    }
References Object::GetGUID(), WorldLocation::GetMapId(), MAX_DIFFICULTY, and sInstanceSaveMgr.
UnbindInstance()
int LuaPlayer::UnbindInstance (lua_State * L, Player * player)
Unbinds the [Player] from his instances except the one he currently is in.
Difficulty is not used on classic.
Parameters
uint32 map = true
uint32 difficulty = 0
    {
        uint32 map = Eluna::CHECKVAL<uint32>(L, 2);
#ifndef CLASSIC
        uint32 difficulty = Eluna::CHECKVAL<uint32>(L, 3, 0);
        if (difficulty < MAX_DIFFICULTY)
#ifndef AZEROTHCORE
            player->UnbindInstance(map, (Difficulty)difficulty);
#else
            sInstanceSaveMgr->PlayerUnbindInstance(player->GetGUID(), map, Difficulty(difficulty), true, player);
#endif//AZEROTHCORE
#else//CLASSIC
        player->UnbindInstance(map);
#endif
        return 0;
    }
References Object::GetGUID(), MAX_DIFFICULTY, and sInstanceSaveMgr.
UnsetKnownTitle()
int LuaPlayer::UnsetKnownTitle (lua_State * L, Player * player)
Removes a title by ID from the [Player]s list of known titles
Parameters
uint32 titleId
    {
        uint32 id = Eluna::CHECKVAL<uint32>(L, 2);
        CharTitlesEntry const* t = sCharTitlesStore.LookupEntry(id);
        if (t)
            player->SetTitle(t, true);
        return 0;
    }
References sCharTitlesStore, and Player::SetTitle().
UpdatePlayerSetting()
int LuaPlayer::UpdatePlayerSetting (lua_State * L, Player * player)
Sets a setting value for the [Player]
Parameters
string source
uint32 index
uint32 value
    {
        std::string source = Eluna::CHECKVAL<std::string>(L, 2);
        uint32 index = Eluna::CHECKVAL<uint32>(L, 3);
        uint32 value = Eluna::CHECKVAL<uint32>(L, 4);
        player->UpdatePlayerSetting(source, index, value);
        return 0;
    }
References Player::UpdatePlayerSetting().
Whisper()
int LuaPlayer::Whisper (lua_State * L, Player * player)
Sends whisper text from the [Player]
Parameters
string text
uint32 lang : language the [Player] will speak
[Player] receiver : is the [Player] that will receive the whisper, if TrinityCore
ObjectGuid guid : is the GUID of a [Player] that will receive the whisper, not TrinityCore
    {
        std::string text = Eluna::CHECKVAL<std::string>(L, 2);
        uint32 lang = Eluna::CHECKVAL<uint32>(L, 3);
#if defined(TRINITY) || defined(AZEROTHCORE)
        Player* receiver = Eluna::CHECKOBJ<Player>(L, 4);
        player->Whisper(text, (Language)lang, receiver);
#else
        ObjectGuid guid = Eluna::CHECKVAL<ObjectGuid>(L, 4);
        player->Whisper(text, lang, guid);
#endif
        return 0;
    }
References Player::Whisper().
Yell()
int LuaPlayer::Yell (lua_State * L, Player * player)
Sends yell text from the [Player]
Parameters
string text : text for the [Player] to yells
uint32 lang : language the [Player] will speak
    {
        std::string text = Eluna::CHECKVAL<std::string>(L, 2);
        uint32 lang = Eluna::CHECKVAL<uint32>(L, 3);
#if defined(TRINITY) || defined(AZEROTHCORE)
        player->Yell(text, (Language)lang);
#else
        player->Yell(text, lang);
#endif
        return 0;
    }
References Player::Yell().