AzerothCore Doxygen
boss_the_lich_king.cpp File Reference
#include "AchievementCriteriaScript.h"
#include "AreaDefines.h"
#include "Cell.h"
#include "CellImpl.h"
#include "CreatureScript.h"
#include "CreatureTextMgr.h"
#include "GameTime.h"
#include "GridNotifiers.h"
#include "ObjectMgr.h"
#include "ScriptedCreature.h"
#include "Spell.h"
#include "SpellAuraEffects.h"
#include "SpellScript.h"
#include "SpellScriptLoader.h"
#include "Unit.h"
#include "Vehicle.h"
#include "Weather.h"
#include "icecrown_citadel.h"
#include "PassiveAI.h"
Classes
struct ShadowTrapLKTargetSelector
struct NonTankLKTargetSelector
struct DefileTargetSelector
class FrozenThroneResetWorker
class StartMovementEvent
class VileSpiritActivateEvent
class TriggerWickedSpirit
class LichKingDeathEvent
class LichKingMovieEvent
class NecroticPlagueTargetCheck
class HeightDifferenceCheck
class boss_the_lich_king
struct boss_the_lich_king::boss_the_lich_kingAI
class npc_tirion_fordring_tft
struct npc_tirion_fordring_tft::npc_tirion_fordringAI
class spell_the_lich_king_quake
class spell_the_lich_king_jump
class spell_the_lich_king_jump_remove_aura
class spell_the_lich_king_play_movie
class npc_shambling_horror_icc
struct npc_shambling_horror_icc::npc_shambling_horror_iccAI
class spell_the_lich_king_infest_aura
class spell_the_lich_king_necrotic_plague_aura
class spell_the_lich_king_necrotic_plague_jump
class spell_the_lich_king_necrotic_plague_jump_aura
class spell_the_lich_king_shadow_trap_visual_aura
class spell_the_lich_king_shadow_trap_periodic
class spell_the_lich_king_ice_burst_target_search
class npc_icc_ice_sphere
struct npc_icc_ice_sphere::npc_icc_ice_sphereAI
class spell_the_lich_king_raging_spirit
class npc_raging_spirit
struct npc_raging_spirit::npc_raging_spiritAI
class VehicleCheck
class spell_the_lich_king_defile
class spell_the_lich_king_soul_reaper_aura
class npc_valkyr_shadowguard
struct npc_valkyr_shadowguard::npc_valkyr_shadowguardAI
class spell_the_lich_king_summon_into_air
class spell_the_lich_king_teleport_to_frostmourne_hc
class spell_the_lich_king_valkyr_target_search
class spell_the_lich_king_cast_back_to_caster
class spell_the_lich_king_life_siphon
class spell_the_lich_king_vile_spirits_aura
class spell_the_lich_king_vile_spirits_visual
class spell_the_lich_king_vile_spirit_move_target_search
class spell_the_lich_king_vile_spirit_damage_target_search
class spell_the_lich_king_harvest_soul_aura
class npc_strangulate_vehicle
struct npc_strangulate_vehicle::npc_strangulate_vehicleAI
class npc_terenas_menethil
struct npc_terenas_menethil::npc_terenas_menethilAI
class spell_the_lich_king_lights_favor_aura
class spell_the_lich_king_restore_soul
class npc_spirit_warden
struct npc_spirit_warden::npc_spirit_wardenAI
class spell_the_lich_king_dark_hunger_aura
class spell_the_lich_king_soul_rip_aura
class npc_icc_lk_checktarget
struct npc_icc_lk_checktarget::npc_icc_lk_checktargetAI
class spell_the_lich_king_summon_spirit_bomb
class npc_lk_spirit_bomb
struct npc_lk_spirit_bomb::npc_lk_spirit_bombAI
class spell_the_lich_king_trigger_vile_spirit
class npc_lk_wicked_spirit
struct npc_lk_wicked_spirit::npc_lk_wicked_spiritAI
class achievement_been_waiting_long_time
class achievement_neck_deep_in_vile
Macros
#define NECROTIC_PLAGUE_LK RAID_MODE<uint32>(70337, 73912, 73913, 73914)
#define NECROTIC_PLAGUE_PLR RAID_MODE<uint32>(70338, 73785, 73786, 73787)
#define REMORSELESS_WINTER_1 RAID_MODE<uint32>(68981, 74270, 74271, 74272)
#define REMORSELESS_WINTER_2 RAID_MODE<uint32>(72259, 74273, 74274, 74275)
#define SUMMON_VALKYR RAID_MODE<uint32>(69037, 74361, 69037, 74361)
#define HARVESTED_SOUL_BUFF RAID_MODE<uint32>(72679, 74318, 74319, 74320)
#define DATA_PLAGUE_STACK 70337
#define DATA_VILE 45814622
Enumerations
enum Texts {
SAY_LK_INTRO_1 = 0 ,
SAY_LK_INTRO_2 = 1 ,
SAY_LK_INTRO_3 = 2 ,
SAY_LK_REMORSELESS_WINTER = 4 ,
SAY_LK_QUAKE = 5 ,
SAY_LK_SUMMON_VALKYR = 6 ,
SAY_LK_HARVEST_SOUL = 7 ,
SAY_LK_FROSTMOURNE_ESCAPE = 8 ,
SAY_LK_FROSTMOURNE_KILL = 9 ,
SAY_LK_KILL = 10 ,
SAY_LK_BERSERK = 11 ,
EMOTE_DEFILE_WARNING = 12 ,
EMOTE_NECROTIC_PLAGUE_WARNING = 13 ,
SAY_LK_OUTRO_1 = 14 ,
SAY_LK_OUTRO_2 = 15 ,
SAY_LK_OUTRO_3 = 16 ,
SAY_LK_OUTRO_4 = 17 ,
SAY_LK_OUTRO_5 = 18 ,
SAY_LK_OUTRO_6 = 19 ,
SAY_LK_OUTRO_7 = 20 ,
SAY_LK_OUTRO_8 = 21 ,
SAY_TIRION_INTRO_1 = 0 ,
SAY_TIRION_INTRO_2 = 1 ,
SAY_TIRION_OUTRO_1 = 2 ,
SAY_TIRION_OUTRO_2 = 3 ,
SAY_TIRION_OUTRO_3 = 4 ,
SAY_TERENAS_OUTRO_1 = 0 ,
SAY_TERENAS_OUTRO_2 = 1 ,
SAY_TERENAS_INTRO_1 = 0 ,
SAY_TERENAS_INTRO_2 = 1 ,
SAY_TERENAS_INTRO_3 = 2
}
enum Spells {
SPELL_PLAGUE_AVOIDANCE = 72846 ,
SPELL_EMOTE_SIT_NO_SHEATH = 73220 ,
SPELL_BOSS_HITTIN_YA = 73878 ,
SPELL_BOSS_HITTIN_YA_AURA = 73879 ,
SPELL_EMOTE_SHOUT_NO_SHEATH = 73213 ,
SPELL_ICE_LOCK = 71614 ,
SPELL_FURY_OF_FROSTMOURNE = 72350 ,
SPELL_FURY_OF_FROSTMOURNE_NO_REZ = 72351 ,
SPELL_EMOTE_QUESTION_NO_SHEATH = 73330 ,
SPELL_RAISE_DEAD = 71769 ,
SPELL_LIGHTS_BLESSING = 71797 ,
SPELL_JUMP = 71809 ,
SPELL_JUMP_TRIGGERED = 71811 ,
SPELL_JUMP_2 = 72431 ,
SPELL_SUMMON_BROKEN_FROSTMOURNE = 74081 ,
SPELL_SUMMON_BROKEN_FROSTMOURNE_2 = 72406 ,
SPELL_SUMMON_BROKEN_FROSTMOURNE_3 = 73017 ,
SPELL_BROKEN_FROSTMOURNE = 72398 ,
SPELL_BROKEN_FROSTMOURNE_KNOCK = 72405 ,
SPELL_SOUL_BARRAGE = 72305 ,
SPELL_SUMMON_TERENAS = 72420 ,
SPELL_MASS_RESURRECTION = 72429 ,
SPELL_MASS_RESURRECTION_REAL = 72423 ,
SPELL_PLAY_MOVIE = 73159 ,
SPELL_REMORSELESS_WINTER_1 = 68981 ,
SPELL_REMORSELESS_WINTER_2 = 72259 ,
SPELL_QUAKE = 72262 ,
SPELL_PAIN_AND_SUFFERING = 72133 ,
SPELL_SUMMON_ICE_SPHERE = 69104 ,
SPELL_ICE_SPHERE = 69090 ,
SPELL_ICE_BURST_TARGET_SEARCH = 69109 ,
SPELL_ICE_PULSE = 69091 ,
SPELL_ICE_BURST = 69108 ,
SPELL_RAGING_SPIRIT = 69200 ,
SPELL_RAGING_SPIRIT_VISUAL = 69197 ,
SPELL_RAGING_SPIRIT_VISUAL_CLONE = 69198 ,
SPELL_SOUL_SHRIEK = 69242 ,
SPELL_RISEN_WITCH_DOCTOR_SPAWN = 69639 ,
SPELL_SUMMON_SHAMBLING_HORROR = 70372 ,
SPELL_SUMMON_DRUDGE_GHOULS = 70358 ,
SPELL_INFEST = 70541 ,
SPELL_NECROTIC_PLAGUE = 70337 ,
SPELL_NECROTIC_PLAGUE_JUMP = 70338 ,
SPELL_PLAGUE_SIPHON = 74074 ,
SPELL_SHADOW_TRAP = 73539 ,
SPELL_SHADOW_TRAP_AURA = 73525 ,
SPELL_SHADOW_TRAP_KNOCKBACK = 73529 ,
SPELL_DEFILE = 72762 ,
SPELL_DEFILE_AURA = 72743 ,
SPELL_DEFILE_GROW = 72756 ,
SPELL_SOUL_REAPER = 69409 ,
SPELL_SOUL_REAPER_BUFF = 69410 ,
SPELL_SUMMON_VALKYR = 69037 ,
SPELL_SUMMON_VALKYR_PERIODIC = 74361 ,
SPELL_WINGS_OF_THE_DAMNED = 74352 ,
SPELL_VALKYR_TARGET_SEARCH = 69030 ,
SPELL_HARVEST_SOUL_VALKYR = 68985 ,
SPELL_CHARGE = 74399 ,
SPELL_VALKYR_CARRY = 74445 ,
SPELL_EJECT_ALL_PASSENGERS = 68576 ,
SPELL_LIFE_SIPHON = 73488 ,
SPELL_LIFE_SIPHON_HEAL = 73489 ,
SPELL_VILE_SPIRITS = 70498 ,
SPELL_VILE_SPIRIT_MOVE_SEARCH = 70501 ,
SPELL_VILE_SPIRIT_DAMAGE_SEARCH = 70502 ,
SPELL_SPIRIT_BURST = 70503 ,
SPELL_HARVEST_SOUL = 68980 ,
SPELL_HARVEST_SOUL_VEHICLE = 68984 ,
SPELL_HARVEST_SOUL_VISUAL = 71372 ,
SPELL_HARVEST_SOUL_TELEPORT = 72546 ,
SPELL_HARVEST_SOUL_TELEPORT_BACK = 72597 ,
SPELL_KILL_FROSTMOURNE_PLAYERS = 75127 ,
SPELL_HARVESTED_SOUL_LK_BUFF = 72679 ,
SPELL_HARVEST_SOULS = 73654 ,
SPELL_HARVEST_SOULS_TELEPORT = 73655 ,
SPELL_LIGHTS_FAVOR = 69382 ,
SPELL_RESTORE_SOUL = 72595 ,
SPELL_RESTORE_SOULS = 73650 ,
SPELL_TERENAS_LOSES_INSIDE = 72572 ,
SPELL_DESTROY_SOUL = 74086 ,
SPELL_DARK_HUNGER = 69383 ,
SPELL_DARK_HUNGER_HEAL = 69384 ,
SPELL_SOUL_RIP = 69397 ,
SPELL_SOUL_RIP_DAMAGE = 69398 ,
SPELL_SUMMON_SPIRIT_BOMB_1 = 73581 ,
SPELL_SUMMON_SPIRIT_BOMB_2 = 74299 ,
SPELL_TRIGGER_VILE_SPIRIT_HEROIC = 73582 ,
SPELL_EXPLOSION = 73576 ,
SPELL_SHOCKWAVE = 72149 ,
SPELL_ENRAGE = 72143 ,
SPELL_FRENZY = 28747
}
enum Events {
EVENT_NONE ,
EVENT_INTRO_LK_MOVE ,
EVENT_INTRO_LK_TALK_1 ,
EVENT_INTRO_LK_EMOTE_CAST_SHOUT ,
EVENT_INTRO_LK_EMOTE_1 ,
EVENT_INTRO_LK_CAST_FREEZE ,
EVENT_INTRO_FORDRING_TALK_1 ,
EVENT_INTRO_FORDRING_TALK_2 ,
EVENT_INTRO_FORDRING_EMOTE_1 ,
EVENT_INTRO_FORDRING_CHARGE ,
EVENT_INTRO_FINISH ,
EVENT_OUTRO_LK_TALK_1 ,
EVENT_OUTRO_LK_TALK_2 ,
EVENT_OUTRO_LK_EMOTE_TALK ,
EVENT_OUTRO_LK_TALK_3 ,
EVENT_OUTRO_LK_EMOTE_CAST_SHOUT ,
EVENT_OUTRO_LK_MOVE_CENTER ,
EVENT_OUTRO_LK_TALK_4 ,
EVENT_OUTRO_LK_RAISE_DEAD ,
EVENT_OUTRO_LK_TALK_5 ,
EVENT_OUTRO_LK_TALK_6 ,
EVENT_OUTRO_LK_TALK_7 ,
EVENT_OUTRO_LK_TALK_8 ,
EVENT_OUTRO_FORDRING_TALK_1 ,
EVENT_OUTRO_FORDRING_BLESS ,
EVENT_OUTRO_FORDRING_REMOVE_ICE ,
EVENT_OUTRO_FORDRING_MOVE_1 ,
EVENT_OUTRO_FORDRING_JUMP ,
EVENT_OUTRO_AFTER_SUMMON_BROKEN_FROSTMOURNE ,
EVENT_OUTRO_KNOCK_BACK ,
EVENT_OUTRO_SOUL_BARRAGE ,
EVENT_OUTRO_AFTER_SOUL_BARRAGE ,
EVENT_OUTRO_SUMMON_TERENAS ,
EVENT_OUTRO_TERENAS_TALK_1 ,
EVENT_OUTRO_TERENAS_TALK_2 ,
EVENT_BERSERK ,
EVENT_START_ATTACK ,
EVENT_QUAKE ,
EVENT_QUAKE_2 ,
EVENT_SUMMON_SHAMBLING_HORROR ,
EVENT_SUMMON_DRUDGE_GHOUL ,
EVENT_INFEST ,
EVENT_NECROTIC_PLAGUE ,
EVENT_SHADOW_TRAP ,
EVENT_PAIN_AND_SUFFERING ,
EVENT_SUMMON_ICE_SPHERE ,
EVENT_SUMMON_RAGING_SPIRIT ,
EVENT_DEFILE ,
EVENT_SOUL_REAPER ,
EVENT_SUMMON_VALKYR ,
EVENT_VILE_SPIRITS ,
EVENT_HARVEST_SOUL ,
EVENT_HARVEST_SOULS ,
EVENT_FROSTMOURNE_HEROIC ,
EVENT_SHOCKWAVE ,
EVENT_ENRAGE ,
EVENT_SOUL_SHRIEK ,
EVENT_RAGING_SPIRIT_UNROOT ,
EVENT_GRAB_PLAYER ,
EVENT_MOVE_TO_DROP_POS ,
EVENT_MOVE_TO_SIPHON_POS ,
EVENT_LIFE_SIPHON ,
EVENT_TELEPORT ,
EVENT_MOVE_TO_LICH_KING ,
EVENT_DESPAWN_SELF ,
EVENT_FROSTMOURNE_TALK_1 ,
EVENT_FROSTMOURNE_TALK_2 ,
EVENT_FROSTMOURNE_TALK_3 ,
EVENT_DESTROY_SOUL ,
EVENT_TELEPORT_BACK ,
EVENT_SOUL_RIP
}
enum EventGroups {
EVENT_GROUP_NONE ,
EVENT_GROUP_ABILITIES ,
EVENT_GROUP_BERSERK ,
EVENT_GROUP_VILE_SPIRITS
}
enum Phases {
PHASE_NONE = 0 ,
PHASE_INTRO = 1 ,
PHASE_ONE = 2 ,
PHASE_TWO = 3 ,
PHASE_THREE = 4 ,
PHASE_TRANSITION = 5 ,
PHASE_FROSTMOURNE = 6 ,
PHASE_OUTRO = 7 ,
PHASE_MASK_NO_CAST_CHECK = (1 << PHASE_TRANSITION) | (1 << PHASE_FROSTMOURNE) | (1 << PHASE_OUTRO) ,
PHASE_MASK_NO_VICTIM = (1 << PHASE_INTRO) | (1 << PHASE_OUTRO) | (1 << PHASE_FROSTMOURNE)
}
enum MovePoints {
POINT_NONE ,
POINT_CENTER_1 ,
POINT_CENTER_2 ,
POINT_TIRION_INTRO ,
POINT_TIRION_OUTRO ,
POINT_DROP_PLAYER ,
POINT_START_SIPHON ,
POINT_GROUND
}
enum EncounterActions {
ACTION_NONE ,
ACTION_START_ATTACK ,
ACTION_OUTRO ,
ACTION_BREAK_FROSTMOURNE ,
ACTION_TELEPORT_BACK
}
enum MiscData {
LIGHT_SNOWSTORM = 2490 ,
LIGHT_SOULSTORM = 2508 ,
EQUIP_ASHBRINGER = 13262 ,
MUSIC_FROZEN_THRONE = 17457 ,
MUSIC_SPECIAL = 17458 ,
MUSIC_FURY_OF_FROSTMOURNE = 17459 ,
MUSIC_FINAL = 17460 ,
SOUND_PAIN = 17360 ,
EQUIP_ASHBRINGER_GLOWING = 50442 ,
EQUIP_BROKEN_FROSTMOURNE = 50840 ,
MOVIE_FALL_OF_THE_LICH_KING = 16
}
Functions
bool IsValidPlatformTarget (Unit const *target)
void SendPacketToPlayers (WorldPacket const *data, Unit *source)
void AddSC_boss_the_lich_king ()
Variables
Position const CenterPosition = {503.6282f, -2124.655f, 840.8569f, 0.0f}
Position const TirionSpawn = { 505.2118f, -2124.353f, 840.9403f, 3.141593f }
Position const TirionIntro = {488.2970f, -2124.840f, 840.8569f, 0.0f}
Position const TirionCharge = {472.8500f, -2124.350f, 840.8570f, 0.0f}
Position const LichKingIntro [3] = { {432.0851f, -2123.673f, 864.6582f, 0.0f}, {457.8351f, -2123.423f, 841.1582f, 0.0f}, {465.0730f, -2123.470f, 840.8569f, 0.0f} }
Position const OutroPosition1 = {488.6100f, -2124.620f, 840.8569f, 0.0f}
Position const OutroFlying = {509.6897f, -2124.561f, 845.3565f, 0.0f}
Position const TerenasSpawn = {495.5542f, -2517.012f, 1050.000f, 4.6993f}
Position const TerenasSpawnHeroic = {495.7080f, -2523.760f, 1050.000f, 0.0f}
Position const SpiritWardenSpawn = {495.3406f, -2529.983f, 1050.000f, 1.5592f}
Macro Definition Documentation
DATA_PLAGUE_STACK
#define DATA_PLAGUE_STACK 70337
DATA_VILE
#define DATA_VILE 45814622
HARVESTED_SOUL_BUFF
#define HARVESTED_SOUL_BUFF RAID_MODE<uint32>(72679, 74318, 74319, 74320)
NECROTIC_PLAGUE_LK
#define NECROTIC_PLAGUE_LK RAID_MODE<uint32>(70337, 73912, 73913, 73914)
NECROTIC_PLAGUE_PLR
#define NECROTIC_PLAGUE_PLR RAID_MODE<uint32>(70338, 73785, 73786, 73787)
REMORSELESS_WINTER_1
#define REMORSELESS_WINTER_1 RAID_MODE<uint32>(68981, 74270, 74271, 74272)
REMORSELESS_WINTER_2
#define REMORSELESS_WINTER_2 RAID_MODE<uint32>(72259, 74273, 74274, 74275)
SUMMON_VALKYR
#define SUMMON_VALKYR RAID_MODE<uint32>(69037, 74361, 69037, 74361)
Enumeration Type Documentation
EncounterActions
enum EncounterActions
Enumerator
ACTION_NONE
ACTION_START_ATTACK
ACTION_OUTRO
ACTION_BREAK_FROSTMOURNE
ACTION_TELEPORT_BACK
{
    ACTION_NONE,
    ACTION_START_ATTACK,
    ACTION_OUTRO,
    ACTION_BREAK_FROSTMOURNE,
    ACTION_TELEPORT_BACK,
};
EventGroups
enum EventGroups
Enumerator
EVENT_GROUP_NONE
EVENT_GROUP_ABILITIES
EVENT_GROUP_BERSERK
EVENT_GROUP_VILE_SPIRITS
{
    EVENT_GROUP_NONE,
    EVENT_GROUP_ABILITIES,
    EVENT_GROUP_BERSERK,
    EVENT_GROUP_VILE_SPIRITS,
};
Events
enum Events
Enumerator
EVENT_NONE
EVENT_INTRO_LK_MOVE
EVENT_INTRO_LK_TALK_1
EVENT_INTRO_LK_EMOTE_CAST_SHOUT
EVENT_INTRO_LK_EMOTE_1
EVENT_INTRO_LK_CAST_FREEZE
EVENT_INTRO_FORDRING_TALK_1
EVENT_INTRO_FORDRING_TALK_2
EVENT_INTRO_FORDRING_EMOTE_1
EVENT_INTRO_FORDRING_CHARGE
EVENT_INTRO_FINISH
EVENT_OUTRO_LK_TALK_1
EVENT_OUTRO_LK_TALK_2
EVENT_OUTRO_LK_EMOTE_TALK
EVENT_OUTRO_LK_TALK_3
EVENT_OUTRO_LK_EMOTE_CAST_SHOUT
EVENT_OUTRO_LK_MOVE_CENTER
EVENT_OUTRO_LK_TALK_4
EVENT_OUTRO_LK_RAISE_DEAD
EVENT_OUTRO_LK_TALK_5
EVENT_OUTRO_LK_TALK_6
EVENT_OUTRO_LK_TALK_7
EVENT_OUTRO_LK_TALK_8
EVENT_OUTRO_FORDRING_TALK_1
EVENT_OUTRO_FORDRING_BLESS
EVENT_OUTRO_FORDRING_REMOVE_ICE
EVENT_OUTRO_FORDRING_MOVE_1
EVENT_OUTRO_FORDRING_JUMP
EVENT_OUTRO_AFTER_SUMMON_BROKEN_FROSTMOURNE
EVENT_OUTRO_KNOCK_BACK
EVENT_OUTRO_SOUL_BARRAGE
EVENT_OUTRO_AFTER_SOUL_BARRAGE
EVENT_OUTRO_SUMMON_TERENAS
EVENT_OUTRO_TERENAS_TALK_1
EVENT_OUTRO_TERENAS_TALK_2
EVENT_BERSERK
EVENT_START_ATTACK
EVENT_QUAKE
EVENT_QUAKE_2
EVENT_SUMMON_SHAMBLING_HORROR
EVENT_SUMMON_DRUDGE_GHOUL
EVENT_INFEST
EVENT_NECROTIC_PLAGUE
EVENT_SHADOW_TRAP
EVENT_PAIN_AND_SUFFERING
EVENT_SUMMON_ICE_SPHERE
EVENT_SUMMON_RAGING_SPIRIT
EVENT_DEFILE
EVENT_SOUL_REAPER
EVENT_SUMMON_VALKYR
EVENT_VILE_SPIRITS
EVENT_HARVEST_SOUL
EVENT_HARVEST_SOULS
EVENT_FROSTMOURNE_HEROIC
EVENT_SHOCKWAVE
EVENT_ENRAGE
EVENT_SOUL_SHRIEK
EVENT_RAGING_SPIRIT_UNROOT
EVENT_GRAB_PLAYER
EVENT_MOVE_TO_DROP_POS
EVENT_MOVE_TO_SIPHON_POS
EVENT_LIFE_SIPHON
EVENT_TELEPORT
EVENT_MOVE_TO_LICH_KING
EVENT_DESPAWN_SELF
EVENT_FROSTMOURNE_TALK_1
EVENT_FROSTMOURNE_TALK_2
EVENT_FROSTMOURNE_TALK_3
EVENT_DESTROY_SOUL
EVENT_TELEPORT_BACK
EVENT_SOUL_RIP
{
    EVENT_NONE,
    // Intro
    EVENT_INTRO_LK_MOVE,
    EVENT_INTRO_LK_TALK_1,
    EVENT_INTRO_LK_EMOTE_CAST_SHOUT,
    EVENT_INTRO_LK_EMOTE_1,
    EVENT_INTRO_LK_CAST_FREEZE,
    EVENT_INTRO_FORDRING_TALK_1,
    EVENT_INTRO_FORDRING_TALK_2,
    EVENT_INTRO_FORDRING_EMOTE_1,
    EVENT_INTRO_FORDRING_CHARGE,
    EVENT_INTRO_FINISH,
    // Outro
    EVENT_OUTRO_LK_TALK_1,
    EVENT_OUTRO_LK_TALK_2,
    EVENT_OUTRO_LK_EMOTE_TALK,
    EVENT_OUTRO_LK_TALK_3,
    EVENT_OUTRO_LK_EMOTE_CAST_SHOUT,
    EVENT_OUTRO_LK_MOVE_CENTER,
    EVENT_OUTRO_LK_TALK_4,
    EVENT_OUTRO_LK_RAISE_DEAD,
    EVENT_OUTRO_LK_TALK_5,
    EVENT_OUTRO_LK_TALK_6,
    EVENT_OUTRO_LK_TALK_7,
    EVENT_OUTRO_LK_TALK_8,
    EVENT_OUTRO_FORDRING_TALK_1,
    EVENT_OUTRO_FORDRING_BLESS,
    EVENT_OUTRO_FORDRING_REMOVE_ICE,
    EVENT_OUTRO_FORDRING_MOVE_1,
    EVENT_OUTRO_FORDRING_JUMP,
    EVENT_OUTRO_AFTER_SUMMON_BROKEN_FROSTMOURNE,
    EVENT_OUTRO_KNOCK_BACK,
    EVENT_OUTRO_SOUL_BARRAGE,
    EVENT_OUTRO_AFTER_SOUL_BARRAGE,
    EVENT_OUTRO_SUMMON_TERENAS,
    EVENT_OUTRO_TERENAS_TALK_1,
    EVENT_OUTRO_TERENAS_TALK_2,
    // General
    EVENT_BERSERK,
    EVENT_START_ATTACK,
    EVENT_QUAKE,
    EVENT_QUAKE_2,
    // Combat
    EVENT_SUMMON_SHAMBLING_HORROR,
    EVENT_SUMMON_DRUDGE_GHOUL,
    EVENT_INFEST,
    EVENT_NECROTIC_PLAGUE,
    EVENT_SHADOW_TRAP,
    EVENT_PAIN_AND_SUFFERING,
    EVENT_SUMMON_ICE_SPHERE,
    EVENT_SUMMON_RAGING_SPIRIT,
    EVENT_DEFILE,
    EVENT_SOUL_REAPER,
    EVENT_SUMMON_VALKYR,
    EVENT_VILE_SPIRITS,
    EVENT_HARVEST_SOUL,
    EVENT_HARVEST_SOULS,
    EVENT_FROSTMOURNE_HEROIC,
    // Shambling Horror
    EVENT_SHOCKWAVE,
    EVENT_ENRAGE,
    // Raging Spirit
    EVENT_SOUL_SHRIEK,
    EVENT_RAGING_SPIRIT_UNROOT,
    // Val'kyr Shadowguard
    EVENT_GRAB_PLAYER,
    EVENT_MOVE_TO_DROP_POS,
    EVENT_MOVE_TO_SIPHON_POS,
    EVENT_LIFE_SIPHON,
    // Strangulate Vehicle (Harvest Soul)
    EVENT_TELEPORT,
    EVENT_MOVE_TO_LICH_KING,
    EVENT_DESPAWN_SELF,
    // Inside Frostmourne
    EVENT_FROSTMOURNE_TALK_1,
    EVENT_FROSTMOURNE_TALK_2,
    EVENT_FROSTMOURNE_TALK_3,
    EVENT_DESTROY_SOUL,
    EVENT_TELEPORT_BACK,
    EVENT_SOUL_RIP,
};
MiscData
enum MiscData
Enumerator
LIGHT_SNOWSTORM
LIGHT_SOULSTORM
EQUIP_ASHBRINGER
MUSIC_FROZEN_THRONE
MUSIC_SPECIAL
MUSIC_FURY_OF_FROSTMOURNE
MUSIC_FINAL
SOUND_PAIN
EQUIP_ASHBRINGER_GLOWING
EQUIP_BROKEN_FROSTMOURNE
MOVIE_FALL_OF_THE_LICH_KING
{
    LIGHT_SNOWSTORM             = 2490,
    LIGHT_SOULSTORM             = 2508,
    EQUIP_ASHBRINGER            = 13262,
    MUSIC_FROZEN_THRONE         = 17457,
    MUSIC_SPECIAL               = 17458, // Summon Shambling Horror, Remorseless Winter, Quake, Summon Val'kyr Periodic, Harvest Soul, Vile Spirits
    MUSIC_FURY_OF_FROSTMOURNE   = 17459,
    MUSIC_FINAL                 = 17460, // Raise Dead, Light's Blessing
    SOUND_PAIN                  = 17360, // separate sound, not attached to any text
    EQUIP_ASHBRINGER_GLOWING    = 50442,
    EQUIP_BROKEN_FROSTMOURNE    = 50840,
    MOVIE_FALL_OF_THE_LICH_KING = 16,
};
MovePoints
enum MovePoints
Enumerator
POINT_NONE
POINT_CENTER_1
POINT_CENTER_2
POINT_TIRION_INTRO
POINT_TIRION_OUTRO
POINT_DROP_PLAYER
POINT_START_SIPHON
POINT_GROUND
{
    POINT_NONE,
    POINT_CENTER_1,
    POINT_CENTER_2,
    POINT_TIRION_INTRO,
    POINT_TIRION_OUTRO,
    POINT_DROP_PLAYER,
    POINT_START_SIPHON,
    POINT_GROUND,
};
Phases
enum Phases
Enumerator
PHASE_NONE
PHASE_INTRO
PHASE_ONE
PHASE_TWO
PHASE_THREE
PHASE_TRANSITION
PHASE_FROSTMOURNE
PHASE_OUTRO
PHASE_MASK_NO_CAST_CHECK
PHASE_MASK_NO_VICTIM
{
    PHASE_NONE                  = 0,
    PHASE_INTRO                 = 1,
    PHASE_ONE                   = 2,
    PHASE_TWO                   = 3,
    PHASE_THREE                 = 4,
    PHASE_TRANSITION            = 5,
    PHASE_FROSTMOURNE           = 6, // only set on heroic mode when all players are sent into frostmourne
    PHASE_OUTRO                 = 7,
    PHASE_MASK_NO_CAST_CHECK    = (1 << PHASE_TRANSITION) | (1 << PHASE_FROSTMOURNE) | (1 << PHASE_OUTRO),
    PHASE_MASK_NO_VICTIM        = (1 << PHASE_INTRO) | (1 << PHASE_OUTRO) | (1 << PHASE_FROSTMOURNE),
};
Spells
enum Spells
Enumerator
SPELL_PLAGUE_AVOIDANCE
SPELL_EMOTE_SIT_NO_SHEATH
SPELL_BOSS_HITTIN_YA
SPELL_BOSS_HITTIN_YA_AURA
SPELL_EMOTE_SHOUT_NO_SHEATH
SPELL_ICE_LOCK
SPELL_FURY_OF_FROSTMOURNE
SPELL_FURY_OF_FROSTMOURNE_NO_REZ
SPELL_EMOTE_QUESTION_NO_SHEATH
SPELL_RAISE_DEAD
SPELL_LIGHTS_BLESSING
SPELL_JUMP
SPELL_JUMP_TRIGGERED
SPELL_JUMP_2
SPELL_SUMMON_BROKEN_FROSTMOURNE
SPELL_SUMMON_BROKEN_FROSTMOURNE_2
SPELL_SUMMON_BROKEN_FROSTMOURNE_3
SPELL_BROKEN_FROSTMOURNE
SPELL_BROKEN_FROSTMOURNE_KNOCK
SPELL_SOUL_BARRAGE
SPELL_SUMMON_TERENAS
SPELL_MASS_RESURRECTION
SPELL_MASS_RESURRECTION_REAL
SPELL_PLAY_MOVIE
SPELL_REMORSELESS_WINTER_1
SPELL_REMORSELESS_WINTER_2
SPELL_QUAKE
SPELL_PAIN_AND_SUFFERING
SPELL_SUMMON_ICE_SPHERE
SPELL_ICE_SPHERE
SPELL_ICE_BURST_TARGET_SEARCH
SPELL_ICE_PULSE
SPELL_ICE_BURST
SPELL_RAGING_SPIRIT
SPELL_RAGING_SPIRIT_VISUAL
SPELL_RAGING_SPIRIT_VISUAL_CLONE
SPELL_SOUL_SHRIEK
SPELL_RISEN_WITCH_DOCTOR_SPAWN
SPELL_SUMMON_SHAMBLING_HORROR
SPELL_SUMMON_DRUDGE_GHOULS
SPELL_INFEST
SPELL_NECROTIC_PLAGUE
SPELL_NECROTIC_PLAGUE_JUMP
SPELL_PLAGUE_SIPHON
SPELL_SHADOW_TRAP
SPELL_SHADOW_TRAP_AURA
SPELL_SHADOW_TRAP_KNOCKBACK
SPELL_DEFILE
SPELL_DEFILE_AURA
SPELL_DEFILE_GROW
SPELL_SOUL_REAPER
SPELL_SOUL_REAPER_BUFF
SPELL_SUMMON_VALKYR
SPELL_SUMMON_VALKYR_PERIODIC
SPELL_WINGS_OF_THE_DAMNED
SPELL_VALKYR_TARGET_SEARCH
SPELL_HARVEST_SOUL_VALKYR
SPELL_CHARGE
SPELL_VALKYR_CARRY
SPELL_EJECT_ALL_PASSENGERS
SPELL_LIFE_SIPHON
SPELL_LIFE_SIPHON_HEAL
SPELL_VILE_SPIRITS
SPELL_VILE_SPIRIT_MOVE_SEARCH
SPELL_VILE_SPIRIT_DAMAGE_SEARCH
SPELL_SPIRIT_BURST
SPELL_HARVEST_SOUL
SPELL_HARVEST_SOUL_VEHICLE
SPELL_HARVEST_SOUL_VISUAL
SPELL_HARVEST_SOUL_TELEPORT
SPELL_HARVEST_SOUL_TELEPORT_BACK
SPELL_KILL_FROSTMOURNE_PLAYERS
SPELL_HARVESTED_SOUL_LK_BUFF
SPELL_HARVEST_SOULS
SPELL_HARVEST_SOULS_TELEPORT
SPELL_LIGHTS_FAVOR
SPELL_RESTORE_SOUL
SPELL_RESTORE_SOULS
SPELL_TERENAS_LOSES_INSIDE
SPELL_DESTROY_SOUL
SPELL_DARK_HUNGER
SPELL_DARK_HUNGER_HEAL
SPELL_SOUL_RIP
SPELL_SOUL_RIP_DAMAGE
SPELL_SUMMON_SPIRIT_BOMB_1
SPELL_SUMMON_SPIRIT_BOMB_2
SPELL_TRIGGER_VILE_SPIRIT_HEROIC
SPELL_EXPLOSION
SPELL_SHOCKWAVE
SPELL_ENRAGE
SPELL_FRENZY
{
    // Basic
    SPELL_PLAGUE_AVOIDANCE              = 72846,
    SPELL_EMOTE_SIT_NO_SHEATH           = 73220,
    SPELL_BOSS_HITTIN_YA                = 73878,
    SPELL_BOSS_HITTIN_YA_AURA           = 73879,
    SPELL_EMOTE_SHOUT_NO_SHEATH         = 73213,
    SPELL_ICE_LOCK                      = 71614,
    // Outro
    SPELL_FURY_OF_FROSTMOURNE           = 72350,
    SPELL_FURY_OF_FROSTMOURNE_NO_REZ    = 72351,
    SPELL_EMOTE_QUESTION_NO_SHEATH      = 73330,
    SPELL_RAISE_DEAD                    = 71769,
    SPELL_LIGHTS_BLESSING               = 71797,
    SPELL_JUMP                          = 71809,
    SPELL_JUMP_TRIGGERED                = 71811,
    SPELL_JUMP_2                        = 72431,
    SPELL_SUMMON_BROKEN_FROSTMOURNE     = 74081,
    SPELL_SUMMON_BROKEN_FROSTMOURNE_2   = 72406,
    SPELL_SUMMON_BROKEN_FROSTMOURNE_3   = 73017,
    SPELL_BROKEN_FROSTMOURNE            = 72398,
    SPELL_BROKEN_FROSTMOURNE_KNOCK      = 72405,
    SPELL_SOUL_BARRAGE                  = 72305,
    SPELL_SUMMON_TERENAS                = 72420,
    SPELL_MASS_RESURRECTION             = 72429,
    SPELL_MASS_RESURRECTION_REAL        = 72423,
    SPELL_PLAY_MOVIE                    = 73159,
    // Phase Transition
    SPELL_REMORSELESS_WINTER_1          = 68981,
    SPELL_REMORSELESS_WINTER_2          = 72259,
    SPELL_QUAKE                         = 72262,
    SPELL_PAIN_AND_SUFFERING            = 72133,
    SPELL_SUMMON_ICE_SPHERE             = 69104,
    SPELL_ICE_SPHERE                    = 69090,
    SPELL_ICE_BURST_TARGET_SEARCH       = 69109,
    SPELL_ICE_PULSE                     = 69091,
    SPELL_ICE_BURST                     = 69108,
    SPELL_RAGING_SPIRIT                 = 69200,
    SPELL_RAGING_SPIRIT_VISUAL          = 69197,
    SPELL_RAGING_SPIRIT_VISUAL_CLONE    = 69198,
    SPELL_SOUL_SHRIEK                   = 69242,
    // Phase 1
    SPELL_RISEN_WITCH_DOCTOR_SPAWN      = 69639,
    SPELL_SUMMON_SHAMBLING_HORROR       = 70372,
    SPELL_SUMMON_DRUDGE_GHOULS          = 70358,
    SPELL_INFEST                        = 70541, //cast time 2 sec
    SPELL_NECROTIC_PLAGUE               = 70337,
    SPELL_NECROTIC_PLAGUE_JUMP          = 70338,
    SPELL_PLAGUE_SIPHON                 = 74074,
    SPELL_SHADOW_TRAP                   = 73539,
    SPELL_SHADOW_TRAP_AURA              = 73525,
    SPELL_SHADOW_TRAP_KNOCKBACK         = 73529,
    // Phase 2
    SPELL_DEFILE                        = 72762, //cast time 2 sec
    SPELL_DEFILE_AURA                   = 72743,
    SPELL_DEFILE_GROW                   = 72756,
    SPELL_SOUL_REAPER                   = 69409, // instant
    SPELL_SOUL_REAPER_BUFF              = 69410,
    SPELL_SUMMON_VALKYR                 = 69037, // instant
    SPELL_SUMMON_VALKYR_PERIODIC        = 74361,
    SPELL_WINGS_OF_THE_DAMNED           = 74352,
    SPELL_VALKYR_TARGET_SEARCH          = 69030,
    SPELL_HARVEST_SOUL_VALKYR           = 68985, // vehicle aura used by Val'kyr Shadowguard and Strangulate Vehicle
    SPELL_CHARGE                        = 74399,
    SPELL_VALKYR_CARRY                  = 74445,
    SPELL_EJECT_ALL_PASSENGERS          = 68576,
    SPELL_LIFE_SIPHON                   = 73488,
    SPELL_LIFE_SIPHON_HEAL              = 73489,
    // Phase 3
    SPELL_VILE_SPIRITS                  = 70498,
    SPELL_VILE_SPIRIT_MOVE_SEARCH       = 70501,
    SPELL_VILE_SPIRIT_DAMAGE_SEARCH     = 70502,
    SPELL_SPIRIT_BURST                  = 70503,
    SPELL_HARVEST_SOUL                  = 68980,
    SPELL_HARVEST_SOUL_VEHICLE          = 68984,
    SPELL_HARVEST_SOUL_VISUAL           = 71372,
    SPELL_HARVEST_SOUL_TELEPORT         = 72546,
    SPELL_HARVEST_SOUL_TELEPORT_BACK    = 72597,
    SPELL_KILL_FROSTMOURNE_PLAYERS      = 75127,
    SPELL_HARVESTED_SOUL_LK_BUFF        = 72679,
    SPELL_HARVEST_SOULS                 = 73654,
    SPELL_HARVEST_SOULS_TELEPORT        = 73655,
    //SPELL_IN_FROSTMOURNE_ROOM           = 74276,
    // Frostmourne
    SPELL_LIGHTS_FAVOR                  = 69382,
    SPELL_RESTORE_SOUL                  = 72595,
    SPELL_RESTORE_SOULS                 = 73650,
    SPELL_TERENAS_LOSES_INSIDE          = 72572,
    SPELL_DESTROY_SOUL                  = 74086,
    SPELL_DARK_HUNGER                   = 69383,    // Passive proc healing
    SPELL_DARK_HUNGER_HEAL              = 69384,
    SPELL_SOUL_RIP                      = 69397,    // Deals increasing damage
    SPELL_SOUL_RIP_DAMAGE               = 69398,
    SPELL_SUMMON_SPIRIT_BOMB_1          = 73581,
    SPELL_SUMMON_SPIRIT_BOMB_2          = 74299,
    SPELL_TRIGGER_VILE_SPIRIT_HEROIC    = 73582,
    SPELL_EXPLOSION                     = 73576,
    // Shambling Horror
    SPELL_SHOCKWAVE                     = 72149,
    SPELL_ENRAGE                        = 72143,
    SPELL_FRENZY                        = 28747,
};
Texts
enum Texts
Enumerator
SAY_LK_INTRO_1
SAY_LK_INTRO_2
SAY_LK_INTRO_3
SAY_LK_REMORSELESS_WINTER
SAY_LK_QUAKE
SAY_LK_SUMMON_VALKYR
SAY_LK_HARVEST_SOUL
SAY_LK_FROSTMOURNE_ESCAPE
SAY_LK_FROSTMOURNE_KILL
SAY_LK_KILL
SAY_LK_BERSERK
EMOTE_DEFILE_WARNING
EMOTE_NECROTIC_PLAGUE_WARNING
SAY_LK_OUTRO_1
SAY_LK_OUTRO_2
SAY_LK_OUTRO_3
SAY_LK_OUTRO_4
SAY_LK_OUTRO_5
SAY_LK_OUTRO_6
SAY_LK_OUTRO_7
SAY_LK_OUTRO_8
SAY_TIRION_INTRO_1
SAY_TIRION_INTRO_2
SAY_TIRION_OUTRO_1
SAY_TIRION_OUTRO_2
SAY_TIRION_OUTRO_3
SAY_TERENAS_OUTRO_1
SAY_TERENAS_OUTRO_2
SAY_TERENAS_INTRO_1
SAY_TERENAS_INTRO_2
SAY_TERENAS_INTRO_3
{
    // The Lich King
    SAY_LK_INTRO_1                  = 0,
    SAY_LK_INTRO_2                  = 1,
    SAY_LK_INTRO_3                  = 2,
    SAY_LK_REMORSELESS_WINTER       = 4,
    SAY_LK_QUAKE                    = 5,
    SAY_LK_SUMMON_VALKYR            = 6,
    SAY_LK_HARVEST_SOUL             = 7,
    SAY_LK_FROSTMOURNE_ESCAPE       = 8,    // not said on heroic
    SAY_LK_FROSTMOURNE_KILL         = 9,    // not said on heroic
    SAY_LK_KILL                     = 10,
    SAY_LK_BERSERK                  = 11,
    EMOTE_DEFILE_WARNING            = 12,
    EMOTE_NECROTIC_PLAGUE_WARNING   = 13,
    SAY_LK_OUTRO_1                  = 14,
    SAY_LK_OUTRO_2                  = 15,
    SAY_LK_OUTRO_3                  = 16,
    SAY_LK_OUTRO_4                  = 17,
    SAY_LK_OUTRO_5                  = 18,
    SAY_LK_OUTRO_6                  = 19,
    SAY_LK_OUTRO_7                  = 20,
    SAY_LK_OUTRO_8                  = 21,
    // Highlord Tirion Fordring
    SAY_TIRION_INTRO_1              = 0,
    SAY_TIRION_INTRO_2              = 1,
    SAY_TIRION_OUTRO_1              = 2,
    SAY_TIRION_OUTRO_2              = 3,
    SAY_TIRION_OUTRO_3              = 4,
    // Terenas Menethil (outro)
    SAY_TERENAS_OUTRO_1             = 0,
    SAY_TERENAS_OUTRO_2             = 1,
    // Terenas Menethil (Frostmourne)
    SAY_TERENAS_INTRO_1             = 0,
    SAY_TERENAS_INTRO_2             = 1,
    SAY_TERENAS_INTRO_3             = 2,
};
Function Documentation
AddSC_boss_the_lich_king()
void AddSC_boss_the_lich_king ()
{
    new boss_the_lich_king();
    new npc_tirion_fordring_tft();
    RegisterSpellScript(spell_the_lich_king_quake);
    RegisterSpellScript(spell_the_lich_king_jump);
    RegisterSpellScript(spell_the_lich_king_jump_remove_aura);
    RegisterSpellScriptWithArgs(spell_trigger_spell_from_caster, "spell_the_lich_king_mass_resurrection", SPELL_MASS_RESURRECTION_REAL);
    RegisterSpellScript(spell_the_lich_king_play_movie);
    // fight stuff below
    new npc_shambling_horror_icc();
    RegisterSpellScript(spell_the_lich_king_infest_aura);
    RegisterSpellScript(spell_the_lich_king_necrotic_plague_aura);
    RegisterSpellAndAuraScriptPair(spell_the_lich_king_necrotic_plague_jump, spell_the_lich_king_necrotic_plague_jump_aura);
    RegisterSpellScript(spell_the_lich_king_shadow_trap_visual_aura);
    RegisterSpellScript(spell_the_lich_king_shadow_trap_periodic);
    RegisterSpellScript(spell_the_lich_king_ice_burst_target_search);
    new npc_icc_ice_sphere();
    RegisterSpellScript(spell_the_lich_king_raging_spirit);
    new npc_raging_spirit();
    RegisterSpellScript(spell_the_lich_king_defile);
    RegisterSpellScript(spell_the_lich_king_soul_reaper_aura);
    new npc_valkyr_shadowguard();
    RegisterSpellScript(spell_the_lich_king_summon_into_air);
    RegisterSpellScript(spell_the_lich_king_teleport_to_frostmourne_hc);
    RegisterSpellScript(spell_the_lich_king_valkyr_target_search);
    RegisterSpellScript(spell_the_lich_king_cast_back_to_caster);
    RegisterSpellScript(spell_the_lich_king_life_siphon);
    RegisterSpellScript(spell_the_lich_king_vile_spirits_aura);
    RegisterSpellScript(spell_the_lich_king_vile_spirits_visual);
    RegisterSpellScript(spell_the_lich_king_vile_spirit_move_target_search);
    RegisterSpellScript(spell_the_lich_king_vile_spirit_damage_target_search);
    RegisterSpellScript(spell_the_lich_king_harvest_soul_aura);
    new npc_strangulate_vehicle();
    new npc_terenas_menethil();
    RegisterSpellScript(spell_the_lich_king_lights_favor_aura);
    RegisterSpellScript(spell_the_lich_king_restore_soul);
    new npc_spirit_warden();
    RegisterSpellScript(spell_the_lich_king_dark_hunger_aura);
    RegisterSpellScript(spell_the_lich_king_soul_rip_aura);
    new npc_icc_lk_checktarget();
    RegisterSpellScript(spell_the_lich_king_summon_spirit_bomb);
    new npc_lk_spirit_bomb();
    RegisterSpellScript(spell_the_lich_king_trigger_vile_spirit);
    new npc_lk_wicked_spirit();
    new achievement_been_waiting_long_time();
    new achievement_neck_deep_in_vile();
}
References RegisterSpellAndAuraScriptPair, RegisterSpellScript, RegisterSpellScriptWithArgs, and SPELL_MASS_RESURRECTION_REAL.
Referenced by AddNorthrendScripts().
IsValidPlatformTarget()
bool IsValidPlatformTarget (Unit const * target)
{
    return target->GetExactDist2dSq(&CenterPosition) < 90.0f * 90.0f && target->GetPositionZ() > 840.0f && target->GetPositionZ() < 875.0f;
}
References CenterPosition, Position::GetExactDist2dSq(), and Position::GetPositionZ().
Referenced by boss_the_lich_king::boss_the_lich_kingAI::CanAIAttack(), npc_shambling_horror_icc::npc_shambling_horror_iccAI::CanAIAttack(), npc_raging_spirit::npc_raging_spiritAI::CanAIAttack(), and npc_icc_lk_checktarget::npc_icc_lk_checktargetAI::CanAIAttack().
SendPacketToPlayers()
void SendPacketToPlayers (WorldPacket const * data, Unit * source)
{
    // Send packet to all players in The Frozen Throne
    Map::PlayerList const& players = source->GetMap()->GetPlayers();
    if (!players.IsEmpty())
        for (Map::PlayerList::const_iterator itr = players.begin(); itr != players.end(); ++itr)
            if (Player* player = itr->GetSource())
                if (player->GetAreaId() == AREA_THE_FROZEN_THRONE)
                    player->GetSession()->SendPacket(data);
}
References AREA_THE_FROZEN_THRONE, MapRefMgr::begin(), MapRefMgr::end(), WorldObject::GetMap(), Map::GetPlayers(), and LinkedListHead::IsEmpty().
Variable Documentation
CenterPosition
Position const CenterPosition = {503.6282f, -2124.655f, 840.8569f, 0.0f}
{503.6282f, -2124.655f, 840.8569f, 0.0f};
Referenced by boss_the_lich_king::boss_the_lich_kingAI::DamageTaken(), npc_valkyr_shadowguard::npc_valkyr_shadowguardAI::GoSiphon(), IsValidPlatformTarget(), boss_the_lich_king::boss_the_lich_kingAI::JustSummoned(), npc_tirion_fordring_tft::npc_tirion_fordringAI::UpdateAI(), and npc_icc_ice_sphere::npc_icc_ice_sphereAI::UpdateAI().
LichKingIntro
Position const LichKingIntro[3] = { {432.0851f, -2123.673f, 864.6582f, 0.0f}, {457.8351f, -2123.423f, 841.1582f, 0.0f}, {465.0730f, -2123.470f, 840.8569f, 0.0f} }
{ {432.0851f, -2123.673f, 864.6582f, 0.0f}, {457.8351f, -2123.423f, 841.1582f, 0.0f}, {465.0730f, -2123.470f, 840.8569f, 0.0f} };
Referenced by npc_tirion_fordring_tft::npc_tirion_fordringAI::UpdateAI().
OutroFlying
Position const OutroFlying = {509.6897f, -2124.561f, 845.3565f, 0.0f}
{509.6897f, -2124.561f, 845.3565f, 0.0f};
Referenced by npc_tirion_fordring_tft::npc_tirion_fordringAI::UpdateAI().
OutroPosition1
Position const OutroPosition1 = {488.6100f, -2124.620f, 840.8569f, 0.0f}
{488.6100f, -2124.620f, 840.8569f, 0.0f};
Referenced by npc_tirion_fordring_tft::npc_tirion_fordringAI::UpdateAI().
SpiritWardenSpawn
Position const SpiritWardenSpawn = {495.3406f, -2529.983f, 1050.000f, 1.5592f}
{495.3406f, -2529.983f, 1050.000f, 1.5592f};
Referenced by instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::ProcessEvent().
TerenasSpawn
Position const TerenasSpawn = {495.5542f, -2517.012f, 1050.000f, 4.6993f}
{495.5542f, -2517.012f, 1050.000f, 4.6993f};
Referenced by instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::ProcessEvent().
TerenasSpawnHeroic
Position const TerenasSpawnHeroic = {495.7080f, -2523.760f, 1050.000f, 0.0f}
{495.7080f, -2523.760f, 1050.000f, 0.0f};
Referenced by boss_the_lich_king::boss_the_lich_kingAI::UpdateAI().
TirionCharge
Position const TirionCharge = {472.8500f, -2124.350f, 840.8570f, 0.0f}
{472.8500f, -2124.350f, 840.8570f, 0.0f};
Referenced by npc_tirion_fordring_tft::npc_tirion_fordringAI::UpdateAI().
TirionIntro
Position const TirionIntro = {488.2970f, -2124.840f, 840.8569f, 0.0f}
{488.2970f, -2124.840f, 840.8569f, 0.0f};
Referenced by npc_tirion_fordring_tft::npc_tirion_fordringAI::sGossipSelect().
TirionSpawn
Position const TirionSpawn = { 505.2118f, -2124.353f, 840.9403f, 3.141593f }
{ 505.2118f, -2124.353f, 840.9403f, 3.141593f };
Referenced by boss_the_lich_king::boss_the_lich_kingAI::Reset().