AzerothCore Doxygen
ElunaUtil::WorldObjectInRangeCheck Class Reference
#include "ElunaUtility.h"
Public Member Functions
WorldObjectInRangeCheck (bool nearest, WorldObject const *obj, float range, uint16 typeMask=0, uint32 entry=0, uint32 hostile=0, uint32 dead=0)
WorldObject const & GetFocusObject () const
bool operator() (WorldObject *u)
Public Attributes
WorldObject const *const i_obj
Unit const * i_obj_unit
FactionTemplateEntry const * i_obj_fact
uint32 const i_hostile
uint32 const i_entry
float i_range
uint16 const i_typeMask
uint32 const i_dead
bool const i_nearest
Detailed Description
Constructor & Destructor Documentation
WorldObjectInRangeCheck()
ElunaUtil::WorldObjectInRangeCheck::WorldObjectInRangeCheck (bool nearest, WorldObject const * obj, float range, uint16 typeMask = 0, uint32 entry = 0, uint32 hostile = 0, uint32 dead = 0)
                                                                :
    i_obj(obj), i_obj_unit(nullptr), i_obj_fact(nullptr), i_hostile(hostile), i_entry(entry), i_range(range), i_typeMask(typeMask), i_dead(dead), i_nearest(nearest)
{
    i_obj_unit = i_obj->ToUnit();
    if (!i_obj_unit)
        if (GameObject const* go = i_obj->ToGameObject())
            i_obj_unit = go->GetOwner();
    if (!i_obj_unit)
        i_obj_fact = sFactionTemplateStore.LookupEntry(14);
}
References Unit::GetOwner(), i_obj, i_obj_fact, i_obj_unit, sFactionTemplateStore, Object::ToGameObject(), and Object::ToUnit().
Member Function Documentation
GetFocusObject()
WorldObject const & ElunaUtil::WorldObjectInRangeCheck::GetFocusObject () const
{
    return *i_obj;
}
operator()()
bool ElunaUtil::WorldObjectInRangeCheck::operator() (WorldObject * u)
{
    if (i_typeMask && !u->isType(TypeMask(i_typeMask)))
        return false;
    if (i_entry && u->GetEntry() != i_entry)
        return false;
    if (i_obj->GET_GUID() == u->GET_GUID())
        return false;
    if (!i_obj->IsWithinDistInMap(u, i_range))
        return false;
    Unit const* target = u->ToUnit();
    if (!target)
        if (GameObject const* go = u->ToGameObject())
            target = go->GetOwner();
    if (target)
    {
#ifdef CMANGOS
        if (i_dead && (i_dead == 1) != target->isAlive())
            return false;
#else
        if (i_dead && (i_dead == 1) != target->IsAlive())
            return false;
#endif
        if (i_hostile)
        {
            if (!i_obj_unit)
            {
                if (i_obj_fact)
                {
#if defined TRINITY || AZEROTHCORE
                    if ((i_obj_fact->IsHostileTo(*target->GetFactionTemplateEntry())) != (i_hostile == 1))
                        return false;
#else
                    if ((i_obj_fact->IsHostileTo(*target->getFactionTemplateEntry())) != (i_hostile == 1))
                        return false;
#endif
                }
                else if (i_hostile == 1)
                    return false;
            }
            else if ((i_hostile == 1) != i_obj_unit->IsHostileTo(target))
                return false;
        }
    }
    if (i_nearest)
        i_range = i_obj->GetDistance(u);
    return true;
}
References WorldObject::GetDistance(), Object::GetEntry(), Unit::GetFactionTemplateEntry(), Unit::GetOwner(), Unit::IsAlive(), Object::isType(), Object::ToGameObject(), and Object::ToUnit().
Member Data Documentation
i_dead
uint32 const ElunaUtil::WorldObjectInRangeCheck::i_dead
i_entry
uint32 const ElunaUtil::WorldObjectInRangeCheck::i_entry
i_hostile
uint32 const ElunaUtil::WorldObjectInRangeCheck::i_hostile
i_nearest
bool const ElunaUtil::WorldObjectInRangeCheck::i_nearest
i_obj
WorldObject const* const ElunaUtil::WorldObjectInRangeCheck::i_obj
Referenced by WorldObjectInRangeCheck().
i_obj_fact
FactionTemplateEntry const* ElunaUtil::WorldObjectInRangeCheck::i_obj_fact
Referenced by WorldObjectInRangeCheck().
i_obj_unit
Unit const* ElunaUtil::WorldObjectInRangeCheck::i_obj_unit
Referenced by WorldObjectInRangeCheck().
i_range
float ElunaUtil::WorldObjectInRangeCheck::i_range
i_typeMask
uint16 const ElunaUtil::WorldObjectInRangeCheck::i_typeMask
The documentation for this class was generated from the following files:
mod-eluna/src/LuaEngine/ElunaUtility.h
mod-eluna/src/LuaEngine/ElunaUtility.cpp