AzerothCore Doxygen
CascadeProcSuppressionTest.cpp File Reference
Unit tests for cascade proc suppression via SPELL_ATTR3_INSTANT_TARGET_PROCS.
#include "ProcChanceTestHelper.h"
#include "SpellInfoTestHelper.h"
#include "gtest/gtest.h"
Classes
class CascadeProcSuppressionTest
struct RealSpellTestCase
class CascadeProcRealSpellTest
Functions
TEST_F (CascadeProcSuppressionTest, NormalSpellNormalAura_NotSuppressed)
TEST_F (CascadeProcSuppressionTest, ProcDisabledSpell_NormalAura_Suppressed)
TEST_F (CascadeProcSuppressionTest, ProcDisabledSpell_WithAttr_Suppressed)
TEST_F (CascadeProcSuppressionTest, NormalSpell_AuraWithAttr_Suppressed)
TEST_F (CascadeProcSuppressionTest, SpellInfo_WithAttr_HasAttributeReturnsTrue)
TEST_F (CascadeProcSuppressionTest, SpellInfo_WithoutAttr_HasAttributeReturnsFalse)
TEST_F (CascadeProcSuppressionTest, SpellInfo_WithMixedBits_HasAttributeReturnsTrue)
TEST_P (CascadeProcRealSpellTest, VerifySuppressionForRealSpell)
INSTANTIATE_TEST_SUITE_P (CascadeProcSuppression, CascadeProcRealSpellTest, ::testing::Values(RealSpellTestCase{"Seal Fate", 14195, true}, RealSpellTestCase{"Sword Specialization", 12281, true}, RealSpellTestCase{"Reckoning", 20178, true}, RealSpellTestCase{"Flurry", 16257, true}, RealSpellTestCase{"Eviscerate", 26865, false}), [](testing::TestParamInfo< RealSpellTestCase > const &info) { std::string name=info.param.name;std::replace(name.begin(), name.end(), ' ', '_');return name;})
TEST_F (CascadeProcSuppressionTest, BothFlagsSet_StillSuppressed)
TEST_F (CascadeProcSuppressionTest, OnlyOuterFlag_Suppressed)
TEST_F (CascadeProcSuppressionTest, OnlyPerAuraFlag_Suppressed)
Detailed Description
Unit tests for cascade proc suppression via SPELL_ATTR3_INSTANT_TARGET_PROCS.
Tests the logic from Unit.cpp TriggerAurasProcOnEvent:
Outer check: Spell::IsProcDisabled() (TRIGGERED_DISALLOW_PROC_EVENTS) suppresses all cascade procs
Per-aura check: SPELL_ATTR3_INSTANT_TARGET_PROCS (0x80000) suppresses cascade for that aura
Normal spells/auras without these flags allow cascading
Both flags set simultaneously still suppresses correctly
Definition in file CascadeProcSuppressionTest.cpp.
Function Documentation
INSTANTIATE_TEST_SUITE_P()
INSTANTIATE_TEST_SUITE_P (CascadeProcSuppression , CascadeProcRealSpellTest , ::testing::Values(RealSpellTestCase{"Seal Fate", 14195, true}, RealSpellTestCase{"Sword Specialization", 12281, true}, RealSpellTestCase{"Reckoning", 20178, true}, RealSpellTestCase{"Flurry", 16257, true}, RealSpellTestCase{"Eviscerate", 26865, false}) , [] (testing::TestParamInfo< RealSpellTestCase > const &info) { std::string name=info.param.name;std::replace(name.begin(), name.end(), ' ', '_');return name;})
TEST_F() [1/10]
TEST_F (CascadeProcSuppressionTest , BothFlagsSet_StillSuppressed)
{
    auto config = MakeConfig(true, true);
    EXPECT_TRUE(ProcChanceTestHelper::ShouldSuppressCascadingProc(config))
        << "Both IsProcDisabled and INSTANT_TARGET_PROCS set should still suppress";
}
References ProcChanceTestHelper::ShouldSuppressCascadingProc().
TEST_F() [2/10]
TEST_F (CascadeProcSuppressionTest , NormalSpell_AuraWithAttr_Suppressed)
{
    auto config = MakeConfig(false, true);
    EXPECT_TRUE(ProcChanceTestHelper::ShouldSuppressCascadingProc(config))
        << "Aura with SPELL_ATTR3_INSTANT_TARGET_PROCS should suppress cascading procs";
}
References ProcChanceTestHelper::ShouldSuppressCascadingProc().
TEST_F() [3/10]
TEST_F (CascadeProcSuppressionTest , NormalSpellNormalAura_NotSuppressed)
{
    auto config = MakeConfig(false, false);
    EXPECT_FALSE(ProcChanceTestHelper::ShouldSuppressCascadingProc(config))
        << "Normal spell + normal aura should not suppress cascading procs";
}
References ProcChanceTestHelper::ShouldSuppressCascadingProc().
TEST_F() [4/10]
TEST_F (CascadeProcSuppressionTest , OnlyOuterFlag_Suppressed)
{
    auto config = MakeConfig(true, false);
    EXPECT_TRUE(ProcChanceTestHelper::ShouldSuppressCascadingProc(config))
        << "Only IsProcDisabled should be sufficient to suppress";
}
References ProcChanceTestHelper::ShouldSuppressCascadingProc().
TEST_F() [5/10]
TEST_F (CascadeProcSuppressionTest , OnlyPerAuraFlag_Suppressed)
{
    auto config = MakeConfig(false, true);
    EXPECT_TRUE(ProcChanceTestHelper::ShouldSuppressCascadingProc(config))
        << "Only INSTANT_TARGET_PROCS should be sufficient to suppress";
}
References ProcChanceTestHelper::ShouldSuppressCascadingProc().
TEST_F() [6/10]
TEST_F (CascadeProcSuppressionTest , ProcDisabledSpell_NormalAura_Suppressed)
{
    auto config = MakeConfig(true, false);
    EXPECT_TRUE(ProcChanceTestHelper::ShouldSuppressCascadingProc(config))
        << "Triggered spell with DISALLOW_PROC_EVENTS should suppress all cascading procs";
}
References ProcChanceTestHelper::ShouldSuppressCascadingProc().
TEST_F() [7/10]
TEST_F (CascadeProcSuppressionTest , ProcDisabledSpell_WithAttr_Suppressed)
{
    auto config = MakeConfig(true, true);
    EXPECT_TRUE(ProcChanceTestHelper::ShouldSuppressCascadingProc(config))
        << "Both flags set should still suppress (double-suppress doesn't break)";
}
References ProcChanceTestHelper::ShouldSuppressCascadingProc().
TEST_F() [8/10]
TEST_F (CascadeProcSuppressionTest , SpellInfo_WithAttr_HasAttributeReturnsTrue)
{
    auto spellInfo = SpellInfoBuilder()
        .WithId(99001)
        .WithAttributesEx3(SPELL_ATTR3_INSTANT_TARGET_PROCS)
        .BuildUnique();
    EXPECT_TRUE(spellInfo->HasAttribute(SPELL_ATTR3_INSTANT_TARGET_PROCS))
        << "SpellInfo built with 0x80000 should report HasAttribute true";
}
References SpellInfoBuilder::BuildUnique(), SPELL_ATTR3_INSTANT_TARGET_PROCS, SpellInfoBuilder::WithAttributesEx3(), and SpellInfoBuilder::WithId().
TEST_F() [9/10]
TEST_F (CascadeProcSuppressionTest , SpellInfo_WithMixedBits_HasAttributeReturnsTrue)
{
    // 0x80001 = SPELL_ATTR3_INSTANT_TARGET_PROCS | SPELL_ATTR3_PVP_ENABLING (bit 0)
    auto spellInfo = SpellInfoBuilder()
        .WithId(99003)
        .WithAttributesEx3(0x00080001)
        .BuildUnique();
    EXPECT_TRUE(spellInfo->HasAttribute(SPELL_ATTR3_INSTANT_TARGET_PROCS))
        << "Other bits in AttributesEx3 should not interfere with attribute detection";
}
References SpellInfoBuilder::BuildUnique(), SPELL_ATTR3_INSTANT_TARGET_PROCS, SpellInfoBuilder::WithAttributesEx3(), and SpellInfoBuilder::WithId().
TEST_F() [10/10]
TEST_F (CascadeProcSuppressionTest , SpellInfo_WithoutAttr_HasAttributeReturnsFalse)
{
    auto spellInfo = SpellInfoBuilder()
        .WithId(99002)
        .WithAttributesEx3(0)
        .BuildUnique();
    EXPECT_FALSE(spellInfo->HasAttribute(SPELL_ATTR3_INSTANT_TARGET_PROCS))
        << "SpellInfo built with 0 should report HasAttribute false";
}
References SpellInfoBuilder::BuildUnique(), SPELL_ATTR3_INSTANT_TARGET_PROCS, SpellInfoBuilder::WithAttributesEx3(), and SpellInfoBuilder::WithId().
TEST_P()
TEST_P (CascadeProcRealSpellTest , VerifySuppressionForRealSpell)
{
    auto const& tc = GetParam();
    // Build a SpellInfo mimicking the real spell's AttributesEx3
    auto spellInfo = SpellInfoBuilder()
        .WithId(tc.spellId)
        .WithAttributesEx3(tc.hasAttr ? SPELL_ATTR3_INSTANT_TARGET_PROCS : 0)
        .BuildUnique();
    // Verify attribute detection matches expectation
    EXPECT_EQ(spellInfo->HasAttribute(SPELL_ATTR3_INSTANT_TARGET_PROCS), tc.hasAttr)
        << tc.name << " (spell " << tc.spellId << ") attribute detection mismatch";
    // Verify cascade suppression matches attribute presence
    ProcChanceTestHelper::CascadeProcConfig config;
    config.triggeringSpellIsProcDisabled = false;
    config.auraHasDisableProcAttr = tc.hasAttr;
    EXPECT_EQ(ProcChanceTestHelper::ShouldSuppressCascadingProc(config), tc.hasAttr)
        << tc.name << " (spell " << tc.spellId << ") cascade suppression mismatch";
}
References ProcChanceTestHelper::CascadeProcConfig::auraHasDisableProcAttr, ProcChanceTestHelper::ShouldSuppressCascadingProc(), SPELL_ATTR3_INSTANT_TARGET_PROCS, ProcChanceTestHelper::CascadeProcConfig::triggeringSpellIsProcDisabled, SpellInfoBuilder::WithAttributesEx3(), and SpellInfoBuilder::WithId().