AzerothCore Doxygen
SpellProcCooldownTest.cpp File Reference
Unit tests for proc internal cooldown system.
#include "ProcChanceTestHelper.h"
#include "ProcEventInfoHelper.h"
#include "AuraStub.h"
#include "gtest/gtest.h"
Classes
class SpellProcCooldownTest
Functions
TEST_F (SpellProcCooldownTest, NotOnCooldown_Initially)
TEST_F (SpellProcCooldownTest, OnCooldown_AfterProc)
TEST_F (SpellProcCooldownTest, NotOnCooldown_AfterExpiry)
TEST_F (SpellProcCooldownTest, ExactCooldownBoundary)
TEST_F (SpellProcCooldownTest, ZeroCooldown_NeverBlocks)
TEST_F (SpellProcCooldownTest, CooldownCanBeReset)
TEST_F (SpellProcCooldownTest, CooldownCanBeExtended)
TEST_F (SpellProcCooldownTest, Scenario_LeaderOfThePack_6SecCooldown)
TEST_F (SpellProcCooldownTest, Scenario_WanderingPlague_1SecCooldown)
TEST_F (SpellProcCooldownTest, Scenario_MultipleProcsWithCooldown)
TEST_F (SpellProcCooldownTest, ProcTestScenario_CooldownBlocking)
Detailed Description
Unit tests for proc internal cooldown system.
Definition in file SpellProcCooldownTest.cpp.
Function Documentation
TEST_F() [1/11]
TEST_F (SpellProcCooldownTest , CooldownCanBeExtended)
{
    auto aura = AuraStubBuilder().WithId(12345).Build();
    // Apply 1 second cooldown
    ProcChanceTestHelper::ApplyProcCooldown(aura.get(), _now, 1000);
    // Extend to 5 seconds
    ProcChanceTestHelper::ApplyProcCooldown(aura.get(), _now, 5000);
    // Should still be on cooldown after 2 seconds
    EXPECT_TRUE(ProcChanceTestHelper::IsProcOnCooldown(aura.get(), _now + 2000ms));
}
References ProcChanceTestHelper::ApplyProcCooldown(), AuraStubBuilder::Build(), ProcChanceTestHelper::IsProcOnCooldown(), and AuraStubBuilder::WithId().
TEST_F() [2/11]
TEST_F (SpellProcCooldownTest , CooldownCanBeReset)
{
    auto aura = AuraStubBuilder().WithId(12345).Build();
    ProcChanceTestHelper::ApplyProcCooldown(aura.get(), _now, 5000);
    EXPECT_TRUE(ProcChanceTestHelper::IsProcOnCooldown(aura.get(), _now));
    aura->ResetProcCooldown();
    EXPECT_FALSE(ProcChanceTestHelper::IsProcOnCooldown(aura.get(), _now));
}
References ProcChanceTestHelper::ApplyProcCooldown(), AuraStubBuilder::Build(), ProcChanceTestHelper::IsProcOnCooldown(), and AuraStubBuilder::WithId().
TEST_F() [3/11]
TEST_F (SpellProcCooldownTest , ExactCooldownBoundary)
{
    auto aura = AuraStubBuilder().WithId(12345).Build();
    ProcChanceTestHelper::ApplyProcCooldown(aura.get(), _now, 1000);
    // At exactly cooldown time, should still be on cooldown (< not <=)
    EXPECT_TRUE(ProcChanceTestHelper::IsProcOnCooldown(aura.get(), _now + 999ms));
    // One millisecond after should be off cooldown
    EXPECT_FALSE(ProcChanceTestHelper::IsProcOnCooldown(aura.get(), _now + 1000ms));
}
References ProcChanceTestHelper::ApplyProcCooldown(), AuraStubBuilder::Build(), ProcChanceTestHelper::IsProcOnCooldown(), and AuraStubBuilder::WithId().
TEST_F() [4/11]
TEST_F (SpellProcCooldownTest , NotOnCooldown_AfterExpiry)
{
    auto aura = AuraStubBuilder().WithId(12345).Build();
    // Apply 1 second cooldown
    ProcChanceTestHelper::ApplyProcCooldown(aura.get(), _now, 1000);
    // Should not be on cooldown after 1 second
    EXPECT_FALSE(ProcChanceTestHelper::IsProcOnCooldown(aura.get(), _now + 1001ms));
}
References ProcChanceTestHelper::ApplyProcCooldown(), AuraStubBuilder::Build(), ProcChanceTestHelper::IsProcOnCooldown(), and AuraStubBuilder::WithId().
TEST_F() [5/11]
TEST_F (SpellProcCooldownTest , NotOnCooldown_Initially)
{
    auto aura = AuraStubBuilder().WithId(12345).Build();
    EXPECT_FALSE(ProcChanceTestHelper::IsProcOnCooldown(aura.get(), _now));
}
References AuraStubBuilder::Build(), ProcChanceTestHelper::IsProcOnCooldown(), and AuraStubBuilder::WithId().
TEST_F() [6/11]
TEST_F (SpellProcCooldownTest , OnCooldown_AfterProc)
{
    auto aura = AuraStubBuilder().WithId(12345).Build();
    // Apply 1 second cooldown
    ProcChanceTestHelper::ApplyProcCooldown(aura.get(), _now, 1000);
    // Should be on cooldown immediately after
    EXPECT_TRUE(ProcChanceTestHelper::IsProcOnCooldown(aura.get(), _now));
    EXPECT_TRUE(ProcChanceTestHelper::IsProcOnCooldown(aura.get(), _now + 500ms));
}
References ProcChanceTestHelper::ApplyProcCooldown(), AuraStubBuilder::Build(), ProcChanceTestHelper::IsProcOnCooldown(), and AuraStubBuilder::WithId().
TEST_F() [7/11]
TEST_F (SpellProcCooldownTest , ProcTestScenario_CooldownBlocking)
{
    ProcTestScenario scenario;
    scenario.WithAura(12345);
    auto procEntry = SpellProcEntryBuilder()
        .WithChance(100.0f)
        .WithCooldown(1000ms)
        .Build();
    // First proc should succeed
    EXPECT_TRUE(scenario.SimulateProc(procEntry));
    // Second proc immediately after should fail (on cooldown)
    EXPECT_FALSE(scenario.SimulateProc(procEntry));
    // Advance time past cooldown
    scenario.AdvanceTime(1100ms);
    // Third proc should succeed
    EXPECT_TRUE(scenario.SimulateProc(procEntry));
}
References ProcTestScenario::AdvanceTime(), SpellProcEntryBuilder::Build(), ProcTestScenario::SimulateProc(), ProcTestScenario::WithAura(), SpellProcEntryBuilder::WithChance(), and SpellProcEntryBuilder::WithCooldown().
TEST_F() [8/11]
TEST_F (SpellProcCooldownTest , Scenario_LeaderOfThePack_6SecCooldown)
{
    // Leader of the Pack has a 6 second internal cooldown
    auto aura = AuraStubBuilder().WithId(24932).Build();
    // First proc
    ProcChanceTestHelper::ApplyProcCooldown(aura.get(), _now, 6000);
    // Blocked at 3 seconds
    EXPECT_TRUE(ProcChanceTestHelper::IsProcOnCooldown(aura.get(), _now + 3000ms));
    // Blocked at 5.9 seconds
    EXPECT_TRUE(ProcChanceTestHelper::IsProcOnCooldown(aura.get(), _now + 5999ms));
    // Allowed at 6 seconds
    EXPECT_FALSE(ProcChanceTestHelper::IsProcOnCooldown(aura.get(), _now + 6000ms));
}
References ProcChanceTestHelper::ApplyProcCooldown(), AuraStubBuilder::Build(), ProcChanceTestHelper::IsProcOnCooldown(), and AuraStubBuilder::WithId().
TEST_F() [9/11]
TEST_F (SpellProcCooldownTest , Scenario_MultipleProcsWithCooldown)
{
    auto aura = AuraStubBuilder().WithId(12345).Build();
    auto time = _now;
    // First proc at t=0
    EXPECT_FALSE(ProcChanceTestHelper::IsProcOnCooldown(aura.get(), time));
    ProcChanceTestHelper::ApplyProcCooldown(aura.get(), time, 1000);
    // Second attempt at t=0.5 (blocked)
    time += 500ms;
    EXPECT_TRUE(ProcChanceTestHelper::IsProcOnCooldown(aura.get(), time));
    // Third attempt at t=1.0 (allowed)
    time += 500ms;
    EXPECT_FALSE(ProcChanceTestHelper::IsProcOnCooldown(aura.get(), time));
    ProcChanceTestHelper::ApplyProcCooldown(aura.get(), time, 1000);
    // Fourth attempt at t=1.5 (blocked)
    time += 500ms;
    EXPECT_TRUE(ProcChanceTestHelper::IsProcOnCooldown(aura.get(), time));
    // Fifth attempt at t=2.0 (allowed)
    time += 500ms;
    EXPECT_FALSE(ProcChanceTestHelper::IsProcOnCooldown(aura.get(), time));
}
References ProcChanceTestHelper::ApplyProcCooldown(), AuraStubBuilder::Build(), ProcChanceTestHelper::IsProcOnCooldown(), and AuraStubBuilder::WithId().
TEST_F() [10/11]
TEST_F (SpellProcCooldownTest , Scenario_WanderingPlague_1SecCooldown)
{
    // Wandering Plague has a 1 second internal cooldown
    auto aura = AuraStubBuilder().WithId(49217).Build();
    ProcChanceTestHelper::ApplyProcCooldown(aura.get(), _now, 1000);
    // Blocked at 0.5 seconds
    EXPECT_TRUE(ProcChanceTestHelper::IsProcOnCooldown(aura.get(), _now + 500ms));
    // Allowed at 1 second
    EXPECT_FALSE(ProcChanceTestHelper::IsProcOnCooldown(aura.get(), _now + 1000ms));
}
References ProcChanceTestHelper::ApplyProcCooldown(), AuraStubBuilder::Build(), ProcChanceTestHelper::IsProcOnCooldown(), and AuraStubBuilder::WithId().
TEST_F() [11/11]
TEST_F (SpellProcCooldownTest , ZeroCooldown_NeverBlocks)
{
    auto aura = AuraStubBuilder().WithId(12345).Build();
    // Zero cooldown should not apply any cooldown
    ProcChanceTestHelper::ApplyProcCooldown(aura.get(), _now, 0);
    EXPECT_FALSE(ProcChanceTestHelper::IsProcOnCooldown(aura.get(), _now));
}
References ProcChanceTestHelper::ApplyProcCooldown(), AuraStubBuilder::Build(), ProcChanceTestHelper::IsProcOnCooldown(), and AuraStubBuilder::WithId().