AzerothCore Doxygen
npc_pet_gen_argent_pony_bridle Struct Reference
Public Member Functions
npc_pet_gen_argent_pony_bridle (Creature *c)
void EnterEvadeMode (EvadeReason) override
void Reset () override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
uint32 GetData (uint32 param) const override
void DoAction (int32 param) override
bool OnGossipHello (Player *player, Creature *creature)
bool OnGossipSelect (Player *player, Creature *creature, uint32, uint32 action)
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportPlayer (Unit *unit, Position pos)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool IsUniqueTimedEventDone (uint32 id) const
void SetUniqueTimedEventDone (uint32 id)
void ResetUniqueTimedEvent (uint32 id)
void ClearUniqueTimedEventsDone ()
void ScheduleTimedEvent (Milliseconds timerMin, Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0ms, uint32 uniqueId=0)
void ScheduleTimedEvent (Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0ms, uint32 uniqueId=0)
void ScheduleUniqueTimedEvent (Milliseconds timer, std::function< void()> exec, uint32 uniqueId)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
void SetInvincibility (bool apply)
bool IsInvincible () const
void SetAutoAttackAllowed (bool allow)
bool IsAutoAttackAllowed () const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0ms)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void OnSpellCastFinished (SpellInfo const *, SpellFinishReason)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
int32 VisualizeBoundary (uint32 duration, Unit *owner=nullptr, bool fill=false, bool checkZ=false) const
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
virtual void DistancingStarted ()
virtual void DistancingEnded ()
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid const &, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage to any victim (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Private Attributes
bool _init
uint8 _state
int32 _mountTimer
bool _banners [MAX_RACES]
uint32 _lastAura
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from ScriptedAI
Creature * me
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
npc_pet_gen_argent_pony_bridle()
npc_pet_gen_argent_pony_bridle::npc_pet_gen_argent_pony_bridle (Creature * c) inline
                                                : ScriptedAI(c)
    {
        _state = ARGENT_PONY_STATE_NONE;
        _init = false;
        _mountTimer = 4000;
        _lastAura = 0;
        memset(_banners, 0, sizeof(_banners));
    }
References _banners, _init, _lastAura, _mountTimer, _state, and ARGENT_PONY_STATE_NONE.
Member Function Documentation
DoAction()
void npc_pet_gen_argent_pony_bridle::DoAction (int32 param) inline override virtual
Reimplemented from UnitAI.
    {
        if (param > 60000)
        {
            if (_lastAura)
                me->RemoveAurasDueToSpell(_lastAura);
            _lastAura = param;
            return;
        }
        _state = param;
    }
References _lastAura, _state, ScriptedAI::me, and Unit::RemoveAurasDueToSpell().
EnterEvadeMode()
void npc_pet_gen_argent_pony_bridle::EnterEvadeMode (EvadeReason) inline override virtual
Reimplemented from CreatureAI.
    {
        if (Unit* owner = me->GetCharmerOrOwner())
        {
            me->GetMotionMaster()->Clear(false);
            me->GetMotionMaster()->MoveFollow(owner, PET_FOLLOW_DIST, MINI_PET_FOLLOW_ANGLE, MOTION_SLOT_ACTIVE);
        }
    }
References MotionMaster::Clear(), Unit::GetCharmerOrOwner(), Unit::GetMotionMaster(), ScriptedAI::me, MINI_PET_FOLLOW_ANGLE, MOTION_SLOT_ACTIVE, MotionMaster::MoveFollow(), and PET_FOLLOW_DIST.
GetData()
uint32 npc_pet_gen_argent_pony_bridle::GetData (uint32 param) const inline override virtual
Reimplemented from UnitAI.
    {
        if (param == 0)
            return _state;
        return _banners[param];
    }
References _banners, and _state.
OnGossipHello()
bool npc_pet_gen_argent_pony_bridle::OnGossipHello (Player * player, Creature * creature) inline
    {
        if (player->GetGUID() != creature->GetOwnerGUID())
            return true;
        if (!creature->HasAura(player->GetTeamId(true) ? SPELL_AURA_TIRED_G : SPELL_AURA_TIRED_S))
        {
            uint8 _state = creature->AI()->GetData(0 /*GET_DATA_STATE*/);
            if (_state == ARGENT_PONY_STATE_ENCH || _state == ARGENT_PONY_STATE_VENDOR)
                AddGossipItemFor(player, GOSSIP_ICON_VENDOR, "Visit a trader.", GOSSIP_SENDER_MAIN, GOSSIP_ACTION_TRADE);
            if (_state == ARGENT_PONY_STATE_ENCH || _state == ARGENT_PONY_STATE_BANK)
                AddGossipItemFor(player, GOSSIP_ICON_INTERACT_1, "Visit a bank.", GOSSIP_SENDER_MAIN, GOSSIP_ACTION_BANK);
            if (_state == ARGENT_PONY_STATE_ENCH || _state == ARGENT_PONY_STATE_MAILBOX)
                AddGossipItemFor(player, GOSSIP_ICON_CHAT, "Visit a mailbox.", GOSSIP_SENDER_MAIN, GOSSIP_ACTION_MAILBOX);
        }
        for (uint8 i = RACE_HUMAN; i < MAX_RACES; ++i)
            if (creature->AI()->GetData(i) == uint32(true))
                AddGossipItemFor(player, GOSSIP_ICON_CHAT, argentBanners[i].text, GOSSIP_SENDER_MAIN, argentBanners[i].spell);
        SendGossipMenuFor(player, player->GetGossipTextId(creature), creature->GetGUID());
        return true;
    }
References _state, AddGossipItemFor(), Creature::AI(), ARGENT_PONY_STATE_BANK, ARGENT_PONY_STATE_ENCH, ARGENT_PONY_STATE_MAILBOX, ARGENT_PONY_STATE_VENDOR, argentBanners, UnitAI::GetData(), Player::GetGossipTextId(), Object::GetGUID(), Unit::GetOwnerGUID(), Player::GetTeamId(), GOSSIP_ACTION_BANK, GOSSIP_ACTION_MAILBOX, GOSSIP_ACTION_TRADE, GOSSIP_ICON_CHAT, GOSSIP_ICON_INTERACT_1, GOSSIP_ICON_VENDOR, GOSSIP_SENDER_MAIN, Unit::HasAura(), MAX_RACES, RACE_HUMAN, SendGossipMenuFor(), SPELL_AURA_TIRED_G, and SPELL_AURA_TIRED_S.
OnGossipSelect()
bool npc_pet_gen_argent_pony_bridle::OnGossipSelect (Player * player, Creature * creature, uint32 , uint32 action) inline
    {
        CloseGossipMenuFor(player);
        uint32 spellId = 0;
        switch (action)
        {
            case GOSSIP_ACTION_TRADE:
                creature->ReplaceAllNpcFlags(UNIT_NPC_FLAG_VENDOR);
                player->GetSession()->SendListInventory(creature->GetGUID());
                spellId = player->GetTeamId(true) ? SPELL_AURA_SHOP_G : SPELL_AURA_SHOP_S;
                creature->AI()->DoAction(ARGENT_PONY_STATE_VENDOR);
                break;
            case GOSSIP_ACTION_BANK:
                creature->ReplaceAllNpcFlags(UNIT_NPC_FLAG_BANKER);
                player->GetSession()->SendShowBank(player->GetGUID());
                spellId = player->GetTeamId(true) ? SPELL_AURA_BANK_G : SPELL_AURA_BANK_S;
                creature->AI()->DoAction(ARGENT_PONY_STATE_BANK);
                break;
            case GOSSIP_ACTION_MAILBOX:
                {
                    creature->ReplaceAllNpcFlags(UNIT_NPC_FLAG_GOSSIP | UNIT_NPC_FLAG_MAILBOX);
                    player->GetSession()->SendShowMailBox(creature->GetGUID());
                    spellId = player->GetTeamId(true) ? SPELL_AURA_POSTMAN_G : SPELL_AURA_POSTMAN_S;
                    creature->AI()->DoAction(ARGENT_PONY_STATE_MAILBOX);
                    break;
                }
            default:
                if (action > 60000)
                {
                    creature->AI()->DoAction(action);
                    creature->CastSpell(creature, action, true);
                }
                return true;
        }
        if (spellId && !creature->HasAura(spellId))
        {
            creature->CastSpell(creature, spellId, true);
            player->AddSpellCooldown(spellId, 0, 3 * MINUTE * IN_MILLISECONDS);
            player->AddSpellCooldown(player->GetTeamId(true) ? SPELL_AURA_TIRED_G : SPELL_AURA_TIRED_S, 0, 3 * MINUTE * IN_MILLISECONDS + 4 * HOUR * IN_MILLISECONDS);
            creature->DespawnOrUnsummon(180s);
        }
        return true;
    }
References Player::AddSpellCooldown(), Creature::AI(), ARGENT_PONY_STATE_BANK, ARGENT_PONY_STATE_MAILBOX, ARGENT_PONY_STATE_VENDOR, Unit::CastSpell(), CloseGossipMenuFor(), Creature::DespawnOrUnsummon(), UnitAI::DoAction(), Object::GetGUID(), Player::GetSession(), Player::GetTeamId(), GOSSIP_ACTION_BANK, GOSSIP_ACTION_MAILBOX, GOSSIP_ACTION_TRADE, Unit::HasAura(), HOUR, IN_MILLISECONDS, MINUTE, Unit::ReplaceAllNpcFlags(), WorldSession::SendListInventory(), WorldSession::SendShowBank(), WorldSession::SendShowMailBox(), SPELL_AURA_BANK_G, SPELL_AURA_BANK_S, SPELL_AURA_POSTMAN_G, SPELL_AURA_POSTMAN_S, SPELL_AURA_SHOP_G, SPELL_AURA_SHOP_S, SPELL_AURA_TIRED_G, SPELL_AURA_TIRED_S, UNIT_NPC_FLAG_BANKER, UNIT_NPC_FLAG_GOSSIP, UNIT_NPC_FLAG_MAILBOX, and UNIT_NPC_FLAG_VENDOR.
Reset()
void npc_pet_gen_argent_pony_bridle::Reset () inline override virtual
Reimplemented from UnitAI.
    {
        if (_init)
            return;
        _init = true;
        uint32 duration = 0;
        uint32 aura = 0;
        me->ReplaceAllNpcFlags(UNIT_NPC_FLAG_NONE);
        if (Unit* owner = me->GetCharmerOrOwner())
            if (Player* player = owner->ToPlayer())
                if (player->HasAchieved(ACHIEVEMENT_PONY_UP))
                {
                    _state = ARGENT_PONY_STATE_ENCH;
                    aura = (player->GetTeamId(true) == TEAM_ALLIANCE ? SPELL_AURA_TIRED_S : SPELL_AURA_TIRED_G);
                    duration = player->GetSpellCooldownDelay(aura);
                    me->ReplaceAllNpcFlags(UNIT_NPC_FLAG_GOSSIP);
                    for (uint8 i = 0; i < 3; ++i)
                    {
                        if (player->GetTeamId(true) == TEAM_ALLIANCE)
{
                            if (uint32 cooldown = player->GetSpellCooldownDelay(SPELL_AURA_POSTMAN_S + i))
{
                                duration = cooldown;
                                aura = SPELL_AURA_POSTMAN_S + i;
                                _state = argentPonyService[TEAM_ALLIANCE][i];
                                me->ToTempSummon()->UnSummon(Milliseconds(duration));
                                break;
                            }
                        }
                        else
{
                            if (uint32 cooldown = player->GetSpellCooldownDelay(SPELL_AURA_BANK_G + i))
{
                                duration = cooldown * IN_MILLISECONDS;
                                aura = SPELL_AURA_BANK_G + i;
                                _state = argentPonyService[TEAM_HORDE][i];
                                me->ToTempSummon()->UnSummon(Milliseconds(duration));
                                break;
                            }
                        }
                    }
                    // Generate Banners
                    uint32 mask = player->GetTeamId(true) ? RACEMASK_HORDE : RACEMASK_ALLIANCE;
                    for (uint8 i = 1; i < MAX_RACES; ++i)
                        if (mask & (1 << (i - 1)) && player->HasAchieved(argentBanners[i].achievement))
                            _banners[i] = true;
                }
        if (duration && aura)
        {
            if (Aura* aur = me->AddAura(aura, me))
                aur->SetDuration(duration);
        }
    }
References _banners, _init, _state, ACHIEVEMENT_PONY_UP, Unit::AddAura(), ARGENT_PONY_STATE_ENCH, argentBanners, argentPonyService, Unit::GetCharmerOrOwner(), IN_MILLISECONDS, MAX_RACES, ScriptedAI::me, RACEMASK_ALLIANCE, RACEMASK_HORDE, Unit::ReplaceAllNpcFlags(), SPELL_AURA_BANK_G, SPELL_AURA_POSTMAN_S, SPELL_AURA_TIRED_G, SPELL_AURA_TIRED_S, TEAM_ALLIANCE, TEAM_HORDE, Object::ToPlayer(), Unit::ToTempSummon(), UNIT_NPC_FLAG_GOSSIP, UNIT_NPC_FLAG_NONE, and TempSummon::UnSummon().
UpdateAI()
void npc_pet_gen_argent_pony_bridle::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Implements UnitAI.
    {
        _mountTimer += diff;
        if (_mountTimer > 5000)
        {
            _mountTimer = 0;
            if (_state == ARGENT_PONY_STATE_NONE)
                me->ReplaceAllNpcFlags(UNIT_NPC_FLAG_NONE);
            else if (Unit* owner = me->GetCharmerOrOwner())
            {
                if (owner->IsMounted() && !me->IsMounted())
                    me->CastSpell(me, SPELL_PONY_MOUNT, false);
                else if (!owner->IsMounted() && me->IsMounted())
                    me->RemoveAurasDueToSpell(SPELL_PONY_MOUNT);
            }
        }
    }
References _mountTimer, _state, ARGENT_PONY_STATE_NONE, Unit::CastSpell(), Unit::GetCharmerOrOwner(), Unit::IsMounted(), ScriptedAI::me, Unit::RemoveAurasDueToSpell(), Unit::ReplaceAllNpcFlags(), SPELL_PONY_MOUNT, and UNIT_NPC_FLAG_NONE.
Member Data Documentation
_banners
bool npc_pet_gen_argent_pony_bridle::_banners[MAX_RACES] private
Referenced by GetData(), npc_pet_gen_argent_pony_bridle(), and Reset().
_init
bool npc_pet_gen_argent_pony_bridle::_init private
Referenced by npc_pet_gen_argent_pony_bridle(), and Reset().
_lastAura
uint32 npc_pet_gen_argent_pony_bridle::_lastAura private
Referenced by DoAction(), and npc_pet_gen_argent_pony_bridle().
_mountTimer
int32 npc_pet_gen_argent_pony_bridle::_mountTimer private
Referenced by npc_pet_gen_argent_pony_bridle(), and UpdateAI().
_state
uint8 npc_pet_gen_argent_pony_bridle::_state private
Referenced by DoAction(), GetData(), npc_pet_gen_argent_pony_bridle(), OnGossipHello(), Reset(), and UpdateAI().
The documentation for this struct was generated from the following file:
azerothcore-wotlk/src/server/scripts/Pet/pet_generic.cpp