AzerothCore Doxygen
boss_felmyst Struct Reference
Public Member Functions
boss_felmyst (Creature *creature)
void InitializeAI () override
void Reset () override
void JustEngagedWith (Unit *who) override
Called for reaction when initially engaged.
void KilledUnit (Unit *victim) override
void SpellHitTarget (Unit *target, const SpellInfo *spell) override
void JustDied (Unit *killer) override
void ScheduleGroundAbilities ()
void MovementInform (uint32 type, uint32 point) override
void StartIntro ()
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
Public Member Functions inherited from BossAI
BossAI (Creature *creature, uint32 bossId)
~BossAI () override
bool CanRespawn () override
void DamageTaken (Unit *attacker, uint32 &damage, DamageEffectType damagetype, SpellSchoolMask damageSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void JustSummoned (Creature *summon) override
void SummonedCreatureDespawn (Creature *summon) override
void SummonedCreatureDespawnAll () override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void ScheduleHealthCheckEvent (uint32 healthPct, std::function< void()> exec)
Executes a function once the creature reaches the defined health point percent.
void ScheduleHealthCheckEvent (std::initializer_list< uint8 > healthPct, std::function< void()> exec)
void ScheduleEnrageTimer (uint32 spellId, Milliseconds timer, uint8 textId=0)
virtual void ExecuteEvent (uint32)
virtual void ScheduleTasks ()
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER) override
void JustDied (Unit *) override
void JustReachedHome () override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportPlayer (Unit *unit, Position pos)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool IsUniqueTimedEventDone (uint32 id) const
void SetUniqueTimedEventDone (uint32 id)
void ResetUniqueTimedEvent (uint32 id)
void ClearUniqueTimedEventsDone ()
void ScheduleTimedEvent (Milliseconds timerMin, Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleTimedEvent (Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleUniqueTimedEvent (Milliseconds timer, std::function< void()> exec, uint32 uniqueId)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
void SetInvincibility (bool apply)
bool IsInvincible () const
void SetAutoAttackAllowed (bool allow)
bool IsAutoAttackAllowed () const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureEvade (Creature *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage to any victim (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Private Attributes
uint8 _currentLane = 0
uint8 _strafeCount = 0
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from BossAI
float callForHelpRange
InstanceScript *const instance
Public Attributes inherited from ScriptedAI
Creature * me
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from BossAI
void _Reset ()
void _JustEngagedWith ()
void _JustDied ()
void _JustReachedHome ()
void _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
void TeleportCheaters ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from BossAI
SummonList summons
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
boss_felmyst()
boss_felmyst::boss_felmyst (Creature * creature) inline
: BossAI(creature, DATA_FELMYST), _currentLane(0), _strafeCount(0) { }
Member Function Documentation
InitializeAI()
void boss_felmyst::InitializeAI () inline override virtual
Reimplemented from UnitAI.
    {
        me->SetReactState(REACT_PASSIVE);
        if (instance->GetBossState(DATA_FELMYST) == TO_BE_DECIDED)
        {
            me->SetStandState(UNIT_STAND_STATE_SLEEP);
            me->SetImmuneToPC(true);
            StartIntro();
        }
        else
        {
            me->SetCanFly(true);
            me->SetDisableGravity(true);
            me->SendMovementFlagUpdate();
            me->GetMotionMaster()->MovePath(me->GetEntry() * 10, true);
        }
    }
References DATA_FELMYST, InstanceScript::GetBossState(), Object::GetEntry(), Unit::GetMotionMaster(), BossAI::instance, ScriptedAI::me, MotionMaster::MovePath(), REACT_PASSIVE, Unit::SendMovementFlagUpdate(), Creature::SetCanFly(), Creature::SetDisableGravity(), Unit::SetImmuneToPC(), Creature::SetReactState(), Unit::SetStandState(), StartIntro(), TO_BE_DECIDED, and UNIT_STAND_STATE_SLEEP.
JustDied()
void boss_felmyst::JustDied (Unit * killer) inline override virtual
Reimplemented from CreatureAI.
    {
        BossAI::JustDied(killer);
        me->m_Events.KillAllEvents(false);
        Talk(YELL_DEATH);
        instance->DoRemoveAurasDueToSpellOnPlayers(SPELL_FOG_OF_CORRUPTION_CHARM);
        // Summon Kalecgos (human form of kalecgos fight)
        if (Creature* kalec = me->SummonCreature(NPC_KALECGOS_FELMYST, 1573.1461f, 755.20245f, 99.524956f, 3.595378f))
            kalec->GetMotionMaster()->MovePoint(POINT_KALECGOS, 1474.2347f, 624.0703f, 29.32589f, false, true);
    }
References InstanceScript::DoRemoveAurasDueToSpellOnPlayers(), BossAI::instance, BossAI::JustDied(), EventProcessor::KillAllEvents(), WorldObject::m_Events, ScriptedAI::me, NPC_KALECGOS_FELMYST, POINT_KALECGOS, SPELL_FOG_OF_CORRUPTION_CHARM, WorldObject::SummonCreature(), and YELL_DEATH.
JustEngagedWith()
void boss_felmyst::JustEngagedWith (Unit *) inline override virtual
Called for reaction when initially engaged.
Reimplemented from CreatureAI.
    {
        BossAI::JustEngagedWith(who);
        ScheduleEnrageTimer(SPELL_BERSERK, 10min, YELL_BERSERK);
        me->GetMotionMaster()->Clear();
        Position landPos = who->GetPosition();
        me->m_Events.AddEventAtOffset([&, landPos] {
            me->GetMotionMaster()->MoveLand(POINT_GROUND, landPos);
        }, 1s);
    }
References EventProcessor::AddEventAtOffset(), MotionMaster::Clear(), Unit::GetMotionMaster(), Position::GetPosition(), BossAI::JustEngagedWith(), landPos, WorldObject::m_Events, ScriptedAI::me, POINT_GROUND, BossAI::ScheduleEnrageTimer(), SPELL_BERSERK, and YELL_BERSERK.
KilledUnit()
void boss_felmyst::KilledUnit (Unit * victim) inline override virtual
Reimplemented from CreatureAI.
    {
        if (victim->IsPlayer() && roll_chance_i(50))
            Talk(YELL_KILL);
    }
References Object::IsPlayer(), roll_chance_i(), and YELL_KILL.
MovementInform()
void boss_felmyst::MovementInform (uint32 type, uint32 point) inline override virtual
Reimplemented from CreatureAI.
    {
        if (type != EFFECT_MOTION_TYPE && type != POINT_MOTION_TYPE)
            return;
        switch (point)
        {
            case POINT_GROUND:
                if (!me->HasAura(SPELL_NOXIOUS_FUMES))
                    DoCastSelf(SPELL_NOXIOUS_FUMES, true);
                me->GetMotionMaster()->MoveIdle();
                me->HandleEmoteCommand(EMOTE_ONESHOT_LAND);
                me->SetCanFly(false);
                me->SetDisableGravity(false);
                me->SendMovementFlagUpdate();
                SetInvincibility(false);
                me->m_Events.AddEventAtOffset([&] {
                    me->SetReactState(REACT_AGGRESSIVE);
                    if (me->GetVictim())
                        me->SetTarget(me->GetVictim()->GetGUID());
                    me->ResumeChasingVictim();
                    me->SetCombatMovement(true);
                }, 5s);
                ScheduleGroundAbilities();
                break;
            case POINT_TAKEOFF:
                me->m_Events.AddEventAtOffset([&] {
                    me->CastCustomSpell(SPELL_SUMMON_DEMONIC_VAPOR, SPELLVALUE_MAX_TARGETS, 1, me, true);
                }, 5s);
                me->m_Events.AddEventAtOffset([&] {
                    me->CastCustomSpell(SPELL_SUMMON_DEMONIC_VAPOR, SPELLVALUE_MAX_TARGETS, 1, me, true);
                }, 17s);
                scheduler.Schedule(27s, GROUP_BREATH, [this](TaskContext)
                {
                    if (me->GetDistance(LeftSide) < me->GetDistance(RightSide))
                        me->GetMotionMaster()->MovePoint(POINT_AIR_UP, LeftSide);
                    else
                        me->GetMotionMaster()->MovePoint(POINT_AIR_UP, RightSide);
                });
                break;
            case POINT_AIR_UP:
                me->m_Events.AddEventAtOffset([&] {
                    bool isRightSide = me->FindNearestCreature(NPC_WORLD_TRIGGER_RIGHT, 30.0f);
                    if (_strafeCount >= 3)
                    {
                        _strafeCount = 0;
                        me->GetMotionMaster()->MoveLand(POINT_GROUND, isRightSide ? LandingRightPos : LandingLeftPos);
                        return;
                    }
                    ++_strafeCount;
                    _currentLane = urand(0, 2);
                    if (isRightSide)
                        me->GetMotionMaster()->MovePoint(POINT_LANE, RightSideLanes[_currentLane], false);
                    else
                        me->GetMotionMaster()->MovePoint(POINT_LANE, LeftSideLanes[_currentLane], false);
                }, 5s);
                break;
            case POINT_LANE:
                Talk(EMOTE_BREATH);
                me->m_Events.AddEventAtOffset([&] {
                    for (uint8 i = 0; i < 16; ++i)
                        me->m_Events.AddEvent(new CorruptTriggers(me, _currentLane), me->m_Events.CalculateTime(i*250));
                }, 5s);
                me->m_Events.AddEventAtOffset([&] {
                    DoCastSelf(SPELL_FELMYST_SPEED_BURST, true);
                    if (me->FindNearestCreature(NPC_WORLD_TRIGGER_RIGHT, 30.0f))
                        me->GetMotionMaster()->MovePoint(POINT_AIR_BREATH_END, LeftSideLanes[_currentLane], false);
                    else
                        me->GetMotionMaster()->MovePoint(POINT_AIR_BREATH_END, RightSideLanes[_currentLane], false);
                }, 5s);
                break;
            case POINT_AIR_BREATH_END:
                me->RemoveAurasDueToSpell(SPELL_FELMYST_SPEED_BURST);
                me->m_Events.AddEventAtOffset([&] {
                    if (me->FindNearestCreature(NPC_WORLD_TRIGGER_RIGHT, 30.0f))
                        me->GetMotionMaster()->MovePoint(POINT_AIR_UP, RightSide, false);
                    else
                        me->GetMotionMaster()->MovePoint(POINT_AIR_UP, LeftSide, false);
                }, 2s);
                break;
        }
    }
References _currentLane, _strafeCount, EventProcessor::AddEvent(), EventProcessor::AddEventAtOffset(), EventProcessor::CalculateTime(), Unit::CastCustomSpell(), UnitAI::DoCastSelf(), EFFECT_MOTION_TYPE, EMOTE_BREATH, EMOTE_ONESHOT_LAND, WorldObject::FindNearestCreature(), WorldObject::GetDistance(), Object::GetGUID(), Unit::GetMotionMaster(), Unit::GetVictim(), GROUP_BREATH, Unit::HandleEmoteCommand(), Unit::HasAura(), LandingLeftPos, LandingRightPos, LeftSide, LeftSideLanes, WorldObject::m_Events, ScriptedAI::me, MotionMaster::MoveIdle(), MotionMaster::MoveLand(), MotionMaster::MovePoint(), NPC_WORLD_TRIGGER_RIGHT, POINT_AIR_BREATH_END, POINT_AIR_UP, POINT_GROUND, POINT_LANE, POINT_MOTION_TYPE, POINT_TAKEOFF, REACT_AGGRESSIVE, Unit::RemoveAurasDueToSpell(), Creature::ResumeChasingVictim(), RightSide, RightSideLanes, TaskScheduler::Schedule(), ScheduleGroundAbilities(), CreatureAI::scheduler, Unit::SendMovementFlagUpdate(), Creature::SetCanFly(), Creature::SetCombatMovement(), Creature::SetDisableGravity(), ScriptedAI::SetInvincibility(), Creature::SetReactState(), Creature::SetTarget(), SPELL_FELMYST_SPEED_BURST, SPELL_NOXIOUS_FUMES, SPELL_SUMMON_DEMONIC_VAPOR, SPELLVALUE_MAX_TARGETS, and urand().
Reset()
void boss_felmyst::Reset () inline override virtual
Reimplemented from UnitAI.
    {
        BossAI::Reset();
        instance->DoRemoveAurasDueToSpellOnPlayers(SPELL_FOG_OF_CORRUPTION_CHARM);
        _currentLane = 0;
        _strafeCount = 0;
        me->SetCombatMovement(false);
    }
References _currentLane, _strafeCount, InstanceScript::DoRemoveAurasDueToSpellOnPlayers(), BossAI::instance, ScriptedAI::me, BossAI::Reset(), Creature::SetCombatMovement(), and SPELL_FOG_OF_CORRUPTION_CHARM.
ScheduleGroundAbilities()
void boss_felmyst::ScheduleGroundAbilities () inline
    {
        ScheduleTimedEvent(7500ms, [&] {
            DoCastVictim(SPELL_CLEAVE);
        }, 7500ms);
        ScheduleTimedEvent(13s, 30s, [&] {
            if (scheduler.GetNextGroupOccurrence(GROUP_TAKEOFF) > 2s)
            {
                Talk(YELL_BREATH);
                DoCastVictim(SPELL_CORROSION);
            }
        }, 30s, 39s);
        ScheduleTimedEvent(18s, 43s, [&] {
            if (scheduler.GetNextGroupOccurrence(GROUP_TAKEOFF) > 2s)
                DoCastSelf(SPELL_GAS_NOVA);
        }, 18s, 43s);
        ScheduleTimedEvent(26s, 53s, [&] {
            if (scheduler.GetNextGroupOccurrence(GROUP_TAKEOFF) > 9s)
                DoCastRandomTarget(SPELL_ENCAPSULATE_CHANNEL, 0, 50.0f);
        }, 26s, 53s);
        scheduler.Schedule(1min, GROUP_TAKEOFF, [&](TaskContext)
        {
            Talk(YELL_TAKEOFF);
            scheduler.CancelAll();
            me->SetReactState(REACT_PASSIVE);
            me->SetTarget();
            me->AttackStop();
            me->SetCombatMovement(false);
            me->GetMotionMaster()->Clear();
            me->GetMotionMaster()->MoveIdle();
            me->SetCanFly(true);
            me->SetDisableGravity(true);
            me->SendMovementFlagUpdate();
            SetInvincibility(true);
            me->HandleEmoteCommand(EMOTE_ONESHOT_LIFTOFF);
            me->GetMotionMaster()->MovePoint(POINT_TAKEOFF, me->GetPositionX(), me->GetPositionY(), me->GetPositionZ() + 20.0f);
        });
    }
References Unit::AttackStop(), TaskScheduler::CancelAll(), MotionMaster::Clear(), UnitAI::DoCastRandomTarget(), UnitAI::DoCastSelf(), UnitAI::DoCastVictim(), EMOTE_ONESHOT_LIFTOFF, Unit::GetMotionMaster(), TaskScheduler::GetNextGroupOccurrence(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), GROUP_TAKEOFF, Unit::HandleEmoteCommand(), ScriptedAI::me, MotionMaster::MoveIdle(), MotionMaster::MovePoint(), POINT_TAKEOFF, REACT_PASSIVE, TaskScheduler::Schedule(), CreatureAI::scheduler, ScriptedAI::ScheduleTimedEvent(), Unit::SendMovementFlagUpdate(), Creature::SetCanFly(), Creature::SetCombatMovement(), Creature::SetDisableGravity(), ScriptedAI::SetInvincibility(), Creature::SetReactState(), Creature::SetTarget(), SPELL_CLEAVE, SPELL_ENCAPSULATE_CHANNEL, SPELL_GAS_NOVA, and YELL_TAKEOFF.
Referenced by MovementInform().
SpellHitTarget()
void boss_felmyst::SpellHitTarget (Unit * target, const SpellInfo * spell) inline override virtual
Reimplemented from CreatureAI.
    {
        if (spell->Id == SPELL_STRAFE_TOP || spell->Id == SPELL_STRAFE_MIDDLE || spell->Id == SPELL_STRAFE_BOTTOM)
            target->CastSpell(target, SPELL_FOG_OF_CORRUPTION, true);
    }
References Unit::CastSpell(), SpellInfo::Id, SPELL_FOG_OF_CORRUPTION, SPELL_STRAFE_BOTTOM, SPELL_STRAFE_MIDDLE, and SPELL_STRAFE_TOP.
StartIntro()
void boss_felmyst::StartIntro () inline
    {
        scheduler.Schedule(3s, GROUP_START_INTRO, [this](TaskContext /*context*/)
        {
            me->SetStandState(UNIT_STAND_STATE_STAND);
            me->m_Events.AddEventAtOffset([&] {
                Talk(YELL_BIRTH);
                me->SetCanFly(true);
                me->SetDisableGravity(true);
                me->SendMovementFlagUpdate();
                me->HandleEmoteCommand(EMOTE_ONESHOT_LIFTOFF);
            }, 7s);
            me->m_Events.AddEventAtOffset([&] {
                me->SetImmuneToPC(false);
                me->GetMotionMaster()->MovePath(me->GetEntry() * 10, true);
            }, 8500ms);
        });
    }
References EventProcessor::AddEventAtOffset(), EMOTE_ONESHOT_LIFTOFF, Object::GetEntry(), Unit::GetMotionMaster(), GROUP_START_INTRO, Unit::HandleEmoteCommand(), WorldObject::m_Events, ScriptedAI::me, MotionMaster::MovePath(), TaskScheduler::Schedule(), CreatureAI::scheduler, Unit::SendMovementFlagUpdate(), Creature::SetCanFly(), Creature::SetDisableGravity(), Unit::SetImmuneToPC(), Unit::SetStandState(), UNIT_STAND_STATE_STAND, and YELL_BIRTH.
Referenced by InitializeAI().
UpdateAI()
void boss_felmyst::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Implements UnitAI.
    {
        scheduler.Update(diff);
        if (!UpdateVictim())
            return;
        if (!me->HasUnitMovementFlag(MOVEMENTFLAG_DISABLE_GRAVITY))
            DoMeleeAttackIfReady();
    }
References UnitAI::DoMeleeAttackIfReady(), Unit::HasUnitMovementFlag(), ScriptedAI::me, MOVEMENTFLAG_DISABLE_GRAVITY, CreatureAI::scheduler, TaskScheduler::Update(), and CreatureAI::UpdateVictim().
Member Data Documentation
_currentLane
uint8 boss_felmyst::_currentLane = 0 private
Referenced by MovementInform(), and Reset().
_strafeCount
uint8 boss_felmyst::_strafeCount = 0 private
Referenced by MovementInform(), and Reset().
The documentation for this struct was generated from the following file:
azerothcore-wotlk/src/server/scripts/EasternKingdoms/SunwellPlateau/boss_felmyst.cpp