AzerothCore Doxygen
BattlefieldMgr Class Reference
#include "BattlefieldMgr.h"
Public Types
using BattlefieldSet = std::vector< Battlefield * >
using BattlefieldMap = std::map< uint32, Battlefield * >
Public Member Functions
BattlefieldMgr ()
~BattlefieldMgr ()
void InitBattlefield ()
void HandlePlayerEnterZone (Player *player, uint32 areaflag)
void HandlePlayerLeaveZone (Player *player, uint32 areaflag)
void HandlePlayerResurrects (Player *player, uint32 areaflag)
Battlefield * GetBattlefieldToZoneId (uint32 zoneId)
Battlefield * GetBattlefieldByBattleId (uint32 battleId)
ZoneScript * GetZoneScript (uint32 zoneId)
void AddZone (uint32 zoneId, Battlefield *handle)
void Update (uint32 diff)
void HandleGossipOption (Player *player, ObjectGuid guid, uint32 gossipId)
bool CanTalkTo (Player *player, Creature *creature, GossipMenuItems gso)
void HandleDropFlag (Player *player, uint32 spellId)
Static Public Member Functions
static BattlefieldMgr * instance ()
Private Attributes
BattlefieldSet _battlefieldSet
BattlefieldMap _battlefieldMap
uint32 _updateTimer
Detailed Description
Member Typedef Documentation
BattlefieldMap
using BattlefieldMgr::BattlefieldMap = std::map<uint32 , Battlefield*>
BattlefieldSet
using BattlefieldMgr::BattlefieldSet = std::vector<Battlefield*>
Constructor & Destructor Documentation
BattlefieldMgr()
BattlefieldMgr::BattlefieldMgr ()
                               : _updateTimer(0)
{
}
~BattlefieldMgr()
BattlefieldMgr::~BattlefieldMgr ()
{
    for (Battlefield* bf : _battlefieldSet)
        delete bf;
}
References _battlefieldSet.
Member Function Documentation
AddZone()
void BattlefieldMgr::AddZone (uint32 zoneId, Battlefield * handle)
{
    _battlefieldMap[zoneId] = handle;
}
References _battlefieldMap.
CanTalkTo()
bool BattlefieldMgr::CanTalkTo (Player * player, Creature * creature, GossipMenuItems gso)
GetBattlefieldByBattleId()
Battlefield * BattlefieldMgr::GetBattlefieldByBattleId (uint32 battleId)
{
    for (Battlefield* bf : _battlefieldSet)
        if (bf->GetBattleId() == battleId)
            return bf;
    return nullptr;
}
References _battlefieldSet.
GetBattlefieldToZoneId()
Battlefield * BattlefieldMgr::GetBattlefieldToZoneId (uint32 zoneId)
{
    auto itr = _battlefieldMap.find(zoneId);
    if (itr == _battlefieldMap.end())
        return nullptr;
    if (!itr->second->IsEnabled())
        return nullptr;
    return itr->second;
}
References _battlefieldMap.
GetZoneScript()
ZoneScript * BattlefieldMgr::GetZoneScript (uint32 zoneId)
{
    auto itr = _battlefieldMap.find(zoneId);
    if (itr != _battlefieldMap.end())
        return itr->second;
    return nullptr;
}
References _battlefieldMap.
HandleDropFlag()
void BattlefieldMgr::HandleDropFlag (Player * player, uint32 spellId)
HandleGossipOption()
void BattlefieldMgr::HandleGossipOption (Player * player, ObjectGuid guid, uint32 gossipId)
HandlePlayerEnterZone()
void BattlefieldMgr::HandlePlayerEnterZone (Player * player, uint32 areaflag)
{
    auto itr = _battlefieldMap.find(zoneId);
    if (itr == _battlefieldMap.end())
        return;
    if (itr->second->HasPlayer(player) || !itr->second->IsEnabled())
        return;
    itr->second->HandlePlayerEnterZone(player, zoneId);
    LOG_DEBUG("bg.battlefield", "Player {} entered outdoorpvp id {}", player->GetGUID().ToString(), itr->second->GetTypeId());
}
References _battlefieldMap, Object::GetGUID(), Battlefield::HandlePlayerEnterZone(), LOG_DEBUG, and ObjectGuid::ToString().
HandlePlayerLeaveZone()
void BattlefieldMgr::HandlePlayerLeaveZone (Player * player, uint32 areaflag)
{
    auto itr = _battlefieldMap.find(zoneId);
    if (itr == _battlefieldMap.end())
        return;
    // teleport: remove once in removefromworld, once in updatezone
    if (!itr->second->HasPlayer(player))
        return;
    sScriptMgr->OnBattlefieldPlayerLeaveZone(itr->second, player);
    itr->second->HandlePlayerLeaveZone(player, zoneId);
    LOG_DEBUG("bg.battlefield", "Player {} left outdoorpvp id {}", player->GetGUID().ToString(), itr->second->GetTypeId());
}
References _battlefieldMap, Object::GetGUID(), LOG_DEBUG, sScriptMgr, and ObjectGuid::ToString().
HandlePlayerResurrects()
void BattlefieldMgr::HandlePlayerResurrects (Player * player, uint32 areaflag)
InitBattlefield()
void BattlefieldMgr::InitBattlefield ()
{
    if (sWorld->getIntConfig(CONFIG_WINTERGRASP_ENABLE) == 2)
    {
        LOG_INFO("server.loading", "Battlefield: Wintergrasp is disabled.");
        LOG_INFO("server.loading", " ");
        return;
    }
    Battlefield* bf = new BattlefieldWG;
    // respawn, init variables
    if (!bf->SetupBattlefield())
    {
        LOG_ERROR("server.loading", "Battlefield: Wintergrasp init failed.");
        LOG_INFO("server.loading", " ");
        delete bf;
    }
    else
    {
        _battlefieldSet.push_back(bf);
        LOG_INFO("server.loading", "Battlefield: Wintergrasp successfully initiated.");
        LOG_INFO("server.loading", " ");
    }
}
References _battlefieldSet, CONFIG_WINTERGRASP_ENABLE, LOG_ERROR, LOG_INFO, Battlefield::SetupBattlefield(), and sWorld.
instance()
BattlefieldMgr * BattlefieldMgr::instance () static
{
    static BattlefieldMgr instance;
    return &instance;
}
References instance().
Referenced by instance().
Update()
void BattlefieldMgr::Update (uint32 diff)
{
    _updateTimer += diff;
    if (_updateTimer > BATTLEFIELD_OBJECTIVE_UPDATE_INTERVAL)
    {
        for (Battlefield* bf : _battlefieldSet)
            bf->Update(_updateTimer);
        _updateTimer = 0;
    }
}
References _battlefieldSet, _updateTimer, BATTLEFIELD_OBJECTIVE_UPDATE_INTERVAL, and Battlefield::Update().
Member Data Documentation
_battlefieldMap
BattlefieldMap BattlefieldMgr::_battlefieldMap private
Referenced by AddZone(), GetBattlefieldToZoneId(), GetZoneScript(), HandlePlayerEnterZone(), and HandlePlayerLeaveZone().
_battlefieldSet
BattlefieldSet BattlefieldMgr::_battlefieldSet private
Referenced by GetBattlefieldByBattleId(), InitBattlefield(), Update(), and ~BattlefieldMgr().
_updateTimer
uint32 BattlefieldMgr::_updateTimer private
Referenced by Update().
The documentation for this class was generated from the following files:
azerothcore-wotlk/src/server/game/Battlefield/BattlefieldMgr.h
azerothcore-wotlk/src/server/game/Battlefield/BattlefieldMgr.cpp