AzerothCore Doxygen
npc_thassarian2::npc_thassarian2AI Struct Reference
Public Member Functions
npc_thassarian2AI (Creature *creature)
void Initialize ()
void Reset () override
void SetData (uint32, uint32 data) override
void MovementInform (uint32 type, uint32 param) override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void JustDied (Unit *) override
void Cleanup ()
void sGossipHello (Player *) override
void sGossipSelect (Player *player, uint32, uint32 action) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportPlayer (Unit *unit, Position pos)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool IsUniqueTimedEventDone (uint32 id) const
void SetUniqueTimedEventDone (uint32 id)
void ResetUniqueTimedEvent (uint32 id)
void ClearUniqueTimedEventsDone ()
void ScheduleTimedEvent (Milliseconds timerMin, Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleTimedEvent (Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleUniqueTimedEvent (Milliseconds timer, std::function< void()> exec, uint32 uniqueId)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
void SetInvincibility (bool apply)
bool IsInvincible () const
void SetAutoAttackAllowed (bool allow)
bool IsAutoAttackAllowed () const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage to any victim (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Private Attributes
EventMap _events
ObjectGuid _playerGUID
ObjectGuid _arthasGUID
ObjectGuid _talbotGUID
ObjectGuid _leryssaGUID
ObjectGuid _arlosGUID
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from ScriptedAI
Creature * me
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
npc_thassarian2AI()
npc_thassarian2::npc_thassarian2AI::npc_thassarian2AI (Creature * creature) inline
                                              : ScriptedAI(creature)
        {
            Initialize();
        }
References Initialize().
Member Function Documentation
Cleanup()
void npc_thassarian2::npc_thassarian2AI::Cleanup () inline
        {
            if (Creature* talbot = ObjectAccessor::GetCreature(*me, _talbotGUID))
            {
                talbot->RemoveFromWorld();
            }
            if (Creature* leryssa = ObjectAccessor::GetCreature(*me, _leryssaGUID))
            {
                leryssa->RemoveFromWorld();
            }
            if (Creature* arlos = ObjectAccessor::GetCreature(*me, _arlosGUID))
            {
                arlos->RemoveFromWorld();
            }
            if (Creature* arthas = ObjectAccessor::GetCreature(*me, _arthasGUID))
            {
                arthas->RemoveFromWorld();
            }
        }
References _arlosGUID, _arthasGUID, _leryssaGUID, _talbotGUID, ObjectAccessor::GetCreature(), and ScriptedAI::me.
Referenced by JustDied(), and UpdateAI().
Initialize()
void npc_thassarian2::npc_thassarian2AI::Initialize () inline
        {
            _arthasGUID.Clear();
            _talbotGUID.Clear();
            _leryssaGUID.Clear();
            _arlosGUID.Clear();
        }
References _arlosGUID, _arthasGUID, _leryssaGUID, _talbotGUID, and ObjectGuid::Clear().
Referenced by npc_thassarian2AI(), and Reset().
JustDied()
void npc_thassarian2::npc_thassarian2AI::JustDied (Unit *) inline override virtual
Reimplemented from CreatureAI.
        {
            Cleanup();
            me->DespawnOrUnsummon(1s, 120s);
        }
References Cleanup(), Creature::DespawnOrUnsummon(), and ScriptedAI::me.
MovementInform()
void npc_thassarian2::npc_thassarian2AI::MovementInform (uint32 type, uint32 param) inline override virtual
Reimplemented from CreatureAI.
        {
            if (type == WAYPOINT_MOTION_TYPE && param == 2)
            {
                me->SetWalk(false);
                me->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_STATE_READY1H);
                _events.ScheduleEvent(EVENT_THASSARIAN_SCRIPT_1, 2s);
            }
        }
References _events, EMOTE_STATE_READY1H, EVENT_THASSARIAN_SCRIPT_1, ScriptedAI::me, EventMap::ScheduleEvent(), Unit::SetUInt32Value(), Creature::SetWalk(), UNIT_NPC_EMOTESTATE, and WAYPOINT_MOTION_TYPE.
Reset()
void npc_thassarian2::npc_thassarian2AI::Reset () inline override virtual
Reimplemented from UnitAI.
        {
            me->SetFaction(FACTION_VALIANCE_EXPEDITION_7);
            me->SetStandState(UNIT_STAND_STATE_STAND);
            me->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_ONESHOT_NONE);
            me->RemoveNpcFlag(UNIT_NPC_FLAG_QUESTGIVER);
            me->SetNpcFlag(UNIT_NPC_FLAG_GOSSIP);
            Initialize();
        }
References EMOTE_ONESHOT_NONE, FACTION_VALIANCE_EXPEDITION_7, Initialize(), ScriptedAI::me, Unit::RemoveNpcFlag(), Unit::SetFaction(), Unit::SetNpcFlag(), Unit::SetStandState(), Unit::SetUInt32Value(), UNIT_NPC_EMOTESTATE, UNIT_NPC_FLAG_GOSSIP, UNIT_NPC_FLAG_QUESTGIVER, and UNIT_STAND_STATE_STAND.
SetData()
void npc_thassarian2::npc_thassarian2AI::SetData (uint32 , uint32 data) inline override virtual
Reimplemented from UnitAI.
        {
            switch (data)
            {
                case NPC_LERYSSA:
                {
                    if (Creature* arlos = ObjectAccessor::GetCreature(*me, _arlosGUID))
                    {
                        arlos->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_STATE_STUN);
                    }
                    if (Creature* leryssa = ObjectAccessor::GetCreature(*me, _leryssaGUID))
                    {
                        leryssa->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_STATE_STUN);
                        leryssa->SetOrientation(4.537856f);
                    }
                    _events.ScheduleEvent(EVENT_THASSARIAN_SCRIPT_8, 1s);
                    break;
                }
                case NPC_COUNSELOR_TALBOT:
                {
                    _events.ScheduleEvent(EVENT_THASSARIAN_SCRIPT_18, 0ms);
                }
                    break;
                default:
                    break;
            }
        }
References _arlosGUID, _events, _leryssaGUID, EMOTE_STATE_STUN, EVENT_THASSARIAN_SCRIPT_18, EVENT_THASSARIAN_SCRIPT_8, ObjectAccessor::GetCreature(), ScriptedAI::me, NPC_COUNSELOR_TALBOT, NPC_LERYSSA, EventMap::ScheduleEvent(), and UNIT_NPC_EMOTESTATE.
sGossipHello()
void npc_thassarian2::npc_thassarian2AI::sGossipHello (Player *) inline override virtual
Reimplemented from UnitAI.
        {
            if (!me->HasAura(SPELL_BLOOD_PRESENCE))
            {
                DoCastSelf(SPELL_BLOOD_PRESENCE);
            }
        }
References UnitAI::DoCastSelf(), Unit::HasAura(), ScriptedAI::me, and SPELL_BLOOD_PRESENCE.
sGossipSelect()
void npc_thassarian2::npc_thassarian2AI::sGossipSelect (Player * player, uint32 , uint32 action) inline override virtual
Reimplemented from UnitAI.
        {
            if (action == 0)
            {
                _playerGUID = player->GetGUID();
                CloseGossipMenuFor(player);
                me->RemoveNpcFlag(UNIT_NPC_FLAG_GOSSIP);
                me->GetMotionMaster()->MovePath(PATH_THASSARIAN, false);
            }
        }
References _playerGUID, CloseGossipMenuFor(), Object::GetGUID(), Unit::GetMotionMaster(), ScriptedAI::me, MotionMaster::MovePath(), PATH_THASSARIAN, Unit::RemoveNpcFlag(), and UNIT_NPC_FLAG_GOSSIP.
UpdateAI()
void npc_thassarian2::npc_thassarian2AI::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Implements UnitAI.
        {
            _events.Update(diff);
            if (uint32 eventId = _events.ExecuteEvent())
            {
                switch (eventId)
                {
                    case EVENT_THASSARIAN_SCRIPT_1:
                        // Summon Arthas and Talbot
                        if (Creature* arthas = me->SummonCreature(NPC_IMAGE_LICH_KING, 3729.4614f, 3520.386f, 473.4048f, 1.361f, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 120000))
{
                            _arthasGUID = arthas->GetGUID();
                            arthas->SetUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
                            arthas->SetReactState(REACT_PASSIVE);
                            arthas->SetWalk(true);
                        }
                        if (Creature* talbot = me->SummonCreature(NPC_COUNSELOR_TALBOT, 3748.7627f, 3614.0374f, 473.4048f, 4.5553f, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 120000))
{
                            _talbotGUID = talbot->GetGUID();
                            talbot->SetWalk(true);
                        }
                        _events.ScheduleEvent(EVENT_THASSARIAN_SCRIPT_2, 1s);
                        break;
                    case EVENT_THASSARIAN_SCRIPT_2:
                        // Arthas load path
                        if (Creature* arthas = ObjectAccessor::GetCreature(*me, _arthasGUID))
{
                            arthas->GetMotionMaster()->MovePath(PATH_ARTHAS, false);
                        }
                        _events.ScheduleEvent(EVENT_THASSARIAN_SCRIPT_3, 1s);
                        break;
                    case EVENT_THASSARIAN_SCRIPT_3:
                        // Talbot load path
                        if (Creature* talbot = ObjectAccessor::GetCreature(*me, _talbotGUID))
{
                            talbot->GetMotionMaster()->MovePath(PATH_TALBOT, false);
                        }
                        _events.ScheduleEvent(EVENT_THASSARIAN_SCRIPT_4, 20s);
                        break;
                    case EVENT_THASSARIAN_SCRIPT_4:
                        // Talbot transform and knell
                        if (Creature* talbot = ObjectAccessor::GetCreature(*me, _talbotGUID))
{
                            talbot->CastSpell(talbot, SPELL_TRANSFORM_VALANAR);
                            talbot->UpdateEntry(NPC_PRINCE_VALANAR);
                            talbot->SetFullHealth();
                            talbot->SetFaction(FACTION_UNDEAD_SCOURGE);
                            talbot->SetUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
                            talbot->SetReactState(REACT_PASSIVE);
                            talbot->SetStandState(UNIT_STAND_STATE_KNEEL);
                        }
                        _events.ScheduleEvent(EVENT_THASSARIAN_SCRIPT_5, 7s);
                        break;
                    case EVENT_THASSARIAN_SCRIPT_5:
                        // Talbot say text 1
                        if (Creature* talbot = ObjectAccessor::GetCreature(*me, _talbotGUID))
{
                            talbot->AI()->Talk(SAY_TALBOT_1);
                        }
                        _events.ScheduleEvent(EVENT_THASSARIAN_SCRIPT_6, 9s);
                        break;
                    case EVENT_THASSARIAN_SCRIPT_6:
                        // Summon General Arlos and Leryssa
                        if (Creature* arlos = me->SummonCreature(NPC_GENERAL_ARLOS, 3746.2825f, 3616.3699f, 473.4048f, 4.5029f, TEMPSUMMON_CORPSE_TIMED_DESPAWN))
{
                            _arlosGUID = arlos->GetGUID();
                            arlos->SetWalk(true);
                            arlos->SetImmuneToAll(true);
                            arlos->RemoveNpcFlag(UNIT_NPC_FLAG_QUESTGIVER);
                            arlos->GetMotionMaster()->MovePath(PATH_ARLOS, false);
                        }
                        if (Creature* leryssa = me->SummonCreature(NPC_LERYSSA, 3751.0986f, 3614.9219f, 473.4048f, 4.5029f, TEMPSUMMON_CORPSE_TIMED_DESPAWN))
{
                            _leryssaGUID = leryssa->GetGUID();
                            leryssa->SetWalk(true);
                            leryssa->SetImmuneToAll(true);
                            leryssa->RemoveNpcFlag(UNIT_NPC_FLAG_GOSSIP | UNIT_NPC_FLAG_QUESTGIVER);
                            leryssa->GetMotionMaster()->MovePath(PATH_LERYSSA, false);
                        }
                        _events.ScheduleEvent(EVENT_THASSARIAN_SCRIPT_7, 7s);
                        break;
                    case EVENT_THASSARIAN_SCRIPT_7:
                        // Talbot say text 2
                        if (Creature* talbot = ObjectAccessor::GetCreature(*me, _talbotGUID))
{
                            talbot->AI()->Talk(SAY_TALBOT_2);
                        }
                        break;
                    case EVENT_THASSARIAN_SCRIPT_8:
                        // Thassarian say text 1 and move to location
                        Talk(SAY_THASSARIAN_1);
                        me->SetWalk(false);
                        me->GetMotionMaster()->MovePoint(0, 3722.527f, 3567.2583f, 477.44086f);
                        _events.ScheduleEvent(EVENT_THASSARIAN_SCRIPT_9, 7s);
                        break;
                    case EVENT_THASSARIAN_SCRIPT_9:
                        // Thassarian say text 2
                        Talk(SAY_THASSARIAN_2);
                        me->SetHomePosition(me->GetPositionX(), me->GetPositionY(), me->GetPositionZ(), me->GetOrientation());
                        _events.ScheduleEvent(EVENT_THASSARIAN_SCRIPT_10, 6s);
                        break;
                    case EVENT_THASSARIAN_SCRIPT_10:
                        // Arthas turn to Thassarian and Talbot stand
                        if (Creature* arthas = ObjectAccessor::GetCreature(*me, _arthasGUID))
{
                            arthas->SetFacingToObject(me);
                        }
                        if (Creature* talbot = ObjectAccessor::GetCreature(*me, _talbotGUID))
{
                            talbot->SetStandState(UNIT_STAND_STATE_STAND);
                        }
                        _events.ScheduleEvent(EVENT_THASSARIAN_SCRIPT_11, 4s);
                        break;
                    case EVENT_THASSARIAN_SCRIPT_11:
                        // Arthas say text 2
                        if (Creature* arthas = ObjectAccessor::GetCreature(*me, _arthasGUID))
{
                            arthas->AI()->Talk(SAY_LICH_2);
                        }
                        _events.ScheduleEvent(EVENT_THASSARIAN_SCRIPT_12, 18s);
                        break;
                    case EVENT_THASSARIAN_SCRIPT_12:
                        // Thassarian say text 3
                        Talk(SAY_THASSARIAN_3);
                        _events.ScheduleEvent(EVENT_THASSARIAN_SCRIPT_13, 10s);
                        break;
                    case EVENT_THASSARIAN_SCRIPT_13:
                        // Talbot say text 3
                        if (Creature* talbot = ObjectAccessor::GetCreature(*me, _talbotGUID))
{
                            talbot->AI()->Talk(SAY_TALBOT_3);
                        }
                        _events.ScheduleEvent(EVENT_THASSARIAN_SCRIPT_14, 5s);
                        break;
                    case EVENT_THASSARIAN_SCRIPT_14:
                        // Arthas turn to Talbot say text 3
                        if (Creature* arthas = ObjectAccessor::GetCreature(*me, _arthasGUID))
{
                            if (Creature* talbot = ObjectAccessor::GetCreature(*me, _talbotGUID))
{
                                arthas->SetFacingToObject(talbot);
                            }
                            arthas->AI()->Talk(SAY_LICH_3);
                        }
                        _events.ScheduleEvent(EVENT_THASSARIAN_SCRIPT_15, 5s);
                        break;
                    case EVENT_THASSARIAN_SCRIPT_15:
                        // Arthas turn to me and emote
                        if (Creature* arthas = ObjectAccessor::GetCreature(*me, _arthasGUID))
{
                            arthas->SetFacingToObject(me);
                            arthas->HandleEmoteCommand(EMOTE_ONESHOT_POINT);
                        }
                        _events.ScheduleEvent(EVENT_THASSARIAN_SCRIPT_16, 5s);
                        break;
                    case EVENT_THASSARIAN_SCRIPT_16:
                        // Arthas despawn
                        if (Creature* arthas = ObjectAccessor::GetCreature(*me, _arthasGUID))
{
                            arthas->RemoveFromWorld();
                        }
                        _events.ScheduleEvent(EVENT_THASSARIAN_SCRIPT_17, 3s);
                        break;
                    case EVENT_THASSARIAN_SCRIPT_17:
                        // Talbot say text 4 and attack
                        me->RemoveUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
                        if (Creature* talbot = ObjectAccessor::GetCreature(*me, _talbotGUID))
{
                            talbot->AI()->Talk(SAY_TALBOT_4);
                            talbot->SetFaction(FACTION_UNDEAD_SCOURGE_9);
                            talbot->RemoveUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
                            talbot->SetReactState(REACT_AGGRESSIVE);
                            talbot->Attack(me, false);
                        }
                        break;
                    case EVENT_THASSARIAN_SCRIPT_18:
                        // Arlos say text 1
                        me->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_STATE_READY1H);
                        if (Creature* arlos = ObjectAccessor::GetCreature(*me, _arlosGUID))
{
                            arlos->AI()->Talk(SAY_ARLOS_1);
                            arlos->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_STATE_NONE);
                            arlos->SetStandState(UNIT_STAND_STATE_KNEEL);
                        }
                        if (Creature* leryssa = ObjectAccessor::GetCreature(*me, _leryssaGUID))
{
                            leryssa->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_STATE_NONE);
                        }
                        _events.ScheduleEvent(EVENT_THASSARIAN_SCRIPT_19, 3s);
                        break;
                    case EVENT_THASSARIAN_SCRIPT_19:
                        // Leryssa set facing to me
                        me->RemoveNpcFlag(UNIT_NPC_FLAG_GOSSIP);
                        me->SetNpcFlag(UNIT_NPC_FLAG_QUESTGIVER);
                        if (Creature* leryssa = me->FindNearestCreature(NPC_LERYSSA, 50.0f, true))
{
                            _leryssaGUID = leryssa->GetGUID();
                            leryssa->SetFacingToObject(me);
                            me->SetFacingToObject(leryssa);
                        }
                        _events.ScheduleEvent(EVENT_THASSARIAN_SCRIPT_20, 3s);
                        break;
                    case EVENT_THASSARIAN_SCRIPT_20:
                        // Arlos say text 2 and die. Leryssa say text 1
                        if (Creature* arlos = me->FindNearestCreature(NPC_GENERAL_ARLOS, 50.0f, true))
{
                            _arlosGUID = arlos->GetGUID();
                            arlos->AI()->Talk(SAY_ARLOS_2);
                            arlos->SetStandState(UNIT_STAND_STATE_DEAD);
                        }
                        if (Creature* leryssa = ObjectAccessor::GetCreature(*me, _leryssaGUID))
{
                            leryssa->AI()->Talk(SAY_LERYSSA_1);
                        }
                        _events.ScheduleEvent(EVENT_THASSARIAN_SCRIPT_21, 5s);
                        break;
                    case EVENT_THASSARIAN_SCRIPT_21:
                        // Thassarian say text 4
                        me->SetStandState(UNIT_STAND_STATE_KNEEL);
                        Talk(SAY_THASSARIAN_4);
                        _events.ScheduleEvent(EVENT_THASSARIAN_SCRIPT_22, 3s);
                        break;
                    case EVENT_THASSARIAN_SCRIPT_22:
                        // Leryssa run to Thassarian
                        if (Creature* leryssa = ObjectAccessor::GetCreature(*me, _leryssaGUID))
{
                            leryssa->SetWalk(false);
                            leryssa->MonsterMoveWithSpeed(3726.751f, 3568.1633f, 477.44086f, leryssa->GetSpeed(MOVE_RUN));
                        }
                        _events.ScheduleEvent(EVENT_THASSARIAN_SCRIPT_23, 2s);
                        break;
                    case EVENT_THASSARIAN_SCRIPT_23:
                        // Leryssa say text 2
                        if (Creature* leryssa = ObjectAccessor::GetCreature(*me, _leryssaGUID))
{
                            leryssa->AI()->Talk(SAY_LERYSSA_2);
                            leryssa->SetStandState(UNIT_STAND_STATE_SIT);
                        }
                        _events.ScheduleEvent(EVENT_THASSARIAN_SCRIPT_24, 5s);
                        break;
                    case EVENT_THASSARIAN_SCRIPT_24:
                        // Thassarian say text 5
                        Talk(SAY_THASSARIAN_5);
                        _events.ScheduleEvent(EVENT_THASSARIAN_SCRIPT_25, 10s);
                        break;
                    case EVENT_THASSARIAN_SCRIPT_25:
                        // Leryssa say text 3
                        if (Creature* leryssa = ObjectAccessor::GetCreature(*me, _leryssaGUID))
{
                            leryssa->AI()->Talk(SAY_LERYSSA_3);
                        }
                        _events.ScheduleEvent(EVENT_THASSARIAN_SCRIPT_26, 12s);
                        break;
                    case EVENT_THASSARIAN_SCRIPT_26:
                        // Thassarian say text 6
                        Talk(SAY_THASSARIAN_6);
                        _events.ScheduleEvent(EVENT_THASSARIAN_SCRIPT_27, 11s);
                        break;
                    case EVENT_THASSARIAN_SCRIPT_27:
                        // Leryssa say text 4
                        if (Creature* leryssa = ObjectAccessor::GetCreature(*me, _leryssaGUID))
{
                            leryssa->AI()->Talk(SAY_LERYSSA_4);
                        }
                        _events.ScheduleEvent(EVENT_THASSARIAN_SCRIPT_28, 12s);
                        break;
                    case EVENT_THASSARIAN_SCRIPT_28:
                        // Thassarian say text 7
                        Talk(SAY_THASSARIAN_7);
                        _events.ScheduleEvent(EVENT_THASSARIAN_SCRIPT_29, 35s);
                        break;
                    case EVENT_THASSARIAN_SCRIPT_29:
                        Cleanup();
                        me->DespawnOrUnsummon(30s, 120s);
                        break;
                    default:
                        break;
                }
            }
            if (!UpdateVictim())
            {
                return;
            }
            DoMeleeAttackIfReady();
        }
References _arlosGUID, _arthasGUID, _events, _leryssaGUID, _talbotGUID, Cleanup(), Creature::DespawnOrUnsummon(), UnitAI::DoMeleeAttackIfReady(), EMOTE_ONESHOT_POINT, EMOTE_STATE_NONE, EMOTE_STATE_READY1H, EVENT_THASSARIAN_SCRIPT_1, EVENT_THASSARIAN_SCRIPT_10, EVENT_THASSARIAN_SCRIPT_11, EVENT_THASSARIAN_SCRIPT_12, EVENT_THASSARIAN_SCRIPT_13, EVENT_THASSARIAN_SCRIPT_14, EVENT_THASSARIAN_SCRIPT_15, EVENT_THASSARIAN_SCRIPT_16, EVENT_THASSARIAN_SCRIPT_17, EVENT_THASSARIAN_SCRIPT_18, EVENT_THASSARIAN_SCRIPT_19, EVENT_THASSARIAN_SCRIPT_2, EVENT_THASSARIAN_SCRIPT_20, EVENT_THASSARIAN_SCRIPT_21, EVENT_THASSARIAN_SCRIPT_22, EVENT_THASSARIAN_SCRIPT_23, EVENT_THASSARIAN_SCRIPT_24, EVENT_THASSARIAN_SCRIPT_25, EVENT_THASSARIAN_SCRIPT_26, EVENT_THASSARIAN_SCRIPT_27, EVENT_THASSARIAN_SCRIPT_28, EVENT_THASSARIAN_SCRIPT_29, EVENT_THASSARIAN_SCRIPT_3, EVENT_THASSARIAN_SCRIPT_4, EVENT_THASSARIAN_SCRIPT_5, EVENT_THASSARIAN_SCRIPT_6, EVENT_THASSARIAN_SCRIPT_7, EVENT_THASSARIAN_SCRIPT_8, EVENT_THASSARIAN_SCRIPT_9, EventMap::ExecuteEvent(), FACTION_UNDEAD_SCOURGE, FACTION_UNDEAD_SCOURGE_9, WorldObject::FindNearestCreature(), ObjectAccessor::GetCreature(), Unit::GetMotionMaster(), Position::GetOrientation(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), ScriptedAI::me, MOVE_RUN, MotionMaster::MovePoint(), NPC_COUNSELOR_TALBOT, NPC_GENERAL_ARLOS, NPC_IMAGE_LICH_KING, NPC_LERYSSA, NPC_PRINCE_VALANAR, PATH_ARLOS, PATH_ARTHAS, PATH_LERYSSA, PATH_TALBOT, REACT_AGGRESSIVE, REACT_PASSIVE, Unit::RemoveNpcFlag(), Unit::RemoveUnitFlag(), SAY_ARLOS_1, SAY_ARLOS_2, SAY_LERYSSA_1, SAY_LERYSSA_2, SAY_LERYSSA_3, SAY_LERYSSA_4, SAY_LICH_2, SAY_LICH_3, SAY_TALBOT_1, SAY_TALBOT_2, SAY_TALBOT_3, SAY_TALBOT_4, SAY_THASSARIAN_1, SAY_THASSARIAN_2, SAY_THASSARIAN_3, SAY_THASSARIAN_4, SAY_THASSARIAN_5, SAY_THASSARIAN_6, SAY_THASSARIAN_7, EventMap::ScheduleEvent(), Unit::SetFacingToObject(), Creature::SetHomePosition(), Unit::SetNpcFlag(), Unit::SetStandState(), Unit::SetUInt32Value(), Creature::SetWalk(), SPELL_TRANSFORM_VALANAR, WorldObject::SummonCreature(), TEMPSUMMON_CORPSE_TIMED_DESPAWN, UNIT_FLAG_NON_ATTACKABLE, UNIT_NPC_EMOTESTATE, UNIT_NPC_FLAG_GOSSIP, UNIT_NPC_FLAG_QUESTGIVER, UNIT_STAND_STATE_DEAD, UNIT_STAND_STATE_KNEEL, UNIT_STAND_STATE_SIT, UNIT_STAND_STATE_STAND, EventMap::Update(), and CreatureAI::UpdateVictim().
Member Data Documentation
_arlosGUID
ObjectGuid npc_thassarian2::npc_thassarian2AI::_arlosGUID private
Referenced by Cleanup(), Initialize(), SetData(), and UpdateAI().
_arthasGUID
ObjectGuid npc_thassarian2::npc_thassarian2AI::_arthasGUID private
Referenced by Cleanup(), Initialize(), and UpdateAI().
_events
EventMap npc_thassarian2::npc_thassarian2AI::_events private
Referenced by MovementInform(), SetData(), and UpdateAI().
_leryssaGUID
ObjectGuid npc_thassarian2::npc_thassarian2AI::_leryssaGUID private
Referenced by Cleanup(), Initialize(), SetData(), and UpdateAI().
_playerGUID
ObjectGuid npc_thassarian2::npc_thassarian2AI::_playerGUID private
Referenced by sGossipSelect().
_talbotGUID
ObjectGuid npc_thassarian2::npc_thassarian2AI::_talbotGUID private
Referenced by Cleanup(), Initialize(), and UpdateAI().
The documentation for this struct was generated from the following file:
azerothcore-wotlk/src/server/scripts/Northrend/zone_borean_tundra.cpp