AzerothCore Doxygen
LuaItemTemplate Namespace Reference
Functions
int GetItemId (lua_State *L, ItemTemplate *itemTemplate)
int GetClass (lua_State *L, ItemTemplate *itemTemplate)
int GetSubClass (lua_State *L, ItemTemplate *itemTemplate)
int GetName (lua_State *L, ItemTemplate *itemTemplate)
int GetDisplayId (lua_State *L, ItemTemplate *itemTemplate)
int GetQuality (lua_State *L, ItemTemplate *itemTemplate)
int GetFlags (lua_State *L, ItemTemplate *itemTemplate)
int GetExtraFlags (lua_State *L, ItemTemplate *itemTemplate)
int GetBuyCount (lua_State *L, ItemTemplate *itemTemplate)
int GetBuyPrice (lua_State *L, ItemTemplate *itemTemplate)
int GetSellPrice (lua_State *L, ItemTemplate *itemTemplate)
int GetInventoryType (lua_State *L, ItemTemplate *itemTemplate)
int GetAllowableClass (lua_State *L, ItemTemplate *itemTemplate)
int GetAllowableRace (lua_State *L, ItemTemplate *itemTemplate)
int GetItemLevel (lua_State *L, ItemTemplate *itemTemplate)
int GetRequiredLevel (lua_State *L, ItemTemplate *itemTemplate)
Function Documentation
GetAllowableClass()
int LuaItemTemplate::GetAllowableClass (lua_State * L, ItemTemplate * itemTemplate)
Returns the [Player] classes allowed to use this [ItemTemplate].
Returns
uint32 allowableClass
    {
        Eluna::Push(L, itemTemplate->AllowableClass);
        return 1;
    }
References ItemTemplate::AllowableClass, and Eluna::Push().
GetAllowableRace()
int LuaItemTemplate::GetAllowableRace (lua_State * L, ItemTemplate * itemTemplate)
Returns the [Player] races allowed to use this [ItemTemplate].
Returns
uint32 allowableRace
    {
        Eluna::Push(L, itemTemplate->AllowableRace);
        return 1;
    }
References ItemTemplate::AllowableRace, and Eluna::Push().
GetBuyCount()
int LuaItemTemplate::GetBuyCount (lua_State * L, ItemTemplate * itemTemplate)
Returns the [ItemTemplate]'s default purchase count.
Returns
uint32 buyCount
    {
        Eluna::Push(L, itemTemplate->BuyCount);
        return 1;
    }
References ItemTemplate::BuyCount, and Eluna::Push().
GetBuyPrice()
int LuaItemTemplate::GetBuyPrice (lua_State * L, ItemTemplate * itemTemplate)
Returns the [ItemTemplate]'s purchase price.
Returns
int32 buyPrice
    {
        Eluna::Push(L, itemTemplate->BuyPrice);
        return 1;
    }
References ItemTemplate::BuyPrice, and Eluna::Push().
GetClass()
int LuaItemTemplate::GetClass (lua_State * L, ItemTemplate * itemTemplate)
Returns the [ItemTemplate]'s class.
Returns
uint32 class
    {
        Eluna::Push(L, itemTemplate->Class);
        return 1;
    }
References ItemTemplate::Class, and Eluna::Push().
GetDisplayId()
int LuaItemTemplate::GetDisplayId (lua_State * L, ItemTemplate * itemTemplate)
Returns the [ItemTemplate]'s display ID.
Returns
uint32 displayId
    {
        Eluna::Push(L, itemTemplate->DisplayInfoID);
        return 1;
    }
References ItemTemplate::DisplayInfoID, and Eluna::Push().
GetExtraFlags()
int LuaItemTemplate::GetExtraFlags (lua_State * L, ItemTemplate * itemTemplate)
Returns the [ItemTemplate]'s extra flags.
Returns
uint32 flags
    {
        Eluna::Push(L, itemTemplate->Flags2);
        return 1;
    }
References ItemTemplate::Flags2, and Eluna::Push().
GetFlags()
int LuaItemTemplate::GetFlags (lua_State * L, ItemTemplate * itemTemplate)
Returns the [ItemTemplate]'s flags.
Returns
uint32 flags
    {
        Eluna::Push(L, itemTemplate->Flags);
        return 1;
    }
References ItemTemplate::Flags, and Eluna::Push().
GetInventoryType()
int LuaItemTemplate::GetInventoryType (lua_State * L, ItemTemplate * itemTemplate)
Returns the [ItemTemplate]'s inventory type.
Returns
uint32 inventoryType
    {
        Eluna::Push(L, itemTemplate->InventoryType);
        return 1;
    }
References ItemTemplate::InventoryType, and Eluna::Push().
GetItemId()
int LuaItemTemplate::GetItemId (lua_State * L, ItemTemplate * itemTemplate)
Returns the [ItemTemplate]'s ID.
Returns
uint32 itemId
    {
        Eluna::Push(L, itemTemplate->ItemId);
        return 1;
    }
References ItemTemplate::ItemId, and Eluna::Push().
GetItemLevel()
int LuaItemTemplate::GetItemLevel (lua_State * L, ItemTemplate * itemTemplate)
Returns the [ItemTemplate]'s item level.
Returns
uint32 itemLevel
    {
        Eluna::Push(L, itemTemplate->ItemLevel);
        return 1;
    }
References ItemTemplate::ItemLevel, and Eluna::Push().
GetName()
int LuaItemTemplate::GetName (lua_State * L, ItemTemplate * itemTemplate)
Returns the [ItemTemplate]'s name.
Returns
string name
    {
        Eluna::Push(L, itemTemplate->Name1);
        return 1;
    }
References ItemTemplate::Name1, and Eluna::Push().
GetQuality()
int LuaItemTemplate::GetQuality (lua_State * L, ItemTemplate * itemTemplate)
Returns the [ItemTemplate]'s quality.
Returns
uint32 quality
    {
        Eluna::Push(L, itemTemplate->Quality);
        return 1;
    }
References Eluna::Push(), and ItemTemplate::Quality.
GetRequiredLevel()
int LuaItemTemplate::GetRequiredLevel (lua_State * L, ItemTemplate * itemTemplate)
Returns the minimum level required to use this [ItemTemplate].
Returns
uint32 requiredLevel
    {
        Eluna::Push(L, itemTemplate->RequiredLevel);
        return 1;
    }
References Eluna::Push(), and ItemTemplate::RequiredLevel.
GetSellPrice()
int LuaItemTemplate::GetSellPrice (lua_State * L, ItemTemplate * itemTemplate)
Returns the [ItemTemplate]'s sell price.
Returns
uint32 sellPrice
    {
        Eluna::Push(L, itemTemplate->SellPrice);
        return 1;
    }
References Eluna::Push(), and ItemTemplate::SellPrice.
GetSubClass()
int LuaItemTemplate::GetSubClass (lua_State * L, ItemTemplate * itemTemplate)
Returns the [ItemTemplate]'s subclass.
Returns
uint32 subClass
    {
        Eluna::Push(L, itemTemplate->SubClass);
        return 1;
    }
References Eluna::Push(), and ItemTemplate::SubClass.