AzerothCore Doxygen
SpellProcEntryBuilder Class Reference
Builder class for creating SpellProcEntry test instances.
#include "ProcEventInfoHelper.h"
Public Member Functions
SpellProcEntryBuilder ()
SpellProcEntryBuilder & WithSchoolMask (uint32 schoolMask)
SpellProcEntryBuilder & WithSpellFamilyName (uint32 familyName)
SpellProcEntryBuilder & WithSpellFamilyMask (flag96 familyMask)
SpellProcEntryBuilder & WithProcFlags (uint32 procFlags)
SpellProcEntryBuilder & WithSpellTypeMask (uint32 spellTypeMask)
SpellProcEntryBuilder & WithSpellPhaseMask (uint32 spellPhaseMask)
SpellProcEntryBuilder & WithHitMask (uint32 hitMask)
SpellProcEntryBuilder & WithAttributesMask (uint32 attributesMask)
SpellProcEntryBuilder & WithDisableEffectsMask (uint32 disableEffectsMask)
SpellProcEntryBuilder & WithProcsPerMinute (float ppm)
SpellProcEntryBuilder & WithChance (float chance)
SpellProcEntryBuilder & WithCooldown (Milliseconds cooldown)
SpellProcEntryBuilder & WithCharges (uint32 charges)
SpellProcEntry Build () const
Private Attributes
SpellProcEntry _entry
Detailed Description
Builder class for creating SpellProcEntry test instances.
This helper allows easy construction of SpellProcEntry objects for unit testing the proc system.
Constructor & Destructor Documentation
SpellProcEntryBuilder()
SpellProcEntryBuilder::SpellProcEntryBuilder () inline
    {
        _entry = {};
    }
References _entry.
Member Function Documentation
Build()
SpellProcEntry SpellProcEntryBuilder::Build () const inline
    {
        return _entry;
    }
References _entry.
Referenced by SpellProcTriggeredFilterTest::CreateBasicProcEntry(), AuraScriptProcTestFixture::CreateProcEntry(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
WithAttributesMask()
SpellProcEntryBuilder & SpellProcEntryBuilder::WithAttributesMask (uint32 attributesMask) inline
    {
        _entry.AttributesMask = attributesMask;
        return *this;
    }
References _entry, and SpellProcEntry::AttributesMask.
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
WithChance()
SpellProcEntryBuilder & SpellProcEntryBuilder::WithChance (float chance) inline
    {
        _entry.Chance = chance;
        return *this;
    }
References _entry, and SpellProcEntry::Chance.
Referenced by SpellProcTriggeredFilterTest::CreateBasicProcEntry(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
WithCharges()
SpellProcEntryBuilder & SpellProcEntryBuilder::WithCharges (uint32 charges) inline
    {
        _entry.Charges = charges;
        return *this;
    }
References _entry, and SpellProcEntry::Charges.
Referenced by TEST_F().
WithCooldown()
SpellProcEntryBuilder & SpellProcEntryBuilder::WithCooldown (Milliseconds cooldown) inline
    {
        _entry.Cooldown = cooldown;
        return *this;
    }
References _entry, and SpellProcEntry::Cooldown.
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
WithDisableEffectsMask()
SpellProcEntryBuilder & SpellProcEntryBuilder::WithDisableEffectsMask (uint32 disableEffectsMask) inline
    {
        _entry.DisableEffectsMask = disableEffectsMask;
        return *this;
    }
References _entry, and SpellProcEntry::DisableEffectsMask.
Referenced by TEST_F(), and TEST_F().
WithHitMask()
SpellProcEntryBuilder & SpellProcEntryBuilder::WithHitMask (uint32 hitMask) inline
    {
        _entry.HitMask = hitMask;
        return *this;
    }
References _entry, and SpellProcEntry::HitMask.
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
WithProcFlags()
SpellProcEntryBuilder & SpellProcEntryBuilder::WithProcFlags (uint32 procFlags) inline
    {
        _entry.ProcFlags = procFlags;
        return *this;
    }
References _entry, and SpellProcEntry::ProcFlags.
Referenced by SpellProcTriggeredFilterTest::CreateBasicProcEntry(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
WithProcsPerMinute()
SpellProcEntryBuilder & SpellProcEntryBuilder::WithProcsPerMinute (float ppm) inline
    {
        _entry.ProcsPerMinute = ppm;
        return *this;
    }
References _entry, and SpellProcEntry::ProcsPerMinute.
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
WithSchoolMask()
SpellProcEntryBuilder & SpellProcEntryBuilder::WithSchoolMask (uint32 schoolMask) inline
    {
        _entry.SchoolMask = schoolMask;
        return *this;
    }
References _entry, and SpellProcEntry::SchoolMask.
Referenced by TEST_F(), TEST_F(), and TEST_F().
WithSpellFamilyMask()
SpellProcEntryBuilder & SpellProcEntryBuilder::WithSpellFamilyMask (flag96 familyMask) inline
    {
        _entry.SpellFamilyMask = familyMask;
        return *this;
    }
References _entry, and SpellProcEntry::SpellFamilyMask.
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
WithSpellFamilyName()
SpellProcEntryBuilder & SpellProcEntryBuilder::WithSpellFamilyName (uint32 familyName) inline
    {
        _entry.SpellFamilyName = familyName;
        return *this;
    }
References _entry, and SpellProcEntry::SpellFamilyName.
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
WithSpellPhaseMask()
SpellProcEntryBuilder & SpellProcEntryBuilder::WithSpellPhaseMask (uint32 spellPhaseMask) inline
    {
        _entry.SpellPhaseMask = spellPhaseMask;
        return *this;
    }
References _entry, and SpellProcEntry::SpellPhaseMask.
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
WithSpellTypeMask()
SpellProcEntryBuilder & SpellProcEntryBuilder::WithSpellTypeMask (uint32 spellTypeMask) inline
    {
        _entry.SpellTypeMask = spellTypeMask;
        return *this;
    }
References _entry, spellTypeMask, and SpellProcEntry::SpellTypeMask.
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
Member Data Documentation
_entry
SpellProcEntry SpellProcEntryBuilder::_entry private
Referenced by Build(), SpellProcEntryBuilder(), WithAttributesMask(), WithChance(), WithCharges(), WithCooldown(), WithDisableEffectsMask(), WithHitMask(), WithProcFlags(), WithProcsPerMinute(), WithSchoolMask(), WithSpellFamilyMask(), WithSpellFamilyName(), WithSpellPhaseMask(), and WithSpellTypeMask().
The documentation for this class was generated from the following file:
azerothcore-wotlk/src/test/mocks/ProcEventInfoHelper.h