AzerothCore Doxygen
SpellProcTriggeredFilterTest.cpp File Reference
Unit tests for triggered spell filtering in proc system.
#include "ProcChanceTestHelper.h"
#include "ProcEventInfoHelper.h"
#include "gtest/gtest.h"
Classes
class SpellProcTriggeredFilterTest
Functions
TEST_F (SpellProcTriggeredFilterTest, SelfLoop_BlocksWhenTriggeredBySameAura)
TEST_F (SpellProcTriggeredFilterTest, SelfLoop_AllowsWhenTriggeredByDifferentAura)
TEST_F (SpellProcTriggeredFilterTest, SelfLoop_AllowsWhenNotTriggered)
TEST_F (SpellProcTriggeredFilterTest, TriggeredSpell_BlockedByDefault)
TEST_F (SpellProcTriggeredFilterTest, NonTriggeredSpell_AllowedByDefault)
TEST_F (SpellProcTriggeredFilterTest, CanProcFromProcs_AllowsTriggeredSpells)
TEST_F (SpellProcTriggeredFilterTest, TriggeredCanProcAttribute_AllowsTriggeredSpells)
TEST_F (SpellProcTriggeredFilterTest, NotAProc_AllowsTriggeredSpell)
TEST_F (SpellProcTriggeredFilterTest, AutoAttackMelee_AllowsTriggeredSpells)
TEST_F (SpellProcTriggeredFilterTest, AutoAttackRanged_AllowsTriggeredSpells)
TEST_F (SpellProcTriggeredFilterTest, TakenAutoAttack_AllowsTriggeredSpells)
TEST_F (SpellProcTriggeredFilterTest, KillEvent_AllowsTriggeredSpells)
TEST_F (SpellProcTriggeredFilterTest, KilledEvent_AllowsTriggeredSpells)
TEST_F (SpellProcTriggeredFilterTest, DeathEvent_AllowsTriggeredSpells)
TEST_F (SpellProcTriggeredFilterTest, KillWithOtherFlags_StillAllowsTriggeredSpells)
TEST_F (SpellProcTriggeredFilterTest, Scenario_RapidKilling_AutoShotKill)
TEST_F (SpellProcTriggeredFilterTest, KillEvent_SelfLoopStillBlocked)
TEST_F (SpellProcTriggeredFilterTest, Combined_SelfLoopTakesPrecedence)
TEST_F (SpellProcTriggeredFilterTest, Combined_MultipleExceptions)
TEST_F (SpellProcTriggeredFilterTest, Scenario_HotStreak_TriggeredPyroblast)
TEST_F (SpellProcTriggeredFilterTest, Scenario_SwordSpec_ChainProcs)
TEST_F (SpellProcTriggeredFilterTest, Scenario_WindfuryWeapon_AutoAttack)
TEST_F (SpellProcTriggeredFilterTest, EdgeCase_ZeroEventMask)
TEST_F (SpellProcTriggeredFilterTest, EdgeCase_AllExceptionsDisabled)
Detailed Description
Unit tests for triggered spell filtering in proc system.
Tests the logic from SpellAuras.cpp:2191-2209:
Self-loop prevention (spell triggered by same aura)
Triggered spell blocking (default behavior)
SPELL_ATTR3_CAN_PROC_FROM_PROCS exception
PROC_ATTR_TRIGGERED_CAN_PROC exception
SPELL_ATTR3_NOT_A_PROC exception
AUTO_ATTACK_PROC_FLAG_MASK exception
Definition in file SpellProcTriggeredFilterTest.cpp.
Function Documentation
TEST_F() [1/24]
TEST_F (SpellProcTriggeredFilterTest , AutoAttackMelee_AllowsTriggeredSpells)
{
    ProcChanceTestHelper::TriggeredSpellConfig config;
    config.isTriggered = true;
    config.auraHasCanProcFromProcs = false;
    config.spellHasNotAProc = false;
    auto procEntry = CreateBasicProcEntry();
    // Event mask includes auto-attack - exception applies
    uint32 autoAttackEvent = PROC_FLAG_DONE_MELEE_AUTO_ATTACK;
    EXPECT_FALSE(ProcChanceTestHelper::ShouldBlockTriggeredSpell(
        config, procEntry, autoAttackEvent))
        << "AUTO_ATTACK_PROC_FLAG_MASK (melee) should allow triggered spells";
}
References ProcChanceTestHelper::TriggeredSpellConfig::auraHasCanProcFromProcs, ProcChanceTestHelper::TriggeredSpellConfig::isTriggered, PROC_FLAG_DONE_MELEE_AUTO_ATTACK, ProcChanceTestHelper::ShouldBlockTriggeredSpell(), and ProcChanceTestHelper::TriggeredSpellConfig::spellHasNotAProc.
TEST_F() [2/24]
TEST_F (SpellProcTriggeredFilterTest , AutoAttackRanged_AllowsTriggeredSpells)
{
    ProcChanceTestHelper::TriggeredSpellConfig config;
    config.isTriggered = true;
    config.auraHasCanProcFromProcs = false;
    config.spellHasNotAProc = false;
    auto procEntry = CreateBasicProcEntry();
    // Hunter auto-shot or wand (ranged auto-attack)
    uint32 rangedAutoEvent = PROC_FLAG_DONE_RANGED_AUTO_ATTACK;
    EXPECT_FALSE(ProcChanceTestHelper::ShouldBlockTriggeredSpell(
        config, procEntry, rangedAutoEvent))
        << "AUTO_ATTACK_PROC_FLAG_MASK (ranged) should allow triggered spells";
}
References ProcChanceTestHelper::TriggeredSpellConfig::auraHasCanProcFromProcs, ProcChanceTestHelper::TriggeredSpellConfig::isTriggered, PROC_FLAG_DONE_RANGED_AUTO_ATTACK, ProcChanceTestHelper::ShouldBlockTriggeredSpell(), and ProcChanceTestHelper::TriggeredSpellConfig::spellHasNotAProc.
TEST_F() [3/24]
TEST_F (SpellProcTriggeredFilterTest , CanProcFromProcs_AllowsTriggeredSpells)
{
    ProcChanceTestHelper::TriggeredSpellConfig config;
    config.isTriggered = true;
    config.auraHasCanProcFromProcs = true;  // Exception: aura has SPELL_ATTR3_CAN_PROC_FROM_PROCS
    config.spellHasNotAProc = false;
    auto procEntry = CreateBasicProcEntry();
    // Should be allowed due to aura attribute
    EXPECT_FALSE(ProcChanceTestHelper::ShouldBlockTriggeredSpell(
        config, procEntry, PROC_FLAG_DONE_SPELL_MAGIC_DMG_CLASS_NEG))
        << "SPELL_ATTR3_CAN_PROC_FROM_PROCS should allow triggered spells";
}
References ProcChanceTestHelper::TriggeredSpellConfig::auraHasCanProcFromProcs, ProcChanceTestHelper::TriggeredSpellConfig::isTriggered, PROC_FLAG_DONE_SPELL_MAGIC_DMG_CLASS_NEG, ProcChanceTestHelper::ShouldBlockTriggeredSpell(), and ProcChanceTestHelper::TriggeredSpellConfig::spellHasNotAProc.
TEST_F() [4/24]
TEST_F (SpellProcTriggeredFilterTest , Combined_MultipleExceptions)
{
    ProcChanceTestHelper::TriggeredSpellConfig config;
    config.isTriggered = true;
    config.auraHasCanProcFromProcs = true;  // Exception 1
    config.spellHasNotAProc = true;         // Exception 2
    auto procEntry = SpellProcEntryBuilder()
        .WithProcFlags(PROC_FLAG_DONE_SPELL_MAGIC_DMG_CLASS_NEG)
        .WithAttributesMask(PROC_ATTR_TRIGGERED_CAN_PROC)  // Exception 3
        .WithChance(100.0f)
        .Build();
    // Should be allowed (multiple exceptions all pass)
    EXPECT_FALSE(ProcChanceTestHelper::ShouldBlockTriggeredSpell(
        config, procEntry, PROC_FLAG_DONE_SPELL_MAGIC_DMG_CLASS_NEG))
        << "Multiple exceptions should still allow proc";
}
References ProcChanceTestHelper::TriggeredSpellConfig::auraHasCanProcFromProcs, SpellProcEntryBuilder::Build(), ProcChanceTestHelper::TriggeredSpellConfig::isTriggered, PROC_ATTR_TRIGGERED_CAN_PROC, PROC_FLAG_DONE_SPELL_MAGIC_DMG_CLASS_NEG, ProcChanceTestHelper::ShouldBlockTriggeredSpell(), ProcChanceTestHelper::TriggeredSpellConfig::spellHasNotAProc, SpellProcEntryBuilder::WithAttributesMask(), SpellProcEntryBuilder::WithChance(), and SpellProcEntryBuilder::WithProcFlags().
TEST_F() [5/24]
TEST_F (SpellProcTriggeredFilterTest , Combined_SelfLoopTakesPrecedence)
{
    ProcChanceTestHelper::TriggeredSpellConfig config;
    config.isTriggered = true;
    config.triggeredByAuraSpellId = 12345;
    config.procAuraSpellId = 12345;  // Self-loop
    config.auraHasCanProcFromProcs = true;  // Would normally allow
    auto procEntry = SpellProcEntryBuilder()
        .WithProcFlags(PROC_FLAG_DONE_SPELL_MAGIC_DMG_CLASS_NEG)
        .WithAttributesMask(PROC_ATTR_TRIGGERED_CAN_PROC)
        .WithChance(100.0f)
        .Build();
    // Self-loop should still block even with exceptions
    EXPECT_TRUE(ProcChanceTestHelper::ShouldBlockTriggeredSpell(
        config, procEntry, PROC_FLAG_DONE_SPELL_MAGIC_DMG_CLASS_NEG))
        << "Self-loop should block even when TRIGGERED_CAN_PROC is set";
}
References ProcChanceTestHelper::TriggeredSpellConfig::auraHasCanProcFromProcs, SpellProcEntryBuilder::Build(), ProcChanceTestHelper::TriggeredSpellConfig::isTriggered, PROC_ATTR_TRIGGERED_CAN_PROC, PROC_FLAG_DONE_SPELL_MAGIC_DMG_CLASS_NEG, ProcChanceTestHelper::TriggeredSpellConfig::procAuraSpellId, ProcChanceTestHelper::ShouldBlockTriggeredSpell(), ProcChanceTestHelper::TriggeredSpellConfig::triggeredByAuraSpellId, SpellProcEntryBuilder::WithAttributesMask(), SpellProcEntryBuilder::WithChance(), and SpellProcEntryBuilder::WithProcFlags().
TEST_F() [6/24]
TEST_F (SpellProcTriggeredFilterTest , DeathEvent_AllowsTriggeredSpells)
{
    ProcChanceTestHelper::TriggeredSpellConfig config;
    config.isTriggered = true;
    config.auraHasCanProcFromProcs = false;
    config.spellHasNotAProc = false;
    auto procEntry = CreateBasicProcEntry();
    // PROC_FLAG_DEATH should bypass triggered-spell filter
    EXPECT_FALSE(ProcChanceTestHelper::ShouldBlockTriggeredSpell(
        config, procEntry, PROC_FLAG_DEATH))
        << "PROC_FLAG_DEATH should allow triggered spells";
}
References ProcChanceTestHelper::TriggeredSpellConfig::auraHasCanProcFromProcs, ProcChanceTestHelper::TriggeredSpellConfig::isTriggered, PROC_FLAG_DEATH, ProcChanceTestHelper::ShouldBlockTriggeredSpell(), and ProcChanceTestHelper::TriggeredSpellConfig::spellHasNotAProc.
TEST_F() [7/24]
TEST_F (SpellProcTriggeredFilterTest , EdgeCase_AllExceptionsDisabled)
{
    ProcChanceTestHelper::TriggeredSpellConfig config;
    config.isTriggered = true;
    config.auraHasCanProcFromProcs = false;
    config.spellHasNotAProc = false;
    auto procEntry = SpellProcEntryBuilder()
        .WithProcFlags(PROC_FLAG_DONE_SPELL_MAGIC_DMG_CLASS_NEG)
        .WithAttributesMask(0)  // No TRIGGERED_CAN_PROC
        .WithChance(100.0f)
        .Build();
    // No exceptions - should block
    EXPECT_TRUE(ProcChanceTestHelper::ShouldBlockTriggeredSpell(
        config, procEntry, PROC_FLAG_DONE_SPELL_MAGIC_DMG_CLASS_NEG))
        << "No exceptions should block triggered spell";
}
References ProcChanceTestHelper::TriggeredSpellConfig::auraHasCanProcFromProcs, SpellProcEntryBuilder::Build(), ProcChanceTestHelper::TriggeredSpellConfig::isTriggered, PROC_FLAG_DONE_SPELL_MAGIC_DMG_CLASS_NEG, ProcChanceTestHelper::ShouldBlockTriggeredSpell(), ProcChanceTestHelper::TriggeredSpellConfig::spellHasNotAProc, SpellProcEntryBuilder::WithAttributesMask(), SpellProcEntryBuilder::WithChance(), and SpellProcEntryBuilder::WithProcFlags().
TEST_F() [8/24]
TEST_F (SpellProcTriggeredFilterTest , EdgeCase_ZeroEventMask)
{
    ProcChanceTestHelper::TriggeredSpellConfig config;
    config.isTriggered = true;
    config.auraHasCanProcFromProcs = false;
    auto procEntry = CreateBasicProcEntry();
    // Zero event mask means no auto-attack exception
    EXPECT_TRUE(ProcChanceTestHelper::ShouldBlockTriggeredSpell(
        config, procEntry, 0))
        << "Zero event mask should not grant auto-attack exception";
}
References ProcChanceTestHelper::TriggeredSpellConfig::auraHasCanProcFromProcs, ProcChanceTestHelper::TriggeredSpellConfig::isTriggered, and ProcChanceTestHelper::ShouldBlockTriggeredSpell().
TEST_F() [9/24]
TEST_F (SpellProcTriggeredFilterTest , KilledEvent_AllowsTriggeredSpells)
{
    ProcChanceTestHelper::TriggeredSpellConfig config;
    config.isTriggered = true;
    config.auraHasCanProcFromProcs = false;
    config.spellHasNotAProc = false;
    auto procEntry = CreateBasicProcEntry();
    // PROC_FLAG_KILLED should bypass triggered-spell filter
    EXPECT_FALSE(ProcChanceTestHelper::ShouldBlockTriggeredSpell(
        config, procEntry, PROC_FLAG_KILLED))
        << "PROC_FLAG_KILLED should allow triggered spells";
}
References ProcChanceTestHelper::TriggeredSpellConfig::auraHasCanProcFromProcs, ProcChanceTestHelper::TriggeredSpellConfig::isTriggered, PROC_FLAG_KILLED, ProcChanceTestHelper::ShouldBlockTriggeredSpell(), and ProcChanceTestHelper::TriggeredSpellConfig::spellHasNotAProc.
TEST_F() [10/24]
TEST_F (SpellProcTriggeredFilterTest , KillEvent_AllowsTriggeredSpells)
{
    ProcChanceTestHelper::TriggeredSpellConfig config;
    config.isTriggered = true;
    config.auraHasCanProcFromProcs = false;
    config.spellHasNotAProc = false;
    auto procEntry = CreateBasicProcEntry();
    // PROC_FLAG_KILL should bypass triggered-spell filter
    EXPECT_FALSE(ProcChanceTestHelper::ShouldBlockTriggeredSpell(
        config, procEntry, PROC_FLAG_KILL))
        << "PROC_FLAG_KILL should allow triggered spells";
}
References ProcChanceTestHelper::TriggeredSpellConfig::auraHasCanProcFromProcs, ProcChanceTestHelper::TriggeredSpellConfig::isTriggered, PROC_FLAG_KILL, ProcChanceTestHelper::ShouldBlockTriggeredSpell(), and ProcChanceTestHelper::TriggeredSpellConfig::spellHasNotAProc.
TEST_F() [11/24]
TEST_F (SpellProcTriggeredFilterTest , KillEvent_SelfLoopStillBlocked)
{
    // Even with kill event exemption, self-loop should still be blocked
    ProcChanceTestHelper::TriggeredSpellConfig config;
    config.isTriggered = true;
    config.triggeredByAuraSpellId = 34949;  // Same as proc aura
    config.procAuraSpellId = 34949;
    auto procEntry = SpellProcEntryBuilder()
        .WithProcFlags(PROC_FLAG_KILL)
        .WithChance(100.0f)
        .Build();
    EXPECT_TRUE(ProcChanceTestHelper::ShouldBlockTriggeredSpell(
        config, procEntry, PROC_FLAG_KILL))
        << "Self-loop should still block even on kill events";
}
References SpellProcEntryBuilder::Build(), ProcChanceTestHelper::TriggeredSpellConfig::isTriggered, PROC_FLAG_KILL, ProcChanceTestHelper::TriggeredSpellConfig::procAuraSpellId, ProcChanceTestHelper::ShouldBlockTriggeredSpell(), ProcChanceTestHelper::TriggeredSpellConfig::triggeredByAuraSpellId, SpellProcEntryBuilder::WithChance(), and SpellProcEntryBuilder::WithProcFlags().
TEST_F() [12/24]
TEST_F (SpellProcTriggeredFilterTest , KillWithOtherFlags_StillAllowsTriggeredSpells)
{
    ProcChanceTestHelper::TriggeredSpellConfig config;
    config.isTriggered = true;
    config.auraHasCanProcFromProcs = false;
    config.spellHasNotAProc = false;
    auto procEntry = CreateBasicProcEntry();
    // PROC_FLAG_KILL combined with other flags should still bypass
    uint32 combinedEvent = PROC_FLAG_KILL | PROC_FLAG_DONE_SPELL_MAGIC_DMG_CLASS_NEG;
    EXPECT_FALSE(ProcChanceTestHelper::ShouldBlockTriggeredSpell(
        config, procEntry, combinedEvent))
        << "PROC_FLAG_KILL combined with other flags should still bypass filter";
}
References ProcChanceTestHelper::TriggeredSpellConfig::auraHasCanProcFromProcs, ProcChanceTestHelper::TriggeredSpellConfig::isTriggered, PROC_FLAG_DONE_SPELL_MAGIC_DMG_CLASS_NEG, PROC_FLAG_KILL, ProcChanceTestHelper::ShouldBlockTriggeredSpell(), and ProcChanceTestHelper::TriggeredSpellConfig::spellHasNotAProc.
TEST_F() [13/24]
TEST_F (SpellProcTriggeredFilterTest , NonTriggeredSpell_AllowedByDefault)
{
    ProcChanceTestHelper::TriggeredSpellConfig config;
    config.isTriggered = false;  // Not triggered
    config.auraHasCanProcFromProcs = false;
    config.spellHasNotAProc = false;
    auto procEntry = CreateBasicProcEntry();
    // Should be allowed
    EXPECT_FALSE(ProcChanceTestHelper::ShouldBlockTriggeredSpell(
        config, procEntry, PROC_FLAG_DONE_SPELL_MAGIC_DMG_CLASS_NEG))
        << "Non-triggered spell should be allowed";
}
References ProcChanceTestHelper::TriggeredSpellConfig::auraHasCanProcFromProcs, ProcChanceTestHelper::TriggeredSpellConfig::isTriggered, PROC_FLAG_DONE_SPELL_MAGIC_DMG_CLASS_NEG, ProcChanceTestHelper::ShouldBlockTriggeredSpell(), and ProcChanceTestHelper::TriggeredSpellConfig::spellHasNotAProc.
TEST_F() [14/24]
TEST_F (SpellProcTriggeredFilterTest , NotAProc_AllowsTriggeredSpell)
{
    ProcChanceTestHelper::TriggeredSpellConfig config;
    config.isTriggered = true;
    config.auraHasCanProcFromProcs = false;
    config.spellHasNotAProc = true;  // Exception: spell has SPELL_ATTR3_NOT_A_PROC
    auto procEntry = CreateBasicProcEntry();
    // Should be allowed due to spell attribute
    EXPECT_FALSE(ProcChanceTestHelper::ShouldBlockTriggeredSpell(
        config, procEntry, PROC_FLAG_DONE_SPELL_MAGIC_DMG_CLASS_NEG))
        << "SPELL_ATTR3_NOT_A_PROC should allow triggered spell";
}
References ProcChanceTestHelper::TriggeredSpellConfig::auraHasCanProcFromProcs, ProcChanceTestHelper::TriggeredSpellConfig::isTriggered, PROC_FLAG_DONE_SPELL_MAGIC_DMG_CLASS_NEG, ProcChanceTestHelper::ShouldBlockTriggeredSpell(), and ProcChanceTestHelper::TriggeredSpellConfig::spellHasNotAProc.
TEST_F() [15/24]
TEST_F (SpellProcTriggeredFilterTest , Scenario_HotStreak_TriggeredPyroblast)
{
    // Hot Streak (48108) allows triggered Pyroblast to not proc it again
    ProcChanceTestHelper::TriggeredSpellConfig config;
    config.isTriggered = true;                 // Pyroblast was triggered by Hot Streak
    config.triggeredByAuraSpellId = 48108;     // Hot Streak
    config.procAuraSpellId = 48108;            // Hot Streak is checking if it should proc
    auto procEntry = CreateBasicProcEntry();
    // Self-loop: Hot Streak can't proc from spell it triggered
    EXPECT_TRUE(ProcChanceTestHelper::ShouldBlockTriggeredSpell(
        config, procEntry, PROC_FLAG_DONE_SPELL_MAGIC_DMG_CLASS_NEG))
        << "Hot Streak triggered Pyroblast should not proc Hot Streak";
}
References ProcChanceTestHelper::TriggeredSpellConfig::isTriggered, PROC_FLAG_DONE_SPELL_MAGIC_DMG_CLASS_NEG, ProcChanceTestHelper::TriggeredSpellConfig::procAuraSpellId, ProcChanceTestHelper::ShouldBlockTriggeredSpell(), and ProcChanceTestHelper::TriggeredSpellConfig::triggeredByAuraSpellId.
TEST_F() [16/24]
TEST_F (SpellProcTriggeredFilterTest , Scenario_RapidKilling_AutoShotKill)
{
    // Rapid Killing (34949) has PROC_FLAG_KILL
    // Auto Shot (75) repeated casts are IsTriggered=true
    // Kill event should proc Rapid Killing regardless
    ProcChanceTestHelper::TriggeredSpellConfig config;
    config.isTriggered = true;                 // Auto Shot is triggered
    config.auraHasCanProcFromProcs = false;    // Rapid Killing doesn't have this
    config.spellHasNotAProc = false;           // Auto Shot doesn't have NOT_A_PROC
    auto procEntry = SpellProcEntryBuilder()
        .WithProcFlags(PROC_FLAG_KILL)
        .WithChance(100.0f)
        .Build();
    // PROC_FLAG_KILL exemption should allow this
    EXPECT_FALSE(ProcChanceTestHelper::ShouldBlockTriggeredSpell(
        config, procEntry, PROC_FLAG_KILL))
        << "Rapid Killing should proc from Auto Shot kill";
}
References ProcChanceTestHelper::TriggeredSpellConfig::auraHasCanProcFromProcs, SpellProcEntryBuilder::Build(), ProcChanceTestHelper::TriggeredSpellConfig::isTriggered, PROC_FLAG_KILL, ProcChanceTestHelper::ShouldBlockTriggeredSpell(), ProcChanceTestHelper::TriggeredSpellConfig::spellHasNotAProc, SpellProcEntryBuilder::WithChance(), and SpellProcEntryBuilder::WithProcFlags().
TEST_F() [17/24]
TEST_F (SpellProcTriggeredFilterTest , Scenario_SwordSpec_ChainProcs)
{
    // Sword Specialization with TRIGGERED_CAN_PROC
    ProcChanceTestHelper::TriggeredSpellConfig config;
    config.isTriggered = true;
    config.auraHasCanProcFromProcs = false;
    config.triggeredByAuraSpellId = 12345;  // Some other proc
    config.procAuraSpellId = 16459;         // Sword Specialization
    auto procEntry = SpellProcEntryBuilder()
        .WithProcFlags(PROC_FLAG_DONE_MELEE_AUTO_ATTACK)
        .WithAttributesMask(PROC_ATTR_TRIGGERED_CAN_PROC)
        .WithChance(5.0f)
        .Build();
    // TRIGGERED_CAN_PROC allows chain procs (but not self-loops)
    EXPECT_FALSE(ProcChanceTestHelper::ShouldBlockTriggeredSpell(
        config, procEntry, PROC_FLAG_DONE_MELEE_AUTO_ATTACK))
        << "Sword Spec with TRIGGERED_CAN_PROC should allow chain procs";
}
References ProcChanceTestHelper::TriggeredSpellConfig::auraHasCanProcFromProcs, SpellProcEntryBuilder::Build(), ProcChanceTestHelper::TriggeredSpellConfig::isTriggered, PROC_ATTR_TRIGGERED_CAN_PROC, PROC_FLAG_DONE_MELEE_AUTO_ATTACK, ProcChanceTestHelper::TriggeredSpellConfig::procAuraSpellId, ProcChanceTestHelper::ShouldBlockTriggeredSpell(), ProcChanceTestHelper::TriggeredSpellConfig::triggeredByAuraSpellId, SpellProcEntryBuilder::WithAttributesMask(), SpellProcEntryBuilder::WithChance(), and SpellProcEntryBuilder::WithProcFlags().
TEST_F() [18/24]
TEST_F (SpellProcTriggeredFilterTest , Scenario_WindfuryWeapon_AutoAttack)
{
    // Windfury Weapon procs from auto-attacks, which are allowed for triggered spells
    ProcChanceTestHelper::TriggeredSpellConfig config;
    config.isTriggered = true;  // Windfury extra attacks are triggered
    config.auraHasCanProcFromProcs = false;
    auto procEntry = SpellProcEntryBuilder()
        .WithProcFlags(PROC_FLAG_DONE_MELEE_AUTO_ATTACK)
        .WithProcsPerMinute(2.0f)
        .Build();
    // Auto-attack exception allows triggered Windfury attacks
    EXPECT_FALSE(ProcChanceTestHelper::ShouldBlockTriggeredSpell(
        config, procEntry, PROC_FLAG_DONE_MELEE_AUTO_ATTACK))
        << "Windfury triggered attacks should be allowed (auto-attack exception)";
}
References ProcChanceTestHelper::TriggeredSpellConfig::auraHasCanProcFromProcs, SpellProcEntryBuilder::Build(), ProcChanceTestHelper::TriggeredSpellConfig::isTriggered, PROC_FLAG_DONE_MELEE_AUTO_ATTACK, ProcChanceTestHelper::ShouldBlockTriggeredSpell(), SpellProcEntryBuilder::WithProcFlags(), and SpellProcEntryBuilder::WithProcsPerMinute().
TEST_F() [19/24]
TEST_F (SpellProcTriggeredFilterTest , SelfLoop_AllowsWhenNotTriggered)
{
    ProcChanceTestHelper::TriggeredSpellConfig config;
    config.isTriggered = false;  // Not a triggered spell
    config.triggeredByAuraSpellId = 0;
    config.procAuraSpellId = 12345;
    auto procEntry = CreateBasicProcEntry();
    // Non-triggered spell should be allowed
    EXPECT_FALSE(ProcChanceTestHelper::ShouldBlockTriggeredSpell(
        config, procEntry, PROC_FLAG_DONE_SPELL_MAGIC_DMG_CLASS_NEG))
        << "Non-triggered spell should allow proc";
}
References ProcChanceTestHelper::TriggeredSpellConfig::isTriggered, PROC_FLAG_DONE_SPELL_MAGIC_DMG_CLASS_NEG, ProcChanceTestHelper::TriggeredSpellConfig::procAuraSpellId, ProcChanceTestHelper::ShouldBlockTriggeredSpell(), and ProcChanceTestHelper::TriggeredSpellConfig::triggeredByAuraSpellId.
TEST_F() [20/24]
TEST_F (SpellProcTriggeredFilterTest , SelfLoop_AllowsWhenTriggeredByDifferentAura)
{
    ProcChanceTestHelper::TriggeredSpellConfig config;
    config.isTriggered = true;
    config.triggeredByAuraSpellId = 12345;  // Different from proc aura
    config.procAuraSpellId = 67890;
    config.auraHasCanProcFromProcs = true;  // Allow triggered spells
    auto procEntry = CreateBasicProcEntry();
    // Different aura should be allowed
    EXPECT_FALSE(ProcChanceTestHelper::ShouldBlockTriggeredSpell(
        config, procEntry, PROC_FLAG_DONE_SPELL_MAGIC_DMG_CLASS_NEG))
        << "Different aura trigger should allow proc";
}
References ProcChanceTestHelper::TriggeredSpellConfig::auraHasCanProcFromProcs, ProcChanceTestHelper::TriggeredSpellConfig::isTriggered, PROC_FLAG_DONE_SPELL_MAGIC_DMG_CLASS_NEG, ProcChanceTestHelper::TriggeredSpellConfig::procAuraSpellId, ProcChanceTestHelper::ShouldBlockTriggeredSpell(), and ProcChanceTestHelper::TriggeredSpellConfig::triggeredByAuraSpellId.
TEST_F() [21/24]
TEST_F (SpellProcTriggeredFilterTest , SelfLoop_BlocksWhenTriggeredBySameAura)
{
    ProcChanceTestHelper::TriggeredSpellConfig config;
    config.isTriggered = true;
    config.triggeredByAuraSpellId = 12345;  // Same as proc aura
    config.procAuraSpellId = 12345;
    auto procEntry = CreateBasicProcEntry();
    // Self-loop should be blocked
    EXPECT_TRUE(ProcChanceTestHelper::ShouldBlockTriggeredSpell(
        config, procEntry, PROC_FLAG_DONE_SPELL_MAGIC_DMG_CLASS_NEG))
        << "Self-loop should block proc";
}
References ProcChanceTestHelper::TriggeredSpellConfig::isTriggered, PROC_FLAG_DONE_SPELL_MAGIC_DMG_CLASS_NEG, ProcChanceTestHelper::TriggeredSpellConfig::procAuraSpellId, ProcChanceTestHelper::ShouldBlockTriggeredSpell(), and ProcChanceTestHelper::TriggeredSpellConfig::triggeredByAuraSpellId.
TEST_F() [22/24]
TEST_F (SpellProcTriggeredFilterTest , TakenAutoAttack_AllowsTriggeredSpells)
{
    ProcChanceTestHelper::TriggeredSpellConfig config;
    config.isTriggered = true;
    config.auraHasCanProcFromProcs = false;
    config.spellHasNotAProc = false;
    auto procEntry = CreateBasicProcEntry();
    // Taken melee auto-attack
    uint32 takenMeleeEvent = PROC_FLAG_TAKEN_MELEE_AUTO_ATTACK;
    EXPECT_FALSE(ProcChanceTestHelper::ShouldBlockTriggeredSpell(
        config, procEntry, takenMeleeEvent))
        << "TAKEN_MELEE_AUTO_ATTACK should allow triggered spells";
}
References ProcChanceTestHelper::TriggeredSpellConfig::auraHasCanProcFromProcs, ProcChanceTestHelper::TriggeredSpellConfig::isTriggered, PROC_FLAG_TAKEN_MELEE_AUTO_ATTACK, ProcChanceTestHelper::ShouldBlockTriggeredSpell(), and ProcChanceTestHelper::TriggeredSpellConfig::spellHasNotAProc.
TEST_F() [23/24]
TEST_F (SpellProcTriggeredFilterTest , TriggeredCanProcAttribute_AllowsTriggeredSpells)
{
    ProcChanceTestHelper::TriggeredSpellConfig config;
    config.isTriggered = true;
    config.auraHasCanProcFromProcs = false;
    config.spellHasNotAProc = false;
    // Set TRIGGERED_CAN_PROC attribute
    auto procEntry = SpellProcEntryBuilder()
        .WithProcFlags(PROC_FLAG_DONE_SPELL_MAGIC_DMG_CLASS_NEG)
        .WithAttributesMask(PROC_ATTR_TRIGGERED_CAN_PROC)
        .WithChance(100.0f)
        .Build();
    // Should be allowed due to proc entry attribute
    EXPECT_FALSE(ProcChanceTestHelper::ShouldBlockTriggeredSpell(
        config, procEntry, PROC_FLAG_DONE_SPELL_MAGIC_DMG_CLASS_NEG))
        << "PROC_ATTR_TRIGGERED_CAN_PROC should allow triggered spells";
}
References ProcChanceTestHelper::TriggeredSpellConfig::auraHasCanProcFromProcs, SpellProcEntryBuilder::Build(), ProcChanceTestHelper::TriggeredSpellConfig::isTriggered, PROC_ATTR_TRIGGERED_CAN_PROC, PROC_FLAG_DONE_SPELL_MAGIC_DMG_CLASS_NEG, ProcChanceTestHelper::ShouldBlockTriggeredSpell(), ProcChanceTestHelper::TriggeredSpellConfig::spellHasNotAProc, SpellProcEntryBuilder::WithAttributesMask(), SpellProcEntryBuilder::WithChance(), and SpellProcEntryBuilder::WithProcFlags().
TEST_F() [24/24]
TEST_F (SpellProcTriggeredFilterTest , TriggeredSpell_BlockedByDefault)
{
    ProcChanceTestHelper::TriggeredSpellConfig config;
    config.isTriggered = true;
    config.auraHasCanProcFromProcs = false;
    config.spellHasNotAProc = false;
    // No TRIGGERED_CAN_PROC attribute
    auto procEntry = CreateBasicProcEntry();
    // Should be blocked - no exceptions apply
    EXPECT_TRUE(ProcChanceTestHelper::ShouldBlockTriggeredSpell(
        config, procEntry, PROC_FLAG_DONE_SPELL_MAGIC_DMG_CLASS_NEG))
        << "Triggered spell should be blocked by default";
}
References ProcChanceTestHelper::TriggeredSpellConfig::auraHasCanProcFromProcs, ProcChanceTestHelper::TriggeredSpellConfig::isTriggered, PROC_FLAG_DONE_SPELL_MAGIC_DMG_CLASS_NEG, ProcChanceTestHelper::ShouldBlockTriggeredSpell(), and ProcChanceTestHelper::TriggeredSpellConfig::spellHasNotAProc.