AzerothCore Doxygen
npc_hor_lich_king Struct Reference
Public Member Functions
npc_hor_lich_king (Creature *creature)
void Reset () override
void DoAction (int32 action) override
void WallCompleted ()
void MovementInform (uint32 type, uint32) override
void JustSummoned (Creature *s) override
void SummonedCreatureDies (Creature *, Unit *) override
void SummonedCreatureDespawn (Creature *s) override
void SpellHitTarget (Unit *target, SpellInfo const *spell) override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
Public Member Functions inherited from NullCreatureAI
NullCreatureAI (Creature *c)
void MoveInLineOfSight (Unit *) override
void AttackStart (Unit *) override
void JustStartedThreateningMe (Unit *) override
void JustEnteredCombat (Unit *) override
Called when the unit enters combat.
void UpdateAI (uint32) override
Use to start attacking a target. Called just before JustEngagedWith()
void EnterEvadeMode (EvadeReason) override
void OnCharmed (bool) override
Called when unit is charmed.
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0ms)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
bool IsEngaged () const
Check if creature is currently engaged in combat.
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual bool IsEscortNPC (bool=true) const
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged - this happens after JustEnteredCombat.
void EngagementStart (Unit *who)
void EngagementOver ()
void JustExitedCombat () override
Called when the unit leaves combat.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void OnSpellStart (SpellInfo const *)
virtual void OnSpellCast (SpellInfo const *)
virtual void OnSpellFailed (SpellInfo const *)
virtual void OnChannelFinished (SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void PathEndReached (uint32)
virtual void WaypointPathStarted (uint32)
== Waypoints system =============================
virtual void WaypointStarted (uint32, uint32)
virtual void WaypointReached (uint32, uint32)
virtual void WaypointPathEnded (uint32, uint32)
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *attacker)
virtual void OwnerAttacked (Unit *target)
void OnOwnerCombatInteraction (Unit *target)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
int32 VisualizeBoundary (uint32 duration, Unit *owner=nullptr, bool fill=false, bool checkZ=false) const
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
virtual void DistancingStarted ()
virtual void DistancingEnded ()
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid const &, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void EvadeTimerExpired ()
Called when evade timer expires (target unreachable for too long)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Public Attributes
InstanceScript * instance
EventMap events
SummonList summons
uint8 currentWall
uint8 summonsCount
uint8 div2
Additional Inherited Members
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from NullCreatureAI
static int32 Permissible (Creature const *creature)
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
bool _isEngaged
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
npc_hor_lich_king()
npc_hor_lich_king::npc_hor_lich_king (Creature * creature) inline
                                          : NullCreatureAI(creature), summons(me)
    {
        instance = me->GetInstanceScript();
        if (!instance)
            me->IsAIEnabled = false;
    }
References WorldObject::GetInstanceScript(), instance, Unit::IsAIEnabled, and CreatureAI::me.
Member Function Documentation
DoAction()
void npc_hor_lich_king::DoAction (int32 action) inline override virtual
Reimplemented from UnitAI.
    {
        if (action == ACTION_START_LK_FIGHT_REAL)
            events.ScheduleEvent(EVENT_LK_START_FOLLOWING, 1500ms);
    }
References ACTION_START_LK_FIGHT_REAL, and EVENT_LK_START_FOLLOWING.
JustSummoned()
void npc_hor_lich_king::JustSummoned (Creature * s) inline override virtual
Reimplemented from CreatureAI.
    {
        ++summonsCount;
        summons.Summon(s);
        s->SetHomePosition(PathWaypoints[WP_STOP[currentWall + 1]]);
        s->GetMotionMaster()->MovePoint(0, PathWaypoints[WP_STOP[currentWall + 1]]);
        s->SetInCombatWithZone();
        if (Unit* target = s->SelectNearestPlayer(350.0f))
        {
            s->AddThreat(target, 1000.0f);
            s->AI()->AttackStart(target);
        }
        s->SetHomePosition(PathWaypoints[WP_STOP[currentWall + 1]]);
    }
References Unit::AddThreat(), Creature::AI(), UnitAI::AttackStart(), currentWall, Unit::GetMotionMaster(), MotionMaster::MovePoint(), PathWaypoints, WorldObject::SelectNearestPlayer(), Creature::SetHomePosition(), Creature::SetInCombatWithZone(), SummonList::Summon(), summons, summonsCount, and WP_STOP.
MovementInform()
void npc_hor_lich_king::MovementInform (uint32 type, uint32) inline override virtual
Reimplemented from CreatureAI.
    {
        // Xinef: dont use 0, it is no longer the last point
        // Xinef: if type is escort and spline is finalized, it means that we reached last point from the path
        if (type == ESCORT_MOTION_TYPE && me->movespline->Finalized())
        {
            if (currentWall == 0)
            {
                Talk(SAY_LK_IW_1);
                me->SetOrientation(4.15f);
                if (Creature* icewall = instance->instance->GetCreature(instance->GetGuidData(NPC_ICE_WALL_TARGET)))
                {
                    me->SetFacingToObject(icewall);
                    me->CastSpell(icewall, SPELL_SUMMON_ICE_WALL);
                    events.ScheduleEvent(EVENT_LK_REMORSELESS_WINTER, 4s);
                }
            }
            else if (currentWall == 4)
            {
                Talk(SAY_LK_NOWHERE_TO_RUN);
                instance->SetBossState(DATA_LICH_KING, DONE);
            }
        }
    }
References Unit::CastSpell(), currentWall, DATA_LICH_KING, DONE, ESCORT_MOTION_TYPE, EVENT_LK_REMORSELESS_WINTER, Movement::MoveSpline::Finalized(), Map::GetCreature(), InstanceScript::GetGuidData(), InstanceScript::instance, instance, CreatureAI::me, Unit::movespline, NPC_ICE_WALL_TARGET, SAY_LK_IW_1, SAY_LK_NOWHERE_TO_RUN, InstanceScript::SetBossState(), Unit::SetFacingToObject(), Position::SetOrientation(), and SPELL_SUMMON_ICE_WALL.
Reset()
void npc_hor_lich_king::Reset () inline override virtual
Reimplemented from UnitAI.
    {
        currentWall = 0;
        summonsCount = 0;
        div2 = 0;
        events.Reset();
        events.RescheduleEvent(EVENT_LK_CHECK_COMBAT, 1s);
    }
References currentWall, div2, EVENT_LK_CHECK_COMBAT, and summonsCount.
SpellHitTarget()
void npc_hor_lich_king::SpellHitTarget (Unit * target, SpellInfo const * spell) inline override virtual
Reimplemented from CreatureAI.
    {
        if (target && target->IsAlive() && spell->Id == SPELL_LICH_KING_ZAP_PLAYER)
            Unit::DealDamage(me, target, 10000);
    }
References Unit::DealDamage(), SpellInfo::Id, Unit::IsAlive(), CreatureAI::me, and SPELL_LICH_KING_ZAP_PLAYER.
SummonedCreatureDespawn()
void npc_hor_lich_king::SummonedCreatureDespawn (Creature * s) inline override virtual
Reimplemented from CreatureAI.
    {
        summons.Despawn(s);
    }
References SummonList::Despawn(), and summons.
SummonedCreatureDies()
void npc_hor_lich_king::SummonedCreatureDies (Creature * , Unit *) inline override virtual
Reimplemented from CreatureAI.
    {
        if (!summonsCount)
            return;
        if (--summonsCount == 0)
            WallCompleted();
    }
References summonsCount, and WallCompleted().
UpdateAI()
void npc_hor_lich_king::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Implements UnitAI.
    {
        if (me->HealthBelowPct(70))
            me->SetHealth(me->GetMaxHealth() * 3 / 4);
        events.Update(diff);
        if (me->IsNonMeleeSpellCast(false, true, true))
            return;
        switch (events.ExecuteEvent())
        {
            case EVENT_LK_CHECK_COMBAT:
                if (me->isActiveObject()) // during fight
                {
                    if (Creature* leader = instance->GetCreature(NPC_SYLVANAS_PART2))
                        if (leader->IsAlive() && leader->GetPositionX() < 5575.0f && me->GetExactDist2d(leader) <= 12.5f && !leader->HasAura(SPELL_HARVEST_SOUL) && me->HasAura(SPELL_REMORSELESS_WINTER))
{
                            me->GetMotionMaster()->MovementExpired();
                            me->StopMoving();
                            summonsCount = 255;
                            leader->InterruptNonMeleeSpells(true);
                            me->CastSpell(leader, SPELL_HARVEST_SOUL);
                            events.ScheduleEvent(EVENT_LK_KILL_LEADER, 3s);
                            events.ScheduleEvent(EVENT_LK_CHECK_COMBAT, 1s);
                            break;
                        }
                    if (instance->instance->HavePlayers())
                    {
                        me->SetInCombatWithZone();
                        ++div2;
                        if (div2 > 1)
{
                            div2 = 0;
                            if (me->HasAura(SPELL_REMORSELESS_WINTER)) // prevent going behind him during fight
{
                                Map::PlayerList const& pl = instance->instance->GetPlayers();
                                for (Map::PlayerList::const_iterator itr = pl.begin(); itr != pl.end(); ++itr)
                                    if (Player* p = itr->GetSource())
                                        if (!p->IsGameMaster() && p->IsAlive() && (p->GetPositionX() - me->GetPositionX() + p->GetPositionY() - me->GetPositionY()) > 20.0f)
                                            me->CastSpell(p, SPELL_LICH_KING_ZAP_PLAYER, true);
                            }
                        }
                    }
                    else
                    {
                        summons.DespawnAll();
                        instance->SetData(ACTION_STOP_LK_FIGHT, 1);
                    }
                }
                events.ScheduleEvent(EVENT_LK_CHECK_COMBAT, 1s);
                break;
            case EVENT_LK_KILL_LEADER:
                if (Creature* leader = instance->GetCreature(NPC_SYLVANAS_PART2))
                {
                    leader->CastSpell(leader, SPELL_HOR_SUICIDE, true);
                    Unit::Kill(me, leader);
                    me->InterruptNonMeleeSpells(true);
                    DoCastAOE(SPELL_FURY_OF_FROSTMOURNE);
                }
                break;
            case EVENT_LK_START_FOLLOWING:
                {
                    me->SetSpeed(MOVE_RUN, 9.0f / 7.0f);
                    Movement::PointsArray path;
                    path.emplace_back(me->GetPositionX(), me->GetPositionY(), me->GetPositionZ());
                    for (uint8 i = 0; i <= 2; ++i)
                        path.emplace_back(PathWaypoints[i].GetPositionX(), PathWaypoints[i].GetPositionY(), PathWaypoints[i].GetPositionZ());
                    me->GetMotionMaster()->MoveSplinePath(&path);
                }
                break;
            case EVENT_LK_REMORSELESS_WINTER:
                {
                    me->SetSpeed(MOVE_RUN, me->GetCreatureTemplate()->speed_run);
                    Talk(SAY_LK_WINTER);
                    DoCastSelf(SPELL_REMORSELESS_WINTER, true);
                    Movement::PointsArray path;
                    path.emplace_back(me->GetPositionX(), me->GetPositionY(), me->GetPositionZ());
                    for (uint8 i = 3; i < PATH_WP_COUNT - 1; ++i)
                        path.emplace_back(PathWaypoints[i].GetPositionX(), PathWaypoints[i].GetPositionY(), PathWaypoints[i].GetPositionZ());
                    me->GetMotionMaster()->MoveSplinePath(&path);
                    me->GetMotionMaster()->propagateSpeedChange();
                    events.ScheduleEvent(EVENT_LK_SUMMON, 1s);
                }
                break;
            case EVENT_LK_SUMMON:
                switch (currentWall)
                {
                    case 0:
                        events.ScheduleEvent(EVENT_LK_SUMMON_GHOULS, 0ms);
                        events.ScheduleEvent(EVENT_LK_SUMMON_RWD, 4s);
                        break;
                    case 1:
                        events.ScheduleEvent(EVENT_LK_SUMMON_LA, 0ms);
                        events.ScheduleEvent(EVENT_LK_SUMMON_GHOULS, 100ms);
                        events.ScheduleEvent(EVENT_LK_SUMMON_RWD, 4s);
                        events.ScheduleEvent(EVENT_LK_SUMMON_RWD, 5100ms);
                        break;
                    case 2:
                        events.ScheduleEvent(EVENT_LK_SUMMON_LA, 0ms);
                        events.ScheduleEvent(EVENT_LK_SUMMON_GHOULS, 100ms);
                        events.ScheduleEvent(EVENT_LK_SUMMON_LA, 4s);
                        events.ScheduleEvent(EVENT_LK_SUMMON_RWD, 4100ms);
                        events.ScheduleEvent(EVENT_LK_SUMMON_RWD, 5200ms);
                        break;
                    case 3:
                        events.ScheduleEvent(EVENT_LK_SUMMON_LA, 0ms);
                        events.ScheduleEvent(EVENT_LK_SUMMON_RWD, 100ms);
                        events.ScheduleEvent(EVENT_LK_SUMMON_GHOULS, 1200ms);
                        events.ScheduleEvent(EVENT_LK_SUMMON_RWD, 5300ms);
                        events.ScheduleEvent(EVENT_LK_SUMMON_RWD, 6400ms);
                        events.ScheduleEvent(EVENT_LK_SUMMON_GHOULS, 12s + 500ms);
                        events.ScheduleEvent(EVENT_LK_SUMMON_LA, 16s + 500ms);
                        events.ScheduleEvent(EVENT_LK_SUMMON_RWD, 16s + 600ms);
                        events.ScheduleEvent(EVENT_LK_SUMMON_LA, 17s + 700ms);
                        break;
                }
                break;
            case EVENT_LK_SUMMON_GHOULS:
                DoCastAOE(SPELL_SUMMON_RAGING_GHOULS);
                break;
            case EVENT_LK_SUMMON_RWD:
                DoCastAOE(SPELL_SUMMON_RISEN_WITCH_DOCTOR);
                break;
            case EVENT_LK_SUMMON_LA:
                DoCastAOE(SPELL_SUMMON_LUMBERING_ABOMINATION);
                break;
            case EVENT_LK_SUMMON_NEXT_ICE_WALL:
                Talk(SAY_LK_IW_1 + currentWall);
                if (Creature* c = instance->instance->GetCreature(instance->GetGuidData(NPC_ICE_WALL_TARGET + currentWall)))
                    me->CastSpell(c, SPELL_SUMMON_ICE_WALL);
                break;
        }
    }
References ACTION_STOP_LK_FIGHT, MapRefMgr::begin(), Unit::CastSpell(), currentWall, SummonList::DespawnAll(), div2, UnitAI::DoCastAOE(), UnitAI::DoCastSelf(), MapRefMgr::end(), EVENT_LK_CHECK_COMBAT, EVENT_LK_KILL_LEADER, EVENT_LK_REMORSELESS_WINTER, EVENT_LK_START_FOLLOWING, EVENT_LK_SUMMON, EVENT_LK_SUMMON_GHOULS, EVENT_LK_SUMMON_LA, EVENT_LK_SUMMON_NEXT_ICE_WALL, EVENT_LK_SUMMON_RWD, Map::GetCreature(), InstanceScript::GetCreature(), Creature::GetCreatureTemplate(), Position::GetExactDist2d(), InstanceScript::GetGuidData(), Unit::GetMaxHealth(), Unit::GetMotionMaster(), Map::GetPlayers(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Unit::HasAura(), Map::HavePlayers(), Unit::HealthBelowPct(), InstanceScript::instance, instance, Unit::InterruptNonMeleeSpells(), WorldObject::isActiveObject(), Unit::IsNonMeleeSpellCast(), Unit::Kill(), CreatureAI::me, MOVE_RUN, MotionMaster::MovementExpired(), MotionMaster::MoveSplinePath(), NPC_ICE_WALL_TARGET, NPC_SYLVANAS_PART2, PATH_WP_COUNT, PathWaypoints, MotionMaster::propagateSpeedChange(), SAY_LK_IW_1, SAY_LK_WINTER, ZoneScript::SetData(), Unit::SetHealth(), Creature::SetInCombatWithZone(), Unit::SetSpeed(), CreatureTemplate::speed_run, SPELL_FURY_OF_FROSTMOURNE, SPELL_HARVEST_SOUL, SPELL_HOR_SUICIDE, SPELL_LICH_KING_ZAP_PLAYER, SPELL_REMORSELESS_WINTER, SPELL_SUMMON_ICE_WALL, SPELL_SUMMON_LUMBERING_ABOMINATION, SPELL_SUMMON_RAGING_GHOULS, SPELL_SUMMON_RISEN_WITCH_DOCTOR, Unit::StopMoving(), summons, and summonsCount.
WallCompleted()
void npc_hor_lich_king::WallCompleted () inline
    {
        ++currentWall;
        instance->SetData(ACTION_DELETE_ICE_WALL, 1);
        if (currentWall <= 3)
        {
            events.ScheduleEvent(EVENT_LK_SUMMON_NEXT_ICE_WALL, 1s);
            events.ScheduleEvent(EVENT_LK_SUMMON, currentWall == 3 ? 11s : 7500ms);
        }
        else
            me->RemoveAura(SPELL_REMORSELESS_WINTER);
        if (Creature* c = instance->GetCreature(NPC_SYLVANAS_PART2))
            c->AI()->DoAction(ACTION_INFORM_WALL_DESTROYED);
    }
References ACTION_DELETE_ICE_WALL, ACTION_INFORM_WALL_DESTROYED, currentWall, EVENT_LK_SUMMON, EVENT_LK_SUMMON_NEXT_ICE_WALL, InstanceScript::GetCreature(), instance, CreatureAI::me, NPC_SYLVANAS_PART2, Unit::RemoveAura(), ZoneScript::SetData(), and SPELL_REMORSELESS_WINTER.
Referenced by SummonedCreatureDies().
Member Data Documentation
currentWall
uint8 npc_hor_lich_king::currentWall
Referenced by JustSummoned(), MovementInform(), Reset(), UpdateAI(), and WallCompleted().
div2
uint8 npc_hor_lich_king::div2
Referenced by Reset(), and UpdateAI().
events
EventMap npc_hor_lich_king::events
instance
InstanceScript* npc_hor_lich_king::instance
Referenced by MovementInform(), npc_hor_lich_king(), UpdateAI(), and WallCompleted().
summons
SummonList npc_hor_lich_king::summons
Referenced by JustSummoned(), SummonedCreatureDespawn(), and UpdateAI().
summonsCount
uint8 npc_hor_lich_king::summonsCount
Referenced by JustSummoned(), Reset(), SummonedCreatureDies(), and UpdateAI().
The documentation for this struct was generated from the following file:
azerothcore-wotlk/src/server/scripts/Northrend/FrozenHalls/HallsOfReflection/halls_of_reflection.cpp