AzerothCore Doxygen
hash_helper Class Reference
#include "BindingMap.h"
Public Types
typedef std::size_t result_type
Static Public Member Functions
template<typename T1 , typename T2 , typename... T>
static result_type hash (T1 const &t1, T2 const &t2, T const &... t)
template<typename T , typename std::enable_if< std::is_enum< T >::value >::type * = nullptr>
static result_type hash (T const &t)
template<typename T , typename std::enable_if<!std::is_enum< T >::value >::type * = nullptr>
static result_type hash (T const &t)
Static Private Member Functions
template<typename T >
static void _hash_combine (result_type &seed, T const &v)
template<typename H , typename T1 , typename... T>
static void _hash_combine (result_type &seed, H const &h, T1 const &t1, T const &... t)
Detailed Description
Member Typedef Documentation
result_type
typedef std::size_t hash_helper::result_type
Member Function Documentation
_hash_combine() [1/2]
template<typename H , typename T1 , typename... T> static void hash_helper::_hash_combine (result_type & seed, H const & h, T1 const & t1, T const &... t) inline static private
    {
        _hash_combine(seed, h);
        _hash_combine(seed, t1, t...);
    }
References _hash_combine().
_hash_combine() [2/2]
template<typename T > static void hash_helper::_hash_combine (result_type & seed, T const & v) inline static private
    {
        // from http://www.boost.org/doc/libs/1_40_0/boost/functional/hash/hash.hpp
        seed ^= hash(v) + 0x9e3779b9 + (seed << 6) + (seed >> 2);
    }
References hash().
Referenced by _hash_combine(), and hash().
hash() [1/3]
template<typename T , typename std::enable_if< std::is_enum< T >::value >::type * = nullptr> static result_type hash_helper::hash (T const & t) inline static
    {
        return std::hash<typename std::underlying_type<T>::type>()(t);
    }
hash() [2/3]
template<typename T , typename std::enable_if<!std::is_enum< T >::value >::type * = nullptr> static result_type hash_helper::hash (T const & t) inline static
    {
        return std::hash<T>()(t);
    }
hash() [3/3]
template<typename T1 , typename T2 , typename... T> static result_type hash_helper::hash (T1 const & t1, T2 const & t2, T const &... t) inline static
    {
        result_type seed = 0;
        _hash_combine(seed, t1, t2, t...);
        return seed;
    }
References _hash_combine().
Referenced by _hash_combine(), std::hash< EventKey< T > >::operator()(), std::hash< EntryKey< T > >::operator()(), and std::hash< UniqueObjectKey< T > >::operator()().
The documentation for this class was generated from the following file:
mod-eluna/src/LuaEngine/BindingMap.h