AzerothCore Doxygen
RaceMgr Class Reference
#include "RaceMgr.h"
Static Public Member Functions
static RaceMgr * instance ()
static void LoadRaces ()
static uint8 GetMaxRaces ()
static void SetMaxRaces (uint8 max)
static uint32 GetPlayableRaceMask ()
static uint32 GetAllianceRaceMask ()
static uint32 GetHordeRaceMask ()
Private Member Functions
RaceMgr ()
~RaceMgr ()
Static Private Attributes
static uint8 _maxRaces = 0
static uint32 _playableRaceMask = 0
static uint32 _allianceRaceMask = 0
static uint32 _hordeRaceMask = 0
Detailed Description
Constructor & Destructor Documentation
RaceMgr()
RaceMgr::RaceMgr () private
{
}
~RaceMgr()
RaceMgr::~RaceMgr () private
{
}
Member Function Documentation
GetAllianceRaceMask()
static uint32 RaceMgr::GetAllianceRaceMask () inline static
{ return _allianceRaceMask; }
References _allianceRaceMask.
GetHordeRaceMask()
static uint32 RaceMgr::GetHordeRaceMask () inline static
{ return _hordeRaceMask; }
References _hordeRaceMask.
GetMaxRaces()
static uint8 RaceMgr::GetMaxRaces () inline static
{ return _maxRaces; }
References _maxRaces.
Referenced by LoadRaces().
GetPlayableRaceMask()
static uint32 RaceMgr::GetPlayableRaceMask () inline static
{ return _playableRaceMask; }
References _playableRaceMask.
instance()
RaceMgr * RaceMgr::instance () static
{
    static RaceMgr instance;
    return &instance;
}
References instance().
Referenced by instance().
LoadRaces()
void RaceMgr::LoadRaces () static
{
    SetMaxRaces(0 + 1);
    _playableRaceMask = 0;
    _hordeRaceMask    = 0;
    _allianceRaceMask = 0;
    for (auto const& raceEntry : sChrRacesStore)
    {
        if (!raceEntry)
            continue;
        uint8 alliance = raceEntry->alliance;
        uint8 raceId = raceEntry->RaceID;
        if (raceEntry->Flags & CHRRACES_FLAGS_NOT_PLAYABLE)
            continue;
        if (GetMaxRaces() <= raceId)
            SetMaxRaces(raceId + 1);
        uint32 raceBit = (1 << (raceId - 1));
        _playableRaceMask |= raceBit;
        if (alliance == ALLIANCE_HORDE)
            _hordeRaceMask |= raceBit;
        else if (alliance == ALLIANCE_ALLIANCE)
            _allianceRaceMask |= raceBit;
    }
}
References _allianceRaceMask, _hordeRaceMask, _playableRaceMask, ALLIANCE_ALLIANCE, ALLIANCE_HORDE, CHRRACES_FLAGS_NOT_PLAYABLE, GetMaxRaces(), sChrRacesStore, and SetMaxRaces().
SetMaxRaces()
static void RaceMgr::SetMaxRaces (uint8 max) inline static
{ _maxRaces = max; }
References _maxRaces.
Referenced by LoadRaces().
Member Data Documentation
_allianceRaceMask
uint32 RaceMgr::_allianceRaceMask = 0 static private
Referenced by GetAllianceRaceMask(), and LoadRaces().
_hordeRaceMask
uint32 RaceMgr::_hordeRaceMask = 0 static private
Referenced by GetHordeRaceMask(), and LoadRaces().
_maxRaces
uint8 RaceMgr::_maxRaces = 0 static private
Referenced by GetMaxRaces(), and SetMaxRaces().
_playableRaceMask
uint32 RaceMgr::_playableRaceMask = 0 static private
Referenced by GetPlayableRaceMask(), and LoadRaces().
The documentation for this class was generated from the following files:
azerothcore-wotlk/src/server/game/Entities/Player/RaceMgr.h
azerothcore-wotlk/src/server/game/Entities/Player/RaceMgr.cpp