AzerothCore Doxygen
npc_hor_leader_second::npc_hor_leader_secondAI Struct Reference
Public Member Functions
npc_hor_leader_secondAI (Creature *creature)
void Reset () override
void DoAction (int32 actionId) override
void DamageTaken (Unit *, uint32 &dmg, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void MoveToNextStopPoint ()
void MovementInform (uint32 type, uint32) override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
Public Member Functions inherited from NullCreatureAI
NullCreatureAI (Creature *c)
void MoveInLineOfSight (Unit *) override
void AttackStart (Unit *) override
void JustStartedThreateningMe (Unit *) override
void JustEnteredCombat (Unit *) override
Called when the unit enters combat.
void UpdateAI (uint32) override
Use to start attacking a target. Called just before JustEngagedWith()
void EnterEvadeMode (EvadeReason) override
void OnCharmed (bool) override
Called when unit is charmed.
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0ms)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
bool IsEngaged () const
Check if creature is currently engaged in combat.
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual bool IsEscortNPC (bool=true) const
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged - this happens after JustEnteredCombat.
void EngagementStart (Unit *who)
void EngagementOver ()
void JustExitedCombat () override
Called when the unit leaves combat.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void OnSpellStart (SpellInfo const *)
virtual void OnSpellCast (SpellInfo const *)
virtual void OnSpellFailed (SpellInfo const *)
virtual void OnChannelFinished (SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void PathEndReached (uint32)
virtual void WaypointPathStarted (uint32)
== Waypoints system =============================
virtual void WaypointStarted (uint32, uint32)
virtual void WaypointReached (uint32, uint32)
virtual void WaypointPathEnded (uint32, uint32)
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *attacker)
virtual void OwnerAttacked (Unit *target)
void OnOwnerCombatInteraction (Unit *target)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
int32 VisualizeBoundary (uint32 duration, Unit *owner=nullptr, bool fill=false, bool checkZ=false) const
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
virtual void DistancingStarted ()
virtual void DistancingEnded ()
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid const &, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void EvadeTimerExpired ()
Called when evade timer expires (target unreachable for too long)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage to any victim (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Public Attributes
InstanceScript * instance
EventMap events
uint8 currentStopPoint
Additional Inherited Members
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from NullCreatureAI
static int32 Permissible (Creature const *creature)
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
bool _isEngaged
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
npc_hor_leader_secondAI()
npc_hor_leader_second::npc_hor_leader_secondAI::npc_hor_leader_secondAI (Creature * creature) inline
                                                    : NullCreatureAI(creature)
        {
            instance = me->GetInstanceScript();
            if (!instance)
                me->IsAIEnabled = false;
        }
References WorldObject::GetInstanceScript(), instance, Unit::IsAIEnabled, and CreatureAI::me.
Member Function Documentation
DamageTaken()
void npc_hor_leader_second::npc_hor_leader_secondAI::DamageTaken (Unit * , uint32 & , DamageEffectType , SpellSchoolMask) inline override virtual
Called at any Damage from any attacker (before damage apply)
Note
It use for recalculation damage or special reaction at damage for attack reaction use AttackedBy called for non DOT damage in Unit::DealDamage also
Reimplemented from UnitAI.
        {
            if (dmg >= me->GetHealth())
                dmg = me->GetHealth() - 1;
        }
References Unit::GetHealth(), and CreatureAI::me.
DoAction()
void npc_hor_leader_second::npc_hor_leader_secondAI::DoAction (int32 actionId) inline override virtual
Reimplemented from UnitAI.
        {
            switch (actionId)
            {
                case ACTION_START_INTRO:
                    events.ScheduleEvent(EVENT_LK_SAY_AGGRO, 0ms);
                    events.ScheduleEvent(EVENT_LK_BATTLE_1, 2s + 500ms);
                    events.ScheduleEvent(EVENT_LK_BATTLE_2, 3s);
                    events.ScheduleEvent(me->GetEntry() == NPC_JAINA_PART2 ? EVENT_JAINA_IMMOBILIZE_LK : EVENT_SYLVANAS_IMMOBILIZE_JUMP, 9s);
                    break;
                case ACTION_START_LK_FIGHT_REAL:
                    events.ScheduleEvent(EVENT_START_RUN, 0ms);
                    break;
                case ACTION_INFORM_WALL_DESTROYED:
                    MoveToNextStopPoint();
                    if (currentStopPoint == 5)
                        events.ScheduleEvent(EVENT_SAY_OPENING, 3s);
                    break;
            }
        }
References ACTION_INFORM_WALL_DESTROYED, ACTION_START_INTRO, ACTION_START_LK_FIGHT_REAL, currentStopPoint, EVENT_JAINA_IMMOBILIZE_LK, EVENT_LK_BATTLE_1, EVENT_LK_BATTLE_2, EVENT_LK_SAY_AGGRO, EVENT_SAY_OPENING, EVENT_START_RUN, EVENT_SYLVANAS_IMMOBILIZE_JUMP, Object::GetEntry(), CreatureAI::me, MoveToNextStopPoint(), and NPC_JAINA_PART2.
MovementInform()
void npc_hor_leader_second::npc_hor_leader_secondAI::MovementInform (uint32 type, uint32) inline override virtual
Reimplemented from CreatureAI.
        {
            if (type == ESCORT_MOTION_TYPE && me->movespline->Finalized())
                events.ScheduleEvent(EVENT_SAY_LEADER_STOP_TEXT, 1s);
        }
References ESCORT_MOTION_TYPE, EVENT_SAY_LEADER_STOP_TEXT, Movement::MoveSpline::Finalized(), CreatureAI::me, and Unit::movespline.
MoveToNextStopPoint()
void npc_hor_leader_second::npc_hor_leader_secondAI::MoveToNextStopPoint () inline
        {
            me->SetSpeed(MOVE_RUN, me->GetCreatureTemplate()->speed_run);
            me->InterruptNonMeleeSpells(true);
            me->SetSheath(SHEATH_STATE_MELEE);
            ++currentStopPoint;
            me->SetWalk(false);
            Movement::PointsArray path;
            path.emplace_back(me->GetPositionX(), me->GetPositionY(), me->GetPositionZ());
            for (uint8 i = WP_STOP[currentStopPoint - 1] + (currentStopPoint == 1 ? 0 : 1); i <= WP_STOP[currentStopPoint]; ++i)
                path.emplace_back(PathWaypoints[i].GetPositionX(), PathWaypoints[i].GetPositionY(), PathWaypoints[i].GetPositionZ());
            me->GetMotionMaster()->MoveSplinePath(&path, FORCED_MOVEMENT_RUN);
        }
References currentStopPoint, FORCED_MOVEMENT_RUN, Creature::GetCreatureTemplate(), Unit::GetMotionMaster(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Unit::InterruptNonMeleeSpells(), CreatureAI::me, MOVE_RUN, MotionMaster::MoveSplinePath(), PathWaypoints, Unit::SetSheath(), Unit::SetSpeed(), Creature::SetWalk(), SHEATH_STATE_MELEE, CreatureTemplate::speed_run, and WP_STOP.
Referenced by DoAction(), and UpdateAI().
Reset()
void npc_hor_leader_second::npc_hor_leader_secondAI::Reset () inline override virtual
Reimplemented from UnitAI.
        {
            currentStopPoint = 0;
            events.Reset();
        }
References currentStopPoint.
UpdateAI()
void npc_hor_leader_second::npc_hor_leader_secondAI::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Implements UnitAI.
        {
            events.Update(diff);
            switch (events.ExecuteEvent())
            {
                case EVENT_LK_SAY_AGGRO:
                    if (Creature* lichKing = instance->GetCreature(NPC_LICH_KING_BOSS))
                    {
                        me->Attack(lichKing, true),
                        lichKing->AI()->Talk(me->GetEntry() == NPC_JAINA_PART2 ? SAY_LK_AGGRO_ALLY : SAY_LK_AGGRO_HORDE);
                    }
                    break;
                case EVENT_LK_BATTLE_1:
                    if (Creature* lichKing = instance->GetCreature(NPC_LICH_KING_BOSS))
                        lichKing->CastSpell(lichKing, SPELL_SOUL_REAPER);
                    break;
                case EVENT_LK_BATTLE_2:
                    //horda
                    if (Creature* leader = instance->GetCreature(NPC_SYLVANAS_PART2))
                        leader->CastSpell(leader, SPELL_EVASION, true);
                    if (Creature* lichKing = instance->GetCreature(NPC_LICH_KING_BOSS))
                        lichKing->SetFacingToObject(me);
                    if (Creature* lichKing = instance->GetCreature(NPC_LICH_KING_BOSS))
                    {
                        lichKing->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_ONESHOT_ATTACK2HTIGHT);
                        me->SetFacingToObject(lichKing);
                    }
                    break;
                case EVENT_JAINA_IMMOBILIZE_LK:
                    if (Creature* lichKing = instance->GetCreature(NPC_LICH_KING_BOSS))
                    {
                        lichKing->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_STATE_READY_SPELL_OMNI);
                        me->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_ONESHOT_NONE);
                        me->CastSpell(lichKing, SPELL_JAINA_ICE_PRISON);
                        events.ScheduleEvent(EVENT_SAY_LEAVE, 5s);
                    }
                    break;
                case EVENT_SYLVANAS_IMMOBILIZE_JUMP:
                    if (Creature* lichKing = instance->GetCreature(NPC_LICH_KING_BOSS))
                    {
                        me->AttackStop();
                        me->SetSheath(SHEATH_STATE_MELEE);
                        lichKing->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_STATE_READY_SPELL_OMNI);
                        lichKing->CastSpell(me, SPELL_BLIDING_RETREAT);
                        me->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_ONESHOT_NONE);
                        me->KnockbackFrom(lichKing->GetPositionX(), lichKing->GetPositionY(), 34.3f, 4.0f);
                        events.ScheduleEvent(EVENT_SYLVANAS_DARK_BINDING, 2s +500ms);
                    }
                    break;
                case EVENT_SYLVANAS_DARK_BINDING:
                    if (Creature* lichKing = instance->GetCreature(NPC_LICH_KING_BOSS))
                        me->CastSpell(lichKing, SPELL_SYLVANAS_DARK_BINDING);
                    events.ScheduleEvent(EVENT_SAY_LEAVE, 2s);
                    break;
                case EVENT_SAY_LEAVE:
                    {
                        Map::PlayerList const& pl = instance->instance->GetPlayers();
                        for (Map::PlayerList::const_iterator itr = pl.begin(); itr != pl.end(); ++itr)
                            if (Player* p = itr->GetSource())
                                p->KilledMonsterCredit(me->GetEntry()); //for quest
                        Talk(me->GetEntry() == NPC_JAINA_PART2 ? SAY_JAINA_AGGRO : SAY_SYLVANA_AGGRO);
                        me->SetSheath(SHEATH_STATE_MELEE);
                        me->SetWalk(false);
                        me->SetSpeed(MOVE_RUN, me->GetCreatureTemplate()->speed_run);
                        me->GetMotionMaster()->MovePoint(0, LeaderEscapePos);
                        events.ScheduleEvent(EVENT_ADD_GOSSIP, 7s);
                    }
                    break;
                case EVENT_ADD_GOSSIP:
                    me->RemoveAura(me->GetEntry() == NPC_JAINA_PART2 ? SPELL_JAINA_ICE_BARRIER : SPELL_SYLVANAS_CLOAK_OF_DARKNESS);
                    me->SetFacingTo(LeaderEscapePos.GetOrientation());
                    me->SetNpcFlag(UNIT_NPC_FLAG_GOSSIP);
                    break;
                case EVENT_START_RUN:
                    {
                        instance->SetData(ACTION_START_LK_FIGHT, 1);
                        me->setActive(true);
                        MoveToNextStopPoint();
                        if (Creature* lichKing = instance->GetCreature(NPC_LICH_KING_BOSS))
{
                            lichKing->setActive(true);
                            lichKing->SetInCombatWithZone();
                            lichKing->RemoveAura(me->GetEntry() == NPC_JAINA_PART2 ? SPELL_JAINA_ICE_PRISON : SPELL_SYLVANAS_DARK_BINDING);
                            lichKing->AI()->DoAction(ACTION_START_LK_FIGHT_REAL);
                        }
                    }
                    break;
                case EVENT_SAY_LEADER_STOP_TEXT:
                    {
                        int32 textId = 0;
                        switch (currentStopPoint)
{
                            case 1:
                                textId = SAY_SYLVANAS_IW_1;
                                break;
                            case 2:
                                textId = SAY_SYLVANAS_IW_2;
                                break;
                            case 3:
                                textId = SAY_SYLVANAS_IW_3;
                                break;
                            case 4:
                                textId = SAY_SYLVANAS_IW_4;
                                break;
                            case 5:
                                textId = (me->GetEntry() == NPC_JAINA_PART2 ? SAY_JAINA_TRAP : SAY_SYLVANA_TRAP);
                                break;
                        }
                        Talk(textId);
                        if (currentStopPoint <= 4)
                            DoCastAOE(me->GetEntry() == NPC_JAINA_PART2 ? SPELL_DESTROY_WALL_JAINA : SPELL_DESTROY_WALL_SYLVANAS);
                        else
{
                            me->SetFacingTo(PathWaypoints[PATH_WP_COUNT - 1].GetOrientation());
                            me->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_ONESHOT_READY1H);
                        }
                    }
                    break;
                case EVENT_SAY_OPENING:
                    Talk(me->GetEntry() == NPC_JAINA_PART2 ? SAY_JAINA_ESCAPE_01 : SAY_SYLVANA_ESCAPE_01);
                    break;
            }
            DoMeleeAttackIfReady();
        }
References ACTION_START_LK_FIGHT, ACTION_START_LK_FIGHT_REAL, Unit::Attack(), Unit::AttackStop(), MapRefMgr::begin(), Unit::CastSpell(), currentStopPoint, UnitAI::DoCastAOE(), UnitAI::DoMeleeAttackIfReady(), EMOTE_ONESHOT_ATTACK2HTIGHT, EMOTE_ONESHOT_NONE, EMOTE_ONESHOT_READY1H, EMOTE_STATE_READY_SPELL_OMNI, MapRefMgr::end(), EVENT_ADD_GOSSIP, EVENT_JAINA_IMMOBILIZE_LK, EVENT_LK_BATTLE_1, EVENT_LK_BATTLE_2, EVENT_LK_SAY_AGGRO, EVENT_SAY_LEADER_STOP_TEXT, EVENT_SAY_LEAVE, EVENT_SAY_OPENING, EVENT_START_RUN, EVENT_SYLVANAS_DARK_BINDING, EVENT_SYLVANAS_IMMOBILIZE_JUMP, InstanceScript::GetCreature(), Creature::GetCreatureTemplate(), Object::GetEntry(), Unit::GetMotionMaster(), Position::GetOrientation(), Map::GetPlayers(), InstanceScript::instance, instance, Unit::KnockbackFrom(), LeaderEscapePos, CreatureAI::me, MOVE_RUN, MotionMaster::MovePoint(), MoveToNextStopPoint(), NPC_JAINA_PART2, NPC_LICH_KING_BOSS, NPC_SYLVANAS_PART2, PATH_WP_COUNT, PathWaypoints, Unit::RemoveAura(), SAY_JAINA_AGGRO, SAY_JAINA_ESCAPE_01, SAY_JAINA_TRAP, SAY_LK_AGGRO_ALLY, SAY_LK_AGGRO_HORDE, SAY_SYLVANA_AGGRO, SAY_SYLVANA_ESCAPE_01, SAY_SYLVANA_TRAP, SAY_SYLVANAS_IW_1, SAY_SYLVANAS_IW_2, SAY_SYLVANAS_IW_3, SAY_SYLVANAS_IW_4, WorldObject::setActive(), ZoneScript::SetData(), Unit::SetFacingTo(), Unit::SetFacingToObject(), Unit::SetNpcFlag(), Unit::SetSheath(), Unit::SetSpeed(), Unit::SetUInt32Value(), Creature::SetWalk(), SHEATH_STATE_MELEE, CreatureTemplate::speed_run, SPELL_BLIDING_RETREAT, SPELL_DESTROY_WALL_JAINA, SPELL_DESTROY_WALL_SYLVANAS, SPELL_EVASION, SPELL_JAINA_ICE_BARRIER, SPELL_JAINA_ICE_PRISON, SPELL_SOUL_REAPER, SPELL_SYLVANAS_CLOAK_OF_DARKNESS, SPELL_SYLVANAS_DARK_BINDING, UNIT_NPC_EMOTESTATE, and UNIT_NPC_FLAG_GOSSIP.
Member Data Documentation
currentStopPoint
uint8 npc_hor_leader_second::npc_hor_leader_secondAI::currentStopPoint
Referenced by DoAction(), MoveToNextStopPoint(), Reset(), and UpdateAI().
events
EventMap npc_hor_leader_second::npc_hor_leader_secondAI::events
instance
InstanceScript* npc_hor_leader_second::npc_hor_leader_secondAI::instance
Referenced by npc_hor_leader_secondAI(), and UpdateAI().
The documentation for this struct was generated from the following file:
azerothcore-wotlk/src/server/scripts/Northrend/FrozenHalls/HallsOfReflection/halls_of_reflection.cpp