AzerothCore Doxygen
boss_marli.cpp File Reference
#include "CreatureScript.h"
#include "GameObjectAI.h"
#include "ScriptedCreature.h"
#include "SpellScript.h"
#include "SpellScriptLoader.h"
#include "TaskScheduler.h"
#include "zulgurub.h"
Classes
struct boss_marli
struct npc_spawn_of_marli
class spell_hatch_eggs
class spell_enveloping_webs
class spell_marli_transform
Enumerations
enum Says {
SAY_AGGRO = 0 ,
SAY_TRANSFORM = 1 ,
SAY_SPIDER_SPAWN = 2 ,
SAY_DEATH = 3 ,
SAY_TRANSFORM_BACK = 4 ,
EMOTE_FULL_GROWN = 0
}
enum Spells {
SPELL_CHARGE = 22911 ,
SPELL_ENVELOPING_WEB = 24110 ,
SPELL_CORROSIVE_POISON = 24111 ,
SPELL_POISON_SHOCK = 24112 ,
SPELL_POISON_VOLLEY = 24099 ,
SPELL_DRAIN_LIFE = 24300 ,
SPELL_ENLARGE = 24109 ,
SPELL_SPIDER_EGGS = 24082 ,
SPELL_SPIDER_FORM = 24084 ,
SPELL_TRANSFORM_BACK = 24085 ,
SPELL_THRASH = 3391 ,
SPELL_HATCH_SPIDER_EGG = 24082 ,
SPELL_HATCH_EGGS = 24083 ,
SPELL_GROWTH = 24086 ,
SPELL_FULL_GROWN = 24088
}
enum Phases {
PHASE_TROLL = 1 ,
PHASE_SPIDER = 2
}
enum Misc { GO_SPIDER_EGGS = 179985 }
Functions
void AddSC_boss_marli ()
Variables
float const DamageIncrease = 35.0f
float const DamageDecrease = 100.f / (1.f + DamageIncrease / 100.f) - 100.f
Enumeration Type Documentation
Misc
enum Misc
Enumerator
GO_SPIDER_EGGS
{
    GO_SPIDER_EGGS            = 179985,
};
Phases
enum Phases
Enumerator
PHASE_TROLL
PHASE_SPIDER
{
    PHASE_TROLL               = 1,
    PHASE_SPIDER              = 2
};
Says
enum Says
Enumerator
SAY_AGGRO
SAY_TRANSFORM
SAY_SPIDER_SPAWN
SAY_DEATH
SAY_TRANSFORM_BACK
EMOTE_FULL_GROWN
{
    // Mar'li
    SAY_AGGRO               = 0,
    SAY_TRANSFORM           = 1,
    SAY_SPIDER_SPAWN        = 2,
    SAY_DEATH               = 3,
    SAY_TRANSFORM_BACK      = 4,
    // Spawn of Mar'li
    EMOTE_FULL_GROWN        = 0
};
Spells
enum Spells
Enumerator
SPELL_CHARGE
SPELL_ENVELOPING_WEB
SPELL_CORROSIVE_POISON
SPELL_POISON_SHOCK
SPELL_POISON_VOLLEY
SPELL_DRAIN_LIFE
SPELL_ENLARGE
SPELL_SPIDER_EGGS
SPELL_SPIDER_FORM
SPELL_TRANSFORM_BACK
SPELL_THRASH
SPELL_HATCH_SPIDER_EGG
SPELL_HATCH_EGGS
SPELL_GROWTH
SPELL_FULL_GROWN
{
    // Spider Form
    SPELL_CHARGE              = 22911,
    SPELL_ENVELOPING_WEB      = 24110,
    SPELL_CORROSIVE_POISON    = 24111,
    SPELL_POISON_SHOCK        = 24112,
    // Troll Form
    SPELL_POISON_VOLLEY       = 24099,
    SPELL_DRAIN_LIFE          = 24300,
    SPELL_ENLARGE             = 24109,
    SPELL_SPIDER_EGGS         = 24082,
    // All
    SPELL_SPIDER_FORM         = 24084,
    SPELL_TRANSFORM_BACK      = 24085,
    SPELL_THRASH              = 3391,
    SPELL_HATCH_SPIDER_EGG    = 24082,
    SPELL_HATCH_EGGS          = 24083,
    // Spawn of Mar'li
    SPELL_GROWTH              = 24086,
    SPELL_FULL_GROWN          = 24088
};
Function Documentation
AddSC_boss_marli()
void AddSC_boss_marli ()
{
    RegisterCreatureAI(boss_marli);
    RegisterCreatureAI(npc_spawn_of_marli);
    RegisterSpellScript(spell_hatch_eggs);
    RegisterSpellScript(spell_enveloping_webs);
    RegisterSpellScript(spell_marli_transform);
}
References RegisterCreatureAI, and RegisterSpellScript.
Referenced by AddEasternKingdomsScripts().
Variable Documentation
DamageDecrease
float const DamageDecrease = 100.f / (1.f + DamageIncrease / 100.f) - 100.f
Referenced by boss_marli::_schedulePhaseTroll(), and boss_marli::Reset().
DamageIncrease
float const DamageIncrease = 35.0f
Referenced by boss_marli::_schedulePhaseSpider().