AzerothCore Doxygen
go_strange_pool Class Reference
Public Member Functions
go_strange_pool ()
bool OnGossipHello (Player *player, GameObject *go) override
Public Member Functions inherited from GameObjectScript
bool IsDatabaseBound () const override
virtual bool OnGossipSelect (Player *, GameObject *, uint32, uint32)
virtual bool OnGossipSelectCode (Player *, GameObject *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, GameObject *, Quest const *)
virtual bool OnQuestReward (Player *, GameObject *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, GameObject *)
virtual void OnDestroyed (GameObject *, Player *)
virtual void OnDamaged (GameObject *, Player *)
virtual void OnModifyHealth (GameObject *, Unit *, int32 &, SpellInfo const *)
virtual void OnLootStateChanged (GameObject *, uint32, Unit *)
virtual void OnGameObjectStateChanged (GameObject *, uint32)
virtual GameObjectAI * GetAI (GameObject *) const
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
uint16 GetTotalAvailableHooks ()
Public Member Functions inherited from UpdatableScript< GameObject >
virtual void OnUpdate (GameObject *, uint32)
Additional Inherited Members
Protected Member Functions inherited from GameObjectScript
GameObjectScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name, uint16 totalAvailableHooks=0)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< GameObject >
UpdatableScript ()=default
Detailed Description
Constructor & Destructor Documentation
go_strange_pool()
go_strange_pool::go_strange_pool () inline
: GameObjectScript("go_strange_pool") { }
Member Function Documentation
OnGossipHello()
bool go_strange_pool::OnGossipHello (Player * player, GameObject * go) inline override virtual
Reimplemented from GameObjectScript.
    {
        if (InstanceScript* instance = go->GetInstanceScript())
            if (roll_chance_i(instance->GetBossState(DATA_THE_LURKER_BELOW) != DONE ? 25 : 0) && !instance->IsEncounterInProgress())
            {
                player->CastSpell(player, SPELL_LURKER_SPAWN_TRIGGER, true);
                if (Creature* lurker = go->SummonCreature(NPC_THE_LURKER_BELOW, 38.4567f, -417.324f, -18.916666f, 2.94960f, TEMPSUMMON_MANUAL_DESPAWN))
                    lurker->AI()->DoAction(ACTION_START_EVENT);
                go->DespawnOrUnsummon();
                go->SetRespawnDelay(7 * DAY);
                go->SaveRespawnTime();
                return true;
            }
        return false;
    }
References ACTION_START_EVENT, Unit::CastSpell(), DATA_THE_LURKER_BELOW, DAY, GameObject::DespawnOrUnsummon(), DONE, WorldObject::GetInstanceScript(), NPC_THE_LURKER_BELOW, roll_chance_i(), GameObject::SaveRespawnTime(), GameObject::SetRespawnDelay(), SPELL_LURKER_SPAWN_TRIGGER, WorldObject::SummonCreature(), and TEMPSUMMON_MANUAL_DESPAWN.
The documentation for this class was generated from the following file:
azerothcore-wotlk/src/server/scripts/Outland/CoilfangReservoir/SerpentShrine/boss_lurker_below.cpp