AzerothCore Doxygen
Eluna Class Reference
#include "LuaEngine.h"
Public Types
typedef std::list< LuaScript > ScriptList
typedef std::recursive_mutex LockType
typedef std::lock_guard< LockType > Guard
Public Member Functions
bool ExecuteCall (int params, int res)
bool HasInstanceData (Map const *map)
void CreateInstanceData (Map const *map)
void PushInstanceData (lua_State *L, ElunaInstanceAI *ai, bool incrementCounter=true)
void RunScripts ()
bool ShouldReload () const
bool IsEnabled () const
bool HasLuaState () const
uint64 GetCallstackId () const
int Register (lua_State *L, uint8 reg, uint32 entry, ObjectGuid guid, uint32 instanceId, uint32 event_id, int functionRef, uint32 shots)
CreatureAI * GetAI (Creature *creature)
InstanceData * GetInstanceData (Map *map)
void FreeInstanceId (uint32 instanceId)
void OnTimedEvent (int funcRef, uint32 delay, uint32 calls, WorldObject *obj)
bool OnCommand (ChatHandler &handler, const char *text)
void OnWorldUpdate (uint32 diff)
void OnLootItem (Player *pPlayer, Item *pItem, uint32 count, ObjectGuid guid)
void OnLootMoney (Player *pPlayer, uint32 amount)
void OnFirstLogin (Player *pPlayer)
void OnEquip (Player *pPlayer, Item *pItem, uint8 bag, uint8 slot)
void OnRepop (Player *pPlayer)
void OnResurrect (Player *pPlayer)
void OnQuestAbandon (Player *pPlayer, uint32 questId)
void OnLearnTalents (Player *pPlayer, uint32 talentId, uint32 talentRank, uint32 spellid)
InventoryResult OnCanUseItem (const Player *pPlayer, uint32 itemEntry)
void OnLuaStateClose ()
void OnLuaStateOpen ()
bool OnAddonMessage (Player *sender, uint32 type, std::string &msg, Player *receiver, Guild *guild, Group *group, Channel *channel)
void OnPetAddedToWorld (Player *player, Creature *pet)
void OnQuestRewardItem (Player *player, Item *item, uint32 count)
void OnCreateItem (Player *player, Item *item, uint32 count)
void OnStoreNewItem (Player *player, Item *item, uint32 count)
void OnPlayerCompleteQuest (Player *player, Quest const *quest)
void OnDummyEffect (WorldObject *pCaster, uint32 spellId, SpellEffIndex effIndex, Item *pTarget)
bool OnQuestAccept (Player *pPlayer, Item *pItem, Quest const *pQuest)
bool OnUse (Player *pPlayer, Item *pItem, SpellCastTargets const &targets)
bool OnItemUse (Player *pPlayer, Item *pItem, SpellCastTargets const &targets)
bool OnItemGossip (Player *pPlayer, Item *pItem, SpellCastTargets const &targets)
bool OnExpire (Player *pPlayer, ItemTemplate const *pProto)
bool OnRemove (Player *pPlayer, Item *item)
void HandleGossipSelectOption (Player *pPlayer, Item *item, uint32 sender, uint32 action, const std::string &code)
void OnDummyEffect (WorldObject *pCaster, uint32 spellId, SpellEffIndex effIndex, Creature *pTarget)
bool OnGossipHello (Player *pPlayer, Creature *pCreature)
bool OnGossipSelect (Player *pPlayer, Creature *pCreature, uint32 sender, uint32 action)
bool OnGossipSelectCode (Player *pPlayer, Creature *pCreature, uint32 sender, uint32 action, const char *code)
bool OnQuestAccept (Player *pPlayer, Creature *pCreature, Quest const *pQuest)
bool OnQuestReward (Player *pPlayer, Creature *pCreature, Quest const *pQuest, uint32 opt)
void GetDialogStatus (const Player *pPlayer, const Creature *pCreature)
bool OnSummoned (Creature *creature, Unit *summoner)
bool UpdateAI (Creature *me, const uint32 diff)
bool EnterCombat (Creature *me, Unit *target)
bool DamageTaken (Creature *me, Unit *attacker, uint32 &damage)
bool JustDied (Creature *me, Unit *killer)
bool KilledUnit (Creature *me, Unit *victim)
bool JustSummoned (Creature *me, Creature *summon)
bool SummonedCreatureDespawn (Creature *me, Creature *summon)
bool MovementInform (Creature *me, uint32 type, uint32 id)
bool AttackStart (Creature *me, Unit *target)
bool EnterEvadeMode (Creature *me)
bool JustRespawned (Creature *me)
bool JustReachedHome (Creature *me)
bool ReceiveEmote (Creature *me, Player *player, uint32 emoteId)
bool CorpseRemoved (Creature *me, uint32 &respawnDelay)
bool MoveInLineOfSight (Creature *me, Unit *who)
bool SpellHit (Creature *me, WorldObject *caster, SpellInfo const *spell)
bool SpellHitTarget (Creature *me, WorldObject *target, SpellInfo const *spell)
bool SummonedCreatureDies (Creature *me, Creature *summon, Unit *killer)
bool OwnerAttackedBy (Creature *me, Unit *attacker)
bool OwnerAttacked (Creature *me, Unit *target)
void On_Reset (Creature *me)
void OnDummyEffect (WorldObject *pCaster, uint32 spellId, SpellEffIndex effIndex, GameObject *pTarget)
bool OnGameObjectUse (Player *pPlayer, GameObject *pGameObject)
bool OnGossipHello (Player *pPlayer, GameObject *pGameObject)
bool OnGossipSelect (Player *pPlayer, GameObject *pGameObject, uint32 sender, uint32 action)
bool OnGossipSelectCode (Player *pPlayer, GameObject *pGameObject, uint32 sender, uint32 action, const char *code)
bool OnQuestAccept (Player *pPlayer, GameObject *pGameObject, Quest const *pQuest)
bool OnQuestReward (Player *pPlayer, GameObject *pGameObject, Quest const *pQuest, uint32 opt)
void GetDialogStatus (const Player *pPlayer, const GameObject *pGameObject)
void OnDestroyed (GameObject *pGameObject, WorldObject *attacker)
void OnDamaged (GameObject *pGameObject, WorldObject *attacker)
void OnLootStateChanged (GameObject *pGameObject, uint32 state)
void OnGameObjectStateChanged (GameObject *pGameObject, uint32 state)
void UpdateAI (GameObject *pGameObject, uint32 diff)
void OnSpawn (GameObject *gameobject)
bool OnPacketSend (WorldSession *session, const WorldPacket &packet)
void OnPacketSendAny (Player *player, const WorldPacket &packet, bool &result)
void OnPacketSendOne (Player *player, const WorldPacket &packet, bool &result)
bool OnPacketReceive (WorldSession *session, WorldPacket &packet)
void OnPacketReceiveAny (Player *player, WorldPacket &packet, bool &result)
void OnPacketReceiveOne (Player *player, WorldPacket &packet, bool &result)
void OnPlayerEnterCombat (Player *pPlayer, Unit *pEnemy)
void OnPlayerLeaveCombat (Player *pPlayer)
void OnPVPKill (Player *pKiller, Player *pKilled)
void OnCreatureKill (Player *pKiller, Creature *pKilled)
void OnPlayerKilledByCreature (Creature *pKiller, Player *pKilled)
void OnLevelChanged (Player *pPlayer, uint8 oldLevel)
void OnFreeTalentPointsChanged (Player *pPlayer, uint32 newPoints)
void OnTalentsReset (Player *pPlayer, bool noCost)
void OnMoneyChanged (Player *pPlayer, int32 &amount)
void OnGiveXP (Player *pPlayer, uint32 &amount, Unit *pVictim, uint8 xpSource)
bool OnReputationChange (Player *pPlayer, uint32 factionID, int32 &standing, bool incremental)
void OnDuelRequest (Player *pTarget, Player *pChallenger)
void OnDuelStart (Player *pStarter, Player *pChallenger)
void OnDuelEnd (Player *pWinner, Player *pLoser, DuelCompleteType type)
bool OnChat (Player *pPlayer, uint32 type, uint32 lang, std::string &msg)
bool OnChat (Player *pPlayer, uint32 type, uint32 lang, std::string &msg, Group *pGroup)
bool OnChat (Player *pPlayer, uint32 type, uint32 lang, std::string &msg, Guild *pGuild)
bool OnChat (Player *pPlayer, uint32 type, uint32 lang, std::string &msg, Channel *pChannel)
bool OnChat (Player *pPlayer, uint32 type, uint32 lang, std::string &msg, Player *pReceiver)
void OnEmote (Player *pPlayer, uint32 emote)
void OnTextEmote (Player *pPlayer, uint32 textEmote, uint32 emoteNum, ObjectGuid guid)
void OnSpellCast (Player *pPlayer, Spell *pSpell, bool skipCheck)
void OnLogin (Player *pPlayer)
void OnLogout (Player *pPlayer)
void OnCreate (Player *pPlayer)
void OnDelete (uint32 guid)
void OnSave (Player *pPlayer)
void OnBindToInstance (Player *pPlayer, Difficulty difficulty, uint32 mapid, bool permanent)
void OnUpdateArea (Player *pPlayer, uint32 oldArea, uint32 newArea)
void OnUpdateZone (Player *pPlayer, uint32 newZone, uint32 newArea)
void OnMapChanged (Player *pPlayer)
void HandleGossipSelectOption (Player *pPlayer, uint32 menuId, uint32 sender, uint32 action, const std::string &code)
void OnLearnSpell (Player *player, uint32 spellId)
void OnAchiComplete (Player *player, AchievementEntry const *achievement)
void OnFfaPvpStateUpdate (Player *player, bool hasFfaPvp)
bool OnCanInitTrade (Player *player, Player *target)
bool OnCanSendMail (Player *player, ObjectGuid receiverGuid, ObjectGuid mailbox, std::string &subject, std::string &body, uint32 money, uint32 cod, Item *item)
bool OnCanJoinLfg (Player *player, uint8 roles, lfg::LfgDungeonSet &dungeons, const std::string &comment)
bool OnCanGroupInvite (Player *player, std::string &memberName)
void OnGroupRollRewardItem (Player *player, Item *item, uint32 count, RollVote voteType, Roll *roll)
void OnBattlegroundDesertion (Player *player, const BattlegroundDesertionType type)
void OnCreatureKilledByPet (Player *player, Creature *killed)
void OnInstall (Vehicle *vehicle)
void OnUninstall (Vehicle *vehicle)
void OnInstallAccessory (Vehicle *vehicle, Creature *accessory)
void OnAddPassenger (Vehicle *vehicle, Unit *passenger, int8 seatId)
void OnRemovePassenger (Vehicle *vehicle, Unit *passenger)
bool OnAreaTrigger (Player *pPlayer, AreaTriggerEntry const *pTrigger)
void OnChange (Weather *weather, uint32 zone, WeatherState state, float grade)
void OnAdd (AuctionHouseObject *ah, AuctionEntry *entry)
void OnRemove (AuctionHouseObject *ah, AuctionEntry *entry)
void OnSuccessful (AuctionHouseObject *ah, AuctionEntry *entry)
void OnExpire (AuctionHouseObject *ah, AuctionEntry *entry)
void OnAddMember (Guild *guild, Player *player, uint32 plRank)
void OnRemoveMember (Guild *guild, Player *player, bool isDisbanding)
void OnMOTDChanged (Guild *guild, const std::string &newMotd)
void OnInfoChanged (Guild *guild, const std::string &newInfo)
void OnCreate (Guild *guild, Player *leader, const std::string &name)
void OnDisband (Guild *guild)
void OnMemberWitdrawMoney (Guild *guild, Player *player, uint32 &amount, bool isRepair)
void OnMemberDepositMoney (Guild *guild, Player *player, uint32 &amount)
void OnItemMove (Guild *guild, Player *player, Item *pItem, bool isSrcBank, uint8 srcContainer, uint8 srcSlotId, bool isDestBank, uint8 destContainer, uint8 destSlotId)
void OnEvent (Guild *guild, uint8 eventType, uint32 playerGuid1, uint32 playerGuid2, uint8 newRank)
void OnBankEvent (Guild *guild, uint8 eventType, uint8 tabId, uint32 playerGuid, uint32 itemOrMoney, uint16 itemStackCount, uint8 destTabId)
void OnAddMember (Group *group, ObjectGuid guid)
void OnInviteMember (Group *group, ObjectGuid guid)
void OnRemoveMember (Group *group, ObjectGuid guid, uint8 method)
void OnChangeLeader (Group *group, ObjectGuid newLeaderGuid, ObjectGuid oldLeaderGuid)
void OnDisband (Group *group)
void OnCreate (Group *group, ObjectGuid leaderGuid, GroupType groupType)
void OnCreate (Map *map)
void OnDestroy (Map *map)
void OnPlayerEnter (Map *map, Player *player)
void OnPlayerLeave (Map *map, Player *player)
void OnUpdate (Map *map, uint32 diff)
void OnAddToWorld (Creature *creature)
void OnRemoveFromWorld (Creature *creature)
void OnAddToWorld (GameObject *gameobject)
void OnRemoveFromWorld (GameObject *gameobject)
void OnRemove (Creature *creature)
void OnRemove (GameObject *gameobject)
void OnInitialize (ElunaInstanceAI *ai)
void OnLoad (ElunaInstanceAI *ai)
void OnUpdateInstance (ElunaInstanceAI *ai, uint32 diff)
void OnPlayerEnterInstance (ElunaInstanceAI *ai, Player *player)
void OnCreatureCreate (ElunaInstanceAI *ai, Creature *creature)
void OnGameObjectCreate (ElunaInstanceAI *ai, GameObject *gameobject)
bool OnCheckEncounterInProgress (ElunaInstanceAI *ai)
void OnOpenStateChange (bool open)
void OnConfigLoad (bool reload)
void OnShutdownInitiate (ShutdownExitCode code, ShutdownMask mask)
void OnShutdownCancel ()
void OnStartup ()
void OnShutdown ()
void OnGameEventStart (uint32 eventid)
void OnGameEventStop (uint32 eventid)
void OnBGStart (BattleGround *bg, BattleGroundTypeId bgId, uint32 instanceId)
void OnBGEnd (BattleGround *bg, BattleGroundTypeId bgId, uint32 instanceId, Team winner)
void OnBGCreate (BattleGround *bg, BattleGroundTypeId bgId, uint32 instanceId)
void OnBGDestroy (BattleGround *bg, BattleGroundTypeId bgId, uint32 instanceId)
Static Public Member Functions
static void Initialize ()
static void Uninitialize ()
static void ReloadEluna ()
static LockType & GetLock ()
static bool IsInitialized ()
static Eluna * GetEluna (lua_State *L)
static void Push (lua_State *luastate)
static void Push (lua_State *luastate, const long long)
static void Push (lua_State *luastate, const unsigned long long)
static void Push (lua_State *luastate, const long)
static void Push (lua_State *luastate, const unsigned long)
static void Push (lua_State *luastate, const int)
static void Push (lua_State *luastate, const unsigned int)
static void Push (lua_State *luastate, const bool)
static void Push (lua_State *luastate, const float)
static void Push (lua_State *luastate, const double)
static void Push (lua_State *luastate, const std::string &)
static void Push (lua_State *luastate, const char *)
static void Push (lua_State *luastate, Object const *obj)
static void Push (lua_State *luastate, WorldObject const *obj)
static void Push (lua_State *luastate, Unit const *unit)
static void Push (lua_State *luastate, Pet const *pet)
static void Push (lua_State *luastate, TempSummon const *summon)
static void Push (lua_State *luastate, ObjectGuid const guid)
template<typename T >
static void Push (lua_State *luastate, T const *ptr)
template<typename T >
static T CHECKVAL (lua_State *luastate, int narg)
template<typename T >
static T CHECKVAL (lua_State *luastate, int narg, T def)
template<typename T >
static T * CHECKOBJ (lua_State *luastate, int narg, bool error=true)
static ElunaObject * CHECKTYPE (lua_State *luastate, int narg, const char *tname, bool error=true)
template<>
bool CHECKVAL (lua_State *luastate, int narg)
template<>
float CHECKVAL (lua_State *luastate, int narg)
template<>
double CHECKVAL (lua_State *luastate, int narg)
template<>
signed char CHECKVAL (lua_State *luastate, int narg)
template<>
unsigned char CHECKVAL (lua_State *luastate, int narg)
template<>
short CHECKVAL (lua_State *luastate, int narg)
template<>
unsigned short CHECKVAL (lua_State *luastate, int narg)
template<>
int CHECKVAL (lua_State *luastate, int narg)
template<>
unsigned int CHECKVAL (lua_State *luastate, int narg)
template<>
const char * CHECKVAL (lua_State *luastate, int narg)
template<>
long long CHECKVAL (lua_State *luastate, int narg)
template<>
unsigned long long CHECKVAL (lua_State *luastate, int narg)
template<>
long CHECKVAL (lua_State *luastate, int narg)
template<>
unsigned long CHECKVAL (lua_State *luastate, int narg)
template<>
ObjectGuid CHECKVAL (lua_State *luastate, int narg)
template<>
Object * CHECKOBJ (lua_State *luastate, int narg, bool error)
template<>
WorldObject * CHECKOBJ (lua_State *luastate, int narg, bool error)
template<>
Unit * CHECKOBJ (lua_State *luastate, int narg, bool error)
template<>
ElunaObject * CHECKOBJ (lua_State *luastate, int narg, bool error)
template<>
Unit * CHECKOBJ (lua_State *L, int narg, bool error)
template<>
Object * CHECKOBJ (lua_State *L, int narg, bool error)
template<>
WorldObject * CHECKOBJ (lua_State *L, int narg, bool error)
template<>
ElunaObject * CHECKOBJ (lua_State *L, int narg, bool error)
Public Attributes
lua_State * L
EventMgr * eventMgr
HttpManager httpManager
QueryCallbackProcessor queryProcessor
EventEmitter< void(std::string)> OnError
BindingMap< EventKey< Hooks::ServerEvents > > * ServerEventBindings
BindingMap< EventKey< Hooks::PlayerEvents > > * PlayerEventBindings
BindingMap< EventKey< Hooks::GuildEvents > > * GuildEventBindings
BindingMap< EventKey< Hooks::GroupEvents > > * GroupEventBindings
BindingMap< EventKey< Hooks::VehicleEvents > > * VehicleEventBindings
BindingMap< EventKey< Hooks::BGEvents > > * BGEventBindings
BindingMap< EntryKey< Hooks::PacketEvents > > * PacketEventBindings
BindingMap< EntryKey< Hooks::CreatureEvents > > * CreatureEventBindings
BindingMap< EntryKey< Hooks::GossipEvents > > * CreatureGossipBindings
BindingMap< EntryKey< Hooks::GameObjectEvents > > * GameObjectEventBindings
BindingMap< EntryKey< Hooks::GossipEvents > > * GameObjectGossipBindings
BindingMap< EntryKey< Hooks::ItemEvents > > * ItemEventBindings
BindingMap< EntryKey< Hooks::GossipEvents > > * ItemGossipBindings
BindingMap< EntryKey< Hooks::GossipEvents > > * PlayerGossipBindings
BindingMap< EntryKey< Hooks::InstanceEvents > > * MapEventBindings
BindingMap< EntryKey< Hooks::InstanceEvents > > * InstanceEventBindings
BindingMap< UniqueObjectKey< Hooks::CreatureEvents > > * CreatureUniqueBindings
Static Public Attributes
static Eluna * GEluna = NULL
Private Member Functions
Eluna ()
~Eluna ()
Eluna (Eluna const &)=delete
Eluna & operator= (const Eluna &)=delete
void OpenLua ()
void CloseLua ()
void DestroyBindStores ()
void CreateBindStores ()
void InvalidateObjects ()
template<typename K1 , typename K2 >
int SetupStack (BindingMap< K1 > *bindings1, BindingMap< K2 > *bindings2, const K1 &key1, const K2 &key2, int number_of_arguments)
int CallOneFunction (int number_of_functions, int number_of_arguments, int number_of_results)
void CleanUpStack (int number_of_arguments)
template<typename T >
void ReplaceArgument (T value, uint8 index)
template<typename K1 , typename K2 >
void CallAllFunctions (BindingMap< K1 > *bindings1, BindingMap< K2 > *bindings2, const K1 &key1, const K2 &key2)
template<typename K1 , typename K2 >
bool CallAllFunctionsBool (BindingMap< K1 > *bindings1, BindingMap< K2 > *bindings2, const K1 &key1, const K2 &key2, bool default_value=false)
template<typename K >
int SetupStack (BindingMap< K > *bindings, const K &key, int number_of_arguments)
template<typename K >
void CallAllFunctions (BindingMap< K > *bindings, const K &key)
template<typename K >
bool CallAllFunctionsBool (BindingMap< K > *bindings, const K &key, bool default_value=false)
void Push ()
void Push (const long long value)
void Push (const unsigned long long value)
void Push (const long value)
void Push (const unsigned long value)
void Push (const int value)
void Push (const unsigned int value)
void Push (const bool value)
void Push (const float value)
void Push (const double value)
void Push (const std::string &value)
void Push (const char *value)
void Push (ObjectGuid const value)
template<typename T >
void Push (T const *ptr)
Static Private Member Functions
static void _ReloadEluna ()
static void LoadScriptPaths ()
static void GetScripts (std::string path)
static void AddScriptPath (std::string filename, const std::string &fullpath)
static int StackTrace (lua_State *_L)
static void Report (lua_State *_L)
Private Attributes
uint64 callstackid = 2
uint32 event_level
uint8 push_counter
bool enabled
std::unordered_map< uint32, int > instanceDataRefs
std::unordered_map< uint32, int > continentDataRefs
Static Private Attributes
static bool reload = false
static bool initialized = false
static LockType lock
static ScriptList lua_scripts
static ScriptList lua_extensions
static std::string lua_folderpath
static std::string lua_requirepath
Detailed Description
Member Typedef Documentation
Guard
typedef std::lock_guard<LockType> Eluna::Guard
LockType
typedef std::recursive_mutex Eluna::LockType
ScriptList
typedef std::list<LuaScript> Eluna::ScriptList
Constructor & Destructor Documentation
Eluna() [1/2]
Eluna::Eluna () private
             :
event_level(0),
push_counter(0),
enabled(false),
L(NULL),
eventMgr(NULL),
httpManager(),
queryProcessor(),
ServerEventBindings(NULL),
PlayerEventBindings(NULL),
GuildEventBindings(NULL),
GroupEventBindings(NULL),
VehicleEventBindings(NULL),
BGEventBindings(NULL),
PacketEventBindings(NULL),
CreatureEventBindings(NULL),
CreatureGossipBindings(NULL),
GameObjectEventBindings(NULL),
GameObjectGossipBindings(NULL),
ItemEventBindings(NULL),
ItemGossipBindings(NULL),
PlayerGossipBindings(NULL),
MapEventBindings(NULL),
InstanceEventBindings(NULL),
CreatureUniqueBindings(NULL)
{
    ASSERT(IsInitialized());
    OpenLua();
    // Replace this with map insert if making multithread version
    // Set event manager. Must be after setting sEluna
    // on multithread have a map of state pointers and here insert this pointer to the map and then save a pointer of that pointer to the EventMgr
    eventMgr = new EventMgr(&Eluna::GEluna);
}
References ASSERT, eventMgr, GEluna, IsInitialized(), and OpenLua().
Referenced by Initialize().
~Eluna()
Eluna::~Eluna () private
{
    ASSERT(IsInitialized());
    CloseLua();
    delete eventMgr;
    eventMgr = NULL;
}
References ASSERT, CloseLua(), eventMgr, and IsInitialized().
Eluna() [2/2]
Eluna::Eluna (Eluna const &) private delete
Member Function Documentation
_ReloadEluna()
void Eluna::_ReloadEluna () static private
{
    LOCK_ELUNA;
    ASSERT(IsInitialized());
    if (eConfigMgr->GetOption<bool>("Eluna.PlayerAnnounceReload", false))
        eWorld->SendServerMessage(SERVER_MSG_STRING, "Reloading Eluna...");
    else
        ChatHandler(nullptr).SendGMText(SERVER_MSG_STRING, "Reloading Eluna...");
    // Remove all timed events
    sEluna->eventMgr->SetStates(LUAEVENT_STATE_ERASE);
    // Close lua
    sEluna->CloseLua();
    // Reload script paths
    LoadScriptPaths();
    // Open new lua and libaraies
    sEluna->OpenLua();
    // Run scripts from laoded paths
    sEluna->RunScripts();
    reload = false;
}
References ASSERT, eConfigMgr, eWorld, IsInitialized(), LoadScriptPaths(), LOCK_ELUNA, LUAEVENT_STATE_ERASE, reload, sEluna, ChatHandler::SendGMText(), and SERVER_MSG_STRING.
Referenced by OnWorldUpdate().
AddScriptPath()
void Eluna::AddScriptPath (std::string filename, const std::string & fullpath) static private
{
    ELUNA_LOG_DEBUG("[Eluna]: AddScriptPath Checking file `{}`", fullpath);
    // split file name
    std::size_t extDot = filename.find_last_of('.');
    if (extDot == std::string::npos)
        return;
    std::string ext = filename.substr(extDot);
    filename = filename.substr(0, extDot);
    // check extension and add path to scripts to load
    if (ext != ".lua" && ext != ".dll" && ext != ".so" && ext != ".ext")
        return;
    bool extension = ext == ".ext";
    LuaScript script;
    script.fileext = ext;
    script.filename = filename;
    script.filepath = fullpath;
    script.modulepath = fullpath.substr(0, fullpath.length() - filename.length() - ext.length());
    if (extension)
        lua_extensions.push_back(script);
    else
        lua_scripts.push_back(script);
    ELUNA_LOG_DEBUG("[Eluna]: AddScriptPath add path `{}`", fullpath);
}
References ELUNA_LOG_DEBUG, LuaScript::fileext, LuaScript::filename, LuaScript::filepath, lua_extensions, lua_scripts, and LuaScript::modulepath.
Referenced by GetScripts().
AttackStart()
bool Eluna::AttackStart (Creature * me, Unit * target)
{
    START_HOOK_WITH_RETVAL(CREATURE_EVENT_ON_PRE_COMBAT, me, false);
    Push(me);
    Push(target);
    return CallAllFunctionsBool(CreatureEventBindings, CreatureUniqueBindings, entry_key, unique_key);
}
References CallAllFunctionsBool(), Hooks::CREATURE_EVENT_ON_PRE_COMBAT, CreatureEventBindings, CreatureUniqueBindings, Push(), and START_HOOK_WITH_RETVAL.
CallAllFunctions() [1/2]
template<typename K > void Eluna::CallAllFunctions (BindingMap< K > * bindings, const K & key) inline private
    {
        CallAllFunctions<K, K>(bindings, NULL, key, key);
    }
CallAllFunctions() [2/2]
template<typename K1 , typename K2 > void Eluna::CallAllFunctions (BindingMap< K1 > * bindings1, BindingMap< K2 > * bindings2, const K1 & key1, const K2 & key2) private
{
    int number_of_arguments = this->push_counter;
    // Stack: [arguments]
    int number_of_functions = SetupStack(bindings1, bindings2, key1, key2, number_of_arguments);
    // Stack: event_id, [arguments], [functions]
    while (number_of_functions > 0)
    {
        CallOneFunction(number_of_functions, number_of_arguments, 0);
        --number_of_functions;
        // Stack: event_id, [arguments], [functions - 1]
    }
    // Stack: event_id, [arguments]
    CleanUpStack(number_of_arguments);
    // Stack: (empty)
}
References CallOneFunction(), CleanUpStack(), push_counter, and SetupStack().
Referenced by GetDialogStatus(), GetDialogStatus(), HandleGossipSelectOption(), HandleGossipSelectOption(), On_Reset(), OnAchiComplete(), OnAdd(), OnAddMember(), OnAddMember(), OnAddPassenger(), OnAddToWorld(), OnAddToWorld(), OnBankEvent(), OnBattlegroundDesertion(), OnBGCreate(), OnBGDestroy(), OnBGStart(), OnBindToInstance(), OnChange(), OnChangeLeader(), OnCreate(), OnCreate(), OnCreate(), OnCreate(), OnCreateItem(), OnCreatureCreate(), OnCreatureKill(), OnCreatureKilledByPet(), OnDamaged(), OnDelete(), OnDestroy(), OnDestroyed(), OnDisband(), OnDisband(), OnDuelEnd(), OnDuelRequest(), OnDuelStart(), OnDummyEffect(), OnDummyEffect(), OnDummyEffect(), OnEmote(), OnEquip(), OnEvent(), OnExpire(), OnFfaPvpStateUpdate(), OnFirstLogin(), OnFreeTalentPointsChanged(), OnGameEventStart(), OnGameEventStop(), OnGameObjectCreate(), OnGameObjectStateChanged(), OnGroupRollRewardItem(), OnInfoChanged(), OnInitialize(), OnInstall(), OnInstallAccessory(), OnInviteMember(), OnItemMove(), OnLearnSpell(), OnLearnTalents(), OnLevelChanged(), OnLoad(), OnLogin(), OnLogout(), OnLootItem(), OnLootMoney(), OnLootStateChanged(), OnLuaStateClose(), OnLuaStateOpen(), OnMapChanged(), OnMOTDChanged(), OnOpenStateChange(), OnPetAddedToWorld(), OnPlayerCompleteQuest(), OnPlayerEnter(), OnPlayerEnterCombat(), OnPlayerEnterInstance(), OnPlayerKilledByCreature(), OnPlayerLeave(), OnPlayerLeaveCombat(), OnPVPKill(), OnQuestAbandon(), OnQuestRewardItem(), OnRemove(), OnRemove(), OnRemove(), OnRemoveFromWorld(), OnRemoveFromWorld(), OnRemoveMember(), OnRemoveMember(), OnRemovePassenger(), OnRepop(), OnResurrect(), OnSave(), OnShutdown(), OnShutdownCancel(), OnShutdownInitiate(), OnSpawn(), OnSpellCast(), OnStartup(), OnStoreNewItem(), OnSuccessful(), OnTalentsReset(), OnTextEmote(), OnUninstall(), OnUpdate(), OnUpdateArea(), OnUpdateInstance(), OnUpdateZone(), OnWorldUpdate(), and UpdateAI().
CallAllFunctionsBool() [1/2]
template<typename K > bool Eluna::CallAllFunctionsBool (BindingMap< K > * bindings, const K & key, bool default_value = false) inline private
    {
        return CallAllFunctionsBool<K, K>(bindings, NULL, key, key, default_value);
    }
CallAllFunctionsBool() [2/2]
template<typename K1 , typename K2 > bool Eluna::CallAllFunctionsBool (BindingMap< K1 > * bindings1, BindingMap< K2 > * bindings2, const K1 & key1, const K2 & key2, bool default_value = false) private
{
    bool result = default_value;
    // Note: number_of_arguments here does not count in eventID, which is pushed in SetupStack
    int number_of_arguments = this->push_counter;
    // Stack: [arguments]
    int number_of_functions = SetupStack(bindings1, bindings2, key1, key2, number_of_arguments);
    // Stack: event_id, [arguments], [functions]
    while (number_of_functions > 0)
    {
        int r = CallOneFunction(number_of_functions, number_of_arguments, 1);
        --number_of_functions;
        // Stack: event_id, [arguments], [functions - 1], result
        if (lua_isboolean(L, r) && (lua_toboolean(L, r) == 1) != default_value)
            result = !default_value;
        lua_pop(L, 1);
        // Stack: event_id, [arguments], [functions - 1]
    }
    // Stack: event_id, [arguments]
    CleanUpStack(number_of_arguments);
    // Stack: (empty)
    return result;
}
References CallOneFunction(), CleanUpStack(), L, lua_isboolean, lua_pop, lua_toboolean(), push_counter, and SetupStack().
Referenced by AttackStart(), EnterCombat(), EnterEvadeMode(), JustDied(), JustReachedHome(), JustRespawned(), JustSummoned(), KilledUnit(), MoveInLineOfSight(), MovementInform(), OnAddonMessage(), OnAreaTrigger(), OnCanGroupInvite(), OnCanInitTrade(), OnCanJoinLfg(), OnCanSendMail(), OnCheckEncounterInProgress(), OnCommand(), OnExpire(), OnGameObjectUse(), OnGossipHello(), OnGossipHello(), OnGossipSelect(), OnGossipSelect(), OnGossipSelectCode(), OnGossipSelectCode(), OnItemGossip(), OnItemUse(), OnQuestAccept(), OnQuestAccept(), OnQuestAccept(), OnQuestReward(), OnQuestReward(), OnRemove(), OnSummoned(), ReceiveEmote(), SpellHit(), SpellHitTarget(), SummonedCreatureDespawn(), and UpdateAI().
CallOneFunction()
int Eluna::CallOneFunction (int number_of_functions, int number_of_arguments, int number_of_results) private
{
    ++number_of_arguments; // Caller doesn't know about `event_id`.
    ASSERT(number_of_functions > 0 && number_of_arguments > 0 && number_of_results >= 0);
    // Stack: event_id, [arguments], [functions]
    int functions_top        = lua_gettop(L);
    int first_function_index = functions_top - number_of_functions + 1;
    int arguments_top        = first_function_index - 1;
    int first_argument_index = arguments_top - number_of_arguments + 1;
    // Copy the arguments from the bottom of the stack to the top.
    for (int argument_index = first_argument_index; argument_index <= arguments_top; ++argument_index)
    {
        lua_pushvalue(L, argument_index);
    }
    // Stack: event_id, [arguments], [functions], event_id, [arguments]
    ExecuteCall(number_of_arguments, number_of_results);
    --functions_top;
    // Stack: event_id, [arguments], [functions - 1], [results]
    return functions_top + 1; // Return the location of the first result (if any exist).
}
References ASSERT, ExecuteCall(), L, lua_gettop(), and lua_pushvalue().
Referenced by CallAllFunctions(), CallAllFunctionsBool(), CorpseRemoved(), DamageTaken(), OnCanUseItem(), OnChat(), OnChat(), OnChat(), OnChat(), OnChat(), OnGiveXP(), OnMemberDepositMoney(), OnMemberWitdrawMoney(), OnMoneyChanged(), OnPacketReceiveAny(), OnPacketReceiveOne(), OnPacketSendAny(), OnPacketSendOne(), and OnReputationChange().
CHECKOBJ() [1/9]
template<> Unit * Eluna::CHECKOBJ (lua_State * L, int narg, bool error) static
CHECKOBJ() [2/9]
template<> Object * Eluna::CHECKOBJ (lua_State * L, int narg, bool error) static
CHECKOBJ() [3/9]
template<> WorldObject * Eluna::CHECKOBJ (lua_State * L, int narg, bool error) static
CHECKOBJ() [4/9]
template<> ElunaObject * Eluna::CHECKOBJ (lua_State * L, int narg, bool error) static
CHECKOBJ() [5/9]
template<> Object * Eluna::CHECKOBJ (lua_State * luastate, int narg, bool error) static
{
    Object* obj = CHECKOBJ<WorldObject>(luastate, narg, false);
    if (!obj)
        obj = CHECKOBJ<Item>(luastate, narg, false);
    if (!obj)
        obj = ElunaTemplate<Object>::Check(luastate, narg, error);
    return obj;
}
References ElunaTemplate< T >::Check().
CHECKOBJ() [6/9]
template<> WorldObject * Eluna::CHECKOBJ (lua_State * luastate, int narg, bool error) static
{
    WorldObject* obj = CHECKOBJ<Unit>(luastate, narg, false);
    if (!obj)
        obj = CHECKOBJ<GameObject>(luastate, narg, false);
    if (!obj)
        obj = CHECKOBJ<Corpse>(luastate, narg, false);
    if (!obj)
        obj = ElunaTemplate<WorldObject>::Check(luastate, narg, error);
    return obj;
}
References ElunaTemplate< T >::Check().
CHECKOBJ() [7/9]
template<> Unit * Eluna::CHECKOBJ (lua_State * luastate, int narg, bool error) static
{
    Unit* obj = CHECKOBJ<Player>(luastate, narg, false);
    if (!obj)
        obj = CHECKOBJ<Creature>(luastate, narg, false);
    if (!obj)
        obj = ElunaTemplate<Unit>::Check(luastate, narg, error);
    return obj;
}
References ElunaTemplate< T >::Check().
CHECKOBJ() [8/9]
template<> ElunaObject * Eluna::CHECKOBJ (lua_State * luastate, int narg, bool error) static
{
    return CHECKTYPE(luastate, narg, NULL, error);
}
References CHECKTYPE().
CHECKOBJ() [9/9]
template<typename T > static T * Eluna::CHECKOBJ (lua_State * luastate, int narg, bool error = true) inline static
    {
        return ElunaTemplate<T>::Check(luastate, narg, error);
    }
References ElunaTemplate< T >::Check().
CHECKTYPE()
ElunaObject * Eluna::CHECKTYPE (lua_State * luastate, int narg, const char * tname, bool error = true) static
{
    if (lua_islightuserdata(luastate, narg))
    {
        if (error)
            luaL_argerror(luastate, narg, "bad argument : userdata expected, got lightuserdata");
        return NULL;
    }
    ElunaObject** ptrHold = static_cast<ElunaObject**>(lua_touserdata(luastate, narg));
    if (!ptrHold || (tname && (*ptrHold)->GetTypeName() != tname))
    {
        if (error)
        {
            char buff[256];
            snprintf(buff, 256, "bad argument : %s expected, got %s", tname ? tname : "ElunaObject", ptrHold ? (*ptrHold)->GetTypeName() : luaL_typename(luastate, narg));
            luaL_argerror(luastate, narg, buff);
        }
        return NULL;
    }
    return *ptrHold;
}
References ElunaObject::GetTypeName(), lua_islightuserdata, lua_touserdata(), luaL_argerror(), and luaL_typename.
Referenced by ElunaTemplate< T >::Check(), and CHECKOBJ().
CHECKVAL() [1/17]
template<> bool Eluna::CHECKVAL (lua_State * luastate, int narg) static
{
    return lua_toboolean(luastate, narg) != 0;
}
References lua_toboolean().
CHECKVAL() [2/17]
template<> float Eluna::CHECKVAL (lua_State * luastate, int narg) static
{
    return static_cast<float>(luaL_checknumber(luastate, narg));
}
References luaL_checknumber().
CHECKVAL() [3/17]
template<> double Eluna::CHECKVAL (lua_State * luastate, int narg) static
{
    return luaL_checknumber(luastate, narg);
}
References luaL_checknumber().
CHECKVAL() [4/17]
template<> signed char Eluna::CHECKVAL (lua_State * luastate, int narg) static
{
    return CheckIntegerRange(luastate, narg, SCHAR_MIN, SCHAR_MAX);
}
References CheckIntegerRange().
CHECKVAL() [5/17]
template<> unsigned char Eluna::CHECKVAL (lua_State * luastate, int narg) static
{
    return CheckUnsignedRange(luastate, narg, UCHAR_MAX);
}
References CheckUnsignedRange().
CHECKVAL() [6/17]
template<> short Eluna::CHECKVAL (lua_State * luastate, int narg) static
{
    return CheckIntegerRange(luastate, narg, SHRT_MIN, SHRT_MAX);
}
References CheckIntegerRange().
CHECKVAL() [7/17]
template<> unsigned short Eluna::CHECKVAL (lua_State * luastate, int narg) static
{
    return CheckUnsignedRange(luastate, narg, USHRT_MAX);
}
References CheckUnsignedRange().
CHECKVAL() [8/17]
template<> int Eluna::CHECKVAL (lua_State * luastate, int narg) static
{
    return CheckIntegerRange(luastate, narg, INT_MIN, INT_MAX);
}
References CheckIntegerRange().
CHECKVAL() [9/17]
template<> unsigned int Eluna::CHECKVAL (lua_State * luastate, int narg) static
{
    return CheckUnsignedRange(luastate, narg, UINT_MAX);
}
References CheckUnsignedRange().
CHECKVAL() [10/17]
template<> const char * Eluna::CHECKVAL (lua_State * luastate, int narg) static
{
    return luaL_checkstring(luastate, narg);
}
References luaL_checkstring.
CHECKVAL() [11/17]
template<> long long Eluna::CHECKVAL (lua_State * luastate, int narg) static
{
    if (lua_isnumber(luastate, narg))
        return static_cast<long long>(CHECKVAL<double>(luastate, narg));
    return *(Eluna::CHECKOBJ<long long>(luastate, narg, true));
}
References lua_isnumber().
CHECKVAL() [12/17]
template<> unsigned long long Eluna::CHECKVAL (lua_State * luastate, int narg) static
{
    if (lua_isnumber(luastate, narg))
        return static_cast<unsigned long long>(CHECKVAL<uint32>(luastate, narg));
    return *(Eluna::CHECKOBJ<unsigned long long>(luastate, narg, true));
}
References lua_isnumber().
CHECKVAL() [13/17]
template<> long Eluna::CHECKVAL (lua_State * luastate, int narg) static
{
    return static_cast<long>(CHECKVAL<long long>(luastate, narg));
}
CHECKVAL() [14/17]
template<> unsigned long Eluna::CHECKVAL (lua_State * luastate, int narg) static
{
    return static_cast<unsigned long>(CHECKVAL<unsigned long long>(luastate, narg));
}
CHECKVAL() [15/17]
template<> ObjectGuid Eluna::CHECKVAL (lua_State * luastate, int narg) static
{
    return ObjectGuid(uint64((CHECKVAL<unsigned long long>(luastate, narg))));
}
CHECKVAL() [16/17]
template<typename T > static T Eluna::CHECKVAL (lua_State * luastate, int narg) static
CHECKVAL() [17/17]
template<typename T > static T Eluna::CHECKVAL (lua_State * luastate, int narg, T def) inline static
    {
        return lua_isnoneornil(luastate, narg) ? def : CHECKVAL<T>(luastate, narg);
    }
References lua_isnoneornil.
CleanUpStack()
void Eluna::CleanUpStack (int number_of_arguments) private
{
    // Stack: event_id, [arguments]
    lua_pop(L, number_of_arguments + 1); // Add 1 because the caller doesn't know about `event_id`.
    // Stack: (empty)
    if (event_level == 0)
        InvalidateObjects();
}
References event_level, InvalidateObjects(), L, and lua_pop.
Referenced by CallAllFunctions(), CallAllFunctionsBool(), CorpseRemoved(), DamageTaken(), OnCanUseItem(), OnChat(), OnChat(), OnChat(), OnChat(), OnChat(), OnGiveXP(), OnMemberDepositMoney(), OnMemberWitdrawMoney(), OnMoneyChanged(), OnPacketReceiveAny(), OnPacketReceiveOne(), OnPacketSendAny(), OnPacketSendOne(), and OnReputationChange().
CloseLua()
void Eluna::CloseLua () private
{
    OnLuaStateClose();
    DestroyBindStores();
    // Must close lua state after deleting stores and mgr
    if (L)
        lua_close(L);
    L = NULL;
    instanceDataRefs.clear();
    continentDataRefs.clear();
}
References continentDataRefs, DestroyBindStores(), instanceDataRefs, L, lua_close(), and OnLuaStateClose().
Referenced by ~Eluna().
CorpseRemoved()
bool Eluna::CorpseRemoved (Creature * me, uint32 & respawnDelay)
{
    START_HOOK_WITH_RETVAL(CREATURE_EVENT_ON_CORPSE_REMOVED, me, false);
    bool result = false;
    Push(me);
    Push(respawnDelay);
    int respawnDelayIndex = lua_gettop(L);
    int n = SetupStack(CreatureEventBindings, CreatureUniqueBindings, entry_key, unique_key, 2);
    while (n > 0)
    {
        int r = CallOneFunction(n--, 2, 2);
        if (lua_isboolean(L, r + 0) && lua_toboolean(L, r + 0))
            result = true;
        if (lua_isnumber(L, r + 1))
        {
            respawnDelay = Eluna::CHECKVAL<uint32>(L, r + 1);
            // Update the stack for subsequent calls.
            ReplaceArgument(respawnDelay, respawnDelayIndex);
        }
        lua_pop(L, 2);
    }
    CleanUpStack(2);
    return result;
}
References CallOneFunction(), CleanUpStack(), Hooks::CREATURE_EVENT_ON_CORPSE_REMOVED, CreatureEventBindings, CreatureUniqueBindings, L, lua_gettop(), lua_isboolean, lua_isnumber(), lua_pop, lua_toboolean(), Push(), ReplaceArgument(), SetupStack(), and START_HOOK_WITH_RETVAL.
CreateBindStores()
void Eluna::CreateBindStores () private
{
    DestroyBindStores();
    ServerEventBindings      = new BindingMap< EventKey<Hooks::ServerEvents> >(L);
    PlayerEventBindings      = new BindingMap< EventKey<Hooks::PlayerEvents> >(L);
    GuildEventBindings       = new BindingMap< EventKey<Hooks::GuildEvents> >(L);
    GroupEventBindings       = new BindingMap< EventKey<Hooks::GroupEvents> >(L);
    VehicleEventBindings     = new BindingMap< EventKey<Hooks::VehicleEvents> >(L);
    BGEventBindings          = new BindingMap< EventKey<Hooks::BGEvents> >(L);
    PacketEventBindings      = new BindingMap< EntryKey<Hooks::PacketEvents> >(L);
    CreatureEventBindings    = new BindingMap< EntryKey<Hooks::CreatureEvents> >(L);
    CreatureGossipBindings   = new BindingMap< EntryKey<Hooks::GossipEvents> >(L);
    GameObjectEventBindings  = new BindingMap< EntryKey<Hooks::GameObjectEvents> >(L);
    GameObjectGossipBindings = new BindingMap< EntryKey<Hooks::GossipEvents> >(L);
    ItemEventBindings        = new BindingMap< EntryKey<Hooks::ItemEvents> >(L);
    ItemGossipBindings       = new BindingMap< EntryKey<Hooks::GossipEvents> >(L);
    PlayerGossipBindings     = new BindingMap< EntryKey<Hooks::GossipEvents> >(L);
    MapEventBindings         = new BindingMap< EntryKey<Hooks::InstanceEvents> >(L);
    InstanceEventBindings    = new BindingMap< EntryKey<Hooks::InstanceEvents> >(L);
    CreatureUniqueBindings   = new BindingMap< UniqueObjectKey<Hooks::CreatureEvents> >(L);
}
References BGEventBindings, CreatureEventBindings, CreatureGossipBindings, CreatureUniqueBindings, DestroyBindStores(), GameObjectEventBindings, GameObjectGossipBindings, GroupEventBindings, GuildEventBindings, InstanceEventBindings, ItemEventBindings, ItemGossipBindings, L, MapEventBindings, PacketEventBindings, PlayerEventBindings, PlayerGossipBindings, ServerEventBindings, and VehicleEventBindings.
Referenced by OpenLua().
CreateInstanceData()
void Eluna::CreateInstanceData (Map const * map)
{
    ASSERT(lua_istable(L, -1));
    int ref = luaL_ref(L, LUA_REGISTRYINDEX);
    if (!map->Instanceable())
    {
        uint32 mapId = map->GetId();
        // If there's another table that was already stored for the map, unref it.
        auto mapRef = continentDataRefs.find(mapId);
        if (mapRef != continentDataRefs.end())
        {
            luaL_unref(L, LUA_REGISTRYINDEX, mapRef->second);
        }
        continentDataRefs[mapId] = ref;
    }
    else
    {
        uint32 instanceId = map->GetInstanceId();
        // If there's another table that was already stored for the instance, unref it.
        auto instRef = instanceDataRefs.find(instanceId);
        if (instRef != instanceDataRefs.end())
        {
            luaL_unref(L, LUA_REGISTRYINDEX, instRef->second);
        }
        instanceDataRefs[instanceId] = ref;
    }
}
References ASSERT, continentDataRefs, Map::GetId(), Map::GetInstanceId(), Map::Instanceable(), instanceDataRefs, L, lua_istable, LUA_REGISTRYINDEX, luaL_ref(), and luaL_unref().
DamageTaken()
bool Eluna::DamageTaken (Creature * me, Unit * attacker, uint32 & damage)
{
    START_HOOK_WITH_RETVAL(CREATURE_EVENT_ON_DAMAGE_TAKEN, me, false);
    bool result = false;
    Push(me);
    Push(attacker);
    Push(damage);
    int damageIndex = lua_gettop(L);
    int n = SetupStack(CreatureEventBindings, CreatureUniqueBindings, entry_key, unique_key, 3);
    while (n > 0)
    {
        int r = CallOneFunction(n--, 3, 2);
        if (lua_isboolean(L, r + 0) && lua_toboolean(L, r + 0))
            result = true;
        if (lua_isnumber(L, r + 1))
        {
            damage = Eluna::CHECKVAL<uint32>(L, r + 1);
            // Update the stack for subsequent calls.
            ReplaceArgument(damage, damageIndex);
        }
        lua_pop(L, 2);
    }
    CleanUpStack(3);
    return result;
}
References CallOneFunction(), CleanUpStack(), Hooks::CREATURE_EVENT_ON_DAMAGE_TAKEN, CreatureEventBindings, CreatureUniqueBindings, L, lua_gettop(), lua_isboolean, lua_isnumber(), lua_pop, lua_toboolean(), Push(), ReplaceArgument(), SetupStack(), and START_HOOK_WITH_RETVAL.
DestroyBindStores()
void Eluna::DestroyBindStores () private
{
    delete ServerEventBindings;
    delete PlayerEventBindings;
    delete GuildEventBindings;
    delete GroupEventBindings;
    delete VehicleEventBindings;
    delete PacketEventBindings;
    delete CreatureEventBindings;
    delete CreatureGossipBindings;
    delete GameObjectEventBindings;
    delete GameObjectGossipBindings;
    delete ItemEventBindings;
    delete ItemGossipBindings;
    delete PlayerGossipBindings;
    delete BGEventBindings;
    delete MapEventBindings;
    delete InstanceEventBindings;
    delete CreatureUniqueBindings;
    ServerEventBindings = NULL;
    PlayerEventBindings = NULL;
    GuildEventBindings = NULL;
    GroupEventBindings = NULL;
    VehicleEventBindings = NULL;
    PacketEventBindings = NULL;
    CreatureEventBindings = NULL;
    CreatureGossipBindings = NULL;
    GameObjectEventBindings = NULL;
    GameObjectGossipBindings = NULL;
    ItemEventBindings = NULL;
    ItemGossipBindings = NULL;
    PlayerGossipBindings = NULL;
    BGEventBindings = NULL;
    MapEventBindings = NULL;
    InstanceEventBindings = NULL;
    CreatureUniqueBindings = NULL;
}
References BGEventBindings, CreatureEventBindings, CreatureGossipBindings, CreatureUniqueBindings, GameObjectEventBindings, GameObjectGossipBindings, GroupEventBindings, GuildEventBindings, InstanceEventBindings, ItemEventBindings, ItemGossipBindings, MapEventBindings, PacketEventBindings, PlayerEventBindings, PlayerGossipBindings, ServerEventBindings, and VehicleEventBindings.
Referenced by CloseLua(), and CreateBindStores().
EnterCombat()
bool Eluna::EnterCombat (Creature * me, Unit * target)
{
    START_HOOK_WITH_RETVAL(CREATURE_EVENT_ON_ENTER_COMBAT, me, false);
    Push(me);
    Push(target);
    return CallAllFunctionsBool(CreatureEventBindings, CreatureUniqueBindings, entry_key, unique_key);
}
References CallAllFunctionsBool(), Hooks::CREATURE_EVENT_ON_ENTER_COMBAT, CreatureEventBindings, CreatureUniqueBindings, Push(), and START_HOOK_WITH_RETVAL.
EnterEvadeMode()
bool Eluna::EnterEvadeMode (Creature * me)
{
    On_Reset(me);
    START_HOOK_WITH_RETVAL(CREATURE_EVENT_ON_LEAVE_COMBAT, me, false);
    Push(me);
    return CallAllFunctionsBool(CreatureEventBindings, CreatureUniqueBindings, entry_key, unique_key);
}
References CallAllFunctionsBool(), Hooks::CREATURE_EVENT_ON_LEAVE_COMBAT, CreatureEventBindings, CreatureUniqueBindings, On_Reset(), Push(), and START_HOOK_WITH_RETVAL.
ExecuteCall()
bool Eluna::ExecuteCall (int params, int res)
{
    int top = lua_gettop(L);
    int base = top - params;
    // Expected: function, [parameters]
    ASSERT(base > 0);
    // Check function type
    if (!lua_isfunction(L, base))
    {
        ELUNA_LOG_ERROR("[Eluna]: Cannot execute call: registered value is {}, not a function.", luaL_tolstring(L, base, NULL));
        ASSERT(false); // stack probably corrupt
    }
#if defined(AZEROTHCORE)
    bool usetrace = eConfigMgr->GetOption<bool>("Eluna.TraceBack", false);
#else
    bool usetrace = eConfigMgr->GetBoolDefault("Eluna.TraceBack", false);
#endif
    if (usetrace)
    {
        lua_pushcfunction(L, &StackTrace);
        // Stack: function, [parameters], traceback
        lua_insert(L, base);
        // Stack: traceback, function, [parameters]
    }
    // Objects are invalidated when event_level hits 0
    ++event_level;
    int result = lua_pcall(L, params, res, usetrace ? base : 0);
    --event_level;
    if (usetrace)
    {
        // Stack: traceback, [results or errmsg]
        lua_remove(L, base);
    }
    // Stack: [results or errmsg]
    // lua_pcall returns 0 on success.
    // On error print the error and push nils for expected amount of returned values
    if (result)
    {
        // Stack: errmsg
        Report(L);
        // Force garbage collect
        lua_gc(L, LUA_GCCOLLECT, 0);
        // Push nils for expected amount of results
        for (int i = 0; i < res; ++i)
            lua_pushnil(L);
        // Stack: [nils]
        return false;
    }
    // Stack: [results]
    return true;
}
References ASSERT, eConfigMgr, ELUNA_LOG_ERROR, event_level, L, lua_gc(), LUA_GCCOLLECT, lua_gettop(), lua_insert(), lua_isfunction, lua_pcall, lua_pushcfunction, lua_pushnil(), lua_remove(), luaL_tolstring(), params, Report(), and StackTrace().
Referenced by CallOneFunction(), HttpManager::HandleHttpResponses(), OnTimedEvent(), and RunScripts().
FreeInstanceId()
void Eluna::FreeInstanceId (uint32 instanceId)
{
    LOCK_ELUNA;
    if (!IsEnabled())
        return;
    for (int i = 1; i < Hooks::INSTANCE_EVENT_COUNT; ++i)
    {
        auto key = EntryKey<Hooks::InstanceEvents>((Hooks::InstanceEvents)i, instanceId);
        if (MapEventBindings->HasBindingsFor(key))
            MapEventBindings->Clear(key);
        if (InstanceEventBindings->HasBindingsFor(key))
            InstanceEventBindings->Clear(key);
        if (instanceDataRefs.find(instanceId) != instanceDataRefs.end())
        {
            luaL_unref(L, LUA_REGISTRYINDEX, instanceDataRefs[instanceId]);
            instanceDataRefs.erase(instanceId);
        }
    }
}
References BindingMap< K >::Clear(), BindingMap< K >::HasBindingsFor(), Hooks::INSTANCE_EVENT_COUNT, instanceDataRefs, InstanceEventBindings, IsEnabled(), L, LOCK_ELUNA, LUA_REGISTRYINDEX, luaL_unref(), and MapEventBindings.
GetAI()
CreatureAI * Eluna::GetAI (Creature * creature)
{
    if (!IsEnabled())
        return NULL;
    for (int i = 1; i < Hooks::CREATURE_EVENT_COUNT; ++i)
    {
        Hooks::CreatureEvents event_id = (Hooks::CreatureEvents)i;
        auto entryKey = EntryKey<Hooks::CreatureEvents>(event_id, creature->GetEntry());
        auto uniqueKey = UniqueObjectKey<Hooks::CreatureEvents>(event_id, creature->GET_GUID(), creature->GetInstanceId());
        if (CreatureEventBindings->HasBindingsFor(entryKey) ||
            CreatureUniqueBindings->HasBindingsFor(uniqueKey))
            return new ElunaCreatureAI(creature);
    }
    return NULL;
}
References Hooks::CREATURE_EVENT_COUNT, CreatureEventBindings, CreatureUniqueBindings, Object::GetEntry(), WorldObject::GetInstanceId(), BindingMap< K >::HasBindingsFor(), and IsEnabled().
GetCallstackId()
uint64 Eluna::GetCallstackId () const inline
{ return callstackid; }
GetDialogStatus() [1/2]
void Eluna::GetDialogStatus (const Player * pPlayer, const Creature * pCreature)
{
    START_HOOK(CREATURE_EVENT_ON_DIALOG_STATUS, pCreature);
    Push(pPlayer);
    Push(pCreature);
    CallAllFunctions(CreatureEventBindings, CreatureUniqueBindings, entry_key, unique_key);
}
References CallAllFunctions(), Hooks::CREATURE_EVENT_ON_DIALOG_STATUS, CreatureEventBindings, CreatureUniqueBindings, Push(), and START_HOOK.
GetDialogStatus() [2/2]
void Eluna::GetDialogStatus (const Player * pPlayer, const GameObject * pGameObject)
{
    START_HOOK(GAMEOBJECT_EVENT_ON_DIALOG_STATUS, pGameObject->GetEntry());
    Push(pPlayer);
    Push(pGameObject);
    CallAllFunctions(GameObjectEventBindings, key);
}
References CallAllFunctions(), Hooks::GAMEOBJECT_EVENT_ON_DIALOG_STATUS, GameObjectEventBindings, Object::GetEntry(), Push(), and START_HOOK.
GetEluna()
static Eluna * Eluna::GetEluna (lua_State * L) inline static
    {
        lua_pushstring(L, ELUNA_STATE_PTR);
        lua_rawget(L, LUA_REGISTRYINDEX);
        ASSERT(lua_islightuserdata(L, -1));
        Eluna* E = static_cast<Eluna*>(lua_touserdata(L, -1));
        lua_pop(L, 1);
        ASSERT(E);
        return E;
    }
References ASSERT, ELUNA_STATE_PTR, lua_islightuserdata, lua_pop, lua_pushstring(), lua_rawget(), LUA_REGISTRYINDEX, and lua_touserdata().
Referenced by LuaGlobalFunctions::ClearBattleGroundEvents(), LuaGlobalFunctions::ClearCreatureEvents(), LuaGlobalFunctions::ClearCreatureGossipEvents(), LuaGlobalFunctions::ClearGameObjectEvents(), LuaGlobalFunctions::ClearGameObjectGossipEvents(), LuaGlobalFunctions::ClearGroupEvents(), LuaGlobalFunctions::ClearGuildEvents(), LuaGlobalFunctions::ClearInstanceEvents(), LuaGlobalFunctions::ClearItemEvents(), LuaGlobalFunctions::ClearItemGossipEvents(), LuaGlobalFunctions::ClearMapEvents(), LuaGlobalFunctions::ClearPacketEvents(), LuaGlobalFunctions::ClearPlayerEvents(), LuaGlobalFunctions::ClearPlayerGossipEvents(), LuaGlobalFunctions::ClearServerEvents(), LuaGlobalFunctions::ClearUniqueCreatureEvents(), LuaGlobalFunctions::CreateLuaEvent(), LuaMap::GetInstanceData(), LuaGlobalFunctions::RegisterEntryHelper(), LuaGlobalFunctions::RegisterEventHelper(), LuaGlobalFunctions::RegisterUniqueHelper(), LuaGlobalFunctions::RemoveEventById(), and LuaGlobalFunctions::RemoveEvents().
GetInstanceData()
InstanceData * Eluna::GetInstanceData (Map * map)
{
    if (!IsEnabled())
        return NULL;
    for (int i = 1; i < Hooks::INSTANCE_EVENT_COUNT; ++i)
    {
        Hooks::InstanceEvents event_id = (Hooks::InstanceEvents)i;
        auto key = EntryKey<Hooks::InstanceEvents>(event_id, map->GetId());
        if (MapEventBindings->HasBindingsFor(key) ||
            InstanceEventBindings->HasBindingsFor(key))
            return new ElunaInstanceAI(map);
    }
    return NULL;
}
References Map::GetId(), BindingMap< K >::HasBindingsFor(), Hooks::INSTANCE_EVENT_COUNT, InstanceEventBindings, IsEnabled(), and MapEventBindings.
GetLock()
static LockType & Eluna::GetLock () inline static
{ return lock; };
GetScripts()
void Eluna::GetScripts (std::string path) static private
{
    ELUNA_LOG_DEBUG("[Eluna]: GetScripts from path `{}`", path);
#ifdef USING_BOOST
    boost::filesystem::path someDir(path);
    boost::filesystem::directory_iterator end_iter;
    if (boost::filesystem::exists(someDir) && boost::filesystem::is_directory(someDir))
    {
        lua_requirepath +=
            path + "/?.lua;" +
            path + "/?.ext;" +
            path + "/?.dll;" +
            path + "/?.so;";
        for (boost::filesystem::directory_iterator dir_iter(someDir); dir_iter != end_iter; ++dir_iter)
        {
            std::string fullpath = dir_iter->path().generic_string();
            // Check if file is hidden
#ifdef ELUNA_WINDOWS
            DWORD dwAttrib = GetFileAttributes(fullpath.c_str());
            if (dwAttrib != INVALID_FILE_ATTRIBUTES && (dwAttrib & FILE_ATTRIBUTE_HIDDEN))
                continue;
#else
            std::string name = dir_iter->path().filename().generic_string().c_str();
            if (name[0] == '.')
                continue;
#endif
            // load subfolder
            if (boost::filesystem::is_directory(dir_iter->status()))
            {
                GetScripts(fullpath);
                continue;
            }
            if (boost::filesystem::is_regular_file(dir_iter->status()))
            {
                // was file, try add
                std::string filename = dir_iter->path().filename().generic_string();
                AddScriptPath(filename, fullpath);
            }
        }
    }
#else
    ACE_Dirent dir;
    if (dir.open(path.c_str()) == -1) // Error opening directory, return
        return;
    lua_requirepath +=
        path + "/?.lua;" +
        path + "/?.ext;" +
        path + "/?.dll;" +
        path + "/?.so;";
    ACE_DIRENT *directory = 0;
    while ((directory = dir.read()))
    {
        // Skip the ".." and "." files.
        if (ACE::isdotdir(directory->d_name))
            continue;
        std::string fullpath = path + "/" + directory->d_name;
        // Check if file is hidden
#ifdef ELUNA_WINDOWS
        DWORD dwAttrib = GetFileAttributes(fullpath.c_str());
        if (dwAttrib != INVALID_FILE_ATTRIBUTES && (dwAttrib & FILE_ATTRIBUTE_HIDDEN))
            continue;
#else
        std::string name = directory->d_name;
        if (name[0] == '.')
            continue;
#endif
        ACE_stat stat_buf;
        if (ACE_OS::lstat(fullpath.c_str(), &stat_buf) == -1)
            continue;
        // load subfolder
        if ((stat_buf.st_mode & S_IFMT) == (S_IFDIR))
        {
            GetScripts(fullpath);
            continue;
        }
        // was file, try add
        std::string filename = directory->d_name;
        AddScriptPath(filename, fullpath);
    }
#endif
}
References AddScriptPath(), ELUNA_LOG_DEBUG, GetScripts(), and lua_requirepath.
Referenced by GetScripts(), and LoadScriptPaths().
HandleGossipSelectOption() [1/2]
void Eluna::HandleGossipSelectOption (Player * pPlayer, Item * item, uint32 sender, uint32 action, const std::string & code)
{
    START_HOOK(ItemGossipBindings, GOSSIP_EVENT_ON_SELECT, pItem->GetEntry());
    pPlayer->PlayerTalkClass->ClearMenus();
    Push(pPlayer);
    Push(pItem);
    Push(sender);
    Push(action);
    if (code.empty())
        Push();
    else
        Push(code);
    CallAllFunctions(ItemGossipBindings, key);
}
References CallAllFunctions(), PlayerMenu::ClearMenus(), Object::GetEntry(), Hooks::GOSSIP_EVENT_ON_SELECT, ItemGossipBindings, Player::PlayerTalkClass, Push(), and START_HOOK.
HandleGossipSelectOption() [2/2]
void Eluna::HandleGossipSelectOption (Player * pPlayer, uint32 menuId, uint32 sender, uint32 action, const std::string & code)
{
    START_HOOK(PlayerGossipBindings, GOSSIP_EVENT_ON_SELECT, menuId);
    pPlayer->PlayerTalkClass->ClearMenus();
    Push(pPlayer); // receiver
    Push(pPlayer); // sender, just not to mess up the amount of args.
    Push(sender);
    Push(action);
    if (code.empty())
        Push();
    else
        Push(code);
    CallAllFunctions(PlayerGossipBindings, key);
}
References CallAllFunctions(), PlayerMenu::ClearMenus(), Hooks::GOSSIP_EVENT_ON_SELECT, PlayerGossipBindings, Player::PlayerTalkClass, Push(), and START_HOOK.
HasInstanceData()
bool Eluna::HasInstanceData (Map const * map)
{
    if (!map->Instanceable())
        return continentDataRefs.find(map->GetId()) != continentDataRefs.end();
    else
        return instanceDataRefs.find(map->GetInstanceId()) != instanceDataRefs.end();
}
References continentDataRefs, Map::GetId(), Map::GetInstanceId(), Map::Instanceable(), and instanceDataRefs.
Referenced by PushInstanceData().
HasLuaState()
bool Eluna::HasLuaState () const inline
{ return L != NULL; }
Initialize()
void Eluna::Initialize () static
{
    LOCK_ELUNA;
    ASSERT(!IsInitialized());
#if defined TRINITY || AZEROTHCORE
    // For instance data the data column needs to be able to hold more than 255 characters (tinytext)
    // so we change it to TEXT automatically on startup
    CharacterDatabase.DirectExecute("ALTER TABLE `instance` CHANGE COLUMN `data` `data` TEXT NOT NULL");
#endif
    LoadScriptPaths();
    // Must be before creating GEluna
    // This is checked on Eluna creation
    initialized = true;
    // Create global eluna
    GEluna = new Eluna();
}
References ASSERT, CharacterDatabase, Eluna(), GEluna, initialized, IsInitialized(), LoadScriptPaths(), and LOCK_ELUNA.
Referenced by Eluna_WorldScript::OnBeforeConfigLoad().
InvalidateObjects()
void Eluna::InvalidateObjects () private
{
    ++callstackid;
#ifdef TRINITY
    ASSERT(callstackid, "Callstackid overflow");
#else
    ASSERT(callstackid && "Callstackid overflow");
#endif
}
References ASSERT, and callstackid.
Referenced by CleanUpStack(), and OnTimedEvent().
IsEnabled()
bool Eluna::IsEnabled () const inline
{ return enabled && IsInitialized(); }
Referenced by FreeInstanceId(), GetAI(), GetInstanceData(), OpenLua(), and RunScripts().
IsInitialized()
static bool Eluna::IsInitialized () inline static
{ return initialized; }
Referenced by _ReloadEluna(), Eluna(), Initialize(), ElunaEventProcessor::RemoveEvent(), Uninitialize(), ~Eluna(), and ElunaEventProcessor::~ElunaEventProcessor().
JustDied()
bool Eluna::JustDied (Creature * me, Unit * killer)
{
    On_Reset(me);
    START_HOOK_WITH_RETVAL(CREATURE_EVENT_ON_DIED, me, false);
    Push(me);
    Push(killer);
    return CallAllFunctionsBool(CreatureEventBindings, CreatureUniqueBindings, entry_key, unique_key);
}
References CallAllFunctionsBool(), Hooks::CREATURE_EVENT_ON_DIED, CreatureEventBindings, CreatureUniqueBindings, On_Reset(), Push(), and START_HOOK_WITH_RETVAL.
JustReachedHome()
bool Eluna::JustReachedHome (Creature * me)
{
    START_HOOK_WITH_RETVAL(CREATURE_EVENT_ON_REACH_HOME, me, false);
    Push(me);
    return CallAllFunctionsBool(CreatureEventBindings, CreatureUniqueBindings, entry_key, unique_key);
}
References CallAllFunctionsBool(), Hooks::CREATURE_EVENT_ON_REACH_HOME, CreatureEventBindings, CreatureUniqueBindings, Push(), and START_HOOK_WITH_RETVAL.
JustRespawned()
bool Eluna::JustRespawned (Creature * me)
{
    On_Reset(me);
    START_HOOK_WITH_RETVAL(CREATURE_EVENT_ON_SPAWN, me, false);
    Push(me);
    return CallAllFunctionsBool(CreatureEventBindings, CreatureUniqueBindings, entry_key, unique_key);
}
References CallAllFunctionsBool(), Hooks::CREATURE_EVENT_ON_SPAWN, CreatureEventBindings, CreatureUniqueBindings, On_Reset(), Push(), and START_HOOK_WITH_RETVAL.
JustSummoned()
bool Eluna::JustSummoned (Creature * me, Creature * summon)
{
    START_HOOK_WITH_RETVAL(CREATURE_EVENT_ON_JUST_SUMMONED_CREATURE, me, false);
    Push(me);
    Push(summon);
    return CallAllFunctionsBool(CreatureEventBindings, CreatureUniqueBindings, entry_key, unique_key);
}
References CallAllFunctionsBool(), Hooks::CREATURE_EVENT_ON_JUST_SUMMONED_CREATURE, CreatureEventBindings, CreatureUniqueBindings, Push(), and START_HOOK_WITH_RETVAL.
KilledUnit()
bool Eluna::KilledUnit (Creature * me, Unit * victim)
{
    START_HOOK_WITH_RETVAL(CREATURE_EVENT_ON_TARGET_DIED, me, false);
    Push(me);
    Push(victim);
    return CallAllFunctionsBool(CreatureEventBindings, CreatureUniqueBindings, entry_key, unique_key);
}
References CallAllFunctionsBool(), Hooks::CREATURE_EVENT_ON_TARGET_DIED, CreatureEventBindings, CreatureUniqueBindings, Push(), and START_HOOK_WITH_RETVAL.
LoadScriptPaths()
void Eluna::LoadScriptPaths () static private
{
    uint32 oldMSTime = ElunaUtil::GetCurrTime();
    lua_scripts.clear();
    lua_extensions.clear();
#if defined(AZEROTHCORE)
    lua_folderpath = eConfigMgr->GetOption<std::string>("Eluna.ScriptPath", "lua_scripts");
#else
    lua_folderpath = eConfigMgr->GetStringDefault("Eluna.ScriptPath", "lua_scripts");
#endif
#ifndef ELUNA_WINDOWS
    if (lua_folderpath[0] == '~')
        if (const char* home = getenv("HOME"))
            lua_folderpath.replace(0, 1, home);
#endif
    ELUNA_LOG_INFO("[Eluna]: Searching scripts from `{}`", lua_folderpath);
    lua_requirepath.clear();
    GetScripts(lua_folderpath);
    // Erase last ;
    if (!lua_requirepath.empty())
        lua_requirepath.erase(lua_requirepath.end() - 1);
    ELUNA_LOG_DEBUG("[Eluna]: Loaded {} scripts in {} ms", lua_scripts.size() + lua_extensions.size(), ElunaUtil::GetTimeDiff(oldMSTime));
}
References eConfigMgr, ELUNA_LOG_DEBUG, ELUNA_LOG_INFO, ElunaUtil::GetCurrTime(), GetScripts(), ElunaUtil::GetTimeDiff(), lua_extensions, lua_folderpath, lua_requirepath, and lua_scripts.
Referenced by _ReloadEluna(), and Initialize().
MoveInLineOfSight()
bool Eluna::MoveInLineOfSight (Creature * me, Unit * who)
{
    START_HOOK_WITH_RETVAL(CREATURE_EVENT_ON_MOVE_IN_LOS, me, false);
    Push(me);
    Push(who);
    return CallAllFunctionsBool(CreatureEventBindings, CreatureUniqueBindings, entry_key, unique_key);
}
References CallAllFunctionsBool(), Hooks::CREATURE_EVENT_ON_MOVE_IN_LOS, CreatureEventBindings, CreatureUniqueBindings, Push(), and START_HOOK_WITH_RETVAL.
MovementInform()
bool Eluna::MovementInform (Creature * me, uint32 type, uint32 id)
{
    START_HOOK_WITH_RETVAL(CREATURE_EVENT_ON_REACH_WP, me, false);
    Push(me);
    Push(type);
    Push(id);
    return CallAllFunctionsBool(CreatureEventBindings, CreatureUniqueBindings, entry_key, unique_key);
}
References CallAllFunctionsBool(), Hooks::CREATURE_EVENT_ON_REACH_WP, CreatureEventBindings, CreatureUniqueBindings, Push(), and START_HOOK_WITH_RETVAL.
On_Reset()
void Eluna::On_Reset (Creature * me)
{
    START_HOOK(CREATURE_EVENT_ON_RESET, me);
    Push(me);
    CallAllFunctions(CreatureEventBindings, CreatureUniqueBindings, entry_key, unique_key);
}
References CallAllFunctions(), Hooks::CREATURE_EVENT_ON_RESET, CreatureEventBindings, CreatureUniqueBindings, Push(), and START_HOOK.
Referenced by EnterEvadeMode(), JustDied(), and JustRespawned().
OnAchiComplete()
void Eluna::OnAchiComplete (Player * player, AchievementEntry const * achievement)
{
    START_HOOK(PLAYER_EVENT_ON_ACHIEVEMENT_COMPLETE);
    Push(player);
    Push(achievement);
    CallAllFunctions(PlayerEventBindings, key);
}
References CallAllFunctions(), Hooks::PLAYER_EVENT_ON_ACHIEVEMENT_COMPLETE, PlayerEventBindings, Push(), and START_HOOK.
OnAdd()
void Eluna::OnAdd (AuctionHouseObject * ah, AuctionEntry * entry)
{
#ifdef AZEROTHCORE
    Player* owner = eObjectAccessor()FindPlayer(entry->owner);
#else
    Player* owner = eObjectAccessor()FindPlayer(MAKE_NEW_GUID(entry->owner, 0, HIGHGUID_PLAYER));
#endif
#ifdef TRINITY
    Item* item = eAuctionMgr->GetAItem(entry->itemGUIDLow);
    uint32 expiretime = entry->expire_time;
#elif AZEROTHCORE
    Item* item = eAuctionMgr->GetAItem(entry->item_guid);
    uint32 expiretime = entry->expire_time;
#else
    Item* item = eAuctionMgr->GetAItem(entry->itemGuidLow);
    uint32 expiretime = entry->expireTime;
#endif
    if (!owner || !item)
        return;
    START_HOOK(AUCTION_EVENT_ON_ADD);
    Push(entry->Id);
    Push(owner);
    Push(item);
    Push(expiretime);
    Push(entry->buyout);
    Push(entry->startbid);
    Push(entry->bid);
    Push(entry->bidder);
    CallAllFunctions(ServerEventBindings, key);
}
References Hooks::AUCTION_EVENT_ON_ADD, AuctionEntry::bid, AuctionEntry::bidder, AuctionEntry::buyout, CallAllFunctions(), eAuctionMgr, eObjectAccessor, AuctionEntry::expire_time, AuctionEntry::Id, AuctionEntry::item_guid, AuctionEntry::owner, Push(), ServerEventBindings, START_HOOK, and AuctionEntry::startbid.
OnAddMember() [1/2]
void Eluna::OnAddMember (Group * group, ObjectGuid guid)
{
    START_HOOK(GROUP_EVENT_ON_MEMBER_ADD);
    Push(group);
    Push(guid);
    CallAllFunctions(GroupEventBindings, key);
}
References CallAllFunctions(), Hooks::GROUP_EVENT_ON_MEMBER_ADD, GroupEventBindings, Push(), and START_HOOK.
OnAddMember() [2/2]
void Eluna::OnAddMember (Guild * guild, Player * player, uint32 plRank)
{
    START_HOOK(GUILD_EVENT_ON_ADD_MEMBER);
    Push(guild);
    Push(player);
    Push(plRank);
    CallAllFunctions(GuildEventBindings, key);
}
References CallAllFunctions(), Hooks::GUILD_EVENT_ON_ADD_MEMBER, GuildEventBindings, Push(), and START_HOOK.
OnAddonMessage()
bool Eluna::OnAddonMessage (Player * sender, uint32 type, std::string & msg, Player * receiver, Guild * guild, Group * group, Channel * channel)
{
    START_HOOK_WITH_RETVAL(ADDON_EVENT_ON_MESSAGE, true);
    Push(sender);
    Push(type);
    auto delimeter_position = msg.find('\t');
    if (delimeter_position == std::string::npos)
    {
        Push(msg); // prefix
        Push(); // msg
    }
    else
    {
        std::string prefix = msg.substr(0, delimeter_position);
        std::string content = msg.substr(delimeter_position + 1, std::string::npos);
        Push(prefix);
        Push(content);
    }
    if (receiver)
        Push(receiver);
    else if (guild)
        Push(guild);
    else if (group)
        Push(group);
    else if (channel)
        Push(channel->GetChannelId());
    else
        Push();
    return CallAllFunctionsBool(ServerEventBindings, key, true);
}
References Hooks::ADDON_EVENT_ON_MESSAGE, CallAllFunctionsBool(), Channel::GetChannelId(), Push(), ServerEventBindings, and START_HOOK_WITH_RETVAL.
Referenced by OnChat(), OnChat(), OnChat(), OnChat(), and OnChat().
OnAddPassenger()
void Eluna::OnAddPassenger (Vehicle * vehicle, Unit * passenger, int8 seatId)
{
    START_HOOK(VEHICLE_EVENT_ON_ADD_PASSENGER);
    Push(vehicle);
    Push(passenger);
    Push(seatId);
    CallAllFunctions(VehicleEventBindings, key);
}
References CallAllFunctions(), Push(), START_HOOK, Hooks::VEHICLE_EVENT_ON_ADD_PASSENGER, and VehicleEventBindings.
OnAddToWorld() [1/2]
void Eluna::OnAddToWorld (Creature * creature)
{
    START_HOOK(CREATURE_EVENT_ON_ADD, pCreature);
    Push(pCreature);
    CallAllFunctions(CreatureEventBindings, CreatureUniqueBindings, entry_key, unique_key);
}
References CallAllFunctions(), Hooks::CREATURE_EVENT_ON_ADD, CreatureEventBindings, CreatureUniqueBindings, Push(), and START_HOOK.
OnAddToWorld() [2/2]
void Eluna::OnAddToWorld (GameObject * gameobject)
{
    START_HOOK(GAMEOBJECT_EVENT_ON_ADD, pGameObject->GetEntry());
    Push(pGameObject);
    CallAllFunctions(GameObjectEventBindings, key);
}
References CallAllFunctions(), Hooks::GAMEOBJECT_EVENT_ON_ADD, GameObjectEventBindings, Object::GetEntry(), Push(), and START_HOOK.
OnAreaTrigger()
bool Eluna::OnAreaTrigger (Player * pPlayer, AreaTriggerEntry const * pTrigger)
{
    START_HOOK_WITH_RETVAL(TRIGGER_EVENT_ON_TRIGGER, false);
    Push(pPlayer);
#ifdef TRINITY
    Push(pTrigger->ID);
#elif AZEROTHCORE
    Push(pTrigger->entry);
#else
    Push(pTrigger->id);
#endif
    return CallAllFunctionsBool(ServerEventBindings, key);
}
References CallAllFunctionsBool(), Push(), ServerEventBindings, START_HOOK_WITH_RETVAL, and Hooks::TRIGGER_EVENT_ON_TRIGGER.
OnBankEvent()
void Eluna::OnBankEvent (Guild * guild, uint8 eventType, uint8 tabId, uint32 playerGuid, uint32 itemOrMoney, uint16 itemStackCount, uint8 destTabId)
{
    START_HOOK(GUILD_EVENT_ON_BANK_EVENT);
    Push(guild);
    Push(eventType);
    Push(tabId);
    Push(playerGuid);
    Push(itemOrMoney);
    Push(itemStackCount);
    Push(destTabId);
    CallAllFunctions(GuildEventBindings, key);
}
References CallAllFunctions(), Hooks::GUILD_EVENT_ON_BANK_EVENT, GuildEventBindings, Push(), and START_HOOK.
OnBattlegroundDesertion()
void Eluna::OnBattlegroundDesertion (Player * player, const BattlegroundDesertionType type)
{
    START_HOOK(PLAYER_EVENT_ON_BG_DESERTION);
    Push(player);
    Push(type);
    CallAllFunctions(PlayerEventBindings, key);
}
References CallAllFunctions(), Hooks::PLAYER_EVENT_ON_BG_DESERTION, PlayerEventBindings, Push(), and START_HOOK.
OnBGCreate()
void Eluna::OnBGCreate (BattleGround * bg, BattleGroundTypeId bgId, uint32 instanceId)
{
    START_HOOK(BG_EVENT_ON_CREATE);
    Push(bg);
    Push(bgId);
    Push(instanceId);
    CallAllFunctions(BGEventBindings, key);
}
References Hooks::BG_EVENT_ON_CREATE, BGEventBindings, CallAllFunctions(), Push(), and START_HOOK.
OnBGDestroy()
void Eluna::OnBGDestroy (BattleGround * bg, BattleGroundTypeId bgId, uint32 instanceId)
{
    START_HOOK(BG_EVENT_ON_PRE_DESTROY);
    Push(bg);
    Push(bgId);
    Push(instanceId);
    CallAllFunctions(BGEventBindings, key);
}
References Hooks::BG_EVENT_ON_PRE_DESTROY, BGEventBindings, CallAllFunctions(), Push(), and START_HOOK.
OnBGEnd()
void Eluna::OnBGEnd (BattleGround * bg, BattleGroundTypeId bgId, uint32 instanceId, Team winner)
{
    START_HOOK(BG_EVENT_ON_END);
    Push(bg);
    Push(bgId);
    Push(instanceId);
    Push(winner);
    CallAllFunctions(BGEventBindings, key);
}
References Hooks::BG_EVENT_ON_END, and START_HOOK.
OnBGStart()
void Eluna::OnBGStart (BattleGround * bg, BattleGroundTypeId bgId, uint32 instanceId)
{
    START_HOOK(BG_EVENT_ON_START);
    Push(bg);
    Push(bgId);
    Push(instanceId);
    CallAllFunctions(BGEventBindings, key);
}
References Hooks::BG_EVENT_ON_START, BGEventBindings, CallAllFunctions(), Push(), and START_HOOK.
OnBindToInstance()
void Eluna::OnBindToInstance (Player * pPlayer, Difficulty difficulty, uint32 mapid, bool permanent)
{
    START_HOOK(PLAYER_EVENT_ON_BIND_TO_INSTANCE);
    Push(pPlayer);
    Push(difficulty);
    Push(mapid);
    Push(permanent);
    CallAllFunctions(PlayerEventBindings, key);
}
References CallAllFunctions(), Hooks::PLAYER_EVENT_ON_BIND_TO_INSTANCE, PlayerEventBindings, Push(), and START_HOOK.
OnCanGroupInvite()
bool Eluna::OnCanGroupInvite (Player * player, std::string & memberName)
{
    START_HOOK_WITH_RETVAL(PLAYER_EVENT_ON_CAN_GROUP_INVITE, true);
    Push(player);
    Push(memberName);
    return CallAllFunctionsBool(PlayerEventBindings, key);
}
References CallAllFunctionsBool(), Hooks::PLAYER_EVENT_ON_CAN_GROUP_INVITE, PlayerEventBindings, Push(), and START_HOOK_WITH_RETVAL.
OnCanInitTrade()
bool Eluna::OnCanInitTrade (Player * player, Player * target)
{
    START_HOOK_WITH_RETVAL(PLAYER_EVENT_ON_CAN_INIT_TRADE, true);
    Push(player);
    Push(target);
    return CallAllFunctionsBool(PlayerEventBindings, key);
}
References CallAllFunctionsBool(), Hooks::PLAYER_EVENT_ON_CAN_INIT_TRADE, PlayerEventBindings, Push(), and START_HOOK_WITH_RETVAL.
OnCanJoinLfg()
bool Eluna::OnCanJoinLfg (Player * player, uint8 roles, lfg::LfgDungeonSet & dungeons, const std::string & comment)
{
    START_HOOK_WITH_RETVAL(PLAYER_EVENT_ON_CAN_JOIN_LFG, true);
    Push(player);
    Push(roles);
    lua_newtable(L);
    int table = lua_gettop(L);
    uint32 counter = 1;
    for (uint32 dungeon : dungeons)
    {
        Eluna::Push(L, dungeon);
        lua_rawseti(L, table, counter);
        ++counter;
    }
    lua_settop(L, table);
    ++push_counter;
    Push(comment);
    return CallAllFunctionsBool(PlayerEventBindings, key);
}
References CallAllFunctionsBool(), L, lua_gettop(), lua_newtable, lua_rawseti(), lua_settop(), Hooks::PLAYER_EVENT_ON_CAN_JOIN_LFG, PlayerEventBindings, Push(), push_counter, and START_HOOK_WITH_RETVAL.
OnCanSendMail()
bool Eluna::OnCanSendMail (Player * player, ObjectGuid receiverGuid, ObjectGuid mailbox, std::string & subject, std::string & body, uint32 money, uint32 cod, Item * item)
{
    START_HOOK_WITH_RETVAL(PLAYER_EVENT_ON_CAN_SEND_MAIL, true);
    Push(player);
    Push(receiverGuid);
    Push(mailbox);
    Push(subject);
    Push(body);
    Push(money);
    Push(cod);
    Push(item);
    return CallAllFunctionsBool(PlayerEventBindings, key);
}
References CallAllFunctionsBool(), Hooks::PLAYER_EVENT_ON_CAN_SEND_MAIL, PlayerEventBindings, Push(), and START_HOOK_WITH_RETVAL.
OnCanUseItem()
InventoryResult Eluna::OnCanUseItem (const Player * pPlayer, uint32 itemEntry)
{
    START_HOOK_WITH_RETVAL(PLAYER_EVENT_ON_CAN_USE_ITEM, EQUIP_ERR_OK);
    InventoryResult result = EQUIP_ERR_OK;
    Push(pPlayer);
    Push(itemEntry);
    int n = SetupStack(PlayerEventBindings, key, 2);
    while (n > 0)
    {
        int r = CallOneFunction(n--, 2, 1);
        if (lua_isnumber(L, r))
            result = (InventoryResult)CHECKVAL<uint32>(L, r);
        lua_pop(L, 1);
    }
    CleanUpStack(2);
    return result;
}
References CallOneFunction(), CleanUpStack(), EQUIP_ERR_OK, L, lua_isnumber(), lua_pop, Hooks::PLAYER_EVENT_ON_CAN_USE_ITEM, PlayerEventBindings, Push(), SetupStack(), and START_HOOK_WITH_RETVAL.
OnChange()
void Eluna::OnChange (Weather * weather, uint32 zone, WeatherState state, float grade)
{
    START_HOOK(WEATHER_EVENT_ON_CHANGE);
    Push(zone);
    Push(state);
    Push(grade);
    CallAllFunctions(ServerEventBindings, key);
}
References CallAllFunctions(), Push(), ServerEventBindings, START_HOOK, and Hooks::WEATHER_EVENT_ON_CHANGE.
OnChangeLeader()
void Eluna::OnChangeLeader (Group * group, ObjectGuid newLeaderGuid, ObjectGuid oldLeaderGuid)
{
    START_HOOK(GROUP_EVENT_ON_LEADER_CHANGE);
    Push(group);
    Push(newLeaderGuid);
    Push(oldLeaderGuid);
    CallAllFunctions(GroupEventBindings, key);
}
References CallAllFunctions(), Hooks::GROUP_EVENT_ON_LEADER_CHANGE, GroupEventBindings, Push(), and START_HOOK.
OnChat() [1/5]
bool Eluna::OnChat (Player * pPlayer, uint32 type, uint32 lang, std::string & msg)
{
    if (lang == LANG_ADDON)
        return OnAddonMessage(pPlayer, type, msg, NULL, NULL, NULL, NULL);
    START_HOOK_WITH_RETVAL(PLAYER_EVENT_ON_CHAT, true);
    bool result = true;
    Push(pPlayer);
    Push(msg);
    Push(type);
    Push(lang);
    int n = SetupStack(PlayerEventBindings, key, 4);
    while (n > 0)
    {
        int r = CallOneFunction(n--, 4, 2);
        if (lua_isboolean(L, r + 0) && !lua_toboolean(L, r + 0))
            result = false;
        if (lua_isstring(L, r + 1))
            msg = std::string(lua_tostring(L, r + 1));
        lua_pop(L, 2);
    }
    CleanUpStack(4);
    return result;
}
References CallOneFunction(), CleanUpStack(), L, LANG_ADDON, lua_isboolean, lua_isstring(), lua_pop, lua_toboolean(), lua_tostring, OnAddonMessage(), Hooks::PLAYER_EVENT_ON_CHAT, PlayerEventBindings, Push(), SetupStack(), and START_HOOK_WITH_RETVAL.
OnChat() [2/5]
bool Eluna::OnChat (Player * pPlayer, uint32 type, uint32 lang, std::string & msg, Channel * pChannel)
{
    if (lang == LANG_ADDON)
        return OnAddonMessage(pPlayer, type, msg, NULL, NULL, NULL, pChannel);
    START_HOOK_WITH_RETVAL(PLAYER_EVENT_ON_CHANNEL_CHAT, true);
    bool result = true;
    Push(pPlayer);
    Push(msg);
    Push(type);
    Push(lang);
    Push(pChannel->IsConstant() ? static_cast<int32>(pChannel->GetChannelId()) : -static_cast<int32>(pChannel->GetChannelDBId()));
    int n = SetupStack(PlayerEventBindings, key, 5);
    while (n > 0)
    {
        int r = CallOneFunction(n--, 5, 2);
        if (lua_isboolean(L, r + 0) && !lua_toboolean(L, r + 0))
            result = false;
        if (lua_isstring(L, r + 1))
            msg = std::string(lua_tostring(L, r + 1));
        lua_pop(L, 2);
    }
    CleanUpStack(5);
    return result;
}
References CallOneFunction(), CleanUpStack(), Channel::GetChannelDBId(), Channel::GetChannelId(), Channel::IsConstant(), L, LANG_ADDON, lua_isboolean, lua_isstring(), lua_pop, lua_toboolean(), lua_tostring, OnAddonMessage(), Hooks::PLAYER_EVENT_ON_CHANNEL_CHAT, PlayerEventBindings, Push(), SetupStack(), and START_HOOK_WITH_RETVAL.
OnChat() [3/5]
bool Eluna::OnChat (Player * pPlayer, uint32 type, uint32 lang, std::string & msg, Group * pGroup)
{
    if (lang == LANG_ADDON)
        return OnAddonMessage(pPlayer, type, msg, NULL, NULL, pGroup, NULL);
    START_HOOK_WITH_RETVAL(PLAYER_EVENT_ON_GROUP_CHAT, true);
    bool result = true;
    Push(pPlayer);
    Push(msg);
    Push(type);
    Push(lang);
    Push(pGroup);
    int n = SetupStack(PlayerEventBindings, key, 5);
    while (n > 0)
    {
        int r = CallOneFunction(n--, 5, 2);
        if (lua_isboolean(L, r + 0) && !lua_toboolean(L, r + 0))
            result = false;
        if (lua_isstring(L, r + 1))
            msg = std::string(lua_tostring(L, r + 1));
        lua_pop(L, 2);
    }
    CleanUpStack(5);
    return result;
}
References CallOneFunction(), CleanUpStack(), L, LANG_ADDON, lua_isboolean, lua_isstring(), lua_pop, lua_toboolean(), lua_tostring, OnAddonMessage(), Hooks::PLAYER_EVENT_ON_GROUP_CHAT, PlayerEventBindings, Push(), SetupStack(), and START_HOOK_WITH_RETVAL.
OnChat() [4/5]
bool Eluna::OnChat (Player * pPlayer, uint32 type, uint32 lang, std::string & msg, Guild * pGuild)
{
    if (lang == LANG_ADDON)
        return OnAddonMessage(pPlayer, type, msg, NULL, pGuild, NULL, NULL);
    START_HOOK_WITH_RETVAL(PLAYER_EVENT_ON_GUILD_CHAT, true);
    bool result = true;
    Push(pPlayer);
    Push(msg);
    Push(type);
    Push(lang);
    Push(pGuild);
    int n = SetupStack(PlayerEventBindings, key, 5);
    while (n > 0)
    {
        int r = CallOneFunction(n--, 5, 2);
        if (lua_isboolean(L, r + 0) && !lua_toboolean(L, r + 0))
            result = false;
        if (lua_isstring(L, r + 1))
            msg = std::string(lua_tostring(L, r + 1));
        lua_pop(L, 2);
    }
    CleanUpStack(5);
    return result;
}
References CallOneFunction(), CleanUpStack(), L, LANG_ADDON, lua_isboolean, lua_isstring(), lua_pop, lua_toboolean(), lua_tostring, OnAddonMessage(), Hooks::PLAYER_EVENT_ON_GUILD_CHAT, PlayerEventBindings, Push(), SetupStack(), and START_HOOK_WITH_RETVAL.
OnChat() [5/5]
bool Eluna::OnChat (Player * pPlayer, uint32 type, uint32 lang, std::string & msg, Player * pReceiver)
{
    if (lang == LANG_ADDON)
        return OnAddonMessage(pPlayer, type, msg, pReceiver, NULL, NULL, NULL);
    START_HOOK_WITH_RETVAL(PLAYER_EVENT_ON_WHISPER, true);
    bool result = true;
    Push(pPlayer);
    Push(msg);
    Push(type);
    Push(lang);
    Push(pReceiver);
    int n = SetupStack(PlayerEventBindings, key, 5);
    while (n > 0)
    {
        int r = CallOneFunction(n--, 5, 2);
        if (lua_isboolean(L, r + 0) && !lua_toboolean(L, r + 0))
            result = false;
        if (lua_isstring(L, r + 1))
            msg = std::string(lua_tostring(L, r + 1));
        lua_pop(L, 2);
    }
    CleanUpStack(5);
    return result;
}
References CallOneFunction(), CleanUpStack(), L, LANG_ADDON, lua_isboolean, lua_isstring(), lua_pop, lua_toboolean(), lua_tostring, OnAddonMessage(), Hooks::PLAYER_EVENT_ON_WHISPER, PlayerEventBindings, Push(), SetupStack(), and START_HOOK_WITH_RETVAL.
OnCheckEncounterInProgress()
bool Eluna::OnCheckEncounterInProgress (ElunaInstanceAI * ai)
{
    START_HOOK_WITH_RETVAL(INSTANCE_EVENT_ON_CHECK_ENCOUNTER_IN_PROGRESS, ai, false);
    return CallAllFunctionsBool(MapEventBindings, InstanceEventBindings, mapKey, instanceKey);
}
References CallAllFunctionsBool(), Hooks::INSTANCE_EVENT_ON_CHECK_ENCOUNTER_IN_PROGRESS, InstanceEventBindings, MapEventBindings, and START_HOOK_WITH_RETVAL.
OnCommand()
bool Eluna::OnCommand (ChatHandler & handler, const char * text)
{
    Player* player = handler.IsConsole() ? nullptr : handler.GetSession()->GetPlayer();
    // If from console, player is NULL
    if (!player || player->GetSession()->GetSecurity() >= SEC_ADMINISTRATOR)
    {
        std::string reload = text;
        std::transform(reload.begin(), reload.end(), reload.begin(), ::tolower);
        if (reload.find("reload eluna") == 0)
        {
            ReloadEluna();
            return false;
        }
    }
    START_HOOK_WITH_RETVAL(PLAYER_EVENT_ON_COMMAND, true);
    Push(player);
    Push(text);
    Push(&handler);
    return CallAllFunctionsBool(PlayerEventBindings, key, true);
}
References CallAllFunctionsBool(), WorldSession::GetPlayer(), WorldSession::GetSecurity(), ChatHandler::GetSession(), Player::GetSession(), ChatHandler::IsConsole(), Hooks::PLAYER_EVENT_ON_COMMAND, PlayerEventBindings, Push(), reload, ReloadEluna(), SEC_ADMINISTRATOR, and START_HOOK_WITH_RETVAL.
OnConfigLoad()
void Eluna::OnConfigLoad (bool reload)
{
    START_HOOK(WORLD_EVENT_ON_CONFIG_LOAD);
    Push(reload);
#ifdef AZEROTHCORE
    Push(isBefore);
#endif
    CallAllFunctions(ServerEventBindings, key);
}
References START_HOOK, and Hooks::WORLD_EVENT_ON_CONFIG_LOAD.
OnCreate() [1/4]
void Eluna::OnCreate (Group * group, ObjectGuid leaderGuid, GroupType groupType)
{
    START_HOOK(GROUP_EVENT_ON_CREATE);
    Push(group);
    Push(leaderGuid);
    Push(groupType);
    CallAllFunctions(GroupEventBindings, key);
}
References CallAllFunctions(), Hooks::GROUP_EVENT_ON_CREATE, GroupEventBindings, Push(), and START_HOOK.
OnCreate() [2/4]
void Eluna::OnCreate (Guild * guild, Player * leader, const std::string & name)
{
    START_HOOK(GUILD_EVENT_ON_CREATE);
    Push(guild);
    Push(leader);
    Push(name);
    CallAllFunctions(GuildEventBindings, key);
}
References CallAllFunctions(), Hooks::GUILD_EVENT_ON_CREATE, GuildEventBindings, Push(), and START_HOOK.
OnCreate() [3/4]
void Eluna::OnCreate (Map * map)
{
    START_HOOK(MAP_EVENT_ON_CREATE);
    Push(map);
    CallAllFunctions(ServerEventBindings, key);
}
References CallAllFunctions(), Hooks::MAP_EVENT_ON_CREATE, Push(), ServerEventBindings, and START_HOOK.
OnCreate() [4/4]
void Eluna::OnCreate (Player * pPlayer)
{
    START_HOOK(PLAYER_EVENT_ON_CHARACTER_CREATE);
    Push(pPlayer);
    CallAllFunctions(PlayerEventBindings, key);
}
References CallAllFunctions(), Hooks::PLAYER_EVENT_ON_CHARACTER_CREATE, PlayerEventBindings, Push(), and START_HOOK.
OnCreateItem()
void Eluna::OnCreateItem (Player * player, Item * item, uint32 count)
{
    START_HOOK(PLAYER_EVENT_ON_CREATE_ITEM);
    Push(player);
    Push(item);
    Push(count);
    CallAllFunctions(PlayerEventBindings, key);
}
References CallAllFunctions(), Hooks::PLAYER_EVENT_ON_CREATE_ITEM, PlayerEventBindings, Push(), and START_HOOK.
OnCreatureCreate()
void Eluna::OnCreatureCreate (ElunaInstanceAI * ai, Creature * creature)
{
    START_HOOK(INSTANCE_EVENT_ON_CREATURE_CREATE, ai);
    Push(creature);
    CallAllFunctions(MapEventBindings, InstanceEventBindings, mapKey, instanceKey);
}
References CallAllFunctions(), Hooks::INSTANCE_EVENT_ON_CREATURE_CREATE, InstanceEventBindings, MapEventBindings, Push(), and START_HOOK.
OnCreatureKill()
void Eluna::OnCreatureKill (Player * pKiller, Creature * pKilled)
{
    START_HOOK(PLAYER_EVENT_ON_KILL_CREATURE);
    Push(pKiller);
    Push(pKilled);
    CallAllFunctions(PlayerEventBindings, key);
}
References CallAllFunctions(), Hooks::PLAYER_EVENT_ON_KILL_CREATURE, PlayerEventBindings, Push(), and START_HOOK.
OnCreatureKilledByPet()
void Eluna::OnCreatureKilledByPet (Player * player, Creature * killed)
{
    START_HOOK(PLAYER_EVENT_ON_PET_KILL);
    Push(player);
    Push(killed);
    CallAllFunctions(PlayerEventBindings, key);
}
References CallAllFunctions(), Hooks::PLAYER_EVENT_ON_PET_KILL, PlayerEventBindings, Push(), and START_HOOK.
OnDamaged()
void Eluna::OnDamaged (GameObject * pGameObject, WorldObject * attacker)
{
    START_HOOK(GAMEOBJECT_EVENT_ON_DAMAGED, pGameObject->GetEntry());
    Push(pGameObject);
    Push(attacker);
    CallAllFunctions(GameObjectEventBindings, key);
}
References CallAllFunctions(), Hooks::GAMEOBJECT_EVENT_ON_DAMAGED, GameObjectEventBindings, Object::GetEntry(), Push(), and START_HOOK.
OnDelete()
void Eluna::OnDelete (uint32 guid)
{
    START_HOOK(PLAYER_EVENT_ON_CHARACTER_DELETE);
    Push(guidlow);
    CallAllFunctions(PlayerEventBindings, key);
}
References CallAllFunctions(), Hooks::PLAYER_EVENT_ON_CHARACTER_DELETE, PlayerEventBindings, Push(), and START_HOOK.
OnDestroy()
void Eluna::OnDestroy (Map * map)
{
    START_HOOK(MAP_EVENT_ON_DESTROY);
    Push(map);
    CallAllFunctions(ServerEventBindings, key);
}
References CallAllFunctions(), Hooks::MAP_EVENT_ON_DESTROY, Push(), ServerEventBindings, and START_HOOK.
OnDestroyed()
void Eluna::OnDestroyed (GameObject * pGameObject, WorldObject * attacker)
{
    START_HOOK(GAMEOBJECT_EVENT_ON_DESTROYED, pGameObject->GetEntry());
    Push(pGameObject);
    Push(attacker);
    CallAllFunctions(GameObjectEventBindings, key);
}
References CallAllFunctions(), Hooks::GAMEOBJECT_EVENT_ON_DESTROYED, GameObjectEventBindings, Object::GetEntry(), Push(), and START_HOOK.
OnDisband() [1/2]
void Eluna::OnDisband (Group * group)
{
    START_HOOK(GROUP_EVENT_ON_DISBAND);
    Push(group);
    CallAllFunctions(GroupEventBindings, key);
}
References CallAllFunctions(), Hooks::GROUP_EVENT_ON_DISBAND, GroupEventBindings, Push(), and START_HOOK.
OnDisband() [2/2]
void Eluna::OnDisband (Guild * guild)
{
    START_HOOK(GUILD_EVENT_ON_DISBAND);
    Push(guild);
    CallAllFunctions(GuildEventBindings, key);
}
References CallAllFunctions(), Hooks::GUILD_EVENT_ON_DISBAND, GuildEventBindings, Push(), and START_HOOK.
OnDuelEnd()
void Eluna::OnDuelEnd (Player * pWinner, Player * pLoser, DuelCompleteType type)
{
    START_HOOK(PLAYER_EVENT_ON_DUEL_END);
    Push(pWinner);
    Push(pLoser);
    Push(type);
    CallAllFunctions(PlayerEventBindings, key);
}
References CallAllFunctions(), Hooks::PLAYER_EVENT_ON_DUEL_END, PlayerEventBindings, Push(), and START_HOOK.
OnDuelRequest()
void Eluna::OnDuelRequest (Player * pTarget, Player * pChallenger)
{
    START_HOOK(PLAYER_EVENT_ON_DUEL_REQUEST);
    Push(pTarget);
    Push(pChallenger);
    CallAllFunctions(PlayerEventBindings, key);
}
References CallAllFunctions(), Hooks::PLAYER_EVENT_ON_DUEL_REQUEST, PlayerEventBindings, Push(), and START_HOOK.
OnDuelStart()
void Eluna::OnDuelStart (Player * pStarter, Player * pChallenger)
{
    START_HOOK(PLAYER_EVENT_ON_DUEL_START);
    Push(pStarter);
    Push(pChallenger);
    CallAllFunctions(PlayerEventBindings, key);
}
References CallAllFunctions(), Hooks::PLAYER_EVENT_ON_DUEL_START, PlayerEventBindings, Push(), and START_HOOK.
OnDummyEffect() [1/3]
void Eluna::OnDummyEffect (WorldObject * pCaster, uint32 spellId, SpellEffIndex effIndex, Creature * pTarget)
{
    START_HOOK(CREATURE_EVENT_ON_DUMMY_EFFECT, pTarget);
    Push(pCaster);
    Push(spellId);
    Push(effIndex);
    Push(pTarget);
    CallAllFunctions(CreatureEventBindings, CreatureUniqueBindings, entry_key, unique_key);
}
References CallAllFunctions(), Hooks::CREATURE_EVENT_ON_DUMMY_EFFECT, CreatureEventBindings, CreatureUniqueBindings, Push(), and START_HOOK.
OnDummyEffect() [2/3]
void Eluna::OnDummyEffect (WorldObject * pCaster, uint32 spellId, SpellEffIndex effIndex, GameObject * pTarget)
{
    START_HOOK(GAMEOBJECT_EVENT_ON_DUMMY_EFFECT, pTarget->GetEntry());
    Push(pCaster);
    Push(spellId);
    Push(effIndex);
    Push(pTarget);
    CallAllFunctions(GameObjectEventBindings, key);
}
References CallAllFunctions(), Hooks::GAMEOBJECT_EVENT_ON_DUMMY_EFFECT, GameObjectEventBindings, Object::GetEntry(), Push(), and START_HOOK.
OnDummyEffect() [3/3]
void Eluna::OnDummyEffect (WorldObject * pCaster, uint32 spellId, SpellEffIndex effIndex, Item * pTarget)
{
    START_HOOK(ITEM_EVENT_ON_DUMMY_EFFECT, pTarget->GetEntry());
    Push(pCaster);
    Push(spellId);
    Push(effIndex);
    Push(pTarget);
    CallAllFunctions(ItemEventBindings, key);
}
References CallAllFunctions(), Object::GetEntry(), Hooks::ITEM_EVENT_ON_DUMMY_EFFECT, ItemEventBindings, Push(), and START_HOOK.
OnEmote()
void Eluna::OnEmote (Player * pPlayer, uint32 emote)
{
    START_HOOK(PLAYER_EVENT_ON_EMOTE);
    Push(pPlayer);
    Push(emote);
    CallAllFunctions(PlayerEventBindings, key);
}
References CallAllFunctions(), Hooks::PLAYER_EVENT_ON_EMOTE, PlayerEventBindings, Push(), and START_HOOK.
OnEquip()
void Eluna::OnEquip (Player * pPlayer, Item * pItem, uint8 bag, uint8 slot)
{
    START_HOOK(PLAYER_EVENT_ON_EQUIP);
    Push(pPlayer);
    Push(pItem);
    Push(bag);
    Push(slot);
    CallAllFunctions(PlayerEventBindings, key);
}
References CallAllFunctions(), Hooks::PLAYER_EVENT_ON_EQUIP, PlayerEventBindings, Push(), and START_HOOK.
OnEvent()
void Eluna::OnEvent (Guild * guild, uint8 eventType, uint32 playerGuid1, uint32 playerGuid2, uint8 newRank)
{
    START_HOOK(GUILD_EVENT_ON_EVENT);
    Push(guild);
    Push(eventType);
    Push(playerGuid1);
    Push(playerGuid2);
    Push(newRank);
    CallAllFunctions(GuildEventBindings, key);
}
References CallAllFunctions(), Hooks::GUILD_EVENT_ON_EVENT, GuildEventBindings, Push(), and START_HOOK.
OnExpire() [1/2]
void Eluna::OnExpire (AuctionHouseObject * ah, AuctionEntry * entry)
{
#ifdef AZEROTHCORE
    Player* owner = eObjectAccessor()FindPlayer(entry->owner);
#else
    Player* owner = eObjectAccessor()FindPlayer(MAKE_NEW_GUID(entry->owner, 0, HIGHGUID_PLAYER));
#endif
#ifdef TRINITY
    Item* item = eAuctionMgr->GetAItem(entry->itemGUIDLow);
    uint32 expiretime = entry->expire_time;
#elif AZEROTHCORE
    Item* item = eAuctionMgr->GetAItem(entry->item_guid);
    uint32 expiretime = entry->expire_time;
#else
    Item* item = eAuctionMgr->GetAItem(entry->itemGuidLow);
    uint32 expiretime = entry->expireTime;
#endif
    if (!owner || !item)
        return;
    START_HOOK(AUCTION_EVENT_ON_EXPIRE);
    Push(entry->Id);
    Push(owner);
    Push(item);
    Push(expiretime);
    Push(entry->buyout);
    Push(entry->startbid);
    Push(entry->bid);
    Push(entry->bidder);
    CallAllFunctions(ServerEventBindings, key);
}
References Hooks::AUCTION_EVENT_ON_EXPIRE, AuctionEntry::bid, AuctionEntry::bidder, AuctionEntry::buyout, CallAllFunctions(), eAuctionMgr, eObjectAccessor, AuctionEntry::expire_time, AuctionEntry::Id, AuctionEntry::item_guid, AuctionEntry::owner, Push(), ServerEventBindings, START_HOOK, and AuctionEntry::startbid.
OnExpire() [2/2]
bool Eluna::OnExpire (Player * pPlayer, ItemTemplate const * pProto)
{
    START_HOOK_WITH_RETVAL(ITEM_EVENT_ON_EXPIRE, pProto->ItemId, false);
    Push(pPlayer);
    Push(pProto->ItemId);
    return CallAllFunctionsBool(ItemEventBindings, key);
}
References CallAllFunctionsBool(), Hooks::ITEM_EVENT_ON_EXPIRE, ItemEventBindings, ItemTemplate::ItemId, Push(), and START_HOOK_WITH_RETVAL.
OnFfaPvpStateUpdate()
void Eluna::OnFfaPvpStateUpdate (Player * player, bool hasFfaPvp)
{
    START_HOOK(PLAYER_EVENT_ON_FFAPVP_CHANGE);
    Push(player);
    Push(hasFfaPvp);
    CallAllFunctions(PlayerEventBindings, key);
}
References CallAllFunctions(), Hooks::PLAYER_EVENT_ON_FFAPVP_CHANGE, PlayerEventBindings, Push(), and START_HOOK.
OnFirstLogin()
void Eluna::OnFirstLogin (Player * pPlayer)
{
    START_HOOK(PLAYER_EVENT_ON_FIRST_LOGIN);
    Push(pPlayer);
    CallAllFunctions(PlayerEventBindings, key);
}
References CallAllFunctions(), Hooks::PLAYER_EVENT_ON_FIRST_LOGIN, PlayerEventBindings, Push(), and START_HOOK.
OnFreeTalentPointsChanged()
void Eluna::OnFreeTalentPointsChanged (Player * pPlayer, uint32 newPoints)
{
    START_HOOK(PLAYER_EVENT_ON_TALENTS_CHANGE);
    Push(pPlayer);
    Push(newPoints);
    CallAllFunctions(PlayerEventBindings, key);
}
References CallAllFunctions(), Hooks::PLAYER_EVENT_ON_TALENTS_CHANGE, PlayerEventBindings, Push(), and START_HOOK.
OnGameEventStart()
void Eluna::OnGameEventStart (uint32 eventid)
{
    START_HOOK(GAME_EVENT_START);
    Push(eventid);
    CallAllFunctions(ServerEventBindings, key);
}
References CallAllFunctions(), Hooks::GAME_EVENT_START, Push(), ServerEventBindings, and START_HOOK.
OnGameEventStop()
void Eluna::OnGameEventStop (uint32 eventid)
{
    START_HOOK(GAME_EVENT_STOP);
    Push(eventid);
    CallAllFunctions(ServerEventBindings, key);
}
References CallAllFunctions(), Hooks::GAME_EVENT_STOP, Push(), ServerEventBindings, and START_HOOK.
OnGameObjectCreate()
void Eluna::OnGameObjectCreate (ElunaInstanceAI * ai, GameObject * gameobject)
{
    START_HOOK(INSTANCE_EVENT_ON_GAMEOBJECT_CREATE, ai);
    Push(gameobject);
    CallAllFunctions(MapEventBindings, InstanceEventBindings, mapKey, instanceKey);
}
References CallAllFunctions(), Hooks::INSTANCE_EVENT_ON_GAMEOBJECT_CREATE, InstanceEventBindings, MapEventBindings, Push(), and START_HOOK.
OnGameObjectStateChanged()
void Eluna::OnGameObjectStateChanged (GameObject * pGameObject, uint32 state)
{
    START_HOOK(GAMEOBJECT_EVENT_ON_GO_STATE_CHANGED, pGameObject->GetEntry());
    Push(pGameObject);
    Push(state);
    CallAllFunctions(GameObjectEventBindings, key);
}
References CallAllFunctions(), Hooks::GAMEOBJECT_EVENT_ON_GO_STATE_CHANGED, GameObjectEventBindings, Object::GetEntry(), Push(), and START_HOOK.
OnGameObjectUse()
bool Eluna::OnGameObjectUse (Player * pPlayer, GameObject * pGameObject)
{
    START_HOOK_WITH_RETVAL(GAMEOBJECT_EVENT_ON_USE, pGameObject->GetEntry(), false);
    Push(pGameObject);
    Push(pPlayer);
    return CallAllFunctionsBool(GameObjectEventBindings, key);
}
References CallAllFunctionsBool(), Hooks::GAMEOBJECT_EVENT_ON_USE, GameObjectEventBindings, Object::GetEntry(), Push(), and START_HOOK_WITH_RETVAL.
OnGiveXP()
void Eluna::OnGiveXP (Player * pPlayer, uint32 & amount, Unit * pVictim, uint8 xpSource)
{
    START_HOOK(PLAYER_EVENT_ON_GIVE_XP);
    Push(pPlayer);
    Push(amount);
    Push(pVictim);
    Push(xpSource);
    int amountIndex = lua_gettop(L) - 1;
    int n = SetupStack(PlayerEventBindings, key, 4);
    while (n > 0)
    {
        int r = CallOneFunction(n--, 4, 1);
        if (lua_isnumber(L, r))
        {
            amount = CHECKVAL<uint32>(L, r);
            // Update the stack for subsequent calls.
            ReplaceArgument(amount, amountIndex);
        }
        lua_pop(L, 1);
    }
    CleanUpStack(4);
}
References CallOneFunction(), CleanUpStack(), L, lua_gettop(), lua_isnumber(), lua_pop, Hooks::PLAYER_EVENT_ON_GIVE_XP, PlayerEventBindings, Push(), ReplaceArgument(), SetupStack(), and START_HOOK.
OnGossipHello() [1/2]
bool Eluna::OnGossipHello (Player * pPlayer, Creature * pCreature)
{
    START_HOOK_WITH_RETVAL(CreatureGossipBindings, GOSSIP_EVENT_ON_HELLO, pCreature->GetEntry(), false);
    pPlayer->PlayerTalkClass->ClearMenus();
    Push(pPlayer);
    Push(pCreature);
    return CallAllFunctionsBool(CreatureGossipBindings, key, true);
}
References CallAllFunctionsBool(), PlayerMenu::ClearMenus(), CreatureGossipBindings, Object::GetEntry(), Hooks::GOSSIP_EVENT_ON_HELLO, Player::PlayerTalkClass, Push(), and START_HOOK_WITH_RETVAL.
OnGossipHello() [2/2]
bool Eluna::OnGossipHello (Player * pPlayer, GameObject * pGameObject)
{
    START_HOOK_WITH_RETVAL(GameObjectGossipBindings, GOSSIP_EVENT_ON_HELLO, pGameObject->GetEntry(), false);
    pPlayer->PlayerTalkClass->ClearMenus();
    Push(pPlayer);
    Push(pGameObject);
    return CallAllFunctionsBool(GameObjectGossipBindings, key, true);
}
References CallAllFunctionsBool(), PlayerMenu::ClearMenus(), GameObjectGossipBindings, Object::GetEntry(), Hooks::GOSSIP_EVENT_ON_HELLO, Player::PlayerTalkClass, Push(), and START_HOOK_WITH_RETVAL.
OnGossipSelect() [1/2]
bool Eluna::OnGossipSelect (Player * pPlayer, Creature * pCreature, uint32 sender, uint32 action)
{
    START_HOOK_WITH_RETVAL(CreatureGossipBindings, GOSSIP_EVENT_ON_SELECT, pCreature->GetEntry(), false);
    auto originalMenu = *pPlayer->PlayerTalkClass;
    pPlayer->PlayerTalkClass->ClearMenus();
    Push(pPlayer);
    Push(pCreature);
    Push(sender);
    Push(action);
    auto preventDefault = CallAllFunctionsBool(CreatureGossipBindings, key, true);
    if (!preventDefault) {
        *pPlayer->PlayerTalkClass = originalMenu;
    }
    return preventDefault;
}
References CallAllFunctionsBool(), PlayerMenu::ClearMenus(), CreatureGossipBindings, Object::GetEntry(), Hooks::GOSSIP_EVENT_ON_SELECT, Player::PlayerTalkClass, Push(), and START_HOOK_WITH_RETVAL.
OnGossipSelect() [2/2]
bool Eluna::OnGossipSelect (Player * pPlayer, GameObject * pGameObject, uint32 sender, uint32 action)
{
    START_HOOK_WITH_RETVAL(GameObjectGossipBindings, GOSSIP_EVENT_ON_SELECT, pGameObject->GetEntry(), false);
    pPlayer->PlayerTalkClass->ClearMenus();
    Push(pPlayer);
    Push(pGameObject);
    Push(sender);
    Push(action);
    return CallAllFunctionsBool(GameObjectGossipBindings, key, true);
}
References CallAllFunctionsBool(), PlayerMenu::ClearMenus(), GameObjectGossipBindings, Object::GetEntry(), Hooks::GOSSIP_EVENT_ON_SELECT, Player::PlayerTalkClass, Push(), and START_HOOK_WITH_RETVAL.
OnGossipSelectCode() [1/2]
bool Eluna::OnGossipSelectCode (Player * pPlayer, Creature * pCreature, uint32 sender, uint32 action, const char * code)
{
    START_HOOK_WITH_RETVAL(CreatureGossipBindings, GOSSIP_EVENT_ON_SELECT, pCreature->GetEntry(), false);
    auto originalMenu = *pPlayer->PlayerTalkClass;
    pPlayer->PlayerTalkClass->ClearMenus();
    Push(pPlayer);
    Push(pCreature);
    Push(sender);
    Push(action);
    Push(code);
    auto preventDefault = CallAllFunctionsBool(CreatureGossipBindings, key, true);
    if (!preventDefault) {
        *pPlayer->PlayerTalkClass = originalMenu;
    }
    return preventDefault;
}
References CallAllFunctionsBool(), PlayerMenu::ClearMenus(), CreatureGossipBindings, Object::GetEntry(), Hooks::GOSSIP_EVENT_ON_SELECT, Player::PlayerTalkClass, Push(), and START_HOOK_WITH_RETVAL.
OnGossipSelectCode() [2/2]
bool Eluna::OnGossipSelectCode (Player * pPlayer, GameObject * pGameObject, uint32 sender, uint32 action, const char * code)
{
    START_HOOK_WITH_RETVAL(GameObjectGossipBindings, GOSSIP_EVENT_ON_SELECT, pGameObject->GetEntry(), false);
    pPlayer->PlayerTalkClass->ClearMenus();
    Push(pPlayer);
    Push(pGameObject);
    Push(sender);
    Push(action);
    Push(code);
    return CallAllFunctionsBool(GameObjectGossipBindings, key, true);
}
References CallAllFunctionsBool(), PlayerMenu::ClearMenus(), GameObjectGossipBindings, Object::GetEntry(), Hooks::GOSSIP_EVENT_ON_SELECT, Player::PlayerTalkClass, Push(), and START_HOOK_WITH_RETVAL.
OnGroupRollRewardItem()
void Eluna::OnGroupRollRewardItem (Player * player, Item * item, uint32 count, RollVote voteType, Roll * roll)
{
    START_HOOK(PLAYER_EVENT_ON_GROUP_ROLL_REWARD_ITEM);
    Push(player);
    Push(item);
    Push(count);
    Push(voteType);
    Push(roll);
    CallAllFunctions(PlayerEventBindings, key);
}
References CallAllFunctions(), Hooks::PLAYER_EVENT_ON_GROUP_ROLL_REWARD_ITEM, PlayerEventBindings, Push(), and START_HOOK.
OnInfoChanged()
void Eluna::OnInfoChanged (Guild * guild, const std::string & newInfo)
{
    START_HOOK(GUILD_EVENT_ON_INFO_CHANGE);
    Push(guild);
    Push(newInfo);
    CallAllFunctions(GuildEventBindings, key);
}
References CallAllFunctions(), Hooks::GUILD_EVENT_ON_INFO_CHANGE, GuildEventBindings, Push(), and START_HOOK.
OnInitialize()
void Eluna::OnInitialize (ElunaInstanceAI * ai)
{
    START_HOOK(INSTANCE_EVENT_ON_INITIALIZE, ai);
    CallAllFunctions(MapEventBindings, InstanceEventBindings, mapKey, instanceKey);
}
References CallAllFunctions(), Hooks::INSTANCE_EVENT_ON_INITIALIZE, InstanceEventBindings, MapEventBindings, and START_HOOK.
OnInstall()
void Eluna::OnInstall (Vehicle * vehicle)
{
    START_HOOK(VEHICLE_EVENT_ON_INSTALL);
    Push(vehicle);
    CallAllFunctions(VehicleEventBindings, key);
}
References CallAllFunctions(), Push(), START_HOOK, Hooks::VEHICLE_EVENT_ON_INSTALL, and VehicleEventBindings.
OnInstallAccessory()
void Eluna::OnInstallAccessory (Vehicle * vehicle, Creature * accessory)
{
    START_HOOK(VEHICLE_EVENT_ON_INSTALL_ACCESSORY);
    Push(vehicle);
    Push(accessory);
    CallAllFunctions(VehicleEventBindings, key);
}
References CallAllFunctions(), Push(), START_HOOK, Hooks::VEHICLE_EVENT_ON_INSTALL_ACCESSORY, and VehicleEventBindings.
OnInviteMember()
void Eluna::OnInviteMember (Group * group, ObjectGuid guid)
{
    START_HOOK(GROUP_EVENT_ON_MEMBER_INVITE);
    Push(group);
    Push(guid);
    CallAllFunctions(GroupEventBindings, key);
}
References CallAllFunctions(), Hooks::GROUP_EVENT_ON_MEMBER_INVITE, GroupEventBindings, Push(), and START_HOOK.
OnItemGossip()
bool Eluna::OnItemGossip (Player * pPlayer, Item * pItem, SpellCastTargets const & targets)
{
    START_HOOK_WITH_RETVAL(ItemGossipBindings, GOSSIP_EVENT_ON_HELLO, pItem->GetEntry(), true);
    pPlayer->PlayerTalkClass->ClearMenus();
    Push(pPlayer);
    Push(pItem);
    return CallAllFunctionsBool(ItemGossipBindings, key, true);
}
References CallAllFunctionsBool(), PlayerMenu::ClearMenus(), Object::GetEntry(), Hooks::GOSSIP_EVENT_ON_HELLO, ItemGossipBindings, Player::PlayerTalkClass, Push(), and START_HOOK_WITH_RETVAL.
Referenced by OnUse().
OnItemMove()
void Eluna::OnItemMove (Guild * guild, Player * player, Item * pItem, bool isSrcBank, uint8 srcContainer, uint8 srcSlotId, bool isDestBank, uint8 destContainer, uint8 destSlotId)
{
    START_HOOK(GUILD_EVENT_ON_ITEM_MOVE);
    Push(guild);
    Push(player);
    Push(pItem);
    Push(isSrcBank);
    Push(srcContainer);
    Push(srcSlotId);
    Push(isDestBank);
    Push(destContainer);
    Push(destSlotId);
    CallAllFunctions(GuildEventBindings, key);
}
References CallAllFunctions(), Hooks::GUILD_EVENT_ON_ITEM_MOVE, GuildEventBindings, Push(), and START_HOOK.
OnItemUse()
bool Eluna::OnItemUse (Player * pPlayer, Item * pItem, SpellCastTargets const & targets)
{
    START_HOOK_WITH_RETVAL(ITEM_EVENT_ON_USE, pItem->GetEntry(), true);
    Push(pPlayer);
    Push(pItem);
#if defined TRINITY || AZEROTHCORE
    if (GameObject* target = targets.GetGOTarget())
        Push(target);
    else if (Item* target = targets.GetItemTarget())
        Push(target);
    else if (Corpse* target = targets.GetCorpseTarget())
        Push(target);
    else if (Unit* target = targets.GetUnitTarget())
        Push(target);
    else if (WorldObject* target = targets.GetObjectTarget())
        Push(target);
    else
        Push();
#else
    if (GameObject* target = targets.getGOTarget())
        Push(target);
    else if (Item* target = targets.getItemTarget())
        Push(target);
    else if (Corpse* target = pPlayer->GetMap()->GetCorpse(targets.getCorpseTargetGuid()))
        Push(target);
    else if (Unit* target = targets.getUnitTarget())
        Push(target);
    else
        Push();
#endif
    return CallAllFunctionsBool(ItemEventBindings, key, true);
}
References CallAllFunctionsBool(), Map::GetCorpse(), SpellCastTargets::GetCorpseTarget(), Object::GetEntry(), SpellCastTargets::GetGOTarget(), SpellCastTargets::GetItemTarget(), WorldObject::GetMap(), SpellCastTargets::GetObjectTarget(), SpellCastTargets::GetUnitTarget(), Hooks::ITEM_EVENT_ON_USE, ItemEventBindings, Push(), and START_HOOK_WITH_RETVAL.
Referenced by OnUse().
OnLearnSpell()
void Eluna::OnLearnSpell (Player * player, uint32 spellId)
{
    START_HOOK(PLAYER_EVENT_ON_LEARN_SPELL);
    Push(player);
    Push(spellId);
    CallAllFunctions(PlayerEventBindings, key);
}
References CallAllFunctions(), Hooks::PLAYER_EVENT_ON_LEARN_SPELL, PlayerEventBindings, Push(), and START_HOOK.
OnLearnTalents()
void Eluna::OnLearnTalents (Player * pPlayer, uint32 talentId, uint32 talentRank, uint32 spellid)
{
    START_HOOK(PLAYER_EVENT_ON_LEARN_TALENTS);
    Push(pPlayer);
    Push(talentId);
    Push(talentRank);
    Push(spellid);
    CallAllFunctions(PlayerEventBindings, key);
}
References CallAllFunctions(), Hooks::PLAYER_EVENT_ON_LEARN_TALENTS, PlayerEventBindings, Push(), and START_HOOK.
OnLevelChanged()
void Eluna::OnLevelChanged (Player * pPlayer, uint8 oldLevel)
{
    START_HOOK(PLAYER_EVENT_ON_LEVEL_CHANGE);
    Push(pPlayer);
    Push(oldLevel);
    CallAllFunctions(PlayerEventBindings, key);
}
References CallAllFunctions(), Hooks::PLAYER_EVENT_ON_LEVEL_CHANGE, PlayerEventBindings, Push(), and START_HOOK.
OnLoad()
void Eluna::OnLoad (ElunaInstanceAI * ai)
{
    START_HOOK(INSTANCE_EVENT_ON_LOAD, ai);
    CallAllFunctions(MapEventBindings, InstanceEventBindings, mapKey, instanceKey);
}
References CallAllFunctions(), Hooks::INSTANCE_EVENT_ON_LOAD, InstanceEventBindings, MapEventBindings, and START_HOOK.
OnLogin()
void Eluna::OnLogin (Player * pPlayer)
{
    START_HOOK(PLAYER_EVENT_ON_LOGIN);
    Push(pPlayer);
    CallAllFunctions(PlayerEventBindings, key);
}
References CallAllFunctions(), Hooks::PLAYER_EVENT_ON_LOGIN, PlayerEventBindings, Push(), and START_HOOK.
OnLogout()
void Eluna::OnLogout (Player * pPlayer)
{
    START_HOOK(PLAYER_EVENT_ON_LOGOUT);
    Push(pPlayer);
    CallAllFunctions(PlayerEventBindings, key);
}
References CallAllFunctions(), Hooks::PLAYER_EVENT_ON_LOGOUT, PlayerEventBindings, Push(), and START_HOOK.
OnLootItem()
void Eluna::OnLootItem (Player * pPlayer, Item * pItem, uint32 count, ObjectGuid guid)
{
    START_HOOK(PLAYER_EVENT_ON_LOOT_ITEM);
    Push(pPlayer);
    Push(pItem);
    Push(count);
    Push(guid);
    CallAllFunctions(PlayerEventBindings, key);
}
References CallAllFunctions(), Hooks::PLAYER_EVENT_ON_LOOT_ITEM, PlayerEventBindings, Push(), and START_HOOK.
OnLootMoney()
void Eluna::OnLootMoney (Player * pPlayer, uint32 amount)
{
    START_HOOK(PLAYER_EVENT_ON_LOOT_MONEY);
    Push(pPlayer);
    Push(amount);
    CallAllFunctions(PlayerEventBindings, key);
}
References CallAllFunctions(), Hooks::PLAYER_EVENT_ON_LOOT_MONEY, PlayerEventBindings, Push(), and START_HOOK.
OnLootStateChanged()
void Eluna::OnLootStateChanged (GameObject * pGameObject, uint32 state)
{
    START_HOOK(GAMEOBJECT_EVENT_ON_LOOT_STATE_CHANGE, pGameObject->GetEntry());
    Push(pGameObject);
    Push(state);
    CallAllFunctions(GameObjectEventBindings, key);
}
References CallAllFunctions(), Hooks::GAMEOBJECT_EVENT_ON_LOOT_STATE_CHANGE, GameObjectEventBindings, Object::GetEntry(), Push(), and START_HOOK.
OnLuaStateClose()
void Eluna::OnLuaStateClose ()
{
    START_HOOK(ELUNA_EVENT_ON_LUA_STATE_CLOSE);
    CallAllFunctions(ServerEventBindings, key);
}
References CallAllFunctions(), Hooks::ELUNA_EVENT_ON_LUA_STATE_CLOSE, ServerEventBindings, and START_HOOK.
Referenced by CloseLua().
OnLuaStateOpen()
void Eluna::OnLuaStateOpen ()
{
    START_HOOK(ELUNA_EVENT_ON_LUA_STATE_OPEN);
    CallAllFunctions(ServerEventBindings, key);
}
References CallAllFunctions(), Hooks::ELUNA_EVENT_ON_LUA_STATE_OPEN, ServerEventBindings, and START_HOOK.
Referenced by RunScripts().
OnMapChanged()
void Eluna::OnMapChanged (Player * pPlayer)
{
    START_HOOK(PLAYER_EVENT_ON_MAP_CHANGE);
    Push(player);
    CallAllFunctions(PlayerEventBindings, key);
}
References CallAllFunctions(), Hooks::PLAYER_EVENT_ON_MAP_CHANGE, PlayerEventBindings, Push(), and START_HOOK.
OnMemberDepositMoney()
void Eluna::OnMemberDepositMoney (Guild * guild, Player * player, uint32 & amount)
{
    START_HOOK(GUILD_EVENT_ON_MONEY_DEPOSIT);
    Push(guild);
    Push(player);
    Push(amount);
    int amountIndex = lua_gettop(L);
    int n = SetupStack(GuildEventBindings, key, 3);
    while (n > 0)
    {
        int r = CallOneFunction(n--, 3, 1);
        if (lua_isnumber(L, r))
        {
            amount = CHECKVAL<uint32>(L, r);
            // Update the stack for subsequent calls.
            ReplaceArgument(amount, amountIndex);
        }
        lua_pop(L, 1);
    }
    CleanUpStack(3);
}
References CallOneFunction(), CleanUpStack(), Hooks::GUILD_EVENT_ON_MONEY_DEPOSIT, GuildEventBindings, L, lua_gettop(), lua_isnumber(), lua_pop, Push(), ReplaceArgument(), SetupStack(), and START_HOOK.
OnMemberWitdrawMoney()
void Eluna::OnMemberWitdrawMoney (Guild * guild, Player * player, uint32 & amount, bool isRepair)
{
    START_HOOK(GUILD_EVENT_ON_MONEY_WITHDRAW);
    Push(guild);
    Push(player);
    Push(amount);
    Push(isRepair); // isRepair not a part of Mangos, implement?
    int amountIndex = lua_gettop(L) - 1;
    int n = SetupStack(GuildEventBindings, key, 4);
    while (n > 0)
    {
        int r = CallOneFunction(n--, 4, 1);
        if (lua_isnumber(L, r))
        {
            amount = CHECKVAL<uint32>(L, r);
            // Update the stack for subsequent calls.
            ReplaceArgument(amount, amountIndex);
        }
        lua_pop(L, 1);
    }
    CleanUpStack(4);
}
References CallOneFunction(), CleanUpStack(), Hooks::GUILD_EVENT_ON_MONEY_WITHDRAW, GuildEventBindings, L, lua_gettop(), lua_isnumber(), lua_pop, Push(), ReplaceArgument(), SetupStack(), and START_HOOK.
OnMoneyChanged()
void Eluna::OnMoneyChanged (Player * pPlayer, int32 & amount)
{
    START_HOOK(PLAYER_EVENT_ON_MONEY_CHANGE);
    Push(pPlayer);
    Push(amount);
    int amountIndex = lua_gettop(L);
    int n = SetupStack(PlayerEventBindings, key, 2);
    while (n > 0)
    {
        int r = CallOneFunction(n--, 2, 1);
        if (lua_isnumber(L, r))
        {
            amount = CHECKVAL<int32>(L, r);
            // Update the stack for subsequent calls.
            ReplaceArgument(amount, amountIndex);
        }
        lua_pop(L, 1);
    }
    CleanUpStack(2);
}
References CallOneFunction(), CleanUpStack(), L, lua_gettop(), lua_isnumber(), lua_pop, Hooks::PLAYER_EVENT_ON_MONEY_CHANGE, PlayerEventBindings, Push(), ReplaceArgument(), SetupStack(), and START_HOOK.
OnMOTDChanged()
void Eluna::OnMOTDChanged (Guild * guild, const std::string & newMotd)
{
    START_HOOK(GUILD_EVENT_ON_MOTD_CHANGE);
    Push(guild);
    Push(newMotd);
    CallAllFunctions(GuildEventBindings, key);
}
References CallAllFunctions(), Hooks::GUILD_EVENT_ON_MOTD_CHANGE, GuildEventBindings, Push(), and START_HOOK.
OnOpenStateChange()
void Eluna::OnOpenStateChange (bool open)
{
    START_HOOK(WORLD_EVENT_ON_OPEN_STATE_CHANGE);
    Push(open);
    CallAllFunctions(ServerEventBindings, key);
}
References CallAllFunctions(), Push(), ServerEventBindings, START_HOOK, and Hooks::WORLD_EVENT_ON_OPEN_STATE_CHANGE.
OnPacketReceive()
bool Eluna::OnPacketReceive (WorldSession * session, WorldPacket & packet)
{
    bool result = true;
    Player* player = NULL;
    if (session)
        player = session->GetPlayer();
    OnPacketReceiveAny(player, packet, result);
    OnPacketReceiveOne(player, packet, result);
    return result;
}
References WorldSession::GetPlayer(), OnPacketReceiveAny(), and OnPacketReceiveOne().
OnPacketReceiveAny()
void Eluna::OnPacketReceiveAny (Player * player, WorldPacket & packet, bool & result)
{
    START_HOOK_SERVER(SERVER_EVENT_ON_PACKET_RECEIVE);
    Push(new WorldPacket(packet));
    Push(player);
    int n = SetupStack(ServerEventBindings, key, 2);
    while (n > 0)
    {
        int r = CallOneFunction(n--, 2, 2);
        if (lua_isboolean(L, r + 0) && !lua_toboolean(L, r + 0))
            result = false;
        if (lua_isuserdata(L, r + 1))
            if (WorldPacket* data = CHECKOBJ<WorldPacket>(L, r + 1, false))
                packet = *data;
        lua_pop(L, 2);
    }
    CleanUpStack(2);
}
References CallOneFunction(), CleanUpStack(), L, lua_isboolean, lua_isuserdata(), lua_pop, lua_toboolean(), Push(), Hooks::SERVER_EVENT_ON_PACKET_RECEIVE, ServerEventBindings, SetupStack(), and START_HOOK_SERVER.
Referenced by OnPacketReceive().
OnPacketReceiveOne()
void Eluna::OnPacketReceiveOne (Player * player, WorldPacket & packet, bool & result)
{
    START_HOOK_PACKET(PACKET_EVENT_ON_PACKET_RECEIVE, packet.GetOpcode());
    Push(new WorldPacket(packet));
    Push(player);
    int n = SetupStack(PacketEventBindings, key, 2);
    while (n > 0)
    {
        int r = CallOneFunction(n--, 2, 2);
        if (lua_isboolean(L, r + 0) && !lua_toboolean(L, r + 0))
            result = false;
        if (lua_isuserdata(L, r + 1))
            if (WorldPacket* data = CHECKOBJ<WorldPacket>(L, r + 1, false))
                packet = *data;
        lua_pop(L, 2);
    }
    CleanUpStack(2);
}
References CallOneFunction(), CleanUpStack(), WorldPacket::GetOpcode(), L, lua_isboolean, lua_isuserdata(), lua_pop, lua_toboolean(), Hooks::PACKET_EVENT_ON_PACKET_RECEIVE, PacketEventBindings, Push(), SetupStack(), and START_HOOK_PACKET.
Referenced by OnPacketReceive().
OnPacketSend()
bool Eluna::OnPacketSend (WorldSession * session, const WorldPacket & packet)
{
    bool result = true;
    Player* player = NULL;
    if (session)
        player = session->GetPlayer();
    OnPacketSendAny(player, packet, result);
    OnPacketSendOne(player, packet, result);
    return result;
}
References WorldSession::GetPlayer(), OnPacketSendAny(), and OnPacketSendOne().
OnPacketSendAny()
void Eluna::OnPacketSendAny (Player * player, const WorldPacket & packet, bool & result)
{
    START_HOOK_SERVER(SERVER_EVENT_ON_PACKET_SEND);
    Push(new WorldPacket(packet));
    Push(player);
    int n = SetupStack(ServerEventBindings, key, 2);
    while (n > 0)
    {
        int r = CallOneFunction(n--, 2, 1);
        if (lua_isboolean(L, r + 0) && !lua_toboolean(L, r + 0))
            result = false;
        lua_pop(L, 1);
    }
    CleanUpStack(2);
}
References CallOneFunction(), CleanUpStack(), L, lua_isboolean, lua_pop, lua_toboolean(), Push(), Hooks::SERVER_EVENT_ON_PACKET_SEND, ServerEventBindings, SetupStack(), and START_HOOK_SERVER.
Referenced by OnPacketSend().
OnPacketSendOne()
void Eluna::OnPacketSendOne (Player * player, const WorldPacket & packet, bool & result)
{
    START_HOOK_PACKET(PACKET_EVENT_ON_PACKET_SEND, packet.GetOpcode());
    Push(new WorldPacket(packet));
    Push(player);
    int n = SetupStack(PacketEventBindings, key, 2);
    while (n > 0)
    {
        int r = CallOneFunction(n--, 2, 1);
        if (lua_isboolean(L, r + 0) && !lua_toboolean(L, r + 0))
            result = false;
        lua_pop(L, 1);
    }
    CleanUpStack(2);
}
References CallOneFunction(), CleanUpStack(), WorldPacket::GetOpcode(), L, lua_isboolean, lua_pop, lua_toboolean(), Hooks::PACKET_EVENT_ON_PACKET_SEND, PacketEventBindings, Push(), SetupStack(), and START_HOOK_PACKET.
Referenced by OnPacketSend().
OnPetAddedToWorld()
void Eluna::OnPetAddedToWorld (Player * player, Creature * pet)
{
    START_HOOK(PLAYER_EVENT_ON_PET_ADDED_TO_WORLD);
    Push(player);
    Push(pet);
    CallAllFunctions(PlayerEventBindings, key);
}
References CallAllFunctions(), Hooks::PLAYER_EVENT_ON_PET_ADDED_TO_WORLD, PlayerEventBindings, Push(), and START_HOOK.
OnPlayerCompleteQuest()
void Eluna::OnPlayerCompleteQuest (Player * player, Quest const * quest)
{
    START_HOOK(PLAYER_EVENT_ON_COMPLETE_QUEST);
    Push(player);
    Push(quest);
    CallAllFunctions(PlayerEventBindings, key);
}
References CallAllFunctions(), Hooks::PLAYER_EVENT_ON_COMPLETE_QUEST, PlayerEventBindings, Push(), and START_HOOK.
OnPlayerEnter()
void Eluna::OnPlayerEnter (Map * map, Player * player)
{
    START_HOOK(MAP_EVENT_ON_PLAYER_ENTER);
    Push(map);
    Push(player);
    CallAllFunctions(ServerEventBindings, key);
}
References CallAllFunctions(), Hooks::MAP_EVENT_ON_PLAYER_ENTER, Push(), ServerEventBindings, and START_HOOK.
OnPlayerEnterCombat()
void Eluna::OnPlayerEnterCombat (Player * pPlayer, Unit * pEnemy)
{
    START_HOOK(PLAYER_EVENT_ON_ENTER_COMBAT);
    Push(pPlayer);
    Push(pEnemy);
    CallAllFunctions(PlayerEventBindings, key);
}
References CallAllFunctions(), Hooks::PLAYER_EVENT_ON_ENTER_COMBAT, PlayerEventBindings, Push(), and START_HOOK.
OnPlayerEnterInstance()
void Eluna::OnPlayerEnterInstance (ElunaInstanceAI * ai, Player * player)
{
    START_HOOK(INSTANCE_EVENT_ON_PLAYER_ENTER, ai);
    Push(player);
    CallAllFunctions(MapEventBindings, InstanceEventBindings, mapKey, instanceKey);
}
References CallAllFunctions(), Hooks::INSTANCE_EVENT_ON_PLAYER_ENTER, InstanceEventBindings, MapEventBindings, Push(), and START_HOOK.
OnPlayerKilledByCreature()
void Eluna::OnPlayerKilledByCreature (Creature * pKiller, Player * pKilled)
{
    START_HOOK(PLAYER_EVENT_ON_KILLED_BY_CREATURE);
    Push(pKiller);
    Push(pKilled);
    CallAllFunctions(PlayerEventBindings, key);
}
References CallAllFunctions(), Hooks::PLAYER_EVENT_ON_KILLED_BY_CREATURE, PlayerEventBindings, Push(), and START_HOOK.
OnPlayerLeave()
void Eluna::OnPlayerLeave (Map * map, Player * player)
{
    START_HOOK(MAP_EVENT_ON_PLAYER_LEAVE);
    Push(map);
    Push(player);
    CallAllFunctions(ServerEventBindings, key);
}
References CallAllFunctions(), Hooks::MAP_EVENT_ON_PLAYER_LEAVE, Push(), ServerEventBindings, and START_HOOK.
OnPlayerLeaveCombat()
void Eluna::OnPlayerLeaveCombat (Player * pPlayer)
{
    START_HOOK(PLAYER_EVENT_ON_LEAVE_COMBAT);
    Push(pPlayer);
    CallAllFunctions(PlayerEventBindings, key);
}
References CallAllFunctions(), Hooks::PLAYER_EVENT_ON_LEAVE_COMBAT, PlayerEventBindings, Push(), and START_HOOK.
OnPVPKill()
void Eluna::OnPVPKill (Player * pKiller, Player * pKilled)
{
    START_HOOK(PLAYER_EVENT_ON_KILL_PLAYER);
    Push(pKiller);
    Push(pKilled);
    CallAllFunctions(PlayerEventBindings, key);
}
References CallAllFunctions(), Hooks::PLAYER_EVENT_ON_KILL_PLAYER, PlayerEventBindings, Push(), and START_HOOK.
OnQuestAbandon()
void Eluna::OnQuestAbandon (Player * pPlayer, uint32 questId)
{
    START_HOOK(PLAYER_EVENT_ON_QUEST_ABANDON);
    Push(pPlayer);
    Push(questId);
    CallAllFunctions(PlayerEventBindings, key);
}
References CallAllFunctions(), Hooks::PLAYER_EVENT_ON_QUEST_ABANDON, PlayerEventBindings, Push(), and START_HOOK.
OnQuestAccept() [1/3]
bool Eluna::OnQuestAccept (Player * pPlayer, Creature * pCreature, Quest const * pQuest)
{
    START_HOOK_WITH_RETVAL(CREATURE_EVENT_ON_QUEST_ACCEPT, pCreature, false);
    Push(pPlayer);
    Push(pCreature);
    Push(pQuest);
    return CallAllFunctionsBool(CreatureEventBindings, CreatureUniqueBindings, entry_key, unique_key);
}
References CallAllFunctionsBool(), Hooks::CREATURE_EVENT_ON_QUEST_ACCEPT, CreatureEventBindings, CreatureUniqueBindings, Push(), and START_HOOK_WITH_RETVAL.
OnQuestAccept() [2/3]
bool Eluna::OnQuestAccept (Player * pPlayer, GameObject * pGameObject, Quest const * pQuest)
{
    START_HOOK_WITH_RETVAL(GAMEOBJECT_EVENT_ON_QUEST_ACCEPT, pGameObject->GetEntry(), false);
    Push(pPlayer);
    Push(pGameObject);
    Push(pQuest);
    return CallAllFunctionsBool(GameObjectEventBindings, key);
}
References CallAllFunctionsBool(), Hooks::GAMEOBJECT_EVENT_ON_QUEST_ACCEPT, GameObjectEventBindings, Object::GetEntry(), Push(), and START_HOOK_WITH_RETVAL.
OnQuestAccept() [3/3]
bool Eluna::OnQuestAccept (Player * pPlayer, Item * pItem, Quest const * pQuest)
{
    START_HOOK_WITH_RETVAL(ITEM_EVENT_ON_QUEST_ACCEPT, pItem->GetEntry(), false);
    Push(pPlayer);
    Push(pItem);
    Push(pQuest);
    return CallAllFunctionsBool(ItemEventBindings, key);
}
References CallAllFunctionsBool(), Object::GetEntry(), Hooks::ITEM_EVENT_ON_QUEST_ACCEPT, ItemEventBindings, Push(), and START_HOOK_WITH_RETVAL.
OnQuestReward() [1/2]
bool Eluna::OnQuestReward (Player * pPlayer, Creature * pCreature, Quest const * pQuest, uint32 opt)
{
    START_HOOK_WITH_RETVAL(CREATURE_EVENT_ON_QUEST_REWARD, pCreature, false);
    Push(pPlayer);
    Push(pCreature);
    Push(pQuest);
    Push(opt);
    return CallAllFunctionsBool(CreatureEventBindings, CreatureUniqueBindings, entry_key, unique_key);
}
References CallAllFunctionsBool(), Hooks::CREATURE_EVENT_ON_QUEST_REWARD, CreatureEventBindings, CreatureUniqueBindings, Push(), and START_HOOK_WITH_RETVAL.
OnQuestReward() [2/2]
bool Eluna::OnQuestReward (Player * pPlayer, GameObject * pGameObject, Quest const * pQuest, uint32 opt)
{
    START_HOOK_WITH_RETVAL(GAMEOBJECT_EVENT_ON_QUEST_REWARD, pGameObject->GetEntry(), false);
    Push(pPlayer);
    Push(pGameObject);
    Push(pQuest);
    Push(opt);
    return CallAllFunctionsBool(GameObjectEventBindings, key);
}
References CallAllFunctionsBool(), Hooks::GAMEOBJECT_EVENT_ON_QUEST_REWARD, GameObjectEventBindings, Object::GetEntry(), Push(), and START_HOOK_WITH_RETVAL.
OnQuestRewardItem()
void Eluna::OnQuestRewardItem (Player * player, Item * item, uint32 count)
{
    START_HOOK(PLAYER_EVENT_ON_QUEST_REWARD_ITEM);
    Push(player);
    Push(item);
    Push(count);
    CallAllFunctions(PlayerEventBindings, key);
}
References CallAllFunctions(), Hooks::PLAYER_EVENT_ON_QUEST_REWARD_ITEM, PlayerEventBindings, Push(), and START_HOOK.
OnRemove() [1/4]
void Eluna::OnRemove (AuctionHouseObject * ah, AuctionEntry * entry)
{
#ifdef AZEROTHCORE
    Player* owner = eObjectAccessor()FindPlayer(entry->owner);
#else
    Player* owner = eObjectAccessor()FindPlayer(MAKE_NEW_GUID(entry->owner, 0, HIGHGUID_PLAYER));
#endif
#ifdef TRINITY
    Item* item = eAuctionMgr->GetAItem(entry->itemGUIDLow);
    uint32 expiretime = entry->expire_time;
#elif AZEROTHCORE
    Item* item = eAuctionMgr->GetAItem(entry->item_guid);
    uint32 expiretime = entry->expire_time;
#else
    Item* item = eAuctionMgr->GetAItem(entry->itemGuidLow);
    uint32 expiretime = entry->expireTime;
#endif
    if (!owner || !item)
        return;
    START_HOOK(AUCTION_EVENT_ON_REMOVE);
    Push(entry->Id);
    Push(owner);
    Push(item);
    Push(expiretime);
    Push(entry->buyout);
    Push(entry->startbid);
    Push(entry->bid);
    Push(entry->bidder);
    CallAllFunctions(ServerEventBindings, key);
}
References Hooks::AUCTION_EVENT_ON_REMOVE, AuctionEntry::bid, AuctionEntry::bidder, AuctionEntry::buyout, CallAllFunctions(), eAuctionMgr, eObjectAccessor, AuctionEntry::expire_time, AuctionEntry::Id, AuctionEntry::item_guid, AuctionEntry::owner, Push(), ServerEventBindings, START_HOOK, and AuctionEntry::startbid.
OnRemove() [2/4]
void Eluna::OnRemove (Creature * creature)
{
    START_HOOK(WORLD_EVENT_ON_DELETE_CREATURE);
    Push(creature);
    CallAllFunctions(ServerEventBindings, key);
}
References CallAllFunctions(), Push(), ServerEventBindings, START_HOOK, and Hooks::WORLD_EVENT_ON_DELETE_CREATURE.
OnRemove() [3/4]
void Eluna::OnRemove (GameObject * gameobject)
{
    START_HOOK(WORLD_EVENT_ON_DELETE_GAMEOBJECT);
    Push(gameobject);
    CallAllFunctions(ServerEventBindings, key);
}
References CallAllFunctions(), Push(), ServerEventBindings, START_HOOK, and Hooks::WORLD_EVENT_ON_DELETE_GAMEOBJECT.
OnRemove() [4/4]
bool Eluna::OnRemove (Player * pPlayer, Item * item)
{
    START_HOOK_WITH_RETVAL(ITEM_EVENT_ON_REMOVE, pItem->GetEntry(), false);
    Push(pPlayer);
    Push(pItem);
    return CallAllFunctionsBool(ItemEventBindings, key);
}
References CallAllFunctionsBool(), Object::GetEntry(), Hooks::ITEM_EVENT_ON_REMOVE, ItemEventBindings, Push(), and START_HOOK_WITH_RETVAL.
OnRemoveFromWorld() [1/2]
void Eluna::OnRemoveFromWorld (Creature * creature)
{
    START_HOOK(CREATURE_EVENT_ON_REMOVE, pCreature);
    Push(pCreature);
    CallAllFunctions(CreatureEventBindings, CreatureUniqueBindings, entry_key, unique_key);
}
References CallAllFunctions(), Hooks::CREATURE_EVENT_ON_REMOVE, CreatureEventBindings, CreatureUniqueBindings, Push(), and START_HOOK.
OnRemoveFromWorld() [2/2]
void Eluna::OnRemoveFromWorld (GameObject * gameobject)
{
    START_HOOK(GAMEOBJECT_EVENT_ON_REMOVE, pGameObject->GetEntry());
    Push(pGameObject);
    CallAllFunctions(GameObjectEventBindings, key);
}
References CallAllFunctions(), Hooks::GAMEOBJECT_EVENT_ON_REMOVE, GameObjectEventBindings, Object::GetEntry(), Push(), and START_HOOK.
OnRemoveMember() [1/2]
void Eluna::OnRemoveMember (Group * group, ObjectGuid guid, uint8 method)
{
    START_HOOK(GROUP_EVENT_ON_MEMBER_REMOVE);
    Push(group);
    Push(guid);
    Push(method);
    CallAllFunctions(GroupEventBindings, key);
}
References CallAllFunctions(), Hooks::GROUP_EVENT_ON_MEMBER_REMOVE, GroupEventBindings, Push(), and START_HOOK.
OnRemoveMember() [2/2]
void Eluna::OnRemoveMember (Guild * guild, Player * player, bool isDisbanding)
{
    START_HOOK(GUILD_EVENT_ON_REMOVE_MEMBER);
    Push(guild);
    Push(player);
    Push(isDisbanding);
    CallAllFunctions(GuildEventBindings, key);
}
References CallAllFunctions(), Hooks::GUILD_EVENT_ON_REMOVE_MEMBER, GuildEventBindings, Push(), and START_HOOK.
OnRemovePassenger()
void Eluna::OnRemovePassenger (Vehicle * vehicle, Unit * passenger)
{
    START_HOOK(VEHICLE_EVENT_ON_REMOVE_PASSENGER);
    Push(vehicle);
    Push(passenger);
    CallAllFunctions(VehicleEventBindings, key);
}
References CallAllFunctions(), Push(), START_HOOK, Hooks::VEHICLE_EVENT_ON_REMOVE_PASSENGER, and VehicleEventBindings.
OnRepop()
void Eluna::OnRepop (Player * pPlayer)
{
    START_HOOK(PLAYER_EVENT_ON_REPOP);
    Push(pPlayer);
    CallAllFunctions(PlayerEventBindings, key);
}
References CallAllFunctions(), Hooks::PLAYER_EVENT_ON_REPOP, PlayerEventBindings, Push(), and START_HOOK.
OnReputationChange()
bool Eluna::OnReputationChange (Player * pPlayer, uint32 factionID, int32 & standing, bool incremental)
{
    START_HOOK_WITH_RETVAL(PLAYER_EVENT_ON_REPUTATION_CHANGE, true);
    bool result = true;
    Push(pPlayer);
    Push(factionID);
    Push(standing);
    Push(incremental);
    int standingIndex = lua_gettop(L) - 1;
    int n = SetupStack(PlayerEventBindings, key, 4);
    while (n > 0)
    {
        int r = CallOneFunction(n--, 4, 1);
        if (lua_isnumber(L, r))
        {
            standing = CHECKVAL<int32>(L, r);
            if (standing == -1)
                result = false;
            // Update the stack for subsequent calls.
            ReplaceArgument(standing, standingIndex);
        }
        lua_pop(L, 1);
    }
    CleanUpStack(4);
    return result;
}
References CallOneFunction(), CleanUpStack(), L, lua_gettop(), lua_isnumber(), lua_pop, Hooks::PLAYER_EVENT_ON_REPUTATION_CHANGE, PlayerEventBindings, Push(), ReplaceArgument(), SetupStack(), and START_HOOK_WITH_RETVAL.
OnResurrect()
void Eluna::OnResurrect (Player * pPlayer)
{
    START_HOOK(PLAYER_EVENT_ON_RESURRECT);
    Push(pPlayer);
    CallAllFunctions(PlayerEventBindings, key);
}
References CallAllFunctions(), Hooks::PLAYER_EVENT_ON_RESURRECT, PlayerEventBindings, Push(), and START_HOOK.
OnSave()
void Eluna::OnSave (Player * pPlayer)
{
    START_HOOK(PLAYER_EVENT_ON_SAVE);
    Push(pPlayer);
    CallAllFunctions(PlayerEventBindings, key);
}
References CallAllFunctions(), Hooks::PLAYER_EVENT_ON_SAVE, PlayerEventBindings, Push(), and START_HOOK.
OnShutdown()
void Eluna::OnShutdown ()
{
    START_HOOK(WORLD_EVENT_ON_SHUTDOWN);
    CallAllFunctions(ServerEventBindings, key);
}
References CallAllFunctions(), ServerEventBindings, START_HOOK, and Hooks::WORLD_EVENT_ON_SHUTDOWN.
OnShutdownCancel()
void Eluna::OnShutdownCancel ()
{
    START_HOOK(WORLD_EVENT_ON_SHUTDOWN_CANCEL);
    CallAllFunctions(ServerEventBindings, key);
}
References CallAllFunctions(), ServerEventBindings, START_HOOK, and Hooks::WORLD_EVENT_ON_SHUTDOWN_CANCEL.
OnShutdownInitiate()
void Eluna::OnShutdownInitiate (ShutdownExitCode code, ShutdownMask mask)
{
    START_HOOK(WORLD_EVENT_ON_SHUTDOWN_INIT);
    Push(code);
    Push(mask);
    CallAllFunctions(ServerEventBindings, key);
}
References CallAllFunctions(), Push(), ServerEventBindings, START_HOOK, and Hooks::WORLD_EVENT_ON_SHUTDOWN_INIT.
OnSpawn()
void Eluna::OnSpawn (GameObject * gameobject)
{
    START_HOOK(GAMEOBJECT_EVENT_ON_SPAWN, pGameObject->GetEntry());
    Push(pGameObject);
    CallAllFunctions(GameObjectEventBindings, key);
}
References CallAllFunctions(), Hooks::GAMEOBJECT_EVENT_ON_SPAWN, GameObjectEventBindings, Object::GetEntry(), Push(), and START_HOOK.
OnSpellCast()
void Eluna::OnSpellCast (Player * pPlayer, Spell * pSpell, bool skipCheck)
{
    START_HOOK(PLAYER_EVENT_ON_SPELL_CAST);
    Push(pPlayer);
    Push(pSpell);
    Push(skipCheck);
    CallAllFunctions(PlayerEventBindings, key);
}
References CallAllFunctions(), Hooks::PLAYER_EVENT_ON_SPELL_CAST, PlayerEventBindings, Push(), and START_HOOK.
OnStartup()
void Eluna::OnStartup ()
{
    START_HOOK(WORLD_EVENT_ON_STARTUP);
    CallAllFunctions(ServerEventBindings, key);
}
References CallAllFunctions(), ServerEventBindings, START_HOOK, and Hooks::WORLD_EVENT_ON_STARTUP.
OnStoreNewItem()
void Eluna::OnStoreNewItem (Player * player, Item * item, uint32 count)
{
    START_HOOK(PLAYER_EVENT_ON_STORE_NEW_ITEM);
    Push(player);
    Push(item);
    Push(count);
    CallAllFunctions(PlayerEventBindings, key);
}
References CallAllFunctions(), Hooks::PLAYER_EVENT_ON_STORE_NEW_ITEM, PlayerEventBindings, Push(), and START_HOOK.
OnSuccessful()
void Eluna::OnSuccessful (AuctionHouseObject * ah, AuctionEntry * entry)
{
#ifdef AZEROTHCORE
    Player* owner = eObjectAccessor()FindPlayer(entry->owner);
#else
    Player* owner = eObjectAccessor()FindPlayer(MAKE_NEW_GUID(entry->owner, 0, HIGHGUID_PLAYER));
#endif
#ifdef TRINITY
    Item* item = eAuctionMgr->GetAItem(entry->itemGUIDLow);
    uint32 expiretime = entry->expire_time;
#elif AZEROTHCORE
    Item* item = eAuctionMgr->GetAItem(entry->item_guid);
    uint32 expiretime = entry->expire_time;
#else
    Item* item = eAuctionMgr->GetAItem(entry->itemGuidLow);
    uint32 expiretime = entry->expireTime;
#endif
    if (!owner || !item)
        return;
    START_HOOK(AUCTION_EVENT_ON_SUCCESSFUL);
    Push(entry->Id);
    Push(owner);
    Push(item);
    Push(expiretime);
    Push(entry->buyout);
    Push(entry->startbid);
    Push(entry->bid);
    Push(entry->bidder);
    CallAllFunctions(ServerEventBindings, key);
}
References Hooks::AUCTION_EVENT_ON_SUCCESSFUL, AuctionEntry::bid, AuctionEntry::bidder, AuctionEntry::buyout, CallAllFunctions(), eAuctionMgr, eObjectAccessor, AuctionEntry::expire_time, AuctionEntry::Id, AuctionEntry::item_guid, AuctionEntry::owner, Push(), ServerEventBindings, START_HOOK, and AuctionEntry::startbid.
OnSummoned()
bool Eluna::OnSummoned (Creature * creature, Unit * summoner)
{
    START_HOOK_WITH_RETVAL(CREATURE_EVENT_ON_SUMMONED, pCreature, false);
    Push(pCreature);
    Push(pSummoner);
    return CallAllFunctionsBool(CreatureEventBindings, CreatureUniqueBindings, entry_key, unique_key);
}
References CallAllFunctionsBool(), Hooks::CREATURE_EVENT_ON_SUMMONED, CreatureEventBindings, CreatureUniqueBindings, Push(), and START_HOOK_WITH_RETVAL.
OnTalentsReset()
void Eluna::OnTalentsReset (Player * pPlayer, bool noCost)
{
    START_HOOK(PLAYER_EVENT_ON_TALENTS_RESET);
    Push(pPlayer);
    Push(noCost);
    CallAllFunctions(PlayerEventBindings, key);
}
References CallAllFunctions(), Hooks::PLAYER_EVENT_ON_TALENTS_RESET, PlayerEventBindings, Push(), and START_HOOK.
OnTextEmote()
void Eluna::OnTextEmote (Player * pPlayer, uint32 textEmote, uint32 emoteNum, ObjectGuid guid)
{
    START_HOOK(PLAYER_EVENT_ON_TEXT_EMOTE);
    Push(pPlayer);
    Push(textEmote);
    Push(emoteNum);
    Push(guid);
    CallAllFunctions(PlayerEventBindings, key);
}
References CallAllFunctions(), Hooks::PLAYER_EVENT_ON_TEXT_EMOTE, PlayerEventBindings, Push(), and START_HOOK.
OnTimedEvent()
void Eluna::OnTimedEvent (int funcRef, uint32 delay, uint32 calls, WorldObject * obj)
{
    LOCK_ELUNA;
    ASSERT(!event_level);
    // Get function
    lua_rawgeti(L, LUA_REGISTRYINDEX, funcRef);
    // Push parameters
    Push(L, funcRef);
    Push(L, delay);
    Push(L, calls);
    Push(L, obj);
    // Call function
    ExecuteCall(4, 0);
    ASSERT(!event_level);
    InvalidateObjects();
}
References ASSERT, event_level, ExecuteCall(), InvalidateObjects(), L, LOCK_ELUNA, lua_rawgeti(), LUA_REGISTRYINDEX, and Push().
OnUninstall()
void Eluna::OnUninstall (Vehicle * vehicle)
{
    START_HOOK(VEHICLE_EVENT_ON_UNINSTALL);
    Push(vehicle);
    CallAllFunctions(VehicleEventBindings, key);
}
References CallAllFunctions(), Push(), START_HOOK, Hooks::VEHICLE_EVENT_ON_UNINSTALL, and VehicleEventBindings.
OnUpdate()
void Eluna::OnUpdate (Map * map, uint32 diff)
{
    START_HOOK(MAP_EVENT_ON_UPDATE);
    // enable this for multithread
    // eventMgr->globalProcessor->Update(diff);
    Push(map);
    Push(diff);
    CallAllFunctions(ServerEventBindings, key);
}
References CallAllFunctions(), Hooks::MAP_EVENT_ON_UPDATE, Push(), ServerEventBindings, and START_HOOK.
OnUpdateArea()
void Eluna::OnUpdateArea (Player * pPlayer, uint32 oldArea, uint32 newArea)
{
    START_HOOK(PLAYER_EVENT_ON_UPDATE_AREA);
    Push(pPlayer);
    Push(oldArea);
    Push(newArea);
    CallAllFunctions(PlayerEventBindings, key);
}
References CallAllFunctions(), Hooks::PLAYER_EVENT_ON_UPDATE_AREA, PlayerEventBindings, Push(), and START_HOOK.
OnUpdateInstance()
void Eluna::OnUpdateInstance (ElunaInstanceAI * ai, uint32 diff)
{
    START_HOOK(INSTANCE_EVENT_ON_UPDATE, ai);
    Push(diff);
    CallAllFunctions(MapEventBindings, InstanceEventBindings, mapKey, instanceKey);
}
References CallAllFunctions(), Hooks::INSTANCE_EVENT_ON_UPDATE, InstanceEventBindings, MapEventBindings, Push(), and START_HOOK.
OnUpdateZone()
void Eluna::OnUpdateZone (Player * pPlayer, uint32 newZone, uint32 newArea)
{
    START_HOOK(PLAYER_EVENT_ON_UPDATE_ZONE);
    Push(pPlayer);
    Push(newZone);
    Push(newArea);
    CallAllFunctions(PlayerEventBindings, key);
}
References CallAllFunctions(), Hooks::PLAYER_EVENT_ON_UPDATE_ZONE, PlayerEventBindings, Push(), and START_HOOK.
OnUse()
bool Eluna::OnUse (Player * pPlayer, Item * pItem, SpellCastTargets const & targets)
{
    ObjectGuid guid = pItem->GET_GUID();
    bool castSpell = true;
    if (!OnItemUse(pPlayer, pItem, targets))
        castSpell = false;
    pItem = pPlayer->GetItemByGuid(guid);
    if (pItem)
    {
        if (!OnItemGossip(pPlayer, pItem, targets))
            castSpell = false;
        pItem = pPlayer->GetItemByGuid(guid);
    }
    if (pItem && castSpell)
        return true;
    // Send equip error that shows no message
    // This is a hack fix to stop spell casting visual bug when a spell is not cast on use
    WorldPacket data(SMSG_INVENTORY_CHANGE_FAILURE, 18);
    data << uint8(59); // EQUIP_ERR_NONE / EQUIP_ERR_CANT_BE_DISENCHANTED
    data << guid;
    data << ObjectGuid(uint64(0));
    data << uint8(0);
#ifdef CMANGOS
    pPlayer->GetSession()->SendPacket(data);
#else
    pPlayer->GetSession()->SendPacket(&data);
#endif
    return false;
}
References Player::GetItemByGuid(), Player::GetSession(), OnItemGossip(), OnItemUse(), WorldSession::SendPacket(), and SMSG_INVENTORY_CHANGE_FAILURE.
OnWorldUpdate()
void Eluna::OnWorldUpdate (uint32 diff)
{
    {
        LOCK_ELUNA;
        if (ShouldReload())
            _ReloadEluna();
    }
    eventMgr->globalProcessor->Update(diff);
    httpManager.HandleHttpResponses();
    queryProcessor.ProcessReadyCallbacks();
    START_HOOK(WORLD_EVENT_ON_UPDATE);
    Push(diff);
    CallAllFunctions(ServerEventBindings, key);
}
References _ReloadEluna(), CallAllFunctions(), eventMgr, EventMgr::globalProcessor, HttpManager::HandleHttpResponses(), httpManager, LOCK_ELUNA, AsyncCallbackProcessor< T >::ProcessReadyCallbacks(), Push(), queryProcessor, ServerEventBindings, ShouldReload(), START_HOOK, ElunaEventProcessor::Update(), and Hooks::WORLD_EVENT_ON_UPDATE.
OpenLua()
void Eluna::OpenLua () private
{
#if defined(AZEROTHCORE)
    enabled = eConfigMgr->GetOption<bool>("Eluna.Enabled", true);
#else
    enabled = eConfigMgr->GetBoolDefault("Eluna.Enabled", true);
#endif
    if (!IsEnabled())
    {
        ELUNA_LOG_INFO("[Eluna]: Eluna is disabled in config");
        return;
    }
    L = luaL_newstate();
    lua_pushlightuserdata(L, this);
    lua_setfield(L, LUA_REGISTRYINDEX, ELUNA_STATE_PTR);
    CreateBindStores();
    // open base lua libraries
    luaL_openlibs(L);
    // open additional lua libraries
    // Register methods and functions
    RegisterFunctions(this);
    // Set lua require folder paths (scripts folder structure)
    lua_getglobal(L, "package");
    lua_pushstring(L, lua_requirepath.c_str());
    lua_setfield(L, -2, "path");
    lua_pushstring(L, ""); // erase cpath
    lua_setfield(L, -2, "cpath");
    lua_pop(L, 1);
}
References CreateBindStores(), eConfigMgr, ELUNA_LOG_INFO, ELUNA_STATE_PTR, enabled, IsEnabled(), L, lua_getglobal(), lua_pop, lua_pushlightuserdata(), lua_pushstring(), LUA_REGISTRYINDEX, lua_requirepath, lua_setfield(), luaL_newstate(), luaL_openlibs(), and RegisterFunctions().
Referenced by Eluna().
operator=()
Eluna & Eluna::operator= (const Eluna &) private delete
OwnerAttacked()
bool Eluna::OwnerAttacked (Creature * me, Unit * target)
OwnerAttackedBy()
bool Eluna::OwnerAttackedBy (Creature * me, Unit * attacker)
Push() [1/33]
void Eluna::Push () inline private
{ Push(L); ++push_counter; }
References Push().
Referenced by ElunaTemplate< T >::Add(), LuaUnit::AddAura(), LuaPlayer::AddItem(), LuaGameObject::AddLoot(), LuaGroup::AddMember(), LuaGlobalFunctions::AddTaxiPath(), LuaUnit::Attack(), AttackStart(), LuaUnit::AttackStop(), LuaGlobalFunctions::AuthDBQuery(), LuaGlobalFunctions::Ban(), LuaGlobalFunctions::bit_and(), LuaGlobalFunctions::bit_lshift(), LuaGlobalFunctions::bit_not(), LuaGlobalFunctions::bit_or(), LuaGlobalFunctions::bit_rshift(), LuaGlobalFunctions::bit_xor(), LuaCreature::CanAggro(), LuaCreature::CanAssistTo(), LuaItem::CanBeTraded(), LuaPlayer::CanBlock(), LuaCreature::CanCompleteQuest(), LuaPlayer::CanCompleteQuest(), LuaPlayer::CanCompleteRepeatableQuest(), LuaPlayer::CanEquipItem(), LuaCreature::CanFly(), LuaPlayer::CanFly(), LuaPlayer::CanParry(), LuaPlayer::CanRewardQuest(), LuaPlayer::CanShareQuest(), LuaPlayer::CanSpeak(), LuaCreature::CanSwim(), LuaPlayer::CanTitanGrip(), LuaPlayer::CanUninviteFromGroup(), LuaPlayer::CanUseItem(), LuaCreature::CanWalk(), LuaGlobalFunctions::CharDBQuery(), LuaItem::ClearEnchantment(), CorpseRemoved(), LuaUnit::CountPctFromCurHealth(), LuaUnit::CountPctFromMaxHealth(), createCancelCallback(), LuaGlobalFunctions::CreateLongLong(), LuaGlobalFunctions::CreateLuaEvent(), LuaGlobalFunctions::CreatePacket(), LuaGlobalFunctions::CreateULongLong(), DamageTaken(), ElunaTemplate< T >::Divide(), EnterCombat(), EnterEvadeMode(), ElunaTemplate< T >::Equal(), LuaPlayer::EquipItem(), LuaPlayer::GetAccountId(), LuaPlayer::GetAccountName(), LuaPlayer::GetAchievementCriteriaProgress(), LuaGlobalFunctions::GetActiveGameEvents(), LuaPlayer::GetActiveSpec(), LuaCreature::GetAggroRange(), LuaCreature::GetAIName(), LuaCreature::GetAITarget(), LuaCreature::GetAITargets(), LuaCreature::GetAITargetsCount(), LuaBattleGround::GetAlivePlayersCountByTeam(), LuaItem::GetAllowableClass(), LuaItemTemplate::GetAllowableClass(), LuaItem::GetAllowableRace(), LuaItemTemplate::GetAllowableRace(), LuaWorldObject::GetAngle(), LuaMap::GetAreaId(), LuaWorldObject::GetAreaId(), LuaGlobalFunctions::GetAreaName(), LuaCreature::GetAttackDistance(), LuaUnit::GetAttackers(), LuaUnit::GetAura(), LuaAura::GetAuraId(), LuaItem::GetBagSize(), LuaItem::GetBagSlot(), LuaPlayer::GetBaseSkillValue(), LuaUnit::GetBaseSpellPower(), LuaPlayer::GetBattlegroundId(), LuaPlayer::GetBattlegroundTypeId(), LuaBattleGround::GetBonusHonorFromKillCount(), LuaQuery::GetBool(), LuaBattleGround::GetBracketId(), LuaItem::GetBuyCount(), LuaItemTemplate::GetBuyCount(), LuaItem::GetBuyPrice(), LuaItemTemplate::GetBuyPrice(), LuaObject::GetByteValue(), LuaAura::GetCaster(), LuaSpell::GetCaster(), LuaAura::GetCasterGUID(), LuaAura::GetCasterLevel(), LuaSpell::GetCastTime(), LuaUnit::GetCharmerGUID(), LuaUnit::GetCharmGUID(), LuaPlayer::GetChatTag(), LuaItem::GetClass(), LuaItemTemplate::GetClass(), LuaUnit::GetClass(), LuaUnit::GetClassAsString(), LuaUnit::GetClassMask(), LuaPlayer::GetCoinage(), LuaQuery::GetColumnCount(), LuaPlayer::GetComboPoints(), LuaPlayer::GetComboTarget(), LuaPlayer::GetCompletedQuestsCount(), LuaUnit::GetControllerGUID(), LuaUnit::GetControllerGUIDS(), LuaGlobalFunctions::GetCoreExpansion(), LuaGlobalFunctions::GetCoreName(), LuaGlobalFunctions::GetCoreVersion(), LuaPlayer::GetCorpse(), LuaCreature::GetCorpseDelay(), LuaItem::GetCount(), LuaUnit::GetCreatorGUID(), LuaCreature::GetCreatureFamily(), LuaWorldObject::GetCreaturesInRange(), LuaCreature::GetCreatureSpellCooldownDelay(), LuaUnit::GetCreatureType(), LuaUnit::GetCritterGUID(), LuaUnit::GetCurrentSpell(), LuaCreature::GetCurrentWaypointId(), LuaGlobalFunctions::GetCurrTime(), ElunaInstanceAI::GetData(), ElunaInstanceAI::GetData64(), LuaPlayer::GetDbcLocale(), LuaPlayer::GetDbLocaleIndex(), LuaCreature::GetDBTableGUIDLow(), LuaGameObject::GetDBTableGUIDLow(), LuaCreature::GetDefaultMovementType(), GetDialogStatus(), GetDialogStatus(), LuaMap::GetDifficulty(), LuaPlayer::GetDifficulty(), LuaGameObject::GetDisplayId(), LuaItem::GetDisplayId(), LuaItemTemplate::GetDisplayId(), LuaUnit::GetDisplayId(), LuaWorldObject::GetDistance(), LuaWorldObject::GetDistance2d(), LuaQuery::GetDouble(), LuaPlayer::GetDrunkValue(), LuaAura::GetDuration(), LuaSpell::GetDuration(), LuaItem::GetEnchantmentId(), LuaBattleGround::GetEndTime(), LuaObject::GetEntry(), LuaSpell::GetEntry(), LuaVehicle::GetEntry(), LuaPlayer::GetEquippedItemBySlot(), LuaWorldObject::GetExactDistance(), LuaWorldObject::GetExactDistance2d(), LuaCreature::GetExtraFlags(), LuaItemTemplate::GetExtraFlags(), LuaUnit::GetFaction(), LuaItemTemplate::GetFlags(), LuaQuest::GetFlags(), LuaQuery::GetFloat(), LuaObject::GetFloatValue(), LuaBattleGround::GetFreeSlotsForTeam(), LuaPlayer::GetFreeTalentPoints(), LuaUnit::GetFriendlyUnitsInRange(), LuaWorldObject::GetGameObjectsInRange(), LuaGlobalFunctions::GetGameTime(), LuaUnit::GetGender(), LuaCorpse::GetGhostTime(), LuaPlayer::GetGlyph(), LuaPlayer::GetGMRank(), LuaPlayer::GetGossipTextId(), LuaGameObject::GetGoState(), LuaPlayer::GetGroup(), LuaPlayer::GetGroupInvite(), LuaGroup::GetGroupType(), LuaGroup::GetGUID(), LuaObject::GetGUID(), LuaGlobalFunctions::GetGUIDEntry(), LuaGlobalFunctions::GetGUIDLow(), LuaObject::GetGUIDLow(), LuaGlobalFunctions::GetGUIDType(), LuaPlayer::GetGuild(), LuaGlobalFunctions::GetGuildByLeaderGUID(), LuaGlobalFunctions::GetGuildByName(), LuaPlayer::GetGuildId(), LuaPlayer::GetGuildName(), LuaPlayer::GetGuildRank(), LuaUnit::GetHealth(), LuaPlayer::GetHealthBonusFromStamina(), LuaUnit::GetHealthPct(), LuaMap::GetHeight(), LuaCreature::GetHomePosition(), LuaAchievement::GetId(), LuaGuild::GetId(), LuaQuest::GetId(), LuaGuild::GetInfo(), LuaPlayer::GetInGameTime(), LuaMap::GetInstanceData(), LuaBattleGround::GetInstanceId(), LuaMap::GetInstanceId(), LuaWorldObject::GetInstanceId(), LuaQuery::GetInt16(), LuaQuery::GetInt32(), LuaObject::GetInt32Value(), LuaQuery::GetInt64(), LuaQuery::GetInt8(), LuaItem::GetInventoryType(), LuaItemTemplate::GetInventoryType(), LuaPlayer::GetItemByEntry(), LuaPlayer::GetItemByGUID(), LuaPlayer::GetItemByPos(), LuaPlayer::GetItemCount(), LuaRoll::GetItemCount(), LuaGlobalFunctions::GetItemGUID(), LuaRoll::GetItemGUID(), LuaItemTemplate::GetItemId(), LuaRoll::GetItemId(), LuaItem::GetItemLevel(), LuaItemTemplate::GetItemLevel(), LuaGlobalFunctions::GetItemLink(), LuaItem::GetItemLink(), LuaRoll::GetItemRandomPropId(), LuaRoll::GetItemRandomSuffix(), LuaItem::GetItemSet(), LuaRoll::GetItemSlot(), LuaGlobalFunctions::GetItemTemplate(), LuaItem::GetItemTemplate(), LuaPlayer::GetLatency(), LuaGuild::GetLeader(), LuaGroup::GetLeaderGUID(), LuaGuild::GetLeaderGUID(), LuaQuest::GetLevel(), LuaUnit::GetLevel(), LuaPlayer::GetLevelPlayedTime(), LuaPlayer::GetLifetimeKills(), LuaWorldObject::GetLocation(), LuaCreature::GetLootRecipient(), LuaGameObject::GetLootRecipient(), LuaCreature::GetLootRecipientGroup(), LuaGameObject::GetLootRecipientGroup(), LuaGameObject::GetLootState(), LuaGlobalFunctions::GetLuaEngine(), LuaPlayer::GetMailCount(), LuaPlayer::GetMailItem(), LuaPlayer::GetManaBonusFromIntellect(), LuaBattleGround::GetMap(), LuaWorldObject::GetMap(), LuaGlobalFunctions::GetMapById(), LuaBattleGround::GetMapId(), LuaMap::GetMapId(), LuaWorldObject::GetMapId(), LuaAura::GetMaxDuration(), LuaUnit::GetMaxHealth(), LuaBattleGround::GetMaxLevel(), LuaBattleGround::GetMaxPlayers(), LuaBattleGround::GetMaxPlayersPerTeam(), LuaUnit::GetMaxPower(), LuaPlayer::GetMaxSkillValue(), LuaItem::GetMaxStackCount(), LuaGuild::GetMemberCount(), LuaGroup::GetMemberGroup(), LuaGroup::GetMemberGUID(), LuaGroup::GetMembers(), LuaGuild::GetMembers(), LuaGroup::GetMembersCount(), LuaBattleGround::GetMinLevel(), LuaQuest::GetMinLevel(), LuaBattleGround::GetMinPlayers(), LuaBattleGround::GetMinPlayersPerTeam(), LuaGuild::GetMOTD(), LuaUnit::GetMountId(), LuaUnit::GetMovementType(), LuaAchievement::GetName(), LuaBattleGround::GetName(), LuaGuild::GetName(), LuaItem::GetName(), LuaItemTemplate::GetName(), LuaMap::GetName(), LuaWorldObject::GetName(), LuaUnit::GetNativeDisplayId(), LuaWorldObject::GetNearestCreature(), LuaWorldObject::GetNearestGameObject(), LuaWorldObject::GetNearestPlayer(), LuaWorldObject::GetNearObject(), LuaWorldObject::GetNearObjects(), LuaQuest::GetNextQuestId(), LuaQuest::GetNextQuestInChain(), LuaPlayer::GetNextRandomRaidMember(), LuaCreature::GetNPCFlags(), LuaWorldObject::GetO(), LuaGlobalFunctions::GetObjectGUID(), LuaPacket::GetOpcode(), LuaPlayer::GetOriginalGroup(), LuaPlayer::GetOriginalSubGroup(), LuaAura::GetOwner(), LuaItem::GetOwner(), LuaUnit::GetOwner(), LuaVehicle::GetOwner(), LuaCorpse::GetOwnerGUID(), LuaItem::GetOwnerGUID(), LuaUnit::GetOwnerGUID(), LuaVehicle::GetPassenger(), LuaUnit::GetPetGUID(), LuaWorldObject::GetPhaseMask(), LuaChatHandler::GetPlayer(), LuaGlobalFunctions::GetPlayerByGUID(), LuaGlobalFunctions::GetPlayerByName(), LuaGlobalFunctions::GetPlayerCount(), LuaMap::GetPlayerCount(), LuaGlobalFunctions::GetPlayerGUID(), LuaPlayer::GetPlayerIP(), LuaMap::GetPlayers(), LuaPlayer::GetPlayerSettingValue(), LuaWorldObject::GetPlayersInRange(), LuaRoll::GetPlayerVote(), LuaRoll::GetPlayerVoteGUIDs(), LuaUnit::GetPower(), LuaSpell::GetPowerCost(), LuaUnit::GetPowerPct(), LuaUnit::GetPowerType(), LuaQuest::GetPrevQuestId(), LuaPlayer::GetPureMaxSkillValue(), LuaPlayer::GetPureSkillValue(), LuaItem::GetQuality(), LuaItemTemplate::GetQuality(), LuaGlobalFunctions::GetQuest(), LuaPlayer::GetQuestLevel(), LuaPlayer::GetQuestRewardStatus(), LuaPlayer::GetQuestStatus(), LuaUnit::GetRace(), LuaUnit::GetRaceAsString(), LuaUnit::GetRaceMask(), LuaItem::GetRandomProperty(), LuaItem::GetRandomSuffix(), LuaCreature::GetRank(), LuaSpell::GetReagentCost(), LuaGlobalFunctions::GetRealmID(), LuaWorldObject::GetRelativePoint(), LuaPlayer::GetReputation(), LuaPlayer::GetReputationRank(), LuaPlayer::GetReqKillOrCastCurrentCount(), LuaItem::GetRequiredLevel(), LuaItemTemplate::GetRequiredLevel(), LuaCreature::GetRespawnDelay(), LuaPlayer::GetRestBonus(), LuaRoll::GetRollVoteMask(), LuaQuery::GetRow(), LuaQuery::GetRowCount(), LuaObject::GetScale(), LuaCreature::GetScriptId(), LuaCreature::GetScriptName(), LuaChatHandler::GetSelectedCreature(), LuaChatHandler::GetSelectedObject(), LuaChatHandler::GetSelectedPlayer(), LuaChatHandler::GetSelectedPlayerOrSelf(), LuaChatHandler::GetSelectedUnit(), LuaPlayer::GetSelection(), LuaItem::GetSellPrice(), LuaItemTemplate::GetSellPrice(), LuaPacket::GetSize(), LuaPlayer::GetSkillPermBonusValue(), LuaPlayer::GetSkillTempBonusValue(), LuaPlayer::GetSkillValue(), LuaItem::GetSlot(), LuaPlayer::GetSpecsCount(), LuaUnit::GetSpeed(), LuaUnit::GetSpeedRate(), LuaPlayer::GetSpellCooldownDelay(), LuaItem::GetSpellId(), LuaItem::GetSpellTrigger(), LuaAura::GetStackAmount(), LuaUnit::GetStandState(), LuaUnit::GetStat(), LuaGlobalFunctions::GetStateInstanceId(), LuaGlobalFunctions::GetStateMap(), LuaGlobalFunctions::GetStateMapId(), LuaBattleGround::GetStatus(), LuaQuery::GetString(), LuaItem::GetSubClass(), LuaItemTemplate::GetSubClass(), LuaPlayer::GetSubGroup(), LuaSpell::GetTarget(), LuaSpell::GetTargetDest(), LuaPlayer::GetTeam(), LuaUnit::GetThreatList(), LuaGlobalFunctions::GetTimeDiff(), LuaRoll::GetTotalGreed(), LuaRoll::GetTotalNeed(), LuaRoll::GetTotalPass(), LuaPlayer::GetTotalPlayedTime(), LuaRoll::GetTotalPlayersRolling(), LuaPlayer::GetTrader(), LuaCorpse::GetType(), LuaQuest::GetType(), LuaBattleGround::GetTypeId(), LuaObject::GetTypeId(), LuaQuery::GetUInt16(), LuaObject::GetUInt16Value(), LuaQuery::GetUInt32(), LuaObject::GetUInt32Value(), LuaQuery::GetUInt64(), LuaObject::GetUInt64Value(), LuaQuery::GetUInt8(), LuaUnit::GetUnfriendlyUnitsInRange(), LuaCreature::GetUnitFlags(), LuaCreature::GetUnitFlagsTwo(), LuaGlobalFunctions::GetUnitGUID(), LuaUnit::GetVehicleKit(), LuaUnit::GetVictim(), LuaCreature::GetWanderRadius(), LuaBattleGround::GetWinner(), LuaMap::GetWorldObject(), LuaWorldObject::GetX(), LuaPlayer::GetXP(), LuaPlayer::GetXPRestBonus(), LuaWorldObject::GetY(), LuaWorldObject::GetZ(), LuaWorldObject::GetZoneId(), LuaPlayer::GroupCreate(), LuaPlayer::GroupInvite(), HandleGossipSelectOption(), HandleGossipSelectOption(), HttpManager::HandleHttpResponses(), LuaUnit::HandleStatModifier(), LuaPlayer::HasAchieved(), LuaPlayer::HasAtLoginFlag(), LuaUnit::HasAura(), LuaPlayer::HasCasterSpec(), LuaCreature::HasCategoryCooldown(), LuaObject::HasFlag(), LuaQuest::HasFlag(), LuaGroup::HasFreeSlotSubGroup(), LuaPlayer::HasHealSpec(), LuaPlayer::HasItem(), LuaCreature::HasLootRecipient(), LuaChatHandler::HasLowerSecurity(), LuaChatHandler::HasLowerSecurityAccount(), LuaPlayer::HasMeleeSpec(), LuaCreature::HasQuest(), LuaGameObject::HasQuest(), LuaItem::HasQuest(), LuaPlayer::HasQuest(), LuaPlayer::HasQuestForGO(), LuaPlayer::HasQuestForItem(), LuaCreature::HasSearchedAssistance(), LuaChatHandler::HasSentErrorMessage(), LuaPlayer::HasSkill(), LuaCreature::HasSpell(), LuaPlayer::HasSpell(), LuaCreature::HasSpellCooldown(), LuaPlayer::HasSpellCooldown(), LuaPlayer::HasTalent(), LuaPlayer::HasTankSpec(), LuaPlayer::HasTitle(), LuaUnit::HasUnitState(), LuaUnit::HealthAbovePct(), LuaUnit::HealthBelowPct(), LuaPlayer::InArena(), LuaPlayer::InBattleground(), LuaPlayer::InBattlegroundQueue(), LuaPlayer::IsAcceptingWhispers(), LuaGameObject::IsActive(), LuaPlayer::IsAFK(), LuaUnit::IsAlive(), LuaPlayer::IsAlliance(), LuaMap::IsArena(), LuaUnit::IsArmorer(), LuaGroup::IsAssistant(), LuaUnit::IsAttackingPlayer(), LuaUnit::IsAuctioneer(), LuaSpell::IsAutoRepeat(), LuaChatHandler::IsAvailable(), LuaItem::IsBag(), LuaGlobalFunctions::IsBagPos(), LuaUnit::IsBanker(), LuaGlobalFunctions::IsBankPos(), LuaMap::IsBattleground(), LuaUnit::IsBattleMaster(), LuaGroup::IsBGGroup(), LuaItem::IsBoundAccountWide(), LuaItem::IsBoundByEnchant(), LuaItem::IsBroken(), LuaUnit::IsCasting(), LuaUnit::IsCharmed(), LuaCreature::IsCivilian(), LuaGlobalFunctions::IsCompatibilityMode(), LuaItem::IsConjuredConsumable(), LuaChatHandler::IsConsole(), LuaItem::IsCurrencyToken(), LuaQuest::IsDaily(), LuaUnit::IsDead(), LuaPlayer::IsDND(), LuaMap::IsDungeon(), LuaUnit::IsDying(), LuaCreature::IsElite(), LuaMap::IsEmpty(), LuaGlobalFunctions::IsEquipmentPos(), LuaItem::IsEquipped(), LuaPlayer::IsFalling(), LuaPlayer::IsFlying(), LuaGroup::IsFull(), LuaUnit::IsFullHealth(), LuaGlobalFunctions::IsGameEventActive(), LuaPlayer::IsGM(), LuaPlayer::IsGMChat(), LuaPlayer::IsGMVisible(), LuaUnit::IsGossip(), LuaPlayer::IsGroupVisibleFor(), LuaCreature::IsGuard(), LuaUnit::IsGuildMaster(), LuaMap::IsHeroic(), LuaPlayer::IsHonorOrXPTarget(), LuaPlayer::IsHorde(), LuaPlayer::IsImmuneToDamage(), LuaUnit::IsInAccessiblePlaceFor(), LuaPlayer::IsInArenaTeam(), LuaWorldObject::IsInBack(), LuaItem::IsInBag(), LuaUnit::IsInCombat(), LuaCreature::IsInEvadeMode(), LuaWorldObject::IsInFront(), LuaPlayer::IsInGroup(), LuaPlayer::IsInGuild(), LuaWorldObject::IsInMap(), LuaUnit::IsInnkeeper(), LuaWorldObject::IsInRange(), LuaWorldObject::IsInRange2d(), LuaWorldObject::IsInRange3d(), LuaPlayer::IsInSameGroupWith(), LuaPlayer::IsInSameRaidWith(), LuaItem::IsInTrade(), LuaGlobalFunctions::IsInventoryPos(), LuaPlayer::IsInWater(), LuaUnit::IsInWater(), LuaObject::IsInWorld(), LuaGroup::IsLeader(), LuaGroup::IsLFGGroup(), LuaItem::IsLocked(), LuaGroup::IsMember(), LuaUnit::IsMounted(), LuaPlayer::IsMoving(), LuaItem::IsNotBoundToPlayer(), LuaItem::IsNotEmptyBag(), LuaQuery::IsNull(), LuaVehicle::IsOnBoard(), LuaUnit::IsOnVehicle(), LuaObject::IsPlayer(), LuaItem::IsPotion(), LuaUnit::IsPvPFlagged(), LuaUnit::IsQuestGiver(), LuaCreature::IsRacialLeader(), LuaMap::IsRaid(), LuaGroup::IsRaidGroup(), LuaCreature::IsRegeneratingHealth(), LuaQuest::IsRepeatable(), LuaCreature::IsReputationGainDisabled(), LuaPlayer::IsRested(), LuaUnit::IsRooted(), LuaUnit::IsServiceProvider(), LuaItem::IsSoulBound(), LuaGameObject::IsSpawned(), LuaUnit::IsSpiritGuide(), LuaUnit::IsSpiritHealer(), LuaUnit::IsSpiritService(), LuaUnit::IsStandState(), LuaUnit::IsStopped(), LuaUnit::IsTabardDesigner(), LuaCreature::IsTappedBy(), LuaCreature::IsTargetableForAttack(), LuaUnit::IsTaxi(), LuaPlayer::IsTaxiCheater(), LuaUnit::IsTrainer(), LuaGameObject::IsTransport(), LuaUnit::IsUnderWater(), LuaUnit::IsVendor(), LuaPlayer::IsVisibleForPlayer(), LuaWorldObject::IsWithinDist(), LuaWorldObject::IsWithinDist2d(), LuaWorldObject::IsWithinDist3d(), LuaWorldObject::IsWithinDistInMap(), LuaWorldObject::IsWithinLoS(), LuaCreature::IsWorldBoss(), JustDied(), JustReachedHome(), JustRespawned(), JustSummoned(), KilledUnit(), ElunaTemplate< T >::Less(), ElunaTemplate< T >::LessOrEqual(), ElunaTemplate< T >::Mod(), MoveInLineOfSight(), MovementInform(), ElunaTemplate< T >::Multiply(), LuaQuery::NextRow(), On_Reset(), OnAchiComplete(), OnAdd(), OnAddMember(), OnAddMember(), OnAddonMessage(), OnAddPassenger(), OnAddToWorld(), OnAddToWorld(), OnAreaTrigger(), OnBankEvent(), OnBattlegroundDesertion(), OnBGCreate(), OnBGDestroy(), OnBGStart(), OnBindToInstance(), OnCanGroupInvite(), OnCanInitTrade(), OnCanJoinLfg(), OnCanSendMail(), OnCanUseItem(), OnChange(), OnChangeLeader(), OnChat(), OnChat(), OnChat(), OnChat(), OnChat(), OnCommand(), OnCreate(), OnCreate(), OnCreate(), OnCreate(), OnCreateItem(), OnCreatureCreate(), OnCreatureKill(), OnCreatureKilledByPet(), OnDamaged(), OnDelete(), OnDestroy(), OnDestroyed(), OnDisband(), OnDisband(), OnDuelEnd(), OnDuelRequest(), OnDuelStart(), OnDummyEffect(), OnDummyEffect(), OnDummyEffect(), OnEmote(), OnEquip(), OnEvent(), OnExpire(), OnExpire(), OnFfaPvpStateUpdate(), OnFirstLogin(), OnFreeTalentPointsChanged(), OnGameEventStart(), OnGameEventStop(), OnGameObjectCreate(), OnGameObjectStateChanged(), OnGameObjectUse(), OnGiveXP(), OnGossipHello(), OnGossipHello(), OnGossipSelect(), OnGossipSelect(), OnGossipSelectCode(), OnGossipSelectCode(), OnGroupRollRewardItem(), OnInfoChanged(), OnInstall(), OnInstallAccessory(), OnInviteMember(), OnItemGossip(), OnItemMove(), OnItemUse(), OnLearnSpell(), OnLearnTalents(), OnLevelChanged(), OnLogin(), OnLogout(), OnLootItem(), OnLootMoney(), OnLootStateChanged(), OnMapChanged(), OnMemberDepositMoney(), OnMemberWitdrawMoney(), OnMoneyChanged(), OnMOTDChanged(), OnOpenStateChange(), OnPacketReceiveAny(), OnPacketReceiveOne(), OnPacketSendAny(), OnPacketSendOne(), OnPetAddedToWorld(), OnPlayerCompleteQuest(), OnPlayerEnter(), OnPlayerEnterCombat(), OnPlayerEnterInstance(), OnPlayerKilledByCreature(), OnPlayerLeave(), OnPlayerLeaveCombat(), OnPVPKill(), OnQuestAbandon(), OnQuestAccept(), OnQuestAccept(), OnQuestAccept(), OnQuestReward(), OnQuestReward(), OnQuestRewardItem(), OnRemove(), OnRemove(), OnRemove(), OnRemove(), OnRemoveFromWorld(), OnRemoveFromWorld(), OnRemoveMember(), OnRemoveMember(), OnRemovePassenger(), OnRepop(), OnReputationChange(), OnResurrect(), OnSave(), OnShutdownInitiate(), OnSpawn(), OnSpellCast(), OnStoreNewItem(), OnSuccessful(), OnSummoned(), OnTalentsReset(), OnTextEmote(), OnTimedEvent(), OnUninstall(), OnUpdate(), OnUpdateArea(), OnUpdateInstance(), OnUpdateZone(), OnWorldUpdate(), LuaGlobalFunctions::PerformIngameSpawn(), ElunaTemplate< T >::Pow(), Push(), Push(), Push(), Push(), Push(), Push(), LuaPacket::ReadByte(), LuaPacket::ReadDouble(), LuaPacket::ReadFloat(), LuaPacket::ReadGUID(), LuaPacket::ReadLong(), LuaPacket::ReadShort(), LuaPacket::ReadString(), LuaPacket::ReadUByte(), LuaPacket::ReadULong(), LuaPacket::ReadUShort(), ReceiveEmote(), LuaWorldObject::RegisterEvent(), LuaGroup::RemoveMember(), ReplaceArgument(), LuaPlayer::ResetTalentsCost(), RunScripts(), LuaGroup::SameSubGroup(), LuaCreature::SelectVictim(), LuaGlobalFunctions::SendMail(), ElunaInstanceAI::SetData(), ElunaInstanceAI::SetData64(), LuaItem::SetEnchantment(), SetupStack(), LuaWorldObject::SpawnCreature(), SpellHit(), SpellHitTarget(), ElunaTemplate< T >::Substract(), SummonedCreatureDespawn(), LuaWorldObject::SummonGameObject(), LuaPlayer::Teleport(), LuaObject::ToCorpse(), LuaObject::ToCreature(), LuaObject::ToGameObject(), LuaObject::ToPlayer(), ElunaTemplate< T >::ToString(), LuaObject::ToUnit(), ElunaTemplate< T >::UnaryMinus(), UpdateAI(), UpdateAI(), and LuaGlobalFunctions::WorldDBQuery().
Push() [2/33]
void Eluna::Push (const bool value) inline private
{ Push(L, value); ++push_counter; }
References Push().
Referenced by Push().
Push() [3/33]
void Eluna::Push (const char * value) inline private
{ Push(L, value); ++push_counter; }
References Push().
Referenced by Push().
Push() [4/33]
void Eluna::Push (const double value) inline private
{ Push(L, value); ++push_counter; }
References Push().
Referenced by Push().
Push() [5/33]
void Eluna::Push (const float value) inline private
{ Push(L, value); ++push_counter; }
References Push().
Referenced by Push().
Push() [6/33]
void Eluna::Push (const int value) inline private
{ Push(L, value); ++push_counter; }
References Push().
Referenced by Push().
Push() [7/33]
void Eluna::Push (const long long value) inline private
{ Push(L, value); ++push_counter; }
References Push().
Referenced by Push().
Push() [8/33]
void Eluna::Push (const long value) inline private
{ Push(L, value); ++push_counter; }
References Push().
Referenced by Push().
Push() [9/33]
void Eluna::Push (const std::string & value) inline private
{ Push(L, value); ++push_counter; }
References Push().
Referenced by Push().
Push() [10/33]
void Eluna::Push (const unsigned int value) inline private
{ Push(L, value); ++push_counter; }
References Push().
Referenced by Push().
Push() [11/33]
void Eluna::Push (const unsigned long long value) inline private
{ Push(L, value); ++push_counter; }
References Push().
Referenced by Push().
Push() [12/33]
void Eluna::Push (const unsigned long value) inline private
{ Push(L, value); ++push_counter; }
References Push().
Referenced by Push().
Push() [13/33]
void Eluna::Push (lua_State * luastate) static
{
    lua_pushnil(luastate);
}
References lua_pushnil().
Push() [14/33]
void Eluna::Push (lua_State * luastate, const bool b) static
{
    lua_pushboolean(luastate, b);
}
References lua_pushboolean().
Push() [15/33]
void Eluna::Push (lua_State * luastate, const char * str) static
{
    lua_pushstring(luastate, str);
}
References lua_pushstring().
Push() [16/33]
void Eluna::Push (lua_State * luastate, const double d) static
{
    lua_pushnumber(luastate, d);
}
References lua_pushnumber().
Push() [17/33]
void Eluna::Push (lua_State * luastate, const float f) static
{
    lua_pushnumber(luastate, f);
}
References lua_pushnumber().
Push() [18/33]
void Eluna::Push (lua_State * luastate, const int i) static
{
    lua_pushinteger(luastate, i);
}
References lua_pushinteger().
Push() [19/33]
void Eluna::Push (lua_State * luastate, const long long l) static
{
    ElunaTemplate<long long>::Push(luastate, new long long(l));
}
References ElunaTemplate< T >::Push().
Push() [20/33]
void Eluna::Push (lua_State * luastate, const long l) static
{
    Push(luastate, static_cast<long long>(l));
}
References Push().
Push() [21/33]
void Eluna::Push (lua_State * luastate, const std::string & str) static
{
    lua_pushstring(luastate, str.c_str());
}
References lua_pushstring().
Push() [22/33]
void Eluna::Push (lua_State * luastate, const unsigned int u) static
{
    lua_pushunsigned(luastate, u);
}
References lua_pushunsigned().
Push() [23/33]
void Eluna::Push (lua_State * luastate, const unsigned long long l) static
{
    ElunaTemplate<unsigned long long>::Push(luastate, new unsigned long long(l));
}
References ElunaTemplate< T >::Push().
Push() [24/33]
void Eluna::Push (lua_State * luastate, const unsigned long l) static
{
    Push(luastate, static_cast<unsigned long long>(l));
}
References Push().
Push() [25/33]
void Eluna::Push (lua_State * luastate, Object const * obj) static
{
    if (!obj)
    {
        Push(luastate);
        return;
    }
    switch (obj->GetTypeId())
    {
        case TYPEID_UNIT:
            Push(luastate, obj->ToCreature());
            break;
        case TYPEID_PLAYER:
            Push(luastate, obj->ToPlayer());
            break;
        case TYPEID_GAMEOBJECT:
            Push(luastate, obj->ToGameObject());
            break;
        case TYPEID_CORPSE:
            Push(luastate, obj->ToCorpse());
            break;
        default:
            ElunaTemplate<Object>::Push(luastate, obj);
    }
}
References Object::GetTypeId(), Push(), ElunaTemplate< T >::Push(), Object::ToCorpse(), Object::ToCreature(), Object::ToGameObject(), Object::ToPlayer(), TYPEID_CORPSE, TYPEID_GAMEOBJECT, TYPEID_PLAYER, and TYPEID_UNIT.
Push() [26/33]
void Eluna::Push (lua_State * luastate, ObjectGuid const guid) static
{
    ElunaTemplate<unsigned long long>::Push(luastate, new unsigned long long(guid.GetRawValue()));
}
References ObjectGuid::GetRawValue(), and ElunaTemplate< T >::Push().
Push() [27/33]
void Eluna::Push (lua_State * luastate, Pet const * pet) static
{
    Push<Creature>(luastate, pet);
}
Push() [28/33]
template<typename T > static void Eluna::Push (lua_State * luastate, T const * ptr) inline static
    {
        ElunaTemplate<T>::Push(luastate, ptr);
    }
References ElunaTemplate< T >::Push().
Push() [29/33]
void Eluna::Push (lua_State * luastate, TempSummon const * summon) static
{
    Push<Creature>(luastate, summon);
}
Push() [30/33]
void Eluna::Push (lua_State * luastate, Unit const * unit) static
{
    if (!unit)
    {
        Push(luastate);
        return;
    }
    switch (unit->GetTypeId())
    {
        case TYPEID_UNIT:
            Push(luastate, unit->ToCreature());
            break;
        case TYPEID_PLAYER:
            Push(luastate, unit->ToPlayer());
            break;
        default:
            ElunaTemplate<Unit>::Push(luastate, unit);
    }
}
References Object::GetTypeId(), Push(), ElunaTemplate< T >::Push(), Object::ToCreature(), Object::ToPlayer(), TYPEID_PLAYER, and TYPEID_UNIT.
Push() [31/33]
void Eluna::Push (lua_State * luastate, WorldObject const * obj) static
{
    if (!obj)
    {
        Push(luastate);
        return;
    }
    switch (obj->GetTypeId())
    {
        case TYPEID_UNIT:
            Push(luastate, obj->ToCreature());
            break;
        case TYPEID_PLAYER:
            Push(luastate, obj->ToPlayer());
            break;
        case TYPEID_GAMEOBJECT:
            Push(luastate, obj->ToGameObject());
            break;
        case TYPEID_CORPSE:
            Push(luastate, obj->ToCorpse());
            break;
        default:
            ElunaTemplate<WorldObject>::Push(luastate, obj);
    }
}
References Object::GetTypeId(), Push(), ElunaTemplate< T >::Push(), Object::ToCorpse(), Object::ToCreature(), Object::ToGameObject(), Object::ToPlayer(), TYPEID_CORPSE, TYPEID_GAMEOBJECT, TYPEID_PLAYER, and TYPEID_UNIT.
Push() [32/33]
void Eluna::Push (ObjectGuid const value) inline private
{ Push(L, value); ++push_counter; }
References Push().
Referenced by Push().
Push() [33/33]
template<typename T > void Eluna::Push (T const * ptr) inline private
{ Push(L, ptr); ++push_counter; }
References Push().
Referenced by Push().
PushInstanceData()
void Eluna::PushInstanceData (lua_State * L, ElunaInstanceAI * ai, bool incrementCounter = true)
{
    // Check if the instance data is missing (i.e. someone reloaded Eluna).
    if (!HasInstanceData(ai->instance))
        ai->Reload();
    // Get the instance data table from the registry.
    if (!ai->instance->Instanceable())
        lua_rawgeti(L, LUA_REGISTRYINDEX, continentDataRefs[ai->instance->GetId()]);
    else
        lua_rawgeti(L, LUA_REGISTRYINDEX, instanceDataRefs[ai->instance->GetInstanceId()]);
    ASSERT(lua_istable(L, -1));
    if (incrementCounter)
        ++push_counter;
}
References ASSERT, continentDataRefs, HasInstanceData(), instanceDataRefs, L, lua_istable, lua_rawgeti(), LUA_REGISTRYINDEX, push_counter, and ElunaInstanceAI::Reload().
Referenced by LuaMap::GetInstanceData().
ReceiveEmote()
bool Eluna::ReceiveEmote (Creature * me, Player * player, uint32 emoteId)
{
    START_HOOK_WITH_RETVAL(CREATURE_EVENT_ON_RECEIVE_EMOTE, me, false);
    Push(me);
    Push(player);
    Push(emoteId);
    return CallAllFunctionsBool(CreatureEventBindings, CreatureUniqueBindings, entry_key, unique_key);
}
References CallAllFunctionsBool(), Hooks::CREATURE_EVENT_ON_RECEIVE_EMOTE, CreatureEventBindings, CreatureUniqueBindings, Push(), and START_HOOK_WITH_RETVAL.
Register()
int Eluna::Register (lua_State * L, uint8 reg, uint32 entry, ObjectGuid guid, uint32 instanceId, uint32 event_id, int functionRef, uint32 shots)
{
    uint64 bindingID;
    switch (regtype)
    {
        case Hooks::REGTYPE_SERVER:
            if (event_id < Hooks::SERVER_EVENT_COUNT)
            {
                auto key = EventKey<Hooks::ServerEvents>((Hooks::ServerEvents)event_id);
                bindingID = ServerEventBindings->Insert(key, functionRef, shots);
                createCancelCallback(L, bindingID, ServerEventBindings);
                return 1; // Stack: callback
            }
            break;
        case Hooks::REGTYPE_PLAYER:
            if (event_id < Hooks::PLAYER_EVENT_COUNT)
            {
                auto key = EventKey<Hooks::PlayerEvents>((Hooks::PlayerEvents)event_id);
                bindingID = PlayerEventBindings->Insert(key, functionRef, shots);
                createCancelCallback(L, bindingID, PlayerEventBindings);
                return 1; // Stack: callback
            }
            break;
        case Hooks::REGTYPE_GUILD:
            if (event_id < Hooks::GUILD_EVENT_COUNT)
            {
                auto key = EventKey<Hooks::GuildEvents>((Hooks::GuildEvents)event_id);
                bindingID = GuildEventBindings->Insert(key, functionRef, shots);
                createCancelCallback(L, bindingID, GuildEventBindings);
                return 1; // Stack: callback
            }
            break;
        case Hooks::REGTYPE_GROUP:
            if (event_id < Hooks::GROUP_EVENT_COUNT)
            {
                auto key = EventKey<Hooks::GroupEvents>((Hooks::GroupEvents)event_id);
                bindingID = GroupEventBindings->Insert(key, functionRef, shots);
                createCancelCallback(L, bindingID, GroupEventBindings);
                return 1; // Stack: callback
            }
            break;
        case Hooks::REGTYPE_VEHICLE:
            if (event_id < Hooks::VEHICLE_EVENT_COUNT)
            {
                auto key = EventKey<Hooks::VehicleEvents>((Hooks::VehicleEvents)event_id);
                bindingID = VehicleEventBindings->Insert(key, functionRef, shots);
                createCancelCallback(L, bindingID, VehicleEventBindings);
                return 1; // Stack: callback
            }
            break;
        case Hooks::REGTYPE_BG:
            if (event_id < Hooks::BG_EVENT_COUNT)
            {
                auto key = EventKey<Hooks::BGEvents>((Hooks::BGEvents)event_id);
                bindingID = BGEventBindings->Insert(key, functionRef, shots);
                createCancelCallback(L, bindingID, BGEventBindings);
                return 1; // Stack: callback
            }
            break;
        case Hooks::REGTYPE_PACKET:
            if (event_id < Hooks::PACKET_EVENT_COUNT)
            {
                if (entry >= NUM_MSG_TYPES)
                {
                    luaL_unref(L, LUA_REGISTRYINDEX, functionRef);
                    luaL_error(L, "Couldn't find a creature with (ID: %d)!", entry);
                    return 0; // Stack: (empty)
                }
                auto key = EntryKey<Hooks::PacketEvents>((Hooks::PacketEvents)event_id, entry);
                bindingID = PacketEventBindings->Insert(key, functionRef, shots);
                createCancelCallback(L, bindingID, PacketEventBindings);
                return 1; // Stack: callback
            }
            break;
        case Hooks::REGTYPE_CREATURE:
            if (event_id < Hooks::CREATURE_EVENT_COUNT)
            {
                if (entry != 0)
                {
                    if (!eObjectMgr->GetCreatureTemplate(entry))
                    {
                        luaL_unref(L, LUA_REGISTRYINDEX, functionRef);
                        luaL_error(L, "Couldn't find a creature with (ID: %d)!", entry);
                        return 0; // Stack: (empty)
                    }
                    auto key = EntryKey<Hooks::CreatureEvents>((Hooks::CreatureEvents)event_id, entry);
                    bindingID = CreatureEventBindings->Insert(key, functionRef, shots);
                    createCancelCallback(L, bindingID, CreatureEventBindings);
                }
                else
                {
                    if (guid.IsEmpty())
                    {
                        luaL_unref(L, LUA_REGISTRYINDEX, functionRef);
                        luaL_error(L, "guid was 0!");
                        return 0; // Stack: (empty)
                    }
                    auto key = UniqueObjectKey<Hooks::CreatureEvents>((Hooks::CreatureEvents)event_id, guid, instanceId);
                    bindingID = CreatureUniqueBindings->Insert(key, functionRef, shots);
                    createCancelCallback(L, bindingID, CreatureUniqueBindings);
                }
                return 1; // Stack: callback
            }
            break;
        case Hooks::REGTYPE_CREATURE_GOSSIP:
            if (event_id < Hooks::GOSSIP_EVENT_COUNT)
            {
                if (!eObjectMgr->GetCreatureTemplate(entry))
                {
                    luaL_unref(L, LUA_REGISTRYINDEX, functionRef);
                    luaL_error(L, "Couldn't find a creature with (ID: %d)!", entry);
                    return 0; // Stack: (empty)
                }
                auto key = EntryKey<Hooks::GossipEvents>((Hooks::GossipEvents)event_id, entry);
                bindingID = CreatureGossipBindings->Insert(key, functionRef, shots);
                createCancelCallback(L, bindingID, CreatureGossipBindings);
                return 1; // Stack: callback
            }
            break;
        case Hooks::REGTYPE_GAMEOBJECT:
            if (event_id < Hooks::GAMEOBJECT_EVENT_COUNT)
            {
                if (!eObjectMgr->GetGameObjectTemplate(entry))
                {
                    luaL_unref(L, LUA_REGISTRYINDEX, functionRef);
                    luaL_error(L, "Couldn't find a gameobject with (ID: %d)!", entry);
                    return 0; // Stack: (empty)
                }
                auto key = EntryKey<Hooks::GameObjectEvents>((Hooks::GameObjectEvents)event_id, entry);
                bindingID = GameObjectEventBindings->Insert(key, functionRef, shots);
                createCancelCallback(L, bindingID, GameObjectEventBindings);
                return 1; // Stack: callback
            }
            break;
        case Hooks::REGTYPE_GAMEOBJECT_GOSSIP:
            if (event_id < Hooks::GOSSIP_EVENT_COUNT)
            {
                if (!eObjectMgr->GetGameObjectTemplate(entry))
                {
                    luaL_unref(L, LUA_REGISTRYINDEX, functionRef);
                    luaL_error(L, "Couldn't find a gameobject with (ID: %d)!", entry);
                    return 0; // Stack: (empty)
                }
                auto key = EntryKey<Hooks::GossipEvents>((Hooks::GossipEvents)event_id, entry);
                bindingID = GameObjectGossipBindings->Insert(key, functionRef, shots);
                createCancelCallback(L, bindingID, GameObjectGossipBindings);
                return 1; // Stack: callback
            }
            break;
        case Hooks::REGTYPE_ITEM:
            if (event_id < Hooks::ITEM_EVENT_COUNT)
            {
                if (!eObjectMgr->GetItemTemplate(entry))
                {
                    luaL_unref(L, LUA_REGISTRYINDEX, functionRef);
                    luaL_error(L, "Couldn't find a item with (ID: %d)!", entry);
                    return 0; // Stack: (empty)
                }
                auto key = EntryKey<Hooks::ItemEvents>((Hooks::ItemEvents)event_id, entry);
                bindingID = ItemEventBindings->Insert(key, functionRef, shots);
                createCancelCallback(L, bindingID, ItemEventBindings);
                return 1; // Stack: callback
            }
            break;
        case Hooks::REGTYPE_ITEM_GOSSIP:
            if (event_id < Hooks::GOSSIP_EVENT_COUNT)
            {
                if (!eObjectMgr->GetItemTemplate(entry))
                {
                    luaL_unref(L, LUA_REGISTRYINDEX, functionRef);
                    luaL_error(L, "Couldn't find a item with (ID: %d)!", entry);
                    return 0; // Stack: (empty)
                }
                auto key = EntryKey<Hooks::GossipEvents>((Hooks::GossipEvents)event_id, entry);
                bindingID = ItemGossipBindings->Insert(key, functionRef, shots);
                createCancelCallback(L, bindingID, ItemGossipBindings);
                return 1; // Stack: callback
            }
            break;
        case Hooks::REGTYPE_PLAYER_GOSSIP:
            if (event_id < Hooks::GOSSIP_EVENT_COUNT)
            {
                auto key = EntryKey<Hooks::GossipEvents>((Hooks::GossipEvents)event_id, entry);
                bindingID = PlayerGossipBindings->Insert(key, functionRef, shots);
                createCancelCallback(L, bindingID, PlayerGossipBindings);
                return 1; // Stack: callback
            }
            break;
        case Hooks::REGTYPE_MAP:
            if (event_id < Hooks::INSTANCE_EVENT_COUNT)
            {
                auto key = EntryKey<Hooks::InstanceEvents>((Hooks::InstanceEvents)event_id, entry);
                bindingID = MapEventBindings->Insert(key, functionRef, shots);
                createCancelCallback(L, bindingID, MapEventBindings);
                return 1; // Stack: callback
            }
            break;
        case Hooks::REGTYPE_INSTANCE:
            if (event_id < Hooks::INSTANCE_EVENT_COUNT)
            {
                auto key = EntryKey<Hooks::InstanceEvents>((Hooks::InstanceEvents)event_id, entry);
                bindingID = InstanceEventBindings->Insert(key, functionRef, shots);
                createCancelCallback(L, bindingID, InstanceEventBindings);
                return 1; // Stack: callback
            }
            break;
    }
    luaL_unref(L, LUA_REGISTRYINDEX, functionRef);
    std::ostringstream oss;
    oss << "regtype " << static_cast<uint32>(regtype) << ", event " << event_id << ", entry " << entry << ", guid " << guid.GetRawValue() << ", instance " << instanceId;
    luaL_error(L, "Unknown event type (%s)", oss.str().c_str());
    return 0;
}
References Hooks::BG_EVENT_COUNT, BGEventBindings, createCancelCallback(), Hooks::CREATURE_EVENT_COUNT, CreatureEventBindings, CreatureGossipBindings, CreatureUniqueBindings, eObjectMgr, Hooks::GAMEOBJECT_EVENT_COUNT, GameObjectEventBindings, GameObjectGossipBindings, ObjectGuid::GetRawValue(), Hooks::GOSSIP_EVENT_COUNT, Hooks::GROUP_EVENT_COUNT, GroupEventBindings, Hooks::GUILD_EVENT_COUNT, GuildEventBindings, BindingMap< K >::Insert(), Hooks::INSTANCE_EVENT_COUNT, InstanceEventBindings, ObjectGuid::IsEmpty(), Hooks::ITEM_EVENT_COUNT, ItemEventBindings, ItemGossipBindings, L, LUA_REGISTRYINDEX, luaL_error(), luaL_unref(), MapEventBindings, NUM_MSG_TYPES, Hooks::PACKET_EVENT_COUNT, PacketEventBindings, Hooks::PLAYER_EVENT_COUNT, PlayerEventBindings, PlayerGossipBindings, Hooks::REGTYPE_BG, Hooks::REGTYPE_CREATURE, Hooks::REGTYPE_CREATURE_GOSSIP, Hooks::REGTYPE_GAMEOBJECT, Hooks::REGTYPE_GAMEOBJECT_GOSSIP, Hooks::REGTYPE_GROUP, Hooks::REGTYPE_GUILD, Hooks::REGTYPE_INSTANCE, Hooks::REGTYPE_ITEM, Hooks::REGTYPE_ITEM_GOSSIP, Hooks::REGTYPE_MAP, Hooks::REGTYPE_PACKET, Hooks::REGTYPE_PLAYER, Hooks::REGTYPE_PLAYER_GOSSIP, Hooks::REGTYPE_SERVER, Hooks::REGTYPE_VEHICLE, Hooks::SERVER_EVENT_COUNT, ServerEventBindings, Hooks::VEHICLE_EVENT_COUNT, and VehicleEventBindings.
Referenced by LuaGlobalFunctions::RegisterEntryHelper(), LuaGlobalFunctions::RegisterEventHelper(), and LuaGlobalFunctions::RegisterUniqueHelper().
ReloadEluna()
static void Eluna::ReloadEluna () inline static
{ LOCK_ELUNA; reload = true; }
References LOCK_ELUNA.
Referenced by OnCommand(), and LuaGlobalFunctions::ReloadEluna().
ReplaceArgument()
template<typename T > void Eluna::ReplaceArgument (T value, uint8 index) private
{
    ASSERT(index < lua_gettop(L) && index > 0);
    // Stack: event_id, [arguments], [functions], [results]
    Eluna::Push(L, value);
    // Stack: event_id, [arguments], [functions], [results], value
    lua_replace(L, index + 1);
    // Stack: event_id, [arguments and value], [functions], [results]
}
References ASSERT, L, lua_gettop(), lua_replace(), and Push().
Referenced by CorpseRemoved(), DamageTaken(), OnGiveXP(), OnMemberDepositMoney(), OnMemberWitdrawMoney(), OnMoneyChanged(), and OnReputationChange().
Report()
void Eluna::Report (lua_State * _L) static private
{
    const char* msg = lua_tostring(_L, -1);
    ELUNA_LOG_ERROR("{}", msg);
    lua_pop(_L, 1);
}
References ELUNA_LOG_ERROR, lua_pop, and lua_tostring.
Referenced by ExecuteCall(), and RunScripts().
RunScripts()
void Eluna::RunScripts ()
{
    LOCK_ELUNA;
    if (!IsEnabled())
        return;
    uint32 oldMSTime = ElunaUtil::GetCurrTime();
    uint32 count = 0;
    ScriptList scripts;
    lua_extensions.sort(ScriptPathComparator);
    lua_scripts.sort(ScriptPathComparator);
    scripts.insert(scripts.end(), lua_extensions.begin(), lua_extensions.end());
    scripts.insert(scripts.end(), lua_scripts.begin(), lua_scripts.end());
    std::unordered_map<std::string, std::string> loaded; // filename, path
    lua_getglobal(L, "package");
    // Stack: package
    luaL_getsubtable(L, -1, "loaded");
    // Stack: package, modules
    int modules = lua_gettop(L);
    for (ScriptList::const_iterator it = scripts.begin(); it != scripts.end(); ++it)
    {
        // Check that no duplicate names exist
        if (loaded.find(it->filename) != loaded.end())
        {
            ELUNA_LOG_ERROR("[Eluna]: Error loading `{}`. File with same name already loaded from `{}`, rename either file", it->filepath, loaded[it->filename]);
            continue;
        }
        loaded[it->filename] = it->filepath;
        lua_getfield(L, modules, it->filename.c_str());
        // Stack: package, modules, module
        if (!lua_isnoneornil(L, -1))
        {
            lua_pop(L, 1);
            ELUNA_LOG_DEBUG("[Eluna]: `{}` was already loaded or required", it->filepath);
            continue;
        }
        lua_pop(L, 1);
        // Stack: package, modules
        if (luaL_loadfile(L, it->filepath.c_str()))
        {
            // Stack: package, modules, errmsg
            ELUNA_LOG_ERROR("[Eluna]: Error loading `{}`", it->filepath);
            Report(L);
            // Stack: package, modules
            continue;
        }
        // Stack: package, modules, filefunc
        if (ExecuteCall(0, 1))
        {
            // Stack: package, modules, result
            if (lua_isnoneornil(L, -1) || (lua_isboolean(L, -1) && !lua_toboolean(L, -1)))
            {
                // if result evaluates to false, change it to true
                lua_pop(L, 1);
                Push(L, true);
            }
            lua_setfield(L, modules, it->filename.c_str());
            // Stack: package, modules
            // successfully loaded and ran file
            ELUNA_LOG_DEBUG("[Eluna]: Successfully loaded `{}`", it->filepath);
            ++count;
            continue;
        }
    }
    // Stack: package, modules
    lua_pop(L, 2);
    ELUNA_LOG_INFO("[Eluna]: Executed {} Lua scripts in {} ms", count, ElunaUtil::GetTimeDiff(oldMSTime));
    OnLuaStateOpen();
}
References ELUNA_LOG_DEBUG, ELUNA_LOG_ERROR, ELUNA_LOG_INFO, ExecuteCall(), ElunaUtil::GetCurrTime(), ElunaUtil::GetTimeDiff(), IsEnabled(), L, LOCK_ELUNA, lua_extensions, lua_getfield(), lua_getglobal(), lua_gettop(), lua_isboolean, lua_isnoneornil, lua_pop, lua_scripts, lua_setfield(), lua_toboolean(), luaL_getsubtable(), luaL_loadfile, OnLuaStateOpen(), Push(), Report(), and ScriptPathComparator().
SetupStack() [1/2]
template<typename K > int Eluna::SetupStack (BindingMap< K > * bindings, const K & key, int number_of_arguments) inline private
    {
        return SetupStack<K, K>(bindings, NULL, key, key, number_of_arguments);
    }
SetupStack() [2/2]
template<typename K1 , typename K2 > int Eluna::SetupStack (BindingMap< K1 > * bindings1, BindingMap< K2 > * bindings2, const K1 & key1, const K2 & key2, int number_of_arguments) private
{
    ASSERT(number_of_arguments == this->push_counter);
    ASSERT(key1.event_id == key2.event_id);
    // Stack: [arguments]
    Push(key1.event_id);
    this->push_counter = 0;
    ++number_of_arguments;
    // Stack: [arguments], event_id
    int arguments_top = lua_gettop(L);
    int first_argument_index = arguments_top - number_of_arguments + 1;
    ASSERT(arguments_top >= number_of_arguments);
    lua_insert(L, first_argument_index);
    // Stack: event_id, [arguments]
    bindings1->PushRefsFor(key1);
    if (bindings2)
        bindings2->PushRefsFor(key2);
    // Stack: event_id, [arguments], [functions]
    int number_of_functions = lua_gettop(L) - arguments_top;
    return number_of_functions;
}
References ASSERT, L, lua_gettop(), lua_insert(), Push(), push_counter, and BindingMap< K >::PushRefsFor().
Referenced by CallAllFunctions(), CallAllFunctionsBool(), CorpseRemoved(), DamageTaken(), OnCanUseItem(), OnChat(), OnChat(), OnChat(), OnChat(), OnChat(), OnGiveXP(), OnMemberDepositMoney(), OnMemberWitdrawMoney(), OnMoneyChanged(), OnPacketReceiveAny(), OnPacketReceiveOne(), OnPacketSendAny(), OnPacketSendOne(), and OnReputationChange().
ShouldReload()
bool Eluna::ShouldReload () const inline
{ return reload; }
Referenced by OnWorldUpdate().
SpellHit()
bool Eluna::SpellHit (Creature * me, WorldObject * caster, SpellInfo const * spell)
{
    START_HOOK_WITH_RETVAL(CREATURE_EVENT_ON_HIT_BY_SPELL, me, false);
    Push(me);
    Push(caster);
    Push(spell->Id); // Pass spell object?
    return CallAllFunctionsBool(CreatureEventBindings, CreatureUniqueBindings, entry_key, unique_key);
}
References CallAllFunctionsBool(), Hooks::CREATURE_EVENT_ON_HIT_BY_SPELL, CreatureEventBindings, CreatureUniqueBindings, SpellEntry::Id, Push(), and START_HOOK_WITH_RETVAL.
SpellHitTarget()
bool Eluna::SpellHitTarget (Creature * me, WorldObject * target, SpellInfo const * spell)
{
    START_HOOK_WITH_RETVAL(CREATURE_EVENT_ON_SPELL_HIT_TARGET, me, false);
    Push(me);
    Push(target);
    Push(spell->Id); // Pass spell object?
    return CallAllFunctionsBool(CreatureEventBindings, CreatureUniqueBindings, entry_key, unique_key);
}
References CallAllFunctionsBool(), Hooks::CREATURE_EVENT_ON_SPELL_HIT_TARGET, CreatureEventBindings, CreatureUniqueBindings, SpellEntry::Id, Push(), and START_HOOK_WITH_RETVAL.
StackTrace()
int Eluna::StackTrace (lua_State * _L) static private
{
    // Stack: errmsg
    if (!lua_isstring(_L, -1))  /* 'message' not a string? */
        return 1;  /* keep it intact */
    // Stack: errmsg, debug
    lua_getglobal(_L, "debug");
    if (!lua_istable(_L, -1))
    {
        lua_pop(_L, 1);
        return 1;
    }
    // Stack: errmsg, debug, traceback
    lua_getfield(_L, -1, "traceback");
    if (!lua_isfunction(_L, -1))
    {
        lua_pop(_L, 2);
        return 1;
    }
    lua_pushvalue(_L, -3);  /* pass error message */
    lua_pushinteger(_L, 1);  /* skip this function and traceback */
    // Stack: errmsg, debug, traceback, errmsg, 2
    lua_call(_L, 2, 1);  /* call debug.traceback */
    // dirty stack?
    // Stack: errmsg, debug, tracemsg
    sEluna->OnError(std::string(lua_tostring(_L, -1)));
    return 1;
}
References lua_call, lua_getfield(), lua_getglobal(), lua_isfunction, lua_isstring(), lua_istable, lua_pop, lua_pushinteger(), lua_pushvalue(), lua_tostring, and sEluna.
Referenced by ExecuteCall().
SummonedCreatureDespawn()
bool Eluna::SummonedCreatureDespawn (Creature * me, Creature * summon)
{
    START_HOOK_WITH_RETVAL(CREATURE_EVENT_ON_SUMMONED_CREATURE_DESPAWN, me, false);
    Push(me);
    Push(summon);
    return CallAllFunctionsBool(CreatureEventBindings, CreatureUniqueBindings, entry_key, unique_key);
}
References CallAllFunctionsBool(), Hooks::CREATURE_EVENT_ON_SUMMONED_CREATURE_DESPAWN, CreatureEventBindings, CreatureUniqueBindings, Push(), and START_HOOK_WITH_RETVAL.
SummonedCreatureDies()
bool Eluna::SummonedCreatureDies (Creature * me, Creature * summon, Unit * killer)
Uninitialize()
void Eluna::Uninitialize () static
{
    LOCK_ELUNA;
    ASSERT(IsInitialized());
    delete GEluna;
    GEluna = NULL;
    lua_scripts.clear();
    lua_extensions.clear();
    initialized = false;
}
References ASSERT, GEluna, initialized, IsInitialized(), LOCK_ELUNA, lua_extensions, and lua_scripts.
Referenced by Eluna_WorldScript::OnAfterUnloadAllMaps().
UpdateAI() [1/2]
bool Eluna::UpdateAI (Creature * me, const uint32 diff)
{
    START_HOOK_WITH_RETVAL(CREATURE_EVENT_ON_AIUPDATE, me, false);
    Push(me);
    Push(diff);
    return CallAllFunctionsBool(CreatureEventBindings, CreatureUniqueBindings, entry_key, unique_key);
}
References CallAllFunctionsBool(), Hooks::CREATURE_EVENT_ON_AIUPDATE, CreatureEventBindings, CreatureUniqueBindings, Push(), and START_HOOK_WITH_RETVAL.
UpdateAI() [2/2]
void Eluna::UpdateAI (GameObject * pGameObject, uint32 diff)
{
    pGameObject->elunaEvents->Update(diff);
    START_HOOK(GAMEOBJECT_EVENT_ON_AIUPDATE, pGameObject->GetEntry());
    Push(pGameObject);
    Push(diff);
    CallAllFunctions(GameObjectEventBindings, key);
}
References CallAllFunctions(), WorldObject::elunaEvents, Hooks::GAMEOBJECT_EVENT_ON_AIUPDATE, GameObjectEventBindings, Object::GetEntry(), Push(), START_HOOK, and ElunaEventProcessor::Update().
Member Data Documentation
BGEventBindings
BindingMap< EventKey<Hooks::BGEvents> >* Eluna::BGEventBindings
Referenced by LuaGlobalFunctions::ClearBattleGroundEvents(), CreateBindStores(), DestroyBindStores(), OnBGCreate(), OnBGDestroy(), OnBGStart(), and Register().
callstackid
uint64 Eluna::callstackid = 2 private
Referenced by InvalidateObjects().
continentDataRefs
std::unordered_map<uint32, int> Eluna::continentDataRefs private
Referenced by CloseLua(), CreateInstanceData(), HasInstanceData(), and PushInstanceData().
CreatureEventBindings
BindingMap< EntryKey<Hooks::CreatureEvents> >* Eluna::CreatureEventBindings
Referenced by AttackStart(), LuaGlobalFunctions::ClearCreatureEvents(), CorpseRemoved(), CreateBindStores(), DamageTaken(), DestroyBindStores(), EnterCombat(), EnterEvadeMode(), GetAI(), GetDialogStatus(), JustDied(), JustReachedHome(), JustRespawned(), JustSummoned(), KilledUnit(), MoveInLineOfSight(), MovementInform(), On_Reset(), OnAddToWorld(), OnDummyEffect(), OnQuestAccept(), OnQuestReward(), OnRemoveFromWorld(), OnSummoned(), ReceiveEmote(), Register(), SpellHit(), SpellHitTarget(), SummonedCreatureDespawn(), and UpdateAI().
CreatureGossipBindings
BindingMap< EntryKey<Hooks::GossipEvents> >* Eluna::CreatureGossipBindings
Referenced by LuaGlobalFunctions::ClearCreatureGossipEvents(), CreateBindStores(), DestroyBindStores(), OnGossipHello(), OnGossipSelect(), OnGossipSelectCode(), and Register().
CreatureUniqueBindings
BindingMap< UniqueObjectKey<Hooks::CreatureEvents> >* Eluna::CreatureUniqueBindings
Referenced by AttackStart(), LuaGlobalFunctions::ClearUniqueCreatureEvents(), CorpseRemoved(), CreateBindStores(), DamageTaken(), DestroyBindStores(), EnterCombat(), EnterEvadeMode(), GetAI(), GetDialogStatus(), JustDied(), JustReachedHome(), JustRespawned(), JustSummoned(), KilledUnit(), MoveInLineOfSight(), MovementInform(), On_Reset(), OnAddToWorld(), OnDummyEffect(), OnQuestAccept(), OnQuestReward(), OnRemoveFromWorld(), OnSummoned(), ReceiveEmote(), Register(), SpellHit(), SpellHitTarget(), SummonedCreatureDespawn(), and UpdateAI().
enabled
bool Eluna::enabled private
Referenced by OpenLua().
event_level
uint32 Eluna::event_level private
Referenced by CleanUpStack(), ExecuteCall(), and OnTimedEvent().
eventMgr
EventMgr* Eluna::eventMgr
Referenced by LuaGlobalFunctions::CreateLuaEvent(), Eluna(), OnWorldUpdate(), LuaGlobalFunctions::RemoveEventById(), LuaGlobalFunctions::RemoveEvents(), and ~Eluna().
GameObjectEventBindings
BindingMap< EntryKey<Hooks::GameObjectEvents> >* Eluna::GameObjectEventBindings
Referenced by LuaGlobalFunctions::ClearGameObjectEvents(), CreateBindStores(), DestroyBindStores(), GetDialogStatus(), OnAddToWorld(), OnDamaged(), OnDestroyed(), OnDummyEffect(), OnGameObjectStateChanged(), OnGameObjectUse(), OnLootStateChanged(), OnQuestAccept(), OnQuestReward(), OnRemoveFromWorld(), OnSpawn(), Register(), and UpdateAI().
GameObjectGossipBindings
BindingMap< EntryKey<Hooks::GossipEvents> >* Eluna::GameObjectGossipBindings
Referenced by LuaGlobalFunctions::ClearGameObjectGossipEvents(), CreateBindStores(), DestroyBindStores(), OnGossipHello(), OnGossipSelect(), OnGossipSelectCode(), and Register().
GEluna
Eluna * Eluna::GEluna = NULL static
Referenced by LuaGlobalFunctions::DBQueryAsync(), Eluna(), HttpManager::HandleHttpResponses(), LuaGlobalFunctions::HttpRequest(), Initialize(), Eluna_WorldObjectScript::OnWorldObjectSetMap(), and Uninitialize().
GroupEventBindings
BindingMap< EventKey<Hooks::GroupEvents> >* Eluna::GroupEventBindings
Referenced by LuaGlobalFunctions::ClearGroupEvents(), CreateBindStores(), DestroyBindStores(), OnAddMember(), OnChangeLeader(), OnCreate(), OnDisband(), OnInviteMember(), OnRemoveMember(), and Register().
GuildEventBindings
BindingMap< EventKey<Hooks::GuildEvents> >* Eluna::GuildEventBindings
Referenced by LuaGlobalFunctions::ClearGuildEvents(), CreateBindStores(), DestroyBindStores(), OnAddMember(), OnBankEvent(), OnCreate(), OnDisband(), OnEvent(), OnInfoChanged(), OnItemMove(), OnMemberDepositMoney(), OnMemberWitdrawMoney(), OnMOTDChanged(), OnRemoveMember(), and Register().
httpManager
HttpManager Eluna::httpManager
Referenced by LuaGlobalFunctions::HttpRequest(), and OnWorldUpdate().
initialized
bool Eluna::initialized = false static private
Referenced by Initialize(), and Uninitialize().
instanceDataRefs
std::unordered_map<uint32, int> Eluna::instanceDataRefs private
Referenced by CloseLua(), CreateInstanceData(), FreeInstanceId(), HasInstanceData(), and PushInstanceData().
InstanceEventBindings
BindingMap< EntryKey<Hooks::InstanceEvents> >* Eluna::InstanceEventBindings
Referenced by LuaGlobalFunctions::ClearInstanceEvents(), CreateBindStores(), DestroyBindStores(), FreeInstanceId(), GetInstanceData(), OnCheckEncounterInProgress(), OnCreatureCreate(), OnGameObjectCreate(), OnInitialize(), OnLoad(), OnPlayerEnterInstance(), OnUpdateInstance(), and Register().
ItemEventBindings
BindingMap< EntryKey<Hooks::ItemEvents> >* Eluna::ItemEventBindings
Referenced by LuaGlobalFunctions::ClearItemEvents(), CreateBindStores(), DestroyBindStores(), OnDummyEffect(), OnExpire(), OnItemUse(), OnQuestAccept(), OnRemove(), and Register().
ItemGossipBindings
BindingMap< EntryKey<Hooks::GossipEvents> >* Eluna::ItemGossipBindings
Referenced by LuaGlobalFunctions::ClearItemGossipEvents(), CreateBindStores(), DestroyBindStores(), HandleGossipSelectOption(), OnItemGossip(), and Register().
L
lua_State* Eluna::L
Referenced by CallAllFunctionsBool(), CallOneFunction(), CleanUpStack(), CloseLua(), CorpseRemoved(), CreateBindStores(), CreateInstanceData(), DamageTaken(), ExecuteCall(), FreeInstanceId(), HttpManager::HandleHttpResponses(), OnCanJoinLfg(), OnCanUseItem(), OnChat(), OnChat(), OnChat(), OnChat(), OnChat(), OnGiveXP(), OnMemberDepositMoney(), OnMemberWitdrawMoney(), OnMoneyChanged(), OnPacketReceiveAny(), OnPacketReceiveOne(), OnPacketSendAny(), OnPacketSendOne(), OnReputationChange(), OnTimedEvent(), OpenLua(), PushInstanceData(), ElunaTemplate< T >::Register(), Register(), ReplaceArgument(), RunScripts(), ElunaTemplate< T >::SetMethods(), ElunaGlobal::SetMethods(), and SetupStack().
lock
Eluna::LockType Eluna::lock static private
lua_extensions
Eluna::ScriptList Eluna::lua_extensions static private
Referenced by AddScriptPath(), LoadScriptPaths(), RunScripts(), and Uninitialize().
lua_folderpath
std::string Eluna::lua_folderpath static private
Referenced by LoadScriptPaths().
lua_requirepath
std::string Eluna::lua_requirepath static private
Referenced by GetScripts(), LoadScriptPaths(), and OpenLua().
lua_scripts
Eluna::ScriptList Eluna::lua_scripts static private
Referenced by AddScriptPath(), LoadScriptPaths(), RunScripts(), and Uninitialize().
MapEventBindings
BindingMap< EntryKey<Hooks::InstanceEvents> >* Eluna::MapEventBindings
Referenced by LuaGlobalFunctions::ClearMapEvents(), CreateBindStores(), DestroyBindStores(), FreeInstanceId(), GetInstanceData(), OnCheckEncounterInProgress(), OnCreatureCreate(), OnGameObjectCreate(), OnInitialize(), OnLoad(), OnPlayerEnterInstance(), OnUpdateInstance(), and Register().
OnError
EventEmitter<void(std::string)> Eluna::OnError
PacketEventBindings
BindingMap< EntryKey<Hooks::PacketEvents> >* Eluna::PacketEventBindings
Referenced by LuaGlobalFunctions::ClearPacketEvents(), CreateBindStores(), DestroyBindStores(), OnPacketReceiveOne(), OnPacketSendOne(), and Register().
PlayerEventBindings
BindingMap< EventKey<Hooks::PlayerEvents> >* Eluna::PlayerEventBindings
Referenced by LuaGlobalFunctions::ClearPlayerEvents(), CreateBindStores(), DestroyBindStores(), OnAchiComplete(), OnBattlegroundDesertion(), OnBindToInstance(), OnCanGroupInvite(), OnCanInitTrade(), OnCanJoinLfg(), OnCanSendMail(), OnCanUseItem(), OnChat(), OnChat(), OnChat(), OnChat(), OnChat(), OnCommand(), OnCreate(), OnCreateItem(), OnCreatureKill(), OnCreatureKilledByPet(), OnDelete(), OnDuelEnd(), OnDuelRequest(), OnDuelStart(), OnEmote(), OnEquip(), OnFfaPvpStateUpdate(), OnFirstLogin(), OnFreeTalentPointsChanged(), OnGiveXP(), OnGroupRollRewardItem(), OnLearnSpell(), OnLearnTalents(), OnLevelChanged(), OnLogin(), OnLogout(), OnLootItem(), OnLootMoney(), OnMapChanged(), OnMoneyChanged(), OnPetAddedToWorld(), OnPlayerCompleteQuest(), OnPlayerEnterCombat(), OnPlayerKilledByCreature(), OnPlayerLeaveCombat(), OnPVPKill(), OnQuestAbandon(), OnQuestRewardItem(), OnRepop(), OnReputationChange(), OnResurrect(), OnSave(), OnSpellCast(), OnStoreNewItem(), OnTalentsReset(), OnTextEmote(), OnUpdateArea(), OnUpdateZone(), and Register().
PlayerGossipBindings
BindingMap< EntryKey<Hooks::GossipEvents> >* Eluna::PlayerGossipBindings
Referenced by LuaGlobalFunctions::ClearPlayerGossipEvents(), CreateBindStores(), DestroyBindStores(), HandleGossipSelectOption(), and Register().
push_counter
uint8 Eluna::push_counter private
Referenced by CallAllFunctions(), CallAllFunctionsBool(), OnCanJoinLfg(), PushInstanceData(), and SetupStack().
queryProcessor
QueryCallbackProcessor Eluna::queryProcessor
Referenced by LuaGlobalFunctions::DBQueryAsync(), and OnWorldUpdate().
reload
bool Eluna::reload = false static private
Referenced by _ReloadEluna(), and OnCommand().
ServerEventBindings
BindingMap< EventKey<Hooks::ServerEvents> >* Eluna::ServerEventBindings
Referenced by LuaGlobalFunctions::ClearServerEvents(), CreateBindStores(), DestroyBindStores(), OnAdd(), OnAddonMessage(), OnAreaTrigger(), OnChange(), OnCreate(), OnDestroy(), OnExpire(), OnGameEventStart(), OnGameEventStop(), OnLuaStateClose(), OnLuaStateOpen(), OnOpenStateChange(), OnPacketReceiveAny(), OnPacketSendAny(), OnPlayerEnter(), OnPlayerLeave(), OnRemove(), OnRemove(), OnRemove(), OnShutdown(), OnShutdownCancel(), OnShutdownInitiate(), OnStartup(), OnSuccessful(), OnUpdate(), OnWorldUpdate(), and Register().
VehicleEventBindings
BindingMap< EventKey<Hooks::VehicleEvents> >* Eluna::VehicleEventBindings
Referenced by CreateBindStores(), DestroyBindStores(), OnAddPassenger(), OnInstall(), OnInstallAccessory(), OnRemovePassenger(), OnUninstall(), and Register().
The documentation for this class was generated from the following files:
mod-eluna/src/LuaEngine/LuaEngine.h
mod-eluna/src/LuaEngine/BattleGroundHooks.cpp
mod-eluna/src/LuaEngine/CreatureHooks.cpp
mod-eluna/src/LuaEngine/GameObjectHooks.cpp
mod-eluna/src/LuaEngine/GossipHooks.cpp
mod-eluna/src/LuaEngine/GroupHooks.cpp
mod-eluna/src/LuaEngine/GuildHooks.cpp
mod-eluna/src/LuaEngine/HookHelpers.h
mod-eluna/src/LuaEngine/InstanceHooks.cpp
mod-eluna/src/LuaEngine/ItemHooks.cpp
mod-eluna/src/LuaEngine/LuaEngine.cpp
mod-eluna/src/LuaEngine/PacketHooks.cpp
mod-eluna/src/LuaEngine/PlayerHooks.cpp
mod-eluna/src/LuaEngine/ServerHooks.cpp
mod-eluna/src/LuaEngine/VehicleHooks.cpp