AzerothCore Doxygen
ElunaInstanceAI Class Reference
#include "ElunaInstanceAI.h"
Public Member Functions
ElunaInstanceAI (Map *map)
void Initialize () override
void Load (const char *data) override
const char * Save () const override
void Reload ()
uint32 GetData (uint32 key) const override
void SetData (uint32 key, uint32 value) override
uint64 GetData64 (uint32 key) const override
void SetData64 (uint32 key, uint64 value) override
void Update (uint32 diff) override
bool IsEncounterInProgress () const override
void OnPlayerEnter (Player *player) override
void OnObjectCreate (GameObject *gameobject) override
void OnCreatureCreate (Creature *creature) override
Private Attributes
std::string lastSaveData
Detailed Description
Constructor & Destructor Documentation
ElunaInstanceAI()
ElunaInstanceAI::ElunaInstanceAI (Map * map) inline
                              : InstanceData(map)
    {
    }
Member Function Documentation
GetData()
uint32 ElunaInstanceAI::GetData (uint32 key) const override
{
    LOCK_ELUNA;
    lua_State* L = sEluna->L;
    // Stack: (empty)
    sEluna->PushInstanceData(L, const_cast<ElunaInstanceAI*>(this), false);
    // Stack: instance_data
    Eluna::Push(L, key);
    // Stack: instance_data, key
    lua_gettable(L, -2);
    // Stack: instance_data, value
    uint32 value = Eluna::CHECKVAL<uint32>(L, -1, 0);
    lua_pop(L, 2);
    // Stack: (empty)
    return value;
}
References LOCK_ELUNA, lua_gettable(), lua_pop, Eluna::Push(), and sEluna.
GetData64()
uint64 ElunaInstanceAI::GetData64 (uint32 key) const override
{
    LOCK_ELUNA;
    lua_State* L = sEluna->L;
    // Stack: (empty)
    sEluna->PushInstanceData(L, const_cast<ElunaInstanceAI*>(this), false);
    // Stack: instance_data
    Eluna::Push(L, key);
    // Stack: instance_data, key
    lua_gettable(L, -2);
    // Stack: instance_data, value
    uint64 value = Eluna::CHECKVAL<uint64>(L, -1, 0);
    lua_pop(L, 2);
    // Stack: (empty)
    return value;
}
References LOCK_ELUNA, lua_gettable(), lua_pop, Eluna::Push(), and sEluna.
Initialize()
void ElunaInstanceAI::Initialize () override
{
    LOCK_ELUNA;
    ASSERT(!sEluna->HasInstanceData(instance));
    // Create a new table for instance data.
    lua_State* L = sEluna->L;
    lua_newtable(L);
    sEluna->CreateInstanceData(instance);
    sEluna->OnInitialize(this);
}
References ASSERT, LOCK_ELUNA, lua_newtable, and sEluna.
Referenced by Load().
IsEncounterInProgress()
bool ElunaInstanceAI::IsEncounterInProgress () const inline override
    {
        return sEluna->OnCheckEncounterInProgress(const_cast<ElunaInstanceAI*>(this));
    }
References sEluna.
Load()
void ElunaInstanceAI::Load (const char * data) override
{
    LOCK_ELUNA;
    // If we get passed NULL (i.e. `Reload` was called) then use
    //   the last known save data (or maybe just an empty string).
    if (!data)
    {
        data = lastSaveData.c_str();
    }
    else // Otherwise, copy the new data into our buffer.
    {
        lastSaveData.assign(data);
    }
    if (data[0] == '\0')
    {
        ASSERT(!sEluna->HasInstanceData(instance));
        // Create a new table for instance data.
        lua_State* L = sEluna->L;
        lua_newtable(L);
        sEluna->CreateInstanceData(instance);
        sEluna->OnLoad(this);
        // Stack: (empty)
        return;
    }
    size_t decodedLength;
    const unsigned char* decodedData = ElunaUtil::DecodeData(data, &decodedLength);
    lua_State* L = sEluna->L;
    if (decodedData)
    {
        // Stack: (empty)
        lua_pushcfunction(L, mar_decode);
        lua_pushlstring(L, (const char*)decodedData, decodedLength);
        // Stack: mar_decode, decoded_data
        // Call `mar_decode` and check for success.
        if (lua_pcall(L, 1, 1, 0) == 0)
        {
            // Stack: data
            // Only use the data if it's a table.
            if (lua_istable(L, -1))
            {
                sEluna->CreateInstanceData(instance);
                // Stack: (empty)
                sEluna->OnLoad(this);
                // WARNING! lastSaveData might be different after `OnLoad` if the Lua code saved data.
            }
            else
            {
                ELUNA_LOG_ERROR("Error while loading instance data: Expected data to be a table (type 5), got type {} instead", lua_type(L, -1));
                lua_pop(L, 1);
                // Stack: (empty)
#ifndef TRINITY
                Initialize();
#endif
            }
        }
        else
        {
            // Stack: error_message
            ELUNA_LOG_ERROR("Error while parsing instance data with lua-marshal: {}", lua_tostring(L, -1));
            lua_pop(L, 1);
            // Stack: (empty)
#ifndef TRINITY
            Initialize();
#endif
        }
        delete[] decodedData;
    }
    else
    {
        ELUNA_LOG_ERROR("Error while decoding instance data: Data is not valid base-64");
#ifndef TRINITY
        Initialize();
#endif
    }
}
References ASSERT, ElunaUtil::DecodeData(), ELUNA_LOG_ERROR, Initialize(), lastSaveData, LOCK_ELUNA, lua_istable, lua_newtable, lua_pcall, lua_pop, lua_pushcfunction, lua_pushlstring(), lua_tostring, lua_type(), mar_decode(), and sEluna.
Referenced by Reload().
OnCreatureCreate()
void ElunaInstanceAI::OnCreatureCreate (Creature * creature) inline override
    {
        sEluna->OnCreatureCreate(this, creature);
    }
References sEluna.
OnObjectCreate()
void ElunaInstanceAI::OnObjectCreate (GameObject * gameobject) inline override
    {
        sEluna->OnGameObjectCreate(this, gameobject);
    }
References sEluna.
OnPlayerEnter()
void ElunaInstanceAI::OnPlayerEnter (Player * player) inline override
    {
        sEluna->OnPlayerEnterInstance(this, player);
    }
References sEluna.
Reload()
void ElunaInstanceAI::Reload () inline
    {
        Load(NULL);
    }
References Load().
Referenced by Eluna::PushInstanceData(), and Update().
Save()
const char * ElunaInstanceAI::Save () const override
{
    LOCK_ELUNA;
    lua_State* L = sEluna->L;
    // Stack: (empty)
    /*
     * Need to cheat because this method actually does modify this instance,
     *   even though it's declared as `const`.
     *
     * Declaring virtual methods as `const` is BAD!
     * Don't dictate to children that their methods must be pure.
     */
    ElunaInstanceAI* self = const_cast<ElunaInstanceAI*>(this);
    lua_pushcfunction(L, mar_encode);
    sEluna->PushInstanceData(L, self, false);
    // Stack: mar_encode, instance_data
    if (lua_pcall(L, 1, 1, 0) != 0)
    {
        // Stack: error_message
        ELUNA_LOG_ERROR("Error while saving: {}", lua_tostring(L, -1));
        lua_pop(L, 1);
        return NULL;
    }
    // Stack: data
    size_t dataLength;
    const unsigned char* data = (const unsigned char*)lua_tolstring(L, -1, &dataLength);
    ElunaUtil::EncodeData(data, dataLength, self->lastSaveData);
    lua_pop(L, 1);
    // Stack: (empty)
    return lastSaveData.c_str();
}
References ELUNA_LOG_ERROR, ElunaUtil::EncodeData(), lastSaveData, LOCK_ELUNA, lua_pcall, lua_pop, lua_pushcfunction, lua_tolstring(), lua_tostring, mar_encode(), and sEluna.
SetData()
void ElunaInstanceAI::SetData (uint32 key, uint32 value) override
{
    LOCK_ELUNA;
    lua_State* L = sEluna->L;
    // Stack: (empty)
    sEluna->PushInstanceData(L, this, false);
    // Stack: instance_data
    Eluna::Push(L, key);
    Eluna::Push(L, value);
    // Stack: instance_data, key, value
    lua_settable(L, -3);
    // Stack: instance_data
    lua_pop(L, 1);
    // Stack: (empty)
}
References LOCK_ELUNA, lua_pop, lua_settable(), Eluna::Push(), and sEluna.
SetData64()
void ElunaInstanceAI::SetData64 (uint32 key, uint64 value) override
{
    LOCK_ELUNA;
    lua_State* L = sEluna->L;
    // Stack: (empty)
    sEluna->PushInstanceData(L, this, false);
    // Stack: instance_data
    Eluna::Push(L, key);
    Eluna::Push(L, value);
    // Stack: instance_data, key, value
    lua_settable(L, -3);
    // Stack: instance_data
    lua_pop(L, 1);
    // Stack: (empty)
}
References LOCK_ELUNA, lua_pop, lua_settable(), Eluna::Push(), and sEluna.
Update()
void ElunaInstanceAI::Update (uint32 diff) inline override
    {
        // If Eluna is reloaded, it will be missing our instance data.
        // Reload here instead of waiting for the next hook call (possibly never).
        // This avoids having to have an empty Update hook handler just to trigger the reload.
        if (!sEluna->HasInstanceData(instance))
            Reload();
        sEluna->OnUpdateInstance(this, diff);
    }
References Reload(), and sEluna.
Member Data Documentation
lastSaveData
std::string ElunaInstanceAI::lastSaveData private
Referenced by Load(), and Save().
The documentation for this class was generated from the following files:
mod-eluna/src/LuaEngine/ElunaInstanceAI.h
mod-eluna/src/LuaEngine/ElunaInstanceAI.cpp