AzerothCore Doxygen
message_commandscript Class Reference
Public Member Functions
message_commandscript ()
ChatCommandTable GetCommands () const override
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
uint16 GetTotalAvailableHooks ()
Static Public Member Functions
static bool HandleNameAnnounceCommand (ChatHandler *handler, Tail message)
static bool HandleGMNameAnnounceCommand (ChatHandler *handler, Tail message)
static bool HandleAnnounceCommand (ChatHandler *handler, Tail message)
static bool HandleGMAnnounceCommand (ChatHandler *handler, Tail message)
static bool HandleNotifyCommand (ChatHandler *handler, Tail message)
static bool HandleGMNotifyCommand (ChatHandler *handler, Tail message)
static bool HandleWhispersCommand (ChatHandler *handler, Optional< Variant< bool, EXACT_SEQUENCE("remove")> > operationArg, Optional< std::string > playerNameArg)
Additional Inherited Members
Protected Member Functions inherited from CommandScript
CommandScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name, uint16 totalAvailableHooks=0)
virtual ~ScriptObject ()=default
Detailed Description
Constructor & Destructor Documentation
message_commandscript()
message_commandscript::message_commandscript () inline
: CommandScript("message_commandscript") { }
Member Function Documentation
GetCommands()
ChatCommandTable message_commandscript::GetCommands () const inline override virtual
Implements CommandScript.
    {
        static ChatCommandTable commandTable =
        {
            { "nameannounce",   HandleNameAnnounceCommand,   rbac::RBAC_PERM_COMMAND_NAMEANNOUNCE,   Console::Yes },
            { "gmnameannounce", HandleGMNameAnnounceCommand, rbac::RBAC_PERM_COMMAND_GMNAMEANNOUNCE, Console::Yes },
            { "announce",       HandleAnnounceCommand,       rbac::RBAC_PERM_COMMAND_ANNOUNCE,       Console::Yes },
            { "gmannounce",     HandleGMAnnounceCommand,     rbac::RBAC_PERM_COMMAND_GMANNOUNCE,     Console::Yes },
            { "notify",         HandleNotifyCommand,         rbac::RBAC_PERM_COMMAND_NOTIFY,         Console::Yes },
            { "gmnotify",       HandleGMNotifyCommand,       rbac::RBAC_PERM_COMMAND_GMNOTIFY,       Console::Yes },
            { "whispers",       HandleWhispersCommand,       rbac::RBAC_PERM_COMMAND_WHISPERS,       Console::No },
        };
        return commandTable;
    }
References HandleAnnounceCommand(), HandleGMAnnounceCommand(), HandleGMNameAnnounceCommand(), HandleGMNotifyCommand(), HandleNameAnnounceCommand(), HandleNotifyCommand(), HandleWhispersCommand(), rbac::RBAC_PERM_COMMAND_ANNOUNCE, rbac::RBAC_PERM_COMMAND_GMANNOUNCE, rbac::RBAC_PERM_COMMAND_GMNAMEANNOUNCE, rbac::RBAC_PERM_COMMAND_GMNOTIFY, rbac::RBAC_PERM_COMMAND_NAMEANNOUNCE, rbac::RBAC_PERM_COMMAND_NOTIFY, and rbac::RBAC_PERM_COMMAND_WHISPERS.
HandleAnnounceCommand()
static bool message_commandscript::HandleAnnounceCommand (ChatHandler * handler, Tail message) inline static
    {
        if (message.empty())
            return false;
        sWorldSessionMgr->SendServerMessage(SERVER_MSG_STRING, Acore::StringFormat(handler->GetAcoreString(LANG_SYSTEMMESSAGE), message.data()));
        return true;
    }
References ChatHandler::GetAcoreString(), LANG_SYSTEMMESSAGE, SERVER_MSG_STRING, Acore::StringFormat(), and sWorldSessionMgr.
Referenced by GetCommands().
HandleGMAnnounceCommand()
static bool message_commandscript::HandleGMAnnounceCommand (ChatHandler * handler, Tail message) inline static
    {
        if (message.empty())
            return false;
        handler->SendGMText(LANG_GM_BROADCAST, message.data());
        return true;
    }
References LANG_GM_BROADCAST, and ChatHandler::SendGMText().
Referenced by GetCommands().
HandleGMNameAnnounceCommand()
static bool message_commandscript::HandleGMNameAnnounceCommand (ChatHandler * handler, Tail message) inline static
    {
        if (message.empty())
            return false;
        std::string name("Console");
        if (WorldSession* session = handler->GetSession())
            name = session->GetPlayer()->GetName();
        handler->SendGMText(LANG_GM_ANNOUNCE_COLOR, name, message.data());
        return true;
    }
References ChatHandler::GetSession(), LANG_GM_ANNOUNCE_COLOR, and ChatHandler::SendGMText().
Referenced by GetCommands().
HandleGMNotifyCommand()
static bool message_commandscript::HandleGMNotifyCommand (ChatHandler * handler, Tail message) inline static
    {
        if (message.empty())
            return false;
        std::string str = handler->GetAcoreString(LANG_GM_NOTIFY);
        str += message;
        WorldPacket data(SMSG_NOTIFICATION, (str.size() + 1));
        data << str;
        sWorldSessionMgr->SendGlobalGMMessage(&data);
        return true;
    }
References ChatHandler::GetAcoreString(), LANG_GM_NOTIFY, SMSG_NOTIFICATION, and sWorldSessionMgr.
Referenced by GetCommands().
HandleNameAnnounceCommand()
static bool message_commandscript::HandleNameAnnounceCommand (ChatHandler * handler, Tail message) inline static
    {
        if (message.empty())
            return false;
        std::string name("Console");
        if (WorldSession* session = handler->GetSession())
            name = session->GetPlayer()->GetName();
        handler->SendWorldText(LANG_ANNOUNCE_COLOR, name, message.data());
        return true;
    }
References ChatHandler::GetSession(), LANG_ANNOUNCE_COLOR, and ChatHandler::SendWorldText().
Referenced by GetCommands().
HandleNotifyCommand()
static bool message_commandscript::HandleNotifyCommand (ChatHandler * handler, Tail message) inline static
    {
        if (message.empty())
            return false;
        std::string str = handler->GetAcoreString(LANG_GLOBAL_NOTIFY);
        str += message;
        WorldPacket data(SMSG_NOTIFICATION, (str.size() + 1));
        data << str;
        sWorldSessionMgr->SendGlobalMessage(&data);
        return true;
    }
References ChatHandler::GetAcoreString(), LANG_GLOBAL_NOTIFY, SMSG_NOTIFICATION, and sWorldSessionMgr.
Referenced by GetCommands().
HandleWhispersCommand()
static bool message_commandscript::HandleWhispersCommand (ChatHandler * handler, Optional< Variant< bool, EXACT_SEQUENCE("remove")> > operationArg, Optional< std::string > playerNameArg) inline static
    {
        if (!operationArg)
        {
            handler->PSendSysMessage(LANG_COMMAND_WHISPERACCEPTING, handler->GetSession()->GetPlayer()->isAcceptWhispers() ?  handler->GetAcoreString(LANG_ON) : handler->GetAcoreString(LANG_OFF));
            return true;
        }
        if (operationArg->holds_alternative<bool>())
        {
            if (operationArg->get<bool>())
            {
                handler->GetSession()->GetPlayer()->SetAcceptWhispers(true);
                handler->SendSysMessage(LANG_COMMAND_WHISPERON);
                return true;
            }
            else
            {
                // Remove all players from the Gamemaster's whisper whitelist
                handler->GetSession()->GetPlayer()->ClearWhisperWhiteList();
                handler->GetSession()->GetPlayer()->SetAcceptWhispers(false);
                handler->SendSysMessage(LANG_COMMAND_WHISPEROFF);
                return true;
            }
        }
        if (operationArg->holds_alternative<EXACT_SEQUENCE("remove")>())
        {
            if (!playerNameArg)
                return false;
            if (normalizePlayerName(*playerNameArg))
            {
                if (Player* player = ObjectAccessor::FindPlayerByName(*playerNameArg))
                {
                    handler->GetSession()->GetPlayer()->RemoveFromWhisperWhiteList(player->GetGUID());
                    handler->PSendSysMessage(LANG_COMMAND_WHISPEROFFPLAYER, playerNameArg->c_str());
                    return true;
                }
                else
                {
                    handler->SendErrorMessage(LANG_PLAYER_NOT_FOUND, playerNameArg->c_str());
                    return false;
                }
            }
        }
        handler->SendErrorMessage(LANG_USE_BOL);
        return false;
    }
References Player::ClearWhisperWhiteList(), EXACT_SEQUENCE, ObjectAccessor::FindPlayerByName(), ChatHandler::GetAcoreString(), WorldSession::GetPlayer(), ChatHandler::GetSession(), Player::isAcceptWhispers(), LANG_COMMAND_WHISPERACCEPTING, LANG_COMMAND_WHISPEROFF, LANG_COMMAND_WHISPEROFFPLAYER, LANG_COMMAND_WHISPERON, LANG_OFF, LANG_ON, LANG_PLAYER_NOT_FOUND, LANG_USE_BOL, normalizePlayerName(), ChatHandler::PSendSysMessage(), Player::RemoveFromWhisperWhiteList(), ChatHandler::SendErrorMessage(), ChatHandler::SendSysMessage(), and Player::SetAcceptWhispers().
Referenced by GetCommands().
The documentation for this class was generated from the following file:
azerothcore-wotlk/src/server/scripts/Commands/cs_message.cpp