AzerothCore Doxygen
EventMgr Class Reference
#include "ElunaEventMgr.h"
Public Types
typedef std::unordered_set< ElunaEventProcessor * > ProcessorSet
Public Types inherited from ElunaUtil::Lockable
typedef std::mutex LockType
typedef std::lock_guard< LockType > Guard
Public Member Functions
EventMgr (Eluna **_E)
~EventMgr ()
void SetStates (LuaEventState state)
void SetState (int eventId, LuaEventState state)
Public Member Functions inherited from ElunaUtil::Lockable
LockType & GetLock ()
Public Attributes
ProcessorSet processors
ElunaEventProcessor * globalProcessor
Eluna ** E
Detailed Description
Member Typedef Documentation
ProcessorSet
typedef std::unordered_set<ElunaEventProcessor*> EventMgr::ProcessorSet
Constructor & Destructor Documentation
EventMgr()
EventMgr::EventMgr (Eluna ** _E)
                             : globalProcessor(new ElunaEventProcessor(_E, NULL)), E(_E)
{
}
~EventMgr()
EventMgr::~EventMgr ()
{
    {
        Guard guard(GetLock());
        if (!processors.empty())
            for (ProcessorSet::const_iterator it = processors.begin(); it != processors.end(); ++it) // loop processors
                (*it)->RemoveEvents_internal();
        globalProcessor->RemoveEvents_internal();
    }
    delete globalProcessor;
    globalProcessor = NULL;
}
References ElunaUtil::Lockable::GetLock(), globalProcessor, processors, and ElunaEventProcessor::RemoveEvents_internal().
Member Function Documentation
SetState()
void EventMgr::SetState (int eventId, LuaEventState state)
{
    Guard guard(GetLock());
    if (!processors.empty())
        for (ProcessorSet::const_iterator it = processors.begin(); it != processors.end(); ++it) // loop processors
            (*it)->SetState(eventId, state);
    globalProcessor->SetState(eventId, state);
}
References ElunaUtil::Lockable::GetLock(), globalProcessor, processors, and ElunaEventProcessor::SetState().
Referenced by LuaGlobalFunctions::RemoveEventById().
SetStates()
void EventMgr::SetStates (LuaEventState state)
{
    Guard guard(GetLock());
    if (!processors.empty())
        for (ProcessorSet::const_iterator it = processors.begin(); it != processors.end(); ++it) // loop processors
            (*it)->SetStates(state);
    globalProcessor->SetStates(state);
}
References ElunaUtil::Lockable::GetLock(), globalProcessor, processors, and ElunaEventProcessor::SetStates().
Referenced by LuaGlobalFunctions::RemoveEvents().
Member Data Documentation
E
Eluna** EventMgr::E
globalProcessor
ElunaEventProcessor* EventMgr::globalProcessor
Referenced by LuaGlobalFunctions::CreateLuaEvent(), Eluna::OnWorldUpdate(), LuaGlobalFunctions::RemoveEventById(), LuaGlobalFunctions::RemoveEvents(), SetState(), SetStates(), and ~EventMgr().
processors
ProcessorSet EventMgr::processors
Referenced by SetState(), SetStates(), and ~EventMgr().
The documentation for this class was generated from the following files:
mod-eluna/src/LuaEngine/ElunaEventMgr.h
mod-eluna/src/LuaEngine/ElunaEventMgr.cpp