AzerothCore Doxygen
SpellProcTargetResolutionTest.cpp File Reference
Tests for smart proc trigger target resolution.
#include "ProcEventInfoHelper.h"
#include "Unit.h"
#include "gtest/gtest.h"
Classes
class SpellProcTargetResolutionTest
Functions
static Unit * ResolveProcTriggerTarget (Unit *triggerCaster, ProcEventInfo &eventInfo)
Applies the smart targeting expression from SpellAuraEffects.cpp.
TEST_F (SpellProcTargetResolutionTest, ActorSide_HitPhase_TargetsEnemy)
TEST_F (SpellProcTargetResolutionTest, ActorSide_FinishPhase_ReturnsNullptr)
TEST_F (SpellProcTargetResolutionTest, ActorSide_CastPhase_TargetsEnemy)
TEST_F (SpellProcTargetResolutionTest, VictimSide_HitPhase_TargetsAttacker)
TEST_F (SpellProcTargetResolutionTest, ActorSide_NullActionTarget_ReturnsNullptr)
TEST_F (SpellProcTargetResolutionTest, VictimSide_NullActionTarget_StillReturnsActor)
TEST_F (SpellProcTargetResolutionTest, SelfProc_ActorIsActionTarget)
Detailed Description
Tests for smart proc trigger target resolution.
Verifies the targeting expression used in HandleProcTriggerSpellAuraProc and HandleProcTriggerSpellWithValueAuraProc:
triggerTarget = (triggerCaster == actor) ? actionTarget : actor
This expression correctly resolves targets for all proc scenarios:
Actor-side HIT phase: triggerCaster==actor, returns enemy (actionTarget)
Actor-side FINISH phase: triggerCaster==actor, returns nullptr (actionTarget is nullptr because FINISH phase passes no victim)
Victim-side HIT phase: triggerCaster!=actor, returns attacker (actor)
Definition in file SpellProcTargetResolutionTest.cpp.
Function Documentation
ResolveProcTriggerTarget()
static Unit * ResolveProcTriggerTarget (Unit * triggerCaster, ProcEventInfo & eventInfo) static
Applies the smart targeting expression from SpellAuraEffects.cpp.
This mirrors the logic in HandleProcTriggerSpellAuraProc: Unit* triggerCaster = aurApp->GetTarget(); // the aura owner Unit* triggerTarget = triggerCaster == eventInfo.GetActor() ? eventInfo.GetActionTarget() : eventInfo.GetActor();
{
    return triggerCaster == eventInfo.GetActor()
        ? eventInfo.GetActionTarget()
        : eventInfo.GetActor();
}
References ProcEventInfo::GetActionTarget(), and ProcEventInfo::GetActor().
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
TEST_F() [1/7]
TEST_F (SpellProcTargetResolutionTest , ActorSide_CastPhase_TargetsEnemy)
{
    // Scenario: Actor-side CAST phase proc (e.g., Nature's Grace).
    // actor=Rogue, actionTarget=Enemy
    // triggerCaster == actor, returns actionTarget
    auto eventInfo = ProcEventInfoBuilder()
        .WithActor(FAKE_ROGUE)
        .WithActionTarget(FAKE_ENEMY)
        .WithTypeMask(PROC_FLAG_DONE_SPELL_MAGIC_DMG_CLASS_NEG)
        .WithSpellPhaseMask(PROC_SPELL_PHASE_CAST)
        .Build();
    Unit* triggerCaster = FAKE_ROGUE;
    Unit* result = ResolveProcTriggerTarget(triggerCaster, eventInfo);
    EXPECT_EQ(result, FAKE_ENEMY);
}
References ProcEventInfoBuilder::Build(), PROC_FLAG_DONE_SPELL_MAGIC_DMG_CLASS_NEG, PROC_SPELL_PHASE_CAST, ResolveProcTriggerTarget(), ProcEventInfoBuilder::WithActionTarget(), ProcEventInfoBuilder::WithActor(), ProcEventInfoBuilder::WithSpellPhaseMask(), and ProcEventInfoBuilder::WithTypeMask().
TEST_F() [2/7]
TEST_F (SpellProcTargetResolutionTest , ActorSide_FinishPhase_ReturnsNullptr)
{
    // Scenario: Rogue has Ruthlessness aura, finishes Eviscerate.
    // FINISH phase: actor=Rogue, actionTarget=nullptr (no victim passed)
    // triggerCaster is the aura owner (Rogue), which == actor
    // Result: returns nullptr (CastSpell handles this via implicit targeting)
    auto eventInfo = ProcEventInfoBuilder()
        .WithActor(FAKE_ROGUE)
        .WithActionTarget(nullptr)
        .WithTypeMask(PROC_FLAG_DONE_SPELL_MELEE_DMG_CLASS)
        .WithSpellPhaseMask(PROC_SPELL_PHASE_FINISH)
        .WithHitMask(PROC_HIT_NORMAL)
        .Build();
    Unit* triggerCaster = FAKE_ROGUE; // aura owner
    Unit* result = ResolveProcTriggerTarget(triggerCaster, eventInfo);
    EXPECT_EQ(result, nullptr);
}
References ProcEventInfoBuilder::Build(), PROC_FLAG_DONE_SPELL_MELEE_DMG_CLASS, PROC_HIT_NORMAL, PROC_SPELL_PHASE_FINISH, ResolveProcTriggerTarget(), ProcEventInfoBuilder::WithActionTarget(), ProcEventInfoBuilder::WithActor(), ProcEventInfoBuilder::WithHitMask(), ProcEventInfoBuilder::WithSpellPhaseMask(), and ProcEventInfoBuilder::WithTypeMask().
TEST_F() [3/7]
TEST_F (SpellProcTargetResolutionTest , ActorSide_HitPhase_TargetsEnemy)
{
    // Scenario: Rogue has Ruthlessness aura, casts Eviscerate on enemy.
    // HIT phase: actor=Rogue, actionTarget=Enemy
    // triggerCaster is the aura owner (Rogue), which == actor
    // Result: returns actionTarget (Enemy)
    auto eventInfo = ProcEventInfoBuilder()
        .WithActor(FAKE_ROGUE)
        .WithActionTarget(FAKE_ENEMY)
        .WithTypeMask(PROC_FLAG_DONE_SPELL_MELEE_DMG_CLASS)
        .WithSpellPhaseMask(PROC_SPELL_PHASE_HIT)
        .WithHitMask(PROC_HIT_NORMAL)
        .Build();
    Unit* triggerCaster = FAKE_ROGUE; // aura owner
    Unit* result = ResolveProcTriggerTarget(triggerCaster, eventInfo);
    EXPECT_EQ(result, FAKE_ENEMY);
}
References ProcEventInfoBuilder::Build(), PROC_FLAG_DONE_SPELL_MELEE_DMG_CLASS, PROC_HIT_NORMAL, PROC_SPELL_PHASE_HIT, ResolveProcTriggerTarget(), ProcEventInfoBuilder::WithActionTarget(), ProcEventInfoBuilder::WithActor(), ProcEventInfoBuilder::WithHitMask(), ProcEventInfoBuilder::WithSpellPhaseMask(), and ProcEventInfoBuilder::WithTypeMask().
TEST_F() [4/7]
TEST_F (SpellProcTargetResolutionTest , ActorSide_NullActionTarget_ReturnsNullptr)
{
    // Generic test: when actor-side proc has nullptr actionTarget,
    // result is nullptr regardless of phase
    auto eventInfo = ProcEventInfoBuilder()
        .WithActor(FAKE_ROGUE)
        .WithActionTarget(nullptr)
        .WithTypeMask(PROC_FLAG_DONE_MELEE_AUTO_ATTACK)
        .WithHitMask(PROC_HIT_NORMAL)
        .Build();
    Unit* triggerCaster = FAKE_ROGUE;
    Unit* result = ResolveProcTriggerTarget(triggerCaster, eventInfo);
    EXPECT_EQ(result, nullptr);
}
References ProcEventInfoBuilder::Build(), PROC_FLAG_DONE_MELEE_AUTO_ATTACK, PROC_HIT_NORMAL, ResolveProcTriggerTarget(), ProcEventInfoBuilder::WithActionTarget(), ProcEventInfoBuilder::WithActor(), ProcEventInfoBuilder::WithHitMask(), and ProcEventInfoBuilder::WithTypeMask().
TEST_F() [5/7]
TEST_F (SpellProcTargetResolutionTest , SelfProc_ActorIsActionTarget)
{
    // Edge case: actor == actionTarget (self-damage/self-heal)
    // triggerCaster == actor, returns actionTarget (which is also actor)
    auto eventInfo = ProcEventInfoBuilder()
        .WithActor(FAKE_ROGUE)
        .WithActionTarget(FAKE_ROGUE)
        .WithTypeMask(PROC_FLAG_DONE_SPELL_MAGIC_DMG_CLASS_POS)
        .WithSpellPhaseMask(PROC_SPELL_PHASE_HIT)
        .WithHitMask(PROC_HIT_NORMAL)
        .Build();
    Unit* triggerCaster = FAKE_ROGUE;
    Unit* result = ResolveProcTriggerTarget(triggerCaster, eventInfo);
    EXPECT_EQ(result, FAKE_ROGUE);
}
References ProcEventInfoBuilder::Build(), PROC_FLAG_DONE_SPELL_MAGIC_DMG_CLASS_POS, PROC_HIT_NORMAL, PROC_SPELL_PHASE_HIT, ResolveProcTriggerTarget(), ProcEventInfoBuilder::WithActionTarget(), ProcEventInfoBuilder::WithActor(), ProcEventInfoBuilder::WithHitMask(), ProcEventInfoBuilder::WithSpellPhaseMask(), and ProcEventInfoBuilder::WithTypeMask().
TEST_F() [6/7]
TEST_F (SpellProcTargetResolutionTest , VictimSide_HitPhase_TargetsAttacker)
{
    // Scenario: Enemy has a "when hit" proc aura. Rogue hits Enemy.
    // HIT phase: actor=Rogue (attacker), actionTarget=Enemy (victim)
    // triggerCaster is the aura owner (Enemy), which != actor (Rogue)
    // Result: returns actor (Rogue) — the attacker
    auto eventInfo = ProcEventInfoBuilder()
        .WithActor(FAKE_ROGUE)
        .WithActionTarget(FAKE_ENEMY)
        .WithTypeMask(PROC_FLAG_TAKEN_MELEE_AUTO_ATTACK)
        .WithSpellPhaseMask(PROC_SPELL_PHASE_HIT)
        .WithHitMask(PROC_HIT_NORMAL)
        .Build();
    Unit* triggerCaster = FAKE_ENEMY; // aura owner (victim)
    Unit* result = ResolveProcTriggerTarget(triggerCaster, eventInfo);
    EXPECT_EQ(result, FAKE_ROGUE);
}
References ProcEventInfoBuilder::Build(), PROC_FLAG_TAKEN_MELEE_AUTO_ATTACK, PROC_HIT_NORMAL, PROC_SPELL_PHASE_HIT, ResolveProcTriggerTarget(), ProcEventInfoBuilder::WithActionTarget(), ProcEventInfoBuilder::WithActor(), ProcEventInfoBuilder::WithHitMask(), ProcEventInfoBuilder::WithSpellPhaseMask(), and ProcEventInfoBuilder::WithTypeMask().
TEST_F() [7/7]
TEST_F (SpellProcTargetResolutionTest , VictimSide_NullActionTarget_StillReturnsActor)
{
    // When victim-side proc has nullptr actionTarget, the expression
    // still returns actor (the attacker) since triggerCaster != actor
    auto eventInfo = ProcEventInfoBuilder()
        .WithActor(FAKE_ROGUE)
        .WithActionTarget(nullptr)
        .WithTypeMask(PROC_FLAG_TAKEN_MELEE_AUTO_ATTACK)
        .WithHitMask(PROC_HIT_NORMAL)
        .Build();
    Unit* triggerCaster = FAKE_ENEMY; // aura owner (victim), != actor
    Unit* result = ResolveProcTriggerTarget(triggerCaster, eventInfo);
    EXPECT_EQ(result, FAKE_ROGUE);
}
References ProcEventInfoBuilder::Build(), PROC_FLAG_TAKEN_MELEE_AUTO_ATTACK, PROC_HIT_NORMAL, ResolveProcTriggerTarget(), ProcEventInfoBuilder::WithActionTarget(), ProcEventInfoBuilder::WithActor(), ProcEventInfoBuilder::WithHitMask(), and ProcEventInfoBuilder::WithTypeMask().