AzerothCore Doxygen
ArenaSeasonTeamRewarderImpl Class Reference
#include "ArenaSeasonRewardsDistributor.h"
Public Member Functions
void RewardTeamWithRewardGroup (ArenaTeam *arenaTeam, ArenaSeasonRewardGroup const &rewardGroup) override
Public Member Functions inherited from ArenaSeasonTeamRewarder
virtual ~ArenaSeasonTeamRewarder ()=default
Private Member Functions
void RewardWithMail (ArenaTeam *arenaTeam, ArenaSeasonRewardGroup const &rewardGroup)
void RewardWithAchievements (ArenaTeam *arenaTeam, ArenaSeasonRewardGroup const &rewardGroup)
Detailed Description
Member Function Documentation
RewardTeamWithRewardGroup()
void ArenaSeasonTeamRewarderImpl::RewardTeamWithRewardGroup (ArenaTeam * arenaTeam, ArenaSeasonRewardGroup const & rewardGroup) override virtual
Implements ArenaSeasonTeamRewarder.
{
    RewardWithMail(arenaTeam, rewardGroup);
    RewardWithAchievements(arenaTeam, rewardGroup);
}
References RewardWithAchievements(), and RewardWithMail().
RewardWithAchievements()
void ArenaSeasonTeamRewarderImpl::RewardWithAchievements (ArenaTeam * arenaTeam, ArenaSeasonRewardGroup const & rewardGroup) private
{
    if (rewardGroup.achievementRewards.empty())
        return;
    for (auto const& member : arenaTeam->GetMembers())
    {
        uint32 teamSeasonGames = arenaTeam->GetStats().SeasonGames;
        // Avoid division by zero.
        if (teamSeasonGames == 0)
            continue;
        float memberParticipationPercentage = (static_cast<float>(member.SeasonGames) / teamSeasonGames) * 100;
        if (memberParticipationPercentage < minPctTeamGamesForMemberToGetReward)
            continue;
        Player* player = ObjectAccessor::FindPlayer(member.Guid);
        for (auto const& reward : rewardGroup.achievementRewards)
        {
            AchievementEntry const* achievement = sAchievementStore.LookupEntry(reward.entry);
            if (!achievement)
                continue;
            if (player)
                player->CompletedAchievement(achievement);
            else
                sAchievementMgr->CompletedAchievementForOfflinePlayer(member.Guid.GetCounter(), achievement);
        }
    }
}
References ArenaSeasonRewardGroup::achievementRewards, Player::CompletedAchievement(), ObjectAccessor::FindPlayer(), ArenaTeam::GetMembers(), ArenaTeam::GetStats(), minPctTeamGamesForMemberToGetReward, sAchievementMgr, sAchievementStore, and ArenaTeamStats::SeasonGames.
Referenced by RewardTeamWithRewardGroup().
RewardWithMail()
void ArenaSeasonTeamRewarderImpl::RewardWithMail (ArenaTeam * arenaTeam, ArenaSeasonRewardGroup const & rewardGroup) private
{
    if (rewardGroup.itemRewards.empty() && rewardGroup.goldReward == 0)
        return;
    const uint32 npcKingDondSender = 18897;
    CharacterDatabaseTransaction trans = CharacterDatabase.BeginTransaction();
    for (auto const& member : arenaTeam->GetMembers())
    {
        uint32 teamSeasonGames = arenaTeam->GetStats().SeasonGames;
        // Avoid division by zero.
        if (teamSeasonGames == 0)
            continue;
        float memberParticipationPercentage = (static_cast<float>(member.SeasonGames) / teamSeasonGames) * 100;
        if (memberParticipationPercentage < minPctTeamGamesForMemberToGetReward)
            continue;
        Player* player = ObjectAccessor::FindPlayer(member.Guid);
        auto draft = rewardGroup.rewardMailTemplateID > 0 ?
            MailDraft(rewardGroup.rewardMailTemplateID, false) :
            MailDraft(rewardGroup.rewardMailSubject, rewardGroup.rewardMailBody);
        if (rewardGroup.goldReward > 0)
            draft.AddMoney(rewardGroup.goldReward);
        for (auto const& reward : rewardGroup.itemRewards)
            if (Item* item = Item::CreateItem(reward.entry, 1))
            {
                item->SaveToDB(trans);
                draft.AddItem(item);
            }
        draft.SendMailTo(trans, MailReceiver(player, member.Guid.GetCounter()), MailSender(npcKingDondSender));
    }
    CharacterDatabase.CommitTransaction(trans);
}
References CharacterDatabase, Item::CreateItem(), ObjectAccessor::FindPlayer(), ArenaTeam::GetMembers(), ArenaTeam::GetStats(), ArenaSeasonRewardGroup::goldReward, ArenaSeasonRewardGroup::itemRewards, minPctTeamGamesForMemberToGetReward, ArenaSeasonRewardGroup::rewardMailBody, ArenaSeasonRewardGroup::rewardMailSubject, ArenaSeasonRewardGroup::rewardMailTemplateID, and ArenaTeamStats::SeasonGames.
Referenced by RewardTeamWithRewardGroup().
The documentation for this class was generated from the following files:
azerothcore-wotlk/src/server/game/Battlegrounds/ArenaSeason/ArenaSeasonRewardsDistributor.h
azerothcore-wotlk/src/server/game/Battlegrounds/ArenaSeason/ArenaSeasonRewardsDistributor.cpp