AzerothCore Doxygen
events_script_loader.cpp File Reference
Functions
void AddSC_event_brewfest_scripts ()
void AddSC_event_hallows_end_scripts ()
void AddSC_event_pilgrims_end_scripts ()
void AddSC_event_winter_veil_scripts ()
void AddSC_event_love_in_the_air ()
void AddSC_event_midsummer_scripts ()
void AddSC_event_childrens_week ()
void AddSC_event_firework_show_scripts ()
void AddSC_event_noblegarden_scripts ()
void AddEventsScripts ()
Function Documentation
AddEventsScripts()
void AddEventsScripts ()
{
    AddSC_event_brewfest_scripts();
    AddSC_event_hallows_end_scripts();
    AddSC_event_pilgrims_end_scripts();
    AddSC_event_winter_veil_scripts();
    AddSC_event_love_in_the_air();
    AddSC_event_midsummer_scripts();
    AddSC_event_childrens_week();
    AddSC_event_firework_show_scripts();
    AddSC_event_noblegarden_scripts();
}
References AddSC_event_brewfest_scripts(), AddSC_event_childrens_week(), AddSC_event_firework_show_scripts(), AddSC_event_hallows_end_scripts(), AddSC_event_love_in_the_air(), AddSC_event_midsummer_scripts(), AddSC_event_noblegarden_scripts(), AddSC_event_pilgrims_end_scripts(), and AddSC_event_winter_veil_scripts().
AddSC_event_brewfest_scripts()
void AddSC_event_brewfest_scripts ()
{
    // Npcs
    RegisterCreatureAI(npc_brewfest_keg_thrower);
    RegisterCreatureAI(npc_brewfest_keg_reciver);
    RegisterCreatureAI(npc_brewfest_bark_trigger);
    RegisterCreatureAI(npc_dark_iron_attack_generator);
    RegisterCreatureAI(npc_dark_iron_attack_mole_machine);
    RegisterCreatureAI(npc_dark_iron_guzzler);
    RegisterCreatureAI(npc_brewfest_super_brew_trigger);
    // Spells
    // ram
    RegisterSpellScript(spell_brewfest_main_ram_buff);
    RegisterSpellScript(spell_brewfest_ram_fatigue);
    RegisterSpellScript(spell_brewfest_apple_trap);
    // other
    RegisterSpellScript(spell_catch_the_wild_wolpertinger);
    RegisterSpellScript(spell_brewfest_fill_keg);
    RegisterSpellScript(spell_brewfest_unfill_keg);
    RegisterSpellScript(spell_brewfest_toss_mug);
    RegisterSpellScript(spell_brewfest_add_mug);
    RegisterSpellScript(spell_brewfest_reveler_transform);
    RegisterSpellScript(spell_brewfest_relay_race_force_cast);
    // beer effect
    RegisterCreatureAI(npc_brew_bubble);
    // Coren Direbrew
    RegisterCreatureAI(npc_coren_direbrew);
    RegisterCreatureAI(npc_coren_direbrew_sisters);
    RegisterCreatureAI(npc_direbrew_minion);
    RegisterCreatureAI(npc_direbrew_antagonist);
    new go_direbrew_mole_machine();
    RegisterSpellScript(spell_direbrew_summon_mole_machine_target_picker);
    RegisterSpellScript(spell_send_mug_target_picker);
    RegisterSpellScript(spell_request_second_mug);
    RegisterSpellScript(spell_send_mug_control_aura);
    RegisterSpellScript(spell_barreled_control_aura);
    RegisterSpellScript(spell_direbrew_disarm);
}
References RegisterCreatureAI, and RegisterSpellScript.
Referenced by AddEventsScripts().
AddSC_event_childrens_week()
void AddSC_event_childrens_week ()
{
    RegisterCreatureAI(npc_elder_kekek);
    RegisterCreatureAI(npc_high_oracle_soo_roo);
    RegisterCreatureAI(npc_winterfin_playmate);
    RegisterCreatureAI(npc_snowfall_glade_playmate);
    RegisterCreatureAI(npc_the_etymidian);
    RegisterCreatureAI(npc_the_biggest_tree);
    new at_bring_your_orphan_to();
    new npc_grizzlemaw_cw_trigger();
    new npc_cw_area_trigger();
    RegisterCreatureAI(npc_alexstraza_the_lifebinder);
}
References RegisterCreatureAI.
Referenced by AddEventsScripts().
AddSC_event_firework_show_scripts()
void AddSC_event_firework_show_scripts ()
{
    // Gameobjects
    RegisterGameObjectAI(go_firework_show);
}
References RegisterGameObjectAI.
Referenced by AddEventsScripts().
AddSC_event_hallows_end_scripts()
void AddSC_event_hallows_end_scripts ()
{
    // Spells
    RegisterSpellScript(spell_hallows_end_trick);
    RegisterSpellScript(spell_hallows_end_trick_or_treat);
    RegisterSpellScript(spell_hallows_end_candy);
    RegisterSpellScript(spell_hallows_end_candy_pirate_costume);
    RegisterSpellScript(spell_hallows_end_tricky_treat);
    RegisterSpellScriptWithArgs(spell_hallows_end_put_costume, "spell_hallows_end_pirate_costume", SPELL_PIRATE_COSTUME_MALE, SPELL_PIRATE_COSTUME_FEMALE);
    RegisterSpellScriptWithArgs(spell_hallows_end_put_costume, "spell_hallows_end_leper_costume", SPELL_LEPER_GNOME_COSTUME_MALE, SPELL_LEPER_GNOME_COSTUME_FEMALE);
    RegisterSpellScriptWithArgs(spell_hallows_end_put_costume, "spell_hallows_end_ghost_costume", SPELL_GHOST_COSTUME_MALE, SPELL_GHOST_COSTUME_FEMALE);
    RegisterSpellScriptWithArgs(spell_hallows_end_put_costume, "spell_hallows_end_ninja_costume", SPELL_NINJA_COSTUME_MALE, SPELL_NINJA_COSTUME_FEMALE);
    RegisterSpellScript(spell_hallows_end_base_fire);
    RegisterSpellScript(spell_hallows_end_bucket_lands);
    // Quests
    RegisterCreatureAI(npc_hallows_end_train_fire);
    // creatures
    RegisterCreatureAI(npc_costumed_orphan_matron);
    RegisterCreatureAI(npc_soh_fire_trigger);
    RegisterCreatureAI(npc_hallows_end_soh);
    // Headless Horseman
    new go_loosely_turned_soil();
    new go_pumpkin_shrine();
    RegisterCreatureAI(boss_headless_horseman);
    RegisterCreatureAI(boss_headless_horseman_head);
    RegisterCreatureAI(boss_headless_horseman_pumpkin);
}
References RegisterCreatureAI, RegisterSpellScript, RegisterSpellScriptWithArgs, SPELL_GHOST_COSTUME_FEMALE, SPELL_GHOST_COSTUME_MALE, SPELL_LEPER_GNOME_COSTUME_FEMALE, SPELL_LEPER_GNOME_COSTUME_MALE, SPELL_NINJA_COSTUME_FEMALE, SPELL_NINJA_COSTUME_MALE, SPELL_PIRATE_COSTUME_FEMALE, and SPELL_PIRATE_COSTUME_MALE.
Referenced by AddEventsScripts().
AddSC_event_love_in_the_air()
void AddSC_event_love_in_the_air ()
{
    // Npcs
    RegisterCreatureAI(npc_love_in_air_supply_sentry);
    RegisterCreatureAI(npc_love_in_air_snivel);
    RegisterCreatureAI(npc_love_in_air_snivel_real);
    // Spells
    RegisterSpellScript(spell_love_in_air_perfume_immune);
    RegisterSpellScript(spell_item_create_heart_candy);
    RegisterSpellScript(spell_love_is_in_the_air_romantic_picnic);
    RegisterSpellScript(spell_gen_aura_service_uniform);
}
References RegisterCreatureAI, and RegisterSpellScript.
Referenced by AddEventsScripts().
AddSC_event_midsummer_scripts()
void AddSC_event_midsummer_scripts ()
{
    // Player
    new MidsummerPlayerScript();
    // NPCs
    RegisterCreatureAI(npc_midsummer_bonfire);
    RegisterCreatureAI(npc_midsummer_bonfire_despawner);
    RegisterCreatureAI(npc_midsummer_ribbon_pole_target);
    // Spells
    RegisterSpellScript(spell_fire_festival_fortitude);
    RegisterSpellScript(spell_bonfires_blessing);
    RegisterSpellScript(spell_gen_crab_disguise);
    RegisterSpellScript(spell_midsummer_ribbon_pole_firework);
    RegisterSpellScript(spell_midsummer_ribbon_pole);
    RegisterSpellScript(spell_midsummer_ribbon_pole_visual);
    RegisterSpellScript(spell_midsummer_fling_torch);
    RegisterSpellScript(spell_midsummer_juggling_torch);
    RegisterSpellScript(spell_midsummer_torch_catch);
    RegisterSpellScript(spell_midsummer_summon_ahune_lieutenant);
    RegisterSpellScript(spell_braziers_hit);
    RegisterSpellScript(spell_torch_target_picker);
    RegisterSpellScript(spell_torch_tossing_training);
}
References RegisterCreatureAI, and RegisterSpellScript.
Referenced by AddEventsScripts().
AddSC_event_noblegarden_scripts()
void AddSC_event_noblegarden_scripts ()
{
    RegisterSpellScript(spell_summon_noblegarden_bunny_controller);
    RegisterSpellScript(spell_item_noblegarden_chocolate);
}
References RegisterSpellScript.
Referenced by AddEventsScripts().
AddSC_event_pilgrims_end_scripts()
void AddSC_event_pilgrims_end_scripts ()
{
    // Spells
    RegisterSpellScript(spell_pilgrims_bounty_pass_generic);
    RegisterSpellScript(spell_pilgrims_bounty_feast_on_generic);
    RegisterSpellScript(spell_pilgrims_bounty_turkey_tracker);
    RegisterSpellScript(spell_pilgrims_bounty_serve_generic);
    RegisterSpellAndAuraScriptPair(spell_pilgrims_bounty_food, spell_pilgrims_bounty_food_aura);
    // Npcs
    RegisterCreatureAI(npc_pilgrims_bounty_chair);
    RegisterCreatureAI(npc_pilgrims_bounty_plate);
    // Achievements
    new achievement_pb_pilgrims_peril();
    new achievement_pb_terokkar_turkey_time();
}
References RegisterCreatureAI, RegisterSpellAndAuraScriptPair, and RegisterSpellScript.
Referenced by AddEventsScripts().
AddSC_event_winter_veil_scripts()
void AddSC_event_winter_veil_scripts ()
{
    // Spells
    RegisterSpellScript(spell_winter_veil_mistletoe);
    RegisterSpellScript(spell_winter_wondervolt_trap);
    RegisterSpellScript(spell_winter_veil_racer_rocket_slam);
    RegisterSpellScript(spell_winter_veil_racer_slam_hit);
    RegisterSpellScript(spell_winter_veil_shoot_air_rifle);
}
References RegisterSpellScript.
Referenced by AddEventsScripts().