AzerothCore Doxygen
EffectMovementGenerator Class Reference
#include "PointMovementGenerator.h"
Public Member Functions
EffectMovementGenerator (Movement::MoveSplineInit &spline, uint32 Id)
void Initialize (Unit *) override
void Finalize (Unit *) override
void Reset (Unit *) override
bool Update (Unit *, uint32) override
MovementGeneratorType GetMovementGeneratorType () override
Public Member Functions inherited from MovementGenerator
virtual ~MovementGenerator ()
virtual uint32 GetSplineId () const
virtual void unitSpeedChanged ()
virtual void Pause (uint32)
virtual void Resume (uint32)
virtual bool GetResetPosition (float &, float &, float &)
Private Attributes
uint32 m_Id
Movement::MoveSplineInit i_spline
Detailed Description
Constructor & Destructor Documentation
EffectMovementGenerator()
EffectMovementGenerator::EffectMovementGenerator (Movement::MoveSplineInit & spline, uint32 Id) inline explicit
: m_Id(Id), i_spline(spline) {}
Member Function Documentation
Finalize()
void EffectMovementGenerator::Finalize (Unit * unit) override virtual
Implements MovementGenerator.
{
    if (!unit->IsCreature())
        return;
    if (unit->IsCreature() && unit->HasUnitMovementFlag(MOVEMENTFLAG_FALLING) && unit->movespline->isFalling()) // pussywizard
        unit->RemoveUnitMovementFlag(MOVEMENTFLAG_FALLING);
    // Need restore previous movement since we have no proper states system
    //if (unit->IsAlive() && !unit->HasUnitState(UNIT_STATE_CONFUSED | UNIT_STATE_FLEEING))
    //{
    //    if (Unit* victim = unit->GetVictim())
    //        unit->GetMotionMaster()->MoveChase(victim);
    //    else
    //        unit->GetMotionMaster()->Initialize();
    //}
    if (unit->ToCreature()->AI())
        unit->ToCreature()->AI()->MovementInform(EFFECT_MOTION_TYPE, m_Id);
}
References Creature::AI(), EFFECT_MOTION_TYPE, Unit::HasUnitMovementFlag(), Object::IsCreature(), Movement::MoveSpline::isFalling(), m_Id, MOVEMENTFLAG_FALLING, CreatureAI::MovementInform(), Unit::movespline, Unit::RemoveUnitMovementFlag(), and Object::ToCreature().
GetMovementGeneratorType()
MovementGeneratorType EffectMovementGenerator::GetMovementGeneratorType () inline override virtual
Implements MovementGenerator.
{ return EFFECT_MOTION_TYPE; }
References EFFECT_MOTION_TYPE.
Initialize()
void EffectMovementGenerator::Initialize (Unit *) override virtual
Implements MovementGenerator.
{
    i_spline.Launch();
}
References i_spline, and Movement::MoveSplineInit::Launch().
Reset()
void EffectMovementGenerator::Reset (Unit *) inline override virtual
Implements MovementGenerator.
{}
Update()
bool EffectMovementGenerator::Update (Unit * unit, uint32) override virtual
Implements MovementGenerator.
{
    return !unit->movespline->Finalized();
}
References Movement::MoveSpline::Finalized(), and Unit::movespline.
Member Data Documentation
i_spline
Movement::MoveSplineInit EffectMovementGenerator::i_spline private
Referenced by Initialize().
m_Id
uint32 EffectMovementGenerator::m_Id private
Referenced by Finalize().
The documentation for this class was generated from the following files:
azerothcore-wotlk/src/server/game/Movement/MovementGenerators/PointMovementGenerator.h
azerothcore-wotlk/src/server/game/Movement/MovementGenerators/PointMovementGenerator.cpp