AzerothCore Doxygen
LuaSpell Namespace Reference
Functions
int IsAutoRepeat (lua_State *L, Spell *spell)
int GetCaster (lua_State *L, Spell *spell)
int GetCastTime (lua_State *L, Spell *spell)
int GetEntry (lua_State *L, Spell *spell)
int GetPowerCost (lua_State *L, Spell *spell)
int GetReagentCost (lua_State *L, Spell *spell)
int GetDuration (lua_State *L, Spell *spell)
int GetTargetDest (lua_State *L, Spell *spell)
int GetTarget (lua_State *L, Spell *spell)
int SetAutoRepeat (lua_State *L, Spell *spell)
int Cast (lua_State *L, Spell *spell)
int Cancel (lua_State *, Spell *spell)
int Finish (lua_State *, Spell *spell)
Function Documentation
Cancel()
int LuaSpell::Cancel (lua_State * , Spell * spell)
Cancels the [Spell].
    {
        spell->cancel();
        return 0;
    }
References Spell::cancel().
Cast()
int LuaSpell::Cast (lua_State * L, Spell * spell)
Casts the [Spell].
Parameters
bool skipCheck = false : skips initial checks to see if the [Spell] can be casted or not, this is optional
    {
        bool skipCheck = Eluna::CHECKVAL<bool>(L, 2, false);
        spell->cast(skipCheck);
        return 0;
    }
References Spell::cast().
Finish()
int LuaSpell::Finish (lua_State * , Spell * spell)
Finishes the [Spell].
    {
        spell->finish();
        return 0;
    }
References Spell::finish().
GetCaster()
int LuaSpell::GetCaster (lua_State * L, Spell * spell)
Returns the [Unit] that casted the [Spell].
Returns
[Unit] caster
    {
        Eluna::Push(L, spell->GetCaster());
        return 1;
    }
References Spell::GetCaster(), and Eluna::Push().
GetCastTime()
int LuaSpell::GetCastTime (lua_State * L, Spell * spell)
Returns the cast time of the [Spell].
Returns
int32 castTime
    {
        Eluna::Push(L, spell->GetCastTime());
        return 1;
    }
References Spell::GetCastTime(), and Eluna::Push().
GetDuration()
int LuaSpell::GetDuration (lua_State * L, Spell * spell)
Returns the spell duration of the [Spell].
Returns
int32 duration
    {
#if defined TRINITY || AZEROTHCORE
        Eluna::Push(L, spell->GetSpellInfo()->GetDuration());
#else
        Eluna::Push(L, GetSpellDuration(spell->m_spellInfo));
#endif
        return 1;
    }
References SpellInfo::GetDuration(), Spell::GetSpellInfo(), Spell::m_spellInfo, and Eluna::Push().
GetEntry()
int LuaSpell::GetEntry (lua_State * L, Spell * spell)
Returns the entry ID of the [Spell].
Returns
uint32 entryId
    {
        Eluna::Push(L, spell->m_spellInfo->Id);
        return 1;
    }
References SpellInfo::Id, Spell::m_spellInfo, and Eluna::Push().
GetPowerCost()
int LuaSpell::GetPowerCost (lua_State * L, Spell * spell)
Returns the power cost of the [Spell].
Returns
uint32 powerCost
    {
        Eluna::Push(L, spell->GetPowerCost());
        return 1;
    }
References Spell::GetPowerCost(), and Eluna::Push().
GetReagentCost()
int LuaSpell::GetReagentCost (lua_State * L, Spell * spell)
Returns the reagents needed for the [Spell].
Returns
table reagents : a table containing the [ItemTemplate]s and amount of reagents needed for the [Spell]
    {
        auto spellInfo = spell->GetSpellInfo();
        auto reagents = spellInfo->Reagent;
        auto reagentCounts = spellInfo->ReagentCount;
        lua_newtable(L);
        for (auto i = 0; i < MAX_SPELL_REAGENTS; ++i)
        {
            if (reagents[i] <= 0)
                continue;
            auto reagent = eObjectMgr->GetItemTemplate(reagents[i]);
            auto count = reagentCounts[i];
            Eluna::Push(L, reagent);
            Eluna::Push(L, count);
            lua_settable(L, -3);
        }
        return 1;
    }
References eObjectMgr, Spell::GetSpellInfo(), lua_newtable, lua_settable(), MAX_SPELL_REAGENTS, Eluna::Push(), and SpellInfo::Reagent.
GetTarget()
int LuaSpell::GetTarget (lua_State * L, Spell * spell)
Returns the target [Object] of the [Spell].
The target can be any of the following [Object] types:
[Player]
[Creature]
[GameObject]
[Item]
[Corpse]
Returns
[Object] target
    {
#if defined TRINITY || AZEROTHCORE
        if (GameObject* target = spell->m_targets.GetGOTarget())
            Eluna::Push(L, target);
        else if (Item* target = spell->m_targets.GetItemTarget())
            Eluna::Push(L, target);
        else if (Corpse* target = spell->m_targets.GetCorpseTarget())
            Eluna::Push(L, target);
        else if (Unit* target = spell->m_targets.GetUnitTarget())
            Eluna::Push(L, target);
        else if (WorldObject* target = spell->m_targets.GetObjectTarget())
            Eluna::Push(L, target);
#else
        if (GameObject* target = spell->m_targets.getGOTarget())
            Eluna::Push(L, target);
        else if (Item* target = spell->m_targets.getItemTarget())
            Eluna::Push(L, target);
        else if (Corpse* target = spell->GetCaster()->GetMap()->GetCorpse(spell->m_targets.getCorpseTargetGuid()))
            Eluna::Push(L, target);
        else if (Unit* target = spell->m_targets.getUnitTarget())
            Eluna::Push(L, target);
#endif
        return 1;
    }
References Spell::GetCaster(), Map::GetCorpse(), SpellCastTargets::GetCorpseTarget(), SpellCastTargets::GetGOTarget(), SpellCastTargets::GetItemTarget(), WorldObject::GetMap(), SpellCastTargets::GetObjectTarget(), SpellCastTargets::GetUnitTarget(), Spell::m_targets, and Eluna::Push().
GetTargetDest()
int LuaSpell::GetTargetDest (lua_State * L, Spell * spell)
Returns the target destination coordinates of the [Spell].
Returns
float x : x coordinate of the [Spell]
float y : y coordinate of the [Spell]
float z : z coordinate of the [Spell]
    {
#if defined TRINITY || AZEROTHCORE
        if (!spell->m_targets.HasDst())
            return 3;
        float x, y, z;
        spell->m_targets.GetDstPos()->GetPosition(x, y, z);
#else
        if (!(spell->m_targets.m_targetMask & TARGET_FLAG_DEST_LOCATION))
            return 3;
        float x, y, z;
        spell->m_targets.getDestination(x, y, z);
#endif
        Eluna::Push(L, x);
        Eluna::Push(L, y);
        Eluna::Push(L, z);
        return 3;
    }
References SpellCastTargets::GetDstPos(), Position::GetPosition(), SpellCastTargets::HasDst(), SpellCastTargets::m_targetMask, Spell::m_targets, Eluna::Push(), and TARGET_FLAG_DEST_LOCATION.
IsAutoRepeat()
int LuaSpell::IsAutoRepeat (lua_State * L, Spell * spell)
Returns true if the [Spell] is automatically repeating, false otherwise.
Returns
bool isAutoRepeating
    {
        Eluna::Push(L, spell->IsAutoRepeat());
        return 1;
    }
References Spell::IsAutoRepeat(), and Eluna::Push().
SetAutoRepeat()
int LuaSpell::SetAutoRepeat (lua_State * L, Spell * spell)
Sets the [Spell] to automatically repeat.
Parameters
bool repeat : set variable to 'true' for spell to automatically repeat
    {
        bool repeat = Eluna::CHECKVAL<bool>(L, 2);
        spell->SetAutoRepeat(repeat);
        return 0;
    }
References Spell::SetAutoRepeat().