AzerothCore Doxygen
npc_wild_wyrm Struct Reference
Public Member Functions
npc_wild_wyrm (Creature *creature)
void InitSpellsForPhase ()
void Reset () override
void DoAction (int32 action) override
void SpellHit (Unit *caster, SpellInfo const *spellInfo) override
void MovementInform (uint32 type, uint32 id) override
void DamageTaken (Unit *, uint32 &damage, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void PassengerBoarded (Unit *passenger, int8 seatId, bool apply) override
== Fields =======================================
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
Public Member Functions inherited from VehicleAI
VehicleAI (Creature *creature)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void MoveInLineOfSight (Unit *) override
void AttackStart (Unit *) override
void OnCharmed (bool apply) override
Called when unit is charmed.
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0ms)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void OnSpellCastFinished (SpellInfo const *, SpellFinishReason)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void PathEndReached (uint32)
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
int32 VisualizeBoundary (uint32 duration, Unit *owner=nullptr, bool fill=false, bool checkZ=false) const
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
virtual void DistancingStarted ()
virtual void DistancingEnded ()
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid const &, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage to any victim (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Private Attributes
uint8 _phase {PHASE_INITIAL}
ObjectGuid _playerGuid
Additional Inherited Members
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from VehicleAI
static int32 Permissible (Creature const *creature)
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
npc_wild_wyrm()
npc_wild_wyrm::npc_wild_wyrm (Creature * creature) inline explicit
: VehicleAI(creature) { }
Member Function Documentation
DamageTaken()
void npc_wild_wyrm::DamageTaken (Unit * , uint32 & , DamageEffectType , SpellSchoolMask) inline override virtual
Called at any Damage from any attacker (before damage apply)
Note
It use for recalculation damage or special reaction at damage for attack reaction use AttackedBy called for non DOT damage in Unit::DealDamage also
Reimplemented from UnitAI.
    {
        if (damage >= me->GetHealth())
        {
            damage = me->GetHealth() - 1;
            if (_phase == PHASE_DEAD)
                return;
            _phase = PHASE_DEAD;
            scheduler.CancelAll().Async([this]
            {
                InitSpellsForPhase();
                if (Player* player = ObjectAccessor::GetPlayer(*me, _playerGuid))
                    player->VehicleSpellInitialize();
                DoCastAOE(SPELL_WYRM_KILL_CREDIT);
                DoCastAOE(SPELL_FALLING_DRAGON_FEIGN_DEATH);
                me->RemoveAurasDueToSpell(SPELL_JAWS_OF_DEATH_PERIODIC);
                me->RemoveAurasDueToSpell(SPELL_PRY_JAWS_OPEN);
                me->ReplaceAllNpcFlags(UNIT_NPC_FLAG_NONE);
                me->GetMotionMaster()->MoveFall(POINT_FALL, true);
            });
        }
    }
References _phase, _playerGuid, TaskScheduler::Async(), TaskScheduler::CancelAll(), UnitAI::DoCastAOE(), Unit::GetHealth(), Unit::GetMotionMaster(), ObjectAccessor::GetPlayer(), InitSpellsForPhase(), CreatureAI::me, MotionMaster::MoveFall(), PHASE_DEAD, POINT_FALL, Unit::RemoveAurasDueToSpell(), Unit::ReplaceAllNpcFlags(), CreatureAI::scheduler, SPELL_FALLING_DRAGON_FEIGN_DEATH, SPELL_JAWS_OF_DEATH_PERIODIC, SPELL_PRY_JAWS_OPEN, SPELL_WYRM_KILL_CREDIT, and UNIT_NPC_FLAG_NONE.
DoAction()
void npc_wild_wyrm::DoAction (int32 action) inline override virtual
Reimplemented from UnitAI.
    {
        Player* player = ObjectAccessor::GetPlayer(*me, _playerGuid);
        if (!player)
            return;
        switch (action)
        {
            case ACTION_CLAW_SWIPE_WARN:
                Talk(SAY_SWIPE, player);
                break;
            case ACTION_CLAW_SWIPE_DODGE:
                Talk(SAY_DODGED, player);
                break;
            case ACTION_GRIP_FAILING:
                Talk(SAY_GRIP_WARN, player);
                break;
            case ACTION_GRIP_LOST:
                DoCastAOE(SPELL_EJECT_PASSENGER_1, true);
                break;
            case ACTION_FATAL_STRIKE_MISS:
                Talk(SAY_STRIKE_MISS, player);
                break;
            default:
                break;
        }
    }
References _playerGuid, ACTION_CLAW_SWIPE_DODGE, ACTION_CLAW_SWIPE_WARN, ACTION_FATAL_STRIKE_MISS, ACTION_GRIP_FAILING, ACTION_GRIP_LOST, UnitAI::DoCastAOE(), ObjectAccessor::GetPlayer(), CreatureAI::me, SAY_DODGED, SAY_GRIP_WARN, SAY_STRIKE_MISS, SAY_SWIPE, and SPELL_EJECT_PASSENGER_1.
InitSpellsForPhase()
void npc_wild_wyrm::InitSpellsForPhase () inline
    {
        ASSERT(_phase < PHASE_MAX);
        for (uint8 i = 0; i < ControllableSpellsCount; ++i)
            me->m_spells[i] = WyrmControlSpells[_phase][i];
    }
References _phase, ASSERT, ControllableSpellsCount, Creature::m_spells, CreatureAI::me, PHASE_MAX, and WyrmControlSpells.
Referenced by DamageTaken(), PassengerBoarded(), and Reset().
MovementInform()
void npc_wild_wyrm::MovementInform (uint32 type, uint32 id) inline override virtual
Reimplemented from CreatureAI.
    {
        if (type != POINT_MOTION_TYPE && type != EFFECT_MOTION_TYPE)
            return;
        switch (id)
        {
            case POINT_START_FIGHT:
            {
                Player* player = ObjectAccessor::GetPlayer(*me, _playerGuid);
                if (!player)
                    return;
                DoCast(player, SPELL_PLAYER_MOUNT_WYRM);
                me->GetMotionMaster()->Clear();
                break;
            }
            case POINT_FALL:
                DoCastAOE(SPELL_EJECT_ALL_PASSENGERS);
                me->KillSelf();
                break;
            default:
                break;
        }
    }
References _playerGuid, MotionMaster::Clear(), UnitAI::DoCast(), UnitAI::DoCastAOE(), EFFECT_MOTION_TYPE, Unit::GetMotionMaster(), ObjectAccessor::GetPlayer(), Unit::KillSelf(), CreatureAI::me, POINT_FALL, POINT_MOTION_TYPE, POINT_START_FIGHT, SPELL_EJECT_ALL_PASSENGERS, and SPELL_PLAYER_MOUNT_WYRM.
PassengerBoarded()
void npc_wild_wyrm::PassengerBoarded (Unit * , int8 , bool) inline override virtual
== Fields =======================================
Reimplemented from CreatureAI.
    {
        if (!apply)
        {
            // The player is automatically moved from SEAT_INITIAL to SEAT_MOUTH during phase transition.
            // Only evade if player exits during the respective active phase.
            bool initialPhaseExit = (seatId == SEAT_INITIAL && _phase == PHASE_INITIAL);
            bool mouthPhaseExit = (seatId == SEAT_MOUTH && _phase == PHASE_MOUTH);
            if (initialPhaseExit || mouthPhaseExit)
                EnterEvadeMode(EVADE_REASON_NO_HOSTILES);
            return;
        }
        if (passenger->GetGUID() != _playerGuid)
            return;
        if (seatId == SEAT_INITIAL)
        {
            me->CastCustomSpell(SPELL_GRIP, SPELLVALUE_AURA_STACK, 50);
            DoCastAOE(SPELL_CLAW_SWIPE_PERIODIC, true);
            scheduler.Async([this]
            {
                me->GetMotionMaster()->MoveWaypoint(me->GetWaypointPath(), true);
            }).Schedule(500ms, [this](TaskContext context)
            {
                if (_phase == PHASE_MOUTH)
                    return;
                if (me->HealthBelowPct(25))
                {
                    _phase = PHASE_MOUTH;
                    context.Async([this]
                    {
                        InitSpellsForPhase();
                        DoCastAOE(SPELL_LOW_HEALTH_TRIGGER, true);
                        me->RemoveAurasDueToSpell(SPELL_CLAW_SWIPE_PERIODIC);
                        me->RemoveAurasDueToSpell(SPELL_GRIP);
                        if (Player* player = ObjectAccessor::GetPlayer(*me, _playerGuid))
                            Talk(SAY_PHASE_2, player);
                        DoCastAOE(SPELL_EJECT_PASSENGER_1, true);
                        DoCastAOE(SPELL_JAWS_OF_DEATH_PERIODIC);
                        DoCastAOE(SPELL_FLY_STATE_VISUAL);
                    });
                    return;
                }
                context.Repeat();
            });
        }
    }
References _phase, _playerGuid, TaskScheduler::Async(), TaskContext::Async(), Unit::CastCustomSpell(), UnitAI::DoCastAOE(), CreatureAI::EnterEvadeMode(), CreatureAI::EVADE_REASON_NO_HOSTILES, Object::GetGUID(), Unit::GetMotionMaster(), ObjectAccessor::GetPlayer(), Creature::GetWaypointPath(), Unit::HealthBelowPct(), InitSpellsForPhase(), CreatureAI::me, PHASE_INITIAL, PHASE_MOUTH, Unit::RemoveAurasDueToSpell(), TaskContext::Repeat(), SAY_PHASE_2, CreatureAI::scheduler, SEAT_INITIAL, SEAT_MOUTH, SPELL_CLAW_SWIPE_PERIODIC, SPELL_EJECT_PASSENGER_1, SPELL_FLY_STATE_VISUAL, SPELL_GRIP, SPELL_JAWS_OF_DEATH_PERIODIC, SPELL_LOW_HEALTH_TRIGGER, and SPELLVALUE_AURA_STACK.
Reset()
void npc_wild_wyrm::Reset () inline override virtual
Reimplemented from UnitAI.
    {
        _phase = PHASE_INITIAL;
        _playerGuid.Clear();
        scheduler.CancelAll();
        InitSpellsForPhase();
        me->SetImmuneToPC(false);
    }
References _phase, _playerGuid, TaskScheduler::CancelAll(), ObjectGuid::Clear(), InitSpellsForPhase(), CreatureAI::me, PHASE_INITIAL, CreatureAI::scheduler, and Unit::SetImmuneToPC().
SpellHit()
void npc_wild_wyrm::SpellHit (Unit * caster, SpellInfo const * spellInfo) inline override virtual
Reimplemented from CreatureAI.
    {
        if (!_playerGuid.IsEmpty() || spellInfo->Id != SPELL_SPEAR_OF_HODIR)
            return;
        _playerGuid = caster->GetGUID();
        DoCastAOE(SPELL_FULL_HEAL_MANA, true);
        me->SetImmuneToPC(true);
        me->GetMotionMaster()->MovePoint(POINT_START_FIGHT, *caster);
    }
References _playerGuid, UnitAI::DoCastAOE(), Object::GetGUID(), Unit::GetMotionMaster(), SpellInfo::Id, ObjectGuid::IsEmpty(), CreatureAI::me, MotionMaster::MovePoint(), POINT_START_FIGHT, Unit::SetImmuneToPC(), SPELL_FULL_HEAL_MANA, and SPELL_SPEAR_OF_HODIR.
UpdateAI()
void npc_wild_wyrm::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Implements UnitAI.
    {
        if (!_playerGuid)
        {
            if (UpdateVictim())
                DoMeleeAttackIfReady();
            return;
        }
        scheduler.Update(diff);
    }
References _playerGuid, UnitAI::DoMeleeAttackIfReady(), CreatureAI::scheduler, TaskScheduler::Update(), and CreatureAI::UpdateVictim().
Member Data Documentation
_phase
uint8 npc_wild_wyrm::_phase {PHASE_INITIAL} private
{PHASE_INITIAL};
Referenced by DamageTaken(), InitSpellsForPhase(), PassengerBoarded(), and Reset().
_playerGuid
ObjectGuid npc_wild_wyrm::_playerGuid private
Referenced by DamageTaken(), DoAction(), MovementInform(), PassengerBoarded(), Reset(), SpellHit(), and UpdateAI().
The documentation for this struct was generated from the following file:
azerothcore-wotlk/src/server/scripts/Northrend/zone_storm_peaks.cpp