AzerothCore Doxygen
EventMap Class Reference
#include "EventMap.h"
Classes
struct Event
Public Member Functions
EventMap ()
Reset
Removes all scheduled events and resets time and phase.
void Reset ()
Update
Updates the timer of the event map.
Parameters
time Value in ms to be added to time.
void Update (uint32 time)
void Update (Milliseconds time)
GetPhaseMask
Returns
Active phases as mask.
PhaseMask GetPhaseMask () const
Empty
Returns
True, if there are no events scheduled.
bool Empty () const
SetPhase
Sets the phase of the map (absolute).
Parameters
phase Phase which should be set. Values: 1 - 8. 0 resets phase.
void SetPhase (PhaseIndex phase)
AddPhase
Activates the given phase (absolute).
Parameters
phase Phase which should be activated. Values: 1 - 8
void AddPhase (PhaseIndex phase)
RemovePhase
Deactivates the given phase (absolute).
Parameters
phase Phase which should be deactivated. Values: 1 - 8.
void RemovePhase (PhaseIndex phase)
ScheduleEvent
Schedules a new event. An existing event is not canceled.
Parameters
eventId The id of the new event.
minTime The minimum time until the event occurs as std::chrono type.
maxTime The maximum time until the event occurs as std::chrono type.
group The group which the event is associated to. Has to be between 1 and 8. 0 means it has no group.
phase The phase in which the event can occur. Has to be between 1 and 8. 0 means it can occur in all phases.
void ScheduleEvent (EventId eventId, Milliseconds time, GroupIndex group=0u, PhaseIndex phase=0u)
void ScheduleEvent (EventId eventId, Milliseconds minTime, Milliseconds maxTime, GroupIndex group=0u, PhaseIndex phase=0u)
RescheduleEvent
Cancels the given event and reschedules it.
Parameters
eventId The id of the event.
minTime The minimum time until the event occurs as std::chrono type.
maxTime The maximum time until the event occurs as std::chrono type.
group The group which the event is associated to. Has to be between 1 and 8. 0 means it has no group.
phase The phase in which the event can occur. Has to be between 1 and 8. 0 means it can occur in all phases.
void RescheduleEvent (EventId eventId, Milliseconds time, GroupIndex group=0u, PhaseIndex phase=0u)
void RescheduleEvent (EventId eventId, Milliseconds minTime, Milliseconds maxTime, GroupIndex group=0u, PhaseIndex phase=0u)
Repeat
Repeats the most recently executed event.
Parameters
minTime The minimum time until the event occurs as std::chrono type.
maxTime The maximum time until the event occurs as std::chrono type.
void Repeat (Milliseconds time)
void Repeat (Milliseconds minTime, Milliseconds maxTime)
ExecuteEvent
Returns the next event to execute and removes it from map.
Returns
Id of the event to execute.
EventId ExecuteEvent ()
DelayEvents
Delay all events of the same group.
Parameters
delay Amount of delay as std::chrono type.
group Group of the events.
void DelayEvents (Milliseconds delay)
void DelayEvents (Milliseconds delay, GroupIndex group)
EventsEvents
Delay all events of the same group.
Parameters
delay Amount of delay as std::chrono type.
group Group of the events.
void DelayEventsToMax (Milliseconds delay, GroupIndex group)
CancelEvent
Cancels all events of the specified id.
Parameters
eventId Event id to cancel.
void CancelEvent (EventId eventId)
CancelEventGroup
Cancel events belonging to specified group.
Parameters
group Group to cancel.
void CancelEventGroup (GroupIndex group)
IsInPhase
Returns whether event map is in specified phase or not.
Parameters
phase Wanted phase.
Returns
True, if phase of event map contains specified phase.
bool IsInPhase (PhaseIndex phase) const
GetTimeUntilEvent
Returns time as std::chrono type until next event.
Parameters
eventId The id of the event.
Returns
Time of next event. If event is not scheduled returns Milliseconds::max()
Time of next event.
Milliseconds GetTimeUntilEvent (EventId eventId) const
HasTimeUntilEvent
Returns whether an event is scheduled
Parameters
eventId The id of the event.
Returns
True if event is scheduled
bool HasTimeUntilEvent (EventId eventId) const
Private Types
using EventId = uint16
using GroupIndex = uint8
using GroupMask = uint8
using PhaseIndex = uint8
using PhaseMask = uint8
using EventStore = std::multimap< TimePoint, Event >
Private Attributes
_time
Internal timer.
This does not represent the real date/time value. It's more like a stopwatch: It can run, it can be stopped, it can be resetted and so on. Events occur when this timer has reached their time value. Its value is changed in the Update method.
TimePoint _time { TimePoint::min() }
_phaseMask
Phase mask of the event map.
Contains the phases the event map is in. Multiple phases from 1 to 8 can be set with SetPhase or AddPhase. RemovePhase deactives a phase.
PhaseMask _phaseMask { 0 }
_lastEvent
Stores information on the most recently executed event
Event _lastEvent
_eventMap
Internal event storage map. Contains the scheduled events.
See typedef at the beginning of the class for more details.
EventStore _eventMap
Detailed Description
Member Typedef Documentation
EventId
using EventMap::EventId = uint16 private
EventStore
using EventMap::EventStore = std::multimap<TimePoint, Event> private
Internal storage type. Key: Time as TimePoint when the event should occur.
GroupIndex
using EventMap::GroupIndex = uint8 private
GroupMask
using EventMap::GroupMask = uint8 private
PhaseIndex
using EventMap::PhaseIndex = uint8 private
PhaseMask
using EventMap::PhaseMask = uint8 private
Constructor & Destructor Documentation
EventMap()
EventMap::EventMap () inline
{ }
Member Function Documentation
AddPhase()
void EventMap::AddPhase (PhaseIndex phase)
{
    if (phase && phase <= sizeof(PhaseMask) * 8)
        _phaseMask |= PhaseMask(1u << (phase - 1u));
}
References _phaseMask.
CancelEvent()
void EventMap::CancelEvent (EventId eventId)
{
    if (Empty())
        return;
    for (auto itr = _eventMap.begin(); itr != _eventMap.end();)
    {
        if (eventId == itr->second._id)
        {
            itr = _eventMap.erase(itr);
            continue;
        }
        ++itr;
    }
}
References _eventMap, and Empty().
Referenced by go_suppression_device::go_suppression_deviceAI::Deactivate(), go_suppression_device::go_suppression_deviceAI::DoAction(), BattlegroundWS::EventPlayerCapturedFlag(), BattlegroundWS::EventPlayerClickedOnFlag(), BattlegroundAB::EventPlayerClickedOnFlag(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::JustEngagedWith(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::JustEngagedWith(), BattlegroundDS::PostUpdateImpl(), RescheduleEvent(), RescheduleEvent(), BattlegroundWS::RespawnFlagAfterDrop(), npc_blackhand_incarcerator::npc_blackhand_incarceratorAI::SetData(), instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript::SetData(), instance_ulduar::instance_ulduar_InstanceMapScript::SetData(), instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript::Update(), and npc_simon_bunny::npc_simon_bunnyAI::UpdateAI().
CancelEventGroup()
void EventMap::CancelEventGroup (GroupIndex group)
{
    if (!group || group > sizeof(GroupMask) * 8 || Empty())
        return;
    for (auto itr = _eventMap.begin(); itr != _eventMap.end();)
    {
        if (itr->second._groupMask & GroupMask(1u << (group - 1u)))
        {
            _eventMap.erase(itr);
            itr = _eventMap.begin();
            continue;
        }
        ++itr;
    }
}
References _eventMap, and Empty().
Referenced by npc_simon_bunny::npc_simon_bunnyAI::DoAction(), and boss_ragnaros::boss_ragnarosAI::HandleEmerge().
DelayEvents() [1/2]
void EventMap::DelayEvents (Milliseconds delay)
{
    if (Empty())
        return;
    EventStore delayed = std::move(_eventMap);
    for (auto itr = delayed.begin(); itr != delayed.end();)
    {
        auto node = delayed.extract(itr++);
        node.key() = node.key() + delay;
        _eventMap.insert(_eventMap.end(), std::move(node));
    }
}
References _eventMap, and Empty().
DelayEvents() [2/2]
void EventMap::DelayEvents (Milliseconds delay, GroupIndex group)
{
    if (group > sizeof(GroupMask) * 8 || Empty())
        return;
    EventStore delayed;
    for (auto itr = _eventMap.begin(); itr != _eventMap.end();)
    {
        if (!group || (itr->second._groupMask & GroupMask(1u << (group - 1u))))
        {
            delayed.emplace(itr->first + delay, itr->second);
            itr = _eventMap.erase(itr);
            continue;
        }
        ++itr;
    }
    _eventMap.insert(delayed.begin(), delayed.end());
}
References _eventMap, and Empty().
DelayEventsToMax()
void EventMap::DelayEventsToMax (Milliseconds delay, GroupIndex group)
{
    for (auto itr = _eventMap.begin(); itr != _eventMap.end();)
    {
        if (itr->first < _time + delay && (!group || (itr->second._groupMask & GroupMask(1u << (group - 1u)))))
        {
            ScheduleEvent(itr->second._id, delay, group);
            _eventMap.erase(itr);
            itr = _eventMap.begin();
            continue;
        }
        ++itr;
    }
}
References _eventMap, _time, and ScheduleEvent().
Referenced by boss_faction_championsAI::EventMapGCD().
Empty()
bool EventMap::Empty () const inline
    {
        return _eventMap.empty();
    }
References _eventMap.
Referenced by CancelEvent(), CancelEventGroup(), DelayEvents(), DelayEvents(), ExecuteEvent(), instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript::Update(), instance_ulduar::instance_ulduar_InstanceMapScript::Update(), boss_ragnaros::boss_ragnarosAI::UpdateAI(), and npc_arthas_teleport_visual::npc_arthas_teleport_visualAI::UpdateAI().
ExecuteEvent()
EventMap::EventId EventMap::ExecuteEvent ()
{
    while (!Empty())
    {
        auto const& itr = _eventMap.begin();
        if (itr->first > _time)
            return 0;
        else if (_phaseMask && itr->second._phaseMask && !(itr->second._phaseMask & _phaseMask))
            _eventMap.erase(itr);
        else
        {
            auto eventId = itr->second._id;
            _lastEvent = itr->second;
            _eventMap.erase(itr);
            return eventId;
        }
    }
    return 0;
}
References _eventMap, _lastEvent, _phaseMask, _time, and Empty().
Referenced by BattlegroundAB::PostUpdateImpl(), BattlegroundDS::PostUpdateImpl(), BattlegroundEY::PostUpdateImpl(), BattlegroundWS::PostUpdateImpl(), instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript::Update(), instance_sunken_temple::instance_sunken_temple_InstanceMapScript::Update(), instance_old_hillsbrad::instance_old_hillsbrad_InstanceMapScript::Update(), instance_naxxramas::Update(), instance_ulduar::instance_ulduar_InstanceMapScript::Update(), go_bear_trap::go_bear_trapAI::UpdateAI(), go_gilded_brazier::go_gilded_brazierAI::UpdateAI(), go_bells::go_bellsAI::UpdateAI(), boss_sartharion_dragonAI::UpdateAI(), boss_ambassador_flamelash::boss_ambassador_flamelashAI::UpdateAI(), boss_doomrel::boss_doomrelAI::UpdateAI(), npc_blackhand_incarcerator::npc_blackhand_incarceratorAI::UpdateAI(), npc_vaelastrasz_the_red::npc_vaelastrasz_the_redAI::UpdateAI(), go_suppression_device::go_suppression_deviceAI::UpdateAI(), boss_vaelastrasz::boss_vaelAI::UpdateAI(), boss_ragnaros::boss_ragnarosAI::UpdateAI(), boss_kirtonos_the_herald::boss_kirtonos_the_heraldAI::UpdateAI(), npc_cameron::UpdateAI(), npc_supervisor_raelen::UpdateAI(), npc_eastvale_peasent::UpdateAI(), npc_partygoer_pather::UpdateAI(), npc_partygoer::UpdateAI(), npc_sentinel_leader::UpdateAI(), npc_sentinel_infiltrator::UpdateAI(), npc_lady_sylvanas_windrunner::npc_lady_sylvanas_windrunnerAI::UpdateAI(), npc_varian_wrynn::npc_varian_wrynnAI::UpdateAI(), npc_jaina_proudmoore_bfu::npc_jaina_proudmoore_bfuAI::UpdateAI(), boss_blight_worm::boss_blight_wormAI::UpdateAI(), npc_thrall_bfu::npc_thrall_bfuAI::UpdateAI(), npc_lady_sylvanas_windrunner_bfu::npc_lady_sylvanas_windrunner_bfuAI::UpdateAI(), npc_zulian_prowler::npc_zulian_prowlerAI::UpdateAI(), npc_coren_direbrew::UpdateAI(), npc_arthas::npc_arthasAI::UpdateAI(), npc_stillpine_capitive::npc_stillpine_capitiveAI::UpdateAI(), npc_rabid_thistle_bear::npc_rabid_thistle_bearAI::UpdateAI(), npc_tharnarian::npc_tharnarianAI::UpdateAI(), npc_tiger_matriarch::npc_tiger_matriarchAI::UpdateAI(), boss_sartharion::boss_sartharionAI::UpdateAI(), npc_baltharus_the_warborn_clone::npc_baltharus_the_warborn_cloneAI::UpdateAI(), npc_xerestrasza::npc_xerestraszaAI::UpdateAI(), boss_halion::boss_halionAI::UpdateAI(), boss_twilight_halion::boss_twilight_halionAI::UpdateAI(), npc_halion_controller::npc_halion_controllerAI::UpdateAI(), boss_trollgore::boss_trollgoreAI::UpdateAI(), boss_moorabi::boss_moorabiAI::UpdateAI(), npc_blood_queen_lana_thel::npc_blood_queen_lana_thelAI::UpdateAI(), npc_kinetic_bomb::npc_kinetic_bombAI::UpdateAI(), npc_high_overlord_saurfang_icc::npc_high_overlord_saurfangAI::UpdateAI(), npc_muradin_bronzebeard_icc::npc_muradin_bronzebeard_iccAI::UpdateAI(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::UpdateAI(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::UpdateAI(), npc_gunship_boarding_leader::npc_gunship_boarding_leaderAI::UpdateAI(), npc_spinestalker::npc_spinestalkerAI::UpdateAI(), npc_rimefang::npc_rimefangAI::UpdateAI(), npc_sindragosa_trash::npc_sindragosa_trashAI::UpdateAI(), npc_tirion_fordring_tft::npc_tirion_fordringAI::UpdateAI(), npc_shambling_horror_icc::npc_shambling_horror_iccAI::UpdateAI(), npc_raging_spirit::npc_raging_spiritAI::UpdateAI(), npc_valkyr_shadowguard::npc_valkyr_shadowguardAI::UpdateAI(), npc_strangulate_vehicle::npc_strangulate_vehicleAI::UpdateAI(), npc_terenas_menethil::npc_terenas_menethilAI::UpdateAI(), npc_spirit_warden::npc_spirit_wardenAI::UpdateAI(), boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI::UpdateAI(), npc_the_lich_king_controller::npc_the_lich_king_controllerAI::UpdateAI(), npc_risen_archmage::npc_risen_archmageAI::UpdateAI(), npc_valithria_cloud::npc_valithria_cloudAI::UpdateAI(), npc_blazing_skeleton::npc_blazing_skeletonAI::UpdateAI(), npc_gluttonous_abomination::npc_gluttonous_abominationAI::UpdateAI(), npc_highlord_tirion_fordring_lh::npc_highlord_tirion_fordringAI::UpdateAI(), npc_rotting_frost_giant::npc_rotting_frost_giantAI::UpdateAI(), npc_frost_freeze_trap::npc_frost_freeze_trapAI::UpdateAI(), npc_crok_scourgebane::npc_crok_scourgebaneAI::UpdateAI(), npc_frostwing_vrykul::npc_frostwing_vrykulAI::UpdateAI(), npc_arthas_teleport_visual::npc_arthas_teleport_visualAI::UpdateAI(), npc_ioc_gunship_captain::npc_ioc_gunship_captainAI::UpdateAI(), npc_naxxramas_trigger::UpdateAI(), npc_spark_of_ionar::UpdateAI(), npc_enslaved_proto_drake::UpdateAI(), boss_svala::boss_svalaAI::UpdateAI(), npc_hidden_cultist::npc_hidden_cultistAI::UpdateAI(), npc_bloodmage_laurith::npc_bloodmage_laurithAI::UpdateAI(), npc_thassarian::npc_thassarianAI::UpdateAI(), npc_thassarian2::npc_thassarian2AI::UpdateAI(), npc_counselor_talbot::npc_counselor_talbotAI::UpdateAI(), npc_shandy_dalaran::npc_shandy_dalaranAI::UpdateAI(), npc_commander_eligor_dawnbringer::npc_commander_eligor_dawnbringerAI::UpdateAI(), npc_torturer_lecraft::npc_torturer_lecraftAI::UpdateAI(), npc_venture_co_straggler::npc_venture_co_stragglerAI::UpdateAI(), npc_lake_frog::npc_lake_frogAI::UpdateAI(), npc_crusade_recruit::npc_crusade_recruitAI::UpdateAI(), npc_frozen_core::UpdateAI(), npc_ahune_bunny::UpdateAI(), npc_earthen_ring_flamecaller::UpdateAI(), npc_millhouse_manastorm::npc_millhouse_manastormAI::UpdateAI(), npc_simon_bunny::npc_simon_bunnyAI::UpdateAI(), npc_magister_aledis::UpdateAI(), npc_pet_shaman_earth_elemental::UpdateAI(), npc_pet_shaman_fire_elemental::UpdateAI(), go_l70_etc_music::go_l70_etc_musicAI::UpdateAI(), go_brewfest_music::go_brewfest_musicAI::UpdateAI(), go_pirate_day_music::go_pirate_day_musicAI::UpdateAI(), go_darkmoon_faire_music::go_darkmoon_faire_musicAI::UpdateAI(), go_midsummer_music::go_midsummer_musicAI::UpdateAI(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::UpdateEscortAI(), npc_magwin::npc_magwinAI::UpdateEscortAI(), npc_onyx_flamecaller::npc_onyx_flamecallerAI::UpdateEscortAI(), and npc_jenny::UpdateFollowerAI().
GetPhaseMask()
PhaseMask EventMap::GetPhaseMask () const inline
    {
        return _phaseMask;
    }
References _phaseMask.
Referenced by npc_high_overlord_saurfang_icc::npc_high_overlord_saurfangAI::DoAction(), npc_muradin_bronzebeard_icc::npc_muradin_bronzebeard_iccAI::DoAction(), boss_ragnaros::boss_ragnarosAI::Reset(), and npc_blood_queen_lana_thel::npc_blood_queen_lana_thelAI::UpdateAI().
GetTimeUntilEvent()
Milliseconds EventMap::GetTimeUntilEvent (EventId eventId) const
{
    for (auto const& [time, event] : _eventMap)
        if (eventId == event._id)
            return std::chrono::duration_cast<Milliseconds>(time - _time);
    return Milliseconds::max();
}
References _eventMap, and _time.
Referenced by HasTimeUntilEvent().
HasTimeUntilEvent()
bool EventMap::HasTimeUntilEvent (EventId eventId) const
{
    return GetTimeUntilEvent(eventId) != Milliseconds::max();
}
References GetTimeUntilEvent().
Referenced by BattlegroundWS::GetAssaultSpellId(), boss_twilight_halion::boss_twilight_halionAI::KilledUnit(), and instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript::OnUnitDeath().
IsInPhase()
bool EventMap::IsInPhase (PhaseIndex phase) const
{
    return phase <= sizeof(PhaseIndex) * 8 && (!phase || _phaseMask & PhaseMask(1u << (phase - 1u)));
}
References _phaseMask.
Referenced by npc_coren_direbrew::DamageTaken(), npc_coren_direbrew::MoveInLineOfSight(), and npc_coren_direbrew::UpdateAI().
RemovePhase()
void EventMap::RemovePhase (PhaseIndex phase)
{
    if (phase && phase <= sizeof(PhaseMask) * 8)
        _phaseMask &= PhaseMask(~(1u << (phase - 1u)));
}
References _phaseMask.
Repeat() [1/2]
void EventMap::Repeat (Milliseconds minTime, Milliseconds maxTime)
{
    Repeat(randtime(minTime, maxTime));
}
References randtime(), and Repeat().
Repeat() [2/2]
void EventMap::Repeat (Milliseconds time)
{
    _eventMap.emplace(_time + time, _lastEvent);
}
References _eventMap, _lastEvent, and _time.
Referenced by Repeat(), instance_ulduar::instance_ulduar_InstanceMapScript::Update(), boss_ragnaros::boss_ragnarosAI::UpdateAI(), npc_coren_direbrew::UpdateAI(), npc_arthas::npc_arthasAI::UpdateAI(), boss_sartharion::boss_sartharionAI::UpdateAI(), npc_rimefang::npc_rimefangAI::UpdateAI(), npc_naxxramas_trigger::UpdateAI(), npc_spark_of_ionar::UpdateAI(), npc_frozen_core::UpdateAI(), and npc_ahune_bunny::UpdateAI().
RescheduleEvent() [1/2]
void EventMap::RescheduleEvent (EventId eventId, Milliseconds minTime, Milliseconds maxTime, GroupIndex group = 0u, PhaseIndex phase = 0u)
{
    CancelEvent(eventId);
    ScheduleEvent(eventId, randtime(minTime, maxTime), group, phase);
}
References CancelEvent(), randtime(), and ScheduleEvent().
RescheduleEvent() [2/2]
void EventMap::RescheduleEvent (EventId eventId, Milliseconds time, GroupIndex group = 0u, PhaseIndex phase = 0u)
{
    CancelEvent(eventId);
    ScheduleEvent(eventId, time, group, phase);
}
References CancelEvent(), and ScheduleEvent().
Referenced by instance_naxxramas::ActivateWingPortal(), BattlegroundAB::CreateBanner(), npc_kinetic_bomb::npc_kinetic_bombAI::DoAction(), boss_sartharion_dragonAI::DoAction(), BattlegroundEY::EventPlayerCapturedFlag(), BattlegroundWS::EventPlayerClickedOnFlag(), BattlegroundAB::EventPlayerClickedOnFlag(), BattlegroundEY::EventPlayerDroppedFlag(), BattlegroundWS::EventPlayerDroppedFlag(), instance_ulduar::instance_ulduar_InstanceMapScript::OnPlayerEnter(), boss_halion::boss_halionAI::Reset(), npc_kinetic_bomb::npc_kinetic_bombAI::Reset(), instance_naxxramas::SetBossState(), instance_ulduar::instance_ulduar_InstanceMapScript::SetData(), boss_ragnaros::boss_ragnarosAI::UpdateAI(), npc_strangulate_vehicle::npc_strangulate_vehicleAI::UpdateAI(), and npc_shandy_dalaran::npc_shandy_dalaranAI::UpdateAI().
Reset()
void EventMap::Reset ()
{
    _eventMap.clear();
    _time = TimePoint::min();
    _phaseMask = 0;
}
References _eventMap, _phaseMask, and _time.
Referenced by npc_terenas_menethil::npc_terenas_menethilAI::DamageTaken(), npc_magister_aledis::DamageTaken(), boss_kirtonos_the_herald::boss_kirtonos_the_heraldAI::DoAction(), npc_halion_controller::npc_halion_controllerAI::DoAction(), npc_strangulate_vehicle::npc_strangulate_vehicleAI::DoAction(), npc_terenas_menethil::npc_terenas_menethilAI::DoAction(), boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI::DoAction(), npc_the_lich_king_controller::npc_the_lich_king_controllerAI::DoAction(), npc_frozen_core::DoAction(), npc_ahune_bunny::DoAction(), npc_spark_of_ionar::DoAction(), BattlegroundAB::EndBattleground(), npc_valkyr_shadowguard::npc_valkyr_shadowguardAI::GoSiphon(), boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI::HealReceived(), BattlegroundAB::Init(), BattlegroundEY::Init(), BattlegroundWS::Init(), instance_old_hillsbrad::instance_old_hillsbrad_InstanceMapScript::Initialize(), instance_ulduar::instance_ulduar_InstanceMapScript::Initialize(), npc_millhouse_manastorm::npc_millhouse_manastormAI::InitializeAI(), instance_naxxramas::instance_naxxramas(), npc_strangulate_vehicle::npc_strangulate_vehicleAI::IsSummonedBy(), boss_ambassador_flamelash::boss_ambassador_flamelashAI::JustDied(), boss_ragnaros::boss_ragnarosAI::JustDied(), npc_coren_direbrew::JustDied(), npc_spinestalker::npc_spinestalkerAI::JustDied(), npc_rimefang::npc_rimefangAI::JustDied(), npc_rotting_frost_giant::npc_rotting_frost_giantAI::JustDied(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::JustEngagedWith(), npc_tiger_matriarch::npc_tiger_matriarchAI::JustEngagedWith(), npc_baltharus_the_warborn_clone::npc_baltharus_the_warborn_cloneAI::JustEngagedWith(), npc_onyx_flamecaller::npc_onyx_flamecallerAI::JustEngagedWith(), boss_twilight_halion::boss_twilight_halionAI::JustEngagedWith(), npc_gunship_boarding_leader::npc_gunship_boarding_leaderAI::JustEngagedWith(), npc_pet_shaman_earth_elemental::JustEngagedWith(), npc_pet_shaman_fire_elemental::JustEngagedWith(), npc_valkyr_shadowguard::npc_valkyr_shadowguardAI::MovementInform(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::npc_high_overlord_saurfang_igbAI(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::npc_muradin_bronzebeard_igbAI(), npc_valkyr_shadowguard::npc_valkyr_shadowguardAI::npc_valkyr_shadowguardAI(), boss_ambassador_flamelash::boss_ambassador_flamelashAI::Reset(), boss_vaelastrasz::boss_vaelAI::Reset(), boss_ragnaros::boss_ragnarosAI::Reset(), npc_lady_sylvanas_windrunner::npc_lady_sylvanas_windrunnerAI::Reset(), npc_coren_direbrew::Reset(), npc_arthas::npc_arthasAI::Reset(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::Reset(), npc_magwin::npc_magwinAI::Reset(), npc_stillpine_capitive::npc_stillpine_capitiveAI::Reset(), npc_tharnarian::npc_tharnarianAI::Reset(), boss_sartharion::boss_sartharionAI::Reset(), npc_xerestrasza::npc_xerestraszaAI::Reset(), boss_halion::boss_halionAI::Reset(), boss_twilight_halion::boss_twilight_halionAI::Reset(), npc_halion_controller::npc_halion_controllerAI::Reset(), boss_trollgore::boss_trollgoreAI::Reset(), boss_moorabi::boss_moorabiAI::Reset(), npc_blood_queen_lana_thel::npc_blood_queen_lana_thelAI::Reset(), npc_kinetic_bomb::npc_kinetic_bombAI::Reset(), npc_high_overlord_saurfang_icc::npc_high_overlord_saurfangAI::Reset(), npc_muradin_bronzebeard_icc::npc_muradin_bronzebeard_iccAI::Reset(), npc_spinestalker::npc_spinestalkerAI::Reset(), npc_rimefang::npc_rimefangAI::Reset(), npc_sindragosa_trash::npc_sindragosa_trashAI::Reset(), npc_tirion_fordring_tft::npc_tirion_fordringAI::Reset(), npc_shambling_horror_icc::npc_shambling_horror_iccAI::Reset(), npc_raging_spirit::npc_raging_spiritAI::Reset(), npc_spirit_warden::npc_spirit_wardenAI::Reset(), boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI::Reset(), npc_the_lich_king_controller::npc_the_lich_king_controllerAI::Reset(), npc_risen_archmage::npc_risen_archmageAI::Reset(), npc_valithria_cloud::npc_valithria_cloudAI::Reset(), npc_blazing_skeleton::npc_blazing_skeletonAI::Reset(), npc_gluttonous_abomination::npc_gluttonous_abominationAI::Reset(), npc_highlord_tirion_fordring_lh::npc_highlord_tirion_fordringAI::Reset(), npc_rotting_frost_giant::npc_rotting_frost_giantAI::Reset(), npc_crok_scourgebane::npc_crok_scourgebaneAI::Reset(), npc_frostwing_vrykul::npc_frostwing_vrykulAI::Reset(), npc_arthas_teleport_visual::npc_arthas_teleport_visualAI::Reset(), npc_naxxramas_trigger::Reset(), npc_enslaved_proto_drake::Reset(), boss_svala::boss_svalaAI::Reset(), npc_bloodmage_laurith::npc_bloodmage_laurithAI::Reset(), npc_shandy_dalaran::npc_shandy_dalaranAI::Reset(), npc_torturer_lecraft::npc_torturer_lecraftAI::Reset(), npc_earthen_ring_flamecaller::Reset(), boss_wrath_scryer_soccothrates::Reset(), npc_shandy_dalaran::npc_shandy_dalaranAI::SetData(), npc_cameron::sOnGameEvent(), npc_rabid_thistle_bear::npc_rabid_thistle_bearAI::SpellHit(), npc_simon_bunny::npc_simon_bunnyAI::StartGame(), npc_blood_queen_lana_thel::npc_blood_queen_lana_thelAI::UpdateAI(), npc_terenas_menethil::npc_terenas_menethilAI::UpdateAI(), npc_shandy_dalaran::npc_shandy_dalaranAI::UpdateAI(), and npc_ahune_bunny::UpdateAI().
ScheduleEvent() [1/2]
void EventMap::ScheduleEvent (EventId eventId, Milliseconds minTime, Milliseconds maxTime, GroupIndex group = 0u, PhaseIndex phase = 0u)
{
    ScheduleEvent(eventId, randtime(minTime, maxTime), group, phase);
}
References randtime(), and ScheduleEvent().
ScheduleEvent() [2/2]
void EventMap::ScheduleEvent (EventId eventId, Milliseconds time, GroupIndex group = 0u, PhaseIndex phase = 0u)
{
    if (group > sizeof(GroupMask) * 8)
        return;
    if (phase > sizeof(PhaseMask) * 8)
        return;
    _eventMap.emplace(_time + time, Event(eventId, group, phase));
}
References _eventMap, and _time.
Referenced by go_suppression_device::go_suppression_deviceAI::Activate(), boss_vaelastrasz::boss_vaelAI::BeginSpeech(), npc_commander_eligor_dawnbringer::npc_commander_eligor_dawnbringerAI::ChangeImage(), instance_old_hillsbrad::instance_old_hillsbrad_InstanceMapScript::CleanupInstance(), npc_terenas_menethil::npc_terenas_menethilAI::DamageTaken(), npc_crok_scourgebane::npc_crok_scourgebaneAI::DamageTaken(), npc_magister_aledis::DamageTaken(), DelayEventsToMax(), go_suppression_device::go_suppression_deviceAI::DoAction(), boss_ragnaros::boss_ragnarosAI::DoAction(), boss_kirtonos_the_herald::boss_kirtonos_the_heraldAI::DoAction(), npc_coren_direbrew::DoAction(), npc_xerestrasza::npc_xerestraszaAI::DoAction(), npc_halion_controller::npc_halion_controllerAI::DoAction(), npc_high_overlord_saurfang_icc::npc_high_overlord_saurfangAI::DoAction(), npc_muradin_bronzebeard_icc::npc_muradin_bronzebeard_iccAI::DoAction(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::DoAction(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::DoAction(), npc_tirion_fordring_tft::npc_tirion_fordringAI::DoAction(), npc_terenas_menethil::npc_terenas_menethilAI::DoAction(), boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI::DoAction(), npc_the_lich_king_controller::npc_the_lich_king_controllerAI::DoAction(), npc_frost_freeze_trap::npc_frost_freeze_trapAI::DoAction(), npc_crok_scourgebane::npc_crok_scourgebaneAI::DoAction(), npc_ioc_gunship_captain::npc_ioc_gunship_captainAI::DoAction(), npc_frozen_core::DoAction(), npc_ahune_bunny::DoAction(), npc_simon_bunny::npc_simon_bunnyAI::DoAction(), boss_ambassador_flamelash::boss_ambassador_flamelashAI::DoAction(), npc_arthas::npc_arthasAI::DoAction(), BattlegroundWS::EventPlayerCapturedFlag(), go_brewfest_music::go_brewfest_musicAI::go_brewfest_musicAI(), go_darkmoon_faire_music::go_darkmoon_faire_musicAI::go_darkmoon_faire_musicAI(), go_l70_etc_music::go_l70_etc_musicAI::go_l70_etc_musicAI(), go_midsummer_music::go_midsummer_musicAI::go_midsummer_musicAI(), go_pirate_day_music::go_pirate_day_musicAI::go_pirate_day_musicAI(), npc_valkyr_shadowguard::npc_valkyr_shadowguardAI::GoSiphon(), go_gilded_brazier::go_gilded_brazierAI::GossipHello(), npc_valkyr_shadowguard::npc_valkyr_shadowguardAI::HandleSpeedChangeIfNeeded(), boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI::HealReceived(), npc_jenny::Initialize(), go_bear_trap::go_bear_trapAI::Initialize(), go_suppression_device::go_suppression_deviceAI::InitializeAI(), npc_millhouse_manastorm::npc_millhouse_manastormAI::InitializeAI(), npc_strangulate_vehicle::npc_strangulate_vehicleAI::IsSummonedBy(), boss_ambassador_flamelash::boss_ambassador_flamelashAI::JustEngagedWith(), boss_doomrel::boss_doomrelAI::JustEngagedWith(), npc_blackhand_incarcerator::npc_blackhand_incarceratorAI::JustEngagedWith(), npc_sentinel_leader::JustEngagedWith(), npc_sentinel_infiltrator::JustEngagedWith(), npc_lady_sylvanas_windrunner::npc_lady_sylvanas_windrunnerAI::JustEngagedWith(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::JustEngagedWith(), npc_tiger_matriarch::npc_tiger_matriarchAI::JustEngagedWith(), npc_baltharus_the_warborn_clone::npc_baltharus_the_warborn_cloneAI::JustEngagedWith(), npc_onyx_flamecaller::npc_onyx_flamecallerAI::JustEngagedWith(), boss_twilight_halion::boss_twilight_halionAI::JustEngagedWith(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::JustEngagedWith(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::JustEngagedWith(), npc_gunship_boarding_leader::npc_gunship_boarding_leaderAI::JustEngagedWith(), npc_counselor_talbot::npc_counselor_talbotAI::JustEngagedWith(), npc_pet_shaman_earth_elemental::JustEngagedWith(), npc_pet_shaman_fire_elemental::JustEngagedWith(), boss_sartharion::boss_sartharionAI::JustEngagedWith(), boss_halion::boss_halionAI::JustEngagedWith(), npc_torturer_lecraft::npc_torturer_lecraftAI::JustEngagedWith(), boss_twilight_halion::boss_twilight_halionAI::KilledUnit(), npc_coren_direbrew::MoveInLineOfSight(), npc_blood_queen_lana_thel::npc_blood_queen_lana_thelAI::MoveInLineOfSight(), npc_jenny::MoveInLineOfSight(), boss_kirtonos_the_herald::boss_kirtonos_the_heraldAI::MovementInform(), npc_sentinel_leader::MovementInform(), npc_sentinel_infiltrator::MovementInform(), npc_stillpine_capitive::npc_stillpine_capitiveAI::MovementInform(), npc_high_overlord_saurfang_icc::npc_high_overlord_saurfangAI::MovementInform(), npc_muradin_bronzebeard_icc::npc_muradin_bronzebeard_iccAI::MovementInform(), npc_tirion_fordring_tft::npc_tirion_fordringAI::MovementInform(), npc_valkyr_shadowguard::npc_valkyr_shadowguardAI::MovementInform(), npc_commander_eligor_dawnbringer::npc_commander_eligor_dawnbringerAI::MovementInform(), npc_thassarian2::npc_thassarian2AI::MovementInform(), npc_valkyr_shadowguard::npc_valkyr_shadowguardAI::npc_valkyr_shadowguardAI(), instance_naxxramas::OnPlayerEnter(), instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript::OnUnitDeath(), npc_cameron::PathEndReached(), npc_eastvale_peasent::PathEndReached(), npc_partygoer_pather::PathEndReached(), BattlegroundAB::PostUpdateImpl(), BattlegroundDS::PostUpdateImpl(), BattlegroundEY::PostUpdateImpl(), BattlegroundWS::PostUpdateImpl(), npc_hidden_cultist::npc_hidden_cultistAI::PreScript(), npc_lake_frog::npc_lake_frogAI::ReceiveEmote(), RescheduleEvent(), RescheduleEvent(), npc_supervisor_raelen::Reset(), npc_partygoer_pather::Reset(), npc_partygoer::Reset(), npc_varian_wrynn::npc_varian_wrynnAI::Reset(), npc_jaina_proudmoore_bfu::npc_jaina_proudmoore_bfuAI::Reset(), boss_blight_worm::boss_blight_wormAI::Reset(), npc_thrall_bfu::npc_thrall_bfuAI::Reset(), npc_lady_sylvanas_windrunner_bfu::npc_lady_sylvanas_windrunner_bfuAI::Reset(), npc_zulian_prowler::npc_zulian_prowlerAI::Reset(), boss_trollgore::boss_trollgoreAI::Reset(), boss_moorabi::boss_moorabiAI::Reset(), npc_spinestalker::npc_spinestalkerAI::Reset(), npc_rimefang::npc_rimefangAI::Reset(), npc_sindragosa_trash::npc_sindragosa_trashAI::Reset(), npc_shambling_horror_icc::npc_shambling_horror_iccAI::Reset(), npc_raging_spirit::npc_raging_spiritAI::Reset(), npc_spirit_warden::npc_spirit_wardenAI::Reset(), npc_risen_archmage::npc_risen_archmageAI::Reset(), npc_valithria_cloud::npc_valithria_cloudAI::Reset(), npc_blazing_skeleton::npc_blazing_skeletonAI::Reset(), npc_gluttonous_abomination::npc_gluttonous_abominationAI::Reset(), npc_rotting_frost_giant::npc_rotting_frost_giantAI::Reset(), npc_crok_scourgebane::npc_crok_scourgebaneAI::Reset(), npc_frostwing_vrykul::npc_frostwing_vrykulAI::Reset(), npc_arthas_teleport_visual::npc_arthas_teleport_visualAI::Reset(), npc_naxxramas_trigger::Reset(), npc_spark_of_ionar::Reset(), npc_enslaved_proto_drake::Reset(), npc_thassarian::npc_thassarianAI::Reset(), npc_commander_eligor_dawnbringer::npc_commander_eligor_dawnbringerAI::Reset(), ScheduleEvent(), instance_naxxramas::SetBossState(), instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript::SetBossState(), boss_svala::boss_svalaAI::SetData(), npc_blackhand_incarcerator::npc_blackhand_incarceratorAI::SetData(), instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript::SetData(), instance_sunken_temple::instance_sunken_temple_InstanceMapScript::SetData(), instance_old_hillsbrad::instance_old_hillsbrad_InstanceMapScript::SetData(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::SetData(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::SetData(), npc_highlord_tirion_fordring_lh::npc_highlord_tirion_fordringAI::SetData(), npc_shandy_dalaran::npc_shandy_dalaranAI::SetData(), npc_simon_bunny::npc_simon_bunnyAI::SetData(), npc_supervisor_raelen::SetData(), npc_thassarian2::npc_thassarian2AI::SetData(), npc_tharnarian::npc_tharnarianAI::SetGUID(), boss_ragnaros::boss_ragnarosAI::SetGUID(), npc_lady_sylvanas_windrunner::npc_lady_sylvanas_windrunnerAI::SetGUID(), npc_bloodmage_laurith::npc_bloodmage_laurithAI::SetGUID(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::sGossipSelect(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::sGossipSelect(), npc_crusade_recruit::npc_crusade_recruitAI::sGossipSelect(), npc_cameron::sOnGameEvent(), npc_rabid_thistle_bear::npc_rabid_thistle_bearAI::SpellHit(), npc_earthen_ring_flamecaller::SpellHit(), npc_venture_co_straggler::npc_venture_co_stragglerAI::SpellHit(), npc_magwin::npc_magwinAI::sQuestAccept(), npc_magister_aledis::StartFight(), npc_simon_bunny::npc_simon_bunnyAI::StartGame(), BattlegroundAB::StartingEventOpenDoors(), BattlegroundDS::StartingEventOpenDoors(), BattlegroundEY::StartingEventOpenDoors(), BattlegroundWS::StartingEventOpenDoors(), npc_coren_direbrew::SummonedCreatureDies(), boss_sartharion::boss_sartharionAI::SummonLavaWaves(), boss_ambassador_flamelash::boss_ambassador_flamelashAI::SummonSpirits(), instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript::Update(), instance_naxxramas::Update(), go_bear_trap::go_bear_trapAI::UpdateAI(), go_gilded_brazier::go_gilded_brazierAI::UpdateAI(), go_bells::go_bellsAI::UpdateAI(), boss_ambassador_flamelash::boss_ambassador_flamelashAI::UpdateAI(), boss_doomrel::boss_doomrelAI::UpdateAI(), npc_blackhand_incarcerator::npc_blackhand_incarceratorAI::UpdateAI(), npc_vaelastrasz_the_red::npc_vaelastrasz_the_redAI::UpdateAI(), go_suppression_device::go_suppression_deviceAI::UpdateAI(), boss_vaelastrasz::boss_vaelAI::UpdateAI(), boss_ragnaros::boss_ragnarosAI::UpdateAI(), npc_supervisor_raelen::UpdateAI(), npc_eastvale_peasent::UpdateAI(), npc_partygoer_pather::UpdateAI(), npc_partygoer::UpdateAI(), npc_sentinel_leader::UpdateAI(), npc_sentinel_infiltrator::UpdateAI(), npc_lady_sylvanas_windrunner::npc_lady_sylvanas_windrunnerAI::UpdateAI(), npc_varian_wrynn::npc_varian_wrynnAI::UpdateAI(), npc_jaina_proudmoore_bfu::npc_jaina_proudmoore_bfuAI::UpdateAI(), boss_blight_worm::boss_blight_wormAI::UpdateAI(), npc_thrall_bfu::npc_thrall_bfuAI::UpdateAI(), npc_lady_sylvanas_windrunner_bfu::npc_lady_sylvanas_windrunner_bfuAI::UpdateAI(), npc_coren_direbrew::UpdateAI(), npc_rabid_thistle_bear::npc_rabid_thistle_bearAI::UpdateAI(), npc_tharnarian::npc_tharnarianAI::UpdateAI(), npc_tiger_matriarch::npc_tiger_matriarchAI::UpdateAI(), npc_baltharus_the_warborn_clone::npc_baltharus_the_warborn_cloneAI::UpdateAI(), boss_twilight_halion::boss_twilight_halionAI::UpdateAI(), npc_halion_controller::npc_halion_controllerAI::UpdateAI(), boss_trollgore::boss_trollgoreAI::UpdateAI(), boss_moorabi::boss_moorabiAI::UpdateAI(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::UpdateAI(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::UpdateAI(), npc_gunship_boarding_leader::npc_gunship_boarding_leaderAI::UpdateAI(), npc_spinestalker::npc_spinestalkerAI::UpdateAI(), npc_rimefang::npc_rimefangAI::UpdateAI(), npc_sindragosa_trash::npc_sindragosa_trashAI::UpdateAI(), npc_tirion_fordring_tft::npc_tirion_fordringAI::UpdateAI(), npc_shambling_horror_icc::npc_shambling_horror_iccAI::UpdateAI(), npc_raging_spirit::npc_raging_spiritAI::UpdateAI(), npc_valkyr_shadowguard::npc_valkyr_shadowguardAI::UpdateAI(), npc_terenas_menethil::npc_terenas_menethilAI::UpdateAI(), npc_spirit_warden::npc_spirit_wardenAI::UpdateAI(), boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI::UpdateAI(), npc_risen_archmage::npc_risen_archmageAI::UpdateAI(), npc_valithria_cloud::npc_valithria_cloudAI::UpdateAI(), npc_blazing_skeleton::npc_blazing_skeletonAI::UpdateAI(), npc_gluttonous_abomination::npc_gluttonous_abominationAI::UpdateAI(), npc_rotting_frost_giant::npc_rotting_frost_giantAI::UpdateAI(), npc_frost_freeze_trap::npc_frost_freeze_trapAI::UpdateAI(), npc_crok_scourgebane::npc_crok_scourgebaneAI::UpdateAI(), npc_frostwing_vrykul::npc_frostwing_vrykulAI::UpdateAI(), npc_arthas_teleport_visual::npc_arthas_teleport_visualAI::UpdateAI(), npc_ioc_gunship_captain::npc_ioc_gunship_captainAI::UpdateAI(), npc_enslaved_proto_drake::UpdateAI(), boss_svala::boss_svalaAI::UpdateAI(), npc_hidden_cultist::npc_hidden_cultistAI::UpdateAI(), npc_bloodmage_laurith::npc_bloodmage_laurithAI::UpdateAI(), npc_thassarian2::npc_thassarian2AI::UpdateAI(), npc_counselor_talbot::npc_counselor_talbotAI::UpdateAI(), npc_shandy_dalaran::npc_shandy_dalaranAI::UpdateAI(), npc_commander_eligor_dawnbringer::npc_commander_eligor_dawnbringerAI::UpdateAI(), npc_torturer_lecraft::npc_torturer_lecraftAI::UpdateAI(), npc_venture_co_straggler::npc_venture_co_stragglerAI::UpdateAI(), npc_lake_frog::npc_lake_frogAI::UpdateAI(), npc_crusade_recruit::npc_crusade_recruitAI::UpdateAI(), npc_ahune_bunny::UpdateAI(), npc_earthen_ring_flamecaller::UpdateAI(), npc_millhouse_manastorm::npc_millhouse_manastormAI::UpdateAI(), npc_simon_bunny::npc_simon_bunnyAI::UpdateAI(), npc_magister_aledis::UpdateAI(), npc_pet_shaman_earth_elemental::UpdateAI(), npc_pet_shaman_fire_elemental::UpdateAI(), go_l70_etc_music::go_l70_etc_musicAI::UpdateAI(), go_brewfest_music::go_brewfest_musicAI::UpdateAI(), go_pirate_day_music::go_pirate_day_musicAI::UpdateAI(), go_darkmoon_faire_music::go_darkmoon_faire_musicAI::UpdateAI(), go_midsummer_music::go_midsummer_musicAI::UpdateAI(), npc_halion_controller::npc_halion_controllerAI::UpdateCorporeality(), npc_magwin::npc_magwinAI::UpdateEscortAI(), npc_onyx_flamecaller::npc_onyx_flamecallerAI::UpdateEscortAI(), npc_jenny::UpdateFollowerAI(), npc_arthas::npc_arthasAI::WaypointReached(), and npc_magwin::npc_magwinAI::WaypointReached().
SetPhase()
void EventMap::SetPhase (PhaseIndex phase)
{
    if (!phase)
        _phaseMask = 0;
    else if (phase <= sizeof(PhaseMask) * 8)
        _phaseMask = PhaseMask(1u << (phase - 1u));
}
References _phaseMask.
Referenced by npc_coren_direbrew::DamageTaken(), boss_ragnaros::boss_ragnarosAI::DoAction(), npc_coren_direbrew::DoAction(), npc_high_overlord_saurfang_icc::npc_high_overlord_saurfangAI::DoAction(), npc_muradin_bronzebeard_icc::npc_muradin_bronzebeard_iccAI::DoAction(), npc_ahune_bunny::DoAction(), boss_ragnaros::boss_ragnarosAI::HandleEmerge(), npc_coren_direbrew::MoveInLineOfSight(), npc_blood_queen_lana_thel::npc_blood_queen_lana_thelAI::MoveInLineOfSight(), boss_ragnaros::boss_ragnarosAI::Reset(), npc_coren_direbrew::Reset(), boss_ragnaros::boss_ragnarosAI::UpdateAI(), and npc_ahune_bunny::UpdateAI().
Update() [1/2]
void EventMap::Update (Milliseconds time) inline
    {
        _time += time;
    }
References _time.
Update() [2/2]
void EventMap::Update (uint32 time) inline
    {
        Update(Milliseconds(time));
    }
References Update().
Referenced by BattlegroundAB::PostUpdateImpl(), BattlegroundDS::PostUpdateImpl(), BattlegroundEY::PostUpdateImpl(), BattlegroundWS::PostUpdateImpl(), instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript::Update(), instance_sunken_temple::instance_sunken_temple_InstanceMapScript::Update(), instance_old_hillsbrad::instance_old_hillsbrad_InstanceMapScript::Update(), instance_naxxramas::Update(), instance_ulduar::instance_ulduar_InstanceMapScript::Update(), Update(), go_bear_trap::go_bear_trapAI::UpdateAI(), go_gilded_brazier::go_gilded_brazierAI::UpdateAI(), go_bells::go_bellsAI::UpdateAI(), boss_sartharion_dragonAI::UpdateAI(), boss_ambassador_flamelash::boss_ambassador_flamelashAI::UpdateAI(), boss_doomrel::boss_doomrelAI::UpdateAI(), npc_blackhand_incarcerator::npc_blackhand_incarceratorAI::UpdateAI(), npc_vaelastrasz_the_red::npc_vaelastrasz_the_redAI::UpdateAI(), go_suppression_device::go_suppression_deviceAI::UpdateAI(), boss_vaelastrasz::boss_vaelAI::UpdateAI(), boss_ragnaros::boss_ragnarosAI::UpdateAI(), boss_kirtonos_the_herald::boss_kirtonos_the_heraldAI::UpdateAI(), npc_cameron::UpdateAI(), npc_supervisor_raelen::UpdateAI(), npc_eastvale_peasent::UpdateAI(), npc_partygoer_pather::UpdateAI(), npc_partygoer::UpdateAI(), npc_sentinel_leader::UpdateAI(), npc_sentinel_infiltrator::UpdateAI(), npc_lady_sylvanas_windrunner::npc_lady_sylvanas_windrunnerAI::UpdateAI(), npc_varian_wrynn::npc_varian_wrynnAI::UpdateAI(), npc_jaina_proudmoore_bfu::npc_jaina_proudmoore_bfuAI::UpdateAI(), boss_blight_worm::boss_blight_wormAI::UpdateAI(), npc_thrall_bfu::npc_thrall_bfuAI::UpdateAI(), npc_lady_sylvanas_windrunner_bfu::npc_lady_sylvanas_windrunner_bfuAI::UpdateAI(), npc_zulian_prowler::npc_zulian_prowlerAI::UpdateAI(), npc_coren_direbrew::UpdateAI(), npc_arthas::npc_arthasAI::UpdateAI(), npc_stillpine_capitive::npc_stillpine_capitiveAI::UpdateAI(), npc_rabid_thistle_bear::npc_rabid_thistle_bearAI::UpdateAI(), npc_tharnarian::npc_tharnarianAI::UpdateAI(), npc_tiger_matriarch::npc_tiger_matriarchAI::UpdateAI(), boss_sartharion::boss_sartharionAI::UpdateAI(), npc_baltharus_the_warborn_clone::npc_baltharus_the_warborn_cloneAI::UpdateAI(), npc_xerestrasza::npc_xerestraszaAI::UpdateAI(), boss_halion::boss_halionAI::UpdateAI(), boss_twilight_halion::boss_twilight_halionAI::UpdateAI(), npc_halion_controller::npc_halion_controllerAI::UpdateAI(), boss_trollgore::boss_trollgoreAI::UpdateAI(), boss_moorabi::boss_moorabiAI::UpdateAI(), npc_blood_queen_lana_thel::npc_blood_queen_lana_thelAI::UpdateAI(), npc_kinetic_bomb::npc_kinetic_bombAI::UpdateAI(), npc_high_overlord_saurfang_icc::npc_high_overlord_saurfangAI::UpdateAI(), npc_muradin_bronzebeard_icc::npc_muradin_bronzebeard_iccAI::UpdateAI(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::UpdateAI(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::UpdateAI(), npc_gunship_boarding_leader::npc_gunship_boarding_leaderAI::UpdateAI(), npc_gunship_boarding_add::npc_gunship_boarding_add_realAI::UpdateAI(), npc_spinestalker::npc_spinestalkerAI::UpdateAI(), npc_rimefang::npc_rimefangAI::UpdateAI(), npc_sindragosa_trash::npc_sindragosa_trashAI::UpdateAI(), npc_tirion_fordring_tft::npc_tirion_fordringAI::UpdateAI(), npc_shambling_horror_icc::npc_shambling_horror_iccAI::UpdateAI(), npc_raging_spirit::npc_raging_spiritAI::UpdateAI(), npc_valkyr_shadowguard::npc_valkyr_shadowguardAI::UpdateAI(), npc_strangulate_vehicle::npc_strangulate_vehicleAI::UpdateAI(), npc_terenas_menethil::npc_terenas_menethilAI::UpdateAI(), npc_spirit_warden::npc_spirit_wardenAI::UpdateAI(), boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI::UpdateAI(), npc_the_lich_king_controller::npc_the_lich_king_controllerAI::UpdateAI(), npc_risen_archmage::npc_risen_archmageAI::UpdateAI(), npc_valithria_cloud::npc_valithria_cloudAI::UpdateAI(), npc_blazing_skeleton::npc_blazing_skeletonAI::UpdateAI(), npc_gluttonous_abomination::npc_gluttonous_abominationAI::UpdateAI(), npc_highlord_tirion_fordring_lh::npc_highlord_tirion_fordringAI::UpdateAI(), npc_rotting_frost_giant::npc_rotting_frost_giantAI::UpdateAI(), npc_frost_freeze_trap::npc_frost_freeze_trapAI::UpdateAI(), npc_crok_scourgebane::npc_crok_scourgebaneAI::UpdateAI(), npc_frostwing_vrykul::npc_frostwing_vrykulAI::UpdateAI(), npc_arthas_teleport_visual::npc_arthas_teleport_visualAI::UpdateAI(), npc_ioc_gunship_captain::npc_ioc_gunship_captainAI::UpdateAI(), npc_naxxramas_trigger::UpdateAI(), npc_spark_of_ionar::UpdateAI(), npc_enslaved_proto_drake::UpdateAI(), boss_svala::boss_svalaAI::UpdateAI(), npc_hidden_cultist::npc_hidden_cultistAI::UpdateAI(), npc_bloodmage_laurith::npc_bloodmage_laurithAI::UpdateAI(), npc_thassarian::npc_thassarianAI::UpdateAI(), npc_thassarian2::npc_thassarian2AI::UpdateAI(), npc_counselor_talbot::npc_counselor_talbotAI::UpdateAI(), npc_shandy_dalaran::npc_shandy_dalaranAI::UpdateAI(), npc_commander_eligor_dawnbringer::npc_commander_eligor_dawnbringerAI::UpdateAI(), npc_torturer_lecraft::npc_torturer_lecraftAI::UpdateAI(), npc_venture_co_straggler::npc_venture_co_stragglerAI::UpdateAI(), npc_lake_frog::npc_lake_frogAI::UpdateAI(), npc_crusade_recruit::npc_crusade_recruitAI::UpdateAI(), npc_frozen_core::UpdateAI(), npc_ahune_bunny::UpdateAI(), npc_earthen_ring_flamecaller::UpdateAI(), npc_millhouse_manastorm::npc_millhouse_manastormAI::UpdateAI(), npc_simon_bunny::npc_simon_bunnyAI::UpdateAI(), npc_magister_aledis::UpdateAI(), npc_pet_shaman_earth_elemental::UpdateAI(), npc_pet_shaman_fire_elemental::UpdateAI(), go_l70_etc_music::go_l70_etc_musicAI::UpdateAI(), go_brewfest_music::go_brewfest_musicAI::UpdateAI(), go_pirate_day_music::go_pirate_day_musicAI::UpdateAI(), go_darkmoon_faire_music::go_darkmoon_faire_musicAI::UpdateAI(), go_midsummer_music::go_midsummer_musicAI::UpdateAI(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::UpdateEscortAI(), npc_magwin::npc_magwinAI::UpdateEscortAI(), npc_onyx_flamecaller::npc_onyx_flamecallerAI::UpdateEscortAI(), and npc_jenny::UpdateFollowerAI().
Member Data Documentation
_eventMap
EventStore EventMap::_eventMap private
Referenced by CancelEvent(), CancelEventGroup(), DelayEvents(), DelayEvents(), DelayEventsToMax(), Empty(), ExecuteEvent(), GetTimeUntilEvent(), Repeat(), Reset(), and ScheduleEvent().
_lastEvent
Event EventMap::_lastEvent private
Referenced by ExecuteEvent(), and Repeat().
_phaseMask
PhaseMask EventMap::_phaseMask { 0 } private
{ 0 };
Referenced by AddPhase(), ExecuteEvent(), GetPhaseMask(), IsInPhase(), RemovePhase(), Reset(), and SetPhase().
_time
TimePoint EventMap::_time { TimePoint::min() } private
{ TimePoint::min() };
Referenced by DelayEventsToMax(), ExecuteEvent(), GetTimeUntilEvent(), Repeat(), Reset(), ScheduleEvent(), and Update().
The documentation for this class was generated from the following files:
azerothcore-wotlk/src/common/Utilities/EventMap.h
azerothcore-wotlk/src/common/Utilities/EventMap.cpp