AzerothCore Doxygen
GridTerrainUnloader Class Reference
#include "GridTerrainLoader.h"
Public Member Functions
GridTerrainUnloader (MapGridType &grid, Map *map)
void UnloadTerrain ()
Private Attributes
MapGridType & _grid
Map * _map
Detailed Description
Constructor & Destructor Documentation
GridTerrainUnloader()
GridTerrainUnloader::GridTerrainUnloader (MapGridType & grid, Map * map) inline
        : _grid(grid), _map(map) { }
Member Function Documentation
UnloadTerrain()
void GridTerrainUnloader::UnloadTerrain ()
{
    // Only parent maps manage terrain data
    if (_map->GetInstanceId() != 0)
        return;
    VMAP::VMapFactory::createOrGetVMapMgr()->unloadMap(_map->GetId(), _grid.GetX(), _grid.GetY());
    MMAP::MMapFactory::createOrGetMMapMgr()->unloadMap(_map->GetId(), _grid.GetX(), _grid.GetY());
}
References _grid, _map, MMAP::MMapFactory::createOrGetMMapMgr(), VMAP::VMapFactory::createOrGetVMapMgr(), Map::GetId(), Map::GetInstanceId(), MapGrid< GRID_OBJECT_TYPES, FAR_VISIBLE_OBJECT_TYPES >::GetX(), MapGrid< GRID_OBJECT_TYPES, FAR_VISIBLE_OBJECT_TYPES >::GetY(), MMAP::MMapMgr::unloadMap(), and VMAP::VMapMgr2::unloadMap().
Referenced by MapGridManager::UnloadGrid().
Member Data Documentation
_grid
MapGridType& GridTerrainUnloader::_grid private
Referenced by UnloadTerrain().
_map
Map* GridTerrainUnloader::_map private
Referenced by UnloadTerrain().
The documentation for this class was generated from the following files:
azerothcore-wotlk/src/server/game/Grids/GridTerrainLoader.h
azerothcore-wotlk/src/server/game/Grids/GridTerrainLoader.cpp