AzerothCore Doxygen
BattlefieldScript Class Reference
#include "BattlefieldScript.h"
Public Member Functions
bool IsDatabaseBound () const override
virtual void OnBattlefieldPlayerEnterZone (Battlefield *, Player *)
Called when a player enters the battlefield zone, before team-based data assignment. This is the ideal place to reassign a player's team for cross-faction purposes.
virtual void OnBattlefieldPlayerLeaveZone (Battlefield *, Player *)
Called when a player leaves the battlefield zone, after all cleanup. This is the ideal place to restore a player's original team/faction.
virtual void OnBattlefieldPlayerJoinWar (Battlefield *, Player *)
Called after a player has been added to the active war (accepted the invitation).
virtual void OnBattlefieldPlayerLeaveWar (Battlefield *, Player *)
Called after a player has been removed from the active war.
virtual void OnBattlefieldBeforeInvitePlayerToWar (Battlefield *, Player *)
Called inside InvitePlayerToWar after the WillBeKick entry is erased (using the player's current team) and before the player is inserted into m_InvitedPlayers. This is the correct place to reassign a player's effective team for pre-war zone players: the invite bucket write that follows will use the newly assigned team, keeping all subsequent core operations consistent.
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
uint16 GetTotalAvailableHooks ()
Protected Member Functions
BattlefieldScript (const char *name, std::vector< uint16 > enabledHooks=std::vector< uint16 >())
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name, uint16 totalAvailableHooks=0)
virtual ~ScriptObject ()=default
Detailed Description
Constructor & Destructor Documentation
BattlefieldScript()
BattlefieldScript::BattlefieldScript (const char * name, std::vector< uint16 > enabledHooks = std::vector<uint16>()) protected
                                                                                     :
    ScriptObject(name, BATTLEFIELDHOOK_END)
{
    // If empty - enable all available hooks.
    if (enabledHooks.empty())
        for (uint16 i = 0; i < BATTLEFIELDHOOK_END; ++i)
            enabledHooks.emplace_back(i);
    ScriptRegistry<BattlefieldScript>::AddScript(this, std::move(enabledHooks));
}
References ScriptRegistry< TScript >::AddScript(), and BATTLEFIELDHOOK_END.
Member Function Documentation
IsDatabaseBound()
bool BattlefieldScript::IsDatabaseBound () const inline override virtual
Reimplemented from ScriptObject.
{ return false; }
OnBattlefieldBeforeInvitePlayerToWar()
virtual void BattlefieldScript::OnBattlefieldBeforeInvitePlayerToWar (Battlefield * , Player *) inline virtual
Called inside InvitePlayerToWar after the WillBeKick entry is erased (using the player's current team) and before the player is inserted into m_InvitedPlayers. This is the correct place to reassign a player's effective team for pre-war zone players: the invite bucket write that follows will use the newly assigned team, keeping all subsequent core operations consistent.
Parameters
bf The Battlefield instance
player The player being invited to war
{ }
Referenced by ScriptMgr::OnBattlefieldBeforeInvitePlayerToWar().
OnBattlefieldPlayerEnterZone()
virtual void BattlefieldScript::OnBattlefieldPlayerEnterZone (Battlefield * , Player *) inline virtual
Called when a player enters the battlefield zone, before team-based data assignment. This is the ideal place to reassign a player's team for cross-faction purposes.
Parameters
bf The Battlefield instance
player The player entering the zone
{ }
Referenced by ScriptMgr::OnBattlefieldPlayerEnterZone().
OnBattlefieldPlayerJoinWar()
virtual void BattlefieldScript::OnBattlefieldPlayerJoinWar (Battlefield * , Player *) inline virtual
Called after a player has been added to the active war (accepted the invitation).
Parameters
bf The Battlefield instance
player The player joining the war
{ }
Referenced by ScriptMgr::OnBattlefieldPlayerJoinWar().
OnBattlefieldPlayerLeaveWar()
virtual void BattlefieldScript::OnBattlefieldPlayerLeaveWar (Battlefield * , Player *) inline virtual
Called after a player has been removed from the active war.
Parameters
bf The Battlefield instance
player The player leaving the war
{ }
Referenced by ScriptMgr::OnBattlefieldPlayerLeaveWar().
OnBattlefieldPlayerLeaveZone()
virtual void BattlefieldScript::OnBattlefieldPlayerLeaveZone (Battlefield * , Player *) inline virtual
Called when a player leaves the battlefield zone, after all cleanup. This is the ideal place to restore a player's original team/faction.
Parameters
bf The Battlefield instance
player The player leaving the zone
{ }
Referenced by ScriptMgr::OnBattlefieldPlayerLeaveZone().
The documentation for this class was generated from the following files:
azerothcore-wotlk/src/server/game/Scripting/ScriptDefines/BattlefieldScript.h
azerothcore-wotlk/src/server/game/Scripting/ScriptDefines/BattlefieldScript.cpp