AzerothCore Doxygen
SpellProcSpellTypeMaskTest Class Reference
Tests for SpellTypeMask calculation based on proc phase.
Protected Member Functions
void SetUp () override
Protected Member Functions inherited from AuraScriptProcTestFixture
void SetUp () override
void TearDown () override
ProcTestContext & Context ()
SpellInfo * CreateSpellInfo (uint32_t id, uint32_t familyName=0, uint32_t familyFlags0=0, uint32_t familyFlags1=0, uint32_t familyFlags2=0)
SpellProcEntry CreateProcEntry ()
ProcEventInfo CreateEventInfo (uint32_t typeMask, uint32_t hitMask, uint32_t spellTypeMask=PROC_SPELL_TYPE_MASK_ALL, uint32_t spellPhaseMask=PROC_SPELL_PHASE_HIT)
bool TestCanProc (SpellProcEntry const &procEntry, uint32_t typeMask, uint32_t hitMask, SpellInfo const *triggerSpell=nullptr)
bool TestSpellFamilyMatch (uint32_t procFamilyName, flag96 const &procFamilyMask, SpellInfo const *triggerSpell)
Static Protected Member Functions
static uint32 CalculateSpellTypeMask (uint32 procPhase, DamageInfo *damageInfo, HealInfo *healInfo, bool hasSpellInfo)
Calculate spellTypeMask the same way ProcSkillsAndAuras does.
Detailed Description
Tests for SpellTypeMask calculation based on proc phase.
These tests verify that the proc system correctly calculates SpellTypeMask for different proc phases. This is critical because:
CAST phase: No damage/heal has occurred yet
HIT phase: Damage/heal info is available
FINISH phase: damageInfo may be null even for damage spells
Regression test for: FINISH phase was incorrectly using NO_DMG_HEAL when damageInfo was null, breaking procs like Killing Machine (51124) that require SpellTypeMask=DAMAGE and SpellPhaseMask=FINISH.
Member Function Documentation
CalculateSpellTypeMask()
static uint32 SpellProcSpellTypeMaskTest::CalculateSpellTypeMask (uint32 procPhase, DamageInfo * damageInfo, HealInfo * healInfo, bool hasSpellInfo) inline static protected
Calculate spellTypeMask the same way ProcSkillsAndAuras does.
This mirrors the logic in Unit::ProcSkillsAndAuras to allow unit testing of the spellTypeMask calculation without needing full Unit objects.
    {
        uint32 spellTypeMask = 0;
        if (procPhase == PROC_SPELL_PHASE_CAST || procPhase == PROC_SPELL_PHASE_FINISH)
        {
            // At CAST phase, no damage/heal has occurred yet - use MASK_ALL
            // At FINISH phase, damageInfo may be null but spell did do damage - use MASK_ALL
            spellTypeMask = PROC_SPELL_TYPE_MASK_ALL;
        }
        else if (healInfo && healInfo->GetHeal())
            spellTypeMask = PROC_SPELL_TYPE_HEAL;
        else if (damageInfo && damageInfo->GetDamage())
            spellTypeMask = PROC_SPELL_TYPE_DAMAGE;
        else if (hasSpellInfo)
            spellTypeMask = PROC_SPELL_TYPE_NO_DMG_HEAL;
        return spellTypeMask;
    }
References DamageInfo::GetDamage(), HealInfo::GetHeal(), PROC_SPELL_PHASE_CAST, PROC_SPELL_PHASE_FINISH, PROC_SPELL_TYPE_DAMAGE, PROC_SPELL_TYPE_HEAL, PROC_SPELL_TYPE_MASK_ALL, and PROC_SPELL_TYPE_NO_DMG_HEAL.
SetUp()
void SpellProcSpellTypeMaskTest::SetUp () inline override protected
    {
        AuraScriptProcTestFixture::SetUp();
    }
References AuraScriptProcTestFixture::SetUp().
The documentation for this class was generated from the following file:
azerothcore-wotlk/src/test/server/game/Spells/SpellProcSpellTypeMaskTest.cpp