AzerothCore Doxygen
BossAI Class Reference
#include "ScriptedCreature.h"
Public Member Functions
BossAI (Creature *creature, uint32 bossId)
~BossAI () override
bool CanRespawn () override
void OnSpellCastFinished (SpellInfo const *spell, SpellFinishReason reason) override
void DamageTaken (Unit *attacker, uint32 &damage, DamageEffectType damagetype, SpellSchoolMask damageSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void JustSummoned (Creature *summon) override
void SummonedCreatureDespawn (Creature *summon) override
void SummonedCreatureDespawnAll () override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void ScheduleHealthCheckEvent (uint32 healthPct, std::function< void()> exec, bool allowedWhileCasting=true)
Executes a function once the creature reaches the defined health point percent.
void ScheduleHealthCheckEvent (std::initializer_list< uint8 > healthPct, std::function< void()> exec, bool allowedWhileCasting=true)
void ProcessHealthCheck ()
void ScheduleEnrageTimer (uint32 spellId, Milliseconds timer, uint8 textId=0)
virtual void ExecuteEvent (uint32)
virtual void ScheduleTasks ()
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER) override
void JustDied (Unit *) override
void JustReachedHome () override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportPlayer (Unit *unit, Position pos)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool IsUniqueTimedEventDone (uint32 id) const
void SetUniqueTimedEventDone (uint32 id)
void ResetUniqueTimedEvent (uint32 id)
void ClearUniqueTimedEventsDone ()
void ScheduleTimedEvent (Milliseconds timerMin, Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0ms, uint32 uniqueId=0)
void ScheduleTimedEvent (Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0ms, uint32 uniqueId=0)
void ScheduleUniqueTimedEvent (Milliseconds timer, std::function< void()> exec, uint32 uniqueId)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
void SetInvincibility (bool apply)
bool IsInvincible () const
void SetAutoAttackAllowed (bool allow)
bool IsAutoAttackAllowed () const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0ms)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureEvade (Creature *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
int32 VisualizeBoundary (uint32 duration, Unit *owner=nullptr, bool fill=false, bool checkZ=false) const
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
virtual void DistancingStarted ()
virtual void DistancingEnded ()
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid const &, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage to any victim (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Public Attributes
float callForHelpRange
InstanceScript *const instance
Public Attributes inherited from ScriptedAI
Creature * me
Protected Member Functions
void _Reset ()
void _JustEngagedWith ()
void _JustDied ()
void _JustReachedHome ()
void _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
void TeleportCheaters ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes
SummonList summons
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Private Attributes
uint32 const _bossId
std::list< HealthCheckEventData > _healthCheckEvents
HealthCheckEventData _nextHealthCheck
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Detailed Description
Constructor & Destructor Documentation
BossAI()
BossAI::BossAI (Creature * creature, uint32 bossId)
                                                : ScriptedAI(creature),
    instance(creature->GetInstanceScript()),
    summons(creature),
    _bossId(bossId),
    _nextHealthCheck(0, { }, false)
{
    callForHelpRange = 0.0f;
    if (instance)
        SetBoundary(instance->GetBossBoundary(bossId));
    // Prevents updating the scheduler's timer while the creature is casting.
    // Clear it in the script if you need it to update while the creature is casting.
    scheduler.SetValidator([this]
    {
        return !me->HasUnitState(UNIT_STATE_CASTING);
    });
}
~BossAI()
BossAI::~BossAI () inline override
{}
Member Function Documentation
_EnterEvadeMode()
void BossAI::_EnterEvadeMode (EvadeReason why = EVADE_REASON_OTHER) protected
{
    CreatureAI::EnterEvadeMode(why);
    if (instance && instance->GetBossState(_bossId) != DONE)
    {
        instance->SetBossState(_bossId, NOT_STARTED);
        instance->SaveToDB();
    }
}
References _bossId, DONE, CreatureAI::EnterEvadeMode(), InstanceScript::GetBossState(), instance, NOT_STARTED, InstanceScript::SaveToDB(), and InstanceScript::SetBossState().
Referenced by boss_tenris_mirkblood::EnterEvadeMode(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::EnterEvadeMode(), EnterEvadeMode(), and boss_zuljin::EnterEvadeMode().
_JustDied()
void BossAI::_JustDied () protected
{
    events.Reset();
    scheduler.CancelAll();
    summons.DespawnAll();
    _healthCheckEvents.clear();
    if (instance)
    {
        instance->SetBossState(_bossId, DONE);
        instance->SaveToDB();
    }
}
References _bossId, _healthCheckEvents, TaskScheduler::CancelAll(), SummonList::DespawnAll(), DONE, instance, InstanceScript::SaveToDB(), CreatureAI::scheduler, InstanceScript::SetBossState(), and summons.
Referenced by boss_high_king_maulgar::DoAction(), JustDied(), boss_halycon::boss_halyconAI::JustDied(), boss_highlord_omokk::boss_highlordomokkAI::JustDied(), boss_mor_grayhoof::JustDied(), boss_quartermaster_zigris::JustDied(), boss_rend_blackhand::boss_rend_blackhandAI::JustDied(), boss_solakar_flamewreath::boss_solakar_flamewreathAI::JustDied(), boss_broodlord::boss_broodlordAI::JustDied(), boss_nefarian::JustDied(), boss_razorgore::boss_razorgoreAI::JustDied(), boss_ragnaros::boss_ragnarosAI::JustDied(), boss_attumen::JustDied(), boss_malchezaar::JustDied(), boss_shade_of_aran::JustDied(), boss_terestian_illhoof::JustDied(), boss_vexallus::JustDied(), boss_apothecary_hummel::boss_apothecary_hummelAI::JustDied(), boss_akilzon::JustDied(), boss_arlokk::boss_arlokkAI::JustDied(), boss_hakkar::boss_hakkarAI::JustDied(), boss_thekal::JustDied(), boss_lieutenant_drake::JustDied(), boss_aeonus::JustDied(), boss_chrono_lord_deja::JustDied(), boss_temporus::JustDied(), boss_isalien::JustDied(), boss_moam::JustDied(), boss_rajaxx::JustDied(), boss_sartura::JustDied(), boss_skeram::JustDied(), boss_amanitar::JustDied(), boss_elder_nadox::JustDied(), boss_volazj::JustDied(), boss_jedoga_shadowseeker::JustDied(), boss_taldaram::JustDied(), boss_sartharion::JustDied(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::JustDied(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::JustDied(), boss_festergut::boss_festergutAI::JustDied(), boss_lord_marrowgar::JustDied(), boss_professor_putricide::boss_professor_putricideAI::JustDied(), boss_rotface::boss_rotfaceAI::JustDied(), boss_sindragosa::boss_sindragosaAI::JustDied(), boss_the_lich_king::boss_the_lich_kingAI::JustDied(), boss_sister_svalna::boss_sister_svalnaAI::JustDied(), boss_malygos::JustDied(), boss_ionar::JustDied(), boss_loken::JustDied(), boss_volkhan::JustDied(), boss_sjonnir::boss_sjonnirAI::JustDied(), boss_vezax::JustDied(), boss_ignis::JustDied(), boss_kologarn::JustDied(), boss_xt002::JustDied(), boss_keleseth::JustDied(), boss_exarch_maladaar::JustDied(), boss_nexusprince_shaffar::JustDied(), boss_tavarok::JustDied(), boss_darkweaver_syth::JustDied(), boss_talon_king_ikiss::JustDied(), boss_ambassador_hellmaw::JustDied(), boss_blackheart_the_inciter::JustDied(), boss_grandmaster_vorpil::JustDied(), boss_ahune::JustDied(), boss_mennu_the_betrayer::JustDied(), boss_hydromancer_thespia::JustDied(), boss_mekgineer_steamrigger::JustDied(), boss_warlord_kalithresh::JustDied(), boss_swamplord_muselek::JustDied(), boss_gruul::JustDied(), boss_high_king_maulgar::JustDied(), boss_kelidan_the_breaker::JustDied(), boss_the_maker::JustDied(), boss_omor_the_unscarred::JustDied(), boss_watchkeeper_gargolmar::JustDied(), boss_grand_warlock_nethekurse::JustDied(), boss_dalliah_the_doomsayer::JustDied(), boss_harbinger_skyriss::JustDied(), boss_zereketh_the_unbound::JustDied(), boss_commander_sarannis::JustDied(), boss_high_botanist_freywinn::JustDied(), boss_thorngrin_the_tender::JustDied(), boss_warp_splinter::JustDied(), boss_gatewatcher_gyrokill::JustDied(), boss_gatewatcher_iron_hand::JustDied(), boss_mechano_lord_capacitus::JustDied(), boss_nethermancer_sepethrea::JustDied(), boss_pathaleon_the_calculator::JustDied(), boss_jarien::JustDied(), boss_sothos::JustDied(), boss_epoch_hunter::JustDied(), and boss_lady_deathwhisper::boss_lady_deathwhisperAI::JustDied().
_JustEngagedWith()
void BossAI::_JustEngagedWith () protected
{
    me->SetCombatPulseDelay(5);
    me->setActive(true);
    DoZoneInCombat();
    ScheduleTasks();
    if (callForHelpRange)
    {
        ScheduleTimedEvent(0ms, [&]
        {
            me->CallForHelp(callForHelpRange);
        }, 2s);
    }
    if (instance)
    {
        // bosses do not respawn, check only on enter combat
        if (!instance->CheckRequiredBosses(_bossId))
        {
            EnterEvadeMode();
            return;
        }
        instance->SetBossState(_bossId, IN_PROGRESS);
    }
}
References _bossId, Creature::CallForHelp(), callForHelpRange, InstanceScript::CheckRequiredBosses(), CreatureAI::DoZoneInCombat(), EnterEvadeMode(), IN_PROGRESS, instance, ScriptedAI::me, ScheduleTasks(), ScriptedAI::ScheduleTimedEvent(), WorldObject::setActive(), InstanceScript::SetBossState(), and Creature::SetCombatPulseDelay().
Referenced by boss_victor_nefarius::boss_victor_nefariusAI::BeginEvent(), JustEngagedWith(), boss_anubshiah::boss_anubshiahAI::JustEngagedWith(), boss_eviscerator::boss_evisceratorAI::JustEngagedWith(), boss_gorosh_the_dervish::boss_gorosh_the_dervishAI::JustEngagedWith(), boss_grizzle::boss_grizzleAI::JustEngagedWith(), boss_hedrum::boss_hedrumAI::JustEngagedWith(), boss_magmus::boss_magmusAI::JustEngagedWith(), boss_moira_bronzebeardAI::JustEngagedWith(), boss_high_priestess_thaurissanAI::JustEngagedWith(), boss_okthor::boss_okthorAI::JustEngagedWith(), boss_drakkisath::boss_drakkisathAI::JustEngagedWith(), boss_gyth::boss_gythAI::JustEngagedWith(), boss_halycon::boss_halyconAI::JustEngagedWith(), boss_highlord_omokk::boss_highlordomokkAI::JustEngagedWith(), boss_mor_grayhoof::JustEngagedWith(), boss_overlord_wyrmthalak::boss_overlordwyrmthalakAI::JustEngagedWith(), boss_rend_blackhand::boss_rend_blackhandAI::JustEngagedWith(), boss_solakar_flamewreath::boss_solakar_flamewreathAI::JustEngagedWith(), boss_the_beast::boss_thebeastAI::JustEngagedWith(), boss_urok_doomhowl::boss_urok_doomhowlAI::JustEngagedWith(), boss_warmaster_voone::boss_warmastervooneAI::JustEngagedWith(), boss_razorgore::boss_razorgoreAI::JustEngagedWith(), boss_baron_geddon::boss_baron_geddonAI::JustEngagedWith(), boss_garr::boss_garrAI::JustEngagedWith(), boss_gehennas::boss_gehennasAI::JustEngagedWith(), boss_lucifron::boss_lucifronAI::JustEngagedWith(), boss_magmadar::boss_magmadarAI::JustEngagedWith(), boss_majordomo::boss_majordomoAI::JustEngagedWith(), boss_ragnaros::boss_ragnarosAI::JustEngagedWith(), boss_shazzrah::boss_shazzrahAI::JustEngagedWith(), boss_sulfuron::boss_sulfuronAI::JustEngagedWith(), boss_malchezaar::JustEngagedWith(), boss_shade_of_aran::JustEngagedWith(), boss_priestess_delrissa::JustEngagedWith(), boss_vexallus::JustEngagedWith(), boss_jarien::JustEngagedWith(), boss_sothos::JustEngagedWith(), boss_akilzon::JustEngagedWith(), boss_zuljin::JustEngagedWith(), boss_arlokk::boss_arlokkAI::JustEngagedWith(), boss_gahzranka::JustEngagedWith(), boss_grilek::boss_grilekAI::JustEngagedWith(), boss_hakkar::boss_hakkarAI::JustEngagedWith(), boss_hazzarah::JustEngagedWith(), boss_mandokir::boss_mandokirAI::JustEngagedWith(), boss_renataki::boss_renatakiAI::JustEngagedWith(), boss_thekal::JustEngagedWith(), boss_venoxis::JustEngagedWith(), boss_wushoolay::boss_wushoolayAI::JustEngagedWith(), boss_archimonde::JustEngagedWith(), boss_epoch_hunter::JustEngagedWith(), boss_lieutenant_drake::JustEngagedWith(), boss_chrono_lord_deja::JustEngagedWith(), boss_temporus::JustEngagedWith(), boss_isalien::JustEngagedWith(), boss_skeram::JustEngagedWith(), boss_elder_nadox::JustEngagedWith(), boss_volazj::JustEngagedWith(), boss_jedoga_shadowseeker::JustEngagedWith(), boss_taldaram::JustEngagedWith(), boss_sartharion::JustEngagedWith(), boss_sister_svalna::boss_sister_svalnaAI::JustEngagedWith(), boss_malygos::JustEngagedWith(), boss_ionar::JustEngagedWith(), boss_loken::JustEngagedWith(), boss_volkhan::JustEngagedWith(), boss_sjonnir::boss_sjonnirAI::JustEngagedWith(), boss_vezax::JustEngagedWith(), boss_keleseth::JustEngagedWith(), boss_exarch_maladaar::JustEngagedWith(), boss_shirrak_the_dead_watcher::JustEngagedWith(), boss_nexusprince_shaffar::JustEngagedWith(), boss_tavarok::JustEngagedWith(), boss_anzu::JustEngagedWith(), boss_darkweaver_syth::JustEngagedWith(), boss_talon_king_ikiss::JustEngagedWith(), boss_ambassador_hellmaw::JustEngagedWith(), boss_blackheart_the_inciter::JustEngagedWith(), boss_mennu_the_betrayer::JustEngagedWith(), boss_quagmirran::JustEngagedWith(), boss_rokmar_the_crackler::JustEngagedWith(), boss_hydromancer_thespia::JustEngagedWith(), boss_mekgineer_steamrigger::JustEngagedWith(), boss_warlord_kalithresh::JustEngagedWith(), boss_ghazan::JustEngagedWith(), boss_hungarfen::JustEngagedWith(), boss_swamplord_muselek::JustEngagedWith(), boss_the_black_stalker::JustEngagedWith(), boss_gruul::JustEngagedWith(), boss_high_king_maulgar::JustEngagedWith(), boss_broggok::JustEngagedWith(), boss_kelidan_the_breaker::JustEngagedWith(), boss_the_maker::JustEngagedWith(), boss_omor_the_unscarred::JustEngagedWith(), boss_watchkeeper_gargolmar::JustEngagedWith(), boss_dalliah_the_doomsayer::JustEngagedWith(), boss_zereketh_the_unbound::JustEngagedWith(), boss_commander_sarannis::JustEngagedWith(), boss_high_botanist_freywinn::JustEngagedWith(), boss_thorngrin_the_tender::JustEngagedWith(), boss_warp_splinter::JustEngagedWith(), boss_gatewatcher_gyrokill::JustEngagedWith(), boss_gatewatcher_iron_hand::JustEngagedWith(), boss_mechano_lord_capacitus::JustEngagedWith(), boss_nethermancer_sepethrea::JustEngagedWith(), boss_pathaleon_the_calculator::JustEngagedWith(), boss_murmur::JustEngagedWith(), boss_grand_warlock_nethekurse::JustEngagedWith(), boss_vazruden_the_herald::SummonedCreatureDies(), and boss_anub_arak::UpdateAI().
_JustReachedHome()
void BossAI::_JustReachedHome () inline protected
{ me->setActive(false); }
References ScriptedAI::me, and WorldObject::setActive().
Referenced by JustReachedHome(), boss_majordomo::boss_majordomoAI::JustReachedHome(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::JustReachedHome(), boss_festergut::boss_festergutAI::JustReachedHome(), boss_lord_marrowgar::JustReachedHome(), boss_professor_putricide::boss_professor_putricideAI::JustReachedHome(), boss_rotface::boss_rotfaceAI::JustReachedHome(), npc_green_dragon_combat_trigger::npc_green_dragon_combat_triggerAI::JustReachedHome(), boss_flame_leviathan::JustReachedHome(), boss_freya::JustReachedHome(), boss_vezax::JustReachedHome(), boss_ignis::JustReachedHome(), boss_mimiron::JustReachedHome(), boss_razorscale::JustReachedHome(), boss_thorim::JustReachedHome(), boss_xt002::JustReachedHome(), and boss_ghazan::JustReachedHome().
_Reset()
void BossAI::_Reset () protected
{
    if (!me->IsAlive())
        return;
    if (me->IsEngaged())
        return;
    me->SetCombatPulseDelay(0);
    me->ResetLootMode();
    events.Reset();
    scheduler.CancelAll();
    me->m_Events.KillAllEvents(false);
    summons.DespawnAll();
    ClearUniqueTimedEventsDone();
    _healthCheckEvents.clear();
    if (instance)
        instance->SetBossState(_bossId, NOT_STARTED);
}
References _bossId, _healthCheckEvents, TaskScheduler::CancelAll(), ScriptedAI::ClearUniqueTimedEventsDone(), SummonList::DespawnAll(), instance, Unit::IsAlive(), Unit::IsEngaged(), EventProcessor::KillAllEvents(), WorldObject::m_Events, ScriptedAI::me, NOT_STARTED, Creature::ResetLootMode(), CreatureAI::scheduler, InstanceScript::SetBossState(), Creature::SetCombatPulseDelay(), and summons.
Referenced by Reset(), boss_magmus::boss_magmusAI::Reset(), boss_halycon::boss_halyconAI::Reset(), boss_highlord_omokk::boss_highlordomokkAI::Reset(), boss_overlord_wyrmthalak::boss_overlordwyrmthalakAI::Reset(), boss_quartermaster_zigris::Reset(), boss_rend_blackhand::boss_rend_blackhandAI::Reset(), boss_solakar_flamewreath::boss_solakar_flamewreathAI::Reset(), boss_the_beast::boss_thebeastAI::Reset(), boss_chromaggus::boss_chromaggusAI::Reset(), boss_victor_nefarius::boss_victor_nefariusAI::Reset(), boss_nefarian::Reset(), boss_razorgore::boss_razorgoreAI::Reset(), boss_vaelastrasz::boss_vaelAI::Reset(), boss_baron_geddon::boss_baron_geddonAI::Reset(), boss_garr::boss_garrAI::Reset(), boss_golemagg::boss_golemaggAI::Reset(), boss_ragnaros::boss_ragnarosAI::Reset(), boss_malchezaar::Reset(), boss_tenris_mirkblood::Reset(), boss_terestian_illhoof::Reset(), boss_vexallus::Reset(), boss_darkmaster_gandling::boss_darkmaster_gandlingAI::Reset(), boss_apothecary_hummel::boss_apothecary_hummelAI::Reset(), boss_jarien::Reset(), boss_sothos::Reset(), boss_akilzon::Reset(), boss_zuljin::Reset(), boss_arlokk::boss_arlokkAI::Reset(), boss_hakkar::boss_hakkarAI::Reset(), boss_renataki::boss_renatakiAI::Reset(), boss_thekal::Reset(), boss_archimonde::Reset(), boss_captain_skarloc::Reset(), boss_isalien::Reset(), boss_moam::Reset(), boss_sartura::Reset(), boss_skeram::Reset(), boss_amanitar::Reset(), boss_elder_nadox::Reset(), boss_volazj::Reset(), boss_jedoga_shadowseeker::Reset(), boss_taldaram::Reset(), boss_sartharion::Reset(), boss_sartharion_dragonAI::Reset(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::Reset(), boss_festergut::boss_festergutAI::Reset(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::Reset(), boss_lord_marrowgar::Reset(), boss_professor_putricide::boss_professor_putricideAI::Reset(), boss_rotface::boss_rotfaceAI::Reset(), boss_sindragosa::boss_sindragosaAI::Reset(), boss_the_lich_king::boss_the_lich_kingAI::Reset(), boss_sister_svalna::boss_sister_svalnaAI::Reset(), boss_malygos::Reset(), boss_ionar::Reset(), boss_loken::Reset(), boss_volkhan::Reset(), boss_sjonnir::boss_sjonnirAI::Reset(), boss_freya::Reset(), boss_vezax::Reset(), boss_hodir::Reset(), boss_ignis::Reset(), boss_kologarn::Reset(), boss_mimiron::Reset(), boss_razorscale::Reset(), boss_thorim::Reset(), boss_xt002::Reset(), boss_exarch_maladaar::Reset(), boss_shirrak_the_dead_watcher::Reset(), boss_nexusprince_shaffar::Reset(), boss_tavarok::Reset(), boss_anzu::Reset(), boss_darkweaver_syth::Reset(), boss_talon_king_ikiss::Reset(), boss_ambassador_hellmaw::Reset(), boss_blackheart_the_inciter::Reset(), boss_grandmaster_vorpil::Reset(), boss_murmur::Reset(), boss_mother_shahraz::Reset(), boss_najentus::Reset(), boss_hydross_the_unstable::Reset(), boss_mennu_the_betrayer::Reset(), boss_rokmar_the_crackler::Reset(), boss_warlord_kalithresh::Reset(), boss_ghazan::Reset(), boss_hungarfen::Reset(), boss_swamplord_muselek::Reset(), boss_gruul::Reset(), boss_high_king_maulgar::Reset(), boss_broggok::Reset(), boss_kelidan_the_breaker::Reset(), boss_omor_the_unscarred::Reset(), boss_vazruden_the_herald::Reset(), boss_watchkeeper_gargolmar::Reset(), npc_warden_mellichar::npc_warden_mellicharAI::Reset(), boss_dalliah_the_doomsayer::Reset(), boss_harbinger_skyriss::Reset(), boss_wrath_scryer_soccothrates::Reset(), boss_laj::Reset(), boss_thorngrin_the_tender::Reset(), and boss_pathaleon_the_calculator::Reset().
CanRespawn()
bool BossAI::CanRespawn () override virtual
Reimplemented from CreatureAI.
{
    if (instance)
    {
        if (instance->GetBossState(_bossId) == DONE)
        {
            return false;
        }
    }
    return true;
}
References _bossId, DONE, InstanceScript::GetBossState(), and instance.
DamageTaken()
void BossAI::DamageTaken (Unit * , uint32 & , DamageEffectType , SpellSchoolMask) override virtual
Called at any Damage from any attacker (before damage apply)
Note
It use for recalculation damage or special reaction at damage for attack reaction use AttackedBy called for non DOT damage in Unit::DealDamage also
Reimplemented from UnitAI.
Reimplemented in npc_warden_mellichar::npc_warden_mellicharAI.
{
    ScriptedAI::DamageTaken(attacker, damage, damagetype, damageSchoolMask);
    if (!_nextHealthCheck.HasBeenProcessed())
    {
        if (me->HealthBelowPctDamaged(_nextHealthCheck._healthPct, damage))
        {
            if (!_nextHealthCheck._allowedWhileCasting && me->HasUnitState(UNIT_STATE_CASTING))
            {
                _nextHealthCheck.UpdateStatus(HEALTH_CHECK_PENDING);
                return;
            }
            ProcessHealthCheck();
        }
    }
}
References HealthCheckEventData::_allowedWhileCasting, HealthCheckEventData::_healthPct, _nextHealthCheck, ScriptedAI::DamageTaken(), HealthCheckEventData::HasBeenProcessed(), Unit::HasUnitState(), HEALTH_CHECK_PENDING, Unit::HealthBelowPctDamaged(), ScriptedAI::me, ProcessHealthCheck(), UNIT_STATE_CASTING, and HealthCheckEventData::UpdateStatus().
Referenced by boss_nightbane::DamageTaken(), boss_thekal::DamageTaken(), boss_tenris_mirkblood::DamageTaken(), boss_felblood_kaelthas::DamageTaken(), boss_halazzi::DamageTaken(), boss_anub_arak::DamageTaken(), boss_malygos::DamageTaken(), boss_razorscale::DamageTaken(), boss_illidan_stormrage::DamageTaken(), boss_taldaram::DamageTaken(), boss_shade_of_aran::DamageTaken(), and boss_kiljaeden::DamageTaken().
EnterEvadeMode()
void BossAI::EnterEvadeMode (EvadeReason why = EVADE_REASON_OTHER) inline override virtual
Reimplemented from CreatureAI.
Reimplemented in npc_green_dragon_combat_trigger::npc_green_dragon_combat_triggerAI.
{ _EnterEvadeMode(why); }
References _EnterEvadeMode().
Referenced by _JustEngagedWith(), boss_hakkar::boss_hakkarAI::CheckInRoom(), boss_onyxia::CheckInRoom(), boss_viscidus::CheckInRoom(), boss_fathomlord_karathress::DoAction(), boss_kalecgos::DoAction(), boss_hakkar::boss_hakkarAI::EnterEvadeMode(), boss_gyth::boss_gythAI::EnterEvadeMode(), boss_rend_blackhand::boss_rend_blackhandAI::EnterEvadeMode(), boss_ragnaros::boss_ragnarosAI::EnterEvadeMode(), boss_nightbane::EnterEvadeMode(), boss_arlokk::boss_arlokkAI::EnterEvadeMode(), boss_jeklik::EnterEvadeMode(), boss_archimonde::EnterEvadeMode(), boss_ayamiss::EnterEvadeMode(), boss_buru::EnterEvadeMode(), boss_bug_trio::EnterEvadeMode(), boss_twinemperorsAI::EnterEvadeMode(), boss_amanitar::EnterEvadeMode(), boss_anub_arak::EnterEvadeMode(), boss_sartharion::EnterEvadeMode(), boss_halion::boss_halionAI::EnterEvadeMode(), boss_moorabi::boss_moorabiAI::EnterEvadeMode(), boss_prince_valanar_icc::boss_prince_valanarAI::EnterEvadeMode(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::EnterEvadeMode(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::EnterEvadeMode(), boss_professor_putricide::boss_professor_putricideAI::EnterEvadeMode(), boss_sindragosa::boss_sindragosaAI::EnterEvadeMode(), boss_the_lich_king::boss_the_lich_kingAI::EnterEvadeMode(), boss_four_horsemen::boss_four_horsemenAI::EnterEvadeMode(), boss_ignis::EnterEvadeMode(), boss_mimiron::EnterEvadeMode(), boss_razorscale::EnterEvadeMode(), boss_thorim::EnterEvadeMode(), boss_murmur::EnterEvadeMode(), boss_illidan_stormrage::EnterEvadeMode(), boss_illidari_council::EnterEvadeMode(), boss_shade_of_akama::EnterEvadeMode(), boss_the_lurker_below::EnterEvadeMode(), boss_harbinger_skyriss::EnterEvadeMode(), boss_alar::EnterEvadeMode(), boss_gothik::boss_gothikAI::IsInRoom(), boss_loatheb::boss_loathebAI::IsInRoom(), boss_maexxna::boss_maexxnaAI::IsInRoom(), boss_sapphiron::boss_sapphironAI::IsInRoom(), boss_akilzon::JustEngagedWith(), boss_the_black_stalker::JustEngagedWith(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::JustEngagedWith(), boss_vazruden_the_herald::SummonedCreatureDespawn(), boss_majordomo::boss_majordomoAI::SummonedCreatureDies(), boss_hadronox::SummonedCreatureEvade(), boss_the_beast::boss_thebeastAI::UpdateAI(), boss_broodlord::boss_broodlordAI::UpdateAI(), boss_attumen::UpdateAI(), boss_midnight::UpdateAI(), boss_moroes::UpdateAI(), boss_shade_of_aran::UpdateAI(), boss_hadronox::UpdateAI(), boss_trollgore::boss_trollgoreAI::UpdateAI(), boss_lord_marrowgar::UpdateAI(), boss_volkhan::UpdateAI(), boss_flame_leviathan::UpdateAI(), boss_hodir::UpdateAI(), boss_xt002::UpdateAI(), boss_warchief_kargath_bladefist::UpdateAI(), and boss_vazruden_the_herald::UpdateAI().
ExecuteEvent()
virtual void BossAI::ExecuteEvent (uint32) inline virtual
Reimplemented in boss_solakar_flamewreath::boss_solakar_flamewreathAI, boss_warmaster_voone::boss_warmastervooneAI, boss_baron_geddon::boss_baron_geddonAI, boss_gehennas::boss_gehennasAI, boss_lucifron::boss_lucifronAI, boss_magmadar::boss_magmadarAI, boss_shazzrah::boss_shazzrahAI, boss_sulfuron::boss_sulfuronAI, boss_sartharion_tenebron, boss_sartharion_shadron, boss_sartharion_vesperon, boss_auriaya, and boss_ahune.
{ }
Referenced by boss_sartharion_dragonAI::UpdateAI(), and UpdateAI().
JustDied()
void BossAI::JustDied (Unit *) inline override virtual
Reimplemented from CreatureAI.
Reimplemented in npc_warden_mellichar::npc_warden_mellicharAI.
{ _JustDied(); }
References _JustDied().
Referenced by boss_lord_valthalak::boss_lord_valthalakAI::JustDied(), boss_curator::JustDied(), boss_maiden_of_virtue::JustDied(), boss_moroes::JustDied(), boss_netherspite::JustDied(), boss_felblood_kaelthas::JustDied(), boss_selin_fireheart::JustDied(), boss_brutallus::JustDied(), boss_felmyst::JustDied(), boss_halazzi::JustDied(), boss_janalai::JustDied(), boss_nalorakk::JustDied(), boss_jeklik::JustDied(), boss_marli::JustDied(), boss_venoxis::JustDied(), boss_anetheron::JustDied(), boss_azgalor::JustDied(), boss_kazrogal::JustDied(), boss_rage_winterchill::JustDied(), boss_ayamiss::JustDied(), boss_buru::JustDied(), boss_kurinnaxx::JustDied(), boss_bug_trio::JustDied(), boss_cthun::JustDied(), boss_twinemperorsAI::JustDied(), boss_anub_arak::JustDied(), boss_krik_thir::boss_krik_thirAI::JustDied(), boss_baltharus_the_warborn::boss_baltharus_the_warbornAI::JustDied(), boss_general_zarithrian::boss_general_zarithrianAI::JustDied(), boss_halion::boss_halionAI::JustDied(), boss_saviana_ragefire::boss_saviana_ragefireAI::JustDied(), boss_novos::JustDied(), boss_tharon_ja::boss_tharon_jaAI::JustDied(), boss_trollgore::boss_trollgoreAI::JustDied(), boss_gal_darah::JustDied(), boss_moorabi::boss_moorabiAI::JustDied(), boss_slad_ran::boss_slad_ranAI::JustDied(), boss_anubrekhan::JustDied(), boss_faerlina::boss_faerlinaAI::JustDied(), boss_four_horsemen::boss_four_horsemenAI::JustDied(), boss_gluth::boss_gluthAI::JustDied(), boss_gothik::boss_gothikAI::JustDied(), boss_grobbulus::boss_grobbulusAI::JustDied(), boss_heigan::JustDied(), boss_kelthuzad::boss_kelthuzadAI::JustDied(), boss_loatheb::boss_loathebAI::JustDied(), boss_maexxna::boss_maexxnaAI::JustDied(), boss_noth::boss_nothAI::JustDied(), boss_patchwerk::boss_patchwerkAI::JustDied(), boss_razuvious::boss_razuviousAI::JustDied(), boss_sapphiron::boss_sapphironAI::JustDied(), boss_thaddius::boss_thaddiusAI::JustDied(), boss_anomalus::JustDied(), boss_commander_stoutbeard::JustDied(), boss_keristrasza::JustDied(), boss_magus_telestra::JustDied(), boss_ormorok::JustDied(), boss_auriaya::JustDied(), boss_pandemonius::JustDied(), boss_gurtogg_bloodboil::JustDied(), boss_illidan_stormrage::JustDied(), boss_mother_shahraz::JustDied(), boss_reliquary_of_souls::boss_reliquary_of_soulsAI::JustDied(), boss_shade_of_akama::JustDied(), boss_teron_gorefiend::JustDied(), boss_najentus::JustDied(), boss_fathomlord_karathress::JustDied(), boss_hydross_the_unstable::JustDied(), boss_lady_vashj::JustDied(), boss_morogrim_tidewalker::JustDied(), boss_magtheridon::JustDied(), boss_porung::JustDied(), boss_warbringer_omrogg::JustDied(), boss_warchief_kargath_bladefist::JustDied(), boss_alar::JustDied(), boss_high_astromancer_solarian::JustDied(), boss_kaelthas::JustDied(), and boss_void_reaver::JustDied().
JustEngagedWith()
void BossAI::JustEngagedWith (Unit *) inline override virtual
Called for reaction when initially engaged.
Reimplemented from CreatureAI.
Reimplemented in npc_warden_mellichar::npc_warden_mellicharAI, and npc_green_dragon_combat_trigger::npc_green_dragon_combat_triggerAI.
{ _JustEngagedWith(); }
References _JustEngagedWith().
Referenced by boss_bug_trio::EnterCombatWithTrio(), boss_ayamiss::JustEngagedWith(), boss_lord_valthalak::boss_lord_valthalakAI::JustEngagedWith(), boss_quartermaster_zigris::JustEngagedWith(), boss_broodlord::boss_broodlordAI::JustEngagedWith(), boss_chromaggus::boss_chromaggusAI::JustEngagedWith(), boss_ebonroc::boss_ebonrocAI::JustEngagedWith(), boss_firemaw::boss_firemawAI::JustEngagedWith(), boss_flamegor::boss_flamegorAI::JustEngagedWith(), boss_vaelastrasz::boss_vaelAI::JustEngagedWith(), boss_curator::JustEngagedWith(), boss_maiden_of_virtue::JustEngagedWith(), boss_midnight::JustEngagedWith(), boss_moroes::JustEngagedWith(), boss_netherspite::JustEngagedWith(), boss_nightbane::JustEngagedWith(), boss_felblood_kaelthas::JustEngagedWith(), boss_selin_fireheart::JustEngagedWith(), boss_brutallus::JustEngagedWith(), boss_sacrolash::JustEngagedWith(), boss_alythess::JustEngagedWith(), boss_felmyst::JustEngagedWith(), boss_kalecgos::JustEngagedWith(), boss_muru::JustEngagedWith(), boss_halazzi::JustEngagedWith(), boss_hexlord_malacrass::JustEngagedWith(), boss_janalai::JustEngagedWith(), boss_nalorakk::JustEngagedWith(), boss_jeklik::JustEngagedWith(), boss_jindo::JustEngagedWith(), boss_marli::JustEngagedWith(), boss_anetheron::JustEngagedWith(), boss_azgalor::JustEngagedWith(), boss_kazrogal::JustEngagedWith(), boss_rage_winterchill::JustEngagedWith(), boss_onyxia::JustEngagedWith(), boss_buru::JustEngagedWith(), boss_kurinnaxx::JustEngagedWith(), boss_moam::JustEngagedWith(), boss_ossirian::JustEngagedWith(), boss_eye_of_cthun::JustEngagedWith(), boss_fankriss::JustEngagedWith(), boss_huhuran::JustEngagedWith(), boss_ouro::JustEngagedWith(), boss_sartura::JustEngagedWith(), boss_twinemperorsAI::JustEngagedWith(), boss_viscidus::JustEngagedWith(), boss_krik_thir::boss_krik_thirAI::JustEngagedWith(), boss_baltharus_the_warborn::boss_baltharus_the_warbornAI::JustEngagedWith(), boss_general_zarithrian::boss_general_zarithrianAI::JustEngagedWith(), boss_halion::boss_halionAI::JustEngagedWith(), boss_saviana_ragefire::boss_saviana_ragefireAI::JustEngagedWith(), boss_dred::boss_dredAI::JustEngagedWith(), boss_novos::JustEngagedWith(), boss_tharon_ja::boss_tharon_jaAI::JustEngagedWith(), boss_eck::JustEngagedWith(), boss_gal_darah::JustEngagedWith(), boss_moorabi::boss_moorabiAI::JustEngagedWith(), boss_slad_ran::boss_slad_ranAI::JustEngagedWith(), boss_anubrekhan::JustEngagedWith(), boss_faerlina::boss_faerlinaAI::JustEngagedWith(), boss_four_horsemen::boss_four_horsemenAI::JustEngagedWith(), boss_gluth::boss_gluthAI::JustEngagedWith(), boss_gothik::boss_gothikAI::JustEngagedWith(), boss_grobbulus::boss_grobbulusAI::JustEngagedWith(), boss_heigan::JustEngagedWith(), boss_kelthuzad::boss_kelthuzadAI::JustEngagedWith(), boss_loatheb::boss_loathebAI::JustEngagedWith(), boss_maexxna::boss_maexxnaAI::JustEngagedWith(), boss_noth::boss_nothAI::JustEngagedWith(), boss_patchwerk::boss_patchwerkAI::JustEngagedWith(), boss_razuvious::boss_razuviousAI::JustEngagedWith(), boss_sapphiron::boss_sapphironAI::JustEngagedWith(), boss_thaddius::boss_thaddiusAI::JustEngagedWith(), boss_anomalus::JustEngagedWith(), boss_commander_stoutbeard::JustEngagedWith(), boss_keristrasza::JustEngagedWith(), boss_magus_telestra::JustEngagedWith(), boss_ormorok::JustEngagedWith(), boss_auriaya::JustEngagedWith(), boss_razorscale::JustEngagedWith(), boss_pandemonius::JustEngagedWith(), boss_gurtogg_bloodboil::JustEngagedWith(), boss_illidan_stormrage::JustEngagedWith(), boss_mother_shahraz::JustEngagedWith(), boss_reliquary_of_souls::boss_reliquary_of_soulsAI::JustEngagedWith(), boss_supremus::JustEngagedWith(), boss_teron_gorefiend::JustEngagedWith(), boss_najentus::JustEngagedWith(), boss_fathomlord_karathress::JustEngagedWith(), boss_hydross_the_unstable::JustEngagedWith(), boss_lady_vashj::JustEngagedWith(), boss_the_lurker_below::JustEngagedWith(), boss_morogrim_tidewalker::JustEngagedWith(), boss_ahune::JustEngagedWith(), boss_magtheridon::JustEngagedWith(), boss_porung::JustEngagedWith(), boss_warbringer_omrogg::JustEngagedWith(), boss_warchief_kargath_bladefist::JustEngagedWith(), boss_alar::JustEngagedWith(), boss_high_astromancer_solarian::JustEngagedWith(), and boss_void_reaver::JustEngagedWith().
JustReachedHome()
void BossAI::JustReachedHome () inline override virtual
Reimplemented from CreatureAI.
Reimplemented in npc_green_dragon_combat_trigger::npc_green_dragon_combat_triggerAI.
{ _JustReachedHome(); }
References _JustReachedHome().
Referenced by boss_moroes::JustReachedHome(), boss_nightbane::JustReachedHome(), boss_baltharus_the_warborn::boss_baltharus_the_warbornAI::JustReachedHome(), boss_saviana_ragefire::boss_saviana_ragefireAI::JustReachedHome(), boss_drakkari_colossus::boss_drakkari_colossusAI::JustReachedHome(), boss_gal_darah::JustReachedHome(), boss_hydross_the_unstable::JustReachedHome(), and boss_alar::JustReachedHome().
JustSummoned()
void BossAI::JustSummoned (Creature * summon) override virtual
Reimplemented from CreatureAI.
Reimplemented in npc_warden_mellichar::npc_warden_mellicharAI.
{
    summons.Summon(summon);
    if (me->IsEngaged())
        DoZoneInCombat(summon);
}
References CreatureAI::DoZoneInCombat(), Unit::IsEngaged(), ScriptedAI::me, SummonList::Summon(), and summons.
Referenced by boss_freya::JustSummoned(), boss_kologarn::JustSummoned(), boss_muru::JustSummoned(), boss_skeram::JustSummoned(), boss_victor_nefarius::boss_victor_nefariusAI::JustSummoned(), boss_ragnaros::boss_ragnarosAI::JustSummoned(), boss_attumen::JustSummoned(), boss_midnight::JustSummoned(), boss_kiljaeden::JustSummoned(), boss_halazzi::JustSummoned(), boss_janalai::JustSummoned(), boss_jindo::JustSummoned(), boss_anetheron::JustSummoned(), boss_sartharion_dragonAI::JustSummoned(), boss_the_lich_king::boss_the_lich_kingAI::JustSummoned(), boss_hydross_the_unstable::JustSummoned(), boss_the_black_stalker::JustSummoned(), boss_harbinger_skyriss::JustSummoned(), boss_archimonde::JustSummoned(), and boss_hodir::SpawnHelpers().
OnSpellCastFinished()
void BossAI::OnSpellCastFinished (SpellInfo const * spell, SpellFinishReason reason) override virtual
Reimplemented from CreatureAI.
{
    ScriptedAI::OnSpellCastFinished(spellInfo, reason);
    // Check if any health check events are pending (i.e. waiting for the boss to stop casting.
    if (_nextHealthCheck.IsPending() && me->IsInCombat())
    {
        _nextHealthCheck.UpdateStatus(HEALTH_CHECK_PROCESSED);
        // This must be delayed because creature might still have unit state casting at this point, which might break scripts.
        scheduler.Schedule(1s, [this](TaskContext context)
        {
            if (me->HasUnitState(UNIT_STATE_CASTING))
                context.Repeat();
            else
                ProcessHealthCheck();
        });
    }
}
References _nextHealthCheck, Unit::HasUnitState(), HEALTH_CHECK_PROCESSED, Unit::IsInCombat(), HealthCheckEventData::IsPending(), ScriptedAI::me, CreatureAI::OnSpellCastFinished(), ProcessHealthCheck(), TaskContext::Repeat(), TaskScheduler::Schedule(), CreatureAI::scheduler, UNIT_STATE_CASTING, and HealthCheckEventData::UpdateStatus().
ProcessHealthCheck()
void BossAI::ProcessHealthCheck ()
{
    _nextHealthCheck.UpdateStatus(HEALTH_CHECK_PROCESSED);
    _nextHealthCheck._exec();
    _healthCheckEvents.remove_if([&](HealthCheckEventData data) -> bool
    {
        return data._healthPct == _nextHealthCheck._healthPct;
    });
    if (!_healthCheckEvents.empty())
        _nextHealthCheck = _healthCheckEvents.front();
}
References HealthCheckEventData::_exec, _healthCheckEvents, HealthCheckEventData::_healthPct, _nextHealthCheck, HEALTH_CHECK_PROCESSED, and HealthCheckEventData::UpdateStatus().
Referenced by DamageTaken(), and OnSpellCastFinished().
Reset()
void BossAI::Reset () inline override virtual
Reimplemented from UnitAI.
Reimplemented in npc_green_dragon_combat_trigger::npc_green_dragon_combat_triggerAI, and npc_warden_mellichar::npc_warden_mellicharAI.
{ _Reset(); }
References _Reset().
Referenced by boss_jindo::EnterEvadeMode(), boss_lord_valthalak::boss_lord_valthalakAI::Reset(), boss_curator::Reset(), boss_midnight::Reset(), boss_moroes::Reset(), boss_netherspite::Reset(), boss_nightbane::Reset(), boss_shade_of_aran::Reset(), boss_felblood_kaelthas::Reset(), boss_selin_fireheart::Reset(), boss_brutallus::Reset(), boss_sacrolash::Reset(), boss_alythess::Reset(), boss_felmyst::Reset(), boss_kalecgos::Reset(), boss_muru::Reset(), boss_halazzi::Reset(), boss_hexlord_malacrass::Reset(), boss_janalai::Reset(), boss_nalorakk::Reset(), boss_grilek::boss_grilekAI::Reset(), boss_jeklik::Reset(), boss_mandokir::boss_mandokirAI::Reset(), boss_marli::Reset(), boss_venoxis::Reset(), boss_kazrogal::Reset(), boss_onyxia::Reset(), boss_ayamiss::Reset(), boss_ossirian::Reset(), boss_bug_trio::Reset(), boss_eye_of_cthun::Reset(), boss_cthun::Reset(), boss_fankriss::Reset(), boss_huhuran::Reset(), boss_viscidus::Reset(), boss_anub_arak::Reset(), boss_hadronox::Reset(), boss_krik_thir::boss_krik_thirAI::Reset(), boss_baltharus_the_warborn::boss_baltharus_the_warbornAI::Reset(), boss_general_zarithrian::boss_general_zarithrianAI::Reset(), boss_halion::boss_halionAI::Reset(), boss_saviana_ragefire::boss_saviana_ragefireAI::Reset(), boss_dred::boss_dredAI::Reset(), boss_novos::Reset(), boss_tharon_ja::boss_tharon_jaAI::Reset(), boss_trollgore::boss_trollgoreAI::Reset(), boss_drakkari_colossus::boss_drakkari_colossusAI::Reset(), boss_gal_darah::Reset(), boss_moorabi::boss_moorabiAI::Reset(), boss_slad_ran::boss_slad_ranAI::Reset(), boss_anubrekhan::Reset(), boss_faerlina::boss_faerlinaAI::Reset(), boss_four_horsemen::boss_four_horsemenAI::Reset(), boss_gluth::boss_gluthAI::Reset(), boss_gothik::boss_gothikAI::Reset(), boss_grobbulus::boss_grobbulusAI::Reset(), boss_heigan::Reset(), boss_kelthuzad::boss_kelthuzadAI::Reset(), boss_loatheb::boss_loathebAI::Reset(), boss_maexxna::boss_maexxnaAI::Reset(), boss_noth::boss_nothAI::Reset(), boss_patchwerk::boss_patchwerkAI::Reset(), boss_razuvious::boss_razuviousAI::Reset(), boss_sapphiron::boss_sapphironAI::Reset(), boss_thaddius::boss_thaddiusAI::Reset(), boss_anomalus::Reset(), boss_keristrasza::Reset(), boss_magus_telestra::Reset(), boss_ormorok::Reset(), boss_auriaya::Reset(), boss_gurtogg_bloodboil::Reset(), boss_illidan_stormrage::Reset(), boss_reliquary_of_souls::boss_reliquary_of_soulsAI::Reset(), boss_shade_of_akama::Reset(), boss_supremus::Reset(), boss_teron_gorefiend::Reset(), boss_fathomlord_karathress::Reset(), boss_lady_vashj::Reset(), boss_leotheras_the_blind::Reset(), boss_the_lurker_below::Reset(), boss_morogrim_tidewalker::Reset(), boss_magtheridon::Reset(), boss_warchief_kargath_bladefist::Reset(), boss_alar::Reset(), boss_high_astromancer_solarian::Reset(), boss_kaelthas::Reset(), and boss_void_reaver::Reset().
ScheduleEnrageTimer()
void BossAI::ScheduleEnrageTimer (uint32 spellId, Milliseconds timer, uint8 textId = 0)
{
    me->m_Events.AddEventAtOffset([this, spellId, textId]
    {
        if (!me->IsAlive())
            return;
        if (textId)
            Talk(textId);
        DoCastSelf(spellId, true);
    }, timer);
}
References EventProcessor::AddEventAtOffset(), UnitAI::DoCastSelf(), Unit::IsAlive(), WorldObject::m_Events, and ScriptedAI::me.
Referenced by boss_sartharion::JustEngagedWith(), boss_brutallus::JustEngagedWith(), boss_sacrolash::JustEngagedWith(), boss_alythess::JustEngagedWith(), boss_felmyst::JustEngagedWith(), boss_eck::JustEngagedWith(), boss_anubrekhan::JustEngagedWith(), boss_auriaya::JustEngagedWith(), and boss_thaddius::boss_thaddiusAI::UpdateAI().
ScheduleHealthCheckEvent() [1/2]
void BossAI::ScheduleHealthCheckEvent (std::initializer_list< uint8 > healthPct, std::function< void()> exec, bool allowedWhileCasting = true)
{
    for (auto const& checks : healthPct)
        _healthCheckEvents.push_back(HealthCheckEventData(checks, exec, HEALTH_CHECK_SCHEDULED, allowedWhileCasting));
    _nextHealthCheck = _healthCheckEvents.front();
}
References _healthCheckEvents, _nextHealthCheck, and HEALTH_CHECK_SCHEDULED.
ScheduleHealthCheckEvent() [2/2]
void BossAI::ScheduleHealthCheckEvent (uint32 healthPct, std::function< void()> exec, bool allowedWhileCasting = true)
Executes a function once the creature reaches the defined health point percent.
Parameters
healthPct The health percent at which the code will be executed.
exec The fuction to be executed.
allowedWhileCasting If false, the event will not be checked while the creature is casting.
{
    _healthCheckEvents.push_back(HealthCheckEventData(healthPct, exec, HEALTH_CHECK_SCHEDULED, allowedWhileCasting));
    _nextHealthCheck = _healthCheckEvents.front();
};
References _healthCheckEvents, _nextHealthCheck, and HEALTH_CHECK_SCHEDULED.
Referenced by boss_thekal::CheckPhaseTransition(), boss_zuljin::JustEngagedWith(), boss_venoxis::JustEngagedWith(), boss_mekgineer_steamrigger::JustEngagedWith(), boss_commander_sarannis::JustEngagedWith(), boss_pathaleon_the_calculator::JustEngagedWith(), boss_kurinnaxx::JustEngagedWith(), boss_jeklik::PathEndReached(), boss_gyth::boss_gythAI::Reset(), boss_nefarian::Reset(), boss_curator::Reset(), boss_moroes::Reset(), boss_nightbane::Reset(), boss_malchezaar::Reset(), boss_shade_of_aran::Reset(), boss_tenris_mirkblood::Reset(), boss_felblood_kaelthas::Reset(), boss_vexallus::Reset(), boss_kalecgos::Reset(), boss_kiljaeden::Reset(), boss_hexlord_malacrass::Reset(), boss_janalai::Reset(), boss_archimonde::Reset(), boss_ayamiss::Reset(), boss_volazj::Reset(), boss_taldaram::Reset(), boss_anub_arak::Reset(), boss_krik_thir::boss_krik_thirAI::Reset(), boss_dred::boss_dredAI::Reset(), boss_tharon_ja::boss_tharon_jaAI::Reset(), boss_slad_ran::boss_slad_ranAI::Reset(), boss_ionar::Reset(), boss_loken::Reset(), boss_sjonnir::boss_sjonnirAI::Reset(), boss_exarch_maladaar::Reset(), boss_anzu::Reset(), boss_darkweaver_syth::Reset(), boss_talon_king_ikiss::Reset(), boss_illidan_stormrage::Reset(), boss_mother_shahraz::Reset(), boss_fathomlord_karathress::Reset(), boss_lady_vashj::Reset(), boss_leotheras_the_blind::Reset(), boss_mennu_the_betrayer::Reset(), boss_rokmar_the_crackler::Reset(), boss_ghazan::Reset(), boss_hungarfen::Reset(), boss_high_king_maulgar::Reset(), boss_omor_the_unscarred::Reset(), boss_watchkeeper_gargolmar::Reset(), boss_magtheridon::Reset(), boss_grand_warlock_nethekurse::Reset(), boss_dalliah_the_doomsayer::Reset(), boss_harbinger_skyriss::Reset(), boss_wrath_scryer_soccothrates::Reset(), boss_thorngrin_the_tender::Reset(), and boss_high_astromancer_solarian::Reset().
ScheduleTasks()
virtual void BossAI::ScheduleTasks () inline virtual
Reimplemented in boss_attumen, boss_ayamiss, boss_cthun, boss_volazj, boss_dred::boss_dredAI, boss_drakkari_colossus::boss_drakkari_colossusAI, boss_loken, boss_sjonnir::boss_sjonnirAI, and boss_laj.
{ }
Referenced by _JustEngagedWith().
SummonedCreatureDespawn()
void BossAI::SummonedCreatureDespawn (Creature * summon) override virtual
Reimplemented from CreatureAI.
{
    summons.Despawn(summon);
}
References SummonList::Despawn(), and summons.
Referenced by boss_rend_blackhand::boss_rend_blackhandAI::SummonedCreatureDespawn(), boss_amanitar::SummonedCreatureDespawn(), and boss_sindragosa::boss_sindragosaAI::SummonedCreatureDespawn().
SummonedCreatureDespawnAll()
void BossAI::SummonedCreatureDespawnAll () override virtual
Reimplemented from CreatureAI.
{
    summons.DespawnAll();
}
References SummonList::DespawnAll(), and summons.
TeleportCheaters()
void BossAI::TeleportCheaters () protected
{
    float x, y, z;
    me->GetPosition(x, y, z);
    ThreatContainer::StorageType threatList = me->GetThreatMgr().GetThreatList();
    for (ThreatContainer::StorageType::const_iterator itr = threatList.begin(); itr != threatList.end(); ++itr)
        if (Unit* target = (*itr)->getTarget())
            if (target->IsPlayer() && !IsInBoundary(target))
                target->NearTeleportTo(x, y, z, 0);
}
References Position::GetPosition(), ThreatMgr::GetThreatList(), Unit::GetThreatMgr(), CreatureAI::IsInBoundary(), and ScriptedAI::me.
UpdateAI()
void BossAI::UpdateAI (uint32) override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Implements UnitAI.
Reimplemented in npc_green_dragon_combat_trigger::npc_green_dragon_combat_triggerAI, and npc_warden_mellichar::npc_warden_mellicharAI.
{
    if (!UpdateVictim())
    {
        return;
    }
    events.Update(diff);
    scheduler.Update(diff);
    if (me->HasUnitState(UNIT_STATE_CASTING))
    {
        return;
    }
    while (uint32 const eventId = events.ExecuteEvent())
    {
        ExecuteEvent(eventId);
        if (me->HasUnitState(UNIT_STATE_CASTING))
        {
            return;
        }
    }
    if (IsAutoAttackAllowed())
        DoMeleeAttackIfReady();
}
References UnitAI::DoMeleeAttackIfReady(), ExecuteEvent(), Unit::HasUnitState(), ScriptedAI::IsAutoAttackAllowed(), ScriptedAI::me, CreatureAI::scheduler, UNIT_STATE_CASTING, TaskScheduler::Update(), and CreatureAI::UpdateVictim().
Referenced by boss_nalorakk::UpdateAI(), and boss_heigan::UpdateAI().
Member Data Documentation
_bossId
uint32 const BossAI::_bossId private
Referenced by _EnterEvadeMode(), _JustDied(), _JustEngagedWith(), _Reset(), and CanRespawn().
_healthCheckEvents
std::list<HealthCheckEventData> BossAI::_healthCheckEvents private
Referenced by _JustDied(), _Reset(), ProcessHealthCheck(), ScheduleHealthCheckEvent(), and ScheduleHealthCheckEvent().
_nextHealthCheck
HealthCheckEventData BossAI::_nextHealthCheck private
Referenced by DamageTaken(), OnSpellCastFinished(), ProcessHealthCheck(), ScheduleHealthCheckEvent(), and ScheduleHealthCheckEvent().
callForHelpRange
float BossAI::callForHelpRange
Referenced by _JustEngagedWith(), boss_high_astromancer_solarian::boss_high_astromancer_solarian(), and boss_void_reaver::boss_void_reaver().
instance
InstanceScript* const BossAI::instance
Referenced by _EnterEvadeMode(), _JustDied(), _JustEngagedWith(), _Reset(), boss_sjonnir::boss_sjonnirAI::ActivatePipe(), boss_flame_leviathan::ActivateTowers(), boss_hakkar::boss_hakkarAI::ApplyHakkarPowerStacks(), boss_freya::boss_freya(), boss_hodir::boss_hodir(), boss_mimiron::boss_mimiron(), boss_prince_valanar_icc::boss_prince_valanarAI::boss_prince_valanarAI(), boss_thorim::boss_thorim(), boss_victor_nefarius::boss_victor_nefariusAI::boss_victor_nefariusAI(), boss_wrath_scryer_soccothrates::boss_wrath_scryer_soccothrates(), boss_majordomo::boss_majordomoAI::CanAIAttack(), boss_pathaleon_the_calculator::CanAIAttack(), boss_keristrasza::CanRemovePrison(), CanRespawn(), boss_moira_bronzebeardAI::CastOnEmperorIfPossible(), boss_sacrolash::CheckInRoom(), boss_prince_valanar_icc::boss_prince_valanarAI::CheckRoom(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::CleanAuras(), boss_sartharion_dragonAI::ClearInstance(), boss_sartharion_vesperon::ClearInstance(), boss_kalecgos::ClearPlayerAuras(), boss_mimiron::CloseDoorAndButton(), boss_prince_valanar_icc::boss_prince_valanarAI::DamageDealt(), boss_attumen::DamageTaken(), boss_sindragosa::boss_sindragosaAI::DamageTaken(), boss_freya::DamageTaken(), boss_hodir::DamageTaken(), boss_buru::DamageTaken(), boss_halion::boss_halionAI::DamageTaken(), boss_the_lich_king::boss_the_lich_kingAI::DamageTaken(), npc_warden_mellichar::npc_warden_mellicharAI::DamageTaken(), boss_bug_trio::DamageTaken(), boss_thorim::DamageTaken(), boss_hodir::DoAction(), boss_apothecary_hummel::boss_apothecary_hummelAI::DoAction(), boss_taldaram::DoAction(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::DoAction(), boss_sindragosa::boss_sindragosaAI::DoAction(), boss_the_lich_king::boss_the_lich_kingAI::DoAction(), boss_fathomlord_karathress::DoAction(), boss_broggok::DoAction(), boss_felblood_kaelthas::DoAction(), boss_pathaleon_the_calculator::DoAction(), boss_sacrolash::DoAction(), boss_alythess::DoAction(), boss_kalecgos::DoAction(), boss_onyxia::DoAction(), boss_hadronox::DoAction(), boss_volkhan::DoAction(), boss_sjonnir::boss_sjonnirAI::DoAction(), boss_freya::DoAction(), boss_kologarn::DoAction(), boss_illidan_stormrage::DoAction(), boss_illidari_council::DoAction(), boss_razorgore::boss_razorgoreAI::DoChangePhase(), boss_ahune::Emerge(), boss_bug_trio::EnterCombatWithTrio(), boss_gyth::boss_gythAI::EnterEvadeMode(), boss_rend_blackhand::boss_rend_blackhandAI::EnterEvadeMode(), boss_attumen::EnterEvadeMode(), boss_buru::EnterEvadeMode(), boss_amanitar::EnterEvadeMode(), boss_sartharion::EnterEvadeMode(), boss_halion::boss_halionAI::EnterEvadeMode(), boss_prince_valanar_icc::boss_prince_valanarAI::EnterEvadeMode(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::EnterEvadeMode(), boss_festergut::boss_festergutAI::EnterEvadeMode(), boss_rotface::boss_rotfaceAI::EnterEvadeMode(), boss_sindragosa::boss_sindragosaAI::EnterEvadeMode(), boss_the_lich_king::boss_the_lich_kingAI::EnterEvadeMode(), boss_four_horsemen::boss_four_horsemenAI::EnterEvadeMode(), boss_kologarn::EnterEvadeMode(), boss_illidan_stormrage::EnterEvadeMode(), boss_illidari_council::EnterEvadeMode(), boss_the_lurker_below::EnterEvadeMode(), boss_harbinger_skyriss::EnterEvadeMode(), boss_ouro::EnterEvadeMode(), boss_ahune::EnterEvadeMode(), boss_halazzi::EnterPhase(), boss_bug_trio::EvadeAllBosses(), boss_sartharion_tenebron::ExecuteEvent(), boss_sartharion_shadron::ExecuteEvent(), boss_sartharion_vesperon::ExecuteEvent(), boss_ahune::ExecuteEvent(), boss_krik_thir::boss_krik_thirAI::GetData(), boss_hodir::GetHardmodeChest(), boss_thorim::GetThorimObject(), boss_twinemperorsAI::GetTwin(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::GoToMinchar(), boss_netherspite::HandleDoors(), boss_warbringer_omrogg::HandleHeadTalk(), boss_urok_doomhowl::boss_urok_doomhowlAI::InitializeAI(), boss_majordomo::boss_majordomoAI::InitializeAI(), boss_priestess_delrissa::InitializeAI(), boss_felmyst::InitializeAI(), boss_taldaram::InitializeAI(), boss_flame_leviathan::InitializeAI(), boss_ambassador_hellmaw::InitializeAI(), boss_warchief_kargath_bladefist::InitializeAI(), boss_aeonus::IsSummonedBy(), boss_emperor_dagran_thaurissan::boss_draganthaurissanAI::JustDied(), boss_gyth::boss_gythAI::JustDied(), boss_overlord_wyrmthalak::boss_overlordwyrmthalakAI::JustDied(), boss_pyroguard_emberseer::boss_pyroguard_emberseerAI::JustDied(), boss_rend_blackhand::boss_rend_blackhandAI::JustDied(), boss_solakar_flamewreath::boss_solakar_flamewreathAI::JustDied(), boss_victor_nefarius::boss_victor_nefariusAI::JustDied(), boss_razorgore::boss_razorgoreAI::JustDied(), boss_attumen::JustDied(), boss_shade_of_aran::JustDied(), boss_priestess_delrissa::JustDied(), boss_vexallus::JustDied(), boss_darkmaster_gandling::boss_darkmaster_gandlingAI::JustDied(), boss_baroness_anastari::boss_baroness_anastariAI::JustDied(), boss_sacrolash::JustDied(), boss_alythess::JustDied(), boss_zuljin::JustDied(), boss_mandokir::boss_mandokirAI::JustDied(), boss_thekal::JustDied(), boss_rajaxx::JustDied(), boss_eye_of_cthun::JustDied(), boss_amanitar::JustDied(), boss_sartharion_dragonAI::JustDied(), boss_prince_valanar_icc::boss_prince_valanarAI::JustDied(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::JustDied(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::JustDied(), boss_festergut::boss_festergutAI::JustDied(), boss_rotface::boss_rotfaceAI::JustDied(), boss_sindragosa::boss_sindragosaAI::JustDied(), boss_sister_svalna::boss_sister_svalnaAI::JustDied(), boss_malygos::JustDied(), boss_sjonnir::boss_sjonnirAI::JustDied(), boss_flame_leviathan::JustDied(), boss_kologarn::JustDied(), boss_xt002::JustDied(), boss_talon_king_ikiss::JustDied(), boss_ahune::JustDied(), boss_hydromancer_thespia::JustDied(), boss_warlord_kalithresh::JustDied(), boss_high_king_maulgar::JustDied(), boss_dalliah_the_doomsayer::JustDied(), boss_lord_valthalak::boss_lord_valthalakAI::JustDied(), boss_moroes::JustDied(), boss_felblood_kaelthas::JustDied(), boss_brutallus::JustDied(), boss_felmyst::JustDied(), boss_azgalor::JustDied(), boss_buru::JustDied(), boss_kurinnaxx::JustDied(), boss_bug_trio::JustDied(), boss_cthun::JustDied(), boss_baltharus_the_warborn::boss_baltharus_the_warbornAI::JustDied(), boss_halion::boss_halionAI::JustDied(), boss_novos::JustDied(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::JustDied(), boss_anubrekhan::JustDied(), boss_four_horsemen::boss_four_horsemenAI::JustDied(), boss_thaddius::boss_thaddiusAI::JustDied(), boss_shade_of_akama::JustDied(), boss_fathomlord_karathress::JustDied(), boss_warchief_kargath_bladefist::JustDied(), boss_sartharion_dragonAI::JustEngagedWith(), boss_magmus::boss_magmusAI::JustEngagedWith(), boss_razorgore::boss_razorgoreAI::JustEngagedWith(), boss_shade_of_aran::JustEngagedWith(), boss_darkmaster_gandling::boss_darkmaster_gandlingAI::JustEngagedWith(), boss_hakkar::boss_hakkarAI::JustEngagedWith(), boss_volazj::JustEngagedWith(), boss_anub_arak::JustEngagedWith(), boss_sartharion::JustEngagedWith(), boss_lord_marrowgar::JustEngagedWith(), boss_sister_svalna::boss_sister_svalnaAI::JustEngagedWith(), boss_sjonnir::boss_sjonnirAI::JustEngagedWith(), boss_flame_leviathan::JustEngagedWith(), boss_freya::JustEngagedWith(), boss_hodir::JustEngagedWith(), boss_ignis::JustEngagedWith(), boss_kologarn::JustEngagedWith(), boss_mimiron::JustEngagedWith(), boss_thorim::JustEngagedWith(), boss_xt002::JustEngagedWith(), boss_dalliah_the_doomsayer::JustEngagedWith(), boss_the_lich_king::boss_the_lich_kingAI::JustEngagedWith(), npc_green_dragon_combat_trigger::npc_green_dragon_combat_triggerAI::JustEngagedWith(), boss_sacrolash::JustEngagedWith(), boss_alythess::JustEngagedWith(), boss_onyxia::JustEngagedWith(), boss_buru::JustEngagedWith(), boss_vem::JustEngagedWith(), boss_krik_thir::boss_krik_thirAI::JustEngagedWith(), boss_halion::boss_halionAI::JustEngagedWith(), boss_trollgore::boss_trollgoreAI::JustEngagedWith(), boss_prince_valanar_icc::boss_prince_valanarAI::JustEngagedWith(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::JustEngagedWith(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::JustEngagedWith(), boss_festergut::boss_festergutAI::JustEngagedWith(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::JustEngagedWith(), boss_professor_putricide::boss_professor_putricideAI::JustEngagedWith(), boss_rotface::boss_rotfaceAI::JustEngagedWith(), boss_sindragosa::boss_sindragosaAI::JustEngagedWith(), boss_kelthuzad::boss_kelthuzadAI::JustEngagedWith(), boss_patchwerk::boss_patchwerkAI::JustEngagedWith(), boss_illidan_stormrage::JustEngagedWith(), boss_fathomlord_karathress::JustEngagedWith(), boss_magtheridon::JustEngagedWith(), boss_warchief_kargath_bladefist::JustEngagedWith(), boss_majordomo::boss_majordomoAI::JustReachedHome(), boss_arlokk::boss_arlokkAI::JustReachedHome(), boss_aeonus::JustReachedHome(), boss_prince_valanar_icc::boss_prince_valanarAI::JustReachedHome(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::JustReachedHome(), boss_festergut::boss_festergutAI::JustReachedHome(), boss_lord_marrowgar::JustReachedHome(), boss_professor_putricide::boss_professor_putricideAI::JustReachedHome(), boss_rotface::boss_rotfaceAI::JustReachedHome(), npc_green_dragon_combat_trigger::npc_green_dragon_combat_triggerAI::JustReachedHome(), boss_flame_leviathan::JustReachedHome(), boss_fathomlord_karathress::JustReachedHome(), boss_attumen::JustSummoned(), boss_eye_of_cthun::JustSummoned(), boss_sartharion_dragonAI::JustSummoned(), boss_midnight::KilledUnit(), boss_mandokir::boss_mandokirAI::KilledUnit(), boss_anubrekhan::KilledUnit(), boss_razorscale::KilledUnit(), boss_faerlina::boss_faerlinaAI::KilledUnit(), boss_four_horsemen::boss_four_horsemenAI::KilledUnit(), boss_gluth::boss_gluthAI::KilledUnit(), boss_gothik::boss_gothikAI::KilledUnit(), boss_grobbulus::boss_grobbulusAI::KilledUnit(), boss_heigan::KilledUnit(), boss_kelthuzad::boss_kelthuzadAI::KilledUnit(), boss_loatheb::boss_loathebAI::KilledUnit(), boss_maexxna::boss_maexxnaAI::KilledUnit(), boss_noth::boss_nothAI::KilledUnit(), boss_patchwerk::boss_patchwerkAI::KilledUnit(), boss_sapphiron::boss_sapphironAI::KilledUnit(), boss_thaddius::boss_thaddiusAI::KilledUnit(), boss_mandokir::boss_mandokirAI::MovementInform(), boss_bug_trio::MovementInform(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::MovementInform(), boss_professor_putricide::boss_professor_putricideAI::MovementInform(), boss_lady_vashj::MovementInform(), boss_shade_of_akama::MovementInform(), boss_pyroguard_emberseer::boss_pyroguard_emberseerAI::OpenDoors(), boss_kologarn::PassengerBoarded(), boss_kaelthas::PrepareAdvisors(), boss_magmus::boss_magmusAI::Reset(), boss_gyth::boss_gythAI::Reset(), boss_pyroguard_emberseer::boss_pyroguard_emberseerAI::Reset(), boss_rend_blackhand::boss_rend_blackhandAI::Reset(), boss_razorgore::boss_razorgoreAI::Reset(), boss_majordomo::boss_majordomoAI::Reset(), boss_shade_of_aran::Reset(), boss_priestess_delrissa::Reset(), boss_darkmaster_gandling::boss_darkmaster_gandlingAI::Reset(), boss_baroness_anastari::boss_baroness_anastariAI::Reset(), boss_sacrolash::Reset(), boss_alythess::Reset(), boss_felmyst::Reset(), boss_kalecgos::Reset(), boss_kiljaeden::Reset(), boss_mandokir::boss_mandokirAI::Reset(), boss_thekal::Reset(), boss_archimonde::Reset(), boss_onyxia::Reset(), boss_bug_trio::Reset(), boss_ouro::Reset(), boss_volazj::Reset(), boss_anub_arak::Reset(), boss_krik_thir::boss_krik_thirAI::Reset(), boss_sartharion::Reset(), boss_sartharion_dragonAI::Reset(), boss_general_zarithrian::boss_general_zarithrianAI::Reset(), boss_novos::Reset(), boss_prince_valanar_icc::boss_prince_valanarAI::Reset(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::Reset(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::Reset(), boss_lord_marrowgar::Reset(), boss_professor_putricide::boss_professor_putricideAI::Reset(), boss_the_lich_king::boss_the_lich_kingAI::Reset(), npc_green_dragon_combat_trigger::npc_green_dragon_combat_triggerAI::Reset(), boss_kelthuzad::boss_kelthuzadAI::Reset(), boss_thaddius::boss_thaddiusAI::Reset(), boss_malygos::Reset(), boss_loken::Reset(), boss_volkhan::Reset(), boss_sjonnir::boss_sjonnirAI::Reset(), boss_flame_leviathan::Reset(), boss_hodir::Reset(), boss_ignis::Reset(), boss_kologarn::Reset(), boss_mimiron::Reset(), boss_xt002::Reset(), boss_illidan_stormrage::Reset(), boss_fathomlord_karathress::Reset(), boss_warlord_kalithresh::Reset(), boss_magtheridon::Reset(), boss_grand_warlock_nethekurse::Reset(), boss_warchief_kargath_bladefist::Reset(), npc_warden_mellichar::npc_warden_mellicharAI::Reset(), boss_dalliah_the_doomsayer::Reset(), boss_wrath_scryer_soccothrates::Reset(), boss_pathaleon_the_calculator::Reset(), boss_mimiron::ResetGameObjects(), boss_thekal::ReviveZealot(), boss_magtheridon::ScheduleCombatEvents(), boss_ayamiss::ScheduleTasks(), boss_cthun::ScheduleTasks(), boss_loken::ScheduleTasks(), boss_sjonnir::boss_sjonnirAI::ScheduleTasks(), boss_pyroguard_emberseer::boss_pyroguard_emberseerAI::SetData(), boss_darkmaster_gandling::boss_darkmaster_gandlingAI::SetGate(), boss_kaelthas::SetRoomState(), boss_victor_nefarius::boss_victor_nefariusAI::sGossipSelect(), boss_shade_of_akama::SpellHit(), boss_attumen::SpellHit(), boss_freya::SpellHit(), boss_hodir::SpellHit(), boss_mimiron::SpellHit(), boss_faerlina::boss_faerlinaAI::SpellHit(), boss_razorscale::SpellHit(), boss_thorim::SpellHit(), boss_onyxia::SpellHitTarget(), boss_heigan::StartFightPhase(), boss_ahune::Submerge(), boss_kologarn::SummonedCreatureDespawn(), boss_rend_blackhand::boss_rend_blackhandAI::SummonedCreatureDespawn(), boss_priestess_delrissa::SummonedCreatureDies(), boss_sartharion_shadron::SummonedCreatureDies(), boss_sartharion_vesperon::SummonedCreatureDies(), boss_loatheb::boss_loathebAI::SummonedCreatureDies(), boss_majordomo::boss_majordomoAI::SummonedCreatureDies(), npc_warden_mellichar::npc_warden_mellicharAI::SummonedCreatureDies(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::SummonWaveP1(), boss_flame_leviathan::TurnGates(), boss_flame_leviathan::TurnHealStations(), boss_pyroguard_emberseer::boss_pyroguard_emberseerAI::UpdateAI(), boss_rend_blackhand::boss_rend_blackhandAI::UpdateAI(), boss_solakar_flamewreath::boss_solakar_flamewreathAI::UpdateAI(), boss_majordomo::boss_majordomoAI::UpdateAI(), boss_mandokir::boss_mandokirAI::UpdateAI(), boss_jedoga_shadowseeker::UpdateAI(), boss_sartharion::UpdateAI(), boss_general_zarithrian::boss_general_zarithrianAI::UpdateAI(), boss_halion::boss_halionAI::UpdateAI(), boss_prince_valanar_icc::boss_prince_valanarAI::UpdateAI(), boss_festergut::boss_festergutAI::UpdateAI(), boss_professor_putricide::boss_professor_putricideAI::UpdateAI(), boss_rotface::boss_rotfaceAI::UpdateAI(), boss_gothik::boss_gothikAI::UpdateAI(), boss_kelthuzad::boss_kelthuzadAI::UpdateAI(), boss_sapphiron::boss_sapphironAI::UpdateAI(), boss_malygos::UpdateAI(), boss_hodir::UpdateAI(), boss_mimiron::UpdateAI(), boss_razorscale::UpdateAI(), boss_thorim::UpdateAI(), npc_warden_mellichar::npc_warden_mellicharAI::UpdateAI(), and boss_pyroguard_emberseer::boss_pyroguard_emberseerAI::UpdateRunes().
summons
SummonList BossAI::summons protected
Referenced by _JustDied(), _Reset(), boss_janalai::Boom(), boss_moroes::CheckGuestsInRoom(), boss_volazj::CheckPhaseMinions(), boss_sartharion_dragonAI::ClearInstance(), boss_sartharion::DamageTaken(), boss_freya::DamageTaken(), boss_hodir::DamageTaken(), boss_felblood_kaelthas::DamageTaken(), boss_the_lich_king::boss_the_lich_kingAI::DamageTaken(), boss_thorim::DamageTaken(), boss_victor_nefarius::boss_victor_nefariusAI::DoAction(), boss_apothecary_hummel::boss_apothecary_hummelAI::DoAction(), boss_taldaram::DoAction(), boss_prince_valanar_icc::boss_prince_valanarAI::DoAction(), boss_the_lich_king::boss_the_lich_kingAI::DoAction(), boss_drakkari_colossus::boss_drakkari_colossusAI::DoAction(), boss_illidan_stormrage::DoAction(), boss_reliquary_of_souls::boss_reliquary_of_soulsAI::DoAction(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::EmpowerCultist(), boss_anub_arak::EnterEvadeMode(), boss_moorabi::boss_moorabiAI::EnterEvadeMode(), boss_the_lich_king::boss_the_lich_kingAI::EnterEvadeMode(), boss_mimiron::EnterEvadeMode(), boss_ahune::EnterEvadeMode(), boss_halazzi::EnterPhase(), boss_sartharion_tenebron::ExecuteEvent(), boss_sartharion_shadron::ExecuteEvent(), boss_sartharion_vesperon::ExecuteEvent(), boss_auriaya::ExecuteEvent(), boss_kaelthas::ExecuteMiddleEvent(), boss_professor_putricide::boss_professor_putricideAI::GetData(), boss_moroes::GetRandomGuest(), boss_volkhan::HasActiveGolem(), boss_janalai::HatchAllEggs(), boss_moroes::InitializeGuests(), boss_kaelthas::IntroduceNewAdvisor(), boss_sacrolash::JustDied(), boss_alythess::JustDied(), boss_zuljin::JustDied(), boss_sartharion_dragonAI::JustDied(), boss_prince_valanar_icc::boss_prince_valanarAI::JustDied(), boss_flame_leviathan::JustDied(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::JustDied(), boss_auriaya::JustDied(), boss_illidan_stormrage::JustDied(), boss_reliquary_of_souls::boss_reliquary_of_soulsAI::JustDied(), boss_priestess_delrissa::JustEngagedWith(), boss_zuljin::JustEngagedWith(), boss_muru::JustEngagedWith(), boss_hexlord_malacrass::JustEngagedWith(), boss_novos::JustEngagedWith(), boss_sindragosa::boss_sindragosaAI::JustEngagedWith(), boss_anubrekhan::JustEngagedWith(), boss_faerlina::boss_faerlinaAI::JustEngagedWith(), boss_thaddius::boss_thaddiusAI::JustEngagedWith(), boss_high_astromancer_solarian::JustEngagedWith(), boss_anubrekhan::JustSummoned(), boss_thaddius::boss_thaddiusAI::JustSummoned(), boss_auriaya::JustSummoned(), boss_flame_leviathan::JustSummoned(), boss_ossirian::JustSummoned(), JustSummoned(), boss_gyth::boss_gythAI::JustSummoned(), boss_rend_blackhand::boss_rend_blackhandAI::JustSummoned(), boss_razorgore::boss_razorgoreAI::JustSummoned(), boss_curator::JustSummoned(), boss_nightbane::JustSummoned(), boss_priestess_delrissa::JustSummoned(), boss_vexallus::JustSummoned(), boss_sacrolash::JustSummoned(), boss_hazzarah::JustSummoned(), boss_isalien::JustSummoned(), boss_onyxia::JustSummoned(), boss_eye_of_cthun::JustSummoned(), boss_jedoga_shadowseeker::JustSummoned(), boss_taldaram::JustSummoned(), boss_hadronox::JustSummoned(), boss_sartharion::JustSummoned(), boss_sartharion_tenebron::JustSummoned(), boss_baltharus_the_warborn::boss_baltharus_the_warbornAI::JustSummoned(), boss_general_zarithrian::boss_general_zarithrianAI::JustSummoned(), boss_halion::boss_halionAI::JustSummoned(), boss_novos::JustSummoned(), boss_trollgore::boss_trollgoreAI::JustSummoned(), boss_drakkari_colossus::boss_drakkari_colossusAI::JustSummoned(), boss_gal_darah::JustSummoned(), boss_prince_valanar_icc::boss_prince_valanarAI::JustSummoned(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::JustSummoned(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::JustSummoned(), boss_professor_putricide::boss_professor_putricideAI::JustSummoned(), boss_rotface::boss_rotfaceAI::JustSummoned(), boss_sindragosa::boss_sindragosaAI::JustSummoned(), boss_the_lich_king::boss_the_lich_kingAI::JustSummoned(), boss_malygos::JustSummoned(), boss_anomalus::JustSummoned(), boss_magus_telestra::JustSummoned(), boss_ormorok::JustSummoned(), boss_volkhan::JustSummoned(), boss_grandmaster_vorpil::JustSummoned(), boss_gurtogg_bloodboil::JustSummoned(), boss_illidan_stormrage::JustSummoned(), boss_reliquary_of_souls::boss_reliquary_of_soulsAI::JustSummoned(), boss_supremus::JustSummoned(), boss_teron_gorefiend::JustSummoned(), boss_fathomlord_karathress::JustSummoned(), boss_lady_vashj::JustSummoned(), boss_morogrim_tidewalker::JustSummoned(), boss_omor_the_unscarred::JustSummoned(), boss_vazruden_the_herald::JustSummoned(), boss_warchief_kargath_bladefist::JustSummoned(), npc_warden_mellichar::npc_warden_mellicharAI::JustSummoned(), boss_kaelthas::JustSummoned(), boss_nethermancer_sepethrea::JustSummoned(), boss_terestian_illhoof::JustSummoned(), boss_broggok::JustSummoned(), boss_ayamiss::JustSummoned(), boss_zuljin::MovementInform(), boss_illidan_stormrage::MovementInform(), boss_kaelthas::MovementInform(), boss_jedoga_shadowseeker::MovementInform(), boss_the_lich_king::boss_the_lich_kingAI::MovementInform(), boss_kaelthas::PhaseEnchantedWeaponsExecute(), boss_kaelthas::PrepareAdvisors(), boss_gyth::boss_gythAI::Reset(), boss_rend_blackhand::boss_rend_blackhandAI::Reset(), boss_razorgore::boss_razorgoreAI::Reset(), boss_majordomo::boss_majordomoAI::Reset(), boss_felblood_kaelthas::Reset(), boss_priestess_delrissa::Reset(), boss_isalien::Reset(), boss_prince_valanar_icc::boss_prince_valanarAI::Reset(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::Reset(), npc_green_dragon_combat_trigger::npc_green_dragon_combat_triggerAI::Reset(), boss_faerlina::boss_faerlinaAI::Reset(), boss_thaddius::boss_thaddiusAI::Reset(), boss_auriaya::Reset(), boss_flame_leviathan::Reset(), boss_hodir::Reset(), boss_illidan_stormrage::ScheduleAbilities(), boss_selin_fireheart::SelectNearestCrystal(), boss_sartharion::SendLavaWaves(), boss_vazruden_the_herald::SetData(), boss_malchezaar::SpawnInfernal(), boss_the_lich_king::boss_the_lich_kingAI::SpellHitTarget(), boss_taldaram::SpellHitTarget(), boss_flame_leviathan::SummonedCreatureDespawn(), boss_rend_blackhand::boss_rend_blackhandAI::SummonedCreatureDespawn(), SummonedCreatureDespawn(), boss_ossirian::SummonedCreatureDespawn(), boss_drakkari_colossus::boss_drakkari_colossusAI::SummonedCreatureDespawn(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::SummonedCreatureDespawn(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::SummonedCreatureDespawn(), boss_supremus::SummonedCreatureDespawn(), boss_hydross_the_unstable::SummonedCreatureDespawn(), boss_vazruden_the_herald::SummonedCreatureDespawn(), SummonedCreatureDespawnAll(), boss_rend_blackhand::boss_rend_blackhandAI::SummonedCreatureDies(), boss_moam::SummonedCreatureDies(), boss_sartharion_shadron::SummonedCreatureDies(), boss_the_lurker_below::SummonedCreatureDies(), boss_victor_nefarius::boss_victor_nefariusAI::SummonedCreatureDies(), boss_ragnaros::boss_ragnarosAI::SummonedCreatureDies(), boss_hazzarah::SummonedCreatureDies(), boss_krik_thir::boss_krik_thirAI::SummonedCreatureDies(), boss_drakkari_colossus::boss_drakkari_colossusAI::SummonedCreatureDies(), boss_anzu::SummonedCreatureDies(), boss_reliquary_of_souls::boss_reliquary_of_soulsAI::SummonedCreatureDies(), boss_the_black_stalker::SummonedCreatureDies(), boss_vazruden_the_herald::SummonedCreatureDies(), npc_warden_mellichar::npc_warden_mellicharAI::SummonedCreatureDies(), boss_high_botanist_freywinn::SummonedCreatureDies(), boss_vexallus::SummonedCreatureDies(), boss_viscidus::SummonedCreatureDies(), boss_jedoga_shadowseeker::SummonedCreatureDies(), boss_sartharion::SummonLavaWaves(), boss_moroes::UpdateAI(), boss_jedoga_shadowseeker::UpdateAI(), boss_sartharion::UpdateAI(), boss_halion::boss_halionAI::UpdateAI(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::UpdateAI(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::UpdateAI(), boss_professor_putricide::boss_professor_putricideAI::UpdateAI(), boss_the_lich_king::boss_the_lich_kingAI::UpdateAI(), boss_thaddius::boss_thaddiusAI::UpdateAI(), boss_malygos::UpdateAI(), boss_ionar::UpdateAI(), boss_volkhan::UpdateAI(), boss_flame_leviathan::UpdateAI(), boss_freya::UpdateAI(), boss_vezax::UpdateAI(), boss_mimiron::UpdateAI(), boss_thorim::UpdateAI(), npc_warden_mellichar::npc_warden_mellicharAI::UpdateAI(), and boss_vazruden_the_herald::UpdateAI().
The documentation for this class was generated from the following files:
azerothcore-wotlk/src/server/game/AI/ScriptedAI/ScriptedCreature.h
azerothcore-wotlk/src/server/game/AI/ScriptedAI/ScriptedCreature.cpp