AzerothCore Doxygen
LuaMap Namespace Reference
Functions
int IsArena (lua_State *L, Map *map)
int IsBattleground (lua_State *L, Map *map)
int IsDungeon (lua_State *L, Map *map)
int IsEmpty (lua_State *L, Map *map)
int IsHeroic (lua_State *L, Map *map)
int IsRaid (lua_State *L, Map *map)
int GetName (lua_State *L, Map *map)
int GetHeight (lua_State *L, Map *map)
int GetDifficulty (lua_State *L, Map *map)
int GetInstanceId (lua_State *L, Map *map)
int GetPlayerCount (lua_State *L, Map *map)
int GetMapId (lua_State *L, Map *map)
int GetAreaId (lua_State *L, Map *map)
int GetWorldObject (lua_State *L, Map *map)
int SetWeather (lua_State *L, Map *map)
int GetInstanceData (lua_State *L, Map *map)
int SaveInstanceData (lua_State *, Map *map)
int GetPlayers (lua_State *L, Map *map)
Function Documentation
GetAreaId()
int LuaMap::GetAreaId (lua_State * L, Map * map)
Returns the area ID of the [Map] at the specified X, Y, and Z coordinates.
Parameters
float x
float y
float z
uint32 phasemask = PHASEMASK_NORMAL
Returns
uint32 areaId
    {
        float x = Eluna::CHECKVAL<float>(L, 2);
        float y = Eluna::CHECKVAL<float>(L, 3);
        float z = Eluna::CHECKVAL<float>(L, 4);
#if defined TRINITY || defined AZEROTHCORE
        float phasemask = Eluna::CHECKVAL<uint32>(L, 5, PHASEMASK_NORMAL);
        Eluna::Push(L, map->GetAreaId(phasemask, x, y, z));
#else
        Eluna::Push(L, map->GetTerrain()->GetAreaId(x, y, z));
#endif
        return 1;
    }
References Map::GetAreaId(), PHASEMASK_NORMAL, and Eluna::Push().
GetDifficulty()
int LuaMap::GetDifficulty (lua_State * L, Map * map)
Returns the difficulty of the [Map].
Always returns 0 if the expansion is pre-TBC.
Returns
int32 difficulty
    {
#ifndef CLASSIC
        Eluna::Push(L, map->GetDifficulty());
#else
        Eluna::Push(L, (Difficulty)0);
#endif
        return 1;
    }
References Map::GetDifficulty(), and Eluna::Push().
GetHeight()
int LuaMap::GetHeight (lua_State * L, Map * map)
Returns the height of the [Map] at the given X and Y coordinates.
In case of no height found nil is returned
Parameters
float x
float y
Returns
float z
    {
        float x = Eluna::CHECKVAL<float>(L, 2);
        float y = Eluna::CHECKVAL<float>(L, 3);
#if (defined(TBC) || defined(CLASSIC))
        float z = map->GetHeight(x, y, MAX_HEIGHT);
#else
        uint32 phasemask = Eluna::CHECKVAL<uint32>(L, 4, 1);
        float z = map->GetHeight(phasemask, x, y, MAX_HEIGHT);
#endif
        if (z != INVALID_HEIGHT)
            Eluna::Push(L, z);
        return 1;
    }
References Map::GetHeight(), INVALID_HEIGHT, MAX_HEIGHT, and Eluna::Push().
GetInstanceData()
int LuaMap::GetInstanceData (lua_State * L, Map * map)
Gets the instance data table for the [Map], if it exists.
The instance must be scripted using Eluna for this to succeed. If the instance is scripted in C++ this will return nil.
Returns
table instance_data : instance data table, or nil
    {
#if defined TRINITY || AZEROTHCORE
        ElunaInstanceAI* iAI = NULL;
        if (InstanceMap* inst = map->ToInstanceMap())
            iAI = dynamic_cast<ElunaInstanceAI*>(inst->GetInstanceScript());
#else
        ElunaInstanceAI* iAI = dynamic_cast<ElunaInstanceAI*>(map->GetInstanceData());
#endif
        if (iAI)
            Eluna::GetEluna(L)->PushInstanceData(L, iAI, false);
        else
            Eluna::Push(L); // nil
        return 1;
    }
References Eluna::GetEluna(), Eluna::Push(), Eluna::PushInstanceData(), and Map::ToInstanceMap().
GetInstanceId()
int LuaMap::GetInstanceId (lua_State * L, Map * map)
Returns the instance ID of the [Map].
Returns
uint32 instanceId
    {
        Eluna::Push(L, map->GetInstanceId());
        return 1;
    }
References Map::GetInstanceId(), and Eluna::Push().
GetMapId()
int LuaMap::GetMapId (lua_State * L, Map * map)
Returns the ID of the [Map].
Returns
uint32 mapId
    {
        Eluna::Push(L, map->GetId());
        return 1;
    }
References Map::GetId(), and Eluna::Push().
GetName()
int LuaMap::GetName (lua_State * L, Map * map)
Returns the name of the [Map].
Returns
string mapName
    {
        Eluna::Push(L, map->GetMapName());
        return 1;
    }
References Map::GetMapName(), and Eluna::Push().
GetPlayerCount()
int LuaMap::GetPlayerCount (lua_State * L, Map * map)
Returns the player count currently on the [Map] (excluding GMs).
Returns
uint32 playerCount
    {
        Eluna::Push(L, map->GetPlayersCountExceptGMs());
        return 1;
    }
References Map::GetPlayersCountExceptGMs(), and Eluna::Push().
GetPlayers()
int LuaMap::GetPlayers (lua_State * L, Map * map)
Returns a table with all the current [Player]s in the map
enum TeamId
{
    TEAM_ALLIANCE = 0,
    TEAM_HORDE = 1,
    TEAM_NEUTRAL = 2
};
Parameters
[TeamId] team : optional check team of the [Player], Alliance, Horde or Neutral (All)
Returns
table mapPlayers
    {
        uint32 team = Eluna::CHECKVAL<uint32>(L, 2, TEAM_NEUTRAL);
        lua_newtable(L);
        int tbl = lua_gettop(L);
        uint32 i = 0;
        Map::PlayerList const& players = map->GetPlayers();
        for (Map::PlayerList::const_iterator itr = players.begin(); itr != players.end(); ++itr)
        {
#if defined TRINITY || AZEROTHCORE
            Player* player = itr->GetSource();
#else
            Player* player = itr->getSource();
#endif
            if (!player)
                continue;
            if (player->GetSession() && (team >= TEAM_NEUTRAL || player->GetTeamId() == team))
            {
                Eluna::Push(L, player);
                lua_rawseti(L, tbl, ++i);
            }
        }
        lua_settop(L, tbl);
        return 1;
    }
References MapRefMgr::begin(), MapRefMgr::end(), Map::GetPlayers(), Player::GetSession(), Player::GetTeamId(), lua_gettop(), lua_newtable, lua_rawseti(), lua_settop(), Eluna::Push(), and TEAM_NEUTRAL.
GetWorldObject()
int LuaMap::GetWorldObject (lua_State * L, Map * map)
Returns a [WorldObject] by its GUID from the map if it is spawned.
Parameters
ObjectGuid guid
Returns
[WorldObject] object
    {
        ObjectGuid guid = Eluna::CHECKVAL<ObjectGuid>(L, 2);
#if defined TRINITY || AZEROTHCORE
        switch (guid.GetHigh())
        {
            case HIGHGUID_PLAYER:
                Eluna::Push(L, eObjectAccessor()GetPlayer(map, guid));
                break;
            case HIGHGUID_TRANSPORT:
            case HIGHGUID_MO_TRANSPORT:
            case HIGHGUID_GAMEOBJECT:
                Eluna::Push(L, map->GetGameObject(guid));
                break;
            case HIGHGUID_VEHICLE:
            case HIGHGUID_UNIT:
                Eluna::Push(L, map->GetCreature(guid));
                break;
            case HIGHGUID_PET:
                Eluna::Push(L, map->GetPet(guid));
                break;
            case HIGHGUID_DYNAMICOBJECT:
                Eluna::Push(L, map->GetDynamicObject(guid));
                break;
            case HIGHGUID_CORPSE:
                Eluna::Push(L, map->GetCorpse(guid));
                break;
            default:
                break;
        }
#else
        Eluna::Push(L, map->GetWorldObject(guid));
#endif
        return 1;
    }
References eObjectAccessor, Map::GetCorpse(), Map::GetCreature(), Map::GetDynamicObject(), Map::GetGameObject(), ObjectGuid::GetHigh(), Map::GetPet(), and Eluna::Push().
IsArena()
int LuaMap::IsArena (lua_State * L, Map * map)
Returns true if the [Map] is an arena [BattleGround], false otherwise.
Returns
bool isArena
    {
        Eluna::Push(L, map->IsBattleArena());
        return 1;
    }
References Map::IsBattleArena(), and Eluna::Push().
IsBattleground()
int LuaMap::IsBattleground (lua_State * L, Map * map)
Returns true if the [Map] is a non-arena [BattleGround], false otherwise.
Returns
bool isBattleGround
    {
#if defined TRINITY || AZEROTHCORE
        Eluna::Push(L, map->IsBattleground());
#else
        Eluna::Push(L, map->IsBattleGround());
#endif
        return 1;
    }
References Map::IsBattleground(), and Eluna::Push().
IsDungeon()
int LuaMap::IsDungeon (lua_State * L, Map * map)
Returns true if the [Map] is a dungeon, false otherwise.
Returns
bool isDungeon
    {
        Eluna::Push(L, map->IsDungeon());
        return 1;
    }
References Map::IsDungeon(), and Eluna::Push().
IsEmpty()
int LuaMap::IsEmpty (lua_State * L, Map * map)
Returns true if the [Map] has no [Player]s, false otherwise.
Returns
bool IsEmpty
    {
        Eluna::Push(L, map->IsEmpty());
        return 1;
    }
References LinkedListHead::IsEmpty(), and Eluna::Push().
IsHeroic()
int LuaMap::IsHeroic (lua_State * L, Map * map)
Returns true if the [Map] is a heroic, false otherwise.
Returns
bool isHeroic
    {
        Eluna::Push(L, map->IsHeroic());
        return 1;
    }
References Map::IsHeroic(), and Eluna::Push().
IsRaid()
int LuaMap::IsRaid (lua_State * L, Map * map)
Returns true if the [Map] is a raid, false otherwise.
Returns
bool isRaid
    {
        Eluna::Push(L, map->IsRaid());
        return 1;
    }
References Map::IsRaid(), and Eluna::Push().
SaveInstanceData()
int LuaMap::SaveInstanceData (lua_State * , Map * map)
Saves the [Map]'s instance data to the database.
    {
#if defined TRINITY || AZEROTHCORE
        ElunaInstanceAI* iAI = NULL;
        if (InstanceMap* inst = map->ToInstanceMap())
            iAI = dynamic_cast<ElunaInstanceAI*>(inst->GetInstanceScript());
#else
        ElunaInstanceAI* iAI = dynamic_cast<ElunaInstanceAI*>(map->GetInstanceData());
#endif
        if (iAI)
            iAI->SaveToDB();
        return 0;
    }
References Map::ToInstanceMap().
SetWeather()
int LuaMap::SetWeather (lua_State * L, Map * map)
Sets the [Weather] type based on [WeatherType] and grade supplied.
enum WeatherType
{
    WEATHER_TYPE_FINE       = 0,
    WEATHER_TYPE_RAIN       = 1,
    WEATHER_TYPE_SNOW       = 2,
    WEATHER_TYPE_STORM      = 3,
    WEATHER_TYPE_THUNDERS   = 86,
    WEATHER_TYPE_BLACKRAIN  = 90
};
Parameters
uint32 zone : id of the zone to set the weather for
[WeatherType] type : the [WeatherType], see above available weather types
float grade : the intensity/grade of the [Weather], ranges from 0 to 1
    {
        (void)map; // ensure that the variable is referenced in order to pass compiler checks
        uint32 zoneId = Eluna::CHECKVAL<uint32>(L, 2);
        uint32 weatherType = Eluna::CHECKVAL<uint32>(L, 3);
        float grade = Eluna::CHECKVAL<float>(L, 4);
#if defined TRINITY
        if (Weather * weather = map->GetOrGenerateZoneDefaultWeather(zoneId))
            weather->SetWeather((WeatherType)weatherType, grade);
#elif defined AZEROTHCORE
        Weather* weather = WeatherMgr::FindWeather(zoneId);
        if (!weather)
            weather = WeatherMgr::AddWeather(zoneId);
        if (weather)
            weather->SetWeather((WeatherType)weatherType, grade);
#else
        if (Weather::IsValidWeatherType(weatherType))
            map->SetWeather(zoneId, (WeatherType)weatherType, grade, false);
#endif
        return 0;
    }
References WeatherMgr::AddWeather(), WeatherMgr::FindWeather(), and Weather::SetWeather().