AzerothCore Doxygen
quest_commandscript Class Reference
Public Member Functions
quest_commandscript ()
ChatCommandTable GetCommands () const override
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
uint16 GetTotalAvailableHooks ()
Static Public Member Functions
static bool HandleQuestAdd (ChatHandler *handler, Quest const *quest, Optional< PlayerIdentifier > playerTarget)
static bool HandleQuestRemove (ChatHandler *handler, Quest const *quest, Optional< PlayerIdentifier > playerTarget)
static bool HandleQuestComplete (ChatHandler *handler, Quest const *quest, Optional< PlayerIdentifier > playerTarget)
static bool HandleQuestReward (ChatHandler *handler, Quest const *quest, Optional< PlayerIdentifier > playerTarget)
static bool HandleQuestStatus (ChatHandler *handler, Quest const *quest, Optional< PlayerIdentifier > playerTarget)
Additional Inherited Members
Protected Member Functions inherited from CommandScript
CommandScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name, uint16 totalAvailableHooks=0)
virtual ~ScriptObject ()=default
Detailed Description
Constructor & Destructor Documentation
quest_commandscript()
quest_commandscript::quest_commandscript () inline
: CommandScript("quest_commandscript") { }
Member Function Documentation
GetCommands()
ChatCommandTable quest_commandscript::GetCommands () const inline override virtual
Implements CommandScript.
    {
        static ChatCommandTable questCommandTable =
        {
            { "add",      HandleQuestAdd,      SEC_GAMEMASTER, Console::Yes },
            { "complete", HandleQuestComplete, SEC_GAMEMASTER, Console::Yes },
            { "remove",   HandleQuestRemove,   SEC_GAMEMASTER, Console::Yes },
            { "reward",   HandleQuestReward,   SEC_GAMEMASTER, Console::Yes },
            { "status",   HandleQuestStatus,   SEC_GAMEMASTER, Console::Yes },
        };
        static ChatCommandTable commandTable =
        {
            { "quest", questCommandTable },
        };
        return commandTable;
    }
References HandleQuestAdd(), HandleQuestComplete(), HandleQuestRemove(), HandleQuestReward(), HandleQuestStatus(), and SEC_GAMEMASTER.
HandleQuestAdd()
static bool quest_commandscript::HandleQuestAdd (ChatHandler * handler, Quest const * quest, Optional< PlayerIdentifier > playerTarget) inline static
    {
        if (!playerTarget)
        {
            playerTarget = PlayerIdentifier::FromTargetOrSelf(handler);
        }
        if (!playerTarget)
        {
            handler->SendErrorMessage(LANG_PLAYER_NOT_FOUND);
            return false;
        }
        uint32 entry = quest->GetQuestId();
        // check item starting quest (it can work incorrectly if added without item in inventory)
        ItemTemplateContainer const* itc = sObjectMgr->GetItemTemplateStore();
        ItemTemplateContainer::const_iterator result = find_if(itc->begin(), itc->end(), Finder<uint32, ItemTemplate>(entry, &ItemTemplate::StartQuest));
        if (result != itc->end())
        {
            handler->SendErrorMessage(LANG_COMMAND_QUEST_STARTFROMITEM, entry, result->second.ItemId);
            return false;
        }
        if (Player* player = playerTarget->GetConnectedPlayer())
        {
            if (player->IsActiveQuest(entry))
            {
                handler->SendErrorMessage(LANG_COMMAND_QUEST_ACTIVE, quest->GetTitle().c_str(), entry);
                return false;
            }
            // ok, normal (creature/GO starting) quest
            if (player->CanAddQuest(quest, true))
            {
                player->AddQuestAndCheckCompletion(quest, nullptr);
            }
        }
        else
        {
            ObjectGuid::LowType guid = playerTarget->GetGUID().GetCounter();
            QueryResult result = CharacterDatabase.Query("SELECT 1 FROM character_queststatus WHERE guid = {} AND quest = {}", guid, entry);
            if (result)
            {
                handler->SendErrorMessage(LANG_COMMAND_QUEST_ACTIVE, quest->GetTitle().c_str(), entry);
                return false;
            }
            uint8 index = 0;
            CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_REP_CHAR_QUESTSTATUS);
            stmt->SetData(index++, guid);
            stmt->SetData(index++, entry);
            stmt->SetData(index++, 1);
            stmt->SetData(index++, false);
            stmt->SetData(index++, 0);
            for (uint8 i = 0; i < QUEST_OBJECTIVES_COUNT; i++)
            {
                stmt->SetData(index++, 0);
            }
            for (uint8 i = 0; i < QUEST_ITEM_OBJECTIVES_COUNT; i++)
            {
                stmt->SetData(index++, 0);
            }
            stmt->SetData(index, 0);
            CharacterDatabase.Execute(stmt);
        }
        handler->PSendSysMessage(LANG_COMMAND_QUEST_ADD, quest->GetTitle(), entry);
        handler->SetSentErrorMessage(false);
        return true;
    }
References CHAR_REP_CHAR_QUESTSTATUS, CharacterDatabase, Acore::ChatCommands::PlayerIdentifier::FromTargetOrSelf(), Quest::GetQuestId(), Quest::GetTitle(), LANG_COMMAND_QUEST_ACTIVE, LANG_COMMAND_QUEST_ADD, LANG_COMMAND_QUEST_STARTFROMITEM, LANG_PLAYER_NOT_FOUND, ChatHandler::PSendSysMessage(), QUEST_ITEM_OBJECTIVES_COUNT, QUEST_OBJECTIVES_COUNT, ChatHandler::SendErrorMessage(), PreparedStatementBase::SetData(), ChatHandler::SetSentErrorMessage(), sObjectMgr, and ItemTemplate::StartQuest.
Referenced by GetCommands().
HandleQuestComplete()
static bool quest_commandscript::HandleQuestComplete (ChatHandler * handler, Quest const * quest, Optional< PlayerIdentifier > playerTarget) inline static
    {
        if (!playerTarget)
        {
            playerTarget = PlayerIdentifier::FromTargetOrSelf(handler);
        }
        if (!playerTarget)
        {
            handler->SendErrorMessage(LANG_PLAYER_NOT_FOUND);
            return false;
        }
        uint32 entry = quest->GetQuestId();
        if (Player* player = playerTarget->GetConnectedPlayer())
        {
            // If player doesn't have the quest
            if (player->GetQuestStatus(entry) == QUEST_STATUS_NONE)
            {
                handler->SendErrorMessage(LANG_COMMAND_QUEST_NOTFOUND, entry);
                return false;
            }
            // Add quest items for quests that require items
            for (uint8 x = 0; x < QUEST_ITEM_OBJECTIVES_COUNT; ++x)
            {
                uint32 id    = quest->RequiredItemId[x];
                uint32 count = quest->RequiredItemCount[x];
                if (!id || !count)
                {
                    continue;
                }
                uint32 curItemCount = player->GetItemCount(id, true);
                ItemPosCountVec dest;
                uint8           msg = player->CanStoreNewItem(NULL_BAG, NULL_SLOT, dest, id, count - curItemCount);
                if (msg == EQUIP_ERR_OK)
                {
                    Item* item = player->StoreNewItem(dest, id, true);
                    player->SendNewItem(item, count - curItemCount, true, false);
                }
            }
            // All creature/GO slain/casted (not required, but otherwise it will display "Creature slain 0/10")
            for (uint8 i = 0; i < QUEST_OBJECTIVES_COUNT; ++i)
            {
                int32  creature      = quest->RequiredNpcOrGo[i];
                uint32 creatureCount = quest->RequiredNpcOrGoCount[i];
                if (creature > 0)
                {
                    if (CreatureTemplate const* creatureInfo = sObjectMgr->GetCreatureTemplate(creature))
                    {
                        for (uint16 z = 0; z < creatureCount; ++z)
{
                            player->KilledMonster(creatureInfo, ObjectGuid::Empty);
                        }
                    }
                }
                else if (creature < 0)
                {
                    for (uint16 z = 0; z < creatureCount; ++z)
                    {
                        player->KillCreditGO(creature);
                    }
                }
            }
            // player kills
            if (quest->HasSpecialFlag(QUEST_SPECIAL_FLAGS_PLAYER_KILL))
            {
                if (uint32 reqPlayers = quest->GetPlayersSlain())
                {
                    player->KilledPlayerCreditForQuest(reqPlayers, quest);
                }
            }
            // If the quest requires reputation to complete
            if (uint32 repFaction = quest->GetRepObjectiveFaction())
            {
                uint32 repValue = quest->GetRepObjectiveValue();
                uint32 curRep   = player->GetReputationMgr().GetReputation(repFaction);
                if (curRep < repValue)
                {
                    if (FactionEntry const* factionEntry = sFactionStore.LookupEntry(repFaction))
                    {
                        player->GetReputationMgr().SetReputation(factionEntry, static_cast<float>(repValue));
                    }
                }
            }
            // If the quest requires a SECOND reputation to complete
            if (uint32 repFaction = quest->GetRepObjectiveFaction2())
            {
                uint32 repValue2 = quest->GetRepObjectiveValue2();
                uint32 curRep    = player->GetReputationMgr().GetReputation(repFaction);
                if (curRep < repValue2)
                {
                    if (FactionEntry const* factionEntry = sFactionStore.LookupEntry(repFaction))
                    {
                        player->GetReputationMgr().SetReputation(factionEntry, static_cast<float>(repValue2));
                    }
                }
            }
            // If the quest requires money
            int32 ReqOrRewMoney = quest->GetRewOrReqMoney(player->GetLevel());
            if (ReqOrRewMoney < 0)
            {
                player->ModifyMoney(-ReqOrRewMoney);
            }
            player->CompleteQuest(entry);
        }
        else
        {
            ObjectGuid::LowType guid = playerTarget->GetGUID().GetCounter();
            QueryResult result = CharacterDatabase.Query("SELECT 1 FROM character_queststatus WHERE guid = {} AND quest = {}", guid, entry);
            if (!result)
            {
                handler->SendErrorMessage(LANG_COMMAND_QUEST_NOT_FOUND_IN_LOG, quest->GetTitle(), entry);
                return false;
            }
            CharacterDatabaseTransaction trans = CharacterDatabase.BeginTransaction();
            typedef std::pair<uint32, uint32> items;
            std::vector<items> questItems;
            for (uint8 x = 0; x < QUEST_ITEM_OBJECTIVES_COUNT; ++x)
            {
                uint32 id    = quest->RequiredItemId[x];
                uint32 count = quest->RequiredItemCount[x];
                if (!id || !count)
                {
                    continue;
                }
                questItems.emplace_back(id, count);
            }
            if (!questItems.empty())
            {
                MailSender sender(MAIL_NORMAL, guid, MAIL_STATIONERY_GM);
                // fill mail
                MailDraft draft(quest->GetTitle(), std::string());
                for (auto const& itr : questItems)
                {
                    if (Item* item = Item::CreateItem(itr.first, itr.second))
                    {
                        item->SaveToDB(trans);
                        draft.AddItem(item);
                    }
                }
                draft.SendMailTo(trans, MailReceiver(nullptr, guid), sender);
            }
            uint8 index = 0;
            CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_REP_CHAR_QUESTSTATUS);
            stmt->SetData(index++, guid);
            stmt->SetData(index++, entry);
            stmt->SetData(index++, 1);
            stmt->SetData(index++, quest->HasFlag(QUEST_FLAGS_EXPLORATION));
            stmt->SetData(index++, 0);
            for (uint8 i = 0; i < QUEST_OBJECTIVES_COUNT; i++)
            {
                stmt->SetData(index++, quest->RequiredNpcOrGoCount[i]);
            }
            for (uint8 i = 0; i < QUEST_ITEM_OBJECTIVES_COUNT; i++)
            {
                // Will be updated once they loot the items from the mailbox.
                stmt->SetData(index++, 0);
            }
            stmt->SetData(index, 0);
            trans->Append(stmt);
            // If the quest requires reputation to complete, set the player rep to the required amount.
            if (uint32 repFaction = quest->GetRepObjectiveFaction())
            {
                uint32 repValue = quest->GetRepObjectiveValue();
                stmt = CharacterDatabase.GetPreparedStatement(CHAR_SEL_CHAR_REP_BY_FACTION);
                stmt->SetData(0, repFaction);
                stmt->SetData(1, guid);
                PreparedQueryResult result = CharacterDatabase.Query(stmt);
                if (result)
                {
                    Field* fields = result->Fetch();
                    uint32 curRep = fields[0].Get<uint32>();
                    if (curRep < repValue)
                    {
                        if (sFactionStore.LookupEntry(repFaction))
{
                            stmt = CharacterDatabase.GetPreparedStatement(CHAR_UPD_CHAR_REP_FACTION_CHANGE);
                            stmt->SetData(0, repFaction);
                            stmt->SetData(1, repValue);
                            stmt->SetData(2, repFaction);
                            stmt->SetData(3, guid);
                            trans->Append(stmt);
                        }
                    }
                }
            }
            // If the quest requires reputation to complete, set the player rep to the required amount.
            if (uint32 repFaction = quest->GetRepObjectiveFaction2())
            {
                uint32 repValue = quest->GetRepObjectiveValue();
                stmt = CharacterDatabase.GetPreparedStatement(CHAR_SEL_CHAR_REP_BY_FACTION);
                stmt->SetData(0, repFaction);
                stmt->SetData(1, guid);
                PreparedQueryResult result = CharacterDatabase.Query(stmt);
                if (result)
                {
                    Field* fields = result->Fetch();
                    uint32 curRep = fields[0].Get<uint32>();
                    if (curRep < repValue)
                    {
                        if (sFactionStore.LookupEntry(repFaction))
{
                            stmt = CharacterDatabase.GetPreparedStatement(CHAR_UPD_CHAR_REP_FACTION_CHANGE);
                            stmt->SetData(0, repFaction);
                            stmt->SetData(1, repValue);
                            stmt->SetData(2, repFaction);
                            stmt->SetData(3, guid);
                            trans->Append(stmt);
                        }
                    }
                }
            }
            CharacterDatabase.CommitTransaction(trans);
        }
        // check if Quest Tracker is enabled
        if (sWorld->getBoolConfig(CONFIG_QUEST_ENABLE_QUEST_TRACKER))
        {
            // prepare Quest Tracker datas
            auto stmt = CharacterDatabase.GetPreparedStatement(CHAR_UPD_QUEST_TRACK_GM_COMPLETE);
            stmt->SetData(0, entry);
            stmt->SetData(1, playerTarget->GetGUID().GetCounter());
            // add to Quest Tracker
            CharacterDatabase.Execute(stmt);
        }
        handler->PSendSysMessage(LANG_COMMAND_QUEST_COMPLETE, quest->GetTitle(), entry);
        handler->SetSentErrorMessage(false);
        return true;
    }
References MailDraft::AddItem(), CHAR_REP_CHAR_QUESTSTATUS, CHAR_SEL_CHAR_REP_BY_FACTION, CHAR_UPD_CHAR_REP_FACTION_CHANGE, CHAR_UPD_QUEST_TRACK_GM_COMPLETE, CharacterDatabase, CONFIG_QUEST_ENABLE_QUEST_TRACKER, Item::CreateItem(), ObjectGuid::Empty, EQUIP_ERR_OK, Acore::ChatCommands::PlayerIdentifier::FromTargetOrSelf(), Field::Get(), Quest::GetPlayersSlain(), Quest::GetQuestId(), Quest::GetRepObjectiveFaction(), Quest::GetRepObjectiveFaction2(), Quest::GetRepObjectiveValue(), Quest::GetRepObjectiveValue2(), Quest::GetRewOrReqMoney(), Quest::GetTitle(), Quest::HasFlag(), Quest::HasSpecialFlag(), LANG_COMMAND_QUEST_COMPLETE, LANG_COMMAND_QUEST_NOT_FOUND_IN_LOG, LANG_COMMAND_QUEST_NOTFOUND, LANG_PLAYER_NOT_FOUND, MAIL_NORMAL, MAIL_STATIONERY_GM, NULL_BAG, NULL_SLOT, ChatHandler::PSendSysMessage(), QUEST_FLAGS_EXPLORATION, QUEST_ITEM_OBJECTIVES_COUNT, QUEST_OBJECTIVES_COUNT, QUEST_SPECIAL_FLAGS_PLAYER_KILL, QUEST_STATUS_NONE, Quest::RequiredItemCount, Quest::RequiredItemId, Quest::RequiredNpcOrGo, Quest::RequiredNpcOrGoCount, ChatHandler::SendErrorMessage(), MailDraft::SendMailTo(), PreparedStatementBase::SetData(), ChatHandler::SetSentErrorMessage(), sFactionStore, sObjectMgr, and sWorld.
Referenced by GetCommands().
HandleQuestRemove()
static bool quest_commandscript::HandleQuestRemove (ChatHandler * handler, Quest const * quest, Optional< PlayerIdentifier > playerTarget) inline static
    {
        if (!playerTarget)
        {
            playerTarget = PlayerIdentifier::FromTargetOrSelf(handler);
        }
        if (!playerTarget)
        {
            handler->SendErrorMessage(LANG_PLAYER_NOT_FOUND);
            return false;
        }
        uint32 entry = quest->GetQuestId();
        if (!quest)
        {
            handler->SendErrorMessage(LANG_COMMAND_QUEST_NOTFOUND, entry);
            return false;
        }
        if (Player* player = playerTarget->GetConnectedPlayer())
        {
            // remove all quest entries for 'entry' from quest log
            for (uint8 slot = 0; slot < MAX_QUEST_LOG_SIZE; ++slot)
            {
                uint32 logQuest = player->GetQuestSlotQuestId(slot);
                if (logQuest == entry)
                {
                    player->SetQuestSlot(slot, 0);
                    // we ignore unequippable quest items in this case, its' still be equipped
                    player->TakeQuestSourceItem(logQuest, false);
                    if (quest->HasFlag(QUEST_FLAGS_FLAGS_PVP))
                    {
                        player->pvpInfo.IsHostile = player->pvpInfo.IsInHostileArea || player->HasPvPForcingQuest();
                        player->UpdatePvPState();
                    }
                }
            }
            player->RemoveRewardedQuest(entry);
            player->RemoveActiveQuest(entry, false);
        }
        else
        {
            ObjectGuid::LowType guid = playerTarget->GetGUID().GetCounter();
            CharacterDatabaseTransaction trans = CharacterDatabase.BeginTransaction();
            CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_DEL_CHAR_QUESTSTATUS_REWARDED_BY_QUEST);
            stmt->SetData(0, guid);
            stmt->SetData(1, entry);
            trans->Append(stmt);
            stmt = CharacterDatabase.GetPreparedStatement(CHAR_DEL_CHAR_QUESTSTATUS_BY_QUEST);
            stmt->SetData(0, guid);
            stmt->SetData(1, entry);
            trans->Append(stmt);
            for (uint32 const& requiredItem : quest->RequiredItemId)
            {
                stmt = CharacterDatabase.GetPreparedStatement(CHAR_SEL_CHAR_INVENTORY_ITEM_BY_ENTRY_AND_OWNER);
                stmt->SetData(0, requiredItem);
                stmt->SetData(1, guid);
                PreparedQueryResult result = CharacterDatabase.Query(stmt);
                if (result)
                {
                    Field* fields = result->Fetch();
                    stmt = CharacterDatabase.GetPreparedStatement(CHAR_DEL_CHAR_INVENTORY_BY_ITEM);
                    stmt->SetData(0, fields[0].Get<uint32>());
                    trans->Append(stmt);
                    stmt = CharacterDatabase.GetPreparedStatement(CHAR_DEL_ITEM_INSTANCE);
                    stmt->SetData(0, fields[0].Get<uint32>());
                    trans->Append(stmt);
                }
            }
            CharacterDatabase.CommitTransaction(trans);
        }
        handler->PSendSysMessage(LANG_COMMAND_QUEST_REMOVED, quest->GetTitle(), entry);
        handler->SetSentErrorMessage(false);
        return true;
    }
References CHAR_DEL_CHAR_INVENTORY_BY_ITEM, CHAR_DEL_CHAR_QUESTSTATUS_BY_QUEST, CHAR_DEL_CHAR_QUESTSTATUS_REWARDED_BY_QUEST, CHAR_DEL_ITEM_INSTANCE, CHAR_SEL_CHAR_INVENTORY_ITEM_BY_ENTRY_AND_OWNER, CharacterDatabase, Acore::ChatCommands::PlayerIdentifier::FromTargetOrSelf(), Quest::GetQuestId(), Quest::GetTitle(), Quest::HasFlag(), LANG_COMMAND_QUEST_NOTFOUND, LANG_COMMAND_QUEST_REMOVED, LANG_PLAYER_NOT_FOUND, MAX_QUEST_LOG_SIZE, ChatHandler::PSendSysMessage(), QUEST_FLAGS_FLAGS_PVP, Quest::RequiredItemId, ChatHandler::SendErrorMessage(), PreparedStatementBase::SetData(), and ChatHandler::SetSentErrorMessage().
Referenced by GetCommands().
HandleQuestReward()
static bool quest_commandscript::HandleQuestReward (ChatHandler * handler, Quest const * quest, Optional< PlayerIdentifier > playerTarget) inline static
    {
        if (!playerTarget)
        {
            playerTarget = PlayerIdentifier::FromTargetOrSelf(handler);
        }
        if (!playerTarget)
        {
            handler->SendErrorMessage(LANG_PLAYER_NOT_FOUND);
            return false;
        }
        uint32 entry = quest->GetQuestId();
        if (Player* player = playerTarget->GetConnectedPlayer())
        {
            // If player doesn't have the quest
            if (player->GetQuestStatus(entry) != QUEST_STATUS_COMPLETE)
            {
                handler->SendErrorMessage(LANG_COMMAND_QUEST_NOTFOUND, entry);
                return false;
            }
            player->RewardQuest(quest, 0, player);
        }
        else
        {
            // Achievement criteria updates correctly the next time a quest is rewarded.
            // Titles are already awarded correctly the next time they login (only one quest awards title - 11549).
            // Rewarded talent points (Death Knights) and spells (e.g Druid forms) are also granted on login.
            // No reputation gains - too troublesome to calculate them when the player is offline.
            ObjectGuid::LowType guid = playerTarget->GetGUID().GetCounter();
            uint8 charLevel = sCharacterCache->GetCharacterLevelByGuid(ObjectGuid(HighGuid::Player, guid));
            CharacterDatabaseTransaction trans = CharacterDatabase.BeginTransaction();
            CharacterDatabasePreparedStatement* stmt;
            QueryResult result = CharacterDatabase.Query("SELECT 1 FROM character_queststatus WHERE guid = {} AND quest = {} AND status = 1", guid, entry);
            if (!result)
            {
                handler->SendErrorMessage(LANG_COMMAND_QUEST_NOT_COMPLETE);
                return false;
            }
            for (uint32 const& requiredItem : quest->RequiredItemId)
            {
                stmt = CharacterDatabase.GetPreparedStatement(CHAR_SEL_CHAR_INVENTORY_ITEM_BY_ENTRY_AND_OWNER);
                stmt->SetData(0, requiredItem);
                stmt->SetData(1, guid);
                PreparedQueryResult result = CharacterDatabase.Query(stmt);
                if (result)
                {
                    Field* fields = result->Fetch();
                    stmt = CharacterDatabase.GetPreparedStatement(CHAR_DEL_CHAR_INVENTORY_BY_ITEM);
                    stmt->SetData(0, fields[0].Get<uint32>());
                    trans->Append(stmt);
                    stmt = CharacterDatabase.GetPreparedStatement(CHAR_DEL_ITEM_INSTANCE);
                    stmt->SetData(0, fields[0].Get<uint32>());
                    trans->Append(stmt);
                }
            }
            for (uint32 const& sourceItem : quest->ItemDrop)
            {
                stmt = CharacterDatabase.GetPreparedStatement(CHAR_SEL_CHAR_INVENTORY_ITEM_BY_ENTRY_AND_OWNER);
                stmt->SetData(0, sourceItem);
                stmt->SetData(1, guid);
                PreparedQueryResult result = CharacterDatabase.Query(stmt);
                if (result)
                {
                    Field* fields = result->Fetch();
                    stmt = CharacterDatabase.GetPreparedStatement(CHAR_DEL_CHAR_INVENTORY_BY_ITEM);
                    stmt->SetData(0, fields[0].Get<uint32>());
                    trans->Append(stmt);
                    stmt = CharacterDatabase.GetPreparedStatement(CHAR_DEL_ITEM_INSTANCE);
                    stmt->SetData(0, fields[0].Get<uint32>());
                    trans->Append(stmt);
                }
            }
            typedef std::pair<uint32, uint32> items;
            std::vector<items> questRewardItems;
            if (quest->GetRewChoiceItemsCount())
            {
                for (uint32 const& itemId : quest->RewardChoiceItemId)
                {
                    uint8 index = 0;
                    questRewardItems.emplace_back(itemId, quest->RewardChoiceItemCount[index++]);
                }
            }
            if (quest->GetRewItemsCount())
            {
                for (uint32 const& itemId : quest->RewardItemId)
                {
                    uint8 index = 0;
                    questRewardItems.emplace_back(itemId, quest->RewardItemIdCount[index++]);
                }
            }
            if (!questRewardItems.empty())
            {
                MailSender sender(MAIL_NORMAL, guid, MAIL_STATIONERY_GM);
                // fill mail
                MailDraft draft(quest->GetTitle(), "This quest has been manually rewarded to you. This mail contains your quest rewards.");
                for (auto const& itr : questRewardItems)
                {
                    if (!itr.first || !itr.second)
                    {
                        continue;
                    }
                    // Skip invalid items.
                    if (!sObjectMgr->GetItemTemplate(itr.first))
                    {
                        continue;
                    }
                    if (Item* item = Item::CreateItem(itr.first, itr.second))
                    {
                        item->SaveToDB(trans);
                        draft.AddItem(item);
                    }
                }
                draft.SendMailTo(trans, MailReceiver(nullptr, guid), sender);
            }
            // Send quest giver mail, if any.
            if (uint32 mail_template_id = quest->GetRewMailTemplateId())
            {
                if (quest->GetRewMailSenderEntry() != 0)
                {
                    MailDraft(mail_template_id).SendMailTo(trans, MailReceiver(nullptr, guid), quest->GetRewMailSenderEntry(), MAIL_CHECK_MASK_HAS_BODY, quest->GetRewMailDelaySecs());
                }
            }
            if (quest->IsDaily() || quest->IsDFQuest())
            {
                stmt = CharacterDatabase.GetPreparedStatement(CHAR_INS_CHARACTER_DAILYQUESTSTATUS);
                stmt->SetData(0, guid);
                stmt->SetData(1, entry);
                stmt->SetData(2, GameTime::GetGameTime().count());
                trans->Append(stmt);
            }
            else if (quest->IsWeekly())
            {
                stmt = CharacterDatabase.GetPreparedStatement(CHAR_INS_CHARACTER_WEEKLYQUESTSTATUS);
                stmt->SetData(0, guid);
                stmt->SetData(1, entry);
                trans->Append(stmt);
            }
            else if (quest->IsMonthly())
            {
                stmt = CharacterDatabase.GetPreparedStatement(CHAR_INS_CHARACTER_MONTHLYQUESTSTATUS);
                stmt->SetData(0, guid);
                stmt->SetData(1, entry);
                trans->Append(stmt);
            }
            else if (quest->IsSeasonal())
            {
                // We can't know which event is the quest linked to, so we can't do anything about this.
                /* stmt = CharacterDatabase.GetPreparedStatement(CHAR_INS_CHARACTER_SEASONALQUESTSTATUS);
                stmt->SetData(0, guid);
                stmt->SetData(1, entry);
                stmt->SetData(2, event_id);
                trans->Append(stmt);*/
            }
            if (uint32 honor = quest->CalculateHonorGain(charLevel))
            {
                stmt = CharacterDatabase.GetPreparedStatement(CHAR_UDP_CHAR_HONOR_POINTS_ACCUMULATIVE);
                stmt->SetData(0, honor);
                stmt->SetData(1, guid);
                trans->Append(stmt);
            }
            if (quest->GetRewArenaPoints())
            {
                stmt = CharacterDatabase.GetPreparedStatement(CHAR_UDP_CHAR_ARENA_POINTS_ACCUMULATIVE);
                stmt->SetData(0, quest->GetRewArenaPoints());
                stmt->SetData(1, guid);
                trans->Append(stmt);
            }
            int32 rewMoney = 0;
            if (charLevel >= sWorld->getIntConfig(CONFIG_MAX_PLAYER_LEVEL))
            {
                rewMoney = quest->GetRewMoneyMaxLevel();
            }
            else
            {
                // Some experience might get lost on level up.
                uint32 xp = uint32(quest->XPValue(charLevel) * sWorld->getRate(RATE_XP_QUEST));
                stmt = CharacterDatabase.GetPreparedStatement(CHAR_UPD_XP_ACCUMULATIVE);
                stmt->SetData(0, xp);
                stmt->SetData(1, guid);
                trans->Append(stmt);
            }
            if (int32 rewOrReqMoney = quest->GetRewOrReqMoney(charLevel))
            {
                rewMoney += rewOrReqMoney;
            }
            // Only reward money, don't subtract, let's not cause an overflow...
            if (rewMoney > 0)
            {
                CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_UDP_CHAR_MONEY_ACCUMULATIVE);
                stmt->SetData(0, rewMoney);
                stmt->SetData(1, guid);
                trans->Append(stmt);
            }
            stmt = CharacterDatabase.GetPreparedStatement(CHAR_INS_CHAR_QUESTSTATUS_REWARDED);
            stmt->SetData(0, guid);
            stmt->SetData(1, entry);
            trans->Append(stmt);
            stmt = CharacterDatabase.GetPreparedStatement(CHAR_DEL_CHAR_QUESTSTATUS_BY_QUEST);
            stmt->SetData(0, guid);
            stmt->SetData(1, entry);
            trans->Append(stmt);
            CharacterDatabase.CommitTransaction(trans);
        }
        handler->PSendSysMessage(LANG_COMMAND_QUEST_REWARDED, quest->GetTitle(), entry);
        handler->SetSentErrorMessage(false);
        return true;
    }
References MailDraft::AddItem(), Quest::CalculateHonorGain(), CHAR_DEL_CHAR_INVENTORY_BY_ITEM, CHAR_DEL_CHAR_QUESTSTATUS_BY_QUEST, CHAR_DEL_ITEM_INSTANCE, CHAR_INS_CHAR_QUESTSTATUS_REWARDED, CHAR_INS_CHARACTER_DAILYQUESTSTATUS, CHAR_INS_CHARACTER_MONTHLYQUESTSTATUS, CHAR_INS_CHARACTER_WEEKLYQUESTSTATUS, CHAR_SEL_CHAR_INVENTORY_ITEM_BY_ENTRY_AND_OWNER, CHAR_UDP_CHAR_ARENA_POINTS_ACCUMULATIVE, CHAR_UDP_CHAR_HONOR_POINTS_ACCUMULATIVE, CHAR_UDP_CHAR_MONEY_ACCUMULATIVE, CHAR_UPD_XP_ACCUMULATIVE, CharacterDatabase, CONFIG_MAX_PLAYER_LEVEL, Item::CreateItem(), Acore::ChatCommands::PlayerIdentifier::FromTargetOrSelf(), GameTime::GetGameTime(), Quest::GetQuestId(), Quest::GetRewArenaPoints(), Quest::GetRewChoiceItemsCount(), Quest::GetRewItemsCount(), Quest::GetRewMailDelaySecs(), Quest::GetRewMailSenderEntry(), Quest::GetRewMailTemplateId(), Quest::GetRewMoneyMaxLevel(), Quest::GetRewOrReqMoney(), Quest::GetTitle(), Quest::IsDaily(), Quest::IsDFQuest(), Quest::IsMonthly(), Quest::IsSeasonal(), Quest::IsWeekly(), Quest::ItemDrop, LANG_COMMAND_QUEST_NOT_COMPLETE, LANG_COMMAND_QUEST_NOTFOUND, LANG_COMMAND_QUEST_REWARDED, LANG_PLAYER_NOT_FOUND, MAIL_CHECK_MASK_HAS_BODY, MAIL_NORMAL, MAIL_STATIONERY_GM, Player, ChatHandler::PSendSysMessage(), QUEST_STATUS_COMPLETE, RATE_XP_QUEST, Quest::RequiredItemId, Quest::RewardChoiceItemCount, Quest::RewardChoiceItemId, Quest::RewardItemId, Quest::RewardItemIdCount, sCharacterCache, ChatHandler::SendErrorMessage(), MailDraft::SendMailTo(), PreparedStatementBase::SetData(), ChatHandler::SetSentErrorMessage(), sObjectMgr, sWorld, and Quest::XPValue().
Referenced by GetCommands().
HandleQuestStatus()
static bool quest_commandscript::HandleQuestStatus (ChatHandler * handler, Quest const * quest, Optional< PlayerIdentifier > playerTarget) inline static
    {
        if (!playerTarget)
            playerTarget = PlayerIdentifier::FromTargetOrSelf(handler);
        if (!playerTarget)
        {
            handler->SendErrorMessage(LANG_PLAYER_NOT_FOUND);
            return false;
        }
        uint32 entry = quest->GetQuestId();
        std::string status;
        if (Player* player = playerTarget->GetConnectedPlayer())
        {
            QuestStatus qs = player->GetQuestStatus(entry);
            switch (qs)
            {
                case QUEST_STATUS_NONE:
                    status = "Not Taken";
                    break;
                case QUEST_STATUS_COMPLETE:
                    status = "Complete";
                    break;
                case QUEST_STATUS_INCOMPLETE:
                    status = "Incomplete";
                    break;
                case QUEST_STATUS_FAILED:
                    status = "Failed";
                    break;
                case QUEST_STATUS_REWARDED:
                    status = "Rewarded";
                    break;
                default:
                    status = "Unknown";
                    break;
            }
            handler->PSendSysMessage(LANG_CMD_QUEST_STATUS, quest->GetTitle(), entry, status);
            if (!player->CanTakeQuest(quest, false))
            {
                handler->PSendSysMessage(LANG_CMD_QUEST_UNAVAILABLE, entry);
                if (sDisableMgr->IsDisabledFor(DISABLE_TYPE_QUEST, entry, player))
                    handler->SendSysMessage(LANG_CMD_QUEST_STATUS_DISABLED);
                if (!player->SatisfyQuestStatus(quest, false))
                    handler->SendSysMessage(LANG_CMD_QUEST_STATUS_ALREADY_DONE);
                if (!player->SatisfyQuestClass(quest, false))
                    handler->SendSysMessage(LANG_CMD_QUEST_STATUS_CLASS);
                if (!player->SatisfyQuestRace(quest, false))
                    handler->SendSysMessage(LANG_CMD_QUEST_STATUS_RACE);
                if (player->GetLevel() < quest->GetMinLevel())
                    handler->PSendSysMessage(LANG_CMD_QUEST_STATUS_LOW_LEVEL, quest->GetMinLevel());
                if (quest->GetMaxLevel() > 0 && player->GetLevel() > quest->GetMaxLevel())
                    handler->PSendSysMessage(LANG_CMD_QUEST_STATUS_HIGH_LEVEL, quest->GetMaxLevel());
                if (!player->SatisfyQuestSkill(quest, false))
                    handler->SendSysMessage(LANG_CMD_QUEST_STATUS_SKILL);
                if (!player->SatisfyQuestReputation(quest, false))
                    handler->SendSysMessage(LANG_CMD_QUEST_STATUS_REPUTATION);
                if (!player->SatisfyQuestPreviousQuest(quest, false))
                    handler->SendSysMessage(LANG_CMD_QUEST_STATUS_PREV_QUEST);
                if (!player->SatisfyQuestTimed(quest, false))
                    handler->SendSysMessage(LANG_CMD_QUEST_STATUS_TIMED);
                if (!player->SatisfyQuestExclusiveGroup(quest, false))
                    handler->SendSysMessage(LANG_CMD_QUEST_STATUS_EXCLUSIVE);
                if (!player->SatisfyQuestNextChain(quest, false))
                    handler->SendSysMessage(LANG_CMD_QUEST_STATUS_NEXT_CHAIN);
                if (!player->SatisfyQuestPrevChain(quest, false))
                    handler->SendSysMessage(LANG_CMD_QUEST_STATUS_PREV_CHAIN);
                if (!player->SatisfyQuestBreadcrumb(quest, false))
                    handler->SendSysMessage(LANG_CMD_QUEST_STATUS_BREADCRUMB);
                if (!player->SatisfyQuestDay(quest, false))
                    handler->SendSysMessage(LANG_CMD_QUEST_STATUS_DAY);
                if (!player->SatisfyQuestWeek(quest, false))
                    handler->SendSysMessage(LANG_CMD_QUEST_STATUS_WEEK);
                if (!player->SatisfyQuestMonth(quest, false))
                    handler->SendSysMessage(LANG_CMD_QUEST_STATUS_MONTH);
                if (!player->SatisfyQuestSeasonal(quest, false))
                    handler->SendSysMessage(LANG_CMD_QUEST_STATUS_SEASONAL);
                if (!player->SatisfyQuestConditions(quest, false))
                {
                    handler->SendSysMessage(LANG_CMD_QUEST_STATUS_CONDITION);
                    ConditionList conditions = sConditionMgr->GetConditionsForNotGroupedEntry(CONDITION_SOURCE_TYPE_QUEST_AVAILABLE, entry);
                    ConditionSourceInfo srcInfo = ConditionSourceInfo(player);
                    for (Condition* cond : conditions)
                    {
                        if (!cond->Meets(srcInfo))
                            handler->PSendSysMessage(LANG_CMD_QUEST_STATUS_COND_DETAIL, uint32(cond->ConditionType), cond->ConditionValue1, cond->ConditionValue2, cond->ConditionValue3);
                    }
                }
                if (!player->SatisfyQuestLog(false))
                    handler->SendSysMessage(LANG_CMD_QUEST_STATUS_LOG_FULL);
            }
        }
        else
        {
            handler->SendErrorMessage(LANG_PLAYER_NOT_FOUND);
            return false;
        }
        return true;
    }
References CONDITION_SOURCE_TYPE_QUEST_AVAILABLE, DISABLE_TYPE_QUEST, Acore::ChatCommands::PlayerIdentifier::FromTargetOrSelf(), Quest::GetMaxLevel(), Quest::GetMinLevel(), Quest::GetQuestId(), Quest::GetTitle(), LANG_CMD_QUEST_STATUS, LANG_CMD_QUEST_STATUS_ALREADY_DONE, LANG_CMD_QUEST_STATUS_BREADCRUMB, LANG_CMD_QUEST_STATUS_CLASS, LANG_CMD_QUEST_STATUS_COND_DETAIL, LANG_CMD_QUEST_STATUS_CONDITION, LANG_CMD_QUEST_STATUS_DAY, LANG_CMD_QUEST_STATUS_DISABLED, LANG_CMD_QUEST_STATUS_EXCLUSIVE, LANG_CMD_QUEST_STATUS_HIGH_LEVEL, LANG_CMD_QUEST_STATUS_LOG_FULL, LANG_CMD_QUEST_STATUS_LOW_LEVEL, LANG_CMD_QUEST_STATUS_MONTH, LANG_CMD_QUEST_STATUS_NEXT_CHAIN, LANG_CMD_QUEST_STATUS_PREV_CHAIN, LANG_CMD_QUEST_STATUS_PREV_QUEST, LANG_CMD_QUEST_STATUS_RACE, LANG_CMD_QUEST_STATUS_REPUTATION, LANG_CMD_QUEST_STATUS_SEASONAL, LANG_CMD_QUEST_STATUS_SKILL, LANG_CMD_QUEST_STATUS_TIMED, LANG_CMD_QUEST_STATUS_WEEK, LANG_CMD_QUEST_UNAVAILABLE, LANG_PLAYER_NOT_FOUND, ChatHandler::PSendSysMessage(), QUEST_STATUS_COMPLETE, QUEST_STATUS_FAILED, QUEST_STATUS_INCOMPLETE, QUEST_STATUS_NONE, QUEST_STATUS_REWARDED, sConditionMgr, sDisableMgr, ChatHandler::SendErrorMessage(), and ChatHandler::SendSysMessage().
Referenced by GetCommands().
The documentation for this class was generated from the following file:
azerothcore-wotlk/src/server/scripts/Commands/cs_quest.cpp