AzerothCore Doxygen
HttpManager Class Reference
#include "HttpManager.h"
Public Member Functions
HttpManager ()
~HttpManager ()
void StartHttpWorker ()
void StopHttpWorker ()
void PushRequest (HttpWorkItem *item)
void HandleHttpResponses ()
Private Member Functions
void ClearQueues ()
void HttpWorkerThread ()
bool ParseUrl (const std::string &url, std::string &host, std::string &path)
httplib::Result DoRequest (httplib::Client &client, HttpWorkItem *req, const std::string &path)
Private Attributes
rigtorp::SPSCQueue< HttpWorkItem * > workQueue
rigtorp::SPSCQueue< HttpResponse * > responseQueue
std::thread workerThread
bool startedWorkerThread
std::atomic_bool cancelationToken
std::condition_variable condVar
std::mutex condVarMutex
std::regex parseUrlRegex
Detailed Description
Constructor & Destructor Documentation
HttpManager()
HttpManager::HttpManager ()
    : workQueue(16),
    responseQueue(16),
    startedWorkerThread(false),
    cancelationToken(false),
    condVar(),
    condVarMutex(),
    parseUrlRegex("^(([^:/?#]+):)?(//([^/?#]*))?([^?#]*)(\\?([^#]*))?(#(.*))?")
{
    StartHttpWorker();
}
References StartHttpWorker().
~HttpManager()
HttpManager::~HttpManager ()
{
    StopHttpWorker();
}
References StopHttpWorker().
Member Function Documentation
ClearQueues()
void HttpManager::ClearQueues () private
{
    while (workQueue.front())
    {
        HttpWorkItem* item = *workQueue.front();
        if (item != nullptr)
        {
            delete item;
        }
        workQueue.pop();
    }
    while (responseQueue.front())
    {
        HttpResponse* item = *responseQueue.front();
        if (item != nullptr)
        {
            delete item;
        }
        responseQueue.pop();
    }
}
References rigtorp::SPSCQueue< T, Allocator >::front(), rigtorp::SPSCQueue< T, Allocator >::pop(), responseQueue, and workQueue.
Referenced by StartHttpWorker(), and StopHttpWorker().
DoRequest()
httplib::Result HttpManager::DoRequest (httplib::Client & client, HttpWorkItem * req, const std::string & path) private
{
    const char* path = urlPath.c_str();
    if (req->httpVerb == "GET")
    {
        return client.Get(path, req->headers);
    }
    if (req->httpVerb == "HEAD")
    {
        return client.Head(path, req->headers);
    }
    if (req->httpVerb == "POST")
    {
        return client.Post(path, req->headers, req->body, req->contentType.c_str());
    }
    if (req->httpVerb == "PUT")
    {
        return client.Put(path, req->headers, req->body, req->contentType.c_str());
    }
    if (req->httpVerb == "PATCH")
    {
        return client.Patch(path, req->headers, req->body, req->contentType.c_str());
    }
    if (req->httpVerb == "DELETE")
    {
        return client.Delete(path, req->headers);
    }
    if (req->httpVerb == "OPTIONS")
    {
        return client.Options(path, req->headers);
    }
    ELUNA_LOG_ERROR("[Eluna]: HTTP request error: invalid HTTP verb {}", req->httpVerb);
    return client.Get(path, req->headers);
}
References HttpWorkItem::body, HttpWorkItem::contentType, httplib::Client::Delete(), ELUNA_LOG_ERROR, httplib::Client::Get(), httplib::Client::Head(), HttpWorkItem::headers, HttpWorkItem::httpVerb, httplib::Client::Options(), httplib::Client::Patch(), httplib::Client::Post(), and httplib::Client::Put().
Referenced by HttpWorkerThread().
HandleHttpResponses()
void HttpManager::HandleHttpResponses ()
{
    while (!responseQueue.empty())
    {
        HttpResponse* res = *responseQueue.front();
        responseQueue.pop();
        if (res == nullptr)
        {
            continue;
        }
        LOCK_ELUNA;
        lua_State* L = Eluna::GEluna->L;
        // Get function
        lua_rawgeti(L, LUA_REGISTRYINDEX, res->funcRef);
        // Push parameters
        Eluna::Push(L, res->statusCode);
        Eluna::Push(L, res->body);
        lua_newtable(L);
        for (const auto& item : res->headers) {
            Eluna::Push(L, item.first);
            Eluna::Push(L, item.second);
            lua_settable(L, -3);
        }
        // Call function
        Eluna::GEluna->ExecuteCall(3, 0);
        luaL_unref(L, LUA_REGISTRYINDEX, res->funcRef);
        delete res;
    }
}
References HttpResponse::body, rigtorp::SPSCQueue< T, Allocator >::empty(), Eluna::ExecuteCall(), rigtorp::SPSCQueue< T, Allocator >::front(), HttpResponse::funcRef, Eluna::GEluna, HttpResponse::headers, Eluna::L, LOCK_ELUNA, lua_newtable, lua_rawgeti(), LUA_REGISTRYINDEX, lua_settable(), luaL_unref(), rigtorp::SPSCQueue< T, Allocator >::pop(), Eluna::Push(), responseQueue, and HttpResponse::statusCode.
Referenced by Eluna::OnWorldUpdate().
HttpWorkerThread()
void HttpManager::HttpWorkerThread () private
{
    while (true)
    {
        {
            std::unique_lock<std::mutex> lock(condVarMutex);
            condVar.wait(lock, [&] { return workQueue.front() != nullptr || cancelationToken.load(); });
        }
        if (cancelationToken.load())
        {
            break;
        }
        if (!workQueue.front())
        {
            continue;
        }
        HttpWorkItem* req = *workQueue.front();
        workQueue.pop();
        if (!req)
        {
            continue;
        }
        try
        {
            std::string host;
            std::string path;
            if (!ParseUrl(req->url, host, path)) {
                ELUNA_LOG_ERROR("[Eluna]: Could not parse URL {}", req->url);
                continue;
            }
            httplib::Client cli(host);
            cli.set_connection_timeout(0, 3000000); // 3 seconds
            cli.set_read_timeout(5, 0); // 5 seconds
            cli.set_write_timeout(5, 0); // 5 seconds
            httplib::Result res = DoRequest(cli, req, path);
            httplib::Error err = res.error();
            if (err != httplib::Error::Success)
            {
                ELUNA_LOG_ERROR("[Eluna]: HTTP request error: {}", httplib::to_string(err));
                continue;
            }
            if (res->status == 301)
            {
                std::string location = res->get_header_value("Location");
                std::string host;
                std::string path;
                if (!ParseUrl(location, host, path))
                {
                    ELUNA_LOG_ERROR("[Eluna]: Could not parse URL after redirect: {}", location);
                    continue;
                }
                httplib::Client cli2(host);
                cli2.set_connection_timeout(0, 3000000); // 3 seconds
                cli2.set_read_timeout(5, 0); // 5 seconds
                cli2.set_write_timeout(5, 0); // 5 seconds
                res = DoRequest(cli2, req, path);
            }
            responseQueue.push(new HttpResponse(req->funcRef, res->status, res->body, res->headers));
        }
        catch (const std::exception& ex)
        {
            ELUNA_LOG_ERROR("[Eluna]: HTTP request error: {}", ex.what());
        }
        delete req;
    }
}
References httplib::Response::body, cancelationToken, condVar, condVarMutex, DoRequest(), ELUNA_LOG_ERROR, httplib::Result::error(), rigtorp::SPSCQueue< T, Allocator >::front(), HttpWorkItem::funcRef, httplib::Response::get_header_value(), httplib::Response::headers, ParseUrl(), rigtorp::SPSCQueue< T, Allocator >::pop(), rigtorp::SPSCQueue< T, Allocator >::push(), responseQueue, httplib::Client::set_connection_timeout(), httplib::Client::set_read_timeout(), httplib::Client::set_write_timeout(), httplib::Response::status, httplib::Success, httplib::to_string(), HttpWorkItem::url, and workQueue.
Referenced by StartHttpWorker().
ParseUrl()
bool HttpManager::ParseUrl (const std::string & url, std::string & host, std::string & path) private
{
    std::smatch matches;
    if (!std::regex_search(url, matches, parseUrlRegex))
    {
        return false;
    }
    std::string scheme = matches[2];
    std::string authority = matches[4];
    std::string query = matches[7];
    host = scheme + "://" + authority;
    path = matches[5];
    if (path.empty())
    {
        path = "/";
    }
    path += (query.empty() ? "" : "?") + query;
    return true;
}
References parseUrlRegex.
Referenced by HttpWorkerThread().
PushRequest()
void HttpManager::PushRequest (HttpWorkItem * item)
{
    std::unique_lock<std::mutex> lock(condVarMutex);
    workQueue.push(item);
    condVar.notify_one();
}
References condVar, condVarMutex, rigtorp::SPSCQueue< T, Allocator >::push(), and workQueue.
Referenced by LuaGlobalFunctions::HttpRequest().
StartHttpWorker()
void HttpManager::StartHttpWorker ()
{
    ClearQueues();
    if (!startedWorkerThread)
    {
        cancelationToken.store(false);
        workerThread = std::thread(&HttpManager::HttpWorkerThread, this);
        startedWorkerThread = true;
    }
}
References cancelationToken, ClearQueues(), HttpWorkerThread(), startedWorkerThread, and workerThread.
Referenced by HttpManager().
StopHttpWorker()
void HttpManager::StopHttpWorker ()
{
    if (!startedWorkerThread)
    {
        return;
    }
    cancelationToken.store(true);
    condVar.notify_one();
    workerThread.join();
    ClearQueues();
    startedWorkerThread = false;
}
References cancelationToken, ClearQueues(), condVar, startedWorkerThread, and workerThread.
Referenced by ~HttpManager().
Member Data Documentation
cancelationToken
std::atomic_bool HttpManager::cancelationToken private
Referenced by HttpWorkerThread(), StartHttpWorker(), and StopHttpWorker().
condVar
std::condition_variable HttpManager::condVar private
Referenced by HttpWorkerThread(), PushRequest(), and StopHttpWorker().
condVarMutex
std::mutex HttpManager::condVarMutex private
Referenced by HttpWorkerThread(), and PushRequest().
parseUrlRegex
std::regex HttpManager::parseUrlRegex private
Referenced by ParseUrl().
responseQueue
rigtorp::SPSCQueue<HttpResponse*> HttpManager::responseQueue private
Referenced by ClearQueues(), HandleHttpResponses(), and HttpWorkerThread().
startedWorkerThread
bool HttpManager::startedWorkerThread private
Referenced by StartHttpWorker(), and StopHttpWorker().
workerThread
std::thread HttpManager::workerThread private
Referenced by StartHttpWorker(), and StopHttpWorker().
workQueue
rigtorp::SPSCQueue<HttpWorkItem*> HttpManager::workQueue private
Referenced by ClearQueues(), HttpWorkerThread(), and PushRequest().
The documentation for this class was generated from the following files:
mod-eluna/src/LuaEngine/HttpManager.h
mod-eluna/src/LuaEngine/HttpManager.cpp