AzerothCore Doxygen
ResetToHomeOrientation Class Reference
Public Member Functions
ResetToHomeOrientation (Creature &self)
bool Execute (uint64, uint32) override
Public Member Functions inherited from BasicEvent
BasicEvent ()=default
virtual ~BasicEvent ()=default
virtual bool IsDeletable () const
virtual void Abort (uint64)
void ScheduleAbort ()
Private Attributes
Creature & _self
Detailed Description
Constructor & Destructor Documentation
ResetToHomeOrientation()
ResetToHomeOrientation::ResetToHomeOrientation (Creature & self) inline
: _self(self) { }
Member Function Documentation
Execute()
bool ResetToHomeOrientation::Execute (uint64 , uint32) inline override virtual
Reimplemented from BasicEvent.
    {
            if (_self.IsInWorld() && _self.FindMap() && _self.IsAlive() && !_self.IsInCombat())
            {
                _self.SetFacingTo(_self.GetHomePosition().GetOrientation());
            }
        return true;
    }
References _self, WorldObject::FindMap(), Creature::GetHomePosition(), Unit::IsAlive(), Unit::IsInCombat(), Object::IsInWorld(), and Unit::SetFacingTo().
Member Data Documentation
_self
Creature& ResetToHomeOrientation::_self private
Referenced by Execute().
The documentation for this class was generated from the following file:
azerothcore-wotlk/src/server/game/Entities/Unit/Unit.cpp