AzerothCore Doxygen
northrend_script_loader.cpp File Reference
Functions
void AddSC_boss_slad_ran ()
void AddSC_boss_moorabi ()
void AddSC_boss_drakkari_colossus ()
void AddSC_boss_gal_darah ()
void AddSC_boss_eck ()
void AddSC_instance_gundrak ()
void AddSC_boss_amanitar ()
void AddSC_boss_taldaram ()
void AddSC_boss_elder_nadox ()
void AddSC_boss_jedoga_shadowseeker ()
void AddSC_boss_volazj ()
void AddSC_instance_ahnkahet ()
void AddSC_boss_argent_challenge ()
void AddSC_boss_black_knight ()
void AddSC_boss_grand_champions ()
void AddSC_instance_trial_of_the_champion ()
void AddSC_trial_of_the_champion ()
void AddSC_boss_anubarak_trial ()
void AddSC_boss_faction_champions ()
void AddSC_boss_jaraxxus ()
void AddSC_trial_of_the_crusader ()
void AddSC_boss_twin_valkyr ()
void AddSC_boss_northrend_beasts ()
void AddSC_instance_trial_of_the_crusader ()
void AddSC_boss_krik_thir ()
void AddSC_boss_hadronox ()
void AddSC_boss_anub_arak ()
void AddSC_instance_azjol_nerub ()
void AddSC_boss_anubrekhan ()
void AddSC_boss_maexxna ()
void AddSC_boss_patchwerk ()
void AddSC_boss_grobbulus ()
void AddSC_boss_razuvious ()
void AddSC_boss_kelthuzad ()
void AddSC_boss_loatheb ()
void AddSC_boss_noth ()
void AddSC_boss_gluth ()
void AddSC_boss_sapphiron ()
void AddSC_boss_four_horsemen ()
void AddSC_boss_faerlina ()
void AddSC_boss_heigan ()
void AddSC_boss_gothik ()
void AddSC_boss_thaddius ()
void AddSC_instance_naxxramas ()
void AddSC_boss_magus_telestra ()
void AddSC_boss_anomalus ()
void AddSC_boss_ormorok ()
void AddSC_boss_keristrasza ()
void AddSC_boss_commander_stoutbeard ()
void AddSC_instance_nexus ()
void AddSC_boss_drakos ()
void AddSC_boss_varos ()
void AddSC_boss_urom ()
void AddSC_boss_eregos ()
void AddSC_instance_oculus ()
void AddSC_oculus ()
void AddSC_boss_sartharion ()
void AddSC_instance_obsidian_sanctum ()
void AddSC_boss_malygos ()
void AddSC_instance_eye_of_eternity ()
void AddSC_boss_bjarngrim ()
void AddSC_boss_loken ()
void AddSC_boss_ionar ()
void AddSC_boss_volkhan ()
void AddSC_instance_halls_of_lightning ()
void AddSC_boss_maiden_of_grief ()
void AddSC_boss_krystallus ()
void AddSC_boss_sjonnir ()
void AddSC_brann_bronzebeard ()
void AddSC_instance_halls_of_stone ()
void AddSC_boss_auriaya ()
void AddSC_boss_flame_leviathan ()
void AddSC_boss_ignis ()
void AddSC_boss_razorscale ()
void AddSC_boss_xt002 ()
void AddSC_boss_assembly_of_iron ()
void AddSC_boss_mimiron ()
void AddSC_boss_hodir ()
void AddSC_boss_vezax ()
void AddSC_boss_kologarn ()
void AddSC_boss_freya ()
void AddSC_boss_thorim ()
void AddSC_boss_yoggsaron ()
void AddSC_ulduar ()
void AddSC_boss_algalon_the_observer ()
void AddSC_instance_ulduar ()
void AddSC_boss_keleseth ()
void AddSC_boss_skarvald_dalronn ()
void AddSC_boss_ingvar_the_plunderer ()
void AddSC_instance_utgarde_keep ()
void AddSC_boss_svala ()
void AddSC_boss_palehoof ()
void AddSC_boss_skadi ()
void AddSC_boss_ymiron ()
void AddSC_instance_utgarde_pinnacle ()
void AddSC_utgarde_pinnacle ()
void AddSC_utgarde_keep ()
void AddSC_boss_archavon ()
void AddSC_boss_emalon ()
void AddSC_boss_koralon ()
void AddSC_boss_toravon ()
void AddSC_instance_vault_of_archavon ()
void AddSC_boss_trollgore ()
void AddSC_boss_novos ()
void AddSC_boss_dred ()
void AddSC_boss_tharon_ja ()
void AddSC_instance_drak_tharon_keep ()
void AddSC_boss_cyanigosa ()
void AddSC_boss_erekem ()
void AddSC_boss_ichoron ()
void AddSC_boss_lavanthor ()
void AddSC_boss_moragg ()
void AddSC_boss_xevozz ()
void AddSC_boss_zuramat ()
void AddSC_instance_violet_hold ()
void AddSC_violet_hold ()
void AddSC_instance_forge_of_souls ()
void AddSC_forge_of_souls ()
void AddSC_boss_bronjahm ()
void AddSC_boss_devourer_of_souls ()
void AddSC_instance_pit_of_saron ()
void AddSC_pit_of_saron ()
void AddSC_boss_garfrost ()
void AddSC_boss_ick ()
void AddSC_boss_tyrannus ()
void AddSC_instance_halls_of_reflection ()
void AddSC_halls_of_reflection ()
void AddSC_boss_falric ()
void AddSC_boss_marwyn ()
void AddSC_boss_lord_marrowgar ()
void AddSC_boss_lady_deathwhisper ()
void AddSC_boss_icecrown_gunship_battle ()
void AddSC_boss_deathbringer_saurfang ()
void AddSC_boss_festergut ()
void AddSC_boss_rotface ()
void AddSC_boss_professor_putricide ()
void AddSC_boss_blood_prince_council ()
void AddSC_boss_blood_queen_lana_thel ()
void AddSC_boss_valithria_dreamwalker ()
void AddSC_boss_sindragosa ()
void AddSC_boss_the_lich_king ()
void AddSC_icecrown_citadel_teleport ()
void AddSC_instance_icecrown_citadel ()
void AddSC_icecrown_citadel ()
void AddSC_instance_ruby_sanctum ()
void AddSC_boss_baltharus_the_warborn ()
void AddSC_boss_saviana_ragefire ()
void AddSC_boss_general_zarithrian ()
void AddSC_boss_halion ()
void AddSC_dalaran ()
void AddSC_borean_tundra ()
void AddSC_dragonblight ()
void AddSC_grizzly_hills ()
void AddSC_howling_fjord ()
void AddSC_icecrown ()
void AddSC_sholazar_basin ()
void AddSC_storm_peaks ()
void AddSC_zuldrak ()
void AddSC_crystalsong_forest ()
void AddSC_isle_of_conquest ()
void AddSC_wintergrasp ()
void AddNorthrendScripts ()
Function Documentation
AddNorthrendScripts()
void AddNorthrendScripts ()
{
    AddSC_boss_slad_ran();               //Gundrak
    AddSC_boss_moorabi();
    AddSC_boss_drakkari_colossus();
    AddSC_boss_gal_darah();
    AddSC_boss_eck();
    AddSC_instance_gundrak();
    AddSC_boss_amanitar();
    AddSC_boss_taldaram();              //Azjol-Nerub Ahn'kahet
    AddSC_boss_elder_nadox();
    AddSC_boss_jedoga_shadowseeker();
    AddSC_boss_volazj();
    AddSC_instance_ahnkahet();
    AddSC_boss_argent_challenge();      //Trial of the Champion
    AddSC_boss_black_knight();
    AddSC_boss_grand_champions();
    AddSC_instance_trial_of_the_champion();
    AddSC_trial_of_the_champion();
    AddSC_boss_anubarak_trial();        //Trial of the Crusader
    AddSC_boss_faction_champions();
    AddSC_boss_jaraxxus();
    AddSC_trial_of_the_crusader();
    AddSC_boss_twin_valkyr();
    AddSC_boss_northrend_beasts();
    AddSC_instance_trial_of_the_crusader();
    AddSC_boss_krik_thir();             //Azjol-Nerub Azjol-Nerub
    AddSC_boss_hadronox();
    AddSC_boss_anub_arak();
    AddSC_instance_azjol_nerub();
    AddSC_boss_anubrekhan();            //Naxxramas
    AddSC_boss_maexxna();
    AddSC_boss_patchwerk();
    AddSC_boss_grobbulus();
    AddSC_boss_razuvious();
    AddSC_boss_kelthuzad();
    AddSC_boss_loatheb();
    AddSC_boss_noth();
    AddSC_boss_gluth();
    AddSC_boss_sapphiron();
    AddSC_boss_four_horsemen();
    AddSC_boss_faerlina();
    AddSC_boss_heigan();
    AddSC_boss_gothik();
    AddSC_boss_thaddius();
    AddSC_instance_naxxramas();
    AddSC_boss_magus_telestra();        //The Nexus Nexus
    AddSC_boss_anomalus();
    AddSC_boss_ormorok();
    AddSC_boss_keristrasza();
    AddSC_boss_commander_stoutbeard();
    AddSC_instance_nexus();
    AddSC_boss_drakos();                //The Nexus The Oculus
    AddSC_boss_varos();
    AddSC_boss_urom();
    AddSC_boss_eregos();
    AddSC_instance_oculus();
    AddSC_oculus();
    AddSC_boss_sartharion();            //Obsidian Sanctum
    AddSC_instance_obsidian_sanctum();
    AddSC_boss_malygos();                //Eye of Eternity
    AddSC_instance_eye_of_eternity();
    AddSC_boss_bjarngrim();             //Ulduar Halls of Lightning
    AddSC_boss_loken();
    AddSC_boss_ionar();
    AddSC_boss_volkhan();
    AddSC_instance_halls_of_lightning();
    AddSC_boss_maiden_of_grief();       //Ulduar Halls of Stone
    AddSC_boss_krystallus();
    AddSC_boss_sjonnir();
    AddSC_brann_bronzebeard();
    AddSC_instance_halls_of_stone();
    AddSC_boss_auriaya();               //Ulduar Ulduar
    AddSC_boss_flame_leviathan();
    AddSC_boss_ignis();
    AddSC_boss_razorscale();
    AddSC_boss_xt002();
    AddSC_boss_assembly_of_iron();
    AddSC_boss_mimiron();
    AddSC_boss_hodir();
    AddSC_boss_vezax();
    AddSC_boss_kologarn();
    AddSC_boss_freya();
    AddSC_boss_thorim();
    AddSC_boss_yoggsaron();
    AddSC_ulduar();
    AddSC_boss_algalon_the_observer();
    AddSC_instance_ulduar();
    AddSC_boss_keleseth();              //Utgarde Keep
    AddSC_boss_skarvald_dalronn();
    AddSC_boss_ingvar_the_plunderer();
    AddSC_instance_utgarde_keep();
    AddSC_boss_svala();                 //Utgarde pinnacle
    AddSC_boss_palehoof();
    AddSC_boss_skadi();
    AddSC_boss_ymiron();
    AddSC_instance_utgarde_pinnacle();
    AddSC_utgarde_pinnacle();
    AddSC_utgarde_keep();
    AddSC_boss_archavon();              //Vault of Archavon
    AddSC_boss_emalon();
    AddSC_boss_koralon();
    AddSC_boss_toravon();
    AddSC_instance_vault_of_archavon();
    AddSC_boss_trollgore();             //Drak'Tharon Keep
    AddSC_boss_novos();
    AddSC_boss_dred();
    AddSC_boss_tharon_ja();
    AddSC_instance_drak_tharon_keep();
    AddSC_boss_cyanigosa();             //Violet Hold
    AddSC_boss_erekem();
    AddSC_boss_ichoron();
    AddSC_boss_lavanthor();
    AddSC_boss_moragg();
    AddSC_boss_xevozz();
    AddSC_boss_zuramat();
    AddSC_instance_violet_hold();
    AddSC_violet_hold();
    AddSC_instance_forge_of_souls();   //Forge of Souls
    AddSC_forge_of_souls();
    AddSC_boss_bronjahm();
    AddSC_boss_devourer_of_souls();
    AddSC_instance_pit_of_saron();      //Pit of Saron
    AddSC_pit_of_saron();
    AddSC_boss_garfrost();
    AddSC_boss_ick();
    AddSC_boss_tyrannus();
    AddSC_instance_halls_of_reflection();   // Halls of Reflection
    AddSC_halls_of_reflection();
    AddSC_boss_falric();
    AddSC_boss_marwyn();
    AddSC_boss_lord_marrowgar();        // Icecrown Citadel
    AddSC_boss_lady_deathwhisper();
    AddSC_boss_icecrown_gunship_battle();
    AddSC_boss_deathbringer_saurfang();
    AddSC_boss_festergut();
    AddSC_boss_rotface();
    AddSC_boss_professor_putricide();
    AddSC_boss_blood_prince_council();
    AddSC_boss_blood_queen_lana_thel();
    AddSC_boss_valithria_dreamwalker();
    AddSC_boss_sindragosa();
    AddSC_boss_the_lich_king();
    AddSC_icecrown_citadel_teleport();
    AddSC_instance_icecrown_citadel();
    AddSC_icecrown_citadel();
    AddSC_instance_ruby_sanctum();      // Ruby Sanctum
    AddSC_boss_baltharus_the_warborn();
    AddSC_boss_saviana_ragefire();
    AddSC_boss_general_zarithrian();
    AddSC_boss_halion();
    AddSC_dalaran();
    AddSC_borean_tundra();
    AddSC_dragonblight();
    AddSC_grizzly_hills();
    AddSC_howling_fjord();
    AddSC_icecrown();
    AddSC_sholazar_basin();
    AddSC_storm_peaks();
    AddSC_zuldrak();
    AddSC_crystalsong_forest();
    AddSC_isle_of_conquest();
    AddSC_wintergrasp();
}
References AddSC_borean_tundra(), AddSC_boss_algalon_the_observer(), AddSC_boss_amanitar(), AddSC_boss_anomalus(), AddSC_boss_anub_arak(), AddSC_boss_anubarak_trial(), AddSC_boss_anubrekhan(), AddSC_boss_archavon(), AddSC_boss_argent_challenge(), AddSC_boss_assembly_of_iron(), AddSC_boss_auriaya(), AddSC_boss_baltharus_the_warborn(), AddSC_boss_bjarngrim(), AddSC_boss_black_knight(), AddSC_boss_blood_prince_council(), AddSC_boss_blood_queen_lana_thel(), AddSC_boss_bronjahm(), AddSC_boss_commander_stoutbeard(), AddSC_boss_cyanigosa(), AddSC_boss_deathbringer_saurfang(), AddSC_boss_devourer_of_souls(), AddSC_boss_drakkari_colossus(), AddSC_boss_drakos(), AddSC_boss_dred(), AddSC_boss_eck(), AddSC_boss_elder_nadox(), AddSC_boss_emalon(), AddSC_boss_eregos(), AddSC_boss_erekem(), AddSC_boss_faction_champions(), AddSC_boss_faerlina(), AddSC_boss_falric(), AddSC_boss_festergut(), AddSC_boss_flame_leviathan(), AddSC_boss_four_horsemen(), AddSC_boss_freya(), AddSC_boss_gal_darah(), AddSC_boss_garfrost(), AddSC_boss_general_zarithrian(), AddSC_boss_gluth(), AddSC_boss_gothik(), AddSC_boss_grand_champions(), AddSC_boss_grobbulus(), AddSC_boss_hadronox(), AddSC_boss_halion(), AddSC_boss_heigan(), AddSC_boss_hodir(), AddSC_boss_icecrown_gunship_battle(), AddSC_boss_ichoron(), AddSC_boss_ick(), AddSC_boss_ignis(), AddSC_boss_ingvar_the_plunderer(), AddSC_boss_ionar(), AddSC_boss_jaraxxus(), AddSC_boss_jedoga_shadowseeker(), AddSC_boss_keleseth(), AddSC_boss_kelthuzad(), AddSC_boss_keristrasza(), AddSC_boss_kologarn(), AddSC_boss_koralon(), AddSC_boss_krik_thir(), AddSC_boss_krystallus(), AddSC_boss_lady_deathwhisper(), AddSC_boss_lavanthor(), AddSC_boss_loatheb(), AddSC_boss_loken(), AddSC_boss_lord_marrowgar(), AddSC_boss_maexxna(), AddSC_boss_magus_telestra(), AddSC_boss_maiden_of_grief(), AddSC_boss_malygos(), AddSC_boss_marwyn(), AddSC_boss_mimiron(), AddSC_boss_moorabi(), AddSC_boss_moragg(), AddSC_boss_northrend_beasts(), AddSC_boss_noth(), AddSC_boss_novos(), AddSC_boss_ormorok(), AddSC_boss_palehoof(), AddSC_boss_patchwerk(), AddSC_boss_professor_putricide(), AddSC_boss_razorscale(), AddSC_boss_razuvious(), AddSC_boss_rotface(), AddSC_boss_sapphiron(), AddSC_boss_sartharion(), AddSC_boss_saviana_ragefire(), AddSC_boss_sindragosa(), AddSC_boss_sjonnir(), AddSC_boss_skadi(), AddSC_boss_skarvald_dalronn(), AddSC_boss_slad_ran(), AddSC_boss_svala(), AddSC_boss_taldaram(), AddSC_boss_thaddius(), AddSC_boss_tharon_ja(), AddSC_boss_the_lich_king(), AddSC_boss_thorim(), AddSC_boss_toravon(), AddSC_boss_trollgore(), AddSC_boss_twin_valkyr(), AddSC_boss_tyrannus(), AddSC_boss_urom(), AddSC_boss_valithria_dreamwalker(), AddSC_boss_varos(), AddSC_boss_vezax(), AddSC_boss_volazj(), AddSC_boss_volkhan(), AddSC_boss_xevozz(), AddSC_boss_xt002(), AddSC_boss_ymiron(), AddSC_boss_yoggsaron(), AddSC_boss_zuramat(), AddSC_brann_bronzebeard(), AddSC_crystalsong_forest(), AddSC_dalaran(), AddSC_dragonblight(), AddSC_forge_of_souls(), AddSC_grizzly_hills(), AddSC_halls_of_reflection(), AddSC_howling_fjord(), AddSC_icecrown(), AddSC_icecrown_citadel(), AddSC_icecrown_citadel_teleport(), AddSC_instance_ahnkahet(), AddSC_instance_azjol_nerub(), AddSC_instance_drak_tharon_keep(), AddSC_instance_eye_of_eternity(), AddSC_instance_forge_of_souls(), AddSC_instance_gundrak(), AddSC_instance_halls_of_lightning(), AddSC_instance_halls_of_reflection(), AddSC_instance_halls_of_stone(), AddSC_instance_icecrown_citadel(), AddSC_instance_naxxramas(), AddSC_instance_nexus(), AddSC_instance_obsidian_sanctum(), AddSC_instance_oculus(), AddSC_instance_pit_of_saron(), AddSC_instance_ruby_sanctum(), AddSC_instance_trial_of_the_champion(), AddSC_instance_trial_of_the_crusader(), AddSC_instance_ulduar(), AddSC_instance_utgarde_keep(), AddSC_instance_utgarde_pinnacle(), AddSC_instance_vault_of_archavon(), AddSC_instance_violet_hold(), AddSC_isle_of_conquest(), AddSC_oculus(), AddSC_pit_of_saron(), AddSC_sholazar_basin(), AddSC_storm_peaks(), AddSC_trial_of_the_champion(), AddSC_trial_of_the_crusader(), AddSC_ulduar(), AddSC_utgarde_keep(), AddSC_utgarde_pinnacle(), AddSC_violet_hold(), AddSC_wintergrasp(), and AddSC_zuldrak().
AddSC_borean_tundra()
void AddSC_borean_tundra ()
{
    RegisterSpellScript(spell_q11919_q11940_drake_hunt_aura);
    new npc_thassarian();
    new npc_thassarian2();
    new npc_leryssa();
    new npc_counselor_talbot();
    new npc_sinkhole_kill_credit();
    new npc_khunok_the_behemoth();
    new npc_iruk();
    new npc_nerubar_victim();
    new npc_lurgglbr();
    new npc_beryl_sorcerer();
    new npc_captured_beryl_sorcerer();
    RegisterSpellScript(spell_arcane_chains_character_force_cast);
    new npc_imprisoned_beryl_sorcerer();
    new npc_mootoo_the_younger();
    new npc_bonker_togglevolt();
    new npc_valiance_keep_cannoneer();
    new npc_warmage_coldarra();
    new npc_hidden_cultist();
    RegisterSpellScript(spell_q11719_bloodspore_ruination_45997);
    new npc_bloodmage_laurith();
    RegisterCreatureAI(npc_jenny);
    RegisterSpellScript(spell_necropolis_beam);
    RegisterSpellScript(spell_soul_deflection);
}
References RegisterCreatureAI, and RegisterSpellScript.
Referenced by AddNorthrendScripts().
AddSC_boss_algalon_the_observer()
void AddSC_boss_algalon_the_observer ()
{
    // NPCs
    new boss_algalon_the_observer();
    new npc_brann_bronzebeard_algalon();
    new npc_collapsing_star();
    new npc_living_constellation();
    new npc_algalon_worm_hole();
    // GOs
    new go_celestial_planetarium_access();
    // Spells
    RegisterSpellScript(spell_algalon_phase_punch_aura);
    RegisterSpellScript(spell_algalon_collapse_aura);
    RegisterSpellScript(spell_algalon_trigger_3_adds);
    RegisterSpellScript(spell_algalon_cosmic_smash_damage);
    RegisterSpellScript(spell_algalon_big_bang);
    RegisterSpellScript(spell_algalon_remove_phase_aura);
    RegisterSpellScript(spell_algalon_supermassive_fail);
    // Achievements
    new achievement_algalon_he_feeds_on_your_tears();
    new achievement_algalon_herald_of_the_titans();
}
References RegisterSpellScript.
Referenced by AddNorthrendScripts().
AddSC_boss_amanitar()
void AddSC_boss_amanitar ()
{
    RegisterAhnKahetCreatureAI(boss_amanitar);
    RegisterSpellScript(spell_amanitar_remove_mushroom_power);
}
References RegisterAhnKahetCreatureAI, and RegisterSpellScript.
Referenced by AddNorthrendScripts().
AddSC_boss_anomalus()
void AddSC_boss_anomalus ()
{
    RegisterNexusCreatureAI(boss_anomalus);
    new achievement_chaos_theory();
}
References RegisterNexusCreatureAI.
Referenced by AddNorthrendScripts().
AddSC_boss_anub_arak()
void AddSC_boss_anub_arak ()
{
    RegisterAzjolNerubCreatureAI(boss_anub_arak);
    RegisterSpellScript(spell_azjol_nerub_carrion_beetles);
    RegisterSpellScript(spell_azjol_nerub_pound);
    RegisterSpellScript(spell_azjol_nerub_impale_summon);
}
References RegisterAzjolNerubCreatureAI, and RegisterSpellScript.
Referenced by AddNorthrendScripts().
AddSC_boss_anubarak_trial()
void AddSC_boss_anubarak_trial ()
{
    new boss_anubarak_trial();
    new npc_swarm_scarab();
    new npc_frost_sphere();
    new npc_nerubian_burrower();
    new npc_anubarak_spike();
    RegisterSpellScript(spell_pursuing_spikes_aura);
    RegisterSpellScript(spell_gen_leeching_swarm_aura);
    RegisterSpellScript(spell_gen_leeching_swarm_dmg);
}
References RegisterSpellScript.
Referenced by AddNorthrendScripts().
AddSC_boss_anubrekhan()
void AddSC_boss_anubrekhan ()
{
    new boss_anubrekhan();
}
Referenced by AddNorthrendScripts().
AddSC_boss_archavon()
void AddSC_boss_archavon ()
{
    new boss_archavon();
    RegisterSpellScript(spell_archavon_rock_shards);
}
References RegisterSpellScript.
Referenced by AddNorthrendScripts().
AddSC_boss_argent_challenge()
void AddSC_boss_argent_challenge ()
{
    new boss_eadric();
    new boss_paletress();
    new npc_memory();
    new npc_argent_soldier();
    RegisterSpellScript(spell_eadric_radiance);
    RegisterSpellScript(spell_toc5_light_rain);
    RegisterSpellScript(spell_reflective_shield_aura);
}
References RegisterSpellScript.
Referenced by AddNorthrendScripts().
AddSC_boss_assembly_of_iron()
void AddSC_boss_assembly_of_iron ()
{
    new boss_steelbreaker();
    new boss_runemaster_molgeim();
    new boss_stormcaller_brundir();
    new npc_assembly_lightning();
    RegisterSpellScript(spell_shield_of_runes_aura);
    RegisterSpellScript(spell_assembly_meltdown);
    RegisterSpellScript(spell_assembly_rune_of_summoning_aura);
    new achievement_assembly_of_iron("achievement_but_im_on_your_side", 0);
    new achievement_assembly_of_iron("achievement_assembly_steelbreaker", NPC_STEELBREAKER);
    new achievement_assembly_of_iron("achievement_assembly_runemaster", NPC_MOLGEIM);
    new achievement_assembly_of_iron("achievement_assembly_stormcaller", NPC_BRUNDIR);
    new achievement_cant_do_that_while_stunned();
}
References NPC_BRUNDIR, NPC_MOLGEIM, NPC_STEELBREAKER, and RegisterSpellScript.
Referenced by AddNorthrendScripts().
AddSC_boss_auriaya()
void AddSC_boss_auriaya ()
{
    new boss_auriaya();
    new npc_auriaya_sanctum_sentry();
    new npc_auriaya_feral_defender();
    RegisterSpellScript(spell_auriaya_sentinel_blast);
    new achievement_auriaya_crazy_cat_lady();
    new achievement_auriaya_nine_lives();
}
References RegisterSpellScript.
Referenced by AddNorthrendScripts().
AddSC_boss_baltharus_the_warborn()
void AddSC_boss_baltharus_the_warborn ()
{
    new boss_baltharus_the_warborn();
    new npc_baltharus_the_warborn_clone();
    RegisterSpellScript(spell_baltharus_enervating_brand_trigger);
    new npc_xerestrasza();
    new at_baltharus_plateau();
}
References RegisterSpellScript.
Referenced by AddNorthrendScripts().
AddSC_boss_bjarngrim()
void AddSC_boss_bjarngrim ()
{
    RegisterHallOfLightningCreatureAI(boss_bjarngrim);
    RegisterHallOfLightningCreatureAI(npc_stormforged_lieutenant);
}
References RegisterHallOfLightningCreatureAI.
Referenced by AddNorthrendScripts().
AddSC_boss_black_knight()
void AddSC_boss_black_knight ()
{
    new boss_black_knight();
    new npc_black_knight_skeletal_gryphon();
    new npc_black_knight_ghoul();
    RegisterSpellScript(spell_black_knight_ghoul_claw);
    RegisterSpellScript(spell_black_knight_ghoul_explode);
}
References RegisterSpellScript.
Referenced by AddNorthrendScripts().
AddSC_boss_blood_prince_council()
void AddSC_boss_blood_prince_council ()
{
    new boss_prince_keleseth_icc();
    new boss_prince_taldaram_icc();
    new boss_prince_valanar_icc();
    new npc_blood_queen_lana_thel();
    new npc_dark_nucleus();
    new npc_ball_of_flame();
    new npc_kinetic_bomb();
    RegisterSpellScript(spell_blood_council_shadow_prison_aura);
    RegisterSpellScript(spell_blood_council_shadow_prison_damage);
    RegisterSpellScript(spell_taldaram_glittering_sparks);
    RegisterSpellScript(spell_taldaram_summon_flame_ball);
    RegisterSpellScript(spell_taldaram_ball_of_inferno_flame);
    RegisterSpellAndAuraScriptPair(spell_valanar_kinetic_bomb, spell_valanar_kinetic_bomb_aura);
    RegisterSpellScript(spell_valanar_kinetic_bomb_absorb_aura);
    RegisterSpellScript(spell_valanar_kinetic_bomb_knockback);
    RegisterSpellScript(spell_valanar_kinetic_bomb_summon);
    RegisterSpellScript(spell_blood_council_summon_shadow_resonance);
}
References RegisterSpellAndAuraScriptPair, and RegisterSpellScript.
Referenced by AddNorthrendScripts().
AddSC_boss_blood_queen_lana_thel()
void AddSC_boss_blood_queen_lana_thel ()
{
    new boss_blood_queen_lana_thel();
    RegisterSpellScript(spell_blood_queen_pact_of_the_darkfallen_dmg_aura);
    RegisterSpellScript(spell_blood_queen_pact_of_the_darkfallen);
    RegisterSpellScript(spell_blood_queen_pact_of_the_darkfallen_dmg_target);
    RegisterSpellScript(spell_blood_queen_bloodbolt);
    RegisterSpellScript(spell_blood_queen_frenzied_bloodthirst_aura);
    RegisterSpellScript(spell_blood_queen_essence_of_the_blood_queen_aura);
    RegisterSpellScript(spell_blood_queen_vampiric_bite);
    RegisterSpellScript(spell_blood_queen_swarming_shadows_floor_dmg);
    RegisterSpellScript(spell_blood_queen_presence_of_the_darkfallen);
    new achievement_once_bitten_twice_shy("achievement_once_bitten_twice_shy_n_10", 0, false);
    new achievement_once_bitten_twice_shy("achievement_once_bitten_twice_shy_v_10", 0, true);
    new achievement_once_bitten_twice_shy("achievement_once_bitten_twice_shy_n_25", 1, false);
    new achievement_once_bitten_twice_shy("achievement_once_bitten_twice_shy_v_25", 1, true);
}
References RegisterSpellScript.
Referenced by AddNorthrendScripts().
AddSC_boss_bronjahm()
void AddSC_boss_bronjahm ()
{
    new boss_bronjahm();
    new npc_fos_corrupted_soul_fragment();
    RegisterSpellScript(spell_bronjahm_magic_bane);
    RegisterSpellScript(spell_bronjahm_soulstorm_channel_ooc_aura);
    RegisterSpellScript(spell_bronjahm_soulstorm_visual_aura);
    RegisterSpellScript(spell_bronjahm_soulstorm_targeting);
}
References RegisterSpellScript.
Referenced by AddNorthrendScripts().
AddSC_boss_commander_stoutbeard()
void AddSC_boss_commander_stoutbeard ()
{
    RegisterNexusCreatureAI(boss_commander_stoutbeard);
}
References RegisterNexusCreatureAI.
Referenced by AddNorthrendScripts().
AddSC_boss_cyanigosa()
void AddSC_boss_cyanigosa ()
{
    new boss_cyanigosa();
}
Referenced by AddNorthrendScripts().
AddSC_boss_deathbringer_saurfang()
void AddSC_boss_deathbringer_saurfang ()
{
    new boss_deathbringer_saurfang();
    new npc_high_overlord_saurfang_icc();
    new npc_muradin_bronzebeard_icc();
    new npc_saurfang_event();
    RegisterSpellScript(spell_deathbringer_blood_link_aura);
    RegisterSpellScript(spell_deathbringer_blood_link_blood_beast_aura);
    RegisterSpellScript(spell_deathbringer_blood_link);
    RegisterSpellAndAuraScriptPair(spell_deathbringer_blood_power, spell_deathbringer_blood_power_aura);
    RegisterSpellScript(spell_deathbringer_blood_nova_targeting);
    RegisterSpellScript(spell_deathbringer_boiling_blood);
    new achievement_ive_gone_and_made_a_mess();
    new npc_icc_blood_beast();
}
References RegisterSpellAndAuraScriptPair, and RegisterSpellScript.
Referenced by AddNorthrendScripts().
AddSC_boss_devourer_of_souls()
void AddSC_boss_devourer_of_souls ()
{
    new boss_devourer_of_souls();
    RegisterSpellScript(spell_wailing_souls_periodic_aura);
}
References RegisterSpellScript.
Referenced by AddNorthrendScripts().
AddSC_boss_drakkari_colossus()
void AddSC_boss_drakkari_colossus ()
{
    new boss_drakkari_colossus();
    new boss_drakkari_elemental();
    new npc_living_mojo();
    RegisterSpellScript(spell_drakkari_colossus_emerge);
    RegisterSpellScript(spell_drakkari_colossus_surge);
    RegisterSpellScript(spell_drakkari_colossus_face_me);
}
References RegisterSpellScript.
Referenced by AddNorthrendScripts().
AddSC_boss_drakos()
void AddSC_boss_drakos ()
{
    new boss_drakos();
    new npc_oculus_unstable_sphere();
}
Referenced by AddNorthrendScripts().
AddSC_boss_dred()
void AddSC_boss_dred ()
{
    new boss_dred();
    RegisterSpellScript(spell_dred_grievious_bite_aura);
    RegisterSpellScript(spell_dred_raptor_call);
    new achievement_better_off_dred();
}
References RegisterSpellScript.
Referenced by AddNorthrendScripts().
AddSC_boss_eck()
void AddSC_boss_eck ()
{
    new boss_eck();
}
Referenced by AddNorthrendScripts().
AddSC_boss_elder_nadox()
void AddSC_boss_elder_nadox ()
{
    // Creatures
    RegisterAhnKahetCreatureAI(boss_elder_nadox);
    RegisterAhnKahetCreatureAI(npc_ahnkahar_nerubian);
    // Spells
    RegisterSpellScript(spell_ahn_kahet_swarmer_aura);
    // Achievements
    new achievement_respect_your_elders();
}
References RegisterAhnKahetCreatureAI, and RegisterSpellScript.
Referenced by AddNorthrendScripts().
AddSC_boss_emalon()
void AddSC_boss_emalon ()
{
    new boss_emalon();
    RegisterSpellScript(spell_voa_overcharge_aura);
    RegisterSpellScript(spell_voa_lightning_nova);
}
References RegisterSpellScript.
Referenced by AddNorthrendScripts().
AddSC_boss_eregos()
void AddSC_boss_eregos ()
{
    new boss_eregos();
}
Referenced by AddNorthrendScripts().
AddSC_boss_erekem()
void AddSC_boss_erekem ()
{
    new boss_erekem();
    new npc_erekem_guard();
}
Referenced by AddNorthrendScripts().
AddSC_boss_faction_champions()
void AddSC_boss_faction_champions ()
{
    new npc_toc_druid();
    new npc_toc_shaman();
    new npc_toc_paladin();
    new npc_toc_priest();
    new npc_toc_shadow_priest();
    new npc_toc_mage();
    new npc_toc_warlock();
    new npc_toc_hunter();
    new npc_toc_boomkin();
    new npc_toc_warrior();
    new npc_toc_dk();
    new npc_toc_rogue();
    new npc_toc_enh_shaman();
    new npc_toc_retro_paladin();
    new npc_toc_pet_warlock();
    new npc_toc_pet_hunter();
    RegisterSpellScript(spell_faction_champion_warl_unstable_affliction_aura);
}
References RegisterSpellScript.
Referenced by AddNorthrendScripts().
AddSC_boss_faerlina()
void AddSC_boss_faerlina ()
{
    new boss_faerlina();
}
Referenced by AddNorthrendScripts().
AddSC_boss_falric()
void AddSC_boss_falric ()
{
    new boss_falric();
}
Referenced by AddNorthrendScripts().
AddSC_boss_festergut()
void AddSC_boss_festergut ()
{
    new boss_festergut();
    RegisterSpellScript(spell_festergut_pungent_blight);
    RegisterSpellScript(spell_festergut_blighted_spores_aura);
    RegisterSpellScript(spell_festergut_gastric_bloat);
    RegisterSpellScript(spell_festergut_gaseous_blight);
    new achievement_flu_shot_shortage();
    new npc_stinky_icc();
}
References RegisterSpellScript.
Referenced by AddNorthrendScripts().
AddSC_boss_flame_leviathan()
void AddSC_boss_flame_leviathan ()
{
    new boss_flame_leviathan();
    new boss_flame_leviathan_seat();
    new boss_flame_leviathan_defense_turret();
    new boss_flame_leviathan_overload_device();
    new npc_pool_of_tar();
    // Hard Mode
    new npc_freya_ward();
    new npc_thorims_hammer();
    new npc_mimirons_inferno();
    new npc_hodirs_fury();
    // Helpers
    new npc_brann_radio();
    new npc_storm_beacon_spawn();
    new boss_flame_leviathan_safety_container();
    new npc_mechanolift();
    // GOs
    new go_ulduar_tower();
    // Spells
    RegisterSpellScript(spell_load_into_catapult_aura);
    RegisterSpellScript(spell_auto_repair);
    RegisterSpellScript(spell_systems_shutdown_aura);
    RegisterSpellScript(spell_pursue);
    RegisterSpellScript(spell_vehicle_throw_passenger);
    RegisterSpellScript(spell_tar_blaze_aura);
    RegisterSpellScript(spell_vehicle_grab_pyrite);
    RegisterSpellScript(spell_vehicle_circuit_overload_aura);
    RegisterSpellScript(spell_orbital_supports_aura);
    RegisterSpellScript(spell_thorims_hammer);
    RegisterSpellScript(spell_transitus_shield_beam_aura);
    RegisterSpellScript(spell_shield_generator_aura);
    RegisterSpellScript(spell_demolisher_ride_vehicle);
    // Achievements
    new achievement_flame_leviathan_towers("achievement_flame_leviathan_orbital_bombardment", 1);
    new achievement_flame_leviathan_towers("achievement_flame_leviathan_orbital_devastation", 2);
    new achievement_flame_leviathan_towers("achievement_flame_leviathan_nuked_from_orbit", 3);
    new achievement_flame_leviathan_towers("achievement_flame_leviathan_orbituary", 4);
    new achievement_flame_leviathan_shutout();
    new achievement_flame_leviathan_garage("achievement_flame_leviathan_garage_chopper", NPC_VEHICLE_CHOPPER, 0);
    new achievement_flame_leviathan_garage("achievement_flame_leviathan_garage_siege_engine", NPC_SALVAGED_SIEGE_ENGINE, NPC_SALVAGED_SIEGE_ENGINE_TURRET);
    new achievement_flame_leviathan_garage("achievement_flame_leviathan_garage_demolisher", NPC_SALVAGED_DEMOLISHER, NPC_SALVAGED_DEMOLISHER_TURRET);
    new achievement_flame_leviathan_unbroken();
}
References boss_flame_leviathan::boss_flame_leviathan(), NPC_SALVAGED_DEMOLISHER, NPC_SALVAGED_DEMOLISHER_TURRET, NPC_SALVAGED_SIEGE_ENGINE, NPC_SALVAGED_SIEGE_ENGINE_TURRET, NPC_VEHICLE_CHOPPER, and RegisterSpellScript.
Referenced by AddNorthrendScripts().
AddSC_boss_four_horsemen()
void AddSC_boss_four_horsemen ()
{
    new boss_four_horsemen();
    RegisterSpellScript(spell_four_horsemen_mark_aura);
}
References RegisterSpellScript.
Referenced by AddNorthrendScripts().
AddSC_boss_freya()
void AddSC_boss_freya ()
{
    new boss_freya();
    new boss_freya_elder_stonebark();
    new boss_freya_elder_brightleaf();
    new boss_freya_elder_ironbranch();
    new boss_freya_iron_root();
    new boss_freya_lifebinder();
    new boss_freya_healthy_spore();
    new boss_freya_summons();
    new boss_freya_nature_bomb();
    new achievement_freya_getting_back_to_nature();
    new achievement_freya_knock_on_wood("achievement_freya_knock_on_wood", 1);
    new achievement_freya_knock_on_wood("achievement_freya_knock_knock_on_wood", 2);
    new achievement_freya_knock_on_wood("achievement_freya_knock_knock_knock_on_wood", 3);
}
Referenced by AddNorthrendScripts().
AddSC_boss_gal_darah()
void AddSC_boss_gal_darah ()
{
    RegisterGundrakCreatureAI(boss_gal_darah);
    RegisterSpellScript(spell_galdarah_impaling_charge);
    RegisterSpellScript(spell_galdarah_transform);
    new achievement_share_the_love();
}
References RegisterGundrakCreatureAI, and RegisterSpellScript.
Referenced by AddNorthrendScripts().
AddSC_boss_garfrost()
void AddSC_boss_garfrost ()
{
    new boss_garfrost();
    RegisterSpellScript(spell_garfrost_permafrost);
}
References RegisterSpellScript.
Referenced by AddNorthrendScripts().
AddSC_boss_general_zarithrian()
void AddSC_boss_general_zarithrian ()
{
    new boss_general_zarithrian();
    new npc_onyx_flamecaller();
}
Referenced by AddNorthrendScripts().
AddSC_boss_gluth()
void AddSC_boss_gluth ()
{
    new boss_gluth();
    RegisterSpellScript(spell_gluth_decimate);
}
References RegisterSpellScript.
Referenced by AddNorthrendScripts().
AddSC_boss_gothik()
void AddSC_boss_gothik ()
{
    new boss_gothik();
    new npc_boss_gothik_minion();
    new npc_gothik_trigger();
    RegisterSpellScript(spell_gothik_shadow_bolt_volley);
}
References RegisterSpellScript.
Referenced by AddNorthrendScripts().
AddSC_boss_grand_champions()
void AddSC_boss_grand_champions ()
{
    new boss_grand_champion();
    new npc_toc5_grand_champion_minion();
    new npc_toc5_player_vehicle();
}
Referenced by AddNorthrendScripts().
AddSC_boss_grobbulus()
void AddSC_boss_grobbulus ()
{
    new boss_grobbulus();
    new boss_grobbulus_poison_cloud();
    RegisterSpellScript(spell_grobbulus_mutating_injection_aura);
    RegisterSpellScript(spell_grobbulus_poison);
    RegisterSpellScript(spell_grobbulus_slime_spray);
}
References RegisterSpellScript.
Referenced by AddNorthrendScripts().
AddSC_boss_hadronox()
void AddSC_boss_hadronox ()
{
    new boss_hadronox();
    new npc_anub_ar_crusher();
    RegisterSpellScriptWithArgs(spell_hadronox_summon_periodic_aura, "spell_hadronox_summon_periodic_champion_aura", 15000, SPELL_SUMMON_ANUBAR_CHAMPION);
    RegisterSpellScriptWithArgs(spell_hadronox_summon_periodic_aura, "spell_hadronox_summon_periodic_necromancer_aura", 10000, SPELL_SUMMON_ANUBAR_NECROMANCER);
    RegisterSpellScriptWithArgs(spell_hadronox_summon_periodic_aura, "spell_hadronox_summon_periodic_crypt_fiend_aura", 5000, SPELL_SUMMON_ANUBAR_CRYPT_FIEND);
    RegisterSpellScript(spell_hadronox_leech_poison_aura);
    new achievement_hadronox_denied();
}
References RegisterSpellScript, RegisterSpellScriptWithArgs, SPELL_SUMMON_ANUBAR_CHAMPION, SPELL_SUMMON_ANUBAR_CRYPT_FIEND, and SPELL_SUMMON_ANUBAR_NECROMANCER.
Referenced by AddNorthrendScripts().
AddSC_boss_halion()
void AddSC_boss_halion ()
{
    new boss_halion();
    new boss_twilight_halion();
    new npc_halion_controller();
    new npc_orb_carrier();
    new npc_living_inferno();
    RegisterSpellScript(spell_halion_meteor_strike_targeting);
    RegisterSpellScript(spell_halion_meteor_strike_marker_aura);
    RegisterSpellScript(spell_halion_meteor_strike_spread_aura);
    RegisterSpellScript(spell_halion_blazing_aura);
    RegisterSpellScriptWithArgs(spell_halion_combustion_consumption_aura, "spell_halion_soul_consumption_aura", SPELL_MARK_OF_CONSUMPTION);
    RegisterSpellScriptWithArgs(spell_halion_combustion_consumption_aura, "spell_halion_fiery_combustion_aura", SPELL_MARK_OF_COMBUSTION);
    RegisterSpellScriptWithArgs(spell_halion_marks_aura, "spell_halion_mark_of_combustion_aura", SPELL_FIERY_COMBUSTION_SUMMON, SPELL_FIERY_COMBUSTION);
    RegisterSpellScriptWithArgs(spell_halion_marks_aura, "spell_halion_mark_of_consumption_aura", SPELL_SOUL_CONSUMPTION_SUMMON, SPELL_SOUL_CONSUMPTION);
    RegisterSpellScriptWithArgs(spell_halion_damage_aoe_summon, "spell_halion_combustion_summon", SPELL_FIERY_COMBUSTION_EXPLOSION, SPELL_COMBUSTION_DAMAGE_AURA);
    RegisterSpellScriptWithArgs(spell_halion_damage_aoe_summon, "spell_halion_consumption_summon", SPELL_SOUL_CONSUMPTION_EXPLOSION, SPELL_CONSUMPTION_DAMAGE_AURA);
    RegisterSpellScript(spell_halion_clear_debuffs);
    RegisterSpellAndAuraScriptPair(spell_halion_twilight_phasing, spell_halion_twilight_phasing_aura);
    RegisterSpellScript(spell_halion_twilight_realm_aura);
    RegisterSpellScript(spell_halion_leave_twilight_realm_aura);
    RegisterSpellScript(spell_halion_twilight_cutter_periodic_aura);
    RegisterSpellScript(spell_halion_twilight_cutter);
    RegisterSpellScript(spell_halion_summon_exit_portals);
    RegisterSpellScript(spell_halion_twilight_division);
    RegisterSpellScript(spell_halion_twilight_mending);
}
References RegisterSpellAndAuraScriptPair, RegisterSpellScript, RegisterSpellScriptWithArgs, SPELL_COMBUSTION_DAMAGE_AURA, SPELL_CONSUMPTION_DAMAGE_AURA, SPELL_FIERY_COMBUSTION, SPELL_FIERY_COMBUSTION_EXPLOSION, SPELL_FIERY_COMBUSTION_SUMMON, SPELL_MARK_OF_COMBUSTION, SPELL_MARK_OF_CONSUMPTION, SPELL_SOUL_CONSUMPTION, SPELL_SOUL_CONSUMPTION_EXPLOSION, and SPELL_SOUL_CONSUMPTION_SUMMON.
Referenced by AddNorthrendScripts().
AddSC_boss_heigan()
void AddSC_boss_heigan ()
{
    new boss_heigan();
}
Referenced by AddNorthrendScripts().
AddSC_boss_hodir()
void AddSC_boss_hodir ()
{
    new boss_hodir();
    new npc_ulduar_icicle();
    new npc_ulduar_flash_freeze();
    new npc_ulduar_toasty_fire();
    new npc_ulduar_hodir_priest();
    new npc_ulduar_hodir_druid();
    new npc_ulduar_hodir_shaman();
    new npc_ulduar_hodir_mage();
    RegisterSpellScript(spell_hodir_shatter_chest);
    RegisterSpellScript(spell_hodir_biting_cold_main_aura);
    RegisterSpellScript(spell_hodir_biting_cold_player_aura);
    RegisterSpellScript(spell_hodir_periodic_icicle);
    RegisterSpellAndAuraScriptPair(spell_hodir_flash_freeze, spell_hodir_flash_freeze_aura);
    RegisterSpellScript(spell_hodir_storm_power_aura);
    RegisterSpellScript(spell_hodir_storm_cloud_aura);
    RegisterSpellScript(spell_hodir_toasty_fire_aura);
    RegisterSpellScript(spell_hodir_starlight_aura);
    new achievement_cheese_the_freeze();
    new achievement_getting_cold_in_here();
    new achievement_i_could_say_that_this_cache_was_rare();
    new achievement_i_have_the_coolest_friends();
    new achievement_staying_buffed_all_winter_10();
    new achievement_staying_buffed_all_winter_25();
}
References RegisterSpellAndAuraScriptPair, and RegisterSpellScript.
Referenced by AddNorthrendScripts().
AddSC_boss_icecrown_gunship_battle()
void AddSC_boss_icecrown_gunship_battle ()
{
    new npc_gunship();
    new npc_high_overlord_saurfang_igb();
    new npc_muradin_bronzebeard_igb();
    new npc_zafod_boombox();
    new npc_igb_ship_crew();
    new npc_gunship_boarding_leader();
    new npc_gunship_boarding_add();
    new npc_gunship_mage();
    new npc_gunship_gunner();
    new npc_gunship_rocketeer();
    RegisterSpellScript(spell_igb_rocket_pack_aura);
    RegisterSpellScript(spell_igb_rocket_pack_useable_aura);
    RegisterSpellScript(spell_igb_teleport_to_enemy_ship);
    RegisterSpellScript(spell_igb_check_for_players);
    RegisterSpellScript(spell_igb_gunship_fall_teleport);
    RegisterSpellScript(spell_igb_explosion_main_aura);
    RegisterSpellScript(spell_igb_explosion);
    RegisterSpellScript(spell_igb_teleport_players_on_victory);
    RegisterSpellScript(spell_igb_periodic_trigger_with_power_cost_aura);
    RegisterSpellScript(spell_igb_overheat_aura);
    RegisterSpellScript(spell_igb_cannon_blast);
    RegisterSpellScript(spell_igb_incinerating_blast);
    RegisterSpellScript(spell_igb_burning_pitch_selector);
    RegisterSpellScript(spell_igb_burning_pitch);
    RegisterSpellScript(spell_igb_rocket_artillery);
    RegisterSpellScript(spell_igb_rocket_artillery_explosion);
    RegisterSpellScript(spell_igb_below_zero);
    RegisterSpellScript(spell_igb_on_gunship_deck_aura);
    new achievement_im_on_a_boat();
    RegisterSpellScript(spell_igb_battle_experience_check);
}
References RegisterSpellScript.
Referenced by AddNorthrendScripts().
AddSC_boss_ichoron()
void AddSC_boss_ichoron ()
{
    new boss_ichoron();
    new npc_ichor_globule();
}
Referenced by AddNorthrendScripts().
AddSC_boss_ick()
void AddSC_boss_ick ()
{
    new boss_ick();
    new boss_krick();
    RegisterSpellScript(spell_krick_explosive_barrage_aura);
    RegisterSpellScript(spell_exploding_orb_auto_grow_aura);
}
References RegisterSpellScript.
Referenced by AddNorthrendScripts().
AddSC_boss_ignis()
void AddSC_boss_ignis ()
{
    new boss_ignis();
    new npc_ulduar_iron_construct();
    RegisterSpellScript(spell_ignis_scorch_aura);
    RegisterSpellScript(spell_ignis_grab_initial);
    RegisterSpellScript(spell_ignis_slag_pot_aura);
    new achievement_ignis_shattered();
}
References RegisterSpellScript.
Referenced by AddNorthrendScripts().
AddSC_boss_ingvar_the_plunderer()
void AddSC_boss_ingvar_the_plunderer ()
{
    RegisterUtgardeKeepCreatureAI(boss_ingvar_the_plunderer);
}
References RegisterUtgardeKeepCreatureAI.
Referenced by AddNorthrendScripts().
AddSC_boss_ionar()
void AddSC_boss_ionar ()
{
    RegisterHallOfLightningCreatureAI(boss_ionar);
    RegisterHallOfLightningCreatureAI(npc_spark_of_ionar);
    RegisterSpellScript(spell_ionar_static_overload);
}
References RegisterHallOfLightningCreatureAI, and RegisterSpellScript.
Referenced by AddNorthrendScripts().
AddSC_boss_jaraxxus()
void AddSC_boss_jaraxxus ()
{
    new boss_jaraxxus();
    new npc_fel_infernal();
    new npc_mistress_of_pain();
    RegisterSpellScript(spell_toc25_mistress_kiss_aura);
    RegisterSpellScript(spell_mistress_kiss_area);
}
References RegisterSpellScript.
Referenced by AddNorthrendScripts().
AddSC_boss_jedoga_shadowseeker()
void AddSC_boss_jedoga_shadowseeker ()
{
    // Creatures
    RegisterAhnKahetCreatureAI(boss_jedoga_shadowseeker);
    RegisterAhnKahetCreatureAI(npc_twilight_volunteer);
    // Spells
    RegisterSpellScript(spell_random_lightning_visual_effect);
    // Achievements
    new achievement_volunteer_work();
}
References RegisterAhnKahetCreatureAI, and RegisterSpellScript.
Referenced by AddNorthrendScripts().
AddSC_boss_keleseth()
void AddSC_boss_keleseth ()
{
    RegisterUtgardeKeepCreatureAI(boss_keleseth);
    RegisterUtgardeKeepCreatureAI(npc_frost_tomb);
    RegisterUtgardeKeepCreatureAI(npc_vrykul_skeleton);
    RegisterSpellScript(spell_frost_tomb_aura);
}
References RegisterSpellScript, and RegisterUtgardeKeepCreatureAI.
Referenced by AddNorthrendScripts().
AddSC_boss_kelthuzad()
void AddSC_boss_kelthuzad ()
{
    new boss_kelthuzad();
    new boss_kelthuzad_minion();
    RegisterSpellScript(spell_kelthuzad_frost_blast);
    RegisterSpellScript(spell_kelthuzad_detonate_mana_aura);
}
References RegisterSpellScript.
Referenced by AddNorthrendScripts().
AddSC_boss_keristrasza()
void AddSC_boss_keristrasza ()
{
    RegisterNexusCreatureAI(boss_keristrasza);
    new achievement_intense_cold();
}
References RegisterNexusCreatureAI.
Referenced by AddNorthrendScripts().
AddSC_boss_kologarn()
void AddSC_boss_kologarn ()
{
    // Npcs
    new boss_kologarn();
    new boss_kologarn_arms();
    new boss_kologarn_eyebeam();
    RegisterUlduarCreatureAI(boss_kologarn_pit_kill_bunny);
    // Spells
    RegisterSpellScript(spell_ulduar_stone_grip_cast_target);
    RegisterSpellScript(spell_ulduar_stone_grip_aura);
    RegisterSpellScript(spell_ulduar_squeezed_lifeless);
    RegisterSpellScript(spell_kologarn_focused_eyebeam);
    RegisterSpellScript(spell_kologarn_stone_shout);
    RegisterSpellScript(spell_kologarn_stone_shout_aura);
    // Achievements
    new achievement_kologarn_looks_could_kill();
    new achievement_kologarn_rubble_and_roll();
    new achievement_kologarn_with_open_arms();
}
References RegisterSpellScript, and RegisterUlduarCreatureAI.
Referenced by AddNorthrendScripts().
AddSC_boss_koralon()
void AddSC_boss_koralon ()
{
    new boss_koralon();
    RegisterSpellScript(spell_voa_flaming_cinder);
    RegisterSpellScript(spell_koralon_meteor_fists_aura);
    RegisterSpellScript(spell_flame_warder_meteor_fists_aura);
}
References RegisterSpellScript.
Referenced by AddNorthrendScripts().
AddSC_boss_krik_thir()
void AddSC_boss_krik_thir ()
{
    new boss_krik_thir();
    new achievement_watch_him_die();
}
Referenced by AddNorthrendScripts().
AddSC_boss_krystallus()
void AddSC_boss_krystallus ()
{
    new boss_krystallus();
    RegisterSpellScript(spell_krystallus_shatter);
    RegisterSpellScript(spell_krystallus_shatter_effect);
}
References RegisterSpellScript.
Referenced by AddNorthrendScripts().
AddSC_boss_lady_deathwhisper()
void AddSC_boss_lady_deathwhisper ()
{
    // Creatures
    new boss_lady_deathwhisper();
    new npc_cult_fanatic();
    new npc_cult_adherent();
    new npc_vengeful_shade();
    new npc_darnavan();
    // Spells
    RegisterSpellScript(spell_deathwhisper_mana_barrier_aura);
    RegisterSpellScript(spell_deathwhisper_dark_reckoning);
    // AreaTriggers
    new at_lady_deathwhisper_entrance();
}
References RegisterSpellScript.
Referenced by AddNorthrendScripts().
AddSC_boss_lavanthor()
void AddSC_boss_lavanthor ()
{
    new boss_lavanthor();
}
Referenced by AddNorthrendScripts().
AddSC_boss_loatheb()
void AddSC_boss_loatheb ()
{
    new boss_loatheb();
}
Referenced by AddNorthrendScripts().
AddSC_boss_loken()
void AddSC_boss_loken ()
{
    RegisterHallOfLightningCreatureAI(boss_loken);
    RegisterSpellScript(spell_loken_pulsing_shockwave);
}
References RegisterHallOfLightningCreatureAI, and RegisterSpellScript.
Referenced by AddNorthrendScripts().
AddSC_boss_lord_marrowgar()
void AddSC_boss_lord_marrowgar ()
{
    RegisterIcecrownCitadelCreatureAI(boss_lord_marrowgar);
    new npc_coldflame();
    new npc_bone_spike();
    RegisterSpellScript(spell_marrowgar_coldflame);
    RegisterSpellScript(spell_marrowgar_coldflame_bonestorm);
    RegisterSpellScript(spell_marrowgar_bone_spike_graveyard);
    RegisterSpellScript(spell_marrowgar_bone_storm);
    RegisterSpellScript(spell_marrowgar_bone_slice);
}
References RegisterIcecrownCitadelCreatureAI, and RegisterSpellScript.
Referenced by AddNorthrendScripts().
AddSC_boss_maexxna()
void AddSC_boss_maexxna ()
{
    new boss_maexxna();
    new boss_maexxna_webwrap();
    RegisterSpellScript(spell_web_wrap_damage);
}
References RegisterSpellScript.
Referenced by AddNorthrendScripts().
AddSC_boss_magus_telestra()
void AddSC_boss_magus_telestra ()
{
    RegisterNexusCreatureAI(boss_magus_telestra);
    RegisterSpellScript(spell_boss_magus_telestra_summon_telestra_clones_aura);
    RegisterSpellScript(spell_boss_magus_telestra_gravity_well);
    new achievement_split_personality();
}
References RegisterNexusCreatureAI, and RegisterSpellScript.
Referenced by AddNorthrendScripts().
AddSC_boss_maiden_of_grief()
void AddSC_boss_maiden_of_grief ()
{
    new boss_maiden_of_grief();
}
Referenced by AddNorthrendScripts().
AddSC_boss_malygos()
void AddSC_boss_malygos ()
{
    new boss_malygos();
    new npc_power_spark();
    new npc_vortex_ride();
    new npc_alexstrasza();
    new go_the_focusing_iris();
    new npc_nexus_lord();
    new npc_scion_of_eternity();
    new npc_hover_disk();
    new npc_eoe_wyrmrest_skytalon();
    RegisterSpellScript(spell_eoe_ph3_surge_of_power);
}
References RegisterSpellScript.
Referenced by AddNorthrendScripts().
AddSC_boss_marwyn()
void AddSC_boss_marwyn ()
{
    new boss_marwyn();
    RegisterSpellScript(spell_hor_shared_suffering_aura);
}
References RegisterSpellScript.
Referenced by AddNorthrendScripts().
AddSC_boss_mimiron()
void AddSC_boss_mimiron ()
{
    new boss_mimiron();
    new npc_ulduar_leviathan_mkii();
    new npc_ulduar_vx001();
    new npc_ulduar_aerial_command_unit();
    new npc_ulduar_proximity_mine();
    new npc_ulduar_mimiron_rocket();
    new npc_ulduar_magnetic_core();
    new npc_ulduar_bot_summon_trigger();
    RegisterSpellScript(spell_mimiron_rapid_burst_aura);
    RegisterSpellScript(spell_mimiron_p3wx2_laser_barrage_aura);
    RegisterSpellScript(spell_ulduar_mimiron_mine_explosion);
    new go_ulduar_do_not_push_this_button();
    new npc_ulduar_flames_initial();
    new npc_ulduar_flames_spread();
    new npc_ulduar_emergency_fire_bot();
    new npc_ulduar_rocket_strike_trigger();
    new achievement_mimiron_firefighter();
    new achievement_mimiron_set_up_us_the_bomb_11();
    new achievement_mimiron_set_up_us_the_bomb_12();
    new achievement_mimiron_set_up_us_the_bomb_13();
}
References RegisterSpellScript.
Referenced by AddNorthrendScripts().
AddSC_boss_moorabi()
void AddSC_boss_moorabi ()
{
    new boss_moorabi();
    RegisterSpellScript(spell_moorabi_mojo_frenzy_aura);
    new achievement_less_rabi();
}
References RegisterSpellScript.
Referenced by AddNorthrendScripts().
AddSC_boss_moragg()
void AddSC_boss_moragg ()
{
    new boss_moragg();
    RegisterSpellScript(spell_optic_link_aura);
}
References RegisterSpellScript.
Referenced by AddNorthrendScripts().
AddSC_boss_northrend_beasts()
void AddSC_boss_northrend_beasts ()
{
    new boss_gormok();
    new npc_snobold_vassal();
    new boss_acidmaw();
    new boss_dreadscale();
    new boss_icehowl();
}
Referenced by AddNorthrendScripts().
AddSC_boss_noth()
void AddSC_boss_noth ()
{
    new boss_noth();
}
Referenced by AddNorthrendScripts().
AddSC_boss_novos()
void AddSC_boss_novos ()
{
    new boss_novos();
    RegisterSpellScript(spell_novos_despawn_crystal_handler);
    RegisterSpellScript(spell_novos_crystal_handler_death_aura);
    RegisterSpellScript(spell_novos_summon_minions);
    new achievement_oh_novos();
}
References RegisterSpellScript.
Referenced by AddNorthrendScripts().
AddSC_boss_ormorok()
void AddSC_boss_ormorok ()
{
    RegisterNexusCreatureAI(boss_ormorok);
    RegisterNexusCreatureAI(npc_crystal_spike);
}
References RegisterNexusCreatureAI.
Referenced by AddNorthrendScripts().
AddSC_boss_palehoof()
void AddSC_boss_palehoof ()
{
    new boss_palehoof();
    new npc_massive_jormungar();
    new npc_ferocious_rhino();
    new npc_ravenous_furbolg();
    new npc_frenzied_worgen();
    new go_palehoof_sphere();
}
Referenced by AddNorthrendScripts().
AddSC_boss_patchwerk()
void AddSC_boss_patchwerk ()
{
    new boss_patchwerk();
}
Referenced by AddNorthrendScripts().
AddSC_boss_professor_putricide()
void AddSC_boss_professor_putricide ()
{
    new boss_professor_putricide();
    new npc_volatile_ooze();
    new npc_gas_cloud();
    RegisterSpellScript(spell_putricide_slime_puddle);
    RegisterSpellScript(spell_putricide_slime_puddle_spawn);
    RegisterSpellScript(spell_putricide_grow_stacker_aura);
    RegisterSpellScript(spell_putricide_unstable_experiment);
    RegisterSpellScript(spell_putricide_tear_gas_effect);
    RegisterSpellScript(spell_putricide_gaseous_bloat_aura);
    RegisterSpellScript(spell_putricide_ooze_channel);
    RegisterSpellScript(spell_putricide_ooze_eruption_searcher);
    RegisterSpellScript(spell_putricide_mutated_plague_aura);
    RegisterSpellScript(spell_putricide_unbound_plague);
    RegisterSpellScript(spell_putricide_unbound_plague_dmg_aura);
    RegisterSpellScript(spell_putricide_choking_gas_bomb);
    RegisterSpellScript(spell_putricide_clear_aura_effect_value);
    RegisterSpellAndAuraScriptPair(spell_putricide_mutation_init, spell_putricide_mutation_init_aura);
    RegisterSpellScript(spell_putricide_mutated_transformation);
    RegisterSpellScript(spell_putricide_mutated_transformation_dismiss_aura);
    RegisterSpellScript(spell_putricide_mutated_transformation_dmg);
    RegisterSpellScript(spell_putricide_eat_ooze);
    RegisterSpellScript(spell_putricide_regurgitated_ooze);
}
References RegisterSpellAndAuraScriptPair, and RegisterSpellScript.
Referenced by AddNorthrendScripts().
AddSC_boss_razorscale()
void AddSC_boss_razorscale ()
{
    new boss_razorscale();
    new npc_ulduar_expedition_commander();
    new npc_ulduar_harpoonfirestate();
    new npc_ulduar_expedition_engineer();
    new go_ulduar_working_harpoon();
    new npc_ulduar_dark_rune_guardian();
    new npc_ulduar_dark_rune_watcher();
    new npc_ulduar_dark_rune_sentinel();
    new achievement_quick_shave();
    new achievement_iron_dwarf_medium_rare();
}
Referenced by AddNorthrendScripts().
AddSC_boss_razuvious()
void AddSC_boss_razuvious ()
{
    new boss_razuvious();
    new boss_razuvious_minion();
}
Referenced by AddNorthrendScripts().
AddSC_boss_rotface()
void AddSC_boss_rotface ()
{
    new boss_rotface();
    new npc_little_ooze();
    new npc_big_ooze();
    RegisterSpellAndAuraScriptPair(spell_rotface_mutated_infection, spell_rotface_mutated_infection_aura);
    RegisterSpellScript(spell_rotface_little_ooze_combine);
    RegisterSpellScript(spell_rotface_large_ooze_combine);
    RegisterSpellScript(spell_rotface_large_ooze_buff_combine);
    RegisterSpellScript(spell_rotface_unstable_ooze_explosion_init);
    RegisterSpellScript(spell_rotface_unstable_ooze_explosion);
    RegisterSpellScript(spell_rotface_unstable_ooze_explosion_suicide_aura);
    new npc_precious_icc();
}
References RegisterSpellAndAuraScriptPair, and RegisterSpellScript.
Referenced by AddNorthrendScripts().
AddSC_boss_sapphiron()
void AddSC_boss_sapphiron ()
{
    new boss_sapphiron();
    RegisterSpellScript(spell_sapphiron_frost_explosion);
}
References RegisterSpellScript.
Referenced by AddNorthrendScripts().
AddSC_boss_sartharion()
void AddSC_boss_sartharion ()
{
    new boss_sartharion();
    new boss_sartharion_shadron();
    new boss_sartharion_tenebron();
    new boss_sartharion_vesperon();
    new npc_twilight_summon();
    RegisterSpellScript(spell_sartharion_lava_strike);
    RegisterSpellScript(spell_obsidian_sanctum_flame_tsunami);
    RegisterSpellScript(spell_obsidian_sanctum_flame_tsunami_leap);
}
References RegisterSpellScript.
Referenced by AddNorthrendScripts().
AddSC_boss_saviana_ragefire()
void AddSC_boss_saviana_ragefire ()
{
    new boss_saviana_ragefire();
    RegisterSpellScript(spell_saviana_conflagration_init);
    RegisterSpellScript(spell_saviana_conflagration_throwback);
}
References RegisterSpellScript.
Referenced by AddNorthrendScripts().
AddSC_boss_sindragosa()
void AddSC_boss_sindragosa ()
{
    new boss_sindragosa();
    new npc_ice_tomb();
    RegisterSpellScript(spell_sindragosa_s_fury);
    RegisterSpellScript(spell_sindragosa_unchained_magic);
    RegisterSpellScript(spell_sindragosa_permeating_chill_aura);
    RegisterSpellScript(spell_sindragosa_instability_aura);
    RegisterSpellScript(spell_sindragosa_icy_grip);
    RegisterSpellScript(spell_sindragosa_icy_grip_jump);
    RegisterSpellScript(spell_sindragosa_ice_tomb_filter);
    RegisterSpellScriptWithArgs(spell_trigger_spell_from_caster, "spell_sindragosa_ice_tomb", SPELL_ICE_TOMB_DUMMY);
    RegisterSpellScriptWithArgs(spell_trigger_spell_from_caster, "spell_sindragosa_ice_tomb_dummy", SPELL_FROST_BEACON);
    RegisterSpellScript(spell_sindragosa_frost_beacon_aura);
    RegisterSpellAndAuraScriptPair(spell_sindragosa_ice_tomb_trap, spell_sindragosa_ice_tomb_trap_aura);
    RegisterSpellScript(spell_sindragosa_mystic_buffet);
    RegisterSpellScript(spell_sindragosa_soul_preservation_aura);
    new achievement_all_you_can_eat();
    new npc_spinestalker();
    new npc_rimefang();
    RegisterSpellScript(spell_rimefang_icy_blast);
    new at_sindragosa_lair();
    new npc_sindragosa_trash();
    RegisterSpellScript(spell_frostwarden_handler_order_whelp);
    RegisterSpellAndAuraScriptPair(spell_frostwarden_handler_focus_fire, spell_frostwarden_handler_focus_fire_aura);
    RegisterSpellScript(spell_sindragosa_frost_breath);
}
References RegisterSpellAndAuraScriptPair, RegisterSpellScript, RegisterSpellScriptWithArgs, SPELL_FROST_BEACON, and SPELL_ICE_TOMB_DUMMY.
Referenced by AddNorthrendScripts().
AddSC_boss_sjonnir()
void AddSC_boss_sjonnir ()
{
    new boss_sjonnir();
    new boss_sjonnir_dwarf();
    new boss_sjonnir_malformed_ooze();
    new boss_sjonnir_iron_sludge();
}
Referenced by AddNorthrendScripts().
AddSC_boss_skadi()
void AddSC_boss_skadi ()
{
    new boss_skadi();
    new boss_skadi_grauf();
    new go_harpoon_canon();
}
Referenced by AddNorthrendScripts().
AddSC_boss_skarvald_dalronn()
void AddSC_boss_skarvald_dalronn ()
{
    RegisterUtgardeKeepCreatureAI(boss_skarvald_the_constructor);
    RegisterUtgardeKeepCreatureAI(boss_dalronn_the_controller);
}
References RegisterUtgardeKeepCreatureAI.
Referenced by AddNorthrendScripts().
AddSC_boss_slad_ran()
void AddSC_boss_slad_ran ()
{
    new boss_slad_ran();
    RegisterSpellScript(spell_sladran_grip_of_sladran_aura);
    new achievement_snakes_whyd_it_have_to_be_snakes();
}
References RegisterSpellScript.
Referenced by AddNorthrendScripts().
AddSC_boss_svala()
void AddSC_boss_svala ()
{
    new boss_svala();
    new npc_ritual_channeler();
    RegisterSpellAndAuraScriptPair(spell_svala_ritual_strike, spell_svala_ritual_strike_aura);
}
References RegisterSpellAndAuraScriptPair.
Referenced by AddNorthrendScripts().
AddSC_boss_taldaram()
void AddSC_boss_taldaram ()
{
    RegisterAhnKahetCreatureAI(npc_taldaram_flamesphere);
    RegisterAhnKahetCreatureAI(boss_taldaram);
    // Spells
    RegisterSpellScript(spell_prince_taldaram_conjure_flame_sphere);
    RegisterSpellScript(spell_prince_taldaram_flame_sphere_summon);
}
References RegisterAhnKahetCreatureAI, and RegisterSpellScript.
Referenced by AddNorthrendScripts().
AddSC_boss_thaddius()
void AddSC_boss_thaddius ()
{
    new boss_thaddius();
    new boss_thaddius_summon();
    new npc_tesla();
    RegisterSpellScript(spell_thaddius_pos_neg_charge);
    RegisterSpellScript(spell_thaddius_polarity_shift);
    new at_thaddius_entrance();
}
References RegisterSpellScript.
Referenced by AddNorthrendScripts().
AddSC_boss_tharon_ja()
void AddSC_boss_tharon_ja ()
{
    new boss_tharon_ja();
    RegisterSpellScript(spell_tharon_ja_curse_of_life_aura);
    RegisterSpellScript(spell_tharon_ja_dummy_aura);
    RegisterSpellScript(spell_tharon_ja_clear_gift_of_tharon_ja);
}
References RegisterSpellScript.
Referenced by AddNorthrendScripts().
AddSC_boss_the_lich_king()
void AddSC_boss_the_lich_king ()
{
    new boss_the_lich_king();
    new npc_tirion_fordring_tft();
    RegisterSpellScript(spell_the_lich_king_quake);
    RegisterSpellScript(spell_the_lich_king_jump);
    RegisterSpellScript(spell_the_lich_king_jump_remove_aura);
    RegisterSpellScriptWithArgs(spell_trigger_spell_from_caster, "spell_the_lich_king_mass_resurrection", SPELL_MASS_RESURRECTION_REAL);
    RegisterSpellScript(spell_the_lich_king_play_movie);
    // fight stuff below
    new npc_shambling_horror_icc();
    RegisterSpellScript(spell_the_lich_king_infest_aura);
    RegisterSpellScript(spell_the_lich_king_necrotic_plague_aura);
    RegisterSpellAndAuraScriptPair(spell_the_lich_king_necrotic_plague_jump, spell_the_lich_king_necrotic_plague_jump_aura);
    RegisterSpellScript(spell_the_lich_king_shadow_trap_visual_aura);
    RegisterSpellScript(spell_the_lich_king_shadow_trap_periodic);
    RegisterSpellScript(spell_the_lich_king_ice_burst_target_search);
    new npc_icc_ice_sphere();
    RegisterSpellScript(spell_the_lich_king_raging_spirit);
    new npc_raging_spirit();
    RegisterSpellScript(spell_the_lich_king_defile);
    RegisterSpellScript(spell_the_lich_king_soul_reaper_aura);
    new npc_valkyr_shadowguard();
    RegisterSpellScript(spell_the_lich_king_summon_into_air);
    RegisterSpellScript(spell_the_lich_king_teleport_to_frostmourne_hc);
    RegisterSpellScript(spell_the_lich_king_valkyr_target_search);
    RegisterSpellScript(spell_the_lich_king_cast_back_to_caster);
    RegisterSpellScript(spell_the_lich_king_life_siphon);
    RegisterSpellScript(spell_the_lich_king_vile_spirits_aura);
    RegisterSpellScript(spell_the_lich_king_vile_spirits_visual);
    RegisterSpellScript(spell_the_lich_king_vile_spirit_move_target_search);
    RegisterSpellScript(spell_the_lich_king_vile_spirit_damage_target_search);
    RegisterSpellScript(spell_the_lich_king_harvest_soul_aura);
    new npc_strangulate_vehicle();
    new npc_terenas_menethil();
    RegisterSpellScript(spell_the_lich_king_lights_favor_aura);
    RegisterSpellScript(spell_the_lich_king_restore_soul);
    new npc_spirit_warden();
    RegisterSpellScript(spell_the_lich_king_dark_hunger_aura);
    RegisterSpellScript(spell_the_lich_king_soul_rip_aura);
    new npc_icc_lk_checktarget();
    RegisterSpellScript(spell_the_lich_king_summon_spirit_bomb);
    new npc_lk_spirit_bomb();
    RegisterSpellScript(spell_the_lich_king_trigger_vile_spirit);
    new npc_lk_wicked_spirit();
    new achievement_been_waiting_long_time();
    new achievement_neck_deep_in_vile();
}
References RegisterSpellAndAuraScriptPair, RegisterSpellScript, RegisterSpellScriptWithArgs, and SPELL_MASS_RESURRECTION_REAL.
Referenced by AddNorthrendScripts().
AddSC_boss_thorim()
void AddSC_boss_thorim ()
{
    // Main encounter
    new boss_thorim();
    new boss_thorim_sif();
    new boss_thorim_lightning_orb();
    new boss_thorim_trap();
    new boss_thorim_pillar();
    new boss_thorim_sif_blizzard();
    // Trash
    new boss_thorim_start_npcs();
    new boss_thorim_gauntlet_npcs();
    new boss_thorim_arena_npcs();
    // Mini bosses
    new boss_thorim_runic_colossus();
    new boss_thorim_ancient_rune_giant();
    // GOs
    new go_thorim_lever();
    // Spells
    RegisterSpellScript(spell_thorim_lightning_pillar_P2_aura);
    RegisterSpellScript(spell_thorim_trash_impale_aura);
    // Achievements
    new achievement_thorim_stand_in_the_lightning();
    new achievement_thorim_lose_your_illusion();
}
References RegisterSpellScript.
Referenced by AddNorthrendScripts().
AddSC_boss_toravon()
void AddSC_boss_toravon ()
{
    new boss_toravon();
    new npc_frozen_orb();
    new npc_frozen_orb_stalker();
}
Referenced by AddNorthrendScripts().
AddSC_boss_trollgore()
void AddSC_boss_trollgore ()
{
    new boss_trollgore();
    RegisterSpellScript(spell_trollgore_consume);
    RegisterSpellScript(spell_trollgore_corpse_explode_aura);
    RegisterSpellScript(spell_trollgore_invader_taunt);
    new achievement_consumption_junction();
}
References RegisterSpellScript.
Referenced by AddNorthrendScripts().
AddSC_boss_twin_valkyr()
void AddSC_boss_twin_valkyr ()
{
    new boss_fjola();
    new boss_eydis();
    new npc_essence_of_twin();
    new npc_concentrated_ball();
    RegisterSpellScript(spell_valkyr_essence_aura);
    RegisterSpellScript(spell_valkyr_touch_aura);
    RegisterSpellScript(spell_valkyr_ball_periodic_dummy_aura);
}
References RegisterSpellScript.
Referenced by AddNorthrendScripts().
AddSC_boss_tyrannus()
void AddSC_boss_tyrannus ()
{
    new boss_tyrannus();
}
Referenced by AddNorthrendScripts().
AddSC_boss_urom()
void AddSC_boss_urom ()
{
    new boss_urom();
}
Referenced by AddNorthrendScripts().
AddSC_boss_valithria_dreamwalker()
void AddSC_boss_valithria_dreamwalker ()
{
    new boss_valithria_dreamwalker();
    new npc_green_dragon_combat_trigger();
    new npc_the_lich_king_controller();
    new npc_risen_archmage();
    new npc_valithria_portal();
    new npc_valithria_cloud();
    new npc_blazing_skeleton();
    new npc_suppresser();
    new npc_blistering_zombie();
    new npc_gluttonous_abomination();
    RegisterSpellScript(spell_dreamwalker_summon_portal);
    RegisterSpellScript(spell_dreamwalker_twisted_nightmares);
    RegisterSpellScript(spell_dreamwalker_nightmare_cloud_aura);
    RegisterSpellScript(spell_dreamwalker_mana_void_aura);
    RegisterSpellScript(spell_dreamwalker_decay_periodic_timer_aura);
    RegisterSpellScript(spell_dreamwalker_summoner);
    RegisterSpellScript(spell_dreamwalker_summon_suppresser_aura);
    RegisterSpellScript(spell_dreamwalker_summon_suppresser_effect);
    RegisterSpellScript(spell_valithria_suppression_aura);
    new achievement_portal_jockey();
}
References RegisterSpellScript.
Referenced by AddNorthrendScripts().
AddSC_boss_varos()
void AddSC_boss_varos ()
{
    new boss_varos();
}
Referenced by AddNorthrendScripts().
AddSC_boss_vezax()
void AddSC_boss_vezax ()
{
    new boss_vezax();
    new npc_ulduar_saronite_vapors();
    new npc_ulduar_saronite_animus();
    RegisterSpellScript(spell_aura_of_despair_aura);
    RegisterSpellScript(spell_mark_of_the_faceless_periodic_aura);
    RegisterSpellScript(spell_mark_of_the_faceless_drainhealth);
    RegisterSpellScript(spell_saronite_vapors_dummy_aura);
    RegisterSpellScript(spell_saronite_vapors_damage);
    new achievement_smell_saronite();
    new achievement_shadowdodger();
    new go_ulduar_pure_saronite_deposit();
}
References RegisterSpellScript.
Referenced by AddNorthrendScripts().
AddSC_boss_volazj()
void AddSC_boss_volazj ()
{
    RegisterAhnKahetCreatureAI(boss_volazj);
    RegisterSpellScript(spell_herald_volzaj_insanity);
    RegisterSpellScript(spell_volazj_whisper);
}
References RegisterAhnKahetCreatureAI, and RegisterSpellScript.
Referenced by AddNorthrendScripts().
AddSC_boss_volkhan()
void AddSC_boss_volkhan ()
{
    RegisterHallOfLightningCreatureAI(boss_volkhan);
    RegisterHallOfLightningCreatureAI(npc_molten_golem);
}
References RegisterHallOfLightningCreatureAI.
Referenced by AddNorthrendScripts().
AddSC_boss_xevozz()
void AddSC_boss_xevozz ()
{
    new boss_xevozz();
}
Referenced by AddNorthrendScripts().
AddSC_boss_xt002()
void AddSC_boss_xt002 ()
{
    // Npcs
    new boss_xt002();
    new npc_xt002_heart();
    new npc_xt002_scrapbot();
    new npc_xt002_pummeller();
    new npc_xt002_boombot();
    new npc_xt002_life_spark();
    // Spells
    RegisterSpellScript(spell_xt002_tympanic_tantrum);
    RegisterSpellAndAuraScriptPair(spell_xt002_gravity_bomb, spell_xt002_gravity_bomb_aura);
    RegisterSpellScript(spell_xt002_gravity_bomb_damage);
    RegisterSpellAndAuraScriptPair(spell_xt002_searing_light_spawn_life_spark, spell_xt002_searing_light_spawn_life_spark_aura);
    // Achievements
    new achievement_xt002_nerf_engineering();
    new achievement_xt002_nerf_gravity_bombs();
}
References RegisterSpellAndAuraScriptPair, and RegisterSpellScript.
Referenced by AddNorthrendScripts().
AddSC_boss_ymiron()
void AddSC_boss_ymiron ()
{
    new boss_ymiron();
}
Referenced by AddNorthrendScripts().
AddSC_boss_yoggsaron()
void AddSC_boss_yoggsaron ()
{
    new boss_yoggsaron();
    new boss_yoggsaron_sara();
    new boss_yoggsaron_cloud();
    new boss_yoggsaron_guardian_of_ys();
    new boss_yoggsaron_brain();
    new boss_yoggsaron_death_orb();
    new boss_yoggsaron_crusher_tentacle();
    new boss_yoggsaron_corruptor_tentacle();
    new boss_yoggsaron_constrictor_tentacle();
    RegisterUlduarCreatureAI(boss_yoggsaron_keeper);
    new boss_yoggsaron_descend_portal();
    new boss_yoggsaron_influence_tentacle();
    new boss_yoggsaron_immortal_guardian();
    new boss_yoggsaron_lich_king();
    new boss_yoggsaron_llane();
    new boss_yoggsaron_neltharion();
    new boss_yoggsaron_voice();
    // SPELLS
    RegisterSpellScript(spell_yogg_saron_malady_of_the_mind_aura);
    RegisterSpellAndAuraScriptPair(spell_yogg_saron_brain_link, spell_yogg_saron_brain_link_aura);
    RegisterSpellScript(spell_yogg_saron_shadow_beacon_aura);
    RegisterSpellScript(spell_yogg_saron_destabilization_matrix);
    RegisterSpellScript(spell_yogg_saron_titanic_storm);
    RegisterSpellScript(spell_yogg_saron_lunatic_gaze);
    RegisterSpellScript(spell_yogg_saron_protective_gaze_aura);
    RegisterSpellScript(spell_yogg_saron_empowered_aura);
    RegisterSpellScript(spell_yogg_saron_insane_periodic_trigger);
    RegisterSpellScript(spell_yogg_saron_insane_aura);
    RegisterSpellScript(spell_yogg_saron_sanity_well_aura);
    RegisterSpellScript(spell_keeper_freya_summon_sanity_well);
    RegisterSpellScript(spell_yogg_saron_sanity_reduce);
    RegisterSpellScript(spell_yogg_saron_empowering_shadows);
    RegisterSpellScript(spell_yogg_saron_in_the_maws_of_the_old_god);
    RegisterSpellScript(spell_yogg_saron_target_selectors);
    RegisterSpellScript(spell_yogg_saron_grim_reprisal_aura);
    // ACHIEVEMENTS
    new achievement_yogg_saron_drive_me_crazy();
    new achievement_yogg_saron_darkness("achievement_yogg_saron_three_lights_in_the_darkness", 3);
    new achievement_yogg_saron_darkness("achievement_yogg_saron_two_lights_in_the_darkness", 2);
    new achievement_yogg_saron_darkness("achievement_yogg_saron_one_light_in_the_darkness", 1);
    new achievement_yogg_saron_darkness("achievement_yogg_saron_alone_in_the_darkness", 0);
    new achievement_yogg_saron_he_waits_dreaming("achievement_yogg_saron_he_waits_dreaming_stormwind", ACTION_ILLUSION_STORMWIND);
    new achievement_yogg_saron_he_waits_dreaming("achievement_yogg_saron_he_waits_dreaming_chamber", ACTION_ILLUSION_DRAGONS);
    new achievement_yogg_saron_he_waits_dreaming("achievement_yogg_saron_he_waits_dreaming_icecrown", ACTION_ILLUSION_ICECROWN);
    new achievement_yogg_saron_kiss_and_make_up();
}
References ACTION_ILLUSION_DRAGONS, ACTION_ILLUSION_ICECROWN, ACTION_ILLUSION_STORMWIND, RegisterSpellAndAuraScriptPair, RegisterSpellScript, and RegisterUlduarCreatureAI.
Referenced by AddNorthrendScripts().
AddSC_boss_zuramat()
void AddSC_boss_zuramat ()
{
    new boss_zuramat();
    new npc_vh_void_sentry();
}
Referenced by AddNorthrendScripts().
AddSC_brann_bronzebeard()
void AddSC_brann_bronzebeard ()
{
    new brann_bronzebeard();
    new dark_rune_protectors();
    new dark_rune_stormcaller();
    new iron_golem_custodian();
    RegisterSpellScript(spell_hos_dark_matter);
    RegisterSpellScript(spell_hos_dark_matter_size);
}
References brann_bronzebeard::brann_bronzebeard(), and RegisterSpellScript.
Referenced by AddNorthrendScripts().
AddSC_crystalsong_forest()
void AddSC_crystalsong_forest ()
{
    RegisterCreatureAI(npc_preparations_for_war_vehicle);
    RegisterCreatureAI(npc_warmage_violetstand);
}
References RegisterCreatureAI.
Referenced by AddNorthrendScripts().
AddSC_dalaran()
void AddSC_dalaran ()
{
    // our
    new npc_steam_powered_auctioneer();
    new npc_mei_francis_mount();
    new npc_shandy_dalaran();
    new npc_archmage_landalock();
    new npc_dalaran_mage();
    new npc_dalaran_warrior();
    RegisterCreatureAI(npc_cosmetic_toy_plane);
    new npc_mageguard_dalaran();
    RegisterCreatureAI(npc_minigob_manabonk);
}
References RegisterCreatureAI.
Referenced by AddNorthrendScripts().
AddSC_dragonblight()
void AddSC_dragonblight ()
{
    new npc_conversing_with_the_depths_trigger();
    new go_the_pearl_of_the_depths();
    new npc_hourglass_of_eternity();
    new npc_future_you();
    new npc_mindless_ghoul();
    new npc_injured_7th_legion_soldier();
    RegisterCreatureAI(npc_wintergarde_gryphon);
    RegisterSpellScript(spell_q12237_rescue_villager);
    RegisterSpellScript(spell_q12237_drop_off_villager);
    RegisterSpellScript(spell_call_wintergarde_gryphon);
    new npc_heated_battle();
    RegisterSpellScript(spell_q12478_frostmourne_cavern);
    RegisterSpellScript(spell_q12243_fire_upon_the_waters_aura);
    new npc_q24545_lich_king();
    new at_q24545_frostmourne_cavern();
    new npc_q24545_wretched_ghoul();
    RegisterSpellScript(spell_q24545_aod_special);
    new npc_q24545_vegard_dummy();
    new npc_q24545_vegard();
    new npc_spiritual_insight();
    new npc_commander_eligor_dawnbringer();
    RegisterSpellScript(spell_q12096_q12092_dummy);
    new npc_torturer_lecraft();
    RegisterSpellScript(spell_dragonblight_corrosive_spit);
    RegisterSpellScript(spell_handover_reins);
    RegisterSpellScript(spell_dragonblight_flame_fury);
    RegisterSpellScript(spell_dragonblight_devour_ghoul);
    RegisterSpellScript(spell_dragonblight_devour_ghoul_periodic);
}
References RegisterCreatureAI, and RegisterSpellScript.
Referenced by AddNorthrendScripts().
AddSC_forge_of_souls()
void AddSC_forge_of_souls ()
{
    new npc_fos_leader();
    new npc_fos_leader_second();
    RegisterSpellScript(spell_shield_of_bones_aura);
}
References RegisterSpellScript.
Referenced by AddNorthrendScripts().
AddSC_grizzly_hills()
void AddSC_grizzly_hills ()
{
    new npc_emily();
    new npc_mrfloppy();
    new npc_ravenous_worg();
    new npc_tallhorn_stag();
    new npc_amberpine_woodsman();
    RegisterCreatureAI(npc_wounded_skirmisher);
    RegisterSpellScript(spell_renew_skirmisher);
    new npc_venture_co_straggler();
    new npc_lake_frog();
    RegisterSpellScript(spell_shredder_delivery);
    RegisterSpellScript(spell_infected_worgen_bite_aura);
    RegisterSpellScript(spell_z_check_aura);
    RegisterSpellScript(spell_warhead_detonate);
    RegisterSpellScript(spell_vehicle_warhead_fuse);
    RegisterSpellScript(spell_warhead_fuse_aura);
    RegisterSpellScript(spell_q12227_outhouse_groans);
    RegisterSpellScript(spell_q12227_camera_shake);
    RegisterSpellScript(spell_frog_kiss);
}
References RegisterCreatureAI, and RegisterSpellScript.
Referenced by AddNorthrendScripts().
AddSC_halls_of_reflection()
void AddSC_halls_of_reflection ()
{
    new npc_hor_leader();
    new npc_ghostly_priest();
    new npc_phantom_mage();
    new npc_phantom_hallucination();
    new npc_shadowy_mercenary();
    new npc_spectral_footman();
    new npc_tortured_rifleman();
    new boss_frostsworn_general();
    new npc_hor_spiritual_reflection();
    new at_hor_shadow_throne();
    new npc_hor_lich_king();
    new npc_hor_leader_second();
    new npc_hor_raging_ghoul();
    new npc_hor_risen_witch_doctor();
    new npc_hor_lumbering_abomination();
    RegisterSpellScript(spell_hor_gunship_cannon_fire_aura);
    new at_hor_battered_hilt_start();
    new at_hor_battered_hilt_throw();
}
References RegisterSpellScript.
Referenced by AddNorthrendScripts().
AddSC_howling_fjord()
void AddSC_howling_fjord ()
{
    new npc_attracted_reef_bull();
    new npc_your_inner_turmoil();
    new npc_apothecary_hanes();
    new npc_plaguehound_tracker();
    new npc_razael_and_lyana();
    RegisterCreatureAI(npc_rodin_lightning_enabler);
    RegisterSpellScript(spell_hawk_hunting);
}
References RegisterCreatureAI, and RegisterSpellScript.
Referenced by AddNorthrendScripts().
AddSC_icecrown()
void AddSC_icecrown ()
{
    new npc_black_knight_graveyard();
    new npc_battle_at_valhalas();
    new npc_llod_generic();
    new npc_lord_arete();
    new npc_boneguard_footman();
    new npc_tirions_gambit_tirion();
    RegisterSpellScript(spell_switch_infragreen_bomber_station);
    RegisterSpellAndAuraScriptPair(spell_charge_shield_bomber, spell_charge_shield_bomber_aura);
    RegisterSpellScript(spell_fight_fire_bomber);
    RegisterSpellScript(spell_anti_air_rocket_bomber);
    new npc_infra_green_bomber_generic();
    RegisterSpellScript(spell_onslaught_or_call_bone_gryphon);
    RegisterSpellScript(spell_deliver_gryphon);
    new npc_guardian_pavilion();
    new npc_tournament_training_dummy();
    new npc_blessed_banner();
    new npc_frostbrood_skytalon();
    RegisterSpellScript(spell_crashing_wave);
}
References RegisterSpellAndAuraScriptPair, and RegisterSpellScript.
Referenced by AddNorthrendScripts().
AddSC_icecrown_citadel()
void AddSC_icecrown_citadel ()
{
    new npc_highlord_tirion_fordring_lh();
    new npc_rotting_frost_giant();
    new npc_frost_freeze_trap();
    new npc_alchemist_adrianna();
    new boss_sister_svalna();
    new npc_crok_scourgebane();
    new npc_captain_arnath();
    new npc_captain_brandon();
    new npc_captain_grondel();
    new npc_captain_rupert();
    new npc_frostwing_vrykul();
    new npc_impaling_spear();
    new npc_arthas_teleport_visual();
    RegisterSpellScript(spell_icc_stoneform_aura);
    RegisterSpellScript(spell_icc_sprit_alarm);
    RegisterSpellScript(spell_icc_geist_alarm);
    RegisterSpellScript(spell_frost_giant_death_plague);
    RegisterSpellScript(spell_icc_harvest_blight_specimen);
    RegisterSpellScriptWithArgs(spell_trigger_spell_from_caster, "spell_svalna_caress_of_death", SPELL_IMPALING_SPEAR_KILL);
    RegisterSpellScript(spell_svalna_revive_champion);
    RegisterSpellScript(spell_svalna_remove_spear);
    RegisterSpellScript(spell_icc_soul_missile);
    new at_icc_saurfang_portal();
    new at_icc_shutdown_traps();
    new at_icc_start_blood_quickening();
    new at_icc_start_frostwing_gauntlet();
    // pussywizard below:
    RegisterSpellScript(spell_icc_web_wrap_aura);
    RegisterSpellScript(spell_icc_dark_reckoning_aura);
    RegisterSpellScript(spell_stinky_precious_decimate);
    RegisterSpellScript(spell_icc_yf_frozen_orb_aura);
    RegisterSpellScript(spell_icc_yh_volley_aura);
    RegisterSpellScript(spell_icc_yd_summon_undead);
    RegisterSpellScript(spell_icc_shattered_bones);
    new npc_icc_skybreaker_hierophant();
    new npc_icc_skybreaker_marksman();
    new npc_icc_skybreaker_vicar();
    new npc_icc_skybreaker_luminary();
    new npc_icc_valkyr_herald();
    new npc_icc_severed_essence();
    RegisterIcecrownCitadelCreatureAI(npc_icc_spire_frostwyrm);
    new npc_icc_vengeful_fleshreaper();
    new npc_icc_buff_switcher();
    new npc_icc_nerubar_broodkeeper();
    new npc_icc_gauntlet_controller();
    new npc_icc_putricades_trap();
    new at_icc_gauntlet_event();
    new at_icc_putricide_trap();
    new at_icc_spire_frostwyrm();
}
References RegisterIcecrownCitadelCreatureAI, RegisterSpellScript, RegisterSpellScriptWithArgs, and SPELL_IMPALING_SPEAR_KILL.
Referenced by AddNorthrendScripts().
AddSC_icecrown_citadel_teleport()
void AddSC_icecrown_citadel_teleport ()
{
    new icecrown_citadel_teleport();
    new at_frozen_throne_teleport();
}
Referenced by AddNorthrendScripts().
AddSC_instance_ahnkahet()
void AddSC_instance_ahnkahet ()
{
    new instance_ahnkahet;
    RegisterSpellScript(spell_shadow_sickle_periodic_damage);
}
References RegisterSpellScript.
Referenced by AddNorthrendScripts().
AddSC_instance_azjol_nerub()
void AddSC_instance_azjol_nerub ()
{
    new instance_azjol_nerub();
    RegisterSpellScript(spell_azjol_nerub_fixate);
    RegisterSpellScript(spell_azjol_nerub_web_wrap_aura);
    RegisterSpellScript(spell_azjol_drain_power);
}
References RegisterSpellScript.
Referenced by AddNorthrendScripts().
AddSC_instance_drak_tharon_keep()
void AddSC_instance_drak_tharon_keep ()
{
    new instance_drak_tharon_keep();
    RegisterSpellScript(spell_dtk_raise_dead_aura);
    RegisterSpellScript(spell_dtk_summon_random_drakkari);
}
References RegisterSpellScript.
Referenced by AddNorthrendScripts().
AddSC_instance_eye_of_eternity()
void AddSC_instance_eye_of_eternity ()
{
    new instance_eye_of_eternity();
}
Referenced by AddNorthrendScripts().
AddSC_instance_forge_of_souls()
void AddSC_instance_forge_of_souls ()
{
    new instance_forge_of_souls();
}
Referenced by AddNorthrendScripts().
AddSC_instance_gundrak()
void AddSC_instance_gundrak ()
{
    new instance_gundrak();
}
Referenced by AddNorthrendScripts().
AddSC_instance_halls_of_lightning()
void AddSC_instance_halls_of_lightning ()
{
    new instance_halls_of_lightning();
    new at_hol_hall_of_watchers();
}
Referenced by AddNorthrendScripts().
AddSC_instance_halls_of_reflection()
void AddSC_instance_halls_of_reflection ()
{
    new instance_halls_of_reflection();
}
Referenced by AddNorthrendScripts().
AddSC_instance_halls_of_stone()
void AddSC_instance_halls_of_stone ()
{
    new instance_halls_of_stone();
}
Referenced by AddNorthrendScripts().
AddSC_instance_icecrown_citadel()
void AddSC_instance_icecrown_citadel ()
{
    new instance_icecrown_citadel();
}
Referenced by AddNorthrendScripts().
AddSC_instance_naxxramas()
void AddSC_instance_naxxramas ()
{
    RegisterInstanceScript(instance_naxxramas, MAP_NAXXRAMAS);
    RegisterNaxxramasCreatureAI(npc_mr_bigglesworth);
    RegisterNaxxramasCreatureAI(npc_living_poison);
    RegisterNaxxramasCreatureAI(npc_naxxramas_trigger);
    new at_naxxramas_hub_portal();
}
References MAP_NAXXRAMAS, RegisterInstanceScript, and RegisterNaxxramasCreatureAI.
Referenced by AddNorthrendScripts().
AddSC_instance_nexus()
void AddSC_instance_nexus ()
{
    new instance_nexus();
    RegisterNexusCreatureAI(npc_crystalline_frayer);
}
References RegisterNexusCreatureAI.
Referenced by AddNorthrendScripts().
AddSC_instance_obsidian_sanctum()
void AddSC_instance_obsidian_sanctum ()
{
    new instance_obsidian_sanctum();
}
Referenced by AddNorthrendScripts().
AddSC_instance_oculus()
void AddSC_instance_oculus ()
{
    new instance_oculus();
}
Referenced by AddNorthrendScripts().
AddSC_instance_pit_of_saron()
void AddSC_instance_pit_of_saron ()
{
    new instance_pit_of_saron();
}
Referenced by AddNorthrendScripts().
AddSC_instance_ruby_sanctum()
void AddSC_instance_ruby_sanctum ()
{
    new instance_ruby_sanctum();
    RegisterSpellScript(spell_ruby_sanctum_rallying_shout);
}
References RegisterSpellScript.
Referenced by AddNorthrendScripts().
AddSC_instance_trial_of_the_champion()
void AddSC_instance_trial_of_the_champion ()
{
    new instance_trial_of_the_champion();
}
Referenced by AddNorthrendScripts().
AddSC_instance_trial_of_the_crusader()
void AddSC_instance_trial_of_the_crusader ()
{
    new instance_trial_of_the_crusader();
}
Referenced by AddNorthrendScripts().
AddSC_instance_ulduar()
void AddSC_instance_ulduar ()
{
    new instance_ulduar();
}
References instance_ulduar::instance_ulduar().
Referenced by AddNorthrendScripts().
AddSC_instance_utgarde_keep()
void AddSC_instance_utgarde_keep ()
{
    new instance_utgarde_keep();
}
Referenced by AddNorthrendScripts().
AddSC_instance_utgarde_pinnacle()
void AddSC_instance_utgarde_pinnacle ()
{
    new instance_utgarde_pinnacle();
}
Referenced by AddNorthrendScripts().
AddSC_instance_vault_of_archavon()
void AddSC_instance_vault_of_archavon ()
{
    new instance_vault_of_archavon();
}
Referenced by AddNorthrendScripts().
AddSC_instance_violet_hold()
void AddSC_instance_violet_hold ()
{
    new instance_violet_hold();
}
Referenced by AddNorthrendScripts().
AddSC_isle_of_conquest()
void AddSC_isle_of_conquest ()
{
    new npc_isle_of_conquest_turret();
    new npc_four_car_garage();
    new npc_ioc_gunship_captain();
    new boss_isle_of_conquest();
    RegisterSpellScript(spell_ioc_repair_turret_aura);
    RegisterSpellScript(spell_ioc_bomb_blast_criteria);
    RegisterSpellScript(spell_ioc_gunship_portal);
    RegisterSpellScript(spell_ioc_parachute_ic_aura);
    RegisterSpellScript(spell_ioc_launch);
}
References RegisterSpellScript.
Referenced by AddNorthrendScripts().
AddSC_oculus()
void AddSC_oculus ()
{
    new npc_oculus_drakegiver();
    new npc_oculus_drake();
    new npc_centrifuge_construct();
    RegisterSpellScript(spell_oculus_stop_time_aura);
    RegisterSpellScript(spell_oculus_evasive_maneuvers_aura);
    RegisterSpellScript(spell_oculus_shock_lance);
    RegisterSpellScript(spell_oculus_temporal_rift_aura);
    RegisterSpellScript(spell_oculus_touch_the_nightmare);
    RegisterSpellScript(spell_oculus_dream_funnel_aura);
    RegisterSpellScript(spell_oculus_call_ruby_emerald_amber_drake);
    RegisterSpellScript(spell_oculus_ride_ruby_emerald_amber_drake_que_aura);
    RegisterSpellScript(spell_oculus_evasive_charges_aura);
    RegisterSpellScript(spell_oculus_soar_aura);
    RegisterSpellScript(spell_oculus_rider_aura);
    RegisterSpellScript(spell_oculus_drake_flag_aura);
}
References RegisterSpellScript.
Referenced by AddNorthrendScripts().
AddSC_pit_of_saron()
void AddSC_pit_of_saron ()
{
    new npc_pos_leader();
    new npc_pos_deathwhisper_necrolyte();
    new npc_pos_after_first_boss();
    new npc_pos_tyrannus_events();
    new npc_pos_icicle_trigger();
    new npc_pos_collapsing_icicle();
    new npc_pos_martin_or_gorkun_second();
    new npc_pos_freed_slave();
    new npc_pos_leader_second();
    RegisterSpellScript(spell_pos_empowered_blizzard_aura);
    RegisterSpellScript(spell_pos_slave_trigger_closest);
    RegisterSpellScript(spell_pos_rimefang_frost_nova);
    RegisterSpellScript(spell_pos_blight_aura);
    RegisterSpellScript(spell_pos_glacial_strike_aura);
    new at_tyrannus_event_starter();
}
References RegisterSpellScript.
Referenced by AddNorthrendScripts().
AddSC_sholazar_basin()
void AddSC_sholazar_basin ()
{
    RegisterSpellScript(spell_q12726_song_of_wind_and_water);
    new npc_still_at_it_trigger();
    new npc_mcmanus();
    new go_pressure_valve();
    new go_brazier();
    new npc_vekjik();
    new npc_avatar_of_freya();
    new npc_bushwhacker();
    new npc_engineer_helice();
    new npc_adventurous_dwarf();
    new npc_jungle_punch_target();
    RegisterSpellScript(spell_q12620_the_lifewarden_wrath);
    RegisterSpellScript(spell_q12589_shoot_rjr);
    new npc_vics_flying_machine();
    RegisterSpellScript(spell_shango_tracks);
    RegisterSpellScript(spell_q12611_deathbolt);
}
References RegisterSpellScript.
Referenced by AddNorthrendScripts().
AddSC_storm_peaks()
void AddSC_storm_peaks ()
{
    RegisterCreatureAI(npc_frosthound);
    new npc_iron_watcher();
    new npc_time_lost_proto_drake();
    new npc_wild_wyrm();
    RegisterSpellScript(spell_q13003_thursting_hodirs_spear_aura);
    RegisterSpellScript(spell_q13007_iron_colossus);
    new npc_roxi_ramrocket();
    new npc_brunnhildar_prisoner();
    new npc_freed_protodrake();
    new npc_icefang();
    new npc_hyldsmeet_protodrake();
    RegisterSpellScript(spell_close_rift_aura);
    new npc_vehicle_d16_propelled_delivery();
    RegisterSpellScript(spell_q12823_remove_collapsing_cave_aura);
    RegisterSpellScript(spell_feed_stormcrest_eagle);
}
References RegisterCreatureAI, and RegisterSpellScript.
Referenced by AddNorthrendScripts().
AddSC_trial_of_the_champion()
void AddSC_trial_of_the_champion ()
{
    new npc_announcer_toc5();
}
Referenced by AddNorthrendScripts().
AddSC_trial_of_the_crusader()
void AddSC_trial_of_the_crusader ()
{
    new npc_announcer_toc10();
}
Referenced by AddNorthrendScripts().
AddSC_ulduar()
void AddSC_ulduar ()
{
    new npc_ulduar_keeper();
    RegisterSpellScript(spell_ulduar_energy_sap_aura);
    RegisterUlduarCreatureAI(npc_ulduar_snow_mound);
    new npc_ulduar_storm_tempered_keeper();
    new npc_ulduar_arachnopod_destroyer();
    RegisterSpellScript(spell_ulduar_arachnopod_damaged_aura);
    new AreaTrigger_at_celestial_planetarium_enterance();
    RegisterCreatureAI(npc_salvaged_siege_engine);
}
References RegisterCreatureAI, RegisterSpellScript, and RegisterUlduarCreatureAI.
Referenced by AddNorthrendScripts().
AddSC_utgarde_keep()
void AddSC_utgarde_keep ()
{
    RegisterUtgardeKeepCreatureAI(npc_dragonflayer_forge_master);
    RegisterUtgardeKeepCreatureAI(npc_enslaved_proto_drake);
    RegisterSpellScript(spell_ticking_time_bomb_aura);
}
References RegisterSpellScript, and RegisterUtgardeKeepCreatureAI.
Referenced by AddNorthrendScripts().
AddSC_utgarde_pinnacle()
void AddSC_utgarde_pinnacle ()
{
    RegisterSpellScript(spell_utgarde_pinnacle_beast_mark);
}
References RegisterSpellScript.
Referenced by AddNorthrendScripts().
AddSC_violet_hold()
void AddSC_violet_hold ()
{
    new go_vh_activation_crystal();
    new npc_vh_sinclari();
    new npc_vh_teleportation_portal();
    new npc_azure_saboteur();
    new npc_azure_invader();
    new npc_azure_spellbreaker();
    new npc_azure_binder();
    new npc_azure_mage_slayer();
    new npc_azure_captain();
    new npc_azure_sorceror();
    new npc_azure_raider();
    new npc_azure_stalker();
    RegisterSpellScript(spell_destroy_door_seal_aura);
    RegisterCreatureAI(npc_violet_hold_defense_system);
}
References RegisterCreatureAI, and RegisterSpellScript.
Referenced by AddNorthrendScripts().
AddSC_wintergrasp()
void AddSC_wintergrasp ()
{
    // NPCs
    new npc_wg_queue();
    new npc_wg_spirit_guide();
    new npc_wg_demolisher_engineer();
    new npc_wg_quest_giver();
    new npc_wg_siege_machine();
    // GOs
    new go_wg_vehicle_teleporter();
    // SPELLs
    RegisterSpellScript(spell_wintergrasp_force_building);
    RegisterSpellScript(spell_wintergrasp_create_vehicle);
    RegisterSpellScript(spell_wintergrasp_rp_gg);
    RegisterSpellScript(spell_wintergrasp_portal);
    RegisterSpellScript(spell_wintergrasp_water);
    RegisterSpellScript(spell_wintergrasp_hide_small_elementals_aura);
    RegisterSpellScript(spell_wg_reduce_damage_by_distance);
    // ACHIEVEMENTs
    new achievement_wg_didnt_stand_a_chance();
    new achievement_wg_vehicular_gnomeslaughter();
    new achievement_wg_within_our_grasp();
}
References RegisterSpellScript.
Referenced by AddNorthrendScripts().
AddSC_zuldrak()
void AddSC_zuldrak ()
{
    new npc_finklestein();
    new go_finklestein_cauldron();
    new npc_overlord_drakuru_betrayal();
    new npc_drakuru_shackles();
    new npc_captured_rageclaw();
    new npc_released_offspring_harkoa();
    new npc_crusade_recruit();
    new go_scourge_enclosure();
    RegisterSpellScript(spell_scourge_disguise_instability);
}
References RegisterSpellScript.
Referenced by AddNorthrendScripts().