AzerothCore Doxygen
instance_deadmines::instance_deadmines_InstanceMapScript Struct Reference
Public Member Functions
instance_deadmines_InstanceMapScript (Map *map)
void Initialize () override
void OnGameObjectCreate (GameObject *gameobject) override
void SetData (uint32 type, uint32 data) override
std::string GetSaveData () override
void Load (const char *in) override
Public Member Functions inherited from InstanceScript
InstanceScript (Map *map)
~InstanceScript () override
virtual void CreatureLooted (Creature *, LootType)
void SaveToDB ()
virtual void Update (uint32)
virtual bool IsEncounterInProgress () const
void OnCreatureCreate (Creature *creature) override
void OnCreatureRemove (Creature *creature) override
void OnGameObjectCreate (GameObject *go) override
void OnGameObjectRemove (GameObject *go) override
ObjectGuid GetObjectGuid (uint32 type) const
ObjectGuid GetGuidData (uint32 type) const override
Creature * GetCreature (uint32 type)
GameObject * GetGameObject (uint32 type)
virtual void OnPlayerEnter (Player *)
virtual void OnPlayerLeave (Player *)
virtual void OnPlayerAreaUpdate (Player *, uint32, uint32)
virtual void OnPlayerInWaterStateUpdate (Player *, bool)
void HandleGameObject (ObjectGuid guid, bool open, GameObject *go=nullptr)
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
void DoRespawnGameObject (uint32 type)
void DoRespawnCreature (ObjectGuid guid, bool force=false)
void DoRespawnCreature (uint32 type, bool force=false)
void DoUpdateWorldState (uint32 worldstateId, uint32 worldstateValue)
void DoSendNotifyToInstance (char const *format,...)
void DoUpdateAchievementCriteria (AchievementCriteriaTypes type, uint32 miscValue1=0, uint32 miscValue2=0, Unit *unit=nullptr)
void DoStartTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoStopTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoRemoveAurasDueToSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayer (Player *player, uint32 spell, bool includePets, bool includeControlled)
bool ServerAllowsTwoSideGroups ()
virtual bool SetBossState (uint32 id, EncounterState state)
EncounterState GetBossState (uint32 id) const
CreatureBoundary const * GetBossBoundary (uint32 id) const
BossInfo const * GetBossInfo (uint32 id) const
uint32 GetPersistentData (uint32 index) const
void StorePersistentData (uint32 index, uint32 data)
virtual bool CheckAchievementCriteriaMeet (uint32, Player const *, Unit const *=nullptr, uint32=0)
virtual bool CheckRequiredBosses (uint32, Player const *=nullptr) const
void SetCompletedEncountersMask (uint32 newMask, bool save)
uint32 GetCompletedEncounterMask () const
void SendEncounterUnit (uint32 type, Unit *unit=nullptr, uint8 param1=0, uint8 param2=0)
virtual void FillInitialWorldStates (WorldPackets::WorldState::InitWorldStates &)
uint32 GetEncounterCount () const
void MarkAreaTriggerDone (uint32 id)
void ResetAreaTriggerDone (uint32 id)
bool IsAreaTriggerDone (uint32 id) const
virtual void DoAction (int32)
void DoForAllMinions (uint32 id, std::function< void(Creature *)> exec)
void StoreGameObjectState (ObjectGuid::LowType spawnId, uint8 state)
uint8 GetStoredGameObjectState (ObjectGuid::LowType spawnId) const
void LoadInstanceSavedGameobjectStateData ()
bool IsBossDone (uint32 bossId) const
bool AllBossesDone () const
bool AllBossesDone (std::initializer_list< uint32 > bossIds) const
TeamId GetTeamIdInInstance () const
void SetTeamIdInInstance (TeamId teamId)
bool IsTwoFactionInstance () const
Public Member Functions inherited from ZoneScript
ZoneScript ()
virtual ~ZoneScript ()
virtual uint32 GetCreatureEntry (ObjectGuid::LowType, CreatureData const *data)
virtual uint32 GetGameObjectEntry (ObjectGuid::LowType, uint32 entry)
virtual void OnUnitDeath (Unit *)
virtual void OnCreatureEvade (Creature *)
virtual void SetGuidData (uint32, ObjectGuid)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
virtual uint32 GetData (uint32) const
virtual void ProcessEvent (WorldObject *, uint32)
Private Attributes
uint32 _encounters [MAX_ENCOUNTERS]
Additional Inherited Members
Static Public Member Functions inherited from InstanceScript
static std::string GetBossStateName (uint8 state)
Public Attributes inherited from InstanceScript
Map * instance
TaskScheduler scheduler
Protected Member Functions inherited from InstanceScript
void SetHeaders (std::string const &dataHeaders)
void SetBossNumber (uint32 number)
void SetPersistentDataCount (uint32 number)
void LoadBossBoundaries (BossBoundaryData const &data)
void LoadDoorData (DoorData const *data)
void LoadMinionData (MinionData const *data)
void LoadObjectData (ObjectData const *creatureData, ObjectData const *gameObjectData)
void LoadSummonData (ObjectData const *data)
void SetSummoner (Creature *creature)
void AddObject (Creature *obj, bool add=true)
void RemoveObject (Creature *obj)
void AddObject (GameObject *obj, bool add=true)
void RemoveObject (GameObject *obj)
void AddObject (WorldObject *obj, uint32 type, bool add=true)
void RemoveObject (WorldObject *obj, uint32 type)
void AddDoor (GameObject *door, bool add=true)
void RemoveDoor (GameObject *door)
void AddMinion (Creature *minion, bool add=true)
void RemoveMinion (Creature *minion)
void UpdateDoorState (GameObject *door)
void UpdateMinionState (Creature *minion, EncounterState state)
bool ReadSaveDataHeaders (std::istringstream &data)
void ReadSaveDataBossStates (std::istringstream &data)
void ReadSavePersistentData (std::istringstream &data)
virtual void ReadSaveDataMore (std::istringstream &)
void WriteSaveDataHeaders (std::ostringstream &data)
void WriteSaveDataBossStates (std::ostringstream &data)
void WritePersistentData (std::ostringstream &data)
virtual void WriteSaveDataMore (std::ostringstream &)
Detailed Description
Constructor & Destructor Documentation
instance_deadmines_InstanceMapScript()
instance_deadmines::instance_deadmines_InstanceMapScript::instance_deadmines_InstanceMapScript (Map * map) inline
                                                       : InstanceScript(map)
        {
            SetHeaders(DataHeader);
        }
References DataHeader, and InstanceScript::SetHeaders().
Member Function Documentation
GetSaveData()
std::string instance_deadmines::instance_deadmines_InstanceMapScript::GetSaveData () inline override virtual
Reimplemented from InstanceScript.
        {
            std::ostringstream saveStream;
            saveStream << "D E " << _encounters[0] << ' ' << _encounters[1];
            return saveStream.str();
        }
References _encounters.
Initialize()
void instance_deadmines::instance_deadmines_InstanceMapScript::Initialize () inline override virtual
Reimplemented from InstanceScript.
        {
            memset(&_encounters, 0, sizeof(_encounters));
        }
References _encounters.
Load()
void instance_deadmines::instance_deadmines_InstanceMapScript::Load (const char * in) inline override virtual
Reimplemented from InstanceScript.
        {
            if (!in)
                return;
            char dataHead1, dataHead2;
            std::istringstream loadStream(in);
            loadStream >> dataHead1 >> dataHead2;
            if (dataHead1 == 'D' && dataHead2 == 'E')
            {
                for (uint8 i = 0; i < MAX_ENCOUNTERS; ++i)
                {
                    loadStream >> _encounters[i];
                    if (_encounters[i] == IN_PROGRESS)
                        _encounters[i] = NOT_STARTED;
                }
            }
        }
References _encounters, IN_PROGRESS, MAX_ENCOUNTERS, and NOT_STARTED.
OnGameObjectCreate()
void instance_deadmines::instance_deadmines_InstanceMapScript::OnGameObjectCreate (GameObject * gameobject) inline override virtual
Reimplemented from ZoneScript.
        {
            switch (gameobject->GetEntry())
            {
                case GO_HEAVY_DOOR_1:
                case GO_HEAVY_DOOR_2:
                case GO_DOOR_LEVER_1:
                case GO_DOOR_LEVER_2:
                case GO_DOOR_LEVER_3:
                case GO_CANNON:
                    gameobject->AllowSaveToDB(true);
                    break;
                case GO_FACTORY_DOOR:
                    gameobject->AllowSaveToDB(true);
                    // GoState (Door opened) is restored during GO creation, but we need to set LootState to prevent Lever from closing it again
                    if (_encounters[TYPE_RHAHK_ZOR] == DONE)
                        gameobject->SetLootState(GO_ACTIVATED);
                    break;
                case GO_IRON_CLAD_DOOR:
                    gameobject->AllowSaveToDB(true);
                    if (GetStoredGameObjectState(gameobject->GetSpawnId()) == GO_STATE_ACTIVE)
                    {
                        gameobject->DespawnOrUnsummon();
                    }
                    break;
            }
        }
References _encounters, GameObject::AllowSaveToDB(), GameObject::DespawnOrUnsummon(), DONE, Object::GetEntry(), GameObject::GetSpawnId(), InstanceScript::GetStoredGameObjectState(), GO_ACTIVATED, GO_CANNON, GO_DOOR_LEVER_1, GO_DOOR_LEVER_2, GO_DOOR_LEVER_3, GO_FACTORY_DOOR, GO_HEAVY_DOOR_1, GO_HEAVY_DOOR_2, GO_IRON_CLAD_DOOR, GO_STATE_ACTIVE, GameObject::SetLootState(), and TYPE_RHAHK_ZOR.
SetData()
void instance_deadmines::instance_deadmines_InstanceMapScript::SetData (uint32 type, uint32 data) inline override virtual
Reimplemented from ZoneScript.
        {
            switch (type)
            {
                case TYPE_RHAHK_ZOR:
                case TYPE_CANNON:
                    _encounters[type] = data;
                    break;
            }
            if (data == DONE)
                SaveToDB();
        }
References _encounters, DONE, InstanceScript::SaveToDB(), TYPE_CANNON, and TYPE_RHAHK_ZOR.
Member Data Documentation
_encounters
uint32 instance_deadmines::instance_deadmines_InstanceMapScript::_encounters[MAX_ENCOUNTERS] private
Referenced by GetSaveData(), Initialize(), Load(), OnGameObjectCreate(), and SetData().
The documentation for this struct was generated from the following file:
azerothcore-wotlk/src/server/scripts/EasternKingdoms/Deadmines/instance_deadmines.cpp