AzerothCore Doxygen
eastern_kingdoms_script_loader.cpp File Reference
Functions
void AddSC_alterac_valley ()
void AddSC_boss_balinda ()
void AddSC_boss_drekthar ()
void AddSC_boss_galvangar ()
void AddSC_boss_vanndar ()
void AddSC_blackrock_depths ()
void AddSC_boss_ambassador_flamelash ()
void AddSC_boss_anubshiah ()
void AddSC_boss_draganthaurissan ()
void AddSC_boss_general_angerforge ()
void AddSC_boss_gorosh_the_dervish ()
void AddSC_boss_grizzle ()
void AddSC_boss_eviscerator ()
void AddSC_boss_okthor ()
void AddSC_boss_hedrum ()
void AddSC_boss_high_interrogator_gerstahn ()
void AddSC_boss_magmus ()
void AddSC_boss_moira_bronzebeard ()
void AddSC_boss_high_priestess_thaurissan ()
void AddSC_boss_tomb_of_seven ()
void AddSC_instance_blackrock_depths ()
void AddSC_boss_drakkisath ()
void AddSC_boss_halycon ()
void AddSC_boss_highlordomokk ()
void AddSC_boss_overlordwyrmthalak ()
void AddSC_boss_thebeast ()
void AddSC_boss_lord_valthalak ()
void AddSC_boss_warmastervoone ()
void AddSC_boss_pyroguard_emberseer ()
void AddSC_boss_gyth ()
void AddSC_boss_rend_blackhand ()
void AddSC_boss_urok_doomhowl ()
void AddSC_boss_solakar_flamewreath ()
void AddSC_boss_quartermasterzigris ()
void AddSC_boss_mor_grayhoof ()
void AddSC_instance_blackrock_spire ()
void AddSC_boss_razorgore ()
void AddSC_boss_vaelastrasz ()
void AddSC_boss_broodlord ()
void AddSC_boss_firemaw ()
void AddSC_boss_ebonroc ()
void AddSC_boss_flamegor ()
void AddSC_boss_chromaggus ()
void AddSC_boss_nefarian ()
void AddSC_instance_blackwing_lair ()
void AddSC_boss_mr_smite ()
void AddSC_instance_deadmines ()
void AddSC_instance_gnomeregan ()
void AddSC_instance_karazhan ()
void AddSC_boss_servant_quarters ()
void AddSC_boss_attumen ()
void AddSC_boss_curator ()
void AddSC_boss_chess_event ()
void AddSC_boss_maiden_of_virtue ()
void AddSC_boss_shade_of_aran ()
void AddSC_boss_malchezaar ()
void AddSC_boss_terestian_illhoof ()
void AddSC_boss_moroes ()
void AddSC_bosses_opera ()
void AddSC_boss_netherspite ()
void AddSC_karazhan ()
void AddSC_boss_nightbane ()
void AddSC_boss_felblood_kaelthas ()
void AddSC_boss_selin_fireheart ()
void AddSC_boss_vexallus ()
void AddSC_boss_priestess_delrissa ()
void AddSC_instance_magisters_terrace ()
void AddSC_molten_core ()
void AddSC_boss_lucifron ()
void AddSC_boss_magmadar ()
void AddSC_boss_gehennas ()
void AddSC_boss_garr ()
void AddSC_boss_baron_geddon ()
void AddSC_boss_shazzrah ()
void AddSC_boss_golemagg ()
void AddSC_boss_sulfuron ()
void AddSC_boss_majordomo ()
void AddSC_boss_ragnaros ()
void AddSC_instance_molten_core ()
void AddSC_the_scarlet_enclave ()
void AddSC_the_scarlet_enclave_c1 ()
void AddSC_the_scarlet_enclave_c2 ()
void AddSC_the_scarlet_enclave_c3 ()
void AddSC_the_scarlet_enclave_c5 ()
void AddSC_instance_scarlet_monastery ()
void AddSC_boss_kirtonos_the_herald ()
void AddSC_boss_darkmaster_gandling ()
void AddSC_boss_kormok ()
void AddSC_instance_scholomance ()
void AddSC_boss_apothecary_hummel ()
void AddSC_instance_shadowfang_keep ()
void AddSC_boss_baroness_anastari ()
void AddSC_boss_jarien_and_sothos ()
void AddSC_instance_stratholme ()
void AddSC_instance_sunken_temple ()
void AddSC_instance_sunwell_plateau ()
void AddSC_boss_kalecgos ()
void AddSC_boss_brutallus ()
void AddSC_boss_felmyst ()
void AddSC_boss_eredar_twins ()
void AddSC_boss_muru ()
void AddSC_boss_kiljaeden ()
void AddSC_instance_the_stockade ()
void AddSC_instance_uldaman ()
void AddSC_boss_akilzon ()
void AddSC_boss_halazzi ()
void AddSC_boss_hex_lord_malacrass ()
void AddSC_boss_janalai ()
void AddSC_boss_nalorakk ()
void AddSC_boss_zuljin ()
void AddSC_instance_zulaman ()
void AddSC_zulaman ()
void AddSC_boss_jeklik ()
void AddSC_boss_venoxis ()
void AddSC_boss_marli ()
void AddSC_boss_mandokir ()
void AddSC_boss_gahzranka ()
void AddSC_boss_thekal ()
void AddSC_boss_arlokk ()
void AddSC_boss_jindo ()
void AddSC_boss_hakkar ()
void AddSC_boss_grilek ()
void AddSC_boss_hazzarah ()
void AddSC_boss_renataki ()
void AddSC_boss_wushoolay ()
void AddSC_instance_zulgurub ()
void AddSC_zulgurub ()
void AddSC_arathi_highlands ()
void AddSC_blasted_lands ()
void AddSC_duskwood ()
void AddSC_eastern_plaguelands ()
void AddSC_elwynn_forest ()
void AddSC_eversong_woods ()
void AddSC_ghostlands ()
void AddSC_hinterlands ()
void AddSC_isle_of_queldanas ()
void AddSC_redridge_mountains ()
void AddSC_silverpine_forest ()
void AddSC_stormwind_city ()
void AddSC_undercity ()
void AddSC_western_plaguelands ()
void AddSC_westfall ()
void AddSC_burning_steppes ()
void AddEasternKingdomsScripts ()
Function Documentation
AddEasternKingdomsScripts()
void AddEasternKingdomsScripts ()
{
    AddSC_alterac_valley();                 //Alterac Valley
    AddSC_boss_balinda();
    AddSC_boss_drekthar();
    AddSC_boss_galvangar();
    AddSC_boss_vanndar();
    AddSC_blackrock_depths();               //Blackrock Depths
    AddSC_boss_ambassador_flamelash();
    AddSC_boss_anubshiah();
    AddSC_boss_draganthaurissan();
    AddSC_boss_general_angerforge();
    AddSC_boss_gorosh_the_dervish();
    AddSC_boss_grizzle();
    AddSC_boss_okthor();
    AddSC_boss_eviscerator();
    AddSC_boss_hedrum();
    AddSC_boss_high_interrogator_gerstahn();
    AddSC_boss_magmus();
    AddSC_boss_moira_bronzebeard();
    AddSC_boss_high_priestess_thaurissan();
    AddSC_boss_tomb_of_seven();
    AddSC_instance_blackrock_depths();
    AddSC_boss_drakkisath();                //Blackrock Spire
    AddSC_boss_halycon();
    AddSC_boss_highlordomokk();
    AddSC_boss_overlordwyrmthalak();
    AddSC_boss_thebeast();
    AddSC_boss_lord_valthalak();
    AddSC_boss_warmastervoone();
    AddSC_boss_pyroguard_emberseer();
    AddSC_boss_gyth();
    AddSC_boss_solakar_flamewreath();
    AddSC_boss_rend_blackhand();
    AddSC_boss_urok_doomhowl();
    AddSC_boss_quartermasterzigris();
    AddSC_boss_mor_grayhoof();
    AddSC_instance_blackrock_spire();
    AddSC_boss_razorgore();                 //Blackwing lair
    AddSC_boss_vaelastrasz();
    AddSC_boss_broodlord();
    AddSC_boss_firemaw();
    AddSC_boss_ebonroc();
    AddSC_boss_flamegor();
    AddSC_boss_chromaggus();
    AddSC_boss_nefarian();
    AddSC_instance_blackwing_lair();
    AddSC_boss_mr_smite();
    AddSC_instance_deadmines();             //Deadmines
    AddSC_instance_gnomeregan();            //Gnomeregan
    AddSC_instance_karazhan();              //Karazhan
    AddSC_boss_servant_quarters();
    AddSC_boss_attumen();
    AddSC_boss_curator();
    AddSC_boss_chess_event();
    AddSC_boss_maiden_of_virtue();
    AddSC_boss_shade_of_aran();
    AddSC_boss_malchezaar();
    AddSC_boss_terestian_illhoof();
    AddSC_boss_moroes();
    AddSC_bosses_opera();
    AddSC_boss_netherspite();
    AddSC_karazhan();
    AddSC_boss_nightbane();
    AddSC_boss_felblood_kaelthas();         // Magister's Terrace
    AddSC_boss_selin_fireheart();
    AddSC_boss_vexallus();
    AddSC_boss_priestess_delrissa();
    AddSC_instance_magisters_terrace();
    AddSC_molten_core();                    // Molten core
    AddSC_boss_lucifron();
    AddSC_boss_magmadar();
    AddSC_boss_gehennas();
    AddSC_boss_garr();
    AddSC_boss_baron_geddon();
    AddSC_boss_shazzrah();
    AddSC_boss_golemagg();
    AddSC_boss_sulfuron();
    AddSC_boss_majordomo();
    AddSC_boss_ragnaros();
    AddSC_instance_molten_core();
    AddSC_the_scarlet_enclave();            //Scarlet Enclave
    AddSC_the_scarlet_enclave_c1();
    AddSC_the_scarlet_enclave_c2();
    AddSC_the_scarlet_enclave_c3();
    AddSC_the_scarlet_enclave_c5();
    AddSC_instance_scarlet_monastery();     //Scarlet Monastery
    AddSC_boss_kirtonos_the_herald();
    AddSC_boss_darkmaster_gandling();
    AddSC_boss_kormok();
    AddSC_instance_scholomance();           //Scholomance
    AddSC_boss_apothecary_hummel();
    AddSC_instance_shadowfang_keep();       //Shadowfang keep
    AddSC_boss_baroness_anastari();
    AddSC_boss_jarien_and_sothos();
    AddSC_instance_stratholme();            //Stratholme
    AddSC_instance_sunken_temple();         //Sunken Temple
    AddSC_instance_sunwell_plateau();       //Sunwell Plateau
    AddSC_boss_kalecgos();
    AddSC_boss_brutallus();
    AddSC_boss_felmyst();
    AddSC_boss_eredar_twins();
    AddSC_boss_muru();
    AddSC_boss_kiljaeden();
    AddSC_instance_the_stockade();          //The Stockade
    AddSC_instance_uldaman();               //Uldaman
    AddSC_boss_akilzon();                   //Zul'Aman
    AddSC_boss_halazzi();
    AddSC_boss_hex_lord_malacrass();
    AddSC_boss_janalai();
    AddSC_boss_nalorakk();
    AddSC_boss_zuljin();
    AddSC_instance_zulaman();
    AddSC_zulaman();
    AddSC_boss_jeklik();                    //Zul'Gurub
    AddSC_boss_venoxis();
    AddSC_boss_marli();
    AddSC_boss_mandokir();
    AddSC_boss_gahzranka();
    AddSC_boss_thekal();
    AddSC_boss_arlokk();
    AddSC_boss_jindo();
    AddSC_boss_hakkar();
    AddSC_boss_grilek();
    AddSC_boss_hazzarah();
    AddSC_boss_renataki();
    AddSC_boss_wushoolay();
    AddSC_instance_zulgurub();
    AddSC_zulgurub();
    //AddSC_alterac_mountains();
    AddSC_arathi_highlands();
    AddSC_blasted_lands();
    AddSC_duskwood();
    AddSC_eastern_plaguelands();
    AddSC_elwynn_forest();
    AddSC_eversong_woods();
    AddSC_ghostlands();
    AddSC_hinterlands();
//    AddSC_ironforge();
    AddSC_isle_of_queldanas();
    AddSC_redridge_mountains();
    AddSC_silverpine_forest();
    AddSC_stormwind_city();
    AddSC_undercity();
    AddSC_western_plaguelands();
    AddSC_westfall();
    //AddSC_wetlands();
    AddSC_burning_steppes();
}
References AddSC_alterac_valley(), AddSC_arathi_highlands(), AddSC_blackrock_depths(), AddSC_blasted_lands(), AddSC_boss_akilzon(), AddSC_boss_ambassador_flamelash(), AddSC_boss_anubshiah(), AddSC_boss_apothecary_hummel(), AddSC_boss_arlokk(), AddSC_boss_attumen(), AddSC_boss_balinda(), AddSC_boss_baron_geddon(), AddSC_boss_baroness_anastari(), AddSC_boss_broodlord(), AddSC_boss_brutallus(), AddSC_boss_chess_event(), AddSC_boss_chromaggus(), AddSC_boss_curator(), AddSC_boss_darkmaster_gandling(), AddSC_boss_draganthaurissan(), AddSC_boss_drakkisath(), AddSC_boss_drekthar(), AddSC_boss_ebonroc(), AddSC_boss_eredar_twins(), AddSC_boss_eviscerator(), AddSC_boss_felblood_kaelthas(), AddSC_boss_felmyst(), AddSC_boss_firemaw(), AddSC_boss_flamegor(), AddSC_boss_gahzranka(), AddSC_boss_galvangar(), AddSC_boss_garr(), AddSC_boss_gehennas(), AddSC_boss_general_angerforge(), AddSC_boss_golemagg(), AddSC_boss_gorosh_the_dervish(), AddSC_boss_grilek(), AddSC_boss_grizzle(), AddSC_boss_gyth(), AddSC_boss_hakkar(), AddSC_boss_halazzi(), AddSC_boss_halycon(), AddSC_boss_hazzarah(), AddSC_boss_hedrum(), AddSC_boss_hex_lord_malacrass(), AddSC_boss_high_interrogator_gerstahn(), AddSC_boss_high_priestess_thaurissan(), AddSC_boss_highlordomokk(), AddSC_boss_janalai(), AddSC_boss_jarien_and_sothos(), AddSC_boss_jeklik(), AddSC_boss_jindo(), AddSC_boss_kalecgos(), AddSC_boss_kiljaeden(), AddSC_boss_kirtonos_the_herald(), AddSC_boss_kormok(), AddSC_boss_lord_valthalak(), AddSC_boss_lucifron(), AddSC_boss_magmadar(), AddSC_boss_magmus(), AddSC_boss_maiden_of_virtue(), AddSC_boss_majordomo(), AddSC_boss_malchezaar(), AddSC_boss_mandokir(), AddSC_boss_marli(), AddSC_boss_moira_bronzebeard(), AddSC_boss_mor_grayhoof(), AddSC_boss_moroes(), AddSC_boss_mr_smite(), AddSC_boss_muru(), AddSC_boss_nalorakk(), AddSC_boss_nefarian(), AddSC_boss_netherspite(), AddSC_boss_nightbane(), AddSC_boss_okthor(), AddSC_boss_overlordwyrmthalak(), AddSC_boss_priestess_delrissa(), AddSC_boss_pyroguard_emberseer(), AddSC_boss_quartermasterzigris(), AddSC_boss_ragnaros(), AddSC_boss_razorgore(), AddSC_boss_renataki(), AddSC_boss_rend_blackhand(), AddSC_boss_selin_fireheart(), AddSC_boss_servant_quarters(), AddSC_boss_shade_of_aran(), AddSC_boss_shazzrah(), AddSC_boss_solakar_flamewreath(), AddSC_boss_sulfuron(), AddSC_boss_terestian_illhoof(), AddSC_boss_thebeast(), AddSC_boss_thekal(), AddSC_boss_tomb_of_seven(), AddSC_boss_urok_doomhowl(), AddSC_boss_vaelastrasz(), AddSC_boss_vanndar(), AddSC_boss_venoxis(), AddSC_boss_vexallus(), AddSC_boss_warmastervoone(), AddSC_boss_wushoolay(), AddSC_boss_zuljin(), AddSC_bosses_opera(), AddSC_burning_steppes(), AddSC_duskwood(), AddSC_eastern_plaguelands(), AddSC_elwynn_forest(), AddSC_eversong_woods(), AddSC_ghostlands(), AddSC_hinterlands(), AddSC_instance_blackrock_depths(), AddSC_instance_blackrock_spire(), AddSC_instance_blackwing_lair(), AddSC_instance_deadmines(), AddSC_instance_gnomeregan(), AddSC_instance_karazhan(), AddSC_instance_magisters_terrace(), AddSC_instance_molten_core(), AddSC_instance_scarlet_monastery(), AddSC_instance_scholomance(), AddSC_instance_shadowfang_keep(), AddSC_instance_stratholme(), AddSC_instance_sunken_temple(), AddSC_instance_sunwell_plateau(), AddSC_instance_the_stockade(), AddSC_instance_uldaman(), AddSC_instance_zulaman(), AddSC_instance_zulgurub(), AddSC_isle_of_queldanas(), AddSC_karazhan(), AddSC_molten_core(), AddSC_redridge_mountains(), AddSC_silverpine_forest(), AddSC_stormwind_city(), AddSC_the_scarlet_enclave(), AddSC_the_scarlet_enclave_c1(), AddSC_the_scarlet_enclave_c2(), AddSC_the_scarlet_enclave_c3(), AddSC_the_scarlet_enclave_c5(), AddSC_undercity(), AddSC_western_plaguelands(), AddSC_westfall(), AddSC_zulaman(), and AddSC_zulgurub().
AddSC_alterac_valley()
void AddSC_alterac_valley ()
{
    new npc_av_marshal_or_warmaster();
}
Referenced by AddEasternKingdomsScripts().
AddSC_arathi_highlands()
void AddSC_arathi_highlands ()
{
    new npc_professor_phizzlethorpe();
}
Referenced by AddEasternKingdomsScripts().
AddSC_blackrock_depths()
void AddSC_blackrock_depths ()
{
    new go_shadowforge_brazier();
    new at_ring_of_law();
    new npc_grimstone();
    new npc_phalanx();
    new npc_lokhtos_darkbargainer();
    new npc_rocknot();
    new ironhand_guardian();
}
Referenced by AddEasternKingdomsScripts().
AddSC_blasted_lands()
void AddSC_blasted_lands ()
{
    RegisterSpellScript(spell_razelikh_teleport_group);
}
References RegisterSpellScript.
Referenced by AddEasternKingdomsScripts().
AddSC_boss_akilzon()
void AddSC_boss_akilzon ()
{
    RegisterZulAmanCreatureAI(boss_akilzon);
    RegisterZulAmanCreatureAI(npc_akilzon_eagle);
    RegisterSpellScript(spell_electrial_storm);
    RegisterSpellScript(spell_electrical_storm_proc);
}
References RegisterSpellScript, and RegisterZulAmanCreatureAI.
Referenced by AddEasternKingdomsScripts().
AddSC_boss_ambassador_flamelash()
void AddSC_boss_ambassador_flamelash ()
{
    new boss_ambassador_flamelash();
    new npc_burning_spirit();
}
Referenced by AddEasternKingdomsScripts().
AddSC_boss_anubshiah()
void AddSC_boss_anubshiah ()
{
    new boss_anubshiah();
}
Referenced by AddEasternKingdomsScripts().
AddSC_boss_apothecary_hummel()
void AddSC_boss_apothecary_hummel ()
{
    new boss_apothecary_hummel();
    RegisterShadowfangKeepCreatureAI(npc_apothecary_baxter);
    RegisterShadowfangKeepCreatureAI(npc_apothecary_frye);
    RegisterSpellScript(spell_apothecary_lingering_fumes);
    RegisterSpellScript(spell_apothecary_validate_area);
    RegisterSpellScript(spell_apothecary_throw_cologne);
    RegisterSpellScript(spell_apothecary_throw_perfume);
    RegisterSpellScript(spell_apothecary_perfume_spill);
    RegisterSpellScript(spell_apothecary_cologne_spill);
}
References RegisterShadowfangKeepCreatureAI, and RegisterSpellScript.
Referenced by AddEasternKingdomsScripts().
AddSC_boss_arlokk()
void AddSC_boss_arlokk ()
{
    new boss_arlokk();
    new npc_zulian_prowler();
    new go_gong_of_bethekk();
}
Referenced by AddEasternKingdomsScripts().
AddSC_boss_attumen()
void AddSC_boss_attumen ()
{
    RegisterKarazhanCreatureAI(boss_midnight);
    RegisterKarazhanCreatureAI(boss_attumen);
    RegisterSpellScript(spell_midnight_fixate);
}
References RegisterKarazhanCreatureAI, and RegisterSpellScript.
Referenced by AddEasternKingdomsScripts().
AddSC_boss_balinda()
void AddSC_boss_balinda ()
{
    RegisterCreatureAI(boss_balinda);
}
References RegisterCreatureAI.
Referenced by AddEasternKingdomsScripts().
AddSC_boss_baron_geddon()
void AddSC_boss_baron_geddon ()
{
    new boss_baron_geddon();
    // Spells
    RegisterSpellScript(spell_geddon_inferno_aura);
    RegisterSpellScript(spell_geddon_armageddon_aura);
}
References RegisterSpellScript.
Referenced by AddEasternKingdomsScripts().
AddSC_boss_baroness_anastari()
void AddSC_boss_baroness_anastari ()
{
    new boss_baroness_anastari;
}
Referenced by AddEasternKingdomsScripts().
AddSC_boss_broodlord()
void AddSC_boss_broodlord ()
{
    new boss_broodlord();
    new go_suppression_device();
    RegisterSpellScript(spell_suppression_aura);
}
References RegisterSpellScript.
Referenced by AddEasternKingdomsScripts().
AddSC_boss_brutallus()
void AddSC_boss_brutallus ()
{
    RegisterSunwellPlateauCreatureAI(boss_brutallus);
    RegisterSunwellPlateauCreatureAI(npc_madrigosa);
    RegisterSpellScript(spell_madrigosa_activate_barrier);
    RegisterSpellScript(spell_madrigosa_deactivate_barrier);
    RegisterSpellScript(spell_brutallus_burn);
    new at_sunwell_madrigosa();
}
References RegisterSpellScript, and RegisterSunwellPlateauCreatureAI.
Referenced by AddEasternKingdomsScripts().
AddSC_boss_chess_event()
void AddSC_boss_chess_event ()
{
    RegisterKarazhanCreatureAI(npc_echo_of_medivh);
    RegisterKarazhanCreatureAI(npc_chesspiece);
    RegisterKarazhanCreatureAI(npc_chess_move_trigger);
    RegisterSpellScript(spell_control_piece);
}
References RegisterKarazhanCreatureAI, and RegisterSpellScript.
Referenced by AddEasternKingdomsScripts().
AddSC_boss_chromaggus()
void AddSC_boss_chromaggus ()
{
    new boss_chromaggus();
    new go_chromaggus_lever();
    RegisterSpellScript(spell_gen_elemental_shield);
    RegisterSpellScript(spell_gen_brood_power);
}
References RegisterSpellScript.
Referenced by AddEasternKingdomsScripts().
AddSC_boss_curator()
void AddSC_boss_curator ()
{
    RegisterKarazhanCreatureAI(boss_curator);
}
References RegisterKarazhanCreatureAI.
Referenced by AddEasternKingdomsScripts().
AddSC_boss_darkmaster_gandling()
void AddSC_boss_darkmaster_gandling ()
{
    new boss_darkmaster_gandling();
    new npc_risen_guardian();
}
Referenced by AddEasternKingdomsScripts().
AddSC_boss_draganthaurissan()
void AddSC_boss_draganthaurissan ()
{
    new boss_emperor_dagran_thaurissan();
}
Referenced by AddEasternKingdomsScripts().
AddSC_boss_drakkisath()
void AddSC_boss_drakkisath ()
{
    new boss_drakkisath();
}
Referenced by AddEasternKingdomsScripts().
AddSC_boss_drekthar()
void AddSC_boss_drekthar ()
{
    new boss_drekthar;
}
Referenced by AddEasternKingdomsScripts().
AddSC_boss_ebonroc()
void AddSC_boss_ebonroc ()
{
    new boss_ebonroc();
}
Referenced by AddEasternKingdomsScripts().
AddSC_boss_eredar_twins()
void AddSC_boss_eredar_twins ()
{
    RegisterSunwellPlateauCreatureAI(boss_sacrolash);
    RegisterSunwellPlateauCreatureAI(boss_alythess);
    RegisterSpellScriptWithArgs(spell_eredar_twins_apply_touch, "spell_eredar_twins_apply_dark_touched", SPELL_DARK_TOUCHED);
    RegisterSpellScriptWithArgs(spell_eredar_twins_apply_touch, "spell_eredar_twins_apply_flame_touched", SPELL_FLAME_TOUCHED);
    RegisterSpellScript(spell_eredar_twins_handle_touch);
    RegisterSpellScript(spell_eredar_twins_blaze);
    RegisterSpellScript(spell_eredar_twins_flame_sear);
    RegisterSpellScriptWithArgs(spell_eredar_twins_handle_touch_periodic, "spell_eredar_twins_handle_dark_touched_periodic", SPELL_DARK_TOUCHED, EFFECT_1, SPELL_AURA_PERIODIC_DAMAGE);
    RegisterSpellScriptWithArgs(spell_eredar_twins_handle_touch_periodic, "spell_eredar_twins_handle_flame_touched_periodic", SPELL_FLAME_TOUCHED, EFFECT_2, SPELL_AURA_PERIODIC_TRIGGER_SPELL);
    RegisterSpellScriptWithArgs(spell_eredar_twins_handle_touch_periodic, "spell_eredar_twins_handle_flame_touched_flame_sear", SPELL_FLAME_TOUCHED, EFFECT_1, SPELL_AURA_PERIODIC_DAMAGE);
    new at_sunwell_eredar_twins();
    RegisterGameObjectAI(go_eredar_twins_blaze);
}
References EFFECT_1, EFFECT_2, RegisterGameObjectAI, RegisterSpellScript, RegisterSpellScriptWithArgs, RegisterSunwellPlateauCreatureAI, SPELL_AURA_PERIODIC_DAMAGE, SPELL_AURA_PERIODIC_TRIGGER_SPELL, SPELL_DARK_TOUCHED, and SPELL_FLAME_TOUCHED.
Referenced by AddEasternKingdomsScripts().
AddSC_boss_eviscerator()
void AddSC_boss_eviscerator ()
{
    new boss_eviscerator();
}
Referenced by AddEasternKingdomsScripts().
AddSC_boss_felblood_kaelthas()
void AddSC_boss_felblood_kaelthas ()
{
    RegisterMagistersTerraceCreatureAI(boss_felblood_kaelthas);
    RegisterSpellScript(spell_mt_phoenix_burn);
}
References RegisterMagistersTerraceCreatureAI, and RegisterSpellScript.
Referenced by AddEasternKingdomsScripts().
AddSC_boss_felmyst()
void AddSC_boss_felmyst ()
{
    RegisterSunwellPlateauCreatureAI(boss_felmyst);
    RegisterSunwellPlateauCreatureAI(npc_demonic_vapor);
    RegisterSunwellPlateauCreatureAI(npc_demonic_vapor_trail);
    RegisterSpellScript(spell_felmyst_fog_of_corruption);
    RegisterSpellScript(spell_felmyst_fog_of_corruption_charm_aura);
    RegisterSpellScript(spell_felmyst_open_brutallus_back_doors);
}
References RegisterSpellScript, and RegisterSunwellPlateauCreatureAI.
Referenced by AddEasternKingdomsScripts().
AddSC_boss_firemaw()
void AddSC_boss_firemaw ()
{
    new boss_firemaw();
}
Referenced by AddEasternKingdomsScripts().
AddSC_boss_flamegor()
void AddSC_boss_flamegor ()
{
    new boss_flamegor();
}
Referenced by AddEasternKingdomsScripts().
AddSC_boss_gahzranka()
void AddSC_boss_gahzranka ()
{
    RegisterZulGurubCreatureAI(boss_gahzranka);
    RegisterSpellScript(spell_gahzranka_slam);
    RegisterSpellScript(spell_pagles_point_cast);
}
References RegisterSpellScript, and RegisterZulGurubCreatureAI.
Referenced by AddEasternKingdomsScripts().
AddSC_boss_galvangar()
void AddSC_boss_galvangar ()
{
    new boss_galvangar;
}
Referenced by AddEasternKingdomsScripts().
AddSC_boss_garr()
void AddSC_boss_garr ()
{
    new boss_garr();
    new npc_garr_firesworn();
    // Spells
    RegisterSpellScript(spell_garr_separation_anxiety_aura);
    RegisterSpellScript(spell_garr_frenzy);
}
References RegisterSpellScript.
Referenced by AddEasternKingdomsScripts().
AddSC_boss_gehennas()
void AddSC_boss_gehennas ()
{
    new boss_gehennas();
}
Referenced by AddEasternKingdomsScripts().
AddSC_boss_general_angerforge()
void AddSC_boss_general_angerforge ()
{
    new boss_general_angerforge();
}
Referenced by AddEasternKingdomsScripts().
AddSC_boss_golemagg()
void AddSC_boss_golemagg ()
{
    new boss_golemagg();
    new npc_core_rager();
}
Referenced by AddEasternKingdomsScripts().
AddSC_boss_gorosh_the_dervish()
void AddSC_boss_gorosh_the_dervish ()
{
    new boss_gorosh_the_dervish();
}
Referenced by AddEasternKingdomsScripts().
AddSC_boss_grilek()
void AddSC_boss_grilek ()
{
    new boss_grilek();
}
Referenced by AddEasternKingdomsScripts().
AddSC_boss_grizzle()
void AddSC_boss_grizzle ()
{
    new boss_grizzle();
}
Referenced by AddEasternKingdomsScripts().
AddSC_boss_gyth()
void AddSC_boss_gyth ()
{
    new boss_gyth();
    RegisterSpellScript(spell_gyth_chromatic_protection);
}
References RegisterSpellScript.
Referenced by AddEasternKingdomsScripts().
AddSC_boss_hakkar()
void AddSC_boss_hakkar ()
{
    new boss_hakkar();
    new at_zulgurub_entrance_speech();
    new at_zulgurub_bridge_speech();
    new at_zulgurub_temple_speech();
    new at_zulgurub_bloodfire_pit_speech();
    new at_zulgurub_edge_of_madness_speech();
    RegisterSpellScript(spell_blood_siphon);
    RegisterSpellScript(spell_blood_siphon_aura);
    RegisterSpellScript(spell_hakkar_power_down);
}
References RegisterSpellScript.
Referenced by AddEasternKingdomsScripts().
AddSC_boss_halazzi()
void AddSC_boss_halazzi ()
{
    RegisterZulAmanCreatureAI(boss_halazzi);
}
References RegisterZulAmanCreatureAI.
Referenced by AddEasternKingdomsScripts().
AddSC_boss_halycon()
void AddSC_boss_halycon ()
{
    new boss_halycon();
}
Referenced by AddEasternKingdomsScripts().
AddSC_boss_hazzarah()
void AddSC_boss_hazzarah ()
{
    RegisterZulGurubCreatureAI(boss_hazzarah);
    RegisterSpellScript(spell_chain_burn);
}
References RegisterSpellScript, and RegisterZulGurubCreatureAI.
Referenced by AddEasternKingdomsScripts().
AddSC_boss_hedrum()
void AddSC_boss_hedrum ()
{
    new boss_hedrum();
}
Referenced by AddEasternKingdomsScripts().
AddSC_boss_hex_lord_malacrass()
void AddSC_boss_hex_lord_malacrass ()
{
    RegisterZulAmanCreatureAI(boss_hexlord_malacrass);
    RegisterZulAmanCreatureAI(boss_alyson_antille);
    RegisterSpellScript(spell_hexlord_unstable_affliction);
}
References RegisterSpellScript, and RegisterZulAmanCreatureAI.
Referenced by AddEasternKingdomsScripts().
AddSC_boss_high_interrogator_gerstahn()
void AddSC_boss_high_interrogator_gerstahn ()
{
    new boss_high_interrogator_gerstahn();
}
Referenced by AddEasternKingdomsScripts().
AddSC_boss_high_priestess_thaurissan()
void AddSC_boss_high_priestess_thaurissan ()
{
    new boss_high_priestess_thaurissan();
}
Referenced by AddEasternKingdomsScripts().
AddSC_boss_highlordomokk()
void AddSC_boss_highlordomokk ()
{
    new boss_highlord_omokk();
}
Referenced by AddEasternKingdomsScripts().
AddSC_boss_janalai()
void AddSC_boss_janalai ()
{
    RegisterZulAmanCreatureAI(boss_janalai);
    RegisterZulAmanCreatureAI(npc_janalai_hatcher);
    RegisterSpellScript(spell_summon_all_players_dummy);
}
References RegisterSpellScript, and RegisterZulAmanCreatureAI.
Referenced by AddEasternKingdomsScripts().
AddSC_boss_jarien_and_sothos()
void AddSC_boss_jarien_and_sothos ()
{
    RegisterStratholmeCreatureAI(boss_jarien);
    RegisterStratholmeCreatureAI(boss_sothos);
}
References RegisterStratholmeCreatureAI.
Referenced by AddEasternKingdomsScripts().
AddSC_boss_jeklik()
void AddSC_boss_jeklik ()
{
    RegisterCreatureAI(boss_jeklik);
    RegisterCreatureAI(npc_batrider);
    RegisterSpellScript(spell_batrider_bomb);
}
References RegisterCreatureAI, and RegisterSpellScript.
Referenced by AddEasternKingdomsScripts().
AddSC_boss_jindo()
void AddSC_boss_jindo ()
{
    RegisterZulGurubCreatureAI(boss_jindo);
    RegisterZulGurubCreatureAI(npc_healing_ward);
    RegisterZulGurubCreatureAI(npc_shade_of_jindo);
    RegisterZulGurubCreatureAI(npc_brain_wash_totem);
    RegisterSpellScript(spell_random_aggro);
    RegisterSpellScript(spell_delusions_of_jindo);
}
References RegisterSpellScript, and RegisterZulGurubCreatureAI.
Referenced by AddEasternKingdomsScripts().
AddSC_boss_kalecgos()
void AddSC_boss_kalecgos ()
{
    RegisterSunwellPlateauCreatureAI(boss_kalecgos);
    RegisterSunwellPlateauCreatureAI(boss_sathrovarr);
    RegisterSunwellPlateauCreatureAI(boss_kalec);
    RegisterSpellScript(spell_kalecgos_spectral_blast_dummy);
    RegisterSpellScript(spell_kalecgos_curse_of_boundless_agony_aura);
    RegisterSpellScript(spell_kalecgos_spectral_realm_dummy);
    RegisterSpellScript(spell_kalecgos_spectral_realm_aura);
}
References RegisterSpellScript, and RegisterSunwellPlateauCreatureAI.
Referenced by AddEasternKingdomsScripts().
AddSC_boss_kiljaeden()
void AddSC_boss_kiljaeden ()
{
    RegisterSunwellPlateauCreatureAI(npc_kiljaeden_controller);
    RegisterSunwellPlateauCreatureAI(boss_kiljaeden);
    RegisterSunwellPlateauCreatureAI(npc_kalecgos_kj);
    RegisterSpellScript(spell_kiljaeden_shadow_spike_aura);
    RegisterSpellScript(spell_kiljaeden_sinister_reflection);
    RegisterSpellScript(spell_kiljaeden_sinister_reflection_clone);
    RegisterSpellScript(spell_kiljaeden_flame_dart);
    RegisterSpellScript(spell_kiljaeden_darkness_aura);
    RegisterSpellScript(spell_kiljaeden_power_of_the_blue_flight);
    RegisterSpellScript(spell_kiljaeden_vengeance_of_the_blue_flight_aura);
    RegisterSpellScript(spell_kiljaeden_armageddon_periodic_aura);
    RegisterSpellScript(spell_kiljaeden_armageddon_missile);
    RegisterSpellScript(spell_kiljaeden_dragon_breath);
}
References RegisterSpellScript, and RegisterSunwellPlateauCreatureAI.
Referenced by AddEasternKingdomsScripts().
AddSC_boss_kirtonos_the_herald()
void AddSC_boss_kirtonos_the_herald ()
{
    new boss_kirtonos_the_herald();
}
Referenced by AddEasternKingdomsScripts().
AddSC_boss_kormok()
void AddSC_boss_kormok ()
{
    RegisterScholomanceCreatureAI(boss_kormok);
    RegisterSpellScript(spell_kormok_summon_bone_mages);
    RegisterSpellScript(spell_kormok_summon_bone_minions);
}
References RegisterScholomanceCreatureAI, and RegisterSpellScript.
Referenced by AddEasternKingdomsScripts().
AddSC_boss_lord_valthalak()
void AddSC_boss_lord_valthalak ()
{
    new boss_lord_valthalak();
}
Referenced by AddEasternKingdomsScripts().
AddSC_boss_lucifron()
void AddSC_boss_lucifron ()
{
    new boss_lucifron();
}
Referenced by AddEasternKingdomsScripts().
AddSC_boss_magmadar()
void AddSC_boss_magmadar ()
{
    new boss_magmadar();
    // Spells
    RegisterSpellScript(spell_magmadar_lava_bomb);
}
References RegisterSpellScript.
Referenced by AddEasternKingdomsScripts().
AddSC_boss_magmus()
void AddSC_boss_magmus ()
{
    new boss_magmus();
}
Referenced by AddEasternKingdomsScripts().
AddSC_boss_maiden_of_virtue()
void AddSC_boss_maiden_of_virtue ()
{
    RegisterKarazhanCreatureAI(boss_maiden_of_virtue);
}
References RegisterKarazhanCreatureAI.
Referenced by AddEasternKingdomsScripts().
AddSC_boss_majordomo()
void AddSC_boss_majordomo ()
{
    new boss_majordomo();
    // Spells
    RegisterSpellScript(spell_hate_to_zero);
    RegisterSpellScript(spell_majordomo_separation_anxiety_aura);
    RegisterSpellScript(spell_summon_ragnaros);
}
References RegisterSpellScript.
Referenced by AddEasternKingdomsScripts().
AddSC_boss_malchezaar()
void AddSC_boss_malchezaar ()
{
    RegisterKarazhanCreatureAI(boss_malchezaar);
    RegisterKarazhanCreatureAI(npc_malchezaar_axe);
    RegisterKarazhanCreatureAI(npc_netherspite_infernal);
    RegisterSpellScript(spell_malchezaar_enfeeble);
}
References RegisterKarazhanCreatureAI, and RegisterSpellScript.
Referenced by AddEasternKingdomsScripts().
AddSC_boss_mandokir()
void AddSC_boss_mandokir ()
{
    new boss_mandokir();
    new npc_ohgan();
    RegisterZulGurubCreatureAI(npc_chained_spirit);
    RegisterZulGurubCreatureAI(npc_vilebranch_speaker);
    RegisterSpellScript(spell_threatening_gaze_aura);
    RegisterSpellScript(spell_mandokir_charge);
    RegisterSpellScript(spell_threatening_gaze_charge);
}
References RegisterSpellScript, and RegisterZulGurubCreatureAI.
Referenced by AddEasternKingdomsScripts().
AddSC_boss_marli()
void AddSC_boss_marli ()
{
    RegisterCreatureAI(boss_marli);
    RegisterCreatureAI(npc_spawn_of_marli);
    RegisterSpellScript(spell_hatch_eggs);
    RegisterSpellScript(spell_enveloping_webs);
    RegisterSpellScript(spell_marli_transform);
}
References RegisterCreatureAI, and RegisterSpellScript.
Referenced by AddEasternKingdomsScripts().
AddSC_boss_moira_bronzebeard()
void AddSC_boss_moira_bronzebeard ()
{
    new boss_moira_bronzebeard();
}
Referenced by AddEasternKingdomsScripts().
AddSC_boss_mor_grayhoof()
void AddSC_boss_mor_grayhoof ()
{
    RegisterBlackrockSpireCreatureAI(boss_mor_grayhoof);
}
References RegisterBlackrockSpireCreatureAI.
Referenced by AddEasternKingdomsScripts().
AddSC_boss_moroes()
void AddSC_boss_moroes ()
{
    RegisterKarazhanCreatureAI(boss_moroes);
    RegisterSpellScript(spell_moroes_vanish);
}
References RegisterKarazhanCreatureAI, and RegisterSpellScript.
Referenced by AddEasternKingdomsScripts().
AddSC_boss_mr_smite()
void AddSC_boss_mr_smite ()
{
    new boss_mr_smite();
}
Referenced by AddEasternKingdomsScripts().
AddSC_boss_muru()
void AddSC_boss_muru ()
{
    RegisterSunwellPlateauCreatureAI(boss_muru);
    RegisterSunwellPlateauCreatureAI(boss_entropius);
    RegisterSunwellPlateauCreatureAI(npc_singularity);
    RegisterSunwellPlateauCreatureAI(npc_dark_fiend);
    RegisterSpellScript(spell_muru_summon_blood_elves_periodic_aura);
    RegisterSpellScript(spell_muru_darkness_aura);
    RegisterSpellScript(spell_entropius_void_zone_visual_aura);
    RegisterSpellScript(spell_entropius_black_hole_effect);
    RegisterSpellScript(spell_entropius_negative_energy_periodic);
    RegisterSpellScript(spell_gen_summon_target_floor);
}
References RegisterSpellScript, and RegisterSunwellPlateauCreatureAI.
Referenced by AddEasternKingdomsScripts().
AddSC_boss_nalorakk()
void AddSC_boss_nalorakk ()
{
    RegisterZulAmanCreatureAI(boss_nalorakk);
}
References RegisterZulAmanCreatureAI.
Referenced by AddEasternKingdomsScripts().
AddSC_boss_nefarian()
void AddSC_boss_nefarian ()
{
    new boss_victor_nefarius();
    RegisterCreatureAI(boss_nefarian);
    RegisterCreatureAI(npc_corrupted_totem);
    RegisterCreatureAI(npc_drakonid_spawner);
    RegisterSpellScript(spell_class_call_handler);
    RegisterSpellScript(aura_class_call_wild_magic);
    RegisterSpellScript(aura_class_call_siphon_blessing);
    RegisterSpellScript(spell_class_call_polymorph);
    RegisterSpellScript(spell_corrupted_totems);
    RegisterSpellScript(spell_shadowblink);
    RegisterSpellScript(spell_spawn_drakonid);
}
References RegisterCreatureAI, and RegisterSpellScript.
Referenced by AddEasternKingdomsScripts().
AddSC_boss_netherspite()
void AddSC_boss_netherspite ()
{
    RegisterKarazhanCreatureAI(boss_netherspite);
    RegisterSpellScript(spell_nether_portal_perseverence);
}
References RegisterKarazhanCreatureAI, and RegisterSpellScript.
Referenced by AddEasternKingdomsScripts().
AddSC_boss_nightbane()
void AddSC_boss_nightbane ()
{
    RegisterKarazhanCreatureAI(boss_nightbane);
    new go_blackened_urn();
    RegisterKarazhanCreatureAI(npc_nightbane_helper_target);
    RegisterSpellScript(spell_nightbane_fireball_barrage);
}
References RegisterKarazhanCreatureAI, and RegisterSpellScript.
Referenced by AddEasternKingdomsScripts().
AddSC_boss_okthor()
void AddSC_boss_okthor ()
{
    new boss_okthor();
}
Referenced by AddEasternKingdomsScripts().
AddSC_boss_overlordwyrmthalak()
void AddSC_boss_overlordwyrmthalak ()
{
    new boss_overlord_wyrmthalak();
}
Referenced by AddEasternKingdomsScripts().
AddSC_boss_priestess_delrissa()
void AddSC_boss_priestess_delrissa ()
{
    RegisterMagistersTerraceCreatureAI(boss_priestess_delrissa);
    RegisterMagistersTerraceCreatureAI(boss_kagani_nightstrike);
    RegisterMagistersTerraceCreatureAI(boss_ellris_duskhallow);
    RegisterMagistersTerraceCreatureAI(boss_eramas_brightblaze);
    RegisterMagistersTerraceCreatureAI(boss_yazzai);
    RegisterMagistersTerraceCreatureAI(boss_warlord_salaris);
    RegisterMagistersTerraceCreatureAI(boss_garaxxas);
    RegisterMagistersTerraceCreatureAI(boss_apoko);
    RegisterMagistersTerraceCreatureAI(boss_zelfan);
}
References RegisterMagistersTerraceCreatureAI.
Referenced by AddEasternKingdomsScripts().
AddSC_boss_pyroguard_emberseer()
void AddSC_boss_pyroguard_emberseer ()
{
    new boss_pyroguard_emberseer();
    new npc_blackhand_incarcerator();
}
Referenced by AddEasternKingdomsScripts().
AddSC_boss_quartermasterzigris()
void AddSC_boss_quartermasterzigris ()
{
    RegisterBlackrockSpireCreatureAI(boss_quartermaster_zigris);
}
References RegisterBlackrockSpireCreatureAI.
Referenced by AddEasternKingdomsScripts().
AddSC_boss_ragnaros()
void AddSC_boss_ragnaros ()
{
    new boss_ragnaros();
    RegisterSpellScript(spell_ragnaros_lava_burst_randomizer);
    RegisterSpellScript(spell_ragnaros_summon_sons_of_flame);
}
References RegisterSpellScript.
Referenced by AddEasternKingdomsScripts().
AddSC_boss_razorgore()
void AddSC_boss_razorgore ()
{
    new boss_razorgore();
    new go_orb_of_domination();
    RegisterSpellScript(spell_egg_event);
}
References RegisterSpellScript.
Referenced by AddEasternKingdomsScripts().
AddSC_boss_renataki()
void AddSC_boss_renataki ()
{
    new boss_renataki();
}
Referenced by AddEasternKingdomsScripts().
AddSC_boss_rend_blackhand()
void AddSC_boss_rend_blackhand ()
{
    new boss_rend_blackhand();
}
Referenced by AddEasternKingdomsScripts().
AddSC_boss_selin_fireheart()
void AddSC_boss_selin_fireheart ()
{
    RegisterMagistersTerraceCreatureAI(boss_selin_fireheart);
}
References RegisterMagistersTerraceCreatureAI.
Referenced by AddEasternKingdomsScripts().
AddSC_boss_servant_quarters()
void AddSC_boss_servant_quarters ()
{
    RegisterKarazhanCreatureAI(boss_servant_quarters);
}
References RegisterKarazhanCreatureAI.
Referenced by AddEasternKingdomsScripts().
AddSC_boss_shade_of_aran()
void AddSC_boss_shade_of_aran ()
{
    RegisterKarazhanCreatureAI(boss_shade_of_aran);
    RegisterSpellScript(spell_flamewreath);
    RegisterSpellScript(spell_flamewreath_aura);
    new at_karazhan_atiesh_aran();
}
References RegisterKarazhanCreatureAI, and RegisterSpellScript.
Referenced by AddEasternKingdomsScripts().
AddSC_boss_shazzrah()
void AddSC_boss_shazzrah ()
{
    new boss_shazzrah();
    // Spells
    RegisterSpellScript(spell_shazzrah_gate_dummy);
}
References RegisterSpellScript.
Referenced by AddEasternKingdomsScripts().
AddSC_boss_solakar_flamewreath()
void AddSC_boss_solakar_flamewreath ()
{
    new boss_solakar_flamewreath();
    new npc_rookery_hatcher();
}
Referenced by AddEasternKingdomsScripts().
AddSC_boss_sulfuron()
void AddSC_boss_sulfuron ()
{
    new boss_sulfuron();
    new npc_flamewaker_priest();
}
Referenced by AddEasternKingdomsScripts().
AddSC_boss_terestian_illhoof()
void AddSC_boss_terestian_illhoof ()
{
    RegisterKarazhanCreatureAI(boss_terestian_illhoof);
    RegisterKarazhanCreatureAI(npc_kilrek);
    RegisterKarazhanCreatureAI(npc_demon_chain);
}
References RegisterKarazhanCreatureAI.
Referenced by AddEasternKingdomsScripts().
AddSC_boss_thebeast()
void AddSC_boss_thebeast ()
{
    new boss_the_beast();
    new at_trigger_the_beast_movement();
    new at_the_beast_room();
}
Referenced by AddEasternKingdomsScripts().
AddSC_boss_thekal()
void AddSC_boss_thekal ()
{
    RegisterCreatureAI(boss_thekal);
    RegisterCreatureAI(npc_zealot_lorkhan);
    RegisterCreatureAI(npc_zealot_zath);
}
References RegisterCreatureAI.
Referenced by AddEasternKingdomsScripts().
AddSC_boss_tomb_of_seven()
void AddSC_boss_tomb_of_seven ()
{
    new boss_gloomrel();
    new boss_doomrel();
}
Referenced by AddEasternKingdomsScripts().
AddSC_boss_urok_doomhowl()
void AddSC_boss_urok_doomhowl ()
{
    new boss_urok_doomhowl();
}
Referenced by AddEasternKingdomsScripts().
AddSC_boss_vaelastrasz()
void AddSC_boss_vaelastrasz ()
{
    new boss_vaelastrasz();
    RegisterSpellScript(spell_vael_burning_adrenaline);
}
References RegisterSpellScript.
Referenced by AddEasternKingdomsScripts().
AddSC_boss_vanndar()
void AddSC_boss_vanndar ()
{
    new boss_vanndar;
}
Referenced by AddEasternKingdomsScripts().
AddSC_boss_venoxis()
void AddSC_boss_venoxis ()
{
    RegisterCreatureAI(boss_venoxis);
}
References RegisterCreatureAI.
Referenced by AddEasternKingdomsScripts().
AddSC_boss_vexallus()
void AddSC_boss_vexallus ()
{
    RegisterMagistersTerraceCreatureAI(boss_vexallus);
}
References RegisterMagistersTerraceCreatureAI.
Referenced by AddEasternKingdomsScripts().
AddSC_boss_warmastervoone()
void AddSC_boss_warmastervoone ()
{
    new boss_warmaster_voone();
}
Referenced by AddEasternKingdomsScripts().
AddSC_boss_wushoolay()
void AddSC_boss_wushoolay ()
{
    new boss_wushoolay();
}
Referenced by AddEasternKingdomsScripts().
AddSC_boss_zuljin()
void AddSC_boss_zuljin ()
{
    RegisterZulAmanCreatureAI(boss_zuljin);
    RegisterZulAmanCreatureAI(npc_zuljin_vortex);
    RegisterSpellScript(spell_claw_rage_aura);
    RegisterSpellScript(spell_zuljin_zap);
}
References RegisterSpellScript, and RegisterZulAmanCreatureAI.
Referenced by AddEasternKingdomsScripts().
AddSC_bosses_opera()
void AddSC_bosses_opera ()
{
    RegisterKarazhanCreatureAI(boss_dorothee);
    RegisterKarazhanCreatureAI(boss_strawman);
    RegisterKarazhanCreatureAI(boss_tinhead);
    RegisterKarazhanCreatureAI(boss_roar);
    RegisterKarazhanCreatureAI(boss_crone);
    RegisterKarazhanCreatureAI(npc_tito);
    RegisterKarazhanCreatureAI(npc_cyclone);
    new npc_grandmother();
    RegisterKarazhanCreatureAI(boss_bigbadwolf);
    RegisterKarazhanCreatureAI(boss_julianne);
    RegisterKarazhanCreatureAI(boss_romulo);
}
References RegisterKarazhanCreatureAI.
Referenced by AddEasternKingdomsScripts().
AddSC_burning_steppes()
void AddSC_burning_steppes ()
{
    new npc_maredis_firestar();
}
Referenced by AddEasternKingdomsScripts().
AddSC_duskwood()
void AddSC_duskwood ()
{
    RegisterCreatureAI(boss_twilight_corrupter);
    new at_twilight_grove();
}
References RegisterCreatureAI.
Referenced by AddEasternKingdomsScripts().
AddSC_eastern_plaguelands()
void AddSC_eastern_plaguelands ()
{
    new npc_eris_hevenfire();
    new npc_balance_of_light_and_shadow();
    new npc_augustus_the_touched();
}
Referenced by AddEasternKingdomsScripts().
AddSC_elwynn_forest()
void AddSC_elwynn_forest ()
{
    RegisterCreatureAI(npc_cameron);
    RegisterCreatureAI(npc_supervisor_raelen);
    RegisterCreatureAI(npc_eastvale_peasent);
}
References RegisterCreatureAI.
Referenced by AddEasternKingdomsScripts().
AddSC_eversong_woods()
void AddSC_eversong_woods ()
{
    RegisterCreatureAI(npc_partygoer_pather);
    RegisterCreatureAI(npc_partygoer);
}
References RegisterCreatureAI.
Referenced by AddEasternKingdomsScripts().
AddSC_ghostlands()
void AddSC_ghostlands ()
{
    RegisterCreatureAI(npc_ranger_lilatha);
    RegisterCreatureAI(npc_sentinel_leader);
    RegisterCreatureAI(npc_sentinel_infiltrator);
}
References RegisterCreatureAI.
Referenced by AddEasternKingdomsScripts().
AddSC_hinterlands()
void AddSC_hinterlands ()
{
    new npc_rinji();
}
Referenced by AddEasternKingdomsScripts().
AddSC_instance_blackrock_depths()
void AddSC_instance_blackrock_depths ()
{
    new instance_blackrock_depths();
}
Referenced by AddEasternKingdomsScripts().
AddSC_instance_blackrock_spire()
void AddSC_instance_blackrock_spire ()
{
    new instance_blackrock_spire();
    new at_dragonspire_hall();
    new at_blackrock_stadium();
    new go_father_flame();
    new near_scarshield_infiltrator();
    new at_scarshield_infiltrator();
    RegisterSpellScript(spell_blackrock_spire_call_of_vaelastrasz);
    new npc_vaelastrasz_the_red();
}
References RegisterSpellScript.
Referenced by AddEasternKingdomsScripts().
AddSC_instance_blackwing_lair()
void AddSC_instance_blackwing_lair ()
{
    new instance_blackwing_lair();
    RegisterSpellScript(spell_bwl_shadowflame);
    new at_orb_of_command();
}
References RegisterSpellScript.
Referenced by AddEasternKingdomsScripts().
AddSC_instance_deadmines()
void AddSC_instance_deadmines ()
{
    new instance_deadmines();
}
Referenced by AddEasternKingdomsScripts().
AddSC_instance_gnomeregan()
void AddSC_instance_gnomeregan ()
{
    new instance_gnomeregan();
    new npc_kernobee();
    RegisterSpellScript(spell_gnomeregan_radiation_bolt);
}
References RegisterSpellScript.
Referenced by AddEasternKingdomsScripts().
AddSC_instance_karazhan()
void AddSC_instance_karazhan ()
{
    new instance_karazhan();
    RegisterSpellScript(spell_karazhan_brittle_bones_aura);
    RegisterSpellScript(spell_karazhan_overload_aura);
    RegisterSpellScript(spell_karazhan_blink);
}
References RegisterSpellScript.
Referenced by AddEasternKingdomsScripts().
AddSC_instance_magisters_terrace()
void AddSC_instance_magisters_terrace ()
{
    new instance_magisters_terrace();
}
Referenced by AddEasternKingdomsScripts().
AddSC_instance_molten_core()
void AddSC_instance_molten_core ()
{
    new instance_molten_core();
}
Referenced by AddEasternKingdomsScripts().
AddSC_instance_scarlet_monastery()
void AddSC_instance_scarlet_monastery ()
{
    new instance_scarlet_monastery();
}
Referenced by AddEasternKingdomsScripts().
AddSC_instance_scholomance()
void AddSC_instance_scholomance ()
{
    new instance_scholomance();
    RegisterSpellScript(spell_scholomance_fixate_aura);
    RegisterSpellScript(spell_scholomance_boon_of_life_aura);
    new npc_scholomance_occultist();
}
References RegisterSpellScript.
Referenced by AddEasternKingdomsScripts().
AddSC_instance_shadowfang_keep()
void AddSC_instance_shadowfang_keep ()
{
    new instance_shadowfang_keep();
    RegisterSpellScript(spell_shadowfang_keep_haunting_spirits_aura);
    RegisterSpellScript(spell_shadowfang_keep_forsaken_skills_aura);
}
References RegisterSpellScript.
Referenced by AddEasternKingdomsScripts().
AddSC_instance_stratholme()
void AddSC_instance_stratholme ()
{
    new instance_stratholme();
}
Referenced by AddEasternKingdomsScripts().
AddSC_instance_sunken_temple()
void AddSC_instance_sunken_temple ()
{
    new instance_sunken_temple();
    new at_malfurion_stormrage();
    RegisterSpellScript(spell_temple_of_atal_hakkar_hex_of_jammal_an_aura);
    RegisterSpellScript(spell_temple_of_atal_hakkar_awaken_the_soulflayer);
}
References RegisterSpellScript.
Referenced by AddEasternKingdomsScripts().
AddSC_instance_sunwell_plateau()
void AddSC_instance_sunwell_plateau ()
{
    new instance_sunwell_plateau();
    RegisterSpellScript(spell_cataclysm_breath);
    RegisterSunwellPlateauCreatureAI(npc_sunblade_arch_mage);
    RegisterSunwellPlateauCreatureAI(npc_sunblade_scout);
    RegisterSpellScriptWithArgs(spell_sunwell_teleport, "spell_teleport_to_apex_point", SPELL_TELEPORT_TO_APEX_POINT);
    RegisterSpellScriptWithArgs(spell_sunwell_teleport, "spell_teleport_to_witchs_sanctum", SPELL_TELEPORT_TO_WITCHS_SANCTUM);
    RegisterSpellScriptWithArgs(spell_sunwell_teleport, "spell_teleport_to_sunwell_plateau", SPELL_TELEPORT_TO_SUNWELL_PLATEAU);
    RegisterSpellScript(spell_spell_fury_aura);
}
References RegisterSpellScript, RegisterSpellScriptWithArgs, RegisterSunwellPlateauCreatureAI, SPELL_TELEPORT_TO_APEX_POINT, SPELL_TELEPORT_TO_SUNWELL_PLATEAU, and SPELL_TELEPORT_TO_WITCHS_SANCTUM.
Referenced by AddEasternKingdomsScripts().
AddSC_instance_the_stockade()
void AddSC_instance_the_stockade ()
{
    new instance_the_stockade();
}
Referenced by AddEasternKingdomsScripts().
AddSC_instance_uldaman()
void AddSC_instance_uldaman ()
{
    new instance_uldaman();
    RegisterSpellScript(spell_uldaman_sub_boss_agro_keepers);
    RegisterSpellScript(spell_uldaman_stoned_aura);
    RegisterSpellScript(spell_uldaman_boss_agro_archaedas);
}
References RegisterSpellScript.
Referenced by AddEasternKingdomsScripts().
AddSC_instance_zulaman()
void AddSC_instance_zulaman ()
{
    new instance_zulaman();
}
Referenced by AddEasternKingdomsScripts().
AddSC_instance_zulgurub()
void AddSC_instance_zulgurub ()
{
    new instance_zulgurub();
    RegisterGameObjectAI(go_brazier_of_madness);
}
References RegisterGameObjectAI.
Referenced by AddEasternKingdomsScripts().
AddSC_isle_of_queldanas()
void AddSC_isle_of_queldanas ()
{
    new npc_bh_thalorien_dawnseeker();
    RegisterSpellScript(spell_bh_cleanse_quel_delar);
    new npc_grand_magister_rommath();
    new npc_greengill_slave();
    RegisterSpellScript(spell_gen_weapon_coating_enchant);
}
References RegisterSpellScript.
Referenced by AddEasternKingdomsScripts().
AddSC_karazhan()
void AddSC_karazhan ()
{
    new npc_barnes();
    new npc_image_of_medivh();
    new at_karazhan_side_entrance();
    RegisterSpellScript(spell_karazhan_temptation);
    RegisterSpellScript(spell_karazhan_wrath_titans_stacker);
    RegisterSpellScript(spell_karazhan_wrath_titans_aura);
}
References RegisterSpellScript.
Referenced by AddEasternKingdomsScripts().
AddSC_molten_core()
void AddSC_molten_core ()
{
    // Creatures
    new npc_mc_core_hound();
    RegisterCreatureAI(npc_lava_spawn);
    // Spells
    RegisterSpellScript(spell_mc_play_dead_aura);
}
References RegisterCreatureAI, and RegisterSpellScript.
Referenced by AddEasternKingdomsScripts().
AddSC_redridge_mountains()
void AddSC_redridge_mountains ()
{
    new npc_corporal_keeshan();
}
Referenced by AddEasternKingdomsScripts().
AddSC_silverpine_forest()
void AddSC_silverpine_forest ()
{
    new npc_deathstalker_erland();
    RegisterCreatureAI(npc_deathstalker_fearleia);
    new npc_ravenclaw_apparition();
}
References RegisterCreatureAI.
Referenced by AddEasternKingdomsScripts().
AddSC_stormwind_city()
void AddSC_stormwind_city ()
{
    new npc_tyrion();
    new npc_tyrion_spybot();
    new npc_lord_gregor_lescovar();
    new npc_marzon_silent_blade();
    new npc_king_varian_wrynn();
}
Referenced by AddEasternKingdomsScripts().
AddSC_the_scarlet_enclave()
void AddSC_the_scarlet_enclave ()
{
    new npc_valkyr_battle_maiden();
}
Referenced by AddEasternKingdomsScripts().
AddSC_the_scarlet_enclave_c1()
void AddSC_the_scarlet_enclave_c1 ()
{
    RegisterSpellScript(spell_q12641_death_comes_from_on_high_summon_ghouls);
    RegisterSpellScript(spell_q12641_death_comes_from_on_high_recall_eye);
    new npc_death_knight_initiate();
    RegisterSpellScript(spell_item_gift_of_the_harvester);
    RegisterSpellScript(spell_q12698_the_gift_that_keeps_on_giving);
    new npc_scarlet_ghoul();
    new npc_dkc1_gothik();
    new npc_scarlet_cannon();
    new npc_unworthy_initiate();
    new npc_unworthy_initiate_anchor();
    new go_acherus_soul_prison();
    new npc_scarlet_miner();
    new npc_scarlet_miner_cart();
    new go_inconspicuous_mine_car();
    RegisterSpellScript(spell_death_knight_initiate_visual);
    RegisterSpellScript(spell_lich_king_whisper);
    RegisterSpellScript(spell_lich_king_vo_blocker);
}
References RegisterSpellScript.
Referenced by AddEasternKingdomsScripts().
AddSC_the_scarlet_enclave_c2()
void AddSC_the_scarlet_enclave_c2 ()
{
    new npc_scarlet_courier();
    new npc_koltira_deathweaver();
    new npc_a_special_surprise();
    new npc_acherus_necromancer();
    new npc_gothik_the_harvester();
    RegisterSpellScript(spell_chapter2_persuasive_strike);
}
References RegisterSpellScript.
Referenced by AddEasternKingdomsScripts().
AddSC_the_scarlet_enclave_c3()
void AddSC_the_scarlet_enclave_c3 ()
{
    RegisterSpellScript(spell_q12779_an_end_to_all_things);
    RegisterSpellScript(spell_q12779_an_end_to_all_things_devour_aura);
}
References RegisterSpellScript.
Referenced by AddEasternKingdomsScripts().
AddSC_the_scarlet_enclave_c5()
void AddSC_the_scarlet_enclave_c5 ()
{
    new npc_highlord_darion_mograine();
    RegisterSpellScript(spell_chapter5_light_of_dawn_aura);
    RegisterSpellScript(spell_chapter5_return_to_capital);
}
References RegisterSpellScript.
Referenced by AddEasternKingdomsScripts().
AddSC_undercity()
void AddSC_undercity ()
{
    new npc_lady_sylvanas_windrunner();
    new npc_highborne_lamenter();
    new npc_parqual_fintallas();
    new npc_varian_wrynn();
    new npc_thrall_bfu();
    new npc_jaina_proudmoore_bfu();
    new npc_lady_sylvanas_windrunner_bfu();
    new boss_blight_worm();
    RegisterSpellScript(spell_blight_worm_ingest);
}
References RegisterSpellScript.
Referenced by AddEasternKingdomsScripts().
AddSC_western_plaguelands()
void AddSC_western_plaguelands ()
{
    new npc_the_scourge_cauldron();
    new npc_andorhal_tower();
}
Referenced by AddEasternKingdomsScripts().
AddSC_westfall()
void AddSC_westfall ()
{
    new npc_daphne_stilwell();
}
Referenced by AddEasternKingdomsScripts().
AddSC_zulaman()
void AddSC_zulaman ()
{
    RegisterZulAmanCreatureAI(npc_forest_frog);
    new npc_zulaman_hostage();
    RegisterZulAmanCreatureAI(npc_harrison_jones);
    RegisterSpellScript(spell_ritual_of_power);
    RegisterZulAmanCreatureAI(npc_amanishi_lookout);
    RegisterZulAmanCreatureAI(npc_eagle_trash_aggro_trigger);
    RegisterZulAmanCreatureAI(npc_amanishi_tempest);
    RegisterZulAmanCreatureAI(npc_amanishi_scout);
    RegisterSpellScript(spell_alert_drums);
    RegisterSpellScript(spell_summon_amanishi_sentries);
    RegisterSpellScript(spell_call_of_the_beast);
}
References RegisterSpellScript, and RegisterZulAmanCreatureAI.
Referenced by AddEasternKingdomsScripts().
AddSC_zulgurub()
void AddSC_zulgurub ()
{
    RegisterSpellScript(spell_axe_flurry);
}
References RegisterSpellScript.
Referenced by AddEasternKingdomsScripts().