AzerothCore Doxygen
Eluna_AllCreatureScript Class Reference
Public Member Functions
Eluna_AllCreatureScript ()
bool CanCreatureGossipHello (Player *player, Creature *creature) override
This hook called when a player opens a gossip dialog with the creature.
bool CanCreatureGossipSelect (Player *player, Creature *creature, uint32 sender, uint32 action) override
This hook called when a player selects a gossip item in the creature's gossip menu.
bool CanCreatureGossipSelectCode (Player *player, Creature *creature, uint32 sender, uint32 action, const char *code) override
This hook called when a player selects a gossip with a code in the creature's gossip menu.
void OnCreatureAddWorld (Creature *creature) override
This hook runs after add creature in world.
void OnCreatureRemoveWorld (Creature *creature) override
This hook runs after remove creature in world.
bool CanCreatureQuestAccept (Player *player, Creature *creature, Quest const *quest) override
bool CanCreatureQuestReward (Player *player, Creature *creature, Quest const *quest, uint32 opt) override
CreatureAI * GetCreatureAI (Creature *creature) const override
Public Member Functions inherited from AllCreatureScript
virtual void OnAllCreatureUpdate (Creature *, uint32)
virtual void OnBeforeCreatureSelectLevel (const CreatureTemplate *, Creature *, uint8 &)
virtual void Creature_SelectLevel (const CreatureTemplate *, Creature *)
virtual void OnCreatureSaveToDB (Creature *)
This hook runs after creature has been saved to DB.
virtual void OnFfaPvpStateUpdate (Creature *, bool)
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
uint16 GetTotalAvailableHooks ()
Additional Inherited Members
Protected Member Functions inherited from AllCreatureScript
AllCreatureScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name, uint16 totalAvailableHooks=0)
virtual ~ScriptObject ()=default
Detailed Description
Constructor & Destructor Documentation
Eluna_AllCreatureScript()
Eluna_AllCreatureScript::Eluna_AllCreatureScript () inline
: AllCreatureScript("Eluna_AllCreatureScript") { }
Member Function Documentation
CanCreatureGossipHello()
bool Eluna_AllCreatureScript::CanCreatureGossipHello (Player * , Creature *) inline override virtual
This hook called when a player opens a gossip dialog with the creature.
Parameters
player Contains information about the Player
creature Contains information about the Creature
Returns
False if you want to continue, true if you want to disable
Reimplemented from AllCreatureScript.
    {
        if (sEluna->OnGossipHello(player, creature))
            return true;
        return false;
    }
References sEluna.
CanCreatureGossipSelect()
bool Eluna_AllCreatureScript::CanCreatureGossipSelect (Player * , Creature * , uint32 , uint32) inline override virtual
This hook called when a player selects a gossip item in the creature's gossip menu.
Parameters
player Contains information about the Player
creature Contains information about the Creature
sender Contains information about the sender type
action Contains information about the action id
Returns
False if you want to continue, true if you want to disable
Reimplemented from AllCreatureScript.
    {
        if (sEluna->OnGossipSelect(player, creature, sender, action))
            return true;
        return false;
    }
References sEluna.
CanCreatureGossipSelectCode()
bool Eluna_AllCreatureScript::CanCreatureGossipSelectCode (Player * , Creature * , uint32 , uint32 , const char *) inline override virtual
This hook called when a player selects a gossip with a code in the creature's gossip menu.
Parameters
player Contains information about the Player
creature Contains information about the Creature
sender Contains information about the sender type
action Contains information about the action id
code Contains information about the code entered
Returns
True if you want to continue, false if you want to disable
Reimplemented from AllCreatureScript.
    {
        if (sEluna->OnGossipSelectCode(player, creature, sender, action, code))
            return true;
        return false;
    }
References sEluna.
CanCreatureQuestAccept()
bool Eluna_AllCreatureScript::CanCreatureQuestAccept (Player * player, Creature * creature, Quest const * quest) inline override virtual
Reimplemented from AllCreatureScript.
    {
        sEluna->OnQuestAccept(player, creature, quest);
        return false;
    }
References sEluna.
CanCreatureQuestReward()
bool Eluna_AllCreatureScript::CanCreatureQuestReward (Player * player, Creature * creature, Quest const * quest, uint32 opt) inline override virtual
Reimplemented from AllCreatureScript.
    {
        if (sEluna->OnQuestReward(player, creature, quest, opt))
        {
            ClearGossipMenuFor(player);
            return true;
        }
        return false;
    }
References ClearGossipMenuFor(), and sEluna.
GetCreatureAI()
CreatureAI * Eluna_AllCreatureScript::GetCreatureAI (Creature * creature) const inline override virtual
Reimplemented from AllCreatureScript.
    {
        if (CreatureAI* luaAI = sEluna->GetAI(creature))
            return luaAI;
        return nullptr;
    }
References sEluna.
OnCreatureAddWorld()
void Eluna_AllCreatureScript::OnCreatureAddWorld (Creature *) inline override virtual
This hook runs after add creature in world.
Parameters
creature Contains information about the Creature
Reimplemented from AllCreatureScript.
    {
        sEluna->OnAddToWorld(creature);
        if (creature->IsGuardian() && creature->ToTempSummon() && creature->ToTempSummon()->GetSummonerGUID().IsPlayer())
            sEluna->OnPetAddedToWorld(creature->ToTempSummon()->GetSummonerUnit()->ToPlayer(), creature);
    }
References TempSummon::GetSummonerGUID(), TempSummon::GetSummonerUnit(), Unit::IsGuardian(), ObjectGuid::IsPlayer(), sEluna, Object::ToPlayer(), and Unit::ToTempSummon().
OnCreatureRemoveWorld()
void Eluna_AllCreatureScript::OnCreatureRemoveWorld (Creature *) inline override virtual
This hook runs after remove creature in world.
Parameters
creature Contains information about the Creature
Reimplemented from AllCreatureScript.
    {
        sEluna->OnRemoveFromWorld(creature);
    }
References sEluna.
The documentation for this class was generated from the following file:
mod-eluna/src/ElunaLuaEngine_SC.cpp