AzerothCore Doxygen
rbac::RBACPermission Class Reference
#include "RBAC.h"
Public Member Functions
RBACPermission (uint32 id=0, std::string const &name="")
std::string const & GetName () const
Gets the Name of the Object.
uint32 GetId () const
Gets the Id of the Object.
RBACPermissionContainer const & GetLinkedPermissions () const
Gets the Permissions linked to this permission.
void AddLinkedPermission (uint32 id)
Adds a new linked Permission.
void RemoveLinkedPermission (uint32 id)
Removes a linked Permission.
Private Attributes
uint32 _id
std::string _name
‍id of the object
RBACPermissionContainer _perms
‍name of the object
Detailed Description
Constructor & Destructor Documentation
RBACPermission()
rbac::RBACPermission::RBACPermission (uint32 id = 0, std::string const & name = "") inline
                                                             :
        _id(id), _name(name), _perms() { }
Member Function Documentation
AddLinkedPermission()
void rbac::RBACPermission::AddLinkedPermission (uint32 id) inline
Adds a new linked Permission.
{ _perms.insert(id); }
Referenced by AccountMgr::LoadRBAC().
GetId()
uint32 rbac::RBACPermission::GetId () const inline
Gets the Id of the Object.
{ return _id; }
Referenced by rbac_commandscript::HandleRBACListPermissionsCommand(), and rbac_commandscript::HandleRBACPermListCommand().
GetLinkedPermissions()
RBACPermissionContainer const & rbac::RBACPermission::GetLinkedPermissions () const inline
Gets the Permissions linked to this permission.
{ return _perms; }
Referenced by rbac::RBACData::ExpandPermissions(), and rbac_commandscript::HandleRBACListPermissionsCommand().
GetName()
std::string const & rbac::RBACPermission::GetName () const inline
Gets the Name of the Object.
{ return _name; }
Referenced by rbac_commandscript::HandleRBACListPermissionsCommand(), rbac_commandscript::HandleRBACPermDenyCommand(), rbac_commandscript::HandleRBACPermGrantCommand(), rbac_commandscript::HandleRBACPermListCommand(), and rbac_commandscript::HandleRBACPermRevokeCommand().
RemoveLinkedPermission()
void rbac::RBACPermission::RemoveLinkedPermission (uint32 id) inline
Removes a linked Permission.
{ _perms.erase(id); }
Member Data Documentation
_id
uint32 rbac::RBACPermission::_id private
_name
std::string rbac::RBACPermission::_name private
‍id of the object
_perms
RBACPermissionContainer rbac::RBACPermission::_perms private
‍name of the object
The documentation for this class was generated from the following file:
azerothcore-wotlk/src/server/game/Accounts/RBAC.h