AzerothCore Doxygen
EventProcessor Class Reference
#include "EventProcessor.h"
Public Member Functions
EventProcessor ()=default
~EventProcessor ()
void Update (uint32 p_time)
void KillAllEvents (bool force)
void AddEvent (BasicEvent *Event, uint64 e_time, bool set_addtime=true, uint8 eventGroup=0)
template<typename T >
is_lambda_event< T > AddEvent (T &&event, Milliseconds e_time, bool set_addtime=true, uint8 eventGroup=0)
void AddEventAtOffset (BasicEvent *event, Milliseconds offset, uint8 eventGroup=0)
template<typename T >
is_lambda_event< T > AddEventAtOffset (T &&event, Milliseconds offset, uint8 eventGroup=0)
void AddEventAtOffset (BasicEvent *event, Milliseconds offset, Milliseconds offset2, uint8 eventGroup=0)
template<typename T >
is_lambda_event< T > AddEventAtOffset (T &&event, Milliseconds offset, Milliseconds offset2, uint8 eventGroup=0)
void ModifyEventTime (BasicEvent *event, Milliseconds newTime)
uint64 CalculateTime (uint64 t_offset) const
uint64 CalculateQueueTime (uint64 delay) const
void CancelEventGroup (uint8 group)
bool HasEvents () const
Protected Attributes
uint64 m_time {0}
EventList m_events
bool m_aborting
Detailed Description
Constructor & Destructor Documentation
EventProcessor()
EventProcessor::EventProcessor () default
~EventProcessor()
EventProcessor::~EventProcessor ()
{
    KillAllEvents(true);
}
References KillAllEvents().
Member Function Documentation
AddEvent() [1/2]
void EventProcessor::AddEvent (BasicEvent * Event, uint64 e_time, bool set_addtime = true, uint8 eventGroup = 0)
{
    if (set_addtime)
        Event->m_addTime = m_time;
    Event->m_execTime = e_time;
    Event->m_eventGroup = eventGroup;
    m_events.emplace(e_time, Event);
}
References m_events, and m_time.
Referenced by AddEventAtOffset(), AddEventAtOffset(), Unit::CastDelayedSpellWithPeriodicAmount(), SpellEvent::Execute(), and Update().
AddEvent() [2/2]
template<typename T > is_lambda_event< T > EventProcessor::AddEvent (T && event, Milliseconds e_time, bool set_addtime = true, uint8 eventGroup = 0) inline
{ AddEvent(new LambdaBasicEvent<T>(std::move(event)), e_time.count(), set_addtime, eventGroup); }
References AddEvent().
Referenced by AddEvent().
AddEventAtOffset() [1/4]
void EventProcessor::AddEventAtOffset (BasicEvent * event, Milliseconds offset, Milliseconds offset2, uint8 eventGroup = 0) inline
{ AddEvent(event, CalculateTime(randtime(offset, offset2).count()), true, eventGroup); }
References AddEvent(), CalculateTime(), and randtime().
AddEventAtOffset() [2/4]
void EventProcessor::AddEventAtOffset (BasicEvent * event, Milliseconds offset, uint8 eventGroup = 0) inline
{ AddEvent(event, CalculateTime(offset.count()), true, eventGroup); }
References AddEvent(), and CalculateTime().
Referenced by Unit::_ExitVehicle(), at_hol_hall_of_watchers::_OnTrigger(), npc_q24545_wretched_ghoul::npc_q24545_wretched_ghoulAI::Activate(), BattlegroundQueue::AddEvent(), CharmInfo::AddSpellToActionBar(), Spell::AddUnitTarget(), spell_sindragosa_ice_tomb_trap_aura::AfterApply(), Creature::CallAssistance(), boss_high_nethermancer_zerevor::CastDampenMagicIfPossible(), boss_murmur::CastSuppressionOOC(), boss_romulo::DamageTaken(), boss_muru::DamageTaken(), boss_felblood_kaelthas::DamageTaken(), boss_the_lich_king::boss_the_lich_kingAI::DamageTaken(), boss_julianne::DoAction(), boss_baltharus_the_warborn::boss_baltharus_the_warbornAI::DoAction(), boss_prince_keleseth_icc::boss_prince_kelesethAI::DoAction(), boss_prince_taldaram_icc::boss_prince_taldaramAI::DoAction(), boss_prince_valanar_icc::boss_prince_valanarAI::DoAction(), boss_sindragosa::boss_sindragosaAI::DoAction(), npc_spinestalker::npc_spinestalkerAI::DoAction(), npc_rimefang::npc_rimefangAI::DoAction(), npc_green_dragon_combat_trigger::npc_green_dragon_combat_triggerAI::DoAction(), boss_felblood_kaelthas::DoAction(), boss_akilzon::DoAction(), boss_cthun::DoAction(), boss_krik_thir::boss_krik_thirAI::DoAction(), boss_kalecgos::DoAction(), boss_illidan_stormrage::DoAction(), npc_akama_illidan::DoAction(), npc_maiev_illidan::DoAction(), npc_blade_of_azzinoth::DoAction(), boss_ouro::Emerge(), boss_zuljin::EnterPhase(), BattlegroundAV::EventPlayerAssaultsPoint(), BattlegroundIC::EventPlayerClickedOnFlag(), BattlegroundEY::EventTeamLostPoint(), BattleExperienceEvent::Execute(), UtherBatteredHiltEvent::Execute(), TriggerWickedSpirit::Execute(), lapseTeleport::Execute(), PartyTimeEmoteEvent::Execute(), npc_xt002_boombot::npc_xt002_boombotAI::Explode(), Creature::ForcedDespawn(), spell_item_party_time::HandleEffectApply(), spell_chapter2_persuasive_strike::HandleHit(), spell_alar_flame_quills::HandlePeriodic(), WorldSession::HandlePlayerLoginFromDB(), spell_ayamiss_swarmer_teleport_trigger::HandleScript(), boss_akilzon::HandleStormSequence(), boss_kiljaeden::InitializeAI(), boss_ambassador_hellmaw::InitializeAI(), npc_pet_mage_mirror_image::InitializeAI(), Totem::InitSummon(), npc_blade_of_azzinoth::IsSummonedBy(), npc_flame_of_azzinoth::IsSummonedBy(), npc_demonic_vapor::IsSummonedBy(), npc_maiev_illidan::IsSummonedBy(), npc_swarm_scarab::npc_swarm_scarabAI::JustDied(), npc_nerubian_burrower::npc_nerubian_burrowerAI::JustDied(), npc_gunship::npc_gunshipAI::JustDied(), npc_xt002_boombot::npc_xt002_boombotAI::JustDied(), npc_q24545_wretched_ghoul::npc_q24545_wretched_ghoulAI::JustDied(), boss_akilzon::JustEngagedWith(), boss_zuljin::JustEngagedWith(), boss_keleseth::JustEngagedWith(), npc_flame_of_azzinoth::JustEngagedWith(), boss_essence_of_suffering::boss_essence_of_sufferingAI::JustEngagedWith(), boss_swamplord_muselek::JustEngagedWith(), boss_felmyst::JustEngagedWith(), boss_muru::JustEngagedWith(), boss_janalai::JustEngagedWith(), boss_anubrekhan::boss_anubrekhanAI::JustEngagedWith(), boss_gurtogg_bloodboil::JustEngagedWith(), boss_illidan_stormrage::JustEngagedWith(), boss_mother_shahraz::JustEngagedWith(), boss_najentus::JustEngagedWith(), npc_akama_illidan::JustReachedHome(), npc_kiljaeden_controller::JustSummoned(), boss_kiljaeden::JustSummoned(), boss_hazzarah::JustSummoned(), boss_baltharus_the_warborn::boss_baltharus_the_warbornAI::JustSummoned(), boss_drakkari_colossus::boss_drakkari_colossusAI::JustSummoned(), boss_prince_valanar_icc::boss_prince_valanarAI::JustSummoned(), boss_sindragosa::boss_sindragosaAI::JustSummoned(), boss_the_lich_king::boss_the_lich_kingAI::JustSummoned(), boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI::JustSummoned(), npc_risen_archmage::npc_risen_archmageAI::JustSummoned(), boss_algalon_the_observer::boss_algalon_the_observerAI::JustSummoned(), boss_reliquary_of_souls::boss_reliquary_of_soulsAI::JustSummoned(), boss_krik_thir::boss_krik_thirAI::KilledUnit(), boss_gurtogg_bloodboil::KilledUnit(), boss_illidan_stormrage::KilledUnit(), boss_essence_of_suffering::boss_essence_of_sufferingAI::KilledUnit(), boss_essence_of_desire::boss_essence_of_desireAI::KilledUnit(), boss_essence_of_anger::boss_essence_of_angerAI::KilledUnit(), Creature::ModifyThreatPercentTemp(), boss_ebonroc::boss_ebonrocAI::MovementInform(), npc_koltira_deathweaver::npc_koltira_deathweaverAI::MovementInform(), boss_zuljin::MovementInform(), boss_captain_skarloc::MovementInform(), boss_ayamiss::MovementInform(), boss_illidan_stormrage::MovementInform(), npc_akama_illidan::MovementInform(), boss_essence_of_suffering::boss_essence_of_sufferingAI::MovementInform(), boss_essence_of_desire::boss_essence_of_desireAI::MovementInform(), boss_felmyst::MovementInform(), gunship_npc_AI::MovementInform(), npc_gunship_boarding_addAI::MovementInform(), boss_ghazan::MovementInform(), BattlegroundAB::NodeDeoccupied(), spell_halion_twilight_realm_aura::OnApply(), boss_taldaram::OnAuraRemove(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnCreatureCreate(), go_main_chambers_access_panel::OnGossipHello(), spell_halion_leave_twilight_realm_aura::OnRemove(), spell_q12937_relief_for_the_fallen::OnRemove(), at_cthun_stomach_exit::OnTrigger(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnUnitDeath(), npc_hyldsmeet_protodrake::npc_hyldsmeet_protodrakeAI::PassengerBoarded(), boss_anetheron::PathEndReached(), boss_rage_winterchill::PathEndReached(), npc_hyjal_ground_trash::PathEndReached(), npc_hyjal_frost_wyrm::PathEndReached(), boss_ambassador_hellmaw::PathEndReached(), npc_akama_illidan::PathEndReached(), npc_hyjal_gargoyle::PathEndReached(), npc_hive_zara_swarmer::PathEndReached(), boss_reliquary_of_souls::boss_reliquary_of_soulsAI::PhaseTransitionSpawns(), Spell::prepare(), SmartScript::ProcessAction(), boss_vexallus::Reset(), boss_kiljaeden::Reset(), boss_entropius::Reset(), npc_dark_fiend::Reset(), npc_singularity::Reset(), boss_runemaster_molgeim::boss_runemaster_molgeimAI::Reset(), boss_alar::ScheduleAbilities(), boss_illidan_stormrage::ScheduleAbilities(), BossAI::ScheduleEnrageTimer(), boss_gal_darah::ScheduleEvents(), npc_gunship_boarding_addAI::SetData(), boss_gal_darah::SpellHit(), npc_koltira_deathweaver::npc_koltira_deathweaverAI::StartEvent(), boss_felmyst::StartIntro(), npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::SummonedCreatureDies(), boss_hydross_the_unstable::SummonMovementInform(), boss_hydross_the_unstable::SummonTaintedElementalOOC(), CreatureAI::Talk(), TempSummon::UnSummon(), Totem::UnSummon(), spell_illidari_council_deadly_strike_aura::Update(), npc_kalecgos_kj::UpdateAI(), boss_anomalus::UpdateAI(), and npc_dark_fiend::UpdateAI().
AddEventAtOffset() [3/4]
template<typename T > is_lambda_event< T > EventProcessor::AddEventAtOffset (T && event, Milliseconds offset, Milliseconds offset2, uint8 eventGroup = 0) inline
{ AddEventAtOffset(new LambdaBasicEvent<T>(std::move(event)), offset, offset2, eventGroup); };
References AddEventAtOffset().
Referenced by AddEventAtOffset().
AddEventAtOffset() [4/4]
template<typename T > is_lambda_event< T > EventProcessor::AddEventAtOffset (T && event, Milliseconds offset, uint8 eventGroup = 0) inline
{ AddEventAtOffset(new LambdaBasicEvent<T>(std::move(event)), offset, eventGroup); };
References AddEventAtOffset().
Referenced by AddEventAtOffset().
CalculateQueueTime()
uint64 EventProcessor::CalculateQueueTime (uint64 delay) const
{
    return CalculateTime(delay - (m_time % delay));
}
References CalculateTime(), and m_time.
Referenced by Unit::CastDelayedSpellWithPeriodicAmount().
CalculateTime()
uint64 EventProcessor::CalculateTime (uint64 t_offset) const
{
    return (m_time + t_offset);
}
References m_time.
Referenced by AddEventAtOffset(), AddEventAtOffset(), CalculateQueueTime(), and Update().
CancelEventGroup()
void EventProcessor::CancelEventGroup (uint8 group)
{
    for (auto itr = m_events.begin(); itr != m_events.end();)
    {
        if (itr->second->m_eventGroup != group)
        {
            ++itr;
            continue;
        }
        // Abort events which weren't aborted already
        if (!itr->second->IsAborted())
        {
            itr->second->SetAborted();
            itr->second->Abort(m_time);
        }
        delete itr->second;
        itr = m_events.erase(itr);
    }
}
References m_events, and m_time.
Referenced by boss_murmur::CastSuppressionOOC(), boss_illidan_stormrage::DoAction(), boss_illidan_stormrage::EnterEvadeMode(), boss_mother_shahraz::JustDied(), boss_najentus::JustDied(), boss_zuljin::JustEngagedWith(), boss_murmur::JustEngagedWith(), boss_hydross_the_unstable::JustEngagedWith(), boss_janalai::Reset(), boss_illidan_stormrage::Reset(), boss_mother_shahraz::Reset(), boss_najentus::Reset(), and boss_illidan_stormrage::ScheduleAbilities().
HasEvents()
bool EventProcessor::HasEvents () const inline
{ return !m_events.empty(); }
References m_events.
KillAllEvents()
void EventProcessor::KillAllEvents (bool force)
{
    // first, abort all existing events
    for (auto itr = m_events.begin(); itr != m_events.end();)
    {
        // Abort events which weren't aborted already
        if (!itr->second->IsAborted())
        {
            itr->second->SetAborted();
            itr->second->Abort(m_time);
        }
        // Skip non-deletable events when we are
        // not forcing the event cancellation.
        if (!force && !itr->second->IsDeletable())
        {
            ++itr;
            continue;
        }
        delete itr->second;
        if (force)
            ++itr; // Clear the whole container when forcing
        else
            itr = m_events.erase(itr);
    }
    if (force)
        m_events.clear();
}
References m_events, and m_time.
Referenced by BossAI::_Reset(), WorldObject::CleanupsBeforeDelete(), npc_q24545_wretched_ghoul::npc_q24545_wretched_ghoulAI::DoAction(), boss_akilzon::JustDied(), boss_felmyst::JustDied(), boss_loken::JustEngagedWith(), boss_krik_thir::boss_krik_thirAI::JustEngagedWith(), at_cthun_stomach_exit::OnTrigger(), npc_koltira_deathweaver::npc_koltira_deathweaverAI::Reset(), boss_brutallus::Reset(), boss_muru::Reset(), boss_akilzon::Reset(), boss_janalai::Reset(), boss_zuljin::Reset(), boss_anubrekhan::boss_anubrekhanAI::Reset(), npc_akama_illidan::Reset(), npc_maiev_illidan::Reset(), boss_alar::Reset(), NPCStaveQuestAI::ResetState(), Battleground::~Battleground(), BattlegroundQueue::~BattlegroundQueue(), and ~EventProcessor().
ModifyEventTime()
void EventProcessor::ModifyEventTime (BasicEvent * event, Milliseconds newTime)
{
    for (auto itr = m_events.begin(); itr != m_events.end(); ++itr)
    {
        if (itr->second != event)
            continue;
        event->m_execTime = newTime.count();
        m_events.erase(itr);
        m_events.emplace(newTime.count(), event);
        break;
    }
}
References m_events.
Referenced by Spell::RecalculateDelayMomentForDst().
Update()
void EventProcessor::Update (uint32 p_time)
{
    // update time
    m_time += p_time;
    // main event loop
    EventList::iterator i;
    while (((i = m_events.begin()) != m_events.end()) && i->first <= m_time)
    {
        // get and remove event from queue
        BasicEvent* event = i->second;
        m_events.erase(i);
        if (event->IsRunning())
        {
            if (event->Execute(m_time, p_time))
            {
                // completely destroy event if it is not re-added
                delete event;
            }
            continue;
        }
        if (event->IsAbortScheduled())
        {
            event->Abort(m_time);
            // Mark the event as aborted
            event->SetAborted();
        }
        if (event->IsDeletable())
        {
            delete event;
            continue;
        }
        // Reschedule non deletable events to be checked at
        // the next update tick
        AddEvent(event, CalculateTime(1), false);
    }
}
References BasicEvent::Abort(), AddEvent(), CalculateTime(), m_events, and m_time.
Referenced by Battleground::_ProcessResurrect(), WorldObject::Update(), and BattlegroundQueue::UpdateEvents().
Member Data Documentation
m_aborting
bool EventProcessor::m_aborting protected
m_events
EventList EventProcessor::m_events protected
Referenced by AddEvent(), CancelEventGroup(), HasEvents(), KillAllEvents(), ModifyEventTime(), and Update().
m_time
uint64 EventProcessor::m_time {0} protected
{0};
Referenced by AddEvent(), CalculateQueueTime(), CalculateTime(), CancelEventGroup(), KillAllEvents(), and Update().
The documentation for this class was generated from the following files:
azerothcore-wotlk/src/common/Utilities/EventProcessor.h
azerothcore-wotlk/src/common/Utilities/EventProcessor.cpp