AzerothCore Doxygen
LuaAchievement Namespace Reference
Functions
int GetId (lua_State *L, AchievementEntry *const achievement)
int GetName (lua_State *L, AchievementEntry *const achievement)
Function Documentation
GetId()
int LuaAchievement::GetId (lua_State * L, AchievementEntry *const achievement)
Returns the [Achievement]'s ID.
Returns
uint32 id
    {
        Eluna::Push(L, achievement->ID);
        return 1;
    }
References AchievementEntry::ID, and Eluna::Push().
GetName()
int LuaAchievement::GetName (lua_State * L, AchievementEntry *const achievement)
Returns the [Achievement]'s name.
enum LocaleConstant
{
    LOCALE_enUS = 0,
    LOCALE_koKR = 1,
    LOCALE_frFR = 2,
    LOCALE_deDE = 3,
    LOCALE_zhCN = 4,
    LOCALE_zhTW = 5,
    LOCALE_esES = 6,
    LOCALE_esMX = 7,
    LOCALE_ruRU = 8
};
Parameters
[LocaleConstant] locale = DEFAULT_LOCALE : locale to return the [Achievement] name in
Returns
string name
    {
        uint8 locale = Eluna::CHECKVAL<uint8>(L, 2, DEFAULT_LOCALE);
        if (locale >= TOTAL_LOCALES)
        {
            return luaL_argerror(L, 2, "valid LocaleConstant expected");
        }
        Eluna::Push(L, achievement->name[locale]);
        return 1;
    }
References DEFAULT_LOCALE, luaL_argerror(), AchievementEntry::name, Eluna::Push(), and TOTAL_LOCALES.