AzerothCore Doxygen
boss_jarien_and_sothos.cpp File Reference
#include "CreatureScript.h"
#include "ScriptedCreature.h"
#include "TaskScheduler.h"
#include "stratholme.h"
Classes
struct boss_jarien
struct boss_sothos
Enumerations
enum Texts {
SAY_SOTHOS_ON_SUMMON_0 = 0 ,
SAY_SOTHOS_ON_SUMMON_1 = 1 ,
EMOTE_SOTHOS_VENGEANCE = 2 ,
SAY_JARIEN_ON_SUMMON_0 = 0 ,
SAY_JARIEN_ON_SUMMON_1 = 1 ,
SAY_JARIEN_ON_SUMMON_2 = 2 ,
EMOTE_JARIEN_VENGEANCE = 3 ,
SAY_SPIRIT_BOTH_DEAD = 0
}
enum Spells {
SPELL_MORTAL_STRIKE = 16856 ,
SPELL_SHADOW_SHOCK = 22575 ,
SPELL_CRIPPLE = 20812 ,
SPELL_CLEAVE = 15284 ,
SPELL_SHIELD_CHARGE = 15749 ,
SPELL_SHIELD_SLAM = 15655 ,
SPELL_SHIELD_BLOCK = 12169 ,
SPELL_SHADOW_BOLT = 27646 ,
SPELL_FEAR = 27641 ,
SPELL_VENGEANCE = 27650
}
enum Phases {
PHASE_TALK = 0 ,
PHASE_FIGHT
}
enum Actions { ACTION_PARTNER_DEAD = 0 }
Functions
void HandleBothDead (Creature *creature, bool jarien, Unit *killer)
void AddSC_boss_jarien_and_sothos ()
Variables
const Position heirloomsPosition = { 3423.389893f, -3055.571045f, 136.49837f, 5.707379f }
Enumeration Type Documentation
Actions
enum Actions
Enumerator
ACTION_PARTNER_DEAD
{
    ACTION_PARTNER_DEAD = 0
};
Phases
enum Phases
Enumerator
PHASE_TALK
PHASE_FIGHT
{
    PHASE_TALK = 0,
    PHASE_FIGHT
};
Spells
enum Spells
Enumerator
SPELL_MORTAL_STRIKE
SPELL_SHADOW_SHOCK
SPELL_CRIPPLE
SPELL_CLEAVE
SPELL_SHIELD_CHARGE
SPELL_SHIELD_SLAM
SPELL_SHIELD_BLOCK
SPELL_SHADOW_BOLT
SPELL_FEAR
SPELL_VENGEANCE
{
    // Jarien
    SPELL_MORTAL_STRIKE     = 16856,
    SPELL_SHADOW_SHOCK      = 22575,
    SPELL_CRIPPLE           = 20812,
    SPELL_CLEAVE            = 15284,
    // Sothos
    SPELL_SHIELD_CHARGE     = 15749,
    SPELL_SHIELD_SLAM       = 15655,
    SPELL_SHIELD_BLOCK      = 12169,
    SPELL_SHADOW_BOLT       = 27646,
    SPELL_FEAR              = 27641,
    // Both
    SPELL_VENGEANCE         = 27650
};
Texts
enum Texts
Enumerator
SAY_SOTHOS_ON_SUMMON_0
SAY_SOTHOS_ON_SUMMON_1
EMOTE_SOTHOS_VENGEANCE
SAY_JARIEN_ON_SUMMON_0
SAY_JARIEN_ON_SUMMON_1
SAY_JARIEN_ON_SUMMON_2
EMOTE_JARIEN_VENGEANCE
SAY_SPIRIT_BOTH_DEAD
{
    // Sothos
    SAY_SOTHOS_ON_SUMMON_0     = 0,
    SAY_SOTHOS_ON_SUMMON_1     = 1,
    EMOTE_SOTHOS_VENGEANCE     = 2,
    // Jarien
    SAY_JARIEN_ON_SUMMON_0     = 0,
    SAY_JARIEN_ON_SUMMON_1     = 1,
    SAY_JARIEN_ON_SUMMON_2     = 2,
    EMOTE_JARIEN_VENGEANCE     = 3,
    // Spirit
    SAY_SPIRIT_BOTH_DEAD       = 0
};
Function Documentation
AddSC_boss_jarien_and_sothos()
void AddSC_boss_jarien_and_sothos ()
{
    RegisterStratholmeCreatureAI(boss_jarien);
    RegisterStratholmeCreatureAI(boss_sothos);
}
References RegisterStratholmeCreatureAI.
Referenced by AddEasternKingdomsScripts().
HandleBothDead()
void HandleBothDead (Creature * creature, bool jarien, Unit * killer)
{
    // Spirit talk
    if (jarien)
    {
        if (Creature* spirit = creature->FindNearestCreature(NPC_SPIRIT_OF_JARIEN, 100.f))
        {
            spirit->AttackStop();
            spirit->SetReactState(REACT_PASSIVE);
            spirit->AI()->Talk(SAY_SPIRIT_BOTH_DEAD);
        }
    }
    else
    {
        if (Creature* spirit = creature->FindNearestCreature(NPC_SPIRIT_OF_SOTHOS, 100.f))
        {
            spirit->AttackStop();
            spirit->SetReactState(REACT_PASSIVE);
            spirit->AI()->Talk(SAY_SPIRIT_BOTH_DEAD);
        }
    }
    // chest spawn
    if (GameObject* chest = killer->SummonGameObject(GO_JARIEN_AND_SOTHOS_HEIRLOOMS, heirloomsPosition.GetPositionX(), heirloomsPosition.GetPositionY(), heirloomsPosition.GetPositionZ(), heirloomsPosition.GetOrientation(), 0.f, 0.f, 0.f, 0.f, 0))
    {
        chest->setActive(true);
        chest->SetGoState(GO_STATE_READY);
        chest->SetLootState(GO_READY);
        chest->SetUInt32Value(GAMEOBJECT_FACTION, 35);
    }
}
References WorldObject::FindNearestCreature(), GAMEOBJECT_FACTION, Position::GetOrientation(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), GO_JARIEN_AND_SOTHOS_HEIRLOOMS, GO_READY, GO_STATE_READY, heirloomsPosition, NPC_SPIRIT_OF_JARIEN, NPC_SPIRIT_OF_SOTHOS, REACT_PASSIVE, SAY_SPIRIT_BOTH_DEAD, and WorldObject::SummonGameObject().
Referenced by boss_jarien::JustDied(), and boss_sothos::JustDied().
Variable Documentation
heirloomsPosition
const Position heirloomsPosition = { 3423.389893f, -3055.571045f, 136.49837f, 5.707379f }
{ 3423.389893f, -3055.571045f, 136.49837f, 5.707379f };
Referenced by HandleBothDead().