AzerothCore Doxygen
PeriodicAbsorbStealthProcTest.cpp File Reference
#include "ProcEventInfoHelper.h"
#include "SpellMgr.h"
#include "WorldMock.h"
#include "gtest/gtest.h"
#include "gmock/gmock.h"
Classes
class PeriodicAbsorbStealthProcTest
Tests for fully absorbed periodic damage not triggering TAKEN procs.
Functions
TEST_F (PeriodicAbsorbStealthProcTest, FullyAbsorbedPeriodicDoesNotTriggerTakenProc)
TEST_F (PeriodicAbsorbStealthProcTest, NonAbsorbedPeriodicTriggersTakenProc)
TEST_F (PeriodicAbsorbStealthProcTest, CriticalPeriodicTriggersTakenProc)
TEST_F (PeriodicAbsorbStealthProcTest, PartiallyAbsorbedPeriodicTriggersTakenProc)
TEST_F (PeriodicAbsorbStealthProcTest, FullyAbsorbedPeriodicTriggersDoneProc)
Function Documentation
TEST_F() [1/5]
TEST_F (PeriodicAbsorbStealthProcTest , CriticalPeriodicTriggersTakenProc)
{
    auto procEntry = SpellProcEntryBuilder()
        .WithProcFlags(PROC_FLAG_TAKEN_PERIODIC)
        .WithHitMask(0)
        .Build();
    auto eventInfo = ProcEventInfoBuilder()
        .WithTypeMask(PROC_FLAG_TAKEN_PERIODIC)
        .WithHitMask(PROC_HIT_CRITICAL)
        .Build();
    EXPECT_TRUE(sSpellMgr->CanSpellTriggerProcOnEvent(procEntry, eventInfo));
}
References ProcEventInfoBuilder::Build(), SpellProcEntryBuilder::Build(), PROC_FLAG_TAKEN_PERIODIC, PROC_HIT_CRITICAL, sSpellMgr, ProcEventInfoBuilder::WithHitMask(), SpellProcEntryBuilder::WithHitMask(), SpellProcEntryBuilder::WithProcFlags(), and ProcEventInfoBuilder::WithTypeMask().
TEST_F() [2/5]
TEST_F (PeriodicAbsorbStealthProcTest , FullyAbsorbedPeriodicDoesNotTriggerTakenProc)
{
    // Stealth has ProcFlags including PROC_FLAG_TAKEN_PERIODIC, HitMask=0
    // Default TAKEN HitMask = PROC_HIT_NORMAL | PROC_HIT_CRITICAL (no ABSORB)
    auto procEntry = SpellProcEntryBuilder()
        .WithProcFlags(PROC_FLAG_TAKEN_PERIODIC)
        .WithHitMask(0)
        .Build();
    // Fully absorbed periodic tick: hitMask = PROC_HIT_ABSORB only
    // (damage=0 so PROC_EX_NORMAL_HIT is NOT set)
    auto eventInfo = ProcEventInfoBuilder()
        .WithTypeMask(PROC_FLAG_TAKEN_PERIODIC)
        .WithHitMask(PROC_HIT_ABSORB)
        .Build();
    EXPECT_FALSE(sSpellMgr->CanSpellTriggerProcOnEvent(procEntry, eventInfo));
}
References ProcEventInfoBuilder::Build(), SpellProcEntryBuilder::Build(), PROC_FLAG_TAKEN_PERIODIC, PROC_HIT_ABSORB, sSpellMgr, ProcEventInfoBuilder::WithHitMask(), SpellProcEntryBuilder::WithHitMask(), SpellProcEntryBuilder::WithProcFlags(), and ProcEventInfoBuilder::WithTypeMask().
TEST_F() [3/5]
TEST_F (PeriodicAbsorbStealthProcTest , FullyAbsorbedPeriodicTriggersDoneProc)
{
    auto procEntry = SpellProcEntryBuilder()
        .WithProcFlags(PROC_FLAG_DONE_PERIODIC)
        .WithSpellPhaseMask(PROC_SPELL_PHASE_HIT)
        .WithHitMask(0)
        .Build();
    // Fully absorbed: only PROC_HIT_ABSORB
    auto eventInfo = ProcEventInfoBuilder()
        .WithTypeMask(PROC_FLAG_DONE_PERIODIC)
        .WithSpellPhaseMask(PROC_SPELL_PHASE_HIT)
        .WithHitMask(PROC_HIT_ABSORB)
        .Build();
    // DONE default includes ABSORB, so this SHOULD trigger
    EXPECT_TRUE(sSpellMgr->CanSpellTriggerProcOnEvent(procEntry, eventInfo));
}
References ProcEventInfoBuilder::Build(), SpellProcEntryBuilder::Build(), PROC_FLAG_DONE_PERIODIC, PROC_HIT_ABSORB, PROC_SPELL_PHASE_HIT, sSpellMgr, ProcEventInfoBuilder::WithHitMask(), SpellProcEntryBuilder::WithHitMask(), SpellProcEntryBuilder::WithProcFlags(), ProcEventInfoBuilder::WithSpellPhaseMask(), SpellProcEntryBuilder::WithSpellPhaseMask(), and ProcEventInfoBuilder::WithTypeMask().
TEST_F() [4/5]
TEST_F (PeriodicAbsorbStealthProcTest , NonAbsorbedPeriodicTriggersTakenProc)
{
    auto procEntry = SpellProcEntryBuilder()
        .WithProcFlags(PROC_FLAG_TAKEN_PERIODIC)
        .WithHitMask(0)
        .Build();
    // Normal periodic tick: hitMask includes PROC_HIT_NORMAL
    auto eventInfo = ProcEventInfoBuilder()
        .WithTypeMask(PROC_FLAG_TAKEN_PERIODIC)
        .WithHitMask(PROC_HIT_NORMAL)
        .Build();
    EXPECT_TRUE(sSpellMgr->CanSpellTriggerProcOnEvent(procEntry, eventInfo));
}
References ProcEventInfoBuilder::Build(), SpellProcEntryBuilder::Build(), PROC_FLAG_TAKEN_PERIODIC, PROC_HIT_NORMAL, sSpellMgr, ProcEventInfoBuilder::WithHitMask(), SpellProcEntryBuilder::WithHitMask(), SpellProcEntryBuilder::WithProcFlags(), and ProcEventInfoBuilder::WithTypeMask().
TEST_F() [5/5]
TEST_F (PeriodicAbsorbStealthProcTest , PartiallyAbsorbedPeriodicTriggersTakenProc)
{
    auto procEntry = SpellProcEntryBuilder()
        .WithProcFlags(PROC_FLAG_TAKEN_PERIODIC)
        .WithHitMask(0)
        .Build();
    // Partial absorb: both NORMAL and ABSORB flags set
    auto eventInfo = ProcEventInfoBuilder()
        .WithTypeMask(PROC_FLAG_TAKEN_PERIODIC)
        .WithHitMask(PROC_HIT_NORMAL | PROC_HIT_ABSORB)
        .Build();
    EXPECT_TRUE(sSpellMgr->CanSpellTriggerProcOnEvent(procEntry, eventInfo));
}
References ProcEventInfoBuilder::Build(), SpellProcEntryBuilder::Build(), PROC_FLAG_TAKEN_PERIODIC, PROC_HIT_ABSORB, PROC_HIT_NORMAL, sSpellMgr, ProcEventInfoBuilder::WithHitMask(), SpellProcEntryBuilder::WithHitMask(), SpellProcEntryBuilder::WithProcFlags(), and ProcEventInfoBuilder::WithTypeMask().