AzerothCore Doxygen
BattlegroundMap Class Reference
#include "Map.h"
Public Member Functions
BattlegroundMap (uint32 id, uint32 InstanceId, Map *_parent, uint8 spawnMode)
~BattlegroundMap () override
bool AddPlayerToMap (Player *) override
void RemovePlayerFromMap (Player *, bool) override
EnterState CannotEnter (Player *player, bool loginCheck=false) override
void SetUnload ()
void RemoveAllPlayers () override
void InitVisibilityDistance () override
Battleground * GetBG ()
void SetBG (Battleground *bg)
Public Member Functions inherited from Map
Map (uint32 id, uint32 InstanceId, uint8 SpawnMode, Map *_parent=nullptr)
~Map () override
MapEntry const * GetEntry () const
bool CanUnload (uint32 diff)
virtual void AfterPlayerUnlinkFromMap ()
template<class T >
bool AddToMap (T *, bool checkTransport=false)
template<class T >
void RemoveFromMap (T *, bool)
void MarkNearbyCellsOf (WorldObject *obj)
virtual void Update (const uint32, const uint32, bool thread=true)
float GetVisibilityRange () const
void SetVisibilityRange (float range)
void OnCreateMap ()
void PlayerRelocation (Player *, float x, float y, float z, float o)
void CreatureRelocation (Creature *creature, float x, float y, float z, float o)
void GameObjectRelocation (GameObject *go, float x, float y, float z, float o)
void DynamicObjectRelocation (DynamicObject *go, float x, float y, float z, float o)
template<class T , class CONTAINER >
void Visit (const Cell &cell, TypeContainerVisitor< T, CONTAINER > &visitor)
bool IsGridLoaded (GridCoord const &gridCoord) const
bool IsGridLoaded (float x, float y) const
bool IsGridCreated (GridCoord const &gridCoord) const
bool IsGridCreated (float x, float y) const
void LoadGrid (float x, float y)
void LoadAllGrids ()
void LoadGridsInRange (Position const &center, float radius)
bool UnloadGrid (MapGridType &grid)
virtual void UnloadAll ()
std::shared_ptr< GridTerrainData > GetGridTerrainDataSharedPtr (GridCoord const &gridCoord)
GridTerrainData * GetGridTerrainData (GridCoord const &gridCoord)
GridTerrainData * GetGridTerrainData (float x, float y)
uint32 GetId () const
Map const * GetParent () const
std::shared_mutex & GetMMapLock () const
void HandleDelayedVisibility ()
float GetHeight (float x, float y, float z, bool checkVMap=true, float maxSearchDist=DEFAULT_HEIGHT_SEARCH) const
float GetGridHeight (float x, float y) const
float GetMinHeight (float x, float y) const
Transport * GetTransportForPos (uint32 phase, float x, float y, float z, WorldObject *worldobject=nullptr)
void GetFullTerrainStatusForPosition (uint32 phaseMask, float x, float y, float z, float collisionHeight, PositionFullTerrainStatus &data, Optional< uint8 > reqLiquidType={})
LiquidData const GetLiquidData (uint32 phaseMask, float x, float y, float z, float collisionHeight, Optional< uint8 > ReqLiquidType)
bool GetAreaInfo (uint32 phaseMask, float x, float y, float z, uint32 &mogpflags, int32 &adtId, int32 &rootId, int32 &groupId) const
uint32 GetAreaId (uint32 phaseMask, float x, float y, float z) const
uint32 GetZoneId (uint32 phaseMask, float x, float y, float z) const
void GetZoneAndAreaId (uint32 phaseMask, uint32 &zoneid, uint32 &areaid, float x, float y, float z) const
float GetWaterLevel (float x, float y) const
bool IsInWater (uint32 phaseMask, float x, float y, float z, float collisionHeight) const
bool IsUnderWater (uint32 phaseMask, float x, float y, float z, float collisionHeight) const
bool HasEnoughWater (WorldObject const *searcher, float x, float y, float z) const
bool HasEnoughWater (WorldObject const *searcher, LiquidData const &liquidData) const
void MoveAllCreaturesInMoveList ()
void MoveAllGameObjectsInMoveList ()
void MoveAllDynamicObjectsInMoveList ()
void RemoveAllObjectsInRemoveList ()
uint32 GetInstanceId () const
uint8 GetSpawnMode () const
const char * GetMapName () const
Difficulty GetDifficulty () const
bool IsRegularDifficulty () const
MapDifficulty const * GetMapDifficulty () const
bool Instanceable () const
bool IsDungeon () const
bool IsNonRaidDungeon () const
bool IsRaid () const
bool IsRaidOrHeroicDungeon () const
bool IsHeroic () const
bool Is25ManRaid () const
bool IsBattleground () const
bool IsBattleArena () const
bool IsBattlegroundOrArena () const
bool IsWorldMap () const
bool GetEntrancePos (int32 &mapid, float &x, float &y)
void AddObjectToRemoveList (WorldObject *obj)
virtual void DelayedUpdate (const uint32 diff)
void resetMarkedCells ()
bool isCellMarked (uint32 pCellId)
void markCell (uint32 pCellId)
bool HavePlayers () const
uint32 GetPlayersCountExceptGMs () const
void SendToPlayers (WorldPacket const *data) const
PlayerList const & GetPlayers () const
void ScriptsStart (std::map< uint32, std::multimap< uint32, ScriptInfo > > const &scripts, uint32 id, Object *source, Object *target)
Put scripts in the execution queue.
void ScriptCommandStart (ScriptInfo const &script, uint32 delay, Object *source, Object *target)
void UpdateIteratorBack (Player *player)
TempSummon * SummonCreature (uint32 entry, Position const &pos, SummonPropertiesEntry const *properties=nullptr, uint32 duration=0, WorldObject *summoner=nullptr, uint32 spellId=0, uint32 vehId=0, bool visibleBySummonerOnly=false)
GameObject * SummonGameObject (uint32 entry, float x, float y, float z, float ang, float rotation0, float rotation1, float rotation2, float rotation3, uint32 respawnTime, bool checkTransport=true)
GameObject * SummonGameObject (uint32 entry, Position const &pos, float rotation0=0.0f, float rotation1=0.0f, float rotation2=0.0f, float rotation3=0.0f, uint32 respawnTime=100, bool checkTransport=true)
void SummonCreatureGroup (uint8 group, std::list< TempSummon * > *list=nullptr)
Corpse * GetCorpse (ObjectGuid const &guid)
Creature * GetCreature (ObjectGuid const &guid)
GameObject * GetGameObject (ObjectGuid const &guid)
Transport * GetTransport (ObjectGuid const &guid)
DynamicObject * GetDynamicObject (ObjectGuid const &guid)
Pet * GetPet (ObjectGuid const &guid)
MapStoredObjectTypesContainer & GetObjectsStore ()
CreatureBySpawnIdContainer & GetCreatureBySpawnIdStore ()
GameObjectBySpawnIdContainer & GetGameObjectBySpawnIdStore ()
std::unordered_set< Corpse * > const * GetCorpsesInGrid (uint32 gridId) const
Corpse * GetCorpseByPlayer (ObjectGuid const &ownerGuid) const
MapInstanced * ToMapInstanced ()
MapInstanced const * ToMapInstanced () const
InstanceMap * ToInstanceMap ()
InstanceMap const * ToInstanceMap () const
BattlegroundMap * ToBattlegroundMap ()
BattlegroundMap const * ToBattlegroundMap () const
float GetWaterOrGroundLevel (uint32 phasemask, float x, float y, float z, float *ground=nullptr, bool swim=false, float collisionHeight=DEFAULT_COLLISION_HEIGHT) const
float GetHeight (uint32 phasemask, float x, float y, float z, bool vmap=true, float maxSearchDist=DEFAULT_HEIGHT_SEARCH) const
bool isInLineOfSight (float x1, float y1, float z1, float x2, float y2, float z2, uint32 phasemask, LineOfSightChecks checks, VMAP::ModelIgnoreFlags ignoreFlags) const
bool CanReachPositionAndGetValidCoords (WorldObject const *source, PathGenerator *path, float &destX, float &destY, float &destZ, bool failOnCollision=true, bool failOnSlopes=true) const
Check if a given source can reach a specific point following a path and normalize the coords. Use this method for long paths, otherwise use the overloaded method with the start coords when you need to do a quick check on small segments.
bool CanReachPositionAndGetValidCoords (WorldObject const *source, float &destX, float &destY, float &destZ, bool failOnCollision=true, bool failOnSlopes=true) const
validate the new destination and set reachable coords Check if a given unit can reach a specific point on a segment and set the correct dest coords NOTE: use this method with small segments.
bool CanReachPositionAndGetValidCoords (WorldObject const *source, float startX, float startY, float startZ, float &destX, float &destY, float &destZ, bool failOnCollision=true, bool failOnSlopes=true) const
bool CheckCollisionAndGetValidCoords (WorldObject const *source, float startX, float startY, float startZ, float &destX, float &destY, float &destZ, bool failOnCollision=true) const
validate the new destination and set coords Check if a given unit can face collisions in a specific segment
void Balance ()
void RemoveGameObjectModel (const GameObjectModel &model)
void InsertGameObjectModel (const GameObjectModel &model)
bool ContainsGameObjectModel (const GameObjectModel &model) const
DynamicMapTree const & GetDynamicMapTree () const
bool GetObjectHitPos (uint32 phasemask, float x1, float y1, float z1, float x2, float y2, float z2, float &rx, float &ry, float &rz, float modifyDist)
float GetGameObjectFloor (uint32 phasemask, float x, float y, float z, float maxSearchDist=DEFAULT_HEIGHT_SEARCH) const
time_t GetLinkedRespawnTime (ObjectGuid guid) const
time_t GetCreatureRespawnTime (ObjectGuid::LowType dbGuid) const
time_t GetGORespawnTime (ObjectGuid::LowType dbGuid) const
void SaveCreatureRespawnTime (ObjectGuid::LowType dbGuid, time_t &respawnTime)
void RemoveCreatureRespawnTime (ObjectGuid::LowType dbGuid)
void SaveGORespawnTime (ObjectGuid::LowType dbGuid, time_t &respawnTime)
void RemoveGORespawnTime (ObjectGuid::LowType dbGuid)
void LoadRespawnTimes ()
void DeleteRespawnTimes ()
time_t GetInstanceResetPeriod () const
void UpdatePlayerZoneStats (uint32 oldZone, uint32 newZone)
uint32 ApplyDynamicModeRespawnScaling (WorldObject const *obj, uint32 respawnDelay) const
void ScheduleCreatureRespawn (ObjectGuid, Milliseconds, Position pos=Position())
void LoadCorpseData ()
void DeleteCorpseData ()
void AddCorpse (Corpse *corpse)
void RemoveCorpse (Corpse *corpse)
Corpse * ConvertCorpseToBones (ObjectGuid const &ownerGuid, bool insignia=false)
void RemoveOldCorpses ()
bool SendZoneMessage (uint32 zone, WorldPacket const *packet, WorldSession const *self=nullptr, TeamId teamId=TEAM_NEUTRAL) const
Send a packet to all players (or players selected team) in the zone (except self if mentioned)
void SendZoneText (uint32 zoneId, char const *text, WorldSession const *self=nullptr, TeamId teamId=TEAM_NEUTRAL) const
Send a System Message to all players in the zone (except self if mentioned)
void SendInitTransports (Player *player)
void SendRemoveTransports (Player *player)
void SendZoneDynamicInfo (uint32 zoneId, Player *player) const
void SendZoneWeather (uint32 zoneId, Player *player) const
void SendZoneWeather (ZoneDynamicInfo const &zoneDynamicInfo, Player *player) const
void SendInitSelf (Player *player)
void UpdateWeather (uint32 const diff)
void UpdateExpiredCorpses (uint32 const diff)
void PlayDirectSoundToMap (uint32 soundId, uint32 zoneId=0)
void SetZoneMusic (uint32 zoneId, uint32 musicId)
Weather * GetOrGenerateZoneDefaultWeather (uint32 zoneId)
void SetZoneWeather (uint32 zoneId, WeatherState weatherId, float weatherGrade)
void SetZoneOverrideLight (uint32 zoneId, uint32 lightId, Milliseconds fadeInTime)
void UpdateEncounterState (EncounterCreditType type, uint32 creditEntry, Unit *source)
void LogEncounterFinished (EncounterCreditType type, uint32 creditEntry)
void DoForAllPlayers (std::function< void(Player *)> exec)
void EnsureGridCreated (GridCoord const &gridCoord)
bool AllTransportsEmpty () const
void AllTransportsRemovePassengers ()
TransportsContainer const & GetAllTransports () const
template<HighGuid high>
ObjectGuid::LowType GenerateLowGuid ()
void AddUpdateObject (Object *obj)
void RemoveUpdateObject (Object *obj)
size_t GetUpdatableObjectsCount () const
virtual std::string GetDebugInfo () const
uint32 GetCreatedGridsCount ()
uint32 GetLoadedGridsCount ()
uint32 GetCreatedCellsInGridCount (uint16 const x, uint16 const y)
uint32 GetCreatedCellsInMapCount ()
void AddObjectToPendingUpdateList (WorldObject *obj)
void RemoveObjectFromMapUpdateList (WorldObject *obj)
void AddWorldObjectToFarVisibleMap (WorldObject *obj)
void RemoveWorldObjectFromFarVisibleMap (WorldObject *obj)
void AddWorldObjectToZoneWideVisibleMap (uint32 zoneId, WorldObject *obj)
void RemoveWorldObjectFromZoneWideVisibleMap (uint32 zoneId, WorldObject *obj)
ZoneWideVisibleWorldObjectsSet const * GetZoneWideVisibleWorldObjectsForZone (uint32 zoneId) const
uint32 GetPlayerCountInZone (uint32 zoneId) const
template<>
void AddToGrid (Creature *obj, Cell const &cell)
template<>
void AddToGrid (GameObject *obj, Cell const &cell)
template<>
void AddToGrid (Player *obj, Cell const &cell)
template<>
void AddToGrid (Corpse *obj, Cell const &cell)
template<>
void DeleteFromWorld (Player *player)
template<>
void InitializeObject (Creature *)
template<>
void InitializeObject (GameObject *)
template<>
bool AddToMap (Transport *obj, bool)
template<>
void RemoveFromMap (Transport *obj, bool remove)
Public Member Functions inherited from GridRefMgr< MapGridType >
GridReference< MapGridType > * getFirst ()
GridReference< MapGridType > * getLast ()
iterator begin ()
iterator end ()
iterator rbegin ()
iterator rend ()
Public Member Functions inherited from RefMgr< TO, FROM >
RefMgr ()=default
virtual ~RefMgr ()
Reference< TO, FROM > * getFirst ()
Reference< TO, FROM > const * getFirst () const
Reference< TO, FROM > * getLast ()
Reference< TO, FROM > const * getLast () const
iterator begin ()
iterator end ()
iterator rbegin ()
iterator rend ()
void clearReferences ()
Public Member Functions inherited from LinkedListHead
LinkedListHead ()
bool IsEmpty () const
LinkedListElement * getFirst ()
LinkedListElement const * getFirst () const
LinkedListElement * getLast ()
LinkedListElement const * getLast () const
void insertFirst (LinkedListElement *pElem)
void insertLast (LinkedListElement *pElem)
uint32 getSize () const
void incSize ()
void decSize ()
Private Attributes
Battleground * m_bg
Additional Inherited Members
Public Types inherited from Map
enum EnterState {
CAN_ENTER = 0 ,
CANNOT_ENTER_ALREADY_IN_MAP = 1 ,
CANNOT_ENTER_NO_ENTRY ,
CANNOT_ENTER_UNINSTANCED_DUNGEON ,
CANNOT_ENTER_DIFFICULTY_UNAVAILABLE ,
CANNOT_ENTER_NOT_IN_RAID ,
CANNOT_ENTER_CORPSE_IN_DIFFERENT_INSTANCE ,
CANNOT_ENTER_INSTANCE_BIND_MISMATCH ,
CANNOT_ENTER_TOO_MANY_INSTANCES ,
CANNOT_ENTER_MAX_PLAYERS ,
CANNOT_ENTER_ZONE_IN_COMBAT ,
CANNOT_ENTER_UNSPECIFIED_REASON
}
typedef MapRefMgr PlayerList
typedef std::unordered_multimap< ObjectGuid::LowType, Creature * > CreatureBySpawnIdContainer
typedef std::unordered_multimap< ObjectGuid::LowType, GameObject * > GameObjectBySpawnIdContainer
typedef std::vector< WorldObject * > UpdatableObjectList
typedef std::unordered_set< WorldObject * > PendingAddUpdatableObjectList
Public Types inherited from GridRefMgr< MapGridType >
typedef LinkedListHead::Iterator< GridReference< MapGridType > > iterator
Public Types inherited from RefMgr< TO, FROM >
typedef LinkedListHead::Iterator< Reference< TO, FROM > > iterator
Public Types inherited from LinkedListHead
typedef Iterator< LinkedListElement > iterator
Static Public Member Functions inherited from Map
static void DeleteRespawnTimesInDB (uint16 mapId, uint32 instanceId)
Public Attributes inherited from Map
std::unordered_set< Unit * > i_objectsForDelayedVisibility
CreatureGroupHolderType CreatureGroupHolder
EventProcessor Events
DataMap CustomData
Protected Member Functions inherited from Map
template<class T >
void AddToGrid (T *object, Cell const &cell)
Protected Attributes inherited from Map
std::mutex Lock
std::shared_mutex MMapLock
MapGridManager _mapGridManager
MapEntry const * i_mapEntry
uint8 i_spawnMode
uint32 i_InstanceId
uint32 m_unloadTimer
float m_VisibleDistance
DynamicMapTree _dynamicTree
time_t _instanceResetPeriod
MapRefMgr m_mapRefMgr
MapRefMgr::iterator m_mapRefIter
TransportsContainer _transports
TransportsContainer::iterator _transportsUpdateIter
Detailed Description
Constructor & Destructor Documentation
BattlegroundMap()
BattlegroundMap::BattlegroundMap (uint32 id, uint32 InstanceId, Map * _parent, uint8 spawnMode)
    : Map(id, InstanceId, spawnMode, _parent), m_bg(nullptr)
{
    //lets initialize visibility distance for BG/Arenas
    BattlegroundMap::InitVisibilityDistance();
}
References InitVisibilityDistance().
~BattlegroundMap()
BattlegroundMap::~BattlegroundMap () override
{
    if (m_bg)
    {
        //unlink to prevent crash, always unlink all pointer reference before destruction
        m_bg->SetBgMap(nullptr);
        m_bg = nullptr;
    }
}
References m_bg, and Battleground::SetBgMap().
Member Function Documentation
AddPlayerToMap()
bool BattlegroundMap::AddPlayerToMap (Player * player) override virtual
Reimplemented from Map.
{
    player->m_InstanceValid = true;
    if (IsBattleArena())
        player->CastSpell(player, 100102, true);
    return Map::AddPlayerToMap(player);
}
References Map::AddPlayerToMap(), Unit::CastSpell(), Map::IsBattleArena(), and Player::m_InstanceValid.
CannotEnter()
Map::EnterState BattlegroundMap::CannotEnter (Player * player, bool loginCheck = false) override virtual
Reimplemented from Map.
{
    if (!loginCheck && player->GetMapRef().getTarget() == this)
    {
        LOG_ERROR("maps", "BGMap::CanEnter - player {} is already in map!", player->GetGUID().ToString());
        ABORT();
        return CANNOT_ENTER_ALREADY_IN_MAP;
    }
    if (player->GetBattlegroundId() != GetInstanceId())
        return CANNOT_ENTER_INSTANCE_BIND_MISMATCH;
    // pussywizard: no need to check player limit here, invitations are limited by Battleground::GetFreeSlotsForTeam
    return Map::CannotEnter(player, loginCheck);
}
References ABORT, Map::CANNOT_ENTER_ALREADY_IN_MAP, Map::CANNOT_ENTER_INSTANCE_BIND_MISMATCH, Map::CannotEnter(), Player::GetBattlegroundId(), Object::GetGUID(), Map::GetInstanceId(), Player::GetMapRef(), Reference< TO, FROM >::getTarget(), LOG_ERROR, and ObjectGuid::ToString().
GetBG()
Battleground * BattlegroundMap::GetBG () inline
{ return m_bg; }
References m_bg.
Referenced by ArenaSpectator::HandleSpectatorSpectateCommand(), RemovePlayerFromMap(), and npc_ioc_gunship_captain::npc_ioc_gunship_captainAI::UpdateAI().
InitVisibilityDistance()
void BattlegroundMap::InitVisibilityDistance () override virtual
Reimplemented from Map.
{
    //init visibility distance for BG/Arenas
    m_VisibleDistance = World::GetMaxVisibleDistanceInBGArenas();
    if (IsBattleArena()) // pussywizard: start with 30yd visibility range on arenas to ensure players can't get informations about the opponents in any way
        m_VisibleDistance = 30.0f;
}
References World::GetMaxVisibleDistanceInBGArenas(), Map::IsBattleArena(), and Map::m_VisibleDistance.
Referenced by BattlegroundMap().
RemoveAllPlayers()
void BattlegroundMap::RemoveAllPlayers () override virtual
Reimplemented from Map.
{
    if (HavePlayers())
        for (MapRefMgr::iterator itr = m_mapRefMgr.begin(); itr != m_mapRefMgr.end(); ++itr)
            if (Player* player = itr->GetSource())
                if (!player->IsBeingTeleportedFar())
                    player->TeleportTo(player->GetEntryPoint());
}
References MapRefMgr::begin(), MapRefMgr::end(), Map::HavePlayers(), and Map::m_mapRefMgr.
Referenced by MapInstanced::DestroyInstance().
RemovePlayerFromMap()
void BattlegroundMap::RemovePlayerFromMap (Player * player, bool remove) override virtual
Reimplemented from Map.
{
    if (Battleground* bg = GetBG())
    {
        bg->RemovePlayerAtLeave(player);
        if (IsBattleArena())
            bg->RemoveSpectator(player);
    }
    if (IsBattleArena())
        player->RemoveAura(100102);
    Map::RemovePlayerFromMap(player, remove);
}
References GetBG(), Map::IsBattleArena(), Unit::RemoveAura(), and Map::RemovePlayerFromMap().
SetBG()
void BattlegroundMap::SetBG (Battleground * bg) inline
{ m_bg = bg; }
References m_bg.
Referenced by MapInstanced::CreateBattleground(), and Battleground::~Battleground().
SetUnload()
void BattlegroundMap::SetUnload ()
{
    m_unloadTimer = MIN_UNLOAD_DELAY;
}
References Map::m_unloadTimer, and MIN_UNLOAD_DELAY.
Referenced by Battleground::~Battleground().
Member Data Documentation
m_bg
Battleground* BattlegroundMap::m_bg private
Referenced by GetBG(), SetBG(), and ~BattlegroundMap().
The documentation for this class was generated from the following files:
azerothcore-wotlk/src/server/game/Maps/Map.h
azerothcore-wotlk/src/server/game/Maps/Map.cpp