AzerothCore Doxygen
spell_pal_seal_of_vengeance_aura Class Reference
Private Member Functions
PrepareAuraScript (spell_pal_seal_of_vengeance_aura)
bool Validate (SpellInfo const *) override
bool Load () override
void HandleApplyDoT (AuraEffect const *aurEff, ProcEventInfo &eventInfo)
void HandleSeal (AuraEffect const *aurEff, ProcEventInfo &eventInfo)
void Register () override
Private Attributes
bool _isVengeance = true
Additional Inherited Members
Public Member Functions inherited from AuraScript
AuraScript ()
bool _Validate (SpellInfo const *entry) override
bool _Load (Aura *aura)
void _PrepareScriptCall (AuraScriptHookType hookType, AuraApplication const *aurApp=nullptr)
void _FinishScriptCall ()
bool _IsDefaultActionPrevented ()
void PreventDefaultAction ()
SpellInfo const * GetSpellInfo () const
uint32 GetId () const
ObjectGuid GetCasterGUID () const
Unit * GetCaster () const
WorldObject * GetOwner () const
Unit * GetUnitOwner () const
DynamicObject * GetDynobjOwner () const
void Remove (AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
Aura * GetAura () const
AuraObjectType GetType () const
int32 GetDuration () const
void SetDuration (int32 duration, bool withMods=false)
void RefreshDuration ()
time_t GetApplyTime () const
int32 GetMaxDuration () const
void SetMaxDuration (int32 duration)
int32 CalcMaxDuration () const
bool IsExpired () const
bool IsPermanent () const
uint8 GetCharges () const
void SetCharges (uint8 charges)
uint8 CalcMaxCharges () const
bool ModCharges (int8 num, AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
bool DropCharge (AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
uint8 GetStackAmount () const
void SetStackAmount (uint8 num)
bool ModStackAmount (int32 num, AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
bool IsPassive () const
bool IsDeathPersistent () const
bool HasEffect (uint8 effIndex) const
AuraEffect * GetEffect (uint8 effIndex) const
bool HasEffectType (AuraType type) const
Unit * GetTarget () const
AuraApplication const * GetTargetApplication () const
Public Member Functions inherited from _SpellScript
_SpellScript ()
virtual ~_SpellScript ()
virtual void _Register ()
virtual void _Unload ()
virtual void _Init (std::string const *scriptname, uint32 spellId)
std::string const * _GetScriptName () const
virtual void Unload ()
Static Public Member Functions inherited from _SpellScript
static bool ValidateSpellInfo (std::initializer_list< uint32 > spellIds)
template<class T >
static bool ValidateSpellInfo (T const &spellIds)
Public Attributes inherited from AuraScript
HookList< CheckAreaTargetHandler > DoCheckAreaTarget
HookList< AuraDispelHandler > OnDispel
HookList< AuraDispelHandler > AfterDispel
HookList< EffectApplyHandler > OnEffectApply
HookList< EffectApplyHandler > AfterEffectApply
HookList< EffectApplyHandler > OnEffectRemove
HookList< EffectApplyHandler > AfterEffectRemove
HookList< EffectPeriodicHandler > OnEffectPeriodic
HookList< EffectUpdatePeriodicHandler > OnEffectUpdatePeriodic
HookList< EffectCalcAmountHandler > DoEffectCalcAmount
HookList< EffectCalcPeriodicHandler > DoEffectCalcPeriodic
HookList< EffectCalcSpellModHandler > DoEffectCalcSpellMod
HookList< EffectAbsorbHandler > OnEffectAbsorb
HookList< EffectAbsorbHandler > AfterEffectAbsorb
HookList< EffectManaShieldHandler > OnEffectManaShield
HookList< EffectManaShieldHandler > AfterEffectManaShield
HookList< EffectSplitHandler > OnEffectSplit
HookList< CheckProcHandler > DoCheckProc
HookList< CheckEffectProcHandler > DoCheckEffectProc
HookList< AfterCheckProcHandler > DoAfterCheckProc
HookList< AuraProcHandler > DoPrepareProc
HookList< AuraProcHandler > OnProc
HookList< AuraProcHandler > AfterProc
HookList< EffectProcHandler > OnEffectProc
HookList< EffectProcHandler > AfterEffectProc
Protected Attributes inherited from _SpellScript
uint8 m_currentScriptState
std::string const * m_scriptName
uint32 m_scriptSpellId
Detailed Description
Member Function Documentation
HandleApplyDoT()
void spell_pal_seal_of_vengeance_aura::HandleApplyDoT (AuraEffect const * aurEff, ProcEventInfo & eventInfo) inline private
    {
        PreventDefaultAction();
        if (!(eventInfo.GetTypeMask() & PROC_FLAG_DONE_MELEE_AUTO_ATTACK))
        {
            SpellInfo const* spellInfo = eventInfo.GetSpellInfo();
            if (!spellInfo || spellInfo->SpellIconID != PALADIN_ICON_HAMMER_OF_THE_RIGHTEOUS)
                return;
        }
        uint32 dotSpell = _isVengeance ? SPELL_PALADIN_HOLY_VENGEANCE : SPELL_PALADIN_BLOOD_CORRUPTION;
        eventInfo.GetActor()->CastSpell(eventInfo.GetActionTarget(), dotSpell, true, nullptr, aurEff);
    }
References _isVengeance, Unit::CastSpell(), ProcEventInfo::GetActionTarget(), ProcEventInfo::GetActor(), ProcEventInfo::GetSpellInfo(), ProcEventInfo::GetTypeMask(), PALADIN_ICON_HAMMER_OF_THE_RIGHTEOUS, AuraScript::PreventDefaultAction(), PROC_FLAG_DONE_MELEE_AUTO_ATTACK, SPELL_PALADIN_BLOOD_CORRUPTION, SPELL_PALADIN_HOLY_VENGEANCE, and SpellInfo::SpellIconID.
Referenced by Register().
HandleSeal()
void spell_pal_seal_of_vengeance_aura::HandleSeal (AuraEffect const * aurEff, ProcEventInfo & eventInfo) inline private
    {
        PreventDefaultAction();
        Unit* caster = eventInfo.GetActor();
        Unit* target = eventInfo.GetActionTarget();
        AuraEffect const* sealDot = target->GetAuraEffect(SPELL_AURA_PERIODIC_DAMAGE, SPELLFAMILY_PALADIN, 0x00000000, 0x00000800, 0x00000000, caster->GetGUID());
        if (!sealDot)
            return;
        uint8 stacks = sealDot->GetBase()->GetStackAmount();
        uint8 maxStacks = sealDot->GetSpellInfo()->StackAmount;
        uint32 damageSpell = _isVengeance ? SPELL_PALADIN_SEAL_OF_VENGEANCE_EFFECT : SPELL_PALADIN_SEAL_OF_CORRUPTION_EFFECT;
        // Scale weapon damage % by stacks (6.6% per stack, up to 33% at 5 stacks)
        SpellInfo const* spellInfo = sSpellMgr->GetSpellInfo(damageSpell);
        int32 amount = spellInfo->Effects[EFFECT_0].CalcValue();
        amount = (amount * stacks) / maxStacks;
        caster->CastCustomSpell(damageSpell, SPELLVALUE_BASE_POINT0, amount, target, true, nullptr, aurEff);
    }
References _isVengeance, Unit::CastCustomSpell(), EFFECT_0, SpellInfo::Effects, ProcEventInfo::GetActionTarget(), ProcEventInfo::GetActor(), Unit::GetAuraEffect(), AuraEffect::GetBase(), Object::GetGUID(), AuraEffect::GetSpellInfo(), Aura::GetStackAmount(), AuraScript::PreventDefaultAction(), SPELL_AURA_PERIODIC_DAMAGE, SPELL_PALADIN_SEAL_OF_CORRUPTION_EFFECT, SPELL_PALADIN_SEAL_OF_VENGEANCE_EFFECT, SPELLFAMILY_PALADIN, SPELLVALUE_BASE_POINT0, sSpellMgr, and SpellInfo::StackAmount.
Referenced by Register().
Load()
bool spell_pal_seal_of_vengeance_aura::Load () inline override private virtual
Reimplemented from _SpellScript.
    {
        // Seal of Vengeance = 31801, Seal of Corruption = 53736
        _isVengeance = GetSpellInfo()->Id == 31801;
        return true;
    }
References _isVengeance, AuraScript::GetSpellInfo(), and SpellInfo::Id.
PrepareAuraScript()
spell_pal_seal_of_vengeance_aura::PrepareAuraScript (spell_pal_seal_of_vengeance_aura) private
Register()
void spell_pal_seal_of_vengeance_aura::Register () inline override private virtual
Implements _SpellScript.
    {
        OnEffectProc += AuraEffectProcFn(spell_pal_seal_of_vengeance_aura::HandleApplyDoT, EFFECT_0, SPELL_AURA_DUMMY);
        OnEffectProc += AuraEffectProcFn(spell_pal_seal_of_vengeance_aura::HandleSeal, EFFECT_0, SPELL_AURA_DUMMY);
    }
References AuraEffectProcFn, EFFECT_0, HandleApplyDoT(), HandleSeal(), AuraScript::OnEffectProc, and SPELL_AURA_DUMMY.
Validate()
bool spell_pal_seal_of_vengeance_aura::Validate (SpellInfo const *) inline override private virtual
Reimplemented from _SpellScript.
    {
        return ValidateSpellInfo(
        {
            SPELL_PALADIN_HOLY_VENGEANCE,
            SPELL_PALADIN_BLOOD_CORRUPTION,
            SPELL_PALADIN_SEAL_OF_VENGEANCE_EFFECT,
            SPELL_PALADIN_SEAL_OF_CORRUPTION_EFFECT
        });
    }
References SPELL_PALADIN_BLOOD_CORRUPTION, SPELL_PALADIN_HOLY_VENGEANCE, SPELL_PALADIN_SEAL_OF_CORRUPTION_EFFECT, SPELL_PALADIN_SEAL_OF_VENGEANCE_EFFECT, and _SpellScript::ValidateSpellInfo().
Member Data Documentation
_isVengeance
bool spell_pal_seal_of_vengeance_aura::_isVengeance = true private
Referenced by HandleApplyDoT(), HandleSeal(), and Load().
The documentation for this class was generated from the following file:
azerothcore-wotlk/src/server/scripts/Spells/spell_paladin.cpp