AzerothCore Doxygen
StaticVMapCollisionData Class Reference
#include "MapCollisionData.h"
Public Member Functions
StaticVMapCollisionData (uint32 mapId)
bool isInLineOfSight (float x1, float y1, float z1, float x2, float y2, float z2, VMAP::ModelIgnoreFlags ignoreFlags) const
bool GetObjectHitPos (float x1, float y1, float z1, float x2, float y2, float z2, float &rx, float &ry, float &rz, float modifyDist) const
float getHeight (float x, float y, float z, float maxSearchDist) const
bool GetAreaAndLiquidData (float x, float y, float z, Optional< uint8 > reqLiquidType, VMAP::AreaAndLiquidData &data) const
Protected Attributes
std::shared_ptr< VMAP::StaticMapTree > _staticTree
uint32 _mapId
Friends
class MapCollisionData
Detailed Description
Constructor & Destructor Documentation
StaticVMapCollisionData()
StaticVMapCollisionData::StaticVMapCollisionData (uint32 mapId) inline
: _mapId(mapId) {}
Member Function Documentation
GetAreaAndLiquidData()
bool StaticVMapCollisionData::GetAreaAndLiquidData (float x, float y, float z, Optional< uint8 > reqLiquidType, VMAP::AreaAndLiquidData & data) const
{
    if (_staticTree)
    {
        VMAP::LocationInfo info;
        G3D::Vector3 const pos = VMAP::VMapMgr2::convertPositionToInternalRep(x, y, z);
        if (_staticTree->GetLocationInfo(pos, info))
        {
            data.floorZ = info.ground_Z;
            if (!DisableMgr::IsVMAPDisabledFor(_mapId, VMAP::VMAP_DISABLE_LIQUIDSTATUS))
            {
                uint32 liquidType = info.hitModel->GetLiquidType(); // entry from LiquidType.dbc
                float liquidLevel;
                if (!reqLiquidType || (GetLiquidFlags(liquidType) & *reqLiquidType))
                    if (info.hitInstance->GetLiquidLevel(pos, info, liquidLevel))
                        data.liquidInfo.emplace(liquidType, liquidLevel);
            }
            if (!DisableMgr::IsVMAPDisabledFor(_mapId, VMAP::VMAP_DISABLE_AREAFLAG))
                data.areaInfo.emplace(info.hitModel->GetWmoID(), info.hitInstance->adtId, info.rootId, info.hitModel->GetMogpFlags(), info.hitInstance->ID);
            return true;
        }
    }
    return false;
}
References _mapId, _staticTree, VMAP::ModelSpawn::adtId, VMAP::AreaAndLiquidData::areaInfo, VMAP::VMapMgr2::convertPositionToInternalRep(), VMAP::AreaAndLiquidData::floorZ, GetLiquidFlags(), VMAP::ModelInstance::GetLiquidLevel(), VMAP::GroupModel::GetLiquidType(), VMAP::GroupModel::GetMogpFlags(), VMAP::GroupModel::GetWmoID(), VMAP::LocationInfo::ground_Z, VMAP::LocationInfo::hitInstance, VMAP::LocationInfo::hitModel, VMAP::ModelSpawn::ID, DisableMgr::IsVMAPDisabledFor(), VMAP::AreaAndLiquidData::liquidInfo, VMAP::LocationInfo::rootId, VMAP::VMAP_DISABLE_AREAFLAG, and VMAP::VMAP_DISABLE_LIQUIDSTATUS.
Referenced by Map::GetAreaInfo(), Map::GetFullTerrainStatusForPosition(), and Map::GetLiquidData().
getHeight()
float StaticVMapCollisionData::getHeight (float x, float y, float z, float maxSearchDist) const
{
#if defined(ENABLE_VMAP_CHECKS)
    if (sWorld->getBoolConfig(CONFIG_VMAP_ENABLE_HEIGHT) && !DisableMgr::IsVMAPDisabledFor(_mapId, VMAP::VMAP_DISABLE_HEIGHT))
#endif
    {
        if (_staticTree)
        {
            G3D::Vector3 const pos = VMAP::VMapMgr2::convertPositionToInternalRep(x, y, z);
            float height = _staticTree->getHeight(pos, maxSearchDist);
            if (height >= G3D::finf())
                return VMAP_INVALID_HEIGHT_VALUE; // No height
            return height;
        }
    }
    return VMAP_INVALID_HEIGHT_VALUE;
}
References _mapId, _staticTree, CONFIG_VMAP_ENABLE_HEIGHT, VMAP::VMapMgr2::convertPositionToInternalRep(), DisableMgr::IsVMAPDisabledFor(), sWorld, VMAP::VMAP_DISABLE_HEIGHT, and VMAP_INVALID_HEIGHT_VALUE.
Referenced by Map::GetHeight().
GetObjectHitPos()
bool StaticVMapCollisionData::GetObjectHitPos (float x1, float y1, float z1, float x2, float y2, float z2, float & rx, float & ry, float & rz, float modifyDist) const
{
#if defined(ENABLE_VMAP_CHECKS)
    if (sWorld->getBoolConfig(CONFIG_VMAP_ENABLE_LOS) && !DisableMgr::IsVMAPDisabledFor(_mapId, VMAP::VMAP_DISABLE_LOS))
#endif
    {
        if (_staticTree)
        {
            G3D::Vector3 const pos1 = VMAP::VMapMgr2::convertPositionToInternalRep(x1, y1, z1);
            G3D::Vector3 const pos2 = VMAP::VMapMgr2::convertPositionToInternalRep(x2, y2, z2);
            G3D::Vector3 resultPos;
            bool result = _staticTree->GetObjectHitPos(pos1, pos2, resultPos, modifyDist);
            resultPos = VMAP::VMapMgr2::convertPositionToInternalRep(resultPos.x, resultPos.y, resultPos.z);
            rx = resultPos.x;
            ry = resultPos.y;
            rz = resultPos.z;
            return result;
        }
    }
    rx = x2;
    ry = y2;
    rz = z2;
    return false;
}
References _mapId, _staticTree, CONFIG_VMAP_ENABLE_LOS, VMAP::VMapMgr2::convertPositionToInternalRep(), DisableMgr::IsVMAPDisabledFor(), sWorld, and VMAP::VMAP_DISABLE_LOS.
Referenced by Map::CheckCollisionAndGetValidCoords(), spell_entropius_black_hole_effect::RaycastToObstacle(), and Spell::SelectImplicitCasterDestTargets().
isInLineOfSight()
bool StaticVMapCollisionData::isInLineOfSight (float x1, float y1, float z1, float x2, float y2, float z2, VMAP::ModelIgnoreFlags ignoreFlags) const
{
#if defined(ENABLE_VMAP_CHECKS)
    if (!sWorld->getBoolConfig(CONFIG_VMAP_ENABLE_LOS) || DisableMgr::IsVMAPDisabledFor(_mapId, VMAP::VMAP_DISABLE_LOS))
        return true;
#endif
    if (!_staticTree)
        return true;
    G3D::Vector3 const pos1 = VMAP::VMapMgr2::convertPositionToInternalRep(x1, y1, z1);
    G3D::Vector3 const pos2 = VMAP::VMapMgr2::convertPositionToInternalRep(x2, y2, z2);
    if (pos1 != pos2)
        return _staticTree->isInLineOfSight(pos1, pos2, ignoreFlags);
    return true;
}
References _mapId, _staticTree, CONFIG_VMAP_ENABLE_LOS, VMAP::VMapMgr2::convertPositionToInternalRep(), DisableMgr::IsVMAPDisabledFor(), sWorld, and VMAP::VMAP_DISABLE_LOS.
Referenced by Map::isInLineOfSight().
Friends And Related Symbol Documentation
MapCollisionData
friend class MapCollisionData friend
Member Data Documentation
_mapId
uint32 StaticVMapCollisionData::_mapId protected
Referenced by GetAreaAndLiquidData(), getHeight(), GetObjectHitPos(), and isInLineOfSight().
_staticTree
std::shared_ptr<VMAP::StaticMapTree> StaticVMapCollisionData::_staticTree protected
Referenced by GetAreaAndLiquidData(), getHeight(), GetObjectHitPos(), MapCollisionData::GetStaticTreeSharedPtr(), isInLineOfSight(), MapCollisionData::LoadVMapTile(), and MapCollisionData::MapCollisionData().
The documentation for this class was generated from the following files:
azerothcore-wotlk/src/server/game/Maps/MapCollisionData.h
azerothcore-wotlk/src/server/game/Maps/MapCollisionData.cpp