AzerothCore Doxygen
gm_commandscript Class Reference
Public Member Functions
gm_commandscript ()
ChatCommandTable GetCommands () const override
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
uint16 GetTotalAvailableHooks ()
Static Public Member Functions
static bool HandleGMChatCommand (ChatHandler *handler, Optional< bool > enableArg)
static bool HandleGMFlyCommand (ChatHandler *handler, Optional< bool > enable)
static bool HandleGMListIngameCommand (ChatHandler *handler)
static bool HandleGMListFullCommand (ChatHandler *handler)
Display the list of GMs.
static bool HandleGMVisibleCommand (ChatHandler *handler, Optional< bool > visibleArg)
static bool HandleGMOnCommand (ChatHandler *handler)
static bool HandleGMOffCommand (ChatHandler *handler)
static bool HandleGMSpectatorCommand (ChatHandler *handler, Optional< bool > enable)
Additional Inherited Members
Protected Member Functions inherited from CommandScript
CommandScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name, uint16 totalAvailableHooks=0)
virtual ~ScriptObject ()=default
Detailed Description
Constructor & Destructor Documentation
gm_commandscript()
gm_commandscript::gm_commandscript () inline
: CommandScript("gm_commandscript") { }
Member Function Documentation
GetCommands()
ChatCommandTable gm_commandscript::GetCommands () const inline override virtual
Implements CommandScript.
    {
        static ChatCommandTable gmCommandTable =
        {
            { "chat",      HandleGMChatCommand,       SEC_GAMEMASTER,     Console::No  },
            { "fly",       HandleGMFlyCommand,        SEC_GAMEMASTER,     Console::No  },
            { "ingame",    HandleGMListIngameCommand, SEC_PLAYER,         Console::Yes },
            { "list",      HandleGMListFullCommand,   SEC_ADMINISTRATOR,  Console::Yes },
            { "visible",   HandleGMVisibleCommand,    SEC_GAMEMASTER,     Console::No  },
            { "on",        HandleGMOnCommand,         SEC_MODERATOR,      Console::No  },
            { "off",       HandleGMOffCommand,        SEC_MODERATOR,      Console::No  },
            { "spectator", HandleGMSpectatorCommand,  SEC_GAMEMASTER,     Console::No  },
        };
        static ChatCommandTable commandTable =
        {
            { "gm", gmCommandTable }
        };
        return commandTable;
    }
References HandleGMChatCommand(), HandleGMFlyCommand(), HandleGMListFullCommand(), HandleGMListIngameCommand(), HandleGMOffCommand(), HandleGMOnCommand(), HandleGMSpectatorCommand(), HandleGMVisibleCommand(), SEC_ADMINISTRATOR, SEC_GAMEMASTER, SEC_MODERATOR, and SEC_PLAYER.
HandleGMChatCommand()
static bool gm_commandscript::HandleGMChatCommand (ChatHandler * handler, Optional< bool > enableArg) inline static
    {
        if (WorldSession* session = handler->GetSession())
        {
            if (!enableArg)
            {
                if (!AccountMgr::IsPlayerAccount(session->GetSecurity()) && session->GetPlayer()->isGMChat())
                    handler->SendNotification(LANG_GM_CHAT_ON);
                else
                    handler->SendNotification(LANG_GM_CHAT_OFF);
                return true;
            }
            if (*enableArg)
            {
                session->GetPlayer()->SetGMChat(true);
                handler->SendNotification(LANG_GM_CHAT_ON);
                return true;
            }
            else
            {
                session->GetPlayer()->SetGMChat(false);
                handler->SendNotification(LANG_GM_CHAT_OFF);
                return true;
            }
        }
        handler->SendErrorMessage(LANG_USE_BOL);
        return false;
    }
References ChatHandler::GetSession(), AccountMgr::IsPlayerAccount(), LANG_GM_CHAT_OFF, LANG_GM_CHAT_ON, LANG_USE_BOL, ChatHandler::SendErrorMessage(), and ChatHandler::SendNotification().
Referenced by GetCommands().
HandleGMFlyCommand()
static bool gm_commandscript::HandleGMFlyCommand (ChatHandler * handler, Optional< bool > enable) inline static
    {
        Player* target = handler->getSelectedPlayer();
        if (!target)
            target = handler->GetSession()->GetPlayer();
        bool canFly = false;
        if (enable.has_value())
        {
            canFly = *enable;
            target->SetCanFly(canFly);
        }
        else
        {
            canFly = !handler->GetSession()->GetPlayer()->CanFly();
            target->SetCanFly(canFly);
        }
        handler->PSendSysMessage(LANG_COMMAND_FLYMODE_STATUS, handler->GetNameLink(target), canFly ? "on" : "off");
        return true;
    }
References Player::CanFly(), ChatHandler::GetNameLink(), WorldSession::GetPlayer(), ChatHandler::getSelectedPlayer(), ChatHandler::GetSession(), LANG_COMMAND_FLYMODE_STATUS, ChatHandler::PSendSysMessage(), and Unit::SetCanFly().
Referenced by GetCommands().
HandleGMListFullCommand()
static bool gm_commandscript::HandleGMListFullCommand (ChatHandler * handler) inline static
Display the list of GMs.
Get the accounts with GM Level >0
Cycle through them. Display username and GM level
    {
        LoginDatabasePreparedStatement* stmt = LoginDatabase.GetPreparedStatement(LOGIN_SEL_GM_ACCOUNTS);
        stmt->SetData(0, uint8(SEC_MODERATOR));
        stmt->SetData(1, int32(realm.Id.Realm));
        PreparedQueryResult result = LoginDatabase.Query(stmt);
        if (result)
        {
            handler->SendSysMessage(LANG_GMLIST);
            handler->SendSysMessage("========================");
            do
            {
                Field* fields = result->Fetch();
                std::string name = fields[0].Get<std::string>();
                uint8 security = fields[1].Get<uint8>();
                uint8 max = (16 - name.length()) / 2;
                uint8 max2 = max;
                if ((max + max2 + name.length()) == 16)
                    max2 = max - 1;
                if (handler->GetSession())
                    handler->PSendSysMessage("|    {} GMLevel {}", name, security);
                else
                    handler->PSendSysMessage("|{}{}{}|   {}  |", max, " ", name, max2, " ", security);
            } while (result->NextRow());
            handler->SendSysMessage("========================");
        }
        else
            handler->PSendSysMessage(LANG_GMLIST_EMPTY);
        return true;
    }
References Field::Get(), ChatHandler::GetSession(), Realm::Id, LANG_GMLIST, LANG_GMLIST_EMPTY, LOGIN_SEL_GM_ACCOUNTS, LoginDatabase, ChatHandler::PSendSysMessage(), realm, RealmHandle::Realm, SEC_MODERATOR, ChatHandler::SendSysMessage(), and PreparedStatementBase::SetData().
Referenced by GetCommands().
HandleGMListIngameCommand()
static bool gm_commandscript::HandleGMListIngameCommand (ChatHandler * handler) inline static
    {
        bool first = true;
        bool footer = false;
        std::shared_lock<std::shared_mutex> lock(*HashMapHolder<Player>::GetLock());
        for (auto const& [playerGuid, player] : ObjectAccessor::GetPlayers())
        {
            AccountTypes playerSec = player->GetSession()->GetSecurity();
            if ((player->IsGameMaster() ||
                 (!AccountMgr::IsPlayerAccount(playerSec) && playerSec <= AccountTypes(sWorld->getIntConfig(CONFIG_GM_LEVEL_IN_GM_LIST)))) &&
                (!handler->GetSession() || player->IsVisibleGloballyFor(handler->GetSession()->GetPlayer())))
            {
                if (first)
                {
                    first = false;
                    footer = true;
                    handler->SendSysMessage(LANG_GMS_ON_SRV);
                    handler->SendSysMessage("========================");
                }
                std::string const& name = player->GetName();
                uint8 size = uint8(name.size());
                uint8 security = playerSec;
                uint8 max = ((16 - size) / 2);
                uint8 max2 = max;
                if ((max + max2 + size) == 16)
                    max2 = max - 1;
                if (handler->GetSession())
                    handler->PSendSysMessage("|    {} GMLevel {}", name, security);
                else
                    handler->PSendSysMessage("|{}{}{}|   {}  |", max, " ", name, max2, " ", security);
            }
        }
        if (footer)
            handler->SendSysMessage("========================");
        if (first)
            handler->SendSysMessage(LANG_GMS_NOT_LOGGED);
        return true;
    }
References CONFIG_GM_LEVEL_IN_GM_LIST, WorldSession::GetPlayer(), ObjectAccessor::GetPlayers(), ChatHandler::GetSession(), AccountMgr::IsPlayerAccount(), LANG_GMS_NOT_LOGGED, LANG_GMS_ON_SRV, ChatHandler::PSendSysMessage(), ChatHandler::SendSysMessage(), and sWorld.
Referenced by GetCommands().
HandleGMOffCommand()
static bool gm_commandscript::HandleGMOffCommand (ChatHandler * handler) inline static
    {
        handler->GetPlayer()->SetGameMaster(false);
        handler->GetPlayer()->UpdateTriggerVisibility();
        handler->SendNotification(LANG_GM_OFF);
        return true;
    }
References ChatHandler::GetPlayer(), LANG_GM_OFF, ChatHandler::SendNotification(), Player::SetGameMaster(), and Player::UpdateTriggerVisibility().
Referenced by GetCommands().
HandleGMOnCommand()
static bool gm_commandscript::HandleGMOnCommand (ChatHandler * handler) inline static
    {
        handler->GetPlayer()->SetGameMaster(true);
        handler->GetPlayer()->UpdateTriggerVisibility();
        handler->SendNotification(LANG_GM_ON);
        return true;
    }
References ChatHandler::GetPlayer(), LANG_GM_ON, ChatHandler::SendNotification(), Player::SetGameMaster(), and Player::UpdateTriggerVisibility().
Referenced by GetCommands().
HandleGMSpectatorCommand()
static bool gm_commandscript::HandleGMSpectatorCommand (ChatHandler * handler, Optional< bool > enable) inline static
    {
        Player* player = handler->GetSession()->GetPlayer();
        if (enable.has_value())
            player->SetGMSpectator(*enable);
        else
            player->SetGMSpectator(!player->IsGMSpectator());
        handler->SendNotification(player->IsGMSpectator() ? LANG_GM_SPECTATOR_ON : LANG_GM_SPECTATOR_OFF);
        return true;
    }
References WorldSession::GetPlayer(), ChatHandler::GetSession(), Player::IsGMSpectator(), LANG_GM_SPECTATOR_OFF, LANG_GM_SPECTATOR_ON, ChatHandler::SendNotification(), and Player::SetGMSpectator().
Referenced by GetCommands().
HandleGMVisibleCommand()
static bool gm_commandscript::HandleGMVisibleCommand (ChatHandler * handler, Optional< bool > visibleArg) inline static
    {
        Player* _player = handler->GetSession()->GetPlayer();
        if (!visibleArg)
        {
            handler->PSendSysMessage(LANG_YOU_ARE, _player->isGMVisible() ? handler->GetAcoreString(LANG_VISIBLE) : handler->GetAcoreString(LANG_INVISIBLE));
            return true;
        }
        const uint32 VISUAL_AURA = 37800;
        if (*visibleArg)
        {
            if (_player->HasAura(VISUAL_AURA))
                _player->RemoveAurasDueToSpell(VISUAL_AURA);
            _player->SetGMVisible(true);
            _player->UpdateObjectVisibility();
            handler->SendNotification(LANG_INVISIBLE_VISIBLE);
        }
        else
        {
            _player->AddAura(VISUAL_AURA, _player);
            _player->SetGMVisible(false);
            _player->UpdateObjectVisibility();
            handler->SendNotification(LANG_INVISIBLE_INVISIBLE);
        }
        return true;
    }
References Unit::AddAura(), ChatHandler::GetAcoreString(), WorldSession::GetPlayer(), ChatHandler::GetSession(), Unit::HasAura(), Player::isGMVisible(), LANG_INVISIBLE, LANG_INVISIBLE_INVISIBLE, LANG_INVISIBLE_VISIBLE, LANG_VISIBLE, LANG_YOU_ARE, ChatHandler::PSendSysMessage(), Unit::RemoveAurasDueToSpell(), ChatHandler::SendNotification(), Player::SetGMVisible(), and Player::UpdateObjectVisibility().
Referenced by GetCommands().
The documentation for this class was generated from the following file:
azerothcore-wotlk/src/server/scripts/Commands/cs_gm.cpp