AzerothCore Doxygen
PetitionMgr Class Reference
#include "PetitionMgr.h"
Public Member Functions
void LoadPetitions ()
void LoadSignatures ()
void AddPetition (ObjectGuid petitionGUID, ObjectGuid ownerGuid, std::string const &name, uint8 type, uint32 petitionId)
void RemovePetition (ObjectGuid petitionGUID)
void RemovePetitionByOwnerAndType (ObjectGuid ownerGuid, uint8 type)
Petition const * GetPetition (ObjectGuid petitionGUID) const
Petition const * GetPetitionById (uint32 petitionId) const
Petition const * GetPetitionByOwnerWithType (ObjectGuid ownerGuid, uint8 type) const
PetitionContainer * GetPetitionStore ()
void AddSignature (ObjectGuid petitionGUID, uint32 accountId, ObjectGuid playerGuid)
void RemoveSignaturesByPlayer (ObjectGuid playerGuid)
void RemoveSignaturesByPlayerAndType (ObjectGuid playerGuid, uint8 type)
Signatures const * GetSignature (ObjectGuid petitionGUID) const
SignatureContainer * GetSignatureStore ()
uint32 GeneratePetitionId ()
uint32 GetPetitionIdByItemGuid (ObjectGuid petitionItemGuid) const
ObjectGuid GetItemGuidByPetitionId (uint32 petitionId) const
Static Public Member Functions
static PetitionMgr * instance ()
Protected Attributes
PetitionContainer PetitionStore
SignatureContainer SignatureStore
std::unordered_map< uint32, ObjectGuid > PetitionIdToItemGuid
uint32 _nextPetitionId = 1
Private Member Functions
PetitionMgr ()
~PetitionMgr ()
Detailed Description
Constructor & Destructor Documentation
PetitionMgr()
PetitionMgr::PetitionMgr () private
{
}
~PetitionMgr()
PetitionMgr::~PetitionMgr () private
{
}
Member Function Documentation
AddPetition()
void PetitionMgr::AddPetition (ObjectGuid petitionGUID, ObjectGuid ownerGuid, std::string const & name, uint8 type, uint32 petitionId)
{
    Petition& p = PetitionStore[petitionGUID];
    p.petitionGuid = petitionGUID;
    p.petitionId = petitionId;
    p.ownerGuid = ownerGuid;
    p.petitionName = name;
    p.petitionType = type;
    Signatures& s = SignatureStore[petitionGUID];
    s.petitionGuid = petitionGUID;
    s.signatureMap.clear();
}
References Petition::ownerGuid, Petition::petitionGuid, Signatures::petitionGuid, Petition::petitionId, Petition::petitionName, PetitionStore, Petition::petitionType, Signatures::signatureMap, and SignatureStore.
Referenced by LoadPetitions().
AddSignature()
void PetitionMgr::AddSignature (ObjectGuid petitionGUID, uint32 accountId, ObjectGuid playerGuid)
{
    Signatures& s = SignatureStore[petitionGUID];
    s.signatureMap[playerGuid] = accountId;
}
References Signatures::signatureMap, and SignatureStore.
Referenced by LoadSignatures().
GeneratePetitionId()
uint32 PetitionMgr::GeneratePetitionId ()
{
    // ensure 31-bit range and avoid collisions with already loaded petitions
    if (_nextPetitionId == 0 || _nextPetitionId >= 0x7FFFFFFF)
        _nextPetitionId = 1;
    // find first free id
    while (PetitionIdToItemGuid.count(_nextPetitionId))
    {
        ++_nextPetitionId;
        if (_nextPetitionId >= 0x7FFFFFFF)
            _nextPetitionId = 1;
    }
    uint32 id = _nextPetitionId++;
    if (_nextPetitionId >= 0x7FFFFFFF)
        _nextPetitionId = 1;
    return id;
}
References _nextPetitionId, and PetitionIdToItemGuid.
GetItemGuidByPetitionId()
ObjectGuid PetitionMgr::GetItemGuidByPetitionId (uint32 petitionId) const
{
    auto it = PetitionIdToItemGuid.find(petitionId);
    if (it == PetitionIdToItemGuid.end())
        return ObjectGuid::Empty;
    return it->second;
}
References ObjectGuid::Empty, and PetitionIdToItemGuid.
GetPetition()
Petition const * PetitionMgr::GetPetition (ObjectGuid petitionGUID) const
{
    PetitionContainer::const_iterator itr = PetitionStore.find(petitionGUID);
    if (itr != PetitionStore.end())
        return &itr->second;
    return nullptr;
}
References PetitionStore.
Referenced by GetPetitionById(), and GetPetitionIdByItemGuid().
GetPetitionById()
Petition const * PetitionMgr::GetPetitionById (uint32 petitionId) const
{
    auto it = PetitionIdToItemGuid.find(petitionId);
    if (it == PetitionIdToItemGuid.end())
        return nullptr;
    return GetPetition(it->second);
}
References GetPetition(), and PetitionIdToItemGuid.
GetPetitionByOwnerWithType()
Petition const * PetitionMgr::GetPetitionByOwnerWithType (ObjectGuid ownerGuid, uint8 type) const
{
    for (PetitionContainer::const_iterator itr = PetitionStore.begin(); itr != PetitionStore.end(); ++itr)
        if (itr->second.ownerGuid == ownerGuid && itr->second.petitionType == type)
            return &itr->second;
    return nullptr;
}
References PetitionStore.
GetPetitionIdByItemGuid()
uint32 PetitionMgr::GetPetitionIdByItemGuid (ObjectGuid petitionItemGuid) const
{
    Petition const* p = GetPetition(petitionItemGuid);
    return p ? p->petitionId : 0;
}
References GetPetition(), and Petition::petitionId.
GetPetitionStore()
PetitionContainer * PetitionMgr::GetPetitionStore () inline
{ return &PetitionStore; }
References PetitionStore.
GetSignature()
Signatures const * PetitionMgr::GetSignature (ObjectGuid petitionGUID) const
{
    SignatureContainer::const_iterator itr = SignatureStore.find(petitionGUID);
    if (itr != SignatureStore.end())
        return &itr->second;
    return nullptr;
}
References SignatureStore.
GetSignatureStore()
SignatureContainer * PetitionMgr::GetSignatureStore () inline
{ return &SignatureStore; }
References SignatureStore.
instance()
PetitionMgr * PetitionMgr::instance () static
{
    static PetitionMgr instance;
    return &instance;
}
References instance().
Referenced by instance().
LoadPetitions()
void PetitionMgr::LoadPetitions ()
{
    uint32 oldMSTime = getMSTime();
    PetitionStore.clear();
    PetitionIdToItemGuid.clear();
    QueryResult result = CharacterDatabase.Query("SELECT ownerguid, petitionguid, name, type, petition_id FROM petition");
    if (!result)
    {
        LOG_WARN("server.loading", ">> Loaded 0 Petitions!");
        LOG_INFO("server.loading", " ");
        return;
    }
    uint32 count = 0;
    uint32 maxId = 0;
    do
    {
        Field* fields = result->Fetch();
        uint32 itemLow = fields[1].Get<uint32>();
        uint32 petitionId = fields[4].Get<uint32>();
        ObjectGuid itemGuid = ObjectGuid::Create<HighGuid::Item>(itemLow);
        ObjectGuid ownerGuid = ObjectGuid::Create<HighGuid::Player>(fields[0].Get<uint32>());
        AddPetition(itemGuid, ownerGuid, fields[2].Get<std::string>(), fields[3].Get<uint8>(), petitionId);
        PetitionIdToItemGuid[petitionId] = itemGuid;
        if (petitionId > maxId)
            maxId = petitionId;
        ++count;
    } while (result->NextRow());
    // initialize next id (keep within 31-bit safe range)
    _nextPetitionId = std::min<uint32>(std::max<uint32>(maxId + 1, 1), 0x7FFFFFFFu);
    LOG_INFO("server.loading", ">> Loaded {} Petitions in {} ms", count, GetMSTimeDiffToNow(oldMSTime));
    LOG_INFO("server.loading", " ");
}
References _nextPetitionId, AddPetition(), CharacterDatabase, Field::Get(), getMSTime(), GetMSTimeDiffToNow(), LOG_INFO, LOG_WARN, PetitionIdToItemGuid, and PetitionStore.
LoadSignatures()
void PetitionMgr::LoadSignatures ()
{
    uint32 oldMSTime = getMSTime();
    SignatureStore.clear();
    QueryResult result = CharacterDatabase.Query("SELECT petition_id, playerguid, player_account FROM petition_sign");
    if (!result)
    {
        LOG_WARN("server.loading", ">> Loaded 0 Petition signs!");
        LOG_INFO("server.loading", " ");
        return;
    }
    uint32 count = 0;
    do
    {
        Field* fields = result->Fetch();
        uint32 petitionId = fields[0].Get<uint32>();
        auto it = PetitionIdToItemGuid.find(petitionId);
        if (it == PetitionIdToItemGuid.end())
            continue; // orphan signature, skip
        AddSignature(it->second, fields[2].Get<uint32>(), ObjectGuid::Create<HighGuid::Player>(fields[1].Get<uint32>()));
        ++count;
    } while (result->NextRow());
    LOG_INFO("server.loading", ">> Loaded {} Petition signs in {} ms", count, GetMSTimeDiffToNow(oldMSTime));
    LOG_INFO("server.loading", " ");
}
References AddSignature(), CharacterDatabase, Field::Get(), getMSTime(), GetMSTimeDiffToNow(), LOG_INFO, LOG_WARN, PetitionIdToItemGuid, and SignatureStore.
RemovePetition()
void PetitionMgr::RemovePetition (ObjectGuid petitionGUID)
{
    auto it = PetitionStore.find(petitionGUID);
    if (it != PetitionStore.end())
    {
        PetitionIdToItemGuid.erase(it->second.petitionId);
        PetitionStore.erase(it);
    }
    // remove signatures
    SignatureStore.erase(petitionGUID);
}
References PetitionIdToItemGuid, PetitionStore, and SignatureStore.
RemovePetitionByOwnerAndType()
void PetitionMgr::RemovePetitionByOwnerAndType (ObjectGuid ownerGuid, uint8 type)
{
    for (PetitionContainer::iterator itr = PetitionStore.begin(); itr != PetitionStore.end();)
    {
        if (itr->second.ownerGuid == ownerGuid && (!type || type == itr->second.petitionType))
        {
            // Remove invalid charter item
            if (type == itr->second.petitionType)
            {
                if (Player* owner = ObjectAccessor::FindConnectedPlayer(ownerGuid))
                {
                    if (Item* item = owner->GetItemByGuid(itr->first))
                    {
                        owner->DestroyItem(item->GetBagSlot(), item->GetSlot(), true);
                    }
                }
            }
            // remove signatures
            SignatureStore.erase(itr->first);
            PetitionStore.erase(itr++);
        }
        else
            ++itr;
    }
}
References ObjectAccessor::FindConnectedPlayer(), PetitionStore, and SignatureStore.
RemoveSignaturesByPlayer()
void PetitionMgr::RemoveSignaturesByPlayer (ObjectGuid playerGuid)
{
    for (SignatureContainer::iterator itr = SignatureStore.begin(); itr != SignatureStore.end(); ++itr)
    {
        SignatureMap::iterator signItr = itr->second.signatureMap.find(playerGuid);
        if (signItr != itr->second.signatureMap.end())
            itr->second.signatureMap.erase(signItr);
    }
}
References Signatures::signatureMap, and SignatureStore.
RemoveSignaturesByPlayerAndType()
void PetitionMgr::RemoveSignaturesByPlayerAndType (ObjectGuid playerGuid, uint8 type)
{
    for (SignatureContainer::iterator itr = SignatureStore.begin(); itr != SignatureStore.end(); ++itr)
    {
        Petition const* petition = sPetitionMgr->GetPetition(itr->first);
        if (!petition || petition->petitionType != type)
            continue;
        SignatureMap::iterator signItr = itr->second.signatureMap.find(playerGuid);
        if (signItr != itr->second.signatureMap.end())
            itr->second.signatureMap.erase(signItr);
    }
}
References Petition::petitionType, SignatureStore, and sPetitionMgr.
Member Data Documentation
_nextPetitionId
uint32 PetitionMgr::_nextPetitionId = 1 protected
Referenced by GeneratePetitionId(), and LoadPetitions().
PetitionIdToItemGuid
std::unordered_map<uint32, ObjectGuid> PetitionMgr::PetitionIdToItemGuid protected
Referenced by GeneratePetitionId(), GetItemGuidByPetitionId(), GetPetitionById(), LoadPetitions(), LoadSignatures(), and RemovePetition().
PetitionStore
PetitionContainer PetitionMgr::PetitionStore protected
Referenced by AddPetition(), GetPetition(), GetPetitionByOwnerWithType(), GetPetitionStore(), LoadPetitions(), RemovePetition(), and RemovePetitionByOwnerAndType().
SignatureStore
SignatureContainer PetitionMgr::SignatureStore protected
Referenced by AddPetition(), AddSignature(), GetSignature(), GetSignatureStore(), LoadSignatures(), RemovePetition(), RemovePetitionByOwnerAndType(), RemoveSignaturesByPlayer(), and RemoveSignaturesByPlayerAndType().
The documentation for this class was generated from the following files:
azerothcore-wotlk/src/server/game/Petitions/PetitionMgr.h
azerothcore-wotlk/src/server/game/Petitions/PetitionMgr.cpp