AzerothCore Doxygen
npc_kernobee Class Reference
Classes
struct npc_kernobeeAI
Public Member Functions
npc_kernobee ()
CreatureAI * GetAI (Creature *creature) const override
bool OnQuestAccept (Player *player, Creature *creature, const Quest *quest) override
Public Member Functions inherited from CreatureScript
bool IsDatabaseBound () const override
virtual bool OnGossipHello (Player *, Creature *)
virtual bool OnGossipSelect (Player *, Creature *, uint32, uint32)
virtual bool OnGossipSelectCode (Player *, Creature *, uint32, uint32, const char *)
virtual bool OnQuestSelect (Player *, Creature *, Quest const *)
virtual bool OnQuestComplete (Player *, Creature *, Quest const *)
virtual bool OnQuestReward (Player *, Creature *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, Creature *)
virtual void OnFfaPvpStateUpdate (Creature *, bool)
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
uint16 GetTotalAvailableHooks ()
Public Member Functions inherited from UpdatableScript< Creature >
virtual void OnUpdate (Creature *, uint32)
Additional Inherited Members
Protected Member Functions inherited from CreatureScript
CreatureScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name, uint16 totalAvailableHooks=0)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< Creature >
UpdatableScript ()=default
Detailed Description
Constructor & Destructor Documentation
npc_kernobee()
npc_kernobee::npc_kernobee () inline
: CreatureScript("npc_kernobee") { }
Member Function Documentation
GetAI()
CreatureAI * npc_kernobee::GetAI (Creature * creature) const inline override virtual
Reimplemented from CreatureScript.
    {
        return GetGnomereganAI<npc_kernobeeAI>(creature);
    }
OnQuestAccept()
bool npc_kernobee::OnQuestAccept (Player * player, Creature * creature, const Quest * quest) inline override virtual
Reimplemented from CreatureScript.
    {
        if (quest->GetQuestId() == QUEST_A_FINE_MESS)
        {
            creature->SetStandState(UNIT_STAND_STATE_STAND);
            creature->AI()->SetGUID(player->GetGUID(), 0);
            creature->GetMotionMaster()->MoveFollow(player, PET_FOLLOW_DIST, M_PI, MOTION_SLOT_CONTROLLED);
        }
        return true;
    }
References Creature::AI(), Object::GetGUID(), Unit::GetMotionMaster(), Quest::GetQuestId(), MOTION_SLOT_CONTROLLED, MotionMaster::MoveFollow(), PET_FOLLOW_DIST, QUEST_A_FINE_MESS, UnitAI::SetGUID(), Unit::SetStandState(), and UNIT_STAND_STATE_STAND.
The documentation for this class was generated from the following file:
azerothcore-wotlk/src/server/scripts/EasternKingdoms/Gnomeregan/instance_gnomeregan.cpp