AzerothCore Doxygen
ProcChanceTestHelper Class Reference
Helper class for testing proc chance calculations.
#include "ProcChanceTestHelper.h"
Classes
struct ConditionsConfig
Configuration for simulating conditions system.
struct EquipmentConfig
Configuration for simulating equipment requirements.
struct PPMModifierConfig
PPM modifier configuration for testing SPELLMOD_PROC_PER_MINUTE.
struct TriggeredSpellConfig
Configuration for simulating triggered spell filtering.
Static Public Member Functions
static float CalculatePPMChance (uint32 weaponSpeed, float ppm, float ppmModifier=0.0f)
Calculate PPM proc chance Implements the formula: (WeaponSpeed * PPM) / 600.0f.
static float ApplyLevel60Reduction (float baseChance, uint32 actorLevel)
Calculate level 60+ reduction Implements PROC_ATTR_REDUCE_PROC_60: 3.333% reduction per level above 60.
static float SimulateCalcProcChance (SpellProcEntry const &procEntry, uint32 actorLevel=80, uint32 weaponSpeed=2500, float chanceModifier=0.0f, float ppmModifier=0.0f, bool hasDamageInfo=true, bool hasHealInfo=false)
Simulate CalcProcChance() from SpellAuras.cpp.
static bool SimulateConsumeProcCharges (AuraStub *aura, SpellProcEntry const &procEntry)
Simulate charge consumption from ConsumeProcCharges()
static bool IsProcOnCooldown (AuraStub const *aura, std::chrono::steady_clock::time_point now)
Check if proc is on cooldown.
static void ApplyProcCooldown (AuraStub *aura, std::chrono::steady_clock::time_point now, uint32 cooldownMs)
Apply proc cooldown to aura.
static bool SpellHasManaCost (SpellInfo const *spellInfo)
Check if spell has mana cost (for PROC_ATTR_REQ_MANA_COST)
static float CalculateEffectivePPM (float chancePerSwing, uint32 actualSwingSpeedMs)
Simulate effective procs per minute.
static bool ShouldBlockTriggeredSpell (TriggeredSpellConfig const &config, SpellProcEntry const &procEntry, uint32 eventTypeMask)
Simulate triggered spell filtering Implements the self-loop prevention and triggered spell blocking from SpellAuras.cpp.
static uint8 ApplyDisableEffectsMask (uint8 initialMask, uint32 disableEffectsMask)
Apply DisableEffectsMask to get final proc effect mask.
static bool ShouldBlockDueToDisabledEffects (uint8 initialMask, uint32 disableEffectsMask)
Check if proc should be blocked due to all effects being disabled.
static float CalculatePPMChanceWithModifiers (uint32 weaponSpeed, float basePPM, PPMModifierConfig const &modConfig)
Calculate PPM chance with spell modifiers Simulates GetPPMProcChance() with SPELLMOD_PROC_PER_MINUTE.
static bool ShouldBlockDueToEquipment (EquipmentConfig const &config)
Simulate equipment requirement check Returns true if proc should be blocked due to equipment requirements.
static uint8 GetWeaponSlotForAttackType (uint8 attackType)
Get equipment slot for attack type.
static bool ShouldBlockDueToConditions (ConditionsConfig const &config)
Simulate conditions check Returns true if proc should be blocked due to conditions.
Static Public Attributes
static constexpr uint32 WEAPON_SPEED_FAST_DAGGER = 1400
Get common weapon speeds for testing.
static constexpr uint32 WEAPON_SPEED_NORMAL_SWORD = 2500
static constexpr uint32 WEAPON_SPEED_SLOW_2H = 3300
static constexpr uint32 WEAPON_SPEED_VERY_SLOW = 3800
static constexpr uint32 WEAPON_SPEED_STAFF = 3600
static constexpr uint32 FORM_SPEED_CAT = 1000
Shapeshift form base attack speeds (from SpellShapeshiftForm.dbc)
static constexpr uint32 FORM_SPEED_BEAR = 2500
static constexpr float PPM_OMEN_OF_CLARITY = 6.0f
Common PPM values from spell_proc database.
static constexpr float PPM_JUDGEMENT_OF_LIGHT = 15.0f
static constexpr float PPM_WINDFURY_WEAPON = 2.0f
static constexpr uint32 AUTO_ATTACK_PROC_FLAG_MASK
Auto-attack proc flag mask (hunter auto-shot, wands exception) These triggered spells are allowed to proc without TRIGGERED_CAN_PROC.
static constexpr int32 ITEM_CLASS_WEAPON = 2
Item classes for equipment requirement checking.
static constexpr int32 ITEM_CLASS_ARMOR = 4
static constexpr int32 ITEM_CLASS_ANY = -1
static constexpr uint8 BASE_ATTACK = 0
Attack types for weapon slot mapping.
static constexpr uint8 OFF_ATTACK = 1
static constexpr uint8 RANGED_ATTACK = 2
Detailed Description
Helper class for testing proc chance calculations.
Provides standalone implementations of proc-related calculations that can be tested without requiring full game objects.
Member Function Documentation
ApplyDisableEffectsMask()
static uint8 ProcChanceTestHelper::ApplyDisableEffectsMask (uint8 initialMask, uint32 disableEffectsMask) inline static
Apply DisableEffectsMask to get final proc effect mask.
Parameters
initialMask Initial effect mask (usually 0x07 for all 3 effects)
disableEffectsMask Mask of effects to disable
Returns
Resulting effect mask after applying disable mask
    {
        uint8 result = initialMask;
        for (uint8 i = 0; i < 3; ++i)
        {
            if (disableEffectsMask & (1u << i))
                result &= ~(1 << i);
        }
        return result;
    }
Referenced by ShouldBlockDueToDisabledEffects(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
ApplyLevel60Reduction()
static float ProcChanceTestHelper::ApplyLevel60Reduction (float baseChance, uint32 actorLevel) inline static
Calculate level 60+ reduction Implements PROC_ATTR_REDUCE_PROC_60: 3.333% reduction per level above 60.
Parameters
baseChance Base proc chance
actorLevel Actor's level
Returns
Reduced proc chance
    {
        if (actorLevel <= 60)
            return baseChance;
        // Reduction = (level - 60) / 30, capped at 1.0
        float reduction = static_cast<float>(actorLevel - 60) / 30.0f;
        return std::max(0.0f, (1.0f - reduction) * baseChance);
    }
Referenced by SimulateCalcProcChance(), TEST_F(), and TEST_P().
ApplyProcCooldown()
static void ProcChanceTestHelper::ApplyProcCooldown (AuraStub * aura, std::chrono::steady_clock::time_point now, uint32 cooldownMs) inline static
Apply proc cooldown to aura.
Parameters
aura The aura stub
now Current time point
cooldownMs Cooldown duration in milliseconds
    {
        if (!aura || cooldownMs == 0)
            return;
        aura->AddProcCooldown(now + std::chrono::milliseconds(cooldownMs));
    }
References AuraStub::AddProcCooldown().
Referenced by ProcTestScenario::SimulateProc(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
CalculateEffectivePPM()
static float ProcChanceTestHelper::CalculateEffectivePPM (float chancePerSwing, uint32 actualSwingSpeedMs) inline static
Simulate effective procs per minute.
Given a per-swing chance and the actual swing interval, calculate how many procs occur per minute on average.
Parameters
chancePerSwing Proc chance per swing (0-100+)
actualSwingSpeedMs Actual time between swings in milliseconds
Returns
Average procs per minute
    {
        if (actualSwingSpeedMs == 0)
            return 0.0f;
        float swingsPerMinute = 60000.0f / static_cast<float>(actualSwingSpeedMs);
        return swingsPerMinute * (chancePerSwing / 100.0f);
    }
Referenced by TEST_F(), TEST_F(), TEST_F(), and TEST_F().
CalculatePPMChance()
static float ProcChanceTestHelper::CalculatePPMChance (uint32 weaponSpeed, float ppm, float ppmModifier = 0.0f) inline static
Calculate PPM proc chance Implements the formula: (WeaponSpeed * PPM) / 600.0f.
Parameters
weaponSpeed Weapon attack speed in milliseconds
ppm Procs per minute value
ppmModifier Additional PPM modifier (from talents/auras)
Returns
Proc chance as percentage (0-100+)
    {
        if (ppm <= 0.0f)
            return 0.0f;
        float modifiedPPM = ppm + ppmModifier;
        return (static_cast<float>(weaponSpeed) * modifiedPPM) / 600.0f;
    }
Referenced by SimulateCalcProcChance(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
CalculatePPMChanceWithModifiers()
static float ProcChanceTestHelper::CalculatePPMChanceWithModifiers (uint32 weaponSpeed, float basePPM, PPMModifierConfig const & modConfig) inline static
Calculate PPM chance with spell modifiers Simulates GetPPMProcChance() with SPELLMOD_PROC_PER_MINUTE.
    {
        if (basePPM <= 0.0f)
            return 0.0f;
        float ppm = basePPM;
        // Apply modifiers only if we have spell proto and spell mod owner
        if (modConfig.hasSpellProto && modConfig.hasSpellModOwner)
        {
            // Apply flat modifier first (SPELLMOD_FLAT)
            ppm += modConfig.flatModifier;
            // Apply percent modifier (SPELLMOD_PCT)
            ppm *= modConfig.pctModifier;
        }
        return (static_cast<float>(weaponSpeed) * ppm) / 600.0f;
    }
References ProcChanceTestHelper::PPMModifierConfig::flatModifier, ProcChanceTestHelper::PPMModifierConfig::hasSpellModOwner, ProcChanceTestHelper::PPMModifierConfig::hasSpellProto, and ProcChanceTestHelper::PPMModifierConfig::pctModifier.
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
GetWeaponSlotForAttackType()
static uint8 ProcChanceTestHelper::GetWeaponSlotForAttackType (uint8 attackType) inline static
Get equipment slot for attack type.
Parameters
attackType Attack type (BASE_ATTACK, OFF_ATTACK, RANGED_ATTACK)
Returns
Equipment slot index (simulated)
    {
        switch (attackType)
        {
            case BASE_ATTACK:
                return 15;  // EQUIPMENT_SLOT_MAINHAND
            case OFF_ATTACK:
                return 16;  // EQUIPMENT_SLOT_OFFHAND
            case RANGED_ATTACK:
                return 17;  // EQUIPMENT_SLOT_RANGED
            default:
                return 15;
        }
    }
References BASE_ATTACK, OFF_ATTACK, and RANGED_ATTACK.
Referenced by TEST_F(), TEST_F(), TEST_F(), and TEST_F().
IsProcOnCooldown()
static bool ProcChanceTestHelper::IsProcOnCooldown (AuraStub const * aura, std::chrono::steady_clock::time_point now) inline static
Check if proc is on cooldown.
Parameters
aura The aura stub
now Current time point
Returns
true if proc is blocked by cooldown
    {
        if (!aura)
            return false;
        return aura->IsProcOnCooldown(now);
    }
References AuraStub::IsProcOnCooldown().
Referenced by ProcTestScenario::SimulateProc(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
ShouldBlockDueToConditions()
static bool ProcChanceTestHelper::ShouldBlockDueToConditions (ConditionsConfig const & config) inline static
Simulate conditions check Returns true if proc should be blocked due to conditions.
Parameters
config Conditions configuration
Returns
true if proc should be blocked
    {
        // No conditions configured - allow proc
        if (!config.hasConditions)
            return false;
        // Check if conditions are met
        return !config.conditionsMet;
    }
References ProcChanceTestHelper::ConditionsConfig::conditionsMet, and ProcChanceTestHelper::ConditionsConfig::hasConditions.
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
ShouldBlockDueToDisabledEffects()
static bool ProcChanceTestHelper::ShouldBlockDueToDisabledEffects (uint8 initialMask, uint32 disableEffectsMask) inline static
Check if proc should be blocked due to all effects being disabled.
Parameters
initialMask Initial effect mask
disableEffectsMask Mask of effects to disable
Returns
true if all effects disabled (proc blocked), false otherwise
    {
        return ApplyDisableEffectsMask(initialMask, disableEffectsMask) == 0;
    }
References ApplyDisableEffectsMask().
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
ShouldBlockDueToEquipment()
static bool ProcChanceTestHelper::ShouldBlockDueToEquipment (EquipmentConfig const & config) inline static
Simulate equipment requirement check Returns true if proc should be blocked due to equipment requirements.
Parameters
config Equipment configuration
Returns
true if proc should be blocked
    {
        // Only check for passive player auras with equipment requirements
        if (!config.isPassive || !config.isPlayer || config.equippedItemClass == ITEM_CLASS_ANY)
            return false;
        // SPELL_ATTR3_NO_PROC_EQUIP_REQUIREMENT bypasses check
        if (config.hasNoEquipRequirementAttr)
            return false;
        // Feral form blocks weapon procs
        if (config.equippedItemClass == ITEM_CLASS_WEAPON && config.isInFeralForm)
            return true;
        // No item equipped in the required slot
        if (!config.hasEquippedItem)
            return true;
        // Item is broken
        if (config.itemIsBroken)
            return true;
        // Item doesn't fit spell requirements (wrong subclass, etc.)
        if (!config.itemFitsRequirements)
            return true;
        return false;
    }
References ProcChanceTestHelper::EquipmentConfig::equippedItemClass, ProcChanceTestHelper::EquipmentConfig::hasEquippedItem, ProcChanceTestHelper::EquipmentConfig::hasNoEquipRequirementAttr, ProcChanceTestHelper::EquipmentConfig::isInFeralForm, ProcChanceTestHelper::EquipmentConfig::isPassive, ProcChanceTestHelper::EquipmentConfig::isPlayer, ITEM_CLASS_ANY, ITEM_CLASS_WEAPON, ProcChanceTestHelper::EquipmentConfig::itemFitsRequirements, and ProcChanceTestHelper::EquipmentConfig::itemIsBroken.
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
ShouldBlockTriggeredSpell()
static bool ProcChanceTestHelper::ShouldBlockTriggeredSpell (TriggeredSpellConfig const & config, SpellProcEntry const & procEntry, uint32 eventTypeMask) inline static
Simulate triggered spell filtering Implements the self-loop prevention and triggered spell blocking from SpellAuras.cpp.
Parameters
config Configuration for the triggered spell
procEntry The proc entry being checked
eventTypeMask The event type mask from ProcEventInfo
Returns
true if proc should be blocked (return 0), false if allowed
    {
        // Self-loop prevention: block if triggered by the same aura
        // SpellAuras.cpp:2191-2192
        if (config.triggeredByAuraSpellId != 0 &&
            config.triggeredByAuraSpellId == config.procAuraSpellId)
        {
            return true; // Block: self-loop detected
        }
        // Check if triggered spell filtering applies
        // SpellAuras.cpp:2195-2208
        if (!config.auraHasCanProcFromProcs &&
            !(procEntry.AttributesMask & PROC_ATTR_TRIGGERED_CAN_PROC) &&
            !(eventTypeMask & AUTO_ATTACK_PROC_FLAG_MASK))
        {
            // Filter triggered spells unless they have NOT_A_PROC
            if (config.isTriggered && !config.spellHasNotAProc)
            {
                return true; // Block: triggered spell without exceptions
            }
        }
        return false; // Allow proc
    }
References SpellProcEntry::AttributesMask, ProcChanceTestHelper::TriggeredSpellConfig::auraHasCanProcFromProcs, AUTO_ATTACK_PROC_FLAG_MASK, ProcChanceTestHelper::TriggeredSpellConfig::isTriggered, PROC_ATTR_TRIGGERED_CAN_PROC, ProcChanceTestHelper::TriggeredSpellConfig::procAuraSpellId, ProcChanceTestHelper::TriggeredSpellConfig::spellHasNotAProc, and ProcChanceTestHelper::TriggeredSpellConfig::triggeredByAuraSpellId.
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
SimulateCalcProcChance()
static float ProcChanceTestHelper::SimulateCalcProcChance (SpellProcEntry const & procEntry, uint32 actorLevel = 80, uint32 weaponSpeed = 2500, float chanceModifier = 0.0f, float ppmModifier = 0.0f, bool hasDamageInfo = true, bool hasHealInfo = false) inline static
Simulate CalcProcChance() from SpellAuras.cpp.
Parameters
procEntry The proc configuration
actorLevel Actor's level (for PROC_ATTR_REDUCE_PROC_60)
weaponSpeed Weapon speed (for PPM calculation)
chanceModifier Talent/aura modifier to chance
ppmModifier Talent/aura modifier to PPM
hasDamageInfo Whether a DamageInfo is present (enables PPM)
hasHealInfo Whether a HealInfo is present (also enables PPM)
Returns
Calculated proc chance
    {
        float chance = procEntry.Chance;
        // PPM calculation overrides base chance if PPM > 0 and we have DamageInfo or HealInfo
        if ((hasDamageInfo || hasHealInfo) && procEntry.ProcsPerMinute > 0.0f)
        {
            chance = CalculatePPMChance(weaponSpeed, procEntry.ProcsPerMinute, ppmModifier);
        }
        // Apply chance modifier (SPELLMOD_CHANCE_OF_SUCCESS)
        chance += chanceModifier;
        // Apply level 60+ reduction if attribute is set
        if (procEntry.AttributesMask & PROC_ATTR_REDUCE_PROC_60)
        {
            chance = ApplyLevel60Reduction(chance, actorLevel);
        }
        return chance;
    }
References ApplyLevel60Reduction(), SpellProcEntry::AttributesMask, CalculatePPMChance(), SpellProcEntry::Chance, PROC_ATTR_REDUCE_PROC_60, and SpellProcEntry::ProcsPerMinute.
Referenced by ProcTestScenario::SimulateProc(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_P().
SimulateConsumeProcCharges()
static bool ProcChanceTestHelper::SimulateConsumeProcCharges (AuraStub * aura, SpellProcEntry const & procEntry) inline static
Simulate charge consumption from ConsumeProcCharges()
Parameters
aura The aura stub to modify
procEntry The proc configuration
Returns
true if aura was removed (charges/stacks exhausted)
    {
        if (!aura)
            return false;
        if (procEntry.AttributesMask & PROC_ATTR_USE_STACKS_FOR_CHARGES)
        {
            return aura->ModStackAmount(-1);
        }
        else if (aura->IsUsingCharges())
        {
            aura->DropCharge();
            if (aura->GetCharges() == 0)
            {
                aura->Remove();
                return true;
            }
        }
        return false;
    }
References SpellProcEntry::AttributesMask, AuraStub::DropCharge(), AuraStub::GetCharges(), AuraStub::IsUsingCharges(), AuraStub::ModStackAmount(), PROC_ATTR_USE_STACKS_FOR_CHARGES, and AuraStub::Remove().
Referenced by ProcTestScenario::SimulateProc(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_P().
SpellHasManaCost()
static bool ProcChanceTestHelper::SpellHasManaCost (SpellInfo const * spellInfo) inline static
Check if spell has mana cost (for PROC_ATTR_REQ_MANA_COST)
Parameters
spellInfo The spell info to check
Returns
true if spell has mana cost > 0
    {
        if (!spellInfo)
            return false;
        return spellInfo->ManaCost > 0 || spellInfo->ManaCostPercentage > 0;
    }
References SpellInfo::ManaCost, and SpellInfo::ManaCostPercentage.
Referenced by TEST_F(), and TEST_F().
Member Data Documentation
AUTO_ATTACK_PROC_FLAG_MASK
constexpr uint32 ProcChanceTestHelper::AUTO_ATTACK_PROC_FLAG_MASK static constexpr
Initial value:
=
        PROC_FLAG_DONE_MELEE_AUTO_ATTACK | PROC_FLAG_TAKEN_MELEE_AUTO_ATTACK |
        PROC_FLAG_DONE_RANGED_AUTO_ATTACK | PROC_FLAG_TAKEN_RANGED_AUTO_ATTACK
Auto-attack proc flag mask (hunter auto-shot, wands exception) These triggered spells are allowed to proc without TRIGGERED_CAN_PROC.
Referenced by ShouldBlockTriggeredSpell().
BASE_ATTACK
constexpr uint8 ProcChanceTestHelper::BASE_ATTACK = 0 static constexpr
Attack types for weapon slot mapping.
Referenced by GetWeaponSlotForAttackType(), TEST_F(), and TEST_F().
FORM_SPEED_BEAR
constexpr uint32 ProcChanceTestHelper::FORM_SPEED_BEAR = 2500 static constexpr
Referenced by TEST_F(), and TEST_F().
FORM_SPEED_CAT
constexpr uint32 ProcChanceTestHelper::FORM_SPEED_CAT = 1000 static constexpr
Shapeshift form base attack speeds (from SpellShapeshiftForm.dbc)
Referenced by TEST_F(), TEST_F(), TEST_F(), and TEST_F().
ITEM_CLASS_ANY
constexpr int32 ProcChanceTestHelper::ITEM_CLASS_ANY = -1 static constexpr
Referenced by ShouldBlockDueToEquipment(), and TEST_F().
ITEM_CLASS_ARMOR
constexpr int32 ProcChanceTestHelper::ITEM_CLASS_ARMOR = 4 static constexpr
Referenced by SpellProcEquipmentTest::CreateArmorProcConfig().
ITEM_CLASS_WEAPON
constexpr int32 ProcChanceTestHelper::ITEM_CLASS_WEAPON = 2 static constexpr
Item classes for equipment requirement checking.
Referenced by SpellProcEquipmentTest::CreateWeaponProcConfig(), ShouldBlockDueToEquipment(), TEST_F(), and TEST_F().
OFF_ATTACK
constexpr uint8 ProcChanceTestHelper::OFF_ATTACK = 1 static constexpr
Referenced by GetWeaponSlotForAttackType(), TEST_F(), and TEST_F().
PPM_JUDGEMENT_OF_LIGHT
constexpr float ProcChanceTestHelper::PPM_JUDGEMENT_OF_LIGHT = 15.0f static constexpr
PPM_OMEN_OF_CLARITY
constexpr float ProcChanceTestHelper::PPM_OMEN_OF_CLARITY = 6.0f static constexpr
Common PPM values from spell_proc database.
PPM_WINDFURY_WEAPON
constexpr float ProcChanceTestHelper::PPM_WINDFURY_WEAPON = 2.0f static constexpr
RANGED_ATTACK
constexpr uint8 ProcChanceTestHelper::RANGED_ATTACK = 2 static constexpr
Referenced by GetWeaponSlotForAttackType(), TEST_F(), and TEST_F().
WEAPON_SPEED_FAST_DAGGER
constexpr uint32 ProcChanceTestHelper::WEAPON_SPEED_FAST_DAGGER = 1400 static constexpr
Get common weapon speeds for testing.
WEAPON_SPEED_NORMAL_SWORD
constexpr uint32 ProcChanceTestHelper::WEAPON_SPEED_NORMAL_SWORD = 2500 static constexpr
WEAPON_SPEED_SLOW_2H
constexpr uint32 ProcChanceTestHelper::WEAPON_SPEED_SLOW_2H = 3300 static constexpr
WEAPON_SPEED_STAFF
constexpr uint32 ProcChanceTestHelper::WEAPON_SPEED_STAFF = 3600 static constexpr
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
WEAPON_SPEED_VERY_SLOW
constexpr uint32 ProcChanceTestHelper::WEAPON_SPEED_VERY_SLOW = 3800 static constexpr
The documentation for this class was generated from the following file:
azerothcore-wotlk/src/test/mocks/ProcChanceTestHelper.h