AzerothCore Doxygen
AuraStub Class Reference
Lightweight stub for Aura proc-related functionality.
#include "AuraStub.h"
Public Types
using TimePoint = std::chrono::steady_clock::time_point
Public Member Functions
AuraStub (uint32_t id=0, uint32_t spellFamilyName=0)
virtual ~AuraStub ()=default
uint32_t GetId () const
uint32_t GetSpellFamilyName () const
void SetId (uint32_t id)
void SetSpellFamilyName (uint32_t familyName)
AuraEffectStub * GetEffect (uint8_t effIndex) const
bool HasEffect (uint8_t effIndex) const
uint8_t GetEffectMask () const
uint8_t GetCharges () const
bool IsUsingCharges () const
void SetCharges (uint8_t charges)
void SetUsingCharges (bool usingCharges)
virtual bool DropCharge ()
bool WasChargeDropped () const
void ResetChargeDropped ()
int32_t GetDuration () const
int32_t GetMaxDuration () const
bool IsPermanent () const
void SetDuration (int32_t duration)
void SetMaxDuration (int32_t maxDuration)
bool IsProcOnCooldown (TimePoint now) const
void AddProcCooldown (TimePoint cooldownEnd)
void ResetProcCooldown ()
uint8_t GetStackAmount () const
void SetStackAmount (uint8_t amount)
virtual bool ModStackAmount (int32_t amount, bool=true)
Modify stack amount (for PROC_ATTR_USE_STACKS_FOR_CHARGES) Mimics Aura::ModStackAmount() - removes aura if stacks reach 0.
bool IsPassive () const
bool IsRemoved () const
void SetPassive (bool isPassive)
void SetRemoved (bool isRemoved)
virtual void Remove ()
Mark aura as removed (for charge exhaustion) Mimics Aura::Remove()
AuraApplicationStub & GetOrCreateApplication ()
AuraApplicationStub * GetApplication () const
Private Attributes
uint32_t _id = 0
uint32_t _spellFamilyName = 0
std::unique_ptr< AuraEffectStub > _effects [3]
std::unique_ptr< AuraApplicationStub > _application
uint8_t _charges = 0
bool _isUsingCharges = false
bool _chargeDropped = false
int32_t _duration = -1
int32_t _maxDuration = -1
TimePoint _procCooldown = TimePoint::min()
uint8_t _stackAmount = 1
bool _isPassive = false
bool _isRemoved = false
Detailed Description
Lightweight stub for Aura proc-related functionality.
Member Typedef Documentation
TimePoint
using AuraStub::TimePoint = std::chrono::steady_clock::time_point
Constructor & Destructor Documentation
AuraStub()
AuraStub::AuraStub (uint32_t id = 0, uint32_t spellFamilyName = 0) inline
        : _id(id), _spellFamilyName(spellFamilyName)
    {
        // Create 3 effect slots by default
        for (int i = 0; i < 3; ++i)
        {
            _effects[i] = std::make_unique<AuraEffectStub>(static_cast<uint8_t>(i));
        }
    }
References _effects.
~AuraStub()
virtual AuraStub::~AuraStub () virtual default
Member Function Documentation
AddProcCooldown()
void AuraStub::AddProcCooldown (TimePoint cooldownEnd) inline
    {
        _procCooldown = cooldownEnd;
    }
References _procCooldown.
Referenced by ProcChanceTestHelper::ApplyProcCooldown().
DropCharge()
virtual bool AuraStub::DropCharge () inline virtual
    {
        if (_charges > 0)
        {
            --_charges;
            _chargeDropped = true;
            return true;
        }
        return false;
    }
References _chargeDropped, and _charges.
Referenced by ProcChanceTestHelper::SimulateConsumeProcCharges().
GetApplication()
AuraApplicationStub * AuraStub::GetApplication () const inline
    {
        return _application.get();
    }
References _application.
GetCharges()
uint8_t AuraStub::GetCharges () const inline
{ return _charges; }
References _charges.
Referenced by ProcChanceTestHelper::SimulateConsumeProcCharges().
GetDuration()
int32_t AuraStub::GetDuration () const inline
{ return _duration; }
References _duration.
GetEffect()
AuraEffectStub * AuraStub::GetEffect (uint8_t effIndex) const inline
    {
        return (effIndex < 3) ? _effects[effIndex].get() : nullptr;
    }
References _effects.
GetEffectMask()
uint8_t AuraStub::GetEffectMask () const inline
    {
        uint8_t mask = 0;
        for (uint8_t i = 0; i < 3; ++i)
        {
            if (_effects[i])
                mask |= (1 << i);
        }
        return mask;
    }
References _effects.
GetId()
uint32_t AuraStub::GetId () const inline
{ return _id; }
References _id.
GetMaxDuration()
int32_t AuraStub::GetMaxDuration () const inline
{ return _maxDuration; }
References _maxDuration.
GetOrCreateApplication()
AuraApplicationStub & AuraStub::GetOrCreateApplication () inline
    {
        if (!_application)
            _application = std::make_unique<AuraApplicationStub>();
        return *_application;
    }
References _application.
GetSpellFamilyName()
uint32_t AuraStub::GetSpellFamilyName () const inline
{ return _spellFamilyName; }
References _spellFamilyName.
GetStackAmount()
uint8_t AuraStub::GetStackAmount () const inline
{ return _stackAmount; }
References _stackAmount.
HasEffect()
bool AuraStub::HasEffect (uint8_t effIndex) const inline
    {
        return effIndex < 3 && _effects[effIndex] != nullptr;
    }
References _effects.
IsPassive()
bool AuraStub::IsPassive () const inline
{ return _isPassive; }
References _isPassive.
IsPermanent()
bool AuraStub::IsPermanent () const inline
{ return _maxDuration == -1; }
References _maxDuration.
IsProcOnCooldown()
bool AuraStub::IsProcOnCooldown (TimePoint now) const inline
    {
        return now < _procCooldown;
    }
References _procCooldown.
Referenced by ProcChanceTestHelper::IsProcOnCooldown().
IsRemoved()
bool AuraStub::IsRemoved () const inline
{ return _isRemoved; }
References _isRemoved.
IsUsingCharges()
bool AuraStub::IsUsingCharges () const inline
{ return _isUsingCharges; }
References _isUsingCharges.
Referenced by ProcChanceTestHelper::SimulateConsumeProcCharges().
ModStackAmount()
virtual bool AuraStub::ModStackAmount (int32_t amount, bool = true) inline virtual
Modify stack amount (for PROC_ATTR_USE_STACKS_FOR_CHARGES) Mimics Aura::ModStackAmount() - removes aura if stacks reach 0.
    {
        int32_t newAmount = static_cast<int32_t>(_stackAmount) + amount;
        if (newAmount <= 0)
        {
            _stackAmount = 0;
            Remove();
            return true; // Aura removed
        }
        _stackAmount = static_cast<uint8_t>(newAmount);
        return false;
    }
References _stackAmount, and Remove().
Referenced by ProcChanceTestHelper::SimulateConsumeProcCharges().
Remove()
virtual void AuraStub::Remove () inline virtual
Mark aura as removed (for charge exhaustion) Mimics Aura::Remove()
    {
        _isRemoved = true;
    }
References _isRemoved.
Referenced by ModStackAmount(), and ProcChanceTestHelper::SimulateConsumeProcCharges().
ResetChargeDropped()
void AuraStub::ResetChargeDropped () inline
{ _chargeDropped = false; }
References _chargeDropped.
ResetProcCooldown()
void AuraStub::ResetProcCooldown () inline
    {
        _procCooldown = TimePoint::min();
    }
References _procCooldown.
SetCharges()
void AuraStub::SetCharges (uint8_t charges) inline
{ _charges = charges; }
References _charges.
Referenced by ProcTestContext::WithAuraCharges().
SetDuration()
void AuraStub::SetDuration (int32_t duration) inline
{ _duration = duration; }
References _duration.
SetId()
void AuraStub::SetId (uint32_t id) inline
{ _id = id; }
References _id.
Referenced by ProcTestContext::WithAuraId().
SetMaxDuration()
void AuraStub::SetMaxDuration (int32_t maxDuration) inline
{ _maxDuration = maxDuration; }
References _maxDuration.
SetPassive()
void AuraStub::SetPassive (bool isPassive) inline
{ _isPassive = isPassive; }
References _isPassive.
SetRemoved()
void AuraStub::SetRemoved (bool isRemoved) inline
{ _isRemoved = isRemoved; }
References _isRemoved.
SetSpellFamilyName()
void AuraStub::SetSpellFamilyName (uint32_t familyName) inline
{ _spellFamilyName = familyName; }
References _spellFamilyName.
Referenced by ProcTestContext::WithAuraSpellFamily().
SetStackAmount()
void AuraStub::SetStackAmount (uint8_t amount) inline
{ _stackAmount = amount; }
References _stackAmount.
SetUsingCharges()
void AuraStub::SetUsingCharges (bool usingCharges) inline
{ _isUsingCharges = usingCharges; }
References _isUsingCharges.
Referenced by ProcTestContext::WithAuraCharges().
WasChargeDropped()
bool AuraStub::WasChargeDropped () const inline
{ return _chargeDropped; }
References _chargeDropped.
Member Data Documentation
_application
std::unique_ptr<AuraApplicationStub> AuraStub::_application private
Referenced by GetApplication(), and GetOrCreateApplication().
_chargeDropped
bool AuraStub::_chargeDropped = false private
Referenced by DropCharge(), ResetChargeDropped(), and WasChargeDropped().
_charges
uint8_t AuraStub::_charges = 0 private
Referenced by DropCharge(), GetCharges(), and SetCharges().
_duration
int32_t AuraStub::_duration = -1 private
Referenced by GetDuration(), and SetDuration().
_effects
std::unique_ptr<AuraEffectStub> AuraStub::_effects[3] private
Referenced by AuraStub(), GetEffect(), GetEffectMask(), and HasEffect().
_id
uint32_t AuraStub::_id = 0 private
Referenced by GetId(), and SetId().
_isPassive
bool AuraStub::_isPassive = false private
Referenced by IsPassive(), and SetPassive().
_isRemoved
bool AuraStub::_isRemoved = false private
Referenced by IsRemoved(), Remove(), and SetRemoved().
_isUsingCharges
bool AuraStub::_isUsingCharges = false private
Referenced by IsUsingCharges(), and SetUsingCharges().
_maxDuration
int32_t AuraStub::_maxDuration = -1 private
Referenced by GetMaxDuration(), IsPermanent(), and SetMaxDuration().
_procCooldown
TimePoint AuraStub::_procCooldown = TimePoint::min() private
Referenced by AddProcCooldown(), IsProcOnCooldown(), and ResetProcCooldown().
_spellFamilyName
uint32_t AuraStub::_spellFamilyName = 0 private
Referenced by GetSpellFamilyName(), and SetSpellFamilyName().
_stackAmount
uint8_t AuraStub::_stackAmount = 1 private
Referenced by GetStackAmount(), ModStackAmount(), and SetStackAmount().
The documentation for this class was generated from the following file:
azerothcore-wotlk/src/test/mocks/AuraStub.h