AzerothCore Doxygen
rbac_commandscript Class Reference
Public Member Functions
rbac_commandscript ()
ChatCommandTable GetCommands () const override
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
uint16 GetTotalAvailableHooks ()
Static Public Member Functions
static RBACCommandData GetRBACData (uint32 accountId, std::string const &accountName)
static bool HandleRBACPermGrantCommand (ChatHandler *handler, AccountIdentifier account, uint32 permId, Optional< int32 > realmId)
static bool HandleRBACPermDenyCommand (ChatHandler *handler, AccountIdentifier account, uint32 permId, Optional< int32 > realmId)
static bool HandleRBACPermRevokeCommand (ChatHandler *handler, AccountIdentifier account, uint32 permId, Optional< int32 > realmId)
static char const * GetSecurityLevelName (uint8 secLevel)
static bool HandleRBACPermListCommand (ChatHandler *handler, AccountIdentifier account)
static bool HandleRBACListPermissionsCommand (ChatHandler *handler, Optional< uint32 > permId)
Additional Inherited Members
Protected Member Functions inherited from CommandScript
CommandScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name, uint16 totalAvailableHooks=0)
virtual ~ScriptObject ()=default
Detailed Description
Constructor & Destructor Documentation
rbac_commandscript()
rbac_commandscript::rbac_commandscript () inline
: CommandScript("rbac_commandscript") { }
Member Function Documentation
GetCommands()
ChatCommandTable rbac_commandscript::GetCommands () const inline override virtual
Implements CommandScript.
    {
        static ChatCommandTable rbacAccountCommandTable =
        {
            { "list",   HandleRBACPermListCommand,   LANG_RBAC_HELP_ACC_LIST,   rbac::RBAC_PERM_COMMAND_RBAC_ACC_PERM_LIST,   Console::Yes },
            { "grant",  HandleRBACPermGrantCommand,  LANG_RBAC_HELP_ACC_GRANT,  rbac::RBAC_PERM_COMMAND_RBAC_ACC_PERM_GRANT,  Console::Yes },
            { "deny",   HandleRBACPermDenyCommand,   LANG_RBAC_HELP_ACC_DENY,   rbac::RBAC_PERM_COMMAND_RBAC_ACC_PERM_DENY,   Console::Yes },
            { "revoke", HandleRBACPermRevokeCommand, LANG_RBAC_HELP_ACC_REVOKE, rbac::RBAC_PERM_COMMAND_RBAC_ACC_PERM_REVOKE, Console::Yes },
        };
        static ChatCommandTable rbacCommandTable =
        {
            { "account", rbacAccountCommandTable },
            { "list",    HandleRBACListPermissionsCommand, rbac::RBAC_PERM_COMMAND_RBAC_LIST, Console::Yes },
        };
        static ChatCommandTable commandTable =
        {
            { "rbac", rbacCommandTable },
        };
        return commandTable;
    }
References HandleRBACListPermissionsCommand(), HandleRBACPermDenyCommand(), HandleRBACPermGrantCommand(), HandleRBACPermListCommand(), HandleRBACPermRevokeCommand(), LANG_RBAC_HELP_ACC_DENY, LANG_RBAC_HELP_ACC_GRANT, LANG_RBAC_HELP_ACC_LIST, LANG_RBAC_HELP_ACC_REVOKE, rbac::RBAC_PERM_COMMAND_RBAC_ACC_PERM_DENY, rbac::RBAC_PERM_COMMAND_RBAC_ACC_PERM_GRANT, rbac::RBAC_PERM_COMMAND_RBAC_ACC_PERM_LIST, rbac::RBAC_PERM_COMMAND_RBAC_ACC_PERM_REVOKE, and rbac::RBAC_PERM_COMMAND_RBAC_LIST.
GetRBACData()
static RBACCommandData rbac_commandscript::GetRBACData (uint32 accountId, std::string const & accountName) inline static
    {
        // session->GetRBACData() can be null after World::ReloadRBAC()
        if (WorldSession* session = sWorldSessionMgr->FindSession(accountId))
            if (rbac::RBACData* sessionRbac = session->GetRBACData())
                return { sessionRbac, false };
        rbac::RBACData* rbac = new rbac::RBACData(accountId, accountName, realm.Id.Realm, AccountMgr::GetSecurity(accountId, realm.Id.Realm));
        rbac->LoadFromDB();
        return { rbac, true };
    }
References AccountMgr::GetSecurity(), Realm::Id, realm, RealmHandle::Realm, and sWorldSessionMgr.
Referenced by HandleRBACPermDenyCommand(), HandleRBACPermGrantCommand(), HandleRBACPermListCommand(), and HandleRBACPermRevokeCommand().
GetSecurityLevelName()
static char const * rbac_commandscript::GetSecurityLevelName (uint8 secLevel) inline static
    {
        switch (secLevel)
        {
            case SEC_PLAYER:        return "SEC_PLAYER";
            case SEC_MODERATOR:     return "SEC_MODERATOR";
            case SEC_GAMEMASTER:    return "SEC_GAMEMASTER";
            case SEC_ADMINISTRATOR: return "SEC_ADMINISTRATOR";
            case SEC_CONSOLE:       return "SEC_CONSOLE";
            default:                return "Unknown";
        }
    }
References SEC_ADMINISTRATOR, SEC_CONSOLE, SEC_GAMEMASTER, SEC_MODERATOR, and SEC_PLAYER.
Referenced by HandleRBACPermListCommand().
HandleRBACListPermissionsCommand()
static bool rbac_commandscript::HandleRBACListPermissionsCommand (ChatHandler * handler, Optional< uint32 > permId) inline static
    {
        if (!permId)
        {
            rbac::RBACPermissionsContainer const& permissions = sAccountMgr->GetRBACPermissionList();
            handler->SendSysMessage(handler->GetAcoreString(LANG_RBAC_LIST_PERMISSIONS_HEADER));
            for (auto const& [_, permission] : permissions)
            {
                handler->PSendSysMessage(LANG_RBAC_LIST_ELEMENT, permission->GetId(), permission->GetName().c_str());
            }
        }
        else
        {
            rbac::RBACPermission const* permission = sAccountMgr->GetRBACPermission(*permId);
            if (!permission)
            {
                handler->PSendSysMessage(LANG_RBAC_WRONG_PARAMETER_ID, *permId);
                handler->SetSentErrorMessage(true);
                return false;
            }
            handler->SendSysMessage(handler->GetAcoreString(LANG_RBAC_LIST_PERMISSIONS_HEADER));
            handler->PSendSysMessage(LANG_RBAC_LIST_ELEMENT, permission->GetId(), permission->GetName().c_str());
            handler->SendSysMessage(handler->GetAcoreString(LANG_RBAC_LIST_PERMS_LINKED_HEADER));
            for (uint32 linkedPerm : permission->GetLinkedPermissions())
                if (rbac::RBACPermission const* rbacPermission = sAccountMgr->GetRBACPermission(linkedPerm))
                    handler->PSendSysMessage(LANG_RBAC_LIST_ELEMENT, rbacPermission->GetId(), rbacPermission->GetName().c_str());
        }
        return true;
    }
References ChatHandler::GetAcoreString(), rbac::RBACPermission::GetId(), rbac::RBACPermission::GetLinkedPermissions(), rbac::RBACPermission::GetName(), LANG_RBAC_LIST_ELEMENT, LANG_RBAC_LIST_PERMISSIONS_HEADER, LANG_RBAC_LIST_PERMS_LINKED_HEADER, LANG_RBAC_WRONG_PARAMETER_ID, ChatHandler::PSendSysMessage(), sAccountMgr, ChatHandler::SendSysMessage(), and ChatHandler::SetSentErrorMessage().
Referenced by GetCommands().
HandleRBACPermDenyCommand()
static bool rbac_commandscript::HandleRBACPermDenyCommand (ChatHandler * handler, AccountIdentifier account, uint32 permId, Optional< int32 > realmId) inline static
    {
        if (handler->HasLowerSecurityAccount(nullptr, account.GetID(), true))
            return false;
        if (!realmId)
            realmId = -1;
        RBACCommandData data = GetRBACData(account.GetID(), account.GetName());
        rbac::RBACCommandResult result = data.rbac->DenyPermission(permId, *realmId);
        rbac::RBACPermission const* permission = sAccountMgr->GetRBACPermission(permId);
        switch (result)
        {
            case rbac::RBAC_CANT_ADD_ALREADY_ADDED:
                handler->PSendSysMessage(LANG_RBAC_PERM_DENIED_IN_LIST, permId, permission->GetName().c_str(),
                                         *realmId, account.GetID(), account.GetName().c_str());
                break;
            case rbac::RBAC_IN_GRANTED_LIST:
                handler->PSendSysMessage(LANG_RBAC_PERM_DENIED_IN_GRANTED_LIST, permId, permission->GetName().c_str(),
                                         *realmId, account.GetID(), account.GetName().c_str());
                break;
            case rbac::RBAC_OK:
                handler->PSendSysMessage(LANG_RBAC_PERM_DENIED, permId, permission->GetName().c_str(),
                                         *realmId, account.GetID(), account.GetName().c_str());
                break;
            case rbac::RBAC_ID_DOES_NOT_EXISTS:
                handler->PSendSysMessage(LANG_RBAC_WRONG_PARAMETER_ID, permId);
                break;
            default:
                break;
        }
        return true;
    }
References rbac::RBACData::DenyPermission(), Acore::ChatCommands::AccountIdentifier::GetID(), rbac::RBACPermission::GetName(), Acore::ChatCommands::AccountIdentifier::GetName(), GetRBACData(), ChatHandler::HasLowerSecurityAccount(), LANG_RBAC_PERM_DENIED, LANG_RBAC_PERM_DENIED_IN_GRANTED_LIST, LANG_RBAC_PERM_DENIED_IN_LIST, LANG_RBAC_WRONG_PARAMETER_ID, ChatHandler::PSendSysMessage(), RBACCommandData::rbac, rbac::RBAC_CANT_ADD_ALREADY_ADDED, rbac::RBAC_ID_DOES_NOT_EXISTS, rbac::RBAC_IN_GRANTED_LIST, rbac::RBAC_OK, and sAccountMgr.
Referenced by GetCommands().
HandleRBACPermGrantCommand()
static bool rbac_commandscript::HandleRBACPermGrantCommand (ChatHandler * handler, AccountIdentifier account, uint32 permId, Optional< int32 > realmId) inline static
    {
        if (handler->HasLowerSecurityAccount(nullptr, account.GetID(), true))
            return false;
        if (!realmId)
            realmId = -1;
        RBACCommandData data = GetRBACData(account.GetID(), account.GetName());
        rbac::RBACCommandResult result = data.rbac->GrantPermission(permId, *realmId);
        rbac::RBACPermission const* permission = sAccountMgr->GetRBACPermission(permId);
        switch (result)
        {
            case rbac::RBAC_CANT_ADD_ALREADY_ADDED:
                handler->PSendSysMessage(LANG_RBAC_PERM_GRANTED_IN_LIST, permId, permission->GetName().c_str(),
                                         *realmId, account.GetID(), account.GetName().c_str());
                break;
            case rbac::RBAC_IN_DENIED_LIST:
                handler->PSendSysMessage(LANG_RBAC_PERM_GRANTED_IN_DENIED_LIST, permId, permission->GetName().c_str(),
                                         *realmId, account.GetID(), account.GetName().c_str());
                break;
            case rbac::RBAC_OK:
                handler->PSendSysMessage(LANG_RBAC_PERM_GRANTED, permId, permission->GetName().c_str(),
                                         *realmId, account.GetID(), account.GetName().c_str());
                break;
            case rbac::RBAC_ID_DOES_NOT_EXISTS:
                handler->PSendSysMessage(LANG_RBAC_WRONG_PARAMETER_ID, permId);
                break;
            default:
                break;
        }
        return true;
    }
References Acore::ChatCommands::AccountIdentifier::GetID(), rbac::RBACPermission::GetName(), Acore::ChatCommands::AccountIdentifier::GetName(), GetRBACData(), rbac::RBACData::GrantPermission(), ChatHandler::HasLowerSecurityAccount(), LANG_RBAC_PERM_GRANTED, LANG_RBAC_PERM_GRANTED_IN_DENIED_LIST, LANG_RBAC_PERM_GRANTED_IN_LIST, LANG_RBAC_WRONG_PARAMETER_ID, ChatHandler::PSendSysMessage(), RBACCommandData::rbac, rbac::RBAC_CANT_ADD_ALREADY_ADDED, rbac::RBAC_ID_DOES_NOT_EXISTS, rbac::RBAC_IN_DENIED_LIST, rbac::RBAC_OK, and sAccountMgr.
Referenced by GetCommands().
HandleRBACPermListCommand()
static bool rbac_commandscript::HandleRBACPermListCommand (ChatHandler * handler, AccountIdentifier account) inline static
    {
        RBACCommandData data = GetRBACData(account.GetID(), account.GetName());
        handler->PSendSysMessage(LANG_RBAC_LIST_HEADER_GRANTED, data.rbac->GetId(), data.rbac->GetName().c_str());
        rbac::RBACPermissionContainer const& granted = data.rbac->GetGrantedPermissions();
        if (granted.empty())
            handler->SendSysMessage(handler->GetAcoreString(LANG_RBAC_LIST_EMPTY));
        else
        {
            for (uint32 grantedId : granted)
            {
                rbac::RBACPermission const* permission = sAccountMgr->GetRBACPermission(grantedId);
                handler->PSendSysMessage(LANG_RBAC_LIST_ELEMENT, permission->GetId(), permission->GetName().c_str());
            }
        }
        handler->PSendSysMessage(LANG_RBAC_LIST_HEADER_DENIED, data.rbac->GetId(), data.rbac->GetName().c_str());
        rbac::RBACPermissionContainer const& denied = data.rbac->GetDeniedPermissions();
        if (denied.empty())
            handler->SendSysMessage(handler->GetAcoreString(LANG_RBAC_LIST_EMPTY));
        else
        {
            for (uint32 deniedId : denied)
            {
                rbac::RBACPermission const* permission = sAccountMgr->GetRBACPermission(deniedId);
                handler->PSendSysMessage(LANG_RBAC_LIST_ELEMENT, permission->GetId(), permission->GetName().c_str());
            }
        }
        handler->PSendSysMessage(LANG_RBAC_LIST_HEADER_BY_SEC_LEVEL, data.rbac->GetId(), data.rbac->GetName().c_str(),
                                 data.rbac->GetSecurityLevel(), GetSecurityLevelName(data.rbac->GetSecurityLevel()));
        rbac::RBACPermissionContainer const& defaultPermissions = sAccountMgr->GetRBACDefaultPermissions(data.rbac->GetSecurityLevel());
        if (defaultPermissions.empty())
            handler->SendSysMessage(handler->GetAcoreString(LANG_RBAC_LIST_EMPTY));
        else
        {
            for (uint32 defaultPermission : defaultPermissions)
            {
                rbac::RBACPermission const* permission = sAccountMgr->GetRBACPermission(defaultPermission);
                handler->PSendSysMessage(LANG_RBAC_LIST_ELEMENT, permission->GetId(), permission->GetName().c_str());
            }
        }
        return true;
    }
References ChatHandler::GetAcoreString(), rbac::RBACData::GetDeniedPermissions(), rbac::RBACData::GetGrantedPermissions(), rbac::RBACPermission::GetId(), rbac::RBACData::GetId(), Acore::ChatCommands::AccountIdentifier::GetID(), rbac::RBACPermission::GetName(), rbac::RBACData::GetName(), Acore::ChatCommands::AccountIdentifier::GetName(), GetRBACData(), rbac::RBACData::GetSecurityLevel(), GetSecurityLevelName(), LANG_RBAC_LIST_ELEMENT, LANG_RBAC_LIST_EMPTY, LANG_RBAC_LIST_HEADER_BY_SEC_LEVEL, LANG_RBAC_LIST_HEADER_DENIED, LANG_RBAC_LIST_HEADER_GRANTED, ChatHandler::PSendSysMessage(), RBACCommandData::rbac, sAccountMgr, and ChatHandler::SendSysMessage().
Referenced by GetCommands().
HandleRBACPermRevokeCommand()
static bool rbac_commandscript::HandleRBACPermRevokeCommand (ChatHandler * handler, AccountIdentifier account, uint32 permId, Optional< int32 > realmId) inline static
    {
        if (handler->HasLowerSecurityAccount(nullptr, account.GetID(), true))
            return false;
        if (!realmId)
            realmId = -1;
        RBACCommandData data = GetRBACData(account.GetID(), account.GetName());
        rbac::RBACCommandResult result = data.rbac->RevokePermission(permId, *realmId);
        rbac::RBACPermission const* permission = sAccountMgr->GetRBACPermission(permId);
        switch (result)
        {
            case rbac::RBAC_CANT_REVOKE_NOT_IN_LIST:
                handler->PSendSysMessage(LANG_RBAC_PERM_REVOKED_NOT_IN_LIST, permId, permission->GetName().c_str(),
                                         *realmId, account.GetID(), account.GetName().c_str());
                break;
            case rbac::RBAC_OK:
                handler->PSendSysMessage(LANG_RBAC_PERM_REVOKED, permId, permission->GetName().c_str(),
                                         *realmId, account.GetID(), account.GetName().c_str());
                break;
            case rbac::RBAC_ID_DOES_NOT_EXISTS:
                handler->PSendSysMessage(LANG_RBAC_WRONG_PARAMETER_ID, permId);
                break;
            default:
                break;
        }
        return true;
    }
References Acore::ChatCommands::AccountIdentifier::GetID(), rbac::RBACPermission::GetName(), Acore::ChatCommands::AccountIdentifier::GetName(), GetRBACData(), ChatHandler::HasLowerSecurityAccount(), LANG_RBAC_PERM_REVOKED, LANG_RBAC_PERM_REVOKED_NOT_IN_LIST, LANG_RBAC_WRONG_PARAMETER_ID, ChatHandler::PSendSysMessage(), RBACCommandData::rbac, rbac::RBAC_CANT_REVOKE_NOT_IN_LIST, rbac::RBAC_ID_DOES_NOT_EXISTS, rbac::RBAC_OK, rbac::RBACData::RevokePermission(), and sAccountMgr.
Referenced by GetCommands().
The documentation for this class was generated from the following file:
azerothcore-wotlk/src/server/scripts/Commands/cs_rbac.cpp