AzerothCore Doxygen
LuaEngine.cpp File Reference
#include "Hooks.h"
#include "LuaEngine.h"
#include "BindingMap.h"
#include "Chat.h"
#include "ElunaEventMgr.h"
#include "ElunaIncludes.h"
#include "ElunaTemplate.h"
#include "ElunaUtility.h"
#include "ElunaCreatureAI.h"
#include "ElunaInstanceAI.h"
#include <boost/filesystem.hpp>
#include "lua.h"
#include "lualib.h"
#include "lauxlib.h"
Macros
#define USING_BOOST
Functions
void RegisterFunctions (Eluna *E)
static bool ScriptPathComparator (const LuaScript &first, const LuaScript &second)
static int CheckIntegerRange (lua_State *luastate, int narg, int min, int max)
static unsigned int CheckUnsignedRange (lua_State *luastate, int narg, unsigned int max)
template<>
std::string Eluna::CHECKVAL< std::string > (lua_State *luastate, int narg)
template<typename K >
static int cancelBinding (lua_State *L)
template<typename K >
static void createCancelCallback (lua_State *L, uint64 bindingID, BindingMap< K > *bindings)
Macro Definition Documentation
USING_BOOST
#define USING_BOOST
Function Documentation
cancelBinding()
template<typename K > static int cancelBinding (lua_State * L) static
{
    uint64 bindingID = Eluna::CHECKVAL<uint64>(L, lua_upvalueindex(1));
    BindingMap<K>* bindings = (BindingMap<K>*)lua_touserdata(L, lua_upvalueindex(2));
    ASSERT(bindings != NULL);
    bindings->Remove(bindingID);
    return 0;
}
References ASSERT, lua_touserdata(), lua_upvalueindex, and BindingMap< K >::Remove().
CheckIntegerRange()
static int CheckIntegerRange (lua_State * luastate, int narg, int min, int max) static
{
    double value = luaL_checknumber(luastate, narg);
    char error_buffer[64];
    if (value > max)
    {
        snprintf(error_buffer, 64, "value must be less than or equal to %i", max);
        return luaL_argerror(luastate, narg, error_buffer);
    }
    if (value < min)
    {
        snprintf(error_buffer, 64, "value must be greater than or equal to %i", min);
        return luaL_argerror(luastate, narg, error_buffer);
    }
    return static_cast<int>(value);
}
References luaL_argerror(), and luaL_checknumber().
Referenced by Eluna::CHECKVAL().
CheckUnsignedRange()
static unsigned int CheckUnsignedRange (lua_State * luastate, int narg, unsigned int max) static
{
    double value = luaL_checknumber(luastate, narg);
    if (value < 0)
        return luaL_argerror(luastate, narg, "value must be greater than or equal to 0");
    if (value > max)
    {
        char error_buffer[64];
        snprintf(error_buffer, 64, "value must be less than or equal to %u", max);
        return luaL_argerror(luastate, narg, error_buffer);
    }
    return static_cast<unsigned int>(value);
}
References luaL_argerror(), and luaL_checknumber().
Referenced by Eluna::CHECKVAL().
createCancelCallback()
template<typename K > static void createCancelCallback (lua_State * L, uint64 bindingID, BindingMap< K > * bindings) static
{
    Eluna::Push(L, bindingID);
    lua_pushlightuserdata(L, bindings);
    // Stack: bindingID, bindings
    lua_pushcclosure(L, &cancelBinding<K>, 2);
    // Stack: cancel_callback
}
References lua_pushcclosure(), lua_pushlightuserdata(), and Eluna::Push().
Referenced by Eluna::Register().
Eluna::CHECKVAL< std::string >()
template<> std::string Eluna::CHECKVAL< std::string > (lua_State * luastate, int narg)
{
    return luaL_checkstring(luastate, narg);
}
References luaL_checkstring.
RegisterFunctions()
void RegisterFunctions (Eluna * E) extern
{
    ElunaGlobal::SetMethods(E, GlobalMethods);
    ElunaTemplate<Object>::Register(E, "Object");
    ElunaTemplate<Object>::SetMethods(E, ObjectMethods);
    ElunaTemplate<WorldObject>::Register(E, "WorldObject");
    ElunaTemplate<WorldObject>::SetMethods(E, ObjectMethods);
    ElunaTemplate<WorldObject>::SetMethods(E, WorldObjectMethods);
    ElunaTemplate<Unit>::Register(E, "Unit");
    ElunaTemplate<Unit>::SetMethods(E, ObjectMethods);
    ElunaTemplate<Unit>::SetMethods(E, WorldObjectMethods);
    ElunaTemplate<Unit>::SetMethods(E, UnitMethods);
    ElunaTemplate<Player>::Register(E, "Player");
    ElunaTemplate<Player>::SetMethods(E, ObjectMethods);
    ElunaTemplate<Player>::SetMethods(E, WorldObjectMethods);
    ElunaTemplate<Player>::SetMethods(E, UnitMethods);
    ElunaTemplate<Player>::SetMethods(E, PlayerMethods);
    ElunaTemplate<Creature>::Register(E, "Creature");
    ElunaTemplate<Creature>::SetMethods(E, ObjectMethods);
    ElunaTemplate<Creature>::SetMethods(E, WorldObjectMethods);
    ElunaTemplate<Creature>::SetMethods(E, UnitMethods);
    ElunaTemplate<Creature>::SetMethods(E, CreatureMethods);
    ElunaTemplate<GameObject>::Register(E, "GameObject");
    ElunaTemplate<GameObject>::SetMethods(E, ObjectMethods);
    ElunaTemplate<GameObject>::SetMethods(E, WorldObjectMethods);
    ElunaTemplate<GameObject>::SetMethods(E, GameObjectMethods);
    ElunaTemplate<Corpse>::Register(E, "Corpse");
    ElunaTemplate<Corpse>::SetMethods(E, ObjectMethods);
    ElunaTemplate<Corpse>::SetMethods(E, WorldObjectMethods);
    ElunaTemplate<Corpse>::SetMethods(E, CorpseMethods);
    ElunaTemplate<Item>::Register(E, "Item");
    ElunaTemplate<Item>::SetMethods(E, ObjectMethods);
    ElunaTemplate<Item>::SetMethods(E, ItemMethods);
    ElunaTemplate<ItemTemplate>::Register(E, "ItemTemplate");
    ElunaTemplate<ItemTemplate>::SetMethods(E, ItemTemplateMethods);
#ifndef CLASSIC
#ifndef TBC
    ElunaTemplate<Vehicle>::Register(E, "Vehicle");
    ElunaTemplate<Vehicle>::SetMethods(E, VehicleMethods);
#endif
#endif
    ElunaTemplate<Group>::Register(E, "Group");
    ElunaTemplate<Group>::SetMethods(E, GroupMethods);
    ElunaTemplate<Guild>::Register(E, "Guild");
    ElunaTemplate<Guild>::SetMethods(E, GuildMethods);
    ElunaTemplate<Aura>::Register(E, "Aura");
    ElunaTemplate<Aura>::SetMethods(E, AuraMethods);
    ElunaTemplate<Spell>::Register(E, "Spell");
    ElunaTemplate<Spell>::SetMethods(E, SpellMethods);
    ElunaTemplate<Quest>::Register(E, "Quest");
    ElunaTemplate<Quest>::SetMethods(E, QuestMethods);
    ElunaTemplate<Map>::Register(E, "Map");
    ElunaTemplate<Map>::SetMethods(E, MapMethods);
    ElunaTemplate<AuctionHouseEntry>::Register(E, "AuctionHouseEntry");
    ElunaTemplate<AuctionHouseEntry>::SetMethods(E, AuctionMethods);
    ElunaTemplate<BattleGround>::Register(E, "BattleGround");
    ElunaTemplate<BattleGround>::SetMethods(E, BattleGroundMethods);
    ElunaTemplate<ChatHandler>::Register(E, "ChatHandler");
    ElunaTemplate<ChatHandler>::SetMethods(E, ChatHandlerMethods);
    ElunaTemplate<WorldPacket>::Register(E, "WorldPacket", true);
    ElunaTemplate<WorldPacket>::SetMethods(E, PacketMethods);
    ElunaTemplate<ElunaQuery>::Register(E, "ElunaQuery", true);
    ElunaTemplate<ElunaQuery>::SetMethods(E, QueryMethods);
    ElunaTemplate<AchievementEntry>::Register(E, "AchievementEntry");
    ElunaTemplate<AchievementEntry>::SetMethods(E, AchievementMethods);
    ElunaTemplate<Roll>::Register(E, "Roll");
    ElunaTemplate<Roll>::SetMethods(E, RollMethods);
    ElunaTemplate<long long>::Register(E, "long long", true);
    ElunaTemplate<unsigned long long>::Register(E, "unsigned long long", true);
}
References AchievementMethods, AuctionMethods, AuraMethods, BattleGroundMethods, ChatHandlerMethods, CorpseMethods, CreatureMethods, GameObjectMethods, GlobalMethods, GroupMethods, GuildMethods, ItemMethods, ItemTemplateMethods, MapMethods, ObjectMethods, PacketMethods, PlayerMethods, QueryMethods, QuestMethods, ElunaTemplate< T >::Register(), RollMethods, ElunaTemplate< T >::SetMethods(), ElunaGlobal::SetMethods(), SpellMethods, UnitMethods, VehicleMethods, and WorldObjectMethods.
Referenced by Eluna::OpenLua().
ScriptPathComparator()
static bool ScriptPathComparator (const LuaScript & first, const LuaScript & second) static
{
    return first.filepath < second.filepath;
}
References LuaScript::filepath.
Referenced by Eluna::RunScripts().