AzerothCore Doxygen
AutobroadcastMgr Class Reference
#include "AutobroadcastMgr.h"
Public Member Functions
void LoadAutobroadcasts ()
void LoadAutobroadcastsLocalized ()
void SendAutobroadcasts ()
Static Public Member Functions
static AutobroadcastMgr * instance ()
Private Types
typedef std::map< uint8, std::vector< std::string > > AutobroadcastsMap
typedef std::map< uint8, uint8 > AutobroadcastsWeightMap
Private Member Functions
void SendWorldAnnouncement (uint8 textId)
void SendNotificationAnnouncement (uint8 textId)
Private Attributes
AutobroadcastsMap _autobroadcasts
AutobroadcastsWeightMap _autobroadcastsWeights
AnnounceType _announceType
Detailed Description
Member Typedef Documentation
AutobroadcastsMap
typedef std::map<uint8, std::vector<std::string> > AutobroadcastMgr::AutobroadcastsMap private
AutobroadcastsWeightMap
typedef std::map<uint8, uint8> AutobroadcastMgr::AutobroadcastsWeightMap private
Member Function Documentation
instance()
AutobroadcastMgr * AutobroadcastMgr::instance () static
{
    static AutobroadcastMgr instance;
    return &instance;
}
References instance().
Referenced by instance().
LoadAutobroadcasts()
void AutobroadcastMgr::LoadAutobroadcasts ()
{
    uint32 oldMSTime = getMSTime();
    _autobroadcasts.clear();
    _autobroadcastsWeights.clear();
    uint32 realmId = sConfigMgr->GetOption<int32>("RealmID", 0);
    LoginDatabasePreparedStatement* stmt = LoginDatabase.GetPreparedStatement(LOGIN_SEL_AUTOBROADCAST);
    stmt->SetData(0, realmId);
    PreparedQueryResult result = LoginDatabase.Query(stmt);
    if (!result)
    {
        LOG_WARN("autobroadcast", ">> Loaded 0 autobroadcasts definitions. DB table `autobroadcast` is empty for this realm!");
        return;
    }
    _announceType = static_cast<AnnounceType>(sWorld->getIntConfig(CONFIG_AUTOBROADCAST_CENTER));
    if (_announceType < AnnounceType::World || _announceType > AnnounceType::Both)
    {
        LOG_ERROR("autobroadcast", "AutobroadcastMgr::LoadAutobroadcasts: Config option AutoBroadcast.Center set to not allowed value {}. Set to default value 0", (int8)_announceType);
        _announceType = AnnounceType::World;
    }
    do
    {
        Field* fields = result->Fetch();
        uint8 textId = fields[0].Get<uint8>();
        ObjectMgr::AddLocaleString(fields[2].Get<std::string>(), DEFAULT_LOCALE, _autobroadcasts[textId]);
        _autobroadcastsWeights[textId] = fields[1].Get<uint8>();
    } while (result->NextRow());
    LOG_INFO("server.loading", ">> Loaded {} Autobroadcast Definitions in {} ms", _autobroadcasts.size(), GetMSTimeDiffToNow(oldMSTime));
}
References _announceType, _autobroadcasts, _autobroadcastsWeights, ObjectMgr::AddLocaleString(), Both, CONFIG_AUTOBROADCAST_CENTER, DEFAULT_LOCALE, Field::Get(), getMSTime(), GetMSTimeDiffToNow(), LOG_ERROR, LOG_INFO, LOG_WARN, LOGIN_SEL_AUTOBROADCAST, LoginDatabase, sConfigMgr, PreparedStatementBase::SetData(), sWorld, and World.
LoadAutobroadcastsLocalized()
void AutobroadcastMgr::LoadAutobroadcastsLocalized ()
{
    uint32 oldMSTime = getMSTime();
    uint32 realmId = sConfigMgr->GetOption<int32>("RealmID", 0);
    if (_autobroadcasts.empty())
        return;
    LoginDatabasePreparedStatement* stmt = LoginDatabase.GetPreparedStatement(LOGIN_SEL_AUTOBROADCAST_LOCALIZED);
    stmt->SetData(0, realmId);
    PreparedQueryResult result = LoginDatabase.Query(stmt);
    if (!result)
    {
        LOG_WARN("server.loading", ">> Loaded 0 localized autobroadcasts definitions. DB table `autobroadcast_localized` is empty for this realm!");
        LOG_INFO("server.loading", " ");
        return;
    }
    uint8 count = 0;
    do
    {
        Field* fields = result->Fetch();
        uint8 textId = fields[0].Get<uint8>();
        LocaleConstant locale = GetLocaleByName(fields[1].Get<std::string>());
        if (locale == DEFAULT_LOCALE || ObjectMgr::GetLocaleString(_autobroadcasts[textId], DEFAULT_LOCALE).empty())
            continue;
        ObjectMgr::AddLocaleString(fields[2].Get<std::string>(), locale, _autobroadcasts[textId]);
        count++;
    } while (result->NextRow());
    LOG_INFO("server.loading", ">> Loaded {} Localized Autobroadcast Definitions in {} ms", count, GetMSTimeDiffToNow(oldMSTime));
    LOG_INFO("server.loading", " ");
}
References _autobroadcasts, ObjectMgr::AddLocaleString(), DEFAULT_LOCALE, Field::Get(), GetLocaleByName(), ObjectMgr::GetLocaleString(), getMSTime(), GetMSTimeDiffToNow(), LOG_INFO, LOG_WARN, LOGIN_SEL_AUTOBROADCAST_LOCALIZED, LoginDatabase, sConfigMgr, and PreparedStatementBase::SetData().
SendAutobroadcasts()
void AutobroadcastMgr::SendAutobroadcasts ()
{
    if (_autobroadcasts.empty())
        return;
    uint32 weight = 0;
    uint8 textId = 0;
    AutobroadcastsWeightMap selectionWeights;
    for (AutobroadcastsWeightMap::const_iterator it = _autobroadcastsWeights.begin(); it != _autobroadcastsWeights.end(); ++it)
    {
        if (it->second)
        {
            weight += it->second;
            selectionWeights[it->first] = it->second;
        }
    }
    if (weight)
    {
        uint32 selectedWeight = urand(0, weight - 1);
        weight = 0;
        for (AutobroadcastsWeightMap::const_iterator it = selectionWeights.begin(); it != selectionWeights.end(); ++it)
        {
            weight += it->second;
            if (selectedWeight < weight)
            {
                textId = it->first;
                break;
            }
        }
    }
    else
    {
        textId = urand(0, _autobroadcasts.size());
    }
    switch (_announceType)
    {
    case AnnounceType::World:
        SendWorldAnnouncement(textId);
        break;
    case AnnounceType::Notification:
        SendNotificationAnnouncement(textId);
        break;
    case AnnounceType::Both:
        SendWorldAnnouncement(textId);
        SendNotificationAnnouncement(textId);
    default:
        break;
    }
    LOG_DEBUG("autobroadcast", "AutobroadcastMgr::SendAutobroadcasts: '{}'", textId);
}
References _announceType, _autobroadcasts, _autobroadcastsWeights, Both, LOG_DEBUG, Notification, SendNotificationAnnouncement(), SendWorldAnnouncement(), urand(), and World.
SendNotificationAnnouncement()
void AutobroadcastMgr::SendNotificationAnnouncement (uint8 textId) private
{
    ChatHandler(nullptr).DoForAllValidSessions([&](Player* player)
    {
        // Retrieve player's locale
        LocaleConstant locale = player->GetSession()->GetSessionDbLocaleIndex();
        if (!_autobroadcasts.count(textId))
            return;
        // Get localized message
        std::string_view localizedMessage = ObjectMgr::GetLocaleString(_autobroadcasts[textId], locale);
        // Check if there is a localized message if not use default one.
        if (localizedMessage.empty())
            localizedMessage = ObjectMgr::GetLocaleString(_autobroadcasts[textId], DEFAULT_LOCALE);
        // Prepare the WorldPacket
        WorldPacket data(SMSG_NOTIFICATION, (localizedMessage.size() + 1));
        data << localizedMessage;
        // Send packet to the player
        player->GetSession()->SendPacket(&data);
    });
}
References _autobroadcasts, DEFAULT_LOCALE, ChatHandler::DoForAllValidSessions(), ObjectMgr::GetLocaleString(), Player::GetSession(), WorldSession::SendPacket(), and SMSG_NOTIFICATION.
Referenced by SendAutobroadcasts().
SendWorldAnnouncement()
void AutobroadcastMgr::SendWorldAnnouncement (uint8 textId) private
{
    // Send localized messages to all sessions
    ChatHandler(nullptr).DoForAllValidSessions([&](Player* player)
    {
        // Get player's locale
        LocaleConstant locale = player->GetSession()->GetSessionDbLocaleIndex();
        if (!_autobroadcasts.empty())
            return;
        std::string_view localizedMessage = ObjectMgr::GetLocaleString(_autobroadcasts[textId], locale);
        // Check if there is a localized message if not use default one.
        if (localizedMessage.empty())
            localizedMessage = ObjectMgr::GetLocaleString(_autobroadcasts[textId], DEFAULT_LOCALE);
        // Send the localized or fallback message
        ChatHandler(player->GetSession()).SendWorldTextOptional(localizedMessage, ANNOUNCER_FLAG_DISABLE_AUTOBROADCAST);
    });
}
References _autobroadcasts, ANNOUNCER_FLAG_DISABLE_AUTOBROADCAST, DEFAULT_LOCALE, ChatHandler::DoForAllValidSessions(), ObjectMgr::GetLocaleString(), Player::GetSession(), and ChatHandler::SendWorldTextOptional().
Referenced by SendAutobroadcasts().
Member Data Documentation
_announceType
AnnounceType AutobroadcastMgr::_announceType private
Referenced by LoadAutobroadcasts(), and SendAutobroadcasts().
_autobroadcasts
AutobroadcastsMap AutobroadcastMgr::_autobroadcasts private
Referenced by LoadAutobroadcasts(), LoadAutobroadcastsLocalized(), SendAutobroadcasts(), SendNotificationAnnouncement(), and SendWorldAnnouncement().
_autobroadcastsWeights
AutobroadcastsWeightMap AutobroadcastMgr::_autobroadcastsWeights private
Referenced by LoadAutobroadcasts(), and SendAutobroadcasts().
The documentation for this class was generated from the following files:
azerothcore-wotlk/src/server/game/Autobroadcast/AutobroadcastMgr.h
azerothcore-wotlk/src/server/game/Autobroadcast/AutobroadcastMgr.cpp