AzerothCore Doxygen
AuraScriptProcTestFixture Class Reference
Base fixture for AuraScript proc testing.
#include "AuraScriptTestFramework.h"
Protected Member Functions
void SetUp () override
void TearDown () override
ProcTestContext & Context ()
SpellInfo * CreateSpellInfo (uint32_t id, uint32_t familyName=0, uint32_t familyFlags0=0, uint32_t familyFlags1=0, uint32_t familyFlags2=0)
SpellProcEntry CreateProcEntry ()
ProcEventInfo CreateEventInfo (uint32_t typeMask, uint32_t hitMask, uint32_t spellTypeMask=PROC_SPELL_TYPE_MASK_ALL, uint32_t spellPhaseMask=PROC_SPELL_PHASE_HIT)
bool TestCanProc (SpellProcEntry const &procEntry, uint32_t typeMask, uint32_t hitMask, SpellInfo const *triggerSpell=nullptr)
bool TestSpellFamilyMatch (uint32_t procFamilyName, flag96 const &procFamilyMask, SpellInfo const *triggerSpell)
Private Attributes
std::unique_ptr< ProcTestContext > _context
std::vector< SpellInfo * > _spellInfos
Detailed Description
Base fixture for AuraScript proc testing.
This provides infrastructure for testing proc behavior at the unit level without requiring full game objects.
Member Function Documentation
Context()
ProcTestContext & AuraScriptProcTestFixture::Context () inline protected
{ return *_context; }
References _context.
CreateEventInfo()
ProcEventInfo AuraScriptProcTestFixture::CreateEventInfo (uint32_t typeMask, uint32_t hitMask, uint32_t spellTypeMask = PROC_SPELL_TYPE_MASK_ALL, uint32_t spellPhaseMask = PROC_SPELL_PHASE_HIT) inline protected
    {
        return ProcEventInfoBuilder()
            .WithTypeMask(typeMask)
            .WithHitMask(hitMask)
            .WithSpellTypeMask(spellTypeMask)
            .WithSpellPhaseMask(spellPhaseMask)
            .Build();
    }
References ProcEventInfoBuilder::Build(), spellTypeMask, ProcEventInfoBuilder::WithHitMask(), ProcEventInfoBuilder::WithSpellPhaseMask(), ProcEventInfoBuilder::WithSpellTypeMask(), and ProcEventInfoBuilder::WithTypeMask().
CreateProcEntry()
SpellProcEntry AuraScriptProcTestFixture::CreateProcEntry () inline protected
    {
        return SpellProcEntryBuilder().Build();
    }
References SpellProcEntryBuilder::Build().
CreateSpellInfo()
SpellInfo * AuraScriptProcTestFixture::CreateSpellInfo (uint32_t id, uint32_t familyName = 0, uint32_t familyFlags0 = 0, uint32_t familyFlags1 = 0, uint32_t familyFlags2 = 0) inline protected
    {
        auto* spellInfo = SpellInfoBuilder()
            .WithId(id)
            .WithSpellFamilyName(familyName)
            .WithSpellFamilyFlags(familyFlags0, familyFlags1, familyFlags2)
            .Build();
        _spellInfos.push_back(spellInfo);
        return spellInfo;
    }
References _spellInfos, SpellInfoBuilder::Build(), SpellInfoBuilder::WithId(), SpellInfoBuilder::WithSpellFamilyFlags(), and SpellInfoBuilder::WithSpellFamilyName().
SetUp()
void AuraScriptProcTestFixture::SetUp () inline override protected
    {
        _context = std::make_unique<ProcTestContext>();
        _spellInfos.clear();
    }
References _context, and _spellInfos.
Referenced by SpellProcIntegrationTest::SetUp(), and SpellProcSpellTypeMaskTest::SetUp().
TearDown()
void AuraScriptProcTestFixture::TearDown () inline override protected
    {
        for (auto* spellInfo : _spellInfos)
        {
            delete spellInfo;
        }
        _spellInfos.clear();
    }
References _spellInfos.
TestCanProc()
bool AuraScriptProcTestFixture::TestCanProc (SpellProcEntry const & procEntry, uint32_t typeMask, uint32_t hitMask, SpellInfo const * triggerSpell = nullptr) inline protected
    {
        DamageInfo* damageInfoPtr = nullptr;
        HealInfo* healInfoPtr = nullptr;
        // Create real DamageInfo/HealInfo if we have a trigger spell
        // Note: This requires the actual game classes, which may need adjustment
        // For now, we use the stub approach
        auto eventInfo = ProcEventInfoBuilder()
            .WithTypeMask(typeMask)
            .WithHitMask(hitMask)
            .WithSpellTypeMask(PROC_SPELL_TYPE_MASK_ALL)
            .WithSpellPhaseMask(PROC_SPELL_PHASE_HIT)
            .Build();
        return sSpellMgr->CanSpellTriggerProcOnEvent(procEntry, eventInfo);
    }
References ProcEventInfoBuilder::Build(), PROC_SPELL_PHASE_HIT, PROC_SPELL_TYPE_MASK_ALL, sSpellMgr, ProcEventInfoBuilder::WithHitMask(), ProcEventInfoBuilder::WithSpellPhaseMask(), ProcEventInfoBuilder::WithSpellTypeMask(), and ProcEventInfoBuilder::WithTypeMask().
TestSpellFamilyMatch()
bool AuraScriptProcTestFixture::TestSpellFamilyMatch (uint32_t procFamilyName, flag96 const & procFamilyMask, SpellInfo const * triggerSpell) inline protected
    {
        if (procFamilyName && triggerSpell)
        {
            if (procFamilyName != triggerSpell->SpellFamilyName)
                return false;
            if (procFamilyMask)
            {
                flag96 triggerMask;
                triggerMask[0] = triggerSpell->SpellFamilyFlags[0];
                triggerMask[1] = triggerSpell->SpellFamilyFlags[1];
                triggerMask[2] = triggerSpell->SpellFamilyFlags[2];
                if (!(triggerMask & procFamilyMask))
                    return false;
            }
        }
        return true;
    }
References SpellInfo::SpellFamilyFlags, and SpellInfo::SpellFamilyName.
Member Data Documentation
_context
std::unique_ptr<ProcTestContext> AuraScriptProcTestFixture::_context private
Referenced by Context(), and SetUp().
_spellInfos
std::vector<SpellInfo*> AuraScriptProcTestFixture::_spellInfos private
Referenced by CreateSpellInfo(), SetUp(), and TearDown().
The documentation for this class was generated from the following file:
azerothcore-wotlk/src/test/mocks/AuraScriptTestFramework.h