AzerothCore Doxygen
instance_zulaman::instance_zulaman_InstanceMapScript Struct Reference
Public Member Functions
instance_zulaman_InstanceMapScript (Map *map)
void Initialize () override
void OnPlayerEnter (Player *) override
void OnCreatureCreate (Creature *creature) override
void OnGameObjectCreate (GameObject *go) override
void SummonHostage (uint8 num)
void DoAction (int32 actionId) override
void CheckInstanceStatus (GameObject *gate=nullptr)
void SetData (uint32 type, uint32 data) override
void StartAkilzonGauntlet ()
void ResetAkilzonGauntlet ()
void OnUnitDeath (Unit *unit) override
void OnCreatureEvade (Creature *creature) override
bool SetBossState (uint32 type, EncounterState state) override
uint32 GetData (uint32 type) const override
void Update (uint32 diff) override
Public Member Functions inherited from InstanceScript
InstanceScript (Map *map)
~InstanceScript () override
virtual void Load (char const *data)
virtual void CreatureLooted (Creature *, LootType)
virtual std::string GetSaveData ()
void SaveToDB ()
virtual bool IsEncounterInProgress () const
void OnCreatureCreate (Creature *creature) override
void OnCreatureRemove (Creature *creature) override
void OnGameObjectCreate (GameObject *go) override
void OnGameObjectRemove (GameObject *go) override
ObjectGuid GetObjectGuid (uint32 type) const
ObjectGuid GetGuidData (uint32 type) const override
Creature * GetCreature (uint32 type)
GameObject * GetGameObject (uint32 type)
virtual void OnPlayerLeave (Player *)
virtual void OnPlayerAreaUpdate (Player *, uint32, uint32)
virtual void OnPlayerInWaterStateUpdate (Player *, bool)
void HandleGameObject (ObjectGuid guid, bool open, GameObject *go=nullptr)
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
void DoRespawnGameObject (uint32 type)
void DoRespawnCreature (ObjectGuid guid, bool force=false)
void DoRespawnCreature (uint32 type, bool force=false)
void DoUpdateWorldState (uint32 worldstateId, uint32 worldstateValue)
void DoSendNotifyToInstance (char const *format,...)
void DoUpdateAchievementCriteria (AchievementCriteriaTypes type, uint32 miscValue1=0, uint32 miscValue2=0, Unit *unit=nullptr)
void DoStartTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoStopTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoRemoveAurasDueToSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayer (Player *player, uint32 spell, bool includePets, bool includeControlled)
bool ServerAllowsTwoSideGroups ()
EncounterState GetBossState (uint32 id) const
CreatureBoundary const * GetBossBoundary (uint32 id) const
BossInfo const * GetBossInfo (uint32 id) const
uint32 GetPersistentData (uint32 index) const
void StorePersistentData (uint32 index, uint32 data)
virtual bool CheckAchievementCriteriaMeet (uint32, Player const *, Unit const *=nullptr, uint32=0)
virtual bool CheckRequiredBosses (uint32, Player const *=nullptr) const
void SetCompletedEncountersMask (uint32 newMask, bool save)
uint32 GetCompletedEncounterMask () const
void SendEncounterUnit (uint32 type, Unit *unit=nullptr, uint8 param1=0, uint8 param2=0)
virtual void FillInitialWorldStates (WorldPackets::WorldState::InitWorldStates &)
uint32 GetEncounterCount () const
void MarkAreaTriggerDone (uint32 id)
void ResetAreaTriggerDone (uint32 id)
bool IsAreaTriggerDone (uint32 id) const
void DoForAllMinions (uint32 id, std::function< void(Creature *)> exec)
void StoreGameObjectState (ObjectGuid::LowType spawnId, uint8 state)
uint8 GetStoredGameObjectState (ObjectGuid::LowType spawnId) const
void LoadInstanceSavedGameobjectStateData ()
bool IsBossDone (uint32 bossId) const
bool AllBossesDone () const
bool AllBossesDone (std::initializer_list< uint32 > bossIds) const
TeamId GetTeamIdInInstance () const
void SetTeamIdInInstance (TeamId teamId)
bool IsTwoFactionInstance () const
Public Member Functions inherited from ZoneScript
ZoneScript ()
virtual ~ZoneScript ()
virtual uint32 GetCreatureEntry (ObjectGuid::LowType, CreatureData const *data)
virtual uint32 GetGameObjectEntry (ObjectGuid::LowType, uint32 entry)
virtual void SetGuidData (uint32, ObjectGuid)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
virtual void ProcessEvent (WorldObject *, uint32)
Private Attributes
uint32 RandVendor [RAND_VENDOR]
GuidSet AkilzonTrash
EncounterState _akilzonGauntlet = NOT_STARTED
Additional Inherited Members
Static Public Member Functions inherited from InstanceScript
static std::string GetBossStateName (uint8 state)
Public Attributes inherited from InstanceScript
Map * instance
TaskScheduler scheduler
Protected Member Functions inherited from InstanceScript
void SetHeaders (std::string const &dataHeaders)
void SetBossNumber (uint32 number)
void SetPersistentDataCount (uint32 number)
void LoadBossBoundaries (BossBoundaryData const &data)
void LoadDoorData (DoorData const *data)
void LoadMinionData (MinionData const *data)
void LoadObjectData (ObjectData const *creatureData, ObjectData const *gameObjectData)
void LoadSummonData (ObjectData const *data)
void SetSummoner (Creature *creature)
void AddObject (Creature *obj, bool add=true)
void RemoveObject (Creature *obj)
void AddObject (GameObject *obj, bool add=true)
void RemoveObject (GameObject *obj)
void AddObject (WorldObject *obj, uint32 type, bool add=true)
void RemoveObject (WorldObject *obj, uint32 type)
void AddDoor (GameObject *door, bool add=true)
void RemoveDoor (GameObject *door)
void AddMinion (Creature *minion, bool add=true)
void RemoveMinion (Creature *minion)
void UpdateDoorState (GameObject *door)
void UpdateMinionState (Creature *minion, EncounterState state)
bool ReadSaveDataHeaders (std::istringstream &data)
void ReadSaveDataBossStates (std::istringstream &data)
void ReadSavePersistentData (std::istringstream &data)
virtual void ReadSaveDataMore (std::istringstream &)
void WriteSaveDataHeaders (std::ostringstream &data)
void WriteSaveDataBossStates (std::ostringstream &data)
void WritePersistentData (std::ostringstream &data)
virtual void WriteSaveDataMore (std::ostringstream &)
Detailed Description
Constructor & Destructor Documentation
instance_zulaman_InstanceMapScript()
instance_zulaman::instance_zulaman_InstanceMapScript::instance_zulaman_InstanceMapScript (Map * map) inline
: InstanceScript(map) {}
Member Function Documentation
CheckInstanceStatus()
void instance_zulaman::instance_zulaman_InstanceMapScript::CheckInstanceStatus (GameObject * gate = nullptr) inline
        {
            if (AllBossesDone({ DATA_NALORAKK, DATA_AKILZON, DATA_JANALAI, DATA_HALAZZI }))
                HandleGameObject(ObjectGuid::Empty, true, gate ? gate : GetGameObject(DATA_HEXLORD_GATE));
        }
References InstanceScript::AllBossesDone(), DATA_AKILZON, DATA_HALAZZI, DATA_HEXLORD_GATE, DATA_JANALAI, DATA_NALORAKK, ObjectGuid::Empty, InstanceScript::GetGameObject(), and InstanceScript::HandleGameObject().
Referenced by OnGameObjectCreate(), and SetBossState().
DoAction()
void instance_zulaman::instance_zulaman_InstanceMapScript::DoAction (int32 actionId) inline override virtual
Reimplemented from InstanceScript.
        {
            if (actionId == ACTION_START_TIMED_RUN)
            {
                if (uint32 timer = GetPersistentData(DATA_TIMED_RUN))
                {
                    DoUpdateWorldState(WORLD_STATE_ZUL_AMAN_SHOW_TIMER, 1);
                    DoUpdateWorldState(WORLD_STATE_ZUL_AMAN_TIME_TO_SACRIFICE, timer);
                }
                scheduler.Schedule(1min, GROUP_TIMED_RUN, [this](TaskContext context)
                {
                    if (uint32 timer = GetPersistentData(DATA_TIMED_RUN))
                    {
                        --timer;
                        DoUpdateWorldState(WORLD_STATE_ZUL_AMAN_SHOW_TIMER, 1);
                        DoUpdateWorldState(WORLD_STATE_ZUL_AMAN_TIME_TO_SACRIFICE, timer);
                        StorePersistentData(DATA_TIMED_RUN, timer);
                        context.Repeat();
                    }
                    else
                        DoUpdateWorldState(WORLD_STATE_ZUL_AMAN_SHOW_TIMER, 0);
                });
            }
        }
References ACTION_START_TIMED_RUN, DATA_TIMED_RUN, InstanceScript::DoUpdateWorldState(), InstanceScript::GetPersistentData(), GROUP_TIMED_RUN, TaskContext::Repeat(), TaskScheduler::Schedule(), InstanceScript::scheduler, InstanceScript::StorePersistentData(), WORLD_STATE_ZUL_AMAN_SHOW_TIMER, and WORLD_STATE_ZUL_AMAN_TIME_TO_SACRIFICE.
Referenced by OnPlayerEnter().
GetData()
uint32 instance_zulaman::instance_zulaman_InstanceMapScript::GetData (uint32 type) const inline override virtual
Reimplemented from ZoneScript.
        {
            if (type == TYPE_RAND_VENDOR_1)
                return RandVendor[0];
            else if (type == TYPE_RAND_VENDOR_2)
                return RandVendor[1];
            else if (type == TYPE_AKILZON_GAUNTLET)
                return _akilzonGauntlet;
            else if (type == DATA_CHEST_LOOTED)
                return GetPersistentData(DATA_CHEST_COUNT);
            return 0;
        }
References _akilzonGauntlet, DATA_CHEST_COUNT, DATA_CHEST_LOOTED, InstanceScript::GetPersistentData(), RandVendor, TYPE_AKILZON_GAUNTLET, TYPE_RAND_VENDOR_1, and TYPE_RAND_VENDOR_2.
Initialize()
void instance_zulaman::instance_zulaman_InstanceMapScript::Initialize () inline override virtual
Reimplemented from InstanceScript.
        {
            SetHeaders(DataHeader);
            SetBossNumber(MAX_ENCOUNTER);
            SetPersistentDataCount(PersistentDataCount);
            LoadObjectData(creatureData, gameObjectData);
            LoadBossBoundaries(boundaries);
            LoadDoorData(doorData);
            LoadSummonData(summonData);
            for (uint8 i = 0; i < RAND_VENDOR; ++i)
                RandVendor[i] = NOT_STARTED;
            StorePersistentData(DATA_TIMED_RUN, 0);
        }
References boundaries, creatureData, DATA_TIMED_RUN, DataHeader, doorData, gameObjectData, InstanceScript::LoadBossBoundaries(), InstanceScript::LoadDoorData(), InstanceScript::LoadObjectData(), InstanceScript::LoadSummonData(), MAX_ENCOUNTER, NOT_STARTED, PersistentDataCount, RAND_VENDOR, RandVendor, InstanceScript::SetBossNumber(), InstanceScript::SetHeaders(), InstanceScript::SetPersistentDataCount(), InstanceScript::StorePersistentData(), and summonData.
OnCreatureCreate()
void instance_zulaman::instance_zulaman_InstanceMapScript::OnCreatureCreate (Creature * creature) inline override virtual
Reimplemented from ZoneScript.
        {
            switch (creature->GetEntry())
            {
                case NPC_AMANISHI_GUARDIAN:
                case NPC_AMANISHI_SAVAGE:
                    if (creature->GetPositionY() >= 1500.0f) // gate
                        creature->SetImmuneToAll(true);
                    break;
                // Akil'zon gauntlet
                case NPC_AMANISHI_TEMPEST:
                    if (creature->GetPositionZ() >= 50.0f) // excludes Tempest in Hexlord Malacrass' trash
                        AkilzonTrash.insert(creature->GetGUID());
                    break;
                case NPC_AMANISHI_LOOKOUT:
                case NPC_AMANISHI_PROTECTOR:
                case NPC_EAGLE_TRASH_AGGRO_TRIGGER:
                    AkilzonTrash.insert(creature->GetGUID());
                    break;
                case NPC_AMANISHI_WIND_WALKER:
                    if (creature->GetPositionZ() >= 26.0f) // excludes Wind Walker in first patrol
                        AkilzonTrash.insert(creature->GetGUID());
                    break;
            }
            InstanceScript::OnCreatureCreate(creature);
        }
References AkilzonTrash, Object::GetEntry(), Object::GetGUID(), Position::GetPositionY(), Position::GetPositionZ(), NPC_AMANISHI_GUARDIAN, NPC_AMANISHI_LOOKOUT, NPC_AMANISHI_PROTECTOR, NPC_AMANISHI_SAVAGE, NPC_AMANISHI_TEMPEST, NPC_AMANISHI_WIND_WALKER, NPC_EAGLE_TRASH_AGGRO_TRIGGER, InstanceScript::OnCreatureCreate(), and Unit::SetImmuneToAll().
OnCreatureEvade()
void instance_zulaman::instance_zulaman_InstanceMapScript::OnCreatureEvade (Creature * creature) inline override virtual
Reimplemented from ZoneScript.
        {
            switch (creature->GetEntry())
            {
                case NPC_AMANISHI_TEMPEST:
                case NPC_AMANISHI_PROTECTOR:
                case NPC_AMANISHI_WIND_WALKER:
                    if (AkilzonTrash.contains(creature->GetGUID()))
                        ResetAkilzonGauntlet();
                    break;
                default:
                    break;
            }
        }
References AkilzonTrash, Object::GetEntry(), Object::GetGUID(), NPC_AMANISHI_PROTECTOR, NPC_AMANISHI_TEMPEST, NPC_AMANISHI_WIND_WALKER, and ResetAkilzonGauntlet().
OnGameObjectCreate()
void instance_zulaman::instance_zulaman_InstanceMapScript::OnGameObjectCreate (GameObject * go) inline override virtual
Reimplemented from ZoneScript.
        {
            InstanceScript::OnGameObjectCreate(go);
            if (go->GetEntry() == GO_GATE_HEXLORD)
                CheckInstanceStatus(go);
        }
References CheckInstanceStatus(), Object::GetEntry(), GO_GATE_HEXLORD, and InstanceScript::OnGameObjectCreate().
OnPlayerEnter()
void instance_zulaman::instance_zulaman_InstanceMapScript::OnPlayerEnter (Player *) inline override virtual
Reimplemented from InstanceScript.
        {
            if (!scheduler.IsGroupScheduled(GROUP_TIMED_RUN) && GetPersistentData(DATA_TIMED_RUN))
                DoAction(ACTION_START_TIMED_RUN);
        }
References ACTION_START_TIMED_RUN, DATA_TIMED_RUN, DoAction(), InstanceScript::GetPersistentData(), GROUP_TIMED_RUN, TaskScheduler::IsGroupScheduled(), and InstanceScript::scheduler.
OnUnitDeath()
void instance_zulaman::instance_zulaman_InstanceMapScript::OnUnitDeath (Unit * unit) inline override virtual
Reimplemented from ZoneScript.
        {
            Creature* creature = unit->ToCreature();
            if (!creature)
                return;
            switch (creature->GetEntry())
            {
                case NPC_AMANISHI_PROTECTOR:
                case NPC_AMANISHI_WIND_WALKER:
                    if (_akilzonGauntlet == NOT_STARTED && AkilzonTrash.contains(creature->GetGUID()))
                        creature->DespawnOrUnsummon(30s, 1s);
                default:
                    break;
            }
        }
References _akilzonGauntlet, AkilzonTrash, Creature::DespawnOrUnsummon(), Object::GetEntry(), Object::GetGUID(), NOT_STARTED, NPC_AMANISHI_PROTECTOR, NPC_AMANISHI_WIND_WALKER, and Object::ToCreature().
ResetAkilzonGauntlet()
void instance_zulaman::instance_zulaman_InstanceMapScript::ResetAkilzonGauntlet () inline
        {
            _akilzonGauntlet = NOT_STARTED;
            for (ObjectGuid guid : AkilzonTrash)
                if (Creature* creature = instance->GetCreature(guid))
                {
                    if (!creature->IsAlive())
                        creature->Respawn();
                    else if (creature->GetEntry() == NPC_AMANISHI_TEMPEST)
                        creature->AI()->DoAction(ACTION_RESET_AKILZON_GAUNTLET);
                }
            if (Creature* creature = GetCreature(DATA_LOOKOUT))
                if (creature->isMoving())
                    creature->Respawn(true);
        }
References _akilzonGauntlet, ACTION_RESET_AKILZON_GAUNTLET, AkilzonTrash, DATA_LOOKOUT, Map::GetCreature(), InstanceScript::GetCreature(), InstanceScript::instance, NOT_STARTED, and NPC_AMANISHI_TEMPEST.
Referenced by OnCreatureEvade(), and SetData().
SetBossState()
bool instance_zulaman::instance_zulaman_InstanceMapScript::SetBossState (uint32 type, EncounterState state) inline override virtual
Reimplemented from InstanceScript.
        {
            if (!InstanceScript::SetBossState(type, state))
                return false;
            if (state == DONE)
            {
                switch (type)
                {
                    case DATA_NALORAKK:
                        if (uint32 timer = GetPersistentData(DATA_TIMED_RUN))
{
                            StorePersistentData(DATA_TIMED_RUN, timer += 15);
                            DoUpdateWorldState(WORLD_STATE_ZUL_AMAN_TIME_TO_SACRIFICE, timer);
                        }
                        SummonHostage(type);
                        break;
                    case DATA_AKILZON:
                        if (uint32 timer = GetPersistentData(DATA_TIMED_RUN))
{
                            StorePersistentData(DATA_TIMED_RUN, timer += 10);
                            DoUpdateWorldState(WORLD_STATE_ZUL_AMAN_TIME_TO_SACRIFICE, timer);
                        }
                        SummonHostage(type);
                        break;
                    case DATA_JANALAI:
                    case DATA_HALAZZI:
                        SummonHostage(type);
                        break;
                    case DATA_HEXLORD:
                        if (GameObject* zuljinGate = GetGameObject(DATA_ZULJIN_GATE))
                            zuljinGate->RemoveGameObjectFlag(GO_FLAG_LOCKED);
                        break;
                }
                if (GetPersistentData(DATA_TIMED_RUN) && AllBossesDone({ DATA_NALORAKK, DATA_AKILZON, DATA_JANALAI, DATA_HALAZZI }))
                {
                    StorePersistentData(DATA_TIMED_RUN, 0);
                    DoUpdateWorldState(WORLD_STATE_ZUL_AMAN_SHOW_TIMER, 0);
                }
                CheckInstanceStatus();
            }
            else
            {
                if (type == DATA_HEXLORD)
                {
                    if (state == IN_PROGRESS)
                        HandleGameObject(ObjectGuid::Empty, false, GetGameObject(DATA_HEXLORD_GATE));
                    else if (state == NOT_STARTED)
                        CheckInstanceStatus();
                }
            }
            return true;
        }
References InstanceScript::AllBossesDone(), CheckInstanceStatus(), DATA_AKILZON, DATA_HALAZZI, DATA_HEXLORD, DATA_HEXLORD_GATE, DATA_JANALAI, DATA_NALORAKK, DATA_TIMED_RUN, DATA_ZULJIN_GATE, DONE, InstanceScript::DoUpdateWorldState(), ObjectGuid::Empty, InstanceScript::GetGameObject(), InstanceScript::GetPersistentData(), GO_FLAG_LOCKED, InstanceScript::HandleGameObject(), IN_PROGRESS, NOT_STARTED, InstanceScript::SetBossState(), InstanceScript::StorePersistentData(), SummonHostage(), WORLD_STATE_ZUL_AMAN_SHOW_TIMER, and WORLD_STATE_ZUL_AMAN_TIME_TO_SACRIFICE.
SetData()
void instance_zulaman::instance_zulaman_InstanceMapScript::SetData (uint32 type, uint32 data) inline override virtual
Reimplemented from ZoneScript.
        {
            if (type == TYPE_RAND_VENDOR_1)
                RandVendor[0] = data;
            else if (type == TYPE_RAND_VENDOR_2)
                RandVendor[1] = data;
            else if (type == TYPE_AKILZON_GAUNTLET)
            {
                if (data == IN_PROGRESS)
                    StartAkilzonGauntlet();
                else if (data == NOT_STARTED)
                    ResetAkilzonGauntlet();
                else if (data == DONE)
                    _akilzonGauntlet = DONE;
            }
            else if (type == DATA_CHEST_LOOTED)
            {
                uint8 chestCount = GetPersistentData(DATA_CHEST_COUNT);
                StorePersistentData(DATA_CHEST_COUNT, ++chestCount);
            }
        }
References _akilzonGauntlet, DATA_CHEST_COUNT, DATA_CHEST_LOOTED, DONE, InstanceScript::GetPersistentData(), IN_PROGRESS, NOT_STARTED, RandVendor, ResetAkilzonGauntlet(), StartAkilzonGauntlet(), InstanceScript::StorePersistentData(), TYPE_AKILZON_GAUNTLET, TYPE_RAND_VENDOR_1, and TYPE_RAND_VENDOR_2.
StartAkilzonGauntlet()
void instance_zulaman::instance_zulaman_InstanceMapScript::StartAkilzonGauntlet () inline
        {
            _akilzonGauntlet = IN_PROGRESS;
            for (ObjectGuid const& guid : AkilzonTrash)
                if (Creature* creature = instance->GetCreature(guid))
                    switch (creature->GetEntry())
                    {
                        case NPC_EAGLE_TRASH_AGGRO_TRIGGER:
                            creature->DisappearAndDie();
                            break;
                        case NPC_AMANISHI_LOOKOUT:
                        case NPC_AMANISHI_TEMPEST:
                            creature->AI()->DoAction(ACTION_START_AKILZON_GAUNTLET);
                            break;
                        default:
                            break;
                    }
        }
References _akilzonGauntlet, ACTION_START_AKILZON_GAUNTLET, AkilzonTrash, Map::GetCreature(), IN_PROGRESS, InstanceScript::instance, NPC_AMANISHI_LOOKOUT, NPC_AMANISHI_TEMPEST, and NPC_EAGLE_TRASH_AGGRO_TRIGGER.
Referenced by SetData().
SummonHostage()
void instance_zulaman::instance_zulaman_InstanceMapScript::SummonHostage (uint8 num) inline
        {
            if (!GetPersistentData(DATA_TIMED_RUN))
                return;
            instance->SummonCreature(HostageInfo[num].npc, HostageInfo[num].pos);
        }
References DATA_TIMED_RUN, InstanceScript::GetPersistentData(), HostageInfo, InstanceScript::instance, and Map::SummonCreature().
Referenced by SetBossState().
Update()
void instance_zulaman::instance_zulaman_InstanceMapScript::Update (uint32 diff) inline override virtual
Reimplemented from InstanceScript.
        {
            scheduler.Update(diff);
        }
References InstanceScript::scheduler, and TaskScheduler::Update().
Member Data Documentation
_akilzonGauntlet
EncounterState instance_zulaman::instance_zulaman_InstanceMapScript::_akilzonGauntlet = NOT_STARTED private
Referenced by GetData(), OnUnitDeath(), ResetAkilzonGauntlet(), SetData(), and StartAkilzonGauntlet().
AkilzonTrash
GuidSet instance_zulaman::instance_zulaman_InstanceMapScript::AkilzonTrash private
Referenced by OnCreatureCreate(), OnCreatureEvade(), OnUnitDeath(), ResetAkilzonGauntlet(), and StartAkilzonGauntlet().
RandVendor
uint32 instance_zulaman::instance_zulaman_InstanceMapScript::RandVendor[RAND_VENDOR] private
Referenced by GetData(), Initialize(), and SetData().
The documentation for this struct was generated from the following file:
azerothcore-wotlk/src/server/scripts/EasternKingdoms/ZulAman/instance_zulaman.cpp