AzerothCore Doxygen
spell_item.cpp File Reference
#include "AreaDefines.h"
#include "Battleground.h"
#include "CreatureScript.h"
#include "ObjectMgr.h"
#include "Pet.h"
#include "Player.h"
#include "ScriptedCreature.h"
#include "SkillDiscovery.h"
#include "SpellAuraEffects.h"
#include "SpellMgr.h"
#include "SpellScript.h"
#include "SpellScriptLoader.h"
#include "WorldSession.h"
Classes
class spell_item_massive_seaforium_charge
class spell_item_titanium_seal_of_dalaran
class spell_item_mind_amplify_dish
class spell_item_runescroll_of_fortitude
class spell_item_branns_communicator
class spell_item_goblin_gumbo_kettle
class spell_item_with_mount_speed
class spell_item_magic_dust
class spell_item_toy_train_set
class spell_item_rocket_chicken
class spell_item_sleepy_willy
class spell_item_lil_phylactery
class spell_item_shifting_naaru_silver
class spell_item_toxic_wasteling
class spell_item_lil_xt
class spell_item_essence_of_life
class spell_item_crazy_alchemists_potion
class spell_item_skull_of_impeding_doom
class spell_item_feast
class spell_item_gnomish_universal_remote
class spell_item_powerful_anti_venom
class spell_item_strong_anti_venom
class spell_item_anti_venom
class spell_item_gnomish_shrink_ray
class spell_item_goblin_weather_machine
class spell_item_goblin_weather_machine_aura
class spell_item_light_lamp
class spell_item_fetch_ball
class spell_item_oracle_ablutions
class spell_item_trauma
class spell_item_blade_ward_enchant
class spell_item_blood_draining_enchant
class spell_item_dragon_kite_summon_lightning_bunny
class spell_item_enchanted_broom_periodic
class spell_item_summon_or_dismiss
class spell_item_draenic_pale_ale
class spell_item_direbrew_remote
class spell_item_direbrew_remote_aura
class spell_item_healing_trance
class spell_item_summon_argent_knight
class spell_item_instant_statue
class spell_item_trigger_spell
class spell_item_aegis_of_preservation
class spell_item_arcane_shroud
class spell_item_valanyr_hammer_of_ancient_kings
class spell_item_brittle_armor
class spell_item_blessing_of_ancient_kings
class spell_item_defibrillate
class spell_item_desperate_defense
class spell_item_deviate_fish
class PartyTimeEmoteEvent
class spell_item_party_time
class spell_item_echoes_of_light
class spell_item_fate_rune_of_unsurpassed_vigor
class spell_item_flask_of_the_north
class spell_item_gnomish_death_ray
class spell_item_make_a_wish
class spell_item_mercurial_shield
class spell_item_mingos_fortune_generator
class spell_item_necrotic_touch
class spell_item_net_o_matic
class spell_item_noggenfogger_elixir
class spell_item_piccolo_of_the_flaming_fire
class spell_item_savory_deviate_delight
class spell_item_scroll_of_recall
class spell_item_dimensional_ripper_area52
class spell_item_unsated_craving
class spell_item_shadows_fate
class spell_item_shadowmourne
class spell_item_shadowmourne_soul_fragment
class spell_item_six_demon_bag
class spell_item_the_eye_of_diminution
class spell_item_underbelly_elixir
class spell_item_book_of_glyph_mastery
class spell_item_map_of_the_geyser_fields
class spell_item_vanquished_clutches
class spell_item_ashbringer
class spell_magic_eater_food
class spell_item_shimmering_vessel
class spell_item_purify_helboar_meat
class spell_item_reindeer_transformation
class spell_item_nigh_invulnerability
class spell_item_poultryizer
class spell_item_socrethars_stone
class spell_item_demon_broiled_surprise
class spell_item_complete_raptor_capture
class spell_item_impale_leviroth
class spell_item_brewfest_mount_transformation
class spell_item_brewfest_hops
class spell_item_nitro_boots
class spell_item_teach_language
class spell_item_rocket_boots
class spell_item_healing_injector
class spell_item_mana_injector
class spell_item_pygmy_oil
class spell_item_unusual_compass
class spell_item_chicken_cover
class spell_item_refocus
class spell_item_muisek_vessel
class spell_item_greatmothers_soulcatcher
class spell_item_eggnog
class spell_item_goblin_bomb
class spell_item_linken_boomerang
class spell_item_recall
class spell_item_wraith_scythe_drain_life
class spell_item_mirrens_drinking_hat
class spell_item_snowman
class spell_item_freeze_rookery_egg
class spell_item_green_whelp_armor
class spell_item_elixir_of_shadows
class spell_item_worn_troll_dice
class spell_item_venomhide_feed
class spell_item_scroll_of_retribution
class spell_item_eye_of_grillok
class spell_item_eye_of_grillok_aura
class spell_item_fel_mana_potion
class spell_item_gor_dreks_ointment
class spell_item_skyguard_blasting_charges
class spell_item_luffa
class spell_item_spell_reflectors
class spell_item_multiphase_goggles
class spell_item_bloodsail_admiral_hat
Enumerations
enum MassiveSeaforiumCharge { ITEM_MASSIVE_SEAFORIUM_CHARGE = 39213 }
enum TitaniumSealOfDalaran {
TITANIUM_SEAL_OF_DALARAN_BROADCAST_TEXT_ID_FLIP = 32638 ,
TITANIUM_SEAL_OF_DALARAN_BROADCAST_TEXT_ID_HEADS_UP = 32663 ,
TITANIUM_SEAL_OF_DALARAN_BROADCAST_TEXT_ID_FACE_DOWN = 32664
}
enum AmplifyDish {
SPELL_AMPLIFY_30S = 13180 ,
SPELL_AMPLIFY_10S = 67799 ,
SPELL_MENTAL_BATTLE = 67810 ,
SPELL_AMPLIFY_CHARM_30S = 13181 ,
SPELL_AMPLIFY_CHARM_10S = 26740
}
enum RunescrollOfFortitude { SPELL_FORTITUDE = 72590 }
enum BrannsCommunicator {
NPC_BRANN_BRONZEBEARD = 29579 ,
SPELL_CONTACT_BRANN = 55038
}
enum MountModSpells {
SPELL_CARROT_ON_A_STICK_EFFECT = 48402 ,
SPELL_RIDING_CROP_EFFECT = 48383 ,
SPELL_MITHRIL_SPURS_EFFECT = 59916 ,
SPELL_MITHRIL_SPURS = 7215 ,
SPELL_MOUNT_SPEED_CARROT = 48777 ,
SPELL_MOUNT_SPEED_RIDING = 48776
}
enum eChicken { SPELL_ROCKET_CHICKEN_EMOTE = 45255 }
enum Feast {
SPELL_GREAT_FEAST = 57301 ,
SPELL_FISH_FEAST = 57426 ,
SPELL_SMALL_FEAST = 58474 ,
SPELL_GIGANTIC_FEAST = 58465 ,
GREAT_FEAST_BROADCAST_TEXT_ID_PREPARE = 31843 ,
FISH_FEAST_BROADCAST_TEXT_ID_PREPARE = 31844 ,
SMALL_FEAST_BROADCAST_TEXT_ID_PREPARE = 31845 ,
GIGANTIC_FEAST_BROADCAST_TEXT_ID_PREPARE = 31846
}
enum GnomishShrinkRay {
SPELL_GNOMISH_SHRINK_RAY_SELF = 13004 ,
SPELL_GNOMISH_SHRINK_RAY_TARGET = 13003
}
enum GoblinWeatherMachiene {
SPELL_PERSONALIZED_WEATHER_RAIN = 46736 ,
SPELL_PERSONALIZED_WEATHER_SNOW = 46738 ,
SPELL_PERSONALIZED_WEATHER_SUN = 46739 ,
SPELL_PERSONALIZED_WEATHER_CLOUDS = 46740
}
enum oracleAblutions {
SPELL_ABLUTION_RUNIC = 59812 ,
SPELL_ABLUTION_MANA = 59813 ,
SPELL_ABLUTION_RAGE = 59814 ,
SPELL_ABLUTION_ENERGY = 59815
}
enum eDreanicPaleAle { SPELL_PINK_ELEKK = 49908 }
enum eMoleMachine { SPELL_MOLE_MACHINE_PORT_TO_GRIM_GUZZLER = 47523 }
enum HealingTrance {
SPELL_HEALING_DISCOUNT = 37705 ,
SPELL_SOUL_PRESERVER = 60510 ,
SPELL_PRIEST_EYE_OF_GRUUL_HEALING_TRANCE = 37706 ,
SPELL_DRUID_EYE_OF_GRUUL_HEALING_TRANCE = 37721 ,
SPELL_SHAMAN_EYE_OF_GRUUL_HEALING_TRANCE = 37722 ,
SPELL_PALADIN_EYE_OF_GRUUL_HEALING_TRANCE = 37723 ,
SPELL_DRUID_SOUL_PRESERVER_HEALING_TRANCE = 60512 ,
SPELL_PALADIN_SOUL_PRESERVER_HEALING_TRANCE = 60513 ,
SPELL_PRIEST_SOUL_PRESERVER_HEALING_TRANCE = 60514 ,
SPELL_SHAMAN_SOUL_PRESERVER_HEALING_TRANCE = 60515
}
enum eArgentKnight { SPELL_SUMMON_ARGENT_KNIGHT_ALLIANCE = 54296 }
enum InstantStatue {
CREATURE_INSTANT_STATUE_PEDESTAL = 40246 ,
SPELL_INSTANT_STATUE = 75731
}
enum AegisOfPreservation { SPELL_AEGIS_HEAL = 23781 }
enum BrittleArmor { SPELL_BRITTLE_ARMOR = 24575 }
enum BlessingOfAncientKings { SPELL_PROTECTION_OF_ANCIENT_KINGS = 64413 }
enum Defibrillate {
SPELL_GOBLIN_JUMPER_CABLES_FAIL = 8338 ,
SPELL_GOBLIN_JUMPER_CABLES_XL_FAIL = 23055
}
enum DesperateDefense {
SPELL_DESPERATE_RAGE = 33898 ,
SPELL_SERVERSIDE_DESPERAT_DEFENSE = 33897
}
enum DeviateFishSpells {
SPELL_SLEEPY = 8064 ,
SPELL_INVIGORATE = 8065 ,
SPELL_SHRINK = 8066 ,
SPELL_PARTY_TIME = 8067 ,
SPELL_HEALTHY_SPIRIT = 8068 ,
SPELL_REJUVENATION = 8070
}
enum FateRuneOfUnsurpassedVigor { SPELL_UNSURPASSED_VIGOR = 25733 }
enum FlaskOfTheNorthSpells {
SPELL_FLASK_OF_THE_NORTH_SP = 67016 ,
SPELL_FLASK_OF_THE_NORTH_AP = 67017 ,
SPELL_FLASK_OF_THE_NORTH_STR = 67018
}
enum GnomishDeathRay { SPELL_GNOMISH_DEATH_RAY_TARGET = 13279 }
enum MakeAWish {
SPELL_MR_PINCHYS_BLESSING = 33053 ,
SPELL_SUMMON_MIGHTY_MR_PINCHY = 33057 ,
SPELL_SUMMON_FURIOUS_MR_PINCHY = 33059 ,
SPELL_TINY_MAGICAL_CRAWDAD = 33062 ,
SPELL_MR_PINCHYS_GIFT = 33064
}
enum MingoFortune {
SPELL_CREATE_FORTUNE_1 = 40804 ,
SPELL_CREATE_FORTUNE_2 = 40805 ,
SPELL_CREATE_FORTUNE_3 = 40806 ,
SPELL_CREATE_FORTUNE_4 = 40807 ,
SPELL_CREATE_FORTUNE_5 = 40808 ,
SPELL_CREATE_FORTUNE_6 = 40809 ,
SPELL_CREATE_FORTUNE_7 = 40908 ,
SPELL_CREATE_FORTUNE_8 = 40910 ,
SPELL_CREATE_FORTUNE_9 = 40911 ,
SPELL_CREATE_FORTUNE_10 = 40912 ,
SPELL_CREATE_FORTUNE_11 = 40913 ,
SPELL_CREATE_FORTUNE_12 = 40914 ,
SPELL_CREATE_FORTUNE_13 = 40915 ,
SPELL_CREATE_FORTUNE_14 = 40916 ,
SPELL_CREATE_FORTUNE_15 = 40918 ,
SPELL_CREATE_FORTUNE_16 = 40919 ,
SPELL_CREATE_FORTUNE_17 = 40920 ,
SPELL_CREATE_FORTUNE_18 = 40921 ,
SPELL_CREATE_FORTUNE_19 = 40922 ,
SPELL_CREATE_FORTUNE_20 = 40923
}
enum MercurialShield { SPELL_MERCURIAL_SHIELD = 26464 }
enum NecroticTouch { SPELL_ITEM_NECROTIC_TOUCH_PROC = 71879 }
enum NetOMaticSpells {
SPELL_NET_O_MATIC_TRIGGERED1 = 16566 ,
SPELL_NET_O_MATIC_TRIGGERED2 = 13119 ,
SPELL_NET_O_MATIC_TRIGGERED3 = 13099
}
enum NoggenfoggerElixirSpells {
SPELL_NOGGENFOGGER_ELIXIR_TRIGGERED1 = 16595 ,
SPELL_NOGGENFOGGER_ELIXIR_TRIGGERED2 = 16593 ,
SPELL_NOGGENFOGGER_ELIXIR_TRIGGERED3 = 16591
}
enum SavoryDeviateDelight {
SPELL_FLIP_OUT_MALE = 8219 ,
SPELL_FLIP_OUT_FEMALE = 8220 ,
SPELL_YAAARRRR_MALE = 8221 ,
SPELL_YAAARRRR_FEMALE = 8222
}
enum ScrollOfRecall {
SPELL_SCROLL_OF_RECALL_I = 48129 ,
SPELL_SCROLL_OF_RECALL_II = 60320 ,
SPELL_SCROLL_OF_RECALL_III = 60321 ,
SPELL_LOST = 60444 ,
SPELL_SCROLL_OF_RECALL_FAIL_ALLIANCE_1 = 60323 ,
SPELL_SCROLL_OF_RECALL_FAIL_HORDE_1 = 60328
}
enum DimensionalRipperArea52 {
SPELL_TRANSPORTER_MALFUNCTION = 36895 ,
SPELL_TRANSFORM_HORDE = 36897 ,
SPELL_TRANSFORM_ALLIANCE = 36899 ,
SPELL_SOUL_SPLIT_EVIL = 36900 ,
SPELL_SOUL_SPLIT_GOOD = 36901
}
enum ShadowsFate { SPELL_SOUL_FEAST = 71203 }
enum ExceptionCreature {
NPC_GLUTTONOUS_ABOMINATION = 37886 ,
NPC_RISEN_ARCHMAGE = 37868 ,
NPC_BLISTERING_ZOMBIE = 37934 ,
NPC_BLAZING_SKELETON = 36791 ,
NPC_SINDRAGOSA = 36853
}
enum Shadowmourne {
SPELL_SHADOWMOURNE_CHAOS_BANE_DAMAGE = 71904 ,
SPELL_SHADOWMOURNE_SOUL_FRAGMENT = 71905 ,
SPELL_SHADOWMOURNE_VISUAL_LOW = 72521 ,
SPELL_SHADOWMOURNE_VISUAL_HIGH = 72523 ,
SPELL_SHADOWMOURNE_CHAOS_BANE_BUFF = 73422 ,
SPELL_BLOOD_PLAGUE = 55078
}
enum SixDemonBagSpells {
SPELL_FROSTBOLT = 11538 ,
SPELL_POLYMORPH = 14621 ,
SPELL_SUMMON_FELHOUND_MINION = 14642 ,
SPELL_FIREBALL = 15662 ,
SPELL_CHAIN_LIGHTNING = 21179 ,
SPELL_ENVELOPING_WINDS = 25189
}
enum UnderbellyElixirSpells {
SPELL_UNDERBELLY_ELIXIR_TRIGGERED1 = 59645 ,
SPELL_UNDERBELLY_ELIXIR_TRIGGERED2 = 59831 ,
SPELL_UNDERBELLY_ELIXIR_TRIGGERED3 = 59843 ,
AREA_UNDERBELLY = 4560
}
enum GenericData {
SPELL_ARCANITE_DRAGONLING = 19804 ,
SPELL_BATTLE_CHICKEN = 13166 ,
SPELL_MECHANICAL_DRAGONLING = 4073 ,
SPELL_MITHRIL_MECHANICAL_DRAGONLING = 12749
}
enum Sinkholes {
NPC_SOUTH_SINKHOLE = 25664 ,
NPC_NORTHEAST_SINKHOLE = 25665 ,
NPC_NORTHWEST_SINKHOLE = 25666
}
enum VanquishedClutchesSpells {
SPELL_CRUSHER = 64982 ,
SPELL_CONSTRICTOR = 64983 ,
SPELL_CORRUPTOR = 64984
}
enum AshbringerSounds {
SOUND_ASHBRINGER_1 = 8906 ,
SOUND_ASHBRINGER_2 = 8907 ,
SOUND_ASHBRINGER_3 = 8908 ,
SOUND_ASHBRINGER_4 = 8920 ,
SOUND_ASHBRINGER_5 = 8921 ,
SOUND_ASHBRINGER_6 = 8922 ,
SOUND_ASHBRINGER_7 = 8923 ,
SOUND_ASHBRINGER_8 = 8924 ,
SOUND_ASHBRINGER_9 = 8925 ,
SOUND_ASHBRINGER_10 = 8926 ,
SOUND_ASHBRINGER_11 = 8927 ,
SOUND_ASHBRINGER_12 = 8928
}
enum MagicEater {
SPELL_WILD_MAGIC = 58891 ,
SPELL_WELL_FED_1 = 57288 ,
SPELL_WELL_FED_2 = 57139 ,
SPELL_WELL_FED_3 = 57111 ,
SPELL_WELL_FED_4 = 57286 ,
SPELL_WELL_FED_5 = 57291
}
enum PurifyHelboarMeat {
SPELL_SUMMON_PURIFIED_HELBOAR_MEAT = 29277 ,
SPELL_SUMMON_TOXIC_HELBOAR_MEAT = 29278
}
enum ReindeerTransformation {
SPELL_FLYING_REINDEER_310 = 44827 ,
SPELL_FLYING_REINDEER_280 = 44825 ,
SPELL_FLYING_REINDEER_60 = 44824 ,
SPELL_REINDEER_100 = 25859 ,
SPELL_REINDEER_60 = 25858
}
enum NighInvulnerability {
SPELL_NIGH_INVULNERABILITY = 30456 ,
SPELL_COMPLETE_VULNERABILITY = 30457
}
enum Poultryzer {
SPELL_POULTRYIZER_SUCCESS_1 = 30501 ,
SPELL_POULTRYIZER_SUCCESS_2 = 30504 ,
SPELL_POULTRYIZER_BACKFIRE = 30506
}
enum SocretharsStone {
SPELL_SOCRETHAR_TO_SEAT = 35743 ,
SPELL_SOCRETHAR_FROM_SEAT = 35744
}
enum DemonBroiledSurprise {
QUEST_SUPER_HOT_STEW = 11379 ,
SPELL_CREATE_DEMON_BROILED_SURPRISE = 43753 ,
NPC_ABYSSAL_FLAMEBRINGER = 19973
}
enum CompleteRaptorCapture { SPELL_RAPTOR_CAPTURE_CREDIT = 42337 }
enum ImpaleLeviroth {
NPC_LEVIROTH = 26452 ,
SPELL_LEVIROTH_SELF_IMPALE = 49882
}
enum BrewfestMountTransformation {
SPELL_MOUNT_RAM_100 = 43900 ,
SPELL_MOUNT_RAM_60 = 43899 ,
SPELL_MOUNT_KODO_100 = 49379 ,
SPELL_MOUNT_KODO_60 = 49378 ,
SPELL_BREWFEST_MOUNT_TRANSFORM = 49357 ,
SPELL_BREWFEST_MOUNT_TRANSFORM_REVERSE = 52845 ,
SPELL_FRESH_DWARVEN_HOPS = 66050
}
enum NitroBoots {
SPELL_NITRO_BOOTS_SUCCESS = 54861 ,
SPELL_NITRO_BOOTS_BACKFIRE = 46014
}
enum TeachLanguage {
SPELL_LEARN_GNOMISH_BINARY = 50242 ,
SPELL_LEARN_GOBLIN_BINARY = 50246
}
enum RocketBoots { SPELL_ROCKET_BOOTS_PROC = 30452 }
enum PygmyOil {
SPELL_PYGMY_OIL_PYGMY_AURA = 53806 ,
SPELL_PYGMY_OIL_SMALLER_AURA = 53805
}
enum ChickenCover {
SPELL_CHICKEN_NET = 51959 ,
SPELL_CAPTURE_CHICKEN_ESCAPE = 51037 ,
QUEST_CHICKEN_PARTY = 12702 ,
QUEST_FLOWN_THE_COOP = 12532
}
enum Refocus { SPELL_CATEGORY_AIMED_MULTI = 85 }
enum GreatmothersSoulcather { SPELL_FORCE_CAST_SUMMON_GNOME_SOUL = 46486 }
enum Eggnog {
SPELL_EGG_NOG_REINDEER = 21936 ,
SPELL_EGG_NOG_SNOWMAN = 21980
}
enum GoblinBomb {
SPELL_SUMMON_GOBLIN_BOMB = 13258 ,
SPELL_MALFUNCTION_EXPLOSION = 13261
}
enum LinkenBoomerang {
SPELL_DISARM = 15752 ,
SPELL_STUN = 15753 ,
CHANCE_TO_HIT = 3
}
enum RecallSpellIds {
SPELL_RECALL_HORDE = 22563 ,
SPELL_RECALL_ALLIANCE = 22564
}
enum MirrensDrinkingHat {
SPELL_LOCH_MODAN_LAGER = 29827 ,
SPELL_STOUTHAMMER_LITE = 29828 ,
SPELL_AERIE_PEAK_PALE_ALE = 29829
}
enum TrollDice { TEXT_WORN_TROLL_DICE = 26152 }
enum VenomhideHatchling { NPC_VENOMHIDE_HATCHLING = 34320 }
enum ScrollOfRetribution { NPC_VIERA_SUNWHISPER = 17226 }
enum EyeofGrillok {
SPELL_EYE_OF_GRILLOK = 38495 ,
NPC_EYE_OF_GRILLOK = 19440
}
enum FelManaPotion {
SPELL_ALCHEMIST_STONE = 17619 ,
SPELL_ALCHEMIST_STONE_ENERGIZE = 21400
}
enum DreksOintment {
NPC_THUNDERLORD_DIRE_WOLF = 20748 ,
SPELL_GOR_DREKS_OINTMENT = 32578
}
enum Skettis { QUEST_FIRES_OVER_SKETTIS = 11008 }
enum BloodsailAdmiralHat { NPC_ADMIRAL_HAT_PARROT = 11236 }
Functions
uint32 WeatherForcast ()
void AddSC_item_spell_scripts ()
Variables
const uint32 crazyAlchemistTable [5]
std::array< uint32, 20 > const CreateFortuneSpells
Enumeration Type Documentation
AegisOfPreservation
enum AegisOfPreservation
Enumerator
SPELL_AEGIS_HEAL
{
    SPELL_AEGIS_HEAL   = 23781
};
AmplifyDish
enum AmplifyDish
Enumerator
SPELL_AMPLIFY_30S
SPELL_AMPLIFY_10S
SPELL_MENTAL_BATTLE
SPELL_AMPLIFY_CHARM_30S
SPELL_AMPLIFY_CHARM_10S
{
    SPELL_AMPLIFY_30S               = 13180,
    SPELL_AMPLIFY_10S               = 67799,
    SPELL_MENTAL_BATTLE             = 67810,
    SPELL_AMPLIFY_CHARM_30S         = 13181,
    SPELL_AMPLIFY_CHARM_10S         = 26740,
};
AshbringerSounds
enum AshbringerSounds
Enumerator
SOUND_ASHBRINGER_1
SOUND_ASHBRINGER_2
SOUND_ASHBRINGER_3
SOUND_ASHBRINGER_4
SOUND_ASHBRINGER_5
SOUND_ASHBRINGER_6
SOUND_ASHBRINGER_7
SOUND_ASHBRINGER_8
SOUND_ASHBRINGER_9
SOUND_ASHBRINGER_10
SOUND_ASHBRINGER_11
SOUND_ASHBRINGER_12
{
    SOUND_ASHBRINGER_1  = 8906,                             // "I was pure once"
    SOUND_ASHBRINGER_2  = 8907,                             // "Fought for righteousness"
    SOUND_ASHBRINGER_3  = 8908,                             // "I was once called Ashbringer"
    SOUND_ASHBRINGER_4  = 8920,                             // "Betrayed by my order"
    SOUND_ASHBRINGER_5  = 8921,                             // "Destroyed by Kel'Thuzad"
    SOUND_ASHBRINGER_6  = 8922,                             // "Made to serve"
    SOUND_ASHBRINGER_7  = 8923,                             // "My son watched me die"
    SOUND_ASHBRINGER_8  = 8924,                             // "Crusades fed his rage"
    SOUND_ASHBRINGER_9  = 8925,                             // "Truth is unknown to him"
    SOUND_ASHBRINGER_10 = 8926,                             // "Scarlet Crusade  is pure no longer"
    SOUND_ASHBRINGER_11 = 8927,                             // "Balnazzar's crusade corrupted my son"
    SOUND_ASHBRINGER_12 = 8928,                             // "Kill them all!"
};
BlessingOfAncientKings
enum BlessingOfAncientKings
Enumerator
SPELL_PROTECTION_OF_ANCIENT_KINGS
{
    SPELL_PROTECTION_OF_ANCIENT_KINGS   = 64413
};
BloodsailAdmiralHat
enum BloodsailAdmiralHat
Enumerator
NPC_ADMIRAL_HAT_PARROT
{
    NPC_ADMIRAL_HAT_PARROT = 11236, // Blood Parrot
};
BrannsCommunicator
enum BrannsCommunicator
Enumerator
NPC_BRANN_BRONZEBEARD
SPELL_CONTACT_BRANN
{
    NPC_BRANN_BRONZEBEARD = 29579,
    SPELL_CONTACT_BRANN   = 55038,
};
BrewfestMountTransformation
enum BrewfestMountTransformation
Enumerator
SPELL_MOUNT_RAM_100
SPELL_MOUNT_RAM_60
SPELL_MOUNT_KODO_100
SPELL_MOUNT_KODO_60
SPELL_BREWFEST_MOUNT_TRANSFORM
SPELL_BREWFEST_MOUNT_TRANSFORM_REVERSE
SPELL_FRESH_DWARVEN_HOPS
{
    SPELL_MOUNT_RAM_100                         = 43900,
    SPELL_MOUNT_RAM_60                          = 43899,
    SPELL_MOUNT_KODO_100                        = 49379,
    SPELL_MOUNT_KODO_60                         = 49378,
    SPELL_BREWFEST_MOUNT_TRANSFORM              = 49357,
    SPELL_BREWFEST_MOUNT_TRANSFORM_REVERSE      = 52845,
    SPELL_FRESH_DWARVEN_HOPS                    = 66050,
};
BrittleArmor
enum BrittleArmor
Enumerator
SPELL_BRITTLE_ARMOR
{
    SPELL_BRITTLE_ARMOR = 24575
};
ChickenCover
enum ChickenCover
Enumerator
SPELL_CHICKEN_NET
SPELL_CAPTURE_CHICKEN_ESCAPE
QUEST_CHICKEN_PARTY
QUEST_FLOWN_THE_COOP
{
    SPELL_CHICKEN_NET               = 51959,
    SPELL_CAPTURE_CHICKEN_ESCAPE    = 51037,
    QUEST_CHICKEN_PARTY             = 12702,
    QUEST_FLOWN_THE_COOP            = 12532,
};
CompleteRaptorCapture
enum CompleteRaptorCapture
Enumerator
SPELL_RAPTOR_CAPTURE_CREDIT
{
    SPELL_RAPTOR_CAPTURE_CREDIT     = 42337,
};
Defibrillate
enum Defibrillate
Enumerator
SPELL_GOBLIN_JUMPER_CABLES_FAIL
SPELL_GOBLIN_JUMPER_CABLES_XL_FAIL
{
    SPELL_GOBLIN_JUMPER_CABLES_FAIL     = 8338,
    SPELL_GOBLIN_JUMPER_CABLES_XL_FAIL  = 23055
};
DemonBroiledSurprise
enum DemonBroiledSurprise
Enumerator
QUEST_SUPER_HOT_STEW
SPELL_CREATE_DEMON_BROILED_SURPRISE
NPC_ABYSSAL_FLAMEBRINGER
{
    QUEST_SUPER_HOT_STEW                    = 11379,
    SPELL_CREATE_DEMON_BROILED_SURPRISE     = 43753,
    NPC_ABYSSAL_FLAMEBRINGER                = 19973,
};
DesperateDefense
enum DesperateDefense
Enumerator
SPELL_DESPERATE_RAGE
SPELL_SERVERSIDE_DESPERAT_DEFENSE
{
    SPELL_DESPERATE_RAGE    = 33898,
    SPELL_SERVERSIDE_DESPERAT_DEFENSE = 33897 // Root and Pacify
};
DeviateFishSpells
enum DeviateFishSpells
Enumerator
SPELL_SLEEPY
SPELL_INVIGORATE
SPELL_SHRINK
SPELL_PARTY_TIME
SPELL_HEALTHY_SPIRIT
SPELL_REJUVENATION
{
    SPELL_SLEEPY            = 8064,
    SPELL_INVIGORATE        = 8065,
    SPELL_SHRINK            = 8066,
    SPELL_PARTY_TIME        = 8067,
    SPELL_HEALTHY_SPIRIT    = 8068,
    SPELL_REJUVENATION      = 8070
};
DimensionalRipperArea52
enum DimensionalRipperArea52
Enumerator
SPELL_TRANSPORTER_MALFUNCTION
SPELL_TRANSFORM_HORDE
SPELL_TRANSFORM_ALLIANCE
SPELL_SOUL_SPLIT_EVIL
SPELL_SOUL_SPLIT_GOOD
{
    SPELL_TRANSPORTER_MALFUNCTION    = 36895,
    SPELL_TRANSFORM_HORDE            = 36897,
    SPELL_TRANSFORM_ALLIANCE         = 36899,
    SPELL_SOUL_SPLIT_EVIL            = 36900,
    SPELL_SOUL_SPLIT_GOOD            = 36901
};
DreksOintment
enum DreksOintment
Enumerator
NPC_THUNDERLORD_DIRE_WOLF
SPELL_GOR_DREKS_OINTMENT
{
    NPC_THUNDERLORD_DIRE_WOLF = 20748,
    SPELL_GOR_DREKS_OINTMENT  = 32578
};
eArgentKnight
enum eArgentKnight
Enumerator
SPELL_SUMMON_ARGENT_KNIGHT_ALLIANCE
{
    SPELL_SUMMON_ARGENT_KNIGHT_ALLIANCE = 54296
};
eChicken
enum eChicken
Enumerator
SPELL_ROCKET_CHICKEN_EMOTE
{
    SPELL_ROCKET_CHICKEN_EMOTE          = 45255,
};
eDreanicPaleAle
enum eDreanicPaleAle
Enumerator
SPELL_PINK_ELEKK
{
    SPELL_PINK_ELEKK            = 49908
};
Eggnog
enum Eggnog
Enumerator
SPELL_EGG_NOG_REINDEER
SPELL_EGG_NOG_SNOWMAN
{
    SPELL_EGG_NOG_REINDEER = 21936,
    SPELL_EGG_NOG_SNOWMAN  = 21980,
};
eMoleMachine
enum eMoleMachine
Enumerator
SPELL_MOLE_MACHINE_PORT_TO_GRIM_GUZZLER
{
    SPELL_MOLE_MACHINE_PORT_TO_GRIM_GUZZLER     = 47523,
};
ExceptionCreature
enum ExceptionCreature
Enumerator
NPC_GLUTTONOUS_ABOMINATION
NPC_RISEN_ARCHMAGE
NPC_BLISTERING_ZOMBIE
NPC_BLAZING_SKELETON
NPC_SINDRAGOSA
{
    NPC_GLUTTONOUS_ABOMINATION = 37886,
    NPC_RISEN_ARCHMAGE         = 37868,
    NPC_BLISTERING_ZOMBIE      = 37934,
    NPC_BLAZING_SKELETON       = 36791,
    NPC_SINDRAGOSA             = 36853
};
EyeofGrillok
enum EyeofGrillok
Enumerator
SPELL_EYE_OF_GRILLOK
NPC_EYE_OF_GRILLOK
{
    SPELL_EYE_OF_GRILLOK = 38495,
    NPC_EYE_OF_GRILLOK   = 19440
};
FateRuneOfUnsurpassedVigor
enum FateRuneOfUnsurpassedVigor
Enumerator
SPELL_UNSURPASSED_VIGOR
{
    SPELL_UNSURPASSED_VIGOR = 25733
};
Feast
enum Feast
Enumerator
SPELL_GREAT_FEAST
SPELL_FISH_FEAST
SPELL_SMALL_FEAST
SPELL_GIGANTIC_FEAST
GREAT_FEAST_BROADCAST_TEXT_ID_PREPARE
FISH_FEAST_BROADCAST_TEXT_ID_PREPARE
SMALL_FEAST_BROADCAST_TEXT_ID_PREPARE
GIGANTIC_FEAST_BROADCAST_TEXT_ID_PREPARE
{
    SPELL_GREAT_FEAST                        = 57301,
    SPELL_FISH_FEAST                         = 57426,
    SPELL_SMALL_FEAST                        = 58474,
    SPELL_GIGANTIC_FEAST                     = 58465,
    GREAT_FEAST_BROADCAST_TEXT_ID_PREPARE    = 31843,
    FISH_FEAST_BROADCAST_TEXT_ID_PREPARE     = 31844,
    SMALL_FEAST_BROADCAST_TEXT_ID_PREPARE    = 31845,
    GIGANTIC_FEAST_BROADCAST_TEXT_ID_PREPARE = 31846
};
FelManaPotion
enum FelManaPotion
Enumerator
SPELL_ALCHEMIST_STONE
SPELL_ALCHEMIST_STONE_ENERGIZE
{
    SPELL_ALCHEMIST_STONE          = 17619,
    SPELL_ALCHEMIST_STONE_ENERGIZE = 21400
};
FlaskOfTheNorthSpells
enum FlaskOfTheNorthSpells
Enumerator
SPELL_FLASK_OF_THE_NORTH_SP
SPELL_FLASK_OF_THE_NORTH_AP
SPELL_FLASK_OF_THE_NORTH_STR
{
    SPELL_FLASK_OF_THE_NORTH_SP = 67016,
    SPELL_FLASK_OF_THE_NORTH_AP = 67017,
    SPELL_FLASK_OF_THE_NORTH_STR = 67018,
};
GenericData
enum GenericData
Enumerator
SPELL_ARCANITE_DRAGONLING
SPELL_BATTLE_CHICKEN
SPELL_MECHANICAL_DRAGONLING
SPELL_MITHRIL_MECHANICAL_DRAGONLING
{
    SPELL_ARCANITE_DRAGONLING           = 19804,
    SPELL_BATTLE_CHICKEN                = 13166,
    SPELL_MECHANICAL_DRAGONLING         = 4073,
    SPELL_MITHRIL_MECHANICAL_DRAGONLING = 12749,
};
GnomishDeathRay
enum GnomishDeathRay
Enumerator
SPELL_GNOMISH_DEATH_RAY_TARGET
{
    SPELL_GNOMISH_DEATH_RAY_TARGET  = 13279,
};
GnomishShrinkRay
enum GnomishShrinkRay
Enumerator
SPELL_GNOMISH_SHRINK_RAY_SELF
SPELL_GNOMISH_SHRINK_RAY_TARGET
{
    SPELL_GNOMISH_SHRINK_RAY_SELF = 13004,
    SPELL_GNOMISH_SHRINK_RAY_TARGET = 13003,
};
GoblinBomb
enum GoblinBomb
Enumerator
SPELL_SUMMON_GOBLIN_BOMB
SPELL_MALFUNCTION_EXPLOSION
{
    SPELL_SUMMON_GOBLIN_BOMB     = 13258,
    SPELL_MALFUNCTION_EXPLOSION  = 13261
};
GoblinWeatherMachiene
enum GoblinWeatherMachiene
Enumerator
SPELL_PERSONALIZED_WEATHER_RAIN
SPELL_PERSONALIZED_WEATHER_SNOW
SPELL_PERSONALIZED_WEATHER_SUN
SPELL_PERSONALIZED_WEATHER_CLOUDS
{
    SPELL_PERSONALIZED_WEATHER_RAIN = 46736,
    SPELL_PERSONALIZED_WEATHER_SNOW = 46738,
    SPELL_PERSONALIZED_WEATHER_SUN  = 46739,
    SPELL_PERSONALIZED_WEATHER_CLOUDS = 46740
};
GreatmothersSoulcather
enum GreatmothersSoulcather
Enumerator
SPELL_FORCE_CAST_SUMMON_GNOME_SOUL
{
    SPELL_FORCE_CAST_SUMMON_GNOME_SOUL = 46486,
};
HealingTrance
enum HealingTrance
Enumerator
SPELL_HEALING_DISCOUNT
SPELL_SOUL_PRESERVER
SPELL_PRIEST_EYE_OF_GRUUL_HEALING_TRANCE
SPELL_DRUID_EYE_OF_GRUUL_HEALING_TRANCE
SPELL_SHAMAN_EYE_OF_GRUUL_HEALING_TRANCE
SPELL_PALADIN_EYE_OF_GRUUL_HEALING_TRANCE
SPELL_DRUID_SOUL_PRESERVER_HEALING_TRANCE
SPELL_PALADIN_SOUL_PRESERVER_HEALING_TRANCE
SPELL_PRIEST_SOUL_PRESERVER_HEALING_TRANCE
SPELL_SHAMAN_SOUL_PRESERVER_HEALING_TRANCE
{
    SPELL_HEALING_DISCOUNT                      = 37705,
    SPELL_SOUL_PRESERVER                        = 60510,
    SPELL_PRIEST_EYE_OF_GRUUL_HEALING_TRANCE    = 37706,
    SPELL_DRUID_EYE_OF_GRUUL_HEALING_TRANCE     = 37721,
    SPELL_SHAMAN_EYE_OF_GRUUL_HEALING_TRANCE    = 37722,
    SPELL_PALADIN_EYE_OF_GRUUL_HEALING_TRANCE   = 37723,
    SPELL_DRUID_SOUL_PRESERVER_HEALING_TRANCE   = 60512,
    SPELL_PALADIN_SOUL_PRESERVER_HEALING_TRANCE = 60513,
    SPELL_PRIEST_SOUL_PRESERVER_HEALING_TRANCE  = 60514,
    SPELL_SHAMAN_SOUL_PRESERVER_HEALING_TRANCE  = 60515,
};
ImpaleLeviroth
enum ImpaleLeviroth
Enumerator
NPC_LEVIROTH
SPELL_LEVIROTH_SELF_IMPALE
{
    NPC_LEVIROTH                = 26452,
    SPELL_LEVIROTH_SELF_IMPALE  = 49882,
};
InstantStatue
enum InstantStatue
Enumerator
CREATURE_INSTANT_STATUE_PEDESTAL
SPELL_INSTANT_STATUE
{
    CREATURE_INSTANT_STATUE_PEDESTAL = 40246,
    SPELL_INSTANT_STATUE = 75731
};
LinkenBoomerang
enum LinkenBoomerang
Enumerator
SPELL_DISARM
SPELL_STUN
CHANCE_TO_HIT
{
    SPELL_DISARM  = 15752,
    SPELL_STUN    = 15753,
    CHANCE_TO_HIT = 3
};
MagicEater
enum MagicEater
Enumerator
SPELL_WILD_MAGIC
SPELL_WELL_FED_1
SPELL_WELL_FED_2
SPELL_WELL_FED_3
SPELL_WELL_FED_4
SPELL_WELL_FED_5
{
    SPELL_WILD_MAGIC                             = 58891,
    SPELL_WELL_FED_1                             = 57288,
    SPELL_WELL_FED_2                             = 57139,
    SPELL_WELL_FED_3                             = 57111,
    SPELL_WELL_FED_4                             = 57286,
    SPELL_WELL_FED_5                             = 57291,
};
MakeAWish
enum MakeAWish
Enumerator
SPELL_MR_PINCHYS_BLESSING
SPELL_SUMMON_MIGHTY_MR_PINCHY
SPELL_SUMMON_FURIOUS_MR_PINCHY
SPELL_TINY_MAGICAL_CRAWDAD
SPELL_MR_PINCHYS_GIFT
{
    SPELL_MR_PINCHYS_BLESSING       = 33053,
    SPELL_SUMMON_MIGHTY_MR_PINCHY   = 33057,
    SPELL_SUMMON_FURIOUS_MR_PINCHY  = 33059,
    SPELL_TINY_MAGICAL_CRAWDAD      = 33062,
    SPELL_MR_PINCHYS_GIFT           = 33064,
};
MassiveSeaforiumCharge
enum MassiveSeaforiumCharge
Enumerator
ITEM_MASSIVE_SEAFORIUM_CHARGE
{
    ITEM_MASSIVE_SEAFORIUM_CHARGE = 39213,
};
MercurialShield
enum MercurialShield
Enumerator
SPELL_MERCURIAL_SHIELD
{
    SPELL_MERCURIAL_SHIELD = 26464
};
MingoFortune
enum MingoFortune
Enumerator
SPELL_CREATE_FORTUNE_1
SPELL_CREATE_FORTUNE_2
SPELL_CREATE_FORTUNE_3
SPELL_CREATE_FORTUNE_4
SPELL_CREATE_FORTUNE_5
SPELL_CREATE_FORTUNE_6
SPELL_CREATE_FORTUNE_7
SPELL_CREATE_FORTUNE_8
SPELL_CREATE_FORTUNE_9
SPELL_CREATE_FORTUNE_10
SPELL_CREATE_FORTUNE_11
SPELL_CREATE_FORTUNE_12
SPELL_CREATE_FORTUNE_13
SPELL_CREATE_FORTUNE_14
SPELL_CREATE_FORTUNE_15
SPELL_CREATE_FORTUNE_16
SPELL_CREATE_FORTUNE_17
SPELL_CREATE_FORTUNE_18
SPELL_CREATE_FORTUNE_19
SPELL_CREATE_FORTUNE_20
{
    SPELL_CREATE_FORTUNE_1       = 40804,
    SPELL_CREATE_FORTUNE_2       = 40805,
    SPELL_CREATE_FORTUNE_3       = 40806,
    SPELL_CREATE_FORTUNE_4       = 40807,
    SPELL_CREATE_FORTUNE_5       = 40808,
    SPELL_CREATE_FORTUNE_6       = 40809,
    SPELL_CREATE_FORTUNE_7       = 40908,
    SPELL_CREATE_FORTUNE_8       = 40910,
    SPELL_CREATE_FORTUNE_9       = 40911,
    SPELL_CREATE_FORTUNE_10      = 40912,
    SPELL_CREATE_FORTUNE_11      = 40913,
    SPELL_CREATE_FORTUNE_12      = 40914,
    SPELL_CREATE_FORTUNE_13      = 40915,
    SPELL_CREATE_FORTUNE_14      = 40916,
    SPELL_CREATE_FORTUNE_15      = 40918,
    SPELL_CREATE_FORTUNE_16      = 40919,
    SPELL_CREATE_FORTUNE_17      = 40920,
    SPELL_CREATE_FORTUNE_18      = 40921,
    SPELL_CREATE_FORTUNE_19      = 40922,
    SPELL_CREATE_FORTUNE_20      = 40923
};
MirrensDrinkingHat
enum MirrensDrinkingHat
Enumerator
SPELL_LOCH_MODAN_LAGER
SPELL_STOUTHAMMER_LITE
SPELL_AERIE_PEAK_PALE_ALE
{
    SPELL_LOCH_MODAN_LAGER      = 29827,
    SPELL_STOUTHAMMER_LITE      = 29828,
    SPELL_AERIE_PEAK_PALE_ALE   = 29829
};
MountModSpells
enum MountModSpells
Enumerator
SPELL_CARROT_ON_A_STICK_EFFECT
SPELL_RIDING_CROP_EFFECT
SPELL_MITHRIL_SPURS_EFFECT
SPELL_MITHRIL_SPURS
SPELL_MOUNT_SPEED_CARROT
SPELL_MOUNT_SPEED_RIDING
{
    SPELL_CARROT_ON_A_STICK_EFFECT = 48402,
    SPELL_RIDING_CROP_EFFECT = 48383,
    SPELL_MITHRIL_SPURS_EFFECT = 59916,
    SPELL_MITHRIL_SPURS = 7215,
    SPELL_MOUNT_SPEED_CARROT = 48777,
    SPELL_MOUNT_SPEED_RIDING = 48776
};
NecroticTouch
enum NecroticTouch
Enumerator
SPELL_ITEM_NECROTIC_TOUCH_PROC
{
    SPELL_ITEM_NECROTIC_TOUCH_PROC  = 71879
};
NetOMaticSpells
enum NetOMaticSpells
Enumerator
SPELL_NET_O_MATIC_TRIGGERED1
SPELL_NET_O_MATIC_TRIGGERED2
SPELL_NET_O_MATIC_TRIGGERED3
{
    SPELL_NET_O_MATIC_TRIGGERED1 = 16566,
    SPELL_NET_O_MATIC_TRIGGERED2 = 13119,
    SPELL_NET_O_MATIC_TRIGGERED3 = 13099,
};
NighInvulnerability
enum NighInvulnerability
Enumerator
SPELL_NIGH_INVULNERABILITY
SPELL_COMPLETE_VULNERABILITY
{
    SPELL_NIGH_INVULNERABILITY                  = 30456,
    SPELL_COMPLETE_VULNERABILITY                = 30457,
};
NitroBoots
enum NitroBoots
Enumerator
SPELL_NITRO_BOOTS_SUCCESS
SPELL_NITRO_BOOTS_BACKFIRE
{
    SPELL_NITRO_BOOTS_SUCCESS       = 54861,
    SPELL_NITRO_BOOTS_BACKFIRE      = 46014,
};
NoggenfoggerElixirSpells
enum NoggenfoggerElixirSpells
Enumerator
SPELL_NOGGENFOGGER_ELIXIR_TRIGGERED1
SPELL_NOGGENFOGGER_ELIXIR_TRIGGERED2
SPELL_NOGGENFOGGER_ELIXIR_TRIGGERED3
{
    SPELL_NOGGENFOGGER_ELIXIR_TRIGGERED1 = 16595,
    SPELL_NOGGENFOGGER_ELIXIR_TRIGGERED2 = 16593,
    SPELL_NOGGENFOGGER_ELIXIR_TRIGGERED3 = 16591,
};
oracleAblutions
enum oracleAblutions
Enumerator
SPELL_ABLUTION_RUNIC
SPELL_ABLUTION_MANA
SPELL_ABLUTION_RAGE
SPELL_ABLUTION_ENERGY
{
    SPELL_ABLUTION_RUNIC            = 59812,
    SPELL_ABLUTION_MANA             = 59813,
    SPELL_ABLUTION_RAGE             = 59814,
    SPELL_ABLUTION_ENERGY           = 59815,
};
Poultryzer
enum Poultryzer
Enumerator
SPELL_POULTRYIZER_SUCCESS_1
SPELL_POULTRYIZER_SUCCESS_2
SPELL_POULTRYIZER_BACKFIRE
{
    SPELL_POULTRYIZER_SUCCESS_1  = 30501,
    SPELL_POULTRYIZER_SUCCESS_2  = 30504, // malfunction
    SPELL_POULTRYIZER_BACKFIRE   = 30506, // Not removed on damage
};
PurifyHelboarMeat
enum PurifyHelboarMeat
Enumerator
SPELL_SUMMON_PURIFIED_HELBOAR_MEAT
SPELL_SUMMON_TOXIC_HELBOAR_MEAT
{
    SPELL_SUMMON_PURIFIED_HELBOAR_MEAT      = 29277,
    SPELL_SUMMON_TOXIC_HELBOAR_MEAT         = 29278,
};
PygmyOil
enum PygmyOil
Enumerator
SPELL_PYGMY_OIL_PYGMY_AURA
SPELL_PYGMY_OIL_SMALLER_AURA
{
    SPELL_PYGMY_OIL_PYGMY_AURA      = 53806,
    SPELL_PYGMY_OIL_SMALLER_AURA    = 53805,
};
RecallSpellIds
enum RecallSpellIds
Enumerator
SPELL_RECALL_HORDE
SPELL_RECALL_ALLIANCE
{
    SPELL_RECALL_HORDE = 22563,
    SPELL_RECALL_ALLIANCE = 22564
};
Refocus
enum Refocus
Enumerator
SPELL_CATEGORY_AIMED_MULTI
{
    SPELL_CATEGORY_AIMED_MULTI = 85
};
ReindeerTransformation
enum ReindeerTransformation
Enumerator
SPELL_FLYING_REINDEER_310
SPELL_FLYING_REINDEER_280
SPELL_FLYING_REINDEER_60
SPELL_REINDEER_100
SPELL_REINDEER_60
{
    SPELL_FLYING_REINDEER_310                   = 44827,
    SPELL_FLYING_REINDEER_280                   = 44825,
    SPELL_FLYING_REINDEER_60                    = 44824,
    SPELL_REINDEER_100                          = 25859,
    SPELL_REINDEER_60                           = 25858,
};
RocketBoots
enum RocketBoots
Enumerator
SPELL_ROCKET_BOOTS_PROC
{
    SPELL_ROCKET_BOOTS_PROC      = 30452,
};
RunescrollOfFortitude
enum RunescrollOfFortitude
Enumerator
SPELL_FORTITUDE
{
    SPELL_FORTITUDE = 72590,
};
SavoryDeviateDelight
enum SavoryDeviateDelight
Enumerator
SPELL_FLIP_OUT_MALE
SPELL_FLIP_OUT_FEMALE
SPELL_YAAARRRR_MALE
SPELL_YAAARRRR_FEMALE
{
    SPELL_FLIP_OUT_MALE     = 8219,
    SPELL_FLIP_OUT_FEMALE   = 8220,
    SPELL_YAAARRRR_MALE     = 8221,
    SPELL_YAAARRRR_FEMALE   = 8222,
};
ScrollOfRecall
enum ScrollOfRecall
Enumerator
SPELL_SCROLL_OF_RECALL_I
SPELL_SCROLL_OF_RECALL_II
SPELL_SCROLL_OF_RECALL_III
SPELL_LOST
SPELL_SCROLL_OF_RECALL_FAIL_ALLIANCE_1
SPELL_SCROLL_OF_RECALL_FAIL_HORDE_1
{
    SPELL_SCROLL_OF_RECALL_I                = 48129,
    SPELL_SCROLL_OF_RECALL_II               = 60320,
    SPELL_SCROLL_OF_RECALL_III              = 60321,
    SPELL_LOST                              = 60444,
    SPELL_SCROLL_OF_RECALL_FAIL_ALLIANCE_1  = 60323,
    SPELL_SCROLL_OF_RECALL_FAIL_HORDE_1     = 60328,
};
ScrollOfRetribution
enum ScrollOfRetribution
Enumerator
NPC_VIERA_SUNWHISPER
{
    NPC_VIERA_SUNWHISPER    = 17226
};
Shadowmourne
enum Shadowmourne
Enumerator
SPELL_SHADOWMOURNE_CHAOS_BANE_DAMAGE
SPELL_SHADOWMOURNE_SOUL_FRAGMENT
SPELL_SHADOWMOURNE_VISUAL_LOW
SPELL_SHADOWMOURNE_VISUAL_HIGH
SPELL_SHADOWMOURNE_CHAOS_BANE_BUFF
SPELL_BLOOD_PLAGUE
{
    SPELL_SHADOWMOURNE_CHAOS_BANE_DAMAGE    = 71904,
    SPELL_SHADOWMOURNE_SOUL_FRAGMENT        = 71905,
    SPELL_SHADOWMOURNE_VISUAL_LOW           = 72521,
    SPELL_SHADOWMOURNE_VISUAL_HIGH          = 72523,
    SPELL_SHADOWMOURNE_CHAOS_BANE_BUFF      = 73422,
    SPELL_BLOOD_PLAGUE                      = 55078,
};
ShadowsFate
enum ShadowsFate
Enumerator
SPELL_SOUL_FEAST
{
    SPELL_SOUL_FEAST        = 71203,
};
Sinkholes
enum Sinkholes
Enumerator
NPC_SOUTH_SINKHOLE
NPC_NORTHEAST_SINKHOLE
NPC_NORTHWEST_SINKHOLE
{
    NPC_SOUTH_SINKHOLE      = 25664,
    NPC_NORTHEAST_SINKHOLE  = 25665,
    NPC_NORTHWEST_SINKHOLE  = 25666,
};
SixDemonBagSpells
enum SixDemonBagSpells
Enumerator
SPELL_FROSTBOLT
SPELL_POLYMORPH
SPELL_SUMMON_FELHOUND_MINION
SPELL_FIREBALL
SPELL_CHAIN_LIGHTNING
SPELL_ENVELOPING_WINDS
{
    SPELL_FROSTBOLT                 = 11538,
    SPELL_POLYMORPH                 = 14621,
    SPELL_SUMMON_FELHOUND_MINION    = 14642,
    SPELL_FIREBALL                  = 15662,
    SPELL_CHAIN_LIGHTNING           = 21179,
    SPELL_ENVELOPING_WINDS          = 25189,
};
Skettis
enum Skettis
Enumerator
QUEST_FIRES_OVER_SKETTIS
{
    QUEST_FIRES_OVER_SKETTIS = 11008
};
SocretharsStone
enum SocretharsStone
Enumerator
SPELL_SOCRETHAR_TO_SEAT
SPELL_SOCRETHAR_FROM_SEAT
{
    SPELL_SOCRETHAR_TO_SEAT     = 35743,
    SPELL_SOCRETHAR_FROM_SEAT   = 35744,
};
TeachLanguage
enum TeachLanguage
Enumerator
SPELL_LEARN_GNOMISH_BINARY
SPELL_LEARN_GOBLIN_BINARY
{
    SPELL_LEARN_GNOMISH_BINARY      = 50242,
    SPELL_LEARN_GOBLIN_BINARY       = 50246,
};
TitaniumSealOfDalaran
enum TitaniumSealOfDalaran
Enumerator
TITANIUM_SEAL_OF_DALARAN_BROADCAST_TEXT_ID_FLIP
TITANIUM_SEAL_OF_DALARAN_BROADCAST_TEXT_ID_HEADS_UP
TITANIUM_SEAL_OF_DALARAN_BROADCAST_TEXT_ID_FACE_DOWN
{
    TITANIUM_SEAL_OF_DALARAN_BROADCAST_TEXT_ID_FLIP      = 32638,
    TITANIUM_SEAL_OF_DALARAN_BROADCAST_TEXT_ID_HEADS_UP  = 32663,
    TITANIUM_SEAL_OF_DALARAN_BROADCAST_TEXT_ID_FACE_DOWN = 32664
};
TrollDice
enum TrollDice
Enumerator
TEXT_WORN_TROLL_DICE
{
    TEXT_WORN_TROLL_DICE = 26152
};
UnderbellyElixirSpells
enum UnderbellyElixirSpells
Enumerator
SPELL_UNDERBELLY_ELIXIR_TRIGGERED1
SPELL_UNDERBELLY_ELIXIR_TRIGGERED2
SPELL_UNDERBELLY_ELIXIR_TRIGGERED3
AREA_UNDERBELLY
{
    SPELL_UNDERBELLY_ELIXIR_TRIGGERED1  = 59645,
    SPELL_UNDERBELLY_ELIXIR_TRIGGERED2  = 59831,
    SPELL_UNDERBELLY_ELIXIR_TRIGGERED3  = 59843,
    AREA_UNDERBELLY                     = 4560,
};
VanquishedClutchesSpells
enum VanquishedClutchesSpells
Enumerator
SPELL_CRUSHER
SPELL_CONSTRICTOR
SPELL_CORRUPTOR
{
    SPELL_CRUSHER       = 64982,
    SPELL_CONSTRICTOR   = 64983,
    SPELL_CORRUPTOR     = 64984,
};
VenomhideHatchling
enum VenomhideHatchling
Enumerator
NPC_VENOMHIDE_HATCHLING
{
    NPC_VENOMHIDE_HATCHLING = 34320
};
Function Documentation
AddSC_item_spell_scripts()
void AddSC_item_spell_scripts ()
{
    RegisterSpellScript(spell_item_massive_seaforium_charge);
    RegisterSpellScript(spell_item_titanium_seal_of_dalaran);
    RegisterSpellScript(spell_item_mind_amplify_dish);
    RegisterSpellScript(spell_item_runescroll_of_fortitude);
    RegisterSpellScript(spell_item_branns_communicator);
    RegisterSpellScript(spell_item_goblin_gumbo_kettle);
    RegisterSpellScript(spell_item_with_mount_speed);
    RegisterSpellScript(spell_item_magic_dust);
    RegisterSpellScript(spell_item_toy_train_set);
    RegisterSpellScript(spell_item_rocket_chicken);
    RegisterSpellScript(spell_item_sleepy_willy);
    RegisterSpellScript(spell_item_lil_phylactery);
    RegisterSpellScript(spell_item_shifting_naaru_silver);
    RegisterSpellScript(spell_item_toxic_wasteling);
    RegisterSpellScript(spell_item_lil_xt);
    RegisterSpellScript(spell_item_essence_of_life);
    RegisterSpellScript(spell_item_crazy_alchemists_potion);
    RegisterSpellScript(spell_item_skull_of_impeding_doom);
    RegisterSpellScript(spell_item_feast);
    RegisterSpellScript(spell_item_gnomish_universal_remote);
    RegisterSpellScript(spell_item_powerful_anti_venom);
    RegisterSpellScript(spell_item_strong_anti_venom);
    RegisterSpellScript(spell_item_anti_venom);
    RegisterSpellScript(spell_item_gnomish_shrink_ray);
    RegisterSpellScript(spell_item_goblin_weather_machine);
    RegisterSpellScript(spell_item_goblin_weather_machine_aura);
    RegisterSpellScript(spell_item_light_lamp);
    RegisterSpellScript(spell_item_fetch_ball);
    RegisterSpellScript(spell_item_oracle_ablutions);
    RegisterSpellScript(spell_item_trauma);
    RegisterSpellScript(spell_item_blade_ward_enchant);
    RegisterSpellScript(spell_item_blood_draining_enchant);
    RegisterSpellScript(spell_item_dragon_kite_summon_lightning_bunny);
    RegisterSpellScript(spell_item_enchanted_broom_periodic);
    RegisterSpellScript(spell_item_summon_or_dismiss);
    RegisterSpellScript(spell_item_draenic_pale_ale);
    RegisterSpellAndAuraScriptPair(spell_item_direbrew_remote, spell_item_direbrew_remote_aura);
    RegisterSpellScript(spell_item_healing_trance);
    RegisterSpellScript(spell_item_summon_argent_knight);
    RegisterSpellScript(spell_item_instant_statue);
    // 23074 Arcanite Dragonling
    RegisterSpellScriptWithArgs(spell_item_trigger_spell, "spell_item_arcanite_dragonling", SPELL_ARCANITE_DRAGONLING);
    // 23133 Gnomish Battle Chicken
    RegisterSpellScriptWithArgs(spell_item_trigger_spell, "spell_item_gnomish_battle_chicken", SPELL_BATTLE_CHICKEN);
    // 23076 Mechanical Dragonling
    RegisterSpellScriptWithArgs(spell_item_trigger_spell, "spell_item_mechanical_dragonling", SPELL_MECHANICAL_DRAGONLING);
    // 23075 Mithril Mechanical Dragonling
    RegisterSpellScriptWithArgs(spell_item_trigger_spell, "spell_item_mithril_mechanical_dragonling", SPELL_MITHRIL_MECHANICAL_DRAGONLING);
    RegisterSpellScript(spell_item_aegis_of_preservation);
    RegisterSpellScript(spell_item_arcane_shroud);
    RegisterSpellScript(spell_item_brittle_armor);
    RegisterSpellScript(spell_item_blessing_of_ancient_kings);
    RegisterSpellScript(spell_item_valanyr_hammer_of_ancient_kings);
    RegisterSpellScriptWithArgs(spell_item_defibrillate, "spell_item_goblin_jumper_cables", 67, SPELL_GOBLIN_JUMPER_CABLES_FAIL);
    RegisterSpellScriptWithArgs(spell_item_defibrillate, "spell_item_goblin_jumper_cables_xl", 50, SPELL_GOBLIN_JUMPER_CABLES_XL_FAIL);
    RegisterSpellScriptWithArgs(spell_item_defibrillate, "spell_item_gnomish_army_knife", 33);
    RegisterSpellScript(spell_item_desperate_defense);
    RegisterSpellScript(spell_item_deviate_fish);
    RegisterSpellScript(spell_item_party_time);
    RegisterSpellScript(spell_item_echoes_of_light);
    RegisterSpellScript(spell_item_fate_rune_of_unsurpassed_vigor);
    RegisterSpellScript(spell_item_flask_of_the_north);
    RegisterSpellScript(spell_item_gnomish_death_ray);
    RegisterSpellScript(spell_item_make_a_wish);
    RegisterSpellScript(spell_item_mercurial_shield);
    RegisterSpellScript(spell_item_mingos_fortune_generator);
    RegisterSpellScript(spell_item_necrotic_touch);
    RegisterSpellScript(spell_item_net_o_matic);
    RegisterSpellScript(spell_item_noggenfogger_elixir);
    RegisterSpellScript(spell_item_piccolo_of_the_flaming_fire);
    RegisterSpellScript(spell_item_savory_deviate_delight);
    RegisterSpellScript(spell_item_scroll_of_recall);
    RegisterSpellScript(spell_item_dimensional_ripper_area52);
    RegisterSpellScript(spell_item_unsated_craving);
    RegisterSpellScript(spell_item_shadows_fate);
    RegisterSpellScript(spell_item_shadowmourne);
    RegisterSpellScript(spell_item_shadowmourne_soul_fragment);
    RegisterSpellScript(spell_item_six_demon_bag);
    RegisterSpellScript(spell_item_the_eye_of_diminution);
    RegisterSpellScript(spell_item_underbelly_elixir);
    RegisterSpellScript(spell_item_book_of_glyph_mastery);
    RegisterSpellScript(spell_item_map_of_the_geyser_fields);
    RegisterSpellScript(spell_item_vanquished_clutches);
    RegisterSpellScript(spell_item_ashbringer);
    RegisterSpellScript(spell_magic_eater_food);
    RegisterSpellScript(spell_item_refocus);
    RegisterSpellScript(spell_item_shimmering_vessel);
    RegisterSpellScript(spell_item_purify_helboar_meat);
    RegisterSpellScript(spell_item_reindeer_transformation);
    RegisterSpellScript(spell_item_nigh_invulnerability);
    RegisterSpellScript(spell_item_poultryizer);
    RegisterSpellScript(spell_item_socrethars_stone);
    RegisterSpellScript(spell_item_demon_broiled_surprise);
    RegisterSpellScript(spell_item_complete_raptor_capture);
    RegisterSpellScript(spell_item_impale_leviroth);
    RegisterSpellScript(spell_item_brewfest_mount_transformation);
    RegisterSpellScript(spell_item_nitro_boots);
    RegisterSpellScript(spell_item_teach_language);
    RegisterSpellScript(spell_item_rocket_boots);
    RegisterSpellScript(spell_item_healing_injector);
    RegisterSpellScript(spell_item_mana_injector);
    RegisterSpellScript(spell_item_pygmy_oil);
    RegisterSpellScript(spell_item_unusual_compass);
    RegisterSpellScript(spell_item_chicken_cover);
    RegisterSpellScript(spell_item_muisek_vessel);
    RegisterSpellScript(spell_item_greatmothers_soulcatcher);
    RegisterSpellScript(spell_item_eggnog);
    RegisterSpellScript(spell_item_goblin_bomb);
    RegisterSpellScript(spell_item_linken_boomerang);
    RegisterSpellScript(spell_item_recall);
    RegisterSpellScript(spell_item_wraith_scythe_drain_life);
    RegisterSpellScript(spell_item_mirrens_drinking_hat);
    RegisterSpellScript(spell_item_snowman);
    RegisterSpellScript(spell_item_freeze_rookery_egg);
    RegisterSpellScript(spell_item_green_whelp_armor);
    RegisterSpellScript(spell_item_elixir_of_shadows);
    RegisterSpellScript(spell_item_worn_troll_dice);
    RegisterSpellScript(spell_item_venomhide_feed);
    RegisterSpellScript(spell_item_scroll_of_retribution);
    RegisterSpellAndAuraScriptPair(spell_item_eye_of_grillok, spell_item_eye_of_grillok_aura);
    RegisterSpellScript(spell_item_fel_mana_potion);
    RegisterSpellScript(spell_item_gor_dreks_ointment);
    RegisterSpellScript(spell_item_skyguard_blasting_charges);
    RegisterSpellScript(spell_item_luffa);
    RegisterSpellScript(spell_item_spell_reflectors);
    RegisterSpellScript(spell_item_multiphase_goggles);
    RegisterSpellScript(spell_item_bloodsail_admiral_hat);
    RegisterSpellScript(spell_item_brewfest_hops);
}
References RegisterSpellAndAuraScriptPair, RegisterSpellScript, RegisterSpellScriptWithArgs, SPELL_ARCANITE_DRAGONLING, SPELL_BATTLE_CHICKEN, SPELL_GOBLIN_JUMPER_CABLES_FAIL, SPELL_GOBLIN_JUMPER_CABLES_XL_FAIL, SPELL_MECHANICAL_DRAGONLING, and SPELL_MITHRIL_MECHANICAL_DRAGONLING.
Referenced by AddSpellsScripts().
WeatherForcast()
uint32 WeatherForcast ()
{
    if (!SpellScript::ValidateSpellInfo({
        SPELL_PERSONALIZED_WEATHER_RAIN,
        SPELL_PERSONALIZED_WEATHER_SNOW,
        SPELL_PERSONALIZED_WEATHER_SUN,
        SPELL_PERSONALIZED_WEATHER_CLOUDS
        }))
        return 0;
    uint32 spellId = 0;
    switch (urand(0, 3))
    {
        case 0:
            spellId = SPELL_PERSONALIZED_WEATHER_RAIN;
            break;
        case 1:
            spellId = SPELL_PERSONALIZED_WEATHER_SNOW;
            break;
        case 2:
            spellId = SPELL_PERSONALIZED_WEATHER_SUN;
            break;
        case 3:
            spellId = SPELL_PERSONALIZED_WEATHER_CLOUDS;
            break;
    }
    return spellId;
}
References SPELL_PERSONALIZED_WEATHER_CLOUDS, SPELL_PERSONALIZED_WEATHER_RAIN, SPELL_PERSONALIZED_WEATHER_SNOW, SPELL_PERSONALIZED_WEATHER_SUN, urand(), and _SpellScript::ValidateSpellInfo().
Referenced by spell_item_goblin_weather_machine::HandleScriptEffect(), and spell_item_goblin_weather_machine_aura::OnRemove().
Variable Documentation
crazyAlchemistTable
const uint32 crazyAlchemistTable[5]
Initial value:
=
{
    53909,
    53908,
    53762,
    43185,
    43186
}
{
    53909, // Wild Magic
    53908, // Potion of Speed
    53762, // Indestructible Potion
    43185, // Runic Healing Potion
    43186  // Runic Mana Potion
};
Referenced by spell_item_crazy_alchemists_potion::HandleHeal().
CreateFortuneSpells
std::array<uint32, 20> const CreateFortuneSpells
Initial value:
=
{
    SPELL_CREATE_FORTUNE_1, SPELL_CREATE_FORTUNE_2, SPELL_CREATE_FORTUNE_3, SPELL_CREATE_FORTUNE_4, SPELL_CREATE_FORTUNE_5,
    SPELL_CREATE_FORTUNE_6, SPELL_CREATE_FORTUNE_7, SPELL_CREATE_FORTUNE_8, SPELL_CREATE_FORTUNE_9, SPELL_CREATE_FORTUNE_10,
    SPELL_CREATE_FORTUNE_11, SPELL_CREATE_FORTUNE_12, SPELL_CREATE_FORTUNE_13, SPELL_CREATE_FORTUNE_14, SPELL_CREATE_FORTUNE_15,
    SPELL_CREATE_FORTUNE_16, SPELL_CREATE_FORTUNE_17, SPELL_CREATE_FORTUNE_18, SPELL_CREATE_FORTUNE_19, SPELL_CREATE_FORTUNE_20
}
{
    SPELL_CREATE_FORTUNE_1, SPELL_CREATE_FORTUNE_2, SPELL_CREATE_FORTUNE_3, SPELL_CREATE_FORTUNE_4, SPELL_CREATE_FORTUNE_5,
    SPELL_CREATE_FORTUNE_6, SPELL_CREATE_FORTUNE_7, SPELL_CREATE_FORTUNE_8, SPELL_CREATE_FORTUNE_9, SPELL_CREATE_FORTUNE_10,
    SPELL_CREATE_FORTUNE_11, SPELL_CREATE_FORTUNE_12, SPELL_CREATE_FORTUNE_13, SPELL_CREATE_FORTUNE_14, SPELL_CREATE_FORTUNE_15,
    SPELL_CREATE_FORTUNE_16, SPELL_CREATE_FORTUNE_17, SPELL_CREATE_FORTUNE_18, SPELL_CREATE_FORTUNE_19, SPELL_CREATE_FORTUNE_20
};
Referenced by spell_item_mingos_fortune_generator::HandleDummy(), and spell_item_mingos_fortune_generator::Validate().