AzerothCore Doxygen
MapPreloadRequest Class Reference
Public Member Functions
MapPreloadRequest (uint32 mapId, MapUpdater &updater)
void call () override
Public Member Functions inherited from UpdateRequest
UpdateRequest ()=default
virtual ~UpdateRequest ()=default
Private Attributes
uint32 _mapId
MapUpdater & _updater
Detailed Description
Constructor & Destructor Documentation
MapPreloadRequest()
MapPreloadRequest::MapPreloadRequest (uint32 mapId, MapUpdater & updater) inline
        : _mapId(mapId), _updater(updater)
    {
    }
Member Function Documentation
call()
void MapPreloadRequest::call () inline override virtual
Implements UpdateRequest.
    {
        Map* map = sMapMgr->CreateBaseMap(_mapId);
        LOG_INFO("server.loading", ">> Loading All Grids For Map {} ({})", map->GetId(), map->GetMapName());
        map->LoadAllGrids();
        _updater.update_finished();
    }
References _mapId, _updater, Map::GetId(), Map::GetMapName(), Map::LoadAllGrids(), LOG_INFO, sMapMgr, and MapUpdater::update_finished().
Member Data Documentation
_mapId
uint32 MapPreloadRequest::_mapId private
Referenced by call().
_updater
MapUpdater& MapPreloadRequest::_updater private
Referenced by call().
The documentation for this class was generated from the following file:
azerothcore-wotlk/src/server/game/Maps/MapUpdater.cpp