AzerothCore Doxygen
LuaUnit Namespace Reference
Functions
int SetImmuneTo (lua_State *L, Unit *unit)
int HandleStatModifier (lua_State *L, Unit *unit)
int Attack (lua_State *L, Unit *unit)
int AttackStop (lua_State *L, Unit *unit)
int IsStandState (lua_State *L, Unit *unit)
int IsMounted (lua_State *L, Unit *unit)
int IsRooted (lua_State *L, Unit *unit)
int IsFullHealth (lua_State *L, Unit *unit)
int IsInAccessiblePlaceFor (lua_State *L, Unit *unit)
int IsAuctioneer (lua_State *L, Unit *unit)
int IsGuildMaster (lua_State *L, Unit *unit)
int IsInnkeeper (lua_State *L, Unit *unit)
int IsTrainer (lua_State *L, Unit *unit)
int IsGossip (lua_State *L, Unit *unit)
int IsTaxi (lua_State *L, Unit *unit)
int IsSpiritHealer (lua_State *L, Unit *unit)
int IsSpiritGuide (lua_State *L, Unit *unit)
int IsTabardDesigner (lua_State *L, Unit *unit)
int IsServiceProvider (lua_State *L, Unit *unit)
int IsSpiritService (lua_State *L, Unit *unit)
int IsAlive (lua_State *L, Unit *unit)
int IsDead (lua_State *L, Unit *unit)
int IsDying (lua_State *L, Unit *unit)
int IsBanker (lua_State *L, Unit *unit)
int IsVendor (lua_State *L, Unit *unit)
int IsBattleMaster (lua_State *L, Unit *unit)
int IsCharmed (lua_State *L, Unit *unit)
int IsArmorer (lua_State *L, Unit *unit)
int IsAttackingPlayer (lua_State *L, Unit *unit)
int IsPvPFlagged (lua_State *L, Unit *unit)
int IsOnVehicle (lua_State *L, Unit *unit)
int IsInCombat (lua_State *L, Unit *unit)
int IsUnderWater (lua_State *L, Unit *unit)
int IsInWater (lua_State *L, Unit *unit)
int IsStopped (lua_State *L, Unit *unit)
int IsQuestGiver (lua_State *L, Unit *unit)
int HealthBelowPct (lua_State *L, Unit *unit)
int HealthAbovePct (lua_State *L, Unit *unit)
int HasAura (lua_State *L, Unit *unit)
int IsCasting (lua_State *L, Unit *unit)
int HasUnitState (lua_State *L, Unit *unit)
int GetOwner (lua_State *L, Unit *unit)
int GetOwnerGUID (lua_State *L, Unit *unit)
int GetMountId (lua_State *L, Unit *unit)
int GetCreatorGUID (lua_State *L, Unit *unit)
int GetCharmerGUID (lua_State *L, Unit *unit)
int GetCharmGUID (lua_State *L, Unit *unit)
int GetPetGUID (lua_State *L, Unit *unit)
int GetControllerGUID (lua_State *L, Unit *unit)
int GetControllerGUIDS (lua_State *L, Unit *unit)
int GetStat (lua_State *L, Unit *unit)
int GetBaseSpellPower (lua_State *L, Unit *unit)
int GetVictim (lua_State *L, Unit *unit)
int GetCurrentSpell (lua_State *L, Unit *unit)
int GetStandState (lua_State *L, Unit *unit)
int GetDisplayId (lua_State *L, Unit *unit)
int GetNativeDisplayId (lua_State *L, Unit *unit)
int GetLevel (lua_State *L, Unit *unit)
int GetHealth (lua_State *L, Unit *unit)
Powers PowerSelectorHelper (lua_State *L, Unit *unit, int powerType=-1)
int GetPower (lua_State *L, Unit *unit)
int GetMaxPower (lua_State *L, Unit *unit)
int GetPowerPct (lua_State *L, Unit *unit)
int GetPowerType (lua_State *L, Unit *unit)
int GetMaxHealth (lua_State *L, Unit *unit)
int GetHealthPct (lua_State *L, Unit *unit)
int GetGender (lua_State *L, Unit *unit)
int GetRace (lua_State *L, Unit *unit)
int GetClass (lua_State *L, Unit *unit)
int GetRaceMask (lua_State *L, Unit *unit)
int GetClassMask (lua_State *L, Unit *unit)
int GetCreatureType (lua_State *L, Unit *unit)
int GetClassAsString (lua_State *L, Unit *unit)
int GetRaceAsString (lua_State *L, Unit *unit)
int GetFaction (lua_State *L, Unit *unit)
int GetAura (lua_State *L, Unit *unit)
int GetFriendlyUnitsInRange (lua_State *L, Unit *unit)
int GetUnfriendlyUnitsInRange (lua_State *L, Unit *unit)
int GetVehicleKit (lua_State *L, Unit *unit)
int GetCritterGUID (lua_State *L, Unit *unit)
int GetSpeed (lua_State *L, Unit *unit)
int GetSpeedRate (lua_State *L, Unit *unit)
int GetMovementType (lua_State *L, Unit *unit)
int GetAttackers (lua_State *L, Unit *unit)
int SetOwnerGUID (lua_State *L, Unit *unit)
int SetPvP (lua_State *L, Unit *unit)
int SetSheath (lua_State *L, Unit *unit)
int SetName (lua_State *L, Unit *unit)
int SetSpeed (lua_State *L, Unit *unit)
int SetSpeedRate (lua_State *L, Unit *unit)
int SetFaction (lua_State *L, Unit *unit)
int SetLevel (lua_State *L, Unit *unit)
int SetHealth (lua_State *L, Unit *unit)
int SetMaxHealth (lua_State *L, Unit *unit)
int SetPower (lua_State *L, Unit *unit)
int ModifyPower (lua_State *L, Unit *unit)
int SetMaxPower (lua_State *L, Unit *unit)
int SetPowerType (lua_State *L, Unit *unit)
int SetDisplayId (lua_State *L, Unit *unit)
int SetNativeDisplayId (lua_State *L, Unit *unit)
int SetFacing (lua_State *L, Unit *unit)
int SetFacingToObject (lua_State *L, Unit *unit)
int SetCreatorGUID (lua_State *L, Unit *unit)
int SetPetGUID (lua_State *L, Unit *unit)
int SetWaterWalk (lua_State *L, Unit *unit)
int SetStandState (lua_State *L, Unit *unit)
int SetInCombatWith (lua_State *L, Unit *unit)
int SetFFA (lua_State *L, Unit *unit)
int SetSanctuary (lua_State *L, Unit *unit)
int SetCritterGUID (lua_State *L, Unit *unit)
int SetRooted (lua_State *L, Unit *unit)
int SetConfused (lua_State *L, Unit *unit)
int SetFeared (lua_State *L, Unit *unit)
int ClearThreatList (lua_State *, Unit *unit)
int GetThreatList (lua_State *L, Unit *unit)
int Mount (lua_State *L, Unit *unit)
int Dismount (lua_State *, Unit *unit)
int PerformEmote (lua_State *L, Unit *unit)
int EmoteState (lua_State *L, Unit *unit)
int CountPctFromCurHealth (lua_State *L, Unit *unit)
int CountPctFromMaxHealth (lua_State *L, Unit *unit)
int SendChatMessageToPlayer (lua_State *L, Unit *unit)
int MoveStop (lua_State *, Unit *unit)
int MoveExpire (lua_State *L, Unit *unit)
int MoveClear (lua_State *L, Unit *unit)
int MoveIdle (lua_State *, Unit *unit)
int MoveRandom (lua_State *L, Unit *unit)
int MoveHome (lua_State *, Unit *unit)
int MoveFollow (lua_State *L, Unit *unit)
int MoveChase (lua_State *L, Unit *unit)
int MoveConfused (lua_State *, Unit *unit)
int MoveFleeing (lua_State *L, Unit *unit)
int MoveTo (lua_State *L, Unit *unit)
int MoveJump (lua_State *L, Unit *unit)
int SendUnitWhisper (lua_State *L, Unit *unit)
int SendUnitEmote (lua_State *L, Unit *unit)
int SendUnitSay (lua_State *L, Unit *unit)
int SendUnitYell (lua_State *L, Unit *unit)
int DeMorph (lua_State *, Unit *unit)
int CastSpell (lua_State *L, Unit *unit)
int CastCustomSpell (lua_State *L, Unit *unit)
int CastSpellAoF (lua_State *L, Unit *unit)
int ClearInCombat (lua_State *, Unit *unit)
int StopSpellCast (lua_State *L, Unit *unit)
int InterruptSpell (lua_State *L, Unit *unit)
int AddAura (lua_State *L, Unit *unit)
int RemoveAura (lua_State *L, Unit *unit)
int RemoveAllAuras (lua_State *, Unit *unit)
int RemoveArenaAuras (lua_State *, Unit *unit)
int AddUnitState (lua_State *L, Unit *unit)
int ClearUnitState (lua_State *L, Unit *unit)
int NearTeleport (lua_State *L, Unit *unit)
int DealDamage (lua_State *L, Unit *unit)
int DealHeal (lua_State *L, Unit *unit)
int Kill (lua_State *L, Unit *unit)
int AddThreat (lua_State *L, Unit *unit)
int ModifyThreatPct (lua_State *L, Unit *unit)
Function Documentation
AddAura()
int LuaUnit::AddAura (lua_State * L, Unit * unit)
Adds the [Aura] of the given spell entry on the given target from the [Unit].
Parameters
uint32 spell : entry of a spell
[Unit] target : aura will be applied on the target
Returns
[Aura] aura
    {
        uint32 spell = Eluna::CHECKVAL<uint32>(L, 2);
        Unit* target = Eluna::CHECKOBJ<Unit>(L, 3);
        SpellInfo const* spellEntry = sSpellMgr->GetSpellInfo(spell);
        if (!spellEntry)
            return 1;
        Eluna::Push(L, unit->AddAura(spell, target));
        return 1;
    }
References Unit::AddAura(), Eluna::Push(), and sSpellMgr.
AddThreat()
int LuaUnit::AddThreat (lua_State * L, Unit * unit)
Adds threat to the [Unit] from the victim.
enum SpellSchoolMask
{
    SPELL_SCHOOL_MASK_NONE    = 0,
    SPELL_SCHOOL_MASK_NORMAL  = 1,
    SPELL_SCHOOL_MASK_HOLY    = 2,
    SPELL_SCHOOL_MASK_FIRE    = 4,
    SPELL_SCHOOL_MASK_NATURE  = 8,
    SPELL_SCHOOL_MASK_FROST   = 16,
    SPELL_SCHOOL_MASK_SHADOW  = 32,
    SPELL_SCHOOL_MASK_ARCANE  = 64,
}
Parameters
[Unit] victim : [Unit] that caused the threat
float threat : threat amount
[SpellSchoolMask] schoolMask = 0 : [SpellSchoolMask] of the threat causer
uint32 spell = 0 : spell entry used for threat
    {
        Unit* victim = Eluna::CHECKOBJ<Unit>(L, 2);
        float threat = Eluna::CHECKVAL<float>(L, 3, true);
        uint32 spell = Eluna::CHECKVAL<uint32>(L, 4, 0);
        uint32 schoolMask = Eluna::CHECKVAL<uint32>(L, 5, 0);
        if (schoolMask > SPELL_SCHOOL_MASK_ALL)
        {
            return luaL_argerror(L, 4, "valid SpellSchoolMask expected");
        }
        unit->AddThreat(victim, threat, (SpellSchoolMask)schoolMask, spell ? sSpellMgr->GetSpellInfo(spell) : NULL);
        return 0;
    }
References Unit::AddThreat(), luaL_argerror(), SPELL_SCHOOL_MASK_ALL, and sSpellMgr.
AddUnitState()
int LuaUnit::AddUnitState (lua_State * L, Unit * unit)
Adds the given unit state for the [Unit].
Parameters
[UnitState] state
    {
        uint32 state = Eluna::CHECKVAL<uint32>(L, 2);
        unit->AddUnitState(state);
        return 0;
    }
References Unit::AddUnitState().
Attack()
int LuaUnit::Attack (lua_State * L, Unit * unit)
The [Unit] tries to attack a given target
Parameters
[Unit] who : [Unit] to attack
bool meleeAttack = false: attack with melee or not
Returns
didAttack : if the [Unit] did not attack
    {
        Unit* who = Eluna::CHECKOBJ<Unit>(L, 2);
        bool meleeAttack = Eluna::CHECKVAL<bool>(L, 3, false);
        Eluna::Push(L, unit->Attack(who, meleeAttack));
        return 1;
    }
References Unit::Attack(), and Eluna::Push().
AttackStop()
int LuaUnit::AttackStop (lua_State * L, Unit * unit)
The [Unit] stops attacking its target
Returns
bool isAttacking : if the [Unit] wasn't attacking already
    {
        Eluna::Push(L, unit->AttackStop());
        return 1;
    }
References Unit::AttackStop(), and Eluna::Push().
CastCustomSpell()
int LuaUnit::CastCustomSpell (lua_State * L, Unit * unit)
Casts the [Spell] at target [Unit] with custom basepoints or casters. See also [Unit:CastSpell].
Parameters
[Unit] target = nil
uint32 spell
bool triggered = false
int32 bp0 = nil : custom basepoints for [Spell] effect 1. If nil, no change is made
int32 bp1 = nil : custom basepoints for [Spell] effect 2. If nil, no change is made
int32 bp2 = nil : custom basepoints for [Spell] effect 3. If nil, no change is made
[Item] castItem = nil
ObjectGuid originalCaster = ObjectGuid()
    {
        Unit* target = Eluna::CHECKOBJ<Unit>(L, 2, false);
        uint32 spell = Eluna::CHECKVAL<uint32>(L, 3);
        bool triggered = Eluna::CHECKVAL<bool>(L, 4, false);
        bool has_bp0 = !lua_isnoneornil(L, 5);
        int32 bp0 = Eluna::CHECKVAL<int32>(L, 5, 0);
        bool has_bp1 = !lua_isnoneornil(L, 6);
        int32 bp1 = Eluna::CHECKVAL<int32>(L, 6, 0);
        bool has_bp2 = !lua_isnoneornil(L, 7);
        int32 bp2 = Eluna::CHECKVAL<int32>(L, 7, 0);
        Item* castItem = Eluna::CHECKOBJ<Item>(L, 8, false);
        ObjectGuid originalCaster = Eluna::CHECKVAL<ObjectGuid>(L, 9, ObjectGuid());
        unit->CastCustomSpell(target, spell, has_bp0 ? &bp0 : NULL, has_bp1 ? &bp1 : NULL, has_bp2 ? &bp2 : NULL, triggered, castItem, NULL, ObjectGuid(originalCaster));
        return 0;
    }
References Unit::CastCustomSpell(), and lua_isnoneornil.
CastSpell()
int LuaUnit::CastSpell (lua_State * L, Unit * unit)
Makes the [Unit] cast the spell on the target.
Parameters
[Unit] target = nil : can be self or another unit
uint32 spell : entry of a spell
bool triggered = false : if true the spell is instant and has no cost
    {
        Unit* target = Eluna::CHECKOBJ<Unit>(L, 2, false);
        uint32 spell = Eluna::CHECKVAL<uint32>(L, 3);
        bool triggered = Eluna::CHECKVAL<bool>(L, 4, false);
        SpellInfo const* spellEntry = sSpellMgr->GetSpellInfo(spell);
        if (!spellEntry)
            return 0;
        unit->CastSpell(target, spell, triggered);
        return 0;
    }
References Unit::CastSpell(), and sSpellMgr.
CastSpellAoF()
int LuaUnit::CastSpellAoF (lua_State * L, Unit * unit)
Makes the [Unit] cast the spell to the given coordinates, used for area effect spells.
Parameters
float x
float y
float z
uint32 spell : entry of a spell
bool triggered = false : if true the spell is instant and has no cost
    {
        float _x = Eluna::CHECKVAL<float>(L, 2);
        float _y = Eluna::CHECKVAL<float>(L, 3);
        float _z = Eluna::CHECKVAL<float>(L, 4);
        uint32 spell = Eluna::CHECKVAL<uint32>(L, 5);
        bool triggered = Eluna::CHECKVAL<bool>(L, 6, true);
        unit->CastSpell(_x, _y, _z, spell, triggered);
        return 0;
    }
References Unit::CastSpell().
ClearInCombat()
int LuaUnit::ClearInCombat (lua_State * , Unit * unit)
Clears the [Unit]'s combat
    {
        unit->ClearInCombat();
        return 0;
    }
References Unit::ClearInCombat().
ClearThreatList()
int LuaUnit::ClearThreatList (lua_State * , Unit * unit)
Clears the [Unit]'s threat list.
    {
        unit->GetThreatMgr().ClearAllThreat();
        return 0;
    }
References ThreatMgr::ClearAllThreat(), and Unit::GetThreatMgr().
ClearUnitState()
int LuaUnit::ClearUnitState (lua_State * L, Unit * unit)
Removes the given unit state from the [Unit].
Parameters
[UnitState] state
    {
        uint32 state = Eluna::CHECKVAL<uint32>(L, 2);
        unit->ClearUnitState(state);
        return 0;
    }
References Unit::ClearUnitState().
CountPctFromCurHealth()
int LuaUnit::CountPctFromCurHealth (lua_State * L, Unit * unit)
Returns calculated percentage from Health
Returns
int32 percentage
    {
        Eluna::Push(L, unit->CountPctFromCurHealth(Eluna::CHECKVAL<int32>(L, 2)));
        return 1;
    }
References Unit::CountPctFromCurHealth(), and Eluna::Push().
CountPctFromMaxHealth()
int LuaUnit::CountPctFromMaxHealth (lua_State * L, Unit * unit)
Returns calculated percentage from Max Health
Returns
int32 percentage
    {
        Eluna::Push(L, unit->CountPctFromMaxHealth(Eluna::CHECKVAL<int32>(L, 2)));
        return 1;
    }
References Unit::CountPctFromMaxHealth(), and Eluna::Push().
DealDamage()
int LuaUnit::DealDamage (lua_State * L, Unit * unit)
Makes the [Unit] damage the target [Unit]
enum SpellSchools
{
    SPELL_SCHOOL_NORMAL  = 0,
    SPELL_SCHOOL_HOLY    = 1,
    SPELL_SCHOOL_FIRE    = 2,
    SPELL_SCHOOL_NATURE  = 3,
    SPELL_SCHOOL_FROST   = 4,
    SPELL_SCHOOL_SHADOW  = 5,
    SPELL_SCHOOL_ARCANE  = 6,
    MAX_SPELL_SCHOOL     = 7
};
Parameters
[Unit] target : [Unit] to damage
uint32 damage : amount to damage
bool durabilityloss = true : if false, the damage does not do durability damage
[SpellSchools] school = MAX_SPELL_SCHOOL : school the damage is done in or MAX_SPELL_SCHOOL for direct damage
uint32 spell = 0 : spell that inflicts the damage
    {
        Unit* target = Eluna::CHECKOBJ<Unit>(L, 2);
        uint32 damage = Eluna::CHECKVAL<uint32>(L, 3);
        bool durabilityloss = Eluna::CHECKVAL<bool>(L, 4, true);
        uint32 school = Eluna::CHECKVAL<uint32>(L, 5, MAX_SPELL_SCHOOL);
        uint32 spell = Eluna::CHECKVAL<uint32>(L, 6, 0);
        if (school > MAX_SPELL_SCHOOL)
            return luaL_argerror(L, 6, "valid SpellSchool expected");
        // flat melee damage without resistence/etc reduction
        if (school == MAX_SPELL_SCHOOL)
        {
            Unit::DealDamage(unit, target, damage, NULL, DIRECT_DAMAGE, SPELL_SCHOOL_MASK_NORMAL, NULL, durabilityloss);
            unit->SendAttackStateUpdate(HITINFO_AFFECTS_VICTIM, target, 1, SPELL_SCHOOL_MASK_NORMAL, damage, 0, 0, VICTIMSTATE_HIT, 0);
            return 0;
        }
        SpellSchoolMask schoolmask = SpellSchoolMask(1 << school);
        if (Unit::IsDamageReducedByArmor(schoolmask))
            damage = Unit::CalcArmorReducedDamage(unit, target, damage, NULL, BASE_ATTACK);
        if (!spell)
        {
            DamageInfo dmgInfo(unit, target, damage, nullptr, schoolmask, SPELL_DIRECT_DAMAGE);
            unit->CalcAbsorbResist(dmgInfo);
            if (!dmgInfo.GetDamage())
                damage = 0;
            else
                damage = dmgInfo.GetDamage();
            uint32 absorb = dmgInfo.GetAbsorb();
            uint32 resist = dmgInfo.GetResist();
            unit->DealDamageMods(target, damage, &absorb);
            Unit::DealDamage(unit, target, damage, NULL, DIRECT_DAMAGE, schoolmask, NULL, false);
            unit->SendAttackStateUpdate(HITINFO_AFFECTS_VICTIM, target, 0, schoolmask, damage, absorb, resist, VICTIMSTATE_HIT, 0);
            return 0;
        }
        if (!spell)
            return 0;
        SpellInfo const* spellInfo = sSpellMgr->GetSpellInfo(spell);
        if (!spellInfo)
            return 0;
        SpellNonMeleeDamage dmgInfo(unit, target, spellInfo, spellInfo->GetSchoolMask());
        Unit::DealDamageMods(dmgInfo.target, dmgInfo.damage, &dmgInfo.absorb);
        unit->SendSpellNonMeleeDamageLog(&dmgInfo);
        unit->DealSpellDamage(&dmgInfo, true);
        return 0;
    }
References SpellNonMeleeDamage::absorb, BASE_ATTACK, Unit::CalcAbsorbResist(), Unit::CalcArmorReducedDamage(), SpellNonMeleeDamage::damage, Unit::DealDamage(), Unit::DealDamageMods(), Unit::DealSpellDamage(), DIRECT_DAMAGE, DamageInfo::GetAbsorb(), DamageInfo::GetDamage(), DamageInfo::GetResist(), SpellInfo::GetSchoolMask(), HITINFO_AFFECTS_VICTIM, Unit::IsDamageReducedByArmor(), luaL_argerror(), MAX_SPELL_SCHOOL, Unit::SendAttackStateUpdate(), Unit::SendSpellNonMeleeDamageLog(), SPELL_DIRECT_DAMAGE, SPELL_SCHOOL_MASK_NORMAL, sSpellMgr, SpellNonMeleeDamage::target, and VICTIMSTATE_HIT.
DealHeal()
int LuaUnit::DealHeal (lua_State * L, Unit * unit)
Makes the [Unit] heal the target [Unit] with given spell
Parameters
[Unit] target : [Unit] to heal
uint32 spell : spell that causes the healing
uint32 amount : amount to heal
bool critical = false : if true, heal is logged as critical
    {
        Unit* target = Eluna::CHECKOBJ<Unit>(L, 2);
        uint32 spell = Eluna::CHECKVAL<uint32>(L, 3);
        uint32 amount = Eluna::CHECKVAL<uint32>(L, 4);
        bool critical = Eluna::CHECKVAL<bool>(L, 5, false);
        if (const SpellInfo* info = sSpellMgr->GetSpellInfo(spell))
        {
            HealInfo healInfo(unit, target, amount, info, info->GetSchoolMask());
            unit->HealBySpell(healInfo, critical);
        }
        return 0;
    }
References Unit::HealBySpell(), and sSpellMgr.
DeMorph()
int LuaUnit::DeMorph (lua_State * , Unit * unit)
Unmorphs the [Unit] setting it's display ID back to the native display ID.
    {
        unit->DeMorph();
        return 0;
    }
References Unit::DeMorph().
Dismount()
int LuaUnit::Dismount (lua_State * , Unit * unit)
Dismounts the [Unit].
    {
        if (unit->IsMounted())
        {
            unit->Dismount();
            unit->RemoveAurasByType(SPELL_AURA_MOUNTED);
        }
        return 0;
    }
References Unit::Dismount(), Unit::IsMounted(), Unit::RemoveAurasByType(), and SPELL_AURA_MOUNTED.
EmoteState()
int LuaUnit::EmoteState (lua_State * L, Unit * unit)
Makes the [Unit] perform the given emote continuously.
Parameters
uint32 emoteId
    {
        uint32 emoteId = Eluna::CHECKVAL<uint32>(L, 2);
        unit->SetUInt32Value(UNIT_NPC_EMOTESTATE, emoteId);
        return 0;
    }
References Unit::SetUInt32Value(), and UNIT_NPC_EMOTESTATE.
GetAttackers()
int LuaUnit::GetAttackers (lua_State * L, Unit * unit)
Returns the [Unit]'s attackers.
Returns
table attackers : table of [Unit]s attacking the unit
    {
        const Unit::AttackerSet& attackers = unit->getAttackers();
        lua_newtable(L);
        int table = lua_gettop(L);
        uint32 i = 1;
        for (Unit* attacker : attackers)
        {
            if (!attacker)
            {
                continue;
            }
            Eluna::Push(L, attacker);
            lua_rawseti(L, table, i);
            ++i;
        }
        lua_settop(L, table); // push table to top of stack
        return 1;
    }
References Unit::getAttackers(), lua_gettop(), lua_newtable, lua_rawseti(), lua_settop(), and Eluna::Push().
GetAura()
int LuaUnit::GetAura (lua_State * L, Unit * unit)
Returns the [Aura] of the given spell entry on the [Unit] or nil.
Parameters
uint32 spellID : entry of the aura spell
Returns
[Aura] aura : aura object or nil
    {
        uint32 spellID = Eluna::CHECKVAL<uint32>(L, 2);
        Eluna::Push(L, unit->GetAura(spellID));
        return 1;
    }
References Unit::GetAura(), and Eluna::Push().
GetBaseSpellPower()
int LuaUnit::GetBaseSpellPower (lua_State * L, Unit * unit)
Returns the [Unit]'s base spell power
Parameters
uint32 spellSchool
Returns
uint32 spellPower
    {
        uint32 spellschool = Eluna::CHECKVAL<uint32>(L, 2);
        if (spellschool >= MAX_SPELL_SCHOOL)
            return 1;
        Eluna::Push(L, unit->GetUInt32Value(PLAYER_FIELD_MOD_DAMAGE_DONE_POS + spellschool));
        return 1;
    }
References Object::GetUInt32Value(), MAX_SPELL_SCHOOL, PLAYER_FIELD_MOD_DAMAGE_DONE_POS, and Eluna::Push().
GetCharmerGUID()
int LuaUnit::GetCharmerGUID (lua_State * L, Unit * unit)
Returns the [Unit]'s charmer's GUID.
Returns
ObjectGuid charmerGUID
    {
        Eluna::Push(L, unit->GetCharmerGUID());
        return 1;
    }
References Unit::GetCharmerGUID(), and Eluna::Push().
GetCharmGUID()
int LuaUnit::GetCharmGUID (lua_State * L, Unit * unit)
Returns the GUID of the [Unit]'s charmed entity.
Returns
ObjectGuid charmedGUID
    {
        Eluna::Push(L, unit->GetCharmGUID());
        return 1;
    }
References Unit::GetCharmGUID(), and Eluna::Push().
GetClass()
int LuaUnit::GetClass (lua_State * L, Unit * unit)
Returns the [Unit]'s class ID.
Returns
[Classes] class
    {
        Eluna::Push(L, unit->getClass());
        return 1;
    }
References Unit::getClass(), and Eluna::Push().
GetClassAsString()
int LuaUnit::GetClassAsString (lua_State * L, Unit * unit)
Returns the [Unit]'s class' name in given or default locale or nil.
enum LocaleConstant
{
    LOCALE_enUS = 0,
    LOCALE_koKR = 1,
    LOCALE_frFR = 2,
    LOCALE_deDE = 3,
    LOCALE_zhCN = 4,
    LOCALE_zhTW = 5,
    LOCALE_esES = 6,
    LOCALE_esMX = 7,
    LOCALE_ruRU = 8
};
Parameters
[LocaleConstant] locale = DEFAULT_LOCALE
Returns
string className : class name or nil
    {
        uint8 locale = Eluna::CHECKVAL<uint8>(L, 2, DEFAULT_LOCALE);
        if (locale >= TOTAL_LOCALES)
            return luaL_argerror(L, 2, "valid LocaleConstant expected");
        const ChrClassesEntry* entry = sChrClassesStore.LookupEntry(unit->getClass());
        if (!entry)
            return 1;
        Eluna::Push(L, entry->name[locale]);
        return 1;
    }
References DEFAULT_LOCALE, Unit::getClass(), luaL_argerror(), ChrClassesEntry::name, Eluna::Push(), sChrClassesStore, and TOTAL_LOCALES.
GetClassMask()
int LuaUnit::GetClassMask (lua_State * L, Unit * unit)
Returns the class mask
Returns
uint32 classmask
    {
        Eluna::Push(L, unit->getClassMask());
        return 1;
    }
References Unit::getClassMask(), and Eluna::Push().
GetControllerGUID()
int LuaUnit::GetControllerGUID (lua_State * L, Unit * unit)
Returns the GUID of the [Unit]'s charmer or owner.
Returns
ObjectGuid controllerGUID
    {
        Eluna::Push(L, unit->GetCharmerOrOwnerGUID());
        return 1;
    }
References Unit::GetCharmerOrOwnerGUID(), and Eluna::Push().
GetControllerGUIDS()
int LuaUnit::GetControllerGUIDS (lua_State * L, Unit * unit)
Returns the GUID of the [Unit]'s charmer or owner or its own GUID.
Returns
ObjectGuid controllerGUID
    {
        Eluna::Push(L, unit->GetCharmerOrOwnerOrOwnGUID());
        return 1;
    }
References Unit::GetCharmerOrOwnerOrOwnGUID(), and Eluna::Push().
GetCreatorGUID()
int LuaUnit::GetCreatorGUID (lua_State * L, Unit * unit)
Returns the [Unit]'s creator's GUID.
Returns
ObjectGuid creatorGUID
    {
        Eluna::Push(L, unit->GetCreatorGUID());
        return 1;
    }
References Unit::GetCreatorGUID(), and Eluna::Push().
GetCreatureType()
int LuaUnit::GetCreatureType (lua_State * L, Unit * unit)
Returns the [Unit]'s creature type ID (enumerated in CreatureType.dbc).
enum CreatureType
{
    CREATURE_TYPE_BEAST            = 1,
    CREATURE_TYPE_DRAGONKIN        = 2,
    CREATURE_TYPE_DEMON            = 3,
    CREATURE_TYPE_ELEMENTAL        = 4,
    CREATURE_TYPE_GIANT            = 5,
    CREATURE_TYPE_UNDEAD           = 6,
    CREATURE_TYPE_HUMANOID         = 7,
    CREATURE_TYPE_CRITTER          = 8,
    CREATURE_TYPE_MECHANICAL       = 9,
    CREATURE_TYPE_NOT_SPECIFIED    = 10,
    CREATURE_TYPE_TOTEM            = 11,
    CREATURE_TYPE_NON_COMBAT_PET   = 12,     // This and below is TBC+
    CREATURE_TYPE_GAS_CLOUD        = 13
};
Returns
[CreatureType] creatureType
    {
        Eluna::Push(L, unit->GetCreatureType());
        return 1;
    }
References Unit::GetCreatureType(), and Eluna::Push().
GetCritterGUID()
int LuaUnit::GetCritterGUID (lua_State * L, Unit * unit)
Returns the Critter Guid
Returns
ObjectGuid critterGuid
    {
        Eluna::Push(L, unit->GetCritterGUID());
        return 1;
    }
References Unit::GetCritterGUID(), and Eluna::Push().
GetCurrentSpell()
int LuaUnit::GetCurrentSpell (lua_State * L, Unit * unit)
Returns the currently casted [Spell] of given type or nil.
enum CurrentSpellTypes
{
    CURRENT_MELEE_SPELL             = 0,
    CURRENT_GENERIC_SPELL           = 1,
    CURRENT_CHANNELED_SPELL         = 2,
    CURRENT_AUTOREPEAT_SPELL        = 3
};
Parameters
[CurrentSpellTypes] spellType
Returns
[Spell] castedSpell
    {
        uint32 type = Eluna::CHECKVAL<uint32>(L, 2);
        if (type >= CURRENT_MAX_SPELL)
            return luaL_argerror(L, 2, "valid CurrentSpellTypes expected");
        Eluna::Push(L, unit->GetCurrentSpell(type));
        return 1;
    }
References CURRENT_MAX_SPELL, Unit::GetCurrentSpell(), luaL_argerror(), and Eluna::Push().
GetDisplayId()
int LuaUnit::GetDisplayId (lua_State * L, Unit * unit)
Returns the [Unit]'s current display ID.
Returns
uint32 displayId
    {
        Eluna::Push(L, unit->GetDisplayId());
        return 1;
    }
References Unit::GetDisplayId(), and Eluna::Push().
GetFaction()
int LuaUnit::GetFaction (lua_State * L, Unit * unit)
Returns the [Unit]'s faction ID.
Returns
uint32 faction
    {
        Eluna::Push(L, unit->GetFaction());
        return 1;
    }
References Unit::GetFaction(), and Eluna::Push().
GetFriendlyUnitsInRange()
int LuaUnit::GetFriendlyUnitsInRange (lua_State * L, Unit * unit)
Returns a table containing friendly [Unit]'s within given range of the [Unit].
Parameters
float range = 533.333 : search radius
Returns
table friendyUnits : table filled with friendly units
    {
        float range = Eluna::CHECKVAL<float>(L, 2, SIZE_OF_GRIDS);
        std::list<Unit*> list;
        Acore::AnyFriendlyUnitInObjectRangeCheck checker(unit, unit, range);
        Acore::UnitListSearcher<Acore::AnyFriendlyUnitInObjectRangeCheck> searcher(unit, list, checker);
        Cell::VisitAllObjects(unit, searcher, range);
        ElunaUtil::ObjectGUIDCheck guidCheck(unit->GET_GUID());
        list.remove_if(guidCheck);
        lua_createtable(L, list.size(), 0);
        int tbl = lua_gettop(L);
        uint32 i = 0;
        for (std::list<Unit*>::const_iterator it = list.begin(); it != list.end(); ++it)
        {
            Eluna::Push(L, *it);
            lua_rawseti(L, tbl, ++i);
        }
        lua_settop(L, tbl);
        return 1;
    }
References lua_createtable(), lua_gettop(), lua_rawseti(), lua_settop(), Eluna::Push(), SIZE_OF_GRIDS, and Cell::VisitAllObjects().
GetGender()
int LuaUnit::GetGender (lua_State * L, Unit * unit)
Returns the [Unit]'s gender.
Returns
uint8 gender : 0 for male, 1 for female and 2 for none
    {
        Eluna::Push(L, unit->getGender());
        return 1;
    }
References Unit::getGender(), and Eluna::Push().
GetHealth()
int LuaUnit::GetHealth (lua_State * L, Unit * unit)
Returns the [Unit]'s health amount.
Returns
uint32 healthAmount
    {
        Eluna::Push(L, unit->GetHealth());
        return 1;
    }
References Unit::GetHealth(), and Eluna::Push().
GetHealthPct()
int LuaUnit::GetHealthPct (lua_State * L, Unit * unit)
Returns the [Unit]'s health percent.
Returns
float healthPct
    {
        Eluna::Push(L, unit->GetHealthPct());
        return 1;
    }
References Unit::GetHealthPct(), and Eluna::Push().
GetLevel()
int LuaUnit::GetLevel (lua_State * L, Unit * unit)
Returns the [Unit]'s level.
Returns
uint8 level
    {
        Eluna::Push(L, unit->GetLevel());
        return 1;
    }
References Unit::GetLevel(), and Eluna::Push().
GetMaxHealth()
int LuaUnit::GetMaxHealth (lua_State * L, Unit * unit)
Returns the [Unit]'s max health.
Returns
uint32 maxHealth
    {
        Eluna::Push(L, unit->GetMaxHealth());
        return 1;
    }
References Unit::GetMaxHealth(), and Eluna::Push().
GetMaxPower()
int LuaUnit::GetMaxPower (lua_State * L, Unit * unit)
Returns the [Unit]'s max power amount for given power type.
enum Powers
{
    POWER_MANA        = 0,
    POWER_RAGE        = 1,
    POWER_FOCUS       = 2,
    POWER_ENERGY      = 3,
    POWER_HAPPINESS   = 4,
    POWER_RUNE        = 5,
    POWER_RUNIC_POWER = 6,
    MAX_POWERS        = 7,
    POWER_ALL         = 127,         // default for class?
    POWER_HEALTH      = 0xFFFFFFFE   // (-2 as signed value)
};
Parameters
int type = -1 : a valid power type from [Powers] or -1 for the [Unit]'s current power type
Returns
uint32 maxPowerAmount
    {
        int type = Eluna::CHECKVAL<int>(L, 2, -1);
        Powers power = PowerSelectorHelper(L, unit, type);
        Eluna::Push(L, unit->GetMaxPower(power));
        return 1;
    }
References Unit::GetMaxPower(), PowerSelectorHelper(), and Eluna::Push().
GetMountId()
int LuaUnit::GetMountId (lua_State * L, Unit * unit)
Returns the [Unit]'s mount's modelID.
Returns
uint32 mountId : displayId of the mount
    {
        Eluna::Push(L, unit->GetMountID());
        return 1;
    }
References Unit::GetMountID(), and Eluna::Push().
GetMovementType()
int LuaUnit::GetMovementType (lua_State * L, Unit * unit)
Returns the current movement type for this [Unit].
enum MovementGeneratorType
{
    IDLE_MOTION_TYPE                = 0,
    RANDOM_MOTION_TYPE              = 1,
    WAYPOINT_MOTION_TYPE            = 2,
    MAX_DB_MOTION_TYPE              = 3,
    ANIMAL_RANDOM_MOTION_TYPE       = 3, // TC
    CONFUSED_MOTION_TYPE            = 4,
    CHASE_MOTION_TYPE               = 5,
    HOME_MOTION_TYPE                = 6,
    FLIGHT_MOTION_TYPE              = 7,
    POINT_MOTION_TYPE               = 8,
    FLEEING_MOTION_TYPE             = 9,
    DISTRACT_MOTION_TYPE            = 10,
    ASSISTANCE_MOTION_TYPE          = 11,
    ASSISTANCE_DISTRACT_MOTION_TYPE = 12,
    TIMED_FLEEING_MOTION_TYPE       = 13,
    FOLLOW_MOTION_TYPE              = 14,
    EFFECT_MOTION_TYPE              = 15, // mangos
    ROTATE_MOTION_TYPE              = 15, // TC
    EFFECT_MOTION_TYPE              = 16, // TC
    NULL_MOTION_TYPE                = 17, // TC
};
Returns
[MovementGeneratorType] movementType
    {
        Eluna::Push(L, unit->GetMotionMaster()->GetCurrentMovementGeneratorType());
        return 1;
    }
References MotionMaster::GetCurrentMovementGeneratorType(), Unit::GetMotionMaster(), and Eluna::Push().
GetNativeDisplayId()
int LuaUnit::GetNativeDisplayId (lua_State * L, Unit * unit)
Returns the [Unit]'s native/original display ID.
Returns
uint32 displayId
    {
        Eluna::Push(L, unit->GetNativeDisplayId());
        return 1;
    }
References Unit::GetNativeDisplayId(), and Eluna::Push().
GetOwner()
int LuaUnit::GetOwner (lua_State * L, Unit * unit)
Returns the [Unit]'s owner.
Returns
[Unit] owner
    {
        Eluna::Push(L, unit->GetOwner());
        return 1;
    }
References Unit::GetOwner(), and Eluna::Push().
GetOwnerGUID()
int LuaUnit::GetOwnerGUID (lua_State * L, Unit * unit)
Returns the [Unit]'s owner's GUID.
Returns
ObjectGuid ownerGUID
    {
        Eluna::Push(L, unit->GetOwnerGUID());
        return 1;
    }
References Unit::GetOwnerGUID(), and Eluna::Push().
GetPetGUID()
int LuaUnit::GetPetGUID (lua_State * L, Unit * unit)
Returns the GUID of the [Unit]'s pet.
Returns
ObjectGuid petGUID
    {
        Eluna::Push(L, unit->GetPetGUID());
        return 1;
    }
References Unit::GetPetGUID(), and Eluna::Push().
GetPower()
int LuaUnit::GetPower (lua_State * L, Unit * unit)
Returns the [Unit]'s power amount for given power type.
enum Powers
{
    POWER_MANA        = 0,
    POWER_RAGE        = 1,
    POWER_FOCUS       = 2,
    POWER_ENERGY      = 3,
    POWER_HAPPINESS   = 4,
    POWER_RUNE        = 5,
    POWER_RUNIC_POWER = 6,
    MAX_POWERS        = 7,
    POWER_ALL         = 127,         // default for class?
    POWER_HEALTH      = 0xFFFFFFFE   // (-2 as signed value)
};
Parameters
int type = -1 : a valid power type from [Powers] or -1 for the [Unit]'s current power type
Returns
uint32 powerAmount
    {
        int type = Eluna::CHECKVAL<int>(L, 2, -1);
        Powers power = PowerSelectorHelper(L, unit, type);
        Eluna::Push(L, unit->GetPower(power));
        return 1;
    }
References Unit::GetPower(), PowerSelectorHelper(), and Eluna::Push().
GetPowerPct()
int LuaUnit::GetPowerPct (lua_State * L, Unit * unit)
Returns the [Unit]'s power percent for given power type.
enum Powers
{
    POWER_MANA        = 0,
    POWER_RAGE        = 1,
    POWER_FOCUS       = 2,
    POWER_ENERGY      = 3,
    POWER_HAPPINESS   = 4,
    POWER_RUNE        = 5,
    POWER_RUNIC_POWER = 6,
    MAX_POWERS        = 7,
    POWER_ALL         = 127,         // default for class?
    POWER_HEALTH      = 0xFFFFFFFE   // (-2 as signed value)
};
Parameters
int type = -1 : a valid power type from [Powers] or -1 for the [Unit]'s current power type
Returns
float powerPct
    {
        int type = Eluna::CHECKVAL<int>(L, 2, -1);
        Powers power = PowerSelectorHelper(L, unit, type);
        float percent = ((float)unit->GetPower(power) / (float)unit->GetMaxPower(power)) * 100.0f;
        Eluna::Push(L, percent);
        return 1;
    }
References Unit::GetMaxPower(), Unit::GetPower(), PowerSelectorHelper(), and Eluna::Push().
GetPowerType()
int LuaUnit::GetPowerType (lua_State * L, Unit * unit)
Returns the [Unit]'s current power type.
enum Powers
{
    POWER_MANA        = 0,
    POWER_RAGE        = 1,
    POWER_FOCUS       = 2,
    POWER_ENERGY      = 3,
    POWER_HAPPINESS   = 4,
    POWER_RUNE        = 5,
    POWER_RUNIC_POWER = 6,
    MAX_POWERS        = 7,
    POWER_ALL         = 127,         // default for class?
    POWER_HEALTH      = 0xFFFFFFFE   // (-2 as signed value)
};
Returns
[Powers] powerType
    {
        Eluna::Push(L, unit->getPowerType());
        return 1;
    }
References Unit::getPowerType(), and Eluna::Push().
GetRace()
int LuaUnit::GetRace (lua_State * L, Unit * unit)
Returns the [Unit]'s race ID.
Returns
[Races] race
    {
        Eluna::Push(L, unit->getRace());
        return 1;
    }
References Unit::getRace(), and Eluna::Push().
GetRaceAsString()
int LuaUnit::GetRaceAsString (lua_State * L, Unit * unit)
Returns the [Unit]'s race's name in given or default locale or nil.
enum LocaleConstant
{
    LOCALE_enUS = 0,
    LOCALE_koKR = 1,
    LOCALE_frFR = 2,
    LOCALE_deDE = 3,
    LOCALE_zhCN = 4,
    LOCALE_zhTW = 5,
    LOCALE_esES = 6,
    LOCALE_esMX = 7,
    LOCALE_ruRU = 8
};
Parameters
[LocaleConstant] locale = DEFAULT_LOCALE : locale to return the race name in
Returns
string raceName : race name or nil
    {
        uint8 locale = Eluna::CHECKVAL<uint8>(L, 2, DEFAULT_LOCALE);
        if (locale >= TOTAL_LOCALES)
            return luaL_argerror(L, 2, "valid LocaleConstant expected");
        const ChrRacesEntry* entry = sChrRacesStore.LookupEntry(unit->getRace());
        if (!entry)
            return 1;
        Eluna::Push(L, entry->name[locale]);
        return 1;
    }
References DEFAULT_LOCALE, Unit::getRace(), luaL_argerror(), ChrRacesEntry::name, Eluna::Push(), sChrRacesStore, and TOTAL_LOCALES.
GetRaceMask()
int LuaUnit::GetRaceMask (lua_State * L, Unit * unit)
Returns the race mask
Returns
uint32 racemask
    {
        Eluna::Push(L, unit->getRaceMask());
        return 1;
    }
References Unit::getRaceMask(), and Eluna::Push().
GetSpeed()
int LuaUnit::GetSpeed (lua_State * L, Unit * unit)
Returns the [Unit]'s speed of given [UnitMoveType].
enum UnitMoveType
{
    MOVE_WALK           = 0,
    MOVE_RUN            = 1,
    MOVE_RUN_BACK       = 2,
    MOVE_SWIM           = 3,
    MOVE_SWIM_BACK      = 4,
    MOVE_TURN_RATE      = 5,
    MOVE_FLIGHT         = 6,
    MOVE_FLIGHT_BACK    = 7,
    MOVE_PITCH_RATE     = 8
};
Parameters
[UnitMoveType] type
Returns
float speed
    {
        uint32 type = Eluna::CHECKVAL<uint32>(L, 2);
        if (type >= MAX_MOVE_TYPE)
            return luaL_argerror(L, 2, "valid UnitMoveType expected");
        Eluna::Push(L, unit->GetSpeed((UnitMoveType)type));
        return 1;
    }
References Unit::GetSpeed(), luaL_argerror(), MAX_MOVE_TYPE, and Eluna::Push().
GetSpeedRate()
int LuaUnit::GetSpeedRate (lua_State * L, Unit * unit)
Returns the [Unit]'s speed rate of given [UnitMoveType].
enum UnitMoveType
{
    MOVE_WALK           = 0,
    MOVE_RUN            = 1,
    MOVE_RUN_BACK       = 2,
    MOVE_SWIM           = 3,
    MOVE_SWIM_BACK      = 4,
    MOVE_TURN_RATE      = 5,
    MOVE_FLIGHT         = 6,
    MOVE_FLIGHT_BACK    = 7,
    MOVE_PITCH_RATE     = 8
};
Parameters
[UnitMoveType] type
Returns
float speed
    {
        uint32 type = Eluna::CHECKVAL<uint32>(L, 2);
        if (type >= MAX_MOVE_TYPE)
        {
            return luaL_argerror(L, 2, "valid UnitMoveType expected");
        }
        Eluna::Push(L, unit->GetSpeedRate((UnitMoveType)type));
        return 1;
    }
References Unit::GetSpeedRate(), luaL_argerror(), MAX_MOVE_TYPE, and Eluna::Push().
GetStandState()
int LuaUnit::GetStandState (lua_State * L, Unit * unit)
Returns the [Unit]'s current stand state.
Returns
uint8 standState
    {
        Eluna::Push(L, unit->getStandState());
        return 1;
    }
References Unit::getStandState(), and Eluna::Push().
GetStat()
int LuaUnit::GetStat (lua_State * L, Unit * unit)
Returns [Unit]'s specified stat
Parameters
uint32 statType
Returns
float stat
    {
        uint32 stat = Eluna::CHECKVAL<uint32>(L, 2);
        if (stat >= MAX_STATS)
            return 1;
        Eluna::Push(L, unit->GetStat((Stats)stat));
        return 1;
    }
References Unit::GetStat(), MAX_STATS, and Eluna::Push().
GetThreatList()
int LuaUnit::GetThreatList (lua_State * L, Unit * unit)
Returns the [Unit]'s threat list.
Returns
table threatList : table of [Unit]s in the threat list
    {
        if (!unit->CanHaveThreatList())
        {
            Eluna::Push(L);
            return 1;
        }
        ThreatContainer::StorageType const& list = unit->GetThreatMgr().GetThreatList();
        lua_newtable(L);
        int table = lua_gettop(L);
        uint32 i = 1;
        for (ThreatReference* item : list)
        {
            if (!item)
            {
                continue;
            }
            Unit* victim = item->GetVictim();
            if (!victim)
            {
                continue;
            }
            Eluna::Push(L, victim);
            lua_rawseti(L, table, i);
            ++i;
        }
        lua_settop(L, table); // push table to top of stack
        return 1;
    }
References Unit::CanHaveThreatList(), ThreatMgr::GetThreatList(), Unit::GetThreatMgr(), Unit::GetVictim(), lua_gettop(), lua_newtable, lua_rawseti(), lua_settop(), and Eluna::Push().
GetUnfriendlyUnitsInRange()
int LuaUnit::GetUnfriendlyUnitsInRange (lua_State * L, Unit * unit)
Returns a table containing unfriendly [Unit]'s within given range of the [Unit].
Parameters
float range = 533.333 : search radius
Returns
table unfriendyUnits : table filled with unfriendly units
    {
        float range = Eluna::CHECKVAL<float>(L, 2, SIZE_OF_GRIDS);
        std::list<Unit*> list;
        Acore::AnyUnfriendlyUnitInObjectRangeCheck checker(unit, unit, range);
        Acore::UnitListSearcher<Acore::AnyUnfriendlyUnitInObjectRangeCheck> searcher(unit, list, checker);
        Cell::VisitAllObjects(unit, searcher, range);
        ElunaUtil::ObjectGUIDCheck guidCheck(unit->GET_GUID());
        list.remove_if(guidCheck);
        lua_createtable(L, list.size(), 0);
        int tbl = lua_gettop(L);
        uint32 i = 0;
        for (std::list<Unit*>::const_iterator it = list.begin(); it != list.end(); ++it)
        {
            Eluna::Push(L, *it);
            lua_rawseti(L, tbl, ++i);
        }
        lua_settop(L, tbl);
        return 1;
    }
References lua_createtable(), lua_gettop(), lua_rawseti(), lua_settop(), Eluna::Push(), SIZE_OF_GRIDS, and Cell::VisitAllObjects().
GetVehicleKit()
int LuaUnit::GetVehicleKit (lua_State * L, Unit * unit)
Returns [Unit]'s [Vehicle] methods
Returns
[Vehicle] vehicle
    {
        Eluna::Push(L, unit->GetVehicleKit());
        return 1;
    }
References Unit::GetVehicleKit(), and Eluna::Push().
GetVictim()
int LuaUnit::GetVictim (lua_State * L, Unit * unit)
Returns the [Unit]'s current victim target or nil.
Returns
[Unit] victim
    {
        Eluna::Push(L, unit->GetVictim());
        return 1;
    }
References Unit::GetVictim(), and Eluna::Push().
HandleStatModifier()
int LuaUnit::HandleStatModifier (lua_State * L, Unit * unit)
The [Unit] modifies a specific stat
Parameters
int32 stat : The stat to modify
int8 type : The type of modifier to apply
float value : The value to apply to the stat
bool apply = false : Whether the modifier should be applied or removed
Returns
bool : Whether the stat modification was successful
    {
        int32 stat = Eluna::CHECKVAL<int32>(L, 2);
        int8  type = Eluna::CHECKVAL<int8>(L, 3);
        float value = Eluna::CHECKVAL<float>(L, 4);
        bool apply = Eluna::CHECKVAL<bool>(L, 5, false);
        Eluna::Push(L, unit->HandleStatModifier(UnitMods(UNIT_MOD_STAT_START + stat), (UnitModifierType)type, value, apply));
        return 1;
    }
References Unit::HandleStatModifier(), Eluna::Push(), and UNIT_MOD_STAT_START.
HasAura()
int LuaUnit::HasAura (lua_State * L, Unit * unit)
Returns true if the [Unit] has an aura from the given spell entry.
Parameters
uint32 spell : entry of the aura spell
Returns
bool hasAura
    {
        uint32 spell = Eluna::CHECKVAL<uint32>(L, 2);
        Eluna::Push(L, unit->HasAura(spell));
        return 1;
    }
References Unit::HasAura(), and Eluna::Push().
HasUnitState()
int LuaUnit::HasUnitState (lua_State * L, Unit * unit)
Returns true if the [Unit] has the given unit state.
Parameters
[UnitState] state : an unit state
Returns
bool hasState
    {
        uint32 state = Eluna::CHECKVAL<uint32>(L, 2);
        Eluna::Push(L, unit->HasUnitState(state));
        return 1;
    }
References Unit::HasUnitState(), and Eluna::Push().
HealthAbovePct()
int LuaUnit::HealthAbovePct (lua_State * L, Unit * unit)
Returns true if the [Unit]'s health is above the given percentage.
Parameters
int32 healthpct : percentage in integer from
Returns
bool isAbove
    {
        Eluna::Push(L, unit->HealthAbovePct(Eluna::CHECKVAL<int32>(L, 2)));
        return 1;
    }
References Unit::HealthAbovePct(), and Eluna::Push().
HealthBelowPct()
int LuaUnit::HealthBelowPct (lua_State * L, Unit * unit)
Returns true if the [Unit]'s health is below the given percentage.
Parameters
int32 healthpct : percentage in integer from
Returns
bool isBelow
    {
        Eluna::Push(L, unit->HealthBelowPct(Eluna::CHECKVAL<int32>(L, 2)));
        return 1;
    }
References Unit::HealthBelowPct(), and Eluna::Push().
InterruptSpell()
int LuaUnit::InterruptSpell (lua_State * L, Unit * unit)
Interrupts [Unit]'s spell state, casting, etc.
if spell is not interruptible, it will return
Parameters
int32 spellType : type of spell to interrupt
bool delayed = true : skips if the spell is delayed
    {
        int spellType = Eluna::CHECKVAL<int>(L, 2);
        bool delayed = Eluna::CHECKVAL<bool>(L, 3, true);
        switch (spellType)
        {
        case 0:
            spellType = CURRENT_MELEE_SPELL;
            break;
        case 1:
            spellType = CURRENT_GENERIC_SPELL;
            break;
        case 2:
            spellType = CURRENT_CHANNELED_SPELL;
            break;
        case 3:
            spellType = CURRENT_AUTOREPEAT_SPELL;
            break;
        default:
            return luaL_argerror(L, 2, "valid CurrentSpellTypes expected");
        }
        unit->InterruptSpell((CurrentSpellTypes)spellType, delayed);
        return 0;
    }
References CURRENT_AUTOREPEAT_SPELL, CURRENT_CHANNELED_SPELL, CURRENT_GENERIC_SPELL, CURRENT_MELEE_SPELL, Unit::InterruptSpell(), and luaL_argerror().
IsAlive()
int LuaUnit::IsAlive (lua_State * L, Unit * unit)
Returns true if the [Unit] is alive.
Returns
bool isAlive
    {
        Eluna::Push(L, unit->IsAlive());
        return 1;
    }
References Unit::IsAlive(), and Eluna::Push().
IsArmorer()
int LuaUnit::IsArmorer (lua_State * L, Unit * unit)
Returns true if the [Unit] is an armorer and can repair equipment.
Returns
bool isArmorer
    {
        Eluna::Push(L, unit->IsArmorer());
        return 1;
    }
References Unit::IsArmorer(), and Eluna::Push().
IsAttackingPlayer()
int LuaUnit::IsAttackingPlayer (lua_State * L, Unit * unit)
Returns true if the [Unit] is attacking a player.
Returns
bool isAttackingPlayer
    {
        Eluna::Push(L, unit->isAttackingPlayer());
        return 1;
    }
References Unit::isAttackingPlayer(), and Eluna::Push().
IsAuctioneer()
int LuaUnit::IsAuctioneer (lua_State * L, Unit * unit)
Returns true if the [Unit] an auctioneer.
Returns
bool isAuctioneer
    {
        Eluna::Push(L, unit->IsAuctioner());
        return 1;
    }
References Unit::IsAuctioner(), and Eluna::Push().
IsBanker()
int LuaUnit::IsBanker (lua_State * L, Unit * unit)
Returns true if the [Unit] is a banker.
Returns
bool isBanker
    {
        Eluna::Push(L, unit->IsBanker());
        return 1;
    }
References Unit::IsBanker(), and Eluna::Push().
IsBattleMaster()
int LuaUnit::IsBattleMaster (lua_State * L, Unit * unit)
Returns true if the [Unit] is a battle master.
Returns
bool isBattleMaster
    {
        Eluna::Push(L, unit->IsBattleMaster());
        return 1;
    }
References Unit::IsBattleMaster(), and Eluna::Push().
IsCasting()
int LuaUnit::IsCasting (lua_State * L, Unit * unit)
Returns true if the [Unit] is casting a spell
Returns
bool isCasting
    {
        Eluna::Push(L, unit->HasUnitState(UNIT_STATE_CASTING));
        return 1;
    }
References Unit::HasUnitState(), Eluna::Push(), and UNIT_STATE_CASTING.
IsCharmed()
int LuaUnit::IsCharmed (lua_State * L, Unit * unit)
Returns true if the [Unit] is a charmed.
Returns
bool isCharmed
    {
        Eluna::Push(L, unit->IsCharmed());
        return 1;
    }
References Unit::IsCharmed(), and Eluna::Push().
IsDead()
int LuaUnit::IsDead (lua_State * L, Unit * unit)
Returns true if the [Unit] is dead.
Returns
bool isDead
    {
        Eluna::Push(L, unit->isDead());
        return 1;
    }
References Unit::isDead(), and Eluna::Push().
IsDying()
int LuaUnit::IsDying (lua_State * L, Unit * unit)
Returns true if the [Unit] is dying.
Returns
bool isDying
    {
        Eluna::Push(L, unit->isDying());
        return 1;
    }
References Unit::isDying(), and Eluna::Push().
IsFullHealth()
int LuaUnit::IsFullHealth (lua_State * L, Unit * unit)
Returns true if the [Unit] has full health.
Returns
bool hasFullHealth
    {
        Eluna::Push(L, unit->IsFullHealth());
        return 1;
    }
References Unit::IsFullHealth(), and Eluna::Push().
IsGossip()
int LuaUnit::IsGossip (lua_State * L, Unit * unit)
Returns true if the [Unit] is able to show a gossip window.
Returns
bool hasGossip
    {
        Eluna::Push(L, unit->IsGossip());
        return 1;
    }
References Unit::IsGossip(), and Eluna::Push().
IsGuildMaster()
int LuaUnit::IsGuildMaster (lua_State * L, Unit * unit)
Returns true if the [Unit] a guild master.
Returns
bool isGuildMaster
    {
        Eluna::Push(L, unit->IsGuildMaster());
        return 1;
    }
References Unit::IsGuildMaster(), and Eluna::Push().
IsInAccessiblePlaceFor()
int LuaUnit::IsInAccessiblePlaceFor (lua_State * L, Unit * unit)
Returns true if the [Unit] is in an accessible place for the given [Creature].
Parameters
[WorldObject] obj
float radius
Returns
bool isAccessible
    {
        Creature* creature = Eluna::CHECKOBJ<Creature>(L, 2);
        Eluna::Push(L, unit->isInAccessiblePlaceFor(creature));
        return 1;
    }
References Unit::isInAccessiblePlaceFor(), and Eluna::Push().
IsInCombat()
int LuaUnit::IsInCombat (lua_State * L, Unit * unit)
Returns true if the [Unit] is in combat.
Returns
bool inCombat
    {
        Eluna::Push(L, unit->IsInCombat());
        return 1;
    }
References Unit::IsInCombat(), and Eluna::Push().
IsInnkeeper()
int LuaUnit::IsInnkeeper (lua_State * L, Unit * unit)
Returns true if the [Unit] an innkeeper.
Returns
bool isInnkeeper
    {
        Eluna::Push(L, unit->IsInnkeeper());
        return 1;
    }
References Unit::IsInnkeeper(), and Eluna::Push().
IsInWater()
int LuaUnit::IsInWater (lua_State * L, Unit * unit)
Returns true if the [Unit] is in water.
Returns
bool inWater
    {
        Eluna::Push(L, unit->IsInWater());
        return 1;
    }
References Unit::IsInWater(), and Eluna::Push().
IsMounted()
int LuaUnit::IsMounted (lua_State * L, Unit * unit)
Returns true if the [Unit] is mounted.
Returns
bool isMounted
    {
        Eluna::Push(L, unit->IsMounted());
        return 1;
    }
References Unit::IsMounted(), and Eluna::Push().
IsOnVehicle()
int LuaUnit::IsOnVehicle (lua_State * L, Unit * unit)
Returns true if the [Unit] is on a [Vehicle].
Returns
bool isOnVehicle
    {
        Eluna::Push(L, unit->GetVehicle());
        return 1;
    }
References Unit::GetVehicle(), and Eluna::Push().
IsPvPFlagged()
int LuaUnit::IsPvPFlagged (lua_State * L, Unit * unit)
Returns true if the [Unit] flagged for PvP.
Returns
bool isPvP
    {
        Eluna::Push(L, unit->IsPvP());
        return 1;
    }
References Unit::IsPvP(), and Eluna::Push().
IsQuestGiver()
int LuaUnit::IsQuestGiver (lua_State * L, Unit * unit)
Returns true if the [Unit] is a quest giver.
Returns
bool questGiver
    {
        Eluna::Push(L, unit->IsQuestGiver());
        return 1;
    }
References Unit::IsQuestGiver(), and Eluna::Push().
IsRooted()
int LuaUnit::IsRooted (lua_State * L, Unit * unit)
Returns true if the [Unit] is rooted.
Returns
bool isRooted
    {
        Eluna::Push(L, unit->HasRootAura() || unit->HasUnitMovementFlag(MOVEMENTFLAG_ROOT));
        return 1;
    }
References Unit::HasRootAura(), Unit::HasUnitMovementFlag(), MOVEMENTFLAG_ROOT, and Eluna::Push().
IsServiceProvider()
int LuaUnit::IsServiceProvider (lua_State * L, Unit * unit)
Returns true if the [Unit] provides services like vendor, training and auction.
Returns
bool isTabardDesigner
    {
        Eluna::Push(L, unit->IsServiceProvider());
        return 1;
    }
References Unit::IsServiceProvider(), and Eluna::Push().
IsSpiritGuide()
int LuaUnit::IsSpiritGuide (lua_State * L, Unit * unit)
Returns true if the [Unit] is a spirit guide.
Returns
bool isSpiritGuide
    {
        Eluna::Push(L, unit->IsSpiritGuide());
        return 1;
    }
References Unit::IsSpiritGuide(), and Eluna::Push().
IsSpiritHealer()
int LuaUnit::IsSpiritHealer (lua_State * L, Unit * unit)
Returns true if the [Unit] is a spirit healer.
Returns
bool isSpiritHealer
    {
        Eluna::Push(L, unit->IsSpiritHealer());
        return 1;
    }
References Unit::IsSpiritHealer(), and Eluna::Push().
IsSpiritService()
int LuaUnit::IsSpiritService (lua_State * L, Unit * unit)
Returns true if the [Unit] is a spirit guide or spirit healer.
Returns
bool isSpiritService
    {
        Eluna::Push(L, unit->IsSpiritService());
        return 1;
    }
References Unit::IsSpiritService(), and Eluna::Push().
IsStandState()
int LuaUnit::IsStandState (lua_State * L, Unit * unit)
Returns true if the [Unit] is standing.
Returns
bool isStanding
    {
        Eluna::Push(L, unit->IsStandState());
        return 1;
    }
References Unit::IsStandState(), and Eluna::Push().
IsStopped()
int LuaUnit::IsStopped (lua_State * L, Unit * unit)
Returns true if the [Unit] is not moving.
Returns
bool notMoving
    {
        Eluna::Push(L, unit->IsStopped());
        return 1;
    }
References Unit::IsStopped(), and Eluna::Push().
IsTabardDesigner()
int LuaUnit::IsTabardDesigner (lua_State * L, Unit * unit)
Returns true if the [Unit] is a tabard designer.
Returns
bool isTabardDesigner
    {
        Eluna::Push(L, unit->IsTabardDesigner());
        return 1;
    }
References Unit::IsTabardDesigner(), and Eluna::Push().
IsTaxi()
int LuaUnit::IsTaxi (lua_State * L, Unit * unit)
Returns true if the [Unit] is a taxi master.
Returns
bool isTaxi
    {
        Eluna::Push(L, unit->IsTaxi());
        return 1;
    }
References Unit::IsTaxi(), and Eluna::Push().
IsTrainer()
int LuaUnit::IsTrainer (lua_State * L, Unit * unit)
Returns true if the [Unit] a trainer.
Returns
bool isTrainer
    {
        Eluna::Push(L, unit->IsTrainer());
        return 1;
    }
References Unit::IsTrainer(), and Eluna::Push().
IsUnderWater()
int LuaUnit::IsUnderWater (lua_State * L, Unit * unit)
Returns true if the [Unit] is under water.
Returns
bool underWater
    {
        Eluna::Push(L, unit->IsUnderWater());
        return 1;
    }
References Unit::IsUnderWater(), and Eluna::Push().
IsVendor()
int LuaUnit::IsVendor (lua_State * L, Unit * unit)
Returns true if the [Unit] is a vendor.
Returns
bool isVendor
    {
        Eluna::Push(L, unit->IsVendor());
        return 1;
    }
References Unit::IsVendor(), and Eluna::Push().
Kill()
int LuaUnit::Kill (lua_State * L, Unit * unit)
Makes the [Unit] kill the target [Unit]
Parameters
[Unit] target : [Unit] to kill
bool durLoss = true : when true, the target's items suffer durability loss
    {
        Unit* target = Eluna::CHECKOBJ<Unit>(L, 2);
        bool durLoss = Eluna::CHECKVAL<bool>(L, 3, true);
        Unit::Kill(unit, target, durLoss);
        return 0;
    }
References Unit::Kill().
ModifyPower()
int LuaUnit::ModifyPower (lua_State * L, Unit * unit)
modifies the [Unit]'s power amount for the given power type.
enum Powers
{
    POWER_MANA        = 0,
    POWER_RAGE        = 1,
    POWER_FOCUS       = 2,
    POWER_ENERGY      = 3,
    POWER_HAPPINESS   = 4,
    POWER_RUNE        = 5,
    POWER_RUNIC_POWER = 6,
    MAX_POWERS        = 7,
    POWER_ALL         = 127,         // default for class?
    POWER_HEALTH      = 0xFFFFFFFE   // (-2 as signed value)
};
Parameters
int32 amount : amount to modify
int type = -1 : a valid power type from [Powers] or -1 for the [Unit]'s current power type
    {
        int32 amt = Eluna::CHECKVAL<int32>(L, 2);
        int type = Eluna::CHECKVAL<int>(L, 3, -1);
        Powers power = PowerSelectorHelper(L, unit, type);
        unit->ModifyPower(power, amt);
        return 0;
    }
References Unit::ModifyPower(), and PowerSelectorHelper().
ModifyThreatPct()
int LuaUnit::ModifyThreatPct (lua_State * L, Unit * unit)
Modifies threat in pct to the [Unit] from the victim
Parameters
[Unit] victim : [Unit] that caused the threat
int32 percent : threat amount in pct
    {
        Unit* victim = Eluna::CHECKOBJ<Unit>(L, 2);
        int32 threatPct = Eluna::CHECKVAL<int32>(L, 3, true);
        unit->GetThreatMgr().ModifyThreatByPercent(victim, threatPct);
        return 0;
    }
References Unit::GetThreatMgr(), and ThreatMgr::ModifyThreatByPercent().
Mount()
int LuaUnit::Mount (lua_State * L, Unit * unit)
Mounts the [Unit] on the given displayID/modelID.
Parameters
uint32 displayId
    {
        uint32 displayId = Eluna::CHECKVAL<uint32>(L, 2);
        unit->Mount(displayId);
        return 0;
    }
References Unit::Mount().
MoveChase()
int LuaUnit::MoveChase (lua_State * L, Unit * unit)
The [Unit] will chase the target
Parameters
[Unit] target : target to chase
float dist = 0 : distance start chasing
float angle = 0
    {
        Unit* target = Eluna::CHECKOBJ<Unit>(L, 2);
        float dist = Eluna::CHECKVAL<float>(L, 3, 0.0f);
        float angle = Eluna::CHECKVAL<float>(L, 4, 0.0f);
        unit->GetMotionMaster()->MoveChase(target, dist, angle);
        return 0;
    }
References Unit::GetMotionMaster(), and MotionMaster::MoveChase().
MoveClear()
int LuaUnit::MoveClear (lua_State * L, Unit * unit)
Clears the [Unit]'s movement
Parameters
bool reset = true : clean movement
    {
        bool reset = Eluna::CHECKVAL<bool>(L, 2, true);
        unit->GetMotionMaster()->Clear(reset);
        return 0;
    }
References MotionMaster::Clear(), and Unit::GetMotionMaster().
MoveConfused()
int LuaUnit::MoveConfused (lua_State * , Unit * unit)
The [Unit] will move confused
    {
        unit->GetMotionMaster()->MoveConfused();
        return 0;
    }
References Unit::GetMotionMaster(), and MotionMaster::MoveConfused().
MoveExpire()
int LuaUnit::MoveExpire (lua_State * L, Unit * unit)
The [Unit]'s movement expires and clears movement
Parameters
bool reset = true : cleans movement
    {
        bool reset = Eluna::CHECKVAL<bool>(L, 2, true);
        unit->GetMotionMaster()->MovementExpired(reset);
        return 0;
    }
References Unit::GetMotionMaster(), and MotionMaster::MovementExpired().
MoveFleeing()
int LuaUnit::MoveFleeing (lua_State * L, Unit * unit)
The [Unit] will flee
Parameters
[Unit] target
uint32 time = 0 : flee delay
    {
        Unit* target = Eluna::CHECKOBJ<Unit>(L, 2);
        uint32 time = Eluna::CHECKVAL<uint32>(L, 3, 0);
        unit->GetMotionMaster()->MoveFleeing(target, time);
        return 0;
    }
References Unit::GetMotionMaster(), and MotionMaster::MoveFleeing().
MoveFollow()
int LuaUnit::MoveFollow (lua_State * L, Unit * unit)
The [Unit] will follow the target
Parameters
[Unit] target : target to follow
float dist = 0 : distance to start following
float angle = 0
    {
        Unit* target = Eluna::CHECKOBJ<Unit>(L, 2);
        float dist = Eluna::CHECKVAL<float>(L, 3, 0.0f);
        float angle = Eluna::CHECKVAL<float>(L, 4, 0.0f);
        unit->GetMotionMaster()->MoveFollow(target, dist, angle);
        return 0;
    }
References Unit::GetMotionMaster(), and MotionMaster::MoveFollow().
MoveHome()
int LuaUnit::MoveHome (lua_State * , Unit * unit)
The [Unit] will move to its set home location
    {
        unit->GetMotionMaster()->MoveTargetedHome();
        return 0;
    }
References Unit::GetMotionMaster(), and MotionMaster::MoveTargetedHome().
MoveIdle()
int LuaUnit::MoveIdle (lua_State * , Unit * unit)
The [Unit] will be idle
    {
        unit->GetMotionMaster()->MoveIdle();
        return 0;
    }
References Unit::GetMotionMaster(), and MotionMaster::MoveIdle().
MoveJump()
int LuaUnit::MoveJump (lua_State * L, Unit * unit)
Makes the [Unit] jump to the coordinates
Parameters
float x
float y
float z
float zSpeed : start velocity
float maxHeight : maximum height
uint32 id = 0 : unique movement Id
    {
        float x = Eluna::CHECKVAL<float>(L, 2);
        float y = Eluna::CHECKVAL<float>(L, 3);
        float z = Eluna::CHECKVAL<float>(L, 4);
        float zSpeed = Eluna::CHECKVAL<float>(L, 5);
        float maxHeight = Eluna::CHECKVAL<float>(L, 6);
        uint32 id = Eluna::CHECKVAL<uint32>(L, 7, 0);
        Position pos(x, y, z);
        unit->GetMotionMaster()->MoveJump(pos, zSpeed, maxHeight, id);
        return 0;
    }
References Unit::GetMotionMaster(), and MotionMaster::MoveJump().
MoveRandom()
int LuaUnit::MoveRandom (lua_State * L, Unit * unit)
The [Unit] will move at random
Parameters
float radius : limit on how far the [Unit] will move at random
    {
        float radius = Eluna::CHECKVAL<float>(L, 2);
        float x, y, z;
        unit->GetPosition(x, y, z);
        unit->GetMotionMaster()->MoveRandom(radius);
        return 0;
    }
References Unit::GetMotionMaster(), Position::GetPosition(), and MotionMaster::MoveRandom().
MoveStop()
int LuaUnit::MoveStop (lua_State * , Unit * unit)
Stops the [Unit]'s movement
    {
        unit->StopMoving();
        return 0;
    }
References Unit::StopMoving().
MoveTo()
int LuaUnit::MoveTo (lua_State * L, Unit * unit)
The [Unit] will move to the coordinates
Parameters
uint32 id : unique waypoint Id
float x
float y
float z
bool genPath = true : if true, generates path
    {
        uint32 id = Eluna::CHECKVAL<uint32>(L, 2);
        float x = Eluna::CHECKVAL<float>(L, 3);
        float y = Eluna::CHECKVAL<float>(L, 4);
        float z = Eluna::CHECKVAL<float>(L, 5);
        bool genPath = Eluna::CHECKVAL<bool>(L, 6, true);
        unit->GetMotionMaster()->MovePoint(id, x, y, z, genPath);
        return 0;
    }
References Unit::GetMotionMaster(), and MotionMaster::MovePoint().
NearTeleport()
int LuaUnit::NearTeleport (lua_State * L, Unit * unit)
Makes the [Unit] teleport to given coordinates within same map.
Parameters
float x
float y
float z
float o : orientation
    {
        float x = Eluna::CHECKVAL<float>(L, 2);
        float y = Eluna::CHECKVAL<float>(L, 3);
        float z = Eluna::CHECKVAL<float>(L, 4);
        float o = Eluna::CHECKVAL<float>(L, 5);
        unit->NearTeleportTo(x, y, z, o);
        return 0;
    }
References Unit::NearTeleportTo().
PerformEmote()
int LuaUnit::PerformEmote (lua_State * L, Unit * unit)
Makes the [Unit] perform the given emote.
Parameters
uint32 emoteId
    {
        unit->HandleEmoteCommand(Eluna::CHECKVAL<uint32>(L, 2));
        return 0;
    }
References Unit::HandleEmoteCommand().
PowerSelectorHelper()
Powers LuaUnit::PowerSelectorHelper (lua_State * L, Unit * unit, int powerType = -1)
    {
        if (powerType == -1)
            return unit->getPowerType();
        if (powerType < 0 || powerType >= int(MAX_POWERS))
            luaL_argerror(L, 2, "valid Powers expected");
        return (Powers)powerType;
    }
References Unit::getPowerType(), luaL_argerror(), and MAX_POWERS.
Referenced by GetMaxPower(), GetPower(), GetPowerPct(), ModifyPower(), SetMaxPower(), and SetPower().
RemoveAllAuras()
int LuaUnit::RemoveAllAuras (lua_State * , Unit * unit)
Removes all [Aura]'s from the [Unit].
Note: talents and racials are also auras, use with caution
    {
        unit->RemoveAllAuras();
        return 0;
    }
References Unit::RemoveAllAuras().
RemoveArenaAuras()
int LuaUnit::RemoveArenaAuras (lua_State * , Unit * unit)
Removes all positive visible [Aura]'s from the [Unit].
    {
        unit->RemoveArenaAuras();
        return 0;
    }
References Unit::RemoveArenaAuras().
RemoveAura()
int LuaUnit::RemoveAura (lua_State * L, Unit * unit)
Removes [Aura] of the given spell entry from the [Unit].
Parameters
uint32 spell : entry of a spell
    {
        uint32 spellId = Eluna::CHECKVAL<uint32>(L, 2);
        unit->RemoveAurasDueToSpell(spellId);
        return 0;
    }
References Unit::RemoveAurasDueToSpell().
SendChatMessageToPlayer()
int LuaUnit::SendChatMessageToPlayer (lua_State * L, Unit * unit)
Sends chat message to [Player]
Parameters
uint8 type : chat, whisper, etc
uint32 lang : language to speak
string msg
[Player] target
    {
        uint8 type = Eluna::CHECKVAL<uint8>(L, 2);
        uint32 lang = Eluna::CHECKVAL<uint32>(L, 3);
        std::string msg = Eluna::CHECKVAL<std::string>(L, 4);
        Player* target = Eluna::CHECKOBJ<Player>(L, 5);
        if (type >= MAX_CHAT_MSG_TYPE)
            return luaL_argerror(L, 2, "valid ChatMsg expected");
        if (lang >= LANGUAGES_COUNT)
            return luaL_argerror(L, 3, "valid Language expected");
        WorldPacket data;
        ChatHandler::BuildChatPacket(data, ChatMsg(type), Language(lang), unit, target, msg);
        target->GetSession()->SendPacket(&data);
        return 0;
    }
References ChatHandler::BuildChatPacket(), Player::GetSession(), LANGUAGES_COUNT, luaL_argerror(), MAX_CHAT_MSG_TYPE, and WorldSession::SendPacket().
SendUnitEmote()
int LuaUnit::SendUnitEmote (lua_State * L, Unit * unit)
The [Unit] will emote the message
Parameters
string msg : message for the [Unit] to emote
[Unit] receiver = nil : specific [Unit] to receive the message
bool bossEmote = false : is a boss emote
    {
        const char* msg = Eluna::CHECKVAL<const char*>(L, 2);
        Unit* receiver = Eluna::CHECKOBJ<Unit>(L, 3, false);
        bool bossEmote = Eluna::CHECKVAL<bool>(L, 4, false);
        if (std::string(msg).length() > 0)
            unit->TextEmote(msg, receiver, bossEmote);
        return 0;
    }
References Unit::TextEmote().
SendUnitSay()
int LuaUnit::SendUnitSay (lua_State * L, Unit * unit)
The [Unit] will say the message
Parameters
string msg : message for the [Unit] to say
uint32 language : language for the [Unit] to speak
    {
        const char* msg = Eluna::CHECKVAL<const char*>(L, 2);
        uint32 language = Eluna::CHECKVAL<uint32>(L, 3);
        if (std::string(msg).length() > 0)
            unit->Say(msg, (Language)language, unit);
        return 0;
    }
References Unit::Say().
SendUnitWhisper()
int LuaUnit::SendUnitWhisper (lua_State * L, Unit * unit)
The [Unit] will whisper the message to a [Player]
Parameters
string msg : message for the [Unit] to emote
uint32 lang : language for the [Unit] to speak
[Player] receiver : specific [Unit] to receive the message
bool bossWhisper = false : is a boss whisper
    {
        const char* msg = Eluna::CHECKVAL<const char*>(L, 2);
        uint32 lang = Eluna::CHECKVAL<uint32>(L, 3);
        (void)lang; // ensure that the variable is referenced in order to pass compiler checks
        Player* receiver = Eluna::CHECKOBJ<Player>(L, 4);
        bool bossWhisper = Eluna::CHECKVAL<bool>(L, 5, false);
        if (std::string(msg).length() > 0)
            unit->Whisper(msg, (Language)lang, receiver, bossWhisper);
        return 0;
    }
References Unit::Whisper().
SendUnitYell()
int LuaUnit::SendUnitYell (lua_State * L, Unit * unit)
The [Unit] will yell the message
Parameters
string msg : message for the [Unit] to yell
uint32 language : language for the [Unit] to speak
    {
        const char* msg = Eluna::CHECKVAL<const char*>(L, 2);
        uint32 language = Eluna::CHECKVAL<uint32>(L, 3);
        if (std::string(msg).length() > 0)
            unit->Yell(msg, (Language)language, unit);
        return 0;
    }
References Unit::Yell().
SetConfused()
int LuaUnit::SetConfused (lua_State * L, Unit * unit)
Confuses the [Unit], if 'false' specified, the [Unit] is no longer confused.
Parameters
bool apply = true
    {
        bool apply = Eluna::CHECKVAL<bool>(L, 2, true);
        unit->SetControlled(apply, UNIT_STATE_CONFUSED);
        return 0;
    }
References Unit::SetControlled(), and UNIT_STATE_CONFUSED.
SetCreatorGUID()
int LuaUnit::SetCreatorGUID (lua_State * L, Unit * unit)
Sets creator GUID
Parameters
ObjectGuid guid
    {
        ObjectGuid guid = Eluna::CHECKVAL<ObjectGuid>(L, 2);
        unit->SetCreatorGUID(guid);
        return 0;
    }
References Unit::SetCreatorGUID().
SetCritterGUID()
int LuaUnit::SetCritterGUID (lua_State * L, Unit * unit)
    {
        ObjectGuid guid = Eluna::CHECKVAL<ObjectGuid>(L, 2);
        unit->SetCritterGUID(guid);
        return 0;
    }
References Unit::SetCritterGUID().
SetDisplayId()
int LuaUnit::SetDisplayId (lua_State * L, Unit * unit)
Sets the [Unit]'s modelID.
Parameters
uint32 displayId
    {
        uint32 model = Eluna::CHECKVAL<uint32>(L, 2);
        unit->SetDisplayId(model);
        return 0;
    }
References Unit::SetDisplayId().
SetFacing()
int LuaUnit::SetFacing (lua_State * L, Unit * unit)
Sets the [Unit]'s facing/orientation.
Parameters
uint32 orientation
    {
        float o = Eluna::CHECKVAL<float>(L, 2);
        unit->SetFacingTo(o);
        return 0;
    }
References Unit::SetFacingTo().
SetFacingToObject()
int LuaUnit::SetFacingToObject (lua_State * L, Unit * unit)
Sets the [Unit] to face the given [WorldObject]'s direction.
Parameters
[WorldObject] target
    {
        WorldObject* obj = Eluna::CHECKOBJ<WorldObject>(L, 2);
        unit->SetFacingToObject(obj);
        return 0;
    }
References Unit::SetFacingToObject().
SetFaction()
int LuaUnit::SetFaction (lua_State * L, Unit * unit)
Sets the [Unit]'s faction.
Parameters
uint32 faction : new faction ID
    {
        uint32 factionId = Eluna::CHECKVAL<uint32>(L, 2);
        unit->SetFaction(factionId);
        return 0;
    }
References Unit::SetFaction().
SetFeared()
int LuaUnit::SetFeared (lua_State * L, Unit * unit)
Fears the [Unit], if 'false' specified, the [Unit] is no longer feared.
Parameters
bool apply = true
    {
        bool apply = Eluna::CHECKVAL<bool>(L, 2, true);
        unit->SetControlled(apply, UNIT_STATE_FLEEING);
        return 0;
    }
References Unit::SetControlled(), and UNIT_STATE_FLEEING.
SetFFA()
int LuaUnit::SetFFA (lua_State * L, Unit * unit)
Sets the [Unit]'s FFA flag on or off.
Parameters
bool apply = true
    {
        bool apply = Eluna::CHECKVAL<bool>(L, 2, true);
        if (apply)
        {
            unit->SetByteFlag(UNIT_FIELD_BYTES_2, 1, UNIT_BYTE2_FLAG_FFA_PVP);
            for (Unit::ControlSet::iterator itr = unit->m_Controlled.begin(); itr != unit->m_Controlled.end(); ++itr)
                (*itr)->SetByteValue(UNIT_FIELD_BYTES_2, 1, UNIT_BYTE2_FLAG_FFA_PVP);
        }
        else
        {
            unit->RemoveByteFlag(UNIT_FIELD_BYTES_2, 1, UNIT_BYTE2_FLAG_FFA_PVP);
            for (Unit::ControlSet::iterator itr = unit->m_Controlled.begin(); itr != unit->m_Controlled.end(); ++itr)
                (*itr)->RemoveByteFlag(UNIT_FIELD_BYTES_2, 1, UNIT_BYTE2_FLAG_FFA_PVP);
        }
        return 0;
    }
References Unit::m_Controlled, Object::RemoveByteFlag(), Object::SetByteFlag(), UNIT_BYTE2_FLAG_FFA_PVP, and UNIT_FIELD_BYTES_2.
SetHealth()
int LuaUnit::SetHealth (lua_State * L, Unit * unit)
Sets the [Unit]'s health.
Parameters
uint32 health : new health
    {
        uint32 amt = Eluna::CHECKVAL<uint32>(L, 2);
        unit->SetHealth(amt);
        return 0;
    }
References Unit::SetHealth().
SetImmuneTo()
int LuaUnit::SetImmuneTo (lua_State * L, Unit * unit)
Sets a mechanic immunity for the [Unit].
  MECHANIC_NONE             = 0,
  MECHANIC_CHARM            = 1,
  MECHANIC_DISORIENTED      = 2,
  MECHANIC_DISARM           = 3,
  MECHANIC_DISTRACT         = 4,
  MECHANIC_FEAR             = 5,
  MECHANIC_GRIP             = 6,
  MECHANIC_ROOT             = 7,
  MECHANIC_SLOW_ATTACK      = 8,
  MECHANIC_SILENCE          = 9,
  MECHANIC_SLEEP            = 10,
  MECHANIC_SNARE            = 11,
  MECHANIC_STUN             = 12,
  MECHANIC_FREEZE           = 13,
  MECHANIC_KNOCKOUT         = 14,
  MECHANIC_BLEED            = 15,
  MECHANIC_BANDAGE          = 16,
  MECHANIC_POLYMORPH        = 17,
  MECHANIC_BANISH           = 18,
  MECHANIC_SHIELD           = 19,
  MECHANIC_SHACKLE          = 20,
  MECHANIC_MOUNT            = 21,
  MECHANIC_INFECTED         = 22,
  MECHANIC_TURN             = 23,
  MECHANIC_HORROR           = 24,
  MECHANIC_INVULNERABILITY  = 25,
  MECHANIC_INTERRUPT        = 26,
  MECHANIC_DAZE             = 27,
  MECHANIC_DISCOVERY        = 28,
  MECHANIC_IMMUNE_SHIELD    = 29,     // Divine (Blessing) Shield/Protection and Ice Block
  MECHANIC_SAPPED           = 30,
  MECHANIC_ENRAGED          = 31
Parameters
int32 immunity : new value for the immunity mask
bool apply = true : if true, the immunity is applied, otherwise it is removed
    {
        int32 immunity = Eluna::CHECKVAL<int32>(L, 2);
        bool apply = Eluna::CHECKVAL<bool>(L, 3, true);
        unit->ApplySpellImmune(0, 5, immunity, apply);
        return 0;
    }
References Unit::ApplySpellImmune().
SetInCombatWith()
int LuaUnit::SetInCombatWith (lua_State * L, Unit * unit)
Sets the [Unit] in combat with the enemy [Unit].
Parameters
[Unit] enemy : the [Unit] to start combat with
    {
        Unit* enemy = Eluna::CHECKOBJ<Unit>(L, 2);
        unit->SetInCombatWith(enemy);
        return 0;
    }
References Unit::SetInCombatWith().
SetLevel()
int LuaUnit::SetLevel (lua_State * L, Unit * unit)
Sets the [Unit]'s level.
Parameters
uint8 level : new level
    {
        uint8 newlevel = Eluna::CHECKVAL<uint8>(L, 2);
        if (newlevel < 1)
            return luaL_argerror(L, 2, "level cannot be below 1");
        if (Player* player = unit->ToPlayer())
        {
            player->GiveLevel(newlevel);
            player->InitTalentForLevel();
            player->SetUInt32Value(PLAYER_XP, 0);
        }
        else
            unit->SetLevel(newlevel);
        return 0;
    }
References luaL_argerror(), PLAYER_XP, Unit::SetLevel(), and Object::ToPlayer().
SetMaxHealth()
int LuaUnit::SetMaxHealth (lua_State * L, Unit * unit)
Sets the [Unit]'s max health.
Parameters
uint32 maxHealth : new max health
    {
        uint32 amt = Eluna::CHECKVAL<uint32>(L, 2);
        unit->SetMaxHealth(amt);
        return 0;
    }
References Unit::SetMaxHealth().
SetMaxPower()
int LuaUnit::SetMaxPower (lua_State * L, Unit * unit)
Sets the [Unit]'s max power amount for the given power type.
enum Powers
{
    POWER_MANA        = 0,
    POWER_RAGE        = 1,
    POWER_FOCUS       = 2,
    POWER_ENERGY      = 3,
    POWER_HAPPINESS   = 4,
    POWER_RUNE        = 5,
    POWER_RUNIC_POWER = 6,
    MAX_POWERS        = 7,
    POWER_ALL         = 127,         // default for class?
    POWER_HEALTH      = 0xFFFFFFFE   // (-2 as signed value)
};
Parameters
int type = -1 : a valid power type from [Powers] or -1 for the [Unit]'s current power type
uint32 maxPower : new max power amount
    {
        int type = Eluna::CHECKVAL<int>(L, 2, -1);
        uint32 amt = Eluna::CHECKVAL<uint32>(L, 3);
        Powers power = PowerSelectorHelper(L, unit, type);
        unit->SetMaxPower(power, amt);
        return 0;
    }
References PowerSelectorHelper(), and Unit::SetMaxPower().
SetName()
int LuaUnit::SetName (lua_State * L, Unit * unit)
Sets the [Unit]'s name internally.
Parameters
string name : new name
    {
        const char* name = Eluna::CHECKVAL<const char*>(L, 2);
        if (std::string(name).length() > 0)
            unit->SetName(name);
        return 0;
    }
References WorldObject::SetName().
SetNativeDisplayId()
int LuaUnit::SetNativeDisplayId (lua_State * L, Unit * unit)
Sets the [Unit]'s native/default modelID.
Parameters
uint32 displayId
    {
        uint32 model = Eluna::CHECKVAL<uint32>(L, 2);
        unit->SetNativeDisplayId(model);
        return 0;
    }
References Unit::SetNativeDisplayId().
SetOwnerGUID()
int LuaUnit::SetOwnerGUID (lua_State * L, Unit * unit)
Sets the [Unit]'s owner GUID to given GUID.
Parameters
ObjectGuid guid : new owner guid
    {
        ObjectGuid guid = Eluna::CHECKVAL<ObjectGuid>(L, 2);
        unit->SetOwnerGUID(guid);
        return 0;
    }
References Unit::SetOwnerGUID().
SetPetGUID()
int LuaUnit::SetPetGUID (lua_State * L, Unit * unit)
Sets pet GUID
Parameters
ObjectGuid guid
    {
        ObjectGuid guid = Eluna::CHECKVAL<ObjectGuid>(L, 2);
        unit->SetPetGUID(guid);
        return 0;
    }
References Unit::SetPetGUID().
SetPower()
int LuaUnit::SetPower (lua_State * L, Unit * unit)
Sets the [Unit]'s power amount for the given power type.
enum Powers
{
    POWER_MANA        = 0,
    POWER_RAGE        = 1,
    POWER_FOCUS       = 2,
    POWER_ENERGY      = 3,
    POWER_HAPPINESS   = 4,
    POWER_RUNE        = 5,
    POWER_RUNIC_POWER = 6,
    MAX_POWERS        = 7,
    POWER_ALL         = 127,         // default for class?
    POWER_HEALTH      = 0xFFFFFFFE   // (-2 as signed value)
};
Parameters
uint32 amount : new power amount
int type = -1 : a valid power type from [Powers] or -1 for the [Unit]'s current power type
    {
        uint32 amt = Eluna::CHECKVAL<uint32>(L, 2);
        int type = Eluna::CHECKVAL<int>(L, 3, -1);
        Powers power = PowerSelectorHelper(L, unit, type);
        unit->SetPower(power, amt);
        return 0;
    }
References PowerSelectorHelper(), and Unit::SetPower().
SetPowerType()
int LuaUnit::SetPowerType (lua_State * L, Unit * unit)
Sets the [Unit]'s power type.
enum Powers
{
    POWER_MANA        = 0,
    POWER_RAGE        = 1,
    POWER_FOCUS       = 2,
    POWER_ENERGY      = 3,
    POWER_HAPPINESS   = 4,
    POWER_RUNE        = 5,
    POWER_RUNIC_POWER = 6,
    MAX_POWERS        = 7,
    POWER_ALL         = 127,         // default for class?
    POWER_HEALTH      = 0xFFFFFFFE   // (-2 as signed value)
};
Parameters
[Powers] type : a valid power type
    {
        uint32 type = Eluna::CHECKVAL<uint32>(L, 2);
        if (type >= int(MAX_POWERS))
            return luaL_argerror(L, 2, "valid Powers expected");
        unit->setPowerType((Powers)type);
        return 0;
    }
References luaL_argerror(), MAX_POWERS, and Unit::setPowerType().
SetPvP()
int LuaUnit::SetPvP (lua_State * L, Unit * unit)
Sets the [Unit]'s PvP on or off.
Parameters
bool apply = true : true if set on, false if off
    {
        bool apply = Eluna::CHECKVAL<bool>(L, 2, true);
        unit->SetPvP(apply);
        return 0;
    }
References Unit::SetPvP().
SetRooted()
int LuaUnit::SetRooted (lua_State * L, Unit * unit)
Roots the [Unit] to the ground, if 'false' specified, unroots the [Unit].
Parameters
bool apply = true
    {
        bool apply = Eluna::CHECKVAL<bool>(L, 2, true);
        unit->SetControlled(apply, UNIT_STATE_ROOT);
        return 0;
    }
References Unit::SetControlled(), and UNIT_STATE_ROOT.
SetSanctuary()
int LuaUnit::SetSanctuary (lua_State * L, Unit * unit)
Sets the [Unit]'s sanctuary flag on or off.
Parameters
bool apply = true
    {
        bool apply = Eluna::CHECKVAL<bool>(L, 2, true);
        if (apply)
        {
            unit->SetByteFlag(UNIT_FIELD_BYTES_2, 1, UNIT_BYTE2_FLAG_SANCTUARY);
            unit->CombatStop();
            unit->CombatStopWithPets();
        }
        else
            unit->RemoveByteFlag(UNIT_FIELD_BYTES_2, 1, UNIT_BYTE2_FLAG_SANCTUARY);
        return 0;
    }
References Unit::CombatStop(), Unit::CombatStopWithPets(), Object::RemoveByteFlag(), Object::SetByteFlag(), UNIT_BYTE2_FLAG_SANCTUARY, and UNIT_FIELD_BYTES_2.
SetSheath()
int LuaUnit::SetSheath (lua_State * L, Unit * unit)
Sets the [Unit]'s sheath state.
enum SheathState
{
    SHEATH_STATE_UNARMED  = 0, // non prepared weapon
    SHEATH_STATE_MELEE    = 1, // prepared melee weapon
    SHEATH_STATE_RANGED   = 2  // prepared ranged weapon
};
Parameters
[SheathState] sheathState : valid SheathState
    {
        uint32 sheathed = Eluna::CHECKVAL<uint32>(L, 2);
        if (sheathed >= MAX_SHEATH_STATE)
            return luaL_argerror(L, 2, "valid SheathState expected");
        unit->SetSheath((SheathState)sheathed);
        return 0;
    }
References luaL_argerror(), MAX_SHEATH_STATE, and Unit::SetSheath().
SetSpeed()
int LuaUnit::SetSpeed (lua_State * L, Unit * unit)
Sets the [Unit]'s speed of given [UnitMoveType] to given speed. If forced, packets sent to clients forcing the visual change.
enum UnitMoveType
{
    MOVE_WALK           = 0,
    MOVE_RUN            = 1,
    MOVE_RUN_BACK       = 2,
    MOVE_SWIM           = 3,
    MOVE_SWIM_BACK      = 4,
    MOVE_TURN_RATE      = 5,
    MOVE_FLIGHT         = 6,
    MOVE_FLIGHT_BACK    = 7,
    MOVE_PITCH_RATE     = 8
};
Parameters
[UnitMoveType] type
float rate
bool forced = false
    {
        uint32 type = Eluna::CHECKVAL<uint32>(L, 2);
        float rate = Eluna::CHECKVAL<float>(L, 3);
        bool forced = Eluna::CHECKVAL<bool>(L, 4, false);
        (void)forced; // ensure that the variable is referenced in order to pass compiler checks
        if (type >= MAX_MOVE_TYPE)
            return luaL_argerror(L, 2, "valid UnitMoveType expected");
        unit->SetSpeed((UnitMoveType)type, rate);
        return 0;
    }
References luaL_argerror(), MAX_MOVE_TYPE, and Unit::SetSpeed().
SetSpeedRate()
int LuaUnit::SetSpeedRate (lua_State * L, Unit * unit)
Sets the [Unit]'s speed rate of given [UnitMoveType] to given rate. If forced, packets sent to clients forcing the visual change.
enum UnitMoveType
{
    MOVE_WALK           = 0,
    MOVE_RUN            = 1,
    MOVE_RUN_BACK       = 2,
    MOVE_SWIM           = 3,
    MOVE_SWIM_BACK      = 4,
    MOVE_TURN_RATE      = 5,
    MOVE_FLIGHT         = 6,
    MOVE_FLIGHT_BACK    = 7,
    MOVE_PITCH_RATE     = 8
};
Parameters
[UnitMoveType] type
float rate
bool forced = false
    {
        uint32 type = Eluna::CHECKVAL<uint32>(L, 2);
        float rate = Eluna::CHECKVAL<float>(L, 3);
        if (type >= MAX_MOVE_TYPE)
            return luaL_argerror(L, 2, "valid UnitMoveType expected");
        unit->SetSpeedRate((UnitMoveType)type, rate);
        return 0;
    }
References luaL_argerror(), MAX_MOVE_TYPE, and Unit::SetSpeedRate().
SetStandState()
int LuaUnit::SetStandState (lua_State * L, Unit * unit)
Sets the [Unit]'s stand state
Parameters
uint8 state : stand state
    {
        uint8 state = Eluna::CHECKVAL<uint8>(L, 2);
        unit->SetStandState(state);
        return 0;
    }
References Unit::SetStandState().
SetWaterWalk()
int LuaUnit::SetWaterWalk (lua_State * L, Unit * unit)
Toggles (Sets) [Unit]'s water walking
Parameters
bool enable = true
    {
        bool enable = Eluna::CHECKVAL<bool>(L, 2, true);
        unit->SetWaterWalking(enable);
        return 0;
    }
References Unit::SetWaterWalking().
StopSpellCast()
int LuaUnit::StopSpellCast (lua_State * L, Unit * unit)
Stops the [Unit]'s current spell cast
Parameters
uint32 spell = 0 : entry of a spell
    {
        uint32 spellId = Eluna::CHECKVAL<uint32>(L, 2, 0);
        unit->CastStop(spellId);
        return 0;
    }
References Unit::CastStop().