AzerothCore Doxygen
ScriptMgr Class Reference
#include "ScriptMgr.h"
Public Types
typedef void(* ScriptLoaderCallbackType) ()
typedef void(* ModulesLoaderCallbackType) ()
Public Member Functions
void Initialize ()
void LoadDatabase ()
void FillSpellSummary ()
void CheckIfScriptsInDatabaseExist ()
std::string_view ScriptsVersion () const
void IncreaseScriptCount ()
void DecreaseScriptCount ()
uint32 GetScriptCount () const
void SetScriptLoader (ScriptLoaderCallbackType script_loader_callback)
void SetModulesLoader (ModulesLoaderCallbackType script_loader_callback)
void Unload ()
void CreateSpellScripts (uint32 spellId, std::list< SpellScript * > &scriptVector)
void CreateAuraScripts (uint32 spellId, std::list< AuraScript * > &scriptVector)
void CreateSpellScriptLoaders (uint32 spellId, std::vector< std::pair< SpellScriptLoader *, std::multimap< uint32, uint32 >::iterator > > &scriptVector)
void OnNetworkStart ()
void OnNetworkStop ()
void OnSocketOpen (std::shared_ptr< WorldSocket > socket)
void OnSocketClose (std::shared_ptr< WorldSocket > socket)
bool CanPacketReceive (WorldSession *session, WorldPacket const &packet)
bool CanPacketSend (WorldSession *session, WorldPacket const &packet)
void OnLoadCustomDatabaseTable ()
void OnOpenStateChange (bool open)
void OnBeforeConfigLoad (bool reload)
void OnAfterConfigLoad (bool reload)
void OnBeforeFinalizePlayerWorldSession (uint32 &cacheVersion)
void OnMotdChange (std::string &newMotd, LocaleConstant &locale)
void OnShutdownInitiate (ShutdownExitCode code, ShutdownMask mask)
void OnShutdownCancel ()
void OnWorldUpdate (uint32 diff)
void OnStartup ()
void OnShutdown ()
void OnBeforeWorldInitialized ()
void OnAfterUnloadAllMaps ()
void OnHonorCalculation (float &honor, uint8 level, float multiplier)
void OnGrayLevelCalculation (uint8 &grayLevel, uint8 playerLevel)
void OnColorCodeCalculation (XPColorChar &color, uint8 playerLevel, uint8 mobLevel)
void OnZeroDifferenceCalculation (uint8 &diff, uint8 playerLevel)
void OnBaseGainCalculation (uint32 &gain, uint8 playerLevel, uint8 mobLevel, ContentLevels content)
void OnGainCalculation (uint32 &gain, Player *player, Unit *unit)
void OnGroupRateCalculation (float &rate, uint32 count, bool isRaid)
void OnAfterArenaRatingCalculation (Battleground *const bg, int32 &winnerMatchmakerChange, int32 &loserMatchmakerChange, int32 &winnerChange, int32 &loserChange)
void OnBeforeUpdatingPersonalRating (int32 &mod, uint32 type)
void OnCreateMap (Map *map)
void OnDestroyMap (Map *map)
void OnLoadGridMap (Map *map, GridTerrainData *gmap, uint32 gx, uint32 gy)
void OnUnloadGridMap (Map *map, GridTerrainData *gmap, uint32 gx, uint32 gy)
void OnPlayerEnterMap (Map *map, Player *player)
void OnPlayerLeaveMap (Map *map, Player *player)
void OnMapUpdate (Map *map, uint32 diff)
InstanceScript * CreateInstanceScript (InstanceMap *map)
bool OnQuestAccept (Player *player, Item *item, Quest const *quest)
bool OnItemUse (Player *player, Item *item, SpellCastTargets const &targets)
bool OnItemExpire (Player *player, ItemTemplate const *proto)
bool OnItemRemove (Player *player, Item *item)
bool OnCastItemCombatSpell (Player *player, Unit *victim, SpellInfo const *spellInfo, Item *item)
void OnGossipSelect (Player *player, Item *item, uint32 sender, uint32 action)
void OnGossipSelectCode (Player *player, Item *item, uint32 sender, uint32 action, const char *code)
bool OnGossipHello (Player *player, Creature *creature)
bool OnGossipSelect (Player *player, Creature *creature, uint32 sender, uint32 action)
bool OnGossipSelectCode (Player *player, Creature *creature, uint32 sender, uint32 action, const char *code)
bool OnQuestAccept (Player *player, Creature *creature, Quest const *quest)
bool OnQuestSelect (Player *player, Creature *creature, Quest const *quest)
bool OnQuestComplete (Player *player, Creature *creature, Quest const *quest)
bool OnQuestReward (Player *player, Creature *creature, Quest const *quest, uint32 opt)
uint32 GetDialogStatus (Player *player, Creature *creature)
CreatureAI * GetCreatureAI (Creature *creature)
void OnCreatureUpdate (Creature *creature, uint32 diff)
void OnCreatureAddWorld (Creature *creature)
void OnCreatureRemoveWorld (Creature *creature)
void OnFfaPvpStateUpdate (Creature *creature, bool InPvp)
bool OnGossipHello (Player *player, GameObject *go)
bool OnGossipSelect (Player *player, GameObject *go, uint32 sender, uint32 action)
bool OnGossipSelectCode (Player *player, GameObject *go, uint32 sender, uint32 action, const char *code)
bool OnQuestAccept (Player *player, GameObject *go, Quest const *quest)
bool OnQuestReward (Player *player, GameObject *go, Quest const *quest, uint32 opt)
uint32 GetDialogStatus (Player *player, GameObject *go)
void OnGameObjectDestroyed (GameObject *go, Player *player)
void OnGameObjectDamaged (GameObject *go, Player *player)
void OnGameObjectModifyHealth (GameObject *go, Unit *attackerOrHealer, int32 &change, SpellInfo const *spellInfo)
void OnGameObjectLootStateChanged (GameObject *go, uint32 state, Unit *unit)
void OnGameObjectStateChanged (GameObject *go, uint32 state)
void OnGameObjectUpdate (GameObject *go, uint32 diff)
GameObjectAI * GetGameObjectAI (GameObject *go)
void OnGameObjectAddWorld (GameObject *go)
void OnGameObjectRemoveWorld (GameObject *go)
bool OnAreaTrigger (Player *player, AreaTrigger const *trigger)
Battleground * CreateBattleground (BattlegroundTypeId typeId)
OutdoorPvP * CreateOutdoorPvP (OutdoorPvPData const *data)
std::vector< Acore::ChatCommands::ChatCommandBuilder > GetChatCommands ()
void OnWeatherChange (Weather *weather, WeatherState state, float grade)
void OnWeatherUpdate (Weather *weather, uint32 diff)
void OnAuctionAdd (AuctionHouseObject *ah, AuctionEntry *entry)
void OnAuctionRemove (AuctionHouseObject *ah, AuctionEntry *entry)
void OnAuctionSuccessful (AuctionHouseObject *ah, AuctionEntry *entry)
void OnAuctionExpire (AuctionHouseObject *ah, AuctionEntry *entry)
void OnBeforeAuctionHouseMgrSendAuctionWonMail (AuctionHouseMgr *auctionHouseMgr, AuctionEntry *auction, Player *bidder, uint32 &bidder_accId, bool &sendNotification, bool &updateAchievementCriteria, bool &sendMail)
void OnBeforeAuctionHouseMgrSendAuctionSalePendingMail (AuctionHouseMgr *auctionHouseMgr, AuctionEntry *auction, Player *owner, uint32 &owner_accId, bool &sendMail)
void OnBeforeAuctionHouseMgrSendAuctionSuccessfulMail (AuctionHouseMgr *auctionHouseMgr, AuctionEntry *auction, Player *owner, uint32 &owner_accId, uint32 &profit, bool &sendNotification, bool &updateAchievementCriteria, bool &sendMail)
void OnBeforeAuctionHouseMgrSendAuctionExpiredMail (AuctionHouseMgr *auctionHouseMgr, AuctionEntry *auction, Player *owner, uint32 &owner_accId, bool &sendNotification, bool &sendMail)
void OnBeforeAuctionHouseMgrSendAuctionOutbiddedMail (AuctionHouseMgr *auctionHouseMgr, AuctionEntry *auction, Player *oldBidder, uint32 &oldBidder_accId, Player *newBidder, uint32 &newPrice, bool &sendNotification, bool &sendMail)
void OnBeforeAuctionHouseMgrSendAuctionCancelledToBidderMail (AuctionHouseMgr *auctionHouseMgr, AuctionEntry *auction, Player *bidder, uint32 &bidder_accId, bool &sendMail)
void OnBeforeAuctionHouseMgrUpdate ()
bool OnConditionCheck (Condition *condition, ConditionSourceInfo &sourceInfo)
void OnInstall (Vehicle *veh)
void OnUninstall (Vehicle *veh)
void OnReset (Vehicle *veh)
void OnInstallAccessory (Vehicle *veh, Creature *accessory)
void OnAddPassenger (Vehicle *veh, Unit *passenger, int8 seatId)
void OnRemovePassenger (Vehicle *veh, Unit *passenger)
void OnDynamicObjectUpdate (DynamicObject *dynobj, uint32 diff)
void OnAddPassenger (Transport *transport, Player *player)
void OnAddCreaturePassenger (Transport *transport, Creature *creature)
void OnRemovePassenger (Transport *transport, Player *player)
void OnTransportUpdate (Transport *transport, uint32 diff)
void OnRelocate (Transport *transport, uint32 waypointId, uint32 mapId, float x, float y, float z)
bool OnCriteriaCheck (uint32 scriptId, Player *source, Unit *target, uint32 criteria_id)
void OnPlayerJustDied (Player *player)
void OnPlayerCalculateTalentsPoints (Player const *player, uint32 &talentPointsForLevel)
void OnPlayerReleasedGhost (Player *player)
void OnPlayerSendInitialPacketsBeforeAddToMap (Player *player, WorldPacket &data)
void OnPlayerBeforeUpdate (Player *player, uint32 p_time)
void OnPlayerUpdate (Player *player, uint32 p_time)
void OnPlayerPVPKill (Player *killer, Player *killed)
void OnPlayerPVPFlagChange (Player *player, bool state)
void OnPlayerCreatureKill (Player *killer, Creature *killed)
void OnPlayerCreatureKilledByPet (Player *petOwner, Creature *killed)
void OnPlayerKilledByCreature (Creature *killer, Player *killed)
void OnPlayerLevelChanged (Player *player, uint8 oldLevel)
void OnPlayerFreeTalentPointsChanged (Player *player, uint32 newPoints)
void OnPlayerTalentsReset (Player *player, bool noCost)
void OnPlayerAfterSpecSlotChanged (Player *player, uint8 newSlot)
void OnPlayerMoneyChanged (Player *player, int32 &amount)
void OnPlayerBeforeLootMoney (Player *player, Loot *loot)
void OnPlayerGiveXP (Player *player, uint32 &amount, Unit *victim, uint8 xpSource)
bool OnPlayerReputationChange (Player *player, uint32 factionID, int32 &standing, bool incremental)
void OnPlayerReputationRankChange (Player *player, uint32 factionID, ReputationRank newRank, ReputationRank oldRank, bool increased)
void OnPlayerLearnSpell (Player *player, uint32 spellID)
void OnPlayerForgotSpell (Player *player, uint32 spellID)
void OnPlayerDuelRequest (Player *target, Player *challenger)
void OnPlayerDuelStart (Player *player1, Player *player2)
void OnPlayerDuelEnd (Player *winner, Player *loser, DuelCompleteType type)
void OnPlayerChat (Player *player, uint32 type, uint32 lang, std::string &msg)
void OnPlayerBeforeSendChatMessage (Player *player, uint32 &type, uint32 &lang, std::string &msg)
void OnPlayerChat (Player *player, uint32 type, uint32 lang, std::string &msg, Player *receiver)
void OnPlayerChat (Player *player, uint32 type, uint32 lang, std::string &msg, Group *group)
void OnPlayerChat (Player *player, uint32 type, uint32 lang, std::string &msg, Guild *guild)
void OnPlayerChat (Player *player, uint32 type, uint32 lang, std::string &msg, Channel *channel)
void OnPlayerEmote (Player *player, uint32 emote)
void OnPlayerTextEmote (Player *player, uint32 textEmote, uint32 emoteNum, ObjectGuid guid)
void OnPlayerSpellCast (Player *player, Spell *spell, bool skipCheck)
void OnPlayerLogin (Player *player)
void OnPlayerLoadFromDB (Player *player)
void OnPlayerBeforeLogout (Player *player)
void OnPlayerLogout (Player *player)
void OnPlayerCreate (Player *player)
void OnPlayerSave (Player *player)
void OnPlayerDelete (ObjectGuid guid, uint32 accountId)
void OnPlayerFailedDelete (ObjectGuid guid, uint32 accountId)
void OnPlayerBindToInstance (Player *player, Difficulty difficulty, uint32 mapid, bool permanent)
void OnPlayerUpdateZone (Player *player, uint32 newZone, uint32 newArea)
void OnPlayerUpdateArea (Player *player, uint32 oldArea, uint32 newArea)
bool OnPlayerBeforeTeleport (Player *player, uint32 mapid, float x, float y, float z, float orientation, uint32 options, Unit *target)
void OnPlayerUpdateFaction (Player *player)
void OnPlayerAddToBattleground (Player *player, Battleground *bg)
void OnPlayerQueueRandomDungeon (Player *player, uint32 &rDungeonId)
void OnPlayerRemoveFromBattleground (Player *player, Battleground *bg)
void OnPlayerAchievementComplete (Player *player, AchievementEntry const *achievement)
bool OnPlayerBeforeAchievementComplete (Player *player, AchievementEntry const *achievement)
void OnPlayerCriteriaProgress (Player *player, AchievementCriteriaEntry const *criteria)
bool OnPlayerBeforeCriteriaProgress (Player *player, AchievementCriteriaEntry const *criteria)
void OnPlayerAchievementSave (CharacterDatabaseTransaction trans, Player *player, uint16 achiId, CompletedAchievementData achiData)
void OnPlayerCriteriaSave (CharacterDatabaseTransaction trans, Player *player, uint16 critId, CriteriaProgress criteriaData)
void OnPlayerGossipSelect (Player *player, uint32 menu_id, uint32 sender, uint32 action)
void OnPlayerGossipSelectCode (Player *player, uint32 menu_id, uint32 sender, uint32 action, const char *code)
void OnPlayerBeingCharmed (Player *player, Unit *charmer, uint32 oldFactionId, uint32 newFactionId)
void OnPlayerAfterSetVisibleItemSlot (Player *player, uint8 slot, Item *item)
void OnPlayerAfterMoveItemFromInventory (Player *player, Item *it, uint8 bag, uint8 slot, bool update)
void OnPlayerEquip (Player *player, Item *it, uint8 bag, uint8 slot, bool update)
void OnPlayerJoinBG (Player *player)
void OnPlayerJoinArena (Player *player)
void OnPlayerGetMaxPersonalArenaRatingRequirement (Player const *player, uint32 minSlot, uint32 &maxArenaRating) const
void OnPlayerLootItem (Player *player, Item *item, uint32 count, ObjectGuid lootguid)
void OnPlayerBeforeFillQuestLootItem (Player *player, LootItem &item)
void OnPlayerStoreNewItem (Player *player, Item *item, uint32 count)
void OnPlayerCreateItem (Player *player, Item *item, uint32 count)
void OnPlayerQuestRewardItem (Player *player, Item *item, uint32 count)
bool OnPlayerCanPlaceAuctionBid (Player *player, AuctionEntry *auction)
void OnPlayerGroupRollRewardItem (Player *player, Item *item, uint32 count, RollVote voteType, Roll *roll)
bool OnPlayerBeforeOpenItem (Player *player, Item *item)
bool OnPlayerBeforeQuestComplete (Player *player, uint32 quest_id)
void OnPlayerQuestComputeXP (Player *player, Quest const *quest, uint32 &xpValue)
void OnPlayerBeforeDurabilityRepair (Player *player, ObjectGuid npcGUID, ObjectGuid itemGUID, float &discountMod, uint8 guildBank)
void OnPlayerBeforeBuyItemFromVendor (Player *player, ObjectGuid vendorguid, uint32 vendorslot, uint32 &item, uint8 count, uint8 bag, uint8 slot)
void OnPlayerBeforeStoreOrEquipNewItem (Player *player, uint32 vendorslot, uint32 &item, uint8 count, uint8 bag, uint8 slot, ItemTemplate const *pProto, Creature *pVendor, VendorItem const *crItem, bool bStore)
void OnPlayerAfterStoreOrEquipNewItem (Player *player, uint32 vendorslot, Item *item, uint8 count, uint8 bag, uint8 slot, ItemTemplate const *pProto, Creature *pVendor, VendorItem const *crItem, bool bStore)
void OnPlayerAfterUpdateMaxPower (Player *player, Powers &power, float &value)
void OnPlayerAfterUpdateMaxHealth (Player *player, float &value)
void OnPlayerBeforeUpdateAttackPowerAndDamage (Player *player, float &level, float &val2, bool ranged)
void OnPlayerAfterUpdateAttackPowerAndDamage (Player *player, float &level, float &base_attPower, float &attPowerMod, float &attPowerMultiplier, bool ranged)
void OnPlayerBeforeInitTalentForLevel (Player *player, uint8 &level, uint32 &talentPointsForLevel)
void OnPlayerFirstLogin (Player *player)
void OnPlayerSetMaxLevel (Player *player, uint32 &maxPlayerLevel)
void OnPlayerCompleteQuest (Player *player, Quest const *quest)
void OnPlayerBattlegroundDesertion (Player *player, BattlegroundDesertionType const desertionType)
bool OnPlayerCanJoinInBattlegroundQueue (Player *player, ObjectGuid BattlemasterGuid, BattlegroundTypeId BGTypeID, uint8 joinAsGroup, GroupJoinBattlegroundResult &err)
bool OnPlayerShouldBeRewardedWithMoneyInsteadOfExp (Player *player)
void OnPlayerBeforeTempSummonInitStats (Player *player, TempSummon *tempSummon, uint32 &duration)
void OnPlayerBeforeGuardianInitStatsForLevel (Player *player, Guardian *guardian, CreatureTemplate const *cinfo, PetType &petType)
void OnPlayerAfterGuardianInitStatsForLevel (Player *player, Guardian *guardian)
void OnPlayerBeforeLoadPetFromDB (Player *player, uint32 &petentry, uint32 &petnumber, bool &current, bool &forceLoadFromDB)
bool OnPlayerCanJoinInArenaQueue (Player *player, ObjectGuid BattlemasterGuid, uint8 arenaslot, BattlegroundTypeId BGTypeID, uint8 joinAsGroup, uint8 IsRated, GroupJoinBattlegroundResult &err)
bool OnPlayerCanBattleFieldPort (Player *player, uint8 arenaType, BattlegroundTypeId BGTypeID, uint8 action)
bool OnPlayerCanGroupInvite (Player *player, std::string &membername)
bool OnPlayerCanGroupAccept (Player *player, Group *group)
bool OnPlayerCanSellItem (Player *player, Item *item, Creature *creature)
bool OnPlayerCanSendMail (Player *player, ObjectGuid receiverGuid, ObjectGuid mailbox, std::string &subject, std::string &body, uint32 money, uint32 COD, Item *item)
void OnPlayerPetitionBuy (Player *player, Creature *creature, uint32 &charterid, uint32 &cost, uint32 &type)
void OnPlayerPetitionShowList (Player *player, Creature *creature, uint32 &CharterEntry, uint32 &CharterDispayID, uint32 &CharterCost)
void OnPlayerRewardKillRewarder (Player *player, KillRewarder *rewarder, bool isDungeon, float &rate)
bool OnPlayerCanGiveMailRewardAtGiveLevel (Player *player, uint8 level)
void OnPlayerDeleteFromDB (CharacterDatabaseTransaction trans, uint32 guid)
bool OnPlayerCanRepopAtGraveyard (Player *player)
std::optional< bool > OnPlayerIsClass (Player const *player, Classes playerClass, ClassContext context)
void OnPlayerGetMaxSkillValue (Player *player, uint32 skill, int32 &result, bool IsPure)
bool OnPlayerHasActivePowerType (Player const *player, Powers power)
void OnPlayerUpdateGatheringSkill (Player *player, uint32 skillId, uint32 currentLevel, uint32 gray, uint32 green, uint32 yellow, uint32 &gain)
void OnPlayerUpdateCraftingSkill (Player *player, SkillLineAbilityEntry const *skill, uint32 currentLevel, uint32 &gain)
bool OnPlayerUpdateFishingSkill (Player *player, int32 skill, int32 zone_skill, int32 chance, int32 roll)
bool OnPlayerCanAreaExploreAndOutdoor (Player *player)
void OnPlayerVictimRewardBefore (Player *player, Player *victim, uint32 &killer_title, uint32 &victim_title)
void OnPlayerVictimRewardAfter (Player *player, Player *victim, uint32 &killer_title, uint32 &victim_rank, float &honor_f)
void OnPlayerCustomScalingStatValueBefore (Player *player, ItemTemplate const *proto, uint8 slot, bool apply, uint32 &CustomScalingStatValue)
void OnPlayerCustomScalingStatValue (Player *player, ItemTemplate const *proto, uint32 &statType, int32 &val, uint8 itemProtoStatNumber, uint32 ScalingStatValue, ScalingStatValuesEntry const *ssv)
void OnPlayerApplyItemModsBefore (Player *player, uint8 slot, bool apply, uint8 itemProtoStatNumber, uint32 statType, int32 &val)
void OnPlayerApplyEnchantmentItemModsBefore (Player *player, Item *item, EnchantmentSlot slot, bool apply, uint32 enchant_spell_id, uint32 &enchant_amount)
void OnPlayerApplyWeaponDamage (Player *player, uint8 slot, ItemTemplate const *proto, float &minDamage, float &maxDamage, uint8 damageIndex)
bool OnPlayerCanArmorDamageModifier (Player *player)
void OnPlayerGetFeralApBonus (Player *player, int32 &feral_bonus, int32 dpsMod, ItemTemplate const *proto, ScalingStatValuesEntry const *ssv)
bool OnPlayerCanApplyWeaponDependentAuraDamageMod (Player *player, Item *item, WeaponAttackType attackType, AuraEffect const *aura, bool apply)
bool OnPlayerCanApplyEquipSpell (Player *player, SpellInfo const *spellInfo, Item *item, bool apply, bool form_change)
bool OnPlayerCanApplyEquipSpellsItemSet (Player *player, ItemSetEffect *eff)
bool OnPlayerCanCastItemCombatSpell (Player *player, Unit *target, WeaponAttackType attType, uint32 procVictim, uint32 procEx, Item *item, ItemTemplate const *proto)
bool OnPlayerCanCastItemUseSpell (Player *player, Item *item, SpellCastTargets const &targets, uint8 cast_count, uint32 glyphIndex)
void OnPlayerApplyAmmoBonuses (Player *player, ItemTemplate const *proto, float &currentAmmoDPS)
bool OnPlayerCanEquipItem (Player *player, uint8 slot, uint16 &dest, Item *pItem, bool swap, bool not_loading)
bool OnPlayerCanUnequipItem (Player *player, uint16 pos, bool swap)
bool OnPlayerCanUseItem (Player *player, ItemTemplate const *proto, InventoryResult &result)
bool OnPlayerCanSaveEquipNewItem (Player *player, Item *item, uint16 pos, bool update)
bool OnPlayerCanApplyEnchantment (Player *player, Item *item, EnchantmentSlot slot, bool apply, bool apply_dur, bool ignore_condition)
void OnPlayerGetQuestRate (Player *player, float &result)
bool OnPlayerPassedQuestKilledMonsterCredit (Player *player, Quest const *qinfo, uint32 entry, uint32 real_entry, ObjectGuid guid)
bool OnPlayerCheckItemInSlotAtLoadInventory (Player *player, Item *item, uint8 slot, uint8 &err, uint16 &dest)
bool OnPlayerNotAvoidSatisfy (Player *player, DungeonProgressionRequirements const *ar, uint32 target_map, bool report)
bool OnPlayerNotVisibleGloballyFor (Player *player, Player const *u)
void OnPlayerGetArenaPersonalRating (Player *player, uint8 slot, uint32 &result)
void OnPlayerFfaPvpStateUpdate (Player *player, bool result)
void OnPlayerGetArenaTeamId (Player *player, uint8 slot, uint32 &result)
void OnPlayerIsFFAPvP (Player *player, bool &result)
void OnPlayerIsPvP (Player *player, bool &result)
void OnPlayerGetMaxSkillValueForLevel (Player *player, uint16 &result)
bool OnPlayerNotSetArenaTeamInfoField (Player *player, uint8 slot, ArenaTeamInfoType type, uint32 value)
bool OnPlayerCanJoinLfg (Player *player, uint8 roles, lfg::LfgDungeonSet &dungeons, const std::string &comment)
bool OnPlayerCanEnterMap (Player *player, MapEntry const *entry, InstanceTemplate const *instance, MapDifficulty const *mapDiff, bool loginCheck)
bool OnPlayerCanInitTrade (Player *player, Player *target)
bool OnPlayerCanSetTradeItem (Player *player, Item *tradedItem, uint8 tradeSlot)
void OnPlayerSetServerSideVisibility (Player *player, ServerSideVisibilityType &type, AccountTypes &sec)
void OnPlayerSetServerSideVisibilityDetect (Player *player, ServerSideVisibilityType &type, AccountTypes &sec)
void OnPlayerResurrect (Player *player, float restore_percent, bool applySickness)
void OnPlayerBeforeChooseGraveyard (Player *player, TeamId teamId, bool nearCorpse, uint32 &graveyardOverride)
bool OnPlayerCanUseChat (Player *player, uint32 type, uint32 language, std::string &msg)
bool OnPlayerCanUseChat (Player *player, uint32 type, uint32 language, std::string &msg, Player *receiver)
bool OnPlayerCanUseChat (Player *player, uint32 type, uint32 language, std::string &msg, Group *group)
bool OnPlayerCanUseChat (Player *player, uint32 type, uint32 language, std::string &msg, Guild *guild)
bool OnPlayerCanUseChat (Player *player, uint32 type, uint32 language, std::string &msg, Channel *channel)
void OnPlayerLearnTalents (Player *player, uint32 talentId, uint32 talentRank, uint32 spellid)
void OnPlayerEnterCombat (Player *player, Unit *enemy)
void OnPlayerLeaveCombat (Player *player)
void OnPlayerQuestAbandon (Player *player, uint32 questId)
bool OnPlayerCanSendErrorAlreadyLooted (Player *player)
void OnPlayerAfterCreatureLoot (Player *player)
void OnPlayerAfterCreatureLootMoney (Player *player)
bool OnPlayerCanFlyInZone (Player *player, uint32 mapId, uint32 zoneId, SpellInfo const *bySpell)
bool OnPlayerCanUpdateSkill (Player *player, uint32 skillId)
void OnPlayerBeforeUpdateSkill (Player *player, uint32 skill_id, uint32 &value, uint32 max, uint32 step)
void OnPlayerUpdateSkill (Player *player, uint32 skillId, uint32 value, uint32 max, uint32 step, uint32 newValue)
bool OnPlayerCanResurrect (Player *player)
void AnticheatSetCanFlybyServer (Player *player, bool apply)
void AnticheatSetUnderACKmount (Player *player)
void AnticheatSetRootACKUpd (Player *player)
void AnticheatUpdateMovementInfo (Player *player, MovementInfo const &movementInfo)
void AnticheatSetJumpingbyOpcode (Player *player, bool jump)
bool AnticheatHandleDoubleJump (Player *player, Unit *mover)
bool AnticheatCheckMovementInfo (Player *player, MovementInfo const &movementInfo, Unit *mover, bool jump)
void OnAccountLogin (uint32 accountId)
void OnBeforeAccountDelete (uint32 accountId)
void OnLastIpUpdate (uint32 accountId, std::string ip)
void OnFailedAccountLogin (uint32 accountId)
void OnEmailChange (uint32 accountId)
void OnFailedEmailChange (uint32 accountId)
void OnPasswordChange (uint32 accountId)
void OnFailedPasswordChange (uint32 accountId)
bool CanAccountCreateCharacter (uint32 accountId, uint8 charRace, uint8 charClass)
void OnGuildAddMember (Guild *guild, Player *player, uint8 &plRank)
void OnGuildRemoveMember (Guild *guild, Player *player, bool isDisbanding, bool isKicked)
void OnGuildMOTDChanged (Guild *guild, const std::string &newMotd)
void OnGuildInfoChanged (Guild *guild, const std::string &newInfo)
void OnGuildCreate (Guild *guild, Player *leader, const std::string &name)
void OnGuildDisband (Guild *guild)
void OnGuildMemberWitdrawMoney (Guild *guild, Player *player, uint32 &amount, bool isRepair)
void OnGuildMemberDepositMoney (Guild *guild, Player *player, uint32 &amount)
void OnGuildItemMove (Guild *guild, Player *player, Item *pItem, bool isSrcBank, uint8 srcContainer, uint8 srcSlotId, bool isDestBank, uint8 destContainer, uint8 destSlotId)
void OnGuildEvent (Guild *guild, uint8 eventType, ObjectGuid::LowType playerGuid1, ObjectGuid::LowType playerGuid2, uint8 newRank)
void OnGuildBankEvent (Guild *guild, uint8 eventType, uint8 tabId, ObjectGuid::LowType playerGuid, uint32 itemOrMoney, uint16 itemStackCount, uint8 destTabId)
bool CanGuildSendBankList (Guild const *guild, WorldSession *session, uint8 tabId, bool sendAllSlots)
void OnGroupAddMember (Group *group, ObjectGuid guid)
void OnGroupInviteMember (Group *group, ObjectGuid guid)
void OnGroupRemoveMember (Group *group, ObjectGuid guid, RemoveMethod method, ObjectGuid kicker, const char *reason)
void OnGroupChangeLeader (Group *group, ObjectGuid newLeaderGuid, ObjectGuid oldLeaderGuid)
void OnGroupDisband (Group *group)
bool CanGroupJoinBattlegroundQueue (Group const *group, Player *member, Battleground const *bgTemplate, uint32 MinPlayerCount, bool isRated, uint32 arenaSlot)
void OnCreate (Group *group, Player *leader)
void OnGlobalItemDelFromDB (CharacterDatabaseTransaction trans, ObjectGuid::LowType itemGuid)
void OnGlobalMirrorImageDisplayItem (Item const *item, uint32 &display)
void OnBeforeUpdateArenaPoints (ArenaTeam *at, std::map< ObjectGuid, uint32 > &ap)
void OnAfterRefCount (Player const *player, Loot &loot, bool canRate, uint16 lootMode, LootStoreItem *LootStoreItem, uint32 &maxcount, LootStore const &store)
void OnAfterCalculateLootGroupAmount (Player const *player, Loot &loot, uint16 lootMode, uint32 &groupAmount, LootStore const &store)
void OnBeforeDropAddItem (Player const *player, Loot &loot, bool canRate, uint16 lootMode, LootStoreItem *LootStoreItem, LootStore const &store)
bool OnItemRoll (Player const *player, LootStoreItem const *LootStoreItem, float &chance, Loot &loot, LootStore const &store)
bool OnBeforeLootEqualChanced (Player const *player, LootStoreItemList EqualChanced, Loot &loot, LootStore const &store)
void OnInitializeLockedDungeons (Player *player, uint8 &level, uint32 &lockData, lfg::LFGDungeonData const *dungeon)
void OnAfterInitializeLockedDungeons (Player *player)
void OnAfterUpdateEncounterState (Map *map, EncounterCreditType type, uint32 creditEntry, Unit *source, Difficulty difficulty_fixed, DungeonEncounterList const *encounters, uint32 dungeonCompleted, bool updated)
void OnBeforeWorldObjectSetPhaseMask (WorldObject const *worldObject, uint32 &oldPhaseMask, uint32 &newPhaseMask, bool &useCombinedPhases, bool &update)
bool OnIsAffectedBySpellModCheck (SpellInfo const *affectSpell, SpellInfo const *checkSpell, SpellModifier const *mod)
bool OnSpellHealingBonusTakenNegativeModifiers (Unit const *target, Unit const *caster, SpellInfo const *spellInfo, float &val)
void OnLoadSpellCustomAttr (SpellInfo *spell)
bool OnAllowedForPlayerLootCheck (Player const *player, ObjectGuid source)
bool OnAllowedToLootContainerCheck (Player const *player, ObjectGuid source)
void OnInstanceIdRemoved (uint32 instanceId)
Called when an instance Id is deleted, usually because it expired or no players are bound to it anymore.
void OnBeforeSetBossState (uint32 id, EncounterState newState, EncounterState oldState, Map *instance)
Called when any raid boss has their state updated (e.g. pull, reset, kill).
void AfterInstanceGameObjectCreate (Map *instance, GameObject *go)
Called when a game object is created inside an instance.
uint32 IncreaseScheduledScriptsCount ()
uint32 DecreaseScheduledScriptCount ()
uint32 DecreaseScheduledScriptCount (std::size_t count)
bool IsScriptScheduled () const
void OnHeal (Unit *healer, Unit *reciever, uint32 &gain)
void OnDamage (Unit *attacker, Unit *victim, uint32 &damage)
void ModifyPeriodicDamageAurasTick (Unit *target, Unit *attacker, uint32 &damage, SpellInfo const *spellInfo)
void ModifyMeleeDamage (Unit *target, Unit *attacker, uint32 &damage)
void ModifySpellDamageTaken (Unit *target, Unit *attacker, int32 &damage, SpellInfo const *spellInfo)
void ModifyHealReceived (Unit *target, Unit *healer, uint32 &addHealth, SpellInfo const *spellInfo)
uint32 DealDamage (Unit *AttackerUnit, Unit *pVictim, uint32 damage, DamageEffectType damagetype)
void OnBeforeRollMeleeOutcomeAgainst (Unit const *attacker, Unit const *victim, WeaponAttackType attType, int32 &attackerMaxSkillValueForLevel, int32 &victimMaxSkillValueForLevel, int32 &attackerWeaponSkill, int32 &victimDefenseSkill, int32 &crit_chance, int32 &miss_chance, int32 &dodge_chance, int32 &parry_chance, int32 &block_chance)
void OnAuraApply (Unit *, Aura *)
void OnAuraRemove (Unit *unit, AuraApplication *aurApp, AuraRemoveMode mode)
bool IfNormalReaction (Unit const *unit, Unit const *target, ReputationRank &repRank)
bool IsNeedModSpellDamagePercent (Unit const *unit, AuraEffect *auraEff, float &doneTotalMod, SpellInfo const *spellProto)
bool IsNeedModMeleeDamagePercent (Unit const *unit, AuraEffect *auraEff, float &doneTotalMod, SpellInfo const *spellProto)
bool IsNeedModHealPercent (Unit const *unit, AuraEffect *auraEff, float &doneTotalMod, SpellInfo const *spellProto)
bool CanSetPhaseMask (Unit const *unit, uint32 newPhaseMask, bool update)
bool IsCustomBuildValuesUpdate (Unit const *unit, uint8 updateType, ByteBuffer &fieldBuffer, Player const *target, uint16 index)
bool ShouldTrackValuesUpdatePosByIndex (Unit const *unit, uint8 updateType, uint16 index)
void OnPatchValuesUpdate (Unit const *unit, ByteBuffer &valuesUpdateBuf, BuildValuesCachePosPointers &posPointers, Player *target)
void OnUnitUpdate (Unit *unit, uint32 diff)
void OnDisplayIdChange (Unit *unit, uint32 displayId)
void OnUnitEnterEvadeMode (Unit *unit, uint8 why)
void OnUnitEnterCombat (Unit *unit, Unit *victim)
void OnUnitDeath (Unit *unit, Unit *killer)
void OnUnitSetShapeshiftForm (Unit *unit, uint8 form)
void OnPlayerMove (Player *player, MovementInfo movementInfo, uint32 opcode)
void OnBeforeCreatureSelectLevel (const CreatureTemplate *cinfo, Creature *creature, uint8 &level)
void Creature_SelectLevel (const CreatureTemplate *cinfo, Creature *creature)
void OnCreatureSaveToDB (Creature *creature)
void OnGameObjectSaveToDB (GameObject *go)
void OnBeforeCreateInstanceScript (InstanceMap *instanceMap, InstanceScript **instanceData, bool load, std::string data, uint32 completedEncounterMask)
void OnDestroyInstance (MapInstanced *mapInstanced, Map *map)
void OnBattlegroundStart (Battleground *bg)
void OnBattlegroundEndReward (Battleground *bg, Player *player, TeamId winnerTeamId)
void OnBattlegroundUpdate (Battleground *bg, uint32 diff)
void OnBattlegroundAddPlayer (Battleground *bg, Player *player)
void OnBattlegroundBeforeAddPlayer (Battleground *bg, Player *player)
void OnBattlegroundRemovePlayerAtLeave (Battleground *bg, Player *player)
void OnQueueUpdate (BattlegroundQueue *queue, uint32 diff, BattlegroundTypeId bgTypeId, BattlegroundBracketId bracket_id, uint8 arenaType, bool isRated, uint32 arenaRating)
bool OnQueueUpdateValidity (BattlegroundQueue *queue, uint32 diff, BattlegroundTypeId bgTypeId, BattlegroundBracketId bracket_id, uint8 arenaType, bool isRated, uint32 arenaRating)
void OnAddGroup (BattlegroundQueue *queue, GroupQueueInfo *ginfo, uint32 &index, Player *leader, Group *group, BattlegroundTypeId bgTypeId, PvPDifficultyEntry const *bracketEntry, uint8 arenaType, bool isRated, bool isPremade, uint32 arenaRating, uint32 matchmakerRating, uint32 arenaTeamId, uint32 opponentsArenaTeamId)
bool CanFillPlayersToBG (BattlegroundQueue *queue, Battleground *bg, BattlegroundBracketId bracket_id)
bool IsCheckNormalMatch (BattlegroundQueue *queue, Battleground *bgTemplate, BattlegroundBracketId bracket_id, uint32 minPlayers, uint32 maxPlayers)
bool CanSendMessageBGQueue (BattlegroundQueue *queue, Player *leader, Battleground *bg, PvPDifficultyEntry const *bracketEntry)
bool OnBeforeSendJoinMessageArenaQueue (BattlegroundQueue *queue, Player *leader, GroupQueueInfo *ginfo, PvPDifficultyEntry const *bracketEntry, bool isRated)
bool OnBeforeSendExitMessageArenaQueue (BattlegroundQueue *queue, GroupQueueInfo *ginfo)
void OnBattlegroundEnd (Battleground *bg, TeamId winnerTeamId)
void OnBattlegroundDestroy (Battleground *bg)
void OnBattlegroundCreate (Battleground *bg)
void OnGetSlotByType (const uint32 type, uint8 &slot)
void OnGetArenaPoints (ArenaTeam *at, float &points)
void OnArenaTypeIDToQueueID (const BattlegroundTypeId bgTypeId, const uint8 arenaType, uint32 &queueTypeID)
void OnArenaQueueIdToArenaType (const BattlegroundQueueTypeId bgQueueTypeId, uint8 &ArenaType)
void OnSetArenaMaxPlayersPerTeam (const uint8 arenaType, uint32 &maxPlayerPerTeam)
void OnCalcMaxDuration (Aura const *aura, int32 &maxDuration)
bool CanModAuraEffectDamageDone (AuraEffect const *auraEff, Unit *target, AuraApplication const *aurApp, uint8 mode, bool apply)
bool CanModAuraEffectModDamagePercentDone (AuraEffect const *auraEff, Unit *target, AuraApplication const *aurApp, uint8 mode, bool apply)
void OnSpellCheckCast (Spell *spell, bool strict, SpellCastResult &res)
bool CanPrepare (Spell *spell, SpellCastTargets const *targets, AuraEffect const *triggeredByAura)
bool CanScalingEverything (Spell *spell)
bool CanSelectSpecTalent (Spell *spell)
void OnScaleAuraUnitAdd (Spell *spell, Unit *target, uint32 effectMask, bool checkIfValid, bool implicit, uint8 auraScaleMask, TargetInfo &targetInfo)
void OnRemoveAuraScaleTargets (Spell *spell, TargetInfo &targetInfo, uint8 auraScaleMask, bool &needErase)
void OnBeforeAuraRankForLevel (SpellInfo const *spellInfo, SpellInfo const *latestSpellInfo, uint8 level)
void OnDummyEffect (WorldObject *caster, uint32 spellID, SpellEffIndex effIndex, GameObject *gameObjTarget)
void OnDummyEffect (WorldObject *caster, uint32 spellID, SpellEffIndex effIndex, Creature *creatureTarget)
void OnDummyEffect (WorldObject *caster, uint32 spellID, SpellEffIndex effIndex, Item *itemTarget)
void OnSpellCastCancel (Spell *spell, Unit *caster, SpellInfo const *spellInfo, bool bySelf)
void OnSpellCast (Spell *spell, Unit *caster, SpellInfo const *spellInfo, bool skipCheck)
void OnSpellPrepare (Spell *spell, Unit *caster, SpellInfo const *spellInfo)
void OnGameEventStart (uint16 EventID)
void OnGameEventStop (uint16 EventID)
void OnGameEventCheck (uint16 EventID)
void OnBeforeMailDraftSendMailTo (MailDraft *mailDraft, MailReceiver const &receiver, MailSender const &sender, MailCheckMask &checked, uint32 &deliver_delay, uint32 &custom_expiration, bool &deleteMailItemsFromDB, bool &sendMail)
void SetRealmCompleted (AchievementEntry const *achievement)
bool IsCompletedCriteria (AchievementMgr *mgr, AchievementCriteriaEntry const *achievementCriteria, AchievementEntry const *achievement, CriteriaProgress const *progress)
bool IsRealmCompleted (AchievementGlobalMgr const *globalmgr, AchievementEntry const *achievement, std::chrono::system_clock::time_point completionTime)
void OnBeforeCheckCriteria (AchievementMgr *mgr, AchievementCriteriaEntryList const *achievementCriteriaList)
bool CanCheckCriteria (AchievementMgr *mgr, AchievementCriteriaEntry const *achievementCriteria)
void OnInitStatsForLevel (Guardian *guardian, uint8 petlevel)
void OnCalculateMaxTalentPointsForLevel (Pet *pet, uint8 level, uint8 &points)
bool CanUnlearnSpellSet (Pet *pet, uint32 level, uint32 spell)
bool CanUnlearnSpellDefault (Pet *pet, SpellInfo const *spellInfo)
bool CanResetTalents (Pet *pet)
bool CanAddMember (ArenaTeam *team, ObjectGuid PlayerGuid)
void OnGetPoints (ArenaTeam *team, uint32 memberRating, float &points)
bool CanSaveToDB (ArenaTeam *team)
bool OnBeforeArenaCheckWinConditions (Battleground *const bg)
void OnArenaStart (Battleground *const bg)
void OnConstructObject (Object *origin)
void OnDestructObject (Object *origin)
void OnConstructPlayer (Player *origin)
void OnDestructPlayer (Player *origin)
void OnConstructGroup (Group *origin)
void OnDestructGroup (Group *origin)
void OnConstructInstanceSave (InstanceSave *origin)
void OnDestructInstanceSave (InstanceSave *origin)
void OnItemCreate (Item *item, ItemTemplate const *itemProto, Player const *owner)
bool CanApplySoulboundFlag (Item *item, ItemTemplate const *proto)
bool CanItemApplyEquipSpell (Player *player, Item *item)
bool CanSendAuctionHello (WorldSession const *session, ObjectGuid guid, Creature *creature)
void ValidateSpellAtCastSpell (Player *player, uint32 &oldSpellId, uint32 &spellId, uint8 &castCount, uint8 &castFlags)
void OnPlayerSetPhase (const AuraEffect *auraEff, AuraApplication const *aurApp, uint8 mode, bool apply, uint32 &newPhase)
void ValidateSpellAtCastSpellResult (Player *player, Unit *mover, Spell *spell, uint32 oldSpellId, uint32 spellId)
void OnAfterLootTemplateProcess (Loot *loot, LootTemplate const *tab, LootStore const &store, Player *lootOwner, bool personal, bool noEmptyError, uint16 lootMode)
void OnInstanceSave (InstanceSave *instanceSave)
void GetDialogStatus (Player *player, Object *questgiver)
void OnHandleDevCommand (Player *player, bool &enable)
bool OnTryExecuteCommand (ChatHandler &handler, std::string_view cmdStr)
bool OnBeforeIsInvokerVisible (std::string name, Acore::Impl::ChatCommands::CommandPermissions permissions, ChatHandler const &who)
void OnAfterDatabasesLoaded (uint32 updateFlags)
void OnAfterDatabaseLoadCreatureTemplates (std::vector< CreatureTemplate * > creatureTemplateStore)
void OnWorldObjectDestroy (WorldObject *object)
void OnWorldObjectCreate (WorldObject *object)
void OnWorldObjectSetMap (WorldObject *object, Map *map)
void OnWorldObjectResetMap (WorldObject *object)
void OnWorldObjectUpdate (WorldObject *object, uint32 diff)
void OnPetAddToWorld (Pet *pet)
void OnLootMoney (Player *player, uint32 gold)
void OnTicketCreate (GmTicket *ticket)
void OnTicketUpdateLastChange (GmTicket *ticket)
void OnTicketClose (GmTicket *ticket)
void OnTicketStatusUpdate (GmTicket *ticket)
void OnTicketResolve (GmTicket *ticket)
Static Public Member Functions
static ScriptMgr * instance ()
Private Member Functions
ScriptMgr ()
virtual ~ScriptMgr ()
Private Attributes
uint32 _scriptCount
std::atomic< long > _scheduledScripts
ScriptLoaderCallbackType _script_loader_callback
ModulesLoaderCallbackType _modules_loader_callback
Friends
class ScriptObject
Detailed Description
Member Typedef Documentation
ModulesLoaderCallbackType
typedef void(* ScriptMgr::ModulesLoaderCallbackType) ()
ScriptLoaderCallbackType
typedef void(* ScriptMgr::ScriptLoaderCallbackType) ()
Constructor & Destructor Documentation
ScriptMgr()
ScriptMgr::ScriptMgr () private
    : _scriptCount(0),
    _scheduledScripts(0),
    _script_loader_callback(nullptr),
    _modules_loader_callback(nullptr) { }
Member Function Documentation
AfterInstanceGameObjectCreate()
void ScriptMgr::AfterInstanceGameObjectCreate (Map * instance, GameObject * go)
Called when a game object is created inside an instance.
Parameters
instance A pointer to the [map] object of the instance
go The object being added
{
    CALL_ENABLED_HOOKS(GlobalScript, GLOBALHOOK_AFTER_INSTANCE_GAME_OBJECT_CREATE, script->AfterInstanceGameObjectCreate(instance, go));
}
References GlobalScript::AfterInstanceGameObjectCreate(), CALL_ENABLED_HOOKS, GLOBALHOOK_AFTER_INSTANCE_GAME_OBJECT_CREATE, and instance().
AnticheatCheckMovementInfo()
bool ScriptMgr::AnticheatCheckMovementInfo (Player * player, MovementInfo const & movementInfo, Unit * mover, bool jump)
{
    CALL_ENABLED_BOOLEAN_HOOKS(PlayerScript, PLAYERHOOK_ANTICHEAT_CHECK_MOVEMENT_INFO, !script->AnticheatCheckMovementInfo(player, movementInfo, mover, jump));
}
References PlayerScript::AnticheatCheckMovementInfo(), CALL_ENABLED_BOOLEAN_HOOKS, and PLAYERHOOK_ANTICHEAT_CHECK_MOVEMENT_INFO.
AnticheatHandleDoubleJump()
bool ScriptMgr::AnticheatHandleDoubleJump (Player * player, Unit * mover)
{
    CALL_ENABLED_BOOLEAN_HOOKS(PlayerScript, PLAYERHOOK_ANTICHEAT_HANDLE_DOUBLE_JUMP, !script->AnticheatHandleDoubleJump(player, mover));
}
References PlayerScript::AnticheatHandleDoubleJump(), CALL_ENABLED_BOOLEAN_HOOKS, and PLAYERHOOK_ANTICHEAT_HANDLE_DOUBLE_JUMP.
AnticheatSetCanFlybyServer()
void ScriptMgr::AnticheatSetCanFlybyServer (Player * player, bool apply)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ANTICHEAT_SET_CAN_FLY_BY_SERVER, script->AnticheatSetCanFlybyServer(player, apply));
}
References PlayerScript::AnticheatSetCanFlybyServer(), CALL_ENABLED_HOOKS, and PLAYERHOOK_ANTICHEAT_SET_CAN_FLY_BY_SERVER.
AnticheatSetJumpingbyOpcode()
void ScriptMgr::AnticheatSetJumpingbyOpcode (Player * player, bool jump)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ANTICHEAT_SET_JUMPING_BY_OPCODE, script->AnticheatSetJumpingbyOpcode(player, jump));
}
References PlayerScript::AnticheatSetJumpingbyOpcode(), CALL_ENABLED_HOOKS, and PLAYERHOOK_ANTICHEAT_SET_JUMPING_BY_OPCODE.
AnticheatSetRootACKUpd()
void ScriptMgr::AnticheatSetRootACKUpd (Player * player)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ANTICHEAT_SET_ROOT_ACK_UPD, script->AnticheatSetRootACKUpd(player));
}
References PlayerScript::AnticheatSetRootACKUpd(), CALL_ENABLED_HOOKS, and PLAYERHOOK_ANTICHEAT_SET_ROOT_ACK_UPD.
AnticheatSetUnderACKmount()
void ScriptMgr::AnticheatSetUnderACKmount (Player * player)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ANTICHEAT_SET_UNDER_ACK_MOUNT, script->AnticheatSetUnderACKmount(player));
}
References PlayerScript::AnticheatSetUnderACKmount(), CALL_ENABLED_HOOKS, and PLAYERHOOK_ANTICHEAT_SET_UNDER_ACK_MOUNT.
AnticheatUpdateMovementInfo()
void ScriptMgr::AnticheatUpdateMovementInfo (Player * player, MovementInfo const & movementInfo)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ANTICHEAT_UPDATE_MOVEMENT_INFO, script->AnticheatUpdateMovementInfo(player, movementInfo));
}
References PlayerScript::AnticheatUpdateMovementInfo(), CALL_ENABLED_HOOKS, and PLAYERHOOK_ANTICHEAT_UPDATE_MOVEMENT_INFO.
CanAccountCreateCharacter()
bool ScriptMgr::CanAccountCreateCharacter (uint32 accountId, uint8 charRace, uint8 charClass)
{
    CALL_ENABLED_BOOLEAN_HOOKS(AccountScript, ACCOUNTHOOK_CAN_ACCOUNT_CREATE_CHARACTER, !script->CanAccountCreateCharacter(accountId, charRace, charClass));
}
References ACCOUNTHOOK_CAN_ACCOUNT_CREATE_CHARACTER, CALL_ENABLED_BOOLEAN_HOOKS, and AccountScript::CanAccountCreateCharacter().
CanAddMember()
bool ScriptMgr::CanAddMember (ArenaTeam * team, ObjectGuid PlayerGuid)
{
    CALL_ENABLED_BOOLEAN_HOOKS(ArenaScript, ARENAHOOK_CAN_ADD_MEMBER, !script->CanAddMember(team, PlayerGuid));
}
References ARENAHOOK_CAN_ADD_MEMBER, CALL_ENABLED_BOOLEAN_HOOKS, and ArenaScript::CanAddMember().
CanApplySoulboundFlag()
bool ScriptMgr::CanApplySoulboundFlag (Item * item, ItemTemplate const * proto)
{
    CALL_ENABLED_BOOLEAN_HOOKS(MiscScript, MISCHOOK_CAN_APPLY_SOULBOUND_FLAG, !script->CanApplySoulboundFlag(item, proto));
}
References CALL_ENABLED_BOOLEAN_HOOKS, MiscScript::CanApplySoulboundFlag(), and MISCHOOK_CAN_APPLY_SOULBOUND_FLAG.
CanCheckCriteria()
bool ScriptMgr::CanCheckCriteria (AchievementMgr * mgr, AchievementCriteriaEntry const * achievementCriteria)
{
    CALL_ENABLED_BOOLEAN_HOOKS(AchievementScript, ACHIEVEMENTHOOK_CAN_CHECK_CRITERIA, !script->CanCheckCriteria(mgr, achievementCriteria));
}
References ACHIEVEMENTHOOK_CAN_CHECK_CRITERIA, CALL_ENABLED_BOOLEAN_HOOKS, and AchievementScript::CanCheckCriteria().
CanFillPlayersToBG()
bool ScriptMgr::CanFillPlayersToBG (BattlegroundQueue * queue, Battleground * bg, BattlegroundBracketId bracket_id)
{
    CALL_ENABLED_BOOLEAN_HOOKS(AllBattlegroundScript, ALLBATTLEGROUNDHOOK_CAN_FILL_PLAYERS_TO_BG, !script->CanFillPlayersToBG(queue, bg, bracket_id));
}
References ALLBATTLEGROUNDHOOK_CAN_FILL_PLAYERS_TO_BG, CALL_ENABLED_BOOLEAN_HOOKS, and AllBattlegroundScript::CanFillPlayersToBG().
CanGroupJoinBattlegroundQueue()
bool ScriptMgr::CanGroupJoinBattlegroundQueue (Group const * group, Player * member, Battleground const * bgTemplate, uint32 MinPlayerCount, bool isRated, uint32 arenaSlot)
{
    CALL_ENABLED_BOOLEAN_HOOKS(GroupScript, GROUPHOOK_CAN_GROUP_JOIN_BATTLEGROUND_QUEUE, !script->CanGroupJoinBattlegroundQueue(group, member, bgTemplate, MinPlayerCount, isRated, arenaSlot));
}
References CALL_ENABLED_BOOLEAN_HOOKS, GroupScript::CanGroupJoinBattlegroundQueue(), and GROUPHOOK_CAN_GROUP_JOIN_BATTLEGROUND_QUEUE.
CanGuildSendBankList()
bool ScriptMgr::CanGuildSendBankList (Guild const * guild, WorldSession * session, uint8 tabId, bool sendAllSlots)
{
    CALL_ENABLED_BOOLEAN_HOOKS(GuildScript, GUILDHOOK_CAN_GUILD_SEND_BANK_LIST, !script->CanGuildSendBankList(guild, session, tabId, sendAllSlots));
}
References CALL_ENABLED_BOOLEAN_HOOKS, GuildScript::CanGuildSendBankList(), and GUILDHOOK_CAN_GUILD_SEND_BANK_LIST.
CanItemApplyEquipSpell()
bool ScriptMgr::CanItemApplyEquipSpell (Player * player, Item * item)
{
    CALL_ENABLED_BOOLEAN_HOOKS(MiscScript, MISCHOOK_CAN_ITEM_APPLY_EQUIP_SPELL, !script->CanItemApplyEquipSpell(player, item));
}
References CALL_ENABLED_BOOLEAN_HOOKS, MiscScript::CanItemApplyEquipSpell(), and MISCHOOK_CAN_ITEM_APPLY_EQUIP_SPELL.
CanModAuraEffectDamageDone()
bool ScriptMgr::CanModAuraEffectDamageDone (AuraEffect const * auraEff, Unit * target, AuraApplication const * aurApp, uint8 mode, bool apply)
{
    CALL_ENABLED_BOOLEAN_HOOKS(AllSpellScript, ALLSPELLHOOK_CAN_MOD_AURA_EFFECT_DAMAGE_DONE, !script->CanModAuraEffectDamageDone(auraEff, target, aurApp, mode, apply));
}
References ALLSPELLHOOK_CAN_MOD_AURA_EFFECT_DAMAGE_DONE, CALL_ENABLED_BOOLEAN_HOOKS, and AllSpellScript::CanModAuraEffectDamageDone().
CanModAuraEffectModDamagePercentDone()
bool ScriptMgr::CanModAuraEffectModDamagePercentDone (AuraEffect const * auraEff, Unit * target, AuraApplication const * aurApp, uint8 mode, bool apply)
{
    CALL_ENABLED_BOOLEAN_HOOKS(AllSpellScript, ALLSPELLHOOK_CAN_MOD_AURA_EFFECT_MOD_DAMAGE_PERCENT_DONE, !script->CanModAuraEffectModDamagePercentDone(auraEff, target, aurApp, mode, apply));
}
References ALLSPELLHOOK_CAN_MOD_AURA_EFFECT_MOD_DAMAGE_PERCENT_DONE, CALL_ENABLED_BOOLEAN_HOOKS, and AllSpellScript::CanModAuraEffectModDamagePercentDone().
CanPacketReceive()
bool ScriptMgr::CanPacketReceive (WorldSession * session, WorldPacket const & packet)
{
    if (ScriptRegistry<ServerScript>::ScriptPointerList.empty())
        return true;
    WorldPacket copy(packet);
    CALL_ENABLED_BOOLEAN_HOOKS(ServerScript, SERVERHOOK_CAN_PACKET_RECEIVE, !script->CanPacketReceive(session, copy));
}
References CALL_ENABLED_BOOLEAN_HOOKS, ServerScript::CanPacketReceive(), and SERVERHOOK_CAN_PACKET_RECEIVE.
CanPacketSend()
bool ScriptMgr::CanPacketSend (WorldSession * session, WorldPacket const & packet)
{
    ASSERT(session);
    if (ScriptRegistry<ServerScript>::ScriptPointerList.empty())
        return true;
    WorldPacket copy(packet);
    CALL_ENABLED_BOOLEAN_HOOKS(ServerScript, SERVERHOOK_CAN_PACKET_SEND, !script->CanPacketSend(session, copy));
}
References ASSERT, CALL_ENABLED_BOOLEAN_HOOKS, ServerScript::CanPacketSend(), and SERVERHOOK_CAN_PACKET_SEND.
CanPrepare()
bool ScriptMgr::CanPrepare (Spell * spell, SpellCastTargets const * targets, AuraEffect const * triggeredByAura)
{
    CALL_ENABLED_BOOLEAN_HOOKS(AllSpellScript, ALLSPELLHOOK_CAN_PREPARE, !script->CanPrepare(spell, targets, triggeredByAura));
}
References ALLSPELLHOOK_CAN_PREPARE, CALL_ENABLED_BOOLEAN_HOOKS, and AllSpellScript::CanPrepare().
CanResetTalents()
bool ScriptMgr::CanResetTalents (Pet * pet)
{
    CALL_ENABLED_BOOLEAN_HOOKS(PetScript, PETHOOK_CAN_RESET_TALENTS, !script->CanResetTalents(pet));
}
References CALL_ENABLED_BOOLEAN_HOOKS, PetScript::CanResetTalents(), and PETHOOK_CAN_RESET_TALENTS.
CanSaveToDB()
bool ScriptMgr::CanSaveToDB (ArenaTeam * team)
{
    CALL_ENABLED_BOOLEAN_HOOKS(ArenaScript, ARENAHOOK_CAN_SAVE_TO_DB, !script->CanSaveToDB(team));
}
References ARENAHOOK_CAN_SAVE_TO_DB, CALL_ENABLED_BOOLEAN_HOOKS, and ArenaScript::CanSaveToDB().
CanScalingEverything()
bool ScriptMgr::CanScalingEverything (Spell * spell)
{
    CALL_ENABLED_BOOLEAN_HOOKS_WITH_DEFAULT_FALSE(AllSpellScript, ALLSPELLHOOK_CAN_SCALING_EVERYTHING, script->CanScalingEverything(spell));
}
References ALLSPELLHOOK_CAN_SCALING_EVERYTHING, CALL_ENABLED_BOOLEAN_HOOKS_WITH_DEFAULT_FALSE, and AllSpellScript::CanScalingEverything().
CanSelectSpecTalent()
bool ScriptMgr::CanSelectSpecTalent (Spell * spell)
{
    CALL_ENABLED_BOOLEAN_HOOKS(AllSpellScript, ALLSPELLHOOK_CAN_SELECT_SPEC_TALENT, !script->CanSelectSpecTalent(spell));
}
References ALLSPELLHOOK_CAN_SELECT_SPEC_TALENT, CALL_ENABLED_BOOLEAN_HOOKS, and AllSpellScript::CanSelectSpecTalent().
CanSendAuctionHello()
bool ScriptMgr::CanSendAuctionHello (WorldSession const * session, ObjectGuid guid, Creature * creature)
{
    CALL_ENABLED_BOOLEAN_HOOKS(MiscScript, MISCHOOK_CAN_SEND_AUCTIONHELLO, !script->CanSendAuctionHello(session, guid, creature));
}
References CALL_ENABLED_BOOLEAN_HOOKS, MiscScript::CanSendAuctionHello(), and MISCHOOK_CAN_SEND_AUCTIONHELLO.
CanSendMessageBGQueue()
bool ScriptMgr::CanSendMessageBGQueue (BattlegroundQueue * queue, Player * leader, Battleground * bg, PvPDifficultyEntry const * bracketEntry)
{
    CALL_ENABLED_BOOLEAN_HOOKS(AllBattlegroundScript, ALLBATTLEGROUNDHOOK_CAN_SEND_MESSAGE_BG_QUEUE, !script->CanSendMessageBGQueue(queue, leader, bg, bracketEntry));
}
References ALLBATTLEGROUNDHOOK_CAN_SEND_MESSAGE_BG_QUEUE, CALL_ENABLED_BOOLEAN_HOOKS, and AllBattlegroundScript::CanSendMessageBGQueue().
CanSetPhaseMask()
bool ScriptMgr::CanSetPhaseMask (Unit const * unit, uint32 newPhaseMask, bool update)
{
    CALL_ENABLED_BOOLEAN_HOOKS(UnitScript, UNITHOOK_CAN_SET_PHASE_MASK, !script->CanSetPhaseMask(unit, newPhaseMask, update));
}
References CALL_ENABLED_BOOLEAN_HOOKS, UnitScript::CanSetPhaseMask(), and UNITHOOK_CAN_SET_PHASE_MASK.
CanUnlearnSpellDefault()
bool ScriptMgr::CanUnlearnSpellDefault (Pet * pet, SpellInfo const * spellInfo)
{
    CALL_ENABLED_BOOLEAN_HOOKS(PetScript, PETHOOK_CAN_UNLEARN_SPELL_DEFAULT, !script->CanUnlearnSpellDefault(pet, spellInfo));
}
References CALL_ENABLED_BOOLEAN_HOOKS, PetScript::CanUnlearnSpellDefault(), and PETHOOK_CAN_UNLEARN_SPELL_DEFAULT.
CanUnlearnSpellSet()
bool ScriptMgr::CanUnlearnSpellSet (Pet * pet, uint32 level, uint32 spell)
{
    CALL_ENABLED_BOOLEAN_HOOKS(PetScript, PETHOOK_CAN_UNLEARN_SPELL_SET, !script->CanUnlearnSpellSet(pet, level, spell));
}
References CALL_ENABLED_BOOLEAN_HOOKS, PetScript::CanUnlearnSpellSet(), and PETHOOK_CAN_UNLEARN_SPELL_SET.
CheckIfScriptsInDatabaseExist()
void ScriptMgr::CheckIfScriptsInDatabaseExist ()
{
    for (auto const& scriptName : sObjectMgr->GetScriptNames())
    {
        if (uint32 sid = sObjectMgr->GetScriptId(scriptName))
        {
            if (!ScriptRegistry<SpellScriptLoader>::GetScriptById(sid) &&
                !ScriptRegistry<ServerScript>::GetScriptById(sid) &&
                !ScriptRegistry<WorldScript>::GetScriptById(sid) &&
                !ScriptRegistry<FormulaScript>::GetScriptById(sid) &&
                !ScriptRegistry<WorldMapScript>::GetScriptById(sid) &&
                !ScriptRegistry<InstanceMapScript>::GetScriptById(sid) &&
                !ScriptRegistry<BattlegroundMapScript>::GetScriptById(sid) &&
                !ScriptRegistry<ItemScript>::GetScriptById(sid) &&
                !ScriptRegistry<CreatureScript>::GetScriptById(sid) &&
                !ScriptRegistry<GameObjectScript>::GetScriptById(sid) &&
                !ScriptRegistry<AreaTriggerScript>::GetScriptById(sid) &&
                !ScriptRegistry<BattlegroundScript>::GetScriptById(sid) &&
                !ScriptRegistry<OutdoorPvPScript>::GetScriptById(sid) &&
                !ScriptRegistry<CommandScript>::GetScriptById(sid) &&
                !ScriptRegistry<WeatherScript>::GetScriptById(sid) &&
                !ScriptRegistry<AuctionHouseScript>::GetScriptById(sid) &&
                !ScriptRegistry<ConditionScript>::GetScriptById(sid) &&
                !ScriptRegistry<VehicleScript>::GetScriptById(sid) &&
                !ScriptRegistry<DynamicObjectScript>::GetScriptById(sid) &&
                !ScriptRegistry<TransportScript>::GetScriptById(sid) &&
                !ScriptRegistry<AchievementCriteriaScript>::GetScriptById(sid) &&
                !ScriptRegistry<PlayerScript>::GetScriptById(sid) &&
                !ScriptRegistry<GuildScript>::GetScriptById(sid) &&
                !ScriptRegistry<BGScript>::GetScriptById(sid) &&
                !ScriptRegistry<AchievementScript>::GetScriptById(sid) &&
                !ScriptRegistry<ArenaTeamScript>::GetScriptById(sid) &&
                !ScriptRegistry<SpellSC>::GetScriptById(sid) &&
                !ScriptRegistry<MiscScript>::GetScriptById(sid) &&
                !ScriptRegistry<PetScript>::GetScriptById(sid) &&
                !ScriptRegistry<CommandSC>::GetScriptById(sid) &&
                !ScriptRegistry<ArenaScript>::GetScriptById(sid) &&
                !ScriptRegistry<GroupScript>::GetScriptById(sid) &&
                !ScriptRegistry<DatabaseScript>::GetScriptById(sid) &&
                !ScriptRegistry<TicketScript>::GetScriptById(sid))
                {
                    LOG_ERROR("sql.sql", "Script named '{}' is assigned in the database, but has no code!", scriptName);
                }
        }
    }
}
References ScriptRegistry< TScript >::GetScriptById(), LOG_ERROR, and sObjectMgr.
Referenced by LoadDatabase().
CreateAuraScripts()
void ScriptMgr::CreateAuraScripts (uint32 spellId, std::list< AuraScript * > & scriptVector)
{
    SpellScriptsBounds bounds = sObjectMgr->GetSpellScriptsBounds(spellId);
    for (SpellScriptsContainer::iterator itr = bounds.first; itr != bounds.second; ++itr)
    {
        SpellScriptLoader* tempScript = ScriptRegistry<SpellScriptLoader>::GetScriptById(itr->second);
        if (!tempScript)
            continue;
        AuraScript* script = tempScript->GetAuraScript();
        if (!script)
            continue;
        script->_Init(&tempScript->GetName(), spellId);
        scriptVector.push_back(script);
    }
}
References _SpellScript::_Init(), SpellScriptLoader::GetAuraScript(), ScriptObject::GetName(), ScriptRegistry< TScript >::GetScriptById(), and sObjectMgr.
CreateBattleground()
Battleground * ScriptMgr::CreateBattleground (BattlegroundTypeId typeId)
Todo:
: Implement script-side battlegrounds.
{
    ABORT();
    return nullptr;
}
References ABORT.
CreateInstanceScript()
InstanceScript * ScriptMgr::CreateInstanceScript (InstanceMap * map)
{
    ASSERT(map);
    auto tempScript = ScriptRegistry<InstanceMapScript>::GetScriptById(map->GetScriptId());
    return tempScript ? tempScript->GetInstanceScript(map) : nullptr;
}
References ASSERT, ScriptRegistry< TScript >::GetScriptById(), and InstanceMap::GetScriptId().
CreateOutdoorPvP()
OutdoorPvP * ScriptMgr::CreateOutdoorPvP (OutdoorPvPData const * data)
{
    ASSERT(data);
    auto tempScript = ScriptRegistry<OutdoorPvPScript>::GetScriptById(data->ScriptId);
    return tempScript ? tempScript->GetOutdoorPvP() : nullptr;
}
References ASSERT, ScriptRegistry< TScript >::GetScriptById(), and OutdoorPvPData::ScriptId.
CreateSpellScriptLoaders()
void ScriptMgr::CreateSpellScriptLoaders (uint32 spellId, std::vector< std::pair< SpellScriptLoader *, std::multimap< uint32, uint32 >::iterator > > & scriptVector)
{
    SpellScriptsBounds bounds = sObjectMgr->GetSpellScriptsBounds(spellId);
    scriptVector.reserve(std::distance(bounds.first, bounds.second));
    for (SpellScriptsContainer::iterator itr = bounds.first; itr != bounds.second; ++itr)
    {
        SpellScriptLoader* tempScript = ScriptRegistry<SpellScriptLoader>::GetScriptById(itr->second);
        if (!tempScript)
            continue;
        scriptVector.emplace_back(tempScript, itr);
    }
}
References ScriptRegistry< TScript >::GetScriptById(), and sObjectMgr.
CreateSpellScripts()
void ScriptMgr::CreateSpellScripts (uint32 spellId, std::list< SpellScript * > & scriptVector)
{
    SpellScriptsBounds bounds = sObjectMgr->GetSpellScriptsBounds(spellId);
    for (SpellScriptsContainer::iterator itr = bounds.first; itr != bounds.second; ++itr)
    {
        SpellScriptLoader* tempScript = ScriptRegistry<SpellScriptLoader>::GetScriptById(itr->second);
        if (!tempScript)
            continue;
        SpellScript* script = tempScript->GetSpellScript();
        if (!script)
            continue;
        script->_Init(&tempScript->GetName(), spellId);
        scriptVector.push_back(script);
    }
}
References _SpellScript::_Init(), ScriptObject::GetName(), ScriptRegistry< TScript >::GetScriptById(), SpellScriptLoader::GetSpellScript(), and sObjectMgr.
Creature_SelectLevel()
void ScriptMgr::Creature_SelectLevel (const CreatureTemplate * cinfo, Creature * creature)
{
    ExecuteScript<AllCreatureScript>([&](AllCreatureScript* script)
    {
        script->Creature_SelectLevel(cinfo, creature);
    });
}
References AllCreatureScript::Creature_SelectLevel().
DealDamage()
uint32 ScriptMgr::DealDamage (Unit * AttackerUnit, Unit * pVictim, uint32 damage, DamageEffectType damagetype)
{
    if (ScriptRegistry<UnitScript>::ScriptPointerList.empty())
    {
        return damage;
    }
    for (auto const& [scriptID, script] : ScriptRegistry<UnitScript>::ScriptPointerList)
    {
        auto const& dmg = script->DealDamage(AttackerUnit, pVictim, damage, damagetype);
        if (dmg != damage)
        {
            return damage;
        }
    }
    return damage;
}
DecreaseScheduledScriptCount() [1/2]
uint32 ScriptMgr::DecreaseScheduledScriptCount () inline
{ return --_scheduledScripts; }
References _scheduledScripts.
DecreaseScheduledScriptCount() [2/2]
uint32 ScriptMgr::DecreaseScheduledScriptCount (std::size_t count) inline
{ return _scheduledScripts -= count; }
References _scheduledScripts.
DecreaseScriptCount()
void ScriptMgr::DecreaseScriptCount () inline
{ --_scriptCount; }
References _scriptCount.
FillSpellSummary()
void ScriptMgr::FillSpellSummary ()
{
    UnitAI::FillAISpellInfo();
    SpellSummary = new TSpellSummary[sSpellMgr->GetSpellInfoStoreSize()];
    SpellInfo const* pTempSpell;
    for (uint32 i = 0; i < sSpellMgr->GetSpellInfoStoreSize(); ++i)
    {
        SpellSummary[i].Effects = 0;
        SpellSummary[i].Targets = 0;
        pTempSpell = sSpellMgr->GetSpellInfo(i);
        // This spell doesn't exist.
        if (!pTempSpell)
            continue;
        for (uint32 j = 0; j < MAX_SPELL_EFFECTS; ++j)
        {
            // Spell targets self.
            if (pTempSpell->Effects[j].TargetA.GetTarget() == TARGET_UNIT_CASTER)
                SpellSummary[i].Targets |= 1 << (SELECT_TARGET_SELF - 1);
            // Spell targets a single enemy.
            if (pTempSpell->Effects[j].TargetA.GetTarget() == TARGET_UNIT_TARGET_ENEMY ||
                    pTempSpell->Effects[j].TargetA.GetTarget() == TARGET_DEST_TARGET_ENEMY)
                SpellSummary[i].Targets |= 1 << (SELECT_TARGET_SINGLE_ENEMY - 1);
            // Spell targets AoE at enemy.
            if (pTempSpell->Effects[j].TargetA.GetTarget() == TARGET_UNIT_SRC_AREA_ENEMY ||
                    pTempSpell->Effects[j].TargetA.GetTarget() == TARGET_UNIT_DEST_AREA_ENEMY ||
                    pTempSpell->Effects[j].TargetA.GetTarget() == TARGET_SRC_CASTER ||
                    pTempSpell->Effects[j].TargetA.GetTarget() == TARGET_DEST_DYNOBJ_ENEMY)
                SpellSummary[i].Targets |= 1 << (SELECT_TARGET_AOE_ENEMY - 1);
            // Spell targets an enemy.
            if (pTempSpell->Effects[j].TargetA.GetTarget() == TARGET_UNIT_TARGET_ENEMY ||
                    pTempSpell->Effects[j].TargetA.GetTarget() == TARGET_DEST_TARGET_ENEMY ||
                    pTempSpell->Effects[j].TargetA.GetTarget() == TARGET_UNIT_SRC_AREA_ENEMY ||
                    pTempSpell->Effects[j].TargetA.GetTarget() == TARGET_UNIT_DEST_AREA_ENEMY ||
                    pTempSpell->Effects[j].TargetA.GetTarget() == TARGET_SRC_CASTER ||
                    pTempSpell->Effects[j].TargetA.GetTarget() == TARGET_DEST_DYNOBJ_ENEMY)
                SpellSummary[i].Targets |= 1 << (SELECT_TARGET_ANY_ENEMY - 1);
            // Spell targets a single friend (or self).
            if (pTempSpell->Effects[j].TargetA.GetTarget() == TARGET_UNIT_CASTER ||
                    pTempSpell->Effects[j].TargetA.GetTarget() == TARGET_UNIT_TARGET_ALLY ||
                    pTempSpell->Effects[j].TargetA.GetTarget() == TARGET_UNIT_TARGET_PARTY)
                SpellSummary[i].Targets |= 1 << (SELECT_TARGET_SINGLE_FRIEND - 1);
            // Spell targets AoE friends.
            if (pTempSpell->Effects[j].TargetA.GetTarget() == TARGET_UNIT_CASTER_AREA_PARTY ||
                    pTempSpell->Effects[j].TargetA.GetTarget() == TARGET_UNIT_LASTTARGET_AREA_PARTY ||
                    pTempSpell->Effects[j].TargetA.GetTarget() == TARGET_SRC_CASTER)
                SpellSummary[i].Targets |= 1 << (SELECT_TARGET_AOE_FRIEND - 1);
            // Spell targets any friend (or self).
            if (pTempSpell->Effects[j].TargetA.GetTarget() == TARGET_UNIT_CASTER ||
                    pTempSpell->Effects[j].TargetA.GetTarget() == TARGET_UNIT_TARGET_ALLY ||
                    pTempSpell->Effects[j].TargetA.GetTarget() == TARGET_UNIT_TARGET_PARTY ||
                    pTempSpell->Effects[j].TargetA.GetTarget() == TARGET_UNIT_CASTER_AREA_PARTY ||
                    pTempSpell->Effects[j].TargetA.GetTarget() == TARGET_UNIT_LASTTARGET_AREA_PARTY ||
                    pTempSpell->Effects[j].TargetA.GetTarget() == TARGET_SRC_CASTER)
                SpellSummary[i].Targets |= 1 << (SELECT_TARGET_ANY_FRIEND - 1);
            // Make sure that this spell includes a damage effect.
            if (pTempSpell->Effects[j].Effect == SPELL_EFFECT_SCHOOL_DAMAGE ||
                    pTempSpell->Effects[j].Effect == SPELL_EFFECT_INSTAKILL ||
                    pTempSpell->Effects[j].Effect == SPELL_EFFECT_ENVIRONMENTAL_DAMAGE ||
                    pTempSpell->Effects[j].Effect == SPELL_EFFECT_HEALTH_LEECH)
                SpellSummary[i].Effects |= 1 << (SELECT_EFFECT_DAMAGE - 1);
            // Make sure that this spell includes a healing effect (or an apply aura with a periodic heal).
            if (pTempSpell->Effects[j].Effect == SPELL_EFFECT_HEAL ||
                    pTempSpell->Effects[j].Effect == SPELL_EFFECT_HEAL_MAX_HEALTH ||
                    pTempSpell->Effects[j].Effect == SPELL_EFFECT_HEAL_MECHANICAL ||
                    (pTempSpell->Effects[j].Effect == SPELL_EFFECT_APPLY_AURA  && pTempSpell->Effects[j].ApplyAuraName == 8))
                SpellSummary[i].Effects |= 1 << (SELECT_EFFECT_HEALING - 1);
            // Make sure that this spell applies an aura.
            if (pTempSpell->Effects[j].Effect == SPELL_EFFECT_APPLY_AURA)
                SpellSummary[i].Effects |= 1 << (SELECT_EFFECT_AURA - 1);
        }
    }
}
References TSpellSummary::Effects, SpellInfo::Effects, UnitAI::FillAISpellInfo(), MAX_SPELL_EFFECTS, SELECT_EFFECT_AURA, SELECT_EFFECT_DAMAGE, SELECT_EFFECT_HEALING, SELECT_TARGET_ANY_ENEMY, SELECT_TARGET_ANY_FRIEND, SELECT_TARGET_AOE_ENEMY, SELECT_TARGET_AOE_FRIEND, SELECT_TARGET_SELF, SELECT_TARGET_SINGLE_ENEMY, SELECT_TARGET_SINGLE_FRIEND, SPELL_EFFECT_APPLY_AURA, SPELL_EFFECT_ENVIRONMENTAL_DAMAGE, SPELL_EFFECT_HEAL, SPELL_EFFECT_HEAL_MAX_HEALTH, SPELL_EFFECT_HEAL_MECHANICAL, SPELL_EFFECT_HEALTH_LEECH, SPELL_EFFECT_INSTAKILL, SPELL_EFFECT_SCHOOL_DAMAGE, SpellSummary, sSpellMgr, TARGET_DEST_DYNOBJ_ENEMY, TARGET_DEST_TARGET_ENEMY, TARGET_SRC_CASTER, TARGET_UNIT_CASTER, TARGET_UNIT_CASTER_AREA_PARTY, TARGET_UNIT_DEST_AREA_ENEMY, TARGET_UNIT_LASTTARGET_AREA_PARTY, TARGET_UNIT_SRC_AREA_ENEMY, TARGET_UNIT_TARGET_ALLY, TARGET_UNIT_TARGET_ENEMY, TARGET_UNIT_TARGET_PARTY, and TSpellSummary::Targets.
Referenced by LoadDatabase().
GetChatCommands()
Acore::ChatCommands::ChatCommandTable ScriptMgr::GetChatCommands ()
{
    Acore::ChatCommands::ChatCommandTable table;
    for (auto const& [scriptID, script] : ScriptRegistry<CommandScript>::ScriptPointerList)
    {
        Acore::ChatCommands::ChatCommandTable cmds = script->GetCommands();
        std::move(cmds.begin(), cmds.end(), std::back_inserter(table));
    }
    return table;
}
GetCreatureAI()
CreatureAI * ScriptMgr::GetCreatureAI (Creature * creature)
{
    ASSERT(creature);
    auto retAI = GetReturnAIScript<AllCreatureScript, CreatureAI>([creature](AllCreatureScript* script)
    {
        return script->GetCreatureAI(creature);
    });
    if (retAI)
    {
        return retAI;
    }
    auto tempScript = ScriptRegistry<CreatureScript>::GetScriptById(creature->GetScriptId());
    return tempScript ? tempScript->GetAI(creature) : nullptr;
}
References ASSERT, AllCreatureScript::GetCreatureAI(), ScriptRegistry< TScript >::GetScriptById(), and Creature::GetScriptId().
GetDialogStatus() [1/3]
uint32 ScriptMgr::GetDialogStatus (Player * player, Creature * creature)
{
    ASSERT(player);
    ASSERT(creature);
    auto tempScript = ScriptRegistry<CreatureScript>::GetScriptById(creature->GetScriptId());
    return tempScript ? tempScript->GetDialogStatus(player, creature) : DIALOG_STATUS_SCRIPTED_NO_STATUS;
}
References ASSERT, DIALOG_STATUS_SCRIPTED_NO_STATUS, ScriptRegistry< TScript >::GetScriptById(), and Creature::GetScriptId().
GetDialogStatus() [2/3]
uint32 ScriptMgr::GetDialogStatus (Player * player, GameObject * go)
{
    ASSERT(player);
    ASSERT(go);
    auto tempScript = ScriptRegistry<GameObjectScript>::GetScriptById(go->GetScriptId());
    return tempScript ? tempScript->GetDialogStatus(player, go) : DIALOG_STATUS_SCRIPTED_NO_STATUS;
}
References ASSERT, DIALOG_STATUS_SCRIPTED_NO_STATUS, ScriptRegistry< TScript >::GetScriptById(), and GameObject::GetScriptId().
GetDialogStatus() [3/3]
void ScriptMgr::GetDialogStatus (Player * player, Object * questgiver)
{
    CALL_ENABLED_HOOKS(MiscScript, MISCHOOK_GET_DIALOG_STATUS, script->GetDialogStatus(player, questgiver));
}
References CALL_ENABLED_HOOKS, MiscScript::GetDialogStatus(), and MISCHOOK_GET_DIALOG_STATUS.
GetGameObjectAI()
GameObjectAI * ScriptMgr::GetGameObjectAI (GameObject * go)
{
    ASSERT(go);
    auto retAI = GetReturnAIScript<AllGameObjectScript, GameObjectAI>([go](AllGameObjectScript* script)
    {
        return script->GetGameObjectAI(go);
    });
    if (retAI)
    {
        return retAI;
    }
    auto tempScript = ScriptRegistry<GameObjectScript>::GetScriptById(go->GetScriptId());
    return tempScript ? tempScript->GetAI(go) : nullptr;
}
References ASSERT, AllGameObjectScript::GetGameObjectAI(), ScriptRegistry< TScript >::GetScriptById(), and GameObject::GetScriptId().
GetScriptCount()
uint32 ScriptMgr::GetScriptCount () const inline
{ return _scriptCount; }
References _scriptCount.
Referenced by LoadDatabase().
IfNormalReaction()
bool ScriptMgr::IfNormalReaction (Unit const * unit, Unit const * target, ReputationRank & repRank)
{
    CALL_ENABLED_BOOLEAN_HOOKS(UnitScript, UNITHOOK_IF_NORMAL_REACTION, !script->IfNormalReaction(unit, target, repRank));
}
References CALL_ENABLED_BOOLEAN_HOOKS, UnitScript::IfNormalReaction(), and UNITHOOK_IF_NORMAL_REACTION.
IncreaseScheduledScriptsCount()
uint32 ScriptMgr::IncreaseScheduledScriptsCount () inline
{ return ++_scheduledScripts; }
References _scheduledScripts.
IncreaseScriptCount()
void ScriptMgr::IncreaseScriptCount () inline
{ ++_scriptCount; }
References _scriptCount.
Initialize()
void ScriptMgr::Initialize ()
{
    LOG_INFO("server.loading", "> Loading C++ scripts");
    LOG_INFO("server.loading", " ");
    AddSC_SmartScripts();
    // LFGScripts
    lfg::AddSC_LFGScripts();
    ASSERT(_script_loader_callback,
        "Script loader callback wasn't registered!");
    ASSERT(_modules_loader_callback,
        "Modules loader callback wasn't registered!");
    _script_loader_callback();
    _modules_loader_callback();
    ScriptRegistry<AccountScript>::InitEnabledHooksIfNeeded(ACCOUNTHOOK_END);
    ScriptRegistry<AchievementScript>::InitEnabledHooksIfNeeded(ACHIEVEMENTHOOK_END);
    ScriptRegistry<ArenaScript>::InitEnabledHooksIfNeeded(ARENAHOOK_END);
    ScriptRegistry<ArenaTeamScript>::InitEnabledHooksIfNeeded(ARENATEAMHOOK_END);
    ScriptRegistry<AuctionHouseScript>::InitEnabledHooksIfNeeded(AUCTIONHOUSEHOOK_END);
    ScriptRegistry<BGScript>::InitEnabledHooksIfNeeded(ALLBATTLEGROUNDHOOK_END);
    ScriptRegistry<CommandSC>::InitEnabledHooksIfNeeded(ALLCOMMANDHOOK_END);
    ScriptRegistry<DatabaseScript>::InitEnabledHooksIfNeeded(DATABASEHOOK_END);
    ScriptRegistry<FormulaScript>::InitEnabledHooksIfNeeded(FORMULAHOOK_END);
    ScriptRegistry<GameEventScript>::InitEnabledHooksIfNeeded(GAMEEVENTHOOK_END);
    ScriptRegistry<GlobalScript>::InitEnabledHooksIfNeeded(GLOBALHOOK_END);
    ScriptRegistry<GroupScript>::InitEnabledHooksIfNeeded(GROUPHOOK_END);
    ScriptRegistry<GuildScript>::InitEnabledHooksIfNeeded(GUILDHOOK_END);
    ScriptRegistry<LootScript>::InitEnabledHooksIfNeeded(LOOTHOOK_END);
    ScriptRegistry<MailScript>::InitEnabledHooksIfNeeded(MAILHOOK_END);
    ScriptRegistry<MiscScript>::InitEnabledHooksIfNeeded(MISCHOOK_END);
    ScriptRegistry<MovementHandlerScript>::InitEnabledHooksIfNeeded(MOVEMENTHOOK_END);
    ScriptRegistry<PetScript>::InitEnabledHooksIfNeeded(PETHOOK_END);
    ScriptRegistry<PlayerScript>::InitEnabledHooksIfNeeded(PLAYERHOOK_END);
    ScriptRegistry<ServerScript>::InitEnabledHooksIfNeeded(SERVERHOOK_END);
    ScriptRegistry<SpellSC>::InitEnabledHooksIfNeeded(ALLSPELLHOOK_END);
    ScriptRegistry<TicketScript>::InitEnabledHooksIfNeeded(TICKETHOOK_END);
    ScriptRegistry<UnitScript>::InitEnabledHooksIfNeeded(UNITHOOK_END);
    ScriptRegistry<WorldObjectScript>::InitEnabledHooksIfNeeded(WORLDOBJECTHOOK_END);
    ScriptRegistry<WorldScript>::InitEnabledHooksIfNeeded(WORLDHOOK_END);
    ScriptRegistry<AllMapScript>::InitEnabledHooksIfNeeded(ALLMAPHOOK_END);
}
References _modules_loader_callback, _script_loader_callback, ACCOUNTHOOK_END, ACHIEVEMENTHOOK_END, lfg::AddSC_LFGScripts(), AddSC_SmartScripts(), ALLBATTLEGROUNDHOOK_END, ALLCOMMANDHOOK_END, ALLMAPHOOK_END, ALLSPELLHOOK_END, ARENAHOOK_END, ARENATEAMHOOK_END, ASSERT, AUCTIONHOUSEHOOK_END, DATABASEHOOK_END, FORMULAHOOK_END, GAMEEVENTHOOK_END, GLOBALHOOK_END, GROUPHOOK_END, GUILDHOOK_END, ScriptRegistry< TScript >::InitEnabledHooksIfNeeded(), LOG_INFO, LOOTHOOK_END, MAILHOOK_END, MISCHOOK_END, MOVEMENTHOOK_END, PETHOOK_END, PLAYERHOOK_END, SERVERHOOK_END, TICKETHOOK_END, UNITHOOK_END, WORLDHOOK_END, and WORLDOBJECTHOOK_END.
instance()
ScriptMgr * ScriptMgr::instance () static
{
    static ScriptMgr instance;
    return &instance;
}
References instance().
Referenced by AfterInstanceGameObjectCreate(), instance(), OnBeforeSetBossState(), and OnPlayerCanEnterMap().
IsCheckNormalMatch()
bool ScriptMgr::IsCheckNormalMatch (BattlegroundQueue * queue, Battleground * bgTemplate, BattlegroundBracketId bracket_id, uint32 minPlayers, uint32 maxPlayers)
{
    CALL_ENABLED_BOOLEAN_HOOKS_WITH_DEFAULT_FALSE(AllBattlegroundScript, ALLBATTLEGROUNDHOOK_IS_CHECK_NORMAL_MATCH, script->IsCheckNormalMatch(queue, bgTemplate, bracket_id, minPlayers, maxPlayers));
}
References ALLBATTLEGROUNDHOOK_IS_CHECK_NORMAL_MATCH, CALL_ENABLED_BOOLEAN_HOOKS_WITH_DEFAULT_FALSE, and AllBattlegroundScript::IsCheckNormalMatch().
IsCompletedCriteria()
bool ScriptMgr::IsCompletedCriteria (AchievementMgr * mgr, AchievementCriteriaEntry const * achievementCriteria, AchievementEntry const * achievement, CriteriaProgress const * progress)
{
    CALL_ENABLED_BOOLEAN_HOOKS(AchievementScript, ACHIEVEMENTHOOK_IS_COMPLETED_CRITERIA, !script->IsCompletedCriteria(mgr, achievementCriteria, achievement, progress));
}
References ACHIEVEMENTHOOK_IS_COMPLETED_CRITERIA, CALL_ENABLED_BOOLEAN_HOOKS, and AchievementScript::IsCompletedCriteria().
IsCustomBuildValuesUpdate()
bool ScriptMgr::IsCustomBuildValuesUpdate (Unit const * unit, uint8 updateType, ByteBuffer & fieldBuffer, Player const * target, uint16 index)
{
    CALL_ENABLED_BOOLEAN_HOOKS_WITH_DEFAULT_FALSE(UnitScript, UNITHOOK_IS_CUSTOM_BUILD_VALUES_UPDATE, script->IsCustomBuildValuesUpdate(unit, updateType, fieldBuffer, target, index));
}
References CALL_ENABLED_BOOLEAN_HOOKS_WITH_DEFAULT_FALSE, UnitScript::IsCustomBuildValuesUpdate(), and UNITHOOK_IS_CUSTOM_BUILD_VALUES_UPDATE.
IsNeedModHealPercent()
bool ScriptMgr::IsNeedModHealPercent (Unit const * unit, AuraEffect * auraEff, float & doneTotalMod, SpellInfo const * spellProto)
{
    CALL_ENABLED_BOOLEAN_HOOKS(UnitScript, UNITHOOK_IS_NEEDMOD_HEAL_PERCENT, !script->IsNeedModHealPercent(unit, auraEff, doneTotalMod, spellProto));
}
References CALL_ENABLED_BOOLEAN_HOOKS, UnitScript::IsNeedModHealPercent(), and UNITHOOK_IS_NEEDMOD_HEAL_PERCENT.
IsNeedModMeleeDamagePercent()
bool ScriptMgr::IsNeedModMeleeDamagePercent (Unit const * unit, AuraEffect * auraEff, float & doneTotalMod, SpellInfo const * spellProto)
{
    CALL_ENABLED_BOOLEAN_HOOKS(UnitScript, UNITHOOK_IS_NEEDMOD_MELEE_DAMAGE_PERCENT, !script->IsNeedModMeleeDamagePercent(unit, auraEff, doneTotalMod, spellProto));
}
References CALL_ENABLED_BOOLEAN_HOOKS, UnitScript::IsNeedModMeleeDamagePercent(), and UNITHOOK_IS_NEEDMOD_MELEE_DAMAGE_PERCENT.
IsNeedModSpellDamagePercent()
bool ScriptMgr::IsNeedModSpellDamagePercent (Unit const * unit, AuraEffect * auraEff, float & doneTotalMod, SpellInfo const * spellProto)
{
    CALL_ENABLED_BOOLEAN_HOOKS(UnitScript, UNITHOOK_IS_NEEDMOD_SPELL_DAMAGE_PERCENT, !script->IsNeedModSpellDamagePercent(unit, auraEff, doneTotalMod, spellProto));
}
References CALL_ENABLED_BOOLEAN_HOOKS, UnitScript::IsNeedModSpellDamagePercent(), and UNITHOOK_IS_NEEDMOD_SPELL_DAMAGE_PERCENT.
IsRealmCompleted()
bool ScriptMgr::IsRealmCompleted (AchievementGlobalMgr const * globalmgr, AchievementEntry const * achievement, std::chrono::system_clock::time_point completionTime)
{
    CALL_ENABLED_BOOLEAN_HOOKS(AchievementScript, ACHIEVEMENTHOOK_IS_REALM_COMPLETED, !script->IsRealmCompleted(globalmgr, achievement, completionTime));
}
References ACHIEVEMENTHOOK_IS_REALM_COMPLETED, CALL_ENABLED_BOOLEAN_HOOKS, and AchievementScript::IsRealmCompleted().
IsScriptScheduled()
bool ScriptMgr::IsScriptScheduled () const inline
{ return _scheduledScripts > 0; }
References _scheduledScripts.
LoadDatabase()
void ScriptMgr::LoadDatabase ()
{
    uint32 oldMSTime = getMSTime();
    sScriptSystemMgr->LoadScriptWaypoints();
    // Add all scripts that must be loaded after db/maps
    ScriptRegistry<WorldMapScript>::AddALScripts();
    ScriptRegistry<BattlegroundMapScript>::AddALScripts();
    ScriptRegistry<InstanceMapScript>::AddALScripts();
    ScriptRegistry<SpellScriptLoader>::AddALScripts();
    ScriptRegistry<ItemScript>::AddALScripts();
    ScriptRegistry<CreatureScript>::AddALScripts();
    ScriptRegistry<GameObjectScript>::AddALScripts();
    ScriptRegistry<AreaTriggerScript>::AddALScripts();
    ScriptRegistry<BattlegroundScript>::AddALScripts();
    ScriptRegistry<OutdoorPvPScript>::AddALScripts();
    ScriptRegistry<WeatherScript>::AddALScripts();
    ScriptRegistry<ConditionScript>::AddALScripts();
    ScriptRegistry<TransportScript>::AddALScripts();
    ScriptRegistry<AchievementCriteriaScript>::AddALScripts();
    FillSpellSummary();
    CheckIfScriptsInDatabaseExist();
    LOG_INFO("server.loading", ">> Loaded {} C++ scripts in {} ms", GetScriptCount(), GetMSTimeDiffToNow(oldMSTime));
    LOG_INFO("server.loading", " ");
}
References ScriptRegistry< TScript >::AddALScripts(), CheckIfScriptsInDatabaseExist(), FillSpellSummary(), getMSTime(), GetMSTimeDiffToNow(), GetScriptCount(), LOG_INFO, and sScriptSystemMgr.
ModifyHealReceived()
void ScriptMgr::ModifyHealReceived (Unit * target, Unit * healer, uint32 & addHealth, SpellInfo const * spellInfo)
{
    CALL_ENABLED_HOOKS(UnitScript, UNITHOOK_MODIFY_HEAL_RECEIVED, script->ModifyHealReceived(target, healer, heal, spellInfo));
}
References CALL_ENABLED_HOOKS, UnitScript::ModifyHealReceived(), and UNITHOOK_MODIFY_HEAL_RECEIVED.
ModifyMeleeDamage()
void ScriptMgr::ModifyMeleeDamage (Unit * target, Unit * attacker, uint32 & damage)
{
    CALL_ENABLED_HOOKS(UnitScript, UNITHOOK_MODIFY_MELEE_DAMAGE, script->ModifyMeleeDamage(target, attacker, damage));
}
References CALL_ENABLED_HOOKS, UnitScript::ModifyMeleeDamage(), and UNITHOOK_MODIFY_MELEE_DAMAGE.
ModifyPeriodicDamageAurasTick()
void ScriptMgr::ModifyPeriodicDamageAurasTick (Unit * target, Unit * attacker, uint32 & damage, SpellInfo const * spellInfo)
{
    CALL_ENABLED_HOOKS(UnitScript, UNITHOOK_MODIFY_PERIODIC_DAMAGE_AURAS_TICK, script->ModifyPeriodicDamageAurasTick(target, attacker, damage, spellInfo));
}
References CALL_ENABLED_HOOKS, UnitScript::ModifyPeriodicDamageAurasTick(), and UNITHOOK_MODIFY_PERIODIC_DAMAGE_AURAS_TICK.
ModifySpellDamageTaken()
void ScriptMgr::ModifySpellDamageTaken (Unit * target, Unit * attacker, int32 & damage, SpellInfo const * spellInfo)
{
    CALL_ENABLED_HOOKS(UnitScript, UNITHOOK_MODIFY_SPELL_DAMAGE_TAKEN, script->ModifySpellDamageTaken(target, attacker, damage, spellInfo));
}
References CALL_ENABLED_HOOKS, UnitScript::ModifySpellDamageTaken(), and UNITHOOK_MODIFY_SPELL_DAMAGE_TAKEN.
OnAccountLogin()
void ScriptMgr::OnAccountLogin (uint32 accountId)
{
    CALL_ENABLED_HOOKS(AccountScript, ACCOUNTHOOK_ON_ACCOUNT_LOGIN, script->OnAccountLogin(accountId));
}
References ACCOUNTHOOK_ON_ACCOUNT_LOGIN, CALL_ENABLED_HOOKS, and AccountScript::OnAccountLogin().
OnAddCreaturePassenger()
void ScriptMgr::OnAddCreaturePassenger (Transport * transport, Creature * creature)
{
    ASSERT(transport);
    ASSERT(creature);
    if (auto tempScript = ScriptRegistry<TransportScript>::GetScriptById(transport->GetScriptId()))
    {
        tempScript->OnAddCreaturePassenger(transport, creature);
    }
}
References ASSERT, and GameObject::GetScriptId().
OnAddGroup()
void ScriptMgr::OnAddGroup (BattlegroundQueue * queue, GroupQueueInfo * ginfo, uint32 & index, Player * leader, Group * group, BattlegroundTypeId bgTypeId, PvPDifficultyEntry const * bracketEntry, uint8 arenaType, bool isRated, bool isPremade, uint32 arenaRating, uint32 matchmakerRating, uint32 arenaTeamId, uint32 opponentsArenaTeamId)
{
    CALL_ENABLED_HOOKS(AllBattlegroundScript, ALLBATTLEGROUNDHOOK_ON_ADD_GROUP, script->OnAddGroup(queue, ginfo, index, leader, group, bgTypeId, bracketEntry, arenaType, isRated, isPremade, arenaRating, matchmakerRating, arenaTeamId, opponentsArenaTeamId));
}
References ALLBATTLEGROUNDHOOK_ON_ADD_GROUP, CALL_ENABLED_HOOKS, and AllBattlegroundScript::OnAddGroup().
OnAddPassenger() [1/2]
void ScriptMgr::OnAddPassenger (Transport * transport, Player * player)
{
    ASSERT(transport);
    ASSERT(player);
    if (auto tempScript = ScriptRegistry<TransportScript>::GetScriptById(transport->GetScriptId()))
    {
        tempScript->OnAddPassenger(transport, player);
    }
}
References ASSERT, and GameObject::GetScriptId().
OnAddPassenger() [2/2]
void ScriptMgr::OnAddPassenger (Vehicle * veh, Unit * passenger, int8 seatId)
{
    ASSERT(veh);
    ASSERT(veh->GetBase()->IsCreature());
    ASSERT(passenger);
    if (auto tempScript = ScriptRegistry<VehicleScript>::GetScriptById(veh->GetBase()->ToCreature()->GetScriptId()))
    {
        tempScript->OnAddPassenger(veh, passenger, seatId);
    }
}
References ASSERT, Vehicle::GetBase(), Creature::GetScriptId(), Object::IsCreature(), and Object::ToCreature().
OnAfterArenaRatingCalculation()
void ScriptMgr::OnAfterArenaRatingCalculation (Battleground *const bg, int32 & winnerMatchmakerChange, int32 & loserMatchmakerChange, int32 & winnerChange, int32 & loserChange)
{
    CALL_ENABLED_HOOKS(FormulaScript, FORMULAHOOK_ON_AFTER_ARENA_RATING_CALCULATION, script->OnAfterArenaRatingCalculation(bg, winnerMatchmakerChange, loserMatchmakerChange, winnerChange, loserChange));
}
References CALL_ENABLED_HOOKS, FORMULAHOOK_ON_AFTER_ARENA_RATING_CALCULATION, and FormulaScript::OnAfterArenaRatingCalculation().
OnAfterCalculateLootGroupAmount()
void ScriptMgr::OnAfterCalculateLootGroupAmount (Player const * player, Loot & loot, uint16 lootMode, uint32 & groupAmount, LootStore const & store)
{
    CALL_ENABLED_HOOKS(GlobalScript, GLOBALHOOK_ON_AFTER_CALCULATE_LOOT_GROUP_AMOUNT, script->OnAfterCalculateLootGroupAmount(player, loot, lootMode, groupAmount, store));
}
References CALL_ENABLED_HOOKS, GLOBALHOOK_ON_AFTER_CALCULATE_LOOT_GROUP_AMOUNT, and GlobalScript::OnAfterCalculateLootGroupAmount().
OnAfterConfigLoad()
void ScriptMgr::OnAfterConfigLoad (bool reload)
{
    CALL_ENABLED_HOOKS(WorldScript, WORLDHOOK_ON_AFTER_CONFIG_LOAD, script->OnAfterConfigLoad(reload));
}
References CALL_ENABLED_HOOKS, WorldScript::OnAfterConfigLoad(), and WORLDHOOK_ON_AFTER_CONFIG_LOAD.
OnAfterDatabaseLoadCreatureTemplates()
void ScriptMgr::OnAfterDatabaseLoadCreatureTemplates (std::vector< CreatureTemplate * > creatureTemplateStore)
{
    CALL_ENABLED_HOOKS(DatabaseScript, DATABASEHOOK_ON_AFTER_DATABASE_LOAD_CREATURETEMPLATES, script->OnAfterDatabaseLoadCreatureTemplates(creatureTemplates));
}
References CALL_ENABLED_HOOKS, DATABASEHOOK_ON_AFTER_DATABASE_LOAD_CREATURETEMPLATES, and DatabaseScript::OnAfterDatabaseLoadCreatureTemplates().
OnAfterDatabasesLoaded()
void ScriptMgr::OnAfterDatabasesLoaded (uint32 updateFlags)
{
    CALL_ENABLED_HOOKS(DatabaseScript, DATABASEHOOK_ON_AFTER_DATABASES_LOADED, script->OnAfterDatabasesLoaded(updateFlags));
}
References CALL_ENABLED_HOOKS, DATABASEHOOK_ON_AFTER_DATABASES_LOADED, and DatabaseScript::OnAfterDatabasesLoaded().
OnAfterInitializeLockedDungeons()
void ScriptMgr::OnAfterInitializeLockedDungeons (Player * player)
{
    CALL_ENABLED_HOOKS(GlobalScript, GLOBALHOOK_ON_AFTER_INITIALIZE_LOCKED_DUNGEONS, script->OnAfterInitializeLockedDungeons(player));
}
References CALL_ENABLED_HOOKS, GLOBALHOOK_ON_AFTER_INITIALIZE_LOCKED_DUNGEONS, and GlobalScript::OnAfterInitializeLockedDungeons().
OnAfterLootTemplateProcess()
void ScriptMgr::OnAfterLootTemplateProcess (Loot * loot, LootTemplate const * tab, LootStore const & store, Player * lootOwner, bool personal, bool noEmptyError, uint16 lootMode)
{
    CALL_ENABLED_HOOKS(MiscScript, MISCHOOK_ON_AFTER_LOOT_TEMPLATE_PROCESS, script->OnAfterLootTemplateProcess(loot, tab, store, lootOwner, personal, noEmptyError, lootMode));
}
References CALL_ENABLED_HOOKS, MISCHOOK_ON_AFTER_LOOT_TEMPLATE_PROCESS, and MiscScript::OnAfterLootTemplateProcess().
OnAfterRefCount()
void ScriptMgr::OnAfterRefCount (Player const * player, Loot & loot, bool canRate, uint16 lootMode, LootStoreItem * LootStoreItem, uint32 & maxcount, LootStore const & store)
{
    CALL_ENABLED_HOOKS(GlobalScript, GLOBALHOOK_ON_AFTER_REF_COUNT, script->OnAfterRefCount(player, LootStoreItem, loot, canRate, lootMode, maxcount, store));
}
References CALL_ENABLED_HOOKS, GLOBALHOOK_ON_AFTER_REF_COUNT, and GlobalScript::OnAfterRefCount().
OnAfterUnloadAllMaps()
void ScriptMgr::OnAfterUnloadAllMaps ()
{
    CALL_ENABLED_HOOKS(WorldScript, WORLDHOOK_ON_AFTER_UNLOAD_ALL_MAPS, script->OnAfterUnloadAllMaps());
}
References CALL_ENABLED_HOOKS, WorldScript::OnAfterUnloadAllMaps(), and WORLDHOOK_ON_AFTER_UNLOAD_ALL_MAPS.
OnAfterUpdateEncounterState()
void ScriptMgr::OnAfterUpdateEncounterState (Map * map, EncounterCreditType type, uint32 creditEntry, Unit * source, Difficulty difficulty_fixed, DungeonEncounterList const * encounters, uint32 dungeonCompleted, bool updated)
{
    CALL_ENABLED_HOOKS(GlobalScript, GLOBALHOOK_ON_AFTER_UPDATE_ENCOUNTER_STATE, script->OnAfterUpdateEncounterState(map, type, creditEntry, source, difficulty_fixed, encounters, dungeonCompleted, updated));
}
References CALL_ENABLED_HOOKS, GLOBALHOOK_ON_AFTER_UPDATE_ENCOUNTER_STATE, and GlobalScript::OnAfterUpdateEncounterState().
OnAllowedForPlayerLootCheck()
bool ScriptMgr::OnAllowedForPlayerLootCheck (Player const * player, ObjectGuid source)
{
    CALL_ENABLED_BOOLEAN_HOOKS(GlobalScript, GLOBALHOOK_ON_ALLOWED_FOR_PLAYER_LOOT_CHECK, script->OnAllowedForPlayerLootCheck(player, source));
}
References CALL_ENABLED_BOOLEAN_HOOKS, GLOBALHOOK_ON_ALLOWED_FOR_PLAYER_LOOT_CHECK, and GlobalScript::OnAllowedForPlayerLootCheck().
OnAllowedToLootContainerCheck()
bool ScriptMgr::OnAllowedToLootContainerCheck (Player const * player, ObjectGuid source)
{
    CALL_ENABLED_BOOLEAN_HOOKS(GlobalScript, GLOBALHOOK_ON_ALLOWED_TO_LOOT_CONTAINER_CHECK, script->OnAllowedToLootContainerCheck(player, source));
}
References CALL_ENABLED_BOOLEAN_HOOKS, GLOBALHOOK_ON_ALLOWED_TO_LOOT_CONTAINER_CHECK, and GlobalScript::OnAllowedToLootContainerCheck().
OnAreaTrigger()
bool ScriptMgr::OnAreaTrigger (Player * player, AreaTrigger const * trigger)
{
    ASSERT(player);
    ASSERT(trigger);
    auto ret = IsValidBoolScript<ElunaScript>([&](ElunaScript* script)
    {
        return script->CanAreaTrigger(player, trigger);
    });
    if (ret && *ret)
    {
        return false;
    }
    auto tempScript = ScriptRegistry<AreaTriggerScript>::GetScriptById(sObjectMgr->GetAreaTriggerScriptId(trigger->entry));
    return tempScript ? tempScript->OnTrigger(player, trigger) : false;
}
OnArenaQueueIdToArenaType()
void ScriptMgr::OnArenaQueueIdToArenaType (const BattlegroundQueueTypeId bgQueueTypeId, uint8 & ArenaType)
{
    CALL_ENABLED_HOOKS(ArenaTeamScript, ARENATEAMHOOK_ON_QUEUEID_TO_ARENA_TYPE, script->OnQueueIdToArenaType(bgQueueTypeId, ArenaType));
}
References ARENATEAMHOOK_ON_QUEUEID_TO_ARENA_TYPE, CALL_ENABLED_HOOKS, and ArenaTeamScript::OnQueueIdToArenaType().
OnArenaStart()
void ScriptMgr::OnArenaStart (Battleground *const bg)
{
    CALL_ENABLED_HOOKS(ArenaScript, ARENAHOOK_ON_ARENA_START, script->OnArenaStart(bg));
}
References ARENAHOOK_ON_ARENA_START, CALL_ENABLED_HOOKS, and ArenaScript::OnArenaStart().
OnArenaTypeIDToQueueID()
void ScriptMgr::OnArenaTypeIDToQueueID (const BattlegroundTypeId bgTypeId, const uint8 arenaType, uint32 & queueTypeID)
{
    CALL_ENABLED_HOOKS(ArenaTeamScript, ARENATEAMHOOK_ON_TYPEID_TO_QUEUEID, script->OnTypeIDToQueueID(bgTypeId, arenaType, queueTypeID));
}
References ARENATEAMHOOK_ON_TYPEID_TO_QUEUEID, CALL_ENABLED_HOOKS, and ArenaTeamScript::OnTypeIDToQueueID().
OnAuctionAdd()
void ScriptMgr::OnAuctionAdd (AuctionHouseObject * ah, AuctionEntry * entry)
{
    ASSERT(ah);
    ASSERT(entry);
    CALL_ENABLED_HOOKS(AuctionHouseScript, AUCTIONHOUSEHOOK_ON_AUCTION_ADD, script->OnAuctionAdd(ah, entry));
}
References ASSERT, AUCTIONHOUSEHOOK_ON_AUCTION_ADD, CALL_ENABLED_HOOKS, and AuctionHouseScript::OnAuctionAdd().
OnAuctionExpire()
void ScriptMgr::OnAuctionExpire (AuctionHouseObject * ah, AuctionEntry * entry)
{
    ASSERT(ah);
    ASSERT(entry);
    CALL_ENABLED_HOOKS(AuctionHouseScript, AUCTIONHOUSEHOOK_ON_AUCTION_EXPIRE, script->OnAuctionExpire(ah, entry));
}
References ASSERT, AUCTIONHOUSEHOOK_ON_AUCTION_EXPIRE, CALL_ENABLED_HOOKS, and AuctionHouseScript::OnAuctionExpire().
OnAuctionRemove()
void ScriptMgr::OnAuctionRemove (AuctionHouseObject * ah, AuctionEntry * entry)
{
    ASSERT(ah);
    ASSERT(entry);
    CALL_ENABLED_HOOKS(AuctionHouseScript, AUCTIONHOUSEHOOK_ON_AUCTION_REMOVE, script->OnAuctionRemove(ah, entry));
}
References ASSERT, AUCTIONHOUSEHOOK_ON_AUCTION_REMOVE, CALL_ENABLED_HOOKS, and AuctionHouseScript::OnAuctionRemove().
OnAuctionSuccessful()
void ScriptMgr::OnAuctionSuccessful (AuctionHouseObject * ah, AuctionEntry * entry)
{
    ASSERT(ah);
    ASSERT(entry);
    CALL_ENABLED_HOOKS(AuctionHouseScript, AUCTIONHOUSEHOOK_ON_AUCTION_SUCCESSFUL, script->OnAuctionSuccessful(ah, entry));
}
References ASSERT, AUCTIONHOUSEHOOK_ON_AUCTION_SUCCESSFUL, CALL_ENABLED_HOOKS, and AuctionHouseScript::OnAuctionSuccessful().
OnAuraApply()
void ScriptMgr::OnAuraApply (Unit * unit, Aura * aura)
{
    CALL_ENABLED_HOOKS(UnitScript, UNITHOOK_ON_AURA_APPLY, script->OnAuraApply(unit, aura));
}
References CALL_ENABLED_HOOKS, UnitScript::OnAuraApply(), and UNITHOOK_ON_AURA_APPLY.
OnAuraRemove()
void ScriptMgr::OnAuraRemove (Unit * unit, AuraApplication * aurApp, AuraRemoveMode mode)
{
    CALL_ENABLED_HOOKS(UnitScript, UNITHOOK_ON_AURA_REMOVE, script->OnAuraRemove(unit, aurApp, mode));
}
References CALL_ENABLED_HOOKS, UnitScript::OnAuraRemove(), and UNITHOOK_ON_AURA_REMOVE.
OnBaseGainCalculation()
void ScriptMgr::OnBaseGainCalculation (uint32 & gain, uint8 playerLevel, uint8 mobLevel, ContentLevels content)
{
    CALL_ENABLED_HOOKS(FormulaScript, FORMULAHOOK_ON_BASE_GAIN_CALCULATION, script->OnBaseGainCalculation(gain, playerLevel, mobLevel, content));
}
References CALL_ENABLED_HOOKS, FORMULAHOOK_ON_BASE_GAIN_CALCULATION, and FormulaScript::OnBaseGainCalculation().
OnBattlegroundAddPlayer()
void ScriptMgr::OnBattlegroundAddPlayer (Battleground * bg, Player * player)
{
    CALL_ENABLED_HOOKS(AllBattlegroundScript, ALLBATTLEGROUNDHOOK_ON_BATTLEGROUND_ADD_PLAYER, script->OnBattlegroundAddPlayer(bg, player));
}
References ALLBATTLEGROUNDHOOK_ON_BATTLEGROUND_ADD_PLAYER, CALL_ENABLED_HOOKS, and AllBattlegroundScript::OnBattlegroundAddPlayer().
OnBattlegroundBeforeAddPlayer()
void ScriptMgr::OnBattlegroundBeforeAddPlayer (Battleground * bg, Player * player)
{
    CALL_ENABLED_HOOKS(AllBattlegroundScript, ALLBATTLEGROUNDHOOK_ON_BATTLEGROUND_BEFORE_ADD_PLAYER, script->OnBattlegroundBeforeAddPlayer(bg, player));
}
References ALLBATTLEGROUNDHOOK_ON_BATTLEGROUND_BEFORE_ADD_PLAYER, CALL_ENABLED_HOOKS, and AllBattlegroundScript::OnBattlegroundBeforeAddPlayer().
OnBattlegroundCreate()
void ScriptMgr::OnBattlegroundCreate (Battleground * bg)
{
    CALL_ENABLED_HOOKS(AllBattlegroundScript, ALLBATTLEGROUNDHOOK_ON_BATTLEGROUND_CREATE, script->OnBattlegroundCreate(bg));
}
References ALLBATTLEGROUNDHOOK_ON_BATTLEGROUND_CREATE, CALL_ENABLED_HOOKS, and AllBattlegroundScript::OnBattlegroundCreate().
OnBattlegroundDestroy()
void ScriptMgr::OnBattlegroundDestroy (Battleground * bg)
{
    CALL_ENABLED_HOOKS(AllBattlegroundScript, ALLBATTLEGROUNDHOOK_ON_BATTLEGROUND_DESTROY, script->OnBattlegroundDestroy(bg));
}
References ALLBATTLEGROUNDHOOK_ON_BATTLEGROUND_DESTROY, CALL_ENABLED_HOOKS, and AllBattlegroundScript::OnBattlegroundDestroy().
OnBattlegroundEnd()
void ScriptMgr::OnBattlegroundEnd (Battleground * bg, TeamId winnerTeamId)
{
    CALL_ENABLED_HOOKS(AllBattlegroundScript, ALLBATTLEGROUNDHOOK_ON_BATTLEGROUND_END, script->OnBattlegroundEnd(bg, winnerTeam));
}
References ALLBATTLEGROUNDHOOK_ON_BATTLEGROUND_END, CALL_ENABLED_HOOKS, and AllBattlegroundScript::OnBattlegroundEnd().
OnBattlegroundEndReward()
void ScriptMgr::OnBattlegroundEndReward (Battleground * bg, Player * player, TeamId winnerTeamId)
{
    CALL_ENABLED_HOOKS(AllBattlegroundScript, ALLBATTLEGROUNDHOOK_ON_BATTLEGROUND_END_REWARD, script->OnBattlegroundEndReward(bg, player, winnerTeamId));
}
References ALLBATTLEGROUNDHOOK_ON_BATTLEGROUND_END_REWARD, CALL_ENABLED_HOOKS, and AllBattlegroundScript::OnBattlegroundEndReward().
OnBattlegroundRemovePlayerAtLeave()
void ScriptMgr::OnBattlegroundRemovePlayerAtLeave (Battleground * bg, Player * player)
{
    CALL_ENABLED_HOOKS(AllBattlegroundScript, ALLBATTLEGROUNDHOOK_ON_BATTLEGROUND_REMOVE_PLAYER_AT_LEAVE, script->OnBattlegroundRemovePlayerAtLeave(bg, player));
}
References ALLBATTLEGROUNDHOOK_ON_BATTLEGROUND_REMOVE_PLAYER_AT_LEAVE, CALL_ENABLED_HOOKS, and AllBattlegroundScript::OnBattlegroundRemovePlayerAtLeave().
OnBattlegroundStart()
void ScriptMgr::OnBattlegroundStart (Battleground * bg)
{
    CALL_ENABLED_HOOKS(AllBattlegroundScript, ALLBATTLEGROUNDHOOK_ON_BATTLEGROUND_START, script->OnBattlegroundStart(bg));
}
References ALLBATTLEGROUNDHOOK_ON_BATTLEGROUND_START, CALL_ENABLED_HOOKS, and AllBattlegroundScript::OnBattlegroundStart().
OnBattlegroundUpdate()
void ScriptMgr::OnBattlegroundUpdate (Battleground * bg, uint32 diff)
{
    CALL_ENABLED_HOOKS(AllBattlegroundScript, ALLBATTLEGROUNDHOOK_ON_BATTLEGROUND_UPDATE, script->OnBattlegroundUpdate(bg, diff));
}
References ALLBATTLEGROUNDHOOK_ON_BATTLEGROUND_UPDATE, CALL_ENABLED_HOOKS, and AllBattlegroundScript::OnBattlegroundUpdate().
OnBeforeAccountDelete()
void ScriptMgr::OnBeforeAccountDelete (uint32 accountId)
{
    CALL_ENABLED_HOOKS(AccountScript, ACCOUNTHOOK_ON_BEFORE_ACCOUNT_DELETE, script->OnBeforeAccountDelete(accountId));
}
References ACCOUNTHOOK_ON_BEFORE_ACCOUNT_DELETE, CALL_ENABLED_HOOKS, and AccountScript::OnBeforeAccountDelete().
OnBeforeArenaCheckWinConditions()
bool ScriptMgr::OnBeforeArenaCheckWinConditions (Battleground *const bg)
{
    CALL_ENABLED_BOOLEAN_HOOKS(ArenaScript, ARENAHOOK_ON_BEFORE_CHECK_WIN_CONDITION, !script->OnBeforeArenaCheckWinConditions(bg));
}
References ARENAHOOK_ON_BEFORE_CHECK_WIN_CONDITION, CALL_ENABLED_BOOLEAN_HOOKS, and ArenaScript::OnBeforeArenaCheckWinConditions().
OnBeforeAuctionHouseMgrSendAuctionCancelledToBidderMail()
void ScriptMgr::OnBeforeAuctionHouseMgrSendAuctionCancelledToBidderMail (AuctionHouseMgr * auctionHouseMgr, AuctionEntry * auction, Player * bidder, uint32 & bidder_accId, bool & sendMail)
{
    CALL_ENABLED_HOOKS(AuctionHouseScript, AUCTIONHOUSEHOOK_ON_BEFORE_AUCTIONHOUSEMGR_SEND_AUCTION_CANCELLED_TO_BIDDER_MAIL, script->OnBeforeAuctionHouseMgrSendAuctionCancelledToBidderMail(auctionHouseMgr, auction, bidder, bidder_accId, sendMail));
}
References AUCTIONHOUSEHOOK_ON_BEFORE_AUCTIONHOUSEMGR_SEND_AUCTION_CANCELLED_TO_BIDDER_MAIL, CALL_ENABLED_HOOKS, and AuctionHouseScript::OnBeforeAuctionHouseMgrSendAuctionCancelledToBidderMail().
OnBeforeAuctionHouseMgrSendAuctionExpiredMail()
void ScriptMgr::OnBeforeAuctionHouseMgrSendAuctionExpiredMail (AuctionHouseMgr * auctionHouseMgr, AuctionEntry * auction, Player * owner, uint32 & owner_accId, bool & sendNotification, bool & sendMail)
{
    CALL_ENABLED_HOOKS(AuctionHouseScript, AUCTIONHOUSEHOOK_ON_BEFORE_AUCTIONHOUSEMGR_SEND_AUCTION_EXPIRED_MAIL, script->OnBeforeAuctionHouseMgrSendAuctionExpiredMail(auctionHouseMgr, auction, owner, owner_accId, sendNotification, sendMail));
}
References AUCTIONHOUSEHOOK_ON_BEFORE_AUCTIONHOUSEMGR_SEND_AUCTION_EXPIRED_MAIL, CALL_ENABLED_HOOKS, and AuctionHouseScript::OnBeforeAuctionHouseMgrSendAuctionExpiredMail().
OnBeforeAuctionHouseMgrSendAuctionOutbiddedMail()
void ScriptMgr::OnBeforeAuctionHouseMgrSendAuctionOutbiddedMail (AuctionHouseMgr * auctionHouseMgr, AuctionEntry * auction, Player * oldBidder, uint32 & oldBidder_accId, Player * newBidder, uint32 & newPrice, bool & sendNotification, bool & sendMail)
{
    CALL_ENABLED_HOOKS(AuctionHouseScript, AUCTIONHOUSEHOOK_ON_BEFORE_AUCTIONHOUSEMGR_SEND_AUCTION_OUTBIDDED_MAIL, script->OnBeforeAuctionHouseMgrSendAuctionOutbiddedMail(auctionHouseMgr, auction, oldBidder, oldBidder_accId, newBidder, newPrice, sendNotification, sendMail));
}
References AUCTIONHOUSEHOOK_ON_BEFORE_AUCTIONHOUSEMGR_SEND_AUCTION_OUTBIDDED_MAIL, CALL_ENABLED_HOOKS, and AuctionHouseScript::OnBeforeAuctionHouseMgrSendAuctionOutbiddedMail().
OnBeforeAuctionHouseMgrSendAuctionSalePendingMail()
void ScriptMgr::OnBeforeAuctionHouseMgrSendAuctionSalePendingMail (AuctionHouseMgr * auctionHouseMgr, AuctionEntry * auction, Player * owner, uint32 & owner_accId, bool & sendMail)
{
    CALL_ENABLED_HOOKS(AuctionHouseScript, AUCTIONHOUSEHOOK_ON_BEFORE_AUCTIONHOUSEMGR_SEND_AUCTION_SALE_PENDING_MAIL, script->OnBeforeAuctionHouseMgrSendAuctionSalePendingMail(auctionHouseMgr, auction, owner, owner_accId, sendMail));
}
References AUCTIONHOUSEHOOK_ON_BEFORE_AUCTIONHOUSEMGR_SEND_AUCTION_SALE_PENDING_MAIL, CALL_ENABLED_HOOKS, and AuctionHouseScript::OnBeforeAuctionHouseMgrSendAuctionSalePendingMail().
OnBeforeAuctionHouseMgrSendAuctionSuccessfulMail()
void ScriptMgr::OnBeforeAuctionHouseMgrSendAuctionSuccessfulMail (AuctionHouseMgr * auctionHouseMgr, AuctionEntry * auction, Player * owner, uint32 & owner_accId, uint32 & profit, bool & sendNotification, bool & updateAchievementCriteria, bool & sendMail)
{
    CALL_ENABLED_HOOKS(AuctionHouseScript, AUCTIONHOUSEHOOK_ON_BEFORE_AUCTIONHOUSEMGR_SEND_AUCTION_SUCCESSFUL_MAIL, script->OnBeforeAuctionHouseMgrSendAuctionSuccessfulMail(auctionHouseMgr, auction, owner, owner_accId, profit, sendNotification, updateAchievementCriteria, sendMail));
}
References AUCTIONHOUSEHOOK_ON_BEFORE_AUCTIONHOUSEMGR_SEND_AUCTION_SUCCESSFUL_MAIL, CALL_ENABLED_HOOKS, and AuctionHouseScript::OnBeforeAuctionHouseMgrSendAuctionSuccessfulMail().
OnBeforeAuctionHouseMgrSendAuctionWonMail()
void ScriptMgr::OnBeforeAuctionHouseMgrSendAuctionWonMail (AuctionHouseMgr * auctionHouseMgr, AuctionEntry * auction, Player * bidder, uint32 & bidder_accId, bool & sendNotification, bool & updateAchievementCriteria, bool & sendMail)
{
    CALL_ENABLED_HOOKS(AuctionHouseScript, AUCTIONHOUSEHOOK_ON_BEFORE_AUCTIONHOUSEMGR_SEND_AUCTION_WON_MAIL, script->OnBeforeAuctionHouseMgrSendAuctionWonMail(auctionHouseMgr, auction, bidder, bidder_accId, sendNotification, updateAchievementCriteria, sendMail));
}
References AUCTIONHOUSEHOOK_ON_BEFORE_AUCTIONHOUSEMGR_SEND_AUCTION_WON_MAIL, CALL_ENABLED_HOOKS, and AuctionHouseScript::OnBeforeAuctionHouseMgrSendAuctionWonMail().
OnBeforeAuctionHouseMgrUpdate()
void ScriptMgr::OnBeforeAuctionHouseMgrUpdate ()
{
    CALL_ENABLED_HOOKS(AuctionHouseScript, AUCTIONHOUSEHOOK_ON_BEFORE_AUCTIONHOUSEMGR_UPDATE, script->OnBeforeAuctionHouseMgrUpdate());
}
References AUCTIONHOUSEHOOK_ON_BEFORE_AUCTIONHOUSEMGR_UPDATE, CALL_ENABLED_HOOKS, and AuctionHouseScript::OnBeforeAuctionHouseMgrUpdate().
OnBeforeAuraRankForLevel()
void ScriptMgr::OnBeforeAuraRankForLevel (SpellInfo const * spellInfo, SpellInfo const * latestSpellInfo, uint8 level)
{
    CALL_ENABLED_HOOKS(AllSpellScript, ALLSPELLHOOK_ON_BEFORE_AURA_RANK_FOR_LEVEL, script->OnBeforeAuraRankForLevel(spellInfo, latestSpellInfo, level));
}
References ALLSPELLHOOK_ON_BEFORE_AURA_RANK_FOR_LEVEL, CALL_ENABLED_HOOKS, and AllSpellScript::OnBeforeAuraRankForLevel().
OnBeforeCheckCriteria()
void ScriptMgr::OnBeforeCheckCriteria (AchievementMgr * mgr, AchievementCriteriaEntryList const * achievementCriteriaList)
{
    CALL_ENABLED_HOOKS(AchievementScript, ACHIEVEMENTHOOK_ON_BEFORE_CHECK_CRITERIA, script->OnBeforeCheckCriteria(mgr, achievementCriteriaList));
}
References ACHIEVEMENTHOOK_ON_BEFORE_CHECK_CRITERIA, CALL_ENABLED_HOOKS, and AchievementScript::OnBeforeCheckCriteria().
OnBeforeConfigLoad()
void ScriptMgr::OnBeforeConfigLoad (bool reload)
{
    CALL_ENABLED_HOOKS(WorldScript, WORLDHOOK_ON_BEFORE_CONFIG_LOAD, script->OnBeforeConfigLoad(reload));
}
References CALL_ENABLED_HOOKS, WorldScript::OnBeforeConfigLoad(), and WORLDHOOK_ON_BEFORE_CONFIG_LOAD.
OnBeforeCreateInstanceScript()
void ScriptMgr::OnBeforeCreateInstanceScript (InstanceMap * instanceMap, InstanceScript ** instanceData, bool load, std::string data, uint32 completedEncounterMask)
{
    CALL_ENABLED_HOOKS(AllMapScript, ALLMAPHOOK_ON_BEFORE_CREATE_INSTANCE_SCRIPT, script->OnBeforeCreateInstanceScript(instanceMap, instanceData, load, data, completedEncounterMask));
}
References ALLMAPHOOK_ON_BEFORE_CREATE_INSTANCE_SCRIPT, CALL_ENABLED_HOOKS, and AllMapScript::OnBeforeCreateInstanceScript().
OnBeforeCreatureSelectLevel()
void ScriptMgr::OnBeforeCreatureSelectLevel (const CreatureTemplate * cinfo, Creature * creature, uint8 & level)
{
    ExecuteScript<AllCreatureScript>([&](AllCreatureScript* script)
    {
        script->OnBeforeCreatureSelectLevel(cinfo, creature, level);
    });
}
References AllCreatureScript::OnBeforeCreatureSelectLevel().
OnBeforeDropAddItem()
void ScriptMgr::OnBeforeDropAddItem (Player const * player, Loot & loot, bool canRate, uint16 lootMode, LootStoreItem * LootStoreItem, LootStore const & store)
{
    CALL_ENABLED_HOOKS(GlobalScript, GLOBALHOOK_ON_BEFORE_DROP_ADD_ITEM, script->OnBeforeDropAddItem(player, loot, canRate, lootMode, LootStoreItem, store));
}
References CALL_ENABLED_HOOKS, GLOBALHOOK_ON_BEFORE_DROP_ADD_ITEM, and GlobalScript::OnBeforeDropAddItem().
OnBeforeFinalizePlayerWorldSession()
void ScriptMgr::OnBeforeFinalizePlayerWorldSession (uint32 & cacheVersion)
{
    CALL_ENABLED_HOOKS(WorldScript, WORLDHOOK_ON_BEFORE_FINALIZE_PLAYER_WORLD_SESSION, script->OnBeforeFinalizePlayerWorldSession(cacheVersion));
}
References CALL_ENABLED_HOOKS, WorldScript::OnBeforeFinalizePlayerWorldSession(), and WORLDHOOK_ON_BEFORE_FINALIZE_PLAYER_WORLD_SESSION.
OnBeforeIsInvokerVisible()
bool ScriptMgr::OnBeforeIsInvokerVisible (std::string name, Acore::Impl::ChatCommands::CommandPermissions permissions, ChatHandler const & who)
{
    CALL_ENABLED_BOOLEAN_HOOKS(AllCommandScript, ALLCOMMANDHOOK_ON_BEFORE_IS_INVOKER_VISIBLE, !script->OnBeforeIsInvokerVisible(name, permissions, who));
}
References ALLCOMMANDHOOK_ON_BEFORE_IS_INVOKER_VISIBLE, CALL_ENABLED_BOOLEAN_HOOKS, and AllCommandScript::OnBeforeIsInvokerVisible().
OnBeforeLootEqualChanced()
bool ScriptMgr::OnBeforeLootEqualChanced (Player const * player, LootStoreItemList EqualChanced, Loot & loot, LootStore const & store)
{
    CALL_ENABLED_BOOLEAN_HOOKS(GlobalScript, GLOBALHOOK_ON_BEFORE_LOOT_EQUAL_CHANCED, !script->OnBeforeLootEqualChanced(player, equalChanced, loot, store));
}
References CALL_ENABLED_BOOLEAN_HOOKS, GLOBALHOOK_ON_BEFORE_LOOT_EQUAL_CHANCED, and GlobalScript::OnBeforeLootEqualChanced().
OnBeforeMailDraftSendMailTo()
void ScriptMgr::OnBeforeMailDraftSendMailTo (MailDraft * mailDraft, MailReceiver const & receiver, MailSender const & sender, MailCheckMask & checked, uint32 & deliver_delay, uint32 & custom_expiration, bool & deleteMailItemsFromDB, bool & sendMail)
{
    CALL_ENABLED_HOOKS(MailScript, MAILHOOK_ON_BEFORE_MAIL_DRAFT_SEND_MAIL_TO, script->OnBeforeMailDraftSendMailTo(mailDraft, receiver, sender, checked, deliver_delay, custom_expiration, deleteMailItemsFromDB, sendMail));
}
References CALL_ENABLED_HOOKS, MAILHOOK_ON_BEFORE_MAIL_DRAFT_SEND_MAIL_TO, and MailScript::OnBeforeMailDraftSendMailTo().
OnBeforeRollMeleeOutcomeAgainst()
void ScriptMgr::OnBeforeRollMeleeOutcomeAgainst (Unit const * attacker, Unit const * victim, WeaponAttackType attType, int32 & attackerMaxSkillValueForLevel, int32 & victimMaxSkillValueForLevel, int32 & attackerWeaponSkill, int32 & victimDefenseSkill, int32 & crit_chance, int32 & miss_chance, int32 & dodge_chance, int32 & parry_chance, int32 & block_chance)
{
    CALL_ENABLED_HOOKS(UnitScript, UNITHOOK_ON_BEFORE_ROLL_MELEE_OUTCOME_AGAINST, script->OnBeforeRollMeleeOutcomeAgainst(attacker, victim, attType, attackerMaxSkillValueForLevel, victimMaxSkillValueForLevel, attackerWeaponSkill, victimDefenseSkill, crit_chance, miss_chance, dodge_chance, parry_chance, block_chance));
}
References CALL_ENABLED_HOOKS, UnitScript::OnBeforeRollMeleeOutcomeAgainst(), and UNITHOOK_ON_BEFORE_ROLL_MELEE_OUTCOME_AGAINST.
OnBeforeSendExitMessageArenaQueue()
bool ScriptMgr::OnBeforeSendExitMessageArenaQueue (BattlegroundQueue * queue, GroupQueueInfo * ginfo)
{
    CALL_ENABLED_BOOLEAN_HOOKS(AllBattlegroundScript, ALLBATTLEGROUNDHOOK_ON_BEFORE_SEND_EXIT_MESSAGE_ARENA_QUEUE, !script->OnBeforeSendExitMessageArenaQueue(queue, ginfo));
}
References ALLBATTLEGROUNDHOOK_ON_BEFORE_SEND_EXIT_MESSAGE_ARENA_QUEUE, CALL_ENABLED_BOOLEAN_HOOKS, and AllBattlegroundScript::OnBeforeSendExitMessageArenaQueue().
OnBeforeSendJoinMessageArenaQueue()
bool ScriptMgr::OnBeforeSendJoinMessageArenaQueue (BattlegroundQueue * queue, Player * leader, GroupQueueInfo * ginfo, PvPDifficultyEntry const * bracketEntry, bool isRated)
{
    CALL_ENABLED_BOOLEAN_HOOKS(AllBattlegroundScript, ALLBATTLEGROUNDHOOK_ON_BEFORE_SEND_JOIN_MESSAGE_ARENA_QUEUE, !script->OnBeforeSendJoinMessageArenaQueue(queue, leader, ginfo, bracketEntry, isRated));
}
References ALLBATTLEGROUNDHOOK_ON_BEFORE_SEND_JOIN_MESSAGE_ARENA_QUEUE, CALL_ENABLED_BOOLEAN_HOOKS, and AllBattlegroundScript::OnBeforeSendJoinMessageArenaQueue().
OnBeforeSetBossState()
void ScriptMgr::OnBeforeSetBossState (uint32 id, EncounterState newState, EncounterState oldState, Map * instance)
Called when any raid boss has their state updated (e.g. pull, reset, kill).
Careful checks for old- and newState are required, since it can fire multiple times and not only when combat starts/ends.
Parameters
id The id of the boss in the [instance]
newState The new boss state to be applied to this boss
oldState The previously assigned state of this boss
instance A pointer to the [map] object of the instance
{
    CALL_ENABLED_HOOKS(GlobalScript, GLOBALHOOK_ON_BEFORE_SET_BOSS_STATE, script->OnBeforeSetBossState(id, newState, oldState, instance));
}
References CALL_ENABLED_HOOKS, GLOBALHOOK_ON_BEFORE_SET_BOSS_STATE, instance(), and GlobalScript::OnBeforeSetBossState().
OnBeforeUpdateArenaPoints()
void ScriptMgr::OnBeforeUpdateArenaPoints (ArenaTeam * at, std::map< ObjectGuid, uint32 > & ap)
{
    CALL_ENABLED_HOOKS(GlobalScript, GLOBALHOOK_ON_BEFORE_UPDATE_ARENA_POINTS, script->OnBeforeUpdateArenaPoints(at, ap));
}
References CALL_ENABLED_HOOKS, GLOBALHOOK_ON_BEFORE_UPDATE_ARENA_POINTS, and GlobalScript::OnBeforeUpdateArenaPoints().
OnBeforeUpdatingPersonalRating()
void ScriptMgr::OnBeforeUpdatingPersonalRating (int32 & mod, uint32 type)
{
    CALL_ENABLED_HOOKS(FormulaScript, FORMULAHOOK_ON_BEFORE_UPDATING_PERSONAL_RATING, script->OnBeforeUpdatingPersonalRating(mod, type));
}
References CALL_ENABLED_HOOKS, FORMULAHOOK_ON_BEFORE_UPDATING_PERSONAL_RATING, and FormulaScript::OnBeforeUpdatingPersonalRating().
OnBeforeWorldInitialized()
void ScriptMgr::OnBeforeWorldInitialized ()
{
    CALL_ENABLED_HOOKS(WorldScript, WORLDHOOK_ON_BEFORE_WORLD_INITIALIZED, script->OnBeforeWorldInitialized());
}
References CALL_ENABLED_HOOKS, WorldScript::OnBeforeWorldInitialized(), and WORLDHOOK_ON_BEFORE_WORLD_INITIALIZED.
OnBeforeWorldObjectSetPhaseMask()
void ScriptMgr::OnBeforeWorldObjectSetPhaseMask (WorldObject const * worldObject, uint32 & oldPhaseMask, uint32 & newPhaseMask, bool & useCombinedPhases, bool & update)
{
    CALL_ENABLED_HOOKS(GlobalScript, GLOBALHOOK_ON_BEFORE_WORLDOBJECT_SET_PHASEMASK, script->OnBeforeWorldObjectSetPhaseMask(worldObject, oldPhaseMask, newPhaseMask, useCombinedPhases, update));
}
References CALL_ENABLED_HOOKS, GLOBALHOOK_ON_BEFORE_WORLDOBJECT_SET_PHASEMASK, and GlobalScript::OnBeforeWorldObjectSetPhaseMask().
OnCalcMaxDuration()
void ScriptMgr::OnCalcMaxDuration (Aura const * aura, int32 & maxDuration)
{
    CALL_ENABLED_HOOKS(AllSpellScript, ALLSPELLHOOK_ON_CALC_MAX_DURATION, script->OnCalcMaxDuration(aura, maxDuration));
}
References ALLSPELLHOOK_ON_CALC_MAX_DURATION, CALL_ENABLED_HOOKS, and AllSpellScript::OnCalcMaxDuration().
OnCalculateMaxTalentPointsForLevel()
void ScriptMgr::OnCalculateMaxTalentPointsForLevel (Pet * pet, uint8 level, uint8 & points)
{
    CALL_ENABLED_HOOKS(PetScript, PETHOOK_ON_CALCULATE_MAX_TALENT_POINTS_FOR_LEVEL, script->OnCalculateMaxTalentPointsForLevel(pet, level, points));
}
References CALL_ENABLED_HOOKS, PetScript::OnCalculateMaxTalentPointsForLevel(), and PETHOOK_ON_CALCULATE_MAX_TALENT_POINTS_FOR_LEVEL.
OnCastItemCombatSpell()
bool ScriptMgr::OnCastItemCombatSpell (Player * player, Unit * victim, SpellInfo const * spellInfo, Item * item)
{
    ASSERT(player);
    ASSERT(victim);
    ASSERT(spellInfo);
    ASSERT(item);
    auto tempScript = ScriptRegistry<ItemScript>::GetScriptById(item->GetScriptId());
    return tempScript ? tempScript->OnCastItemCombatSpell(player, victim, spellInfo, item) : true;
}
References ASSERT, ScriptRegistry< TScript >::GetScriptById(), and Item::GetScriptId().
OnColorCodeCalculation()
void ScriptMgr::OnColorCodeCalculation (XPColorChar & color, uint8 playerLevel, uint8 mobLevel)
{
    CALL_ENABLED_HOOKS(FormulaScript, FORMULAHOOK_ON_COLOR_CODE_CALCULATION, script->OnColorCodeCalculation(color, playerLevel, mobLevel));
}
References CALL_ENABLED_HOOKS, FORMULAHOOK_ON_COLOR_CODE_CALCULATION, and FormulaScript::OnColorCodeCalculation().
OnConditionCheck()
bool ScriptMgr::OnConditionCheck (Condition * condition, ConditionSourceInfo & sourceInfo)
{
    ASSERT(condition);
    auto tempScript = ScriptRegistry<ConditionScript>::GetScriptById(condition->ScriptId);
    return tempScript ? tempScript->OnConditionCheck(condition, sourceInfo) : true;
}
References ASSERT, ScriptRegistry< TScript >::GetScriptById(), and Condition::ScriptId.
OnConstructGroup()
void ScriptMgr::OnConstructGroup (Group * origin)
{
    CALL_ENABLED_HOOKS(MiscScript, MISCHOOK_ON_CONSTRUCT_GROUP, script->OnConstructGroup(origin));
}
References CALL_ENABLED_HOOKS, MISCHOOK_ON_CONSTRUCT_GROUP, and MiscScript::OnConstructGroup().
OnConstructInstanceSave()
void ScriptMgr::OnConstructInstanceSave (InstanceSave * origin)
{
    CALL_ENABLED_HOOKS(MiscScript, MISCHOOK_ON_CONSTRUCT_INSTANCE_SAVE, script->OnConstructInstanceSave(origin));
}
References CALL_ENABLED_HOOKS, MISCHOOK_ON_CONSTRUCT_INSTANCE_SAVE, and MiscScript::OnConstructInstanceSave().
OnConstructObject()
void ScriptMgr::OnConstructObject (Object * origin)
{
    CALL_ENABLED_HOOKS(MiscScript, MISCHOOK_ON_CONSTRUCT_OBJECT, script->OnConstructObject(origin));
}
References CALL_ENABLED_HOOKS, MISCHOOK_ON_CONSTRUCT_OBJECT, and MiscScript::OnConstructObject().
OnConstructPlayer()
void ScriptMgr::OnConstructPlayer (Player * origin)
{
    CALL_ENABLED_HOOKS(MiscScript, MISCHOOK_ON_CONSTRUCT_PLAYER, script->OnConstructPlayer(origin));
}
References CALL_ENABLED_HOOKS, MISCHOOK_ON_CONSTRUCT_PLAYER, and MiscScript::OnConstructPlayer().
OnCreate()
void ScriptMgr::OnCreate (Group * group, Player * leader)
{
    CALL_ENABLED_HOOKS(GroupScript, GROUPHOOK_ON_CREATE, script->OnCreate(group, leader));
}
References CALL_ENABLED_HOOKS, GROUPHOOK_ON_CREATE, and GroupScript::OnCreate().
OnCreateMap()
void ScriptMgr::OnCreateMap (Map * map)
{
    ASSERT(map);
    CALL_ENABLED_HOOKS(AllMapScript, ALLMAPHOOK_ON_CREATE_MAP, script->OnCreateMap(map));
    ForeachMaps<WorldMapScript>(map,
    [&](WorldMapScript* script)
    {
        script->OnCreate(map);
    });
    ForeachMaps<InstanceMapScript>(map,
    [&](InstanceMapScript* script)
    {
        script->OnCreate((InstanceMap*)map);
    });
    ForeachMaps<BattlegroundMapScript>(map,
    [&](BattlegroundMapScript* script)
    {
        script->OnCreate((BattlegroundMap*)map);
    });
}
References ALLMAPHOOK_ON_CREATE_MAP, ASSERT, CALL_ENABLED_HOOKS, MapScript< TMap >::OnCreate(), and AllMapScript::OnCreateMap().
OnCreatureAddWorld()
void ScriptMgr::OnCreatureAddWorld (Creature * creature)
{
    ASSERT(creature);
    ExecuteScript<AllCreatureScript>([&](AllCreatureScript* script)
    {
        script->OnCreatureAddWorld(creature);
    });
}
References ASSERT, and AllCreatureScript::OnCreatureAddWorld().
OnCreatureRemoveWorld()
void ScriptMgr::OnCreatureRemoveWorld (Creature * creature)
{
    ASSERT(creature);
    ExecuteScript<AllCreatureScript>([&](AllCreatureScript* script)
    {
        script->OnCreatureRemoveWorld(creature);
    });
}
References ASSERT, and AllCreatureScript::OnCreatureRemoveWorld().
OnCreatureSaveToDB()
void ScriptMgr::OnCreatureSaveToDB (Creature * creature)
{
    ASSERT(creature);
    ExecuteScript<AllCreatureScript>([&](AllCreatureScript* script)
    {
        script->OnCreatureSaveToDB(creature);
    });
}
References ASSERT, and AllCreatureScript::OnCreatureSaveToDB().
OnCreatureUpdate()
void ScriptMgr::OnCreatureUpdate (Creature * creature, uint32 diff)
{
    ASSERT(creature);
    ExecuteScript<AllCreatureScript>([&](AllCreatureScript* script)
    {
        script->OnAllCreatureUpdate(creature, diff);
    });
    if (auto tempScript = ScriptRegistry<CreatureScript>::GetScriptById(creature->GetScriptId()))
    {
        tempScript->OnUpdate(creature, diff);
    }
}
References ASSERT, Creature::GetScriptId(), and AllCreatureScript::OnAllCreatureUpdate().
OnCriteriaCheck()
bool ScriptMgr::OnCriteriaCheck (uint32 scriptId, Player * source, Unit * target, uint32 criteria_id)
{
    ASSERT(source);
    // target can be nullptr.
    auto tempScript = ScriptRegistry<AchievementCriteriaScript>::GetScriptById(scriptId);
    return tempScript ? tempScript->OnCheck(source, target, criteria_id) : false;
}
References ASSERT, and ScriptRegistry< TScript >::GetScriptById().
OnDamage()
void ScriptMgr::OnDamage (Unit * attacker, Unit * victim, uint32 & damage)
{
    CALL_ENABLED_HOOKS(UnitScript, UNITHOOK_ON_DAMAGE, script->OnDamage(attacker, victim, damage));
}
References CALL_ENABLED_HOOKS, UnitScript::OnDamage(), and UNITHOOK_ON_DAMAGE.
OnDestroyInstance()
void ScriptMgr::OnDestroyInstance (MapInstanced * mapInstanced, Map * map)
{
    CALL_ENABLED_HOOKS(AllMapScript, ALLMAPHOOK_ON_DESTROY_INSTANCE, script->OnDestroyInstance(mapInstanced, map));
}
References ALLMAPHOOK_ON_DESTROY_INSTANCE, CALL_ENABLED_HOOKS, and AllMapScript::OnDestroyInstance().
OnDestroyMap()
void ScriptMgr::OnDestroyMap (Map * map)
{
    ASSERT(map);
    CALL_ENABLED_HOOKS(AllMapScript, ALLMAPHOOK_ON_DESTROY_MAP, script->OnDestroyMap(map));
    ForeachMaps<WorldMapScript>(map,
    [&](WorldMapScript* script)
    {
        script->OnDestroy(map);
    });
    ForeachMaps<InstanceMapScript>(map,
    [&](InstanceMapScript* script)
    {
        script->OnDestroy((InstanceMap*)map);
    });
    ForeachMaps<BattlegroundMapScript>(map,
    [&](BattlegroundMapScript* script)
    {
        script->OnDestroy((BattlegroundMap*)map);
    });
}
References ALLMAPHOOK_ON_DESTROY_MAP, ASSERT, CALL_ENABLED_HOOKS, MapScript< TMap >::OnDestroy(), and AllMapScript::OnDestroyMap().
OnDestructGroup()
void ScriptMgr::OnDestructGroup (Group * origin)
{
    CALL_ENABLED_HOOKS(MiscScript, MISCHOOK_ON_DESTRUCT_GROUP, script->OnDestructGroup(origin));
}
References CALL_ENABLED_HOOKS, MISCHOOK_ON_DESTRUCT_GROUP, and MiscScript::OnDestructGroup().
OnDestructInstanceSave()
void ScriptMgr::OnDestructInstanceSave (InstanceSave * origin)
{
    CALL_ENABLED_HOOKS(MiscScript, MISCHOOK_ON_DESTRUCT_INSTANCE_SAVE, script->OnDestructInstanceSave(origin));
}
References CALL_ENABLED_HOOKS, MISCHOOK_ON_DESTRUCT_INSTANCE_SAVE, and MiscScript::OnDestructInstanceSave().
OnDestructObject()
void ScriptMgr::OnDestructObject (Object * origin)
{
    CALL_ENABLED_HOOKS(MiscScript, MISCHOOK_ON_DESTRUCT_OBJECT, script->OnDestructObject(origin));
}
References CALL_ENABLED_HOOKS, MISCHOOK_ON_DESTRUCT_OBJECT, and MiscScript::OnDestructObject().
OnDestructPlayer()
void ScriptMgr::OnDestructPlayer (Player * origin)
{
    CALL_ENABLED_HOOKS(MiscScript, MISCHOOK_ON_DESTRUCT_PLAYER, script->OnDestructPlayer(origin));
}
References CALL_ENABLED_HOOKS, MISCHOOK_ON_DESTRUCT_PLAYER, and MiscScript::OnDestructPlayer().
OnDisplayIdChange()
void ScriptMgr::OnDisplayIdChange (Unit * unit, uint32 displayId)
{
    CALL_ENABLED_HOOKS(UnitScript, UNITHOOK_ON_DISPLAYID_CHANGE, script->OnDisplayIdChange(unit, displayId));
}
References CALL_ENABLED_HOOKS, UnitScript::OnDisplayIdChange(), and UNITHOOK_ON_DISPLAYID_CHANGE.
OnDummyEffect() [1/3]
void ScriptMgr::OnDummyEffect (WorldObject * caster, uint32 spellID, SpellEffIndex effIndex, Creature * creatureTarget)
{
    CALL_ENABLED_HOOKS(AllSpellScript, ALLSPELLHOOK_ON_DUMMY_EFFECT_CREATURE, script->OnDummyEffect(caster, spellID, effIndex, creatureTarget));
}
References ALLSPELLHOOK_ON_DUMMY_EFFECT_CREATURE, CALL_ENABLED_HOOKS, and AllSpellScript::OnDummyEffect().
OnDummyEffect() [2/3]
void ScriptMgr::OnDummyEffect (WorldObject * caster, uint32 spellID, SpellEffIndex effIndex, GameObject * gameObjTarget)
{
    CALL_ENABLED_HOOKS(AllSpellScript, ALLSPELLHOOK_ON_DUMMY_EFFECT_GAMEOBJECT, script->OnDummyEffect(caster, spellID, effIndex, gameObjTarget));
}
References ALLSPELLHOOK_ON_DUMMY_EFFECT_GAMEOBJECT, CALL_ENABLED_HOOKS, and AllSpellScript::OnDummyEffect().
OnDummyEffect() [3/3]
void ScriptMgr::OnDummyEffect (WorldObject * caster, uint32 spellID, SpellEffIndex effIndex, Item * itemTarget)
{
    CALL_ENABLED_HOOKS(AllSpellScript, ALLSPELLHOOK_ON_DUMMY_EFFECT_ITEM, script->OnDummyEffect(caster, spellID, effIndex, itemTarget));
}
References ALLSPELLHOOK_ON_DUMMY_EFFECT_ITEM, CALL_ENABLED_HOOKS, and AllSpellScript::OnDummyEffect().
OnDynamicObjectUpdate()
void ScriptMgr::OnDynamicObjectUpdate (DynamicObject * dynobj, uint32 diff)
{
    ASSERT(dynobj);
    for (auto const& [scriptID, script] : ScriptRegistry<DynamicObjectScript>::ScriptPointerList)
    {
        script->OnUpdate(dynobj, diff);
    }
}
References ASSERT.
OnEmailChange()
void ScriptMgr::OnEmailChange (uint32 accountId)
{
    CALL_ENABLED_HOOKS(AccountScript, ACCOUNTHOOK_ON_EMAIL_CHANGE, script->OnEmailChange(accountId));
}
References ACCOUNTHOOK_ON_EMAIL_CHANGE, CALL_ENABLED_HOOKS, and AccountScript::OnEmailChange().
OnFailedAccountLogin()
void ScriptMgr::OnFailedAccountLogin (uint32 accountId)
{
    CALL_ENABLED_HOOKS(AccountScript, ACCOUNTHOOK_ON_FAILED_ACCOUNT_LOGIN, script->OnFailedAccountLogin(accountId));
}
References ACCOUNTHOOK_ON_FAILED_ACCOUNT_LOGIN, CALL_ENABLED_HOOKS, and AccountScript::OnFailedAccountLogin().
OnFailedEmailChange()
void ScriptMgr::OnFailedEmailChange (uint32 accountId)
{
    CALL_ENABLED_HOOKS(AccountScript, ACCOUNTHOOK_ON_FAILED_EMAIL_CHANGE, script->OnFailedEmailChange(accountId));
}
References ACCOUNTHOOK_ON_FAILED_EMAIL_CHANGE, CALL_ENABLED_HOOKS, and AccountScript::OnFailedEmailChange().
OnFailedPasswordChange()
void ScriptMgr::OnFailedPasswordChange (uint32 accountId)
{
    CALL_ENABLED_HOOKS(AccountScript, ACCOUNTHOOK_ON_FAILED_PASSWORD_CHANGE, script->OnFailedPasswordChange(accountId));
}
References ACCOUNTHOOK_ON_FAILED_PASSWORD_CHANGE, CALL_ENABLED_HOOKS, and AccountScript::OnFailedPasswordChange().
OnFfaPvpStateUpdate()
void ScriptMgr::OnFfaPvpStateUpdate (Creature * creature, bool InPvp)
{
    ExecuteScript<AllCreatureScript>([&](AllCreatureScript* script)
        {
            script->OnFfaPvpStateUpdate(creature, InPvp);
        });
}
References AllCreatureScript::OnFfaPvpStateUpdate().
OnGainCalculation()
void ScriptMgr::OnGainCalculation (uint32 & gain, Player * player, Unit * unit)
{
    ASSERT(player);
    ASSERT(unit);
    CALL_ENABLED_HOOKS(FormulaScript, FORMULAHOOK_ON_GAIN_CALCULATION, script->OnGainCalculation(gain, player, unit));
}
References ASSERT, CALL_ENABLED_HOOKS, FORMULAHOOK_ON_GAIN_CALCULATION, and FormulaScript::OnGainCalculation().
OnGameEventCheck()
void ScriptMgr::OnGameEventCheck (uint16 EventID)
{
    CALL_ENABLED_HOOKS(GameEventScript, GAMEEVENTHOOK_ON_EVENT_CHECK, script->OnEventCheck(EventID));
}
References CALL_ENABLED_HOOKS, GAMEEVENTHOOK_ON_EVENT_CHECK, and GameEventScript::OnEventCheck().
OnGameEventStart()
void ScriptMgr::OnGameEventStart (uint16 EventID)
{
    CALL_ENABLED_HOOKS(GameEventScript, GAMEEVENTHOOK_ON_START, script->OnStart(EventID));
}
References CALL_ENABLED_HOOKS, GAMEEVENTHOOK_ON_START, and GameEventScript::OnStart().
OnGameEventStop()
void ScriptMgr::OnGameEventStop (uint16 EventID)
{
    CALL_ENABLED_HOOKS(GameEventScript, GAMEEVENTHOOK_ON_STOP, script->OnStop(EventID));
}
References CALL_ENABLED_HOOKS, GAMEEVENTHOOK_ON_STOP, and GameEventScript::OnStop().
OnGameObjectAddWorld()
void ScriptMgr::OnGameObjectAddWorld (GameObject * go)
{
    ASSERT(go);
    ExecuteScript<AllGameObjectScript>([&](AllGameObjectScript* script)
    {
        script->OnGameObjectAddWorld(go);
    });
}
References ASSERT, and AllGameObjectScript::OnGameObjectAddWorld().
OnGameObjectDamaged()
void ScriptMgr::OnGameObjectDamaged (GameObject * go, Player * player)
{
    ASSERT(go);
    ExecuteScript<AllGameObjectScript>([&](AllGameObjectScript* script)
    {
        script->OnGameObjectDamaged(go, player);
    });
    if (auto tempScript = ScriptRegistry<GameObjectScript>::GetScriptById(go->GetScriptId()))
    {
        tempScript->OnDamaged(go, player);
    }
}
References ASSERT, GameObject::GetScriptId(), and AllGameObjectScript::OnGameObjectDamaged().
OnGameObjectDestroyed()
void ScriptMgr::OnGameObjectDestroyed (GameObject * go, Player * player)
{
    ASSERT(go);
    ExecuteScript<AllGameObjectScript>([&](AllGameObjectScript* script)
    {
        script->OnGameObjectDestroyed(go, player);
    });
    if (auto tempScript = ScriptRegistry<GameObjectScript>::GetScriptById(go->GetScriptId()))
    {
        tempScript->OnDestroyed(go, player);
    }
}
References ASSERT, GameObject::GetScriptId(), and AllGameObjectScript::OnGameObjectDestroyed().
OnGameObjectLootStateChanged()
void ScriptMgr::OnGameObjectLootStateChanged (GameObject * go, uint32 state, Unit * unit)
{
    ASSERT(go);
    ExecuteScript<AllGameObjectScript>([&](AllGameObjectScript* script)
    {
        script->OnGameObjectLootStateChanged(go, state, unit);
    });
    if (auto tempScript = ScriptRegistry<GameObjectScript>::GetScriptById(go->GetScriptId()))
    {
        tempScript->OnLootStateChanged(go, state, unit);
    }
}
References ASSERT, GameObject::GetScriptId(), and AllGameObjectScript::OnGameObjectLootStateChanged().
OnGameObjectModifyHealth()
void ScriptMgr::OnGameObjectModifyHealth (GameObject * go, Unit * attackerOrHealer, int32 & change, SpellInfo const * spellInfo)
{
    ASSERT(go);
    ExecuteScript<AllGameObjectScript>([&](AllGameObjectScript* script)
    {
        script->OnGameObjectModifyHealth(go, attackerOrHealer, change, spellInfo);
    });
    if (auto tempScript = ScriptRegistry<GameObjectScript>::GetScriptById(go->GetScriptId()))
    {
        tempScript->OnModifyHealth(go, attackerOrHealer, change, spellInfo);
    }
}
References ASSERT, GameObject::GetScriptId(), and AllGameObjectScript::OnGameObjectModifyHealth().
OnGameObjectRemoveWorld()
void ScriptMgr::OnGameObjectRemoveWorld (GameObject * go)
{
    ASSERT(go);
    ExecuteScript<AllGameObjectScript>([&](AllGameObjectScript* script)
    {
        script->OnGameObjectRemoveWorld(go);
    });
}
References ASSERT, and AllGameObjectScript::OnGameObjectRemoveWorld().
OnGameObjectSaveToDB()
void ScriptMgr::OnGameObjectSaveToDB (GameObject * go)
{
    ASSERT(go);
    ExecuteScript<AllGameObjectScript>([&](AllGameObjectScript* script)
    {
        script->OnGameObjectSaveToDB(go);
    });
}
References ASSERT, and AllGameObjectScript::OnGameObjectSaveToDB().
OnGameObjectStateChanged()
void ScriptMgr::OnGameObjectStateChanged (GameObject * go, uint32 state)
{
    ASSERT(go);
    ExecuteScript<AllGameObjectScript>([&](AllGameObjectScript* script)
    {
        script->OnGameObjectStateChanged(go, state);
    });
    if (auto tempScript = ScriptRegistry<GameObjectScript>::GetScriptById(go->GetScriptId()))
    {
        tempScript->OnGameObjectStateChanged(go, state);
    }
}
References ASSERT, GameObject::GetScriptId(), and AllGameObjectScript::OnGameObjectStateChanged().
OnGameObjectUpdate()
void ScriptMgr::OnGameObjectUpdate (GameObject * go, uint32 diff)
{
    ASSERT(go);
    ExecuteScript<AllGameObjectScript>([&](AllGameObjectScript* script)
    {
        script->OnGameObjectUpdate(go, diff);
    });
    if (auto tempScript = ScriptRegistry<GameObjectScript>::GetScriptById(go->GetScriptId()))
    {
        tempScript->OnUpdate(go, diff);
    }
}
References ASSERT, GameObject::GetScriptId(), and AllGameObjectScript::OnGameObjectUpdate().
OnGetArenaPoints()
void ScriptMgr::OnGetArenaPoints (ArenaTeam * at, float & points)
{
    CALL_ENABLED_HOOKS(ArenaTeamScript, ARENATEAMHOOK_ON_GET_ARENA_POINTS, script->OnGetArenaPoints(at, points));
}
References ARENATEAMHOOK_ON_GET_ARENA_POINTS, CALL_ENABLED_HOOKS, and ArenaTeamScript::OnGetArenaPoints().
OnGetPoints()
void ScriptMgr::OnGetPoints (ArenaTeam * team, uint32 memberRating, float & points)
{
    CALL_ENABLED_HOOKS(ArenaScript, ARENAHOOK_ON_GET_POINTS, script->OnGetPoints(team, memberRating, points));
}
References ARENAHOOK_ON_GET_POINTS, CALL_ENABLED_HOOKS, and ArenaScript::OnGetPoints().
OnGetSlotByType()
void ScriptMgr::OnGetSlotByType (const uint32 type, uint8 & slot)
{
    CALL_ENABLED_HOOKS(ArenaTeamScript, ARENATEAMHOOK_ON_GET_SLOT_BY_TYPE, script->OnGetSlotByType(type, slot));
}
References ARENATEAMHOOK_ON_GET_SLOT_BY_TYPE, CALL_ENABLED_HOOKS, and ArenaTeamScript::OnGetSlotByType().
OnGlobalItemDelFromDB()
void ScriptMgr::OnGlobalItemDelFromDB (CharacterDatabaseTransaction trans, ObjectGuid::LowType itemGuid)
{
    ASSERT(trans);
    ASSERT(itemGuid);
    CALL_ENABLED_HOOKS(GlobalScript, GLOBALHOOK_ON_ITEM_DEL_FROM_DB, script->OnItemDelFromDB(trans, itemGuid));
}
References ASSERT, CALL_ENABLED_HOOKS, GLOBALHOOK_ON_ITEM_DEL_FROM_DB, and GlobalScript::OnItemDelFromDB().
OnGlobalMirrorImageDisplayItem()
void ScriptMgr::OnGlobalMirrorImageDisplayItem (Item const * item, uint32 & display)
{
    CALL_ENABLED_HOOKS(GlobalScript, GLOBALHOOK_ON_MIRRORIMAGE_DISPLAY_ITEM, script->OnMirrorImageDisplayItem(item, display));
}
References CALL_ENABLED_HOOKS, GLOBALHOOK_ON_MIRRORIMAGE_DISPLAY_ITEM, and GlobalScript::OnMirrorImageDisplayItem().
OnGossipHello() [1/2]
bool ScriptMgr::OnGossipHello (Player * player, Creature * creature)
{
    ASSERT(player);
    ASSERT(creature);
    auto ret = IsValidBoolScript<AllCreatureScript>([&](AllCreatureScript* script)
    {
        return script->CanCreatureGossipHello(player, creature);
    });
    if (ret && *ret)
    {
        return true;
    }
    auto tempScript = ScriptRegistry<CreatureScript>::GetScriptById(creature->GetScriptId());
    ClearGossipMenuFor(player);
    return tempScript ? tempScript->OnGossipHello(player, creature) : false;
}
References ASSERT, AllCreatureScript::CanCreatureGossipHello(), ClearGossipMenuFor(), ScriptRegistry< TScript >::GetScriptById(), and Creature::GetScriptId().
OnGossipHello() [2/2]
bool ScriptMgr::OnGossipHello (Player * player, GameObject * go)
{
    ASSERT(player);
    ASSERT(go);
    auto ret = IsValidBoolScript<AllGameObjectScript>([&](AllGameObjectScript* script)
    {
        return script->CanGameObjectGossipHello(player, go);
    });
    if (ret && *ret)
    {
        return true;
    }
    auto tempScript = ScriptRegistry<GameObjectScript>::GetScriptById(go->GetScriptId());
    ClearGossipMenuFor(player);
    return tempScript && tempScript->OnGossipHello(player, go);
}
References ASSERT, AllGameObjectScript::CanGameObjectGossipHello(), ClearGossipMenuFor(), ScriptRegistry< TScript >::GetScriptById(), and GameObject::GetScriptId().
OnGossipSelect() [1/3]
bool ScriptMgr::OnGossipSelect (Player * player, Creature * creature, uint32 sender, uint32 action)
{
    ASSERT(player);
    ASSERT(creature);
    auto ret = IsValidBoolScript<AllCreatureScript>([&](AllCreatureScript* script)
    {
        return script->CanCreatureGossipSelect(player, creature, sender, action);
    });
    if (ret && *ret)
    {
        return true;
    }
    auto tempScript = ScriptRegistry<CreatureScript>::GetScriptById(creature->GetScriptId());
    return tempScript ? tempScript->OnGossipSelect(player, creature, sender, action) : false;
}
References ASSERT, AllCreatureScript::CanCreatureGossipSelect(), ScriptRegistry< TScript >::GetScriptById(), and Creature::GetScriptId().
OnGossipSelect() [2/3]
bool ScriptMgr::OnGossipSelect (Player * player, GameObject * go, uint32 sender, uint32 action)
{
    ASSERT(player);
    ASSERT(go);
    auto ret = IsValidBoolScript<AllGameObjectScript>([&](AllGameObjectScript* script)
    {
        return script->CanGameObjectGossipSelect(player, go, sender, action);
    });
    if (ret && *ret)
    {
        return true;
    }
    auto tempScript = ScriptRegistry<GameObjectScript>::GetScriptById(go->GetScriptId());
    return tempScript ? tempScript->OnGossipSelect(player, go, sender, action) : false;
}
References ASSERT, AllGameObjectScript::CanGameObjectGossipSelect(), ScriptRegistry< TScript >::GetScriptById(), and GameObject::GetScriptId().
OnGossipSelect() [3/3]
void ScriptMgr::OnGossipSelect (Player * player, Item * item, uint32 sender, uint32 action)
{
    ASSERT(player);
    ASSERT(item);
    ExecuteScript<AllItemScript>([&](AllItemScript* script)
    {
        script->OnItemGossipSelect(player, item, sender, action);
    });
    if (auto tempScript = ScriptRegistry<ItemScript>::GetScriptById(item->GetScriptId()))
    {
        tempScript->OnGossipSelect(player, item, sender, action);
    }
}
References ASSERT, Item::GetScriptId(), and AllItemScript::OnItemGossipSelect().
OnGossipSelectCode() [1/3]
bool ScriptMgr::OnGossipSelectCode (Player * player, Creature * creature, uint32 sender, uint32 action, const char * code)
{
    ASSERT(player);
    ASSERT(creature);
    ASSERT(code);
    auto ret = IsValidBoolScript<AllCreatureScript>([&](AllCreatureScript* script)
    {
        return script->CanCreatureGossipSelectCode(player, creature, sender, action, code);
    });
    if (ret && *ret)
    {
        return true;
    }
    auto tempScript = ScriptRegistry<CreatureScript>::GetScriptById(creature->GetScriptId());
    return tempScript ? tempScript->OnGossipSelectCode(player, creature, sender, action, code) : false;
}
References ASSERT, AllCreatureScript::CanCreatureGossipSelectCode(), ScriptRegistry< TScript >::GetScriptById(), and Creature::GetScriptId().
OnGossipSelectCode() [2/3]
bool ScriptMgr::OnGossipSelectCode (Player * player, GameObject * go, uint32 sender, uint32 action, const char * code)
{
    ASSERT(player);
    ASSERT(go);
    ASSERT(code);
    auto ret = IsValidBoolScript<AllGameObjectScript>([&](AllGameObjectScript* script)
    {
        return script->CanGameObjectGossipSelectCode(player, go, sender, action, code);
    });
    if (ret && *ret)
    {
        return true;
    }
    auto tempScript = ScriptRegistry<GameObjectScript>::GetScriptById(go->GetScriptId());
    return tempScript ? tempScript->OnGossipSelectCode(player, go, sender, action, code) : false;
}
References ASSERT, AllGameObjectScript::CanGameObjectGossipSelectCode(), ScriptRegistry< TScript >::GetScriptById(), and GameObject::GetScriptId().
OnGossipSelectCode() [3/3]
void ScriptMgr::OnGossipSelectCode (Player * player, Item * item, uint32 sender, uint32 action, const char * code)
{
    ASSERT(player);
    ASSERT(item);
    ExecuteScript<AllItemScript>([&](AllItemScript* script)
    {
        script->OnItemGossipSelectCode(player, item, sender, action, code);
    });
    if (auto tempScript = ScriptRegistry<ItemScript>::GetScriptById(item->GetScriptId()))
    {
        tempScript->OnGossipSelectCode(player, item, sender, action, code);
    }
}
References ASSERT, Item::GetScriptId(), and AllItemScript::OnItemGossipSelectCode().
OnGrayLevelCalculation()
void ScriptMgr::OnGrayLevelCalculation (uint8 & grayLevel, uint8 playerLevel)
{
    CALL_ENABLED_HOOKS(FormulaScript, FORMULAHOOK_ON_GRAY_LEVEL_CALCULATION, script->OnGrayLevelCalculation(grayLevel, playerLevel));
}
References CALL_ENABLED_HOOKS, FORMULAHOOK_ON_GRAY_LEVEL_CALCULATION, and FormulaScript::OnGrayLevelCalculation().
OnGroupAddMember()
void ScriptMgr::OnGroupAddMember (Group * group, ObjectGuid guid)
{
    ASSERT(group);
    CALL_ENABLED_HOOKS(GroupScript, GROUPHOOK_ON_ADD_MEMBER, script->OnAddMember(group, guid));
}
References ASSERT, CALL_ENABLED_HOOKS, GROUPHOOK_ON_ADD_MEMBER, and GroupScript::OnAddMember().
OnGroupChangeLeader()
void ScriptMgr::OnGroupChangeLeader (Group * group, ObjectGuid newLeaderGuid, ObjectGuid oldLeaderGuid)
{
    ASSERT(group);
    CALL_ENABLED_HOOKS(GroupScript, GROUPHOOK_ON_CHANGE_LEADER, script->OnChangeLeader(group, newLeaderGuid, oldLeaderGuid));
}
References ASSERT, CALL_ENABLED_HOOKS, GROUPHOOK_ON_CHANGE_LEADER, and GroupScript::OnChangeLeader().
OnGroupDisband()
void ScriptMgr::OnGroupDisband (Group * group)
{
    ASSERT(group);
    CALL_ENABLED_HOOKS(GroupScript, GROUPHOOK_ON_DISBAND, script->OnDisband(group));
}
References ASSERT, CALL_ENABLED_HOOKS, GROUPHOOK_ON_DISBAND, and GroupScript::OnDisband().
OnGroupInviteMember()
void ScriptMgr::OnGroupInviteMember (Group * group, ObjectGuid guid)
{
    ASSERT(group);
    CALL_ENABLED_HOOKS(GroupScript, GROUPHOOK_ON_INVITE_MEMBER, script->OnInviteMember(group, guid));
}
References ASSERT, CALL_ENABLED_HOOKS, GROUPHOOK_ON_INVITE_MEMBER, and GroupScript::OnInviteMember().
OnGroupRateCalculation()
void ScriptMgr::OnGroupRateCalculation (float & rate, uint32 count, bool isRaid)
{
    CALL_ENABLED_HOOKS(FormulaScript, FORMULAHOOK_ON_GROUP_RATE_CALCULATION, script->OnGroupRateCalculation(rate, count, isRaid));
}
References CALL_ENABLED_HOOKS, FORMULAHOOK_ON_GROUP_RATE_CALCULATION, and FormulaScript::OnGroupRateCalculation().
OnGroupRemoveMember()
void ScriptMgr::OnGroupRemoveMember (Group * group, ObjectGuid guid, RemoveMethod method, ObjectGuid kicker, const char * reason)
{
    ASSERT(group);
    CALL_ENABLED_HOOKS(GroupScript, GROUPHOOK_ON_REMOVE_MEMBER, script->OnRemoveMember(group, guid, method, kicker, reason));
}
References ASSERT, CALL_ENABLED_HOOKS, GROUPHOOK_ON_REMOVE_MEMBER, and GroupScript::OnRemoveMember().
OnGuildAddMember()
void ScriptMgr::OnGuildAddMember (Guild * guild, Player * player, uint8 & plRank)
{
    CALL_ENABLED_HOOKS(GuildScript, GUILDHOOK_ON_ADD_MEMBER, script->OnAddMember(guild, player, plRank));
}
References CALL_ENABLED_HOOKS, GUILDHOOK_ON_ADD_MEMBER, and GuildScript::OnAddMember().
OnGuildBankEvent()
void ScriptMgr::OnGuildBankEvent (Guild * guild, uint8 eventType, uint8 tabId, ObjectGuid::LowType playerGuid, uint32 itemOrMoney, uint16 itemStackCount, uint8 destTabId)
{
    CALL_ENABLED_HOOKS(GuildScript, GUILDHOOK_ON_BANK_EVENT, script->OnBankEvent(guild, eventType, tabId, playerGuid, itemOrMoney, itemStackCount, destTabId));
}
References CALL_ENABLED_HOOKS, GUILDHOOK_ON_BANK_EVENT, and GuildScript::OnBankEvent().
OnGuildCreate()
void ScriptMgr::OnGuildCreate (Guild * guild, Player * leader, const std::string & name)
{
    CALL_ENABLED_HOOKS(GuildScript, GUILDHOOK_ON_CREATE, script->OnCreate(guild, leader, name));
}
References CALL_ENABLED_HOOKS, GUILDHOOK_ON_CREATE, and GuildScript::OnCreate().
OnGuildDisband()
void ScriptMgr::OnGuildDisband (Guild * guild)
{
    CALL_ENABLED_HOOKS(GuildScript, GUILDHOOK_ON_DISBAND, script->OnDisband(guild));
}
References CALL_ENABLED_HOOKS, GUILDHOOK_ON_DISBAND, and GuildScript::OnDisband().
OnGuildEvent()
void ScriptMgr::OnGuildEvent (Guild * guild, uint8 eventType, ObjectGuid::LowType playerGuid1, ObjectGuid::LowType playerGuid2, uint8 newRank)
{
    CALL_ENABLED_HOOKS(GuildScript, GUILDHOOK_ON_EVENT, script->OnEvent(guild, eventType, playerGuid1, playerGuid2, newRank));
}
References CALL_ENABLED_HOOKS, GUILDHOOK_ON_EVENT, and GuildScript::OnEvent().
OnGuildInfoChanged()
void ScriptMgr::OnGuildInfoChanged (Guild * guild, const std::string & newInfo)
{
    CALL_ENABLED_HOOKS(GuildScript, GUILDHOOK_ON_INFO_CHANGED, script->OnInfoChanged(guild, newInfo));
}
References CALL_ENABLED_HOOKS, GUILDHOOK_ON_INFO_CHANGED, and GuildScript::OnInfoChanged().
OnGuildItemMove()
void ScriptMgr::OnGuildItemMove (Guild * guild, Player * player, Item * pItem, bool isSrcBank, uint8 srcContainer, uint8 srcSlotId, bool isDestBank, uint8 destContainer, uint8 destSlotId)
{
    CALL_ENABLED_HOOKS(GuildScript, GUILDHOOK_ON_ITEM_MOVE, script->OnItemMove(guild, player, pItem, isSrcBank, srcContainer, srcSlotId, isDestBank, destContainer, destSlotId));
}
References CALL_ENABLED_HOOKS, GUILDHOOK_ON_ITEM_MOVE, and GuildScript::OnItemMove().
OnGuildMemberDepositMoney()
void ScriptMgr::OnGuildMemberDepositMoney (Guild * guild, Player * player, uint32 & amount)
{
    CALL_ENABLED_HOOKS(GuildScript, GUILDHOOK_ON_MEMBER_DEPOSIT_MONEY, script->OnMemberDepositMoney(guild, player, amount));
}
References CALL_ENABLED_HOOKS, GUILDHOOK_ON_MEMBER_DEPOSIT_MONEY, and GuildScript::OnMemberDepositMoney().
OnGuildMemberWitdrawMoney()
void ScriptMgr::OnGuildMemberWitdrawMoney (Guild * guild, Player * player, uint32 & amount, bool isRepair)
{
    CALL_ENABLED_HOOKS(GuildScript, GUILDHOOK_ON_MEMBER_WITDRAW_MONEY, script->OnMemberWitdrawMoney(guild, player, amount, isRepair));
}
References CALL_ENABLED_HOOKS, GUILDHOOK_ON_MEMBER_WITDRAW_MONEY, and GuildScript::OnMemberWitdrawMoney().
OnGuildMOTDChanged()
void ScriptMgr::OnGuildMOTDChanged (Guild * guild, const std::string & newMotd)
{
    CALL_ENABLED_HOOKS(GuildScript, GUILDHOOK_ON_MOTD_CHANGED, script->OnMOTDChanged(guild, newMotd));
}
References CALL_ENABLED_HOOKS, GUILDHOOK_ON_MOTD_CHANGED, and GuildScript::OnMOTDChanged().
OnGuildRemoveMember()
void ScriptMgr::OnGuildRemoveMember (Guild * guild, Player * player, bool isDisbanding, bool isKicked)
{
    CALL_ENABLED_HOOKS(GuildScript, GUILDHOOK_ON_REMOVE_MEMBER, script->OnRemoveMember(guild, player, isDisbanding, isKicked));
}
References CALL_ENABLED_HOOKS, GUILDHOOK_ON_REMOVE_MEMBER, and GuildScript::OnRemoveMember().
OnHandleDevCommand()
void ScriptMgr::OnHandleDevCommand (Player * player, bool & enable)
{
    CALL_ENABLED_HOOKS(AllCommandScript, ALLCOMMANDHOOK_ON_HANDLE_DEV_COMMAND, script->OnHandleDevCommand(player, enable));
}
References ALLCOMMANDHOOK_ON_HANDLE_DEV_COMMAND, CALL_ENABLED_HOOKS, and AllCommandScript::OnHandleDevCommand().
OnHeal()
void ScriptMgr::OnHeal (Unit * healer, Unit * reciever, uint32 & gain)
{
    CALL_ENABLED_HOOKS(UnitScript, UNITHOOK_ON_HEAL, script->OnHeal(healer, reciever, gain));
}
References CALL_ENABLED_HOOKS, UnitScript::OnHeal(), and UNITHOOK_ON_HEAL.
OnHonorCalculation()
void ScriptMgr::OnHonorCalculation (float & honor, uint8 level, float multiplier)
{
    CALL_ENABLED_HOOKS(FormulaScript, FORMULAHOOK_ON_HONOR_CALCULATION, script->OnHonorCalculation(honor, level, multiplier));
}
References CALL_ENABLED_HOOKS, FORMULAHOOK_ON_HONOR_CALCULATION, and FormulaScript::OnHonorCalculation().
OnInitializeLockedDungeons()
void ScriptMgr::OnInitializeLockedDungeons (Player * player, uint8 & level, uint32 & lockData, lfg::LFGDungeonData const * dungeon)
{
    CALL_ENABLED_HOOKS(GlobalScript, GLOBALHOOK_ON_INITIALIZE_LOCKED_DUNGEONS, script->OnInitializeLockedDungeons(player, level, lockData, dungeon));
}
References CALL_ENABLED_HOOKS, GLOBALHOOK_ON_INITIALIZE_LOCKED_DUNGEONS, and GlobalScript::OnInitializeLockedDungeons().
OnInitStatsForLevel()
void ScriptMgr::OnInitStatsForLevel (Guardian * guardian, uint8 petlevel)
{
    CALL_ENABLED_HOOKS(PetScript, PETHOOK_ON_INIT_STATS_FOR_LEVEL, script->OnInitStatsForLevel(guardian, petlevel));
}
References CALL_ENABLED_HOOKS, PetScript::OnInitStatsForLevel(), and PETHOOK_ON_INIT_STATS_FOR_LEVEL.
OnInstall()
void ScriptMgr::OnInstall (Vehicle * veh)
{
    ASSERT(veh);
    ASSERT(veh->GetBase()->IsCreature());
    if (auto tempScript = ScriptRegistry<VehicleScript>::GetScriptById(veh->GetBase()->ToCreature()->GetScriptId()))
    {
        tempScript->OnInstall(veh);
    }
}
References ASSERT, Vehicle::GetBase(), Creature::GetScriptId(), Object::IsCreature(), and Object::ToCreature().
OnInstallAccessory()
void ScriptMgr::OnInstallAccessory (Vehicle * veh, Creature * accessory)
{
    ASSERT(veh);
    ASSERT(veh->GetBase()->IsCreature());
    ASSERT(accessory);
    if (auto tempScript = ScriptRegistry<VehicleScript>::GetScriptById(veh->GetBase()->ToCreature()->GetScriptId()))
    {
        tempScript->OnInstallAccessory(veh, accessory);
    }
}
References ASSERT, Vehicle::GetBase(), Creature::GetScriptId(), Object::IsCreature(), and Object::ToCreature().
OnInstanceIdRemoved()
void ScriptMgr::OnInstanceIdRemoved (uint32 instanceId)
Called when an instance Id is deleted, usually because it expired or no players are bound to it anymore.
Parameters
instanceId The unique id of the instance
{
    CALL_ENABLED_HOOKS(GlobalScript, GLOBALHOOK_ON_INSTANCEID_REMOVED, script->OnInstanceIdRemoved(instanceId));
}
References CALL_ENABLED_HOOKS, GLOBALHOOK_ON_INSTANCEID_REMOVED, and GlobalScript::OnInstanceIdRemoved().
OnInstanceSave()
void ScriptMgr::OnInstanceSave (InstanceSave * instanceSave)
{
    CALL_ENABLED_HOOKS(MiscScript, MISCHOOK_ON_INSTANCE_SAVE, script->OnInstanceSave(instanceSave));
}
References CALL_ENABLED_HOOKS, MISCHOOK_ON_INSTANCE_SAVE, and MiscScript::OnInstanceSave().
OnIsAffectedBySpellModCheck()
bool ScriptMgr::OnIsAffectedBySpellModCheck (SpellInfo const * affectSpell, SpellInfo const * checkSpell, SpellModifier const * mod)
{
    CALL_ENABLED_BOOLEAN_HOOKS(GlobalScript, GLOBALHOOK_ON_IS_AFFECTED_BY_SPELL_MOD_CHECK, !script->OnIsAffectedBySpellModCheck(affectSpell, checkSpell, mod));
}
References CALL_ENABLED_BOOLEAN_HOOKS, GLOBALHOOK_ON_IS_AFFECTED_BY_SPELL_MOD_CHECK, and GlobalScript::OnIsAffectedBySpellModCheck().
OnItemCreate()
void ScriptMgr::OnItemCreate (Item * item, ItemTemplate const * itemProto, Player const * owner)
{
    CALL_ENABLED_HOOKS(MiscScript, MISCHOOK_ON_ITEM_CREATE, script->OnItemCreate(item, itemProto, owner));
}
References CALL_ENABLED_HOOKS, MISCHOOK_ON_ITEM_CREATE, and MiscScript::OnItemCreate().
OnItemExpire()
bool ScriptMgr::OnItemExpire (Player * player, ItemTemplate const * proto)
{
    ASSERT(player);
    ASSERT(proto);
    auto ret = IsValidBoolScript<AllItemScript>([&](AllItemScript* script)
    {
        return !script->CanItemExpire(player, proto);
    });
    if (ret && *ret)
    {
        return false;
    }
    auto tempScript = ScriptRegistry<ItemScript>::GetScriptById(proto->ScriptId);
    return tempScript ? tempScript->OnExpire(player, proto) : false;
}
References ASSERT, AllItemScript::CanItemExpire(), ScriptRegistry< TScript >::GetScriptById(), and ItemTemplate::ScriptId.
OnItemRemove()
bool ScriptMgr::OnItemRemove (Player * player, Item * item)
{
    ASSERT(player);
    ASSERT(item);
    auto ret = IsValidBoolScript<AllItemScript>([&](AllItemScript* script)
    {
        return !script->CanItemRemove(player, item);
    });
    if (ret && *ret)
    {
        return false;
    }
    auto tempScript = ScriptRegistry<ItemScript>::GetScriptById(item->GetScriptId());
    return tempScript ? tempScript->OnRemove(player, item) : false;
}
References ASSERT, AllItemScript::CanItemRemove(), ScriptRegistry< TScript >::GetScriptById(), and Item::GetScriptId().
OnItemRoll()
bool ScriptMgr::OnItemRoll (Player const * player, LootStoreItem const * LootStoreItem, float & chance, Loot & loot, LootStore const & store)
{
    CALL_ENABLED_BOOLEAN_HOOKS(GlobalScript, GLOBALHOOK_ON_ITEM_ROLL, !script->OnItemRoll(player, lootStoreItem, chance, loot, store));
}
References CALL_ENABLED_BOOLEAN_HOOKS, GLOBALHOOK_ON_ITEM_ROLL, and GlobalScript::OnItemRoll().
OnItemUse()
bool ScriptMgr::OnItemUse (Player * player, Item * item, SpellCastTargets const & targets)
{
    ASSERT(player);
    ASSERT(item);
    auto ret = IsValidBoolScript<AllItemScript>([&](AllItemScript* script)
    {
        return script->CanItemUse(player, item, targets);
    });
    if (ret && *ret)
    {
        return true;
    }
    auto tempScript = ScriptRegistry<ItemScript>::GetScriptById(item->GetScriptId());
    return tempScript ? tempScript->OnUse(player, item, targets) : false;
}
References ASSERT, AllItemScript::CanItemUse(), ScriptRegistry< TScript >::GetScriptById(), and Item::GetScriptId().
OnLastIpUpdate()
void ScriptMgr::OnLastIpUpdate (uint32 accountId, std::string ip)
{
    CALL_ENABLED_HOOKS(AccountScript, ACCOUNTHOOK_ON_LAST_IP_UPDATE, script->OnLastIpUpdate(accountId, ip));
}
References ACCOUNTHOOK_ON_LAST_IP_UPDATE, CALL_ENABLED_HOOKS, and AccountScript::OnLastIpUpdate().
OnLoadCustomDatabaseTable()
void ScriptMgr::OnLoadCustomDatabaseTable ()
{
    CALL_ENABLED_HOOKS(WorldScript, WORLDHOOK_ON_LOAD_CUSTOM_DATABASE_TABLE, script->OnLoadCustomDatabaseTable());
}
References CALL_ENABLED_HOOKS, WorldScript::OnLoadCustomDatabaseTable(), and WORLDHOOK_ON_LOAD_CUSTOM_DATABASE_TABLE.
OnLoadGridMap()
void ScriptMgr::OnLoadGridMap (Map * map, GridTerrainData * gmap, uint32 gx, uint32 gy)
{
    ASSERT(map);
    ForeachMaps<WorldMapScript>(map,
    [&](WorldMapScript* script)
    {
        script->OnLoadGridMap(map, gmap, gx, gy);
    });
    ForeachMaps<InstanceMapScript>(map,
    [&](InstanceMapScript* script)
    {
        script->OnLoadGridMap((InstanceMap*)map, gmap, gx, gy);
    });
    ForeachMaps<BattlegroundMapScript>(map,
    [&](BattlegroundMapScript* script)
    {
        script->OnLoadGridMap((BattlegroundMap*)map, gmap, gx, gy);
    });
}
References ASSERT, and MapScript< TMap >::OnLoadGridMap().
OnLoadSpellCustomAttr()
void ScriptMgr::OnLoadSpellCustomAttr (SpellInfo * spell)
{
    CALL_ENABLED_HOOKS(GlobalScript, GLOBALHOOK_ON_LOAD_SPELL_CUSTOM_ATTR, script->OnLoadSpellCustomAttr(spell));
}
References CALL_ENABLED_HOOKS, GLOBALHOOK_ON_LOAD_SPELL_CUSTOM_ATTR, and GlobalScript::OnLoadSpellCustomAttr().
OnLootMoney()
void ScriptMgr::OnLootMoney (Player * player, uint32 gold)
{
    ASSERT(player);
    CALL_ENABLED_HOOKS(LootScript, LOOTHOOK_ON_LOOT_MONEY, script->OnLootMoney(player, gold));
}
References ASSERT, CALL_ENABLED_HOOKS, LOOTHOOK_ON_LOOT_MONEY, and LootScript::OnLootMoney().
OnMapUpdate()
void ScriptMgr::OnMapUpdate (Map * map, uint32 diff)
{
    ASSERT(map);
    CALL_ENABLED_HOOKS(AllMapScript, ALLMAPHOOK_ON_MAP_UPDATE, script->OnMapUpdate(map, diff));
    ForeachMaps<WorldMapScript>(map,
    [&](WorldMapScript* script)
    {
        script->OnUpdate(map, diff);
    });
    ForeachMaps<InstanceMapScript>(map,
    [&](InstanceMapScript* script)
    {
        script->OnUpdate((InstanceMap*)map, diff);
    });
    ForeachMaps<BattlegroundMapScript>(map,
    [&](BattlegroundMapScript* script)
    {
        script->OnUpdate((BattlegroundMap*)map, diff);
    });
}
References ALLMAPHOOK_ON_MAP_UPDATE, ASSERT, CALL_ENABLED_HOOKS, AllMapScript::OnMapUpdate(), and MapScript< TMap >::OnUpdate().
OnMotdChange()
void ScriptMgr::OnMotdChange (std::string & newMotd, LocaleConstant & locale)
{
    CALL_ENABLED_HOOKS(WorldScript, WORLDHOOK_ON_MOTD_CHANGE, script->OnMotdChange(newMotd, locale));
}
References CALL_ENABLED_HOOKS, WorldScript::OnMotdChange(), and WORLDHOOK_ON_MOTD_CHANGE.
OnNetworkStart()
void ScriptMgr::OnNetworkStart ()
{
    CALL_ENABLED_HOOKS(ServerScript, SERVERHOOK_ON_NETWORK_START, script->OnNetworkStart());
}
References CALL_ENABLED_HOOKS, ServerScript::OnNetworkStart(), and SERVERHOOK_ON_NETWORK_START.
OnNetworkStop()
void ScriptMgr::OnNetworkStop ()
{
    CALL_ENABLED_HOOKS(ServerScript, SERVERHOOK_ON_NETWORK_STOP, script->OnNetworkStop());
}
References CALL_ENABLED_HOOKS, ServerScript::OnNetworkStop(), and SERVERHOOK_ON_NETWORK_STOP.
OnOpenStateChange()
void ScriptMgr::OnOpenStateChange (bool open)
{
    CALL_ENABLED_HOOKS(WorldScript, WORLDHOOK_ON_OPEN_STATE_CHANGE, script->OnOpenStateChange(open));
}
References CALL_ENABLED_HOOKS, WorldScript::OnOpenStateChange(), and WORLDHOOK_ON_OPEN_STATE_CHANGE.
OnPasswordChange()
void ScriptMgr::OnPasswordChange (uint32 accountId)
{
    CALL_ENABLED_HOOKS(AccountScript, ACCOUNTHOOK_ON_PASSWORD_CHANGE, script->OnPasswordChange(accountId));
}
References ACCOUNTHOOK_ON_PASSWORD_CHANGE, CALL_ENABLED_HOOKS, and AccountScript::OnPasswordChange().
OnPatchValuesUpdate()
void ScriptMgr::OnPatchValuesUpdate (Unit const * unit, ByteBuffer & valuesUpdateBuf, BuildValuesCachePosPointers & posPointers, Player * target)
{
    CALL_ENABLED_HOOKS(UnitScript, UNITHOOK_ON_PATCH_VALUES_UPDATE, script->OnPatchValuesUpdate(unit, valuesUpdateBuf, posPointers, target));
}
References CALL_ENABLED_HOOKS, UnitScript::OnPatchValuesUpdate(), and UNITHOOK_ON_PATCH_VALUES_UPDATE.
OnPetAddToWorld()
void ScriptMgr::OnPetAddToWorld (Pet * pet)
{
    ASSERT(pet);
    CALL_ENABLED_HOOKS(PetScript, PETHOOK_ON_PET_ADD_TO_WORLD, script->OnPetAddToWorld(pet));
}
References ASSERT, CALL_ENABLED_HOOKS, PetScript::OnPetAddToWorld(), and PETHOOK_ON_PET_ADD_TO_WORLD.
OnPlayerAchievementComplete()
void ScriptMgr::OnPlayerAchievementComplete (Player * player, AchievementEntry const * achievement)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_ACHI_COMPLETE, script->OnPlayerAchievementComplete(player, achievement));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerAchievementComplete(), and PLAYERHOOK_ON_ACHI_COMPLETE.
OnPlayerAchievementSave()
void ScriptMgr::OnPlayerAchievementSave (CharacterDatabaseTransaction trans, Player * player, uint16 achiId, CompletedAchievementData achiData)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_ACHI_SAVE, script->OnPlayerAchievementSave(trans, player, achiId, achiData));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerAchievementSave(), and PLAYERHOOK_ON_ACHI_SAVE.
OnPlayerAddToBattleground()
void ScriptMgr::OnPlayerAddToBattleground (Player * player, Battleground * bg)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_ADD_TO_BATTLEGROUND, script->OnPlayerAddToBattleground(player, bg));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerAddToBattleground(), and PLAYERHOOK_ON_ADD_TO_BATTLEGROUND.
OnPlayerAfterCreatureLoot()
void ScriptMgr::OnPlayerAfterCreatureLoot (Player * player)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_AFTER_CREATURE_LOOT, script->OnPlayerAfterCreatureLoot(player));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerAfterCreatureLoot(), and PLAYERHOOK_ON_AFTER_CREATURE_LOOT.
OnPlayerAfterCreatureLootMoney()
void ScriptMgr::OnPlayerAfterCreatureLootMoney (Player * player)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_AFTER_CREATURE_LOOT_MONEY, script->OnPlayerAfterCreatureLootMoney(player));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerAfterCreatureLootMoney(), and PLAYERHOOK_ON_AFTER_CREATURE_LOOT_MONEY.
OnPlayerAfterGuardianInitStatsForLevel()
void ScriptMgr::OnPlayerAfterGuardianInitStatsForLevel (Player * player, Guardian * guardian)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_AFTER_GUARDIAN_INIT_STATS_FOR_LEVEL, script->OnPlayerAfterGuardianInitStatsForLevel(player, guardian));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerAfterGuardianInitStatsForLevel(), and PLAYERHOOK_ON_AFTER_GUARDIAN_INIT_STATS_FOR_LEVEL.
OnPlayerAfterMoveItemFromInventory()
void ScriptMgr::OnPlayerAfterMoveItemFromInventory (Player * player, Item * it, uint8 bag, uint8 slot, bool update)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_AFTER_MOVE_ITEM_FROM_INVENTORY, script->OnPlayerAfterMoveItemFromInventory(player, it, bag, slot, update));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerAfterMoveItemFromInventory(), and PLAYERHOOK_ON_AFTER_MOVE_ITEM_FROM_INVENTORY.
OnPlayerAfterSetVisibleItemSlot()
void ScriptMgr::OnPlayerAfterSetVisibleItemSlot (Player * player, uint8 slot, Item * item)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_AFTER_SET_VISIBLE_ITEM_SLOT, script->OnPlayerAfterSetVisibleItemSlot(player, slot, item));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerAfterSetVisibleItemSlot(), and PLAYERHOOK_ON_AFTER_SET_VISIBLE_ITEM_SLOT.
OnPlayerAfterSpecSlotChanged()
void ScriptMgr::OnPlayerAfterSpecSlotChanged (Player * player, uint8 newSlot)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_AFTER_SPEC_SLOT_CHANGED, script->OnPlayerAfterSpecSlotChanged(player, newSlot));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerAfterSpecSlotChanged(), and PLAYERHOOK_ON_AFTER_SPEC_SLOT_CHANGED.
OnPlayerAfterStoreOrEquipNewItem()
void ScriptMgr::OnPlayerAfterStoreOrEquipNewItem (Player * player, uint32 vendorslot, Item * item, uint8 count, uint8 bag, uint8 slot, ItemTemplate const * pProto, Creature * pVendor, VendorItem const * crItem, bool bStore)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_AFTER_STORE_OR_EQUIP_NEW_ITEM, script->OnPlayerAfterStoreOrEquipNewItem(player, vendorslot, item, count, bag, slot, pProto, pVendor, crItem, bStore));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerAfterStoreOrEquipNewItem(), and PLAYERHOOK_ON_AFTER_STORE_OR_EQUIP_NEW_ITEM.
OnPlayerAfterUpdateAttackPowerAndDamage()
void ScriptMgr::OnPlayerAfterUpdateAttackPowerAndDamage (Player * player, float & level, float & base_attPower, float & attPowerMod, float & attPowerMultiplier, bool ranged)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_AFTER_UPDATE_ATTACK_POWER_AND_DAMAGE, script->OnPlayerAfterUpdateAttackPowerAndDamage(player, level, base_attPower, attPowerMod, attPowerMultiplier, ranged));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerAfterUpdateAttackPowerAndDamage(), and PLAYERHOOK_ON_AFTER_UPDATE_ATTACK_POWER_AND_DAMAGE.
OnPlayerAfterUpdateMaxHealth()
void ScriptMgr::OnPlayerAfterUpdateMaxHealth (Player * player, float & value)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_AFTER_UPDATE_MAX_HEALTH, script->OnPlayerAfterUpdateMaxHealth(player, value));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerAfterUpdateMaxHealth(), and PLAYERHOOK_ON_AFTER_UPDATE_MAX_HEALTH.
OnPlayerAfterUpdateMaxPower()
void ScriptMgr::OnPlayerAfterUpdateMaxPower (Player * player, Powers & power, float & value)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_AFTER_UPDATE_MAX_POWER, script->OnPlayerAfterUpdateMaxPower(player, power, value));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerAfterUpdateMaxPower(), and PLAYERHOOK_ON_AFTER_UPDATE_MAX_POWER.
OnPlayerApplyAmmoBonuses()
void ScriptMgr::OnPlayerApplyAmmoBonuses (Player * player, ItemTemplate const * proto, float & currentAmmoDPS)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_APPLY_AMMO_BONUSES, script->OnPlayerApplyAmmoBonuses(player, proto, currentAmmoDPS));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerApplyAmmoBonuses(), and PLAYERHOOK_ON_APPLY_AMMO_BONUSES.
OnPlayerApplyEnchantmentItemModsBefore()
void ScriptMgr::OnPlayerApplyEnchantmentItemModsBefore (Player * player, Item * item, EnchantmentSlot slot, bool apply, uint32 enchant_spell_id, uint32 & enchant_amount)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_APPLY_ENCHANTMENT_ITEM_MODS_BEFORE, script->OnPlayerApplyEnchantmentItemModsBefore(player, item, slot, apply, enchant_spell_id, enchant_amount));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerApplyEnchantmentItemModsBefore(), and PLAYERHOOK_ON_APPLY_ENCHANTMENT_ITEM_MODS_BEFORE.
OnPlayerApplyItemModsBefore()
void ScriptMgr::OnPlayerApplyItemModsBefore (Player * player, uint8 slot, bool apply, uint8 itemProtoStatNumber, uint32 statType, int32 & val)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_APPLY_ITEM_MODS_BEFORE, script->OnPlayerApplyItemModsBefore(player, slot, apply, itemProtoStatNumber, statType, val));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerApplyItemModsBefore(), and PLAYERHOOK_ON_APPLY_ITEM_MODS_BEFORE.
OnPlayerApplyWeaponDamage()
void ScriptMgr::OnPlayerApplyWeaponDamage (Player * player, uint8 slot, ItemTemplate const * proto, float & minDamage, float & maxDamage, uint8 damageIndex)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_APPLY_WEAPON_DAMAGE, script->OnPlayerApplyWeaponDamage(player, slot, proto, minDamage, maxDamage, damageIndex));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerApplyWeaponDamage(), and PLAYERHOOK_ON_APPLY_WEAPON_DAMAGE.
OnPlayerBattlegroundDesertion()
void ScriptMgr::OnPlayerBattlegroundDesertion (Player * player, BattlegroundDesertionType const desertionType)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_BATTLEGROUND_DESERTION, script->OnPlayerBattlegroundDesertion(player, desertionType));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerBattlegroundDesertion(), and PLAYERHOOK_ON_BATTLEGROUND_DESERTION.
OnPlayerBeforeAchievementComplete()
bool ScriptMgr::OnPlayerBeforeAchievementComplete (Player * player, AchievementEntry const * achievement)
{
    CALL_ENABLED_BOOLEAN_HOOKS(PlayerScript, PLAYERHOOK_ON_BEFORE_ACHI_COMPLETE, !script->OnPlayerBeforeAchievementComplete(player, achievement));
}
References CALL_ENABLED_BOOLEAN_HOOKS, PlayerScript::OnPlayerBeforeAchievementComplete(), and PLAYERHOOK_ON_BEFORE_ACHI_COMPLETE.
OnPlayerBeforeBuyItemFromVendor()
void ScriptMgr::OnPlayerBeforeBuyItemFromVendor (Player * player, ObjectGuid vendorguid, uint32 vendorslot, uint32 & item, uint8 count, uint8 bag, uint8 slot)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_BEFORE_BUY_ITEM_FROM_VENDOR, script->OnPlayerBeforeBuyItemFromVendor(player, vendorguid, vendorslot, item, count, bag, slot));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerBeforeBuyItemFromVendor(), and PLAYERHOOK_ON_BEFORE_BUY_ITEM_FROM_VENDOR.
OnPlayerBeforeChooseGraveyard()
void ScriptMgr::OnPlayerBeforeChooseGraveyard (Player * player, TeamId teamId, bool nearCorpse, uint32 & graveyardOverride)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_BEFORE_CHOOSE_GRAVEYARD, script->OnPlayerBeforeChooseGraveyard(player, teamId, nearCorpse, graveyardOverride));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerBeforeChooseGraveyard(), and PLAYERHOOK_ON_BEFORE_CHOOSE_GRAVEYARD.
OnPlayerBeforeCriteriaProgress()
bool ScriptMgr::OnPlayerBeforeCriteriaProgress (Player * player, AchievementCriteriaEntry const * criteria)
{
    CALL_ENABLED_BOOLEAN_HOOKS(PlayerScript, PLAYERHOOK_ON_BEFORE_CRITERIA_PROGRESS, !script->OnPlayerBeforeCriteriaProgress(player, criteria));
}
References CALL_ENABLED_BOOLEAN_HOOKS, PlayerScript::OnPlayerBeforeCriteriaProgress(), and PLAYERHOOK_ON_BEFORE_CRITERIA_PROGRESS.
OnPlayerBeforeDurabilityRepair()
void ScriptMgr::OnPlayerBeforeDurabilityRepair (Player * player, ObjectGuid npcGUID, ObjectGuid itemGUID, float & discountMod, uint8 guildBank)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_BEFORE_DURABILITY_REPAIR, script->OnPlayerBeforeDurabilityRepair(player, npcGUID, itemGUID, discountMod, guildBank));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerBeforeDurabilityRepair(), and PLAYERHOOK_ON_BEFORE_DURABILITY_REPAIR.
OnPlayerBeforeFillQuestLootItem()
void ScriptMgr::OnPlayerBeforeFillQuestLootItem (Player * player, LootItem & item)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_BEFORE_FILL_QUEST_LOOT_ITEM, script->OnPlayerBeforeFillQuestLootItem(player, item));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerBeforeFillQuestLootItem(), and PLAYERHOOK_ON_BEFORE_FILL_QUEST_LOOT_ITEM.
OnPlayerBeforeGuardianInitStatsForLevel()
void ScriptMgr::OnPlayerBeforeGuardianInitStatsForLevel (Player * player, Guardian * guardian, CreatureTemplate const * cinfo, PetType & petType)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_BEFORE_GUARDIAN_INIT_STATS_FOR_LEVEL, script->OnPlayerBeforeGuardianInitStatsForLevel(player, guardian, cinfo, petType));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerBeforeGuardianInitStatsForLevel(), and PLAYERHOOK_ON_BEFORE_GUARDIAN_INIT_STATS_FOR_LEVEL.
OnPlayerBeforeInitTalentForLevel()
void ScriptMgr::OnPlayerBeforeInitTalentForLevel (Player * player, uint8 & level, uint32 & talentPointsForLevel)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_BEFORE_INIT_TALENT_FOR_LEVEL, script->OnPlayerBeforeInitTalentForLevel(player, level, talentPointsForLevel));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerBeforeInitTalentForLevel(), and PLAYERHOOK_ON_BEFORE_INIT_TALENT_FOR_LEVEL.
OnPlayerBeforeLoadPetFromDB()
void ScriptMgr::OnPlayerBeforeLoadPetFromDB (Player * player, uint32 & petentry, uint32 & petnumber, bool & current, bool & forceLoadFromDB)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_BEFORE_LOAD_PET_FROM_DB, script->OnPlayerBeforeLoadPetFromDB(player, petentry, petnumber, current, forceLoadFromDB));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerBeforeLoadPetFromDB(), and PLAYERHOOK_ON_BEFORE_LOAD_PET_FROM_DB.
OnPlayerBeforeLogout()
void ScriptMgr::OnPlayerBeforeLogout (Player * player)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_BEFORE_LOGOUT, script->OnPlayerBeforeLogout(player));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerBeforeLogout(), and PLAYERHOOK_ON_BEFORE_LOGOUT.
OnPlayerBeforeLootMoney()
void ScriptMgr::OnPlayerBeforeLootMoney (Player * player, Loot * loot)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_BEFORE_LOOT_MONEY, script->OnPlayerBeforeLootMoney(player, loot));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerBeforeLootMoney(), and PLAYERHOOK_ON_BEFORE_LOOT_MONEY.
OnPlayerBeforeOpenItem()
bool ScriptMgr::OnPlayerBeforeOpenItem (Player * player, Item * item)
{
    CALL_ENABLED_BOOLEAN_HOOKS(PlayerScript, PLAYERHOOK_ON_BEFORE_OPEN_ITEM, !script->OnPlayerBeforeOpenItem(player, item));
}
References CALL_ENABLED_BOOLEAN_HOOKS, PlayerScript::OnPlayerBeforeOpenItem(), and PLAYERHOOK_ON_BEFORE_OPEN_ITEM.
OnPlayerBeforeQuestComplete()
bool ScriptMgr::OnPlayerBeforeQuestComplete (Player * player, uint32 quest_id)
{
    CALL_ENABLED_BOOLEAN_HOOKS(PlayerScript, PLAYERHOOK_ON_BEFORE_QUEST_COMPLETE, !script->OnPlayerBeforeQuestComplete(player, quest_id));
}
References CALL_ENABLED_BOOLEAN_HOOKS, PlayerScript::OnPlayerBeforeQuestComplete(), and PLAYERHOOK_ON_BEFORE_QUEST_COMPLETE.
OnPlayerBeforeSendChatMessage()
void ScriptMgr::OnPlayerBeforeSendChatMessage (Player * player, uint32 & type, uint32 & lang, std::string & msg)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_BEFORE_SEND_CHAT_MESSAGE, script->OnPlayerBeforeSendChatMessage(player, type, lang, msg));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerBeforeSendChatMessage(), and PLAYERHOOK_ON_BEFORE_SEND_CHAT_MESSAGE.
OnPlayerBeforeStoreOrEquipNewItem()
void ScriptMgr::OnPlayerBeforeStoreOrEquipNewItem (Player * player, uint32 vendorslot, uint32 & item, uint8 count, uint8 bag, uint8 slot, ItemTemplate const * pProto, Creature * pVendor, VendorItem const * crItem, bool bStore)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_BEFORE_STORE_OR_EQUIP_NEW_ITEM, script->OnPlayerBeforeStoreOrEquipNewItem(player, vendorslot, item, count, bag, slot, pProto, pVendor, crItem, bStore));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerBeforeStoreOrEquipNewItem(), and PLAYERHOOK_ON_BEFORE_STORE_OR_EQUIP_NEW_ITEM.
OnPlayerBeforeTeleport()
bool ScriptMgr::OnPlayerBeforeTeleport (Player * player, uint32 mapid, float x, float y, float z, float orientation, uint32 options, Unit * target)
{
    CALL_ENABLED_BOOLEAN_HOOKS(PlayerScript, PLAYERHOOK_ON_BEFORE_TELEPORT, !script->OnPlayerBeforeTeleport(player, mapid, x, y, z, orientation, options, target));
}
References CALL_ENABLED_BOOLEAN_HOOKS, PlayerScript::OnPlayerBeforeTeleport(), and PLAYERHOOK_ON_BEFORE_TELEPORT.
OnPlayerBeforeTempSummonInitStats()
void ScriptMgr::OnPlayerBeforeTempSummonInitStats (Player * player, TempSummon * tempSummon, uint32 & duration)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_BEFORE_TEMP_SUMMON_INIT_STATS, script->OnPlayerBeforeTempSummonInitStats(player, tempSummon, duration));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerBeforeTempSummonInitStats(), and PLAYERHOOK_ON_BEFORE_TEMP_SUMMON_INIT_STATS.
OnPlayerBeforeUpdate()
void ScriptMgr::OnPlayerBeforeUpdate (Player * player, uint32 p_time)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_BEFORE_UPDATE, script->OnPlayerBeforeUpdate(player, p_time));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerBeforeUpdate(), and PLAYERHOOK_ON_BEFORE_UPDATE.
OnPlayerBeforeUpdateAttackPowerAndDamage()
void ScriptMgr::OnPlayerBeforeUpdateAttackPowerAndDamage (Player * player, float & level, float & val2, bool ranged)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_BEFORE_UPDATE_ATTACK_POWER_AND_DAMAGE, script->OnPlayerBeforeUpdateAttackPowerAndDamage(player, level, val2, ranged));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerBeforeUpdateAttackPowerAndDamage(), and PLAYERHOOK_ON_BEFORE_UPDATE_ATTACK_POWER_AND_DAMAGE.
OnPlayerBeforeUpdateSkill()
void ScriptMgr::OnPlayerBeforeUpdateSkill (Player * player, uint32 skill_id, uint32 & value, uint32 max, uint32 step)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_BEFORE_UPDATE_SKILL, script->OnPlayerBeforeUpdateSkill(player, skillId, value, max, step));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerBeforeUpdateSkill(), and PLAYERHOOK_ON_BEFORE_UPDATE_SKILL.
OnPlayerBeingCharmed()
void ScriptMgr::OnPlayerBeingCharmed (Player * player, Unit * charmer, uint32 oldFactionId, uint32 newFactionId)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_BEING_CHARMED, script->OnPlayerBeingCharmed(player, charmer, oldFactionId, newFactionId));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerBeingCharmed(), and PLAYERHOOK_ON_BEING_CHARMED.
OnPlayerBindToInstance()
void ScriptMgr::OnPlayerBindToInstance (Player * player, Difficulty difficulty, uint32 mapid, bool permanent)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_BIND_TO_INSTANCE, script->OnPlayerBindToInstance(player, difficulty, mapid, permanent));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerBindToInstance(), and PLAYERHOOK_ON_BIND_TO_INSTANCE.
OnPlayerCalculateTalentsPoints()
void ScriptMgr::OnPlayerCalculateTalentsPoints (Player const * player, uint32 & talentPointsForLevel)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_CALCULATE_TALENTS_POINTS, script->OnPlayerCalculateTalentsPoints(player, talentPointsForLevel));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerCalculateTalentsPoints(), and PLAYERHOOK_ON_CALCULATE_TALENTS_POINTS.
OnPlayerCanApplyEnchantment()
bool ScriptMgr::OnPlayerCanApplyEnchantment (Player * player, Item * item, EnchantmentSlot slot, bool apply, bool apply_dur, bool ignore_condition)
{
    CALL_ENABLED_BOOLEAN_HOOKS(PlayerScript, PLAYERHOOK_CAN_APPLY_ENCHANTMENT, !script->OnPlayerCanApplyEnchantment(player, item, slot, apply, apply_dur, ignore_condition));
}
References CALL_ENABLED_BOOLEAN_HOOKS, PlayerScript::OnPlayerCanApplyEnchantment(), and PLAYERHOOK_CAN_APPLY_ENCHANTMENT.
OnPlayerCanApplyEquipSpell()
bool ScriptMgr::OnPlayerCanApplyEquipSpell (Player * player, SpellInfo const * spellInfo, Item * item, bool apply, bool form_change)
{
    CALL_ENABLED_BOOLEAN_HOOKS(PlayerScript, PLAYERHOOK_CAN_APPLY_EQUIP_SPELL, !script->OnPlayerCanApplyEquipSpell(player, spellInfo, item, apply, form_change));
}
References CALL_ENABLED_BOOLEAN_HOOKS, PlayerScript::OnPlayerCanApplyEquipSpell(), and PLAYERHOOK_CAN_APPLY_EQUIP_SPELL.
OnPlayerCanApplyEquipSpellsItemSet()
bool ScriptMgr::OnPlayerCanApplyEquipSpellsItemSet (Player * player, ItemSetEffect * eff)
{
    CALL_ENABLED_BOOLEAN_HOOKS(PlayerScript, PLAYERHOOK_CAN_APPLY_EQUIP_SPELLS_ITEM_SET, !script->OnPlayerCanApplyEquipSpellsItemSet(player, eff));
}
References CALL_ENABLED_BOOLEAN_HOOKS, PlayerScript::OnPlayerCanApplyEquipSpellsItemSet(), and PLAYERHOOK_CAN_APPLY_EQUIP_SPELLS_ITEM_SET.
OnPlayerCanApplyWeaponDependentAuraDamageMod()
bool ScriptMgr::OnPlayerCanApplyWeaponDependentAuraDamageMod (Player * player, Item * item, WeaponAttackType attackType, AuraEffect const * aura, bool apply)
{
    CALL_ENABLED_BOOLEAN_HOOKS(PlayerScript, PLAYERHOOK_CAN_APPLY_WEAPON_DEPENDENT_AURA_DAMAGE_MOD, !script->OnPlayerCanApplyWeaponDependentAuraDamageMod(player, item, attackType, aura, apply));
}
References CALL_ENABLED_BOOLEAN_HOOKS, PlayerScript::OnPlayerCanApplyWeaponDependentAuraDamageMod(), and PLAYERHOOK_CAN_APPLY_WEAPON_DEPENDENT_AURA_DAMAGE_MOD.
OnPlayerCanAreaExploreAndOutdoor()
bool ScriptMgr::OnPlayerCanAreaExploreAndOutdoor (Player * player)
{
    CALL_ENABLED_BOOLEAN_HOOKS(PlayerScript, PLAYERHOOK_CAN_AREA_EXPLORE_AND_OUTDOOR, !script->OnPlayerCanAreaExploreAndOutdoor(player));
}
References CALL_ENABLED_BOOLEAN_HOOKS, PlayerScript::OnPlayerCanAreaExploreAndOutdoor(), and PLAYERHOOK_CAN_AREA_EXPLORE_AND_OUTDOOR.
OnPlayerCanArmorDamageModifier()
bool ScriptMgr::OnPlayerCanArmorDamageModifier (Player * player)
{
    CALL_ENABLED_BOOLEAN_HOOKS(PlayerScript, PLAYERHOOK_CAN_ARMOR_DAMAGE_MODIFIER, !script->OnPlayerCanArmorDamageModifier(player));
}
References CALL_ENABLED_BOOLEAN_HOOKS, PlayerScript::OnPlayerCanArmorDamageModifier(), and PLAYERHOOK_CAN_ARMOR_DAMAGE_MODIFIER.
OnPlayerCanBattleFieldPort()
bool ScriptMgr::OnPlayerCanBattleFieldPort (Player * player, uint8 arenaType, BattlegroundTypeId BGTypeID, uint8 action)
{
    CALL_ENABLED_BOOLEAN_HOOKS(PlayerScript, PLAYERHOOK_CAN_BATTLEFIELD_PORT, !script->OnPlayerCanBattleFieldPort(player, arenaType, BGTypeID, action));
}
References CALL_ENABLED_BOOLEAN_HOOKS, PlayerScript::OnPlayerCanBattleFieldPort(), and PLAYERHOOK_CAN_BATTLEFIELD_PORT.
OnPlayerCanCastItemCombatSpell()
bool ScriptMgr::OnPlayerCanCastItemCombatSpell (Player * player, Unit * target, WeaponAttackType attType, uint32 procVictim, uint32 procEx, Item * item, ItemTemplate const * proto)
{
    CALL_ENABLED_BOOLEAN_HOOKS(PlayerScript, PLAYERHOOK_CAN_CAST_ITEM_COMBAT_SPELL, !script->OnPlayerCanCastItemCombatSpell(player, target, attType, procVictim, procEx, item, proto));
}
References CALL_ENABLED_BOOLEAN_HOOKS, PlayerScript::OnPlayerCanCastItemCombatSpell(), and PLAYERHOOK_CAN_CAST_ITEM_COMBAT_SPELL.
OnPlayerCanCastItemUseSpell()
bool ScriptMgr::OnPlayerCanCastItemUseSpell (Player * player, Item * item, SpellCastTargets const & targets, uint8 cast_count, uint32 glyphIndex)
{
    CALL_ENABLED_BOOLEAN_HOOKS(PlayerScript, PLAYERHOOK_CAN_CAST_ITEM_USE_SPELL, !script->OnPlayerCanCastItemUseSpell(player, item, targets, cast_count, glyphIndex));
}
References CALL_ENABLED_BOOLEAN_HOOKS, PlayerScript::OnPlayerCanCastItemUseSpell(), and PLAYERHOOK_CAN_CAST_ITEM_USE_SPELL.
OnPlayerCanEnterMap()
bool ScriptMgr::OnPlayerCanEnterMap (Player * player, MapEntry const * entry, InstanceTemplate const * instance, MapDifficulty const * mapDiff, bool loginCheck)
{
    CALL_ENABLED_BOOLEAN_HOOKS(PlayerScript, PLAYERHOOK_CAN_ENTER_MAP, !script->OnPlayerCanEnterMap(player, entry, instance, mapDiff, loginCheck));
}
References CALL_ENABLED_BOOLEAN_HOOKS, instance(), PlayerScript::OnPlayerCanEnterMap(), and PLAYERHOOK_CAN_ENTER_MAP.
OnPlayerCanEquipItem()
bool ScriptMgr::OnPlayerCanEquipItem (Player * player, uint8 slot, uint16 & dest, Item * pItem, bool swap, bool not_loading)
{
    CALL_ENABLED_BOOLEAN_HOOKS(PlayerScript, PLAYERHOOK_CAN_EQUIP_ITEM, !script->OnPlayerCanEquipItem(player, slot, dest, pItem, swap, not_loading));
}
References CALL_ENABLED_BOOLEAN_HOOKS, PlayerScript::OnPlayerCanEquipItem(), and PLAYERHOOK_CAN_EQUIP_ITEM.
OnPlayerCanFlyInZone()
bool ScriptMgr::OnPlayerCanFlyInZone (Player * player, uint32 mapId, uint32 zoneId, SpellInfo const * bySpell)
{
    CALL_ENABLED_BOOLEAN_HOOKS(PlayerScript, PLAYERHOOK_ON_CAN_PLAYER_FLY_IN_ZONE, !script->OnPlayerCanFlyInZone(player, mapId, zoneId, bySpell));
}
References CALL_ENABLED_BOOLEAN_HOOKS, PlayerScript::OnPlayerCanFlyInZone(), and PLAYERHOOK_ON_CAN_PLAYER_FLY_IN_ZONE.
OnPlayerCanGiveMailRewardAtGiveLevel()
bool ScriptMgr::OnPlayerCanGiveMailRewardAtGiveLevel (Player * player, uint8 level)
{
    CALL_ENABLED_BOOLEAN_HOOKS(PlayerScript, PLAYERHOOK_CAN_GIVE_MAIL_REWARD_AT_GIVE_LEVEL, !script->OnPlayerCanGiveMailRewardAtGiveLevel(player, level));
}
References CALL_ENABLED_BOOLEAN_HOOKS, PlayerScript::OnPlayerCanGiveMailRewardAtGiveLevel(), and PLAYERHOOK_CAN_GIVE_MAIL_REWARD_AT_GIVE_LEVEL.
OnPlayerCanGroupAccept()
bool ScriptMgr::OnPlayerCanGroupAccept (Player * player, Group * group)
{
    CALL_ENABLED_BOOLEAN_HOOKS(PlayerScript, PLAYERHOOK_CAN_GROUP_ACCEPT, !script->OnPlayerCanGroupAccept(player, group));
}
References CALL_ENABLED_BOOLEAN_HOOKS, PlayerScript::OnPlayerCanGroupAccept(), and PLAYERHOOK_CAN_GROUP_ACCEPT.
OnPlayerCanGroupInvite()
bool ScriptMgr::OnPlayerCanGroupInvite (Player * player, std::string & membername)
{
    CALL_ENABLED_BOOLEAN_HOOKS(PlayerScript, PLAYERHOOK_CAN_GROUP_INVITE, !script->OnPlayerCanGroupInvite(player, membername));
}
References CALL_ENABLED_BOOLEAN_HOOKS, PlayerScript::OnPlayerCanGroupInvite(), and PLAYERHOOK_CAN_GROUP_INVITE.
OnPlayerCanInitTrade()
bool ScriptMgr::OnPlayerCanInitTrade (Player * player, Player * target)
{
    CALL_ENABLED_BOOLEAN_HOOKS(PlayerScript, PLAYERHOOK_CAN_INIT_TRADE, !script->OnPlayerCanInitTrade(player, target));
}
References CALL_ENABLED_BOOLEAN_HOOKS, PlayerScript::OnPlayerCanInitTrade(), and PLAYERHOOK_CAN_INIT_TRADE.
OnPlayerCanJoinInArenaQueue()
bool ScriptMgr::OnPlayerCanJoinInArenaQueue (Player * player, ObjectGuid BattlemasterGuid, uint8 arenaslot, BattlegroundTypeId BGTypeID, uint8 joinAsGroup, uint8 IsRated, GroupJoinBattlegroundResult & err)
{
    CALL_ENABLED_BOOLEAN_HOOKS(PlayerScript, PLAYERHOOK_CAN_JOIN_IN_ARENA_QUEUE, !script->OnPlayerCanJoinInArenaQueue(player, BattlemasterGuid, arenaslot, BGTypeID, joinAsGroup, IsRated, err));
}
References CALL_ENABLED_BOOLEAN_HOOKS, PlayerScript::OnPlayerCanJoinInArenaQueue(), and PLAYERHOOK_CAN_JOIN_IN_ARENA_QUEUE.
OnPlayerCanJoinInBattlegroundQueue()
bool ScriptMgr::OnPlayerCanJoinInBattlegroundQueue (Player * player, ObjectGuid BattlemasterGuid, BattlegroundTypeId BGTypeID, uint8 joinAsGroup, GroupJoinBattlegroundResult & err)
{
    CALL_ENABLED_BOOLEAN_HOOKS(PlayerScript, PLAYERHOOK_CAN_JOIN_IN_BATTLEGROUND_QUEUE, !script->OnPlayerCanJoinInBattlegroundQueue(player, BattlemasterGuid, BGTypeID, joinAsGroup, err));
}
References CALL_ENABLED_BOOLEAN_HOOKS, PlayerScript::OnPlayerCanJoinInBattlegroundQueue(), and PLAYERHOOK_CAN_JOIN_IN_BATTLEGROUND_QUEUE.
OnPlayerCanJoinLfg()
bool ScriptMgr::OnPlayerCanJoinLfg (Player * player, uint8 roles, lfg::LfgDungeonSet & dungeons, const std::string & comment)
{
    CALL_ENABLED_BOOLEAN_HOOKS(PlayerScript, PLAYERHOOK_CAN_JOIN_LFG, !script->OnPlayerCanJoinLfg(player, roles, dungeons, comment));
}
References CALL_ENABLED_BOOLEAN_HOOKS, PlayerScript::OnPlayerCanJoinLfg(), and PLAYERHOOK_CAN_JOIN_LFG.
OnPlayerCanPlaceAuctionBid()
bool ScriptMgr::OnPlayerCanPlaceAuctionBid (Player * player, AuctionEntry * auction)
{
    CALL_ENABLED_BOOLEAN_HOOKS(PlayerScript, PLAYERHOOK_CAN_PLACE_AUCTION_BID, !script->OnPlayerCanPlaceAuctionBid(player, auction));
}
References CALL_ENABLED_BOOLEAN_HOOKS, PlayerScript::OnPlayerCanPlaceAuctionBid(), and PLAYERHOOK_CAN_PLACE_AUCTION_BID.
OnPlayerCanRepopAtGraveyard()
bool ScriptMgr::OnPlayerCanRepopAtGraveyard (Player * player)
{
    CALL_ENABLED_BOOLEAN_HOOKS(PlayerScript, PLAYERHOOK_CAN_REPOP_AT_GRAVEYARD, !script->OnPlayerCanRepopAtGraveyard(player));
}
References CALL_ENABLED_BOOLEAN_HOOKS, PlayerScript::OnPlayerCanRepopAtGraveyard(), and PLAYERHOOK_CAN_REPOP_AT_GRAVEYARD.
OnPlayerCanResurrect()
bool ScriptMgr::OnPlayerCanResurrect (Player * player)
{
    CALL_ENABLED_BOOLEAN_HOOKS(PlayerScript, PLAYERHOOK_CAN_RESURRECT, !script->OnPlayerCanResurrect(player));
}
References CALL_ENABLED_BOOLEAN_HOOKS, PlayerScript::OnPlayerCanResurrect(), and PLAYERHOOK_CAN_RESURRECT.
OnPlayerCanSaveEquipNewItem()
bool ScriptMgr::OnPlayerCanSaveEquipNewItem (Player * player, Item * item, uint16 pos, bool update)
{
    CALL_ENABLED_BOOLEAN_HOOKS(PlayerScript, PLAYERHOOK_CAN_SAVE_EQUIP_NEW_ITEM, !script->OnPlayerCanSaveEquipNewItem(player, item, pos, update));
}
References CALL_ENABLED_BOOLEAN_HOOKS, PlayerScript::OnPlayerCanSaveEquipNewItem(), and PLAYERHOOK_CAN_SAVE_EQUIP_NEW_ITEM.
OnPlayerCanSellItem()
bool ScriptMgr::OnPlayerCanSellItem (Player * player, Item * item, Creature * creature)
{
    CALL_ENABLED_BOOLEAN_HOOKS(PlayerScript, PLAYERHOOK_CAN_SELL_ITEM, !script->OnPlayerCanSellItem(player, item, creature));
}
References CALL_ENABLED_BOOLEAN_HOOKS, PlayerScript::OnPlayerCanSellItem(), and PLAYERHOOK_CAN_SELL_ITEM.
OnPlayerCanSendErrorAlreadyLooted()
bool ScriptMgr::OnPlayerCanSendErrorAlreadyLooted (Player * player)
{
    CALL_ENABLED_BOOLEAN_HOOKS(PlayerScript, PLAYERHOOK_CAN_SEND_ERROR_ALREADY_LOOTED, !script->OnPlayerCanSendErrorAlreadyLooted(player));
}
References CALL_ENABLED_BOOLEAN_HOOKS, PlayerScript::OnPlayerCanSendErrorAlreadyLooted(), and PLAYERHOOK_CAN_SEND_ERROR_ALREADY_LOOTED.
OnPlayerCanSendMail()
bool ScriptMgr::OnPlayerCanSendMail (Player * player, ObjectGuid receiverGuid, ObjectGuid mailbox, std::string & subject, std::string & body, uint32 money, uint32 COD, Item * item)
{
    CALL_ENABLED_BOOLEAN_HOOKS(PlayerScript, PLAYERHOOK_CAN_SEND_MAIL, !script->OnPlayerCanSendMail(player, receiverGuid, mailbox, subject, body, money, COD, item));
}
References CALL_ENABLED_BOOLEAN_HOOKS, PlayerScript::OnPlayerCanSendMail(), and PLAYERHOOK_CAN_SEND_MAIL.
OnPlayerCanSetTradeItem()
bool ScriptMgr::OnPlayerCanSetTradeItem (Player * player, Item * tradedItem, uint8 tradeSlot)
{
    CALL_ENABLED_BOOLEAN_HOOKS(PlayerScript, PLAYERHOOK_CAN_SET_TRADE_ITEM, !script->OnPlayerCanSetTradeItem(player, tradedItem, tradeSlot));
}
References CALL_ENABLED_BOOLEAN_HOOKS, PlayerScript::OnPlayerCanSetTradeItem(), and PLAYERHOOK_CAN_SET_TRADE_ITEM.
OnPlayerCanUnequipItem()
bool ScriptMgr::OnPlayerCanUnequipItem (Player * player, uint16 pos, bool swap)
{
    CALL_ENABLED_BOOLEAN_HOOKS(PlayerScript, PLAYERHOOK_CAN_UNEQUIP_ITEM, !script->OnPlayerCanUnequipItem(player, pos, swap));
}
References CALL_ENABLED_BOOLEAN_HOOKS, PlayerScript::OnPlayerCanUnequipItem(), and PLAYERHOOK_CAN_UNEQUIP_ITEM.
OnPlayerCanUpdateSkill()
bool ScriptMgr::OnPlayerCanUpdateSkill (Player * player, uint32 skillId)
{
    CALL_ENABLED_BOOLEAN_HOOKS(PlayerScript, PLAYERHOOK_ON_CAN_UPDATE_SKILL, !script->OnPlayerCanUpdateSkill(player, skillId));
}
References CALL_ENABLED_BOOLEAN_HOOKS, PlayerScript::OnPlayerCanUpdateSkill(), and PLAYERHOOK_ON_CAN_UPDATE_SKILL.
OnPlayerCanUseChat() [1/5]
bool ScriptMgr::OnPlayerCanUseChat (Player * player, uint32 type, uint32 language, std::string & msg)
{
    CALL_ENABLED_BOOLEAN_HOOKS(PlayerScript, PLAYERHOOK_CAN_PLAYER_USE_CHAT, !script->OnPlayerCanUseChat(player, type, language, msg));
}
References CALL_ENABLED_BOOLEAN_HOOKS, PlayerScript::OnPlayerCanUseChat(), and PLAYERHOOK_CAN_PLAYER_USE_CHAT.
OnPlayerCanUseChat() [2/5]
bool ScriptMgr::OnPlayerCanUseChat (Player * player, uint32 type, uint32 language, std::string & msg, Channel * channel)
{
    CALL_ENABLED_BOOLEAN_HOOKS(PlayerScript, PLAYERHOOK_CAN_PLAYER_USE_CHANNEL_CHAT, !script->OnPlayerCanUseChat(player, type, language, msg, channel));
}
References CALL_ENABLED_BOOLEAN_HOOKS, PlayerScript::OnPlayerCanUseChat(), and PLAYERHOOK_CAN_PLAYER_USE_CHANNEL_CHAT.
OnPlayerCanUseChat() [3/5]
bool ScriptMgr::OnPlayerCanUseChat (Player * player, uint32 type, uint32 language, std::string & msg, Group * group)
{
    CALL_ENABLED_BOOLEAN_HOOKS(PlayerScript, PLAYERHOOK_CAN_PLAYER_USE_GROUP_CHAT, !script->OnPlayerCanUseChat(player, type, language, msg, group));
}
References CALL_ENABLED_BOOLEAN_HOOKS, PlayerScript::OnPlayerCanUseChat(), and PLAYERHOOK_CAN_PLAYER_USE_GROUP_CHAT.
OnPlayerCanUseChat() [4/5]
bool ScriptMgr::OnPlayerCanUseChat (Player * player, uint32 type, uint32 language, std::string & msg, Guild * guild)
{
    CALL_ENABLED_BOOLEAN_HOOKS(PlayerScript, PLAYERHOOK_CAN_PLAYER_USE_GUILD_CHAT, !script->OnPlayerCanUseChat(player, type, language, msg, guild));
}
References CALL_ENABLED_BOOLEAN_HOOKS, PlayerScript::OnPlayerCanUseChat(), and PLAYERHOOK_CAN_PLAYER_USE_GUILD_CHAT.
OnPlayerCanUseChat() [5/5]
bool ScriptMgr::OnPlayerCanUseChat (Player * player, uint32 type, uint32 language, std::string & msg, Player * receiver)
{
    CALL_ENABLED_BOOLEAN_HOOKS(PlayerScript, PLAYERHOOK_CAN_PLAYER_USE_PRIVATE_CHAT, !script->OnPlayerCanUseChat(player, type, language, msg, receiver));
}
References CALL_ENABLED_BOOLEAN_HOOKS, PlayerScript::OnPlayerCanUseChat(), and PLAYERHOOK_CAN_PLAYER_USE_PRIVATE_CHAT.
OnPlayerCanUseItem()
bool ScriptMgr::OnPlayerCanUseItem (Player * player, ItemTemplate const * proto, InventoryResult & result)
{
    CALL_ENABLED_BOOLEAN_HOOKS(PlayerScript, PLAYERHOOK_CAN_USE_ITEM, !script->OnPlayerCanUseItem(player, proto, result));
}
References CALL_ENABLED_BOOLEAN_HOOKS, PlayerScript::OnPlayerCanUseItem(), and PLAYERHOOK_CAN_USE_ITEM.
OnPlayerChat() [1/5]
void ScriptMgr::OnPlayerChat (Player * player, uint32 type, uint32 lang, std::string & msg)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_CHAT, script->OnPlayerChat(player, type, lang, msg));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerChat(), and PLAYERHOOK_ON_CHAT.
OnPlayerChat() [2/5]
void ScriptMgr::OnPlayerChat (Player * player, uint32 type, uint32 lang, std::string & msg, Channel * channel)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_CHAT_WITH_CHANNEL, script->OnPlayerChat(player, type, lang, msg, channel));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerChat(), and PLAYERHOOK_ON_CHAT_WITH_CHANNEL.
OnPlayerChat() [3/5]
void ScriptMgr::OnPlayerChat (Player * player, uint32 type, uint32 lang, std::string & msg, Group * group)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_CHAT_WITH_GROUP, script->OnPlayerChat(player, type, lang, msg, group));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerChat(), and PLAYERHOOK_ON_CHAT_WITH_GROUP.
OnPlayerChat() [4/5]
void ScriptMgr::OnPlayerChat (Player * player, uint32 type, uint32 lang, std::string & msg, Guild * guild)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_CHAT_WITH_GUILD, script->OnPlayerChat(player, type, lang, msg, guild));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerChat(), and PLAYERHOOK_ON_CHAT_WITH_GUILD.
OnPlayerChat() [5/5]
void ScriptMgr::OnPlayerChat (Player * player, uint32 type, uint32 lang, std::string & msg, Player * receiver)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_CHAT_WITH_RECEIVER, script->OnPlayerChat(player, type, lang, msg, receiver));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerChat(), and PLAYERHOOK_ON_CHAT_WITH_RECEIVER.
OnPlayerCheckItemInSlotAtLoadInventory()
bool ScriptMgr::OnPlayerCheckItemInSlotAtLoadInventory (Player * player, Item * item, uint8 slot, uint8 & err, uint16 & dest)
{
    CALL_ENABLED_BOOLEAN_HOOKS(PlayerScript, PLAYERHOOK_CHECK_ITEM_IN_SLOT_AT_LOAD_INVENTORY, !script->OnPlayerCheckItemInSlotAtLoadInventory(player, item, slot, err, dest));
}
References CALL_ENABLED_BOOLEAN_HOOKS, PlayerScript::OnPlayerCheckItemInSlotAtLoadInventory(), and PLAYERHOOK_CHECK_ITEM_IN_SLOT_AT_LOAD_INVENTORY.
OnPlayerCompleteQuest()
void ScriptMgr::OnPlayerCompleteQuest (Player * player, Quest const * quest)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_PLAYER_COMPLETE_QUEST, script->OnPlayerCompleteQuest(player, quest));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerCompleteQuest(), and PLAYERHOOK_ON_PLAYER_COMPLETE_QUEST.
OnPlayerCreate()
void ScriptMgr::OnPlayerCreate (Player * player)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_CREATE, script->OnPlayerCreate(player));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerCreate(), and PLAYERHOOK_ON_CREATE.
OnPlayerCreateItem()
void ScriptMgr::OnPlayerCreateItem (Player * player, Item * item, uint32 count)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_CREATE_ITEM, script->OnPlayerCreateItem(player, item, count));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerCreateItem(), and PLAYERHOOK_ON_CREATE_ITEM.
OnPlayerCreatureKill()
void ScriptMgr::OnPlayerCreatureKill (Player * killer, Creature * killed)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_CREATURE_KILL, script->OnPlayerCreatureKill(killer, killed));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerCreatureKill(), and PLAYERHOOK_ON_CREATURE_KILL.
OnPlayerCreatureKilledByPet()
void ScriptMgr::OnPlayerCreatureKilledByPet (Player * petOwner, Creature * killed)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_CREATURE_KILLED_BY_PET, script->OnPlayerCreatureKilledByPet(petOwner, killed));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerCreatureKilledByPet(), and PLAYERHOOK_ON_CREATURE_KILLED_BY_PET.
OnPlayerCriteriaProgress()
void ScriptMgr::OnPlayerCriteriaProgress (Player * player, AchievementCriteriaEntry const * criteria)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_CRITERIA_PROGRESS, script->OnPlayerCriteriaProgress(player, criteria));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerCriteriaProgress(), and PLAYERHOOK_ON_CRITERIA_PROGRESS.
OnPlayerCriteriaSave()
void ScriptMgr::OnPlayerCriteriaSave (CharacterDatabaseTransaction trans, Player * player, uint16 critId, CriteriaProgress criteriaData)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_CRITERIA_SAVE, script->OnPlayerCriteriaSave(trans, player, critId, criteriaData));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerCriteriaSave(), and PLAYERHOOK_ON_CRITERIA_SAVE.
OnPlayerCustomScalingStatValue()
void ScriptMgr::OnPlayerCustomScalingStatValue (Player * player, ItemTemplate const * proto, uint32 & statType, int32 & val, uint8 itemProtoStatNumber, uint32 ScalingStatValue, ScalingStatValuesEntry const * ssv)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_CUSTOM_SCALING_STAT_VALUE, script->OnPlayerCustomScalingStatValue(player, proto, statType, val, itemProtoStatNumber, ScalingStatValue, ssv));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerCustomScalingStatValue(), and PLAYERHOOK_ON_CUSTOM_SCALING_STAT_VALUE.
OnPlayerCustomScalingStatValueBefore()
void ScriptMgr::OnPlayerCustomScalingStatValueBefore (Player * player, ItemTemplate const * proto, uint8 slot, bool apply, uint32 & CustomScalingStatValue)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_CUSTOM_SCALING_STAT_VALUE_BEFORE, script->OnPlayerCustomScalingStatValueBefore(player, proto, slot, apply, CustomScalingStatValue));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerCustomScalingStatValueBefore(), and PLAYERHOOK_ON_CUSTOM_SCALING_STAT_VALUE_BEFORE.
OnPlayerDelete()
void ScriptMgr::OnPlayerDelete (ObjectGuid guid, uint32 accountId)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_DELETE, script->OnPlayerDelete(guid, accountId));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerDelete(), and PLAYERHOOK_ON_DELETE.
OnPlayerDeleteFromDB()
void ScriptMgr::OnPlayerDeleteFromDB (CharacterDatabaseTransaction trans, uint32 guid)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_DELETE_FROM_DB, script->OnPlayerDeleteFromDB(trans, guid));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerDeleteFromDB(), and PLAYERHOOK_ON_DELETE_FROM_DB.
OnPlayerDuelEnd()
void ScriptMgr::OnPlayerDuelEnd (Player * winner, Player * loser, DuelCompleteType type)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_DUEL_END, script->OnPlayerDuelEnd(winner, loser, type));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerDuelEnd(), and PLAYERHOOK_ON_DUEL_END.
OnPlayerDuelRequest()
void ScriptMgr::OnPlayerDuelRequest (Player * target, Player * challenger)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_DUEL_REQUEST, script->OnPlayerDuelRequest(target, challenger));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerDuelRequest(), and PLAYERHOOK_ON_DUEL_REQUEST.
OnPlayerDuelStart()
void ScriptMgr::OnPlayerDuelStart (Player * player1, Player * player2)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_DUEL_START, script->OnPlayerDuelStart(player1, player2));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerDuelStart(), and PLAYERHOOK_ON_DUEL_START.
OnPlayerEmote()
void ScriptMgr::OnPlayerEmote (Player * player, uint32 emote)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_EMOTE, script->OnPlayerEmote(player, emote));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerEmote(), and PLAYERHOOK_ON_EMOTE.
OnPlayerEnterCombat()
void ScriptMgr::OnPlayerEnterCombat (Player * player, Unit * enemy)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_PLAYER_ENTER_COMBAT, script->OnPlayerEnterCombat(player, enemy));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerEnterCombat(), and PLAYERHOOK_ON_PLAYER_ENTER_COMBAT.
OnPlayerEnterMap()
void ScriptMgr::OnPlayerEnterMap (Map * map, Player * player)
{
    ASSERT(map);
    ASSERT(player);
    CALL_ENABLED_HOOKS(AllMapScript, ALLMAPHOOK_ON_PLAYER_ENTER_ALL, script->OnPlayerEnterAll(map, player));
    ExecuteScript<PlayerScript>([=](PlayerScript* script)
    {
        script->OnPlayerMapChanged(player);
    });
    ForeachMaps<WorldMapScript>(map,
    [&](WorldMapScript* script)
    {
        script->OnPlayerEnter(map, player);
    });
    ForeachMaps<InstanceMapScript>(map,
    [&](InstanceMapScript* script)
    {
        script->OnPlayerEnter((InstanceMap*)map, player);
    });
    ForeachMaps<BattlegroundMapScript>(map,
    [&](BattlegroundMapScript* script)
    {
        script->OnPlayerEnter((BattlegroundMap*)map, player);
    });
}
References ALLMAPHOOK_ON_PLAYER_ENTER_ALL, ASSERT, CALL_ENABLED_HOOKS, AllMapScript::OnPlayerEnterAll(), and PlayerScript::OnPlayerMapChanged().
OnPlayerEquip()
void ScriptMgr::OnPlayerEquip (Player * player, Item * it, uint8 bag, uint8 slot, bool update)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_EQUIP, script->OnPlayerEquip(player, it, bag, slot, update));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerEquip(), and PLAYERHOOK_ON_EQUIP.
OnPlayerFailedDelete()
void ScriptMgr::OnPlayerFailedDelete (ObjectGuid guid, uint32 accountId)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_FAILED_DELETE, script->OnPlayerFailedDelete(guid, accountId));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerFailedDelete(), and PLAYERHOOK_ON_FAILED_DELETE.
OnPlayerFfaPvpStateUpdate()
void ScriptMgr::OnPlayerFfaPvpStateUpdate (Player * player, bool result)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_FFA_PVP_STATE_UPDATE, script->OnPlayerFfaPvpStateUpdate(player, result));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerFfaPvpStateUpdate(), and PLAYERHOOK_ON_FFA_PVP_STATE_UPDATE.
OnPlayerFirstLogin()
void ScriptMgr::OnPlayerFirstLogin (Player * player)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_FIRST_LOGIN, script->OnPlayerFirstLogin(player));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerFirstLogin(), and PLAYERHOOK_ON_FIRST_LOGIN.
OnPlayerForgotSpell()
void ScriptMgr::OnPlayerForgotSpell (Player * player, uint32 spellID)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_FORGOT_SPELL, script->OnPlayerForgotSpell(player, spellID));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerForgotSpell(), and PLAYERHOOK_ON_FORGOT_SPELL.
OnPlayerFreeTalentPointsChanged()
void ScriptMgr::OnPlayerFreeTalentPointsChanged (Player * player, uint32 newPoints)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_FREE_TALENT_POINTS_CHANGED, script->OnPlayerFreeTalentPointsChanged(player, points));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerFreeTalentPointsChanged(), and PLAYERHOOK_ON_FREE_TALENT_POINTS_CHANGED.
OnPlayerGetArenaPersonalRating()
void ScriptMgr::OnPlayerGetArenaPersonalRating (Player * player, uint8 slot, uint32 & result)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_GET_ARENA_PERSONAL_RATING, script->OnPlayerGetArenaPersonalRating(player, slot, result));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerGetArenaPersonalRating(), and PLAYERHOOK_ON_GET_ARENA_PERSONAL_RATING.
OnPlayerGetArenaTeamId()
void ScriptMgr::OnPlayerGetArenaTeamId (Player * player, uint8 slot, uint32 & result)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_GET_ARENA_TEAM_ID, script->OnPlayerGetArenaTeamId(player, slot, result));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerGetArenaTeamId(), and PLAYERHOOK_ON_GET_ARENA_TEAM_ID.
OnPlayerGetFeralApBonus()
void ScriptMgr::OnPlayerGetFeralApBonus (Player * player, int32 & feral_bonus, int32 dpsMod, ItemTemplate const * proto, ScalingStatValuesEntry const * ssv)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_GET_FERAL_AP_BONUS, script->OnPlayerGetFeralApBonus(player, feral_bonus, dpsMod, proto, ssv));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerGetFeralApBonus(), and PLAYERHOOK_ON_GET_FERAL_AP_BONUS.
OnPlayerGetMaxPersonalArenaRatingRequirement()
void ScriptMgr::OnPlayerGetMaxPersonalArenaRatingRequirement (Player const * player, uint32 minSlot, uint32 & maxArenaRating) const
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_GET_MAX_PERSONAL_ARENA_RATING_REQUIREMENT, script->OnPlayerGetMaxPersonalArenaRatingRequirement(player, minSlot, maxArenaRating));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerGetMaxPersonalArenaRatingRequirement(), and PLAYERHOOK_ON_GET_MAX_PERSONAL_ARENA_RATING_REQUIREMENT.
OnPlayerGetMaxSkillValue()
void ScriptMgr::OnPlayerGetMaxSkillValue (Player * player, uint32 skill, int32 & result, bool IsPure)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_GET_MAX_SKILL_VALUE, script->OnPlayerGetMaxSkillValue(player, skill, result, IsPure));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerGetMaxSkillValue(), and PLAYERHOOK_ON_GET_MAX_SKILL_VALUE.
OnPlayerGetMaxSkillValueForLevel()
void ScriptMgr::OnPlayerGetMaxSkillValueForLevel (Player * player, uint16 & result)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_GET_MAX_SKILL_VALUE_FOR_LEVEL, script->OnPlayerGetMaxSkillValueForLevel(player, result));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerGetMaxSkillValueForLevel(), and PLAYERHOOK_ON_GET_MAX_SKILL_VALUE_FOR_LEVEL.
OnPlayerGetQuestRate()
void ScriptMgr::OnPlayerGetQuestRate (Player * player, float & result)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_GET_QUEST_RATE, script->OnPlayerGetQuestRate(player, result));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerGetQuestRate(), and PLAYERHOOK_ON_GET_QUEST_RATE.
OnPlayerGiveXP()
void ScriptMgr::OnPlayerGiveXP (Player * player, uint32 & amount, Unit * victim, uint8 xpSource)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_GIVE_EXP, script->OnPlayerGiveXP(player, amount, victim, xpSource));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerGiveXP(), and PLAYERHOOK_ON_GIVE_EXP.
OnPlayerGossipSelect()
void ScriptMgr::OnPlayerGossipSelect (Player * player, uint32 menu_id, uint32 sender, uint32 action)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_GOSSIP_SELECT, script->OnPlayerGossipSelect(player, menu_id, sender, action));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerGossipSelect(), and PLAYERHOOK_ON_GOSSIP_SELECT.
OnPlayerGossipSelectCode()
void ScriptMgr::OnPlayerGossipSelectCode (Player * player, uint32 menu_id, uint32 sender, uint32 action, const char * code)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_GOSSIP_SELECT_CODE, script->OnPlayerGossipSelectCode(player, menu_id, sender, action, code));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerGossipSelectCode(), and PLAYERHOOK_ON_GOSSIP_SELECT_CODE.
OnPlayerGroupRollRewardItem()
void ScriptMgr::OnPlayerGroupRollRewardItem (Player * player, Item * item, uint32 count, RollVote voteType, Roll * roll)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_GROUP_ROLL_REWARD_ITEM, script->OnPlayerGroupRollRewardItem(player, item, count, voteType, roll));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerGroupRollRewardItem(), and PLAYERHOOK_ON_GROUP_ROLL_REWARD_ITEM.
OnPlayerHasActivePowerType()
bool ScriptMgr::OnPlayerHasActivePowerType (Player const * player, Powers power)
{
    CALL_ENABLED_BOOLEAN_HOOKS_WITH_DEFAULT_FALSE(PlayerScript, PLAYERHOOK_ON_PLAYER_HAS_ACTIVE_POWER_TYPE, script->OnPlayerHasActivePowerType(player, power));
}
References CALL_ENABLED_BOOLEAN_HOOKS_WITH_DEFAULT_FALSE, PlayerScript::OnPlayerHasActivePowerType(), and PLAYERHOOK_ON_PLAYER_HAS_ACTIVE_POWER_TYPE.
OnPlayerIsClass()
Optional< bool > ScriptMgr::OnPlayerIsClass (Player const * player, Classes playerClass, ClassContext context)
{
    if (ScriptRegistry<PlayerScript>::EnabledHooks[PLAYERHOOK_ON_PLAYER_IS_CLASS].empty())
        return {};
    for (auto const& script : ScriptRegistry<PlayerScript>::EnabledHooks[PLAYERHOOK_ON_PLAYER_IS_CLASS])
    {
        Optional<bool> scriptResult = script->OnPlayerIsClass(player, unitClass, context);
        if (scriptResult)
            return scriptResult;
    }
    return {};
}
References PLAYERHOOK_ON_PLAYER_IS_CLASS.
OnPlayerIsFFAPvP()
void ScriptMgr::OnPlayerIsFFAPvP (Player * player, bool & result)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_IS_FFA_PVP, script->OnPlayerIsFFAPvP(player, result));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerIsFFAPvP(), and PLAYERHOOK_ON_IS_FFA_PVP.
OnPlayerIsPvP()
void ScriptMgr::OnPlayerIsPvP (Player * player, bool & result)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_IS_PVP, script->OnPlayerIsPvP(player, result));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerIsPvP(), and PLAYERHOOK_ON_IS_PVP.
OnPlayerJoinArena()
void ScriptMgr::OnPlayerJoinArena (Player * player)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_PLAYER_JOIN_ARENA, script->OnPlayerJoinArena(player));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerJoinArena(), and PLAYERHOOK_ON_PLAYER_JOIN_ARENA.
OnPlayerJoinBG()
void ScriptMgr::OnPlayerJoinBG (Player * player)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_PLAYER_JOIN_BG, script->OnPlayerJoinBG(player));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerJoinBG(), and PLAYERHOOK_ON_PLAYER_JOIN_BG.
OnPlayerJustDied()
void ScriptMgr::OnPlayerJustDied (Player * player)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_PLAYER_JUST_DIED, script->OnPlayerJustDied(player));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerJustDied(), and PLAYERHOOK_ON_PLAYER_JUST_DIED.
OnPlayerKilledByCreature()
void ScriptMgr::OnPlayerKilledByCreature (Creature * killer, Player * killed)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_PLAYER_KILLED_BY_CREATURE, script->OnPlayerKilledByCreature(killer, killed));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerKilledByCreature(), and PLAYERHOOK_ON_PLAYER_KILLED_BY_CREATURE.
OnPlayerLearnSpell()
void ScriptMgr::OnPlayerLearnSpell (Player * player, uint32 spellID)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_LEARN_SPELL, script->OnPlayerLearnSpell(player, spellID));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerLearnSpell(), and PLAYERHOOK_ON_LEARN_SPELL.
OnPlayerLearnTalents()
void ScriptMgr::OnPlayerLearnTalents (Player * player, uint32 talentId, uint32 talentRank, uint32 spellid)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_PLAYER_LEARN_TALENTS, script->OnPlayerLearnTalents(player, talentId, talentRank, spellid));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerLearnTalents(), and PLAYERHOOK_ON_PLAYER_LEARN_TALENTS.
OnPlayerLeaveCombat()
void ScriptMgr::OnPlayerLeaveCombat (Player * player)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_PLAYER_LEAVE_COMBAT, script->OnPlayerLeaveCombat(player));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerLeaveCombat(), and PLAYERHOOK_ON_PLAYER_LEAVE_COMBAT.
OnPlayerLeaveMap()
void ScriptMgr::OnPlayerLeaveMap (Map * map, Player * player)
{
    ASSERT(map);
    ASSERT(player);
    CALL_ENABLED_HOOKS(AllMapScript, ALLMAPHOOK_ON_PLAYER_LEAVE_ALL, script->OnPlayerLeaveAll(map, player));
    ForeachMaps<WorldMapScript>(map,
    [&](WorldMapScript* script)
    {
        script->OnPlayerLeave(map, player);
    });
    ForeachMaps<InstanceMapScript>(map,
    [&](InstanceMapScript* script)
    {
        script->OnPlayerLeave((InstanceMap*)map, player);
    });
    ForeachMaps<BattlegroundMapScript>(map,
    [&](BattlegroundMapScript* script)
    {
        script->OnPlayerLeave((BattlegroundMap*)map, player);
    });
}
References ALLMAPHOOK_ON_PLAYER_LEAVE_ALL, ASSERT, CALL_ENABLED_HOOKS, MapScript< TMap >::OnPlayerLeave(), and AllMapScript::OnPlayerLeaveAll().
OnPlayerLevelChanged()
void ScriptMgr::OnPlayerLevelChanged (Player * player, uint8 oldLevel)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_LEVEL_CHANGED, script->OnPlayerLevelChanged(player, oldLevel));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerLevelChanged(), and PLAYERHOOK_ON_LEVEL_CHANGED.
OnPlayerLoadFromDB()
void ScriptMgr::OnPlayerLoadFromDB (Player * player)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_LOAD_FROM_DB, script->OnPlayerLoadFromDB(player));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerLoadFromDB(), and PLAYERHOOK_ON_LOAD_FROM_DB.
OnPlayerLogin()
void ScriptMgr::OnPlayerLogin (Player * player)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_LOGIN, script->OnPlayerLogin(player));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerLogin(), and PLAYERHOOK_ON_LOGIN.
OnPlayerLogout()
void ScriptMgr::OnPlayerLogout (Player * player)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_LOGOUT, script->OnPlayerLogout(player));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerLogout(), and PLAYERHOOK_ON_LOGOUT.
OnPlayerLootItem()
void ScriptMgr::OnPlayerLootItem (Player * player, Item * item, uint32 count, ObjectGuid lootguid)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_LOOT_ITEM, script->OnPlayerLootItem(player, item, count, lootguid));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerLootItem(), and PLAYERHOOK_ON_LOOT_ITEM.
OnPlayerMoneyChanged()
void ScriptMgr::OnPlayerMoneyChanged (Player * player, int32 & amount)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_MONEY_CHANGED, script->OnPlayerMoneyChanged(player, amount));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerMoneyChanged(), and PLAYERHOOK_ON_MONEY_CHANGED.
OnPlayerMove()
void ScriptMgr::OnPlayerMove (Player * player, MovementInfo movementInfo, uint32 opcode)
{
    CALL_ENABLED_HOOKS(MovementHandlerScript, MOVEMENTHOOK_ON_PLAYER_MOVE, script->OnPlayerMove(player, movementInfo, opcode));
}
References CALL_ENABLED_HOOKS, MOVEMENTHOOK_ON_PLAYER_MOVE, and MovementHandlerScript::OnPlayerMove().
OnPlayerNotAvoidSatisfy()
bool ScriptMgr::OnPlayerNotAvoidSatisfy (Player * player, DungeonProgressionRequirements const * ar, uint32 target_map, bool report)
{
    CALL_ENABLED_BOOLEAN_HOOKS(PlayerScript, PLAYERHOOK_NOT_AVOID_SATISFY, !script->OnPlayerNotAvoidSatisfy(player, ar, target_map, report));
}
References CALL_ENABLED_BOOLEAN_HOOKS, PlayerScript::OnPlayerNotAvoidSatisfy(), and PLAYERHOOK_NOT_AVOID_SATISFY.
OnPlayerNotSetArenaTeamInfoField()
bool ScriptMgr::OnPlayerNotSetArenaTeamInfoField (Player * player, uint8 slot, ArenaTeamInfoType type, uint32 value)
{
    CALL_ENABLED_BOOLEAN_HOOKS(PlayerScript, PLAYERHOOK_NOT_SET_ARENA_TEAM_INFO_FIELD, !script->OnPlayerNotSetArenaTeamInfoField(player, slot, type, value));
}
References CALL_ENABLED_BOOLEAN_HOOKS, PlayerScript::OnPlayerNotSetArenaTeamInfoField(), and PLAYERHOOK_NOT_SET_ARENA_TEAM_INFO_FIELD.
OnPlayerNotVisibleGloballyFor()
bool ScriptMgr::OnPlayerNotVisibleGloballyFor (Player * player, Player const * u)
{
    CALL_ENABLED_BOOLEAN_HOOKS(PlayerScript, PLAYERHOOK_NOT_VISIBLE_GLOBALLY_FOR, !script->OnPlayerNotVisibleGloballyFor(player, u));
}
References CALL_ENABLED_BOOLEAN_HOOKS, PlayerScript::OnPlayerNotVisibleGloballyFor(), and PLAYERHOOK_NOT_VISIBLE_GLOBALLY_FOR.
OnPlayerPassedQuestKilledMonsterCredit()
bool ScriptMgr::OnPlayerPassedQuestKilledMonsterCredit (Player * player, Quest const * qinfo, uint32 entry, uint32 real_entry, ObjectGuid guid)
{
    CALL_ENABLED_BOOLEAN_HOOKS(PlayerScript, PLAYERHOOK_PASSED_QUEST_KILLED_MONSTER_CREDIT, !script->OnPlayerPassedQuestKilledMonsterCredit(player, qinfo, entry, real_entry, guid));
}
References CALL_ENABLED_BOOLEAN_HOOKS, PlayerScript::OnPlayerPassedQuestKilledMonsterCredit(), and PLAYERHOOK_PASSED_QUEST_KILLED_MONSTER_CREDIT.
OnPlayerPetitionBuy()
void ScriptMgr::OnPlayerPetitionBuy (Player * player, Creature * creature, uint32 & charterid, uint32 & cost, uint32 & type)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_PETITION_BUY, script->OnPlayerPetitionBuy(player, creature, charterid, cost, type));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerPetitionBuy(), and PLAYERHOOK_PETITION_BUY.
OnPlayerPetitionShowList()
void ScriptMgr::OnPlayerPetitionShowList (Player * player, Creature * creature, uint32 & CharterEntry, uint32 & CharterDispayID, uint32 & CharterCost)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_PETITION_SHOW_LIST, script->OnPlayerPetitionShowList(player, creature, CharterEntry, CharterDispayID, CharterCost));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerPetitionShowList(), and PLAYERHOOK_PETITION_SHOW_LIST.
OnPlayerPVPFlagChange()
void ScriptMgr::OnPlayerPVPFlagChange (Player * player, bool state)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_PLAYER_PVP_FLAG_CHANGE, script->OnPlayerPVPFlagChange(player, state));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerPVPFlagChange(), and PLAYERHOOK_ON_PLAYER_PVP_FLAG_CHANGE.
OnPlayerPVPKill()
void ScriptMgr::OnPlayerPVPKill (Player * killer, Player * killed)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_PVP_KILL, script->OnPlayerPVPKill(killer, killed));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerPVPKill(), and PLAYERHOOK_ON_PVP_KILL.
OnPlayerQuestAbandon()
void ScriptMgr::OnPlayerQuestAbandon (Player * player, uint32 questId)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_QUEST_ABANDON, script->OnPlayerQuestAbandon(player, questId));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerQuestAbandon(), and PLAYERHOOK_ON_QUEST_ABANDON.
OnPlayerQuestComputeXP()
void ScriptMgr::OnPlayerQuestComputeXP (Player * player, Quest const * quest, uint32 & xpValue)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_QUEST_COMPUTE_EXP, script->OnPlayerQuestComputeXP(player, quest, xpValue));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerQuestComputeXP(), and PLAYERHOOK_ON_QUEST_COMPUTE_EXP.
OnPlayerQuestRewardItem()
void ScriptMgr::OnPlayerQuestRewardItem (Player * player, Item * item, uint32 count)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_QUEST_REWARD_ITEM, script->OnPlayerQuestRewardItem(player, item, count));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerQuestRewardItem(), and PLAYERHOOK_ON_QUEST_REWARD_ITEM.
OnPlayerQueueRandomDungeon()
void ScriptMgr::OnPlayerQueueRandomDungeon (Player * player, uint32 & rDungeonId)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_QUEUE_RANDOM_DUNGEON, script->OnPlayerQueueRandomDungeon(player, rDungeonId));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerQueueRandomDungeon(), and PLAYERHOOK_ON_QUEUE_RANDOM_DUNGEON.
OnPlayerReleasedGhost()
void ScriptMgr::OnPlayerReleasedGhost (Player * player)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_PLAYER_RELEASED_GHOST, script->OnPlayerReleasedGhost(player));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerReleasedGhost(), and PLAYERHOOK_ON_PLAYER_RELEASED_GHOST.
OnPlayerRemoveFromBattleground()
void ScriptMgr::OnPlayerRemoveFromBattleground (Player * player, Battleground * bg)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_REMOVE_FROM_BATTLEGROUND, script->OnPlayerRemoveFromBattleground(player, bg));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerRemoveFromBattleground(), and PLAYERHOOK_ON_REMOVE_FROM_BATTLEGROUND.
OnPlayerReputationChange()
bool ScriptMgr::OnPlayerReputationChange (Player * player, uint32 factionID, int32 & standing, bool incremental)
{
    CALL_ENABLED_BOOLEAN_HOOKS(PlayerScript, PLAYERHOOK_ON_REPUTATION_CHANGE, !script->OnPlayerReputationChange(player, factionID, standing, incremental));
}
References CALL_ENABLED_BOOLEAN_HOOKS, PlayerScript::OnPlayerReputationChange(), and PLAYERHOOK_ON_REPUTATION_CHANGE.
OnPlayerReputationRankChange()
void ScriptMgr::OnPlayerReputationRankChange (Player * player, uint32 factionID, ReputationRank newRank, ReputationRank oldRank, bool increased)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_REPUTATION_RANK_CHANGE, script->OnPlayerReputationRankChange(player, factionID, newRank, oldRank, increased));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerReputationRankChange(), and PLAYERHOOK_ON_REPUTATION_RANK_CHANGE.
OnPlayerResurrect()
void ScriptMgr::OnPlayerResurrect (Player * player, float restore_percent, bool applySickness)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_PLAYER_RESURRECT, script->OnPlayerResurrect(player, restore_percent, applySickness));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerResurrect(), and PLAYERHOOK_ON_PLAYER_RESURRECT.
OnPlayerRewardKillRewarder()
void ScriptMgr::OnPlayerRewardKillRewarder (Player * player, KillRewarder * rewarder, bool isDungeon, float & rate)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_REWARD_KILL_REWARDER, script->OnPlayerRewardKillRewarder(player, rewarder, isDungeon, rate));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerRewardKillRewarder(), and PLAYERHOOK_ON_REWARD_KILL_REWARDER.
OnPlayerSave()
void ScriptMgr::OnPlayerSave (Player * player)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_SAVE, script->OnPlayerSave(player));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerSave(), and PLAYERHOOK_ON_SAVE.
OnPlayerSendInitialPacketsBeforeAddToMap()
void ScriptMgr::OnPlayerSendInitialPacketsBeforeAddToMap (Player * player, WorldPacket & data)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_SEND_INITIAL_PACKETS_BEFORE_ADD_TO_MAP, script->OnPlayerSendInitialPacketsBeforeAddToMap(player, data));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerSendInitialPacketsBeforeAddToMap(), and PLAYERHOOK_ON_SEND_INITIAL_PACKETS_BEFORE_ADD_TO_MAP.
OnPlayerSetMaxLevel()
void ScriptMgr::OnPlayerSetMaxLevel (Player * player, uint32 & maxPlayerLevel)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_SET_MAX_LEVEL, script->OnPlayerSetMaxLevel(player, maxPlayerLevel));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerSetMaxLevel(), and PLAYERHOOK_ON_SET_MAX_LEVEL.
OnPlayerSetPhase()
void ScriptMgr::OnPlayerSetPhase (const AuraEffect * auraEff, AuraApplication const * aurApp, uint8 mode, bool apply, uint32 & newPhase)
{
    CALL_ENABLED_HOOKS(MiscScript, MISCHOOK_ON_PLAYER_SET_PHASE, script->OnPlayerSetPhase(auraEff, aurApp, mode, apply, newPhase));
}
References CALL_ENABLED_HOOKS, MISCHOOK_ON_PLAYER_SET_PHASE, and MiscScript::OnPlayerSetPhase().
OnPlayerSetServerSideVisibility()
void ScriptMgr::OnPlayerSetServerSideVisibility (Player * player, ServerSideVisibilityType & type, AccountTypes & sec)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_SET_SERVER_SIDE_VISIBILITY, script->OnPlayerSetServerSideVisibility(player, type, sec));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerSetServerSideVisibility(), and PLAYERHOOK_ON_SET_SERVER_SIDE_VISIBILITY.
OnPlayerSetServerSideVisibilityDetect()
void ScriptMgr::OnPlayerSetServerSideVisibilityDetect (Player * player, ServerSideVisibilityType & type, AccountTypes & sec)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_SET_SERVER_SIDE_VISIBILITY_DETECT, script->OnPlayerSetServerSideVisibilityDetect(player, type, sec));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerSetServerSideVisibilityDetect(), and PLAYERHOOK_ON_SET_SERVER_SIDE_VISIBILITY_DETECT.
OnPlayerShouldBeRewardedWithMoneyInsteadOfExp()
bool ScriptMgr::OnPlayerShouldBeRewardedWithMoneyInsteadOfExp (Player * player)
{
    CALL_ENABLED_BOOLEAN_HOOKS_WITH_DEFAULT_FALSE(PlayerScript, PLAYERHOOK_SHOULD_BE_REWARDED_WITH_MONEY_INSTEAD_OF_EXP, script->OnPlayerShouldBeRewardedWithMoneyInsteadOfExp(player));
}
References CALL_ENABLED_BOOLEAN_HOOKS_WITH_DEFAULT_FALSE, PlayerScript::OnPlayerShouldBeRewardedWithMoneyInsteadOfExp(), and PLAYERHOOK_SHOULD_BE_REWARDED_WITH_MONEY_INSTEAD_OF_EXP.
OnPlayerSpellCast()
void ScriptMgr::OnPlayerSpellCast (Player * player, Spell * spell, bool skipCheck)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_SPELL_CAST, script->OnPlayerSpellCast(player, spell, skipCheck));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerSpellCast(), and PLAYERHOOK_ON_SPELL_CAST.
OnPlayerStoreNewItem()
void ScriptMgr::OnPlayerStoreNewItem (Player * player, Item * item, uint32 count)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_STORE_NEW_ITEM, script->OnPlayerStoreNewItem(player, item, count));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerStoreNewItem(), and PLAYERHOOK_ON_STORE_NEW_ITEM.
OnPlayerTalentsReset()
void ScriptMgr::OnPlayerTalentsReset (Player * player, bool noCost)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_TALENTS_RESET, script->OnPlayerTalentsReset(player, noCost));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerTalentsReset(), and PLAYERHOOK_ON_TALENTS_RESET.
OnPlayerTextEmote()
void ScriptMgr::OnPlayerTextEmote (Player * player, uint32 textEmote, uint32 emoteNum, ObjectGuid guid)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_TEXT_EMOTE, script->OnPlayerTextEmote(player, textEmote, emoteNum, guid));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerTextEmote(), and PLAYERHOOK_ON_TEXT_EMOTE.
OnPlayerUpdate()
void ScriptMgr::OnPlayerUpdate (Player * player, uint32 p_time)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_UPDATE, script->OnPlayerUpdate(player, p_time));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerUpdate(), and PLAYERHOOK_ON_UPDATE.
OnPlayerUpdateArea()
void ScriptMgr::OnPlayerUpdateArea (Player * player, uint32 oldArea, uint32 newArea)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_UPDATE_AREA, script->OnPlayerUpdateArea(player, oldArea, newArea));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerUpdateArea(), and PLAYERHOOK_ON_UPDATE_AREA.
OnPlayerUpdateCraftingSkill()
void ScriptMgr::OnPlayerUpdateCraftingSkill (Player * player, SkillLineAbilityEntry const * skill, uint32 currentLevel, uint32 & gain)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_UPDATE_CRAFTING_SKILL, script->OnPlayerUpdateCraftingSkill(player, skill, currentLevel, gain));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerUpdateCraftingSkill(), and PLAYERHOOK_ON_UPDATE_CRAFTING_SKILL.
OnPlayerUpdateFaction()
void ScriptMgr::OnPlayerUpdateFaction (Player * player)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_UPDATE_FACTION, script->OnPlayerUpdateFaction(player));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerUpdateFaction(), and PLAYERHOOK_ON_UPDATE_FACTION.
OnPlayerUpdateFishingSkill()
bool ScriptMgr::OnPlayerUpdateFishingSkill (Player * player, int32 skill, int32 zone_skill, int32 chance, int32 roll)
{
    CALL_ENABLED_BOOLEAN_HOOKS(PlayerScript, PLAYERHOOK_ON_UPDATE_FISHING_SKILL, !script->OnPlayerUpdateFishingSkill(player, skill, zone_skill, chance, roll));
}
References CALL_ENABLED_BOOLEAN_HOOKS, PlayerScript::OnPlayerUpdateFishingSkill(), and PLAYERHOOK_ON_UPDATE_FISHING_SKILL.
OnPlayerUpdateGatheringSkill()
void ScriptMgr::OnPlayerUpdateGatheringSkill (Player * player, uint32 skillId, uint32 currentLevel, uint32 gray, uint32 green, uint32 yellow, uint32 & gain)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_UPDATE_GATHERING_SKILL, script->OnPlayerUpdateGatheringSkill(player, skillId, currentLevel, gray, green, yellow, gain));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerUpdateGatheringSkill(), and PLAYERHOOK_ON_UPDATE_GATHERING_SKILL.
OnPlayerUpdateSkill()
void ScriptMgr::OnPlayerUpdateSkill (Player * player, uint32 skillId, uint32 value, uint32 max, uint32 step, uint32 newValue)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_UPDATE_SKILL, script->OnPlayerUpdateSkill(player, skillId, value, max, step, newValue));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerUpdateSkill(), and PLAYERHOOK_ON_UPDATE_SKILL.
OnPlayerUpdateZone()
void ScriptMgr::OnPlayerUpdateZone (Player * player, uint32 newZone, uint32 newArea)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_UPDATE_ZONE, script->OnPlayerUpdateZone(player, newZone, newArea));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerUpdateZone(), and PLAYERHOOK_ON_UPDATE_ZONE.
OnPlayerVictimRewardAfter()
void ScriptMgr::OnPlayerVictimRewardAfter (Player * player, Player * victim, uint32 & killer_title, uint32 & victim_rank, float & honor_f)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_VICTIM_REWARD_AFTER, script->OnPlayerVictimRewardAfter(player, victim, killer_title, victim_rank, honor_f));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerVictimRewardAfter(), and PLAYERHOOK_ON_VICTIM_REWARD_AFTER.
OnPlayerVictimRewardBefore()
void ScriptMgr::OnPlayerVictimRewardBefore (Player * player, Player * victim, uint32 & killer_title, uint32 & victim_title)
{
    CALL_ENABLED_HOOKS(PlayerScript, PLAYERHOOK_ON_VICTIM_REWARD_BEFORE, script->OnPlayerVictimRewardBefore(player, victim, killer_title, victim_title));
}
References CALL_ENABLED_HOOKS, PlayerScript::OnPlayerVictimRewardBefore(), and PLAYERHOOK_ON_VICTIM_REWARD_BEFORE.
OnQuestAccept() [1/3]
bool ScriptMgr::OnQuestAccept (Player * player, Creature * creature, Quest const * quest)
{
    ASSERT(player);
    ASSERT(creature);
    ASSERT(quest);
    auto ret = IsValidBoolScript<AllCreatureScript>([&](AllCreatureScript* script)
    {
        return script->CanCreatureQuestAccept(player, creature, quest);
    });
    if (ret && *ret)
    {
        return true;
    }
    auto tempScript = ScriptRegistry<CreatureScript>::GetScriptById(creature->GetScriptId());
    ClearGossipMenuFor(player);
    return tempScript ? tempScript->OnQuestAccept(player, creature, quest) : false;
}
References ASSERT, AllCreatureScript::CanCreatureQuestAccept(), ClearGossipMenuFor(), ScriptRegistry< TScript >::GetScriptById(), and Creature::GetScriptId().
OnQuestAccept() [2/3]
bool ScriptMgr::OnQuestAccept (Player * player, GameObject * go, Quest const * quest)
{
    ASSERT(player);
    ASSERT(go);
    ASSERT(quest);
    auto ret = IsValidBoolScript<AllGameObjectScript>([&](AllGameObjectScript* script)
    {
        return script->CanGameObjectQuestAccept(player, go, quest);
    });
    if (ret && *ret)
    {
        return true;
    }
    auto tempScript = ScriptRegistry<GameObjectScript>::GetScriptById(go->GetScriptId());
    ClearGossipMenuFor(player);
    return tempScript ? tempScript->OnQuestAccept(player, go, quest) : false;
}
References ASSERT, AllGameObjectScript::CanGameObjectQuestAccept(), ClearGossipMenuFor(), ScriptRegistry< TScript >::GetScriptById(), and GameObject::GetScriptId().
OnQuestAccept() [3/3]
bool ScriptMgr::OnQuestAccept (Player * player, Item * item, Quest const * quest)
{
    ASSERT(player);
    ASSERT(item);
    ASSERT(quest);
    auto ret = IsValidBoolScript<AllItemScript>([&](AllItemScript* script)
    {
        return !script->CanItemQuestAccept(player, item, quest);
    });
    if (ret && *ret)
    {
        return false;
    }
    auto tempScript = ScriptRegistry<ItemScript>::GetScriptById(item->GetScriptId());
    ClearGossipMenuFor(player);
    return tempScript ? tempScript->OnQuestAccept(player, item, quest) : false;
}
References ASSERT, AllItemScript::CanItemQuestAccept(), ClearGossipMenuFor(), ScriptRegistry< TScript >::GetScriptById(), and Item::GetScriptId().
OnQuestComplete()
bool ScriptMgr::OnQuestComplete (Player * player, Creature * creature, Quest const * quest)
{
    ASSERT(player);
    ASSERT(creature);
    ASSERT(quest);
    auto tempScript = ScriptRegistry<CreatureScript>::GetScriptById(creature->GetScriptId());
    ClearGossipMenuFor(player);
    return tempScript ? tempScript->OnQuestComplete(player, creature, quest) : false;
}
References ASSERT, ClearGossipMenuFor(), ScriptRegistry< TScript >::GetScriptById(), and Creature::GetScriptId().
OnQuestReward() [1/2]
bool ScriptMgr::OnQuestReward (Player * player, Creature * creature, Quest const * quest, uint32 opt)
{
    ASSERT(player);
    ASSERT(creature);
    ASSERT(quest);
    auto ret = IsValidBoolScript<AllCreatureScript>([&](AllCreatureScript* script)
    {
        return script->CanCreatureQuestReward(player, creature, quest, opt);
    });
    if (ret && *ret)
    {
        return false;
    }
    auto tempScript = ScriptRegistry<CreatureScript>::GetScriptById(creature->GetScriptId());
    ClearGossipMenuFor(player);
    return tempScript ? tempScript->OnQuestReward(player, creature, quest, opt) : false;
}
References ASSERT, AllCreatureScript::CanCreatureQuestReward(), ClearGossipMenuFor(), ScriptRegistry< TScript >::GetScriptById(), and Creature::GetScriptId().
OnQuestReward() [2/2]
bool ScriptMgr::OnQuestReward (Player * player, GameObject * go, Quest const * quest, uint32 opt)
{
    ASSERT(player);
    ASSERT(go);
    ASSERT(quest);
    auto ret = IsValidBoolScript<AllGameObjectScript>([&](AllGameObjectScript* script)
    {
        return script->CanGameObjectQuestReward(player, go, quest, opt);
    });
    if (ret && *ret)
    {
        return false;
    }
    auto tempScript = ScriptRegistry<GameObjectScript>::GetScriptById(go->GetScriptId());
    ClearGossipMenuFor(player);
    return tempScript ? tempScript->OnQuestReward(player, go, quest, opt) : false;
}
References ASSERT, AllGameObjectScript::CanGameObjectQuestReward(), ClearGossipMenuFor(), ScriptRegistry< TScript >::GetScriptById(), and GameObject::GetScriptId().
OnQuestSelect()
bool ScriptMgr::OnQuestSelect (Player * player, Creature * creature, Quest const * quest)
{
    ASSERT(player);
    ASSERT(creature);
    ASSERT(quest);
    auto tempScript = ScriptRegistry<CreatureScript>::GetScriptById(creature->GetScriptId());
    ClearGossipMenuFor(player);
    return tempScript ? tempScript->OnQuestSelect(player, creature, quest) : false;
}
References ASSERT, ClearGossipMenuFor(), ScriptRegistry< TScript >::GetScriptById(), and Creature::GetScriptId().
OnQueueUpdate()
void ScriptMgr::OnQueueUpdate (BattlegroundQueue * queue, uint32 diff, BattlegroundTypeId bgTypeId, BattlegroundBracketId bracket_id, uint8 arenaType, bool isRated, uint32 arenaRating)
{
    CALL_ENABLED_HOOKS(AllBattlegroundScript, ALLBATTLEGROUNDHOOK_ON_QUEUE_UPDATE, script->OnQueueUpdate(queue, diff, bgTypeId, bracket_id, arenaType, isRated, arenaRating));
}
References ALLBATTLEGROUNDHOOK_ON_QUEUE_UPDATE, CALL_ENABLED_HOOKS, and AllBattlegroundScript::OnQueueUpdate().
OnQueueUpdateValidity()
bool ScriptMgr::OnQueueUpdateValidity (BattlegroundQueue * queue, uint32 diff, BattlegroundTypeId bgTypeId, BattlegroundBracketId bracket_id, uint8 arenaType, bool isRated, uint32 arenaRating)
{
    CALL_ENABLED_BOOLEAN_HOOKS(AllBattlegroundScript, ALLBATTLEGROUNDHOOK_ON_QUEUE_UPDATE_VALIDITY, !script->OnQueueUpdateValidity(queue, diff, bgTypeId, bracket_id, arenaType, isRated, arenaRating));
}
References ALLBATTLEGROUNDHOOK_ON_QUEUE_UPDATE_VALIDITY, CALL_ENABLED_BOOLEAN_HOOKS, and AllBattlegroundScript::OnQueueUpdateValidity().
OnRelocate()
void ScriptMgr::OnRelocate (Transport * transport, uint32 waypointId, uint32 mapId, float x, float y, float z)
{
    if (auto tempScript = ScriptRegistry<TransportScript>::GetScriptById(transport->GetScriptId()))
    {
        tempScript->OnRelocate(transport, waypointId, mapId, x, y, z);
    }
}
References GameObject::GetScriptId().
OnRemoveAuraScaleTargets()
void ScriptMgr::OnRemoveAuraScaleTargets (Spell * spell, TargetInfo & targetInfo, uint8 auraScaleMask, bool & needErase)
{
    CALL_ENABLED_HOOKS(AllSpellScript, ALLSPELLHOOK_ON_REMOVE_AURA_SCALE_TARGETS, script->OnRemoveAuraScaleTargets(spell, targetInfo, auraScaleMask, needErase));
}
References ALLSPELLHOOK_ON_REMOVE_AURA_SCALE_TARGETS, CALL_ENABLED_HOOKS, and AllSpellScript::OnRemoveAuraScaleTargets().
OnRemovePassenger() [1/2]
void ScriptMgr::OnRemovePassenger (Transport * transport, Player * player)
{
    ASSERT(transport);
    ASSERT(player);
    if (auto tempScript = ScriptRegistry<TransportScript>::GetScriptById(transport->GetScriptId()))
    {
        tempScript->OnRemovePassenger(transport, player);
    }
}
References ASSERT, and GameObject::GetScriptId().
OnRemovePassenger() [2/2]
void ScriptMgr::OnRemovePassenger (Vehicle * veh, Unit * passenger)
{
    ASSERT(veh);
    ASSERT(veh->GetBase()->IsCreature());
    ASSERT(passenger);
    if (auto tempScript = ScriptRegistry<VehicleScript>::GetScriptById(veh->GetBase()->ToCreature()->GetScriptId()))
    {
        tempScript->OnRemovePassenger(veh, passenger);
    }
}
References ASSERT, Vehicle::GetBase(), Creature::GetScriptId(), Object::IsCreature(), and Object::ToCreature().
OnReset()
void ScriptMgr::OnReset (Vehicle * veh)
{
    ASSERT(veh);
    ASSERT(veh->GetBase()->IsCreature());
    if (auto tempScript = ScriptRegistry<VehicleScript>::GetScriptById(veh->GetBase()->ToCreature()->GetScriptId()))
    {
        tempScript->OnReset(veh);
    }
}
References ASSERT, Vehicle::GetBase(), Creature::GetScriptId(), Object::IsCreature(), and Object::ToCreature().
OnScaleAuraUnitAdd()
void ScriptMgr::OnScaleAuraUnitAdd (Spell * spell, Unit * target, uint32 effectMask, bool checkIfValid, bool implicit, uint8 auraScaleMask, TargetInfo & targetInfo)
{
    CALL_ENABLED_HOOKS(AllSpellScript, ALLSPELLHOOK_ON_SCALE_AURA_UNIT_ADD, script->OnScaleAuraUnitAdd(spell, target, effectMask, checkIfValid, implicit, auraScaleMask, targetInfo));
}
References ALLSPELLHOOK_ON_SCALE_AURA_UNIT_ADD, CALL_ENABLED_HOOKS, and AllSpellScript::OnScaleAuraUnitAdd().
OnSetArenaMaxPlayersPerTeam()
void ScriptMgr::OnSetArenaMaxPlayersPerTeam (const uint8 arenaType, uint32 & maxPlayerPerTeam)
{
    CALL_ENABLED_HOOKS(ArenaTeamScript, ARENATEAMHOOK_ON_SET_ARENA_MAX_PLAYERS_PER_TEAM, script->OnSetArenaMaxPlayersPerTeam(arenaType, maxPlayerPerTeam));
}
References ARENATEAMHOOK_ON_SET_ARENA_MAX_PLAYERS_PER_TEAM, CALL_ENABLED_HOOKS, and ArenaTeamScript::OnSetArenaMaxPlayersPerTeam().
OnShutdown()
void ScriptMgr::OnShutdown ()
{
    CALL_ENABLED_HOOKS(WorldScript, WORLDHOOK_ON_SHUTDOWN, script->OnShutdown());
}
References CALL_ENABLED_HOOKS, WorldScript::OnShutdown(), and WORLDHOOK_ON_SHUTDOWN.
OnShutdownCancel()
void ScriptMgr::OnShutdownCancel ()
{
    CALL_ENABLED_HOOKS(WorldScript, WORLDHOOK_ON_SHUTDOWN_CANCEL, script->OnShutdownCancel());
}
References CALL_ENABLED_HOOKS, WorldScript::OnShutdownCancel(), and WORLDHOOK_ON_SHUTDOWN_CANCEL.
OnShutdownInitiate()
void ScriptMgr::OnShutdownInitiate (ShutdownExitCode code, ShutdownMask mask)
{
    CALL_ENABLED_HOOKS(WorldScript, WORLDHOOK_ON_SHUTDOWN_INITIATE, script->OnShutdownInitiate(code, mask));
}
References CALL_ENABLED_HOOKS, WorldScript::OnShutdownInitiate(), and WORLDHOOK_ON_SHUTDOWN_INITIATE.
OnSocketClose()
void ScriptMgr::OnSocketClose (std::shared_ptr< WorldSocket > socket)
{
    ASSERT(socket);
    CALL_ENABLED_HOOKS(ServerScript, SERVERHOOK_ON_SOCKET_CLOSE, script->OnSocketClose(socket));
}
References ASSERT, CALL_ENABLED_HOOKS, ServerScript::OnSocketClose(), and SERVERHOOK_ON_SOCKET_CLOSE.
OnSocketOpen()
void ScriptMgr::OnSocketOpen (std::shared_ptr< WorldSocket > socket)
{
    ASSERT(socket);
    CALL_ENABLED_HOOKS(ServerScript, SERVERHOOK_ON_SOCKET_OPEN, script->OnSocketOpen(socket));
}
References ASSERT, CALL_ENABLED_HOOKS, ServerScript::OnSocketOpen(), and SERVERHOOK_ON_SOCKET_OPEN.
OnSpellCast()
void ScriptMgr::OnSpellCast (Spell * spell, Unit * caster, SpellInfo const * spellInfo, bool skipCheck)
{
    CALL_ENABLED_HOOKS(AllSpellScript, ALLSPELLHOOK_ON_CAST, script->OnSpellCast(spell, caster, spellInfo, skipCheck));
}
References ALLSPELLHOOK_ON_CAST, CALL_ENABLED_HOOKS, and AllSpellScript::OnSpellCast().
OnSpellCastCancel()
void ScriptMgr::OnSpellCastCancel (Spell * spell, Unit * caster, SpellInfo const * spellInfo, bool bySelf)
{
    CALL_ENABLED_HOOKS(AllSpellScript, ALLSPELLHOOK_ON_CAST_CANCEL, script->OnSpellCastCancel(spell, caster, spellInfo, bySelf));
}
References ALLSPELLHOOK_ON_CAST_CANCEL, CALL_ENABLED_HOOKS, and AllSpellScript::OnSpellCastCancel().
OnSpellCheckCast()
void ScriptMgr::OnSpellCheckCast (Spell * spell, bool strict, SpellCastResult & res)
{
    CALL_ENABLED_HOOKS(AllSpellScript, ALLSPELLHOOK_ON_SPELL_CHECK_CAST, script->OnSpellCheckCast(spell, strict, res));
}
References ALLSPELLHOOK_ON_SPELL_CHECK_CAST, CALL_ENABLED_HOOKS, and AllSpellScript::OnSpellCheckCast().
OnSpellHealingBonusTakenNegativeModifiers()
bool ScriptMgr::OnSpellHealingBonusTakenNegativeModifiers (Unit const * target, Unit const * caster, SpellInfo const * spellInfo, float & val)
{
    CALL_ENABLED_BOOLEAN_HOOKS_WITH_DEFAULT_FALSE(GlobalScript, GLOBALHOOK_ON_SPELL_HEALING_BONUS_TAKEN_NEGATIVE_MODIFIERS, script->OnSpellHealingBonusTakenNegativeModifiers(target, caster, spellInfo, val));
}
References CALL_ENABLED_BOOLEAN_HOOKS_WITH_DEFAULT_FALSE, GLOBALHOOK_ON_SPELL_HEALING_BONUS_TAKEN_NEGATIVE_MODIFIERS, and GlobalScript::OnSpellHealingBonusTakenNegativeModifiers().
OnSpellPrepare()
void ScriptMgr::OnSpellPrepare (Spell * spell, Unit * caster, SpellInfo const * spellInfo)
{
    CALL_ENABLED_HOOKS(AllSpellScript, ALLSPELLHOOK_ON_PREPARE, script->OnSpellPrepare(spell, caster, spellInfo));
}
References ALLSPELLHOOK_ON_PREPARE, CALL_ENABLED_HOOKS, and AllSpellScript::OnSpellPrepare().
OnStartup()
void ScriptMgr::OnStartup ()
{
    CALL_ENABLED_HOOKS(WorldScript, WORLDHOOK_ON_STARTUP, script->OnStartup());
}
References CALL_ENABLED_HOOKS, WorldScript::OnStartup(), and WORLDHOOK_ON_STARTUP.
OnTicketClose()
void ScriptMgr::OnTicketClose (GmTicket * ticket)
{
    CALL_ENABLED_HOOKS(TicketScript, TICKETHOOK_ON_TICKET_CLOSE, script->OnTicketClose(ticket));
}
References CALL_ENABLED_HOOKS, TicketScript::OnTicketClose(), and TICKETHOOK_ON_TICKET_CLOSE.
OnTicketCreate()
void ScriptMgr::OnTicketCreate (GmTicket * ticket)
{
    CALL_ENABLED_HOOKS(TicketScript, TICKETHOOK_ON_TICKET_CREATE, script->OnTicketCreate(ticket));
}
References CALL_ENABLED_HOOKS, TicketScript::OnTicketCreate(), and TICKETHOOK_ON_TICKET_CREATE.
OnTicketResolve()
void ScriptMgr::OnTicketResolve (GmTicket * ticket)
{
    CALL_ENABLED_HOOKS(TicketScript, TICKETHOOK_ON_TICKET_RESOLVE, script->OnTicketResolve(ticket));
}
References CALL_ENABLED_HOOKS, TicketScript::OnTicketResolve(), and TICKETHOOK_ON_TICKET_RESOLVE.
OnTicketStatusUpdate()
void ScriptMgr::OnTicketStatusUpdate (GmTicket * ticket)
{
    CALL_ENABLED_HOOKS(TicketScript, TICKETHOOK_ON_TICKET_STATUS_UPDATE, script->OnTicketStatusUpdate(ticket));
}
References CALL_ENABLED_HOOKS, TicketScript::OnTicketStatusUpdate(), and TICKETHOOK_ON_TICKET_STATUS_UPDATE.
OnTicketUpdateLastChange()
void ScriptMgr::OnTicketUpdateLastChange (GmTicket * ticket)
{
    CALL_ENABLED_HOOKS(TicketScript, TICKETHOOK_ON_TICKET_UPDATE_LAST_CHANGE, script->OnTicketUpdateLastChange(ticket));
}
References CALL_ENABLED_HOOKS, TicketScript::OnTicketUpdateLastChange(), and TICKETHOOK_ON_TICKET_UPDATE_LAST_CHANGE.
OnTransportUpdate()
void ScriptMgr::OnTransportUpdate (Transport * transport, uint32 diff)
{
    ASSERT(transport);
    if (auto tempScript = ScriptRegistry<TransportScript>::GetScriptById(transport->GetScriptId()))
    {
        tempScript->OnUpdate(transport, diff);
    }
}
References ASSERT, and GameObject::GetScriptId().
OnTryExecuteCommand()
bool ScriptMgr::OnTryExecuteCommand (ChatHandler & handler, std::string_view cmdStr)
{
    CALL_ENABLED_BOOLEAN_HOOKS(AllCommandScript, ALLCOMMANDHOOK_ON_TRY_EXECUTE_COMMAND, !script->OnTryExecuteCommand(handler, cmdStr));
}
References ALLCOMMANDHOOK_ON_TRY_EXECUTE_COMMAND, CALL_ENABLED_BOOLEAN_HOOKS, and AllCommandScript::OnTryExecuteCommand().
OnUninstall()
void ScriptMgr::OnUninstall (Vehicle * veh)
{
    ASSERT(veh);
    ASSERT(veh->GetBase()->IsCreature());
    if (auto tempScript = ScriptRegistry<VehicleScript>::GetScriptById(veh->GetBase()->ToCreature()->GetScriptId()))
    {
        tempScript->OnUninstall(veh);
    }
}
References ASSERT, Vehicle::GetBase(), Creature::GetScriptId(), Object::IsCreature(), and Object::ToCreature().
OnUnitDeath()
void ScriptMgr::OnUnitDeath (Unit * unit, Unit * killer)
{
    CALL_ENABLED_HOOKS(UnitScript, UNITHOOK_ON_UNIT_DEATH, script->OnUnitDeath(unit, killer));
}
References CALL_ENABLED_HOOKS, UnitScript::OnUnitDeath(), and UNITHOOK_ON_UNIT_DEATH.
OnUnitEnterCombat()
void ScriptMgr::OnUnitEnterCombat (Unit * unit, Unit * victim)
{
    CALL_ENABLED_HOOKS(UnitScript, UNITHOOK_ON_UNIT_ENTER_COMBAT, script->OnUnitEnterCombat(unit, victim));
}
References CALL_ENABLED_HOOKS, UnitScript::OnUnitEnterCombat(), and UNITHOOK_ON_UNIT_ENTER_COMBAT.
OnUnitEnterEvadeMode()
void ScriptMgr::OnUnitEnterEvadeMode (Unit * unit, uint8 why)
{
    CALL_ENABLED_HOOKS(UnitScript, UNITHOOK_ON_UNIT_ENTER_EVADE_MODE, script->OnUnitEnterEvadeMode(unit, evadeReason));
}
References CALL_ENABLED_HOOKS, UnitScript::OnUnitEnterEvadeMode(), and UNITHOOK_ON_UNIT_ENTER_EVADE_MODE.
OnUnitSetShapeshiftForm()
void ScriptMgr::OnUnitSetShapeshiftForm (Unit * unit, uint8 form)
{
    CALL_ENABLED_HOOKS(UnitScript, UNITHOOK_ON_UNIT_SET_SHAPESHIFT_FORM, script->OnUnitSetShapeshiftForm(unit, form));
}
References CALL_ENABLED_HOOKS, UnitScript::OnUnitSetShapeshiftForm(), and UNITHOOK_ON_UNIT_SET_SHAPESHIFT_FORM.
OnUnitUpdate()
void ScriptMgr::OnUnitUpdate (Unit * unit, uint32 diff)
{
    CALL_ENABLED_HOOKS(UnitScript, UNITHOOK_ON_UNIT_UPDATE, script->OnUnitUpdate(unit, diff));
}
References CALL_ENABLED_HOOKS, UnitScript::OnUnitUpdate(), and UNITHOOK_ON_UNIT_UPDATE.
OnUnloadGridMap()
void ScriptMgr::OnUnloadGridMap (Map * map, GridTerrainData * gmap, uint32 gx, uint32 gy)
{
    ASSERT(map);
    ASSERT(gmap);
    ForeachMaps<WorldMapScript>(map,
    [&](WorldMapScript* script)
    {
        script->OnUnloadGridMap(map, gmap, gx, gy);
    });
    ForeachMaps<InstanceMapScript>(map,
    [&](InstanceMapScript* script)
    {
        script->OnUnloadGridMap((InstanceMap*)map, gmap, gx, gy);
    });
    ForeachMaps<BattlegroundMapScript>(map,
    [&](BattlegroundMapScript* script)
    {
        script->OnUnloadGridMap((BattlegroundMap*)map, gmap, gx, gy);
    });
}
References ASSERT, and MapScript< TMap >::OnUnloadGridMap().
OnWeatherChange()
void ScriptMgr::OnWeatherChange (Weather * weather, WeatherState state, float grade)
{
    ASSERT(weather);
    ExecuteScript<ElunaScript>([&](ElunaScript* script)
    {
        script->OnWeatherChange(weather, state, grade);
    });
    if (auto tempScript = ScriptRegistry<WeatherScript>::GetScriptById(weather->GetScriptId()))
    {
        tempScript->OnChange(weather, state, grade);
    }
}
References ASSERT, Weather::GetScriptId(), and ElunaScript::OnWeatherChange().
OnWeatherUpdate()
void ScriptMgr::OnWeatherUpdate (Weather * weather, uint32 diff)
{
    ASSERT(weather);
    if (auto tempScript = ScriptRegistry<WeatherScript>::GetScriptById(weather->GetScriptId()))
    {
        tempScript->OnUpdate(weather, diff);
    }
}
References ASSERT, and Weather::GetScriptId().
OnWorldObjectCreate()
void ScriptMgr::OnWorldObjectCreate (WorldObject * object)
{
    ASSERT(object);
    CALL_ENABLED_HOOKS(WorldObjectScript, WORLDOBJECTHOOK_ON_WORLD_OBJECT_CREATE, script->OnWorldObjectCreate(object));
}
References ASSERT, CALL_ENABLED_HOOKS, WorldObjectScript::OnWorldObjectCreate(), and WORLDOBJECTHOOK_ON_WORLD_OBJECT_CREATE.
OnWorldObjectDestroy()
void ScriptMgr::OnWorldObjectDestroy (WorldObject * object)
{
    ASSERT(object);
    CALL_ENABLED_HOOKS(WorldObjectScript, WORLDOBJECTHOOK_ON_WORLD_OBJECT_DESTROY, script->OnWorldObjectDestroy(object));
}
References ASSERT, CALL_ENABLED_HOOKS, WorldObjectScript::OnWorldObjectDestroy(), and WORLDOBJECTHOOK_ON_WORLD_OBJECT_DESTROY.
OnWorldObjectResetMap()
void ScriptMgr::OnWorldObjectResetMap (WorldObject * object)
{
    ASSERT(object);
    CALL_ENABLED_HOOKS(WorldObjectScript, WORLDOBJECTHOOK_ON_WORLD_OBJECT_RESET_MAP, script->OnWorldObjectResetMap(object));
}
References ASSERT, CALL_ENABLED_HOOKS, WorldObjectScript::OnWorldObjectResetMap(), and WORLDOBJECTHOOK_ON_WORLD_OBJECT_RESET_MAP.
OnWorldObjectSetMap()
void ScriptMgr::OnWorldObjectSetMap (WorldObject * object, Map * map)
{
    ASSERT(object);
    CALL_ENABLED_HOOKS(WorldObjectScript, WORLDOBJECTHOOK_ON_WORLD_OBJECT_SET_MAP, script->OnWorldObjectSetMap(object, map));
}
References ASSERT, CALL_ENABLED_HOOKS, WorldObjectScript::OnWorldObjectSetMap(), and WORLDOBJECTHOOK_ON_WORLD_OBJECT_SET_MAP.
OnWorldObjectUpdate()
void ScriptMgr::OnWorldObjectUpdate (WorldObject * object, uint32 diff)
{
    ASSERT(object);
    CALL_ENABLED_HOOKS(WorldObjectScript, WORLDOBJECTHOOK_ON_WORLD_OBJECT_UPDATE, script->OnWorldObjectUpdate(object, diff));
}
References ASSERT, CALL_ENABLED_HOOKS, WorldObjectScript::OnWorldObjectUpdate(), and WORLDOBJECTHOOK_ON_WORLD_OBJECT_UPDATE.
OnWorldUpdate()
void ScriptMgr::OnWorldUpdate (uint32 diff)
{
    CALL_ENABLED_HOOKS(WorldScript, WORLDHOOK_ON_UPDATE, script->OnUpdate(diff));
}
References CALL_ENABLED_HOOKS, WorldScript::OnUpdate(), and WORLDHOOK_ON_UPDATE.
OnZeroDifferenceCalculation()
void ScriptMgr::OnZeroDifferenceCalculation (uint8 & diff, uint8 playerLevel)
{
    CALL_ENABLED_HOOKS(FormulaScript, FORMULAHOOK_ON_ZERO_DIFFERENCE_CALCULATION, script->OnZeroDifferenceCalculation(diff, playerLevel));
}
References CALL_ENABLED_HOOKS, FORMULAHOOK_ON_ZERO_DIFFERENCE_CALCULATION, and FormulaScript::OnZeroDifferenceCalculation().
ScriptsVersion()
std::string_view ScriptMgr::ScriptsVersion () const inline
{ return "Integrated Azeroth Scripts"; }
SetModulesLoader()
void ScriptMgr::SetModulesLoader (ModulesLoaderCallbackType script_loader_callback) inline
Sets the modules loader callback which is invoked to load modules (Workaround for circular dependency game <-> modules)
    {
        _modules_loader_callback = script_loader_callback;
    }
References _modules_loader_callback.
SetRealmCompleted()
void ScriptMgr::SetRealmCompleted (AchievementEntry const * achievement)
{
    CALL_ENABLED_HOOKS(AchievementScript, ACHIEVEMENTHOOK_SET_REALM_COMPLETED, script->SetRealmCompleted(achievement));
}
References ACHIEVEMENTHOOK_SET_REALM_COMPLETED, CALL_ENABLED_HOOKS, and AchievementScript::SetRealmCompleted().
SetScriptLoader()
void ScriptMgr::SetScriptLoader (ScriptLoaderCallbackType script_loader_callback) inline
Sets the script loader callback which is invoked to load scripts (Workaround for circular dependency game <-> scripts)
    {
        _script_loader_callback = script_loader_callback;
    }
References _script_loader_callback.
ShouldTrackValuesUpdatePosByIndex()
bool ScriptMgr::ShouldTrackValuesUpdatePosByIndex (Unit const * unit, uint8 updateType, uint16 index)
{
    CALL_ENABLED_BOOLEAN_HOOKS_WITH_DEFAULT_FALSE(UnitScript, UNITHOOK_SHOULD_TRACK_VALUES_UPDATE_POS_BY_INDEX, script->ShouldTrackValuesUpdatePosByIndex(unit, updateType, index));
}
References CALL_ENABLED_BOOLEAN_HOOKS_WITH_DEFAULT_FALSE, UnitScript::ShouldTrackValuesUpdatePosByIndex(), and UNITHOOK_SHOULD_TRACK_VALUES_UPDATE_POS_BY_INDEX.
Unload()
void ScriptMgr::Unload ()
{
    SCR_CLEAR<AccountScript>();
    SCR_CLEAR<AchievementCriteriaScript>();
    SCR_CLEAR<AchievementScript>();
    SCR_CLEAR<AllCreatureScript>();
    SCR_CLEAR<AllGameObjectScript>();
    SCR_CLEAR<AllItemScript>();
    SCR_CLEAR<AllMapScript>();
    SCR_CLEAR<AreaTriggerScript>();
    SCR_CLEAR<ArenaScript>();
    SCR_CLEAR<ArenaTeamScript>();
    SCR_CLEAR<AuctionHouseScript>();
    SCR_CLEAR<BGScript>();
    SCR_CLEAR<BattlegroundMapScript>();
    SCR_CLEAR<BattlegroundScript>();
    SCR_CLEAR<CommandSC>();
    SCR_CLEAR<CommandScript>();
    SCR_CLEAR<ConditionScript>();
    SCR_CLEAR<CreatureScript>();
    SCR_CLEAR<DatabaseScript>();
    SCR_CLEAR<DynamicObjectScript>();
    SCR_CLEAR<ElunaScript>();
    SCR_CLEAR<FormulaScript>();
    SCR_CLEAR<GameEventScript>();
    SCR_CLEAR<GameObjectScript>();
    SCR_CLEAR<GlobalScript>();
    SCR_CLEAR<GroupScript>();
    SCR_CLEAR<GuildScript>();
    SCR_CLEAR<InstanceMapScript>();
    SCR_CLEAR<ItemScript>();
    SCR_CLEAR<LootScript>();
    SCR_CLEAR<MailScript>();
    SCR_CLEAR<MiscScript>();
    SCR_CLEAR<MovementHandlerScript>();
    SCR_CLEAR<OutdoorPvPScript>();
    SCR_CLEAR<PetScript>();
    SCR_CLEAR<PlayerScript>();
    SCR_CLEAR<ServerScript>();
    SCR_CLEAR<SpellSC>();
    SCR_CLEAR<SpellScriptLoader>();
    SCR_CLEAR<TicketScript>();
    SCR_CLEAR<TransportScript>();
    SCR_CLEAR<UnitScript>();
    SCR_CLEAR<VehicleScript>();
    SCR_CLEAR<WeatherScript>();
    SCR_CLEAR<WorldMapScript>();
    SCR_CLEAR<WorldObjectScript>();
    SCR_CLEAR<WorldScript>();
    delete[] SpellSummary;
}
References SpellSummary.
ValidateSpellAtCastSpell()
void ScriptMgr::ValidateSpellAtCastSpell (Player * player, uint32 & oldSpellId, uint32 & spellId, uint8 & castCount, uint8 & castFlags)
{
    CALL_ENABLED_HOOKS(MiscScript, MISCHOOK_VALIDATE_SPELL_AT_CAST_SPELL, script->ValidateSpellAtCastSpell(player, oldSpellId, spellId, castCount, castFlags));
}
References CALL_ENABLED_HOOKS, MISCHOOK_VALIDATE_SPELL_AT_CAST_SPELL, and MiscScript::ValidateSpellAtCastSpell().
ValidateSpellAtCastSpellResult()
void ScriptMgr::ValidateSpellAtCastSpellResult (Player * player, Unit * mover, Spell * spell, uint32 oldSpellId, uint32 spellId)
{
    CALL_ENABLED_HOOKS(MiscScript, MISCHOOK_VALIDATE_SPELL_AT_CAST_SPELL_RESULT, script->ValidateSpellAtCastSpellResult(player, mover, spell, oldSpellId, spellId));
}
References CALL_ENABLED_HOOKS, MISCHOOK_VALIDATE_SPELL_AT_CAST_SPELL_RESULT, and MiscScript::ValidateSpellAtCastSpellResult().
~ScriptMgr()
ScriptMgr::~ScriptMgr () private virtual
{ }
Friends And Related Symbol Documentation
ScriptObject
friend class ScriptObject friend
Member Data Documentation
_modules_loader_callback
ModulesLoaderCallbackType ScriptMgr::_modules_loader_callback private
Referenced by Initialize(), and SetModulesLoader().
_scheduledScripts
std::atomic<long> ScriptMgr::_scheduledScripts private
Referenced by DecreaseScheduledScriptCount(), DecreaseScheduledScriptCount(), IncreaseScheduledScriptsCount(), and IsScriptScheduled().
_script_loader_callback
ScriptLoaderCallbackType ScriptMgr::_script_loader_callback private
Referenced by Initialize(), and SetScriptLoader().
_scriptCount
uint32 ScriptMgr::_scriptCount private
Referenced by DecreaseScriptCount(), GetScriptCount(), and IncreaseScriptCount().
The documentation for this class was generated from the following files:
azerothcore-wotlk/src/server/game/Scripting/ScriptMgr.h
azerothcore-wotlk/src/server/game/Scripting/ScriptDefines/AccountScript.cpp
azerothcore-wotlk/src/server/game/Scripting/ScriptDefines/AchievementCriteriaScript.cpp
azerothcore-wotlk/src/server/game/Scripting/ScriptDefines/AchievementScript.cpp
azerothcore-wotlk/src/server/game/Scripting/ScriptDefines/AllBattlegroundScript.cpp
azerothcore-wotlk/src/server/game/Scripting/ScriptDefines/AllCommandScript.cpp
azerothcore-wotlk/src/server/game/Scripting/ScriptDefines/AllCreatureScript.cpp
azerothcore-wotlk/src/server/game/Scripting/ScriptDefines/AllGameObjectScript.cpp
azerothcore-wotlk/src/server/game/Scripting/ScriptDefines/AllItemScript.cpp
azerothcore-wotlk/src/server/game/Scripting/ScriptDefines/AllMapScript.cpp
azerothcore-wotlk/src/server/game/Scripting/ScriptDefines/AllSpellScript.cpp
azerothcore-wotlk/src/server/game/Scripting/ScriptDefines/AreaTriggerScript.cpp
azerothcore-wotlk/src/server/game/Scripting/ScriptDefines/ArenaScript.cpp
azerothcore-wotlk/src/server/game/Scripting/ScriptDefines/ArenaTeamScript.cpp
azerothcore-wotlk/src/server/game/Scripting/ScriptDefines/AuctionHouseScript.cpp
azerothcore-wotlk/src/server/game/Scripting/ScriptDefines/BattlegroundScript.cpp
azerothcore-wotlk/src/server/game/Scripting/ScriptDefines/CommandScript.cpp
azerothcore-wotlk/src/server/game/Scripting/ScriptDefines/ConditionScript.cpp
azerothcore-wotlk/src/server/game/Scripting/ScriptDefines/CreatureScript.cpp
azerothcore-wotlk/src/server/game/Scripting/ScriptDefines/DatabaseScript.cpp
azerothcore-wotlk/src/server/game/Scripting/ScriptDefines/DynamicObjectScript.cpp
azerothcore-wotlk/src/server/game/Scripting/ScriptDefines/FormulaScript.cpp
azerothcore-wotlk/src/server/game/Scripting/ScriptDefines/GameEventScript.cpp
azerothcore-wotlk/src/server/game/Scripting/ScriptDefines/GameObjectScript.cpp
azerothcore-wotlk/src/server/game/Scripting/ScriptDefines/GlobalScript.cpp
azerothcore-wotlk/src/server/game/Scripting/ScriptDefines/GroupScript.cpp
azerothcore-wotlk/src/server/game/Scripting/ScriptDefines/GuildScript.cpp
azerothcore-wotlk/src/server/game/Scripting/ScriptDefines/InstanceMapScript.cpp
azerothcore-wotlk/src/server/game/Scripting/ScriptDefines/LootScript.cpp
azerothcore-wotlk/src/server/game/Scripting/ScriptDefines/MailScript.cpp
azerothcore-wotlk/src/server/game/Scripting/ScriptDefines/MiscScript.cpp
azerothcore-wotlk/src/server/game/Scripting/ScriptDefines/MovementHandlerScript.cpp
azerothcore-wotlk/src/server/game/Scripting/ScriptDefines/OutdoorPvPScript.cpp
azerothcore-wotlk/src/server/game/Scripting/ScriptDefines/PetScript.cpp
azerothcore-wotlk/src/server/game/Scripting/ScriptDefines/PlayerScript.cpp
azerothcore-wotlk/src/server/game/Scripting/ScriptDefines/ServerScript.cpp
azerothcore-wotlk/src/server/game/Scripting/ScriptDefines/SpellScriptLoader.cpp
azerothcore-wotlk/src/server/game/Scripting/ScriptDefines/TicketScript.cpp
azerothcore-wotlk/src/server/game/Scripting/ScriptDefines/TransportScript.cpp
azerothcore-wotlk/src/server/game/Scripting/ScriptDefines/UnitScript.cpp
azerothcore-wotlk/src/server/game/Scripting/ScriptDefines/VehicleScript.cpp
azerothcore-wotlk/src/server/game/Scripting/ScriptDefines/WeatherScript.cpp
azerothcore-wotlk/src/server/game/Scripting/ScriptDefines/WorldObjectScript.cpp
azerothcore-wotlk/src/server/game/Scripting/ScriptDefines/WorldScript.cpp
azerothcore-wotlk/src/server/game/Scripting/ScriptMgr.cpp