AzerothCore Doxygen
ArenaTeamFilterTest.cpp File Reference
#include "Define.h"
#include "gmock/gmock.h"
#include "gtest/gtest.h"
#include "ArenaTeamFilter.h"
#include "ArenaTeamMgr.h"
#include "ArenaTeam.h"
#include <memory>
#include "WorldMock.h"
Classes
class ArenaTeamTest
class ArenaTeamFilterTest
Functions
ArenaTeam * ArenaTeamWithType (uint8 type)
TEST_F (ArenaTeamFilterTest, AllTeamsFilter)
TEST_F (ArenaTeamFilterTest, FilterBySpecificTypes)
TEST_F (ArenaTeamFilterTest, FabricCreatesFilterByInput)
Function Documentation
ArenaTeamWithType()
ArenaTeam * ArenaTeamWithType (uint8 type)
{
    ArenaTeamTest* team = new ArenaTeamTest();
    team->SetType(type);
    return team;
}
References ArenaTeamTest::SetType().
Referenced by ArenaTeamFilterTest::SetUp().
TEST_F() [1/3]
TEST_F (ArenaTeamFilterTest , AllTeamsFilter)
{
    ArenaTeamFilterAllTeams filter;
    ArenaTeamMgr::ArenaTeamContainer result = filter.Filter(arenaTeams);
    EXPECT_EQ(result.size(), arenaTeams.size());
    EXPECT_EQ(result[1], team1);
    EXPECT_EQ(result[2], team2);
    EXPECT_EQ(result[3], team3);
}
References ArenaTeamFilterAllTeams::Filter().
TEST_F() [2/3]
TEST_F (ArenaTeamFilterTest , FabricCreatesFilterByInput)
{
    ArenaTeamFilterFactoryByUserInput fabric;
    // Test for "all" input
    auto allTeamsFilter = fabric.CreateFilterByUserInput("all");
    ArenaTeamMgr::ArenaTeamContainer allTeamsResult = allTeamsFilter->Filter(arenaTeams);
    EXPECT_EQ(allTeamsResult.size(), arenaTeams.size()); // All teams should pass
    // Test for "2,3" input
    auto specificTypesFilter = fabric.CreateFilterByUserInput("2,3");
    ArenaTeamMgr::ArenaTeamContainer filteredResult = specificTypesFilter->Filter(arenaTeams);
    EXPECT_EQ(filteredResult.size(), 2);  // Only 2v2 and 3v3 teams should pass
    EXPECT_EQ(filteredResult[1], team1);  // 2v2
    EXPECT_EQ(filteredResult[2], team2);  // 3v3
}
References ArenaTeamFilterFactoryByUserInput::CreateFilterByUserInput().
TEST_F() [3/3]
TEST_F (ArenaTeamFilterTest , FilterBySpecificTypes)
{
    std::vector<uint8> validTypes = {2, 3}; // Filtering for 2v2 and 3v3
    ArenaTeamFilterByTypes filter(validTypes);
    ArenaTeamMgr::ArenaTeamContainer result = filter.Filter(arenaTeams);
    EXPECT_EQ(result.size(), 2);           // Only 2v2 and 3v3 should pass
    EXPECT_EQ(result[1], team1);           // team1 is 2v2
    EXPECT_EQ(result[2], team2);           // team2 is 3v3
    EXPECT_EQ(result.find(3), result.end()); // team3 (5v5) should be filtered out
}
References ArenaTeamFilterByTypes::Filter().