AzerothCore Doxygen
ObjectAccessor Namespace Reference
Functions
WorldObject * GetWorldObject (WorldObject const &, ObjectGuid const &guid)
Object * GetObjectByTypeMask (WorldObject const &, ObjectGuid const &guid, uint32 typemask)
Corpse * GetCorpse (WorldObject const &u, ObjectGuid const &guid)
GameObject * GetGameObject (WorldObject const &u, ObjectGuid const &guid)
Transport * GetTransport (WorldObject const &u, ObjectGuid const &guid)
DynamicObject * GetDynamicObject (WorldObject const &u, ObjectGuid const &guid)
Unit * GetUnit (WorldObject const &, ObjectGuid const &guid)
Creature * GetCreature (WorldObject const &u, ObjectGuid const &guid)
Pet * GetPet (WorldObject const &, ObjectGuid const &guid)
Player * GetPlayer (Map const *, ObjectGuid const &guid)
Player * GetPlayer (WorldObject const &, ObjectGuid const &guid)
Creature * GetCreatureOrPetOrVehicle (WorldObject const &, ObjectGuid const &)
Player * FindPlayer (ObjectGuid const guid)
Player * FindPlayerByLowGUID (ObjectGuid::LowType lowguid)
Player * FindConnectedPlayer (ObjectGuid const guid)
Player * FindPlayerByName (std::string const &name, bool checkInWorld=true)
Creature * GetSpawnedCreatureByDBGUID (uint32 mapId, uint64 guid)
Get a spawned creature by DB guid column. MODULE USAGE ONLY - USE IT FOR CUSTOM CONTENT.
GameObject * GetSpawnedGameObjectByDBGUID (uint32 mapId, uint64 guid)
Get a spawned gameobject by DB guid column. MODULE USAGE ONLY - USE IT FOR CUSTOM CONTENT.
HashMapHolder< Player >::MapType const & GetPlayers ()
template<class T >
void AddObject (T *object)
template<class T >
void RemoveObject (T *object)
void SaveAllPlayers ()
template<>
void AddObject (Player *player)
template<>
void RemoveObject (Player *player)
void UpdatePlayerNameMapReference (std::string oldname, Player *player)
Function Documentation
AddObject() [1/2]
template<> void ObjectAccessor::AddObject (Player * player)
{
    HashMapHolder<Player>::Insert(player);
    PlayerNameMapHolder::Insert(player);
}
References PlayerNameMapHolder::Insert(), and HashMapHolder< T >::Insert().
AddObject() [2/2]
template<class T > void ObjectAccessor::AddObject (T * object)
    {
        HashMapHolder<T>::Insert(object);
    }
References HashMapHolder< T >::Insert().
Referenced by WorldSession::HandlePlayerLoginFromDB().
FindConnectedPlayer()
Player * ObjectAccessor::FindConnectedPlayer (ObjectGuid const guid)
{
    return HashMapHolder<Player>::Find(guid);
}
References HashMapHolder< T >::Find().
Referenced by Battleground::_ProcessJoin(), InstanceSaveMgr::_ResetSave(), Guild::AddMember(), ArenaTeam::AddMember(), InstanceMap::AddPlayerToMap(), ArenaTeam::BroadcastPacket(), Group::CanJoinBattlegroundQueue(), Player::CanUninviteFromGroup(), Group::ChangeLeader(), Group::ChangeMembersGroup(), lfg::LFGQueue::CheckCompatibility(), ArenaTeam::Create(), MapInstanced::CreateInstance(), Guild::DeleteMember(), ArenaTeam::DelMember(), Group::Disband(), BGQueueInviteEvent::Execute(), BGQueueRemoveEvent::Execute(), Guild::Member::FindPlayer(), ArenaTeam::FinishGame(), GmTicket::GetAssignedPlayer(), ArenaTeam::GetAverageMMR(), SocialMgr::GetFriendInfo(), Group::GetLeader(), Creature::GetLootRecipient(), GameObject::GetLootRecipient(), GmTicket::GetPlayer(), CalendarMgr::GetPlayerEvents(), ChatHandler::getSelectedPlayer(), ChatHandler::getSelectedPlayerOrSelf(), WorldSession::HandleAddFriendOpcode(), WorldSession::HandleAuctionPlaceBid(), WorldSession::HandleBattleFieldPortOpcode(), cache_commandscript::HandleCacheRefreshCommand(), WorldSession::HandleCalendarAddEvent(), WorldSession::HandleCharCustomize(), WorldSession::HandleCharDeleteOpcode(), WorldSession::HandleCharFactionOrRaceChange(), WorldSession::HandleCharRenameCallBack(), WorldSession::HandleChatIgnoredOpcode(), WorldSession::HandleGroupAcceptOpcode(), WorldSession::HandleGroupDeclineOpcode(), WorldSession::HandleGroupSetLeaderOpcode(), WorldSession::HandleGroupUninviteGuidOpcode(), WorldSession::HandleOfferPetitionOpcode(), WorldSession::HandlePetitionDeclineOpcode(), WorldSession::HandlePetitionSignOpcode(), WorldSession::HandleRaidTargetUpdateOpcode(), WorldSession::HandleSendMail(), lfg::LFGMgr::HasIgnore(), BattlegroundQueue::InviteGroupToBG(), lfg::LFGMgr::LoadLFGDungeons(), lfg::LFGMgr::MakeNewGroup(), ArenaTeam::NotifyStatsChanged(), Group::OfflineReadyCheck(), lfg::LFGGroupScript::OnRemoveMember(), Group::RemoveMember(), PetitionMgr::RemovePetitionByOwnerAndType(), Player::RemovePetitionsAndSigns(), BattlegroundQueue::RemovePlayer(), Player::ResetInstances(), ArenaTeam::Roster(), AuctionHouseMgr::SendAuctionCancelledToBidderMail(), AuctionHouseMgr::SendAuctionExpiredMail(), AuctionHouseMgr::SendAuctionOutbiddedMail(), AuctionHouseMgr::SendAuctionSalePendingMail(), AuctionHouseMgr::SendAuctionSuccessfulMail(), AuctionHouseMgr::SendAuctionWonMail(), CalendarMgr::SendCalendarClearPendingAction(), CalendarMgr::SendCalendarCommandResult(), CalendarMgr::SendCalendarEvent(), CalendarMgr::SendCalendarEventInvite(), CalendarMgr::SendCalendarEventInviteAlert(), CalendarMgr::SendCalendarEventInviteRemoveAlert(), lfg::LFGMgr::SendLfgBootProposalUpdate(), lfg::LFGMgr::SendLfgJoinResult(), lfg::LFGMgr::SendLfgQueueStatus(), WorldSession::SendLfgRoleCheckUpdate(), lfg::LFGMgr::SendLfgRoleCheckUpdate(), lfg::LFGMgr::SendLfgRoleChosen(), lfg::LFGMgr::SendLfgUpdateParty(), lfg::LFGMgr::SendLfgUpdatePlayer(), lfg::LFGMgr::SendLfgUpdateProposal(), Group::SendLootAllPassed(), Group::SendLootRoll(), Group::SendLootRollWon(), Group::SendLootStartRoll(), WorldSession::SendNameQueryOpcode(), CalendarMgr::SendPacketToAllEventRelatives(), Channel::SendToOne(), Group::SendUpdateToPlayer(), ArenaTeam::SetCaptain(), InstanceSaveMgr::UnbindAllFor(), AuctionHouseSearcher::Update(), and lfg::LFGMgr::UpdateRaidBrowser().
FindPlayer()
Player * ObjectAccessor::FindPlayer (ObjectGuid const guid)
{
    Player* player = HashMapHolder<Player>::Find(guid);
    return player && player->IsInWorld() ? player : nullptr;
}
References HashMapHolder< T >::Find(), and Object::IsInWorld().
Referenced by Battleground::_ProcessJoin(), Battleground::_ProcessResurrect(), Loot::AddItem(), BfGraveyard::AddPlayer(), Arena::AddPlayer(), Battleground::AddPlayerToResurrectQueue(), Group::BroadcastGroupUpdate(), OutdoorPvP::BroadcastPacket(), Battlefield::BroadcastPacketToQueue(), Battlefield::BroadcastPacketToWar(), Battlefield::BroadcastPacketToZone(), SocialMgr::BroadcastToFriendListers(), OutdoorPvPEP::BuffTeams(), BattlegroundSA::CaptureGraveyard(), BattlefieldWG::CapturePointTaken(), OPvPCapturePointTF::ChangeState(), Spell::CheckCast(), Group::CheckLevelForRaid(), SpellInfo::CheckTarget(), Group::ConvertToRaid(), Group::CountTheRoll(), AccountMgr::DeleteAccount(), ArenaTeamMgr::DistributeArenaPoints(), Spell::DoAllEffectOnTarget(), DelayedWindstoneSummonEvent::Execute(), Loot::FillQuestLoot(), FindPlayerByLowGUID(), lfg::LFGMgr::FinishDungeon(), Item::GetOwner(), Group::GroupLoot(), WorldSession::HandleBattlegroundPlayerPositionsOpcode(), WorldSession::HandleInitiateTradeOpcode(), WorldSession::HandleInspectArenaTeamsOpcode(), BattlefieldWG::HandleKill(), WorldSession::HandleReportPvPAFK(), WorldSession::HandleSummonResponseOpcode(), WorldState::HandleSunsReachSubPhaseTransition(), Battlefield::InvitePlayersInQueueToWar(), Battlefield::InvitePlayersInZoneToQueue(), Battlefield::InvitePlayersInZoneToWar(), ArenaTeam::IsFighting(), Battlefield::KickAfkPlayers(), Battlefield::KickPlayerFromBattlefield(), Unit::Kill(), lfg::LFGMgr::MakeNewGroup(), Group::NeedBeforeGreed(), Loot::NotifyItemRemoved(), Loot::NotifyMoneyRemoved(), Loot::NotifyQuestItemRemoved(), spell_dru_rejuvenation_moonglade_2_set::OnApply(), BattlefieldWG::OnBattleEnd(), BattlefieldWG::OnBattleStart(), BattlefieldWG::OnCreatureCreate(), spell_q12937_relief_for_the_fallen::OnRemove(), Acore::WorldObjectSpellTargetCheck::operator()(), BfGraveyard::RelocateDeadPlayers(), Battleground::RelocateDeadPlayers(), BattlegroundQueue::RemovePlayer(), BfGraveyard::RemovePlayer(), lfg::LFGMgr::RemoveProposal(), Group::ResetMaxEnchantingLevel(), BfGraveyard::Resurrect(), ArenaSeasonTeamRewarderImpl::RewardWithAchievements(), ArenaSeasonTeamRewarderImpl::RewardWithMail(), Spell::SelectEffectTypeImplicitTargets(), BfCapturePoint::SendChangePhase(), BattlefieldWG::SendInitWorldStatesToAll(), BfCapturePoint::SendObjectiveComplete(), OPvPCapturePoint::SendObjectiveComplete(), BfCapturePoint::SendUpdateWorldState(), Battlefield::SendUpdateWorldState(), OPvPCapturePoint::SendUpdateWorldState(), OutdoorPvP::SendUpdateWorldState(), WorldState::SendWorldstateUpdate(), OPvPCapturePointZM_Graveyard::SetBeaconState(), Channel::SetOwner(), Player::SummonIfPossible(), Battlefield::TeamCastSpell(), OutdoorPvP::TeamCastSpell(), BfCapturePoint::Update(), OPvPCapturePoint::Update(), OPvPCapturePointNA::Update(), BattlefieldWG::UpdatedDestroyedTowerCount(), Group::UpdateLooterGuid(), BattlefieldWG::UpdateTenacity(), BattlefieldWG::UpdateVehicleCountWG(), and GameObject::Use().
FindPlayerByLowGUID()
Player * ObjectAccessor::FindPlayerByLowGUID (ObjectGuid::LowType lowguid)
{
    ObjectGuid guid = ObjectGuid::Create<HighGuid::Player>(lowguid);
    return ObjectAccessor::FindPlayer(guid);
}
References FindPlayer().
Referenced by Player::DeleteFromDB(), WorldSession::HandleMailTakeItem(), lookup_commandscript::LookupPlayerSearchCommand(), ObjectMgr::ReturnOrDeleteOldMails(), MailDraft::SendMailTo(), MailDraft::SendReturnToSender(), and Acore::ChatCommands::PlayerIdentifier::TryConsume().
FindPlayerByName()
Player * ObjectAccessor::FindPlayerByName (std::string const & name, bool checkInWorld = true)
{
    if (Player* player = PlayerNameMapHolder::Find(name))
        if (!checkInWorld || player->IsInWorld())
            return player;
    return nullptr;
}
References PlayerNameMapHolder::Find().
Referenced by BanMgr::BanCharacter(), ChatHandler::extractLowGuidFromLink(), ChatHandler::extractPlayerTarget(), ChatHandler::GetPlayerGroupAndGUIDByName(), WorldSession::HandleArenaTeamInviteOpcode(), ban_commandscript::HandleBanInfoCharacterCommand(), WorldSession::HandleCalendarEventInvite(), deserter_commandscript::HandleDeserterAdd(), ticket_commandscript::HandleGMTicketGetByNameCommand(), WorldSession::HandleGroupChangeSubGroupOpcode(), WorldSession::HandleGroupInviteOpcode(), WorldSession::HandleGroupSwapSubGroupOpcode(), Guild::HandleInviteMember(), WorldSession::HandleMessagechatOpcode(), npc_commandscript::HandleNpcWhisperCommand(), misc_commandscript::HandleSkirmishCommand(), ArenaSpectator::HandleSpectatorSpectateCommand(), ArenaSpectator::HandleSpectatorWatchCommand(), message_commandscript::HandleWhispersCommand(), WorldSession::HandleWhoisOpcode(), Channel::Invite(), Channel::KickOrBan(), BanMgr::RemoveBanCharacter(), Channel::SetMode(), Channel::SetOwner(), and Acore::ChatCommands::PlayerIdentifier::TryConsume().
GetCorpse()
Corpse * ObjectAccessor::GetCorpse (WorldObject const & u, ObjectGuid const & guid)
{
    return u.GetMap()->GetCorpse(guid);
}
References Map::GetCorpse(), and WorldObject::GetMap().
Referenced by Spell::CheckEffectTarget(), WorldSession::DoLootRelease(), GetWorldObject(), WorldSession::HandleAutostoreLootItemOpcode(), WorldSession::HandleLootMoneyOpcode(), Map::RemoveAllObjectsInRemoveList(), and Player::SendLoot().
GetCreature()
Creature * ObjectAccessor::GetCreature (WorldObject const & u, ObjectGuid const & guid)
{
    return u.GetMap()->GetCreature(guid);
}
References Map::GetCreature(), and WorldObject::GetMap().
Referenced by at_zulgurub_entrance_speech::_OnTrigger(), at_zulgurub_bridge_speech::_OnTrigger(), at_zulgurub_temple_speech::_OnTrigger(), at_zulgurub_bloodfire_pit_speech::_OnTrigger(), at_zulgurub_edge_of_madness_speech::_OnTrigger(), boss_kologarn::boss_kologarnAI::AttachLeftArm(), boss_kologarn::boss_kologarnAI::AttachRightArm(), boss_twilight_halion::boss_twilight_halionAI::boss_twilight_halionAI(), npc_anubisath_sentinel::aqsentinelAI::CallBuddiesToAttack(), boss_algalon_the_observer::boss_algalon_the_observerAI::CallConstellations(), npc_supervisor_raelen::CallPeasent(), boss_moira_bronzebeardAI::CastOnEmperorIfPossible(), npc_commander_eligor_dawnbringer::npc_commander_eligor_dawnbringerAI::ChangeImage(), npc_still_at_it_trigger::npc_still_at_it_triggerAI::CheckAction(), npc_cork_gizelton::npc_cork_gizeltonAI::CheckCaravan(), boss_volazj::CheckPhaseMinions(), spell_putricide_mutation_init::CheckRequirementInternal(), npc_battle_at_valhalas::npc_battle_at_valhalasAI::CheckSummons(), npc_twiggy_flathead::npc_twiggy_flatheadAI::CleanUp(), npc_thassarian2::npc_thassarian2AI::Cleanup(), boss_kologarn_eyebeam::boss_kologarn_eyebeamAI::DamageDealt(), boss_sartharion::boss_sartharionAI::DamageTaken(), boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI::DamageTaken(), boss_freya::boss_freyaAI::DamageTaken(), boss_halion::boss_halionAI::DamageTaken(), boss_twilight_halion::boss_twilight_halionAI::DamageTaken(), boss_the_lich_king::boss_the_lich_kingAI::DamageTaken(), npc_ulduar_iron_construct::npc_ulduar_iron_constructAI::DamageTaken(), npc_ulduar_flash_freeze::npc_ulduar_flash_freezeAI::DamageTaken(), boss_thorim_start_npcs::boss_thorim_start_npcsAI::DamageTaken(), boss_mal_ganis::boss_mal_ganisAI::DamageTaken(), boss_kologarn_arms::boss_kologarn_armsAI::DamageTaken(), boss_yoggsaron_brain::boss_yoggsaron_brainAI::DamageTaken(), SummonList::DespawnAll(), SummonList::DespawnEntry(), boss_jedoga_shadowseeker::DespawnOOCSummons(), boss_netherspite::DestroyPortals(), boss_mandokir::boss_mandokirAI::DoAction(), go_ossirian_crystal::go_ossirian_crystalAI::DoAction(), boss_jedoga_shadowseeker::DoAction(), npc_high_overlord_saurfang_icc::npc_high_overlord_saurfangAI::DoAction(), npc_muradin_bronzebeard_icc::npc_muradin_bronzebeard_iccAI::DoAction(), boss_the_lich_king::boss_the_lich_kingAI::DoAction(), npc_strangulate_vehicle::npc_strangulate_vehicleAI::DoAction(), npc_crok_scourgebane::npc_crok_scourgebaneAI::DoAction(), npc_argent_captainAI::DoAction(), npc_ahune_bunny::DoAction(), SummonList::DoAction(), SummonList::DoAction(), boss_paletress::boss_paletressAI::DoAction(), boss_thorim_sif::boss_thorim_sifAI::DoAction(), npc_xt002_heart::npc_xt002_heartAI::DoAction(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::DoAction(), boss_yoggsaron_brain::boss_yoggsaron_brainAI::DoAction(), npc_scarlet_miner_cart::npc_scarlet_miner_cartAI::DoAction(), boss_razorgore::boss_razorgoreAI::DoChangePhase(), npc_tirions_gambit_tirion::npc_tirions_gambit_tirionAI::DoSummonAction(), SummonList::DoZoneInCombat(), npc_ravenclaw_apparition::npc_ravenclaw_apparitionAI::EmoteCrowd(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::EmpowerCultist(), boss_halion::boss_halionAI::EnterEvadeMode(), boss_prince_keleseth_icc::boss_prince_kelesethAI::EnterEvadeMode(), boss_prince_taldaram_icc::boss_prince_taldaramAI::EnterEvadeMode(), boss_prince_valanar_icc::boss_prince_valanarAI::EnterEvadeMode(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::EnterEvadeMode(), boss_festergut::boss_festergutAI::EnterEvadeMode(), boss_rotface::boss_rotfaceAI::EnterEvadeMode(), boss_the_lich_king::boss_the_lich_kingAI::EnterEvadeMode(), npc_tirion_fordring_tft::npc_tirion_fordringAI::EnterEvadeMode(), npc_argent_captainAI::EnterEvadeMode(), npc_burning_spirit::npc_burning_spiritAI::EnterEvadeMode(), npc_lord_gregor_lescovar::npc_lord_gregor_lescovarAI::EnterEvadeMode(), AssistDelayEvent::Execute(), IceTombSummonEvent::Execute(), boss_sartharion_tenebron::boss_sartharion_tenebronAI::ExecuteEvent(), boss_salramm::boss_salrammAI::ExplodeGhoul(), spell_festergut_blighted_spores_aura::ExtraEffect(), spell_the_lich_king_restore_soul::FilterTargets(), npc_thrall_bfu::npc_thrall_bfuAI::FollowThrall(), brann_bronzebeard::brann_bronzebeardAI::GetAbedneum(), Unit::GetCompanionPet(), npc_hourglass_of_eternity::npc_hourglass_of_eternityAI::GetCopy(), GetCreatureOrPetOrVehicle(), SummonList::GetCreatureWithEntry(), npc_chesspiece::GetEnemyPiece(), SummonList::GetEntryCount(), npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::GetEntryFromSummons(), npc_arthas::npc_arthasAI::GetEventNpc(), boss_skadi::boss_skadiAI::GetGrauf(), boss_hodir::boss_hodirAI::GetHelper(), npc_echo_of_medivh::GetHostileTargetForChangeFacing(), brann_bronzebeard::brann_bronzebeardAI::GetKaddrak(), npc_chesspiece::GetLowestHpFriendlyPiece(), npc_still_at_it_trigger::npc_still_at_it_triggerAI::GetManus(), brann_bronzebeard::brann_bronzebeardAI::GetMarnak(), npc_conversing_with_the_depths_trigger::npc_conversing_with_the_depths_triggerAI::GetOachanoa(), GetObjectByTypeMask(), npc_anubisath_sentinel::aqsentinelAI::GetOtherSentinels(), npc_echo_of_medivh::GetPiece(), npc_pilgrims_bounty_chair::GetPlate(), boss_moroes::GetRandomGuest(), npc_dream_fog::npc_dream_fogAI::GetRandomUnitFromDragonThreatList(), boss_twin_valkyrAI::GetSister(), npc_air_force_bots::npc_air_force_botsAI::GetSummonedGuard(), TempSummon::GetSummonerCreatureBase(), GetUnit(), npc_wintergarde_gryphon::getVillager(), GetWorldObject(), go_ossirian_crystal::go_ossirian_crystalAI::GossipHello(), go_troll_cage::go_troll_cageAI::GossipHello(), go_wind_stone::go_wind_stoneAI::GossipSelect(), spell_illidari_council_empyreal_balance::HandleAfterCast(), spell_illidari_council_empyreal_equivalency::HandleAfterCast(), npc_anachronos_the_ancient::npc_anachronos_the_ancientAI::HandleAnimation(), npc_torloth_the_magnificent::npc_torloth_the_magnificentAI::HandleAnimation(), npc_echo_of_medivh::HandleCheat(), spell_halion_twilight_division::HandleDummy(), spell_mage_summon_water_elemental::HandleDummy(), spell_black_template_harpooners_mark_aura::HandleEffectRemove(), spell_botanica_call_of_the_falcon_aura::HandleEffectRemove(), spell_assembly_meltdown::HandleInstaKill(), spell_oculus_rider_aura::HandleOnEffectRemove(), npc_echo_of_medivh::HandlePieceMoveByAI(), spell_sartharion_lava_strike::HandleSchoolDamage(), spell_festergut_pungent_blight::HandleScript(), spell_putricide_unbound_plague::HandleScript(), spell_rotface_large_ooze_combine::HandleScript(), spell_rotface_large_ooze_buff_combine::HandleScript(), spell_q12805_lifeblood_dummy::HandleScript(), spell_putricide_mutated_transformation::HandleSummon(), boss_volkhan::HasActiveGolem(), SummonList::HasEntry(), boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI::HealReceived(), npc_cork_gizelton::npc_cork_gizeltonAI::ImmuneFlagSet(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::InformCloud(), go_troll_cage::go_troll_cageAI::initBlyCrewMember(), boss_warchief_kargath_bladefist::InitializeAI(), SummonList::IsAnyCreatureAlive(), SummonList::IsAnyCreatureInCombat(), SummonList::IsAnyCreatureWithEntryAlive(), IsEncounterComplete(), npc_direbrew_minion::IsSummonedBy(), npc_onyx_flamecaller::npc_onyx_flamecallerAI::IsSummonedBy(), npc_living_inferno::npc_living_infernoAI::IsSummonedBy(), npc_kinetic_bomb::npc_kinetic_bombAI::IsSummonedBy(), npc_putricide_oozeAI::IsSummonedBy(), npc_raging_spirit::npc_raging_spiritAI::IsSummonedBy(), npc_suppresser::npc_suppresserAI::IsSummonedBy(), npc_strangulate_vehicle::npc_strangulate_vehicleAI::IsSummonedBy(), boss_kologarn_eyebeam::boss_kologarn_eyebeamAI::IsSummonedBy(), boss_emperor_dagran_thaurissan::boss_draganthaurissanAI::JustDied(), npc_chesspiece::JustDied(), boss_infinite_corruptor::boss_infinite_corruptorAI::JustDied(), npc_anubisath_sentinel::aqsentinelAI::JustDied(), npc_qiraj_war_spawn::npc_qiraj_war_spawnAI::JustDied(), boss_sartharion_dragonAI::JustDied(), npc_memory::npc_memoryAI::JustDied(), boss_prince_keleseth_icc::boss_prince_kelesethAI::JustDied(), boss_prince_taldaram_icc::boss_prince_taldaramAI::JustDied(), boss_prince_valanar_icc::boss_prince_valanarAI::JustDied(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::JustDied(), boss_festergut::boss_festergutAI::JustDied(), npc_stinky_icc::npc_stinky_iccAI::JustDied(), boss_rotface::boss_rotfaceAI::JustDied(), npc_little_ooze::npc_little_oozeAI::JustDied(), npc_big_ooze::npc_big_oozeAI::JustDied(), npc_precious_icc::npc_precious_iccAI::JustDied(), npc_raging_spirit::npc_raging_spiritAI::JustDied(), npc_spirit_warden::npc_spirit_wardenAI::JustDied(), boss_sister_svalna::boss_sister_svalnaAI::JustDied(), boss_sjonnir::boss_sjonnirAI::JustDied(), boss_sjonnir_iron_sludge::boss_sjonnir_iron_sludgeAI::JustDied(), brann_bronzebeard::brann_bronzebeardAI::JustDied(), npc_auriaya_feral_defender::npc_auriaya_feral_defenderAI::JustDied(), boss_freya_summons::boss_freya_summonsAI::JustDied(), npc_ulduar_saronite_vapors::npc_ulduar_saronite_vaporsAI::JustDied(), npc_ulduar_saronite_animus::npc_ulduar_saronite_animusAI::JustDied(), npc_ulduar_iron_construct::npc_ulduar_iron_constructAI::JustDied(), boss_kologarn::boss_kologarnAI::JustDied(), boss_kologarn_arms::boss_kologarn_armsAI::JustDied(), boss_thorim_start_npcs::boss_thorim_start_npcsAI::JustDied(), boss_thorim_runic_colossus::boss_thorim_runic_colossusAI::JustDied(), boss_thorim_ancient_rune_giant::boss_thorim_ancient_rune_giantAI::JustDied(), npc_xt002_heart::npc_xt002_heartAI::JustDied(), boss_yoggsaron::boss_yoggsaronAI::JustDied(), npc_ulduar_storm_tempered_keeper::npc_ulduar_storm_tempered_keeperAI::JustDied(), npc_massive_jormungar::npc_massive_jormungarAI::JustDied(), npc_ferocious_rhino::npc_ferocious_rhinoAI::JustDied(), npc_ravenous_furbolg::npc_ravenous_furbolgAI::JustDied(), npc_frenzied_worgen::npc_frenzied_worgenAI::JustDied(), violet_hold_trashAI::JustDied(), npc_infernal_attacker::npc_infernal_attackerAI::JustDied(), npc_illidari_spawn::npc_illidari_spawnAI::JustDied(), boss_epoch_hunter::JustDied(), boss_baltharus_the_warborn::boss_baltharus_the_warbornAI::JustDied(), boss_halion::boss_halionAI::JustDied(), boss_twilight_halion::boss_twilight_halionAI::JustDied(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::JustDied(), boss_flame_leviathan_defense_turret::boss_flame_leviathan_defense_turretAI::JustDied(), boss_freya_elder_stonebark::boss_freya_elder_stonebarkAI::JustDied(), boss_freya_elder_brightleaf::boss_freya_elder_brightleafAI::JustDied(), boss_freya_elder_ironbranch::boss_freya_elder_ironbranchAI::JustDied(), boss_warchief_kargath_bladefist::JustDied(), npc_torloth_the_magnificent::npc_torloth_the_magnificentAI::JustDied(), boss_priestess_delrissa::JustEngagedWith(), npc_sunblade_scout::JustEngagedWith(), npc_amanishi_scout::JustEngagedWith(), npc_risen_archmage::npc_risen_archmageAI::JustEngagedWith(), boss_sister_svalna::boss_sister_svalnaAI::JustEngagedWith(), boss_sjonnir::boss_sjonnirAI::JustEngagedWith(), npc_auriaya_sanctum_sentry::npc_auriaya_sanctum_sentryAI::JustEngagedWith(), boss_freya::boss_freyaAI::JustEngagedWith(), boss_shirrak_the_dead_watcher::JustEngagedWith(), boss_sartharion::boss_sartharionAI::JustEngagedWith(), npc_green_dragon_combat_trigger::npc_green_dragon_combat_triggerAI::JustEngagedWith(), npc_lord_gregor_lescovar::npc_lord_gregor_lescovarAI::JustEngagedWith(), boss_prince_keleseth_icc::boss_prince_kelesethAI::JustEngagedWith(), boss_prince_taldaram_icc::boss_prince_taldaramAI::JustEngagedWith(), boss_prince_valanar_icc::boss_prince_valanarAI::JustEngagedWith(), boss_festergut::boss_festergutAI::JustEngagedWith(), boss_rotface::boss_rotfaceAI::JustEngagedWith(), boss_steelbreaker::boss_steelbreakerAI::JustEngagedWith(), boss_runemaster_molgeim::boss_runemaster_molgeimAI::JustEngagedWith(), boss_stormcaller_brundir::boss_stormcaller_brundirAI::JustEngagedWith(), boss_yoggsaron_cloud::boss_yoggsaron_cloudAI::JustSummoned(), npc_frozen_orb_stalker::npc_frozen_orb_stalkerAI::JustSummoned(), npc_ulduar_storm_tempered_keeper::npc_ulduar_storm_tempered_keeperAI::JustSummoned(), boss_captain_skarloc::JustSummoned(), boss_sartharion_dragonAI::JustSummoned(), npc_collapsing_star::npc_collapsing_starAI::JustSummoned(), npc_algalon_worm_hole::npc_algalon_worm_holeAI::JustSummoned(), boss_mandokir::boss_mandokirAI::KilledUnit(), npc_grizzlemaw_cw_trigger::npc_grizzlemaw_cw_triggerAI::MoveInLineOfSight(), boss_kologarn::boss_kologarnAI::MoveInLineOfSight(), npc_chesspiece::MovementInform(), npc_koltira_deathweaver::npc_koltira_deathweaverAI::MovementInform(), npc_acherus_necromancer::npc_acherus_necromancerAI::MovementInform(), npc_gothik_the_harvester::npc_gothik_the_harvesterAI::MovementInform(), boss_grand_champion::boss_grand_championAI::MovementInform(), npc_tirion_fordring_tft::npc_tirion_fordringAI::MovementInform(), npc_fel_guard_hound::npc_fel_guard_houndAI::MovementInform(), npc_shattered_hand_scout::MovementInform(), boss_jedoga_shadowseeker::MovementInform(), npc_burning_spirit::npc_burning_spiritAI::MovementInform(), npc_sergeant_bly::npc_sergeant_blyAI::MovementInform(), npc_xt002_scrapbot::npc_xt002_scrapbotAI::MovementInform(), npc_cameron::MoveTheChildren(), npc_image_of_medivh::npc_image_of_medivhAI::NextStep(), npc_big_ooze::npc_big_oozeAI::npc_big_oozeAI(), npc_little_ooze::npc_little_oozeAI::npc_little_oozeAI(), npc_ulduar_saronite_animus::npc_ulduar_saronite_animusAI::npc_ulduar_saronite_animusAI(), spell_blood_queen_frenzied_bloodthirst_aura::OnApply(), spell_blood_queen_vampiric_bite::OnCast(), achievement_cant_do_that_while_stunned::OnCheck(), achievement_auriaya_crazy_cat_lady::OnCheck(), achievement_auriaya_nine_lives::OnCheck(), achievement_kologarn_looks_could_kill::OnCheck(), achievement_kologarn_rubble_and_roll::OnCheck(), achievement_kologarn_with_open_arms::OnCheck(), achievement_xt002_nerf_engineering::OnCheck(), achievement_xt002_nerf_gravity_bombs::OnCheck(), achievement_thorim_stand_in_the_lightning::OnCheck(), achievement_thorim_lose_your_illusion::OnCheck(), achievement_yogg_saron_darkness::OnCheck(), achievement_yogg_saron_he_waits_dreaming::OnCheck(), go_palehoof_sphere::OnGossipHello(), npc_ulduar_expedition_commander::OnGossipHello(), go_orb_of_domination::OnGossipHello(), go_acherus_soul_prison::OnGossipHello(), go_ulduar_do_not_push_this_button::OnGossipHello(), go_harpoon_canon::OnGossipHello(), go_ulduar_working_harpoon::OnGossipHello(), npc_ulduar_expedition_commander::OnGossipSelect(), npc_cos_chromie_start::OnGossipSelect(), spell_blood_queen_frenzied_bloodthirst_aura::OnRemove(), at_trigger_the_beast_movement::OnTrigger(), at_the_beast_room::OnTrigger(), at_baltharus_plateau::OnTrigger(), at_lady_deathwhisper_entrance::OnTrigger(), at_sindragosa_lair::OnTrigger(), at_icc_start_frostwing_gauntlet::OnTrigger(), at_icc_gauntlet_event::OnTrigger(), at_icc_putricide_trap::OnTrigger(), npc_scarlet_miner_cart::npc_scarlet_miner_cartAI::PassengerBoarded(), npc_doctor::npc_doctorAI::PatientSaved(), npc_simone::npc_simoneAI::Precious(), npc_jungle_punch_target::npc_jungle_punch_targetAI::proceedCwEvent(), npc_cork_gizelton::npc_cork_gizeltonAI::RelocateSummons(), npc_ulduar_flames_initial::npc_ulduar_flames_initialAI::RemoveAll(), boss_festergut::boss_festergutAI::RemoveBlight(), npc_echo_of_medivh::RemoveCheats(), SummonList::RemoveNotExisting(), npc_cork_gizelton::npc_cork_gizeltonAI::RemoveSummons(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::ReorderInstance(), boss_majordomo::boss_majordomoAI::Reset(), npc_varian_wrynn::npc_varian_wrynnAI::Reset(), npc_thrall_bfu::npc_thrall_bfuAI::Reset(), boss_mandokir::boss_mandokirAI::Reset(), npc_dark_iron_attack_generator::Reset(), npc_anubisath_sentinel::aqsentinelAI::Reset(), boss_paletress::boss_paletressAI::Reset(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::Reset(), boss_the_lich_king::boss_the_lich_kingAI::Reset(), boss_sjonnir::boss_sjonnirAI::Reset(), boss_freya::boss_freyaAI::Reset(), boss_razorscale::boss_razorscaleAI::Reset(), npc_xt002_scrapbot::npc_xt002_scrapbotAI::Reset(), npc_xt002_boombot::npc_xt002_boombotAI::Reset(), boss_palehoof::boss_palehoofAI::Reset(), npc_captain_saeed::npc_captain_saeedAI::Reset(), SmartScript::ResetBaseObject(), npc_ahune_bunny::ResetFlameCallers(), SummonList::Respawn(), RespawnAssemblyOfIron(), boss_sartharion::boss_sartharionAI::RespawnDragons(), RestoreAssemblyHealth(), BfGraveyard::Resurrect(), boss_thorim_runic_colossus::boss_thorim_runic_colossusAI::RunRunicSmash(), boss_razuvious::boss_razuviousAI::ScheduleInteractWithDeathKnight(), boss_razuvious::boss_razuviousAI::ScheduleRP(), spell_the_lich_king_valkyr_target_search::SelectTarget(), WorldSession::SendDoFlight(), npc_xt002_heart::npc_xt002_heartAI::SendEnergyToCorner(), Player::SendInitWorldStates(), boss_sartharion::boss_sartharionAI::SendLavaWaves(), npc_anubisath_sentinel::aqsentinelAI::SendMyListToBuddies(), WorldSession::SendTaxiStatus(), instance_naxxramas::SetBossState(), npc_ulduar_harpoonfirestate::npc_ulduar_harpoonfirestateAI::SetData(), boss_the_beast::boss_thebeastAI::SetData(), npc_shandy_dalaran::npc_shandy_dalaranAI::SetData(), npc_thassarian2::npc_thassarian2AI::SetData(), boss_murmur::SetGUID(), npc_crok_scourgebane::npc_crok_scourgebaneAI::SetGUID(), npc_cork_gizelton::npc_cork_gizeltonAI::SetGUID(), npc_tirion_fordring_tft::npc_tirion_fordringAI::sGossipSelect(), instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::SpawnAnubArak(), npc_varian_wrynn::npc_varian_wrynnAI::SpawnWave(), boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI::SpellHit(), npc_ulduar_iron_construct::npc_ulduar_iron_constructAI::SpellHit(), boss_razorscale::boss_razorscaleAI::SpellHit(), npc_drakuru_shackles::npc_drakuru_shacklesAI::SpellHit(), npc_deaths_door_fell_cannon_target_bunny::npc_deaths_door_fell_cannon_target_bunnyAI::SpellHit(), npc_injured_patient::npc_injured_patientAI::SpellHit(), npc_chesspiece::SpellHitTarget(), boss_yoggsaron_voice::boss_yoggsaron_voiceAI::SpellHitTarget(), npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI::SpidersMoveDown(), npc_giant_claw_tentacle::Submerge(), PassengerController::SummonCreatures(), boss_sartharion_shadron::boss_sartharion_shadronAI::SummonedCreatureDies(), npc_drakonid_spawner::SummonedCreatureDies(), boss_elder_nadox::SummonHelpers(), npc_captain_saeed::npc_captain_saeedAI::SummonsAction(), npc_cork_gizelton::npc_cork_gizeltonAI::SummonsFollow(), npc_sergeant_bly::npc_sergeant_blyAI::switchFactionIfAlive(), npc_commander_dawnforge::npc_commander_dawnforgeAI::Turn_to_Pathaleons_Image(), npc_commander_eligor_dawnbringer::npc_commander_eligor_dawnbringerAI::TurnAudience(), boss_rend_blackhand::boss_rend_blackhandAI::UpdateAI(), npc_vaelastrasz_the_red::npc_vaelastrasz_the_redAI::UpdateAI(), npc_core_rager::npc_core_ragerAI::UpdateAI(), boss_majordomo::boss_majordomoAI::UpdateAI(), npc_chesspiece::UpdateAI(), npc_barnes::npc_barnesAI::UpdateAI(), npc_scarlet_ghoul::npc_scarlet_ghoulAI::UpdateAI(), npc_scarlet_miner::npc_scarlet_minerAI::UpdateAI(), npc_acherus_necromancer::npc_acherus_necromancerAI::UpdateAI(), npc_gothik_the_harvester::npc_gothik_the_harvesterAI::UpdateAI(), npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::UpdateAI(), npc_kalecgos_kj::UpdateAI(), npc_cameron::UpdateAI(), npc_eastvale_peasent::UpdateAI(), npc_bh_thalorien_dawnseeker::npc_bh_thalorien_dawnseekerAI::UpdateAI(), npc_varian_wrynn::npc_varian_wrynnAI::UpdateAI(), npc_thrall_bfu::npc_thrall_bfuAI::UpdateAI(), npc_winterfin_playmate::UpdateAI(), npc_snowfall_glade_playmate::UpdateAI(), npc_the_biggest_tree::UpdateAI(), npc_high_oracle_soo_roo::UpdateAI(), npc_elder_kekek::UpdateAI(), npc_the_etymidian::UpdateAI(), npc_alexstraza_the_lifebinder::UpdateAI(), npc_arthas::npc_arthasAI::UpdateAI(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::UpdateAI(), boss_skeram::UpdateAI(), npc_tharnarian::npc_tharnarianAI::UpdateAI(), npc_twiggy_flathead::npc_twiggy_flatheadAI::UpdateAI(), npc_sergeant_bly::npc_sergeant_blyAI::UpdateAI(), boss_jedoga_shadowseeker::UpdateAI(), boss_anub_arak::UpdateAI(), boss_sartharion::boss_sartharionAI::UpdateAI(), boss_general_zarithrian::boss_general_zarithrianAI::UpdateAI(), boss_halion::boss_halionAI::UpdateAI(), boss_twilight_halion::boss_twilight_halionAI::UpdateAI(), npc_halion_controller::npc_halion_controllerAI::UpdateAI(), boss_paletress::boss_paletressAI::UpdateAI(), npc_toc5_grand_champion_minion::npc_toc5_grand_champion_minionAI::UpdateAI(), boss_grand_champion::boss_grand_championAI::UpdateAI(), boss_anubarak_trial::boss_anubarak_trialAI::UpdateAI(), npc_snobold_vassal::npc_snobold_vassalAI::UpdateAI(), boss_jormungarAI::UpdateAI(), boss_novos::boss_novosAI::UpdateAI(), npc_hor_leader::npc_hor_leaderAI::UpdateAI(), npc_blood_queen_lana_thel::npc_blood_queen_lana_thelAI::UpdateAI(), npc_high_overlord_saurfang_icc::npc_high_overlord_saurfangAI::UpdateAI(), npc_muradin_bronzebeard_icc::npc_muradin_bronzebeard_iccAI::UpdateAI(), boss_festergut::boss_festergutAI::UpdateAI(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::UpdateAI(), npc_cult_fanatic::npc_cult_fanaticAI::UpdateAI(), npc_cult_adherent::npc_cult_adherentAI::UpdateAI(), boss_rotface::boss_rotfaceAI::UpdateAI(), boss_the_lich_king::boss_the_lich_kingAI::UpdateAI(), npc_tirion_fordring_tft::npc_tirion_fordringAI::UpdateAI(), npc_valkyr_shadowguard::npc_valkyr_shadowguardAI::UpdateAI(), npc_strangulate_vehicle::npc_strangulate_vehicleAI::UpdateAI(), npc_terenas_menethil::npc_terenas_menethilAI::UpdateAI(), npc_highlord_tirion_fordring_lh::npc_highlord_tirion_fordringAI::UpdateAI(), npc_crok_scourgebane::npc_crok_scourgebaneAI::UpdateAI(), boss_thaddius::boss_thaddiusAI::UpdateAI(), boss_thaddius_summon::boss_thaddius_summonAI::UpdateAI(), npc_stormforged_lieutenant::UpdateAI(), boss_sjonnir::boss_sjonnirAI::UpdateAI(), boss_algalon_the_observer::boss_algalon_the_observerAI::UpdateAI(), npc_freya_ward::npc_freya_wardAI::UpdateAI(), boss_freya_elder_brightleaf::boss_freya_elder_brightleafAI::UpdateAI(), boss_vezax::boss_vezaxAI::UpdateAI(), npc_ulduar_hodir_priest::npc_ulduar_hodir_priestAI::UpdateAI(), npc_ulduar_hodir_druid::npc_ulduar_hodir_druidAI::UpdateAI(), npc_ulduar_hodir_shaman::npc_ulduar_hodir_shamanAI::UpdateAI(), npc_ulduar_hodir_mage::npc_ulduar_hodir_mageAI::UpdateAI(), npc_ulduar_flames_initial::npc_ulduar_flames_initialAI::UpdateAI(), boss_razorscale::boss_razorscaleAI::UpdateAI(), npc_ulduar_expedition_engineer::npc_ulduar_expedition_engineerAI::UpdateAI(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::UpdateAI(), npc_ulduar_storm_tempered_keeper::npc_ulduar_storm_tempered_keeperAI::UpdateAI(), boss_ingvar_the_plunderer::UpdateAI(), boss_palehoof::boss_palehoofAI::UpdateAI(), boss_svala::boss_svalaAI::UpdateAI(), npc_thassarian2::npc_thassarian2AI::UpdateAI(), npc_archmage_landalock::npc_archmage_landalockAI::UpdateAI(), npc_commander_eligor_dawnbringer::npc_commander_eligor_dawnbringerAI::UpdateAI(), npc_lord_arete::npc_lord_areteAI::UpdateAI(), npc_blessed_banner::npc_blessed_bannerAI::UpdateAI(), npc_overlord_drakuru_betrayal::npc_overlord_drakuru_betrayalAI::UpdateAI(), npc_ahune_bunny::UpdateAI(), npc_deaths_door_fell_cannon_target_bunny::npc_deaths_door_fell_cannon_target_bunnyAI::UpdateAI(), npc_commander_dawnforge::npc_commander_dawnforgeAI::UpdateAI(), npc_pet_gen_fetch_ball::UpdateAI(), npc_injured_patient::npc_injured_patientAI::UpdateAI(), npc_lord_gregor_lescovar::npc_lord_gregor_lescovarAI::UpdateAI(), boss_ichoron::boss_ichoronAI::UpdateAI(), npc_suppresser::npc_suppresserAI::UpdateAI(), npc_xt002_scrapbot::npc_xt002_scrapbotAI::UpdateAI(), npc_xt002_boombot::npc_xt002_boombotAI::UpdateAI(), npc_warmage_violetstand::UpdateAI(), npc_halion_controller::npc_halion_controllerAI::UpdateCorporeality(), npc_cork_gizelton::npc_cork_gizeltonAI::UpdateEscortAI(), brann_bronzebeard::brann_bronzebeardAI::UpdateEscortAI(), npc_tirions_gambit_tirion::npc_tirions_gambit_tirionAI::UpdateEscortAI(), npc_tooga::npc_toogaAI::UpdateFollowerAI(), npc_ringo::npc_ringoAI::UpdateFollowerAI(), boss_netherspite::UpdatePortals(), npc_grimstone::npc_grimstoneAI::updateReset(), brann_bronzebeard::brann_bronzebeardAI::WaypointReached(), npc_tirions_gambit_tirion::npc_tirions_gambit_tirionAI::WaypointReached(), npc_scarlet_miner::npc_scarlet_minerAI::WaypointReached(), npc_varian_wrynn::npc_varian_wrynnAI::WaypointReached(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::WaypointReached(), npc_taretha::npc_tarethaAI::WaypointReached(), npc_general_andorov::WaypointReached(), npc_cork_gizelton::npc_cork_gizeltonAI::WaypointReached(), npc_crok_scourgebane::npc_crok_scourgebaneAI::WaypointReached(), npc_emily::npc_emilyAI::WaypointReached(), and npc_crok_scourgebane::npc_crok_scourgebaneAI::WaypointStart().
GetCreatureOrPetOrVehicle()
Creature * ObjectAccessor::GetCreatureOrPetOrVehicle (WorldObject const & u, ObjectGuid const & guid)
{
    if (guid.IsPet())
        return GetPet(u, guid);
    if (guid.IsCreatureOrVehicle())
        return GetCreature(u, guid);
    return nullptr;
}
References GetCreature(), GetPet(), ObjectGuid::IsCreatureOrVehicle(), and ObjectGuid::IsPet().
Referenced by Unit::GetFirstMinion(), Unit::GetGuardianPet(), Player::GetNextQuest(), Player::GetNPCIfCanInteractWith(), ChatHandler::getSelectedCreature(), SmartScript::GetTargets(), WorldSession::HandleDismissCritter(), WorldSession::HandlePetAbandon(), WorldSession::HandlePetCancelAuraOpcode(), WorldSession::HandlePetSpellAutocastOpcode(), WorldSession::HandlePetStopAttack(), WorldSession::HandleSpellClick(), Player::PrepareQuestMenu(), WorldSession::SendPetNameQuery(), and Player::SendPreparedQuest().
GetDynamicObject()
DynamicObject * ObjectAccessor::GetDynamicObject (WorldObject const & u, ObjectGuid const & guid)
{
    return u.GetMap()->GetDynamicObject(guid);
}
References Map::GetDynamicObject(), and WorldObject::GetMap().
Referenced by GetObjectByTypeMask(), and GetWorldObject().
GetGameObject()
GameObject * ObjectAccessor::GetGameObject (WorldObject const & u, ObjectGuid const & guid)
{
    return u.GetMap()->GetGameObject(guid);
}
References Map::GetGameObject(), and WorldObject::GetMap().
Referenced by Unit::_UpdateSpells(), boss_mimiron::boss_mimironAI::CloseDoorAndButton(), npc_high_overlord_saurfang_icc::npc_high_overlord_saurfangAI::DoAction(), npc_muradin_bronzebeard_icc::npc_muradin_bronzebeard_iccAI::DoAction(), brann_bronzebeard::brann_bronzebeardAI::DoAction(), spell_the_lich_king_quake::FilterTargets(), BfCapturePoint::GetCapturePointGo(), Unit::GetGameObject(), GameObject::GetLinkedTrap(), GetObjectByTypeMask(), boss_thorim::boss_thorimAI::GetThorimObject(), GetWorldObject(), go_celestial_planetarium_access::go_celestial_planetarium_accessAI::GossipHello(), boss_netherspite::HandleDoors(), boss_drakos::boss_drakosAI::JustDied(), boss_thorim_runic_colossus::boss_thorim_runic_colossusAI::JustDied(), boss_thorim_ancient_rune_giant::boss_thorim_ancient_rune_giantAI::JustDied(), boss_xt002::boss_xt002AI::JustDied(), boss_yoggsaron::boss_yoggsaronAI::JustDied(), boss_xt002::boss_xt002AI::JustEngagedWith(), boss_arlokk::boss_arlokkAI::JustReachedHome(), npc_valkyr_shadowguard::npc_valkyr_shadowguardAI::MovementInform(), go_shadowforge_brazier::OnGossipHello(), BattlefieldWG::ProcessEvent(), Unit::RemoveAllGameObjects(), Unit::RemoveGameObject(), boss_ossirian::Reset(), brann_bronzebeard::brann_bronzebeardAI::Reset(), boss_xt002::boss_xt002AI::Reset(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::Reset(), SmartScript::ResetBaseObject(), brann_bronzebeard::brann_bronzebeardAI::ResetEvent(), boss_mimiron::boss_mimironAI::ResetGameObjects(), boss_svala::boss_svalaAI::SetData(), boss_kaelthas::SetRoomState(), boss_flame_leviathan::boss_flame_leviathanAI::TurnGates(), boss_flame_leviathan::boss_flame_leviathanAI::TurnHealStations(), boss_majordomo::boss_majordomoAI::UpdateAI(), boss_ragnaros::boss_ragnarosAI::UpdateAI(), npc_crystal_spike::UpdateAI(), boss_mimiron::boss_mimironAI::UpdateAI(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::UpdateAI(), boss_svala::boss_svalaAI::UpdateAI(), npc_shadowmoon_tuber_node::npc_shadowmoon_tuber_nodeAI::UpdateAI(), brann_bronzebeard::brann_bronzebeardAI::UpdateEscortAI(), and brann_bronzebeard::brann_bronzebeardAI::WaypointReached().
GetObjectByTypeMask()
Object * ObjectAccessor::GetObjectByTypeMask (WorldObject const & p, ObjectGuid const & guid, uint32 typemask)
{
    switch (guid.GetHigh())
    {
        case HighGuid::Item:
            if (typemask & TYPEMASK_ITEM && p.IsPlayer())
                return ((Player const&)p).GetItemByGuid(guid);
            break;
        case HighGuid::Player:
            if (typemask & TYPEMASK_PLAYER)
                return GetPlayer(p, guid);
            break;
        case HighGuid::Transport:
        case HighGuid::Mo_Transport:
        case HighGuid::GameObject:
            if (typemask & TYPEMASK_GAMEOBJECT)
                return GetGameObject(p, guid);
            break;
        case HighGuid::Unit:
        case HighGuid::Vehicle:
            if (typemask & TYPEMASK_UNIT)
                return GetCreature(p, guid);
            break;
        case HighGuid::Pet:
            if (typemask & TYPEMASK_UNIT)
                return GetPet(p, guid);
            break;
        case HighGuid::DynamicObject:
            if (typemask & TYPEMASK_DYNAMICOBJECT)
                return GetDynamicObject(p, guid);
            break;
        default:
            return nullptr;
    }
    return nullptr;
}
References DynamicObject, GameObject, GetCreature(), GetDynamicObject(), GetGameObject(), ObjectGuid::GetHigh(), GetPet(), GetPlayer(), Object::IsPlayer(), Item, Mo_Transport, Pet, Player, Transport, TYPEMASK_DYNAMICOBJECT, TYPEMASK_GAMEOBJECT, TYPEMASK_ITEM, TYPEMASK_PLAYER, TYPEMASK_UNIT, Unit, and Vehicle.
Referenced by Player::GetViewpoint(), WorldSession::HandleQuestgiverAcceptQuestOpcode(), WorldSession::HandleQuestgiverChooseRewardOpcode(), WorldSession::HandleQuestgiverCompleteQuest(), WorldSession::HandleQuestgiverQueryQuestOpcode(), WorldSession::HandleQuestgiverRequestRewardOpcode(), WorldSession::HandleQuestgiverStatusQueryOpcode(), and Player::SendPreparedQuest().
GetPet()
Pet * ObjectAccessor::GetPet (WorldObject const & u, ObjectGuid const & guid)
{
    return u.GetMap()->GetPet(guid);
}
References WorldObject::GetMap(), and Map::GetPet().
Referenced by GetCreatureOrPetOrVehicle(), GetObjectByTypeMask(), Player::GetPet(), GetUnit(), GetWorldObject(), and WorldSession::HandlePetRename().
GetPlayer() [1/2]
Player * ObjectAccessor::GetPlayer (Map const * m, ObjectGuid const & guid)
{
    if (Player * player = HashMapHolder<Player>::Find(guid))
        if (player->IsInWorld() && player->GetMap() == m)
            return player;
    return nullptr;
}
Referenced by npc_enslaved_netherwing_drake::_GetPlayer(), at_hol_hall_of_watchers::_OnTrigger(), npc_hidden_cultist::npc_hidden_cultistAI::AttackPlayer(), Corpse::BuildValuesUpdate(), npc_anachronos_quest_trigger::npc_anachronos_quest_triggerAI::CheckEventFail(), npc_lord_illidan_stormrage::npc_lord_illidan_stormrageAI::CheckEventFail(), BattlegroundWS::CheckFlagKeeperInArea(), npc_cork_gizelton::npc_cork_gizeltonAI::CheckPlayer(), npc_simon_bunny::npc_simon_bunnyAI::CheckPlayer(), GameObject::CheckRitualList(), npc_battle_at_valhalas::npc_battle_at_valhalasAI::CheckSummons(), GameObject::ClearRitualList(), npc_dragonmaw_peon::npc_dragonmaw_peonAI::CreditPlayer(), MotionTransport::DelayedTeleportTransport(), npc_eris_hevenfire::npc_eris_hevenfireAI::DoAction(), npc_chained_spirit::DoAction(), npc_ball_of_flame::npc_ball_of_flameAI::DoAction(), npc_anubarak_spike::npc_anubarak_spikeAI::DoAction(), BattlegroundIC::DoAction(), npc_midsummer_ribbon_pole_target::DoCleanupChecks(), npc_forest_frog::DoSpawnRandom(), npc_midsummer_ribbon_pole_target::DoSpewLavaChecks(), npc_clintar_spirit::npc_clintar_spiritAI::EnterEvadeMode(), npc_overlord_drakuru_betrayal::npc_overlord_drakuru_betrayalAI::EnterEvadeMode(), NPCStaveQuestAI::EvadeOnFeignDeath(), EoEDrakeEnterVehicleEvent::Execute(), VerasEnvenom::Execute(), dragonmaw_race_npc::FinishRace(), instance_stratholme::instance_stratholme_InstanceMapScript::gate_critter_delay(), Unit::GetCharmerOrOwnerPlayerOrPlayerItself(), Unit::GetDiseasesByCaster(), NPCStaveQuestAI::GetGossipPlayer(), FollowerAI::GetLeaderForFollower(), GetObjectByTypeMask(), Puppet::GetOwner(), npc_pet_gen_soul_trader_beacon::GetOwner(), npc_conversing_with_the_depths_trigger::npc_conversing_with_the_depths_triggerAI::GetPlayer(), npc_hourglass_of_eternity::npc_hourglass_of_eternityAI::GetPlayer(), GetPlayer(), npc_escortAI::GetPlayerForEscort(), boss_headless_horseman::GetRhymePlayer(), Player::GetSelectedPlayer(), GetUnit(), npc_wild_wyrm::npc_wild_wyrmAI::GetValidPlayer(), GetWorldObject(), npc_simon_bunny::npc_simon_bunnyAI::GivePunishment(), npc_simon_bunny::npc_simon_bunnyAI::GiveRewardForLevel(), npc_imprisoned_beryl_sorcerer::npc_imprisoned_beryl_sorcererAI::GotStinged(), WorldSession::HandleAcceptGrantLevel(), npc_anachronos_the_ancient::npc_anachronos_the_ancientAI::HandleAnimation(), npc_torloth_the_magnificent::npc_torloth_the_magnificentAI::HandleAnimation(), WorldSession::HandleEjectPassenger(), WorldSession::HandleEnterPlayerVehicle(), WorldSession::HandleGrantLevel(), spell_chapter2_persuasive_strike::HandleHit(), WorldSession::HandleInspectHonorStatsOpcode(), WorldSession::HandleInspectOpcode(), WorldSession::HandleLootMasterGiveOpcode(), WorldSession::HandleQueryInspectAchievements(), WorldSession::HandleQuestConfirmAccept(), WorldSession::HandleQuestgiverAcceptQuestOpcode(), WorldSession::HandleQuestPushResult(), npc_deathstalker_fearleia::JustDied(), npc_zulaman_hostage::npc_zulaman_hostageAI::JustDied(), npc_clintar_spirit::npc_clintar_spiritAI::JustDied(), npc_ice_tomb::npc_ice_tombAI::JustDied(), npc_battle_at_valhalas::npc_battle_at_valhalasAI::JustSummoned(), npc_overlord_drakuru_betrayal::npc_overlord_drakuru_betrayalAI::MoveInLineOfSight(), npc_unworthy_initiate::npc_unworthy_initiateAI::MovementInform(), npc_hive_zara_larva::MovementInform(), npc_stillpine_capitive::npc_stillpine_capitiveAI::MovementInform(), npc_valkyr_shadowguard::npc_valkyr_shadowguardAI::MovementInform(), npc_korkron_or_wildhammer::MovementInform(), npc_chained_spirit::MovementInform(), dragonmaw_race_npc::MovementInform(), spell_claw_rage_aura::OnPeriodic(), npc_doctor::npc_doctorAI::PatientDied(), BattlegroundWS::PostUpdateImpl(), npc_hidden_cultist::npc_hidden_cultistAI::PreScript(), npc_jungle_punch_target::npc_jungle_punch_targetAI::proceedCwEvent(), SmartScript::ProcessAction(), BattlegroundWS::RemoveAssaultAuras(), npc_finklestein::npc_finklesteinAI::RightClickCauldron(), boss_baroness_anastari::boss_baroness_anastariAI::SchedulePossession(), Map::ScriptsProcess(), npc_anubarak_spike::npc_anubarak_spikeAI::SelectNewTarget(), Unit::SendComboPoints(), npc_q24545_lich_king::npc_q24545_lich_kingAI::SetData(), boss_archimonde::SetGUID(), npc_bloodmage_laurith::npc_bloodmage_laurithAI::SetGUID(), Unit::SetOwnerGUID(), npc_deaths_door_fell_cannon_target_bunny::npc_deaths_door_fell_cannon_target_bunnyAI::SpellHit(), boss_flame_leviathan::boss_flame_leviathanAI::SpellHitTarget(), npc_finklestein::npc_finklesteinAI::StartNextTask(), dragonmaw_race_npc::StartRace(), dragonmaw_race_npc::StartRaceAttacks(), SmartAI::StopFollow(), npc_deathstalker_fearleia::SummonCreatureWithRandomTarget(), npc_lord_illidan_stormrage::npc_lord_illidan_stormrageAI::SummonNextWave(), GameObject::Update(), Creature::Update(), go_gilded_brazier::go_gilded_brazierAI::UpdateAI(), npc_kernobee::npc_kernobeeAI::UpdateAI(), npc_death_knight_initiate::npc_death_knight_initiateAI::UpdateAI(), npc_unworthy_initiate::npc_unworthy_initiateAI::UpdateAI(), npc_a_special_surprise::npc_a_special_surpriseAI::UpdateAI(), npc_eris_hevenfire::npc_eris_hevenfireAI::UpdateAI(), npc_bh_thalorien_dawnseeker::npc_bh_thalorien_dawnseekerAI::UpdateAI(), npc_grand_magister_rommath::npc_grand_magister_rommathAI::UpdateAI(), npc_lady_sylvanas_windrunner::npc_lady_sylvanas_windrunnerAI::UpdateAI(), npc_forest_frog::UpdateAI(), npc_winterfin_playmate::UpdateAI(), npc_snowfall_glade_playmate::UpdateAI(), npc_the_biggest_tree::UpdateAI(), npc_high_oracle_soo_roo::UpdateAI(), npc_elder_kekek::UpdateAI(), npc_the_etymidian::UpdateAI(), npc_alexstraza_the_lifebinder::UpdateAI(), npc_draenei_survivor::npc_draenei_survivorAI::UpdateAI(), npc_rabid_thistle_bear::npc_rabid_thistle_bearAI::UpdateAI(), npc_clintar_spirit::npc_clintar_spiritAI::UpdateAI(), npc_shenthul::npc_shenthulAI::UpdateAI(), npc_twiggy_flathead::npc_twiggy_flatheadAI::UpdateAI(), npc_sergeant_bly::npc_sergeant_blyAI::UpdateAI(), npc_anubarak_spike::npc_anubarak_spikeAI::UpdateAI(), npc_snobold_vassal::npc_snobold_vassalAI::UpdateAI(), boss_gormok::boss_gormokAI::UpdateAI(), boss_icehowl::boss_icehowlAI::UpdateAI(), boss_twin_valkyrAI::UpdateAI(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::UpdateAI(), npc_ice_tomb::npc_ice_tombAI::UpdateAI(), boss_maexxna::boss_maexxnaAI::UpdateAI(), npc_scion_of_eternity::npc_scion_of_eternityAI::UpdateAI(), boss_ignis::boss_ignisAI::UpdateAI(), boss_yoggsaron_voice::boss_yoggsaron_voiceAI::UpdateAI(), npc_sinkhole_kill_credit::npc_sinkhole_kill_creditAI::UpdateAI(), npc_beryl_sorcerer::npc_beryl_sorcererAI::UpdateAI(), npc_hidden_cultist::npc_hidden_cultistAI::UpdateAI(), npc_bloodmage_laurith::npc_bloodmage_laurithAI::UpdateAI(), npc_minigob_manabonk::UpdateAI(), npc_q24545_lich_king::npc_q24545_lich_kingAI::UpdateAI(), npc_venture_co_straggler::npc_venture_co_stragglerAI::UpdateAI(), npc_battle_at_valhalas::npc_battle_at_valhalasAI::UpdateAI(), npc_wild_wyrm::npc_wild_wyrmAI::UpdateAI(), npc_overlord_drakuru_betrayal::npc_overlord_drakuru_betrayalAI::UpdateAI(), npc_oscillating_frequency_scanner_master_bunny::npc_oscillating_frequency_scanner_master_bunnyAI::UpdateAI(), npc_magister_aledis::UpdateAI(), npc_commander_dawnforge::npc_commander_dawnforgeAI::UpdateAI(), npc_mature_netherwing_drake::npc_mature_netherwing_drakeAI::UpdateAI(), npc_pet_gen_imp_in_a_bottle::UpdateAI(), npc_magwin::npc_magwinAI::UpdateEscortAI(), GameObject::Use(), and npc_cork_gizelton::npc_cork_gizeltonAI::WaypointReached().
GetPlayer() [2/2]
Player * ObjectAccessor::GetPlayer (WorldObject const & u, ObjectGuid const & guid)
{
    return GetPlayer(u.GetMap(), guid);
}
References WorldObject::GetMap(), and GetPlayer().
GetPlayers()
HashMapHolder< Player >::MapType const & ObjectAccessor::GetPlayers ()
{
    return HashMapHolder<Player>::GetContainer();
}
References HashMapHolder< T >::GetContainer().
Referenced by WorldSessionMgr::DoForAllOnlinePlayers(), deserter_commandscript::HandleDeserterRemoveAll(), gm_commandscript::HandleGMListIngameCommand(), misc_commandscript::HandleMuteCommand(), SaveAllPlayers(), and WhoListCacheMgr::Update().
GetSpawnedCreatureByDBGUID()
Creature * ObjectAccessor::GetSpawnedCreatureByDBGUID (uint32 mapId, uint64 guid)
Get a spawned creature by DB guid column. MODULE USAGE ONLY - USE IT FOR CUSTOM CONTENT.
Parameters
uint32 mapId The map id where the creature is spawned.
uint64 guid Database guid of the creature we are accessing.
{
    if (Map* map = sMapMgr->FindBaseMap(mapId))
    {
        auto bounds = map->GetCreatureBySpawnIdStore().equal_range(guid);
        if (bounds.first == bounds.second)
        {
            return nullptr;
        }
        if (Creature* creature = bounds.first->second)
        {
            return creature;
        }
    }
    return nullptr;
}
References sMapMgr.
GetSpawnedGameObjectByDBGUID()
GameObject * ObjectAccessor::GetSpawnedGameObjectByDBGUID (uint32 mapId, uint64 guid)
Get a spawned gameobject by DB guid column. MODULE USAGE ONLY - USE IT FOR CUSTOM CONTENT.
Parameters
uint32 mapId The map id where the gameobject is spawned.
uint64 guid Database guid of the gameobject we are accessing.
{
    if (Map* map = sMapMgr->FindBaseMap(mapId))
    {
        auto bounds = map->GetGameObjectBySpawnIdStore().equal_range(guid);
        if (bounds.first == bounds.second)
        {
            return nullptr;
        }
        if (GameObject* go = bounds.first->second)
        {
            return go;
        }
    }
    return nullptr;
}
References sMapMgr.
GetTransport()
Transport * ObjectAccessor::GetTransport (WorldObject const & u, ObjectGuid const & guid)
{
    return u.GetMap()->GetTransport(guid);
}
References WorldObject::GetMap(), and Map::GetTransport().
Referenced by ResetEncounterEvent::Execute().
GetUnit()
Unit * ObjectAccessor::GetUnit (WorldObject const & u, ObjectGuid const & guid)
{
    if (guid.IsPlayer())
        return GetPlayer(u, guid);
    if (guid.IsPet())
        return GetPet(u, guid);
    return GetCreature(u, guid);
}
References GetCreature(), GetPet(), GetPlayer(), ObjectGuid::IsPet(), and ObjectGuid::IsPlayer().
Referenced by Vehicle::AddPassenger(), DynamicObject::BindToCaster(), Spell::cancel(), npc_hallows_end_soh::CastFires(), boss_mor_grayhoof::CastRandomSpell(), SmartAI::CheckConditions(), VehicleAI::CheckConditions(), Aura::Create(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::DamageTaken(), Spell::DelayedChannel(), UnitAI::DoAddAuraToAllHostilePlayers(), Spell::DoAllEffectOnLaunchTarget(), Spell::DoAllEffectOnTarget(), UnitAI::DoCastToAllHostilePlayers(), PointMovementGenerator< T >::DoFinalize(), Spell::EffectJumpDest(), Spell::EffectPersistentAA(), boss_faction_championsAI::EnemiesInRange(), boss_malchezaar::EnfeebleResetHealth(), SmartAI::EnterEvadeMode(), AssistDelayEvent::Execute(), TemporaryThreatModifierEvent::Execute(), RedirectSpellEvent::Execute(), ReflectEvent::Execute(), AuraMunchingQueue::Execute(), spell_eoe_ph3_surge_of_power::FilterTargets(), spell_putricide_mutated_transformation_dmg::FilterTargetsInitial(), boss_supremus::FindHatefulStrikeTarget(), npc_hallows_end_soh::FinishEvent(), Aura::GetCaster(), Unit::GetCharm(), Unit::GetCharmer(), Unit::GetFirstControlled(), Minion::GetOwner(), GameObject::GetOwner(), Unit::GetOwner(), Vehicle::GetPassenger(), FleeingMovementGenerator< T >::GetPoint(), Unit::GetRedirectThreatTarget(), ChatHandler::getSelectedObject(), Player::GetSelectedUnit(), npc_dark_iron_guzzler::GetTarget(), SmartScript::GetTargets(), spell_dk_scourge_strike::HandleAfterHit(), WorldSession::HandleAttackSwingOpcode(), WorldSession::HandleChangeSeatsOnControlledVehicle(), spell_item_gnomish_death_ray::HandleDummy(), spell_rog_killing_spree_aura::HandleEffectPeriodic(), WorldSession::HandleEjectPassenger(), WorldSession::HandleFarSightOpcode(), gobject_commandscript::HandleGameObjectDeleteCommand(), WorldSession::HandleMirrorImageDataRequest(), WorldSession::HandlePetAction(), WorldSession::HandlePetActionHelper(), WorldSession::HandlePetCastSpellOpcode(), WorldSession::HandlePetSetAction(), spell_item_lil_phylactery::HandleProc(), spell_gen_proc_not_self::HandleProc(), spell_rog_blade_flurry::HandleProc(), spell_kaelthas_nether_beam::HandleScriptEffect(), WorldSession::HandleSetSelectionOpcode(), WorldSession::HandleTextEmoteOpcode(), Spell::HandleThreatSpells(), WorldSession::HandleUpdateMissileTrajectory(), WorldSession::HandleUpdateProjectilePosition(), Spell::InitExplicitTargets(), Totem::InitStats(), NPCStaveQuestAI::IsFairFight(), npc_tiger_matriarch::npc_tiger_matriarchAI::IsSummonedBy(), boss_sapphiron::boss_sapphironAI::IsValidExplosionTarget(), Vehicle::IsVehicleInUse(), npc_kilrek::JustDied(), npc_demon_chain::JustDied(), npc_zulian_prowler::npc_zulian_prowlerAI::JustDied(), npc_eye_tentacle::JustDied(), npc_claw_tentacle::JustDied(), npc_giant_claw_tentacle::JustDied(), npc_giant_eye_tentacle::JustDied(), npc_snobold_vassal::npc_snobold_vassalAI::JustDied(), boss_maexxna_webwrap::boss_maexxna_webwrapAI::JustDied(), boss_freya_iron_root::boss_freya_iron_rootAI::JustDied(), boss_yoggsaron_constrictor_tentacle::boss_yoggsaron_constrictor_tentacleAI::JustDied(), npc_stolen_soul::JustDied(), npc_inner_demon::JustDied(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::JustDied(), npc_frost_tomb::JustDied(), npc_healing_ward::JustEngagedWith(), npc_obsidian_eradicator::JustEngagedWith(), npc_obsidian_nullifier::JustEngagedWith(), boss_blackheart_the_inciter::JustEngagedWith(), boss_swamplord_muselek::JustEngagedWith(), boss_gal_darah::JustSummoned(), npc_akilzon_eagle::MovementInform(), npc_pet_mage_mirror_image::MySelectNextTarget(), boss_razorgore::boss_razorgoreAI::OnCharmed(), npc_chesspiece::OnCharmed(), spell_yogg_saron_brain_link_aura::OnPeriodic(), AbominationDespawner::operator()(), Unit::OutDebugInfo(), boss_chromaggus::boss_chromaggusAI::PathEndReached(), SmartScript::ProcessAction(), SmartScript::ProcessEvent(), ThreatMgr::processThreatEvent(), boss_priestess_lackey_commonAI::RecalculateThreat(), boss_faction_championsAI::RecalculateThreat(), Vehicle::RelocatePassengers(), DynamicObject::RemoveCasterViewpoint(), Unit::RemoveCharmedBy(), GameObject::RemoveFromOwner(), npc_pet_dk_ebon_gargoyle::RemoveTargetAura(), npc_zulian_prowler::npc_zulian_prowlerAI::Reset(), boss_faction_championsAI::SelectEnemyCaster(), Spell::SelectImplicitAreaTargets(), npc_scholomance_occultist::npc_scholomance_occultistAI::SelectUnitCasting(), DynamicObject::SetCasterViewpoint(), Unit::SetControlled(), boss_shade_of_aran::SetGUID(), boss_mandokir::boss_mandokirAI::SetGUID(), Unit::SetSpeed(), Spell::Spell(), boss_akilzon::SummonEagles(), CreatureAI::Talk(), Vehicle::TeleportVehicle(), npc_commander_dawnforge::npc_commander_dawnforgeAI::Turn_to_eachother(), Pet::Update(), GameObject::Update(), Unit::Update(), TotemAI::UpdateAI(), npc_rocknot::npc_rocknotAI::UpdateAI(), boss_drakkisath::boss_drakkisathAI::UpdateAI(), boss_vaelastrasz::boss_vaelAI::UpdateAI(), npc_image_of_medivh::npc_image_of_medivhAI::UpdateAI(), npc_balance_of_light_and_shadow::npc_balance_of_light_and_shadowAI::UpdateAI(), boss_arlokk::boss_arlokkAI::UpdateAI(), boss_grilek::boss_grilekAI::UpdateAI(), boss_renataki::boss_renatakiAI::UpdateAI(), npc_hallows_end_soh::UpdateAI(), npc_tiger_matriarch::npc_tiger_matriarchAI::UpdateAI(), npc_toc5_grand_champion_minion::npc_toc5_grand_champion_minionAI::UpdateAI(), boss_grand_champion::boss_grand_championAI::UpdateAI(), npc_snobold_vassal::npc_snobold_vassalAI::UpdateAI(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::UpdateAI(), npc_putricide_oozeAI::UpdateAI(), npc_icc_ice_sphere::npc_icc_ice_sphereAI::UpdateAI(), boss_sapphiron::boss_sapphironAI::UpdateAI(), boss_stormcaller_brundir::boss_stormcaller_brundirAI::UpdateAI(), npc_wg_siege_machine::npc_wg_siege_machineAI::UpdateAI(), boss_the_lurker_below::UpdateAI(), npc_invis_infernal_caster::npc_invis_infernal_casterAI::UpdateAI(), npc_mature_netherwing_drake::npc_mature_netherwing_drakeAI::UpdateAI(), guard_shattrath_scryer::guard_shattrath_scryerAI::UpdateAI(), guard_shattrath_aldor::guard_shattrath_aldorAI::UpdateAI(), npc_garments_of_quests::npc_garments_of_questsAI::UpdateAI(), npc_spring_rabbit::npc_spring_rabbitAI::UpdateAI(), PetAI::UpdateAI(), boss_maexxna_webwrap::boss_maexxna_webwrapAI::UpdateAI(), npc_frost_tomb::UpdateAI(), Spell::UpdateChanneledTargetList(), HostileReference::updateOnlineStatus(), Spell::UpdatePointers(), boss_netherspite::UpdatePortals(), and Vehicle::~Vehicle().
GetWorldObject()
WorldObject * ObjectAccessor::GetWorldObject (WorldObject const & p, ObjectGuid const & guid)
{
    switch (guid.GetHigh())
    {
        case HighGuid::Player:
            return GetPlayer(p, guid);
        case HighGuid::Transport:
        case HighGuid::Mo_Transport:
        case HighGuid::GameObject:
            return GetGameObject(p, guid);
        case HighGuid::Vehicle:
        case HighGuid::Unit:
            return GetCreature(p, guid);
        case HighGuid::Pet:
            return GetPet(p, guid);
        case HighGuid::DynamicObject:
            return GetDynamicObject(p, guid);
        case HighGuid::Corpse:
            return GetCorpse(p, guid);
        default:
            return nullptr;
    }
    return nullptr;
}
References Corpse, DynamicObject, GameObject, GetCorpse(), GetCreature(), GetDynamicObject(), GetGameObject(), ObjectGuid::GetHigh(), GetPet(), GetPlayer(), Mo_Transport, Pet, Player, Transport, Unit, and Vehicle.
Referenced by Unit::_UpdateSpells(), SummonList::DoForAllSummons(), SmartScript::GetLastInvoker(), SpellCastTargets::GetObjectTargetChannel(), TempSummon::GetSummoner(), SmartScript::GetTargets(), AuraEffect::PeriodicTick(), SpellCastTargets::Update(), ObjectGuidVector::UpdateObjects(), and Spell::UpdatePointers().
RemoveObject() [1/2]
template<> void ObjectAccessor::RemoveObject (Player * player)
{
    HashMapHolder<Player>::Remove(player);
    PlayerNameMapHolder::Remove(player);
}
References PlayerNameMapHolder::Remove(), and HashMapHolder< T >::Remove().
RemoveObject() [2/2]
template<class T > void ObjectAccessor::RemoveObject (T * object)
    {
        HashMapHolder<T>::Remove(object);
    }
References HashMapHolder< T >::Remove().
Referenced by Map::DeleteFromWorld().
SaveAllPlayers()
void ObjectAccessor::SaveAllPlayers ()
{
    std::shared_lock<std::shared_mutex> lock(*HashMapHolder<Player>::GetLock());
    HashMapHolder<Player>::MapType const& m = GetPlayers();
    for (HashMapHolder<Player>::MapType::const_iterator itr = m.begin(); itr != m.end(); ++itr)
        itr->second->SaveToDB(false, false);
}
References GetPlayers().
Referenced by misc_commandscript::HandleSaveAllCommand().
UpdatePlayerNameMapReference()
void ObjectAccessor::UpdatePlayerNameMapReference (std::string oldname, Player * player)
{
    PlayerNameMapHolder::RemoveByName(oldname);
    PlayerNameMapHolder::Insert(player);
}
References PlayerNameMapHolder::Insert(), and PlayerNameMapHolder::RemoveByName().
Referenced by character_commandscript::HandleCharacterRenameCommand().