AzerothCore Doxygen
ProcTestContext Class Reference
Context for a proc test scenario.
#include "AuraScriptTestFramework.h"
Public Member Functions
ProcTestContext ()=default
UnitStub & GetActor ()
UnitStub const & GetActor () const
UnitStub & GetTarget ()
UnitStub const & GetTarget () const
AuraStub & GetAura ()
AuraStub const & GetAura () const
DamageInfoStub & GetDamageInfo ()
DamageInfoStub const & GetDamageInfo () const
HealInfoStub & GetHealInfo ()
HealInfoStub const & GetHealInfo () const
ProcTestContext & WithAuraId (uint32_t auraId)
ProcTestContext & WithAuraSpellFamily (uint32_t familyName)
ProcTestContext & WithAuraCharges (uint8_t charges)
ProcTestContext & WithActorAsPlayer (bool isPlayer=true)
ProcTestContext & WithDamage (uint32_t damage, uint32_t schoolMask=1)
ProcTestContext & WithHeal (uint32_t heal, uint32_t effectiveHeal=0)
ProcTestContext & WithCriticalHit ()
ProcTestContext & WithNormalHit ()
Private Attributes
UnitStub _actor
UnitStub _target
AuraStub _aura
DamageInfoStub _damageInfo
HealInfoStub _healInfo
Detailed Description
Context for a proc test scenario.
Constructor & Destructor Documentation
ProcTestContext()
ProcTestContext::ProcTestContext () default
Member Function Documentation
GetActor() [1/2]
UnitStub & ProcTestContext::GetActor () inline
{ return _actor; }
References _actor.
GetActor() [2/2]
UnitStub const & ProcTestContext::GetActor () const inline
{ return _actor; }
References _actor.
GetAura() [1/2]
AuraStub & ProcTestContext::GetAura () inline
{ return _aura; }
References _aura.
GetAura() [2/2]
AuraStub const & ProcTestContext::GetAura () const inline
{ return _aura; }
References _aura.
GetDamageInfo() [1/2]
DamageInfoStub & ProcTestContext::GetDamageInfo () inline
{ return _damageInfo; }
References _damageInfo.
GetDamageInfo() [2/2]
DamageInfoStub const & ProcTestContext::GetDamageInfo () const inline
{ return _damageInfo; }
References _damageInfo.
GetHealInfo() [1/2]
HealInfoStub & ProcTestContext::GetHealInfo () inline
{ return _healInfo; }
References _healInfo.
GetHealInfo() [2/2]
HealInfoStub const & ProcTestContext::GetHealInfo () const inline
{ return _healInfo; }
References _healInfo.
GetTarget() [1/2]
UnitStub & ProcTestContext::GetTarget () inline
{ return _target; }
References _target.
GetTarget() [2/2]
UnitStub const & ProcTestContext::GetTarget () const inline
{ return _target; }
References _target.
WithActorAsPlayer()
ProcTestContext & ProcTestContext::WithActorAsPlayer (bool isPlayer = true) inline
    {
        _actor.SetIsPlayer(isPlayer);
        return *this;
    }
References _actor, and UnitStub::SetIsPlayer().
WithAuraCharges()
ProcTestContext & ProcTestContext::WithAuraCharges (uint8_t charges) inline
    {
        _aura.SetCharges(charges);
        _aura.SetUsingCharges(charges > 0);
        return *this;
    }
References _aura, AuraStub::SetCharges(), and AuraStub::SetUsingCharges().
WithAuraId()
ProcTestContext & ProcTestContext::WithAuraId (uint32_t auraId) inline
    {
        _aura.SetId(auraId);
        return *this;
    }
References _aura, and AuraStub::SetId().
WithAuraSpellFamily()
ProcTestContext & ProcTestContext::WithAuraSpellFamily (uint32_t familyName) inline
    {
        _aura.SetSpellFamilyName(familyName);
        return *this;
    }
References _aura, and AuraStub::SetSpellFamilyName().
WithCriticalHit()
ProcTestContext & ProcTestContext::WithCriticalHit () inline
    {
        _damageInfo.SetHitMask(PROC_HIT_CRITICAL);
        _healInfo.SetHitMask(PROC_HIT_CRITICAL);
        return *this;
    }
References _damageInfo, _healInfo, PROC_HIT_CRITICAL, DamageInfoStub::SetHitMask(), and HealInfoStub::SetHitMask().
WithDamage()
ProcTestContext & ProcTestContext::WithDamage (uint32_t damage, uint32_t schoolMask = 1) inline
    {
        _damageInfo.SetDamage(damage);
        _damageInfo.SetOriginalDamage(damage);
        _damageInfo.SetSchoolMask(schoolMask);
        return *this;
    }
References _damageInfo, DamageInfoStub::SetDamage(), DamageInfoStub::SetOriginalDamage(), and DamageInfoStub::SetSchoolMask().
WithHeal()
ProcTestContext & ProcTestContext::WithHeal (uint32_t heal, uint32_t effectiveHeal = 0) inline
    {
        _healInfo.SetHeal(heal);
        _healInfo.SetEffectiveHeal(effectiveHeal > 0 ? effectiveHeal : heal);
        return *this;
    }
References _healInfo, HealInfoStub::SetEffectiveHeal(), and HealInfoStub::SetHeal().
WithNormalHit()
ProcTestContext & ProcTestContext::WithNormalHit () inline
    {
        _damageInfo.SetHitMask(PROC_HIT_NORMAL);
        _healInfo.SetHitMask(PROC_HIT_NORMAL);
        return *this;
    }
References _damageInfo, _healInfo, PROC_HIT_NORMAL, DamageInfoStub::SetHitMask(), and HealInfoStub::SetHitMask().
Member Data Documentation
_actor
UnitStub ProcTestContext::_actor private
Referenced by GetActor(), GetActor(), and WithActorAsPlayer().
_aura
AuraStub ProcTestContext::_aura private
Referenced by GetAura(), GetAura(), WithAuraCharges(), WithAuraId(), and WithAuraSpellFamily().
_damageInfo
DamageInfoStub ProcTestContext::_damageInfo private
Referenced by GetDamageInfo(), GetDamageInfo(), WithCriticalHit(), WithDamage(), and WithNormalHit().
_healInfo
HealInfoStub ProcTestContext::_healInfo private
Referenced by GetHealInfo(), GetHealInfo(), WithCriticalHit(), WithHeal(), and WithNormalHit().
_target
UnitStub ProcTestContext::_target private
Referenced by GetTarget(), and GetTarget().
The documentation for this class was generated from the following file:
azerothcore-wotlk/src/test/mocks/AuraScriptTestFramework.h