AzerothCore Doxygen
AuraMunchingQueue Class Reference
Public Member Functions
AuraMunchingQueue (Unit &owner, ObjectGuid targetGUID, int32 basePoints, uint32 spellId, AuraEffect *aurEff, AuraType auraType)
bool Execute (uint64, uint32) override
Public Member Functions inherited from BasicEvent
BasicEvent ()=default
virtual ~BasicEvent ()=default
virtual bool IsDeletable () const
virtual void Abort (uint64)
void ScheduleAbort ()
Private Attributes
Unit & _owner
ObjectGuid _targetGUID
int32 _basePoints
uint32 _spellId
AuraEffect * _aurEff
AuraType _auraType
Detailed Description
Constructor & Destructor Documentation
AuraMunchingQueue()
AuraMunchingQueue::AuraMunchingQueue (Unit & owner, ObjectGuid targetGUID, int32 basePoints, uint32 spellId, AuraEffect * aurEff, AuraType auraType) inline
: _owner(owner), _targetGUID(targetGUID), _basePoints(basePoints), _spellId(spellId), _aurEff(aurEff), _auraType(auraType) { }
Member Function Documentation
Execute()
bool AuraMunchingQueue::Execute (uint64 , uint32) inline override virtual
Reimplemented from BasicEvent.
    {
        if (_owner.IsInWorld() && _owner.FindMap())
            if (Unit* target = ObjectAccessor::GetUnit(_owner, _targetGUID))
            {
                bool auraFound = false; // Used to ensure _aurEff exists to avoid wild pointer access/crash
                Unit::AuraEffectList const& auraEffects = target->GetAuraEffectsByType(_auraType);
                for (Unit::AuraEffectList::const_iterator j = auraEffects.begin(); j != auraEffects.end(); ++j)
                    if ((*j) == _aurEff)
                        auraFound = true;
                if (!auraFound)
                    _aurEff = nullptr;
                _owner.CastCustomSpell(_spellId, SPELLVALUE_BASE_POINT0, _basePoints, target, TriggerCastFlags(TRIGGERED_FULL_MASK & ~TRIGGERED_NO_PERIODIC_RESET), nullptr, _aurEff, _owner.GetGUID());
            }
        return true;
    }
References _auraType, _aurEff, _basePoints, _owner, _spellId, _targetGUID, Unit::CastCustomSpell(), WorldObject::FindMap(), Object::GetGUID(), ObjectAccessor::GetUnit(), Object::IsInWorld(), SPELLVALUE_BASE_POINT0, TRIGGERED_FULL_MASK, and TRIGGERED_NO_PERIODIC_RESET.
Member Data Documentation
_auraType
AuraType AuraMunchingQueue::_auraType private
Referenced by Execute().
_aurEff
AuraEffect* AuraMunchingQueue::_aurEff private
Referenced by Execute().
_basePoints
int32 AuraMunchingQueue::_basePoints private
Referenced by Execute().
_owner
Unit& AuraMunchingQueue::_owner private
Referenced by Execute().
_spellId
uint32 AuraMunchingQueue::_spellId private
Referenced by Execute().
_targetGUID
ObjectGuid AuraMunchingQueue::_targetGUID private
Referenced by Execute().
The documentation for this class was generated from the following file:
azerothcore-wotlk/src/server/game/Entities/Unit/Unit.cpp