AzerothCore Doxygen
RangeSelector Struct Reference
#include "UnitAI.h"
Public Member Functions
RangeSelector (Unit const *unit, float maxDist, bool playerOnly, bool inLos, float minDist=0.f)
bool operator() (Unit const *target) const
Private Attributes
Unit const * _me
float _minDist
float _maxDist
bool _playerOnly
bool _inLos
Additional Inherited Members
Public Types inherited from Acore::unary_function< Unit *, bool >
typedef Unit * argument_type
typedef bool result_type
Detailed Description
Constructor & Destructor Documentation
RangeSelector()
RangeSelector::RangeSelector (Unit const * unit, float maxDist, bool playerOnly, bool inLos, float minDist = 0.f) inline
: _me(unit), _minDist(minDist), _maxDist(maxDist), _playerOnly(playerOnly), _inLos(inLos) {}
Member Function Documentation
operator()()
bool RangeSelector::operator() (Unit const * target) const inline
    {
        if (!_me || !target)
            return false;
        if (_playerOnly && !target->IsPlayer())
            return false;
        if (_maxDist > 0.0f && !_me->IsInRange(target, _minDist, _maxDist))
            return false;
        if (_inLos && !_me->IsWithinLOSInMap(target))
            return false;
        return true;
    }
References _inLos, _maxDist, _me, _minDist, _playerOnly, WorldObject::IsInRange(), Object::IsPlayer(), and WorldObject::IsWithinLOSInMap().
Member Data Documentation
_inLos
bool RangeSelector::_inLos private
Referenced by operator()().
_maxDist
float RangeSelector::_maxDist private
Referenced by operator()().
_me
Unit const* RangeSelector::_me private
Referenced by operator()().
_minDist
float RangeSelector::_minDist private
Referenced by operator()().
_playerOnly
bool RangeSelector::_playerOnly private
Referenced by operator()().
The documentation for this struct was generated from the following file:
azerothcore-wotlk/src/server/game/AI/CoreAI/UnitAI.h