AzerothCore Doxygen
zulaman.cpp File Reference
#include "CreatureScript.h"
#include "PassiveAI.h"
#include "Player.h"
#include "ScriptedCreature.h"
#include "ScriptedGossip.h"
#include "SpellAuraEffects.h"
#include "SpellInfo.h"
#include "SpellScript.h"
#include "SpellScriptLoader.h"
#include "zulaman.h"
Classes
struct npc_forest_frog
class npc_zulaman_hostage
struct npc_zulaman_hostage::npc_zulaman_hostageAI
struct npc_harrison_jones
class spell_ritual_of_power
struct npc_amanishi_lookout
struct npc_eagle_trash_aggro_trigger
struct npc_amanishi_tempest
struct npc_amanishi_scout
class spell_alert_drums
class spell_summon_amanishi_sentries
class spell_call_of_the_beast
Macros
#define GOSSIP_HOSTAGE1 "I am glad to help you."
Enumerations
enum ForestFrog {
SPELL_REMOVE_AMANI_CURSE = 43732 ,
SPELL_PUSH_MOJO = 43923 ,
SPELL_SUMMON_AMANI_CHARM_CHEST_1 = 43835 ,
SPELL_SUMMON_AMANI_CHARM_CHEST_2 = 43756 ,
SPELL_SUMMON_MONEY_BAG = 43774 ,
SPELL_STEALTH_ = 34189 ,
SPELL_FIXATE = 43360 ,
NPC_FOREST_FROG = 24396 ,
NPC_MANNUTH = 24397 ,
NPC_DEEZ = 24403 ,
NPC_GALATHRYN = 24404 ,
NPC_ADARRAH = 24405 ,
NPC_FUDGERICK = 24406 ,
NPC_DARWEN = 24407 ,
NPC_GUNTER = 24408 ,
NPC_KYREN = 24409 ,
NPC_MITZI = 24445 ,
NPC_CHRISTIAN = 24448 ,
NPC_BRENNAN = 24453 ,
NPC_HOLLEE = 24455 ,
SAY_THANKS_FREED = 0 ,
SAY_CHEST_SPAWN = 1 ,
SAY_CHEST_TALK = 2 ,
SAY_GOODBYE = 3 ,
POINT_DESPAWN = 1
}
enum Says {
SAY_HARRISON_0 = 0 ,
SAY_HARRISON_1 = 1 ,
SAY_HARRISON_2 = 0 ,
SAY_HARRISON_3 = 1
}
enum Spells {
SPELL_BANGING_THE_GONG = 45225 ,
SPELL_STEALTH = 34189 ,
SPELL_COSMETIC_SPEAR_THROW = 43647
}
enum Phases {
PHASE_GONG = 0 ,
PHASE_GATE_CLOSED = 1 ,
PHASE_GATE_OPENED = 2
}
enum Actions { ACTION_COMPLETE_GONG_RITUAL = 0 }
enum Waypoints {
HARRISON_MOVE_1 = 2435800 ,
HARRISON_MOVE_2 = 2435801 ,
HARRISON_MOVE_3 = 2435802
}
enum DisplayIds {
MODEL_HARRISON_JONES_0 = 22340 ,
MODEL_HARRISON_JONES_1 = 22354 ,
MODEL_HARRISON_JONES_2 = 22347
}
enum EntryIds {
NPC_HARRISON_JONES_1 = 24375 ,
NPC_HARRISON_JONES_2 = 24365
}
enum Weapons {
WEAPON_MACE = 5301 ,
WEAPON_SPEAR = 13631
}
enum AmanishiLookout {
PATH_LOOKOUT = 2417500 ,
SAY_INVADERS = 0
}
enum AmanishiTempest {
GROUP_AKILZON_GAUNTLET = 1 ,
SPELL_SUMMON_EAGLE = 43487 ,
SPELL_SUMMON_WARRIOR = 43486 ,
SPELL_THUNDERCLAP = 44033
}
enum AmanishiScout {
NPC_WORLD_TRIGGER = 22515 ,
SAY_AGGRO = 0 ,
SPELL_ALERT_DRUMS = 42177 ,
SPELL_MULTI_SHOT = 43205 ,
SPELL_SHOOT = 16496
}
enum SpellAlertDrums { SPELL_SUMMON_AMANISHI_SENTRIES = 42179 }
enum AmanishiSentries {
SUMMON_AMANISHI_SENTRIES_1 = 42180 ,
SUMMON_AMANISHI_SENTRIES_2 = 42181 ,
SUMMON_AMANISHI_SENTRIES_3 = 42182 ,
SUMMON_AMANISHI_SENTRIES_4 = 42183
}
Functions
bool IsHut (Creature *trigger)
bool IsDrum (Creature *trigger)
void AddSC_zulaman ()
Variables
static uint32 HostageEntry [] = {23790, 23999, 24024, 24001}
static uint32 ChestEntry [] = {186648, 187021, 186667, 186672}
Macro Definition Documentation
GOSSIP_HOSTAGE1
#define GOSSIP_HOSTAGE1 "I am glad to help you."
Enumeration Type Documentation
Actions
enum Actions
Enumerator
ACTION_COMPLETE_GONG_RITUAL
{
    ACTION_COMPLETE_GONG_RITUAL        = 0
};
AmanishiLookout
enum AmanishiLookout
Enumerator
PATH_LOOKOUT
SAY_INVADERS
{
    PATH_LOOKOUT       = 2417500,
    SAY_INVADERS       = 0,
};
AmanishiScout
enum AmanishiScout
Enumerator
NPC_WORLD_TRIGGER
SAY_AGGRO
SPELL_ALERT_DRUMS
SPELL_MULTI_SHOT
SPELL_SHOOT
{
    NPC_WORLD_TRIGGER               = 22515,
    SAY_AGGRO                       = 0,
    SPELL_ALERT_DRUMS               = 42177,
    SPELL_MULTI_SHOT                = 43205,
    SPELL_SHOOT                     = 16496
};
AmanishiSentries
enum AmanishiSentries
Enumerator
SUMMON_AMANISHI_SENTRIES_1
SUMMON_AMANISHI_SENTRIES_2
SUMMON_AMANISHI_SENTRIES_3
SUMMON_AMANISHI_SENTRIES_4
{
    SUMMON_AMANISHI_SENTRIES_1 = 42180,
    SUMMON_AMANISHI_SENTRIES_2 = 42181,
    SUMMON_AMANISHI_SENTRIES_3 = 42182,
    SUMMON_AMANISHI_SENTRIES_4 = 42183,
};
AmanishiTempest
enum AmanishiTempest
Enumerator
GROUP_AKILZON_GAUNTLET
SPELL_SUMMON_EAGLE
SPELL_SUMMON_WARRIOR
SPELL_THUNDERCLAP
{
    GROUP_AKILZON_GAUNTLET  = 1,
    SPELL_SUMMON_EAGLE      = 43487,
    SPELL_SUMMON_WARRIOR    = 43486,
    SPELL_THUNDERCLAP       = 44033,
};
DisplayIds
enum DisplayIds
Enumerator
MODEL_HARRISON_JONES_0
MODEL_HARRISON_JONES_1
MODEL_HARRISON_JONES_2
{
    MODEL_HARRISON_JONES_0              = 22340,
    MODEL_HARRISON_JONES_1              = 22354,
    MODEL_HARRISON_JONES_2              = 22347
};
EntryIds
enum EntryIds
Enumerator
NPC_HARRISON_JONES_1
NPC_HARRISON_JONES_2
{
    NPC_HARRISON_JONES_1                = 24375,
    NPC_HARRISON_JONES_2                = 24365
};
ForestFrog
enum ForestFrog
Enumerator
SPELL_REMOVE_AMANI_CURSE
SPELL_PUSH_MOJO
SPELL_SUMMON_AMANI_CHARM_CHEST_1
SPELL_SUMMON_AMANI_CHARM_CHEST_2
SPELL_SUMMON_MONEY_BAG
SPELL_STEALTH_
SPELL_FIXATE
NPC_FOREST_FROG
NPC_MANNUTH
NPC_DEEZ
NPC_GALATHRYN
NPC_ADARRAH
NPC_FUDGERICK
NPC_DARWEN
NPC_GUNTER
NPC_KYREN
NPC_MITZI
NPC_CHRISTIAN
NPC_BRENNAN
NPC_HOLLEE
SAY_THANKS_FREED
SAY_CHEST_SPAWN
SAY_CHEST_TALK
SAY_GOODBYE
POINT_DESPAWN
{
    // Spells
    SPELL_REMOVE_AMANI_CURSE          = 43732,
    SPELL_PUSH_MOJO                   = 43923,
    SPELL_SUMMON_AMANI_CHARM_CHEST_1  = 43835, // Amani Treasure Box (186744)
    SPELL_SUMMON_AMANI_CHARM_CHEST_2  = 43756, // Amani Charm Box (186734)
    SPELL_SUMMON_MONEY_BAG            = 43774, // Money Bag (186736)
    SPELL_STEALTH_                    = 34189,
    SPELL_FIXATE                      = 43360,
    // Creatures
    NPC_FOREST_FROG                   = 24396,
    NPC_MANNUTH                       = 24397,
    NPC_DEEZ                          = 24403,
    NPC_GALATHRYN                     = 24404,
    NPC_ADARRAH                       = 24405,
    NPC_FUDGERICK                     = 24406,
    NPC_DARWEN                        = 24407,
    NPC_GUNTER                        = 24408,
    NPC_KYREN                         = 24409,
    NPC_MITZI                         = 24445,
    NPC_CHRISTIAN                     = 24448,
    NPC_BRENNAN                       = 24453,
    NPC_HOLLEE                        = 24455,
    // Adarrah is spawned elsewhere.
    // So her text 0 isn't used in this instance.
    SAY_THANKS_FREED                  = 0,
    SAY_CHEST_SPAWN                   = 1,
    SAY_CHEST_TALK                    = 2,
    SAY_GOODBYE                       = 3,
    POINT_DESPAWN                     = 1,
};
Phases
enum Phases
Enumerator
PHASE_GONG
PHASE_GATE_CLOSED
PHASE_GATE_OPENED
{
    PHASE_GONG                         = 0,
    PHASE_GATE_CLOSED                  = 1,
    PHASE_GATE_OPENED                  = 2
};
Says
enum Says
Enumerator
SAY_HARRISON_0
SAY_HARRISON_1
SAY_HARRISON_2
SAY_HARRISON_3
{
    SAY_HARRISON_0                    = 0,
    SAY_HARRISON_1                    = 1,
    SAY_HARRISON_2                    = 0,
    SAY_HARRISON_3                    = 1
};
SpellAlertDrums
enum SpellAlertDrums
Enumerator
SPELL_SUMMON_AMANISHI_SENTRIES
{
    SPELL_SUMMON_AMANISHI_SENTRIES  = 42179
};
Spells
enum Spells
Enumerator
SPELL_BANGING_THE_GONG
SPELL_STEALTH
SPELL_COSMETIC_SPEAR_THROW
{
    SPELL_BANGING_THE_GONG            = 45225,
    SPELL_STEALTH                     = 34189,
    SPELL_COSMETIC_SPEAR_THROW        = 43647
};
Waypoints
enum Waypoints
Enumerator
HARRISON_MOVE_1
HARRISON_MOVE_2
HARRISON_MOVE_3
{
    HARRISON_MOVE_1                     = 2435800,
    HARRISON_MOVE_2                     = 2435801,
    HARRISON_MOVE_3                     = 2435802
};
Weapons
enum Weapons
Enumerator
WEAPON_MACE
WEAPON_SPEAR
{
    WEAPON_MACE                         = 5301,
    WEAPON_SPEAR                        = 13631
};
Function Documentation
AddSC_zulaman()
void AddSC_zulaman ()
{
    RegisterZulAmanCreatureAI(npc_forest_frog);
    new npc_zulaman_hostage();
    RegisterZulAmanCreatureAI(npc_harrison_jones);
    RegisterSpellScript(spell_ritual_of_power);
    RegisterZulAmanCreatureAI(npc_amanishi_lookout);
    RegisterZulAmanCreatureAI(npc_eagle_trash_aggro_trigger);
    RegisterZulAmanCreatureAI(npc_amanishi_tempest);
    RegisterZulAmanCreatureAI(npc_amanishi_scout);
    RegisterSpellScript(spell_alert_drums);
    RegisterSpellScript(spell_summon_amanishi_sentries);
    RegisterSpellScript(spell_call_of_the_beast);
}
References RegisterSpellScript, and RegisterZulAmanCreatureAI.
Referenced by AddEasternKingdomsScripts().
IsDrum()
bool IsDrum (Creature * trigger) inline
{
    return trigger->GetPositionX() < -90.0f // South of Jan'alai area
        && !IsHut(trigger);
}
References Position::GetPositionX(), and IsHut().
Referenced by npc_amanishi_scout::JustEngagedWith().
IsHut()
bool IsHut (Creature * trigger) inline
{
    return trigger->GetPositionX() < -90.0f // South of Jan'alai area
        && ((trigger->GetOrientation() > 2.7f) || (trigger->GetOrientation() < 2.7f && 1270.0f < trigger->GetPositionY() && trigger->GetPositionY() < 1280.0f));
}
References Position::GetOrientation(), Position::GetPositionX(), and Position::GetPositionY().
Referenced by spell_summon_amanishi_sentries::HandleScriptEffect(), and IsDrum().
Variable Documentation
ChestEntry
uint32 ChestEntry[] = {186648, 187021, 186667, 186672} static
{186648, 187021, 186667, 186672};
Referenced by npc_zulaman_hostage::OnGossipSelect().
HostageEntry
uint32 HostageEntry[] = {23790, 23999, 24024, 24001} static
{23790, 23999, 24024, 24001};
Referenced by npc_zulaman_hostage::OnGossipSelect().