AzerothCore Doxygen
HealthCheckEventData Struct Reference
#include "ScriptedCreature.h"
Public Member Functions
HealthCheckEventData (uint8 healthPct, std::function< void()> exec, uint8 status=HEALTH_CHECK_SCHEDULED, bool allowedWhileCasting=true, Milliseconds Delay=0ms)
bool HasBeenProcessed () const
bool IsPending () const
Milliseconds GetDelay () const
void UpdateStatus (uint8 status)
Public Attributes
uint8 _healthPct
std::function< void()> _exec
uint8 _status
bool _allowedWhileCasting
Milliseconds _delay
Detailed Description
Constructor & Destructor Documentation
HealthCheckEventData()
HealthCheckEventData::HealthCheckEventData (uint8 healthPct, std::function< void()> exec, uint8 status = HEALTH_CHECK_SCHEDULED, bool allowedWhileCasting = true, Milliseconds Delay = 0ms) inline
: _healthPct(healthPct), _exec(exec), _status(status), _allowedWhileCasting(allowedWhileCasting), _delay(Delay) { };
Member Function Documentation
GetDelay()
Milliseconds HealthCheckEventData::GetDelay () const inline
{ return _delay; };
References _delay.
HasBeenProcessed()
bool HealthCheckEventData::HasBeenProcessed () const inline
{ return _status == HEALTH_CHECK_PROCESSED; };
References _status, and HEALTH_CHECK_PROCESSED.
Referenced by BossAI::DamageTaken().
IsPending()
bool HealthCheckEventData::IsPending () const inline
{ return _status == HEALTH_CHECK_PENDING; };
References _status, and HEALTH_CHECK_PENDING.
Referenced by BossAI::OnSpellCastFinished().
UpdateStatus()
void HealthCheckEventData::UpdateStatus (uint8 status) inline
{ _status = status; };
References _status.
Referenced by BossAI::DamageTaken(), BossAI::OnSpellCastFinished(), and BossAI::ProcessHealthCheck().
Member Data Documentation
_allowedWhileCasting
bool HealthCheckEventData::_allowedWhileCasting
Referenced by BossAI::DamageTaken().
_delay
Milliseconds HealthCheckEventData::_delay
Referenced by GetDelay().
_exec
std::function<void()> HealthCheckEventData::_exec
Referenced by BossAI::ProcessHealthCheck().
_healthPct
uint8 HealthCheckEventData::_healthPct
Referenced by BossAI::DamageTaken(), and BossAI::ProcessHealthCheck().
_status
uint8 HealthCheckEventData::_status
Referenced by HasBeenProcessed(), IsPending(), and UpdateStatus().
The documentation for this struct was generated from the following file:
azerothcore-wotlk/src/server/game/AI/ScriptedAI/ScriptedCreature.h