AzerothCore Doxygen
Eluna_BGScript Class Reference
Public Member Functions
Eluna_BGScript ()
void OnBattlegroundStart (Battleground *bg) override
This hook runs before start Battleground.
void OnBattlegroundEnd (Battleground *bg, TeamId winnerTeam) override
This hook runs after end Battleground.
void OnBattlegroundDestroy (Battleground *bg) override
This hook runs before Battleground destroy.
void OnBattlegroundCreate (Battleground *bg) override
This hook runs after Battleground create.
Public Member Functions inherited from AllBattlegroundScript
bool IsDatabaseBound () const override
virtual void OnBattlegroundEndReward (Battleground *, Player *, TeamId)
virtual void OnBattlegroundUpdate (Battleground *, uint32)
virtual void OnBattlegroundAddPlayer (Battleground *, Player *)
virtual void OnBattlegroundBeforeAddPlayer (Battleground *, Player *)
virtual void OnBattlegroundRemovePlayerAtLeave (Battleground *, Player *)
virtual void OnQueueUpdate (BattlegroundQueue *, uint32, BattlegroundTypeId, BattlegroundBracketId, uint8, bool, uint32)
virtual bool OnQueueUpdateValidity (BattlegroundQueue *, uint32, BattlegroundTypeId, BattlegroundBracketId, uint8, bool, uint32)
virtual void OnAddGroup (BattlegroundQueue *, GroupQueueInfo *, uint32 &, Player *, Group *, BattlegroundTypeId, PvPDifficultyEntry const *, uint8, bool, bool, uint32, uint32, uint32, uint32)
virtual bool CanFillPlayersToBG (BattlegroundQueue *, Battleground *, BattlegroundBracketId)
virtual bool IsCheckNormalMatch (BattlegroundQueue *, Battleground *, BattlegroundBracketId, uint32, uint32)
virtual bool CanSendMessageBGQueue (BattlegroundQueue *, Player *, Battleground *, PvPDifficultyEntry const *)
virtual bool OnBeforeSendJoinMessageArenaQueue (BattlegroundQueue *, Player *, GroupQueueInfo *, PvPDifficultyEntry const *, bool)
This hook runs before sending the join message during the arena queue, allowing you to run extra operations or disabling the join message.
virtual bool OnBeforeSendExitMessageArenaQueue (BattlegroundQueue *, GroupQueueInfo *)
This hook runs before sending the exit message during the arena queue, allowing you to run extra operations or disabling the exit message.
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
uint16 GetTotalAvailableHooks ()
Additional Inherited Members
Protected Member Functions inherited from AllBattlegroundScript
AllBattlegroundScript (const char *name, std::vector< uint16 > enabledHooks=std::vector< uint16 >())
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name, uint16 totalAvailableHooks=0)
virtual ~ScriptObject ()=default
Detailed Description
Constructor & Destructor Documentation
Eluna_BGScript()
Eluna_BGScript::Eluna_BGScript () inline
: BGScript("Eluna_BGScript") { }
Member Function Documentation
OnBattlegroundCreate()
void Eluna_BGScript::OnBattlegroundCreate (Battleground *) inline override virtual
This hook runs after Battleground create.
Parameters
bg Contains information about the Battleground
Reimplemented from AllBattlegroundScript.
    {
        sEluna->OnBGCreate(bg, bg->GetBgTypeID(), bg->GetInstanceID());
    }
References Battleground::GetBgTypeID(), Battleground::GetInstanceID(), and sEluna.
OnBattlegroundDestroy()
void Eluna_BGScript::OnBattlegroundDestroy (Battleground *) inline override virtual
This hook runs before Battleground destroy.
Parameters
bg Contains information about the Battleground
Reimplemented from AllBattlegroundScript.
    {
        sEluna->OnBGDestroy(bg, bg->GetBgTypeID(), bg->GetInstanceID());
    }
References Battleground::GetBgTypeID(), Battleground::GetInstanceID(), and sEluna.
OnBattlegroundEnd()
void Eluna_BGScript::OnBattlegroundEnd (Battleground * , TeamId) inline override virtual
This hook runs after end Battleground.
Parameters
bg Contains information about the Battleground
TeamId Contains information about the winneer team
Reimplemented from AllBattlegroundScript.
    {
        sEluna->OnBGEnd(bg, bg->GetBgTypeID(), bg->GetInstanceID(), winnerTeam);
    }
References Battleground::GetBgTypeID(), Battleground::GetInstanceID(), and sEluna.
OnBattlegroundStart()
void Eluna_BGScript::OnBattlegroundStart (Battleground *) inline override virtual
This hook runs before start Battleground.
Parameters
bg Contains information about the Battleground
Reimplemented from AllBattlegroundScript.
    {
        sEluna->OnBGStart(bg, bg->GetBgTypeID(), bg->GetInstanceID());
    }
References Battleground::GetBgTypeID(), Battleground::GetInstanceID(), and sEluna.
The documentation for this class was generated from the following file:
mod-eluna/src/ElunaLuaEngine_SC.cpp