AzerothCore Doxygen
ServerMailCondition Struct Reference
Represents a condition that must be met for a player to receive a server mail.
#include "ServerMailMgr.h"
Public Member Functions
ServerMailCondition ()=default
bool CheckCondition (Player *player) const
Checks if a player meets this condition.
Public Attributes
ServerMailConditionType type = ServerMailConditionType::Invalid
uint32 value { 0 }
uint32 state { 0 }
Detailed Description
Represents a condition that must be met for a player to receive a server mail.
Each condition has a type (see ServerMailConditionType) and a value associated with the type. For example, for a level condition, the value represents the required player level.
Some condition also have a state associated with the value. For example, for a reputation condition, the state represents the current reputation state, like Exalted.
Conditions are attached to server mail templates and are evaluated when players log in.
Constructor & Destructor Documentation
ServerMailCondition()
ServerMailCondition::ServerMailCondition () default
Member Function Documentation
CheckCondition()
bool ServerMailCondition::CheckCondition (Player * player) const
Checks if a player meets this condition.
Evaluates the condition type and compares the player's attributes to the required value.
Parameters
player The player to check.
Returns
True if the player meets the condition, otherwise false.
{
    switch (type)
    {
    case ServerMailConditionType::Level:
        return player->GetLevel() >= value;
    case ServerMailConditionType::PlayTime:
        return player->GetTotalPlayedTime() >= value;
    case ServerMailConditionType::Quest:
        return player->GetQuestStatus(value) == state;
    case ServerMailConditionType::Achievement:
        return player->HasAchieved(value);
    case ServerMailConditionType::Reputation:
        return player->GetReputationRank(value) >= state;
    case ServerMailConditionType::Faction:
        return player->GetTeamId() == value;
    case ServerMailConditionType::Race:
        return (player->getRaceMask() & value) != 0;
    case ServerMailConditionType::Class:
        return (player->getClassMask() & value) != 0;
    case ServerMailConditionType::AccountFlags:
        return player->GetSession()->HasAccountFlag(value);
    default:
        [[unlikely]] LOG_ERROR("server.mail", "Unknown server mail condition type '{}'", static_cast<uint32>(type));
        return false;
    }
}
References AccountFlags, Achievement, Class, Faction, Unit::getClassMask(), Unit::GetLevel(), Player::GetQuestStatus(), Unit::getRaceMask(), Player::GetReputationRank(), Player::GetSession(), Player::GetTeamId(), Player::GetTotalPlayedTime(), WorldSession::HasAccountFlag(), Player::HasAchieved(), Level, LOG_ERROR, PlayTime, Quest, Race, Reputation, state, type, and value.
Member Data Documentation
state
uint32 ServerMailCondition::state { 0 }
{ 0 };
Referenced by CheckCondition(), and ServerMailMgr::LoadMailServerTemplatesConditions().
type
ServerMailConditionType ServerMailCondition::type = ServerMailConditionType::Invalid
Referenced by CheckCondition(), and ServerMailMgr::LoadMailServerTemplatesConditions().
value
uint32 ServerMailCondition::value { 0 }
{ 0 };
Referenced by CheckCondition(), and ServerMailMgr::LoadMailServerTemplatesConditions().
The documentation for this struct was generated from the following files:
azerothcore-wotlk/src/server/game/Mails/ServerMailMgr.h
azerothcore-wotlk/src/server/game/Mails/ServerMailMgr.cpp