AzerothCore Doxygen
LuaItem Namespace Reference
Functions
int IsSoulBound (lua_State *L, Item *item)
int IsBoundAccountWide (lua_State *L, Item *item)
int IsBoundByEnchant (lua_State *L, Item *item)
int IsNotBoundToPlayer (lua_State *L, Item *item)
int IsLocked (lua_State *L, Item *item)
int IsBag (lua_State *L, Item *item)
int IsCurrencyToken (lua_State *L, Item *item)
int IsNotEmptyBag (lua_State *L, Item *item)
int IsBroken (lua_State *L, Item *item)
int CanBeTraded (lua_State *L, Item *item)
int IsInTrade (lua_State *L, Item *item)
int IsInBag (lua_State *L, Item *item)
int IsEquipped (lua_State *L, Item *item)
int HasQuest (lua_State *L, Item *item)
int IsPotion (lua_State *L, Item *item)
int IsConjuredConsumable (lua_State *L, Item *item)
int GetItemLink (lua_State *L, Item *item)
int GetOwnerGUID (lua_State *L, Item *item)
int GetOwner (lua_State *L, Item *item)
int GetCount (lua_State *L, Item *item)
int GetMaxStackCount (lua_State *L, Item *item)
int GetSlot (lua_State *L, Item *item)
int GetBagSlot (lua_State *L, Item *item)
int GetEnchantmentId (lua_State *L, Item *item)
int GetSpellId (lua_State *L, Item *item)
int GetSpellTrigger (lua_State *L, Item *item)
int GetClass (lua_State *L, Item *item)
int GetSubClass (lua_State *L, Item *item)
int GetName (lua_State *L, Item *item)
int GetDisplayId (lua_State *L, Item *item)
int GetQuality (lua_State *L, Item *item)
int GetBuyCount (lua_State *L, Item *item)
int GetBuyPrice (lua_State *L, Item *item)
int GetSellPrice (lua_State *L, Item *item)
int GetInventoryType (lua_State *L, Item *item)
int GetAllowableClass (lua_State *L, Item *item)
int GetAllowableRace (lua_State *L, Item *item)
int GetItemLevel (lua_State *L, Item *item)
int GetRequiredLevel (lua_State *L, Item *item)
int GetRandomProperty (lua_State *L, Item *item)
int GetRandomSuffix (lua_State *L, Item *item)
int GetItemSet (lua_State *L, Item *item)
int GetBagSize (lua_State *L, Item *item)
int GetItemTemplate (lua_State *L, Item *item)
int SetOwner (lua_State *L, Item *item)
int SetBinding (lua_State *L, Item *item)
int SetCount (lua_State *L, Item *item)
int SetEnchantment (lua_State *L, Item *item)
int ClearEnchantment (lua_State *L, Item *item)
int SaveToDB (lua_State *, Item *item)
Function Documentation
CanBeTraded()
int LuaItem::CanBeTraded (lua_State * L, Item * item)
Returns 'true' if the [Item] can be traded, 'false' otherwise
Returns
bool isTradeable
    {
#if (defined(TBC) || defined(CLASSIC))
        Eluna::Push(L, item->CanBeTraded());
#else
        bool mail = Eluna::CHECKVAL<bool>(L, 2, false);
        Eluna::Push(L, item->CanBeTraded(mail));
#endif
        return 1;
    }
References Item::CanBeTraded(), and Eluna::Push().
ClearEnchantment()
int LuaItem::ClearEnchantment (lua_State * L, Item * item)
Removes an enchant from the [Item] by the specified slot
Parameters
uint32 enchantSlot : the slot for the enchant to be removed from
Returns
bool enchantmentRemoved : if enchantment is successfully removed from specified slot, returns 'true', otherwise 'false'
    {
        Player* owner = item->GetOwner();
        if (!owner)
        {
            Eluna::Push(L, false);
            return 1;
        }
        EnchantmentSlot slot = (EnchantmentSlot)Eluna::CHECKVAL<uint32>(L, 2);
        if (slot >= MAX_INSPECTED_ENCHANTMENT_SLOT)
            return luaL_argerror(L, 2, "valid EnchantmentSlot expected");
        if (!item->GetEnchantmentId(slot))
        {
            Eluna::Push(L, false);
            return 1;
        }
        owner->ApplyEnchantment(item, slot, false);
        item->ClearEnchantment(slot);
        Eluna::Push(L, true);
        return 1;
    }
References Player::ApplyEnchantment(), Item::ClearEnchantment(), Item::GetEnchantmentId(), Item::GetOwner(), luaL_argerror(), MAX_INSPECTED_ENCHANTMENT_SLOT, and Eluna::Push().
GetAllowableClass()
int LuaItem::GetAllowableClass (lua_State * L, Item * item)
Returns the [Player] classes allowed to use this [Item]
Returns
uint32 allowableClass
    {
        Eluna::Push(L, item->GetTemplate()->AllowableClass);
        return 1;
    }
References ItemTemplate::AllowableClass, Item::GetTemplate(), and Eluna::Push().
GetAllowableRace()
int LuaItem::GetAllowableRace (lua_State * L, Item * item)
Returns the [Player] races allowed to use this [Item]
Returns
uint32 allowableRace
    {
        Eluna::Push(L, item->GetTemplate()->AllowableRace);
        return 1;
    }
References ItemTemplate::AllowableRace, Item::GetTemplate(), and Eluna::Push().
GetBagSize()
int LuaItem::GetBagSize (lua_State * L, Item * item)
Returns the bag size of this [Item], 0 if [Item] is not a bag
Returns
uint32 bagSize
    {
        if (Bag* bag = item->ToBag())
            Eluna::Push(L, bag->GetBagSize());
        else
            Eluna::Push(L, 0);
        return 1;
    }
References Eluna::Push(), and Item::ToBag().
GetBagSlot()
int LuaItem::GetBagSlot (lua_State * L, Item * item)
Returns the [Item]s current bag slot
Returns
uint8 bagSlot
    {
        Eluna::Push(L, item->GetBagSlot());
        return 1;
    }
References Item::GetBagSlot(), and Eluna::Push().
GetBuyCount()
int LuaItem::GetBuyCount (lua_State * L, Item * item)
Returns the default purchase count of the [Item]
Returns
uint32 count
    {
        Eluna::Push(L, item->GetTemplate()->BuyCount);
        return 1;
    }
References ItemTemplate::BuyCount, Item::GetTemplate(), and Eluna::Push().
GetBuyPrice()
int LuaItem::GetBuyPrice (lua_State * L, Item * item)
Returns the purchase price of the [Item]
Returns
uint32 price
    {
        Eluna::Push(L, item->GetTemplate()->BuyPrice);
        return 1;
    }
References ItemTemplate::BuyPrice, Item::GetTemplate(), and Eluna::Push().
GetClass()
int LuaItem::GetClass (lua_State * L, Item * item)
Returns class of the [Item]
Returns
uint32 class
    {
        Eluna::Push(L, item->GetTemplate()->Class);
        return 1;
    }
References ItemTemplate::Class, Item::GetTemplate(), and Eluna::Push().
GetCount()
int LuaItem::GetCount (lua_State * L, Item * item)
Returns the [Item]s stack count
Returns
uint32 count
    {
        Eluna::Push(L, item->GetCount());
        return 1;
    }
References Item::GetCount(), and Eluna::Push().
GetDisplayId()
int LuaItem::GetDisplayId (lua_State * L, Item * item)
Returns the display ID of the [Item]
Returns
uint32 displayId
    {
        Eluna::Push(L, item->GetTemplate()->DisplayInfoID);
        return 1;
    }
References ItemTemplate::DisplayInfoID, Item::GetTemplate(), and Eluna::Push().
GetEnchantmentId()
int LuaItem::GetEnchantmentId (lua_State * L, Item * item)
Returns the [Item]s enchantment ID by enchant slot specified
Parameters
[EnchantmentSlot] enchantSlot : the enchant slot specified
Returns
uint32 enchantId : the id of the enchant slot specified
    {
        uint32 enchant_slot = Eluna::CHECKVAL<uint32>(L, 2);
        if (enchant_slot >= MAX_INSPECTED_ENCHANTMENT_SLOT)
            return luaL_argerror(L, 2, "valid EnchantmentSlot expected");
        Eluna::Push(L, item->GetEnchantmentId(EnchantmentSlot(enchant_slot)));
        return 1;
    }
References Item::GetEnchantmentId(), luaL_argerror(), MAX_INSPECTED_ENCHANTMENT_SLOT, and Eluna::Push().
GetInventoryType()
int LuaItem::GetInventoryType (lua_State * L, Item * item)
Returns the inventory type of the [Item]
Returns
uint32 inventoryType
    {
        Eluna::Push(L, item->GetTemplate()->InventoryType);
        return 1;
    }
References Item::GetTemplate(), ItemTemplate::InventoryType, and Eluna::Push().
GetItemLevel()
int LuaItem::GetItemLevel (lua_State * L, Item * item)
Returns the [Item]s level
Returns
uint32 itemLevel
    {
        Eluna::Push(L, item->GetTemplate()->ItemLevel);
        return 1;
    }
References Item::GetTemplate(), ItemTemplate::ItemLevel, and Eluna::Push().
GetItemLink()
int LuaItem::GetItemLink (lua_State * L, Item * item)
Returns the chat link of the [Item]
enum LocaleConstant
{
    LOCALE_enUS = 0,
    LOCALE_koKR = 1,
    LOCALE_frFR = 2,
    LOCALE_deDE = 3,
    LOCALE_zhCN = 4,
    LOCALE_zhTW = 5,
    LOCALE_esES = 6,
    LOCALE_esMX = 7,
    LOCALE_ruRU = 8
};
Parameters
[LocaleConstant] locale = DEFAULT_LOCALE : locale to return the [Item]'s name in
Returns
string itemLink
    {
        uint8 locale = Eluna::CHECKVAL<uint8>(L, 2, DEFAULT_LOCALE);
        if (locale >= TOTAL_LOCALES)
            return luaL_argerror(L, 2, "valid LocaleConstant expected");
        const ItemTemplate* temp = item->GetTemplate();
        std::string name = temp->Name1;
        if (ItemLocale const* il = eObjectMgr->GetItemLocale(temp->ItemId))
        {
            ObjectMgr::GetLocaleString(il->Name, static_cast<LocaleConstant>(locale), name);
        }
#ifndef CLASSIC
        if (int32 itemRandPropId = item->GetItemRandomPropertyId())
        {
#if defined(CATA) || defined (MISTS)
            char* suffix = NULL;
#else
#if TRINITY || AZEROTHCORE
            std::array<char const*, 16> const* suffix = NULL;
#else
            char* const* suffix = NULL;
#endif
#endif
            if (itemRandPropId < 0)
            {
                const ItemRandomSuffixEntry* itemRandEntry = sItemRandomSuffixStore.LookupEntry(-item->GetItemRandomPropertyId());
                if (itemRandEntry)
                {
#if TRINITY || AZEROTHCORE
                    suffix = &itemRandEntry->Name;
#else
                    suffix = itemRandEntry->nameSuffix;
#endif
                }
            }
            else
            {
                const ItemRandomPropertiesEntry* itemRandEntry = sItemRandomPropertiesStore.LookupEntry(item->GetItemRandomPropertyId());
                if (itemRandEntry)
                {
#if TRINITY || AZEROTHCORE
                    suffix = &itemRandEntry->Name;
#else
                    suffix = itemRandEntry->nameSuffix;
#endif
                }
            }
            if (suffix)
            {
#if TRINITY || AZEROTHCORE
                const char* suffixName = (*suffix)[(name != temp->Name1) ? locale : uint8(DEFAULT_LOCALE)];
#else
                const char* suffixName = suffix[(name != temp->Name1) ? locale : uint8(DEFAULT_LOCALE)];
#endif
                if (strcmp(suffixName, "") != 0)
                {
                    name += ' ';
                    name += suffixName;
                }
            }
        }
#endif
        Player* owner = item->GetOwner();
        std::ostringstream oss;
        oss << "|c" << std::hex << ItemQualityColors[temp->Quality] << std::dec <<
            "|Hitem:" << temp->ItemId << ":" <<
            item->GetEnchantmentId(PERM_ENCHANTMENT_SLOT) << ":" <<
#ifndef CLASSIC
            item->GetEnchantmentId(SOCK_ENCHANTMENT_SLOT) << ":" <<
            item->GetEnchantmentId(SOCK_ENCHANTMENT_SLOT_2) << ":" <<
            item->GetEnchantmentId(SOCK_ENCHANTMENT_SLOT_3) << ":" <<
            item->GetEnchantmentId(BONUS_ENCHANTMENT_SLOT) << ":" <<
#endif
            item->GetItemRandomPropertyId() << ":" << item->GetItemSuffixFactor() << ":" <<
            (uint32)(owner ? owner->GetLevel() : 0) << "|h[" << name << "]|h|r";
        Eluna::Push(L, oss.str());
        return 1;
    }
References BONUS_ENCHANTMENT_SLOT, DEFAULT_LOCALE, eObjectMgr, Item::GetEnchantmentId(), Item::GetItemRandomPropertyId(), Item::GetItemSuffixFactor(), Unit::GetLevel(), ObjectMgr::GetLocaleString(), Item::GetOwner(), Item::GetTemplate(), ItemTemplate::ItemId, ItemQualityColors, luaL_argerror(), ItemRandomPropertiesEntry::Name, ItemRandomSuffixEntry::Name, ItemTemplate::Name1, PERM_ENCHANTMENT_SLOT, Eluna::Push(), ItemTemplate::Quality, sItemRandomPropertiesStore, sItemRandomSuffixStore, SOCK_ENCHANTMENT_SLOT, SOCK_ENCHANTMENT_SLOT_2, SOCK_ENCHANTMENT_SLOT_3, and TOTAL_LOCALES.
GetItemSet()
int LuaItem::GetItemSet (lua_State * L, Item * item)
Returns the item set ID of this [Item]
Returns
uint32 itemSetId
    {
        Eluna::Push(L, item->GetTemplate()->ItemSet);
        return 1;
    }
References Item::GetTemplate(), ItemTemplate::ItemSet, and Eluna::Push().
GetItemTemplate()
int LuaItem::GetItemTemplate (lua_State * L, Item * item)
Returns the [ItemTemplate] for this [Item].
Returns
[ItemTemplate] itemTemplate
    {
        Eluna::Push(L, item->GetTemplate());
        return 1;
    }
References Item::GetTemplate(), and Eluna::Push().
GetMaxStackCount()
int LuaItem::GetMaxStackCount (lua_State * L, Item * item)
Returns the [Item]s max stack count
Returns
uint32 maxCount
    {
        Eluna::Push(L, item->GetMaxStackCount());
        return 1;
    }
References Item::GetMaxStackCount(), and Eluna::Push().
GetName()
int LuaItem::GetName (lua_State * L, Item * item)
Returns the name of the [Item]
Returns
string name
    {
        Eluna::Push(L, item->GetTemplate()->Name1);
        return 1;
    }
References Item::GetTemplate(), ItemTemplate::Name1, and Eluna::Push().
GetOwner()
int LuaItem::GetOwner (lua_State * L, Item * item)
Returns the [Player] who currently owns the [Item]
Returns
[Player] player : the [Player] who owns the [Item]
    {
        Eluna::Push(L, item->GetOwner());
        return 1;
    }
References Item::GetOwner(), and Eluna::Push().
GetOwnerGUID()
int LuaItem::GetOwnerGUID (lua_State * L, Item * item)
    {
#if defined TRINITY || AZEROTHCORE
        Eluna::Push(L, item->GetOwnerGUID());
#else
        Eluna::Push(L, item->GetOwnerGuid());
#endif
        return 1;
    }
References Item::GetOwnerGUID(), and Eluna::Push().
GetQuality()
int LuaItem::GetQuality (lua_State * L, Item * item)
Returns the quality of the [Item]
Returns
uint32 quality
    {
        Eluna::Push(L, item->GetTemplate()->Quality);
        return 1;
    }
References Item::GetTemplate(), Eluna::Push(), and ItemTemplate::Quality.
GetRandomProperty()
int LuaItem::GetRandomProperty (lua_State * L, Item * item)
Returns the random property ID of this [Item]
Returns
uint32 randomPropertyId
    {
        Eluna::Push(L, item->GetTemplate()->RandomProperty);
        return 1;
    }
References Item::GetTemplate(), Eluna::Push(), and ItemTemplate::RandomProperty.
GetRandomSuffix()
int LuaItem::GetRandomSuffix (lua_State * L, Item * item)
    {
        Eluna::Push(L, item->GetTemplate()->RandomSuffix);
        return 1;
    }
References Item::GetTemplate(), Eluna::Push(), and ItemTemplate::RandomSuffix.
GetRequiredLevel()
int LuaItem::GetRequiredLevel (lua_State * L, Item * item)
Returns the minimum level required to use this [Item]
Returns
uint32 requiredLevel
    {
        Eluna::Push(L, item->GetTemplate()->RequiredLevel);
        return 1;
    }
References Item::GetTemplate(), Eluna::Push(), and ItemTemplate::RequiredLevel.
GetSellPrice()
int LuaItem::GetSellPrice (lua_State * L, Item * item)
Returns the sell price of the [Item]
Returns
uint32 price
    {
        Eluna::Push(L, item->GetTemplate()->SellPrice);
        return 1;
    }
References Item::GetTemplate(), Eluna::Push(), and ItemTemplate::SellPrice.
GetSlot()
int LuaItem::GetSlot (lua_State * L, Item * item)
Returns the [Item]s current slot
Returns
uint8 slot
    {
        Eluna::Push(L, item->GetSlot());
        return 1;
    }
References Item::GetSlot(), and Eluna::Push().
GetSpellId()
int LuaItem::GetSpellId (lua_State * L, Item * item)
Returns the spell ID tied to the [Item] by spell index
Parameters
uint32 spellIndex : the spell index specified
Returns
uint32 spellId : the id of the spell
    {
        uint32 index = Eluna::CHECKVAL<uint32>(L, 2);
        if (index >= MAX_ITEM_PROTO_SPELLS)
            return luaL_argerror(L, 2, "valid SpellIndex expected");
        Eluna::Push(L, item->GetTemplate()->Spells[index].SpellId);
        return 1;
    }
References Item::GetTemplate(), luaL_argerror(), MAX_ITEM_PROTO_SPELLS, Eluna::Push(), _Spell::SpellId, and ItemTemplate::Spells.
GetSpellTrigger()
int LuaItem::GetSpellTrigger (lua_State * L, Item * item)
Returns the spell trigger tied to the [Item] by spell index
Parameters
uint32 spellIndex : the spell index specified
Returns
uint32 spellTrigger : the spell trigger of the specified index
    {
        uint32 index = Eluna::CHECKVAL<uint32>(L, 2);
        if (index >= MAX_ITEM_PROTO_SPELLS)
            return luaL_argerror(L, 2, "valid SpellIndex expected");
        Eluna::Push(L, item->GetTemplate()->Spells[index].SpellTrigger);
        return 1;
    }
References Item::GetTemplate(), luaL_argerror(), MAX_ITEM_PROTO_SPELLS, Eluna::Push(), ItemTemplate::Spells, and _Spell::SpellTrigger.
GetSubClass()
int LuaItem::GetSubClass (lua_State * L, Item * item)
Returns subclass of the [Item]
Returns
uint32 subClass
    {
        Eluna::Push(L, item->GetTemplate()->SubClass);
        return 1;
    }
References Item::GetTemplate(), Eluna::Push(), and ItemTemplate::SubClass.
HasQuest()
int LuaItem::HasQuest (lua_State * L, Item * item)
Returns 'true' if the [Item] has the [Quest] specified tied to it, 'false' otherwise
Parameters
uint32 questId : the [Quest] id to be checked
Returns
bool hasQuest
    {
        uint32 quest = Eluna::CHECKVAL<uint32>(L, 2);
#if defined TRINITY || AZEROTHCORE
        Eluna::Push(L, item->hasQuest(quest));
#else
        Eluna::Push(L, item->HasQuest(quest));
#endif
        return 1;
    }
References Item::hasQuest(), and Eluna::Push().
IsBag()
int LuaItem::IsBag (lua_State * L, Item * item)
Returns 'true' if the [Item] is a bag, 'false' otherwise
Returns
bool isBag
    {
        Eluna::Push(L, item->IsBag());
        return 1;
    }
References Item::IsBag(), and Eluna::Push().
IsBoundAccountWide()
int LuaItem::IsBoundAccountWide (lua_State * L, Item * item)
Returns 'true' if the [Item] is account bound, 'false' otherwise
Returns
bool isAccountBound
    {
        Eluna::Push(L, item->IsBoundAccountWide());
        return 1;
    }
References Item::IsBoundAccountWide(), and Eluna::Push().
IsBoundByEnchant()
int LuaItem::IsBoundByEnchant (lua_State * L, Item * item)
Returns 'true' if the [Item] is bound to a [Player] by an enchant, 'false' otehrwise
Returns
bool isBoundByEnchant
    {
        Eluna::Push(L, item->IsBoundByEnchant());
        return 1;
    }
References Item::IsBoundByEnchant(), and Eluna::Push().
IsBroken()
int LuaItem::IsBroken (lua_State * L, Item * item)
Returns 'true' if the [Item] is broken, 'false' otherwise
Returns
bool isBroken
    {
        Eluna::Push(L, item->IsBroken());
        return 1;
    }
References Item::IsBroken(), and Eluna::Push().
IsConjuredConsumable()
int LuaItem::IsConjuredConsumable (lua_State * L, Item * item)
Returns 'true' if the [Item] is a conjured consumable, 'false' otherwise
Returns
bool isConjuredConsumable
    {
        Eluna::Push(L, item->IsConjuredConsumable());
        return 1;
    }
References Item::IsConjuredConsumable(), and Eluna::Push().
IsCurrencyToken()
int LuaItem::IsCurrencyToken (lua_State * L, Item * item)
Returns 'true' if the [Item] is a currency token, 'false' otherwise
Returns
bool isCurrencyToken
    {
        Eluna::Push(L, item->IsCurrencyToken());
        return 1;
    }
References Item::IsCurrencyToken(), and Eluna::Push().
IsEquipped()
int LuaItem::IsEquipped (lua_State * L, Item * item)
Returns 'true' if the [Item] is currently equipped, 'false' otherwise
Returns
bool isEquipped
    {
        Eluna::Push(L, item->IsEquipped());
        return 1;
    }
References Item::IsEquipped(), and Eluna::Push().
IsInBag()
int LuaItem::IsInBag (lua_State * L, Item * item)
Returns 'true' if the [Item] is currently in a bag, 'false' otherwise
Returns
bool isInBag
    {
        Eluna::Push(L, item->IsInBag());
        return 1;
    }
References Item::IsInBag(), and Eluna::Push().
IsInTrade()
int LuaItem::IsInTrade (lua_State * L, Item * item)
Returns 'true' if the [Item] is currently in a trade window, 'false' otherwise
Returns
bool isInTrade
    {
        Eluna::Push(L, item->IsInTrade());
        return 1;
    }
References Item::IsInTrade(), and Eluna::Push().
IsLocked()
int LuaItem::IsLocked (lua_State * L, Item * item)
Returns 'true' if the [Item] is locked, 'false' otherwise
Returns
bool isLocked
    {
        Eluna::Push(L, item->IsLocked());
        return 1;
    }
References Item::IsLocked(), and Eluna::Push().
IsNotBoundToPlayer()
int LuaItem::IsNotBoundToPlayer (lua_State * L, Item * item)
Returns 'true' if the [Item] is not bound to the [Player] specified, 'false' otherwise
Parameters
[Player] player : the [Player] object to check the item against
Returns
bool isNotBound
    {
        Player* player = Eluna::CHECKOBJ<Player>(L, 2);
        Eluna::Push(L, item->IsBindedNotWith(player));
        return 1;
    }
References Item::IsBindedNotWith(), and Eluna::Push().
IsNotEmptyBag()
int LuaItem::IsNotEmptyBag (lua_State * L, Item * item)
Returns 'true' if the [Item] is a not an empty bag, 'false' otherwise
Returns
bool isNotEmptyBag
    {
        Eluna::Push(L, item->IsNotEmptyBag());
        return 1;
    }
References Item::IsNotEmptyBag(), and Eluna::Push().
IsPotion()
int LuaItem::IsPotion (lua_State * L, Item * item)
Returns 'true' if the [Item] is a potion, 'false' otherwise
Returns
bool isPotion
    {
        Eluna::Push(L, item->IsPotion());
        return 1;
    }
References Item::IsPotion(), and Eluna::Push().
IsSoulBound()
int LuaItem::IsSoulBound (lua_State * L, Item * item)
Returns 'true' if the [Item] is soulbound, 'false' otherwise
Returns
bool isSoulBound
    {
        Eluna::Push(L, item->IsSoulBound());
        return 1;
    }
References Item::IsSoulBound(), and Eluna::Push().
SaveToDB()
int LuaItem::SaveToDB (lua_State * , Item * item)
Saves the [Item] to the database
    {
#if defined TRINITY || defined AZEROTHCORE
        CharacterDatabaseTransaction trans = CharacterDatabaseTransaction(nullptr);
        item->SaveToDB(trans);
#else
        item->SaveToDB();
#endif
        return 0;
    }
References Item::SaveToDB().
SetBinding()
int LuaItem::SetBinding (lua_State * L, Item * item)
Sets the binding of the [Item] to 'true' or 'false'
Parameters
bool setBinding
    {
        bool soulbound = Eluna::CHECKVAL<bool>(L, 2);
        item->SetBinding(soulbound);
        item->SetState(ITEM_CHANGED, item->GetOwner());
        return 0;
    }
References Item::GetOwner(), ITEM_CHANGED, Item::SetBinding(), and Item::SetState().
SetCount()
int LuaItem::SetCount (lua_State * L, Item * item)
Sets the stack count of the [Item]
Parameters
uint32 count
    {
        uint32 count = Eluna::CHECKVAL<uint32>(L, 2);
        item->SetCount(count);
        return 0;
    }
References Item::SetCount().
SetEnchantment()
int LuaItem::SetEnchantment (lua_State * L, Item * item)
Sets the specified enchantment of the [Item] to the specified slot
Parameters
uint32 enchantId : the ID of the enchant to be applied
uint32 enchantSlot : the slot for the enchant to be applied to
Returns
bool enchantmentSuccess : if enchantment is successfully set to specified slot, returns 'true', otherwise 'false'
    {
        Player* owner = item->GetOwner();
        if (!owner)
        {
            Eluna::Push(L, false);
            return 1;
        }
        uint32 enchant = Eluna::CHECKVAL<uint32>(L, 2);
        if (!sSpellItemEnchantmentStore.LookupEntry(enchant))
        {
            Eluna::Push(L, false);
            return 1;
        }
        EnchantmentSlot slot = (EnchantmentSlot)Eluna::CHECKVAL<uint32>(L, 3);
        if (slot >= MAX_INSPECTED_ENCHANTMENT_SLOT)
            return luaL_argerror(L, 2, "valid EnchantmentSlot expected");
        owner->ApplyEnchantment(item, slot, false);
        item->SetEnchantment(slot, enchant, 0, 0);
        owner->ApplyEnchantment(item, slot, true);
        Eluna::Push(L, true);
        return 1;
    }
References Player::ApplyEnchantment(), Item::GetOwner(), luaL_argerror(), MAX_INSPECTED_ENCHANTMENT_SLOT, Eluna::Push(), Item::SetEnchantment(), and sSpellItemEnchantmentStore.
SetOwner()
int LuaItem::SetOwner (lua_State * L, Item * item)
Sets the [Player] specified as the owner of the [Item]
Parameters
[Player] player : the [Player] specified
    {
        Player* player = Eluna::CHECKOBJ<Player>(L, 2);
#if defined TRINITY || AZEROTHCORE
        item->SetOwnerGUID(player->GET_GUID());
#else
        item->SetOwnerGuid(player->GET_GUID());
#endif
        return 0;
    }
References Item::SetOwnerGUID().