AzerothCore Doxygen
OutdoorPvPHP Class Reference
#include "OutdoorPvPHP.h"
Public Member Functions
OutdoorPvPHP ()
bool SetupOutdoorPvP () override
void HandlePlayerEnterZone (Player *player, uint32 zone) override
void HandlePlayerLeaveZone (Player *player, uint32 zone) override
bool Update (uint32 diff) override
void FillInitialWorldStates (WorldPackets::WorldState::InitWorldStates &packet) override
void SendRemoveWorldStates (Player *player) override
void HandleKillImpl (Player *player, Unit *killed) override
uint32 GetAllianceTowersControlled () const
void SetAllianceTowersControlled (uint32 count)
uint32 GetHordeTowersControlled () const
void SetHordeTowersControlled (uint32 count)
Public Member Functions inherited from OutdoorPvP
OutdoorPvP ()=default
~OutdoorPvP () override
void DeleteSpawns ()
virtual bool HandleAreaTrigger (Player *player, uint32 trigger)
virtual bool HandleCustomSpell (Player *player, uint32 spellId, GameObject *go)
virtual bool HandleOpenGo (Player *player, GameObject *go)
void OnGameObjectCreate (GameObject *go) override
void OnGameObjectRemove (GameObject *go) override
void OnCreatureCreate (Creature *creature) override
void OnCreatureRemove (Creature *creature) override
void SendUpdateWorldState (uint32 field, uint32 value)
virtual void HandleKill (Player *killer, Unit *killed)
bool IsInsideObjective (Player *player) const
virtual void AwardKillBonus (Player *)
uint32 GetTypeId () const
virtual bool HandleDropFlag (Player *player, uint32 spellId)
virtual bool HandleGossipOption (Player *player, Creature *creature, uint32 gossipId)
virtual bool CanTalkTo (Player *player, Creature *c, GossipMenuItems const &gso)
void TeamApplyBuff (TeamId teamId, uint32 spellId, uint32 spellId2=0, Player *sameMapPlr=nullptr)
Map * GetMap () const
Public Member Functions inherited from ZoneScript
ZoneScript ()
virtual ~ZoneScript ()
virtual uint32 GetCreatureEntry (ObjectGuid::LowType, CreatureData const *data)
virtual uint32 GetGameObjectEntry (ObjectGuid::LowType, uint32 entry)
virtual void OnUnitDeath (Unit *)
virtual void OnCreatureEvade (Creature *)
virtual ObjectGuid GetGuidData (uint32) const
virtual void SetGuidData (uint32, ObjectGuid)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void ProcessEvent (WorldObject *, uint32)
Private Attributes
uint32 m_AllianceTowersControlled
uint32 m_HordeTowersControlled
Additional Inherited Members
Public Types inherited from OutdoorPvP
typedef std::map< ObjectGuid::LowType, OPvPCapturePoint * > OPvPCapturePointMap
typedef std::pair< ObjectGuid::LowType, GameObject * > GoScriptPair
typedef std::pair< ObjectGuid::LowType, Creature * > CreatureScriptPair
Protected Member Functions inherited from OutdoorPvP
void BroadcastPacket (WorldPacket &data) const
virtual void HandlePlayerResurrects (Player *player, uint32 zone)
void AddCapturePoint (OPvPCapturePoint *cp)
OPvPCapturePoint * GetCapturePoint (ObjectGuid::LowType spawnId) const
void RegisterZone (uint32 zoneid)
bool HasPlayer (Player const *player) const
void TeamCastSpell (TeamId team, int32 spellId, Player *sameMapPlr=nullptr)
void SetMapFromZone (uint32 zone)
Protected Attributes inherited from OutdoorPvP
OPvPCapturePointMap _capturePoints
std::array< PlayerSet, 2 > _players
uint32 _typeId {}
bool _sendUpdate { true }
Map * _map {}
std::unordered_map< ObjectGuid::LowType, GameObject * > _goScriptStore
std::unordered_map< ObjectGuid::LowType, Creature * > _creatureScriptStore
Detailed Description
Constructor & Destructor Documentation
OutdoorPvPHP()
OutdoorPvPHP::OutdoorPvPHP ()
{
    _typeId = OUTDOOR_PVP_HP;
    m_AllianceTowersControlled = 0;
    m_HordeTowersControlled = 0;
}
References OutdoorPvP::_typeId, m_AllianceTowersControlled, m_HordeTowersControlled, and OUTDOOR_PVP_HP.
Member Function Documentation
FillInitialWorldStates()
void OutdoorPvPHP::FillInitialWorldStates (WorldPackets::WorldState::InitWorldStates & packet) override virtual
Reimplemented from OutdoorPvP.
{
    packet.Worldstates.reserve(8);
    packet.Worldstates.emplace_back(WORLD_STATE_OPVP_HP_UI_TOWER_DISPLAY_A, 1);
    packet.Worldstates.emplace_back(WORLD_STATE_OPVP_HP_UI_TOWER_DISPLAY_H, 1);
    packet.Worldstates.emplace_back(WORLD_STATE_OPVP_HP_UI_TOWER_COUNT_A, m_AllianceTowersControlled);
    packet.Worldstates.emplace_back(WORLD_STATE_OPVP_HP_UI_TOWER_COUNT_H, m_HordeTowersControlled);
    packet.Worldstates.emplace_back(WORLD_STATE_OPVP_HP_UI_TOWER_COUNT_H, m_HordeTowersControlled);
    packet.Worldstates.emplace_back(WORLD_STATE_OPVP_HP_UI_TOWER_SLIDER_DISPLAY, 0);
    packet.Worldstates.emplace_back(WORLD_STATE_OPVP_HP_UI_TOWER_SLIDER_POS, 50);
    packet.Worldstates.emplace_back(WORLD_STATE_OPVP_HP_UI_TOWER_SLIDER_N, 100);
    for (OPvPCapturePointMap::iterator itr = _capturePoints.begin(); itr != _capturePoints.end(); ++itr)
    {
        itr->second->FillInitialWorldStates(packet);
    }
}
References OutdoorPvP::_capturePoints, m_AllianceTowersControlled, m_HordeTowersControlled, WORLD_STATE_OPVP_HP_UI_TOWER_COUNT_A, WORLD_STATE_OPVP_HP_UI_TOWER_COUNT_H, WORLD_STATE_OPVP_HP_UI_TOWER_DISPLAY_A, WORLD_STATE_OPVP_HP_UI_TOWER_DISPLAY_H, WORLD_STATE_OPVP_HP_UI_TOWER_SLIDER_DISPLAY, WORLD_STATE_OPVP_HP_UI_TOWER_SLIDER_N, WORLD_STATE_OPVP_HP_UI_TOWER_SLIDER_POS, and WorldPackets::WorldState::InitWorldStates::Worldstates.
GetAllianceTowersControlled()
uint32 OutdoorPvPHP::GetAllianceTowersControlled () const
{
    return m_AllianceTowersControlled;
}
References m_AllianceTowersControlled.
GetHordeTowersControlled()
uint32 OutdoorPvPHP::GetHordeTowersControlled () const
{
    return m_HordeTowersControlled;
}
References m_HordeTowersControlled.
HandleKillImpl()
void OutdoorPvPHP::HandleKillImpl (Player * player, Unit * killed) override virtual
Reimplemented from OutdoorPvP.
{
    if (!killed->IsPlayer())
        return;
    if (player->GetTeamId() == TEAM_ALLIANCE && killed->ToPlayer()->GetTeamId() != TEAM_ALLIANCE)
        player->CastSpell(player, AlliancePlayerKillReward, true);
    else if (player->GetTeamId() == TEAM_HORDE && killed->ToPlayer()->GetTeamId() != TEAM_HORDE)
        player->CastSpell(player, HordePlayerKillReward, true);
}
References AlliancePlayerKillReward, Unit::CastSpell(), Player::GetTeamId(), HordePlayerKillReward, Object::IsPlayer(), TEAM_ALLIANCE, TEAM_HORDE, and Object::ToPlayer().
HandlePlayerEnterZone()
void OutdoorPvPHP::HandlePlayerEnterZone (Player * player, uint32 zone) override virtual
Reimplemented from OutdoorPvP.
{
    // add buffs
    if (player->GetTeamId() == TEAM_ALLIANCE)
    {
        if (m_AllianceTowersControlled >= 3)
            player->CastSpell(player, AllianceBuff, true);
    }
    else
    {
        if (m_HordeTowersControlled >= 3)
            player->CastSpell(player, HordeBuff, true);
    }
    OutdoorPvP::HandlePlayerEnterZone(player, zone);
}
References AllianceBuff, Unit::CastSpell(), Player::GetTeamId(), OutdoorPvP::HandlePlayerEnterZone(), HordeBuff, m_AllianceTowersControlled, m_HordeTowersControlled, and TEAM_ALLIANCE.
HandlePlayerLeaveZone()
void OutdoorPvPHP::HandlePlayerLeaveZone (Player * player, uint32 zone) override virtual
Reimplemented from OutdoorPvP.
{
    // remove buffs
    if (player->GetTeamId() == TEAM_ALLIANCE)
    {
        player->RemoveAurasDueToSpell(AllianceBuff);
    }
    else
    {
        player->RemoveAurasDueToSpell(HordeBuff);
    }
    OutdoorPvP::HandlePlayerLeaveZone(player, zone);
}
References AllianceBuff, Player::GetTeamId(), OutdoorPvP::HandlePlayerLeaveZone(), HordeBuff, Unit::RemoveAurasDueToSpell(), and TEAM_ALLIANCE.
SendRemoveWorldStates()
void OutdoorPvPHP::SendRemoveWorldStates (Player * player) override virtual
Reimplemented from OutdoorPvP.
{
    player->SendUpdateWorldState(WORLD_STATE_OPVP_HP_UI_TOWER_DISPLAY_A, 0);
    player->SendUpdateWorldState(WORLD_STATE_OPVP_HP_UI_TOWER_DISPLAY_H, 0);
    player->SendUpdateWorldState(WORLD_STATE_OPVP_HP_UI_TOWER_COUNT_H, 0);
    player->SendUpdateWorldState(WORLD_STATE_OPVP_HP_UI_TOWER_COUNT_A, 0);
    player->SendUpdateWorldState(WORLD_STATE_OPVP_HP_UI_TOWER_SLIDER_N, 0);
    player->SendUpdateWorldState(WORLD_STATE_OPVP_HP_UI_TOWER_SLIDER_POS, 0);
    player->SendUpdateWorldState(WORLD_STATE_OPVP_HP_UI_TOWER_SLIDER_DISPLAY, 0);
    for (int i = 0; i < HP_TOWER_NUM; ++i)
    {
        player->SendUpdateWorldState(HP_MAP_N[i], 0);
        player->SendUpdateWorldState(HP_MAP_A[i], 0);
        player->SendUpdateWorldState(HP_MAP_H[i], 0);
    }
}
References HP_MAP_A, HP_MAP_H, HP_MAP_N, HP_TOWER_NUM, Player::SendUpdateWorldState(), WORLD_STATE_OPVP_HP_UI_TOWER_COUNT_A, WORLD_STATE_OPVP_HP_UI_TOWER_COUNT_H, WORLD_STATE_OPVP_HP_UI_TOWER_DISPLAY_A, WORLD_STATE_OPVP_HP_UI_TOWER_DISPLAY_H, WORLD_STATE_OPVP_HP_UI_TOWER_SLIDER_DISPLAY, WORLD_STATE_OPVP_HP_UI_TOWER_SLIDER_N, and WORLD_STATE_OPVP_HP_UI_TOWER_SLIDER_POS.
SetAllianceTowersControlled()
void OutdoorPvPHP::SetAllianceTowersControlled (uint32 count)
{
    m_AllianceTowersControlled = count;
}
References m_AllianceTowersControlled.
SetHordeTowersControlled()
void OutdoorPvPHP::SetHordeTowersControlled (uint32 count)
{
    m_HordeTowersControlled = count;
}
References m_HordeTowersControlled.
SetupOutdoorPvP()
bool OutdoorPvPHP::SetupOutdoorPvP () override virtual
Reimplemented from OutdoorPvP.
{
    m_AllianceTowersControlled = 0;
    m_HordeTowersControlled = 0;
    // add the zones affected by the pvp buff
    for (int i = 0; i < OutdoorPvPHPBuffZonesNum; ++i)
        RegisterZone(OutdoorPvPHPBuffZones[i]);
    SetMapFromZone(OutdoorPvPHPBuffZones[0]);
    AddCapturePoint(new OPvPCapturePointHP(this, HP_TOWER_BROKEN_HILL));
    AddCapturePoint(new OPvPCapturePointHP(this, HP_TOWER_OVERLOOK));
    AddCapturePoint(new OPvPCapturePointHP(this, HP_TOWER_STADIUM));
    return true;
}
References OutdoorPvP::AddCapturePoint(), HP_TOWER_BROKEN_HILL, HP_TOWER_OVERLOOK, HP_TOWER_STADIUM, m_AllianceTowersControlled, m_HordeTowersControlled, OutdoorPvPHPBuffZones, OutdoorPvPHPBuffZonesNum, OutdoorPvP::RegisterZone(), and OutdoorPvP::SetMapFromZone().
Update()
bool OutdoorPvPHP::Update (uint32 diff) override virtual
Reimplemented from OutdoorPvP.
{
    bool changed = OutdoorPvP::Update(diff);
    if (changed)
    {
        if (m_AllianceTowersControlled == 3)
            TeamApplyBuff(TEAM_ALLIANCE, AllianceBuff, HordeBuff);
        else if (m_HordeTowersControlled == 3)
            TeamApplyBuff(TEAM_HORDE, HordeBuff, AllianceBuff);
        else
        {
            TeamCastSpell(TEAM_ALLIANCE, -AllianceBuff);
            TeamCastSpell(TEAM_HORDE, -HordeBuff);
        }
        SendUpdateWorldState(WORLD_STATE_OPVP_HP_UI_TOWER_COUNT_A, m_AllianceTowersControlled);
        SendUpdateWorldState(WORLD_STATE_OPVP_HP_UI_TOWER_COUNT_H, m_HordeTowersControlled);
    }
    return changed;
}
References AllianceBuff, HordeBuff, m_AllianceTowersControlled, m_HordeTowersControlled, OutdoorPvP::SendUpdateWorldState(), TEAM_ALLIANCE, TEAM_HORDE, OutdoorPvP::TeamApplyBuff(), OutdoorPvP::TeamCastSpell(), OutdoorPvP::Update(), WORLD_STATE_OPVP_HP_UI_TOWER_COUNT_A, and WORLD_STATE_OPVP_HP_UI_TOWER_COUNT_H.
Member Data Documentation
m_AllianceTowersControlled
uint32 OutdoorPvPHP::m_AllianceTowersControlled private
Referenced by FillInitialWorldStates(), GetAllianceTowersControlled(), HandlePlayerEnterZone(), OutdoorPvPHP(), SetAllianceTowersControlled(), SetupOutdoorPvP(), and Update().
m_HordeTowersControlled
uint32 OutdoorPvPHP::m_HordeTowersControlled private
Referenced by FillInitialWorldStates(), GetHordeTowersControlled(), HandlePlayerEnterZone(), OutdoorPvPHP(), SetHordeTowersControlled(), SetupOutdoorPvP(), and Update().
The documentation for this class was generated from the following files:
azerothcore-wotlk/src/server/scripts/OutdoorPvP/OutdoorPvPHP.h
azerothcore-wotlk/src/server/scripts/OutdoorPvP/OutdoorPvPHP.cpp