AzerothCore Doxygen
ProcTestScenario Class Reference
Test context for proc simulation scenarios.
#include "ProcChanceTestHelper.h"
Public Member Functions
ProcTestScenario ()
void AdvanceTime (std::chrono::milliseconds duration)
std::chrono::steady_clock::time_point GetNow () const
UnitStub & GetActor ()
UnitStub const & GetActor () const
ProcTestScenario & WithActorLevel (uint8_t level)
ProcTestScenario & WithWeaponSpeed (uint8_t attackType, uint32_t speed)
std::unique_ptr< AuraStub > & GetAura ()
ProcTestScenario & WithAura (uint32_t spellId, uint8_t charges=0, uint8_t stacks=1)
bool SimulateProc (SpellProcEntry const &procEntry, float rollResult=0.0f)
Private Attributes
std::chrono::steady_clock::time_point _now
UnitStub _actor
std::unique_ptr< AuraStub > _aura
Detailed Description
Test context for proc simulation scenarios.
Constructor & Destructor Documentation
ProcTestScenario()
ProcTestScenario::ProcTestScenario () inline
: _now(std::chrono::steady_clock::now()) {}
Member Function Documentation
AdvanceTime()
void ProcTestScenario::AdvanceTime (std::chrono::milliseconds duration) inline
    {
        _now += duration;
    }
References _now.
Referenced by TEST_F(), TEST_F(), and TEST_P().
GetActor() [1/2]
UnitStub & ProcTestScenario::GetActor () inline
{ return _actor; }
References _actor.
GetActor() [2/2]
UnitStub const & ProcTestScenario::GetActor () const inline
{ return _actor; }
References _actor.
GetAura()
std::unique_ptr< AuraStub > & ProcTestScenario::GetAura () inline
{ return _aura; }
References _aura.
Referenced by TEST_F(), TEST_F(), and TEST_F().
GetNow()
std::chrono::steady_clock::time_point ProcTestScenario::GetNow () const inline
{ return _now; }
References _now.
SimulateProc()
bool ProcTestScenario::SimulateProc (SpellProcEntry const & procEntry, float rollResult = 0.0f) inline
    {
        if (!_aura)
            return false;
        // Check cooldown
        if (ProcChanceTestHelper::IsProcOnCooldown(_aura.get(), _now))
            return false;
        // Calculate chance
        float chance = ProcChanceTestHelper::SimulateCalcProcChance(
            procEntry,
            _actor.GetLevel(),
            _actor.GetAttackTime(0));
        // Roll check (rollResult of 0 means always pass)
        if (rollResult > 0.0f && rollResult > chance)
            return false;
        // Apply cooldown if set
        if (procEntry.Cooldown.count() > 0)
        {
            ProcChanceTestHelper::ApplyProcCooldown(_aura.get(), _now,
                static_cast<uint32>(procEntry.Cooldown.count()));
        }
        // Consume charges
        ProcChanceTestHelper::SimulateConsumeProcCharges(_aura.get(), procEntry);
        return true;
    }
References _actor, _aura, _now, ProcChanceTestHelper::ApplyProcCooldown(), SpellProcEntry::Cooldown, UnitStub::GetAttackTime(), UnitStub::GetLevel(), ProcChanceTestHelper::IsProcOnCooldown(), ProcChanceTestHelper::SimulateCalcProcChance(), and ProcChanceTestHelper::SimulateConsumeProcCharges().
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_P().
WithActorLevel()
ProcTestScenario & ProcTestScenario::WithActorLevel (uint8_t level) inline
    {
        _actor.SetLevel(level);
        return *this;
    }
References _actor, and UnitStub::SetLevel().
WithAura()
ProcTestScenario & ProcTestScenario::WithAura (uint32_t spellId, uint8_t charges = 0, uint8_t stacks = 1) inline
    {
        _aura = std::make_unique<AuraStub>(spellId);
        _aura->SetCharges(charges);
        _aura->SetUsingCharges(charges > 0);
        _aura->SetStackAmount(stacks);
        return *this;
    }
References _aura.
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_P().
WithWeaponSpeed()
ProcTestScenario & ProcTestScenario::WithWeaponSpeed (uint8_t attackType, uint32_t speed) inline
    {
        _actor.SetAttackTime(attackType, speed);
        return *this;
    }
References _actor, and UnitStub::SetAttackTime().
Member Data Documentation
_actor
UnitStub ProcTestScenario::_actor private
Referenced by GetActor(), GetActor(), SimulateProc(), WithActorLevel(), and WithWeaponSpeed().
_aura
std::unique_ptr<AuraStub> ProcTestScenario::_aura private
Referenced by GetAura(), SimulateProc(), and WithAura().
_now
std::chrono::steady_clock::time_point ProcTestScenario::_now private
Referenced by AdvanceTime(), GetNow(), and SimulateProc().
The documentation for this class was generated from the following file:
azerothcore-wotlk/src/test/mocks/ProcChanceTestHelper.h