AzerothCore Doxygen
BinarySpellDetectionTest.cpp File Reference
#include "SpellInfoTestHelper.h"
#include "SpellInfo.h"
#include "SharedDefines.h"
#include "gtest/gtest.h"
Classes
class BinarySpellDetectionTest
Functions
TEST_F (BinarySpellDetectionTest, AuraWithCalcValue_IsBinary)
TEST_F (BinarySpellDetectionTest, AuraWithZeroCalcValue_NotBinary)
TEST_F (BinarySpellDetectionTest, InterruptCast_IsBinary)
TEST_F (BinarySpellDetectionTest, InterruptCastWithNoImmunities_NotBinary)
TEST_F (BinarySpellDetectionTest, FearLikeSpell_SecondEffectHasValue_IsBinary)
TEST_F (BinarySpellDetectionTest, PolymorphLikeSpell_IsBinary)
TEST_F (BinarySpellDetectionTest, FrostNovaLikeSpell_IsBinary)
Function Documentation
TEST_F() [1/7]
TEST_F (BinarySpellDetectionTest , AuraWithCalcValue_IsBinary)
{
    auto spell = SpellInfoBuilder()
        .WithEffect(0, SPELL_EFFECT_APPLY_AURA, SPELL_AURA_MOD_FEAR)
        .WithEffectBasePoints(0, 0)
        .WithEffectDieSides(0, 1) // CalcValue = 0 + 1 = 1
        .WithSchoolMask(SPELL_SCHOOL_MASK_SHADOW)
        .BuildUnique();
    EXPECT_TRUE(ShouldMarkBinary(spell.get(), 0));
}
References SpellInfoBuilder::BuildUnique(), SPELL_AURA_MOD_FEAR, SPELL_EFFECT_APPLY_AURA, SPELL_SCHOOL_MASK_SHADOW, SpellInfoBuilder::WithEffect(), SpellInfoBuilder::WithEffectBasePoints(), SpellInfoBuilder::WithEffectDieSides(), and SpellInfoBuilder::WithSchoolMask().
TEST_F() [2/7]
TEST_F (BinarySpellDetectionTest , AuraWithZeroCalcValue_NotBinary)
{
    auto spell = SpellInfoBuilder()
        .WithEffect(0, SPELL_EFFECT_APPLY_AURA, SPELL_AURA_MOD_FEAR)
        .WithEffectBasePoints(0, 0)
        .WithEffectDieSides(0, 0) // CalcValue = 0
        .WithSchoolMask(SPELL_SCHOOL_MASK_SHADOW)
        .BuildUnique();
    EXPECT_FALSE(ShouldMarkBinary(spell.get(), 0));
}
References SpellInfoBuilder::BuildUnique(), SPELL_AURA_MOD_FEAR, SPELL_EFFECT_APPLY_AURA, SPELL_SCHOOL_MASK_SHADOW, SpellInfoBuilder::WithEffect(), SpellInfoBuilder::WithEffectBasePoints(), SpellInfoBuilder::WithEffectDieSides(), and SpellInfoBuilder::WithSchoolMask().
TEST_F() [3/7]
TEST_F (BinarySpellDetectionTest , FearLikeSpell_SecondEffectHasValue_IsBinary)
{
    auto spell = SpellInfoBuilder()
        .WithEffect(0, SPELL_EFFECT_APPLY_AURA, SPELL_AURA_MOD_FEAR)
        .WithEffectBasePoints(0, -1)
        .WithEffectDieSides(0, 1) // CalcValue = -1 + 1 = 0
        .WithEffect(1, SPELL_EFFECT_APPLY_AURA, SPELL_AURA_MOD_INCREASE_SPEED)
        .WithEffectBasePoints(1, 24)
        .WithEffectDieSides(1, 1) // CalcValue = 24 + 1 = 25
        .WithSchoolMask(SPELL_SCHOOL_MASK_SHADOW)
        .BuildUnique();
    // Effect 0 has CalcValue 0, should not mark binary
    EXPECT_FALSE(ShouldMarkBinary(spell.get(), 0));
    // Effect 1 has CalcValue 25, should mark binary
    EXPECT_TRUE(ShouldMarkBinary(spell.get(), 1));
}
References SpellInfoBuilder::BuildUnique(), SPELL_AURA_MOD_FEAR, SPELL_AURA_MOD_INCREASE_SPEED, SPELL_EFFECT_APPLY_AURA, SPELL_SCHOOL_MASK_SHADOW, SpellInfoBuilder::WithEffect(), SpellInfoBuilder::WithEffectBasePoints(), SpellInfoBuilder::WithEffectDieSides(), and SpellInfoBuilder::WithSchoolMask().
TEST_F() [4/7]
TEST_F (BinarySpellDetectionTest , FrostNovaLikeSpell_IsBinary)
{
    auto spell = SpellInfoBuilder()
        .WithEffect(0, SPELL_EFFECT_APPLY_AURA, SPELL_AURA_MOD_ROOT)
        .WithEffectBasePoints(0, 0)
        .WithEffectDieSides(0, 1) // CalcValue = 1
        .WithSchoolMask(SPELL_SCHOOL_MASK_FROST)
        .BuildUnique();
    EXPECT_TRUE(ShouldMarkBinary(spell.get(), 0));
}
References SpellInfoBuilder::BuildUnique(), SPELL_AURA_MOD_ROOT, SPELL_EFFECT_APPLY_AURA, SPELL_SCHOOL_MASK_FROST, SpellInfoBuilder::WithEffect(), SpellInfoBuilder::WithEffectBasePoints(), SpellInfoBuilder::WithEffectDieSides(), and SpellInfoBuilder::WithSchoolMask().
TEST_F() [5/7]
TEST_F (BinarySpellDetectionTest , InterruptCast_IsBinary)
{
    auto spell = SpellInfoBuilder()
        .WithEffect(0, SPELL_EFFECT_INTERRUPT_CAST)
        .WithEffectBasePoints(0, 0)
        .WithEffectDieSides(0, 0) // CalcValue = 0
        .WithSchoolMask(SPELL_SCHOOL_MASK_SHADOW)
        .BuildUnique();
    EXPECT_TRUE(ShouldMarkBinary(spell.get(), 0));
}
References SpellInfoBuilder::BuildUnique(), SPELL_EFFECT_INTERRUPT_CAST, SPELL_SCHOOL_MASK_SHADOW, SpellInfoBuilder::WithEffect(), SpellInfoBuilder::WithEffectBasePoints(), SpellInfoBuilder::WithEffectDieSides(), and SpellInfoBuilder::WithSchoolMask().
TEST_F() [6/7]
TEST_F (BinarySpellDetectionTest , InterruptCastWithNoImmunities_NotBinary)
{
    auto spell = SpellInfoBuilder()
        .WithEffect(0, SPELL_EFFECT_INTERRUPT_CAST)
        .WithEffectBasePoints(0, 0)
        .WithEffectDieSides(0, 0)
        .WithAttributes(SPELL_ATTR0_NO_IMMUNITIES)
        .WithSchoolMask(SPELL_SCHOOL_MASK_SHADOW)
        .BuildUnique();
    EXPECT_FALSE(ShouldMarkBinary(spell.get(), 0));
}
References SpellInfoBuilder::BuildUnique(), SPELL_ATTR0_NO_IMMUNITIES, SPELL_EFFECT_INTERRUPT_CAST, SPELL_SCHOOL_MASK_SHADOW, SpellInfoBuilder::WithAttributes(), SpellInfoBuilder::WithEffect(), SpellInfoBuilder::WithEffectBasePoints(), SpellInfoBuilder::WithEffectDieSides(), and SpellInfoBuilder::WithSchoolMask().
TEST_F() [7/7]
TEST_F (BinarySpellDetectionTest , PolymorphLikeSpell_IsBinary)
{
    auto spell = SpellInfoBuilder()
        .WithEffect(0, SPELL_EFFECT_APPLY_AURA, SPELL_AURA_MOD_CONFUSE)
        .WithEffectBasePoints(0, 0)
        .WithEffectDieSides(0, 1) // CalcValue = 1
        .WithSchoolMask(SPELL_SCHOOL_MASK_ARCANE)
        .BuildUnique();
    EXPECT_TRUE(ShouldMarkBinary(spell.get(), 0));
}
References SpellInfoBuilder::BuildUnique(), SPELL_AURA_MOD_CONFUSE, SPELL_EFFECT_APPLY_AURA, SPELL_SCHOOL_MASK_ARCANE, SpellInfoBuilder::WithEffect(), SpellInfoBuilder::WithEffectBasePoints(), SpellInfoBuilder::WithEffectDieSides(), and SpellInfoBuilder::WithSchoolMask().