AzerothCore Doxygen
GameObjectSummonGroupTest.cpp File Reference
#include "ObjectMgr.h"
#include "SmartScriptMgr.h"
#include "TemporarySummon.h"
#include "WorldMock.h"
#include "gtest/gtest.h"
Classes
class GameObjectSummonGroupTest
Functions
TEST_F (GameObjectSummonGroupTest, DataStructStoresFields)
TEST_F (GameObjectSummonGroupTest, QuaternionIdentity)
TEST_F (GameObjectSummonGroupTest, AccessorReturnsNullForMissing)
TEST_F (GameObjectSummonGroupTest, AccessorReturnsNullForAllTypes)
TEST_F (GameObjectSummonGroupTest, DifferentGroupsAreIndependent)
TEST_F (GameObjectSummonGroupTest, SmartActionEnumValue)
TEST_F (GameObjectSummonGroupTest, SmartActionUnionSize)
TEST_F (GameObjectSummonGroupTest, TempSummonGroupKeyOrdering)
TEST_F (GameObjectSummonGroupTest, SummonerTypeValues)
Function Documentation
TEST_F() [1/9]
TEST_F (GameObjectSummonGroupTest , AccessorReturnsNullForAllTypes)
{
    auto const* r1 = sObjectMgr->GetGameObjectSummonGroup(
        99999, SUMMONER_TYPE_CREATURE, 0);
    auto const* r2 = sObjectMgr->GetGameObjectSummonGroup(
        99999, SUMMONER_TYPE_GAMEOBJECT, 0);
    auto const* r3 = sObjectMgr->GetGameObjectSummonGroup(
        99999, SUMMONER_TYPE_MAP, 0);
    EXPECT_EQ(r1, nullptr);
    EXPECT_EQ(r2, nullptr);
    EXPECT_EQ(r3, nullptr);
}
References sObjectMgr, SUMMONER_TYPE_CREATURE, SUMMONER_TYPE_GAMEOBJECT, and SUMMONER_TYPE_MAP.
TEST_F() [2/9]
TEST_F (GameObjectSummonGroupTest , AccessorReturnsNullForMissing)
{
    auto const* result = sObjectMgr->GetGameObjectSummonGroup(
        99999, SUMMONER_TYPE_CREATURE, 0);
    EXPECT_EQ(result, nullptr);
}
References sObjectMgr, and SUMMONER_TYPE_CREATURE.
TEST_F() [3/9]
TEST_F (GameObjectSummonGroupTest , DataStructStoresFields)
{
    GameObjectSummonData data;
    data.entry = 2332;
    data.pos.Relocate(-14652.38f, 146.51f, 3.50f, 0.35f);
    data.rot = G3D::Quat(0.0f, 0.0f, 0.17f, 0.98f);
    data.respawnTime = 120;
    EXPECT_EQ(data.entry, 2332u);
    EXPECT_FLOAT_EQ(data.pos.GetPositionX(), -14652.38f);
    EXPECT_FLOAT_EQ(data.pos.GetPositionY(), 146.51f);
    EXPECT_FLOAT_EQ(data.pos.GetPositionZ(), 3.50f);
    EXPECT_FLOAT_EQ(data.pos.GetOrientation(), 0.35f);
    EXPECT_FLOAT_EQ(data.rot.x, 0.0f);
    EXPECT_FLOAT_EQ(data.rot.y, 0.0f);
    EXPECT_FLOAT_EQ(data.rot.z, 0.17f);
    EXPECT_FLOAT_EQ(data.rot.w, 0.98f);
    EXPECT_EQ(data.respawnTime, 120u);
}
References GameObjectSummonData::entry, Position::GetOrientation(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), GameObjectSummonData::pos, Position::Relocate(), GameObjectSummonData::respawnTime, and GameObjectSummonData::rot.
TEST_F() [4/9]
TEST_F (GameObjectSummonGroupTest , DifferentGroupsAreIndependent)
{
    auto const* g0 = sObjectMgr->GetGameObjectSummonGroup(
        2289, SUMMONER_TYPE_GAMEOBJECT, 0);
    auto const* g1 = sObjectMgr->GetGameObjectSummonGroup(
        2289, SUMMONER_TYPE_GAMEOBJECT, 1);
    // Both should be null since DB isn't loaded in tests,
    // but they should be independent lookups
    EXPECT_EQ(g0, nullptr);
    EXPECT_EQ(g1, nullptr);
}
References sObjectMgr, and SUMMONER_TYPE_GAMEOBJECT.
TEST_F() [5/9]
TEST_F (GameObjectSummonGroupTest , QuaternionIdentity)
{
    GameObjectSummonData data;
    data.rot = G3D::Quat(0.0f, 0.0f, 0.0f, 1.0f);
    EXPECT_FLOAT_EQ(data.rot.x, 0.0f);
    EXPECT_FLOAT_EQ(data.rot.y, 0.0f);
    EXPECT_FLOAT_EQ(data.rot.z, 0.0f);
    EXPECT_FLOAT_EQ(data.rot.w, 1.0f);
}
References GameObjectSummonData::rot.
TEST_F() [6/9]
TEST_F (GameObjectSummonGroupTest , SmartActionEnumValue)
{
    EXPECT_EQ(SMART_ACTION_SUMMON_GAMEOBJECT_GROUP, 241);
    EXPECT_EQ(SMART_ACTION_AC_END, 242);
}
References SMART_ACTION_AC_END, and SMART_ACTION_SUMMON_GAMEOBJECT_GROUP.
TEST_F() [7/9]
TEST_F (GameObjectSummonGroupTest , SmartActionUnionSize)
{
    SmartAction action{};
    action.gameobjectGroup.group = 5;
    EXPECT_EQ(action.gameobjectGroup.group, 5u);
}
References SmartAction::gameobjectGroup, and SmartAction::group.
TEST_F() [8/9]
TEST_F (GameObjectSummonGroupTest , SummonerTypeValues)
{
    EXPECT_EQ(SUMMONER_TYPE_CREATURE, 0);
    EXPECT_EQ(SUMMONER_TYPE_GAMEOBJECT, 1);
    EXPECT_EQ(SUMMONER_TYPE_MAP, 2);
}
References SUMMONER_TYPE_CREATURE, SUMMONER_TYPE_GAMEOBJECT, and SUMMONER_TYPE_MAP.
TEST_F() [9/9]
TEST_F (GameObjectSummonGroupTest , TempSummonGroupKeyOrdering)
{
    TempSummonGroupKey k1(100, SUMMONER_TYPE_CREATURE, 0);
    TempSummonGroupKey k2(100, SUMMONER_TYPE_GAMEOBJECT, 0);
    TempSummonGroupKey k3(100, SUMMONER_TYPE_CREATURE, 1);
    TempSummonGroupKey k4(200, SUMMONER_TYPE_CREATURE, 0);
    // std::tuple ordering: summoner ID first, then type, then group
    EXPECT_LT(k1, k2);  // same id, creature < gameobject
    EXPECT_LT(k1, k3);  // same id+type, group 0 < 1
    EXPECT_LT(k1, k4);  // id 100 < 200
}
References SUMMONER_TYPE_CREATURE, and SUMMONER_TYPE_GAMEOBJECT.