AzerothCore Doxygen
WorldSessionMgr Class Reference
#include "WorldSessionMgr.h"
Public Types
typedef std::unordered_map< uint32, WorldSession * > SessionMap
Public Member Functions
WorldSessionMgr ()
~WorldSessionMgr ()
WorldSession * FindSession (uint32 id) const
Find a session by its id.
WorldSession * FindOfflineSession (uint32 id) const
WorldSession * FindOfflineSessionForCharacterGUID (ObjectGuid::LowType guidLow) const
void UpdateSessions (uint32 const diff)
bool KickSession (uint32 id)
Remove a given session.
void KickAll ()
Kick (and save) all players.
void KickAllLess (AccountTypes sec)
Kick (and save) all players with security level less sec
void AddSession (WorldSession *session)
void AddQueuedPlayer (WorldSession *session)
bool RemoveQueuedPlayer (WorldSession *session)
int32 GetQueuePos (WorldSession *session)
bool HasRecentlyDisconnected (WorldSession *session)
SessionMap const & GetAllSessions () const
void UpdateMaxSessionCounters ()
Get the number of current active sessions.
uint32 GetActiveAndQueuedSessionCount () const
uint32 GetActiveSessionCount () const
uint32 GetQueuedSessionCount () const
uint32 GetMaxQueuedSessionCount () const
Get the maximum number of parallel sessions on the server since last reboot.
uint32 GetMaxActiveSessionCount () const
uint32 GetPlayerCount () const
Get number of players.
uint32 GetMaxPlayerCount () const
void SetPlayerAmountLimit (uint32 limit)
Active session server limit.
uint32 GetPlayerAmountLimit () const
void IncreasePlayerCount ()
Increase/Decrease number of players.
void DecreasePlayerCount ()
void SendGlobalMessage (WorldPacket const *packet, WorldSession *self=nullptr, TeamId teamId=TEAM_NEUTRAL)
Send a packet to all players (except self if mentioned)
void SendGlobalGMMessage (WorldPacket const *packet, WorldSession *self=nullptr, TeamId teamId=TEAM_NEUTRAL)
Send a packet to all GMs (except self if mentioned)
bool SendZoneMessage (uint32 zone, WorldPacket const *packet, WorldSession *self=nullptr, TeamId teamId=TEAM_NEUTRAL)
Send a packet to all players (or players selected team) in the zone (except self if mentioned)
void SendZoneText (uint32 zone, std::string text, WorldSession *self=nullptr, TeamId teamId=TEAM_NEUTRAL)
Send a System Message to all players in the zone (except self if mentioned)
void SendServerMessage (ServerMessageType messageID, std::string stringParam="", Player *player=nullptr)
Send a server message to the user(s)
void DoForAllOnlinePlayers (std::function< void(Player *)> exec)
Static Public Member Functions
static WorldSessionMgr * Instance ()
Private Types
typedef std::unordered_map< uint32, time_t > DisconnectMap
typedef std::list< WorldSession * > Queue
Private Member Functions
void AddSession_ (WorldSession *session)
Private Attributes
LockedQueue< WorldSession * > _addSessQueue
SessionMap _sessions
SessionMap _offlineSessions
DisconnectMap _disconnects
Queue _queuedPlayer
uint32 _playerLimit
uint32 _maxActiveSessionCount
uint32 _maxQueuedSessionCount
uint32 _playerCount
uint32 _maxPlayerCount
Detailed Description
Member Typedef Documentation
DisconnectMap
typedef std::unordered_map<uint32, time_t> WorldSessionMgr::DisconnectMap private
Queue
typedef std::list<WorldSession*> WorldSessionMgr::Queue private
SessionMap
typedef std::unordered_map<uint32, WorldSession*> WorldSessionMgr::SessionMap
Constructor & Destructor Documentation
WorldSessionMgr()
WorldSessionMgr::WorldSessionMgr ()
{
    _playerLimit = 0;
    _maxActiveSessionCount = 0;
    _maxQueuedSessionCount = 0;
    _playerCount = 0;
    _maxPlayerCount = 0;
}
References _maxActiveSessionCount, _maxPlayerCount, _maxQueuedSessionCount, _playerCount, and _playerLimit.
~WorldSessionMgr()
WorldSessionMgr::~WorldSessionMgr ()
Empty the kicked session set
{
    while (!_sessions.empty())
    {
        // not remove from queue, prevent loading new sessions
        delete _sessions.begin()->second;
        _sessions.erase(_sessions.begin());
    }
    while (!_offlineSessions.empty())
    {
        delete _offlineSessions.begin()->second;
        _offlineSessions.erase(_offlineSessions.begin());
    }
}
References _offlineSessions, and _sessions.
Member Function Documentation
AddQueuedPlayer()
void WorldSessionMgr::AddQueuedPlayer (WorldSession * session)
{
    session->SetInQueue(true);
    _queuedPlayer.push_back(session);
    // The 1st SMSG_AUTH_RESPONSE needs to contain other info too.
    session->SendAuthResponse(AUTH_WAIT_QUEUE, false, GetQueuePos(session));
}
References _queuedPlayer, AUTH_WAIT_QUEUE, GetQueuePos(), WorldSession::SendAuthResponse(), and WorldSession::SetInQueue().
Referenced by AddSession_().
AddSession()
void WorldSessionMgr::AddSession (WorldSession * session)
{
    _addSessQueue.add(session);
}
References _addSessQueue, and LockedQueue< T, StorageType >::add().
AddSession_()
void WorldSessionMgr::AddSession_ (WorldSession * session) private
{
    ASSERT(session);
    // kick existing session with same account (if any)
    // if character on old session is being loaded, then return
    if (!KickSession(session->GetAccountId()))
    {
        session->KickPlayer("kick existing session with same account");
        delete session; // session not added yet in session list, so not listed in queue
        return;
    }
    SessionMap::const_iterator old = _sessions.find(session->GetAccountId());
    if (old != _sessions.end())
    {
        WorldSession* oldSession = old->second;
        if (!RemoveQueuedPlayer(oldSession) && sWorld->getIntConfig(CONFIG_INTERVAL_DISCONNECT_TOLERANCE))
            _disconnects[session->GetAccountId()] = GameTime::GetGameTime().count();
        // pussywizard:
        if (oldSession->HandleSocketClosed())
        {
            // there should be no offline session if current one is logged onto a character
            SessionMap::iterator iter;
            if ((iter = _offlineSessions.find(oldSession->GetAccountId())) != _offlineSessions.end())
            {
                WorldSession* tmp = iter->second;
                _offlineSessions.erase(iter);
                delete tmp;
            }
            oldSession->SetOfflineTime(GameTime::GetGameTime().count());
            _offlineSessions[oldSession->GetAccountId()] = oldSession;
        }
        else
        {
            delete oldSession;
        }
    }
    _sessions[session->GetAccountId()] = session;
    uint32 Sessions = GetActiveAndQueuedSessionCount();
    uint32 pLimit = GetPlayerAmountLimit();
    // don't count this session when checking player limit
    --Sessions;
    if (pLimit > 0 && Sessions >= pLimit && AccountMgr::IsPlayerAccount(session->GetSecurity()) && !session->CanSkipQueue() && !HasRecentlyDisconnected(session))
    {
        AddQueuedPlayer(session);
        UpdateMaxSessionCounters();
        return;
    }
    session->InitializeSession();
    UpdateMaxSessionCounters();
}
References _disconnects, _offlineSessions, _sessions, AddQueuedPlayer(), ASSERT, WorldSession::CanSkipQueue(), CONFIG_INTERVAL_DISCONNECT_TOLERANCE, WorldSession::GetAccountId(), GetActiveAndQueuedSessionCount(), GameTime::GetGameTime(), GetPlayerAmountLimit(), WorldSession::GetSecurity(), WorldSession::HandleSocketClosed(), HasRecentlyDisconnected(), WorldSession::InitializeSession(), AccountMgr::IsPlayerAccount(), WorldSession::KickPlayer(), KickSession(), RemoveQueuedPlayer(), WorldSession::SetOfflineTime(), sWorld, and UpdateMaxSessionCounters().
Referenced by UpdateSessions().
DecreasePlayerCount()
void WorldSessionMgr::DecreasePlayerCount () inline
{ _playerCount--; }
References _playerCount.
DoForAllOnlinePlayers()
void WorldSessionMgr::DoForAllOnlinePlayers (std::function< void(Player *)> exec)
{
    std::shared_lock lock(*HashMapHolder<Player>::GetLock());
    for (auto const& it : ObjectAccessor::GetPlayers())
    {
        if (Player* player = it.second)
        {
            if (!player->IsInWorld())
            {
                continue;
            }
            exec(player);
        }
    }
}
References ObjectAccessor::GetPlayers().
FindOfflineSession()
WorldSession * WorldSessionMgr::FindOfflineSession (uint32 id) const
{
    SessionMap::const_iterator itr = _offlineSessions.find(id);
    if (itr != _offlineSessions.end())
        return itr->second;
    else
        return nullptr;
}
References _offlineSessions.
FindOfflineSessionForCharacterGUID()
WorldSession * WorldSessionMgr::FindOfflineSessionForCharacterGUID (ObjectGuid::LowType guidLow) const
{
    if (_offlineSessions.empty())
        return nullptr;
    for (SessionMap::const_iterator itr = _offlineSessions.begin(); itr != _offlineSessions.end(); ++itr)
        if (itr->second->GetGuidLow() == guidLow)
            return itr->second;
    return nullptr;
}
References _offlineSessions.
FindSession()
WorldSession * WorldSessionMgr::FindSession (uint32 id) const
Find a session by its id.
{
    SessionMap::const_iterator itr = _sessions.find(id);
    if (itr != _sessions.end())
        return itr->second;                                 // also can return nullptr for kicked session
    else
        return nullptr;
}
References _sessions.
GetActiveAndQueuedSessionCount()
uint32 WorldSessionMgr::GetActiveAndQueuedSessionCount () const inline
{ return _sessions.size(); }
References _sessions.
Referenced by AddSession_().
GetActiveSessionCount()
uint32 WorldSessionMgr::GetActiveSessionCount () const inline
{ return _sessions.size() - _queuedPlayer.size(); }
References _queuedPlayer, and _sessions.
Referenced by RemoveQueuedPlayer().
GetAllSessions()
SessionMap const & WorldSessionMgr::GetAllSessions () const inline
{ return _sessions; }
References _sessions.
GetMaxActiveSessionCount()
uint32 WorldSessionMgr::GetMaxActiveSessionCount () const inline
{ return _maxActiveSessionCount; }
References _maxActiveSessionCount.
GetMaxPlayerCount()
uint32 WorldSessionMgr::GetMaxPlayerCount () const inline
{ return _maxPlayerCount; }
References _maxPlayerCount.
GetMaxQueuedSessionCount()
uint32 WorldSessionMgr::GetMaxQueuedSessionCount () const inline
Get the maximum number of parallel sessions on the server since last reboot.
{ return _maxQueuedSessionCount; }
References _maxQueuedSessionCount.
GetPlayerAmountLimit()
uint32 WorldSessionMgr::GetPlayerAmountLimit () const inline
{ return _playerLimit; }
References _playerLimit.
Referenced by AddSession_(), and RemoveQueuedPlayer().
GetPlayerCount()
uint32 WorldSessionMgr::GetPlayerCount () const inline
Get number of players.
{ return _playerCount; }
References _playerCount.
GetQueuedSessionCount()
uint32 WorldSessionMgr::GetQueuedSessionCount () const inline
{ return _queuedPlayer.size(); }
References _queuedPlayer.
GetQueuePos()
int32 WorldSessionMgr::GetQueuePos (WorldSession * session)
{
    uint32 position = 1;
    for (Queue::const_iterator iter = _queuedPlayer.begin(); iter != _queuedPlayer.end(); ++iter, ++position)
        if ((*iter) == session)
            return position;
    return 0;
}
References _queuedPlayer.
Referenced by AddQueuedPlayer().
HasRecentlyDisconnected()
bool WorldSessionMgr::HasRecentlyDisconnected (WorldSession * session)
{
    if (!session)
        return false;
    if (uint32 tolerance = sWorld->getIntConfig(CONFIG_INTERVAL_DISCONNECT_TOLERANCE))
    {
        for (DisconnectMap::iterator i = _disconnects.begin(); i != _disconnects.end();)
        {
            if ((GameTime::GetGameTime().count() - i->second) < tolerance)
            {
                if (i->first == session->GetAccountId())
                    return true;
                ++i;
            }
            else
                _disconnects.erase(i++);
        }
    }
    return false;
}
References _disconnects, CONFIG_INTERVAL_DISCONNECT_TOLERANCE, WorldSession::GetAccountId(), GameTime::GetGameTime(), and sWorld.
Referenced by AddSession_().
IncreasePlayerCount()
void WorldSessionMgr::IncreasePlayerCount () inline
Increase/Decrease number of players.
    {
        _playerCount++;
        _maxPlayerCount = std::max(_maxPlayerCount, _playerCount);
    }
References _maxPlayerCount, and _playerCount.
Instance()
WorldSessionMgr * WorldSessionMgr::Instance () static
{
    static WorldSessionMgr instance;
    return &instance;
}
KickAll()
void WorldSessionMgr::KickAll ()
Kick (and save) all players.
{
    _queuedPlayer.clear();                                 // prevent send queue update packet and login queued sessions
    // session not removed at kick and will removed in next update tick
    for (SessionMap::const_iterator itr = _sessions.begin(); itr != _sessions.end(); ++itr)
        itr->second->KickPlayer("KickAll sessions");
    // pussywizard: kick offline sessions
    for (SessionMap::const_iterator itr = _offlineSessions.begin(); itr != _offlineSessions.end(); ++itr)
        itr->second->KickPlayer("KickAll offline sessions");
}
References _offlineSessions, _queuedPlayer, and _sessions.
KickAllLess()
void WorldSessionMgr::KickAllLess (AccountTypes sec)
Kick (and save) all players with security level less sec
{
    // session not removed at kick and will removed in next update tick
    for (SessionMap::const_iterator itr = _sessions.begin(); itr != _sessions.end(); ++itr)
        if (itr->second->GetSecurity() < sec)
            itr->second->KickPlayer("KickAllLess");
}
References _sessions.
KickSession()
bool WorldSessionMgr::KickSession (uint32 id)
Remove a given session.
Find the session, kick the user, but we can't delete session at this moment to prevent iterator invalidation
{
    SessionMap::const_iterator itr = _sessions.find(id);
    if (itr != _sessions.end() && itr->second)
    {
        if (itr->second->PlayerLoading())
            return false;
        itr->second->KickPlayer("KickSession", false);
    }
    return true;
}
References _sessions, and WorldSession::KickPlayer().
Referenced by AddSession_().
RemoveQueuedPlayer()
bool WorldSessionMgr::RemoveQueuedPlayer (WorldSession * session)
{
    uint32 sessions = GetActiveSessionCount();
    uint32 position = 1;
    Queue::iterator iter = _queuedPlayer.begin();
    // search to remove and count skipped positions
    bool found = false;
    for (; iter != _queuedPlayer.end(); ++iter, ++position)
    {
        if (*iter == session)
        {
            session->SetInQueue(false);
            session->ResetTimeOutTime(false);
            iter = _queuedPlayer.erase(iter);
            found = true;
            break;
        }
    }
    // if session not queued then it was an active session
    if (!found)
    {
        ASSERT(sessions > 0);
        --sessions;
    }
    // accept first in queue
    if ((!GetPlayerAmountLimit() || sessions < GetPlayerAmountLimit()) && !_queuedPlayer.empty())
    {
        WorldSession* pop_sess = _queuedPlayer.front();
        pop_sess->InitializeSession();
        _queuedPlayer.pop_front();
        // update iter to point first queued socket or end() if queue is empty now
        iter = _queuedPlayer.begin();
        position = 1;
    }
    // update queue position from iter to end()
    for (; iter != _queuedPlayer.end(); ++iter, ++position)
        (*iter)->SendAuthWaitQueue(position);
    return found;
}
References _queuedPlayer, ASSERT, GetActiveSessionCount(), GetPlayerAmountLimit(), WorldSession::InitializeSession(), WorldSession::ResetTimeOutTime(), and WorldSession::SetInQueue().
Referenced by AddSession_(), and UpdateSessions().
SendGlobalGMMessage()
void WorldSessionMgr::SendGlobalGMMessage (WorldPacket const * packet, WorldSession * self = nullptr, TeamId teamId = TEAM_NEUTRAL)
Send a packet to all GMs (except self if mentioned)
{
    SessionMap::iterator itr;
    for (itr = _sessions.begin(); itr != _sessions.end(); ++itr)
    {
        if (itr->second &&
            itr->second->GetPlayer() &&
            itr->second->GetPlayer()->IsInWorld() &&
            itr->second != self &&
            !AccountMgr::IsPlayerAccount(itr->second->GetSecurity()) &&
            (teamId == TEAM_NEUTRAL || itr->second->GetPlayer()->GetTeamId() == teamId))
        {
            itr->second->SendPacket(packet);
        }
    }
}
References _sessions, AccountMgr::IsPlayerAccount(), and TEAM_NEUTRAL.
SendGlobalMessage()
void WorldSessionMgr::SendGlobalMessage (WorldPacket const * packet, WorldSession * self = nullptr, TeamId teamId = TEAM_NEUTRAL)
Send a packet to all players (except self if mentioned)
{
    SessionMap::const_iterator itr;
    for (itr = _sessions.begin(); itr != _sessions.end(); ++itr)
    {
        if (itr->second &&
            itr->second->GetPlayer() &&
            itr->second->GetPlayer()->IsInWorld() &&
            itr->second != self &&
            (teamId == TEAM_NEUTRAL || itr->second->GetPlayer()->GetTeamId() == teamId))
        {
            itr->second->SendPacket(packet);
        }
    }
}
References _sessions, and TEAM_NEUTRAL.
Referenced by SendServerMessage().
SendServerMessage()
void WorldSessionMgr::SendServerMessage (ServerMessageType messageID, std::string stringParam = "", Player * player = nullptr)
Send a server message to the user(s)
{
    WorldPackets::Chat::ChatServerMessage chatServerMessage;
    chatServerMessage.MessageID = int32(messageID);
    if (messageID <= SERVER_MSG_STRING)
        chatServerMessage.StringParam = stringParam;
    if (player)
        player->SendDirectMessage(chatServerMessage.Write());
    else
        SendGlobalMessage(chatServerMessage.Write());
}
References WorldPackets::Chat::ChatServerMessage::MessageID, Player::SendDirectMessage(), SendGlobalMessage(), SERVER_MSG_STRING, WorldPackets::Chat::ChatServerMessage::StringParam, and WorldPackets::Chat::ChatServerMessage::Write().
SendZoneMessage()
bool WorldSessionMgr::SendZoneMessage (uint32 zone, WorldPacket const * packet, WorldSession * self = nullptr, TeamId teamId = TEAM_NEUTRAL)
Send a packet to all players (or players selected team) in the zone (except self if mentioned)
{
    bool foundPlayerToSend = false;
    SessionMap::const_iterator itr;
    for (itr = _sessions.begin(); itr != _sessions.end(); ++itr)
    {
        if (itr->second &&
            itr->second->GetPlayer() &&
            itr->second->GetPlayer()->IsInWorld() &&
            itr->second->GetPlayer()->GetZoneId() == zone &&
            itr->second != self &&
            (teamId == TEAM_NEUTRAL || itr->second->GetPlayer()->GetTeamId() == teamId))
        {
            itr->second->SendPacket(packet);
            foundPlayerToSend = true;
        }
    }
    return foundPlayerToSend;
}
References _sessions, and TEAM_NEUTRAL.
Referenced by SendZoneText().
SendZoneText()
void WorldSessionMgr::SendZoneText (uint32 zone, std::string text, WorldSession * self = nullptr, TeamId teamId = TEAM_NEUTRAL)
Send a System Message to all players in the zone (except self if mentioned)
{
    WorldPacket data;
    ChatHandler::BuildChatPacket(data, CHAT_MSG_SYSTEM, LANG_UNIVERSAL, nullptr, nullptr, text.c_str());
    SendZoneMessage(zone, &data, self, teamId);
}
References ChatHandler::BuildChatPacket(), CHAT_MSG_SYSTEM, LANG_UNIVERSAL, and SendZoneMessage().
SetPlayerAmountLimit()
void WorldSessionMgr::SetPlayerAmountLimit (uint32 limit) inline
Active session server limit.
{ _playerLimit = limit; }
References _playerLimit.
UpdateMaxSessionCounters()
void WorldSessionMgr::UpdateMaxSessionCounters ()
Get the number of current active sessions.
{
    _maxActiveSessionCount = std::max(_maxActiveSessionCount, uint32(_sessions.size() - _queuedPlayer.size()));
    _maxQueuedSessionCount = std::max(_maxQueuedSessionCount, uint32(_queuedPlayer.size()));
}
References _maxActiveSessionCount, _maxQueuedSessionCount, _queuedPlayer, and _sessions.
Referenced by AddSession_().
UpdateSessions()
void WorldSessionMgr::UpdateSessions (uint32 const diff)
Add new sessions
Then send an update signal to remaining ones
and remove not active sessions from the list
{
    {
        METRIC_DETAILED_NO_THRESHOLD_TIMER("world_update_time",
            METRIC_TAG("type", "Add sessions"),
            METRIC_TAG("parent_type", "Update sessions"));
        WorldSession* sess = nullptr;
        while (_addSessQueue.next(sess))
        {
            AddSession_(sess);
        }
    }
    for (SessionMap::iterator itr = _sessions.begin(), next; itr != _sessions.end(); itr = next)
    {
        next = itr;
        ++next;
        WorldSession* pSession = itr->second;
        WorldSessionFilter updater(pSession);
        // pussywizard:
        if (pSession->HandleSocketClosed())
        {
            if (!RemoveQueuedPlayer(pSession) && sWorld->getIntConfig(CONFIG_INTERVAL_DISCONNECT_TOLERANCE))
                _disconnects[pSession->GetAccountId()] = GameTime::GetGameTime().count();
            _sessions.erase(itr);
            // there should be no offline session if current one is logged onto a character
            SessionMap::iterator iter;
            if ((iter = _offlineSessions.find(pSession->GetAccountId())) != _offlineSessions.end())
            {
                WorldSession* tmp = iter->second;
                _offlineSessions.erase(iter);
                delete tmp;
            }
            pSession->SetOfflineTime(GameTime::GetGameTime().count());
            _offlineSessions[pSession->GetAccountId()] = pSession;
            continue;
        }
        [[maybe_unused]] uint32 currentSessionId = itr->first;
        METRIC_DETAILED_TIMER("world_update_sessions_time", METRIC_TAG("account_id", std::to_string(currentSessionId)));
        if (!pSession->Update(diff, updater))
        {
            if (!RemoveQueuedPlayer(pSession) && sWorld->getIntConfig(CONFIG_INTERVAL_DISCONNECT_TOLERANCE))
                _disconnects[pSession->GetAccountId()] = GameTime::GetGameTime().count();
            _sessions.erase(itr);
            delete pSession;
        }
    }
    // pussywizard:
    if (_offlineSessions.empty())
        return;
    uint32 currTime = GameTime::GetGameTime().count();
    for (SessionMap::iterator itr = _offlineSessions.begin(), next; itr != _offlineSessions.end(); itr = next)
    {
        next = itr;
        ++next;
        WorldSession* pSession = itr->second;
        if (!pSession->GetPlayer() || pSession->GetOfflineTime() + 60 < currTime || pSession->IsKicked())
        {
            _offlineSessions.erase(itr);
            delete pSession;
        }
    }
}
References _addSessQueue, _disconnects, _offlineSessions, _sessions, AddSession_(), CONFIG_INTERVAL_DISCONNECT_TOLERANCE, WorldSession::GetAccountId(), GameTime::GetGameTime(), WorldSession::GetOfflineTime(), WorldSession::GetPlayer(), WorldSession::HandleSocketClosed(), WorldSession::IsKicked(), METRIC_DETAILED_NO_THRESHOLD_TIMER, METRIC_DETAILED_TIMER, METRIC_TAG, LockedQueue< T, StorageType >::next(), RemoveQueuedPlayer(), WorldSession::SetOfflineTime(), sWorld, and WorldSession::Update().
Member Data Documentation
_addSessQueue
LockedQueue<WorldSession*> WorldSessionMgr::_addSessQueue private
Referenced by AddSession(), and UpdateSessions().
_disconnects
DisconnectMap WorldSessionMgr::_disconnects private
Referenced by AddSession_(), HasRecentlyDisconnected(), and UpdateSessions().
_maxActiveSessionCount
uint32 WorldSessionMgr::_maxActiveSessionCount private
Referenced by GetMaxActiveSessionCount(), UpdateMaxSessionCounters(), and WorldSessionMgr().
_maxPlayerCount
uint32 WorldSessionMgr::_maxPlayerCount private
Referenced by GetMaxPlayerCount(), IncreasePlayerCount(), and WorldSessionMgr().
_maxQueuedSessionCount
uint32 WorldSessionMgr::_maxQueuedSessionCount private
Referenced by GetMaxQueuedSessionCount(), UpdateMaxSessionCounters(), and WorldSessionMgr().
_offlineSessions
SessionMap WorldSessionMgr::_offlineSessions private
Referenced by AddSession_(), FindOfflineSession(), FindOfflineSessionForCharacterGUID(), KickAll(), UpdateSessions(), and ~WorldSessionMgr().
_playerCount
uint32 WorldSessionMgr::_playerCount private
Referenced by DecreasePlayerCount(), GetPlayerCount(), IncreasePlayerCount(), and WorldSessionMgr().
_playerLimit
uint32 WorldSessionMgr::_playerLimit private
Referenced by GetPlayerAmountLimit(), SetPlayerAmountLimit(), and WorldSessionMgr().
_queuedPlayer
Queue WorldSessionMgr::_queuedPlayer private
Referenced by AddQueuedPlayer(), GetActiveSessionCount(), GetQueuedSessionCount(), GetQueuePos(), KickAll(), RemoveQueuedPlayer(), and UpdateMaxSessionCounters().
_sessions
SessionMap WorldSessionMgr::_sessions private
Referenced by AddSession_(), FindSession(), GetActiveAndQueuedSessionCount(), GetActiveSessionCount(), GetAllSessions(), KickAll(), KickAllLess(), KickSession(), SendGlobalGMMessage(), SendGlobalMessage(), SendZoneMessage(), UpdateMaxSessionCounters(), UpdateSessions(), and ~WorldSessionMgr().
The documentation for this class was generated from the following files:
azerothcore-wotlk/src/server/game/Server/WorldSessionMgr.h
azerothcore-wotlk/src/server/game/Server/WorldSessionMgr.cpp