AzerothCore Doxygen
SpellProcSpellTypeMaskTest.cpp File Reference
#include "AuraScriptTestFramework.h"
#include "SpellMgr.h"
#include "gtest/gtest.h"
Classes
class SpellProcSpellTypeMaskTest
Tests for SpellTypeMask calculation based on proc phase.
Functions
TEST_F (SpellProcSpellTypeMaskTest, CastPhase_UsesMaskAll)
TEST_F (SpellProcSpellTypeMaskTest, FinishPhase_UsesMaskAll_EvenWithNullDamageInfo)
TEST_F (SpellProcSpellTypeMaskTest, HitPhase_WithDamage_UsesDamageType)
TEST_F (SpellProcSpellTypeMaskTest, HitPhase_WithHeal_UsesHealType)
TEST_F (SpellProcSpellTypeMaskTest, HitPhase_NoDamageNoHeal_UsesNoDmgHeal)
TEST_F (SpellProcSpellTypeMaskTest, KillingMachine_FinishPhase_MatchesDamageTypeMask)
Regression test for Killing Machine (51124) proc consumption.
TEST_F (SpellProcSpellTypeMaskTest, KillingMachine_FullIntegration_ProcTriggers)
Verify FINISH phase works with actual CanSpellTriggerProcOnEvent.
TEST_F (SpellProcSpellTypeMaskTest, KillingMachine_BugScenario_NoDmgHealFails)
Verify the bug scenario - FINISH phase with NO_DMG_HEAL fails.
Function Documentation
TEST_F() [1/8]
TEST_F (SpellProcSpellTypeMaskTest , CastPhase_UsesMaskAll)
{
    // CAST phase should use MASK_ALL regardless of damage/heal info
    uint32 result = CalculateSpellTypeMask(PROC_SPELL_PHASE_CAST, nullptr, nullptr, true);
    EXPECT_EQ(result, PROC_SPELL_TYPE_MASK_ALL);
}
References PROC_SPELL_PHASE_CAST, and PROC_SPELL_TYPE_MASK_ALL.
TEST_F() [2/8]
TEST_F (SpellProcSpellTypeMaskTest , FinishPhase_UsesMaskAll_EvenWithNullDamageInfo)
{
    // FINISH phase should use MASK_ALL even when damageInfo is null
    // This is the key regression test - previously returned NO_DMG_HEAL
    uint32 result = CalculateSpellTypeMask(PROC_SPELL_PHASE_FINISH, nullptr, nullptr, true);
    EXPECT_EQ(result, PROC_SPELL_TYPE_MASK_ALL);
    // Verify it includes DAMAGE type (required for procs like Killing Machine)
    EXPECT_TRUE(result & PROC_SPELL_TYPE_DAMAGE);
}
References PROC_SPELL_PHASE_FINISH, PROC_SPELL_TYPE_DAMAGE, and PROC_SPELL_TYPE_MASK_ALL.
TEST_F() [3/8]
TEST_F (SpellProcSpellTypeMaskTest , HitPhase_NoDamageNoHeal_UsesNoDmgHeal)
{
    // HIT phase with no damage/heal info should use NO_DMG_HEAL
    uint32 result = CalculateSpellTypeMask(PROC_SPELL_PHASE_HIT, nullptr, nullptr, true);
    EXPECT_EQ(result, PROC_SPELL_TYPE_NO_DMG_HEAL);
}
References PROC_SPELL_PHASE_HIT, and PROC_SPELL_TYPE_NO_DMG_HEAL.
TEST_F() [4/8]
TEST_F (SpellProcSpellTypeMaskTest , HitPhase_WithDamage_UsesDamageType)
{
    auto* spellInfo = CreateSpellInfo(12345, 15, 0);
    DamageInfo damageInfo(nullptr, nullptr, 100, spellInfo, SPELL_SCHOOL_MASK_FROST, SPELL_DIRECT_DAMAGE);
    uint32 result = CalculateSpellTypeMask(PROC_SPELL_PHASE_HIT, &damageInfo, nullptr, true);
    EXPECT_EQ(result, PROC_SPELL_TYPE_DAMAGE);
}
References PROC_SPELL_PHASE_HIT, PROC_SPELL_TYPE_DAMAGE, SPELL_DIRECT_DAMAGE, and SPELL_SCHOOL_MASK_FROST.
TEST_F() [5/8]
TEST_F (SpellProcSpellTypeMaskTest , HitPhase_WithHeal_UsesHealType)
{
    auto* spellInfo = CreateSpellInfo(12345, 15, 0);
    HealInfo healInfo(nullptr, nullptr, 100, spellInfo, SPELL_SCHOOL_MASK_HOLY);
    uint32 result = CalculateSpellTypeMask(PROC_SPELL_PHASE_HIT, nullptr, &healInfo, true);
    EXPECT_EQ(result, PROC_SPELL_TYPE_HEAL);
}
References PROC_SPELL_PHASE_HIT, PROC_SPELL_TYPE_HEAL, and SPELL_SCHOOL_MASK_HOLY.
TEST_F() [6/8]
TEST_F (SpellProcSpellTypeMaskTest , KillingMachine_BugScenario_NoDmgHealFails)
Verify the bug scenario - FINISH phase with NO_DMG_HEAL fails.
This test documents the bug behavior: if FINISH phase incorrectly uses NO_DMG_HEAL spellTypeMask, Killing Machine style procs fail.
{
    auto procEntry = SpellProcEntryBuilder()
        .WithSpellFamilyName(15)
        .WithSpellFamilyMask(flag96(2, 0, 0))
        .WithProcFlags(PROC_FLAG_DONE_SPELL_MAGIC_DMG_CLASS_NEG)
        .WithSpellTypeMask(PROC_SPELL_TYPE_DAMAGE) // Requires DAMAGE
        .WithSpellPhaseMask(PROC_SPELL_PHASE_FINISH)
        .Build();
    auto* icyTouchSpell = CreateSpellInfo(49909, 15, 2);
    DamageInfo damageInfo(nullptr, nullptr, 100, icyTouchSpell, SPELL_SCHOOL_MASK_FROST, SPELL_DIRECT_DAMAGE);
    // Simulate the bug: FINISH phase with NO_DMG_HEAL (the old broken behavior)
    auto eventInfo = ProcEventInfoBuilder()
        .WithTypeMask(PROC_FLAG_DONE_SPELL_MAGIC_DMG_CLASS_NEG)
        .WithHitMask(PROC_HIT_NORMAL)
        .WithSpellTypeMask(PROC_SPELL_TYPE_NO_DMG_HEAL) // Bug: wrong mask
        .WithSpellPhaseMask(PROC_SPELL_PHASE_FINISH)
        .WithDamageInfo(&damageInfo)
        .Build();
    // This should fail - documenting the bug behavior
    EXPECT_FALSE(sSpellMgr->CanSpellTriggerProcOnEvent(procEntry, eventInfo))
        << "With NO_DMG_HEAL spellTypeMask, DAMAGE-requiring procs should NOT trigger (this was the bug)";
}
References ProcEventInfoBuilder::Build(), SpellProcEntryBuilder::Build(), PROC_FLAG_DONE_SPELL_MAGIC_DMG_CLASS_NEG, PROC_HIT_NORMAL, PROC_SPELL_PHASE_FINISH, PROC_SPELL_TYPE_DAMAGE, PROC_SPELL_TYPE_NO_DMG_HEAL, SPELL_DIRECT_DAMAGE, SPELL_SCHOOL_MASK_FROST, sSpellMgr, ProcEventInfoBuilder::WithDamageInfo(), ProcEventInfoBuilder::WithHitMask(), SpellProcEntryBuilder::WithProcFlags(), SpellProcEntryBuilder::WithSpellFamilyMask(), SpellProcEntryBuilder::WithSpellFamilyName(), ProcEventInfoBuilder::WithSpellPhaseMask(), SpellProcEntryBuilder::WithSpellPhaseMask(), ProcEventInfoBuilder::WithSpellTypeMask(), SpellProcEntryBuilder::WithSpellTypeMask(), and ProcEventInfoBuilder::WithTypeMask().
TEST_F() [7/8]
TEST_F (SpellProcSpellTypeMaskTest , KillingMachine_FinishPhase_MatchesDamageTypeMask)
Regression test for Killing Machine (51124) proc consumption.
Killing Machine has:
SpellTypeMask = 1 (PROC_SPELL_TYPE_DAMAGE)
SpellPhaseMask = 4 (PROC_SPELL_PHASE_FINISH)
When Icy Touch is cast, the FINISH phase event must have a spellTypeMask that includes DAMAGE for the proc to fire and consume the buff.
The bug was: FINISH phase calculated spellTypeMask as NO_DMG_HEAL (4) because damageInfo was null, causing the proc check to fail.
{
    // Killing Machine spell_proc entry
    auto procEntry = SpellProcEntryBuilder()
        .WithSpellFamilyName(15) // SPELLFAMILY_DEATHKNIGHT
        .WithSpellFamilyMask(flag96(2, 6, 0)) // Icy Touch, Frost Strike, Howling Blast
        .WithProcFlags(PROC_FLAG_DONE_SPELL_MELEE_DMG_CLASS | PROC_FLAG_DONE_SPELL_MAGIC_DMG_CLASS_NEG)
        .WithSpellTypeMask(PROC_SPELL_TYPE_DAMAGE)
        .WithSpellPhaseMask(PROC_SPELL_PHASE_FINISH)
        .WithAttributesMask(PROC_ATTR_REQ_SPELLMOD)
        .WithCharges(1)
        .Build();
    // Calculate what spellTypeMask FINISH phase would produce
    // (simulating Spell.cpp calling ProcSkillsAndAuras with nullptr damageInfo)
    uint32 finishPhaseSpellTypeMask = CalculateSpellTypeMask(PROC_SPELL_PHASE_FINISH, nullptr, nullptr, true);
    // Verify the calculated mask includes DAMAGE type
    EXPECT_TRUE(finishPhaseSpellTypeMask & PROC_SPELL_TYPE_DAMAGE)
        << "FINISH phase spellTypeMask must include PROC_SPELL_TYPE_DAMAGE for Killing Machine to work";
    // Verify that the proc entry's SpellTypeMask requirement is satisfied
    EXPECT_TRUE(finishPhaseSpellTypeMask & procEntry.SpellTypeMask)
        << "FINISH phase spellTypeMask (" << finishPhaseSpellTypeMask
        << ") must match Killing Machine's SpellTypeMask requirement (" << procEntry.SpellTypeMask << ")";
}
References SpellProcEntryBuilder::Build(), PROC_ATTR_REQ_SPELLMOD, PROC_FLAG_DONE_SPELL_MAGIC_DMG_CLASS_NEG, PROC_FLAG_DONE_SPELL_MELEE_DMG_CLASS, PROC_SPELL_PHASE_FINISH, PROC_SPELL_TYPE_DAMAGE, SpellProcEntryBuilder::WithAttributesMask(), SpellProcEntryBuilder::WithCharges(), SpellProcEntryBuilder::WithProcFlags(), SpellProcEntryBuilder::WithSpellFamilyMask(), SpellProcEntryBuilder::WithSpellFamilyName(), SpellProcEntryBuilder::WithSpellPhaseMask(), and SpellProcEntryBuilder::WithSpellTypeMask().
TEST_F() [8/8]
TEST_F (SpellProcSpellTypeMaskTest , KillingMachine_FullIntegration_ProcTriggers)
Verify FINISH phase works with actual CanSpellTriggerProcOnEvent.
This test verifies the full integration: when we pass the correctly calculated spellTypeMask to CanSpellTriggerProcOnEvent, Killing Machine style procs should work.
{
    // Killing Machine spell_proc entry
    auto procEntry = SpellProcEntryBuilder()
        .WithSpellFamilyName(15) // SPELLFAMILY_DEATHKNIGHT
        .WithSpellFamilyMask(flag96(2, 0, 0)) // Icy Touch
        .WithProcFlags(PROC_FLAG_DONE_SPELL_MAGIC_DMG_CLASS_NEG)
        .WithSpellTypeMask(PROC_SPELL_TYPE_DAMAGE)
        .WithSpellPhaseMask(PROC_SPELL_PHASE_FINISH)
        .Build();
    // Create Icy Touch spell info (SpellFamilyFlags = [2, 0, 0])
    auto* icyTouchSpell = CreateSpellInfo(49909, 15, 2); // DK family, mask0=2
    DamageInfo damageInfo(nullptr, nullptr, 100, icyTouchSpell, SPELL_SCHOOL_MASK_FROST, SPELL_DIRECT_DAMAGE);
    // Create event with FINISH phase and MASK_ALL (as the fix provides)
    auto eventInfo = ProcEventInfoBuilder()
        .WithTypeMask(PROC_FLAG_DONE_SPELL_MAGIC_DMG_CLASS_NEG)
        .WithHitMask(PROC_HIT_NORMAL)
        .WithSpellTypeMask(PROC_SPELL_TYPE_MASK_ALL) // Fixed behavior
        .WithSpellPhaseMask(PROC_SPELL_PHASE_FINISH)
        .WithDamageInfo(&damageInfo)
        .Build();
    EXPECT_TRUE(sSpellMgr->CanSpellTriggerProcOnEvent(procEntry, eventInfo))
        << "Killing Machine style proc should trigger on FINISH phase with MASK_ALL spellTypeMask";
}
References ProcEventInfoBuilder::Build(), SpellProcEntryBuilder::Build(), PROC_FLAG_DONE_SPELL_MAGIC_DMG_CLASS_NEG, PROC_HIT_NORMAL, PROC_SPELL_PHASE_FINISH, PROC_SPELL_TYPE_DAMAGE, PROC_SPELL_TYPE_MASK_ALL, SPELL_DIRECT_DAMAGE, SPELL_SCHOOL_MASK_FROST, sSpellMgr, ProcEventInfoBuilder::WithDamageInfo(), ProcEventInfoBuilder::WithHitMask(), SpellProcEntryBuilder::WithProcFlags(), SpellProcEntryBuilder::WithSpellFamilyMask(), SpellProcEntryBuilder::WithSpellFamilyName(), ProcEventInfoBuilder::WithSpellPhaseMask(), SpellProcEntryBuilder::WithSpellPhaseMask(), ProcEventInfoBuilder::WithSpellTypeMask(), SpellProcEntryBuilder::WithSpellTypeMask(), and ProcEventInfoBuilder::WithTypeMask().