AzerothCore Doxygen
TestSpellEntryHelper Class Reference
Helper class to create SpellEntry test instances.
#include "SpellInfoTestHelper.h"
Public Member Functions
TestSpellEntryHelper ()
TestSpellEntryHelper & WithId (uint32 id)
TestSpellEntryHelper & WithSpellFamilyName (uint32 familyName)
TestSpellEntryHelper & WithSpellFamilyFlags (uint32 flag0, uint32 flag1=0, uint32 flag2=0)
TestSpellEntryHelper & WithSchoolMask (uint32 schoolMask)
TestSpellEntryHelper & WithProcFlags (uint32 procFlags)
TestSpellEntryHelper & WithProcChance (uint32 procChance)
TestSpellEntryHelper & WithProcCharges (uint32 procCharges)
TestSpellEntryHelper & WithDmgClass (uint32 dmgClass)
TestSpellEntryHelper & WithAttributesEx3 (uint32 attr)
TestSpellEntryHelper & WithEffect (uint8 effIndex, uint32 effect, uint32 auraType=0)
TestSpellEntryHelper & WithEffectTriggerSpell (uint8 effIndex, uint32 triggerSpell)
TestSpellEntryHelper & WithEffectBasePoints (uint8 effIndex, int32 basePoints)
TestSpellEntryHelper & WithEffectDieSides (uint8 effIndex, int32 dieSides)
TestSpellEntryHelper & WithAttributes (uint32 attr)
SpellEntry const * Get () const
Private Attributes
SpellEntry _entry
Detailed Description
Helper class to create SpellEntry test instances.
This creates a SpellEntry with sensible defaults for unit testing.
Constructor & Destructor Documentation
TestSpellEntryHelper()
TestSpellEntryHelper::TestSpellEntryHelper () inline
    {
        // Zero initialize all fields
        std::memset(&_entry, 0, sizeof(_entry));
        // Set safe defaults
        _entry.EquippedItemClass = -1;
        _entry.SchoolMask = SPELL_SCHOOL_MASK_NORMAL;
        // Initialize empty strings
        for (auto& name : _entry.SpellName)
            name = "";
        for (auto& rank : _entry.Rank)
            rank = "";
    }
References _entry, SpellEntry::EquippedItemClass, SpellEntry::Rank, SpellEntry::SchoolMask, SPELL_SCHOOL_MASK_NORMAL, and SpellEntry::SpellName.
Member Function Documentation
Get()
SpellEntry const * TestSpellEntryHelper::Get () const inline
    {
        return &_entry;
    }
References _entry.
Referenced by SpellInfoBuilder::Build(), and SpellInfoBuilder::BuildUnique().
WithAttributes()
TestSpellEntryHelper & TestSpellEntryHelper::WithAttributes (uint32 attr) inline
    {
        _entry.Attributes = attr;
        return *this;
    }
References _entry, and SpellEntry::Attributes.
Referenced by SpellInfoBuilder::WithAttributes().
WithAttributesEx3()
TestSpellEntryHelper & TestSpellEntryHelper::WithAttributesEx3 (uint32 attr) inline
    {
        _entry.AttributesEx3 = attr;
        return *this;
    }
References _entry, and SpellEntry::AttributesEx3.
Referenced by SpellInfoBuilder::WithAttributesEx3().
WithDmgClass()
TestSpellEntryHelper & TestSpellEntryHelper::WithDmgClass (uint32 dmgClass) inline
    {
        _entry.DmgClass = dmgClass;
        return *this;
    }
References _entry, and SpellEntry::DmgClass.
Referenced by SpellInfoBuilder::WithDmgClass().
WithEffect()
TestSpellEntryHelper & TestSpellEntryHelper::WithEffect (uint8 effIndex, uint32 effect, uint32 auraType = 0) inline
    {
        if (effIndex < MAX_SPELL_EFFECTS)
        {
            _entry.Effect[effIndex] = effect;
            _entry.EffectApplyAuraName[effIndex] = auraType;
        }
        return *this;
    }
References _entry, SpellEntry::Effect, SpellEntry::EffectApplyAuraName, and MAX_SPELL_EFFECTS.
Referenced by SpellInfoBuilder::WithEffect().
WithEffectBasePoints()
TestSpellEntryHelper & TestSpellEntryHelper::WithEffectBasePoints (uint8 effIndex, int32 basePoints) inline
    {
        if (effIndex < MAX_SPELL_EFFECTS)
            _entry.EffectBasePoints[effIndex] = basePoints;
        return *this;
    }
References _entry, SpellEntry::EffectBasePoints, and MAX_SPELL_EFFECTS.
Referenced by SpellInfoBuilder::WithEffectBasePoints().
WithEffectDieSides()
TestSpellEntryHelper & TestSpellEntryHelper::WithEffectDieSides (uint8 effIndex, int32 dieSides) inline
    {
        if (effIndex < MAX_SPELL_EFFECTS)
            _entry.EffectDieSides[effIndex] = dieSides;
        return *this;
    }
References _entry, SpellEntry::EffectDieSides, and MAX_SPELL_EFFECTS.
Referenced by SpellInfoBuilder::WithEffectDieSides().
WithEffectTriggerSpell()
TestSpellEntryHelper & TestSpellEntryHelper::WithEffectTriggerSpell (uint8 effIndex, uint32 triggerSpell) inline
    {
        if (effIndex < MAX_SPELL_EFFECTS)
        {
            _entry.EffectTriggerSpell[effIndex] = triggerSpell;
        }
        return *this;
    }
References _entry, SpellEntry::EffectTriggerSpell, and MAX_SPELL_EFFECTS.
Referenced by SpellInfoBuilder::WithEffectTriggerSpell().
WithId()
TestSpellEntryHelper & TestSpellEntryHelper::WithId (uint32 id) inline
    {
        _entry.Id = id;
        return *this;
    }
References _entry, and SpellEntry::Id.
Referenced by SpellInfoBuilder::WithId().
WithProcChance()
TestSpellEntryHelper & TestSpellEntryHelper::WithProcChance (uint32 procChance) inline
    {
        _entry.ProcChance = procChance;
        return *this;
    }
References _entry, and SpellEntry::ProcChance.
Referenced by SpellInfoBuilder::WithProcChance().
WithProcCharges()
TestSpellEntryHelper & TestSpellEntryHelper::WithProcCharges (uint32 procCharges) inline
    {
        _entry.ProcCharges = procCharges;
        return *this;
    }
References _entry, and SpellEntry::ProcCharges.
Referenced by SpellInfoBuilder::WithProcCharges().
WithProcFlags()
TestSpellEntryHelper & TestSpellEntryHelper::WithProcFlags (uint32 procFlags) inline
    {
        _entry.ProcFlags = procFlags;
        return *this;
    }
References _entry, and SpellEntry::ProcFlags.
Referenced by SpellInfoBuilder::WithProcFlags().
WithSchoolMask()
TestSpellEntryHelper & TestSpellEntryHelper::WithSchoolMask (uint32 schoolMask) inline
    {
        _entry.SchoolMask = schoolMask;
        return *this;
    }
References _entry, and SpellEntry::SchoolMask.
Referenced by SpellInfoBuilder::WithSchoolMask().
WithSpellFamilyFlags()
TestSpellEntryHelper & TestSpellEntryHelper::WithSpellFamilyFlags (uint32 flag0, uint32 flag1 = 0, uint32 flag2 = 0) inline
    {
        _entry.SpellFamilyFlags[0] = flag0;
        _entry.SpellFamilyFlags[1] = flag1;
        _entry.SpellFamilyFlags[2] = flag2;
        return *this;
    }
References _entry, and SpellEntry::SpellFamilyFlags.
Referenced by SpellInfoBuilder::WithSpellFamilyFlags().
WithSpellFamilyName()
TestSpellEntryHelper & TestSpellEntryHelper::WithSpellFamilyName (uint32 familyName) inline
    {
        _entry.SpellFamilyName = familyName;
        return *this;
    }
References _entry, and SpellEntry::SpellFamilyName.
Referenced by SpellInfoBuilder::WithSpellFamilyName().
Member Data Documentation
_entry
SpellEntry TestSpellEntryHelper::_entry private
Referenced by Get(), TestSpellEntryHelper(), WithAttributes(), WithAttributesEx3(), WithDmgClass(), WithEffect(), WithEffectBasePoints(), WithEffectDieSides(), WithEffectTriggerSpell(), WithId(), WithProcChance(), WithProcCharges(), WithProcFlags(), WithSchoolMask(), WithSpellFamilyFlags(), and WithSpellFamilyName().
The documentation for this class was generated from the following file:
azerothcore-wotlk/src/test/mocks/SpellInfoTestHelper.h