AzerothCore Doxygen
instance_naxxramas Class Reference
Public Member Functions
instance_naxxramas (Map *map)
void CreatureTalk (uint32 dataCreature, uint8 dialog)
void SetGoState (uint32 dataGameObject, GOState state)
void ActivateWingPortal (GameObject *go, EncounterState state)
void ActivateWingPortal (uint32 wingPortal)
void HeiganEruptSections (uint32 section)
void OnPlayerEnter (Player *player) override
void OnCreatureCreate (Creature *creature) override
void OnGameObjectCreate (GameObject *go) override
void OnGameObjectRemove (GameObject *go) override
bool CheckAchievementCriteriaMeet (uint32 criteria_id, Player const *, Unit const *, uint32) override
void SetData (uint32 id, uint32 data) override
bool SetBossState (uint32 bossId, EncounterState state) override
void Update (uint32 diff) override
Public Member Functions inherited from InstanceScript
InstanceScript (Map *map)
~InstanceScript () override
virtual void Initialize ()
virtual void Load (char const *data)
virtual void CreatureLooted (Creature *, LootType)
virtual std::string GetSaveData ()
void SaveToDB ()
virtual bool IsEncounterInProgress () const
void OnCreatureCreate (Creature *creature) override
void OnCreatureRemove (Creature *creature) override
void OnGameObjectCreate (GameObject *go) override
void OnGameObjectRemove (GameObject *go) override
ObjectGuid GetObjectGuid (uint32 type) const
ObjectGuid GetGuidData (uint32 type) const override
Creature * GetCreature (uint32 type)
GameObject * GetGameObject (uint32 type)
virtual void OnPlayerLeave (Player *)
virtual void OnPlayerAreaUpdate (Player *, uint32, uint32)
virtual void OnPlayerInWaterStateUpdate (Player *, bool)
void HandleGameObject (ObjectGuid guid, bool open, GameObject *go=nullptr)
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
void DoRespawnGameObject (uint32 type)
void DoRespawnCreature (ObjectGuid guid, bool force=false)
void DoRespawnCreature (uint32 type, bool force=false)
void DoUpdateWorldState (uint32 worldstateId, uint32 worldstateValue)
void DoSendNotifyToInstance (char const *format,...)
void DoUpdateAchievementCriteria (AchievementCriteriaTypes type, uint32 miscValue1=0, uint32 miscValue2=0, Unit *unit=nullptr)
void DoStartTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoStopTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoRemoveAurasDueToSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayer (Player *player, uint32 spell, bool includePets, bool includeControlled)
bool ServerAllowsTwoSideGroups ()
EncounterState GetBossState (uint32 id) const
CreatureBoundary const * GetBossBoundary (uint32 id) const
BossInfo const * GetBossInfo (uint32 id) const
uint32 GetPersistentData (uint32 index) const
void StorePersistentData (uint32 index, uint32 data)
virtual bool CheckRequiredBosses (uint32, Player const *=nullptr) const
void SetCompletedEncountersMask (uint32 newMask, bool save)
uint32 GetCompletedEncounterMask () const
void SendEncounterUnit (uint32 type, Unit *unit=nullptr, uint8 param1=0, uint8 param2=0)
virtual void FillInitialWorldStates (WorldPackets::WorldState::InitWorldStates &)
uint32 GetEncounterCount () const
void MarkAreaTriggerDone (uint32 id)
void ResetAreaTriggerDone (uint32 id)
bool IsAreaTriggerDone (uint32 id) const
virtual void DoAction (int32)
void DoForAllMinions (uint32 id, std::function< void(Creature *)> exec)
void StoreGameObjectState (ObjectGuid::LowType spawnId, uint8 state)
uint8 GetStoredGameObjectState (ObjectGuid::LowType spawnId) const
void LoadInstanceSavedGameobjectStateData ()
bool IsBossDone (uint32 bossId) const
bool AllBossesDone () const
bool AllBossesDone (std::initializer_list< uint32 > bossIds) const
TeamId GetTeamIdInInstance () const
void SetTeamIdInInstance (TeamId teamId)
bool IsTwoFactionInstance () const
Public Member Functions inherited from ZoneScript
ZoneScript ()
virtual ~ZoneScript ()
virtual uint32 GetCreatureEntry (ObjectGuid::LowType, CreatureData const *data)
virtual uint32 GetGameObjectEntry (ObjectGuid::LowType, uint32 entry)
virtual void OnUnitDeath (Unit *)
virtual void OnCreatureEvade (Creature *)
virtual void SetGuidData (uint32, ObjectGuid)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
virtual uint32 GetData (uint32) const
virtual void ProcessEvent (WorldObject *, uint32)
Static Public Member Functions
static uint8 GetEruptionSection (float x, float y)
Static Public Member Functions inherited from InstanceScript
static std::string GetBossStateName (uint8 state)
Private Attributes
EventMap _events
uint8 _currentWingTaunt
uint8 _horsemanLoaded
std::set< GameObject * > _heiganEruption [HeiganEruptSectionCount]
GuidList _patchwerkRoomTrash
uint8 _abominationsKilled
bool _faerlinaAchievement
bool _thaddiusAchievement
bool _loathebAchievement
bool _sapphironAchievement
bool _heiganAchievement
bool _horsemanAchievement
Additional Inherited Members
Public Attributes inherited from InstanceScript
Map * instance
TaskScheduler scheduler
Protected Member Functions inherited from InstanceScript
void SetHeaders (std::string const &dataHeaders)
void SetBossNumber (uint32 number)
void SetPersistentDataCount (uint32 number)
void LoadBossBoundaries (BossBoundaryData const &data)
void LoadDoorData (DoorData const *data)
void LoadMinionData (MinionData const *data)
void LoadObjectData (ObjectData const *creatureData, ObjectData const *gameObjectData)
void LoadSummonData (ObjectData const *data)
void SetSummoner (Creature *creature)
void AddObject (Creature *obj, bool add=true)
void RemoveObject (Creature *obj)
void AddObject (GameObject *obj, bool add=true)
void RemoveObject (GameObject *obj)
void AddObject (WorldObject *obj, uint32 type, bool add=true)
void RemoveObject (WorldObject *obj, uint32 type)
void AddDoor (GameObject *door, bool add=true)
void RemoveDoor (GameObject *door)
void AddMinion (Creature *minion, bool add=true)
void RemoveMinion (Creature *minion)
void UpdateDoorState (GameObject *door)
void UpdateMinionState (Creature *minion, EncounterState state)
bool ReadSaveDataHeaders (std::istringstream &data)
void ReadSaveDataBossStates (std::istringstream &data)
void ReadSavePersistentData (std::istringstream &data)
virtual void ReadSaveDataMore (std::istringstream &)
void WriteSaveDataHeaders (std::ostringstream &data)
void WriteSaveDataBossStates (std::ostringstream &data)
void WritePersistentData (std::ostringstream &data)
virtual void WriteSaveDataMore (std::ostringstream &)
Detailed Description
Constructor & Destructor Documentation
instance_naxxramas()
instance_naxxramas::instance_naxxramas (Map * map) inline
                                 : InstanceScript(map)
    {
        SetHeaders(DataHeader);
        SetBossNumber(MAX_ENCOUNTERS);
        SetPersistentDataCount(PERSISTENT_DATA_COUNT);
        LoadDoorData(doorData);
        LoadObjectData(creatureData, gameObjectData);
        // GameObjects
        for (auto& i : _heiganEruption)
            i.clear();
        // NPCs
        _patchwerkRoomTrash.clear();
        // Controls
        _events.Reset();
        _currentWingTaunt = SAY_FIRST_WING_TAUNT;
        _horsemanLoaded = 0;
        // Achievements
        _abominationsKilled = 0;
        _faerlinaAchievement = true;
        _thaddiusAchievement = true;
        _loathebAchievement = true;
        _heiganAchievement = true;
        _sapphironAchievement = true;
        _horsemanAchievement = true;
    }
References _abominationsKilled, _currentWingTaunt, _events, _faerlinaAchievement, _heiganAchievement, _heiganEruption, _horsemanAchievement, _horsemanLoaded, _loathebAchievement, _patchwerkRoomTrash, _sapphironAchievement, _thaddiusAchievement, creatureData, DataHeader, doorData, gameObjectData, InstanceScript::LoadDoorData(), InstanceScript::LoadObjectData(), MAX_ENCOUNTERS, PERSISTENT_DATA_COUNT, EventMap::Reset(), SAY_FIRST_WING_TAUNT, InstanceScript::SetBossNumber(), InstanceScript::SetHeaders(), and InstanceScript::SetPersistentDataCount().
Member Function Documentation
ActivateWingPortal() [1/2]
void instance_naxxramas::ActivateWingPortal (GameObject * go, EncounterState state) inline
    {
        if (!go || state != DONE)
            return;
        go->SetGoState(GO_STATE_ACTIVE);
        go->RemoveGameObjectFlag(GO_FLAG_NOT_SELECTABLE);
    }
References DONE, GO_FLAG_NOT_SELECTABLE, GO_STATE_ACTIVE, GameObject::RemoveGameObjectFlag(), and GameObject::SetGoState().
Referenced by ActivateWingPortal(), OnGameObjectCreate(), and SetBossState().
ActivateWingPortal() [2/2]
void instance_naxxramas::ActivateWingPortal (uint32 wingPortal) inline
    {
        ActivateWingPortal(GetGameObject(wingPortal), DONE);
        _events.RescheduleEvent(EVENT_KELTHUZAD_WING_TAUNT, 6s);
    }
References _events, ActivateWingPortal(), DONE, EVENT_KELTHUZAD_WING_TAUNT, InstanceScript::GetGameObject(), and EventMap::RescheduleEvent().
CheckAchievementCriteriaMeet()
bool instance_naxxramas::CheckAchievementCriteriaMeet (uint32 criteria_id, Player const * , Unit const * , uint32) inline override virtual
Reimplemented from InstanceScript.
    {
        switch (criteria_id)
        {
            case ACHIEV_CRITERIA_AND_THEY_WOULD_ALL_GO_DOWN_TOGETHER_10_PLAYER:
            case ACHIEV_CRITERIA_AND_THEY_WOULD_ALL_GO_DOWN_TOGETHER_25_PLAYER:
                return _horsemanAchievement;
            case ACHIEV_CRITERIA_JUST_CANT_GET_ENOUGH_10_PLAYER:
            case ACHIEV_CRITERIA_JUST_CANT_GET_ENOUGH_25_PLAYER:
                return _abominationsKilled >= AbominationKillCountReq;
            case ACHIEV_CRITERIA_MOMMA_SAID_KNOCK_YOU_OUT_10_PLAYER:
            case ACHIEV_CRITERIA_MOMMA_SAID_KNOCK_YOU_OUT_25_PLAYER:
                return _faerlinaAchievement;
            case ACHIEV_CRITERIA_SHOKING_10_PLAYER:
            case ACHIEV_CRITERIA_SHOKING_25_PLAYER:
                return _thaddiusAchievement;
            case ACHIEV_CRITERIA_SPORE_LOSER_10_PLAYER:
            case ACHIEV_CRITERIA_SPORE_LOSER_25_PLAYER:
                return _loathebAchievement;
            case ACHIEV_CRITERIA_THE_SAFETY_DANCE_10_PLAYER:
            case ACHIEV_CRITERIA_THE_SAFETY_DANCE_25_PLAYER:
                return _heiganAchievement;
            case ACHIEV_CRITERIA_SUBTRACTION_10_PLAYER:
            case ACHIEV_CRITERIA_THE_DEDICATED_FEW_KELTHUZAD_10_PLAYER:
            case ACHIEV_CRITERIA_THE_DEDICATED_FEW_GOTHIK_10_PLAYER:
            case ACHIEV_CRITERIA_THE_DEDICATED_FEW_ANUB_10_PLAYER:
            case ACHIEV_CRITERIA_THE_DEDICATED_FEW_GROBBULUS_10_PLAYER:
            case ACHIEV_CRITERIA_THE_DEDICATED_FEW_HEIGAN_10_PLAYER:
            case ACHIEV_CRITERIA_THE_DEDICATED_FEW_FAERLINA_10_PLAYER:
            case ACHIEV_CRITERIA_THE_DEDICATED_FEW_MAEXXNA_10_PLAYER:
            case ACHIEV_CRITERIA_THE_DEDICATED_FEW_SAPPHIRON_10_PLAYER:
            case ACHIEV_CRITERIA_THE_DEDICATED_FEW_LOATHEB_10_PLAYER:
            case ACHIEV_CRITERIA_THE_DEDICATED_FEW_GLUTH_10_PLAYER:
            case ACHIEV_CRITERIA_THE_DEDICATED_FEW_THADDIUS_10_PLAYER:
            case ACHIEV_CRITERIA_THE_DEDICATED_FEW_PATCHWERK_10_PLAYER:
            case ACHIEV_CRITERIA_THE_DEDICATED_FEW_RAZUVIOUS_10_PLAYER:
            case ACHIEV_CRITERIA_THE_DEDICATED_FEW_NOTH_10_PLAYER:
                return instance->GetPlayersCountExceptGMs() < TheDedicatedFew10PlayerReq;
            case ACHIEV_CRITERIA_SUBTRACTION_25_PLAYER:
            case ACHIEV_CRITERIA_THE_DEDICATED_FEW_ANUB_25_PLAYER:
            case ACHIEV_CRITERIA_THE_DEDICATED_FEW_FAERLINA_25_PLAYER:
            case ACHIEV_CRITERIA_THE_DEDICATED_FEW_MAEXXNA_25_PLAYER:
            case ACHIEV_CRITERIA_THE_DEDICATED_FEW_PATCHWERK_25_PLAYER:
            case ACHIEV_CRITERIA_THE_DEDICATED_FEW_GROBBULUS_25_PLAYER:
            case ACHIEV_CRITERIA_THE_DEDICATED_FEW_GLUTH_25_PLAYER:
            case ACHIEV_CRITERIA_THE_DEDICATED_FEW_THADDIUS_25_PLAYER:
            case ACHIEV_CRITERIA_THE_DEDICATED_FEW_NOTH_25_PLAYER:
            case ACHIEV_CRITERIA_THE_DEDICATED_FEW_HEIGAN_25_PLAYER:
            case ACHIEV_CRITERIA_THE_DEDICATED_FEW_LOATHEB_25_PLAYER:
            case ACHIEV_CRITERIA_THE_DEDICATED_FEW_RAZUVIOUS_25_PLAYER:
            case ACHIEV_CRITERIA_THE_DEDICATED_FEW_GOTHIK_25_PLAYER:
            case ACHIEV_CRITERIA_THE_DEDICATED_FEW_SAPPHIRON_25_PLAYER:
            case ACHIEV_CRITERIA_THE_DEDICATED_FEW_KELTHUZAD_25_PLAYER:
                return instance->GetPlayersCountExceptGMs() < TheDedicatedFew25PlayerReq;
            case ACHIEV_CRITERIA_THE_HUNDRED_CLUB_10_PLAYER:
            case ACHIEV_CRITERIA_THE_HUNDRED_CLUB_25_PLAYER:
                return _sapphironAchievement;
            case ACHIEV_CRITERIA_THE_UNDYING_KELTHUZAD:
            case ACHIEV_CRITERIA_THE_UNDYING_THE_FOUR_HORSEMEN:
            case ACHIEV_CRITERIA_THE_UNDYING_MAEXXNA:
            case ACHIEV_CRITERIA_THE_UNDYING_LOATHEB:
            case ACHIEV_CRITERIA_THE_UNDYING_THADDIUS:
            case ACHIEV_CRITERIA_THE_IMMORTAL_KELTHUZAD:
            case ACHIEV_CRITERIA_THE_IMMORTAL_THE_FOUR_HORSEMEN:
            case ACHIEV_CRITERIA_THE_IMMORTAL_MAEXXNA:
            case ACHIEV_CRITERIA_THE_IMMORTAL_LOATHEB:
            case ACHIEV_CRITERIA_THE_IMMORTAL_THADDIUS:
                for (int i = 0; i < MAX_ENCOUNTERS; ++i)
                    if (GetBossState(i) != DONE)
                        return false;
                return !GetPersistentData(PERSISTENT_DATA_IMMORTAL_FAIL);
            default:
                return false;
        }
    }
References _abominationsKilled, _faerlinaAchievement, _heiganAchievement, _horsemanAchievement, _loathebAchievement, _sapphironAchievement, _thaddiusAchievement, AbominationKillCountReq, ACHIEV_CRITERIA_AND_THEY_WOULD_ALL_GO_DOWN_TOGETHER_10_PLAYER, ACHIEV_CRITERIA_AND_THEY_WOULD_ALL_GO_DOWN_TOGETHER_25_PLAYER, ACHIEV_CRITERIA_JUST_CANT_GET_ENOUGH_10_PLAYER, ACHIEV_CRITERIA_JUST_CANT_GET_ENOUGH_25_PLAYER, ACHIEV_CRITERIA_MOMMA_SAID_KNOCK_YOU_OUT_10_PLAYER, ACHIEV_CRITERIA_MOMMA_SAID_KNOCK_YOU_OUT_25_PLAYER, ACHIEV_CRITERIA_SHOKING_10_PLAYER, ACHIEV_CRITERIA_SHOKING_25_PLAYER, ACHIEV_CRITERIA_SPORE_LOSER_10_PLAYER, ACHIEV_CRITERIA_SPORE_LOSER_25_PLAYER, ACHIEV_CRITERIA_SUBTRACTION_10_PLAYER, ACHIEV_CRITERIA_SUBTRACTION_25_PLAYER, ACHIEV_CRITERIA_THE_DEDICATED_FEW_ANUB_10_PLAYER, ACHIEV_CRITERIA_THE_DEDICATED_FEW_ANUB_25_PLAYER, ACHIEV_CRITERIA_THE_DEDICATED_FEW_FAERLINA_10_PLAYER, ACHIEV_CRITERIA_THE_DEDICATED_FEW_FAERLINA_25_PLAYER, ACHIEV_CRITERIA_THE_DEDICATED_FEW_GLUTH_10_PLAYER, ACHIEV_CRITERIA_THE_DEDICATED_FEW_GLUTH_25_PLAYER, ACHIEV_CRITERIA_THE_DEDICATED_FEW_GOTHIK_10_PLAYER, ACHIEV_CRITERIA_THE_DEDICATED_FEW_GOTHIK_25_PLAYER, ACHIEV_CRITERIA_THE_DEDICATED_FEW_GROBBULUS_10_PLAYER, ACHIEV_CRITERIA_THE_DEDICATED_FEW_GROBBULUS_25_PLAYER, ACHIEV_CRITERIA_THE_DEDICATED_FEW_HEIGAN_10_PLAYER, ACHIEV_CRITERIA_THE_DEDICATED_FEW_HEIGAN_25_PLAYER, ACHIEV_CRITERIA_THE_DEDICATED_FEW_KELTHUZAD_10_PLAYER, ACHIEV_CRITERIA_THE_DEDICATED_FEW_KELTHUZAD_25_PLAYER, ACHIEV_CRITERIA_THE_DEDICATED_FEW_LOATHEB_10_PLAYER, ACHIEV_CRITERIA_THE_DEDICATED_FEW_LOATHEB_25_PLAYER, ACHIEV_CRITERIA_THE_DEDICATED_FEW_MAEXXNA_10_PLAYER, ACHIEV_CRITERIA_THE_DEDICATED_FEW_MAEXXNA_25_PLAYER, ACHIEV_CRITERIA_THE_DEDICATED_FEW_NOTH_10_PLAYER, ACHIEV_CRITERIA_THE_DEDICATED_FEW_NOTH_25_PLAYER, ACHIEV_CRITERIA_THE_DEDICATED_FEW_PATCHWERK_10_PLAYER, ACHIEV_CRITERIA_THE_DEDICATED_FEW_PATCHWERK_25_PLAYER, ACHIEV_CRITERIA_THE_DEDICATED_FEW_RAZUVIOUS_10_PLAYER, ACHIEV_CRITERIA_THE_DEDICATED_FEW_RAZUVIOUS_25_PLAYER, ACHIEV_CRITERIA_THE_DEDICATED_FEW_SAPPHIRON_10_PLAYER, ACHIEV_CRITERIA_THE_DEDICATED_FEW_SAPPHIRON_25_PLAYER, ACHIEV_CRITERIA_THE_DEDICATED_FEW_THADDIUS_10_PLAYER, ACHIEV_CRITERIA_THE_DEDICATED_FEW_THADDIUS_25_PLAYER, ACHIEV_CRITERIA_THE_HUNDRED_CLUB_10_PLAYER, ACHIEV_CRITERIA_THE_HUNDRED_CLUB_25_PLAYER, ACHIEV_CRITERIA_THE_IMMORTAL_KELTHUZAD, ACHIEV_CRITERIA_THE_IMMORTAL_LOATHEB, ACHIEV_CRITERIA_THE_IMMORTAL_MAEXXNA, ACHIEV_CRITERIA_THE_IMMORTAL_THADDIUS, ACHIEV_CRITERIA_THE_IMMORTAL_THE_FOUR_HORSEMEN, ACHIEV_CRITERIA_THE_SAFETY_DANCE_10_PLAYER, ACHIEV_CRITERIA_THE_SAFETY_DANCE_25_PLAYER, ACHIEV_CRITERIA_THE_UNDYING_KELTHUZAD, ACHIEV_CRITERIA_THE_UNDYING_LOATHEB, ACHIEV_CRITERIA_THE_UNDYING_MAEXXNA, ACHIEV_CRITERIA_THE_UNDYING_THADDIUS, ACHIEV_CRITERIA_THE_UNDYING_THE_FOUR_HORSEMEN, DONE, InstanceScript::GetBossState(), InstanceScript::GetPersistentData(), Map::GetPlayersCountExceptGMs(), InstanceScript::instance, MAX_ENCOUNTERS, PERSISTENT_DATA_IMMORTAL_FAIL, TheDedicatedFew10PlayerReq, and TheDedicatedFew25PlayerReq.
CreatureTalk()
void instance_naxxramas::CreatureTalk (uint32 dataCreature, uint8 dialog) inline
    {
        if (Creature* creature = GetCreature(dataCreature))
            creature->AI()->Talk(dialog);
    }
References InstanceScript::GetCreature().
Referenced by Update().
GetEruptionSection()
static uint8 instance_naxxramas::GetEruptionSection (float x, float y) inline static
    {
        y -= HeiganPos[1];
        if (y < 1.0f)
            return 0;
        x -= HeiganPos[0];
        if (x > -1.0f)
            return 3;
        float slope = y / x;
        for (uint32 i = 0; i < 3; ++i)
            if (slope > HeiganEruptionSlope[i])
                return i;
        return 3;
    }
References HeiganEruptionSlope, and HeiganPos.
Referenced by OnGameObjectCreate(), and OnGameObjectRemove().
HeiganEruptSections()
void instance_naxxramas::HeiganEruptSections (uint32 section) inline
    {
        for (uint8 i = 0; i < HeiganEruptSectionCount; ++i)
        {
            if (i == section)
                continue;
            for (GameObject* go : _heiganEruption[i])
            {
                go->SendCustomAnim(go->GetGoAnimProgress());
                go->CastSpell(nullptr, SPELL_ERUPTION);
            }
        }
    }
References _heiganEruption, HeiganEruptSectionCount, and SPELL_ERUPTION.
Referenced by SetData().
OnCreatureCreate()
void instance_naxxramas::OnCreatureCreate (Creature * creature) inline override virtual
Reimplemented from ZoneScript.
    {
        switch (creature->GetEntry())
        {
            case NPC_LIVING_MONSTROSITY:
            case NPC_MAD_SCIENTIST:
            case NPC_PATCHWORK_GOLEM:
            case NPC_SURGICAL_ASSIST:
                _patchwerkRoomTrash.push_back(creature->GetGUID());
                return;
            case NPC_BILE_RETCHER:
            case NPC_SLUDGE_BELCHER:
                if (creature->GetPositionY() > -3258.0f) // we want only those inside the room, not before
                    _patchwerkRoomTrash.push_back(creature->GetGUID());
                return;
            case NPC_BARON_RIVENDARE:
            case NPC_SIR_ZELIEK:
            case NPC_LADY_BLAUMEUX:
            case NPC_THANE_KORTHAZZ:
                if (++_horsemanLoaded == HorsemanCount)
                    SetBossState(BOSS_HORSEMAN, GetBossState(BOSS_HORSEMAN));
                break;
            default:
                break;
        }
        InstanceScript::OnCreatureCreate(creature);
    }
References _horsemanLoaded, _patchwerkRoomTrash, BOSS_HORSEMAN, InstanceScript::GetBossState(), Object::GetEntry(), Object::GetGUID(), Position::GetPositionY(), HorsemanCount, NPC_BARON_RIVENDARE, NPC_BILE_RETCHER, NPC_LADY_BLAUMEUX, NPC_LIVING_MONSTROSITY, NPC_MAD_SCIENTIST, NPC_PATCHWORK_GOLEM, NPC_SIR_ZELIEK, NPC_SLUDGE_BELCHER, NPC_SURGICAL_ASSIST, NPC_THANE_KORTHAZZ, InstanceScript::OnCreatureCreate(), and SetBossState().
OnGameObjectCreate()
void instance_naxxramas::OnGameObjectCreate (GameObject * go) inline override virtual
Reimplemented from ZoneScript.
    {
        switch (go->GetGOInfo()->displayId)
        {
            case GO_DISPLAY_ID_HEIGAN_ERUPTION1:
            case GO_DISPLAY_ID_HEIGAN_ERUPTION2:
                _heiganEruption[GetEruptionSection(go->GetPositionX(), go->GetPositionY())].insert(go);
                break;
            default:
                break;
        }
        switch (go->GetEntry())
        {
            case GO_SAPPHIRON_GATE:
                if (GetBossState(BOSS_SAPPHIRON) == DONE)
                    go->SetGoState(GO_STATE_ACTIVE);
                break;
            case GO_LOATHEB_PORTAL:
                ActivateWingPortal(go, GetBossState(BOSS_LOATHEB));
                break;
            case GO_THADDIUS_PORTAL:
                ActivateWingPortal(go, GetBossState(BOSS_THADDIUS));
                break;
            case GO_MAEXXNA_PORTAL:
                ActivateWingPortal(go, GetBossState(BOSS_MAEXXNA));
                break;
            case GO_HORSEMAN_PORTAL:
                ActivateWingPortal(go, GetBossState(BOSS_HORSEMAN));
                break;
            default:
                break;
        }
        InstanceScript::OnGameObjectCreate(go);
    }
References _heiganEruption, ActivateWingPortal(), BOSS_HORSEMAN, BOSS_LOATHEB, BOSS_MAEXXNA, BOSS_SAPPHIRON, BOSS_THADDIUS, GameObjectTemplate::displayId, DONE, InstanceScript::GetBossState(), Object::GetEntry(), GetEruptionSection(), GameObject::GetGOInfo(), Position::GetPositionX(), Position::GetPositionY(), GO_DISPLAY_ID_HEIGAN_ERUPTION1, GO_DISPLAY_ID_HEIGAN_ERUPTION2, GO_HORSEMAN_PORTAL, GO_LOATHEB_PORTAL, GO_MAEXXNA_PORTAL, GO_SAPPHIRON_GATE, GO_STATE_ACTIVE, GO_THADDIUS_PORTAL, InstanceScript::OnGameObjectCreate(), and GameObject::SetGoState().
OnGameObjectRemove()
void instance_naxxramas::OnGameObjectRemove (GameObject * go) inline override virtual
Reimplemented from ZoneScript.
    {
        switch (go->GetGOInfo()->displayId)
        {
            case GO_DISPLAY_ID_HEIGAN_ERUPTION1:
            case GO_DISPLAY_ID_HEIGAN_ERUPTION2:
                _heiganEruption[GetEruptionSection(go->GetPositionX(), go->GetPositionY())].erase(go);
                break;
            default:
                break;
        }
        switch (go->GetEntry())
        {
            case GO_SAPPHIRON_BIRTH:
                if (Creature* cr = GetCreature(DATA_SAPPHIRON_BOSS))
                    cr->AI()->DoAction(ACTION_SAPPHIRON_BIRTH);
                break;
            default:
                break;
        }
        InstanceScript::OnGameObjectRemove(go);
    }
References _heiganEruption, ACTION_SAPPHIRON_BIRTH, DATA_SAPPHIRON_BOSS, GameObjectTemplate::displayId, InstanceScript::GetCreature(), Object::GetEntry(), GetEruptionSection(), GameObject::GetGOInfo(), Position::GetPositionX(), Position::GetPositionY(), GO_DISPLAY_ID_HEIGAN_ERUPTION1, GO_DISPLAY_ID_HEIGAN_ERUPTION2, GO_SAPPHIRON_BIRTH, and InstanceScript::OnGameObjectRemove().
OnPlayerEnter()
void instance_naxxramas::OnPlayerEnter (Player * player) inline override virtual
Reimplemented from InstanceScript.
    {
        InstanceScript::OnPlayerEnter(player);
        _events.ScheduleEvent(EVENT_THADDIUS_SCREAMS, 2min, 2min + 30s);
    }
References _events, EVENT_THADDIUS_SCREAMS, InstanceScript::OnPlayerEnter(), and EventMap::ScheduleEvent().
SetBossState()
bool instance_naxxramas::SetBossState (uint32 bossId, EncounterState state) inline override virtual
Reimplemented from InstanceScript.
    {
        switch (bossId)
        {
            case BOSS_PATCHWERK:
            {
                if (state != IN_PROGRESS)
                    break;
                // pull all the trash if not killed
                if (Creature* patchwerk = GetCreature(DATA_PATCHWERK_BOSS))
                {
                    for (auto& itr : _patchwerkRoomTrash)
                    {
                        Creature* trash = ObjectAccessor::GetCreature(*patchwerk, itr);
                        if (trash && trash->IsAlive() && !trash->IsInCombat())
                            trash->AI()->AttackStart(patchwerk->GetVictim());
                    }
                }
                break;
            }
            case BOSS_HEIGAN:
            {
                if (state == NOT_STARTED)
                    _heiganAchievement = true;
                break;
            }
            case BOSS_LOATHEB:
            {
                switch (state)
                {
                    case NOT_STARTED:
                        _loathebAchievement = true;
                        break;
                    case DONE:
                        ActivateWingPortal(DATA_LOATHEB_PORTAL);
                        break;
                    default:
                        break;
                }
                break;
            }
            case BOSS_FAERLINA:
            {
                if (state == NOT_STARTED)
                    _faerlinaAchievement = true;
                break;
            }
            case BOSS_MAEXXNA:
            {
                if (state == DONE)
                    ActivateWingPortal(DATA_MAEXXNA_PORTAL);
                break;
            }
            case BOSS_THADDIUS:
            {
                switch (state)
                {
                    case NOT_STARTED:
                        _thaddiusAchievement = true;
                        break;
                    case DONE:
                        ActivateWingPortal(DATA_THADDIUS_PORTAL);
                        break;
                    default:
                        break;
                }
                break;
            }
            case BOSS_HORSEMAN:
            {
                uint32 horsemanKilled = std::count_if(HorsemanDataGroup.begin(), HorsemanDataGroup.end(), [this](auto&& entry)
                {
                    Creature* cr = GetCreature(entry);
                    return cr && !cr->IsAlive();
                });
                switch (state)
                {
                    case NOT_STARTED:
                    {
                        _horsemanAchievement = true;
                        if (!horsemanKilled)
                            break;
                        for (auto&& entry : HorsemanDataGroup)
{
                            if (Creature* cr = GetCreature(entry))
{
                                cr->SetPosition(cr->GetHomePosition());
                                cr->Respawn();
                            }
                        }
                        break;
                    }
                    case IN_PROGRESS:
                    {
                        for (auto&& entry : HorsemanDataGroup)
                            if (Creature* cr = GetCreature(entry))
                                cr->SetInCombatWithZone();
                        break;
                    }
                    case DONE:
                    {
                        _events.RescheduleEvent(EVENT_AND_THEY_WOULD_ALL_GO_DOWN_TOGETHER, 15s);
                        if (horsemanKilled != HorsemanCount)
                            return false;
                        // all horsemans are killed
                        if (Creature* cr = GetCreature(DATA_BARON_RIVENDARE_BOSS))
                            cr->CastSpell(cr, SPELL_THE_FOUR_HORSEMAN_CREDIT, true);
                        ActivateWingPortal(DATA_HORSEMAN_PORTAL);
                        break;
                    }
                    default:
                        break;
                }
                break;
            }
            case BOSS_SAPPHIRON:
            {
                switch (state)
                {
                    case NOT_STARTED:
                        _sapphironAchievement = true;
                        break;
                    case DONE:
                    {
                        if (GetPersistentData(PERSISTENT_DATA_KELTHUZAD_DIALOG))
                            break;
                        StorePersistentData(PERSISTENT_DATA_KELTHUZAD_DIALOG, 1);
                        SetGoState(DATA_KELTHUZAD_GATE, GO_STATE_READY);
                        _events.ScheduleEvent(EVENT_FROSTWYRM_WATERFALL_DOOR, 5s);
                        break;
                    }
                    default:
                        break;
                }
                break;
            }
            case BOSS_KELTHUZAD:
            {
                if (state == NOT_STARTED)
                    _abominationsKilled = 0;
                break;
            }
            default:
                break;
        }
        return InstanceScript::SetBossState(bossId, state);
    }
References _abominationsKilled, _events, _faerlinaAchievement, _heiganAchievement, _horsemanAchievement, _loathebAchievement, _patchwerkRoomTrash, _sapphironAchievement, _thaddiusAchievement, ActivateWingPortal(), Creature::AI(), UnitAI::AttackStart(), BOSS_FAERLINA, BOSS_HEIGAN, BOSS_HORSEMAN, BOSS_KELTHUZAD, BOSS_LOATHEB, BOSS_MAEXXNA, BOSS_PATCHWERK, BOSS_SAPPHIRON, BOSS_THADDIUS, DATA_BARON_RIVENDARE_BOSS, DATA_HORSEMAN_PORTAL, DATA_KELTHUZAD_GATE, DATA_LOATHEB_PORTAL, DATA_MAEXXNA_PORTAL, DATA_PATCHWERK_BOSS, DATA_THADDIUS_PORTAL, DONE, EVENT_AND_THEY_WOULD_ALL_GO_DOWN_TOGETHER, EVENT_FROSTWYRM_WATERFALL_DOOR, InstanceScript::GetCreature(), ObjectAccessor::GetCreature(), InstanceScript::GetPersistentData(), GO_STATE_READY, HorsemanCount, HorsemanDataGroup, IN_PROGRESS, Unit::IsAlive(), Unit::IsInCombat(), NOT_STARTED, PERSISTENT_DATA_KELTHUZAD_DIALOG, EventMap::RescheduleEvent(), EventMap::ScheduleEvent(), InstanceScript::SetBossState(), SetGoState(), SPELL_THE_FOUR_HORSEMAN_CREDIT, and InstanceScript::StorePersistentData().
Referenced by OnCreatureCreate().
SetData()
void instance_naxxramas::SetData (uint32 id, uint32 data) inline override virtual
Reimplemented from ZoneScript.
    {
        switch (id)
        {
            case DATA_ABOMINATION_KILLED:
                ++_abominationsKilled;
                return;
            case DATA_FRENZY_REMOVED:
                _faerlinaAchievement = false;
                return;
            case DATA_CHARGES_CROSSED:
                _thaddiusAchievement = false;
                return;
            case DATA_SPORE_KILLED:
                _loathebAchievement = false;
                return;
            case DATA_HUNDRED_CLUB:
                _sapphironAchievement = false;
                return;
            case DATA_DANCE_FAIL:
                _heiganAchievement = false;
                return;
            case DATA_HEIGAN_ERUPTION:
                HeiganEruptSections(data);
                return;
            default:
                return;
        }
    }
References _abominationsKilled, _faerlinaAchievement, _heiganAchievement, _loathebAchievement, _sapphironAchievement, _thaddiusAchievement, DATA_ABOMINATION_KILLED, DATA_CHARGES_CROSSED, DATA_DANCE_FAIL, DATA_FRENZY_REMOVED, DATA_HEIGAN_ERUPTION, DATA_HUNDRED_CLUB, DATA_SPORE_KILLED, and HeiganEruptSections().
SetGoState()
void instance_naxxramas::SetGoState (uint32 dataGameObject, GOState state) inline
    {
        if (GameObject* go = GetGameObject(dataGameObject))
            go->SetGoState(state);
    }
References InstanceScript::GetGameObject().
Referenced by SetBossState(), and Update().
Update()
void instance_naxxramas::Update (uint32 diff) inline override virtual
Reimplemented from InstanceScript.
    {
        _events.Update(diff);
        switch (_events.ExecuteEvent())
        {
            case EVENT_THADDIUS_SCREAMS:
            {
                if (GetBossState(BOSS_THADDIUS) == DONE)
                    break;
                instance->PlayDirectSoundToMap(SOUND_SCREAM + urand(0, 3));
                return _events.ScheduleEvent(EVENT_THADDIUS_SCREAMS, 2min, 2min + 30s);
            }
            case EVENT_AND_THEY_WOULD_ALL_GO_DOWN_TOGETHER:
                _horsemanAchievement = false;
                break;
            case EVENT_KELTHUZAD_WING_TAUNT:
                return CreatureTalk(DATA_KELTHUZAD_BOSS, _currentWingTaunt++);
            case EVENT_HORSEMEN_INTRO1:
                CreatureTalk(DATA_THANE_KORTHAZZ_BOSS, SAY_HORSEMEN_DIALOG1);
                return _events.ScheduleEvent(EVENT_HORSEMEN_INTRO2, 4500ms);
            case EVENT_HORSEMEN_INTRO2:
                CreatureTalk(DATA_SIR_ZELIEK_BOSS, SAY_HORSEMEN_DIALOG1);
                return _events.ScheduleEvent(EVENT_HORSEMEN_INTRO3, 6500ms);
            case EVENT_HORSEMEN_INTRO3:
                CreatureTalk(DATA_LADY_BLAUMEUX_BOSS, SAY_HORSEMEN_DIALOG1);
                return _events.ScheduleEvent(EVENT_HORSEMEN_INTRO4, 6500ms);
            case EVENT_HORSEMEN_INTRO4:
                CreatureTalk(DATA_BARON_RIVENDARE_BOSS, SAY_HORSEMEN_DIALOG1);
                return _events.ScheduleEvent(EVENT_HORSEMEN_INTRO5, 6500ms);
            case EVENT_HORSEMEN_INTRO5:
                CreatureTalk(DATA_LADY_BLAUMEUX_BOSS, SAY_HORSEMEN_DIALOG2);
                return _events.ScheduleEvent(EVENT_HORSEMEN_INTRO6, 6500ms);
            case EVENT_HORSEMEN_INTRO6:
                CreatureTalk(DATA_SIR_ZELIEK_BOSS, SAY_HORSEMEN_DIALOG2);
                return _events.ScheduleEvent(EVENT_HORSEMEN_INTRO7, 6500ms);
            case EVENT_HORSEMEN_INTRO7:
                CreatureTalk(DATA_THANE_KORTHAZZ_BOSS, SAY_HORSEMEN_DIALOG2);
                return _events.ScheduleEvent(EVENT_HORSEMEN_INTRO8, 6500ms);
            case EVENT_HORSEMEN_INTRO8:
                return CreatureTalk(DATA_BARON_RIVENDARE_BOSS, SAY_HORSEMEN_DIALOG2);
            case EVENT_FROSTWYRM_WATERFALL_DOOR:
                SetGoState(DATA_SAPPHIRON_GATE, GO_STATE_ACTIVE);
                return _events.ScheduleEvent(EVENT_KELTHUZAD_LICH_KING_TALK1, 5s);
            case EVENT_KELTHUZAD_LICH_KING_TALK1:
                CreatureTalk(DATA_KELTHUZAD_BOSS, SAY_SAPP_DIALOG1);
                return _events.ScheduleEvent(EVENT_KELTHUZAD_LICH_KING_TALK2, 10s);
            case EVENT_KELTHUZAD_LICH_KING_TALK2:
                CreatureTalk(DATA_LICH_KING_BOSS, SAY_SAPP_DIALOG2_LICH);
                return _events.ScheduleEvent(EVENT_KELTHUZAD_LICH_KING_TALK3, 14s);
            case EVENT_KELTHUZAD_LICH_KING_TALK3:
                CreatureTalk(DATA_KELTHUZAD_BOSS, SAY_SAPP_DIALOG3);
                return _events.ScheduleEvent(EVENT_KELTHUZAD_LICH_KING_TALK4, 10s);
            case EVENT_KELTHUZAD_LICH_KING_TALK4:
                CreatureTalk(DATA_LICH_KING_BOSS, SAY_SAPP_DIALOG4_LICH);
                return _events.ScheduleEvent(EVENT_KELTHUZAD_LICH_KING_TALK5, 12s);
            case EVENT_KELTHUZAD_LICH_KING_TALK5:
                CreatureTalk(DATA_KELTHUZAD_BOSS, SAY_SAPP_DIALOG5);
                return _events.ScheduleEvent(EVENT_KELTHUZAD_LICH_KING_TALK6, 5s);
            case EVENT_KELTHUZAD_LICH_KING_TALK6:
                CreatureTalk(DATA_KELTHUZAD_BOSS, SAY_SAPP_DIALOG6);
                return SetGoState(DATA_KELTHUZAD_GATE, GO_STATE_ACTIVE);
            default:
                break;
        }
    }
References _currentWingTaunt, _events, _horsemanAchievement, BOSS_THADDIUS, CreatureTalk(), DATA_BARON_RIVENDARE_BOSS, DATA_KELTHUZAD_BOSS, DATA_KELTHUZAD_GATE, DATA_LADY_BLAUMEUX_BOSS, DATA_LICH_KING_BOSS, DATA_SAPPHIRON_GATE, DATA_SIR_ZELIEK_BOSS, DATA_THANE_KORTHAZZ_BOSS, DONE, EVENT_AND_THEY_WOULD_ALL_GO_DOWN_TOGETHER, EVENT_FROSTWYRM_WATERFALL_DOOR, EVENT_HORSEMEN_INTRO1, EVENT_HORSEMEN_INTRO2, EVENT_HORSEMEN_INTRO3, EVENT_HORSEMEN_INTRO4, EVENT_HORSEMEN_INTRO5, EVENT_HORSEMEN_INTRO6, EVENT_HORSEMEN_INTRO7, EVENT_HORSEMEN_INTRO8, EVENT_KELTHUZAD_LICH_KING_TALK1, EVENT_KELTHUZAD_LICH_KING_TALK2, EVENT_KELTHUZAD_LICH_KING_TALK3, EVENT_KELTHUZAD_LICH_KING_TALK4, EVENT_KELTHUZAD_LICH_KING_TALK5, EVENT_KELTHUZAD_LICH_KING_TALK6, EVENT_KELTHUZAD_WING_TAUNT, EVENT_THADDIUS_SCREAMS, EventMap::ExecuteEvent(), InstanceScript::GetBossState(), GO_STATE_ACTIVE, InstanceScript::instance, Map::PlayDirectSoundToMap(), SAY_HORSEMEN_DIALOG1, SAY_HORSEMEN_DIALOG2, SAY_SAPP_DIALOG1, SAY_SAPP_DIALOG2_LICH, SAY_SAPP_DIALOG3, SAY_SAPP_DIALOG4_LICH, SAY_SAPP_DIALOG5, SAY_SAPP_DIALOG6, EventMap::ScheduleEvent(), SetGoState(), SOUND_SCREAM, EventMap::Update(), and urand().
Member Data Documentation
_abominationsKilled
uint8 instance_naxxramas::_abominationsKilled private
Referenced by CheckAchievementCriteriaMeet(), instance_naxxramas(), SetBossState(), and SetData().
_currentWingTaunt
uint8 instance_naxxramas::_currentWingTaunt private
Referenced by instance_naxxramas(), and Update().
_events
EventMap instance_naxxramas::_events private
Referenced by ActivateWingPortal(), instance_naxxramas(), OnPlayerEnter(), SetBossState(), and Update().
_faerlinaAchievement
bool instance_naxxramas::_faerlinaAchievement private
Referenced by CheckAchievementCriteriaMeet(), instance_naxxramas(), SetBossState(), and SetData().
_heiganAchievement
bool instance_naxxramas::_heiganAchievement private
Referenced by CheckAchievementCriteriaMeet(), instance_naxxramas(), SetBossState(), and SetData().
_heiganEruption
std::set<GameObject*> instance_naxxramas::_heiganEruption[HeiganEruptSectionCount] private
Referenced by HeiganEruptSections(), instance_naxxramas(), OnGameObjectCreate(), and OnGameObjectRemove().
_horsemanAchievement
bool instance_naxxramas::_horsemanAchievement private
Referenced by CheckAchievementCriteriaMeet(), instance_naxxramas(), SetBossState(), and Update().
_horsemanLoaded
uint8 instance_naxxramas::_horsemanLoaded private
Referenced by instance_naxxramas(), and OnCreatureCreate().
_loathebAchievement
bool instance_naxxramas::_loathebAchievement private
Referenced by CheckAchievementCriteriaMeet(), instance_naxxramas(), SetBossState(), and SetData().
_patchwerkRoomTrash
GuidList instance_naxxramas::_patchwerkRoomTrash private
Referenced by instance_naxxramas(), OnCreatureCreate(), and SetBossState().
_sapphironAchievement
bool instance_naxxramas::_sapphironAchievement private
Referenced by CheckAchievementCriteriaMeet(), instance_naxxramas(), SetBossState(), and SetData().
_thaddiusAchievement
bool instance_naxxramas::_thaddiusAchievement private
Referenced by CheckAchievementCriteriaMeet(), instance_naxxramas(), SetBossState(), and SetData().
The documentation for this class was generated from the following file:
azerothcore-wotlk/src/server/scripts/Northrend/Naxxramas/instance_naxxramas.cpp