AzerothCore Doxygen
FormationMovementGenerator Class Reference
#include "FormationMovementGenerator.h"
Public Member Functions
FormationMovementGenerator (Unit *leader, float range, float angle, uint32 point1, uint32 point2)
MovementGeneratorType GetMovementGeneratorType ()
void DoInitialize (Creature *)
void DoFinalize (Creature *)
void DoReset (Creature *)
bool DoUpdate (Creature *, uint32)
Public Member Functions inherited from MovementGeneratorMedium< Creature, FormationMovementGenerator >
void Initialize (Unit *u) override
void Finalize (Unit *u) override
void Reset (Unit *u) override
bool Update (Unit *u, uint32 time_diff) override
Public Member Functions inherited from MovementGenerator
virtual ~MovementGenerator ()
virtual uint32 GetSplineId () const
virtual void unitSpeedChanged ()
virtual void Pause (uint32)
virtual void Resume (uint32)
virtual bool GetResetPosition (float &, float &, float &)
Public Member Functions inherited from AbstractFollower
AbstractFollower (Unit *target=nullptr)
virtual ~AbstractFollower ()
void SetTarget (Unit *unit)
Unit * GetTarget () const
Private Member Functions
void MovementInform (Creature *owner)
void LaunchMovement (Creature *owner, Unit *target)
Private Attributes
float const _range
float _angle
uint32 const _point1
uint32 const _point2
uint32 _lastLeaderSplineID
bool _hasPredictedDestination
bool _isMoving
Position _lastLeaderPosition
TimeTracker _nextMoveTimer
Static Private Attributes
static constexpr uint32 FORMATION_MOVEMENT_INTERVAL = 1200
Detailed Description
Constructor & Destructor Documentation
FormationMovementGenerator()
FormationMovementGenerator::FormationMovementGenerator (Unit * leader, float range, float angle, uint32 point1, uint32 point2) explicit
    : AbstractFollower(leader), _range(range), _angle(angle), _point1(point1), _point2(point2), _lastLeaderSplineID(0),
    _hasPredictedDestination(false), _isMoving(false), _nextMoveTimer(0)
{
}
Member Function Documentation
DoFinalize()
void FormationMovementGenerator::DoFinalize (Creature * owner)
{
    owner->ClearUnitState(UNIT_STATE_FOLLOW_MOVE);
}
References Unit::ClearUnitState(), and UNIT_STATE_FOLLOW_MOVE.
DoInitialize()
void FormationMovementGenerator::DoInitialize (Creature * owner)
{
    if (owner->HasUnitState(UNIT_STATE_NOT_MOVE) || owner->IsMovementPreventedByCasting())
    {
        owner->StopMoving();
        return;
    }
    _nextMoveTimer.Reset(0);
}
References _nextMoveTimer, Unit::HasUnitState(), Creature::IsMovementPreventedByCasting(), TimeTracker::Reset(), Unit::StopMoving(), and UNIT_STATE_NOT_MOVE.
Referenced by DoReset().
DoReset()
void FormationMovementGenerator::DoReset (Creature * owner)
{
    DoInitialize(owner);
}
References DoInitialize().
DoUpdate()
bool FormationMovementGenerator::DoUpdate (Creature * owner, uint32 diff)
{
    Unit* target = GetTarget();
    if (!owner || !target)
        return false;
    if (owner->HasUnitState(UNIT_STATE_NOT_MOVE) || owner->IsMovementPreventedByCasting())
    {
        owner->StopMoving();
        _nextMoveTimer.Reset(0);
        _hasPredictedDestination = false;
        _isMoving = false;
        return true;
    }
    if (target->movespline->Finalized() && target->movespline->GetId() == _lastLeaderSplineID && _hasPredictedDestination)
    {
        owner->StopMoving();
        _nextMoveTimer.Reset(0);
        _hasPredictedDestination = false;
        _isMoving = false;
        return true;
    }
    if (!owner->movespline->Finalized())
        owner->SetHomePosition(owner->GetPosition());
    if (!target->movespline->Finalized() && target->movespline->GetId() != _lastLeaderSplineID)
    {
        if (_point1 && target->IsCreature())
        {
            if (CreatureGroup* formation = target->ToCreature()->GetFormation())
            {
                if (Creature* leader = formation->GetLeader())
                {
                    uint32 currentWaypoint = leader->GetCurrentWaypointID() + 1;
                    if (currentWaypoint == _point1 || currentWaypoint == _point2)
                        _angle = Position::NormalizeOrientation(float(2 * M_PI) - _angle);
                }
            }
        }
        LaunchMovement(owner, target);
        _lastLeaderSplineID = target->movespline->GetId();
        return true;
    }
    _nextMoveTimer.Update(diff);
    if (_nextMoveTimer.Passed())
    {
        _nextMoveTimer.Reset(FORMATION_MOVEMENT_INTERVAL);
        if (_lastLeaderPosition != target->GetPosition())
        {
            LaunchMovement(owner, target);
            return true;
        }
    }
    if (_isMoving && owner->movespline->Finalized())
    {
        _isMoving = false;
        owner->SetFacingTo(target->GetOrientation());
        MovementInform(owner);
    }
    return true;
}
References _angle, _hasPredictedDestination, _isMoving, _lastLeaderPosition, _lastLeaderSplineID, _nextMoveTimer, _point1, _point2, Movement::MoveSpline::Finalized(), FORMATION_MOVEMENT_INTERVAL, Creature::GetFormation(), Movement::MoveSpline::GetId(), Position::GetOrientation(), Position::GetPosition(), AbstractFollower::GetTarget(), Unit::HasUnitState(), Object::IsCreature(), Creature::IsMovementPreventedByCasting(), LaunchMovement(), MovementInform(), Unit::movespline, Position::NormalizeOrientation(), TimeTracker::Passed(), TimeTracker::Reset(), Unit::SetFacingTo(), Creature::SetHomePosition(), Unit::StopMoving(), Object::ToCreature(), UNIT_STATE_NOT_MOVE, and TimeTracker::Update().
GetMovementGeneratorType()
MovementGeneratorType FormationMovementGenerator::GetMovementGeneratorType () inline virtual
Implements MovementGenerator.
{ return FORMATION_MOTION_TYPE; }
References FORMATION_MOTION_TYPE.
LaunchMovement()
void FormationMovementGenerator::LaunchMovement (Creature * owner, Unit * target) private
{
    float relativeAngle = 0.0f;
    if (!target->movespline->Finalized())
    {
        G3D::Vector3 const leaderDestination = target->movespline->CurrentDestination();
        relativeAngle = target->GetRelativeAngle(leaderDestination.x, leaderDestination.y);
    }
    Position dest = target->GetPosition();
    float velocity = 0.0f;
    if (!target->movespline->Finalized())
    {
        // Pick up leader's spline velocity
        velocity = target->movespline->Velocity();
        // Calculate travel distance to get a 1650ms result
        float travelDist = velocity * 1.65f;
        target->MovePositionToFirstCollision(dest, travelDist, relativeAngle);
        target->MovePositionToFirstCollision(dest, _range, _angle + relativeAngle);
        float distance = owner->GetExactDist(dest);
        float velocityMod = std::min<float>(distance / travelDist, 1.5f);
        velocity *= velocityMod;
        _hasPredictedDestination = true;
    }
    else
    {
        target->MovePositionToFirstCollision(dest, _range, _angle + relativeAngle);
        _hasPredictedDestination = false;
    }
    if (velocity == 0.0f)
        velocity = target->GetSpeed(MOVE_WALK);
    Movement::MoveSplineInit init(owner);
    init.MoveTo(dest.GetPositionX(), dest.GetPositionY(), dest.GetPositionZ());
    init.SetVelocity(velocity);
    init.Launch();
    _lastLeaderPosition.Relocate(target->GetPosition());
    _isMoving = true;
    owner->AddUnitState(UNIT_STATE_FOLLOW_MOVE);
}
References _angle, _hasPredictedDestination, _isMoving, _lastLeaderPosition, _range, Unit::AddUnitState(), Movement::MoveSpline::CurrentDestination(), Movement::MoveSpline::Finalized(), Position::GetExactDist(), Position::GetPosition(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Position::GetRelativeAngle(), Unit::GetSpeed(), Movement::MoveSplineInit::Launch(), MOVE_WALK, WorldObject::MovePositionToFirstCollision(), Unit::movespline, Movement::MoveSplineInit::MoveTo(), Position::Relocate(), Movement::MoveSplineInit::SetVelocity(), UNIT_STATE_FOLLOW_MOVE, and Movement::MoveSpline::Velocity().
Referenced by DoUpdate().
MovementInform()
void FormationMovementGenerator::MovementInform (Creature * owner) private
{
    if (owner->AI())
        owner->AI()->MovementInform(FORMATION_MOTION_TYPE, 0);
}
References Creature::AI(), FORMATION_MOTION_TYPE, and CreatureAI::MovementInform().
Referenced by DoUpdate().
Member Data Documentation
_angle
float FormationMovementGenerator::_angle private
Referenced by DoUpdate(), and LaunchMovement().
_hasPredictedDestination
bool FormationMovementGenerator::_hasPredictedDestination private
Referenced by DoUpdate(), and LaunchMovement().
_isMoving
bool FormationMovementGenerator::_isMoving private
Referenced by DoUpdate(), and LaunchMovement().
_lastLeaderPosition
Position FormationMovementGenerator::_lastLeaderPosition private
Referenced by DoUpdate(), and LaunchMovement().
_lastLeaderSplineID
uint32 FormationMovementGenerator::_lastLeaderSplineID private
Referenced by DoUpdate().
_nextMoveTimer
TimeTracker FormationMovementGenerator::_nextMoveTimer private
Referenced by DoInitialize(), and DoUpdate().
_point1
uint32 const FormationMovementGenerator::_point1 private
Referenced by DoUpdate().
_point2
uint32 const FormationMovementGenerator::_point2 private
Referenced by DoUpdate().
_range
float const FormationMovementGenerator::_range private
Referenced by LaunchMovement().
FORMATION_MOVEMENT_INTERVAL
constexpr uint32 FormationMovementGenerator::FORMATION_MOVEMENT_INTERVAL = 1200 static constexpr private
Referenced by DoUpdate().
The documentation for this class was generated from the following files:
azerothcore-wotlk/src/server/game/Movement/MovementGenerators/FormationMovementGenerator.h
azerothcore-wotlk/src/server/game/Movement/MovementGenerators/FormationMovementGenerator.cpp