AzerothCore Doxygen
ExtraAttackChainProcTest.cpp File Reference
Unit tests for extra attack chain-proc prevention.
#include "ProcChanceTestHelper.h"
#include "gtest/gtest.h"
Classes
class ExtraAttackChainProcTest
Functions
TEST_F (ExtraAttackChainProcTest, NormalProc_AllowedWhenNoExtraAttackInProgress)
TEST_F (ExtraAttackChainProcTest, SelfChain_BlockedWhenSameSpell)
TEST_F (ExtraAttackChainProcTest, CrossChain_BlockedBySwordSpecialization)
TEST_F (ExtraAttackChainProcTest, CrossChain_BlockedByHackAndSlash)
TEST_F (ExtraAttackChainProcTest, DifferentExtraAttack_AllowedWhenNotBlacklisted)
TEST_F (ExtraAttackChainProcTest, NonExtraAttackProc_UnaffectedByExtraAttackState)
TEST_F (ExtraAttackChainProcTest, Reckoning_SelfChainBlocked)
TEST_F (ExtraAttackChainProcTest, Reckoning_AllowedDuringHandOfJustice)
Variables
constexpr uint32 SPELL_RECKONING = 32746
constexpr uint32 SPELL_HAND_OF_JUSTICE = 15601
Detailed Description
Unit tests for extra attack chain-proc prevention.
Tests the logic from SpellAuraEffects.cpp:1245-1261 (CheckEffectProc):
Self-chain prevention (same extra attack spell can't proc itself)
Cross-chain prevention (Sword Specialization / Hack and Slash block all extra attack procs)
Non-blacklisted extra attack spells allow cross-proccing
Non-extra-attack procs are unaffected by the guard
Definition in file ExtraAttackChainProcTest.cpp.
Function Documentation
TEST_F() [1/8]
TEST_F (ExtraAttackChainProcTest , CrossChain_BlockedByHackAndSlash)
{
    // Reckoning trying to proc during Hack and Slash extra attack
    auto config = MakeConfig(true, SPELL_RECKONING, SPELL_HACK_AND_SLASH);
    EXPECT_TRUE(ProcChanceTestHelper::ShouldBlockExtraAttackChainProc(config))
        << "Hack and Slash extra attack should block all other extra attack procs";
}
References ProcChanceTestHelper::ShouldBlockExtraAttackChainProc(), SPELL_HACK_AND_SLASH, and SPELL_RECKONING.
TEST_F() [2/8]
TEST_F (ExtraAttackChainProcTest , CrossChain_BlockedBySwordSpecialization)
{
    // Reckoning trying to proc during Sword Spec extra attack
    auto config = MakeConfig(true, SPELL_RECKONING, SPELL_SWORD_SPECIALIZATION);
    EXPECT_TRUE(ProcChanceTestHelper::ShouldBlockExtraAttackChainProc(config))
        << "Sword Specialization extra attack should block all other extra attack procs";
}
References ProcChanceTestHelper::ShouldBlockExtraAttackChainProc(), SPELL_RECKONING, and SPELL_SWORD_SPECIALIZATION.
TEST_F() [3/8]
TEST_F (ExtraAttackChainProcTest , DifferentExtraAttack_AllowedWhenNotBlacklisted)
{
    // Sword Spec trying to proc during Hand of Justice extra attack
    // Hand of Justice (15601) is not blacklisted, so cross-proc is allowed
    auto config = MakeConfig(true, SPELL_SWORD_SPECIALIZATION, SPELL_HAND_OF_JUSTICE);
    EXPECT_FALSE(ProcChanceTestHelper::ShouldBlockExtraAttackChainProc(config))
        << "Non-blacklisted extra attack spells should allow cross-proccing";
}
References ProcChanceTestHelper::ShouldBlockExtraAttackChainProc(), SPELL_HAND_OF_JUSTICE, and SPELL_SWORD_SPECIALIZATION.
TEST_F() [4/8]
TEST_F (ExtraAttackChainProcTest , NonExtraAttackProc_UnaffectedByExtraAttackState)
{
    // A proc that does NOT grant extra attacks should never be blocked,
    // even during Sword Spec extra attack
    auto config = MakeConfig(false, 12345, SPELL_SWORD_SPECIALIZATION);
    EXPECT_FALSE(ProcChanceTestHelper::ShouldBlockExtraAttackChainProc(config))
        << "Non-extra-attack procs should be unaffected by extra attack state";
}
References ProcChanceTestHelper::ShouldBlockExtraAttackChainProc(), and SPELL_SWORD_SPECIALIZATION.
TEST_F() [5/8]
TEST_F (ExtraAttackChainProcTest , NormalProc_AllowedWhenNoExtraAttackInProgress)
{
    // lastExtraAttackSpell == 0 means no extra attack is executing
    auto config = MakeConfig(true, SPELL_SWORD_SPECIALIZATION, 0);
    EXPECT_FALSE(ProcChanceTestHelper::ShouldBlockExtraAttackChainProc(config))
        << "Extra attack proc should be allowed when no extra attack is in progress";
}
References ProcChanceTestHelper::ShouldBlockExtraAttackChainProc(), and SPELL_SWORD_SPECIALIZATION.
TEST_F() [6/8]
TEST_F (ExtraAttackChainProcTest , Reckoning_AllowedDuringHandOfJustice)
{
    // Reckoning trying to proc during Hand of Justice extra attack
    // Hand of Justice is not blacklisted, so Reckoning is allowed
    auto config = MakeConfig(true, SPELL_RECKONING, SPELL_HAND_OF_JUSTICE);
    EXPECT_FALSE(ProcChanceTestHelper::ShouldBlockExtraAttackChainProc(config))
        << "Reckoning should be allowed during Hand of Justice extra attack";
}
References ProcChanceTestHelper::ShouldBlockExtraAttackChainProc(), SPELL_HAND_OF_JUSTICE, and SPELL_RECKONING.
TEST_F() [7/8]
TEST_F (ExtraAttackChainProcTest , Reckoning_SelfChainBlocked)
{
    // Reckoning (32746) trying to proc during its own extra attack
    auto config = MakeConfig(true, SPELL_RECKONING, SPELL_RECKONING);
    EXPECT_TRUE(ProcChanceTestHelper::ShouldBlockExtraAttackChainProc(config))
        << "Reckoning should not chain-proc itself";
}
References ProcChanceTestHelper::ShouldBlockExtraAttackChainProc(), and SPELL_RECKONING.
TEST_F() [8/8]
TEST_F (ExtraAttackChainProcTest , SelfChain_BlockedWhenSameSpell)
{
    // Sword Spec trying to proc during its own extra attack
    auto config = MakeConfig(true, SPELL_SWORD_SPECIALIZATION, SPELL_SWORD_SPECIALIZATION);
    EXPECT_TRUE(ProcChanceTestHelper::ShouldBlockExtraAttackChainProc(config))
        << "Extra attack spell should not chain-proc itself";
}
References ProcChanceTestHelper::ShouldBlockExtraAttackChainProc(), and SPELL_SWORD_SPECIALIZATION.
Variable Documentation
SPELL_HAND_OF_JUSTICE
constexpr uint32 SPELL_HAND_OF_JUSTICE = 15601 constexpr
Referenced by TEST_F(), and TEST_F().
SPELL_RECKONING
constexpr uint32 SPELL_RECKONING = 32746 constexpr
Referenced by TEST_F(), TEST_F(), TEST_F(), and TEST_F().