AzerothCore Doxygen
npc_ulduar_vx001::npc_ulduar_vx001AI Struct Reference
Public Member Functions
npc_ulduar_vx001AI (Creature *pCreature)
void Reset () override
void AttackStart (Unit *) override
void SetData (uint32 id, uint32 value) override
uint32 GetData (uint32) const override
void DoAction (int32 action) override
void DamageTaken (Unit *, uint32 &damage, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void MoveInLineOfSight (Unit *) override
void KilledUnit (Unit *who) override
void EnterEvadeMode (EvadeReason why) override
void PassengerBoarded (Unit *p, int8, bool apply) override
== Fields =======================================
void SpellHit (Unit *, SpellInfo const *spell) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportPlayer (Unit *unit, Position pos)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool IsUniqueTimedEventDone (uint32 id) const
void SetUniqueTimedEventDone (uint32 id)
void ResetUniqueTimedEvent (uint32 id)
void ClearUniqueTimedEventsDone ()
void ScheduleTimedEvent (Milliseconds timerMin, Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0ms, uint32 uniqueId=0)
void ScheduleTimedEvent (Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0ms, uint32 uniqueId=0)
void ScheduleUniqueTimedEvent (Milliseconds timer, std::function< void()> exec, uint32 uniqueId)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
void SetInvincibility (bool apply)
bool IsInvincible () const
void SetAutoAttackAllowed (bool allow)
bool IsAutoAttackAllowed () const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0ms)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void OnSpellCastFinished (SpellInfo const *, SpellFinishReason)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
int32 VisualizeBoundary (uint32 duration, Unit *owner=nullptr, bool fill=false, bool checkZ=false) const
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
virtual void DistancingStarted ()
virtual void DistancingEnded ()
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void SetGUID (ObjectGuid const &, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage to any victim (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Public Attributes
InstanceScript * pInstance
EventMap events
bool bIsEvading
uint8 Phase
bool fighting
bool leftarm
uint32 spinningUpOrientation
uint16 spinningUpTimer
Public Attributes inherited from ScriptedAI
Creature * me
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
npc_ulduar_vx001AI()
npc_ulduar_vx001::npc_ulduar_vx001AI::npc_ulduar_vx001AI (Creature * pCreature) inline
                                                : ScriptedAI(pCreature)
        {
            pInstance = me->GetInstanceScript();
            bIsEvading = false;
        }
References bIsEvading, WorldObject::GetInstanceScript(), ScriptedAI::me, and pInstance.
Member Function Documentation
AttackStart()
void npc_ulduar_vx001::npc_ulduar_vx001AI::AttackStart (Unit *) inline override virtual
Reimplemented from UnitAI.
{}
DamageTaken()
void npc_ulduar_vx001::npc_ulduar_vx001AI::DamageTaken (Unit * , uint32 & , DamageEffectType , SpellSchoolMask) inline override virtual
Called at any Damage from any attacker (before damage apply)
Note
It use for recalculation damage or special reaction at damage for attack reaction use AttackedBy called for non DOT damage in Unit::DealDamage also
Reimplemented from UnitAI.
        {
            if (damage >= me->GetHealth() || me->GetHealth() < 15000)
            {
                damage = 0;
                if (me->GetReactState() == REACT_PASSIVE)
                    return;
                me->SetReactState(REACT_PASSIVE);
                if (Phase == 2)
                {
                    if (!me->HasUnitFlag(UNIT_FLAG_NOT_SELECTABLE))
                    {
                        me->SetUnitFlag(UNIT_FLAG_NOT_SELECTABLE);
                        SetData(1, 0);
                        me->InterruptNonMeleeSpells(false);
                        me->RemoveAllAurasExceptType(SPELL_AURA_CONTROL_VEHICLE);
                        me->SendMeleeAttackStop();
                        me->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_ONESHOT_CUSTOM_SPELL_06);
                        me->HandleEmoteCommand(EMOTE_ONESHOT_CUSTOM_SPELL_06);
                        if (Creature* c = GetMimiron())
                            c->AI()->SetData(0, 2);
                    }
                }
                else if (Phase == 4)
                {
                    if (!me->HasUnitFlag(UNIT_FLAG_NON_ATTACKABLE))
                    {
                        me->SetUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
                        me->InterruptNonMeleeSpells(false);
                        me->RemoveAllAurasExceptType(SPELL_AURA_CONTROL_VEHICLE);
                        me->CastSpell(me, SPELL_SELF_REPAIR, false);
                        if (Creature* c = GetMimiron())
{
                            if (c->AI()->GetData(1))
                                me->CastSpell(me, SPELL_EMERGENCY_MODE, true);
                            if (c->AI()->GetData(2))
                                me->CastSpell(me, SPELL_BERSERK, true);
                            c->AI()->SetData(0, 5);
                        }
                    }
                }
            }
        }
References Unit::CastSpell(), EMOTE_ONESHOT_CUSTOM_SPELL_06, Unit::GetHealth(), GetMimiron, Creature::GetReactState(), Unit::HandleEmoteCommand(), Unit::HasUnitFlag(), Unit::InterruptNonMeleeSpells(), ScriptedAI::me, REACT_PASSIVE, Unit::RemoveAllAurasExceptType(), Unit::SendMeleeAttackStop(), SetData(), Creature::SetReactState(), Unit::SetUInt32Value(), Unit::SetUnitFlag(), SPELL_AURA_CONTROL_VEHICLE, SPELL_BERSERK, SPELL_EMERGENCY_MODE, SPELL_SELF_REPAIR, UNIT_FLAG_NON_ATTACKABLE, UNIT_FLAG_NOT_SELECTABLE, and UNIT_NPC_EMOTESTATE.
DoAction()
void npc_ulduar_vx001::npc_ulduar_vx001AI::DoAction (int32 action) inline override virtual
Reimplemented from UnitAI.
        {
            if (action == 1337)
                if (Vehicle* vk = me->GetVehicleKit())
                    for (uint8 i = 0; i < 2; ++i)
                        if (Unit* r = vk->GetPassenger(5 + i))
                            if (r->IsCreature())
                                r->ToCreature()->DespawnOrUnsummon(1ms);
        }
References Unit::GetVehicleKit(), and ScriptedAI::me.
EnterEvadeMode()
void npc_ulduar_vx001::npc_ulduar_vx001AI::EnterEvadeMode (EvadeReason why) inline override virtual
Reimplemented from CreatureAI.
        {
            if (bIsEvading)
                return;
            bIsEvading = true;
            me->RemoveAllAuras();
            me->ExitVehicle();
            _EnterEvadeMode();
            Reset();
            if (Creature* mimiron = GetMimiron())
                mimiron->AI()->EnterEvadeMode(why);
            bIsEvading = false;
        }
References CreatureAI::_EnterEvadeMode(), bIsEvading, Unit::ExitVehicle(), GetMimiron, ScriptedAI::me, Unit::RemoveAllAuras(), and Reset().
GetData()
uint32 npc_ulduar_vx001::npc_ulduar_vx001AI::GetData (uint32) const inline override virtual
Reimplemented from UnitAI.
        {
            return spinningUpOrientation;
        }
References spinningUpOrientation.
KilledUnit()
void npc_ulduar_vx001::npc_ulduar_vx001AI::KilledUnit (Unit * who) inline override virtual
Reimplemented from CreatureAI.
        {
            if (who->IsPlayer())
                if (Creature* c = GetMimiron())
                {
                    if (Phase == 2)
                    {
                        c->AI()->Talk(SAY_VX001_SLAY);
                    }
                    else
                    {
                        c->AI()->Talk(SAY_V07TRON_SLAY);
                    }
                }
        }
References GetMimiron, Object::IsPlayer(), SAY_V07TRON_SLAY, and SAY_VX001_SLAY.
MoveInLineOfSight()
void npc_ulduar_vx001::npc_ulduar_vx001AI::MoveInLineOfSight (Unit *) inline override virtual
Reimplemented from CreatureAI.
{}
PassengerBoarded()
void npc_ulduar_vx001::npc_ulduar_vx001AI::PassengerBoarded (Unit * , int8 , bool) inline override virtual
== Fields =======================================
Reimplemented from CreatureAI.
        {
            if (p->GetEntry() == NPC_ROCKET_VISUAL && !apply)
                p->ToCreature()->DespawnOrUnsummon(8s);
        }
References Creature::DespawnOrUnsummon(), Object::GetEntry(), NPC_ROCKET_VISUAL, and Object::ToCreature().
Reset()
void npc_ulduar_vx001::npc_ulduar_vx001AI::Reset () inline override virtual
Reimplemented from UnitAI.
        {
            Phase = 0;
            fighting = false;
            leftarm = false;
            spinningUpTimer = 0;
            me->SetRegeneratingHealth(false);
            events.Reset();
        }
References fighting, leftarm, ScriptedAI::me, Creature::SetRegeneratingHealth(), and spinningUpTimer.
Referenced by EnterEvadeMode().
SetData()
void npc_ulduar_vx001::npc_ulduar_vx001AI::SetData (uint32 id, uint32 value) inline override virtual
Reimplemented from UnitAI.
        {
            if (id == 1) // setting phase to start fighting
            {
                switch (value)
                {
                    case 0:
                        Phase = 0;
                        fighting = false;
                        me->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_ONESHOT_NONE);
                        events.Reset();
                        break;
                    case 2:
                        Phase = 2;
                        fighting = true;
                        me->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_ONESHOT_SPELL_CAST_OMNI);
                        me->RemoveUnitFlag(UNIT_FLAG_NOT_SELECTABLE);
                        events.Reset();
                        events.ScheduleEvent(EVENT_SPELL_HEAT_WAVE, 10s);
                        events.ScheduleEvent(EVENT_SPELL_ROCKET_STRIKE, 16s);
                        events.ScheduleEvent(EVENT_SPELL_RAPID_BURST, 0ms);
                        events.ScheduleEvent(EVENT_SPELL_SPINNING_UP, 30s);
                        events.ScheduleEvent(EVENT_REINSTALL_ROCKETS, 3s);
                        if (Creature* c = GetMimiron())
                            if (c->AI()->GetData(1))
{
                                events.ScheduleEvent(EVENT_FLAME_SUPPRESSION_10, 7s);
                                events.ScheduleEvent(EVENT_FROST_BOMB, 1s);
                            }
                        break;
                    case 4:
                        Phase = 4;
                        fighting = true;
                        me->RemoveUnitFlag(UNIT_FLAG_NOT_SELECTABLE);
                        events.Reset();
                        events.ScheduleEvent(EVENT_REINSTALL_ROCKETS, 3s);
                        events.ScheduleEvent(EVENT_SPELL_ROCKET_STRIKE, 16s);
                        events.ScheduleEvent(EVENT_HAND_PULSE, 1ms);
                        events.ScheduleEvent(EVENT_SPELL_SPINNING_UP, 30s);
                        if (Creature* c = GetMimiron())
                            if (c->AI()->GetData(1))
                                events.ScheduleEvent(EVENT_FROST_BOMB, 1s);
                        break;
                }
            }
        }
References EMOTE_ONESHOT_NONE, EMOTE_ONESHOT_SPELL_CAST_OMNI, EVENT_FLAME_SUPPRESSION_10, EVENT_FROST_BOMB, EVENT_HAND_PULSE, EVENT_REINSTALL_ROCKETS, EVENT_SPELL_HEAT_WAVE, EVENT_SPELL_RAPID_BURST, EVENT_SPELL_ROCKET_STRIKE, EVENT_SPELL_SPINNING_UP, fighting, GetMimiron, ScriptedAI::me, Unit::RemoveUnitFlag(), Unit::SetUInt32Value(), UNIT_FLAG_NOT_SELECTABLE, and UNIT_NPC_EMOTESTATE.
Referenced by DamageTaken().
SpellHit()
void npc_ulduar_vx001::npc_ulduar_vx001AI::SpellHit (Unit * , SpellInfo const * spell) inline override virtual
Reimplemented from CreatureAI.
        {
            if (spell->Id == SPELL_SELF_REPAIR)
            {
                me->RemoveUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
                me->SetReactState(REACT_AGGRESSIVE);
            }
        }
References SpellInfo::Id, ScriptedAI::me, REACT_AGGRESSIVE, Unit::RemoveUnitFlag(), Creature::SetReactState(), SPELL_SELF_REPAIR, and UNIT_FLAG_NON_ATTACKABLE.
UpdateAI()
void npc_ulduar_vx001::npc_ulduar_vx001AI::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Implements UnitAI.
        {
            if (!fighting)
                return;
            events.Update(diff);
            if (spinningUpTimer) // executed about a second after starting casting to ensure players can see the correct direction
            {
                if (spinningUpTimer <= diff)
                {
                    float angle = (spinningUpOrientation * 2 * M_PI) / 100.0f;
                    me->SetFacingTo(angle);
                    spinningUpTimer = 0;
                }
                else
                    spinningUpTimer -= diff;
            }
            if (me->HasUnitState(UNIT_STATE_CASTING))
                return;
            switch (events.ExecuteEvent())
            {
                case 0:
                    break;
                case EVENT_SPELL_HEAT_WAVE:
                    me->CastSpell(me, SPELL_HEAT_WAVE, true);
                    events.Repeat(10s);
                    break;
                case EVENT_SPELL_ROCKET_STRIKE:
                    if (Vehicle* vk = me->GetVehicleKit())
                    {
                        for( int i = 0; i < (Phase / 2); ++i )
{
                            uint8 index = (Phase == 2 ? rand() % 2 : i);
                            if (Unit* r = vk->GetPassenger(5 + index))
                                if (Player* temp = SelectTargetFromPlayerList(100.0f))
{
                                    if (Creature* trigger = me->SummonCreature(NPC_ROCKET_STRIKE_N, temp->GetPositionX(), temp->GetPositionY(), temp->GetPositionZ(), 0.0f, TEMPSUMMON_TIMED_DESPAWN, 6000))
                                        trigger->CastSpell(trigger, SPELL_ROCKET_STRIKE_AURA, true);
                                    Position exitPos = r->GetPosition();
                                    exitPos.m_positionX += cos(me->GetOrientation()) * 2.35f;
                                    exitPos.m_positionY += std::sin(me->GetOrientation()) * 2.35f;
                                    exitPos.m_positionZ += 2.0f * Phase;
                                    r->_ExitVehicle(&exitPos);
                                    me->RemoveAurasByType(SPELL_AURA_CONTROL_VEHICLE, r->GetGUID());
                                    if (r->IsCreature())
                                        r->ToCreature()->AI()->SetData(0, 0);
                                }
                        }
                        events.Repeat(20s);
                        events.ScheduleEvent(EVENT_REINSTALL_ROCKETS, 10s);
                    }
                    break;
                case EVENT_REINSTALL_ROCKETS:
                    if (Vehicle* vk = me->GetVehicleKit())
                    {
                        for (uint8 i = 5; i <= 6; ++i)
                            if (!vk->GetPassenger(i))
                                if (TempSummon* accessory = me->SummonCreature(NPC_ROCKET_VISUAL, me->GetPositionX(), me->GetPositionY(), me->GetPositionZ() + 4.0f, me->GetOrientation(), TEMPSUMMON_MANUAL_DESPAWN))
                                    if (!me->HandleSpellClick(accessory, i))
                                        accessory->UnSummon();
                    }
                    break;
                case EVENT_SPELL_RAPID_BURST:
                    if (Player* p = SelectTargetFromPlayerList(80.0f))
                    {
                        me->CastSpell(p, SPELL_RAPID_BURST, true);
                        me->SetFacingToObject(p);
                    }
                    events.Repeat(3200ms);
                    break;
                case EVENT_HAND_PULSE:
                    if (Player* p = SelectTargetFromPlayerList(80.0f))
                    {
                        me->SetFacingToObject(p);
                        if (Unit* vb = me->GetVehicleBase())
{
                            vb->SendMeleeAttackStop();
                            vb->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_ONESHOT_NONE);
                            if (!leftarm)
{
                                vb->HandleEmoteCommand(EMOTE_ONESHOT_CUSTOM_SPELL_03);
                                me->CastSpell(p, SPELL_HAND_PULSE_R, false);
                            }
                            else
{
                                vb->HandleEmoteCommand(EMOTE_ONESHOT_CUSTOM_SPELL_04);
                                me->CastSpell(p, SPELL_HAND_PULSE_L, false);
                            }
                        }
                        leftarm = !leftarm;
                    }
                    events.Repeat(1750ms);
                    break;
                case EVENT_SPELL_SPINNING_UP:
                    events.Repeat(45s);
                    if (Player* p = SelectTargetFromPlayerList(80.0f))
                    {
                        float angle = me->GetAngle(p);
                        spinningUpOrientation = (uint32)((angle * 100.0f) / (2 * M_PI));
                        spinningUpTimer = 1500;
                        me->SetFacingTo(angle);
                        me->CastSpell(p, SPELL_SPINNING_UP, true);
                        if (Unit* vehicle = me->GetVehicleBase())
{
                            vehicle->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_STATE_CUSTOM_SPELL_01);
                            vehicle->HandleEmoteCommand(EMOTE_STATE_CUSTOM_SPELL_01);
                        }
                        events.RescheduleEvent((Phase == 2 ? EVENT_SPELL_RAPID_BURST : EVENT_HAND_PULSE), 14s + 500ms);
                    }
                    break;
                case EVENT_FLAME_SUPPRESSION_10:
                    me->CastSpell(me, SPELL_FLAME_SUPPRESSANT_10yd, false);
                    events.Repeat(10s);
                    break;
                case EVENT_FROST_BOMB:
                    me->CastCustomSpell(SPELL_VX001_FROST_BOMB, SPELLVALUE_MAX_TARGETS, 1, (Unit*)nullptr, false);
                    events.Repeat(45s);
                    break;
            }
        }
References Unit::CastCustomSpell(), Unit::CastSpell(), EMOTE_ONESHOT_CUSTOM_SPELL_03, EMOTE_ONESHOT_CUSTOM_SPELL_04, EMOTE_ONESHOT_NONE, EMOTE_STATE_CUSTOM_SPELL_01, EVENT_FLAME_SUPPRESSION_10, EVENT_FROST_BOMB, EVENT_HAND_PULSE, EVENT_REINSTALL_ROCKETS, EVENT_SPELL_HEAT_WAVE, EVENT_SPELL_RAPID_BURST, EVENT_SPELL_ROCKET_STRIKE, EVENT_SPELL_SPINNING_UP, fighting, Position::GetAngle(), Position::GetOrientation(), Position::GetPosition(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Unit::GetVehicleBase(), Unit::GetVehicleKit(), Unit::HandleSpellClick(), Unit::HasUnitState(), leftarm, Position::m_positionX, Position::m_positionY, Position::m_positionZ, ScriptedAI::me, NPC_ROCKET_STRIKE_N, NPC_ROCKET_VISUAL, Phase, Unit::RemoveAurasByType(), ScriptedAI::SelectTargetFromPlayerList(), Unit::SetFacingTo(), Unit::SetFacingToObject(), SPELL_AURA_CONTROL_VEHICLE, SPELL_FLAME_SUPPRESSANT_10yd, SPELL_HAND_PULSE_L, SPELL_HAND_PULSE_R, SPELL_HEAT_WAVE, SPELL_RAPID_BURST, SPELL_ROCKET_STRIKE_AURA, SPELL_SPINNING_UP, SPELL_VX001_FROST_BOMB, SPELLVALUE_MAX_TARGETS, spinningUpOrientation, spinningUpTimer, WorldObject::SummonCreature(), TEMPSUMMON_MANUAL_DESPAWN, TEMPSUMMON_TIMED_DESPAWN, UNIT_NPC_EMOTESTATE, and UNIT_STATE_CASTING.
Member Data Documentation
bIsEvading
bool npc_ulduar_vx001::npc_ulduar_vx001AI::bIsEvading
Referenced by EnterEvadeMode(), and npc_ulduar_vx001AI().
events
EventMap npc_ulduar_vx001::npc_ulduar_vx001AI::events
fighting
bool npc_ulduar_vx001::npc_ulduar_vx001AI::fighting
Referenced by Reset(), SetData(), and UpdateAI().
leftarm
bool npc_ulduar_vx001::npc_ulduar_vx001AI::leftarm
Referenced by Reset(), and UpdateAI().
Phase
uint8 npc_ulduar_vx001::npc_ulduar_vx001AI::Phase
Referenced by UpdateAI().
pInstance
InstanceScript* npc_ulduar_vx001::npc_ulduar_vx001AI::pInstance
Referenced by npc_ulduar_vx001AI().
spinningUpOrientation
uint32 npc_ulduar_vx001::npc_ulduar_vx001AI::spinningUpOrientation
Referenced by GetData(), and UpdateAI().
spinningUpTimer
uint16 npc_ulduar_vx001::npc_ulduar_vx001AI::spinningUpTimer
Referenced by Reset(), and UpdateAI().
The documentation for this struct was generated from the following file:
azerothcore-wotlk/src/server/scripts/Northrend/Ulduar/Ulduar/boss_mimiron.cpp