AzerothCore Doxygen
ProcEventInfo Class Reference
#include "Unit.h"
Public Member Functions
ProcEventInfo (Unit *actor, Unit *actionTarget, Unit *procTarget, uint32 typeMask, uint32 spellTypeMask, uint32 spellPhaseMask, uint32 hitMask, Spell const *spell, DamageInfo *damageInfo, HealInfo *healInfo, SpellInfo const *triggeredByAuraSpell=nullptr, int8 procAuraEffectIndex=-1)
Unit * GetActor ()
Unit * GetActionTarget () const
Unit * GetProcTarget () const
uint32 GetTypeMask () const
uint32 GetSpellTypeMask () const
uint32 GetSpellPhaseMask () const
uint32 GetHitMask () const
SpellInfo const * GetSpellInfo () const
SpellSchoolMask GetSchoolMask () const
Spell const * GetProcSpell () const
DamageInfo * GetDamageInfo () const
HealInfo * GetHealInfo () const
SpellInfo const * GetTriggerAuraSpell () const
int8 GetTriggerAuraEffectIndex () const
uint32 GetProcCooldown () const
void SetProcCooldown (uint32 cooldown)
std::optional< float > GetProcChance () const
void SetProcChance (float chance)
void ResetProcChance ()
Private Attributes
Unit *const _actor
Unit *const _actionTarget
Unit *const _procTarget
uint32 _typeMask
uint32 _spellTypeMask
uint32 _spellPhaseMask
uint32 _hitMask
uint32 _cooldown
Spell const * _spell
DamageInfo * _damageInfo
HealInfo * _healInfo
SpellInfo const *const _triggeredByAuraSpell
int8 _procAuraEffectIndex
std::optional< float > _chance
Detailed Description
Constructor & Destructor Documentation
ProcEventInfo()
ProcEventInfo::ProcEventInfo (Unit * actor, Unit * actionTarget, Unit * procTarget, uint32 typeMask, uint32 spellTypeMask, uint32 spellPhaseMask, uint32 hitMask, Spell const * spell, DamageInfo * damageInfo, HealInfo * healInfo, SpellInfo const * triggeredByAuraSpell = nullptr, int8 procAuraEffectIndex = -1) explicit
    : _actor(actor), _actionTarget(actionTarget), _procTarget(procTarget), _typeMask(typeMask), _spellTypeMask(spellTypeMask), _spellPhaseMask(spellPhaseMask),
      _hitMask(hitMask), _spell(spell), _damageInfo(damageInfo), _healInfo(healInfo), _triggeredByAuraSpell(triggeredByAuraSpell), _procAuraEffectIndex(procAuraEffectIndex)
{
    _chance.reset();
}
References _chance.
Member Function Documentation
GetActionTarget()
Unit * ProcEventInfo::GetActionTarget () const inline
{ return _actionTarget; }
References _actionTarget.
Referenced by SpellMgr::CanSpellTriggerProcOnEvent(), spell_deathbringer_blood_link_aura::CheckProc(), spell_deathbringer_blood_link_blood_beast_aura::CheckProc(), spell_xt002_321_boombot_aura::CheckProc(), spell_reliquary_of_souls_aura_of_desire_aura::CheckProc(), spell_dk_wandering_plague_aura::CheckProc(), spell_dk_blood_caked_blade::CheckProc(), spell_dk_dancing_rune_weapon::CheckProc(), spell_dru_glyph_of_rake::CheckProc(), spell_dru_glyph_of_rejuvenation::CheckProc(), spell_dru_t10_restoration_4p_bonus_dummy::CheckProc(), spell_gen_proc_on_self::CheckProc(), spell_gen_proc_not_self::CheckProc(), spell_hun_piercing_shots::CheckProc(), spell_item_lil_phylactery::CheckProc(), spell_item_trauma::CheckProc(), spell_mage_burning_determination::CheckProc(), spell_mage_molten_armor::CheckProc(), spell_pal_seal_of_command_aura::CheckProc(), spell_pri_vampiric_touch::CheckProc(), spell_pri_glyph_of_dispel_magic::CheckProc(), spell_pri_aq_3p_bonus::CheckProc(), spell_q10985_light_of_the_naaru::CheckProc(), spell_sha_nature_guardian::CheckProc(), spell_sha_glyph_of_healing_wave::CheckProc(), spell_sha_frozen_power::CheckProc(), spell_sha_lightning_overload::CheckProc(), spell_sha_lightning_shield::CheckProc(), spell_warl_decimation::CheckProc(), spell_warl_improved_drain_soul::CheckProc(), spell_warr_t3_prot_8p_bonus::CheckProc(), spell_warr_second_wind::CheckProc(), spell_item_unsated_craving::CheckProc(), spell_pri_body_and_soul::CheckProcDummy(), Aura::GetProcEffectMask(), spell_pal_seal_of_vengeance_aura::HandleApplyDoT(), spell_karazhan_wrath_titans_aura::HandleProc(), spell_deathbringer_blood_link_aura::HandleProc(), spell_deathbringer_blood_link_blood_beast_aura::HandleProc(), spell_reliquary_of_souls_aura_of_desire_aura::HandleProc(), spell_hun_glyph_of_mend_pet::HandleProc(), spell_item_trauma::HandleProc(), spell_item_blade_ward_enchant::HandleProc(), spell_item_blood_draining_enchant::HandleProc(), spell_pal_divine_purpose::HandleProc(), spell_karazhan_temptation::HandleProc(), spell_deathbringer_blood_beast_blood_link::HandleProc(), spell_putricide_ooze_tank_protection::HandleProc(), spell_uk_second_wind::HandleProc(), spell_twisted_reflection::HandleProc(), spell_pet_guard_dog::HandleProc(), spell_dk_blood_caked_blade::HandleProc(), spell_dk_dancing_rune_weapon::HandleProc(), spell_dk_acclimation::HandleProc(), spell_dk_mark_of_blood::HandleProc(), spell_dk_unholy_blight::HandleProc(), spell_dk_necrosis::HandleProc(), spell_dk_sudden_doom::HandleProc(), spell_dk_threat_of_thassarian::HandleProc(), spell_dk_glyph_of_scourge_strike::HandleProc(), spell_dk_pvp_4p_bonus::HandleProc(), spell_dru_glyph_of_rake::HandleProc(), spell_dru_glyph_of_rejuvenation::HandleProc(), spell_dru_revitalize::HandleProc(), spell_dru_t3_2p_bonus::HandleProc(), spell_dru_t3_6p_bonus::HandleProc(), spell_dru_glyph_of_shred::HandleProc(), spell_dru_glyph_of_starfire_dummy::HandleProc(), spell_gen_proc_not_self::HandleProc(), spell_gen_adaptive_warding::HandleProc(), spell_gen_moss_covered_feet::HandleProc(), spell_gen_obsidian_armor::HandleProc(), spell_gen_blade_warding::HandleProc(), spell_hun_thrill_of_the_hunt::HandleProc(), spell_hun_piercing_shots::HandleProc(), spell_item_unsated_craving::HandleProc(), spell_item_alchemists_stone::HandleProc(), spell_item_trinket_stack< StackSpell, TriggerSpell >::HandleProc(), spell_item_charm_witch_doctor::HandleProc(), spell_item_mana_drain::HandleProc(), spell_item_persistent_shield::HandleProc(), spell_item_tiny_abomination_in_a_jar::HandleProc(), spell_item_tiny_abomination_in_a_jar_hero::HandleProc(), spell_mage_blazing_speed::HandleProc(), spell_pal_seal_of_command_aura::HandleProc(), spell_pal_sacred_shield_base::HandleProc(), spell_pal_righteous_vengeance::HandleProc(), spell_pal_sheath_of_light::HandleProc(), spell_pal_glyph_of_holy_light_proc::HandleProc(), spell_pal_infusion_of_light::HandleProc(), spell_pal_item_t6_trinket::HandleProc(), spell_pal_t3_6p_bonus::HandleProc(), spell_pal_t8_2p_bonus::HandleProc(), spell_pal_glyph_of_holy_light_dummy::HandleProc(), spell_pal_heart_of_the_crusader::HandleProc(), spell_pal_improved_lay_of_hands::HandleProc(), spell_pri_glyph_of_dispel_magic::HandleProc(), spell_pri_t3_4p_bonus::HandleProc(), spell_pri_t10_heal_2p_bonus::HandleProc(), spell_pri_blessed_recovery::HandleProc(), spell_rog_glyph_of_backstab::HandleProc(), spell_rog_deadly_brew::HandleProc(), spell_sha_nature_guardian::HandleProc(), spell_sha_frozen_power::HandleProc(), spell_sha_lightning_overload::HandleProc(), spell_sha_flametongue_weapon::HandleProc(), spell_sha_glyph_of_earth_shield::HandleProc(), spell_sha_lightning_shield::HandleProc(), spell_sha_static_shock::HandleProc(), spell_sha_t10_elemental_4p_bonus::HandleProc(), spell_sha_t3_6p_bonus::HandleProc(), spell_sha_t8_elemental_4p_bonus::HandleProc(), spell_sha_t9_elemental_4p_bonus::HandleProc(), spell_sha_windfury_weapon::HandleProc(), spell_warl_seed_of_corruption_dummy::HandleProc(), spell_warl_seed_of_corruption_generic::HandleProc(), spell_warl_nether_protection::HandleProc(), spell_warr_deep_wounds_aura::HandleProc(), spell_dk_wandering_plague_aura::HandleProc(), spell_gen_black_bow_of_the_betrayer::HandleProc(), spell_item_petrified_twilight_scale::HandleProc(), spell_item_petrified_twilight_scale_heroic::HandleProc(), AuraEffect::HandleProcTriggerDamageAuraProc(), AuraEffect::HandleProcTriggerSpellAuraProc(), AuraEffect::HandleProcTriggerSpellWithValueAuraProc(), spell_pal_seal_of_vengeance_aura::HandleSeal(), spell_gen_proc_on_victim::OnProc(), spell_pal_glyph_of_divinity::OnProc(), spell_pal_judgements_of_the_just::OnProc(), and ResolveProcTriggerTarget().
GetActor()
Unit * ProcEventInfo::GetActor () inline
{ return _actor; };
References _actor.
Referenced by spell_warl_demonic_pact_aura::AfterCheckProc(), Aura::CalcProcChance(), SpellMgr::CanSpellTriggerProcOnEvent(), AuraEffect::CheckEffectProc(), spell_gen_weapon_coating_enchant::CheckProc(), spell_deathbringer_blood_link_aura::CheckProc(), spell_deathbringer_blood_link_blood_beast_aura::CheckProc(), spell_reliquary_of_souls_aura_of_desire_aura::CheckProc(), spell_gargolmar_retalliation::CheckProc(), spell_dk_improved_blood_presence_triggered::CheckProc(), spell_dk_wandering_plague_aura::CheckProc(), spell_dk_blood_caked_blade::CheckProc(), spell_dk_dancing_rune_weapon::CheckProc(), spell_dk_advantage_t10_4p::CheckProc(), spell_dk_blade_barrier::CheckProc(), spell_dk_death_rune::CheckProc(), spell_dru_t10_restoration_4p_bonus_dummy::CheckProc(), spell_dru_t9_feral_relic::CheckProc(), spell_gen_proc_on_self::CheckProc(), spell_gen_proc_not_self::CheckProc(), spell_gen_proc_reduced_above_60::CheckProc(), spell_gen_retaliation_toc::CheckProc(), spell_hun_lock_and_load::CheckProc(), spell_hun_t9_4p_bonus::CheckProc(), spell_item_green_whelp_armor::CheckProc(), spell_item_living_root_of_the_wildheart::CheckProc(), spell_mage_ignite::CheckProc(), spell_mage_combustion::CheckProc(), spell_mage_gen_extra_effects::CheckProc(), spell_mage_missile_barrage_proc::CheckProc(), spell_pal_seal_of_command_aura::CheckProc(), spell_pal_seal_of_light::CheckProc(), spell_pal_judgement_of_wisdom_mana::CheckProc(), spell_pal_spiritual_attunement::CheckProc(), spell_pal_light_s_beacon::CheckProc(), spell_pri_aq_3p_bonus::CheckProc(), spell_rog_blade_flurry::CheckProc(), spell_rog_setup::CheckProc(), spell_sha_t10_restoration_4p_bonus::CheckProc(), spell_sha_earthliving_weapon::CheckProc(), spell_sha_flametongue_weapon::CheckProc(), spell_sha_windfury_weapon::CheckProc(), spell_warl_decimation::CheckProc(), spell_warl_demonic_pact::CheckProc(), spell_warl_improved_drain_soul::CheckProc(), spell_warr_improved_spell_reflection::CheckProc(), spell_warr_sweeping_strikes::CheckProc(), spell_warr_retaliation::CheckProc(), spell_warr_second_wind::CheckProc(), spell_item_unsated_craving::CheckProc(), spell_pri_body_and_soul::CheckProcDummy(), Aura::GetProcEffectMask(), spell_pal_seal_of_vengeance_aura::HandleApplyDoT(), spell_deathbringer_blood_link_aura::HandleProc(), spell_deathbringer_blood_link_blood_beast_aura::HandleProc(), spell_xt002_321_boombot_aura::HandleProc(), spell_reliquary_of_souls_aura_of_desire_aura::HandleProc(), spell_dk_glyph_of_death_grip::HandleProc(), spell_gen_petrified_bark::HandleProc(), spell_hun_kill_command_pet::HandleProc(), spell_item_blade_ward_enchant::HandleProc(), spell_item_shadows_fate::HandleProc(), spell_mage_ignite::HandleProc(), spell_sha_tidal_force_dummy::HandleProc(), spell_warl_demonic_pact::HandleProc(), spell_anetheron_vampiric_aura::HandleProc(), spell_twisted_reflection::HandleProc(), spell_pet_guard_dog::HandleProc(), spell_pet_silverback::HandleProc(), spell_dk_improved_blood_presence_triggered::HandleProc(), spell_dk_blood_caked_blade::HandleProc(), spell_dk_dancing_rune_weapon::HandleProc(), spell_dk_mark_of_blood::HandleProc(), spell_dk_sudden_doom::HandleProc(), spell_dk_threat_of_thassarian::HandleProc(), spell_dk_glyph_of_scourge_strike::HandleProc(), spell_dru_glyph_of_barkskin::HandleProc(), spell_dru_revitalize::HandleProc(), spell_dru_t3_2p_bonus::HandleProc(), spell_dru_t3_6p_bonus::HandleProc(), spell_dru_t3_8p_bonus::HandleProc(), spell_dru_item_t6_trinket::HandleProc(), spell_dru_glyph_of_shred::HandleProc(), spell_dru_glyph_of_starfire_dummy::HandleProc(), spell_dru_t10_restoration_4p_bonus_dummy::HandleProc(), spell_dru_t9_feral_relic::HandleProc(), spell_gen_blade_warding::HandleProc(), spell_gen_vampiric_touch::HandleProc(), spell_gen_retaliation_toc::HandleProc(), spell_hun_hunting_party::HandleProc(), spell_hun_piercing_shots::HandleProc(), spell_hun_t9_4p_bonus::HandleProc(), spell_item_unsated_craving::HandleProc(), spell_item_darkmoon_card_greatness::HandleProc(), spell_item_death_choice::HandleProc(), spell_item_trinket_stack< StackSpell, TriggerSpell >::HandleProc(), spell_item_soul_preserver::HandleProc(), spell_item_charm_witch_doctor::HandleProc(), spell_item_mana_drain::HandleProc(), spell_item_aura_of_madness::HandleProc(), spell_item_deathbringers_will_normal::HandleProc(), spell_item_deathbringers_will_heroic::HandleProc(), spell_item_discerning_eye_beast_dummy::HandleProc(), spell_item_frozen_shadoweave::HandleProc(), spell_item_healing_touch_refund::HandleProc(), spell_item_heartpierce::HandleProc(), spell_item_heartpierce_hero::HandleProc(), spell_item_mark_of_conquest::HandleProc(), spell_item_persistent_shield::HandleProc(), spell_item_pet_healing::HandleProc(), spell_item_sunwell_exalted_caster_neck::HandleProc(), spell_item_sunwell_exalted_melee_neck::HandleProc(), spell_item_sunwell_exalted_tank_neck::HandleProc(), spell_item_swift_hand_justice_dummy::HandleProc(), spell_item_tiny_abomination_in_a_jar::HandleProc(), spell_item_tiny_abomination_in_a_jar_hero::HandleProc(), spell_item_totem_of_flowing_water::HandleProc(), spell_item_purified_shard_of_the_scale::HandleProc(), spell_item_shiny_shard_of_the_scale::HandleProc(), spell_item_living_root_of_the_wildheart::HandleProc(), spell_pal_seal_of_command_aura::HandleProc(), spell_pal_sacred_shield_base::HandleProc(), spell_pal_sheath_of_light::HandleProc(), spell_pal_judgement_of_light_heal::HandleProc(), spell_pal_judgement_of_wisdom_mana::HandleProc(), spell_pal_item_t6_trinket::HandleProc(), spell_pal_t3_6p_bonus::HandleProc(), spell_pal_t8_2p_bonus::HandleProc(), spell_pal_glyph_of_holy_light_dummy::HandleProc(), spell_pal_heart_of_the_crusader::HandleProc(), spell_pal_illumination::HandleProc(), spell_pal_light_s_beacon::HandleProc(), spell_pri_vampiric_touch::HandleProc(), spell_pri_aq_3p_bonus::HandleProc(), spell_pri_item_t6_trinket::HandleProc(), spell_pri_t3_4p_bonus::HandleProc(), spell_pri_t10_heal_2p_bonus::HandleProc(), spell_sha_nature_guardian::HandleProc(), spell_sha_t8_electrified::HandleProc(), spell_sha_flametongue_weapon::HandleProc(), spell_sha_glyph_of_earth_shield::HandleProc(), spell_sha_glyph_of_totem_of_wrath::HandleProc(), spell_sha_imp_water_shield::HandleProc(), spell_sha_item_t6_trinket::HandleProc(), spell_sha_lightning_shield::HandleProc(), spell_sha_static_shock::HandleProc(), spell_sha_t10_elemental_4p_bonus::HandleProc(), spell_sha_t3_6p_bonus::HandleProc(), spell_sha_t8_elemental_4p_bonus::HandleProc(), spell_sha_t9_elemental_4p_bonus::HandleProc(), spell_sha_windfury_weapon::HandleProc(), spell_warl_drain_soul::HandleProc(), spell_warl_demonic_pact_aura::HandleProc(), spell_warl_glyph_of_corruption_nightfall::HandleProc(), spell_warl_soul_leech::HandleProc(), spell_warr_sweeping_strikes::HandleProc(), spell_dk_wandering_plague_aura::HandleProc(), spell_dk_death_rune::HandleProc(), spell_hun_lock_and_load::HandleProc(), spell_item_corpse_tongue_coin::HandleProc(), spell_item_corpse_tongue_coin_heroic::HandleProc(), spell_item_soul_harvesters_charm::HandleProc(), spell_mage_gen_extra_effects::HandleProc(), spell_warl_improved_drain_soul::HandleProc(), spell_pri_body_and_soul::HandleProcDummy(), AuraEffect::HandleProcTriggerDamageAuraProc(), AuraEffect::HandleProcTriggerSpellAuraProc(), AuraEffect::HandleProcTriggerSpellWithValueAuraProc(), spell_pal_seal_of_vengeance_aura::HandleSeal(), spell_pal_glyph_of_divinity::OnProc(), spell_warr_improved_spell_reflection::OnProc(), and ResolveProcTriggerTarget().
GetDamageInfo()
DamageInfo * ProcEventInfo::GetDamageInfo () const inline
{ return _damageInfo; }
References _damageInfo.
Referenced by Aura::CalcProcChance(), spell_pri_lightwell_renew::CheckDropCharge(), AuraEffect::CheckEffectProc(), spell_deathbringer_blood_link_aura::CheckProc(), spell_deathbringer_blood_link_blood_beast_aura::CheckProc(), spell_utgarde_pinnacle_beast_mark::CheckProc(), spell_dk_wandering_plague_aura::CheckProc(), spell_dk_scent_of_blood_trigger::CheckProc(), spell_dk_acclimation::CheckProc(), spell_dk_unholy_blight::CheckProc(), spell_dk_necrosis::CheckProc(), spell_item_shadowmourne::CheckProc(), spell_mage_ignite::CheckProc(), spell_mage_master_of_elements::CheckProc(), spell_pal_sacred_shield_base::CheckProc(), spell_pal_seal_of_righteousness::CheckProc(), spell_sha_nature_guardian::CheckProc(), spell_warl_siphon_life::CheckProc(), spell_warl_fel_synergy::CheckProc(), spell_warl_nether_protection::CheckProc(), spell_warr_t3_prot_8p_bonus::CheckProc(), Aura::GetProcEffectMask(), spell_soul_deflection::HandleProc(), spell_reliquary_of_souls_aura_of_desire_aura::HandleProc(), spell_black_temple_consuming_strikes_aura::HandleProc(), spell_gen_petrified_bark::HandleProc(), spell_gen_overlords_brand::HandleProc(), spell_gen_overlords_brand_dot::HandleProc(), spell_item_blood_draining_enchant::HandleProc(), spell_mage_ignite::HandleProc(), spell_anetheron_vampiric_aura::HandleProc(), spell_the_lich_king_dark_hunger_aura::HandleProc(), spell_oculus_temporal_rift_aura::HandleProc(), spell_yogg_saron_grim_reprisal_aura::HandleProc(), spell_twisted_reflection::HandleProc(), spell_dk_improved_blood_presence_triggered::HandleProc(), spell_dk_dancing_rune_weapon::HandleProc(), spell_dk_acclimation::HandleProc(), spell_dk_blood_gorged::HandleProc(), spell_dk_unholy_blight::HandleProc(), spell_dk_necrosis::HandleProc(), spell_dru_t10_balance_4p_bonus::HandleProc(), spell_gen_vampiric_touch::HandleProc(), spell_gen_earth_shield_toc::HandleProc(), spell_hun_piercing_shots::HandleProc(), spell_item_necrotic_touch::HandleProc(), spell_item_frozen_shadoweave::HandleProc(), spell_item_pet_healing::HandleProc(), spell_mage_master_of_elements::HandleProc(), spell_pal_righteous_vengeance::HandleProc(), spell_pri_vampiric_embrace::HandleProc(), spell_pri_blessed_recovery::HandleProc(), spell_rog_blade_flurry::HandleProc(), spell_sha_t8_electrified::HandleProc(), spell_sha_spirit_hunt::HandleProc(), spell_sha_lightning_overload::HandleProc(), spell_sha_t8_elemental_4p_bonus::HandleProc(), spell_sha_t9_elemental_4p_bonus::HandleProc(), spell_warl_seed_of_corruption_aura::HandleProc(), spell_warl_seed_of_corruption_generic_aura::HandleProc(), spell_warl_seed_of_corruption_dummy::HandleProc(), spell_warl_seed_of_corruption_generic::HandleProc(), spell_warl_soul_leech::HandleProc(), spell_warl_nether_protection::HandleProc(), spell_warr_sweeping_strikes::HandleProc(), spell_dk_wandering_plague_aura::HandleProc(), spell_dk_hungering_cold::HandleProc(), spell_gen_vampiric_might::HandleProc(), spell_gen_mirrored_soul::HandleProc(), spell_blood_queen_essence_of_the_blood_queen_aura::OnProc(), spell_pal_eye_for_an_eye::OnProc(), spell_warl_siphon_life::OnProc(), and spell_warl_fel_synergy::OnProc().
GetHealInfo()
HealInfo * ProcEventInfo::GetHealInfo () const inline
{ return _healInfo; }
References _healInfo.
Referenced by Aura::CalcProcChance(), spell_dru_t10_restoration_4p_bonus_dummy::CheckProc(), spell_hun_misdirection::CheckProc(), spell_item_valanyr_hammer_of_ancient_kings::CheckProc(), spell_item_persistent_shield::CheckProc(), spell_item_commendation_of_kaelthas::CheckProc(), spell_item_sunwell_exalted_healer_neck::CheckProc(), spell_pal_sacred_shield_base::CheckProc(), spell_pal_sheath_of_light::CheckProc(), spell_pal_spiritual_attunement::CheckProc(), spell_pal_t8_2p_bonus::CheckProc(), spell_pal_glyph_of_holy_light_dummy::CheckProc(), spell_pri_item_greater_heal_refund::CheckProc(), spell_pri_aq_3p_bonus::CheckProc(), spell_pri_t5_heal_2p_bonus::CheckProc(), spell_pri_t10_heal_2p_bonus::CheckProc(), spell_gen_overlords_brand::HandleProc(), spell_gen_overlords_brand_dot::HandleProc(), spell_dru_living_seed::HandleProc(), spell_dru_glyph_of_rejuvenation::HandleProc(), spell_dru_t10_restoration_4p_bonus_dummy::HandleProc(), spell_item_blessing_of_ancient_kings::HandleProc(), spell_item_persistent_shield::HandleProc(), spell_pal_sacred_shield_base::HandleProc(), spell_pal_sheath_of_light::HandleProc(), spell_pal_spiritual_attunement::HandleProc(), spell_pal_glyph_of_holy_light_proc::HandleProc(), spell_pal_infusion_of_light::HandleProc(), spell_pal_t8_2p_bonus::HandleProc(), spell_pal_glyph_of_holy_light_dummy::HandleProc(), spell_pal_illumination::HandleProc(), spell_pal_light_s_beacon::HandleProc(), spell_pri_divine_aegis::HandleProc(), spell_pri_glyph_of_prayer_of_healing::HandleProc(), spell_pri_aq_3p_bonus::HandleProc(), spell_pri_t10_heal_2p_bonus::HandleProc(), spell_sha_t10_restoration_4p_bonus::HandleProc(), spell_sha_glyph_of_healing_wave::HandleProc(), and spell_sha_ancestral_awakening::HandleProc().
GetHitMask()
uint32 ProcEventInfo::GetHitMask () const inline
{ return _hitMask; }
References _hitMask.
Referenced by SpellMgr::CanSpellTriggerProcOnEvent(), spell_deathbringer_blood_link_aura::CheckProc(), spell_deathbringer_blood_link_blood_beast_aura::CheckProc(), spell_dk_scent_of_blood_trigger::CheckProc(), spell_mage_burning_determination::CheckProc(), spell_mage_combustion::CheckProc(), spell_pal_sacred_shield_base::CheckProc(), spell_pal_seal_of_righteousness::CheckProc(), spell_pri_item_greater_heal_refund::CheckProc(), spell_gen_overlords_brand_dot::HandleProc(), spell_mage_hot_streak::HandleProc(), spell_pal_infusion_of_light::HandleProc(), spell_rog_blade_flurry::HandleProc(), and spell_sha_lightning_overload::HandleProc().
GetProcChance()
std::optional< float > ProcEventInfo::GetProcChance () const inline
{ return _chance; }
References _chance.
GetProcCooldown()
uint32 ProcEventInfo::GetProcCooldown () const inline
{ return _cooldown; }
References _cooldown.
Referenced by spell_warl_demonic_pact_aura::HandleProc().
GetProcSpell()
Spell const * ProcEventInfo::GetProcSpell () const inline
{ return _spell; }
References _spell.
Referenced by spell_war_sudden_death_aura::AfterCheckProc(), AuraEffect::CheckEffectProc(), spell_hun_misdirection::CheckProc(), Aura::GetProcEffectMask(), and spell_mage_fingers_of_frost::PrepareProc().
GetProcTarget()
Unit * ProcEventInfo::GetProcTarget () const inline
{ return _procTarget; }
References _procTarget.
Referenced by spell_sindragosa_permeating_chill_aura::CheckProc(), spell_gargolmar_retalliation::CheckProc(), spell_hun_glyph_of_arcane_shot::CheckProc(), spell_item_blessing_of_ancient_kings::CheckProc(), spell_item_necrotic_touch::CheckProc(), spell_mage_ignite::CheckProc(), spell_pal_seal_of_light::CheckProc(), spell_pal_seal_of_righteousness::CheckProc(), spell_pri_divine_aegis::CheckProc(), spell_rog_blade_flurry::CheckProc(), spell_sha_t10_restoration_4p_bonus::CheckProc(), spell_sha_earthliving_weapon::CheckProc(), spell_warl_drain_soul::CheckProc(), spell_warr_sweeping_strikes::CheckProc(), spell_warr_retaliation::CheckProc(), spell_warr_retaliation::HandleEffectProc(), spell_ahune_spanky_hands::HandleProc(), spell_mage_ignite::HandleProc(), spell_mage_glyph_of_polymorph::HandleProc(), spell_dru_t10_balance_4p_bonus::HandleProc(), spell_dru_living_seed::HandleProc(), spell_item_blessing_of_ancient_kings::HandleProc(), spell_item_necrotic_touch::HandleProc(), spell_item_shadowmourne::HandleProc(), spell_item_sunwell_exalted_caster_neck::HandleProc(), spell_item_purified_shard_of_the_scale::HandleProc(), spell_item_shiny_shard_of_the_scale::HandleProc(), spell_mage_imp_blizzard::HandleProc(), spell_pal_seal_of_righteousness::HandleProc(), spell_pri_divine_aegis::HandleProc(), spell_pri_glyph_of_prayer_of_healing::HandleProc(), spell_sha_t10_restoration_4p_bonus::HandleProc(), spell_sha_item_lightning_shield::HandleProc(), spell_sha_item_lightning_shield_trigger::HandleProc(), spell_sha_t8_electrified::HandleProc(), spell_warl_glyph_of_shadowflame::HandleProc(), spell_pal_eye_for_an_eye::OnProc(), spell_warr_damage_shield::OnProc(), spell_koralon_meteor_fists_aura::TriggerFists(), and spell_flame_warder_meteor_fists_aura::TriggerFists().
GetSchoolMask()
SpellSchoolMask ProcEventInfo::GetSchoolMask () const
{
    if (_spell)
        return _spell->GetSpellInfo()->GetSchoolMask();
    if (_damageInfo)
        return _damageInfo->GetSchoolMask();
    if (_healInfo)
        return _healInfo->GetSchoolMask();
    return SPELL_SCHOOL_MASK_NONE;
}
References _damageInfo, _healInfo, _spell, DamageInfo::GetSchoolMask(), HealInfo::GetSchoolMask(), SpellInfo::GetSchoolMask(), Spell::GetSpellInfo(), and SPELL_SCHOOL_MASK_NONE.
Referenced by SpellMgr::CanSpellTriggerProcOnEvent(), spell_mage_burnout::HandleProc(), and spell_sha_item_mana_surge::HandleProc().
GetSpellInfo()
SpellInfo const * ProcEventInfo::GetSpellInfo () const
{
    if (_spell)
        return _spell->GetSpellInfo();
    if (_damageInfo)
        return _damageInfo->GetSpellInfo();
    if (_healInfo)
        return _healInfo->GetSpellInfo();
    return nullptr;
}
References _damageInfo, _healInfo, _spell, DamageInfo::GetSpellInfo(), HealInfo::GetSpellInfo(), and Spell::GetSpellInfo().
Referenced by Aura::CalcProcChance(), SpellMgr::CanSpellTriggerProcOnEvent(), AuraEffect::CheckEffectProc(), spell_gyth_chromatic_protection::CheckProc(), spell_karazhan_wrath_titans_aura::CheckProc(), spell_deathbringer_blood_link_aura::CheckProc(), spell_deathbringer_blood_link_blood_beast_aura::CheckProc(), spell_uk_second_wind::CheckProc(), spell_botanica_shift_form_aura::CheckProc(), spell_pet_guard_dog::CheckProc(), spell_pet_silverback::CheckProc(), spell_pet_culling_the_herd::CheckProc(), spell_dk_wandering_plague_aura::CheckProc(), spell_dk_dancing_rune_weapon::CheckProc(), spell_dk_blade_barrier::CheckProc(), spell_dk_pvp_4p_bonus::CheckProc(), spell_dru_omen_of_clarity::CheckProc(), spell_dru_moonkin_form_passive_proc::CheckProc(), spell_dru_glyph_of_innervate::CheckProc(), spell_dru_glyph_of_rake::CheckProc(), spell_dru_eclipse::CheckProc(), spell_dru_t10_restoration_4p_bonus_dummy::CheckProc(), spell_gen_allow_proc_from_spells_with_cost::CheckProc(), spell_gen_black_magic_enchant::CheckProc(), spell_gen_proc_from_direct_damage::CheckProc(), spell_gen_adaptive_warding::CheckProc(), spell_gen_obsidian_armor::CheckProc(), spell_hun_intimidation::CheckProc(), spell_hun_rapid_recuperation::CheckProc(), spell_item_essence_of_life::CheckProc(), spell_item_shadowmourne::CheckProc(), spell_item_pendant_of_the_violet_eye::CheckProc(), spell_item_crystal_spire_of_karabor::CheckProc(), spell_mage_burning_determination::CheckProc(), spell_mage_molten_armor::CheckProc(), spell_mage_burnout::CheckProc(), spell_mage_brain_freeze::CheckProc(), spell_mage_ignite::CheckProc(), spell_mage_arcane_potency::CheckProc(), spell_mage_empowered_fire::CheckProc(), spell_mage_gen_extra_effects::CheckProc(), spell_mage_missile_barrage::CheckProc(), spell_mage_dragon_breath::CheckProc(), spell_pal_seal_of_command_aura::CheckProc(), spell_pal_seal_of_light::CheckProc(), spell_pal_spiritual_attunement::CheckProc(), spell_pal_item_t6_trinket::CheckProc(), spell_pal_light_s_beacon::CheckProc(), spell_pri_vampiric_touch::CheckProc(), spell_pri_vampiric_embrace::CheckProc(), spell_pri_glyph_of_dispel_magic::CheckProc(), spell_pri_improved_spirit_tap::CheckProc(), spell_rog_quick_recovery::CheckProc(), spell_sha_earthliving_weapon::CheckProc(), spell_sha_item_mana_surge::CheckProc(), spell_sha_elemental_focus::CheckProc(), spell_sha_flurry_proc::CheckProc(), spell_sha_lightning_overload::CheckProc(), spell_sha_astral_shift_aura::CheckProc(), spell_sha_glyph_of_totem_of_wrath::CheckProc(), spell_sha_imp_water_shield::CheckProc(), spell_warl_decimation::CheckProc(), spell_warr_improved_spell_reflection::CheckProc(), spell_warr_sweeping_strikes::CheckProc(), spell_warr_second_wind::CheckProc(), spell_hun_ascpect_of_the_viper::CheckProc(), spell_pri_body_and_soul::CheckProcDummy(), spell_pri_body_and_soul::CheckProcTriggerSpell(), spell_hun_lock_and_load::CheckTrapProc(), spell_pal_seal_of_vengeance_aura::HandleApplyDoT(), spell_gyth_chromatic_protection::HandleProc(), spell_karazhan_wrath_titans_aura::HandleProc(), spell_deathbringer_blood_link_aura::HandleProc(), spell_pet_guard_dog::HandleProc(), spell_dk_dancing_rune_weapon::HandleProc(), spell_dk_threat_of_thassarian::HandleProc(), spell_dru_eclipse::HandleProc(), spell_dru_t3_8p_bonus::HandleProc(), spell_dru_item_t6_trinket::HandleProc(), spell_gen_adaptive_warding::HandleProc(), spell_gen_obsidian_armor::HandleProc(), spell_hun_glyph_of_arcane_shot::HandleProc(), spell_hun_thrill_of_the_hunt::HandleProc(), spell_item_alchemists_stone::HandleProc(), spell_mage_burnout::HandleProc(), spell_pal_seal_of_command_aura::HandleProc(), spell_pal_infusion_of_light::HandleProc(), spell_pal_light_s_beacon::HandleProc(), spell_rog_quick_recovery::HandleProc(), spell_sha_item_mana_surge::HandleProc(), spell_sha_t8_electrified::HandleProc(), spell_sha_lightning_overload::HandleProc(), spell_sha_glyph_of_earth_shield::HandleProc(), spell_sha_item_t6_trinket::HandleProc(), spell_dk_bone_shield::HandleProc(), spell_dk_hungering_cold::HandleProc(), spell_hun_rapid_recuperation_trigger::HandleRapidFireProc(), spell_hun_rapid_recuperation_trigger::HandleRapidKillingProc(), spell_pal_glyph_of_divinity::OnProc(), and Aura::PrepareProcToTrigger().
GetSpellPhaseMask()
uint32 ProcEventInfo::GetSpellPhaseMask () const inline
{ return _spellPhaseMask; }
References _spellPhaseMask.
Referenced by spell_war_sudden_death_aura::AfterCheckProc(), SpellMgr::CanSpellTriggerProcOnEvent(), and spell_mage_fingers_of_frost::PrepareProc().
GetSpellTypeMask()
uint32 ProcEventInfo::GetSpellTypeMask () const inline
{ return _spellTypeMask; }
References _spellTypeMask.
Referenced by SpellMgr::CanSpellTriggerProcOnEvent(), and spell_pri_item_t6_trinket::HandleProc().
GetTriggerAuraEffectIndex()
int8 ProcEventInfo::GetTriggerAuraEffectIndex () const inline
{ return _procAuraEffectIndex; }
References _procAuraEffectIndex.
GetTriggerAuraSpell()
SpellInfo const * ProcEventInfo::GetTriggerAuraSpell () const inline
{ return _triggeredByAuraSpell; }
References _triggeredByAuraSpell.
Referenced by spell_pal_seal_of_righteousness::CheckProc().
GetTypeMask()
uint32 ProcEventInfo::GetTypeMask () const inline
{ return _typeMask; }
References _typeMask.
Referenced by spell_pri_shadowfiend_death::AfterCheckProc(), SpellMgr::CanSpellTriggerProcOnEvent(), spell_hun_lock_and_load::CheckPeriodicProc(), spell_dru_omen_of_clarity::CheckProc(), spell_gen_allow_proc_from_spells_with_cost::CheckProc(), spell_gen_black_magic_enchant::CheckProc(), spell_gen_no_offhand_proc::CheckProc(), spell_mage_molten_armor::CheckProc(), spell_rog_combat_potency::CheckProc(), spell_sha_flametongue_weapon::CheckProc(), spell_sha_windfury_weapon::CheckProc(), spell_hun_lock_and_load::CheckTrapProc(), Aura::GetProcEffectMask(), spell_pal_seal_of_vengeance_aura::HandleApplyDoT(), spell_gen_overlords_brand::HandleProc(), spell_item_mark_of_conquest::HandleProc(), spell_pal_sacred_shield_base::HandleProc(), spell_sha_flametongue_weapon::HandleProc(), and spell_warr_deep_wounds_aura::HandleProc().
ResetProcChance()
void ProcEventInfo::ResetProcChance () inline
{ _chance.reset(); }
References _chance.
SetProcChance()
void ProcEventInfo::SetProcChance (float chance) inline
{ _chance = chance; }
References _chance.
SetProcCooldown()
void ProcEventInfo::SetProcCooldown (uint32 cooldown) inline
{ _cooldown = cooldown; }
References _cooldown.
Member Data Documentation
_actionTarget
Unit* const ProcEventInfo::_actionTarget private
Referenced by GetActionTarget().
_actor
Unit* const ProcEventInfo::_actor private
Referenced by GetActor().
_chance
std::optional<float> ProcEventInfo::_chance private
Referenced by GetProcChance(), ProcEventInfo(), ResetProcChance(), and SetProcChance().
_cooldown
uint32 ProcEventInfo::_cooldown private
Referenced by GetProcCooldown(), and SetProcCooldown().
_damageInfo
DamageInfo* ProcEventInfo::_damageInfo private
Referenced by GetDamageInfo(), GetSchoolMask(), and GetSpellInfo().
_healInfo
HealInfo* ProcEventInfo::_healInfo private
Referenced by GetHealInfo(), GetSchoolMask(), and GetSpellInfo().
_hitMask
uint32 ProcEventInfo::_hitMask private
Referenced by GetHitMask().
_procAuraEffectIndex
int8 ProcEventInfo::_procAuraEffectIndex private
Referenced by GetTriggerAuraEffectIndex().
_procTarget
Unit* const ProcEventInfo::_procTarget private
Referenced by GetProcTarget().
_spell
Spell const* ProcEventInfo::_spell private
Referenced by GetProcSpell(), GetSchoolMask(), and GetSpellInfo().
_spellPhaseMask
uint32 ProcEventInfo::_spellPhaseMask private
Referenced by GetSpellPhaseMask().
_spellTypeMask
uint32 ProcEventInfo::_spellTypeMask private
Referenced by GetSpellTypeMask().
_triggeredByAuraSpell
SpellInfo const* const ProcEventInfo::_triggeredByAuraSpell private
Referenced by GetTriggerAuraSpell().
_typeMask
uint32 ProcEventInfo::_typeMask private
Referenced by GetTypeMask().
The documentation for this class was generated from the following files:
azerothcore-wotlk/src/server/game/Entities/Unit/Unit.h
azerothcore-wotlk/src/server/game/Entities/Unit/Unit.cpp