AzerothCore Doxygen
Acore::HealthOrderPred Class Reference
Public Member Functions
HealthOrderPred (bool ascending=true)
bool operator() (WorldObject const *objA, WorldObject const *objB) const
bool operator() (Unit const *a, Unit const *b) const
Private Attributes
bool const _ascending
Detailed Description
Constructor & Destructor Documentation
HealthOrderPred()
Acore::HealthOrderPred::HealthOrderPred (bool ascending = true) inline
: _ascending(ascending) { }
Member Function Documentation
operator()() [1/2]
bool Acore::HealthOrderPred::operator() (Unit const * a, Unit const * b) const inline
        {
            uint32 rA = a ? a->GetHealth() : 0;
            uint32 rB = b ? b->GetHealth() : 0;
            return _ascending ? rA < rB : rA > rB;
        }
References _ascending, and Unit::GetHealth().
operator()() [2/2]
bool Acore::HealthOrderPred::operator() (WorldObject const * objA, WorldObject const * objB) const inline
        {
            Unit const* a = objA->ToUnit();
            Unit const* b = objB->ToUnit();
            uint32 rA = a ? a->GetHealth() : 0;
            uint32 rB = b ? b->GetHealth() : 0;
            return _ascending ? rA < rB : rA > rB;
        }
References _ascending, Unit::GetHealth(), and Object::ToUnit().
Member Data Documentation
_ascending
bool const Acore::HealthOrderPred::_ascending private
Referenced by operator()(), and operator()().
The documentation for this class was generated from the following file:
azerothcore-wotlk/src/server/game/Entities/Unit/Unit.h