AzerothCore Doxygen
ArenaTeamFilterFactoryByUserInput Class Reference
#include "ArenaTeamFilter.h"
Public Member Functions
std::unique_ptr< ArenaTeamFilter > CreateFilterByUserInput (std::string userInput)
Private Member Functions
std::vector< uint8 > ParseTypes (std::string_view userInput)
Detailed Description
Member Function Documentation
CreateFilterByUserInput()
std::unique_ptr< ArenaTeamFilter > ArenaTeamFilterFactoryByUserInput::CreateFilterByUserInput (std::string userInput) inline
    {
        std::transform(userInput.begin(), userInput.end(), userInput.begin(),
                       [](unsigned char c) { return std::tolower(c); });
        if (userInput == "all")
            return std::make_unique<ArenaTeamFilterAllTeams>();
        // Parse the input string (e.g., "2,3") into valid types
        std::vector<uint8> validTypes = ParseTypes(userInput);
        if (!validTypes.empty())
            return std::make_unique<ArenaTeamFilterByTypes>(validTypes);
        return nullptr;
    }
References ParseTypes().
Referenced by arena_commandscript::HandleArenaSeasonRewardCommand(), and TEST_F().
ParseTypes()
std::vector< uint8 > ArenaTeamFilterFactoryByUserInput::ParseTypes (std::string_view userInput) inline private
    {
        std::vector<uint8> validTypes;
        auto tokens = Acore::Tokenize(userInput, ',', false);
        for (auto const& token : tokens)
            if (auto typeOpt = Acore::StringTo<uint8>(token))
                validTypes.push_back(*typeOpt);
        return validTypes;
    }
References Acore::Tokenize().
Referenced by CreateFilterByUserInput().
The documentation for this class was generated from the following file:
azerothcore-wotlk/src/server/game/Battlegrounds/ArenaSeason/ArenaTeamFilter.h