AzerothCore Doxygen
instance_shattered_halls::instance_shattered_halls_InstanceMapScript Struct Reference
Public Member Functions
instance_shattered_halls_InstanceMapScript (Map *map)
void Initialize () override
void OnCreatureCreate (Creature *creature) override
void SetData (uint32 type, uint32 data) override
ObjectGuid GetGuidData (uint32 data) const override
void Update (uint32 diff) override
void ReadSaveDataMore (std::istringstream &data) override
void WriteSaveDataMore (std::ostringstream &data) override
Public Member Functions inherited from InstanceScript
InstanceScript (Map *map)
~InstanceScript () override
virtual void Load (char const *data)
virtual void CreatureLooted (Creature *, LootType)
virtual std::string GetSaveData ()
void SaveToDB ()
virtual bool IsEncounterInProgress () const
void OnCreatureCreate (Creature *creature) override
void OnCreatureRemove (Creature *creature) override
void OnGameObjectCreate (GameObject *go) override
void OnGameObjectRemove (GameObject *go) override
ObjectGuid GetObjectGuid (uint32 type) const
ObjectGuid GetGuidData (uint32 type) const override
Creature * GetCreature (uint32 type)
GameObject * GetGameObject (uint32 type)
virtual void OnPlayerEnter (Player *)
virtual void OnPlayerLeave (Player *)
virtual void OnPlayerAreaUpdate (Player *, uint32, uint32)
virtual void OnPlayerInWaterStateUpdate (Player *, bool)
void HandleGameObject (ObjectGuid guid, bool open, GameObject *go=nullptr)
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
void DoRespawnGameObject (uint32 type)
void DoRespawnCreature (ObjectGuid guid, bool force=false)
void DoRespawnCreature (uint32 type, bool force=false)
void DoUpdateWorldState (uint32 worldstateId, uint32 worldstateValue)
void DoSendNotifyToInstance (char const *format,...)
void DoUpdateAchievementCriteria (AchievementCriteriaTypes type, uint32 miscValue1=0, uint32 miscValue2=0, Unit *unit=nullptr)
void DoStartTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoStopTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoRemoveAurasDueToSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayer (Player *player, uint32 spell, bool includePets, bool includeControlled)
bool ServerAllowsTwoSideGroups ()
virtual bool SetBossState (uint32 id, EncounterState state)
EncounterState GetBossState (uint32 id) const
CreatureBoundary const * GetBossBoundary (uint32 id) const
BossInfo const * GetBossInfo (uint32 id) const
uint32 GetPersistentData (uint32 index) const
void StorePersistentData (uint32 index, uint32 data)
virtual bool CheckAchievementCriteriaMeet (uint32, Player const *, Unit const *=nullptr, uint32=0)
virtual bool CheckRequiredBosses (uint32, Player const *=nullptr) const
void SetCompletedEncountersMask (uint32 newMask, bool save)
uint32 GetCompletedEncounterMask () const
void SendEncounterUnit (uint32 type, Unit *unit=nullptr, uint8 param1=0, uint8 param2=0)
virtual void FillInitialWorldStates (WorldPackets::WorldState::InitWorldStates &)
uint32 GetEncounterCount () const
void MarkAreaTriggerDone (uint32 id)
void ResetAreaTriggerDone (uint32 id)
bool IsAreaTriggerDone (uint32 id) const
virtual void DoAction (int32)
void DoForAllMinions (uint32 id, std::function< void(Creature *)> exec)
void StoreGameObjectState (ObjectGuid::LowType spawnId, uint8 state)
uint8 GetStoredGameObjectState (ObjectGuid::LowType spawnId) const
void LoadInstanceSavedGameobjectStateData ()
bool IsBossDone (uint32 bossId) const
bool AllBossesDone () const
bool AllBossesDone (std::initializer_list< uint32 > bossIds) const
TeamId GetTeamIdInInstance () const
void SetTeamIdInInstance (TeamId teamId)
bool IsTwoFactionInstance () const
Public Member Functions inherited from ZoneScript
ZoneScript ()
virtual ~ZoneScript ()
virtual uint32 GetCreatureEntry (ObjectGuid::LowType, CreatureData const *data)
virtual uint32 GetGameObjectEntry (ObjectGuid::LowType, uint32 entry)
virtual void OnUnitDeath (Unit *)
virtual void OnCreatureEvade (Creature *)
virtual void SetGuidData (uint32, ObjectGuid)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
virtual uint32 GetData (uint32) const
virtual void ProcessEvent (WorldObject *, uint32)
Protected Attributes
ObjectGuid ExecutionerGUID
ObjectGuid PrisonerGUID [3]
uint32 RescueTimer
Additional Inherited Members
Static Public Member Functions inherited from InstanceScript
static std::string GetBossStateName (uint8 state)
Public Attributes inherited from InstanceScript
Map * instance
TaskScheduler scheduler
Protected Member Functions inherited from InstanceScript
void SetHeaders (std::string const &dataHeaders)
void SetBossNumber (uint32 number)
void SetPersistentDataCount (uint32 number)
void LoadBossBoundaries (BossBoundaryData const &data)
void LoadDoorData (DoorData const *data)
void LoadMinionData (MinionData const *data)
void LoadObjectData (ObjectData const *creatureData, ObjectData const *gameObjectData)
void LoadSummonData (ObjectData const *data)
void SetSummoner (Creature *creature)
void AddObject (Creature *obj, bool add=true)
void RemoveObject (Creature *obj)
void AddObject (GameObject *obj, bool add=true)
void RemoveObject (GameObject *obj)
void AddObject (WorldObject *obj, uint32 type, bool add=true)
void RemoveObject (WorldObject *obj, uint32 type)
void AddDoor (GameObject *door, bool add=true)
void RemoveDoor (GameObject *door)
void AddMinion (Creature *minion, bool add=true)
void RemoveMinion (Creature *minion)
void UpdateDoorState (GameObject *door)
void UpdateMinionState (Creature *minion, EncounterState state)
bool ReadSaveDataHeaders (std::istringstream &data)
void ReadSaveDataBossStates (std::istringstream &data)
void ReadSavePersistentData (std::istringstream &data)
void WriteSaveDataHeaders (std::ostringstream &data)
void WriteSaveDataBossStates (std::ostringstream &data)
void WritePersistentData (std::ostringstream &data)
Detailed Description
Constructor & Destructor Documentation
instance_shattered_halls_InstanceMapScript()
instance_shattered_halls::instance_shattered_halls_InstanceMapScript::instance_shattered_halls_InstanceMapScript (Map * map) inline
: InstanceScript(map) { }
Member Function Documentation
GetGuidData()
ObjectGuid instance_shattered_halls::instance_shattered_halls_InstanceMapScript::GetGuidData (uint32 data) const inline override virtual
Reimplemented from ZoneScript.
        {
            switch (data)
            {
                case DATA_PRISONER_1:
                case DATA_PRISONER_2:
                case DATA_PRISONER_3:
                    return PrisonerGUID[data - DATA_PRISONER_1];
                case DATA_EXECUTIONER:
                    return ExecutionerGUID;
            }
            return ObjectGuid::Empty;
        }
References DATA_EXECUTIONER, DATA_PRISONER_1, DATA_PRISONER_2, DATA_PRISONER_3, ObjectGuid::Empty, ExecutionerGUID, and PrisonerGUID.
Initialize()
void instance_shattered_halls::instance_shattered_halls_InstanceMapScript::Initialize () inline override virtual
Reimplemented from InstanceScript.
        {
            SetBossNumber(ENCOUNTER_COUNT);
            LoadObjectData(creatureData, nullptr);
            LoadDoorData(doorData);
            RescueTimer = 100 * MINUTE * IN_MILLISECONDS;
        }
References creatureData, doorData, ENCOUNTER_COUNT, IN_MILLISECONDS, InstanceScript::LoadDoorData(), InstanceScript::LoadObjectData(), MINUTE, RescueTimer, and InstanceScript::SetBossNumber().
OnCreatureCreate()
void instance_shattered_halls::instance_shattered_halls_InstanceMapScript::OnCreatureCreate (Creature * creature) inline override virtual
Reimplemented from ZoneScript.
        {
            switch (creature->GetEntry())
            {
                case NPC_SHATTERED_EXECUTIONER:
                    if (RescueTimer > 25 * MINUTE * IN_MILLISECONDS)
                        creature->AddLootMode(2);
                    ExecutionerGUID = creature->GetGUID();
                    break;
                case NPC_RIFLEMAN_BROWNBEARD:
                    if (GetTeamIdInInstance() == TEAM_HORDE)
                        creature->UpdateEntry(NPC_KORAG_PROUDMANE);
                    PrisonerGUID[0] = creature->GetGUID();
                    break;
                case NPC_CAPTAIN_ALINA:
                    if (GetTeamIdInInstance() == TEAM_HORDE)
                        creature->UpdateEntry(NPC_CAPTAIN_BONESHATTER);
                    PrisonerGUID[1] = creature->GetGUID();
                    break;
                case NPC_PRIVATE_JACINT:
                    if (GetTeamIdInInstance() == TEAM_HORDE)
                        creature->UpdateEntry(NPC_SCOUT_ORGARR);
                    PrisonerGUID[2] = creature->GetGUID();
                    break;
                case NPC_RANDY_WHIZZLESPROCKET:
                    if (GetTeamIdInInstance() == TEAM_HORDE)
                        creature->UpdateEntry(NPC_DRISELLA);
                    break;
            }
            InstanceScript::OnCreatureCreate(creature);
        }
References Creature::AddLootMode(), ExecutionerGUID, Object::GetEntry(), Object::GetGUID(), InstanceScript::GetTeamIdInInstance(), IN_MILLISECONDS, MINUTE, NPC_CAPTAIN_ALINA, NPC_CAPTAIN_BONESHATTER, NPC_DRISELLA, NPC_KORAG_PROUDMANE, NPC_PRIVATE_JACINT, NPC_RANDY_WHIZZLESPROCKET, NPC_RIFLEMAN_BROWNBEARD, NPC_SCOUT_ORGARR, NPC_SHATTERED_EXECUTIONER, InstanceScript::OnCreatureCreate(), PrisonerGUID, RescueTimer, TEAM_HORDE, and Creature::UpdateEntry().
ReadSaveDataMore()
void instance_shattered_halls::instance_shattered_halls_InstanceMapScript::ReadSaveDataMore (std::istringstream & data) inline override virtual
Reimplemented from InstanceScript.
        {
            data >> RescueTimer;
        }
References RescueTimer.
SetData()
void instance_shattered_halls::instance_shattered_halls_InstanceMapScript::SetData (uint32 type, uint32 data) inline override virtual
Reimplemented from ZoneScript.
        {
            if (type == DATA_ENTERED_ROOM && data == DATA_ENTERED_ROOM && RescueTimer == 100 * MINUTE * IN_MILLISECONDS)
            {
                DoCastSpellOnPlayers(SPELL_KARGATHS_EXECUTIONER_1);
                if (Creature* kargath = GetCreature(DATA_KARGATH))
                    sCreatureTextMgr->SendChat(kargath, GetTeamIdInInstance() == TEAM_ALLIANCE ? 3 : 4, nullptr, CHAT_MSG_ADDON, LANG_ADDON, TEXT_RANGE_MAP);
                RescueTimer = 80 * MINUTE * IN_MILLISECONDS;
            }
        }
References CHAT_MSG_ADDON, DATA_ENTERED_ROOM, DATA_KARGATH, InstanceScript::DoCastSpellOnPlayers(), InstanceScript::GetCreature(), InstanceScript::GetTeamIdInInstance(), IN_MILLISECONDS, LANG_ADDON, MINUTE, RescueTimer, sCreatureTextMgr, SPELL_KARGATHS_EXECUTIONER_1, TEAM_ALLIANCE, and TEXT_RANGE_MAP.
Update()
void instance_shattered_halls::instance_shattered_halls_InstanceMapScript::Update (uint32 diff) inline override virtual
Reimplemented from InstanceScript.
        {
            if (RescueTimer && RescueTimer < 100 * MINUTE * IN_MILLISECONDS)
            {
                RescueTimer -= std::min(RescueTimer, diff);
                if ((RescueTimer / IN_MILLISECONDS) == 25 * MINUTE)
                {
                    DoRemoveAurasDueToSpellOnPlayers(SPELL_KARGATHS_EXECUTIONER_1);
                    DoCastSpellOnPlayers(SPELL_KARGATHS_EXECUTIONER_2);
                    if (Creature* prisoner = instance->GetCreature(PrisonerGUID[0]))
                        Unit::Kill(prisoner, prisoner);
                    if (Creature* executioner = instance->GetCreature(ExecutionerGUID))
                        executioner->RemoveLootMode(2);
                }
                else if ((RescueTimer / IN_MILLISECONDS) == 15 * MINUTE)
                {
                    DoRemoveAurasDueToSpellOnPlayers(SPELL_KARGATHS_EXECUTIONER_2);
                    DoCastSpellOnPlayers(SPELL_KARGATHS_EXECUTIONER_3);
                    if (Creature* prisoner = instance->GetCreature(PrisonerGUID[1]))
                        Unit::Kill(prisoner, prisoner);
                }
                else if ((RescueTimer / IN_MILLISECONDS) == 0)
                {
                    DoRemoveAurasDueToSpellOnPlayers(SPELL_KARGATHS_EXECUTIONER_3);
                    if (Creature* prisoner = instance->GetCreature(PrisonerGUID[2]))
                        Unit::Kill(prisoner, prisoner);
                }
            }
        }
References InstanceScript::DoCastSpellOnPlayers(), InstanceScript::DoRemoveAurasDueToSpellOnPlayers(), ExecutionerGUID, Map::GetCreature(), IN_MILLISECONDS, InstanceScript::instance, Unit::Kill(), MINUTE, PrisonerGUID, RescueTimer, SPELL_KARGATHS_EXECUTIONER_1, SPELL_KARGATHS_EXECUTIONER_2, and SPELL_KARGATHS_EXECUTIONER_3.
WriteSaveDataMore()
void instance_shattered_halls::instance_shattered_halls_InstanceMapScript::WriteSaveDataMore (std::ostringstream & data) inline override virtual
Reimplemented from InstanceScript.
        {
            data << RescueTimer;
        }
References RescueTimer.
Member Data Documentation
ExecutionerGUID
ObjectGuid instance_shattered_halls::instance_shattered_halls_InstanceMapScript::ExecutionerGUID protected
Referenced by GetGuidData(), OnCreatureCreate(), and Update().
PrisonerGUID
ObjectGuid instance_shattered_halls::instance_shattered_halls_InstanceMapScript::PrisonerGUID[3] protected
Referenced by GetGuidData(), OnCreatureCreate(), and Update().
RescueTimer
uint32 instance_shattered_halls::instance_shattered_halls_InstanceMapScript::RescueTimer protected
Referenced by Initialize(), OnCreatureCreate(), ReadSaveDataMore(), SetData(), Update(), and WriteSaveDataMore().
The documentation for this struct was generated from the following file:
azerothcore-wotlk/src/server/scripts/Outland/HellfireCitadel/ShatteredHalls/instance_shattered_halls.cpp