AzerothCore Doxygen
autobroadcast_commandscript Class Reference
Public Member Functions
autobroadcast_commandscript ()
ChatCommandTable GetCommands () const override
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
uint16 GetTotalAvailableHooks ()
Static Public Member Functions
static bool HandleAutobroadcastListCommand (ChatHandler *handler)
static bool HandleAutobroadcastAddCommand (ChatHandler *handler, uint8 weight, Tail text)
static bool HandleAutobroadcastLocaleCommand (ChatHandler *handler, uint32 id, std::string locale, Tail text)
static bool HandleAutobroadcastRemoveCommand (ChatHandler *handler, uint32 id)
Additional Inherited Members
Protected Member Functions inherited from CommandScript
CommandScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name, uint16 totalAvailableHooks=0)
virtual ~ScriptObject ()=default
Detailed Description
Constructor & Destructor Documentation
autobroadcast_commandscript()
autobroadcast_commandscript::autobroadcast_commandscript () inline
: CommandScript("autobroadcast_commandscript") { }
Member Function Documentation
GetCommands()
ChatCommandTable autobroadcast_commandscript::GetCommands () const inline override virtual
Implements CommandScript.
    {
        static ChatCommandTable autobroadcastCommandTable =
        {
            { "list",   HandleAutobroadcastListCommand,   SEC_GAMEMASTER,    Console::Yes },
            { "add",    HandleAutobroadcastAddCommand,    SEC_ADMINISTRATOR, Console::Yes },
            { "locale", HandleAutobroadcastLocaleCommand, SEC_ADMINISTRATOR, Console::Yes },
            { "remove", HandleAutobroadcastRemoveCommand, SEC_ADMINISTRATOR, Console::Yes }
        };
        static ChatCommandTable commandTable =
        {
            { "autobroadcast", autobroadcastCommandTable }
        };
        return commandTable;
    }
References HandleAutobroadcastAddCommand(), HandleAutobroadcastListCommand(), HandleAutobroadcastLocaleCommand(), HandleAutobroadcastRemoveCommand(), SEC_ADMINISTRATOR, and SEC_GAMEMASTER.
HandleAutobroadcastAddCommand()
static bool autobroadcast_commandscript::HandleAutobroadcastAddCommand (ChatHandler * handler, uint8 weight, Tail text) inline static
    {
        if (text.empty())
            return false;
        uint32 realmId = sConfigMgr->GetOption<int32>("RealmID", 0);
        LoginDatabasePreparedStatement* stmt = LoginDatabase.GetPreparedStatement(LOGIN_INS_AUTOBROADCAST);
        stmt->SetData(0, realmId);
        stmt->SetData(1, weight);
        stmt->SetData(2, std::string(text));
        LoginDatabase.DirectExecute(stmt);
        // Retrieve the newly inserted ID
        stmt = LoginDatabase.GetPreparedStatement(LOGIN_SEL_AUTOBROADCAST_MAX_ID);
        stmt->SetData(0, realmId);
        PreparedQueryResult result = LoginDatabase.Query(stmt);
        uint32 newId = 0;
        if (result)
            newId = result->Fetch()[0].Get<uint32>();
        sAutobroadcastMgr->LoadAutobroadcasts();
        sAutobroadcastMgr->LoadAutobroadcastsLocalized();
        handler->PSendSysMessage(LANG_AUTOBROADCAST_ADD_SUCCESS, newId);
        return true;
    }
References LANG_AUTOBROADCAST_ADD_SUCCESS, LOGIN_INS_AUTOBROADCAST, LOGIN_SEL_AUTOBROADCAST_MAX_ID, LoginDatabase, ChatHandler::PSendSysMessage(), sAutobroadcastMgr, sConfigMgr, and PreparedStatementBase::SetData().
Referenced by GetCommands().
HandleAutobroadcastListCommand()
static bool autobroadcast_commandscript::HandleAutobroadcastListCommand (ChatHandler * handler) inline static
    {
        uint32 realmId = sConfigMgr->GetOption<int32>("RealmID", 0);
        LoginDatabasePreparedStatement* stmt = LoginDatabase.GetPreparedStatement(LOGIN_SEL_AUTOBROADCAST);
        stmt->SetData(0, realmId);
        PreparedQueryResult result = LoginDatabase.Query(stmt);
        if (!result)
        {
            handler->SendSysMessage(LANG_AUTOBROADCAST_LIST_EMPTY);
            return true;
        }
        // Prefetch all locales and group by id
        LoginDatabasePreparedStatement* localeStmt = LoginDatabase.GetPreparedStatement(LOGIN_SEL_AUTOBROADCAST_LOCALIZED);
        localeStmt->SetData(0, realmId);
        PreparedQueryResult localeResult = LoginDatabase.Query(localeStmt);
        std::unordered_map<uint32, std::vector<std::pair<std::string, std::string>>> localeMap;
        if (localeResult)
        {
            do
            {
                Field* localeFields = localeResult->Fetch();
                uint32 localeId = localeFields[0].Get<uint32>();
                std::string locale = localeFields[1].Get<std::string>();
                std::string localeText = localeFields[2].Get<std::string>();
                localeMap[localeId].emplace_back(std::move(locale), std::move(localeText));
            } while (localeResult->NextRow());
        }
        handler->SendSysMessage(LANG_AUTOBROADCAST_LIST_HEADER);
        do
        {
            Field* fields = result->Fetch();
            uint32 id = fields[0].Get<uint32>();
            uint8 weight = fields[1].Get<uint8>();
            std::string text = fields[2].Get<std::string>();
            handler->PSendSysMessage(LANG_AUTOBROADCAST_LIST_ENTRY, id, weight, text);
            auto itr = localeMap.find(id);
            if (itr != localeMap.end())
                for (auto const& [locale, localeText] : itr->second)
                    handler->PSendSysMessage(LANG_AUTOBROADCAST_LOCALE_ENTRY, locale, localeText);
        } while (result->NextRow());
        return true;
    }
References Field::Get(), LANG_AUTOBROADCAST_LIST_EMPTY, LANG_AUTOBROADCAST_LIST_ENTRY, LANG_AUTOBROADCAST_LIST_HEADER, LANG_AUTOBROADCAST_LOCALE_ENTRY, LOGIN_SEL_AUTOBROADCAST, LOGIN_SEL_AUTOBROADCAST_LOCALIZED, LoginDatabase, ChatHandler::PSendSysMessage(), sConfigMgr, ChatHandler::SendSysMessage(), and PreparedStatementBase::SetData().
Referenced by GetCommands().
HandleAutobroadcastLocaleCommand()
static bool autobroadcast_commandscript::HandleAutobroadcastLocaleCommand (ChatHandler * handler, uint32 id, std::string locale, Tail text) inline static
    {
        if (text.empty())
            return false;
        if (!IsLocaleValid(locale))
        {
            handler->SendErrorMessage(LANG_AUTOBROADCAST_INVALID_LOCALE);
            return true;
        }
        uint32 realmId = sConfigMgr->GetOption<int32>("RealmID", 0);
        // Verify the autobroadcast entry exists
        LoginDatabasePreparedStatement* stmt = LoginDatabase.GetPreparedStatement(LOGIN_SEL_AUTOBROADCAST_BY_ID);
        stmt->SetData(0, id);
        stmt->SetData(1, realmId);
        PreparedQueryResult result = LoginDatabase.Query(stmt);
        if (!result)
        {
            handler->SendErrorMessage(LANG_AUTOBROADCAST_NOT_FOUND, id);
            return true;
        }
        stmt = LoginDatabase.GetPreparedStatement(LOGIN_INS_AUTOBROADCAST_LOCALE);
        stmt->SetData(0, realmId);
        stmt->SetData(1, id);
        stmt->SetData(2, locale);
        stmt->SetData(3, std::string(text));
        LoginDatabase.DirectExecute(stmt);
        sAutobroadcastMgr->LoadAutobroadcasts();
        sAutobroadcastMgr->LoadAutobroadcastsLocalized();
        handler->PSendSysMessage(LANG_AUTOBROADCAST_LOCALE_SUCCESS, locale, id);
        return true;
    }
References IsLocaleValid(), LANG_AUTOBROADCAST_INVALID_LOCALE, LANG_AUTOBROADCAST_LOCALE_SUCCESS, LANG_AUTOBROADCAST_NOT_FOUND, LOGIN_INS_AUTOBROADCAST_LOCALE, LOGIN_SEL_AUTOBROADCAST_BY_ID, LoginDatabase, ChatHandler::PSendSysMessage(), sAutobroadcastMgr, sConfigMgr, ChatHandler::SendErrorMessage(), and PreparedStatementBase::SetData().
Referenced by GetCommands().
HandleAutobroadcastRemoveCommand()
static bool autobroadcast_commandscript::HandleAutobroadcastRemoveCommand (ChatHandler * handler, uint32 id) inline static
    {
        uint32 realmId = sConfigMgr->GetOption<int32>("RealmID", 0);
        // Verify the autobroadcast entry exists
        LoginDatabasePreparedStatement* stmt = LoginDatabase.GetPreparedStatement(LOGIN_SEL_AUTOBROADCAST_BY_ID);
        stmt->SetData(0, id);
        stmt->SetData(1, realmId);
        PreparedQueryResult result = LoginDatabase.Query(stmt);
        if (!result)
        {
            handler->SendErrorMessage(LANG_AUTOBROADCAST_NOT_FOUND, id);
            return true;
        }
        // Delete the autobroadcast entry
        stmt = LoginDatabase.GetPreparedStatement(LOGIN_DEL_AUTOBROADCAST);
        stmt->SetData(0, id);
        stmt->SetData(1, realmId);
        LoginDatabase.DirectExecute(stmt);
        // Delete associated locale entries
        stmt = LoginDatabase.GetPreparedStatement(LOGIN_DEL_AUTOBROADCAST_LOCALE);
        stmt->SetData(0, id);
        stmt->SetData(1, realmId);
        LoginDatabase.DirectExecute(stmt);
        sAutobroadcastMgr->LoadAutobroadcasts();
        sAutobroadcastMgr->LoadAutobroadcastsLocalized();
        handler->PSendSysMessage(LANG_AUTOBROADCAST_REMOVE_SUCCESS, id);
        return true;
    }
References LANG_AUTOBROADCAST_NOT_FOUND, LANG_AUTOBROADCAST_REMOVE_SUCCESS, LOGIN_DEL_AUTOBROADCAST, LOGIN_DEL_AUTOBROADCAST_LOCALE, LOGIN_SEL_AUTOBROADCAST_BY_ID, LoginDatabase, ChatHandler::PSendSysMessage(), sAutobroadcastMgr, sConfigMgr, ChatHandler::SendErrorMessage(), and PreparedStatementBase::SetData().
Referenced by GetCommands().
The documentation for this class was generated from the following file:
azerothcore-wotlk/src/server/scripts/Commands/cs_autobroadcast.cpp