AzerothCore Doxygen
instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript Struct Reference
Public Member Functions
instance_blackwing_lair_InstanceMapScript (Map *map)
void Initialize () override
void OnCreatureCreate (Creature *creature) override
void OnGameObjectCreate (GameObject *go) override
void OnGameObjectRemove (GameObject *go) override
uint32 GetData (uint32 data) const override
bool CheckRequiredBosses (uint32 bossId, Player const *) const override
bool SetBossState (uint32 type, EncounterState state) override
void SetData (uint32 type, uint32 data) override
ObjectGuid GetGuidData (uint32 type) const override
void OnUnitDeath (Unit *unit) override
void Update (uint32 diff) override
void ReadSaveDataMore (std::istringstream &data) override
void WriteSaveDataMore (std::ostringstream &data) override
Public Member Functions inherited from InstanceScript
InstanceScript (Map *map)
~InstanceScript () override
virtual void Load (char const *data)
virtual void CreatureLooted (Creature *, LootType)
virtual std::string GetSaveData ()
void SaveToDB ()
virtual bool IsEncounterInProgress () const
void OnCreatureCreate (Creature *creature) override
void OnCreatureRemove (Creature *creature) override
void OnGameObjectCreate (GameObject *go) override
void OnGameObjectRemove (GameObject *go) override
ObjectGuid GetObjectGuid (uint32 type) const
ObjectGuid GetGuidData (uint32 type) const override
Creature * GetCreature (uint32 type)
GameObject * GetGameObject (uint32 type)
virtual void OnPlayerEnter (Player *)
virtual void OnPlayerLeave (Player *)
virtual void OnPlayerAreaUpdate (Player *, uint32, uint32)
virtual void OnPlayerInWaterStateUpdate (Player *, bool)
void HandleGameObject (ObjectGuid guid, bool open, GameObject *go=nullptr)
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
void DoRespawnGameObject (uint32 type)
void DoRespawnCreature (ObjectGuid guid, bool force=false)
void DoRespawnCreature (uint32 type, bool force=false)
void DoUpdateWorldState (uint32 worldstateId, uint32 worldstateValue)
void DoSendNotifyToInstance (char const *format,...)
void DoUpdateAchievementCriteria (AchievementCriteriaTypes type, uint32 miscValue1=0, uint32 miscValue2=0, Unit *unit=nullptr)
void DoStartTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoStopTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoRemoveAurasDueToSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayer (Player *player, uint32 spell, bool includePets, bool includeControlled)
bool ServerAllowsTwoSideGroups ()
EncounterState GetBossState (uint32 id) const
CreatureBoundary const * GetBossBoundary (uint32 id) const
BossInfo const * GetBossInfo (uint32 id) const
uint32 GetPersistentData (uint32 index) const
void StorePersistentData (uint32 index, uint32 data)
virtual bool CheckAchievementCriteriaMeet (uint32, Player const *, Unit const *=nullptr, uint32=0)
void SetCompletedEncountersMask (uint32 newMask, bool save)
uint32 GetCompletedEncounterMask () const
void SendEncounterUnit (uint32 type, Unit *unit=nullptr, uint8 param1=0, uint8 param2=0)
virtual void FillInitialWorldStates (WorldPackets::WorldState::InitWorldStates &)
uint32 GetEncounterCount () const
void MarkAreaTriggerDone (uint32 id)
void ResetAreaTriggerDone (uint32 id)
bool IsAreaTriggerDone (uint32 id) const
virtual void DoAction (int32)
void DoForAllMinions (uint32 id, std::function< void(Creature *)> exec)
void StoreGameObjectState (ObjectGuid::LowType spawnId, uint8 state)
uint8 GetStoredGameObjectState (ObjectGuid::LowType spawnId) const
void LoadInstanceSavedGameobjectStateData ()
bool IsBossDone (uint32 bossId) const
bool AllBossesDone () const
bool AllBossesDone (std::initializer_list< uint32 > bossIds) const
TeamId GetTeamIdInInstance () const
void SetTeamIdInInstance (TeamId teamId)
bool IsTwoFactionInstance () const
Public Member Functions inherited from ZoneScript
ZoneScript ()
virtual ~ZoneScript ()
virtual uint32 GetCreatureEntry (ObjectGuid::LowType, CreatureData const *data)
virtual uint32 GetGameObjectEntry (ObjectGuid::LowType, uint32 entry)
virtual void OnCreatureEvade (Creature *)
virtual void SetGuidData (uint32, ObjectGuid)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
virtual void ProcessEvent (WorldObject *, uint32)
Protected Attributes
ObjectGuid razorgoreGUID
ObjectGuid nefarianGUID
ObjectGuid nefarianDoorGUID
uint8 EggCount
uint32 EggEvent
GuidList EggList
GuidList guardList
std::array< uint32, 2 > addsCount
uint32 NefarianLeftTunnel
uint32 NefarianRightTunnel
EventMap _events
Additional Inherited Members
Static Public Member Functions inherited from InstanceScript
static std::string GetBossStateName (uint8 state)
Public Attributes inherited from InstanceScript
Map * instance
TaskScheduler scheduler
Protected Member Functions inherited from InstanceScript
void SetHeaders (std::string const &dataHeaders)
void SetBossNumber (uint32 number)
void SetPersistentDataCount (uint32 number)
void LoadBossBoundaries (BossBoundaryData const &data)
void LoadDoorData (DoorData const *data)
void LoadMinionData (MinionData const *data)
void LoadObjectData (ObjectData const *creatureData, ObjectData const *gameObjectData)
void LoadSummonData (ObjectData const *data)
void SetSummoner (Creature *creature)
void AddObject (Creature *obj, bool add=true)
void RemoveObject (Creature *obj)
void AddObject (GameObject *obj, bool add=true)
void RemoveObject (GameObject *obj)
void AddObject (WorldObject *obj, uint32 type, bool add=true)
void RemoveObject (WorldObject *obj, uint32 type)
void AddDoor (GameObject *door, bool add=true)
void RemoveDoor (GameObject *door)
void AddMinion (Creature *minion, bool add=true)
void RemoveMinion (Creature *minion)
void UpdateDoorState (GameObject *door)
void UpdateMinionState (Creature *minion, EncounterState state)
bool ReadSaveDataHeaders (std::istringstream &data)
void ReadSaveDataBossStates (std::istringstream &data)
void ReadSavePersistentData (std::istringstream &data)
void WriteSaveDataHeaders (std::ostringstream &data)
void WriteSaveDataBossStates (std::ostringstream &data)
void WritePersistentData (std::ostringstream &data)
Detailed Description
Constructor & Destructor Documentation
instance_blackwing_lair_InstanceMapScript()
instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript::instance_blackwing_lair_InstanceMapScript (Map * map) inline
                                                            : InstanceScript(map)
        {
            SetHeaders(DataHeader);
            SetBossNumber(EncounterCount);
            LoadDoorData(doorData);
            LoadObjectData(creatureData, objectData);
        }
References creatureData, DataHeader, doorData, EncounterCount, InstanceScript::LoadDoorData(), InstanceScript::LoadObjectData(), objectData, InstanceScript::SetBossNumber(), and InstanceScript::SetHeaders().
Member Function Documentation
CheckRequiredBosses()
bool instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript::CheckRequiredBosses (uint32 bossId, Player const *) const inline override virtual
Reimplemented from InstanceScript.
        {
            switch (bossId)
            {
                case DATA_BROODLORD_LASHLAYER:
                    if (GetBossState(DATA_VAELASTRAZ_THE_CORRUPT) != DONE)
                        return false;
                    break;
                default:
                    break;
            }
            return true;
        }
References DATA_BROODLORD_LASHLAYER, DATA_VAELASTRAZ_THE_CORRUPT, DONE, and InstanceScript::GetBossState().
GetData()
uint32 instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript::GetData (uint32 data) const inline override virtual
Reimplemented from ZoneScript.
        {
            switch (data)
            {
                case DATA_NEFARIAN_LEFT_TUNNEL:
                    return NefarianLeftTunnel;
                case DATA_NEFARIAN_RIGHT_TUNNEL:
                    return NefarianRightTunnel;
                case DATA_EGG_EVENT:
                    return EggEvent;
                default:
                    break;
            }
            return 0;
        }
References DATA_EGG_EVENT, DATA_NEFARIAN_LEFT_TUNNEL, DATA_NEFARIAN_RIGHT_TUNNEL, EggEvent, NefarianLeftTunnel, and NefarianRightTunnel.
GetGuidData()
ObjectGuid instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript::GetGuidData (uint32 type) const inline override virtual
Reimplemented from ZoneScript.
        {
            switch (type)
            {
                case DATA_RAZORGORE_THE_UNTAMED:
                    return razorgoreGUID;
                default:
                    break;
            }
            return ObjectGuid::Empty;
        }
References DATA_RAZORGORE_THE_UNTAMED, ObjectGuid::Empty, and razorgoreGUID.
Initialize()
void instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript::Initialize () inline override virtual
Reimplemented from InstanceScript.
        {
            // Razorgore
            EggCount = 0;
            EggEvent = 0;
            NefarianLeftTunnel = 0;
            NefarianRightTunnel = 0;
            addsCount.fill(0);
        }
References addsCount, EggCount, EggEvent, NefarianLeftTunnel, and NefarianRightTunnel.
OnCreatureCreate()
void instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript::OnCreatureCreate (Creature * creature) inline override virtual
Reimplemented from ZoneScript.
        {
            // This is required because the tempspawn at Vael overwrites his GUID.
            if (creature->GetEntry() == NPC_VICTOR_NEFARIUS && creature->ToTempSummon())
            {
                return;
            }
            InstanceScript::OnCreatureCreate(creature);
            switch (creature->GetEntry())
            {
                case NPC_RAZORGORE:
                    razorgoreGUID = creature->GetGUID();
                    break;
                case NPC_BLACKWING_DRAGON:
                    ++addsCount[0];
                    if (Creature* razor = instance->GetCreature(razorgoreGUID))
                    {
                        if (CreatureAI* razorAI = razor->AI())
{
                            razorAI->JustSummoned(creature);
                        }
                    }
                    break;
                case NPC_BLACKWING_LEGIONAIRE:
                case NPC_BLACKWING_MAGE:
                    ++addsCount[1];
                    if (Creature* razor = instance->GetCreature(razorgoreGUID))
                    {
                        if (CreatureAI* razorAI = razor->AI())
{
                            razorAI->JustSummoned(creature);
                        }
                    }
                    break;
                case NPC_BLACKWING_GUARDSMAN:
                    guardList.push_back(creature->GetGUID());
                    break;
                case NPC_NEFARIAN:
                    nefarianGUID = creature->GetGUID();
                    break;
                case NPC_BLACK_DRAKONID:
                case NPC_BLUE_DRAKONID:
                case NPC_BRONZE_DRAKONID:
                case NPC_CHROMATIC_DRAKONID:
                case NPC_GREEN_DRAKONID:
                case NPC_RED_DRAKONID:
                    if (Creature* nefarius = GetCreature(DATA_LORD_VICTOR_NEFARIUS))
                    {
                        if (CreatureAI* nefariusAI = nefarius->AI())
{
                            nefariusAI->JustSummoned(creature);
                        }
                    }
                    break;
                default:
                    break;
            }
        }
References addsCount, DATA_LORD_VICTOR_NEFARIUS, Map::GetCreature(), InstanceScript::GetCreature(), Object::GetEntry(), Object::GetGUID(), guardList, InstanceScript::instance, nefarianGUID, NPC_BLACK_DRAKONID, NPC_BLACKWING_DRAGON, NPC_BLACKWING_GUARDSMAN, NPC_BLACKWING_LEGIONAIRE, NPC_BLACKWING_MAGE, NPC_BLUE_DRAKONID, NPC_BRONZE_DRAKONID, NPC_CHROMATIC_DRAKONID, NPC_GREEN_DRAKONID, NPC_NEFARIAN, NPC_RAZORGORE, NPC_RED_DRAKONID, NPC_VICTOR_NEFARIUS, InstanceScript::OnCreatureCreate(), razorgoreGUID, and Unit::ToTempSummon().
OnGameObjectCreate()
void instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript::OnGameObjectCreate (GameObject * go) inline override virtual
Reimplemented from ZoneScript.
        {
            InstanceScript::OnGameObjectCreate(go);
            switch (go->GetEntry())
            {
                case GO_BLACK_DRAGON_EGG:
                    if (GetBossState(DATA_FIREMAW) == DONE)
                    {
                        go->SetPhaseMask(2, true);
                    }
                    else
                    {
                        EggList.push_back(go->GetGUID());
                    }
                    break;
                default:
                    break;
            }
        }
References DATA_FIREMAW, DONE, EggList, InstanceScript::GetBossState(), Object::GetEntry(), Object::GetGUID(), GO_BLACK_DRAGON_EGG, InstanceScript::OnGameObjectCreate(), and GameObject::SetPhaseMask().
OnGameObjectRemove()
void instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript::OnGameObjectRemove (GameObject * go) inline override virtual
Reimplemented from ZoneScript.
        {
            InstanceScript::OnGameObjectRemove(go);
            if (go->GetEntry() == GO_BLACK_DRAGON_EGG)
                EggList.remove(go->GetGUID());
        }
References EggList, Object::GetEntry(), Object::GetGUID(), GO_BLACK_DRAGON_EGG, and InstanceScript::OnGameObjectRemove().
OnUnitDeath()
void instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript::OnUnitDeath (Unit * unit) inline override virtual
Reimplemented from ZoneScript.
        {
            switch (unit->GetEntry())
            {
                case NPC_BLACKWING_DRAGON:
                    --addsCount[0];
                    if (EggEvent != DONE && _events.GetTimeUntilEvent(EVENT_RAZOR_SPAWN) == Milliseconds::max())
                    {
                        _events.ScheduleEvent(EVENT_RAZOR_SPAWN, 1s);
                    }
                    break;
                case NPC_BLACKWING_LEGIONAIRE:
                case NPC_BLACKWING_MAGE:
                    --addsCount[1];
                    if (EggEvent != DONE && _events.GetTimeUntilEvent(EVENT_RAZOR_SPAWN) == Milliseconds::max())
                    {
                        _events.ScheduleEvent(EVENT_RAZOR_SPAWN, 1s);
                    }
                    break;
                default:
                    break;
            }
        }
References _events, addsCount, DONE, EggEvent, EVENT_RAZOR_SPAWN, Object::GetEntry(), EventMap::GetTimeUntilEvent(), NPC_BLACKWING_DRAGON, NPC_BLACKWING_LEGIONAIRE, NPC_BLACKWING_MAGE, and EventMap::ScheduleEvent().
ReadSaveDataMore()
void instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript::ReadSaveDataMore (std::istringstream & data) inline override virtual
Reimplemented from InstanceScript.
        {
            data >> NefarianLeftTunnel;
            data >> NefarianRightTunnel;
        }
References NefarianLeftTunnel, and NefarianRightTunnel.
SetBossState()
bool instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript::SetBossState (uint32 type, EncounterState state) inline override virtual
Todo:
: after dynamic spawns
Reimplemented from InstanceScript.
        {
            if (!InstanceScript::SetBossState(type, state))
                return false;
            switch (type)
            {
                case DATA_RAZORGORE_THE_UNTAMED:
                    if (state == DONE)
                    {
                        for (ObjectGuid const& guid : EggList)
{
                            // Eggs should be destroyed instead
                            if (GameObject* egg = instance->GetGameObject(guid))
{
                                egg->SetPhaseMask(2, true);
                            }
                        }
                    }
                    break;
                case DATA_NEFARIAN:
                    switch (state)
                    {
                        case FAIL:
                            _events.ScheduleEvent(EVENT_RESPAWN_NEFARIUS, 15min);
                            [[fallthrough]];
                        case NOT_STARTED:
                            if (Creature* nefarian = instance->GetCreature(nefarianGUID))
{
                                nefarian->DespawnOrUnsummon();
                            }
                            break;
                        default:
                            break;
                    }
                    break;
            }
            return true;
        }
References _events, DATA_NEFARIAN, DATA_RAZORGORE_THE_UNTAMED, DONE, EggList, EVENT_RESPAWN_NEFARIUS, FAIL, Map::GetCreature(), Map::GetGameObject(), InstanceScript::instance, nefarianGUID, NOT_STARTED, EventMap::ScheduleEvent(), and InstanceScript::SetBossState().
SetData()
void instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript::SetData (uint32 type, uint32 data) inline override virtual
Reimplemented from ZoneScript.
        {
            if (type == DATA_EGG_EVENT)
            {
                switch (data)
                {
                    case DONE:
                        EggEvent = data;
                        break;
                    case FAIL:
                        _events.CancelEvent(EVENT_RAZOR_SPAWN);
                        break;
                    case IN_PROGRESS:
                        _events.ScheduleEvent(EVENT_RAZOR_SPAWN, 45s);
                        EggEvent = data;
                        EggCount = 0;
                        addsCount.fill(0);
                        break;
                    case NOT_STARTED:
                        _events.CancelEvent(EVENT_RAZOR_SPAWN);
                        EggEvent = data;
                        EggCount = 0;
                        addsCount.fill(0);
                        for (ObjectGuid const& guid : EggList)
{
                            DoRespawnGameObject(guid, 0);
                        }
                        DoRespawnCreature(DATA_GRETHOK);
                        for (ObjectGuid const& guid : guardList)
{
                            DoRespawnCreature(guid);
                        }
                        break;
                    case SPECIAL:
                        if (EggEvent == NOT_STARTED)
                            SetData(DATA_EGG_EVENT, IN_PROGRESS);
                        if (++EggCount >= EggList.size())
{
                            if (Creature* razor = instance->GetCreature(razorgoreGUID))
{
                                SetData(DATA_EGG_EVENT, DONE);
                                razor->RemoveAurasDueToSpell(19832); // MindControl
                                DoRemoveAurasDueToSpellOnPlayers(19832);
                            }
                            _events.ScheduleEvent(EVENT_RAZOR_PHASE_TWO, 1s);
                            _events.CancelEvent(EVENT_RAZOR_SPAWN);
                        }
                        break;
                }
            }
            if (type == DATA_NEFARIAN_LEFT_TUNNEL)
            {
                NefarianLeftTunnel = data;
            }
            if (type == DATA_NEFARIAN_RIGHT_TUNNEL)
            {
                NefarianRightTunnel = data;
            }
        }
References _events, addsCount, EventMap::CancelEvent(), DATA_EGG_EVENT, DATA_GRETHOK, DATA_NEFARIAN_LEFT_TUNNEL, DATA_NEFARIAN_RIGHT_TUNNEL, DONE, InstanceScript::DoRemoveAurasDueToSpellOnPlayers(), InstanceScript::DoRespawnCreature(), InstanceScript::DoRespawnGameObject(), EggCount, EggEvent, EggList, EVENT_RAZOR_PHASE_TWO, EVENT_RAZOR_SPAWN, FAIL, Map::GetCreature(), guardList, IN_PROGRESS, InstanceScript::instance, NefarianLeftTunnel, NefarianRightTunnel, NOT_STARTED, razorgoreGUID, EventMap::ScheduleEvent(), SetData(), and SPECIAL.
Referenced by SetData().
Update()
void instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript::Update (uint32 diff) inline override virtual
Reimplemented from InstanceScript.
        {
            if (_events.Empty())
                return;
            _events.Update(diff);
            while (uint32 eventId = _events.ExecuteEvent())
            {
                switch (eventId)
                {
                    case EVENT_RAZOR_SPAWN:
                        if (EggEvent == IN_PROGRESS)
{
                            bool spawnMoreAdds = true;
                            for (uint8 i = urand(2, 5); i > 0; --i)
{
                                uint32 mobEntry = Entry[urand(0, 2)];
                                uint32 dragonkinsCount = addsCount[0];
                                uint32 orcsCount = addsCount[1];
                                // If more than 12 dragonkins...
                                if (dragonkinsCount >= 12)
{
                                    //... and more than 40 orcs - stop spawning more adds.
                                    if (orcsCount >= 40)
{
                                        spawnMoreAdds = false;
                                        break;
                                    }
                                    //... - stop spawning them.
                                    else if (mobEntry == NPC_BLACKWING_DRAGON)
{
                                        continue;
                                    }
                                }
                                // If more than 40 orcs - stop spawning them.
                                else if (orcsCount >= 40 && mobEntry != NPC_BLACKWING_DRAGON)
{
                                    continue;
                                }
                                if (Creature* summon = instance->SummonCreature(mobEntry, SummonPosition[urand(0, 7)]))
{
                                    summon->AI()->DoZoneInCombat();
                                }
                            }
                            if (spawnMoreAdds)
{
                                _events.ScheduleEvent(EVENT_RAZOR_SPAWN, 15000);
                            }
                        }
                        break;
                    case EVENT_RAZOR_PHASE_TWO:
                        _events.CancelEvent(EVENT_RAZOR_SPAWN);
                        if (Creature* razor = instance->GetCreature(razorgoreGUID))
                            razor->AI()->DoAction(ACTION_PHASE_TWO);
                        break;
                    case EVENT_RESPAWN_NEFARIUS:
                        if (Creature* nefarius = GetCreature(DATA_LORD_VICTOR_NEFARIUS))
{
                            nefarius->SetPhaseMask(1, true);
                            nefarius->setActive(true);
                            nefarius->Respawn();
                            nefarius->GetMotionMaster()->MoveTargetedHome();
                        }
                        break;
                }
            }
        }
References _events, ACTION_PHASE_TWO, addsCount, EventMap::CancelEvent(), DATA_LORD_VICTOR_NEFARIUS, EggEvent, EventMap::Empty(), Entry, EVENT_RAZOR_PHASE_TWO, EVENT_RAZOR_SPAWN, EVENT_RESPAWN_NEFARIUS, EventMap::ExecuteEvent(), Map::GetCreature(), InstanceScript::GetCreature(), IN_PROGRESS, InstanceScript::instance, NPC_BLACKWING_DRAGON, razorgoreGUID, EventMap::ScheduleEvent(), Map::SummonCreature(), SummonPosition, EventMap::Update(), and urand().
WriteSaveDataMore()
void instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript::WriteSaveDataMore (std::ostringstream & data) inline override virtual
Reimplemented from InstanceScript.
        {
            data << NefarianLeftTunnel << ' ' << NefarianRightTunnel;
        }
References NefarianLeftTunnel, and NefarianRightTunnel.
Member Data Documentation
_events
EventMap instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript::_events protected
Referenced by OnUnitDeath(), SetBossState(), SetData(), and Update().
addsCount
std::array<uint32, 2> instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript::addsCount protected
Referenced by Initialize(), OnCreatureCreate(), OnUnitDeath(), SetData(), and Update().
EggCount
uint8 instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript::EggCount protected
Referenced by Initialize(), and SetData().
EggEvent
uint32 instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript::EggEvent protected
Referenced by GetData(), Initialize(), OnUnitDeath(), SetData(), and Update().
EggList
GuidList instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript::EggList protected
Referenced by OnGameObjectCreate(), OnGameObjectRemove(), SetBossState(), and SetData().
guardList
GuidList instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript::guardList protected
Referenced by OnCreatureCreate(), and SetData().
nefarianDoorGUID
ObjectGuid instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript::nefarianDoorGUID protected
nefarianGUID
ObjectGuid instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript::nefarianGUID protected
Referenced by OnCreatureCreate(), and SetBossState().
NefarianLeftTunnel
uint32 instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript::NefarianLeftTunnel protected
Referenced by GetData(), Initialize(), ReadSaveDataMore(), SetData(), and WriteSaveDataMore().
NefarianRightTunnel
uint32 instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript::NefarianRightTunnel protected
Referenced by GetData(), Initialize(), ReadSaveDataMore(), SetData(), and WriteSaveDataMore().
razorgoreGUID
ObjectGuid instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript::razorgoreGUID protected
Referenced by GetGuidData(), OnCreatureCreate(), SetData(), and Update().
The documentation for this struct was generated from the following file:
azerothcore-wotlk/src/server/scripts/EasternKingdoms/BlackrockMountain/BlackwingLair/instance_blackwing_lair.cpp