AzerothCore Doxygen
AuraScript Class Reference
#include "SpellScript.h"
Classes
class AfterCheckProcHandler
class AuraDispelHandler
class AuraProcHandler
class CheckAreaTargetHandler
class CheckProcHandler
class EffectAbsorbHandler
class EffectApplyHandler
class EffectBase
class EffectCalcAmountHandler
class EffectCalcPeriodicHandler
class EffectCalcSpellModHandler
class EffectManaShieldHandler
class EffectPeriodicHandler
class EffectProcHandler
class EffectSplitHandler
class EffectUpdatePeriodicHandler
class ScriptStateStore
Public Member Functions
AuraScript ()
bool _Validate (SpellInfo const *entry) override
bool _Load (Aura *aura)
void _PrepareScriptCall (AuraScriptHookType hookType, AuraApplication const *aurApp=nullptr)
void _FinishScriptCall ()
bool _IsDefaultActionPrevented ()
void PreventDefaultAction ()
SpellInfo const * GetSpellInfo () const
uint32 GetId () const
ObjectGuid GetCasterGUID () const
Unit * GetCaster () const
WorldObject * GetOwner () const
Unit * GetUnitOwner () const
DynamicObject * GetDynobjOwner () const
void Remove (uint32 removeMode=0)
Aura * GetAura () const
AuraObjectType GetType () const
int32 GetDuration () const
void SetDuration (int32 duration, bool withMods=false)
void RefreshDuration ()
time_t GetApplyTime () const
int32 GetMaxDuration () const
void SetMaxDuration (int32 duration)
int32 CalcMaxDuration () const
bool IsExpired () const
bool IsPermanent () const
uint8 GetCharges () const
void SetCharges (uint8 charges)
uint8 CalcMaxCharges () const
bool ModCharges (int8 num, AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
bool DropCharge (AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
uint8 GetStackAmount () const
void SetStackAmount (uint8 num)
bool ModStackAmount (int32 num, AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
bool IsPassive () const
bool IsDeathPersistent () const
bool HasEffect (uint8 effIndex) const
AuraEffect * GetEffect (uint8 effIndex) const
bool HasEffectType (AuraType type) const
Unit * GetTarget () const
AuraApplication const * GetTargetApplication () const
Public Member Functions inherited from _SpellScript
_SpellScript ()
virtual ~_SpellScript ()
virtual void _Register ()
virtual void _Unload ()
virtual void _Init (std::string const *scriptname, uint32 spellId)
std::string const * _GetScriptName () const
virtual void Register ()=0
virtual bool Validate (SpellInfo const *)
virtual bool Load ()
virtual void Unload ()
Public Attributes
HookList< CheckAreaTargetHandler > DoCheckAreaTarget
HookList< AuraDispelHandler > OnDispel
HookList< AuraDispelHandler > AfterDispel
HookList< EffectApplyHandler > OnEffectApply
HookList< EffectApplyHandler > AfterEffectApply
HookList< EffectApplyHandler > OnEffectRemove
HookList< EffectApplyHandler > AfterEffectRemove
HookList< EffectPeriodicHandler > OnEffectPeriodic
HookList< EffectUpdatePeriodicHandler > OnEffectUpdatePeriodic
HookList< EffectCalcAmountHandler > DoEffectCalcAmount
HookList< EffectCalcPeriodicHandler > DoEffectCalcPeriodic
HookList< EffectCalcSpellModHandler > DoEffectCalcSpellMod
HookList< EffectAbsorbHandler > OnEffectAbsorb
HookList< EffectAbsorbHandler > AfterEffectAbsorb
HookList< EffectManaShieldHandler > OnEffectManaShield
HookList< EffectManaShieldHandler > AfterEffectManaShield
HookList< EffectSplitHandler > OnEffectSplit
HookList< CheckProcHandler > DoCheckProc
HookList< AfterCheckProcHandler > DoAfterCheckProc
HookList< AuraProcHandler > DoPrepareProc
HookList< AuraProcHandler > OnProc
HookList< AuraProcHandler > AfterProc
HookList< EffectProcHandler > OnEffectProc
HookList< EffectProcHandler > AfterEffectProc
Private Types
typedef std::stack< ScriptStateStore > ScriptStateStack
Private Attributes
Aura * m_aura
AuraApplication const * m_auraApplication
bool m_defaultActionPrevented
ScriptStateStack m_scriptStates
Additional Inherited Members
Static Public Member Functions inherited from _SpellScript
static bool ValidateSpellInfo (std::initializer_list< uint32 > spellIds)
template<class T >
static bool ValidateSpellInfo (T const &spellIds)
Protected Attributes inherited from _SpellScript
uint8 m_currentScriptState
std::string const * m_scriptName
uint32 m_scriptSpellId
Detailed Description
Member Typedef Documentation
ScriptStateStack
typedef std::stack<ScriptStateStore> AuraScript::ScriptStateStack private
Constructor & Destructor Documentation
AuraScript()
AuraScript::AuraScript () inline
                 : _SpellScript(), m_aura(nullptr), m_auraApplication(nullptr), m_defaultActionPrevented(false)
    {}
Member Function Documentation
_FinishScriptCall()
void AuraScript::_FinishScriptCall ()
{
    ScriptStateStore stateStore = m_scriptStates.top();
    m_currentScriptState = stateStore._currentScriptState;
    m_auraApplication = stateStore._auraApplication;
    m_defaultActionPrevented = stateStore._defaultActionPrevented;
    m_scriptStates.pop();
}
References AuraScript::ScriptStateStore::_auraApplication, AuraScript::ScriptStateStore::_currentScriptState, AuraScript::ScriptStateStore::_defaultActionPrevented, m_auraApplication, _SpellScript::m_currentScriptState, m_defaultActionPrevented, and m_scriptStates.
Referenced by _Load().
_IsDefaultActionPrevented()
bool AuraScript::_IsDefaultActionPrevented ()
{
    switch (m_currentScriptState)
    {
        case AURA_SCRIPT_HOOK_EFFECT_APPLY:
        case AURA_SCRIPT_HOOK_EFFECT_REMOVE:
        case AURA_SCRIPT_HOOK_EFFECT_PERIODIC:
        case AURA_SCRIPT_HOOK_EFFECT_ABSORB:
        case AURA_SCRIPT_HOOK_EFFECT_SPLIT:
        case AURA_SCRIPT_HOOK_PREPARE_PROC:
        case AURA_SCRIPT_HOOK_PROC:
        case AURA_SCRIPT_HOOK_EFFECT_PROC:
            return m_defaultActionPrevented;
        default:
            ASSERT(false && "AuraScript::_IsDefaultActionPrevented is called in a wrong place");
            return false;
    }
}
References ASSERT, AURA_SCRIPT_HOOK_EFFECT_ABSORB, AURA_SCRIPT_HOOK_EFFECT_APPLY, AURA_SCRIPT_HOOK_EFFECT_PERIODIC, AURA_SCRIPT_HOOK_EFFECT_PROC, AURA_SCRIPT_HOOK_EFFECT_REMOVE, AURA_SCRIPT_HOOK_EFFECT_SPLIT, AURA_SCRIPT_HOOK_PREPARE_PROC, AURA_SCRIPT_HOOK_PROC, _SpellScript::m_currentScriptState, and m_defaultActionPrevented.
_Load()
bool AuraScript::_Load (Aura * aura)
{
    m_aura = aura;
    _PrepareScriptCall((AuraScriptHookType)SPELL_SCRIPT_STATE_LOADING, nullptr);
    bool load = Load();
    _FinishScriptCall();
    return load;
}
References _FinishScriptCall(), _PrepareScriptCall(), _SpellScript::Load(), m_aura, and SPELL_SCRIPT_STATE_LOADING.
_PrepareScriptCall()
void AuraScript::_PrepareScriptCall (AuraScriptHookType hookType, AuraApplication const * aurApp = nullptr)
{
    m_scriptStates.push(ScriptStateStore(m_currentScriptState, m_auraApplication, m_defaultActionPrevented));
    m_currentScriptState = hookType;
    m_defaultActionPrevented = false;
    m_auraApplication = aurApp;
}
References m_auraApplication, _SpellScript::m_currentScriptState, m_defaultActionPrevented, and m_scriptStates.
Referenced by _Load().
_Validate()
bool AuraScript::_Validate (SpellInfo const * entry) override virtual
Reimplemented from _SpellScript.
{
    for (std::list<CheckAreaTargetHandler>::iterator itr = DoCheckAreaTarget.begin(); itr != DoCheckAreaTarget.end();  ++itr)
        if (!entry->HasAreaAuraEffect() && !entry->HasEffect(SPELL_EFFECT_PERSISTENT_AREA_AURA))
            LOG_ERROR("spells.scripts", "Spell `{}` of script `{}` does not have area aura effect - handler bound to hook `DoCheckAreaTarget` of AuraScript won't be executed", entry->Id, m_scriptName->c_str());
    for (std::list<AuraDispelHandler>::iterator itr = OnDispel.begin(); itr != OnDispel.end();  ++itr)
        if (!entry->HasEffect(SPELL_EFFECT_APPLY_AURA) && !entry->HasAreaAuraEffect())
            LOG_ERROR("spells.scripts", "Spell `{}` of script `{}` does not have apply aura effect - handler bound to hook `OnDispel` of AuraScript won't be executed", entry->Id, m_scriptName->c_str());
    for (std::list<AuraDispelHandler>::iterator itr = AfterDispel.begin(); itr != AfterDispel.end();  ++itr)
        if (!entry->HasEffect(SPELL_EFFECT_APPLY_AURA) && !entry->HasAreaAuraEffect())
            LOG_ERROR("spells.scripts", "Spell `{}` of script `{}` does not have apply aura effect - handler bound to hook `AfterDispel` of AuraScript won't be executed", entry->Id, m_scriptName->c_str());
    for (std::list<EffectApplyHandler>::iterator itr = OnEffectApply.begin(); itr != OnEffectApply.end();  ++itr)
        if (!(*itr).GetAffectedEffectsMask(entry))
            LOG_ERROR("spells.scripts", "Spell `{}` Effect `{}` of script `{}` did not match dbc effect data - handler bound to hook `OnEffectApply` of AuraScript won't be executed", entry->Id, (*itr).ToString(), m_scriptName->c_str());
    for (std::list<EffectApplyHandler>::iterator itr = OnEffectRemove.begin(); itr != OnEffectRemove.end();  ++itr)
        if (!(*itr).GetAffectedEffectsMask(entry))
            LOG_ERROR("spells.scripts", "Spell `{}` Effect `{}` of script `{}` did not match dbc effect data - handler bound to hook `OnEffectRemove` of AuraScript won't be executed", entry->Id, (*itr).ToString(), m_scriptName->c_str());
    for (std::list<EffectApplyHandler>::iterator itr = AfterEffectApply.begin(); itr != AfterEffectApply.end();  ++itr)
        if (!(*itr).GetAffectedEffectsMask(entry))
            LOG_ERROR("spells.scripts", "Spell `{}` Effect `{}` of script `{}` did not match dbc effect data - handler bound to hook `AfterEffectApply` of AuraScript won't be executed", entry->Id, (*itr).ToString(), m_scriptName->c_str());
    for (std::list<EffectApplyHandler>::iterator itr = AfterEffectRemove.begin(); itr != AfterEffectRemove.end();  ++itr)
        if (!(*itr).GetAffectedEffectsMask(entry))
            LOG_ERROR("spells.scripts", "Spell `{}` Effect `{}` of script `{}` did not match dbc effect data - handler bound to hook `AfterEffectRemove` of AuraScript won't be executed", entry->Id, (*itr).ToString(), m_scriptName->c_str());
    for (std::list<EffectPeriodicHandler>::iterator itr = OnEffectPeriodic.begin(); itr != OnEffectPeriodic.end();  ++itr)
        if (!(*itr).GetAffectedEffectsMask(entry))
            LOG_ERROR("spells.scripts", "Spell `{}` Effect `{}` of script `{}` did not match dbc effect data - handler bound to hook `OnEffectPeriodic` of AuraScript won't be executed", entry->Id, (*itr).ToString(), m_scriptName->c_str());
    for (std::list<EffectUpdatePeriodicHandler>::iterator itr = OnEffectUpdatePeriodic.begin(); itr != OnEffectUpdatePeriodic.end();  ++itr)
        if (!(*itr).GetAffectedEffectsMask(entry))
            LOG_ERROR("spells.scripts", "Spell `{}` Effect `{}` of script `{}` did not match dbc effect data - handler bound to hook `OnEffectUpdatePeriodic` of AuraScript won't be executed", entry->Id, (*itr).ToString(), m_scriptName->c_str());
    for (std::list<EffectCalcAmountHandler>::iterator itr = DoEffectCalcAmount.begin(); itr != DoEffectCalcAmount.end();  ++itr)
        if (!(*itr).GetAffectedEffectsMask(entry))
            LOG_ERROR("spells.scripts", "Spell `{}` Effect `{}` of script `{}` did not match dbc effect data - handler bound to hook `DoEffectCalcAmount` of AuraScript won't be executed", entry->Id, (*itr).ToString(), m_scriptName->c_str());
    for (std::list<EffectCalcPeriodicHandler>::iterator itr = DoEffectCalcPeriodic.begin(); itr != DoEffectCalcPeriodic.end();  ++itr)
        if (!(*itr).GetAffectedEffectsMask(entry))
            LOG_ERROR("spells.scripts", "Spell `{}` Effect `{}` of script `{}` did not match dbc effect data - handler bound to hook `DoEffectCalcPeriodic` of AuraScript won't be executed", entry->Id, (*itr).ToString(), m_scriptName->c_str());
    for (std::list<EffectCalcSpellModHandler>::iterator itr = DoEffectCalcSpellMod.begin(); itr != DoEffectCalcSpellMod.end();  ++itr)
        if (!(*itr).GetAffectedEffectsMask(entry))
            LOG_ERROR("spells.scripts", "Spell `{}` Effect `{}` of script `{}` did not match dbc effect data - handler bound to hook `DoEffectCalcSpellMod` of AuraScript won't be executed", entry->Id, (*itr).ToString(), m_scriptName->c_str());
    for (std::list<EffectAbsorbHandler>::iterator itr = OnEffectAbsorb.begin(); itr != OnEffectAbsorb.end();  ++itr)
        if (!(*itr).GetAffectedEffectsMask(entry))
            LOG_ERROR("spells.scripts", "Spell `{}` Effect `{}` of script `{}` did not match dbc effect data - handler bound to hook `OnEffectAbsorb` of AuraScript won't be executed", entry->Id, (*itr).ToString(), m_scriptName->c_str());
    for (std::list<EffectAbsorbHandler>::iterator itr = AfterEffectAbsorb.begin(); itr != AfterEffectAbsorb.end();  ++itr)
        if (!(*itr).GetAffectedEffectsMask(entry))
            LOG_ERROR("spells.scripts", "Spell `{}` Effect `{}` of script `{}` did not match dbc effect data - handler bound to hook `AfterEffectAbsorb` of AuraScript won't be executed", entry->Id, (*itr).ToString(), m_scriptName->c_str());
    for (std::list<EffectManaShieldHandler>::iterator itr = OnEffectManaShield.begin(); itr != OnEffectManaShield.end();  ++itr)
        if (!(*itr).GetAffectedEffectsMask(entry))
            LOG_ERROR("spells.scripts", "Spell `{}` Effect `{}` of script `{}` did not match dbc effect data - handler bound to hook `OnEffectManaShield` of AuraScript won't be executed", entry->Id, (*itr).ToString(), m_scriptName->c_str());
    for (std::list<EffectManaShieldHandler>::iterator itr = AfterEffectManaShield.begin(); itr != AfterEffectManaShield.end();  ++itr)
        if (!(*itr).GetAffectedEffectsMask(entry))
            LOG_ERROR("spells.scripts", "Spell `{}` Effect `{}` of script `{}` did not match dbc effect data - handler bound to hook `AfterEffectManaShield` of AuraScript won't be executed", entry->Id, (*itr).ToString(), m_scriptName->c_str());
    for (std::list<EffectSplitHandler>::iterator itr = OnEffectSplit.begin(); itr != OnEffectSplit.end();  ++itr)
        if (!(*itr).GetAffectedEffectsMask(entry))
            LOG_ERROR("spells.scripts", "Spell `{}` Effect `{}` of script `{}` did not match dbc effect data - handler bound to hook `OnEffectSplit` of AuraScript won't be executed", entry->Id, (*itr).ToString(), m_scriptName->c_str());
    for (std::list<CheckProcHandler>::iterator itr = DoCheckProc.begin(); itr != DoCheckProc.end(); ++itr)
        if (!entry->HasEffect(SPELL_EFFECT_APPLY_AURA) && !entry->HasAreaAuraEffect())
            LOG_ERROR("spells.scripts", "Spell `{}` of script `{}` does not have apply aura effect - handler bound to hook `DoCheckProc` of AuraScript won't be executed", entry->Id, m_scriptName->c_str());
    for (std::list<AfterCheckProcHandler>::iterator itr = DoAfterCheckProc.begin(); itr != DoAfterCheckProc.end(); ++itr)
        if (!entry->HasEffect(SPELL_EFFECT_APPLY_AURA) && !entry->HasAreaAuraEffect())
            LOG_ERROR("spells.scripts", "Spell `{}` of script `{}` does not have apply aura effect - handler bound to hook `DoAfterCheckProc` of AuraScript won't be executed", entry->Id, m_scriptName->c_str());
    for (std::list<AuraProcHandler>::iterator itr = DoPrepareProc.begin(); itr != DoPrepareProc.end(); ++itr)
        if (!entry->HasEffect(SPELL_EFFECT_APPLY_AURA) && !entry->HasAreaAuraEffect())
            LOG_ERROR("spells.scripts", "Spell `{}` of script `{}` does not have apply aura effect - handler bound to hook `DoPrepareProc` of AuraScript won't be executed", entry->Id, m_scriptName->c_str());
    for (std::list<AuraProcHandler>::iterator itr = OnProc.begin(); itr != OnProc.end(); ++itr)
        if (!entry->HasEffect(SPELL_EFFECT_APPLY_AURA) && !entry->HasAreaAuraEffect())
            LOG_ERROR("spells.scripts", "Spell `{}` of script `{}` does not have apply aura effect - handler bound to hook `OnProc` of AuraScript won't be executed", entry->Id, m_scriptName->c_str());
    for (std::list<AuraProcHandler>::iterator itr = AfterProc.begin(); itr != AfterProc.end(); ++itr)
        if (!entry->HasEffect(SPELL_EFFECT_APPLY_AURA) && !entry->HasAreaAuraEffect())
            LOG_ERROR("spells.scripts", "Spell `{}` of script `{}` does not have apply aura effect - handler bound to hook `AfterProc` of AuraScript won't be executed", entry->Id, m_scriptName->c_str());
    for (std::list<EffectProcHandler>::iterator itr = OnEffectProc.begin(); itr != OnEffectProc.end(); ++itr)
        if (!(*itr).GetAffectedEffectsMask(entry))
            LOG_ERROR("spells.scripts", "Spell `{}` Effect `{}` of script `{}` did not match dbc effect data - handler bound to hook `OnEffectProc` of AuraScript won't be executed", entry->Id, (*itr).ToString(), m_scriptName->c_str());
    for (std::list<EffectProcHandler>::iterator itr = AfterEffectProc.begin(); itr != AfterEffectProc.end(); ++itr)
        if (!(*itr).GetAffectedEffectsMask(entry))
            LOG_ERROR("spells.scripts", "Spell `{}` Effect `{}` of script `{}` did not match dbc effect data - handler bound to hook `AfterEffectProc` of AuraScript won't be executed", entry->Id, (*itr).ToString(), m_scriptName->c_str());
    return _SpellScript::_Validate(entry);
}
References _SpellScript::_Validate(), SpellInfo::HasAreaAuraEffect(), SpellInfo::HasEffect(), SpellInfo::Id, LOG_ERROR, _SpellScript::m_scriptName, SPELL_EFFECT_APPLY_AURA, and SPELL_EFFECT_PERSISTENT_AREA_AURA.
Referenced by ObjectMgr::ValidateSpellScripts().
CalcMaxCharges()
uint8 AuraScript::CalcMaxCharges () const
{
    return m_aura->CalcMaxCharges();
}
References Aura::CalcMaxCharges(), and m_aura.
CalcMaxDuration()
int32 AuraScript::CalcMaxDuration () const
{
    return m_aura->CalcMaxDuration();
}
References Aura::CalcMaxDuration(), and m_aura.
DropCharge()
bool AuraScript::DropCharge (AuraRemoveMode removeMode = AURA_REMOVE_BY_DEFAULT)
{
    return m_aura->DropCharge(removeMode);
}
References Aura::DropCharge(), and m_aura.
Referenced by spell_dk_bone_shield::HandleProc().
GetApplyTime()
time_t AuraScript::GetApplyTime () const
{
    return m_aura->GetApplyTime();
}
References Aura::GetApplyTime(), and m_aura.
Referenced by spell_midsummer_ribbon_pole::HandleEffectPeriodic().
GetAura()
Aura * AuraScript::GetAura () const
{
    return m_aura;
}
References m_aura.
Referenced by spell_dragonblight_corrosive_spit::AfterApply(), spell_reliquary_of_souls_aura_of_desire_aura::CalculateAmount(), spell_reliquary_of_souls_aura_of_anger_aura::CalculateAmount(), spell_teron_gorefiend_spirit_lance::CalculateAmount(), spell_festergut_blighted_spores_aura::ExtraEffect(), spell_valkyr_essence_aura::HandleAfterEffectAbsorb(), spell_muru_summon_blood_elves_periodic_aura::HandleApply(), spell_gen_baby_murloc_passive::HandleApply(), spell_valanar_kinetic_bomb_aura::HandleDummyTick(), spell_hydross_mark_of_hydross::HandleEffectApply(), spell_dru_idol_lifebloom::HandleEffectCalcSpellMod(), spell_optic_link_aura::HandleEffectPeriodic(), spell_shade_of_akama_shade_soul_channel::HandleEffectRemove(), spell_dk_chains_of_ice_aura::HandlePeriodic(), spell_warl_improved_demonic_tactics::HandlePeriodic(), spell_voa_overcharge_aura::HandlePeriodicDummy(), spell_item_shadowmourne::HandleProc(), spell_warl_seed_of_corruption_aura::HandleProc(), spell_warl_seed_of_corruption_generic_aura::HandleProc(), spell_igb_overheat_aura::Load(), spell_gen_animal_blood::OnApply(), spell_contagion_of_rot::OnApply(), spell_hadronox_summon_periodic_aura::OnApply(), spell_love_is_in_the_air_romantic_picnic::OnPeriodic(), spell_the_lich_king_lights_favor_aura::OnPeriodic(), spell_kalecgos_curse_of_boundless_agony_aura::OnPeriodic(), spell_illidan_demon_transform2_aura::OnPeriodic(), spell_halion_marks_aura::OnRemove(), spell_item_shifting_naaru_silver::OnRemove(), spell_direbrew_disarm::PeriodicTick(), spell_summon_ice_spear_delayer::PeriodicTick(), spell_dragonblight_corrosive_spit::PeriodicTick(), spell_gen_defend::RefreshVisualShields(), spell_reliquary_of_souls_aura_of_desire_aura::Update(), spell_reliquary_of_souls_aura_of_anger_aura::Update(), spell_teron_gorefiend_spirit_lance::Update(), and spell_black_temple_shadow_inferno_aura::Update().
GetCaster()
Unit * AuraScript::GetCaster () const
{
    return m_aura->GetCaster();
}
References Aura::GetCaster(), and m_aura.
Referenced by spell_yogg_saron_protective_gaze_aura::Absorb(), spell_dk_will_of_the_necropolis::Absorb(), spell_sindragosa_ice_tomb_trap_aura::AfterApply(), spell_gen_summon_elemental::AfterApply(), spell_mage_master_of_elements::AfterCheckProc(), spell_the_lich_king_necrotic_plague_jump_aura::AfterDispel(), spell_astromancer_wrath_of_the_astromancer::AfterRemove(), spell_gen_summon_elemental::AfterRemove(), spell_gen_consume::AfterRemove(), spell_gen_apply_aura_after_expiration::AfterRemove(), spell_sha_sentry_totem::AfterRemove(), spell_dru_lifebloom::AfterRemove(), spell_mage_living_bomb::AfterRemove(), spell_oculus_stop_time_aura::Apply(), spell_sha_earthbind_totem::Apply(), spell_warl_health_funnel::ApplyEffect(), spell_hallows_end_base_fire::CalcPeriodic(), spell_svala_ritual_strike_aura::CalculateAmount(), spell_dk_anti_magic_shell_self::CalculateAmount(), spell_dk_anti_magic_zone::CalculateAmount(), spell_dk_icebound_fortitude::CalculateAmount(), spell_dru_swift_flight_passive::CalculateAmount(), spell_gen_vehicle_scaling_aura::CalculateAmount(), spell_item_spell_reflectors::CalculateAmount(), spell_pal_hand_of_salvation::CalculateAmount(), spell_pri_lightwell_renew::CalculateAmount(), spell_dru_rip::CalculateAmount(), spell_mage_fire_frost_ward::CalculateAmount(), spell_mage_mana_shield::CalculateAmount(), spell_rog_rupture::CalculateAmount(), spell_warl_shadow_ward::CalculateAmount(), spell_dru_innervate::CalculateAmount(), spell_gen_gift_of_naaru::CalculateAmount(), spell_pal_sacred_shield_base::CalculateAmount(), spell_sha_earth_shield::CalculateAmount(), spell_warl_demonic_knowledge::CalculateAmount(), spell_warl_seed_of_corruption_aura::CalculateAmount(), spell_mage_ice_barrier_aura::CalculateAmount(), spell_pri_power_word_shield_aura::CalculateAmount(), spell_warr_rend::CalculateAmount(), spell_the_lich_king_lights_favor_aura::CalculateBonus(), spell_item_skull_of_impeding_doom::CalculateDamageAmount(), spell_item_skull_of_impeding_doom::CalculateManaLeechAmount(), spell_gen_area_aura_select_players_and_caster::CheckAreaTarget(), spell_mage_focus_magic::CheckProc(), spell_warr_vigilance::CheckProc(), spell_mage_fingers_of_frost_proc::CheckProc(), spell_warl_drain_soul::CheckProc(), spell_warl_seed_of_corruption_aura::Detonate(), spell_warl_seed_of_corruption_generic_aura::Detonate(), spell_warr_vigilance::HandleAfterApply(), spell_shield_of_bones_aura::HandleAfterEffectAbsorb(), spell_saronite_vapors_dummy_aura::HandleAfterEffectApply(), spell_hodir_storm_power_aura::HandleAfterEffectApply(), spell_hodir_toasty_fire_aura::HandleAfterEffectApply(), spell_hodir_starlight_aura::HandleAfterEffectApply(), spell_marli_transform::HandleApply(), spell_warr_vigilance::HandleApply(), spell_warl_glyph_of_felguard::HandleApply(), spell_warl_glyph_of_voidwalker::HandleApply(), spell_gen_on_tournament_mount::HandleApplyEffect(), spell_gen_tournament_pennant::HandleApplyEffect(), spell_pri_mind_control::HandleApplyEffect(), spell_pri_renew::HandleApplyEffect(), spell_warl_seduction::HandleAuraApply(), spell_pri_vampiric_touch::HandleDispel(), spell_sha_flame_shock::HandleDispel(), spell_hexlord_unstable_affliction::HandleDispel(), spell_faction_champion_warl_unstable_affliction_aura::HandleDispel(), spell_dru_lifebloom::HandleDispel(), spell_warl_unstable_affliction::HandleDispel(), spell_lich_king_vo_blocker::HandleEffectApply(), spell_scholomance_fixate_aura::HandleEffectApply(), spell_catch_the_wild_wolpertinger::HandleEffectApply(), spell_shade_of_akama_shade_soul_channel::HandleEffectApply(), spell_hydross_cleansing_field_aura::HandleEffectApply(), spell_arcatraz_soul_steal_aura::HandleEffectApply(), spell_pal_blessing_of_sanctuary::HandleEffectApply(), spell_q12851_going_bearback::HandleEffectApply(), spell_oculus_dream_funnel_aura::HandleEffectCalcAmount(), spell_toc25_mistress_kiss_aura::HandleEffectPeriodic(), spell_hor_gunship_cannon_fire_aura::HandleEffectPeriodic(), spell_pos_empowered_blizzard_aura::HandleEffectPeriodic(), spell_icc_yf_frozen_orb_aura::HandleEffectPeriodic(), spell_oculus_soar_aura::HandleEffectPeriodic(), spell_mark_of_the_faceless_periodic_aura::HandleEffectPeriodic(), spell_hodir_storm_cloud_aura::HandleEffectPeriodic(), spell_ignis_slag_pot_aura::HandleEffectPeriodic(), spell_mimiron_p3wx2_laser_barrage_aura::HandleEffectPeriodic(), spell_ulduar_arachnopod_damaged_aura::HandleEffectPeriodic(), spell_gen_haunted_aura::HandleEffectPeriodic(), spell_q2203_thaumaturgy_channel::HandleEffectPeriodic(), spell_sha_earthbind_totem::HandleEffectPeriodic(), spell_brewfest_main_ram_buff::HandleEffectPeriodic(), spell_gen_leeching_swarm_aura::HandleEffectPeriodic(), spell_valkyr_touch_aura::HandleEffectPeriodic(), spell_icc_yh_volley_aura::HandleEffectPeriodic(), spell_hodir_flash_freeze_aura::HandleEffectPeriodic(), spell_ignis_scorch_aura::HandleEffectPeriodic(), spell_mimiron_rapid_burst_aura::HandleEffectPeriodic(), spell_optic_link_aura::HandleEffectPeriodic(), spell_q12619_emblazon_runeblade::HandleEffectPeriodic(), spell_midnight_fixate::HandleEffectRemove(), spell_scholomance_fixate_aura::HandleEffectRemove(), spell_inoculate_nestlewood_owlkin::HandleEffectRemove(), spell_hadronox_leech_poison_aura::HandleEffectRemove(), spell_q11919_q11940_drake_hunt_aura::HandleEffectRemove(), spell_reliquary_of_souls_fixate_aura::HandleEffectRemove(), spell_reliquary_of_souls_spite_aura::HandleEffectRemove(), spell_teron_gorefiend_shadow_of_death::HandleEffectRemove(), spell_black_temple_wyvern_sting_aura::HandleEffectRemove(), spell_hydross_cleansing_field_aura::HandleEffectRemove(), spell_arcatraz_soul_steal_aura::HandleEffectRemove(), spell_burning_maul::HandleOnApply(), spell_oculus_evasive_charges_aura::HandleOnEffectApply(), spell_oculus_soar_aura::HandleOnEffectApply(), spell_oculus_drake_flag_aura::HandleOnEffectApply(), spell_oculus_rider_aura::HandleOnEffectApply(), spell_oculus_evasive_charges_aura::HandleOnEffectRemove(), spell_oculus_rider_aura::HandleOnEffectRemove(), spell_ticking_time_bomb_aura::HandleOnEffectRemove(), spell_gen_haunted_aura::HandleOnEffectRemove(), spell_burning_maul::HandleOnRemove(), spell_item_noblegarden_chocolate::HandlePeriodic(), spell_shadow_sickle_periodic_damage::HandlePeriodic(), spell_rancid_spore_cloud::HandlePeriodic(), spell_spore_cloud::HandlePeriodic(), spell_garr_separation_anxiety_aura::HandlePeriodic(), spell_majordomo_separation_anxiety_aura::HandlePeriodic(), spell_oculus_ride_ruby_emerald_amber_drake_que_aura::HandlePeriodic(), spell_dk_death_and_decay_aura::HandlePeriodic(), spell_dk_pet_scaling::HandlePeriodic(), spell_hun_generic_scaling::HandlePeriodic(), spell_hun_sniper_training::HandlePeriodic(), spell_mage_pet_scaling::HandlePeriodic(), spell_sha_feral_spirit_scaling::HandlePeriodic(), spell_warl_generic_scaling::HandlePeriodic(), spell_shadow_bolt_whirl::HandlePeriodic(), spell_krick_explosive_barrage_aura::HandlePeriodicTick(), spell_deathwhisper_mana_barrier_aura::HandlePeriodicTick(), spell_gen_consume::HandleProc(), spell_soul_deflection::HandleProc(), spell_item_shadows_fate::HandleProc(), spell_oculus_temporal_rift_aura::HandleProc(), spell_gen_proc_not_self::HandleProc(), spell_felmyst_fog_of_corruption_charm_aura::HandleRemove(), spell_marli_transform::HandleRemove(), spell_grobbulus_mutating_injection_aura::HandleRemove(), spell_scourge_disguise_instability::HandleRemove(), spell_warl_haunt_aura::HandleRemove(), spell_warl_glyph_of_felguard::HandleRemove(), spell_warl_glyph_of_voidwalker::HandleRemove(), spell_gen_on_tournament_mount::HandleRemoveEffect(), spell_pri_mind_control::HandleRemoveEffect(), spell_warl_drain_soul::HandleTick(), spell_alert_drums::HandleTriggerSpell(), spell_putricide_mutated_plague_aura::HandleTriggerSpell(), spell_shadowfang_keep_haunting_spirits_aura::HandleUpdatePeriodic(), spell_pri_lightwell_renew::HandleUpdateSpellclick(), spell_q11065_wrangle_some_aether_rays_aura::if(), spell_mc_play_dead_aura::Load(), spell_electrial_storm::Load(), spell_dk_anti_magic_shell_raid::Load(), spell_dk_anti_magic_shell_self::Load(), spell_dk_anti_magic_zone::Load(), spell_dk_icebound_fortitude::Load(), spell_dk_spell_deflection::Load(), spell_dk_will_of_the_necropolis::Load(), spell_dru_moonkin_form_passive::Load(), spell_dru_primal_tenacity::Load(), spell_dru_rip::Load(), spell_dru_savage_defense::Load(), spell_dru_swift_flight_passive::Load(), spell_gen_vehicle_scaling_aura::Load(), spell_gen_on_tournament_mount::Load(), spell_gen_tournament_pennant::Load(), spell_hun_aspect_of_the_beast::Load(), spell_pal_divine_sacrifice::Load(), spell_pal_hand_of_sacrifice_aura::Load(), spell_pri_renew::Load(), spell_q12937_relief_for_the_fallen::Load(), spell_rog_nerves_of_steel::Load(), spell_rog_rupture::Load(), spell_sha_astral_shift::Load(), spell_warl_curse_of_doom::Load(), spell_scholomance_boon_of_life_aura::OnApply(), spell_gen_crab_disguise::OnApply(), spell_the_lich_king_necrotic_plague_jump_aura::OnApply(), spell_four_horsemen_mark_aura::OnApply(), spell_aura_of_despair_aura::OnApply(), spell_hodir_storm_power_aura::OnApply(), spell_gen_clone_weapon_aura::OnApply(), spell_silithyst::OnApply(), spell_gen_steal_weapon::OnApply(), spell_hun_aspect_of_the_beast::OnApply(), spell_item_shifting_naaru_silver::OnApply(), spell_claw_rage_aura::OnPeriodic(), spell_love_is_in_the_air_romantic_picnic::OnPeriodic(), spell_the_lich_king_soul_reaper_aura::OnPeriodic(), spell_the_lich_king_lights_favor_aura::OnPeriodic(), spell_icc_dark_reckoning_aura::OnPeriodic(), spell_kologarn_stone_shout_aura::OnPeriodic(), spell_illidan_tear_of_azzinoth_summon_channel_aura::OnPeriodic(), spell_item_eye_of_grillok_aura::OnPeriodic(), spell_item_fel_mana_potion::OnPeriodic(), spell_deathwhisper_dark_reckoning::OnPeriodic(), spell_the_lich_king_soul_rip_aura::OnPeriodic(), spell_thorim_lightning_pillar_P2_aura::OnPeriodic(), spell_xt002_gravity_bomb_aura::OnPeriodic(), spell_q12779_an_end_to_all_things_devour_aura::OnRemove(), spell_temple_of_atal_hakkar_hex_of_jammal_an_aura::OnRemove(), spell_electrial_storm::OnRemove(), spell_threatening_gaze_aura::OnRemove(), spell_gen_crab_disguise::OnRemove(), spell_boss_salramm_steal_flesh_aura::OnRemove(), spell_huhuran_wyvern_sting::OnRemove(), spell_halion_meteor_strike_marker_aura::OnRemove(), spell_the_lich_king_necrotic_plague_aura::OnRemove(), spell_dragonblight_devour_ghoul_periodic::OnRemove(), spell_auchenai_possess::OnRemove(), spell_silithyst::OnRemove(), spell_gen_steal_weapon::OnRemove(), spell_hun_aspect_of_the_beast::OnRemove(), spell_item_instant_statue::OnRemove(), spell_item_bloodsail_admiral_hat::OnRemove(), spell_q12937_relief_for_the_fallen::OnRemove(), spell_hor_shared_suffering_aura::OnRemove(), spell_the_lich_king_necrotic_plague_jump_aura::OnRemove(), spell_xt002_gravity_bomb_aura::OnRemove(), spell_xt002_searing_light_spawn_life_spark_aura::OnRemove(), spell_warl_curse_of_doom::OnRemove(), spell_sindragosa_frost_beacon_aura::PeriodicTick(), spell_frostwarden_handler_focus_fire_aura::PeriodicTick(), spell_dreamwalker_summon_suppresser_aura::PeriodicTick(), spell_summon_ice_spear_delayer::PeriodicTick(), spell_ice_spear_control_aura::PeriodicTick(), spell_trollgore_corpse_explode_aura::PeriodicTick(), spell_summoning_rhyme_aura::PeriodicTick(), spell_pilgrims_bounty_food_aura::RecalculateHook(), spell_gen_defend::RefreshVisualShields(), spell_gen_defend::RemoveDummyFromDriver(), spell_warl_drain_soul::RemoveEffect(), spell_warl_shadowburn::RemoveEffect(), spell_pal_divine_sacrifice::Split(), and spell_item_brewfest_hops::Update().
GetCasterGUID()
ObjectGuid AuraScript::GetCasterGUID () const
{
    return m_aura->GetCasterGUID();
}
References Aura::GetCasterGUID(), and m_aura.
Referenced by spell_dru_feral_swiftness::AfterApply(), spell_dru_savage_roar_aura::AfterApply(), spell_the_lich_king_necrotic_plague_jump_aura::AfterDispel(), spell_dru_lifebloom::AfterRemove(), spell_gen_lifebloom::AfterRemove(), spell_dru_lifebloom::HandleDispel(), spell_hydross_mark_of_hydross::HandleEffectApply(), spell_pal_blessing_of_sanctuary::HandleEffectRemove(), spell_putricide_gaseous_bloat_aura::HandleExtraEffect(), spell_sha_earth_shield::HandleProc(), spell_warr_improved_spell_reflection_trigger_aura::HandleRemove(), spell_warl_haunt_aura::HandleRemove(), spell_putricide_mutated_plague_aura::HandleTriggerSpell(), spell_dru_rejuvenation_moonglade_2_set::OnApply(), spell_the_lich_king_vile_spirits_aura::OnPeriodic(), spell_the_lich_king_soul_rip_aura::OnPeriodic(), spell_gen_turkey_marker::OnPeriodic(), spell_halion_marks_aura::OnRemove(), spell_putricide_mutated_plague_aura::OnRemove(), spell_the_lich_king_necrotic_plague_aura::OnRemove(), spell_sindragosa_instability_aura::OnRemove(), spell_the_lich_king_necrotic_plague_jump_aura::OnRemove(), and spell_rog_savage_combat::Update().
GetCharges()
uint8 AuraScript::GetCharges () const
{
    return m_aura->GetCharges();
}
References Aura::GetCharges(), and m_aura.
Referenced by spell_mark_of_malice::HandleProc().
GetDuration()
int32 AuraScript::GetDuration () const
{
    return m_aura->GetDuration();
}
References Aura::GetDuration(), and m_aura.
Referenced by spell_q12243_fire_upon_the_waters_aura::HandleApplyEffect(), spell_pri_mind_control::HandleApplyEffect(), spell_item_noblegarden_chocolate::HandlePeriodic(), spell_item_shifting_naaru_silver::OnApply(), and spell_flamewreath_aura::OnRemove().
GetDynobjOwner()
DynamicObject * AuraScript::GetDynobjOwner () const
{
    return m_aura->GetDynobjOwner();
}
References Aura::GetDynobjOwner(), and m_aura.
GetEffect()
AuraEffect * AuraScript::GetEffect (uint8 effIndex) const
{
    return m_aura->GetEffect(effIndex);
}
References Aura::GetEffect(), and m_aura.
Referenced by spell_reliquary_of_souls_aura_of_desire_aura::CalculateAmount(), spell_reliquary_of_souls_aura_of_anger_aura::CalculateAmount(), spell_teron_gorefiend_spirit_lance::CalculateAmount(), spell_hun_improved_mend_pet::CheckProc(), spell_warl_seed_of_corruption_generic_aura::Detonate(), spell_pri_renew::HandleApplyEffect(), spell_pri_vampiric_touch::HandleDispel(), spell_hexlord_unstable_affliction::HandleDispel(), spell_faction_champion_warl_unstable_affliction_aura::HandleDispel(), spell_dru_lifebloom::HandleDispel(), spell_warl_unstable_affliction::HandleDispel(), spell_hallows_end_base_fire::HandleEffectApply(), spell_optic_link_aura::HandleEffectPeriodic(), spell_dk_chains_of_ice_aura::HandlePeriodic(), spell_dk_pet_scaling::HandlePeriodic(), spell_dk_army_of_the_dead_passive::HandlePeriodic(), spell_pet_hit_expertise_scalling::HandlePeriodic(), spell_pet_intellect_spirit_resilience_scaling::HandlePeriodic(), spell_pet_spellhit_expertise_spellpen_scaling::HandlePeriodic(), spell_hun_generic_scaling::HandlePeriodic(), spell_mage_pet_scaling::HandlePeriodic(), spell_sha_feral_spirit_scaling::HandlePeriodic(), spell_warl_demonic_knowledge::HandlePeriodic(), spell_warl_generic_scaling::HandlePeriodic(), spell_the_lich_king_lights_favor_aura::OnPeriodic(), spell_reliquary_of_souls_aura_of_desire_aura::Update(), spell_reliquary_of_souls_aura_of_anger_aura::Update(), and spell_teron_gorefiend_spirit_lance::Update().
GetId()
uint32 AuraScript::GetId () const
{
    return m_aura->GetId();
}
References Aura::GetId(), and m_aura.
Referenced by spell_dru_bear_form_passive::CalculateAmount(), spell_gen_vehicle_scaling_aura::CalculateAmount(), spell_hodir_storm_power_aura::HandleAfterEffectApply(), spell_gen_tournament_pennant::HandleApplyEffect(), spell_warl_demonic_circle_summon::HandleDummyTick(), spell_love_in_air_perfume_immune::HandleEffectApply(), spell_dk_anti_magic_shell_self::HandleEffectApply(), spell_pet_hit_expertise_scalling::HandleEffectApply(), spell_pet_intellect_spirit_resilience_scaling::HandleEffectApply(), spell_pet_spellhit_expertise_spellpen_scaling::HandleEffectApply(), spell_dru_idol_lifebloom::HandleEffectCalcSpellMod(), spell_pal_exorcism_and_holy_wrath_damage::HandleEffectCalcSpellMod(), spell_warl_improved_demonic_tactics::HandleEffectCalcSpellMod(), spell_warr_glyph_of_sunder_armor::HandleEffectCalcSpellMod(), spell_love_in_air_perfume_immune::HandleEffectRemove(), spell_dk_anti_magic_shell_self::HandleEffectRemove(), spell_dk_presence::HandleImprovedBloodPresence(), spell_dk_presence::HandleImprovedFrostPresence(), spell_dk_presence::HandleImprovedUnholyPresence(), spell_illidan_shadow_prison_aura::HandleOnEffectApply(), spell_oculus_rider_aura::HandleOnEffectRemove(), spell_illidan_shadow_prison_aura::HandleOnEffectRemove(), spell_hun_sniper_training::HandlePeriodic(), spell_item_enchanted_broom_periodic::HandlePeriodicTick(), spell_warl_demonic_circle_summon::HandleRemove(), spell_dreamwalker_decay_periodic_timer_aura::Load(), spell_ignis_slag_pot_aura::OnApply(), spell_love_is_in_the_air_romantic_picnic::OnPeriodic(), spell_ignis_slag_pot_aura::OnRemove(), spell_pilgrims_bounty_food_aura::RecalculateHook(), spell_gen_defend::RefreshVisualShields(), spell_gen_defend::RemoveDummyFromDriver(), and spell_gen_bg_preparation::Update().
GetMaxDuration()
int32 AuraScript::GetMaxDuration () const
{
    return m_aura->GetMaxDuration();
}
References Aura::GetMaxDuration(), and m_aura.
Referenced by spell_hodir_biting_cold_player_aura::HandleEffectPeriodic(), and spell_gen_turkey_marker::OnPeriodic().
GetOwner()
WorldObject * AuraScript::GetOwner () const
{
    return m_aura->GetOwner();
}
References Aura::GetOwner(), and m_aura.
Referenced by spell_gen_summon_elemental::AfterApply(), spell_gen_summon_elemental::AfterRemove(), spell_hun_animal_handler::CalculateAmount(), spell_dk_army_of_the_dead_passive::CalculateAPAmount(), spell_dru_treant_scaling::CalculateAPAmount(), spell_hun_generic_scaling::CalculateAPAmount(), spell_pri_shadowfiend_scaling::CalculateAPAmount(), spell_sha_feral_spirit_scaling::CalculateAPAmount(), spell_sha_fire_elemental_scaling::CalculateAPAmount(), spell_warl_generic_scaling::CalculateAPAmount(), spell_warl_infernal_scaling::CalculateAPAmount(), spell_dk_pet_scaling::CalculateHasteAmount(), spell_dk_army_of_the_dead_passive::CalculateHealthAmount(), spell_dru_treant_scaling::CalculateResistanceAmount(), spell_hun_generic_scaling::CalculateResistanceAmount(), spell_mage_pet_scaling::CalculateResistanceAmount(), spell_pri_shadowfiend_scaling::CalculateResistanceAmount(), spell_sha_feral_spirit_scaling::CalculateResistanceAmount(), spell_sha_fire_elemental_scaling::CalculateResistanceAmount(), spell_warl_generic_scaling::CalculateResistanceAmount(), spell_warl_infernal_scaling::CalculateResistanceAmount(), spell_dk_pet_scaling::CalculateSPAmount(), spell_dk_army_of_the_dead_passive::CalculateSPAmount(), spell_dru_treant_scaling::CalculateSPAmount(), spell_hun_generic_scaling::CalculateSPAmount(), spell_mage_pet_scaling::CalculateSPAmount(), spell_pri_shadowfiend_scaling::CalculateSPAmount(), spell_sha_feral_spirit_scaling::CalculateSPAmount(), spell_sha_fire_elemental_scaling::CalculateSPAmount(), spell_warl_generic_scaling::CalculateSPAmount(), spell_warl_infernal_scaling::CalculateSPAmount(), spell_dk_pet_scaling::CalculateStatAmount(), spell_dru_treant_scaling::CalculateStatAmount(), spell_hun_generic_scaling::CalculateStatAmount(), spell_mage_pet_scaling::CalculateStatAmount(), spell_pri_shadowfiend_scaling::CalculateStatAmount(), spell_sha_feral_spirit_scaling::CalculateStatAmount(), spell_sha_fire_elemental_scaling::CalculateStatAmount(), spell_warl_generic_scaling::CalculateStatAmount(), spell_warl_infernal_scaling::CalculateStatAmount(), spell_igb_rocket_pack_useable_aura::CheckAreaTarget(), spell_pri_vampiric_touch::CheckProc(), spell_valkyr_essence_aura::HandleAfterEffectAbsorb(), spell_reflective_shield_aura::HandleAfterEffectAbsorb(), spell_igb_rocket_pack_useable_aura::HandleApply(), spell_igb_on_gunship_deck_aura::HandleApply(), spell_item_party_time::HandleEffectApply(), spell_q11919_q11940_drake_hunt_aura::HandleEffectRemove(), spell_item_enchanted_broom_periodic::HandlePeriodicTick(), spell_pri_shadowfiend_death::HandleProc(), spell_igb_rocket_pack_useable_aura::HandleRemove(), spell_warr_improved_spell_reflection_trigger_aura::HandleRemove(), spell_igb_rocket_pack_useable_aura::Load(), spell_igb_on_gunship_deck_aura::Load(), spell_the_lich_king_harvest_soul_aura::Load(), spell_dreamwalker_nightmare_cloud_aura::Load(), spell_q11919_q11940_drake_hunt_aura::Load(), spell_gen_vehicle_scaling_aura::Load(), spell_eredar_twins_handle_touch_periodic::OnPeriodic(), spell_xt002_gravity_bomb_aura::OnPeriodic(), spell_xt002_gravity_bomb_aura::OnRemove(), spell_xt002_searing_light_spawn_life_spark_aura::OnRemove(), and spell_ulduar_stone_grip_aura::OnRemoveStun().
GetSpellInfo()
SpellInfo const * AuraScript::GetSpellInfo () const
{
    return m_aura->GetSpellInfo();
}
References Aura::GetSpellInfo(), and m_aura.
Referenced by spell_dk_will_of_the_necropolis::Absorb(), spell_dru_nurturing_instinct::AfterApply(), spell_astromancer_wrath_of_the_astromancer::AfterRemove(), spell_dru_nurturing_instinct::AfterRemove(), spell_dru_lifebloom::AfterRemove(), spell_gen_replenishment_aura::CalculateAmount(), spell_hun_cower::CalculateAmount(), spell_mage_fire_frost_ward::CalculateAmount(), spell_mage_mana_shield::CalculateAmount(), spell_warl_shadow_ward::CalculateAmount(), spell_gen_gift_of_naaru::CalculateAmount(), spell_pal_sacred_shield_base::CalculateAmount(), spell_sha_earth_shield::CalculateAmount(), spell_warl_improved_demonic_tactics::CalculateAmount(), spell_warl_seed_of_corruption_aura::CalculateAmount(), spell_mage_ice_barrier_aura::CalculateAmount(), spell_pri_power_word_shield_aura::CalculateAmount(), spell_warr_rend::CalculateAmount(), spell_warl_seed_of_corruption_aura::Detonate(), spell_warl_seed_of_corruption_generic_aura::Detonate(), spell_rotface_mutated_infection_aura::ExtraRemoveEffect(), spell_valkyr_essence_aura::HandleAfterEffectAbsorb(), spell_shield_of_bones_aura::HandleAfterEffectAbsorb(), spell_infected_worgen_bite_aura::HandleAfterEffectApply(), spell_igb_on_gunship_deck_aura::HandleApply(), spell_pri_renew::HandleApplyEffect(), spell_dru_lifebloom::HandleDispel(), spell_dk_improved_unholy_presence::HandleEffectApply(), spell_warr_glyph_of_sunder_armor::HandleEffectCalcSpellMod(), spell_rog_prey_on_the_weak::HandleEffectPeriodic(), spell_valkyr_touch_aura::HandleEffectPeriodic(), spell_q12619_emblazon_runeblade::HandleEffectPeriodic(), spell_reliquary_of_souls_fixate_aura::HandleEffectRemove(), spell_shade_of_akama_shade_soul_channel::HandleEffectRemove(), spell_black_temple_skeleton_shot_aura::HandleEffectRemove(), spell_dk_raise_ally_trigger::HandleEffectRemove(), spell_putricide_gaseous_bloat_aura::HandleExtraEffect(), spell_rancid_spore_cloud::HandlePeriodic(), spell_spore_cloud::HandlePeriodic(), spell_kiljaeden_shadow_spike_aura::HandlePeriodic(), spell_kiljaeden_armageddon_periodic_aura::HandlePeriodic(), spell_halion_twilight_cutter_periodic_aura::HandlePeriodic(), spell_oculus_ride_ruby_emerald_amber_drake_que_aura::HandlePeriodic(), spell_hun_sniper_training::HandlePeriodic(), spell_igb_periodic_trigger_with_power_cost_aura::HandlePeriodicTick(), spell_gen_consume::HandleProc(), spell_black_temple_consuming_strikes_aura::HandleProc(), spell_item_trauma::HandleProc(), spell_item_blood_draining_enchant::HandleProc(), spell_mage_ignite::HandleProc(), spell_dk_scent_of_blood::HandleProc(), spell_item_healing_trance::HandleProc(), spell_karazhan_temptation::HandleProc(), spell_dk_dancing_rune_weapon::HandleProc(), spell_item_unsated_craving::HandleProc(), spell_pal_sacred_shield_base::HandleProc(), spell_putricide_mutated_plague_aura::HandleTriggerSpell(), spell_hun_sniper_training::HandleUpdatePeriodic(), spell_gen_have_item_auras::if(), spell_dk_anti_magic_shell_raid::Load(), spell_dk_anti_magic_shell_self::Load(), spell_dk_anti_magic_zone::Load(), spell_dk_spell_deflection::Load(), spell_dk_will_of_the_necropolis::Load(), spell_dru_moonkin_form_passive::Load(), spell_dru_primal_tenacity::Load(), spell_dru_savage_defense::Load(), spell_gen_absorb0_hitlimit1::Load(), spell_item_brewfest_hops::Load(), spell_pal_ardent_defender::Load(), spell_pal_divine_sacrifice::Load(), spell_pri_guardian_spirit::Load(), spell_rog_cheat_death::Load(), spell_rog_nerves_of_steel::Load(), spell_sha_astral_shift::Load(), spell_gen_clone_weapon_aura::OnApply(), spell_gen_choking_vines::OnApply(), spell_valithria_suppression_aura::OnApply(), spell_gruul_ground_slam_trigger::OnApply(), spell_pilgrims_bounty_serve_generic::OnAuraRemove(), spell_anubisath_mortal_strike::OnPeriodic(), spell_kologarn_stone_shout_aura::OnPeriodic(), spell_item_fel_mana_potion::OnPeriodic(), spell_deathwhisper_dark_reckoning::OnPeriodic(), spell_the_lich_king_vile_spirits_aura::OnPeriodic(), spell_thorim_lightning_pillar_P2_aura::OnPeriodic(), spell_karathress_power_of_tidalvess::OnPeriodic(), spell_karathress_power_of_caribdis::OnPeriodic(), spell_leotheras_demon_link::OnPeriodic(), spell_lurker_below_spout::OnPeriodic(), spell_gen_periodic_knock_away::OnPeriodic(), spell_gen_proc_on_victim::OnProc(), spell_azgalor_doom_aura::OnRemove(), spell_putricide_mutated_plague_aura::OnRemove(), spell_valithria_suppression_aura::OnRemove(), spell_gen_clone_weapon_aura::OnRemove(), spell_xt002_gravity_bomb_aura::OnRemove(), spell_gen_sober_up::OnRemove(), spell_frostwarden_handler_focus_fire_aura::PeriodicTick(), spell_doomfire::PeriodicTick(), spell_broggok_poison_cloud::PeriodicTick(), spell_gen_defend::RefreshVisualShields(), spell_gen_defend::RemoveVisualShields(), spell_illidari_council_deadly_strike_aura::Update(), spell_mother_shahraz_beam_periodic_aura::Update(), spell_mother_shahraz_saber_lash_aura::Update(), spell_black_temple_charge_rage_aura::Update(), and spell_black_temple_spell_absorption_aura::Update().
GetStackAmount()
uint8 AuraScript::GetStackAmount () const
{
    return m_aura->GetStackAmount();
}
References Aura::GetStackAmount(), and m_aura.
Referenced by spell_charge_shield_bomber_aura::Absorb(), spell_the_lich_king_necrotic_plague_jump_aura::AfterDispel(), spell_dru_lifebloom::AfterRemove(), spell_braziers_hit::HandleAfterEffectApply(), spell_saronite_vapors_dummy_aura::HandleAfterEffectApply(), spell_infected_worgen_bite_aura::HandleAfterEffectApply(), spell_hodir_biting_cold_player_aura::HandleEffectPeriodic(), spell_sladran_grip_of_sladran_aura::HandlePeriodic(), spell_algalon_phase_punch_aura::HandlePeriodic(), spell_voa_overcharge_aura::HandlePeriodicDummy(), spell_item_blade_ward_enchant::HandleProc(), spell_item_blood_draining_enchant::HandleProc(), spell_gen_blade_warding::HandleProc(), spell_putricide_mutated_plague_aura::HandleTriggerSpell(), spell_the_lich_king_necrotic_plague_jump_aura::OnApply(), spell_four_horsemen_mark_aura::OnApply(), spell_gen_choking_vines::OnApply(), spell_gen_turkey_marker::OnPeriodic(), spell_halion_marks_aura::OnRemove(), spell_putricide_mutated_plague_aura::OnRemove(), spell_algalon_phase_punch_aura::OnRemove(), spell_the_lich_king_necrotic_plague_jump_aura::OnRemove(), spell_item_shadowmourne_soul_fragment::OnStackChange(), and spell_sindragosa_soul_preservation_aura::PeriodicTick().
GetTarget()
Unit * AuraScript::GetTarget () const
{
    switch (m_currentScriptState)
    {
        case AURA_SCRIPT_HOOK_EFFECT_APPLY:
        case AURA_SCRIPT_HOOK_EFFECT_REMOVE:
        case AURA_SCRIPT_HOOK_EFFECT_AFTER_APPLY:
        case AURA_SCRIPT_HOOK_EFFECT_AFTER_REMOVE:
        case AURA_SCRIPT_HOOK_EFFECT_PERIODIC:
        case AURA_SCRIPT_HOOK_EFFECT_ABSORB:
        case AURA_SCRIPT_HOOK_EFFECT_AFTER_ABSORB:
        case AURA_SCRIPT_HOOK_EFFECT_MANASHIELD:
        case AURA_SCRIPT_HOOK_EFFECT_AFTER_MANASHIELD:
        case AURA_SCRIPT_HOOK_EFFECT_SPLIT:
        case AURA_SCRIPT_HOOK_CHECK_PROC:
        case AURA_SCRIPT_HOOK_AFTER_CHECK_PROC:
        case AURA_SCRIPT_HOOK_PREPARE_PROC:
        case AURA_SCRIPT_HOOK_PROC:
        case AURA_SCRIPT_HOOK_AFTER_PROC:
        case AURA_SCRIPT_HOOK_EFFECT_PROC:
        case AURA_SCRIPT_HOOK_EFFECT_AFTER_PROC:
            return m_auraApplication->GetTarget();
        default:
            LOG_ERROR("spells.scripts", "Script: `{}` Spell: `{}` AuraScript::GetTarget called in a hook in which the call won't have effect!", m_scriptName->c_str(), m_scriptSpellId);
    }
    return nullptr;
}
References AURA_SCRIPT_HOOK_AFTER_CHECK_PROC, AURA_SCRIPT_HOOK_AFTER_PROC, AURA_SCRIPT_HOOK_CHECK_PROC, AURA_SCRIPT_HOOK_EFFECT_ABSORB, AURA_SCRIPT_HOOK_EFFECT_AFTER_ABSORB, AURA_SCRIPT_HOOK_EFFECT_AFTER_APPLY, AURA_SCRIPT_HOOK_EFFECT_AFTER_MANASHIELD, AURA_SCRIPT_HOOK_EFFECT_AFTER_PROC, AURA_SCRIPT_HOOK_EFFECT_AFTER_REMOVE, AURA_SCRIPT_HOOK_EFFECT_APPLY, AURA_SCRIPT_HOOK_EFFECT_MANASHIELD, AURA_SCRIPT_HOOK_EFFECT_PERIODIC, AURA_SCRIPT_HOOK_EFFECT_PROC, AURA_SCRIPT_HOOK_EFFECT_REMOVE, AURA_SCRIPT_HOOK_EFFECT_SPLIT, AURA_SCRIPT_HOOK_PREPARE_PROC, AURA_SCRIPT_HOOK_PROC, AuraApplication::GetTarget(), LOG_ERROR, m_auraApplication, _SpellScript::m_currentScriptState, _SpellScript::m_scriptName, and _SpellScript::m_scriptSpellId.
Referenced by spell_yogg_saron_protective_gaze_aura::Absorb(), spell_dk_anti_magic_shell_self::Absorb(), spell_dk_spell_deflection::Absorb(), spell_dk_will_of_the_necropolis::Absorb(), spell_dru_moonkin_form_passive::Absorb(), spell_dru_primal_tenacity::Absorb(), spell_pri_guardian_spirit::Absorb(), spell_rog_cheat_death::Absorb(), spell_rog_nerves_of_steel::Absorb(), spell_sha_astral_shift::Absorb(), spell_dru_savage_defense::Absorb(), spell_mage_fire_frost_ward::Absorb(), spell_pal_ardent_defender::Absorb(), spell_halion_combustion_consumption_aura::AddMarkStack(), spell_sindragosa_ice_tomb_trap_aura::AfterApply(), spell_commander_sarannis_arcane_devastation::AfterApply(), spell_dru_nurturing_instinct::AfterApply(), spell_dragonblight_corrosive_spit::AfterApply(), spell_dru_feral_swiftness::AfterApply(), spell_dru_savage_roar_aura::AfterApply(), spell_dru_survival_instincts_aura::AfterApply(), spell_the_lich_king_necrotic_plague_jump_aura::AfterDispel(), spell_dru_nurturing_instinct::AfterRemove(), spell_dru_feral_swiftness::AfterRemove(), spell_dru_savage_roar_aura::AfterRemove(), spell_dru_survival_instincts_aura::AfterRemove(), spell_gen_consume::AfterRemove(), spell_gen_apply_aura_after_expiration::AfterRemove(), spell_dru_lifebloom::AfterRemove(), spell_gen_lifebloom::AfterRemove(), spell_mage_living_bomb::AfterRemove(), spell_oculus_stop_time_aura::Apply(), spell_warl_health_funnel::ApplyEffect(), spell_dk_blood_gorged::CheckProc(), spell_pal_blessing_of_sanctuary::CheckProc(), spell_pri_mana_leech::CheckProc(), spell_rog_tricks_of_the_trade::CheckProc(), spell_sha_earth_shield::CheckProc(), spell_gargolmar_retalliation::CheckProc(), spell_gen_adaptive_warding::CheckProc(), spell_hun_misdirection::CheckProc(), spell_item_shadowmourne::CheckProc(), spell_warl_siphon_life::CheckProc(), spell_warl_fel_synergy::CheckProc(), spell_warr_retaliation::CheckProc(), spell_rotface_unstable_ooze_explosion_suicide_aura::DespawnSelf(), spell_warl_seed_of_corruption_aura::Detonate(), spell_warl_seed_of_corruption_generic_aura::Detonate(), spell_festergut_blighted_spores_aura::ExtraEffect(), spell_rotface_mutated_infection_aura::ExtraRemoveEffect(), spell_sindragosa_ice_tomb_trap_aura::ExtraRemoveEffect(), spell_geddon_inferno_aura::HandleAfterApply(), spell_geddon_armageddon_aura::HandleAfterApply(), spell_warr_vigilance::HandleAfterApply(), spell_braziers_hit::HandleAfterEffectApply(), spell_saronite_vapors_dummy_aura::HandleAfterEffectApply(), spell_hodir_storm_power_aura::HandleAfterEffectApply(), spell_hodir_toasty_fire_aura::HandleAfterEffectApply(), spell_hodir_starlight_aura::HandleAfterEffectApply(), spell_infected_worgen_bite_aura::HandleAfterEffectApply(), spell_torch_tossing_training::HandleAfterEffectRemove(), spell_geddon_inferno_aura::HandleAfterRemove(), spell_geddon_armageddon_aura::HandleAfterRemove(), spell_warlords_rage::HandleAfterRemove(), spell_capacitus_polarity_charge_aura::HandleAfterRemove(), spell_felmyst_fog_of_corruption_charm_aura::HandleApply(), spell_nullify::HandleApply(), spell_amanitar_remove_mushroom_power::HandleApply(), spell_igb_rocket_pack_useable_aura::HandleApply(), spell_igb_on_gunship_deck_aura::HandleApply(), spell_dru_enrage::HandleApply(), spell_pal_avenging_wrath::HandleApply(), spell_rog_killing_spree_aura::HandleApply(), spell_warr_vigilance::HandleApply(), spell_q12243_fire_upon_the_waters_aura::HandleApplyEffect(), spell_pri_mind_control::HandleApplyEffect(), spell_pri_renew::HandleApplyEffect(), spell_warl_eye_of_kilrogg::HandleAuraApply(), spell_warl_seduction::HandleAuraApply(), spell_warl_demonic_aegis::HandleAuraApply(), spell_warl_eye_of_kilrogg::HandleAuraRemove(), spell_magtheridon_shadow_grasp_visual::HandleDummyApply(), spell_magtheridon_shadow_grasp_visual::HandleDummyRemove(), spell_valanar_kinetic_bomb_aura::HandleDummyTick(), spell_item_rocket_chicken::HandleDummyTick(), spell_warl_demonic_circle_summon::HandleDummyTick(), spell_shadowfang_keep_haunting_spirits_aura::HandleDummyTick(), spell_blood_council_shadow_prison_aura::HandleDummyTick(), spell_mc_play_dead_aura::HandleEffectApply(), spell_lich_king_vo_blocker::HandleEffectApply(), spell_scholomance_fixate_aura::HandleEffectApply(), spell_kiljaeden_shield_of_the_blue::HandleEffectApply(), spell_catch_the_wild_wolpertinger::HandleEffectApply(), spell_hallows_end_candy_pirate_costume::HandleEffectApply(), spell_hallows_end_base_fire::HandleEffectApply(), spell_love_in_air_perfume_immune::HandleEffectApply(), spell_midsummer_ribbon_pole::HandleEffectApply(), spell_z_check_aura::HandleEffectApply(), spell_reliquary_of_souls_aura_of_suffering_aura::HandleEffectApply(), spell_shade_of_akama_shade_soul_channel::HandleEffectApply(), spell_hydross_cleansing_field_aura::HandleEffectApply(), spell_hydross_mark_of_hydross::HandleEffectApply(), spell_q10563_q10596_to_legion_hold_aura::HandleEffectApply(), spell_dk_master_of_ghouls::HandleEffectApply(), spell_dk_anti_magic_shell_self::HandleEffectApply(), spell_gen_visual_dummy_stun::HandleEffectApply(), spell_gen_feign_death_all_flags::HandleEffectApply(), spell_gen_feign_death_no_dyn_flag::HandleEffectApply(), spell_gen_feign_death_no_prevent_emotes::HandleEffectApply(), spell_gen_prevent_emotes::HandleEffectApply(), spell_pal_blessing_of_sanctuary::HandleEffectApply(), spell_q11065_wrangle_some_aether_rays_aura::HandleEffectApply(), spell_q11396_11399_force_shield_arcane_purple_x3::HandleEffectApply(), spell_q12851_going_bearback::HandleEffectApply(), spell_dk_improved_blood_presence::HandleEffectApply(), spell_dk_improved_frost_presence::HandleEffectApply(), spell_dk_improved_unholy_presence::HandleEffectApply(), spell_midsummer_ribbon_pole::HandleEffectPeriodic(), spell_mount_check_aura::HandleEffectPeriodic(), spell_pursuing_spikes_aura::HandleEffectPeriodic(), spell_toc25_mistress_kiss_aura::HandleEffectPeriodic(), spell_valkyr_ball_periodic_dummy_aura::HandleEffectPeriodic(), spell_icc_yf_frozen_orb_aura::HandleEffectPeriodic(), spell_mark_of_the_faceless_periodic_aura::HandleEffectPeriodic(), spell_hodir_biting_cold_player_aura::HandleEffectPeriodic(), spell_hodir_storm_cloud_aura::HandleEffectPeriodic(), spell_ignis_slag_pot_aura::HandleEffectPeriodic(), spell_yogg_saron_sanity_well_aura::HandleEffectPeriodic(), spell_destroy_door_seal_aura::HandleEffectPeriodic(), spell_z_check_aura::HandleEffectPeriodic(), spell_gen_parachute::HandleEffectPeriodic(), spell_gen_gryphon_wyvern_mount_check::HandleEffectPeriodic(), spell_gen_whisper_gulch_yogg_saron_whisper::HandleEffectPeriodic(), spell_q11010_q11102_q11023_aggro_burst::HandleEffectPeriodic(), spell_q12730_quenching_mist::HandleEffectPeriodic(), spell_rog_killing_spree_aura::HandleEffectPeriodic(), spell_rog_prey_on_the_weak::HandleEffectPeriodic(), spell_sha_earthbind_totem::HandleEffectPeriodic(), spell_gen_leeching_swarm_aura::HandleEffectPeriodic(), spell_pos_blight_aura::HandleEffectPeriodic(), spell_pos_glacial_strike_aura::HandleEffectPeriodic(), spell_icc_yh_volley_aura::HandleEffectPeriodic(), spell_hodir_biting_cold_main_aura::HandleEffectPeriodic(), spell_hodir_flash_freeze_aura::HandleEffectPeriodic(), spell_ulduar_energy_sap_aura::HandleEffectPeriodic(), spell_frost_tomb_aura::HandleEffectPeriodic(), spell_optic_link_aura::HandleEffectPeriodic(), spell_sha_item_t10_elemental_2p_bonus::HandleEffectProc(), spell_warr_retaliation::HandleEffectProc(), spell_mc_play_dead_aura::HandleEffectRemove(), spell_midnight_fixate::HandleEffectRemove(), spell_scholomance_fixate_aura::HandleEffectRemove(), spell_brewfest_main_ram_buff::HandleEffectRemove(), spell_brewfest_ram_fatigue::HandleEffectRemove(), spell_hallows_end_candy_pirate_costume::HandleEffectRemove(), spell_love_in_air_perfume_immune::HandleEffectRemove(), spell_inoculate_nestlewood_owlkin::HandleEffectRemove(), spell_illidan_parasitic_shadowfiend_aura::HandleEffectRemove(), spell_illidan_parasitic_shadowfiend_trigger_aura::HandleEffectRemove(), spell_reliquary_of_souls_aura_of_suffering_aura::HandleEffectRemove(), spell_reliquary_of_souls_fixate_aura::HandleEffectRemove(), spell_reliquary_of_souls_spite_aura::HandleEffectRemove(), spell_shade_of_akama_shade_soul_channel::HandleEffectRemove(), spell_teron_gorefiend_shadow_of_death::HandleEffectRemove(), spell_teron_gorefiend_spiritual_vengeance::HandleEffectRemove(), spell_black_temple_skeleton_shot_aura::HandleEffectRemove(), spell_black_temple_wyvern_sting_aura::HandleEffectRemove(), spell_hydross_cleansing_field_aura::HandleEffectRemove(), spell_hydross_cleansing_field_command::HandleEffectRemove(), spell_lady_vashj_magic_barrier::HandleEffectRemove(), spell_serpentshrine_cavern_serpentshrine_parasite::HandleEffectRemove(), spell_serpentshrine_cavern_serpentshrine_parasite_trigger_aura::HandleEffectRemove(), spell_q10190_battery_recharging_blaster_aura::HandleEffectRemove(), spell_q10563_q10596_to_legion_hold_aura::HandleEffectRemove(), spell_dk_master_of_ghouls::HandleEffectRemove(), spell_dk_anti_magic_shell_self::HandleEffectRemove(), spell_dk_improved_blood_presence::HandleEffectRemove(), spell_dk_improved_frost_presence::HandleEffectRemove(), spell_dk_improved_unholy_presence::HandleEffectRemove(), spell_dk_presence::HandleEffectRemove(), spell_gen_baby_murloc::HandleEffectRemove(), spell_gen_visual_dummy_stun::HandleEffectRemove(), spell_gen_feign_death_all_flags::HandleEffectRemove(), spell_gen_feign_death_no_dyn_flag::HandleEffectRemove(), spell_gen_feign_death_no_prevent_emotes::HandleEffectRemove(), spell_pal_blessing_of_sanctuary::HandleEffectRemove(), spell_q10525_vision_guide::HandleEffectRemove(), spell_q10769_dissension_amongst_the_ranks_aura::HandleEffectRemove(), spell_q11396_11399_force_shield_arcane_purple_x3::HandleEffectRemove(), spell_serpentshrine_cavern_infection::HandleEffectRemove(), spell_putricide_gaseous_bloat_aura::HandleExtraEffect(), spell_dk_presence::HandleImprovedBloodPresence(), spell_dk_presence::HandleImprovedFrostPresence(), spell_dk_presence::HandleImprovedUnholyPresence(), spell_hun_taming_the_beast::HandleOnEffectApply(), spell_illidan_shadow_prison_aura::HandleOnEffectApply(), spell_ticking_time_bomb_aura::HandleOnEffectRemove(), spell_warhead_fuse_aura::HandleOnEffectRemove(), spell_hun_taming_the_beast::HandleOnEffectRemove(), spell_illidan_shadow_prison_aura::HandleOnEffectRemove(), aura_class_call_wild_magic::HandlePeriodic(), aura_class_call_siphon_blessing::HandlePeriodic(), spell_igb_rocket_pack_aura::HandlePeriodic(), spell_algalon_phase_punch_aura::HandlePeriodic(), spell_algalon_collapse_aura::HandlePeriodic(), spell_algalon_remove_phase_aura::HandlePeriodic(), spell_close_rift_aura::HandlePeriodic(), spell_sha_totemic_mastery::HandlePeriodic(), spell_garr_separation_anxiety_aura::HandlePeriodic(), spell_majordomo_separation_anxiety_aura::HandlePeriodic(), spell_oculus_ride_ruby_emerald_amber_drake_que_aura::HandlePeriodic(), spell_dk_death_and_decay_aura::HandlePeriodic(), spell_hun_sniper_training::HandlePeriodic(), spell_shadow_bolt_whirl::HandlePeriodic(), spell_voa_overcharge_aura::HandlePeriodicDummy(), spell_wintergrasp_hide_small_elementals_aura::HandlePeriodicDummy(), spell_igb_periodic_trigger_with_power_cost_aura::HandlePeriodicTick(), spell_item_enchanted_broom_periodic::HandlePeriodicTick(), spell_bronjahm_soulstorm_channel_ooc_aura::HandlePeriodicTick(), spell_bronjahm_soulstorm_visual_aura::HandlePeriodicTick(), spell_wailing_souls_periodic_aura::HandlePeriodicTick(), spell_exploding_orb_auto_grow_aura::HandlePeriodicTick(), spell_item_direbrew_remote_aura::HandlePeriodicTick(), spell_oculus_evasive_maneuvers_aura::HandleProc(), spell_mark_of_malice::HandleProc(), spell_item_fate_rune_of_unsurpassed_vigor::HandleProc(), spell_pri_t4_4p_bonus::HandleProc(), spell_pri_shadowfiend_death::HandleProc(), spell_rog_tricks_of_the_trade::HandleProc(), spell_gyth_chromatic_protection::HandleProc(), spell_karazhan_wrath_titans_aura::HandleProc(), spell_soul_deflection::HandleProc(), spell_black_temple_consuming_strikes_aura::HandleProc(), spell_ahune_spanky_hands::HandleProc(), spell_utgarde_pinnacle_beast_mark::HandleProc(), spell_dk_scent_of_blood::HandleProc(), spell_dru_living_seed_proc::HandleProc(), spell_hun_ascpect_of_the_viper::HandleProc(), spell_hun_improved_mend_pet::HandleProc(), spell_hun_misdirection::HandleProc(), spell_item_healing_trance::HandleProc(), spell_item_aegis_of_preservation::HandleProc(), spell_item_desperate_defense::HandleProc(), spell_mage_focus_magic::HandleProc(), spell_pal_blessing_of_sanctuary::HandleProc(), spell_pri_item_greater_heal_refund::HandleProc(), spell_pri_mana_leech::HandleProc(), spell_sha_earth_shield::HandleProc(), spell_warr_vigilance::HandleProc(), spell_karazhan_temptation::HandleProc(), spell_the_lich_king_dark_hunger_aura::HandleProc(), spell_oculus_temporal_rift_aura::HandleProc(), spell_yogg_saron_grim_reprisal_aura::HandleProc(), spell_dk_blood_gorged::HandleProc(), spell_dru_t10_balance_4p_bonus::HandleProc(), spell_dru_living_seed::HandleProc(), spell_hun_glyph_of_arcane_shot::HandleProc(), spell_item_blessing_of_ancient_kings::HandleProc(), spell_item_necrotic_touch::HandleProc(), spell_item_shadowmourne::HandleProc(), spell_mage_burnout::HandleProc(), spell_mage_master_of_elements::HandleProc(), spell_pal_seal_of_righteousness::HandleProc(), spell_pri_divine_aegis::HandleProc(), spell_pri_glyph_of_prayer_of_healing::HandleProc(), spell_rog_blade_flurry::HandleProc(), spell_sha_t10_restoration_4p_bonus::HandleProc(), spell_sha_item_lightning_shield::HandleProc(), spell_sha_item_lightning_shield_trigger::HandleProc(), spell_sha_item_mana_surge::HandleProc(), spell_warl_glyph_of_shadowflame::HandleProc(), spell_warr_sweeping_strikes::HandleProc(), spell_warl_demonic_circle_summon::HandleRemove(), spell_vael_burning_adrenaline::HandleRemove(), spell_felmyst_fog_of_corruption_charm_aura::HandleRemove(), spell_trollgore_corpse_explode_aura::HandleRemove(), spell_igb_rocket_pack_useable_aura::HandleRemove(), spell_grobbulus_mutating_injection_aura::HandleRemove(), spell_dru_enrage::HandleRemove(), spell_pal_divine_intervention::HandleRemove(), spell_pal_avenging_wrath::HandleRemove(), spell_rog_killing_spree_aura::HandleRemove(), spell_rog_tricks_of_the_trade_proc::HandleRemove(), spell_warr_vigilance::HandleRemove(), spell_igb_rocket_pack_aura::HandleRemove(), spell_warl_haunt_aura::HandleRemove(), spell_q12243_fire_upon_the_waters_aura::HandleRemoveEffect(), spell_pri_mind_control::HandleRemoveEffect(), spell_kelthuzad_detonate_mana_aura::HandleScript(), spell_gen_paralytic_poison::HandleStun(), spell_warl_demonic_circle_teleport::HandleTeleport(), spell_warl_drain_soul::HandleTick(), spell_putricide_grow_stacker_aura::HandleTriggerSpell(), spell_ioc_parachute_ic_aura::HandleTriggerSpell(), spell_magic_eater_food::HandleTriggerSpell(), spell_q11010_q11102_q11023_aggro_check_aura::HandleTriggerSpell(), spell_putricide_mutated_plague_aura::HandleTriggerSpell(), spell_pri_lightwell_renew::HandleUpdateSpellclick(), spell_scholomance_boon_of_life_aura::OnApply(), spell_brewfest_reveler_transform::OnApply(), spell_direbrew_disarm::OnApply(), spell_love_is_in_the_air_romantic_picnic::OnApply(), spell_gen_aura_service_uniform::OnApply(), spell_bonfires_blessing::OnApply(), spell_halion_combustion_consumption_aura::OnApply(), spell_halion_twilight_phasing_aura::OnApply(), spell_halion_twilight_realm_aura::OnApply(), spell_halion_leave_twilight_realm_aura::OnApply(), spell_blood_queen_frenzied_bloodthirst_aura::OnApply(), spell_icc_stoneform_aura::OnApply(), spell_four_horsemen_mark_aura::OnApply(), spell_aura_of_despair_aura::OnApply(), spell_ignis_slag_pot_aura::OnApply(), spell_yogg_saron_shadow_beacon_aura::OnApply(), spell_dru_rejuvenation_moonglade_2_set::OnApply(), spell_gen_clone_weapon_aura::OnApply(), spell_gen_damage_reduction_aura::OnApply(), spell_gen_choking_vines::OnApply(), spell_gen_steal_weapon::OnApply(), spell_item_shifting_naaru_silver::OnApply(), spell_item_multiphase_goggles::OnApply(), spell_q12987_read_pronouncement::OnApply(), spell_valithria_suppression_aura::OnApply(), spell_hun_ascpect_of_the_viper::OnApply(), spell_hun_viper_attack_speed::OnApply(), spell_item_with_mount_speed::OnApply(), spell_pilgrims_bounty_serve_generic::OnAuraRemove(), spell_apothecary_perfume_spill::OnPeriodic(), spell_apothecary_cologne_spill::OnPeriodic(), spell_love_is_in_the_air_romantic_picnic::OnPeriodic(), spell_dred_grievious_bite_aura::OnPeriodic(), spell_the_lich_king_soul_reaper_aura::OnPeriodic(), spell_icc_dark_reckoning_aura::OnPeriodic(), spell_illidan_tear_of_azzinoth_summon_channel_aura::OnPeriodic(), spell_illidan_cage_trap_stun_aura::OnPeriodic(), spell_black_temple_dementia_aura::OnPeriodic(), spell_npc22275_crystal_prison_aura::OnPeriodic(), spell_gen_curse_of_pain::OnPeriodic(), spell_item_eye_of_grillok_aura::OnPeriodic(), spell_kalecgos_curse_of_boundless_agony_aura::OnPeriodic(), spell_mark_of_kazrogal_aura::OnPeriodic(), spell_deathwhisper_dark_reckoning::OnPeriodic(), spell_the_lich_king_vile_spirits_aura::OnPeriodic(), spell_the_lich_king_soul_rip_aura::OnPeriodic(), spell_web_wrap_damage::OnPeriodic(), spell_assembly_rune_of_summoning_aura::OnPeriodic(), spell_mark_of_kazzak_aura::OnPeriodic(), spell_gen_turkey_marker::OnPeriodic(), spell_blood_queen_essence_of_the_blood_queen_aura::OnProc(), spell_pal_eye_for_an_eye::OnProc(), spell_warl_siphon_life::OnProc(), spell_warl_fel_synergy::OnProc(), spell_warr_damage_shield::OnProc(), spell_flamewreath_aura::OnRemove(), spell_q12779_an_end_to_all_things_devour_aura::OnRemove(), spell_scholomance_boon_of_life_aura::OnRemove(), spell_temple_of_atal_hakkar_hex_of_jammal_an_aura::OnRemove(), spell_blood_siphon_aura::OnRemove(), spell_threatening_gaze_aura::OnRemove(), spell_gen_aura_service_uniform::OnRemove(), spell_azgalor_doom_aura::OnRemove(), spell_azjol_nerub_web_wrap_aura::OnRemove(), spell_halion_combustion_consumption_aura::OnRemove(), spell_halion_marks_aura::OnRemove(), spell_halion_twilight_phasing_aura::OnRemove(), spell_halion_leave_twilight_realm_aura::OnRemove(), spell_blood_queen_frenzied_bloodthirst_aura::OnRemove(), spell_putricide_mutated_plague_aura::OnRemove(), spell_putricide_mutation_init_aura::OnRemove(), spell_putricide_mutated_transformation_dismiss_aura::OnRemove(), spell_the_lich_king_necrotic_plague_aura::OnRemove(), spell_the_lich_king_shadow_trap_visual_aura::OnRemove(), spell_the_lich_king_harvest_soul_aura::OnRemove(), spell_valithria_suppression_aura::OnRemove(), spell_icc_stoneform_aura::OnRemove(), spell_icc_web_wrap_aura::OnRemove(), spell_ioc_repair_turret_aura::OnRemove(), spell_ionar_static_overload::OnRemove(), spell_algalon_phase_punch_aura::OnRemove(), spell_assembly_rune_of_summoning_aura::OnRemove(), spell_aura_of_despair_aura::OnRemove(), spell_ignis_slag_pot_aura::OnRemove(), spell_yogg_saron_shadow_beacon_aura::OnRemove(), spell_auchenai_possess::OnRemove(), spell_dru_rejuvenation_moonglade_2_set::OnRemove(), spell_gen_clone_weapon_aura::OnRemove(), spell_gen_damage_reduction_aura::OnRemove(), spell_gen_prevent_emotes::OnRemove(), spell_hun_ascpect_of_the_viper::OnRemove(), spell_hun_misdirection::OnRemove(), spell_hun_misdirection_proc::OnRemove(), spell_hun_viper_attack_speed::OnRemove(), spell_item_with_mount_speed::OnRemove(), spell_item_shifting_naaru_silver::OnRemove(), spell_item_desperate_defense::OnRemove(), spell_item_shadowmourne::OnRemove(), spell_item_shadowmourne_soul_fragment::OnRemove(), spell_item_multiphase_goggles::OnRemove(), spell_mage_glyph_of_eternal_water::OnRemove(), spell_mage_combustion_proc::OnRemove(), spell_rog_tricks_of_the_trade::OnRemove(), spell_hor_shared_suffering_aura::OnRemove(), spell_sindragosa_instability_aura::OnRemove(), spell_the_lich_king_necrotic_plague_jump_aura::OnRemove(), spell_gen_sober_up::OnRemove(), spell_warl_curse_of_doom::OnRemove(), spell_item_shadowmourne_soul_fragment::OnStackChange(), spell_send_mug_control_aura::PeriodicTick(), spell_barreled_control_aura::PeriodicTick(), spell_direbrew_disarm::PeriodicTick(), spell_sindragosa_frost_beacon_aura::PeriodicTick(), spell_sindragosa_soul_preservation_aura::PeriodicTick(), spell_frostwarden_handler_focus_fire_aura::PeriodicTick(), spell_summon_ice_spear_delayer::PeriodicTick(), spell_entropius_negative_energy_periodic::PeriodicTick(), spell_doomfire::PeriodicTick(), spell_trollgore_corpse_explode_aura::PeriodicTick(), spell_blood_queen_pact_of_the_darkfallen_dmg_aura::PeriodicTick(), spell_dragonblight_corrosive_spit::PeriodicTick(), spell_summoning_rhyme_aura::PeriodicTick(), spell_broggok_poison_cloud::PeriodicTick(), spell_brewfest_ram_fatigue::PrepareAuraScript(), spell_control_piece::PrepareAuraScript(), spell_dru_enrage::RecalculateBaseArmor(), spell_illidari_council_reflective_shield_aura::ReflectDamage(), spell_pri_power_word_shield_aura::ReflectDamage(), spell_gen_defend::RefreshVisualShields(), spell_warl_health_funnel::RemoveEffect(), spell_warl_drain_soul::RemoveEffect(), spell_warl_shadowburn::RemoveEffect(), spell_gen_defend::RemoveVisualShields(), spell_pal_hand_of_sacrifice_aura::Split(), spell_dk_anti_magic_shell_self::Trigger(), spell_mage_incanters_absorbtion_base_AuraScript::Trigger(), spell_koralon_meteor_fists_aura::TriggerFists(), spell_flame_warder_meteor_fists_aura::TriggerFists(), and spell_dru_predatory_strikes::UpdateAmount().
GetTargetApplication()
AuraApplication const * AuraScript::GetTargetApplication () const
{
    return m_auraApplication;
}
References m_auraApplication.
Referenced by spell_astromancer_wrath_of_the_astromancer::AfterRemove(), spell_gen_consume::AfterRemove(), spell_gen_apply_aura_after_expiration::AfterRemove(), spell_dru_lifebloom::AfterRemove(), spell_gen_lifebloom::AfterRemove(), spell_mage_living_bomb::AfterRemove(), spell_warlords_rage::HandleAfterRemove(), spell_capacitus_polarity_charge_aura::HandleAfterRemove(), spell_inoculate_nestlewood_owlkin::HandleEffectRemove(), spell_hadronox_leech_poison_aura::HandleEffectRemove(), spell_q11919_q11940_drake_hunt_aura::HandleEffectRemove(), spell_black_temple_skeleton_shot_aura::HandleEffectRemove(), spell_leotheras_insidious_whisper_aura::HandleEffectRemove(), spell_q10190_battery_recharging_blaster_aura::HandleEffectRemove(), spell_q10930_big_bone_worm_aura::HandleEffectRemove(), spell_q10929_fumping_aura::HandleEffectRemove(), spell_serpentshrine_cavern_infection::HandleEffectRemove(), spell_kiljaeden_darkness_aura::HandleRemove(), spell_grobbulus_mutating_injection_aura::HandleRemove(), spell_gen_paralytic_poison::HandleStun(), spell_flamewreath_aura::OnRemove(), spell_q12779_an_end_to_all_things_devour_aura::OnRemove(), spell_scholomance_boon_of_life_aura::OnRemove(), spell_electrial_storm::OnRemove(), spell_threatening_gaze_aura::OnRemove(), spell_azgalor_doom_aura::OnRemove(), spell_huhuran_wyvern_sting::OnRemove(), spell_halion_marks_aura::OnRemove(), spell_blood_queen_frenzied_bloodthirst_aura::OnRemove(), spell_the_lich_king_necrotic_plague_aura::OnRemove(), spell_the_lich_king_shadow_trap_visual_aura::OnRemove(), spell_the_lich_king_harvest_soul_aura::OnRemove(), spell_ioc_repair_turret_aura::OnRemove(), spell_ionar_static_overload::OnRemove(), spell_dragonblight_flame_fury::OnRemove(), spell_dragonblight_devour_ghoul_periodic::OnRemove(), spell_auchenai_possess::OnRemove(), spell_hun_misdirection::OnRemove(), spell_rog_tricks_of_the_trade::OnRemove(), spell_hor_shared_suffering_aura::OnRemove(), spell_sindragosa_instability_aura::OnRemove(), spell_the_lich_king_necrotic_plague_jump_aura::OnRemove(), spell_shield_of_runes_aura::OnRemove(), spell_warl_seed_of_corruption_aura::OnRemove(), spell_warl_curse_of_doom::OnRemove(), spell_warl_drain_soul::RemoveEffect(), and spell_warl_shadowburn::RemoveEffect().
GetType()
AuraObjectType AuraScript::GetType () const
{
    return m_aura->GetType();
}
References Aura::GetType(), and m_aura.
Referenced by spell_igb_overheat_aura::Load().
GetUnitOwner()
Unit * AuraScript::GetUnitOwner () const
{
    return m_aura->GetUnitOwner();
}
References Aura::GetUnitOwner(), and m_aura.
Referenced by spell_dru_barkskin::AfterApply(), spell_q13003_thursting_hodirs_spear_aura::AfterRemove(), spell_astromancer_wrath_of_the_astromancer::AfterRemove(), spell_dru_barkskin::AfterRemove(), spell_halion_marks_aura::BeforeDispel(), spell_serpentshrine_cavern_coilfang_water::CalcPeriodic(), spell_dk_pet_scaling::CalcPeriodic(), spell_dk_army_of_the_dead_passive::CalcPeriodic(), spell_pet_hit_expertise_scalling::CalcPeriodic(), spell_pet_intellect_spirit_resilience_scaling::CalcPeriodic(), spell_pet_spellhit_expertise_spellpen_scaling::CalcPeriodic(), spell_mage_pet_scaling::CalcPeriodic(), spell_mark_of_kazzak_aura::CalculateAmount(), spell_dk_vampiric_blood::CalculateAmount(), spell_dru_bear_form_passive::CalculateAmount(), spell_dru_brambles_treant::CalculateAmount(), spell_dru_dash_aura::CalculateAmount(), spell_dru_owlkin_frenzy::CalculateAmount(), spell_gen_reduced_above_60_aura::CalculateAmount(), spell_gen_disabled_above_63::CalculateAmount(), spell_gen_replenishment_aura::CalculateAmount(), spell_hun_cower::CalculateAmount(), spell_hun_animal_handler::CalculateAmount(), spell_item_arcane_shroud::CalculateAmount(), spell_item_the_eye_of_diminution::CalculateAmount(), spell_pal_hand_of_salvation::CalculateAmount(), spell_gen_lifeblood::CalculateAmount(), spell_sha_earth_shield::CalculateAmount(), spell_warl_improved_demonic_tactics::CalculateAmount(), spell_warl_seed_of_corruption_aura::CalculateAmount(), spell_warr_rend::CalculateAmount(), spell_dk_army_of_the_dead_passive::CalculateAPAmount(), spell_dru_treant_scaling::CalculateAPAmount(), spell_hun_generic_scaling::CalculateAPAmount(), spell_pri_shadowfiend_scaling::CalculateAPAmount(), spell_sha_feral_spirit_scaling::CalculateAPAmount(), spell_sha_fire_elemental_scaling::CalculateAPAmount(), spell_warl_generic_scaling::CalculateAPAmount(), spell_warl_infernal_scaling::CalculateAPAmount(), spell_pet_hit_expertise_scalling::CalculateExpertiseAmount(), spell_pet_spellhit_expertise_spellpen_scaling::CalculateExpertiseAmount(), spell_dk_pet_scaling::CalculateHasteAmount(), spell_dk_army_of_the_dead_passive::CalculateHealthAmount(), spell_pet_hit_expertise_scalling::CalculateHitAmount(), spell_dru_treant_scaling::CalculateResistanceAmount(), spell_hun_generic_scaling::CalculateResistanceAmount(), spell_mage_pet_scaling::CalculateResistanceAmount(), spell_pri_shadowfiend_scaling::CalculateResistanceAmount(), spell_sha_feral_spirit_scaling::CalculateResistanceAmount(), spell_sha_fire_elemental_scaling::CalculateResistanceAmount(), spell_warl_generic_scaling::CalculateResistanceAmount(), spell_warl_infernal_scaling::CalculateResistanceAmount(), spell_dk_pet_scaling::CalculateSPAmount(), spell_dk_army_of_the_dead_passive::CalculateSPAmount(), spell_dru_treant_scaling::CalculateSPAmount(), spell_hun_generic_scaling::CalculateSPAmount(), spell_mage_pet_scaling::CalculateSPAmount(), spell_pri_shadowfiend_scaling::CalculateSPAmount(), spell_sha_feral_spirit_scaling::CalculateSPAmount(), spell_sha_fire_elemental_scaling::CalculateSPAmount(), spell_warl_generic_scaling::CalculateSPAmount(), spell_warl_infernal_scaling::CalculateSPAmount(), spell_pet_hit_expertise_scalling::CalculateSpellHitAmount(), spell_pet_spellhit_expertise_spellpen_scaling::CalculateSpellHitAmount(), spell_pet_spellhit_expertise_spellpen_scaling::CalculateSpellPenAmount(), spell_pet_intellect_spirit_resilience_scaling::CalculateSpiritAmount(), spell_dk_pet_scaling::CalculateStatAmount(), spell_dru_treant_scaling::CalculateStatAmount(), spell_hun_generic_scaling::CalculateStatAmount(), spell_mage_pet_scaling::CalculateStatAmount(), spell_pri_shadowfiend_scaling::CalculateStatAmount(), spell_sha_feral_spirit_scaling::CalculateStatAmount(), spell_sha_fire_elemental_scaling::CalculateStatAmount(), spell_warl_generic_scaling::CalculateStatAmount(), spell_warl_infernal_scaling::CalculateStatAmount(), spell_dru_brambles_treant::CheckProc(), spell_botanica_shift_form_aura::CheckProc(), spell_kiljaeden_vengeance_of_the_blue_flight_aura::HandleApply(), spell_boss_magus_telestra_summon_telestra_clones_aura::HandleApply(), spell_pri_vampiric_touch::HandleDispel(), spell_dru_lifebloom::HandleDispel(), spell_magtheridon_shadow_grasp::HandleDummyApply(), spell_magtheridon_shadow_grasp::HandleDummyRemove(), spell_shadowfang_keep_forsaken_skills_aura::HandleDummyTick(), spell_uldaman_stoned_aura::HandleEffectApply(), spell_novos_crystal_handler_death_aura::HandleEffectApply(), spell_tharon_ja_dummy_aura::HandleEffectApply(), spell_teron_gorefiend_shadowy_construct::HandleEffectApply(), spell_black_template_harpooners_mark_aura::HandleEffectApply(), spell_leotheras_insidious_whisper_aura::HandleEffectApply(), spell_serpentshrine_cavern_coilfang_water::HandleEffectApply(), spell_botanica_call_of_the_falcon_aura::HandleEffectApply(), spell_dk_dancing_rune_weapon_visual::HandleEffectApply(), spell_dk_army_of_the_dead_passive::HandleEffectApply(), spell_gen_model_visible::HandleEffectApply(), spell_dk_pet_scaling::HandleEffectApply(), spell_dru_treant_scaling::HandleEffectApply(), spell_pet_hit_expertise_scalling::HandleEffectApply(), spell_pet_intellect_spirit_resilience_scaling::HandleEffectApply(), spell_pet_spellhit_expertise_spellpen_scaling::HandleEffectApply(), spell_mage_pet_scaling::HandleEffectApply(), spell_pri_shadowfiend_scaling::HandleEffectApply(), spell_sha_feral_spirit_scaling::HandleEffectApply(), spell_sha_fire_elemental_scaling::HandleEffectApply(), spell_warl_infernal_scaling::HandleEffectApply(), spell_hallows_end_base_fire::HandleEffectPeriodicUpdate(), spell_uldaman_stoned_aura::HandleEffectRemove(), spell_tharon_ja_dummy_aura::HandleEffectRemove(), spell_dtk_raise_dead_aura::HandleEffectRemove(), spell_black_template_harpooners_mark_aura::HandleEffectRemove(), spell_leotheras_insidious_whisper_aura::HandleEffectRemove(), spell_lurker_below_spout::HandleEffectRemove(), spell_serpentshrine_cavern_coilfang_water::HandleEffectRemove(), spell_botanica_call_of_the_falcon_aura::HandleEffectRemove(), spell_q10930_big_bone_worm_aura::HandleEffectRemove(), spell_q10929_fumping_aura::HandleEffectRemove(), spell_dk_raise_ally_trigger::HandleEffectRemove(), spell_gen_model_visible::HandleEffectRemove(), spell_yogg_saron_brain_link_aura::HandleOnEffectApply(), spell_hadronox_summon_periodic_aura::HandlePeriodic(), spell_halion_meteor_strike_spread_aura::HandlePeriodic(), spell_moorabi_mojo_frenzy_aura::HandlePeriodic(), spell_sladran_grip_of_sladran_aura::HandlePeriodic(), spell_serpentshrine_cavern_coilfang_water::HandlePeriodic(), spell_alar_flame_quills::HandlePeriodic(), spell_kaelthas_remote_toy::HandlePeriodic(), spell_kaelthas_burn::HandlePeriodic(), spell_q10923_evil_draws_near_periodic_aura::HandlePeriodic(), spell_kiljaeden_shadow_spike_aura::HandlePeriodic(), spell_kiljaeden_armageddon_periodic_aura::HandlePeriodic(), spell_halion_twilight_cutter_periodic_aura::HandlePeriodic(), spell_ragin_flames_inferno::HandlePeriodic(), spell_dk_pet_scaling::HandlePeriodic(), spell_hun_generic_scaling::HandlePeriodic(), spell_mage_pet_scaling::HandlePeriodic(), spell_sha_feral_spirit_scaling::HandlePeriodic(), spell_warl_generic_scaling::HandlePeriodic(), spell_magtheridon_shadow_grasp::HandlePeriodicRemove(), spell_deathbringer_blood_link_aura::HandlePeriodicTick(), spell_gen_consume::HandleProc(), spell_item_lil_phylactery::HandleProc(), spell_mage_burning_determination::HandleProc(), spell_item_trauma::HandleProc(), spell_dk_dancing_rune_weapon::HandleProc(), spell_kiljaeden_darkness_aura::HandleRemove(), spell_kiljaeden_vengeance_of_the_blue_flight_aura::HandleRemove(), spell_entropius_void_zone_visual_aura::HandleRemove(), spell_boss_magus_telestra_summon_telestra_clones_aura::HandleRemove(), spell_warr_improved_spell_reflection_trigger_aura::HandleRemove(), spell_gen_food_heart_emote::HandleUpdatePeriodic(), spell_hun_sniper_training::HandleUpdatePeriodic(), spell_uldaman_stoned_aura::Load(), spell_dtk_raise_dead_aura::Load(), spell_igb_overheat_aura::Load(), spell_the_lich_king_vile_spirits_aura::Load(), spell_boss_magus_telestra_summon_telestra_clones_aura::Load(), spell_illidan_demon_transform1_aura::Load(), spell_illidan_demon_transform2_aura::Load(), spell_teron_gorefiend_shadowy_construct::Load(), spell_kaelthas_flame_strike::Load(), spell_gen_replenishment_aura::Load(), spell_pal_ardent_defender::Load(), spell_rog_cheat_death::Load(), spell_warl_improved_demonic_tactics::Load(), spell_chapter5_light_of_dawn_aura::OnApply(), spell_shadowfang_keep_forsaken_skills_aura::OnApply(), spell_spell_fury_aura::OnApply(), spell_yogg_saron_malady_of_the_mind_aura::OnApply(), spell_alar_dive_bomb::OnApply(), spell_astromancer_solarian_transform::OnApply(), spell_gen_animal_blood::OnApply(), spell_contagion_of_rot::OnApply(), spell_gen_food_heart_emote::OnApply(), spell_gruul_ground_slam_trigger::OnApply(), spell_item_shifting_naaru_silver::OnBaseRemove(), spell_muru_summon_blood_elves_periodic_aura::OnPeriodic(), spell_cthun_digestive_acid::OnPeriodic(), spell_anubisath_mortal_strike::OnPeriodic(), spell_tharon_ja_curse_of_life_aura::OnPeriodic(), spell_the_lich_king_infest_aura::OnPeriodic(), spell_thorim_trash_impale_aura::OnPeriodic(), spell_yogg_saron_brain_link_aura::OnPeriodic(), spell_yogg_saron_empowered_aura::OnPeriodic(), spell_illidan_demon_transform1_aura::OnPeriodic(), spell_black_temple_curse_of_vitality_aura::OnPeriodic(), spell_gen_flurry_of_claws::OnPeriodic(), spell_muru_darkness_aura::OnPeriodic(), spell_thorim_lightning_pillar_P2_aura::OnPeriodic(), spell_illidan_demon_transform2_aura::OnPeriodic(), spell_karathress_power_of_tidalvess::OnPeriodic(), spell_karathress_power_of_caribdis::OnPeriodic(), spell_leotheras_demon_link::OnPeriodic(), spell_lurker_below_spout::OnPeriodic(), spell_gen_periodic_knock_away::OnPeriodic(), spell_hun_aspect_of_the_beast::OnPetApply(), spell_gen_proc_on_victim::OnProc(), spell_chapter5_light_of_dawn_aura::OnRemove(), spell_kalecgos_curse_of_boundless_agony_aura::OnRemove(), spell_kalecgos_spectral_realm_aura::OnRemove(), spell_boss_salramm_steal_flesh_aura::OnRemove(), spell_huhuran_wyvern_sting::OnRemove(), spell_yogg_saron_malady_of_the_mind_aura::OnRemove(), spell_yogg_saron_insane_aura::OnRemove(), spell_dragonblight_flame_fury::OnRemove(), spell_dragonblight_devour_ghoul_periodic::OnRemove(), spell_astromancer_solarian_transform::OnRemove(), spell_kaelthas_flame_strike::OnRemove(), spell_gen_animal_blood::OnRemove(), spell_item_goblin_weather_machine_aura::OnRemove(), spell_q12937_relief_for_the_fallen::OnRemove(), spell_shield_of_runes_aura::OnRemove(), spell_black_morass_corrupt_medivh::PeriodicTick(), spell_karazhan_overload_aura::PeriodicTick(), spell_geddon_inferno_aura::PeriodicTick(), spell_azjol_nerub_carrion_beetles::PrepareAuraScript(), spell_deathbringer_blood_power_aura::RecalculateHook(), spell_pri_power_word_shield_aura::ReflectDamage(), spell_igb_overheat_aura::SendClientControl(), spell_gen_holiday_buff_food::TriggerFoodBuff(), spell_auchenai_possess::Update(), spell_allergies::Update(), spell_gen_bg_preparation::Update(), spell_rog_savage_combat::Update(), spell_item_goblin_gumbo_kettle::Update(), spell_karazhan_brittle_bones_aura::Update(), spell_black_temple_curse_of_the_bleakheart_aura::Update(), spell_illidari_council_deadly_strike_aura::Update(), spell_mother_shahraz_random_periodic_aura::Update(), spell_mother_shahraz_beam_periodic_aura::Update(), spell_mother_shahraz_saber_lash_aura::Update(), spell_black_temple_charge_rage_aura::Update(), spell_black_temple_shadow_inferno_aura::Update(), and spell_black_temple_spell_absorption_aura::Update().
HasEffect()
bool AuraScript::HasEffect (uint8 effIndex) const
{
    return m_aura->HasEffect(effIndex);
}
References Aura::HasEffect(), and m_aura.
HasEffectType()
bool AuraScript::HasEffectType (AuraType type) const
{
    return m_aura->HasEffectType(type);
}
References Aura::HasEffectType(), and m_aura.
IsDeathPersistent()
bool AuraScript::IsDeathPersistent () const
{
    return m_aura->IsDeathPersistent();
}
References Aura::IsDeathPersistent(), and m_aura.
IsExpired()
bool AuraScript::IsExpired () const
{
    return m_aura->IsExpired();
}
References Aura::IsExpired(), and m_aura.
Referenced by spell_warr_improved_spell_reflection_trigger_aura::HandleRemove(), spell_azgalor_doom_aura::OnRemove(), and spell_warl_curse_of_doom::OnRemove().
IsPassive()
bool AuraScript::IsPassive () const
{
    return m_aura->IsPassive();
}
References Aura::IsPassive(), and m_aura.
IsPermanent()
bool AuraScript::IsPermanent () const
{
    return m_aura->IsPermanent();
}
References Aura::IsPermanent(), and m_aura.
ModCharges()
bool AuraScript::ModCharges (int8 num, AuraRemoveMode removeMode = AURA_REMOVE_BY_DEFAULT)
{
    return m_aura->ModCharges(num, removeMode);
}
References m_aura, and Aura::ModCharges().
ModStackAmount()
bool AuraScript::ModStackAmount (int32 num, AuraRemoveMode removeMode = AURA_REMOVE_BY_DEFAULT)
{
    return m_aura->ModStackAmount(num, removeMode);
}
References m_aura, and Aura::ModStackAmount().
Referenced by spell_charge_shield_bomber_aura::Absorb(), spell_gen_shriveling_gaze::HandleApply(), spell_hodir_biting_cold_player_aura::HandleEffectPeriodic(), spell_q13003_thursting_hodirs_spear_aura::HandlePeriodic(), spell_karazhan_wrath_titans_aura::HandleProc(), spell_spell_fury_aura::OnApply(), spell_q13003_thursting_hodirs_spear_aura::OnApply(), spell_fungal_decay::OnApply(), spell_gen_shriveling_gaze::OnPeriodic(), spell_gen_turkey_marker::OnPeriodic(), and spell_fungal_decay::PeriodicTick().
PreventDefaultAction()
void AuraScript::PreventDefaultAction ()
{
    switch (m_currentScriptState)
    {
        case AURA_SCRIPT_HOOK_EFFECT_APPLY:
        case AURA_SCRIPT_HOOK_EFFECT_REMOVE:
        case AURA_SCRIPT_HOOK_EFFECT_PERIODIC:
        case AURA_SCRIPT_HOOK_EFFECT_ABSORB:
        case AURA_SCRIPT_HOOK_EFFECT_SPLIT:
        case AURA_SCRIPT_HOOK_PREPARE_PROC:
        case AURA_SCRIPT_HOOK_PROC:
        case AURA_SCRIPT_HOOK_EFFECT_PROC:
            m_defaultActionPrevented = true;
            break;
        default:
            LOG_ERROR("spells.scripts", "Script: `{}` Spell: `{}` AuraScript::PreventDefaultAction called in a hook in which the call won't have effect!", m_scriptName->c_str(), m_scriptSpellId);
            break;
    }
}
References AURA_SCRIPT_HOOK_EFFECT_ABSORB, AURA_SCRIPT_HOOK_EFFECT_APPLY, AURA_SCRIPT_HOOK_EFFECT_PERIODIC, AURA_SCRIPT_HOOK_EFFECT_PROC, AURA_SCRIPT_HOOK_EFFECT_REMOVE, AURA_SCRIPT_HOOK_EFFECT_SPLIT, AURA_SCRIPT_HOOK_PREPARE_PROC, AURA_SCRIPT_HOOK_PROC, LOG_ERROR, _SpellScript::m_currentScriptState, m_defaultActionPrevented, _SpellScript::m_scriptName, and _SpellScript::m_scriptSpellId.
Referenced by spell_teron_gorefiend_shadow_of_death::Absorb(), spell_mage_fire_frost_ward::Absorb(), spell_rotface_unstable_ooze_explosion_suicide_aura::DespawnSelf(), spell_warl_eye_of_kilrogg::HandleAuraApply(), spell_shadowfang_keep_forsaken_skills_aura::HandleDummyTick(), spell_tharon_ja_dummy_aura::HandleEffectApply(), spell_dk_dancing_rune_weapon_visual::HandleEffectApply(), spell_midsummer_ribbon_pole::HandleEffectPeriodic(), spell_hor_gunship_cannon_fire_aura::HandleEffectPeriodic(), spell_pos_empowered_blizzard_aura::HandleEffectPeriodic(), spell_icc_yf_frozen_orb_aura::HandleEffectPeriodic(), spell_oculus_soar_aura::HandleEffectPeriodic(), spell_hodir_storm_cloud_aura::HandleEffectPeriodic(), spell_destroy_door_seal_aura::HandleEffectPeriodic(), spell_z_check_aura::HandleEffectPeriodic(), spell_gen_whisper_gulch_yogg_saron_whisper::HandleEffectPeriodic(), spell_q2203_thaumaturgy_channel::HandleEffectPeriodic(), spell_valkyr_touch_aura::HandleEffectPeriodic(), spell_pos_glacial_strike_aura::HandleEffectPeriodic(), spell_icc_yh_volley_aura::HandleEffectPeriodic(), spell_frost_tomb_aura::HandleEffectPeriodic(), spell_q12619_emblazon_runeblade::HandleEffectPeriodic(), spell_warr_t3_prot_8p_bonus::HandleEffectProc(), spell_sha_item_t10_elemental_2p_bonus::HandleEffectProc(), spell_warr_retaliation::HandleEffectProc(), spell_tharon_ja_dummy_aura::HandleEffectRemove(), spell_yogg_saron_brain_link_aura::HandleOnEffectApply(), spell_oculus_rider_aura::HandleOnEffectApply(), spell_mage_fingers_of_frost_proc_aura::HandleOnEffectProc(), aura_class_call_siphon_blessing::HandlePeriodic(), spell_hadronox_summon_periodic_aura::HandlePeriodic(), spell_halion_meteor_strike_spread_aura::HandlePeriodic(), spell_moorabi_mojo_frenzy_aura::HandlePeriodic(), spell_sladran_grip_of_sladran_aura::HandlePeriodic(), spell_algalon_phase_punch_aura::HandlePeriodic(), spell_algalon_collapse_aura::HandlePeriodic(), spell_algalon_remove_phase_aura::HandlePeriodic(), spell_serpentshrine_cavern_coilfang_water::HandlePeriodic(), spell_rancid_spore_cloud::HandlePeriodic(), spell_spore_cloud::HandlePeriodic(), spell_alar_flame_quills::HandlePeriodic(), spell_kaelthas_remote_toy::HandlePeriodic(), spell_q10923_evil_draws_near_periodic_aura::HandlePeriodic(), spell_sha_totemic_mastery::HandlePeriodic(), spell_kiljaeden_shadow_spike_aura::HandlePeriodic(), spell_kiljaeden_armageddon_periodic_aura::HandlePeriodic(), spell_halion_twilight_cutter_periodic_aura::HandlePeriodic(), spell_oculus_ride_ruby_emerald_amber_drake_que_aura::HandlePeriodic(), spell_dk_death_and_decay_aura::HandlePeriodic(), spell_dk_pet_scaling::HandlePeriodic(), spell_dk_army_of_the_dead_passive::HandlePeriodic(), spell_pet_hit_expertise_scalling::HandlePeriodic(), spell_pet_intellect_spirit_resilience_scaling::HandlePeriodic(), spell_pet_spellhit_expertise_spellpen_scaling::HandlePeriodic(), spell_hun_generic_scaling::HandlePeriodic(), spell_hun_sniper_training::HandlePeriodic(), spell_mage_pet_scaling::HandlePeriodic(), spell_sha_feral_spirit_scaling::HandlePeriodic(), spell_warl_improved_demonic_tactics::HandlePeriodic(), spell_warl_demonic_knowledge::HandlePeriodic(), spell_warl_generic_scaling::HandlePeriodic(), spell_voa_overcharge_aura::HandlePeriodicDummy(), spell_wintergrasp_hide_small_elementals_aura::HandlePeriodicDummy(), spell_krick_explosive_barrage_aura::HandlePeriodicTick(), spell_deathbringer_blood_link_aura::HandlePeriodicTick(), spell_igb_periodic_trigger_with_power_cost_aura::HandlePeriodicTick(), spell_deathwhisper_mana_barrier_aura::HandlePeriodicTick(), spell_item_enchanted_broom_periodic::HandlePeriodicTick(), spell_bronjahm_soulstorm_channel_ooc_aura::HandlePeriodicTick(), spell_bronjahm_soulstorm_visual_aura::HandlePeriodicTick(), spell_wailing_souls_periodic_aura::HandlePeriodicTick(), spell_exploding_orb_auto_grow_aura::HandlePeriodicTick(), spell_item_direbrew_remote_aura::HandlePeriodicTick(), spell_oculus_evasive_maneuvers_aura::HandleProc(), spell_mark_of_malice::HandleProc(), spell_item_lil_phylactery::HandleProc(), spell_mage_burning_determination::HandleProc(), spell_pri_t4_4p_bonus::HandleProc(), spell_pri_shadowfiend_death::HandleProc(), spell_rog_tricks_of_the_trade::HandleProc(), spell_gyth_chromatic_protection::HandleProc(), spell_karazhan_wrath_titans_aura::HandleProc(), spell_deathbringer_blood_link_aura::HandleProc(), spell_deathbringer_blood_link_blood_beast_aura::HandleProc(), spell_reliquary_of_souls_aura_of_desire_aura::HandleProc(), spell_black_temple_consuming_strikes_aura::HandleProc(), spell_ahune_spanky_hands::HandleProc(), spell_item_trauma::HandleProc(), spell_item_blade_ward_enchant::HandleProc(), spell_item_blood_draining_enchant::HandleProc(), spell_item_shadows_fate::HandleProc(), spell_mage_ignite::HandleProc(), spell_utgarde_pinnacle_beast_mark::HandleProc(), spell_dk_scent_of_blood::HandleProc(), spell_dru_living_seed_proc::HandleProc(), spell_hun_ascpect_of_the_viper::HandleProc(), spell_hun_improved_mend_pet::HandleProc(), spell_hun_misdirection::HandleProc(), spell_item_healing_trance::HandleProc(), spell_item_aegis_of_preservation::HandleProc(), spell_item_desperate_defense::HandleProc(), spell_mage_focus_magic::HandleProc(), spell_pal_blessing_of_sanctuary::HandleProc(), spell_pri_item_greater_heal_refund::HandleProc(), spell_pri_mana_leech::HandleProc(), spell_sha_earth_shield::HandleProc(), spell_warr_vigilance::HandleProc(), spell_karazhan_temptation::HandleProc(), spell_the_lich_king_dark_hunger_aura::HandleProc(), spell_oculus_temporal_rift_aura::HandleProc(), spell_dk_wandering_plague_aura::HandleProc(), spell_dk_blood_caked_blade::HandleProc(), spell_dk_dancing_rune_weapon::HandleProc(), spell_dk_blood_gorged::HandleProc(), spell_dru_t10_balance_4p_bonus::HandleProc(), spell_dru_living_seed::HandleProc(), spell_gen_proc_not_self::HandleProc(), spell_gen_adaptive_warding::HandleProc(), spell_gen_moss_covered_feet::HandleProc(), spell_gen_obsidian_armor::HandleProc(), spell_gen_blade_warding::HandleProc(), spell_hun_glyph_of_arcane_shot::HandleProc(), spell_item_blessing_of_ancient_kings::HandleProc(), spell_item_necrotic_touch::HandleProc(), spell_item_unsated_craving::HandleProc(), spell_item_shadowmourne::HandleProc(), spell_mage_burnout::HandleProc(), spell_mage_master_of_elements::HandleProc(), spell_pal_seal_of_command_aura::HandleProc(), spell_pal_sacred_shield_base::HandleProc(), spell_pal_seal_of_righteousness::HandleProc(), spell_pri_divine_aegis::HandleProc(), spell_pri_glyph_of_prayer_of_healing::HandleProc(), spell_pri_vampiric_touch::HandleProc(), spell_rog_blade_flurry::HandleProc(), spell_sha_t10_restoration_4p_bonus::HandleProc(), spell_sha_item_lightning_shield::HandleProc(), spell_sha_item_lightning_shield_trigger::HandleProc(), spell_sha_item_mana_surge::HandleProc(), spell_sha_t8_electrified::HandleProc(), spell_warl_seed_of_corruption_aura::HandleProc(), spell_warl_seed_of_corruption_generic_aura::HandleProc(), spell_warl_glyph_of_shadowflame::HandleProc(), spell_warl_drain_soul::HandleProc(), spell_warl_demonic_pact_aura::HandleProc(), spell_warr_sweeping_strikes::HandleProc(), spell_dk_bone_shield::HandleProc(), spell_dk_hungering_cold::HandleProc(), spell_hun_lock_and_load::HandleProcs(), spell_kelthuzad_detonate_mana_aura::HandleScript(), spell_putricide_grow_stacker_aura::HandleTriggerSpell(), spell_magic_eater_food::HandleTriggerSpell(), spell_alert_drums::HandleTriggerSpell(), spell_putricide_mutated_plague_aura::HandleTriggerSpell(), spell_anubisath_mortal_strike::OnPeriodic(), spell_dred_grievious_bite_aura::OnPeriodic(), spell_tharon_ja_curse_of_life_aura::OnPeriodic(), spell_the_lich_king_infest_aura::OnPeriodic(), spell_illidan_tear_of_azzinoth_summon_channel_aura::OnPeriodic(), spell_illidan_demon_transform1_aura::OnPeriodic(), spell_illidan_cage_trap_stun_aura::OnPeriodic(), spell_npc22275_crystal_prison_aura::OnPeriodic(), spell_gen_flurry_of_claws::OnPeriodic(), spell_gen_shriveling_gaze::OnPeriodic(), spell_deathwhisper_dark_reckoning::OnPeriodic(), spell_the_lich_king_soul_rip_aura::OnPeriodic(), spell_assembly_rune_of_summoning_aura::OnPeriodic(), spell_thorim_lightning_pillar_P2_aura::OnPeriodic(), spell_illidan_demon_transform2_aura::OnPeriodic(), spell_karathress_power_of_tidalvess::OnPeriodic(), spell_karathress_power_of_caribdis::OnPeriodic(), spell_leotheras_demon_link::OnPeriodic(), spell_lurker_below_spout::OnPeriodic(), spell_gen_periodic_knock_away::OnPeriodic(), spell_gen_proc_on_victim::OnProc(), spell_blood_queen_essence_of_the_blood_queen_aura::OnProc(), spell_pal_eye_for_an_eye::OnProc(), spell_warl_siphon_life::OnProc(), spell_warl_fel_synergy::OnProc(), spell_warr_improved_spell_reflection::OnProc(), spell_warr_damage_shield::OnProc(), spell_barreled_control_aura::PeriodicTick(), spell_sindragosa_frost_beacon_aura::PeriodicTick(), spell_sindragosa_ice_tomb_trap_aura::PeriodicTick(), spell_sindragosa_soul_preservation_aura::PeriodicTick(), spell_frostwarden_handler_focus_fire_aura::PeriodicTick(), spell_dreamwalker_nightmare_cloud_aura::PeriodicTick(), spell_dreamwalker_summon_suppresser_aura::PeriodicTick(), spell_karazhan_overload_aura::PeriodicTick(), spell_geddon_inferno_aura::PeriodicTick(), spell_entropius_negative_energy_periodic::PeriodicTick(), spell_igb_explosion_main_aura::PeriodicTick(), spell_dreamwalker_mana_void_aura::PeriodicTick(), spell_dragonblight_corrosive_spit::PeriodicTick(), spell_broggok_poison_cloud::PeriodicTick(), spell_the_eye_countercharge_aura::PrepareProc(), spell_warl_drain_soul::RemoveEffect(), spell_warl_shadowburn::RemoveEffect(), spell_koralon_meteor_fists_aura::TriggerFists(), spell_flame_warder_meteor_fists_aura::TriggerFists(), spell_item_goblin_gumbo_kettle::Update(), spell_karazhan_brittle_bones_aura::Update(), spell_reliquary_of_souls_aura_of_desire_aura::Update(), spell_teron_gorefiend_spirit_lance::Update(), spell_black_temple_curse_of_the_bleakheart_aura::Update(), spell_illidari_council_deadly_strike_aura::Update(), spell_mother_shahraz_random_periodic_aura::Update(), spell_mother_shahraz_beam_periodic_aura::Update(), spell_mother_shahraz_saber_lash_aura::Update(), spell_black_temple_charge_rage_aura::Update(), spell_black_temple_shadow_inferno_aura::Update(), and spell_black_temple_spell_absorption_aura::Update().
RefreshDuration()
void AuraScript::RefreshDuration ()
{
    m_aura->RefreshDuration();
}
References m_aura, and Aura::RefreshDuration().
Remove()
void AuraScript::Remove (uint32 removeMode = 0)
{
    m_aura->Remove((AuraRemoveMode)removeMode);
}
References m_aura, and Aura::Remove().
Referenced by spell_pri_guardian_spirit::Absorb(), spell_the_lich_king_necrotic_plague_jump_aura::AfterDispel(), spell_pursuing_spikes_aura::HandleEffectPeriodic(), spell_igb_rocket_pack_aura::HandlePeriodic(), spell_algalon_phase_punch_aura::HandlePeriodic(), spell_wailing_souls_periodic_aura::HandlePeriodicTick(), spell_rog_tricks_of_the_trade::HandleProc(), spell_warl_seed_of_corruption_aura::HandleProc(), spell_warl_seed_of_corruption_generic_aura::HandleProc(), and spell_the_lich_king_infest_aura::OnPeriodic().
SetCharges()
void AuraScript::SetCharges (uint8 charges)
{
    m_aura->SetCharges(charges);
}
References m_aura, and Aura::SetCharges().
SetDuration()
void AuraScript::SetDuration (int32 duration, bool withMods = false)
{
    m_aura->SetDuration(duration, withMods);
}
References m_aura, and Aura::SetDuration().
Referenced by spell_gen_disabled_above_63::CalculateAmount(), spell_infected_worgen_bite_aura::HandleAfterEffectApply(), spell_entropius_void_zone_visual_aura::HandleApply(), spell_scourge_disguise_instability::HandleApply(), spell_lurker_below_spout::HandleEffectApply(), spell_q11065_wrangle_some_aether_rays_aura::HandleEffectApply(), spell_midsummer_ribbon_pole::HandleEffectPeriodic(), spell_toc25_mistress_kiss_aura::HandleEffectPeriodic(), spell_hodir_biting_cold_player_aura::HandleEffectPeriodic(), spell_yogg_saron_brain_link_aura::HandleOnEffectApply(), spell_sladran_grip_of_sladran_aura::HandlePeriodic(), spell_serpentshrine_cavern_coilfang_water::HandlePeriodic(), spell_item_direbrew_remote_aura::HandlePeriodicTick(), spell_oculus_evasive_maneuvers_aura::HandleProc(), spell_dk_hungering_cold::HandleProc(), spell_halion_meteor_strike_marker_aura::OnApply(), spell_dred_grievious_bite_aura::OnPeriodic(), spell_tharon_ja_curse_of_life_aura::OnPeriodic(), spell_thorim_trash_impale_aura::OnPeriodic(), spell_yogg_saron_brain_link_aura::OnPeriodic(), spell_illidan_tear_of_azzinoth_summon_channel_aura::OnPeriodic(), spell_illidan_demon_transform1_aura::OnPeriodic(), spell_illidan_cage_trap_stun_aura::OnPeriodic(), spell_black_temple_curse_of_vitality_aura::OnPeriodic(), spell_npc22275_crystal_prison_aura::OnPeriodic(), spell_mark_of_kazrogal_aura::OnPeriodic(), spell_illidan_demon_transform2_aura::OnPeriodic(), spell_mark_of_kazzak_aura::OnPeriodic(), spell_hun_aspect_of_the_beast::OnPetApply(), spell_sindragosa_soul_preservation_aura::PeriodicTick(), spell_auchenai_possess::Update(), spell_gen_bg_preparation::Update(), and spell_rog_savage_combat::Update().
SetMaxDuration()
void AuraScript::SetMaxDuration (int32 duration)
{
    m_aura->SetMaxDuration(duration);
}
References m_aura, and Aura::SetMaxDuration().
Referenced by spell_gen_bg_preparation::Update().
SetStackAmount()
void AuraScript::SetStackAmount (uint8 num)
{
    m_aura->SetStackAmount(num);
}
References m_aura, and Aura::SetStackAmount().
Member Data Documentation
AfterDispel
HookList<AuraDispelHandler> AuraScript::AfterDispel
Referenced by spell_hexlord_unstable_affliction::Register(), spell_faction_champion_warl_unstable_affliction_aura::Register(), spell_the_lich_king_necrotic_plague_jump_aura::Register(), spell_dru_lifebloom::Register(), spell_pri_vampiric_touch::Register(), spell_sha_flame_shock::Register(), and spell_warl_unstable_affliction::Register().
AfterEffectAbsorb
HookList<EffectAbsorbHandler> AuraScript::AfterEffectAbsorb
Referenced by spell_reflective_shield_aura::Register(), spell_valkyr_essence_aura::Register(), spell_shield_of_bones_aura::Register(), spell_illidari_council_reflective_shield_aura::Register(), spell_dk_anti_magic_shell_self::Register(), spell_mage_fire_frost_ward::Register(), spell_mage_ice_barrier_aura::Register(), and spell_pri_power_word_shield_aura::Register().
AfterEffectApply
HookList<EffectApplyHandler> AuraScript::AfterEffectApply
Referenced by spell_geddon_inferno_aura::Register(), spell_geddon_armageddon_aura::Register(), spell_mc_play_dead_aura::Register(), spell_scholomance_boon_of_life_aura::Register(), spell_brewfest_reveler_transform::Register(), spell_love_is_in_the_air_romantic_picnic::Register(), spell_gen_aura_service_uniform::Register(), spell_bonfires_blessing::Register(), spell_gen_crab_disguise::Register(), spell_braziers_hit::Register(), spell_nullify::Register(), spell_halion_combustion_consumption_aura::Register(), spell_halion_twilight_realm_aura::Register(), spell_halion_leave_twilight_realm_aura::Register(), spell_igb_rocket_pack_useable_aura::Register(), spell_igb_overheat_aura::Register(), spell_igb_on_gunship_deck_aura::Register(), spell_sindragosa_ice_tomb_trap_aura::Register(), spell_the_lich_king_necrotic_plague_jump_aura::Register(), spell_valithria_suppression_aura::Register(), spell_four_horsemen_mark_aura::Register(), spell_boss_magus_telestra_summon_telestra_clones_aura::Register(), spell_oculus_stop_time_aura::Register(), spell_saronite_vapors_dummy_aura::Register(), spell_hodir_storm_power_aura::Register(), spell_hodir_toasty_fire_aura::Register(), spell_hodir_starlight_aura::Register(), spell_yogg_saron_shadow_beacon_aura::Register(), spell_dragonblight_corrosive_spit::Register(), spell_infected_worgen_bite_aura::Register(), spell_shade_of_akama_shade_soul_channel::Register(), spell_teron_gorefiend_shadowy_construct::Register(), spell_hydross_cleansing_field_aura::Register(), spell_leotheras_insidious_whisper_aura::Register(), spell_serpentshrine_cavern_coilfang_water::Register(), spell_commander_sarannis_arcane_devastation::Register(), spell_dk_improved_blood_presence::Register(), spell_dk_improved_frost_presence::Register(), spell_dk_improved_unholy_presence::Register(), spell_dk_presence::Register(), spell_dru_nurturing_instinct::Register(), spell_dru_feral_swiftness::Register(), spell_dru_barkskin::Register(), spell_dru_enrage::Register(), spell_dru_predatory_strikes::Register(), spell_dru_savage_roar_aura::Register(), spell_dru_survival_instincts_aura::Register(), spell_dru_rejuvenation_moonglade_2_set::Register(), spell_gen_animal_blood::Register(), spell_gen_defend::Register(), spell_gen_on_tournament_mount::Register(), spell_gen_summon_elemental::Register(), spell_contagion_of_rot::Register(), spell_silithyst::Register(), spell_gen_steal_weapon::Register(), spell_hun_aspect_of_the_beast::Register(), spell_hun_ascpect_of_the_viper::Register(), spell_hun_viper_attack_speed::Register(), spell_item_shadowmourne_soul_fragment::Register(), spell_pal_blessing_of_sanctuary::Register(), spell_pri_lightwell_renew::Register(), spell_pri_mind_control::Register(), spell_q12851_going_bearback::Register(), spell_q12987_read_pronouncement::Register(), spell_rog_killing_spree_aura::Register(), and spell_warr_vigilance::Register().
AfterEffectManaShield
HookList<EffectManaShieldHandler> AuraScript::AfterEffectManaShield
Referenced by spell_mage_mana_shield::Register().
AfterEffectProc
HookList<EffectProcHandler> AuraScript::AfterEffectProc
Referenced by spell_mage_fingers_of_frost_proc_aura::Register().
AfterEffectRemove
HookList<EffectApplyHandler> AuraScript::AfterEffectRemove
Referenced by spell_vael_burning_adrenaline::Register(), spell_geddon_inferno_aura::Register(), spell_geddon_armageddon_aura::Register(), spell_mc_play_dead_aura::Register(), spell_q12779_an_end_to_all_things_devour_aura::Register(), spell_kalecgos_curse_of_boundless_agony_aura::Register(), spell_electrial_storm::Register(), spell_blood_siphon_aura::Register(), spell_gen_aura_service_uniform::Register(), spell_gen_crab_disguise::Register(), spell_torch_tossing_training::Register(), spell_boss_salramm_steal_flesh_aura::Register(), spell_huhuran_wyvern_sting::Register(), spell_inoculate_nestlewood_owlkin::Register(), spell_hadronox_leech_poison_aura::Register(), spell_halion_meteor_strike_marker_aura::Register(), spell_halion_combustion_consumption_aura::Register(), spell_halion_marks_aura::Register(), spell_halion_leave_twilight_realm_aura::Register(), spell_trollgore_corpse_explode_aura::Register(), spell_dtk_raise_dead_aura::Register(), spell_hor_shared_suffering_aura::Register(), spell_blood_queen_frenzied_bloodthirst_aura::Register(), spell_festergut_blighted_spores_aura::Register(), spell_igb_rocket_pack_useable_aura::Register(), spell_igb_overheat_aura::Register(), spell_putricide_mutated_plague_aura::Register(), spell_putricide_mutation_init_aura::Register(), spell_putricide_mutated_transformation_dismiss_aura::Register(), spell_rotface_mutated_infection_aura::Register(), spell_sindragosa_instability_aura::Register(), spell_sindragosa_ice_tomb_trap_aura::Register(), spell_the_lich_king_necrotic_plague_aura::Register(), spell_the_lich_king_necrotic_plague_jump_aura::Register(), spell_the_lich_king_shadow_trap_visual_aura::Register(), spell_the_lich_king_harvest_soul_aura::Register(), spell_valithria_suppression_aura::Register(), spell_ioc_repair_turret_aura::Register(), spell_grobbulus_mutating_injection_aura::Register(), spell_boss_magus_telestra_summon_telestra_clones_aura::Register(), spell_shield_of_runes_aura::Register(), spell_aura_of_despair_aura::Register(), spell_ignis_slag_pot_aura::Register(), spell_xt002_gravity_bomb_aura::Register(), spell_yogg_saron_shadow_beacon_aura::Register(), spell_q11919_q11940_drake_hunt_aura::Register(), spell_q13003_thursting_hodirs_spear_aura::Register(), spell_illidan_parasitic_shadowfiend_aura::Register(), spell_illidan_parasitic_shadowfiend_trigger_aura::Register(), spell_reliquary_of_souls_spite_aura::Register(), spell_shade_of_akama_shade_soul_channel::Register(), spell_teron_gorefiend_shadow_of_death::Register(), spell_teron_gorefiend_spiritual_vengeance::Register(), spell_black_temple_skeleton_shot_aura::Register(), spell_black_temple_wyvern_sting_aura::Register(), spell_hydross_cleansing_field_aura::Register(), spell_hydross_cleansing_field_command::Register(), spell_lady_vashj_magic_barrier::Register(), spell_leotheras_insidious_whisper_aura::Register(), spell_serpentshrine_cavern_serpentshrine_parasite::Register(), spell_serpentshrine_cavern_serpentshrine_parasite_trigger_aura::Register(), spell_serpentshrine_cavern_infection::Register(), spell_serpentshrine_cavern_coilfang_water::Register(), spell_warlords_rage::Register(), spell_gruul_ground_slam_trigger::Register(), spell_astromancer_wrath_of_the_astromancer::Register(), spell_capacitus_polarity_charge_aura::Register(), spell_dk_improved_blood_presence::Register(), spell_dk_improved_frost_presence::Register(), spell_dk_improved_unholy_presence::Register(), spell_dk_presence::Register(), spell_dru_nurturing_instinct::Register(), spell_dru_feral_swiftness::Register(), spell_dru_barkskin::Register(), spell_dru_enrage::Register(), spell_dru_lifebloom::Register(), spell_dru_predatory_strikes::Register(), spell_dru_savage_roar_aura::Register(), spell_dru_survival_instincts_aura::Register(), spell_dru_rejuvenation_moonglade_2_set::Register(), spell_gen_animal_blood::Register(), spell_gen_paralytic_poison::Register(), spell_gen_lifebloom::Register(), spell_gen_summon_elemental::Register(), spell_silithyst::Register(), spell_gen_consume::Register(), spell_gen_apply_aura_after_expiration::Register(), spell_gen_sober_up::Register(), spell_gen_steal_weapon::Register(), spell_hun_wyvern_sting::Register(), spell_hun_aspect_of_the_beast::Register(), spell_hun_ascpect_of_the_viper::Register(), spell_hun_misdirection::Register(), spell_hun_misdirection_proc::Register(), spell_hun_viper_attack_speed::Register(), spell_item_shifting_naaru_silver::Register(), spell_item_goblin_weather_machine_aura::Register(), spell_item_shadowmourne::Register(), spell_item_shadowmourne_soul_fragment::Register(), spell_mage_combustion_proc::Register(), spell_mage_living_bomb::Register(), spell_pal_avenging_wrath::Register(), spell_pal_blessing_of_sanctuary::Register(), spell_pri_lightwell_renew::Register(), spell_pri_mind_control::Register(), spell_q10525_vision_guide::Register(), spell_rog_killing_spree_aura::Register(), spell_rog_tricks_of_the_trade::Register(), spell_rog_tricks_of_the_trade_proc::Register(), spell_sha_sentry_totem::Register(), spell_warl_eye_of_kilrogg::Register(), spell_warl_seed_of_corruption_aura::Register(), spell_warl_curse_of_doom::Register(), and spell_warr_improved_spell_reflection_trigger_aura::Register().
AfterProc
HookList<AuraProcHandler> AuraScript::AfterProc
Referenced by spell_hun_lock_and_load::Register().
DoAfterCheckProc
HookList<AfterCheckProcHandler> AuraScript::DoAfterCheckProc
Referenced by spell_mage_fingers_of_frost_proc_aura::Register(), spell_mage_master_of_elements::Register(), spell_pri_shadowfiend_death::Register(), and spell_war_sudden_death_aura::Register().
DoCheckAreaTarget
HookList<CheckAreaTargetHandler> AuraScript::DoCheckAreaTarget
Referenced by spell_igb_rocket_pack_useable_aura::Register(), spell_igb_on_gunship_deck_aura::Register(), spell_gen_area_aura_select_players::Register(), spell_gen_area_aura_select_players_and_caster::Register(), and spell_gen_av_drekthar_presence::Register().
DoCheckProc
HookList<CheckProcHandler> AuraScript::DoCheckProc
Referenced by spell_mage_fingers_of_frost_proc_aura::Register(), spell_mage_fingers_of_frost_proc::Register(), spell_karazhan_wrath_titans_aura::Register(), spell_gen_weapon_coating_enchant::Register(), spell_deathbringer_blood_link_aura::Register(), spell_deathbringer_blood_link_blood_beast_aura::Register(), spell_igb_battle_experience_check::Register(), spell_sindragosa_permeating_chill_aura::Register(), spell_utgarde_pinnacle_beast_mark::Register(), spell_mother_shahraz_saber_lash_aura::Register(), spell_reliquary_of_souls_aura_of_desire_aura::Register(), spell_gargolmar_retalliation::Register(), spell_botanica_shift_form_aura::Register(), spell_the_eye_countercharge_aura::Register(), spell_dk_improved_blood_presence_proc::Register(), spell_dk_wandering_plague_aura::Register(), spell_dk_blood_caked_blade::Register(), spell_dk_dancing_rune_weapon::Register(), spell_dk_scent_of_blood_trigger::Register(), spell_dk_blood_gorged::Register(), spell_dru_t10_balance_4p_bonus::Register(), spell_dru_omen_of_clarity::Register(), spell_dru_brambles_treant::Register(), spell_dru_moonkin_form_passive_proc::Register(), spell_gen_allow_proc_from_spells_with_cost::Register(), spell_gen_black_magic_enchant::Register(), spell_gen_proc_from_direct_damage::Register(), spell_gen_no_offhand_proc::Register(), spell_gen_proc_on_self::Register(), spell_gen_proc_not_self::Register(), spell_gen_proc_reduced_above_60::Register(), spell_gen_adaptive_warding::Register(), spell_gen_obsidian_armor::Register(), spell_hun_ascpect_of_the_viper::Register(), spell_hun_improved_mend_pet::Register(), spell_hun_misdirection::Register(), spell_hun_glyph_of_arcane_shot::Register(), spell_hun_lock_and_load::Register(), spell_hun_intimidation::Register(), spell_item_lil_phylactery::Register(), spell_item_essence_of_life::Register(), spell_item_trauma::Register(), spell_item_valanyr_hammer_of_ancient_kings::Register(), spell_item_blessing_of_ancient_kings::Register(), spell_item_necrotic_touch::Register(), spell_item_unsated_craving::Register(), spell_item_shadowmourne::Register(), spell_item_green_whelp_armor::Register(), spell_mage_burning_determination::Register(), spell_mage_molten_armor::Register(), spell_mage_burnout::Register(), spell_mage_brain_freeze::Register(), spell_mage_focus_magic::Register(), spell_mage_ignite::Register(), spell_pal_seal_of_command_aura::Register(), spell_pal_seal_of_light::Register(), spell_pal_sacred_shield_base::Register(), spell_pal_blessing_of_sanctuary::Register(), spell_pal_seal_of_righteousness::Register(), spell_pri_divine_aegis::Register(), spell_pri_item_greater_heal_refund::Register(), spell_pri_mana_leech::Register(), spell_pri_vampiric_touch::Register(), spell_q10985_light_of_the_naaru::Register(), spell_rog_combat_potency::Register(), spell_rog_blade_flurry::Register(), spell_rog_tricks_of_the_trade::Register(), spell_sha_t10_restoration_4p_bonus::Register(), spell_sha_earth_shield::Register(), spell_sha_earthliving_weapon::Register(), spell_sha_item_mana_surge::Register(), spell_sha_flurry_proc::Register(), spell_warl_siphon_life::Register(), spell_warl_fel_synergy::Register(), spell_warl_drain_soul::Register(), spell_warr_improved_spell_reflection::Register(), spell_warr_sweeping_strikes::Register(), spell_warr_vigilance::Register(), spell_warr_t3_prot_8p_bonus::Register(), and spell_warr_retaliation::Register().
DoEffectCalcAmount
HookList<EffectCalcAmountHandler> AuraScript::DoEffectCalcAmount
Referenced by spell_pilgrims_bounty_food_aura::Register(), spell_deathbringer_blood_power_aura::Register(), spell_the_lich_king_lights_favor_aura::Register(), spell_oculus_dream_funnel_aura::Register(), spell_yogg_saron_protective_gaze_aura::Register(), spell_svala_ritual_strike_aura::Register(), spell_charge_shield_bomber_aura::Register(), spell_illidari_council_balance_of_power_aura::Register(), spell_reliquary_of_souls_aura_of_desire_aura::Register(), spell_reliquary_of_souls_aura_of_anger_aura::Register(), spell_teron_gorefiend_spirit_lance::Register(), spell_black_temple_spell_absorption_aura::Register(), spell_mark_of_kazzak_aura::Register(), spell_dk_pet_scaling::Register(), spell_dk_anti_magic_shell_raid::Register(), spell_dk_anti_magic_shell_self::Register(), spell_dk_anti_magic_zone::Register(), spell_dk_icebound_fortitude::Register(), spell_dk_spell_deflection::Register(), spell_dk_vampiric_blood::Register(), spell_dk_will_of_the_necropolis::Register(), spell_dk_army_of_the_dead_passive::Register(), spell_dru_bear_form_passive::Register(), spell_dru_brambles_treant::Register(), spell_dru_treant_scaling::Register(), spell_dru_dash_aura::Register(), spell_dru_innervate::Register(), spell_dru_moonkin_form_passive::Register(), spell_dru_owlkin_frenzy::Register(), spell_dru_primal_tenacity::Register(), spell_dru_rip::Register(), spell_dru_savage_defense::Register(), spell_dru_swift_flight_passive::Register(), spell_gen_reduced_above_60_aura::Register(), spell_pet_hit_expertise_scalling::Register(), spell_gen_disabled_above_63::Register(), spell_gen_lifeblood::Register(), spell_gen_vehicle_scaling_aura::Register(), spell_gen_gift_of_naaru::Register(), spell_gen_replenishment_aura::Register(), spell_pet_intellect_spirit_resilience_scaling::Register(), spell_pet_spellhit_expertise_spellpen_scaling::Register(), spell_hun_cower::Register(), spell_hun_animal_handler::Register(), spell_hun_generic_scaling::Register(), spell_item_skull_of_impeding_doom::Register(), spell_item_arcane_shroud::Register(), spell_item_the_eye_of_diminution::Register(), spell_item_spell_reflectors::Register(), spell_mage_pet_scaling::Register(), spell_mage_fire_frost_ward::Register(), spell_mage_ice_barrier_aura::Register(), spell_mage_mana_shield::Register(), spell_pal_sacred_shield_base::Register(), spell_pal_ardent_defender::Register(), spell_pal_hand_of_salvation::Register(), spell_pri_shadowfiend_scaling::Register(), spell_pri_guardian_spirit::Register(), spell_pri_lightwell_renew::Register(), spell_pri_power_word_shield_aura::Register(), spell_rog_cheat_death::Register(), spell_rog_nerves_of_steel::Register(), spell_rog_rupture::Register(), spell_sha_feral_spirit_scaling::Register(), spell_sha_fire_elemental_scaling::Register(), spell_sha_astral_shift::Register(), spell_sha_earth_shield::Register(), spell_warl_improved_demonic_tactics::Register(), spell_warl_demonic_knowledge::Register(), spell_warl_generic_scaling::Register(), spell_warl_infernal_scaling::Register(), spell_warl_seed_of_corruption_aura::Register(), spell_warl_shadow_ward::Register(), and spell_warr_rend::Register().
DoEffectCalcPeriodic
HookList<EffectCalcPeriodicHandler> AuraScript::DoEffectCalcPeriodic
Referenced by spell_karazhan_brittle_bones_aura::Register(), spell_shadowfang_keep_haunting_spirits_aura::Register(), spell_hallows_end_base_fire::Register(), spell_yogg_saron_sanity_well_aura::Register(), spell_auchenai_possess::Register(), spell_black_temple_curse_of_the_bleakheart_aura::Register(), spell_lurker_below_spout::Register(), spell_serpentshrine_cavern_coilfang_water::Register(), spell_allergies::Register(), spell_dk_pet_scaling::Register(), spell_dk_army_of_the_dead_passive::Register(), spell_gen_bg_preparation::Register(), spell_pet_hit_expertise_scalling::Register(), spell_gen_haunted_aura::Register(), spell_pet_intellect_spirit_resilience_scaling::Register(), spell_pet_spellhit_expertise_spellpen_scaling::Register(), spell_gen_food_heart_emote::Register(), spell_hun_generic_scaling::Register(), spell_item_goblin_gumbo_kettle::Register(), spell_item_brewfest_hops::Register(), spell_mage_mirror_image::Register(), spell_mage_pet_scaling::Register(), spell_rog_savage_combat::Register(), spell_sha_feral_spirit_scaling::Register(), spell_warl_improved_demonic_tactics::Register(), spell_warl_demonic_knowledge::Register(), and spell_warl_generic_scaling::Register().
DoEffectCalcSpellMod
HookList<EffectCalcSpellModHandler> AuraScript::DoEffectCalcSpellMod
Referenced by spell_dru_idol_lifebloom::Register(), spell_pal_exorcism_and_holy_wrath_damage::Register(), spell_warl_improved_demonic_tactics::Register(), and spell_warr_glyph_of_sunder_armor::Register().
DoPrepareProc
HookList<AuraProcHandler> AuraScript::DoPrepareProc
m_aura
Aura* AuraScript::m_aura private
Referenced by _Load(), CalcMaxCharges(), CalcMaxDuration(), DropCharge(), GetApplyTime(), GetAura(), GetCaster(), GetCasterGUID(), GetCharges(), GetDuration(), GetDynobjOwner(), GetEffect(), GetId(), GetMaxDuration(), GetOwner(), GetSpellInfo(), GetStackAmount(), GetType(), GetUnitOwner(), HasEffect(), HasEffectType(), IsDeathPersistent(), IsExpired(), IsPassive(), IsPermanent(), ModCharges(), ModStackAmount(), RefreshDuration(), Remove(), SetCharges(), SetDuration(), SetMaxDuration(), and SetStackAmount().
m_auraApplication
AuraApplication const* AuraScript::m_auraApplication private
Referenced by _FinishScriptCall(), _PrepareScriptCall(), GetTarget(), and GetTargetApplication().
m_defaultActionPrevented
bool AuraScript::m_defaultActionPrevented private
Referenced by _FinishScriptCall(), _IsDefaultActionPrevented(), _PrepareScriptCall(), and PreventDefaultAction().
m_scriptStates
ScriptStateStack AuraScript::m_scriptStates private
Referenced by _FinishScriptCall(), and _PrepareScriptCall().
OnDispel
HookList<AuraDispelHandler> AuraScript::OnDispel
Referenced by spell_halion_marks_aura::Register(), and spell_the_lich_king_necrotic_plague_jump_aura::Register().
OnEffectAbsorb
HookList<EffectAbsorbHandler> AuraScript::OnEffectAbsorb
Referenced by spell_valanar_kinetic_bomb_absorb_aura::Register(), spell_yogg_saron_protective_gaze_aura::Register(), spell_charge_shield_bomber_aura::Register(), spell_teron_gorefiend_shadow_of_death::Register(), spell_black_temple_spell_absorption_aura::Register(), spell_dk_anti_magic_shell_raid::Register(), spell_dk_anti_magic_shell_self::Register(), spell_dk_anti_magic_zone::Register(), spell_dk_spell_deflection::Register(), spell_dk_will_of_the_necropolis::Register(), spell_dru_moonkin_form_passive::Register(), spell_dru_primal_tenacity::Register(), spell_dru_savage_defense::Register(), spell_gen_absorb0_hitlimit1::Register(), spell_mage_fire_frost_ward::Register(), spell_pal_ardent_defender::Register(), spell_pri_guardian_spirit::Register(), spell_rog_cheat_death::Register(), spell_rog_nerves_of_steel::Register(), and spell_sha_astral_shift::Register().
OnEffectApply
HookList<EffectApplyHandler> AuraScript::OnEffectApply
Referenced by spell_midnight_fixate::Register(), spell_nether_portal_perseverence::Register(), spell_lich_king_vo_blocker::Register(), spell_chapter5_light_of_dawn_aura::Register(), spell_scholomance_fixate_aura::Register(), spell_shadowfang_keep_forsaken_skills_aura::Register(), spell_felmyst_fog_of_corruption_charm_aura::Register(), spell_kiljaeden_vengeance_of_the_blue_flight_aura::Register(), spell_kiljaeden_shield_of_the_blue::Register(), spell_muru_summon_blood_elves_periodic_aura::Register(), spell_entropius_void_zone_visual_aura::Register(), spell_spell_fury_aura::Register(), spell_uldaman_stoned_aura::Register(), spell_marli_transform::Register(), spell_catch_the_wild_wolpertinger::Register(), spell_direbrew_disarm::Register(), spell_hallows_end_candy_pirate_costume::Register(), spell_hallows_end_base_fire::Register(), spell_love_in_air_perfume_immune::Register(), spell_midsummer_ribbon_pole::Register(), spell_inoculate_nestlewood_owlkin::Register(), spell_amanitar_remove_mushroom_power::Register(), spell_hadronox_summon_periodic_aura::Register(), spell_halion_meteor_strike_marker_aura::Register(), spell_halion_twilight_phasing_aura::Register(), spell_novos_crystal_handler_death_aura::Register(), spell_tharon_ja_dummy_aura::Register(), spell_blood_queen_frenzied_bloodthirst_aura::Register(), spell_the_lich_king_necrotic_plague_jump_aura::Register(), spell_icc_stoneform_aura::Register(), spell_oculus_evasive_charges_aura::Register(), spell_oculus_soar_aura::Register(), spell_oculus_rider_aura::Register(), spell_oculus_drake_flag_aura::Register(), spell_aura_of_despair_aura::Register(), spell_hodir_storm_power_aura::Register(), spell_ignis_slag_pot_aura::Register(), spell_yogg_saron_malady_of_the_mind_aura::Register(), spell_yogg_saron_brain_link_aura::Register(), spell_q12243_fire_upon_the_waters_aura::Register(), spell_z_check_aura::Register(), spell_q13003_thursting_hodirs_spear_aura::Register(), spell_scourge_disguise_instability::Register(), spell_illidan_shadow_prison_aura::Register(), spell_reliquary_of_souls_aura_of_suffering_aura::Register(), spell_black_template_harpooners_mark_aura::Register(), spell_hydross_mark_of_hydross::Register(), spell_lurker_below_spout::Register(), spell_fungal_decay::Register(), spell_magtheridon_shadow_grasp::Register(), spell_magtheridon_shadow_grasp_visual::Register(), spell_burning_maul::Register(), spell_arcatraz_soul_steal_aura::Register(), spell_botanica_call_of_the_falcon_aura::Register(), spell_alar_dive_bomb::Register(), spell_astromancer_solarian_transform::Register(), spell_q10563_q10596_to_legion_hold_aura::Register(), spell_dk_master_of_ghouls::Register(), spell_dk_dancing_rune_weapon_visual::Register(), spell_dk_pet_scaling::Register(), spell_dk_anti_magic_shell_self::Register(), spell_dk_army_of_the_dead_passive::Register(), spell_dru_treant_scaling::Register(), spell_gen_model_visible::Register(), spell_gen_have_item_auras::Register(), spell_pet_hit_expertise_scalling::Register(), spell_gen_baby_murloc_passive::Register(), spell_gen_baby_murloc::Register(), spell_gen_visual_dummy_stun::Register(), spell_gen_feign_death_all_flags::Register(), spell_gen_feign_death_no_dyn_flag::Register(), spell_gen_feign_death_no_prevent_emotes::Register(), spell_gen_clone_weapon_aura::Register(), spell_gen_damage_reduction_aura::Register(), spell_gen_tournament_pennant::Register(), spell_gen_prevent_emotes::Register(), spell_gen_shriveling_gaze::Register(), spell_gen_choking_vines::Register(), spell_pet_intellect_spirit_resilience_scaling::Register(), spell_pet_spellhit_expertise_spellpen_scaling::Register(), spell_gen_food_heart_emote::Register(), spell_hun_taming_the_beast::Register(), spell_item_with_mount_speed::Register(), spell_item_shifting_naaru_silver::Register(), spell_item_party_time::Register(), spell_item_multiphase_goggles::Register(), spell_mage_mirror_image::Register(), spell_mage_pet_scaling::Register(), spell_pal_avenging_wrath::Register(), spell_pri_shadowfiend_scaling::Register(), spell_pri_renew::Register(), spell_q11065_wrangle_some_aether_rays_aura::Register(), spell_q10525_vision_guide::Register(), spell_q11322_q11317_the_cleansing::Register(), spell_q10769_dissension_amongst_the_ranks_aura::Register(), spell_quest_test_flight_charging::Register(), spell_q11396_11399_force_shield_arcane_purple_x3::Register(), spell_sha_feral_spirit_scaling::Register(), spell_sha_fire_elemental_scaling::Register(), spell_sha_earthbind_totem::Register(), spell_warl_eye_of_kilrogg::Register(), spell_warl_seduction::Register(), spell_warl_infernal_scaling::Register(), spell_warl_demonic_circle_teleport::Register(), spell_warl_health_funnel::Register(), spell_warl_glyph_of_felguard::Register(), spell_warl_glyph_of_voidwalker::Register(), and spell_warr_vigilance::Register().
OnEffectManaShield
HookList<EffectManaShieldHandler> AuraScript::OnEffectManaShield
OnEffectPeriodic
HookList<EffectPeriodicHandler> AuraScript::OnEffectPeriodic
Referenced by aura_class_call_wild_magic::Register(), aura_class_call_siphon_blessing::Register(), spell_geddon_inferno_aura::Register(), spell_garr_separation_anxiety_aura::Register(), spell_majordomo_separation_anxiety_aura::Register(), spell_karazhan_brittle_bones_aura::Register(), spell_karazhan_overload_aura::Register(), spell_apothecary_perfume_spill::Register(), spell_apothecary_cologne_spill::Register(), spell_shadowfang_keep_haunting_spirits_aura::Register(), spell_shadowfang_keep_forsaken_skills_aura::Register(), spell_eredar_twins_handle_touch_periodic::Register(), spell_kalecgos_curse_of_boundless_agony_aura::Register(), spell_kiljaeden_shadow_spike_aura::Register(), spell_kiljaeden_armageddon_periodic_aura::Register(), spell_muru_summon_blood_elves_periodic_aura::Register(), spell_muru_darkness_aura::Register(), spell_entropius_negative_energy_periodic::Register(), spell_claw_rage_aura::Register(), spell_alert_drums::Register(), spell_brewfest_main_ram_buff::Register(), spell_brewfest_ram_fatigue::Register(), spell_send_mug_control_aura::Register(), spell_barreled_control_aura::Register(), spell_direbrew_disarm::Register(), spell_love_is_in_the_air_romantic_picnic::Register(), spell_midsummer_ribbon_pole::Register(), spell_item_noblegarden_chocolate::Register(), spell_doomfire::Register(), spell_mark_of_kazrogal_aura::Register(), spell_black_morass_corrupt_medivh::Register(), spell_cthun_digestive_acid::Register(), spell_anubisath_mortal_strike::Register(), spell_mount_check_aura::Register(), spell_shadow_sickle_periodic_damage::Register(), spell_azjol_nerub_carrion_beetles::Register(), spell_hadronox_summon_periodic_aura::Register(), spell_halion_meteor_strike_spread_aura::Register(), spell_halion_combustion_consumption_aura::Register(), spell_halion_twilight_cutter_periodic_aura::Register(), spell_pursuing_spikes_aura::Register(), spell_gen_leeching_swarm_aura::Register(), spell_toc25_mistress_kiss_aura::Register(), spell_valkyr_touch_aura::Register(), spell_valkyr_ball_periodic_dummy_aura::Register(), spell_dred_grievious_bite_aura::Register(), spell_tharon_ja_curse_of_life_aura::Register(), spell_trollgore_corpse_explode_aura::Register(), spell_bronjahm_soulstorm_channel_ooc_aura::Register(), spell_bronjahm_soulstorm_visual_aura::Register(), spell_wailing_souls_periodic_aura::Register(), spell_hor_gunship_cannon_fire_aura::Register(), spell_krick_explosive_barrage_aura::Register(), spell_exploding_orb_auto_grow_aura::Register(), spell_pos_empowered_blizzard_aura::Register(), spell_pos_blight_aura::Register(), spell_pos_glacial_strike_aura::Register(), spell_moorabi_mojo_frenzy_aura::Register(), spell_sladran_grip_of_sladran_aura::Register(), spell_blood_council_shadow_prison_aura::Register(), spell_valanar_kinetic_bomb_aura::Register(), spell_blood_queen_pact_of_the_darkfallen_dmg_aura::Register(), spell_deathbringer_blood_link_aura::Register(), spell_igb_rocket_pack_aura::Register(), spell_igb_explosion_main_aura::Register(), spell_igb_periodic_trigger_with_power_cost_aura::Register(), spell_deathwhisper_mana_barrier_aura::Register(), spell_deathwhisper_dark_reckoning::Register(), spell_putricide_grow_stacker_aura::Register(), spell_putricide_gaseous_bloat_aura::Register(), spell_putricide_mutated_plague_aura::Register(), spell_rotface_unstable_ooze_explosion_suicide_aura::Register(), spell_sindragosa_frost_beacon_aura::Register(), spell_sindragosa_ice_tomb_trap_aura::Register(), spell_sindragosa_soul_preservation_aura::Register(), spell_frostwarden_handler_focus_fire_aura::Register(), spell_the_lich_king_infest_aura::Register(), spell_the_lich_king_soul_reaper_aura::Register(), spell_the_lich_king_vile_spirits_aura::Register(), spell_the_lich_king_lights_favor_aura::Register(), spell_the_lich_king_soul_rip_aura::Register(), spell_dreamwalker_nightmare_cloud_aura::Register(), spell_dreamwalker_mana_void_aura::Register(), spell_dreamwalker_summon_suppresser_aura::Register(), spell_icc_dark_reckoning_aura::Register(), spell_icc_yf_frozen_orb_aura::Register(), spell_icc_yh_volley_aura::Register(), spell_ioc_parachute_ic_aura::Register(), spell_kelthuzad_detonate_mana_aura::Register(), spell_web_wrap_damage::Register(), spell_oculus_ride_ruby_emerald_amber_drake_que_aura::Register(), spell_oculus_soar_aura::Register(), spell_algalon_phase_punch_aura::Register(), spell_algalon_collapse_aura::Register(), spell_algalon_remove_phase_aura::Register(), spell_assembly_rune_of_summoning_aura::Register(), spell_mark_of_the_faceless_periodic_aura::Register(), spell_hodir_biting_cold_main_aura::Register(), spell_hodir_biting_cold_player_aura::Register(), spell_hodir_flash_freeze_aura::Register(), spell_hodir_storm_cloud_aura::Register(), spell_ignis_scorch_aura::Register(), spell_ignis_slag_pot_aura::Register(), spell_kologarn_stone_shout_aura::Register(), spell_mimiron_rapid_burst_aura::Register(), spell_mimiron_p3wx2_laser_barrage_aura::Register(), spell_thorim_lightning_pillar_P2_aura::Register(), spell_thorim_trash_impale_aura::Register(), spell_xt002_gravity_bomb_aura::Register(), spell_yogg_saron_brain_link_aura::Register(), spell_yogg_saron_empowered_aura::Register(), spell_yogg_saron_sanity_well_aura::Register(), spell_ulduar_energy_sap_aura::Register(), spell_ulduar_arachnopod_damaged_aura::Register(), spell_frost_tomb_aura::Register(), spell_voa_overcharge_aura::Register(), spell_optic_link_aura::Register(), spell_destroy_door_seal_aura::Register(), spell_dragonblight_corrosive_spit::Register(), spell_z_check_aura::Register(), spell_q13003_thursting_hodirs_spear_aura::Register(), spell_close_rift_aura::Register(), spell_wintergrasp_hide_small_elementals_aura::Register(), spell_illidan_tear_of_azzinoth_summon_channel_aura::Register(), spell_illidan_demon_transform1_aura::Register(), spell_illidan_demon_transform2_aura::Register(), spell_illidan_cage_trap_stun_aura::Register(), spell_illidari_council_deadly_strike_aura::Register(), spell_mother_shahraz_random_periodic_aura::Register(), spell_mother_shahraz_beam_periodic_aura::Register(), spell_mother_shahraz_saber_lash_aura::Register(), spell_reliquary_of_souls_aura_of_desire_aura::Register(), spell_reliquary_of_souls_aura_of_anger_aura::Register(), spell_teron_gorefiend_spirit_lance::Register(), spell_black_temple_curse_of_the_bleakheart_aura::Register(), spell_black_temple_charge_rage_aura::Register(), spell_black_temple_shadow_inferno_aura::Register(), spell_black_temple_spell_absorption_aura::Register(), spell_black_temple_curse_of_vitality_aura::Register(), spell_black_temple_dementia_aura::Register(), spell_mark_of_kazzak_aura::Register(), spell_karathress_power_of_tidalvess::Register(), spell_karathress_power_of_caribdis::Register(), spell_leotheras_demon_link::Register(), spell_lurker_below_spout::Register(), spell_serpentshrine_cavern_coilfang_water::Register(), spell_rancid_spore_cloud::Register(), spell_summoning_rhyme_aura::Register(), spell_summon_ice_spear_delayer::Register(), spell_ice_spear_control_aura::Register(), spell_spore_cloud::Register(), spell_fungal_decay::Register(), spell_broggok_poison_cloud::Register(), spell_alar_flame_quills::Register(), spell_kaelthas_remote_toy::Register(), spell_kaelthas_burn::Register(), spell_ragin_flames_inferno::Register(), spell_npc22275_crystal_prison_aura::Register(), spell_q10923_evil_draws_near_periodic_aura::Register(), spell_dk_death_and_decay_aura::Register(), spell_dk_pet_scaling::Register(), spell_dk_army_of_the_dead_passive::Register(), spell_pet_hit_expertise_scalling::Register(), spell_gen_periodic_knock_away::Register(), spell_gen_flurry_of_claws::Register(), spell_gen_haunted_aura::Register(), spell_gen_parachute::Register(), spell_gen_turkey_marker::Register(), spell_gen_gryphon_wyvern_mount_check::Register(), spell_gen_whisper_gulch_yogg_saron_whisper::Register(), spell_gen_shriveling_gaze::Register(), spell_gen_curse_of_pain::Register(), spell_pet_intellect_spirit_resilience_scaling::Register(), spell_pet_spellhit_expertise_spellpen_scaling::Register(), spell_hun_generic_scaling::Register(), spell_hun_sniper_training::Register(), spell_item_rocket_chicken::Register(), spell_item_enchanted_broom_periodic::Register(), spell_item_direbrew_remote_aura::Register(), spell_magic_eater_food::Register(), spell_item_eye_of_grillok_aura::Register(), spell_item_fel_mana_potion::Register(), spell_mage_pet_scaling::Register(), spell_quest_test_flight_charging::Register(), spell_q2203_thaumaturgy_channel::Register(), spell_q11010_q11102_q11023_aggro_check_aura::Register(), spell_q11010_q11102_q11023_aggro_burst::Register(), spell_q12730_quenching_mist::Register(), spell_q12619_emblazon_runeblade::Register(), spell_rog_killing_spree_aura::Register(), spell_rog_prey_on_the_weak::Register(), spell_sha_totemic_mastery::Register(), spell_sha_feral_spirit_scaling::Register(), spell_sha_earthbind_totem::Register(), spell_warl_improved_demonic_tactics::Register(), spell_warl_demonic_knowledge::Register(), spell_warl_generic_scaling::Register(), spell_warl_demonic_circle_summon::Register(), spell_warl_drain_soul::Register(), and spell_shadow_bolt_whirl::Register().
OnEffectProc
HookList<EffectProcHandler> AuraScript::OnEffectProc
Referenced by spell_mage_fingers_of_frost_proc_aura::Register(), spell_gyth_chromatic_protection::Register(), spell_karazhan_temptation::Register(), spell_karazhan_wrath_titans_aura::Register(), spell_blood_queen_essence_of_the_blood_queen_aura::Register(), spell_deathbringer_blood_link_aura::Register(), spell_deathbringer_blood_link_blood_beast_aura::Register(), spell_the_lich_king_dark_hunger_aura::Register(), spell_oculus_evasive_maneuvers_aura::Register(), spell_oculus_temporal_rift_aura::Register(), spell_yogg_saron_grim_reprisal_aura::Register(), spell_utgarde_pinnacle_beast_mark::Register(), spell_koralon_meteor_fists_aura::Register(), spell_flame_warder_meteor_fists_aura::Register(), spell_soul_deflection::Register(), spell_mark_of_malice::Register(), spell_reliquary_of_souls_aura_of_desire_aura::Register(), spell_black_temple_consuming_strikes_aura::Register(), spell_ahune_spanky_hands::Register(), spell_dk_wandering_plague_aura::Register(), spell_dk_blood_caked_blade::Register(), spell_dk_dancing_rune_weapon::Register(), spell_dk_blood_gorged::Register(), spell_dk_scent_of_blood::Register(), spell_dru_t10_balance_4p_bonus::Register(), spell_dru_living_seed::Register(), spell_dru_living_seed_proc::Register(), spell_gen_proc_not_self::Register(), spell_gen_adaptive_warding::Register(), spell_gen_moss_covered_feet::Register(), spell_gen_obsidian_armor::Register(), spell_gen_blade_warding::Register(), spell_gen_proc_on_victim::Register(), spell_hun_ascpect_of_the_viper::Register(), spell_hun_improved_mend_pet::Register(), spell_hun_misdirection::Register(), spell_hun_glyph_of_arcane_shot::Register(), spell_hun_lock_and_load::Register(), spell_item_lil_phylactery::Register(), spell_item_trauma::Register(), spell_item_blade_ward_enchant::Register(), spell_item_blood_draining_enchant::Register(), spell_item_healing_trance::Register(), spell_item_aegis_of_preservation::Register(), spell_item_blessing_of_ancient_kings::Register(), spell_item_desperate_defense::Register(), spell_item_fate_rune_of_unsurpassed_vigor::Register(), spell_item_necrotic_touch::Register(), spell_item_unsated_craving::Register(), spell_item_shadows_fate::Register(), spell_item_shadowmourne::Register(), spell_mage_burning_determination::Register(), spell_mage_burnout::Register(), spell_mage_focus_magic::Register(), spell_mage_ignite::Register(), spell_mage_master_of_elements::Register(), spell_pal_seal_of_command_aura::Register(), spell_pal_sacred_shield_base::Register(), spell_pal_blessing_of_sanctuary::Register(), spell_pal_eye_for_an_eye::Register(), spell_pal_seal_of_righteousness::Register(), spell_pri_divine_aegis::Register(), spell_pri_glyph_of_prayer_of_healing::Register(), spell_pri_item_greater_heal_refund::Register(), spell_pri_mana_leech::Register(), spell_pri_vampiric_touch::Register(), spell_pri_t4_4p_bonus::Register(), spell_pri_shadowfiend_death::Register(), spell_rog_blade_flurry::Register(), spell_rog_tricks_of_the_trade::Register(), spell_sha_t10_restoration_4p_bonus::Register(), spell_sha_earth_shield::Register(), spell_sha_item_lightning_shield::Register(), spell_sha_item_lightning_shield_trigger::Register(), spell_sha_item_mana_surge::Register(), spell_sha_item_t10_elemental_2p_bonus::Register(), spell_sha_t8_electrified::Register(), spell_warl_seed_of_corruption_aura::Register(), spell_warl_seed_of_corruption_generic_aura::Register(), spell_warl_siphon_life::Register(), spell_warl_fel_synergy::Register(), spell_warl_glyph_of_shadowflame::Register(), spell_warl_drain_soul::Register(), spell_warl_demonic_pact_aura::Register(), spell_warr_improved_spell_reflection::Register(), spell_warr_damage_shield::Register(), spell_warr_sweeping_strikes::Register(), spell_warr_vigilance::Register(), spell_warr_t3_prot_8p_bonus::Register(), and spell_warr_retaliation::Register().
OnEffectRemove
HookList<EffectApplyHandler> AuraScript::OnEffectRemove
Referenced by spell_midnight_fixate::Register(), spell_flamewreath_aura::Register(), spell_chapter5_light_of_dawn_aura::Register(), spell_scholomance_fixate_aura::Register(), spell_scholomance_boon_of_life_aura::Register(), spell_temple_of_atal_hakkar_hex_of_jammal_an_aura::Register(), spell_felmyst_fog_of_corruption_charm_aura::Register(), spell_kalecgos_spectral_realm_aura::Register(), spell_kiljaeden_darkness_aura::Register(), spell_kiljaeden_vengeance_of_the_blue_flight_aura::Register(), spell_entropius_void_zone_visual_aura::Register(), spell_uldaman_stoned_aura::Register(), spell_threatening_gaze_aura::Register(), spell_marli_transform::Register(), spell_brewfest_main_ram_buff::Register(), spell_brewfest_ram_fatigue::Register(), spell_hallows_end_candy_pirate_costume::Register(), spell_love_in_air_perfume_immune::Register(), spell_pilgrims_bounty_serve_generic::Register(), spell_azgalor_doom_aura::Register(), spell_azjol_nerub_web_wrap_aura::Register(), spell_halion_twilight_phasing_aura::Register(), spell_tharon_ja_dummy_aura::Register(), spell_igb_rocket_pack_aura::Register(), spell_icc_stoneform_aura::Register(), spell_icc_web_wrap_aura::Register(), spell_oculus_evasive_charges_aura::Register(), spell_oculus_rider_aura::Register(), spell_ionar_static_overload::Register(), spell_algalon_phase_punch_aura::Register(), spell_assembly_rune_of_summoning_aura::Register(), spell_ulduar_stone_grip_aura::Register(), spell_xt002_searing_light_spawn_life_spark_aura::Register(), spell_yogg_saron_malady_of_the_mind_aura::Register(), spell_yogg_saron_insane_aura::Register(), spell_ticking_time_bomb_aura::Register(), spell_q12243_fire_upon_the_waters_aura::Register(), spell_dragonblight_flame_fury::Register(), spell_dragonblight_devour_ghoul_periodic::Register(), spell_warhead_fuse_aura::Register(), spell_scourge_disguise_instability::Register(), spell_auchenai_possess::Register(), spell_illidan_shadow_prison_aura::Register(), spell_reliquary_of_souls_aura_of_suffering_aura::Register(), spell_reliquary_of_souls_fixate_aura::Register(), spell_black_template_harpooners_mark_aura::Register(), spell_lurker_below_spout::Register(), spell_magtheridon_shadow_grasp::Register(), spell_magtheridon_shadow_grasp_visual::Register(), spell_burning_maul::Register(), spell_arcatraz_soul_steal_aura::Register(), spell_botanica_call_of_the_falcon_aura::Register(), spell_astromancer_solarian_transform::Register(), spell_kaelthas_flame_strike::Register(), spell_q10190_battery_recharging_blaster_aura::Register(), spell_q10563_q10596_to_legion_hold_aura::Register(), spell_q10930_big_bone_worm_aura::Register(), spell_q10929_fumping_aura::Register(), spell_dk_raise_ally_trigger::Register(), spell_dk_master_of_ghouls::Register(), spell_dk_anti_magic_shell_self::Register(), spell_gen_model_visible::Register(), spell_gen_baby_murloc::Register(), spell_gen_fixate_aura::Register(), spell_gen_visual_dummy_stun::Register(), spell_gen_haunted_aura::Register(), spell_gen_feign_death_all_flags::Register(), spell_gen_feign_death_no_dyn_flag::Register(), spell_gen_feign_death_no_prevent_emotes::Register(), spell_gen_clone_weapon_aura::Register(), spell_gen_damage_reduction_aura::Register(), spell_gen_defend::Register(), spell_gen_on_tournament_mount::Register(), spell_gen_prevent_emotes::Register(), spell_hun_taming_the_beast::Register(), spell_item_with_mount_speed::Register(), spell_item_instant_statue::Register(), spell_item_desperate_defense::Register(), spell_item_multiphase_goggles::Register(), spell_item_bloodsail_admiral_hat::Register(), spell_mage_glyph_of_eternal_water::Register(), spell_pal_divine_intervention::Register(), spell_q11065_wrangle_some_aether_rays_aura::Register(), spell_q11026_a11051_banish_the_demons_aura::Register(), spell_q10769_dissension_amongst_the_ranks_aura::Register(), spell_q11396_11399_force_shield_arcane_purple_x3::Register(), spell_q12937_relief_for_the_fallen::Register(), spell_q9718_crow_transform::Register(), spell_warl_demonic_aegis::Register(), spell_warl_demonic_circle_summon::Register(), spell_warl_haunt_aura::Register(), spell_warl_health_funnel::Register(), spell_warl_drain_soul::Register(), spell_warl_shadowburn::Register(), spell_warl_glyph_of_felguard::Register(), spell_warl_glyph_of_voidwalker::Register(), and spell_warr_vigilance::Register().
OnEffectSplit
HookList<EffectSplitHandler> AuraScript::OnEffectSplit
Referenced by spell_pal_divine_sacrifice::Register(), and spell_pal_hand_of_sacrifice_aura::Register().
OnEffectUpdatePeriodic
HookList<EffectUpdatePeriodicHandler> AuraScript::OnEffectUpdatePeriodic
Referenced by spell_shadowfang_keep_haunting_spirits_aura::Register(), spell_hallows_end_base_fire::Register(), spell_putricide_unbound_plague_dmg_aura::Register(), spell_the_lich_king_infest_aura::Register(), spell_dreamwalker_decay_periodic_timer_aura::Register(), spell_auchenai_possess::Register(), spell_allergies::Register(), spell_dk_chains_of_ice_aura::Register(), spell_gen_bg_preparation::Register(), spell_gen_baby_murloc_passive::Register(), spell_gen_burn_brutallus::Register(), spell_gen_holiday_buff_food::Register(), spell_gen_consume::Register(), spell_gen_food_heart_emote::Register(), spell_hun_sniper_training::Register(), spell_item_goblin_gumbo_kettle::Register(), spell_item_brewfest_hops::Register(), and spell_rog_savage_combat::Register().
OnProc
HookList<AuraProcHandler> AuraScript::OnProc
Referenced by spell_blood_queen_essence_of_the_blood_queen_aura::Register(), spell_dk_bone_shield::Register(), spell_dk_hungering_cold::Register(), spell_gen_proc_on_victim::Register(), spell_pal_eye_for_an_eye::Register(), spell_warl_siphon_life::Register(), spell_warl_fel_synergy::Register(), spell_warr_improved_spell_reflection::Register(), and spell_warr_damage_shield::Register().
The documentation for this class was generated from the following files:
azerothcore-wotlk/src/server/game/Spells/SpellScript.h
azerothcore-wotlk/src/server/game/Spells/SpellScript.cpp