AzerothCore Doxygen
ObjectMgr.cpp File Reference
#include "ObjectMgr.h"
#include "AchievementMgr.h"
#include "ArenaTeamMgr.h"
#include "CharacterCache.h"
#include "Chat.h"
#include "Common.h"
#include "Config.h"
#include "Containers.h"
#include "CreatureAIFactory.h"
#include "DBCStructure.h"
#include "DatabaseEnv.h"
#include "DisableMgr.h"
#include "GameEventMgr.h"
#include "GameObjectAIFactory.h"
#include "GameTime.h"
#include "GossipDef.h"
#include "GroupMgr.h"
#include "GuildMgr.h"
#include "LFGMgr.h"
#include "Log.h"
#include "MapMgr.h"
#include "Pet.h"
#include "PoolMgr.h"
#include "ReputationMgr.h"
#include "ScriptMgr.h"
#include "Spell.h"
#include "SpellMgr.h"
#include "SpellScript.h"
#include "SpellScriptLoader.h"
#include "StringConvert.h"
#include "Tokenize.h"
#include "Transport.h"
#include "Unit.h"
#include "Util.h"
#include "Vehicle.h"
#include "World.h"
#include <boost/algorithm/string.hpp>
#include <numeric>
#include "ItemEnchantmentMgr.h"
Enumerations
enum LanguageType {
LT_BASIC_LATIN = 0x0000 ,
LT_EXTENDEN_LATIN = 0x0001 ,
LT_CYRILLIC = 0x0002 ,
LT_EAST_ASIA = 0x0004 ,
LT_ANY = 0xFFFF
}
Functions
std::string GetScriptsTableNameByType (ScriptsType type)
ScriptMapMap * GetScriptsMapByType (ScriptsType type)
std::string GetScriptCommandName (ScriptCommands command)
bool normalizePlayerName (std::string &name)
LanguageDesc const * GetLanguageDescByID (uint32 lang)
void CheckGOLockId (GameObjectTemplate const *goInfo, uint32 dataN, uint32 N)
void CheckGOLinkedTrapId (GameObjectTemplate const *goInfo, uint32 dataN, uint32 N)
void CheckGOSpellId (GameObjectTemplate const *goInfo, uint32 dataN, uint32 N)
void CheckAndFixGOChairHeightId (GameObjectTemplate const *goInfo, uint32 const &dataN, uint32 N)
void CheckGONoDamageImmuneId (GameObjectTemplate *goTemplate, uint32 dataN, uint32 N)
void CheckGOConsumable (GameObjectTemplate const *goInfo, uint32 dataN, uint32 N)
static LanguageType GetRealmLanguageType (bool create)
bool isValidString (std::wstring wstr, uint32 strictMask, bool numericOrSpace, bool create=false)
SkillRangeType GetSkillRangeType (SkillRaceClassInfoEntry const *rcEntry)
Variables
ScriptMapMap sSpellScripts
ScriptMapMap sEventScripts
ScriptMapMap sWaypointScripts
LanguageDesc lang_description [LANGUAGES_COUNT]
ServerConfigs const qualityToBuyValueConfig [MAX_ITEM_QUALITY]
ServerConfigs const qualityToSellValueConfig [MAX_ITEM_QUALITY]
Enumeration Type Documentation
LanguageType
enum LanguageType
Enumerator
LT_BASIC_LATIN
LT_EXTENDEN_LATIN
LT_CYRILLIC
LT_EAST_ASIA
LT_ANY
{
    LT_BASIC_LATIN    = 0x0000,
    LT_EXTENDEN_LATIN = 0x0001,
    LT_CYRILLIC       = 0x0002,
    LT_EAST_ASIA      = 0x0004,
    LT_ANY            = 0xFFFF
};
Function Documentation
CheckAndFixGOChairHeightId()
void CheckAndFixGOChairHeightId (GameObjectTemplate const * goInfo, uint32 const & dataN, uint32 N) inline
{
    if (dataN <= (UNIT_STAND_STATE_SIT_HIGH_CHAIR - UNIT_STAND_STATE_SIT_LOW_CHAIR))
        return;
    LOG_ERROR("sql.sql", "Gameobject (Entry: {} GoType: {}) have data{}={} but correct chair height in range 0..{}.",
                     goInfo->entry, goInfo->type, N, dataN, UNIT_STAND_STATE_SIT_HIGH_CHAIR - UNIT_STAND_STATE_SIT_LOW_CHAIR);
    // prevent client and server unexpected work
    const_cast<uint32&>(dataN) = 0;
}
References GameObjectTemplate::entry, LOG_ERROR, GameObjectTemplate::type, UNIT_STAND_STATE_SIT_HIGH_CHAIR, and UNIT_STAND_STATE_SIT_LOW_CHAIR.
Referenced by ObjectMgr::LoadGameObjectTemplate().
CheckGOConsumable()
void CheckGOConsumable (GameObjectTemplate const * goInfo, uint32 dataN, uint32 N) inline
{
    // 0/1 correct values
    if (dataN <= 1)
        return;
    LOG_ERROR("sql.sql", "Gameobject (Entry: {} GoType: {}) have data{}={} but expected boolean (0/1) consumable field value.",
                     goInfo->entry, goInfo->type, N, dataN);
}
References GameObjectTemplate::entry, LOG_ERROR, and GameObjectTemplate::type.
Referenced by ObjectMgr::LoadGameObjectTemplate().
CheckGOLinkedTrapId()
void CheckGOLinkedTrapId (GameObjectTemplate const * goInfo, uint32 dataN, uint32 N) inline
{
    if (GameObjectTemplate const* trapInfo = sObjectMgr->GetGameObjectTemplate(dataN))
    {
        if (trapInfo->type != GAMEOBJECT_TYPE_TRAP)
            LOG_ERROR("sql.sql", "Gameobject (Entry: {} GoType: {}) have data{}={} but GO (Entry {}) have not GAMEOBJECT_TYPE_TRAP ({}) type.",
                             goInfo->entry, goInfo->type, N, dataN, dataN, GAMEOBJECT_TYPE_TRAP);
    }
}
References GameObjectTemplate::entry, GAMEOBJECT_TYPE_TRAP, LOG_ERROR, sObjectMgr, and GameObjectTemplate::type.
Referenced by ObjectMgr::LoadGameObjectTemplate().
CheckGOLockId()
void CheckGOLockId (GameObjectTemplate const * goInfo, uint32 dataN, uint32 N) inline
{
    if (sLockStore.LookupEntry(dataN))
        return;
    LOG_ERROR("sql.sql", "Gameobject (Entry: {} GoType: {}) have data{}={} but lock (Id: {}) not found.",
                     goInfo->entry, goInfo->type, N, goInfo->door.lockId, goInfo->door.lockId);
}
References GameObjectTemplate::door, GameObjectTemplate::entry, GameObjectTemplate::lockId, LOG_ERROR, sLockStore, and GameObjectTemplate::type.
Referenced by ObjectMgr::LoadGameObjectTemplate().
CheckGONoDamageImmuneId()
void CheckGONoDamageImmuneId (GameObjectTemplate * goTemplate, uint32 dataN, uint32 N) inline
{
    // 0/1 correct values
    if (dataN <= 1)
        return;
    LOG_ERROR("sql.sql", "Gameobject (Entry: {} GoType: {}) have data{}={} but expected boolean (0/1) noDamageImmune field value.", goTemplate->entry, goTemplate->type, N, dataN);
}
References GameObjectTemplate::entry, LOG_ERROR, and GameObjectTemplate::type.
Referenced by ObjectMgr::LoadGameObjectTemplate().
CheckGOSpellId()
void CheckGOSpellId (GameObjectTemplate const * goInfo, uint32 dataN, uint32 N) inline
{
    if (sSpellMgr->GetSpellInfo(dataN))
        return;
    LOG_ERROR("sql.sql", "Gameobject (Entry: {} GoType: {}) have data{}={} but Spell (Entry {}) not exist.",
                     goInfo->entry, goInfo->type, N, dataN, dataN);
}
References GameObjectTemplate::entry, LOG_ERROR, sSpellMgr, and GameObjectTemplate::type.
Referenced by ObjectMgr::LoadGameObjectTemplate().
GetLanguageDescByID()
LanguageDesc const * GetLanguageDescByID (uint32 lang)
{
    for (uint8 i = 0; i < LANGUAGES_COUNT; ++i)
    {
        if (uint32(lang_description[i].lang_id) == lang)
            return &lang_description[i];
    }
    return nullptr;
}
References lang_description, and LANGUAGES_COUNT.
Referenced by WorldSession::HandleMessagechatOpcode(), ObjectMgr::LoadBroadcastTexts(), and CreatureTextMgr::LoadCreatureTexts().
GetRealmLanguageType()
static LanguageType GetRealmLanguageType (bool create) static
{
    switch (sWorld->getIntConfig(CONFIG_REALM_ZONE))
    {
        case REALM_ZONE_UNKNOWN:                            // any language
        case REALM_ZONE_DEVELOPMENT:
        case REALM_ZONE_TEST_SERVER:
        case REALM_ZONE_QA_SERVER:
            return LT_ANY;
        case REALM_ZONE_UNITED_STATES:                      // extended-Latin
        case REALM_ZONE_OCEANIC:
        case REALM_ZONE_LATIN_AMERICA:
        case REALM_ZONE_ENGLISH:
        case REALM_ZONE_GERMAN:
        case REALM_ZONE_FRENCH:
        case REALM_ZONE_SPANISH:
            return LT_EXTENDEN_LATIN;
        case REALM_ZONE_KOREA:                              // East-Asian
        case REALM_ZONE_TAIWAN:
        case REALM_ZONE_CHINA:
            return LT_EAST_ASIA;
        case REALM_ZONE_RUSSIAN:                            // Cyrillic
            return LT_CYRILLIC;
        default:
            return create ? LT_BASIC_LATIN : LT_ANY;        // basic-Latin at create, any at login
    }
}
References CONFIG_REALM_ZONE, LT_ANY, LT_BASIC_LATIN, LT_CYRILLIC, LT_EAST_ASIA, LT_EXTENDEN_LATIN, REALM_ZONE_CHINA, REALM_ZONE_DEVELOPMENT, REALM_ZONE_ENGLISH, REALM_ZONE_FRENCH, REALM_ZONE_GERMAN, REALM_ZONE_KOREA, REALM_ZONE_LATIN_AMERICA, REALM_ZONE_OCEANIC, REALM_ZONE_QA_SERVER, REALM_ZONE_RUSSIAN, REALM_ZONE_SPANISH, REALM_ZONE_TAIWAN, REALM_ZONE_TEST_SERVER, REALM_ZONE_UNITED_STATES, REALM_ZONE_UNKNOWN, and sWorld.
Referenced by isValidString().
GetScriptCommandName()
std::string GetScriptCommandName (ScriptCommands command)
{
    std::string res = "";
    switch (command)
    {
        case SCRIPT_COMMAND_TALK:
            res = "SCRIPT_COMMAND_TALK";
            break;
        case SCRIPT_COMMAND_EMOTE:
            res = "SCRIPT_COMMAND_EMOTE";
            break;
        case SCRIPT_COMMAND_FIELD_SET:
            res = "SCRIPT_COMMAND_FIELD_SET";
            break;
        case SCRIPT_COMMAND_MOVE_TO:
            res = "SCRIPT_COMMAND_MOVE_TO";
            break;
        case SCRIPT_COMMAND_FLAG_SET:
            res = "SCRIPT_COMMAND_FLAG_SET";
            break;
        case SCRIPT_COMMAND_FLAG_REMOVE:
            res = "SCRIPT_COMMAND_FLAG_REMOVE";
            break;
        case SCRIPT_COMMAND_TELEPORT_TO:
            res = "SCRIPT_COMMAND_TELEPORT_TO";
            break;
        case SCRIPT_COMMAND_QUEST_EXPLORED:
            res = "SCRIPT_COMMAND_QUEST_EXPLORED";
            break;
        case SCRIPT_COMMAND_KILL_CREDIT:
            res = "SCRIPT_COMMAND_KILL_CREDIT";
            break;
        case SCRIPT_COMMAND_RESPAWN_GAMEOBJECT:
            res = "SCRIPT_COMMAND_RESPAWN_GAMEOBJECT";
            break;
        case SCRIPT_COMMAND_TEMP_SUMMON_CREATURE:
            res = "SCRIPT_COMMAND_TEMP_SUMMON_CREATURE";
            break;
        case SCRIPT_COMMAND_OPEN_DOOR:
            res = "SCRIPT_COMMAND_OPEN_DOOR";
            break;
        case SCRIPT_COMMAND_CLOSE_DOOR:
            res = "SCRIPT_COMMAND_CLOSE_DOOR";
            break;
        case SCRIPT_COMMAND_ACTIVATE_OBJECT:
            res = "SCRIPT_COMMAND_ACTIVATE_OBJECT";
            break;
        case SCRIPT_COMMAND_REMOVE_AURA:
            res = "SCRIPT_COMMAND_REMOVE_AURA";
            break;
        case SCRIPT_COMMAND_CAST_SPELL:
            res = "SCRIPT_COMMAND_CAST_SPELL";
            break;
        case SCRIPT_COMMAND_PLAY_SOUND:
            res = "SCRIPT_COMMAND_PLAY_SOUND";
            break;
        case SCRIPT_COMMAND_CREATE_ITEM:
            res = "SCRIPT_COMMAND_CREATE_ITEM";
            break;
        case SCRIPT_COMMAND_DESPAWN_SELF:
            res = "SCRIPT_COMMAND_DESPAWN_SELF";
            break;
        case SCRIPT_COMMAND_LOAD_PATH:
            res = "SCRIPT_COMMAND_LOAD_PATH";
            break;
        case SCRIPT_COMMAND_CALLSCRIPT_TO_UNIT:
            res = "SCRIPT_COMMAND_CALLSCRIPT_TO_UNIT";
            break;
        case SCRIPT_COMMAND_KILL:
            res = "SCRIPT_COMMAND_KILL";
            break;
        // AzerothCore only
        case SCRIPT_COMMAND_ORIENTATION:
            res = "SCRIPT_COMMAND_ORIENTATION";
            break;
        case SCRIPT_COMMAND_EQUIP:
            res = "SCRIPT_COMMAND_EQUIP";
            break;
        case SCRIPT_COMMAND_MODEL:
            res = "SCRIPT_COMMAND_MODEL";
            break;
        case SCRIPT_COMMAND_CLOSE_GOSSIP:
            res = "SCRIPT_COMMAND_CLOSE_GOSSIP";
            break;
        case SCRIPT_COMMAND_PLAYMOVIE:
            res = "SCRIPT_COMMAND_PLAYMOVIE";
            break;
        default:
            {
                char sz[32];
                snprintf(sz, sizeof(sz), "Unknown command: %d", command);
                res = sz;
                break;
            }
    }
    return res;
}
References SCRIPT_COMMAND_ACTIVATE_OBJECT, SCRIPT_COMMAND_CALLSCRIPT_TO_UNIT, SCRIPT_COMMAND_CAST_SPELL, SCRIPT_COMMAND_CLOSE_DOOR, SCRIPT_COMMAND_CLOSE_GOSSIP, SCRIPT_COMMAND_CREATE_ITEM, SCRIPT_COMMAND_DESPAWN_SELF, SCRIPT_COMMAND_EMOTE, SCRIPT_COMMAND_EQUIP, SCRIPT_COMMAND_FIELD_SET, SCRIPT_COMMAND_FLAG_REMOVE, SCRIPT_COMMAND_FLAG_SET, SCRIPT_COMMAND_KILL, SCRIPT_COMMAND_KILL_CREDIT, SCRIPT_COMMAND_LOAD_PATH, SCRIPT_COMMAND_MODEL, SCRIPT_COMMAND_MOVE_TO, SCRIPT_COMMAND_OPEN_DOOR, SCRIPT_COMMAND_ORIENTATION, SCRIPT_COMMAND_PLAY_SOUND, SCRIPT_COMMAND_PLAYMOVIE, SCRIPT_COMMAND_QUEST_EXPLORED, SCRIPT_COMMAND_REMOVE_AURA, SCRIPT_COMMAND_RESPAWN_GAMEOBJECT, SCRIPT_COMMAND_TALK, SCRIPT_COMMAND_TELEPORT_TO, and SCRIPT_COMMAND_TEMP_SUMMON_CREATURE.
Referenced by ScriptInfo::GetDebugInfo(), and ObjectMgr::LoadScripts().
GetScriptsMapByType()
ScriptMapMap * GetScriptsMapByType (ScriptsType type)
{
    ScriptMapMap* res = nullptr;
    switch (type)
    {
        case SCRIPTS_SPELL:
            res = &sSpellScripts;
            break;
        case SCRIPTS_EVENT:
            res = &sEventScripts;
            break;
        case SCRIPTS_WAYPOINT:
            res = &sWaypointScripts;
            break;
        default:
            break;
    }
    return res;
}
References SCRIPTS_EVENT, SCRIPTS_SPELL, SCRIPTS_WAYPOINT, sEventScripts, sSpellScripts, and sWaypointScripts.
Referenced by ObjectMgr::LoadScripts(), and Map::ScriptsProcess().
GetScriptsTableNameByType()
std::string GetScriptsTableNameByType (ScriptsType type)
{
    std::string res = "";
    switch (type)
    {
        case SCRIPTS_SPELL:
            res = "spell_scripts";
            break;
        case SCRIPTS_EVENT:
            res = "event_scripts";
            break;
        case SCRIPTS_WAYPOINT:
            res = "waypoint_scripts";
            break;
        default:
            break;
    }
    return res;
}
References SCRIPTS_EVENT, SCRIPTS_SPELL, and SCRIPTS_WAYPOINT.
Referenced by ScriptInfo::GetDebugInfo(), and ObjectMgr::LoadScripts().
GetSkillRangeType()
SkillRangeType GetSkillRangeType (SkillRaceClassInfoEntry const * rcEntry)
{
    SkillLineEntry const* skill = sSkillLineStore.LookupEntry(rcEntry->SkillID);
    if (!skill)
    {
        return SKILL_RANGE_NONE;
    }
    if (sSkillTiersStore.LookupEntry(rcEntry->SkillTierID))
    {
        return SKILL_RANGE_RANK;
    }
    if (rcEntry->SkillID == SKILL_RUNEFORGING)
    {
        return SKILL_RANGE_MONO;
    }
    switch (skill->categoryId)
    {
        case SKILL_CATEGORY_ARMOR:
            return SKILL_RANGE_MONO;
        case SKILL_CATEGORY_LANGUAGES:
            return SKILL_RANGE_LANGUAGE;
    }
    return SKILL_RANGE_LEVEL;
}
References SkillLineEntry::categoryId, SKILL_CATEGORY_ARMOR, SKILL_CATEGORY_LANGUAGES, SKILL_RANGE_LANGUAGE, SKILL_RANGE_LEVEL, SKILL_RANGE_MONO, SKILL_RANGE_NONE, SKILL_RANGE_RANK, SKILL_RUNEFORGING, SkillRaceClassInfoEntry::SkillID, SkillRaceClassInfoEntry::SkillTierID, sSkillLineStore, and sSkillTiersStore.
Referenced by Player::_LoadSkills(), Player::LearnDefaultSkill(), and Player::UpdateSkillsForLevel().
isValidString()
bool isValidString (std::wstring wstr, uint32 strictMask, bool numericOrSpace, bool create = false)
{
    if (strictMask == 0)                                       // any language, ignore realm
    {
        if (isExtendedLatinString(wstr, numericOrSpace))
            return true;
        if (isCyrillicString(wstr, numericOrSpace))
            return true;
        if (isEastAsianString(wstr, numericOrSpace))
            return true;
        return false;
    }
    if (strictMask & 0x2)                                    // realm zone specific
    {
        LanguageType lt = GetRealmLanguageType(create);
        if (lt & LT_EXTENDEN_LATIN)
            if (isExtendedLatinString(wstr, numericOrSpace))
                return true;
        if (lt & LT_CYRILLIC)
            if (isCyrillicString(wstr, numericOrSpace))
                return true;
        if (lt & LT_EAST_ASIA)
            if (isEastAsianString(wstr, numericOrSpace))
                return true;
    }
    if (strictMask & 0x1)                                    // basic Latin
    {
        if (isBasicLatinString(wstr, numericOrSpace))
            return true;
    }
    return false;
}
References GetRealmLanguageType(), isBasicLatinString(), isCyrillicString(), isEastAsianString(), isExtendedLatinString(), LT_CYRILLIC, LT_EAST_ASIA, and LT_EXTENDEN_LATIN.
Referenced by ObjectMgr::CheckPetName(), ObjectMgr::CheckPlayerName(), ObjectMgr::IsValidChannelName(), and ObjectMgr::IsValidCharterName().
normalizePlayerName()
bool normalizePlayerName (std::string & name)
{
    if (name.empty())
        return false;
    if (name.find(" ") != std::string::npos)
        return false;
    std::wstring tmp;
    if (!Utf8toWStr(name, tmp))
        return false;
    wstrToLower(tmp);
    if (!tmp.empty())
        tmp[0] = wcharToUpper(tmp[0]);
    if (!WStrToUtf8(tmp, name))
        return false;
    return true;
}
References Utf8toWStr(), wcharToUpper(), wstrToLower(), and WStrToUtf8().
Referenced by ChatHandler::extractLowGuidFromLink(), ChatHandler::extractPlayerNameFromLink(), PlayerNameMapHolder::Find(), character_commandscript::GetDeletedCharacterInfoList(), ChatHandler::GetPlayerGroupAndGUIDByName(), WorldSession::HandleAddFriendOpcode(), WorldSession::HandleAddIgnoreOpcode(), WorldSession::HandleArenaTeamInviteOpcode(), WorldSession::HandleArenaTeamLeaderOpcode(), WorldSession::HandleArenaTeamRemoveOpcode(), ban_commandscript::HandleBanCharacterCommand(), ban_commandscript::HandleBanHelper(), WorldSession::HandleChannelBan(), WorldSession::HandleChannelInvite(), WorldSession::HandleChannelKick(), WorldSession::HandleChannelModerator(), WorldSession::HandleChannelMute(), WorldSession::HandleChannelSetOwner(), WorldSession::HandleChannelUnban(), WorldSession::HandleChannelUnmoderator(), WorldSession::HandleChannelUnmute(), character_commandscript::HandleCharacterRenameCommand(), WorldSession::HandleCharCreateOpcode(), WorldSession::HandleCharCustomizeCallback(), WorldSession::HandleCharFactionOrRaceChangeCallback(), WorldSession::HandleCharRenameOpcode(), deserter_commandscript::HandleDeserterAdd(), ticket_commandscript::HandleGMTicketAssignToCommand(), ticket_commandscript::HandleGMTicketGetByNameCommand(), WorldSession::HandleGroupInviteOpcode(), WorldSession::HandleGroupSwapSubGroupOpcode(), WorldSession::HandleGroupUninviteOpcode(), WorldSession::HandleGuildDemoteOpcode(), WorldSession::HandleGuildInviteOpcode(), WorldSession::HandleGuildLeaderOpcode(), WorldSession::HandleGuildPromoteOpcode(), WorldSession::HandleGuildRemoveOpcode(), WorldSession::HandleGuildSetOfficerNoteOpcode(), WorldSession::HandleGuildSetPublicNoteOpcode(), WorldSession::HandleMessagechatOpcode(), WorldSession::HandleSendMail(), WorldSession::HandleSetPlayerDeclinedNames(), ban_commandscript::HandleUnBanCharacterCommand(), ban_commandscript::HandleUnBanHelper(), message_commandscript::HandleWhispersCommand(), WorldSession::HandleWhoisOpcode(), PlayerDumpReader::LoadDump(), Acore::ChatCommands::PlayerIdentifier::TryConsume(), and character_commandscript::ValidatePDumpTarget().
Variable Documentation
lang_description
LanguageDesc lang_description[LANGUAGES_COUNT]
Initial value:
=
{
    { LANG_ADDON,           0, 0                       },
    { LANG_UNIVERSAL,       0, 0                       },
    { LANG_ORCISH,        669, SKILL_LANG_ORCISH       },
    { LANG_DARNASSIAN,    671, SKILL_LANG_DARNASSIAN   },
    { LANG_TAURAHE,       670, SKILL_LANG_TAURAHE      },
    { LANG_DWARVISH,      672, SKILL_LANG_DWARVEN      },
    { LANG_COMMON,        668, SKILL_LANG_COMMON       },
    { LANG_DEMONIC,       815, SKILL_LANG_DEMON_TONGUE },
    { LANG_TITAN,         816, SKILL_LANG_TITAN        },
    { LANG_THALASSIAN,    813, SKILL_LANG_THALASSIAN   },
    { LANG_DRACONIC,      814, SKILL_LANG_DRACONIC     },
    { LANG_KALIMAG,       817, SKILL_LANG_OLD_TONGUE   },
    { LANG_GNOMISH,      7340, SKILL_LANG_GNOMISH      },
    { LANG_TROLL,        7341, SKILL_LANG_TROLL        },
    { LANG_GUTTERSPEAK, 17737, SKILL_LANG_GUTTERSPEAK  },
    { LANG_DRAENEI,     29932, SKILL_LANG_DRAENEI      },
    { LANG_ZOMBIE,          0, 0                       },
    { LANG_GNOMISH_BINARY,  0, 0                       },
    { LANG_GOBLIN_BINARY,   0, 0                       }
}
{
    { LANG_ADDON,           0, 0                       },
    { LANG_UNIVERSAL,       0, 0                       },
    { LANG_ORCISH,        669, SKILL_LANG_ORCISH       },
    { LANG_DARNASSIAN,    671, SKILL_LANG_DARNASSIAN   },
    { LANG_TAURAHE,       670, SKILL_LANG_TAURAHE      },
    { LANG_DWARVISH,      672, SKILL_LANG_DWARVEN      },
    { LANG_COMMON,        668, SKILL_LANG_COMMON       },
    { LANG_DEMONIC,       815, SKILL_LANG_DEMON_TONGUE },
    { LANG_TITAN,         816, SKILL_LANG_TITAN        },
    { LANG_THALASSIAN,    813, SKILL_LANG_THALASSIAN   },
    { LANG_DRACONIC,      814, SKILL_LANG_DRACONIC     },
    { LANG_KALIMAG,       817, SKILL_LANG_OLD_TONGUE   },
    { LANG_GNOMISH,      7340, SKILL_LANG_GNOMISH      },
    { LANG_TROLL,        7341, SKILL_LANG_TROLL        },
    { LANG_GUTTERSPEAK, 17737, SKILL_LANG_GUTTERSPEAK  },
    { LANG_DRAENEI,     29932, SKILL_LANG_DRAENEI      },
    { LANG_ZOMBIE,          0, 0                       },
    { LANG_GNOMISH_BINARY,  0, 0                       },
    { LANG_GOBLIN_BINARY,   0, 0                       }
};
Referenced by GetLanguageDescByID(), and learn_commandscript::HandleLearnAllLangCommand().
qualityToBuyValueConfig
ServerConfigs const qualityToBuyValueConfig[MAX_ITEM_QUALITY]
Initial value:
=
{
    RATE_BUYVALUE_ITEM_POOR,
    RATE_BUYVALUE_ITEM_NORMAL,
    RATE_BUYVALUE_ITEM_UNCOMMON,
    RATE_BUYVALUE_ITEM_RARE,
    RATE_BUYVALUE_ITEM_EPIC,
    RATE_BUYVALUE_ITEM_LEGENDARY,
    RATE_BUYVALUE_ITEM_ARTIFACT,
    RATE_BUYVALUE_ITEM_HEIRLOOM,
}
{
    RATE_BUYVALUE_ITEM_POOR,                                    // ITEM_QUALITY_POOR
    RATE_BUYVALUE_ITEM_NORMAL,                                  // ITEM_QUALITY_NORMAL
    RATE_BUYVALUE_ITEM_UNCOMMON,                                // ITEM_QUALITY_UNCOMMON
    RATE_BUYVALUE_ITEM_RARE,                                    // ITEM_QUALITY_RARE
    RATE_BUYVALUE_ITEM_EPIC,                                    // ITEM_QUALITY_EPIC
    RATE_BUYVALUE_ITEM_LEGENDARY,                               // ITEM_QUALITY_LEGENDARY
    RATE_BUYVALUE_ITEM_ARTIFACT,                                // ITEM_QUALITY_ARTIFACT
    RATE_BUYVALUE_ITEM_HEIRLOOM,                                // ITEM_QUALITY_HEIRLOOM
};
Referenced by ObjectMgr::LoadItemTemplates().
qualityToSellValueConfig
ServerConfigs const qualityToSellValueConfig[MAX_ITEM_QUALITY]
Initial value:
=
{
    RATE_SELLVALUE_ITEM_POOR,
    RATE_SELLVALUE_ITEM_NORMAL,
    RATE_SELLVALUE_ITEM_UNCOMMON,
    RATE_SELLVALUE_ITEM_RARE,
    RATE_SELLVALUE_ITEM_EPIC,
    RATE_SELLVALUE_ITEM_LEGENDARY,
    RATE_SELLVALUE_ITEM_ARTIFACT,
    RATE_SELLVALUE_ITEM_HEIRLOOM,
}
{
    RATE_SELLVALUE_ITEM_POOR,                                   // ITEM_QUALITY_POOR
    RATE_SELLVALUE_ITEM_NORMAL,                                 // ITEM_QUALITY_NORMAL
    RATE_SELLVALUE_ITEM_UNCOMMON,                               // ITEM_QUALITY_UNCOMMON
    RATE_SELLVALUE_ITEM_RARE,                                   // ITEM_QUALITY_RARE
    RATE_SELLVALUE_ITEM_EPIC,                                   // ITEM_QUALITY_EPIC
    RATE_SELLVALUE_ITEM_LEGENDARY,                              // ITEM_QUALITY_LEGENDARY
    RATE_SELLVALUE_ITEM_ARTIFACT,                               // ITEM_QUALITY_ARTIFACT
    RATE_SELLVALUE_ITEM_HEIRLOOM,                               // ITEM_QUALITY_HEIRLOOM
};
Referenced by ObjectMgr::LoadItemTemplates().
sEventScripts
ScriptMapMap sEventScripts
Referenced by MotionTransport::DoEventIfAny(), FlightPathMovementGenerator::DoEventIfAny(), WorldSession::DoLootRelease(), Spell::EffectSendEvent(), GetScriptsMapByType(), ObjectMgr::LoadEventScripts(), and GameObject::Use().
sSpellScripts
ScriptMapMap sSpellScripts
Referenced by Spell::EffectDummy(), Spell::EffectScriptEffect(), GetScriptsMapByType(), and ObjectMgr::LoadSpellScripts().
sWaypointScripts
ScriptMapMap sWaypointScripts
Referenced by GetScriptsMapByType(), ObjectMgr::LoadWaypointScripts(), and WaypointMovementGenerator< Creature >::OnArrived().