AzerothCore Doxygen
CombatReference Struct Reference
#include "CombatManager.h"
Public Member Functions
Unit * GetOther (Unit const *me) const
void EndCombat ()
void SuppressFor (Unit *who)
bool IsSuppressedFor (Unit const *who) const
CombatReference (CombatReference const &)=delete
CombatReference & operator= (CombatReference const &)=delete
Public Attributes
Unit *const first
Unit *const second
bool const _isPvP
Protected Member Functions
CombatReference (Unit *a, Unit *b, bool pvp=false)
void Refresh ()
void Suppress (Unit *who)
Protected Attributes
bool _suppressFirst = false
bool _suppressSecond = false
Friends
class CombatManager
Detailed Description
Constructor & Destructor Documentation
CombatReference() [1/2]
CombatReference::CombatReference (CombatReference const &) delete
CombatReference() [2/2]
CombatReference::CombatReference (Unit * a, Unit * b, bool pvp = false) inline protected
: first(a), second(b), _isPvP(pvp) { }
Member Function Documentation
EndCombat()
void CombatReference::EndCombat ()
{
    // sequencing matters here - AI might do nasty stuff, so make sure refs are in a consistent state before you hand off!
    // first, get rid of any threat that still exists...
    first->GetThreatMgr().ClearThreat(second);
    second->GetThreatMgr().ClearThreat(first);
    // ...then, remove the references from both managers...
    first->GetCombatManager().PurgeReference(second->GetGUID(), _isPvP);
    second->GetCombatManager().PurgeReference(first->GetGUID(), _isPvP);
    // ...update the combat state, which will potentially remove IN_COMBAT...
    bool const needFirstAI = first->GetCombatManager().UpdateOwnerCombatState();
    bool const needSecondAI = second->GetCombatManager().UpdateOwnerCombatState();
    // ...and if that happened, also notify the AI of it...
    if (needFirstAI)
        if (UnitAI* firstAI = first->GetAI())
            firstAI->JustExitedCombat();
    if (needSecondAI)
        if (UnitAI* secondAI = second->GetAI())
            secondAI->JustExitedCombat();
    // ...and finally clean up the reference object
    delete this;
}
References _isPvP, ThreatManager::ClearThreat(), first, Unit::GetAI(), Unit::GetCombatManager(), Object::GetGUID(), Unit::GetThreatMgr(), CombatManager::PurgeReference(), second, and CombatManager::UpdateOwnerCombatState().
Referenced by CombatManager::EndCombatBeyondRange(), CombatManager::RevalidateCombat(), and CombatManager::Update().
GetOther()
Unit * CombatReference::GetOther (Unit const * me) const inline
{ return (first == me) ? second : first; }
Referenced by CombatManager::RevalidateCombat().
IsSuppressedFor()
bool CombatReference::IsSuppressedFor (Unit const * who) const inline
{ return (who == first) ? _suppressFirst : _suppressSecond; }
operator=()
CombatReference & CombatReference::operator= (CombatReference const &) delete
Refresh()
void CombatReference::Refresh () protected
{
    bool needFirstAI = false, needSecondAI = false;
    if (_suppressFirst)
    {
        _suppressFirst = false;
        needFirstAI = first->GetCombatManager().UpdateOwnerCombatState();
    }
    if (_suppressSecond)
    {
        _suppressSecond = false;
        needSecondAI = second->GetCombatManager().UpdateOwnerCombatState();
    }
    if (needFirstAI)
        CombatManager::NotifyAICombat(first, second);
    if (needSecondAI)
        CombatManager::NotifyAICombat(second, first);
}
References _suppressFirst, _suppressSecond, first, Unit::GetCombatManager(), CombatManager::NotifyAICombat(), second, and CombatManager::UpdateOwnerCombatState().
Suppress()
void CombatReference::Suppress (Unit * who) inline protected
{ (who == first ? _suppressFirst : _suppressSecond) = true; }
Referenced by CombatManager::SetInCombatWith(), and SuppressFor().
SuppressFor()
void CombatReference::SuppressFor (Unit * who)
{
    Suppress(who);
    if (who->GetCombatManager().UpdateOwnerCombatState())
        if (UnitAI* ai = who->GetAI())
            ai->JustExitedCombat();
}
References Unit::GetAI(), Unit::GetCombatManager(), Suppress(), and CombatManager::UpdateOwnerCombatState().
Friends And Related Symbol Documentation
CombatManager
friend class CombatManager friend
Member Data Documentation
_isPvP
bool const CombatReference::_isPvP
Referenced by EndCombat(), and CombatManager::PutReference().
_suppressFirst
bool CombatReference::_suppressFirst = false protected
Referenced by Refresh().
_suppressSecond
bool CombatReference::_suppressSecond = false protected
Referenced by Refresh().
first
Unit* const CombatReference::first
Referenced by EndCombat(), CombatManager::EndCombatBeyondRange(), Refresh(), and CombatManager::Update().
second
Unit* const CombatReference::second
Referenced by EndCombat(), CombatManager::EndCombatBeyondRange(), Refresh(), CombatManager::RevalidateCombat(), and CombatManager::Update().
The documentation for this struct was generated from the following files:
azerothcore-wotlk/src/server/game/Combat/CombatManager.h
azerothcore-wotlk/src/server/game/Combat/CombatManager.cpp