AzerothCore Doxygen
boss_lady_deathwhisper.cpp File Reference
#include "AreaTriggerScript.h"
#include "CreatureScript.h"
#include "Group.h"
#include "ObjectMgr.h"
#include "Player.h"
#include "ScriptedCreature.h"
#include "SpellInfo.h"
#include "SpellScriptLoader.h"
#include "icecrown_citadel.h"
#include <random>
Classes
class DaranavanMoveEvent
class boss_lady_deathwhisper
struct boss_lady_deathwhisper::boss_lady_deathwhisperAI
class npc_cult_fanatic
struct npc_cult_fanatic::npc_cult_fanaticAI
class npc_cult_adherent
struct npc_cult_adherent::npc_cult_adherentAI
class npc_vengeful_shade
struct npc_vengeful_shade::npc_vengeful_shadeAI
class npc_darnavan
struct npc_darnavan::npc_darnavanAI
class spell_deathwhisper_mana_barrier_aura
class spell_deathwhisper_dark_reckoning
class at_lady_deathwhisper_entrance
Macros
#define NPC_DARNAVAN RAID_MODE<uint32>(NPC_DARNAVAN_10, NPC_DARNAVAN_25, NPC_DARNAVAN_10, NPC_DARNAVAN_25)
#define NPC_DARNAVAN_CREDIT RAID_MODE<uint32>(NPC_DARNAVAN_CREDIT_10, NPC_DARNAVAN_CREDIT_25, NPC_DARNAVAN_CREDIT_10, NPC_DARNAVAN_CREDIT_25)
#define QUEST_DEPROGRAMMING RAID_MODE<uint32>(QUEST_DEPROGRAMMING_10, QUEST_DEPROGRAMMING_25, QUEST_DEPROGRAMMING_10, QUEST_DEPROGRAMMING_25)
Enumerations
enum ScriptTexts {
SAY_INTRO_1 = 0 ,
SAY_INTRO_2 = 1 ,
SAY_INTRO_3 = 2 ,
SAY_INTRO_4 = 3 ,
SAY_INTRO_5 = 4 ,
SAY_INTRO_6 = 5 ,
SAY_INTRO_7 = 6 ,
SAY_AGGRO = 7 ,
SAY_PHASE_2 = 8 ,
EMOTE_PHASE_2 = 9 ,
SAY_DOMINATE_MIND = 10 ,
SAY_DARK_EMPOWERMENT = 11 ,
SAY_DARK_TRANSFORMATION = 12 ,
SAY_ANIMATE_DEAD = 13 ,
SAY_KILL = 14 ,
SAY_BERSERK = 15 ,
SAY_DEATH = 16 ,
SAY_DARNAVAN_AGGRO = 0 ,
SAY_DARNAVAN_RESCUED = 1
}
enum Spells {
SPELL_SHADOW_CHANNELING = 43897 ,
SPELL_MANA_BARRIER = 70842 ,
SPELL_DEATH_AND_DECAY = 71001 ,
SPELL_DOMINATE_MIND_25 = 71289 ,
SPELL_SHADOW_BOLT = 71254 ,
SPELL_DARK_MARTYRDOM_T = 70897 ,
SPELL_DARK_TRANSFORMATION_T = 70895 ,
SPELL_DARK_EMPOWERMENT_T = 70896 ,
SPELL_FROSTBOLT = 71420 ,
SPELL_FROSTBOLT_VOLLEY = 72905 ,
SPELL_TOUCH_OF_INSIGNIFICANCE = 71204 ,
SPELL_SUMMON_SHADE = 71363 ,
SPELL_NECROTIC_STRIKE = 70659 ,
SPELL_SHADOW_CLEAVE = 70670 ,
SPELL_VAMPIRIC_MIGHT = 70674 ,
SPELL_DARK_MARTYRDOM_FANATIC = 71236 ,
SPELL_DARK_MARTYRDOM_FANATIC_25N = 72495 ,
SPELL_DARK_MARTYRDOM_FANATIC_10H = 72496 ,
SPELL_DARK_MARTYRDOM_FANATIC_25H = 72497 ,
SPELL_FANATIC_S_DETERMINATION = 71235 ,
SPELL_DARK_TRANSFORMATION = 70900 ,
SPELL_FROST_FEVER = 67767 ,
SPELL_DEATHCHILL_BOLT = 70594 ,
SPELL_DEATHCHILL_BLAST = 70906 ,
SPELL_CURSE_OF_TORPOR = 71237 ,
SPELL_SHORUD_OF_THE_OCCULT = 70768 ,
SPELL_DARK_MARTYRDOM_ADHERENT = 70903 ,
SPELL_DARK_MARTYRDOM_ADHERENT_25N = 72498 ,
SPELL_DARK_MARTYRDOM_ADHERENT_10H = 72499 ,
SPELL_DARK_MARTYRDOM_ADHERENT_25H = 72500 ,
SPELL_ADHERENT_S_DETERMINATION = 71234 ,
SPELL_DARK_EMPOWERMENT = 70901 ,
SPELL_VENGEFUL_BLAST_PASSIVE = 71494 ,
SPELL_VENGEFUL_BLAST_10N = 71544 ,
SPELL_VENGEFUL_BLAST_25N = 72010 ,
SPELL_VENGEFUL_BLAST_10H = 72011 ,
SPELL_VENGEFUL_BLAST_25H = 72012 ,
SPELL_BLADESTORM = 65947 ,
SPELL_CHARGE = 65927 ,
SPELL_INTIMIDATING_SHOUT = 65930 ,
SPELL_MORTAL_STRIKE = 65926 ,
SPELL_SHATTERING_THROW = 65940 ,
SPELL_SUNDER_ARMOR = 65936 ,
SPELL_FULL_HOUSE = 72827 ,
SPELL_TELEPORT_VISUAL = 52096 ,
SPELL_CLEAR_ALL_DEBUFFS = 34098 ,
SPELL_FULL_HEAL = 17683 ,
SPELL_PERMANENT_FEIGN_DEATH = 70628
}
enum EventTypes {
EVENT_INTRO_2 = 1 ,
EVENT_INTRO_3 ,
EVENT_INTRO_4 ,
EVENT_INTRO_5 ,
EVENT_INTRO_6 ,
EVENT_INTRO_7 ,
EVENT_BERSERK ,
EVENT_SPELL_DEATH_AND_DECAY ,
EVENT_SPELL_DOMINATE_MIND_25 ,
EVENT_SPELL_SHADOW_BOLT ,
EVENT_SUMMON_WAVE_P1 ,
EVENT_EMPOWER_CULTIST ,
EVENT_SPELL_FROSTBOLT ,
EVENT_SPELL_FROSTBOLT_VOLLEY ,
EVENT_SPELL_TOUCH_OF_INSIGNIFICANCE ,
EVENT_SPELL_SUMMON_SHADE ,
EVENT_SUMMON_WAVE_P2 ,
EVENT_SPELL_CULTIST_DARK_MARTYRDOM ,
EVENT_CULTIST_DARK_MARTYRDOM_REVIVE ,
EVENT_SPELL_FANATIC_NECROTIC_STRIKE ,
EVENT_SPELL_FANATIC_SHADOW_CLEAVE ,
EVENT_SPELL_FANATIC_VAMPIRIC_MIGHT ,
EVENT_SPELL_ADHERENT_FROST_FEVER ,
EVENT_SPELL_ADHERENT_DEATHCHILL ,
EVENT_SPELL_ADHERENT_CURSE_OF_TORPOR ,
EVENT_SPELL_ADHERENT_SHROUD_OF_THE_OCCULT ,
EVENT_DARNAVAN_BLADESTORM ,
EVENT_DARNAVAN_CHARGE ,
EVENT_DARNAVAN_INTIMIDATING_SHOUT ,
EVENT_DARNAVAN_MORTAL_STRIKE ,
EVENT_DARNAVAN_SHATTERING_THROW ,
EVENT_DARNAVAN_SUNDER_ARMOR
}
enum Phases {
PHASE_ALL = 0 ,
PHASE_INTRO = 1 ,
PHASE_ONE = 2 ,
PHASE_TWO = 3 ,
PHASE_INTRO_MASK = 1 << (PHASE_INTRO - 1) ,
PHASE_ONE_MASK = 1 << (PHASE_ONE - 1)
}
enum DeprogrammingData {
NPC_DARNAVAN_10 = 38472 ,
NPC_DARNAVAN_25 = 38485 ,
NPC_DARNAVAN_CREDIT_10 = 39091 ,
NPC_DARNAVAN_CREDIT_25 = 39092 ,
ACTION_COMPLETE_QUEST = -384720 ,
POINT_DESPAWN = 384721
}
enum Actions { ACTION_START_INTRO }
Functions
void ApplyMechanicImmune (Creature *c, bool apply)
void AddSC_boss_lady_deathwhisper ()
Variables
uint32 const SummonEntries [2] = {NPC_CULT_FANATIC, NPC_CULT_ADHERENT}
Position const SummonPositions [7]
Macro Definition Documentation
NPC_DARNAVAN
#define NPC_DARNAVAN RAID_MODE<uint32>(NPC_DARNAVAN_10, NPC_DARNAVAN_25, NPC_DARNAVAN_10, NPC_DARNAVAN_25)
NPC_DARNAVAN_CREDIT
#define NPC_DARNAVAN_CREDIT RAID_MODE<uint32>(NPC_DARNAVAN_CREDIT_10, NPC_DARNAVAN_CREDIT_25, NPC_DARNAVAN_CREDIT_10, NPC_DARNAVAN_CREDIT_25)
QUEST_DEPROGRAMMING
#define QUEST_DEPROGRAMMING RAID_MODE<uint32>(QUEST_DEPROGRAMMING_10, QUEST_DEPROGRAMMING_25, QUEST_DEPROGRAMMING_10, QUEST_DEPROGRAMMING_25)
Enumeration Type Documentation
Actions
enum Actions
Enumerator
ACTION_START_INTRO
{
    ACTION_START_INTRO
};
DeprogrammingData
enum DeprogrammingData
Enumerator
NPC_DARNAVAN_10
NPC_DARNAVAN_25
NPC_DARNAVAN_CREDIT_10
NPC_DARNAVAN_CREDIT_25
ACTION_COMPLETE_QUEST
POINT_DESPAWN
{
    NPC_DARNAVAN_10         = 38472,
    NPC_DARNAVAN_25         = 38485,
    NPC_DARNAVAN_CREDIT_10  = 39091,
    NPC_DARNAVAN_CREDIT_25  = 39092,
    ACTION_COMPLETE_QUEST   = -384720,
    POINT_DESPAWN           = 384721,
};
EventTypes
enum EventTypes
Enumerator
EVENT_INTRO_2
EVENT_INTRO_3
EVENT_INTRO_4
EVENT_INTRO_5
EVENT_INTRO_6
EVENT_INTRO_7
EVENT_BERSERK
EVENT_SPELL_DEATH_AND_DECAY
EVENT_SPELL_DOMINATE_MIND_25
EVENT_SPELL_SHADOW_BOLT
EVENT_SUMMON_WAVE_P1
EVENT_EMPOWER_CULTIST
EVENT_SPELL_FROSTBOLT
EVENT_SPELL_FROSTBOLT_VOLLEY
EVENT_SPELL_TOUCH_OF_INSIGNIFICANCE
EVENT_SPELL_SUMMON_SHADE
EVENT_SUMMON_WAVE_P2
EVENT_SPELL_CULTIST_DARK_MARTYRDOM
EVENT_CULTIST_DARK_MARTYRDOM_REVIVE
EVENT_SPELL_FANATIC_NECROTIC_STRIKE
EVENT_SPELL_FANATIC_SHADOW_CLEAVE
EVENT_SPELL_FANATIC_VAMPIRIC_MIGHT
EVENT_SPELL_ADHERENT_FROST_FEVER
EVENT_SPELL_ADHERENT_DEATHCHILL
EVENT_SPELL_ADHERENT_CURSE_OF_TORPOR
EVENT_SPELL_ADHERENT_SHROUD_OF_THE_OCCULT
EVENT_DARNAVAN_BLADESTORM
EVENT_DARNAVAN_CHARGE
EVENT_DARNAVAN_INTIMIDATING_SHOUT
EVENT_DARNAVAN_MORTAL_STRIKE
EVENT_DARNAVAN_SHATTERING_THROW
EVENT_DARNAVAN_SUNDER_ARMOR
{
    // Lady Deathwhisper:
    EVENT_INTRO_2 = 1,
    EVENT_INTRO_3,
    EVENT_INTRO_4,
    EVENT_INTRO_5,
    EVENT_INTRO_6,
    EVENT_INTRO_7,
    EVENT_BERSERK,
    EVENT_SPELL_DEATH_AND_DECAY,
    EVENT_SPELL_DOMINATE_MIND_25,
    // Phase 1:
    EVENT_SPELL_SHADOW_BOLT,
    EVENT_SUMMON_WAVE_P1,
    EVENT_EMPOWER_CULTIST,
    // Phase 2:
    EVENT_SPELL_FROSTBOLT,
    EVENT_SPELL_FROSTBOLT_VOLLEY,
    EVENT_SPELL_TOUCH_OF_INSIGNIFICANCE,
    EVENT_SPELL_SUMMON_SHADE,
    EVENT_SUMMON_WAVE_P2,
    // Shared adds events:
    EVENT_SPELL_CULTIST_DARK_MARTYRDOM,
    EVENT_CULTIST_DARK_MARTYRDOM_REVIVE,
    // Cult Fanatic:
    EVENT_SPELL_FANATIC_NECROTIC_STRIKE,
    EVENT_SPELL_FANATIC_SHADOW_CLEAVE,
    EVENT_SPELL_FANATIC_VAMPIRIC_MIGHT,
    // Cult Adherent:
    EVENT_SPELL_ADHERENT_FROST_FEVER,
    EVENT_SPELL_ADHERENT_DEATHCHILL,
    EVENT_SPELL_ADHERENT_CURSE_OF_TORPOR,
    EVENT_SPELL_ADHERENT_SHROUD_OF_THE_OCCULT,
    // Darnavan:
    EVENT_DARNAVAN_BLADESTORM,
    EVENT_DARNAVAN_CHARGE,
    EVENT_DARNAVAN_INTIMIDATING_SHOUT,
    EVENT_DARNAVAN_MORTAL_STRIKE,
    EVENT_DARNAVAN_SHATTERING_THROW,
    EVENT_DARNAVAN_SUNDER_ARMOR,
};
Phases
enum Phases
Enumerator
PHASE_ALL
PHASE_INTRO
PHASE_ONE
PHASE_TWO
PHASE_INTRO_MASK
PHASE_ONE_MASK
{
    PHASE_ALL       = 0,
    PHASE_INTRO     = 1,
    PHASE_ONE       = 2,
    PHASE_TWO       = 3,
    PHASE_INTRO_MASK    = 1 << (PHASE_INTRO - 1),
    PHASE_ONE_MASK      = 1 << (PHASE_ONE - 1),
};
ScriptTexts
enum ScriptTexts
Enumerator
SAY_INTRO_1
SAY_INTRO_2
SAY_INTRO_3
SAY_INTRO_4
SAY_INTRO_5
SAY_INTRO_6
SAY_INTRO_7
SAY_AGGRO
SAY_PHASE_2
EMOTE_PHASE_2
SAY_DOMINATE_MIND
SAY_DARK_EMPOWERMENT
SAY_DARK_TRANSFORMATION
SAY_ANIMATE_DEAD
SAY_KILL
SAY_BERSERK
SAY_DEATH
SAY_DARNAVAN_AGGRO
SAY_DARNAVAN_RESCUED
{
    // Lady Deathwhisper
    SAY_INTRO_1                 = 0,
    SAY_INTRO_2                 = 1,
    SAY_INTRO_3                 = 2,
    SAY_INTRO_4                 = 3,
    SAY_INTRO_5                 = 4,
    SAY_INTRO_6                 = 5,
    SAY_INTRO_7                 = 6,
    SAY_AGGRO                   = 7,
    SAY_PHASE_2                 = 8,
    EMOTE_PHASE_2               = 9,
    SAY_DOMINATE_MIND           = 10,
    SAY_DARK_EMPOWERMENT        = 11,
    SAY_DARK_TRANSFORMATION     = 12,
    SAY_ANIMATE_DEAD            = 13,
    SAY_KILL                    = 14,
    SAY_BERSERK                 = 15,
    SAY_DEATH                   = 16,
    // Darnavan
    SAY_DARNAVAN_AGGRO          = 0,
    SAY_DARNAVAN_RESCUED        = 1,
};
Spells
enum Spells
Enumerator
SPELL_SHADOW_CHANNELING
SPELL_MANA_BARRIER
SPELL_DEATH_AND_DECAY
SPELL_DOMINATE_MIND_25
SPELL_SHADOW_BOLT
SPELL_DARK_MARTYRDOM_T
SPELL_DARK_TRANSFORMATION_T
SPELL_DARK_EMPOWERMENT_T
SPELL_FROSTBOLT
SPELL_FROSTBOLT_VOLLEY
SPELL_TOUCH_OF_INSIGNIFICANCE
SPELL_SUMMON_SHADE
SPELL_NECROTIC_STRIKE
SPELL_SHADOW_CLEAVE
SPELL_VAMPIRIC_MIGHT
SPELL_DARK_MARTYRDOM_FANATIC
SPELL_DARK_MARTYRDOM_FANATIC_25N
SPELL_DARK_MARTYRDOM_FANATIC_10H
SPELL_DARK_MARTYRDOM_FANATIC_25H
SPELL_FANATIC_S_DETERMINATION
SPELL_DARK_TRANSFORMATION
SPELL_FROST_FEVER
SPELL_DEATHCHILL_BOLT
SPELL_DEATHCHILL_BLAST
SPELL_CURSE_OF_TORPOR
SPELL_SHORUD_OF_THE_OCCULT
SPELL_DARK_MARTYRDOM_ADHERENT
SPELL_DARK_MARTYRDOM_ADHERENT_25N
SPELL_DARK_MARTYRDOM_ADHERENT_10H
SPELL_DARK_MARTYRDOM_ADHERENT_25H
SPELL_ADHERENT_S_DETERMINATION
SPELL_DARK_EMPOWERMENT
SPELL_VENGEFUL_BLAST_PASSIVE
SPELL_VENGEFUL_BLAST_10N
SPELL_VENGEFUL_BLAST_25N
SPELL_VENGEFUL_BLAST_10H
SPELL_VENGEFUL_BLAST_25H
SPELL_BLADESTORM
SPELL_CHARGE
SPELL_INTIMIDATING_SHOUT
SPELL_MORTAL_STRIKE
SPELL_SHATTERING_THROW
SPELL_SUNDER_ARMOR
SPELL_FULL_HOUSE
SPELL_TELEPORT_VISUAL
SPELL_CLEAR_ALL_DEBUFFS
SPELL_FULL_HEAL
SPELL_PERMANENT_FEIGN_DEATH
{
    // Lady Deathwhisper
    SPELL_SHADOW_CHANNELING           = 43897, // during intro
    SPELL_MANA_BARRIER                = 70842,
    SPELL_DEATH_AND_DECAY             = 71001,
    SPELL_DOMINATE_MIND_25            = 71289,
    SPELL_SHADOW_BOLT                 = 71254,
    SPELL_DARK_MARTYRDOM_T            = 70897,
    SPELL_DARK_TRANSFORMATION_T       = 70895,
    SPELL_DARK_EMPOWERMENT_T          = 70896,
    SPELL_FROSTBOLT                   = 71420,
    SPELL_FROSTBOLT_VOLLEY            = 72905,
    SPELL_TOUCH_OF_INSIGNIFICANCE     = 71204,
    SPELL_SUMMON_SHADE                = 71363,
    // Fanatics
    SPELL_NECROTIC_STRIKE             = 70659,
    SPELL_SHADOW_CLEAVE               = 70670,
    SPELL_VAMPIRIC_MIGHT              = 70674,
    SPELL_DARK_MARTYRDOM_FANATIC      = 71236,
    SPELL_DARK_MARTYRDOM_FANATIC_25N  = 72495,
    SPELL_DARK_MARTYRDOM_FANATIC_10H  = 72496,
    SPELL_DARK_MARTYRDOM_FANATIC_25H  = 72497,
    SPELL_FANATIC_S_DETERMINATION     = 71235,
    SPELL_DARK_TRANSFORMATION         = 70900,
    //  Adherents
    SPELL_FROST_FEVER                 = 67767,
    SPELL_DEATHCHILL_BOLT             = 70594,
    SPELL_DEATHCHILL_BLAST            = 70906,
    SPELL_CURSE_OF_TORPOR             = 71237,
    SPELL_SHORUD_OF_THE_OCCULT        = 70768,
    SPELL_DARK_MARTYRDOM_ADHERENT     = 70903,
    SPELL_DARK_MARTYRDOM_ADHERENT_25N = 72498,
    SPELL_DARK_MARTYRDOM_ADHERENT_10H = 72499,
    SPELL_DARK_MARTYRDOM_ADHERENT_25H = 72500,
    SPELL_ADHERENT_S_DETERMINATION    = 71234,
    SPELL_DARK_EMPOWERMENT            = 70901,
    // Vengeful Shade
    SPELL_VENGEFUL_BLAST_PASSIVE      = 71494,
    SPELL_VENGEFUL_BLAST_10N          = 71544,
    SPELL_VENGEFUL_BLAST_25N          = 72010,
    SPELL_VENGEFUL_BLAST_10H          = 72011,
    SPELL_VENGEFUL_BLAST_25H          = 72012,
    // Darnavan
    SPELL_BLADESTORM                  = 65947,
    SPELL_CHARGE                      = 65927,
    SPELL_INTIMIDATING_SHOUT          = 65930,
    SPELL_MORTAL_STRIKE               = 65926,
    SPELL_SHATTERING_THROW            = 65940,
    SPELL_SUNDER_ARMOR                = 65936,
    // misc
    SPELL_FULL_HOUSE                  = 72827, // achievement
    SPELL_TELEPORT_VISUAL             = 52096, // used by adds
    SPELL_CLEAR_ALL_DEBUFFS           = 34098,
    SPELL_FULL_HEAL                   = 17683,
    SPELL_PERMANENT_FEIGN_DEATH       = 70628,
};
Function Documentation
AddSC_boss_lady_deathwhisper()
void AddSC_boss_lady_deathwhisper ()
{
    // Creatures
    new boss_lady_deathwhisper();
    new npc_cult_fanatic();
    new npc_cult_adherent();
    new npc_vengeful_shade();
    new npc_darnavan();
    // Spells
    RegisterSpellScript(spell_deathwhisper_mana_barrier_aura);
    RegisterSpellScript(spell_deathwhisper_dark_reckoning);
    // AreaTriggers
    new at_lady_deathwhisper_entrance();
}
References RegisterSpellScript.
Referenced by AddNorthrendScripts().
ApplyMechanicImmune()
void ApplyMechanicImmune (Creature * c, bool apply)
{
    c->ApplySpellImmune(0, IMMUNITY_MECHANIC, MECHANIC_FEAR, apply);
    c->ApplySpellImmune(0, IMMUNITY_MECHANIC, MECHANIC_INTERRUPT, apply);
    c->ApplySpellImmune(0, IMMUNITY_MECHANIC, MECHANIC_KNOCKOUT, apply);
    c->ApplySpellImmune(0, IMMUNITY_MECHANIC, MECHANIC_SILENCE, apply);
    c->ApplySpellImmune(0, IMMUNITY_MECHANIC, MECHANIC_STUN, apply);
    c->ApplySpellImmune(0, IMMUNITY_MECHANIC, MECHANIC_DISORIENTED, apply);
    c->ApplySpellImmune(0, IMMUNITY_MECHANIC, MECHANIC_POLYMORPH, apply);
    c->ApplySpellImmune(0, IMMUNITY_MECHANIC, MECHANIC_SLEEP, apply);
    c->ApplySpellImmune(0, IMMUNITY_MECHANIC, MECHANIC_FREEZE, apply);
    c->ApplySpellImmune(0, IMMUNITY_MECHANIC, MECHANIC_HORROR, apply);
    c->ApplySpellImmune(0, IMMUNITY_MECHANIC, MECHANIC_CHARM, apply);
}
References Unit::ApplySpellImmune(), IMMUNITY_MECHANIC, MECHANIC_CHARM, MECHANIC_DISORIENTED, MECHANIC_FEAR, MECHANIC_FREEZE, MECHANIC_HORROR, MECHANIC_INTERRUPT, MECHANIC_KNOCKOUT, MECHANIC_POLYMORPH, MECHANIC_SILENCE, MECHANIC_SLEEP, and MECHANIC_STUN.
Referenced by npc_cult_fanatic::npc_cult_fanaticAI::SpellHit(), and npc_cult_adherent::npc_cult_adherentAI::SpellHit().
Variable Documentation
SummonEntries
uint32 const SummonEntries[2] = {NPC_CULT_FANATIC, NPC_CULT_ADHERENT}
{NPC_CULT_FANATIC, NPC_CULT_ADHERENT};
Referenced by boss_lady_deathwhisper::boss_lady_deathwhisperAI::SummonWaveP1(), and boss_lady_deathwhisper::boss_lady_deathwhisperAI::SummonWaveP2().
SummonPositions
Position const SummonPositions[7]
Initial value:
=
{
    {-578.7066f, 2154.167f, 51.01529f, 1.692969f},
    {-598.9028f, 2155.005f, 51.01530f, 1.692969f},
    {-619.2864f, 2154.460f, 51.01530f, 1.692969f},
    {-578.6996f, 2269.856f, 51.01529f, 4.590216f},
    {-598.9688f, 2269.264f, 51.01529f, 4.590216f},
    {-619.4323f, 2268.523f, 51.01530f, 4.590216f},
    {-524.2480f, 2211.920f, 62.90960f, 3.141592f},
}
{
    {-578.7066f, 2154.167f, 51.01529f, 1.692969f}, // 1 Left Door 1 (Cult Fanatic)
    {-598.9028f, 2155.005f, 51.01530f, 1.692969f}, // 2 Left Door 2 (Cult Adherent)
    {-619.2864f, 2154.460f, 51.01530f, 1.692969f}, // 3 Left Door 3 (Cult Fanatic)
    {-578.6996f, 2269.856f, 51.01529f, 4.590216f}, // 4 Right Door 1 (Cult Adherent)
    {-598.9688f, 2269.264f, 51.01529f, 4.590216f}, // 5 Right Door 2 (Cult Fanatic)
    {-619.4323f, 2268.523f, 51.01530f, 4.590216f}, // 6 Right Door 3 (Cult Adherent)
    {-524.2480f, 2211.920f, 62.90960f, 3.141592f}, // 7 Upper (Random Cultist)
};
Referenced by DaranavanMoveEvent::Execute(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::SummonWaveP1(), and boss_lady_deathwhisper::boss_lady_deathwhisperAI::SummonWaveP2().