AzerothCore Doxygen
boss_blood_queen_lana_thel.cpp File Reference
#include "AchievementCriteriaScript.h"
#include "AreaDefines.h"
#include "CreatureScript.h"
#include "GridNotifiers.h"
#include "ObjectMgr.h"
#include "ScriptedCreature.h"
#include "Spell.h"
#include "SpellAuraEffects.h"
#include "SpellScriptLoader.h"
#include "icecrown_citadel.h"
Classes
struct VampiricBiteTargetSelector
class boss_blood_queen_lana_thel
struct boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI
class spell_blood_queen_pact_of_the_darkfallen_dmg_aura
class spell_blood_queen_pact_of_the_darkfallen
class spell_blood_queen_pact_of_the_darkfallen_dmg_target
class BloodboltHitCheck
class spell_blood_queen_bloodbolt
class spell_blood_queen_frenzied_bloodthirst_aura
class spell_blood_queen_essence_of_the_blood_queen_aura
class spell_blood_queen_vampiric_bite
class spell_blood_queen_swarming_shadows_floor_dmg
class spell_blood_queen_presence_of_the_darkfallen
class achievement_once_bitten_twice_shy
Typedefs
typedef boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI LanaThelAI
Enumerations
enum Texts {
SAY_AGGRO = 0 ,
SAY_VAMPIRIC_BITE = 1 ,
SAY_MIND_CONTROL = 2 ,
EMOTE_BLOODTHIRST = 3 ,
SAY_SWARMING_SHADOWS = 4 ,
EMOTE_SWARMING_SHADOWS = 5 ,
SAY_PACT_OF_THE_DARKFALLEN = 6 ,
SAY_AIR_PHASE = 7 ,
SAY_KILL = 8 ,
SAY_WIPE = 9 ,
SAY_BERSERK = 10 ,
SAY_DEATH = 11 ,
EMOTE_BERSERK_RAID = 12
}
enum Spells {
SPELL_SHROUD_OF_SORROW = 70986 ,
SPELL_FRENZIED_BLOODTHIRST_VISUAL = 71949 ,
SPELL_VAMPIRIC_BITE = 71726 ,
SPELL_VAMPIRIC_BITE_DUMMY = 71837 ,
SPELL_ESSENCE_OF_BLOOD_QUEEN = 70867 ,
SPELL_ESSENCE_OF_THE_BLOOD_QUEEN_PLR = 70879 ,
SPELL_ESSENCE_OF_THE_BLOOD_QUEEN_HEAL = 70872 ,
SPELL_FRENZIED_BLOODTHIRST = 70877 ,
SPELL_UNCONTROLLABLE_FRENZY = 70923 ,
SPELL_PRESENCE_OF_THE_DARKFALLEN_DUMMY = 70994 ,
SPELL_PRESENCE_OF_THE_DARKFALLEN_EFFECT = 70995 ,
SPELL_PRESENCE_OF_THE_DARKFALLEN_SE = 71952 ,
SPELL_BLOOD_MIRROR_DAMAGE = 70821 ,
SPELL_BLOOD_MIRROR_VISUAL = 71510 ,
SPELL_BLOOD_MIRROR_DUMMY = 70838 ,
SPELL_DELIRIOUS_SLASH = 71623 ,
SPELL_PACT_OF_THE_DARKFALLEN_TARGET = 71336 ,
SPELL_PACT_OF_THE_DARKFALLEN = 71340 ,
SPELL_PACT_OF_THE_DARKFALLEN_DAMAGE = 71341 ,
SPELL_SWARMING_SHADOWS = 71264 ,
SPELL_TWILIGHT_BLOODBOLT_TARGET = 71445 ,
SPELL_TWILIGHT_BLOODBOLT = 71818 ,
SPELL_TWILIGHT_BLOODBOLT_FROM_WHIRL = 71446 ,
SPELL_INCITE_TERROR = 73070 ,
SPELL_BLOODBOLT_WHIRL = 71772 ,
SPELL_ANNIHILATE = 71322
}
enum Shadowmourne {
QUEST_BLOOD_INFUSION = 24756 ,
SPELL_BLOOD_INFUSION_CREDIT = 72934 ,
SPELL_GUSHING_WOUND = 72132 ,
SPELL_THIRST_QUENCHED = 72154
}
enum Events {
EVENT_NONE ,
EVENT_BERSERK ,
EVENT_VAMPIRIC_BITE ,
EVENT_BLOOD_MIRROR ,
EVENT_DELIRIOUS_SLASH ,
EVENT_PACT_OF_THE_DARKFALLEN ,
EVENT_SWARMING_SHADOWS ,
EVENT_TWILIGHT_BLOODBOLT ,
EVENT_AIR_PHASE ,
EVENT_AIR_START_FLYING ,
EVENT_AIR_FLY_DOWN
}
enum Guids {
GUID_VAMPIRE = 1 ,
GUID_BLOODBOLT = 2
}
enum Points {
POINT_CENTER = 1 ,
POINT_AIR = 2 ,
POINT_GROUND = 3 ,
POINT_MINCHAR = 4
}
Functions
bool IsVampire (Unit const *unit)
void AddSC_boss_blood_queen_lana_thel ()
Variables
Position const centerPos = {4595.7090f, 2769.4190f, 400.6368f, 0.000000f}
Position const airPos = {4595.7090f, 2769.4190f, 422.3893f, 0.000000f}
Position const mincharPos = {4629.3711f, 2782.6089f, 424.6390f, 0.000000f}
Typedef Documentation
LanaThelAI
typedef boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI LanaThelAI
Enumeration Type Documentation
Events
enum Events
Enumerator
EVENT_NONE
EVENT_BERSERK
EVENT_VAMPIRIC_BITE
EVENT_BLOOD_MIRROR
EVENT_DELIRIOUS_SLASH
EVENT_PACT_OF_THE_DARKFALLEN
EVENT_SWARMING_SHADOWS
EVENT_TWILIGHT_BLOODBOLT
EVENT_AIR_PHASE
EVENT_AIR_START_FLYING
EVENT_AIR_FLY_DOWN
{
    EVENT_NONE,
    EVENT_BERSERK,
    EVENT_VAMPIRIC_BITE,
    EVENT_BLOOD_MIRROR,
    EVENT_DELIRIOUS_SLASH,
    EVENT_PACT_OF_THE_DARKFALLEN,
    EVENT_SWARMING_SHADOWS,
    EVENT_TWILIGHT_BLOODBOLT,
    EVENT_AIR_PHASE,
    EVENT_AIR_START_FLYING,
    EVENT_AIR_FLY_DOWN,
};
Guids
enum Guids
Enumerator
GUID_VAMPIRE
GUID_BLOODBOLT
{
    GUID_VAMPIRE    = 1,
    GUID_BLOODBOLT  = 2,
};
Points
enum Points
Enumerator
POINT_CENTER
POINT_AIR
POINT_GROUND
POINT_MINCHAR
{
    POINT_CENTER    = 1,
    POINT_AIR       = 2,
    POINT_GROUND    = 3,
    POINT_MINCHAR   = 4,
};
Shadowmourne
enum Shadowmourne
Enumerator
QUEST_BLOOD_INFUSION
SPELL_BLOOD_INFUSION_CREDIT
SPELL_GUSHING_WOUND
SPELL_THIRST_QUENCHED
{
    QUEST_BLOOD_INFUSION                    = 24756,
    SPELL_BLOOD_INFUSION_CREDIT             = 72934,
    SPELL_GUSHING_WOUND                     = 72132,
    SPELL_THIRST_QUENCHED                   = 72154,
};
Spells
enum Spells
Enumerator
SPELL_SHROUD_OF_SORROW
SPELL_FRENZIED_BLOODTHIRST_VISUAL
SPELL_VAMPIRIC_BITE
SPELL_VAMPIRIC_BITE_DUMMY
SPELL_ESSENCE_OF_BLOOD_QUEEN
SPELL_ESSENCE_OF_THE_BLOOD_QUEEN_PLR
SPELL_ESSENCE_OF_THE_BLOOD_QUEEN_HEAL
SPELL_FRENZIED_BLOODTHIRST
SPELL_UNCONTROLLABLE_FRENZY
SPELL_PRESENCE_OF_THE_DARKFALLEN_DUMMY
SPELL_PRESENCE_OF_THE_DARKFALLEN_EFFECT
SPELL_PRESENCE_OF_THE_DARKFALLEN_SE
SPELL_BLOOD_MIRROR_DAMAGE
SPELL_BLOOD_MIRROR_VISUAL
SPELL_BLOOD_MIRROR_DUMMY
SPELL_DELIRIOUS_SLASH
SPELL_PACT_OF_THE_DARKFALLEN_TARGET
SPELL_PACT_OF_THE_DARKFALLEN
SPELL_PACT_OF_THE_DARKFALLEN_DAMAGE
SPELL_SWARMING_SHADOWS
SPELL_TWILIGHT_BLOODBOLT_TARGET
SPELL_TWILIGHT_BLOODBOLT
SPELL_TWILIGHT_BLOODBOLT_FROM_WHIRL
SPELL_INCITE_TERROR
SPELL_BLOODBOLT_WHIRL
SPELL_ANNIHILATE
{
    SPELL_SHROUD_OF_SORROW                  = 70986,
    SPELL_FRENZIED_BLOODTHIRST_VISUAL       = 71949,
    SPELL_VAMPIRIC_BITE                     = 71726,
    SPELL_VAMPIRIC_BITE_DUMMY               = 71837,
    SPELL_ESSENCE_OF_BLOOD_QUEEN            = 70867,
    SPELL_ESSENCE_OF_THE_BLOOD_QUEEN_PLR    = 70879,
    SPELL_ESSENCE_OF_THE_BLOOD_QUEEN_HEAL   = 70872,
    SPELL_FRENZIED_BLOODTHIRST              = 70877,
    SPELL_UNCONTROLLABLE_FRENZY             = 70923,
    SPELL_PRESENCE_OF_THE_DARKFALLEN_DUMMY  = 70994,
    SPELL_PRESENCE_OF_THE_DARKFALLEN_EFFECT = 70995,
    SPELL_PRESENCE_OF_THE_DARKFALLEN_SE     = 71952,
    SPELL_BLOOD_MIRROR_DAMAGE               = 70821,
    SPELL_BLOOD_MIRROR_VISUAL               = 71510,
    SPELL_BLOOD_MIRROR_DUMMY                = 70838,
    SPELL_DELIRIOUS_SLASH                   = 71623,
    SPELL_PACT_OF_THE_DARKFALLEN_TARGET     = 71336,
    SPELL_PACT_OF_THE_DARKFALLEN            = 71340,
    SPELL_PACT_OF_THE_DARKFALLEN_DAMAGE     = 71341,
    SPELL_SWARMING_SHADOWS                  = 71264,
    SPELL_TWILIGHT_BLOODBOLT_TARGET         = 71445,
    SPELL_TWILIGHT_BLOODBOLT                = 71818,
    SPELL_TWILIGHT_BLOODBOLT_FROM_WHIRL     = 71446,
    SPELL_INCITE_TERROR                     = 73070,
    SPELL_BLOODBOLT_WHIRL                   = 71772,
    SPELL_ANNIHILATE                        = 71322,
};
Texts
enum Texts
Enumerator
SAY_AGGRO
SAY_VAMPIRIC_BITE
SAY_MIND_CONTROL
EMOTE_BLOODTHIRST
SAY_SWARMING_SHADOWS
EMOTE_SWARMING_SHADOWS
SAY_PACT_OF_THE_DARKFALLEN
SAY_AIR_PHASE
SAY_KILL
SAY_WIPE
SAY_BERSERK
SAY_DEATH
EMOTE_BERSERK_RAID
{
    SAY_AGGRO                   = 0,
    SAY_VAMPIRIC_BITE           = 1,
    SAY_MIND_CONTROL            = 2,
    EMOTE_BLOODTHIRST           = 3,
    SAY_SWARMING_SHADOWS        = 4,
    EMOTE_SWARMING_SHADOWS      = 5,
    SAY_PACT_OF_THE_DARKFALLEN  = 6,
    SAY_AIR_PHASE               = 7,
    SAY_KILL                    = 8,
    SAY_WIPE                    = 9,
    SAY_BERSERK                 = 10,
    SAY_DEATH                   = 11,
    EMOTE_BERSERK_RAID          = 12
};
Function Documentation
AddSC_boss_blood_queen_lana_thel()
void AddSC_boss_blood_queen_lana_thel ()
{
    new boss_blood_queen_lana_thel();
    RegisterSpellScript(spell_blood_queen_pact_of_the_darkfallen_dmg_aura);
    RegisterSpellScript(spell_blood_queen_pact_of_the_darkfallen);
    RegisterSpellScript(spell_blood_queen_pact_of_the_darkfallen_dmg_target);
    RegisterSpellScript(spell_blood_queen_bloodbolt);
    RegisterSpellScript(spell_blood_queen_frenzied_bloodthirst_aura);
    RegisterSpellScript(spell_blood_queen_essence_of_the_blood_queen_aura);
    RegisterSpellScript(spell_blood_queen_vampiric_bite);
    RegisterSpellScript(spell_blood_queen_swarming_shadows_floor_dmg);
    RegisterSpellScript(spell_blood_queen_presence_of_the_darkfallen);
    new achievement_once_bitten_twice_shy("achievement_once_bitten_twice_shy_n_10", 0, false);
    new achievement_once_bitten_twice_shy("achievement_once_bitten_twice_shy_v_10", 0, true);
    new achievement_once_bitten_twice_shy("achievement_once_bitten_twice_shy_n_25", 1, false);
    new achievement_once_bitten_twice_shy("achievement_once_bitten_twice_shy_v_25", 1, true);
}
References RegisterSpellScript.
Referenced by AddNorthrendScripts().
IsVampire()
bool IsVampire (Unit const * unit)
{
    if (unit->HasAnyAuras(SPELL_ESSENCE_OF_BLOOD_QUEEN, SPELL_ESSENCE_OF_THE_BLOOD_QUEEN_PLR, SPELL_FRENZIED_BLOODTHIRST))
        return true;
    return false;
}
References Unit::HasAnyAuras(), SPELL_ESSENCE_OF_BLOOD_QUEEN, SPELL_ESSENCE_OF_THE_BLOOD_QUEEN_PLR, and SPELL_FRENZIED_BLOODTHIRST.
Referenced by spell_blood_queen_vampiric_bite::CheckTarget(), and VampiricBiteTargetSelector::operator()().
Variable Documentation
airPos
Position const airPos = {4595.7090f, 2769.4190f, 422.3893f, 0.000000f}
{4595.7090f, 2769.4190f, 422.3893f, 0.000000f};
Referenced by boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::UpdateAI().
centerPos
Position const centerPos = {4595.7090f, 2769.4190f, 400.6368f, 0.000000f}
{4595.7090f, 2769.4190f, 400.6368f, 0.000000f};
Referenced by boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::UpdateAI().
mincharPos
Position const mincharPos = {4629.3711f, 2782.6089f, 424.6390f, 0.000000f}
{4629.3711f, 2782.6089f, 424.6390f, 0.000000f};
Referenced by boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::GoToMinchar().