AzerothCore Doxygen
npc_kiljaeden_controller Struct Reference
Public Member Functions
npc_kiljaeden_controller (Creature *creature)
void ResetOrbs ()
void Reset () override
void JustDied (Unit *) override
void JustSummoned (Creature *summon) override
void SummonedCreatureDies (Creature *summon, Unit *) override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
Public Member Functions inherited from NullCreatureAI
NullCreatureAI (Creature *c)
void MoveInLineOfSight (Unit *) override
void AttackStart (Unit *) override
void UpdateAI (uint32) override
Use to start attacking a target. Called just before JustEngagedWith()
void EnterEvadeMode (EvadeReason) override
void OnCharmed (bool) override
Called when unit is charmed.
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0ms)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void KilledUnit (Unit *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void OnSpellCastFinished (SpellInfo const *, SpellFinishReason)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
int32 VisualizeBoundary (uint32 duration, Unit *owner=nullptr, bool fill=false, bool checkZ=false) const
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
virtual void DistancingStarted ()
virtual void DistancingEnded ()
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid const &, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Private Attributes
InstanceScript * instance
SummonList summons
Additional Inherited Members
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from NullCreatureAI
static int32 Permissible (Creature const *creature)
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
npc_kiljaeden_controller()
npc_kiljaeden_controller::npc_kiljaeden_controller (Creature * creature) inline
                                                 : NullCreatureAI(creature), summons(me)
    {
        instance = creature->GetInstanceScript();
        scheduler.SetValidator([this]
        {
            return !me->HasUnitState(UNIT_STATE_CASTING);
        });
    }
References WorldObject::GetInstanceScript(), Unit::HasUnitState(), instance, CreatureAI::me, CreatureAI::scheduler, TaskScheduler::SetValidator(), and UNIT_STATE_CASTING.
Member Function Documentation
JustDied()
void npc_kiljaeden_controller::JustDied (Unit *) inline override virtual
Reimplemented from CreatureAI.
    {
        EntryCheckPredicate kilCheck(NPC_KILJAEDEN);
        EntryCheckPredicate kalCheck(NPC_KALECGOS_KJ);
        summons.DespawnIf(kilCheck);
        summons.DoAction(ACTION_START_POST_EVENT, kalCheck);
        summons.DespawnIf(kalCheck);
        DoCastAOE(SPELL_DESTROY_ALL_DRAKES, true);
        summons.DespawnAll();
    }
References ACTION_START_POST_EVENT, SummonList::DespawnAll(), SummonList::DespawnIf(), SummonList::DoAction(), UnitAI::DoCastAOE(), NPC_KALECGOS_KJ, NPC_KILJAEDEN, SPELL_DESTROY_ALL_DRAKES, and summons.
JustSummoned()
void npc_kiljaeden_controller::JustSummoned (Creature * summon) inline override virtual
Reimplemented from CreatureAI.
    {
        summons.Summon(summon);
        if (summon->GetEntry() == NPC_SINISTER_REFLECTION)
        {
            summon->m_Events.AddEventAtOffset([summon] {
                if (summon && summon->IsAlive() && !summon->IsInCombat())
                    summon->SetInCombatWithZone();
            }, 5s);
        }
        else if (summon->GetEntry() == NPC_KALECGOS_KJ)
            summon->setActive(true);
    }
References EventProcessor::AddEventAtOffset(), Object::GetEntry(), Unit::IsAlive(), Unit::IsInCombat(), WorldObject::m_Events, NPC_KALECGOS_KJ, NPC_SINISTER_REFLECTION, WorldObject::setActive(), Creature::SetInCombatWithZone(), SummonList::Summon(), and summons.
Reset()
void npc_kiljaeden_controller::Reset () inline override virtual
Reimplemented from UnitAI.
    {
        scheduler.CancelAll();
        instance->SetBossState(DATA_KILJAEDEN, NOT_STARTED);
        summons.DespawnAll();
        ResetOrbs();
        me->SummonCreature(NPC_HAND_OF_THE_DECEIVER, 1702.62f, 611.19f, 27.66f, 1.81f, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 30000);
        me->SummonCreature(NPC_HAND_OF_THE_DECEIVER, 1684.099f, 618.848f, 27.67f, 0.589f, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 30000);
        me->SummonCreature(NPC_HAND_OF_THE_DECEIVER, 1688.38f, 641.10f, 27.50f, 5.43f, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 30000);
        me->SummonCreature(NPC_ANVEENA, me->GetPositionX(), me->GetPositionY(), me->GetPositionZ() + 40.0f, 0.0f);
        DoCastAOE(SPELL_DESTROY_ALL_DRAKES, true);
        DoCastSelf(SPELL_ANVEENA_ENERGY_DRAIN, true);
        scheduler.Schedule(1min, [this](TaskContext context) {
            if (instance->GetBossState(DATA_KILJAEDEN) == NOT_STARTED)
                Talk(SAY_KJ_OFFCOMBAT);
            context.Repeat(90s, 3min);
        });
    }
References TaskScheduler::CancelAll(), DATA_KILJAEDEN, SummonList::DespawnAll(), UnitAI::DoCastAOE(), UnitAI::DoCastSelf(), InstanceScript::GetBossState(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), instance, CreatureAI::me, NOT_STARTED, NPC_ANVEENA, NPC_HAND_OF_THE_DECEIVER, TaskContext::Repeat(), ResetOrbs(), SAY_KJ_OFFCOMBAT, TaskScheduler::Schedule(), CreatureAI::scheduler, InstanceScript::SetBossState(), SPELL_ANVEENA_ENERGY_DRAIN, SPELL_DESTROY_ALL_DRAKES, WorldObject::SummonCreature(), summons, and TEMPSUMMON_CORPSE_TIMED_DESPAWN.
ResetOrbs()
void npc_kiljaeden_controller::ResetOrbs () inline
    {
        for (uint8 i = DATA_ORB_OF_THE_BLUE_DRAGONFLIGHT_1; i < DATA_ORB_OF_THE_BLUE_DRAGONFLIGHT_4 + 1; ++i)
            if (GameObject* orb = instance->GetGameObject(i))
                orb->SetGameObjectFlag(GO_FLAG_NOT_SELECTABLE);
    }
References DATA_ORB_OF_THE_BLUE_DRAGONFLIGHT_1, DATA_ORB_OF_THE_BLUE_DRAGONFLIGHT_4, InstanceScript::GetGameObject(), GO_FLAG_NOT_SELECTABLE, and instance.
Referenced by Reset().
SummonedCreatureDies()
void npc_kiljaeden_controller::SummonedCreatureDies (Creature * summon, Unit *) inline override virtual
Reimplemented from CreatureAI.
    {
        summons.Despawn(summon);
        if (summon->GetEntry() == NPC_HAND_OF_THE_DECEIVER)
        {
            instance->SetBossState(DATA_KILJAEDEN, IN_PROGRESS);
            scheduler.Schedule(1s, [this](TaskContext context) {
                auto const& playerList = me->GetMap()->GetPlayers();
                for (auto const& playerRef : playerList)
                    if (Player* player = playerRef.GetSource())
                        if (!player->IsGameMaster() && me->GetDistance2d(player) < 60.0f && player->IsAlive())
{
                            context.Repeat();
                            return;
                        }
                CreatureAI::EnterEvadeMode();
            });
            if (!summons.HasEntry(NPC_HAND_OF_THE_DECEIVER))
            {
                me->RemoveAurasDueToSpell(SPELL_ANVEENA_ENERGY_DRAIN);
                me->SummonCreature(NPC_KILJAEDEN, me->GetPositionX(), me->GetPositionY(), me->GetPositionZ() + 1.5f, 4.3f, TEMPSUMMON_MANUAL_DESPAWN);
                me->SummonCreature(NPC_KALECGOS_KJ, 1726.80f, 661.43f, 138.65f, 3.95f, TEMPSUMMON_MANUAL_DESPAWN);
            }
        }
    }
References DATA_KILJAEDEN, SummonList::Despawn(), CreatureAI::EnterEvadeMode(), WorldObject::GetDistance2d(), Object::GetEntry(), WorldObject::GetMap(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), SummonList::HasEntry(), IN_PROGRESS, instance, CreatureAI::me, NPC_HAND_OF_THE_DECEIVER, NPC_KALECGOS_KJ, NPC_KILJAEDEN, Unit::RemoveAurasDueToSpell(), TaskContext::Repeat(), TaskScheduler::Schedule(), CreatureAI::scheduler, InstanceScript::SetBossState(), SPELL_ANVEENA_ENERGY_DRAIN, WorldObject::SummonCreature(), summons, and TEMPSUMMON_MANUAL_DESPAWN.
UpdateAI()
void npc_kiljaeden_controller::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Implements UnitAI.
    {
        scheduler.Update(diff);
    }
References CreatureAI::scheduler, and TaskScheduler::Update().
Member Data Documentation
instance
InstanceScript* npc_kiljaeden_controller::instance private
Referenced by npc_kiljaeden_controller(), Reset(), ResetOrbs(), and SummonedCreatureDies().
summons
SummonList npc_kiljaeden_controller::summons private
Referenced by JustDied(), JustSummoned(), Reset(), and SummonedCreatureDies().
The documentation for this struct was generated from the following file:
azerothcore-wotlk/src/server/scripts/EasternKingdoms/SunwellPlateau/boss_kiljaeden.cpp