AzerothCore Doxygen
WorldObject Class Reference
#include "Object.h"
Public Member Functions
~WorldObject () override
virtual void Update (uint32 diff)
void _Create (ObjectGuid::LowType guidlow, HighGuid guidhigh, uint32 phaseMask)
void AddToWorld () override
void RemoveFromWorld () override
void GetNearPoint2D (WorldObject const *searcher, float &x, float &y, float distance, float absAngle, Position const *startPos=nullptr) const
void GetNearPoint2D (float &x, float &y, float distance, float absAngle, Position const *startPos=nullptr) const
void GetNearPoint (WorldObject const *searcher, float &x, float &y, float &z, float searcher_size, float distance2d, float absAngle, float controlZ=0, Position const *startPos=nullptr) const
void GetVoidClosePoint (float &x, float &y, float &z, float size, float distance2d=0, float relAngle=0, float controlZ=0) const
bool GetClosePoint (float &x, float &y, float &z, float size, float distance2d=0, float angle=0, WorldObject const *forWho=nullptr, bool force=false) const
void MovePosition (Position &pos, float dist, float angle)
Position GetNearPosition (float dist, float angle)
void MovePositionToFirstCollision (Position &pos, float dist, float angle)
Position GetFirstCollisionPosition (float startX, float startY, float startZ, float destX, float destY)
Position GetFirstCollisionPosition (float destX, float destY, float destZ)
Position GetFirstCollisionPosition (float dist, float angle)
Position GetRandomNearPosition (float radius)
void GetContactPoint (WorldObject const *obj, float &x, float &y, float &z, float distance2d=CONTACT_DISTANCE) const
void GetChargeContactPoint (WorldObject const *obj, float &x, float &y, float &z, float distance2d=CONTACT_DISTANCE) const
float GetObjectSize () const
virtual float GetCombatReach () const
void UpdateGroundPositionZ (float x, float y, float &z) const
void UpdateAllowedPositionZ (float x, float y, float &z, float *groundZ=nullptr) const
void GetRandomPoint (const Position &srcPos, float distance, float &rand_x, float &rand_y, float &rand_z) const
Position GetRandomPoint (const Position &srcPos, float distance) const
uint32 GetInstanceId () const
virtual void SetPhaseMask (uint32 newPhaseMask, bool update)
uint32 GetPhaseMask () const
bool InSamePhase (WorldObject const *obj) const
bool InSamePhase (uint32 phasemask) const
uint32 GetZoneId () const
uint32 GetAreaId () const
void GetZoneAndAreaId (uint32 &zoneid, uint32 &areaid) const
bool IsOutdoors () const
LiquidData const & GetLiquidData () const
InstanceScript * GetInstanceScript () const
std::string const & GetName () const
void SetName (std::string const &newname)
virtual std::string const & GetNameForLocaleIdx (LocaleConstant) const
float GetDistance (WorldObject const *obj) const
float GetDistance (const Position &pos) const
float GetDistance (float x, float y, float z) const
float GetDistance2d (WorldObject const *obj) const
float GetDistance2d (float x, float y) const
float GetDistanceZ (WorldObject const *obj) const
bool IsSelfOrInSameMap (WorldObject const *obj) const
bool IsInMap (WorldObject const *obj) const
bool IsWithinDist3d (float x, float y, float z, float dist) const
bool IsWithinDist3d (const Position *pos, float dist) const
bool IsWithinDist2d (float x, float y, float dist) const
bool IsWithinDist2d (const Position *pos, float dist) const
bool IsWithinDist (WorldObject const *obj, float dist2compare, bool is3D=true, bool incOwnRadius=true, bool incTargetRadius=true) const
bool IsWithinDistInMap (WorldObject const *obj, float dist2compare, bool is3D=true, bool incOwnRadius=true, bool incTargetRadius=true) const
bool IsWithinLOS (float x, float y, float z, VMAP::ModelIgnoreFlags ignoreFlags=VMAP::ModelIgnoreFlags::Nothing, LineOfSightChecks checks=LINEOFSIGHT_ALL_CHECKS) const
bool IsWithinLOSInMap (WorldObject const *obj, VMAP::ModelIgnoreFlags ignoreFlags=VMAP::ModelIgnoreFlags::Nothing, LineOfSightChecks checks=LINEOFSIGHT_ALL_CHECKS, Optional< float > collisionHeight={ }, Optional< float > combatReach={ }) const
Position GetHitSpherePointFor (Position const &dest, Optional< float > collisionHeight={ }, Optional< float > combatReach={ }) const
void GetHitSpherePointFor (Position const &dest, float &x, float &y, float &z, Optional< float > collisionHeight={ }, Optional< float > combatReach={ }) const
bool GetDistanceOrder (WorldObject const *obj1, WorldObject const *obj2, bool is3D=true) const
bool IsInRange (WorldObject const *obj, float minRange, float maxRange, bool is3D=true) const
bool IsInRange2d (float x, float y, float minRange, float maxRange) const
bool IsInRange3d (float x, float y, float z, float minRange, float maxRange) const
bool isInFront (WorldObject const *target, float arc=M_PI) const
bool isInBack (WorldObject const *target, float arc=M_PI) const
bool IsInBetween (WorldObject const *obj1, WorldObject const *obj2, float size=0) const
virtual void CleanupsBeforeDelete (bool finalCleanup=true)
virtual void SendMessageToSet (WorldPacket const *data, bool self) const
virtual void SendMessageToSetInRange (WorldPacket const *data, float dist, bool self) const
virtual void SendMessageToSet (WorldPacket const *data, Player const *skipped_rcvr) const
virtual uint8 getLevelForTarget (WorldObject const *) const
void PlayDistanceSound (uint32 sound_id, Player *target=nullptr)
void PlayDirectSound (uint32 sound_id, Player *target=nullptr)
void PlayRadiusSound (uint32 sound_id, float radius)
void PlayDirectMusic (uint32 music_id, Player *target=nullptr)
void PlayRadiusMusic (uint32 music_id, float radius)
template<typename Worker >
void DoForAllVisiblePlayers (Worker &&worker)
template<typename Worker >
void DoForAllVisibleWorldObjects (Worker &&worker)
void DestroyForVisiblePlayers ()
void SendObjectDeSpawnAnim (ObjectGuid guid)
virtual void SaveRespawnTime ()
void AddObjectToRemoveList ()
float GetGridActivationRange () const
float GetVisibilityRange () const
virtual float GetSightRange (WorldObject const *target=nullptr) const
bool CanSeeOrDetect (WorldObject const *obj, bool ignoreStealth=false, bool distanceCheck=false, bool checkAlert=false) const
void SendPlayMusic (uint32 Music, bool OnlySelf)
virtual void SetMap (Map *map)
virtual void ResetMap ()
Map * GetMap () const
Map * FindMap () const
void SetZoneScript ()
void ClearZoneScript ()
ZoneScript * GetZoneScript () const
TempSummon * SummonCreature (uint32 id, const Position &pos, TempSummonType spwtype=TEMPSUMMON_MANUAL_DESPAWN, uint32 despwtime=0, uint32 vehId=0, SummonPropertiesEntry const *properties=nullptr, bool visibleBySummonerOnly=false) const
TempSummon * SummonCreature (uint32 id, float x, float y, float z, float ang=0, TempSummonType spwtype=TEMPSUMMON_MANUAL_DESPAWN, uint32 despwtime=0, SummonPropertiesEntry const *properties=nullptr, bool visibleBySummonerOnly=false)
GameObject * SummonGameObject (uint32 entry, float x, float y, float z, float ang, float rotation0, float rotation1, float rotation2, float rotation3, uint32 respawnTime, bool checkTransport=true, GOSummonType summonType=GO_SUMMON_TIMED_OR_CORPSE_DESPAWN)
Creature * SummonTrigger (float x, float y, float z, float ang, uint32 dur, bool setLevel=false, CreatureAI *(*GetAI)(Creature *)=nullptr)
void SummonCreatureGroup (uint8 group, std::list< TempSummon * > *list=nullptr)
Creature * FindNearestCreature (uint32 entry, float range, bool alive=true) const
GameObject * FindNearestGameObject (uint32 entry, float range, bool onlySpawned=false) const
GameObject * FindNearestGameObjectOfType (GameobjectTypes type, float range) const
Player * SelectNearestPlayer (float distance=0) const
void GetGameObjectListWithEntryInGrid (std::list< GameObject * > &lList, uint32 uiEntry, float fMaxSearchRange) const
void GetGameObjectListWithEntryInGrid (std::list< GameObject * > &gameobjectList, std::vector< uint32 > const &entries, float maxSearchRange) const
void GetCreatureListWithEntryInGrid (std::list< Creature * > &lList, uint32 uiEntry, float fMaxSearchRange) const
void GetCreatureListWithEntryInGrid (std::list< Creature * > &creatureList, std::vector< uint32 > const &entries, float maxSearchRange) const
void GetDeadCreatureListInGrid (std::list< Creature * > &lList, float maxSearchRange, bool alive=false) const
virtual void UpdateObjectVisibility (bool forced=true, bool fromUpdate=false)
virtual void UpdateObjectVisibilityOnCreate ()
void BuildUpdate (UpdateDataMapType &data_map) override
void GetCreaturesWithEntryInRange (std::list< Creature * > &creatureList, float radius, uint32 entry)
void SetPositionDataUpdate ()
void UpdatePositionData ()
void AddToObjectUpdate () override
void RemoveFromObjectUpdate () override
void AddToNotify (uint16 f)
void RemoveFromNotify (uint16 f)
bool isNeedNotify (uint16 f) const
uint16 GetNotifyFlags () const
bool NotifyExecuted (uint16 f) const
void SetNotified (uint16 f)
void ResetAllNotifies ()
bool isActiveObject () const
void setActive (bool isActiveObject)
VisibilityDistanceType GetVisibilityOverrideType () const
bool IsVisibilityOverridden () const
bool IsZoneWideVisible () const
bool IsFarVisible () const
float GetVisibilityOverrideDistance () const
void SetVisibilityDistanceOverride (VisibilityDistanceType type)
bool IsInWintergrasp () const
Transport * GetTransport () const
float GetTransOffsetX () const
float GetTransOffsetY () const
float GetTransOffsetZ () const
float GetTransOffsetO () const
uint32 GetTransTime () const
int8 GetTransSeat () const
virtual ObjectGuid GetTransGUID () const
void SetTransport (Transport *t)
virtual float GetStationaryX () const
virtual float GetStationaryY () const
virtual float GetStationaryZ () const
virtual float GetStationaryO () const
float GetMapWaterOrGroundLevel (Position pos, float *ground=nullptr) const
float GetMapWaterOrGroundLevel (float x, float y, float z, float *ground=nullptr) const
float GetMapHeight (float x, float y, float z, bool vmap=true, float distanceToSearch=50.0f) const
float GetFloorZ () const
float GetMinHeightInWater () const
Get the minimum height of a object that should be in water to start floating/swim.
virtual float GetCollisionHeight () const
virtual float GetCollisionWidth () const
virtual float GetCollisionRadius () const
void AddAllowedLooter (ObjectGuid guid)
void ResetAllowedLooters ()
void SetAllowedLooters (GuidUnorderedSet const looters)
bool HasAllowedLooter (ObjectGuid guid) const
GuidUnorderedSet const & GetAllowedLooters () const
void RemoveAllowedLooter (ObjectGuid guid)
virtual bool IsUpdateNeeded ()
bool CanBeAddedToMapUpdateList ()
std::string GetDebugInfo () const override
ObjectVisibilityContainer & GetObjectVisibilityContainer ()
ObjectVisibilityContainer const & GetObjectVisibilityContainer () const
Public Member Functions inherited from Object
virtual ~Object ()
bool IsInWorld () const
ObjectGuid GetGUID () const
PackedGuid const & GetPackGUID () const
uint32 GetEntry () const
void SetEntry (uint32 entry)
float GetObjectScale () const
virtual void SetObjectScale (float scale)
virtual uint32 GetDynamicFlags () const
bool HasDynamicFlag (uint32 flag) const
virtual void SetDynamicFlag (uint32 flag)
virtual void RemoveDynamicFlag (uint32 flag)
virtual void ReplaceAllDynamicFlags (uint32 flag)
TypeID GetTypeId () const
bool isType (uint16 mask) const
virtual void BuildCreateUpdateBlockForPlayer (UpdateData *data, Player *target)
void SendUpdateToPlayer (Player *player)
void BuildValuesUpdateBlockForPlayer (UpdateData *data, Player *target)
void BuildOutOfRangeUpdateBlock (UpdateData *data) const
void BuildMovementUpdateBlock (UpdateData *data, uint32 flags=0) const
virtual void DestroyForPlayer (Player *target, bool onDeath=false) const
int32 GetInt32Value (uint16 index) const
uint32 GetUInt32Value (uint16 index) const
uint64 GetUInt64Value (uint16 index) const
float GetFloatValue (uint16 index) const
uint8 GetByteValue (uint16 index, uint8 offset) const
uint16 GetUInt16Value (uint16 index, uint8 offset) const
ObjectGuid GetGuidValue (uint16 index) const
void SetInt32Value (uint16 index, int32 value)
void SetUInt32Value (uint16 index, uint32 value)
void UpdateUInt32Value (uint16 index, uint32 value)
void SetUInt64Value (uint16 index, uint64 value)
void SetFloatValue (uint16 index, float value)
void SetByteValue (uint16 index, uint8 offset, uint8 value)
void SetUInt16Value (uint16 index, uint8 offset, uint16 value)
void SetInt16Value (uint16 index, uint8 offset, int16 value)
void SetGuidValue (uint16 index, ObjectGuid value)
void SetStatFloatValue (uint16 index, float value)
void SetStatInt32Value (uint16 index, int32 value)
bool AddGuidValue (uint16 index, ObjectGuid value)
bool RemoveGuidValue (uint16 index, ObjectGuid value)
void ApplyModUInt32Value (uint16 index, int32 val, bool apply)
void ApplyModInt32Value (uint16 index, int32 val, bool apply)
void ApplyModUInt64Value (uint16 index, int32 val, bool apply)
void ApplyModPositiveFloatValue (uint16 index, float val, bool apply)
void ApplyModSignedFloatValue (uint16 index, float val, bool apply)
void SetFlag (uint16 index, uint32 newFlag)
void RemoveFlag (uint16 index, uint32 oldFlag)
void ToggleFlag (uint16 index, uint32 flag)
bool HasFlag (uint16 index, uint32 flag) const
void ApplyModFlag (uint16 index, uint32 flag, bool apply)
void SetByteFlag (uint16 index, uint8 offset, uint8 newFlag)
void RemoveByteFlag (uint16 index, uint8 offset, uint8 newFlag)
bool HasByteFlag (uint16 index, uint8 offset, uint8 flag) const
void SetFlag64 (uint16 index, uint64 newFlag)
void RemoveFlag64 (uint16 index, uint64 oldFlag)
void ToggleFlag64 (uint16 index, uint64 flag)
bool HasFlag64 (uint16 index, uint64 flag) const
void ApplyModFlag64 (uint16 index, uint64 flag, bool apply)
void ClearUpdateMask (bool remove)
uint16 GetValuesCount () const
virtual bool hasQuest (uint32) const
virtual bool hasInvolvedQuest (uint32) const
void BuildFieldsUpdate (Player *, UpdateDataMapType &)
void SetFieldNotifyFlag (uint16 flag)
void RemoveFieldNotifyFlag (uint16 flag)
void ForceValuesUpdateAtIndex (uint32)
bool IsPlayer () const
Player * ToPlayer ()
Player const * ToPlayer () const
bool IsCreature () const
Creature * ToCreature ()
Creature const * ToCreature () const
bool IsUnit () const
Unit * ToUnit ()
Unit const * ToUnit () const
bool IsGameObject () const
GameObject * ToGameObject ()
GameObject const * ToGameObject () const
bool IsCorpse () const
Corpse * ToCorpse ()
Corpse const * ToCorpse () const
bool IsDynamicObject () const
DynamicObject * ToDynObject ()
DynamicObject const * ToDynObject () const
bool IsItem () const
virtual void Heartbeat ()
template<typename... T>
bool EntryEquals (T... entries) const
Public Member Functions inherited from WorldLocation
WorldLocation (uint32 _mapId=MAPID_INVALID, float x=0.f, float y=0.f, float z=0.f, float o=0.f)
WorldLocation (uint32 mapId, Position const &position)
void WorldRelocate (const WorldLocation &loc)
void WorldRelocate (uint32 mapId=MAPID_INVALID, float x=0.f, float y=0.f, float z=0.f, float o=0.f)
void SetMapId (uint32 mapId)
uint32 GetMapId () const
void GetWorldLocation (uint32 &mapId, float &x, float &y) const
void GetWorldLocation (uint32 &mapId, float &x, float &y, float &z) const
void GetWorldLocation (uint32 &mapId, float &x, float &y, float &z, float &o) const
void GetWorldLocation (WorldLocation *location) const
WorldLocation GetWorldLocation () const
std::string GetDebugInfo () const
Public Member Functions inherited from Position
Position (float x=0, float y=0, float z=0, float o=0)
Position (Position const &loc)
Position (Position &&)=default
Position & operator= (const Position &)=default
Position & operator= (Position &&)=default
bool operator== (Position const &a) const
bool operator!= (Position const &a)
bool operator!= (Position const &a) const
operator G3D::Vector3 () const
void Relocate (float x, float y)
void Relocate (float x, float y, float z)
void Relocate (float x, float y, float z, float orientation)
void Relocate (const Position &pos)
void Relocate (const Position *pos)
void RelocatePolarOffset (float angle, float dist, float z=0.0f)
void RelocateOffset (const Position &offset)
void SetOrientation (float orientation)
float GetPositionX () const
float GetPositionY () const
float GetPositionZ () const
float GetOrientation () const
void GetPosition (float &x, float &y) const
void GetPosition (float &x, float &y, float &z) const
void GetPosition (float &x, float &y, float &z, float &o) const
Position GetPosition () const
Position::PositionXYZStreamer PositionXYZStream ()
Position::PositionXYZOStreamer PositionXYZOStream ()
bool IsPositionValid () const
float GetExactDist2dSq (const float x, const float y) const
float GetExactDist2dSq (Position const &pos) const
float GetExactDist2dSq (Position const *pos) const
float GetExactDist2d (const float x, const float y) const
float GetExactDist2d (Position const &pos) const
float GetExactDist2d (Position const *pos) const
float GetExactDistSq (float x, float y, float z) const
float GetExactDistSq (Position const &pos) const
float GetExactDistSq (Position const *pos) const
float GetExactDist (float x, float y, float z) const
float GetExactDist (Position const &pos) const
float GetExactDist (Position const *pos) const
void GetPositionOffsetTo (const Position &endPos, Position &retOffset) const
Position GetPositionWithOffset (Position const &offset) const
float GetAngle (const Position *pos) const
float GetAngle (float x, float y) const
float GetAbsoluteAngle (float x, float y) const
float GetAbsoluteAngle (Position const &pos) const
float GetAbsoluteAngle (Position const *pos) const
float GetRelativeAngle (const Position *pos) const
float GetRelativeAngle (float x, float y) const
float ToAbsoluteAngle (float relAngle) const
void GetSinCos (float x, float y, float &vsin, float &vcos) const
bool IsInDist2d (float x, float y, float dist) const
bool IsInDist2d (const Position *pos, float dist) const
bool IsInDist (float x, float y, float z, float dist) const
bool IsInDist (const Position *pos, float dist) const
bool IsWithinBox (const Position &center, float xradius, float yradius, float zradius) const
bool HasInArc (float arcangle, const Position *pos, float targetRadius=0.0f) const
bool HasInLine (Position const *pos, float width) const
bool HasInLine (Position const *pos, float objSize, float width) const
std::string ToString () const
Public Attributes
FlaggedValuesArray32< int32, uint32, StealthType, TOTAL_STEALTH_TYPES > m_stealth
FlaggedValuesArray32< int32, uint32, StealthType, TOTAL_STEALTH_TYPES > m_stealthDetect
FlaggedValuesArray32< int32, uint32, InvisibilityType, TOTAL_INVISIBILITY_TYPES > m_invisibility
FlaggedValuesArray32< int32, uint32, InvisibilityType, TOTAL_INVISIBILITY_TYPES > m_invisibilityDetect
FlaggedValuesArray32< int32, uint32, ServerSideVisibilityType, TOTAL_SERVERSIDE_VISIBILITY_TYPES > m_serverSideVisibility
FlaggedValuesArray32< int32, uint32, ServerSideVisibilityType, TOTAL_SERVERSIDE_VISIBILITY_TYPES > m_serverSideVisibilityDetect
uint32 LastUsedScriptID
MovementInfo m_movementInfo
ALEEventProcessor * ALEEvents
EventProcessor m_Events
Public Attributes inherited from Object
DataMap CustomData
Public Attributes inherited from WorldLocation
uint32 m_mapId
Public Attributes inherited from Position
float m_positionX = 0
float m_positionY = 0
float m_positionZ = 0
float m_orientation = 0
Protected Member Functions
WorldObject ()
virtual void ProcessPositionDataChanged (PositionFullTerrainStatus const &data)
void SetLocationMapId (uint32 _mapId)
void SetLocationInstanceId (uint32 _instanceId)
virtual bool IsNeverVisible () const
virtual bool IsAlwaysVisibleFor (WorldObject const *) const
virtual bool IsInvisibleDueToDespawn () const
virtual bool IsAlwaysDetectableFor (WorldObject const *) const
Protected Member Functions inherited from Object
Object ()
void _InitValues ()
void _Create (ObjectGuid::LowType guidlow, uint32 entry, HighGuid guidhigh)
std::string _ConcatFields (uint16 startIndex, uint16 size) const
bool _LoadIntoDataField (std::string const &data, uint32 startOffset, uint32 count)
uint32 GetUpdateFieldData (Player const *target, uint32 *&flags) const
void BuildMovementUpdate (ByteBuffer *data, uint16 flags) const
virtual void BuildValuesUpdate (uint8 updateType, ByteBuffer *data, Player *target)
void AddToObjectUpdateIfNeeded ()
Protected Attributes
std::string m_name
bool m_isActive
VisibilityDistanceType _visibilityDistanceOverrideType
ZoneScript * m_zoneScript
uint32 _zoneId
uint32 _areaId
float _floorZ
bool _outdoors
LiquidData _liquidData
bool _updatePositionData
Transport * m_transport
Protected Attributes inherited from Object
uint16 m_objectType
TypeID m_objectTypeId
uint16 m_updateFlag
union {
int32 * m_int32Values
uint32 * m_uint32Values
float * m_floatValues
};
UpdateMask _changesMask
uint16 m_valuesCount
uint16 _fieldNotifyFlags
bool m_objectUpdated
Private Member Functions
virtual bool _IsWithinDist (WorldObject const *obj, float dist2compare, bool is3D, bool incOwnRadius=true, bool incTargetRadius=true) const
bool CanNeverSee (WorldObject const *obj) const
virtual bool CanAlwaysSee (WorldObject const *) const
bool CanDetect (WorldObject const *obj, bool ignoreStealth, bool checkClient, bool checkAlert=false) const
bool CanDetectInvisibilityOf (WorldObject const *obj) const
bool CanDetectStealthOf (WorldObject const *obj, bool checkAlert=false) const
void RemoveFromMapVisibilityOverrideContainers ()
void AddToMapVisibilityOverrideContainers ()
Private Attributes
Map * m_currMap
Milliseconds _heartbeatTimer
uint32 m_InstanceId
uint32 m_phaseMask
bool m_useCombinedPhases
uint16 m_notifyflags
uint16 m_executed_notifies
GuidUnorderedSet _allowedLooters
ObjectVisibilityContainer _objectVisibilityContainer
Additional Inherited Members
Static Public Member Functions inherited from Object
static ObjectGuid GetGUID (Object const *o)
Static Public Member Functions inherited from Position
static float NormalizeOrientation (float o)
Detailed Description
Constructor & Destructor Documentation
WorldObject()
WorldObject::WorldObject () explicit protected
                         : WorldLocation(),
    LastUsedScriptID(0), m_name(""), m_isActive(false), _visibilityDistanceOverrideType(VisibilityDistanceType::Normal), m_zoneScript(nullptr),
    _zoneId(0), _areaId(0), _floorZ(INVALID_HEIGHT), _outdoors(false), _liquidData(), _updatePositionData(false), m_transport(nullptr),
    m_currMap(nullptr), _heartbeatTimer(HEARTBEAT_INTERVAL), m_InstanceId(0), m_phaseMask(PHASEMASK_NORMAL), m_useCombinedPhases(true),
    m_notifyflags(0), m_executed_notifies(0), _objectVisibilityContainer(this)
{
    m_serverSideVisibility.SetValue(SERVERSIDE_VISIBILITY_GHOST, GHOST_VISIBILITY_ALIVE | GHOST_VISIBILITY_GHOST);
    m_serverSideVisibilityDetect.SetValue(SERVERSIDE_VISIBILITY_GHOST, GHOST_VISIBILITY_ALIVE);
    sScriptMgr->OnWorldObjectCreate(this);
}
References GHOST_VISIBILITY_ALIVE, GHOST_VISIBILITY_GHOST, m_serverSideVisibility, m_serverSideVisibilityDetect, SERVERSIDE_VISIBILITY_GHOST, FlaggedValuesArray32< T_VALUES, T_FLAGS, FLAG_TYPE, ARRAY_SIZE >::SetValue(), and sScriptMgr.
~WorldObject()
WorldObject::~WorldObject () override
{
    sScriptMgr->OnWorldObjectDestroy(this);
}
References sScriptMgr.
Member Function Documentation
_Create()
void WorldObject::_Create (ObjectGuid::LowType guidlow, HighGuid guidhigh, uint32 phaseMask)
{
    Object::_Create(guidlow, 0, guidhigh);
    SetPhaseMask(phaseMask, false);
}
References Object::_Create(), and SetPhaseMask().
Referenced by Corpse::Create(), and DynamicObject::CreateDynamicObject().
_IsWithinDist()
bool WorldObject::_IsWithinDist (WorldObject const * obj, float dist2compare, bool is3D, bool incOwnRadius = true, bool incTargetRadius = true) const private virtual
Reimplemented in GameObject.
{
    float maxdist = dist2compare;
    if (incOwnRadius)
        maxdist += GetObjectSize();
    if (incTargetRadius)
        maxdist += obj->GetObjectSize();
    if (m_transport && obj->GetTransport() &&  obj->GetTransport()->GetGUID() == m_transport->GetGUID())
    {
        float dtx = m_movementInfo.transport.pos.m_positionX - obj->m_movementInfo.transport.pos.m_positionX;
        float dty = m_movementInfo.transport.pos.m_positionY - obj->m_movementInfo.transport.pos.m_positionY;
        float disttsq = dtx * dtx + dty * dty;
        if (is3D)
        {
            float dtz = m_movementInfo.transport.pos.m_positionZ - obj->m_movementInfo.transport.pos.m_positionZ;
            disttsq += dtz * dtz;
        }
        return disttsq < (maxdist * maxdist);
    }
    float dx = GetPositionX() - obj->GetPositionX();
    float dy = GetPositionY() - obj->GetPositionY();
    float distsq = dx * dx + dy * dy;
    if (is3D)
    {
        float dz = GetPositionZ() - obj->GetPositionZ();
        distsq += dz * dz;
    }
    return distsq < maxdist * maxdist;
}
References Object::GetGUID(), GetObjectSize(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), GetTransport(), m_movementInfo, Position::m_positionX, Position::m_positionY, Position::m_positionZ, m_transport, MovementInfo::TransportInfo::pos, and MovementInfo::transport.
Referenced by IsWithinDist(), and IsWithinDistInMap().
AddAllowedLooter()
void WorldObject::AddAllowedLooter (ObjectGuid guid)
{
    _allowedLooters.insert(guid);
}
References _allowedLooters.
Referenced by GameObject::SetLootRecipient(), and Creature::SetLootRecipient().
AddObjectToRemoveList()
void WorldObject::AddObjectToRemoveList ()
{
    ASSERT(m_uint32Values);
    Map* map = FindMap();
    if (!map)
    {
        LOG_ERROR("entities.object", "Object {} at attempt add to move list not have valid map (Id: {}).", GetGUID().ToString(), GetMapId());
        return;
    }
    map->AddObjectToRemoveList(this);
}
References Map::AddObjectToRemoveList(), ASSERT, FindMap(), Object::GetGUID(), WorldLocation::GetMapId(), LOG_ERROR, Object::m_uint32Values, and Position::ToString().
Referenced by MotionTransport::DelayedTeleportTransport(), Battleground::DelCreature(), OPvPCapturePoint::DelCreature(), GameObject::Delete(), OPvPCapturePointNA::DespawnCreatures(), CinematicMgr::EndCinematic(), ResetEncounterEvent::Execute(), npc_commandscript::HandleNpcDeleteCommand(), SmartScript::ProcessAction(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::ProcessEvent(), DynamicObject::Remove(), Player::RemovePet(), go_firework_show::SpawnNextFirework(), npc_midsummer_bonfire::StampOut(), MotionTransport::UnloadStaticPassengers(), TempSummon::UnSummon(), Totem::UnSummon(), and outdoorpvp_na_halaa_creatures::UpdateAI().
AddToMapVisibilityOverrideContainers()
void WorldObject::AddToMapVisibilityOverrideContainers () private
{
    if (!IsVisibilityOverridden())
        return;
    if (!IsInWorld())
        return;
    if (IsFarVisible())
        GetMap()->AddWorldObjectToFarVisibleMap(this);
    else if (IsZoneWideVisible())
        GetMap()->AddWorldObjectToZoneWideVisibleMap(_zoneId, this);
}
References _zoneId, Map::AddWorldObjectToFarVisibleMap(), Map::AddWorldObjectToZoneWideVisibleMap(), GetMap(), IsFarVisible(), Object::IsInWorld(), IsVisibilityOverridden(), and IsZoneWideVisible().
Referenced by SetVisibilityDistanceOverride().
AddToNotify()
void WorldObject::AddToNotify (uint16 f)
{
    if (!(m_notifyflags & f))
        if (Unit* u = ToUnit())
        {
            if (f & NOTIFY_VISIBILITY_CHANGED)
            {
                uint32 EVENT_VISIBILITY_DELAY = u->FindMap() ? DynamicVisibilityMgr::GetVisibilityNotifyDelay(u->FindMap()->GetEntry()->map_type) : 1000;
                uint32 diff = getMSTimeDiff(u->m_last_notify_mstime, GameTime::GetGameTimeMS().count());
                if (diff >= EVENT_VISIBILITY_DELAY / 2)
                    EVENT_VISIBILITY_DELAY /= 2;
                else
                    EVENT_VISIBILITY_DELAY -= diff;
                u->m_delayed_unit_relocation_timer = EVENT_VISIBILITY_DELAY;
                u->m_last_notify_mstime = GameTime::GetGameTimeMS().count() + EVENT_VISIBILITY_DELAY - 1;
            }
            else if (f & NOTIFY_AI_RELOCATION)
            {
                u->m_delayed_unit_ai_notify_timer = u->FindMap() ? DynamicVisibilityMgr::GetAINotifyDelay(u->FindMap()->GetEntry()->map_type) : 500;
            }
            m_notifyflags |= f;
        }
}
References DynamicVisibilityMgr::GetAINotifyDelay(), GameTime::GetGameTimeMS(), getMSTimeDiff(), DynamicVisibilityMgr::GetVisibilityNotifyDelay(), m_notifyflags, NOTIFY_AI_RELOCATION, NOTIFY_VISIBILITY_CHANGED, and Object::ToUnit().
Referenced by Unit::ExecuteDelayedUnitRelocationEvent(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnCreatureCreate(), Unit::SetContestedPvP(), Player::UpdateObjectVisibility(), and Unit::UpdateObjectVisibility().
AddToObjectUpdate()
void WorldObject::AddToObjectUpdate () override virtual
Implements Object.
{
    GetMap()->AddUpdateObject(this);
}
References Map::AddUpdateObject(), and GetMap().
AddToWorld()
void WorldObject::AddToWorld () override virtual
Reimplemented from Object.
{
    Object::AddToWorld();
    GetMap()->GetZoneAndAreaId(GetPhaseMask(), _zoneId, _areaId, GetPositionX(), GetPositionY(), GetPositionZ());
    GetMap()->AddObjectToPendingUpdateList(this);
    if (IsZoneWideVisible())
        GetMap()->AddWorldObjectToZoneWideVisibleMap(_zoneId, this);
}
References _areaId, _zoneId, Map::AddObjectToPendingUpdateList(), Object::AddToWorld(), Map::AddWorldObjectToZoneWideVisibleMap(), GetMap(), GetPhaseMask(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Map::GetZoneAndAreaId(), and IsZoneWideVisible().
Referenced by DynamicObject::AddToWorld(), GameObject::AddToWorld(), and Unit::AddToWorld().
BuildUpdate()
void WorldObject::BuildUpdate (UpdateDataMapType & data_map) override virtual
Reimplemented from Object.
{
    // Build update for self
    if (IsPlayer())
        BuildFieldsUpdate(ToPlayer(), data_map);
    // Build update for visible players
    DoForAllVisiblePlayers([this, &data_map](Player* player)
    {
        BuildFieldsUpdate(player, data_map);
    });
    ClearUpdateMask(false);
}
References Object::BuildFieldsUpdate(), Object::ClearUpdateMask(), DoForAllVisiblePlayers(), Object::IsPlayer(), and Object::ToPlayer().
CanAlwaysSee()
virtual bool WorldObject::CanAlwaysSee (WorldObject const *) const inline private virtual
Reimplemented in Creature, and Player.
{ return false; }
Referenced by CanSeeOrDetect().
CanBeAddedToMapUpdateList()
bool WorldObject::CanBeAddedToMapUpdateList ()
{
    switch (GetTypeId())
    {
    case TYPEID_UNIT:
        return IsCreature();
    case TYPEID_DYNAMICOBJECT:
    case TYPEID_GAMEOBJECT:
        return true;
    default:
        return false;
    }
    return false;
}
References Object::GetTypeId(), Object::IsCreature(), TYPEID_DYNAMICOBJECT, TYPEID_GAMEOBJECT, and TYPEID_UNIT.
Referenced by Map::AddObjectToPendingUpdateList(), and Map::RemoveObjectFromMapUpdateList().
CanDetect()
bool WorldObject::CanDetect (WorldObject const * obj, bool ignoreStealth, bool checkClient, bool checkAlert = false) const private
{
    WorldObject const* seer = this;
    // Pets don't have detection, they use the detection of their masters
    if (Unit const* thisUnit = ToUnit())
        if (Unit* controller = thisUnit->GetCharmerOrOwner())
            seer = controller;
    if (obj->IsAlwaysDetectableFor(seer) || GetEntry() == WORLD_TRIGGER) // xinef: World Trigger can detect all objects, used for wild gameobjects without owner!
        return true;
    if (!ignoreStealth)
    {
        if (!seer->CanDetectInvisibilityOf(obj)) // xinef: added ignoreStealth, allow AoE spells to hit invisible targets!
        {
            return false;
        }
        if (!seer->CanDetectStealthOf(obj, checkAlert))
        {
            // xinef: ignore units players have at client, this cant be cheated!
            if (checkClient)
            {
                if (!IsPlayer() || !ToPlayer()->HaveAtClient(obj))
                    return false;
            }
            else
                return false;
        }
    }
    return true;
}
References CanDetectInvisibilityOf(), CanDetectStealthOf(), Unit::GetCharmerOrOwner(), Object::GetEntry(), IsAlwaysDetectableFor(), Object::IsPlayer(), Object::ToPlayer(), Object::ToUnit(), and WORLD_TRIGGER.
Referenced by CanSeeOrDetect().
CanDetectInvisibilityOf()
bool WorldObject::CanDetectInvisibilityOf (WorldObject const * obj) const private
{
    uint32 mask = obj->m_invisibility.GetFlags() & m_invisibilityDetect.GetFlags();
    // xinef: include invisible flags of caster in the mask, 2 invisible objects should be able to detect eachother
    mask |= obj->m_invisibility.GetFlags() & m_invisibility.GetFlags();
    // Check for not detected types
    if (mask != obj->m_invisibility.GetFlags())
        return false;
    // It isn't possible in invisibility to detect something that can't detect the invisible object
    // (it's at least true for spell: 66)
    // It seems like that only Units are affected by this check (couldn't see arena doors with preparation invisibility)
    if (obj->ToUnit())
    {
        // Permanently invisible creatures should be able to engage non-invisible targets.
        // ex. Skulking Witch (20882) / Greater Invisibility (16380)
        bool isPermInvisibleCreature = false;
        if (Creature const* baseObj = ToCreature())
        {
            Unit::AuraEffectList const& auraEffects = baseObj->GetAuraEffectsByType(SPELL_AURA_MOD_INVISIBILITY);
            for (AuraEffect* const effect : auraEffects)
            {
                if (SpellInfo const* spell = effect->GetSpellInfo())
                {
                    if (spell->GetMaxDuration() == -1)
                    {
                        isPermInvisibleCreature = true;
                    }
                }
            }
        }
        if (!isPermInvisibleCreature)
        {
            uint32 objMask = m_invisibility.GetFlags() & obj->m_invisibilityDetect.GetFlags();
            // xinef: include invisible flags of caster in the mask, 2 invisible objects should be able to detect eachother
            objMask |= m_invisibility.GetFlags() & obj->m_invisibility.GetFlags();
            if (objMask != m_invisibility.GetFlags())
                return false;
        }
    }
    for (uint32 i = 0; i < TOTAL_INVISIBILITY_TYPES; ++i)
    {
        if (!(mask & (1 << i)))
            continue;
        // xinef: visible for the same invisibility type:
        if (m_invisibility.GetValue(InvisibilityType(i)) && obj->m_invisibility.GetValue(InvisibilityType(i)))
            continue;
        int32 objInvisibilityValue = obj->m_invisibility.GetValue(InvisibilityType(i));
        int32 ownInvisibilityDetectValue = m_invisibilityDetect.GetValue(InvisibilityType(i));
        // Too low value to detect
        if (ownInvisibilityDetectValue < objInvisibilityValue)
            return false;
    }
    return true;
}
References FlaggedValuesArray32< T_VALUES, T_FLAGS, FLAG_TYPE, ARRAY_SIZE >::GetFlags(), FlaggedValuesArray32< T_VALUES, T_FLAGS, FLAG_TYPE, ARRAY_SIZE >::GetValue(), m_invisibility, m_invisibilityDetect, SPELL_AURA_MOD_INVISIBILITY, Object::ToCreature(), TOTAL_INVISIBILITY_TYPES, and Object::ToUnit().
Referenced by CanDetect().
CanDetectStealthOf()
bool WorldObject::CanDetectStealthOf (WorldObject const * obj, bool checkAlert = false) const private
{
    // Combat reach is the minimal distance (both in front and behind),
    //   and it is also used in the range calculation.
    // One stealth point increases the visibility range by 0.3 yard.
    if (!obj->m_stealth.GetFlags())
        return true;
    // dead players shouldnt be able to detect stealth on arenas
    if (isType(TYPEMASK_PLAYER))
        if (!ToPlayer()->IsAlive())
            return false;
    float distance = GetExactDist(obj);
    float combatReach = 0.0f;
    if (IsUnit())
        combatReach = ((Unit*)this)->GetCombatReach();
    if (distance < combatReach)
        return true;
    if (!HasInArc(M_PI, obj))
        return false;
    for (uint32 i = 0; i < TOTAL_STEALTH_TYPES; ++i)
    {
        if (!(obj->m_stealth.GetFlags() & (1 << i)))
            continue;
        if (IsUnit())
            if (((Unit*)this)->HasAuraTypeWithMiscvalue(SPELL_AURA_DETECT_STEALTH, i))
                return true;
        // Starting points
        int32 detectionValue = 30;
        // Level difference: 5 point / level, starting from level 1.
        // There may be spells for this and the starting points too, but
        // not in the DBCs of the client.
        detectionValue += int32(getLevelForTarget(obj) - 1) * 5;
        // Apply modifiers
        detectionValue += m_stealthDetect.GetValue(StealthType(i));
        if (obj->isType(TYPEMASK_GAMEOBJECT))
        {
            detectionValue += 30; // pussywizard: increase detection range for gameobjects (ie. traps)
            if (Unit* owner = ((GameObject*)obj)->GetOwner())
                detectionValue -= int32(owner->getLevelForTarget(this) - 1) * 5;
        }
        detectionValue -= obj->m_stealth.GetValue(StealthType(i));
        // Calculate max distance
        float visibilityRange = float(detectionValue) * 0.3f + combatReach;
        Unit const* unit = ToUnit();
        // If this unit is an NPC then player detect range doesn't apply
        if (unit && unit->IsPlayer() && visibilityRange > MAX_PLAYER_STEALTH_DETECT_RANGE)
            visibilityRange = MAX_PLAYER_STEALTH_DETECT_RANGE;
        if (checkAlert)
            visibilityRange += (visibilityRange * 0.08f) + 1.5f;
        Unit const* targetUnit = obj->ToUnit();
        // If checking for alert, and creature's visibility range is greater than aggro distance, No alert
        if (checkAlert && unit && unit->ToCreature() && visibilityRange >= unit->ToCreature()->GetAttackDistance(targetUnit) + unit->ToCreature()->m_CombatDistance)
            return false;
        if (distance > visibilityRange)
            return false;
    }
    return true;
}
References Creature::GetAttackDistance(), Position::GetExactDist(), FlaggedValuesArray32< T_VALUES, T_FLAGS, FLAG_TYPE, ARRAY_SIZE >::GetFlags(), getLevelForTarget(), FlaggedValuesArray32< T_VALUES, T_FLAGS, FLAG_TYPE, ARRAY_SIZE >::GetValue(), Position::HasInArc(), Object::IsPlayer(), Object::isType(), Object::IsUnit(), Creature::m_CombatDistance, m_stealth, m_stealthDetect, MAX_PLAYER_STEALTH_DETECT_RANGE, SPELL_AURA_DETECT_STEALTH, Object::ToCreature(), Object::ToPlayer(), TOTAL_STEALTH_TYPES, Object::ToUnit(), TYPEMASK_GAMEOBJECT, and TYPEMASK_PLAYER.
Referenced by CanDetect().
CanNeverSee()
bool WorldObject::CanNeverSee (WorldObject const * obj) const private
{
    if (!IsInWorld())
        return true;
    if (obj->IsNeverVisible())
        return true;
    if (IsCreature() && obj->IsCreature())
        return GetMap() != obj->GetMap() || (!InSamePhase(obj) && ToUnit()->GetVehicleBase() != obj && this != obj->ToUnit()->GetVehicleBase());
    return GetMap() != obj->GetMap() || !InSamePhase(obj);
}
References GetMap(), Unit::GetVehicleBase(), InSamePhase(), Object::IsCreature(), Object::IsInWorld(), IsNeverVisible(), and Object::ToUnit().
Referenced by CanSeeOrDetect().
CanSeeOrDetect()
bool WorldObject::CanSeeOrDetect (WorldObject const * obj, bool ignoreStealth = false, bool distanceCheck = false, bool checkAlert = false) const
{
    if (this == obj)
        return true;
    if (CanNeverSee(obj))
        return false;
    if (obj->IsAlwaysVisibleFor(this) || CanAlwaysSee(obj))
        return true;
    // Creature scripts
    if (Creature const* cObj = obj->ToCreature())
    {
        if (Player const* player = ToPlayer())
        {
            if (cObj->IsAIEnabled && !cObj->AI()->CanBeSeen(player))
            {
                return false;
            }
            ConditionList conditions = sConditionMgr->GetConditionsForNotGroupedEntry(CONDITION_SOURCE_TYPE_CREATURE_VISIBILITY, cObj->GetEntry());
            if (!sConditionMgr->IsObjectMeetToConditions((WorldObject*)this, (WorldObject*)obj, conditions))
            {
                return false;
            }
        }
    }
    // Gameobject scripts
    if (GameObject const* goObj = obj->ToGameObject())
    {
        if (ToPlayer() && !goObj->AI()->CanBeSeen(ToPlayer()))
        {
            return false;
        }
    }
    // pussywizard: arena spectator
    if (obj->IsPlayer())
        if (((Player const*)obj)->IsSpectator() && ((Player const*)obj)->FindMap()->IsBattleArena())
            return false;
    bool corpseVisibility = false;
    if (distanceCheck)
    {
        bool corpseCheck = false;
        WorldObject const* viewpoint = this;
        if (Player const* thisPlayer = ToPlayer())
        {
            viewpoint = thisPlayer->GetSeer();
            if (Creature const* creature = obj->ToCreature())
            {
                if (TempSummon const* tempSummon = creature->ToTempSummon())
                {
                    if (tempSummon->IsVisibleBySummonerOnly() && GetGUID() != tempSummon->GetSummonerGUID())
                    {
                        return false;
                    }
                }
            }
            if (thisPlayer->isDead() && thisPlayer->GetHealth() > 0 && // Cheap way to check for ghost state
                    !(obj->m_serverSideVisibility.GetValue(SERVERSIDE_VISIBILITY_GHOST) & m_serverSideVisibility.GetValue(SERVERSIDE_VISIBILITY_GHOST) & GHOST_VISIBILITY_GHOST))
            {
                if (Corpse* corpse = thisPlayer->GetCorpse())
                {
                    corpseCheck = true;
                    if (corpse->IsWithinDist(thisPlayer, GetSightRange(obj), false))
                        if (corpse->IsWithinDist(obj, GetSightRange(obj), false))
                            corpseVisibility = true;
                }
            }
            // our additional checks
            if (Unit const* target = obj->ToUnit())
            {
                // xinef: don't allow to detect vehicle accessory if you can't see vehicle base!
                if (Unit const* vehicle = target->GetVehicleBase())
                    if (!thisPlayer->HaveAtClient(vehicle))
                        return false;
                // pussywizard: during arena preparation, don't allow to detect pets if can't see its owner (spoils enemy arena frames)
                if (target->IsPet() && target->GetOwnerGUID() && target->FindMap()->IsBattleArena() && GetGUID() != target->GetOwnerGUID())
                    if (BattlegroundMap* bgmap = target->FindMap()->ToBattlegroundMap())
                        if (Battleground* bg = bgmap->GetBG())
                            if (bg->GetStatus() < STATUS_IN_PROGRESS && !thisPlayer->HaveAtClient(target->GetOwnerGUID()))
                                return false;
            }
            if (thisPlayer->GetFarSightDistance() && !thisPlayer->isInFront(obj))
                return false;
        }
        // Xinef: check reversely obj vs viewpoint, object could be a gameObject which overrides _IsWithinDist function to include gameobject size
        if (!corpseCheck && !viewpoint->IsWithinDist(obj, GetSightRange(obj), false))
            return false;
    }
    // GM visibility off or hidden NPC
    if (!obj->m_serverSideVisibility.GetValue(SERVERSIDE_VISIBILITY_GM))
    {
        // Stop checking other things for GMs
        if (m_serverSideVisibilityDetect.GetValue(SERVERSIDE_VISIBILITY_GM))
            return true;
    }
    else
        return m_serverSideVisibilityDetect.GetValue(SERVERSIDE_VISIBILITY_GM) >= obj->m_serverSideVisibility.GetValue(SERVERSIDE_VISIBILITY_GM);
    // Ghost players, Spirit Healers, and some other NPCs
    if (!corpseVisibility && !(obj->m_serverSideVisibility.GetValue(SERVERSIDE_VISIBILITY_GHOST) & m_serverSideVisibilityDetect.GetValue(SERVERSIDE_VISIBILITY_GHOST)))
    {
        // Alive players can see dead players in some cases, but other objects can't do that
        if (Player const* thisPlayer = ToPlayer())
        {
            if (Player const* objPlayer = obj->ToPlayer())
            {
                if (thisPlayer->GetTeamId() != objPlayer->GetTeamId() || !thisPlayer->IsGroupVisibleFor(objPlayer))
                    return false;
            }
            else
                return false;
        }
        else
            return false;
    }
    if (obj->IsInvisibleDueToDespawn())
        return false;
    // pussywizard: arena spectator
    if (this->IsPlayer())
        if (((Player const*)this)->IsSpectator() && ((Player const*)this)->FindMap()->IsBattleArena() && (obj->m_invisibility.GetFlags() || obj->m_stealth.GetFlags()))
            return false;
    if (!CanDetect(obj, ignoreStealth, !distanceCheck, checkAlert))
    {
        return false;
    }
    return true;
}
References CanAlwaysSee(), CanDetect(), CanNeverSee(), CONDITION_SOURCE_TYPE_CREATURE_VISIBILITY, FindMap(), FlaggedValuesArray32< T_VALUES, T_FLAGS, FLAG_TYPE, ARRAY_SIZE >::GetFlags(), Object::GetGUID(), GetSightRange(), FlaggedValuesArray32< T_VALUES, T_FLAGS, FLAG_TYPE, ARRAY_SIZE >::GetValue(), Unit::GetVehicleBase(), GHOST_VISIBILITY_GHOST, IsAlwaysVisibleFor(), IsInvisibleDueToDespawn(), Object::IsPlayer(), IsWithinDist(), m_invisibility, m_serverSideVisibility, m_serverSideVisibilityDetect, m_stealth, sConditionMgr, SERVERSIDE_VISIBILITY_GHOST, SERVERSIDE_VISIBILITY_GM, STATUS_IN_PROGRESS, Map::ToBattlegroundMap(), Object::ToCreature(), Object::ToGameObject(), Object::ToPlayer(), Unit::ToTempSummon(), and Object::ToUnit().
Referenced by Unit::_IsValidAssistTarget(), Unit::_IsValidAttackTarget(), Creature::CanAssistTo(), SpellInfo::CheckTarget(), CreatureUnitRelocationWorker(), npc_icc_vengeful_fleshreaper::npc_icc_vengeful_fleshreaperAI::MoveInLineOfSight(), npc_pet_dk_ebon_gargoyle::MySelectNextTarget(), Acore::NearestAttackableUnitInObjectRangeCheck::operator()(), Acore::NearestVisibleDetectableContestedGuardUnitCheck::operator()(), Acore::VisibleNotifier::SendToSelf(), TotemAI::UpdateAI(), Player::UpdateVisibilityOf(), and Player::UpdateVisibilityOf().
CleanupsBeforeDelete()
void WorldObject::CleanupsBeforeDelete (bool finalCleanup = true) virtual
Reimplemented in DynamicObject, GameObject, Player, MotionTransport, StaticTransport, and Unit.
{
    if (IsInWorld())
        RemoveFromWorld();
    m_Events.KillAllEvents(false);                      // non-delatable (currently cast spells) will not deleted now but it will deleted at call in Map::RemoveAllObjectsInRemoveList
}
References Object::IsInWorld(), EventProcessor::KillAllEvents(), m_Events, and RemoveFromWorld().
Referenced by Map::AddObjectToRemoveList(), and DynamicObject::CleanupsBeforeDelete().
ClearZoneScript()
void WorldObject::ClearZoneScript ()
{
    m_zoneScript = nullptr;
}
References m_zoneScript.
DestroyForVisiblePlayers()
void WorldObject::DestroyForVisiblePlayers ()
{
    if (!IsInWorld())
        return;
    VisiblePlayersMap& visiblePlayerMap = GetObjectVisibilityContainer().GetVisiblePlayersMap();
    for (VisiblePlayersMap::iterator itr = visiblePlayerMap.begin(); itr != visiblePlayerMap.end();)
    {
        Player* player = itr->second;
        DestroyForPlayer(player);
        // Clean up visibility references now
        itr = GetObjectVisibilityContainer().UnlinkVisibilityFromWorldObject(player, itr);
    }
}
References Object::DestroyForPlayer(), GetObjectVisibilityContainer(), ObjectVisibilityContainer::GetVisiblePlayersMap(), Object::IsInWorld(), and ObjectVisibilityContainer::UnlinkVisibilityFromWorldObject().
Referenced by Creature::DisappearAndDie(), boss_cyanigosa::boss_cyanigosaAI::JustDied(), Creature::RemoveCorpse(), Map::RemoveCorpse(), RemoveFromWorld(), boss_urom::boss_uromAI::SpellHit(), GameObject::Update(), and go_witherbark_totem_bundle::go_witherbark_totem_bundleAI::UpdateAI().
DoForAllVisiblePlayers()
template<typename Worker > void WorldObject::DoForAllVisiblePlayers (Worker && worker) inline
    {
        for (auto const& kvPair : GetObjectVisibilityContainer().GetVisiblePlayersMap())
            worker(kvPair.second);
    }
References GetObjectVisibilityContainer(), and ObjectVisibilityContainer::GetVisiblePlayersMap().
Referenced by BuildUpdate().
DoForAllVisibleWorldObjects()
template<typename Worker > void WorldObject::DoForAllVisibleWorldObjects (Worker && worker) inline
    {
        // Not a player, no access to this map
        VisibleWorldObjectsMap const* visibleWorldObjectsMap = GetObjectVisibilityContainer().GetVisibleWorldObjectsMap();
        if (!visibleWorldObjectsMap)
            return;
        for (auto const& kvPair : *visibleWorldObjectsMap)
            worker(kvPair.second);
    }
References GetObjectVisibilityContainer(), and ObjectVisibilityContainer::GetVisibleWorldObjectsMap().
Referenced by Player::SendQuestGiverStatusMultiple(), Player::SendTaxiNodeStatusMultiple(), Player::UpdateForQuestWorldObjects(), and Player::UpdateTriggerVisibility().
FindMap()
Map * WorldObject::FindMap () const inline
{ return m_currMap; }
References m_currMap.
Referenced by Player::_AddSpellCooldown(), Group::_cancelHomebindIfInstance(), Group::_homebindIfInstance(), Player::_SaveCharacter(), HomeMovementGenerator< Creature >::_setTargetLocation(), FormationMgr::AddCreatureToGroup(), AddObjectToRemoveList(), Pet::AddToWorld(), Vehicle::ApplyAllImmunities(), Spell::cancel(), CanSeeOrDetect(), Spell::CheckCast(), Group::CountTheRoll(), Spell::DoAllEffectOnTarget(), ScriptedAI::DoPlayMusic(), Spell::EffectPersistentAA(), AuraMunchingQueue::Execute(), EoEDrakeEnterVehicleEvent::Execute(), Spell::finish(), lfg::LFGMgr::FinishDungeon(), spell_dk_scourge_strike::HandleAfterHit(), WorldSession::HandleCastSpellOpcode(), WorldSession::HandleEnterPlayerVehicle(), WorldSession::HandlePlayerLoginOpcode(), spell_dk_blood_caked_blade::HandleProc(), ArenaSpectator::HandleResetCommand(), spell_temple_of_atal_hakkar_awaken_the_soulflayer::HandleSendEvent(), WorldSession::HandleSetDungeonDifficultyOpcode(), WorldSession::HandleSetRaidDifficultyOpcode(), misc_commandscript::HandleSkirmishCommand(), spectator_commandscript::HandleSpectatorLeaveCommand(), ArenaSpectator::HandleSpectatorSpectateCommand(), ArenaSpectator::HandleSpectatorWatchCommand(), Unit::HandleSpellClick(), IsInMap(), GameObject::IsInstanceGameobject(), boss_headless_horseman::JustDied(), Player::LoadFromDB(), Pet::LoadPetFromDB(), LogCommandUsage(), WorldSession::LogoutPlayer(), Map::MoveAllCreaturesInMoveList(), Map::MoveAllDynamicObjectsInMoveList(), Map::MoveAllGameObjectsInMoveList(), Player::NeedSendSpectatorData(), achievement_once_bitten_twice_shy::OnCheck(), Unit::PatchValuesUpdate(), spell_blood_queen_pact_of_the_darkfallen_dmg_aura::PeriodicTick(), SmartScript::ProcessAction(), FormationMgr::RemoveCreatureFromGroup(), Player::RemovePet(), Player::ResetInstances(), KillRewarder::Reward(), Spell::SendChannelStart(), Player::SendClearCooldown(), Spell::SendSpellStart(), setActive(), Player::setDeathState(), Unit::SetHealth(), Unit::SetMaxHealth(), Unit::SetMaxPower(), Player::SetMover(), Unit::SetPower(), Unit::setPowerType(), Player::SetSelection(), SetZoneScript(), SummonCreature(), Player::SummonPet(), OutdoorPvP::TeamCastSpell(), Player::Update(), and Unit::Update().
FindNearestCreature()
Creature * WorldObject::FindNearestCreature (uint32 entry, float range, bool alive = true) const
{
    Creature* creature = nullptr;
    Acore::NearestCreatureEntryWithLiveStateInObjectRangeCheck checker(*this, entry, alive, range);
    Acore::CreatureLastSearcher<Acore::NearestCreatureEntryWithLiveStateInObjectRangeCheck> searcher(this, creature, checker);
    Cell::VisitObjects(this, searcher, range);
    return creature;
}
References Cell::VisitObjects().
Referenced by npc_thrall_bfu::npc_thrall_bfuAI::ActivateValimathrasPortal(), npc_commander_dawnforge::npc_commander_dawnforgeAI::CanStartEvent(), boss_murmur::CastSuppressionOOC(), spell_renew_skirmisher::CheckRequirement(), spell_challenge_veraku::CheckRequirement(), spell_disrupt_summoning_ritual::CheckRequirement(), spell_item_demon_broiled_surprise::CheckRequirement(), spell_q12943_shadow_vault_decree::CheckRequirement(), spell_item_map_of_the_geyser_fields::CheckSinkholes(), npc_q24545_lich_king::npc_q24545_lich_kingAI::CleanAll(), boss_grand_champion::boss_grand_championAI::DamageTaken(), npc_gunship::npc_gunshipAI::DamageTaken(), npc_terenas_menethil::npc_terenas_menethilAI::DamageTaken(), boss_the_lich_king::boss_the_lich_kingAI::DamageTaken(), boss_jarien::DoAction(), boss_sothos::DoAction(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::DoAction(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::DoAction(), boss_krik_thir::boss_krik_thirAI::DoAction(), npc_blade_of_azzinoth::DoAction(), boss_kelidan_the_breaker::DoAction(), go_transport_the_iron_eagle::EventInform(), go_transport_the_thundercaller::EventInform(), go_transport_the_purple_princess::EventInform(), UtherBatteredHiltEvent::Execute(), DelayedCastMincharEvent::Execute(), spell_the_lich_king_restore_soul::FilterTargets(), npc_dark_iron_guzzler::FindNextKeg(), npc_dark_iron_attack_generator::FinishAttackDueToWin(), npc_dark_iron_attack_generator::FinishEventDueToLoss(), GetClosestCreatureWithEntry(), npc_shattered_hand_scout::GetPorung(), npc_dark_iron_attack_generator::GetRandomBartender(), npc_anachronos_the_ancient::npc_anachronos_the_ancientAI::HandleAnimation(), spell_igb_on_gunship_deck_aura::HandleApply(), HandleBothDead(), npc_echo_of_medivh::HandleCellInitialData(), npc_echo_of_medivh::HandleCheat(), spell_panther_cage_key::HandleDummy(), spell_q12589_shoot_rjr::HandleDummy(), spell_valanar_kinetic_bomb_aura::HandleDummyTick(), spell_q11719_bloodspore_ruination_45997::HandleEffect(), spell_midsummer_ribbon_pole::HandleEffectPeriodic(), spell_pursuing_spikes_aura::HandleEffectPeriodic(), spell_gen_haunted_aura::HandleOnEffectRemove(), aura_class_call_siphon_blessing::HandlePeriodic(), spell_brewfest_toss_mug::HandleScriptEffect(), spell_q12943_shadow_vault_decree::HandleScriptEffect(), spell_q12620_the_lifewarden_wrath::HandleSendEvent(), npc_hourglass_of_eternity::npc_hourglass_of_eternityAI::HideNozdormu(), instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::InstanceCleanup(), npc_flame_of_azzinoth::IsSummonedBy(), npc_vaelastrasz_the_red::npc_vaelastrasz_the_redAI::IsSummonedBy(), npc_oculus_drake::npc_oculus_drakeAI::IsSummonedBy(), npc_maiev_illidan::IsSummonedBy(), boss_rend_blackhand::boss_rend_blackhandAI::JustDied(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::JustDied(), npc_gunship::npc_gunshipAI::JustDied(), gunship_npc_AI::JustDied(), npc_q24545_vegard::npc_q24545_vegardAI::JustDied(), npc_enraged_spirit::npc_enraged_spiritAI::JustDied(), boss_jarien::JustDied(), boss_sothos::JustDied(), boss_cthun::JustDied(), boss_porung::JustDied(), npc_blackhand_incarcerator::npc_blackhand_incarceratorAI::JustEngagedWith(), boss_devourer_of_souls::boss_devourer_of_soulsAI::JustEngagedWith(), boss_eregos::boss_eregosAI::JustEngagedWith(), boss_razorscale::boss_razorscaleAI::JustEngagedWith(), boss_thorim_gauntlet_npcs::boss_thorim_gauntlet_npcsAI::JustEngagedWith(), npc_ulduar_storm_tempered_keeper::npc_ulduar_storm_tempered_keeperAI::JustEngagedWith(), boss_warlord_kalithresh::JustEngagedWith(), boss_thaddius_summon::boss_thaddius_summonAI::JustEngagedWith(), boss_festergut::boss_festergutAI::JustEngagedWith(), npc_sindragosa_trash::npc_sindragosa_trashAI::JustEngagedWith(), npc_kalecgos_kj::JustSummoned(), npc_overlord_drakuru_betrayal::JustSummoned(), npc_grand_magister_rommath::npc_grand_magister_rommathAI::MoveInLineOfSight(), npc_cw_area_trigger::npc_cw_area_triggerAI::MoveInLineOfSight(), npc_black_knight_graveyard::npc_black_knight_graveyardAI::MoveInLineOfSight(), npc_daranelle::npc_daranelleAI::MoveInLineOfSight(), npc_acherus_necromancer::npc_acherus_necromancerAI::MovementInform(), npc_gothik_the_harvester::npc_gothik_the_harvesterAI::MovementInform(), npc_sentinel_leader::MovementInform(), npc_sentinel_infiltrator::MovementInform(), boss_felmyst::MovementInform(), boss_ymiron::boss_ymironAI::MovementInform(), npc_janalai_hatcher::MovementInform(), npc_attracted_reef_bull::npc_attracted_reef_bullAI::MovementInform(), spell_q12987_read_pronouncement::OnApply(), go_ulduar_tower::OnDestroyed(), spell_bh_cleanse_quel_delar::OnEffect(), go_gong_of_bethekk::OnGossipHello(), go_resonite_cask::OnGossipHello(), go_duskwither_spire_power_source::OnGossipHello(), go_manticron_cube::OnGossipHello(), go_acherus_soul_prison::OnGossipHello(), go_ravager_cage::OnGossipHello(), go_bristlelimb_cage::OnGossipHello(), go_the_pearl_of_the_depths::OnGossipHello(), go_pressure_valve::OnGossipHello(), go_brazier::OnGossipHello(), go_finklestein_cauldron::OnGossipHello(), go_scourge_enclosure::OnGossipHello(), go_simon_cluster::OnGossipHello(), go_warmaul_prison::OnGossipHello(), go_scourge_cage::OnGossipHello(), go_arcane_prison::OnGossipHello(), go_jotunheim_cage::OnGossipHello(), go_dragonflayer_cage::OnGossipHello(), go_hive_pod::OnGossipHello(), npc_mcmanus::OnGossipSelect(), go_pumpkin_shrine::OnGossipSelect(), npc_mikhail::OnQuestAccept(), npc_tyrion::OnQuestAccept(), go_crystal_prison::OnQuestAccept(), go_crystalline_tear::OnQuestAccept(), go_loosely_turned_soil::OnQuestReward(), spell_item_instant_statue::OnRemove(), at_cthun_stomach_exit::OnTrigger(), at_q24545_frostmourne_cavern::OnTrigger(), AreaTrigger_at_scent_larkorwi::OnTrigger(), AreaTrigger_at_nats_landing::OnTrigger(), AreaTrigger_at_sentry_point::OnTrigger(), AreaTrigger_at_brewfest::OnTrigger(), at_blackrock_stadium::OnTrigger(), near_scarshield_infiltrator::OnTrigger(), at_scarshield_infiltrator::OnTrigger(), at_malfurion_stormrage::OnTrigger(), at_commander_dawnforge::OnTrigger(), item_incendiary_explosives::OnUse(), item_captured_frog::OnUse(), npc_akama_illidan::PathEndReached(), spell_quest_test_flight_charging::PerformKick(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::ProcessEvent(), npc_blackhand_incarcerator::npc_blackhand_incarceratorAI::Reset(), boss_rend_blackhand::boss_rend_blackhandAI::Reset(), boss_victor_nefarius::boss_victor_nefariusAI::Reset(), boss_nefarian::Reset(), boss_jarien::Reset(), boss_sothos::Reset(), npc_bh_thalorien_dawnseeker::npc_bh_thalorien_dawnseekerAI::Reset(), boss_eye_of_cthun::Reset(), boss_festergut::boss_festergutAI::Reset(), boss_thaddius_summon::boss_thaddius_summonAI::Reset(), npc_freya_ward::npc_freya_wardAI::Reset(), boss_thorim_start_npcs::boss_thorim_start_npcsAI::Reset(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::Reset(), npc_cosmetic_toy_plane::Reset(), npc_rodin_lightning_enabler::Reset(), boss_yoggsaron_lich_king::boss_yoggsaron_lich_kingAI::Say(), boss_yoggsaron_llane::boss_yoggsaron_llaneAI::Say(), boss_yoggsaron_neltharion::boss_yoggsaron_neltharionAI::Say(), boss_razuvious_minion::boss_razuvious_minionAI::ScheduleAttackDummy(), boss_rend_blackhand::boss_rend_blackhandAI::SetData(), npc_highlord_tirion_fordring_lh::npc_highlord_tirion_fordringAI::SetData(), npc_q24545_lich_king::npc_q24545_lich_kingAI::SetData(), npc_shandy_dalaran::npc_shandy_dalaranAI::SetData(), npc_tharnarian::npc_tharnarianAI::SetGUID(), npc_hourglass_of_eternity::npc_hourglass_of_eternityAI::ShowNozdormu(), npc_midsummer_ribbon_pole_target::SpawnFireSpiralBunny(), npc_shadowmoon_tuber_node::npc_shadowmoon_tuber_nodeAI::SpellHit(), boss_thorim_pillar::boss_thorim_pillarAI::SpellHit(), npc_living_constellation::npc_living_constellationAI::SpellHit(), npc_enslaved_netherwing_drake::SpellHit(), npc_ulduar_flames_initial::npc_ulduar_flames_initialAI::SpreadFlame(), npc_commander_eligor_dawnbringer::npc_commander_eligor_dawnbringerAI::StoreTargets(), spell_midsummer_fling_torch::ThrowNextTorch(), instance_stratholme::instance_stratholme_InstanceMapScript::Update(), instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::Update(), go_bear_trap::go_bear_trapAI::UpdateAI(), SmartAI::UpdateAI(), npc_blackhand_incarcerator::npc_blackhand_incarceratorAI::UpdateAI(), npc_vaelastrasz_the_red::npc_vaelastrasz_the_redAI::UpdateAI(), boss_victor_nefarius::boss_victor_nefariusAI::UpdateAI(), npc_unworthy_initiate::npc_unworthy_initiateAI::UpdateAI(), npc_acherus_necromancer::npc_acherus_necromancerAI::UpdateAI(), npc_gothik_the_harvester::npc_gothik_the_harvesterAI::UpdateAI(), npc_balance_of_light_and_shadow::npc_balance_of_light_and_shadowAI::UpdateAI(), npc_cameron::UpdateAI(), npc_eastvale_peasent::UpdateAI(), npc_sentinel_leader::UpdateAI(), npc_sentinel_infiltrator::UpdateAI(), npc_grand_magister_rommath::npc_grand_magister_rommathAI::UpdateAI(), npc_lady_sylvanas_windrunner::npc_lady_sylvanas_windrunnerAI::UpdateAI(), npc_thrall_bfu::npc_thrall_bfuAI::UpdateAI(), npc_alexstraza_the_lifebinder::UpdateAI(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::UpdateAI(), npc_medivh_bm::UpdateAI(), npc_murkdeep::npc_murkdeepAI::UpdateAI(), npc_giant_spotlight::npc_giant_spotlightAI::UpdateAI(), npc_qiraj_war_spawn::npc_qiraj_war_spawnAI::UpdateAI(), boss_elder_nadox::UpdateAI(), boss_grand_champion::boss_grand_championAI::UpdateAI(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::UpdateAI(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::UpdateAI(), boss_professor_putricide::boss_professor_putricideAI::UpdateAI(), boss_the_lich_king::boss_the_lich_kingAI::UpdateAI(), npc_tirion_fordring_tft::npc_tirion_fordringAI::UpdateAI(), npc_terenas_menethil::npc_terenas_menethilAI::UpdateAI(), npc_frostwing_vrykul::npc_frostwing_vrykulAI::UpdateAI(), boss_thaddius_summon::boss_thaddius_summonAI::UpdateAI(), boss_malygos::boss_malygosAI::UpdateAI(), boss_varos::boss_varosAI::UpdateAI(), boss_flame_leviathan::boss_flame_leviathanAI::UpdateAI(), npc_freya_ward::npc_freya_wardAI::UpdateAI(), npc_ulduar_iron_construct::npc_ulduar_iron_constructAI::UpdateAI(), boss_kologarn::boss_kologarnAI::UpdateAI(), npc_ulduar_emergency_fire_bot::npc_ulduar_emergency_fire_botAI::UpdateAI(), npc_ulduar_storm_tempered_keeper::npc_ulduar_storm_tempered_keeperAI::UpdateAI(), npc_sinkhole_kill_credit::npc_sinkhole_kill_creditAI::UpdateAI(), npc_thassarian::npc_thassarianAI::UpdateAI(), npc_thassarian2::npc_thassarian2AI::UpdateAI(), npc_hourglass_of_eternity::npc_hourglass_of_eternityAI::UpdateAI(), npc_q24545_lich_king::npc_q24545_lich_kingAI::UpdateAI(), npc_lord_arete::npc_lord_areteAI::UpdateAI(), go_wg_vehicle_teleporter::go_wg_vehicle_teleporterAI::UpdateAI(), npc_drakuru_shackles::npc_drakuru_shacklesAI::UpdateAI(), npc_fel_guard_hound::npc_fel_guard_houndAI::UpdateAI(), npc_captain_saeed::npc_captain_saeedAI::UpdateAI(), npc_spring_rabbit::npc_spring_rabbitAI::UpdateAI(), npc_lord_gregor_lescovar::npc_lord_gregor_lescovarAI::UpdateAI(), npc_tyrion_spybot::npc_tyrion_spybotAI::UpdateAI(), npc_magwin::npc_magwinAI::UpdateEscortAI(), npc_tirions_gambit_tirion::npc_tirions_gambit_tirionAI::UpdateEscortAI(), npc_ranger_lilatha::WaypointReached(), npc_deathstalker_erland::npc_deathstalker_erlandAI::WaypointReached(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::WaypointReached(), npc_magwin::npc_magwinAI::WaypointReached(), npc_apothecary_hanes::npc_Apothecary_HanesAI::WaypointReached(), npc_ancestral_wolf::npc_ancestral_wolfAI::WaypointReached(), and npc_bessy::npc_bessyAI::WaypointReached().
FindNearestGameObject()
GameObject * WorldObject::FindNearestGameObject (uint32 entry, float range, bool onlySpawned = false) const
{
    GameObject* go = nullptr;
    Acore::NearestGameObjectEntryInObjectRangeCheck checker(*this, entry, range, onlySpawned);
    Acore::GameObjectLastSearcher<Acore::NearestGameObjectEntryInObjectRangeCheck> searcher(this, go, checker);
    Cell::VisitObjects(this, searcher, range);
    return go;
}
References Cell::VisitObjects().
Referenced by spell_q12237_rescue_villager::CheckCast(), spell_q9452_cast_net::CheckCast(), npc_q24545_lich_king::npc_q24545_lich_kingAI::CleanAll(), boss_mimiron::boss_mimironAI::CloseDoorAndButton(), boss_hodir::boss_hodirAI::DamageTaken(), npc_ulduar_toasty_fire::npc_ulduar_toasty_fireAI::DoAction(), npc_thrall_warchief::npc_thrall_warchiefAI::DoAction(), npc_overlord_drakuru_betrayal::DoAction(), boss_yoggsaron_brain::boss_yoggsaron_brainAI::DoAction(), Spell::EffectScriptEffect(), boss_ouro::EnterEvadeMode(), npc_dirt_mound::EnterEvadeMode(), GetClosestGameObjectWithEntry(), spell_halion_twilight_division::HandleDummy(), npc_midsummer_bonfire::Ignite(), boss_vezax::boss_vezaxAI::JustDied(), boss_kologarn::boss_kologarnAI::JustDied(), boss_fathomlord_karathress::JustDied(), boss_hodir::boss_hodirAI::JustEngagedWith(), npc_midsummer_ribbon_pole_target::LocateRibbonPole(), npc_andorhal_tower::npc_andorhal_towerAI::MoveInLineOfSight(), npc_ulduar_snow_mound::MoveInLineOfSight(), npc_overlord_drakuru_betrayal::MoveInLineOfSight(), npc_pos_leader_second::npc_pos_leader_secondAI::MovementInform(), npc_dragonmaw_peon::npc_dragonmaw_peonAI::MovementInform(), go_thorim_lever::OnGossipHello(), npc_lurgglbr::OnQuestAccept(), npc_simon_bunny::npc_simon_bunnyAI::PrepareClusters(), instance_stratholme::instance_stratholme_InstanceMapScript::ProcessSlaughterEvent(), npc_ranger_lilatha::Reset(), npc_stillpine_capitive::npc_stillpine_capitiveAI::Reset(), boss_thaddius::boss_thaddiusAI::Reset(), boss_hodir::boss_hodirAI::Reset(), npc_wounded_blood_elf::npc_wounded_blood_elfAI::Reset(), boss_mimiron::boss_mimironAI::ResetGameObjects(), npc_simon_bunny::npc_simon_bunnyAI::ResetNode(), npc_shadowmoon_tuber_node::npc_shadowmoon_tuber_nodeAI::SetData(), npc_ulduar_harpoonfirestate::npc_ulduar_harpoonfirestateAI::SetData(), boss_rend_blackhand::boss_rend_blackhandAI::SetData(), npc_q24545_lich_king::npc_q24545_lich_kingAI::SetData(), npc_simon_bunny::npc_simon_bunnyAI::SetUpPreGame(), npc_crate_helper::npc_crate_helperAI::SpellHit(), npc_rabid_thistle_bear::npc_rabid_thistle_bearAI::SpellHit(), npc_rinji::npc_rinjiAI::sQuestAccept(), npc_simon_bunny::npc_simon_bunnyAI::StartGame(), boss_ouro::Submerge(), npc_grimstone::npc_grimstoneAI::SummonBoss(), boss_ambassador_flamelash::boss_ambassador_flamelashAI::TurnRunes(), boss_gyth::boss_gythAI::UpdateAI(), boss_victor_nefarius::boss_victor_nefariusAI::UpdateAI(), npc_unworthy_initiate::npc_unworthy_initiateAI::UpdateAI(), npc_scarlet_courier::npc_scarlet_courierAI::UpdateAI(), npc_partygoer::UpdateAI(), npc_grand_magister_rommath::npc_grand_magister_rommathAI::UpdateAI(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::UpdateAI(), npc_giant_spotlight::npc_giant_spotlightAI::UpdateAI(), boss_thaddius::boss_thaddiusAI::UpdateAI(), boss_mimiron::boss_mimironAI::UpdateAI(), npc_ulduar_aerial_command_unit::npc_ulduar_aerial_command_unitAI::UpdateAI(), npc_sinkhole_kill_credit::npc_sinkhole_kill_creditAI::UpdateAI(), npc_valiance_keep_cannoneer::npc_valiance_keep_cannoneerAI::UpdateAI(), npc_q24545_lich_king::npc_q24545_lich_kingAI::UpdateAI(), npc_mature_netherwing_drake::npc_mature_netherwing_drakeAI::UpdateAI(), npc_dragonmaw_peon::npc_dragonmaw_peonAI::UpdateAI(), npc_pet_gen_plump_turkey::UpdateAI(), npc_tirions_gambit_tirion::npc_tirions_gambit_tirionAI::UpdateEscortAI(), npc_ranger_lilatha::WaypointReached(), npc_wounded_blood_elf::npc_wounded_blood_elfAI::WaypointReached(), and npc_isla_starmane::npc_isla_starmaneAI::WaypointReached().
FindNearestGameObjectOfType()
GameObject * WorldObject::FindNearestGameObjectOfType (GameobjectTypes type, float range) const
{
    GameObject* go = nullptr;
    Acore::NearestGameObjectTypeInObjectRangeCheck checker(*this, type, range);
    Acore::GameObjectLastSearcher<Acore::NearestGameObjectTypeInObjectRangeCheck> searcher(this, go, checker);
    Cell::VisitObjects(this, searcher, range);
    return go;
}
References Cell::VisitObjects().
Referenced by Map::GetTransportForPos(), WorldSession::HandleAlterAppearance(), and misc_commandscript::HandleOpenDoorCommand().
GetAllowedLooters()
GuidUnorderedSet const & WorldObject::GetAllowedLooters () const
{
    return _allowedLooters;
}
References _allowedLooters.
Referenced by GameObject::SetLootRecipient().
GetAreaId()
uint32 WorldObject::GetAreaId () const
{
    if (_updatePositionData)
        const_cast<WorldObject*>(this)->UpdatePositionData();
    return _areaId;
}
References _areaId, _updatePositionData, and UpdatePositionData().
Referenced by Player::AddQuest(), Player::CheckAreaExploreAndOutdoor(), Spell::CheckCast(), Player::CompleteQuest(), ScriptedAI::DoPlayMusic(), Spell::EffectBind(), Spell::EffectDuel(), npc_costumed_orphan_matron::GetInitXYZ(), go_bells::go_bellsAI::go_bellsAI(), spell_item_socrethars_stone::HandleDummy(), WorldSession::HandleHearthAndResurrect(), OutdoorPvPNA::HandleKill(), misc_commandscript::HandlePInfoCommand(), WorldSession::HandlePlayerLoginFromDB(), spell_gen_teleporting::HandleScript(), spell_q12735_song_of_cleansing::HandleScript(), Player::IncompleteQuest(), DisableMgr::IsDisabledFor(), SpellArea::IsFitToRequirements(), npc_gilthares::npc_giltharesAI::JustEngagedWith(), LogCommandUsage(), npc_the_scourge_cauldron::npc_the_scourge_cauldronAI::MoveInLineOfSight(), npc_mageguard_dalaran::npc_mageguard_dalaranAI::MoveInLineOfSight(), npc_guardian_pavilion::npc_guardian_pavilionAI::MoveInLineOfSight(), achievement_tilted::OnCheck(), BattlefieldWG::OnCreatureCreate(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnPlayerAreaUpdate(), instance_hyjal::instance_mount_hyjal_InstanceMapScript::OnPlayerInWaterStateUpdate(), instance_ulduar::instance_ulduar_InstanceMapScript::OnUnitDeath(), item_petrov_cluster_bombs::OnUse(), item_only_for_flight::OnUse(), FlameLeviathanPursuedTargetSelector::operator()(), SmartScript::ProcessAction(), Player::RemoveActiveQuest(), Player::RepopAtGraveyard(), Player::RewardHonor(), Player::RewardQuest(), CreatureTextMgr::SendChatPacket(), BattlefieldWG::SendInitWorldStatesTo(), CreatureTextMgr::SendNonChatPacket(), Creature::SendZoneUnderAttackMessage(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::SetData(), npc_counselor_talbot::npc_counselor_talbotAI::UpdateAI(), npc_freed_protodrake::npc_freed_protodrakeAI::UpdateAI(), go_brewfest_music::go_brewfest_musicAI::UpdateAI(), and lfg::LFGMgr::UpdateRaidBrowser().
GetChargeContactPoint()
void WorldObject::GetChargeContactPoint (WorldObject const * obj, float & x, float & y, float & z, float distance2d = CONTACT_DISTANCE) const
{
    // angle to face `obj` to `this` using distance includes size of `obj`
    GetNearPoint(obj, x, y, z, obj->GetObjectSize(), distance2d, GetAngle(obj));
    if (std::fabs(this->GetPositionZ() - z) > 3.0f || !IsWithinLOS(x, y, z))
    {
        x = this->GetPositionX();
        y = this->GetPositionY();
        z = this->GetPositionZ();
        obj->UpdateGroundPositionZ(x, y, z);
    }
}
References Position::GetAngle(), GetNearPoint(), GetObjectSize(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), IsWithinLOS(), and UpdateGroundPositionZ().
GetClosePoint()
bool WorldObject::GetClosePoint (float & x, float & y, float & z, float size, float distance2d = 0, float angle = 0, WorldObject const * forWho = nullptr, bool force = false) const
{
    // angle calculated from current orientation
    GetNearPoint(forWho, x, y, z, size, distance2d, GetOrientation() + angle);
    if (std::fabs(this->GetPositionZ() - z) > 3.0f || !IsWithinLOS(x, y, z))
    {
        x = this->GetPositionX();
        y = this->GetPositionY();
        z = this->GetPositionZ();
        if (forWho)
            if (Unit const* u = forWho->ToUnit())
                u->UpdateAllowedPositionZ(x, y, z);
    }
    float maxDist = GetObjectSize() + size + distance2d + 1.0f;
    if (GetExactDistSq(x, y, z) >= maxDist * maxDist)
    {
        if (force)
        {
            x = this->GetPositionX();
            y = this->GetPositionY();
            z = this->GetPositionZ();
            return true;
        }
        return false;
    }
    return true;
}
References Position::GetExactDistSq(), GetNearPoint(), GetObjectSize(), Position::GetOrientation(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), IsWithinLOS(), and Object::ToUnit().
Referenced by Spell::EffectResurrectPet(), Spell::EffectSummonObject(), Spell::EffectSummonObjectWild(), Spell::EffectSummonPet(), Spell::EffectTransmitted(), cast_commandscript::HandleCastDistCommand(), debug_commandscript::HandleDebugSpawnVehicleCommand(), misc_commandscript::HandleGroupSummonCommand(), spell_item_draenic_pale_ale::HandleSummon(), misc_commandscript::HandleSummonCommand(), Pet::LoadPetFromDB(), MotionMaster::MoveJumpTo(), SmartScript::ProcessAction(), npc_released_offspring_harkoa::npc_released_offspring_harkoaAI::Reset(), npc_dragonmaw_peon::npc_dragonmaw_peonAI::SpellHit(), SummonCreature(), npc_acherus_necromancer::npc_acherus_necromancerAI::UpdateAI(), npc_gothik_the_harvester::npc_gothik_the_harvesterAI::UpdateAI(), npc_valkyr_battle_maiden::npc_valkyr_battle_maidenAI::UpdateAI(), and npc_toc_dk::npc_toc_dkAI::UpdateAI().
GetCollisionHeight()
virtual float WorldObject::GetCollisionHeight () const inline virtual
Reimplemented in Unit.
{ return 0.0f; }
Referenced by PathGenerator::BuildPolyPath(), Map::CanReachPositionAndGetValidCoords(), Map::CheckCollisionAndGetValidCoords(), GetFloorZ(), GetHitSpherePointFor(), GetMapHeight(), GetMapWaterOrGroundLevel(), GetMinHeightInWater(), PathGenerator::GetNavTerrain(), GetNearPoint(), Map::HasEnoughWater(), PathGenerator::IsSwimmableSegment(), PathGenerator::IsWalkableClimb(), IsWithinLOS(), IsWithinLOSInMap(), PathGenerator::ShortenPathUntilDist(), and UpdatePositionData().
GetCollisionRadius()
virtual float WorldObject::GetCollisionRadius () const inline virtual
Reimplemented in Unit.
{ return GetObjectSize() / 2; }
References GetObjectSize().
GetCollisionWidth()
virtual float WorldObject::GetCollisionWidth () const inline virtual
Reimplemented in Unit.
{ return GetObjectSize(); }
References GetObjectSize().
Referenced by GetMinHeightInWater().
GetCombatReach()
virtual float WorldObject::GetCombatReach () const inline virtual
Reimplemented in Unit.
{ return 0.0f; } // overridden (only) in Unit
Referenced by GetHitSpherePointFor(), GetNearPoint2D(), Acore::WorldObjectSpellTrajTargetCheck::operator()(), SmartScript::ProcessAction(), and Cell::Visit().
GetContactPoint()
void WorldObject::GetContactPoint (WorldObject const * obj, float & x, float & y, float & z, float distance2d = CONTACT_DISTANCE) const
{
    // angle to face `obj` to `this` using distance includes size of `obj`
    GetNearPoint(obj, x, y, z, obj->GetObjectSize(), distance2d, GetAngle(obj));
    // Exclude gameobjects from LoS calculations
    if (std::fabs(this->GetPositionZ() - z) > 3.0f || (!IsGameObject() && !IsWithinLOS(x, y, z)))
    {
        x = this->GetPositionX();
        y = this->GetPositionY();
        z = this->GetPositionZ();
        obj->UpdateAllowedPositionZ(x, y, z);
    }
}
References Position::GetAngle(), GetNearPoint(), GetObjectSize(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Object::IsGameObject(), IsWithinLOS(), and UpdateAllowedPositionZ().
Referenced by npc_unworthy_initiate::npc_unworthy_initiateAI::EventStart(), and Unit::JumpTo().
GetCreatureListWithEntryInGrid() [1/2]
void WorldObject::GetCreatureListWithEntryInGrid (std::list< Creature * > & creatureList, std::vector< uint32 > const & entries, float maxSearchRange) const
{
    Acore::AllCreaturesMatchingOneEntryInRange check(this, entries, maxSearchRange);
    Acore::CreatureListSearcher searcher(this, creatureList, check);
    Cell::VisitObjects(this, searcher, maxSearchRange);
}
References Cell::VisitObjects().
GetCreatureListWithEntryInGrid() [2/2]
void WorldObject::GetCreatureListWithEntryInGrid (std::list< Creature * > & lList, uint32 uiEntry, float fMaxSearchRange) const
{
    Acore::AllCreaturesOfEntryInRange check(this, entry, maxSearchRange);
    Acore::CreatureListSearcher<Acore::AllCreaturesOfEntryInRange> searcher(this, creatureList, check);
    Cell::VisitObjects(this, searcher, maxSearchRange);
}
References Cell::VisitObjects().
Referenced by at_hol_hall_of_watchers::_OnTrigger(), npc_anubisath_sentinel::aqsentinelAI::AddSentinelsNear(), npc_minion_spawner::CanSpawnRareMinion(), spell_q12237_rescue_villager::CheckCast(), npc_akama_shade::DamageTaken(), npc_necrotic_shard::DespawnCultists(), npc_necrotic_shard::DespawnEventDoodads(), npc_necrotic_shard::DespawnShadowsOfDoom(), boss_apothecary_hummel::boss_apothecary_hummelAI::DoAction(), npc_overlord_drakuru_betrayal::DoAction(), npc_lord_gregor_lescovar::npc_lord_gregor_lescovarAI::DoGuardsDisappearAndDie(), spell_the_lich_king_restore_soul::FilterTargets(), boss_the_beast::boss_thebeastAI::FindNearbyOrcs(), GetCreatureListWithEntryInGrid(), spell_apothecary_lingering_fumes::HandleAfterCast(), npc_anachronos_the_ancient::npc_anachronos_the_ancientAI::HandleAnimation(), spell_q12243_fire_upon_the_waters_aura::HandleApplyEffect(), BattlegroundIC::HandleCapturedNodes(), BattlegroundIC::HandleContestedNodes(), spell_dred_raptor_call::HandleDummy(), spell_warhead_detonate::HandleDummy(), spell_icc_sprit_alarm::HandleEvent(), spell_kiljaeden_armageddon_periodic_aura::HandlePeriodic(), spell_q12243_fire_upon_the_waters_aura::HandleRemoveEffect(), spell_q12620_the_lifewarden_wrath::HandleSendEvent(), npc_necrotic_shard::HasMinion(), boss_twilight_corrupter::InitializeAI(), boss_rajaxx::JustDied(), npc_lava_spawn::JustEngagedWith(), boss_elder_nadox::JustEngagedWith(), npc_hadronox_crusherPackAI::JustEngagedWith(), npc_akama_shade::MovementInform(), SmartScript::ProcessEvent(), boss_jaraxxus::boss_jaraxxusAI::Reset(), npc_necrotic_shard::ScheduleTasks(), npc_gothik_trigger::npc_gothik_triggerAI::SelectRandomSkullPile(), npc_harrison_jones::SpellHit(), boss_shade_of_akama::SpellHit(), go_firework_show::StopShow(), boss_ouro::Submerge(), npc_thrall_bfu::npc_thrall_bfuAI::SummonedCreatureDies(), npc_varian_wrynn::npc_varian_wrynnAI::UpdateAI(), npc_thrall_bfu::npc_thrall_bfuAI::UpdateAI(), npc_overlord_drakuru_betrayal::UpdateAI(), outdoorpvp_na_halaa_creatures::UpdateAI(), and npc_necrotic_shard::UpdateFindersAmount().
GetCreaturesWithEntryInRange()
void WorldObject::GetCreaturesWithEntryInRange (std::list< Creature * > & creatureList, float radius, uint32 entry)
{
    Acore::AllCreaturesOfEntryInRange check(this, entry, radius);
    Acore::CreatureListSearcher<Acore::AllCreaturesOfEntryInRange> searcher(this, creatureList, check);
    Cell::VisitObjects(this, searcher, radius);
}
References Cell::VisitObjects().
Referenced by boss_kelthuzad_minion::boss_kelthuzad_minionAI::AttackStart(), npc_midsummer_ribbon_pole_target::DoDancingFLameChecks(), npc_midsummer_ribbon_pole_target::DoGroundFlowerChecks(), FixOrientation::Execute(), boss_alyson_antille::GetNearbyFriendlies(), spell_black_template_harpooners_mark_aura::HandleEffectApply(), spell_botanica_call_of_the_falcon_aura::HandleEffectApply(), spell_mc_play_dead_aura::HandleEffectRemove(), spell_winter_veil_racer_rocket_slam::HandleTriggerSpell(), boss_janalai::HatchAllEggs(), boss_headless_horseman::JustDied(), boss_ignis::boss_ignisAI::JustDied(), boss_malchezaar::JustEngagedWith(), boss_ignis::boss_ignisAI::JustEngagedWith(), boss_razorscale::boss_razorscaleAI::JustEngagedWith(), boss_buru::ManipulateEggs(), boss_nalorakk::MoveInLineOfSight(), go_beacon::go_beaconAI::OnStateChanged(), spell_dreamwalker_summon_suppresser_aura::PeriodicTick(), spell_midsummer_ribbon_pole_visual::PrepareSpellScript(), boss_grobbulus::boss_grobbulusAI::PullChamberAdds(), npc_hallows_end_soh::Reset(), boss_watchkeeper_gargolmar::Reset(), npc_captain_saeed::npc_captain_saeedAI::SetGUID(), boss_hodir::boss_hodirAI::SpellHitTarget(), npc_icc_putricades_trap::npc_icc_putricades_trapAI::UpdateAI(), boss_sjonnir_malformed_ooze::boss_sjonnir_malformed_oozeAI::UpdateAI(), npc_ulduar_hodir_mage::npc_ulduar_hodir_mageAI::UpdateAI(), boss_ignis::boss_ignisAI::UpdateAI(), npc_ulduar_aerial_command_unit::npc_ulduar_aerial_command_unitAI::UpdateAI(), boss_svala::boss_svalaAI::UpdateAI(), and npc_tirions_gambit_tirion::npc_tirions_gambit_tirionAI::UpdateEscortAI().
GetDeadCreatureListInGrid()
void WorldObject::GetDeadCreatureListInGrid (std::list< Creature * > & lList, float maxSearchRange, bool alive = false) const
{
    Acore::AllDeadCreaturesInRange check(this, maxSearchRange, alive);
    Acore::CreatureListSearcher<Acore::AllDeadCreaturesInRange> searcher(this, creaturedeadList, check);
    Cell::VisitObjects(this, searcher, maxSearchRange);
}
References Cell::VisitObjects().
Referenced by GetDeadCreatureListInGrid().
GetDebugInfo()
std::string WorldObject::GetDebugInfo () const override virtual
Reimplemented from Object.
{
    std::stringstream sstr;
    sstr << WorldLocation::GetDebugInfo() << "\n"
        << Object::GetDebugInfo() << "\n"
        << "Name: " << GetName();
    return sstr.str();
}
References Object::GetDebugInfo(), WorldLocation::GetDebugInfo(), and GetName().
Referenced by Aura::GetDebugInfo(), GameObject::GetDebugInfo(), and Unit::GetDebugInfo().
GetDistance() [1/3]
float WorldObject::GetDistance (const Position & pos) const
{
    float d = GetExactDist(&pos) - GetObjectSize();
    return d > 0.0f ? d : 0.0f;
}
References Position::GetExactDist(), and GetObjectSize().
GetDistance() [2/3]
float WorldObject::GetDistance (float x, float y, float z) const
{
    float d = GetExactDist(x, y, z) - GetObjectSize();
    return d > 0.0f ? d : 0.0f;
}
References Position::GetExactDist(), and GetObjectSize().
GetDistance() [3/3]
float WorldObject::GetDistance (WorldObject const * obj) const
{
    float d = GetExactDist(obj) - GetObjectSize() - obj->GetObjectSize();
    return d > 0.0f ? d : 0.0f;
}
References Position::GetExactDist(), and GetObjectSize().
Referenced by Spell::AddGOTarget(), Spell::AddUnitTarget(), boss_urom::boss_uromAI::AttackStart(), boss_attumen::CanMeleeHit(), boss_midnight::CanMeleeHit(), Spell::CheckCast(), boss_priestess_delrissa::CheckInRoom(), boss_kalecgos::CheckInRoom(), boss_isle_of_conquest::boss_isle_of_conquestAI::CheckRageBuff(), Spell::EffectChargeDest(), Spell::EffectPullTowards(), boss_sapphiron::boss_sapphironAI::EnterCombatSelfFunction(), boss_magmadar::boss_magmadarAI::ExecuteEvent(), boss_nightbane::FlyToClosestPreFlyWayPoint(), Unit::GetMagicHitRedirectTarget(), boss_urom::boss_uromAI::GetPhaseByCurrentPosition(), FleeingMovementGenerator< T >::GetPoint(), OutdoorPvPSI::HandleDropFlag(), Unit::HandleDummyAuraProc(), spell_image_of_drakuru_reagent_check::HandleDummyEffect(), spell_herald_volzaj_insanity::HandleDummyEffect(), spell_egg_explosion::HandleDummyHitTarget(), misc_commandscript::HandleGetDistanceCommand(), spell_yogg_saron_brain_link_aura::HandleOnEffectApply(), spell_garr_separation_anxiety_aura::HandlePeriodic(), spell_majordomo_separation_anxiety_aura::HandlePeriodic(), spell_entropius_black_hole_effect::HandlePull(), spell_boss_magus_telestra_gravity_well::HandlePull(), spell_gen_ds_flush_knockback::HandleScript(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::InformCloud(), Player::IsAtGroupRewardDistance(), Player::IsAtRecruitAFriendDistance(), SmartAI::IsEscortInvokerInRange(), Player::IsInAreaTriggerRadius(), boss_sartharion::boss_sartharionAI::IsTargetInBounds(), boss_shirrak_the_dead_watcher::JustEngagedWith(), boss_hadronox::JustSummoned(), npc_lady_sylvanas_windrunner::npc_lady_sylvanas_windrunnerAI::JustSummoned(), Condition::Meets(), npc_brewfest_keg_thrower::MoveInLineOfSight(), npc_brewfest_keg_reciver::MoveInLineOfSight(), npc_brewfest_bark_trigger::MoveInLineOfSight(), npc_love_in_air_supply_sentry::MoveInLineOfSight(), npc_love_in_air_snivel::MoveInLineOfSight(), boss_kelthuzad::boss_kelthuzadAI::MoveInLineOfSight(), npc_black_knight_graveyard::npc_black_knight_graveyardAI::MoveInLineOfSight(), npc_captain_saeed::npc_captain_saeedAI::MoveInLineOfSight(), boss_felmyst::MovementInform(), spell_yogg_saron_brain_link_aura::OnPeriodic(), Acore::NearestAssistCreatureInCreatureRangeCheck::operator()(), Acore::NearestCreatureEntryWithLiveStateInObjectRangeCheck::operator()(), Acore::NearestGameObjectFishingHole::operator()(), Acore::NearestGameObjectCheck::operator()(), Acore::NearestGameObjectEntryInObjectRangeCheck::operator()(), Acore::NearestGameObjectTypeInObjectRangeCheck::operator()(), Acore::NearestPlayerInObjectRangeCheck::operator()(), Acore::NearestAttackableUnitInObjectRangeCheck::operator()(), Acore::NearestHostileUnitCheck::operator()(), Acore::NearestHostileUnitInAttackDistanceCheck::operator()(), ManaVoidSelector::operator()(), LeechingThrowSelector::operator()(), Acore::WorldObjectSpellNearbyTargetCheck::operator()(), npc_vortex_ride::npc_vortex_rideAI::PassengerBoarded(), spell_quest_test_flight_charging::PerformKick(), SmartScript::ProcessAction(), Creature::reachWithSpellAttack(), Creature::reachWithSpellCure(), Map::ScriptsProcess(), boss_yoggsaron_constrictor_tentacle::boss_yoggsaron_constrictor_tentacleAI::SelectConstrictTarget(), boss_yoggsaron_corruptor_tentacle::boss_yoggsaron_corruptor_tentacleAI::SelectCorruptionTarget(), npc_enslaved_proto_drake::SetData(), Pet::Update(), boss_broodlord::boss_broodlordAI::UpdateAI(), npc_core_rager::npc_core_ragerAI::UpdateAI(), npc_kernobee::npc_kernobeeAI::UpdateAI(), npc_acherus_necromancer::npc_acherus_necromancerAI::UpdateAI(), npc_gothik_the_harvester::npc_gothik_the_harvesterAI::UpdateAI(), npc_lady_sylvanas_windrunner::npc_lady_sylvanas_windrunnerAI::UpdateAI(), npc_highborne_lamenter::npc_highborne_lamenterAI::UpdateAI(), npc_black_knight_ghoul::npc_black_knight_ghoulAI::UpdateAI(), npc_dark_nucleus::npc_dark_nucleusAI::UpdateAI(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::UpdateAI(), npc_frostwing_vrykul::npc_frostwing_vrykulAI::UpdateAI(), npc_icc_vengeful_fleshreaper::npc_icc_vengeful_fleshreaperAI::UpdateAI(), npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI::UpdateAI(), npc_icc_putricades_trap::npc_icc_putricades_trapAI::UpdateAI(), boss_volkhan::UpdateAI(), boss_stormcaller_brundir::boss_stormcaller_brundirAI::UpdateAI(), npc_auriaya_sanctum_sentry::npc_auriaya_sanctum_sentryAI::UpdateAI(), boss_freya::boss_freyaAI::UpdateAI(), boss_vezax::boss_vezaxAI::UpdateAI(), npc_ulduar_aerial_command_unit::npc_ulduar_aerial_command_unitAI::UpdateAI(), boss_thorim_start_npcs::boss_thorim_start_npcsAI::UpdateAI(), npc_ulduar_arachnopod_destroyer::npc_ulduar_arachnopod_destroyerAI::UpdateAI(), boss_xevozz::boss_xevozzAI::UpdateAI(), npc_battle_at_valhalas::npc_battle_at_valhalasAI::UpdateAI(), npc_pet_gen_target_following_bomb::UpdateAI(), and Player::UpdateCharmedAI().
GetDistance2d() [1/2]
float WorldObject::GetDistance2d (float x, float y) const
{
    float d = GetExactDist2d(x, y) - GetObjectSize();
    return d > 0.0f ? d : 0.0f;
}
References Position::GetExactDist2d(), and GetObjectSize().
GetDistance2d() [2/2]
float WorldObject::GetDistance2d (WorldObject const * obj) const
{
    float d = GetExactDist2d(obj) - GetObjectSize() - obj->GetObjectSize();
    return d > 0.0f ? d : 0.0f;
}
References Position::GetExactDist2d(), and GetObjectSize().
Referenced by spell_krystallus_shatter_effect::CalculateDamage(), spell_gruul_shatter_effect::CalculateDamage(), spell_loken_pulsing_shockwave::CalculateDamage(), boss_shade_of_aran::CheckAranInRoom(), npc_cork_gizelton::npc_cork_gizeltonAI::CheckCaravan(), spell_baltharus_enervating_brand_trigger::CheckDistance(), boss_onyxia::CheckInRoom(), npc_argent_captainAI::DoAction(), Spell::EffectSummonType(), boss_faction_championsAI::EnemiesInRange(), BattlegroundAB::EventPlayerClickedOnFlag(), spell_blade_dance_targeting::FilterTargets(), BfGraveyard::GetDistance(), npc_spiritual_insight::npc_spiritual_insightAI::GetSpeachId(), GetVelocity(), spell_shadowblink::HandleDummy(), misc_commandscript::HandleGetDistanceCommand(), boss_balinda::JustEngagedWith(), boss_aeonus::JustReachedHome(), npc_winterfin_playmate::MoveInLineOfSight(), npc_snowfall_glade_playmate::MoveInLineOfSight(), npc_the_biggest_tree::MoveInLineOfSight(), npc_high_oracle_soo_roo::MoveInLineOfSight(), npc_elder_kekek::MoveInLineOfSight(), npc_the_etymidian::MoveInLineOfSight(), npc_alexstraza_the_lifebinder::MoveInLineOfSight(), npc_cw_area_trigger::npc_cw_area_triggerAI::MoveInLineOfSight(), npc_grizzlemaw_cw_trigger::npc_grizzlemaw_cw_triggerAI::MoveInLineOfSight(), npc_jungle_punch_target::npc_jungle_punch_targetAI::MoveInLineOfSight(), boss_reliquary_of_souls::boss_reliquary_of_soulsAI::MoveInLineOfSight(), instance_blackrock_depths::instance_blackrock_depths_InstanceMapScript::OnCreatureCreate(), ChargeTargetSelector::operator()(), spell_algalon_cosmic_smash_damage::RecalculateDamage(), boss_priestess_lackey_commonAI::RecalculateThreat(), boss_faction_championsAI::RecalculateThreat(), RevivePlayer(), boss_razuvious::boss_razuviousAI::ScheduleRP(), npc_kiljaeden_controller::SummonedCreatureDies(), Player::TeleportTo(), npc_av_marshal_or_warmaster::npc_av_marshal_or_warmasterAI::UpdateAI(), boss_drekthar::boss_drektharAI::UpdateAI(), boss_galvangar::boss_galvangarAI::UpdateAI(), boss_vanndar::boss_vanndarAI::UpdateAI(), boss_gorosh_the_dervish::boss_gorosh_the_dervishAI::UpdateAI(), boss_grizzle::boss_grizzleAI::UpdateAI(), boss_hedrum::boss_hedrumAI::UpdateAI(), boss_okthor::boss_okthorAI::UpdateAI(), npc_rookery_hatcher::npc_rookery_hatcherAI::UpdateAI(), npc_unworthy_initiate::npc_unworthy_initiateAI::UpdateAI(), npc_eris_hevenfire::npc_eris_hevenfireAI::UpdateAI(), npc_rabid_thistle_bear::npc_rabid_thistle_bearAI::UpdateAI(), npc_twiggy_flathead::npc_twiggy_flatheadAI::UpdateAI(), npc_toc_hunter::npc_toc_hunterAI::UpdateAI(), npc_toc_warrior::npc_toc_warriorAI::UpdateAI(), npc_toc_dk::npc_toc_dkAI::UpdateAI(), npc_toc_rogue::npc_toc_rogueAI::UpdateAI(), npc_vortex_ride::npc_vortex_rideAI::UpdateAI(), npc_preparations_for_war_vehicle::UpdateAI(), npc_boneguard_footman::npc_boneguard_footmanAI::UpdateAI(), npc_pet_gen_fetch_ball::UpdateAI(), BattlefieldWG::UpdatedDestroyedTowerCount(), boss_netherspite::UpdatePortals(), and GameObject::Use().
GetDistanceOrder()
bool WorldObject::GetDistanceOrder (WorldObject const * obj1, WorldObject const * obj2, bool is3D = true) const
{
    float dx1 = GetPositionX() - obj1->GetPositionX();
    float dy1 = GetPositionY() - obj1->GetPositionY();
    float distsq1 = dx1 * dx1 + dy1 * dy1;
    if (is3D)
    {
        float dz1 = GetPositionZ() - obj1->GetPositionZ();
        distsq1 += dz1 * dz1;
    }
    float dx2 = GetPositionX() - obj2->GetPositionX();
    float dy2 = GetPositionY() - obj2->GetPositionY();
    float distsq2 = dx2 * dx2 + dy2 * dy2;
    if (is3D)
    {
        float dz2 = GetPositionZ() - obj2->GetPositionZ();
        distsq2 += dz2 * dz2;
    }
    return distsq1 < distsq2;
}
References Position::GetPositionX(), Position::GetPositionY(), and Position::GetPositionZ().
Referenced by Acore::ObjectDistanceOrderPred::operator()(), and Spell::SearchChainTargets().
GetDistanceZ()
float WorldObject::GetDistanceZ (WorldObject const * obj) const
{
    float dz = std::fabs(GetPositionZ() - obj->GetPositionZ());
    float sizefactor = GetObjectSize() + obj->GetObjectSize();
    float dist = dz - sizefactor;
    return (dist > 0 ? dist : 0);
}
References GetObjectSize(), and Position::GetPositionZ().
Referenced by Creature::CanStartAttack(), and npc_pet_hunter_snake_trap::MoveInLineOfSight().
GetFirstCollisionPosition() [1/3]
Position WorldObject::GetFirstCollisionPosition (float destX, float destY, float destZ)
{
    Position pos = GetPosition();
    auto distance = GetExactDistSq(destX,destY,destZ);
    auto dx = destX - pos.GetPositionX();
    auto dy = destY - pos.GetPositionY();
    auto ang = std::atan2(dy, dx);
    ang = (ang >= 0) ? ang : 2 * M_PI + ang;
    MovePositionToFirstCollision(pos, distance, ang);
    return pos;
}
References Position::GetExactDistSq(), Position::GetPosition(), Position::GetPositionX(), Position::GetPositionY(), and MovePositionToFirstCollision().
GetFirstCollisionPosition() [2/3]
Position WorldObject::GetFirstCollisionPosition (float dist, float angle)
{
    Position pos = GetPosition();
    MovePositionToFirstCollision(pos, dist, angle);
    return pos;
}
References Position::GetPosition(), and MovePositionToFirstCollision().
GetFirstCollisionPosition() [3/3]
Position WorldObject::GetFirstCollisionPosition (float startX, float startY, float startZ, float destX, float destY)
{
    auto dx = destX - startX;
    auto dy = destY - startY;
    auto ang = std::atan2(dy, dx);
    ang = (ang >= 0) ? ang : 2 * M_PI + ang;
    Position pos = Position(startX, startY, startZ, ang);
    auto distance = pos.GetExactDist2d(destX,destY);
    MovePositionToFirstCollision(pos, distance, ang);
    return pos;
}
References Position::GetExactDist2d(), and MovePositionToFirstCollision().
Referenced by Spell::EffectCharge(), Spell::EffectChargeDest(), and spell_class_call_handler::HandleOnHitRogue().
GetFloorZ()
float WorldObject::GetFloorZ () const
{
    if (_updatePositionData)
        const_cast<WorldObject*>(this)->UpdatePositionData();
    if (!IsInWorld())
        return _floorZ;
    return std::max<float>(_floorZ, GetMap()->GetGameObjectFloor(GetPhaseMask(), GetPositionX(), GetPositionY(), GetPositionZ() + std::max(GetCollisionHeight(), Z_OFFSET_FIND_HEIGHT)));
}
References _floorZ, _updatePositionData, GetCollisionHeight(), GetMap(), GetPhaseMask(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Object::IsInWorld(), UpdatePositionData(), and Z_OFFSET_FIND_HEIGHT.
Referenced by npc_icc_nerubar_broodkeeper::npc_icc_nerubar_broodkeeperAI::MoveInLineOfSight(), and Creature::UpdateMovementFlags().
GetGameObjectListWithEntryInGrid() [1/2]
void WorldObject::GetGameObjectListWithEntryInGrid (std::list< GameObject * > & gameobjectList, std::vector< uint32 > const & entries, float maxSearchRange) const
{
    Acore::AllGameObjectsMatchingOneEntryInRange check(this, entries, maxSearchRange);
    Acore::GameObjectListSearcher searcher(this, gameobjectList, check);
    Cell::VisitObjects(this, searcher, maxSearchRange);
}
References Cell::VisitObjects().
GetGameObjectListWithEntryInGrid() [2/2]
void WorldObject::GetGameObjectListWithEntryInGrid (std::list< GameObject * > & lList, uint32 uiEntry, float fMaxSearchRange) const
{
    Acore::AllGameObjectsWithEntryInRange check(this, entry, maxSearchRange);
    Acore::GameObjectListSearcher<Acore::AllGameObjectsWithEntryInRange> searcher(this, gameobjectList, check);
    Cell::VisitObjects(this, searcher, maxSearchRange);
}
References Cell::VisitObjects().
Referenced by npc_necrotic_shard::DespawnEventDoodads(), npc_necropolis_health::DespawnNecropolis(), GetGameObjectListWithEntryInGrid(), spell_q10612_10613_the_fel_and_the_furious::HandleScriptEffect(), npc_midsummer_bonfire_despawner::npc_midsummer_bonfire_despawner(), SmartScript::ProcessEvent(), boss_victor_nefarius::boss_victor_nefariusAI::Reset(), boss_marli::Reset(), npc_necrotic_shard::ScheduleTasks(), go_firework_show::StopShow(), npc_necrotic_shard::SummonCultists(), npc_rookery_hatcher::npc_rookery_hatcherAI::UpdateAI(), and boss_sindragosa::boss_sindragosaAI::UpdateAI().
GetGridActivationRange()
float WorldObject::GetGridActivationRange () const
{
    if (ToPlayer())
    {
        if (ToPlayer()->GetCinematicMgr()->IsOnCinematic())
        {
            return DEFAULT_VISIBILITY_INSTANCE;
        }
        return IsInWintergrasp() ? VISIBILITY_DIST_WINTERGRASP : GetMap()->GetVisibilityRange();
    }
    else if (ToCreature())
    {
        return ToCreature()->m_SightDistance;
    }
    else if (((IsGameObject() && ToGameObject()->IsTransport()) || IsDynamicObject()) && isActiveObject())
    {
        return GetMap()->GetVisibilityRange();
    }
    return 0.0f;
}
References DEFAULT_VISIBILITY_INSTANCE, GetMap(), Map::GetVisibilityRange(), isActiveObject(), Object::IsDynamicObject(), Object::IsGameObject(), IsInWintergrasp(), Creature::m_SightDistance, Object::ToCreature(), Object::ToGameObject(), Object::ToPlayer(), and VISIBILITY_DIST_WINTERGRASP.
Referenced by misc_commandscript::HandleRespawnAllCommand(), and Map::MarkNearbyCellsOf().
GetHitSpherePointFor() [1/2]
void WorldObject::GetHitSpherePointFor (Position const & dest, float & x, float & y, float & z, Optional< float > collisionHeight = { }, Optional< float > combatReach = { }) const
{
    Position pos = GetHitSpherePointFor(dest, collisionHeight, combatReach);
    x = pos.GetPositionX();
    y = pos.GetPositionY();
    z = pos.GetPositionZ();
}
References GetHitSpherePointFor(), Position::GetPositionX(), Position::GetPositionY(), and Position::GetPositionZ().
GetHitSpherePointFor() [2/2]
Position WorldObject::GetHitSpherePointFor (Position const & dest, Optional< float > collisionHeight = { }, Optional< float > combatReach = { }) const
{
    G3D::Vector3 vThis(GetPositionX(), GetPositionY(), GetPositionZ() + (collisionHeight ? *collisionHeight : GetCollisionHeight()));
    G3D::Vector3 vObj(dest.GetPositionX(), dest.GetPositionY(), dest.GetPositionZ());
    G3D::Vector3 contactPoint = vThis + (vObj - vThis).directionOrZero() * std::min(dest.GetExactDist(this), (combatReach ? *combatReach : GetCombatReach()));
    return Position(contactPoint.x, contactPoint.y, contactPoint.z, GetAngle(contactPoint.x, contactPoint.y));
}
References Position::GetAngle(), GetCollisionHeight(), GetCombatReach(), Position::GetExactDist(), Position::GetPositionX(), Position::GetPositionY(), and Position::GetPositionZ().
Referenced by GetHitSpherePointFor(), IsWithinLOS(), IsWithinLOSInMap(), and PathGenerator::ShortenPathUntilDist().
GetInstanceId()
uint32 WorldObject::GetInstanceId () const inline
{ return m_InstanceId; }
References m_InstanceId.
Referenced by Group::_cancelHomebindIfInstance(), Player::_SaveCharacter(), FormationMgr::AddCreatureToGroup(), Map::AddObjectToRemoveList(), Creature::Create(), Group::Disband(), RandomMovementGenerator< T >::DoInitialize(), Player::GetNextQuest(), WorldSession::HandleGroupInviteOpcode(), WorldSession::HandleInstanceLockResponse(), mmaps_commandscript::HandleMmapLoadedTilesCommand(), mmaps_commandscript::HandleMmapLocCommand(), npc_commandscript::HandleNpcInfoCommand(), Player::IsAtRecruitAFriendDistance(), Unit::Kill(), PathGenerator::PathGenerator(), Player::PrepareQuestMenu(), FormationMgr::RemoveCreatureFromGroup(), Vehicle::RemovePassenger(), GameObject::SaveStateToDB(), Corpse::SaveToDB(), Player::SetMover(), and Player::Update().
GetInstanceScript()
InstanceScript * WorldObject::GetInstanceScript () const
{
    Map* map = GetMap();
    return map->IsDungeon() ? map->ToInstanceMap()->GetInstanceScript() : nullptr;
}
References InstanceMap::GetInstanceScript(), GetMap(), Map::IsDungeon(), and Map::ToInstanceMap().
Referenced by CreatureAI::_EnterEvadeMode(), at_karazhan_side_entrance::_OnTrigger(), at_sunwell_madrigosa::_OnTrigger(), at_sunwell_eredar_twins::_OnTrigger(), at_rp_nethekurse::_OnTrigger(), at_icc_spire_frostwyrm::_OnTrigger(), at_zulgurub_entrance_speech::_OnTrigger(), at_zulgurub_bridge_speech::_OnTrigger(), at_zulgurub_temple_speech::_OnTrigger(), at_zulgurub_bloodfire_pit_speech::_OnTrigger(), at_zulgurub_edge_of_madness_speech::_OnTrigger(), at_twin_emperors::_OnTrigger(), at_thaddius_entrance::_OnTrigger(), at_underbog_ghazan::_OnTrigger(), Pet::AddToWorld(), boss_algalon_the_observer::boss_algalon_the_observerAI::boss_algalon_the_observerAI(), boss_anubarak_trial::boss_anubarak_trialAI::boss_anubarak_trialAI(), boss_archavon::boss_archavonAI::boss_archavonAI(), boss_auriaya::boss_auriayaAI::boss_auriayaAI(), boss_bigbadwolf::boss_bigbadwolf(), boss_bjarngrim::boss_bjarngrim(), boss_black_knight::boss_black_knightAI::boss_black_knightAI(), boss_blindeye_the_seer::boss_blindeye_the_seer(), boss_bronjahm::boss_bronjahmAI::boss_bronjahmAI(), boss_crone::boss_crone(), boss_cyanigosa::boss_cyanigosaAI::boss_cyanigosaAI(), boss_dalronn_the_controller::boss_dalronn_the_controller(), boss_devourer_of_souls::boss_devourer_of_soulsAI::boss_devourer_of_soulsAI(), boss_doomrel::boss_doomrelAI::boss_doomrelAI(), boss_dorothee::boss_dorothee(), boss_drakos::boss_drakosAI::boss_drakosAI(), boss_eadric::boss_eadricAI::boss_eadricAI(), boss_emalon::boss_emalonAI::boss_emalonAI(), boss_eregos::boss_eregosAI::boss_eregosAI(), boss_erekem::boss_erekemAI::boss_erekemAI(), boss_faction_championsAI::boss_faction_championsAI(), boss_falric::boss_falricAI::boss_falricAI(), boss_fathomguard_caribdis::boss_fathomguard_caribdis(), boss_fathomguard_sharkkis::boss_fathomguard_sharkkis(), boss_fathomguard_tidalvess::boss_fathomguard_tidalvess(), boss_flame_leviathan_defense_turret::boss_flame_leviathan_defense_turretAI::boss_flame_leviathan_defense_turretAI(), boss_flame_leviathan::boss_flame_leviathanAI::boss_flame_leviathanAI(), boss_freya_summons::boss_freya_summonsAI::boss_freya_summonsAI(), boss_freya::boss_freyaAI::boss_freyaAI(), boss_frostsworn_general::boss_frostsworn_generalAI::boss_frostsworn_generalAI(), boss_garfrost::boss_garfrostAI::boss_garfrostAI(), boss_gormok::boss_gormokAI::boss_gormokAI(), boss_grand_champion::boss_grand_championAI::boss_grand_championAI(), boss_hodir::boss_hodirAI::boss_hodirAI(), boss_icehowl::boss_icehowlAI::boss_icehowlAI(), boss_ichoron::boss_ichoronAI::boss_ichoronAI(), boss_ick::boss_ickAI::boss_ickAI(), boss_illidari_council_memberAI::boss_illidari_council_memberAI(), boss_ingvar_the_plunderer::boss_ingvar_the_plunderer(), boss_jaraxxus::boss_jaraxxusAI::boss_jaraxxusAI(), boss_jormungarAI::boss_jormungarAI(), boss_julianne::boss_julianne(), boss_kiggler_the_crazed::boss_kiggler_the_crazed(), boss_kirtonos_the_herald::boss_kirtonos_the_heraldAI::boss_kirtonos_the_heraldAI(), boss_kologarn_eyebeam::boss_kologarn_eyebeamAI::boss_kologarn_eyebeamAI(), boss_kologarn::boss_kologarnAI::boss_kologarnAI(), boss_koralon::boss_koralonAI::boss_koralonAI(), boss_krick::boss_krickAI::boss_krickAI(), boss_krosh_firehand::boss_krosh_firehand(), boss_krystallus::boss_krystallusAI::boss_krystallusAI(), boss_lavanthor::boss_lavanthorAI::boss_lavanthorAI(), boss_maiden_of_grief::boss_maiden_of_griefAI::boss_maiden_of_griefAI(), boss_malygos::boss_malygosAI::boss_malygosAI(), boss_marwyn::boss_marwynAI::boss_marwynAI(), boss_mimiron::boss_mimironAI::boss_mimironAI(), boss_moragg::boss_moraggAI::boss_moraggAI(), boss_olm_the_summoner::boss_olm_the_summoner(), boss_palehoof::boss_palehoofAI::boss_palehoofAI(), boss_paletress::boss_paletressAI::boss_paletressAI(), boss_priestess_lackey_commonAI::boss_priestess_lackey_commonAI(), boss_razorscale::boss_razorscaleAI::boss_razorscaleAI(), boss_roar::boss_roar(), boss_romulo::boss_romulo(), boss_runemaster_molgeim::boss_runemaster_molgeimAI::boss_runemaster_molgeimAI(), boss_sathrovarr::boss_sathrovarr(), boss_skadi_grauf::boss_skadi_graufAI::boss_skadi_graufAI(), boss_skadi::boss_skadiAI::boss_skadiAI(), boss_skarvald_the_constructor::boss_skarvald_the_constructor(), boss_steelbreaker::boss_steelbreakerAI::boss_steelbreakerAI(), boss_stormcaller_brundir::boss_stormcaller_brundirAI::boss_stormcaller_brundirAI(), boss_strawman::boss_strawman(), boss_svala::boss_svalaAI::boss_svalaAI(), boss_thaddius_summon::boss_thaddius_summonAI::boss_thaddius_summonAI(), boss_thorim::boss_thorimAI::boss_thorimAI(), boss_tinhead::boss_tinhead(), boss_toravon::boss_toravonAI::boss_toravonAI(), boss_twin_valkyrAI::boss_twin_valkyrAI(), boss_tyrannus::boss_tyrannusAI::boss_tyrannusAI(), boss_urom::boss_uromAI::boss_uromAI(), boss_varos::boss_varosAI::boss_varosAI(), boss_vezax::boss_vezaxAI::boss_vezaxAI(), boss_xevozz::boss_xevozzAI::boss_xevozzAI(), boss_xt002::boss_xt002AI::boss_xt002AI(), boss_ymiron::boss_ymironAI::boss_ymironAI(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::boss_yoggsaron_saraAI(), boss_yoggsaron::boss_yoggsaronAI::boss_yoggsaronAI(), boss_zuramat::boss_zuramatAI::boss_zuramatAI(), brann_bronzebeard::brann_bronzebeardAI::brann_bronzebeardAI(), spell_serpentshrine_cavern_coilfang_water::CalcPeriodic(), spell_igb_rocket_pack_useable_aura::CheckAreaTarget(), Spell::CheckCast(), spell_putricide_mutation_init::CheckRequirementInternal(), GameObject::Create(), boss_kologarn_eyebeam::boss_kologarn_eyebeamAI::DamageDealt(), boss_illidari_council_memberAI::DamageTaken(), npc_ulduar_iron_construct::npc_ulduar_iron_constructAI::DamageTaken(), boss_thorim_start_npcs::boss_thorim_start_npcsAI::DamageTaken(), boss_mal_ganis::boss_mal_ganisAI::DamageTaken(), boss_kologarn_arms::boss_kologarn_armsAI::DamageTaken(), boss_yoggsaron_brain::boss_yoggsaron_brainAI::DamageTaken(), boss_razuvious_minion::boss_razuvious_minionAI::DoAction(), boss_thorim_sif::boss_thorim_sifAI::DoAction(), npc_xt002_heart::npc_xt002_heartAI::DoAction(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::DoAction(), boss_yoggsaron_brain::boss_yoggsaron_brainAI::DoAction(), Spell::EffectSanctuary(), Spell::EffectSendEvent(), boss_entropius::EnterEvadeMode(), npc_ghostly_priest::npc_ghostly_priestAI::EnterEvadeMode(), npc_phantom_mage::npc_phantom_mageAI::EnterEvadeMode(), npc_shadowy_mercenary::npc_shadowy_mercenaryAI::EnterEvadeMode(), npc_spectral_footman::npc_spectral_footmanAI::EnterEvadeMode(), npc_tortured_rifleman::npc_tortured_riflemanAI::EnterEvadeMode(), SendEncounterUnit::Execute(), UtherBatteredHiltEvent::Execute(), spell_blood_queen_pact_of_the_darkfallen::FilterTargets(), spell_igb_teleport_players_on_victory::FilterTargets(), SmartScript::GetTargets(), go_brazier_of_madness::GossipHello(), go_blood_drenched_door::go_blood_drenched_doorAI::GossipHello(), go_celestial_planetarium_access::go_celestial_planetarium_accessAI::GossipHello(), spell_felmyst_open_brutallus_back_doors::HandleAfterCast(), spell_thaddius_pos_neg_charge::HandleDamage(), spell_halion_twilight_division::HandleDummy(), spell_teron_gorefiend_shadow_of_death::HandleEffectRemove(), AuraEffect::HandleFeignDeath(), spell_hadronox_summon_periodic_aura::HandlePeriodic(), spell_serpentshrine_cavern_coilfang_water::HandlePeriodic(), spell_festergut_pungent_blight::HandleScript(), spell_putricide_unbound_plague::HandleScript(), spell_auto_repair::HandleScript(), spell_temple_of_atal_hakkar_awaken_the_soulflayer::HandleSendEvent(), spell_uldaman_boss_agro_archaedas::HandleSendEvent(), spell_illidari_council_circle_of_healing::HandleSharedRule(), spell_putricide_mutated_transformation::HandleSummon(), go_eredar_twins_blaze::InitializeAI(), npc_toxic_slime::InitializeAI(), SmartAI::IsEscortInvokerInRange(), npc_hyjal_jaina::hyjalJainaAI::IsSummonedBy(), npc_living_inferno::npc_living_infernoAI::IsSummonedBy(), npc_kinetic_bomb::npc_kinetic_bombAI::IsSummonedBy(), npc_putricide_oozeAI::IsSummonedBy(), boss_kalec::JustDied(), boss_entropius::JustDied(), boss_headless_horseman::JustDied(), npc_hyjal_jaina::hyjalJainaAI::JustDied(), npc_hyjal_thrall::hyjalThrallAI::JustDied(), npc_hyjal_tyrande::hyjalTyrandeAI::JustDied(), boss_infinite_corruptor::boss_infinite_corruptorAI::JustDied(), npc_hor_raging_ghoul::npc_hor_raging_ghoulAI::JustDied(), npc_hor_risen_witch_doctor::npc_hor_risen_witch_doctorAI::JustDied(), npc_hor_lumbering_abomination::npc_hor_lumbering_abominationAI::JustDied(), npc_stinky_icc::npc_stinky_iccAI::JustDied(), npc_precious_icc::npc_precious_iccAI::JustDied(), boss_kelthuzad_minion::boss_kelthuzad_minionAI::JustDied(), boss_thaddius_summon::boss_thaddius_summonAI::JustDied(), npc_mr_bigglesworth::JustDied(), boss_sjonnir_iron_sludge::boss_sjonnir_iron_sludgeAI::JustDied(), npc_auriaya_feral_defender::npc_auriaya_feral_defenderAI::JustDied(), npc_ulduar_iron_construct::npc_ulduar_iron_constructAI::JustDied(), boss_ignis::boss_ignisAI::JustDied(), boss_kologarn_arms::boss_kologarn_armsAI::JustDied(), boss_thorim_start_npcs::boss_thorim_start_npcsAI::JustDied(), boss_thorim_runic_colossus::boss_thorim_runic_colossusAI::JustDied(), boss_thorim_ancient_rune_giant::boss_thorim_ancient_rune_giantAI::JustDied(), npc_xt002_heart::npc_xt002_heartAI::JustDied(), boss_epoch_hunter::JustDied(), boss_freya_elder_stonebark::boss_freya_elder_stonebarkAI::JustDied(), boss_freya_elder_brightleaf::boss_freya_elder_brightleafAI::JustDied(), boss_freya_elder_ironbranch::boss_freya_elder_ironbranchAI::JustDied(), npc_xt002_scrapbot::npc_xt002_scrapbotAI::JustDied(), npc_frost_tomb::JustDied(), npc_crystalline_frayer::JustEngagedWith(), npc_auriaya_sanctum_sentry::npc_auriaya_sanctum_sentryAI::JustEngagedWith(), boss_ignis::boss_ignisAI::JustEngagedWith(), boss_thaddius_summon::boss_thaddius_summonAI::JustEngagedWith(), boss_razuvious_minion::boss_razuvious_minionAI::JustEngagedWith(), boss_headless_horseman::JustReachedHome(), boss_yoggsaron_cloud::boss_yoggsaron_cloudAI::JustSummoned(), npc_frozen_orb_stalker::npc_frozen_orb_stalkerAI::JustSummoned(), npc_warchief_portal::JustSummoned(), boss_captain_skarloc::JustSummoned(), npc_gluttonous_abomination::npc_gluttonous_abominationAI::JustSummoned(), npc_gothik_trigger::npc_gothik_triggerAI::JustSummoned(), npc_boss_gothik_minion::npc_boss_gothik_minionAI::KilledUnit(), boss_grobbulus_poison_cloud::boss_grobbulus_poison_cloudAI::KilledUnit(), boss_kelthuzad_minion::boss_kelthuzad_minionAI::KilledUnit(), boss_razuvious_minion::boss_razuvious_minionAI::KilledUnit(), boss_thaddius_summon::boss_thaddius_summonAI::KilledUnit(), spell_felmyst_open_brutallus_back_doors::Load(), spell_igb_rocket_pack_useable_aura::Load(), spell_igb_gunship_fall_teleport::Load(), spell_igb_teleport_players_on_victory::Load(), spell_the_lich_king_quake::Load(), spell_the_lich_king_harvest_soul_aura::Load(), spell_the_lich_king_restore_soul::Load(), spell_dreamwalker_nightmare_cloud_aura::Load(), npc_ouro_spawner::MoveInLineOfSight(), npc_announcer_toc5::npc_announcer_toc5AI::MovementInform(), npc_xt002_scrapbot::npc_xt002_scrapbotAI::MovementInform(), npc_ahune_bunny::npc_ahune_bunny(), npc_akama_illidan::npc_akama_illidan(), npc_akama_shade::npc_akama_shade(), npc_ancient_wisp::npc_ancient_wisp(), npc_argent_soldier::npc_argent_soldierAI::npc_argent_soldierAI(), npc_arthas::npc_arthasAI::npc_arthasAI(), npc_azure_saboteur::npc_azure_saboteurAI::npc_azure_saboteurAI(), npc_barnes::npc_barnesAI::npc_barnesAI(), npc_belnistrasz::npc_belnistraszAI::npc_belnistraszAI(), npc_black_knight_ghoul::npc_black_knight_ghoulAI::npc_black_knight_ghoulAI(), npc_blood_queen_lana_thel::npc_blood_queen_lana_thelAI::npc_blood_queen_lana_thelAI(), npc_buru_egg::npc_buru_egg(), npc_chained_spirit::npc_chained_spirit(), npc_chesspiece::npc_chesspiece(), npc_creature_generator_akama::npc_creature_generator_akama(), npc_dirt_mound::npc_dirt_mound(), npc_dragonflayer_forge_master::npc_dragonflayer_forge_master(), npc_earthen_ring_flamecaller::npc_earthen_ring_flamecaller(), npc_echo_of_medivh::npc_echo_of_medivh(), npc_erekem_guard::npc_erekem_guardAI::npc_erekem_guardAI(), npc_ferocious_rhino::npc_ferocious_rhinoAI::npc_ferocious_rhinoAI(), npc_forest_frog::npc_forest_frog(), npc_fos_corrupted_soul_fragment::npc_fos_corrupted_soul_fragmentAI::npc_fos_corrupted_soul_fragmentAI(), npc_frenzied_worgen::npc_frenzied_worgenAI::npc_frenzied_worgenAI(), npc_frost_tomb::npc_frost_tomb(), npc_frozen_core::npc_frozen_core(), npc_general_andorov::npc_general_andorov(), npc_grimstone::npc_grimstoneAI::npc_grimstoneAI(), npc_harrison_jones::npc_harrison_jones(), npc_healing_ward::npc_healing_ward(), npc_high_overlord_saurfang_icc::npc_high_overlord_saurfangAI::npc_high_overlord_saurfangAI(), npc_hive_zara_larva::npc_hive_zara_larva(), npc_hor_leader_second::npc_hor_leader_secondAI::npc_hor_leader_secondAI(), npc_hor_leader::npc_hor_leaderAI::npc_hor_leaderAI(), npc_hor_lich_king::npc_hor_lich_kingAI::npc_hor_lich_kingAI(), npc_hover_disk::npc_hover_diskAI::npc_hover_diskAI(), npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI::npc_icc_gauntlet_controllerAI(), npc_icc_putricades_trap::npc_icc_putricades_trapAI::npc_icc_putricades_trapAI(), npc_ichor_globule::npc_ichor_globuleAI::npc_ichor_globuleAI(), npc_image_of_medivh::npc_image_of_medivhAI::npc_image_of_medivhAI(), npc_kalecgos_kj::npc_kalecgos_kj(), npc_kiljaeden_controller::npc_kiljaeden_controller(), npc_kilrek::npc_kilrek(), npc_madrigosa::npc_madrigosa(), npc_maiev_illidan::npc_maiev_illidan(), npc_massive_jormungar::npc_massive_jormungarAI::npc_massive_jormungarAI(), npc_medivh_bm::npc_medivh_bm(), npc_memory::npc_memoryAI::npc_memoryAI(), npc_millhouse_manastorm::npc_millhouse_manastormAI::npc_millhouse_manastormAI(), npc_molten_golem::npc_molten_golem(), npc_muradin_bronzebeard_icc::npc_muradin_bronzebeard_iccAI::npc_muradin_bronzebeard_iccAI(), npc_nerubian_burrower::npc_nerubian_burrowerAI::npc_nerubian_burrowerAI(), npc_nexus_lord::npc_nexus_lordAI::npc_nexus_lordAI(), npc_oculus_drake::npc_oculus_drakeAI::npc_oculus_drakeAI(), npc_oculus_drakegiver::npc_oculus_drakegiverAI::npc_oculus_drakegiverAI(), npc_pos_after_first_boss::npc_pos_after_first_bossAI::npc_pos_after_first_bossAI(), npc_pos_collapsing_icicle::npc_pos_collapsing_icicleAI::npc_pos_collapsing_icicleAI(), npc_pos_deathwhisper_necrolyte::npc_pos_deathwhisper_necrolyteAI::npc_pos_deathwhisper_necrolyteAI(), npc_pos_icicle_trigger::npc_pos_icicle_triggerAI::npc_pos_icicle_triggerAI(), npc_pos_leader_second::npc_pos_leader_secondAI::npc_pos_leader_secondAI(), npc_pos_leader::npc_pos_leaderAI::npc_pos_leaderAI(), npc_pos_martin_or_gorkun_second::npc_pos_martin_or_gorkun_secondAI::npc_pos_martin_or_gorkun_secondAI(), npc_pos_tyrannus_events::npc_pos_tyrannus_eventsAI::npc_pos_tyrannus_eventsAI(), npc_power_spark::npc_power_sparkAI::npc_power_sparkAI(), npc_ravenous_furbolg::npc_ravenous_furbolgAI::npc_ravenous_furbolgAI(), npc_risen_guardian::npc_risen_guardianAI::npc_risen_guardianAI(), npc_rocknot::npc_rocknotAI::npc_rocknotAI(), npc_scholomance_occultist::npc_scholomance_occultistAI::npc_scholomance_occultistAI(), npc_scion_of_eternity::npc_scion_of_eternityAI::npc_scion_of_eternityAI(), npc_sergeant_bly::npc_sergeant_blyAI::npc_sergeant_blyAI(), npc_sindragosa_trash::npc_sindragosa_trashAI::npc_sindragosa_trashAI(), npc_snobold_vassal::npc_snobold_vassalAI::npc_snobold_vassalAI(), npc_taretha::npc_tarethaAI::npc_tarethaAI(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::npc_thrall_old_hillsbradAI(), npc_time_rift::npc_time_rift(), npc_tito::npc_tito(), npc_toc5_grand_champion_minion::npc_toc5_grand_champion_minionAI::npc_toc5_grand_champion_minionAI(), npc_ulduar_aerial_command_unit::npc_ulduar_aerial_command_unitAI::npc_ulduar_aerial_command_unitAI(), npc_ulduar_expedition_commander::npc_ulduar_expedition_commanderAI::npc_ulduar_expedition_commanderAI(), npc_ulduar_expedition_engineer::npc_ulduar_expedition_engineerAI::npc_ulduar_expedition_engineerAI(), npc_ulduar_flash_freeze::npc_ulduar_flash_freezeAI::npc_ulduar_flash_freezeAI(), npc_ulduar_harpoonfirestate::npc_ulduar_harpoonfirestateAI::npc_ulduar_harpoonfirestateAI(), npc_ulduar_hodir_druid::npc_ulduar_hodir_druidAI::npc_ulduar_hodir_druidAI(), npc_ulduar_hodir_mage::npc_ulduar_hodir_mageAI::npc_ulduar_hodir_mageAI(), npc_ulduar_hodir_priest::npc_ulduar_hodir_priestAI::npc_ulduar_hodir_priestAI(), npc_ulduar_hodir_shaman::npc_ulduar_hodir_shamanAI::npc_ulduar_hodir_shamanAI(), npc_ulduar_leviathan_mkii::npc_ulduar_leviathan_mkiiAI::npc_ulduar_leviathan_mkiiAI(), npc_ulduar_magnetic_core::npc_ulduar_magnetic_coreAI::npc_ulduar_magnetic_coreAI(), npc_ulduar_saronite_animus::npc_ulduar_saronite_animusAI::npc_ulduar_saronite_animusAI(), npc_ulduar_saronite_vapors::npc_ulduar_saronite_vaporsAI::npc_ulduar_saronite_vaporsAI(), npc_ulduar_vx001::npc_ulduar_vx001AI::npc_ulduar_vx001AI(), npc_vh_teleportation_portal::npc_vh_teleportation_portalAI::npc_vh_teleportation_portalAI(), npc_vh_void_sentry::npc_vh_void_sentryAI::npc_vh_void_sentryAI(), npc_vrykul_skeleton::npc_vrykul_skeleton(), npc_weegli_blastfuse::npc_weegli_blastfuseAI::npc_weegli_blastfuseAI(), npc_zealot_lorkhan::npc_zealot_lorkhan(), npc_zealot_zath::npc_zealot_zath(), spell_blood_queen_vampiric_bite::OnCast(), achievement_cant_do_that_while_stunned::OnCheck(), achievement_auriaya_crazy_cat_lady::OnCheck(), achievement_auriaya_nine_lives::OnCheck(), achievement_kologarn_looks_could_kill::OnCheck(), achievement_kologarn_rubble_and_roll::OnCheck(), achievement_kologarn_with_open_arms::OnCheck(), achievement_xt002_nerf_engineering::OnCheck(), achievement_xt002_nerf_gravity_bombs::OnCheck(), achievement_flame_leviathan_unbroken::OnCheck(), achievement_thorim_stand_in_the_lightning::OnCheck(), achievement_thorim_lose_your_illusion::OnCheck(), achievement_yogg_saron_darkness::OnCheck(), achievement_yogg_saron_he_waits_dreaming::OnCheck(), go_shadowforge_brazier::OnGossipHello(), go_blackened_urn::OnGossipHello(), go_gong_of_bethekk::OnGossipHello(), go_palehoof_sphere::OnGossipHello(), go_vh_activation_crystal::OnGossipHello(), go_main_chambers_access_panel::OnGossipHello(), go_broggok_lever::OnGossipHello(), npc_barnes::OnGossipHello(), npc_arthas::OnGossipHello(), npc_cos_chromie_middle::OnGossipHello(), npc_thrall_old_hillsbrad::OnGossipHello(), npc_announcer_toc5::OnGossipHello(), npc_announcer_toc10::OnGossipHello(), npc_hor_leader::OnGossipHello(), npc_high_overlord_saurfang_icc::OnGossipHello(), npc_muradin_bronzebeard_icc::OnGossipHello(), npc_alchemist_adrianna::OnGossipHello(), npc_oculus_drakegiver::OnGossipHello(), brann_bronzebeard::OnGossipHello(), npc_ulduar_expedition_commander::OnGossipHello(), npc_vh_sinclari::OnGossipHello(), go_orb_of_domination::OnGossipHello(), icecrown_citadel_teleport::OnGossipHello(), go_ulduar_do_not_push_this_button::OnGossipHello(), go_strange_pool::OnGossipHello(), go_ulduar_pure_saronite_deposit::OnGossipHello(), go_harpoon_canon::OnGossipHello(), go_the_focusing_iris::OnGossipHello(), go_ulduar_working_harpoon::OnGossipHello(), npc_hyjal_jaina::OnGossipSelect(), npc_hyjal_thrall::OnGossipSelect(), boss_gloomrel::OnGossipSelect(), boss_doomrel::OnGossipSelect(), npc_zulaman_hostage::OnGossipSelect(), npc_high_overlord_saurfang_icc::OnGossipSelect(), npc_muradin_bronzebeard_icc::OnGossipSelect(), npc_announcer_toc5::OnGossipSelect(), npc_announcer_toc10::OnGossipSelect(), npc_hor_leader::OnGossipSelect(), npc_ulduar_expedition_commander::OnGossipSelect(), npc_vh_sinclari::OnGossipSelect(), npc_cos_chromie_start::OnGossipSelect(), npc_cos_chromie_middle::OnGossipSelect(), npc_thrall_old_hillsbrad::OnGossipSelect(), npc_hor_leader_second::OnGossipSelect(), npc_icc_buff_switcher::OnGossipSelect(), go_pumpkin_shrine::OnGossipSelect(), go_father_flame::OnLootStateChanged(), npc_cos_chromie_start::OnQuestAccept(), npc_cos_chromie_middle::OnQuestAccept(), npc_rocknot::OnQuestReward(), spell_blood_queen_frenzied_bloodthirst_aura::OnRemove(), OnlyOnceAreaTriggerScript::OnTrigger(), at_trigger_the_beast_movement::OnTrigger(), at_the_beast_room::OnTrigger(), at_karazhan_atiesh_aran::OnTrigger(), at_karazhan_mirkblood_approach::OnTrigger(), at_karazhan_mirkblood_entrance::OnTrigger(), at_cthun_stomach_exit::OnTrigger(), at_cthun_center::OnTrigger(), at_baltharus_plateau::OnTrigger(), at_hor_battered_hilt_start::OnTrigger(), at_hor_battered_hilt_throw::OnTrigger(), at_lady_deathwhisper_entrance::OnTrigger(), at_sindragosa_lair::OnTrigger(), at_icc_saurfang_portal::OnTrigger(), at_icc_shutdown_traps::OnTrigger(), at_icc_start_blood_quickening::OnTrigger(), at_icc_start_frostwing_gauntlet::OnTrigger(), at_icc_gauntlet_event::OnTrigger(), at_icc_putricide_trap::OnTrigger(), at_frozen_throne_teleport::OnTrigger(), at_naxxramas_hub_portal::OnTrigger(), at_quagmirran_lair::OnTrigger(), at_shattered_halls_execution::OnTrigger(), at_ring_of_law::OnTrigger(), at_dragonspire_hall::OnTrigger(), at_blackrock_stadium::OnTrigger(), at_malfurion_stormrage::OnTrigger(), at_battleguard_sartura::OnTrigger(), at_hor_shadow_throne::OnTrigger(), at_tyrannus_event_starter::OnTrigger(), ValithriaDespawner::operator()(), npc_hyjal_jaina::hyjalJainaAI::PathEndReached(), SmartScript::ProcessAction(), spell_igb_gunship_fall_teleport::RelocateDest(), npc_dark_fiend::Reset(), npc_hyjal_jaina::hyjalJainaAI::Reset(), npc_hyjal_thrall::hyjalThrallAI::Reset(), boss_infinite_corruptor::boss_infinite_corruptorAI::Reset(), go_sand_trap::Reset(), npc_xerestrasza::npc_xerestraszaAI::Reset(), npc_announcer_toc5::npc_announcer_toc5AI::Reset(), boss_ignis::boss_ignisAI::Reset(), npc_xt002_scrapbot::npc_xt002_scrapbotAI::Reset(), npc_xt002_boombot::npc_xt002_boombotAI::Reset(), OnlyOnceAreaTriggerScript::ResetAreaTriggerDone(), GameObject::SaveStateToDB(), spell_the_lich_king_valkyr_target_search::SelectTarget(), spell_igb_gunship_fall_teleport::SelectTransport(), Player::SendInitWorldStates(), Player::SendLoot(), Unit::setDeathState(), Player::SetInWater(), boss_victor_nefarius::boss_victor_nefariusAI::sGossipSelect(), npc_ulduar_iron_construct::npc_ulduar_iron_constructAI::SpellHit(), npc_ulduar_keeper::npc_ulduar_keeperAI::SpellHit(), npc_living_constellation::npc_living_constellationAI::SpellHit(), npc_ulduar_rocket_strike_trigger::npc_ulduar_rocket_strike_triggerAI::SpellHitTarget(), boss_yoggsaron_voice::boss_yoggsaron_voiceAI::SpellHitTarget(), npc_gothik_trigger::npc_gothik_triggerAI::SummonedCreatureDespawn(), TriggerBurningPitch(), npc_bone_spike::npc_bone_spikeAI::UpdateAI(), npc_frost_freeze_trap::npc_frost_freeze_trapAI::UpdateAI(), boss_thaddius_summon::boss_thaddius_summonAI::UpdateAI(), npc_brann_bronzebeard_algalon::npc_brann_bronzebeard_algalonAI::UpdateAI(), npc_ulduar_flash_freeze::npc_ulduar_flash_freezeAI::UpdateAI(), npc_ulduar_bot_summon_trigger::npc_ulduar_bot_summon_triggerAI::UpdateAI(), npc_ulduar_flames_initial::npc_ulduar_flames_initialAI::UpdateAI(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::UpdateAI(), npc_xt002_scrapbot::npc_xt002_scrapbotAI::UpdateAI(), npc_xt002_boombot::npc_xt002_boombotAI::UpdateAI(), Player::UpdateArea(), Map::UpdateEncounterState(), violet_hold_trashAI::violet_hold_trashAI(), and npc_black_knight_skeletal_gryphon::npc_black_knight_skeletal_gryphonAI::WaypointReached().
getLevelForTarget()
virtual uint8 WorldObject::getLevelForTarget (WorldObject const *) const inline virtual
Reimplemented in Unit, Creature, and GameObject.
{ return 1; }
Referenced by CanDetectStealthOf().
GetLiquidData()
LiquidData const & WorldObject::GetLiquidData () const
{
    if (_updatePositionData)
        const_cast<WorldObject*>(this)->UpdatePositionData();
    return _liquidData;
}
References _liquidData, _updatePositionData, and UpdatePositionData().
Referenced by Unit::isInAccessiblePlaceFor(), Unit::IsInWater(), Unit::IsUnderWater(), Unit::ProcessTerrainStatusUpdate(), Player::ProcessTerrainStatusUpdate(), and Creature::UpdateMovementFlags().
GetMap()
Map * WorldObject::GetMap () const inline
{ ASSERT(m_currMap); return m_currMap; }
References ASSERT, and m_currMap.
Referenced by Map::_FindGameObject(), Battleground::_ProcessResurrect(), RandomMovementGenerator< T >::_setRandomLocation(), boss_sjonnir::boss_sjonnirAI::ActivatePipe(), Map::AddPlayerToMap(), AddToMapVisibilityOverrideContainers(), AddToObjectUpdate(), GameObject::AddToSkillupList(), Corpse::AddToWorld(), Creature::AddToWorld(), DynamicObject::AddToWorld(), GameObject::AddToWorld(), AddToWorld(), Pet::AddToWorld(), Map::ApplyDynamicModeRespawnScaling(), npc_ritual_channeler::npc_ritual_channelerAI::AttackStart(), npc_av_marshal_or_warmaster::npc_av_marshal_or_warmasterAI::AttackStart(), boss_drekthar::boss_drektharAI::AttackStart(), boss_vanndar::boss_vanndarAI::AttackStart(), CinematicMgr::BeginCinematic(), boss_flame_leviathan::boss_flame_leviathanAI::BindPlayers(), DynamicObject::BindToCaster(), Player::BuildPlayerRepop(), PathGenerator::BuildPolyPath(), MotionTransport::BuildUpdate(), StaticTransport::BuildUpdate(), spell_svala_ritual_strike_aura::CalculateAmount(), spell_gen_consumption::CalculateDamage(), Creature::CanCreatureAttack(), Unit::CanHaveThreatList(), CanNeverSee(), Creature::CanPeriodicallyCallForAssistance(), Player::CanRollForItemInLFG(), boss_professor_putricide::boss_professor_putricideAI::ChangePhase(), Spell::CheckCast(), Map::CheckCollisionAndGetValidCoords(), Player::CheckDuelDistance(), Spell::CheckEffectTarget(), spell_sha_fire_nova::CheckFireTotem(), boss_gothik::boss_gothikAI::CheckGroupSplitted(), Player::CheckInstanceLoginValid(), boss_volazj::CheckPhaseMinions(), boss_skadi_grauf::boss_skadi_graufAI::CheckPlayers(), BattlegroundRV::CheckPositionForUnit(), boss_heigan::CheckSafetyDance(), Spell::CheckSpellFocus(), Creature::Create(), Pet::CreateBaseAtCreature(), Pet::CreateBaseAtCreatureInfo(), Player::CreateCorpse(), DynamicObject::CreateDynamicObject(), Creature::CreateFromProto(), MotionTransport::CreateGOPassenger(), MotionTransport::CreateNPCPassenger(), Player::CreatePet(), Player::CreatePet(), TransportMgr::CreateTransport(), boss_eregos::boss_eregosAI::DamageTaken(), boss_eadric::boss_eadricAI::DamageTaken(), boss_ick::boss_ickAI::DamageTaken(), boss_freya::boss_freyaAI::DamageTaken(), npc_molten_golem::DamageTaken(), boss_the_lich_king::boss_the_lich_kingAI::DamageTaken(), boss_thorim::boss_thorimAI::DamageTaken(), MotionTransport::DelayedTeleportTransport(), Creature::DeleteFromDB(), GameObject::DeleteFromDB(), Creature::DespawnOnEvade(), boss_twin_valkyrAI::DoAction(), boss_nightbane::DoAction(), npc_harrison_jones::DoAction(), boss_ayamiss::DoAction(), npc_thrall_warchief::npc_thrall_warchiefAI::DoAction(), npc_orb_carrier::npc_orb_carrierAI::DoAction(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::DoAction(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::DoAction(), boss_the_lich_king::boss_the_lich_kingAI::DoAction(), npc_strangulate_vehicle::npc_strangulate_vehicleAI::DoAction(), npc_arthas::npc_arthasAI::DoAction(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::DoAction(), boss_illidari_council::DoAction(), Spell::DoAllEffectOnTarget(), boss_algalon_the_observer::boss_algalon_the_observerAI::DoCheckHeraldOfTheTitans(), MotionTransport::DoEventIfAny(), FlightPathMovementGenerator::DoEventIfAny(), WorldSession::DoLootRelease(), ScriptedAI::DoPlayMusic(), npc_forest_frog::DoSpawnRandom(), ScriptedAI::DoTeleportAll(), boss_icehowl::boss_icehowlAI::DoTrampleIfValid(), CreatureAI::DoZoneInCombat(), Player::DuelComplete(), DynObjAura::DynObjAura(), Spell::EffectAddFarsight(), Spell::EffectCreateTamedPet(), Spell::EffectDestroyAllTotems(), Spell::EffectDuel(), Spell::EffectDummy(), Spell::EffectPersistentAA(), Spell::EffectScriptEffect(), Spell::EffectSendEvent(), Spell::EffectSummonObject(), Spell::EffectSummonObjectWild(), Spell::EffectSummonPet(), Spell::EffectSummonType(), Spell::EffectTameCreature(), Spell::EffectTeleportUnits(), Spell::EffectTransmitted(), boss_sapphiron::boss_sapphironAI::EnterCombatSelfFunction(), npc_av_marshal_or_warmaster::npc_av_marshal_or_warmasterAI::EnterEvadeMode(), boss_drekthar::boss_drektharAI::EnterEvadeMode(), boss_vanndar::boss_vanndarAI::EnterEvadeMode(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::EnterEvadeMode(), boss_malygos::boss_malygosAI::EnterEvadeMode(), BattleExperienceEvent::Execute(), Unit::ExecuteDelayedUnitRelocationEvent(), SmartScript::FillScript(), npc_singularity::FindAndFollowTarget(), SmartScript::FindCreatureNear(), SmartScript::FindGameObjectNear(), Creature::ForcedDespawn(), boss_thorim::boss_thorimAI::GetArenaPlayer(), Player::GetCorpse(), ObjectAccessor::GetCorpse(), ObjectAccessor::GetCreature(), ChatHandler::GetCreatureFromPlayerMapByDbGuid(), ObjectAccessor::GetDynamicObject(), GetFloorZ(), ObjectAccessor::GetGameObject(), Player::GetGameObjectIfCanInteractWith(), GetGridActivationRange(), GetInstanceScript(), GetMapHeight(), GetMapWaterOrGroundLevel(), Unit::GetMeleeAttackPoint(), PathGenerator::GetNavTerrain(), Player::GetNextQuest(), ChatHandler::GetObjectFromPlayerMapByDbGuid(), ObjectAccessor::GetPet(), ObjectAccessor::GetPlayer(), GetSightRange(), npc_ranshalla::npc_ranshallaAI::GetSpeakerByEntry(), SpellMgr::GetSpellIdForDifficulty(), SmartScript::GetTargets(), ObjectAccessor::GetTransport(), GetVisibilityRange(), go_celestial_planetarium_access::go_celestial_planetarium_accessAI::GossipHello(), misc_commandscript::HandleAppearCommand(), WorldSession::HandleAreaSpiritHealerQueryOpcode(), WorldSession::HandleAreaSpiritHealerQueueOpcode(), WorldSession::HandleAreaTriggerOpcode(), AuraEffect::HandleAuraDummy(), Unit::HandleAuraProc(), WorldSession::HandleAutostoreLootItemOpcode(), WorldSession::HandleBattlemasterHelloOpcode(), WorldSession::HandleBattlemasterJoinArena(), misc_commandscript::HandleChangeWeather(), spell_freezing_circle::HandleDamage(), debug_commandscript::HandleDebugMapDataCommand(), debug_commandscript::HandleDebugSpawnVehicleCommand(), debug_commandscript::HandleDebugVisibilityDataCommand(), debug_commandscript::HandleDebugZoneStatsCommand(), OutdoorPvPSI::HandleDropFlag(), spell_item_nitro_boots::HandleDummy(), spell_sha_fire_nova::HandleDummy(), spell_teron_gorefiend_shadowy_construct::HandleEffectApply(), spell_valkyr_touch_aura::HandleEffectPeriodic(), AuraEffect::HandleFeignDeath(), gobject_commandscript::HandleGameObjectAddCommand(), WorldSession::HandleGameobjectReportUse(), WorldSession::HandleGossipSelectOptionOpcode(), misc_commandscript::HandleGroupSummonCommand(), instance_commandscript::HandleInstanceSaveDataCommand(), list_commandscript::HandleListCreatureCommand(), list_commandscript::HandleListObjectCommand(), WorldSession::HandleLootMasterGiveOpcode(), WorldSession::HandleLootMoneyOpcode(), AuraEffect::HandleModInvisibility(), AuraEffect::HandleModPossessPet(), AuraEffect::HandleModStealth(), WorldSession::HandleMoverRelocation(), WorldSession::HandleMoveTeleportAck(), WorldSession::HandleMoveWorldportAck(), npc_commandscript::HandleNpcAddCommand(), spell_yogg_saron_brain_link_aura::HandleOnEffectApply(), WorldSession::HandlePetAction(), AuraEffect::HandlePhase(), WorldSession::HandlePlayerLoginFromDB(), WorldSession::HandlePlayerLoginToCharInWorld(), AuraEffect::HandlePreventResurrection(), spell_dreamwalker_summon_portal::HandleScript(), spell_prince_taldaram_conjure_flame_sphere::HandleScript(), WorldSession::HandleSetDungeonDifficultyOpcode(), WorldSession::HandleSetRaidDifficultyOpcode(), misc_commandscript::HandleSkirmishCommand(), spell_halion_damage_aoe_summon::HandleSummon(), spell_putricide_mutated_transformation::HandleSummon(), spell_wintergrasp_create_vehicle::HandleSummon(), misc_commandscript::HandleSummonCommand(), WorldSession::HandleTotemDestroyed(), spell_winter_veil_racer_rocket_slam::HandleTriggerSpell(), wp_commandscript::HandleWpModifyCommand(), wp_commandscript::HandleWpShowCommand(), Player::HasQuestForGO(), Player::HasQuestForItem(), boss_ichoron::boss_ichoronAI::IchoronDoCastToAllHostilePlayers(), Creature::InitEntry(), TempSummon::InitStats(), Player::inRandomLfgDungeon(), InstanceHasScript(), boss_halion::boss_halionAI::IsAnyPlayerValid(), Player::IsAtGroupRewardDistance(), Unit::isAttackingPlayer(), npc_valkyr_shadowguard::npc_valkyr_shadowguardAI::IsHeroic(), npc_strangulate_vehicle::npc_strangulate_vehicleAI::IsHeroic(), Unit::isInAccessiblePlaceFor(), PathGenerator::IsSwimmableSegment(), Creature::IsUpdateNeeded(), GameObject::IsUpdateNeeded(), IsWithinLOS(), IsWithinLOSInMap(), npc_ranshalla::npc_ranshallaAI::JustDidDialogueStep(), boss_rend_blackhand::boss_rend_blackhandAI::JustDied(), boss_apothecary_hummel::boss_apothecary_hummelAI::JustDied(), npc_coren_direbrew::JustDied(), boss_headless_horseman::JustDied(), boss_azuregos::boss_azuregosAI::JustDied(), boss_rajaxx::JustDied(), boss_skeram::JustDied(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::JustDied(), npc_gunship::npc_gunshipAI::JustDied(), boss_sjonnir::boss_sjonnirAI::JustDied(), boss_yoggsaron::boss_yoggsaronAI::JustDied(), boss_ahune::JustDied(), boss_four_horsemen::boss_four_horsemenAI::JustDied(), boss_alar::JustDied(), boss_devourer_of_souls::boss_devourer_of_soulsAI::JustEngagedWith(), boss_krystallus::boss_krystallusAI::JustEngagedWith(), boss_sjonnir::boss_sjonnirAI::JustEngagedWith(), boss_shirrak_the_dead_watcher::JustEngagedWith(), boss_alyson_antille::JustEngagedWith(), boss_ossirian::JustEngagedWith(), npc_tirion_fordring_tft::npc_tirion_fordringAI::JustReachedHome(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::JustSummoned(), boss_gothik::boss_gothikAI::JustSummoned(), Unit::Kill(), Player::KilledMonsterCredit(), Player::KilledPlayerCredit(), spell_svalna_revive_champion::Land(), boss_felblood_kaelthas::LapseAction(), spell_the_lich_king_vile_spirits_aura::Load(), Creature::LoadCreatureFromDB(), GameObject::LoadGameObjectFromDB(), StaticTransport::LoadGameObjectFromDB(), Pet::LoadPetFromDB(), MotionTransport::LoadStaticPassengers(), WorldSession::LogoutPlayer(), AchievementCriteriaData::Meets(), MotionMaster::MoveBackwards(), MotionMaster::MoveFall(), MotionMaster::MoveForwards(), npc_ulduar_snow_mound::MoveInLineOfSight(), npc_tirion_fordring_tft::npc_tirion_fordringAI::MovementInform(), npc_valkyr_shadowguard::npc_valkyr_shadowguardAI::MovementInform(), boss_malygos::boss_malygosAI::MovementInform(), boss_the_lich_king::boss_the_lich_kingAI::MovementInform(), MovePositionToFirstCollision(), npc_image_of_medivh::npc_image_of_medivhAI::NextStep(), npc_frost_sphere::npc_frost_sphereAI::npc_frost_sphereAI(), WaypointMovementGenerator< Creature >::OnArrived(), achievement_once_bitten_twice_shy::OnCheck(), npc_essence_of_twin::OnGossipHello(), lfg::LFGPlayerScript::OnPlayerMapChanged(), at_ancient_leaf::OnTrigger(), at_icc_saurfang_portal::OnTrigger(), AreaTrigger_at_celestial_planetarium_enterance::OnTrigger(), at_shattered_halls_execution::OnTrigger(), boss_pyroguard_emberseer::boss_pyroguard_emberseerAI::OpenDoors(), boss_nightbane::PathEndReached(), Unit::PetSpellFail(), spell_halion_twilight_phasing::Phase(), Player::PrepareQuestMenu(), spell_fire_festival_fortitude::PrepareSpellScript(), SmartScript::ProcessAction(), WorldSession::ProcessMovementInfo(), ProcessPositionDataChanged(), GameObject::Refresh(), Vehicle::RelocatePassengers(), Player::RemovedInsignia(), RemoveFromMapVisibilityOverrideContainers(), RemoveFromObjectUpdate(), Corpse::RemoveFromWorld(), Creature::RemoveFromWorld(), DynamicObject::RemoveFromWorld(), GameObject::RemoveFromWorld(), Pet::RemoveFromWorld(), boss_krystallus::boss_krystallusAI::RemoveStonedEffect(), boss_sartharion_dragonAI::RemoveTwilightPortal(), Player::RepopAtGraveyard(), boss_rend_blackhand::boss_rend_blackhandAI::Reset(), boss_azuregos::boss_azuregosAI::Reset(), boss_ossirian::Reset(), npc_tirion_fordring_tft::npc_tirion_fordringAI::Reset(), npc_raging_spirit::npc_raging_spiritAI::Reset(), npc_frostwing_vrykul::npc_frostwing_vrykulAI::Reset(), boss_sjonnir::boss_sjonnirAI::Reset(), boss_kologarn_pit_kill_bunny::Reset(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::Reset(), Player::ResetMap(), boss_volazj::ResetPlayersPhaseMask(), GameObject::Respawn(), Creature::Respawn(), Player::RewardQuest(), Player::RewardReputation(), Creature::SaveRespawnTime(), GameObject::SaveRespawnTime(), ScriptedAI::ScriptedAI(), Map::ScriptsProcess(), Spell::SearchTargets(), boss_yoggsaron_constrictor_tentacle::boss_yoggsaron_constrictor_tentacleAI::SelectConstrictTarget(), boss_yoggsaron_corruptor_tentacle::boss_yoggsaron_corruptor_tentacleAI::SelectCorruptionTarget(), Spell::SelectImplicitCasterDestTargets(), boss_gluth::boss_gluthAI::SelectPlayerInRoom(), boss_thorim_arena_npcs::boss_thorim_arena_npcsAI::SelectT(), spell_gen_rallying_cry_of_the_dragonslayer::SelectTarget(), ScriptedAI::SelectTargetFromPlayerList(), npc_minigob_manabonk::SelectTargetInDalaran(), CreatureTextMgr::SendChatPacket(), Player::SendInitialPacketsAfterAddToMap(), Player::SendInitialPacketsBeforeAddToMap(), Player::SendLoot(), CreatureTextMgr::SendNonChatPacket(), SendPacketToPlayers(), Acore::VisibleNotifier::SendToSelf(), npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::SendUpdateWorldState(), npc_pos_tyrannus_events::npc_pos_tyrannus_eventsAI::SetData(), boss_pyroguard_emberseer::boss_pyroguard_emberseerAI::SetData(), Creature::setDeathState(), spell_blood_council_summon_shadow_resonance::SetDest(), spell_spawn_blood_pool::SetDest(), GameObject::SetDestructibleState(), Player::SetEntryPoint(), npc_gunship::npc_gunshipAI::SetGUID(), Unit::SetHover(), Creature::SetLootRecipient(), Unit::SetPhaseMask(), Creature::SetPosition(), GameObject::SetPosition(), boss_akilzon::SetWeather(), npc_tirion_fordring_tft::npc_tirion_fordringAI::sGossipSelect(), PathGenerator::ShortenPathUntilDist(), Player::SpawnCorpseBones(), boss_hodir::boss_hodirAI::SpawnHelpers(), boss_jaraxxus::boss_jaraxxusAI::SpellHit(), boss_the_lich_king::boss_the_lich_kingAI::SpellHitTarget(), Player::StoreRaidMapDifficulty(), boss_majordomo::boss_majordomoAI::SummonedCreatureDies(), npc_kiljaeden_controller::SummonedCreatureDies(), npc_varian_wrynn::npc_varian_wrynnAI::SummonedCreatureDies(), npc_thrall_bfu::npc_thrall_bfuAI::SummonedCreatureDies(), SummonGameObject(), Spell::SummonGuardian(), Player::SummonPet(), boss_rend_blackhand::boss_rend_blackhandAI::SummonWave(), brann_bronzebeard::brann_bronzebeardAI::SwitchHeadVisaul(), lfg::LFGMgr::TeleportPlayer(), Player::TeleportTo(), MotionTransport::TeleportTransport(), Vehicle::TeleportVehicle(), Unit::UnsummonAllTotems(), Pet::Update(), MotionTransport::Update(), DynamicObject::Update(), GameObject::Update(), Creature::Update(), Player::Update(), AchievementMgr::UpdateAchievementCriteria(), boss_rend_blackhand::boss_rend_blackhandAI::UpdateAI(), boss_chromaggus::boss_chromaggusAI::UpdateAI(), boss_nefarian::UpdateAI(), boss_vaelastrasz::boss_vaelAI::UpdateAI(), npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::UpdateAI(), npc_varian_wrynn::npc_varian_wrynnAI::UpdateAI(), npc_thrall_bfu::npc_thrall_bfuAI::UpdateAI(), npc_forest_frog::UpdateAI(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::UpdateAI(), npc_time_rift::UpdateAI(), boss_cthun::UpdateAI(), npc_toc5_grand_champion_minion::npc_toc5_grand_champion_minionAI::UpdateAI(), boss_grand_champion::boss_grand_championAI::UpdateAI(), npc_snobold_vassal::npc_snobold_vassalAI::UpdateAI(), boss_gormok::boss_gormokAI::UpdateAI(), boss_twin_valkyrAI::UpdateAI(), npc_pos_tyrannus_events::npc_pos_tyrannus_eventsAI::UpdateAI(), boss_prince_valanar_icc::boss_prince_valanarAI::UpdateAI(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::UpdateAI(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::UpdateAI(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::UpdateAI(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::UpdateAI(), npc_gunship_boarding_addAI::UpdateAI(), npc_gunship_gunner::npc_gunship_gunnerAI::UpdateAI(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::UpdateAI(), boss_the_lich_king::boss_the_lich_kingAI::UpdateAI(), npc_tirion_fordring_tft::npc_tirion_fordringAI::UpdateAI(), npc_raging_spirit::npc_raging_spiritAI::UpdateAI(), npc_icc_valkyr_herald::npc_icc_valkyr_heraldAI::UpdateAI(), npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI::UpdateAI(), npc_icc_putricades_trap::npc_icc_putricades_trapAI::UpdateAI(), npc_ioc_gunship_captain::npc_ioc_gunship_captainAI::UpdateAI(), boss_gluth::boss_gluthAI::UpdateAI(), boss_sapphiron::boss_sapphironAI::UpdateAI(), boss_malygos::boss_malygosAI::UpdateAI(), npc_scion_of_eternity::npc_scion_of_eternityAI::UpdateAI(), npc_alexstrasza::npc_alexstraszaAI::UpdateAI(), boss_keristrasza::UpdateAI(), npc_brann_bronzebeard_algalon::npc_brann_bronzebeard_algalonAI::UpdateAI(), boss_freya::boss_freyaAI::UpdateAI(), boss_freya_nature_bomb::boss_freya_nature_bombAI::UpdateAI(), boss_vezax::boss_vezaxAI::UpdateAI(), boss_hodir::boss_hodirAI::UpdateAI(), boss_ignis::boss_ignisAI::UpdateAI(), boss_mimiron::boss_mimironAI::UpdateAI(), npc_ulduar_leviathan_mkii::npc_ulduar_leviathan_mkiiAI::UpdateAI(), npc_ulduar_flames_initial::npc_ulduar_flames_initialAI::UpdateAI(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::UpdateAI(), npc_preparations_for_war_vehicle::UpdateAI(), npc_pet_gen_plump_turkey::UpdateAI(), npc_gunship::npc_gunshipAI::UpdateAI(), npc_midsummer_bonfire::UpdateBonfireBlessingBuffs(), Player::UpdateCharmedAI(), npc_grimstone::npc_grimstoneAI::UpdateEscortAI(), GameObject::UpdateModel(), GameObject::UpdateModelPosition(), StaticTransport::UpdatePassengerPositions(), MotionTransport::UpdatePassengerPositions(), boss_netherspite::UpdatePortals(), Unit::UpdatePosition(), MotionTransport::UpdatePosition(), StaticTransport::UpdatePosition(), UpdatePositionData(), boss_pyroguard_emberseer::boss_pyroguard_emberseerAI::UpdateRunes(), Player::UpdateVisibilityOf(), npc_herald_of_the_lich_king::UpdateWeather(), npc_pallid_horror::UpdateWeather(), Player::UpdateZone(), GameObject::Use(), Cell::VisitFarVisibleObjects(), Cell::VisitObjects(), npc_ranshalla::npc_ranshallaAI::WaypointReached(), npc_grimstone::npc_grimstoneAI::WaypointReached(), npc_thrall_bfu::npc_thrall_bfuAI::WaypointReached(), and npc_cork_gizelton::npc_cork_gizeltonAI::WaypointReached().
GetMapHeight()
float WorldObject::GetMapHeight (float x, float y, float z, bool vmap = true, float distanceToSearch = 50.0f) const
{
    if (z != MAX_HEIGHT)
        z += std::max(GetCollisionHeight(), Z_OFFSET_FIND_HEIGHT);
    return GetMap()->GetHeight(GetPhaseMask(), x, y, z, vmap, distanceToSearch);
}
References GetCollisionHeight(), Map::GetHeight(), GetMap(), GetPhaseMask(), MAX_HEIGHT, and Z_OFFSET_FIND_HEIGHT.
Referenced by npc_pet_dk_ebon_gargoyle::InitializeAI(), boss_cyanigosa::boss_cyanigosaAI::JustDied(), MotionMaster::MoveFall(), MovePosition(), IgbArtilleryCheck::operator()(), npc_kinetic_bomb::npc_kinetic_bombAI::Reset(), npc_invis_infernal_caster::npc_invis_infernal_casterAI::Reset(), Spell::SelectImplicitCasterDestTargets(), spell_azjol_nerub_impale_summon::SetDest(), spell_blood_council_summon_shadow_resonance::SetDest(), spell_necropolis_beam::SetDest(), boss_freya::boss_freyaAI::SpawnWave(), npc_rimefang::npc_rimefangAI::UpdateAI(), boss_ormorok::UpdateAI(), boss_freya::boss_freyaAI::UpdateAI(), UpdateAllowedPositionZ(), and UpdateGroundPositionZ().
GetMapWaterOrGroundLevel() [1/2]
float WorldObject::GetMapWaterOrGroundLevel (float x, float y, float z, float * ground = nullptr) const
{
    return GetMap()->GetWaterOrGroundLevel(GetPhaseMask(), x, y, z, ground,
        IsUnit() ? !static_cast<Unit const*>(this)->HasWaterWalkAura() : false,
        std::max(GetCollisionHeight(),  Z_OFFSET_FIND_HEIGHT));
}
References GetCollisionHeight(), GetMap(), GetPhaseMask(), Map::GetWaterOrGroundLevel(), Object::IsUnit(), and Z_OFFSET_FIND_HEIGHT.
GetMapWaterOrGroundLevel() [2/2]
float WorldObject::GetMapWaterOrGroundLevel (Position pos, float * ground = nullptr) const inline
    {
        return GetMapWaterOrGroundLevel(pos.GetPositionX(), pos.GetPositionY(), pos.GetPositionZ(), ground);
    };
References GetMapWaterOrGroundLevel(), Position::GetPositionX(), Position::GetPositionY(), and Position::GetPositionZ().
Referenced by RandomMovementGenerator< T >::_setRandomLocation(), spell_gen_summon_target_floor::ChangeSummonPos(), boss_taldaram::DoAction(), GetMapWaterOrGroundLevel(), spell_q12589_shoot_rjr::HandleDummy(), and UpdateAllowedPositionZ().
GetMinHeightInWater()
float WorldObject::GetMinHeightInWater () const
Get the minimum height of a object that should be in water to start floating/swim.
Returns
float
{
    // have a fun with Archimedes' formula
    auto height = GetCollisionHeight();
    auto width = GetCollisionWidth();
    auto weight = getWeight(height, width, 1040); // avg human specific weight
    auto heightOutOfWater = getOutOfWater(width, weight, 10202) * 4.0f; // avg human density
    auto heightInWater = height - heightOutOfWater;
    return (height > heightInWater ? heightInWater : (height - (height / 3)));
}
References GetCollisionHeight(), GetCollisionWidth(), getOutOfWater(), and getWeight().
Referenced by Map::HasEnoughWater(), and UpdateAllowedPositionZ().
GetName()
std::string const & WorldObject::GetName () const inline
{ return m_name; }
References m_name.
Referenced by Player::_LoadActions(), Player::_LoadHomeBind(), Player::_LoadInventory(), Player::_LoadItem(), Player::_LoadMailedItem(), Player::_LoadQuestStatus(), Player::_LoadSkills(), Player::_SaveCharacter(), Player::_SaveInventory(), Guild::_SendBankList(), Group::AddLeaderInvite(), Guild::AddMember(), ArenaTeam::AddMember(), Group::AddMember(), Vehicle::AddPassenger(), Battleground::AddPlayer(), InstanceMap::AddPlayerToMap(), Player::ApplyBaseModPctValue(), Group::BroadcastGroupUpdate(), WorldSession::BuildPartyMemberStatsChangedPacket(), Player::BuildPlayerRepop(), Player::BuyItemFromVendorSlot(), Player::CanBankItem(), InstanceMap::CannotEnter(), WorldSession::CanOpenMailBox(), Player::CastItemCombatSpell(), Group::ChangeLeader(), Player::CheckAreaExploreAndOutdoor(), Player::CheckSkillLearnedBySpell(), Corpse::Create(), Group::Create(), Guild::Create(), TransportMgr::CreateTransport(), FlightPathMovementGenerator::DoEventIfAny(), Player::DuelComplete(), Spell::EffectScriptEffect(), Player::EnvironmentalDamage(), ChatHandler::extractPlayerTarget(), Pet::FillPetInfo(), GetDebugInfo(), Unit::GetFactionTemplateEntry(), Player::GetGameObjectIfCanInteractWith(), Creature::GetNameForLocaleIdx(), GameObject::GetNameForLocaleIdx(), ChatHandler::GetNameLink(), WorldSession::GetPlayerInfo(), GetPlayerInfo(), Player::GetPlayerName(), WorldSession::GetPlayerName(), ReputationMgr::GetReputation(), Creature::GetSummonerGUID(), GmTicket::GmTicket(), WorldSession::HandleAcceptTradeOpcode(), account_commandscript::HandleAccountCreateCommand(), spell_rog_deadly_poison::HandleAfterHit(), WorldSession::HandleAreaTriggerOpcode(), WorldSession::HandleArenaTeamAcceptOpcode(), WorldSession::HandleArenaTeamInviteOpcode(), WorldSession::HandleArenaTeamLeaderOpcode(), WorldSession::HandleArenaTeamLeaveOpcode(), WorldSession::HandleArenaTeamRemoveOpcode(), WorldSession::HandleAuctionSellItem(), Player::HandleBaseModFlatValue(), WorldSession::HandleBattlefieldListOpcode(), WorldSession::HandleBattleFieldPortOpcode(), WorldSession::HandleBattlemasterJoinArena(), debug_commandscript::HandleDebugGetLootRecipientCommand(), debug_commandscript::HandleDebugHostileRefListCommand(), debug_commandscript::HandleDebugLoSCommand(), debug_commandscript::HandleDebugSendOpcodeCommand(), debug_commandscript::HandleDebugThreatListCommand(), deserter_commandscript::HandleDeserterAdd(), WorldSession::HandleDuelAcceptedOpcode(), WorldSession::HandleFarSightOpcode(), WorldSession::HandleForceSpeedChangeAck(), ticket_commandscript::HandleGMTicketCloseByIdCommand(), ticket_commandscript::HandleGMTicketCommentCommand(), ticket_commandscript::HandleGMTicketCompleteCommand(), ticket_commandscript::HandleGMTicketDeleteByIdCommand(), ticket_commandscript::HandleGMTicketResponseDeleteCommand(), ticket_commandscript::HandleGMTicketUnAssignCommand(), WorldSession::HandleGrantLevel(), WorldSession::HandleGroupDeclineOpcode(), WorldSession::HandleGroupInviteOpcode(), group_commandscript::HandleGroupJoinCommand(), WorldSession::HandleInstanceLockResponse(), inventory_commandscript::HandleInventoryCountCommand(), Guild::HandleInviteMember(), Guild::HandleLeaveMember(), lookup_commandscript::HandleLookupTitleCommand(), WorldSession::HandleLootMasterGiveOpcode(), WorldSession::HandleMailTakeItem(), Guild::HandleMemberDepositMoney(), Guild::HandleMemberLogout(), Guild::HandleMemberWithdrawMoney(), WorldSession::HandleMessagechatOpcode(), mmaps_commandscript::HandleMmapPathCommand(), misc_commandscript::HandleMovegensCommand(), npc_commandscript::HandleNpcDoActionCommand(), npc_commandscript::HandleNpcFollowCommand(), npc_commandscript::HandleNpcSetDataCommand(), npc_commandscript::HandleNpcUnFollowCommand(), WorldSession::HandleOfferPetitionOpcode(), WorldSession::HandleOpenItemOpcode(), WorldSession::HandlePetitionBuyOpcode(), WorldSession::HandlePetitionSignOpcode(), OutdoorPvP::HandlePlayerLeaveZone(), WorldSession::HandlePlayerLoginFromDB(), WorldSession::HandleQuestgiverChooseRewardOpcode(), WorldSession::HandleQuestgiverCompleteQuest(), Guild::HandleRemoveMember(), WorldSession::HandleReportPvPAFK(), WorldSession::HandleRequestPartyMemberStatsOpcode(), ArenaSpectator::HandleResetCommand(), spell_the_flag_of_ownership::HandleScript(), WorldSession::HandleSendMail(), WorldSession::HandleSetActionButtonOpcode(), Guild::HandleSetLeader(), misc_commandscript::HandleSkirmishCommand(), misc_commandscript::HandleSummonCommand(), titles_commandscript::HandleTitlesAddCommand(), titles_commandscript::HandleTitlesCurrentCommand(), titles_commandscript::HandleTitlesRemoveCommand(), WorldSession::HandleTurnInPetitionOpcode(), Guild::HandleUpdateMemberRank(), npc_pet_gen_imp_in_a_bottle::InitializeAI(), PlayerNameMapHolder::Insert(), Channel::Invite(), BattlegroundQueue::InviteGroupToBG(), Player::IsActionButtonDataValid(), ReputationMgr::IsAtWar(), lfg::LFGMgr::JoinLfg(), WorldSession::KickPlayer(), Player::LearnCustomSpells(), Player::LoadFromDB(), WaypointMovementGenerator< Creature >::LoadPath(), LogCommandUsage(), WorldSession::LogoutPlayer(), MotionMaster::MovePath(), MotionMaster::MoveTaxiFlight(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnCreatureCreate(), ChatLogScript::OnPlayerCanUseChat(), ChatLogScript::OnPlayerCanUseChat(), ChatLogScript::OnPlayerCanUseChat(), ChatLogScript::OnPlayerCanUseChat(), ChatLogScript::OnPlayerCanUseChat(), lfg::LFGPlayerScript::OnPlayerMapChanged(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnUnitDeath(), Unit::OutDebugInfo(), MapMgr::PlayerCannotEnter(), Player::PrepareGossipMenu(), SmartScript::ProcessAction(), PlayerNameMapHolder::Remove(), Map::RemoveAllPlayers(), Player::RemoveFromWorld(), Vehicle::RemovePassenger(), Creature::Respawn(), Pet::SavePetToDB(), AchievementMgr::SendAchievementEarned(), CreatureTextMgr::SendChat(), Guild::SendLoginInfo(), Spell::SendLoot(), WorldSession::SendPetNameQuery(), BattlegroundMgr::SendToBattleground(), Unit::SetCharm(), Player::setDeathState(), Player::SetEquipmentSet(), Channel::SetMode(), Guild::Member::SetStats(), Creature::SetTextRepeatId(), Player::SetViewpoint(), npc_chesspiece::sGossipHello(), FollowerAI::StartFollow(), Player::StopCastingCharm(), lfg::LFGMgr::TeleportPlayer(), Player::TeleportTo(), Channel::UnBan(), Pet::Update(), Player::Update(), boss_archavon::boss_archavonAI::UpdateAI(), Player::UpdateHomebindTime(), GameObject::Use(), and Player::Whisper().
GetNameForLocaleIdx()
virtual std::string const & WorldObject::GetNameForLocaleIdx (LocaleConstant) const inline virtual
Reimplemented in Creature, and GameObject.
{ return m_name; }
References m_name.
Referenced by ChatHandler::BuildChatPacket(), Acore::EmoteChatBuilder::operator()(), and Spell::SendResurrectRequest().
GetNearPoint()
void WorldObject::GetNearPoint (WorldObject const * searcher, float & x, float & y, float & z, float searcher_size, float distance2d, float absAngle, float controlZ = 0, Position const * startPos = nullptr) const
{
    GetNearPoint2D(x, y, distance2d + searcher_size, absAngle, startPos);
    z = GetPositionZ();
    if (searcher)
    {
        if (Unit const* unit = searcher->ToUnit(); Unit const* target = ToUnit())
        {
            if (unit && target && unit->IsInWater() && target->IsInWater())
            {
                // if the searcher is in water
                // we have no ground so we can
                // set the target height to the
                // z-coord to keep the searcher
                // at the correct height (face to face)
                z += GetCollisionHeight() - unit->GetCollisionHeight();
            }
        }
        searcher->UpdateAllowedPositionZ(x, y, z);
    }
    else
    {
        UpdateAllowedPositionZ(x, y, z);
    }
    // if detection disabled, return first point
    if (!sWorld->getBoolConfig(CONFIG_DETECT_POS_COLLISION))
        return;
    // return if the point is already in LoS
    if (!controlZ && IsWithinLOS(x, y, z))
        return;
    // remember first point
    float first_x = x;
    float first_y = y;
    float first_z = z;
    // loop in a circle to look for a point in LoS using small steps
    for (float angle = float(M_PI) / 8; angle < float(M_PI) * 2; angle += float(M_PI) / 8)
    {
        GetNearPoint2D(x, y, distance2d + searcher_size, absAngle + angle, startPos);
        z = GetPositionZ();
        UpdateAllowedPositionZ(x, y, z);
        if (controlZ && fabsf(GetPositionZ() - z) > controlZ)
            continue;
        if (IsWithinLOS(x, y, z))
            return;
    }
    // still not in LoS, give up and return first position found
    if (startPos)
    {
        x = searcher->GetPositionX();
        y = searcher->GetPositionY();
        z = searcher->GetPositionZ();
    }
    else
    {
        x = first_x;
        y = first_y;
        z = first_z;
    }
}
References CONFIG_DETECT_POS_COLLISION, GetCollisionHeight(), GetNearPoint2D(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Unit::IsInWater(), IsWithinLOS(), sWorld, Object::ToUnit(), and UpdateAllowedPositionZ().
Referenced by npc_maiev_illidan::DoAction(), ChaseMovementGenerator< T >::DoUpdate(), GetChargeContactPoint(), GetClosePoint(), GetContactPoint(), Unit::GetMeleeAttackPoint(), Unit::GetRandomContactPoint(), GetVoidClosePoint(), npc_hourglass_of_eternity::npc_hourglass_of_eternityAI::InitializeAI(), npc_akama_shade::JustSummoned(), npc_akama_illidan::MovementInform(), SmartScript::ProcessAction(), npc_pallid_horror::ScheduleTasks(), Spell::SelectImplicitCasterDestTargets(), boss_quartermaster_zigris::SpellHitTarget(), and npc_hourglass_of_eternity::npc_hourglass_of_eternityAI::UpdateAI().
GetNearPoint2D() [1/2]
void WorldObject::GetNearPoint2D (float & x, float & y, float distance, float absAngle, Position const * startPos = nullptr) const
{
    GetNearPoint2D(nullptr, x, y, distance2d, absAngle, startPos);
}
References GetNearPoint2D().
GetNearPoint2D() [2/2]
void WorldObject::GetNearPoint2D (WorldObject const * searcher, float & x, float & y, float distance, float absAngle, Position const * startPos = nullptr) const
{
    float effectiveReach = GetCombatReach();
    if (searcher)
    {
        effectiveReach += searcher->GetCombatReach();
        if (this != searcher)
        {
            float myHover = 0.0f, searcherHover = 0.0f;
            if (Unit const* unit = ToUnit())
                myHover = unit->GetHoverHeight();
            if (Unit const* searchUnit = searcher->ToUnit())
                searcherHover = searchUnit->GetHoverHeight();
            float hoverDelta = myHover - searcherHover;
            if (hoverDelta != 0.0f)
                effectiveReach = std::sqrt(std::max(effectiveReach * effectiveReach - hoverDelta * hoverDelta, 0.0f));
        }
    }
    float positionX = startPos ? startPos->GetPositionX() : GetPositionX();
    float positionY = startPos ? startPos->GetPositionY() : GetPositionY();
    x = positionX + (effectiveReach + distance2d) * std::cos(absAngle);
    y = positionY + (effectiveReach + distance2d) * std::sin(absAngle);
    Acore::NormalizeMapCoord(x);
    Acore::NormalizeMapCoord(y);
}
References GetCombatReach(), Position::GetPositionX(), Position::GetPositionY(), Acore::NormalizeMapCoord(), and Object::ToUnit().
Referenced by GetNearPoint(), GetNearPoint2D(), and npc_frostbrood_skytalon::npc_frostbrood_skytalonAI::UpdateAI().
GetNearPosition()
Position WorldObject::GetNearPosition (float dist, float angle)
{
    Position pos = GetPosition();
    MovePosition(pos, dist, angle);
    return pos;
}
References Position::GetPosition(), and MovePosition().
Referenced by boss_headless_horseman::DamageTaken(), npc_time_rift::DoSummonAtRift(), Spell::EffectSummonType(), spell_q9847_a_spirit_ally::HandleSendEvent(), npc_simone::npc_simoneAI::JustDied(), spell_svalna_revive_champion::Land(), spell_gen_random_target32::ModDest(), spell_q12308_escape_from_silverbrook_summon_worgen::ModDest(), go_beacon::go_beaconAI::OnStateChanged(), npc_simone::npc_simoneAI::RespawnPet(), npc_stillpine_capitive::npc_stillpine_capitiveAI::StartMoving(), boss_anzu::SummonBroods(), and npc_time_rift::UpdateAI().
GetNotifyFlags()
uint16 WorldObject::GetNotifyFlags () const inline
{ return m_notifyflags; }
References m_notifyflags.
GetObjectSize()
float WorldObject::GetObjectSize () const
{
    return (m_valuesCount > UNIT_FIELD_COMBATREACH) ? m_floatValues[UNIT_FIELD_COMBATREACH] : DEFAULT_WORLD_OBJECT_SIZE * GetObjectScale();
}
References DEFAULT_WORLD_OBJECT_SIZE, Object::GetObjectScale(), Object::m_floatValues, Object::m_valuesCount, and UNIT_FIELD_COMBATREACH.
Referenced by _IsWithinDist(), GameObject::_IsWithinDist(), Creature::CanCreatureAttack(), Spell::EffectSummonPet(), GetChargeContactPoint(), GetClosePoint(), GetCollisionRadius(), GetCollisionWidth(), Unit::GetCollisionWidth(), GetContactPoint(), GetDistance(), GetDistance(), GetDistance(), GetDistance2d(), GetDistance2d(), GetDistanceZ(), Unit::GetMeleeAttackPoint(), GetVelocity(), misc_commandscript::HandleGroupSummonCommand(), spell_marrowgar_coldflame::HandleScriptEffect(), IsInBetween(), IsInRange(), IsInRange2d(), IsInRange3d(), IsWithinDist2d(), IsWithinDist2d(), IsWithinDist3d(), IsWithinDist3d(), MotionMaster::MoveJumpTo(), Acore::WorldObjectSpellConeTargetCheck::operator()(), SmartScript::ProcessAction(), npc_released_offspring_harkoa::npc_released_offspring_harkoaAI::Reset(), npc_dragonmaw_peon::npc_dragonmaw_peonAI::SpellHit(), SummonCreature(), npc_acherus_necromancer::npc_acherus_necromancerAI::UpdateAI(), npc_gothik_the_harvester::npc_gothik_the_harvesterAI::UpdateAI(), and npc_valkyr_battle_maiden::npc_valkyr_battle_maidenAI::UpdateAI().
GetObjectVisibilityContainer() [1/2]
ObjectVisibilityContainer & WorldObject::GetObjectVisibilityContainer () inline
{ return _objectVisibilityContainer; }
References _objectVisibilityContainer.
Referenced by DestroyForVisiblePlayers(), DoForAllVisiblePlayers(), DoForAllVisibleWorldObjects(), debug_commandscript::HandleDebugVisibilityDataCommand(), WorldSession::HandlePlayerLoginToCharInWorld(), Player::HaveAtClient(), Creature::IsUpdateNeeded(), GameObject::IsUpdateNeeded(), ObjectVisibilityContainer::LinkWorldObjectVisibility(), Player::Player(), RemoveFromWorld(), SendMessageToSet(), Player::SendMessageToSet(), SendMessageToSetInRange(), Player::SendMessageToSetInRange(), Player::SendQuestGiverStatusMultiple(), Acore::VisibleNotifier::SendToSelf(), ObjectVisibilityContainer::UnlinkVisibilityFromPlayer(), ObjectVisibilityContainer::UnlinkVisibilityFromWorldObject(), ObjectVisibilityContainer::UnlinkWorldObjectVisibility(), Player::UpdateForQuestWorldObjects(), Player::UpdateTriggerVisibility(), Player::UpdateVisibilityOf(), Player::UpdateVisibilityOf(), UpdateVisibilityOf_helper(), UpdateVisibilityOf_helper(), UpdateVisibilityOf_helper(), and UpdateVisibilityOf_helper().
GetObjectVisibilityContainer() [2/2]
ObjectVisibilityContainer const & WorldObject::GetObjectVisibilityContainer () const inline
{ return _objectVisibilityContainer; }
References _objectVisibilityContainer.
GetPhaseMask()
uint32 WorldObject::GetPhaseMask () const inline
{ return m_phaseMask; }
References m_phaseMask.
Referenced by RandomMovementGenerator< T >::_setRandomLocation(), AddToWorld(), PathGenerator::BuildPolyPath(), Map::CheckCollisionAndGetValidCoords(), boss_volazj::CheckPhaseMinions(), BattlegroundRV::CheckPositionForUnit(), Map::ConvertCorpseToBones(), Creature::Create(), Corpse::Create(), Pet::CreateBaseAtCreature(), Pet::CreateBaseAtCreatureInfo(), DynamicObject::CreateDynamicObject(), Spell::EffectDuel(), Spell::EffectSummonObject(), Spell::EffectSummonObjectWild(), Spell::EffectTransmitted(), GameObject::EnableCollision(), GetFloorZ(), GetMapHeight(), GetMapWaterOrGroundLevel(), PathGenerator::GetNavTerrain(), GameObjectModelOwnerImpl::GetPhaseMask(), Player::GetPhaseMaskForSpawn(), debug_commandscript::HandleDebugSpawnVehicleCommand(), OutdoorPvPSI::HandleDropFlag(), gobject_commandscript::HandleGameObjectInfoCommand(), gobject_commandscript::HandleGameObjectNearCommand(), misc_commandscript::HandleGPSCommand(), npc_commandscript::HandleNpcInfoCommand(), npc_commandscript::HandleNpcNearCommand(), misc_commandscript::HandlePInfoCommand(), Map::HasEnoughWater(), InSamePhase(), InSamePhase(), PathGenerator::IsSwimmableSegment(), IsWithinLOS(), IsWithinLOSInMap(), npc_the_lich_king_controller::npc_the_lich_king_controllerAI::JustSummoned(), spell_svalna_revive_champion::Land(), Creature::LoadCreatureFromDB(), Pet::LoadPetFromDB(), instance_old_hillsbrad::instance_old_hillsbrad_InstanceMapScript::OnGameObjectCreate(), at_q24545_frostmourne_cavern::OnTrigger(), IgbArtilleryCheck::operator()(), WorldSession::ProcessMovementInfo(), Corpse::SaveToDB(), Creature::SaveToDB(), Creature::SaveToDB(), GameObject::SaveToDB(), Spell::SelectImplicitCasterDestTargets(), Creature::setDeathState(), spell_blood_council_summon_shadow_resonance::SetDest(), spell_spawn_blood_pool::SetDest(), Unit::SetHover(), Unit::SetPhaseMask(), PathGenerator::ShortenPathUntilDist(), Map::SummonCreature(), SummonGameObject(), Player::SummonPet(), SummonTrigger(), Creature::Update(), and UpdatePositionData().
GetRandomNearPosition()
Position WorldObject::GetRandomNearPosition (float radius)
{
    Position pos = GetPosition();
    MovePosition(pos, radius * (float) rand_norm(), (float) rand_norm() * static_cast<float>(2 * M_PI));
    return pos;
}
References Position::GetPosition(), MovePosition(), and rand_norm().
Referenced by CreatureAI::DoSummon(), CreatureAI::DoSummonFlyer(), npc_cyclone::JustEngagedWith(), npc_enslaved_netherwing_drake::SpellHit(), and npc_minigob_manabonk::UpdateAI().
GetRandomPoint() [1/2]
Position WorldObject::GetRandomPoint (const Position & srcPos, float distance) const
{
    float x, y, z;
    GetRandomPoint(srcPos, distance, x, y, z);
    return Position(x, y, z, GetOrientation());
}
References Position::GetOrientation(), and GetRandomPoint().
GetRandomPoint() [2/2]
void WorldObject::GetRandomPoint (const Position & srcPos, float distance, float & rand_x, float & rand_y, float & rand_z) const
{
    if (!distance)
    {
        pos.GetPosition(rand_x, rand_y, rand_z);
        return;
    }
    // angle to face `obj` to `this`
    float angle = (float)rand_norm() * static_cast<float>(2 * M_PI);
    float new_dist = (float)rand_norm() * static_cast<float>(distance);
    rand_x = pos.m_positionX + new_dist * cos(angle);
    rand_y = pos.m_positionY + new_dist * std::sin(angle);
    rand_z = pos.m_positionZ;
    Acore::NormalizeMapCoord(rand_x);
    Acore::NormalizeMapCoord(rand_y);
    UpdateGroundPositionZ(rand_x, rand_y, rand_z);            // update to LOS height if available
}
References Position::GetPosition(), Position::m_positionX, Position::m_positionY, Position::m_positionZ, Acore::NormalizeMapCoord(), rand_norm(), and UpdateGroundPositionZ().
Referenced by boss_isalien::DamageTaken(), instance_stratholme::instance_stratholme_InstanceMapScript::DoSpawnPlaguedCritters(), Spell::EffectSummonType(), OrcMoveEvent::Execute(), GetRandomPoint(), SmartScript::ProcessAction(), Spell::SummonGuardian(), and boss_fankriss::SummonHatchlingWaves().
GetSightRange()
float WorldObject::GetSightRange (WorldObject const * target = nullptr) const virtual
Reimplemented in Player.
{
    if (ToUnit())
    {
        if (ToPlayer())
        {
            if (target)
            {
                if (target->IsCreature() && target->IsVisibilityOverridden())
                    return target->GetVisibilityOverrideDistance();
                else if (target->IsGameObject())
                {
                    if (IsInWintergrasp() && target->IsInWintergrasp())
                        return VISIBILITY_DIST_WINTERGRASP;
                    else if (target->IsVisibilityOverridden())
                        return target->GetVisibilityOverrideDistance();
                    else if (ToPlayer()->GetCinematicMgr()->IsOnCinematic())
                        return DEFAULT_VISIBILITY_INSTANCE;
                    else
                        return GetMap()->GetVisibilityRange();
                }
                return IsInWintergrasp() && target->IsInWintergrasp() ? VISIBILITY_DIST_WINTERGRASP : GetMap()->GetVisibilityRange();
            }
            return IsInWintergrasp() ? VISIBILITY_DIST_WINTERGRASP : GetMap()->GetVisibilityRange();
        }
        else if (ToCreature())
            return ToCreature()->m_SightDistance;
        else
            return SIGHT_RANGE_UNIT;
    }
    if (ToDynObject() && isActiveObject())
        return GetMap()->GetVisibilityRange();
    return 0.0f;
}
References DEFAULT_VISIBILITY_INSTANCE, GetMap(), GetVisibilityOverrideDistance(), Map::GetVisibilityRange(), isActiveObject(), Object::IsCreature(), Object::IsGameObject(), IsInWintergrasp(), IsVisibilityOverridden(), Creature::m_SightDistance, SIGHT_RANGE_UNIT, Object::ToCreature(), Object::ToDynObject(), Object::ToPlayer(), Object::ToUnit(), and VISIBILITY_DIST_WINTERGRASP.
Referenced by CanSeeOrDetect(), and Player::GetSightRange().
GetStationaryO()
virtual float WorldObject::GetStationaryO () const inline virtual
Reimplemented in GameObject.
{ return GetOrientation(); }
References Position::GetOrientation().
GetStationaryX()
virtual float WorldObject::GetStationaryX () const inline virtual
Reimplemented in GameObject.
{ return GetPositionX(); }
References Position::GetPositionX().
GetStationaryY()
virtual float WorldObject::GetStationaryY () const inline virtual
Reimplemented in GameObject.
{ return GetPositionY(); }
References Position::GetPositionY().
GetStationaryZ()
virtual float WorldObject::GetStationaryZ () const inline virtual
Reimplemented in GameObject.
{ return GetPositionZ(); }
References Position::GetPositionZ().
GetTransGUID()
ObjectGuid WorldObject::GetTransGUID () const virtual
Reimplemented in Unit.
{
    if (GetTransport())
        return GetTransport()->GetGUID();
    return ObjectGuid::Empty;
}
References ObjectGuid::Empty, Object::GetGUID(), and GetTransport().
Referenced by IgbTeleportOnVictoryCheck::operator()(), and SpellDestination::SpellDestination().
GetTransOffsetO()
float WorldObject::GetTransOffsetO () const inline
{ return m_movementInfo.transport.pos.GetOrientation(); }
References Position::GetOrientation(), m_movementInfo, MovementInfo::TransportInfo::pos, and MovementInfo::transport.
Referenced by Player::_SaveCharacter(), Unit::BuildMovementPacket(), Object::BuildMovementUpdate(), npc_commandscript::HandleNpcAddCommand(), SpellCastTargets::Read(), Creature::SaveToDB(), and SpellDestination::SpellDestination().
GetTransOffsetX()
float WorldObject::GetTransOffsetX () const inline
{ return m_movementInfo.transport.pos.GetPositionX(); }
References Position::GetPositionX(), m_movementInfo, MovementInfo::TransportInfo::pos, and MovementInfo::transport.
Referenced by Player::_SaveCharacter(), Unit::BuildMovementPacket(), npc_commandscript::HandleNpcAddCommand(), SpellCastTargets::Read(), Creature::SaveToDB(), and SpellDestination::SpellDestination().
GetTransOffsetY()
float WorldObject::GetTransOffsetY () const inline
{ return m_movementInfo.transport.pos.GetPositionY(); }
References Position::GetPositionY(), m_movementInfo, MovementInfo::TransportInfo::pos, and MovementInfo::transport.
Referenced by Player::_SaveCharacter(), Unit::BuildMovementPacket(), npc_commandscript::HandleNpcAddCommand(), SpellCastTargets::Read(), Creature::SaveToDB(), and SpellDestination::SpellDestination().
GetTransOffsetZ()
float WorldObject::GetTransOffsetZ () const inline
{ return m_movementInfo.transport.pos.GetPositionZ(); }
References Position::GetPositionZ(), m_movementInfo, MovementInfo::TransportInfo::pos, and MovementInfo::transport.
Referenced by Player::_SaveCharacter(), Unit::BuildMovementPacket(), npc_commandscript::HandleNpcAddCommand(), SpellCastTargets::Read(), Creature::SaveToDB(), and SpellDestination::SpellDestination().
GetTransport()
Transport * WorldObject::GetTransport () const inline
{ return m_transport; }
References m_transport.
Referenced by _IsWithinDist(), Player::_SaveCharacter(), MotionTransport::AddPassenger(), StaticTransport::AddPassenger(), Unit::BuildMovementPacket(), Object::BuildMovementUpdate(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::CanAIAttack(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::CanAIAttack(), npc_igb_ship_crew::npc_igb_ship_crewAI::CanAIAttack(), npc_gunship_boarding_addAI::CanAIAttack(), npc_gunship_gunner::npc_gunship_gunnerAI::CanAIAttack(), DynamicObject::CleanupsBeforeDelete(), GameObject::CleanupsBeforeDelete(), Unit::CleanupsBeforeDelete(), npc_gunship::npc_gunshipAI::DamageTaken(), DelayedMovementEvent::Execute(), ResetEncounterEvent::Execute(), npc_gunship::GetAI(), Unit::GetDirectTransport(), Creature::GetRespawnPosition(), GetTransGUID(), Unit::GetTransGUID(), GameObject::GetWorldRotation(), WorldSession::HandleForceSpeedChangeAck(), misc_commandscript::HandleGPSCommand(), WorldSession::HandleMoverRelocation(), WorldSession::HandleMoveWorldportAck(), npc_commandscript::HandleNpcAddCommand(), WorldSession::HandlePlayerLoginFromDB(), Unit::isInAccessiblePlaceFor(), npc_gunship::npc_gunshipAI::JustDied(), Player::KillPlayer(), npc_gunship_boarding_addAI::MovementInform(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::npc_high_overlord_saurfang_igbAI(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::npc_muradin_bronzebeard_igbAI(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnCreatureCreate(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnUnitDeath(), item_petrov_cluster_bombs::OnUse(), IgbExplosionCheck::operator()(), BurningPitchFilterCheck::operator()(), IgbArtilleryCheck::operator()(), Player::ProcessTerrainStatusUpdate(), spell_igb_teleport_to_enemy_ship::RelocateTransportOffset(), Creature::RemoveFromWorld(), DynamicObject::RemoveFromWorld(), GameObject::RemoveFromWorld(), Vehicle::RemovePassenger(), Creature::SaveToDB(), Creature::SaveToDB(), spell_igb_gunship_fall_teleport::SelectTransport(), Map::SendInitSelf(), Map::SendInitTransports(), Map::SendRemoveTransports(), Unit::SetCharmedBy(), gunship_npc_AI::SetData(), Movement::MoveSplineInit::SetFacing(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::sGossipSelect(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::sGossipSelect(), WaypointMovementGenerator< Creature >::StartMove(), Map::SummonCreature(), Player::TeleportTo(), Creature::Update(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::UpdateAI(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::UpdateAI(), and UpdateAllowedPositionZ().
GetTransSeat()
int8 WorldObject::GetTransSeat () const inline
{ return m_movementInfo.transport.seat; }
References m_movementInfo, MovementInfo::TransportInfo::seat, and MovementInfo::transport.
Referenced by Unit::_EnterVehicle(), Unit::BuildMovementPacket(), Unit::ChangeSeat(), Movement::MoveSplineInit::Launch(), and Movement::MoveSplineInit::Stop().
GetTransTime()
uint32 WorldObject::GetTransTime () const inline
{ return m_movementInfo.transport.time; }
References m_movementInfo, MovementInfo::TransportInfo::time, and MovementInfo::transport.
Referenced by Unit::BuildMovementPacket().
GetVisibilityOverrideDistance()
float WorldObject::GetVisibilityOverrideDistance () const
{
    ASSERT(_visibilityDistanceOverrideType < VisibilityDistanceType::Max);
    return VisibilityDistances[AsUnderlyingType(_visibilityDistanceOverrideType)];
}
References _visibilityDistanceOverrideType, ASSERT, AsUnderlyingType(), Max, and VisibilityDistances.
Referenced by GetSightRange(), and GetVisibilityRange().
GetVisibilityOverrideType()
VisibilityDistanceType WorldObject::GetVisibilityOverrideType () const inline
{ return _visibilityDistanceOverrideType; }
References _visibilityDistanceOverrideType.
Referenced by Player::IsWorldObjectOutOfSightRange(), and SetVisibilityDistanceOverride().
GetVisibilityRange()
float WorldObject::GetVisibilityRange () const
{
    if (IsCreature() && IsVisibilityOverridden())
        return GetVisibilityOverrideDistance();
    else if (IsGameObject())
    {
        if (IsInWintergrasp())
            return VISIBILITY_DIST_WINTERGRASP;
        else if (IsVisibilityOverridden())
            return GetVisibilityOverrideDistance();
        else
            return GetMap()->GetVisibilityRange();
    }
    else
        return IsInWintergrasp() ? VISIBILITY_DIST_WINTERGRASP : GetMap()->GetVisibilityRange();
}
References GetMap(), GetVisibilityOverrideDistance(), Map::GetVisibilityRange(), Object::IsCreature(), Object::IsGameObject(), IsInWintergrasp(), IsVisibilityOverridden(), and VISIBILITY_DIST_WINTERGRASP.
Referenced by PetAI::_needToStop(), Creature::CanCreatureAttack(), Spell::CheckCast(), Spell::CheckSpellFocus(), Spell::EffectForceDeselect(), Spell::EffectSanctuary(), debug_commandscript::HandleDebugVisibilityDataCommand(), AuraEffect::HandleFeignDeath(), Player::SendMessageToSet(), Player::TeleportTo(), Pet::Update(), Creature::Update(), Player::Update(), go_midsummer_music::go_midsummer_musicAI::UpdateAI(), and UpdateObjectVisibility().
GetVoidClosePoint()
void WorldObject::GetVoidClosePoint (float & x, float & y, float & z, float size, float distance2d = 0, float relAngle = 0, float controlZ = 0) const
{
    // angle calculated from current orientation
    GetNearPoint(nullptr, x, y, z, size, distance2d, GetOrientation() + relAngle, controlZ);
}
References GetNearPoint(), and Position::GetOrientation().
GetZoneAndAreaId()
void WorldObject::GetZoneAndAreaId (uint32 & zoneid, uint32 & areaid) const
{
    if (_updatePositionData)
        const_cast<WorldObject*>(this)->UpdatePositionData();
    zoneid = _zoneId;
    areaid = _areaId;
}
References _areaId, _updatePositionData, _zoneId, and UpdatePositionData().
Referenced by ArenaSeasonMgr::BroadcastUpdatedWorldState(), Spell::CheckCast(), Graveyard::GetClosestGraveyard(), GameObject::GetFishLoot(), Aura::HandleAuraSpecificMods(), WorldSession::HandleMoveTeleportAck(), WorldSession::HandleMoveWorldportAck(), WorldSession::HandlePlayerLoginToCharInWorld(), AchievementCriteriaData::Meets(), Player::ResurrectPlayer(), Player::SendInitialPacketsAfterAddToMap(), Player::SendQuestUpdate(), Player::Update(), Player::UpdatePosition(), and GameObject::Use().
GetZoneId()
uint32 WorldObject::GetZoneId () const
{
    if (_updatePositionData)
        const_cast<WorldObject*>(this)->UpdatePositionData();
    return _zoneId;
}
References _updatePositionData, _zoneId, and UpdatePositionData().
Referenced by Player::_LoadInventory(), Player::_SaveCharacter(), Player::AddQuest(), Vehicle::ApplyAllImmunities(), Map::ApplyDynamicModeRespawnScaling(), WorldSession::BuildPartyMemberStatsChangedPacket(), npc_herald_of_the_lich_king::ChangeZoneEventStatus(), Spell::CheckCast(), spell_gen_weapon_coating_enchant::CheckProc(), Player::CompleteQuest(), ScriptedAI::DoPlayMusic(), Spell::EffectSummonPlayer(), Spell::EffectSummonRaFFriend(), Acore::XP::Gain(), SocialMgr::GetFriendInfo(), Player::GetOutdoorPvP(), Player::GiveXP(), go_bells::go_bellsAI::go_bellsAI(), WorldSession::HandleAreaSpiritHealerQueryOpcode(), WorldSession::HandleAreaSpiritHealerQueueOpcode(), AuraEffect::HandleAuraDummy(), WorldSession::HandleBfEntryInviteResponse(), misc_commandscript::HandleChangeWeather(), debug_commandscript::HandleDebugVisibilityDataCommand(), debug_commandscript::HandleDebugZoneStatsCommand(), spell_midsummer_summon_ahune_lieutenant::HandleDummy(), go_commandscript::HandleGoZoneXYCommand(), WorldSession::HandleHearthAndResurrect(), misc_commandscript::HandleLinkGraveCommand(), WorldSession::HandleMoveTeleportAck(), misc_commandscript::HandleNearGraveCommand(), spell_wintergrasp_hide_small_elementals_aura::HandlePeriodicDummy(), WorldSession::HandlePlayerLoginFromDB(), WorldSession::HandleRequestPartyMemberStatsOpcode(), misc_commandscript::HandleSummonCommand(), Player::IncompleteQuest(), go_firework_show::InitShow(), SpellArea::IsFitToRequirements(), Player::IsWorldObjectOutOfSightRange(), boss_azuregos::boss_azuregosAI::JustDied(), npc_necropolis_health::JustDied(), npc_pallid_horror::JustDied(), Unit::Kill(), Player::KilledPlayerCredit(), LogCommandUsage(), WorldSession::LogoutPlayer(), npc_mageguard_dalaran::npc_mageguard_dalaranAI::MoveInLineOfSight(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnPlayerAreaUpdate(), item_petrov_cluster_bombs::OnUse(), item_only_for_flight::OnUse(), spell_fire_festival_fortitude::PrepareSpellScript(), SmartScript::ProcessAction(), Player::RemoveActiveQuest(), Player::RemovedInsignia(), Map::RemovePlayerFromMap(), Player::RepopAtGraveyard(), boss_azuregos::boss_azuregosAI::Reset(), Player::RewardQuest(), npc_minigob_manabonk::SelectTargetInDalaran(), CreatureTextMgr::SendChatPacket(), CreatureTextMgr::SendNonChatPacket(), Acore::VisibleNotifier::SendToSelf(), Map::SendZoneMessage(), Guild::Member::SetStats(), boss_akilzon::SetWeather(), SetZoneScript(), npc_midsummer_bonfire::UpdateBonfireBlessingBuffs(), npc_herald_of_the_lich_king::UpdateWeather(), and npc_pallid_horror::UpdateWeather().
GetZoneScript()
ZoneScript * WorldObject::GetZoneScript () const inline
{ return m_zoneScript; }
References m_zoneScript.
Referenced by CreatureAI::_EnterEvadeMode(), Creature::AddToWorld(), Creature::CreateFromProto(), Spell::EffectSendEvent(), Creature::RemoveFromWorld(), and Unit::setDeathState().
HasAllowedLooter()
bool WorldObject::HasAllowedLooter (ObjectGuid guid) const
{
    if (_allowedLooters.empty())
    {
        return true;
    }
    return _allowedLooters.find(guid) != _allowedLooters.end();
}
References _allowedLooters.
Referenced by Player::IsAtLootRewardDistance(), and GameObject::IsLootAllowedFor().
InSamePhase() [1/2]
bool WorldObject::InSamePhase (uint32 phasemask) const inline
{ return m_useCombinedPhases ? GetPhaseMask() & phasemask : GetPhaseMask() == phasemask; }
References GetPhaseMask(), and m_useCombinedPhases.
InSamePhase() [2/2]
bool WorldObject::InSamePhase (WorldObject const * obj) const inline
{ return InSamePhase(obj->GetPhaseMask()); }
References GetPhaseMask(), and InSamePhase().
Referenced by Unit::Attack(), CanNeverSee(), boss_halion::boss_halionAI::DamageTaken(), boss_twilight_halion::boss_twilight_halionAI::DamageTaken(), InSamePhase(), IsValidCombatTarget(), ThreatCalcHelper::isValidProcess(), Unit::IsWithinBoundaryRadius(), Unit::IsWithinCombatRange(), GameObject::IsWithinDistInMap(), IsWithinDistInMap(), Unit::IsWithinMeleeRange(), Unit::IsWithinRange(), Acore::NearestCreatureEntryWithLiveStateInObjectRangeCheck::operator()(), Acore::AllWorldObjectsInRange::operator()(), Unit::SetPhaseMask(), Acore::MessageDistDeliverer::Visit(), Acore::MessageDistDelivererToHostile::Visit(), Acore::MessageDistDeliverer::Visit(), Acore::MessageDistDelivererToHostile::Visit(), Acore::MessageDistDeliverer::Visit(), and Acore::MessageDistDelivererToHostile::Visit().
isActiveObject()
bool WorldObject::isActiveObject () const inline
{ return m_isActive; }
References m_isActive.
Referenced by npc_warden_mellichar::npc_warden_mellicharAI::DamageTaken(), HostileRefMgr::deleteReferencesOutOfRange(), npc_grand_magister_rommath::npc_grand_magister_rommathAI::DoAction(), npc_crok_scourgebane::npc_crok_scourgebaneAI::DoAction(), boss_illidari_council::DoAction(), npc_bh_thalorien_dawnseeker::npc_bh_thalorien_dawnseekerAI::EnterEvadeMode(), GetGridActivationRange(), GetSightRange(), IsUpdateNeeded(), npc_bh_thalorien_dawnseeker::npc_bh_thalorien_dawnseekerAI::SetData(), npc_bh_thalorien_dawnseeker::npc_bh_thalorien_dawnseekerAI::SummonedCreatureDespawn(), npc_bh_thalorien_dawnseeker::npc_bh_thalorien_dawnseekerAI::UpdateAI(), npc_grand_magister_rommath::npc_grand_magister_rommathAI::UpdateAI(), npc_hor_lich_king::npc_hor_lich_kingAI::UpdateAI(), npc_crok_scourgebane::npc_crok_scourgebaneAI::UpdateAI(), boss_sister_svalna::boss_sister_svalnaAI::UpdateAI(), and boss_illidari_council::UpdateAI().
IsAlwaysDetectableFor()
virtual bool WorldObject::IsAlwaysDetectableFor (WorldObject const *) const inline protected virtual
Reimplemented in Creature, Player, and Unit.
{ return false; }
Referenced by CanDetect(), and Unit::IsAlwaysDetectableFor().
IsAlwaysVisibleFor()
virtual bool WorldObject::IsAlwaysVisibleFor (WorldObject const *) const inline protected virtual
Reimplemented in GameObject, and Unit.
{ return false; }
Referenced by CanSeeOrDetect(), GameObject::IsAlwaysVisibleFor(), and Unit::IsAlwaysVisibleFor().
IsFarVisible()
bool WorldObject::IsFarVisible () const inline
{ return _visibilityDistanceOverrideType == VisibilityDistanceType::Large || _visibilityDistanceOverrideType == VisibilityDistanceType::Gigantic; }
References _visibilityDistanceOverrideType, Gigantic, and Large.
Referenced by Map::AddToGrid(), Map::AddToGrid(), AddToMapVisibilityOverrideContainers(), Map::MoveAllCreaturesInMoveList(), Map::MoveAllGameObjectsInMoveList(), and RemoveFromMapVisibilityOverrideContainers().
isInBack()
bool WorldObject::isInBack (WorldObject const * target, float arc = M_PI) const
{
    return !HasInArc(2 * M_PI - arc, target);
}
References Position::HasInArc().
Referenced by Acore::WorldObjectSpellConeTargetCheck::operator()().
IsInBetween()
bool WorldObject::IsInBetween (WorldObject const * obj1, WorldObject const * obj2, float size = 0) const
{
    if (!obj1 || !obj2)
        return false;
    if (!size)
        size = GetObjectSize() / 2;
    float pdist = obj1->GetExactDist2dSq(obj2) + size / 2.0f;
    if (GetExactDist2dSq(obj1) >= pdist || GetExactDist2dSq(obj2) >= pdist)
        return false;
    if (G3D::fuzzyEq(obj1->GetPositionX(), obj2->GetPositionX()))
        return GetPositionX() >= obj1->GetPositionX() - size && GetPositionX() <= obj1->GetPositionX() + size;
    float A = (obj2->GetPositionY() - obj1->GetPositionY()) / (obj2->GetPositionX() - obj1->GetPositionX());
    float B = -1;
    float C = obj1->GetPositionY() - A * obj1->GetPositionX();
    float dist = std::fabs(A * GetPositionX() + B * GetPositionY() + C) / std::sqrt(A * A + B * B);
    return dist <= size;
}
References Position::GetExactDist2dSq(), GetObjectSize(), Position::GetPositionX(), and Position::GetPositionY().
Referenced by TwilightCutterSelector::operator()().
isInFront()
bool WorldObject::isInFront (WorldObject const * target, float arc = M_PI) const
{
    return HasInArc(arc, target);
}
References Position::HasInArc().
Referenced by spell_dk_death_coil::CheckCast(), spell_pal_holy_shock::CheckCast(), spell_pri_penance::CheckCast(), spell_gargolmar_retalliation::CheckProc(), spell_warr_retaliation::CheckProc(), boss_reliquary_of_souls::boss_reliquary_of_soulsAI::MoveInLineOfSight(), and Acore::WorldObjectSpellConeTargetCheck::operator()().
IsInMap()
bool WorldObject::IsInMap (WorldObject const * obj) const
{
    if (obj)
    {
        return IsInWorld() && obj->IsInWorld() && (FindMap() == obj->FindMap());
    }
    return false;
}
References FindMap(), and Object::IsInWorld().
Referenced by Unit::Attack(), Creature::CanCreatureAttack(), npc_unkor_the_ruthless::npc_unkor_the_ruthlessAI::DamageTaken(), SmartAI::EndPath(), ReflectEvent::Execute(), Unit::GetPartyMembers(), Player::GetsRecruitAFriendBonus(), WorldSession::HandlePushQuestToParty(), WorldSession::HandleReclaimCorpseOpcode(), Unit::HandleSpellClick(), Player::IsAtGroupRewardDistance(), SmartAI::IsEscortInvokerInRange(), IsSelfOrInSameMap(), ThreatCalcHelper::isValidProcess(), Unit::IsWithinBoundaryRadius(), Unit::IsWithinCombatRange(), GameObject::IsWithinDistInMap(), IsWithinDistInMap(), IsWithinLOSInMap(), Unit::IsWithinMeleeRange(), Unit::IsWithinRange(), Unit::Kill(), MysticBuffetTargetFilter::operator()(), KillRewarder::Reward(), Totem::UnSummon(), PetAI::UpdateAllies(), and Group::UpdatePlayerOutOfRange().
IsInRange()
bool WorldObject::IsInRange (WorldObject const * obj, float minRange, float maxRange, bool is3D = true) const
{
    float dx = GetPositionX() - obj->GetPositionX();
    float dy = GetPositionY() - obj->GetPositionY();
    float distsq = dx * dx + dy * dy;
    if (is3D)
    {
        float dz = GetPositionZ() - obj->GetPositionZ();
        distsq += dz * dz;
    }
    float sizefactor = GetObjectSize() + obj->GetObjectSize();
    // check only for real range
    if (minRange > 0.0f)
    {
        float mindist = minRange + sizefactor;
        if (distsq < mindist * mindist)
            return false;
    }
    float maxdist = maxRange + sizefactor;
    return distsq < maxdist * maxdist;
}
References GetObjectSize(), Position::GetPositionX(), Position::GetPositionY(), and Position::GetPositionZ().
Referenced by SmartScript::GetTargets(), npc_anachronos_the_ancient::npc_anachronos_the_ancientAI::HandleAnimation(), RangeSelector::operator()(), SmartScript::ProcessEvent(), npc_varian_wrynn::npc_varian_wrynnAI::UpdateAI(), npc_thrall_bfu::npc_thrall_bfuAI::UpdateAI(), boss_grand_champion::boss_grand_championAI::UpdateAI(), and boss_gathios_the_shatterer::UpdateAI().
IsInRange2d()
bool WorldObject::IsInRange2d (float x, float y, float minRange, float maxRange) const
{
    float dx = GetPositionX() - x;
    float dy = GetPositionY() - y;
    float distsq = dx * dx + dy * dy;
    float sizefactor = GetObjectSize();
    // check only for real range
    if (minRange > 0.0f)
    {
        float mindist = minRange + sizefactor;
        if (distsq < mindist * mindist)
            return false;
    }
    float maxdist = maxRange + sizefactor;
    return distsq < maxdist * maxdist;
}
References GetObjectSize(), Position::GetPositionX(), and Position::GetPositionY().
IsInRange3d()
bool WorldObject::IsInRange3d (float x, float y, float z, float minRange, float maxRange) const
{
    float dx = GetPositionX() - x;
    float dy = GetPositionY() - y;
    float dz = GetPositionZ() - z;
    float distsq = dx * dx + dy * dy + dz * dz;
    float sizefactor = GetObjectSize();
    // check only for real range
    if (minRange > 0.0f)
    {
        float mindist = minRange + sizefactor;
        if (distsq < mindist * mindist)
            return false;
    }
    float maxdist = maxRange + sizefactor;
    return distsq < maxdist * maxdist;
}
References GetObjectSize(), Position::GetPositionX(), Position::GetPositionY(), and Position::GetPositionZ().
IsInvisibleDueToDespawn()
virtual bool WorldObject::IsInvisibleDueToDespawn () const inline protected virtual
Reimplemented in Creature, and GameObject.
{ return false; }
Referenced by CanSeeOrDetect(), Creature::IsInvisibleDueToDespawn(), and GameObject::IsInvisibleDueToDespawn().
IsInWintergrasp()
bool WorldObject::IsInWintergrasp () const inline
    {
        return GetMapId() == MAP_NORTHREND && GetPositionX() > 3733.33331f && GetPositionX() < 5866.66663f && GetPositionY() > 1599.99999f && GetPositionY() < 4799.99997f;
    }
References WorldLocation::GetMapId(), Position::GetPositionX(), Position::GetPositionY(), and MAP_NORTHREND.
Referenced by GetGridActivationRange(), GetSightRange(), and GetVisibilityRange().
isNeedNotify()
bool WorldObject::isNeedNotify (uint16 f) const inline
{ return m_notifyflags & f;}
References m_notifyflags.
Referenced by GridObjectLoader::LoadCreatures(), Acore::AIRelocationNotifier::Visit(), and Acore::CreatureRelocationNotifier::Visit().
IsNeverVisible()
virtual bool WorldObject::IsNeverVisible () const inline protected virtual
Reimplemented in GameObject, and Player.
{ return !IsInWorld(); }
References Object::IsInWorld().
Referenced by CanNeverSee(), GameObject::IsNeverVisible(), and Player::IsNeverVisible().
IsOutdoors()
bool WorldObject::IsOutdoors () const
{
    if (_updatePositionData)
        const_cast<WorldObject*>(this)->UpdatePositionData();
    return _outdoors;
}
References _outdoors, _updatePositionData, and UpdatePositionData().
Referenced by Player::CheckAreaExploreAndOutdoor(), Spell::CheckCast(), and misc_commandscript::HandleGPSCommand().
IsSelfOrInSameMap()
bool WorldObject::IsSelfOrInSameMap (WorldObject const * obj) const
{
    if (this == obj)
    {
        return true;
    }
    return IsInMap(obj);
}
References IsInMap().
Referenced by Aura::UpdateTargetMap().
IsUpdateNeeded()
bool WorldObject::IsUpdateNeeded () virtual
Reimplemented in Creature, and GameObject.
{
    if (isActiveObject())
        return true;
    return false;
}
References isActiveObject().
Referenced by Creature::IsUpdateNeeded(), GameObject::IsUpdateNeeded(), and Map::UpdateNonPlayerObjects().
IsVisibilityOverridden()
bool WorldObject::IsVisibilityOverridden () const inline
{ return _visibilityDistanceOverrideType > VisibilityDistanceType::Normal; }
References _visibilityDistanceOverrideType, and Normal.
Referenced by AddToMapVisibilityOverrideContainers(), GetSightRange(), GetVisibilityRange(), and RemoveFromMapVisibilityOverrideContainers().
IsWithinDist()
bool WorldObject::IsWithinDist (WorldObject const * obj, float dist2compare, bool is3D = true, bool incOwnRadius = true, bool incTargetRadius = true) const
{
    return obj && _IsWithinDist(obj, dist2compare, is3D, incOwnRadius, incTargetRadius);
}
References _IsWithinDist().
Referenced by Unit::CalcAbsorbResist(), Creature::CanCreatureAttack(), CanSeeOrDetect(), npc_cork_gizelton::npc_cork_gizeltonAI::CheckPlayer(), npc_maiev_illidan::DoAction(), WorldSession::HandleReclaimCorpseOpcode(), boss_attumen::IsSummonedBy(), Player::IsWorldObjectOutOfSightRange(), npc_yor::JustEngagedWith(), boss_twinemperorsAI::JustEngagedWith(), CreatureAI::MoveInLineOfSight(), npc_brew_bubble::MoveInLineOfSight(), npc_a_special_surprise::npc_a_special_surpriseAI::MoveInLineOfSight(), npc_amanishi_lookout::MoveInLineOfSight(), npc_eagle_trash_aggro_trigger::MoveInLineOfSight(), npc_mageguard_dalaran::npc_mageguard_dalaranAI::MoveInLineOfSight(), Acore::NearestCreatureEntryWithLiveStateInObjectRangeCheck::operator()(), Acore::AllGameObjectsWithEntryInRange::operator()(), Acore::AllGameObjectsMatchingOneEntryInRange::operator()(), Acore::PlayerAtMinimumRangeAway::operator()(), Acore::AllCreaturesOfEntryInRange::operator()(), Acore::AllCreaturesMatchingOneEntryInRange::operator()(), FrostwingVrykulSearcher::operator()(), Acore::AllWorldObjectsInRange::operator()(), Spell::SearchChainTargets(), dragonmaw_race_npc::StartRace(), npc_daphne_stilwell::npc_daphne_stilwellAI::Update(), npc_unworthy_initiate::npc_unworthy_initiateAI::UpdateAI(), npc_ichor_globule::npc_ichor_globuleAI::UpdateAI(), and Group::UpdatePlayerOutOfRange().
IsWithinDist2d() [1/2]
bool WorldObject::IsWithinDist2d (const Position * pos, float dist) const
{
    return IsInDist2d(pos, dist + GetObjectSize());
}
References GetObjectSize(), and Position::IsInDist2d().
IsWithinDist2d() [2/2]
bool WorldObject::IsWithinDist2d (float x, float y, float dist) const
{
    return IsInDist2d(x, y, dist + GetObjectSize());
}
References GetObjectSize(), and Position::IsInDist2d().
Referenced by spell_vehicle_throw_passenger::HandleScript(), boss_alyson_antille::JustEngagedWith(), npc_vekniss_stinger::JustEngagedWith(), boss_eye_of_cthun::MoveInLineOfSight(), npc_shattered_hand_scout::MoveInLineOfSight(), BattlefieldWG::OnCreatureCreate(), npc_artorius::npc_artoriusAI::UpdateAI(), npc_simone::npc_simoneAI::UpdateAI(), npc_nelson::npc_nelsonAI::UpdateAI(), and npc_franklin::npc_franklinAI::UpdateAI().
IsWithinDist3d() [1/2]
bool WorldObject::IsWithinDist3d (const Position * pos, float dist) const
{
    return IsInDist(pos, dist + GetObjectSize());
}
References GetObjectSize(), and Position::IsInDist().
IsWithinDist3d() [2/2]
bool WorldObject::IsWithinDist3d (float x, float y, float z, float dist) const
{
    return IsInDist(x, y, z, dist + GetObjectSize());
}
References GetObjectSize(), and Position::IsInDist().
Referenced by Spell::CheckRange(), spell_grobbulus_poison::FilterTargets(), GameObject::IsInRange(), boss_the_black_stalker::JustEngagedWith(), Acore::WorldObjectSpellAreaTargetCheck::operator()(), Player::TeleportTo(), boss_grobbulus::boss_grobbulusAI::UpdateAI(), and npc_power_spark::npc_power_sparkAI::UpdateAI().
IsWithinDistInMap()
bool WorldObject::IsWithinDistInMap (WorldObject const * obj, float dist2compare, bool is3D = true, bool incOwnRadius = true, bool incTargetRadius = true) const
{
    return obj && IsInMap(obj) && InSamePhase(obj) && _IsWithinDist(obj, dist2compare, is3D, incOwnRadius, incTargetRadius);
}
References _IsWithinDist(), InSamePhase(), and IsInMap().
Referenced by npc_escortAI::AssistPlayerInCombatAgainst(), FollowerAI::AssistPlayerInCombatAgainst(), SmartAI::AssistPlayerInCombatAgainst(), Creature::CanStartAttack(), Player::CheckDuelDistance(), npc_anachronos_quest_trigger::npc_anachronos_quest_triggerAI::CheckEventFail(), npc_lord_illidan_stormrage::npc_lord_illidan_stormrageAI::CheckEventFail(), spell_sha_fire_nova::CheckFireTotem(), WorldSession::DoLootRelease(), CreatureAI::DoZoneInCombat(), boss_halazzi::EnterPhase(), BattlegroundEY::EventPlayerClickedOnFlag(), BattlegroundWS::EventPlayerClickedOnFlag(), BattlegroundAB::EventPlayerClickedOnFlag(), FollowerAI::GetLeaderForFollower(), Player::GetNextRandomRaidMember(), Unit::GetNextRandomRaidMemberOrPet(), Player::GetNPCIfCanInteractWith(), Unit::HandleAuraRaidProcFromChargeWithValue(), WorldSession::HandleAutostoreLootItemOpcode(), WorldSession::HandleInitiateTradeOpcode(), WorldSession::HandleLootMoneyOpcode(), AuraEffect::HandleModPossessPet(), Unit::isInBackInMap(), Unit::isInFrontInMap(), npc_escortAI::IsPlayerOrGroupInRange(), boss_gothik::boss_gothikAI::JustSummoned(), npc_dkc1_gothik::npc_dkc1_gothikAI::MoveInLineOfSight(), boss_muru::MoveInLineOfSight(), boss_aeonus::MoveInLineOfSight(), boss_chrono_lord_deja::MoveInLineOfSight(), boss_temporus::MoveInLineOfSight(), npc_medivh_bm::MoveInLineOfSight(), npc_general_andorov::MoveInLineOfSight(), npc_ouro_spawner::MoveInLineOfSight(), npc_draenei_survivor::npc_draenei_survivorAI::MoveInLineOfSight(), npc_kerlonian::npc_kerlonianAI::MoveInLineOfSight(), npc_aged_dying_ancient_kodo::npc_aged_dying_ancient_kodoAI::MoveInLineOfSight(), npc_custodian_of_time::npc_custodian_of_timeAI::MoveInLineOfSight(), npc_tooga::npc_toogaAI::MoveInLineOfSight(), npc_twiggy_flathead::npc_twiggy_flatheadAI::MoveInLineOfSight(), npc_ringo::npc_ringoAI::MoveInLineOfSight(), npc_hadronox_crusherPackAI::MoveInLineOfSight(), boss_gluth::boss_gluthAI::MoveInLineOfSight(), boss_loken::MoveInLineOfSight(), npc_khunok_the_behemoth::npc_khunok_the_behemothAI::MoveInLineOfSight(), npc_jenny::MoveInLineOfSight(), boss_exarch_maladaar::MoveInLineOfSight(), boss_nexusprince_shaffar::MoveInLineOfSight(), boss_warlord_kalithresh::MoveInLineOfSight(), npc_daranelle::npc_daranelleAI::MoveInLineOfSight(), npc_ancestral_wolf::npc_ancestral_wolfAI::MoveInLineOfSight(), npc_pet_hunter_snake_trap::MoveInLineOfSight(), npc_air_force_bots::npc_air_force_botsAI::MoveInLineOfSight(), boss_leotheras_the_blind::MoveToTargetIfOutOfRange(), Acore::AnyDeadUnitObjectInRangeCheck::operator()(), Acore::AnyDeadUnitObjectInRangeCheck::operator()(), Acore::CallOfHelpCreatureInRangeDo::operator()(), Acore::AnyAssistCreatureInRangeCheck::operator()(), Acore::NearestAssistCreatureInCreatureRangeCheck::operator()(), Acore::NearestGameObjectFishingHole::operator()(), Acore::NearestGameObjectCheck::operator()(), Acore::NearestGameObjectEntryInObjectRangeCheck::operator()(), Acore::NearestGameObjectTypeInObjectRangeCheck::operator()(), Acore::AnyDeadUnitObjectInRangeCheck::operator()(), Acore::AnyPlayerInObjectRangeCheck::operator()(), Acore::NearestPlayerInObjectRangeCheck::operator()(), Acore::AnyPlayerInObjectRangeCheck::operator()(), Acore::MostHPMissingInRange::operator()(), Acore::MostHPPercentMissingInRange::operator()(), Acore::FriendlyCCedInRange::operator()(), Acore::FriendlyMissingBuffInRange::operator()(), Acore::AnyUnfriendlyUnitInObjectRangeCheck::operator()(), Acore::AnyUnfriendlyNoTotemUnitInObjectRangeCheck::operator()(), Acore::NearestAttackableNoTotemUnitInObjectRangeCheck::operator()(), Acore::AnyFriendlyUnitInObjectRangeCheck::operator()(), Acore::AnyFriendlyNotSelfUnitInObjectRangeCheck::operator()(), Acore::AnyGroupedUnitInObjectRangeCheck::operator()(), Acore::AnyUnitInObjectRangeCheck::operator()(), Acore::NearestAttackableUnitInObjectRangeCheck::operator()(), Acore::AnyAoETargetUnitInObjectRangeCheck::operator()(), Acore::AnyAttackableUnitExceptForOriginalCasterInObjectRangeCheck::operator()(), Acore::NearestHostileUnitCheck::operator()(), Acore::NearestHostileUnitInAttackDistanceCheck::operator()(), Acore::MostHPMissingGroupInRange::operator()(), Acore::AllDeadCreaturesInRange::operator()(), Acore::AnyUnfriendlyAttackableVisibleUnitInObjectRangeCheck::operator()(), SmartScript::ProcessEvent(), npc_lake_frog::npc_lake_frogAI::ReceiveEmote(), npc_dancing_flames::npc_dancing_flamesAI::ReceiveEmote(), Map::ScriptsProcess(), ScriptedAI::SelectSpell(), ScriptedAI::SelectTargetFromPlayerList(), Player::SendLoot(), npc_corrupted_totem::SetAura(), Pet::Update(), Creature::Update(), Player::Update(), TotemAI::UpdateAI(), npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::UpdateAI(), boss_four_horsemen::boss_four_horsemenAI::UpdateAI(), FollowerAI::UpdateAI(), Spell::UpdateChanneledTargetList(), and Player::UpdatePosition().
IsWithinLOS()
bool WorldObject::IsWithinLOS (float x, float y, float z, VMAP::ModelIgnoreFlags ignoreFlags = VMAP::ModelIgnoreFlags::Nothing, LineOfSightChecks checks = LINEOFSIGHT_ALL_CHECKS) const
{
    if (IsInWorld())
    {
        oz += GetCollisionHeight();
        float x, y, z;
        if (IsPlayer())
        {
            GetPosition(x, y, z);
            z += GetCollisionHeight();
        }
        else
        {
            GetHitSpherePointFor({ ox, oy, oz }, x, y, z);
        }
        return GetMap()->isInLineOfSight(x, y, z, ox, oy, oz, GetPhaseMask(), checks, ignoreFlags);
    }
    return true;
}
References GetCollisionHeight(), GetHitSpherePointFor(), GetMap(), GetPhaseMask(), Position::GetPosition(), Map::isInLineOfSight(), Object::IsInWorld(), and Object::IsPlayer().
Referenced by RandomMovementGenerator< T >::_setRandomLocation(), Spell::CheckCast(), Spell::CheckEffectTarget(), boss_ick::boss_ickAI::DamageTaken(), Spell::EffectChargeDest(), spell_dru_starfall_dummy::FilterTargets(), GetChargeContactPoint(), GetClosePoint(), GetContactPoint(), GetNearPoint(), Unit::GetRandomContactPoint(), spell_marrowgar_coldflame_bonestorm::HandleScriptEffect(), spell_marrowgar_coldflame::HandleScriptEffect(), boss_vem::JustEngagedWith(), npc_dancing_flames::npc_dancing_flamesAI::ReceiveEmote(), Spell::SelectImplicitCasterDestTargets(), npc_coldflame::npc_coldflameAI::UpdateAI(), boss_freya::boss_freyaAI::UpdateAI(), and boss_mimiron::boss_mimironAI::UpdateAI().
IsWithinLOSInMap()
bool WorldObject::IsWithinLOSInMap (WorldObject const * obj, VMAP::ModelIgnoreFlags ignoreFlags = VMAP::ModelIgnoreFlags::Nothing, LineOfSightChecks checks = LINEOFSIGHT_ALL_CHECKS, Optional< float > collisionHeight = { }, Optional< float > combatReach = { }) const
{
   if (!IsInMap(obj))
        return false;
    float ox, oy, oz;
    if (obj->IsPlayer())
    {
        obj->GetPosition(ox, oy, oz);
        oz += obj->GetCollisionHeight();
    }
    else
        obj->GetHitSpherePointFor({ GetPositionX(), GetPositionY(), GetPositionZ() + (collisionHeight ? *collisionHeight : GetCollisionHeight()) }, ox, oy, oz);
    float x, y, z;
    if (IsPlayer())
    {
        GetPosition(x, y, z);
        z += GetCollisionHeight();
    }
    else
        GetHitSpherePointFor({ obj->GetPositionX(), obj->GetPositionY(), obj->GetPositionZ() + obj->GetCollisionHeight() }, x, y, z, collisionHeight, combatReach);
    return GetMap()->isInLineOfSight(x, y, z, ox, oy, oz, GetPhaseMask(), checks, ignoreFlags);
}
References GetCollisionHeight(), GetHitSpherePointFor(), GetMap(), GetPhaseMask(), Position::GetPosition(), Position::GetPosition(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Map::isInLineOfSight(), IsInMap(), and Object::IsPlayer().
Referenced by at_hol_hall_of_watchers::_OnTrigger(), npc_escortAI::AssistPlayerInCombatAgainst(), FollowerAI::AssistPlayerInCombatAgainst(), SmartAI::AssistPlayerInCombatAgainst(), Unit::AttackerStateUpdate(), boss_swamplord_muselek::CanShootVictim(), Creature::CanStartAttack(), Spell::CheckCast(), Spell::CheckEffectTarget(), spell_hun_masters_call::DoCheckCast(), DynObjAura::FillTargetMap(), npc_singularity::FindAndFollowTarget(), debug_commandscript::HandleDebugLoSCommand(), boss_halion::boss_halionAI::IsAnyPlayerValid(), npc_amanishi_lookout::MoveInLineOfSight(), boss_eye_of_cthun::MoveInLineOfSight(), boss_reliquary_of_souls::boss_reliquary_of_soulsAI::MoveInLineOfSight(), Acore::CallOfHelpCreatureInRangeDo::operator()(), Acore::AnyAssistCreatureInRangeCheck::operator()(), Acore::NearestAssistCreatureInCreatureRangeCheck::operator()(), Acore::NearestAttackableNoTotemUnitInObjectRangeCheck::operator()(), NecroticPlagueTargetCheck::operator()(), RangeSelector::operator()(), ShadowTrapLKTargetSelector::operator()(), NonTankLKTargetSelector::operator()(), DefileTargetSelector::operator()(), MysticBuffetTargetFilter::operator()(), SmartScript::ProcessAction(), SmartScript::ProcessEvent(), Spell::SearchChainTargets(), Unit::SelectNearbyNoTotemTarget(), Unit::SelectNearbyTarget(), ScriptedAI::SelectTargetFromPlayerList(), CreatureAI::TriggerAlert(), Pet::Update(), boss_quartermaster_zigris::UpdateAI(), boss_mandokir::boss_mandokirAI::UpdateAI(), boss_sindragosa::boss_sindragosaAI::UpdateAI(), and boss_the_lich_king::boss_the_lich_kingAI::UpdateAI().
IsZoneWideVisible()
bool WorldObject::IsZoneWideVisible () const inline
{ return _visibilityDistanceOverrideType == VisibilityDistanceType::Infinite; }
References _visibilityDistanceOverrideType, and Infinite.
Referenced by AddToMapVisibilityOverrideContainers(), AddToWorld(), ProcessPositionDataChanged(), and RemoveFromMapVisibilityOverrideContainers().
MovePosition()
void WorldObject::MovePosition (Position & pos, float dist, float angle)
{
    angle += GetOrientation();
    float destx, desty, destz, ground, floor;
    destx = pos.m_positionX + dist * cos(angle);
    desty = pos.m_positionY + dist * std::sin(angle);
    // Prevent invalid coordinates here, position is unchanged
    if (!Acore::IsValidMapCoord(destx, desty))
    {
        LOG_FATAL("entities.object", "WorldObject::MovePosition invalid coordinates X: {} and Y: {} were passed!", destx, desty);
        return;
    }
    ground = GetMapHeight(destx, desty, MAX_HEIGHT);
    floor = GetMapHeight(destx, desty, pos.m_positionZ);
    destz = std::fabs(ground - pos.m_positionZ) <= std::fabs(floor - pos.m_positionZ) ? ground : floor;
    float step = dist / 10.0f;
    for (uint8 j = 0; j < 10; ++j)
    {
        // do not allow too big z changes
        if (std::fabs(pos.m_positionZ - destz) > 6.0f)
        {
            destx -= step * cos(angle);
            desty -= step * std::sin(angle);
            ground = GetMapHeight(destx, desty, MAX_HEIGHT);
            floor = GetMapHeight(destx, desty, pos.m_positionZ);
            destz = std::fabs(ground - pos.m_positionZ) <= std::fabs(floor - pos.m_positionZ) ? ground : floor;
        }
        // we have correct destz now
        else
        {
            pos.Relocate(destx, desty, destz);
            break;
        }
    }
    Acore::NormalizeMapCoord(pos.m_positionX);
    Acore::NormalizeMapCoord(pos.m_positionY);
    UpdateGroundPositionZ(pos.m_positionX, pos.m_positionY, pos.m_positionZ);
    pos.SetOrientation(GetOrientation());
}
References GetMapHeight(), Position::GetOrientation(), Acore::IsValidMapCoord(), LOG_FATAL, Position::m_positionX, Position::m_positionY, Position::m_positionZ, MAX_HEIGHT, Acore::NormalizeMapCoord(), Position::Relocate(), Position::SetOrientation(), and UpdateGroundPositionZ().
Referenced by GetNearPosition(), GetRandomNearPosition(), and Spell::SelectImplicitDestDestTargets().
MovePositionToFirstCollision()
void WorldObject::MovePositionToFirstCollision (Position & pos, float dist, float angle)
{
    angle += GetOrientation();
    float destx, desty, destz;
    destx = pos.m_positionX + dist * cos(angle);
    desty = pos.m_positionY + dist * std::sin(angle);
    destz = pos.m_positionZ;
    if (!GetMap()->CheckCollisionAndGetValidCoords(this, pos.m_positionX, pos.m_positionY, pos.m_positionZ, destx, desty, destz, false))
        return;
    pos.SetOrientation(GetOrientation());
    pos.Relocate(destx, desty, destz);
}
References GetMap(), Position::GetOrientation(), Position::m_positionX, Position::m_positionY, Position::m_positionZ, Position::Relocate(), and Position::SetOrientation().
Referenced by FollowMovementGenerator< T >::DoUpdate(), Spell::EffectStuck(), VehicleDespawnEvent::Execute(), GetFirstCollisionPosition(), GetFirstCollisionPosition(), GetFirstCollisionPosition(), spell_boss_magus_telestra_gravity_well::HandlePull(), MotionMaster::MoveKnockbackFrom(), Spell::SelectImplicitCasterDestTargets(), and Spell::SelectImplicitTargetDestTargets().
NotifyExecuted()
bool WorldObject::NotifyExecuted (uint16 f) const inline
{ return m_executed_notifies & f;}
References m_executed_notifies.
PlayDirectMusic()
void WorldObject::PlayDirectMusic (uint32 music_id, Player * target = nullptr)
{
    if (target)
        target->SendDirectMessage(WorldPackets::Misc::PlayMusic(music_id).Write());
    else
        SendMessageToSet(WorldPackets::Misc::PlayMusic(music_id).Write(), true);
}
References Player::SendDirectMessage(), and SendMessageToSet().
Referenced by debug_commandscript::HandleDebugPlayMusicCommand(), go_l70_etc_music::go_l70_etc_musicAI::UpdateAI(), go_brewfest_music::go_brewfest_musicAI::UpdateAI(), go_pirate_day_music::go_pirate_day_musicAI::UpdateAI(), go_darkmoon_faire_music::go_darkmoon_faire_musicAI::UpdateAI(), and go_midsummer_music::go_midsummer_musicAI::UpdateAI().
PlayDirectSound()
void WorldObject::PlayDirectSound (uint32 sound_id, Player * target = nullptr)
{
    if (target)
        target->SendDirectMessage(WorldPackets::Misc::Playsound(sound_id).Write());
    else
        SendMessageToSet(WorldPackets::Misc::Playsound(sound_id).Write(), true);
}
References Player::SendDirectMessage(), and SendMessageToSet().
Referenced by Player::CanAddQuest(), ScriptedAI::DoPlaySoundToSet(), Spell::EffectPlaySound(), AuraEffect::HandleAuraDummy(), debug_commandscript::HandleDebugPlaySoundCommand(), spell_kaelthas_kael_explodes::HandleScriptEffect(), boss_the_lich_king::boss_the_lich_kingAI::JustDied(), boss_palehoof::boss_palehoofAI::JustDied(), boss_kazrogal::JustDied(), boss_saviana_ragefire::boss_saviana_ragefireAI::JustDied(), spell_item_ashbringer::OnDummyEffect(), go_bells::go_bellsAI::UpdateAI(), boss_cthun::UpdateAI(), boss_hodir::boss_hodirAI::UpdateAI(), boss_yoggsaron::boss_yoggsaronAI::UpdateAI(), and brann_bronzebeard::brann_bronzebeardAI::UpdateEscortAI().
PlayDistanceSound()
void WorldObject::PlayDistanceSound (uint32 sound_id, Player * target = nullptr)
{
    if (target)
        target->SendDirectMessage(WorldPackets::Misc::PlayObjectSound(GetGUID(), sound_id).Write());
    else
        SendMessageToSet(WorldPackets::Misc::PlayObjectSound(GetGUID(), sound_id).Write(), true);
}
References Object::GetGUID(), Player::SendDirectMessage(), and SendMessageToSet().
Referenced by AuraEffect::HandleAuraDummy(), debug_commandscript::HandleDebugPlaySoundCommand(), npc_harrison_jones::SpellHit(), npc_cameron::UpdateAI(), and npc_eastvale_peasent::UpdateAI().
PlayRadiusMusic()
void WorldObject::PlayRadiusMusic (uint32 music_id, float radius)
{
    std::vector<Player*> targets;
    Acore::AnyPlayerInObjectRangeCheck check(this, radius, false);
    Acore::PlayerListSearcher<Acore::AnyPlayerInObjectRangeCheck> searcher(this, targets, check);
    Cell::VisitObjects(this, searcher, radius);
    for (Player* player : targets)
        player->SendDirectMessage(WorldPackets::Misc::PlayMusic(music_id).Write());
}
References Cell::VisitObjects(), and WorldPackets::Misc::PlayMusic::Write().
PlayRadiusSound()
void WorldObject::PlayRadiusSound (uint32 sound_id, float radius)
{
    std::vector<Player*> targets;
    Acore::AnyPlayerInObjectRangeCheck check(this, radius, false);
    Acore::PlayerListSearcher<Acore::AnyPlayerInObjectRangeCheck> searcher(this, targets, check);
    Cell::VisitObjects(this, searcher, radius);
    for (Player* player : targets)
        player->SendDirectMessage(WorldPackets::Misc::Playsound(sound_id).Write());
}
References Cell::VisitObjects(), and WorldPackets::Misc::Playsound::Write().
Referenced by npc_blade_of_azzinoth::IsSummonedBy().
ProcessPositionDataChanged()
void WorldObject::ProcessPositionDataChanged (PositionFullTerrainStatus const & data) protected virtual
Reimplemented in Unit.
{
    uint32 const oldZoneId = _zoneId;
    _zoneId = _areaId = data.areaId;
    if (AreaTableEntry const* area = sAreaTableStore.LookupEntry(_areaId))
        if (area->zone)
            _zoneId = area->zone;
    _outdoors   = data.outdoors;
    _floorZ     = data.floorZ;
    _liquidData = data.liquidInfo;
    // Has zone ID changed?
    if (oldZoneId != _zoneId)
    {
        // If so, check if we are far visibility overridden object and refresh maps if needed.
        if (IsZoneWideVisible())
        {
            GetMap()->RemoveWorldObjectFromZoneWideVisibleMap(oldZoneId, this);
            GetMap()->AddWorldObjectToZoneWideVisibleMap(_zoneId, this);
        }
    }
}
References _areaId, _floorZ, _liquidData, _outdoors, _zoneId, Map::AddWorldObjectToZoneWideVisibleMap(), PositionFullTerrainStatus::areaId, PositionFullTerrainStatus::floorZ, GetMap(), IsZoneWideVisible(), PositionFullTerrainStatus::liquidInfo, PositionFullTerrainStatus::outdoors, Map::RemoveWorldObjectFromZoneWideVisibleMap(), and sAreaTableStore.
Referenced by Unit::ProcessPositionDataChanged(), and UpdatePositionData().
RemoveAllowedLooter()
void WorldObject::RemoveAllowedLooter (ObjectGuid guid)
{
    _allowedLooters.erase(guid);
}
References _allowedLooters.
RemoveFromMapVisibilityOverrideContainers()
void WorldObject::RemoveFromMapVisibilityOverrideContainers () private
{
    if (!IsVisibilityOverridden())
        return;
    if (!IsInWorld())
        return;
    if (IsFarVisible())
        GetMap()->RemoveWorldObjectFromFarVisibleMap(this);
    else if (IsZoneWideVisible())
        GetMap()->RemoveWorldObjectFromZoneWideVisibleMap(_zoneId, this);
}
References _zoneId, GetMap(), IsFarVisible(), Object::IsInWorld(), IsVisibilityOverridden(), IsZoneWideVisible(), Map::RemoveWorldObjectFromFarVisibleMap(), and Map::RemoveWorldObjectFromZoneWideVisibleMap().
Referenced by RemoveFromWorld(), and SetVisibilityDistanceOverride().
RemoveFromNotify()
void WorldObject::RemoveFromNotify (uint16 f) inline
{ m_notifyflags &= ~f; }
References m_notifyflags.
Referenced by Unit::ExecuteDelayedUnitAINotifyEvent(), Unit::ExecuteDelayedUnitRelocationEvent(), and Player::Update().
RemoveFromObjectUpdate()
void WorldObject::RemoveFromObjectUpdate () override virtual
Implements Object.
{
    GetMap()->RemoveUpdateObject(this);
}
References GetMap(), and Map::RemoveUpdateObject().
RemoveFromWorld()
void WorldObject::RemoveFromWorld () override virtual
Reimplemented from Object.
{
    if (!IsInWorld())
        return;
    RemoveFromMapVisibilityOverrideContainers();
    DestroyForVisiblePlayers();
    GetObjectVisibilityContainer().CleanVisibilityReferences();
    Object::RemoveFromWorld();
}
References ObjectVisibilityContainer::CleanVisibilityReferences(), DestroyForVisiblePlayers(), GetObjectVisibilityContainer(), Object::IsInWorld(), RemoveFromMapVisibilityOverrideContainers(), and Object::RemoveFromWorld().
Referenced by CleanupsBeforeDelete(), Corpse::RemoveFromWorld(), DynamicObject::RemoveFromWorld(), GameObject::RemoveFromWorld(), and Unit::RemoveFromWorld().
ResetAllNotifies()
void WorldObject::ResetAllNotifies () inline
{ m_notifyflags = 0; m_executed_notifies = 0; }
References m_executed_notifies, and m_notifyflags.
ResetAllowedLooters()
void WorldObject::ResetAllowedLooters ()
{
    _allowedLooters.clear();
}
References _allowedLooters.
Referenced by GameObject::SetLootRecipient(), and Creature::SetLootRecipient().
ResetMap()
void WorldObject::ResetMap () virtual
Reimplemented in Player.
{
    ASSERT(m_currMap);
    ASSERT(!IsInWorld());
    sScriptMgr->OnWorldObjectResetMap(this);
    m_currMap = nullptr;
    //maybe not for corpse
    //m_mapId = 0;
    //m_InstanceId = 0;
}
References ASSERT, Object::IsInWorld(), m_currMap, and sScriptMgr.
Referenced by Map::RemoveCorpse(), Map::RemoveFromMap(), and Player::ResetMap().
SaveRespawnTime()
virtual void WorldObject::SaveRespawnTime () inline virtual
Reimplemented in Creature, and GameObject.
{}
SelectNearestPlayer()
Player * WorldObject::SelectNearestPlayer (float distance = 0) const
{
    Player* target = nullptr;
    Acore::NearestPlayerInObjectRangeCheck checker(this, distance);
    Acore::PlayerLastSearcher<Acore::NearestPlayerInObjectRangeCheck> searcher(this, target, checker);
    Cell::VisitObjects(this, searcher, distance);
    return target;
}
References Cell::VisitObjects().
Referenced by spell_blade_dance_targeting::FilterTargets(), spell_tsh_shoot_flame_arrow::FilterTargets(), SmartScript::GetTargets(), spell_valkyr_ball_periodic_dummy_aura::HandleEffectPeriodic(), npc_big_ooze::npc_big_oozeAI::IsSummonedBy(), boss_kiggler_the_crazed::JustEngagedWith(), boss_krosh_firehand::JustEngagedWith(), npc_hor_lich_king::npc_hor_lich_kingAI::JustSummoned(), boss_devourer_of_souls::boss_devourer_of_soulsAI::JustSummoned(), npc_hover_disk::npc_hover_diskAI::MovementInform(), npc_shattered_hand_scout::MovementInform(), npc_omen::npc_omenAI::MovementInform(), npc_gunship_mage::npc_gunship_mageAI::MovementInform(), npc_pos_martin_or_gorkun_second::npc_pos_martin_or_gorkun_secondAI::npc_pos_martin_or_gorkun_secondAI(), boss_headless_horseman_pumpkin::Reset(), npc_ahnqiraji_critter::Reset(), boss_grand_warlock_nethekurse::SetData(), npc_cork_gizelton::npc_cork_gizeltonAI::SetData(), instance_eye_of_eternity::instance_eye_of_eternity_InstanceMapScript::SetData(), npc_bh_thalorien_dawnseeker::npc_bh_thalorien_dawnseekerAI::SetData(), npc_argent_captainAI::SpellHit(), boss_headless_horseman_head::SpellHit(), npc_giant_claw_tentacle::Submerge(), instance_blackrock_depths::instance_blackrock_depths_InstanceMapScript::TombOfSevenEvent(), boss_rend_blackhand::boss_rend_blackhandAI::UpdateAI(), boss_victor_nefarius::boss_victor_nefariusAI::UpdateAI(), npc_hallows_end_soh::UpdateAI(), npc_murkdeep::npc_murkdeepAI::UpdateAI(), npc_high_overlord_saurfang_icc::npc_high_overlord_saurfangAI::UpdateAI(), npc_muradin_bronzebeard_icc::npc_muradin_bronzebeard_iccAI::UpdateAI(), npc_big_ooze::npc_big_oozeAI::UpdateAI(), npc_valithria_cloud::npc_valithria_cloudAI::UpdateAI(), boss_four_horsemen::boss_four_horsemenAI::UpdateAI(), boss_razorscale::boss_razorscaleAI::UpdateAI(), npc_hor_raging_ghoul::npc_hor_raging_ghoulAI::UpdateAI(), and npc_grimstone::npc_grimstoneAI::UpdateEscortAI().
SendMessageToSet() [1/2]
void WorldObject::SendMessageToSet (WorldPacket const * data, bool self) const virtual
Reimplemented in Player.
{
    if (IsInWorld())
        SendMessageToSetInRange(data, 0.0f, self);
}
References Object::IsInWorld(), and SendMessageToSetInRange().
Referenced by AuraApplication::ClientUpdate(), Unit::DealDamageShieldDamage(), Spell::Delayed(), Unit::Dismount(), Spell::EffectDispel(), Spell::EffectInstaKill(), Spell::EffectStealBeneficialBuff(), npc_xt002_boombot::npc_xt002_boombotAI::Explode(), AuraEffect::HandleAuraSetVehicle(), Unit::HandleEmoteCommand(), WorldSession::HandleForceSpeedChangeAck(), WorldSession::HandleMoveFlagChangeOpcode(), WorldSession::HandleMovementOpcodes(), WorldSession::HandleMoveRootAck(), WorldSession::HandleMoveSplineDoneOpcode(), WorldSession::HandleUpdateProjectilePosition(), npc_gunship::npc_gunshipAI::JustDied(), Movement::MoveSplineInit::Launch(), Unit::Mount(), PlayDirectMusic(), PlayDirectSound(), PlayDistanceSound(), Unit::SendAttackStateUpdate(), Unit::SendChangeCurrentVictimOpcode(), Spell::SendChannelStart(), Spell::SendChannelUpdate(), Unit::SendClearTarget(), Unit::SendClearThreatListOpcode(), GameObject::SendCustomAnim(), Unit::SendEnergizeSpellLog(), Unit::SendHealSpellLog(), Spell::SendInterrupted(), Spell::SendLogExecute(), Unit::SendMeleeAttackStart(), Unit::SendMeleeAttackStop(), Unit::SendMonsterMove(), Unit::SendMovementFlagUpdate(), Unit::SendMoveRoot(), SendObjectDeSpawnAnim(), Unit::SendPeriodicAuraLog(), Unit::SendPetActionSound(), Unit::SendPetDismissSound(), SendPlayMusic(), Unit::SendPlaySpellImpact(), Unit::SendPlaySpellVisual(), Unit::SendRemoveFromThreatListOpcode(), Unit::SendSpellDamageImmune(), Unit::SendSpellDamageResist(), Spell::SendSpellGo(), Unit::SendSpellMiss(), Unit::SendSpellNonMeleeDamageLog(), Spell::SendSpellStart(), Unit::SendTeleportPacket(), Unit::SendThreatListUpdate(), Unit::SetCanFly(), Unit::SetDisableGravity(), Unit::SetFeatherFall(), Unit::SetHover(), Unit::SetPower(), Unit::SetSpeed(), Creature::SetSwim(), Creature::SetWalk(), Unit::SetWaterWalking(), Movement::MoveSplineInit::Stop(), and boss_svala::boss_svalaAI::UpdateAI().
SendMessageToSet() [2/2]
void WorldObject::SendMessageToSet (WorldPacket const * data, Player const * skipped_rcvr) const virtual
Reimplemented in Player.
{
    Acore::MessageDistDeliverer notifier(this, data, 0.0f, false, skipped_rcvr);
    notifier.Visit(GetObjectVisibilityContainer().GetVisiblePlayersMap());
}
References GetObjectVisibilityContainer(), and Acore::MessageDistDeliverer::Visit().
SendMessageToSetInRange()
void WorldObject::SendMessageToSetInRange (WorldPacket const * data, float dist, bool self) const virtual
Reimplemented in Player.
{
    Acore::MessageDistDeliverer notifier(this, data, dist);
    notifier.Visit(GetObjectVisibilityContainer().GetVisiblePlayersMap());
}
References GetObjectVisibilityContainer(), and Acore::MessageDistDeliverer::Visit().
Referenced by SendMessageToSet(), and CreatureTextMgr::SendNonChatPacket().
SendObjectDeSpawnAnim()
void WorldObject::SendObjectDeSpawnAnim (ObjectGuid guid)
{
    WorldPacket data(SMSG_GAMEOBJECT_DESPAWN_ANIM, 8);
    data << guid;
    SendMessageToSet(&data, true);
}
References SendMessageToSet(), and SMSG_GAMEOBJECT_DESPAWN_ANIM.
Referenced by GameObject::Delete(), GameObject::DespawnOrUnsummon(), DynamicObject::Remove(), and GameObject::Update().
SendPlayMusic()
void WorldObject::SendPlayMusic (uint32 Music, bool OnlySelf)
{
    WorldPacket data(SMSG_PLAY_MUSIC, 4);
    data << Music;
    if (OnlySelf && IsPlayer())
        ToPlayer()->SendDirectMessage(&data);
    else
        SendMessageToSet(&data, true); // ToSelf ignored in this case
}
References Object::IsPlayer(), Player::SendDirectMessage(), SendMessageToSet(), SMSG_PLAY_MUSIC, and Object::ToPlayer().
setActive()
void WorldObject::setActive (bool isActiveObject)
{
    if (m_isActive == on)
        return;
    if (IsPlayer())
        return;
    m_isActive = on;
    if (!on || !IsInWorld())
        return;
    Map* map = FindMap();
    if (!map)
        return;
    map->AddObjectToPendingUpdateList(this);
}
References Map::AddObjectToPendingUpdateList(), FindMap(), Object::IsInWorld(), Object::IsPlayer(), and m_isActive.
Referenced by BossAI::_JustEngagedWith(), BossAI::_JustReachedHome(), Unit::AddPlayerToVision(), CinematicMgr::BeginCinematic(), boss_twilight_halion::boss_twilight_halionAI::boss_twilight_halionAI(), npc_bh_thalorien_dawnseeker::npc_bh_thalorien_dawnseekerAI::DamageTaken(), npc_warden_mellichar::npc_warden_mellicharAI::DamageTaken(), npc_grand_magister_rommath::npc_grand_magister_rommathAI::DoAction(), boss_krick::boss_krickAI::DoAction(), npc_hyjal_ground_trash::DoAction(), npc_hyjal_gargoyle::DoAction(), npc_hyjal_frost_wyrm::DoAction(), npc_xerestrasza::npc_xerestraszaAI::DoAction(), boss_sindragosa::boss_sindragosaAI::DoAction(), npc_spinestalker::npc_spinestalkerAI::DoAction(), npc_rimefang::npc_rimefangAI::DoAction(), npc_terenas_menethil::npc_terenas_menethilAI::DoAction(), npc_crok_scourgebane::npc_crok_scourgebaneAI::DoAction(), boss_sister_svalna::boss_sister_svalnaAI::DoAction(), npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI::DoAction(), npc_icc_putricades_trap::npc_icc_putricades_trapAI::DoAction(), npc_tirions_gambit_tirion::npc_tirions_gambit_tirionAI::DoAction(), boss_illidari_council::DoAction(), boss_kologarn::boss_kologarnAI::EnterEvadeMode(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::EnterEvadeMode(), ValithriaDespawner::Execute(), go_necropolis::go_necropolis(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::InitFight(), npc_cork_gizelton::npc_cork_gizeltonAI::Initialize(), boss_razorscale::boss_razorscaleAI::InitializeAI(), npc_lord_arete::npc_lord_areteAI::InitializeAI(), npc_herald_of_the_lich_king::InitializeAI(), Totem::InitSummon(), npc_warden_mellichar::npc_warden_mellicharAI::JustDied(), boss_sartharion_dragonAI::JustEngagedWith(), boss_servant_quarters::JustEngagedWith(), boss_hadronox::JustEngagedWith(), boss_anubarak_trial::boss_anubarak_trialAI::JustEngagedWith(), boss_jaraxxus::boss_jaraxxusAI::JustEngagedWith(), boss_gormok::boss_gormokAI::JustEngagedWith(), boss_jormungarAI::JustEngagedWith(), boss_icehowl::boss_icehowlAI::JustEngagedWith(), boss_twin_valkyrAI::JustEngagedWith(), npc_stinky_icc::npc_stinky_iccAI::JustEngagedWith(), boss_lord_marrowgar::JustEngagedWith(), npc_precious_icc::npc_precious_iccAI::JustEngagedWith(), npc_icc_valkyr_herald::npc_icc_valkyr_heraldAI::JustEngagedWith(), boss_algalon_the_observer::boss_algalon_the_observerAI::JustEngagedWith(), boss_auriaya::boss_auriayaAI::JustEngagedWith(), boss_flame_leviathan::boss_flame_leviathanAI::JustEngagedWith(), boss_freya::boss_freyaAI::JustEngagedWith(), boss_vezax::boss_vezaxAI::JustEngagedWith(), boss_ignis::boss_ignisAI::JustEngagedWith(), boss_kologarn::boss_kologarnAI::JustEngagedWith(), boss_mimiron::boss_mimironAI::JustEngagedWith(), boss_thorim::boss_thorimAI::JustEngagedWith(), boss_xt002::boss_xt002AI::JustEngagedWith(), boss_the_lich_king::boss_the_lich_kingAI::JustEngagedWith(), npc_green_dragon_combat_trigger::npc_green_dragon_combat_triggerAI::JustEngagedWith(), boss_trollgore::boss_trollgoreAI::JustEngagedWith(), boss_prince_keleseth_icc::boss_prince_kelesethAI::JustEngagedWith(), boss_prince_taldaram_icc::boss_prince_taldaramAI::JustEngagedWith(), boss_prince_valanar_icc::boss_prince_valanarAI::JustEngagedWith(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::JustEngagedWith(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::JustEngagedWith(), boss_festergut::boss_festergutAI::JustEngagedWith(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::JustEngagedWith(), boss_professor_putricide::boss_professor_putricideAI::JustEngagedWith(), boss_rotface::boss_rotfaceAI::JustEngagedWith(), boss_sindragosa::boss_sindragosaAI::JustEngagedWith(), boss_steelbreaker::boss_steelbreakerAI::JustEngagedWith(), boss_runemaster_molgeim::boss_runemaster_molgeimAI::JustEngagedWith(), boss_stormcaller_brundir::boss_stormcaller_brundirAI::JustEngagedWith(), boss_anubarak_trial::boss_anubarak_trialAI::JustReachedHome(), boss_jaraxxus::boss_jaraxxusAI::JustReachedHome(), boss_gormok::boss_gormokAI::JustReachedHome(), boss_jormungarAI::JustReachedHome(), boss_icehowl::boss_icehowlAI::JustReachedHome(), boss_twin_valkyrAI::JustReachedHome(), boss_prince_keleseth_icc::boss_prince_kelesethAI::JustReachedHome(), boss_prince_taldaram_icc::boss_prince_taldaramAI::JustReachedHome(), boss_prince_valanar_icc::boss_prince_valanarAI::JustReachedHome(), npc_icc_valkyr_herald::npc_icc_valkyr_heraldAI::JustReachedHome(), npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI::JustReachedHome(), npc_icc_putricades_trap::npc_icc_putricades_trapAI::JustReachedHome(), boss_algalon_the_observer::boss_algalon_the_observerAI::JustReachedHome(), boss_steelbreaker::boss_steelbreakerAI::JustReachedHome(), boss_runemaster_molgeim::boss_runemaster_molgeimAI::JustReachedHome(), boss_stormcaller_brundir::boss_stormcaller_brundirAI::JustReachedHome(), boss_auriaya::boss_auriayaAI::JustReachedHome(), boss_flame_leviathan::boss_flame_leviathanAI::JustReachedHome(), boss_freya::boss_freyaAI::JustReachedHome(), boss_vezax::boss_vezaxAI::JustReachedHome(), boss_ignis::boss_ignisAI::JustReachedHome(), boss_mimiron::boss_mimironAI::JustReachedHome(), boss_thorim::boss_thorimAI::JustReachedHome(), boss_xt002::boss_xt002AI::JustReachedHome(), npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::JustRespawned(), npc_kiljaeden_controller::JustSummoned(), boss_hydross_the_unstable::JustSummoned(), npc_pos_tyrannus_events::npc_pos_tyrannus_eventsAI::MovementInform(), boss_sindragosa::boss_sindragosaAI::MovementInform(), npc_spinestalker::npc_spinestalkerAI::MovementInform(), npc_rimefang::npc_rimefangAI::MovementInform(), npc_minigob_manabonk::npc_minigob_manabonk(), npc_necropolis::npc_necropolis(), npc_necropolis_proxy::npc_necropolis_proxy(), npc_necropolis_relay::npc_necropolis_relay(), npc_necrotic_shard::npc_necrotic_shard(), npc_time_lost_proto_drake::npc_time_lost_proto_drakeAI::npc_time_lost_proto_drakeAI(), npc_wg_spirit_guide::npc_wg_spirit_guideAI::npc_wg_spirit_guideAI(), npc_vehicle_d16_propelled_delivery::npc_vehicle_d16_propelled_deliveryAI::PassengerBoarded(), Unit::RemovePlayerFromVision(), npc_koltira_deathweaver::npc_koltira_deathweaverAI::Reset(), npc_valkyr_battle_maiden::npc_valkyr_battle_maidenAI::Reset(), npc_q24545_lich_king::npc_q24545_lich_kingAI::Reset(), npc_tirions_gambit_tirion::npc_tirions_gambit_tirionAI::Reset(), npc_akama_illidan::Reset(), npc_warden_mellichar::npc_warden_mellicharAI::Reset(), boss_svala::boss_svalaAI::SetData(), npc_highlord_tirion_fordring_lh::npc_highlord_tirion_fordringAI::SetData(), npc_bh_thalorien_dawnseeker::npc_bh_thalorien_dawnseekerAI::SetData(), npc_pos_leader::npc_pos_leaderAI::SetData(), npc_q24545_lich_king::npc_q24545_lich_kingAI::SetGUID(), BattlegroundIC::SetupBattleground(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::sGossipSelect(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::sGossipSelect(), npc_akama_illidan::sGossipSelect(), Battlefield::SpawnCreature(), Battlefield::SpawnGameObject(), go_firework_show::SpawnNextFirework(), npc_koltira_deathweaver::npc_koltira_deathweaverAI::StartEvent(), go_firework_show::StartShow(), go_firework_show::StopShow(), npc_warden_mellichar::npc_warden_mellicharAI::SummonedCreatureDies(), instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::Update(), npc_kalecgos_kj::UpdateAI(), npc_bh_thalorien_dawnseeker::npc_bh_thalorien_dawnseekerAI::UpdateAI(), npc_grand_magister_rommath::npc_grand_magister_rommathAI::UpdateAI(), npc_varian_wrynn::npc_varian_wrynnAI::UpdateAI(), npc_thrall_bfu::npc_thrall_bfuAI::UpdateAI(), npc_xerestrasza::npc_xerestraszaAI::UpdateAI(), npc_hor_leader_second::npc_hor_leader_secondAI::UpdateAI(), boss_krick::boss_krickAI::UpdateAI(), npc_pos_leader::npc_pos_leaderAI::UpdateAI(), npc_pos_tyrannus_events::npc_pos_tyrannus_eventsAI::UpdateAI(), npc_highlord_tirion_fordring_lh::npc_highlord_tirion_fordringAI::UpdateAI(), and boss_svala::boss_svalaAI::UpdateAI().
SetAllowedLooters()
void WorldObject::SetAllowedLooters (GuidUnorderedSet const looters)
{
    _allowedLooters = looters;
}
References _allowedLooters.
Referenced by GameObject::SetLootRecipient().
SetLocationInstanceId()
void WorldObject::SetLocationInstanceId (uint32 _instanceId) inline protected
{ m_InstanceId = _instanceId; }
References m_InstanceId.
Referenced by Corpse::LoadCorpseFromDB().
SetLocationMapId()
void WorldObject::SetLocationMapId (uint32 _mapId) inline protected
{ m_mapId = _mapId; }
References WorldLocation::m_mapId.
Referenced by Corpse::LoadCorpseFromDB().
SetMap()
void WorldObject::SetMap (Map * map) virtual
Reimplemented in Player.
{
    ASSERT(map);
    ASSERT(!IsInWorld());
    if (m_currMap == map) // command add npc: first create, than loadfromdb
    {
        return;
    }
    if (m_currMap)
    {
        LOG_FATAL("entities.object", "WorldObject::SetMap: obj {} new map {} {}, old map {} {}", (uint32)GetTypeId(), map->GetId(), map->GetInstanceId(), m_currMap->GetId(), m_currMap->GetInstanceId());
        ABORT();
    }
    m_currMap = map;
    m_mapId = map->GetId();
    m_InstanceId = map->GetInstanceId();
    sScriptMgr->OnWorldObjectSetMap(this, map);
}
References ABORT, ASSERT, Map::GetId(), Map::GetInstanceId(), Object::GetTypeId(), Object::IsInWorld(), LOG_FATAL, m_currMap, m_InstanceId, WorldLocation::m_mapId, and sScriptMgr.
Referenced by Map::AddCorpse(), Pet::Create(), Creature::Create(), GameObject::Create(), StaticTransport::Create(), DynamicObject::CreateDynamicObject(), TransportMgr::CreateTransport(), MotionTransport::DelayedTeleportTransport(), and Player::SetMap().
SetName()
void WorldObject::SetName (std::string const & newname) inline
{ m_name = newname; }
References m_name.
Referenced by GameObject::Create(), StaticTransport::Create(), Pet::CreateBaseAtCreature(), Pet::CreateBaseAtCreatureInfo(), MotionTransport::CreateMoTrans(), Spell::EffectSummonPet(), WorldSession::HandlePetRename(), Creature::InitEntry(), Pet::LoadPetFromDB(), and Player::SummonPet().
SetNotified()
void WorldObject::SetNotified (uint16 f) inline
{ m_executed_notifies |= f;}
References m_executed_notifies.
SetPhaseMask()
void WorldObject::SetPhaseMask (uint32 newPhaseMask, bool update) virtual
Reimplemented in GameObject, and Unit.
{
    sScriptMgr->OnBeforeWorldObjectSetPhaseMask(this, m_phaseMask, newPhaseMask, m_useCombinedPhases, update);
    m_phaseMask = newPhaseMask;
    if (update && IsInWorld())
        UpdateObjectVisibility();
}
References Object::IsInWorld(), m_phaseMask, m_useCombinedPhases, sScriptMgr, and UpdateObjectVisibility().
Referenced by _Create(), Map::ConvertCorpseToBones(), Corpse::LoadCorpseFromDB(), GameObject::SetPhaseMask(), and Unit::SetPhaseMask().
SetPositionDataUpdate()
void WorldObject::SetPositionDataUpdate ()
{
    _updatePositionData = true;
    // Calls immediately for charmed units
    if (IsCreature() && ToUnit()->IsCharmedOwnedByPlayerOrPlayer())
        UpdatePositionData();
}
References _updatePositionData, Object::IsCreature(), Object::ToUnit(), and UpdatePositionData().
Referenced by Map::DynamicObjectRelocation(), and Map::GameObjectRelocation().
SetTransport()
void WorldObject::SetTransport (Transport * t) inline
{ m_transport = t; }
References m_transport.
Referenced by MotionTransport::AddPassenger(), StaticTransport::AddPassenger(), DynamicObject::CleanupsBeforeDelete(), GameObject::CleanupsBeforeDelete(), MotionTransport::CleanupsBeforeDelete(), StaticTransport::CleanupsBeforeDelete(), Unit::CleanupsBeforeDelete(), MotionTransport::CreateGOPassenger(), MotionTransport::CreateNPCPassenger(), WorldSession::HandleMoverRelocation(), MotionTransport::RemovePassenger(), and StaticTransport::RemovePassenger().
SetVisibilityDistanceOverride()
void WorldObject::SetVisibilityDistanceOverride (VisibilityDistanceType type)
{
    ASSERT(type < VisibilityDistanceType::Max);
    if (type == GetVisibilityOverrideType())
        return;
    if (!IsCreature() && !IsGameObject() && !IsDynamicObject())
        return;
    // Important to remove from old visibility override containers first
    RemoveFromMapVisibilityOverrideContainers();
    // Always update _visibilityDistanceOverrideType, even when not in world
    _visibilityDistanceOverrideType = type;
    // Finally, add to new visibility override containers
    AddToMapVisibilityOverrideContainers();
}
References _visibilityDistanceOverrideType, AddToMapVisibilityOverrideContainers(), ASSERT, GetVisibilityOverrideType(), Object::IsCreature(), Object::IsDynamicObject(), Object::IsGameObject(), Max, and RemoveFromMapVisibilityOverrideContainers().
Referenced by GameObject::Create(), Totem::InitSummon(), and Creature::LoadCreaturesAddon().
SetZoneScript()
void WorldObject::SetZoneScript ()
{
    if (Map* map = FindMap())
    {
        if (InstanceMap* instanceMap = map->ToInstanceMap())
            m_zoneScript = reinterpret_cast<ZoneScript*>(instanceMap->GetInstanceScript());
        else if (!map->IsBattlegroundOrArena())
        {
            uint32 zoneId = GetZoneId();
            if (Battlefield* bf = sBattlefieldMgr->GetBattlefieldToZoneId(zoneId))
                m_zoneScript = bf;
            else
                m_zoneScript = sOutdoorPvPMgr->GetZoneScript(zoneId);
        }
    }
}
References FindMap(), GetZoneId(), m_zoneScript, sBattlefieldMgr, sOutdoorPvPMgr, and Map::ToInstanceMap().
Referenced by GameObject::Create(), StaticTransport::Create(), and Creature::CreateFromProto().
SummonCreature() [1/2]
TempSummon * WorldObject::SummonCreature (uint32 id, const Position & pos, TempSummonType spwtype = TEMPSUMMON_MANUAL_DESPAWN, uint32 despwtime = 0, uint32 vehId = 0, SummonPropertiesEntry const * properties = nullptr, bool visibleBySummonerOnly = false) const
{
    if (Map* map = FindMap())
    {
        if (TempSummon* summon = map->SummonCreature(entry, pos, properties, duration, (WorldObject*)this, 0, 0, visibleBySummonerOnly))
        {
            summon->SetTempSummonType(spwtype);
            return summon;
        }
    }
    return nullptr;
}
References FindMap(), TempSummon::SetTempSummonType(), and SummonCreature().
Referenced by at_icc_spire_frostwyrm::_OnTrigger(), Battleground::AddCreature(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::AddPortals(), boss_xt002::boss_xt002AI::AttachHeart(), boss_kologarn::boss_kologarnAI::AttachLeftArm(), boss_kologarn::boss_kologarnAI::AttachRightArm(), CinematicMgr::BeginCinematic(), boss_eydis::boss_eydisAI::boss_eydisAI(), boss_fjola::boss_fjolaAI::boss_fjolaAI(), boss_headless_horseman::DamageTaken(), boss_algalon_the_observer::boss_algalon_the_observerAI::DamageTaken(), npc_ulduar_arachnopod_destroyer::npc_ulduar_arachnopod_destroyerAI::DamageTaken(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::DamageTaken(), npc_grand_magister_rommath::npc_grand_magister_rommathAI::DoAction(), boss_victor_nefarius::boss_victor_nefariusAI::DoAction(), boss_archimonde::DoAction(), npc_thrall_warchief::npc_thrall_warchiefAI::DoAction(), npc_ahune_bunny::DoAction(), boss_cthun::DoAction(), npc_costumed_orphan_matron::DoAction(), npc_arthas::npc_arthasAI::DoAction(), boss_palehoof::boss_palehoofAI::DoAction(), boss_archimonde::DoCastDoomFire(), boss_bug_trio::DoFinalSpell(), npc_rinji::npc_rinjiAI::DoSpawnAmbush(), npc_lakota_windsong::npc_lakota_windsongAI::DoSpawnBandits(), ScriptedAI::DoSpawnCreature(), instance_stratholme::instance_stratholme_InstanceMapScript::DoSpawnPlaguedCritters(), npc_paoka_swiftmountain::npc_paoka_swiftmountainAI::DoSpawnWyvern(), npc_midsummer_ribbon_pole_target::DoSpewLavaChecks(), CreatureAI::DoSummon(), CreatureAI::DoSummon(), npc_time_rift::DoSummonAtRift(), CreatureAI::DoSummonFlyer(), npc_ranshalla::npc_ranshallaAI::DoSummonPriestess(), npc_muglash::npc_muglashAI::DoWaveSummon(), Spell::EffectDummy(), Spell::EffectSummonType(), npc_giant_claw_tentacle::Emerge(), DelayedSummonEvent::Execute(), IceTombSummonEvent::Execute(), boss_sartharion_tenebron::boss_sartharion_tenebronAI::ExecuteEvent(), boss_sartharion_shadron::boss_sartharion_shadronAI::ExecuteEvent(), boss_sartharion_vesperon::boss_sartharion_vesperonAI::ExecuteEvent(), boss_kaelthas::ExecuteMiddleEvent(), npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::FinishFight(), boss_janalai::FireWall(), npc_simon_bunny::npc_simon_bunnyAI::GivePunishment(), go_brazier_of_madness::GossipHello(), go_celestial_planetarium_access::go_celestial_planetarium_accessAI::GossipHello(), spell_rotface_unstable_ooze_explosion_init::HandleCast(), debug_commandscript::HandleDebugSpawnVehicleCommand(), spell_midsummer_summon_ahune_lieutenant::HandleDummy(), spell_q11010_q11102_q11023_choose_loc::HandleDummy(), spell_herald_volzaj_insanity::HandleDummyEffect(), spell_hor_gunship_cannon_fire_aura::HandleEffectPeriodic(), spell_gen_haunted_aura::HandleEffectPeriodic(), spell_hodir_flash_freeze_aura::HandleEffectPeriodic(), spell_ignis_scorch_aura::HandleEffectPeriodic(), spell_dtk_raise_dead_aura::HandleEffectRemove(), spell_icc_geist_alarm::HandleEvent(), spell_grobbulus_slime_spray::HandleHit(), mmaps_commandscript::HandleMmapPathCommand(), npc_commandscript::HandleNpcAddTempSpawnCommand(), spell_gen_haunted::HandleOnEffectHit(), spell_kaelthas_summon_nether_vapor::HandleScriptEffect(), spell_q12478_frostmourne_cavern::HandleSendEvent(), spell_q9847_a_spirit_ally::HandleSendEvent(), spell_item_draenic_pale_ale::HandleSummon(), boss_priestess_delrissa::InitializeAI(), npc_general_andorov::InitializeAI(), boss_prince_keleseth_icc::boss_prince_kelesethAI::InitializeAI(), boss_prince_taldaram_icc::boss_prince_taldaramAI::InitializeAI(), boss_prince_valanar_icc::boss_prince_valanarAI::InitializeAI(), npc_hourglass_of_eternity::npc_hourglass_of_eternityAI::InitializeAI(), brann_bronzebeard::brann_bronzebeardAI::InitializeEvent(), boss_moroes::InitializeGuests(), Vehicle::InstallAccessory(), instance_trial_of_the_champion::instance_trial_of_the_champion_InstanceMapScript::InstanceCleanup(), instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::InstanceCleanup(), npc_ranshalla::npc_ranshallaAI::JustDidDialogueStep(), boss_halycon::boss_halyconAI::JustDied(), npc_auriaya_feral_defender::npc_auriaya_feral_defenderAI::JustDied(), boss_kologarn_arms::boss_kologarn_armsAI::JustDied(), boss_exarch_maladaar::JustDied(), npc_necrotic_shard::JustDied(), boss_jarien::JustDied(), boss_sothos::JustDied(), boss_felmyst::JustDied(), boss_kurinnaxx::JustDied(), npc_webbed_creature::npc_webbed_creatureAI::JustDied(), boss_shade_of_aran::JustEngagedWith(), boss_mandokir::boss_mandokirAI::JustEngagedWith(), boss_anubarak_trial::boss_anubarak_trialAI::JustEngagedWith(), boss_devourer_of_souls::boss_devourer_of_soulsAI::JustEngagedWith(), boss_keleseth::JustEngagedWith(), boss_exarch_maladaar::JustEngagedWith(), boss_shirrak_the_dead_watcher::JustEngagedWith(), boss_blackheart_the_inciter::JustEngagedWith(), boss_sacrolash::JustEngagedWith(), boss_kalecgos::JustEngagedWith(), boss_hexlord_malacrass::JustEngagedWith(), boss_janalai::JustEngagedWith(), boss_onyxia::JustEngagedWith(), boss_ossirian::JustEngagedWith(), boss_novos::JustEngagedWith(), boss_anubrekhan::boss_anubrekhanAI::JustEngagedWith(), boss_high_astromancer_solarian::JustEngagedWith(), boss_halion::boss_halionAI::JustSummoned(), npc_akama_illidan::KilledUnit(), npc_the_scourge_cauldron::npc_the_scourge_cauldronAI::MoveInLineOfSight(), npc_ulduar_snow_mound::MoveInLineOfSight(), npc_black_knight_graveyard::npc_black_knight_graveyardAI::MoveInLineOfSight(), npc_koltira_deathweaver::npc_koltira_deathweaverAI::MovementInform(), boss_captain_skarloc::MovementInform(), boss_malygos::boss_malygosAI::MovementInform(), boss_vazruden_the_herald::MovementInform(), boss_flame_leviathan_safety_container::boss_flame_leviathan_safety_containerAI::MovementInform(), npc_claw_tentacle::npc_claw_tentacle(), npc_eye_tentacle::npc_eye_tentacle(), npc_giant_claw_tentacle::npc_giant_claw_tentacle(), npc_giant_eye_tentacle::npc_giant_eye_tentacle(), npc_ulduar_flames_initial::npc_ulduar_flames_initialAI::npc_ulduar_flames_initialAI(), npc_vh_void_sentry::npc_vh_void_sentryAI::npc_vh_void_sentryAI(), go_gong_of_bethekk::OnGossipHello(), go_resonite_cask::OnGossipHello(), go_strange_pool::OnGossipHello(), go_ethereum_prison::OnGossipHello(), go_ethereum_stasis::OnGossipHello(), go_sacred_fire_of_life::OnGossipHello(), go_southfury_moonstone::OnGossipHello(), go_arcane_prison::OnGossipHello(), go_hive_pod::OnGossipHello(), npc_grandmother::OnGossipSelect(), go_pumpkin_shrine::OnGossipSelect(), go_apexis_relic::OnGossipSelect(), instance_ruins_of_ahnqiraj::instance_ruins_of_ahnqiraj_InstanceMapScript::OnPlayerEnter(), instance_eye_of_eternity::instance_eye_of_eternity_InstanceMapScript::OnPlayerEnter(), npc_maghar_captive::OnQuestAccept(), npc_karynaku::OnQuestAccept(), go_crystalline_tear::OnQuestAccept(), go_loosely_turned_soil::OnQuestReward(), spell_xt002_gravity_bomb_aura::OnRemove(), AreaTrigger_at_scent_larkorwi::OnTrigger(), AreaTrigger_at_nats_landing::OnTrigger(), AreaTrigger_at_sentry_point::OnTrigger(), AreaTrigger_at_area_52_entrance::OnTrigger(), at_malfurion_stormrage::OnTrigger(), at_twilight_grove::OnTrigger(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnUnitDeath(), boss_jeklik::PathEndReached(), npc_akama_illidan::PathEndReached(), boss_yoggsaron_brain::boss_yoggsaron_brainAI::PrepareChamberIllusion(), npc_barnes::npc_barnesAI::PrepareEncounter(), npc_dark_iron_attack_generator::PrepareEvent(), boss_yoggsaron_brain::boss_yoggsaron_brainAI::PrepareIceCrownIllusion(), boss_yoggsaron_brain::boss_yoggsaron_brainAI::PrepareStormwindIllusion(), npc_battle_at_valhalas::npc_battle_at_valhalasAI::PrepareSummons(), SmartScript::ProcessAction(), boss_flame_leviathan::boss_flame_leviathanAI::RadioSay(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::ReorderInstance(), boss_majordomo::boss_majordomoAI::Reset(), boss_malchezaar::Reset(), npc_image_of_medivh::npc_image_of_medivhAI::Reset(), boss_garaxxas::Reset(), npc_kiljaeden_controller::Reset(), npc_coren_direbrew::Reset(), boss_archimonde::Reset(), boss_infinite_corruptor::boss_infinite_corruptorAI::Reset(), boss_anubarak_trial::boss_anubarak_trialAI::Reset(), boss_drakkari_colossus::boss_drakkari_colossusAI::Reset(), boss_slad_ran::boss_slad_ranAI::Reset(), boss_the_lich_king::boss_the_lich_kingAI::Reset(), boss_thaddius::boss_thaddiusAI::Reset(), boss_bjarngrim::Reset(), boss_sjonnir::boss_sjonnirAI::Reset(), boss_auriaya::boss_auriayaAI::Reset(), npc_ulduar_leviathan_mkii::npc_ulduar_leviathan_mkiiAI::Reset(), boss_thorim_runic_colossus::boss_thorim_runic_colossusAI::Reset(), boss_skadi::boss_skadiAI::Reset(), boss_vazruden_the_herald::Reset(), npc_oscillating_frequency_scanner_master_bunny::npc_oscillating_frequency_scanner_master_bunnyAI::Reset(), npc_firework::npc_fireworkAI::Reset(), npc_minion_spawner::Reset(), boss_emalon::boss_emalonAI::ResetSummons(), boss_warchief_kargath_bladefist::RespawnAssassins(), boss_alar::ScheduleAbilities(), boss_illidan_stormrage::ScheduleAbilities(), boss_kiljaeden::ScheduleBasicAbilities(), boss_the_lurker_below::SchedulerPhaseOne(), npc_pallid_horror::ScheduleTasks(), boss_cthun::ScheduleTasks(), boss_sjonnir::boss_sjonnirAI::ScheduleTasks(), boss_svala::boss_svalaAI::SetData(), npc_ulduar_harpoonfirestate::npc_ulduar_harpoonfirestateAI::SetData(), instance_eye_of_eternity::instance_eye_of_eternity_InstanceMapScript::SetData(), npc_pos_tyrannus_events::npc_pos_tyrannus_eventsAI::SetData(), npc_idol_room_spawner::npc_idol_room_spawnerAI::SetData(), npc_lady_sylvanas_windrunner::npc_lady_sylvanas_windrunnerAI::SetGUID(), npc_kurenai_captive::npc_kurenai_captiveAI::SetGUID(), npc_echo_of_medivh::SetupBoard(), boss_hexlord_malacrass::SpawnAdds(), boss_zuljin::SpawnAdds(), boss_thorim::boss_thorimAI::SpawnAllNPCs(), boss_thorim::boss_thorimAI::SpawnAnArenaNPC(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::SpawnClouds(), boss_selin_fireheart::SpawnCrystals(), boss_skadi_grauf::boss_skadi_graufAI::SpawnFlameTriggers(), boss_kelthuzad::boss_kelthuzadAI::SpawnHelpers(), boss_razuvious::boss_razuviousAI::SpawnHelpers(), boss_hodir::boss_hodirAI::SpawnHelpers(), boss_skadi_grauf::boss_skadi_graufAI::SpawnHelpers(), boss_malchezaar::SpawnInfernal(), boss_darkmaster_gandling::boss_darkmaster_gandlingAI::SpawnMobsInRoom(), boss_ossirian::SpawnNextCrystal(), boss_alar::SpawnPhoenixes(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::SpawnTentacle(), npc_arthas::npc_arthasAI::SpawnTimeRift(), boss_grandmaster_vorpil::spawnVoidTraveler(), boss_freya::boss_freyaAI::SpawnWave(), npc_grimstone::npc_grimstoneAI::SpawnWave(), npc_varian_wrynn::npc_varian_wrynnAI::SpawnWave(), npc_thrall_bfu::npc_thrall_bfuAI::SpawnWave(), boss_julianne::SpellHit(), boss_urom::boss_uromAI::SpellHit(), boss_headless_horseman_pumpkin::SpellHit(), boss_sister_svalna::boss_sister_svalnaAI::SpellHitTarget(), npc_icc_valkyr_herald::npc_icc_valkyr_heraldAI::SpellHitTarget(), boss_freya::boss_freyaAI::SpellHitTarget(), boss_lethon::boss_lethonAI::SpellHitTarget(), npc_xt002_heart::npc_xt002_heartAI::SpellHitTarget(), boss_ionar::Split(), npc_ulduar_flames_initial::npc_ulduar_flames_initialAI::SpreadFlame(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::Summon(), npc_eris_hevenfire::npc_eris_hevenfireAI::SummonArchers(), npc_grimstone::npc_grimstoneAI::SummonBoss(), npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI::SummonBroodling(), boss_anzu::SummonBroods(), SummonCreature(), SummonCreature(), SummonCreatureGroup(), PassengerController::SummonCreatures(), brann_bronzebeard::brann_bronzebeardAI::SummonCreatures(), npc_deathstalker_fearleia::SummonCreatureWithRandomTarget(), SummonCroneIfReady(), npc_ravenclaw_apparition::npc_ravenclaw_apparitionAI::SummonCrowd(), boss_anubrekhan::boss_anubrekhanAI::SummonCryptGuards(), npc_necrotic_shard::SummonCultists(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::SummonDeathOrbs(), boss_akilzon::SummonEagles(), boss_cthun::SummonedCreatureDies(), npc_kiljaeden_controller::SummonedCreatureDies(), boss_jedoga_shadowseeker::SummonedCreatureDies(), npc_pallid_horror::SummonFlameshockers(), npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI::SummonFrostwardens(), npc_air_force_bots::npc_air_force_botsAI::SummonGuard(), boss_fankriss::SummonHatchlingWaves(), boss_kelthuzad::boss_kelthuzadAI::SummonHelper(), boss_noth::boss_nothAI::SummonHelper(), npc_cork_gizelton::npc_cork_gizeltonAI::SummonHelpers(), boss_faerlina::boss_faerlinaAI::SummonHelpers(), boss_gothik::boss_gothikAI::SummonHelpers(), boss_yoggsaron::boss_yoggsaronAI::SummonImmortalGuardian(), npc_invis_infernal_caster::npc_invis_infernal_casterAI::SummonInfernal(), boss_sartharion::boss_sartharionAI::SummonLavaWaves(), boss_amanitar::SummonMushroom(), npc_anachronos_quest_trigger::npc_anachronos_quest_triggerAI::SummonNextWave(), npc_lord_illidan_stormrage::npc_lord_illidan_stormrageAI::SummonNextWave(), go_wind_stone::go_wind_stoneAI::SummonNPC(), npc_medivh_bm::SummonOrcs(), npc_eris_hevenfire::npc_eris_hevenfireAI::SummonPeasants(), npc_xt002_heart::npc_xt002_heartAI::SummonPiles(), boss_netherspite::SummonPortals(), boss_grandmaster_vorpil::summonPortals(), npc_coren_direbrew::SummonSister(), npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI::SummonSpiders(), boss_ambassador_flamelash::boss_ambassador_flamelashAI::SummonSpirits(), boss_anzu::SummonSpirits(), boss_sartharion::boss_sartharionAI::SummonStartingTriggers(), go_tadpole_cage::go_tadpole_cageAI::SummonTadpoles(), boss_dorothee::SummonTito(), SummonTrigger(), instance_trial_of_the_champion::instance_trial_of_the_champion_InstanceMapScript::Update(), instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::Update(), instance_violet_hold::instance_violet_hold_InstanceMapScript::Update(), boss_overlord_wyrmthalak::boss_overlordwyrmthalakAI::UpdateAI(), boss_rend_blackhand::boss_rend_blackhandAI::UpdateAI(), boss_victor_nefarius::boss_victor_nefariusAI::UpdateAI(), boss_vaelastrasz::boss_vaelAI::UpdateAI(), npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::UpdateAI(), npc_kalecgos_kj::UpdateAI(), npc_bh_thalorien_dawnseeker::npc_bh_thalorien_dawnseekerAI::UpdateAI(), npc_thrall_bfu::npc_thrall_bfuAI::UpdateAI(), npc_dark_iron_attack_generator::UpdateAI(), npc_dark_iron_attack_mole_machine::UpdateAI(), npc_pilgrims_bounty_chair::UpdateAI(), npc_arthas::npc_arthasAI::UpdateAI(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::UpdateAI(), npc_medivh_bm::UpdateAI(), npc_time_rift::UpdateAI(), boss_onyxia::UpdateAI(), npc_belnistrasz::npc_belnistraszAI::UpdateAI(), npc_murkdeep::npc_murkdeepAI::UpdateAI(), npc_clintar_spirit::npc_clintar_spiritAI::UpdateAI(), npc_twiggy_flathead::npc_twiggy_flatheadAI::UpdateAI(), npc_shadowpriest_sezziz::npc_shadowpriest_sezzizAI::UpdateAI(), npc_twilight_volunteer::UpdateAI(), boss_anubarak_trial::boss_anubarak_trialAI::UpdateAI(), npc_snobold_vassal::npc_snobold_vassalAI::UpdateAI(), boss_jormungarAI::UpdateAI(), boss_twin_valkyrAI::UpdateAI(), npc_phantom_mage::npc_phantom_mageAI::UpdateAI(), npc_pos_leader::npc_pos_leaderAI::UpdateAI(), npc_pos_after_first_boss::npc_pos_after_first_bossAI::UpdateAI(), npc_pos_tyrannus_events::npc_pos_tyrannus_eventsAI::UpdateAI(), npc_pos_martin_or_gorkun_second::npc_pos_martin_or_gorkun_secondAI::UpdateAI(), npc_pos_leader_second::npc_pos_leader_secondAI::UpdateAI(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::UpdateAI(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::UpdateAI(), boss_rotface::boss_rotfaceAI::UpdateAI(), npc_icc_putricades_trap::npc_icc_putricades_trapAI::UpdateAI(), boss_gluth::boss_gluthAI::UpdateAI(), boss_kelthuzad::boss_kelthuzadAI::UpdateAI(), boss_maexxna::boss_maexxnaAI::UpdateAI(), boss_sapphiron::boss_sapphironAI::UpdateAI(), npc_naxxramas_trigger::UpdateAI(), boss_malygos::boss_malygosAI::UpdateAI(), boss_ormorok::UpdateAI(), boss_drakos::boss_drakosAI::UpdateAI(), boss_eregos::boss_eregosAI::UpdateAI(), boss_varos::boss_varosAI::UpdateAI(), boss_sjonnir_malformed_ooze::boss_sjonnir_malformed_oozeAI::UpdateAI(), boss_algalon_the_observer::boss_algalon_the_observerAI::UpdateAI(), npc_hodirs_fury::npc_hodirs_furyAI::UpdateAI(), npc_mimirons_inferno::npc_mimirons_infernoAI::UpdateAI(), npc_thorims_hammer::npc_thorims_hammerAI::UpdateAI(), npc_storm_beacon_spawn::npc_storm_beacon_spawnAI::UpdateAI(), boss_freya::boss_freyaAI::UpdateAI(), boss_freya_elder_brightleaf::boss_freya_elder_brightleafAI::UpdateAI(), boss_mimiron::boss_mimironAI::UpdateAI(), npc_ulduar_vx001::npc_ulduar_vx001AI::UpdateAI(), npc_ulduar_aerial_command_unit::npc_ulduar_aerial_command_unitAI::UpdateAI(), npc_ulduar_bot_summon_trigger::npc_ulduar_bot_summon_triggerAI::UpdateAI(), boss_razorscale::boss_razorscaleAI::UpdateAI(), boss_thorim::boss_thorimAI::UpdateAI(), boss_thorim_sif::boss_thorim_sifAI::UpdateAI(), boss_thorim_ancient_rune_giant::boss_thorim_ancient_rune_giantAI::UpdateAI(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::UpdateAI(), npc_massive_jormungar::npc_massive_jormungarAI::UpdateAI(), boss_svala::boss_svalaAI::UpdateAI(), boss_ymiron::boss_ymironAI::UpdateAI(), boss_emalon::boss_emalonAI::UpdateAI(), boss_toravon::boss_toravonAI::UpdateAI(), npc_thassarian2::npc_thassarian2AI::UpdateAI(), npc_archmage_landalock::npc_archmage_landalockAI::UpdateAI(), npc_conversing_with_the_depths_trigger::npc_conversing_with_the_depths_triggerAI::UpdateAI(), npc_hourglass_of_eternity::npc_hourglass_of_eternityAI::UpdateAI(), npc_q24545_lich_king::npc_q24545_lich_kingAI::UpdateAI(), npc_llod_generic::npc_llod_genericAI::UpdateAI(), npc_overlord_drakuru_betrayal::UpdateAI(), npc_ahune_bunny::UpdateAI(), npc_warden_mellichar::npc_warden_mellicharAI::UpdateAI(), npc_deaths_door_fell_cannon_target_bunny::npc_deaths_door_fell_cannon_target_bunnyAI::UpdateAI(), npc_commander_dawnforge::npc_commander_dawnforgeAI::UpdateAI(), npc_doctor::npc_doctorAI::UpdateAI(), npc_wizzlecrank_shredder::npc_wizzlecrank_shredderAI::UpdateEscortAI(), brann_bronzebeard::brann_bronzebeardAI::UpdateEscortAI(), npc_tirions_gambit_tirion::npc_tirions_gambit_tirionAI::UpdateEscortAI(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::UpdateKeeperSpawns(), boss_netherspite::UpdatePortals(), CreatureAI::VisualizeBoundary(), npc_tirions_gambit_tirion::npc_tirions_gambit_tirionAI::WaypointReached(), npc_arthas::npc_arthasAI::WaypointReached(), npc_barnes::npc_barnesAI::WaypointReached(), npc_professor_phizzlethorpe::npc_professor_phizzlethorpeAI::WaypointReached(), npc_ranger_lilatha::WaypointReached(), npc_lord_gregor_lescovar::npc_lord_gregor_lescovarAI::WaypointReached(), npc_daphne_stilwell::npc_daphne_stilwellAI::WaypointReached(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::WaypointReached(), npc_cork_gizelton::npc_cork_gizeltonAI::WaypointReached(), npc_kaya_flathoof::npc_kaya_flathoofAI::WaypointReached(), npc_wizzlecrank_shredder::npc_wizzlecrank_shredderAI::WaypointReached(), npc_ame::npc_ameAI::WaypointReached(), npc_emily::npc_emilyAI::WaypointReached(), npc_maghar_captive::npc_maghar_captiveAI::WaypointReached(), npc_kurenai_captive::npc_kurenai_captiveAI::WaypointReached(), and npc_bessy::npc_bessyAI::WaypointReached().
SummonCreature() [2/2]
TempSummon * WorldObject::SummonCreature (uint32 id, float x, float y, float z, float ang = 0, TempSummonType spwtype = TEMPSUMMON_MANUAL_DESPAWN, uint32 despwtime = 0, SummonPropertiesEntry const * properties = nullptr, bool visibleBySummonerOnly = false)
{
    if (!x && !y && !z)
    {
        GetClosePoint(x, y, z, GetObjectSize());
        ang = GetOrientation();
    }
    Position pos;
    pos.Relocate(x, y, z, ang);
    return SummonCreature(id, pos, spwtype, despwtime, 0, properties, visibleBySummonerOnly);
}
References GetClosePoint(), GetObjectSize(), Position::GetOrientation(), Position::Relocate(), and SummonCreature().
SummonCreatureGroup()
void WorldObject::SummonCreatureGroup (uint8 group, std::list< TempSummon * > * list = nullptr)
Summons group of creatures. Should be called only by instances of Creature and GameObject classes.
Parameters
group Id of group to summon.
list List to store pointers to summoned creatures.
{
    ASSERT((IsGameObject() || IsCreature()) && "Only GOs and creatures can summon npc groups!");
    std::vector<TempSummonData> const* data = sObjectMgr->GetSummonGroup(GetEntry(), IsGameObject() ? SUMMONER_TYPE_GAMEOBJECT : SUMMONER_TYPE_CREATURE, group);
    if (!data)
        return;
    for (std::vector<TempSummonData>::const_iterator itr = data->begin(); itr != data->end(); ++itr)
        if (TempSummon* summon = SummonCreature(itr->entry, itr->pos, itr->type, itr->time))
            if (list)
                list->push_back(summon);
}
References ASSERT, Object::GetEntry(), Object::IsCreature(), Object::IsGameObject(), sObjectMgr, SummonCreature(), SUMMONER_TYPE_CREATURE, and SUMMONER_TYPE_GAMEOBJECT.
Referenced by boss_eye_of_cthun::DoAction(), boss_majordomo::boss_majordomoAI::InitializeAI(), boss_taldaram::InitializeAI(), boss_jedoga_shadowseeker::JustEngagedWith(), boss_anub_arak::JustEngagedWith(), npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::JustRespawned(), npc_akama_shade::MovementInform(), npc_hyjal_thrall::OnGossipSelect(), SmartScript::ProcessAction(), boss_apothecary_hummel::boss_apothecary_hummelAI::Reset(), boss_jedoga_shadowseeker::Reset(), boss_hadronox::Reset(), boss_hadronox::SummonCrusherPack(), boss_rend_blackhand::boss_rend_blackhandAI::SummonWave(), npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::UpdateAI(), npc_overlord_drakuru_betrayal::UpdateAI(), and npc_tirions_gambit_tirion::npc_tirions_gambit_tirionAI::UpdateEscortAI().
SummonGameObject()
GameObject * WorldObject::SummonGameObject (uint32 entry, float x, float y, float z, float ang, float rotation0, float rotation1, float rotation2, float rotation3, uint32 respawnTime, bool checkTransport = true, GOSummonType summonType = GO_SUMMON_TIMED_OR_CORPSE_DESPAWN)
{
    if (!IsInWorld())
        return nullptr;
    GameObjectTemplate const* goinfo = sObjectMgr->GetGameObjectTemplate(entry);
    if (!goinfo)
    {
        LOG_ERROR("sql.sql", "Gameobject template {} not found in database!", entry);
        return nullptr;
    }
    Map* map = GetMap();
    GameObject* go = sObjectMgr->IsGameObjectStaticTransport(entry) ? new StaticTransport() : new GameObject();
    if (!go->Create(map->GenerateLowGuid<HighGuid::GameObject>(), entry, map, GetPhaseMask(), x, y, z, ang, G3D::Quat(rotation0, rotation1, rotation2, rotation3), 100, GO_STATE_READY))
    {
        delete go;
        return nullptr;
    }
    go->SetRespawnTime(respawnTime);
    // Xinef: if gameobject is temporary, set custom spellid
    if (respawnTime)
        go->SetSpellId(1);
    if (IsPlayer() || (IsCreature() && summonType == GO_SUMMON_TIMED_OR_CORPSE_DESPAWN)) //not sure how to handle this
        ToUnit()->AddGameObject(go);
    else
        go->SetSpawnedByDefault(false);
    map->AddToMap(go, checkTransport);
    return go;
}
References Unit::AddGameObject(), Map::AddToMap(), GameObject::Create(), GameObject, Map::GenerateLowGuid(), GetMap(), GetPhaseMask(), GO_STATE_READY, GO_SUMMON_TIMED_OR_CORPSE_DESPAWN, Object::IsCreature(), Object::IsInWorld(), Object::IsPlayer(), LOG_ERROR, GameObject::SetRespawnTime(), GameObject::SetSpawnedByDefault(), GameObject::SetSpellId(), sObjectMgr, and Object::ToUnit().
Referenced by boss_freya::boss_freyaAI::DamageTaken(), boss_thorim::boss_thorimAI::DamageTaken(), npc_grand_magister_rommath::npc_grand_magister_rommathAI::DoAction(), instance_obsidian_sanctum::instance_obsidian_sanctum_InstanceMapScript::DoAction(), npc_overlord_drakuru_betrayal::DoAction(), npc_ahune_bunny::DoAction(), npc_medivh_bm::DoAction(), IceTombSummonEvent::Execute(), boss_sartharion_tenebron::boss_sartharion_tenebronAI::ExecuteEvent(), boss_sartharion_shadron::boss_sartharion_shadronAI::ExecuteEvent(), boss_sartharion_vesperon::boss_sartharion_vesperonAI::ExecuteEvent(), npc_anachronos_the_ancient::npc_anachronos_the_ancientAI::HandleAnimation(), HandleBothDead(), spell_gordunni_trap::HandleDummy(), spell_q12014_steady_as_a_rock::HandleFinish(), gobject_commandscript::HandleGameObjectAddTempCommand(), boss_sapphiron::boss_sapphironAI::InitializeAI(), boss_eregos::boss_eregosAI::JustDied(), boss_kologarn::boss_kologarnAI::JustDied(), boss_four_horsemen::boss_four_horsemenAI::JustDied(), spell_pagles_point_cast::OnEffect(), instance_sunken_temple::instance_sunken_temple_InstanceMapScript::OnGameObjectCreate(), npc_zulaman_hostage::OnGossipSelect(), spell_silithyst::OnRemove(), SmartScript::ProcessAction(), npc_brewfest_super_brew_trigger::Reset(), boss_ossirian::Reset(), npc_crystal_spike::Reset(), boss_freya_nature_bomb::boss_freya_nature_bombAI::Reset(), npc_oscillating_frequency_scanner_master_bunny::npc_oscillating_frequency_scanner_master_bunnyAI::Reset(), npc_ulduar_harpoonfirestate::npc_ulduar_harpoonfirestateAI::SetData(), instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::SetData(), instance_ulduar::instance_ulduar_InstanceMapScript::SpawnHodirChests(), boss_ossirian::SpawnNextCrystal(), go_firework_show::SpawnNextFirework(), npc_thrall_bfu::npc_thrall_bfuAI::SpawnWave(), npc_deaths_door_fell_cannon_target_bunny::npc_deaths_door_fell_cannon_target_bunnyAI::SpellHit(), instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::Update(), instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::Update(), npc_thrall_bfu::npc_thrall_bfuAI::UpdateAI(), npc_dark_iron_attack_mole_machine::UpdateAI(), npc_belnistrasz::npc_belnistraszAI::UpdateAI(), npc_pos_leader_second::npc_pos_leader_secondAI::UpdateAI(), boss_sapphiron::boss_sapphironAI::UpdateAI(), npc_alexstrasza::npc_alexstraszaAI::UpdateAI(), boss_algalon_the_observer::boss_algalon_the_observerAI::UpdateAI(), boss_mimiron::boss_mimironAI::UpdateAI(), boss_razorscale::boss_razorscaleAI::UpdateAI(), npc_shandy_dalaran::npc_shandy_dalaranAI::UpdateAI(), npc_still_at_it_trigger::npc_still_at_it_triggerAI::UpdateAI(), npc_grimstone::npc_grimstoneAI::UpdateEscortAI(), brann_bronzebeard::brann_bronzebeardAI::UpdateEscortAI(), npc_tirions_gambit_tirion::npc_tirions_gambit_tirionAI::UpdateEscortAI(), and npc_engineer_helice::npc_engineer_heliceAI::WaypointReached().
SummonTrigger()
Creature * WorldObject::SummonTrigger (float x, float y, float z, float ang, uint32 dur, bool setLevel = false, CreatureAI *(*)(Creature *) GetAI = nullptr)
{
    TempSummonType summonType = (duration == 0) ? TEMPSUMMON_DEAD_DESPAWN : TEMPSUMMON_TIMED_DESPAWN;
    Creature* summon = SummonCreature(WORLD_TRIGGER, x, y, z, ang, summonType, duration);
    if (!summon)
        return nullptr;
    //summon->SetName(GetName());
    if (setLevel && (IsPlayer() || IsCreature()))
    {
        summon->SetFaction(((Unit*)this)->GetFaction());
        summon->SetLevel(((Unit*)this)->GetLevel());
    }
    // Xinef: correctly set phase mask in case of gameobjects
    summon->SetPhaseMask(GetPhaseMask(), false);
    if (GetAI)
        summon->AIM_Initialize(GetAI(summon));
    return summon;
}
References Creature::AIM_Initialize(), GetPhaseMask(), Object::IsCreature(), Object::IsPlayer(), Unit::SetFaction(), Unit::SetLevel(), Unit::SetPhaseMask(), SummonCreature(), TEMPSUMMON_DEAD_DESPAWN, TEMPSUMMON_TIMED_DESPAWN, and WORLD_TRIGGER.
Referenced by GameObject::CastSpell(), boss_kiljaeden::EmpowerOrb(), spell_q10612_10613_the_fel_and_the_furious::HandleScriptEffect(), go_wg_vehicle_teleporter::go_wg_vehicle_teleporterAI::IsValidVehicle(), boss_kologarn_arms::boss_kologarn_armsAI::JustDied(), SmartScript::ProcessAction(), Map::ScriptsProcess(), boss_headless_horseman::UpdateAI(), boss_ymiron::boss_ymironAI::UpdateAI(), go_flames::go_flamesAI::UpdateAI(), and go_heat::go_heatAI::UpdateAI().
Update()
void WorldObject::Update (uint32 diff) virtual
Reimplemented in Pet, MotionTransport, StaticTransport, DynamicObject, GameObject, Creature, TempSummon, Puppet, Player, Totem, and Unit.
{
    m_Events.Update(diff);
    _heartbeatTimer -= Milliseconds(diff);
    while (_heartbeatTimer <= 0ms)
    {
        _heartbeatTimer += HEARTBEAT_INTERVAL;
        Heartbeat();
    }
    sScriptMgr->OnWorldObjectUpdate(this, diff);
}
References _heartbeatTimer, Object::Heartbeat(), HEARTBEAT_INTERVAL, m_Events, sScriptMgr, and EventProcessor::Update().
Referenced by GameObject::Update(), Unit::Update(), and Map::UpdateNonPlayerObjects().
UpdateAllowedPositionZ()
void WorldObject::UpdateAllowedPositionZ (float x, float y, float & z, float * groundZ = nullptr) const
{
    if (GetTransport())
    {
        if (groundZ)
            *groundZ = z;
        return;
    }
    if (Unit const* unit = ToUnit())
    {
        if (!unit->CanFly())
        {
            Creature const* c = unit->ToCreature();
            bool canSwim = c ? c->CanSwim() : true;
            float ground_z = z;
            float max_z;
            if (canSwim)
                max_z = GetMapWaterOrGroundLevel(x, y, z, &ground_z);
            else
                max_z = ground_z = GetMapHeight(x, y, z);
            if (max_z > INVALID_HEIGHT)
            {
                if (canSwim && unit->GetMap()->IsInWater(unit->GetPhaseMask(), x, y, max_z - Z_OFFSET_FIND_HEIGHT, unit->GetCollisionHeight()))
                {
                    // do not allow creatures to walk on
                    // water level while swimming
                    max_z = std::max(max_z - GetMinHeightInWater(), ground_z);
                }
                else
                {
                    // hovering units cannot go below their hover height
                    float hoverOffset = unit->GetHoverHeight();
                    max_z += hoverOffset;
                    ground_z += hoverOffset;
                }
                if (z > max_z)
                    z = max_z;
                else if (z < ground_z)
                    z = ground_z;
            }
            if (groundZ)
                *groundZ = ground_z;
        }
        else
        {
            float ground_z = GetMapHeight(x, y, z) + unit->GetHoverHeight();
            if (z < ground_z)
                z = ground_z;
            if (groundZ)
               *groundZ = ground_z;
        }
    }
    else
    {
        float ground_z = GetMapHeight(x, y, z);
        if (ground_z > INVALID_HEIGHT)
            z = ground_z;
        if (groundZ)
            *groundZ = ground_z;
    }
}
References Creature::CanSwim(), GetMapHeight(), GetMapWaterOrGroundLevel(), GetMinHeightInWater(), GetTransport(), INVALID_HEIGHT, Object::ToCreature(), Object::ToUnit(), and Z_OFFSET_FIND_HEIGHT.
Referenced by RandomMovementGenerator< T >::_setRandomLocation(), HomeMovementGenerator< Creature >::_setTargetLocation(), Map::CheckCollisionAndGetValidCoords(), ChaseMovementGenerator< T >::DispatchSplineToPosition(), GetContactPoint(), GetNearPoint(), Unit::GetRandomContactPoint(), PathGenerator::NormalizePath(), CharmInfo::SaveStayPosition(), spell_valanar_kinetic_bomb_summon::SelectDest(), Unit::SetHover(), and WaypointMovementGenerator< Creature >::StartMove().
UpdateGroundPositionZ()
void WorldObject::UpdateGroundPositionZ (float x, float y, float & z) const
{
    float new_z = GetMapHeight(x, y, z);
    if (new_z > INVALID_HEIGHT)
        z = new_z + (IsUnit() ? static_cast<Unit const*>(this)->GetHoverHeight() : 0.0f);
}
References GetMapHeight(), INVALID_HEIGHT, and Object::IsUnit().
Referenced by IceTombSummonEvent::Execute(), GetChargeContactPoint(), GetRandomPoint(), npc_lk_spirit_bomb::npc_lk_spirit_bombAI::IsSummonedBy(), CreatureGroup::LeaderMoveTo(), MovePosition(), spell_putricide_slime_puddle_spawn::SelectDest(), spell_sindragosa_s_fury::SelectDest(), npc_necrotic_shard::SummonCultists(), and boss_sindragosa::boss_sindragosaAI::UpdateAI().
UpdateObjectVisibility()
void WorldObject::UpdateObjectVisibility (bool forced = true, bool fromUpdate = false) virtual
Reimplemented in Player, and Unit.
{
    //updates object's visibility for nearby players
    Acore::VisibleChangesNotifier notifier(*this);
    Cell::VisitObjects(this, notifier, GetVisibilityRange());
}
References GetVisibilityRange(), and Cell::VisitObjects().
Referenced by Map::DynamicObjectRelocation(), Map::GameObjectRelocation(), SetPhaseMask(), GameObject::SetRespawnTime(), GameObject::Update(), Unit::UpdateObjectVisibility(), UpdateObjectVisibilityOnCreate(), and TempSummon::UpdateObjectVisibilityOnCreate().
UpdateObjectVisibilityOnCreate()
virtual void WorldObject::UpdateObjectVisibilityOnCreate () inline virtual
Reimplemented in TempSummon.
{ UpdateObjectVisibility(true); }
References UpdateObjectVisibility().
UpdatePositionData()
void WorldObject::UpdatePositionData ()
{
    _updatePositionData = false;
    PositionFullTerrainStatus data;
    GetMap()->GetFullTerrainStatusForPosition(GetPhaseMask(), GetPositionX(), GetPositionY(), GetPositionZ(), GetCollisionHeight(), data);
    ProcessPositionDataChanged(data);
}
References _updatePositionData, GetCollisionHeight(), Map::GetFullTerrainStatusForPosition(), GetMap(), GetPhaseMask(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), and ProcessPositionDataChanged().
Referenced by Map::ConvertCorpseToBones(), GameObject::Create(), StaticTransport::Create(), Pet::CreateBaseAtCreature(), Pet::CreateBaseAtCreatureInfo(), Player::CreateCorpse(), DynamicObject::CreateDynamicObject(), Map::CreatureRelocation(), GetAreaId(), GetFloorZ(), GetLiquidData(), GetZoneAndAreaId(), GetZoneId(), WorldSession::HandleMoveWorldportAck(), IsOutdoors(), Map::LoadCorpseData(), Player::LoadFromDB(), Pet::LoadPetFromDB(), Map::PlayerRelocation(), and SetPositionDataUpdate().
Member Data Documentation
_allowedLooters
GuidUnorderedSet WorldObject::_allowedLooters private
Referenced by AddAllowedLooter(), GetAllowedLooters(), HasAllowedLooter(), RemoveAllowedLooter(), ResetAllowedLooters(), and SetAllowedLooters().
_areaId
uint32 WorldObject::_areaId protected
Referenced by AddToWorld(), GetAreaId(), GetZoneAndAreaId(), and ProcessPositionDataChanged().
_floorZ
float WorldObject::_floorZ protected
Referenced by GetFloorZ(), and ProcessPositionDataChanged().
_heartbeatTimer
Milliseconds WorldObject::_heartbeatTimer private
Referenced by Update().
_liquidData
LiquidData WorldObject::_liquidData protected
Referenced by GetLiquidData(), and ProcessPositionDataChanged().
_objectVisibilityContainer
ObjectVisibilityContainer WorldObject::_objectVisibilityContainer private
Referenced by GetObjectVisibilityContainer(), and GetObjectVisibilityContainer().
_outdoors
bool WorldObject::_outdoors protected
Referenced by IsOutdoors(), and ProcessPositionDataChanged().
_updatePositionData
bool WorldObject::_updatePositionData protected
Referenced by GetAreaId(), GetFloorZ(), GetLiquidData(), GetZoneAndAreaId(), GetZoneId(), IsOutdoors(), SetPositionDataUpdate(), and UpdatePositionData().
_visibilityDistanceOverrideType
VisibilityDistanceType WorldObject::_visibilityDistanceOverrideType protected
Referenced by GetVisibilityOverrideDistance(), GetVisibilityOverrideType(), IsFarVisible(), IsVisibilityOverridden(), IsZoneWideVisible(), and SetVisibilityDistanceOverride().
_zoneId
uint32 WorldObject::_zoneId protected
Referenced by AddToMapVisibilityOverrideContainers(), AddToWorld(), GetZoneAndAreaId(), GetZoneId(), ProcessPositionDataChanged(), and RemoveFromMapVisibilityOverrideContainers().
ALEEvents
ALEEventProcessor* WorldObject::ALEEvents
LastUsedScriptID
uint32 WorldObject::LastUsedScriptID
Referenced by Creature::Create(), GameObject::Create(), StaticTransport::Create(), WorldSession::HandleGossipSelectOptionOpcode(), and instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnCreatureCreate().
m_currMap
Map* WorldObject::m_currMap private
Referenced by FindMap(), GetMap(), ResetMap(), and SetMap().
m_Events
EventProcessor WorldObject::m_Events
Referenced by Unit::_ExitVehicle(), at_hol_hall_of_watchers::_OnTrigger(), BossAI::_Reset(), npc_q24545_wretched_ghoul::npc_q24545_wretched_ghoulAI::Activate(), CharmInfo::AddSpellToActionBar(), Spell::AddUnitTarget(), spell_sindragosa_ice_tomb_trap_aura::AfterApply(), Creature::CallAssistance(), boss_krik_thir::boss_krik_thirAI::CallWatcher(), boss_high_nethermancer_zerevor::CastDampenMagicIfPossible(), Unit::CastDelayedSpellWithPeriodicAmount(), boss_murmur::CastSuppressionOOC(), CleanupsBeforeDelete(), boss_romulo::DamageTaken(), boss_muru::DamageTaken(), boss_felblood_kaelthas::DamageTaken(), boss_the_lich_king::boss_the_lich_kingAI::DamageTaken(), npc_q24545_wretched_ghoul::npc_q24545_wretched_ghoulAI::DoAction(), boss_julianne::DoAction(), boss_baltharus_the_warborn::boss_baltharus_the_warbornAI::DoAction(), boss_prince_keleseth_icc::boss_prince_kelesethAI::DoAction(), boss_prince_taldaram_icc::boss_prince_taldaramAI::DoAction(), boss_prince_valanar_icc::boss_prince_valanarAI::DoAction(), boss_sindragosa::boss_sindragosaAI::DoAction(), npc_spinestalker::npc_spinestalkerAI::DoAction(), npc_rimefang::npc_rimefangAI::DoAction(), npc_green_dragon_combat_trigger::npc_green_dragon_combat_triggerAI::DoAction(), boss_felblood_kaelthas::DoAction(), boss_akilzon::DoAction(), boss_cthun::DoAction(), boss_krik_thir::boss_krik_thirAI::DoAction(), boss_kalecgos::DoAction(), boss_illidan_stormrage::DoAction(), npc_akama_illidan::DoAction(), npc_maiev_illidan::DoAction(), npc_blade_of_azzinoth::DoAction(), boss_ouro::Emerge(), boss_illidan_stormrage::EnterEvadeMode(), boss_zuljin::EnterPhase(), SpellEvent::Execute(), BattleExperienceEvent::Execute(), UtherBatteredHiltEvent::Execute(), TriggerWickedSpirit::Execute(), lapseTeleport::Execute(), PartyTimeEmoteEvent::Execute(), npc_xt002_boombot::npc_xt002_boombotAI::Explode(), Creature::ForcedDespawn(), spell_item_party_time::HandleEffectApply(), spell_chapter2_persuasive_strike::HandleHit(), spell_alar_flame_quills::HandlePeriodic(), WorldSession::HandlePlayerLoginFromDB(), spell_ayamiss_swarmer_teleport_trigger::HandleScript(), boss_akilzon::HandleStormSequence(), boss_kiljaeden::InitializeAI(), boss_ambassador_hellmaw::InitializeAI(), npc_pet_mage_mirror_image::InitializeAI(), Totem::InitSummon(), npc_blade_of_azzinoth::IsSummonedBy(), npc_flame_of_azzinoth::IsSummonedBy(), npc_demonic_vapor::IsSummonedBy(), npc_maiev_illidan::IsSummonedBy(), boss_akilzon::JustDied(), npc_swarm_scarab::npc_swarm_scarabAI::JustDied(), npc_nerubian_burrower::npc_nerubian_burrowerAI::JustDied(), npc_gunship::npc_gunshipAI::JustDied(), npc_xt002_boombot::npc_xt002_boombotAI::JustDied(), npc_q24545_wretched_ghoul::npc_q24545_wretched_ghoulAI::JustDied(), boss_felmyst::JustDied(), boss_mother_shahraz::JustDied(), boss_najentus::JustDied(), boss_akilzon::JustEngagedWith(), boss_zuljin::JustEngagedWith(), boss_loken::JustEngagedWith(), boss_keleseth::JustEngagedWith(), npc_flame_of_azzinoth::JustEngagedWith(), boss_essence_of_suffering::boss_essence_of_sufferingAI::JustEngagedWith(), boss_swamplord_muselek::JustEngagedWith(), boss_felmyst::JustEngagedWith(), boss_muru::JustEngagedWith(), boss_janalai::JustEngagedWith(), boss_krik_thir::boss_krik_thirAI::JustEngagedWith(), boss_novos::JustEngagedWith(), boss_anubrekhan::boss_anubrekhanAI::JustEngagedWith(), boss_murmur::JustEngagedWith(), boss_gurtogg_bloodboil::JustEngagedWith(), boss_illidan_stormrage::JustEngagedWith(), boss_mother_shahraz::JustEngagedWith(), boss_najentus::JustEngagedWith(), boss_hydross_the_unstable::JustEngagedWith(), npc_akama_illidan::JustReachedHome(), npc_kiljaeden_controller::JustSummoned(), boss_kiljaeden::JustSummoned(), boss_hazzarah::JustSummoned(), boss_baltharus_the_warborn::boss_baltharus_the_warbornAI::JustSummoned(), boss_drakkari_colossus::boss_drakkari_colossusAI::JustSummoned(), boss_prince_valanar_icc::boss_prince_valanarAI::JustSummoned(), boss_sindragosa::boss_sindragosaAI::JustSummoned(), boss_the_lich_king::boss_the_lich_kingAI::JustSummoned(), boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI::JustSummoned(), npc_risen_archmage::npc_risen_archmageAI::JustSummoned(), boss_algalon_the_observer::boss_algalon_the_observerAI::JustSummoned(), boss_reliquary_of_souls::boss_reliquary_of_soulsAI::JustSummoned(), boss_krik_thir::boss_krik_thirAI::KilledUnit(), boss_gurtogg_bloodboil::KilledUnit(), boss_illidan_stormrage::KilledUnit(), boss_essence_of_suffering::boss_essence_of_sufferingAI::KilledUnit(), boss_essence_of_desire::boss_essence_of_desireAI::KilledUnit(), boss_essence_of_anger::boss_essence_of_angerAI::KilledUnit(), Creature::ModifyThreatPercentTemp(), boss_ebonroc::boss_ebonrocAI::MovementInform(), npc_koltira_deathweaver::npc_koltira_deathweaverAI::MovementInform(), boss_zuljin::MovementInform(), boss_captain_skarloc::MovementInform(), boss_ayamiss::MovementInform(), boss_illidan_stormrage::MovementInform(), npc_akama_illidan::MovementInform(), boss_essence_of_suffering::boss_essence_of_sufferingAI::MovementInform(), boss_essence_of_desire::boss_essence_of_desireAI::MovementInform(), boss_felmyst::MovementInform(), gunship_npc_AI::MovementInform(), npc_gunship_boarding_addAI::MovementInform(), boss_ghazan::MovementInform(), spell_halion_twilight_realm_aura::OnApply(), boss_taldaram::OnAuraRemove(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnCreatureCreate(), go_main_chambers_access_panel::OnGossipHello(), spell_halion_leave_twilight_realm_aura::OnRemove(), spell_q12937_relief_for_the_fallen::OnRemove(), at_cthun_stomach_exit::OnTrigger(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnUnitDeath(), boss_anetheron::PathEndReached(), boss_rage_winterchill::PathEndReached(), npc_hyjal_ground_trash::PathEndReached(), npc_hyjal_frost_wyrm::PathEndReached(), boss_ambassador_hellmaw::PathEndReached(), npc_akama_illidan::PathEndReached(), npc_hyjal_gargoyle::PathEndReached(), npc_hive_zara_swarmer::PathEndReached(), boss_reliquary_of_souls::boss_reliquary_of_soulsAI::PhaseTransitionSpawns(), Spell::prepare(), SmartScript::ProcessAction(), Spell::RecalculateDelayMomentForDst(), boss_vexallus::Reset(), npc_koltira_deathweaver::npc_koltira_deathweaverAI::Reset(), boss_brutallus::Reset(), boss_kiljaeden::Reset(), boss_muru::Reset(), boss_entropius::Reset(), npc_dark_fiend::Reset(), npc_singularity::Reset(), boss_akilzon::Reset(), boss_janalai::Reset(), boss_zuljin::Reset(), boss_anubrekhan::boss_anubrekhanAI::Reset(), boss_runemaster_molgeim::boss_runemaster_molgeimAI::Reset(), boss_illidan_stormrage::Reset(), npc_akama_illidan::Reset(), npc_maiev_illidan::Reset(), boss_mother_shahraz::Reset(), boss_najentus::Reset(), boss_alar::Reset(), NPCStaveQuestAI::ResetState(), boss_alar::ScheduleAbilities(), boss_illidan_stormrage::ScheduleAbilities(), BossAI::ScheduleEnrageTimer(), boss_gal_darah::ScheduleEvents(), boss_loken::ScheduleTasks(), npc_gunship_boarding_addAI::SetData(), boss_gal_darah::SpellHit(), npc_koltira_deathweaver::npc_koltira_deathweaverAI::StartEvent(), boss_felmyst::StartIntro(), npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::SummonedCreatureDies(), boss_hydross_the_unstable::SummonMovementInform(), boss_hydross_the_unstable::SummonTaintedElementalOOC(), boss_krik_thir::boss_krik_thirAI::SummonWatcher(), CreatureAI::Talk(), TempSummon::UnSummon(), Totem::UnSummon(), spell_illidari_council_deadly_strike_aura::Update(), Update(), npc_kalecgos_kj::UpdateAI(), boss_anomalus::UpdateAI(), and npc_dark_fiend::UpdateAI().
m_executed_notifies
uint16 WorldObject::m_executed_notifies private
Referenced by NotifyExecuted(), ResetAllNotifies(), and SetNotified().
m_InstanceId
uint32 WorldObject::m_InstanceId private
Referenced by GetInstanceId(), SetLocationInstanceId(), and SetMap().
m_invisibility
FlaggedValuesArray32<int32, uint32, InvisibilityType, TOTAL_INVISIBILITY_TYPES> WorldObject::m_invisibility
Referenced by CanDetectInvisibilityOf(), CanSeeOrDetect(), GameObject::Create(), StaticTransport::Create(), and AuraEffect::HandleModInvisibility().
m_invisibilityDetect
FlaggedValuesArray32<int32, uint32, InvisibilityType, TOTAL_INVISIBILITY_TYPES> WorldObject::m_invisibilityDetect
Referenced by CanDetectInvisibilityOf(), AuraEffect::HandleModInvisibilityDetect(), and Player::UpdateInvisibilityDrunkDetect().
m_isActive
bool WorldObject::m_isActive protected
Referenced by isActiveObject(), Player::Player(), and setActive().
m_movementInfo
MovementInfo WorldObject::m_movementInfo
Referenced by _IsWithinDist(), Unit::AddExtraUnitMovementFlag(), Vehicle::AddPassenger(), MotionTransport::AddPassenger(), StaticTransport::AddPassenger(), Unit::AddUnitMovementFlag(), Unit::BuildMovementPacket(), Object::BuildMovementUpdate(), WorldSession::BuildPartyMemberStatsChangedPacket(), Player::CanFly(), DynamicObject::CleanupsBeforeDelete(), GameObject::CleanupsBeforeDelete(), MotionTransport::CleanupsBeforeDelete(), StaticTransport::CleanupsBeforeDelete(), Unit::CleanupsBeforeDelete(), MotionTransport::CreateGOPassenger(), MotionTransport::CreateNPCPassenger(), MotionTransport::DelayedTeleportTransport(), Unit::DisableSpline(), npc_escortAI::GenerateWaypointArray(), SmartAI::GenerateWayPointArray(), Unit::GetExtraUnitMovementFlags(), GetTransOffsetO(), GetTransOffsetX(), GetTransOffsetY(), GetTransOffsetZ(), GetTransSeat(), GetTransTime(), Unit::GetUnitMovementFlags(), WorldSession::HandleChangeSeatsOnControlledVehicle(), misc_commandscript::HandleGPSCommand(), WorldSession::HandleMoveFlagChangeOpcode(), WorldSession::HandleMoveKnockBackAck(), WorldSession::HandleMoveNotActiveMover(), WorldSession::HandleMoveRootAck(), WorldSession::HandleMoverRelocation(), WorldSession::HandleMoveSplineDoneOpcode(), WorldSession::HandleMoveTimeSkippedOpcode(), WorldSession::HandleMoveWorldportAck(), WorldSession::HandlePlayerLoginFromDB(), WorldSession::HandlePlayerLoginToCharInWorld(), WorldSession::HandleRequestPartyMemberStatsOpcode(), Unit::HasExtraUnitMovementFlag(), Unit::HasLeewayMovement(), Unit::HasUnitMovementFlag(), Unit::IsFalling(), Unit::IsFlying(), Creature::IsFreeToMove(), Unit::IsHovering(), Unit::IsLevitating(), Unit::isMoving(), Unit::IsRooted(), Unit::isSwimming(), Unit::isTurning(), Unit::IsWalking(), Movement::MoveSplineInit::Launch(), Player::LoadFromDB(), MotionMaster::MoveFall(), Movement::MoveSplineInit::MoveSplineInit(), FollowMovementGenerator< T >::PositionOkay(), PredictPosition(), WorldSession::ProcessMovementInfo(), spell_igb_teleport_to_enemy_ship::RelocateTransportOffset(), Unit::RemoveExtraUnitMovementFlag(), Vehicle::RemovePassenger(), MotionTransport::RemovePassenger(), StaticTransport::RemovePassenger(), Unit::RemoveUnitMovementFlag(), Unit::SendMoveRoot(), Unit::SetCanFly(), Unit::SetDisableGravity(), Unit::SetExtraUnitMovementFlags(), Unit::SetFeatherFall(), Unit::SetHover(), Unit::SetUnitMovementFlags(), Unit::SetWaterWalking(), Movement::MoveSplineInit::Stop(), Player::TeleportTo(), Creature::UpdateMovementFlags(), StaticTransport::UpdatePassengerPositions(), MotionTransport::UpdatePassengerPositions(), and Unit::UpdateSplinePosition().
m_name
std::string WorldObject::m_name protected
Referenced by Player::_LoadGlyphAuras(), Player::Create(), GetName(), GetNameForLocaleIdx(), Player::LoadFromDB(), Pet::Pet(), Player::SaveToDB(), and SetName().
m_notifyflags
uint16 WorldObject::m_notifyflags private
Referenced by AddToNotify(), GetNotifyFlags(), isNeedNotify(), RemoveFromNotify(), and ResetAllNotifies().
m_phaseMask
uint32 WorldObject::m_phaseMask private
Referenced by GetPhaseMask(), and SetPhaseMask().
m_serverSideVisibility
FlaggedValuesArray32<int32, uint32, ServerSideVisibilityType, TOTAL_SERVERSIDE_VISIBILITY_TYPES> WorldObject::m_serverSideVisibility
Referenced by CanSeeOrDetect(), Creature::Create(), AuraEffect::HandleAuraGhost(), Unit::IsVisible(), Player::SetServerSideVisibility(), Unit::SetVisible(), Unit::Unit(), and WorldObject().
m_serverSideVisibilityDetect
FlaggedValuesArray32<int32, uint32, ServerSideVisibilityType, TOTAL_SERVERSIDE_VISIBILITY_TYPES> WorldObject::m_serverSideVisibilityDetect
Referenced by CanSeeOrDetect(), Creature::Create(), AuraEffect::HandleAuraGhost(), Player::SetServerSideVisibilityDetect(), and WorldObject().
m_stealth
FlaggedValuesArray32<int32, uint32, StealthType, TOTAL_STEALTH_TYPES> WorldObject::m_stealth
Referenced by CanDetectStealthOf(), CanSeeOrDetect(), GameObject::Create(), AuraEffect::HandleModStealth(), and AuraEffect::HandleModStealthLevel().
m_stealthDetect
FlaggedValuesArray32<int32, uint32, StealthType, TOTAL_STEALTH_TYPES> WorldObject::m_stealthDetect
Referenced by CanDetectStealthOf(), and AuraEffect::HandleModStealthDetect().
m_transport
Transport* WorldObject::m_transport protected
Referenced by _IsWithinDist(), GetTransport(), WorldSession::HandleMoveWorldportAck(), WorldSession::HandlePlayerLoginFromDB(), Player::LoadFromDB(), SetTransport(), and Player::TeleportTo().
m_useCombinedPhases
bool WorldObject::m_useCombinedPhases private
Referenced by InSamePhase(), and SetPhaseMask().
m_zoneScript
ZoneScript* WorldObject::m_zoneScript protected
Referenced by GameObject::AddToWorld(), ClearZoneScript(), GameObject::Create(), StaticTransport::Create(), TransportMgr::CreateTransport(), GameObject::EventInform(), GetZoneScript(), GameObject::RemoveFromWorld(), and SetZoneScript().
The documentation for this class was generated from the following files:
azerothcore-wotlk/src/server/game/Entities/Object/Object.h
azerothcore-wotlk/src/server/game/Entities/Object/Object.cpp