AzerothCore Doxygen
LuaGlobalFunctions Namespace Reference
Functions
int GetLuaEngine (lua_State *L)
int GetCoreName (lua_State *L)
int GetRealmID (lua_State *L)
int GetCoreVersion (lua_State *L)
int GetCoreExpansion (lua_State *L)
int GetStateMap (lua_State *L)
int GetStateMapId (lua_State *L)
int GetStateInstanceId (lua_State *L)
int GetQuest (lua_State *L)
int GetPlayerByGUID (lua_State *L)
int GetPlayerByName (lua_State *L)
int GetGameTime (lua_State *L)
int GetPlayersInWorld (lua_State *L)
int GetGuildByName (lua_State *L)
int GetMapById (lua_State *L)
int GetGuildByLeaderGUID (lua_State *L)
int GetPlayerCount (lua_State *L)
int GetPlayerGUID (lua_State *L)
int GetItemGUID (lua_State *L)
int GetItemTemplate (lua_State *L)
int GetObjectGUID (lua_State *L)
int GetUnitGUID (lua_State *L)
int GetGUIDLow (lua_State *L)
int GetItemLink (lua_State *L)
int GetGUIDType (lua_State *L)
int GetGUIDEntry (lua_State *L)
int GetAreaName (lua_State *L)
int GetActiveGameEvents (lua_State *L)
static int RegisterEntryHelper (lua_State *L, int regtype)
static int RegisterEventHelper (lua_State *L, int regtype)
static int RegisterUniqueHelper (lua_State *L, int regtype)
int RegisterServerEvent (lua_State *L)
int RegisterPlayerEvent (lua_State *L)
int RegisterGuildEvent (lua_State *L)
int RegisterGroupEvent (lua_State *L)
int RegisterBGEvent (lua_State *L)
int RegisterPacketEvent (lua_State *L)
int RegisterCreatureGossipEvent (lua_State *L)
int RegisterGameObjectGossipEvent (lua_State *L)
int RegisterItemEvent (lua_State *L)
int RegisterItemGossipEvent (lua_State *L)
int RegisterMapEvent (lua_State *L)
int RegisterInstanceEvent (lua_State *L)
int RegisterPlayerGossipEvent (lua_State *L)
int RegisterCreatureEvent (lua_State *L)
int RegisterUniqueCreatureEvent (lua_State *L)
int RegisterGameObjectEvent (lua_State *L)
int ReloadEluna (lua_State *)
int RunCommand (lua_State *L)
int SendWorldMessage (lua_State *L)
template<typename T >
static int DBQueryAsync (lua_State *L, DatabaseWorkerPool< T > &db)
int WorldDBQuery (lua_State *L)
int WorldDBQueryAsync (lua_State *L)
int WorldDBExecute (lua_State *L)
int CharDBQuery (lua_State *L)
int CharDBQueryAsync (lua_State *L)
int CharDBExecute (lua_State *L)
int AuthDBQuery (lua_State *L)
int AuthDBQueryAsync (lua_State *L)
int AuthDBExecute (lua_State *L)
int CreateLuaEvent (lua_State *L)
int RemoveEventById (lua_State *L)
int RemoveEvents (lua_State *L)
int PerformIngameSpawn (lua_State *L)
int CreatePacket (lua_State *L)
int AddVendorItem (lua_State *L)
int VendorRemoveItem (lua_State *L)
int VendorRemoveAllItems (lua_State *L)
int Kick (lua_State *L)
int Ban (lua_State *L)
int SaveAllPlayers (lua_State *)
int SendMail (lua_State *L)
int bit_and (lua_State *L)
int bit_or (lua_State *L)
int bit_lshift (lua_State *L)
int bit_rshift (lua_State *L)
int bit_xor (lua_State *L)
int bit_not (lua_State *L)
int AddTaxiPath (lua_State *L)
int IsCompatibilityMode (lua_State *L)
int IsInventoryPos (lua_State *L)
int IsEquipmentPos (lua_State *L)
int IsBankPos (lua_State *L)
int IsBagPos (lua_State *L)
int IsGameEventActive (lua_State *L)
int GetCurrTime (lua_State *L)
int GetTimeDiff (lua_State *L)
static std::string GetStackAsString (lua_State *L)
int PrintInfo (lua_State *L)
int PrintError (lua_State *L)
int PrintDebug (lua_State *L)
int StartGameEvent (lua_State *L)
int StopGameEvent (lua_State *L)
int HttpRequest (lua_State *L)
int CreateLongLong (lua_State *L)
int CreateULongLong (lua_State *L)
int ClearBattleGroundEvents (lua_State *L)
int ClearCreatureEvents (lua_State *L)
int ClearUniqueCreatureEvents (lua_State *L)
int ClearCreatureGossipEvents (lua_State *L)
int ClearGameObjectEvents (lua_State *L)
int ClearGameObjectGossipEvents (lua_State *L)
int ClearGroupEvents (lua_State *L)
int ClearGuildEvents (lua_State *L)
int ClearItemEvents (lua_State *L)
int ClearItemGossipEvents (lua_State *L)
int ClearPacketEvents (lua_State *L)
int ClearPlayerEvents (lua_State *L)
int ClearPlayerGossipEvents (lua_State *L)
int ClearServerEvents (lua_State *L)
int ClearMapEvents (lua_State *L)
int ClearInstanceEvents (lua_State *L)
Function Documentation
AddTaxiPath()
int LuaGlobalFunctions::AddTaxiPath (lua_State * L)
Adds a taxi path to a specified map, returns the used pathId.
Note that the first taxi point needs to be near the player when he starts the taxi path. The function should also be used only once per path added so use it on server startup for example.
Related function: [Player:StartTaxi]
-- Execute on startup
local pathTable = {{mapid, x, y, z}, {mapid, x, y, z}}
local path = AddTaxiPath(pathTable, 28135, 28135)
-- Execute when the player should fly
player:StartTaxi(path)
Parameters
table waypoints : table containing waypoints: {map, x, y, z[, actionFlag, delay]}
uint32 mountA : alliance [Creature] entry
uint32 mountH : horde [Creature] entry
uint32 price = 0 : price of the taxi path
uint32 pathId = 0 : path Id of the taxi path
Returns
uint32 actualPathId
    {
        luaL_checktype(L, 1, LUA_TTABLE);
        uint32 mountA = Eluna::CHECKVAL<uint32>(L, 2);
        uint32 mountH = Eluna::CHECKVAL<uint32>(L, 3);
        uint32 price = Eluna::CHECKVAL<uint32>(L, 4, 0);
        uint32 pathId = Eluna::CHECKVAL<uint32>(L, 5, 0);
        lua_pushvalue(L, 1);
        // Stack: {nodes}, mountA, mountH, price, pathid, {nodes}
        std::list<TaxiPathNodeEntry> nodes;
        int start = lua_gettop(L);
        int end = start;
        Eluna::Push(L);
        // Stack: {nodes}, mountA, mountH, price, pathid, {nodes}, nil
        while (lua_next(L, -2) != 0)
        {
            // Stack: {nodes}, mountA, mountH, price, pathid, {nodes}, key, value
            luaL_checktype(L, -1, LUA_TTABLE);
            Eluna::Push(L);
            // Stack: {nodes}, mountA, mountH, price, pathid, {nodes}, key, value, nil
            while (lua_next(L, -2) != 0)
            {
                // Stack: {nodes}, mountA, mountH, price, pathid, {nodes}, key, value, key2, value2
                lua_insert(L, end++);
                // Stack: {nodes}, mountA, mountH, price, pathid, {nodes}, value2, key, value, key2
            }
            // Stack: {nodes}, mountA, mountH, price, pathid, {nodes}, value2, key, value
            if (start == end)
                continue;
            if (end - start < 4) // no mandatory args, dont add
                return luaL_argerror(L, 1, "all waypoints do not have mandatory arguments");
            while (end - start < 8) // fill optional args with 0
            {
                Eluna::Push(L, 0);
                lua_insert(L, end++);
                // Stack: {nodes}, mountA, mountH, price, pathid, {nodes}, node, key, value
            }
            TaxiPathNodeEntry entry;
#ifdef TRINITY
            // mandatory
            entry.ContinentID = Eluna::CHECKVAL<uint32>(L, start);
            entry.Loc.X = Eluna::CHECKVAL<float>(L, start + 1);
            entry.Loc.Y = Eluna::CHECKVAL<float>(L, start + 2);
            entry.Loc.Z = Eluna::CHECKVAL<float>(L, start + 3);
            // optional
            entry.Flags = Eluna::CHECKVAL<uint32>(L, start + 4, 0);
            entry.Delay = Eluna::CHECKVAL<uint32>(L, start + 5, 0);
#else
            // mandatory
            entry.mapid = Eluna::CHECKVAL<uint32>(L, start);
            entry.x = Eluna::CHECKVAL<float>(L, start + 1);
            entry.y = Eluna::CHECKVAL<float>(L, start + 2);
            entry.z = Eluna::CHECKVAL<float>(L, start + 3);
            // optional
            entry.actionFlag = Eluna::CHECKVAL<uint32>(L, start + 4, 0);
            entry.delay = Eluna::CHECKVAL<uint32>(L, start + 5, 0);
#endif
            nodes.push_back(entry);
            while (end != start) // remove args
                if (!lua_isnone(L, --end))
                    lua_remove(L, end);
            // Stack: {nodes}, mountA, mountH, price, pathid, {nodes}, key, value
            lua_pop(L, 1);
            // Stack: {nodes}, mountA, mountH, price, pathid, {nodes}, key
        }
        // Stack: {nodes}, mountA, mountH, price, pathid, {nodes}
        lua_pop(L, 1);
        // Stack: {nodes}, mountA, mountH, price, pathid
        if (nodes.size() < 2)
            return 1;
        if (!pathId)
            pathId = sTaxiPathNodesByPath.size();
        if (sTaxiPathNodesByPath.size() <= pathId)
            sTaxiPathNodesByPath.resize(pathId + 1);
        sTaxiPathNodesByPath[pathId].clear();
        sTaxiPathNodesByPath[pathId].resize(nodes.size());
        static uint32 nodeId = 500;
        uint32 startNode = nodeId;
        uint32 index = 0;
        for (std::list<TaxiPathNodeEntry>::iterator it = nodes.begin(); it != nodes.end(); ++it)
        {
            TaxiPathNodeEntry& entry = *it;
            TaxiNodesEntry* nodeEntry = new TaxiNodesEntry();
#ifdef TRINITY
            entry.PathID = pathId;
            entry.NodeIndex = nodeId;
            nodeEntry->ID = index;
            nodeEntry->ContinentID = entry.ContinentID;
            nodeEntry->Pos.X = entry.Loc.X;
            nodeEntry->Pos.Y = entry.Loc.Y;
            nodeEntry->Pos.Z = entry.Loc.Z;
            nodeEntry->MountCreatureID[0] = mountH;
            nodeEntry->MountCreatureID[1] = mountA;
            sTaxiNodesStore.SetEntry(nodeId++, nodeEntry);
            sTaxiPathNodesByPath[pathId][index++] = new TaxiPathNodeEntry(entry);
#else
            entry.path = pathId;
            entry.index = nodeId;
            nodeEntry->ID = index;
            nodeEntry->map_id = entry.mapid;
            nodeEntry->x = entry.x;
            nodeEntry->y = entry.y;
            nodeEntry->z = entry.z;
            nodeEntry->MountCreatureID[0] = mountH;
            nodeEntry->MountCreatureID[1] = mountA;
            sTaxiNodesStore.SetEntry(nodeId++, nodeEntry);
#ifndef AZEROTHCORE
            sTaxiPathNodesByPath[pathId].set(index++, new TaxiPathNodeEntry(entry));
#else
            sTaxiPathNodesByPath[pathId][index++] = new TaxiPathNodeEntry(entry);
#endif
#endif
        }
        if (startNode >= nodeId)
            return 1;
#ifndef AZEROTHCORE
        sTaxiPathSetBySource[startNode][nodeId - 1] = TaxiPathBySourceAndDestination(pathId, price);
#endif
        TaxiPathEntry* pathEntry = new TaxiPathEntry();
#ifdef TRINITY
        pathEntry->FromTaxiNode = startNode;
        pathEntry->ToTaxiNode = nodeId - 1;
        pathEntry->Cost = price;
#else
        pathEntry->from = startNode;
        pathEntry->to = nodeId - 1;
        pathEntry->price = price;
#endif
        pathEntry->ID = pathId;
        sTaxiPathStore.SetEntry(pathId, pathEntry);
#ifdef AZEROTHCORE
        sTaxiPathSetBySource[startNode][nodeId - 1] = pathEntry;
#endif
        Eluna::Push(L, pathId);
        return 1;
    }
References TaxiPathNodeEntry::actionFlag, AddTaxiPath(), TaxiPathNodeEntry::delay, TaxiPathEntry::from, TaxiNodesEntry::ID, TaxiPathEntry::ID, TaxiPathNodeEntry::index, lua_gettop(), lua_insert(), lua_isnone, lua_next(), lua_pop, lua_pushvalue(), lua_remove(), LUA_TTABLE, luaL_argerror(), luaL_checktype(), TaxiNodesEntry::map_id, TaxiPathNodeEntry::mapid, TaxiNodesEntry::MountCreatureID, TaxiPathNodeEntry::path, TaxiPathEntry::price, Eluna::Push(), sTaxiNodesStore, sTaxiPathNodesByPath, sTaxiPathSetBySource, sTaxiPathStore, TaxiPathEntry::to, TaxiNodesEntry::x, TaxiPathNodeEntry::x, TaxiNodesEntry::y, TaxiPathNodeEntry::y, TaxiNodesEntry::z, and TaxiPathNodeEntry::z.
Referenced by AddTaxiPath().
AddVendorItem()
int LuaGlobalFunctions::AddVendorItem (lua_State * L)
Adds an [Item] to a vendor and updates the world database.
Parameters
uint32 entry : [Creature] entry Id
uint32 item : [Item] entry Id
int32 maxcount : max [Item] stack count
uint32 incrtime : combined with maxcount, incrtime tells how often (in seconds) the vendor list is refreshed and the limited [Item] copies are restocked
uint32 extendedcost : unique cost of an [Item], such as conquest points for example
    {
        uint32 entry = Eluna::CHECKVAL<uint32>(L, 1);
        uint32 item = Eluna::CHECKVAL<uint32>(L, 2);
        int maxcount = Eluna::CHECKVAL<int>(L, 3);
        uint32 incrtime = Eluna::CHECKVAL<uint32>(L, 4);
        uint32 extendedcost = Eluna::CHECKVAL<uint32>(L, 5);
#if defined TRINITY || AZEROTHCORE
#ifdef CATA
        if (!eObjectMgr->IsVendorItemValid(entry, item, maxcount, incrtime, extendedcost, 1))
            return 0;
        eObjectMgr->AddVendorItem(entry, item, maxcount, incrtime, extendedcost, 1);
#else
        if (!eObjectMgr->IsVendorItemValid(entry, item, maxcount, incrtime, extendedcost))
            return 0;
        eObjectMgr->AddVendorItem(entry, item, maxcount, incrtime, extendedcost);
#endif
#else
        if (!eObjectMgr->IsVendorItemValid(false, "npc_vendor", entry, item, maxcount, incrtime, extendedcost, 0))
            return 0;
#ifndef CLASSIC
        eObjectMgr->AddVendorItem(entry, item, maxcount, incrtime, extendedcost);
#else
        eObjectMgr->AddVendorItem(entry, item, maxcount, incrtime);
#endif
#endif//TRINITY
        return 0;
    }
References AddVendorItem(), and eObjectMgr.
Referenced by AddVendorItem().
AuthDBExecute()
int LuaGlobalFunctions::AuthDBExecute (lua_State * L)
Executes a SQL query on the login database.
The query may be executed asynchronously (at a later, unpredictable time). If you need to execute the query synchronously, use [Global:AuthDBQuery] instead.
Any results produced are ignored. If you need results from the query, use [Global:AuthDBQuery] or [Global:AuthDBQueryAsync] instead.
AuthDBExecute("DELETE FROM my_table")
Parameters
string sql : query to execute
    {
        const char* query = Eluna::CHECKVAL<const char*>(L, 1);
        LoginDatabase.Execute(query);
        return 0;
    }
References AuthDBExecute(), and LoginDatabase.
Referenced by AuthDBExecute().
AuthDBQuery()
int LuaGlobalFunctions::AuthDBQuery (lua_State * L)
Executes a SQL query on the login database and returns an [ElunaQuery].
The query is always executed synchronously (i.e. execution halts until the query has finished and then results are returned). If you need to execute the query asynchronously, use [Global:AuthDBQueryAsync] instead.
For an example see [Global:WorldDBQuery].
Parameters
string sql : query to execute
Returns
[ElunaQuery] results or nil if no rows found
    {
        const char* query = Eluna::CHECKVAL<const char*>(L, 1);
#if defined TRINITY || AZEROTHCORE
        QueryResult result = LoginDatabase.Query(query);
        if (result)
            Eluna::Push(L, new QueryResult(result));
        else
            Eluna::Push(L);
#else
        QueryNamedResult* result = LoginDatabase.QueryNamed(query);
        if (result)
            Eluna::Push(L, result);
        else
            Eluna::Push(L);
#endif
        return 1;
    }
References AuthDBQuery(), LoginDatabase, and Eluna::Push().
Referenced by AuthDBQuery().
AuthDBQueryAsync()
int LuaGlobalFunctions::AuthDBQueryAsync (lua_State * L)
Executes an asynchronous SQL query on the character database and passes an [ElunaQuery] to a callback function.
The query is executed asynchronously (i.e. the server keeps running while the query is executed in parallel, and results are passed to a callback function). If you need to execute the query synchronously, use [Global:AuthDBQuery] instead.
For an example see [Global:WorldDBQueryAsync].
Parameters
string sql : query to execute
function callback : function that will be called when the results are available
    {
        return DBQueryAsync(L, LoginDatabase);
    }
References AuthDBQueryAsync(), DBQueryAsync(), and LoginDatabase.
Referenced by AuthDBQueryAsync().
Ban()
int LuaGlobalFunctions::Ban (lua_State * L)
Ban's a [Player]'s account, character or IP
enum BanMode
{
    BAN_ACCOUNT = 0,
    BAN_CHARACTER = 1,
    BAN_IP = 2
};
Parameters
[BanMode] banMode : method of ban, refer to BanMode above
string nameOrIP : If BanMode is 0 then accountname, if 1 then charactername if 2 then ip
uint32 duration : duration (in seconds) of the ban
string reason = "" : ban reason, this is optional
string whoBanned = "" : the [Player]'s name that banned the account, character or IP, this is optional
Returns
int result : status of the ban. 0 if success, 1 if syntax error, 2 if target not found, 3 if a longer ban already exists, nil if unknown result
    {
        int banMode = Eluna::CHECKVAL<int>(L, 1);
        std::string nameOrIP = Eluna::CHECKVAL<std::string>(L, 2);
        uint32 duration = Eluna::CHECKVAL<uint32>(L, 3);
        const char* reason = Eluna::CHECKVAL<const char*>(L, 4, "");
        const char* whoBanned = Eluna::CHECKVAL<const char*>(L, 5, "");
        const int BAN_ACCOUNT = 0;
        const int BAN_CHARACTER = 1;
        const int BAN_IP = 2;
        switch (banMode)
        {
            case BAN_ACCOUNT:
#if defined TRINITY || AZEROTHCORE
                if (!Utf8ToUpperOnlyLatin(nameOrIP))
                    return luaL_argerror(L, 2, "invalid account name");
#else
                if (!AccountMgr::normalizeString(nameOrIP))
                    return luaL_argerror(L, 2, "invalid account name");
#endif
                break;
            case BAN_CHARACTER:
                if (!normalizePlayerName(nameOrIP))
                    return luaL_argerror(L, 2, "invalid character name");
                break;
            case BAN_IP:
                if (!IsIPAddress(nameOrIP.c_str()))
                    return luaL_argerror(L, 2, "invalid ip");
                break;
            default:
                return luaL_argerror(L, 1, "unknown banmode");
        }
        BanReturn result;
        switch (banMode)
        {
            case BAN_ACCOUNT:
                result = sBan->BanAccount(nameOrIP, std::to_string(duration) + "s", reason, whoBanned);
            break;
            case BAN_CHARACTER:
                result = sBan->BanCharacter(nameOrIP, std::to_string(duration) + "s", reason, whoBanned);
            break;
            case BAN_IP:
                result = sBan->BanIP(nameOrIP, std::to_string(duration) + "s", reason, whoBanned);
            break;
        }
        switch (result)
        {
        case BanReturn::BAN_SUCCESS:
            Eluna::Push(L, 0);
            break;
        case BanReturn::BAN_SYNTAX_ERROR:
            Eluna::Push(L, 1);
            break;
        case BanReturn::BAN_NOTFOUND:
            Eluna::Push(L, 2);
            break;
#ifdef AZEROTHCORE
        case BanReturn::BAN_LONGER_EXISTS:
            Eluna::Push(L, 3);
            break;
#elif TRINITY
        case BanReturn::BAN_EXISTS:
            Eluna::Push(L, 3);
            break;
#endif
        }
        return 1;
    }
References Ban(), BAN_ACCOUNT, BAN_CHARACTER, BAN_IP, BAN_LONGER_EXISTS, BAN_NOTFOUND, BAN_SUCCESS, BAN_SYNTAX_ERROR, IsIPAddress(), luaL_argerror(), normalizePlayerName(), Eluna::Push(), sBan, and Utf8ToUpperOnlyLatin().
Referenced by Ban().
bit_and()
int LuaGlobalFunctions::bit_and (lua_State * L)
Performs a bitwise AND (a & b).
Parameters
uint32 a
uint32 b
Returns
uint32 result
    {
        uint32 a = Eluna::CHECKVAL<uint32>(L, 1);
        uint32 b = Eluna::CHECKVAL<uint32>(L, 2);
        Eluna::Push(L, a & b);
        return 1;
    }
References bit_and(), and Eluna::Push().
Referenced by bit_and().
bit_lshift()
int LuaGlobalFunctions::bit_lshift (lua_State * L)
Performs a bitwise left-shift (a << b).
Parameters
uint32 a
uint32 b
Returns
uint32 result
    {
        uint32 a = Eluna::CHECKVAL<uint32>(L, 1);
        uint32 b = Eluna::CHECKVAL<uint32>(L, 2);
        Eluna::Push(L, a << b);
        return 1;
    }
References bit_lshift(), and Eluna::Push().
Referenced by bit_lshift().
bit_not()
int LuaGlobalFunctions::bit_not (lua_State * L)
Performs a bitwise NOT (~a).
Parameters
uint32 a
Returns
uint32 result
    {
        uint32 a = Eluna::CHECKVAL<uint32>(L, 1);
        Eluna::Push(L, ~a);
        return 1;
    }
References bit_not(), and Eluna::Push().
Referenced by bit_not().
bit_or()
int LuaGlobalFunctions::bit_or (lua_State * L)
Performs a bitwise OR (a | b).
Parameters
uint32 a
uint32 b
Returns
uint32 result
    {
        uint32 a = Eluna::CHECKVAL<uint32>(L, 1);
        uint32 b = Eluna::CHECKVAL<uint32>(L, 2);
        Eluna::Push(L, a | b);
        return 1;
    }
References bit_or(), and Eluna::Push().
Referenced by bit_or().
bit_rshift()
int LuaGlobalFunctions::bit_rshift (lua_State * L)
Performs a bitwise right-shift (a >> b).
Parameters
uint32 a
uint32 b
Returns
uint32 result
    {
        uint32 a = Eluna::CHECKVAL<uint32>(L, 1);
        uint32 b = Eluna::CHECKVAL<uint32>(L, 2);
        Eluna::Push(L, a >> b);
        return 1;
    }
References bit_rshift(), and Eluna::Push().
Referenced by bit_rshift().
bit_xor()
int LuaGlobalFunctions::bit_xor (lua_State * L)
Performs a bitwise XOR (a ^ b).
Parameters
uint32 a
uint32 b
Returns
uint32 result
    {
        uint32 a = Eluna::CHECKVAL<uint32>(L, 1);
        uint32 b = Eluna::CHECKVAL<uint32>(L, 2);
        Eluna::Push(L, a ^ b);
        return 1;
    }
References bit_xor(), and Eluna::Push().
Referenced by bit_xor().
CharDBExecute()
int LuaGlobalFunctions::CharDBExecute (lua_State * L)
Executes a SQL query on the character database.
The query may be executed asynchronously (at a later, unpredictable time). If you need to execute the query synchronously, use [Global:CharDBQuery] instead.
Any results produced are ignored. If you need results from the query, use [Global:CharDBQuery] or [Global:CharDBQueryAsync] instead.
CharDBExecute("DELETE FROM my_table")
Parameters
string sql : query to execute
    {
        const char* query = Eluna::CHECKVAL<const char*>(L, 1);
        CharacterDatabase.Execute(query);
        return 0;
    }
References CharacterDatabase, and CharDBExecute().
Referenced by CharDBExecute().
CharDBQuery()
int LuaGlobalFunctions::CharDBQuery (lua_State * L)
Executes a SQL query on the character database and returns an [ElunaQuery].
The query is always executed synchronously (i.e. execution halts until the query has finished and then results are returned). If you need to execute the query asynchronously, use [Global:CharDBQueryAsync] instead.
For an example see [Global:WorldDBQuery].
Parameters
string sql : query to execute
Returns
[ElunaQuery] results or nil if no rows found
    {
        const char* query = Eluna::CHECKVAL<const char*>(L, 1);
#if defined TRINITY || AZEROTHCORE
        QueryResult result = CharacterDatabase.Query(query);
        if (result)
            Eluna::Push(L, new QueryResult(result));
        else
            Eluna::Push(L);
#else
        QueryNamedResult* result = CharacterDatabase.QueryNamed(query);
        if (result)
            Eluna::Push(L, result);
        else
            Eluna::Push(L);
#endif
        return 1;
    }
References CharacterDatabase, CharDBQuery(), and Eluna::Push().
Referenced by CharDBQuery().
CharDBQueryAsync()
int LuaGlobalFunctions::CharDBQueryAsync (lua_State * L)
Executes an asynchronous SQL query on the character database and passes an [ElunaQuery] to a callback function.
The query is executed asynchronously (i.e. the server keeps running while the query is executed in parallel, and results are passed to a callback function). If you need to execute the query synchronously, use [Global:CharDBQuery] instead.
For an example see [Global:WorldDBQueryAsync].
Parameters
string sql : query to execute
function callback : function that will be called when the results are available
    {
        return DBQueryAsync(L, CharacterDatabase);
    }
References CharacterDatabase, CharDBQueryAsync(), and DBQueryAsync().
Referenced by CharDBQueryAsync().
ClearBattleGroundEvents()
int LuaGlobalFunctions::ClearBattleGroundEvents (lua_State * L)
Unbinds event handlers for either all [BattleGround] events, or one type of event.
If event_type is nil, all [BattleGround] event handlers are cleared.
Otherwise, only event handlers for event_type are cleared.
@proto () @proto (event_type)
Parameters
uint32 event_type : the event whose handlers will be cleared, see [Global:RegisterBGEvent]
    {
        typedef EventKey<Hooks::BGEvents> Key;
        if (lua_isnoneornil(L, 1))
        {
            Eluna::GetEluna(L)->BGEventBindings->Clear();
        }
        else
        {
            uint32 event_type = Eluna::CHECKVAL<uint32>(L, 1);
            Eluna::GetEluna(L)->BGEventBindings->Clear(Key((Hooks::BGEvents)event_type));
        }
        return 0;
    }
References Eluna::BGEventBindings, BindingMap< K >::Clear(), ClearBattleGroundEvents(), Eluna::GetEluna(), and lua_isnoneornil.
Referenced by ClearBattleGroundEvents().
ClearCreatureEvents()
int LuaGlobalFunctions::ClearCreatureEvents (lua_State * L)
Unbinds event handlers for either all of a [Creature]'s events, or one type of event.
If event_type is nil, all the [Creature]'s event handlers are cleared.
Otherwise, only event handlers for event_type are cleared.
NOTE: this will affect all instances of the [Creature], not just one. To bind and unbind events to a single [Creature], see [Global:RegisterUniqueCreatureEvent] and [Global:ClearUniqueCreatureEvents].
@proto (entry) @proto (entry, event_type)
Parameters
uint32 entry : the ID of one or more [Creature]s whose handlers will be cleared
uint32 event_type : the event whose handlers will be cleared, see [Global:RegisterCreatureEvent]
    {
        typedef EntryKey<Hooks::CreatureEvents> Key;
        if (lua_isnoneornil(L, 2))
        {
            uint32 entry = Eluna::CHECKVAL<uint32>(L, 1);
            Eluna* E = Eluna::GetEluna(L);
            for (uint32 i = 1; i < Hooks::CREATURE_EVENT_COUNT; ++i)
                E->CreatureEventBindings->Clear(Key((Hooks::CreatureEvents)i, entry));
        }
        else
        {
            uint32 entry = Eluna::CHECKVAL<uint32>(L, 1);
            uint32 event_type = Eluna::CHECKVAL<uint32>(L, 2);
            Eluna::GetEluna(L)->CreatureEventBindings->Clear(Key((Hooks::CreatureEvents)event_type, entry));
        }
        return 0;
    }
References BindingMap< K >::Clear(), ClearCreatureEvents(), Hooks::CREATURE_EVENT_COUNT, Eluna::CreatureEventBindings, Eluna::GetEluna(), and lua_isnoneornil.
Referenced by ClearCreatureEvents().
ClearCreatureGossipEvents()
int LuaGlobalFunctions::ClearCreatureGossipEvents (lua_State * L)
Unbinds event handlers for either all of a [Creature]'s gossip events, or one type of event.
If event_type is nil, all the [Creature]'s gossip event handlers are cleared.
Otherwise, only event handlers for event_type are cleared.
NOTE: this will affect all instances of the [Creature], not just one. To bind and unbind gossip events to a single [Creature], tell the Eluna developers to implement that.
@proto (entry) @proto (entry, event_type)
Parameters
uint32 entry : the ID of a [Creature] whose handlers will be cleared
uint32 event_type : the event whose handlers will be cleared, see [Global:RegisterCreatureGossipEvent]
    {
        typedef EntryKey<Hooks::GossipEvents> Key;
        if (lua_isnoneornil(L, 2))
        {
            uint32 entry = Eluna::CHECKVAL<uint32>(L, 1);
            Eluna* E = Eluna::GetEluna(L);
            for (uint32 i = 1; i < Hooks::GOSSIP_EVENT_COUNT; ++i)
                E->CreatureGossipBindings->Clear(Key((Hooks::GossipEvents)i, entry));
        }
        else
        {
            uint32 entry = Eluna::CHECKVAL<uint32>(L, 1);
            uint32 event_type = Eluna::CHECKVAL<uint32>(L, 2);
            Eluna::GetEluna(L)->CreatureGossipBindings->Clear(Key((Hooks::GossipEvents)event_type, entry));
        }
        return 0;
    }
References BindingMap< K >::Clear(), ClearCreatureGossipEvents(), Eluna::CreatureGossipBindings, Eluna::GetEluna(), Hooks::GOSSIP_EVENT_COUNT, and lua_isnoneornil.
Referenced by ClearCreatureGossipEvents().
ClearGameObjectEvents()
int LuaGlobalFunctions::ClearGameObjectEvents (lua_State * L)
Unbinds event handlers for either all of a [GameObject]'s events, or one type of event.
If event_type is nil, all the [GameObject]'s event handlers are cleared.
Otherwise, only event handlers for event_type are cleared.
NOTE: this will affect all instances of the [GameObject], not just one. To bind and unbind events to a single [GameObject], tell the Eluna developers to implement that.
@proto (entry) @proto (entry, event_type)
Parameters
uint32 entry : the ID of a [GameObject] whose handlers will be cleared
uint32 event_type : the event whose handlers will be cleared, see [Global:RegisterGameObjectEvent]
    {
        typedef EntryKey<Hooks::GameObjectEvents> Key;
        if (lua_isnoneornil(L, 2))
        {
            uint32 entry = Eluna::CHECKVAL<uint32>(L, 1);
            Eluna* E = Eluna::GetEluna(L);
            for (uint32 i = 1; i < Hooks::GAMEOBJECT_EVENT_COUNT; ++i)
                E->GameObjectEventBindings->Clear(Key((Hooks::GameObjectEvents)i, entry));
        }
        else
        {
            uint32 entry = Eluna::CHECKVAL<uint32>(L, 1);
            uint32 event_type = Eluna::CHECKVAL<uint32>(L, 2);
            Eluna::GetEluna(L)->GameObjectEventBindings->Clear(Key((Hooks::GameObjectEvents)event_type, entry));
        }
        return 0;
    }
References BindingMap< K >::Clear(), ClearGameObjectEvents(), Hooks::GAMEOBJECT_EVENT_COUNT, Eluna::GameObjectEventBindings, Eluna::GetEluna(), and lua_isnoneornil.
Referenced by ClearGameObjectEvents().
ClearGameObjectGossipEvents()
int LuaGlobalFunctions::ClearGameObjectGossipEvents (lua_State * L)
Unbinds event handlers for either all of a [GameObject]'s gossip events, or one type of event.
If event_type is nil, all the [GameObject]'s gossip event handlers are cleared.
Otherwise, only event handlers for event_type are cleared.
NOTE: this will affect all instances of the [GameObject], not just one. To bind and unbind gossip events to a single [GameObject], tell the Eluna developers to implement that.
@proto (entry) @proto (entry, event_type)
Parameters
uint32 entry : the ID of a [GameObject] whose handlers will be cleared
uint32 event_type : the event whose handlers will be cleared, see [Global:RegisterGameObjectGossipEvent]
    {
        typedef EntryKey<Hooks::GossipEvents> Key;
        if (lua_isnoneornil(L, 2))
        {
            uint32 entry = Eluna::CHECKVAL<uint32>(L, 1);
            Eluna* E = Eluna::GetEluna(L);
            for (uint32 i = 1; i < Hooks::GOSSIP_EVENT_COUNT; ++i)
                E->GameObjectGossipBindings->Clear(Key((Hooks::GossipEvents)i, entry));
        }
        else
        {
            uint32 entry = Eluna::CHECKVAL<uint32>(L, 1);
            uint32 event_type = Eluna::CHECKVAL<uint32>(L, 2);
            Eluna::GetEluna(L)->GameObjectGossipBindings->Clear(Key((Hooks::GossipEvents)event_type, entry));
        }
        return 0;
    }
References BindingMap< K >::Clear(), ClearGameObjectGossipEvents(), Eluna::GameObjectGossipBindings, Eluna::GetEluna(), Hooks::GOSSIP_EVENT_COUNT, and lua_isnoneornil.
Referenced by ClearGameObjectGossipEvents().
ClearGroupEvents()
int LuaGlobalFunctions::ClearGroupEvents (lua_State * L)
Unbinds event handlers for either all [Group] events, or one type of [Group] event.
If event_type is nil, all [Group] event handlers are cleared.
Otherwise, only event handlers for event_type are cleared.
@proto () @proto (event_type)
Parameters
uint32 event_type : the event whose handlers will be cleared, see [Global:RegisterGroupEvent]
    {
        typedef EventKey<Hooks::GroupEvents> Key;
        if (lua_isnoneornil(L, 1))
        {
            Eluna::GetEluna(L)->GroupEventBindings->Clear();
        }
        else
        {
            uint32 event_type = Eluna::CHECKVAL<uint32>(L, 1);
            Eluna::GetEluna(L)->GroupEventBindings->Clear(Key((Hooks::GroupEvents)event_type));
        }
        return 0;
    }
References BindingMap< K >::Clear(), ClearGroupEvents(), Eluna::GetEluna(), Eluna::GroupEventBindings, and lua_isnoneornil.
Referenced by ClearGroupEvents().
ClearGuildEvents()
int LuaGlobalFunctions::ClearGuildEvents (lua_State * L)
Unbinds event handlers for either all [Guild] events, or one type of [Guild] event.
If event_type is nil, all [Guild] event handlers are cleared.
Otherwise, only event handlers for event_type are cleared.
@proto () @proto (event_type)
Parameters
uint32 event_type : the event whose handlers will be cleared, see [Global:RegisterGuildEvent]
    {
        typedef EventKey<Hooks::GuildEvents> Key;
        if (lua_isnoneornil(L, 1))
        {
            Eluna::GetEluna(L)->GuildEventBindings->Clear();
        }
        else
        {
            uint32 event_type = Eluna::CHECKVAL<uint32>(L, 1);
            Eluna::GetEluna(L)->GuildEventBindings->Clear(Key((Hooks::GuildEvents)event_type));
        }
        return 0;
    }
References BindingMap< K >::Clear(), ClearGuildEvents(), Eluna::GetEluna(), Eluna::GuildEventBindings, and lua_isnoneornil.
Referenced by ClearGuildEvents().
ClearInstanceEvents()
int LuaGlobalFunctions::ClearInstanceEvents (lua_State * L)
Unbinds event handlers for either all of an instanced [Map]'s events, or one type of event.
If event_type is nil, all the instanced [Map]'s event handlers are cleared.
Otherwise, only event handlers for event_type are cleared.
@proto (instance_id) @proto (instance_id, event_type)
Parameters
uint32 entry : the ID of an instance of a [Map]
uint32 event_type : the event whose handlers will be cleared, see [Global:RegisterInstanceEvent]
    {
        typedef EntryKey<Hooks::InstanceEvents> Key;
        if (lua_isnoneornil(L, 2))
        {
            uint32 entry = Eluna::CHECKVAL<uint32>(L, 1);
            Eluna* E = Eluna::GetEluna(L);
            for (uint32 i = 1; i < Hooks::INSTANCE_EVENT_COUNT; ++i)
                E->InstanceEventBindings->Clear(Key((Hooks::InstanceEvents)i, entry));
        }
        else
        {
            uint32 entry = Eluna::CHECKVAL<uint32>(L, 1);
            uint32 event_type = Eluna::CHECKVAL<uint32>(L, 2);
            Eluna::GetEluna(L)->InstanceEventBindings->Clear(Key((Hooks::InstanceEvents)event_type, entry));
        }
        return 0;
    }
References BindingMap< K >::Clear(), ClearInstanceEvents(), Eluna::GetEluna(), Hooks::INSTANCE_EVENT_COUNT, Eluna::InstanceEventBindings, and lua_isnoneornil.
Referenced by ClearInstanceEvents().
ClearItemEvents()
int LuaGlobalFunctions::ClearItemEvents (lua_State * L)
Unbinds event handlers for either all of an [Item]'s events, or one type of event.
If event_type is nil, all the [Item]'s event handlers are cleared.
Otherwise, only event handlers for event_type are cleared.
NOTE: this will affect all instances of the [Item], not just one. To bind and unbind events to a single [Item], tell the Eluna developers to implement that.
@proto (entry) @proto (entry, event_type)
Parameters
uint32 entry : the ID of an [Item] whose handlers will be cleared
uint32 event_type : the event whose handlers will be cleared, see [Global:RegisterItemEvent]
    {
        typedef EntryKey<Hooks::ItemEvents> Key;
        if (lua_isnoneornil(L, 2))
        {
            uint32 entry = Eluna::CHECKVAL<uint32>(L, 1);
            Eluna* E = Eluna::GetEluna(L);
            for (uint32 i = 1; i < Hooks::ITEM_EVENT_COUNT; ++i)
                E->ItemEventBindings->Clear(Key((Hooks::ItemEvents)i, entry));
        }
        else
        {
            uint32 entry = Eluna::CHECKVAL<uint32>(L, 1);
            uint32 event_type = Eluna::CHECKVAL<uint32>(L, 2);
            Eluna::GetEluna(L)->ItemEventBindings->Clear(Key((Hooks::ItemEvents)event_type, entry));
        }
        return 0;
    }
References BindingMap< K >::Clear(), ClearItemEvents(), Eluna::GetEluna(), Hooks::ITEM_EVENT_COUNT, Eluna::ItemEventBindings, and lua_isnoneornil.
Referenced by ClearItemEvents().
ClearItemGossipEvents()
int LuaGlobalFunctions::ClearItemGossipEvents (lua_State * L)
Unbinds event handlers for either all of an [Item]'s gossip events, or one type of event.
If event_type is nil, all the [Item]'s gossip event handlers are cleared.
Otherwise, only event handlers for event_type are cleared.
NOTE: this will affect all instances of the [Item], not just one. To bind and unbind gossip events to a single [Item], tell the Eluna developers to implement that.
@proto (entry) @proto (entry, event_type)
Parameters
uint32 entry : the ID of an [Item] whose handlers will be cleared
uint32 event_type : the event whose handlers will be cleared, see [Global:RegisterItemGossipEvent]
    {
        typedef EntryKey<Hooks::GossipEvents> Key;
        if (lua_isnoneornil(L, 2))
        {
            uint32 entry = Eluna::CHECKVAL<uint32>(L, 1);
            Eluna* E = Eluna::GetEluna(L);
            for (uint32 i = 1; i < Hooks::GOSSIP_EVENT_COUNT; ++i)
                E->ItemGossipBindings->Clear(Key((Hooks::GossipEvents)i, entry));
        }
        else
        {
            uint32 entry = Eluna::CHECKVAL<uint32>(L, 1);
            uint32 event_type = Eluna::CHECKVAL<uint32>(L, 2);
            Eluna::GetEluna(L)->ItemGossipBindings->Clear(Key((Hooks::GossipEvents)event_type, entry));
        }
        return 0;
    }
References BindingMap< K >::Clear(), ClearItemGossipEvents(), Eluna::GetEluna(), Hooks::GOSSIP_EVENT_COUNT, Eluna::ItemGossipBindings, and lua_isnoneornil.
Referenced by ClearItemGossipEvents().
ClearMapEvents()
int LuaGlobalFunctions::ClearMapEvents (lua_State * L)
Unbinds event handlers for either all of a non-instanced [Map]'s events, or one type of event.
If event_type is nil, all the non-instanced [Map]'s event handlers are cleared.
Otherwise, only event handlers for event_type are cleared.
@proto (map_id) @proto (map_id, event_type)
Parameters
uint32 map_id : the ID of a [Map]
uint32 event_type : the event whose handlers will be cleared, see [Global:RegisterPlayerGossipEvent]
    {
        typedef EntryKey<Hooks::InstanceEvents> Key;
        if (lua_isnoneornil(L, 2))
        {
            uint32 entry = Eluna::CHECKVAL<uint32>(L, 1);
            Eluna* E = Eluna::GetEluna(L);
            for (uint32 i = 1; i < Hooks::INSTANCE_EVENT_COUNT; ++i)
                E->MapEventBindings->Clear(Key((Hooks::InstanceEvents)i, entry));
        }
        else
        {
            uint32 entry = Eluna::CHECKVAL<uint32>(L, 1);
            uint32 event_type = Eluna::CHECKVAL<uint32>(L, 2);
            Eluna::GetEluna(L)->MapEventBindings->Clear(Key((Hooks::InstanceEvents)event_type, entry));
        }
        return 0;
    }
References BindingMap< K >::Clear(), ClearMapEvents(), Eluna::GetEluna(), Hooks::INSTANCE_EVENT_COUNT, lua_isnoneornil, and Eluna::MapEventBindings.
Referenced by ClearMapEvents().
ClearPacketEvents()
int LuaGlobalFunctions::ClearPacketEvents (lua_State * L)
Unbinds event handlers for either all of a [WorldPacket] opcode's events, or one type of event.
If event_type is nil, all the [WorldPacket] opcode's event handlers are cleared.
Otherwise, only event handlers for event_type are cleared.
@proto (opcode) @proto (opcode, event_type)
Parameters
uint32 opcode : the type of [WorldPacket] whose handlers will be cleared
uint32 event_type : the event whose handlers will be cleared, see [Global:RegisterPacketEvent]
    {
        typedef EntryKey<Hooks::PacketEvents> Key;
        if (lua_isnoneornil(L, 2))
        {
            uint32 entry = Eluna::CHECKVAL<uint32>(L, 1);
            Eluna* E = Eluna::GetEluna(L);
            for (uint32 i = 1; i < Hooks::PACKET_EVENT_COUNT; ++i)
                E->PacketEventBindings->Clear(Key((Hooks::PacketEvents)i, entry));
        }
        else
        {
            uint32 entry = Eluna::CHECKVAL<uint32>(L, 1);
            uint32 event_type = Eluna::CHECKVAL<uint32>(L, 2);
            Eluna::GetEluna(L)->PacketEventBindings->Clear(Key((Hooks::PacketEvents)event_type, entry));
        }
        return 0;
    }
References BindingMap< K >::Clear(), ClearPacketEvents(), Eluna::GetEluna(), lua_isnoneornil, Hooks::PACKET_EVENT_COUNT, and Eluna::PacketEventBindings.
Referenced by ClearPacketEvents().
ClearPlayerEvents()
int LuaGlobalFunctions::ClearPlayerEvents (lua_State * L)
Unbinds event handlers for either all [Player] events, or one type of [Player] event.
If event_type is nil, all [Player] event handlers are cleared.
Otherwise, only event handlers for event_type are cleared.
@proto () @proto (event_type)
Parameters
uint32 event_type : the event whose handlers will be cleared, see [Global:RegisterPlayerEvent]
    {
        typedef EventKey<Hooks::PlayerEvents> Key;
        if (lua_isnoneornil(L, 1))
        {
            Eluna::GetEluna(L)->PlayerEventBindings->Clear();
        }
        else
        {
            uint32 event_type = Eluna::CHECKVAL<uint32>(L, 1);
            Eluna::GetEluna(L)->PlayerEventBindings->Clear(Key((Hooks::PlayerEvents)event_type));
        }
        return 0;
    }
References BindingMap< K >::Clear(), ClearPlayerEvents(), Eluna::GetEluna(), lua_isnoneornil, and Eluna::PlayerEventBindings.
Referenced by ClearPlayerEvents().
ClearPlayerGossipEvents()
int LuaGlobalFunctions::ClearPlayerGossipEvents (lua_State * L)
Unbinds event handlers for either all of a [Player]'s gossip events, or one type of event.
If event_type is nil, all the [Player]'s gossip event handlers are cleared.
Otherwise, only event handlers for event_type are cleared.
@proto (entry) @proto (entry, event_type)
Parameters
uint32 entry : the low GUID of a [Player] whose handlers will be cleared
uint32 event_type : the event whose handlers will be cleared, see [Global:RegisterPlayerGossipEvent]
    {
        typedef EntryKey<Hooks::GossipEvents> Key;
        if (lua_isnoneornil(L, 2))
        {
            uint32 entry = Eluna::CHECKVAL<uint32>(L, 1);
            Eluna* E = Eluna::GetEluna(L);
            for (uint32 i = 1; i < Hooks::GOSSIP_EVENT_COUNT; ++i)
                E->PlayerGossipBindings->Clear(Key((Hooks::GossipEvents)i, entry));
        }
        else
        {
            uint32 entry = Eluna::CHECKVAL<uint32>(L, 1);
            uint32 event_type = Eluna::CHECKVAL<uint32>(L, 2);
            Eluna::GetEluna(L)->PlayerGossipBindings->Clear(Key((Hooks::GossipEvents)event_type, entry));
        }
        return 0;
    }
References BindingMap< K >::Clear(), ClearPlayerGossipEvents(), Eluna::GetEluna(), Hooks::GOSSIP_EVENT_COUNT, lua_isnoneornil, and Eluna::PlayerGossipBindings.
Referenced by ClearPlayerGossipEvents().
ClearServerEvents()
int LuaGlobalFunctions::ClearServerEvents (lua_State * L)
Unbinds event handlers for either all server events, or one type of event.
If event_type is nil, all server event handlers are cleared.
Otherwise, only event handlers for event_type are cleared.
@proto () @proto (event_type)
Parameters
uint32 event_type : the event whose handlers will be cleared, see [Global:RegisterServerEvent]
    {
        typedef EventKey<Hooks::ServerEvents> Key;
        if (lua_isnoneornil(L, 1))
        {
            Eluna::GetEluna(L)->ServerEventBindings->Clear();
        }
        else
        {
            uint32 event_type = Eluna::CHECKVAL<uint32>(L, 1);
            Eluna::GetEluna(L)->ServerEventBindings->Clear(Key((Hooks::ServerEvents)event_type));
        }
        return 0;
    }
References BindingMap< K >::Clear(), ClearServerEvents(), Eluna::GetEluna(), lua_isnoneornil, and Eluna::ServerEventBindings.
Referenced by ClearServerEvents().
ClearUniqueCreatureEvents()
int LuaGlobalFunctions::ClearUniqueCreatureEvents (lua_State * L)
Unbinds event handlers for either all of a [Creature]'s events, or one type of event.
If event_type is nil, all the [Creature]'s event handlers are cleared.
Otherwise, only event handlers for event_type are cleared.
NOTE: this will affect only a single [Creature]. To bind and unbind events to all instances of a [Creature], see [Global:RegisterCreatureEvent] and [Global:ClearCreatureEvent].
@proto (entry) @proto (entry, event_type)
Parameters
ObjectGuid guid : the GUID of a single [Creature] whose handlers will be cleared
uint32 instance_id : the instance ID of a single [Creature] whose handlers will be cleared
uint32 event_type : the event whose handlers will be cleared, see [Global:RegisterCreatureEvent]
    {
        typedef UniqueObjectKey<Hooks::CreatureEvents> Key;
        if (lua_isnoneornil(L, 3))
        {
            ObjectGuid guid = Eluna::CHECKVAL<ObjectGuid>(L, 1);
            uint32 instanceId = Eluna::CHECKVAL<uint32>(L, 2);
            Eluna* E = Eluna::GetEluna(L);
            for (uint32 i = 1; i < Hooks::CREATURE_EVENT_COUNT; ++i)
                E->CreatureUniqueBindings->Clear(Key((Hooks::CreatureEvents)i, guid, instanceId));
        }
        else
        {
            ObjectGuid guid = Eluna::CHECKVAL<ObjectGuid>(L, 1);
            uint32 instanceId = Eluna::CHECKVAL<uint32>(L, 2);
            uint32 event_type = Eluna::CHECKVAL<uint32>(L, 3);
            Eluna::GetEluna(L)->CreatureUniqueBindings->Clear(Key((Hooks::CreatureEvents)event_type, guid, instanceId));
        }
        return 0;
    }
References BindingMap< K >::Clear(), ClearUniqueCreatureEvents(), Hooks::CREATURE_EVENT_COUNT, Eluna::CreatureUniqueBindings, Eluna::GetEluna(), and lua_isnoneornil.
Referenced by ClearUniqueCreatureEvents().
CreateLongLong()
int LuaGlobalFunctions::CreateLongLong (lua_State * L)
Returns an object representing a long long (64-bit) value.
The value by default is 0, but can be initialized to a value by passing a number or long long as a string.
@proto value = () @proto value = (n) @proto value = (n_ll) @proto value = (n_str)
Parameters
int32 n
int64 n_ll
string n_str
Returns
int64 value
    {
        long long init = 0;
        if (lua_isstring(L, 1))
        {
            std::string str = Eluna::CHECKVAL<std::string>(L, 1);
            std::istringstream iss(str);
            iss >> init;
            if (iss.bad())
                return luaL_argerror(L, 1, "long long (as string) could not be converted");
        }
        else if (!lua_isnoneornil(L, 1))
            init = Eluna::CHECKVAL<long long>(L, 1);
        Eluna::Push(L, init);
        return 1;
    }
References CreateLongLong(), lua_isnoneornil, lua_isstring(), luaL_argerror(), and Eluna::Push().
Referenced by CreateLongLong().
CreateLuaEvent()
int LuaGlobalFunctions::CreateLuaEvent (lua_State * L)
Registers a global timed event.
When the passed function is called, the parameters (eventId, delay, repeats) are passed to it.
Repeats will decrease on each call if the event does not repeat indefinitely
@proto eventId = (function, delay) @proto eventId = (function, delaytable) @proto eventId = (function, delay, repeats) @proto eventId = (function, delaytable, repeats)
Parameters
function function : function to trigger when the time has passed
uint32 delay : set time in milliseconds for the event to trigger
table delaytable : a table {min, max} containing the minimum and maximum delay time
uint32 repeats = 1 : how many times for the event to repeat, 0 is infinite
Returns
int eventId : unique ID for the timed event used to cancel it or nil
    {
        luaL_checktype(L, 1, LUA_TFUNCTION);
        uint32 min, max;
        if (lua_istable(L, 2))
        {
            Eluna::Push(L, 1);
            lua_gettable(L, 2);
            min = Eluna::CHECKVAL<uint32>(L, -1);
            Eluna::Push(L, 2);
            lua_gettable(L, 2);
            max = Eluna::CHECKVAL<uint32>(L, -1);
            lua_pop(L, 2);
        }
        else
            min = max = Eluna::CHECKVAL<uint32>(L, 2);
        uint32 repeats = Eluna::CHECKVAL<uint32>(L, 3, 1);
        if (min > max)
            return luaL_argerror(L, 2, "min is bigger than max delay");
        lua_pushvalue(L, 1);
        int functionRef = luaL_ref(L, LUA_REGISTRYINDEX);
        if (functionRef != LUA_REFNIL && functionRef != LUA_NOREF)
        {
            Eluna::GetEluna(L)->eventMgr->globalProcessor->AddEvent(functionRef, min, max, repeats);
            Eluna::Push(L, functionRef);
        }
        return 1;
    }
References ElunaEventProcessor::AddEvent(), CreateLuaEvent(), Eluna::eventMgr, Eluna::GetEluna(), EventMgr::globalProcessor, lua_gettable(), lua_istable, LUA_NOREF, lua_pop, lua_pushvalue(), LUA_REFNIL, LUA_REGISTRYINDEX, LUA_TFUNCTION, luaL_argerror(), luaL_checktype(), luaL_ref(), and Eluna::Push().
Referenced by CreateLuaEvent().
CreatePacket()
int LuaGlobalFunctions::CreatePacket (lua_State * L)
Creates a [WorldPacket].
Parameters
[Opcodes] opcode : the opcode of the packet
uint32 size : the size of the packet
Returns
[WorldPacket] packet
    {
        uint32 opcode = Eluna::CHECKVAL<uint32>(L, 1);
        size_t size = Eluna::CHECKVAL<size_t>(L, 2);
        if (opcode >= NUM_MSG_TYPES)
            return luaL_argerror(L, 1, "valid opcode expected");
        Eluna::Push(L, new WorldPacket((OpcodesList)opcode, size));
        return 1;
    }
References luaL_argerror(), NUM_MSG_TYPES, and Eluna::Push().
CreateULongLong()
int LuaGlobalFunctions::CreateULongLong (lua_State * L)
Returns an object representing an unsigned long long (64-bit) value.
The value by default is 0, but can be initialized to a value by passing a number or unsigned long long as a string.
@proto value = () @proto value = (n) @proto value = (n_ull) @proto value = (n_str)
Parameters
uint32 n
uint64 n_ull
string n_str
Returns
uint64 value
    {
        unsigned long long init = 0;
        if (lua_isstring(L, 1))
        {
            std::string str = Eluna::CHECKVAL<std::string>(L, 1);
            std::istringstream iss(str);
            iss >> init;
            if (iss.bad())
                return luaL_argerror(L, 1, "unsigned long long (as string) could not be converted");
        }
        else if (!lua_isnoneornil(L, 1))
            init = Eluna::CHECKVAL<unsigned long long>(L, 1);
        Eluna::Push(L, init);
        return 1;
    }
References CreateULongLong(), lua_isnoneornil, lua_isstring(), luaL_argerror(), and Eluna::Push().
Referenced by CreateULongLong().
DBQueryAsync()
template<typename T > static int LuaGlobalFunctions::DBQueryAsync (lua_State * L, DatabaseWorkerPool< T > & db) static
    {
        const char* query = Eluna::CHECKVAL<const char*>(L, 1);
        luaL_checktype(L, 2, LUA_TFUNCTION);
        lua_pushvalue(L, 2);
        int funcRef = luaL_ref(L, LUA_REGISTRYINDEX);
        if (funcRef == LUA_REFNIL || funcRef == LUA_NOREF)
        {
            luaL_argerror(L, 2, "unable to make a ref to function");
            return 0;
        }
        Eluna::GEluna->queryProcessor.AddCallback(db.AsyncQuery(query).WithCallback([L, funcRef](QueryResult result)
            {
                ElunaQuery* eq = result ? new ElunaQuery(result) : nullptr;
                LOCK_ELUNA;
                // Get function
                lua_rawgeti(L, LUA_REGISTRYINDEX, funcRef);
                // Push parameters
                Eluna::Push(L, eq);
                // Call function
                Eluna::GEluna->ExecuteCall(1, 0);
                luaL_unref(L, LUA_REGISTRYINDEX, funcRef);
            }));
        return 0;
    }
References AsyncCallbackProcessor< T >::AddCallback(), DatabaseWorkerPool< T >::AsyncQuery(), DBQueryAsync(), Eluna::GEluna, LUA_NOREF, lua_pushvalue(), LUA_REFNIL, LUA_REGISTRYINDEX, LUA_TFUNCTION, luaL_argerror(), luaL_checktype(), luaL_ref(), Eluna::queryProcessor, and QueryCallback::WithCallback().
Referenced by AuthDBQueryAsync(), CharDBQueryAsync(), DBQueryAsync(), and WorldDBQueryAsync().
GetActiveGameEvents()
int LuaGlobalFunctions::GetActiveGameEvents (lua_State * L)
Returns the currently active game events.
Returns
table activeEvents
    {
        lua_newtable(L);
        int tbl = lua_gettop(L);
        uint32 counter = 1;
        GameEventMgr::ActiveEvents const& activeEvents = eGameEventMgr->GetActiveEventList();
        for (GameEventMgr::ActiveEvents::const_iterator i = activeEvents.begin(); i != activeEvents.end(); ++i)
        {
            Eluna::Push(L, *i);
            lua_rawseti(L, tbl, counter);
            counter++;
        }
        lua_settop(L, tbl);
        return 1;
    }
References eGameEventMgr, GetActiveGameEvents(), lua_gettop(), lua_newtable, lua_rawseti(), lua_settop(), and Eluna::Push().
Referenced by GetActiveGameEvents().
GetAreaName()
int LuaGlobalFunctions::GetAreaName (lua_State * L)
Returns the area or zone's name.
enum LocaleConstant
{
    LOCALE_enUS = 0,
    LOCALE_koKR = 1,
    LOCALE_frFR = 2,
    LOCALE_deDE = 3,
    LOCALE_zhCN = 4,
    LOCALE_zhTW = 5,
    LOCALE_esES = 6,
    LOCALE_esMX = 7,
    LOCALE_ruRU = 8
};
Parameters
uint32 areaOrZoneId : area ID or zone ID
[LocaleConstant] locale = DEFAULT_LOCALE : locale to return the name in
Returns
string areaOrZoneName
    {
        uint32 areaOrZoneId = Eluna::CHECKVAL<uint32>(L, 1);
        uint8 locale = Eluna::CHECKVAL<uint8>(L, 2, DEFAULT_LOCALE);
        if (locale >= TOTAL_LOCALES)
            return luaL_argerror(L, 2, "valid LocaleConstant expected");
#if defined TRINITY || AZEROTHCORE
        AreaTableEntry const* areaEntry = sAreaTableStore.LookupEntry(areaOrZoneId);
#else
        AreaTableEntry const* areaEntry = GetAreaEntryByAreaID(areaOrZoneId);
#endif
        if (!areaEntry)
            return luaL_argerror(L, 1, "valid Area or Zone ID expected");
#if defined(TRINITY)
        Eluna::Push(L, areaEntry->AreaName[locale]);
#else
        Eluna::Push(L, areaEntry->area_name[locale]);
#endif
        return 1;
    }
References AreaTableEntry::area_name, DEFAULT_LOCALE, GetAreaName(), luaL_argerror(), Eluna::Push(), sAreaTableStore, and TOTAL_LOCALES.
Referenced by GetAreaName().
GetCoreExpansion()
int LuaGlobalFunctions::GetCoreExpansion (lua_State * L)
Returns emulator's supported expansion.
Expansion is 0 for pre-TBC, 1 for TBC, 2 for WotLK, and 3 for Cataclysm.
Returns
int32 expansion
    {
#ifdef CLASSIC
        Eluna::Push(L, 0);
#elif defined(TBC)
        Eluna::Push(L, 1);
#elif defined(WOTLK)
        Eluna::Push(L, 2);
#elif defined(CATA)
        Eluna::Push(L, 3);
#endif
        return 1;
    }
References Eluna::Push().
GetCoreName()
int LuaGlobalFunctions::GetCoreName (lua_State * L)
Returns emulator's name.
The result will be either MaNGOS, cMaNGOS, or TrinityCore.
Returns
string coreName
    {
        Eluna::Push(L, CORE_NAME);
        return 1;
    }
References Eluna::Push().
GetCoreVersion()
int LuaGlobalFunctions::GetCoreVersion (lua_State * L)
Returns emulator version
For TrinityCore returns the date of the last revision, e.g. 2015-08-26 22:53:12 +0300
For cMaNGOS returns the date and time of the last revision, e.g. 2015-09-06 13:18:50
for MaNGOS returns the version number as string, e.g. 21000
Returns
string version
    {
        Eluna::Push(L, CORE_VERSION);
        return 1;
    }
References Eluna::Push().
GetCurrTime()
int LuaGlobalFunctions::GetCurrTime (lua_State * L)
Returns the server's current time.
Returns
uint32 currTime : the current time, in milliseconds
    {
        Eluna::Push(L, ElunaUtil::GetCurrTime());
        return 1;
    }
References ElunaUtil::GetCurrTime(), and Eluna::Push().
GetGameTime()
int LuaGlobalFunctions::GetGameTime (lua_State * L)
Returns game time in seconds
Returns
uint32 time
    {
#ifdef TRINITY
        Eluna::Push(L, GameTime::GetGameTime());
#elif AZEROTHCORE
        Eluna::Push(L, GameTime::GetGameTime().count());
#else
        Eluna::Push(L, eWorld->GetGameTime());
#endif
        return 1;
    }
References eWorld, GameTime::GetGameTime(), and Eluna::Push().
GetGUIDEntry()
int LuaGlobalFunctions::GetGUIDEntry (lua_State * L)
Returns the entry ID from a GUID.
GUID consist of entry ID, low GUID, and type ID.
Parameters
ObjectGuid guid : GUID of an [Creature] or [GameObject]
Returns
uint32 entry : entry ID, or 0 if guid is not a [Creature] or [GameObject]
    {
        ObjectGuid guid = Eluna::CHECKVAL<ObjectGuid>(L, 1);
        Eluna::Push(L, guid.GetEntry());
        return 1;
    }
References ObjectGuid::GetEntry(), GetGUIDEntry(), and Eluna::Push().
Referenced by GetGUIDEntry().
GetGUIDLow()
int LuaGlobalFunctions::GetGUIDLow (lua_State * L)
Returns the low GUID from a GUID.
A GUID consists of a low GUID, type ID, and possibly an entry ID depending on the type ID.
Low GUID is an ID to distinct the objects of the same type.
[Player] and [Creature] for example can have the same low GUID but not GUID.
On TrinityCore all low GUIDs are different for all objects of the same type. For example creatures in instances are assigned new GUIDs when the Map is created.
On MaNGOS and cMaNGOS low GUIDs are unique only on the same map. For example creatures in instances use the same low GUID assigned for that spawn in the database. This is why to identify a creature you have to know the instanceId and low GUID. See [Map:GetIntstanceId]
Parameters
ObjectGuid guid : GUID of an [Object]
Returns
uint32 lowguid : low GUID of the [Object]
    {
        ObjectGuid guid = Eluna::CHECKVAL<ObjectGuid>(L, 1);
        Eluna::Push(L, guid.GetCounter());
        return 1;
    }
References ObjectGuid::GetCounter(), GetGUIDLow(), and Eluna::Push().
Referenced by GetGUIDLow().
GetGUIDType()
int LuaGlobalFunctions::GetGUIDType (lua_State * L)
Returns the type ID from a GUID.
Type ID is different for each type ([Player], [Creature], [GameObject], etc.).
GUID consist of entry ID, low GUID, and type ID.
Parameters
ObjectGuid guid : GUID of an [Object]
Returns
int32 typeId : type ID of the [Object]
    {
        ObjectGuid guid = Eluna::CHECKVAL<ObjectGuid>(L, 1);
        Eluna::Push(L, static_cast<int>(guid.GetHigh()));
        return 1;
    }
References GetGUIDType(), ObjectGuid::GetHigh(), and Eluna::Push().
Referenced by GetGUIDType().
GetGuildByLeaderGUID()
int LuaGlobalFunctions::GetGuildByLeaderGUID (lua_State * L)
Returns [Guild] by the leader's GUID
Parameters
ObjectGuid guid : the guid of a [Guild] leader
Returns
[Guild] guild, or nil if it doesn't exist
    {
        ObjectGuid guid = Eluna::CHECKVAL<ObjectGuid>(L, 1);
        Eluna::Push(L, eGuildMgr->GetGuildByLeader(guid));
        return 1;
    }
References eGuildMgr, GetGuildByLeaderGUID(), and Eluna::Push().
Referenced by GetGuildByLeaderGUID().
GetGuildByName()
int LuaGlobalFunctions::GetGuildByName (lua_State * L)
Returns a [Guild] by name.
Parameters
string name
Returns
[Guild] guild : the Guild, or nil if it doesn't exist
    {
        const char* name = Eluna::CHECKVAL<const char*>(L, 1);
        Eluna::Push(L, eGuildMgr->GetGuildByName(name));
        return 1;
    }
References eGuildMgr, GetGuildByName(), and Eluna::Push().
Referenced by GetGuildByName().
GetItemGUID()
int LuaGlobalFunctions::GetItemGUID (lua_State * L)
Builds an [Item]'s GUID.
[Item] GUID consist of low GUID and type ID [Player] and [Item] for example can have the same low GUID but not GUID.
Parameters
uint32 lowguid : low GUID of the [Item]
Returns
ObjectGuid guid
    {
        uint32 lowguid = Eluna::CHECKVAL<uint32>(L, 1);
        Eluna::Push(L, MAKE_NEW_GUID(lowguid, 0, HIGHGUID_ITEM));
        return 1;
    }
References GetItemGUID(), and Eluna::Push().
Referenced by GetItemGUID().
GetItemLink()
int LuaGlobalFunctions::GetItemLink (lua_State * L)
Returns an chat link for an [Item].
enum LocaleConstant
{
    LOCALE_enUS = 0,
    LOCALE_koKR = 1,
    LOCALE_frFR = 2,
    LOCALE_deDE = 3,
    LOCALE_zhCN = 4,
    LOCALE_zhTW = 5,
    LOCALE_esES = 6,
    LOCALE_esMX = 7,
    LOCALE_ruRU = 8
};
Parameters
uint32 entry : entry ID of an [Item]
[LocaleConstant] locale = DEFAULT_LOCALE : locale to return the [Item] name in
Returns
string itemLink
    {
        uint32 entry = Eluna::CHECKVAL<uint32>(L, 1);
        uint8 locale = Eluna::CHECKVAL<uint8>(L, 2, DEFAULT_LOCALE);
        if (locale >= TOTAL_LOCALES)
            return luaL_argerror(L, 2, "valid LocaleConstant expected");
        const ItemTemplate* temp = eObjectMgr->GetItemTemplate(entry);
        if (!temp)
            return luaL_argerror(L, 1, "valid ItemEntry expected");
        std::string name = temp->Name1;
        if (ItemLocale const* il = eObjectMgr->GetItemLocale(entry))
            ObjectMgr::GetLocaleString(il->Name, static_cast<LocaleConstant>(locale), name);
        std::ostringstream oss;
        oss << "|c" << std::hex << ItemQualityColors[temp->Quality] << std::dec <<
            "|Hitem:" << entry << ":0:" <<
#ifndef CLASSIC
            "0:0:0:0:" <<
#endif
            "0:0:0:0|h[" << name << "]|h|r";
        Eluna::Push(L, oss.str());
        return 1;
    }
References DEFAULT_LOCALE, eObjectMgr, GetItemLink(), ObjectMgr::GetLocaleString(), ItemQualityColors, luaL_argerror(), ItemTemplate::Name1, Eluna::Push(), ItemTemplate::Quality, and TOTAL_LOCALES.
Referenced by GetItemLink().
GetItemTemplate()
int LuaGlobalFunctions::GetItemTemplate (lua_State * L)
    {
        uint32 entry = Eluna::CHECKVAL<uint32>(L, 1);
        Eluna::Push(L, eObjectMgr->GetItemTemplate(entry));
        return 1;
    }
References eObjectMgr, and Eluna::Push().
GetLuaEngine()
int LuaGlobalFunctions::GetLuaEngine (lua_State * L)
Returns Lua engine's name.
Always returns "ElunaEngine" on Eluna.
Returns
string engineName
    {
        Eluna::Push(L, "ElunaEngine");
        return 1;
    }
References Eluna::Push().
GetMapById()
int LuaGlobalFunctions::GetMapById (lua_State * L)
Returns a [Map] by ID.
Parameters
uint32 mapId : see Map.dbc
uint32 instanceId = 0 : required if the map is an instance, otherwise don't pass anything
Returns
[Map] map : the Map, or nil if it doesn't exist
    {
        uint32 mapid = Eluna::CHECKVAL<uint32>(L, 1);
        uint32 instance = Eluna::CHECKVAL<uint32>(L, 2, 0);
        Eluna::Push(L, eMapMgr->FindMap(mapid, instance));
        return 1;
    }
References eMapMgr, GetMapById(), and Eluna::Push().
Referenced by GetMapById().
GetObjectGUID()
int LuaGlobalFunctions::GetObjectGUID (lua_State * L)
Builds a [GameObject]'s GUID.
A GameObject's GUID consist of entry ID, low GUID and type ID
A [Player] and GameObject for example can have the same low GUID but not GUID.
Parameters
uint32 lowguid : low GUID of the [GameObject]
uint32 entry : entry ID of the [GameObject]
Returns
ObjectGuid guid
    {
        uint32 lowguid = Eluna::CHECKVAL<uint32>(L, 1);
        uint32 entry = Eluna::CHECKVAL<uint32>(L, 2);
        Eluna::Push(L, MAKE_NEW_GUID(lowguid, entry, HIGHGUID_GAMEOBJECT));
        return 1;
    }
References GetObjectGUID(), and Eluna::Push().
Referenced by GetObjectGUID().
GetPlayerByGUID()
int LuaGlobalFunctions::GetPlayerByGUID (lua_State * L)
Finds and Returns [Player] by guid if found
Parameters
ObjectGuid guid : guid of the [Player], you can get it with [Object:GetGUID]
Returns
[Player] player
    {
        ObjectGuid guid = Eluna::CHECKVAL<ObjectGuid>(L, 1);
        Eluna::Push(L, eObjectAccessor()FindPlayer(guid));
        return 1;
    }
References eObjectAccessor, and Eluna::Push().
GetPlayerByName()
int LuaGlobalFunctions::GetPlayerByName (lua_State * L)
Finds and Returns [Player] by name if found
Parameters
string name : name of the [Player]
Returns
[Player] player
    {
        const char* name = Eluna::CHECKVAL<const char*>(L, 1);
        Eluna::Push(L, eObjectAccessor()FindPlayerByName(name));
        return 1;
    }
References eObjectAccessor, and Eluna::Push().
GetPlayerCount()
int LuaGlobalFunctions::GetPlayerCount (lua_State * L)
Returns the amount of [Player]s in the world.
Returns
uint32 count
    {
        Eluna::Push(L, eWorld->GetActiveSessionCount());
        return 1;
    }
References eWorld, GetPlayerCount(), and Eluna::Push().
Referenced by GetPlayerCount().
GetPlayerGUID()
int LuaGlobalFunctions::GetPlayerGUID (lua_State * L)
Builds a [Player]'s GUID
[Player] GUID consist of low GUID and type ID
[Player] and [Creature] for example can have the same low GUID but not GUID.
Parameters
uint32 lowguid : low GUID of the [Player]
Returns
ObjectGuid guid
    {
        uint32 lowguid = Eluna::CHECKVAL<uint32>(L, 1);
        Eluna::Push(L, MAKE_NEW_GUID(lowguid, 0, HIGHGUID_PLAYER));
        return 1;
    }
References GetPlayerGUID(), and Eluna::Push().
Referenced by GetPlayerGUID().
GetPlayersInWorld()
int LuaGlobalFunctions::GetPlayersInWorld (lua_State * L)
Returns a table with all the current [Player]s in the world
Does not return players that may be teleporting or otherwise not on any map.
enum TeamId
{
    TEAM_ALLIANCE = 0,
    TEAM_HORDE = 1,
    TEAM_NEUTRAL = 2
};
Parameters
[TeamId] team = TEAM_NEUTRAL : optional check team of the [Player], Alliance, Horde or Neutral (All)
bool onlyGM = false : optional check if GM only
Returns
table worldPlayers
    {
        uint32 team = Eluna::CHECKVAL<uint32>(L, 1, TEAM_NEUTRAL);
        bool onlyGM = Eluna::CHECKVAL<bool>(L, 2, false);
        lua_newtable(L);
        int tbl = lua_gettop(L);
        uint32 i = 0;
#if defined(MANGOS)
        eObjectAccessor()DoForAllPlayers([&](Player* player){
            if(player->IsInWorld())
            {
                if ((team == TEAM_NEUTRAL || player->GetTeamId() == team) && (!onlyGM || player->isGameMaster()))
                {
                    Eluna::Push(L, player);
                    lua_rawseti(L, tbl, ++i);
                }
            }
        });
#else
        {
#if defined TRINITY || AZEROTHCORE
            std::shared_lock<std::shared_mutex> lock(*HashMapHolder<Player>::GetLock());
#else
            HashMapHolder<Player>::ReadGuard g(HashMapHolder<Player>::GetLock());
#endif
            const HashMapHolder<Player>::MapType& m = eObjectAccessor()GetPlayers();
            for (HashMapHolder<Player>::MapType::const_iterator it = m.begin(); it != m.end(); ++it)
            {
                if (Player* player = it->second)
                {
                    if (!player->IsInWorld())
                        continue;
#if defined TRINITY || AZEROTHCORE
                    if ((team == TEAM_NEUTRAL || player->GetTeamId() == team) && (!onlyGM || player->IsGameMaster()))
#else
                    if ((team == TEAM_NEUTRAL || player->GetTeamId() == team) && (!onlyGM || player->isGameMaster()))
#endif
                    {
                        Eluna::Push(L, player);
                        lua_rawseti(L, tbl, ++i);
                    }
                }
            }
        }
#endif
        lua_settop(L, tbl); // push table to top of stack
        return 1;
    }
References eObjectAccessor, Object::IsInWorld(), lua_gettop(), lua_newtable, and TEAM_NEUTRAL.
GetQuest()
int LuaGlobalFunctions::GetQuest (lua_State * L)
Returns [Quest] template
Parameters
uint32 questId : [Quest] entry ID
Returns
[Quest] quest
    {
        uint32 questId = Eluna::CHECKVAL<uint32>(L, 1);
        Eluna::Push(L, eObjectMgr->GetQuestTemplate(questId));
        return 1;
    }
References eObjectMgr, and Eluna::Push().
GetRealmID()
int LuaGlobalFunctions::GetRealmID (lua_State * L)
Returns emulator .conf RealmID
for MaNGOS returns the realmID as it is stored in the core.
for TrinityCore returns the realmID as it is in the conf file.
Returns
uint32 realm ID
    {
#ifdef MANGOS
        Eluna::Push(L, realmID);
#elif defined(AZEROTHCORE)
        Eluna::Push(L, sConfigMgr->GetOption<uint32>("RealmID", 1));
#else
        Eluna::Push(L, sConfigMgr->GetIntDefault("RealmID", 1));
#endif
        return 1;
    }
References Eluna::Push(), and sConfigMgr.
GetStackAsString()
static std::string LuaGlobalFunctions::GetStackAsString (lua_State * L) static
    {
        std::ostringstream oss;
        int top = lua_gettop(L);
        for (int i = 1; i <= top; ++i)
        {
            oss << luaL_tolstring(L, i, NULL);
            lua_pop(L, 1);
        }
        return oss.str();
    }
References GetStackAsString(), lua_gettop(), lua_pop, and luaL_tolstring().
Referenced by GetStackAsString(), PrintDebug(), PrintError(), and PrintInfo().
GetStateInstanceId()
int LuaGlobalFunctions::GetStateInstanceId (lua_State * L)
Returns the instance ID of the Lua state. Returns 0 for continent maps and the world state.
Returns
uint32 instanceId
    {
        // Until AC supports multistate, this will always return 0
        Eluna::Push(L, 0);
        return 1;
    }
References Eluna::Push().
GetStateMap()
int LuaGlobalFunctions::GetStateMap (lua_State * L)
Returns the [Map] pointer of the Lua state. Returns null for the "World" state.
Returns
[Map] map
    {
        // Until AC supports multistate, this will always return nil
        Eluna::Push(L);
        return 1;
    }
References Eluna::Push().
GetStateMapId()
int LuaGlobalFunctions::GetStateMapId (lua_State * L)
Returns the map ID of the Lua state. Returns -1 for the "World" state.
Returns
int32 mapId
    {
        // Until AC supports multistate, this will always return -1
        Eluna::Push(L, -1);
        return 1;
    }
References Eluna::Push().
GetTimeDiff()
int LuaGlobalFunctions::GetTimeDiff (lua_State * L)
Returns the difference between an old timestamp and the current time.
Parameters
uint32 oldTime : an old timestamp, in milliseconds
Returns
uint32 timeDiff : the difference, in milliseconds
    {
        uint32 oldtimems = Eluna::CHECKVAL<uint32>(L, 1);
        Eluna::Push(L, ElunaUtil::GetTimeDiff(oldtimems));
        return 1;
    }
References ElunaUtil::GetTimeDiff(), and Eluna::Push().
GetUnitGUID()
int LuaGlobalFunctions::GetUnitGUID (lua_State * L)
Builds a [Creature]'s GUID.
[Creature] GUID consist of entry ID, low GUID and type ID
[Player] and [Creature] for example can have the same low GUID but not GUID.
Parameters
uint32 lowguid : low GUID of the [Creature]
uint32 entry : entry ID of the [Creature]
Returns
ObjectGuid guid
    {
        uint32 lowguid = Eluna::CHECKVAL<uint32>(L, 1);
        uint32 entry = Eluna::CHECKVAL<uint32>(L, 2);
        Eluna::Push(L, MAKE_NEW_GUID(lowguid, entry, HIGHGUID_UNIT));
        return 1;
    }
References GetUnitGUID(), and Eluna::Push().
Referenced by GetUnitGUID().
HttpRequest()
int LuaGlobalFunctions::HttpRequest (lua_State * L)
Performs a non-blocking HTTP request.
When the passed callback function is called, the parameters (status, body, headers) are passed to it.
-- GET example (prints a random word)
HttpRequest("GET", "https://random-word-api.herokuapp.com/word", function(status, body, headers)
    print("Random word: " .. string.sub(body, 3, body:len() - 2))
end)
-- POST example with JSON request body
HttpRequest("POST", "https://jsonplaceholder.typicode.com/posts", '{"userId": 1,"title": "Foo","body": "Bar!"}', "application/json", function(status, body, headers)
    print(body)
end)
-- Example with request headers
HttpRequest("GET", "https://postman-echo.com/headers", { Accept = "application/json", ["User-Agent"] = "Eluna Lua Engine" }, function(status, body, headers)
    print(body)
end)
@proto (httpMethod, url, function) @proto (httpMethod, url, headers, function) @proto (httpMethod, url, body, contentType, function) @proto (httpMethod, url, body, contentType, headers, function)
Parameters
string httpMethod : the HTTP method to use (possible values are: "GET", "HEAD", "POST", "PUT", "PATCH", "DELETE", "OPTIONS")
string url : the URL to query
table headers : a table with string key-value pairs containing the request headers
string body : the request's body (only used for POST, PUT and PATCH requests)
string contentType : the body's content-type
function function : function that will be called when the request is executed
    {
        std::string httpVerb = Eluna::CHECKVAL<std::string>(L, 1);
        std::string url = Eluna::CHECKVAL<std::string>(L, 2);
        std::string body;
        std::string bodyContentType;
        httplib::Headers headers;
        int headersIdx = 3;
        int callbackIdx = 3;
        if (!lua_istable(L, headersIdx) && lua_isstring(L, headersIdx) && lua_isstring(L, headersIdx + 1))
        {
            body = Eluna::CHECKVAL<std::string>(L, 3);
            bodyContentType = Eluna::CHECKVAL<std::string>(L, 4);
            headersIdx = 5;
            callbackIdx = 5;
        }
        if (lua_istable(L, headersIdx))
        {
            ++callbackIdx;
            lua_pushnil(L); // First key
            while (lua_next(L, headersIdx) != 0)
            {
                // Uses 'key' (at index -2) and 'value' (at index -1)
                if (lua_isstring(L, -2))
                {
                    std::string key(lua_tostring(L, -2));
                    std::string value(lua_tostring(L, -1));
                    headers.insert(std::pair<std::string, std::string>(key, value));
                }
                // Removes 'value'; keeps 'key' for next iteration
                lua_pop(L, 1);
            }
        }
        lua_pushvalue(L, callbackIdx);
        int funcRef = luaL_ref(L, LUA_REGISTRYINDEX);
        if (funcRef >= 0)
        {
            Eluna::GEluna->httpManager.PushRequest(new HttpWorkItem(funcRef, httpVerb, url, body, bodyContentType, headers));
        }
        else
        {
            luaL_argerror(L, callbackIdx, "unable to make a ref to function");
        }
        return 0;
    }
References Eluna::GEluna, Eluna::httpManager, HttpRequest(), lua_isstring(), lua_istable, lua_next(), lua_pop, lua_pushnil(), lua_pushvalue(), LUA_REGISTRYINDEX, lua_tostring, luaL_argerror(), luaL_ref(), and HttpManager::PushRequest().
Referenced by HttpRequest().
IsBagPos()
int LuaGlobalFunctions::IsBagPos (lua_State * L)
Returns true if the bag and slot is a valid bag position, otherwise false.
See [Global:IsInventoryPos] for bag/slot combination examples.
Parameters
uint8 bag : the bag the [Item] is in, you can get this with [Item:GetBagSlot]
uint8 slot : the slot the [Item] is in within the bag, you can get this with [Item:GetSlot]
Returns
bool isBagPosition
    {
        uint8 bag = Eluna::CHECKVAL<uint8>(L, 1);
        uint8 slot = Eluna::CHECKVAL<uint8>(L, 2);
        Eluna::Push(L, Player::IsBagPos((bag << 8) + slot));
        return 1;
    }
References IsBagPos(), Player::IsBagPos(), and Eluna::Push().
Referenced by IsBagPos().
IsBankPos()
int LuaGlobalFunctions::IsBankPos (lua_State * L)
Returns true if the bag and slot is a valid bank position, otherwise false.
See [Global:IsInventoryPos] for bag/slot combination examples.
Parameters
uint8 bag : the bag the [Item] is in, you can get this with [Item:GetBagSlot]
uint8 slot : the slot the [Item] is in within the bag, you can get this with [Item:GetSlot]
Returns
bool isBankPosition
    {
        uint8 bag = Eluna::CHECKVAL<uint8>(L, 1);
        uint8 slot = Eluna::CHECKVAL<uint8>(L, 2);
        Eluna::Push(L, Player::IsBankPos(bag, slot));
        return 1;
    }
References IsBankPos(), Player::IsBankPos(), and Eluna::Push().
Referenced by IsBankPos().
IsCompatibilityMode()
int LuaGlobalFunctions::IsCompatibilityMode (lua_State * L)
Returns true if Eluna is in compatibility mode, false if in multistate.
Returns
bool isCompatibilityMode
    {
        // Until AC supports multistate, this will always return true
        Eluna::Push(L, true);
        return 1;
    }
References IsCompatibilityMode(), and Eluna::Push().
Referenced by IsCompatibilityMode().
IsEquipmentPos()
int LuaGlobalFunctions::IsEquipmentPos (lua_State * L)
Returns true if the bag and slot is a valid equipment position, otherwise false.
See [Global:IsInventoryPos] for bag/slot combination examples.
Parameters
uint8 bag : the bag the [Item] is in, you can get this with [Item:GetBagSlot]
uint8 slot : the slot the [Item] is in within the bag, you can get this with [Item:GetSlot]
Returns
bool isEquipmentPosition
    {
        uint8 bag = Eluna::CHECKVAL<uint8>(L, 1);
        uint8 slot = Eluna::CHECKVAL<uint8>(L, 2);
        Eluna::Push(L, Player::IsEquipmentPos(bag, slot));
        return 1;
    }
References IsEquipmentPos(), Player::IsEquipmentPos(), and Eluna::Push().
Referenced by IsEquipmentPos().
IsGameEventActive()
int LuaGlobalFunctions::IsGameEventActive (lua_State * L)
Returns true if the event is currently active, otherwise false.
Parameters
uint16 eventId : the event id to check.
Returns
bool isActive
    {
        uint16 eventId = Eluna::CHECKVAL<uint16>(L, 1);
        Eluna::Push(L, eGameEventMgr->IsActiveEvent(eventId));
        return 1;
    }
References eGameEventMgr, IsGameEventActive(), and Eluna::Push().
Referenced by IsGameEventActive().
IsInventoryPos()
int LuaGlobalFunctions::IsInventoryPos (lua_State * L)
Returns true if the bag and slot is a valid inventory position, otherwise false.
Some commonly used combinations:
Bag 255 (common character inventory)
Slots 0-18: equipment
Slots 19-22: bag slots
Slots 23-38: backpack
Slots 39-66: bank main slots
Slots 67-74: bank bag slots
Slots 86-117: keyring
Bags 19-22 (equipped bags)
Slots 0-35
Bags 67-74 (bank bags)
Slots 0-35
Parameters
uint8 bag : the bag the [Item] is in, you can get this with [Item:GetBagSlot]
uint8 slot : the slot the [Item] is in within the bag, you can get this with [Item:GetSlot]
Returns
bool isInventoryPos
    {
        uint8 bag = Eluna::CHECKVAL<uint8>(L, 1);
        uint8 slot = Eluna::CHECKVAL<uint8>(L, 2);
        Eluna::Push(L, Player::IsInventoryPos(bag, slot));
        return 1;
    }
References IsInventoryPos(), Player::IsInventoryPos(), and Eluna::Push().
Referenced by IsInventoryPos().
Kick()
int LuaGlobalFunctions::Kick (lua_State * L)
Kicks a [Player] from the server.
Parameters
[Player] player : [Player] to kick
    {
        Player* player = Eluna::CHECKOBJ<Player>(L, 1);
#ifdef TRINITY
        player->GetSession()->KickPlayer("GlobalMethods::Kick Kick the player");
#else
        player->GetSession()->KickPlayer();
#endif
        return 0;
    }
References Player::GetSession(), Kick(), and WorldSession::KickPlayer().
Referenced by Kick().
PerformIngameSpawn()
int LuaGlobalFunctions::PerformIngameSpawn (lua_State * L)
Performs an in-game spawn and returns the [Creature] or [GameObject] spawned.
Parameters
int32 spawnType : type of object to spawn, 1 = [Creature], 2 = [GameObject]
uint32 entry : entry ID of the [Creature] or [GameObject]
uint32 mapId : map ID to spawn the [Creature] or [GameObject] in
uint32 instanceId : instance ID to put the [Creature] or [GameObject] in. Non instance is 0
float x : x coordinate of the [Creature] or [GameObject]
float y : y coordinate of the [Creature] or [GameObject]
float z : z coordinate of the [Creature] or [GameObject]
float o : o facing/orientation of the [Creature] or [GameObject]
bool save = false : optional to save the [Creature] or [GameObject] to the database
uint32 durorresptime = 0 : despawn time of the [Creature] if it's not saved or respawn time of [GameObject]
uint32 phase = 1 : phase to put the [Creature] or [GameObject] in
Returns
[WorldObject] worldObject : returns [Creature] or [GameObject]
    {
        int spawntype = Eluna::CHECKVAL<int>(L, 1);
        uint32 entry = Eluna::CHECKVAL<uint32>(L, 2);
        uint32 mapID = Eluna::CHECKVAL<uint32>(L, 3);
        uint32 instanceID = Eluna::CHECKVAL<uint32>(L, 4);
        float x = Eluna::CHECKVAL<float>(L, 5);
        float y = Eluna::CHECKVAL<float>(L, 6);
        float z = Eluna::CHECKVAL<float>(L, 7);
        float o = Eluna::CHECKVAL<float>(L, 8);
        bool save = Eluna::CHECKVAL<bool>(L, 9, false);
        uint32 durorresptime = Eluna::CHECKVAL<uint32>(L, 10, 0);
#if (!defined(TBC) && !defined(CLASSIC))
        uint32 phase = Eluna::CHECKVAL<uint32>(L, 11, PHASEMASK_NORMAL);
        if (!phase)
        {
            Eluna::Push(L);
            return 1;
        }
#endif
#if !defined TRINITY && !AZEROTHCORE
        Map* map = eMapMgr->FindMap(mapID, instanceID);
        if (!map)
        {
            Eluna::Push(L);
            return 1;
        }
        if (spawntype == 1) // spawn creature
        {
            if (save)
            {
                CreatureInfo const* cinfo = ObjectMgr::GetCreatureTemplate(entry);
                if (!cinfo)
                {
                    Eluna::Push(L);
                    return 1;
                }
#if (defined(TBC) || defined(CLASSIC))
                CreatureCreatePos pos(map, x, y, z, o);
#else
                CreatureCreatePos pos(map, x, y, z, o, phase);
#endif
                Creature* pCreature = new Creature;
                // used guids from specially reserved range (can be 0 if no free values)
                uint32 lowguid = eObjectMgr->GenerateStaticCreatureLowGuid();
                if (!lowguid)
                {
                    Eluna::Push(L);
                    return 1;
                }
                if (!pCreature->Create(lowguid, pos, cinfo))
                {
                    delete pCreature;
                    Eluna::Push(L);
                    return 1;
                }
#ifdef TBC
                pCreature->SaveToDB(map->GetId(), (1 << map->GetSpawnMode()));
#elif defined(CLASSIC)
                pCreature->SaveToDB(map->GetId());
#else
                pCreature->SaveToDB(map->GetId(), (1 << map->GetSpawnMode()), phase);
#endif
                uint32 db_guid = pCreature->GetGUIDLow();
                // To call _LoadGoods(); _LoadQuests(); CreateTrainerSpells();
                pCreature->LoadFromDB(db_guid, map);
                map->Add(pCreature);
                eObjectMgr->AddCreatureToGrid(db_guid, eObjectMgr->GetCreatureData(db_guid));
                if (durorresptime)
                    pCreature->ForcedDespawn(durorresptime);
                Eluna::Push(L, pCreature);
            }
            else
            {
                CreatureInfo const* cinfo = ObjectMgr::GetCreatureTemplate(entry);
                if (!cinfo)
                {
                    Eluna::Push(L);
                    return 1;
                }
                TemporarySummon* pCreature = new TemporarySummon(ObjectGuid(uint64(0)));
#if (defined(TBC) || defined(CLASSIC))
                CreatureCreatePos pos(map, x, y, z, o);
#else
                CreatureCreatePos pos(map, x, y, z, o, phase);
#endif
                if (!pCreature->Create(map->GenerateLocalLowGuid(cinfo->GetHighGuid()), pos, cinfo, TEAM_NONE))
                {
                    delete pCreature;
                    {
                        Eluna::Push(L);
                        return 1;
                    }
                }
                pCreature->SetRespawnCoord(pos);
                // Active state set before added to map
                pCreature->SetActiveObjectState(false);
                // Also initializes the AI and MMGen
                pCreature->Summon(durorresptime ? TEMPSPAWN_TIMED_OR_DEAD_DESPAWN : TEMPSPAWN_MANUAL_DESPAWN, durorresptime);
                // Creature Linking, Initial load is handled like respawn
                if (pCreature->IsLinkingEventTrigger())
                    map->GetCreatureLinkingHolder()->DoCreatureLinkingEvent(LINKING_EVENT_RESPAWN, pCreature);
                Eluna::Push(L, pCreature);
            }
            return 1;
        }
        if (spawntype == 2) // Spawn object
        {
            if (save)
            {
                const GameObjectInfo* gInfo = ObjectMgr::GetGameObjectInfo(entry);
                if (!gInfo)
                {
                    Eluna::Push(L);
                    return 1;
                }
                // used guids from specially reserved range (can be 0 if no free values)
                uint32 db_lowGUID = eObjectMgr->GenerateStaticGameObjectLowGuid();
                if (!db_lowGUID)
                {
                    Eluna::Push(L);
                    return 1;
                }
                GameObject* pGameObj = new GameObject;
#if (defined(TBC) || defined(CLASSIC))
                if (!pGameObj->Create(db_lowGUID, gInfo->id, map, x, y, z, o))
#else
                if (!pGameObj->Create(db_lowGUID, gInfo->id, map, phase, x, y, z, o))
#endif
                {
                    delete pGameObj;
                    Eluna::Push(L);
                    return 1;
                }
                if (durorresptime)
                    pGameObj->SetRespawnTime(durorresptime);
                // fill the gameobject data and save to the db
#ifdef TBC
                pGameObj->SaveToDB(map->GetId(), (1 << map->GetSpawnMode()));
#elif defined(CLASSIC)
                pGameObj->SaveToDB(map->GetId());
#else
                pGameObj->SaveToDB(map->GetId(), (1 << map->GetSpawnMode()), phase);
#endif
                // this will generate a new guid if the object is in an instance
                if (!pGameObj->LoadFromDB(db_lowGUID, map))
                {
                    delete pGameObj;
                    Eluna::Push(L);
                    return 1;
                }
                // DEBUG_LOG(GetMangosString(LANG_GAMEOBJECT_CURRENT), gInfo->name, db_lowGUID, x, y, z, o);
                map->Add(pGameObj);
                pGameObj->AIM_Initialize();
                eObjectMgr->AddGameobjectToGrid(db_lowGUID, eObjectMgr->GetGOData(db_lowGUID));
                Eluna::Push(L, pGameObj);
            }
            else
            {
                GameObject* pGameObj = new GameObject;
#if (defined(TBC) || defined(CLASSIC))
                if (!pGameObj->Create(map->GenerateLocalLowGuid(HIGHGUID_GAMEOBJECT), entry, map, x, y, z, o))
#else
                if (!pGameObj->Create(map->GenerateLocalLowGuid(HIGHGUID_GAMEOBJECT), entry, map, phase, x, y, z, o))
#endif
                {
                    delete pGameObj;
                    Eluna::Push(L);
                    return 1;
                }
                pGameObj->SetRespawnTime(durorresptime / IN_MILLISECONDS);
                map->Add(pGameObj);
                pGameObj->AIM_Initialize();
                Eluna::Push(L, pGameObj);
            }
            return 1;
        }
#else
        Map* map = eMapMgr->FindMap(mapID, instanceID);
        if (!map)
        {
            Eluna::Push(L);
            return 1;
        }
        Position pos = { x, y, z, o };
        if (spawntype == 1) // spawn creature
        {
            if (save)
            {
                Creature* creature = new Creature();
#ifndef AZEROTHCORE
                if (!creature->Create(map->GenerateLowGuid<HighGuid::Unit>(), map, phase, entry, pos))
#else
                if (!creature->Create(map->GenerateLowGuid<HighGuid::Unit>(), map, phase, entry, 0, x, y, z, o))
#endif
                {
                    delete creature;
                    Eluna::Push(L);
                    return 1;
                }
                creature->SaveToDB(map->GetId(), (1 << map->GetSpawnMode()), phase);
                uint32 db_guid = creature->GetSpawnId();
                // To call _LoadGoods(); _LoadQuests(); CreateTrainerSpells()
                // current "creature" variable is deleted and created fresh new, otherwise old values might trigger asserts or cause undefined behavior
                creature->CleanupsBeforeDelete();
                delete creature;
                creature = new Creature();
#ifndef AZEROTHCORE
                if (!creature->LoadFromDB(db_guid, map, true, true))
#else
                if (!creature->LoadFromDB(db_guid, map, true))
#endif
                {
                    delete creature;
                    Eluna::Push(L);
                    return 1;
                }
                eObjectMgr->AddCreatureToGrid(db_guid, eObjectMgr->GetCreatureData(db_guid));
                Eluna::Push(L, creature);
            }
            else
            {
                TempSummon* creature = map->SummonCreature(entry, pos, NULL, durorresptime);
                if (!creature)
                {
                    Eluna::Push(L);
                    return 1;
                }
                if (durorresptime)
                    creature->SetTempSummonType(TEMPSUMMON_TIMED_OR_DEAD_DESPAWN);
                else
                    creature->SetTempSummonType(TEMPSUMMON_MANUAL_DESPAWN);
                Eluna::Push(L, creature);
            }
            return 1;
        }
        if (spawntype == 2) // Spawn object
        {
            const GameObjectTemplate* objectInfo = eObjectMgr->GetGameObjectTemplate(entry);
            if (!objectInfo)
            {
                Eluna::Push(L);
                return 1;
            }
            if (objectInfo->displayId && !sGameObjectDisplayInfoStore.LookupEntry(objectInfo->displayId))
            {
                Eluna::Push(L);
                return 1;
            }
            GameObject* object = new GameObject;
#ifndef AZEROTHCORE
            uint32 guidLow = map->GenerateLowGuid<HighGuid::GameObject>();
            QuaternionData rot = QuaternionData::fromEulerAnglesZYX(o, 0.f, 0.f);
            if (!object->Create(guidLow, objectInfo->entry, map, phase, Position(x, y, z, o), rot, 0, GO_STATE_READY))
#else
            uint32 guidLow = map->GenerateLowGuid<HighGuid::GameObject>();
            if (!object->Create(guidLow, entry, map, phase, x, y, z, o, G3D::Quat(0.0f, 0.0f, 0.0f, 0.0f), 100, GO_STATE_READY))
#endif
            {
                delete object;
                Eluna::Push(L);
                return 1;
            }
            if (durorresptime)
                object->SetRespawnTime(durorresptime);
            if (save)
            {
                // fill the gameobject data and save to the db
                object->SaveToDB(map->GetId(), (1 << map->GetSpawnMode()), phase);
                guidLow = object->GetSpawnId();
                // delete the old object and do a clean load from DB with a fresh new GameObject instance.
                // this is required to avoid weird behavior and memory leaks
                delete object;
                object = new GameObject();
                // this will generate a new lowguid if the object is in an instance
#ifndef AZEROTHCORE
                if (!object->LoadFromDB(guidLow, map, true))
#else
                if (!object->LoadFromDB(guidLow, map))
#endif
                {
                    delete object;
                    Eluna::Push(L);
                    return 1;
                }
                eObjectMgr->AddGameobjectToGrid(guidLow, eObjectMgr->GetGameObjectData(guidLow));
            }
            else
                map->AddToMap(object);
            Eluna::Push(L, object);
            return 1;
        }
#endif
        Eluna::Push(L);
        return 1;
    }
References Map::AddToMap(), GameObject::AIM_Initialize(), Unit::CleanupsBeforeDelete(), Creature::Create(), GameObject::Create(), GameObjectTemplate::displayId, eMapMgr, GameObjectTemplate::entry, eObjectMgr, Creature::ForcedDespawn(), GameObject, Map::GenerateLowGuid(), ObjectMgr::GetCreatureTemplate(), Map::GetId(), Creature::GetSpawnId(), Map::GetSpawnMode(), GO_STATE_READY, IN_MILLISECONDS, GameObject::LoadFromDB(), Creature::LoadFromDB(), PerformIngameSpawn(), PHASEMASK_NORMAL, Eluna::Push(), Creature::SaveToDB(), GameObject::SaveToDB(), GameObject::SetRespawnTime(), TempSummon::SetTempSummonType(), sGameObjectDisplayInfoStore, Map::SummonCreature(), TEMPSUMMON_MANUAL_DESPAWN, TEMPSUMMON_TIMED_OR_DEAD_DESPAWN, and Unit.
Referenced by PerformIngameSpawn().
PrintDebug()
int LuaGlobalFunctions::PrintDebug (lua_State * L)
Prints given parameters to the debug log.
Parameters
...
    {
        ELUNA_LOG_DEBUG("{}", GetStackAsString(L));
        return 0;
    }
References ELUNA_LOG_DEBUG, GetStackAsString(), and PrintDebug().
Referenced by PrintDebug().
PrintError()
int LuaGlobalFunctions::PrintError (lua_State * L)
Prints given parameters to the error log.
Parameters
...
    {
        ELUNA_LOG_ERROR("{}", GetStackAsString(L));
        return 0;
    }
References ELUNA_LOG_ERROR, GetStackAsString(), and PrintError().
Referenced by PrintError().
PrintInfo()
int LuaGlobalFunctions::PrintInfo (lua_State * L)
Prints given parameters to the info log.
Parameters
...
    {
        ELUNA_LOG_INFO("{}", GetStackAsString(L));
        return 0;
    }
References ELUNA_LOG_INFO, GetStackAsString(), and PrintInfo().
Referenced by PrintInfo().
RegisterBGEvent()
int LuaGlobalFunctions::RegisterBGEvent (lua_State * L)
Registers a [BattleGround] event handler.
enum BGEvents
{
    BG_EVENT_ON_START                               = 1,    // (event, bg, bgId, instanceId) - Needs to be added to TC
    BG_EVENT_ON_END                                 = 2,    // (event, bg, bgId, instanceId, winner) - Needs to be added to TC
    BG_EVENT_ON_CREATE                              = 3,    // (event, bg, bgId, instanceId) - Needs to be added to TC
    BG_EVENT_ON_PRE_DESTROY                         = 4,    // (event, bg, bgId, instanceId) - Needs to be added to TC
    BG_EVENT_COUNT
};
@proto cancel = (event, function) @proto cancel = (event, function, shots)
Parameters
uint32 event : [BattleGround] event Id, refer to BGEvents above
function function : function to register
uint32 shots = 0 : the number of times the function will be called, 0 means "always call this function"
Returns
function cancel : a function that cancels the binding when called
    {
        return RegisterEventHelper(L, Hooks::REGTYPE_BG);
    }
References RegisterBGEvent(), RegisterEventHelper(), and Hooks::REGTYPE_BG.
Referenced by RegisterBGEvent().
RegisterCreatureEvent()
int LuaGlobalFunctions::RegisterCreatureEvent (lua_State * L)
Registers a [Creature] event handler.
enum CreatureEvents
{
    CREATURE_EVENT_ON_ENTER_COMBAT                    = 1,  // (event, creature, target) - Can return true to stop normal action
    CREATURE_EVENT_ON_LEAVE_COMBAT                    = 2,  // (event, creature) - Can return true to stop normal action
    CREATURE_EVENT_ON_TARGET_DIED                     = 3,  // (event, creature, victim) - Can return true to stop normal action
    CREATURE_EVENT_ON_DIED                            = 4,  // (event, creature, killer) - Can return true to stop normal action
    CREATURE_EVENT_ON_SPAWN                           = 5,  // (event, creature) - Can return true to stop normal action
    CREATURE_EVENT_ON_REACH_WP                        = 6,  // (event, creature, type, id) - Can return true to stop normal action
    CREATURE_EVENT_ON_AIUPDATE                        = 7,  // (event, creature, diff) - Can return true to stop normal action
    CREATURE_EVENT_ON_RECEIVE_EMOTE                   = 8,  // (event, creature, player, emoteid) - Can return true to stop normal action
    CREATURE_EVENT_ON_DAMAGE_TAKEN                    = 9,  // (event, creature, attacker, damage) - Can return true to stop normal action, can return new damage as second return value.
    CREATURE_EVENT_ON_PRE_COMBAT                      = 10, // (event, creature, target) - Can return true to stop normal action
    // UNUSED
    CREATURE_EVENT_ON_OWNER_ATTACKED                  = 12, // (event, creature, target) - Can return true to stop normal action            // Not on mangos
    CREATURE_EVENT_ON_OWNER_ATTACKED_AT               = 13, // (event, creature, attacker) - Can return true to stop normal action          // Not on mangos
    CREATURE_EVENT_ON_HIT_BY_SPELL                    = 14, // (event, creature, caster, spellid) - Can return true to stop normal action
    CREATURE_EVENT_ON_SPELL_HIT_TARGET                = 15, // (event, creature, target, spellid) - Can return true to stop normal action
    // UNUSED                                         = 16, // (event, creature)
    // UNUSED                                         = 17, // (event, creature)
    // UNUSED                                         = 18, // (event, creature)
    CREATURE_EVENT_ON_JUST_SUMMONED_CREATURE          = 19, // (event, creature, summon) - Can return true to stop normal action
    CREATURE_EVENT_ON_SUMMONED_CREATURE_DESPAWN       = 20, // (event, creature, summon) - Can return true to stop normal action
    CREATURE_EVENT_ON_SUMMONED_CREATURE_DIED          = 21, // (event, creature, summon, killer) - Can return true to stop normal action    // Not on mangos
    CREATURE_EVENT_ON_SUMMONED                        = 22, // (event, creature, summoner) - Can return true to stop normal action
    CREATURE_EVENT_ON_RESET                           = 23, // (event, creature)
    CREATURE_EVENT_ON_REACH_HOME                      = 24, // (event, creature) - Can return true to stop normal action
    // UNUSED                                         = 25, // (event, creature)
    CREATURE_EVENT_ON_CORPSE_REMOVED                  = 26, // (event, creature, respawndelay) - Can return true to stop normal action, can return new respawndelay as second return value
    CREATURE_EVENT_ON_MOVE_IN_LOS                     = 27, // (event, creature, unit) - Can return true to stop normal action. Does not actually check LOS, just uses the sight range
    // UNUSED                                         = 28, // (event, creature)
    // UNUSED                                         = 29, // (event, creature)
    CREATURE_EVENT_ON_DUMMY_EFFECT                    = 30, // (event, caster, spellid, effindex, creature)
    CREATURE_EVENT_ON_QUEST_ACCEPT                    = 31, // (event, player, creature, quest) - Can return true
    // UNUSED                                         = 32, // (event, creature)
    // UNUSED                                         = 33, // (event, creature)
    CREATURE_EVENT_ON_QUEST_REWARD                    = 34, // (event, player, creature, quest, opt) - Can return true
    CREATURE_EVENT_ON_DIALOG_STATUS                   = 35, // (event, player, creature)
    CREATURE_EVENT_ON_ADD                             = 36, // (event, creature)
    CREATURE_EVENT_ON_REMOVE                          = 37, // (event, creature)
    CREATURE_EVENT_COUNT
};
@proto cancel = (entry, event, function) @proto cancel = (entry, event, function, shots)
Parameters
uint32 entry : the ID of one or more [Creature]s
uint32 event : refer to CreatureEvents above
function function : function that will be called when the event occurs
uint32 shots = 0 : the number of times the function will be called, 0 means "always call this function"
Returns
function cancel : a function that cancels the binding when called
    {
        return RegisterEntryHelper(L, Hooks::REGTYPE_CREATURE);
    }
References RegisterCreatureEvent(), RegisterEntryHelper(), and Hooks::REGTYPE_CREATURE.
Referenced by RegisterCreatureEvent().
RegisterCreatureGossipEvent()
int LuaGlobalFunctions::RegisterCreatureGossipEvent (lua_State * L)
Registers a [Creature] gossip event handler.
enum GossipEvents
{
    GOSSIP_EVENT_ON_HELLO                           = 1,    // (event, player, object) - Object is the Creature/GameObject/Item. Can return false to do default action. For item gossip can return false to stop spell casting.
    GOSSIP_EVENT_ON_SELECT                          = 2,    // (event, player, object, sender, intid, code, menu_id) - Object is the Creature/GameObject/Item/Player, menu_id is only for player gossip. Can return false to do default action.
    GOSSIP_EVENT_COUNT
};
@proto cancel = (entry, event, function) @proto cancel = (entry, event, function, shots)
Parameters
uint32 entry : [Creature] entry Id
uint32 event : [Creature] gossip event Id, refer to GossipEvents above
function function : function to register
uint32 shots = 0 : the number of times the function will be called, 0 means "always call this function"
Returns
function cancel : a function that cancels the binding when called
    {
        return RegisterEntryHelper(L, Hooks::REGTYPE_CREATURE_GOSSIP);
    }
References RegisterCreatureGossipEvent(), RegisterEntryHelper(), and Hooks::REGTYPE_CREATURE_GOSSIP.
Referenced by RegisterCreatureGossipEvent().
RegisterEntryHelper()
static int LuaGlobalFunctions::RegisterEntryHelper (lua_State * L, int regtype) static
    {
        uint32 id = Eluna::CHECKVAL<uint32>(L, 1);
        uint32 ev = Eluna::CHECKVAL<uint32>(L, 2);
        luaL_checktype(L, 3, LUA_TFUNCTION);
        uint32 shots = Eluna::CHECKVAL<uint32>(L, 4, 0);
        lua_pushvalue(L, 3);
        int functionRef = luaL_ref(L, LUA_REGISTRYINDEX);
        if (functionRef >= 0)
            return Eluna::GetEluna(L)->Register(L, regtype, id, ObjectGuid(), 0, ev, functionRef, shots);
        else
            luaL_argerror(L, 3, "unable to make a ref to function");
        return 0;
    }
References Eluna::GetEluna(), lua_pushvalue(), LUA_REGISTRYINDEX, LUA_TFUNCTION, luaL_argerror(), luaL_checktype(), luaL_ref(), Eluna::Register(), and RegisterEntryHelper().
Referenced by RegisterCreatureEvent(), RegisterCreatureGossipEvent(), RegisterEntryHelper(), RegisterGameObjectEvent(), RegisterGameObjectGossipEvent(), RegisterInstanceEvent(), RegisterItemEvent(), RegisterItemGossipEvent(), RegisterMapEvent(), RegisterPacketEvent(), and RegisterPlayerGossipEvent().
RegisterEventHelper()
static int LuaGlobalFunctions::RegisterEventHelper (lua_State * L, int regtype) static
    {
        uint32 ev = Eluna::CHECKVAL<uint32>(L, 1);
        luaL_checktype(L, 2, LUA_TFUNCTION);
        uint32 shots = Eluna::CHECKVAL<uint32>(L, 3, 0);
        lua_pushvalue(L, 2);
        int functionRef = luaL_ref(L, LUA_REGISTRYINDEX);
        if (functionRef >= 0)
            return Eluna::GetEluna(L)->Register(L, regtype, 0, ObjectGuid(), 0, ev, functionRef, shots);
        else
            luaL_argerror(L, 2, "unable to make a ref to function");
        return 0;
    }
References Eluna::GetEluna(), lua_pushvalue(), LUA_REGISTRYINDEX, LUA_TFUNCTION, luaL_argerror(), luaL_checktype(), luaL_ref(), Eluna::Register(), and RegisterEventHelper().
Referenced by RegisterBGEvent(), RegisterEventHelper(), RegisterGroupEvent(), RegisterGuildEvent(), RegisterPlayerEvent(), and RegisterServerEvent().
RegisterGameObjectEvent()
int LuaGlobalFunctions::RegisterGameObjectEvent (lua_State * L)
Registers a [GameObject] event handler.
enum GameObjectEvents
{
    GAMEOBJECT_EVENT_ON_AIUPDATE                    = 1,    // (event, go, diff)
    GAMEOBJECT_EVENT_ON_SPAWN                       = 2,    // (event, go)
    GAMEOBJECT_EVENT_ON_DUMMY_EFFECT                = 3,    // (event, caster, spellid, effindex, go) - Can return true to stop normal action
    GAMEOBJECT_EVENT_ON_QUEST_ACCEPT                = 4,    // (event, player, go, quest) - Can return true to stop normal action
    GAMEOBJECT_EVENT_ON_QUEST_REWARD                = 5,    // (event, player, go, quest, opt) - Can return true to stop normal action
    GAMEOBJECT_EVENT_ON_DIALOG_STATUS               = 6,    // (event, player, go)
    GAMEOBJECT_EVENT_ON_DESTROYED                   = 7,    // (event, go, attacker)
    GAMEOBJECT_EVENT_ON_DAMAGED                     = 8,    // (event, go, attacker)
    GAMEOBJECT_EVENT_ON_LOOT_STATE_CHANGE           = 9,    // (event, go, state)
    GAMEOBJECT_EVENT_ON_GO_STATE_CHANGED            = 10,   // (event, go, state)
    // UNUSED                                       = 11,   // (event, gameobject)
    GAMEOBJECT_EVENT_ON_ADD                         = 12,   // (event, gameobject)
    GAMEOBJECT_EVENT_ON_REMOVE                      = 13,   // (event, gameobject)
    GAMEOBJECT_EVENT_ON_USE                         = 14,   // (event, go, player) - Can return true to stop normal action
    GAMEOBJECT_EVENT_COUNT
};
@proto cancel = (entry, event, function) @proto cancel = (entry, event, function, shots)
Parameters
uint32 entry : [GameObject] entry Id
uint32 event : [GameObject] event Id, refer to GameObjectEvents above
function function : function to register
uint32 shots = 0 : the number of times the function will be called, 0 means "always call this function"
Returns
function cancel : a function that cancels the binding when called
    {
        return RegisterEntryHelper(L, Hooks::REGTYPE_GAMEOBJECT);
    }
References RegisterEntryHelper(), RegisterGameObjectEvent(), and Hooks::REGTYPE_GAMEOBJECT.
Referenced by RegisterGameObjectEvent().
RegisterGameObjectGossipEvent()
int LuaGlobalFunctions::RegisterGameObjectGossipEvent (lua_State * L)
Registers a [GameObject] gossip event handler.
enum GossipEvents
{
    GOSSIP_EVENT_ON_HELLO                           = 1,    // (event, player, object) - Object is the Creature/GameObject/Item. Can return false to do default action. For item gossip can return false to stop spell casting.
    GOSSIP_EVENT_ON_SELECT                          = 2,    // (event, player, object, sender, intid, code, menu_id) - Object is the Creature/GameObject/Item/Player, menu_id is only for player gossip. Can return false to do default action.
    GOSSIP_EVENT_COUNT
};
@proto cancel = (entry, event, function) @proto cancel = (entry, event, function, shots)
Parameters
uint32 entry : [GameObject] entry Id
uint32 event : [GameObject] gossip event Id, refer to GossipEvents above
function function : function to register
uint32 shots = 0 : the number of times the function will be called, 0 means "always call this function"
Returns
function cancel : a function that cancels the binding when called
    {
        return RegisterEntryHelper(L, Hooks::REGTYPE_GAMEOBJECT_GOSSIP);
    }
References RegisterEntryHelper(), RegisterGameObjectGossipEvent(), and Hooks::REGTYPE_GAMEOBJECT_GOSSIP.
Referenced by RegisterGameObjectGossipEvent().
RegisterGroupEvent()
int LuaGlobalFunctions::RegisterGroupEvent (lua_State * L)
Registers a [Group] event handler.
enum GroupEvents
{
    // Group
    GROUP_EVENT_ON_MEMBER_ADD               =     1,       // (event, group, guid)
    GROUP_EVENT_ON_MEMBER_INVITE            =     2,       // (event, group, guid)
    GROUP_EVENT_ON_MEMBER_REMOVE            =     3,       // (event, group, guid, method, kicker, reason)
    GROUP_EVENT_ON_LEADER_CHANGE            =     4,       // (event, group, newLeaderGuid, oldLeaderGuid)
    GROUP_EVENT_ON_DISBAND                  =     5,       // (event, group)
    GROUP_EVENT_ON_CREATE                   =     6,       // (event, group, leaderGuid, groupType)
    GROUP_EVENT_COUNT
};
@proto cancel = (event, function) @proto cancel = (event, function, shots)
Parameters
uint32 event : [Group] event Id, refer to GroupEvents above
function function : function to register
uint32 shots = 0 : the number of times the function will be called, 0 means "always call this function"
Returns
function cancel : a function that cancels the binding when called
    {
        return RegisterEventHelper(L, Hooks::REGTYPE_GROUP);
    }
References RegisterEventHelper(), RegisterGroupEvent(), and Hooks::REGTYPE_GROUP.
Referenced by RegisterGroupEvent().
RegisterGuildEvent()
int LuaGlobalFunctions::RegisterGuildEvent (lua_State * L)
Registers a [Guild] event handler.
enum GuildEvents
{
    // Guild
    GUILD_EVENT_ON_ADD_MEMBER               =     1,       // (event, guild, player, rank)
    GUILD_EVENT_ON_REMOVE_MEMBER            =     2,       // (event, guild, player, isDisbanding)
    GUILD_EVENT_ON_MOTD_CHANGE              =     3,       // (event, guild, newMotd)
    GUILD_EVENT_ON_INFO_CHANGE              =     4,       // (event, guild, newInfo)
    GUILD_EVENT_ON_CREATE                   =     5,       // (event, guild, leader, name)  // Not on TC
    GUILD_EVENT_ON_DISBAND                  =     6,       // (event, guild)
    GUILD_EVENT_ON_MONEY_WITHDRAW           =     7,       // (event, guild, player, amount, isRepair) - Can return new money amount
    GUILD_EVENT_ON_MONEY_DEPOSIT            =     8,       // (event, guild, player, amount) - Can return new money amount
    GUILD_EVENT_ON_ITEM_MOVE                =     9,       // (event, guild, player, item, isSrcBank, srcContainer, srcSlotId, isDestBank, destContainer, destSlotId)   // TODO
    GUILD_EVENT_ON_EVENT                    =     10,      // (event, guild, eventType, plrGUIDLow1, plrGUIDLow2, newRank)  // TODO
    GUILD_EVENT_ON_BANK_EVENT               =     11,      // (event, guild, eventType, tabId, playerGUIDLow, itemOrMoney, itemStackCount, destTabId)
    GUILD_EVENT_COUNT
};
@proto cancel = (event, function) @proto cancel = (event, function, shots)
Parameters
uint32 event : [Guild] event Id, refer to GuildEvents above
function function : function to register
uint32 shots = 0 : the number of times the function will be called, 0 means "always call this function"
Returns
function cancel : a function that cancels the binding when called
    {
        return RegisterEventHelper(L, Hooks::REGTYPE_GUILD);
    }
References RegisterEventHelper(), RegisterGuildEvent(), and Hooks::REGTYPE_GUILD.
Referenced by RegisterGuildEvent().
RegisterInstanceEvent()
int LuaGlobalFunctions::RegisterInstanceEvent (lua_State * L)
Registers a [Map] event handler for one instance of a [Map].
enum InstanceEvents
{
    INSTANCE_EVENT_ON_INITIALIZE                    = 1,    // (event, instance_data, map)
    INSTANCE_EVENT_ON_LOAD                          = 2,    // (event, instance_data, map)
    INSTANCE_EVENT_ON_UPDATE                        = 3,    // (event, instance_data, map, diff)
    INSTANCE_EVENT_ON_PLAYER_ENTER                  = 4,    // (event, instance_data, map, player)
    INSTANCE_EVENT_ON_CREATURE_CREATE               = 5,    // (event, instance_data, map, creature)
    INSTANCE_EVENT_ON_GAMEOBJECT_CREATE             = 6,    // (event, instance_data, map, go)
    INSTANCE_EVENT_ON_CHECK_ENCOUNTER_IN_PROGRESS   = 7,    // (event, instance_data, map)
    INSTANCE_EVENT_COUNT
};
Parameters
uint32 instance_id : ID of an instance of a [Map]
uint32 event : [Map] event ID, refer to MapEvents above
function function : function to register
uint32 shots = 0 : the number of times the function will be called, 0 means "always call this function"
    {
        return RegisterEntryHelper(L, Hooks::REGTYPE_INSTANCE);
    }
References RegisterEntryHelper(), RegisterInstanceEvent(), and Hooks::REGTYPE_INSTANCE.
Referenced by RegisterInstanceEvent().
RegisterItemEvent()
int LuaGlobalFunctions::RegisterItemEvent (lua_State * L)
Registers an [Item] event handler.
enum ItemEvents
{
    ITEM_EVENT_ON_DUMMY_EFFECT                      = 1,    // (event, caster, spellid, effindex, item)
    ITEM_EVENT_ON_USE                               = 2,    // (event, player, item, target) - Can return false to stop the spell casting
    ITEM_EVENT_ON_QUEST_ACCEPT                      = 3,    // (event, player, item, quest) - Can return true
    ITEM_EVENT_ON_EXPIRE                            = 4,    // (event, player, itemid) - Can return true
    ITEM_EVENT_ON_REMOVE                            = 5,    // (event, player, item) - Can return true
    ITEM_EVENT_COUNT
};
@proto cancel = (entry, event, function) @proto cancel = (entry, event, function, shots)
Parameters
uint32 entry : [Item] entry Id
uint32 event : [Item] event Id, refer to ItemEvents above
function function : function to register
uint32 shots = 0 : the number of times the function will be called, 0 means "always call this function"
Returns
function cancel : a function that cancels the binding when called
    {
        return RegisterEntryHelper(L, Hooks::REGTYPE_ITEM);
    }
References RegisterEntryHelper(), RegisterItemEvent(), and Hooks::REGTYPE_ITEM.
Referenced by RegisterItemEvent().
RegisterItemGossipEvent()
int LuaGlobalFunctions::RegisterItemGossipEvent (lua_State * L)
Registers an [Item] gossip event handler.
enum GossipEvents
{
    GOSSIP_EVENT_ON_HELLO                           = 1,    // (event, player, object) - Object is the Creature/GameObject/Item. Can return false to do default action. For item gossip can return false to stop spell casting.
    GOSSIP_EVENT_ON_SELECT                          = 2,    // (event, player, object, sender, intid, code, menu_id) - Object is the Creature/GameObject/Item/Player, menu_id is only for player gossip. Can return false to do default action.
    GOSSIP_EVENT_COUNT
};
@proto cancel = (entry, event, function) @proto cancel = (entry, event, function, shots)
Parameters
uint32 entry : [Item] entry Id
uint32 event : [Item] gossip event Id, refer to GossipEvents above
function function : function to register
uint32 shots = 0 : the number of times the function will be called, 0 means "always call this function"
Returns
function cancel : a function that cancels the binding when called
    {
        return RegisterEntryHelper(L, Hooks::REGTYPE_ITEM_GOSSIP);
    }
References RegisterEntryHelper(), RegisterItemGossipEvent(), and Hooks::REGTYPE_ITEM_GOSSIP.
Referenced by RegisterItemGossipEvent().
RegisterMapEvent()
int LuaGlobalFunctions::RegisterMapEvent (lua_State * L)
Registers a [Map] event handler for all instance of a [Map].
enum InstanceEvents
{
    INSTANCE_EVENT_ON_INITIALIZE                    = 1,    // (event, instance_data, map)
    INSTANCE_EVENT_ON_LOAD                          = 2,    // (event, instance_data, map)
    INSTANCE_EVENT_ON_UPDATE                        = 3,    // (event, instance_data, map, diff)
    INSTANCE_EVENT_ON_PLAYER_ENTER                  = 4,    // (event, instance_data, map, player)
    INSTANCE_EVENT_ON_CREATURE_CREATE               = 5,    // (event, instance_data, map, creature)
    INSTANCE_EVENT_ON_GAMEOBJECT_CREATE             = 6,    // (event, instance_data, map, go)
    INSTANCE_EVENT_ON_CHECK_ENCOUNTER_IN_PROGRESS   = 7,    // (event, instance_data, map)
    INSTANCE_EVENT_COUNT
};
Parameters
uint32 map_id : ID of a [Map]
uint32 event : [Map] event ID, refer to MapEvents above
function function : function to register
uint32 shots = 0 : the number of times the function will be called, 0 means "always call this function"
    {
        return RegisterEntryHelper(L, Hooks::REGTYPE_MAP);
    }
References RegisterEntryHelper(), RegisterMapEvent(), and Hooks::REGTYPE_MAP.
Referenced by RegisterMapEvent().
RegisterPacketEvent()
int LuaGlobalFunctions::RegisterPacketEvent (lua_State * L)
Registers a [WorldPacket] event handler.
enum PacketEvents
{
    PACKET_EVENT_ON_PACKET_RECEIVE          =     5,       // (event, packet, player) - Player only if accessible. Can return false, newPacket
    PACKET_EVENT_ON_PACKET_RECEIVE_UNKNOWN  =     6,       // Not Implemented
    PACKET_EVENT_ON_PACKET_SEND             =     7,       // (event, packet, player) - Player only if accessible. Can return false, newPacket
    PACKET_EVENT_COUNT
};
@proto cancel = (entry, event, function) @proto cancel = (entry, event, function, shots)
Parameters
uint32 entry : opcode
uint32 event : packet event Id, refer to PacketEvents above
function function : function to register
uint32 shots = 0 : the number of times the function will be called, 0 means "always call this function"
Returns
function cancel : a function that cancels the binding when called
    {
        return RegisterEntryHelper(L, Hooks::REGTYPE_PACKET);
    }
References RegisterEntryHelper(), RegisterPacketEvent(), and Hooks::REGTYPE_PACKET.
Referenced by RegisterPacketEvent().
RegisterPlayerEvent()
int LuaGlobalFunctions::RegisterPlayerEvent (lua_State * L)
Registers a [Player] event handler.
enum PlayerEvents
{
    PLAYER_EVENT_ON_CHARACTER_CREATE        =     1,        // (event, player)
    PLAYER_EVENT_ON_CHARACTER_DELETE        =     2,        // (event, guid)
    PLAYER_EVENT_ON_LOGIN                   =     3,        // (event, player)
    PLAYER_EVENT_ON_LOGOUT                  =     4,        // (event, player)
    PLAYER_EVENT_ON_SPELL_CAST              =     5,        // (event, player, spell, skipCheck)
    PLAYER_EVENT_ON_KILL_PLAYER             =     6,        // (event, killer, killed)
    PLAYER_EVENT_ON_KILL_CREATURE           =     7,        // (event, killer, killed)
    PLAYER_EVENT_ON_KILLED_BY_CREATURE      =     8,        // (event, killer, killed)
    PLAYER_EVENT_ON_DUEL_REQUEST            =     9,        // (event, target, challenger)
    PLAYER_EVENT_ON_DUEL_START              =     10,       // (event, player1, player2)
    PLAYER_EVENT_ON_DUEL_END                =     11,       // (event, winner, loser, type)
    PLAYER_EVENT_ON_GIVE_XP                 =     12,       // (event, player, amount, victim, source) - Can return new XP amount
    PLAYER_EVENT_ON_LEVEL_CHANGE            =     13,       // (event, player, oldLevel)
    PLAYER_EVENT_ON_MONEY_CHANGE            =     14,       // (event, player, amount) - Can return new money amount
    PLAYER_EVENT_ON_REPUTATION_CHANGE       =     15,       // (event, player, factionId, standing, incremental) - Can return new standing -> if standing == -1, it will prevent default action (rep gain)
    PLAYER_EVENT_ON_TALENTS_CHANGE          =     16,       // (event, player, points)
    PLAYER_EVENT_ON_TALENTS_RESET           =     17,       // (event, player, noCost)
    PLAYER_EVENT_ON_CHAT                    =     18,       // (event, player, msg, Type, lang) - Can return false, newMessage
    PLAYER_EVENT_ON_WHISPER                 =     19,       // (event, player, msg, Type, lang, receiver) - Can return false, newMessage
    PLAYER_EVENT_ON_GROUP_CHAT              =     20,       // (event, player, msg, Type, lang, group) - Can return false, newMessage
    PLAYER_EVENT_ON_GUILD_CHAT              =     21,       // (event, player, msg, Type, lang, guild) - Can return false, newMessage
    PLAYER_EVENT_ON_CHANNEL_CHAT            =     22,       // (event, player, msg, Type, lang, channel) - channel is negative for custom channels. Can return false, newMessage
    PLAYER_EVENT_ON_EMOTE                   =     23,       // (event, player, emote) - Not triggered on any known emote
    PLAYER_EVENT_ON_TEXT_EMOTE              =     24,       // (event, player, textEmote, emoteNum, guid)
    PLAYER_EVENT_ON_SAVE                    =     25,       // (event, player)
    PLAYER_EVENT_ON_BIND_TO_INSTANCE        =     26,       // (event, player, difficulty, mapid, permanent)
    PLAYER_EVENT_ON_UPDATE_ZONE             =     27,       // (event, player, newZone, newArea)
    PLAYER_EVENT_ON_MAP_CHANGE              =     28,       // (event, player)
    // Custom
    PLAYER_EVENT_ON_EQUIP                   =     29,       // (event, player, item, bag, slot)
    PLAYER_EVENT_ON_FIRST_LOGIN             =     30,       // (event, player)
    PLAYER_EVENT_ON_CAN_USE_ITEM            =     31,       // (event, player, itemEntry) - Can return InventoryResult enum value
    PLAYER_EVENT_ON_LOOT_ITEM               =     32,       // (event, player, item, count)
    PLAYER_EVENT_ON_ENTER_COMBAT            =     33,       // (event, player, enemy)
    PLAYER_EVENT_ON_LEAVE_COMBAT            =     34,       // (event, player)
    PLAYER_EVENT_ON_REPOP                   =     35,       // (event, player)
    PLAYER_EVENT_ON_RESURRECT               =     36,       // (event, player)
    PLAYER_EVENT_ON_LOOT_MONEY              =     37,       // (event, player, amount)
    PLAYER_EVENT_ON_QUEST_ABANDON           =     38,       // (event, player, questId)
    PLAYER_EVENT_ON_LEARN_TALENTS           =     39,       // (event, player, talentId, talentRank, spellid)
    // UNUSED                               =     40,       // (event, player)
    // UNUSED                               =     41,       // (event, player)
    PLAYER_EVENT_ON_COMMAND                 =     42,       // (event, player, command, chatHandler) - player is nil if command used from console. Can return false
    PLAYER_EVENT_ON_PET_ADDED_TO_WORLD      =     43,       // (event, player, pet)
    PLAYER_EVENT_ON_LEARN_SPELL             =     44,       // (event, player, spellId)
    PLAYER_EVENT_ON_ACHIEVEMENT_COMPLETE    =     45,       // (event, player, achievement)
    PLAYER_EVENT_ON_FFAPVP_CHANGE           =     46,       // (event, player, hasFfaPvp)
    PLAYER_EVENT_ON_UPDATE_AREA             =     47,       // (event, player, oldArea, newArea)
    PLAYER_EVENT_ON_CAN_INIT_TRADE          =     48,       // (event, player, target) - Can return false to prevent the trade
    PLAYER_EVENT_ON_CAN_SEND_MAIL           =     49,       // (event, player, receiverGuid, mailbox, subject, body, money, cod, item) - Can return false to prevent sending the mail
    PLAYER_EVENT_ON_CAN_JOIN_LFG            =     50,       // (event, player, roles, dungeons, comment) - Can return false to prevent queueing
    PLAYER_EVENT_ON_QUEST_REWARD_ITEM       =     51,       //  (event, player, item, count)
    PLAYER_EVENT_ON_CREATE_ITEM             =     52,       //  (event, player, item, count)
    PLAYER_EVENT_ON_STORE_NEW_ITEM          =     53,       //  (event, player, item, count)
    PLAYER_EVENT_ON_COMPLETE_QUEST          =     54,       // (event, player, quest)
    PLAYER_EVENT_ON_CAN_GROUP_INVITE        =     55,       // (event, player, memberName) - Can return false to prevent inviting
    PLAYER_EVENT_ON_GROUP_ROLL_REWARD_ITEM  =     56,       // (event, player, item, count, voteType, roll)
    PLAYER_EVENT_ON_BG_DESERTION            =     57,       // (event, player, type)
};
@proto cancel = (event, function) @proto cancel = (event, function, shots)
Parameters
uint32 event : [Player] event Id, refer to PlayerEvents above
function function : function to register
uint32 shots = 0 : the number of times the function will be called, 0 means "always call this function"
Returns
function cancel : a function that cancels the binding when called
    {
        return RegisterEventHelper(L, Hooks::REGTYPE_PLAYER);
    }
References RegisterEventHelper(), RegisterPlayerEvent(), and Hooks::REGTYPE_PLAYER.
Referenced by RegisterPlayerEvent().
RegisterPlayerGossipEvent()
int LuaGlobalFunctions::RegisterPlayerGossipEvent (lua_State * L)
Registers a [Player] gossip event handler.
Note that you can not use GOSSIP_EVENT_ON_HELLO with this hook. It does nothing since players dont have an "on hello".
enum GossipEvents
{
    GOSSIP_EVENT_ON_HELLO                           = 1,    // (event, player, object) - Object is the Creature/GameObject/Item. Can return false to do default action. For item gossip can return false to stop spell casting.
    GOSSIP_EVENT_ON_SELECT                          = 2,    // (event, player, object, sender, intid, code, menu_id) - Object is the Creature/GameObject/Item/Player, menu_id is only for player gossip. Can return false to do default action.
    GOSSIP_EVENT_COUNT
};
@proto cancel = (menu_id, event, function) @proto cancel = (menu_id, event, function, shots)
Parameters
uint32 menu_id : [Player] gossip menu Id
uint32 event : [Player] gossip event Id, refer to GossipEvents above
function function : function to register
uint32 shots = 0 : the number of times the function will be called, 0 means "always call this function"
Returns
function cancel : a function that cancels the binding when called
    {
        return RegisterEntryHelper(L, Hooks::REGTYPE_PLAYER_GOSSIP);
    }
References RegisterEntryHelper(), RegisterPlayerGossipEvent(), and Hooks::REGTYPE_PLAYER_GOSSIP.
Referenced by RegisterPlayerGossipEvent().
RegisterServerEvent()
int LuaGlobalFunctions::RegisterServerEvent (lua_State * L)
Registers a server event handler.
enum ServerEvents
{
    // Server
    SERVER_EVENT_ON_NETWORK_START           =     1,       // Not Implemented
    SERVER_EVENT_ON_NETWORK_STOP            =     2,       // Not Implemented
    SERVER_EVENT_ON_SOCKET_OPEN             =     3,       // Not Implemented
    SERVER_EVENT_ON_SOCKET_CLOSE            =     4,       // Not Implemented
    SERVER_EVENT_ON_PACKET_RECEIVE          =     5,       // (event, packet, player) - Player only if accessible. Can return false, newPacket
    SERVER_EVENT_ON_PACKET_RECEIVE_UNKNOWN  =     6,       // Not Implemented
    SERVER_EVENT_ON_PACKET_SEND             =     7,       // (event, packet, player) - Player only if accessible. Can return false, newPacket
    // World
    WORLD_EVENT_ON_OPEN_STATE_CHANGE        =     8,        // (event, open) - Needs core support on Mangos
    WORLD_EVENT_ON_CONFIG_LOAD              =     9,        // (event, reload)
    // UNUSED                               =     10,
    WORLD_EVENT_ON_SHUTDOWN_INIT            =     11,       // (event, code, mask)
    WORLD_EVENT_ON_SHUTDOWN_CANCEL          =     12,       // (event)
    WORLD_EVENT_ON_UPDATE                   =     13,       // (event, diff)
    WORLD_EVENT_ON_STARTUP                  =     14,       // (event)
    WORLD_EVENT_ON_SHUTDOWN                 =     15,       // (event)
    // Eluna
    ELUNA_EVENT_ON_LUA_STATE_CLOSE          =     16,       // (event) - triggers just before shutting down eluna (on shutdown and restart)
    // Map
    MAP_EVENT_ON_CREATE                     =     17,       // (event, map)
    MAP_EVENT_ON_DESTROY                    =     18,       // (event, map)
    MAP_EVENT_ON_GRID_LOAD                  =     19,       // Not Implemented
    MAP_EVENT_ON_GRID_UNLOAD                =     20,       // Not Implemented
    MAP_EVENT_ON_PLAYER_ENTER               =     21,       // (event, map, player)
    MAP_EVENT_ON_PLAYER_LEAVE               =     22,       // (event, map, player)
    MAP_EVENT_ON_UPDATE                     =     23,       // (event, map, diff)
    // Area trigger
    TRIGGER_EVENT_ON_TRIGGER                =     24,       // (event, player, triggerId) - Can return true
    // Weather
    WEATHER_EVENT_ON_CHANGE                 =     25,       // (event, zoneId, state, grade)
    // Auction house
    AUCTION_EVENT_ON_ADD                    =     26,       // (event, auctionId, owner, item, expireTime, buyout, startBid, currentBid, bidderGUIDLow)
    AUCTION_EVENT_ON_REMOVE                 =     27,       // (event, auctionId, owner, item, expireTime, buyout, startBid, currentBid, bidderGUIDLow)
    AUCTION_EVENT_ON_SUCCESSFUL             =     28,       // (event, auctionId, owner, item, expireTime, buyout, startBid, currentBid, bidderGUIDLow)
    AUCTION_EVENT_ON_EXPIRE                 =     29,       // (event, auctionId, owner, item, expireTime, buyout, startBid, currentBid, bidderGUIDLow)
    // AddOns
    ADDON_EVENT_ON_MESSAGE                  =     30,       // (event, sender, type, prefix, msg, target) - target can be nil/whisper_target/guild/group/channel. Can return false
    WORLD_EVENT_ON_DELETE_CREATURE          =     31,       // (event, creature)
    WORLD_EVENT_ON_DELETE_GAMEOBJECT        =     32,       // (event, gameobject)
    // Eluna
    ELUNA_EVENT_ON_LUA_STATE_OPEN           =     33,       // (event) - triggers after all scripts are loaded
    GAME_EVENT_START                        =     34,       // (event, gameeventid)
    GAME_EVENT_STOP                         =     35,       // (event, gameeventid)
};
@proto cancel = (event, function) @proto cancel = (event, function, shots)
Parameters
uint32 event : server event ID, refer to ServerEvents above
function function : function that will be called when the event occurs
uint32 shots = 0 : the number of times the function will be called, 0 means "always call this function"
Returns
function cancel : a function that cancels the binding when called
    {
        return RegisterEventHelper(L, Hooks::REGTYPE_SERVER);
    }
References RegisterEventHelper(), RegisterServerEvent(), and Hooks::REGTYPE_SERVER.
Referenced by RegisterServerEvent().
RegisterUniqueCreatureEvent()
int LuaGlobalFunctions::RegisterUniqueCreatureEvent (lua_State * L)
Registers a [Creature] event handler for a single [Creature].
enum CreatureEvents
{
    CREATURE_EVENT_ON_ENTER_COMBAT                    = 1,  // (event, creature, target) - Can return true to stop normal action
    CREATURE_EVENT_ON_LEAVE_COMBAT                    = 2,  // (event, creature) - Can return true to stop normal action
    CREATURE_EVENT_ON_TARGET_DIED                     = 3,  // (event, creature, victim) - Can return true to stop normal action
    CREATURE_EVENT_ON_DIED                            = 4,  // (event, creature, killer) - Can return true to stop normal action
    CREATURE_EVENT_ON_SPAWN                           = 5,  // (event, creature) - Can return true to stop normal action
    CREATURE_EVENT_ON_REACH_WP                        = 6,  // (event, creature, type, id) - Can return true to stop normal action
    CREATURE_EVENT_ON_AIUPDATE                        = 7,  // (event, creature, diff) - Can return true to stop normal action
    CREATURE_EVENT_ON_RECEIVE_EMOTE                   = 8,  // (event, creature, player, emoteid) - Can return true to stop normal action
    CREATURE_EVENT_ON_DAMAGE_TAKEN                    = 9,  // (event, creature, attacker, damage) - Can return true to stop normal action, can return new damage as second return value.
    CREATURE_EVENT_ON_PRE_COMBAT                      = 10, // (event, creature, target) - Can return true to stop normal action
    // UNUSED
    CREATURE_EVENT_ON_OWNER_ATTACKED                  = 12, // (event, creature, target) - Can return true to stop normal action            // Not on mangos
    CREATURE_EVENT_ON_OWNER_ATTACKED_AT               = 13, // (event, creature, attacker) - Can return true to stop normal action          // Not on mangos
    CREATURE_EVENT_ON_HIT_BY_SPELL                    = 14, // (event, creature, caster, spellid) - Can return true to stop normal action
    CREATURE_EVENT_ON_SPELL_HIT_TARGET                = 15, // (event, creature, target, spellid) - Can return true to stop normal action
    // UNUSED                                         = 16, // (event, creature)
    // UNUSED                                         = 17, // (event, creature)
    // UNUSED                                         = 18, // (event, creature)
    CREATURE_EVENT_ON_JUST_SUMMONED_CREATURE          = 19, // (event, creature, summon) - Can return true to stop normal action
    CREATURE_EVENT_ON_SUMMONED_CREATURE_DESPAWN       = 20, // (event, creature, summon) - Can return true to stop normal action
    CREATURE_EVENT_ON_SUMMONED_CREATURE_DIED          = 21, // (event, creature, summon, killer) - Can return true to stop normal action    // Not on mangos
    CREATURE_EVENT_ON_SUMMONED                        = 22, // (event, creature, summoner) - Can return true to stop normal action
    CREATURE_EVENT_ON_RESET                           = 23, // (event, creature)
    CREATURE_EVENT_ON_REACH_HOME                      = 24, // (event, creature) - Can return true to stop normal action
    // UNUSED                                         = 25, // (event, creature)
    CREATURE_EVENT_ON_CORPSE_REMOVED                  = 26, // (event, creature, respawndelay) - Can return true to stop normal action, can return new respawndelay as second return value
    CREATURE_EVENT_ON_MOVE_IN_LOS                     = 27, // (event, creature, unit) - Can return true to stop normal action. Does not actually check LOS, just uses the sight range
    // UNUSED                                         = 28, // (event, creature)
    // UNUSED                                         = 29, // (event, creature)
    CREATURE_EVENT_ON_DUMMY_EFFECT                    = 30, // (event, caster, spellid, effindex, creature)
    CREATURE_EVENT_ON_QUEST_ACCEPT                    = 31, // (event, player, creature, quest) - Can return true
    // UNUSED                                         = 32, // (event, creature)
    // UNUSED                                         = 33, // (event, creature)
    CREATURE_EVENT_ON_QUEST_REWARD                    = 34, // (event, player, creature, quest, opt) - Can return true
    CREATURE_EVENT_ON_DIALOG_STATUS                   = 35, // (event, player, creature)
    CREATURE_EVENT_ON_ADD                             = 36, // (event, creature)
    CREATURE_EVENT_ON_REMOVE                          = 37, // (event, creature)
    CREATURE_EVENT_COUNT
};
@proto cancel = (guid, instance_id, event, function) @proto cancel = (guid, instance_id, event, function, shots)
Parameters
ObjectGuid guid : the GUID of a single [Creature]
uint32 instance_id : the instance ID of a single [Creature]
uint32 event : refer to CreatureEvents above
function function : function that will be called when the event occurs
uint32 shots = 0 : the number of times the function will be called, 0 means "always call this function"
Returns
function cancel : a function that cancels the binding when called
    {
        return RegisterUniqueHelper(L, Hooks::REGTYPE_CREATURE);
    }
References RegisterUniqueCreatureEvent(), RegisterUniqueHelper(), and Hooks::REGTYPE_CREATURE.
Referenced by RegisterUniqueCreatureEvent().
RegisterUniqueHelper()
static int LuaGlobalFunctions::RegisterUniqueHelper (lua_State * L, int regtype) static
    {
        ObjectGuid guid = Eluna::CHECKVAL<ObjectGuid>(L, 1);
        uint32 instanceId = Eluna::CHECKVAL<uint32>(L, 2);
        uint32 ev = Eluna::CHECKVAL<uint32>(L, 3);
        luaL_checktype(L, 4, LUA_TFUNCTION);
        uint32 shots = Eluna::CHECKVAL<uint32>(L, 5, 0);
        lua_pushvalue(L, 4);
        int functionRef = luaL_ref(L, LUA_REGISTRYINDEX);
        if (functionRef >= 0)
            return Eluna::GetEluna(L)->Register(L, regtype, 0, guid, instanceId, ev, functionRef, shots);
        else
            luaL_argerror(L, 4, "unable to make a ref to function");
        return 0;
    }
References Eluna::GetEluna(), lua_pushvalue(), LUA_REGISTRYINDEX, LUA_TFUNCTION, luaL_argerror(), luaL_checktype(), luaL_ref(), Eluna::Register(), and RegisterUniqueHelper().
Referenced by RegisterUniqueCreatureEvent(), and RegisterUniqueHelper().
ReloadEluna()
int LuaGlobalFunctions::ReloadEluna (lua_State *)
Reloads the Lua engine.
    {
        Eluna::ReloadEluna();
        return 0;
    }
References Eluna::ReloadEluna(), and ReloadEluna().
Referenced by ReloadEluna().
RemoveEventById()
int LuaGlobalFunctions::RemoveEventById (lua_State * L)
Removes a global timed event specified by ID.
Parameters
int eventId : event Id to remove
bool all_Events = false : remove from all events, not just global
    {
        int eventId = Eluna::CHECKVAL<int>(L, 1);
        bool all_Events = Eluna::CHECKVAL<bool>(L, 1, false);
        // not thread safe
        if (all_Events)
            Eluna::GetEluna(L)->eventMgr->SetState(eventId, LUAEVENT_STATE_ABORT);
        else
            Eluna::GetEluna(L)->eventMgr->globalProcessor->SetState(eventId, LUAEVENT_STATE_ABORT);
        return 0;
    }
References Eluna::eventMgr, Eluna::GetEluna(), EventMgr::globalProcessor, LUAEVENT_STATE_ABORT, RemoveEventById(), ElunaEventProcessor::SetState(), and EventMgr::SetState().
Referenced by RemoveEventById().
RemoveEvents()
int LuaGlobalFunctions::RemoveEvents (lua_State * L)
Removes all global timed events.
Parameters
bool all_Events = false : remove all events, not just global
    {
        bool all_Events = Eluna::CHECKVAL<bool>(L, 1, false);
        // not thread safe
        if (all_Events)
            Eluna::GetEluna(L)->eventMgr->SetStates(LUAEVENT_STATE_ABORT);
        else
            Eluna::GetEluna(L)->eventMgr->globalProcessor->SetStates(LUAEVENT_STATE_ABORT);
        return 0;
    }
References Eluna::eventMgr, Eluna::GetEluna(), EventMgr::globalProcessor, LUAEVENT_STATE_ABORT, RemoveEvents(), ElunaEventProcessor::SetStates(), and EventMgr::SetStates().
Referenced by RemoveEvents().
RunCommand()
int LuaGlobalFunctions::RunCommand (lua_State * L)
Runs a command.
Parameters
string command : the command to run
    {
        const char* command = Eluna::CHECKVAL<const char*>(L, 1);
#if defined TRINITY || AZEROTHCORE
        eWorld->QueueCliCommand(new CliCommandHolder(nullptr, command, [](void*, std::string_view view)
        {
            std::string str = { view.begin(), view.end() };
            str.erase(std::find_if(str.rbegin(), str.rend(), [](unsigned char ch) { return !std::isspace(ch); }).base(), str.end()); // Remove trailing spaces and line breaks
            ELUNA_LOG_INFO("{}", str);
        }, nullptr));
#elif defined MANGOS
        eWorld->QueueCliCommand(new CliCommandHolder(0, SEC_CONSOLE, nullptr, command, nullptr, nullptr));
#endif
        return 0;
    }
References ELUNA_LOG_INFO, eWorld, RunCommand(), and SEC_CONSOLE.
Referenced by RunCommand().
SaveAllPlayers()
int LuaGlobalFunctions::SaveAllPlayers (lua_State *)
Saves all [Player]s.
    {
        eObjectAccessor()SaveAllPlayers();
        return 0;
    }
References eObjectAccessor.
SendMail()
int LuaGlobalFunctions::SendMail (lua_State * L)
Sends mail to a [Player].
There can be several item entry-amount pairs at the end of the function. There can be maximum of 12 different items.
enum MailStationery
{
    MAIL_STATIONERY_TEST = 1,
    MAIL_STATIONERY_DEFAULT = 41,
    MAIL_STATIONERY_GM = 61,
    MAIL_STATIONERY_AUCTION = 62,
    MAIL_STATIONERY_VAL = 64, // Valentine
    MAIL_STATIONERY_CHR = 65, // Christmas
    MAIL_STATIONERY_ORP = 67 // Orphan
};
Parameters
string subject : title (subject) of the mail
string text : contents of the mail
uint32 receiverGUIDLow : low GUID of the receiver
uint32 senderGUIDLow = 0 : low GUID of the sender
[MailStationery] stationary = MAIL_STATIONERY_DEFAULT : type of mail that is being sent as, refer to MailStationery above
uint32 delay = 0 : mail send delay in milliseconds
uint32 money = 0 : money to send
uint32 cod = 0 : cod money amount
uint32 entry = 0 : entry of an [Item] to send with mail
uint32 amount = 0 : amount of the [Item] to send with mail
Returns
uint32 itemGUIDlow : low GUID of the item. Up to 12 values returned, returns nil if no further items are sent
    {
        int i = 0;
        std::string subject = Eluna::CHECKVAL<std::string>(L, ++i);
        std::string text = Eluna::CHECKVAL<std::string>(L, ++i);
        uint32 receiverGUIDLow = Eluna::CHECKVAL<uint32>(L, ++i);
        uint32 senderGUIDLow = Eluna::CHECKVAL<uint32>(L, ++i, 0);
        uint32 stationary = Eluna::CHECKVAL<uint32>(L, ++i, MAIL_STATIONERY_DEFAULT);
        uint32 delay = Eluna::CHECKVAL<uint32>(L, ++i, 0);
        uint32 money = Eluna::CHECKVAL<uint32>(L, ++i, 0);
        uint32 cod = Eluna::CHECKVAL<uint32>(L, ++i, 0);
        int argAmount = lua_gettop(L);
        MailSender sender(MAIL_NORMAL, senderGUIDLow, (MailStationery)stationary);
        MailDraft draft(subject, text);
#if defined TRINITY || AZEROTHCORE
        if (cod)
            draft.AddCOD(cod);
        if (money)
            draft.AddMoney(money);
#else
        if (cod)
            draft.SetCOD(cod);
        if (money)
            draft.SetMoney(money);
#endif
#if defined TRINITY || defined AZEROTHCORE
        CharacterDatabaseTransaction trans = CharacterDatabase.BeginTransaction();
#endif
        uint8 addedItems = 0;
        while (addedItems <= MAX_MAIL_ITEMS && i + 2 <= argAmount)
        {
            uint32 entry = Eluna::CHECKVAL<uint32>(L, ++i);
            uint32 amount = Eluna::CHECKVAL<uint32>(L, ++i);
#if defined TRINITY || AZEROTHCORE
            ItemTemplate const* item_proto = eObjectMgr->GetItemTemplate(entry);
#else
            ItemTemplate const* item_proto = ObjectMgr::GetItemPrototype(entry);
#endif
            if (!item_proto)
            {
                luaL_error(L, "Item entry %d does not exist", entry);
                continue;
            }
            if (amount < 1 || (item_proto->MaxCount > 0 && amount > uint32(item_proto->MaxCount)))
            {
                luaL_error(L, "Item entry %d has invalid amount %d", entry, amount);
                continue;
            }
            if (Item* item = Item::CreateItem(entry, amount))
            {
#if defined TRINITY || AZEROTHCORE
                item->SaveToDB(trans);
#else
                item->SaveToDB();
#endif
                draft.AddItem(item);
#if defined TRINITY || AZEROTHCORE
                Eluna::Push(L, item->GetGUID().GetCounter());
#else
                Eluna::Push(L, item->GetGUIDLow());
#endif
                ++addedItems;
            }
        }
        Player* receiverPlayer = eObjectAccessor()FindPlayer(MAKE_NEW_GUID(receiverGUIDLow, 0, HIGHGUID_PLAYER));
#if defined TRINITY || AZEROTHCORE
        draft.SendMailTo(trans, MailReceiver(receiverPlayer, receiverGUIDLow), sender, MAIL_CHECK_MASK_NONE, delay);
        CharacterDatabase.CommitTransaction(trans);
#else
        draft.SendMailTo(MailReceiver(receiverPlayer, MAKE_NEW_GUID(receiverGUIDLow, 0, HIGHGUID_PLAYER)), sender);
#endif
        return addedItems;
    }
References MailDraft::AddCOD(), MailDraft::AddItem(), MailDraft::AddMoney(), CharacterDatabase, Item::CreateItem(), eObjectAccessor, eObjectMgr, lua_gettop(), luaL_error(), MAIL_CHECK_MASK_NONE, MAIL_NORMAL, MAIL_STATIONERY_DEFAULT, MAX_MAIL_ITEMS, ItemTemplate::MaxCount, Eluna::Push(), SendMail(), and MailDraft::SendMailTo().
Referenced by SendMail().
SendWorldMessage()
int LuaGlobalFunctions::SendWorldMessage (lua_State * L)
Sends a message to all [Player]s online.
Parameters
string message : message to send
    {
        const char* message = Eluna::CHECKVAL<const char*>(L, 1);
        eWorld->SendServerMessage(SERVER_MSG_STRING, message);
        return 0;
    }
References eWorld, SendWorldMessage(), and SERVER_MSG_STRING.
Referenced by SendWorldMessage().
StartGameEvent()
int LuaGlobalFunctions::StartGameEvent (lua_State * L)
Starts the event by eventId, if force is set, the event will force start regardless of previous event state.
Parameters
uint16 eventId : the event id to start.
bool force = false : set true to force start the event.
    {
        uint16 eventId = Eluna::CHECKVAL<uint16>(L, 1);
        bool force = Eluna::CHECKVAL<bool>(L, 2, false);
        eGameEventMgr->StartEvent(eventId, force);
        return 0;
    }
References eGameEventMgr, and StartGameEvent().
Referenced by StartGameEvent().
StopGameEvent()
int LuaGlobalFunctions::StopGameEvent (lua_State * L)
Stops the event by eventId, if force is set, the event will force stop regardless of previous event state.
Parameters
uint16 eventId : the event id to stop.
bool force = false : set true to force stop the event.
    {
        uint16 eventId = Eluna::CHECKVAL<uint16>(L, 1);
        bool force = Eluna::CHECKVAL<bool>(L, 2, false);
        eGameEventMgr->StopEvent(eventId, force);
        return 0;
    }
References eGameEventMgr, and StopGameEvent().
Referenced by StopGameEvent().
VendorRemoveAllItems()
int LuaGlobalFunctions::VendorRemoveAllItems (lua_State * L)
Removes all [Item]s from a vendor and updates the database.
Parameters
uint32 entry : [Creature] entry Id
    {
        uint32 entry = Eluna::CHECKVAL<uint32>(L, 1);
        VendorItemData const* items = eObjectMgr->GetNpcVendorItemList(entry);
        if (!items || items->Empty())
            return 0;
        auto const& itemlist = items->m_items;
        for (auto itr = itemlist.rbegin(); itr != itemlist.rend(); ++itr)
#if defined(CATA) || defined(MISTS)
            eObjectMgr->RemoveVendorItem(entry, (*itr)->item, 1);
#else
#ifdef TRINITY
            eObjectMgr->RemoveVendorItem(entry, itr->item);
#else
            eObjectMgr->RemoveVendorItem(entry, (*itr)->item);
#endif
#endif
        return 0;
    }
References VendorItemData::Empty(), eObjectMgr, VendorItemData::m_items, and VendorRemoveAllItems().
Referenced by VendorRemoveAllItems().
VendorRemoveItem()
int LuaGlobalFunctions::VendorRemoveItem (lua_State * L)
Removes an [Item] from a vendor and updates the database.
Parameters
uint32 entry : [Creature] entry Id
uint32 item : [Item] entry Id
    {
        uint32 entry = Eluna::CHECKVAL<uint32>(L, 1);
        uint32 item = Eluna::CHECKVAL<uint32>(L, 2);
        if (!eObjectMgr->GetCreatureTemplate(entry))
            return luaL_argerror(L, 1, "valid CreatureEntry expected");
#if defined(CATA) || defined(MISTS)
        eObjectMgr->RemoveVendorItem(entry, item, 1);
#else
        eObjectMgr->RemoveVendorItem(entry, item);
#endif
        return 0;
    }
References eObjectMgr, luaL_argerror(), and VendorRemoveItem().
Referenced by VendorRemoveItem().
WorldDBExecute()
int LuaGlobalFunctions::WorldDBExecute (lua_State * L)
Executes a SQL query on the world database.
The query may be executed asynchronously (at a later, unpredictable time). If you need to execute the query synchronously, use [Global:WorldDBQuery] instead.
Any results produced are ignored. If you need results from the query, use [Global:WorldDBQuery] or [Global:WorldDBQueryAsync] instead.
WorldDBExecute("DELETE FROM my_table")
Parameters
string sql : query to execute
    {
        const char* query = Eluna::CHECKVAL<const char*>(L, 1);
        WorldDatabase.Execute(query);
        return 0;
    }
References WorldDatabase, and WorldDBExecute().
Referenced by WorldDBExecute().
WorldDBQuery()
int LuaGlobalFunctions::WorldDBQuery (lua_State * L)
Executes a SQL query on the world database and returns an [ElunaQuery].
The query is always executed synchronously (i.e. execution halts until the query has finished and then results are returned). If you need to execute the query asynchronously, use [Global:WorldDBQueryAsync] instead.
local Q = WorldDBQuery("SELECT entry, name FROM creature_template LIMIT 10")
if Q then
    repeat
        local entry, name = Q:GetUInt32(0), Q:GetString(1)
        print(entry, name)
    until not Q:NextRow()
end
Parameters
string sql : query to execute
Returns
[ElunaQuery] results or nil if no rows found or nil if no rows found
    {
        const char* query = Eluna::CHECKVAL<const char*>(L, 1);
#if defined TRINITY || AZEROTHCORE
        ElunaQuery result = WorldDatabase.Query(query);
        if (result)
            Eluna::Push(L, new ElunaQuery(result));
        else
            Eluna::Push(L);
#else
        ElunaQuery* result = WorldDatabase.QueryNamed(query);
        if (result)
            Eluna::Push(L, result);
        else
            Eluna::Push(L);
#endif
        return 1;
    }
References Eluna::Push(), WorldDatabase, and WorldDBQuery().
Referenced by WorldDBQuery().
WorldDBQueryAsync()
int LuaGlobalFunctions::WorldDBQueryAsync (lua_State * L)
Executes an asynchronous SQL query on the world database and passes an [ElunaQuery] to a callback function.
The query is executed asynchronously (i.e. the server keeps running while the query is executed in parallel, and results are passed to a callback function). If you need to execute the query synchronously, use [Global:WorldDBQuery] instead.
WorldDBQueryAsync("SELECT entry, name FROM creature_template LIMIT 10", function(Q)
    if Q then
        repeat
            local entry, name = Q:GetUInt32(0), Q:GetString(1)
            print(entry, name)
        until not Q:NextRow()
    end
end)
Parameters
string sql : query to execute
function callback : function that will be called when the results are available
    {
        return DBQueryAsync(L, WorldDatabase);
    }
References DBQueryAsync(), WorldDatabase, and WorldDBQueryAsync().
Referenced by WorldDBQueryAsync().