AzerothCore Doxygen
instance_violet_hold::instance_violet_hold_InstanceMapScript Struct Reference
Public Member Functions
instance_violet_hold_InstanceMapScript (Map *map)
void Initialize () override
bool IsEncounterInProgress () const override
void OnCreatureCreate (Creature *creature) override
void OnGameObjectCreate (GameObject *go) override
bool SetBossState (uint32 id, EncounterState state) override
void ProcessEvent (WorldObject *, uint32 eventId) override
void DoAction (int32 action) override
void SetData (uint32 type, uint32 data) override
void SetGuidData (uint32 type, ObjectGuid data) override
uint32 GetData (uint32 type) const override
ObjectGuid GetGuidData (uint32 identifier) const override
void StartBossEncounter (uint32 bossId)
void Update (uint32 diff) override
void OnPlayerEnter (Player *plr) override
bool DoNeedCleanup (bool enter)
void InstanceCleanup ()
bool CheckAchievementCriteriaMeet (uint32 criteria_id, Player const *, Unit const *, uint32) override
void SummonDefenseSystem ()
Public Member Functions inherited from InstanceScript
InstanceScript (Map *map)
~InstanceScript () override
virtual void Load (char const *data)
virtual void CreatureLooted (Creature *, LootType)
virtual std::string GetSaveData ()
void SaveToDB ()
void OnCreatureCreate (Creature *creature) override
void OnCreatureRemove (Creature *creature) override
void OnGameObjectCreate (GameObject *go) override
void OnGameObjectRemove (GameObject *go) override
ObjectGuid GetObjectGuid (uint32 type) const
ObjectGuid GetGuidData (uint32 type) const override
Creature * GetCreature (uint32 type)
GameObject * GetGameObject (uint32 type)
virtual void OnPlayerLeave (Player *)
virtual void OnPlayerAreaUpdate (Player *, uint32, uint32)
virtual void OnPlayerInWaterStateUpdate (Player *, bool)
void HandleGameObject (ObjectGuid guid, bool open, GameObject *go=nullptr)
Open or close a GameObject by GUID.
void HandleGameObject (uint32 type, bool open)
Open or close a GameObject registered via LoadObjectData.
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
void DoRespawnGameObject (uint32 type)
void DoRespawnCreature (ObjectGuid guid, bool force=false)
void DoRespawnCreature (uint32 type, bool force=false)
void DoUpdateWorldState (uint32 worldstateId, uint32 worldstateValue)
void DoSendNotifyToInstance (char const *format,...)
void DoUpdateAchievementCriteria (AchievementCriteriaTypes type, uint32 miscValue1=0, uint32 miscValue2=0, Unit *unit=nullptr)
void DoStartTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoStopTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoRemoveAurasDueToSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayer (Player *player, uint32 spell, bool includePets, bool includeControlled)
bool ServerAllowsTwoSideGroups ()
EncounterState GetBossState (uint32 id) const
CreatureBoundary const * GetBossBoundary (uint32 id) const
BossInfo const * GetBossInfo (uint32 id) const
uint32 GetPersistentData (uint32 index) const
void StorePersistentData (uint32 index, uint32 data)
virtual bool CheckRequiredBosses (uint32, Player const *=nullptr) const
bool _SkipCheckRequiredBosses (Player const *player=nullptr) const
void SetCompletedEncountersMask (uint32 newMask, bool save)
uint32 GetCompletedEncounterMask () const
void SendEncounterUnit (uint32 type, Unit *unit=nullptr, uint8 param1=0, uint8 param2=0)
virtual void FillInitialWorldStates (WorldPackets::WorldState::InitWorldStates &)
uint32 GetEncounterCount () const
void MarkAreaTriggerDone (uint32 id)
void ResetAreaTriggerDone (uint32 id)
bool IsAreaTriggerDone (uint32 id) const
void DoForAllMinions (uint32 id, std::function< void(Creature *)> exec)
void StoreGameObjectState (ObjectGuid::LowType spawnId, uint8 state)
uint8 GetStoredGameObjectState (ObjectGuid::LowType spawnId) const
void LoadInstanceSavedGameobjectStateData ()
bool IsBossDone (uint32 bossId) const
bool AllBossesDone () const
bool AllBossesDone (std::initializer_list< uint32 > bossIds) const
TeamId GetTeamIdInInstance () const
void SetTeamIdInInstance (TeamId teamId)
bool IsTwoFactionInstance () const
Public Member Functions inherited from ZoneScript
ZoneScript ()
virtual ~ZoneScript ()
virtual uint32 GetCreatureEntry (ObjectGuid::LowType, CreatureData const *data)
virtual uint32 GetGameObjectEntry (ObjectGuid::LowType, uint32 entry)
virtual void OnUnitDeath (Unit *)
virtual void OnCreatureEvade (Creature *)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
Private Attributes
bool _cleaned { false }
uint8 _encounterStatus { NOT_STARTED }
EventMap _events
uint8 _gateHealth { 100 }
uint8 _waveCount { 0 }
uint8 _portalLocation { 0 }
bool _achievementCompleted { false }
bool _defensesUsed { false }
GuidVector _activationCrystalGuidList
ObjectGuid _guardGuid [4]
ObjectGuid _erekemGuardGuid [2]
GuidSet _trashMobs
Additional Inherited Members
Static Public Member Functions inherited from InstanceScript
static std::string GetBossStateName (uint8 state)
Public Attributes inherited from InstanceScript
Map * instance
TaskScheduler scheduler
Protected Member Functions inherited from InstanceScript
void SetHeaders (std::string const &dataHeaders)
void SetBossNumber (uint32 number)
void SetPersistentDataCount (uint32 number)
void LoadBossBoundaries (BossBoundaryData const &data)
void LoadDoorData (DoorData const *data)
void LoadMinionData (MinionData const *data)
void LoadObjectData (ObjectData const *creatureData, ObjectData const *gameObjectData)
void LoadSummonData (ObjectData const *data)
void SetSummoner (Creature *creature)
void AddObject (Creature *obj, bool add=true)
void RemoveObject (Creature *obj)
void AddObject (GameObject *obj, bool add=true)
void RemoveObject (GameObject *obj)
void AddObject (WorldObject *obj, uint32 type, bool add=true)
void RemoveObject (WorldObject *obj, uint32 type)
void AddDoor (GameObject *door, bool add=true)
void RemoveDoor (GameObject *door)
void AddMinion (Creature *minion, bool add=true)
void RemoveMinion (Creature *minion)
void UpdateDoorState (GameObject *door)
void UpdateMinionState (Creature *minion, EncounterState state)
bool ReadSaveDataHeaders (std::istringstream &data)
void ReadSaveDataBossStates (std::istringstream &data)
void ReadSavePersistentData (std::istringstream &data)
virtual void ReadSaveDataMore (std::istringstream &)
void WriteSaveDataHeaders (std::ostringstream &data)
void WriteSaveDataBossStates (std::ostringstream &data)
void WritePersistentData (std::ostringstream &data)
virtual void WriteSaveDataMore (std::ostringstream &)
Detailed Description
Constructor & Destructor Documentation
instance_violet_hold_InstanceMapScript()
instance_violet_hold::instance_violet_hold_InstanceMapScript::instance_violet_hold_InstanceMapScript (Map * map) inline
                                                         : InstanceScript(map)
        {
            SetHeaders(DataHeader);
            SetBossNumber(MAX_BOSS);
            SetPersistentDataCount(PERSISTENT_DATA_COUNT);
            LoadObjectData(creatureData, goData);
        }
References creatureData, DataHeader, goData, InstanceScript::LoadObjectData(), MAX_BOSS, PERSISTENT_DATA_COUNT, InstanceScript::SetBossNumber(), InstanceScript::SetHeaders(), and InstanceScript::SetPersistentDataCount().
Member Function Documentation
CheckAchievementCriteriaMeet()
bool instance_violet_hold::instance_violet_hold_InstanceMapScript::CheckAchievementCriteriaMeet (uint32 criteria_id, Player const * , Unit const * , uint32) inline override virtual
Reimplemented from InstanceScript.
        {
            switch (criteria_id)
            {
                case CRITERIA_DEFENSELESS:
                    return _gateHealth == 100 && !_defensesUsed;
                case CRITERIA_A_VOID_DANCE:
                case CRITERIA_DEHYDRATION:
                    return _achievementCompleted;
            }
            return false;
        }
References _achievementCompleted, _defensesUsed, _gateHealth, CRITERIA_A_VOID_DANCE, CRITERIA_DEFENSELESS, and CRITERIA_DEHYDRATION.
DoAction()
void instance_violet_hold::instance_violet_hold_InstanceMapScript::DoAction (int32 action) inline override virtual
Reimplemented from InstanceScript.
        {
            switch (action)
            {
                case ACTION_START_INSTANCE:
                    if (_encounterStatus == NOT_STARTED)
                    {
                        _encounterStatus = IN_PROGRESS;
                        if (Creature* sinclari = GetCreature(DATA_SINCLARI))
{
                            sinclari->RemoveNpcFlag(UNIT_NPC_FLAG_GOSSIP);
                            sinclari->AI()->Talk(SAY_SINCLARI_LEAVING);
                        }
                        _events.RescheduleEvent(EVENT_GUARDS_FALL_BACK, 4s);
                        _events.RescheduleEvent(EVENT_CHECK_PLAYERS, 5s);
                    }
                    break;
                case ACTION_PORTAL_DEFEATED:
                    _events.RescheduleEvent(EVENT_SUMMON_PORTAL, 3s);
                    break;
                case ACTION_DECREASE_DOOR_HEALTH:
                    if (_gateHealth > 0)
                        --_gateHealth;
                    if (_gateHealth == 0)
                    {
                        _cleaned = false;
                        InstanceCleanup();
                    }
                    DoUpdateWorldState(WORLD_STATE_VIOLET_HOLD_PRISON_STATE, (uint32)_gateHealth);
                    break;
                case ACTION_RELEASE_BOSS:
                    if (_waveCount == 6)
                        StartBossEncounter(GetPersistentData(PERSISTENT_DATA_FIRST_BOSS));
                    else
                        StartBossEncounter(GetPersistentData(PERSISTENT_DATA_SECOND_BOSS));
                    break;
            }
        }
References _cleaned, _encounterStatus, _events, _gateHealth, _waveCount, ACTION_DECREASE_DOOR_HEALTH, ACTION_PORTAL_DEFEATED, ACTION_RELEASE_BOSS, ACTION_START_INSTANCE, DATA_SINCLARI, InstanceScript::DoUpdateWorldState(), EVENT_CHECK_PLAYERS, EVENT_GUARDS_FALL_BACK, EVENT_SUMMON_PORTAL, InstanceScript::GetCreature(), InstanceScript::GetPersistentData(), IN_PROGRESS, InstanceCleanup(), NOT_STARTED, PERSISTENT_DATA_FIRST_BOSS, PERSISTENT_DATA_SECOND_BOSS, EventMap::RescheduleEvent(), SAY_SINCLARI_LEAVING, StartBossEncounter(), UNIT_NPC_FLAG_GOSSIP, and WORLD_STATE_VIOLET_HOLD_PRISON_STATE.
DoNeedCleanup()
bool instance_violet_hold::instance_violet_hold_InstanceMapScript::DoNeedCleanup (bool enter) inline
        {
            uint32 aliveCount = instance->GetPlayersCountExceptGMs(true);
            bool need = enter ? aliveCount <= 1 : aliveCount == 0;
            if (!need && _cleaned)
                _cleaned = false;
            return need;
        }
References _cleaned, Map::GetPlayersCountExceptGMs(), and InstanceScript::instance.
Referenced by OnPlayerEnter(), and Update().
GetData()
uint32 instance_violet_hold::instance_violet_hold_InstanceMapScript::GetData (uint32 type) const inline override virtual
Reimplemented from ZoneScript.
        {
            switch (type)
            {
                case DATA_ENCOUNTER_STATUS:
                    return (uint32)_encounterStatus;
                case DATA_WAVE_COUNT:
                    return (uint32)_waveCount;
                case DATA_PORTAL_LOCATION:
                    return _portalLocation;
            }
            return 0;
        }
References _encounterStatus, _portalLocation, _waveCount, DATA_ENCOUNTER_STATUS, DATA_PORTAL_LOCATION, and DATA_WAVE_COUNT.
Referenced by Update().
GetGuidData()
ObjectGuid instance_violet_hold::instance_violet_hold_InstanceMapScript::GetGuidData (uint32 identifier) const inline override virtual
Reimplemented from ZoneScript.
        {
            if (identifier == DATA_EREKEM_GUARD_1_GUID)
                return _erekemGuardGuid[0];
            if (identifier == DATA_EREKEM_GUARD_2_GUID)
                return _erekemGuardGuid[1];
            return ObjectGuid::Empty;
        }
References _erekemGuardGuid, DATA_EREKEM_GUARD_1_GUID, DATA_EREKEM_GUARD_2_GUID, and ObjectGuid::Empty.
Initialize()
void instance_violet_hold::instance_violet_hold_InstanceMapScript::Initialize () inline override virtual
Reimplemented from InstanceScript.
        {
            _cleaned = false;
            _encounterStatus = NOT_STARTED;
            _events.Reset();
            _gateHealth = 100;
            _waveCount = 0;
            _portalLocation = 0;
            _defensesUsed = false;
            _activationCrystalGuidList.clear();
        }
References _activationCrystalGuidList, _cleaned, _defensesUsed, _encounterStatus, _events, _gateHealth, _portalLocation, _waveCount, NOT_STARTED, and EventMap::Reset().
InstanceCleanup()
void instance_violet_hold::instance_violet_hold_InstanceMapScript::InstanceCleanup () inline
        {
            if (_cleaned)
                return;
            _cleaned = true;
            for (ObjectGuid const& guid : _activationCrystalGuidList)
                if (GameObject* go = instance->GetGameObject(guid))
                {
                    HandleGameObject(ObjectGuid::Empty, false, go);
                    go->SetGameObjectFlag(GO_FLAG_NOT_SELECTABLE);
                }
            if (Creature* sinclari = GetCreature(DATA_SINCLARI))
            {
                sinclari->SetNpcFlag(UNIT_NPC_FLAG_GOSSIP);
                sinclari->DespawnOrUnsummon(0ms, 3s);
            }
            for (ObjectGuid& guid : _guardGuid)
            {
                if (Creature* guard = instance->GetCreature(guid))
                {
                    guard->SetVisible(GetBossState(DATA_CYANIGOSA) != DONE);
                    guard->SetReactState(REACT_AGGRESSIVE);
                    guard->DespawnOrUnsummon(0ms, 3s);
                }
                guid.Clear();
            }
            if (Creature* portal = GetCreature(DATA_TELEPORTATION_PORTAL))
                portal->DespawnOrUnsummon();
            for (ObjectGuid const& guid : _trashMobs)
                if (Creature* trash = instance->GetCreature(guid))
                    trash->DespawnOrUnsummon();
            _trashMobs.clear();
            if (Creature* doorSeal = GetCreature(DATA_DOOR_SEAL))
                doorSeal->RemoveAllAuras();
            HandleGameObject(DATA_MAIN_DOOR, true);
            if (GetBossState(DATA_CYANIGOSA) != DONE)
            {
                HandleGameObject(DATA_MORAGG_CELL, false);
                HandleGameObject(DATA_EREKEM_CELL, false);
                HandleGameObject(DATA_EREKEM_GUARD_2_CELL, false);
                HandleGameObject(DATA_EREKEM_GUARD_1_CELL, false);
                HandleGameObject(DATA_ICHORON_CELL, false);
                HandleGameObject(DATA_LAVANTHOR_CELL, false);
                HandleGameObject(DATA_XEVOZZ_CELL, false);
                HandleGameObject(DATA_ZURAMAT_CELL, false);
                for (uint32 id = BOSS_MORAGG; id <= BOSS_ZURAMAT; ++id)
                {
                    if (Creature* boss = GetCreature(id))
                    {
                        boss->SetUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
                        boss->SetImmuneToNPC(true);
                        boss->DespawnOrUnsummon(0ms, 3s);
                    }
                }
                if (Creature* guard1 = instance->GetCreature(_erekemGuardGuid[0]))
                {
                    guard1->SetUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
                    guard1->SetImmuneToAll(true);
                    guard1->DespawnOrUnsummon(0ms, 3s);
                }
                _erekemGuardGuid[0].Clear();
                if (Creature* guard2 = instance->GetCreature(_erekemGuardGuid[1]))
                {
                    guard2->SetUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
                    guard2->SetImmuneToAll(true);
                    guard2->DespawnOrUnsummon(0ms, 3s);
                }
                _erekemGuardGuid[1].Clear();
                if (Creature* cyanigosa = GetCreature(DATA_CYANIGOSA))
                    cyanigosa->DespawnOrUnsummon();
            }
            DoUpdateWorldState(WORLD_STATE_VIOLET_HOLD_SHOW, 0);
            _encounterStatus = NOT_STARTED;
            _gateHealth = 100;
            if (GetBossState(DATA_2ND_BOSS) == DONE)
                _waveCount = 12;
            else if (GetBossState(DATA_1ST_BOSS) == DONE)
                _waveCount = 6;
            else
                _waveCount = 0;
            _defensesUsed = false;
            if (GetBossState(DATA_CYANIGOSA) == DONE)
                _encounterStatus = DONE;
            _events.Reset();
            _events.RescheduleEvent(EVENT_CHECK_PLAYERS, 5s);
        }
References _activationCrystalGuidList, _cleaned, _defensesUsed, _encounterStatus, _erekemGuardGuid, _events, _gateHealth, _guardGuid, _trashMobs, _waveCount, BOSS_MORAGG, BOSS_ZURAMAT, ObjectGuid::Clear(), DATA_1ST_BOSS, DATA_2ND_BOSS, DATA_CYANIGOSA, DATA_DOOR_SEAL, DATA_EREKEM_CELL, DATA_EREKEM_GUARD_1_CELL, DATA_EREKEM_GUARD_2_CELL, DATA_ICHORON_CELL, DATA_LAVANTHOR_CELL, DATA_MAIN_DOOR, DATA_MORAGG_CELL, DATA_SINCLARI, DATA_TELEPORTATION_PORTAL, DATA_XEVOZZ_CELL, DATA_ZURAMAT_CELL, DONE, InstanceScript::DoUpdateWorldState(), ObjectGuid::Empty, EVENT_CHECK_PLAYERS, InstanceScript::GetBossState(), Map::GetCreature(), InstanceScript::GetCreature(), Map::GetGameObject(), GO_FLAG_NOT_SELECTABLE, InstanceScript::HandleGameObject(), InstanceScript::instance, NOT_STARTED, REACT_AGGRESSIVE, EventMap::RescheduleEvent(), EventMap::Reset(), UNIT_FLAG_NON_ATTACKABLE, UNIT_NPC_FLAG_GOSSIP, and WORLD_STATE_VIOLET_HOLD_SHOW.
Referenced by DoAction(), OnPlayerEnter(), SetBossState(), and Update().
IsEncounterInProgress()
bool instance_violet_hold::instance_violet_hold_InstanceMapScript::IsEncounterInProgress () const inline override virtual
Reimplemented from InstanceScript.
        {
            return _encounterStatus == IN_PROGRESS;
        }
References _encounterStatus, and IN_PROGRESS.
OnCreatureCreate()
void instance_violet_hold::instance_violet_hold_InstanceMapScript::OnCreatureCreate (Creature * creature) inline override virtual
Reimplemented from ZoneScript.
        {
            InstanceScript::OnCreatureCreate(creature);
            switch (creature->GetEntry())
            {
                case NPC_VIOLET_HOLD_GUARD:
                    for (ObjectGuid& guid : _guardGuid)
                        if (!guid)
{
                            guid = creature->GetGUID();
                            break;
                        }
                    break;
                case NPC_DEFENSE_DUMMY_TARGET:
                    creature->ApplySpellImmune(0, IMMUNITY_ID, SPELL_ARCANE_LIGHTNING, true);
                    break;
                case NPC_EREKEM_GUARD:
                    if (!_erekemGuardGuid[0])
                        _erekemGuardGuid[0] = creature->GetGUID();
                    else
                        _erekemGuardGuid[1] = creature->GetGUID();
                    break;
            }
        }
References _erekemGuardGuid, _guardGuid, Unit::ApplySpellImmune(), Object::GetEntry(), Object::GetGUID(), IMMUNITY_ID, NPC_DEFENSE_DUMMY_TARGET, NPC_EREKEM_GUARD, NPC_VIOLET_HOLD_GUARD, InstanceScript::OnCreatureCreate(), and SPELL_ARCANE_LIGHTNING.
OnGameObjectCreate()
void instance_violet_hold::instance_violet_hold_InstanceMapScript::OnGameObjectCreate (GameObject * go) inline override virtual
Reimplemented from ZoneScript.
        {
            InstanceScript::OnGameObjectCreate(go);
            if (go->GetEntry() == GO_ACTIVATION_CRYSTAL)
            {
                HandleGameObject(ObjectGuid::Empty, false, go);
                go->SetGameObjectFlag(GO_FLAG_NOT_SELECTABLE);
                _activationCrystalGuidList.push_back(go->GetGUID());
            }
        }
References _activationCrystalGuidList, ObjectGuid::Empty, Object::GetEntry(), Object::GetGUID(), GO_ACTIVATION_CRYSTAL, GO_FLAG_NOT_SELECTABLE, InstanceScript::HandleGameObject(), InstanceScript::OnGameObjectCreate(), and GameObject::SetGameObjectFlag().
OnPlayerEnter()
void instance_violet_hold::instance_violet_hold_InstanceMapScript::OnPlayerEnter (Player * plr) inline override virtual
Reimplemented from InstanceScript.
        {
            if (_encounterStatus == IN_PROGRESS)
            {
                if (DoNeedCleanup(plr->IsAlive()))
                    InstanceCleanup();
                plr->SendUpdateWorldState(WORLD_STATE_VIOLET_HOLD_SHOW, 1);
                plr->SendUpdateWorldState(WORLD_STATE_VIOLET_HOLD_PRISON_STATE, (uint32)_gateHealth);
                plr->SendUpdateWorldState(WORLD_STATE_VIOLET_HOLD_WAVE_COUNT, (uint32)_waveCount);
            }
            else
                plr->SendUpdateWorldState(WORLD_STATE_VIOLET_HOLD_SHOW, 0);
        }
References _encounterStatus, _gateHealth, _waveCount, DoNeedCleanup(), IN_PROGRESS, InstanceCleanup(), Unit::IsAlive(), Player::SendUpdateWorldState(), WORLD_STATE_VIOLET_HOLD_PRISON_STATE, WORLD_STATE_VIOLET_HOLD_SHOW, and WORLD_STATE_VIOLET_HOLD_WAVE_COUNT.
ProcessEvent()
void instance_violet_hold::instance_violet_hold_InstanceMapScript::ProcessEvent (WorldObject * , uint32 eventId) inline override virtual
Reimplemented from ZoneScript.
        {
            if (eventId == EVENT_ACTIVATE_CRYSTAL)
            {
                _defensesUsed = true;
                SummonDefenseSystem();
            }
        }
References _defensesUsed, EVENT_ACTIVATE_CRYSTAL, and SummonDefenseSystem().
SetBossState()
bool instance_violet_hold::instance_violet_hold_InstanceMapScript::SetBossState (uint32 id, EncounterState state) inline override virtual
Reimplemented from InstanceScript.
        {
            if (!InstanceScript::SetBossState(id, state))
                return false;
            switch (id)
            {
                case BOSS_MORAGG:
                case BOSS_EREKEM:
                case BOSS_ICHORON:
                case BOSS_LAVANTHOR:
                case BOSS_XEVOZZ:
                case BOSS_ZURAMAT:
                    if (state == DONE)
                    {
                        if (_waveCount == 6)
                            SetBossState(DATA_1ST_BOSS, DONE);
                        else if (_waveCount == 12)
                            SetBossState(DATA_2ND_BOSS, DONE);
                        _events.RescheduleEvent(EVENT_SUMMON_PORTAL, 35s);
                    }
                    else if (state == FAIL || state == NOT_STARTED)
                    {
                        _cleaned = false;
                        InstanceCleanup();
                    }
                    break;
                case DATA_CYANIGOSA:
                    if (state == DONE)
                    {
                        _events.Reset();
                        _encounterStatus = DONE;
                        HandleGameObject(DATA_MAIN_DOOR, true);
                        DoUpdateWorldState(WORLD_STATE_VIOLET_HOLD_SHOW, 0);
                        if (Creature* sinclari = GetCreature(DATA_SINCLARI))
{
                            sinclari->AI()->Talk(SAY_SINCLARI_COMPLETE);
                            sinclari->DespawnOrUnsummon(0ms, 3s);
                        }
                    }
                    else if (state == FAIL || state == NOT_STARTED)
                    {
                        _cleaned = false;
                        InstanceCleanup();
                    }
                    break;
                default:
                    break;
            }
            return true;
        }
References _cleaned, _encounterStatus, _events, _waveCount, BOSS_EREKEM, BOSS_ICHORON, BOSS_LAVANTHOR, BOSS_MORAGG, BOSS_XEVOZZ, BOSS_ZURAMAT, DATA_1ST_BOSS, DATA_2ND_BOSS, DATA_CYANIGOSA, DATA_MAIN_DOOR, DATA_SINCLARI, DONE, InstanceScript::DoUpdateWorldState(), EVENT_SUMMON_PORTAL, FAIL, InstanceScript::GetCreature(), InstanceScript::HandleGameObject(), InstanceCleanup(), NOT_STARTED, EventMap::RescheduleEvent(), EventMap::Reset(), SAY_SINCLARI_COMPLETE, InstanceScript::SetBossState(), SetBossState(), and WORLD_STATE_VIOLET_HOLD_SHOW.
Referenced by SetBossState().
SetData()
void instance_violet_hold::instance_violet_hold_InstanceMapScript::SetData (uint32 type, uint32 data) inline override virtual
Reimplemented from ZoneScript.
        {
            switch (type)
            {
                case DATA_PORTAL_LOCATION:
                    _portalLocation = data;
                    break;
                case DATA_ACHIEV:
                    _achievementCompleted = !!data;
                    break;
            }
        }
References _achievementCompleted, _portalLocation, DATA_ACHIEV, and DATA_PORTAL_LOCATION.
Referenced by Update().
SetGuidData()
void instance_violet_hold::instance_violet_hold_InstanceMapScript::SetGuidData (uint32 type, ObjectGuid data) inline override virtual
Reimplemented from ZoneScript.
        {
            if (type == DATA_ADD_TRASH_MOB)
                _trashMobs.insert(data);
            else if (type == DATA_DELETE_TRASH_MOB && !_cleaned)
                _trashMobs.erase(data);
        }
References _cleaned, _trashMobs, DATA_ADD_TRASH_MOB, and DATA_DELETE_TRASH_MOB.
StartBossEncounter()
void instance_violet_hold::instance_violet_hold_InstanceMapScript::StartBossEncounter (uint32 bossId) inline
        {
            switch (bossId)
            {
                case BOSS_MORAGG:
                    HandleGameObject(DATA_MORAGG_CELL, true);
                    break;
                case BOSS_EREKEM:
                    HandleGameObject(DATA_EREKEM_CELL, true);
                    HandleGameObject(DATA_EREKEM_GUARD_2_CELL, true);
                    HandleGameObject(DATA_EREKEM_GUARD_1_CELL, true);
                    if (Creature* guard1 = instance->GetCreature(_erekemGuardGuid[0]))
                    {
                        guard1->RemoveUnitMovementFlag(MOVEMENTFLAG_WALKING);
                        guard1->RemoveUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
                        guard1->SetImmuneToAll(false);
                        guard1->GetMotionMaster()->MovePoint(0, BossStartMove21);
                    }
                    if (Creature* guard2 = instance->GetCreature(_erekemGuardGuid[1]))
                    {
                        guard2->RemoveUnitMovementFlag(MOVEMENTFLAG_WALKING);
                        guard2->RemoveUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
                        guard2->SetImmuneToAll(false);
                        guard2->GetMotionMaster()->MovePoint(0, BossStartMove22);
                    }
                    break;
                case BOSS_ICHORON:
                    HandleGameObject(DATA_ICHORON_CELL, true);
                    break;
                case BOSS_LAVANTHOR:
                    HandleGameObject(DATA_LAVANTHOR_CELL, true);
                    break;
                case BOSS_XEVOZZ:
                    HandleGameObject(DATA_XEVOZZ_CELL, true);
                    break;
                case BOSS_ZURAMAT:
                    HandleGameObject(DATA_ZURAMAT_CELL, true);
                    break;
            }
            static Position const BossStartPositions[] =
            {
                BossStartMove1,  // BOSS_MORAGG
                BossStartMove2,  // BOSS_EREKEM
                BossStartMove3,  // BOSS_ICHORON
                BossStartMove4,  // BOSS_LAVANTHOR
                BossStartMove5,  // BOSS_XEVOZZ
                BossStartMove6,  // BOSS_ZURAMAT
            };
            Creature* boss = GetCreature(bossId);
            if (boss)
            {
                boss->GetMotionMaster()->MovePoint(0, BossStartPositions[bossId - BOSS_MORAGG]);
                boss->RemoveUnitMovementFlag(MOVEMENTFLAG_WALKING);
                boss->RemoveUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
                boss->SetImmuneToNPC(false);
                boss->SetReactState(REACT_AGGRESSIVE);
                if ((_waveCount == 6 && GetBossState(DATA_1ST_BOSS) == DONE) || (_waveCount == 12 && GetBossState(DATA_2ND_BOSS) == DONE))
                    boss->SetLootMode(0);
            }
        }
References _erekemGuardGuid, _waveCount, BOSS_EREKEM, BOSS_ICHORON, BOSS_LAVANTHOR, BOSS_MORAGG, BOSS_XEVOZZ, BOSS_ZURAMAT, BossStartMove1, BossStartMove2, BossStartMove21, BossStartMove22, BossStartMove3, BossStartMove4, BossStartMove5, BossStartMove6, DATA_1ST_BOSS, DATA_2ND_BOSS, DATA_EREKEM_CELL, DATA_EREKEM_GUARD_1_CELL, DATA_EREKEM_GUARD_2_CELL, DATA_ICHORON_CELL, DATA_LAVANTHOR_CELL, DATA_MORAGG_CELL, DATA_XEVOZZ_CELL, DATA_ZURAMAT_CELL, DONE, InstanceScript::GetBossState(), Map::GetCreature(), InstanceScript::GetCreature(), Unit::GetMotionMaster(), InstanceScript::HandleGameObject(), InstanceScript::instance, MOVEMENTFLAG_WALKING, MotionMaster::MovePoint(), REACT_AGGRESSIVE, Unit::RemoveUnitFlag(), Unit::RemoveUnitMovementFlag(), Unit::SetImmuneToNPC(), Creature::SetLootMode(), Creature::SetReactState(), and UNIT_FLAG_NON_ATTACKABLE.
Referenced by DoAction().
SummonDefenseSystem()
void instance_violet_hold::instance_violet_hold_InstanceMapScript::SummonDefenseSystem () inline
        {
            Position const pos = {1919.09546f, 812.29724f, 86.2905f, M_PI};
            instance->SummonCreature(NPC_DEFENSE_SYSTEM, pos, 0, 6499);
        }
References InstanceScript::instance, NPC_DEFENSE_SYSTEM, and Map::SummonCreature().
Referenced by ProcessEvent(), and Update().
Update()
void instance_violet_hold::instance_violet_hold_InstanceMapScript::Update (uint32 diff) inline override virtual
Reimplemented from InstanceScript.
        {
            _events.Update(diff);
            switch (_events.ExecuteEvent())
            {
                case EVENT_CHECK_PLAYERS:
                    if (DoNeedCleanup(false))
                        InstanceCleanup();
                    _events.Repeat(5s);
                    break;
                case EVENT_GUARDS_FALL_BACK:
                    for (ObjectGuid const& guid : _guardGuid)
                        if (Creature* guard = instance->GetCreature(guid))
{
                            guard->SetReactState(REACT_PASSIVE);
                            guard->CombatStop();
                            guard->RemoveUnitMovementFlag(MOVEMENTFLAG_WALKING);
                            guard->GetMotionMaster()->MovePoint(0, guardMovePosition);
                        }
                    _events.RescheduleEvent(EVENT_GUARDS_DISAPPEAR, 5s);
                    break;
                case EVENT_GUARDS_DISAPPEAR:
                    for (ObjectGuid const& guid : _guardGuid)
                        if (Creature* guard = instance->GetCreature(guid))
                            guard->SetVisible(false);
                    _events.RescheduleEvent(EVENT_SINCLARI_FALL_BACK, 2s);
                    break;
                case EVENT_SINCLARI_FALL_BACK:
                    if (Creature* sinclari = GetCreature(DATA_SINCLARI))
                    {
                        sinclari->RemoveUnitMovementFlag(MOVEMENTFLAG_WALKING);
                        sinclari->GetMotionMaster()->MovePoint(0, sinclariOutsidePosition);
                    }
                    SummonDefenseSystem();
                    _events.RescheduleEvent(EVENT_START_ENCOUNTER, 4s);
                    break;
                case EVENT_START_ENCOUNTER:
                    if (Creature* sinclari = GetCreature(DATA_SINCLARI))
                    {
                        sinclari->AI()->Talk(SAY_SINCLARI_DOOR_LOCK);
                        sinclari->SetNpcFlag(UNIT_NPC_FLAG_GOSSIP);
                    }
                    if (Creature* doorSeal = GetCreature(DATA_DOOR_SEAL))
                        doorSeal->RemoveAllAuras();
                    _gateHealth = 100;
                    HandleGameObject(DATA_MAIN_DOOR, false);
                    DoUpdateWorldState(WORLD_STATE_VIOLET_HOLD_SHOW, 1);
                    DoUpdateWorldState(WORLD_STATE_VIOLET_HOLD_PRISON_STATE, (uint32)_gateHealth);
                    DoUpdateWorldState(WORLD_STATE_VIOLET_HOLD_WAVE_COUNT, (uint32)_waveCount);
                    for (ObjectGuid const& guid : _activationCrystalGuidList)
                        if (GameObject* go = instance->GetGameObject(guid))
{
                            HandleGameObject(ObjectGuid::Empty, false, go);
                            go->RemoveGameObjectFlag(GO_FLAG_NOT_SELECTABLE);
                        }
                    _events.RescheduleEvent(EVENT_SUMMON_PORTAL, 4s);
                    break;
                case EVENT_SUMMON_PORTAL:
                    ++_waveCount;
                    DoUpdateWorldState(WORLD_STATE_VIOLET_HOLD_WAVE_COUNT, (uint32)_waveCount);
                    SetData(DATA_PORTAL_LOCATION, (GetData(DATA_PORTAL_LOCATION) + urand(1, 5)) % 6);
                    if (Creature* sinclari = GetCreature(DATA_SINCLARI))
                    {
                        if (_waveCount % 6 != 0)
                            sinclari->SummonCreature(NPC_TELEPORTATION_PORTAL, PortalLocations[GetData(DATA_PORTAL_LOCATION)], TEMPSUMMON_CORPSE_DESPAWN);
                        else if (_waveCount == 6 || _waveCount == 12)
{
                            if (!GetPersistentData(PERSISTENT_DATA_FIRST_BOSS) || !GetPersistentData(PERSISTENT_DATA_SECOND_BOSS))
{
                                uint32 firstBoss = urand(BOSS_MORAGG, BOSS_ZURAMAT);
                                uint32 secondBoss;
                                do { secondBoss = urand(BOSS_MORAGG, BOSS_ZURAMAT); }
                                while (firstBoss == secondBoss);
                                StorePersistentData(PERSISTENT_DATA_FIRST_BOSS, firstBoss);
                                StorePersistentData(PERSISTENT_DATA_SECOND_BOSS, secondBoss);
                            }
                            sinclari->SummonCreature(NPC_TELEPORTATION_PORTAL, MiddleRoomPortalSaboLocation, TEMPSUMMON_CORPSE_DESPAWN);
                        }
                        else
{
                            if (Creature* cyanigosa = sinclari->SummonCreature(NPC_CYANIGOSA, CyanigosasSpawnLocation, TEMPSUMMON_DEAD_DESPAWN))
{
                                cyanigosa->CastSpell(cyanigosa, SPELL_CYANIGOSA_BLUE_AURA, false);
                                cyanigosa->AI()->Talk(CYANIGOSA_SAY_SPAWN);
                                cyanigosa->GetMotionMaster()->MoveJump(MiddleRoomLocation.GetPositionX(), MiddleRoomLocation.GetPositionY(), MiddleRoomLocation.GetPositionZ(), 10.0f, 20.0f);
                            }
                            _events.RescheduleEvent(EVENT_CYANIGOSA_TRANSFORM, 10s);
                        }
                    }
                    break;
                case EVENT_CYANIGOSA_TRANSFORM:
                    if (Creature* cyanigosa = GetCreature(DATA_CYANIGOSA))
                    {
                        cyanigosa->RemoveAurasDueToSpell(SPELL_CYANIGOSA_BLUE_AURA);
                        cyanigosa->CastSpell(cyanigosa, SPELL_CYANIGOSA_TRANSFORM, 0);
                        _events.RescheduleEvent(EVENT_CYANIGOSA_ATTACK, 2500ms);
                    }
                    break;
                case EVENT_CYANIGOSA_ATTACK:
                    if (Creature* cyanigosa = GetCreature(DATA_CYANIGOSA))
                    {
                        cyanigosa->RemoveUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
                        cyanigosa->SetImmuneToNPC(false);
                    }
                    break;
            }
        }
References _activationCrystalGuidList, _events, _gateHealth, _guardGuid, _waveCount, BOSS_MORAGG, BOSS_ZURAMAT, CYANIGOSA_SAY_SPAWN, CyanigosasSpawnLocation, DATA_CYANIGOSA, DATA_DOOR_SEAL, DATA_MAIN_DOOR, DATA_PORTAL_LOCATION, DATA_SINCLARI, DoNeedCleanup(), InstanceScript::DoUpdateWorldState(), ObjectGuid::Empty, EVENT_CHECK_PLAYERS, EVENT_CYANIGOSA_ATTACK, EVENT_CYANIGOSA_TRANSFORM, EVENT_GUARDS_DISAPPEAR, EVENT_GUARDS_FALL_BACK, EVENT_SINCLARI_FALL_BACK, EVENT_START_ENCOUNTER, EVENT_SUMMON_PORTAL, EventMap::ExecuteEvent(), Map::GetCreature(), InstanceScript::GetCreature(), GetData(), Map::GetGameObject(), InstanceScript::GetPersistentData(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), GO_FLAG_NOT_SELECTABLE, guardMovePosition, InstanceScript::HandleGameObject(), InstanceScript::instance, InstanceCleanup(), MiddleRoomLocation, MiddleRoomPortalSaboLocation, MOVEMENTFLAG_WALKING, NPC_CYANIGOSA, NPC_TELEPORTATION_PORTAL, PERSISTENT_DATA_FIRST_BOSS, PERSISTENT_DATA_SECOND_BOSS, PortalLocations, REACT_PASSIVE, EventMap::Repeat(), EventMap::RescheduleEvent(), SAY_SINCLARI_DOOR_LOCK, SetData(), sinclariOutsidePosition, SPELL_CYANIGOSA_BLUE_AURA, SPELL_CYANIGOSA_TRANSFORM, InstanceScript::StorePersistentData(), WorldObject::SummonCreature(), SummonDefenseSystem(), TEMPSUMMON_CORPSE_DESPAWN, TEMPSUMMON_DEAD_DESPAWN, UNIT_FLAG_NON_ATTACKABLE, UNIT_NPC_FLAG_GOSSIP, EventMap::Update(), urand(), WORLD_STATE_VIOLET_HOLD_PRISON_STATE, WORLD_STATE_VIOLET_HOLD_SHOW, and WORLD_STATE_VIOLET_HOLD_WAVE_COUNT.
Member Data Documentation
_achievementCompleted
bool instance_violet_hold::instance_violet_hold_InstanceMapScript::_achievementCompleted { false } private
{ false };
Referenced by CheckAchievementCriteriaMeet(), and SetData().
_activationCrystalGuidList
GuidVector instance_violet_hold::instance_violet_hold_InstanceMapScript::_activationCrystalGuidList private
Referenced by Initialize(), InstanceCleanup(), OnGameObjectCreate(), and Update().
_cleaned
bool instance_violet_hold::instance_violet_hold_InstanceMapScript::_cleaned { false } private
{ false };
Referenced by DoAction(), DoNeedCleanup(), Initialize(), InstanceCleanup(), SetBossState(), and SetGuidData().
_defensesUsed
bool instance_violet_hold::instance_violet_hold_InstanceMapScript::_defensesUsed { false } private
{ false };
Referenced by CheckAchievementCriteriaMeet(), Initialize(), InstanceCleanup(), and ProcessEvent().
_encounterStatus
uint8 instance_violet_hold::instance_violet_hold_InstanceMapScript::_encounterStatus { NOT_STARTED } private
{ NOT_STARTED };
Referenced by DoAction(), GetData(), Initialize(), InstanceCleanup(), IsEncounterInProgress(), OnPlayerEnter(), and SetBossState().
_erekemGuardGuid
ObjectGuid instance_violet_hold::instance_violet_hold_InstanceMapScript::_erekemGuardGuid[2] private
Referenced by GetGuidData(), InstanceCleanup(), OnCreatureCreate(), and StartBossEncounter().
_events
EventMap instance_violet_hold::instance_violet_hold_InstanceMapScript::_events private
Referenced by DoAction(), Initialize(), InstanceCleanup(), SetBossState(), and Update().
_gateHealth
uint8 instance_violet_hold::instance_violet_hold_InstanceMapScript::_gateHealth { 100 } private
{ 100 };
Referenced by CheckAchievementCriteriaMeet(), DoAction(), Initialize(), InstanceCleanup(), OnPlayerEnter(), and Update().
_guardGuid
ObjectGuid instance_violet_hold::instance_violet_hold_InstanceMapScript::_guardGuid[4] private
Referenced by InstanceCleanup(), OnCreatureCreate(), and Update().
_portalLocation
uint8 instance_violet_hold::instance_violet_hold_InstanceMapScript::_portalLocation { 0 } private
{ 0 };
Referenced by GetData(), Initialize(), and SetData().
_trashMobs
GuidSet instance_violet_hold::instance_violet_hold_InstanceMapScript::_trashMobs private
Referenced by InstanceCleanup(), and SetGuidData().
_waveCount
uint8 instance_violet_hold::instance_violet_hold_InstanceMapScript::_waveCount { 0 } private
{ 0 };
Referenced by DoAction(), GetData(), Initialize(), InstanceCleanup(), OnPlayerEnter(), SetBossState(), StartBossEncounter(), and Update().
The documentation for this struct was generated from the following file:
azerothcore-wotlk/src/server/scripts/Northrend/VioletHold/instance_violet_hold.cpp