AzerothCore Doxygen
ElunaEventProcessor Class Reference
#include "ElunaEventMgr.h"
Public Types
typedef std::multimap< uint64, LuaEvent * > EventList
typedef std::unordered_map< int, LuaEvent * > EventMap
Public Member Functions
ElunaEventProcessor (Eluna **_E, WorldObject *_obj)
~ElunaEventProcessor ()
void Update (uint32 diff)
void SetStates (LuaEventState state)
void SetState (int eventId, LuaEventState state)
void AddEvent (int funcRef, uint32 min, uint32 max, uint32 repeats)
Public Attributes
EventMap eventMap
Private Member Functions
void RemoveEvents_internal ()
void AddEvent (LuaEvent *luaEvent)
void RemoveEvent (LuaEvent *luaEvent)
Private Attributes
EventList eventList
uint64 m_time
WorldObject * obj
Eluna ** E
Friends
class EventMgr
Detailed Description
Member Typedef Documentation
EventList
typedef std::multimap<uint64, LuaEvent*> ElunaEventProcessor::EventList
EventMap
typedef std::unordered_map<int, LuaEvent*> ElunaEventProcessor::EventMap
Constructor & Destructor Documentation
ElunaEventProcessor()
ElunaEventProcessor::ElunaEventProcessor (Eluna ** _E, WorldObject * _obj)
                                                                      : m_time(0), obj(_obj), E(_E)
{
    // can be called from multiple threads
    if (obj)
    {
        EventMgr::Guard guard((*E)->eventMgr->GetLock());
        (*E)->eventMgr->processors.insert(this);
    }
}
References obj.
~ElunaEventProcessor()
ElunaEventProcessor::~ElunaEventProcessor ()
{
    // can be called from multiple threads
    {
        LOCK_ELUNA;
        RemoveEvents_internal();
    }
    if (obj && Eluna::IsInitialized())
    {
        EventMgr::Guard guard((*E)->eventMgr->GetLock());
        (*E)->eventMgr->processors.erase(this);
    }
}
References Eluna::IsInitialized(), LOCK_ELUNA, obj, and RemoveEvents_internal().
Member Function Documentation
AddEvent() [1/2]
void ElunaEventProcessor::AddEvent (int funcRef, uint32 min, uint32 max, uint32 repeats)
{
    AddEvent(new LuaEvent(funcRef, min, max, repeats));
}
References AddEvent().
Referenced by AddEvent(), LuaGlobalFunctions::CreateLuaEvent(), LuaWorldObject::RegisterEvent(), and Update().
AddEvent() [2/2]
void ElunaEventProcessor::AddEvent (LuaEvent * luaEvent) private
{
    luaEvent->GenerateDelay();
    eventList.insert(std::pair<uint64, LuaEvent*>(m_time + luaEvent->delay, luaEvent));
    eventMap[luaEvent->funcRef] = luaEvent;
}
References LuaEvent::delay, eventList, eventMap, LuaEvent::funcRef, LuaEvent::GenerateDelay(), and m_time.
RemoveEvent()
void ElunaEventProcessor::RemoveEvent (LuaEvent * luaEvent) private
{
    // Unreference if should and if Eluna was not yet uninitialized and if the lua state still exists
    if (luaEvent->state != LUAEVENT_STATE_ERASE && Eluna::IsInitialized() && (*E)->HasLuaState())
    {
        // Free lua function ref
        luaL_unref((*E)->L, LUA_REGISTRYINDEX, luaEvent->funcRef);
    }
    delete luaEvent;
}
References LuaEvent::funcRef, Eluna::IsInitialized(), LUA_REGISTRYINDEX, LUAEVENT_STATE_ERASE, luaL_unref(), and LuaEvent::state.
Referenced by RemoveEvents_internal(), and Update().
RemoveEvents_internal()
void ElunaEventProcessor::RemoveEvents_internal () private
{
    //if (!final)
    //{
    //    for (EventList::iterator it = eventList.begin(); it != eventList.end(); ++it)
    //        it->second->to_Abort = true;
    //    return;
    //}
    for (EventList::iterator it = eventList.begin(); it != eventList.end(); ++it)
        RemoveEvent(it->second);
    eventList.clear();
    eventMap.clear();
}
References eventList, eventMap, and RemoveEvent().
Referenced by ~ElunaEventProcessor(), and EventMgr::~EventMgr().
SetState()
void ElunaEventProcessor::SetState (int eventId, LuaEventState state)
{
    if (eventMap.find(eventId) != eventMap.end())
        eventMap[eventId]->SetState(state);
    if (state == LUAEVENT_STATE_ERASE)
        eventMap.erase(eventId);
}
References eventMap, and LUAEVENT_STATE_ERASE.
Referenced by LuaGlobalFunctions::RemoveEventById(), LuaWorldObject::RemoveEventById(), and EventMgr::SetState().
SetStates()
void ElunaEventProcessor::SetStates (LuaEventState state)
{
    for (EventList::iterator it = eventList.begin(); it != eventList.end(); ++it)
        it->second->SetState(state);
    if (state == LUAEVENT_STATE_ERASE)
        eventMap.clear();
}
References eventList, eventMap, and LUAEVENT_STATE_ERASE.
Referenced by LuaWorldObject::RemoveEvents(), LuaGlobalFunctions::RemoveEvents(), and EventMgr::SetStates().
Update()
void ElunaEventProcessor::Update (uint32 diff)
{
    m_time += diff;
    for (EventList::iterator it = eventList.begin(); it != eventList.end() && it->first <= m_time; it = eventList.begin())
    {
        LuaEvent* luaEvent = it->second;
        eventList.erase(it);
        if (luaEvent->state != LUAEVENT_STATE_ERASE)
            eventMap.erase(luaEvent->funcRef);
        if (luaEvent->state == LUAEVENT_STATE_RUN)
        {
            uint32 delay = luaEvent->delay;
            bool remove = luaEvent->repeats == 1;
            if (!remove)
                AddEvent(luaEvent); // Reschedule before calling incase RemoveEvents used
            // Call the timed event
            (*E)->OnTimedEvent(luaEvent->funcRef, delay, luaEvent->repeats ? luaEvent->repeats-- : luaEvent->repeats, obj);
            if (!remove)
                continue;
        }
        // Event should be deleted (executed last time or set to be aborted)
        RemoveEvent(luaEvent);
    }
}
References AddEvent(), LuaEvent::delay, eventList, eventMap, LuaEvent::funcRef, LUAEVENT_STATE_ERASE, LUAEVENT_STATE_RUN, m_time, obj, RemoveEvent(), LuaEvent::repeats, and LuaEvent::state.
Referenced by Eluna_UnitScript::OnUnitUpdate(), Eluna::OnWorldUpdate(), and Eluna::UpdateAI().
Friends And Related Symbol Documentation
EventMgr
friend class EventMgr friend
Member Data Documentation
E
Eluna** ElunaEventProcessor::E private
eventList
EventList ElunaEventProcessor::eventList private
Referenced by AddEvent(), RemoveEvents_internal(), SetStates(), and Update().
eventMap
EventMap ElunaEventProcessor::eventMap
Referenced by AddEvent(), RemoveEvents_internal(), SetState(), SetStates(), and Update().
m_time
uint64 ElunaEventProcessor::m_time private
Referenced by AddEvent(), and Update().
obj
WorldObject* ElunaEventProcessor::obj private
Referenced by ElunaEventProcessor(), Update(), and ~ElunaEventProcessor().
The documentation for this class was generated from the following files:
mod-eluna/src/LuaEngine/ElunaEventMgr.h
mod-eluna/src/LuaEngine/ElunaEventMgr.cpp