AzerothCore Doxygen
TargetedMovementGenerator.cpp File Reference
#include "TargetedMovementGenerator.h"
#include "Creature.h"
#include "CreatureAI.h"
#include "MoveSplineInit.h"
#include "Pet.h"
#include "Player.h"
#include "Spell.h"
#include "Transport.h"
Functions
static bool IsMutualChase (Unit *owner, Unit *target)
float GetChaseRange (Unit const *owner, Unit const *target)
static Optional< float > GetVelocity (Unit *owner, Unit *target, G3D::Vector3 const &dest, bool playerPet)
static Position const PredictPosition (Unit *target)
static bool IsValidPredictedPosition (Unit *target, Position const &predicted)
Function Documentation
GetChaseRange()
float GetChaseRange (Unit const * owner, Unit const * target) inline
{
    float hitboxSum = owner->GetCombatReach() + target->GetCombatReach();
    float hoverDelta = owner->GetHoverHeight() - target->GetHoverHeight();
    if (hoverDelta != 0.0f)
        return std::sqrt(std::max(hitboxSum * hitboxSum - hoverDelta * hoverDelta, 0.0f));
    return hitboxSum;
}
References Unit::GetCombatReach(), and Unit::GetHoverHeight().
Referenced by ChaseMovementGenerator< T >::DoUpdate().
GetVelocity()
static Optional< float > GetVelocity (Unit * owner, Unit * target, G3D::Vector3 const & dest, bool playerPet) static
{
    Optional<float> speed = {};
    if (!owner->IsInCombat() && !owner->IsVehicle() && !owner->HasUnitFlag(UNIT_FLAG_POSSESSED) &&
        (owner->IsPet() || owner->IsGuardian() || owner->GetGUID() == target->GetCritterGUID() || owner->GetCharmerOrOwnerGUID() == target->GetGUID()))
    {
        uint32 moveFlags = target->GetUnitMovementFlags();
        if (target->IsWalking())
        {
            moveFlags |= MOVEMENTFLAG_WALKING;
        }
        UnitMoveType moveType = Movement::SelectSpeedType(moveFlags);
        speed = target->GetSpeed(moveType);
        if (playerPet)
        {
            float distance = owner->GetDistance2d(dest.x, dest.y) - target->GetObjectSize() - (*speed / 2.f);
            if (distance > 0.f)
            {
                float multiplier = 1.f + (distance / 10.f);
                *speed *= multiplier;
            }
        }
    }
    return speed;
}
References Unit::GetCharmerOrOwnerGUID(), Unit::GetCritterGUID(), WorldObject::GetDistance2d(), Object::GetGUID(), WorldObject::GetObjectSize(), Unit::GetSpeed(), Unit::GetUnitMovementFlags(), Unit::HasUnitFlag(), Unit::IsGuardian(), Unit::IsInCombat(), Unit::IsPet(), Unit::IsVehicle(), Unit::IsWalking(), MOVEMENTFLAG_WALKING, Movement::SelectSpeedType(), and UNIT_FLAG_POSSESSED.
Referenced by FollowMovementGenerator< T >::DoUpdate().
IsMutualChase()
static bool IsMutualChase (Unit * owner, Unit * target) static
{
    if (target->GetMotionMaster()->GetCurrentMovementGeneratorType() != CHASE_MOTION_TYPE)
        return false;
    return target->GetVictim() == owner;
}
References CHASE_MOTION_TYPE, MotionMaster::GetCurrentMovementGeneratorType(), Unit::GetMotionMaster(), and Unit::GetVictim().
Referenced by ChaseMovementGenerator< T >::DoUpdate().
IsValidPredictedPosition()
static bool IsValidPredictedPosition (Unit * target, Position const & predicted) static
{
    Position current = target->GetPosition();
    if (current.GetExactDist2d(&predicted) > 15.0f)
        return false;
    // Check line of sight from current to predicted to avoid clipping through geometry
    if (!target->IsWithinLOS(predicted.GetPositionX(), predicted.GetPositionY(), predicted.GetPositionZ()))
        return false;
    return true;
}
References Position::GetExactDist2d(), Position::GetPosition(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), and WorldObject::IsWithinLOS().
Referenced by FollowMovementGenerator< T >::DoUpdate().
PredictPosition()
static Position const PredictPosition (Unit * target) static
{
    Position pos = target->GetPosition();
    // 0.5 - it's time (0.5 sec) between starting movement opcode (e.g. MSG_MOVE_START_FORWARD) and MSG_MOVE_HEARTBEAT sent by client
    float speed = target->GetSpeed(Movement::SelectSpeedType(target->GetUnitMovementFlags())) * 0.5f;
    float orientation = target->GetOrientation();
    if (target->m_movementInfo.HasMovementFlag(MOVEMENTFLAG_FORWARD))
    {
        pos.m_positionX += cos(orientation) * speed;
        pos.m_positionY += std::sin(orientation) * speed;
    }
    else if (target->m_movementInfo.HasMovementFlag(MOVEMENTFLAG_BACKWARD))
    {
        pos.m_positionX -= cos(orientation) * speed;
        pos.m_positionY -= std::sin(orientation) * speed;
    }
    if (target->m_movementInfo.HasMovementFlag(MOVEMENTFLAG_STRAFE_LEFT))
    {
        pos.m_positionX += cos(orientation + M_PI / 2.f) * speed;
        pos.m_positionY += std::sin(orientation + M_PI / 2.f) * speed;
    }
    else if (target->m_movementInfo.HasMovementFlag(MOVEMENTFLAG_STRAFE_RIGHT))
    {
        pos.m_positionX += cos(orientation - M_PI / 2.f) * speed;
        pos.m_positionY += std::sin(orientation - M_PI / 2.f) * speed;
    }
    return pos;
}
References Position::GetOrientation(), Position::GetPosition(), Unit::GetSpeed(), Unit::GetUnitMovementFlags(), MovementInfo::HasMovementFlag(), WorldObject::m_movementInfo, Position::m_positionX, Position::m_positionY, MOVEMENTFLAG_BACKWARD, MOVEMENTFLAG_FORWARD, MOVEMENTFLAG_STRAFE_LEFT, MOVEMENTFLAG_STRAFE_RIGHT, and Movement::SelectSpeedType().
Referenced by FollowMovementGenerator< T >::DoUpdate().