AzerothCore Doxygen
instance_blackrock_depths Struct Reference
Public Member Functions
instance_blackrock_depths (Map *map)
void OnPlayerEnter (Player *) override
void ReplaceMoiraIfSaved ()
void Initialize () override
void OnCreatureCreate (Creature *creature) override
void OnGameObjectCreate (GameObject *go) override
void OnUnitDeath (Unit *unit) override
void SetData (uint32 type, uint32 data) override
uint32 GetData (uint32 type) const override
ObjectGuid GetGuidData (uint32 data) const override
std::string GetSaveData () override
void Load (const char *in) override
void TombOfSevenEvent ()
void TombOfSevenReset ()
bool CheckTombReset (uint32 diff)
void Update (uint32 diff) override
Public Member Functions inherited from InstanceScript
InstanceScript (Map *map)
~InstanceScript () override
virtual void CreatureLooted (Creature *, LootType)
void SaveToDB ()
virtual bool IsEncounterInProgress () const
void OnCreatureCreate (Creature *creature) override
void OnCreatureRemove (Creature *creature) override
void OnGameObjectCreate (GameObject *go) override
void OnGameObjectRemove (GameObject *go) override
ObjectGuid GetObjectGuid (uint32 type) const
ObjectGuid GetGuidData (uint32 type) const override
Creature * GetCreature (uint32 type)
GameObject * GetGameObject (uint32 type)
virtual void OnPlayerLeave (Player *)
virtual void OnPlayerAreaUpdate (Player *, uint32, uint32)
virtual void OnPlayerInWaterStateUpdate (Player *, bool)
void HandleGameObject (ObjectGuid guid, bool open, GameObject *go=nullptr)
Open or close a GameObject by GUID.
void HandleGameObject (uint32 type, bool open)
Open or close a GameObject registered via LoadObjectData.
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
void DoRespawnGameObject (uint32 type)
void DoRespawnCreature (ObjectGuid guid, bool force=false)
void DoRespawnCreature (uint32 type, bool force=false)
void DoUpdateWorldState (uint32 worldstateId, uint32 worldstateValue)
void DoSendNotifyToInstance (char const *format,...)
void DoUpdateAchievementCriteria (AchievementCriteriaTypes type, uint32 miscValue1=0, uint32 miscValue2=0, Unit *unit=nullptr)
void DoStartTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoStopTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoRemoveAurasDueToSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayer (Player *player, uint32 spell, bool includePets, bool includeControlled)
bool ServerAllowsTwoSideGroups ()
virtual bool SetBossState (uint32 id, EncounterState state)
EncounterState GetBossState (uint32 id) const
CreatureBoundary const * GetBossBoundary (uint32 id) const
BossInfo const * GetBossInfo (uint32 id) const
uint32 GetPersistentData (uint32 index) const
void StorePersistentData (uint32 index, uint32 data)
virtual bool CheckAchievementCriteriaMeet (uint32, Player const *, Unit const *=nullptr, uint32=0)
virtual bool CheckRequiredBosses (uint32, Player const *=nullptr) const
bool _SkipCheckRequiredBosses (Player const *player=nullptr) const
void SetCompletedEncountersMask (uint32 newMask, bool save)
uint32 GetCompletedEncounterMask () const
void SendEncounterUnit (uint32 type, Unit *unit=nullptr, uint8 param1=0, uint8 param2=0)
virtual void FillInitialWorldStates (WorldPackets::WorldState::InitWorldStates &)
uint32 GetEncounterCount () const
void MarkAreaTriggerDone (uint32 id)
void ResetAreaTriggerDone (uint32 id)
bool IsAreaTriggerDone (uint32 id) const
virtual void DoAction (int32)
void DoForAllMinions (uint32 id, std::function< void(Creature *)> exec)
void StoreGameObjectState (ObjectGuid::LowType spawnId, uint8 state)
uint8 GetStoredGameObjectState (ObjectGuid::LowType spawnId) const
void LoadInstanceSavedGameobjectStateData ()
bool IsBossDone (uint32 bossId) const
bool AllBossesDone () const
bool AllBossesDone (std::initializer_list< uint32 > bossIds) const
TeamId GetTeamIdInInstance () const
void SetTeamIdInInstance (TeamId teamId)
bool IsTwoFactionInstance () const
Public Member Functions inherited from ZoneScript
ZoneScript ()
virtual ~ZoneScript ()
virtual uint32 GetCreatureEntry (ObjectGuid::LowType, CreatureData const *data)
virtual uint32 GetGameObjectEntry (ObjectGuid::LowType, uint32 entry)
virtual void OnCreatureEvade (Creature *)
virtual void SetGuidData (uint32, ObjectGuid)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
virtual void ProcessEvent (WorldObject *, uint32)
Public Attributes
uint32 encounter [MAX_ENCOUNTER]
std::string str_data
ObjectGuid EmperorGUID
ObjectGuid PhalanxGUID
ObjectGuid MagmusGUID
ObjectGuid MoiraGUID
ObjectGuid PriestessGUID
ObjectGuid IronhandGUID [6]
ObjectGuid CorenGUID
ObjectGuid GoArena1GUID
ObjectGuid GoArena2GUID
ObjectGuid GoArena3GUID
ObjectGuid GoArena4GUID
ObjectGuid GoShadowLockGUID
ObjectGuid GoShadowMechGUID
ObjectGuid GoShadowGiantGUID
ObjectGuid GoShadowDummyGUID
ObjectGuid GoBarKegGUID
ObjectGuid GoBarKegTrapGUID
ObjectGuid GoBarDoorGUID
ObjectGuid GoTombEnterGUID
ObjectGuid GoTombExitGUID
ObjectGuid GoLyceumGUID
ObjectGuid GoSFSGUID
ObjectGuid GoSFNGUID
ObjectGuid GoGolemNGUID
ObjectGuid GoGolemSGUID
ObjectGuid GoThroneGUID
ObjectGuid GoChestGUID
ObjectGuid GoSpectralChaliceGUID
uint32 BarAleCount
uint32 GhostKillCount
ObjectGuid TombBossGUIDs [7]
uint32 tombResetTimer
uint32 TombTimer
uint32 TombEventCounter
uint32 OpenedCoofers
uint32 IronhandCounter
GuidList ArgelmachAdds
ObjectGuid ArgelmachGUID
TempSummon * TempSummonGrimstone = nullptr
Position GrimstonePositon = Position(625.559f, -205.618f, -52.735f, 2.609f)
time_t timeRingFail = 0
uint8 arenaMobsToSpawn
uint8 arenaBossToSpawn
std::vector< ObjectGuid > ArenaSpectators
Position CenterOfRingOfLaw = Position(595.289, -186.56)
ObjectGuid EmperorSenators [5]
std::vector< ObjectGuid > EmperorSenatorsVector
Position EmperorSpawnPos = Position(1380.52, -831, 115)
Public Attributes inherited from InstanceScript
Map * instance
TaskScheduler scheduler
Additional Inherited Members
Static Public Member Functions inherited from InstanceScript
static std::string GetBossStateName (uint8 state)
Protected Member Functions inherited from InstanceScript
void SetHeaders (std::string const &dataHeaders)
void SetBossNumber (uint32 number)
void SetPersistentDataCount (uint32 number)
void LoadBossBoundaries (BossBoundaryData const &data)
void LoadDoorData (DoorData const *data)
void LoadMinionData (MinionData const *data)
void LoadObjectData (ObjectData const *creatureData, ObjectData const *gameObjectData)
void LoadSummonData (ObjectData const *data)
void SetSummoner (Creature *creature)
void AddObject (Creature *obj, bool add=true)
void RemoveObject (Creature *obj)
void AddObject (GameObject *obj, bool add=true)
void RemoveObject (GameObject *obj)
void AddObject (WorldObject *obj, uint32 type, bool add=true)
void RemoveObject (WorldObject *obj, uint32 type)
void AddDoor (GameObject *door, bool add=true)
void RemoveDoor (GameObject *door)
void AddMinion (Creature *minion, bool add=true)
void RemoveMinion (Creature *minion)
void UpdateDoorState (GameObject *door)
void UpdateMinionState (Creature *minion, EncounterState state)
bool ReadSaveDataHeaders (std::istringstream &data)
void ReadSaveDataBossStates (std::istringstream &data)
void ReadSavePersistentData (std::istringstream &data)
virtual void ReadSaveDataMore (std::istringstream &)
void WriteSaveDataHeaders (std::ostringstream &data)
void WriteSaveDataBossStates (std::ostringstream &data)
void WritePersistentData (std::ostringstream &data)
virtual void WriteSaveDataMore (std::ostringstream &)
Detailed Description
Constructor & Destructor Documentation
instance_blackrock_depths()
instance_blackrock_depths::instance_blackrock_depths (Map * map) inline
                                        : InstanceScript(map)
    {
        SetHeaders(DataHeader);
    }
References DataHeader, and InstanceScript::SetHeaders().
Member Function Documentation
CheckTombReset()
bool instance_blackrock_depths::CheckTombReset (uint32 diff) inline
    {
        bool anyBossAlive = false; // status of the bosses up until the current one
        for (uint8 i = 0; i < TombEventCounter; i++)
        {
            Creature* boss = instance->GetCreature(TombBossGUIDs[i]);
            if (boss)
            {
                anyBossAlive |= boss->IsAlive();
                if (boss->IsAlive() && boss->IsInCombat())
                {
                    tombResetTimer = TIMER_TOMB_RESET;
                    return false;  // any boss in combat means we shouldn't reset.
                }
            }
        }
        if (!anyBossAlive) // no boss alive, put reset timer back up
            tombResetTimer = TIMER_TOMB_RESET;
        tombResetTimer -= diff;
        return tombResetTimer < diff;
    }
References Map::GetCreature(), InstanceScript::instance, Unit::IsAlive(), Unit::IsInCombat(), TIMER_TOMB_RESET, TombBossGUIDs, TombEventCounter, and tombResetTimer.
Referenced by Update().
GetData()
uint32 instance_blackrock_depths::GetData (uint32 type) const inline override virtual
Reimplemented from ZoneScript.
    {
        switch (type)
        {
            case TYPE_RING_OF_LAW:
                return encounter[0];
            case TYPE_VAULT:
                return encounter[1];
            case TYPE_BAR:
                if (encounter[2] == IN_PROGRESS && BarAleCount == 3)
                    return SPECIAL;
                else
                    return encounter[2];
            case TYPE_TOMB_OF_SEVEN:
                return encounter[3];
            case TYPE_LYCEUM:
                return encounter[4];
            case TYPE_IRON_HALL:
                return encounter[5];
            case DATA_TIME_RING_FAIL:
                return timeRingFail;
            case DATA_ARENA_MOBS:
                return arenaMobsToSpawn;
            case DATA_ARENA_BOSS:
                return arenaBossToSpawn;
        }
        return 0;
    }
References arenaBossToSpawn, arenaMobsToSpawn, BarAleCount, DATA_ARENA_BOSS, DATA_ARENA_MOBS, DATA_TIME_RING_FAIL, encounter, IN_PROGRESS, SPECIAL, timeRingFail, TYPE_BAR, TYPE_IRON_HALL, TYPE_LYCEUM, TYPE_RING_OF_LAW, TYPE_TOMB_OF_SEVEN, and TYPE_VAULT.
Referenced by Update().
GetGuidData()
ObjectGuid instance_blackrock_depths::GetGuidData (uint32 data) const inline override virtual
Reimplemented from ZoneScript.
    {
        switch (data)
        {
            case DATA_EMPEROR:
                return EmperorGUID;
            case DATA_PHALANX:
                return PhalanxGUID;
            case DATA_MOIRA:
                return MoiraGUID;
            case DATA_COREN:
                return CorenGUID;
            case DATA_ARENA1:
                return GoArena1GUID;
            case DATA_ARENA2:
                return GoArena2GUID;
            case DATA_ARENA3:
                return GoArena3GUID;
            case DATA_ARENA4:
                return GoArena4GUID;
            case DATA_GO_BAR_KEG:
                return GoBarKegGUID;
            case DATA_GO_BAR_KEG_TRAP:
                return GoBarKegTrapGUID;
            case DATA_GO_BAR_DOOR:
                return GoBarDoorGUID;
            case DATA_SF_BRAZIER_N:
                return GoSFNGUID;
            case DATA_SF_BRAZIER_S:
                return GoSFSGUID;
            case DATA_THRONE_DOOR:
                return GoThroneGUID;
            case DATA_GOLEM_DOOR_N:
                return GoGolemNGUID;
            case DATA_GOLEM_DOOR_S:
                return GoGolemSGUID;
            case DATA_GO_CHALICE:
                return GoSpectralChaliceGUID;
            case DATA_MAGMUS:
            {
                return MagmusGUID;
            }
        }
        return ObjectGuid::Empty;
    }
References CorenGUID, DATA_ARENA1, DATA_ARENA2, DATA_ARENA3, DATA_ARENA4, DATA_COREN, DATA_EMPEROR, DATA_GO_BAR_DOOR, DATA_GO_BAR_KEG, DATA_GO_BAR_KEG_TRAP, DATA_GO_CHALICE, DATA_GOLEM_DOOR_N, DATA_GOLEM_DOOR_S, DATA_MAGMUS, DATA_MOIRA, DATA_PHALANX, DATA_SF_BRAZIER_N, DATA_SF_BRAZIER_S, DATA_THRONE_DOOR, EmperorGUID, ObjectGuid::Empty, GoArena1GUID, GoArena2GUID, GoArena3GUID, GoArena4GUID, GoBarDoorGUID, GoBarKegGUID, GoBarKegTrapGUID, GoGolemNGUID, GoGolemSGUID, GoSFNGUID, GoSFSGUID, GoSpectralChaliceGUID, GoThroneGUID, MagmusGUID, MoiraGUID, and PhalanxGUID.
Referenced by SetData().
GetSaveData()
std::string instance_blackrock_depths::GetSaveData () inline override virtual
Reimplemented from InstanceScript.
    {
        return str_data;
    }
References str_data.
Initialize()
void instance_blackrock_depths::Initialize () inline override virtual
Reimplemented from InstanceScript.
    {
        memset(&encounter, 0, sizeof(encounter));
        BarAleCount = 0;
        GhostKillCount = 0;
        TombTimer = TIMER_TOMB_START;
        TombEventCounter = 0;
        tombResetTimer   = 0;
        OpenedCoofers = 0;
        IronhandCounter  = 0;
        ArenaSpectators.clear();
        // these are linked to the dungeon and not how many times the arena started.
        arenaMobsToSpawn = urand(0, 5);
        arenaBossToSpawn = urand(0, 5);
    }
References arenaBossToSpawn, arenaMobsToSpawn, ArenaSpectators, BarAleCount, encounter, GhostKillCount, IronhandCounter, OpenedCoofers, TIMER_TOMB_START, TombEventCounter, tombResetTimer, TombTimer, and urand().
Load()
void instance_blackrock_depths::Load (const char * in) inline override virtual
Reimplemented from InstanceScript.
    {
        if (!in)
        {
            OUT_LOAD_INST_DATA_FAIL;
            return;
        }
        OUT_LOAD_INST_DATA(in);
        std::istringstream loadStream(in);
        loadStream >> encounter[0] >> encounter[1] >> encounter[2] >> encounter[3]
                   >> encounter[4] >> encounter[5] >> GhostKillCount;
        for (uint8 i = 0; i < MAX_ENCOUNTER; ++i)
            if (encounter[i] == IN_PROGRESS)
                encounter[i] = NOT_STARTED;
        if (GhostKillCount > 0 && GhostKillCount < 7)
            GhostKillCount = 0;//reset tomb of seven event
        if (GhostKillCount >= 7)
            GhostKillCount = 7;
        OUT_LOAD_INST_DATA_COMPLETE;
    }
References encounter, GhostKillCount, IN_PROGRESS, MAX_ENCOUNTER, NOT_STARTED, OUT_LOAD_INST_DATA, OUT_LOAD_INST_DATA_COMPLETE, and OUT_LOAD_INST_DATA_FAIL.
OnCreatureCreate()
void instance_blackrock_depths::OnCreatureCreate (Creature * creature) inline override virtual
Reimplemented from ZoneScript.
    {
        switch (creature->GetEntry())
        {
            case NPC_EMPEROR:
                EmperorGUID = creature->GetGUID();
                break;
            case NPC_PHALANX:
                PhalanxGUID = creature->GetGUID();
                break;
            case NPC_MOIRA:
                MoiraGUID = creature->GetGUID();
                break;
            case NPC_COREN_DIREBREW:
                CorenGUID = creature->GetGUID();
                break;
            case NPC_ANGERREL:
                TombBossGUIDs[0] = creature->GetGUID();
                break;
            case NPC_SEETHREL:
                TombBossGUIDs[1] = creature->GetGUID();
                break;
            case NPC_DOPEREL:
                TombBossGUIDs[2] = creature->GetGUID();
                break;
            case NPC_GLOOMREL:
                TombBossGUIDs[3] = creature->GetGUID();
                break;
            case NPC_VILEREL:
                TombBossGUIDs[4] = creature->GetGUID();
                break;
            case NPC_HATEREL:
                TombBossGUIDs[5] = creature->GetGUID();
                break;
            case NPC_DOOMREL:
                TombBossGUIDs[6] = creature->GetGUID();
                break;
            case NPC_MAGMUS:
                MagmusGUID = creature->GetGUID();
                if (!creature->IsAlive())
                    HandleGameObject(GoThroneGUID, true); // if Magmus is dead open door to last boss
                break;
            case NPC_WEAPON_TECHNICIAN:
            case NPC_DOOMFORGE_ARCANASMITH:
            case NPC_RAGEREAVER_GOLEM:
            case NPC_WRATH_HAMMER_CONSTRUCT:
                if (creature->IsAlive() && creature->GetPositionZ() < -51.5f && creature->GetPositionZ() > -55.f)
                    ArgelmachAdds.push_back(creature->GetGUID());
                break;
            case NPC_GOLEM_LORD_ARGELMACH:
                ArgelmachGUID = creature->GetGUID();
                break;
            case NPC_IRONHAND_GUARDIAN:
                IronhandGUID[IronhandCounter] = creature->GetGUID();
                IronhandCounter++;
                break;
            case NPC_ARENA_SPECTATOR:
                ArenaSpectators.push_back(creature->GetGUID());
                if (encounter[TYPE_RING_OF_LAW] == DONE) // added for crashes
                {
                    creature->SetFaction(FACTION_NEUTRAL);
                    creature->SetReactState(REACT_DEFENSIVE);
                }
                break;
            case NPC_SHADOWFORGE_PEASANT:
            case NPC_SHADOWFORCE_CITIZEN: // both do the same
                if (creature->GetDistance2d(CenterOfRingOfLaw.GetPositionX(), CenterOfRingOfLaw.GetPositionY()) < (float)RADIUS_RING_OF_LAW)
                    ArenaSpectators.push_back(creature->GetGUID());
                if (encounter[TYPE_RING_OF_LAW] == DONE) // added for crashes
                {
                    creature->SetFaction(FACTION_NEUTRAL);
                    creature->SetReactState(REACT_DEFENSIVE);
                }
                break;
            case NPC_SHADOWFORGE_SENATOR:
                // keep track of Senators that are not too far from emperor. Can't really use emperor as creature due to him possibly not being spawned.
                // some senators spawn at ring of law
                if (creature->GetDistance2d(EmperorSpawnPos.GetPositionX(), EmperorSpawnPos.GetPositionY()) < (float)DISTANCE_EMPEROR_ROOM)
                    EmperorSenatorsVector.push_back(creature->GetGUID());
                break;
            default:
                break;
        }
    }
References ArenaSpectators, ArgelmachAdds, ArgelmachGUID, CenterOfRingOfLaw, CorenGUID, DISTANCE_EMPEROR_ROOM, DONE, EmperorGUID, EmperorSenatorsVector, EmperorSpawnPos, encounter, FACTION_NEUTRAL, WorldObject::GetDistance2d(), Object::GetEntry(), Object::GetGUID(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), GoThroneGUID, InstanceScript::HandleGameObject(), IronhandCounter, IronhandGUID, Unit::IsAlive(), MagmusGUID, MoiraGUID, NPC_ANGERREL, NPC_ARENA_SPECTATOR, NPC_COREN_DIREBREW, NPC_DOOMFORGE_ARCANASMITH, NPC_DOOMREL, NPC_DOPEREL, NPC_EMPEROR, NPC_GLOOMREL, NPC_GOLEM_LORD_ARGELMACH, NPC_HATEREL, NPC_IRONHAND_GUARDIAN, NPC_MAGMUS, NPC_MOIRA, NPC_PHALANX, NPC_RAGEREAVER_GOLEM, NPC_SEETHREL, NPC_SHADOWFORCE_CITIZEN, NPC_SHADOWFORGE_PEASANT, NPC_SHADOWFORGE_SENATOR, NPC_VILEREL, NPC_WEAPON_TECHNICIAN, NPC_WRATH_HAMMER_CONSTRUCT, PhalanxGUID, RADIUS_RING_OF_LAW, REACT_DEFENSIVE, Unit::SetFaction(), Creature::SetReactState(), TombBossGUIDs, and TYPE_RING_OF_LAW.
OnGameObjectCreate()
void instance_blackrock_depths::OnGameObjectCreate (GameObject * go) inline override virtual
Reimplemented from ZoneScript.
    {
        switch (go->GetEntry())
        {
            case GO_ARENA1:
                GoArena1GUID = go->GetGUID();
                break;
            case GO_ARENA2:
                GoArena2GUID = go->GetGUID();
                break;
            case GO_ARENA3:
                GoArena3GUID = go->GetGUID();
                break;
            case GO_ARENA4:
                GoArena4GUID = go->GetGUID();
                break;
            case GO_SHADOW_LOCK:
                GoShadowLockGUID = go->GetGUID();
                break;
            case GO_SHADOW_MECHANISM:
                GoShadowMechGUID = go->GetGUID();
                break;
            case GO_SHADOW_GIANT_DOOR:
                GoShadowGiantGUID = go->GetGUID();
                break;
            case GO_SHADOW_DUMMY:
                GoShadowDummyGUID = go->GetGUID();
                break;
            case GO_BAR_KEG_SHOT:
                GoBarKegGUID = go->GetGUID();
                break;
            case GO_BAR_KEG_TRAP:
                GoBarKegTrapGUID = go->GetGUID();
                break;
            case GO_BAR_DOOR:
                GoBarDoorGUID = go->GetGUID();
                break;
            case GO_TOMB_ENTER:
                GoTombEnterGUID = go->GetGUID();
                break;
            case GO_TOMB_EXIT:
                GoTombExitGUID = go->GetGUID();
                if (GhostKillCount >= 7)
                    HandleGameObject(ObjectGuid::Empty, true, go);
                else
                    HandleGameObject(ObjectGuid::Empty, false, go);
                break;
            case GO_LYCEUM:
                GoLyceumGUID = go->GetGUID();
                break;
            case GO_SF_S:
                GoSFSGUID = go->GetGUID();
                break;
            case GO_SF_N:
                GoSFNGUID = go->GetGUID();
                break;
            case GO_GOLEM_ROOM_N:
                GoGolemNGUID = go->GetGUID();
                break;
            case GO_GOLEM_ROOM_S:
                GoGolemSGUID = go->GetGUID();
                break;
            case GO_THRONE_ROOM:
                GoThroneGUID = go->GetGUID();
                break;
            case GO_CHEST_SEVEN:
                GoChestGUID = go->GetGUID();
                break;
            case GO_SPECTRAL_CHALICE:
                GoSpectralChaliceGUID = go->GetGUID();
                break;
        }
    }
References ObjectGuid::Empty, Object::GetEntry(), Object::GetGUID(), GhostKillCount, GO_ARENA1, GO_ARENA2, GO_ARENA3, GO_ARENA4, GO_BAR_DOOR, GO_BAR_KEG_SHOT, GO_BAR_KEG_TRAP, GO_CHEST_SEVEN, GO_GOLEM_ROOM_N, GO_GOLEM_ROOM_S, GO_LYCEUM, GO_SF_N, GO_SF_S, GO_SHADOW_DUMMY, GO_SHADOW_GIANT_DOOR, GO_SHADOW_LOCK, GO_SHADOW_MECHANISM, GO_SPECTRAL_CHALICE, GO_THRONE_ROOM, GO_TOMB_ENTER, GO_TOMB_EXIT, GoArena1GUID, GoArena2GUID, GoArena3GUID, GoArena4GUID, GoBarDoorGUID, GoBarKegGUID, GoBarKegTrapGUID, GoChestGUID, GoGolemNGUID, GoGolemSGUID, GoLyceumGUID, GoSFNGUID, GoSFSGUID, GoShadowDummyGUID, GoShadowGiantGUID, GoShadowLockGUID, GoShadowMechGUID, GoSpectralChaliceGUID, GoThroneGUID, GoTombEnterGUID, GoTombExitGUID, and InstanceScript::HandleGameObject().
OnPlayerEnter()
void instance_blackrock_depths::OnPlayerEnter (Player *) inline override virtual
Reimplemented from InstanceScript.
    {
        ReplaceMoiraIfSaved(); // In case a player joins the party during the run
     //   SetData(TYPE_RING_OF_LAW, DONE);
    }
References ReplaceMoiraIfSaved().
OnUnitDeath()
void instance_blackrock_depths::OnUnitDeath (Unit * unit) inline override virtual
Reimplemented from ZoneScript.
    {
        uint32 deadSenators = 0;
        switch (unit->GetEntry())
        {
            case NPC_WEAPON_TECHNICIAN:
            case NPC_DOOMFORGE_ARCANASMITH:
            case NPC_RAGEREAVER_GOLEM:
            case NPC_WRATH_HAMMER_CONSTRUCT:
                ArgelmachAdds.remove(unit->GetGUID());
                break;
            case NPC_MAGMUS:
                SetData(TYPE_IRON_HALL, DONE);
                break;
            case NPC_SHADOWFORGE_SENATOR:
                deadSenators = 1; //hacky, but we cannot count the unit that just died through its state because OnUnitDeath() is called before the state is set.
                for (const auto &senatorGUID: EmperorSenatorsVector)
                    if (Creature* senator = instance->GetCreature(senatorGUID))
                        if (!senator->IsAlive() || senator->isDying())
                            deadSenators++;
                if (Creature* emperor = instance->GetCreature(EmperorGUID))
                    // send % of senators that died
                    emperor->AI()->SetData(0, (100 * deadSenators) / EmperorSenatorsVector.size());
                break;
            case NPC_ANGERREL:
            case NPC_DOPEREL:
            case NPC_HATEREL:
            case NPC_VILEREL:
            case NPC_SEETHREL:
            case NPC_GLOOMREL:
            case NPC_DOOMREL:
                GhostKillCount++;
                if (GhostKillCount >= 7)
                    SetData(TYPE_TOMB_OF_SEVEN, DONE);
                break;
            default:
                break;
        }
    }
References ArgelmachAdds, DONE, EmperorGUID, EmperorSenatorsVector, Map::GetCreature(), Object::GetEntry(), Object::GetGUID(), GhostKillCount, InstanceScript::instance, NPC_ANGERREL, NPC_DOOMFORGE_ARCANASMITH, NPC_DOOMREL, NPC_DOPEREL, NPC_GLOOMREL, NPC_HATEREL, NPC_MAGMUS, NPC_RAGEREAVER_GOLEM, NPC_SEETHREL, NPC_SHADOWFORGE_SENATOR, NPC_VILEREL, NPC_WEAPON_TECHNICIAN, NPC_WRATH_HAMMER_CONSTRUCT, SetData(), TYPE_IRON_HALL, and TYPE_TOMB_OF_SEVEN.
ReplaceMoiraIfSaved()
void instance_blackrock_depths::ReplaceMoiraIfSaved () inline
    {
        ObjectGuid* GUIDToReplace = &PriestessGUID; // default to having Moira
        ObjectGuid* GUIDToSpawn   = &MoiraGUID;
        uint32      NPCEntry      = NPC_MOIRA;
        bool        MoiraSaved    = true;
        // check if all players saved her.
        Map::PlayerList const& lPlayers = instance->GetPlayers();
        if (!lPlayers.IsEmpty())
        {
            for (Map::PlayerList::const_iterator itr = lPlayers.begin(); itr != lPlayers.end(); ++itr)
            {
                if (Player* player = itr->GetSource())
                {
                    // set to false if this player hasn't saved her. Another player can't put it to true.
                    MoiraSaved = MoiraSaved && ((player->GetQuestStatus(PRINCESS_QUEST_HORDE) == QUEST_STATUS_REWARDED)
                                                || (player->GetQuestStatus(PRINCESS_QUEST_ALLIANCE) == QUEST_STATUS_REWARDED));
                }
            }
        }
        // assign correct GUIDs and spawn targets
        if (MoiraSaved)
        {
            GUIDToReplace = &MoiraGUID;
            GUIDToSpawn   = &PriestessGUID;
            NPCEntry      = NPC_PRIESTESS;
        }
        if (Creature* CreatureToReplace = instance->GetCreature(*GUIDToReplace))
        {
            Creature* NewSpawn = instance->SummonCreature(NPCEntry, CreatureToReplace->GetPosition());
            CreatureToReplace->RemoveFromWorld();
            *GUIDToSpawn = NewSpawn->GetGUID();
        }
    }
References MapRefMgr::begin(), MapRefMgr::end(), Map::GetCreature(), Object::GetGUID(), Map::GetPlayers(), InstanceScript::instance, LinkedListHead::IsEmpty(), MoiraGUID, NPC_MOIRA, NPC_PRIESTESS, PriestessGUID, PRINCESS_QUEST_ALLIANCE, PRINCESS_QUEST_HORDE, QUEST_STATUS_REWARDED, TempSummon::RemoveFromWorld(), and Map::SummonCreature().
Referenced by OnPlayerEnter(), and SetData().
SetData()
void instance_blackrock_depths::SetData (uint32 type, uint32 data) inline override virtual
Reimplemented from ZoneScript.
    {
        LOG_DEBUG("scripts.ai", "Instance Blackrock Depths: SetData update (Type: {} Data {})", type, data);
        switch (type)
        {
            case TYPE_RING_OF_LAW:
                encounter[0] = data;
                switch (data)
                {
                case IN_PROGRESS:
                    TempSummonGrimstone = instance->SummonCreature(NPC_GRIMSTONE, GrimstonePositon);
                    break;
                case FAIL:
                    if (TempSummonGrimstone)
                    {
                        TempSummonGrimstone->RemoveFromWorld();
                        TempSummonGrimstone = nullptr;
                        timeRingFail = GameTime::GetGameTime().count();
                    }
                    SetData(TYPE_RING_OF_LAW, NOT_STARTED);
                    break;
                case DONE:
                    for (auto const& itr : ArenaSpectators)
                        if (Creature* spectator = instance->GetCreature(itr))
{
                            spectator->SetFaction(FACTION_NEUTRAL);
                            spectator->SetReactState(REACT_DEFENSIVE);
                        }
                    break;
                default:
                    break;
                }
                break;
            case TYPE_VAULT:
                encounter[1] = data;
                break;
            case TYPE_BAR:
                if (data == SPECIAL)
                    ++BarAleCount;
                else
                    encounter[2] = data;
                break;
            case TYPE_TOMB_OF_SEVEN:
                encounter[3] = data;
                switch (data)
                {
                    case IN_PROGRESS:
                        HandleGameObject(GoTombExitGUID, false);
                        HandleGameObject(GoTombEnterGUID, false);
                        break;
                    case DONE:
                        DoRespawnGameObject(GoChestGUID, DAY);
                        HandleGameObject(GoTombExitGUID, true);
                        HandleGameObject(GoTombEnterGUID, true);
                        break;
                }
                break;
            case TYPE_LYCEUM:
                encounter[4] = data;
                if (data == DONE)
                {
                    HandleGameObject(GetGuidData(DATA_GOLEM_DOOR_N), true);
                    HandleGameObject(GetGuidData(DATA_GOLEM_DOOR_S), true);
                    if (Creature* magmus = instance->GetCreature(MagmusGUID))
                        magmus->AI()->Talk(0);
                    ReplaceMoiraIfSaved(); // Need to place the correct final boss, but we need her to be spawned first.
                }
                break;
            case TYPE_IRON_HALL:
                encounter[5] = data;
                switch (data)
                {
                case NOT_STARTED:
                case IN_PROGRESS:
                    for (int i = 0; i < 6; i++)
                        if (Creature* ironhand = instance->GetCreature(IronhandGUID[i]))
                            ironhand->AI()->SetData(0, data == IN_PROGRESS);
                    break;
                case DONE:
                    HandleGameObject(GetGuidData(DATA_THRONE_DOOR), true);
                    break;
                default:
                    break;
                }
                break;
            case DATA_OPEN_COFFER_DOORS:
                OpenedCoofers += 1;
                if (OpenedCoofers == 12)
                {
                    Position pos = {812.15f, -348.91f, -50.579f, 0.7f};
                    if (TempSummon* summon = instance->SummonCreature(NPC_WATCHMAN_DOOMGRIP, pos))
                        summon->SetTempSummonType(TEMPSUMMON_MANUAL_DESPAWN);
                }
                break;
            case DATA_GOLEM_LORD_ARGELMACH_INIT:
            {
                if (Creature* argelmach = instance->GetCreature(ArgelmachGUID))
                {
                    GuidList adds = ArgelmachAdds;
                    for (GuidList::const_iterator itr = adds.begin(); itr != adds.end();)
                    {
                        if (Creature* argelmachAdd = instance->GetCreature(*itr))
{
                            if (argelmachAdd->GetEntry() == NPC_WRATH_HAMMER_CONSTRUCT)
{
                                argelmachAdd->RemoveAurasDueToSpell(SPELL_STONED);
                                argelmachAdd->AI()->AttackStart(argelmach->GetVictim());
                                itr = adds.erase(itr);
                            }
                            else if (argelmachAdd->GetEntry() == NPC_RAGEREAVER_GOLEM)
{
                                if (argelmachAdd->IsWithinDist2d(argelmach, 10.f))
{
                                    argelmachAdd->RemoveAurasDueToSpell(SPELL_STONED);
                                    argelmachAdd->AI()->AttackStart(argelmach->GetVictim());
                                    itr = adds.erase(itr);
                                }
                                else
                                    ++itr;
                            }
                            else
{
                                ++itr;
                            }
                        }
                        else
{
                            ++itr;
                        }
                    }
                    if (!adds.empty())
                    {
                        argelmach->SetReactState(REACT_PASSIVE);
                        argelmach->SetTarget();
                        argelmach->AI()->SetData(DATA_GOLEM_LORD_ARGELMACH_INIT, IN_PROGRESS);
                    }
                    else
                    {
                        argelmach->AI()->SetData(DATA_GOLEM_LORD_ARGELMACH_INIT, DONE);
                    }
                }
                break;
            }
            case DATA_GOLEM_LORD_ARGELMACH_ADDS:
            {
                if (Creature* argelmach = instance->GetCreature(ArgelmachGUID))
                {
                    argelmach->HandleEmoteCommand(EMOTE_ONESHOT_SHOUT);
                    argelmach->m_Events.AddEventAtOffset(new RestoreAttack(argelmach), 3s);
                    for (ObjectGuid const& argelmachAddGUID : ArgelmachAdds)
                        if (Creature* argelmachAdd = instance->GetCreature(argelmachAddGUID))
                            if (!argelmachAdd->IsInCombat())
{
                                argelmachAdd->RemoveAurasDueToSpell(SPELL_STONED);
                                argelmachAdd->AI()->AttackStart(argelmach->GetVictim());
                            }
                }
                break;
            }
            default:
                break;
        }
        if (data == DONE || GhostKillCount >= 7)
        {
            OUT_SAVE_INST_DATA;
            std::ostringstream saveStream;
            saveStream << encounter[0] << ' ' << encounter[1] << ' ' << encounter[2] << ' '
                       << encounter[3] << ' ' << encounter[4] << ' ' << encounter[5] << ' ' << GhostKillCount;
            str_data = saveStream.str();
            SaveToDB();
            OUT_SAVE_INST_DATA_COMPLETE;
        }
    }
References ArenaSpectators, ArgelmachAdds, ArgelmachGUID, BarAleCount, DATA_GOLEM_DOOR_N, DATA_GOLEM_DOOR_S, DATA_GOLEM_LORD_ARGELMACH_ADDS, DATA_GOLEM_LORD_ARGELMACH_INIT, DATA_OPEN_COFFER_DOORS, DATA_THRONE_DOOR, DAY, DONE, InstanceScript::DoRespawnGameObject(), EMOTE_ONESHOT_SHOUT, encounter, FACTION_NEUTRAL, FAIL, Map::GetCreature(), GameTime::GetGameTime(), GetGuidData(), GhostKillCount, GoChestGUID, GoTombEnterGUID, GoTombExitGUID, GrimstonePositon, InstanceScript::HandleGameObject(), IN_PROGRESS, InstanceScript::instance, IronhandGUID, LOG_DEBUG, MagmusGUID, NOT_STARTED, NPC_GRIMSTONE, NPC_RAGEREAVER_GOLEM, NPC_WATCHMAN_DOOMGRIP, NPC_WRATH_HAMMER_CONSTRUCT, OpenedCoofers, OUT_SAVE_INST_DATA, OUT_SAVE_INST_DATA_COMPLETE, REACT_DEFENSIVE, REACT_PASSIVE, TempSummon::RemoveFromWorld(), ReplaceMoiraIfSaved(), InstanceScript::SaveToDB(), SetData(), SPECIAL, SPELL_STONED, str_data, Map::SummonCreature(), TEMPSUMMON_MANUAL_DESPAWN, TempSummonGrimstone, timeRingFail, TYPE_BAR, TYPE_IRON_HALL, TYPE_LYCEUM, TYPE_RING_OF_LAW, TYPE_TOMB_OF_SEVEN, and TYPE_VAULT.
Referenced by OnUnitDeath(), SetData(), and TombOfSevenReset().
TombOfSevenEvent()
void instance_blackrock_depths::TombOfSevenEvent () inline
    {
        if (GhostKillCount < 7 && TombBossGUIDs[TombEventCounter])
        {
            if (Creature* boss = instance->GetCreature(TombBossGUIDs[TombEventCounter]))
            {
                ++TombEventCounter;
                boss->SetFaction(FACTION_DARK_IRON_DWARVES);
                boss->SetImmuneToPC(false);
                // find suitable target here.
                Player* target = boss->SelectNearestPlayer(130);
                if (target && boss->CanCreatureAttack(target, true))
                {
                    boss->AI()->AttackStart(target);
                    boss->AI()->DoZoneInCombat();
                    tombResetTimer = TIMER_TOMB_RESET;
                }
            }
        }
    }
References FACTION_DARK_IRON_DWARVES, Map::GetCreature(), GhostKillCount, InstanceScript::instance, WorldObject::SelectNearestPlayer(), TIMER_TOMB_RESET, TombBossGUIDs, TombEventCounter, and tombResetTimer.
Referenced by Update().
TombOfSevenReset()
void instance_blackrock_depths::TombOfSevenReset () inline
    {
        HandleGameObject(GoTombExitGUID, false);// close exit door
        HandleGameObject(GoTombEnterGUID, true);// open entrance door
        for (uint8 i = 0; i < 7; ++i)
            if (Creature* boss = instance->GetCreature(TombBossGUIDs[i]))
            {
                if (!boss->IsAlive())
                {
                    //do not call EnterEvadeMode(), it will create infinit loops
                    boss->Respawn();
                    boss->RemoveAllAuras();
                    boss->GetThreatMgr().ClearAllThreat();
                    boss->CombatStop(true);
                    boss->LoadCreaturesAddon(true);
                    boss->GetMotionMaster()->MoveTargetedHome();
                    boss->SetLootRecipient(nullptr);
                }
                boss->SetFaction(FACTION_FRIENDLY);
                boss->SetImmuneToPC(true); // think this is useless
                if (i == 6) // doomrel needs explicit reset
                    boss->AI()->Reset();
            }
        GhostKillCount = 0;
        TombEventCounter = 0;
        TombTimer = TIMER_TOMB_START;
        SetData(TYPE_TOMB_OF_SEVEN, NOT_STARTED);
    }
References FACTION_FRIENDLY, Map::GetCreature(), GhostKillCount, GoTombEnterGUID, GoTombExitGUID, InstanceScript::HandleGameObject(), InstanceScript::instance, NOT_STARTED, SetData(), TIMER_TOMB_START, TombBossGUIDs, TombEventCounter, TombTimer, and TYPE_TOMB_OF_SEVEN.
Referenced by Update().
Update()
void instance_blackrock_depths::Update (uint32 diff) inline override virtual
Reimplemented from InstanceScript.
    {
        if ((GetData(TYPE_TOMB_OF_SEVEN) == IN_PROGRESS) && GhostKillCount < 7)
        {
            if (TombTimer <= diff)
            {
                TombTimer = TIMER_TOMBOFTHESEVEN;
                TombOfSevenEvent();
            }
            else
            {
                TombTimer -= diff;
            }
            if (CheckTombReset(diff))
                TombOfSevenReset();
        }
    }
References CheckTombReset(), GetData(), GhostKillCount, IN_PROGRESS, TIMER_TOMBOFTHESEVEN, TombOfSevenEvent(), TombOfSevenReset(), TombTimer, and TYPE_TOMB_OF_SEVEN.
Member Data Documentation
arenaBossToSpawn
uint8 instance_blackrock_depths::arenaBossToSpawn
Referenced by GetData(), and Initialize().
arenaMobsToSpawn
uint8 instance_blackrock_depths::arenaMobsToSpawn
Referenced by GetData(), and Initialize().
ArenaSpectators
std::vector<ObjectGuid> instance_blackrock_depths::ArenaSpectators
Referenced by Initialize(), OnCreatureCreate(), and SetData().
ArgelmachAdds
GuidList instance_blackrock_depths::ArgelmachAdds
Referenced by OnCreatureCreate(), OnUnitDeath(), and SetData().
ArgelmachGUID
ObjectGuid instance_blackrock_depths::ArgelmachGUID
Referenced by OnCreatureCreate(), and SetData().
BarAleCount
uint32 instance_blackrock_depths::BarAleCount
Referenced by GetData(), Initialize(), and SetData().
CenterOfRingOfLaw
Position instance_blackrock_depths::CenterOfRingOfLaw = Position(595.289, -186.56)
Referenced by OnCreatureCreate().
CorenGUID
ObjectGuid instance_blackrock_depths::CorenGUID
Referenced by GetGuidData(), and OnCreatureCreate().
EmperorGUID
ObjectGuid instance_blackrock_depths::EmperorGUID
Referenced by GetGuidData(), OnCreatureCreate(), and OnUnitDeath().
EmperorSenators
ObjectGuid instance_blackrock_depths::EmperorSenators[5]
EmperorSenatorsVector
std::vector<ObjectGuid> instance_blackrock_depths::EmperorSenatorsVector
Referenced by OnCreatureCreate(), and OnUnitDeath().
EmperorSpawnPos
Position instance_blackrock_depths::EmperorSpawnPos = Position(1380.52, -831, 115)
Referenced by OnCreatureCreate().
encounter
uint32 instance_blackrock_depths::encounter[MAX_ENCOUNTER]
Referenced by GetData(), Initialize(), Load(), OnCreatureCreate(), and SetData().
GhostKillCount
uint32 instance_blackrock_depths::GhostKillCount
Referenced by Initialize(), Load(), OnGameObjectCreate(), OnUnitDeath(), SetData(), TombOfSevenEvent(), TombOfSevenReset(), and Update().
GoArena1GUID
ObjectGuid instance_blackrock_depths::GoArena1GUID
Referenced by GetGuidData(), and OnGameObjectCreate().
GoArena2GUID
ObjectGuid instance_blackrock_depths::GoArena2GUID
Referenced by GetGuidData(), and OnGameObjectCreate().
GoArena3GUID
ObjectGuid instance_blackrock_depths::GoArena3GUID
Referenced by GetGuidData(), and OnGameObjectCreate().
GoArena4GUID
ObjectGuid instance_blackrock_depths::GoArena4GUID
Referenced by GetGuidData(), and OnGameObjectCreate().
GoBarDoorGUID
ObjectGuid instance_blackrock_depths::GoBarDoorGUID
Referenced by GetGuidData(), and OnGameObjectCreate().
GoBarKegGUID
ObjectGuid instance_blackrock_depths::GoBarKegGUID
Referenced by GetGuidData(), and OnGameObjectCreate().
GoBarKegTrapGUID
ObjectGuid instance_blackrock_depths::GoBarKegTrapGUID
Referenced by GetGuidData(), and OnGameObjectCreate().
GoChestGUID
ObjectGuid instance_blackrock_depths::GoChestGUID
Referenced by OnGameObjectCreate(), and SetData().
GoGolemNGUID
ObjectGuid instance_blackrock_depths::GoGolemNGUID
Referenced by GetGuidData(), and OnGameObjectCreate().
GoGolemSGUID
ObjectGuid instance_blackrock_depths::GoGolemSGUID
Referenced by GetGuidData(), and OnGameObjectCreate().
GoLyceumGUID
ObjectGuid instance_blackrock_depths::GoLyceumGUID
Referenced by OnGameObjectCreate().
GoSFNGUID
ObjectGuid instance_blackrock_depths::GoSFNGUID
Referenced by GetGuidData(), and OnGameObjectCreate().
GoSFSGUID
ObjectGuid instance_blackrock_depths::GoSFSGUID
Referenced by GetGuidData(), and OnGameObjectCreate().
GoShadowDummyGUID
ObjectGuid instance_blackrock_depths::GoShadowDummyGUID
Referenced by OnGameObjectCreate().
GoShadowGiantGUID
ObjectGuid instance_blackrock_depths::GoShadowGiantGUID
Referenced by OnGameObjectCreate().
GoShadowLockGUID
ObjectGuid instance_blackrock_depths::GoShadowLockGUID
Referenced by OnGameObjectCreate().
GoShadowMechGUID
ObjectGuid instance_blackrock_depths::GoShadowMechGUID
Referenced by OnGameObjectCreate().
GoSpectralChaliceGUID
ObjectGuid instance_blackrock_depths::GoSpectralChaliceGUID
Referenced by GetGuidData(), and OnGameObjectCreate().
GoThroneGUID
ObjectGuid instance_blackrock_depths::GoThroneGUID
Referenced by GetGuidData(), OnCreatureCreate(), and OnGameObjectCreate().
GoTombEnterGUID
ObjectGuid instance_blackrock_depths::GoTombEnterGUID
Referenced by OnGameObjectCreate(), SetData(), and TombOfSevenReset().
GoTombExitGUID
ObjectGuid instance_blackrock_depths::GoTombExitGUID
Referenced by OnGameObjectCreate(), SetData(), and TombOfSevenReset().
GrimstonePositon
Position instance_blackrock_depths::GrimstonePositon = Position(625.559f, -205.618f, -52.735f, 2.609f)
Referenced by SetData().
IronhandCounter
uint32 instance_blackrock_depths::IronhandCounter
Referenced by Initialize(), and OnCreatureCreate().
IronhandGUID
ObjectGuid instance_blackrock_depths::IronhandGUID[6]
Referenced by OnCreatureCreate(), and SetData().
MagmusGUID
ObjectGuid instance_blackrock_depths::MagmusGUID
Referenced by GetGuidData(), OnCreatureCreate(), and SetData().
MoiraGUID
ObjectGuid instance_blackrock_depths::MoiraGUID
Referenced by GetGuidData(), OnCreatureCreate(), and ReplaceMoiraIfSaved().
OpenedCoofers
uint32 instance_blackrock_depths::OpenedCoofers
Referenced by Initialize(), and SetData().
PhalanxGUID
ObjectGuid instance_blackrock_depths::PhalanxGUID
Referenced by GetGuidData(), and OnCreatureCreate().
PriestessGUID
ObjectGuid instance_blackrock_depths::PriestessGUID
Referenced by ReplaceMoiraIfSaved().
str_data
std::string instance_blackrock_depths::str_data
Referenced by GetSaveData(), and SetData().
TempSummonGrimstone
TempSummon* instance_blackrock_depths::TempSummonGrimstone = nullptr
Referenced by SetData().
timeRingFail
time_t instance_blackrock_depths::timeRingFail = 0
Referenced by GetData(), and SetData().
TombBossGUIDs
ObjectGuid instance_blackrock_depths::TombBossGUIDs[7]
Referenced by CheckTombReset(), OnCreatureCreate(), TombOfSevenEvent(), and TombOfSevenReset().
TombEventCounter
uint32 instance_blackrock_depths::TombEventCounter
Referenced by CheckTombReset(), Initialize(), TombOfSevenEvent(), and TombOfSevenReset().
tombResetTimer
uint32 instance_blackrock_depths::tombResetTimer
Referenced by CheckTombReset(), Initialize(), and TombOfSevenEvent().
TombTimer
uint32 instance_blackrock_depths::TombTimer
Referenced by Initialize(), TombOfSevenReset(), and Update().
The documentation for this struct was generated from the following file:
azerothcore-wotlk/src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockDepths/instance_blackrock_depths.cpp