AzerothCore Doxygen
LuaRoll Namespace Reference
Functions
int GetItemGUID (lua_State *L, Roll *roll)
int GetItemId (lua_State *L, Roll *roll)
int GetItemRandomPropId (lua_State *L, Roll *roll)
int GetItemRandomSuffix (lua_State *L, Roll *roll)
int GetItemCount (lua_State *L, Roll *roll)
int GetPlayerVote (lua_State *L, Roll *roll)
int GetPlayerVoteGUIDs (lua_State *L, Roll *roll)
int GetTotalPlayersRolling (lua_State *L, Roll *roll)
int GetTotalNeed (lua_State *L, Roll *roll)
int GetTotalGreed (lua_State *L, Roll *roll)
int GetTotalPass (lua_State *L, Roll *roll)
int GetItemSlot (lua_State *L, Roll *roll)
int GetRollVoteMask (lua_State *L, Roll *roll)
Function Documentation
GetItemCount()
int LuaRoll::GetItemCount (lua_State * L, Roll * roll)
Returns the rolled [Item]'s count.
Returns
uint8 count
    {
        Eluna::Push(L, roll->itemCount);
        return 1;
    }
References Roll::itemCount, and Eluna::Push().
GetItemGUID()
int LuaRoll::GetItemGUID (lua_State * L, Roll * roll)
Returns the rolled [Item]'s GUID.
Returns
ObjectGuid guid
    {
        Eluna::Push(L, roll->itemGUID.GetCounter());
        return 1;
    }
References ObjectGuid::GetCounter(), Roll::itemGUID, and Eluna::Push().
GetItemId()
int LuaRoll::GetItemId (lua_State * L, Roll * roll)
Returns the rolled [Item]'s entry.
Returns
uint32 entry
    {
        Eluna::Push(L, roll->itemid);
        return 1;
    }
References Roll::itemid, and Eluna::Push().
GetItemRandomPropId()
int LuaRoll::GetItemRandomPropId (lua_State * L, Roll * roll)
Returns the rolled [Item]'s random property ID.
Returns
int32 randomPropId
    {
        Eluna::Push(L, roll->itemRandomPropId);
        return 1;
    }
References Roll::itemRandomPropId, and Eluna::Push().
GetItemRandomSuffix()
int LuaRoll::GetItemRandomSuffix (lua_State * L, Roll * roll)
Returns the rolled [Item]'s random suffix ID.
Returns
uint32 randomSuffix
    {
        Eluna::Push(L, roll->itemRandomSuffix);
        return 1;
    }
References Roll::itemRandomSuffix, and Eluna::Push().
GetItemSlot()
int LuaRoll::GetItemSlot (lua_State * L, Roll * roll)
Returns the rolled [Item]'s slot in the loot window.
Returns
uint8 slot
    {
        Eluna::Push(L, roll->itemSlot);
        return 1;
    }
References Roll::itemSlot, and Eluna::Push().
GetPlayerVote()
int LuaRoll::GetPlayerVote (lua_State * L, Roll * roll)
Returns the vote type for a [Player] on this [Roll]. See [Roll:GetPlayerVoteGUIDs] to obtain the GUIDs of the [Player]s who rolled.
enum RollVote
{
    PASS              = 0,
    NEED              = 1,
    GREED             = 2,
    DISENCHANT        = 3,
    NOT_EMITED_YET    = 4,
    NOT_VALID         = 5
};
Parameters
ObjectGuid guid
Returns
[RollVote] vote
    {
        ObjectGuid guid = Eluna::CHECKVAL<ObjectGuid>(L, 2);
        bool found = false;
        for (std::pair<const ObjectGuid, RollVote>& pair : roll->playerVote)
        {
            if (pair.first == guid)
            {
                Eluna::Push(L, pair.second);
                found = true;
            }
        }
        if (!found)
        {
            Eluna::Push(L);
        }
        return 1;
    }
References Roll::playerVote, and Eluna::Push().
GetPlayerVoteGUIDs()
int LuaRoll::GetPlayerVoteGUIDs (lua_State * L, Roll * roll)
Returns the GUIDs of the [Player]s who rolled. See [Roll:GetPlayerVote] to obtain the vote type of a [Player].
Returns
table guids
    {
        lua_newtable(L);
        int table = lua_gettop(L);
        uint32 i = 1;
        for (std::pair<const ObjectGuid, RollVote>& pair : roll->playerVote)
        {
            Eluna::Push(L, pair.first);
            lua_rawseti(L, table, i);
            ++i;
        }
        lua_settop(L, table); // push table to top of stack
        return 1;
    }
References lua_gettop(), lua_newtable, lua_rawseti(), lua_settop(), Roll::playerVote, and Eluna::Push().
GetRollVoteMask()
int LuaRoll::GetRollVoteMask (lua_State * L, Roll * roll)
Returns the mask applied to this [Roll].
enum RollMask
{
    ROLL_FLAG_TYPE_PASS                 = 0x01,
    ROLL_FLAG_TYPE_NEED                 = 0x02,
    ROLL_FLAG_TYPE_GREED                = 0x04,
    ROLL_FLAG_TYPE_DISENCHANT           = 0x08,
    ROLL_ALL_TYPE_NO_DISENCHANT         = 0x07,
    ROLL_ALL_TYPE_MASK                  = 0x0F
};
Returns
[RollMask] rollMask
    {
        Eluna::Push(L, roll->rollVoteMask);
        return 1;
    }
References Eluna::Push(), and Roll::rollVoteMask.
GetTotalGreed()
int LuaRoll::GetTotalGreed (lua_State * L, Roll * roll)
Returns the total number of players who rolled greed.
Returns
uint8 playersCount
    {
        Eluna::Push(L, roll->totalGreed);
        return 1;
    }
References Eluna::Push(), and Roll::totalGreed.
GetTotalNeed()
int LuaRoll::GetTotalNeed (lua_State * L, Roll * roll)
Returns the total number of players who rolled need.
Returns
uint8 playersCount
    {
        Eluna::Push(L, roll->totalNeed);
        return 1;
    }
References Eluna::Push(), and Roll::totalNeed.
GetTotalPass()
int LuaRoll::GetTotalPass (lua_State * L, Roll * roll)
Returns the total number of players who passed.
Returns
uint8 playersCount
    {
        Eluna::Push(L, roll->totalPass);
        return 1;
    }
References Eluna::Push(), and Roll::totalPass.
GetTotalPlayersRolling()
int LuaRoll::GetTotalPlayersRolling (lua_State * L, Roll * roll)
Returns the total number of players who rolled.
Returns
uint8 playersCount
    {
        Eluna::Push(L, roll->totalPlayersRolling);
        return 1;
    }
References Eluna::Push(), and Roll::totalPlayersRolling.