AzerothCore Doxygen
TypeVectorContainer< OBJECT_TYPES > Class Template Reference
#include "TypeContainer.h"
Public Member Functions
template<class SPECIFIC_TYPE >
std::size_t Count () const
template<class SPECIFIC_TYPE >
bool Insert (SPECIFIC_TYPE *obj)
template<class SPECIFIC_TYPE >
bool Remove (SPECIFIC_TYPE *obj)
ContainerVector< OBJECT_TYPES > & GetElements ()
const ContainerVector< OBJECT_TYPES > & GetElements () const
Private Attributes
ContainerVector< OBJECT_TYPES > i_elements
Detailed Description
template<class OBJECT_TYPES>
class TypeVectorContainer< OBJECT_TYPES >
Member Function Documentation
Count()
template<class OBJECT_TYPES > template<class SPECIFIC_TYPE > std::size_t TypeVectorContainer< OBJECT_TYPES >::Count () const inline
{ return Acore::Count(i_elements, (SPECIFIC_TYPE*)nullptr); }
References Acore::Count(), and TypeVectorContainer< OBJECT_TYPES >::i_elements.
GetElements() [1/2]
template<class OBJECT_TYPES > ContainerVector< OBJECT_TYPES > & TypeVectorContainer< OBJECT_TYPES >::GetElements () inline
{ return i_elements; }
References TypeVectorContainer< OBJECT_TYPES >::i_elements.
Referenced by VisitorHelper().
GetElements() [2/2]
template<class OBJECT_TYPES > const ContainerVector< OBJECT_TYPES > & TypeVectorContainer< OBJECT_TYPES >::GetElements () const inline
{ return i_elements; }
References TypeVectorContainer< OBJECT_TYPES >::i_elements.
Insert()
template<class OBJECT_TYPES > template<class SPECIFIC_TYPE > bool TypeVectorContainer< OBJECT_TYPES >::Insert (SPECIFIC_TYPE * obj) inline
    {
        SPECIFIC_TYPE* t = Acore::Insert(i_elements, obj);
        return (t != nullptr);
    }
References TypeVectorContainer< OBJECT_TYPES >::i_elements, and Acore::Insert().
Remove()
template<class OBJECT_TYPES > template<class SPECIFIC_TYPE > bool TypeVectorContainer< OBJECT_TYPES >::Remove (SPECIFIC_TYPE * obj) inline
    {
        SPECIFIC_TYPE* t = Acore::Remove(i_elements, obj);
        return (t != nullptr);
    }
References TypeVectorContainer< OBJECT_TYPES >::i_elements, and Acore::Remove().
Member Data Documentation
i_elements
template<class OBJECT_TYPES > ContainerVector<OBJECT_TYPES> TypeVectorContainer< OBJECT_TYPES >::i_elements private
Referenced by TypeVectorContainer< OBJECT_TYPES >::Count(), TypeVectorContainer< OBJECT_TYPES >::GetElements(), TypeVectorContainer< OBJECT_TYPES >::GetElements(), TypeVectorContainer< OBJECT_TYPES >::Insert(), and TypeVectorContainer< OBJECT_TYPES >::Remove().
The documentation for this class was generated from the following file:
azerothcore-wotlk/src/common/Dynamic/TypeContainer.h