AzerothCore Doxygen
boss_icecrown_gunship_battle.cpp File Reference
#include "AchievementCriteriaScript.h"
#include "AreaDefines.h"
#include "Config.h"
#include "CreatureScript.h"
#include "CreatureTextMgr.h"
#include "GameTime.h"
#include "MoveSpline.h"
#include "MoveSplineInit.h"
#include "SpellScript.h"
#include "SpellScriptLoader.h"
#include "Transport.h"
#include "TransportMgr.h"
#include "Vehicle.h"
#include "icecrown_citadel.h"
#include "PassiveAI.h"
#include "SpellAuraEffects.h"
Classes
struct SlotInfo
class BattleExperienceEvent
class PassengerController
class DelayedMovementEvent
class ResetEncounterEvent
class npc_gunship
struct npc_gunship::npc_gunshipAI
class npc_high_overlord_saurfang_igb
struct npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI
class npc_muradin_bronzebeard_igb
struct npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI
class npc_zafod_boombox
struct npc_zafod_boombox::npc_zafod_boomboxAI
class npc_igb_ship_crew
struct npc_igb_ship_crew::npc_igb_ship_crewAI
struct gunship_npc_AI
struct npc_gunship_boarding_addAI
class npc_gunship_boarding_leader
struct npc_gunship_boarding_leader::npc_gunship_boarding_leaderAI
class npc_gunship_boarding_add
struct npc_gunship_boarding_add::npc_gunship_boarding_add_realAI
class npc_gunship_mage
struct npc_gunship_mage::npc_gunship_mageAI
class npc_gunship_gunner
struct npc_gunship_gunner::npc_gunship_gunnerAI
class npc_gunship_rocketeer
struct npc_gunship_rocketeer::npc_gunship_rocketeerAI
class spell_igb_rocket_pack_aura
class spell_igb_rocket_pack_useable_aura
class spell_igb_teleport_to_enemy_ship
class spell_igb_check_for_players
class spell_igb_gunship_fall_teleport
class spell_igb_explosion_main_aura
class IgbExplosionCheck
class spell_igb_explosion
class IgbTeleportOnVictoryCheck
class spell_igb_teleport_players_on_victory
class spell_igb_periodic_trigger_with_power_cost_aura
class spell_igb_overheat_aura
class spell_igb_cannon_blast
class spell_igb_incinerating_blast
class BurningPitchFilterCheck
class spell_igb_burning_pitch_selector
class spell_igb_burning_pitch
class IgbArtilleryCheck
class spell_igb_rocket_artillery
class spell_igb_rocket_artillery_explosion
class spell_igb_below_zero
class spell_igb_on_gunship_deck_aura
class achievement_im_on_a_boat
class spell_igb_battle_experience_check
Macros
#define EVENT_CHARGE_PREPATH 13371337
Enumerations
enum Texts {
SAY_SAURFANG_INTRO_1 = 0 ,
SAY_SAURFANG_INTRO_2 = 1 ,
SAY_SAURFANG_INTRO_3 = 2 ,
SAY_SAURFANG_INTRO_4 = 3 ,
SAY_SAURFANG_INTRO_5 = 4 ,
SAY_SAURFANG_INTRO_6 = 5 ,
SAY_SAURFANG_INTRO_A = 6 ,
SAY_SAURFANG_BOARD = 7 ,
SAY_SAURFANG_ENTER_SKYBREAKER = 8 ,
SAY_SAURFANG_AXETHROWERS = 9 ,
SAY_SAURFANG_ROCKETEERS = 10 ,
SAY_SAURFANG_MAGES = 11 ,
SAY_SAURFANG_VICTORY = 12 ,
SAY_SAURFANG_WIPE = 13 ,
SAY_MURADIN_INTRO_1 = 0 ,
SAY_MURADIN_INTRO_2 = 1 ,
SAY_MURADIN_INTRO_3 = 2 ,
SAY_MURADIN_INTRO_4 = 3 ,
SAY_MURADIN_INTRO_5 = 4 ,
SAY_MURADIN_INTRO_6 = 5 ,
SAY_MURADIN_INTRO_7 = 6 ,
SAY_MURADIN_INTRO_H = 7 ,
SAY_MURADIN_BOARD = 8 ,
SAY_MURADIN_ENTER_ORGRIMMS_HAMMER = 9 ,
SAY_MURADIN_RIFLEMAN = 10 ,
SAY_MURADIN_MORTAR = 11 ,
SAY_MURADIN_SORCERERS = 12 ,
SAY_MURADIN_VICTORY = 13 ,
SAY_MURADIN_WIPE = 14 ,
SAY_ZAFOD_ROCKET_PACK_ACTIVE = 0 ,
SAY_ZAFOD_ROCKET_PACK_DISABLED = 1 ,
SAY_OVERHEAT = 0
}
enum Events {
EVENT_INTRO_H_1 = 1 ,
EVENT_INTRO_H_2 = 2 ,
EVENT_INTRO_SUMMON_SKYBREAKER = 3 ,
EVENT_INTRO_H_3 = 4 ,
EVENT_INTRO_H_4 = 5 ,
EVENT_INTRO_H_5 = 6 ,
EVENT_INTRO_H_6 = 7 ,
EVENT_INTRO_A_1 = 1 ,
EVENT_INTRO_A_2 = 2 ,
EVENT_INTRO_SUMMON_ORGRIMS_HAMMER = 3 ,
EVENT_INTRO_A_3 = 4 ,
EVENT_INTRO_A_4 = 5 ,
EVENT_INTRO_A_5 = 6 ,
EVENT_INTRO_A_6 = 7 ,
EVENT_INTRO_A_7 = 8 ,
EVENT_KEEP_PLAYER_IN_COMBAT = 9 ,
EVENT_SUMMON_MAGE = 10 ,
EVENT_ADDS = 11 ,
EVENT_ADDS_BOARD_YELL = 12 ,
EVENT_CHECK_RIFLEMAN = 13 ,
EVENT_CHECK_MORTAR = 14 ,
EVENT_CLEAVE = 15 ,
EVENT_BLADESTORM = 16 ,
EVENT_WOUNDING_STRIKE = 17
}
enum Spells {
SPELL_FRIENDLY_BOSS_DAMAGE_MOD = 70339 ,
SPELL_CHECK_FOR_PLAYERS = 70332 ,
SPELL_GUNSHIP_FALL_TELEPORT = 67335 ,
SPELL_TELEPORT_PLAYERS_ON_RESET_A = 70446 ,
SPELL_TELEPORT_PLAYERS_ON_RESET_H = 71284 ,
SPELL_TELEPORT_PLAYERS_ON_VICTORY = 72340 ,
SPELL_ACHIEVEMENT = 72959 ,
SPELL_AWARD_REPUTATION_BOSS_KILL = 73843 ,
SPELL_EXPLOSION_WIPE = 72134 ,
SPELL_EXPLOSION_VICTORY = 72137 ,
SPELL_BURNING_PITCH_A = 70403 ,
SPELL_BURNING_PITCH_H = 70397 ,
SPELL_BURNING_PITCH = 69660 ,
SPELL_BURNING_PITCH_DAMAGE_A = 70383 ,
SPELL_BURNING_PITCH_DAMAGE_H = 70374 ,
SPELL_CLEAVE = 15284 ,
SPELL_BATTLE_FURY = 69637 ,
SPELL_SHADOW_CHANNELING = 43897 ,
SPELL_SHOOT = 70162 ,
SPELL_HURL_AXE = 70161 ,
SPELL_BELOW_ZERO = 69705 ,
SPELL_ROCKET_ARTILLERY_A = 70609 ,
SPELL_ROCKET_ARTILLERY_H = 69678 ,
SPELL_RENDING_THROW = 70309 ,
SPELL_TASTE_OF_BLOOD = 69634 ,
SPELL_TELEPORT_TO_ENEMY_SHIP = 70104 ,
SPELL_BATTLE_EXPERIENCE = 71201 ,
SPELL_EXPERIENCED = 71188 ,
SPELL_VETERAN = 71193 ,
SPELL_ELITE = 71195 ,
SPELL_ADDS_BERSERK = 72525 ,
SPELL_BLADESTORM = 69652 ,
SPELL_WOUNDING_STRIKE = 69651 ,
SPELL_DESPERATE_RESOLVE = 69647 ,
SPELL_LOCK_PLAYERS_AND_TAP_CHEST = 72347 ,
SPELL_ON_SKYBREAKER_DECK = 70120 ,
SPELL_ON_ORGRIMS_HAMMER_DECK = 70121 ,
SPELL_CREATE_ROCKET_PACK = 70055 ,
SPELL_ROCKET_PACK_DAMAGE = 69193 ,
SPELL_ROCKET_BURST = 69192 ,
SPELL_ROCKET_PACK_USEABLE = 70348 ,
SPELL_OVERHEAT = 69487 ,
SPELL_EJECT_ALL_PASSENGERS = 68576
}
enum MiscData { MUSIC_ENCOUNTER = 17289 }
enum EncounterActions {
ACTION_SPAWN_MAGE = 1 ,
ACTION_SPAWN_ALL_ADDS = 2 ,
ACTION_CLEAR_SLOT = 3 ,
ACTION_SET_SLOT = 4 ,
ACTION_SHIP_VISITS_SELF = 5 ,
ACTION_SHIP_VISITS_ENEMY = 6 ,
ACTION_SHIP_VISITS_SELF_2 = 7 ,
ACTION_SHIP_VISITS_ENEMY_2 = 8
}
enum PassengerSlots {
SLOT_FREEZE_MAGE = 0 ,
SLOT_MAGE_1 = 1 ,
SLOT_MAGE_2 = 2 ,
SLOT_RIFLEMAN_1 = 3 ,
SLOT_RIFLEMAN_2 = 4 ,
SLOT_RIFLEMAN_3 = 5 ,
SLOT_RIFLEMAN_4 = 6 ,
SLOT_RIFLEMAN_5 = 7 ,
SLOT_RIFLEMAN_6 = 8 ,
SLOT_RIFLEMAN_7 = 9 ,
SLOT_RIFLEMAN_8 = 10 ,
SLOT_MORTAR_1 = 11 ,
SLOT_MORTAR_2 = 12 ,
SLOT_MORTAR_3 = 13 ,
SLOT_MORTAR_4 = 14 ,
SLOT_MARINE_1 = 15 ,
SLOT_MARINE_2 = 16 ,
SLOT_MARINE_3 = 17 ,
SLOT_MARINE_4 = 18 ,
SLOT_SERGEANT_1 = 19 ,
SLOT_SERGEANT_2 = 20 ,
MAX_SLOTS
}
Functions
void TriggerBurningPitch (Creature *c)
void AddSC_boss_icecrown_gunship_battle ()
Variables
Position const SkybreakerAddsSpawnPos = { 15.91131f, 0.0f, 20.4628f, M_PI }
Position const OrgrimsHammerAddsSpawnPos = { 60.728395f, 0.0f, 38.93467f, M_PI }
Position const SkybreakerTeleportPortal = { 6.666975f, 0.013001f, 20.87888f, 0.0f }
Position const OrgrimsHammerTeleportExit = { 7.461699f, 0.158853f, 35.72989f, 0.0f }
Position const OrgrimsHammerTeleportPortal = { 47.550990f, -0.101778f, 37.61111f, 0.0f }
Position const SkybreakerTeleportExit = { -17.55738f, -0.090421f, 21.18366f, 0.0f }
uint32 const MuradinExitPathSize = 10
Position const MuradinExitPath [MuradinExitPathSize]
uint32 const SaurfangExitPathSize = 13
Position const SaurfangExitPath [SaurfangExitPathSize]
SlotInfo const SkybreakerSlotInfo [MAX_SLOTS]
SlotInfo const OrgrimsHammerSlotInfo [MAX_SLOTS]
Macro Definition Documentation
EVENT_CHARGE_PREPATH
#define EVENT_CHARGE_PREPATH 13371337
Enumeration Type Documentation
EncounterActions
enum EncounterActions
Enumerator
ACTION_SPAWN_MAGE
ACTION_SPAWN_ALL_ADDS
ACTION_CLEAR_SLOT
ACTION_SET_SLOT
ACTION_SHIP_VISITS_SELF
ACTION_SHIP_VISITS_ENEMY
ACTION_SHIP_VISITS_SELF_2
ACTION_SHIP_VISITS_ENEMY_2
{
    ACTION_SPAWN_MAGE           = 1,
    ACTION_SPAWN_ALL_ADDS       = 2,
    ACTION_CLEAR_SLOT           = 3,
    ACTION_SET_SLOT             = 4,
    ACTION_SHIP_VISITS_SELF     = 5,
    ACTION_SHIP_VISITS_ENEMY    = 6,
    ACTION_SHIP_VISITS_SELF_2   = 7,
    ACTION_SHIP_VISITS_ENEMY_2  = 8
};
Events
enum Events
Enumerator
EVENT_INTRO_H_1
EVENT_INTRO_H_2
EVENT_INTRO_SUMMON_SKYBREAKER
EVENT_INTRO_H_3
EVENT_INTRO_H_4
EVENT_INTRO_H_5
EVENT_INTRO_H_6
EVENT_INTRO_A_1
EVENT_INTRO_A_2
EVENT_INTRO_SUMMON_ORGRIMS_HAMMER
EVENT_INTRO_A_3
EVENT_INTRO_A_4
EVENT_INTRO_A_5
EVENT_INTRO_A_6
EVENT_INTRO_A_7
EVENT_KEEP_PLAYER_IN_COMBAT
EVENT_SUMMON_MAGE
EVENT_ADDS
EVENT_ADDS_BOARD_YELL
EVENT_CHECK_RIFLEMAN
EVENT_CHECK_MORTAR
EVENT_CLEAVE
EVENT_BLADESTORM
EVENT_WOUNDING_STRIKE
{
    // High Overlord Saurfang
    EVENT_INTRO_H_1                 = 1,
    EVENT_INTRO_H_2                 = 2,
    EVENT_INTRO_SUMMON_SKYBREAKER   = 3,
    EVENT_INTRO_H_3                 = 4,
    EVENT_INTRO_H_4                 = 5,
    EVENT_INTRO_H_5                 = 6,
    EVENT_INTRO_H_6                 = 7,
    // Muradin Bronzebeard
    EVENT_INTRO_A_1                 = 1,
    EVENT_INTRO_A_2                 = 2,
    EVENT_INTRO_SUMMON_ORGRIMS_HAMMER = 3,
    EVENT_INTRO_A_3                 = 4,
    EVENT_INTRO_A_4                 = 5,
    EVENT_INTRO_A_5                 = 6,
    EVENT_INTRO_A_6                 = 7,
    EVENT_INTRO_A_7                 = 8,
    EVENT_KEEP_PLAYER_IN_COMBAT     = 9,
    EVENT_SUMMON_MAGE               = 10,
    EVENT_ADDS                      = 11,
    EVENT_ADDS_BOARD_YELL           = 12,
    EVENT_CHECK_RIFLEMAN            = 13,
    EVENT_CHECK_MORTAR              = 14,
    EVENT_CLEAVE                    = 15,
    EVENT_BLADESTORM                = 16,
    EVENT_WOUNDING_STRIKE           = 17
};
MiscData
enum MiscData
Enumerator
MUSIC_ENCOUNTER
{
    MUSIC_ENCOUNTER         = 17289
};
PassengerSlots
enum PassengerSlots
Enumerator
SLOT_FREEZE_MAGE
SLOT_MAGE_1
SLOT_MAGE_2
SLOT_RIFLEMAN_1
SLOT_RIFLEMAN_2
SLOT_RIFLEMAN_3
SLOT_RIFLEMAN_4
SLOT_RIFLEMAN_5
SLOT_RIFLEMAN_6
SLOT_RIFLEMAN_7
SLOT_RIFLEMAN_8
SLOT_MORTAR_1
SLOT_MORTAR_2
SLOT_MORTAR_3
SLOT_MORTAR_4
SLOT_MARINE_1
SLOT_MARINE_2
SLOT_MARINE_3
SLOT_MARINE_4
SLOT_SERGEANT_1
SLOT_SERGEANT_2
MAX_SLOTS
{
    // Freezing the cannons
    SLOT_FREEZE_MAGE    = 0,
    // Channeling the portal, refilled with adds that board player's ship
    SLOT_MAGE_1         = 1,
    SLOT_MAGE_2         = 2,
    // Rifleman
    SLOT_RIFLEMAN_1     = 3,
    SLOT_RIFLEMAN_2     = 4,
    SLOT_RIFLEMAN_3     = 5,
    SLOT_RIFLEMAN_4     = 6,
    // Additional Rifleman on 25 man
    SLOT_RIFLEMAN_5     = 7,
    SLOT_RIFLEMAN_6     = 8,
    SLOT_RIFLEMAN_7     = 9,
    SLOT_RIFLEMAN_8     = 10,
    // Mortar
    SLOT_MORTAR_1       = 11,
    SLOT_MORTAR_2       = 12,
    // Additional spawns on 25 man
    SLOT_MORTAR_3       = 13,
    SLOT_MORTAR_4       = 14,
    // Marines
    SLOT_MARINE_1       = 15,
    SLOT_MARINE_2       = 16,
    // Additional spawns on 25 man
    SLOT_MARINE_3       = 17,
    SLOT_MARINE_4       = 18,
    // Sergeants
    SLOT_SERGEANT_1     = 19,
    // Additional spawns on 25 man
    SLOT_SERGEANT_2     = 20,
    MAX_SLOTS
};
Spells
enum Spells
Enumerator
SPELL_FRIENDLY_BOSS_DAMAGE_MOD
SPELL_CHECK_FOR_PLAYERS
SPELL_GUNSHIP_FALL_TELEPORT
SPELL_TELEPORT_PLAYERS_ON_RESET_A
SPELL_TELEPORT_PLAYERS_ON_RESET_H
SPELL_TELEPORT_PLAYERS_ON_VICTORY
SPELL_ACHIEVEMENT
SPELL_AWARD_REPUTATION_BOSS_KILL
SPELL_EXPLOSION_WIPE
SPELL_EXPLOSION_VICTORY
SPELL_BURNING_PITCH_A
SPELL_BURNING_PITCH_H
SPELL_BURNING_PITCH
SPELL_BURNING_PITCH_DAMAGE_A
SPELL_BURNING_PITCH_DAMAGE_H
SPELL_CLEAVE
SPELL_BATTLE_FURY
SPELL_SHADOW_CHANNELING
SPELL_SHOOT
SPELL_HURL_AXE
SPELL_BELOW_ZERO
SPELL_ROCKET_ARTILLERY_A
SPELL_ROCKET_ARTILLERY_H
SPELL_RENDING_THROW
SPELL_TASTE_OF_BLOOD
SPELL_TELEPORT_TO_ENEMY_SHIP
SPELL_BATTLE_EXPERIENCE
SPELL_EXPERIENCED
SPELL_VETERAN
SPELL_ELITE
SPELL_ADDS_BERSERK
SPELL_BLADESTORM
SPELL_WOUNDING_STRIKE
SPELL_DESPERATE_RESOLVE
SPELL_LOCK_PLAYERS_AND_TAP_CHEST
SPELL_ON_SKYBREAKER_DECK
SPELL_ON_ORGRIMS_HAMMER_DECK
SPELL_CREATE_ROCKET_PACK
SPELL_ROCKET_PACK_DAMAGE
SPELL_ROCKET_BURST
SPELL_ROCKET_PACK_USEABLE
SPELL_OVERHEAT
SPELL_EJECT_ALL_PASSENGERS
{
    // Applied on friendly transport NPCs
    SPELL_FRIENDLY_BOSS_DAMAGE_MOD          = 70339,
    SPELL_CHECK_FOR_PLAYERS                 = 70332,
    SPELL_GUNSHIP_FALL_TELEPORT             = 67335,
    SPELL_TELEPORT_PLAYERS_ON_RESET_A       = 70446,
    SPELL_TELEPORT_PLAYERS_ON_RESET_H       = 71284,
    SPELL_TELEPORT_PLAYERS_ON_VICTORY       = 72340,
    SPELL_ACHIEVEMENT                       = 72959,
    SPELL_AWARD_REPUTATION_BOSS_KILL        = 73843,
    // Gunship Hull
    SPELL_EXPLOSION_WIPE                    = 72134,
    SPELL_EXPLOSION_VICTORY                 = 72137,
    SPELL_BURNING_PITCH_A                   = 70403,
    SPELL_BURNING_PITCH_H                   = 70397,
    SPELL_BURNING_PITCH                     = 69660,
    SPELL_BURNING_PITCH_DAMAGE_A            = 70383,
    SPELL_BURNING_PITCH_DAMAGE_H            = 70374,
    // Murading Bronzebeard
    // High Overlord Saurfang
    SPELL_CLEAVE                            = 15284,
    SPELL_BATTLE_FURY                       = 69637,
    // Skybreaker Sorcerer
    // Kor'kron Battle-Mage
    SPELL_SHADOW_CHANNELING                 = 43897,
    // Skybreaker Rifleman
    // Kor'kron Axethrower
    SPELL_SHOOT                             = 70162,
    SPELL_HURL_AXE                          = 70161,
    // Skybreaker Sorcerer
    // Kor'kron Battle-Mage
    SPELL_BELOW_ZERO                        = 69705,
    // Skybreaker Mortar Soldier
    // Kor'kron Rocketeer
    SPELL_ROCKET_ARTILLERY_A                = 70609,
    SPELL_ROCKET_ARTILLERY_H                = 69678,
    // Murading Bronzebeard
    // High Overlord Saurfang
    SPELL_RENDING_THROW                     = 70309,
    SPELL_TASTE_OF_BLOOD                    = 69634,
    // Hostile NPCs
    SPELL_TELEPORT_TO_ENEMY_SHIP            = 70104,
    SPELL_BATTLE_EXPERIENCE                 = 71201,
    SPELL_EXPERIENCED                       = 71188,
    SPELL_VETERAN                           = 71193,
    SPELL_ELITE                             = 71195,
    SPELL_ADDS_BERSERK                      = 72525,
    // Skybreaker Sergeant
    // Kor'kron Sergeant
    SPELL_BLADESTORM                        = 69652,
    SPELL_WOUNDING_STRIKE                   = 69651,
    SPELL_DESPERATE_RESOLVE                 = 69647,
    //
    SPELL_LOCK_PLAYERS_AND_TAP_CHEST        = 72347,
    SPELL_ON_SKYBREAKER_DECK                = 70120,
    SPELL_ON_ORGRIMS_HAMMER_DECK            = 70121,
    // Rocket Pack
    SPELL_CREATE_ROCKET_PACK                = 70055,
    SPELL_ROCKET_PACK_DAMAGE                = 69193,
    SPELL_ROCKET_BURST                      = 69192,
    SPELL_ROCKET_PACK_USEABLE               = 70348,
    // Alliance Gunship Cannon
    // Horde Gunship Cannon
    SPELL_OVERHEAT                          = 69487,
    SPELL_EJECT_ALL_PASSENGERS              = 68576,
};
Texts
enum Texts
Enumerator
SAY_SAURFANG_INTRO_1
SAY_SAURFANG_INTRO_2
SAY_SAURFANG_INTRO_3
SAY_SAURFANG_INTRO_4
SAY_SAURFANG_INTRO_5
SAY_SAURFANG_INTRO_6
SAY_SAURFANG_INTRO_A
SAY_SAURFANG_BOARD
SAY_SAURFANG_ENTER_SKYBREAKER
SAY_SAURFANG_AXETHROWERS
SAY_SAURFANG_ROCKETEERS
SAY_SAURFANG_MAGES
SAY_SAURFANG_VICTORY
SAY_SAURFANG_WIPE
SAY_MURADIN_INTRO_1
SAY_MURADIN_INTRO_2
SAY_MURADIN_INTRO_3
SAY_MURADIN_INTRO_4
SAY_MURADIN_INTRO_5
SAY_MURADIN_INTRO_6
SAY_MURADIN_INTRO_7
SAY_MURADIN_INTRO_H
SAY_MURADIN_BOARD
SAY_MURADIN_ENTER_ORGRIMMS_HAMMER
SAY_MURADIN_RIFLEMAN
SAY_MURADIN_MORTAR
SAY_MURADIN_SORCERERS
SAY_MURADIN_VICTORY
SAY_MURADIN_WIPE
SAY_ZAFOD_ROCKET_PACK_ACTIVE
SAY_ZAFOD_ROCKET_PACK_DISABLED
SAY_OVERHEAT
{
    // High Overlord Saurfang
    SAY_SAURFANG_INTRO_1                = 0,
    SAY_SAURFANG_INTRO_2                = 1,
    SAY_SAURFANG_INTRO_3                = 2,
    SAY_SAURFANG_INTRO_4                = 3,
    SAY_SAURFANG_INTRO_5                = 4,
    SAY_SAURFANG_INTRO_6                = 5,
    SAY_SAURFANG_INTRO_A                = 6,
    SAY_SAURFANG_BOARD                  = 7,
    SAY_SAURFANG_ENTER_SKYBREAKER       = 8,
    SAY_SAURFANG_AXETHROWERS            = 9,
    SAY_SAURFANG_ROCKETEERS             = 10,
    SAY_SAURFANG_MAGES                  = 11,
    SAY_SAURFANG_VICTORY                = 12,
    SAY_SAURFANG_WIPE                   = 13,
    // Muradin Bronzebeard
    SAY_MURADIN_INTRO_1                 = 0,
    SAY_MURADIN_INTRO_2                 = 1,
    SAY_MURADIN_INTRO_3                 = 2,
    SAY_MURADIN_INTRO_4                 = 3,
    SAY_MURADIN_INTRO_5                 = 4,
    SAY_MURADIN_INTRO_6                 = 5,
    SAY_MURADIN_INTRO_7                 = 6,
    SAY_MURADIN_INTRO_H                 = 7,
    SAY_MURADIN_BOARD                   = 8,
    SAY_MURADIN_ENTER_ORGRIMMS_HAMMER   = 9,
    SAY_MURADIN_RIFLEMAN                = 10,
    SAY_MURADIN_MORTAR                  = 11,
    SAY_MURADIN_SORCERERS               = 12,
    SAY_MURADIN_VICTORY                 = 13,
    SAY_MURADIN_WIPE                    = 14,
    SAY_ZAFOD_ROCKET_PACK_ACTIVE        = 0,
    SAY_ZAFOD_ROCKET_PACK_DISABLED      = 1,
    SAY_OVERHEAT                        = 0
};
Function Documentation
AddSC_boss_icecrown_gunship_battle()
void AddSC_boss_icecrown_gunship_battle ()
{
    new npc_gunship();
    new npc_high_overlord_saurfang_igb();
    new npc_muradin_bronzebeard_igb();
    new npc_zafod_boombox();
    new npc_igb_ship_crew();
    new npc_gunship_boarding_leader();
    new npc_gunship_boarding_add();
    new npc_gunship_mage();
    new npc_gunship_gunner();
    new npc_gunship_rocketeer();
    RegisterSpellScript(spell_igb_rocket_pack_aura);
    RegisterSpellScript(spell_igb_rocket_pack_useable_aura);
    RegisterSpellScript(spell_igb_teleport_to_enemy_ship);
    RegisterSpellScript(spell_igb_check_for_players);
    RegisterSpellScript(spell_igb_gunship_fall_teleport);
    RegisterSpellScript(spell_igb_explosion_main_aura);
    RegisterSpellScript(spell_igb_explosion);
    RegisterSpellScript(spell_igb_teleport_players_on_victory);
    RegisterSpellScript(spell_igb_periodic_trigger_with_power_cost_aura);
    RegisterSpellScript(spell_igb_overheat_aura);
    RegisterSpellScript(spell_igb_cannon_blast);
    RegisterSpellScript(spell_igb_incinerating_blast);
    RegisterSpellScript(spell_igb_burning_pitch_selector);
    RegisterSpellScript(spell_igb_burning_pitch);
    RegisterSpellScript(spell_igb_rocket_artillery);
    RegisterSpellScript(spell_igb_rocket_artillery_explosion);
    RegisterSpellScript(spell_igb_below_zero);
    RegisterSpellScript(spell_igb_on_gunship_deck_aura);
    new achievement_im_on_a_boat();
    RegisterSpellScript(spell_igb_battle_experience_check);
}
References RegisterSpellScript.
Referenced by AddNorthrendScripts().
TriggerBurningPitch()
void TriggerBurningPitch (Creature * c)
{
    InstanceScript* i = c->GetInstanceScript();
    uint32 spellId = i->GetData(DATA_TEAMID_IN_INSTANCE) == TEAM_HORDE ? SPELL_BURNING_PITCH_A : SPELL_BURNING_PITCH_H;
    if (!c->HasSpellCooldown(spellId))
    {
        c->CastSpell((Unit*)nullptr, spellId, false);
        c->_AddCreatureSpellCooldown(spellId, 0, urand(3000, 4000));
    }
}
References Creature::_AddCreatureSpellCooldown(), Unit::CastSpell(), DATA_TEAMID_IN_INSTANCE, ZoneScript::GetData(), WorldObject::GetInstanceScript(), Creature::HasSpellCooldown(), SPELL_BURNING_PITCH_A, SPELL_BURNING_PITCH_H, TEAM_HORDE, and urand().
Referenced by npc_gunship_boarding_leader::npc_gunship_boarding_leaderAI::UpdateAI(), npc_gunship_boarding_add::npc_gunship_boarding_add_realAI::UpdateAI(), and npc_gunship_gunner::npc_gunship_gunnerAI::UpdateAI().
Variable Documentation
MuradinExitPath
Position const MuradinExitPath[MuradinExitPathSize]
Initial value:
=
{
    { 8.130936f, -0.2699585f, 20.31728f, 0.0f },
    { 6.380936f, -0.2699585f, 20.31728f, 0.0f },
    { 3.507703f, 0.02986573f, 20.78463f, 0.0f },
    { -2.767633f, 3.743143f, 20.37663f, 0.0f },
    { -4.017633f, 4.493143f, 20.12663f, 0.0f },
    { -7.242224f, 6.856013f, 20.03468f, 0.0f },
    { -7.742224f, 8.606013f, 20.78468f, 0.0f },
    { -7.992224f, 9.856013f, 21.28468f, 0.0f },
    { -12.24222f, 23.10601f, 21.28468f, 0.0f },
    { -14.88477f, 25.20844f, 21.59985f, 0.0f },
}
{
    { 8.130936f, -0.2699585f, 20.31728f, 0.0f },
    { 6.380936f, -0.2699585f, 20.31728f, 0.0f },
    { 3.507703f, 0.02986573f, 20.78463f, 0.0f },
    { -2.767633f, 3.743143f, 20.37663f, 0.0f },
    { -4.017633f, 4.493143f, 20.12663f, 0.0f },
    { -7.242224f, 6.856013f, 20.03468f, 0.0f },
    { -7.742224f, 8.606013f, 20.78468f, 0.0f },
    { -7.992224f, 9.856013f, 21.28468f, 0.0f },
    { -12.24222f, 23.10601f, 21.28468f, 0.0f },
    { -14.88477f, 25.20844f, 21.59985f, 0.0f },
};
Referenced by npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::DoAction().
MuradinExitPathSize
uint32 const MuradinExitPathSize = 10
Referenced by npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::DoAction().
OrgrimsHammerAddsSpawnPos
Position const OrgrimsHammerAddsSpawnPos = { 60.728395f, 0.0f, 38.93467f, M_PI }
{ 60.728395f, 0.0f, 38.93467f, M_PI };
Referenced by PassengerController::ResetSlots().
OrgrimsHammerSlotInfo
SlotInfo const OrgrimsHammerSlotInfo[MAX_SLOTS]
{
    { NPC_KOR_KRON_BATTLE_MAGE, { 13.58548f, 0.3867192f, 34.99243f, 1.53589f }, 0 },
    { NPC_KOR_KRON_BATTLE_MAGE, { 47.29290f, -4.308941f, 37.55550f, 1.570796f }, 0 },
    { NPC_KOR_KRON_BATTLE_MAGE, { 47.34621f,  4.032004f, 37.70952f, 4.817109f }, 0 },
    { NPC_KOR_KRON_AXETHROWER, { -12.09280f, 27.65942f, 33.58557f, 1.53589f }, 30 },
    { NPC_KOR_KRON_AXETHROWER, { -3.170555f, 28.30652f, 34.21082f, 1.53589f }, 30 },
    { NPC_KOR_KRON_AXETHROWER, { 14.928040f, 26.18018f, 35.47803f, 1.53589f }, 30 },
    { NPC_KOR_KRON_AXETHROWER, { 24.703310f, 25.36584f, 35.97845f, 1.53589f }, 30 },
    { NPC_KOR_KRON_AXETHROWER, { -16.65302f, 27.59668f, 33.18726f, 1.53589f }, 30 },
    { NPC_KOR_KRON_AXETHROWER, { -8.084572f, 28.21448f, 33.93805f, 1.53589f }, 30 },
    { NPC_KOR_KRON_AXETHROWER, {  7.594765f, 27.41968f, 35.00775f, 1.53589f }, 30 },
    { NPC_KOR_KRON_AXETHROWER, { 20.763390f, 25.58215f, 35.75287f, 1.53589f }, 30 },
    { NPC_KOR_KRON_ROCKETEER, { -11.44849f, -25.71838f, 33.64343f, 1.518436f }, 30 },
    { NPC_KOR_KRON_ROCKETEER, {  12.30336f, -25.69653f, 35.32373f, 1.518436f }, 30 },
    { NPC_KOR_KRON_ROCKETEER, { -0.05931854f, -25.46399f, 34.50592f, 1.518436f }, 30 },
    { NPC_KOR_KRON_ROCKETEER, { 27.62149000f, -23.48108f, 36.12708f, 1.518436f }, 30 },
    { NPC_KOR_KRON_REAVER, OrgrimsHammerTeleportPortal, 0 },
    { NPC_KOR_KRON_REAVER, OrgrimsHammerTeleportPortal, 0 },
    { NPC_KOR_KRON_REAVER, OrgrimsHammerTeleportPortal, 0 },
    { NPC_KOR_KRON_REAVER, OrgrimsHammerTeleportPortal, 0 },
    { NPC_KOR_KRON_SERGEANT, OrgrimsHammerTeleportPortal, 0 },
    { NPC_KOR_KRON_SERGEANT, OrgrimsHammerTeleportPortal, 0 }
};
Referenced by PassengerController::ResetSlots(), gunship_npc_AI::SetSlotInfo(), and npc_gunship_boarding_addAI::SetSlotInfo().
OrgrimsHammerTeleportExit
Position const OrgrimsHammerTeleportExit = { 7.461699f, 0.158853f, 35.72989f, 0.0f }
{ 7.461699f, 0.158853f, 35.72989f, 0.0f };
Referenced by npc_gunship_boarding_addAI::MovementInform(), and npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::UpdateAI().
OrgrimsHammerTeleportPortal
Position const OrgrimsHammerTeleportPortal = { 47.550990f, -0.101778f, 37.61111f, 0.0f }
{ 47.550990f, -0.101778f, 37.61111f, 0.0f };
Referenced by npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::UpdateAI().
SaurfangExitPath
Position const SaurfangExitPath[SaurfangExitPathSize]
Initial value:
=
{
    { 30.43987f, 0.1475817f, 36.10674f, 0.0f },
    { 21.36141f, -3.056458f, 35.42970f, 0.0f },
    { 19.11141f, -3.806458f, 35.42970f, 0.0f },
    { 19.01736f, -3.299440f, 35.39428f, 0.0f },
    { 18.6747f, -5.862823f, 35.66611f, 0.0f },
    { 18.6747f, -7.862823f, 35.66611f, 0.0f },
    { 18.1747f, -17.36282f, 35.66611f, 0.0f },
    { 18.1747f, -22.61282f, 35.66611f, 0.0f },
    { 17.9247f, -24.36282f, 35.41611f, 0.0f },
    { 17.9247f, -26.61282f, 35.66611f, 0.0f },
    { 17.9247f, -27.86282f, 35.66611f, 0.0f },
    { 17.9247f, -29.36282f, 35.66611f, 0.0f },
    { 15.33203f, -30.42621f, 35.93796f, 0.0f }
}
{
    { 30.43987f, 0.1475817f, 36.10674f, 0.0f },
    { 21.36141f, -3.056458f, 35.42970f, 0.0f },
    { 19.11141f, -3.806458f, 35.42970f, 0.0f },
    { 19.01736f, -3.299440f, 35.39428f, 0.0f },
    { 18.6747f, -5.862823f, 35.66611f, 0.0f },
    { 18.6747f, -7.862823f, 35.66611f, 0.0f },
    { 18.1747f, -17.36282f, 35.66611f, 0.0f },
    { 18.1747f, -22.61282f, 35.66611f, 0.0f },
    { 17.9247f, -24.36282f, 35.41611f, 0.0f },
    { 17.9247f, -26.61282f, 35.66611f, 0.0f },
    { 17.9247f, -27.86282f, 35.66611f, 0.0f },
    { 17.9247f, -29.36282f, 35.66611f, 0.0f },
    { 15.33203f, -30.42621f, 35.93796f, 0.0f }
};
Referenced by npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::DoAction().
SaurfangExitPathSize
uint32 const SaurfangExitPathSize = 13
Referenced by npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::DoAction().
SkybreakerAddsSpawnPos
Position const SkybreakerAddsSpawnPos = { 15.91131f, 0.0f, 20.4628f, M_PI }
{ 15.91131f, 0.0f, 20.4628f, M_PI };
Referenced by PassengerController::ResetSlots().
SkybreakerSlotInfo
SlotInfo const SkybreakerSlotInfo[MAX_SLOTS]
{
    { NPC_SKYBREAKER_SORCERER, { -9.479858f, 0.05663967f, 20.77026f, 4.729842f }, 0 },
    { NPC_SKYBREAKER_SORCERER, { 6.385986f,  4.978760f, 20.55417f, 4.694936f }, 0 },
    { NPC_SKYBREAKER_SORCERER, { 6.579102f, -4.674561f, 20.55060f, 1.553343f }, 0 },
    { NPC_SKYBREAKER_RIFLEMAN, { -29.563900f, -17.95801f, 20.73837f, 4.747295f }, 30 },
    { NPC_SKYBREAKER_RIFLEMAN, { -18.017210f, -18.82056f, 20.79150f, 4.747295f }, 30 },
    { NPC_SKYBREAKER_RIFLEMAN, { -9.1193850f, -18.79102f, 20.58887f, 4.712389f }, 30 },
    { NPC_SKYBREAKER_RIFLEMAN, { -0.3364258f, -18.87183f, 20.56824f, 4.712389f }, 30 },
    { NPC_SKYBREAKER_RIFLEMAN, { -34.705810f, -17.67261f, 20.51523f, 4.729842f }, 30 },
    { NPC_SKYBREAKER_RIFLEMAN, { -23.562010f, -18.28564f, 20.67859f, 4.729842f }, 30 },
    { NPC_SKYBREAKER_RIFLEMAN, { -13.602780f, -18.74268f, 20.59622f, 4.712389f }, 30 },
    { NPC_SKYBREAKER_RIFLEMAN, { -4.3350220f, -18.84619f, 20.58234f, 4.712389f }, 30 },
    { NPC_SKYBREAKER_MORTAR_SOLDIER, { -31.70142f, 18.02783f, 20.77197f, 4.712389f }, 30 },
    { NPC_SKYBREAKER_MORTAR_SOLDIER, { -9.368652f, 18.75806f, 20.65335f, 4.712389f }, 30 },
    { NPC_SKYBREAKER_MORTAR_SOLDIER, { -20.40851f, 18.40381f, 20.50647f, 4.694936f }, 30 },
    { NPC_SKYBREAKER_MORTAR_SOLDIER, { 0.1585693f, 18.11523f, 20.41949f, 4.729842f }, 30 },
    { NPC_SKYBREAKER_MARINE, SkybreakerTeleportPortal, 0 },
    { NPC_SKYBREAKER_MARINE, SkybreakerTeleportPortal, 0 },
    { NPC_SKYBREAKER_MARINE, SkybreakerTeleportPortal, 0 },
    { NPC_SKYBREAKER_MARINE, SkybreakerTeleportPortal, 0 },
    { NPC_SKYBREAKER_SERGEANT, SkybreakerTeleportPortal, 0 },
    { NPC_SKYBREAKER_SERGEANT, SkybreakerTeleportPortal, 0 }
};
Referenced by PassengerController::ResetSlots(), gunship_npc_AI::SetSlotInfo(), and npc_gunship_boarding_addAI::SetSlotInfo().
SkybreakerTeleportExit
Position const SkybreakerTeleportExit = { -17.55738f, -0.090421f, 21.18366f, 0.0f }
{ -17.55738f, -0.090421f, 21.18366f, 0.0f };
Referenced by npc_gunship_boarding_addAI::MovementInform(), and npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::UpdateAI().
SkybreakerTeleportPortal
Position const SkybreakerTeleportPortal = { 6.666975f, 0.013001f, 20.87888f, 0.0f }
{ 6.666975f, 0.013001f, 20.87888f, 0.0f };
Referenced by npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::UpdateAI().