AzerothCore Doxygen
AbstractFollower Class Reference
#include "AbstractFollower.h"
Public Member Functions
AbstractFollower (Unit *target=nullptr)
virtual ~AbstractFollower ()
void SetTarget (Unit *unit)
Unit * GetTarget () const
bool IsTargetValid () const
virtual void stopFollowing ()
Public Attributes
Unit * _target = nullptr
Protected Attributes
FollowerReference i_target
Detailed Description
Constructor & Destructor Documentation
AbstractFollower()
AbstractFollower::AbstractFollower (Unit * target = nullptr) inline explicit
{ SetTarget(target); }
References SetTarget().
~AbstractFollower()
virtual AbstractFollower::~AbstractFollower () inline virtual
{ SetTarget(nullptr); }
References SetTarget().
Member Function Documentation
GetTarget()
Unit * AbstractFollower::GetTarget () const inline
{ return _target; }
References _target.
Referenced by FormationMovementGenerator::DoUpdate(), ChaseMovementGenerator< T >::GetTarget(), FollowMovementGenerator< T >::GetTarget(), and SetTarget().
IsTargetValid()
bool AbstractFollower::IsTargetValid () const inline
{ return i_target.isValid(); }
References i_target, and Reference< TO, FROM >::isValid().
SetTarget()
void AbstractFollower::SetTarget (Unit * unit)
{
    if (unit == GetTarget())
        return;
    i_target.link(unit, this);
    _target = i_target.getTarget();
}
References _target, Reference< TO, FROM >::getTarget(), GetTarget(), i_target, and Reference< TO, FROM >::link().
Referenced by AbstractFollower(), and ~AbstractFollower().
stopFollowing()
virtual void AbstractFollower::stopFollowing () inline virtual
{ }
Referenced by FollowerReference::sourceObjectDestroyLink().
Member Data Documentation
_target
Unit* AbstractFollower::_target = nullptr
Referenced by GetTarget(), and SetTarget().
i_target
FollowerReference AbstractFollower::i_target protected
Referenced by IsTargetValid(), and SetTarget().
The documentation for this class was generated from the following files:
azerothcore-wotlk/src/server/game/Movement/AbstractFollower.h
azerothcore-wotlk/src/server/game/Movement/AbstractFollower.cpp