AzerothCore Doxygen
ElunaUtil::Lockable Class Reference
#include "ElunaUtility.h"
Public Types
typedef std::mutex LockType
typedef std::lock_guard< LockType > Guard
Public Member Functions
LockType & GetLock ()
Private Attributes
LockType _lock
Detailed Description
Member Typedef Documentation
Guard
typedef std::lock_guard<LockType> ElunaUtil::Lockable::Guard
LockType
typedef std::mutex ElunaUtil::Lockable::LockType
Member Function Documentation
GetLock()
LockType & ElunaUtil::Lockable::GetLock () inline
{ return _lock; }
References _lock.
Referenced by BindingMap< K >::Clear(), BindingMap< K >::Clear(), BindingMap< K >::HasBindingsFor(), BindingMap< K >::Insert(), BindingMap< K >::PushRefsFor(), BindingMap< K >::Remove(), EventMgr::SetState(), EventMgr::SetStates(), and EventMgr::~EventMgr().
Member Data Documentation
_lock
LockType ElunaUtil::Lockable::_lock private
Referenced by GetLock().
The documentation for this class was generated from the following file:
mod-eluna/src/LuaEngine/ElunaUtility.h