AzerothCore Doxygen
boss_the_lurker_below Struct Reference
Public Member Functions
boss_the_lurker_below (Creature *creature)
void Reset () override
void EnterEvadeMode (EvadeReason why) override
void DamageTaken (Unit *, uint32 &damage, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void DoAction (int32 action) override
void AttackStart (Unit *who) override
void JustEngagedWith (Unit *who) override
Called for reaction when initially engaged.
void SummonedCreatureDies (Creature *, Unit *) override
void SchedulerPhaseOne (std::chrono::milliseconds spoutTimer, std::chrono::milliseconds p2Timer)
void SchedulerPhaseTwo (Milliseconds timer)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
Public Member Functions inherited from BossAI
BossAI (Creature *creature, uint32 bossId)
~BossAI () override
bool CanRespawn () override
void DamageTaken (Unit *attacker, uint32 &damage, DamageEffectType damagetype, SpellSchoolMask damageSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void JustSummoned (Creature *summon) override
void SummonedCreatureDespawn (Creature *summon) override
void SummonedCreatureDespawnAll () override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void ScheduleHealthCheckEvent (uint32 healthPct, std::function< void()> exec)
Executes a function once the creature reaches the defined health point percent.
void ScheduleHealthCheckEvent (std::initializer_list< uint8 > healthPct, std::function< void()> exec)
void ScheduleEnrageTimer (uint32 spellId, Milliseconds timer, uint8 textId=0)
virtual void ExecuteEvent (uint32)
virtual void ScheduleTasks ()
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER) override
void JustDied (Unit *) override
void JustReachedHome () override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportPlayer (Unit *unit, Position pos)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool IsUniqueTimedEventDone (uint32 id) const
void SetUniqueTimedEventDone (uint32 id)
void ResetUniqueTimedEvent (uint32 id)
void ClearUniqueTimedEventsDone ()
void ScheduleTimedEvent (Milliseconds timerMin, Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleTimedEvent (Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleUniqueTimedEvent (Milliseconds timer, std::function< void()> exec, uint32 uniqueId)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
void SetInvincibility (bool apply)
bool IsInvincible () const
void SetAutoAttackAllowed (bool allow)
bool IsAutoAttackAllowed () const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureEvade (Creature *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
int32 VisualizeBoundary (uint32 duration, Unit *owner=nullptr, bool fill=false, bool checkZ=false) const
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage to any victim (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from BossAI
float callForHelpRange
InstanceScript *const instance
Public Attributes inherited from ScriptedAI
Creature * me
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from BossAI
void _Reset ()
void _JustEngagedWith ()
void _JustDied ()
void _JustReachedHome ()
void _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
void TeleportCheaters ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from BossAI
SummonList summons
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
boss_the_lurker_below()
boss_the_lurker_below::boss_the_lurker_below (Creature * creature) inline
: BossAI(creature, DATA_THE_LURKER_BELOW) { }
Member Function Documentation
AttackStart()
void boss_the_lurker_below::AttackStart (Unit * who) inline override virtual
Reimplemented from UnitAI.
    {
        if (who && me->GetReactState() == REACT_AGGRESSIVE)
        {
            me->Attack(who, true);
        }
    }
References Unit::Attack(), Creature::GetReactState(), ScriptedAI::me, and REACT_AGGRESSIVE.
DamageTaken()
void boss_the_lurker_below::DamageTaken (Unit * , uint32 & , DamageEffectType , SpellSchoolMask) inline override virtual
Called at any Damage from any attacker (before damage apply)
Note
It use for recalculation damage or special reaction at damage for attack reaction use AttackedBy called for non DOT damage in Unit::DealDamage also
Reimplemented from UnitAI.
    {
        if (damage >= me->GetHealth())
        {
            // Liquid state around his area is working awkwardly and doesn't consider him to be swimming
            // Therefore he falls to the bottom of the lake when he dies, because he is "flying" in his pool
            // Removing this prevents him from dropping to the bottom of the lake
            // There is also a visual issue currently causing him to drop to the bottom of the lake but his body not update clientside
            // So it looks as if he was floating but he has in fact dropped to the bottom of the lake, and thus becomes unlootable
            me->SetDisableGravity(false);
        }
    }
References Unit::GetHealth(), ScriptedAI::me, and Creature::SetDisableGravity().
DoAction()
void boss_the_lurker_below::DoAction (int32 action) inline override virtual
Reimplemented from UnitAI.
    {
        if (action == ACTION_START_EVENT)
        {
            me->SetStandState(UNIT_STAND_STATE_SUBMERGED);
            me->SetReactState(REACT_AGGRESSIVE);
            me->setAttackTimer(BASE_ATTACK, 6000);
            me->RemoveUnitFlag(UNIT_FLAG_NOT_SELECTABLE);
            me->SetInCombatWithZone();
            me->SetStandState(UNIT_STAND_STATE_STAND);
        }
    }
References ACTION_START_EVENT, BASE_ATTACK, ScriptedAI::me, REACT_AGGRESSIVE, Unit::RemoveUnitFlag(), Unit::setAttackTimer(), Creature::SetInCombatWithZone(), Creature::SetReactState(), Unit::SetStandState(), UNIT_FLAG_NOT_SELECTABLE, UNIT_STAND_STATE_STAND, and UNIT_STAND_STATE_SUBMERGED.
EnterEvadeMode()
void boss_the_lurker_below::EnterEvadeMode (EvadeReason why) inline override virtual
Reimplemented from CreatureAI.
    {
        BossAI::EnterEvadeMode(why);
        if (GameObject* pool = instance->GetGameObject(DATA_STRANGE_POOL))
        {
            pool->Respawn();
            pool->SetRespawnTime(10);
            pool->SaveRespawnTime(10);
        }
        me->DespawnOrUnsummon(2000);
    }
References DATA_STRANGE_POOL, Creature::DespawnOrUnsummon(), BossAI::EnterEvadeMode(), InstanceScript::GetGameObject(), BossAI::instance, and ScriptedAI::me.
JustEngagedWith()
void boss_the_lurker_below::JustEngagedWith (Unit *) inline override virtual
Called for reaction when initially engaged.
Reimplemented from CreatureAI.
    {
        BossAI::JustEngagedWith(who);
        SchedulerPhaseOne(38800ms, 91000ms);
    }
References BossAI::JustEngagedWith(), and SchedulerPhaseOne().
Reset()
void boss_the_lurker_below::Reset () inline override virtual
Reimplemented from UnitAI.
    {
        BossAI::Reset();
        me->SetReactState(REACT_PASSIVE);
        me->SetStandState(UNIT_STAND_STATE_SUBMERGED);
        me->SetUnitFlag(UNIT_FLAG_NOT_SELECTABLE);
    }
References ScriptedAI::me, REACT_PASSIVE, BossAI::Reset(), Creature::SetReactState(), Unit::SetStandState(), Unit::SetUnitFlag(), UNIT_FLAG_NOT_SELECTABLE, and UNIT_STAND_STATE_SUBMERGED.
SchedulerPhaseOne()
void boss_the_lurker_below::SchedulerPhaseOne (std::chrono::milliseconds spoutTimer, std::chrono::milliseconds p2Timer) inline
    {
        scheduler.Schedule(10900ms, GROUP_GEYSER, [this](TaskContext context)
        {
            DoCastRandomTarget(SPELL_GEYSER);
            context.Repeat(10200ms, 54900ms);
        }).Schedule(18150ms, GROUP_WHIRL, [this](TaskContext context)
        {
            DoCastSelf(SPELL_WHIRL);
            context.Repeat(34150ms, 68550ms);
        }).Schedule(spoutTimer, [this](TaskContext context)
        {
            Talk(EMOTE_TAKE_BREATH);
            me->CastSpell(me, SPELL_SPOUT_VISUAL, TRIGGERED_IGNORE_SET_FACING);
            me->SetReactState(REACT_PASSIVE);
            me->SetFacingToObject(me->GetVictim());
            me->SetTarget();
            scheduler.RescheduleGroup(GROUP_GEYSER, 25s);
            scheduler.RescheduleGroup(GROUP_WHIRL, 20s);
            scheduler.Schedule(3s, [this](TaskContext)
            {
                me->InterruptNonMeleeSpells(false);
                DoCastSelf(RAND(SPELL_SPOUT_PERIODIC_1, SPELL_SPOUT_PERIODIC_2), true);
            });
            context.Repeat(60s);
        }).Schedule(p2Timer, [this](TaskContext)
        {
            //phase2
            scheduler.CancelAll();
            DoCastSelf(SPELL_SUBMERGE_VISUAL);
            DoCastSelf(SPELL_CLEAR_ALL_DEBUFFS, true);
            me->SetStandState(UNIT_STAND_STATE_SUBMERGED);
            me->SetUnitFlag(UNIT_FLAG_NOT_SELECTABLE);
            for (uint8 i = 0; i < MAX_SUMMONS; ++i)
            {
                //needs sniffed spell probably
                me->SummonCreature(i < 6 ? NPC_COILFANG_AMBUSHER : NPC_COILFANG_GUARDIAN, positions[i].GetPositionX(), positions[i].GetPositionY(), positions[i].GetPositionZ(), positions[i].GetAngle(me), TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT, 10000);
            }
            SchedulerPhaseTwo(60s);
        });
    }
References TaskScheduler::CancelAll(), Unit::CastSpell(), UnitAI::DoCastRandomTarget(), UnitAI::DoCastSelf(), EMOTE_TAKE_BREATH, Position::GetAngle(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Unit::GetVictim(), GROUP_GEYSER, GROUP_WHIRL, Unit::InterruptNonMeleeSpells(), MAX_SUMMONS, ScriptedAI::me, NPC_COILFANG_AMBUSHER, NPC_COILFANG_GUARDIAN, positions, RAND(), REACT_PASSIVE, TaskContext::Repeat(), TaskScheduler::RescheduleGroup(), TaskScheduler::Schedule(), CreatureAI::scheduler, SchedulerPhaseTwo(), Unit::SetFacingToObject(), Creature::SetReactState(), Unit::SetStandState(), Creature::SetTarget(), Unit::SetUnitFlag(), SPELL_CLEAR_ALL_DEBUFFS, SPELL_GEYSER, SPELL_SPOUT_PERIODIC_1, SPELL_SPOUT_PERIODIC_2, SPELL_SPOUT_VISUAL, SPELL_SUBMERGE_VISUAL, SPELL_WHIRL, WorldObject::SummonCreature(), TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT, TRIGGERED_IGNORE_SET_FACING, UNIT_FLAG_NOT_SELECTABLE, and UNIT_STAND_STATE_SUBMERGED.
Referenced by JustEngagedWith(), and SchedulerPhaseTwo().
SchedulerPhaseTwo()
void boss_the_lurker_below::SchedulerPhaseTwo (Milliseconds timer) inline
    {
        scheduler.Schedule(timer, [this](TaskContext)
        {
            me->setAttackTimer(BASE_ATTACK, 6000);
            me->SetStandState(UNIT_STAND_STATE_STAND);
            me->RemoveUnitFlag(UNIT_FLAG_NOT_SELECTABLE);
            scheduler.CancelAll();
            SchedulerPhaseOne(10000ms, 90750ms);
        });
    }
References BASE_ATTACK, TaskScheduler::CancelAll(), ScriptedAI::me, Unit::RemoveUnitFlag(), TaskScheduler::Schedule(), CreatureAI::scheduler, SchedulerPhaseOne(), Unit::setAttackTimer(), Unit::SetStandState(), UNIT_FLAG_NOT_SELECTABLE, and UNIT_STAND_STATE_STAND.
Referenced by SchedulerPhaseOne(), and SummonedCreatureDies().
SummonedCreatureDies()
void boss_the_lurker_below::SummonedCreatureDies (Creature * , Unit *) inline override virtual
Reimplemented from CreatureAI.
    {
        if (!summons.IsAnyCreatureAlive() && me->HasUnitFlag(UNIT_FLAG_NOT_SELECTABLE))
        {
            SchedulerPhaseTwo(1s);
        }
    }
References Unit::HasUnitFlag(), SummonList::IsAnyCreatureAlive(), ScriptedAI::me, SchedulerPhaseTwo(), BossAI::summons, and UNIT_FLAG_NOT_SELECTABLE.
UpdateAI()
void boss_the_lurker_below::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Implements UnitAI.
    {
        if (!UpdateVictim())
            return;
        scheduler.Update(diff);
        if (me->getStandState() != UNIT_STAND_STATE_STAND || !me->isAttackReady() || me->GetReactState() != REACT_AGGRESSIVE)
            return;
        Unit* target = nullptr;
        if (me->IsWithinMeleeRange(me->GetVictim()))
        {
            target = me->GetVictim();
        }
        else
        {
            ThreatContainer::StorageType const& t_list = me->GetThreatMgr().GetThreatList();
            for (ThreatReference const* ref : t_list)
            {
                if (Unit* threatTarget = ObjectAccessor::GetUnit(*me, ref->getUnitGuid()))
                {
                    if (me->IsWithinMeleeRange(threatTarget))
                    {
                        target = threatTarget;
                        break;
                    }
                }
            }
        }
        if (target)
        {
            me->AttackerStateUpdate(target);
        }
        else if ((target = SelectTarget(SelectTargetMethod::Random, 0)))
        {
            me->CastSpell(target, SPELL_WATER_BOLT, false);
        }
        me->resetAttackTimer();
    }
References Unit::AttackerStateUpdate(), Unit::CastSpell(), Creature::GetReactState(), Unit::getStandState(), ThreatMgr::GetThreatList(), Unit::GetThreatMgr(), ObjectAccessor::GetUnit(), Unit::GetVictim(), Unit::isAttackReady(), Unit::IsWithinMeleeRange(), ScriptedAI::me, Random, REACT_AGGRESSIVE, Unit::resetAttackTimer(), CreatureAI::scheduler, UnitAI::SelectTarget(), SPELL_WATER_BOLT, UNIT_STAND_STATE_STAND, TaskScheduler::Update(), and CreatureAI::UpdateVictim().
The documentation for this struct was generated from the following file:
azerothcore-wotlk/src/server/scripts/Outland/CoilfangReservoir/SerpentShrine/boss_lurker_below.cpp