AzerothCore Doxygen
StatSystem.cpp File Reference
#include "Config.h"
#include "Creature.h"
#include "Pet.h"
#include "Player.h"
#include "ScriptMgr.h"
#include "SharedDefines.h"
#include "SpellAuraEffects.h"
#include "SpellMgr.h"
#include "Unit.h"
Functions
bool _ModifyUInt32 (bool apply, uint32 &baseValue, int32 &amount)
Variables
const float m_diminishing_k [MAX_CLASSES]
Function Documentation
_ModifyUInt32()
bool _ModifyUInt32 (bool apply, uint32 & baseValue, int32 & amount) inline
{
    // If amount is negative, change sign and value of apply.
    if (amount < 0)
    {
        apply = !apply;
        amount = -amount;
    }
    if (apply)
        baseValue += amount;
    else
    {
        // Make sure we do not get uint32 overflow.
        if (amount > int32(baseValue))
            amount = baseValue;
        baseValue -= amount;
    }
    return apply;
}
Referenced by Player::ApplyFeralAPBonus(), Player::ApplyHealthRegenBonus(), Player::ApplyManaRegenBonus(), Player::ApplySpellDamageBonus(), Player::ApplySpellHealingBonus(), and Player::ApplySpellPowerBonus().
Variable Documentation
m_diminishing_k
const float m_diminishing_k[MAX_CLASSES]
Initial value:
=
{
    0.9560f,
    0.9560f,
    0.9880f,
    0.9880f,
    0.9830f,
    0.9560f,
    0.9880f,
    0.9830f,
    0.9830f,
    0.0f,
    0.9720f
}
{
    0.9560f,  // Warrior
    0.9560f,  // Paladin
    0.9880f,  // Hunter
    0.9880f,  // Rogue
    0.9830f,  // Priest
    0.9560f,  // DK
    0.9880f,  // Shaman
    0.9830f,  // Mage
    0.9830f,  // Warlock
    0.0f,     // ??
    0.9720f   // Druid
};
Referenced by Player::GetMissPercentageFromDefence(), Player::UpdateDodgePercentage(), and Player::UpdateParryPercentage().