AzerothCore Doxygen
lua.h File Reference
#include <stdarg.h>
#include <stddef.h>
#include "luaconf.h"
Classes
struct lua_Debug
Macros
#define LUA_VERSION_MAJOR "5"
#define LUA_VERSION_MINOR "2"
#define LUA_VERSION_NUM 502
#define LUA_VERSION_RELEASE "4"
#define LUA_VERSION "Lua " LUA_VERSION_MAJOR "." LUA_VERSION_MINOR
#define LUA_RELEASE LUA_VERSION "." LUA_VERSION_RELEASE
#define LUA_COPYRIGHT LUA_RELEASE " Copyright (C) 1994-2015 Lua.org, PUC-Rio"
#define LUA_AUTHORS "R. Ierusalimschy, L. H. de Figueiredo, W. Celes"
#define LUA_SIGNATURE "\033Lua"
#define LUA_MULTRET (-1)
#define LUA_REGISTRYINDEX LUAI_FIRSTPSEUDOIDX
#define lua_upvalueindex(i) (LUA_REGISTRYINDEX - (i))
#define LUA_OK 0
#define LUA_YIELD 1
#define LUA_ERRRUN 2
#define LUA_ERRSYNTAX 3
#define LUA_ERRMEM 4
#define LUA_ERRGCMM 5
#define LUA_ERRERR 6
#define LUA_TNONE (-1)
#define LUA_TNIL 0
#define LUA_TBOOLEAN 1
#define LUA_TLIGHTUSERDATA 2
#define LUA_TNUMBER 3
#define LUA_TSTRING 4
#define LUA_TTABLE 5
#define LUA_TFUNCTION 6
#define LUA_TUSERDATA 7
#define LUA_TTHREAD 8
#define LUA_NUMTAGS 9
#define LUA_MINSTACK 20
#define LUA_RIDX_MAINTHREAD 1
#define LUA_RIDX_GLOBALS 2
#define LUA_RIDX_LAST LUA_RIDX_GLOBALS
#define LUA_OPADD 0 /* ORDER TM */
#define LUA_OPSUB 1
#define LUA_OPMUL 2
#define LUA_OPDIV 3
#define LUA_OPMOD 4
#define LUA_OPPOW 5
#define LUA_OPUNM 6
#define LUA_OPEQ 0
#define LUA_OPLT 1
#define LUA_OPLE 2
#define lua_call(L, n, r) lua_callk(L, (n), (r), 0, NULL)
#define lua_pcall(L, n, r, f) lua_pcallk(L, (n), (r), (f), 0, NULL)
#define lua_yield(L, n) lua_yieldk(L, (n), 0, NULL)
#define LUA_GCSTOP 0
#define LUA_GCRESTART 1
#define LUA_GCCOLLECT 2
#define LUA_GCCOUNT 3
#define LUA_GCCOUNTB 4
#define LUA_GCSTEP 5
#define LUA_GCSETPAUSE 6
#define LUA_GCSETSTEPMUL 7
#define LUA_GCSETMAJORINC 8
#define LUA_GCISRUNNING 9
#define LUA_GCGEN 10
#define LUA_GCINC 11
#define lua_tonumber(L, i) lua_tonumberx(L,i,NULL)
#define lua_tointeger(L, i) lua_tointegerx(L,i,NULL)
#define lua_tounsigned(L, i) lua_tounsignedx(L,i,NULL)
#define lua_pop(L, n) lua_settop(L, -(n)-1)
#define lua_newtable(L) lua_createtable(L, 0, 0)
#define lua_register(L, n, f) (lua_pushcfunction(L, (f)), lua_setglobal(L, (n)))
#define lua_pushcfunction(L, f) lua_pushcclosure(L, (f), 0)
#define lua_isfunction(L, n) (lua_type(L, (n)) == LUA_TFUNCTION)
#define lua_istable(L, n) (lua_type(L, (n)) == LUA_TTABLE)
#define lua_islightuserdata(L, n) (lua_type(L, (n)) == LUA_TLIGHTUSERDATA)
#define lua_isnil(L, n) (lua_type(L, (n)) == LUA_TNIL)
#define lua_isboolean(L, n) (lua_type(L, (n)) == LUA_TBOOLEAN)
#define lua_isthread(L, n) (lua_type(L, (n)) == LUA_TTHREAD)
#define lua_isnone(L, n) (lua_type(L, (n)) == LUA_TNONE)
#define lua_isnoneornil(L, n) (lua_type(L, (n)) <= 0)
#define lua_pushliteral(L, s) lua_pushlstring(L, "" s, (sizeof(s)/sizeof(char))-1)
#define lua_pushglobaltable(L) lua_rawgeti(L, LUA_REGISTRYINDEX, LUA_RIDX_GLOBALS)
#define lua_tostring(L, i) lua_tolstring(L, (i), NULL)
#define LUA_HOOKCALL 0
#define LUA_HOOKRET 1
#define LUA_HOOKLINE 2
#define LUA_HOOKCOUNT 3
#define LUA_HOOKTAILCALL 4
#define LUA_MASKCALL (1 << LUA_HOOKCALL)
#define LUA_MASKRET (1 << LUA_HOOKRET)
#define LUA_MASKLINE (1 << LUA_HOOKLINE)
#define LUA_MASKCOUNT (1 << LUA_HOOKCOUNT)
Typedefs
typedef struct lua_State lua_State
typedef int(* lua_CFunction) (lua_State *L)
typedef const char *(* lua_Reader) (lua_State *L, void *ud, size_t *sz)
typedef int(* lua_Writer) (lua_State *L, const void *p, size_t sz, void *ud)
typedef void *(* lua_Alloc) (void *ud, void *ptr, size_t osize, size_t nsize)
typedef LUA_NUMBER lua_Number
typedef LUA_INTEGER lua_Integer
typedef LUA_UNSIGNED lua_Unsigned
typedef struct lua_Debug lua_Debug
typedef void(* lua_Hook) (lua_State *L, lua_Debug *ar)
Functions
LUA_API lua_State *() lua_newstate (lua_Alloc f, void *ud)
LUA_API void() lua_close (lua_State *L)
LUA_API lua_State *() lua_newthread (lua_State *L)
LUA_API lua_CFunction() lua_atpanic (lua_State *L, lua_CFunction panicf)
LUA_API const lua_Number *() lua_version (lua_State *L)
LUA_API int() lua_absindex (lua_State *L, int idx)
LUA_API int() lua_gettop (lua_State *L)
LUA_API void() lua_settop (lua_State *L, int idx)
LUA_API void() lua_pushvalue (lua_State *L, int idx)
LUA_API void() lua_remove (lua_State *L, int idx)
LUA_API void() lua_insert (lua_State *L, int idx)
LUA_API void() lua_replace (lua_State *L, int idx)
LUA_API void() lua_copy (lua_State *L, int fromidx, int toidx)
LUA_API int() lua_checkstack (lua_State *L, int sz)
LUA_API void() lua_xmove (lua_State *from, lua_State *to, int n)
LUA_API int() lua_isnumber (lua_State *L, int idx)
LUA_API int() lua_isstring (lua_State *L, int idx)
LUA_API int() lua_iscfunction (lua_State *L, int idx)
LUA_API int() lua_isuserdata (lua_State *L, int idx)
LUA_API int() lua_type (lua_State *L, int idx)
LUA_API const char *() lua_typename (lua_State *L, int tp)
LUA_API lua_Number() lua_tonumberx (lua_State *L, int idx, int *isnum)
LUA_API lua_Integer() lua_tointegerx (lua_State *L, int idx, int *isnum)
LUA_API lua_Unsigned() lua_tounsignedx (lua_State *L, int idx, int *isnum)
LUA_API int() lua_toboolean (lua_State *L, int idx)
LUA_API const char *() lua_tolstring (lua_State *L, int idx, size_t *len)
LUA_API size_t() lua_rawlen (lua_State *L, int idx)
LUA_API lua_CFunction() lua_tocfunction (lua_State *L, int idx)
LUA_API void *() lua_touserdata (lua_State *L, int idx)
LUA_API lua_State *() lua_tothread (lua_State *L, int idx)
LUA_API const void *() lua_topointer (lua_State *L, int idx)
LUA_API void() lua_arith (lua_State *L, int op)
LUA_API int() lua_rawequal (lua_State *L, int idx1, int idx2)
LUA_API int() lua_compare (lua_State *L, int idx1, int idx2, int op)
LUA_API void() lua_pushnil (lua_State *L)
LUA_API void() lua_pushnumber (lua_State *L, lua_Number n)
LUA_API void() lua_pushinteger (lua_State *L, lua_Integer n)
LUA_API void() lua_pushunsigned (lua_State *L, lua_Unsigned n)
LUA_API const char *() lua_pushlstring (lua_State *L, const char *s, size_t l)
LUA_API const char *() lua_pushstring (lua_State *L, const char *s)
LUA_API const char *() lua_pushvfstring (lua_State *L, const char *fmt, va_list argp)
LUA_API const char *() lua_pushfstring (lua_State *L, const char *fmt,...)
LUA_API void() lua_pushcclosure (lua_State *L, lua_CFunction fn, int n)
LUA_API void() lua_pushboolean (lua_State *L, int b)
LUA_API void() lua_pushlightuserdata (lua_State *L, void *p)
LUA_API int() lua_pushthread (lua_State *L)
LUA_API void() lua_getglobal (lua_State *L, const char *var)
LUA_API void() lua_gettable (lua_State *L, int idx)
LUA_API void() lua_getfield (lua_State *L, int idx, const char *k)
LUA_API void() lua_rawget (lua_State *L, int idx)
LUA_API void() lua_rawgeti (lua_State *L, int idx, int n)
LUA_API void() lua_rawgetp (lua_State *L, int idx, const void *p)
LUA_API void() lua_createtable (lua_State *L, int narr, int nrec)
LUA_API void *() lua_newuserdata (lua_State *L, size_t sz)
LUA_API int() lua_getmetatable (lua_State *L, int objindex)
LUA_API void() lua_getuservalue (lua_State *L, int idx)
LUA_API void() lua_setglobal (lua_State *L, const char *var)
LUA_API void() lua_settable (lua_State *L, int idx)
LUA_API void() lua_setfield (lua_State *L, int idx, const char *k)
LUA_API void() lua_rawset (lua_State *L, int idx)
LUA_API void() lua_rawseti (lua_State *L, int idx, int n)
LUA_API void() lua_rawsetp (lua_State *L, int idx, const void *p)
LUA_API int() lua_setmetatable (lua_State *L, int objindex)
LUA_API void() lua_setuservalue (lua_State *L, int idx)
LUA_API void() lua_callk (lua_State *L, int nargs, int nresults, int ctx, lua_CFunction k)
LUA_API int() lua_getctx (lua_State *L, int *ctx)
LUA_API int() lua_pcallk (lua_State *L, int nargs, int nresults, int errfunc, int ctx, lua_CFunction k)
LUA_API int() lua_load (lua_State *L, lua_Reader reader, void *dt, const char *chunkname, const char *mode)
LUA_API int() lua_dump (lua_State *L, lua_Writer writer, void *data)
LUA_API int() lua_yieldk (lua_State *L, int nresults, int ctx, lua_CFunction k)
LUA_API int() lua_resume (lua_State *L, lua_State *from, int narg)
LUA_API int() lua_status (lua_State *L)
LUA_API int() lua_gc (lua_State *L, int what, int data)
LUA_API int() lua_error (lua_State *L)
LUA_API int() lua_next (lua_State *L, int idx)
LUA_API void() lua_concat (lua_State *L, int n)
LUA_API void() lua_len (lua_State *L, int idx)
LUA_API lua_Alloc() lua_getallocf (lua_State *L, void **ud)
LUA_API void() lua_setallocf (lua_State *L, lua_Alloc f, void *ud)
LUA_API int() lua_getstack (lua_State *L, int level, lua_Debug *ar)
LUA_API int() lua_getinfo (lua_State *L, const char *what, lua_Debug *ar)
LUA_API const char *() lua_getlocal (lua_State *L, const lua_Debug *ar, int n)
LUA_API const char *() lua_setlocal (lua_State *L, const lua_Debug *ar, int n)
LUA_API const char *() lua_getupvalue (lua_State *L, int funcindex, int n)
LUA_API const char *() lua_setupvalue (lua_State *L, int funcindex, int n)
LUA_API void *() lua_upvalueid (lua_State *L, int fidx, int n)
LUA_API void() lua_upvaluejoin (lua_State *L, int fidx1, int n1, int fidx2, int n2)
LUA_API int() lua_sethook (lua_State *L, lua_Hook func, int mask, int count)
LUA_API lua_Hook() lua_gethook (lua_State *L)
LUA_API int() lua_gethookmask (lua_State *L)
LUA_API int() lua_gethookcount (lua_State *L)
Variables
const char lua_ident []
Macro Definition Documentation
LUA_AUTHORS
#define LUA_AUTHORS "R. Ierusalimschy, L. H. de Figueiredo, W. Celes"
lua_call
#define lua_call (L, n, r) lua_callk(L, (n), (r), 0, NULL)
LUA_COPYRIGHT
#define LUA_COPYRIGHT LUA_RELEASE " Copyright (C) 1994-2015 Lua.org, PUC-Rio"
LUA_ERRERR
#define LUA_ERRERR 6
LUA_ERRGCMM
#define LUA_ERRGCMM 5
LUA_ERRMEM
#define LUA_ERRMEM 4
LUA_ERRRUN
#define LUA_ERRRUN 2
LUA_ERRSYNTAX
#define LUA_ERRSYNTAX 3
LUA_GCCOLLECT
#define LUA_GCCOLLECT 2
LUA_GCCOUNT
#define LUA_GCCOUNT 3
LUA_GCCOUNTB
#define LUA_GCCOUNTB 4
LUA_GCGEN
#define LUA_GCGEN 10
LUA_GCINC
#define LUA_GCINC 11
LUA_GCISRUNNING
#define LUA_GCISRUNNING 9
LUA_GCRESTART
#define LUA_GCRESTART 1
LUA_GCSETMAJORINC
#define LUA_GCSETMAJORINC 8
LUA_GCSETPAUSE
#define LUA_GCSETPAUSE 6
LUA_GCSETSTEPMUL
#define LUA_GCSETSTEPMUL 7
LUA_GCSTEP
#define LUA_GCSTEP 5
LUA_GCSTOP
#define LUA_GCSTOP 0
LUA_HOOKCALL
#define LUA_HOOKCALL 0
LUA_HOOKCOUNT
#define LUA_HOOKCOUNT 3
LUA_HOOKLINE
#define LUA_HOOKLINE 2
LUA_HOOKRET
#define LUA_HOOKRET 1
LUA_HOOKTAILCALL
#define LUA_HOOKTAILCALL 4
lua_isboolean
#define lua_isboolean (L, n) (lua_type(L, (n)) == LUA_TBOOLEAN)
lua_isfunction
#define lua_isfunction (L, n) (lua_type(L, (n)) == LUA_TFUNCTION)
lua_islightuserdata
#define lua_islightuserdata (L, n) (lua_type(L, (n)) == LUA_TLIGHTUSERDATA)
lua_isnil
#define lua_isnil (L, n) (lua_type(L, (n)) == LUA_TNIL)
lua_isnone
#define lua_isnone (L, n) (lua_type(L, (n)) == LUA_TNONE)
lua_isnoneornil
#define lua_isnoneornil (L, n) (lua_type(L, (n)) <= 0)
lua_istable
#define lua_istable (L, n) (lua_type(L, (n)) == LUA_TTABLE)
lua_isthread
#define lua_isthread (L, n) (lua_type(L, (n)) == LUA_TTHREAD)
LUA_MASKCALL
#define LUA_MASKCALL (1 << LUA_HOOKCALL)
LUA_MASKCOUNT
#define LUA_MASKCOUNT (1 << LUA_HOOKCOUNT)
LUA_MASKLINE
#define LUA_MASKLINE (1 << LUA_HOOKLINE)
LUA_MASKRET
#define LUA_MASKRET (1 << LUA_HOOKRET)
LUA_MINSTACK
#define LUA_MINSTACK 20
LUA_MULTRET
#define LUA_MULTRET (-1)
lua_newtable
#define lua_newtable (L) lua_createtable(L, 0, 0)
LUA_NUMTAGS
#define LUA_NUMTAGS 9
LUA_OK
#define LUA_OK 0
LUA_OPADD
#define LUA_OPADD 0 /* ORDER TM */
LUA_OPDIV
#define LUA_OPDIV 3
LUA_OPEQ
#define LUA_OPEQ 0
LUA_OPLE
#define LUA_OPLE 2
LUA_OPLT
#define LUA_OPLT 1
LUA_OPMOD
#define LUA_OPMOD 4
LUA_OPMUL
#define LUA_OPMUL 2
LUA_OPPOW
#define LUA_OPPOW 5
LUA_OPSUB
#define LUA_OPSUB 1
LUA_OPUNM
#define LUA_OPUNM 6
lua_pcall
#define lua_pcall (L, n, r, f) lua_pcallk(L, (n), (r), (f), 0, NULL)
lua_pop
#define lua_pop (L, n) lua_settop(L, -(n)-1)
lua_pushcfunction
#define lua_pushcfunction (L, f) lua_pushcclosure(L, (f), 0)
lua_pushglobaltable
#define lua_pushglobaltable (L) lua_rawgeti(L, LUA_REGISTRYINDEX, LUA_RIDX_GLOBALS)
                 {
  int event;
  const char *name; /* (n) */
  const char *namewhat; /* (n) 'global', 'local', 'field', 'method' */
  const char *what; /* (S) 'Lua', 'C', 'main', 'tail' */
  const char *source;   /* (S) */
  int currentline;  /* (l) */
  int linedefined;  /* (S) */
  int lastlinedefined;  /* (S) */
  unsigned char nups;   /* (u) number of upvalues */
  unsigned char nparams;/* (u) number of parameters */
  char isvararg;        /* (u) */
  char istailcall;  /* (t) */
  char short_src[LUA_IDSIZE]; /* (S) */
  /* private part */
  struct CallInfo *i_ci;  /* active function */
};
/* }====================================================================== */
/******************************************************************************
* Copyright (C) 1994-2015 Lua.org, PUC-Rio.
*
* Permission is hereby granted, free of charge, to any person obtaining
* a copy of this software and associated documentation files (the
* "Software"), to deal in the Software without restriction, including
* without limitation the rights to use, copy, modify, merge, publish,
* distribute, sublicense, and/or sell copies of the Software, and to
* permit persons to whom the Software is furnished to do so, subject to
* the following conditions:
*
* The above copyright notice and this permission notice shall be
* included in all copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
* EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
* IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
* CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
* TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
* SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
******************************************************************************/
#endif
lua_pushliteral
#define lua_pushliteral (L, s) lua_pushlstring(L, "" s, (sizeof(s)/sizeof(char))-1)
lua_register
#define lua_register (L, n, f) (lua_pushcfunction(L, (f)), lua_setglobal(L, (n)))
LUA_REGISTRYINDEX
#define LUA_REGISTRYINDEX LUAI_FIRSTPSEUDOIDX
LUA_RELEASE
#define LUA_RELEASE LUA_VERSION "." LUA_VERSION_RELEASE
LUA_RIDX_GLOBALS
#define LUA_RIDX_GLOBALS 2
LUA_RIDX_LAST
#define LUA_RIDX_LAST LUA_RIDX_GLOBALS
LUA_RIDX_MAINTHREAD
#define LUA_RIDX_MAINTHREAD 1
LUA_SIGNATURE
#define LUA_SIGNATURE "\033Lua"
LUA_TBOOLEAN
#define LUA_TBOOLEAN 1
LUA_TFUNCTION
#define LUA_TFUNCTION 6
LUA_TLIGHTUSERDATA
#define LUA_TLIGHTUSERDATA 2
LUA_TNIL
#define LUA_TNIL 0
LUA_TNONE
#define LUA_TNONE (-1)
LUA_TNUMBER
#define LUA_TNUMBER 3
lua_tointeger
#define lua_tointeger (L, i) lua_tointegerx(L,i,NULL)
lua_tonumber
#define lua_tonumber (L, i) lua_tonumberx(L,i,NULL)
lua_tostring
#define lua_tostring (L, i) lua_tolstring(L, (i), NULL)
lua_tounsigned
#define lua_tounsigned (L, i) lua_tounsignedx(L,i,NULL)
LUA_TSTRING
#define LUA_TSTRING 4
LUA_TTABLE
#define LUA_TTABLE 5
LUA_TTHREAD
#define LUA_TTHREAD 8
LUA_TUSERDATA
#define LUA_TUSERDATA 7
lua_upvalueindex
#define lua_upvalueindex (i) (LUA_REGISTRYINDEX - (i))
LUA_VERSION
#define LUA_VERSION "Lua " LUA_VERSION_MAJOR "." LUA_VERSION_MINOR
LUA_VERSION_MAJOR
#define LUA_VERSION_MAJOR "5"
LUA_VERSION_MINOR
#define LUA_VERSION_MINOR "2"
LUA_VERSION_NUM
#define LUA_VERSION_NUM 502
LUA_VERSION_RELEASE
#define LUA_VERSION_RELEASE "4"
LUA_YIELD
#define LUA_YIELD 1
lua_yield
#define lua_yield (L, n) lua_yieldk(L, (n), 0, NULL)
Typedef Documentation
lua_Alloc
typedef void *(* lua_Alloc) (void *ud, void *ptr, size_t osize, size_t nsize)
lua_CFunction
typedef int(* lua_CFunction) (lua_State *L)
lua_Debug
typedef struct lua_Debug lua_Debug
lua_Hook
typedef void(* lua_Hook) (lua_State *L, lua_Debug *ar)
lua_Integer
typedef LUA_INTEGER lua_Integer
lua_Number
typedef LUA_NUMBER lua_Number
lua_Reader
typedef const char *(* lua_Reader) (lua_State *L, void *ud, size_t *sz)
lua_State
typedef struct lua_State lua_State
lua_Unsigned
typedef LUA_UNSIGNED lua_Unsigned
lua_Writer
typedef int(* lua_Writer) (lua_State *L, const void *p, size_t sz, void *ud)
Function Documentation
lua_absindex()
LUA_API int() lua_absindex (lua_State * L, int idx)
lua_arith()
LUA_API void() lua_arith (lua_State * L, int op)
lua_atpanic()
LUA_API lua_CFunction() lua_atpanic (lua_State * L, lua_CFunction panicf)
lua_callk()
LUA_API void() lua_callk (lua_State * L, int nargs, int nresults, int ctx, lua_CFunction k)
lua_checkstack()
LUA_API int() lua_checkstack (lua_State * L, int sz)
lua_close()
LUA_API void() lua_close (lua_State * L)
Referenced by Eluna::CloseLua().
lua_compare()
LUA_API int() lua_compare (lua_State * L, int idx1, int idx2, int op)
lua_concat()
LUA_API void() lua_concat (lua_State * L, int n)
lua_copy()
LUA_API void() lua_copy (lua_State * L, int fromidx, int toidx)
lua_createtable()
LUA_API void() lua_createtable (lua_State * L, int narr, int nrec)
Referenced by LuaCreature::GetAITargets(), LuaWorldObject::GetCreaturesInRange(), LuaUnit::GetFriendlyUnitsInRange(), LuaWorldObject::GetGameObjectsInRange(), LuaWorldObject::GetNearObjects(), LuaWorldObject::GetPlayersInRange(), LuaQuery::GetRow(), LuaUnit::GetUnfriendlyUnitsInRange(), and mar_encode_value().
lua_dump()
LUA_API int() lua_dump (lua_State * L, lua_Writer writer, void * data)
Referenced by mar_encode_value().
lua_error()
LUA_API int() lua_error (lua_State * L)
lua_gc()
LUA_API int() lua_gc (lua_State * L, int what, int data)
Referenced by Eluna::ExecuteCall().
lua_getallocf()
LUA_API lua_Alloc() lua_getallocf (lua_State * L, void ** ud)
lua_getctx()
LUA_API int() lua_getctx (lua_State * L, int * ctx)
lua_getfield()
LUA_API void() lua_getfield (lua_State * L, int idx, const char * k)
Referenced by Eluna::RunScripts(), and Eluna::StackTrace().
lua_getglobal()
LUA_API void() lua_getglobal (lua_State * L, const char * var)
Referenced by Eluna::OpenLua(), ElunaTemplate< T >::Register(), Eluna::RunScripts(), and Eluna::StackTrace().
lua_gethook()
LUA_API lua_Hook() lua_gethook (lua_State * L)
lua_gethookcount()
LUA_API int() lua_gethookcount (lua_State * L)
lua_gethookmask()
LUA_API int() lua_gethookmask (lua_State * L)
lua_getinfo()
LUA_API int() lua_getinfo (lua_State * L, const char * what, lua_Debug * ar)
Referenced by mar_encode_value().
lua_getlocal()
LUA_API const char *() lua_getlocal (lua_State * L, const lua_Debug * ar, int n)
lua_getmetatable()
LUA_API int() lua_getmetatable (lua_State * L, int objindex)
lua_getstack()
LUA_API int() lua_getstack (lua_State * L, int level, lua_Debug * ar)
lua_gettable()
LUA_API void() lua_gettable (lua_State * L, int idx)
Referenced by LuaGlobalFunctions::CreateLuaEvent(), ElunaInstanceAI::GetData(), ElunaInstanceAI::GetData64(), and LuaWorldObject::RegisterEvent().
lua_gettop()
LUA_API int() lua_gettop (lua_State * L)
Referenced by LuaGameObject::AddLoot(), LuaGlobalFunctions::AddTaxiPath(), ElunaTemplate< T >::CallMethod(), Eluna::CallOneFunction(), Eluna::CorpseRemoved(), Eluna::DamageTaken(), Eluna::ExecuteCall(), LuaGlobalFunctions::GetActiveGameEvents(), LuaCreature::GetAITargets(), LuaUnit::GetAttackers(), LuaWorldObject::GetCreaturesInRange(), LuaUnit::GetFriendlyUnitsInRange(), LuaWorldObject::GetGameObjectsInRange(), LuaGroup::GetMembers(), LuaGuild::GetMembers(), LuaWorldObject::GetNearObjects(), LuaMap::GetPlayers(), LuaWorldObject::GetPlayersInRange(), LuaGlobalFunctions::GetPlayersInWorld(), LuaRoll::GetPlayerVoteGUIDs(), LuaQuery::GetRow(), LuaGlobalFunctions::GetStackAsString(), LuaUnit::GetThreatList(), LuaUnit::GetUnfriendlyUnitsInRange(), Eluna::OnCanJoinLfg(), Eluna::OnGiveXP(), Eluna::OnMemberDepositMoney(), Eluna::OnMemberWitdrawMoney(), Eluna::OnMoneyChanged(), Eluna::OnReputationChange(), ElunaTemplate< T >::Register(), Eluna::ReplaceArgument(), Eluna::RunScripts(), LuaGlobalFunctions::SendMail(), Eluna::SetupStack(), and ElunaGlobal::thunk().
lua_getupvalue()
LUA_API const char *() lua_getupvalue (lua_State * L, int funcindex, int n)
Referenced by mar_encode_value().
lua_getuservalue()
LUA_API void() lua_getuservalue (lua_State * L, int idx)
lua_insert()
LUA_API void() lua_insert (lua_State * L, int idx)
Referenced by LuaGlobalFunctions::AddTaxiPath(), Eluna::ExecuteCall(), and Eluna::SetupStack().
lua_iscfunction()
LUA_API int() lua_iscfunction (lua_State * L, int idx)
lua_isnumber()
LUA_API int() lua_isnumber (lua_State * L, int idx)
Referenced by Eluna::CHECKVAL(), Eluna::CorpseRemoved(), Eluna::DamageTaken(), mar_decode_value(), Eluna::OnCanUseItem(), Eluna::OnGiveXP(), Eluna::OnMemberDepositMoney(), Eluna::OnMemberWitdrawMoney(), Eluna::OnMoneyChanged(), Eluna::OnReputationChange(), and LuaChatHandler::SendSysMessage().
lua_isstring()
LUA_API int() lua_isstring (lua_State * L, int idx)
Referenced by LuaGlobalFunctions::CreateLongLong(), LuaGlobalFunctions::CreateULongLong(), LuaGlobalFunctions::HttpRequest(), Eluna::OnChat(), Eluna::OnChat(), Eluna::OnChat(), Eluna::OnChat(), Eluna::OnChat(), and Eluna::StackTrace().
lua_isuserdata()
LUA_API int() lua_isuserdata (lua_State * L, int idx)
Referenced by Eluna::OnPacketReceiveAny(), and Eluna::OnPacketReceiveOne().
lua_len()
LUA_API void() lua_len (lua_State * L, int idx)
lua_load()
LUA_API int() lua_load (lua_State * L, lua_Reader reader, void * dt, const char * chunkname, const char * mode)
Referenced by mar_decode_value().
lua_newstate()
LUA_API lua_State *() lua_newstate (lua_Alloc f, void * ud)
lua_newthread()
LUA_API lua_State *() lua_newthread (lua_State * L)
lua_newuserdata()
LUA_API void *() lua_newuserdata (lua_State * L, size_t sz)
Referenced by ElunaTemplate< T >::Push().
lua_next()
LUA_API int() lua_next (lua_State * L, int idx)
Referenced by LuaGlobalFunctions::AddTaxiPath(), LuaGlobalFunctions::HttpRequest(), and mar_encode_table().
lua_pcallk()
LUA_API int() lua_pcallk (lua_State * L, int nargs, int nresults, int errfunc, int ctx, lua_CFunction k)
lua_pushboolean()
LUA_API void() lua_pushboolean (lua_State * L, int b)
Referenced by mar_decode_value(), and Eluna::Push().
lua_pushcclosure()
LUA_API void() lua_pushcclosure (lua_State * L, lua_CFunction fn, int n)
Referenced by createCancelCallback(), ElunaTemplate< T >::SetMethods(), and ElunaGlobal::SetMethods().
lua_pushfstring()
LUA_API const char *() lua_pushfstring (lua_State * L, const char * fmt, ...)
Referenced by ElunaTemplate< T >::ToString().
lua_pushinteger()
LUA_API void() lua_pushinteger (lua_State * L, lua_Integer n)
Referenced by mar_encode(), mar_encode_value(), Eluna::Push(), and Eluna::StackTrace().
lua_pushlightuserdata()
LUA_API void() lua_pushlightuserdata (lua_State * L, void * p)
Referenced by createCancelCallback(), Eluna::OpenLua(), ElunaTemplate< T >::SetMethods(), and ElunaGlobal::SetMethods().
lua_pushlstring()
LUA_API const char *() lua_pushlstring (lua_State * L, const char * s, size_t l)
Referenced by ElunaInstanceAI::Load(), mar_decode_value(), and mar_encode().
lua_pushnil()
LUA_API void() lua_pushnil (lua_State * L)
Referenced by Eluna::ExecuteCall(), LuaGlobalFunctions::HttpRequest(), mar_decode_value(), mar_encode(), mar_encode_table(), ElunaTemplate< T >::Push(), and Eluna::Push().
lua_pushnumber()
LUA_API void() lua_pushnumber (lua_State * L, lua_Number n)
Referenced by mar_decode_value(), mar_encode_value(), Eluna::Push(), and Eluna::Push().
lua_pushstring()
LUA_API const char *() lua_pushstring (lua_State * L, const char * s)
Referenced by Eluna::GetEluna(), ElunaTemplate< T >::GetType(), mar_decode_value(), mar_encode_value(), Eluna::OpenLua(), ElunaTemplate< T >::Push(), Eluna::Push(), Eluna::Push(), ElunaTemplate< T >::SetMethods(), and ElunaGlobal::SetMethods().
lua_pushthread()
LUA_API int() lua_pushthread (lua_State * L)
lua_pushunsigned()
LUA_API void() lua_pushunsigned (lua_State * L, lua_Unsigned n)
Referenced by Eluna::Push().
lua_pushvalue()
LUA_API void() lua_pushvalue (lua_State * L, int idx)
Referenced by LuaGlobalFunctions::AddTaxiPath(), Eluna::CallOneFunction(), LuaGlobalFunctions::CreateLuaEvent(), LuaGlobalFunctions::DBQueryAsync(), LuaGlobalFunctions::HttpRequest(), mar_decode_value(), mar_encode(), mar_encode_value(), ElunaTemplate< T >::Register(), LuaGlobalFunctions::RegisterEntryHelper(), LuaWorldObject::RegisterEvent(), LuaGlobalFunctions::RegisterEventHelper(), LuaGlobalFunctions::RegisterUniqueHelper(), and Eluna::StackTrace().
lua_pushvfstring()
LUA_API const char *() lua_pushvfstring (lua_State * L, const char * fmt, va_list argp)
lua_rawequal()
LUA_API int() lua_rawequal (lua_State * L, int idx1, int idx2)
lua_rawget()
LUA_API void() lua_rawget (lua_State * L, int idx)
Referenced by Eluna::GetEluna(), mar_decode_value(), mar_encode_value(), ElunaTemplate< T >::Push(), and ElunaTemplate< T >::SetMethods().
lua_rawgeti()
LUA_API void() lua_rawgeti (lua_State * L, int idx, int n)
Referenced by HttpManager::HandleHttpResponses(), mar_decode(), mar_decode_value(), mar_encode(), Eluna::OnTimedEvent(), Eluna::PushInstanceData(), and BindingMap< K >::PushRefsFor().
lua_rawgetp()
LUA_API void() lua_rawgetp (lua_State * L, int idx, const void * p)
lua_rawlen()
LUA_API size_t() lua_rawlen (lua_State * L, int idx)
Referenced by mar_decode(), and mar_encode().
lua_rawset()
LUA_API void() lua_rawset (lua_State * L, int idx)
Referenced by LuaQuery::GetRow(), mar_decode_table(), mar_decode_value(), mar_encode(), mar_encode_value(), ElunaTemplate< T >::SetMethods(), and ElunaGlobal::SetMethods().
lua_rawseti()
LUA_API void() lua_rawseti (lua_State * L, int idx, int n)
Referenced by LuaGlobalFunctions::GetActiveGameEvents(), LuaCreature::GetAITargets(), LuaUnit::GetAttackers(), LuaWorldObject::GetCreaturesInRange(), LuaUnit::GetFriendlyUnitsInRange(), LuaWorldObject::GetGameObjectsInRange(), LuaGroup::GetMembers(), LuaGuild::GetMembers(), LuaWorldObject::GetNearObjects(), LuaMap::GetPlayers(), LuaWorldObject::GetPlayersInRange(), LuaRoll::GetPlayerVoteGUIDs(), LuaUnit::GetThreatList(), LuaUnit::GetUnfriendlyUnitsInRange(), mar_decode(), mar_decode_value(), mar_encode_value(), and Eluna::OnCanJoinLfg().
lua_rawsetp()
LUA_API void() lua_rawsetp (lua_State * L, int idx, const void * p)
lua_remove()
LUA_API void() lua_remove (lua_State * L, int idx)
Referenced by LuaGlobalFunctions::AddTaxiPath(), Eluna::ExecuteCall(), mar_decode(), mar_decode_value(), mar_encode(), mar_encode_value(), and ElunaGlobal::SetMethods().
lua_replace()
LUA_API void() lua_replace (lua_State * L, int idx)
Referenced by mar_clone(), and Eluna::ReplaceArgument().
lua_resume()
LUA_API int() lua_resume (lua_State * L, lua_State * from, int narg)
lua_setallocf()
LUA_API void() lua_setallocf (lua_State * L, lua_Alloc f, void * ud)
lua_setfield()
LUA_API void() lua_setfield (lua_State * L, int idx, const char * k)
Referenced by Eluna::OpenLua(), ElunaTemplate< T >::Register(), and Eluna::RunScripts().
lua_setglobal()
LUA_API void() lua_setglobal (lua_State * L, const char * var)
Referenced by ElunaTemplate< T >::Register().
lua_sethook()
LUA_API int() lua_sethook (lua_State * L, lua_Hook func, int mask, int count)
lua_setlocal()
LUA_API const char *() lua_setlocal (lua_State * L, const lua_Debug * ar, int n)
lua_setmetatable()
LUA_API int() lua_setmetatable (lua_State * L, int objindex)
Referenced by ElunaTemplate< T >::Push().
lua_settable()
LUA_API void() lua_settable (lua_State * L, int idx)
Referenced by LuaSpell::GetReagentCost(), HttpManager::HandleHttpResponses(), ElunaInstanceAI::SetData(), and ElunaInstanceAI::SetData64().
lua_settop()
LUA_API void() lua_settop (lua_State * L, int idx)
Referenced by ElunaTemplate< T >::CallMethod(), LuaGlobalFunctions::GetActiveGameEvents(), LuaCreature::GetAITargets(), LuaUnit::GetAttackers(), LuaWorldObject::GetCreaturesInRange(), LuaUnit::GetFriendlyUnitsInRange(), LuaWorldObject::GetGameObjectsInRange(), LuaGroup::GetMembers(), LuaGuild::GetMembers(), LuaWorldObject::GetNearObjects(), LuaMap::GetPlayers(), LuaWorldObject::GetPlayersInRange(), LuaRoll::GetPlayerVoteGUIDs(), LuaQuery::GetRow(), LuaUnit::GetThreatList(), LuaUnit::GetUnfriendlyUnitsInRange(), mar_decode(), mar_encode(), Eluna::OnCanJoinLfg(), and ElunaGlobal::thunk().
lua_setupvalue()
LUA_API const char *() lua_setupvalue (lua_State * L, int funcindex, int n)
Referenced by mar_decode_value().
lua_setuservalue()
LUA_API void() lua_setuservalue (lua_State * L, int idx)
lua_status()
LUA_API int() lua_status (lua_State * L)
lua_toboolean()
LUA_API int() lua_toboolean (lua_State * L, int idx)
Referenced by Eluna::CallAllFunctionsBool(), Eluna::CHECKVAL(), Eluna::CorpseRemoved(), Eluna::DamageTaken(), mar_encode_value(), Eluna::OnChat(), Eluna::OnChat(), Eluna::OnChat(), Eluna::OnChat(), Eluna::OnChat(), Eluna::OnPacketReceiveAny(), Eluna::OnPacketReceiveOne(), Eluna::OnPacketSendAny(), Eluna::OnPacketSendOne(), and Eluna::RunScripts().
lua_tocfunction()
LUA_API lua_CFunction() lua_tocfunction (lua_State * L, int idx)
lua_tointegerx()
LUA_API lua_Integer() lua_tointegerx (lua_State * L, int idx, int * isnum)
lua_tolstring()
LUA_API const char *() lua_tolstring (lua_State * L, int idx, size_t * len)
Referenced by mar_encode_value(), and ElunaInstanceAI::Save().
lua_tonumberx()
LUA_API lua_Number() lua_tonumberx (lua_State * L, int idx, int * isnum)
lua_topointer()
LUA_API const void *() lua_topointer (lua_State * L, int idx)
lua_tothread()
LUA_API lua_State *() lua_tothread (lua_State * L, int idx)
lua_tounsignedx()
LUA_API lua_Unsigned() lua_tounsignedx (lua_State * L, int idx, int * isnum)
lua_touserdata()
LUA_API void *() lua_touserdata (lua_State * L, int idx)
Referenced by ElunaTemplate< T >::CallMethod(), cancelBinding(), Eluna::CHECKTYPE(), Eluna::GetEluna(), and ElunaGlobal::thunk().
lua_type()
LUA_API int() lua_type (lua_State * L, int idx)
Referenced by ElunaInstanceAI::Load(), and mar_encode_value().
lua_typename()
LUA_API const char *() lua_typename (lua_State * L, int tp)
Referenced by mar_encode_value().
lua_upvalueid()
LUA_API void *() lua_upvalueid (lua_State * L, int fidx, int n)
lua_upvaluejoin()
LUA_API void() lua_upvaluejoin (lua_State * L, int fidx1, int n1, int fidx2, int n2)
lua_version()
LUA_API const lua_Number *() lua_version (lua_State * L)
lua_xmove()
LUA_API void() lua_xmove (lua_State * from, lua_State * to, int n)
lua_yieldk()
LUA_API int() lua_yieldk (lua_State * L, int nresults, int ctx, lua_CFunction k)
Variable Documentation
lua_ident
const char lua_ident[] extern