AzerothCore Doxygen
OPvPCapturePointEP_PWT Class Reference
#include "OutdoorPvPEP.h"
Public Member Functions
OPvPCapturePointEP_PWT (OutdoorPvP *pvp)
void ChangeState () override
void SendChangePhase () override
void FillInitialWorldStates (WorldPackets::WorldState::InitWorldStates &packet) override
bool HandlePlayerEnter (Player *player) override
void HandlePlayerLeave (Player *player) override
Public Member Functions inherited from OPvPCapturePoint
OPvPCapturePoint (OutdoorPvP *pvp)
virtual ~OPvPCapturePoint ()=default
void SendUpdateWorldState (uint32 field, uint32 value)
void SendObjectiveComplete (uint32 id, ObjectGuid guid=ObjectGuid::Empty)
bool IsInsideObjective (Player *player) const
virtual bool HandleCustomSpell (Player *player, uint32 spellId, GameObject *go)
virtual int32 HandleOpenGo (Player *player, GameObject *go)
virtual bool Update (uint32 diff)
virtual void ChangeTeam (TeamId)
virtual bool HandleGossipOption (Player *player, Creature *creature, uint32 gossipId)
virtual bool CanTalkTo (Player *player, Creature *c, GossipMenuItems const &gso)
virtual bool HandleDropFlag (Player *player, uint32 spellId)
virtual void DeleteSpawns ()
void AddGO (uint32 type, ObjectGuid::LowType guid, uint32 entry=0)
void AddCre (uint32 type, ObjectGuid::LowType guid, uint32 entry=0)
bool SetCapturePointData (uint32 entry, uint32 map, float x, float y, float z, float o=0, float rotation0=0, float rotation1=0, float rotation2=0, float rotation3=0)
void SetSlider (float slider)
float GetSlider () const
Protected Member Functions
void SummonFlightMaster (TeamId teamId)
void UpdateTowerState ()
Protected Member Functions inherited from OPvPCapturePoint
bool AddObject (uint32 type, uint32 entry, uint32 map, float x, float y, float z, float o, float rotation0, float rotation1, float rotation2, float rotation3)
bool AddCreature (uint32 type, uint32 entry, uint32 map, float x, float y, float z, float o, uint32 spawntimeDelay=0)
bool DelCreature (uint32 type)
bool DelObject (uint32 type)
bool DelCapturePoint ()
Protected Attributes
TeamId m_FlightMasterSpawnedId
uint32 m_TowerState
Protected Attributes inherited from OPvPCapturePoint
std::array< PlayerSet, 2 > _activePlayers
float _maxValue {}
float _minValue {}
float _maxSpeed {}
float _value {}
TeamId _team { TEAM_NEUTRAL }
ObjectiveStates _oldState { OBJECTIVESTATE_NEUTRAL }
ObjectiveStates _state { OBJECTIVESTATE_NEUTRAL }
uint32 _neutralValuePct {}
OutdoorPvP * _pvp {}
std::unordered_map< uint32, ObjectGuid::LowType > _objects
std::unordered_map< uint32, ObjectGuid::LowType > _creatures
std::unordered_map< ObjectGuid::LowType, uint32 > _objectTypes
std::unordered_map< ObjectGuid::LowType, uint32 > _creatureTypes
Additional Inherited Members
Public Attributes inherited from OPvPCapturePoint
ObjectGuid::LowType m_capturePointSpawnId {}
GameObject * _capturePoint {}
Detailed Description
Constructor & Destructor Documentation
OPvPCapturePointEP_PWT()
OPvPCapturePointEP_PWT::OPvPCapturePointEP_PWT (OutdoorPvP * pvp)
    : OPvPCapturePoint(pvp), m_FlightMasterSpawnedId(TEAM_NEUTRAL), m_TowerState(EP_TS_N)
{
    SetCapturePointData(EPCapturePoints[EP_PWT].entry, EPCapturePoints[EP_PWT].map, EPCapturePoints[EP_PWT].x, EPCapturePoints[EP_PWT].y, EPCapturePoints[EP_PWT].z, EPCapturePoints[EP_PWT].o, EPCapturePoints[EP_PWT].rot0, EPCapturePoints[EP_PWT].rot1, EPCapturePoints[EP_PWT].rot2, EPCapturePoints[EP_PWT].rot3);
    AddObject(EP_PWT_FLAGS, EPTowerFlags[EP_PWT].entry, EPTowerFlags[EP_PWT].map, EPTowerFlags[EP_PWT].x, EPTowerFlags[EP_PWT].y, EPTowerFlags[EP_PWT].z, EPTowerFlags[EP_PWT].o, EPTowerFlags[EP_PWT].rot0, EPTowerFlags[EP_PWT].rot1, EPTowerFlags[EP_PWT].rot2, EPTowerFlags[EP_PWT].rot3);
}
References OPvPCapturePoint::AddObject(), EP_PWT, EP_PWT_FLAGS, EPCapturePoints, EPTowerFlags, and OPvPCapturePoint::SetCapturePointData().
Member Function Documentation
ChangeState()
void OPvPCapturePointEP_PWT::ChangeState () override virtual
Implements OPvPCapturePoint.
{
    // if changing from controlling alliance to horde or vice versa
    if (_oldState == OBJECTIVESTATE_ALLIANCE && _oldState != _state)
    {
        sWorldSessionMgr->SendZoneText(EP_GraveyardZone, sObjectMgr->GetAcoreStringForDBCLocale(LANG_OPVP_EP_LOSE_PWT_A));
        ((OutdoorPvPEP*)_pvp)->SetControlledState(EP_PWT, TEAM_NEUTRAL);
    }
    else if (_oldState == OBJECTIVESTATE_HORDE && _oldState != _state)
    {
        sWorldSessionMgr->SendZoneText(EP_GraveyardZone, sObjectMgr->GetAcoreStringForDBCLocale(LANG_OPVP_EP_LOSE_PWT_H));
        ((OutdoorPvPEP*)_pvp)->SetControlledState(EP_PWT, TEAM_NEUTRAL);
    }
    uint32 artkit = 21;
    switch (_state)
    {
        case OBJECTIVESTATE_ALLIANCE:
            m_TowerState = EP_TS_A;
            SummonFlightMaster(TEAM_ALLIANCE);
            artkit = 2;
            ((OutdoorPvPEP*)_pvp)->SetControlledState(EP_PWT, TEAM_ALLIANCE);
            if (_oldState != _state) sWorldSessionMgr->SendZoneText(EP_GraveyardZone, sObjectMgr->GetAcoreStringForDBCLocale(LANG_OPVP_EP_CAPTURE_PWT_A));
            break;
        case OBJECTIVESTATE_HORDE:
            m_TowerState = EP_TS_H;
            SummonFlightMaster(TEAM_HORDE);
            artkit = 1;
            ((OutdoorPvPEP*)_pvp)->SetControlledState(EP_PWT, TEAM_HORDE);
            if (_oldState != _state) sWorldSessionMgr->SendZoneText(EP_GraveyardZone, sObjectMgr->GetAcoreStringForDBCLocale(LANG_OPVP_EP_CAPTURE_PWT_H));
            break;
        case OBJECTIVESTATE_NEUTRAL:
            m_TowerState = EP_TS_N;
            DelCreature(EP_PWT_FLIGHTMASTER);
            m_FlightMasterSpawnedId = TEAM_NEUTRAL;
            break;
        case OBJECTIVESTATE_NEUTRAL_ALLIANCE_CHALLENGE:
            m_TowerState = EP_TS_N_A;
            break;
        case OBJECTIVESTATE_HORDE_ALLIANCE_CHALLENGE:
            m_TowerState = EP_TS_N_A;
            DelCreature(EP_PWT_FLIGHTMASTER);
            m_FlightMasterSpawnedId = TEAM_NEUTRAL;
            break;
        case OBJECTIVESTATE_NEUTRAL_HORDE_CHALLENGE:
            m_TowerState = EP_TS_N_H;
            break;
        case OBJECTIVESTATE_ALLIANCE_HORDE_CHALLENGE:
            m_TowerState = EP_TS_N_H;
            DelCreature(EP_PWT_FLIGHTMASTER);
            m_FlightMasterSpawnedId = TEAM_NEUTRAL;
            break;
    }
    Map* map = sMapMgr->FindMap(0, 0);
    auto bounds = map->GetGameObjectBySpawnIdStore().equal_range(m_capturePointSpawnId);
    for (auto itr = bounds.first; itr != bounds.second; ++itr)
        itr->second->SetGoArtKit(artkit);
    bounds = map->GetGameObjectBySpawnIdStore().equal_range(_objects[EP_PWT_FLAGS]);
    for (auto itr = bounds.first; itr != bounds.second; ++itr)
        itr->second->SetGoArtKit(artkit);
    UpdateTowerState();
    // complete quest objective
    if (m_TowerState == EP_TS_A || m_TowerState == EP_TS_H)
        SendObjectiveComplete(EP_PWT_CM);
}
References OPvPCapturePoint::_objects, OPvPCapturePoint::_oldState, OPvPCapturePoint::_pvp, OPvPCapturePoint::_state, OPvPCapturePoint::DelCreature(), EP_GraveyardZone, EP_PWT, EP_PWT_CM, EP_PWT_FLAGS, EP_PWT_FLIGHTMASTER, EP_TS_A, EP_TS_H, EP_TS_N, EP_TS_N_A, EP_TS_N_H, Map::GetGameObjectBySpawnIdStore(), LANG_OPVP_EP_CAPTURE_PWT_A, LANG_OPVP_EP_CAPTURE_PWT_H, LANG_OPVP_EP_LOSE_PWT_A, LANG_OPVP_EP_LOSE_PWT_H, OPvPCapturePoint::m_capturePointSpawnId, m_FlightMasterSpawnedId, m_TowerState, OBJECTIVESTATE_ALLIANCE, OBJECTIVESTATE_ALLIANCE_HORDE_CHALLENGE, OBJECTIVESTATE_HORDE, OBJECTIVESTATE_HORDE_ALLIANCE_CHALLENGE, OBJECTIVESTATE_NEUTRAL, OBJECTIVESTATE_NEUTRAL_ALLIANCE_CHALLENGE, OBJECTIVESTATE_NEUTRAL_HORDE_CHALLENGE, OPvPCapturePoint::SendObjectiveComplete(), sMapMgr, sObjectMgr, SummonFlightMaster(), sWorldSessionMgr, TEAM_ALLIANCE, TEAM_HORDE, TEAM_NEUTRAL, and UpdateTowerState().
FillInitialWorldStates()
void OPvPCapturePointEP_PWT::FillInitialWorldStates (WorldPackets::WorldState::InitWorldStates & packet) override virtual
Reimplemented from OPvPCapturePoint.
{
    packet.Worldstates.reserve(5);
    packet.Worldstates.emplace_back(WORLD_STATE_OPVP_EP_PLAGUEWOODTOWER_A, (m_TowerState & EP_TS_A) != 0 ? 1 : 0);
    packet.Worldstates.emplace_back(WORLD_STATE_OPVP_EP_PLAGUEWOODTOWER_H, (m_TowerState & EP_TS_H) != 0 ? 1 : 0);
    packet.Worldstates.emplace_back(WORLD_STATE_OPVP_EP_PLAGUEWOODTOWER_N_A, (m_TowerState & EP_TS_N_A) != 0 ? 1 : 0);
    packet.Worldstates.emplace_back(WORLD_STATE_OPVP_EP_PLAGUEWOODTOWER_N_H, (m_TowerState & EP_TS_N_H) != 0 ? 1 : 0);
    packet.Worldstates.emplace_back(WORLD_STATE_OPVP_EP_PLAGUEWOODTOWER_N, (m_TowerState & EP_TS_N) != 0 ? 1 : 0);
}
References EP_TS_A, EP_TS_H, EP_TS_N, EP_TS_N_A, EP_TS_N_H, m_TowerState, WORLD_STATE_OPVP_EP_PLAGUEWOODTOWER_A, WORLD_STATE_OPVP_EP_PLAGUEWOODTOWER_H, WORLD_STATE_OPVP_EP_PLAGUEWOODTOWER_N, WORLD_STATE_OPVP_EP_PLAGUEWOODTOWER_N_A, WORLD_STATE_OPVP_EP_PLAGUEWOODTOWER_N_H, and WorldPackets::WorldState::InitWorldStates::Worldstates.
HandlePlayerEnter()
bool OPvPCapturePointEP_PWT::HandlePlayerEnter (Player * player) override virtual
Reimplemented from OPvPCapturePoint.
{
    if (OPvPCapturePoint::HandlePlayerEnter(player))
    {
        player->SendUpdateWorldState(WORLD_STATE_OPVP_EP_UI_TOWER_SLIDER_DISPLAY, 1);
        uint32 phase = (uint32)ceil((_value + _maxValue) / (2 * _maxValue) * 100.0f);
        player->SendUpdateWorldState(WORLD_STATE_OPVP_EP_UI_TOWER_SLIDER_POS, phase);
        player->SendUpdateWorldState(WORLD_STATE_OPVP_EP_UI_TOWER_SLIDER_N, _neutralValuePct);
        return true;
    }
    return false;
}
References OPvPCapturePoint::_maxValue, OPvPCapturePoint::_neutralValuePct, OPvPCapturePoint::_value, OPvPCapturePoint::HandlePlayerEnter(), Player::SendUpdateWorldState(), WORLD_STATE_OPVP_EP_UI_TOWER_SLIDER_DISPLAY, WORLD_STATE_OPVP_EP_UI_TOWER_SLIDER_N, and WORLD_STATE_OPVP_EP_UI_TOWER_SLIDER_POS.
HandlePlayerLeave()
void OPvPCapturePointEP_PWT::HandlePlayerLeave (Player * player) override virtual
Reimplemented from OPvPCapturePoint.
{
    player->SendUpdateWorldState(WORLD_STATE_OPVP_EP_UI_TOWER_SLIDER_DISPLAY, 0);
    OPvPCapturePoint::HandlePlayerLeave(player);
}
References OPvPCapturePoint::HandlePlayerLeave(), Player::SendUpdateWorldState(), and WORLD_STATE_OPVP_EP_UI_TOWER_SLIDER_DISPLAY.
SendChangePhase()
void OPvPCapturePointEP_PWT::SendChangePhase () override virtual
Reimplemented from OPvPCapturePoint.
{
    // send this too, sometimes the slider disappears, dunno why :(
    SendUpdateWorldState(WORLD_STATE_OPVP_EP_UI_TOWER_SLIDER_DISPLAY, 1);
    // send these updates to only the ones in this objective
    uint32 phase = (uint32)ceil((_value + _maxValue) / (2 * _maxValue) * 100.0f);
    SendUpdateWorldState(WORLD_STATE_OPVP_EP_UI_TOWER_SLIDER_POS, phase);
    // send this too, sometimes it resets :S
    SendUpdateWorldState(WORLD_STATE_OPVP_EP_UI_TOWER_SLIDER_N, _neutralValuePct);
}
References OPvPCapturePoint::_maxValue, OPvPCapturePoint::_neutralValuePct, OPvPCapturePoint::_value, OPvPCapturePoint::SendUpdateWorldState(), WORLD_STATE_OPVP_EP_UI_TOWER_SLIDER_DISPLAY, WORLD_STATE_OPVP_EP_UI_TOWER_SLIDER_N, and WORLD_STATE_OPVP_EP_UI_TOWER_SLIDER_POS.
SummonFlightMaster()
void OPvPCapturePointEP_PWT::SummonFlightMaster (TeamId teamId) protected
{
    if (m_FlightMasterSpawnedId != teamId)
    {
        m_FlightMasterSpawnedId = teamId;
        DelCreature(EP_PWT_FLIGHTMASTER);
        AddCreature(EP_PWT_FLIGHTMASTER, EP_PWT_FlightMaster.entry, EP_PWT_FlightMaster.map, EP_PWT_FlightMaster.x, EP_PWT_FlightMaster.y, EP_PWT_FlightMaster.z, EP_PWT_FlightMaster.o);
        /*
        // sky - we need update gso code
        Creature* c = HashMapHolder<Creature>::Find(_creatures[EP_PWT_FLIGHTMASTER]);
        //Spawn flight master as friendly to capturing team
        c->SetUInt32Value(GAMEOBJECT_FACTION, (teamId == TEAM_ALLIANCE ? 55 : 68));
        if (c)
        {
            GossipOption gso;
            gso.Action = GOSSIP_OPTION_OUTDOORPVP;
            gso.GossipId = 0;
            gso.OptionText.assign(sObjectMgr->GetAcoreStringForDBCLocale(LANG_OPVP_EP_FLIGHT_NPT));
            gso.Id = 50;
            gso.Icon = 0;
            gso.NpcFlag = 0;
            gso.BoxMoney = 0;
            gso.Coded = false;
            c->addGossipOption(gso);
            gso.Action = GOSSIP_OPTION_OUTDOORPVP;
            gso.GossipId = 0;
            gso.OptionText.assign(sObjectMgr->GetAcoreStringForDBCLocale(LANG_OPVP_EP_FLIGHT_EWT));
            gso.Id = 50;
            gso.Icon = 0;
            gso.NpcFlag = 0;
            gso.BoxMoney = 0;
            gso.Coded = false;
            c->addGossipOption(gso);
            gso.Action = GOSSIP_OPTION_OUTDOORPVP;
            gso.GossipId = 0;
            gso.OptionText.assign(sObjectMgr->GetAcoreStringForDBCLocale(LANG_OPVP_EP_FLIGHT_CGT));
            gso.Id = 50;
            gso.Icon = 0;
            gso.NpcFlag = 0;
            gso.BoxMoney = 0;
            gso.Coded = false;
            c->addGossipOption(gso);
        }
        */
    }
}
References OPvPCapturePoint::AddCreature(), OPvPCapturePoint::DelCreature(), creature_type::entry, EP_PWT_FLIGHTMASTER, EP_PWT_FlightMaster, m_FlightMasterSpawnedId, creature_type::map, creature_type::o, creature_type::x, creature_type::y, and creature_type::z.
Referenced by ChangeState().
UpdateTowerState()
void OPvPCapturePointEP_PWT::UpdateTowerState () protected
{
    _pvp->SendUpdateWorldState(WORLD_STATE_OPVP_EP_PLAGUEWOODTOWER_A, bool(m_TowerState & EP_TS_A));
    _pvp->SendUpdateWorldState(WORLD_STATE_OPVP_EP_PLAGUEWOODTOWER_H, bool(m_TowerState & EP_TS_H));
    _pvp->SendUpdateWorldState(WORLD_STATE_OPVP_EP_PLAGUEWOODTOWER_N_A, bool(m_TowerState & EP_TS_N_A));
    _pvp->SendUpdateWorldState(WORLD_STATE_OPVP_EP_PLAGUEWOODTOWER_N_H, bool(m_TowerState & EP_TS_N_H));
    _pvp->SendUpdateWorldState(WORLD_STATE_OPVP_EP_PLAGUEWOODTOWER_N, bool(m_TowerState & EP_TS_N));
}
References OPvPCapturePoint::_pvp, EP_TS_A, EP_TS_H, EP_TS_N, EP_TS_N_A, EP_TS_N_H, m_TowerState, OutdoorPvP::SendUpdateWorldState(), WORLD_STATE_OPVP_EP_PLAGUEWOODTOWER_A, WORLD_STATE_OPVP_EP_PLAGUEWOODTOWER_H, WORLD_STATE_OPVP_EP_PLAGUEWOODTOWER_N, WORLD_STATE_OPVP_EP_PLAGUEWOODTOWER_N_A, and WORLD_STATE_OPVP_EP_PLAGUEWOODTOWER_N_H.
Referenced by ChangeState().
Member Data Documentation
m_FlightMasterSpawnedId
TeamId OPvPCapturePointEP_PWT::m_FlightMasterSpawnedId protected
Referenced by ChangeState(), and SummonFlightMaster().
m_TowerState
uint32 OPvPCapturePointEP_PWT::m_TowerState protected
Referenced by ChangeState(), FillInitialWorldStates(), and UpdateTowerState().
The documentation for this class was generated from the following files:
azerothcore-wotlk/src/server/scripts/OutdoorPvP/OutdoorPvPEP.h
azerothcore-wotlk/src/server/scripts/OutdoorPvP/OutdoorPvPEP.cpp