AzerothCore Doxygen
SpellProcAttributeTest.cpp File Reference
Unit tests for PROC_ATTR_* flags.
#include "ProcChanceTestHelper.h"
#include "ProcEventInfoHelper.h"
#include "SpellInfoTestHelper.h"
#include "AuraStub.h"
#include "UnitStub.h"
#include "gtest/gtest.h"
Classes
class SpellProcAttributeTest
Functions
TEST_F (SpellProcAttributeTest, ReqExpOrHonor_AttributeSet)
TEST_F (SpellProcAttributeTest, ReqExpOrHonor_AttributeNotSet)
TEST_F (SpellProcAttributeTest, TriggeredCanProc_AttributeSet)
TEST_F (SpellProcAttributeTest, TriggeredCanProc_AttributeNotSet)
TEST_F (SpellProcAttributeTest, ReqManaCost_AttributeSet)
TEST_F (SpellProcAttributeTest, ReqManaCost_NullSpell_ShouldNotProc)
TEST_F (SpellProcAttributeTest, ReqSpellmod_AttributeSet)
TEST_F (SpellProcAttributeTest, ReqSpellmod_AttributeNotSet)
TEST_F (SpellProcAttributeTest, ReqSpellmod_AutoGen_PctModifierWithCharges)
TEST_F (SpellProcAttributeTest, ReqSpellmod_AutoGen_FlatModifierWithCharges)
TEST_F (SpellProcAttributeTest, ReqSpellmod_AutoGen_NoCharges_NotSet)
TEST_F (SpellProcAttributeTest, ReqSpellmod_AutoGen_NonModifierWithCharges_NotSet)
TEST_F (SpellProcAttributeTest, ReqSpellmod_AutoGen_ModifierOnSecondEffect)
TEST_F (SpellProcAttributeTest, ReqSpellmod_AutoGen_PreservesExistingAttributes)
TEST_F (SpellProcAttributeTest, UseStacksForCharges_AttributeSet)
TEST_F (SpellProcAttributeTest, UseStacksForCharges_DecrementStacks)
TEST_F (SpellProcAttributeTest, UseStacksForCharges_NotSet_DecrementCharges)
TEST_F (SpellProcAttributeTest, ReduceProc60_AttributeSet)
TEST_F (SpellProcAttributeTest, ReduceProc60_Level60_NoReduction)
TEST_F (SpellProcAttributeTest, ReduceProc60_Level70_Reduced)
TEST_F (SpellProcAttributeTest, ReduceProc60_Level80_Reduced)
TEST_F (SpellProcAttributeTest, ReduceProc60_BelowLevel60_NoReduction)
TEST_F (SpellProcAttributeTest, ReduceProc60_NotSet_NoReduction)
TEST_F (SpellProcAttributeTest, CantProcFromItemCast_AttributeSet)
TEST_F (SpellProcAttributeTest, CantProcFromItemCast_AttributeNotSet)
TEST_F (SpellProcAttributeTest, CombinedAttributes_MultipleFlags)
TEST_F (SpellProcAttributeTest, CombinedAttributes_AllFlags)
TEST_F (SpellProcAttributeTest, Scenario_SealOfCommand_TriggeredCanProc)
TEST_F (SpellProcAttributeTest, Scenario_ClearCasting_ReqManaCost)
TEST_F (SpellProcAttributeTest, Scenario_MaelstromWeapon_UseStacks)
TEST_F (SpellProcAttributeTest, Scenario_OldLevelScaling_ReduceProc60)
TEST_F (SpellProcAttributeTest, AttributeValues_Correct)
TEST_F (SpellProcAttributeTest, AttributeFlags_NonOverlapping)
Detailed Description
Unit tests for PROC_ATTR_* flags.
Tests all proc attribute flags:
PROC_ATTR_REQ_EXP_OR_HONOR (0x01)
PROC_ATTR_TRIGGERED_CAN_PROC (0x02)
PROC_ATTR_REQ_MANA_COST (0x04)
PROC_ATTR_REQ_SPELLMOD (0x08)
PROC_ATTR_USE_STACKS_FOR_CHARGES (0x10)
PROC_ATTR_REDUCE_PROC_60 (0x80)
PROC_ATTR_CANT_PROC_FROM_ITEM_CAST (0x100)
Definition in file SpellProcAttributeTest.cpp.
Function Documentation
TEST_F() [1/33]
TEST_F (SpellProcAttributeTest , AttributeFlags_NonOverlapping)
{
    // Verify no two flags share the same bit
    uint32 flags[] = {
        PROC_ATTR_REQ_EXP_OR_HONOR,
        PROC_ATTR_TRIGGERED_CAN_PROC,
        PROC_ATTR_REQ_MANA_COST,
        PROC_ATTR_REQ_SPELLMOD,
        PROC_ATTR_USE_STACKS_FOR_CHARGES,
        PROC_ATTR_REDUCE_PROC_60,
        PROC_ATTR_CANT_PROC_FROM_ITEM_CAST
    };
    for (size_t i = 0; i < sizeof(flags)/sizeof(flags[0]); ++i)
    {
        for (size_t j = i + 1; j < sizeof(flags)/sizeof(flags[0]); ++j)
        {
            EXPECT_EQ(flags[i] & flags[j], 0u)
                << "Flags at index " << i << " and " << j << " overlap";
        }
    }
}
References PROC_ATTR_CANT_PROC_FROM_ITEM_CAST, PROC_ATTR_REDUCE_PROC_60, PROC_ATTR_REQ_EXP_OR_HONOR, PROC_ATTR_REQ_MANA_COST, PROC_ATTR_REQ_SPELLMOD, PROC_ATTR_TRIGGERED_CAN_PROC, and PROC_ATTR_USE_STACKS_FOR_CHARGES.
TEST_F() [2/33]
TEST_F (SpellProcAttributeTest , AttributeValues_Correct)
{
    // Verify attribute flag values match expected hex values
    EXPECT_EQ(PROC_ATTR_REQ_EXP_OR_HONOR,        0x0000001u);
    EXPECT_EQ(PROC_ATTR_TRIGGERED_CAN_PROC,     0x0000002u);
    EXPECT_EQ(PROC_ATTR_REQ_MANA_COST,          0x0000004u);
    EXPECT_EQ(PROC_ATTR_REQ_SPELLMOD,           0x0000008u);
    EXPECT_EQ(PROC_ATTR_USE_STACKS_FOR_CHARGES, 0x0000010u);
    EXPECT_EQ(PROC_ATTR_REDUCE_PROC_60,         0x0000080u);
    EXPECT_EQ(PROC_ATTR_CANT_PROC_FROM_ITEM_CAST, 0x0000100u);
}
References PROC_ATTR_CANT_PROC_FROM_ITEM_CAST, PROC_ATTR_REDUCE_PROC_60, PROC_ATTR_REQ_EXP_OR_HONOR, PROC_ATTR_REQ_MANA_COST, PROC_ATTR_REQ_SPELLMOD, PROC_ATTR_TRIGGERED_CAN_PROC, and PROC_ATTR_USE_STACKS_FOR_CHARGES.
TEST_F() [3/33]
TEST_F (SpellProcAttributeTest , CantProcFromItemCast_AttributeNotSet)
{
    auto procEntry = SpellProcEntryBuilder()
        .WithChance(100.0f)
        .WithAttributesMask(0)
        .Build();
    EXPECT_FALSE(procEntry.AttributesMask & PROC_ATTR_CANT_PROC_FROM_ITEM_CAST);
}
References SpellProcEntry::AttributesMask, SpellProcEntryBuilder::Build(), PROC_ATTR_CANT_PROC_FROM_ITEM_CAST, SpellProcEntryBuilder::WithAttributesMask(), and SpellProcEntryBuilder::WithChance().
TEST_F() [4/33]
TEST_F (SpellProcAttributeTest , CantProcFromItemCast_AttributeSet)
{
    auto procEntry = SpellProcEntryBuilder()
        .WithChance(100.0f)
        .WithAttributesMask(PROC_ATTR_CANT_PROC_FROM_ITEM_CAST)
        .Build();
    EXPECT_TRUE(procEntry.AttributesMask & PROC_ATTR_CANT_PROC_FROM_ITEM_CAST);
}
References SpellProcEntry::AttributesMask, SpellProcEntryBuilder::Build(), PROC_ATTR_CANT_PROC_FROM_ITEM_CAST, SpellProcEntryBuilder::WithAttributesMask(), and SpellProcEntryBuilder::WithChance().
TEST_F() [5/33]
TEST_F (SpellProcAttributeTest , CombinedAttributes_AllFlags)
{
    uint32 allFlags =
        PROC_ATTR_REQ_EXP_OR_HONOR |
        PROC_ATTR_TRIGGERED_CAN_PROC |
        PROC_ATTR_REQ_MANA_COST |
        PROC_ATTR_REQ_SPELLMOD |
        PROC_ATTR_USE_STACKS_FOR_CHARGES |
        PROC_ATTR_REDUCE_PROC_60 |
        PROC_ATTR_CANT_PROC_FROM_ITEM_CAST;
    auto procEntry = SpellProcEntryBuilder()
        .WithChance(100.0f)
        .WithAttributesMask(allFlags)
        .Build();
    EXPECT_TRUE(procEntry.AttributesMask & PROC_ATTR_REQ_EXP_OR_HONOR);
    EXPECT_TRUE(procEntry.AttributesMask & PROC_ATTR_TRIGGERED_CAN_PROC);
    EXPECT_TRUE(procEntry.AttributesMask & PROC_ATTR_REQ_MANA_COST);
    EXPECT_TRUE(procEntry.AttributesMask & PROC_ATTR_REQ_SPELLMOD);
    EXPECT_TRUE(procEntry.AttributesMask & PROC_ATTR_USE_STACKS_FOR_CHARGES);
    EXPECT_TRUE(procEntry.AttributesMask & PROC_ATTR_REDUCE_PROC_60);
    EXPECT_TRUE(procEntry.AttributesMask & PROC_ATTR_CANT_PROC_FROM_ITEM_CAST);
}
References SpellProcEntry::AttributesMask, SpellProcEntryBuilder::Build(), PROC_ATTR_CANT_PROC_FROM_ITEM_CAST, PROC_ATTR_REDUCE_PROC_60, PROC_ATTR_REQ_EXP_OR_HONOR, PROC_ATTR_REQ_MANA_COST, PROC_ATTR_REQ_SPELLMOD, PROC_ATTR_TRIGGERED_CAN_PROC, PROC_ATTR_USE_STACKS_FOR_CHARGES, SpellProcEntryBuilder::WithAttributesMask(), and SpellProcEntryBuilder::WithChance().
TEST_F() [6/33]
TEST_F (SpellProcAttributeTest , CombinedAttributes_MultipleFlags)
{
    auto procEntry = SpellProcEntryBuilder()
        .WithChance(100.0f)
        .WithAttributesMask(
            PROC_ATTR_TRIGGERED_CAN_PROC |
            PROC_ATTR_REQ_MANA_COST |
            PROC_ATTR_REDUCE_PROC_60)
        .Build();
    EXPECT_TRUE(procEntry.AttributesMask & PROC_ATTR_TRIGGERED_CAN_PROC);
    EXPECT_TRUE(procEntry.AttributesMask & PROC_ATTR_REQ_MANA_COST);
    EXPECT_TRUE(procEntry.AttributesMask & PROC_ATTR_REDUCE_PROC_60);
    EXPECT_FALSE(procEntry.AttributesMask & PROC_ATTR_REQ_EXP_OR_HONOR);
    EXPECT_FALSE(procEntry.AttributesMask & PROC_ATTR_USE_STACKS_FOR_CHARGES);
}
References SpellProcEntry::AttributesMask, SpellProcEntryBuilder::Build(), PROC_ATTR_REDUCE_PROC_60, PROC_ATTR_REQ_EXP_OR_HONOR, PROC_ATTR_REQ_MANA_COST, PROC_ATTR_TRIGGERED_CAN_PROC, PROC_ATTR_USE_STACKS_FOR_CHARGES, SpellProcEntryBuilder::WithAttributesMask(), and SpellProcEntryBuilder::WithChance().
TEST_F() [7/33]
TEST_F (SpellProcAttributeTest , ReduceProc60_AttributeSet)
{
    auto procEntry = SpellProcEntryBuilder()
        .WithChance(30.0f)
        .WithAttributesMask(PROC_ATTR_REDUCE_PROC_60)
        .Build();
    EXPECT_TRUE(procEntry.AttributesMask & PROC_ATTR_REDUCE_PROC_60);
}
References SpellProcEntry::AttributesMask, SpellProcEntryBuilder::Build(), PROC_ATTR_REDUCE_PROC_60, SpellProcEntryBuilder::WithAttributesMask(), and SpellProcEntryBuilder::WithChance().
TEST_F() [8/33]
TEST_F (SpellProcAttributeTest , ReduceProc60_BelowLevel60_NoReduction)
{
    auto procEntry = SpellProcEntryBuilder()
        .WithChance(30.0f)
        .WithAttributesMask(PROC_ATTR_REDUCE_PROC_60)
        .Build();
    float chance = ProcChanceTestHelper::SimulateCalcProcChance(procEntry, 50);
    EXPECT_NEAR(chance, 30.0f, 0.01f);
}
References SpellProcEntryBuilder::Build(), PROC_ATTR_REDUCE_PROC_60, ProcChanceTestHelper::SimulateCalcProcChance(), SpellProcEntryBuilder::WithAttributesMask(), and SpellProcEntryBuilder::WithChance().
TEST_F() [9/33]
TEST_F (SpellProcAttributeTest , ReduceProc60_Level60_NoReduction)
{
    auto procEntry = SpellProcEntryBuilder()
        .WithChance(30.0f)
        .WithAttributesMask(PROC_ATTR_REDUCE_PROC_60)
        .Build();
    float chance = ProcChanceTestHelper::SimulateCalcProcChance(procEntry, 60);
    EXPECT_NEAR(chance, 30.0f, 0.01f);
}
References SpellProcEntryBuilder::Build(), PROC_ATTR_REDUCE_PROC_60, ProcChanceTestHelper::SimulateCalcProcChance(), SpellProcEntryBuilder::WithAttributesMask(), and SpellProcEntryBuilder::WithChance().
TEST_F() [10/33]
TEST_F (SpellProcAttributeTest , ReduceProc60_Level70_Reduced)
{
    auto procEntry = SpellProcEntryBuilder()
        .WithChance(30.0f)
        .WithAttributesMask(PROC_ATTR_REDUCE_PROC_60)
        .Build();
    // Level 70 = 10 levels above 60
    // Reduction = 10/30 = 33.33%
    // 30% * (1 - 0.333) = 20%
    float chance = ProcChanceTestHelper::SimulateCalcProcChance(procEntry, 70);
    EXPECT_NEAR(chance, 20.0f, 0.5f);
}
References SpellProcEntryBuilder::Build(), PROC_ATTR_REDUCE_PROC_60, ProcChanceTestHelper::SimulateCalcProcChance(), SpellProcEntryBuilder::WithAttributesMask(), and SpellProcEntryBuilder::WithChance().
TEST_F() [11/33]
TEST_F (SpellProcAttributeTest , ReduceProc60_Level80_Reduced)
{
    auto procEntry = SpellProcEntryBuilder()
        .WithChance(30.0f)
        .WithAttributesMask(PROC_ATTR_REDUCE_PROC_60)
        .Build();
    // Level 80 = 20 levels above 60
    // Reduction = 20/30 = 66.67%
    // 30% * (1 - 0.667) = 10%
    float chance = ProcChanceTestHelper::SimulateCalcProcChance(procEntry, 80);
    EXPECT_NEAR(chance, 10.0f, 0.5f);
}
References SpellProcEntryBuilder::Build(), PROC_ATTR_REDUCE_PROC_60, ProcChanceTestHelper::SimulateCalcProcChance(), SpellProcEntryBuilder::WithAttributesMask(), and SpellProcEntryBuilder::WithChance().
TEST_F() [12/33]
TEST_F (SpellProcAttributeTest , ReduceProc60_NotSet_NoReduction)
{
    auto procEntry = SpellProcEntryBuilder()
        .WithChance(30.0f)
        .WithAttributesMask(0)  // No REDUCE_PROC_60
        .Build();
    // Even at level 80, no reduction without attribute
    float chance = ProcChanceTestHelper::SimulateCalcProcChance(procEntry, 80);
    EXPECT_NEAR(chance, 30.0f, 0.01f);
}
References SpellProcEntryBuilder::Build(), ProcChanceTestHelper::SimulateCalcProcChance(), SpellProcEntryBuilder::WithAttributesMask(), and SpellProcEntryBuilder::WithChance().
TEST_F() [13/33]
TEST_F (SpellProcAttributeTest , ReqExpOrHonor_AttributeNotSet)
{
    auto procEntry = SpellProcEntryBuilder()
        .WithChance(100.0f)
        .WithAttributesMask(0)
        .Build();
    EXPECT_FALSE(procEntry.AttributesMask & PROC_ATTR_REQ_EXP_OR_HONOR);
}
References SpellProcEntryBuilder::Build(), PROC_ATTR_REQ_EXP_OR_HONOR, SpellProcEntryBuilder::WithAttributesMask(), and SpellProcEntryBuilder::WithChance().
TEST_F() [14/33]
TEST_F (SpellProcAttributeTest , ReqExpOrHonor_AttributeSet)
{
    auto procEntry = SpellProcEntryBuilder()
        .WithChance(100.0f)
        .WithAttributesMask(PROC_ATTR_REQ_EXP_OR_HONOR)
        .Build();
    EXPECT_TRUE(procEntry.AttributesMask & PROC_ATTR_REQ_EXP_OR_HONOR);
}
References SpellProcEntryBuilder::Build(), PROC_ATTR_REQ_EXP_OR_HONOR, SpellProcEntryBuilder::WithAttributesMask(), and SpellProcEntryBuilder::WithChance().
TEST_F() [15/33]
TEST_F (SpellProcAttributeTest , ReqManaCost_AttributeSet)
{
    auto procEntry = SpellProcEntryBuilder()
        .WithChance(100.0f)
        .WithAttributesMask(PROC_ATTR_REQ_MANA_COST)
        .Build();
    EXPECT_TRUE(procEntry.AttributesMask & PROC_ATTR_REQ_MANA_COST);
}
References SpellProcEntryBuilder::Build(), PROC_ATTR_REQ_MANA_COST, SpellProcEntryBuilder::WithAttributesMask(), and SpellProcEntryBuilder::WithChance().
TEST_F() [16/33]
TEST_F (SpellProcAttributeTest , ReqManaCost_NullSpell_ShouldNotProc)
{
    // Null spell should never satisfy mana cost requirement
    EXPECT_FALSE(ProcChanceTestHelper::SpellHasManaCost(nullptr));
}
References ProcChanceTestHelper::SpellHasManaCost().
TEST_F() [17/33]
TEST_F (SpellProcAttributeTest , ReqSpellmod_AttributeNotSet)
{
    auto procEntry = SpellProcEntryBuilder()
        .WithChance(100.0f)
        .WithAttributesMask(0)
        .Build();
    EXPECT_FALSE(procEntry.AttributesMask & PROC_ATTR_REQ_SPELLMOD);
}
References SpellProcEntryBuilder::Build(), PROC_ATTR_REQ_SPELLMOD, SpellProcEntryBuilder::WithAttributesMask(), and SpellProcEntryBuilder::WithChance().
TEST_F() [18/33]
TEST_F (SpellProcAttributeTest , ReqSpellmod_AttributeSet)
{
    auto procEntry = SpellProcEntryBuilder()
        .WithChance(100.0f)
        .WithAttributesMask(PROC_ATTR_REQ_SPELLMOD)
        .Build();
    EXPECT_TRUE(procEntry.AttributesMask & PROC_ATTR_REQ_SPELLMOD);
}
References SpellProcEntryBuilder::Build(), PROC_ATTR_REQ_SPELLMOD, SpellProcEntryBuilder::WithAttributesMask(), and SpellProcEntryBuilder::WithChance().
TEST_F() [19/33]
TEST_F (SpellProcAttributeTest , ReqSpellmod_AutoGen_FlatModifierWithCharges)
{
    // Clearcasting-like: ADD_FLAT_MODIFIER + charges
    auto spellInfo = SpellInfoBuilder()
        .WithId(12345)
        .WithEffect(0, SPELL_EFFECT_APPLY_AURA, SPELL_AURA_ADD_FLAT_MODIFIER)
        .WithProcCharges(2)
        .BuildUnique();
    SpellProcEntry procEntry = SpellProcEntryBuilder()
        .WithCharges(2)
        .WithChance(100.0f)
        .Build();
    ApplyAutoGeneratedSpellmodFlag(spellInfo.get(), procEntry);
    EXPECT_TRUE(procEntry.AttributesMask & PROC_ATTR_REQ_SPELLMOD);
}
References SpellProcEntry::AttributesMask, SpellProcEntryBuilder::Build(), SpellInfoBuilder::BuildUnique(), PROC_ATTR_REQ_SPELLMOD, SPELL_AURA_ADD_FLAT_MODIFIER, SPELL_EFFECT_APPLY_AURA, SpellProcEntryBuilder::WithChance(), SpellProcEntryBuilder::WithCharges(), SpellInfoBuilder::WithEffect(), SpellInfoBuilder::WithId(), and SpellInfoBuilder::WithProcCharges().
TEST_F() [20/33]
TEST_F (SpellProcAttributeTest , ReqSpellmod_AutoGen_ModifierOnSecondEffect)
{
    // Modifier on effect index 1, not 0
    auto spellInfo = SpellInfoBuilder()
        .WithId(12345)
        .WithEffect(0, SPELL_EFFECT_APPLY_AURA, SPELL_AURA_PROC_TRIGGER_SPELL)
        .WithEffect(1, SPELL_EFFECT_APPLY_AURA, SPELL_AURA_ADD_FLAT_MODIFIER)
        .WithProcCharges(1)
        .BuildUnique();
    SpellProcEntry procEntry = SpellProcEntryBuilder()
        .WithCharges(1)
        .WithChance(100.0f)
        .Build();
    ApplyAutoGeneratedSpellmodFlag(spellInfo.get(), procEntry);
    EXPECT_TRUE(procEntry.AttributesMask & PROC_ATTR_REQ_SPELLMOD);
}
References SpellProcEntry::AttributesMask, SpellProcEntryBuilder::Build(), SpellInfoBuilder::BuildUnique(), PROC_ATTR_REQ_SPELLMOD, SPELL_AURA_ADD_FLAT_MODIFIER, SPELL_AURA_PROC_TRIGGER_SPELL, SPELL_EFFECT_APPLY_AURA, SpellProcEntryBuilder::WithChance(), SpellProcEntryBuilder::WithCharges(), SpellInfoBuilder::WithEffect(), SpellInfoBuilder::WithId(), and SpellInfoBuilder::WithProcCharges().
TEST_F() [21/33]
TEST_F (SpellProcAttributeTest , ReqSpellmod_AutoGen_NoCharges_NotSet)
{
    // Modifier aura without charges should NOT get the flag
    auto spellInfo = SpellInfoBuilder()
        .WithId(12345)
        .WithEffect(0, SPELL_EFFECT_APPLY_AURA, SPELL_AURA_ADD_PCT_MODIFIER)
        .WithProcCharges(0)
        .BuildUnique();
    SpellProcEntry procEntry = SpellProcEntryBuilder()
        .WithCharges(0)
        .WithChance(100.0f)
        .Build();
    ApplyAutoGeneratedSpellmodFlag(spellInfo.get(), procEntry);
    EXPECT_FALSE(procEntry.AttributesMask & PROC_ATTR_REQ_SPELLMOD);
}
References SpellProcEntry::AttributesMask, SpellProcEntryBuilder::Build(), SpellInfoBuilder::BuildUnique(), PROC_ATTR_REQ_SPELLMOD, SPELL_AURA_ADD_PCT_MODIFIER, SPELL_EFFECT_APPLY_AURA, SpellProcEntryBuilder::WithChance(), SpellProcEntryBuilder::WithCharges(), SpellInfoBuilder::WithEffect(), SpellInfoBuilder::WithId(), and SpellInfoBuilder::WithProcCharges().
TEST_F() [22/33]
TEST_F (SpellProcAttributeTest , ReqSpellmod_AutoGen_NonModifierWithCharges_NotSet)
{
    // Non-modifier aura with charges should NOT get the flag
    auto spellInfo = SpellInfoBuilder()
        .WithId(12345)
        .WithEffect(0, SPELL_EFFECT_APPLY_AURA, SPELL_AURA_PROC_TRIGGER_SPELL)
        .WithProcCharges(1)
        .BuildUnique();
    SpellProcEntry procEntry = SpellProcEntryBuilder()
        .WithCharges(1)
        .WithChance(100.0f)
        .Build();
    ApplyAutoGeneratedSpellmodFlag(spellInfo.get(), procEntry);
    EXPECT_FALSE(procEntry.AttributesMask & PROC_ATTR_REQ_SPELLMOD);
}
References SpellProcEntry::AttributesMask, SpellProcEntryBuilder::Build(), SpellInfoBuilder::BuildUnique(), PROC_ATTR_REQ_SPELLMOD, SPELL_AURA_PROC_TRIGGER_SPELL, SPELL_EFFECT_APPLY_AURA, SpellProcEntryBuilder::WithChance(), SpellProcEntryBuilder::WithCharges(), SpellInfoBuilder::WithEffect(), SpellInfoBuilder::WithId(), and SpellInfoBuilder::WithProcCharges().
TEST_F() [23/33]
TEST_F (SpellProcAttributeTest , ReqSpellmod_AutoGen_PctModifierWithCharges)
{
    // Rapid Killing (35099): ADD_PCT_MODIFIER + 1 charge
    auto spellInfo = SpellInfoBuilder()
        .WithId(35099)
        .WithEffect(0, SPELL_EFFECT_APPLY_AURA, SPELL_AURA_ADD_PCT_MODIFIER)
        .WithProcFlags(PROC_FLAG_DONE_RANGED_AUTO_ATTACK | PROC_FLAG_DONE_SPELL_RANGED_DMG_CLASS)
        .WithProcCharges(1)
        .BuildUnique();
    SpellProcEntry procEntry = SpellProcEntryBuilder()
        .WithProcFlags(PROC_FLAG_DONE_RANGED_AUTO_ATTACK | PROC_FLAG_DONE_SPELL_RANGED_DMG_CLASS)
        .WithCharges(1)
        .WithChance(100.0f)
        .Build();
    ApplyAutoGeneratedSpellmodFlag(spellInfo.get(), procEntry);
    EXPECT_TRUE(procEntry.AttributesMask & PROC_ATTR_REQ_SPELLMOD);
}
References SpellProcEntry::AttributesMask, SpellProcEntryBuilder::Build(), SpellInfoBuilder::BuildUnique(), PROC_ATTR_REQ_SPELLMOD, PROC_FLAG_DONE_RANGED_AUTO_ATTACK, PROC_FLAG_DONE_SPELL_RANGED_DMG_CLASS, SPELL_AURA_ADD_PCT_MODIFIER, SPELL_EFFECT_APPLY_AURA, SpellProcEntryBuilder::WithChance(), SpellProcEntryBuilder::WithCharges(), SpellInfoBuilder::WithEffect(), SpellInfoBuilder::WithId(), SpellInfoBuilder::WithProcCharges(), SpellProcEntryBuilder::WithProcFlags(), and SpellInfoBuilder::WithProcFlags().
TEST_F() [24/33]
TEST_F (SpellProcAttributeTest , ReqSpellmod_AutoGen_PreservesExistingAttributes)
{
    // Should OR with existing attributes, not replace
    auto spellInfo = SpellInfoBuilder()
        .WithId(12345)
        .WithEffect(0, SPELL_EFFECT_APPLY_AURA, SPELL_AURA_ADD_PCT_MODIFIER)
        .WithProcCharges(1)
        .BuildUnique();
    SpellProcEntry procEntry = SpellProcEntryBuilder()
        .WithCharges(1)
        .WithChance(100.0f)
        .WithAttributesMask(PROC_ATTR_TRIGGERED_CAN_PROC)
        .Build();
    ApplyAutoGeneratedSpellmodFlag(spellInfo.get(), procEntry);
    EXPECT_TRUE(procEntry.AttributesMask & PROC_ATTR_REQ_SPELLMOD);
    EXPECT_TRUE(procEntry.AttributesMask & PROC_ATTR_TRIGGERED_CAN_PROC);
}
References SpellProcEntry::AttributesMask, SpellProcEntryBuilder::Build(), SpellInfoBuilder::BuildUnique(), PROC_ATTR_REQ_SPELLMOD, PROC_ATTR_TRIGGERED_CAN_PROC, SPELL_AURA_ADD_PCT_MODIFIER, SPELL_EFFECT_APPLY_AURA, SpellProcEntryBuilder::WithAttributesMask(), SpellProcEntryBuilder::WithChance(), SpellProcEntryBuilder::WithCharges(), SpellInfoBuilder::WithEffect(), SpellInfoBuilder::WithId(), and SpellInfoBuilder::WithProcCharges().
TEST_F() [25/33]
TEST_F (SpellProcAttributeTest , Scenario_ClearCasting_ReqManaCost)
{
    // Clearcasting (Mage/Priest) requires spell to have mana cost
    auto procEntry = SpellProcEntryBuilder()
        .WithProcFlags(PROC_FLAG_DONE_SPELL_MAGIC_DMG_CLASS_NEG)
        .WithChance(100.0f)
        .WithAttributesMask(PROC_ATTR_REQ_MANA_COST)
        .Build();
    EXPECT_TRUE(procEntry.AttributesMask & PROC_ATTR_REQ_MANA_COST);
    // Null spell check - free/costless spells won't trigger
    EXPECT_FALSE(ProcChanceTestHelper::SpellHasManaCost(nullptr));
}
References SpellProcEntry::AttributesMask, SpellProcEntryBuilder::Build(), PROC_ATTR_REQ_MANA_COST, PROC_FLAG_DONE_SPELL_MAGIC_DMG_CLASS_NEG, ProcChanceTestHelper::SpellHasManaCost(), SpellProcEntryBuilder::WithAttributesMask(), SpellProcEntryBuilder::WithChance(), and SpellProcEntryBuilder::WithProcFlags().
TEST_F() [26/33]
TEST_F (SpellProcAttributeTest , Scenario_MaelstromWeapon_UseStacks)
{
    // Maelstrom Weapon (Shaman) uses stacks
    auto aura = AuraStubBuilder()
        .WithId(53817)
        .WithStackAmount(5)
        .Build();
    auto procEntry = SpellProcEntryBuilder()
        .WithChance(100.0f)
        .WithAttributesMask(PROC_ATTR_USE_STACKS_FOR_CHARGES)
        .Build();
    // Each proc consumes one stack
    ProcChanceTestHelper::SimulateConsumeProcCharges(aura.get(), procEntry);
    EXPECT_EQ(aura->GetStackAmount(), 4);
    ProcChanceTestHelper::SimulateConsumeProcCharges(aura.get(), procEntry);
    EXPECT_EQ(aura->GetStackAmount(), 3);
}
References AuraStubBuilder::Build(), SpellProcEntryBuilder::Build(), PROC_ATTR_USE_STACKS_FOR_CHARGES, ProcChanceTestHelper::SimulateConsumeProcCharges(), SpellProcEntryBuilder::WithAttributesMask(), SpellProcEntryBuilder::WithChance(), AuraStubBuilder::WithId(), and AuraStubBuilder::WithStackAmount().
TEST_F() [27/33]
TEST_F (SpellProcAttributeTest , Scenario_OldLevelScaling_ReduceProc60)
{
    // Some old vanilla/TBC procs have reduced chance at higher levels
    auto procEntry = SpellProcEntryBuilder()
        .WithChance(50.0f)
        .WithAttributesMask(PROC_ATTR_REDUCE_PROC_60)
        .Build();
    // Level 60: Full chance
    float chanceAt60 = ProcChanceTestHelper::SimulateCalcProcChance(procEntry, 60);
    EXPECT_NEAR(chanceAt60, 50.0f, 0.01f);
    // Level 75: 50% reduction (15/30)
    float chanceAt75 = ProcChanceTestHelper::SimulateCalcProcChance(procEntry, 75);
    EXPECT_NEAR(chanceAt75, 25.0f, 0.5f);
    // Level 90: 100% reduction (30/30), capped at 0
    float chanceAt90 = ProcChanceTestHelper::SimulateCalcProcChance(procEntry, 90);
    EXPECT_NEAR(chanceAt90, 0.0f, 0.1f);
}
References SpellProcEntryBuilder::Build(), PROC_ATTR_REDUCE_PROC_60, ProcChanceTestHelper::SimulateCalcProcChance(), SpellProcEntryBuilder::WithAttributesMask(), and SpellProcEntryBuilder::WithChance().
TEST_F() [28/33]
TEST_F (SpellProcAttributeTest , Scenario_SealOfCommand_TriggeredCanProc)
{
    // Seal of Command (Paladin) can proc from triggered spells
    auto procEntry = SpellProcEntryBuilder()
        .WithProcFlags(PROC_FLAG_DONE_MELEE_AUTO_ATTACK)
        .WithChance(100.0f)
        .WithAttributesMask(PROC_ATTR_TRIGGERED_CAN_PROC)
        .Build();
    EXPECT_TRUE(procEntry.AttributesMask & PROC_ATTR_TRIGGERED_CAN_PROC);
}
References SpellProcEntry::AttributesMask, SpellProcEntryBuilder::Build(), PROC_ATTR_TRIGGERED_CAN_PROC, PROC_FLAG_DONE_MELEE_AUTO_ATTACK, SpellProcEntryBuilder::WithAttributesMask(), SpellProcEntryBuilder::WithChance(), and SpellProcEntryBuilder::WithProcFlags().
TEST_F() [29/33]
TEST_F (SpellProcAttributeTest , TriggeredCanProc_AttributeNotSet)
{
    auto procEntry = SpellProcEntryBuilder()
        .WithChance(100.0f)
        .WithAttributesMask(0)
        .Build();
    EXPECT_FALSE(procEntry.AttributesMask & PROC_ATTR_TRIGGERED_CAN_PROC);
}
References SpellProcEntryBuilder::Build(), PROC_ATTR_TRIGGERED_CAN_PROC, SpellProcEntryBuilder::WithAttributesMask(), and SpellProcEntryBuilder::WithChance().
TEST_F() [30/33]
TEST_F (SpellProcAttributeTest , TriggeredCanProc_AttributeSet)
{
    auto procEntry = SpellProcEntryBuilder()
        .WithChance(100.0f)
        .WithAttributesMask(PROC_ATTR_TRIGGERED_CAN_PROC)
        .Build();
    EXPECT_TRUE(procEntry.AttributesMask & PROC_ATTR_TRIGGERED_CAN_PROC);
}
References SpellProcEntryBuilder::Build(), PROC_ATTR_TRIGGERED_CAN_PROC, SpellProcEntryBuilder::WithAttributesMask(), and SpellProcEntryBuilder::WithChance().
TEST_F() [31/33]
TEST_F (SpellProcAttributeTest , UseStacksForCharges_AttributeSet)
{
    auto procEntry = SpellProcEntryBuilder()
        .WithChance(100.0f)
        .WithAttributesMask(PROC_ATTR_USE_STACKS_FOR_CHARGES)
        .Build();
    EXPECT_TRUE(procEntry.AttributesMask & PROC_ATTR_USE_STACKS_FOR_CHARGES);
}
References SpellProcEntry::AttributesMask, SpellProcEntryBuilder::Build(), PROC_ATTR_USE_STACKS_FOR_CHARGES, SpellProcEntryBuilder::WithAttributesMask(), and SpellProcEntryBuilder::WithChance().
TEST_F() [32/33]
TEST_F (SpellProcAttributeTest , UseStacksForCharges_DecrementStacks)
{
    auto aura = AuraStubBuilder()
        .WithId(12345)
        .WithStackAmount(5)
        .Build();
    auto procEntry = SpellProcEntryBuilder()
        .WithChance(100.0f)
        .WithAttributesMask(PROC_ATTR_USE_STACKS_FOR_CHARGES)
        .Build();
    ProcChanceTestHelper::SimulateConsumeProcCharges(aura.get(), procEntry);
    EXPECT_EQ(aura->GetStackAmount(), 4);
}
References AuraStubBuilder::Build(), SpellProcEntryBuilder::Build(), PROC_ATTR_USE_STACKS_FOR_CHARGES, ProcChanceTestHelper::SimulateConsumeProcCharges(), SpellProcEntryBuilder::WithAttributesMask(), SpellProcEntryBuilder::WithChance(), AuraStubBuilder::WithId(), and AuraStubBuilder::WithStackAmount().
TEST_F() [33/33]
TEST_F (SpellProcAttributeTest , UseStacksForCharges_NotSet_DecrementCharges)
{
    auto aura = AuraStubBuilder()
        .WithId(12345)
        .WithCharges(5)
        .WithStackAmount(5)
        .Build();
    auto procEntry = SpellProcEntryBuilder()
        .WithChance(100.0f)
        .WithAttributesMask(0)  // No USE_STACKS_FOR_CHARGES
        .Build();
    ProcChanceTestHelper::SimulateConsumeProcCharges(aura.get(), procEntry);
    // Charges should decrement, stacks unchanged
    EXPECT_EQ(aura->GetCharges(), 4);
    EXPECT_EQ(aura->GetStackAmount(), 5);
}
References AuraStubBuilder::Build(), SpellProcEntryBuilder::Build(), ProcChanceTestHelper::SimulateConsumeProcCharges(), SpellProcEntryBuilder::WithAttributesMask(), SpellProcEntryBuilder::WithChance(), AuraStubBuilder::WithCharges(), AuraStubBuilder::WithId(), and AuraStubBuilder::WithStackAmount().