AzerothCore Doxygen
npc_necrotic_shard Struct Reference
Public Member Functions
npc_necrotic_shard (Creature *creature)
void ScheduleMinionSpawnTask ()
void ScheduleCultistSpawnTask ()
void ScheduleTasks ()
void Reset () override
bool HasCampTypeAura ()
void SpellHit (Unit *caster, SpellInfo const *spell) override
void SpellHitTarget (Unit *, SpellInfo const *spellInfo) override
void DamageTaken (Unit *attacker, uint32 &damage, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void JustDied (Unit *) override
void HandleShardMinionSpawnerSmall ()
void SummonCultists ()
void UpdateFindersAmount ()
void DespawnCultists ()
void DespawnShadowsOfDoom ()
void DespawnEventDoodads ()
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportPlayer (Unit *unit, Position pos)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool IsUniqueTimedEventDone (uint32 id) const
void SetUniqueTimedEventDone (uint32 id)
void ResetUniqueTimedEvent (uint32 id)
void ClearUniqueTimedEventsDone ()
void ScheduleTimedEvent (Milliseconds timerMin, Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleTimedEvent (Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0s, uint32 uniqueId=0)
void ScheduleUniqueTimedEvent (Milliseconds timer, std::function< void()> exec, uint32 uniqueId)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
void SetInvincibility (bool apply)
bool IsInvincible () const
void SetAutoAttackAllowed (bool allow)
bool IsAutoAttackAllowed () const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
int32 VisualizeBoundary (uint32 duration, Unit *owner=nullptr, bool fill=false, bool checkZ=false) const
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage to any victim (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Static Public Member Functions
static uint32 HasMinion (Unit *searcher, float searchDistance=ATTACK_DISTANCE)
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Private Attributes
uint32 _spellCampType = 0
uint32 _nearbyFinderCount = 0
uint8 _zapCount = 0
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Public Attributes inherited from ScriptedAI
Creature * me
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
npc_necrotic_shard()
npc_necrotic_shard::npc_necrotic_shard (Creature * creature) inline
                                           : ScriptedAI(creature)
    {
        me->setActive(true);
        me->SetReactState(REACT_PASSIVE);
        // No healing possible.
        me->ApplySpellImmune(0, IMMUNITY_EFFECT, SPELL_EFFECT_HEAL, true);
        me->ApplySpellImmune(0, IMMUNITY_EFFECT, SPELL_EFFECT_HEAL_PCT, true);
        me->ApplySpellImmune(0, IMMUNITY_EFFECT, SPELL_EFFECT_HEAL_MAX_HEALTH, true);
        me->ApplySpellImmune(0, IMMUNITY_STATE, SPELL_AURA_PERIODIC_HEAL, true);
    }
References Unit::ApplySpellImmune(), IMMUNITY_EFFECT, IMMUNITY_STATE, ScriptedAI::me, REACT_PASSIVE, WorldObject::setActive(), Creature::SetReactState(), SPELL_AURA_PERIODIC_HEAL, SPELL_EFFECT_HEAL, SPELL_EFFECT_HEAL_MAX_HEALTH, and SPELL_EFFECT_HEAL_PCT.
Member Function Documentation
DamageTaken()
void npc_necrotic_shard::DamageTaken (Unit * , uint32 & , DamageEffectType , SpellSchoolMask) inline override virtual
Called at any Damage from any attacker (before damage apply)
Note
It use for recalculation damage or special reaction at damage for attack reaction use AttackedBy called for non DOT damage in Unit::DealDamage also
Reimplemented from UnitAI.
    {
        if (attacker->GetFactionTemplateEntry() != me->GetFactionTemplateEntry())
            damage = 0;
    }
References Unit::GetFactionTemplateEntry(), and ScriptedAI::me.
DespawnCultists()
void npc_necrotic_shard::DespawnCultists () inline
    {
        std::list<Creature*> cultistList;
        me->GetCreatureListWithEntryInGrid(cultistList, NPC_CULTIST_ENGINEER, INSPECT_DISTANCE);
        for (Creature* cultist : cultistList)
            if (cultist)
                cultist->DespawnOrUnsummon();
    }
References WorldObject::GetCreatureListWithEntryInGrid(), INSPECT_DISTANCE, ScriptedAI::me, and NPC_CULTIST_ENGINEER.
Referenced by JustDied().
DespawnEventDoodads()
void npc_necrotic_shard::DespawnEventDoodads () inline
    {
        std::list<GameObject*> doodadList;
        me->GetGameObjectListWithEntryInGrid(
            doodadList,
            { GO_SUMMON_CIRCLE, GO_UNDEAD_FIRE, GO_UNDEAD_FIRE_AURA, GO_SKULLPILE_01, GO_SKULLPILE_02, GO_SKULLPILE_03, GO_SKULLPILE_04, GO_SUMMONER_SHIELD },
            60.0f
        );
        for (GameObject* const& doodad : doodadList)
        {
            doodad->SetRespawnDelay(-1);
            doodad->DespawnOrUnsummon();
        }
        std::list<Creature*> finderList;
        me->GetCreatureListWithEntryInGrid(
            finderList,
            NPC_SCOURGE_INVASION_MINION_FINDER,
            60.0f
        );
        for (Creature* const& finder : finderList)
            finder->DespawnOrUnsummon();
    }
References WorldObject::GetCreatureListWithEntryInGrid(), WorldObject::GetGameObjectListWithEntryInGrid(), GO_SKULLPILE_01, GO_SKULLPILE_02, GO_SKULLPILE_03, GO_SKULLPILE_04, GO_SUMMON_CIRCLE, GO_SUMMONER_SHIELD, GO_UNDEAD_FIRE, GO_UNDEAD_FIRE_AURA, ScriptedAI::me, and NPC_SCOURGE_INVASION_MINION_FINDER.
Referenced by JustDied(), and ScheduleTasks().
DespawnShadowsOfDoom()
void npc_necrotic_shard::DespawnShadowsOfDoom () inline
    {
        std::list<Creature*> shadowList;
        me->GetCreatureListWithEntryInGrid(shadowList, NPC_SHADOW_OF_DOOM, 200.0f);
        for (Creature* shadow : shadowList)
            if (shadow && shadow->IsAlive() && !shadow->IsInCombat())
                shadow->DespawnOrUnsummon();
    }
References WorldObject::GetCreatureListWithEntryInGrid(), ScriptedAI::me, and NPC_SHADOW_OF_DOOM.
Referenced by ScheduleCultistSpawnTask().
HandleShardMinionSpawnerSmall()
void npc_necrotic_shard::HandleShardMinionSpawnerSmall () inline
    {
        uint32 spawnLimit = urand(1, 3); // Up to 3 spawns.
        uint32 spawned = 0;
        std::list<Creature*> finderList;
        GetCreatureListWithEntryInGrid(finderList, me, NPC_SCOURGE_INVASION_MINION_FINDER, 60.0f);
        if (finderList.empty())
            return;
        // On a fresh camp, first the minions are spawned close to the shard and then further and further out.
        finderList.sort(Acore::ObjectDistanceOrderPred(me));
        for (Creature* const& finder : finderList)
        {
            // Stop summoning Minions if we reached the max spawn amount.
            if (spawned == spawnLimit)
                break;
            // Skip dead finders.
            if (!finder->IsAlive())
                continue;
            // Don't take finders with Minions.
            if (HasMinion(finder))
                continue;
            // A finder disappears after summoning the spawner NPC (which summons the minion).
            // after 160-185 seconds a finder respawns on the same position as before.
            if (finder->CastSpell(me, SPELL_FIND_CAMP_TYPE, true) == SPELL_CAST_OK)
            {
                // Values are from Sniffs (rounded). Shortest and Longest respawn time from a finder on the same spot.
                finder->DespawnOrUnsummon(0s, randtime(150s, 200s)); // Delayed despawn to prevent stacked spawns
                spawned++;
            }
        }
    }
References GetCreatureListWithEntryInGrid(), HasMinion(), ScriptedAI::me, NPC_SCOURGE_INVASION_MINION_FINDER, randtime(), SPELL_CAST_OK, SPELL_FIND_CAMP_TYPE, and urand().
Referenced by ScheduleMinionSpawnTask().
HasCampTypeAura()
bool npc_necrotic_shard::HasCampTypeAura () inline
    {
        return me->HasAnyAuras(SPELL_CAMP_TYPE_GHOST_SKELETON, SPELL_CAMP_TYPE_GHOST_GHOUL, SPELL_CAMP_TYPE_GHOUL_SKELETON);
    };
References Unit::HasAnyAuras(), ScriptedAI::me, SPELL_CAMP_TYPE_GHOST_GHOUL, SPELL_CAMP_TYPE_GHOST_SKELETON, and SPELL_CAMP_TYPE_GHOUL_SKELETON.
Referenced by SpellHit().
HasMinion()
static uint32 npc_necrotic_shard::HasMinion (Unit * searcher, float searchDistance = ATTACK_DISTANCE) inline static
    {
        uint32 minionCounter = 0;
        std::list<Creature*> minionList;
        searcher->GetCreatureListWithEntryInGrid(
            minionList,
            { NPC_SKELETAL_SHOCKTROOPER, NPC_GHOUL_BERSERKER, NPC_SPECTRAL_SOLDIER, NPC_LUMBERING_HORROR, NPC_BONE_WITCH, NPC_SPIRIT_OF_THE_DAMNED },
            searchDistance
        );
        for (Creature const* minion : minionList)
            if (minion && minion->IsAlive())
                minionCounter++;
        return minionCounter;
    }
References WorldObject::GetCreatureListWithEntryInGrid(), NPC_BONE_WITCH, NPC_GHOUL_BERSERKER, NPC_LUMBERING_HORROR, NPC_SKELETAL_SHOCKTROOPER, NPC_SPECTRAL_SOLDIER, and NPC_SPIRIT_OF_THE_DAMNED.
Referenced by HandleShardMinionSpawnerSmall(), and SpellHit().
JustDied()
void npc_necrotic_shard::JustDied (Unit *) inline override virtual
Reimplemented from CreatureAI.
    {
        switch (me->GetEntry())
        {
            case NPC_NECROTIC_SHARD:
                if (Creature* shard = me->SummonCreature(NPC_DAMAGED_NECROTIC_SHARD, me->GetPosition(), TEMPSUMMON_MANUAL_DESPAWN))
                {
                    uint32 spellId = _spellCampType ? _spellCampType : static_cast<uint32>(SPELL_CHOOSE_CAMP_TYPE);
                    shard->CastSpell(shard, spellId, true);
                    me->DespawnOrUnsummon();
                }
                break;
            case NPC_DAMAGED_NECROTIC_SHARD:
                // Buff Players.
                DoCastSelf(SPELL_SOUL_REVIVAL, true);
                // Sending the Death Bolt.
                DoCastAOE(SPELL_COMMUNIQUE_CAMP_TO_RELAY_DEATH, true);
                DespawnCultists(); // Despawn remaining Cultists (should never happen).
                DespawnEventDoodads();
                sWorldState->Save(SAVE_ID_SCOURGE_INVASION);
                break;
            default:
                break;
        }
    }
References _spellCampType, DespawnCultists(), DespawnEventDoodads(), Creature::DespawnOrUnsummon(), UnitAI::DoCastAOE(), UnitAI::DoCastSelf(), Object::GetEntry(), Position::GetPosition(), ScriptedAI::me, NPC_DAMAGED_NECROTIC_SHARD, NPC_NECROTIC_SHARD, SAVE_ID_SCOURGE_INVASION, SPELL_CHOOSE_CAMP_TYPE, SPELL_COMMUNIQUE_CAMP_TO_RELAY_DEATH, SPELL_SOUL_REVIVAL, WorldObject::SummonCreature(), sWorldState, and TEMPSUMMON_MANUAL_DESPAWN.
Reset()
void npc_necrotic_shard::Reset () inline override virtual
Reimplemented from UnitAI.
    {
        scheduler.CancelAll();
        ScheduleTasks();
    }
References TaskScheduler::CancelAll(), CreatureAI::scheduler, and ScheduleTasks().
ScheduleCultistSpawnTask()
void npc_necrotic_shard::ScheduleCultistSpawnTask () inline
    {
        scheduler.Schedule(5s, [this](TaskContext context) // Spawn Cultists every 60 minutes.
        {
            me->SetFullHealth();
            DespawnShadowsOfDoom(); // Despawn all remaining Shadows before respawning the Cultists?
            SummonCultists();
            context.Repeat(1h);
        });
    }
References DespawnShadowsOfDoom(), ScriptedAI::me, TaskContext::Repeat(), TaskScheduler::Schedule(), CreatureAI::scheduler, Unit::SetFullHealth(), and SummonCultists().
Referenced by ScheduleTasks().
ScheduleMinionSpawnTask()
void npc_necrotic_shard::ScheduleMinionSpawnTask () inline
    {
        scheduler.Schedule(5s, [this](TaskContext context) // Spawn Minions every 5 seconds.
        {
            HandleShardMinionSpawnerSmall();
            context.Repeat(5s);
        });
    }
References HandleShardMinionSpawnerSmall(), TaskContext::Repeat(), TaskScheduler::Schedule(), and CreatureAI::scheduler.
Referenced by ScheduleTasks(), and SpellHit().
ScheduleTasks()
void npc_necrotic_shard::ScheduleTasks () inline
    {
        if (me->GetEntry() == NPC_NECROTIC_SHARD)
        {
            // Just in case.
            std::list<Creature*> shardList;
            me->GetCreatureListWithEntryInGrid(
                shardList,
                { NPC_NECROTIC_SHARD, NPC_DAMAGED_NECROTIC_SHARD },
                CONTACT_DISTANCE
            );
            for (Creature* shard : shardList)
                if (shard != me)
                    shard->DespawnOnEvade();
            scheduler.Schedule(10s, [this](const TaskContext& /*context*/) // Check if Doodads are spawned 5 seconds after spawn. If not: spawn them
            {
                std::list<GameObject*> objectList;
                me->GetGameObjectListWithEntryInGrid(
                    objectList,
                    {GO_UNDEAD_FIRE, GO_UNDEAD_FIRE_AURA, GO_SKULLPILE_01, GO_SKULLPILE_02, GO_SKULLPILE_03, GO_SKULLPILE_04},
                    50.0f
                );
                for (GameObject* go : objectList)
                    if (go && !go->isSpawned())
                    {
                        go->SetRespawnTime(0);
                        go->Respawn();
                    }
            });
        }
        else if (me->GetEntry() == NPC_DAMAGED_NECROTIC_SHARD)
        {
            UpdateFindersAmount();
            ScheduleMinionSpawnTask();
            ScheduleCultistSpawnTask();
        }
        ScheduleTimedEvent(25s,
            [&]() -> void // Check if there are a summoning circle, otherwise despawn
        {
            if (!GetClosestGameObjectWithEntry(me, GO_SUMMON_CIRCLE, 2.0f))
            {
                DespawnEventDoodads();
                me->DespawnOrUnsummon();
            }
        }, 60s);
    }
References CONTACT_DISTANCE, DespawnEventDoodads(), Creature::DespawnOrUnsummon(), GetClosestGameObjectWithEntry(), WorldObject::GetCreatureListWithEntryInGrid(), Object::GetEntry(), WorldObject::GetGameObjectListWithEntryInGrid(), GO_SKULLPILE_01, GO_SKULLPILE_02, GO_SKULLPILE_03, GO_SKULLPILE_04, GO_SUMMON_CIRCLE, GO_UNDEAD_FIRE, GO_UNDEAD_FIRE_AURA, ScriptedAI::me, NPC_DAMAGED_NECROTIC_SHARD, NPC_NECROTIC_SHARD, TaskScheduler::Schedule(), ScheduleCultistSpawnTask(), ScheduleMinionSpawnTask(), CreatureAI::scheduler, ScriptedAI::ScheduleTimedEvent(), and UpdateFindersAmount().
Referenced by Reset().
SpellHit()
void npc_necrotic_shard::SpellHit (Unit * caster, SpellInfo const * spell) inline override virtual
Reimplemented from CreatureAI.
    {
        switch (spell->Id)
        {
            case SPELL_ZAP_CRYSTAL_CORPSE:
            {
                Creature::DealDamage(me, me, (me->GetMaxHealth() / 4), nullptr, DIRECT_DAMAGE, SPELL_SCHOOL_MASK_NORMAL, nullptr, false);
                _zapCount++;
                if (_zapCount >= 4)
                    me->KillSelf();
                break;
            }
            case SPELL_COMMUNIQUE_RELAY_TO_CAMP:
            {
                me->CastSpell(static_cast<Unit*>(nullptr), SPELL_CAMP_RECEIVES_COMMUNIQUE, true);
                break;
            }
            case SPELL_CHOOSE_CAMP_TYPE:
            {
                _spellCampType = RAND(SPELL_CAMP_TYPE_GHOUL_SKELETON, SPELL_CAMP_TYPE_GHOST_GHOUL, SPELL_CAMP_TYPE_GHOST_SKELETON);
                DoCastSelf(_spellCampType, true);
                break;
            }
            case SPELL_CAMP_RECEIVES_COMMUNIQUE:
            {
                if (!HasCampTypeAura() && me->GetEntry() == NPC_NECROTIC_SHARD)
                {
                    UpdateFindersAmount();
                    DoCastSelf(SPELL_CHOOSE_CAMP_TYPE, true);
                    ScheduleMinionSpawnTask();
                }
                break;
            }
            case SPELL_FIND_CAMP_TYPE:
            {
                // Don't spawn more Minions than finders.
                if (_nearbyFinderCount < HasMinion(me, 60.0f))
                    return;
                static constexpr std::pair<uint32, uint32> auraSpellMap[] = {
                    {SPELL_CAMP_TYPE_GHOST_SKELETON, SPELL_PH_SUMMON_MINION_TRAP_GHOST_SKELETON},
                    {SPELL_CAMP_TYPE_GHOST_GHOUL,    SPELL_PH_SUMMON_MINION_TRAP_GHOST_GHOUL   },
                    {SPELL_CAMP_TYPE_GHOUL_SKELETON, SPELL_PH_SUMMON_MINION_TRAP_GHOUL_SKELETON}
                };
                for (auto const& [aura, spell] : auraSpellMap)
                    if (me->HasAura(aura))
                    {
                        caster->CastSpell(caster, spell, true);
                        break;
                    }
                break;
            }
            default:
                break;
        }
    }
References _nearbyFinderCount, _spellCampType, _zapCount, Unit::CastSpell(), Unit::DealDamage(), DIRECT_DAMAGE, UnitAI::DoCastSelf(), Object::GetEntry(), Unit::GetMaxHealth(), Unit::HasAura(), HasCampTypeAura(), HasMinion(), SpellInfo::Id, Unit::KillSelf(), ScriptedAI::me, NPC_NECROTIC_SHARD, RAND(), ScheduleMinionSpawnTask(), SPELL_CAMP_RECEIVES_COMMUNIQUE, SPELL_CAMP_TYPE_GHOST_GHOUL, SPELL_CAMP_TYPE_GHOST_SKELETON, SPELL_CAMP_TYPE_GHOUL_SKELETON, SPELL_CHOOSE_CAMP_TYPE, SPELL_COMMUNIQUE_RELAY_TO_CAMP, SPELL_FIND_CAMP_TYPE, SPELL_PH_SUMMON_MINION_TRAP_GHOST_GHOUL, SPELL_PH_SUMMON_MINION_TRAP_GHOST_SKELETON, SPELL_PH_SUMMON_MINION_TRAP_GHOUL_SKELETON, SPELL_SCHOOL_MASK_NORMAL, SPELL_ZAP_CRYSTAL_CORPSE, and UpdateFindersAmount().
SpellHitTarget()
void npc_necrotic_shard::SpellHitTarget (Unit * , SpellInfo const * spellInfo) inline override virtual
Reimplemented from CreatureAI.
    {
        if (me->GetEntry() != NPC_DAMAGED_NECROTIC_SHARD)
            return;
        if (spellInfo->Id == SPELL_COMMUNIQUE_CAMP_TO_RELAY_DEATH)
            me->DespawnOrUnsummon();
    }
References Creature::DespawnOrUnsummon(), Object::GetEntry(), SpellInfo::Id, ScriptedAI::me, NPC_DAMAGED_NECROTIC_SHARD, and SPELL_COMMUNIQUE_CAMP_TO_RELAY_DEATH.
SummonCultists()
void npc_necrotic_shard::SummonCultists () inline
    {
        std::list<GameObject*> summonerShieldList;
        me->GetGameObjectListWithEntryInGrid(summonerShieldList, GO_SUMMONER_SHIELD, INSPECT_DISTANCE);
        for (GameObject* const& summonerShield : summonerShieldList)
            summonerShield->DespawnOrUnsummon();
        // We don't have all positions sniffed from the Cultists, so why not using this code which placing them almost perfectly into the circle while B's positions are sometimes way off?
        if (GameObject* go = GetClosestGameObjectWithEntry(me, GO_SUMMON_CIRCLE, CONTACT_DISTANCE))
        {
            for (int i = 0; i < 4; ++i)
            {
                float angle = (float(i) * (M_PI / 2.f)) + go->GetOrientation();
                float x = go->GetPositionX() + 6.95f * std::cos(angle);
                float y = go->GetPositionY() + 6.75f * std::sin(angle);
                float z = go->GetPositionZ() + 5.0f;
                me->UpdateGroundPositionZ(x, y, z);
                me->SummonCreature(NPC_CULTIST_ENGINEER, x, y, z, angle - M_PI, TEMPSUMMON_TIMED_OR_DEAD_DESPAWN, IN_MILLISECONDS * HOUR);
            }
        }
    }
References CONTACT_DISTANCE, GetClosestGameObjectWithEntry(), WorldObject::GetGameObjectListWithEntryInGrid(), GO_SUMMON_CIRCLE, GO_SUMMONER_SHIELD, HOUR, IN_MILLISECONDS, INSPECT_DISTANCE, ScriptedAI::me, NPC_CULTIST_ENGINEER, WorldObject::SummonCreature(), TEMPSUMMON_TIMED_OR_DEAD_DESPAWN, and WorldObject::UpdateGroundPositionZ().
Referenced by ScheduleCultistSpawnTask().
UpdateAI()
void npc_necrotic_shard::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Implements UnitAI.
    {
        scheduler.Update(diff);
    }
References CreatureAI::scheduler, and TaskScheduler::Update().
UpdateFindersAmount()
void npc_necrotic_shard::UpdateFindersAmount () inline
    {
        _nearbyFinderCount = 0;
        std::list<Creature*> finderList;
        me->GetCreatureListWithEntryInGrid(finderList, NPC_SCOURGE_INVASION_MINION_FINDER, 60.0f);
        for (Creature const* finder : finderList)
            if (finder)
                _nearbyFinderCount++;
    }
References _nearbyFinderCount, WorldObject::GetCreatureListWithEntryInGrid(), ScriptedAI::me, and NPC_SCOURGE_INVASION_MINION_FINDER.
Referenced by ScheduleTasks(), and SpellHit().
Member Data Documentation
_nearbyFinderCount
uint32 npc_necrotic_shard::_nearbyFinderCount = 0 private
Referenced by SpellHit(), and UpdateFindersAmount().
_spellCampType
uint32 npc_necrotic_shard::_spellCampType = 0 private
Referenced by JustDied(), and SpellHit().
_zapCount
uint8 npc_necrotic_shard::_zapCount = 0 private
Referenced by SpellHit().
The documentation for this struct was generated from the following file:
azerothcore-wotlk/src/server/scripts/World/scourge_invasion.cpp