AzerothCore Doxygen
ProcChainGuardSimulator Class Reference
Simulates the proc chain guard logic from Unit::TriggerAurasProcOnEvent.
#include "ProcChanceTestHelper.h"
Classes
struct AuraConfig
struct ProcRecord
Public Member Functions
ProcChainGuardSimulator ()
void SimulateTriggerAurasProc (bool triggeringSpellHasDisallowProcEvents, std::vector< AuraConfig > const &auras)
Simulate Unit::TriggerAurasProcOnEvent.
std::vector< ProcRecord > const & GetRecords () const
int32 GetProcDeep () const
bool CanProc () const
Private Member Functions
void SetCantProc (bool apply)
Private Attributes
int32 _procDeep
std::vector< ProcRecord > _records
Detailed Description
Simulates the proc chain guard logic from Unit::TriggerAurasProcOnEvent.
Tracks the m_procDeep counter to verify that:
TRIGGERED_DISALLOW_PROC_EVENTS on the triggering spell disables procs for all auras in the container
SPELL_ATTR3_INSTANT_TARGET_PROCS on individual auras disables procs only during that specific aura's TriggerProcOnEvent call
The counter is properly balanced (returns to 0 after function exits)
Constructor & Destructor Documentation
ProcChainGuardSimulator()
ProcChainGuardSimulator::ProcChainGuardSimulator () inline
: _procDeep(0) {}
Member Function Documentation
CanProc()
bool ProcChainGuardSimulator::CanProc () const inline
{ return _procDeep == 0; }
References _procDeep.
Referenced by SimulateTriggerAurasProc().
GetProcDeep()
int32 ProcChainGuardSimulator::GetProcDeep () const inline
{ return _procDeep; }
References _procDeep.
GetRecords()
std::vector< ProcRecord > const & ProcChainGuardSimulator::GetRecords () const inline
    {
        return _records;
    }
References _records.
SetCantProc()
void ProcChainGuardSimulator::SetCantProc (bool apply) inline private
    {
        if (apply)
            ++_procDeep;
        else
            --_procDeep;
    }
References _procDeep.
Referenced by SimulateTriggerAurasProc().
SimulateTriggerAurasProc()
void ProcChainGuardSimulator::SimulateTriggerAurasProc (bool triggeringSpellHasDisallowProcEvents, std::vector< AuraConfig > const & auras) inline
Simulate Unit::TriggerAurasProcOnEvent.
Parameters
triggeringSpellHasDisallowProcEvents Whether the triggering spell has TRIGGERED_DISALLOW_PROC_EVENTS cast flag
auras List of auras in the proc container
    {
        _records.clear();
        bool const disableProcs = triggeringSpellHasDisallowProcEvents;
        if (disableProcs)
            SetCantProc(true);
        for (auto const& aura : auras)
        {
            if (aura.isRemoved)
                continue;
            if (aura.hasInstantTargetProcs)
                SetCantProc(true);
            // Record CanProc() state during TriggerProcOnEvent
            _records.push_back({
                aura.spellId,
                CanProc(),
                _procDeep
            });
            if (aura.hasInstantTargetProcs)
                SetCantProc(false);
        }
        if (disableProcs)
            SetCantProc(false);
    }
References _procDeep, _records, CanProc(), and SetCantProc().
Referenced by TEST_F().
Member Data Documentation
_procDeep
int32 ProcChainGuardSimulator::_procDeep private
Referenced by CanProc(), GetProcDeep(), SetCantProc(), and SimulateTriggerAurasProc().
_records
std::vector<ProcRecord> ProcChainGuardSimulator::_records private
Referenced by GetRecords(), and SimulateTriggerAurasProc().
The documentation for this class was generated from the following file:
azerothcore-wotlk/src/test/mocks/ProcChanceTestHelper.h