AzerothCore Doxygen
instance_forge_of_souls::instance_forge_of_souls_InstanceScript Struct Reference
Public Member Functions
instance_forge_of_souls_InstanceScript (Map *map)
void OnPlayerEnter (Player *player) override
void OnCreatureCreate (Creature *creature) override
void HandleOutro ()
bool SetBossState (uint32 type, EncounterState state) override
bool CheckAchievementCriteriaMeet (uint32 criteria_id, Player const *, Unit const *, uint32) override
Public Member Functions inherited from InstanceScript
InstanceScript (Map *map)
~InstanceScript () override
virtual void Initialize ()
virtual void Load (char const *data)
virtual void CreatureLooted (Creature *, LootType)
virtual std::string GetSaveData ()
void SaveToDB ()
virtual void Update (uint32)
virtual bool IsEncounterInProgress () const
void OnCreatureCreate (Creature *creature) override
void OnCreatureRemove (Creature *creature) override
void OnGameObjectCreate (GameObject *go) override
void OnGameObjectRemove (GameObject *go) override
ObjectGuid GetObjectGuid (uint32 type) const
ObjectGuid GetGuidData (uint32 type) const override
Creature * GetCreature (uint32 type)
GameObject * GetGameObject (uint32 type)
virtual void OnPlayerLeave (Player *)
virtual void OnPlayerAreaUpdate (Player *, uint32, uint32)
virtual void OnPlayerInWaterStateUpdate (Player *, bool)
void HandleGameObject (ObjectGuid guid, bool open, GameObject *go=nullptr)
Open or close a GameObject by GUID.
void HandleGameObject (uint32 type, bool open)
Open or close a GameObject registered via LoadObjectData.
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
void DoRespawnGameObject (uint32 type)
void DoRespawnCreature (ObjectGuid guid, bool force=false)
void DoRespawnCreature (uint32 type, bool force=false)
void DoUpdateWorldState (uint32 worldstateId, uint32 worldstateValue)
void DoSendNotifyToInstance (char const *format,...)
void DoUpdateAchievementCriteria (AchievementCriteriaTypes type, uint32 miscValue1=0, uint32 miscValue2=0, Unit *unit=nullptr)
void DoStartTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoStopTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoRemoveAurasDueToSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayer (Player *player, uint32 spell, bool includePets, bool includeControlled)
bool ServerAllowsTwoSideGroups ()
EncounterState GetBossState (uint32 id) const
CreatureBoundary const * GetBossBoundary (uint32 id) const
BossInfo const * GetBossInfo (uint32 id) const
uint32 GetPersistentData (uint32 index) const
void StorePersistentData (uint32 index, uint32 data)
virtual bool CheckRequiredBosses (uint32, Player const *=nullptr) const
bool _SkipCheckRequiredBosses (Player const *player=nullptr) const
void SetCompletedEncountersMask (uint32 newMask, bool save)
uint32 GetCompletedEncounterMask () const
void SendEncounterUnit (uint32 type, Unit *unit=nullptr, uint8 param1=0, uint8 param2=0)
virtual void FillInitialWorldStates (WorldPackets::WorldState::InitWorldStates &)
uint32 GetEncounterCount () const
void MarkAreaTriggerDone (uint32 id)
void ResetAreaTriggerDone (uint32 id)
bool IsAreaTriggerDone (uint32 id) const
virtual void DoAction (int32)
void DoForAllMinions (uint32 id, std::function< void(Creature *)> exec)
void StoreGameObjectState (ObjectGuid::LowType spawnId, uint8 state)
uint8 GetStoredGameObjectState (ObjectGuid::LowType spawnId) const
void LoadInstanceSavedGameobjectStateData ()
bool IsBossDone (uint32 bossId) const
bool AllBossesDone () const
bool AllBossesDone (std::initializer_list< uint32 > bossIds) const
TeamId GetTeamIdInInstance () const
void SetTeamIdInInstance (TeamId teamId)
bool IsTwoFactionInstance () const
Public Member Functions inherited from ZoneScript
ZoneScript ()
virtual ~ZoneScript ()
virtual uint32 GetCreatureEntry (ObjectGuid::LowType, CreatureData const *data)
virtual uint32 GetGameObjectEntry (ObjectGuid::LowType, uint32 entry)
virtual void OnUnitDeath (Unit *)
virtual void OnCreatureEvade (Creature *)
virtual void SetGuidData (uint32, ObjectGuid)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void ProcessEvent (WorldObject *, uint32)
Public Attributes
ObjectGuid LeaderFirstGUID
ObjectGuid LeaderSecondGUID
ObjectGuid GuardFirstGUID
ObjectGuid GuardSecondGUID
Public Attributes inherited from InstanceScript
Map * instance
TaskScheduler scheduler
Additional Inherited Members
Static Public Member Functions inherited from InstanceScript
static std::string GetBossStateName (uint8 state)
Protected Member Functions inherited from InstanceScript
void SetHeaders (std::string const &dataHeaders)
void SetBossNumber (uint32 number)
void SetPersistentDataCount (uint32 number)
void LoadBossBoundaries (BossBoundaryData const &data)
void LoadDoorData (DoorData const *data)
void LoadMinionData (MinionData const *data)
void LoadObjectData (ObjectData const *creatureData, ObjectData const *gameObjectData)
void LoadSummonData (ObjectData const *data)
void SetSummoner (Creature *creature)
void AddObject (Creature *obj, bool add=true)
void RemoveObject (Creature *obj)
void AddObject (GameObject *obj, bool add=true)
void RemoveObject (GameObject *obj)
void AddObject (WorldObject *obj, uint32 type, bool add=true)
void RemoveObject (WorldObject *obj, uint32 type)
void AddDoor (GameObject *door, bool add=true)
void RemoveDoor (GameObject *door)
void AddMinion (Creature *minion, bool add=true)
void RemoveMinion (Creature *minion)
void UpdateDoorState (GameObject *door)
void UpdateMinionState (Creature *minion, EncounterState state)
bool ReadSaveDataHeaders (std::istringstream &data)
void ReadSaveDataBossStates (std::istringstream &data)
void ReadSavePersistentData (std::istringstream &data)
virtual void ReadSaveDataMore (std::istringstream &)
void WriteSaveDataHeaders (std::ostringstream &data)
void WriteSaveDataBossStates (std::ostringstream &data)
void WritePersistentData (std::ostringstream &data)
virtual void WriteSaveDataMore (std::ostringstream &)
Detailed Description
Constructor & Destructor Documentation
instance_forge_of_souls_InstanceScript()
instance_forge_of_souls::instance_forge_of_souls_InstanceScript::instance_forge_of_souls_InstanceScript (Map * map) inline
                                                         : InstanceScript(map)
        {
            SetHeaders(DataHeader);
            SetBossNumber(MAX_ENCOUNTER);
            LoadObjectData(creatureData, nullptr);
            LoadBossBoundaries(boundaries);
        }
References boundaries, creatureData, DataHeader, InstanceScript::LoadBossBoundaries(), InstanceScript::LoadObjectData(), MAX_ENCOUNTER, InstanceScript::SetBossNumber(), and InstanceScript::SetHeaders().
Member Function Documentation
CheckAchievementCriteriaMeet()
bool instance_forge_of_souls::instance_forge_of_souls_InstanceScript::CheckAchievementCriteriaMeet (uint32 criteria_id, Player const * , Unit const * , uint32) inline override virtual
Reimplemented from InstanceScript.
        {
            switch (criteria_id)
            {
                case ACHIEV_CRITERIA_SOUL_POWER:
                    if (Creature* bronjahm = GetCreature(DATA_BRONJAHM))
                    {
                        std::list<Creature*> fragments;
                        bronjahm->GetCreaturesWithEntryInRange(fragments, 200.0f, NPC_CORRUPTED_SOUL_FRAGMENT);
                        return std::count_if(fragments.begin(), fragments.end(),
                            [](Creature const* fragment) { return fragment->IsAlive(); }) >= SOUL_POWER_FRAGMENT_COUNT;
                    }
                    break;
                case ACHIEV_CRITERIA_THREE_FACED:
                    if (Creature* devourer = GetCreature(DATA_DEVOURER))
                        return devourer->AI()->GetData(1) != 0;
                    break;
            }
            return false;
        }
References ACHIEV_CRITERIA_SOUL_POWER, ACHIEV_CRITERIA_THREE_FACED, DATA_BRONJAHM, DATA_DEVOURER, InstanceScript::GetCreature(), NPC_CORRUPTED_SOUL_FRAGMENT, and SOUL_POWER_FRAGMENT_COUNT.
HandleOutro()
void instance_forge_of_souls::instance_forge_of_souls_InstanceScript::HandleOutro () inline
        {
            if (!LeaderSecondGUID || !instance->GetCreature(LeaderSecondGUID))
                if (Creature* leader = instance->SummonCreature(NPC_SYLVANAS_PART2, outroSpawnPoint))
                    if (Creature* boss = GetCreature(DATA_DEVOURER))
                    {
                        float angle = boss->GetAngle(leader);
                        leader->GetMotionMaster()->MovePoint(1, boss->GetPositionX() + 10.0f * cos(angle), boss->GetPositionY() + 10.0f * std::sin(angle), boss->GetPositionZ());
                    }
            if (GetTeamIdInInstance() < TEAM_NEUTRAL) // Shouldn't happen, but just in case.
            {
                for (int8 i = 0; outroPositions[i].entry[GetTeamIdInInstance()] != 0; ++i)
                    if (Creature* summon = instance->SummonCreature(outroPositions[i].entry[GetTeamIdInInstance()], outroPositions[i].startPosition))
                        summon->GetMotionMaster()->MoveWaypoint(outroPositions[i].pathId, false);
            }
        }
References DATA_DEVOURER, outroPosition::entry, Map::GetCreature(), InstanceScript::GetCreature(), InstanceScript::GetTeamIdInInstance(), InstanceScript::instance, LeaderSecondGUID, NPC_SYLVANAS_PART2, outroPositions, outroSpawnPoint, Map::SummonCreature(), and TEAM_NEUTRAL.
Referenced by SetBossState().
OnCreatureCreate()
void instance_forge_of_souls::instance_forge_of_souls_InstanceScript::OnCreatureCreate (Creature * creature) inline override virtual
Reimplemented from ZoneScript.
        {
            InstanceScript::OnCreatureCreate(creature);
            switch (creature->GetEntry())
            {
                case NPC_SYLVANAS_PART1:
                    if (GetTeamIdInInstance() == TEAM_ALLIANCE)
                        creature->UpdateEntry(NPC_JAINA_PART1);
                    LeaderFirstGUID = creature->GetGUID();
                    if (AllBossesDone())
                        creature->SetVisible(false);
                    break;
                case NPC_SYLVANAS_PART2:
                    if (GetTeamIdInInstance() == TEAM_ALLIANCE)
                        creature->UpdateEntry(NPC_JAINA_PART2);
                    LeaderSecondGUID = creature->GetGUID();
                    break;
                case NPC_LORALEN:
                    if (GetTeamIdInInstance() == TEAM_ALLIANCE)
                        creature->UpdateEntry(NPC_ELANDRA);
                    if (!GuardFirstGUID)
                    {
                        GuardFirstGUID = creature->GetGUID();
                        if (AllBossesDone())
                            creature->SetVisible(false);
                    }
                    break;
                case NPC_KALIRA:
                    if (GetTeamIdInInstance() == TEAM_ALLIANCE)
                        creature->UpdateEntry(NPC_KORELN);
                    if (!GuardSecondGUID)
                    {
                        GuardSecondGUID = creature->GetGUID();
                        if (AllBossesDone())
                            creature->SetVisible(false);
                    }
                    break;
            }
        }
References InstanceScript::AllBossesDone(), Object::GetEntry(), Object::GetGUID(), InstanceScript::GetTeamIdInInstance(), GuardFirstGUID, GuardSecondGUID, LeaderFirstGUID, LeaderSecondGUID, NPC_ELANDRA, NPC_JAINA_PART1, NPC_JAINA_PART2, NPC_KALIRA, NPC_KORELN, NPC_LORALEN, NPC_SYLVANAS_PART1, NPC_SYLVANAS_PART2, InstanceScript::OnCreatureCreate(), Unit::SetVisible(), TEAM_ALLIANCE, and Creature::UpdateEntry().
OnPlayerEnter()
void instance_forge_of_souls::instance_forge_of_souls_InstanceScript::OnPlayerEnter (Player * player) inline override virtual
Reimplemented from InstanceScript.
        {
            InstanceScript::OnPlayerEnter(player);
            // this will happen only after crash and loading the instance from db
            if (AllBossesDone() && (!LeaderSecondGUID || !instance->GetCreature(LeaderSecondGUID)))
            {
                Position pos = {5658.15f, 2502.564f, 708.83f, 0.885207f};
                instance->SummonCreature(NPC_SYLVANAS_PART2, pos);
            }
        }
References InstanceScript::AllBossesDone(), Map::GetCreature(), InstanceScript::instance, LeaderSecondGUID, NPC_SYLVANAS_PART2, InstanceScript::OnPlayerEnter(), and Map::SummonCreature().
SetBossState()
bool instance_forge_of_souls::instance_forge_of_souls_InstanceScript::SetBossState (uint32 type, EncounterState state) inline override virtual
Reimplemented from InstanceScript.
        {
            if (!InstanceScript::SetBossState(type, state))
                return false;
            if (state == DONE && AllBossesDone())
                HandleOutro();
            return true;
        }
References InstanceScript::AllBossesDone(), DONE, HandleOutro(), and InstanceScript::SetBossState().
Member Data Documentation
GuardFirstGUID
ObjectGuid instance_forge_of_souls::instance_forge_of_souls_InstanceScript::GuardFirstGUID
Referenced by OnCreatureCreate().
GuardSecondGUID
ObjectGuid instance_forge_of_souls::instance_forge_of_souls_InstanceScript::GuardSecondGUID
Referenced by OnCreatureCreate().
LeaderFirstGUID
ObjectGuid instance_forge_of_souls::instance_forge_of_souls_InstanceScript::LeaderFirstGUID
Referenced by OnCreatureCreate().
LeaderSecondGUID
ObjectGuid instance_forge_of_souls::instance_forge_of_souls_InstanceScript::LeaderSecondGUID
Referenced by HandleOutro(), OnCreatureCreate(), and OnPlayerEnter().
The documentation for this struct was generated from the following file:
azerothcore-wotlk/src/server/scripts/Northrend/FrozenHalls/ForgeOfSouls/instance_forge_of_souls.cpp