AzerothCore Doxygen
spell_chapter2_persuasive_strike Class Reference
Private Member Functions
PrepareSpellScript (spell_chapter2_persuasive_strike)
bool Load () override
void HandleHit (SpellEffIndex)
void Register () override
Additional Inherited Members
Public Member Functions inherited from SpellScript
bool _Validate (SpellInfo const *entry) override
bool _Load (Spell *spell)
void _InitHit ()
bool _IsEffectPrevented (SpellEffIndex effIndex)
bool _IsDefaultEffectPrevented (SpellEffIndex effIndex)
void _PrepareScriptCall (SpellScriptHookType hookType)
void _FinishScriptCall ()
bool IsInCheckCastHook () const
bool IsInTargetHook () const
bool IsInHitPhase () const
bool IsInEffectHook () const
Unit * GetCaster ()
Unit * GetOriginalCaster ()
SpellInfo const * GetSpellInfo ()
SpellValue const * GetSpellValue ()
WorldLocation const * GetExplTargetDest ()
void SetExplTargetDest (WorldLocation &loc)
WorldObject * GetExplTargetWorldObject ()
Unit * GetExplTargetUnit ()
GameObject * GetExplTargetGObj ()
Item * GetExplTargetItem ()
Unit * GetHitUnit ()
Creature * GetHitCreature ()
Player * GetHitPlayer ()
Item * GetHitItem ()
GameObject * GetHitGObj ()
WorldLocation * GetHitDest ()
int32 GetHitDamage ()
void SetHitDamage (int32 damage)
void PreventHitDamage ()
int32 GetHitHeal ()
void SetHitHeal (int32 heal)
void PreventHitHeal ()
Spell * GetSpell ()
Aura * GetHitAura ()
void PreventHitAura ()
void PreventHitEffect (SpellEffIndex effIndex)
void PreventHitDefaultEffect (SpellEffIndex effIndex)
int32 GetEffectValue () const
void SetEffectValue (int32 value)
Item * GetCastItem ()
void CreateItem (uint32 effIndex, uint32 itemId)
SpellInfo const * GetTriggeringSpell ()
void FinishCast (SpellCastResult result)
void Cancel ()
void SetCustomCastResultMessage (SpellCustomErrors result)
Public Member Functions inherited from _SpellScript
_SpellScript ()
virtual ~_SpellScript ()
virtual void _Register ()
virtual void _Unload ()
virtual void _Init (std::string const *scriptname, uint32 spellId)
std::string const * _GetScriptName () const
virtual bool Validate (SpellInfo const *)
virtual void Unload ()
Static Public Member Functions inherited from _SpellScript
static bool ValidateSpellInfo (std::initializer_list< uint32 > spellIds)
template<class T >
static bool ValidateSpellInfo (T const &spellIds)
Public Attributes inherited from SpellScript
HookList< CastHandler > BeforeCast
HookList< CastHandler > OnCast
HookList< CastHandler > AfterCast
HookList< CheckCastHandler > OnCheckCast
HookList< EffectHandler > OnEffectLaunch
HookList< EffectHandler > OnEffectLaunchTarget
HookList< EffectHandler > OnEffectHit
HookList< EffectHandler > OnEffectHitTarget
HookList< BeforeHitHandler > BeforeHit
HookList< HitHandler > OnHit
HookList< HitHandler > AfterHit
HookList< ObjectAreaTargetSelectHandler > OnObjectAreaTargetSelect
HookList< ObjectTargetSelectHandler > OnObjectTargetSelect
HookList< DestinationTargetSelectHandler > OnDestinationTargetSelect
Protected Attributes inherited from _SpellScript
uint8 m_currentScriptState
std::string const * m_scriptName
uint32 m_scriptSpellId
Detailed Description
Member Function Documentation
HandleHit()
void spell_chapter2_persuasive_strike::HandleHit (SpellEffIndex) inline private
    {
        Creature* creature = GetHitCreature();
        Player* player = GetCaster()->ToPlayer();
        if (!creature || !player)
            return;
        if (!creature->EntryEquals(NPC_SCARLET_PREACHER, NPC_SCARLET_COMMANDER, NPC_SCARLET_CRUSADER, NPC_SCARLET_MARKSMAN, NPC_SCARLET_LORD_MCCREE))
            return;
        sCreatureTextMgr->SendChat(creature, SAY_PERSUADE_RAND, nullptr, CHAT_MSG_ADDON, LANG_ADDON, TEXT_RANGE_NORMAL, 0, TEAM_NEUTRAL, false, player);
        if (roll_chance_f(30.0f))
        {
            creature->CombatStop(true);
            creature->GetMotionMaster()->MoveIdle();
            creature->SetImmuneToPC(true);
            creature->SetUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
            creature->SetReactState(REACT_PASSIVE);
            creature->AI()->Talk(SAY_PERSUADED1, 8s);
            creature->AI()->Talk(SAY_PERSUADED2, 16s);
            creature->AI()->Talk(SAY_PERSUADED3, 24s);
            creature->AI()->Talk(SAY_PERSUADED4, 32s);
            creature->m_Events.AddEventAtOffset([creature, player]
            {
                if (player)
                    sCreatureTextMgr->SendChat(creature, SAY_PERSUADED5, nullptr, CHAT_MSG_ADDON, LANG_ADDON, TEXT_RANGE_NORMAL, 0, TEAM_NEUTRAL, false, player);
            }, 40s);
            creature->m_Events.AddEventAtOffset([creature, player]
            {
                creature->AI()->Talk(SAY_PERSUADED6);
                if (player)
                {
                    Unit::Kill(player, creature);
                    player->GroupEventHappens(QUEST_HOW_TO_WIN_FRIENDS, creature);
                }
            }, 48s);
        }
        else
            creature->AI()->Talk(SAY_CRUSADER, 1s);
    }
References EventProcessor::AddEventAtOffset(), Creature::AI(), CHAT_MSG_ADDON, Unit::CombatStop(), Object::EntryEquals(), SpellScript::GetCaster(), SpellScript::GetHitCreature(), Unit::GetMotionMaster(), Player::GroupEventHappens(), Unit::Kill(), LANG_ADDON, WorldObject::m_Events, MotionMaster::MoveIdle(), NPC_SCARLET_COMMANDER, NPC_SCARLET_CRUSADER, NPC_SCARLET_LORD_MCCREE, NPC_SCARLET_MARKSMAN, NPC_SCARLET_PREACHER, QUEST_HOW_TO_WIN_FRIENDS, REACT_PASSIVE, roll_chance_f(), SAY_CRUSADER, SAY_PERSUADE_RAND, SAY_PERSUADED1, SAY_PERSUADED2, SAY_PERSUADED3, SAY_PERSUADED4, SAY_PERSUADED5, SAY_PERSUADED6, sCreatureTextMgr, Unit::SetImmuneToPC(), Creature::SetReactState(), Unit::SetUnitFlag(), CreatureAI::Talk(), TEAM_NEUTRAL, TEXT_RANGE_NORMAL, Object::ToPlayer(), and UNIT_FLAG_NON_ATTACKABLE.
Referenced by Register().
Load()
bool spell_chapter2_persuasive_strike::Load () inline override private virtual
Reimplemented from _SpellScript.
    {
        return GetCaster() && GetCaster()->IsPlayer()
            && GetCaster()->ToPlayer()->GetQuestStatus(QUEST_HOW_TO_WIN_FRIENDS) == QUEST_STATUS_INCOMPLETE;
    }
References SpellScript::GetCaster(), Player::GetQuestStatus(), Object::IsPlayer(), QUEST_HOW_TO_WIN_FRIENDS, QUEST_STATUS_INCOMPLETE, and Object::ToPlayer().
PrepareSpellScript()
spell_chapter2_persuasive_strike::PrepareSpellScript (spell_chapter2_persuasive_strike) private
Register()
void spell_chapter2_persuasive_strike::Register () inline override private virtual
Implements _SpellScript.
    {
        OnEffectHitTarget += SpellEffectFn(spell_chapter2_persuasive_strike::HandleHit, EFFECT_0, SPELL_EFFECT_DUMMY);
    }
References EFFECT_0, HandleHit(), SpellScript::OnEffectHitTarget, SPELL_EFFECT_DUMMY, and SpellEffectFn.
The documentation for this class was generated from the following file:
azerothcore-wotlk/src/server/scripts/EasternKingdoms/ScarletEnclave/chapter2.cpp