AzerothCore Doxygen
go_jotunheim_cage Class Reference
Public Member Functions
go_jotunheim_cage ()
bool OnGossipHello (Player *player, GameObject *go) override
Public Member Functions inherited from GameObjectScript
bool IsDatabaseBound () const override
virtual bool OnGossipSelect (Player *, GameObject *, uint32, uint32)
virtual bool OnGossipSelectCode (Player *, GameObject *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, GameObject *, Quest const *)
virtual bool OnQuestReward (Player *, GameObject *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, GameObject *)
virtual void OnDestroyed (GameObject *, Player *)
virtual void OnDamaged (GameObject *, Player *)
virtual void OnModifyHealth (GameObject *, Unit *, int32 &, SpellInfo const *)
virtual void OnLootStateChanged (GameObject *, uint32, Unit *)
virtual void OnGameObjectStateChanged (GameObject *, uint32)
virtual GameObjectAI * GetAI (GameObject *) const
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
uint16 GetTotalAvailableHooks ()
Public Member Functions inherited from UpdatableScript< GameObject >
virtual void OnUpdate (GameObject *, uint32)
Additional Inherited Members
Protected Member Functions inherited from GameObjectScript
GameObjectScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name, uint16 totalAvailableHooks=0)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< GameObject >
UpdatableScript ()=default
Detailed Description
Constructor & Destructor Documentation
go_jotunheim_cage()
go_jotunheim_cage::go_jotunheim_cage () inline
: GameObjectScript("go_jotunheim_cage") { }
Member Function Documentation
OnGossipHello()
bool go_jotunheim_cage::OnGossipHello (Player * player, GameObject * go) inline override virtual
Reimplemented from GameObjectScript.
    {
        go->UseDoorOrButton();
        Creature* pPrisoner = go->FindNearestCreature(NPC_EBON_BLADE_PRISONER_HUMAN, 5.0f, true);
        if (!pPrisoner)
        {
            pPrisoner = go->FindNearestCreature(NPC_EBON_BLADE_PRISONER_TROLL, 5.0f, true);
            if (!pPrisoner)
            {
                pPrisoner = go->FindNearestCreature(NPC_EBON_BLADE_PRISONER_ORC, 5.0f, true);
                if (!pPrisoner)
                    pPrisoner = go->FindNearestCreature(NPC_EBON_BLADE_PRISONER_NE, 5.0f, true);
            }
        }
        if (!pPrisoner || !pPrisoner->IsAlive())
            return false;
        pPrisoner->DespawnOrUnsummon();
        player->KilledMonsterCredit(NPC_EBON_BLADE_PRISONER_HUMAN);
        switch (pPrisoner->GetEntry())
        {
            case NPC_EBON_BLADE_PRISONER_HUMAN:
                player->CastSpell(player, SPELL_SUMMON_BLADE_KNIGHT_H, true);
                break;
            case NPC_EBON_BLADE_PRISONER_NE:
                player->CastSpell(player, SPELL_SUMMON_BLADE_KNIGHT_NE, true);
                break;
            case NPC_EBON_BLADE_PRISONER_TROLL:
                player->CastSpell(player, SPELL_SUMMON_BLADE_KNIGHT_TROLL, true);
                break;
            case NPC_EBON_BLADE_PRISONER_ORC:
                player->CastSpell(player, SPELL_SUMMON_BLADE_KNIGHT_ORC, true);
                break;
        }
        return true;
    }
References Unit::CastSpell(), Creature::DespawnOrUnsummon(), WorldObject::FindNearestCreature(), Object::GetEntry(), Unit::IsAlive(), Player::KilledMonsterCredit(), NPC_EBON_BLADE_PRISONER_HUMAN, NPC_EBON_BLADE_PRISONER_NE, NPC_EBON_BLADE_PRISONER_ORC, NPC_EBON_BLADE_PRISONER_TROLL, SPELL_SUMMON_BLADE_KNIGHT_H, SPELL_SUMMON_BLADE_KNIGHT_NE, SPELL_SUMMON_BLADE_KNIGHT_ORC, SPELL_SUMMON_BLADE_KNIGHT_TROLL, and GameObject::UseDoorOrButton().
The documentation for this class was generated from the following file:
azerothcore-wotlk/src/server/scripts/World/go_scripts.cpp