AzerothCore Doxygen
npc_oculus_drake::npc_oculus_drakeAI Struct Reference
Public Member Functions
npc_oculus_drakeAI (Creature *creature)
void IsSummonedBy (WorldObject *summoner) override
void MovementInform (uint32 type, uint32 id) override
void PassengerBoarded (Unit *passenger, int8, bool add) override
== Fields =======================================
void SpellHitTarget (Unit *target, SpellInfo const *spell) override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
Public Member Functions inherited from VehicleAI
VehicleAI (Creature *creature)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void MoveInLineOfSight (Unit *) override
void AttackStart (Unit *) override
void OnCharmed (bool apply) override
Called when unit is charmed.
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void PathEndReached (uint32)
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void Reset ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Public Attributes
InstanceScript * m_pInstance
bool JustSummoned
uint16 despawnTimer
Additional Inherited Members
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from VehicleAI
static int32 Permissible (Creature const *creature)
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
npc_oculus_drakeAI()
npc_oculus_drake::npc_oculus_drakeAI::npc_oculus_drakeAI (Creature * creature) inline
                                               : VehicleAI(creature)
        {
            m_pInstance = me->GetInstanceScript();
            JustSummoned = true;
        }
References WorldObject::GetInstanceScript(), JustSummoned, m_pInstance, and CreatureAI::me.
Member Function Documentation
IsSummonedBy()
void npc_oculus_drake::npc_oculus_drakeAI::IsSummonedBy (WorldObject * summoner) inline override virtual
Reimplemented from CreatureAI.
        {
            if (!summoner->IsPlayer())
            {
                return;
            }
            if (m_pInstance->GetBossState(DATA_EREGOS) == IN_PROGRESS)
                if (Creature* eregos = me->FindNearestCreature(NPC_EREGOS, 450.0f, true))
                    eregos->DespawnOrUnsummon(); // On retail this kills abusive call of drake during engaged Eregos
            me->SetFacingToObject(summoner);
            switch (me->GetEntry())
            {
                case NPC_RUBY_DRAKE:
                    me->CastSpell(summoner->ToUnit(), SPELL_RIDE_RUBY_DRAKE_QUE);
                    break;
                case NPC_EMERALD_DRAKE:
                    me->CastSpell(summoner->ToUnit(), SPELL_RIDE_EMERALD_DRAKE_QUE);
                    break;
                case NPC_AMBER_DRAKE:
                    me->CastSpell(summoner->ToUnit(), SPELL_RIDE_AMBER_DRAKE_QUE);
                    break;
                default:
                    return;
            }
            Position pos = summoner->GetPosition();
            me->GetMotionMaster()->MovePoint(POINT_LAND, pos);
        }
References Unit::CastSpell(), DATA_EREGOS, WorldObject::FindNearestCreature(), InstanceScript::GetBossState(), Object::GetEntry(), Unit::GetMotionMaster(), Position::GetPosition(), IN_PROGRESS, Object::IsPlayer(), m_pInstance, CreatureAI::me, MotionMaster::MovePoint(), NPC_AMBER_DRAKE, NPC_EMERALD_DRAKE, NPC_EREGOS, NPC_RUBY_DRAKE, POINT_LAND, Unit::SetFacingToObject(), SPELL_RIDE_AMBER_DRAKE_QUE, SPELL_RIDE_EMERALD_DRAKE_QUE, SPELL_RIDE_RUBY_DRAKE_QUE, and Object::ToUnit().
MovementInform()
void npc_oculus_drake::npc_oculus_drakeAI::MovementInform (uint32 type, uint32 id) inline override virtual
Reimplemented from CreatureAI.
        {
            if (type == POINT_MOTION_TYPE && id == POINT_LAND)
                me->SetDisableGravity(false); // Needed this for proper animation after spawn, the summon in air fall to ground bug leave no other option for now, if this isn't used the drake will only walk on move.
        }
References CreatureAI::me, POINT_LAND, POINT_MOTION_TYPE, and Creature::SetDisableGravity().
PassengerBoarded()
void npc_oculus_drake::npc_oculus_drakeAI::PassengerBoarded (Unit * , int8 , bool) inline override virtual
== Fields =======================================
Reimplemented from CreatureAI.
        {
            if (!passenger->IsPlayer())
                return;
            if (add)
            {
                despawnTimer = 0;
            }
            else
            {
                me->DespawnOrUnsummon(2050);
                me->SetOrientation(2.5f);
                me->SetSpeedRate(MOVE_FLIGHT, 1.0f);
                Position pos = me->GetPosition();
                Position offset = { 10.0f, 10.0f, 12.0f, 0.0f };
                pos.RelocateOffset(offset);
                me->SetDisableGravity(true);
                me->GetMotionMaster()->MovePoint(POINT_TAKE_OFF, pos);
            }
        }
References Creature::DespawnOrUnsummon(), despawnTimer, Unit::GetMotionMaster(), Position::GetPosition(), Object::IsPlayer(), CreatureAI::me, MOVE_FLIGHT, MotionMaster::MovePoint(), POINT_TAKE_OFF, Position::RelocateOffset(), Creature::SetDisableGravity(), Position::SetOrientation(), and Unit::SetSpeedRate().
SpellHitTarget()
void npc_oculus_drake::npc_oculus_drakeAI::SpellHitTarget (Unit * target, SpellInfo const * spell) inline override virtual
Reimplemented from CreatureAI.
        {
            for( uint8 i = 0; i < 8; ++i )
                if (me->m_spells[i] == spell->Id)
                {
                    if (target && target->IsAlive() && !target->CanFly() && target->IsHostileTo(me) && !spell->IsTargetingArea())
                    {
                        if (Unit* charmer = me->GetCharmer())
                            Unit::Kill(charmer, charmer, false);
                    }
                    break;
                }
        }
References Unit::CanFly(), Unit::GetCharmer(), SpellInfo::Id, Unit::IsAlive(), Unit::IsHostileTo(), SpellInfo::IsTargetingArea(), Unit::Kill(), Creature::m_spells, and CreatureAI::me.
UpdateAI()
void npc_oculus_drake::npc_oculus_drakeAI::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Implements UnitAI.
        {
            if (JustSummoned)
            {
                despawnTimer = 1;
                JustSummoned = false;
                if (m_pInstance)
                {
                    if (!m_pInstance->IsEncounterInProgress() || m_pInstance->GetData(DATA_EREGOS) == IN_PROGRESS)
                    {
                        if (me->GetVehicleKit() && me->IsSummon())
                            if (!me->GetVehicleKit()->GetPassenger(0))
{
                                if (m_pInstance->GetData(DATA_UROM) == DONE)
{
                                    switch (me->GetEntry())
{
                                        case 27692:
                                            me->m_spells[5] = 50344;
                                            break;
                                        case 27755:
                                            me->m_spells[5] = 49592;
                                            break;
                                        case 27756:
                                            me->m_spells[5] = 50253;
                                            break;
                                    }
                                }
                            }
                    }
                    else
                    {
                        me->DespawnOrUnsummon(2050);
                        me->SetOrientation(2.5f);
                        me->SetSpeedRate(MOVE_FLIGHT, 1.0f);
                        Position pos = me->GetPosition();
                        Position offset = { 10.0f, 10.0f, 12.0f, 0.0f };
                        pos.RelocateOffset(offset);
                        me->SetDisableGravity(true);
                        me->GetMotionMaster()->MovePoint(POINT_TAKE_OFF, pos);
                        return;
                    }
                }
            }
            if (despawnTimer)
            {
                if (despawnTimer >= 5000)
                {
                    me->DespawnOrUnsummon(2050);
                    me->SetOrientation(2.5f);
                    Position pos = me->GetPosition();
                    Position offset = { 10.0f, 10.0f, 12.0f, 0.0f };
                    pos.RelocateOffset(offset);
                    return;
                }
                else
                    despawnTimer += diff;
            }
            VehicleAI::UpdateAI(diff);
        }
References DATA_EREGOS, DATA_UROM, Creature::DespawnOrUnsummon(), despawnTimer, DONE, ZoneScript::GetData(), Object::GetEntry(), Unit::GetMotionMaster(), Vehicle::GetPassenger(), Position::GetPosition(), Unit::GetVehicleKit(), IN_PROGRESS, InstanceScript::IsEncounterInProgress(), Unit::IsSummon(), JustSummoned, m_pInstance, Creature::m_spells, CreatureAI::me, MOVE_FLIGHT, MotionMaster::MovePoint(), POINT_TAKE_OFF, Position::RelocateOffset(), Creature::SetDisableGravity(), Position::SetOrientation(), Unit::SetSpeedRate(), and VehicleAI::UpdateAI().
Member Data Documentation
despawnTimer
uint16 npc_oculus_drake::npc_oculus_drakeAI::despawnTimer
Referenced by PassengerBoarded(), and UpdateAI().
JustSummoned
bool npc_oculus_drake::npc_oculus_drakeAI::JustSummoned
Referenced by npc_oculus_drakeAI(), and UpdateAI().
m_pInstance
InstanceScript* npc_oculus_drake::npc_oculus_drakeAI::m_pInstance
Referenced by IsSummonedBy(), npc_oculus_drakeAI(), and UpdateAI().
The documentation for this struct was generated from the following file:
azerothcore-wotlk/src/server/scripts/Northrend/Nexus/Oculus/oculus.cpp