AzerothCore Doxygen
LuaCreature Namespace Reference
Enumerations
enum SelectAggroTarget {
SELECT_TARGET_RANDOM = 0 ,
SELECT_TARGET_TOPAGGRO ,
SELECT_TARGET_BOTTOMAGGRO ,
SELECT_TARGET_NEAREST ,
SELECT_TARGET_FARTHEST
}
Functions
int IsRegeneratingHealth (lua_State *L, Creature *creature)
int IsReputationGainDisabled (lua_State *L, Creature *creature)
int CanCompleteQuest (lua_State *L, Creature *creature)
int IsTargetableForAttack (lua_State *L, Creature *creature)
int CanAssistTo (lua_State *L, Creature *creature)
int HasSearchedAssistance (lua_State *L, Creature *creature)
int IsTappedBy (lua_State *L, Creature *creature)
int HasLootRecipient (lua_State *L, Creature *creature)
int CanAggro (lua_State *L, Creature *creature)
int CanSwim (lua_State *L, Creature *creature)
int CanWalk (lua_State *L, Creature *creature)
int IsInEvadeMode (lua_State *L, Creature *creature)
int IsElite (lua_State *L, Creature *creature)
int IsGuard (lua_State *L, Creature *creature)
int IsCivilian (lua_State *L, Creature *creature)
int IsRacialLeader (lua_State *L, Creature *creature)
int IsWorldBoss (lua_State *L, Creature *creature)
int HasCategoryCooldown (lua_State *L, Creature *creature)
int HasSpell (lua_State *L, Creature *creature)
int HasQuest (lua_State *L, Creature *creature)
int HasSpellCooldown (lua_State *L, Creature *creature)
int CanFly (lua_State *L, Creature *creature)
int GetRespawnDelay (lua_State *L, Creature *creature)
int GetWanderRadius (lua_State *L, Creature *creature)
int GetCurrentWaypointId (lua_State *L, Creature *creature)
int GetDefaultMovementType (lua_State *L, Creature *creature)
int GetAggroRange (lua_State *L, Creature *creature)
int GetAttackDistance (lua_State *L, Creature *creature)
int GetLootRecipientGroup (lua_State *L, Creature *creature)
int GetLootRecipient (lua_State *L, Creature *creature)
int GetScriptName (lua_State *L, Creature *creature)
int GetAIName (lua_State *L, Creature *creature)
int GetScriptId (lua_State *L, Creature *creature)
int GetCreatureSpellCooldownDelay (lua_State *L, Creature *creature)
int GetCorpseDelay (lua_State *L, Creature *creature)
int GetHomePosition (lua_State *L, Creature *creature)
int SetHomePosition (lua_State *L, Creature *creature)
int GetAITarget (lua_State *L, Creature *creature)
int GetAITargets (lua_State *L, Creature *creature)
int GetAITargetsCount (lua_State *L, Creature *creature)
int GetNPCFlags (lua_State *L, Creature *creature)
int GetUnitFlags (lua_State *L, Creature *creature)
int GetUnitFlagsTwo (lua_State *L, Creature *creature)
int GetExtraFlags (lua_State *L, Creature *creature)
int GetRank (lua_State *L, Creature *creature)
int GetDBTableGUIDLow (lua_State *L, Creature *creature)
int SetNPCFlags (lua_State *L, Creature *creature)
int SetUnitFlags (lua_State *L, Creature *creature)
int SetUnitFlagsTwo (lua_State *L, Creature *creature)
int SetDisableGravity (lua_State *L, Creature *creature)
int SetDeathState (lua_State *L, Creature *creature)
int SetWalk (lua_State *L, Creature *creature)
int SetEquipmentSlots (lua_State *L, Creature *creature)
int SetAggroEnabled (lua_State *L, Creature *creature)
int SetDisableReputationGain (lua_State *L, Creature *creature)
int SetInCombatWithZone (lua_State *, Creature *creature)
int SetWanderRadius (lua_State *L, Creature *creature)
int SetRespawnDelay (lua_State *L, Creature *creature)
int SetDefaultMovementType (lua_State *L, Creature *creature)
int SetNoSearchAssistance (lua_State *L, Creature *creature)
int SetNoCallAssistance (lua_State *L, Creature *creature)
int SetHover (lua_State *L, Creature *creature)
int DespawnOrUnsummon (lua_State *L, Creature *creature)
int Respawn (lua_State *, Creature *creature)
int RemoveCorpse (lua_State *, Creature *creature)
int MoveWaypoint (lua_State *, Creature *creature)
int CallAssistance (lua_State *, Creature *creature)
int CallForHelp (lua_State *L, Creature *creature)
int FleeToGetAssistance (lua_State *, Creature *creature)
int AttackStart (lua_State *L, Creature *creature)
int SaveToDB (lua_State *, Creature *creature)
int SelectVictim (lua_State *L, Creature *creature)
int UpdateEntry (lua_State *L, Creature *creature)
int GetCreatureFamily (lua_State *L, Creature *creature)
Enumeration Type Documentation
SelectAggroTarget
enum LuaCreature::SelectAggroTarget
Enumerator
SELECT_TARGET_RANDOM
SELECT_TARGET_TOPAGGRO
SELECT_TARGET_BOTTOMAGGRO
SELECT_TARGET_NEAREST
SELECT_TARGET_FARTHEST
    {
        SELECT_TARGET_RANDOM = 0,   // Just selects a random target
        SELECT_TARGET_TOPAGGRO,     // Selects targes from top aggro to bottom
        SELECT_TARGET_BOTTOMAGGRO,  // Selects targets from bottom aggro to top
        SELECT_TARGET_NEAREST,
        SELECT_TARGET_FARTHEST
    };
Function Documentation
AttackStart()
int LuaCreature::AttackStart (lua_State * L, Creature * creature)
Make the [Creature] attack target.
Parameters
[Unit] target
    {
        Unit* target = Eluna::CHECKOBJ<Unit>(L, 2);
        creature->AI()->AttackStart(target);
        return 0;
    }
References Creature::AI(), and UnitAI::AttackStart().
CallAssistance()
int LuaCreature::CallAssistance (lua_State * , Creature * creature)
Make the [Creature] call for assistance in combat from other nearby [Creature]s.
    {
        creature->CallAssistance();
        return 0;
    }
References Creature::CallAssistance().
CallForHelp()
int LuaCreature::CallForHelp (lua_State * L, Creature * creature)
Make the [Creature] call for help in combat from friendly [Creature]s within radius.
Parameters
float radius
    {
        float radius = Eluna::CHECKVAL<float>(L, 2);
        creature->CallForHelp(radius);
        return 0;
    }
References Creature::CallForHelp().
CanAggro()
int LuaCreature::CanAggro (lua_State * L, Creature * creature)
Returns true if the [Creature] can start attacking nearby hostile [Unit]s, and returns false otherwise.
Returns
bool canAggro
    {
#if defined(TRINITY) || defined(AZEROTHCORE)
        Eluna::Push(L, !creature->HasFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC));
#else
        // Eluna::Push(L, creature->CanInitiateAttack());
        Eluna::Push(L, !creature->HasFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_PASSIVE));
#endif
        return 1;
    }
References Object::HasFlag(), Eluna::Push(), UNIT_FIELD_FLAGS, and UNIT_FLAG_IMMUNE_TO_NPC.
CanAssistTo()
int LuaCreature::CanAssistTo (lua_State * L, Creature * creature)
Returns true if the [Creature] can assist friend in combat against enemy, and returns false otherwise.
Parameters
[Unit] friend : the Unit we will be assisting
[Unit] enemy : the Unit that we would attack if we assist friend
bool checkFaction = true : if true, the [Creature] must be the same faction as friend to assist
Returns
bool canAssist
    {
        Unit* u = Eluna::CHECKOBJ<Unit>(L, 2);
        Unit* enemy = Eluna::CHECKOBJ<Unit>(L, 3);
        bool checkfaction = Eluna::CHECKVAL<bool>(L, 4, true);
        Eluna::Push(L, creature->CanAssistTo(u, enemy, checkfaction));
        return 1;
    }
References Creature::CanAssistTo(), and Eluna::Push().
CanCompleteQuest()
int LuaCreature::CanCompleteQuest (lua_State * L, Creature * creature)
Returns true if the [Creature] completes the [Quest] with the ID questID, and returns false otherwise.
Parameters
uint32 questID : the ID of a [Quest]
Returns
bool completesQuest
    {
        uint32 quest_id = Eluna::CHECKVAL<uint32>(L, 2);
#if defined(TRINITY) || defined(AZEROTHCORE)
        Eluna::Push(L, creature->hasInvolvedQuest(quest_id));
#else
        Eluna::Push(L, creature->HasInvolvedQuest(quest_id));
#endif
        return 1;
    }
References Creature::hasInvolvedQuest(), and Eluna::Push().
CanFly()
int LuaCreature::CanFly (lua_State * L, Creature * creature)
Returns true if the [Creature] can fly, and returns false otherwise.
Returns
bool canFly
    {
        Eluna::Push(L, creature->CanFly());
        return 1;
    }
References Creature::CanFly(), and Eluna::Push().
CanSwim()
int LuaCreature::CanSwim (lua_State * L, Creature * creature)
Returns true if the [Creature] can move through deep water, and returns false otherwise.
Returns
bool canSwim
    {
        Eluna::Push(L, creature->CanSwim());
        return 1;
    }
References Creature::CanSwim(), and Eluna::Push().
CanWalk()
int LuaCreature::CanWalk (lua_State * L, Creature * creature)
Returns true if the [Creature] can move on land, and returns false otherwise.
Returns
bool canWalk
    {
        Eluna::Push(L, creature->CanWalk());
        return 1;
    }
References Creature::CanWalk(), and Eluna::Push().
DespawnOrUnsummon()
int LuaCreature::DespawnOrUnsummon (lua_State * L, Creature * creature)
Despawn this [Creature].
Parameters
uint32 delay = 0 : dely to despawn in milliseconds
    {
        uint32 msTimeToDespawn = Eluna::CHECKVAL<uint32>(L, 2, 0);
#if defined(TRINITY)
        creature->DespawnOrUnsummon(Milliseconds(msTimeToDespawn));
#elif defined(AZEROTHCORE)
        creature->DespawnOrUnsummon(msTimeToDespawn);
#else
        creature->ForcedDespawn(msTimeToDespawn);
#endif
        return 0;
    }
References Creature::DespawnOrUnsummon(), and Creature::ForcedDespawn().
FleeToGetAssistance()
int LuaCreature::FleeToGetAssistance (lua_State * , Creature * creature)
Make the [Creature] flee combat to get assistance from a nearby friendly [Creature].
    {
        creature->DoFleeToGetAssistance();
        return 0;
    }
References Creature::DoFleeToGetAssistance().
GetAggroRange()
int LuaCreature::GetAggroRange (lua_State * L, Creature * creature)
Returns the aggro range of the [Creature] for target.
Parameters
[Unit] target
Returns
float aggroRange
    {
        Unit* target = Eluna::CHECKOBJ<Unit>(L, 2);
#if defined(TRINITY) || defined(AZEROTHCORE)
        Eluna::Push(L, creature->GetAggroRange(target));
#else
        float AttackDist = creature->GetAttackDistance(target);
        float ThreatRadius = sWorld.getConfig(CONFIG_FLOAT_THREAT_RADIUS);
        Eluna::Push(L, ThreatRadius > AttackDist ? ThreatRadius : AttackDist);
#endif
        return 1;
    }
References Creature::GetAggroRange(), Creature::GetAttackDistance(), Eluna::Push(), and sWorld.
GetAIName()
int LuaCreature::GetAIName (lua_State * L, Creature * creature)
Returns the [Creature]'s AI name.
This is used by the core to assign the Creature's default AI.
If the Creature is scripted by Eluna, the AI is overriden.
Returns
string AIName
    {
        Eluna::Push(L, creature->GetAIName());
        return 1;
    }
References Creature::GetAIName(), and Eluna::Push().
GetAITarget()
int LuaCreature::GetAITarget (lua_State * L, Creature * creature)
Returns a target from the [Creature]'s threat list based on the supplied arguments.
enum SelectAggroTarget { SELECT_TARGET_RANDOM = 0, //Just selects a random target SELECT_TARGET_TOPAGGRO, //Selects targets from top aggro to bottom SELECT_TARGET_BOTTOMAGGRO, //Selects targets from bottom aggro to top SELECT_TARGET_NEAREST, SELECT_TARGET_FARTHEST };
For example, if you wanted to select the third-farthest [Player] within 50 yards that has the [Aura] "Corrupted Blood" (ID 24328), you could use this function like so:
target = creature:GetAITarget(4, true, 3, 50, 24328)
Parameters
[SelectAggroTarget] targetType : how the threat list should be sorted
bool playerOnly = false : if true, skips targets that aren't [Player]s
uint32 position = 0 : used as an offset into the threat list. If targetType is random, used as the number of players from top of aggro to choose from
float distance = 0.0 : if positive, the maximum distance for the target. If negative, the minimum distance
int32 aura = 0 : if positive, the target must have this [Aura]. If negative, the the target must not have this Aura
Returns
[Unit] target : the target, or nil
    {
        uint32 targetType = Eluna::CHECKVAL<uint32>(L, 2);
        bool playerOnly = Eluna::CHECKVAL<bool>(L, 3, false);
        uint32 position = Eluna::CHECKVAL<uint32>(L, 4, 0);
        float dist = Eluna::CHECKVAL<float>(L, 5, 0.0f);
        int32 aura = Eluna::CHECKVAL<int32>(L, 6, 0);
#if defined(CMANGOS)
        ThreatList const& threatlist = creature->getThreatManager().getThreatList();
#elif defined(MANGOS)
        ThreatList const& threatlist = creature->GetThreatManager().getThreatList();
#elif defined(TRINITY)
        auto const& threatlist = creature->GetThreatManager().GetSortedThreatList();
#elif defined(AZEROTHCORE)
        auto const& threatlist = creature->GetThreatMgr().GetThreatList();
#endif
#ifndef TRINITY
        if (threatlist.empty())
            return 1;
        if (position >= threatlist.size())
            return 1;
#endif
        std::list<Unit*> targetList;
#if defined(TRINITY)
        for (ThreatReference const* itr : threatlist)
#else
        for (auto itr = threatlist.begin(); itr != threatlist.end(); ++itr)
#endif
            {
#if defined(TRINITY)
            Unit* target = itr->GetVictim();
#else
            Unit* target = (*itr)->getTarget();
#endif
            if (!target)
                continue;
            if (playerOnly && target->GetTypeId() != TYPEID_PLAYER)
                continue;
            if (aura > 0 && !target->HasAura(aura))
                continue;
            else if (aura < 0 && target->HasAura(-aura))
                continue;
            if (dist > 0.0f && !creature->IsWithinDist(target, dist))
                continue;
            else if (dist < 0.0f && creature->IsWithinDist(target, -dist))
                continue;
            targetList.push_back(target);
        }
        if (targetList.empty())
            return 1;
        if (position >= targetList.size())
            return 1;
        if (targetType == SELECT_TARGET_NEAREST || targetType == SELECT_TARGET_FARTHEST)
            targetList.sort(ElunaUtil::ObjectDistanceOrderPred(creature));
        switch (targetType)
        {
            case SELECT_TARGET_NEAREST:
            case SELECT_TARGET_TOPAGGRO:
                {
                    std::list<Unit*>::const_iterator itr = targetList.begin();
                    if (position)
                        std::advance(itr, position);
                    Eluna::Push(L, *itr);
                }
                break;
            case SELECT_TARGET_FARTHEST:
            case SELECT_TARGET_BOTTOMAGGRO:
                {
                    std::list<Unit*>::reverse_iterator ritr = targetList.rbegin();
                    if (position)
                        std::advance(ritr, position);
                    Eluna::Push(L, *ritr);
                }
                break;
            case SELECT_TARGET_RANDOM:
                {
                    std::list<Unit*>::const_iterator itr = targetList.begin();
                    if (position)
                        std::advance(itr, urand(0, position));
                    else
                        std::advance(itr, urand(0, targetList.size() - 1));
                    Eluna::Push(L, *itr);
                }
                break;
            default:
                luaL_argerror(L, 2, "SelectAggroTarget expected");
                break;
        }
        return 1;
    }
References ThreatMgr::GetThreatList(), Unit::GetThreatMgr(), Object::GetTypeId(), Unit::GetVictim(), Unit::HasAura(), WorldObject::IsWithinDist(), luaL_argerror(), Eluna::Push(), SELECT_TARGET_BOTTOMAGGRO, SELECT_TARGET_FARTHEST, SELECT_TARGET_NEAREST, SELECT_TARGET_RANDOM, SELECT_TARGET_TOPAGGRO, TYPEID_PLAYER, and urand().
GetAITargets()
int LuaCreature::GetAITargets (lua_State * L, Creature * creature)
Returns all [Unit]s in the [Creature]'s threat list.
Returns
table targets
    {
#if defined(TRINITY)
        auto const& threatlist = creature->GetThreatManager().GetThreatenedByMeList();
#elif defined(AZEROTHCORE)
auto const& threatlist = creature->GetThreatMgr().GetThreatList();
#else
        ThreatList const& threatlist = creature->GetThreatManager().getThreatList();
#endif
        lua_createtable(L, threatlist.size(), 0);
        int tbl = lua_gettop(L);
        uint32 i = 0;
        for (auto itr = threatlist.begin(); itr != threatlist.end(); ++itr)
        {
#if defined(TRINITY)
            Unit* target = itr->second->GetOwner();
#else
            Unit* target = (*itr)->getTarget();
#endif
            if (!target)
                continue;
            Eluna::Push(L, target);
            lua_rawseti(L, tbl, ++i);
        }
        lua_settop(L, tbl);
        return 1;
    }
References Unit::GetOwner(), ThreatMgr::GetThreatList(), Unit::GetThreatMgr(), lua_createtable(), lua_gettop(), lua_rawseti(), lua_settop(), and Eluna::Push().
GetAITargetsCount()
int LuaCreature::GetAITargetsCount (lua_State * L, Creature * creature)
Returns the number of [Unit]s in this [Creature]'s threat list.
Returns
int targetsCount
    {
#if defined(TRINITY)
        Eluna::Push(L, creature->GetThreatManager().GetThreatenedByMeList().size());
#elif defined(AZEROTHCORE)
        Eluna::Push(L, creature->GetThreatMgr().GetThreatListSize());
#else
        Eluna::Push(L, creature->GetThreatManager().getThreatList().size());
#endif
        return 1;
    }
References ThreatMgr::GetThreatListSize(), Unit::GetThreatMgr(), and Eluna::Push().
GetAttackDistance()
int LuaCreature::GetAttackDistance (lua_State * L, Creature * creature)
Returns the effective aggro range of the [Creature] for target.
If this is smaller than the minimum aggro range set in the config file, that is used as the aggro range instead.
Parameters
[Unit] target
Returns
float attackDistance
    {
        Unit* target = Eluna::CHECKOBJ<Unit>(L, 2);
        Eluna::Push(L, creature->GetAttackDistance(target));
        return 1;
    }
References Creature::GetAttackDistance(), and Eluna::Push().
GetCorpseDelay()
int LuaCreature::GetCorpseDelay (lua_State * L, Creature * creature)
Returns the delay between when the [Creature] dies and when its body despawns.
Returns
uint32 corpseDelay : the delay, in seconds
    {
        Eluna::Push(L, creature->GetCorpseDelay());
        return 1;
    }
References Creature::GetCorpseDelay(), and Eluna::Push().
GetCreatureFamily()
int LuaCreature::GetCreatureFamily (lua_State * L, Creature * creature)
Returns the [Creature]'s creature family ID (enumerated in CreatureFamily.dbc).
enum CreatureFamily
{
    CREATURE_FAMILY_NONE                = 0,    // TrinityCore only
    CREATURE_FAMILY_WOLF                = 1,
    CREATURE_FAMILY_CAT                 = 2,
    CREATURE_FAMILY_SPIDER              = 3,
    CREATURE_FAMILY_BEAR                = 4,
    CREATURE_FAMILY_BOAR                = 5,
    CREATURE_FAMILY_CROCOLISK           = 6,
    CREATURE_FAMILY_CARRION_BIRD        = 7,
    CREATURE_FAMILY_CRAB                = 8,
    CREATURE_FAMILY_GORILLA             = 9,
    CREATURE_FAMILY_HORSE_CUSTOM        = 10,   // Does not exist in DBC but used for horse like beasts in DB
    CREATURE_FAMILY_RAPTOR              = 11,
    CREATURE_FAMILY_TALLSTRIDER         = 12,
    CREATURE_FAMILY_FELHUNTER           = 15,
    CREATURE_FAMILY_VOIDWALKER          = 16,
    CREATURE_FAMILY_SUCCUBUS            = 17,
    CREATURE_FAMILY_DOOMGUARD           = 19,
    CREATURE_FAMILY_SCORPID             = 20,
    CREATURE_FAMILY_TURTLE              = 21,
    CREATURE_FAMILY_IMP                 = 23,
    CREATURE_FAMILY_BAT                 = 24,
    CREATURE_FAMILY_HYENA               = 25,
    CREATURE_FAMILY_BIRD_OF_PREY        = 26,   // Named CREATURE_FAMILY_OWL in Mangos
    CREATURE_FAMILY_WIND_SERPENT        = 27,
    CREATURE_FAMILY_REMOTE_CONTROL      = 28,
    CREATURE_FAMILY_FELGUARD            = 29,   // This and below is TBC+
    CREATURE_FAMILY_DRAGONHAWK          = 30,
    CREATURE_FAMILY_RAVAGER             = 31,
    CREATURE_FAMILY_WARP_STALKER        = 32,
    CREATURE_FAMILY_SPOREBAT            = 33,
    CREATURE_FAMILY_NETHER_RAY          = 34,
    CREATURE_FAMILY_SERPENT             = 35,
    CREATURE_FAMILY_SEA_LION            = 36,   // TBC only
    CREATURE_FAMILY_MOTH                = 37,   // This and below is WotLK+
    CREATURE_FAMILY_CHIMAERA            = 38,
    CREATURE_FAMILY_DEVILSAUR           = 39,
    CREATURE_FAMILY_GHOUL               = 40,
    CREATURE_FAMILY_SILITHID            = 41,
    CREATURE_FAMILY_WORM                = 42,
    CREATURE_FAMILY_RHINO               = 43,
    CREATURE_FAMILY_WASP                = 44,
    CREATURE_FAMILY_CORE_HOUND          = 45,
    CREATURE_FAMILY_SPIRIT_BEAST        = 46
};
Returns
[CreatureFamily] creatureFamily
    {
        uint32 entry = creature->GetEntry();
#if defined(TRINITY) || defined(AZEROTHCORE)
        CreatureTemplate const* cInfo = sObjectMgr->GetCreatureTemplate(entry);
        if (cInfo)
            Eluna::Push(L, cInfo->family);
#else
        CreatureInfo const* cInfo = ObjectMgr::GetCreatureTemplate(entry);
        if (cInfo)
            Eluna::Push(L, cInfo->Family);
#endif
        return 1;
    }
References CreatureTemplate::family, ObjectMgr::GetCreatureTemplate(), Object::GetEntry(), Eluna::Push(), and sObjectMgr.
GetCreatureSpellCooldownDelay()
int LuaCreature::GetCreatureSpellCooldownDelay (lua_State * L, Creature * creature)
Returns the [Creature]'s cooldown for spellID.
Parameters
uint32 spellID
Returns
uint32 cooldown : the cooldown, in milliseconds
    {
        uint32 spell = Eluna::CHECKVAL<uint32>(L, 2);
#if defined(TRINITY)
        if (SpellInfo const* spellInfo = sSpellMgr->GetSpellInfo(spell))
            Eluna::Push(L, creature->GetSpellHistory()->GetRemainingCooldown(spellInfo));
        else
            Eluna::Push(L, 0);
#elif defined(AZEROTHCORE)
        if (sSpellMgr->GetSpellInfo(spell))
            Eluna::Push(L, creature->GetSpellCooldown(spell));
        else
            Eluna::Push(L, 0);
#else
        Eluna::Push(L, creature->GetCreatureSpellCooldownDelay(spell));
#endif
        return 1;
    }
References Creature::GetSpellCooldown(), Eluna::Push(), and sSpellMgr.
GetCurrentWaypointId()
int LuaCreature::GetCurrentWaypointId (lua_State * L, Creature * creature)
Returns the current waypoint ID of the [Creature].
Returns
uint32 wpId
    {
#if defined(TRINITY)
        Eluna::Push(L, creature->GetCurrentWaypointInfo().first);
#elif defined(AZEROTHCORE)
        Eluna::Push(L, creature->GetCurrentWaypointID());
#else
        Eluna::Push(L, creature->GetMotionMaster()->getLastReachedWaypoint());
#endif
        return 1;
    }
References Creature::GetCurrentWaypointID(), Unit::GetMotionMaster(), and Eluna::Push().
GetDBTableGUIDLow()
int LuaCreature::GetDBTableGUIDLow (lua_State * L, Creature * creature)
Returns the guid of the [Creature] that is used as the ID in the database
Returns
uint32 dbguid
    {
#if defined(TRINITY) || defined(AZEROTHCORE)
        Eluna::Push(L, creature->GetSpawnId());
#else
        // on mangos based this is same as lowguid
        Eluna::Push(L, creature->GetGUIDLow());
#endif
        return 1;
    }
References Creature::GetSpawnId(), and Eluna::Push().
GetDefaultMovementType()
int LuaCreature::GetDefaultMovementType (lua_State * L, Creature * creature)
Returns the default movement type for this [Creature].
Returns
[MovementGeneratorType] defaultMovementType
    {
        Eluna::Push(L, creature->GetDefaultMovementType());
        return 1;
    }
References Creature::GetDefaultMovementType(), and Eluna::Push().
GetExtraFlags()
int LuaCreature::GetExtraFlags (lua_State * L, Creature * creature)
Returns the [Creature]'s Extra flags.
These are used to control whether the NPC is a civilian, uses pathfinding, if it's a guard, etc.
Returns
[ExtraFlags] extraFlags
    {
#if defined(TRINITY) || defined(AZEROTHCORE)
        Eluna::Push(L, creature->GetCreatureTemplate()->flags_extra);
#else
        Eluna::Push(L, creature->GetCreatureInfo()->ExtraFlags);
#endif
        return 1;
    }
References CreatureTemplate::flags_extra, Creature::GetCreatureTemplate(), and Eluna::Push().
GetHomePosition()
int LuaCreature::GetHomePosition (lua_State * L, Creature * creature)
Returns position the [Creature] returns to when evading from combat or respawning.
Returns
float x
float y
float z
float o
    {
        float x, y, z, o;
#if defined(TRINITY) || defined(AZEROTHCORE)
        creature->GetHomePosition(x, y, z, o);
#else
        creature->GetRespawnCoord(x, y, z, &o);
#endif
        Eluna::Push(L, x);
        Eluna::Push(L, y);
        Eluna::Push(L, z);
        Eluna::Push(L, o);
        return 4;
    }
References Creature::GetHomePosition(), and Eluna::Push().
GetLootRecipient()
int LuaCreature::GetLootRecipient (lua_State * L, Creature * creature)
Returns the [Player] that can loot this [Creature].
Returns
[Player] lootRecipient : the player or nil
    {
        Eluna::Push(L, creature->GetLootRecipient());
        return 1;
    }
References Creature::GetLootRecipient(), and Eluna::Push().
GetLootRecipientGroup()
int LuaCreature::GetLootRecipientGroup (lua_State * L, Creature * creature)
Returns the [Group] that can loot this [Creature].
Returns
[Group] lootRecipientGroup : the group or nil
    {
#if defined(TRINITY) || defined(AZEROTHCORE)
        Eluna::Push(L, creature->GetLootRecipientGroup());
#else
        Eluna::Push(L, creature->GetGroupLootRecipient());
#endif
        return 1;
    }
References Creature::GetLootRecipientGroup(), and Eluna::Push().
GetNPCFlags()
int LuaCreature::GetNPCFlags (lua_State * L, Creature * creature)
Returns the [Creature]'s NPC flags.
These are used to control whether the NPC is a vendor, can repair items, can give quests, etc.
Returns
[NPCFlags] npcFlags
    {
        Eluna::Push(L, creature->GetUInt32Value(UNIT_NPC_FLAGS));
        return 1;
    }
References Object::GetUInt32Value(), Eluna::Push(), and UNIT_NPC_FLAGS.
GetRank()
int LuaCreature::GetRank (lua_State * L, Creature * creature)
Returns the [Creature]'s rank.
Returns
[Rank] rank
    {
        Eluna::Push(L, creature->GetCreatureTemplate()->rank);
        return 1;
    }
References Creature::GetCreatureTemplate(), Eluna::Push(), and CreatureTemplate::rank.
GetRespawnDelay()
int LuaCreature::GetRespawnDelay (lua_State * L, Creature * creature)
Returns the time it takes for this [Creature] to respawn once killed.
This value does not usually change over a [Creature]'s lifespan, but can be modified by [Creature:SetRespawnDelay].
Returns
uint32 respawnDelay : the respawn delay, in seconds
    {
        Eluna::Push(L, creature->GetRespawnDelay());
        return 1;
    }
References Creature::GetRespawnDelay(), and Eluna::Push().
GetScriptId()
int LuaCreature::GetScriptId (lua_State * L, Creature * creature)
Returns the [Creature]'s script ID.
Every C++ script name is assigned a unique ID by the core. This returns the ID for this [Creature]'s script name.
Returns
uint32 scriptID
    {
        Eluna::Push(L, creature->GetScriptId());
        return 1;
    }
References Creature::GetScriptId(), and Eluna::Push().
GetScriptName()
int LuaCreature::GetScriptName (lua_State * L, Creature * creature)
Returns the [Creature]'s script name.
This is used by the core to apply C++ scripts to the Creature.
It is not used by Eluna. Eluna will override AI scripts.
Returns
string scriptName
    {
        Eluna::Push(L, creature->GetScriptName());
        return 1;
    }
References Creature::GetScriptName(), and Eluna::Push().
GetUnitFlags()
int LuaCreature::GetUnitFlags (lua_State * L, Creature * creature)
Returns the [Creature]'s Unit flags.
These are used to control whether the NPC is attackable or not, among other things.
Returns
[UnitFlags] unitFlags
    {
        Eluna::Push(L, creature->GetUInt32Value(UNIT_FIELD_FLAGS));
        return 1;
    }
References Object::GetUInt32Value(), Eluna::Push(), and UNIT_FIELD_FLAGS.
GetUnitFlagsTwo()
int LuaCreature::GetUnitFlagsTwo (lua_State * L, Creature * creature)
Returns the [Creature]'s Unit flags 2.
Returns
[UnitFlags2] unitFlags2
    {
        Eluna::Push(L, creature->GetUInt32Value(UNIT_FIELD_FLAGS_2));
        return 1;
    }
References Object::GetUInt32Value(), Eluna::Push(), and UNIT_FIELD_FLAGS_2.
GetWanderRadius()
int LuaCreature::GetWanderRadius (lua_State * L, Creature * creature)
Returns the radius the [Creature] is permitted to wander from its respawn point.
Returns
float wanderRadius
    {
#if defined(TRINITY) || defined(AZEROTHCORE)
        Eluna::Push(L, creature->GetWanderDistance());
#else
        Eluna::Push(L, creature->GetRespawnRadius());
#endif
        return 1;
    }
References Creature::GetWanderDistance(), and Eluna::Push().
HasCategoryCooldown()
int LuaCreature::HasCategoryCooldown (lua_State * L, Creature * creature)
Returns true if the [Creature] cannot cast spellId due to a category cooldown, and returns false otherwise.
Parameters
uint32 spellId : the ID of a [Spell]
Returns
bool hasCooldown
    {
        uint32 spell = Eluna::CHECKVAL<uint32>(L, 2);
#if defined(TRINITY)
        if (const SpellInfo* info = sSpellMgr->GetSpellInfo(spell))
            Eluna::Push(L, info->GetCategory() && creature->GetSpellHistory()->HasCooldown(spell));
        else
            Eluna::Push(L, false);
#elif defined(AZEROTHCORE)
        if (const SpellInfo* info = sSpellMgr->GetSpellInfo(spell))
            Eluna::Push(L, info->GetCategory() && creature->HasSpellCooldown(spell));
        else
            Eluna::Push(L, false);
#else
        Eluna::Push(L, creature->HasCategoryCooldown(spell));
#endif
        return 1;
    }
References Creature::HasSpellCooldown(), Eluna::Push(), and sSpellMgr.
HasLootRecipient()
int LuaCreature::HasLootRecipient (lua_State * L, Creature * creature)
Returns true if the [Creature] will give its loot to a [Player] or [Group], and returns false otherwise.
Returns
bool hasLootRecipient
    {
#if defined(TRINITY) || defined(AZEROTHCORE)
        Eluna::Push(L, creature->hasLootRecipient());
#else
        Eluna::Push(L, creature->HasLootRecipient());
#endif
        return 1;
    }
References Creature::hasLootRecipient(), and Eluna::Push().
HasQuest()
int LuaCreature::HasQuest (lua_State * L, Creature * creature)
Returns true if the [Creature] starts the [Quest] questId, and returns false otherwise.
Parameters
uint32 questId : the ID of a [Quest]
Returns
bool hasQuest
    {
        uint32 questId = Eluna::CHECKVAL<uint32>(L, 2);
#if defined(TRINITY) || defined(AZEROTHCORE)
        Eluna::Push(L, creature->hasQuest(questId));
#else
        Eluna::Push(L, creature->HasQuest(questId));
#endif
        return 1;
    }
References Creature::hasQuest(), and Eluna::Push().
HasSearchedAssistance()
int LuaCreature::HasSearchedAssistance (lua_State * L, Creature * creature)
Returns true if the [Creature] has searched for combat assistance already, and returns false otherwise.
Returns
bool searchedForAssistance
    {
        Eluna::Push(L, creature->HasSearchedAssistance());
        return 1;
    }
References Creature::HasSearchedAssistance(), and Eluna::Push().
HasSpell()
int LuaCreature::HasSpell (lua_State * L, Creature * creature)
Returns true if the [Creature] can cast spellId when mind-controlled, and returns false otherwise.
Parameters
uint32 spellId : the ID of a [Spell]
Returns
bool hasSpell
    {
        uint32 id = Eluna::CHECKVAL<uint32>(L, 2);
        Eluna::Push(L, creature->HasSpell(id));
        return 1;
    }
References Creature::HasSpell(), and Eluna::Push().
HasSpellCooldown()
int LuaCreature::HasSpellCooldown (lua_State * L, Creature * creature)
Returns true if the [Creature] has spellId on cooldown, and returns false otherwise.
Parameters
uint32 spellId : the ID of a [Spell]
Returns
bool hasCooldown
    {
        uint32 spellId = Eluna::CHECKVAL<uint32>(L, 2);
#if defined(TRINITY)
        Eluna::Push(L, creature->GetSpellHistory()->HasCooldown(spellId));
#else
        Eluna::Push(L, creature->HasSpellCooldown(spellId));
#endif
        return 1;
    }
References Creature::HasSpellCooldown(), and Eluna::Push().
IsCivilian()
int LuaCreature::IsCivilian (lua_State * L, Creature * creature)
Returns true if the [Creature] is a civilian, and returns false otherwise.
Returns
bool isCivilian
    {
        Eluna::Push(L, creature->IsCivilian());
        return 1;
    }
References Creature::IsCivilian(), and Eluna::Push().
IsElite()
int LuaCreature::IsElite (lua_State * L, Creature * creature)
Returns true if the [Creature]'s rank is Elite or Rare Elite, and returns false otherwise.
Returns
bool isElite
    {
#if defined(TRINITY) || defined(AZEROTHCORE)
        Eluna::Push(L, creature->isElite());
#else
        Eluna::Push(L, creature->IsElite());
#endif
        return 1;
    }
References Creature::isElite(), and Eluna::Push().
IsGuard()
int LuaCreature::IsGuard (lua_State * L, Creature * creature)
Returns true if the [Creature] is a city guard, and returns false otherwise.
Returns
bool isGuard
    {
        Eluna::Push(L, creature->IsGuard());
        return 1;
    }
References Creature::IsGuard(), and Eluna::Push().
IsInEvadeMode()
int LuaCreature::IsInEvadeMode (lua_State * L, Creature * creature)
Returns true if the [Creature] is returning to its spawn position from combat, and returns false otherwise.
Returns
bool inEvadeMode
    {
        Eluna::Push(L, creature->IsInEvadeMode());
        return 1;
    }
References Creature::IsInEvadeMode(), and Eluna::Push().
IsRacialLeader()
int LuaCreature::IsRacialLeader (lua_State * L, Creature * creature)
Returns true if the [Creature] is the leader of a player faction, and returns false otherwise.
Returns
bool isLeader
    {
        Eluna::Push(L, creature->IsRacialLeader());
        return 1;
    }
References Creature::IsRacialLeader(), and Eluna::Push().
IsRegeneratingHealth()
int LuaCreature::IsRegeneratingHealth (lua_State * L, Creature * creature)
Returns true if the [Creature] can regenerate health, and returns false otherwise.
Returns
bool isRegenerating
    {
#if defined(AZEROTHCORE)
        Eluna::Push(L, creature->isRegeneratingHealth());
#elif defined(TRINITY)
        Eluna::Push(L, creature->CanRegenerateHealth());
#else
        Eluna::Push(L, creature->IsRegeneratingHealth());
#endif
        return 1;
    }
References Creature::isRegeneratingHealth(), and Eluna::Push().
IsReputationGainDisabled()
int LuaCreature::IsReputationGainDisabled (lua_State * L, Creature * creature)
Returns true if the [Creature] is set to not give reputation when killed, and returns false otherwise.
Returns
bool reputationDisabled
    {
        Eluna::Push(L, creature->IsReputationGainDisabled());
        return 1;
    }
References Creature::IsReputationGainDisabled(), and Eluna::Push().
IsTappedBy()
int LuaCreature::IsTappedBy (lua_State * L, Creature * creature)
Returns true if the [Creature] will give its loot to player, and returns false otherwise.
Returns
bool tapped
    {
        Player* player = Eluna::CHECKOBJ<Player>(L, 2);
#if defined(TRINITY) || defined(AZEROTHCORE)
        Eluna::Push(L, creature->isTappedBy(player));
#else
        Eluna::Push(L, creature->IsTappedBy(player));
#endif
        return 1;
    }
References Creature::isTappedBy(), and Eluna::Push().
IsTargetableForAttack()
int LuaCreature::IsTargetableForAttack (lua_State * L, Creature * creature)
Returns true if the [Creature] can be targeted for attack, and returns false otherwise.
Parameters
bool mustBeDead = false : if true, only returns true if the [Creature] is also dead. Otherwise, it must be alive.
Returns
bool targetable
    {
        bool mustBeDead = Eluna::CHECKVAL<bool>(L, 2, false);
#ifdef MANGOS
        Eluna::Push(L, creature->IsTargetableForAttack(mustBeDead));
#else
        Eluna::Push(L, creature->isTargetableForAttack(mustBeDead));
#endif
        return 1;
    }
References Unit::isTargetableForAttack(), and Eluna::Push().
IsWorldBoss()
int LuaCreature::IsWorldBoss (lua_State * L, Creature * creature)
Returns true if the [Creature]'s flags_extra includes Dungeon Boss (0x1000000), and returns false otherwise.
Returns
bool isDungeonBoss Returns true if the [Creature]'s rank is Boss, and returns false otherwise.
bool isWorldBoss
    {
#if defined(TRINITY) || defined(AZEROTHCORE)
        Eluna::Push(L, creature->isWorldBoss());
#else
        Eluna::Push(L, creature->IsWorldBoss());
#endif
        return 1;
    }
References Creature::isWorldBoss(), and Eluna::Push().
MoveWaypoint()
int LuaCreature::MoveWaypoint (lua_State * , Creature * creature)
Make the [Creature] start following its waypoint path.
    {
#if defined(TRINITY) || defined(AZEROTHCORE)
        creature->GetMotionMaster()->MovePath(creature->GetWaypointPath(), true);
#else
        creature->GetMotionMaster()->MoveWaypoint();
#endif
        return 0;
    }
References Unit::GetMotionMaster(), Creature::GetWaypointPath(), and MotionMaster::MovePath().
RemoveCorpse()
int LuaCreature::RemoveCorpse (lua_State * , Creature * creature)
Remove this [Creature]'s corpse.
    {
        creature->RemoveCorpse();
        return 0;
    }
References Creature::RemoveCorpse().
Respawn()
int LuaCreature::Respawn (lua_State * , Creature * creature)
Respawn this [Creature].
    {
        creature->Respawn();
        return 0;
    }
References Creature::Respawn().
SaveToDB()
int LuaCreature::SaveToDB (lua_State * , Creature * creature)
Save the [Creature] in the database.
    {
        creature->SaveToDB();
        return 0;
    }
References Creature::SaveToDB().
SelectVictim()
int LuaCreature::SelectVictim (lua_State * L, Creature * creature)
Make the [Creature] try to find a new target.
This should be called every update cycle for the Creature's AI.
    {
#if defined(TRINITY) || defined(AZEROTHCORE)
        Eluna::Push(L, creature->SelectVictim());
#else
        Eluna::Push(L, creature->SelectHostileTarget());
#endif
        return 1;
    }
References Eluna::Push(), and Creature::SelectVictim().
SetAggroEnabled()
int LuaCreature::SetAggroEnabled (lua_State * L, Creature * creature)
Sets whether the [Creature] can be aggroed.
Parameters
bool allow = true : true to allow aggro, false to disable aggro
    {
        bool allow = Eluna::CHECKVAL<bool>(L, 2, true);
#if defined(TRINITY) || defined(AZEROTHCORE)
        if (allow)
            creature->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC);
        else
            creature->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC);
#else
        if (allow)
            creature->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_PASSIVE);
        else
            creature->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_PASSIVE);
#endif
        return 0;
    }
References Object::RemoveFlag(), Object::SetFlag(), UNIT_FIELD_FLAGS, and UNIT_FLAG_IMMUNE_TO_NPC.
SetDeathState()
int LuaCreature::SetDeathState (lua_State * L, Creature * creature)
Sets the [Creature]'s death state to deathState.
Parameters
[DeathState] deathState
    {
        int32 state = Eluna::CHECKVAL<int32>(L, 2);
#if defined(TRINITY) || defined(AZEROTHCORE)
        creature->setDeathState((DeathState)state);
#else
        creature->SetDeathState((DeathState)state);
#endif
        return 0;
    }
References Creature::setDeathState().
SetDefaultMovementType()
int LuaCreature::SetDefaultMovementType (lua_State * L, Creature * creature)
Sets the default movement type of the [Creature].
Parameters
[MovementGeneratorType] type
    {
        int32 type = Eluna::CHECKVAL<int32>(L, 2);
        creature->SetDefaultMovementType((MovementGeneratorType)type);
        return 0;
    }
References Creature::SetDefaultMovementType().
SetDisableGravity()
int LuaCreature::SetDisableGravity (lua_State * L, Creature * creature)
Makes the [Creature] able to fly if enabled.
Parameters
bool disable
    {
        bool disable = Eluna::CHECKVAL<bool>(L, 2);
#if defined(TRINITY) || defined(AZEROTHCORE)
        creature->SetDisableGravity(disable);
#else
        creature->SetLevitate(disable);
#endif
        return 0;
    }
References Creature::SetDisableGravity().
SetDisableReputationGain()
int LuaCreature::SetDisableReputationGain (lua_State * L, Creature * creature)
Sets whether the [Creature] gives reputation or not.
Parameters
bool disable = true : true to disable reputation, false to enable
    {
        bool disable = Eluna::CHECKVAL<bool>(L, 2, true);
        creature->SetDisableReputationGain(disable);
        return 0;
    }
References Creature::SetDisableReputationGain().
SetEquipmentSlots()
int LuaCreature::SetEquipmentSlots (lua_State * L, Creature * creature)
Equips given [Item]s to the [Unit]. Using 0 removes the equipped [Item]
Parameters
uint32 main_hand : main hand [Item]'s entry
uint32 off_hand : off hand [Item]'s entry
uint32 ranged : ranged [Item]'s entry
    {
        uint32 main_hand = Eluna::CHECKVAL<uint32>(L, 2);
        uint32 off_hand = Eluna::CHECKVAL<uint32>(L, 3);
        uint32 ranged = Eluna::CHECKVAL<uint32>(L, 4);
#if defined(TRINITY) || defined(AZEROTHCORE)
        creature->SetUInt32Value(UNIT_VIRTUAL_ITEM_SLOT_ID + 0, main_hand);
        creature->SetUInt32Value(UNIT_VIRTUAL_ITEM_SLOT_ID + 1, off_hand);
        creature->SetUInt32Value(UNIT_VIRTUAL_ITEM_SLOT_ID + 2, ranged);
#else
        creature->SetVirtualItem(VIRTUAL_ITEM_SLOT_0, main_hand);
        creature->SetVirtualItem(VIRTUAL_ITEM_SLOT_1, off_hand);
        creature->SetVirtualItem(VIRTUAL_ITEM_SLOT_2, ranged);
#endif
        return 0;
    }
References Unit::SetUInt32Value(), Unit::SetVirtualItem(), and UNIT_VIRTUAL_ITEM_SLOT_ID.
SetHomePosition()
int LuaCreature::SetHomePosition (lua_State * L, Creature * creature)
Sets the position the [Creature] returns to when evading from combat or respawning.
Parameters
float x
float y
float z
float o
    {
        float x = Eluna::CHECKVAL<float>(L, 2);
        float y = Eluna::CHECKVAL<float>(L, 3);
        float z = Eluna::CHECKVAL<float>(L, 4);
        float o = Eluna::CHECKVAL<float>(L, 5);
#if defined(TRINITY) || defined(AZEROTHCORE)
        creature->SetHomePosition(x, y, z, o);
#else
        creature->SetRespawnCoord(x, y, z, o);
#endif
        return 0;
    }
References Creature::SetHomePosition().
SetHover()
int LuaCreature::SetHover (lua_State * L, Creature * creature)
Sets whether the creature is hovering / levitating or not.
Parameters
bool enable = true : true to enable hovering, false to disable
    {
        bool enable = Eluna::CHECKVAL<bool>(L, 2, true);
#if defined(TRINITY) || defined(AZEROTHCORE)
        creature->SetHover(enable);
#else
        // Copy paste from Aura::HandleAuraHover
        // TODO: implement core side properly
        WorldPacket data;
        if (enable)
            data.Initialize(SMSG_MOVE_SET_HOVER, 8 + 4);
        else
            data.Initialize(SMSG_MOVE_UNSET_HOVER, 8 + 4);
        data << creature->GetPackGUID();
        data << uint32(0);
#if defined(CMANGOS)
        creature->SendMessageToSet(data, true);
#else
        creature->SendMessageToSet(&data, true);
#endif
#endif
        return 0;
    }
References Object::GetPackGUID(), WorldPacket::Initialize(), WorldObject::SendMessageToSet(), Creature::SetHover(), SMSG_MOVE_SET_HOVER, and SMSG_MOVE_UNSET_HOVER.
SetInCombatWithZone()
int LuaCreature::SetInCombatWithZone (lua_State * , Creature * creature)
Sets the [Creature] as in combat with all [Player]s in the dungeon instance.
This is used by raid bosses to prevent Players from using out-of-combat actions once the encounter has begun.
    {
#if defined(AZEROTHCORE)
        if (creature->IsAIEnabled)
            creature->AI()->DoZoneInCombat();
#elif defined(TRINITY)
        if (creature->IsAIEnabled())
            creature->AI()->DoZoneInCombat();
#else
        creature->SetInCombatWithZone();
#endif
        return 0;
    }
References Creature::AI(), CreatureAI::DoZoneInCombat(), Unit::IsAIEnabled, and Creature::SetInCombatWithZone().
SetNoCallAssistance()
int LuaCreature::SetNoCallAssistance (lua_State * L, Creature * creature)
Sets whether the [Creature] can call nearby enemies for help in combat or not.
Parameters
bool enable = true : true to disable calling for help, false to enable
    {
        bool val = Eluna::CHECKVAL<bool>(L, 2, true);
        creature->SetNoCallAssistance(val);
        return 0;
    }
References Creature::SetNoCallAssistance().
SetNoSearchAssistance()
int LuaCreature::SetNoSearchAssistance (lua_State * L, Creature * creature)
Sets whether the [Creature] can search for assistance at low health or not.
Parameters
bool enable = true : true to disable searching, false to allow
    {
        bool val = Eluna::CHECKVAL<bool>(L, 2, true);
        creature->SetNoSearchAssistance(val);
        return 0;
    }
References Creature::SetNoSearchAssistance().
SetNPCFlags()
int LuaCreature::SetNPCFlags (lua_State * L, Creature * creature)
Sets the [Creature]'s NPC flags to flags.
Parameters
[NPCFlags] flags
    {
        uint32 flags = Eluna::CHECKVAL<uint32>(L, 2);
        creature->SetUInt32Value(UNIT_NPC_FLAGS, flags);
        return 0;
    }
References flags, Unit::SetUInt32Value(), and UNIT_NPC_FLAGS.
SetRespawnDelay()
int LuaCreature::SetRespawnDelay (lua_State * L, Creature * creature)
Sets the time it takes for the [Creature] to respawn when killed.
Parameters
uint32 delay : the delay, in seconds
    {
        uint32 delay = Eluna::CHECKVAL<uint32>(L, 2);
        creature->SetRespawnDelay(delay);
        return 0;
    }
References Creature::SetRespawnDelay().
SetUnitFlags()
int LuaCreature::SetUnitFlags (lua_State * L, Creature * creature)
Sets the [Creature]'s Unit flags to flags.
Parameters
[UnitFlags] flags
    {
        uint32 flags = Eluna::CHECKVAL<uint32>(L, 2);
        creature->SetUInt32Value(UNIT_FIELD_FLAGS, flags);
        return 0;
    }
References flags, Unit::SetUInt32Value(), and UNIT_FIELD_FLAGS.
SetUnitFlagsTwo()
int LuaCreature::SetUnitFlagsTwo (lua_State * L, Creature * creature)
Sets the [Creature]'s Unit flags2 to flags.
Parameters
[UnitFlags2] flags
    {
        uint32 flags = Eluna::CHECKVAL<uint32>(L, 2);
        creature->SetUInt32Value(UNIT_FIELD_FLAGS_2, flags);
        return 0;
    }
References flags, Unit::SetUInt32Value(), and UNIT_FIELD_FLAGS_2.
SetWalk()
int LuaCreature::SetWalk (lua_State * L, Creature * creature)
Sets whether the [Creature] is currently walking or running.
Parameters
bool enable = true : true to enable walking, false for running
    {
        bool enable = Eluna::CHECKVAL<bool>(L, 2, true);
        creature->SetWalk(enable);
        return 0;
    }
References Creature::SetWalk().
SetWanderRadius()
int LuaCreature::SetWanderRadius (lua_State * L, Creature * creature)
Sets the distance the [Creature] can wander from it's spawn point.
Parameters
float distance
    {
        float dist = Eluna::CHECKVAL<float>(L, 2);
#if defined(TRINITY) || defined(AZEROTHCORE)
        creature->SetWanderDistance(dist);
#else
        creature->SetRespawnRadius(dist);
#endif
        return 0;
    }
References Creature::SetWanderDistance().
UpdateEntry()
int LuaCreature::UpdateEntry (lua_State * L, Creature * creature)
Transform the [Creature] into another Creature.
Parameters
uint32 entry : the Creature ID to transform into
uint32 dataGUIDLow = 0 : use this Creature's model and equipment instead of the defaults
    {
        uint32 entry = Eluna::CHECKVAL<uint32>(L, 2);
        uint32 dataGuidLow = Eluna::CHECKVAL<uint32>(L, 3, 0);
#if defined(TRINITY) || defined(AZEROTHCORE)
        creature->UpdateEntry(entry, dataGuidLow ? eObjectMgr->GetCreatureData(dataGuidLow) : NULL);
#else
        creature->UpdateEntry(entry, ALLIANCE, dataGuidLow ? eObjectMgr->GetCreatureData(dataGuidLow) : NULL);
#endif
        return 0;
    }
References ALLIANCE, eObjectMgr, and Creature::UpdateEntry().