AzerothCore Doxygen
instance_eye_of_eternity Struct Reference
Public Member Functions
instance_eye_of_eternity (Map *pMap)
void OnCreatureCreate (Creature *creature) override
ObjectGuid GetGuidData (uint32 data) const override
void VortexHandling ()
void OnPlayerEnter (Player *player) override
void OnGameObjectCreate (GameObject *gameobject) override
void SetData (uint32 type, uint32) override
bool SetBossState (uint32 type, EncounterState state) override
void ProcessEvent (WorldObject *, uint32 eventId) override
bool CheckAchievementCriteriaMeet (uint32 criteria_id, Player const *source, Unit const *, uint32) override
Public Member Functions inherited from InstanceScript
InstanceScript (Map *map)
~InstanceScript () override
virtual void Initialize ()
virtual void Load (char const *data)
virtual void CreatureLooted (Creature *, LootType)
virtual std::string GetSaveData ()
void SaveToDB ()
virtual void Update (uint32)
virtual bool IsEncounterInProgress () const
void OnCreatureCreate (Creature *creature) override
void OnCreatureRemove (Creature *creature) override
void OnGameObjectCreate (GameObject *go) override
void OnGameObjectRemove (GameObject *go) override
ObjectGuid GetObjectGuid (uint32 type) const
ObjectGuid GetGuidData (uint32 type) const override
Creature * GetCreature (uint32 type)
GameObject * GetGameObject (uint32 type)
virtual void OnPlayerLeave (Player *)
virtual void OnPlayerAreaUpdate (Player *, uint32, uint32)
virtual void OnPlayerInWaterStateUpdate (Player *, bool)
void HandleGameObject (ObjectGuid guid, bool open, GameObject *go=nullptr)
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
void DoRespawnGameObject (uint32 type)
void DoRespawnCreature (ObjectGuid guid, bool force=false)
void DoRespawnCreature (uint32 type, bool force=false)
void DoUpdateWorldState (uint32 worldstateId, uint32 worldstateValue)
void DoSendNotifyToInstance (char const *format,...)
void DoUpdateAchievementCriteria (AchievementCriteriaTypes type, uint32 miscValue1=0, uint32 miscValue2=0, Unit *unit=nullptr)
void DoStartTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoStopTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoRemoveAurasDueToSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayer (Player *player, uint32 spell, bool includePets, bool includeControlled)
bool ServerAllowsTwoSideGroups ()
EncounterState GetBossState (uint32 id) const
CreatureBoundary const * GetBossBoundary (uint32 id) const
BossInfo const * GetBossInfo (uint32 id) const
uint32 GetPersistentData (uint32 index) const
void StorePersistentData (uint32 index, uint32 data)
virtual bool CheckRequiredBosses (uint32, Player const *=nullptr) const
void SetCompletedEncountersMask (uint32 newMask, bool save)
uint32 GetCompletedEncounterMask () const
void SendEncounterUnit (uint32 type, Unit *unit=nullptr, uint8 param1=0, uint8 param2=0)
virtual void FillInitialWorldStates (WorldPackets::WorldState::InitWorldStates &)
uint32 GetEncounterCount () const
void MarkAreaTriggerDone (uint32 id)
void ResetAreaTriggerDone (uint32 id)
bool IsAreaTriggerDone (uint32 id) const
virtual void DoAction (int32)
void DoForAllMinions (uint32 id, std::function< void(Creature *)> exec)
void StoreGameObjectState (ObjectGuid::LowType spawnId, uint8 state)
uint8 GetStoredGameObjectState (ObjectGuid::LowType spawnId) const
void LoadInstanceSavedGameobjectStateData ()
bool IsBossDone (uint32 bossId) const
bool AllBossesDone () const
bool AllBossesDone (std::initializer_list< uint32 > bossIds) const
TeamId GetTeamIdInInstance () const
void SetTeamIdInInstance (TeamId teamId)
bool IsTwoFactionInstance () const
Public Member Functions inherited from ZoneScript
ZoneScript ()
virtual ~ZoneScript ()
virtual uint32 GetCreatureEntry (ObjectGuid::LowType, CreatureData const *data)
virtual uint32 GetGameObjectEntry (ObjectGuid::LowType, uint32 entry)
virtual void OnUnitDeath (Unit *)
virtual void OnCreatureEvade (Creature *)
virtual void SetGuidData (uint32, ObjectGuid)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
virtual uint32 GetData (uint32) const
Public Attributes
bool _pokeAchievementValid = false
GuidVector _vortexTriggers
Public Attributes inherited from InstanceScript
Map * instance
TaskScheduler scheduler
Additional Inherited Members
Static Public Member Functions inherited from InstanceScript
static std::string GetBossStateName (uint8 state)
Protected Member Functions inherited from InstanceScript
void SetHeaders (std::string const &dataHeaders)
void SetBossNumber (uint32 number)
void SetPersistentDataCount (uint32 number)
void LoadBossBoundaries (BossBoundaryData const &data)
void LoadDoorData (DoorData const *data)
void LoadMinionData (MinionData const *data)
void LoadObjectData (ObjectData const *creatureData, ObjectData const *gameObjectData)
void LoadSummonData (ObjectData const *data)
void SetSummoner (Creature *creature)
void AddObject (Creature *obj, bool add=true)
void RemoveObject (Creature *obj)
void AddObject (GameObject *obj, bool add=true)
void RemoveObject (GameObject *obj)
void AddObject (WorldObject *obj, uint32 type, bool add=true)
void RemoveObject (WorldObject *obj, uint32 type)
void AddDoor (GameObject *door, bool add=true)
void RemoveDoor (GameObject *door)
void AddMinion (Creature *minion, bool add=true)
void RemoveMinion (Creature *minion)
void UpdateDoorState (GameObject *door)
void UpdateMinionState (Creature *minion, EncounterState state)
bool ReadSaveDataHeaders (std::istringstream &data)
void ReadSaveDataBossStates (std::istringstream &data)
void ReadSavePersistentData (std::istringstream &data)
virtual void ReadSaveDataMore (std::istringstream &)
void WriteSaveDataHeaders (std::ostringstream &data)
void WriteSaveDataBossStates (std::ostringstream &data)
void WritePersistentData (std::ostringstream &data)
virtual void WriteSaveDataMore (std::ostringstream &)
Detailed Description
Constructor & Destructor Documentation
instance_eye_of_eternity()
instance_eye_of_eternity::instance_eye_of_eternity (Map * pMap) inline
                                        : InstanceScript(pMap)
    {
        SetHeaders(DataHeader);
        SetBossNumber(EncounterCount);
        LoadObjectData(creatureData, gameobjectData);
        Initialize();
        _pokeAchievementValid = false;
    }
References _pokeAchievementValid, creatureData, DataHeader, EncounterCount, gameobjectData, InstanceScript::Initialize(), InstanceScript::LoadObjectData(), InstanceScript::SetBossNumber(), and InstanceScript::SetHeaders().
Member Function Documentation
CheckAchievementCriteriaMeet()
bool instance_eye_of_eternity::CheckAchievementCriteriaMeet (uint32 criteria_id, Player const * source, Unit const * , uint32) inline override virtual
Reimplemented from InstanceScript.
    {
        switch (criteria_id)
        {
            case ACHIEV_CRITERIA_A_POKE_IN_THE_EYE_10:
            case ACHIEV_CRITERIA_A_POKE_IN_THE_EYE_25:
                return _pokeAchievementValid;
            case ACHIEV_CRITERIA_DENYIN_THE_SCION_10:
            case ACHIEV_CRITERIA_DENYIN_THE_SCION_25:
                return source && source->GetVehicle() && source->GetVehicle()->GetVehicleInfo()->m_ID == 224;
        }
        return false;
    }
References _pokeAchievementValid, ACHIEV_CRITERIA_A_POKE_IN_THE_EYE_10, ACHIEV_CRITERIA_A_POKE_IN_THE_EYE_25, ACHIEV_CRITERIA_DENYIN_THE_SCION_10, ACHIEV_CRITERIA_DENYIN_THE_SCION_25, Unit::GetVehicle(), Vehicle::GetVehicleInfo(), and VehicleEntry::m_ID.
GetGuidData()
ObjectGuid instance_eye_of_eternity::GetGuidData (uint32 data) const inline override virtual
Reimplemented from ZoneScript.
    {
        if (data == DATA_VORTEX_TRIGGER)
            return !_vortexTriggers.empty() ? _vortexTriggers.front() : ObjectGuid::Empty;
        return InstanceScript::GetGuidData(data);
    }
References _vortexTriggers, DATA_VORTEX_TRIGGER, ObjectGuid::Empty, and InstanceScript::GetGuidData().
OnCreatureCreate()
void instance_eye_of_eternity::OnCreatureCreate (Creature * creature) inline override virtual
Reimplemented from ZoneScript.
    {
        InstanceScript::OnCreatureCreate(creature);
        if (creature->GetEntry() == NPC_VORTEX)
            _vortexTriggers.push_back(creature->GetGUID());
    }
References _vortexTriggers, Object::GetEntry(), Object::GetGUID(), NPC_VORTEX, and InstanceScript::OnCreatureCreate().
OnGameObjectCreate()
void instance_eye_of_eternity::OnGameObjectCreate (GameObject * gameobject) inline override virtual
Reimplemented from ZoneScript.
    {
        InstanceScript::OnGameObjectCreate(gameobject);
        uint32 entry = gameobject->GetEntry();
        if ((entry == GO_IRIS_N || entry == GO_IRIS_H) && GetBossState(DATA_MALYGOS) == DONE)
            gameobject->SetPhaseMask(2, true);
        if (entry == GO_NEXUS_PLATFORM && GetBossState(DATA_MALYGOS) == DONE)
        {
            gameobject->ModifyHealth(-int32(PLATFORM_DESTROY_DAMAGE));
            gameobject->EnableCollision(false);
        }
    }
References DATA_MALYGOS, DONE, GameObject::EnableCollision(), InstanceScript::GetBossState(), Object::GetEntry(), GO_IRIS_H, GO_IRIS_N, GO_NEXUS_PLATFORM, GameObject::ModifyHealth(), InstanceScript::OnGameObjectCreate(), PLATFORM_DESTROY_DAMAGE, and GameObject::SetPhaseMask().
OnPlayerEnter()
void instance_eye_of_eternity::OnPlayerEnter (Player * player) inline override virtual
Reimplemented from InstanceScript.
    {
        if (GetBossState(DATA_MALYGOS) != DONE)
            return;
        ProcessEvent(nullptr, EVENT_IRIS_ACTIVATED);
        if (GameObject* iris = GetGameObject(DATA_IRIS))
            if (iris->GetPhaseMask() != 2)
                iris->SetPhaseMask(2, true);
        if (player && player->IsAlive())
            player->CastSpell(player, SPELL_SUMMON_RED_DRAGON_BUDDY, true);
    }
References Unit::CastSpell(), DATA_IRIS, DATA_MALYGOS, DONE, EVENT_IRIS_ACTIVATED, InstanceScript::GetBossState(), InstanceScript::GetGameObject(), Unit::IsAlive(), ProcessEvent(), and SPELL_SUMMON_RED_DRAGON_BUDDY.
ProcessEvent()
void instance_eye_of_eternity::ProcessEvent (WorldObject * , uint32 eventId) inline override virtual
Reimplemented from ZoneScript.
    {
        if (eventId != EVENT_IRIS_ACTIVATED)
            return;
        if (GameObject* platform = GetGameObject(DATA_NEXUS_PLATFORM))
            if (Creature* malygos = GetCreature(DATA_MALYGOS))
            {
                platform->ModifyHealth(-int32(PLATFORM_DESTROY_DAMAGE), malygos);
                platform->EnableCollision(false);
            }
    }
References DATA_MALYGOS, DATA_NEXUS_PLATFORM, EVENT_IRIS_ACTIVATED, InstanceScript::GetCreature(), InstanceScript::GetGameObject(), and PLATFORM_DESTROY_DAMAGE.
Referenced by OnPlayerEnter().
SetBossState()
bool instance_eye_of_eternity::SetBossState (uint32 type, EncounterState state) inline override virtual
Reimplemented from InstanceScript.
    {
        if (!InstanceScript::SetBossState(type, state))
            return false;
        if (type != DATA_MALYGOS)
            return true;
        switch (state)
        {
            case NOT_STARTED:
                _pokeAchievementValid = false;
                if (GameObject* iris = GetGameObject(DATA_IRIS))
                {
                    iris->SetPhaseMask(1, true);
                    HandleGameObject(iris->GetGUID(), false, iris);
                }
                if (GameObject* portal = GetGameObject(DATA_EXIT_PORTAL))
                    portal->SetPhaseMask(1, true);
                if (GameObject* platform = GetGameObject(DATA_NEXUS_PLATFORM))
                {
                    platform->SetDestructibleState(GO_DESTRUCTIBLE_REBUILDING, nullptr, true);
                    platform->EnableCollision(true);
                }
                break;
            case IN_PROGRESS:
                _pokeAchievementValid = (instance->GetPlayersCountExceptGMs() < (instance->GetSpawnMode() == 0 ? (uint32)9 : (uint32)21));
                break;
            case DONE:
                _pokeAchievementValid = false;
                if (GameObject* portal = GetGameObject(DATA_EXIT_PORTAL))
                    portal->SetPhaseMask(1, true);
                if (Creature* malygos = GetCreature(DATA_MALYGOS))
                    malygos->SummonCreature(NPC_ALEXSTRASZA, 798.0f, 1268.0f, 299.0f, 2.45f, TEMPSUMMON_MANUAL_DESPAWN);
                break;
            default:
                break;
        }
        return true;
    }
References _pokeAchievementValid, DATA_EXIT_PORTAL, DATA_IRIS, DATA_MALYGOS, DATA_NEXUS_PLATFORM, DONE, InstanceScript::GetCreature(), InstanceScript::GetGameObject(), Map::GetPlayersCountExceptGMs(), Map::GetSpawnMode(), GO_DESTRUCTIBLE_REBUILDING, InstanceScript::HandleGameObject(), IN_PROGRESS, InstanceScript::instance, NOT_STARTED, NPC_ALEXSTRASZA, InstanceScript::SetBossState(), and TEMPSUMMON_MANUAL_DESPAWN.
SetData()
void instance_eye_of_eternity::SetData (uint32 type, uint32) inline override virtual
Reimplemented from ZoneScript.
    {
        switch (type)
        {
            case DATA_IRIS_ACTIVATED:
                if (GetBossState(DATA_MALYGOS) == NOT_STARTED)
                {
                    if (Creature* malygos = GetCreature(DATA_MALYGOS))
                    {
                        if (Player* player = malygos->SelectNearestPlayer(250.0f))
                            malygos->AI()->AttackStart(player);
                    }
                }
                break;
            case DATA_SET_IRIS_INACTIVE:
            {
                if (GameObject* iris = GetGameObject(DATA_IRIS))
                {
                    HandleGameObject(ObjectGuid::Empty, true, iris);
                    if (Creature* trigger = iris->SummonCreature(NPC_WORLD_TRIGGER_LAOI, *iris, TEMPSUMMON_TIMED_DESPAWN, 10000))
                        trigger->CastSpell(trigger, SPELL_IRIS_ACTIVATED, true);
                }
                break;
            }
            case DATA_HIDE_IRIS_AND_PORTAL:
                if (GameObject* iris = GetGameObject(DATA_IRIS))
                    iris->SetPhaseMask(2, true);
                if (GameObject* portal = GetGameObject(DATA_EXIT_PORTAL))
                    portal->SetPhaseMask(2, true);
                break;
            case DATA_VORTEX_HANDLING:
                VortexHandling();
                break;
        }
    }
References DATA_EXIT_PORTAL, DATA_HIDE_IRIS_AND_PORTAL, DATA_IRIS, DATA_IRIS_ACTIVATED, DATA_MALYGOS, DATA_SET_IRIS_INACTIVE, DATA_VORTEX_HANDLING, ObjectGuid::Empty, InstanceScript::GetBossState(), InstanceScript::GetCreature(), InstanceScript::GetGameObject(), InstanceScript::HandleGameObject(), NOT_STARTED, NPC_WORLD_TRIGGER_LAOI, WorldObject::SelectNearestPlayer(), SPELL_IRIS_ACTIVATED, WorldObject::SummonCreature(), TEMPSUMMON_TIMED_DESPAWN, and VortexHandling().
VortexHandling()
void instance_eye_of_eternity::VortexHandling () inline
    {
        Creature* malygos = GetCreature(DATA_MALYGOS);
        if (!malygos)
            return;
        for (ObjectGuid const& guid : _vortexTriggers)
        {
            uint8 counter = 0;
            if (Creature* trigger = instance->GetCreature(guid))
            {
                for (auto* ref : malygos->GetThreatMgr().GetUnsortedThreatList())
                {
                    if (counter >= 5)
                        break;
                    if (Player* player = ref->GetVictim()->ToPlayer())
                    {
                        if (player->IsGameMaster() || player->HasAura(SPELL_VORTEX_4))
                            continue;
                        player->CastSpell(trigger, SPELL_VORTEX_4, true);
                        counter++;
                    }
                }
            }
        }
    }
References _vortexTriggers, DATA_MALYGOS, Map::GetCreature(), InstanceScript::GetCreature(), Unit::GetThreatMgr(), ThreatMgr::GetUnsortedThreatList(), Unit::GetVictim(), InstanceScript::instance, SPELL_VORTEX_4, and Object::ToPlayer().
Referenced by SetData().
Member Data Documentation
_pokeAchievementValid
bool instance_eye_of_eternity::_pokeAchievementValid = false
Referenced by CheckAchievementCriteriaMeet(), instance_eye_of_eternity(), and SetBossState().
_vortexTriggers
GuidVector instance_eye_of_eternity::_vortexTriggers
Referenced by GetGuidData(), OnCreatureCreate(), and VortexHandling().
The documentation for this struct was generated from the following file:
azerothcore-wotlk/src/server/scripts/Northrend/Nexus/EyeOfEternity/instance_eye_of_eternity.cpp