AzerothCore Doxygen
lfg::LFGPlayerScript Class Reference
#include "LFGScripts.h"
Public Member Functions
LFGPlayerScript ()
void OnPlayerLevelChanged (Player *player, uint8 oldLevel) override
void OnPlayerLogout (Player *player) override
void OnPlayerLogin (Player *player) override
void OnPlayerBindToInstance (Player *player, Difficulty difficulty, uint32 mapId, bool permanent) override
void OnPlayerMapChanged (Player *player) override
Public Member Functions inherited from PlayerScript
virtual void OnPlayerJustDied (Player *)
virtual void OnPlayerCalculateTalentsPoints (Player const *, uint32 &)
virtual void OnPlayerReleasedGhost (Player *)
virtual void OnPlayerSendInitialPacketsBeforeAddToMap (Player *, WorldPacket &)
virtual void OnPlayerBattlegroundDesertion (Player *, BattlegroundDesertionType const)
virtual void OnPlayerCompleteQuest (Player *, Quest const *)
virtual void OnPlayerPVPKill (Player *, Player *)
virtual void OnPlayerPVPFlagChange (Player *, bool)
virtual void OnPlayerCreatureKill (Player *, Creature *)
virtual void OnPlayerCreatureKilledByPet (Player *, Creature *)
virtual void OnPlayerKilledByCreature (Creature *, Player *)
virtual void OnPlayerFreeTalentPointsChanged (Player *, uint32)
virtual void OnPlayerTalentsReset (Player *, bool)
virtual void OnPlayerAfterSpecSlotChanged (Player *, uint8)
virtual void OnPlayerBeforeUpdate (Player *, uint32)
virtual void OnPlayerUpdate (Player *, uint32)
virtual void OnPlayerMoneyChanged (Player *, int32 &)
virtual void OnPlayerBeforeLootMoney (Player *, Loot *)
virtual void OnPlayerGiveXP (Player *, uint32 &, Unit *, uint8)
virtual bool OnPlayerReputationChange (Player *, uint32, int32 &, bool)
virtual void OnPlayerReputationRankChange (Player *, uint32, ReputationRank, ReputationRank, bool)
virtual void OnPlayerLearnSpell (Player *, uint32)
virtual void OnPlayerForgotSpell (Player *, uint32)
virtual void OnPlayerDuelRequest (Player *, Player *)
virtual void OnPlayerDuelStart (Player *, Player *)
virtual void OnPlayerDuelEnd (Player *, Player *, DuelCompleteType)
virtual void OnPlayerChat (Player *, uint32, uint32, std::string &)
virtual void OnPlayerBeforeSendChatMessage (Player *, uint32 &, uint32 &, std::string &)
virtual void OnPlayerChat (Player *, uint32, uint32, std::string &, Player *)
virtual void OnPlayerChat (Player *, uint32, uint32, std::string &, Group *)
virtual void OnPlayerChat (Player *, uint32, uint32, std::string &, Guild *)
virtual void OnPlayerChat (Player *, uint32, uint32, std::string &, Channel *)
virtual void OnPlayerEmote (Player *, uint32)
virtual void OnPlayerTextEmote (Player *, uint32, uint32, ObjectGuid)
virtual void OnPlayerSpellCast (Player *, Spell *, bool)
virtual void OnPlayerLoadFromDB (Player *)
virtual void OnPlayerBeforeLogout (Player *)
virtual void OnPlayerCreate (Player *)
virtual void OnPlayerDelete (ObjectGuid, uint32)
virtual void OnPlayerFailedDelete (ObjectGuid, uint32)
virtual void OnPlayerSave (Player *)
virtual void OnPlayerUpdateZone (Player *, uint32, uint32)
virtual void OnPlayerUpdateArea (Player *, uint32, uint32)
virtual bool OnPlayerBeforeTeleport (Player *, uint32, float, float, float, float, uint32, Unit *)
virtual void OnPlayerUpdateFaction (Player *)
virtual void OnPlayerAddToBattleground (Player *, Battleground *)
virtual void OnPlayerQueueRandomDungeon (Player *, uint32 &)
virtual void OnPlayerRemoveFromBattleground (Player *, Battleground *)
virtual void OnPlayerAchievementComplete (Player *, AchievementEntry const *)
virtual bool OnPlayerBeforeAchievementComplete (Player *, AchievementEntry const *)
virtual void OnPlayerCriteriaProgress (Player *, AchievementCriteriaEntry const *)
virtual bool OnPlayerBeforeCriteriaProgress (Player *, AchievementCriteriaEntry const *)
virtual void OnPlayerAchievementSave (CharacterDatabaseTransaction, Player *, uint16, CompletedAchievementData)
virtual void OnPlayerCriteriaSave (CharacterDatabaseTransaction, Player *, uint16, CriteriaProgress)
virtual void OnPlayerGossipSelect (Player *, uint32, uint32, uint32)
virtual void OnPlayerGossipSelectCode (Player *, uint32, uint32, uint32, const char *)
virtual void OnPlayerBeingCharmed (Player *, Unit *, uint32, uint32)
virtual void OnPlayerAfterSetVisibleItemSlot (Player *, uint8, Item *)
virtual void OnPlayerAfterMoveItemFromInventory (Player *, Item *, uint8, uint8, bool)
virtual void OnPlayerEquip (Player *, Item *, uint8, uint8, bool)
virtual void OnPlayerJoinBG (Player *)
virtual void OnPlayerJoinArena (Player *)
virtual void OnPlayerGetMaxPersonalArenaRatingRequirement (Player const *, uint32, uint32 &) const
virtual void OnPlayerLootItem (Player *, Item *, uint32, ObjectGuid)
virtual void OnPlayerBeforeFillQuestLootItem (Player *, LootItem &)
virtual void OnPlayerStoreNewItem (Player *, Item *, uint32)
virtual void OnPlayerCreateItem (Player *, Item *, uint32)
virtual void OnPlayerQuestRewardItem (Player *, Item *, uint32)
virtual bool OnPlayerCanPlaceAuctionBid (Player *, AuctionEntry *)
virtual void OnPlayerGroupRollRewardItem (Player *, Item *, uint32, RollVote, Roll *)
virtual bool OnPlayerBeforeOpenItem (Player *, Item *)
virtual bool OnPlayerBeforeQuestComplete (Player *, uint32)
virtual void OnPlayerQuestComputeXP (Player *, Quest const *, uint32 &)
virtual void OnPlayerBeforeDurabilityRepair (Player *, ObjectGuid, ObjectGuid, float &, uint8)
virtual void OnPlayerBeforeBuyItemFromVendor (Player *, ObjectGuid, uint32, uint32 &, uint8, uint8, uint8)
virtual void OnPlayerBeforeStoreOrEquipNewItem (Player *, uint32, uint32 &, uint8, uint8, uint8, ItemTemplate const *, Creature *, VendorItem const *, bool)
virtual void OnPlayerAfterStoreOrEquipNewItem (Player *, uint32, Item *, uint8, uint8, uint8, ItemTemplate const *, Creature *, VendorItem const *, bool)
virtual void OnPlayerAfterUpdateMaxPower (Player *, Powers &, float &)
virtual void OnPlayerAfterUpdateMaxHealth (Player *, float &)
virtual void OnPlayerBeforeUpdateAttackPowerAndDamage (Player *, float &, float &, bool)
virtual void OnPlayerAfterUpdateAttackPowerAndDamage (Player *, float &, float &, float &, float &, bool)
virtual void OnPlayerBeforeInitTalentForLevel (Player *, uint8 &, uint32 &)
virtual void OnPlayerFirstLogin (Player *)
virtual void OnPlayerSetMaxLevel (Player *, uint32 &)
virtual bool OnPlayerCanJoinInBattlegroundQueue (Player *, ObjectGuid, BattlegroundTypeId, uint8, GroupJoinBattlegroundResult &)
virtual bool OnPlayerShouldBeRewardedWithMoneyInsteadOfExp (Player *)
virtual void OnPlayerBeforeTempSummonInitStats (Player *, TempSummon *, uint32 &)
virtual void OnPlayerBeforeGuardianInitStatsForLevel (Player *, Guardian *, CreatureTemplate const *, PetType &)
virtual void OnPlayerAfterGuardianInitStatsForLevel (Player *, Guardian *)
virtual void OnPlayerBeforeLoadPetFromDB (Player *, uint32 &, uint32 &, bool &, bool &)
virtual bool OnPlayerCanJoinInArenaQueue (Player *, ObjectGuid, uint8, BattlegroundTypeId, uint8, uint8, GroupJoinBattlegroundResult &)
virtual bool OnPlayerCanBattleFieldPort (Player *, uint8, BattlegroundTypeId, uint8)
virtual bool OnPlayerCanGroupInvite (Player *, std::string &)
virtual bool OnPlayerCanGroupAccept (Player *, Group *)
virtual bool OnPlayerCanSellItem (Player *, Item *, Creature *)
virtual bool OnPlayerCanSendMail (Player *, ObjectGuid, ObjectGuid, std::string &, std::string &, uint32, uint32, Item *)
virtual void OnPlayerPetitionBuy (Player *, Creature *, uint32 &, uint32 &, uint32 &)
virtual void OnPlayerPetitionShowList (Player *, Creature *, uint32 &, uint32 &, uint32 &)
virtual void OnPlayerRewardKillRewarder (Player *, KillRewarder *, bool, float &)
virtual bool OnPlayerCanGiveMailRewardAtGiveLevel (Player *, uint8)
virtual void OnPlayerDeleteFromDB (CharacterDatabaseTransaction, uint32)
virtual bool OnPlayerCanRepopAtGraveyard (Player *)
virtual Optional< bool > OnPlayerIsClass (Player const *, Classes, ClassContext)
virtual void OnPlayerGetMaxSkillValue (Player *, uint32, int32 &, bool)
virtual bool OnPlayerHasActivePowerType (Player const *, Powers)
virtual void OnPlayerUpdateGatheringSkill (Player *, uint32, uint32, uint32, uint32, uint32, uint32 &)
This hook called before gathering skill gain is applied to the character.
virtual void OnPlayerUpdateCraftingSkill (Player *, SkillLineAbilityEntry const *, uint32, uint32 &)
This hook is called before crafting skill gain is applied to the character.
virtual bool OnPlayerUpdateFishingSkill (Player *, int32, int32, int32, int32)
virtual bool OnPlayerCanAreaExploreAndOutdoor (Player *)
virtual void OnPlayerVictimRewardBefore (Player *, Player *, uint32 &, uint32 &)
virtual void OnPlayerVictimRewardAfter (Player *, Player *, uint32 &, uint32 &, float &)
virtual void OnPlayerCustomScalingStatValueBefore (Player *, ItemTemplate const *, uint8, bool, uint32 &)
virtual void OnPlayerCustomScalingStatValue (Player *, ItemTemplate const *, uint32 &, int32 &, uint8, uint32, ScalingStatValuesEntry const *)
virtual void OnPlayerApplyItemModsBefore (Player *, uint8, bool, uint8, uint32, int32 &)
virtual void OnPlayerApplyEnchantmentItemModsBefore (Player *, Item *, EnchantmentSlot, bool, uint32, uint32 &)
virtual void OnPlayerApplyWeaponDamage (Player *, uint8, ItemTemplate const *, float &, float &, uint8)
virtual bool OnPlayerCanArmorDamageModifier (Player *)
virtual void OnPlayerGetFeralApBonus (Player *, int32 &, int32, ItemTemplate const *, ScalingStatValuesEntry const *)
virtual bool OnPlayerCanApplyWeaponDependentAuraDamageMod (Player *, Item *, WeaponAttackType, AuraEffect const *, bool)
virtual bool OnPlayerCanApplyEquipSpell (Player *, SpellInfo const *, Item *, bool, bool)
virtual bool OnPlayerCanApplyEquipSpellsItemSet (Player *, ItemSetEffect *)
virtual bool OnPlayerCanCastItemCombatSpell (Player *, Unit *, WeaponAttackType, uint32, uint32, Item *, ItemTemplate const *)
virtual bool OnPlayerCanCastItemUseSpell (Player *, Item *, SpellCastTargets const &, uint8, uint32)
virtual void OnPlayerApplyAmmoBonuses (Player *, ItemTemplate const *, float &)
virtual bool OnPlayerCanEquipItem (Player *, uint8, uint16 &, Item *, bool, bool)
virtual bool OnPlayerCanUnequipItem (Player *, uint16, bool)
virtual bool OnPlayerCanUseItem (Player *, ItemTemplate const *, InventoryResult &)
virtual bool OnPlayerCanSaveEquipNewItem (Player *, Item *, uint16, bool)
virtual bool OnPlayerCanApplyEnchantment (Player *, Item *, EnchantmentSlot, bool, bool, bool)
virtual void OnPlayerGetQuestRate (Player *, float &)
virtual bool OnPlayerPassedQuestKilledMonsterCredit (Player *, Quest const *, uint32, uint32, ObjectGuid)
virtual bool OnPlayerCheckItemInSlotAtLoadInventory (Player *, Item *, uint8, uint8 &, uint16 &)
virtual bool OnPlayerNotAvoidSatisfy (Player *, DungeonProgressionRequirements const *, uint32, bool)
virtual bool OnPlayerNotVisibleGloballyFor (Player *, Player const *)
virtual void OnPlayerGetArenaPersonalRating (Player *, uint8, uint32 &)
virtual void OnPlayerGetArenaTeamId (Player *, uint8, uint32 &)
virtual void OnPlayerIsFFAPvP (Player *, bool &)
virtual void OnPlayerFfaPvpStateUpdate (Player *, bool)
virtual void OnPlayerIsPvP (Player *, bool &)
virtual void OnPlayerGetMaxSkillValueForLevel (Player *, uint16 &)
virtual bool OnPlayerNotSetArenaTeamInfoField (Player *, uint8, ArenaTeamInfoType, uint32)
virtual bool OnPlayerCanJoinLfg (Player *, uint8, std::set< uint32 > &, const std::string &)
virtual bool OnPlayerCanEnterMap (Player *, MapEntry const *, InstanceTemplate const *, MapDifficulty const *, bool)
virtual bool OnPlayerCanInitTrade (Player *, Player *)
virtual bool OnPlayerCanSetTradeItem (Player *, Item *, uint8)
This hook called just before finishing the handling of the action of a player setting an item in a trade slot.
virtual void OnPlayerSetServerSideVisibility (Player *, ServerSideVisibilityType &, AccountTypes &)
virtual void OnPlayerSetServerSideVisibilityDetect (Player *, ServerSideVisibilityType &, AccountTypes &)
virtual void OnPlayerResurrect (Player *, float, bool)
virtual void OnPlayerBeforeChooseGraveyard (Player *, TeamId, bool, uint32 &)
virtual bool OnPlayerCanUseChat (Player *, uint32, uint32, std::string &)
This hook called before player sending message in default chat.
virtual bool OnPlayerCanUseChat (Player *, uint32, uint32, std::string &, Player *)
This hook called before player sending message to other player via private.
virtual bool OnPlayerCanUseChat (Player *, uint32, uint32, std::string &, Group *)
This hook called before player sending message to group.
virtual bool OnPlayerCanUseChat (Player *, uint32, uint32, std::string &, Guild *)
This hook called before player sending message to guild.
virtual bool OnPlayerCanUseChat (Player *, uint32, uint32, std::string &, Channel *)
This hook called before player sending message to channel.
virtual void OnPlayerLearnTalents (Player *, uint32, uint32, uint32)
This hook called after player learning talents.
virtual void OnPlayerEnterCombat (Player *, Unit *)
This hook called after player entering combat.
virtual void OnPlayerLeaveCombat (Player *)
This hook called after player leave combat.
virtual void OnPlayerQuestAbandon (Player *, uint32)
This hook called after player abandoning quest.
virtual bool OnPlayerCanFlyInZone (Player *, uint32, uint32, SpellInfo const *)
This hook called before other CanFlyChecks are applied.
virtual void AnticheatSetCanFlybyServer (Player *, bool)
virtual void AnticheatSetUnderACKmount (Player *)
virtual void AnticheatSetRootACKUpd (Player *)
virtual void AnticheatSetJumpingbyOpcode (Player *, bool)
virtual void AnticheatUpdateMovementInfo (Player *, MovementInfo const &)
virtual bool AnticheatHandleDoubleJump (Player *, Unit *)
virtual bool AnticheatCheckMovementInfo (Player *, MovementInfo const &, Unit *, bool)
virtual bool OnPlayerCanSendErrorAlreadyLooted (Player *)
This hook is called, to avoid displaying the error message that the body has already been stripped.
virtual void OnPlayerAfterCreatureLoot (Player *)
It is used when an item is taken from a creature.
virtual void OnPlayerAfterCreatureLootMoney (Player *)
After a creature's money is taken.
virtual bool OnPlayerCanUpdateSkill (Player *, uint32)
virtual void OnPlayerBeforeUpdateSkill (Player *, uint32, uint32 &, uint32, uint32)
virtual void OnPlayerUpdateSkill (Player *, uint32, uint32, uint32, uint32, uint32)
virtual bool OnPlayerCanResurrect (Player *)
This hook is called, to avoid player resurrect.
virtual bool OnPlayerCanGiveLevel (Player *, uint8)
This hook is called, to cancel the normal level up flow.
virtual void OnPlayerSendListInventory (Player *, ObjectGuid, uint32 &)
This hook is called whenever a player interacts with a vendor, and is then shown the vendor list.
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
uint16 GetTotalAvailableHooks ()
Additional Inherited Members
Protected Member Functions inherited from PlayerScript
PlayerScript (const char *name, std::vector< uint16 > enabledHooks=std::vector< uint16 >())
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name, uint16 totalAvailableHooks=0)
virtual ~ScriptObject ()=default
Detailed Description
Constructor & Destructor Documentation
LFGPlayerScript()
lfg::LFGPlayerScript::LFGPlayerScript ()
                                     :
        PlayerScript("LFGPlayerScript",
        {
            PLAYERHOOK_ON_LEVEL_CHANGED,
            PLAYERHOOK_ON_LOGOUT,
            PLAYERHOOK_ON_LOGIN,
            PLAYERHOOK_ON_BIND_TO_INSTANCE,
            PLAYERHOOK_ON_MAP_CHANGED
        })
    {
    }
References PLAYERHOOK_ON_BIND_TO_INSTANCE, PLAYERHOOK_ON_LEVEL_CHANGED, PLAYERHOOK_ON_LOGIN, PLAYERHOOK_ON_LOGOUT, and PLAYERHOOK_ON_MAP_CHANGED.
Member Function Documentation
OnPlayerBindToInstance()
void lfg::LFGPlayerScript::OnPlayerBindToInstance (Player * player, Difficulty difficulty, uint32 mapId, bool permanent) override virtual
Reimplemented from PlayerScript.
    {
        MapEntry const* mapEntry = sMapStore.LookupEntry(mapId);
        if (mapEntry->IsDungeon() && difficulty > DUNGEON_DIFFICULTY_NORMAL)
            sLFGMgr->InitializeLockedDungeons(player, player->GetGroup());
    }
References DUNGEON_DIFFICULTY_NORMAL, Player::GetGroup(), MapEntry::IsDungeon(), sLFGMgr, and sMapStore.
OnPlayerLevelChanged()
void lfg::LFGPlayerScript::OnPlayerLevelChanged (Player * player, uint8 oldLevel) override virtual
Reimplemented from PlayerScript.
    {
        if (!sLFGMgr->isOptionEnabled(LFG_OPTION_ENABLE_DUNGEON_FINDER | LFG_OPTION_ENABLE_RAID_BROWSER | LFG_OPTION_ENABLE_SEASONAL_BOSSES))
            return;
        sLFGMgr->InitializeLockedDungeons(player, player->GetGroup());
    }
References Player::GetGroup(), lfg::LFG_OPTION_ENABLE_DUNGEON_FINDER, lfg::LFG_OPTION_ENABLE_RAID_BROWSER, lfg::LFG_OPTION_ENABLE_SEASONAL_BOSSES, and sLFGMgr.
OnPlayerLogin()
void lfg::LFGPlayerScript::OnPlayerLogin (Player * player) override virtual
Todo:
Restore LfgPlayerData and send proper status to player if it was in a group
Reimplemented from PlayerScript.
    {
        if (!sLFGMgr->isOptionEnabled(LFG_OPTION_ENABLE_DUNGEON_FINDER | LFG_OPTION_ENABLE_RAID_BROWSER | LFG_OPTION_ENABLE_SEASONAL_BOSSES))
            return;
        // Temporal: Trying to determine when group data and LFG data gets desynched
        ObjectGuid guid = player->GetGUID();
        ObjectGuid gguid = sLFGMgr->GetGroup(guid);
        Group const* group = player->GetGroup();
        if (group)
        {
            ObjectGuid gguid2 = group->GetGUID();
            if (gguid != gguid2)
            {
                sLFGMgr->SetupGroupMember(guid, group->GetGUID());
            }
        }
        sLFGMgr->InitializeLockedDungeons(player, group);
        sLFGMgr->SetTeam(player->GetGUID(), player->GetTeamId());
    }
References Player::GetGroup(), Group::GetGUID(), Object::GetGUID(), Player::GetTeamId(), lfg::LFG_OPTION_ENABLE_DUNGEON_FINDER, lfg::LFG_OPTION_ENABLE_RAID_BROWSER, lfg::LFG_OPTION_ENABLE_SEASONAL_BOSSES, and sLFGMgr.
OnPlayerLogout()
void lfg::LFGPlayerScript::OnPlayerLogout (Player * player) override virtual
Reimplemented from PlayerScript.
    {
        if (!sLFGMgr->isOptionEnabled(LFG_OPTION_ENABLE_DUNGEON_FINDER | LFG_OPTION_ENABLE_RAID_BROWSER | LFG_OPTION_ENABLE_SEASONAL_BOSSES))
            return;
        if (!player->GetGroup() || !player->GetGroup()->isLFGGroup())
        {
            player->GetSession()->SendLfgLfrList(false);
            sLFGMgr->LeaveLfg(player->GetGUID());
            sLFGMgr->LeaveAllLfgQueues(player->GetGUID(), true, player->GetGroup() ? player->GetGroup()->GetGUID() : ObjectGuid::Empty);
            // pussywizard: after all necessary actions handle raid browser
            // pussywizard: already done above
            //if (sLFGMgr->GetState(player->GetGUID()) == LFG_STATE_RAIDBROWSER)
            //  sLFGMgr->LeaveLfg(player->GetGUID());
        }
        sLFGMgr->LfrSearchRemove(player);
    }
References ObjectGuid::Empty, Player::GetGroup(), Group::GetGUID(), Object::GetGUID(), Player::GetSession(), Group::isLFGGroup(), lfg::LFG_OPTION_ENABLE_DUNGEON_FINDER, lfg::LFG_OPTION_ENABLE_RAID_BROWSER, lfg::LFG_OPTION_ENABLE_SEASONAL_BOSSES, WorldSession::SendLfgLfrList(), and sLFGMgr.
OnPlayerMapChanged()
void lfg::LFGPlayerScript::OnPlayerMapChanged (Player * player) override virtual
Reimplemented from PlayerScript.
    {
        Map const* map = player->GetMap();
        if (sLFGMgr->inLfgDungeonMap(player->GetGUID(), map->GetId(), map->GetDifficulty()))
        {
            Group* group = player->GetGroup();
            // This function is also called when players log in
            // if for some reason the LFG system recognises the player as being in a LFG dungeon,
            // but the player was loaded without a valid group, we'll teleport to homebind to prevent
            // crashes or other undefined behaviour
            if (!group)
            {
                sLFGMgr->LeaveLfg(player->GetGUID());
                sLFGMgr->LeaveAllLfgQueues(player->GetGUID(), true);
                player->RemoveAurasDueToSpell(LFG_SPELL_LUCK_OF_THE_DRAW);
                player->TeleportTo(player->m_homebindMapId, player->m_homebindX, player->m_homebindY, player->m_homebindZ, 0.0f);
                LOG_DEBUG("lfg", "LFGPlayerScript::OnMapChanged, Player {} ({}) is in LFG dungeon map but does not have a valid group! Teleporting to homebind.",
                    player->GetName(), player->GetGUID().ToString());
                return;
            }
            for (GroupReference* itr = group->GetFirstMember(); itr != nullptr; itr = itr->next())
                if (Player* member = itr->GetSource())
                    player->GetSession()->SendNameQueryOpcode(member->GetGUID());
            if (group->IsLfgWithBuff())
                player->CastSpell(player, LFG_SPELL_LUCK_OF_THE_DRAW, true);
        }
        else
        {
            player->RemoveAurasDueToSpell(LFG_SPELL_LUCK_OF_THE_DRAW);
            // Xinef: Destroy group if only one player is left
            if (Group* group = player->GetGroup())
                if (group->GetMembersCount() <= 1u)
                    group->Disband();
        }
    }
References Unit::CastSpell(), Map::GetDifficulty(), Group::GetFirstMember(), Player::GetGroup(), Object::GetGUID(), Map::GetId(), WorldObject::GetMap(), WorldObject::GetName(), Player::GetSession(), Group::IsLfgWithBuff(), lfg::LFG_SPELL_LUCK_OF_THE_DRAW, LOG_DEBUG, Player::m_homebindMapId, Player::m_homebindX, Player::m_homebindY, Player::m_homebindZ, Unit::RemoveAurasDueToSpell(), WorldSession::SendNameQueryOpcode(), sLFGMgr, Player::TeleportTo(), and ObjectGuid::ToString().
The documentation for this class was generated from the following files:
azerothcore-wotlk/src/server/game/DungeonFinding/LFGScripts.h
azerothcore-wotlk/src/server/game/DungeonFinding/LFGScripts.cpp