AzerothCore Doxygen
SpellInfoBuilder Class Reference
Builder class for creating SpellInfo test instances.
#include "SpellInfoTestHelper.h"
Public Member Functions
SpellInfoBuilder ()
SpellInfoBuilder & WithId (uint32 id)
SpellInfoBuilder & WithSpellFamilyName (uint32 familyName)
SpellInfoBuilder & WithSpellFamilyFlags (uint32 flag0, uint32 flag1=0, uint32 flag2=0)
SpellInfoBuilder & WithSchoolMask (uint32 schoolMask)
SpellInfoBuilder & WithProcFlags (uint32 procFlags)
SpellInfoBuilder & WithProcChance (uint32 procChance)
SpellInfoBuilder & WithProcCharges (uint32 procCharges)
SpellInfoBuilder & WithDmgClass (uint32 dmgClass)
SpellInfoBuilder & WithAttributesEx3 (uint32 attr)
SpellInfoBuilder & WithEffect (uint8 effIndex, uint32 effect, uint32 auraType=0)
SpellInfoBuilder & WithEffectTriggerSpell (uint8 effIndex, uint32 triggerSpell)
SpellInfoBuilder & WithEffectBasePoints (uint8 effIndex, int32 basePoints)
SpellInfoBuilder & WithEffectDieSides (uint8 effIndex, int32 dieSides)
SpellInfoBuilder & WithAttributes (uint32 attr)
SpellInfo * Build ()
std::unique_ptr< SpellInfo > BuildUnique ()
Private Attributes
TestSpellEntryHelper _entryHelper
Detailed Description
Builder class for creating SpellInfo test instances.
This helper allows easy construction of SpellInfo objects for unit testing without requiring DBC data.
Constructor & Destructor Documentation
SpellInfoBuilder()
SpellInfoBuilder::SpellInfoBuilder () inline
: _entryHelper() {}
Member Function Documentation
Build()
SpellInfo * SpellInfoBuilder::Build () inline
    {
        return new SpellInfo(_entryHelper.Get());
    }
References _entryHelper, and TestSpellEntryHelper::Get().
Referenced by SpellProcTest::CreateSpellInfo(), AuraScriptProcTestFixture::CreateSpellInfo(), SpellProcDatabaseTest::SetUp(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
BuildUnique()
std::unique_ptr< SpellInfo > SpellInfoBuilder::BuildUnique () inline
    {
        return std::unique_ptr<SpellInfo>(new SpellInfo(_entryHelper.Get()));
    }
References _entryHelper, and TestSpellEntryHelper::Get().
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
WithAttributes()
SpellInfoBuilder & SpellInfoBuilder::WithAttributes (uint32 attr) inline
    {
        _entryHelper.WithAttributes(attr);
        return *this;
    }
References _entryHelper, and TestSpellEntryHelper::WithAttributes().
Referenced by TEST_F().
WithAttributesEx3()
SpellInfoBuilder & SpellInfoBuilder::WithAttributesEx3 (uint32 attr) inline
    {
        _entryHelper.WithAttributesEx3(attr);
        return *this;
    }
References _entryHelper, and TestSpellEntryHelper::WithAttributesEx3().
Referenced by TEST_F(), TEST_F(), TEST_F(), and TEST_P().
WithDmgClass()
SpellInfoBuilder & SpellInfoBuilder::WithDmgClass (uint32 dmgClass) inline
    {
        _entryHelper.WithDmgClass(dmgClass);
        return *this;
    }
References _entryHelper, and TestSpellEntryHelper::WithDmgClass().
WithEffect()
SpellInfoBuilder & SpellInfoBuilder::WithEffect (uint8 effIndex, uint32 effect, uint32 auraType = 0) inline
    {
        _entryHelper.WithEffect(effIndex, effect, auraType);
        return *this;
    }
References _entryHelper, and TestSpellEntryHelper::WithEffect().
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
WithEffectBasePoints()
SpellInfoBuilder & SpellInfoBuilder::WithEffectBasePoints (uint8 effIndex, int32 basePoints) inline
    {
        _entryHelper.WithEffectBasePoints(effIndex, basePoints);
        return *this;
    }
References _entryHelper, and TestSpellEntryHelper::WithEffectBasePoints().
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
WithEffectDieSides()
SpellInfoBuilder & SpellInfoBuilder::WithEffectDieSides (uint8 effIndex, int32 dieSides) inline
    {
        _entryHelper.WithEffectDieSides(effIndex, dieSides);
        return *this;
    }
References _entryHelper, and TestSpellEntryHelper::WithEffectDieSides().
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
WithEffectTriggerSpell()
SpellInfoBuilder & SpellInfoBuilder::WithEffectTriggerSpell (uint8 effIndex, uint32 triggerSpell) inline
    {
        _entryHelper.WithEffectTriggerSpell(effIndex, triggerSpell);
        return *this;
    }
References _entryHelper, and TestSpellEntryHelper::WithEffectTriggerSpell().
WithId()
SpellInfoBuilder & SpellInfoBuilder::WithId (uint32 id) inline
    {
        _entryHelper.WithId(id);
        return *this;
    }
References _entryHelper, and TestSpellEntryHelper::WithId().
Referenced by SpellProcTest::CreateSpellInfo(), AuraScriptProcTestFixture::CreateSpellInfo(), SpellProcDatabaseTest::SetUp(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_P().
WithProcChance()
SpellInfoBuilder & SpellInfoBuilder::WithProcChance (uint32 procChance) inline
    {
        _entryHelper.WithProcChance(procChance);
        return *this;
    }
References _entryHelper, and TestSpellEntryHelper::WithProcChance().
WithProcCharges()
SpellInfoBuilder & SpellInfoBuilder::WithProcCharges (uint32 procCharges) inline
    {
        _entryHelper.WithProcCharges(procCharges);
        return *this;
    }
References _entryHelper, and TestSpellEntryHelper::WithProcCharges().
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
WithProcFlags()
SpellInfoBuilder & SpellInfoBuilder::WithProcFlags (uint32 procFlags) inline
    {
        _entryHelper.WithProcFlags(procFlags);
        return *this;
    }
References _entryHelper, and TestSpellEntryHelper::WithProcFlags().
Referenced by TEST_F().
WithSchoolMask()
SpellInfoBuilder & SpellInfoBuilder::WithSchoolMask (uint32 schoolMask) inline
    {
        _entryHelper.WithSchoolMask(schoolMask);
        return *this;
    }
References _entryHelper, and TestSpellEntryHelper::WithSchoolMask().
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
WithSpellFamilyFlags()
SpellInfoBuilder & SpellInfoBuilder::WithSpellFamilyFlags (uint32 flag0, uint32 flag1 = 0, uint32 flag2 = 0) inline
    {
        _entryHelper.WithSpellFamilyFlags(flag0, flag1, flag2);
        return *this;
    }
References _entryHelper, and TestSpellEntryHelper::WithSpellFamilyFlags().
Referenced by SpellProcTest::CreateSpellInfo(), AuraScriptProcTestFixture::CreateSpellInfo(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
WithSpellFamilyName()
SpellInfoBuilder & SpellInfoBuilder::WithSpellFamilyName (uint32 familyName) inline
    {
        _entryHelper.WithSpellFamilyName(familyName);
        return *this;
    }
References _entryHelper, and TestSpellEntryHelper::WithSpellFamilyName().
Referenced by SpellProcTest::CreateSpellInfo(), AuraScriptProcTestFixture::CreateSpellInfo(), SpellProcDatabaseTest::SetUp(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
Member Data Documentation
_entryHelper
TestSpellEntryHelper SpellInfoBuilder::_entryHelper private
Referenced by Build(), BuildUnique(), WithAttributes(), WithAttributesEx3(), WithDmgClass(), WithEffect(), WithEffectBasePoints(), WithEffectDieSides(), WithEffectTriggerSpell(), WithId(), WithProcChance(), WithProcCharges(), WithProcFlags(), WithSchoolMask(), WithSpellFamilyFlags(), and WithSpellFamilyName().
The documentation for this class was generated from the following file:
azerothcore-wotlk/src/test/mocks/SpellInfoTestHelper.h