AzerothCore Doxygen
at_hol_hall_of_watchers Class Reference
Public Member Functions
at_hol_hall_of_watchers ()
bool _OnTrigger (Player *player, const AreaTrigger *) override
Public Member Functions inherited from OnlyOnceAreaTriggerScript
bool OnTrigger (Player *, AreaTrigger const *) override
Public Member Functions inherited from AreaTriggerScript
bool IsDatabaseBound () const override
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
uint16 GetTotalAvailableHooks ()
Additional Inherited Members
Protected Member Functions inherited from OnlyOnceAreaTriggerScript
void ResetAreaTriggerDone (InstanceScript *, uint32)
void ResetAreaTriggerDone (Player const *, AreaTrigger const *)
Protected Member Functions inherited from AreaTriggerScript
AreaTriggerScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name, uint16 totalAvailableHooks=0)
virtual ~ScriptObject ()=default
Detailed Description
Constructor & Destructor Documentation
at_hol_hall_of_watchers()
at_hol_hall_of_watchers::at_hol_hall_of_watchers () inline
: OnlyOnceAreaTriggerScript("at_hol_hall_of_watchers") {}
Member Function Documentation
_OnTrigger()
bool at_hol_hall_of_watchers::_OnTrigger (Player * player, const AreaTrigger *) inline override virtual
Implements OnlyOnceAreaTriggerScript.
    {
        std::list<Creature*> creatures;
        player->GetCreatureListWithEntryInGrid(creatures, { NPC_TITANIUM_SIEGEBREAKER, NPC_TITANIUM_THUNDERER }, 50.0f);
        creatures.remove_if([&](Creature const* creature) -> bool
        {
            return !player->IsWithinLOSInMap(creature) || !creature->HasAura(SPELL_FREEZE_ANIM);
        });
        if (creatures.empty())
            return false;
        Acore::Containers::RandomResize(creatures, urand(2, 4));
        ObjectGuid target = player->GetGUID();
        for (Creature* creature : creatures)
        {
            creature->SetHomePosition(player->GetPosition());
            creature->AI()->DoCastSelf(SPELL_AWAKEN);
            creature->RemoveUnitFlag(UNIT_FLAG_NOT_SELECTABLE);
            creature->m_Events.AddEventAtOffset([creature, target] {
                creature->AI()->DoAction(ACTION_ACTIVATE_TITANIUM_VRYKUL);
                if (Player* targetPlayer = ObjectAccessor::GetPlayer(*creature, target))
                    creature->AI()->AttackStart(targetPlayer);
            }, 5s);
        }
        return false;
    }
References ACTION_ACTIVATE_TITANIUM_VRYKUL, EventProcessor::AddEventAtOffset(), Creature::AI(), UnitAI::AttackStart(), UnitAI::DoAction(), UnitAI::DoCastSelf(), WorldObject::GetCreatureListWithEntryInGrid(), Object::GetGUID(), ObjectAccessor::GetPlayer(), Position::GetPosition(), Unit::HasAura(), WorldObject::IsWithinLOSInMap(), WorldObject::m_Events, NPC_TITANIUM_SIEGEBREAKER, NPC_TITANIUM_THUNDERER, Acore::Containers::RandomResize(), Unit::RemoveUnitFlag(), Creature::SetHomePosition(), SPELL_AWAKEN, SPELL_FREEZE_ANIM, UNIT_FLAG_NOT_SELECTABLE, and urand().
The documentation for this class was generated from the following file:
azerothcore-wotlk/src/server/scripts/Northrend/Ulduar/HallsOfLightning/instance_halls_of_lightning.cpp