AzerothCore Doxygen
LuaChatHandler Namespace Reference
Functions
int SendSysMessage (lua_State *L, ChatHandler *handler)
int IsConsole (lua_State *L, ChatHandler *handler)
int GetPlayer (lua_State *L, ChatHandler *handler)
int SendGlobalSysMessage (lua_State *L, ChatHandler *handler)
int SendGlobalGMSysMessage (lua_State *L, ChatHandler *handler)
int HasLowerSecurity (lua_State *L, ChatHandler *handler)
int HasLowerSecurityAccount (lua_State *L, ChatHandler *handler)
int GetSelectedPlayer (lua_State *L, ChatHandler *handler)
int GetSelectedCreature (lua_State *L, ChatHandler *handler)
int GetSelectedUnit (lua_State *L, ChatHandler *handler)
int GetSelectedObject (lua_State *L, ChatHandler *handler)
int GetSelectedPlayerOrSelf (lua_State *L, ChatHandler *handler)
int IsAvailable (lua_State *L, ChatHandler *handler)
int HasSentErrorMessage (lua_State *L, ChatHandler *handler)
Function Documentation
GetPlayer()
int LuaChatHandler::GetPlayer (lua_State * L, ChatHandler * handler)
Returns the [Player] associated with the handler. Returns nil in the case of a console handler
Returns
[Player] player
    {
        Eluna::Push(L, handler->GetPlayer());
        return 1;
    }
References ChatHandler::GetPlayer(), and Eluna::Push().
GetSelectedCreature()
int LuaChatHandler::GetSelectedCreature (lua_State * L, ChatHandler * handler)
Returns the selected [Creature]
Returns
[Creature] creature
    {
        Eluna::Push(L, handler->getSelectedCreature());
        return 1;
    }
References ChatHandler::getSelectedCreature(), and Eluna::Push().
GetSelectedObject()
int LuaChatHandler::GetSelectedObject (lua_State * L, ChatHandler * handler)
Returns the selected [WorldObject]
Returns
[WorldObject] object
    {
        Eluna::Push(L, handler->getSelectedObject());
        return 1;
    }
References ChatHandler::getSelectedObject(), and Eluna::Push().
GetSelectedPlayer()
int LuaChatHandler::GetSelectedPlayer (lua_State * L, ChatHandler * handler)
Returns the selected [Player]
Returns
[Player] player
    {
        Eluna::Push(L, handler->getSelectedPlayer());
        return 1;
    }
References ChatHandler::getSelectedPlayer(), and Eluna::Push().
GetSelectedPlayerOrSelf()
int LuaChatHandler::GetSelectedPlayerOrSelf (lua_State * L, ChatHandler * handler)
Returns the selected [Player] or the current [Player] if nothing is targeted or the target is not a player
Returns
[Player] player
    {
        Eluna::Push(L, handler->getSelectedPlayerOrSelf());
        return 1;
    }
References ChatHandler::getSelectedPlayerOrSelf(), and Eluna::Push().
GetSelectedUnit()
int LuaChatHandler::GetSelectedUnit (lua_State * L, ChatHandler * handler)
Returns the selected [Unit]
Returns
[Unit] unit
    {
        Eluna::Push(L, handler->getSelectedUnit());
        return 1;
    }
References ChatHandler::getSelectedUnit(), and Eluna::Push().
HasLowerSecurity()
int LuaChatHandler::HasLowerSecurity (lua_State * L, ChatHandler * handler)
Checks if the current security level is lower than the specified [Player]'s account
Parameters
[Player] player
[bool] strong = false : Forces non-player accounts (security level greater than 0) to go through the regular check if set to true.
Also, if set to true, the current security level will be considered as lower than the [Player]'s security level if the two levels are equal
Returns
[bool] lower
    {
        Player* player = Eluna::CHECKOBJ<Player>(L, 2);
        bool strong = Eluna::CHECKVAL<bool>(L, 3);
        Eluna::Push(L, handler->HasLowerSecurity(player, ObjectGuid::Empty, strong));
        return 1;
    }
References ObjectGuid::Empty, ChatHandler::HasLowerSecurity(), and Eluna::Push().
HasLowerSecurityAccount()
int LuaChatHandler::HasLowerSecurityAccount (lua_State * L, ChatHandler * handler)
Checks if the current security level is lower than the specified account's level
Parameters
[uint32] account : the target account ID to compare security levels with
[bool] strong = false : Forces non-player accounts (security level greater than 0) to go through the regular check if set to true.
Also, if set to true, the current security level will be considered as lower than the account's security level if the two levels are equal
Returns
[bool] lower
    {
        uint32 account = Eluna::CHECKVAL<uint32>(L, 2);
        bool strong = Eluna::CHECKVAL<bool>(L, 3);
        Eluna::Push(L, handler->HasLowerSecurityAccount(nullptr, account, strong));
        return 1;
    }
References ChatHandler::HasLowerSecurityAccount(), and Eluna::Push().
HasSentErrorMessage()
int LuaChatHandler::HasSentErrorMessage (lua_State * L, ChatHandler * handler)
Returns true if other previously called [ChatHandler] methods sent an error
Returns
[bool] sentErrorMessage
    {
        Eluna::Push(L, handler->HasSentErrorMessage());
        return 1;
    }
References ChatHandler::HasSentErrorMessage(), and Eluna::Push().
IsAvailable()
int LuaChatHandler::IsAvailable (lua_State * L, ChatHandler * handler)
Checks if the securityLevel is available
Parameters
[uint32] securityLevel
Returns
[bool] isAvailable
    {
        uint32 securityLevel = Eluna::CHECKVAL<uint32>(L, 2);
        Eluna::Push(L, handler->IsAvailable(securityLevel));
        return 1;
    }
References ChatHandler::IsAvailable(), and Eluna::Push().
IsConsole()
int LuaChatHandler::IsConsole (lua_State * L, ChatHandler * handler)
Returns true if the [ChatHandler] comes from the console, false if it comes from a player
Returns
bool isConsole
    {
        Eluna::Push(L, handler->IsConsole());
        return 1;
    }
References ChatHandler::IsConsole(), and Eluna::Push().
SendGlobalGMSysMessage()
int LuaChatHandler::SendGlobalGMSysMessage (lua_State * L, ChatHandler * handler)
Sends a message to all connected Game Masters
Parameters
string text : text to send
    {
        std::string text = Eluna::CHECKVAL<std::string>(L, 2);
        handler->SendGlobalGMSysMessage(text.c_str());
        return 0;
    }
References ChatHandler::SendGlobalGMSysMessage().
SendGlobalSysMessage()
int LuaChatHandler::SendGlobalSysMessage (lua_State * L, ChatHandler * handler)
Sends a message to all connected players
Parameters
string text : text to send
    {
        std::string text = Eluna::CHECKVAL<std::string>(L, 2);
        handler->SendGlobalSysMessage(text.c_str());
        return 0;
    }
References ChatHandler::SendGlobalSysMessage().
SendSysMessage()
int LuaChatHandler::SendSysMessage (lua_State * L, ChatHandler * handler)
Sends text to the chat handler
@proto (text) @proto (entry)
Parameters
string text : text to display in chat or console
uint32 entry : id of the string to display
    {
        if (lua_isnumber(L, 2))
        {
            uint32 entry = Eluna::CHECKVAL<uint32>(L, 2);
            handler->SendSysMessage(entry);
        }
        else
        {
            std::string text = Eluna::CHECKVAL<std::string>(L, 2);
            handler->SendSysMessage(text);
        }
        return 0;
    }
References lua_isnumber(), and ChatHandler::SendSysMessage().