AzerothCore Doxygen
LuaVehicle Namespace Reference
Functions
int IsOnBoard (lua_State *L, Vehicle *vehicle)
int GetOwner (lua_State *L, Vehicle *vehicle)
int GetEntry (lua_State *L, Vehicle *vehicle)
int GetPassenger (lua_State *L, Vehicle *vehicle)
int AddPassenger (lua_State *L, Vehicle *vehicle)
int RemovePassenger (lua_State *L, Vehicle *vehicle)
Function Documentation
AddPassenger()
int LuaVehicle::AddPassenger (lua_State * L, Vehicle * vehicle)
Adds [Unit] passenger to a specified seat in the [Vehicle]
Parameters
[Unit] passenger
int8 seat
    {
        Unit* passenger = Eluna::CHECKOBJ<Unit>(L, 2);
        int8 seatId = Eluna::CHECKVAL<int8>(L, 3);
#if defined TRINITY || AZEROTHCORE
        vehicle->AddPassenger(passenger, seatId);
#else
        if (vehicle->CanBoard(passenger))
            vehicle->Board(passenger, seatId);
#endif
        return 0;
    }
References Vehicle::AddPassenger().
GetEntry()
int LuaVehicle::GetEntry (lua_State * L, Vehicle * vehicle)
Returns the [Vehicle]'s entry
Returns
uint32 entry
    {
#ifdef TRINITY
        Eluna::Push(L, vehicle->GetVehicleInfo()->ID);
#elif AZEROTHCORE
        Eluna::Push(L, vehicle->GetVehicleInfo()->m_ID);
#else
        Eluna::Push(L, vehicle->GetVehicleEntry()->m_ID);
#endif
        return 1;
    }
References Vehicle::GetVehicleInfo(), VehicleEntry::m_ID, and Eluna::Push().
GetOwner()
int LuaVehicle::GetOwner (lua_State * L, Vehicle * vehicle)
Returns the [Vehicle]'s owner
Returns
[Unit] owner
    {
#if defined TRINITY || AZEROTHCORE
        Eluna::Push(L, vehicle->GetBase());
#else
        Eluna::Push(L, vehicle->GetOwner());
#endif
        return 1;
    }
References Vehicle::GetBase(), and Eluna::Push().
GetPassenger()
int LuaVehicle::GetPassenger (lua_State * L, Vehicle * vehicle)
Returns the [Vehicle]'s passenger in the specified seat
Parameters
int8 seat
Returns
[Unit] passenger
    {
        int8 seatId = Eluna::CHECKVAL<int8>(L, 2);
        Eluna::Push(L, vehicle->GetPassenger(seatId));
        return 1;
    }
References Vehicle::GetPassenger(), and Eluna::Push().
IsOnBoard()
int LuaVehicle::IsOnBoard (lua_State * L, Vehicle * vehicle)
Returns true if the [Unit] passenger is on board
Parameters
[Unit] passenger
Returns
bool isOnBoard
    {
        Unit* passenger = Eluna::CHECKOBJ<Unit>(L, 2);
#if defined TRINITY || AZEROTHCORE
        Eluna::Push(L, passenger->IsOnVehicle(vehicle->GetBase()));
#else
        Eluna::Push(L, vehicle->HasOnBoard(passenger));
#endif
        return 1;
    }
References Vehicle::GetBase(), Unit::IsOnVehicle(), and Eluna::Push().
RemovePassenger()
int LuaVehicle::RemovePassenger (lua_State * L, Vehicle * vehicle)
Removes [Unit] passenger from the [Vehicle]
Parameters
[Unit] passenger
    {
        Unit* passenger = Eluna::CHECKOBJ<Unit>(L, 2);
#if defined TRINITY || AZEROTHCORE
        vehicle->RemovePassenger(passenger);
#else
        vehicle->UnBoard(passenger, false);
#endif
        return 0;
    }
References Vehicle::RemovePassenger().