AzerothCore Doxygen
AuraStubBuilder Class Reference
Builder for creating AuraStub instances with fluent API.
#include "AuraStub.h"
Public Member Functions
AuraStubBuilder ()
AuraStubBuilder & WithId (uint32_t id)
AuraStubBuilder & WithSpellFamilyName (uint32_t familyName)
AuraStubBuilder & WithCharges (uint8_t charges)
AuraStubBuilder & WithDuration (int32_t duration)
AuraStubBuilder & WithStackAmount (uint8_t amount)
AuraStubBuilder & WithPassive (bool isPassive)
AuraStubBuilder & WithEffect (uint8_t effIndex, int32_t amount, uint32_t auraType=0)
AuraStubBuilder & WithPeriodicEffect (uint8_t effIndex, int32_t amount, int32_t totalTicks)
std::unique_ptr< AuraStub > Build ()
AuraStub * BuildRaw ()
Private Attributes
std::unique_ptr< AuraStub > _stub
Detailed Description
Builder for creating AuraStub instances with fluent API.
Constructor & Destructor Documentation
AuraStubBuilder()
AuraStubBuilder::AuraStubBuilder () inline
: _stub(std::make_unique<AuraStub>()) {}
Member Function Documentation
Build()
std::unique_ptr< AuraStub > AuraStubBuilder::Build () inline
    {
        return std::move(_stub);
    }
References _stub.
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_P().
BuildRaw()
AuraStub * AuraStubBuilder::BuildRaw () inline
    {
        return _stub.release();
    }
References _stub.
WithCharges()
AuraStubBuilder & AuraStubBuilder::WithCharges (uint8_t charges) inline
    {
        _stub->SetCharges(charges);
        _stub->SetUsingCharges(charges > 0);
        return *this;
    }
References _stub.
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
WithDuration()
AuraStubBuilder & AuraStubBuilder::WithDuration (int32_t duration) inline
    {
        _stub->SetDuration(duration);
        _stub->SetMaxDuration(duration);
        return *this;
    }
References _stub.
WithEffect()
AuraStubBuilder & AuraStubBuilder::WithEffect (uint8_t effIndex, int32_t amount, uint32_t auraType = 0) inline
    {
        if (AuraEffectStub* eff = _stub->GetEffect(effIndex))
        {
            eff->SetAmount(amount);
            eff->SetAuraType(auraType);
        }
        return *this;
    }
References _stub.
WithId()
AuraStubBuilder & AuraStubBuilder::WithId (uint32_t id) inline
    {
        _stub->SetId(id);
        return *this;
    }
References _stub.
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_P().
WithPassive()
AuraStubBuilder & AuraStubBuilder::WithPassive (bool isPassive) inline
    {
        _stub->SetPassive(isPassive);
        return *this;
    }
References _stub.
WithPeriodicEffect()
AuraStubBuilder & AuraStubBuilder::WithPeriodicEffect (uint8_t effIndex, int32_t amount, int32_t totalTicks) inline
    {
        if (AuraEffectStub* eff = _stub->GetEffect(effIndex))
        {
            eff->SetAmount(amount);
            eff->SetPeriodic(true);
            eff->SetTotalTicks(totalTicks);
        }
        return *this;
    }
References _stub.
WithSpellFamilyName()
AuraStubBuilder & AuraStubBuilder::WithSpellFamilyName (uint32_t familyName) inline
    {
        _stub->SetSpellFamilyName(familyName);
        return *this;
    }
References _stub.
WithStackAmount()
AuraStubBuilder & AuraStubBuilder::WithStackAmount (uint8_t amount) inline
    {
        _stub->SetStackAmount(amount);
        return *this;
    }
References _stub.
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_P().
Member Data Documentation
_stub
std::unique_ptr<AuraStub> AuraStubBuilder::_stub private
Referenced by Build(), BuildRaw(), WithCharges(), WithDuration(), WithEffect(), WithId(), WithPassive(), WithPeriodicEffect(), WithSpellFamilyName(), and WithStackAmount().
The documentation for this class was generated from the following file:
azerothcore-wotlk/src/test/mocks/AuraStub.h