AzerothCore Doxygen
MMapData Class Reference
#include "MapCollisionData.h"
Public Member Functions
dtNavMesh const * GetNavMesh () const
dtNavMeshQuery const * GetNavMeshQuery ()
Protected Attributes
std::shared_ptr< dtNavMesh > _navMesh
MMAP::ManagedNavMeshQuery _navMeshQuery
Friends
class MapCollisionData
Detailed Description
Member Function Documentation
GetNavMesh()
dtNavMesh const * MMapData::GetNavMesh () const inline
{ return _navMesh.get(); }
References _navMesh.
Referenced by misc_commandscript::HandleGPSCommand(), mmaps_commandscript::HandleMmapLoadedTilesCommand(), mmaps_commandscript::HandleMmapLocCommand(), mmaps_commandscript::HandleMmapPathCommand(), mmaps_commandscript::HandleMmapStatsCommand(), and PathGenerator::PathGenerator().
GetNavMeshQuery()
dtNavMeshQuery const * MMapData::GetNavMeshQuery ()
{
    if (_navMesh && !_navMeshQuery)
        _navMeshQuery = MMAP::MMapMgr::CreateNavMeshQuery(_navMesh.get());
    return _navMeshQuery.get();
}
References _navMesh, _navMeshQuery, and MMAP::MMapMgr::CreateNavMeshQuery().
Referenced by mmaps_commandscript::HandleMmapLoadedTilesCommand(), mmaps_commandscript::HandleMmapLocCommand(), and PathGenerator::PathGenerator().
Friends And Related Symbol Documentation
MapCollisionData
friend class MapCollisionData friend
Member Data Documentation
_navMesh
std::shared_ptr<dtNavMesh> MMapData::_navMesh protected
Referenced by MapCollisionData::GetMMapNavMeshSharedPtr(), GetNavMesh(), GetNavMeshQuery(), MapCollisionData::LoadMMapTile(), and MapCollisionData::MapCollisionData().
_navMeshQuery
MMAP::ManagedNavMeshQuery MMapData::_navMeshQuery protected
Referenced by GetNavMeshQuery().
The documentation for this class was generated from the following files:
azerothcore-wotlk/src/server/game/Maps/MapCollisionData.h
azerothcore-wotlk/src/server/game/Maps/MapCollisionData.cpp