AzerothCore Doxygen
ElunaTemplate< T > Class Template Reference
#include "ElunaTemplate.h"
Public Member Functions
int CollectGarbage (lua_State *L)
int Add (lua_State *L)
int Substract (lua_State *L)
int Multiply (lua_State *L)
int Divide (lua_State *L)
int Mod (lua_State *L)
int Equal (lua_State *L)
int Less (lua_State *L)
int LessOrEqual (lua_State *L)
int Pow (lua_State *L)
int ToString (lua_State *L)
int Add (lua_State *L)
int Substract (lua_State *L)
int Multiply (lua_State *L)
int Divide (lua_State *L)
int Mod (lua_State *L)
int UnaryMinus (lua_State *L)
int Equal (lua_State *L)
int Less (lua_State *L)
int LessOrEqual (lua_State *L)
int Pow (lua_State *L)
int ToString (lua_State *L)
Static Public Member Functions
static void Register (Eluna *E, const char *name, bool gc=false)
template<typename C >
static void SetMethods (Eluna *E, ElunaRegister< C > *methodTable)
static int Push (lua_State *L, T const *obj)
static T * Check (lua_State *L, int narg, bool error=true)
static int GetType (lua_State *L)
static int SetInvalidation (lua_State *L)
static int CallMethod (lua_State *L)
static int CollectGarbage (lua_State *L)
static int ToString (lua_State *L)
static int ArithmeticError (lua_State *L)
static int CompareError (lua_State *L)
static int Add (lua_State *L)
static int Substract (lua_State *L)
static int Multiply (lua_State *L)
static int Divide (lua_State *L)
static int Mod (lua_State *L)
static int Pow (lua_State *L)
static int UnaryMinus (lua_State *L)
static int Concat (lua_State *L)
static int Length (lua_State *L)
static int Equal (lua_State *L)
static int Less (lua_State *L)
static int LessOrEqual (lua_State *L)
static int Call (lua_State *L)
Static Public Attributes
static const char * tname = NULL
static bool manageMemory = false
Detailed Description
template<typename T>
class ElunaTemplate< T >
Member Function Documentation
Add() [1/3]
template<typename T > static int ElunaTemplate< T >::Add (lua_State * L) inline static
{ return ArithmeticError(L); }
References ElunaTemplate< T >::ArithmeticError().
Referenced by ElunaTemplate< T >::Register().
Add() [2/3]
int ElunaTemplate< unsignedlonglong >::Add (lua_State * L)
{ Eluna::Push(L, Eluna::CHECKVAL<unsigned long long>(L, 1) + Eluna::CHECKVAL<unsigned long long>(L, 2)); return 1; }
References Eluna::Push().
Add() [3/3]
int ElunaTemplate< longlong >::Add (lua_State * L)
{ Eluna::Push(L, Eluna::CHECKVAL<long long>(L, 1) + Eluna::CHECKVAL<long long>(L, 2)); return 1; }
References Eluna::Push().
ArithmeticError()
template<typename T > static int ElunaTemplate< T >::ArithmeticError (lua_State * L) inline static
{ return luaL_error(L, "attempt to perform arithmetic on a %s value", tname); }
References luaL_error(), and ElunaTemplate< T >::tname.
Referenced by ElunaTemplate< T >::Add(), ElunaTemplate< T >::Divide(), ElunaTemplate< T >::Mod(), ElunaTemplate< T >::Multiply(), ElunaTemplate< T >::Pow(), ElunaTemplate< T >::Substract(), and ElunaTemplate< T >::UnaryMinus().
Call()
template<typename T > static int ElunaTemplate< T >::Call (lua_State * L) inline static
{ return luaL_error(L, "attempt to call a %s value", tname); }
References luaL_error(), and ElunaTemplate< T >::tname.
Referenced by ElunaTemplate< T >::Register().
CallMethod()
template<typename T > static int ElunaTemplate< T >::CallMethod (lua_State * L) inline static
    {
        T* obj = Eluna::CHECKOBJ<T>(L, 1); // get self
        if (!obj)
            return 0;
        ElunaRegister<T>* l = static_cast<ElunaRegister<T>*>(lua_touserdata(L, lua_upvalueindex(1)));
        int top = lua_gettop(L);
        int expected = l->mfunc(L, obj);
        int args = lua_gettop(L) - top;
        if (args < 0 || args > expected)
        {
            ELUNA_LOG_ERROR("[Eluna]: {} returned unexpected amount of arguments {} out of {}. Report to devs", l->name, args, expected);
            ASSERT(false);
        }
        lua_settop(L, top + expected);
        return expected;
    }
References ASSERT, ELUNA_LOG_ERROR, lua_gettop(), lua_settop(), lua_touserdata(), lua_upvalueindex, ElunaRegister< T >::mfunc, and ElunaRegister< T >::name.
Referenced by ElunaTemplate< T >::SetMethods().
Check()
template<typename T > static T * ElunaTemplate< T >::Check (lua_State * L, int narg, bool error = true) inline static
    {
        ElunaObject* elunaObj = Eluna::CHECKTYPE(L, narg, tname, error);
        if (!elunaObj)
            return NULL;
        if (!elunaObj->IsValid())
        {
            char buff[256];
            snprintf(buff, 256, "%s expected, got pointer to nonexisting (invalidated) object (%s). Check your code.", tname, luaL_typename(L, narg));
            if (error)
            {
                luaL_argerror(L, narg, buff);
            }
            else
            {
                ELUNA_LOG_ERROR("{}", buff);
            }
            return NULL;
        }
        return static_cast<T*>(elunaObj->GetObj());
    }
References Eluna::CHECKTYPE(), ELUNA_LOG_ERROR, ElunaObject::GetObj(), ElunaObject::IsValid(), luaL_argerror(), luaL_typename, and ElunaTemplate< T >::tname.
Referenced by Eluna::CHECKOBJ(), and Eluna::CHECKOBJ().
CollectGarbage() [1/2]
template<typename T > static int ElunaTemplate< T >::CollectGarbage (lua_State * L) inline static
    {
        // Get object pointer (and check type, no error)
        ElunaObject* obj = Eluna::CHECKOBJ<ElunaObject>(L, 1, false);
        if (obj && manageMemory)
            delete static_cast<T*>(obj->GetObj());
        delete obj;
        return 0;
    }
References ElunaObject::GetObj(), and ElunaTemplate< T >::manageMemory.
Referenced by ElunaTemplate< T >::Register().
CollectGarbage() [2/2]
int ElunaTemplate< Vehicle >::CollectGarbage (lua_State * L)
{
    ASSERT(!manageMemory);
    // Get object pointer (and check type, no error)
    ElunaObject* obj = Eluna::CHECKOBJ<ElunaObject>(L, 1, false);
    delete obj;
    return 0;
}
References ASSERT.
CompareError()
template<typename T > static int ElunaTemplate< T >::CompareError (lua_State * L) inline static
{ return luaL_error(L, "attempt to compare %s", tname); }
References luaL_error(), and ElunaTemplate< T >::tname.
Referenced by ElunaTemplate< T >::Less(), and ElunaTemplate< T >::LessOrEqual().
Concat()
template<typename T > static int ElunaTemplate< T >::Concat (lua_State * L) inline static
{ return luaL_error(L, "attempt to concatenate a %s value", tname); }
References luaL_error(), and ElunaTemplate< T >::tname.
Referenced by ElunaTemplate< T >::Register().
Divide() [1/3]
template<typename T > static int ElunaTemplate< T >::Divide (lua_State * L) inline static
{ return ArithmeticError(L); }
References ElunaTemplate< T >::ArithmeticError().
Referenced by ElunaTemplate< T >::Register().
Divide() [2/3]
int ElunaTemplate< unsignedlonglong >::Divide (lua_State * L)
{ Eluna::Push(L, Eluna::CHECKVAL<unsigned long long>(L, 1) / Eluna::CHECKVAL<unsigned long long>(L, 2)); return 1; }
References Eluna::Push().
Divide() [3/3]
int ElunaTemplate< longlong >::Divide (lua_State * L)
{ Eluna::Push(L, Eluna::CHECKVAL<long long>(L, 1) / Eluna::CHECKVAL<long long>(L, 2)); return 1; }
References Eluna::Push().
Equal() [1/3]
template<typename T > static int ElunaTemplate< T >::Equal (lua_State * L) inline static
{ Eluna::Push(L, Eluna::CHECKOBJ<T>(L, 1) == Eluna::CHECKOBJ<T>(L, 2)); return 1; }
References Eluna::Push().
Referenced by ElunaTemplate< T >::Register().
Equal() [2/3]
int ElunaTemplate< unsignedlonglong >::Equal (lua_State * L)
{ Eluna::Push(L, Eluna::CHECKVAL<unsigned long long>(L, 1) == Eluna::CHECKVAL<unsigned long long>(L, 2)); return 1; }
References Eluna::Push().
Equal() [3/3]
int ElunaTemplate< longlong >::Equal (lua_State * L)
{ Eluna::Push(L, Eluna::CHECKVAL<long long>(L, 1) == Eluna::CHECKVAL<long long>(L, 2)); return 1; }
References Eluna::Push().
GetType()
template<typename T > static int ElunaTemplate< T >::GetType (lua_State * L) inline static
    {
        lua_pushstring(L, tname);
        return 1;
    }
References lua_pushstring(), and ElunaTemplate< T >::tname.
Referenced by ElunaTemplate< T >::Register().
Length()
template<typename T > static int ElunaTemplate< T >::Length (lua_State * L) inline static
{ return luaL_error(L, "attempt to get length of a %s value", tname); }
References luaL_error(), and ElunaTemplate< T >::tname.
Referenced by ElunaTemplate< T >::Register().
Less() [1/3]
template<typename T > static int ElunaTemplate< T >::Less (lua_State * L) inline static
{ return CompareError(L); }
References ElunaTemplate< T >::CompareError().
Referenced by ElunaTemplate< T >::Register().
Less() [2/3]
int ElunaTemplate< unsignedlonglong >::Less (lua_State * L)
{ Eluna::Push(L, Eluna::CHECKVAL<unsigned long long>(L, 1) < Eluna::CHECKVAL<unsigned long long>(L, 2)); return 1; }
References Eluna::Push().
Less() [3/3]
int ElunaTemplate< longlong >::Less (lua_State * L)
{ Eluna::Push(L, Eluna::CHECKVAL<long long>(L, 1) < Eluna::CHECKVAL<long long>(L, 2)); return 1; }
References Eluna::Push().
LessOrEqual() [1/3]
template<typename T > static int ElunaTemplate< T >::LessOrEqual (lua_State * L) inline static
{ return CompareError(L); }
References ElunaTemplate< T >::CompareError().
Referenced by ElunaTemplate< T >::Register().
LessOrEqual() [2/3]
int ElunaTemplate< unsignedlonglong >::LessOrEqual (lua_State * L)
{ Eluna::Push(L, Eluna::CHECKVAL<unsigned long long>(L, 1) <= Eluna::CHECKVAL<unsigned long long>(L, 2)); return 1; }
References Eluna::Push().
LessOrEqual() [3/3]
int ElunaTemplate< longlong >::LessOrEqual (lua_State * L)
{ Eluna::Push(L, Eluna::CHECKVAL<long long>(L, 1) <= Eluna::CHECKVAL<long long>(L, 2)); return 1; }
References Eluna::Push().
Mod() [1/3]
template<typename T > static int ElunaTemplate< T >::Mod (lua_State * L) inline static
{ return ArithmeticError(L); }
References ElunaTemplate< T >::ArithmeticError().
Referenced by ElunaTemplate< T >::Register().
Mod() [2/3]
int ElunaTemplate< unsignedlonglong >::Mod (lua_State * L)
{ Eluna::Push(L, Eluna::CHECKVAL<unsigned long long>(L, 1) % Eluna::CHECKVAL<unsigned long long>(L, 2)); return 1; }
References Eluna::Push().
Mod() [3/3]
int ElunaTemplate< longlong >::Mod (lua_State * L)
{ Eluna::Push(L, Eluna::CHECKVAL<long long>(L, 1) % Eluna::CHECKVAL<long long>(L, 2)); return 1; }
References Eluna::Push().
Multiply() [1/3]
template<typename T > static int ElunaTemplate< T >::Multiply (lua_State * L) inline static
{ return ArithmeticError(L); }
References ElunaTemplate< T >::ArithmeticError().
Referenced by ElunaTemplate< T >::Register().
Multiply() [2/3]
int ElunaTemplate< unsignedlonglong >::Multiply (lua_State * L)
{ Eluna::Push(L, Eluna::CHECKVAL<unsigned long long>(L, 1) * Eluna::CHECKVAL<unsigned long long>(L, 2)); return 1; }
References Eluna::Push().
Multiply() [3/3]
int ElunaTemplate< longlong >::Multiply (lua_State * L)
{ Eluna::Push(L, Eluna::CHECKVAL<long long>(L, 1) * Eluna::CHECKVAL<long long>(L, 2)); return 1; }
References Eluna::Push().
Pow() [1/3]
template<typename T > static int ElunaTemplate< T >::Pow (lua_State * L) inline static
{ return ArithmeticError(L); }
References ElunaTemplate< T >::ArithmeticError().
Referenced by ElunaTemplate< T >::Register().
Pow() [2/3]
int ElunaTemplate< unsignedlonglong >::Pow (lua_State * L)
{
    Eluna::Push(L, static_cast<unsigned long long>(powl(static_cast<long double>(Eluna::CHECKVAL<unsigned long long>(L, 1)), static_cast<long double>(Eluna::CHECKVAL<unsigned long long>(L, 2)))));
    return 1;
}
References Eluna::Push().
Pow() [3/3]
int ElunaTemplate< longlong >::Pow (lua_State * L)
{
    Eluna::Push(L, static_cast<long long>(powl(static_cast<long double>(Eluna::CHECKVAL<long long>(L, 1)), static_cast<long double>(Eluna::CHECKVAL<long long>(L, 2)))));
    return 1;
}
References Eluna::Push().
Push()
template<typename T > static int ElunaTemplate< T >::Push (lua_State * L, T const * obj) inline static
    {
        if (!obj)
        {
            lua_pushnil(L);
            return 1;
        }
        // Create new userdata
        ElunaObject** ptrHold = static_cast<ElunaObject**>(lua_newuserdata(L, sizeof(ElunaObject*)));
        if (!ptrHold)
        {
            ELUNA_LOG_ERROR("{} could not create new userdata", tname);
            lua_pushnil(L);
            return 1;
        }
        *ptrHold = new ElunaObject(const_cast<T*>(obj), manageMemory);
        // Set metatable for it
        lua_pushstring(L, tname);
        lua_rawget(L, LUA_REGISTRYINDEX);
        if (!lua_istable(L, -1))
        {
            ELUNA_LOG_ERROR("{} missing metatable", tname);
            lua_pop(L, 2);
            lua_pushnil(L);
            return 1;
        }
        lua_setmetatable(L, -2);
        return 1;
    }
References ELUNA_LOG_ERROR, lua_istable, lua_newuserdata(), lua_pop, lua_pushnil(), lua_pushstring(), lua_rawget(), LUA_REGISTRYINDEX, lua_setmetatable(), ElunaTemplate< T >::manageMemory, and ElunaTemplate< T >::tname.
Referenced by Eluna::Push(), Eluna::Push(), Eluna::Push(), Eluna::Push(), Eluna::Push(), Eluna::Push(), and Eluna::Push().
Register()
template<typename T > static void ElunaTemplate< T >::Register (Eluna * E, const char * name, bool gc = false) inline static
    {
        ASSERT(E);
        ASSERT(name);
        // check that metatable isn't already there
        lua_getglobal(E->L, name);
        ASSERT(lua_isnoneornil(E->L, -1));
        // pop nil
        lua_pop(E->L, 1);
        tname = name;
        manageMemory = gc;
        // create metatable for userdata of this type
        luaL_newmetatable(E->L, tname);
        int metatable  = lua_gettop(E->L);
        // push methodtable to stack to be accessed and modified by users
        lua_pushvalue(E->L, metatable);
        lua_setglobal(E->L, tname);
        // tostring
        lua_pushcfunction(E->L, ToString);
        lua_setfield(E->L, metatable, "__tostring");
        // garbage collecting
        lua_pushcfunction(E->L, CollectGarbage);
        lua_setfield(E->L, metatable, "__gc");
        // make methods accessible through metatable
        lua_pushvalue(E->L, metatable);
        lua_setfield(E->L, metatable, "__index");
        // make new indexes saved to methods
        lua_pushcfunction(E->L, Add);
        lua_setfield(E->L, metatable, "__add");
        // make new indexes saved to methods
        lua_pushcfunction(E->L, Substract);
        lua_setfield(E->L, metatable, "__sub");
        // make new indexes saved to methods
        lua_pushcfunction(E->L, Multiply);
        lua_setfield(E->L, metatable, "__mul");
        // make new indexes saved to methods
        lua_pushcfunction(E->L, Divide);
        lua_setfield(E->L, metatable, "__div");
        // make new indexes saved to methods
        lua_pushcfunction(E->L, Mod);
        lua_setfield(E->L, metatable, "__mod");
        // make new indexes saved to methods
        lua_pushcfunction(E->L, Pow);
        lua_setfield(E->L, metatable, "__pow");
        // make new indexes saved to methods
        lua_pushcfunction(E->L, UnaryMinus);
        lua_setfield(E->L, metatable, "__unm");
        // make new indexes saved to methods
        lua_pushcfunction(E->L, Concat);
        lua_setfield(E->L, metatable, "__concat");
        // make new indexes saved to methods
        lua_pushcfunction(E->L, Length);
        lua_setfield(E->L, metatable, "__len");
        // make new indexes saved to methods
        lua_pushcfunction(E->L, Equal);
        lua_setfield(E->L, metatable, "__eq");
        // make new indexes saved to methods
        lua_pushcfunction(E->L, Less);
        lua_setfield(E->L, metatable, "__lt");
        // make new indexes saved to methods
        lua_pushcfunction(E->L, LessOrEqual);
        lua_setfield(E->L, metatable, "__le");
        // make new indexes saved to methods
        lua_pushcfunction(E->L, Call);
        lua_setfield(E->L, metatable, "__call");
        // special method to get the object type
        lua_pushcfunction(E->L, GetType);
        lua_setfield(E->L, metatable, "GetObjectType");
        // special method to decide object invalidation at end of call
        lua_pushcfunction(E->L, SetInvalidation);
        lua_setfield(E->L, metatable, "SetInvalidation");
        // pop metatable
        lua_pop(E->L, 1);
    }
References ElunaTemplate< T >::Add(), ASSERT, ElunaTemplate< T >::Call(), ElunaTemplate< T >::CollectGarbage(), ElunaTemplate< T >::Concat(), ElunaTemplate< T >::Divide(), ElunaTemplate< T >::Equal(), ElunaTemplate< T >::GetType(), Eluna::L, ElunaTemplate< T >::Length(), ElunaTemplate< T >::Less(), ElunaTemplate< T >::LessOrEqual(), lua_getglobal(), lua_gettop(), lua_isnoneornil, lua_pop, lua_pushcfunction, lua_pushvalue(), lua_setfield(), lua_setglobal(), luaL_newmetatable(), ElunaTemplate< T >::manageMemory, ElunaTemplate< T >::Mod(), ElunaTemplate< T >::Multiply(), ElunaTemplate< T >::Pow(), ElunaTemplate< T >::SetInvalidation(), ElunaTemplate< T >::Substract(), ElunaTemplate< T >::tname, ElunaTemplate< T >::ToString(), and ElunaTemplate< T >::UnaryMinus().
Referenced by RegisterFunctions().
SetInvalidation()
template<typename T > static int ElunaTemplate< T >::SetInvalidation (lua_State * L) inline static
    {
        ElunaObject* elunaObj = Eluna::CHECKOBJ<ElunaObject>(L, 1);
        bool invalidate = Eluna::CHECKVAL<bool>(L, 2);
        elunaObj->SetValidation(invalidate);
        return 0;
    }
References ElunaObject::SetValidation().
Referenced by ElunaTemplate< T >::Register().
SetMethods()
template<typename T > template<typename C > static void ElunaTemplate< T >::SetMethods (Eluna * E, ElunaRegister< C > * methodTable) inline static
    {
        ASSERT(E);
        ASSERT(tname);
        ASSERT(methodTable);
        // get metatable
        lua_pushstring(E->L, tname);
        lua_rawget(E->L, LUA_REGISTRYINDEX);
        ASSERT(lua_istable(E->L, -1));
        for (; methodTable && methodTable->name && methodTable->mfunc; ++methodTable)
        {
            lua_pushstring(E->L, methodTable->name);
            lua_pushlightuserdata(E->L, (void*)methodTable);
            lua_pushcclosure(E->L, CallMethod, 1);
            lua_rawset(E->L, -3);
        }
        lua_pop(E->L, 1);
    }
References ASSERT, ElunaTemplate< T >::CallMethod(), Eluna::L, lua_istable, lua_pop, lua_pushcclosure(), lua_pushlightuserdata(), lua_pushstring(), lua_rawget(), lua_rawset(), LUA_REGISTRYINDEX, ElunaRegister< T >::mfunc, ElunaRegister< T >::name, and ElunaTemplate< T >::tname.
Referenced by RegisterFunctions().
Substract() [1/3]
template<typename T > static int ElunaTemplate< T >::Substract (lua_State * L) inline static
{ return ArithmeticError(L); }
References ElunaTemplate< T >::ArithmeticError().
Referenced by ElunaTemplate< T >::Register().
Substract() [2/3]
int ElunaTemplate< unsignedlonglong >::Substract (lua_State * L)
{ Eluna::Push(L, Eluna::CHECKVAL<unsigned long long>(L, 1) - Eluna::CHECKVAL<unsigned long long>(L, 2)); return 1; }
References Eluna::Push().
Substract() [3/3]
int ElunaTemplate< longlong >::Substract (lua_State * L)
{ Eluna::Push(L, Eluna::CHECKVAL<long long>(L, 1) - Eluna::CHECKVAL<long long>(L, 2)); return 1; }
References Eluna::Push().
ToString() [1/3]
template<typename T > static int ElunaTemplate< T >::ToString (lua_State * L) inline static
    {
        T* obj = Eluna::CHECKOBJ<T>(L, 1, true); // get self
        lua_pushfstring(L, "%s: %p", tname, obj);
        return 1;
    }
References lua_pushfstring(), and ElunaTemplate< T >::tname.
Referenced by ElunaTemplate< T >::Register().
ToString() [2/3]
int ElunaTemplate< unsignedlonglong >::ToString (lua_State * L)
{
    unsigned long long l = Eluna::CHECKVAL<unsigned long long>(L, 1);
    std::ostringstream ss;
    ss << l;
    Eluna::Push(L, ss.str());
    return 1;
}
References Eluna::Push().
ToString() [3/3]
int ElunaTemplate< longlong >::ToString (lua_State * L)
{
    long long l = Eluna::CHECKVAL<long long>(L, 1);
    std::ostringstream ss;
    ss << l;
    Eluna::Push(L, ss.str());
    return 1;
}
References Eluna::Push().
UnaryMinus() [1/2]
template<typename T > static int ElunaTemplate< T >::UnaryMinus (lua_State * L) inline static
{ return ArithmeticError(L); }
References ElunaTemplate< T >::ArithmeticError().
Referenced by ElunaTemplate< T >::Register().
UnaryMinus() [2/2]
int ElunaTemplate< longlong >::UnaryMinus (lua_State * L)
{ Eluna::Push(L, -Eluna::CHECKVAL<long long>(L, 1)); return 1; }
References Eluna::Push().
Member Data Documentation
manageMemory
template<typename T > bool ElunaTemplate< T >::manageMemory = false static
Referenced by ElunaTemplate< T >::CollectGarbage(), ElunaTemplate< T >::Push(), and ElunaTemplate< T >::Register().
tname
template<typename T > const char * ElunaTemplate< T >::tname = NULL static
Referenced by ElunaTemplate< T >::ArithmeticError(), ElunaTemplate< T >::Call(), ElunaTemplate< T >::Check(), ElunaTemplate< T >::CompareError(), ElunaTemplate< T >::Concat(), ElunaTemplate< T >::GetType(), ElunaTemplate< T >::Length(), ElunaTemplate< T >::Push(), ElunaTemplate< T >::Register(), ElunaTemplate< T >::SetMethods(), and ElunaTemplate< T >::ToString().
The documentation for this class was generated from the following file:
mod-eluna/src/LuaEngine/ElunaTemplate.h