AzerothCore Doxygen
PartyTimeEmoteEvent Class Reference
Public Member Functions
PartyTimeEmoteEvent (Player *player)
bool Execute (uint64, uint32) override
Public Member Functions inherited from BasicEvent
BasicEvent ()=default
virtual ~BasicEvent ()=default
virtual bool IsDeletable () const
virtual void Abort (uint64)
void ScheduleAbort ()
Private Attributes
Player * _player
Detailed Description
Constructor & Destructor Documentation
PartyTimeEmoteEvent()
PartyTimeEmoteEvent::PartyTimeEmoteEvent (Player * player) inline
: _player(player) { }
Member Function Documentation
Execute()
bool PartyTimeEmoteEvent::Execute (uint64 , uint32) inline override virtual
Reimplemented from BasicEvent.
    {
        if (!_player->HasAura(SPELL_PARTY_TIME))
        {
            return true;
        }
        if (_player->isMoving())
        {
            _player->HandleEmoteCommand(RAND(EMOTE_ONESHOT_APPLAUD, EMOTE_ONESHOT_LAUGH, EMOTE_ONESHOT_CHEER, EMOTE_ONESHOT_CHICKEN));
        }
        else
        {
            _player->HandleEmoteCommand(RAND(EMOTE_ONESHOT_APPLAUD, EMOTE_ONESHOT_DANCESPECIAL, EMOTE_ONESHOT_LAUGH, EMOTE_ONESHOT_CHEER, EMOTE_ONESHOT_CHICKEN));
        }
        _player->m_Events.AddEventAtOffset(this, RAND(5s, 10s, 15s));
        return false; // do not delete re-added event in EventProcessor::Update
    }
References _player, EventProcessor::AddEventAtOffset(), EMOTE_ONESHOT_APPLAUD, EMOTE_ONESHOT_CHEER, EMOTE_ONESHOT_CHICKEN, EMOTE_ONESHOT_DANCESPECIAL, EMOTE_ONESHOT_LAUGH, Unit::HandleEmoteCommand(), Unit::HasAura(), Unit::isMoving(), WorldObject::m_Events, RAND(), and SPELL_PARTY_TIME.
Member Data Documentation
_player
Player* PartyTimeEmoteEvent::_player private
Referenced by Execute().
The documentation for this class was generated from the following file:
azerothcore-wotlk/src/server/scripts/Spells/spell_item.cpp