AzerothCore Doxygen
SpellProcTest Class Reference
Test fixture for SpellMgr proc tests.
Protected Member Functions
void SetUp () override
void TearDown () override
SpellInfo * CreateSpellInfo (uint32 id=1, uint32 familyName=0, uint32 familyFlag0=0, uint32 familyFlag1=0, uint32 familyFlag2=0)
Protected Attributes
IWorld * _originalWorld = nullptr
NiceMock< WorldMock > * _worldMock = nullptr
std::vector< SpellInfo * > _spellInfos
Detailed Description
Test fixture for SpellMgr proc tests.
Tests the CanSpellTriggerProcOnEvent function and related proc logic.
Member Function Documentation
CreateSpellInfo()
SpellInfo * SpellProcTest::CreateSpellInfo (uint32 id = 1, uint32 familyName = 0, uint32 familyFlag0 = 0, uint32 familyFlag1 = 0, uint32 familyFlag2 = 0) inline protected
    {
        auto* spellInfo = SpellInfoBuilder()
            .WithId(id)
            .WithSpellFamilyName(familyName)
            .WithSpellFamilyFlags(familyFlag0, familyFlag1, familyFlag2)
            .Build();
        _spellInfos.push_back(spellInfo);
        return spellInfo;
    }
References _spellInfos, SpellInfoBuilder::Build(), SpellInfoBuilder::WithId(), SpellInfoBuilder::WithSpellFamilyFlags(), and SpellInfoBuilder::WithSpellFamilyName().
SetUp()
void SpellProcTest::SetUp () inline override protected
    {
        _originalWorld = sWorld.release();
        _worldMock = new NiceMock<WorldMock>();
        sWorld.reset(_worldMock);
        static std::string emptyString;
        ON_CALL(*_worldMock, GetDataPath()).WillByDefault(ReturnRef(emptyString));
    }
References _originalWorld, _worldMock, and sWorld.
TearDown()
void SpellProcTest::TearDown () inline override protected
    {
        IWorld* currentWorld = sWorld.release();
        delete currentWorld;
        _worldMock = nullptr;
        sWorld.reset(_originalWorld);
        _originalWorld = nullptr;
        // Clean up any SpellInfo objects we created
        for (auto* spellInfo : _spellInfos)
            delete spellInfo;
        _spellInfos.clear();
    }
References _originalWorld, _spellInfos, _worldMock, and sWorld.
Member Data Documentation
_originalWorld
IWorld* SpellProcTest::_originalWorld = nullptr protected
Referenced by SetUp(), and TearDown().
_spellInfos
std::vector<SpellInfo*> SpellProcTest::_spellInfos protected
Referenced by CreateSpellInfo(), and TearDown().
_worldMock
NiceMock<WorldMock>* SpellProcTest::_worldMock = nullptr protected
Referenced by SetUp(), and TearDown().
The documentation for this class was generated from the following file:
azerothcore-wotlk/src/test/server/game/Spells/SpellProcTest.cpp