AzerothCore Doxygen
rigtorp::SPSCQueue< T, Allocator > Class Template Reference
#include "SPSCQueue.h"
Public Member Functions
SPSCQueue (const size_t capacity, const Allocator &allocator=Allocator())
~SPSCQueue ()
SPSCQueue (const SPSCQueue &)=delete
SPSCQueue & operator= (const SPSCQueue &)=delete
template<typename... Args>
void emplace (Args &&...args) noexcept(std::is_nothrow_constructible< T, Args &&... >::value)
template<typename... Args>
bool try_emplace (Args &&...args) noexcept(std::is_nothrow_constructible< T, Args &&... >::value)
void push (const T &v) noexcept(std::is_nothrow_copy_constructible< T >::value)
template<typename P , typename = typename std::enable_if< std::is_constructible<T, P &&>::value>::type>
void push (P &&v) noexcept(std::is_nothrow_constructible< T, P && >::value)
bool try_push (const T &v) noexcept(std::is_nothrow_copy_constructible< T >::value)
template<typename P , typename = typename std::enable_if< std::is_constructible<T, P &&>::value>::type>
bool try_push (P &&v) noexcept(std::is_nothrow_constructible< T, P && >::value)
T * front () noexcept
void pop () noexcept
size_t size () const noexcept
bool empty () const noexcept
size_t capacity () const noexcept
Private Attributes
size_t capacity_
T * slots_
Allocator allocator_
std::atomic< size_t > writeIdx_ = {0}
size_t readIdxCache_ = 0
std::atomic< size_t > readIdx_ = {0}
size_t writeIdxCache_ = 0
char padding_ [kCacheLineSize - sizeof(writeIdxCache_)]
Static Private Attributes
static constexpr size_t kCacheLineSize = 64
static constexpr size_t kPadding = (kCacheLineSize - 1) / sizeof(T) + 1
Detailed Description
template<typename T, typename Allocator = std::allocator<T>>
class rigtorp::SPSCQueue< T, Allocator >
Constructor & Destructor Documentation
SPSCQueue() [1/2]
template<typename T , typename Allocator = std::allocator<T>> rigtorp::SPSCQueue< T, Allocator >::SPSCQueue (const size_t capacity, const Allocator & allocator = Allocator()) inline explicit
      : capacity_(capacity), allocator_(allocator) {
    // The queue needs at least one element
    if (capacity_ < 1) {
      capacity_ = 1;
    }
    capacity_++; // Needs one slack element
    // Prevent overflowing size_t
    if (capacity_ > SIZE_MAX - 2 * kPadding) {
      capacity_ = SIZE_MAX - 2 * kPadding;
    }
#if defined(__cpp_if_constexpr) && defined(__cpp_lib_void_t)
    if constexpr (has_allocate_at_least<Allocator>::value) {
      auto res = allocator_.allocate_at_least(capacity_ + 2 * kPadding);
      slots_ = res.ptr;
      capacity_ = res.count - 2 * kPadding;
    } else {
      slots_ = std::allocator_traits<Allocator>::allocate(
          allocator_, capacity_ + 2 * kPadding);
    }
#else
    slots_ = std::allocator_traits<Allocator>::allocate(
        allocator_, capacity_ + 2 * kPadding);
#endif
    static_assert(alignof(SPSCQueue<T>) == kCacheLineSize, "");
    static_assert(sizeof(SPSCQueue<T>) >= 3 * kCacheLineSize, "");
    assert(reinterpret_cast<char *>(&readIdx_) -
               reinterpret_cast<char *>(&writeIdx_) >=
           static_cast<std::ptrdiff_t>(kCacheLineSize));
  }
References rigtorp::SPSCQueue< T, Allocator >::allocator_, rigtorp::SPSCQueue< T, Allocator >::capacity_, rigtorp::SPSCQueue< T, Allocator >::kCacheLineSize, rigtorp::SPSCQueue< T, Allocator >::kPadding, rigtorp::SPSCQueue< T, Allocator >::readIdx_, rigtorp::SPSCQueue< T, Allocator >::slots_, and rigtorp::SPSCQueue< T, Allocator >::writeIdx_.
~SPSCQueue()
template<typename T , typename Allocator = std::allocator<T>> rigtorp::SPSCQueue< T, Allocator >::~SPSCQueue () inline
               {
    while (front()) {
      pop();
    }
    std::allocator_traits<Allocator>::deallocate(allocator_, slots_,
                                                 capacity_ + 2 * kPadding);
  }
References rigtorp::SPSCQueue< T, Allocator >::allocator_, rigtorp::SPSCQueue< T, Allocator >::capacity_, rigtorp::SPSCQueue< T, Allocator >::front(), rigtorp::SPSCQueue< T, Allocator >::kPadding, rigtorp::SPSCQueue< T, Allocator >::pop(), and rigtorp::SPSCQueue< T, Allocator >::slots_.
SPSCQueue() [2/2]
template<typename T , typename Allocator = std::allocator<T>> rigtorp::SPSCQueue< T, Allocator >::SPSCQueue (const SPSCQueue< T, Allocator > &) delete
Member Function Documentation
capacity()
template<typename T , typename Allocator = std::allocator<T>> size_t rigtorp::SPSCQueue< T, Allocator >::capacity () const inline noexcept
{ return capacity_ - 1; }
References rigtorp::SPSCQueue< T, Allocator >::capacity_.
emplace()
template<typename T , typename Allocator = std::allocator<T>> template<typename... Args> void rigtorp::SPSCQueue< T, Allocator >::emplace (Args &&... args) inline noexcept
{
    static_assert(std::is_constructible<T, Args &&...>::value,
                  "T must be constructible with Args&&...");
    auto const writeIdx = writeIdx_.load(std::memory_order_relaxed);
    auto nextWriteIdx = writeIdx + 1;
    if (nextWriteIdx == capacity_) {
      nextWriteIdx = 0;
    }
    while (nextWriteIdx == readIdxCache_) {
      readIdxCache_ = readIdx_.load(std::memory_order_acquire);
    }
    new (&slots_[writeIdx + kPadding]) T(std::forward<Args>(args)...);
    writeIdx_.store(nextWriteIdx, std::memory_order_release);
  }
References rigtorp::SPSCQueue< T, Allocator >::capacity_, rigtorp::SPSCQueue< T, Allocator >::kPadding, rigtorp::SPSCQueue< T, Allocator >::readIdx_, rigtorp::SPSCQueue< T, Allocator >::readIdxCache_, rigtorp::SPSCQueue< T, Allocator >::slots_, and rigtorp::SPSCQueue< T, Allocator >::writeIdx_.
Referenced by rigtorp::SPSCQueue< T, Allocator >::push(), and rigtorp::SPSCQueue< T, Allocator >::push().
empty()
template<typename T , typename Allocator = std::allocator<T>> bool rigtorp::SPSCQueue< T, Allocator >::empty () const inline noexcept
{ return size() == 0; }
References rigtorp::SPSCQueue< T, Allocator >::size().
Referenced by HttpManager::HandleHttpResponses().
front()
template<typename T , typename Allocator = std::allocator<T>> T * rigtorp::SPSCQueue< T, Allocator >::front () inline noexcept
                      {
    auto const readIdx = readIdx_.load(std::memory_order_relaxed);
    if (readIdx == writeIdxCache_) {
      writeIdxCache_ = writeIdx_.load(std::memory_order_acquire);
      if (writeIdxCache_ == readIdx) {
        return nullptr;
      }
    }
    return &slots_[readIdx + kPadding];
  }
References rigtorp::SPSCQueue< T, Allocator >::kPadding, rigtorp::SPSCQueue< T, Allocator >::readIdx_, rigtorp::SPSCQueue< T, Allocator >::slots_, rigtorp::SPSCQueue< T, Allocator >::writeIdx_, and rigtorp::SPSCQueue< T, Allocator >::writeIdxCache_.
Referenced by HttpManager::ClearQueues(), HttpManager::HandleHttpResponses(), HttpManager::HttpWorkerThread(), and rigtorp::SPSCQueue< T, Allocator >::~SPSCQueue().
operator=()
template<typename T , typename Allocator = std::allocator<T>> SPSCQueue & rigtorp::SPSCQueue< T, Allocator >::operator= (const SPSCQueue< T, Allocator > &) delete
pop()
template<typename T , typename Allocator = std::allocator<T>> void rigtorp::SPSCQueue< T, Allocator >::pop () inline noexcept
                      {
    static_assert(std::is_nothrow_destructible<T>::value,
                  "T must be nothrow destructible");
    auto const readIdx = readIdx_.load(std::memory_order_relaxed);
    assert(writeIdx_.load(std::memory_order_acquire) != readIdx);
    slots_[readIdx + kPadding].~T();
    auto nextReadIdx = readIdx + 1;
    if (nextReadIdx == capacity_) {
      nextReadIdx = 0;
    }
    readIdx_.store(nextReadIdx, std::memory_order_release);
  }
References rigtorp::SPSCQueue< T, Allocator >::capacity_, rigtorp::SPSCQueue< T, Allocator >::kPadding, rigtorp::SPSCQueue< T, Allocator >::readIdx_, rigtorp::SPSCQueue< T, Allocator >::slots_, and rigtorp::SPSCQueue< T, Allocator >::writeIdx_.
Referenced by HttpManager::ClearQueues(), HttpManager::HandleHttpResponses(), HttpManager::HttpWorkerThread(), and rigtorp::SPSCQueue< T, Allocator >::~SPSCQueue().
push() [1/2]
template<typename T , typename Allocator = std::allocator<T>> void rigtorp::SPSCQueue< T, Allocator >::push (const T & v) inline noexcept
{
    static_assert(std::is_copy_constructible<T>::value,
                  "T must be copy constructible");
    emplace(v);
  }
References rigtorp::SPSCQueue< T, Allocator >::emplace().
Referenced by HttpManager::HttpWorkerThread(), and HttpManager::PushRequest().
push() [2/2]
template<typename T , typename Allocator = std::allocator<T>> template<typename P , typename = typename std::enable_if< std::is_constructible<T, P &&>::value>::type> void rigtorp::SPSCQueue< T, Allocator >::push (P && v) inline noexcept
{
    emplace(std::forward<P>(v));
  }
References rigtorp::SPSCQueue< T, Allocator >::emplace().
size()
template<typename T , typename Allocator = std::allocator<T>> size_t rigtorp::SPSCQueue< T, Allocator >::size () const inline noexcept
{
    std::ptrdiff_t diff = writeIdx_.load(std::memory_order_acquire) -
                          readIdx_.load(std::memory_order_acquire);
    if (diff < 0) {
      diff += capacity_;
    }
    return static_cast<size_t>(diff);
  }
References rigtorp::SPSCQueue< T, Allocator >::capacity_, rigtorp::SPSCQueue< T, Allocator >::readIdx_, and rigtorp::SPSCQueue< T, Allocator >::writeIdx_.
Referenced by rigtorp::SPSCQueue< T, Allocator >::empty().
try_emplace()
template<typename T , typename Allocator = std::allocator<T>> template<typename... Args> bool rigtorp::SPSCQueue< T, Allocator >::try_emplace (Args &&... args) inline noexcept
{
    static_assert(std::is_constructible<T, Args &&...>::value,
                  "T must be constructible with Args&&...");
    auto const writeIdx = writeIdx_.load(std::memory_order_relaxed);
    auto nextWriteIdx = writeIdx + 1;
    if (nextWriteIdx == capacity_) {
      nextWriteIdx = 0;
    }
    if (nextWriteIdx == readIdxCache_) {
      readIdxCache_ = readIdx_.load(std::memory_order_acquire);
      if (nextWriteIdx == readIdxCache_) {
        return false;
      }
    }
    new (&slots_[writeIdx + kPadding]) T(std::forward<Args>(args)...);
    writeIdx_.store(nextWriteIdx, std::memory_order_release);
    return true;
  }
References rigtorp::SPSCQueue< T, Allocator >::capacity_, rigtorp::SPSCQueue< T, Allocator >::kPadding, rigtorp::SPSCQueue< T, Allocator >::readIdx_, rigtorp::SPSCQueue< T, Allocator >::readIdxCache_, rigtorp::SPSCQueue< T, Allocator >::slots_, and rigtorp::SPSCQueue< T, Allocator >::writeIdx_.
Referenced by rigtorp::SPSCQueue< T, Allocator >::try_push(), and rigtorp::SPSCQueue< T, Allocator >::try_push().
try_push() [1/2]
template<typename T , typename Allocator = std::allocator<T>> bool rigtorp::SPSCQueue< T, Allocator >::try_push (const T & v) inline noexcept
{
    static_assert(std::is_copy_constructible<T>::value,
                  "T must be copy constructible");
    return try_emplace(v);
  }
References rigtorp::SPSCQueue< T, Allocator >::try_emplace().
try_push() [2/2]
template<typename T , typename Allocator = std::allocator<T>> template<typename P , typename = typename std::enable_if< std::is_constructible<T, P &&>::value>::type> bool rigtorp::SPSCQueue< T, Allocator >::try_push (P && v) inline noexcept
{
    return try_emplace(std::forward<P>(v));
  }
References rigtorp::SPSCQueue< T, Allocator >::try_emplace().
Member Data Documentation
allocator_
template<typename T , typename Allocator = std::allocator<T>> Allocator rigtorp::SPSCQueue< T, Allocator >::allocator_ private
Referenced by rigtorp::SPSCQueue< T, Allocator >::SPSCQueue(), and rigtorp::SPSCQueue< T, Allocator >::~SPSCQueue().
capacity_
template<typename T , typename Allocator = std::allocator<T>> size_t rigtorp::SPSCQueue< T, Allocator >::capacity_ private
Referenced by rigtorp::SPSCQueue< T, Allocator >::capacity(), rigtorp::SPSCQueue< T, Allocator >::emplace(), rigtorp::SPSCQueue< T, Allocator >::pop(), rigtorp::SPSCQueue< T, Allocator >::size(), rigtorp::SPSCQueue< T, Allocator >::SPSCQueue(), rigtorp::SPSCQueue< T, Allocator >::try_emplace(), and rigtorp::SPSCQueue< T, Allocator >::~SPSCQueue().
kCacheLineSize
template<typename T , typename Allocator = std::allocator<T>> constexpr size_t rigtorp::SPSCQueue< T, Allocator >::kCacheLineSize = 64 static constexpr private
Referenced by rigtorp::SPSCQueue< T, Allocator >::SPSCQueue().
kPadding
template<typename T , typename Allocator = std::allocator<T>> constexpr size_t rigtorp::SPSCQueue< T, Allocator >::kPadding = (kCacheLineSize - 1) / sizeof(T) + 1 static constexpr private
Referenced by rigtorp::SPSCQueue< T, Allocator >::emplace(), rigtorp::SPSCQueue< T, Allocator >::front(), rigtorp::SPSCQueue< T, Allocator >::pop(), rigtorp::SPSCQueue< T, Allocator >::SPSCQueue(), rigtorp::SPSCQueue< T, Allocator >::try_emplace(), and rigtorp::SPSCQueue< T, Allocator >::~SPSCQueue().
padding_
template<typename T , typename Allocator = std::allocator<T>> char rigtorp::SPSCQueue< T, Allocator >::padding_[kCacheLineSize - sizeof(writeIdxCache_)] private
readIdx_
template<typename T , typename Allocator = std::allocator<T>> std::atomic<size_t> rigtorp::SPSCQueue< T, Allocator >::readIdx_ = {0} private
{0};
Referenced by rigtorp::SPSCQueue< T, Allocator >::emplace(), rigtorp::SPSCQueue< T, Allocator >::front(), rigtorp::SPSCQueue< T, Allocator >::pop(), rigtorp::SPSCQueue< T, Allocator >::size(), rigtorp::SPSCQueue< T, Allocator >::SPSCQueue(), and rigtorp::SPSCQueue< T, Allocator >::try_emplace().
readIdxCache_
template<typename T , typename Allocator = std::allocator<T>> size_t rigtorp::SPSCQueue< T, Allocator >::readIdxCache_ = 0 private
Referenced by rigtorp::SPSCQueue< T, Allocator >::emplace(), and rigtorp::SPSCQueue< T, Allocator >::try_emplace().
slots_
template<typename T , typename Allocator = std::allocator<T>> T* rigtorp::SPSCQueue< T, Allocator >::slots_ private
Referenced by rigtorp::SPSCQueue< T, Allocator >::emplace(), rigtorp::SPSCQueue< T, Allocator >::front(), rigtorp::SPSCQueue< T, Allocator >::pop(), rigtorp::SPSCQueue< T, Allocator >::SPSCQueue(), rigtorp::SPSCQueue< T, Allocator >::try_emplace(), and rigtorp::SPSCQueue< T, Allocator >::~SPSCQueue().
writeIdx_
template<typename T , typename Allocator = std::allocator<T>> std::atomic<size_t> rigtorp::SPSCQueue< T, Allocator >::writeIdx_ = {0} private
{0};
Referenced by rigtorp::SPSCQueue< T, Allocator >::emplace(), rigtorp::SPSCQueue< T, Allocator >::front(), rigtorp::SPSCQueue< T, Allocator >::pop(), rigtorp::SPSCQueue< T, Allocator >::size(), rigtorp::SPSCQueue< T, Allocator >::SPSCQueue(), and rigtorp::SPSCQueue< T, Allocator >::try_emplace().
writeIdxCache_
template<typename T , typename Allocator = std::allocator<T>> size_t rigtorp::SPSCQueue< T, Allocator >::writeIdxCache_ = 0 private
Referenced by rigtorp::SPSCQueue< T, Allocator >::front().
The documentation for this class was generated from the following file:
mod-eluna/src/LuaEngine/libs/rigtorp/SPSCQueue.h