AzerothCore Doxygen
VMAP::VMapMgr2 Class Reference
#include "VMapMgr2.h"
Public Types
typedef uint32(* GetLiquidFlagsFn) (uint32 liquidType)
typedef bool(* IsVMAPDisabledForFn) (uint32 entry, uint8 flags)
Public Member Functions
VMapMgr2 ()
~VMapMgr2 () override
bool processCommand (char *) override
std::string getDirFileName (unsigned int mapId, int, int) const override
LoadResult existsMap (const char *basePath, unsigned int mapId, int x, int y) override
Public Member Functions inherited from VMAP::IVMapMgr
IVMapMgr ()
virtual ~IVMapMgr ()=default
void setEnableLineOfSightCalc (bool pVal)
void setEnableHeightCalc (bool pVal)
bool isLineOfSightCalcEnabled () const
bool isHeightCalcEnabled () const
bool isMapLoadingEnabled () const
Static Public Member Functions
static G3D::Vector3 convertPositionToInternalRep (float x, float y, float z)
static std::string getMapFileName (unsigned int mapId)
Public Attributes
GetLiquidFlagsFn GetLiquidFlagsPtr
IsVMAPDisabledForFn IsVMAPDisabledForPtr
Static Protected Member Functions
static uint32 GetLiquidFlagsDummy (uint32)
static bool IsVMAPDisabledForDummy (uint32, uint8)
Detailed Description
Member Typedef Documentation
GetLiquidFlagsFn
typedef uint32(* VMAP::VMapMgr2::GetLiquidFlagsFn) (uint32 liquidType)
IsVMAPDisabledForFn
typedef bool(* VMAP::VMapMgr2::IsVMAPDisabledForFn) (uint32 entry, uint8 flags)
Constructor & Destructor Documentation
VMapMgr2()
VMAP::VMapMgr2::VMapMgr2 ()
    {
        GetLiquidFlagsPtr = &GetLiquidFlagsDummy;
        IsVMAPDisabledForPtr = &IsVMAPDisabledForDummy;
    }
References GetLiquidFlagsDummy(), GetLiquidFlagsPtr, IsVMAPDisabledForDummy(), and IsVMAPDisabledForPtr.
~VMapMgr2()
VMAP::VMapMgr2::~VMapMgr2 () override
    {
    }
Member Function Documentation
convertPositionToInternalRep()
Vector3 VMAP::VMapMgr2::convertPositionToInternalRep (float x, float y, float z) static
    {
        Vector3 pos;
        const float mid = 0.5f * MAX_NUMBER_OF_GRIDS * SIZE_OF_GRIDS;
        pos.x = mid - x;
        pos.y = mid - y;
        pos.z = z;
        return pos;
    }
References MAX_NUMBER_OF_GRIDS, and SIZE_OF_GRIDS.
Referenced by StaticVMapCollisionData::GetAreaAndLiquidData(), StaticVMapCollisionData::getHeight(), StaticVMapCollisionData::GetObjectHitPos(), and StaticVMapCollisionData::isInLineOfSight().
existsMap()
LoadResult VMAP::VMapMgr2::existsMap (const char * basePath, unsigned int mapId, int x, int y) override virtual
Implements VMAP::IVMapMgr.
    {
        return StaticMapTree::CanLoadMap(std::string(basePath), mapId, x, y);
    }
References VMAP::StaticMapTree::CanLoadMap().
getDirFileName()
std::string VMAP::VMapMgr2::getDirFileName (unsigned int mapId, int , int) const inline override virtual
Implements VMAP::IVMapMgr.
        {
            return getMapFileName(mapId);
        }
References getMapFileName().
GetLiquidFlagsDummy()
static uint32 VMAP::VMapMgr2::GetLiquidFlagsDummy (uint32) inline static protected
{ return 0; }
Referenced by VMapMgr2().
getMapFileName()
std::string VMAP::VMapMgr2::getMapFileName (unsigned int mapId) static
    {
        std::stringstream fname;
        fname.width(3);
        fname << std::setfill('0') << mapId << std::string(MAP_FILENAME_EXTENSION2);
        return fname.str();
    }
References MAP_FILENAME_EXTENSION2.
Referenced by VMAP::StaticMapTree::CanLoadMap(), getDirFileName(), MMAP::TerrainBuilder::loadVMap(), and MapCollisionData::MapCollisionData().
IsVMAPDisabledForDummy()
static bool VMAP::VMapMgr2::IsVMAPDisabledForDummy (uint32 , uint8) inline static protected
{ return false; }
Referenced by VMapMgr2().
processCommand()
bool VMAP::VMapMgr2::processCommand (char * pCommand) inline override virtual
send debug commands
Implements VMAP::IVMapMgr.
{ return false; } // for debug and extensions
Member Data Documentation
GetLiquidFlagsPtr
GetLiquidFlagsFn VMAP::VMapMgr2::GetLiquidFlagsPtr
Referenced by World::SetInitialWorldSettings(), and VMapMgr2().
IsVMAPDisabledForPtr
IsVMAPDisabledForFn VMAP::VMapMgr2::IsVMAPDisabledForPtr
Referenced by World::SetInitialWorldSettings(), and VMapMgr2().
The documentation for this class was generated from the following files:
azerothcore-wotlk/src/common/Collision/Management/VMapMgr2.h
azerothcore-wotlk/src/common/Collision/Management/VMapMgr2.cpp