AzerothCore Doxygen
ElunaUtil Namespace Reference
Classes
class Lockable
class ObjectDistanceOrderPred
class ObjectGUIDCheck
class WorldObjectInRangeCheck
Functions
uint32 GetCurrTime ()
uint32 GetTimeDiff (uint32 oldMSTime)
void EncodeData (const unsigned char *data, size_t input_length, std::string &output)
unsigned char * DecodeData (const char *data, size_t *output_length)
Function Documentation
DecodeData()
unsigned char * ElunaUtil::DecodeData (const char * data, size_t * output_length)
{
    if (decoding_table[(unsigned char)'B'] == 0)
        build_decoding_table();
    size_t input_length = strlen(data);
    if (input_length % 4 != 0)
        return NULL;
    // Make sure there's no invalid characters in the data.
    for (size_t i = 0; i < input_length; ++i)
    {
        unsigned char byte = data[i];
        if (byte == '=')
            continue;
        // Every invalid character (and 'A') will map to 0 (due to `calloc`).
        if (decoding_table[byte] == 0 && byte != 'A')
            return NULL;
    }
    *output_length = input_length / 4 * 3;
    if (data[input_length - 1] == '=') (*output_length)--;
    if (data[input_length - 2] == '=') (*output_length)--;
    unsigned char *decoded_data = new unsigned char[*output_length];
    if (!decoded_data)
        return NULL;
    for (size_t i = 0, j = 0; i < input_length;)
    {
        uint32 sextet_a = data[i] == '=' ? 0 & i++ : decoding_table[(unsigned char)data[i++]];
        uint32 sextet_b = data[i] == '=' ? 0 & i++ : decoding_table[(unsigned char)data[i++]];
        uint32 sextet_c = data[i] == '=' ? 0 & i++ : decoding_table[(unsigned char)data[i++]];
        uint32 sextet_d = data[i] == '=' ? 0 & i++ : decoding_table[(unsigned char)data[i++]];
        uint32 triple = (sextet_a << (3 * 6))
        + (sextet_b << (2 * 6))
        + (sextet_c << (1 * 6))
        + (sextet_d << (0 * 6));
        if (j < *output_length) decoded_data[j++] = (triple >> (2 * 8)) & 0xFF;
        if (j < *output_length) decoded_data[j++] = (triple >> (1 * 8)) & 0xFF;
        if (j < *output_length) decoded_data[j++] = (triple >> (0 * 8)) & 0xFF;
    }
    return decoded_data;
}
References build_decoding_table(), and decoding_table.
Referenced by ElunaInstanceAI::Load().
EncodeData()
void ElunaUtil::EncodeData (const unsigned char * data, size_t input_length, std::string & output)
{
    size_t output_length = 4 * ((input_length + 2) / 3);
    char* buffer = new char[output_length];
    for (size_t i = 0, j = 0; i < input_length;)
    {
        uint32 octet_a = i < input_length ? (unsigned char)data[i++] : 0;
        uint32 octet_b = i < input_length ? (unsigned char)data[i++] : 0;
        uint32 octet_c = i < input_length ? (unsigned char)data[i++] : 0;
        uint32 triple = (octet_a << 0x10) + (octet_b << 0x08) + octet_c;
        buffer[j++] = encoding_table[(triple >> (3 * 6)) & 0x3F];
        buffer[j++] = encoding_table[(triple >> (2 * 6)) & 0x3F];
        buffer[j++] = encoding_table[(triple >> (1 * 6)) & 0x3F];
        buffer[j++] = encoding_table[(triple >> (0 * 6)) & 0x3F];
    }
    for (int i = 0; i < mod_table[input_length % 3]; i++)
        buffer[output_length - 1 - i] = '=';
    output.assign(buffer, output_length); // Need length because `buffer` is not terminated!
    delete[] buffer;
}
References encoding_table, and mod_table.
Referenced by ElunaInstanceAI::Save().
GetCurrTime()
uint32 ElunaUtil::GetCurrTime ()
{
    return getMSTime();
}
References getMSTime().
Referenced by LuaGlobalFunctions::GetCurrTime(), Eluna::LoadScriptPaths(), and Eluna::RunScripts().
GetTimeDiff()
uint32 ElunaUtil::GetTimeDiff (uint32 oldMSTime)
{
    return GetMSTimeDiffToNow(oldMSTime);
}
References GetMSTimeDiffToNow().
Referenced by LuaGlobalFunctions::GetTimeDiff(), Eluna::LoadScriptPaths(), and Eluna::RunScripts().