AzerothCore Doxygen
LuaGroup Namespace Reference
Functions
int IsLeader (lua_State *L, Group *group)
int IsFull (lua_State *L, Group *group)
int IsLFGGroup (lua_State *L, Group *group)
int IsRaidGroup (lua_State *L, Group *group)
int IsBGGroup (lua_State *L, Group *group)
int IsMember (lua_State *L, Group *group)
int IsAssistant (lua_State *L, Group *group)
int SameSubGroup (lua_State *L, Group *group)
int HasFreeSlotSubGroup (lua_State *L, Group *group)
int AddMember (lua_State *L, Group *group)
int GetMembers (lua_State *L, Group *group)
int GetLeaderGUID (lua_State *L, Group *group)
int GetGUID (lua_State *L, Group *group)
int GetMemberGUID (lua_State *L, Group *group)
int GetMembersCount (lua_State *L, Group *group)
int GetGroupType (lua_State *L, Group *group)
int GetMemberGroup (lua_State *L, Group *group)
int SetLeader (lua_State *L, Group *group)
int SendPacket (lua_State *L, Group *group)
int RemoveMember (lua_State *L, Group *group)
int Disband (lua_State *, Group *group)
int ConvertToRaid (lua_State *, Group *group)
int SetMembersGroup (lua_State *L, Group *group)
int SetTargetIcon (lua_State *L, Group *group)
int SetMemberFlag (lua_State *L, Group *group)
Function Documentation
AddMember()
int LuaGroup::AddMember (lua_State * L, Group * group)
Adds a new member to the [Group]
Parameters
[Player] player : [Player] to add to the group
Returns
bool added : true if member was added
    {
        Player* player = Eluna::CHECKOBJ<Player>(L, 2);
        if (player->GetGroup() || !group->IsCreated() || group->IsFull())
        {
            Eluna::Push(L, false);
            return 1;
        }
        if (player->GetGroupInvite())
            player->UninviteFromGroup();
#if defined TRINITY || AZEROTHCORE
        bool success = group->AddMember(player);
        if (success)
            group->BroadcastGroupUpdate();
#else
        bool success = group->AddMember(player->GetObjectGuid(), player->GetName());
#endif
        Eluna::Push(L, success);
        return 1;
    }
References Group::AddMember(), Group::BroadcastGroupUpdate(), Player::GetGroup(), Player::GetGroupInvite(), WorldObject::GetName(), Group::IsCreated(), Group::IsFull(), Eluna::Push(), and Player::UninviteFromGroup().
ConvertToRaid()
int LuaGroup::ConvertToRaid (lua_State * , Group * group)
Converts this [Group] to a raid [Group]
    {
        group->ConvertToRaid();
        return 0;
    }
References Group::ConvertToRaid().
Disband()
int LuaGroup::Disband (lua_State * , Group * group)
Disbands this [Group]
    {
        group->Disband();
        return 0;
    }
References Group::Disband().
GetGroupType()
int LuaGroup::GetGroupType (lua_State * L, Group * group)
Returns the type of this [Group]
enum GroupType
{
    GROUPTYPE_NORMAL         = 0,
    GROUPTYPE_BG             = 1,
    GROUPTYPE_RAID           = 2,
    GROUPTYPE_LFG_RESTRICTED = 4,
    GROUPTYPE_LFG            = 8
};
Returns
[GroupType] groupType
    {
        Eluna::Push(L, group->GetGroupType());
        return 1;
    }
References Group::GetGroupType(), and Eluna::Push().
GetGUID()
int LuaGroup::GetGUID (lua_State * L, Group * group)
Returns the [Group]'s GUID
Returns
ObjectGuid groupGUID
    {
#ifdef CLASSIC
        Eluna::Push(L, group->GetId());
#else
        Eluna::Push(L, group->GET_GUID());
#endif
        return 1;
    }
References Eluna::Push().
GetLeaderGUID()
int LuaGroup::GetLeaderGUID (lua_State * L, Group * group)
Returns [Group] leader GUID
Returns
ObjectGuid leaderGUID
    {
#if defined TRINITY || AZEROTHCORE
        Eluna::Push(L, group->GetLeaderGUID());
#else
        Eluna::Push(L, group->GetLeaderGuid());
#endif
        return 1;
    }
References Group::GetLeaderGUID(), and Eluna::Push().
GetMemberGroup()
int LuaGroup::GetMemberGroup (lua_State * L, Group * group)
Returns the [Player]'s subgroup ID of this [Group]
Parameters
ObjectGuid guid : guid of the player
Returns
uint8 subGroupID : a valid subgroup ID or MAX_RAID_SUBGROUPS+1
    {
        ObjectGuid guid = Eluna::CHECKVAL<ObjectGuid>(L, 2);
        Eluna::Push(L, group->GetMemberGroup(guid));
        return 1;
    }
References Group::GetMemberGroup(), and Eluna::Push().
GetMemberGUID()
int LuaGroup::GetMemberGUID (lua_State * L, Group * group)
Returns a [Group] member's GUID by their name
Parameters
string name : the [Player]'s name
Returns
ObjectGuid memberGUID
    {
        const char* name = Eluna::CHECKVAL<const char*>(L, 2);
#if defined TRINITY || AZEROTHCORE
        Eluna::Push(L, group->GetMemberGUID(name));
#else
        Eluna::Push(L, group->GetMemberGuid(name));
#endif
        return 1;
    }
References Group::GetMemberGUID(), and Eluna::Push().
GetMembers()
int LuaGroup::GetMembers (lua_State * L, Group * group)
Returns a table with the [Player]s in this [Group]
Returns
table groupPlayers : table of [Player]s
    {
        lua_newtable(L);
        int tbl = lua_gettop(L);
        uint32 i = 0;
        for (GroupReference* itr = group->GetFirstMember(); itr; itr = itr->next())
        {
#if defined TRINITY || AZEROTHCORE
            Player* member = itr->GetSource();
#else
            Player* member = itr->getSource();
#endif
            if (!member || !member->GetSession())
                continue;
            Eluna::Push(L, member);
            lua_rawseti(L, tbl, ++i);
        }
        lua_settop(L, tbl); // push table to top of stack
        return 1;
    }
References Group::GetFirstMember(), Player::GetSession(), lua_gettop(), lua_newtable, lua_rawseti(), lua_settop(), and Eluna::Push().
GetMembersCount()
int LuaGroup::GetMembersCount (lua_State * L, Group * group)
Returns the member count of this [Group]
Returns
uint32 memberCount
    {
        Eluna::Push(L, group->GetMembersCount());
        return 1;
    }
References Group::GetMembersCount(), and Eluna::Push().
HasFreeSlotSubGroup()
int LuaGroup::HasFreeSlotSubGroup (lua_State * L, Group * group)
Returns 'true' if the subgroup has free slots in this [Group]
Parameters
uint8 subGroup : subGroup ID to check
Returns
bool hasFreeSlot
    {
        uint8 subGroup = Eluna::CHECKVAL<uint8>(L, 2);
        if (subGroup >= MAX_RAID_SUBGROUPS)
        {
            luaL_argerror(L, 2, "valid subGroup ID expected");
            return 0;
        }
        Eluna::Push(L, group->HasFreeSlotSubGroup(subGroup));
        return 1;
    }
References Group::HasFreeSlotSubGroup(), luaL_argerror(), MAX_RAID_SUBGROUPS, and Eluna::Push().
IsAssistant()
int LuaGroup::IsAssistant (lua_State * L, Group * group)
Returns 'true' if the [Player] is an assistant of this [Group]
Parameters
ObjectGuid guid : guid of a player
Returns
bool isAssistant
    {
        ObjectGuid guid = Eluna::CHECKVAL<ObjectGuid>(L, 2);
        Eluna::Push(L, group->IsAssistant(guid));
        return 1;
    }
References Group::IsAssistant(), and Eluna::Push().
IsBGGroup()
int LuaGroup::IsBGGroup (lua_State * L, Group * group)
Returns 'true' if the [Group] is a battleground [Group]
Returns
bool isBG
    {
        Eluna::Push(L, group->isBGGroup());
        return 1;
    }
References Group::isBGGroup(), and Eluna::Push().
IsFull()
int LuaGroup::IsFull (lua_State * L, Group * group)
Returns 'true' if the [Group] is full
Returns
bool isFull
    {
        Eluna::Push(L, group->IsFull());
        return 1;
    }
References Group::IsFull(), and Eluna::Push().
IsLeader()
int LuaGroup::IsLeader (lua_State * L, Group * group)
Returns 'true' if the [Player] is the [Group] leader
Parameters
ObjectGuid guid : guid of a possible leader
Returns
bool isLeader
    {
        ObjectGuid guid = Eluna::CHECKVAL<ObjectGuid>(L, 2);
        Eluna::Push(L, group->IsLeader(guid));
        return 1;
    }
References Group::IsLeader(), and Eluna::Push().
IsLFGGroup()
int LuaGroup::IsLFGGroup (lua_State * L, Group * group)
Returns 'true' if the [Group] is a LFG group
Returns
bool isLFGGroup
    {
        Eluna::Push(L, group->isLFGGroup());
        return 1;
    }
References Group::isLFGGroup(), and Eluna::Push().
IsMember()
int LuaGroup::IsMember (lua_State * L, Group * group)
Returns 'true' if the [Player] is a member of this [Group]
Parameters
ObjectGuid guid : guid of a player
Returns
bool isMember
    {
        ObjectGuid guid = Eluna::CHECKVAL<ObjectGuid>(L, 2);
        Eluna::Push(L, group->IsMember(guid));
        return 1;
    }
References Group::IsMember(), and Eluna::Push().
IsRaidGroup()
int LuaGroup::IsRaidGroup (lua_State * L, Group * group)
Returns 'true' if the [Group] is a raid [Group]
Returns
bool isRaid
    {
        Eluna::Push(L, group->isRaidGroup());
        return 1;
    }
References Group::isRaidGroup(), and Eluna::Push().
RemoveMember()
int LuaGroup::RemoveMember (lua_State * L, Group * group)
Removes a [Player] from this [Group] and returns 'true' if successful
enum RemoveMethod
{
    GROUP_REMOVEMETHOD_DEFAULT  = 0,
    GROUP_REMOVEMETHOD_KICK     = 1,
    GROUP_REMOVEMETHOD_LEAVE    = 2,
    GROUP_REMOVEMETHOD_KICK_LFG = 3
};
Parameters
ObjectGuid guid : guid of the player to remove
[RemoveMethod] method : method used to remove the player
Returns
bool removed
    {
        ObjectGuid guid = Eluna::CHECKVAL<ObjectGuid>(L, 2);
        uint32 method = Eluna::CHECKVAL<uint32>(L, 3, 0);
#if defined TRINITY || AZEROTHCORE
        Eluna::Push(L, group->RemoveMember(guid, (RemoveMethod)method));
#else
        Eluna::Push(L, group->RemoveMember(guid, method));
#endif
        return 1;
    }
References Eluna::Push(), and Group::RemoveMember().
SameSubGroup()
int LuaGroup::SameSubGroup (lua_State * L, Group * group)
Returns 'true' if the [Player]s are in the same subgroup in this [Group]
Parameters
[Player] player1 : first [Player] to check
[Player] player2 : second [Player] to check
Returns
bool sameSubGroup
    {
        Player* player1 = Eluna::CHECKOBJ<Player>(L, 2);
        Player* player2 = Eluna::CHECKOBJ<Player>(L, 3);
        Eluna::Push(L, group->SameSubGroup(player1, player2));
        return 1;
    }
References Eluna::Push(), and Group::SameSubGroup().
SendPacket()
int LuaGroup::SendPacket (lua_State * L, Group * group)
Sends a specified [WorldPacket] to this [Group]
Parameters
[WorldPacket] packet : the [WorldPacket] to send
bool ignorePlayersInBg : ignores [Player]s in a battleground
ObjectGuid ignore : ignore a [Player] by their GUID
    {
        WorldPacket* data = Eluna::CHECKOBJ<WorldPacket>(L, 2);
        bool ignorePlayersInBg = Eluna::CHECKVAL<bool>(L, 3);
        ObjectGuid ignore = Eluna::CHECKVAL<ObjectGuid>(L, 4);
#ifdef CMANGOS
        group->BroadcastPacket(*data, ignorePlayersInBg, -1, ignore);
#else
        group->BroadcastPacket(data, ignorePlayersInBg, -1, ignore);
#endif
        return 0;
    }
References Group::BroadcastPacket().
SetLeader()
int LuaGroup::SetLeader (lua_State * L, Group * group)
Sets the leader of this [Group]
Parameters
ObjectGuid guid : guid of the new leader
    {
        ObjectGuid guid = Eluna::CHECKVAL<ObjectGuid>(L, 2);
        group->ChangeLeader(guid);
        group->SendUpdate();
        return 0;
    }
References Group::ChangeLeader(), and Group::SendUpdate().
SetMemberFlag()
int LuaGroup::SetMemberFlag (lua_State * L, Group * group)
Sets or removes a flag for a [Group] member
enum GroupMemberFlags
{
    MEMBER_FLAG_ASSISTANT   = 0x01,
    MEMBER_FLAG_MAINTANK    = 0x02,
    MEMBER_FLAG_MAINASSIST  = 0x04,
};
Parameters
ObjectGuid target : GUID of the target
bool apply : add the flag if true, remove the flag otherwise
[GroupMemberFlags] flag : the flag to set or unset
    {
        ObjectGuid target = Eluna::CHECKVAL<ObjectGuid>(L, 2);
        bool apply = Eluna::CHECKVAL<bool>(L, 3);
        GroupMemberFlags flag = static_cast<GroupMemberFlags>(Eluna::CHECKVAL<uint32>(L, 4));
        group->SetGroupMemberFlag(target, apply, flag);
        return 0;
    }
References Group::SetGroupMemberFlag().
SetMembersGroup()
int LuaGroup::SetMembersGroup (lua_State * L, Group * group)
Sets the member's subGroup
Parameters
ObjectGuid guid : guid of the player to move
uint8 groupID : the subGroup's ID
    {
        ObjectGuid guid = Eluna::CHECKVAL<ObjectGuid>(L, 2);
        uint8 subGroup = Eluna::CHECKVAL<uint8>(L, 3);
        if (subGroup >= MAX_RAID_SUBGROUPS)
        {
            luaL_argerror(L, 3, "valid subGroup ID expected");
            return 0;
        }
        if (!group->HasFreeSlotSubGroup(subGroup))
            return 0;
        group->ChangeMembersGroup(guid, subGroup);
        return 0;
    }
References Group::ChangeMembersGroup(), Group::HasFreeSlotSubGroup(), luaL_argerror(), and MAX_RAID_SUBGROUPS.
SetTargetIcon()
int LuaGroup::SetTargetIcon (lua_State * L, Group * group)
Sets the target icon of an object for the [Group]
Parameters
uint8 icon : the icon (Skull, Square, etc)
ObjectGuid target : GUID of the icon target, 0 is to clear the icon
ObjectGuid setter : GUID of the icon setter
    {
        uint8 icon = Eluna::CHECKVAL<uint8>(L, 2);
        ObjectGuid target = Eluna::CHECKVAL<ObjectGuid>(L, 3);
        ObjectGuid setter = Eluna::CHECKVAL<ObjectGuid>(L, 4, ObjectGuid());
        if (icon >= TARGETICONCOUNT)
            return luaL_argerror(L, 2, "valid target icon expected");
#if (defined(CLASSIC) || defined(TBC))
        group->SetTargetIcon(icon, target);
#else
        group->SetTargetIcon(icon, setter, target);
#endif
        return 0;
    }
References luaL_argerror(), Group::SetTargetIcon(), and TARGETICONCOUNT.