AzerothCore Doxygen
HealInfoStubBuilder Class Reference
Builder for creating HealInfoStub instances with fluent API.
#include "DamageHealInfoStub.h"
Public Member Functions
HealInfoStubBuilder ()=default
HealInfoStubBuilder & WithHeal (uint32_t heal)
HealInfoStubBuilder & WithEffectiveHeal (uint32_t effectiveHeal)
HealInfoStubBuilder & WithOverheal (uint32_t overheal)
HealInfoStubBuilder & WithAbsorb (uint32_t absorb)
HealInfoStubBuilder & WithSpellInfo (SpellInfo const *spellInfo)
HealInfoStubBuilder & WithHitMask (uint32_t hitMask)
HealInfoStub Build ()
Private Attributes
HealInfoStub _stub
Detailed Description
Builder for creating HealInfoStub instances with fluent API.
Constructor & Destructor Documentation
HealInfoStubBuilder()
HealInfoStubBuilder::HealInfoStubBuilder () default
Member Function Documentation
Build()
HealInfoStub HealInfoStubBuilder::Build () inline
{ return _stub; }
References _stub.
WithAbsorb()
HealInfoStubBuilder & HealInfoStubBuilder::WithAbsorb (uint32_t absorb) inline
    {
        _stub.SetAbsorb(absorb);
        return *this;
    }
References _stub, and HealInfoStub::SetAbsorb().
WithEffectiveHeal()
HealInfoStubBuilder & HealInfoStubBuilder::WithEffectiveHeal (uint32_t effectiveHeal) inline
    {
        _stub.SetEffectiveHeal(effectiveHeal);
        return *this;
    }
References _stub, and HealInfoStub::SetEffectiveHeal().
WithHeal()
HealInfoStubBuilder & HealInfoStubBuilder::WithHeal (uint32_t heal) inline
    {
        _stub.SetHeal(heal);
        _stub.SetEffectiveHeal(heal); // Assume all effective unless overridden
        return *this;
    }
References _stub, HealInfoStub::SetEffectiveHeal(), and HealInfoStub::SetHeal().
WithHitMask()
HealInfoStubBuilder & HealInfoStubBuilder::WithHitMask (uint32_t hitMask) inline
    {
        _stub.SetHitMask(hitMask);
        return *this;
    }
References _stub, and HealInfoStub::SetHitMask().
WithOverheal()
HealInfoStubBuilder & HealInfoStubBuilder::WithOverheal (uint32_t overheal) inline
    {
        // Overheal = Heal - EffectiveHeal
        // So EffectiveHeal = Heal - Overheal
        if (_stub.GetHeal() >= overheal)
        {
            _stub.SetEffectiveHeal(_stub.GetHeal() - overheal);
        }
        return *this;
    }
References _stub, HealInfoStub::GetHeal(), and HealInfoStub::SetEffectiveHeal().
WithSpellInfo()
HealInfoStubBuilder & HealInfoStubBuilder::WithSpellInfo (SpellInfo const * spellInfo) inline
    {
        _stub.SetSpellInfo(spellInfo);
        return *this;
    }
References _stub, and HealInfoStub::SetSpellInfo().
Member Data Documentation
_stub
HealInfoStub HealInfoStubBuilder::_stub private
Referenced by Build(), WithAbsorb(), WithEffectiveHeal(), WithHeal(), WithHitMask(), WithOverheal(), and WithSpellInfo().
The documentation for this class was generated from the following file:
azerothcore-wotlk/src/test/mocks/DamageHealInfoStub.h