AzerothCore Doxygen
go_brewfest_music::go_brewfest_musicAI Struct Reference
Public Member Functions
go_brewfest_musicAI (GameObject *go)
void UpdateAI (uint32 diff) override
Public Member Functions inherited from GameObjectAI
GameObjectAI (GameObject *go)
virtual ~GameObjectAI ()
virtual void InitializeAI ()
virtual void Reset ()
virtual void DoAction (int32)
virtual void SetGUID (ObjectGuid, int32)
virtual ObjectGuid GetGUID (int32) const
virtual bool GossipHello (Player *, bool)
virtual bool GossipSelect (Player *, uint32, uint32)
virtual bool GossipSelectCode (Player *, uint32, uint32, char const *)
virtual bool QuestAccept (Player *, Quest const *)
virtual bool QuestReward (Player *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *)
virtual void Destroyed (Player *, uint32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void OnGameEvent (bool, uint16)
virtual void OnStateChanged (uint32, Unit *)
virtual void EventInform (uint32)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual bool CanBeSeen (Player const *)
virtual void JustSummoned (Creature *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureEvade (Creature *)
Private Attributes
EventMap _events
uint32 _currentMusicEvent
Additional Inherited Members
Static Public Member Functions inherited from GameObjectAI
static int32 Permissible (GameObject const *go)
Protected Attributes inherited from GameObjectAI
GameObject *const me
Detailed Description
Constructor & Destructor Documentation
go_brewfest_musicAI()
go_brewfest_music::go_brewfest_musicAI::go_brewfest_musicAI (GameObject * go) inline
                                            : GameObjectAI(go)
        {
            _events.ScheduleEvent(EVENT_BM_SELECT_MUSIC, 1000);
            _events.ScheduleEvent(EVENT_BM_START_MUSIC, 1500);
            _currentMusicEvent = EVENT_BREWFESTGOBLIN01;
        }
References _currentMusicEvent, _events, EVENT_BM_SELECT_MUSIC, EVENT_BM_START_MUSIC, EVENT_BREWFESTGOBLIN01, and EventMap::ScheduleEvent().
Member Function Documentation
UpdateAI()
void go_brewfest_music::go_brewfest_musicAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from GameObjectAI.
        {
            _events.Update(diff);
            while (uint32 eventId = _events.ExecuteEvent())
            {
                switch (eventId)
                {
                    case EVENT_BM_SELECT_MUSIC:
{
                            if (!IsHolidayActive(HOLIDAY_BREWFEST)) // Check if Brewfest is active
                                break;
                            // Select random music sample
                            uint32 rnd = urand(0, 2);
                            uint32 musicTime = 1000;
                            //Restart the current selected music
                            _currentMusicEvent = 0;
                            //Check zone to play correct music
                            if (me->GetAreaId() == AREA_EVERSONG_WOODS || me->GetAreaId() == AREA_UNDERCITY || me->GetAreaId() == AREA_ROCKTUSK_FARM || me->GetAreaId() == AREA_DUROTAR || me->GetAreaId() == AREA_THUNDER_BLUFF)
{
                                switch (rnd)
{
                                    case 0:
                                        _currentMusicEvent = EVENT_BREWFESTGOBLIN01;
                                        musicTime = EVENT_BREWFESTGOBLIN01_TIME;
                                        break;
                                    case 1:
                                        _currentMusicEvent = EVENT_BREWFESTGOBLIN02;
                                        musicTime = EVENT_BREWFESTGOBLIN02_TIME;
                                        break;
                                    case 2:
                                        _currentMusicEvent = EVENT_BREWFESTGOBLIN03;
                                        musicTime = EVENT_BREWFESTGOBLIN03_TIME;
                                        break;
                                    default:
                                        break;
                                }
                            }
                            else if (me->GetAreaId() == AREA_GATES_OF_IRONFORGE || me->GetAreaId() == AREA_DUN_MOROGH || me->GetAreaId() == AREA_ELWYNN_FOREST || me->GetAreaId() == AREA_THE_EXODAR || me->GetAreaId() == AREA_DARNASSUS)
{
                                switch (rnd)
{
                                    case 0:
                                        _currentMusicEvent = EVENT_BREWFESTDWARF01;
                                        musicTime = EVENT_BREWFESTDWARF01_TIME;
                                        break;
                                    case 1:
                                        _currentMusicEvent = EVENT_BREWFESTDWARF02;
                                        musicTime = EVENT_BREWFESTDWARF02_TIME;
                                        break;
                                    case 2:
                                        _currentMusicEvent = EVENT_BREWFESTDWARF03;
                                        musicTime = EVENT_BREWFESTDWARF03_TIME;
                                        break;
                                    default:
                                        break;
                                }
                            }
                            else if (me->GetAreaId() == AREA_SHATTRATH_CITY)
{
                                rnd = urand(0, 5);
                                switch (rnd)
{
                                    case 0:
                                        _currentMusicEvent = EVENT_BREWFESTGOBLIN01;
                                        musicTime = EVENT_BREWFESTGOBLIN01_TIME;
                                        break;
                                    case 1:
                                        _currentMusicEvent = EVENT_BREWFESTGOBLIN02;
                                        musicTime = EVENT_BREWFESTGOBLIN02_TIME;
                                        break;
                                    case 2:
                                        _currentMusicEvent = EVENT_BREWFESTGOBLIN03;
                                        musicTime = EVENT_BREWFESTGOBLIN03_TIME;
                                        break;
                                    case 3:
                                        _currentMusicEvent = EVENT_BREWFESTDWARF01;
                                        musicTime = EVENT_BREWFESTDWARF01_TIME;
                                        break;
                                    case 4:
                                        _currentMusicEvent = EVENT_BREWFESTDWARF02;
                                        musicTime = EVENT_BREWFESTDWARF02_TIME;
                                        break;
                                    case 5:
                                        _currentMusicEvent = EVENT_BREWFESTDWARF03;
                                        musicTime = EVENT_BREWFESTDWARF03_TIME;
                                        break;
                                    default:
                                        break;
                                }
                            }
                            _events.ScheduleEvent(EVENT_BM_SELECT_MUSIC, musicTime); // Select new song music after play time is over
                            break;
                        }
                    case EVENT_BM_START_MUSIC:
                        if (!IsHolidayActive(HOLIDAY_BREWFEST)) // Check if Brewfest is active
                            break;
                        // Play selected music
                        if (_currentMusicEvent != 0)
{
                            me->PlayDirectMusic(_currentMusicEvent);
                        }
                        _events.ScheduleEvent(EVENT_BM_START_MUSIC, 5000); // Every 5 second's SMSG_PLAY_MUSIC packet (PlayDirectMusic) is pushed to the client
                        break;
                    default:
                        break;
                }
            }
        }
References _currentMusicEvent, _events, AREA_DARNASSUS, AREA_DUN_MOROGH, AREA_DUROTAR, AREA_ELWYNN_FOREST, AREA_EVERSONG_WOODS, AREA_GATES_OF_IRONFORGE, AREA_ROCKTUSK_FARM, AREA_SHATTRATH_CITY, AREA_THE_EXODAR, AREA_THUNDER_BLUFF, AREA_UNDERCITY, EVENT_BM_SELECT_MUSIC, EVENT_BM_START_MUSIC, EVENT_BREWFESTDWARF01, EVENT_BREWFESTDWARF01_TIME, EVENT_BREWFESTDWARF02, EVENT_BREWFESTDWARF02_TIME, EVENT_BREWFESTDWARF03, EVENT_BREWFESTDWARF03_TIME, EVENT_BREWFESTGOBLIN01, EVENT_BREWFESTGOBLIN01_TIME, EVENT_BREWFESTGOBLIN02, EVENT_BREWFESTGOBLIN02_TIME, EVENT_BREWFESTGOBLIN03, EVENT_BREWFESTGOBLIN03_TIME, EventMap::ExecuteEvent(), WorldObject::GetAreaId(), HOLIDAY_BREWFEST, IsHolidayActive(), GameObjectAI::me, WorldObject::PlayDirectMusic(), EventMap::ScheduleEvent(), EventMap::Update(), and urand().
Member Data Documentation
_currentMusicEvent
uint32 go_brewfest_music::go_brewfest_musicAI::_currentMusicEvent private
Referenced by go_brewfest_musicAI(), and UpdateAI().
_events
EventMap go_brewfest_music::go_brewfest_musicAI::_events private
Referenced by go_brewfest_musicAI(), and UpdateAI().
The documentation for this struct was generated from the following file:
azerothcore-wotlk/src/server/scripts/World/go_scripts.cpp