AzerothCore Doxygen
ticket_commandscript Class Reference
Public Member Functions
ticket_commandscript ()
ChatCommandTable GetCommands () const override
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
uint16 GetTotalAvailableHooks ()
Static Public Member Functions
static bool HandleGMTicketAssignToCommand (ChatHandler *handler, uint32 ticketId, std::string target)
static bool HandleGMTicketCloseByIdCommand (ChatHandler *handler, uint32 ticketId)
static bool HandleGMTicketCommentCommand (ChatHandler *handler, uint32 ticketId, Tail comment)
static bool HandleGMTicketListClosedCommand (ChatHandler *handler)
static bool HandleGMTicketCompleteCommand (ChatHandler *handler, uint32 ticketId, std::optional< std::string > response)
static bool HandleGMTicketDeleteByIdCommand (ChatHandler *handler, uint32 ticketId)
static bool HandleGMTicketEscalateCommand (ChatHandler *handler, uint32 ticketId)
static bool HandleGMTicketListEscalatedCommand (ChatHandler *handler)
static bool HandleGMTicketListCommand (ChatHandler *handler)
static bool HandleGMTicketListOnlineCommand (ChatHandler *handler)
static bool HandleGMTicketResetCommand (ChatHandler *handler)
static bool HandleToggleGMTicketSystem (ChatHandler *handler)
static bool HandleGMTicketUnAssignCommand (ChatHandler *handler, uint32 ticketId)
static bool HandleGMTicketGetByIdCommand (ChatHandler *handler, uint32 ticketId)
static bool HandleGMTicketGetByNameCommand (ChatHandler *handler, std::string name)
static bool TicketResponseAppend (uint32 ticketId, bool newLine, ChatHandler *handler, std::string response)
static bool HandleGMTicketResponseAppendCommand (ChatHandler *handler, uint32 ticketId, Tail res)
static bool HandleGMTicketResponseAppendLnCommand (ChatHandler *handler, uint32 ticketId, Tail res)
static bool HandleGMTicketResponseDeleteCommand (ChatHandler *handler, uint32 ticketId)
static bool HandleGMTicketResponseShowCommand (ChatHandler *handler, uint32 ticketId)
Additional Inherited Members
Protected Member Functions inherited from CommandScript
CommandScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name, uint16 totalAvailableHooks=0)
virtual ~ScriptObject ()=default
Detailed Description
Constructor & Destructor Documentation
ticket_commandscript()
ticket_commandscript::ticket_commandscript () inline
: CommandScript("ticket_commandscript") { }
Member Function Documentation
GetCommands()
ChatCommandTable ticket_commandscript::GetCommands () const inline override virtual
Implements CommandScript.
    {
        static ChatCommandTable ticketResponseCommandTable =
        {
            { "append",         HandleGMTicketResponseAppendCommand,    SEC_GAMEMASTER,     Console::Yes },
            { "appendln",       HandleGMTicketResponseAppendLnCommand,  SEC_GAMEMASTER,     Console::Yes },
            { "delete",         HandleGMTicketResponseDeleteCommand,    SEC_GAMEMASTER,     Console::Yes },
            { "show",           HandleGMTicketResponseShowCommand,      SEC_GAMEMASTER,     Console::Yes }
        };
        static ChatCommandTable ticketCommandTable =
        {
            { "assign",         HandleGMTicketAssignToCommand,          SEC_GAMEMASTER,     Console::Yes },
            { "close",          HandleGMTicketCloseByIdCommand,         SEC_GAMEMASTER,     Console::Yes },
            { "closedlist",     HandleGMTicketListClosedCommand,        SEC_GAMEMASTER,     Console::Yes },
            { "comment",        HandleGMTicketCommentCommand,           SEC_GAMEMASTER,     Console::Yes },
            { "complete",       HandleGMTicketCompleteCommand,          SEC_GAMEMASTER,     Console::Yes },
            { "delete",         HandleGMTicketDeleteByIdCommand,        SEC_ADMINISTRATOR,  Console::Yes },
            { "escalate",       HandleGMTicketEscalateCommand,          SEC_GAMEMASTER,     Console::Yes },
            { "escalatedlist",  HandleGMTicketListEscalatedCommand,     SEC_GAMEMASTER,     Console::Yes },
            { "list",           HandleGMTicketListCommand,              SEC_GAMEMASTER,     Console::Yes },
            { "onlinelist",     HandleGMTicketListOnlineCommand,        SEC_GAMEMASTER,     Console::Yes },
            { "reset",          HandleGMTicketResetCommand,             SEC_CONSOLE,        Console::Yes },
            { "response",       ticketResponseCommandTable },
            { "togglesystem",   HandleToggleGMTicketSystem,             SEC_ADMINISTRATOR,  Console::Yes },
            { "unassign",       HandleGMTicketUnAssignCommand,          SEC_GAMEMASTER,     Console::Yes },
            { "viewid",         HandleGMTicketGetByIdCommand,           SEC_GAMEMASTER,     Console::Yes },
            { "viewname",       HandleGMTicketGetByNameCommand,         SEC_GAMEMASTER,     Console::Yes }
        };
        static ChatCommandTable commandTable =
        {
            { "ticket", ticketCommandTable }
        };
        return commandTable;
    }
References HandleGMTicketAssignToCommand(), HandleGMTicketCloseByIdCommand(), HandleGMTicketCommentCommand(), HandleGMTicketCompleteCommand(), HandleGMTicketDeleteByIdCommand(), HandleGMTicketEscalateCommand(), HandleGMTicketGetByIdCommand(), HandleGMTicketGetByNameCommand(), HandleGMTicketListClosedCommand(), HandleGMTicketListCommand(), HandleGMTicketListEscalatedCommand(), HandleGMTicketListOnlineCommand(), HandleGMTicketResetCommand(), HandleGMTicketResponseAppendCommand(), HandleGMTicketResponseAppendLnCommand(), HandleGMTicketResponseDeleteCommand(), HandleGMTicketResponseShowCommand(), HandleGMTicketUnAssignCommand(), HandleToggleGMTicketSystem(), SEC_ADMINISTRATOR, SEC_CONSOLE, and SEC_GAMEMASTER.
HandleGMTicketAssignToCommand()
static bool ticket_commandscript::HandleGMTicketAssignToCommand (ChatHandler * handler, uint32 ticketId, std::string target) inline static
Console can override though
    {
        if (!normalizePlayerName(target))
            return false;
        GmTicket* ticket = sTicketMgr->GetTicket(ticketId);
        if (!ticket || ticket->IsClosed())
        {
            handler->SendSysMessage(LANG_COMMAND_TICKETNOTEXIST);
            return true;
        }
        // Get target information
        ObjectGuid targetGuid = sCharacterCache->GetCharacterGuidByName(target);
        uint32 targetAccountId = sCharacterCache->GetCharacterAccountIdByGuid(targetGuid);
        uint32 targetGmLevel = AccountMgr::GetSecurity(targetAccountId, realm.Id.Realm);
        // Target must exist and have administrative rights
        if (!targetGuid || AccountMgr::IsPlayerAccount(targetGmLevel))
        {
            handler->SendSysMessage(LANG_COMMAND_TICKETASSIGNERROR_A);
            return true;
        }
        // If already assigned, leave
        if (ticket->IsAssignedTo(targetGuid))
        {
            handler->PSendSysMessage(LANG_COMMAND_TICKETASSIGNERROR_B, ticket->GetId());
            return true;
        }
        // If assigned to different player other than current, leave
        Player* player = handler->GetSession() ? handler->GetSession()->GetPlayer() : nullptr;
        if (player && ticket->IsAssignedNotTo(player->GetGUID()))
        {
            handler->PSendSysMessage(LANG_COMMAND_TICKETALREADYASSIGNED, ticket->GetId(), target);
            return true;
        }
        // Assign ticket
        CharacterDatabaseTransaction trans = CharacterDatabaseTransaction(nullptr);
        ticket->SetAssignedTo(targetGuid, AccountMgr::IsAdminAccount(targetGmLevel));
        ticket->SaveToDB(trans);
        sTicketMgr->UpdateLastChange(ticket);
        std::string msg = ticket->FormatMessageString(*handler, nullptr, target.c_str(), nullptr, nullptr);
        handler->SendGlobalGMSysMessage(msg.c_str());
        return true;
    }
References GmTicket::FormatMessageString(), Object::GetGUID(), GmTicket::GetId(), WorldSession::GetPlayer(), AccountMgr::GetSecurity(), ChatHandler::GetSession(), Realm::Id, AccountMgr::IsAdminAccount(), GmTicket::IsAssignedNotTo(), GmTicket::IsAssignedTo(), GmTicket::IsClosed(), AccountMgr::IsPlayerAccount(), LANG_COMMAND_TICKETALREADYASSIGNED, LANG_COMMAND_TICKETASSIGNERROR_A, LANG_COMMAND_TICKETASSIGNERROR_B, LANG_COMMAND_TICKETNOTEXIST, normalizePlayerName(), ChatHandler::PSendSysMessage(), realm, RealmHandle::Realm, GmTicket::SaveToDB(), sCharacterCache, ChatHandler::SendGlobalGMSysMessage(), ChatHandler::SendSysMessage(), GmTicket::SetAssignedTo(), and sTicketMgr.
Referenced by GetCommands().
HandleGMTicketCloseByIdCommand()
static bool ticket_commandscript::HandleGMTicketCloseByIdCommand (ChatHandler * handler, uint32 ticketId) inline static
    {
        GmTicket* ticket = sTicketMgr->GetTicket(ticketId);
        if (!ticket || ticket->IsClosed() || ticket->IsCompleted())
        {
            handler->SendSysMessage(LANG_COMMAND_TICKETNOTEXIST);
            return true;
        }
        // Ticket should be assigned to the player who tries to close it.
        // Console can override though
        Player* player = handler->GetSession() ? handler->GetSession()->GetPlayer() : nullptr;
        if (player && ticket->IsAssignedNotTo(player->GetGUID()))
        {
            handler->PSendSysMessage(LANG_COMMAND_TICKETCANNOTCLOSE, ticket->GetId());
            return true;
        }
        sTicketMgr->ResolveAndCloseTicket(ticket->GetId(), player ? player->GetGUID() : ObjectGuid::Empty);
        sTicketMgr->UpdateLastChange(ticket);
        std::string msg = ticket->FormatMessageString(*handler, player ? player->GetName().c_str() : "Console", nullptr, nullptr, nullptr);
        handler->SendGlobalGMSysMessage(msg.c_str());
        // Inform player, who submitted this ticket, that it is closed
        if (Player* submitter = ticket->GetPlayer())
        {
            WorldPacket data(SMSG_GMTICKET_DELETETICKET, 4);
            data << uint32(GMTICKET_RESPONSE_TICKET_DELETED);
            submitter->SendDirectMessage(&data);
            ChatHandler(submitter->GetSession()).SendSysMessage(LANG_TICKET_CLOSED);
        }
        return true;
    }
References ObjectGuid::Empty, GmTicket::FormatMessageString(), Object::GetGUID(), GmTicket::GetId(), WorldObject::GetName(), WorldSession::GetPlayer(), GmTicket::GetPlayer(), ChatHandler::GetSession(), GMTICKET_RESPONSE_TICKET_DELETED, GmTicket::IsAssignedNotTo(), GmTicket::IsClosed(), GmTicket::IsCompleted(), LANG_COMMAND_TICKETCANNOTCLOSE, LANG_COMMAND_TICKETNOTEXIST, LANG_TICKET_CLOSED, ChatHandler::PSendSysMessage(), ChatHandler::SendGlobalGMSysMessage(), ChatHandler::SendSysMessage(), SMSG_GMTICKET_DELETETICKET, and sTicketMgr.
Referenced by GetCommands().
HandleGMTicketCommentCommand()
static bool ticket_commandscript::HandleGMTicketCommentCommand (ChatHandler * handler, uint32 ticketId, Tail comment) inline static
    {
        if (comment.empty())
            return false;
        GmTicket* ticket = sTicketMgr->GetTicket(ticketId);
        if (!ticket)
        {
            handler->PSendSysMessage(LANG_COMMAND_TICKETNOTEXIST);
            return true;
        }
        // Cannot comment ticket assigned to someone else (unless done from the Console)
        Player* player = handler->GetSession() ? handler->GetSession()->GetPlayer() : nullptr;
        if (player && ticket->IsAssignedNotTo(player->GetGUID()))
        {
            handler->PSendSysMessage(LANG_COMMAND_TICKETALREADYASSIGNED, ticket->GetId());
            return true;
        }
        CharacterDatabaseTransaction trans = CharacterDatabaseTransaction(nullptr);
        ticket->SetComment(comment.data());
        ticket->SaveToDB(trans);
        sTicketMgr->UpdateLastChange(ticket);
        std::string const assignedName = ticket->GetAssignedToName();
        std::string msg = ticket->FormatMessageString(*handler, assignedName.empty() ? nullptr : assignedName.c_str(), nullptr, nullptr, nullptr);
        msg += handler->PGetParseString(LANG_COMMAND_TICKETLISTADDCOMMENT, player ? player->GetName().c_str() : "Console", comment.data());
        handler->SendGlobalGMSysMessage(msg.c_str());
        return true;
    }
References GmTicket::FormatMessageString(), GmTicket::GetAssignedToName(), Object::GetGUID(), GmTicket::GetId(), WorldObject::GetName(), WorldSession::GetPlayer(), ChatHandler::GetSession(), GmTicket::IsAssignedNotTo(), LANG_COMMAND_TICKETALREADYASSIGNED, LANG_COMMAND_TICKETLISTADDCOMMENT, LANG_COMMAND_TICKETNOTEXIST, ChatHandler::PGetParseString(), ChatHandler::PSendSysMessage(), GmTicket::SaveToDB(), ChatHandler::SendGlobalGMSysMessage(), GmTicket::SetComment(), and sTicketMgr.
Referenced by GetCommands().
HandleGMTicketCompleteCommand()
static bool ticket_commandscript::HandleGMTicketCompleteCommand (ChatHandler * handler, uint32 ticketId, std::optional< std::string > response) inline static
    {
        GmTicket* ticket = sTicketMgr->GetTicket(ticketId);
        if (!ticket || ticket->IsClosed() || ticket->IsCompleted())
        {
            handler->SendSysMessage(LANG_COMMAND_TICKETNOTEXIST);
            return true;
        }
        // Check if handler is not assignee in which case return
        Player* player = handler->GetSession() ? handler->GetSession()->GetPlayer() : nullptr;
        if (player && ticket->IsAssignedNotTo(player->GetGUID()))
        {
            handler->PSendSysMessage(LANG_COMMAND_TICKETALREADYASSIGNED, ticket->GetId());
            return true;
        }
        if (response)
            ticket->AppendResponse(response.value());
        if (Player* player2 = ticket->GetPlayer())
        {
            ticket->SendResponse(player2->GetSession());
            ChatHandler(player2->GetSession()).SendSysMessage(LANG_TICKET_COMPLETED);
        }
        Player* gm = handler->GetSession() ? handler->GetSession()->GetPlayer() : nullptr;
        CharacterDatabaseTransaction trans = CharacterDatabaseTransaction(nullptr);
        ticket->SetCompleted();
        ticket->SetResolvedBy(gm ? gm->GetGUID() : ObjectGuid::Empty);
        ticket->SaveToDB(trans);
        std::string msg = ticket->FormatMessageString(*handler, nullptr, nullptr, nullptr, nullptr);
        msg += handler->PGetParseString(LANG_COMMAND_TICKETCOMPLETED, gm ? gm->GetName().c_str() : "Console");
        handler->SendGlobalGMSysMessage(msg.c_str());
        sTicketMgr->UpdateLastChange(ticket);
        return true;
    }
References GmTicket::AppendResponse(), ObjectGuid::Empty, GmTicket::FormatMessageString(), Object::GetGUID(), GmTicket::GetId(), WorldObject::GetName(), WorldSession::GetPlayer(), GmTicket::GetPlayer(), ChatHandler::GetSession(), GmTicket::IsAssignedNotTo(), GmTicket::IsClosed(), GmTicket::IsCompleted(), LANG_COMMAND_TICKETALREADYASSIGNED, LANG_COMMAND_TICKETCOMPLETED, LANG_COMMAND_TICKETNOTEXIST, LANG_TICKET_COMPLETED, ChatHandler::PGetParseString(), ChatHandler::PSendSysMessage(), GmTicket::SaveToDB(), ChatHandler::SendGlobalGMSysMessage(), GmTicket::SendResponse(), ChatHandler::SendSysMessage(), GmTicket::SetCompleted(), GmTicket::SetResolvedBy(), and sTicketMgr.
Referenced by GetCommands().
HandleGMTicketDeleteByIdCommand()
static bool ticket_commandscript::HandleGMTicketDeleteByIdCommand (ChatHandler * handler, uint32 ticketId) inline static
    {
        GmTicket* ticket = sTicketMgr->GetTicket(ticketId);
        if (!ticket)
        {
            handler->SendSysMessage(LANG_COMMAND_TICKETNOTEXIST);
            return true;
        }
        if (!ticket->IsClosed())
        {
            handler->SendSysMessage(LANG_COMMAND_TICKETCLOSEFIRST);
            return true;
        }
        std::string msg = ticket->FormatMessageString(*handler, nullptr, nullptr, nullptr, handler->GetSession() ? handler->GetSession()->GetPlayer()->GetName().c_str() : "Console");
        handler->SendGlobalGMSysMessage(msg.c_str());
        sTicketMgr->RemoveTicket(ticket->GetId());
        sTicketMgr->UpdateLastChange(ticket);
        if (Player* player = ticket->GetPlayer())
        {
            // Force abandon ticket
            WorldPacket data(SMSG_GMTICKET_DELETETICKET, 4);
            data << uint32(GMTICKET_RESPONSE_TICKET_DELETED);
            player->SendDirectMessage(&data);
        }
        return true;
    }
References GmTicket::FormatMessageString(), GmTicket::GetId(), WorldObject::GetName(), WorldSession::GetPlayer(), GmTicket::GetPlayer(), ChatHandler::GetSession(), GMTICKET_RESPONSE_TICKET_DELETED, GmTicket::IsClosed(), LANG_COMMAND_TICKETCLOSEFIRST, LANG_COMMAND_TICKETNOTEXIST, ChatHandler::SendGlobalGMSysMessage(), ChatHandler::SendSysMessage(), SMSG_GMTICKET_DELETETICKET, and sTicketMgr.
Referenced by GetCommands().
HandleGMTicketEscalateCommand()
static bool ticket_commandscript::HandleGMTicketEscalateCommand (ChatHandler * handler, uint32 ticketId) inline static
    {
        GmTicket* ticket = sTicketMgr->GetTicket(ticketId);
        if (!ticket || ticket->IsClosed() || ticket->IsCompleted() || ticket->GetEscalatedStatus() != TICKET_UNASSIGNED)
        {
            handler->SendSysMessage(LANG_COMMAND_TICKETNOTEXIST);
            return true;
        }
        ticket->SetEscalatedStatus(TICKET_IN_ESCALATION_QUEUE);
        if (Player* player = ticket->GetPlayer())
            sTicketMgr->SendTicket(player->GetSession(), ticket);
        sTicketMgr->UpdateLastChange(ticket);
        return true;
    }
References GmTicket::GetEscalatedStatus(), GmTicket::GetPlayer(), GmTicket::IsClosed(), GmTicket::IsCompleted(), LANG_COMMAND_TICKETNOTEXIST, ChatHandler::SendSysMessage(), GmTicket::SetEscalatedStatus(), sTicketMgr, TICKET_IN_ESCALATION_QUEUE, and TICKET_UNASSIGNED.
Referenced by GetCommands().
HandleGMTicketGetByIdCommand()
static bool ticket_commandscript::HandleGMTicketGetByIdCommand (ChatHandler * handler, uint32 ticketId) inline static
    {
        GmTicket* ticket = sTicketMgr->GetTicket(ticketId);
        if (!ticket || ticket->IsClosed() || ticket->IsCompleted())
        {
            handler->SendSysMessage(LANG_COMMAND_TICKETNOTEXIST);
            return true;
        }
        CharacterDatabaseTransaction trans = CharacterDatabaseTransaction(nullptr);
        ticket->SetViewed();
        ticket->SaveToDB(trans);
        handler->SendSysMessage(ticket->FormatMessageString(*handler, true));
        return true;
    }
References GmTicket::FormatMessageString(), GmTicket::IsClosed(), GmTicket::IsCompleted(), LANG_COMMAND_TICKETNOTEXIST, GmTicket::SaveToDB(), ChatHandler::SendSysMessage(), GmTicket::SetViewed(), and sTicketMgr.
Referenced by GetCommands().
HandleGMTicketGetByNameCommand()
static bool ticket_commandscript::HandleGMTicketGetByNameCommand (ChatHandler * handler, std::string name) inline static
    {
        if (!normalizePlayerName(name))
            return false;
        // Detect target's GUID
        ObjectGuid guid;
        if (Player* player = ObjectAccessor::FindPlayerByName(name, false))
        {
            guid = player->GetGUID();
        }
        else
        {
            guid = sCharacterCache->GetCharacterGuidByName(name);
        }
        // Target must exist
        if (!guid)
        {
            handler->SendSysMessage(LANG_NO_PLAYERS_FOUND);
            return true;
        }
        // Ticket must exist
        GmTicket* ticket = sTicketMgr->GetTicketByPlayer(guid);
        if (!ticket)
        {
            handler->SendSysMessage(LANG_COMMAND_TICKETNOTEXIST);
            return true;
        }
        CharacterDatabaseTransaction trans = CharacterDatabaseTransaction(nullptr);
        ticket->SetViewed();
        ticket->SaveToDB(trans);
        handler->SendSysMessage(ticket->FormatMessageString(*handler, true));
        return true;
    }
References ObjectAccessor::FindPlayerByName(), GmTicket::FormatMessageString(), LANG_COMMAND_TICKETNOTEXIST, LANG_NO_PLAYERS_FOUND, normalizePlayerName(), GmTicket::SaveToDB(), sCharacterCache, ChatHandler::SendSysMessage(), GmTicket::SetViewed(), and sTicketMgr.
Referenced by GetCommands().
HandleGMTicketListClosedCommand()
static bool ticket_commandscript::HandleGMTicketListClosedCommand (ChatHandler * handler) inline static
    {
        sTicketMgr->ShowClosedList(*handler);
        return true;
    }
References sTicketMgr.
Referenced by GetCommands().
HandleGMTicketListCommand()
static bool ticket_commandscript::HandleGMTicketListCommand (ChatHandler * handler) inline static
    {
        sTicketMgr->ShowList(*handler, false);
        return true;
    }
References sTicketMgr.
Referenced by GetCommands().
HandleGMTicketListEscalatedCommand()
static bool ticket_commandscript::HandleGMTicketListEscalatedCommand (ChatHandler * handler) inline static
    {
        sTicketMgr->ShowEscalatedList(*handler);
        return true;
    }
References sTicketMgr.
Referenced by GetCommands().
HandleGMTicketListOnlineCommand()
static bool ticket_commandscript::HandleGMTicketListOnlineCommand (ChatHandler * handler) inline static
    {
        sTicketMgr->ShowList(*handler, true);
        return true;
    }
References sTicketMgr.
Referenced by GetCommands().
HandleGMTicketResetCommand()
static bool ticket_commandscript::HandleGMTicketResetCommand (ChatHandler * handler) inline static
    {
        if (sTicketMgr->GetOpenTicketCount())
        {
            handler->SendSysMessage(LANG_COMMAND_TICKETPENDING);
            return true;
        }
        else
        {
            sTicketMgr->ResetTickets();
            handler->SendSysMessage(LANG_COMMAND_TICKETRESET);
        }
        return true;
    }
References LANG_COMMAND_TICKETPENDING, LANG_COMMAND_TICKETRESET, ChatHandler::SendSysMessage(), and sTicketMgr.
Referenced by GetCommands().
HandleGMTicketResponseAppendCommand()
static bool ticket_commandscript::HandleGMTicketResponseAppendCommand (ChatHandler * handler, uint32 ticketId, Tail res) inline static
    {
        if (res.empty())
            return false;
        else
            return TicketResponseAppend(ticketId, false, handler, res.data());
    }
References TicketResponseAppend().
Referenced by GetCommands().
HandleGMTicketResponseAppendLnCommand()
static bool ticket_commandscript::HandleGMTicketResponseAppendLnCommand (ChatHandler * handler, uint32 ticketId, Tail res) inline static
    {
        if (res.empty())
            return false;
        else
            return TicketResponseAppend(ticketId, true, handler, res.data());
    }
References TicketResponseAppend().
Referenced by GetCommands().
HandleGMTicketResponseDeleteCommand()
static bool ticket_commandscript::HandleGMTicketResponseDeleteCommand (ChatHandler * handler, uint32 ticketId) inline static
Console excluded
    {
        GmTicket* ticket = sTicketMgr->GetTicket(ticketId);
        // Don't allow deleting response for a closed ticket.
        if (!ticket || ticket->IsClosed())
        {
            handler->SendSysMessage(LANG_COMMAND_TICKETNOTEXIST);
            return true;
        }
        // Cannot delete response for a ticket that is assigned to someone else.
        Player* player = handler->GetSession() ? handler->GetSession()->GetPlayer() : nullptr;
        if (player && ticket->IsAssignedNotTo(player->GetGUID()))
        {
            handler->PSendSysMessage(LANG_COMMAND_TICKETALREADYASSIGNED, ticket->GetId());
            return true;
        }
        CharacterDatabaseTransaction trans = CharacterDatabaseTransaction(nullptr);
        ticket->DeleteResponse();
        ticket->SaveToDB(trans);
        sTicketMgr->UpdateLastChange(ticket);
        std::string msg = ticket->FormatMessageString(*handler, nullptr, nullptr, nullptr, nullptr);
        msg += handler->PGetParseString(LANG_COMMAND_TICKETRESPONSEDELETED, player ? player->GetName() : "Console");
        handler->SendGlobalGMSysMessage(msg.c_str());
        return true;
    }
References GmTicket::DeleteResponse(), GmTicket::FormatMessageString(), Object::GetGUID(), GmTicket::GetId(), WorldObject::GetName(), WorldSession::GetPlayer(), ChatHandler::GetSession(), GmTicket::IsAssignedNotTo(), GmTicket::IsClosed(), LANG_COMMAND_TICKETALREADYASSIGNED, LANG_COMMAND_TICKETNOTEXIST, LANG_COMMAND_TICKETRESPONSEDELETED, ChatHandler::PGetParseString(), ChatHandler::PSendSysMessage(), GmTicket::SaveToDB(), ChatHandler::SendGlobalGMSysMessage(), ChatHandler::SendSysMessage(), and sTicketMgr.
Referenced by GetCommands().
HandleGMTicketResponseShowCommand()
static bool ticket_commandscript::HandleGMTicketResponseShowCommand (ChatHandler * handler, uint32 ticketId) inline static
    {
        GmTicket* ticket = sTicketMgr->GetTicket(ticketId);
        if (!ticket)
        {
            handler->SendSysMessage(LANG_COMMAND_TICKETNOTEXIST);
            return true;
        }
        std::string msg = ticket->FormatMessageString(*handler, nullptr, nullptr, nullptr, nullptr);
        msg += handler->PGetParseString(LANG_COMMAND_TICKETLISTRESPONSE, ticket->GetResponse());
        handler->PSendSysMessage(msg);
        return true;
    }
References GmTicket::FormatMessageString(), GmTicket::GetResponse(), LANG_COMMAND_TICKETLISTRESPONSE, LANG_COMMAND_TICKETNOTEXIST, ChatHandler::PGetParseString(), ChatHandler::PSendSysMessage(), ChatHandler::SendSysMessage(), and sTicketMgr.
Referenced by GetCommands().
HandleGMTicketUnAssignCommand()
static bool ticket_commandscript::HandleGMTicketUnAssignCommand (ChatHandler * handler, uint32 ticketId) inline static
If no m_session present it means we're issuing this command from the console
    {
        GmTicket* ticket = sTicketMgr->GetTicket(ticketId);
        if (!ticket || ticket->IsClosed())
        {
            handler->SendSysMessage(LANG_COMMAND_TICKETNOTEXIST);
            return true;
        }
        // Ticket must be assigned
        if (!ticket->IsAssigned())
        {
            handler->PSendSysMessage(LANG_COMMAND_TICKETNOTASSIGNED, ticket->GetId());
            return true;
        }
        // Get security level of player, whom this ticket is assigned to
        uint32 security = SEC_PLAYER;
        Player* assignedPlayer = ticket->GetAssignedPlayer();
        if (assignedPlayer)
            security = assignedPlayer->GetSession()->GetSecurity();
        else
        {
            ObjectGuid guid = ticket->GetAssignedToGUID();
            uint32 accountId = sCharacterCache->GetCharacterAccountIdByGuid(guid);
            security = AccountMgr::GetSecurity(accountId, realm.Id.Realm);
        }
        // Check security
        uint32 mySecurity = handler->GetSession() ? handler->GetSession()->GetSecurity() : SEC_CONSOLE;
        if (security > mySecurity)
        {
            handler->SendSysMessage(LANG_COMMAND_TICKETUNASSIGNSECURITY);
            return true;
        }
        std::string assignedTo = ticket->GetAssignedToName(); // copy assignedto name because we need it after the ticket has been unnassigned
        CharacterDatabaseTransaction trans = CharacterDatabaseTransaction(nullptr);
        ticket->SetUnassigned();
        ticket->SaveToDB(trans);
        sTicketMgr->UpdateLastChange(ticket);
        std::string msg = ticket->FormatMessageString(*handler, nullptr, assignedTo.c_str(),
                          handler->GetSession() ? handler->GetSession()->GetPlayer()->GetName().c_str() : "Console", nullptr);
        handler->SendGlobalGMSysMessage(msg.c_str());
        return true;
    }
References GmTicket::FormatMessageString(), GmTicket::GetAssignedPlayer(), GmTicket::GetAssignedToGUID(), GmTicket::GetAssignedToName(), GmTicket::GetId(), WorldObject::GetName(), WorldSession::GetPlayer(), WorldSession::GetSecurity(), AccountMgr::GetSecurity(), ChatHandler::GetSession(), Player::GetSession(), Realm::Id, GmTicket::IsAssigned(), GmTicket::IsClosed(), LANG_COMMAND_TICKETNOTASSIGNED, LANG_COMMAND_TICKETNOTEXIST, LANG_COMMAND_TICKETUNASSIGNSECURITY, ChatHandler::PSendSysMessage(), realm, RealmHandle::Realm, GmTicket::SaveToDB(), sCharacterCache, SEC_CONSOLE, SEC_PLAYER, ChatHandler::SendGlobalGMSysMessage(), ChatHandler::SendSysMessage(), GmTicket::SetUnassigned(), and sTicketMgr.
Referenced by GetCommands().
HandleToggleGMTicketSystem()
static bool ticket_commandscript::HandleToggleGMTicketSystem (ChatHandler * handler) inline static
    {
        bool status = !sTicketMgr->GetStatus();
        sTicketMgr->SetStatus(status);
        handler->PSendSysMessage(status ? LANG_ALLOW_TICKETS : LANG_DISALLOW_TICKETS);
        return true;
    }
References LANG_ALLOW_TICKETS, LANG_DISALLOW_TICKETS, ChatHandler::PSendSysMessage(), and sTicketMgr.
Referenced by GetCommands().
TicketResponseAppend()
static bool ticket_commandscript::TicketResponseAppend (uint32 ticketId, bool newLine, ChatHandler * handler, std::string response) inline static
Console excluded
    {
        if (response.empty())
            return false;
        GmTicket* ticket = sTicketMgr->GetTicket(ticketId);
        if (!ticket || ticket->IsClosed())
        {
            handler->PSendSysMessage(LANG_COMMAND_TICKETNOTEXIST);
            return true;
        }
        // Cannot add response to ticket, assigned to someone else
        Player* player = handler->GetSession() ? handler->GetSession()->GetPlayer() : nullptr;
        if (player && ticket->IsAssignedNotTo(player->GetGUID()))
        {
            handler->PSendSysMessage(LANG_COMMAND_TICKETALREADYASSIGNED, ticket->GetId());
            return true;
        }
        CharacterDatabaseTransaction trans = CharacterDatabaseTransaction(nullptr);
        if (newLine)
            ticket->AppendResponse("\n");
        ticket->AppendResponse(response);
        ticket->SaveToDB(trans);
        sTicketMgr->UpdateLastChange(ticket);
        std::string msg = ticket->FormatMessageString(*handler, nullptr, nullptr, nullptr, nullptr);
        msg += handler->PGetParseString(LANG_COMMAND_TICKETRESPONSEAPPENDED, response);
        handler->PSendSysMessage(msg);
        return true;
    }
References GmTicket::AppendResponse(), GmTicket::FormatMessageString(), Object::GetGUID(), GmTicket::GetId(), WorldSession::GetPlayer(), ChatHandler::GetSession(), GmTicket::IsAssignedNotTo(), GmTicket::IsClosed(), LANG_COMMAND_TICKETALREADYASSIGNED, LANG_COMMAND_TICKETNOTEXIST, LANG_COMMAND_TICKETRESPONSEAPPENDED, ChatHandler::PGetParseString(), ChatHandler::PSendSysMessage(), GmTicket::SaveToDB(), and sTicketMgr.
Referenced by HandleGMTicketResponseAppendCommand(), and HandleGMTicketResponseAppendLnCommand().
The documentation for this class was generated from the following file:
azerothcore-wotlk/src/server/scripts/Commands/cs_ticket.cpp