AzerothCore Doxygen
TicketScript Class Reference
#include "TicketScript.h"
Public Member Functions
bool IsDatabaseBound () const override
virtual void OnTicketCreate (GmTicket *)
virtual void OnTicketUpdateLastChange (GmTicket *)
virtual void OnTicketClose (GmTicket *)
virtual void OnTicketStatusUpdate (GmTicket *)
virtual void OnTicketResolve (GmTicket *)
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
uint16 GetTotalAvailableHooks ()
Protected Member Functions
TicketScript (char const *name, std::vector< uint16 > enabledHooks=std::vector< uint16 >())
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name, uint16 totalAvailableHooks=0)
virtual ~ScriptObject ()=default
Detailed Description
Constructor & Destructor Documentation
TicketScript()
TicketScript::TicketScript (char const * name, std::vector< uint16 > enabledHooks = std::vector<uint16>()) protected
: ScriptObject(name, TICKETHOOK_END)
{
    // If empty - enable all available hooks.
    if (enabledHooks.empty())
        for (uint16 i = 0; i < TICKETHOOK_END; ++i)
            enabledHooks.emplace_back(i);
    ScriptRegistry<TicketScript>::AddScript(this, std::move(enabledHooks));
}
References ScriptRegistry< TScript >::AddScript(), and TICKETHOOK_END.
Member Function Documentation
IsDatabaseBound()
bool TicketScript::IsDatabaseBound () const inline override virtual
Reimplemented from ScriptObject.
{ return false; }
OnTicketClose()
virtual void TicketScript::OnTicketClose (GmTicket *) inline virtual
{ }
Referenced by ScriptMgr::OnTicketClose().
OnTicketCreate()
virtual void TicketScript::OnTicketCreate (GmTicket *) inline virtual
{ }
Referenced by ScriptMgr::OnTicketCreate().
OnTicketResolve()
virtual void TicketScript::OnTicketResolve (GmTicket *) inline virtual
{ }
Referenced by ScriptMgr::OnTicketResolve().
OnTicketStatusUpdate()
virtual void TicketScript::OnTicketStatusUpdate (GmTicket *) inline virtual
{ }
Referenced by ScriptMgr::OnTicketStatusUpdate().
OnTicketUpdateLastChange()
virtual void TicketScript::OnTicketUpdateLastChange (GmTicket *) inline virtual
{ }
Referenced by ScriptMgr::OnTicketUpdateLastChange().
The documentation for this class was generated from the following files:
azerothcore-wotlk/src/server/game/Scripting/ScriptDefines/TicketScript.h
azerothcore-wotlk/src/server/game/Scripting/ScriptDefines/TicketScript.cpp