AzerothCore Doxygen
worldstate_commandscript Class Reference
Public Member Functions
worldstate_commandscript ()
ChatCommandTable GetCommands () const override
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
uint16 GetTotalAvailableHooks ()
Static Public Member Functions
static bool HandleSunsReachReclamationStatusCommand (ChatHandler *handler)
static bool HandleSunsReachReclamationPhaseCommand (ChatHandler *handler, uint32 phase)
static bool HandleSunsReachReclamationSubPhaseCommand (ChatHandler *handler, uint32 subphase)
static bool HandleSunsReachReclamationCounterCommand (ChatHandler *handler, Optional< uint32 > index, Optional< uint32 > value)
static bool HandleSunwellGateCommand (ChatHandler *handler, uint32 newGate)
static bool HandleSunwellGateCounterCommand (ChatHandler *handler, Optional< uint32 > index, Optional< uint32 > value)
static bool HandleScourgeInvasionCommand (ChatHandler *handler)
static bool HandleScourgeInvasionStateCommand (ChatHandler *handler, uint32 value)
static bool HandleScourgeInvasionBattlesWonCommand (ChatHandler *, int32 value)
static bool HandleScourgeInvasionStartZone (ChatHandler *handler, uint32 value)
Additional Inherited Members
Protected Member Functions inherited from CommandScript
CommandScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name, uint16 totalAvailableHooks=0)
virtual ~ScriptObject ()=default
Detailed Description
Constructor & Destructor Documentation
worldstate_commandscript()
worldstate_commandscript::worldstate_commandscript () inline
: CommandScript("worldstate_commandscript") { }
Member Function Documentation
GetCommands()
ChatCommandTable worldstate_commandscript::GetCommands () const inline override virtual
Implements CommandScript.
    {
        static ChatCommandTable sunsreachCommandTable =
        {
            { "status",      HandleSunsReachReclamationStatusCommand,   SEC_ADMINISTRATOR, Console::Yes },
            { "phase",       HandleSunsReachReclamationPhaseCommand,    SEC_ADMINISTRATOR, Console::Yes },
            { "subphase",    HandleSunsReachReclamationSubPhaseCommand, SEC_ADMINISTRATOR, Console::Yes },
            { "counter",     HandleSunsReachReclamationCounterCommand,  SEC_ADMINISTRATOR, Console::Yes },
            { "gate",        HandleSunwellGateCommand,                  SEC_ADMINISTRATOR, Console::Yes },
            { "gatecounter", HandleSunwellGateCounterCommand,           SEC_ADMINISTRATOR, Console::Yes },
        };
        static ChatCommandTable scourgeInvasionCommandTable =
        {
            { "show",       HandleScourgeInvasionCommand,           SEC_ADMINISTRATOR, Console::Yes },
            { "state",      HandleScourgeInvasionStateCommand,      SEC_ADMINISTRATOR, Console::Yes },
            { "battleswon", HandleScourgeInvasionBattlesWonCommand, SEC_ADMINISTRATOR, Console::Yes },
            { "startzone",  HandleScourgeInvasionStartZone,         SEC_ADMINISTRATOR, Console::Yes },
        };
        static ChatCommandTable worldStateCommandTable =
        {
            { "sunsreach", sunsreachCommandTable },
            { "scourgeinvasion", scourgeInvasionCommandTable }
        };
        static ChatCommandTable commandTable =
        {
            { "worldstate", worldStateCommandTable }
        };
        return commandTable;
    }
References HandleScourgeInvasionBattlesWonCommand(), HandleScourgeInvasionCommand(), HandleScourgeInvasionStartZone(), HandleScourgeInvasionStateCommand(), HandleSunsReachReclamationCounterCommand(), HandleSunsReachReclamationPhaseCommand(), HandleSunsReachReclamationStatusCommand(), HandleSunsReachReclamationSubPhaseCommand(), HandleSunwellGateCommand(), HandleSunwellGateCounterCommand(), and SEC_ADMINISTRATOR.
HandleScourgeInvasionBattlesWonCommand()
static bool worldstate_commandscript::HandleScourgeInvasionBattlesWonCommand (ChatHandler * , int32 value) inline static
    {
        sWorldState->AddBattlesWon(value);
        return true;
    }
References sWorldState.
Referenced by GetCommands().
HandleScourgeInvasionCommand()
static bool worldstate_commandscript::HandleScourgeInvasionCommand (ChatHandler * handler) inline static
    {
        handler->PSendSysMessage(sWorldState->GetScourgeInvasionPrintout());
        return true;
    }
References ChatHandler::PSendSysMessage(), and sWorldState.
Referenced by GetCommands().
HandleScourgeInvasionStartZone()
static bool worldstate_commandscript::HandleScourgeInvasionStartZone (ChatHandler * handler, uint32 value) inline static
    {
        if (value >= SI_TIMER_MAX)
        {
            handler->PSendSysMessage("Syntax: .worldstate scourgeinvasion startzone <value>.\nvalid values: 0-7");
            return true;
        }
        sWorldState->StartZoneEvent(SIZoneIds(value));
        handler->PSendSysMessage("Scourge Invasion event started for zone {}.", value);
        handler->PSendSysMessage(sWorldState->GetScourgeInvasionPrintout());
        return true;
    }
References ChatHandler::PSendSysMessage(), SI_TIMER_MAX, and sWorldState.
Referenced by GetCommands().
HandleScourgeInvasionStateCommand()
static bool worldstate_commandscript::HandleScourgeInvasionStateCommand (ChatHandler * handler, uint32 value) inline static
    {
        if (value >= SI_STATE_MAX)
        {
            handler->PSendSysMessage("Syntax: .worldstate scourgeinvasion state <value>.");
            handler->PSendSysMessage("Valid values are: 0 (Disabled), 1 (Enabled).");
            return true;
        }
        sWorldState->SetScourgeInvasionState(SIState(value));
        handler->PSendSysMessage("Scourge Invasion state set to {}.", value);
        handler->PSendSysMessage(sWorldState->GetScourgeInvasionPrintout());
        return true;
    }
References ChatHandler::PSendSysMessage(), SI_STATE_MAX, and sWorldState.
Referenced by GetCommands().
HandleSunsReachReclamationCounterCommand()
static bool worldstate_commandscript::HandleSunsReachReclamationCounterCommand (ChatHandler * handler, Optional< uint32 > index, Optional< uint32 > value) inline static
    {
        if (!index || !value || index.value() >= COUNTERS_MAX)
        {
            handler->PSendSysMessage("Syntax: .worldstate sunsreach counter <index> <value>.");
            handler->PSendSysMessage(sWorldState->GetSunsReachPrintout());
            return true;
        }
        sWorldState->SetSunsReachCounter(SunsReachCounters(index.value()), value.value());
        handler->PSendSysMessage(sWorldState->GetSunsReachPrintout());
        return true;
    }
References COUNTERS_MAX, ChatHandler::PSendSysMessage(), and sWorldState.
Referenced by GetCommands().
HandleSunsReachReclamationPhaseCommand()
static bool worldstate_commandscript::HandleSunsReachReclamationPhaseCommand (ChatHandler * handler, uint32 phase) inline static
    {
        if (phase > SUNS_REACH_PHASE_4_HARBOR)
        {
            handler->PSendSysMessage("Invalid phase, see \".worldstate sunsreach phase\" for usage");
            return false;
        }
        sWorldState->HandleSunsReachPhaseTransition(phase);
        handler->PSendSysMessage(sWorldState->GetSunsReachPrintout());
        return true;
    }
References ChatHandler::PSendSysMessage(), SUNS_REACH_PHASE_4_HARBOR, and sWorldState.
Referenced by GetCommands().
HandleSunsReachReclamationStatusCommand()
static bool worldstate_commandscript::HandleSunsReachReclamationStatusCommand (ChatHandler * handler) inline static
    {
        handler->PSendSysMessage(sWorldState->GetSunsReachPrintout());
        return true;
    }
References ChatHandler::PSendSysMessage(), and sWorldState.
Referenced by GetCommands().
HandleSunsReachReclamationSubPhaseCommand()
static bool worldstate_commandscript::HandleSunsReachReclamationSubPhaseCommand (ChatHandler * handler, uint32 subphase) inline static
    {
        if (subphase > SUBPHASE_ALL)
        {
            handler->PSendSysMessage("Invalid subphase, see \".worldstate sunsreach subphase\" for usage");
            return false;
        }
        sWorldState->HandleSunsReachSubPhaseTransition(subphase);
        handler->PSendSysMessage(sWorldState->GetSunsReachPrintout());
        return true;
    }
References ChatHandler::PSendSysMessage(), SUBPHASE_ALL, and sWorldState.
Referenced by GetCommands().
HandleSunwellGateCommand()
static bool worldstate_commandscript::HandleSunwellGateCommand (ChatHandler * handler, uint32 newGate) inline static
    {
        if (newGate > SUNWELL_ARCHONISUS_GATE3_OPEN)
        {
            handler->PSendSysMessage("Invalid phase, see \".worldstate sunsreach gate\" for usage");
            return false;
        }
        sWorldState->HandleSunwellGateTransition(newGate);
        handler->PSendSysMessage(sWorldState->GetSunsReachPrintout());
        return true;
    }
References ChatHandler::PSendSysMessage(), SUNWELL_ARCHONISUS_GATE3_OPEN, and sWorldState.
Referenced by GetCommands().
HandleSunwellGateCounterCommand()
static bool worldstate_commandscript::HandleSunwellGateCounterCommand (ChatHandler * handler, Optional< uint32 > index, Optional< uint32 > value) inline static
    {
        if (!index || !value || index.value() >= COUNTERS_MAX_GATES)
        {
            handler->PSendSysMessage("Syntax: .worldstate sunsreach gatecounter <index> <value>.");
            handler->PSendSysMessage(sWorldState->GetSunsReachPrintout());
            return true;
        }
        sWorldState->SetSunwellGateCounter(SunwellGateCounters(index.value()), value.value());
        handler->PSendSysMessage(sWorldState->GetSunsReachPrintout());
        return true;
    }
References COUNTERS_MAX_GATES, ChatHandler::PSendSysMessage(), and sWorldState.
Referenced by GetCommands().
The documentation for this class was generated from the following file:
azerothcore-wotlk/src/server/scripts/Commands/cs_worldstate.cpp