AzerothCore Doxygen
Acore::WorldObjectSpellTrajTargetCheck Struct Reference
#include "Spell.h"
Public Member Functions
WorldObjectSpellTrajTargetCheck (float range, Position const *position, Unit *caster, SpellInfo const *spellInfo, SpellTargetCheckTypes selectionType, std::shared_ptr< ConditionList > condList)
bool operator() (WorldObject *target)
Public Member Functions inherited from Acore::WorldObjectSpellAreaTargetCheck
WorldObjectSpellAreaTargetCheck (float range, Position const *position, Unit *caster, Unit *referer, SpellInfo const *spellInfo, SpellTargetCheckTypes selectionType, std::shared_ptr< ConditionList > condList)
bool operator() (WorldObject *target)
Public Member Functions inherited from Acore::WorldObjectSpellTargetCheck
WorldObjectSpellTargetCheck (Unit *caster, Unit *referer, SpellInfo const *spellInfo, SpellTargetCheckTypes selectionType, std::shared_ptr< ConditionList > condList)
~WorldObjectSpellTargetCheck ()
bool operator() (WorldObject *target)
Additional Inherited Members
Public Attributes inherited from Acore::WorldObjectSpellAreaTargetCheck
float _range
Position const * _position
Public Attributes inherited from Acore::WorldObjectSpellTargetCheck
Unit * _caster
Unit * _referer
SpellInfo const * _spellInfo
SpellTargetCheckTypes _targetSelectionType
ConditionSourceInfo * _condSrcInfo
std::shared_ptr< ConditionList > _condList
Detailed Description
Constructor & Destructor Documentation
WorldObjectSpellTrajTargetCheck()
Acore::WorldObjectSpellTrajTargetCheck::WorldObjectSpellTrajTargetCheck (float range, Position const * position, Unit * caster, SpellInfo const * spellInfo, SpellTargetCheckTypes selectionType, std::shared_ptr< ConditionList > condList)
        : WorldObjectSpellAreaTargetCheck(range, position, caster, caster, spellInfo, selectionType, condList)
    {
    }
Member Function Documentation
operator()()
bool Acore::WorldObjectSpellTrajTargetCheck::operator() (WorldObject * target)
    {
        // return all targets on missile trajectory (0 - size of a missile)
        if (!_caster->HasInLine(target, target->GetObjectSize()))
            return false;
        return WorldObjectSpellAreaTargetCheck::operator ()(target);
    }
References Acore::WorldObjectSpellTargetCheck::_caster, WorldObject::GetObjectSize(), Position::HasInLine(), and Acore::WorldObjectSpellAreaTargetCheck::operator()().
The documentation for this struct was generated from the following files:
azerothcore-wotlk/src/server/game/Spells/Spell.h
azerothcore-wotlk/src/server/game/Spells/Spell.cpp