AzerothCore Doxygen
Eluna_MiscScript Class Reference
Public Member Functions
Eluna_MiscScript ()
void GetDialogStatus (Player *player, Object *questgiver) override
This hook called before get Quest Dialog Status.
Public Member Functions inherited from MiscScript
bool IsDatabaseBound () const override
virtual void OnConstructObject (Object *)
virtual void OnDestructObject (Object *)
virtual void OnConstructPlayer (Player *)
virtual void OnDestructPlayer (Player *)
virtual void OnConstructGroup (Group *)
virtual void OnDestructGroup (Group *)
virtual void OnConstructInstanceSave (InstanceSave *)
virtual void OnDestructInstanceSave (InstanceSave *)
virtual void OnItemCreate (Item *, ItemTemplate const *, Player const *)
virtual bool CanApplySoulboundFlag (Item *, ItemTemplate const *)
virtual bool CanItemApplyEquipSpell (Player *, Item *)
virtual bool CanSendAuctionHello (WorldSession const *, ObjectGuid, Creature *)
virtual void ValidateSpellAtCastSpell (Player *, uint32 &, uint32 &, uint8 &, uint8 &)
virtual void ValidateSpellAtCastSpellResult (Player *, Unit *, Spell *, uint32, uint32)
virtual void OnAfterLootTemplateProcess (Loot *, LootTemplate const *, LootStore const &, Player *, bool, bool, uint16)
virtual void OnPlayerSetPhase (const AuraEffect *, AuraApplication const *, uint8, bool, uint32 &)
virtual void OnInstanceSave (InstanceSave *)
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
uint16 GetTotalAvailableHooks ()
Additional Inherited Members
Protected Member Functions inherited from MiscScript
MiscScript (const char *name, std::vector< uint16 > enabledHooks=std::vector< uint16 >())
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name, uint16 totalAvailableHooks=0)
virtual ~ScriptObject ()=default
Detailed Description
Constructor & Destructor Documentation
Eluna_MiscScript()
Eluna_MiscScript::Eluna_MiscScript () inline
: MiscScript("Eluna_MiscScript") { }
Member Function Documentation
GetDialogStatus()
void Eluna_MiscScript::GetDialogStatus (Player * , Object *) inline override virtual
This hook called before get Quest Dialog Status.
Parameters
player Contains information about the Player
questgiver Contains information about the Object
Reimplemented from MiscScript.
    {
        if (questgiver->GetTypeId() == TYPEID_GAMEOBJECT)
            sEluna->GetDialogStatus(player, questgiver->ToGameObject());
        else if (questgiver->GetTypeId() == TYPEID_UNIT)
            sEluna->GetDialogStatus(player, questgiver->ToCreature());
    }
References Object::GetTypeId(), sEluna, Object::ToCreature(), Object::ToGameObject(), TYPEID_GAMEOBJECT, and TYPEID_UNIT.
The documentation for this class was generated from the following file:
mod-eluna/src/ElunaLuaEngine_SC.cpp