AzerothCore Doxygen
DynamicVMapCollisionData Class Reference
#include "MapCollisionData.h"
Public Member Functions
bool GetObjectHitPos (uint32 phasemask, float x1, float y1, float z1, float x2, float y2, float z2, float &rx, float &ry, float &rz, float modifyDist) const
Public Member Functions inherited from DynamicMapTree
DynamicMapTree ()
~DynamicMapTree ()
bool isInLineOfSight (float x1, float y1, float z1, float x2, float y2, float z2, uint32 phasemask, VMAP::ModelIgnoreFlags ignoreFlags) const
bool GetIntersectionTime (uint32 phasemask, const G3D::Ray &ray, const G3D::Vector3 &endPos, float &maxDist) const
bool GetAreaAndLiquidData (float x, float y, float z, uint32 phasemask, Optional< uint8 > reqLiquidType, VMAP::AreaAndLiquidData &data) const
bool GetObjectHitPos (uint32 phasemask, const G3D::Vector3 &pPos1, const G3D::Vector3 &pPos2, G3D::Vector3 &pResultHitPos, float pModifyDist) const
float getHeight (float x, float y, float z, float maxSearchDist, uint32 phasemask) const
void insert (const GameObjectModel &)
void remove (const GameObjectModel &)
bool contains (const GameObjectModel &) const
int size () const
void balance ()
void update (uint32 diff)
Detailed Description
Member Function Documentation
GetObjectHitPos()
bool DynamicVMapCollisionData::GetObjectHitPos (uint32 phasemask, float x1, float y1, float z1, float x2, float y2, float z2, float & rx, float & ry, float & rz, float modifyDist) const
{
    G3D::Vector3 startPos(x1, y1, z1);
    G3D::Vector3 dstPos(x2, y2, z2);
    G3D::Vector3 resultPos;
    bool result = DynamicMapTree::GetObjectHitPos(phasemask, startPos, dstPos, resultPos, modifyDist);
    rx = resultPos.x;
    ry = resultPos.y;
    rz = resultPos.z;
    return result;
}
References DynamicMapTree::GetObjectHitPos().
Referenced by Map::CheckCollisionAndGetValidCoords(), and Spell::SelectImplicitCasterDestTargets().
The documentation for this class was generated from the following files:
azerothcore-wotlk/src/server/game/Maps/MapCollisionData.h
azerothcore-wotlk/src/server/game/Maps/MapCollisionData.cpp