AzerothCore Doxygen
VampiricBiteTargetSelector Struct Reference
Public Member Functions
VampiricBiteTargetSelector (Creature *source)
bool operator() (Unit const *target) const
Private Attributes
Creature const * _source
Detailed Description
Constructor & Destructor Documentation
VampiricBiteTargetSelector()
VampiricBiteTargetSelector::VampiricBiteTargetSelector (Creature * source) inline
: _source(source) { }
Member Function Documentation
operator()()
bool VampiricBiteTargetSelector::operator() (Unit const * target) const inline
    {
        if (!target)
            return false;
        if (!target->IsPlayer())
            return false;
        if (target->HasAura(SPELL_BLOOD_MIRROR_DAMAGE))
            return false;
        if (IsVampire(target))
            return false;
        return target != _source->GetVictim();
    }
References _source, Unit::GetVictim(), Unit::HasAura(), Object::IsPlayer(), IsVampire(), and SPELL_BLOOD_MIRROR_DAMAGE.
Member Data Documentation
_source
Creature const* VampiricBiteTargetSelector::_source private
Referenced by operator()().
The documentation for this struct was generated from the following file:
azerothcore-wotlk/src/server/scripts/Northrend/IcecrownCitadel/boss_blood_queen_lana_thel.cpp