AzerothCore Doxygen
npc_cork_gizelton::npc_cork_gizeltonAI Struct Reference
Public Member Functions
npc_cork_gizeltonAI (Creature *creature)
void Initialize ()
void JustRespawned () override
void InitializeAI () override
void JustDied (Unit *killer) override
void EnterEvadeMode (EvadeReason why) override
void CheckPlayer ()
void SetGUID (ObjectGuid const &playerGUID, int32 faction) override
void SetData (uint32 field, uint32 data) override
bool CheckCaravan ()
void RemoveSummons ()
void SummonHelpers ()
void SummonedCreatureDies (Creature *creature, Unit *) override
void SummonedCreatureDespawn (Creature *creature) override
void SummonsFollow ()
void RelocateSummons ()
void ImmuneFlagSet (bool remove, uint32 faction)
void WaypointReached (uint32 waypointId) override
void UpdateEscortAI (uint32 diff) override
Public Member Functions inherited from npc_escortAI
npc_escortAI (Creature *creature)
~npc_escortAI () override
void AttackStart (Unit *who) override
void MoveInLineOfSight (Unit *who) override
void JustDied (Unit *) override
void JustRespawned () override
void ReturnToLastPoint ()
void EnterEvadeMode (EvadeReason=EVADE_REASON_OTHER) override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void MovementInform (uint32, uint32) override
void AddWaypoint (uint32 id, float x, float y, float z, uint32 waitTime=0)
bool SetNextWaypoint (uint32 pointId, float x, float y, float z, float orientation)
bool SetNextWaypoint (uint32 pointId, bool setPosition=true)
bool GetWaypointPosition (uint32 pointId, float &x, float &y, float &z)
void GenerateWaypointArray (Movement::PointsArray *points)
virtual void WaypointStart (uint32)
void Start (bool isActiveAttacker=true, ObjectGuid playerGUID=ObjectGuid::Empty, Quest const *quest=nullptr, bool instantRespawn=false, bool canLoopPath=false, bool resetWaypoints=true)
void SetEscortPaused (bool on)
bool HasEscortState (uint32 escortState)
bool IsEscorted () override
void SetMaxPlayerDistance (float newMax)
float GetMaxPlayerDistance ()
void SetDespawnAtEnd (bool despawn)
void SetDespawnAtFar (bool despawn)
bool GetAttack ()
void SetCanAttack (bool attack)
ObjectGuid GetEventStarterGUID ()
void AddEscortState (uint32 escortState)
void RemoveEscortState (uint32 escortState)
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportPlayer (Unit *unit, Position pos)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool IsUniqueTimedEventDone (uint32 id) const
void SetUniqueTimedEventDone (uint32 id)
void ResetUniqueTimedEvent (uint32 id)
void ClearUniqueTimedEventsDone ()
void ScheduleTimedEvent (Milliseconds timerMin, Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0ms, uint32 uniqueId=0)
void ScheduleTimedEvent (Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0ms, uint32 uniqueId=0)
void ScheduleUniqueTimedEvent (Milliseconds timer, std::function< void()> exec, uint32 uniqueId)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
void SetInvincibility (bool apply)
bool IsInvincible () const
void SetAutoAttackAllowed (bool allow)
bool IsAutoAttackAllowed () const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0ms)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void OnSpellCastFinished (SpellInfo const *, SpellFinishReason)
virtual void AttackedBy (Unit *)
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
int32 VisualizeBoundary (uint32 duration, Unit *owner=nullptr, bool fill=false, bool checkZ=false) const
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
virtual void DistancingStarted ()
virtual void DistancingEnded ()
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage to any victim (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Public Attributes
EventMap events
ObjectGuid summons [MAX_CARAVAN_SUMMONS]
bool headNorth
ObjectGuid _playerGUID
uint32 _faction
Public Attributes inherited from ScriptedAI
Creature * me
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from npc_escortAI
Player * GetPlayerForEscort ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
npc_cork_gizeltonAI()
npc_cork_gizelton::npc_cork_gizeltonAI::npc_cork_gizeltonAI (Creature * creature) inline
                                                : npc_escortAI(creature)
        {
        }
Member Function Documentation
CheckCaravan()
bool npc_cork_gizelton::npc_cork_gizeltonAI::CheckCaravan () inline
        {
            for (uint8 i = 0; i < MAX_CARAVAN_SUMMONS; ++i)
            {
                if (!summons[i])
                {
                    SummonHelpers();
                    return false;
                }
                Creature* summon = ObjectAccessor::GetCreature(*me, summons[i]);
                if (!summon || me->GetDistance2d(summon) > 25.0f)
                {
                    SummonHelpers();
                    return false;
                }
            }
            return true;
        }
References ObjectAccessor::GetCreature(), WorldObject::GetDistance2d(), MAX_CARAVAN_SUMMONS, ScriptedAI::me, SummonHelpers(), and summons.
Referenced by UpdateEscortAI(), and WaypointReached().
CheckPlayer()
void npc_cork_gizelton::npc_cork_gizeltonAI::CheckPlayer () inline
        {
            if (_playerGUID)
                if (Player* player = ObjectAccessor::GetPlayer(*me, _playerGUID))
                    if (me->IsWithinDist(player, 60.0f))
                        return;
            _playerGUID.Clear();
            _faction = 35;
            ImmuneFlagSet(false, _faction);
        }
References _faction, _playerGUID, ObjectGuid::Clear(), ObjectAccessor::GetPlayer(), ImmuneFlagSet(), WorldObject::IsWithinDist(), and ScriptedAI::me.
Referenced by WaypointReached().
EnterEvadeMode()
void npc_cork_gizelton::npc_cork_gizeltonAI::EnterEvadeMode (EvadeReason why) inline override virtual
Reimplemented from CreatureAI.
        {
            SummonsFollow();
            ImmuneFlagSet(false, 35);
            npc_escortAI::EnterEvadeMode(why);
        }
References npc_escortAI::EnterEvadeMode(), ImmuneFlagSet(), and SummonsFollow().
ImmuneFlagSet()
void npc_cork_gizelton::npc_cork_gizeltonAI::ImmuneFlagSet (bool remove, uint32 faction) inline
        {
            for (uint8 i = 0; i < MAX_CARAVAN_SUMMONS; ++i)
                if (Creature* summon = ObjectAccessor::GetCreature(*me, summons[i]))
                {
                    summon->SetFaction(faction);
                    if (remove)
                        summon->SetImmuneToNPC(false);
                    else
                        summon->SetImmuneToNPC(true);
                }
            if (remove)
                me->SetImmuneToNPC(false);
            else
                me->SetImmuneToNPC(true);
            me->SetFaction(faction);
        }
References ObjectAccessor::GetCreature(), MAX_CARAVAN_SUMMONS, ScriptedAI::me, Unit::SetFaction(), Unit::SetImmuneToNPC(), and summons.
Referenced by CheckPlayer(), EnterEvadeMode(), and WaypointReached().
Initialize()
void npc_cork_gizelton::npc_cork_gizeltonAI::Initialize () inline
        {
            _faction = 35;
            headNorth = true;
            me->setActive(true);
            events.ScheduleEvent(EVENT_RESTART_ESCORT, 0ms);
        }
References _faction, EVENT_RESTART_ESCORT, headNorth, ScriptedAI::me, and WorldObject::setActive().
Referenced by InitializeAI(), and JustRespawned().
InitializeAI()
void npc_cork_gizelton::npc_cork_gizeltonAI::InitializeAI () inline override virtual
Reimplemented from UnitAI.
        {
            npc_escortAI::InitializeAI();
            Initialize();
        }
References Initialize(), and UnitAI::InitializeAI().
JustDied()
void npc_cork_gizelton::npc_cork_gizeltonAI::JustDied (Unit * killer) inline override virtual
Reimplemented from CreatureAI.
        {
            RemoveSummons();
            npc_escortAI::JustDied(killer);
        }
References npc_escortAI::JustDied(), and RemoveSummons().
JustRespawned()
void npc_cork_gizelton::npc_cork_gizeltonAI::JustRespawned () inline override virtual
Reimplemented from CreatureAI.
        {
            npc_escortAI::JustRespawned();
            Initialize();
        }
References Initialize(), and npc_escortAI::JustRespawned().
RelocateSummons()
void npc_cork_gizelton::npc_cork_gizeltonAI::RelocateSummons () inline
        {
            for (uint8 i = 0; i < MAX_CARAVAN_SUMMONS; ++i)
                if (Creature* summon = ObjectAccessor::GetCreature(*me, summons[i]))
                    summon->SetHomePosition(me->GetPositionX(), me->GetPositionY(), me->GetPositionZ(), me->GetOrientation());
        }
References ObjectAccessor::GetCreature(), Position::GetOrientation(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), MAX_CARAVAN_SUMMONS, ScriptedAI::me, and summons.
Referenced by WaypointReached().
RemoveSummons()
void npc_cork_gizelton::npc_cork_gizeltonAI::RemoveSummons () inline
        {
            for (uint8 i = 0; i < MAX_CARAVAN_SUMMONS; ++i)
            {
                if (Creature* summon = ObjectAccessor::GetCreature(*me, summons[i]))
                    summon->DespawnOrUnsummon();
                summons[i].Clear();
            }
        }
References ObjectGuid::Clear(), ObjectAccessor::GetCreature(), MAX_CARAVAN_SUMMONS, ScriptedAI::me, and summons.
Referenced by JustDied(), and SummonHelpers().
SetData()
void npc_cork_gizelton::npc_cork_gizeltonAI::SetData (uint32 field, uint32 data) inline override virtual
Reimplemented from UnitAI.
        {
            if (field == 1 && data == 1)
                if (Player* player = me->SelectNearestPlayer(50.0f))
                    SetGUID(player->GetGUID(), player->GetFaction());
        }
References ScriptedAI::me, WorldObject::SelectNearestPlayer(), and SetGUID().
SetGUID()
void npc_cork_gizelton::npc_cork_gizeltonAI::SetGUID (ObjectGuid const & playerGUID, int32 faction) inline override virtual
Reimplemented from UnitAI.
        {
            _playerGUID = playerGUID;
            _faction = faction;
            SetEscortPaused(false);
            if (Creature* active = !headNorth ? me : ObjectAccessor::GetCreature(*me, summons[0]))
                active->RemoveNpcFlag(UNIT_NPC_FLAG_QUESTGIVER);
            events.CancelEvent(EVENT_WAIT_FOR_ASSIST);
        }
References _faction, _playerGUID, EVENT_WAIT_FOR_ASSIST, ObjectAccessor::GetCreature(), headNorth, ScriptedAI::me, npc_escortAI::SetEscortPaused(), summons, and UNIT_NPC_FLAG_QUESTGIVER.
Referenced by SetData().
SummonedCreatureDespawn()
void npc_cork_gizelton::npc_cork_gizeltonAI::SummonedCreatureDespawn (Creature * creature) inline override virtual
Reimplemented from CreatureAI.
        {
            if (creature->GetGUID() == summons[0])
                summons[0].Clear();
            else if (creature->GetGUID() == summons[1])
                summons[1].Clear();
            else if (creature->GetGUID() == summons[2])
                summons[2].Clear();
        }
References ObjectGuid::Clear(), Object::GetGUID(), and summons.
SummonedCreatureDies()
void npc_cork_gizelton::npc_cork_gizeltonAI::SummonedCreatureDies (Creature * creature, Unit *) inline override virtual
Reimplemented from CreatureAI.
        {
            if (creature->GetGUID() == summons[0])
                summons[0].Clear();
            else if (creature->GetGUID() == summons[1])
                summons[1].Clear();
            else if (creature->GetGUID() == summons[2])
                summons[2].Clear();
        }
References ObjectGuid::Clear(), Object::GetGUID(), and summons.
SummonHelpers()
void npc_cork_gizelton::npc_cork_gizeltonAI::SummonHelpers () inline
        {
            RemoveSummons();
            me->RemoveNpcFlag(UNIT_NPC_FLAG_QUESTGIVER);
            if (Creature* cr = me->SummonCreature(NPC_RIGGER_GIZELTON, *me))
            {
                cr->RemoveNpcFlag(UNIT_NPC_FLAG_QUESTGIVER);
                summons[0] = cr->GetGUID();
            }
            if (Creature* cr = me->SummonCreature(NPC_CARAVAN_KODO, *me))
            {
                summons[1] = cr->GetGUID();
            }
            if (Creature* cr = me->SummonCreature(NPC_CARAVAN_KODO, *me))
            {
                summons[2] = cr->GetGUID();
            }
            SummonsFollow();
        }
References ScriptedAI::me, NPC_CARAVAN_KODO, NPC_RIGGER_GIZELTON, Unit::RemoveNpcFlag(), RemoveSummons(), WorldObject::SummonCreature(), summons, SummonsFollow(), and UNIT_NPC_FLAG_QUESTGIVER.
Referenced by CheckCaravan().
SummonsFollow()
void npc_cork_gizelton::npc_cork_gizeltonAI::SummonsFollow () inline
        {
            float dist = 1.0f;
            for (uint8 i = 0; i < MAX_CARAVAN_SUMMONS; ++i)
                if (Creature* summon = ObjectAccessor::GetCreature(*me, summons[i]))
                {
                    summon->GetMotionMaster()->Clear(false);
                    summon->StopMoving();
                    summon->GetMotionMaster()->MoveFollow(me, dist, M_PI, MOTION_SLOT_ACTIVE);
                    dist += (i == 1 ? 9.5f : 3.0f);
                }
        }
References ObjectAccessor::GetCreature(), MAX_CARAVAN_SUMMONS, ScriptedAI::me, MOTION_SLOT_ACTIVE, and summons.
Referenced by EnterEvadeMode(), and SummonHelpers().
UpdateEscortAI()
void npc_cork_gizelton::npc_cork_gizeltonAI::UpdateEscortAI (uint32 diff) inline override virtual
Reimplemented from npc_escortAI.
        {
            events.Update(diff);
            switch (events.ExecuteEvent())
            {
                case EVENT_RESUME_PATH:
                    SetEscortPaused(false);
                    if (Creature* talker = headNorth ? me : ObjectAccessor::GetCreature(*me, summons[0]))
                        talker->AI()->Talk(SAY_CARAVAN_LEAVE);
                    headNorth = !headNorth;
                    break;
                case EVENT_WAIT_FOR_ASSIST:
                    SetEscortPaused(false);
                    if (Creature* active = !headNorth ? me : ObjectAccessor::GetCreature(*me, summons[0]))
                        active->RemoveNpcFlag(UNIT_NPC_FLAG_QUESTGIVER);
                    break;
                case EVENT_RESTART_ESCORT:
                    CheckCaravan();
                    SetDespawnAtEnd(false);
                    Start(true, ObjectGuid::Empty, 0, false, false, true);
                    break;
            }
            if (!UpdateVictim())
                return;
            DoMeleeAttackIfReady();
        }
References CheckCaravan(), UnitAI::DoMeleeAttackIfReady(), ObjectGuid::Empty, EVENT_RESTART_ESCORT, EVENT_RESUME_PATH, EVENT_WAIT_FOR_ASSIST, ObjectAccessor::GetCreature(), headNorth, ScriptedAI::me, SAY_CARAVAN_LEAVE, npc_escortAI::SetDespawnAtEnd(), npc_escortAI::SetEscortPaused(), npc_escortAI::Start(), summons, UNIT_NPC_FLAG_QUESTGIVER, and CreatureAI::UpdateVictim().
WaypointReached()
void npc_cork_gizelton::npc_cork_gizeltonAI::WaypointReached (uint32 waypointId) inline override virtual
Implements npc_escortAI.
        {
            RelocateSummons();
            switch (waypointId)
            {
                // Finished north path
                case 52:
                    me->SummonCreature(NPC_VENDOR_TRON, -694.61f, 1460.7f, 90.794f, 2.4f, TEMPSUMMON_TIMED_DESPAWN, 600000 + 15 * IN_MILLISECONDS);
                    SetEscortPaused(true);
                    events.ScheduleEvent(EVENT_RESUME_PATH, TIME_SHOP_STOP);
                    CheckCaravan();
                    break;
                // Finished south path
                case 193:
                    me->SummonCreature(NPC_SUPER_SELLER, -1905.5f, 2463.3f, 61.52f, 5.87f, TEMPSUMMON_TIMED_DESPAWN, 600000 + 15 * IN_MILLISECONDS);
                    SetEscortPaused(true);
                    events.ScheduleEvent(EVENT_RESUME_PATH, TIME_SHOP_STOP);
                    CheckCaravan();
                    break;
                // North -> South - hire
                case 77:
                    SetEscortPaused(true);
                    me->SetNpcFlag(UNIT_NPC_FLAG_QUESTGIVER);
                    Talk(SAY_CARAVAN_HIRE);
                    events.ScheduleEvent(EVENT_WAIT_FOR_ASSIST, TIME_HIRE_STOP);
                    break;
                // Sout -> North - hire
                case 208:
                    SetEscortPaused(true);
                    if (Creature* rigger = ObjectAccessor::GetCreature(*me, summons[0]))
                    {
                        rigger->SetNpcFlag(UNIT_NPC_FLAG_QUESTGIVER);
                        rigger->AI()->Talk(SAY_CARAVAN_HIRE);
                    }
                    events.ScheduleEvent(EVENT_WAIT_FOR_ASSIST, TIME_HIRE_STOP);
                    break;
                // North -> South - complete
                case 103:
                    if (Player* player = ObjectAccessor::GetPlayer(*me, _playerGUID))
                    {
                        if (CheckCaravan())
                            player->GroupEventHappens(QUEST_BODYGUARD_FOR_HIRE, player);
                        else
                            player->FailQuest(QUEST_BODYGUARD_FOR_HIRE);
                    }
                    _playerGUID.Clear();
                    CheckPlayer();
                    break;
                // South -> North - complete
                case 235:
                    if (Player* player = ObjectAccessor::GetPlayer(*me, _playerGUID))
                    {
                        if (CheckCaravan())
                            player->GroupEventHappens(QUEST_GIZELTON_CARAVAN, player);
                        else
                            player->FailQuest(QUEST_GIZELTON_CARAVAN);
                    }
                    _playerGUID.Clear();
                    CheckPlayer();
                    break;
                // North -> South - spawn attackers
                case 83:
                case 93:
                case 100:
                    {
                        if (!_playerGUID)
                            return;
                        ImmuneFlagSet(true, _faction);
                        Creature* cr = nullptr;
                        for (uint8 i = 0; i < 4; ++i)
{
                            float o = (i * M_PI / 2) + (M_PI / 4);
                            float x = me->GetPositionX() + cos(o) * 15.0f;
                            float y = me->GetPositionY() + std::sin(o) * 15.0f;
                            if ((cr = me->SummonCreature((i % 2 == 0 ? NPC_KOLKAR_WAYLAYER : NPC_KOLKAR_AMBUSHER),
                                                         x, y, me->GetMap()->GetHeight(x, y, MAX_HEIGHT), 0.0f, TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT, 30000)))
                                cr->AI()->AttackStart(me);
                        }
                        if (cr)
{
                            AttackStart(cr);
                            me->CallForHelp(50.0f);
                        }
                        break;
                    }
                // South -> North - spawn attackers
                case 221:
                case 228:
                case 233:
                    {
                        if (!_playerGUID)
                            return;
                        ImmuneFlagSet(true, _faction);
                        Creature* cr = nullptr;
                        for (uint8 i = 0; i < 3; ++i)
{
                            float o = i * 2 * M_PI / 3;
                            float x = me->GetPositionX() + cos(o) * 10.0f;
                            float y = me->GetPositionY() + std::sin(o) * 10.0f;
                            uint32 entry = NPC_LESSER_INFERNAL;
                            if (i)
                                entry = i == 1 ? NPC_DOOMWARDER : NPC_NETHER;
                            if ((cr = me->SummonCreature(entry, x, y, me->GetMap()->GetHeight(x, y, MAX_HEIGHT), 0.0f, TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT, 30000)))
                                cr->AI()->AttackStart(me);
                        }
                        if (cr)
{
                            AttackStart(cr);
                            me->CallForHelp(50.0f);
                        }
                        break;
                    }
                case 282:
                    events.ScheduleEvent(EVENT_RESTART_ESCORT, 1s);
                    break;
            }
        }
References _faction, _playerGUID, Creature::AI(), UnitAI::AttackStart(), npc_escortAI::AttackStart(), Creature::CallForHelp(), CheckCaravan(), CheckPlayer(), ObjectGuid::Clear(), EVENT_RESTART_ESCORT, EVENT_RESUME_PATH, EVENT_WAIT_FOR_ASSIST, ObjectAccessor::GetCreature(), Map::GetHeight(), WorldObject::GetMap(), ObjectAccessor::GetPlayer(), Position::GetPositionX(), Position::GetPositionY(), ImmuneFlagSet(), IN_MILLISECONDS, MAX_HEIGHT, ScriptedAI::me, NPC_DOOMWARDER, NPC_KOLKAR_AMBUSHER, NPC_KOLKAR_WAYLAYER, NPC_LESSER_INFERNAL, NPC_NETHER, NPC_SUPER_SELLER, NPC_VENDOR_TRON, QUEST_BODYGUARD_FOR_HIRE, QUEST_GIZELTON_CARAVAN, RelocateSummons(), SAY_CARAVAN_HIRE, npc_escortAI::SetEscortPaused(), Unit::SetNpcFlag(), WorldObject::SummonCreature(), summons, TEMPSUMMON_TIMED_DESPAWN, TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT, TIME_HIRE_STOP, TIME_SHOP_STOP, and UNIT_NPC_FLAG_QUESTGIVER.
Member Data Documentation
_faction
uint32 npc_cork_gizelton::npc_cork_gizeltonAI::_faction
Referenced by CheckPlayer(), Initialize(), SetGUID(), and WaypointReached().
_playerGUID
ObjectGuid npc_cork_gizelton::npc_cork_gizeltonAI::_playerGUID
Referenced by CheckPlayer(), SetGUID(), and WaypointReached().
events
EventMap npc_cork_gizelton::npc_cork_gizeltonAI::events
headNorth
bool npc_cork_gizelton::npc_cork_gizeltonAI::headNorth
Referenced by Initialize(), SetGUID(), and UpdateEscortAI().
summons
ObjectGuid npc_cork_gizelton::npc_cork_gizeltonAI::summons[MAX_CARAVAN_SUMMONS]
Referenced by CheckCaravan(), ImmuneFlagSet(), RelocateSummons(), RemoveSummons(), SetGUID(), SummonedCreatureDespawn(), SummonedCreatureDies(), SummonHelpers(), SummonsFollow(), UpdateEscortAI(), and WaypointReached().
The documentation for this struct was generated from the following file:
azerothcore-wotlk/src/server/scripts/Kalimdor/zone_desolace.cpp