AzerothCore Doxygen
ObjectVisibilityContainer Class Reference
#include "ObjectVisibilityContainer.h"
Public Member Functions
ObjectVisibilityContainer (WorldObject *selfObject)
~ObjectVisibilityContainer ()
void InitForPlayer ()
void CleanVisibilityReferences ()
void LinkWorldObjectVisibility (WorldObject *worldObject)
void UnlinkWorldObjectVisibility (WorldObject *worldObject)
VisibleWorldObjectsMap::iterator UnlinkVisibilityFromPlayer (WorldObject *worldObject, VisibleWorldObjectsMap::iterator itr)
VisiblePlayersMap::iterator UnlinkVisibilityFromWorldObject (Player *player, VisiblePlayersMap::iterator itr)
VisiblePlayersMap & GetVisiblePlayersMap ()
VisiblePlayersMap const & GetVisiblePlayersMap () const
VisibleWorldObjectsMap * GetVisibleWorldObjectsMap ()
VisibleWorldObjectsMap const * GetVisibleWorldObjectsMap () const
Private Member Functions
void DirectRemoveVisibilityReference (ObjectGuid guid)
void DirectInsertVisiblePlayerReference (Player *player)
void DirectRemoveVisiblePlayerReference (ObjectGuid guid)
Private Attributes
WorldObject * _selfObject
std::unique_ptr< VisibleWorldObjectsMap > _visibleWorldObjectsMap
VisiblePlayersMap _visiblePlayersMap
Detailed Description
Constructor & Destructor Documentation
ObjectVisibilityContainer()
ObjectVisibilityContainer::ObjectVisibilityContainer (WorldObject * selfObject)
                                                                            :
    _selfObject(selfObject)
{
}
~ObjectVisibilityContainer()
ObjectVisibilityContainer::~ObjectVisibilityContainer ()
{
    ASSERT(_visiblePlayersMap.empty());
    if (_visibleWorldObjectsMap)
        ASSERT((*_visibleWorldObjectsMap).empty());
}
References _visiblePlayersMap, _visibleWorldObjectsMap, and ASSERT.
Member Function Documentation
CleanVisibilityReferences()
void ObjectVisibilityContainer::CleanVisibilityReferences ()
{
    for (auto const& kvPair : _visiblePlayersMap)
        kvPair.second->GetObjectVisibilityContainer().DirectRemoveVisibilityReference(_selfObject->GetGUID());
    if (_visibleWorldObjectsMap)
    {
        for (auto const& kvPair : *_visibleWorldObjectsMap)
            kvPair.second->GetObjectVisibilityContainer().DirectRemoveVisiblePlayerReference(_selfObject->GetGUID());
        (*_visibleWorldObjectsMap).clear();
    }
    _visiblePlayersMap.clear();
}
References _selfObject, _visiblePlayersMap, _visibleWorldObjectsMap, and Object::GetGUID().
Referenced by WorldSession::HandlePlayerLoginToCharInWorld(), and WorldObject::RemoveFromWorld().
DirectInsertVisiblePlayerReference()
void ObjectVisibilityContainer::DirectInsertVisiblePlayerReference (Player * player) private
{
    _visiblePlayersMap.insert(std::make_pair(player->GetGUID(), player));
}
References _visiblePlayersMap, and Object::GetGUID().
Referenced by LinkWorldObjectVisibility().
DirectRemoveVisibilityReference()
void ObjectVisibilityContainer::DirectRemoveVisibilityReference (ObjectGuid guid) private
{
    ASSERT(_visibleWorldObjectsMap);
    (*_visibleWorldObjectsMap).erase(guid);
}
References _visibleWorldObjectsMap, and ASSERT.
Referenced by UnlinkVisibilityFromWorldObject().
DirectRemoveVisiblePlayerReference()
void ObjectVisibilityContainer::DirectRemoveVisiblePlayerReference (ObjectGuid guid) private
{
    _visiblePlayersMap.erase(guid);
}
References _visiblePlayersMap.
Referenced by UnlinkVisibilityFromPlayer(), and UnlinkWorldObjectVisibility().
GetVisiblePlayersMap() [1/2]
VisiblePlayersMap & ObjectVisibilityContainer::GetVisiblePlayersMap () inline
{ return _visiblePlayersMap; }
References _visiblePlayersMap.
Referenced by WorldObject::DestroyForVisiblePlayers(), WorldObject::DoForAllVisiblePlayers(), and debug_commandscript::HandleDebugVisibilityDataCommand().
GetVisiblePlayersMap() [2/2]
VisiblePlayersMap const & ObjectVisibilityContainer::GetVisiblePlayersMap () const inline
{ return _visiblePlayersMap; }
References _visiblePlayersMap.
GetVisibleWorldObjectsMap() [1/2]
VisibleWorldObjectsMap * ObjectVisibilityContainer::GetVisibleWorldObjectsMap () inline
    {
        if (!_visibleWorldObjectsMap)
            return nullptr;
        return _visibleWorldObjectsMap.get();
    }
References _visibleWorldObjectsMap.
Referenced by WorldObject::DoForAllVisibleWorldObjects(), debug_commandscript::HandleDebugVisibilityDataCommand(), Player::HaveAtClient(), and Acore::VisibleNotifier::SendToSelf().
GetVisibleWorldObjectsMap() [2/2]
VisibleWorldObjectsMap const * ObjectVisibilityContainer::GetVisibleWorldObjectsMap () const inline
    {
        if (!_visibleWorldObjectsMap)
            return nullptr;
        return _visibleWorldObjectsMap.get();
    }
References _visibleWorldObjectsMap.
InitForPlayer()
void ObjectVisibilityContainer::InitForPlayer ()
{
    _visibleWorldObjectsMap = std::make_unique<VisibleWorldObjectsMap>();
}
References _visibleWorldObjectsMap.
Referenced by Player::Player().
LinkWorldObjectVisibility()
void ObjectVisibilityContainer::LinkWorldObjectVisibility (WorldObject * worldObject)
{
    // Do not link self
    if (worldObject == _selfObject)
        return;
    // Transports are special and should not be added to our visibility map
    if (worldObject->IsGameObject() && worldObject->ToGameObject()->IsTransport())
        return;
    // Only players can link visibility
    if (!_visibleWorldObjectsMap)
        return;
    (*_visibleWorldObjectsMap).insert(std::make_pair(worldObject->GetGUID(), worldObject));
    worldObject->GetObjectVisibilityContainer().DirectInsertVisiblePlayerReference(_selfObject->ToPlayer());
}
References _selfObject, _visibleWorldObjectsMap, DirectInsertVisiblePlayerReference(), Object::GetGUID(), WorldObject::GetObjectVisibilityContainer(), Object::IsGameObject(), GameObject::IsTransport(), Object::ToGameObject(), and Object::ToPlayer().
Referenced by Player::UpdateVisibilityOf(), UpdateVisibilityOf_helper(), UpdateVisibilityOf_helper(), UpdateVisibilityOf_helper(), and UpdateVisibilityOf_helper().
UnlinkVisibilityFromPlayer()
VisibleWorldObjectsMap::iterator ObjectVisibilityContainer::UnlinkVisibilityFromPlayer (WorldObject * worldObject, VisibleWorldObjectsMap::iterator itr)
{
    ASSERT(_visibleWorldObjectsMap); // Ensure we aren't for some reason calling this as a non-player object
    worldObject->GetObjectVisibilityContainer().DirectRemoveVisiblePlayerReference(_selfObject->GetGUID());
    return (*_visibleWorldObjectsMap).erase(itr);
}
References _selfObject, _visibleWorldObjectsMap, ASSERT, DirectRemoveVisiblePlayerReference(), Object::GetGUID(), and WorldObject::GetObjectVisibilityContainer().
Referenced by Acore::VisibleNotifier::SendToSelf().
UnlinkVisibilityFromWorldObject()
VisiblePlayersMap::iterator ObjectVisibilityContainer::UnlinkVisibilityFromWorldObject (Player * player, VisiblePlayersMap::iterator itr)
{
    player->GetObjectVisibilityContainer().DirectRemoveVisibilityReference(_selfObject->GetGUID());
    return _visiblePlayersMap.erase(itr);
}
References _selfObject, _visiblePlayersMap, DirectRemoveVisibilityReference(), Object::GetGUID(), and WorldObject::GetObjectVisibilityContainer().
Referenced by WorldObject::DestroyForVisiblePlayers().
UnlinkWorldObjectVisibility()
void ObjectVisibilityContainer::UnlinkWorldObjectVisibility (WorldObject * worldObject)
{
    // Only players can unlink visibility
    if (!_visibleWorldObjectsMap)
        return;
    worldObject->GetObjectVisibilityContainer().DirectRemoveVisiblePlayerReference(_selfObject->GetGUID());
    (*_visibleWorldObjectsMap).erase(worldObject->GetGUID());
}
References _selfObject, _visibleWorldObjectsMap, DirectRemoveVisiblePlayerReference(), Object::GetGUID(), and WorldObject::GetObjectVisibilityContainer().
Referenced by Player::UpdateVisibilityOf(), and Player::UpdateVisibilityOf().
Member Data Documentation
_selfObject
WorldObject* ObjectVisibilityContainer::_selfObject private
Referenced by CleanVisibilityReferences(), LinkWorldObjectVisibility(), UnlinkVisibilityFromPlayer(), UnlinkVisibilityFromWorldObject(), and UnlinkWorldObjectVisibility().
_visiblePlayersMap
VisiblePlayersMap ObjectVisibilityContainer::_visiblePlayersMap private
Referenced by CleanVisibilityReferences(), DirectInsertVisiblePlayerReference(), DirectRemoveVisiblePlayerReference(), GetVisiblePlayersMap(), GetVisiblePlayersMap(), UnlinkVisibilityFromWorldObject(), and ~ObjectVisibilityContainer().
_visibleWorldObjectsMap
std::unique_ptr<VisibleWorldObjectsMap> ObjectVisibilityContainer::_visibleWorldObjectsMap private
Referenced by CleanVisibilityReferences(), DirectRemoveVisibilityReference(), GetVisibleWorldObjectsMap(), GetVisibleWorldObjectsMap(), InitForPlayer(), LinkWorldObjectVisibility(), UnlinkVisibilityFromPlayer(), UnlinkWorldObjectVisibility(), and ~ObjectVisibilityContainer().
The documentation for this class was generated from the following files:
azerothcore-wotlk/src/server/game/Entities/Object/ObjectVisibilityContainer.h
azerothcore-wotlk/src/server/game/Entities/Object/ObjectVisibilityContainer.cpp