AzerothCore Doxygen
OutdoorPvPGH Class Reference
#include "OutdoorPvPGH.h"
Public Member Functions
OutdoorPvPGH ()
bool SetupOutdoorPvP () override
void SendRemoveWorldStates (Player *player) override
Public Member Functions inherited from OutdoorPvP
OutdoorPvP ()=default
~OutdoorPvP () override
void DeleteSpawns ()
virtual void FillInitialWorldStates (WorldPackets::WorldState::InitWorldStates &)
virtual bool HandleAreaTrigger (Player *player, uint32 trigger)
virtual bool HandleCustomSpell (Player *player, uint32 spellId, GameObject *go)
virtual bool HandleOpenGo (Player *player, GameObject *go)
void OnGameObjectCreate (GameObject *go) override
void OnGameObjectRemove (GameObject *go) override
void OnCreatureCreate (Creature *creature) override
void OnCreatureRemove (Creature *creature) override
void SendUpdateWorldState (uint32 field, uint32 value)
virtual bool Update (uint32 diff)
virtual void HandleKill (Player *killer, Unit *killed)
virtual void HandleKillImpl (Player *, Unit *)
bool IsInsideObjective (Player *player) const
virtual void AwardKillBonus (Player *)
uint32 GetTypeId () const
virtual bool HandleDropFlag (Player *player, uint32 spellId)
virtual bool HandleGossipOption (Player *player, Creature *creature, uint32 gossipId)
virtual bool CanTalkTo (Player *player, Creature *c, GossipMenuItems const &gso)
void TeamApplyBuff (TeamId teamId, uint32 spellId, uint32 spellId2=0, Player *sameMapPlr=nullptr)
Map * GetMap () const
Public Member Functions inherited from ZoneScript
ZoneScript ()
virtual ~ZoneScript ()
virtual uint32 GetCreatureEntry (ObjectGuid::LowType, CreatureData const *data)
virtual uint32 GetGameObjectEntry (ObjectGuid::LowType, uint32 entry)
virtual void OnUnitDeath (Unit *)
virtual void OnCreatureEvade (Creature *)
virtual ObjectGuid GetGuidData (uint32) const
virtual void SetGuidData (uint32, ObjectGuid)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void ProcessEvent (WorldObject *, uint32)
Additional Inherited Members
Public Types inherited from OutdoorPvP
typedef std::map< ObjectGuid::LowType, OPvPCapturePoint * > OPvPCapturePointMap
typedef std::pair< ObjectGuid::LowType, GameObject * > GoScriptPair
typedef std::pair< ObjectGuid::LowType, Creature * > CreatureScriptPair
Protected Member Functions inherited from OutdoorPvP
void BroadcastPacket (WorldPacket &data) const
virtual void HandlePlayerEnterZone (Player *player, uint32 zone)
virtual void HandlePlayerLeaveZone (Player *player, uint32 zone)
virtual void HandlePlayerResurrects (Player *player, uint32 zone)
void AddCapturePoint (OPvPCapturePoint *cp)
OPvPCapturePoint * GetCapturePoint (ObjectGuid::LowType spawnId) const
void RegisterZone (uint32 zoneid)
bool HasPlayer (Player const *player) const
void TeamCastSpell (TeamId team, int32 spellId, Player *sameMapPlr=nullptr)
void SetMapFromZone (uint32 zone)
Protected Attributes inherited from OutdoorPvP
OPvPCapturePointMap _capturePoints
std::array< PlayerSet, 2 > _players
uint32 _typeId {}
bool _sendUpdate { true }
Map * _map {}
std::unordered_map< ObjectGuid::LowType, GameObject * > _goScriptStore
std::unordered_map< ObjectGuid::LowType, Creature * > _creatureScriptStore
Detailed Description
Constructor & Destructor Documentation
OutdoorPvPGH()
OutdoorPvPGH::OutdoorPvPGH ()
{
    _typeId = OUTDOOR_PVP_GH;
}
References OutdoorPvP::_typeId, and OUTDOOR_PVP_GH.
Member Function Documentation
SendRemoveWorldStates()
void OutdoorPvPGH::SendRemoveWorldStates (Player * player) override virtual
Reimplemented from OutdoorPvP.
{
    player->SendUpdateWorldState(WORLD_STATE_OPVP_GH_UI_SLIDER_DISPLAY, 0);
    player->SendUpdateWorldState(WORLD_STATE_OPVP_GH_UI_SLIDER_POS, 0);
    player->SendUpdateWorldState(WORLD_STATE_OPVP_GH_UI_SLIDER_N, 0);
}
References Player::SendUpdateWorldState(), WORLD_STATE_OPVP_GH_UI_SLIDER_DISPLAY, WORLD_STATE_OPVP_GH_UI_SLIDER_N, and WORLD_STATE_OPVP_GH_UI_SLIDER_POS.
SetupOutdoorPvP()
bool OutdoorPvPGH::SetupOutdoorPvP () override virtual
Reimplemented from OutdoorPvP.
{
    RegisterZone(GH_ZONE);
    SetMapFromZone(GH_ZONE);
    AddCapturePoint(new OPvPCapturePointGH(this));
    return true;
}
References OutdoorPvP::AddCapturePoint(), GH_ZONE, OutdoorPvP::RegisterZone(), and OutdoorPvP::SetMapFromZone().
The documentation for this class was generated from the following files:
azerothcore-wotlk/src/server/scripts/OutdoorPvP/OutdoorPvPGH.h
azerothcore-wotlk/src/server/scripts/OutdoorPvP/OutdoorPvPGH.cpp