AzerothCore Doxygen
DamageInfoStub Class Reference
Lightweight stub for DamageInfo.
#include "DamageHealInfoStub.h"
Public Member Functions
DamageInfoStub ()=default
DamageInfoStub (uint32_t damage, uint32_t originalDamage, uint32_t schoolMask, uint8_t attackType, SpellInfo const *spellInfo=nullptr)
virtual ~DamageInfoStub ()=default
uint32_t GetDamage () const
uint32_t GetOriginalDamage () const
uint32_t GetAbsorb () const
uint32_t GetResist () const
uint32_t GetBlock () const
void SetDamage (uint32_t damage)
void SetOriginalDamage (uint32_t damage)
void SetAbsorb (uint32_t absorb)
void SetResist (uint32_t resist)
void SetBlock (uint32_t block)
uint32_t GetSchoolMask () const
uint8_t GetAttackType () const
void SetSchoolMask (uint32_t schoolMask)
void SetAttackType (uint8_t attackType)
SpellInfo const * GetSpellInfo () const
void SetSpellInfo (SpellInfo const *spellInfo)
uint32_t GetHitMask () const
void SetHitMask (uint32_t hitMask)
Private Attributes
uint32_t _damage = 0
uint32_t _originalDamage = 0
uint32_t _absorb = 0
uint32_t _resist = 0
uint32_t _block = 0
uint32_t _schoolMask = 1
uint8_t _attackType = 0
uint32_t _hitMask = 0
SpellInfo const * _spellInfo = nullptr
Detailed Description
Lightweight stub for DamageInfo.
Mirrors the key fields of DamageInfo for proc testing without requiring actual Unit objects.
Constructor & Destructor Documentation
DamageInfoStub() [1/2]
DamageInfoStub::DamageInfoStub () default
DamageInfoStub() [2/2]
DamageInfoStub::DamageInfoStub (uint32_t damage, uint32_t originalDamage, uint32_t schoolMask, uint8_t attackType, SpellInfo const * spellInfo = nullptr) inline
        : _damage(damage)
        , _originalDamage(originalDamage)
        , _schoolMask(schoolMask)
        , _attackType(attackType)
        , _spellInfo(spellInfo)
    {}
~DamageInfoStub()
virtual DamageInfoStub::~DamageInfoStub () virtual default
Member Function Documentation
GetAbsorb()
uint32_t DamageInfoStub::GetAbsorb () const inline
{ return _absorb; }
References _absorb.
GetAttackType()
uint8_t DamageInfoStub::GetAttackType () const inline
{ return _attackType; }
References _attackType.
GetBlock()
uint32_t DamageInfoStub::GetBlock () const inline
{ return _block; }
References _block.
GetDamage()
uint32_t DamageInfoStub::GetDamage () const inline
{ return _damage; }
References _damage.
GetHitMask()
uint32_t DamageInfoStub::GetHitMask () const inline
{ return _hitMask; }
References _hitMask.
GetOriginalDamage()
uint32_t DamageInfoStub::GetOriginalDamage () const inline
{ return _originalDamage; }
References _originalDamage.
GetResist()
uint32_t DamageInfoStub::GetResist () const inline
{ return _resist; }
References _resist.
GetSchoolMask()
uint32_t DamageInfoStub::GetSchoolMask () const inline
{ return _schoolMask; }
References _schoolMask.
GetSpellInfo()
SpellInfo const * DamageInfoStub::GetSpellInfo () const inline
{ return _spellInfo; }
References _spellInfo.
SetAbsorb()
void DamageInfoStub::SetAbsorb (uint32_t absorb) inline
{ _absorb = absorb; }
References _absorb.
Referenced by DamageInfoStubBuilder::WithAbsorb().
SetAttackType()
void DamageInfoStub::SetAttackType (uint8_t attackType) inline
{ _attackType = attackType; }
References _attackType.
Referenced by DamageInfoStubBuilder::WithAttackType().
SetBlock()
void DamageInfoStub::SetBlock (uint32_t block) inline
{ _block = block; }
References _block.
Referenced by DamageInfoStubBuilder::WithBlock().
SetDamage()
void DamageInfoStub::SetDamage (uint32_t damage) inline
{ _damage = damage; }
References _damage.
Referenced by DamageInfoStubBuilder::WithDamage(), and ProcTestContext::WithDamage().
SetHitMask()
void DamageInfoStub::SetHitMask (uint32_t hitMask) inline
{ _hitMask = hitMask; }
References _hitMask.
Referenced by ProcTestContext::WithCriticalHit(), DamageInfoStubBuilder::WithHitMask(), and ProcTestContext::WithNormalHit().
SetOriginalDamage()
void DamageInfoStub::SetOriginalDamage (uint32_t damage) inline
{ _originalDamage = damage; }
References _originalDamage.
Referenced by DamageInfoStubBuilder::WithDamage(), ProcTestContext::WithDamage(), and DamageInfoStubBuilder::WithOriginalDamage().
SetResist()
void DamageInfoStub::SetResist (uint32_t resist) inline
{ _resist = resist; }
References _resist.
Referenced by DamageInfoStubBuilder::WithResist().
SetSchoolMask()
void DamageInfoStub::SetSchoolMask (uint32_t schoolMask) inline
{ _schoolMask = schoolMask; }
References _schoolMask.
Referenced by ProcTestContext::WithDamage(), and DamageInfoStubBuilder::WithSchoolMask().
SetSpellInfo()
void DamageInfoStub::SetSpellInfo (SpellInfo const * spellInfo) inline
{ _spellInfo = spellInfo; }
References _spellInfo.
Referenced by DamageInfoStubBuilder::WithSpellInfo().
Member Data Documentation
_absorb
uint32_t DamageInfoStub::_absorb = 0 private
Referenced by GetAbsorb(), and SetAbsorb().
_attackType
uint8_t DamageInfoStub::_attackType = 0 private
Referenced by GetAttackType(), and SetAttackType().
_block
uint32_t DamageInfoStub::_block = 0 private
Referenced by GetBlock(), and SetBlock().
_damage
uint32_t DamageInfoStub::_damage = 0 private
Referenced by GetDamage(), and SetDamage().
_hitMask
uint32_t DamageInfoStub::_hitMask = 0 private
Referenced by GetHitMask(), and SetHitMask().
_originalDamage
uint32_t DamageInfoStub::_originalDamage = 0 private
Referenced by GetOriginalDamage(), and SetOriginalDamage().
_resist
uint32_t DamageInfoStub::_resist = 0 private
Referenced by GetResist(), and SetResist().
_schoolMask
uint32_t DamageInfoStub::_schoolMask = 1 private
Referenced by GetSchoolMask(), and SetSchoolMask().
_spellInfo
SpellInfo const* DamageInfoStub::_spellInfo = nullptr private
Referenced by GetSpellInfo(), and SetSpellInfo().
The documentation for this class was generated from the following file:
azerothcore-wotlk/src/test/mocks/DamageHealInfoStub.h