AzerothCore Doxygen
go_wind_stone::go_wind_stoneAI Struct Reference
Public Member Functions
go_wind_stoneAI (GameObject *go)
void InitializeAI () override
bool GossipHello (Player *player, bool reportUse) override
bool GossipSelect (Player *player, uint32 sender, uint32 action) override
void SummonNPC (GameObject *go, Player *player, uint32 npc, uint32 spellId)
Public Member Functions inherited from GameObjectAI
GameObjectAI (GameObject *go)
virtual ~GameObjectAI ()
virtual void UpdateAI (uint32)
virtual void Reset ()
virtual void DoAction (int32)
virtual void SetGUID (ObjectGuid, int32)
virtual ObjectGuid GetGUID (int32) const
virtual bool GossipSelectCode (Player *, uint32, uint32, char const *)
virtual bool QuestAccept (Player *, Quest const *)
virtual bool QuestReward (Player *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *)
virtual void Destroyed (Player *, uint32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void OnGameEvent (bool, uint16)
virtual void OnStateChanged (uint32, Unit *)
virtual void EventInform (uint32)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual bool CanBeSeen (Player const *)
virtual void JustSummoned (Creature *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureEvade (Creature *)
Private Attributes
ObjectGuid _creatureGuid
Additional Inherited Members
Static Public Member Functions inherited from GameObjectAI
static int32 Permissible (GameObject const *go)
Protected Attributes inherited from GameObjectAI
GameObject *const me
Detailed Description
Constructor & Destructor Documentation
go_wind_stoneAI()
go_wind_stone::go_wind_stoneAI::go_wind_stoneAI (GameObject * go) inline
: GameObjectAI(go) {}
Member Function Documentation
GossipHello()
bool go_wind_stone::go_wind_stoneAI::GossipHello (Player * player, bool reportUse) inline override virtual
Reimplemented from GameObjectAI.
        {
            if (reportUse)
            {
                uint32 gossipId         = me->GetGOInfo()->GetGossipMenuId();
                bool   _twilightSetAura = (player->HasAura(AURA_TWILIGHT_SET, player->GetGUID()));
                bool   _medallionAura   = (player->HasAura(AURA_MEDALLION, player->GetGUID()));
                bool   _ringAura        = (player->HasAura(AURA_RING, player->GetGUID()));
                switch (gossipId)
                {
                case GOSSIPID_LESSER_WS:
                {
                    if (!_twilightSetAura)
                        me->CastSpell(player, SPELL_PUNISHMENT);
                    break;
                }
                case GOSSIPID_WS:
                {
                    if (!_twilightSetAura || !_medallionAura)
                        me->CastSpell(player, SPELL_PUNISHMENT);
                    break;
                }
                case GOSSIPID_GREATER_WS:
                {
                    if (!_twilightSetAura || !_medallionAura || !_ringAura)
                        me->CastSpell(player, SPELL_PUNISHMENT);
                    break;
                }
                default:
                    break;
                }
            }
            return false;
        }
References AURA_MEDALLION, AURA_RING, AURA_TWILIGHT_SET, Object::GetGUID(), GOSSIPID_GREATER_WS, GOSSIPID_LESSER_WS, GOSSIPID_WS, Unit::HasAura(), and SPELL_PUNISHMENT.
GossipSelect()
bool go_wind_stone::go_wind_stoneAI::GossipSelect (Player * player, uint32 sender, uint32 action) inline override virtual
Reimplemented from GameObjectAI.
        {
            Seconds respawnTimer{};
            player->PlayerTalkClass->SendCloseGossip();
            Creature* lastSpawn = ObjectAccessor::GetCreature(*me, _creatureGuid);
            if (lastSpawn && lastSpawn->IsAlive())
            {
                // We already summoned something recently, return.
                CloseGossipMenuFor(player);
                return true;
            }
            else
            {
                _creatureGuid.Clear();
            }
            if (sender == GOSSIPID_LESSER_WS)
            {
                respawnTimer = 300s; // Lesser Windstone respawn in 5 minutes
                switch (action)
                {
                case 0:
                    SummonNPC(me, player, RAND(NPC_TEMPLAR_WATER, NPC_TEMPLAR_FIRE, NPC_TEMPLAR_EARTH, NPC_TEMPLAR_AIR), SPELL_TEMPLAR_RANDOM);
                    break;
                case 1:
                    SummonNPC(me, player, NPC_TEMPLAR_FIRE, SPELL_TEMPLAR_FIRE);
                    break;
                case 2:
                    SummonNPC(me, player, NPC_TEMPLAR_WATER, SPELL_TEMPLAR_WATER);
                    break;
                case 3:
                    SummonNPC(me, player, NPC_TEMPLAR_EARTH, SPELL_TEMPLAR_EARTH);
                    break;
                case 4:
                    SummonNPC(me, player, NPC_TEMPLAR_AIR, SPELL_TEMPLAR_AIR);
                    break;
                default:
                    break;
                }
            }
            else if (sender == GOSSIPID_WS)
            {
                respawnTimer = 900s; // Windstone respawn in 15 minutes
                switch (action)
                {
                case 0:
                    SummonNPC(me, player, RAND(NPC_DUKE_WATER, NPC_DUKE_FIRE, NPC_DUKE_EARTH, NPC_DUKE_AIR), SPELL_DUKE_RANDOM);
                    break;
                case 1:
                    SummonNPC(me, player, NPC_DUKE_FIRE, SPELL_DUKE_FIRE);
                    break;
                case 2:
                    SummonNPC(me, player, NPC_DUKE_WATER, SPELL_DUKE_WATER);
                    break;
                case 3:
                    SummonNPC(me, player, NPC_DUKE_EARTH, SPELL_DUKE_EARTH);
                    break;
                case 4:
                    SummonNPC(me, player, NPC_DUKE_AIR, SPELL_DUKE_AIR);
                    break;
                default:
                    break;
                }
            }
            else if (sender == GOSSIPID_GREATER_WS)
            {
                respawnTimer = 10800s; // Greater Windstone respawn in 3 hours
                switch (action)
                {
                case 0:
                    SummonNPC(me, player, RAND(NPC_ROYAL_WATER, NPC_ROYAL_FIRE, NPC_ROYAL_EARTH, NPC_ROYAL_AIR), SPELL_ROYAL_RANDOM);
                    break;
                case 1:
                    SummonNPC(me, player, NPC_ROYAL_FIRE, SPELL_ROYAL_FIRE);
                    break;
                case 2:
                    SummonNPC(me, player, NPC_ROYAL_WATER, SPELL_ROYAL_WATER);
                    break;
                case 3:
                    SummonNPC(me, player, NPC_ROYAL_EARTH, SPELL_ROYAL_EARTH);
                    break;
                case 4:
                    SummonNPC(me, player, NPC_ROYAL_AIR, SPELL_ROYAL_AIR);
                    break;
                default:
                    break;
                }
            }
            me->DespawnOrUnsummon(5000ms, respawnTimer); // Despawn in 5 Seconds for respawnTimer value
            me->SetGameObjectFlag(GO_FLAG_NOT_SELECTABLE);
            CloseGossipMenuFor(player);
            return false;
        }
References CloseGossipMenuFor(), ObjectAccessor::GetCreature(), GO_FLAG_NOT_SELECTABLE, GOSSIPID_GREATER_WS, GOSSIPID_LESSER_WS, GOSSIPID_WS, Unit::IsAlive(), NPC_DUKE_AIR, NPC_DUKE_EARTH, NPC_DUKE_FIRE, NPC_DUKE_WATER, NPC_ROYAL_AIR, NPC_ROYAL_EARTH, NPC_ROYAL_FIRE, NPC_ROYAL_WATER, NPC_TEMPLAR_AIR, NPC_TEMPLAR_EARTH, NPC_TEMPLAR_FIRE, NPC_TEMPLAR_WATER, Player::PlayerTalkClass, RAND(), PlayerMenu::SendCloseGossip(), SPELL_DUKE_AIR, SPELL_DUKE_EARTH, SPELL_DUKE_FIRE, SPELL_DUKE_RANDOM, SPELL_DUKE_WATER, SPELL_ROYAL_AIR, SPELL_ROYAL_EARTH, SPELL_ROYAL_FIRE, SPELL_ROYAL_RANDOM, SPELL_ROYAL_WATER, SPELL_TEMPLAR_AIR, SPELL_TEMPLAR_EARTH, SPELL_TEMPLAR_FIRE, SPELL_TEMPLAR_RANDOM, and SPELL_TEMPLAR_WATER.
InitializeAI()
void go_wind_stone::go_wind_stoneAI::InitializeAI () inline override virtual
Reimplemented from GameObjectAI.
        {
            me->RemoveGameObjectFlag(GO_FLAG_NOT_SELECTABLE);
        }
References GO_FLAG_NOT_SELECTABLE.
SummonNPC()
void go_wind_stone::go_wind_stoneAI::SummonNPC (GameObject * go, Player * player, uint32 npc, uint32 spellId) inline
        {
            SpellInfo const* spellInfo = sSpellMgr->GetSpellInfo(spellId);
            if (!spellInfo)
                return;
            SpellInfo const* spellInfoTrigger = sSpellMgr->GetSpellInfo(spellInfo->Effects[EFFECT_0].TriggerSpell);
            if (!spellInfoTrigger)
                return;
            Spell*          spell  = new Spell(player, spellInfoTrigger, TRIGGERED_NONE);
            SpellCastResult result = spell->CheckCast(true);
            delete spell;
            if (result != SPELL_CAST_OK)
            {
                return;
            }
            player->CastSpell(player, spellInfoTrigger->Id, false);
            if (TempSummon* summons = go->SummonCreature(npc, go->GetPositionX(), go->GetPositionY(), go->GetPositionZ(), player->GetOrientation() - M_PI, TEMPSUMMON_TIMED_DESPAWN_OOC_ALIVE, 6000))
            {
                summons->SetCorpseDelay(5 * MINUTE);
                summons->SetTarget(player->GetGUID());
                summons->SetLootRecipient(player);
                summons->CastSpell(summons, SPELL_SPAWN_IN, false);
                summons->AI()->Talk(SAY_ON_SPAWN_IN, player);
                summons->m_Events.AddEvent(new DelayedWindstoneSummonEvent(summons, player->GetGUID()), summons->m_Events.CalculateTime(5200));
                _creatureGuid = summons->GetGUID();
            }
        }
References Unit::CastSpell(), Spell::CheckCast(), EFFECT_0, SpellInfo::Effects, Object::GetGUID(), Position::GetOrientation(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), SpellInfo::Id, MINUTE, SAY_ON_SPAWN_IN, SPELL_CAST_OK, SPELL_SPAWN_IN, sSpellMgr, WorldObject::SummonCreature(), summons, TEMPSUMMON_TIMED_DESPAWN_OOC_ALIVE, and TRIGGERED_NONE.
Member Data Documentation
_creatureGuid
ObjectGuid go_wind_stone::go_wind_stoneAI::_creatureGuid private
The documentation for this struct was generated from the following file:
azerothcore-wotlk/src/server/scripts/Kalimdor/zone_silithus.cpp