AzerothCore Doxygen
spell_priest.cpp File Reference
#include "CreatureScript.h"
#include "GridNotifiers.h"
#include "Player.h"
#include "SpellAuraEffects.h"
#include "SpellMgr.h"
#include "SpellScript.h"
#include "SpellScriptLoader.h"
#include "TemporarySummon.h"
Classes
class spell_pri_shadowfiend_scaling
class spell_pri_circle_of_healing
class spell_pri_divine_aegis
class spell_pri_divine_hymn
class spell_pri_glyph_of_prayer_of_healing
class spell_pri_guardian_spirit
class spell_pri_hymn_of_hope
class spell_pri_item_greater_heal_refund
class spell_pri_lightwell
class spell_pri_lightwell_renew
class spell_pri_mana_burn
class spell_pri_mana_leech
class spell_pri_mind_sear
class spell_pri_pain_and_suffering_proc
class spell_pri_penance
class spell_pri_power_word_shield_aura
class spell_pri_power_word_shield
class spell_pri_prayer_of_mending_heal
class spell_pri_renew
class spell_pri_shadow_word_death
class spell_pri_vampiric_touch
class spell_pri_mind_control
class spell_pri_t4_4p_bonus
class spell_pri_shadowfiend_death
class spell_pri_vampiric_embrace
class spell_pri_glyph_of_dispel_magic
class spell_pri_body_and_soul
class spell_pri_improved_shadowform
class spell_pri_aq_3p_bonus
class spell_pri_imp_shadowform
class spell_pri_improved_spirit_tap
class spell_pri_item_t6_trinket
class spell_pri_t3_4p_bonus
class spell_pri_t5_heal_2p_bonus
class spell_pri_t10_heal_2p_bonus
class spell_pri_pain_and_suffering_dummy
class spell_pri_blessed_recovery
Enumerations
enum PriestSpells {
SPELL_PRIEST_DIVINE_AEGIS = 47753 ,
SPELL_PRIEST_EMPOWERED_RENEW = 63544 ,
SPELL_PRIEST_GLYPH_OF_CIRCLE_OF_HEALING = 55675 ,
SPELL_PRIEST_GLYPH_OF_LIGHTWELL = 55673 ,
SPELL_PRIEST_GLYPH_OF_PRAYER_OF_HEALING_HEAL = 56161 ,
SPELL_PRIEST_GUARDIAN_SPIRIT_HEAL = 48153 ,
SPELL_PRIEST_ITEM_EFFICIENCY = 37595 ,
SPELL_PRIEST_LIGHTWELL_CHARGES = 59907 ,
SPELL_PRIEST_MANA_LEECH_PROC = 34650 ,
SPELL_PRIEST_PENANCE_R1 = 47540 ,
SPELL_PRIEST_PENANCE_R1_DAMAGE = 47758 ,
SPELL_PRIEST_PENANCE_R1_HEAL = 47757 ,
SPELL_PRIEST_REFLECTIVE_SHIELD_TRIGGERED = 33619 ,
SPELL_PRIEST_REFLECTIVE_SHIELD_R1 = 33201 ,
SPELL_PRIEST_SHADOW_WORD_DEATH = 32409 ,
SPELL_PRIEST_T9_HEALING_2P = 67201 ,
SPELL_PRIEST_VAMPIRIC_TOUCH_DISPEL = 64085 ,
SPELL_PRIEST_T4_4P_FLEXIBILITY = 37565 ,
SPELL_PRIEST_GLYPH_OF_SHADOWFIEND = 58228 ,
SPELL_PRIEST_GLYPH_OF_SHADOWFIEND_MANA = 58227 ,
SPELL_GENERIC_ARENA_DAMPENING = 74410 ,
SPELL_GENERIC_BATTLEGROUND_DAMPENING = 74411 ,
SPELL_PRIEST_TWIN_DISCIPLINE_R1 = 47586 ,
SPELL_PRIEST_SPIRITUAL_HEALING_R1 = 14898 ,
SPELL_PRIEST_DIVINE_PROVIDENCE_R1 = 47562
}
enum PriestSpellIcons {
PRIEST_ICON_ID_BORROWED_TIME = 2899 ,
PRIEST_ICON_ID_EMPOWERED_RENEW_TALENT = 3021 ,
PRIEST_ICON_ID_PAIN_AND_SUFFERING = 2874 ,
PRIEST_ICON_ID_BODY_AND_SOUL = 2218
}
enum PriestProcSpells {
SPELL_PRIEST_VAMPIRIC_EMBRACE_HEAL = 15290 ,
SPELL_PRIEST_GLYPH_OF_DISPEL_MAGIC_HEAL = 56131 ,
SPELL_PRIEST_BODY_AND_SOUL_SPEED = 64136 ,
SPELL_PRIEST_ORACULAR_HEAL = 26170 ,
SPELL_PRIEST_DIVINE_BLESSING = 40440 ,
SPELL_PRIEST_DIVINE_WRATH = 40441 ,
SPELL_PRIEST_ARMOR_OF_FAITH = 28810 ,
SPELL_PRIEST_BLESSED_HEALING = 70772 ,
SPELL_PRIEST_SHADOW_WORD_DEATH_R1 = 32379 ,
SPELL_PRIEST_MIND_BLAST_R1 = 8092 ,
SPELL_PRIEST_MIND_FLAY_DAMAGE = 58381 ,
SPELL_PRIEST_BLESSED_RECOVERY_R1 = 27813
}
enum Mics {
PRIEST_LIGHTWELL_NPC_1 = 31897 ,
PRIEST_LIGHTWELL_NPC_2 = 31896 ,
PRIEST_LIGHTWELL_NPC_3 = 31895 ,
PRIEST_LIGHTWELL_NPC_4 = 31894 ,
PRIEST_LIGHTWELL_NPC_5 = 31893 ,
PRIEST_LIGHTWELL_NPC_6 = 31883
}
Functions
static int32 CalculateSpellAmount (Unit *caster, int32 amount, SpellInfo const *spellInfo, const AuraEffect *aurEff)
void AddSC_priest_spell_scripts ()
Enumeration Type Documentation
Mics
enum Mics
Enumerator
PRIEST_LIGHTWELL_NPC_1
PRIEST_LIGHTWELL_NPC_2
PRIEST_LIGHTWELL_NPC_3
PRIEST_LIGHTWELL_NPC_4
PRIEST_LIGHTWELL_NPC_5
PRIEST_LIGHTWELL_NPC_6
{
    PRIEST_LIGHTWELL_NPC_1                          = 31897,
    PRIEST_LIGHTWELL_NPC_2                          = 31896,
    PRIEST_LIGHTWELL_NPC_3                          = 31895,
    PRIEST_LIGHTWELL_NPC_4                          = 31894,
    PRIEST_LIGHTWELL_NPC_5                          = 31893,
    PRIEST_LIGHTWELL_NPC_6                          = 31883
};
PriestProcSpells
enum PriestProcSpells
Enumerator
SPELL_PRIEST_VAMPIRIC_EMBRACE_HEAL
SPELL_PRIEST_GLYPH_OF_DISPEL_MAGIC_HEAL
SPELL_PRIEST_BODY_AND_SOUL_SPEED
SPELL_PRIEST_ORACULAR_HEAL
SPELL_PRIEST_DIVINE_BLESSING
SPELL_PRIEST_DIVINE_WRATH
SPELL_PRIEST_ARMOR_OF_FAITH
SPELL_PRIEST_BLESSED_HEALING
SPELL_PRIEST_SHADOW_WORD_DEATH_R1
SPELL_PRIEST_MIND_BLAST_R1
SPELL_PRIEST_MIND_FLAY_DAMAGE
SPELL_PRIEST_BLESSED_RECOVERY_R1
{
    SPELL_PRIEST_VAMPIRIC_EMBRACE_HEAL              = 15290,
    SPELL_PRIEST_GLYPH_OF_DISPEL_MAGIC_HEAL         = 56131,
    SPELL_PRIEST_BODY_AND_SOUL_SPEED                = 64136,
    SPELL_PRIEST_ORACULAR_HEAL                      = 26170,
    SPELL_PRIEST_DIVINE_BLESSING                    = 40440,
    SPELL_PRIEST_DIVINE_WRATH                       = 40441,
    SPELL_PRIEST_ARMOR_OF_FAITH                     = 28810,
    SPELL_PRIEST_BLESSED_HEALING                    = 70772,
    SPELL_PRIEST_SHADOW_WORD_DEATH_R1               = 32379,
    SPELL_PRIEST_MIND_BLAST_R1                      = 8092,
    SPELL_PRIEST_MIND_FLAY_DAMAGE                   = 58381,
    SPELL_PRIEST_BLESSED_RECOVERY_R1                = 27813
};
PriestSpellIcons
enum PriestSpellIcons
Enumerator
PRIEST_ICON_ID_BORROWED_TIME
PRIEST_ICON_ID_EMPOWERED_RENEW_TALENT
PRIEST_ICON_ID_PAIN_AND_SUFFERING
PRIEST_ICON_ID_BODY_AND_SOUL
{
    PRIEST_ICON_ID_BORROWED_TIME                    = 2899,
    PRIEST_ICON_ID_EMPOWERED_RENEW_TALENT           = 3021,
    PRIEST_ICON_ID_PAIN_AND_SUFFERING               = 2874,
    PRIEST_ICON_ID_BODY_AND_SOUL                    = 2218
};
PriestSpells
enum PriestSpells
Enumerator
SPELL_PRIEST_DIVINE_AEGIS
SPELL_PRIEST_EMPOWERED_RENEW
SPELL_PRIEST_GLYPH_OF_CIRCLE_OF_HEALING
SPELL_PRIEST_GLYPH_OF_LIGHTWELL
SPELL_PRIEST_GLYPH_OF_PRAYER_OF_HEALING_HEAL
SPELL_PRIEST_GUARDIAN_SPIRIT_HEAL
SPELL_PRIEST_ITEM_EFFICIENCY
SPELL_PRIEST_LIGHTWELL_CHARGES
SPELL_PRIEST_MANA_LEECH_PROC
SPELL_PRIEST_PENANCE_R1
SPELL_PRIEST_PENANCE_R1_DAMAGE
SPELL_PRIEST_PENANCE_R1_HEAL
SPELL_PRIEST_REFLECTIVE_SHIELD_TRIGGERED
SPELL_PRIEST_REFLECTIVE_SHIELD_R1
SPELL_PRIEST_SHADOW_WORD_DEATH
SPELL_PRIEST_T9_HEALING_2P
SPELL_PRIEST_VAMPIRIC_TOUCH_DISPEL
SPELL_PRIEST_T4_4P_FLEXIBILITY
SPELL_PRIEST_GLYPH_OF_SHADOWFIEND
SPELL_PRIEST_GLYPH_OF_SHADOWFIEND_MANA
SPELL_GENERIC_ARENA_DAMPENING
SPELL_GENERIC_BATTLEGROUND_DAMPENING
SPELL_PRIEST_TWIN_DISCIPLINE_R1
SPELL_PRIEST_SPIRITUAL_HEALING_R1
SPELL_PRIEST_DIVINE_PROVIDENCE_R1
{
    SPELL_PRIEST_DIVINE_AEGIS                       = 47753,
    SPELL_PRIEST_EMPOWERED_RENEW                    = 63544,
    SPELL_PRIEST_GLYPH_OF_CIRCLE_OF_HEALING         = 55675,
    SPELL_PRIEST_GLYPH_OF_LIGHTWELL                 = 55673,
    SPELL_PRIEST_GLYPH_OF_PRAYER_OF_HEALING_HEAL    = 56161,
    SPELL_PRIEST_GUARDIAN_SPIRIT_HEAL               = 48153,
    SPELL_PRIEST_ITEM_EFFICIENCY                    = 37595,
    SPELL_PRIEST_LIGHTWELL_CHARGES                  = 59907,
    SPELL_PRIEST_MANA_LEECH_PROC                    = 34650,
    SPELL_PRIEST_PENANCE_R1                         = 47540,
    SPELL_PRIEST_PENANCE_R1_DAMAGE                  = 47758,
    SPELL_PRIEST_PENANCE_R1_HEAL                    = 47757,
    SPELL_PRIEST_REFLECTIVE_SHIELD_TRIGGERED        = 33619,
    SPELL_PRIEST_REFLECTIVE_SHIELD_R1               = 33201,
    SPELL_PRIEST_SHADOW_WORD_DEATH                  = 32409,
    SPELL_PRIEST_T9_HEALING_2P                      = 67201,
    SPELL_PRIEST_VAMPIRIC_TOUCH_DISPEL              = 64085,
    SPELL_PRIEST_T4_4P_FLEXIBILITY                  = 37565,
    SPELL_PRIEST_GLYPH_OF_SHADOWFIEND               = 58228,
    SPELL_PRIEST_GLYPH_OF_SHADOWFIEND_MANA          = 58227,
    SPELL_GENERIC_ARENA_DAMPENING                   = 74410,
    SPELL_GENERIC_BATTLEGROUND_DAMPENING            = 74411,
    SPELL_PRIEST_TWIN_DISCIPLINE_R1                 = 47586,
    SPELL_PRIEST_SPIRITUAL_HEALING_R1               = 14898,
    SPELL_PRIEST_DIVINE_PROVIDENCE_R1               = 47562
};
Function Documentation
AddSC_priest_spell_scripts()
void AddSC_priest_spell_scripts ()
{
    RegisterSpellScript(spell_pri_shadowfiend_scaling);
    RegisterSpellScript(spell_pri_circle_of_healing);
    RegisterSpellScript(spell_pri_divine_aegis);
    RegisterSpellScript(spell_pri_divine_hymn);
    RegisterSpellScript(spell_pri_glyph_of_prayer_of_healing);
    RegisterSpellScript(spell_pri_guardian_spirit);
    RegisterSpellScript(spell_pri_hymn_of_hope);
    RegisterSpellScript(spell_pri_item_greater_heal_refund);
    RegisterSpellScript(spell_pri_lightwell);
    RegisterSpellScript(spell_pri_lightwell_renew);
    RegisterSpellScript(spell_pri_mana_burn);
    RegisterSpellScript(spell_pri_mana_leech);
    RegisterSpellScript(spell_pri_mind_sear);
    RegisterSpellScript(spell_pri_pain_and_suffering_dummy);
    RegisterSpellScript(spell_pri_pain_and_suffering_proc);
    RegisterSpellScript(spell_pri_penance);
    RegisterSpellAndAuraScriptPair(spell_pri_power_word_shield, spell_pri_power_word_shield_aura);
    RegisterSpellScript(spell_pri_prayer_of_mending_heal);
    RegisterSpellScript(spell_pri_renew);
    RegisterSpellScript(spell_pri_shadow_word_death);
    RegisterSpellScript(spell_pri_vampiric_touch);
    RegisterSpellScript(spell_pri_mind_control);
    RegisterSpellScript(spell_pri_t4_4p_bonus);
    RegisterSpellScript(spell_pri_shadowfiend_death);
    RegisterSpellScript(spell_pri_vampiric_embrace);
    RegisterSpellScript(spell_pri_glyph_of_dispel_magic);
    RegisterSpellScript(spell_pri_body_and_soul);
    RegisterSpellScript(spell_pri_improved_shadowform);
    // Proc system scripts
    RegisterSpellScript(spell_pri_aq_3p_bonus);
    RegisterSpellScript(spell_pri_blessed_recovery);
    RegisterSpellScript(spell_pri_imp_shadowform);
    RegisterSpellScript(spell_pri_improved_spirit_tap);
    RegisterSpellScript(spell_pri_item_t6_trinket);
    RegisterSpellScript(spell_pri_t3_4p_bonus);
    RegisterSpellScript(spell_pri_t5_heal_2p_bonus);
    RegisterSpellScript(spell_pri_t10_heal_2p_bonus);
}
References RegisterSpellAndAuraScriptPair, and RegisterSpellScript.
Referenced by AddSpellsScripts().
CalculateSpellAmount()
static int32 CalculateSpellAmount (Unit * caster, int32 amount, SpellInfo const * spellInfo, const AuraEffect * aurEff) static
{
    // +80.68% from sp bonus
    float bonus = 0.8068f;
    // Borrowed Time
    if (AuraEffect const* borrowedTime = caster->GetDummyAuraEffect(SPELLFAMILY_PRIEST, PRIEST_ICON_ID_BORROWED_TIME, EFFECT_1))
        bonus += CalculatePct(1.0f, borrowedTime->GetAmount());
    bonus *= caster->SpellBaseHealingBonusDone(spellInfo->GetSchoolMask());
    // Improved PW: Shield: its weird having a SPELLMOD_ALL_EFFECTS here but its blizzards doing :)
    // Improved PW: Shield is only applied at the spell healing bonus because it was already applied to the base value in CalculateSpellDamage
    bonus = caster->ApplyEffectModifiers(spellInfo, aurEff->GetEffIndex(), bonus);
    bonus *= caster->CalculateLevelPenalty(spellInfo);
    amount += int32(bonus);
    // Twin Disciplines
    if (AuraEffect const* twinDisciplines = caster->GetAuraEffect(SPELL_AURA_ADD_PCT_MODIFIER, SPELLFAMILY_PRIEST, 0x400000, 0, 0, caster->GetGUID()))
        AddPct(amount, twinDisciplines->GetAmount());
    // Focused Power, xinef: apply positive modifier only
    if (int32 healModifier = caster->GetMaxPositiveAuraModifier(SPELL_AURA_MOD_HEALING_DONE_PERCENT))
        AddPct(amount, healModifier);
    // Arena - Dampening
    if (AuraEffect const* arenaDampening = caster->GetAuraEffect(SPELL_GENERIC_ARENA_DAMPENING, EFFECT_0))
    {
        AddPct(amount, arenaDampening->GetAmount());
    }
    // Battleground - Dampening
    else if (AuraEffect const* bgDampening = caster->GetAuraEffect(SPELL_GENERIC_BATTLEGROUND_DAMPENING, EFFECT_0))
    {
        AddPct(amount, bgDampening->GetAmount());
    }
    return amount;
};
References AddPct(), Unit::ApplyEffectModifiers(), Unit::CalculateLevelPenalty(), CalculatePct(), EFFECT_0, EFFECT_1, Unit::GetAuraEffect(), Unit::GetDummyAuraEffect(), AuraEffect::GetEffIndex(), Object::GetGUID(), Unit::GetMaxPositiveAuraModifier(), SpellInfo::GetSchoolMask(), PRIEST_ICON_ID_BORROWED_TIME, SPELL_AURA_ADD_PCT_MODIFIER, SPELL_AURA_MOD_HEALING_DONE_PERCENT, SPELL_GENERIC_ARENA_DAMPENING, SPELL_GENERIC_BATTLEGROUND_DAMPENING, Unit::SpellBaseHealingBonusDone(), and SPELLFAMILY_PRIEST.
Referenced by spell_pri_power_word_shield_aura::CalculateAmount(), and spell_pri_power_word_shield::CheckCast().