AzerothCore Doxygen
spell_thaddius_pos_neg_charge Class Reference
Private Member Functions
PrepareSpellScript (spell_thaddius_pos_neg_charge)
bool Validate (SpellInfo const *) override
void HandleTargets (std::list< WorldObject * > &targets)
void HandleDamage (SpellEffIndex)
void Register () override
Additional Inherited Members
Public Member Functions inherited from SpellScript
bool _Validate (SpellInfo const *entry) override
bool _Load (Spell *spell)
void _InitHit ()
bool _IsEffectPrevented (SpellEffIndex effIndex)
bool _IsDefaultEffectPrevented (SpellEffIndex effIndex)
void _PrepareScriptCall (SpellScriptHookType hookType)
void _FinishScriptCall ()
bool IsInCheckCastHook () const
bool IsInTargetHook () const
bool IsInHitPhase () const
bool IsInEffectHook () const
Unit * GetCaster ()
Unit * GetOriginalCaster ()
SpellInfo const * GetSpellInfo ()
SpellValue const * GetSpellValue ()
WorldLocation const * GetExplTargetDest ()
void SetExplTargetDest (WorldLocation &loc)
WorldObject * GetExplTargetWorldObject ()
Unit * GetExplTargetUnit ()
GameObject * GetExplTargetGObj ()
Item * GetExplTargetItem ()
Unit * GetHitUnit ()
Creature * GetHitCreature ()
Player * GetHitPlayer ()
Item * GetHitItem ()
GameObject * GetHitGObj ()
WorldLocation * GetHitDest ()
int32 GetHitDamage ()
void SetHitDamage (int32 damage)
void PreventHitDamage ()
int32 GetHitHeal ()
void SetHitHeal (int32 heal)
void PreventHitHeal ()
Spell * GetSpell ()
Aura * GetHitAura ()
void PreventHitAura ()
void PreventHitEffect (SpellEffIndex effIndex)
void PreventHitDefaultEffect (SpellEffIndex effIndex)
int32 GetEffectValue () const
void SetEffectValue (int32 value)
Item * GetCastItem ()
void CreateItem (uint32 effIndex, uint32 itemId)
SpellInfo const * GetTriggeringSpell ()
void FinishCast (SpellCastResult result)
void Cancel ()
void SetCustomCastResultMessage (SpellCustomErrors result)
Public Member Functions inherited from _SpellScript
_SpellScript ()
virtual ~_SpellScript ()
virtual void _Register ()
virtual void _Unload ()
virtual void _Init (std::string const *scriptname, uint32 spellId)
std::string const * _GetScriptName () const
virtual bool Load ()
virtual void Unload ()
Static Public Member Functions inherited from _SpellScript
static bool ValidateSpellInfo (std::initializer_list< uint32 > spellIds)
template<class T >
static bool ValidateSpellInfo (T const &spellIds)
Public Attributes inherited from SpellScript
HookList< CastHandler > BeforeCast
HookList< CastHandler > OnCast
HookList< CastHandler > AfterCast
HookList< CheckCastHandler > OnCheckCast
HookList< EffectHandler > OnEffectLaunch
HookList< EffectHandler > OnEffectLaunchTarget
HookList< EffectHandler > OnEffectHit
HookList< EffectHandler > OnEffectHitTarget
HookList< BeforeHitHandler > BeforeHit
HookList< HitHandler > OnHit
HookList< HitHandler > AfterHit
HookList< ObjectAreaTargetSelectHandler > OnObjectAreaTargetSelect
HookList< ObjectTargetSelectHandler > OnObjectTargetSelect
HookList< DestinationTargetSelectHandler > OnDestinationTargetSelect
Protected Attributes inherited from _SpellScript
uint8 m_currentScriptState
std::string const * m_scriptName
uint32 m_scriptSpellId
Detailed Description
Member Function Documentation
HandleDamage()
void spell_thaddius_pos_neg_charge::HandleDamage (SpellEffIndex) inline private
    {
        if (!GetTriggeringSpell())
            return;
        Unit* target = GetHitUnit();
        if (!target)
            return;
        if (target->HasAura(GetTriggeringSpell()->Id) || !target->IsPlayer())
        {
            SetHitDamage(0);
        }
        else if (InstanceScript* instance = target->GetInstanceScript())
        {
            instance->SetData(DATA_CHARGES_CROSSED, 0);
        }
    }
References DATA_CHARGES_CROSSED, SpellScript::GetHitUnit(), WorldObject::GetInstanceScript(), SpellScript::GetTriggeringSpell(), Unit::HasAura(), Object::IsPlayer(), and SpellScript::SetHitDamage().
Referenced by Register().
HandleTargets()
void spell_thaddius_pos_neg_charge::HandleTargets (std::list< WorldObject * > & targets) inline private
    {
        uint8 count = 0;
        for (auto& ihit : targets)
        {
            if (ihit->GetGUID() != GetCaster()->GetGUID())
            {
                if (Player* target = ihit->ToPlayer())
                {
                    if (target->HasAura(GetTriggeringSpell()->Id))
                    {
                        ++count;
                    }
                }
            }
        }
        if (count)
        {
            uint32 spellId = GetSpellInfo()->Id == SPELL_POSITIVE_CHARGE ? SPELL_POSITIVE_CHARGE_STACK : SPELL_NEGATIVE_CHARGE_STACK;
            GetCaster()->SetAuraStack(spellId, GetCaster(), count);
        }
    }
References SpellScript::GetCaster(), Object::GetGUID(), SpellScript::GetSpellInfo(), SpellScript::GetTriggeringSpell(), SpellInfo::Id, Unit::SetAuraStack(), SPELL_NEGATIVE_CHARGE_STACK, SPELL_POSITIVE_CHARGE, SPELL_POSITIVE_CHARGE_STACK, and Object::ToPlayer().
Referenced by Register().
PrepareSpellScript()
spell_thaddius_pos_neg_charge::PrepareSpellScript (spell_thaddius_pos_neg_charge) private
Register()
void spell_thaddius_pos_neg_charge::Register () inline override private virtual
Implements _SpellScript.
    {
        OnEffectHitTarget += SpellEffectFn(spell_thaddius_pos_neg_charge::HandleDamage, EFFECT_0, SPELL_EFFECT_SCHOOL_DAMAGE);
        OnObjectAreaTargetSelect += SpellObjectAreaTargetSelectFn(spell_thaddius_pos_neg_charge::HandleTargets, EFFECT_0, TARGET_UNIT_SRC_AREA_ALLY);
    }
References EFFECT_0, HandleDamage(), HandleTargets(), SpellScript::OnEffectHitTarget, SpellScript::OnObjectAreaTargetSelect, SPELL_EFFECT_SCHOOL_DAMAGE, SpellEffectFn, SpellObjectAreaTargetSelectFn, and TARGET_UNIT_SRC_AREA_ALLY.
Validate()
bool spell_thaddius_pos_neg_charge::Validate (SpellInfo const *) inline override private virtual
Reimplemented from _SpellScript.
    {
        return ValidateSpellInfo({ SPELL_POSITIVE_CHARGE, SPELL_POSITIVE_CHARGE_STACK });
    }
References SPELL_POSITIVE_CHARGE, SPELL_POSITIVE_CHARGE_STACK, and _SpellScript::ValidateSpellInfo().
The documentation for this class was generated from the following file:
azerothcore-wotlk/src/server/scripts/Northrend/Naxxramas/boss_thaddius.cpp