AzerothCore Doxygen
Totem Class Reference
#include "Totem.h"
Public Member Functions
Totem (SummonPropertiesEntry const *properties, ObjectGuid owner)
~Totem () override
void Update (uint32 time) override
void InitStats (uint32 duration) override
void InitSummon () override
void UnSummon (Milliseconds msTime=0ms) override
uint32 GetSpell (uint8 slot=0) const
uint32 GetTotemDuration () const
void SetTotemDuration (uint32 duration)
TotemType GetTotemType () const
bool UpdateStats (Stats) override
bool UpdateAllStats () override
void UpdateResistances (uint32) override
void UpdateArmor () override
void UpdateMaxHealth () override
void UpdateMaxPower (Powers) override
void UpdateAttackPowerAndDamage (bool) override
void UpdateDamagePhysical (WeaponAttackType) override
bool IsImmunedToSpellEffect (SpellInfo const *spellInfo, uint32 index) const override
Public Member Functions inherited from Minion
Minion (SummonPropertiesEntry const *properties, ObjectGuid owner)
void RemoveFromWorld () override
Unit * GetOwner () const
float GetFollowAngle () const override
void SetFollowAngle (float angle)
bool IsPetGhoul () const
bool IsGuardianPet () const
void setDeathState (DeathState s, bool despawn=false) override
A creature can be in 4 different states: Alive, JustDied, Corpse, and JustRespawned. The cycle follows the next order:
std::string GetDebugInfo () const override
Public Member Functions inherited from TempSummon
TempSummon (SummonPropertiesEntry const *properties, ObjectGuid owner)
~TempSummon () override=default
void UpdateObjectVisibilityOnCreate () override
void RemoveFromWorld () override
void SetTempSummonType (TempSummonType type)
void SaveToDB (uint32, uint8, uint32) override
WorldObject * GetSummoner () const
Unit * GetSummonerUnit () const
Creature * GetSummonerCreatureBase () const
GameObject * GetSummonerGameObject () const
ObjectGuid GetSummonerGUID () const
TempSummonType GetSummonType () const
uint32 GetTimer ()
void SetTimer (uint32 t)
void SetVisibleBySummonerOnly (bool visibleBySummonerOnly)
bool IsVisibleBySummonerOnly () const
std::string GetDebugInfo () const override
Public Member Functions inherited from Creature
Creature ()
~Creature () override
void AddToWorld () override
float GetNativeObjectScale () const override
void SetObjectScale (float scale) override
void SetDisplayId (uint32 displayId, float displayScale=1.f) override
void SetDisplayFromModel (uint32 modelIdx)
void DisappearAndDie ()
bool isVendorWithIconSpeak () const
bool Create (ObjectGuid::LowType guidlow, Map *map, uint32 phaseMask, uint32 Entry, uint32 vehId, float x, float y, float z, float ang, const CreatureData *data=nullptr)
bool LoadCreaturesAddon (bool reload=false)
void SelectLevel (bool changelevel=true)
void LoadEquipment (int8 id=1, bool force=false)
ObjectGuid::LowType GetSpawnId () const
void GetRespawnPosition (float &x, float &y, float &z, float *ori=nullptr, float *dist=nullptr) const
void SetCorpseDelay (uint32 delay)
void SetCorpseRemoveTime (uint32 delay)
uint32 GetCorpseDelay () const
bool HasFlagsExtra (uint32 flag) const
bool IsRacialLeader () const
bool IsCivilian () const
bool IsTrigger () const
bool IsGuard () const
CreatureMovementData const & GetMovementTemplate () const
bool CanWalk () const
bool CanSwim () const override
This method check the current flag/status of a creature and its inhabit type.
bool CanEnterWater () const override
bool CanFly () const override
bool CanHover () const
bool IsRooted () const
MovementGeneratorType GetDefaultMovementType () const override
-------—End of Pet responses methods-------—
void SetDefaultMovementType (MovementGeneratorType mgt)
void SetReactState (ReactStates state)
A creature can have 3 ReactStates : Agressive, Passive, Neutral.
ReactStates GetReactState () const
bool HasReactState (ReactStates state) const
void InitializeReactState ()
Check if the creature has the specified ReactState.
bool isCanInteractWithBattleMaster (Player *player, bool msg) const
bool CanResetTalents (Player *player) const
bool CanCreatureAttack (Unit const *victim, bool skipDistCheck=false) const
void LoadSpellTemplateImmunity ()
bool IsImmunedToSpell (SpellInfo const *spellInfo, Spell const *spell=nullptr) override
bool HasMechanicTemplateImmunity (uint32 mask) const
bool isElite () const
bool isWorldBoss () const
bool IsDungeonBoss () const
bool IsImmuneToKnockback () const
bool IsAvoidingAOE () const
uint8 getLevelForTarget (WorldObject const *target) const override
bool IsInEvadeMode () const
bool IsEvadingAttacks () const
bool AIM_Initialize (CreatureAI *ai=nullptr)
void Motion_Initialize ()
CreatureAI * AI () const
bool SetWalk (bool enable) override
Enable or disable the creature's walk mode by removing: MOVEMENTFLAG_WALKING. Infom also the client.
bool SetSwim (bool enable) override
bool HasSpellFocus (Spell const *focusSpell=nullptr) const
uint32 GetShieldBlockValue () const override
SpellSchoolMask GetMeleeDamageSchoolMask (WeaponAttackType=BASE_ATTACK, uint8=0) const override
void SetMeleeDamageSchool (SpellSchools school)
void _AddCreatureSpellCooldown (uint32 spell_id, uint16 categoryId, uint32 end_time)
void AddSpellCooldown (uint32 spell_id, uint32, uint32 end_time, bool needSendToClient=false, bool forceSendToSpectator=false) override
bool HasSpellCooldown (uint32 spell_id) const override
uint32 GetSpellCooldown (uint32 spell_id) const
void ProhibitSpellSchool (SpellSchoolMask idSchoolMask, uint32 unTimeMs) override
bool IsSpellProhibited (SpellSchoolMask idSchoolMask) const
void ClearProhibitedSpellTimers ()
bool HasSpell (uint32 spellID) const override
void UpdateMovementFlags ()
uint32 GetRandomId (uint32 id1, uint32 id2, uint32 id3)
bool UpdateEntry (uint32 entry, const CreatureData *data=nullptr, bool changelevel=true, bool updateAI=false)
bool UpdateEntry (uint32 entry, bool updateAI)
void CalculateMinMaxDamage (WeaponAttackType attType, bool normalized, bool addTotalPct, float &minDamage, float &maxDamage, uint8 damageIndex) override
void LoadSparringPct ()
float GetSparringPct () const
bool HasWeapon (WeaponAttackType type) const override
bool HasWeaponForAttack (WeaponAttackType type) const override
void SetCanDualWield (bool value) override
int8 GetOriginalEquipmentId () const
uint8 GetCurrentEquipmentId ()
void SetCurrentEquipmentId (uint8 id)
float GetSpellDamageMod (int32 Rank)
VendorItemData const * GetVendorItems () const
uint32 GetVendorItemCurrentCount (VendorItem const *vItem)
uint32 UpdateVendorItemCurrentCount (VendorItem const *vItem, uint32 used_count)
CreatureTemplate const * GetCreatureTemplate () const
CreatureData const * GetCreatureData () const
void SetDetectionDistance (float dist)
CreatureAddon const * GetCreatureAddon () const
std::string const & GetAIName () const
std::string GetScriptName () const
uint32 GetScriptId () const
std::string const & GetNameForLocaleIdx (LocaleConstant locale_idx) const override
bool LoadFromDB (ObjectGuid::LowType guid, Map *map, bool allowDuplicate=false)
bool LoadCreatureFromDB (ObjectGuid::LowType guid, Map *map, bool addToMap=true, bool allowDuplicate=false)
void SaveToDB ()
virtual void DeleteFromDB ()
ObjectGuid GetLootRecipientGUID () const
Player * GetLootRecipient () const
ObjectGuid::LowType GetLootRecipientGroupGUID () const
Group * GetLootRecipientGroup () const
bool hasLootRecipient () const
bool isTappedBy (Player const *player) const
bool CanGeneratePickPocketLoot () const
void SetPickPocketLootTime ()
void ResetPickPocketLootTime ()
void SetLootRecipient (Unit *unit, bool withGroup=true)
void AllLootRemovedFromCorpse ()
uint16 GetLootMode () const
bool HasLootMode (uint16 lootMode) const
void SetLootMode (uint16 lootMode)
void AddLootMode (uint16 lootMode)
void RemoveLootMode (uint16 lootMode)
void ResetLootMode ()
SpellInfo const * reachWithSpellAttack (Unit *victim)
SpellInfo const * reachWithSpellCure (Unit *victim)
bool CanStartAttack (Unit const *u) const
float GetAggroRange (Unit const *target) const
float GetAttackDistance (Unit const *player) const
float GetDetectionRange () const
void SendAIReaction (AiReaction reactionType)
Unit * SelectNearestTarget (float dist=0, bool playerOnly=false) const
Select nearest hostile unit within the given distance (regardless of threat list).
Unit * SelectNearestTargetInAttackDistance (float dist) const
Select nearest hostile unit within the given attack distance (i.e. distance is ignored if > than ATTACK_DISTANCE), regardless of threat list.
void DoFleeToGetAssistance ()
void CallForHelp (float fRadius, Unit *target=nullptr)
void CallAssistance (Unit *target=nullptr)
void SetNoCallForHelp (bool val)
void SetNoCallAssistance (bool val)
void SetNoSearchAssistance (bool val)
bool HasSearchedAssistance ()
bool CanAssistTo (Unit const *u, Unit const *enemy, bool checkfaction=true) const
bool _IsTargetAcceptable (Unit const *target) const
bool CanIgnoreFeignDeath () const
void UpdateMoveInLineOfSightState ()
bool IsMoveInLineOfSightDisabled ()
bool IsMoveInLineOfSightStrictlyDisabled ()
void RemoveCorpse (bool setSpawnTime=true, bool skipVisibility=false)
void DespawnOrUnsummon (Milliseconds msTimeToDespawn=0ms, Seconds forcedRespawnTimer=0s)
void DespawnOnEvade (Seconds respawnDelay=20s)
time_t const & GetRespawnTime () const
time_t GetRespawnTimeEx () const
void SetRespawnTime (uint32 respawn)
void Respawn (bool force=false)
void SaveRespawnTime () override
uint32 GetRespawnDelay () const
void SetRespawnDelay (uint32 delay)
uint32 GetCombatPulseDelay () const
void SetCombatPulseDelay (uint32 delay)
float GetWanderDistance () const
void SetWanderDistance (float dist)
void DoImmediateBoundaryCheck ()
void SendZoneUnderAttackMessage (Player *attacker)
Send a message to LocalDefense channel for players opposition team in the zone.
void SetInCombatWithZone ()
Set in combat all units in the dungeon/raid. Affect only units with IsAIEnabled.
bool hasQuest (uint32 quest_id) const override
bool hasInvolvedQuest (uint32 quest_id) const override
bool isRegeneratingHealth ()
void SetRegeneratingHealth (bool enable)
void SetRegeneratingPower (bool enable)
virtual uint8 GetPetAutoSpellSize () const
virtual uint32 GetPetAutoSpellOnPos (uint8 pos) const
void SetCannotReachTarget (ObjectGuid const &target=ObjectGuid::Empty)
bool CanNotReachTarget () const
bool IsNotReachableAndNeedRegen () const
void SetPosition (float x, float y, float z, float o)
void SetPosition (const Position &pos)
void SetHomePosition (float x, float y, float z, float o)
void SetHomePosition (const Position &pos)
void GetHomePosition (float &x, float &y, float &z, float &ori) const
Position const & GetHomePosition () const
void SetTransportHomePosition (float x, float y, float z, float o)
void SetTransportHomePosition (const Position &pos)
void GetTransportHomePosition (float &x, float &y, float &z, float &ori) const
Position const & GetTransportHomePosition () const
uint32 GetWaypointPath () const
void LoadPath (uint32 pathid)
uint32 GetCurrentWaypointID () const
void UpdateWaypointID (uint32 wpID)
void SearchFormation ()
CreatureGroup const * GetFormation () const
CreatureGroup * GetFormation ()
void SetFormation (CreatureGroup *formation)
Unit * SelectVictim ()
void SetReputationRewardDisabled (bool disable)
bool IsReputationRewardDisabled () const
void SetLootRewardDisabled (bool disable)
bool IsLootRewardDisabled () const
bool IsDamageEnoughForLootingAndReward () const
void LowerPlayerDamageReq (uint32 unDamage, bool damagedByPlayer=true)
void ResetPlayerDamageReq ()
uint32 GetPlayerDamageReq () const
uint32 GetOriginalEntry () const
void SetOriginalEntry (uint32 entry)
void SetTarget (ObjectGuid guid=ObjectGuid::Empty) override
void ClearTarget ()
void FocusTarget (Spell const *focusSpell, WorldObject const *target)
void ReleaseFocus (Spell const *focusSpell)
bool IsMovementPreventedByCasting () const override
std::shared_ptr< time_t > const & GetLastLeashExtensionTimePtr () const
void SetLastLeashExtensionTimePtr (std::shared_ptr< time_t > const &timer)
void ClearLastLeashExtensionTimePtr ()
time_t GetLastLeashExtensionTime () const
void UpdateLeashExtensionTime ()
uint8 GetLeashTimer () const
CreatureTextRepeatIds const & GetTextRepeatGroup (uint8 textGroup)
void SetTextRepeatId (uint8 textGroup, uint8 id)
void ClearTextRepeatGroup (uint8 textGroup)
bool IsFreeToMove ()
bool HasSwimmingFlagOutOfCombat () const
void RefreshSwimmingFlag (bool recheck=false)
void SetAssistanceTimer (uint32 value)
void ModifyThreatPercentTemp (Unit *victim, int32 percent, Milliseconds duration)
void ResumeChasingVictim ()
Helper to resume chasing current victim.
bool CanCastSpell (uint32 spellID) const
Returns true if the creature is able to cast the spell.
ObjectGuid GetSummonerGUID () const
Helper to get the creature's summoner GUID, if it is a summon.
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool IsUpdateNeeded () override
Public Member Functions inherited from Unit
~Unit () override
void Update (uint32 time) override
UnitAI * GetAI ()
void SetAI (UnitAI *newAI)
void AddToWorld () override
void RemoveFromWorld () override
void CleanupBeforeRemoveFromMap (bool finalCleanup)
void CleanupsBeforeDelete (bool finalCleanup=true) override
virtual bool isBeingLoaded () const
bool IsDuringRemoveFromWorld () const
void SetUInt32Value (uint16 index, uint32 value)
Unit * GetOwner () const
ObjectGuid GetOwnerGUID () const
void SetOwnerGUID (ObjectGuid owner)
ObjectGuid GetCreatorGUID () const
void SetCreatorGUID (ObjectGuid creator)
ObjectGuid GetMinionGUID () const
void SetMinionGUID (ObjectGuid guid)
ObjectGuid GetCharmerGUID () const
void SetCharmerGUID (ObjectGuid owner)
ObjectGuid GetCharmGUID () const
void SetPetGUID (ObjectGuid guid)
ObjectGuid GetPetGUID () const
void SetCritterGUID (ObjectGuid guid)
ObjectGuid GetCritterGUID () const
ObjectGuid GetTransGUID () const override
Pet * ToPet ()
Totem * ToTotem ()
TempSummon * ToTempSummon ()
const TempSummon * ToTempSummon () const
void AddUnitState (uint32 f)
bool HasUnitState (const uint32 f) const
void ClearUnitState (uint32 f)
uint32 GetUnitState () const
uint32 HasUnitTypeMask (uint32 mask) const
void AddUnitTypeMask (uint32 mask)
uint32 GetUnitTypeMask () const
UnitFlags GetUnitFlags () const
bool HasUnitFlag (UnitFlags flags) const
void SetUnitFlag (UnitFlags flags)
UnitFlags available in UnitDefines.h.
void RemoveUnitFlag (UnitFlags flags)
UnitFlags available in UnitDefines.h.
void ReplaceAllUnitFlags (UnitFlags flags)
Remove the Unit flag specify only.
UnitFlags2 GetUnitFlags2 () const
Remove all UnitFlags and set new ones. UnitFlags available in UnitDefines.h.
bool HasUnitFlag2 (UnitFlags2 flags) const
void SetUnitFlag2 (UnitFlags2 flags)
void RemoveUnitFlag2 (UnitFlags2 flags)
void ReplaceAllUnitFlags2 (UnitFlags2 flags)
void SetEmoteState (Emote emoteState)
void ClearEmoteState ()
Sets emote state (looping emote). Emotes available in SharedDefines.h.
NPCFlags GetNpcFlags () const
Clears emote state (looping emote)
bool HasNpcFlag (NPCFlags flags) const
void SetNpcFlag (NPCFlags flags)
void RemoveNpcFlag (NPCFlags flags)
void ReplaceAllNpcFlags (NPCFlags flags)
uint32 GetDynamicFlags () const override
void ReplaceAllDynamicFlags (uint32 flag) override
void AddUnitMovementFlag (uint32 f)
void RemoveUnitMovementFlag (uint32 f)
bool HasUnitMovementFlag (uint32 f) const
uint32 GetUnitMovementFlags () const
void SetUnitMovementFlags (uint32 f)
void AddExtraUnitMovementFlag (uint16 f)
void RemoveExtraUnitMovementFlag (uint16 f)
uint16 HasExtraUnitMovementFlag (uint16 f) const
uint16 GetExtraUnitMovementFlags () const
void SetExtraUnitMovementFlags (uint16 f)
bool IsCrowdControlled () const
bool IsImmobilizedState () const
void SetAnimTier (AnimTier animTier)
bool IsSummon () const
bool IsGuardian () const
bool IsControllableGuardian () const
bool IsPet () const
bool IsHunterPet () const
bool IsTotem () const
bool IsVehicle () const
bool IsVendor () const
bool IsTrainer () const
bool IsQuestGiver () const
bool IsGossip () const
bool IsTaxi () const
bool IsGuildMaster () const
bool IsBattleMaster () const
bool IsBanker () const
bool IsInnkeeper () const
bool IsSpiritHealer () const
bool IsSpiritGuide () const
bool IsTabardDesigner () const
bool IsAuctioner () const
bool IsArmorer () const
bool IsServiceProvider () const
bool IsSpiritService () const
uint32 GetCreatureType () const
uint32 GetCreatureTypeMask () const
bool IsCritter () const
uint8 getRace (bool original=false) const
void setRace (uint8 race)
uint32 getRaceMask () const
DisplayRace GetDisplayRaceFromModelId (uint32 modelId) const
DisplayRace GetDisplayRace () const
uint8 getClass () const
virtual bool IsClass (Classes unitClass, ClassContext context=CLASS_CONTEXT_NONE) const
uint32 getClassMask () const
uint8 getGender () const
uint32 GetFaction () const
FactionTemplateEntry const * GetFactionTemplateEntry () const
void SetFaction (uint32 faction)
void RestoreFaction ()
uint32 GetOldFactionId () const
ObjectGuid GetTarget () const
bool isTargetableForAttack (bool checkFakeDeath=true, Unit const *byWho=nullptr) const
bool IsValidAttackTarget (Unit const *target, SpellInfo const *bySpell=nullptr) const
bool _IsValidAttackTarget (Unit const *target, SpellInfo const *bySpell, WorldObject const *obj=nullptr) const
bool IsValidAssistTarget (Unit const *target) const
bool _IsValidAssistTarget (Unit const *target, SpellInfo const *bySpell) const
bool IsClientControlled (Player const *exactClient=nullptr) const
Player const * GetClientControlling () const
float GetBoundaryRadius () const
float GetCombatReach () const override
float GetMeleeReach () const
bool IsWithinRange (Unit const *obj, float dist) const
bool IsWithinBoundaryRadius (const Unit *obj) const
bool IsWithinCombatRange (Unit const *obj, float dist2compare) const
bool IsWithinMeleeRange (Unit const *obj, float dist=0.f) const
float GetMeleeRange (Unit const *target) const
void setAttackTimer (WeaponAttackType type, int32 time)
void resetAttackTimer (WeaponAttackType type=BASE_ATTACK)
int32 getAttackTimer (WeaponAttackType type) const
bool isAttackReady (WeaponAttackType type=BASE_ATTACK) const
bool GetRandomContactPoint (Unit const *target, float &x, float &y, float &z, bool force=false) const
Unit * getAttackerForHelper () const
bool Attack (Unit *victim, bool meleeAttack)
void CastStop (uint32 except_spellid=0, bool withInstant=true)
Interrupt the unit cast for all the current spells.
bool AttackStop ()
Force the unit to stop attacking. This will clear UNIT_STATE_MELEE_ATTACKING, Interrupt current spell, AI assistance, and call SendMeleeAttackStop() to the client.
void RemoveAllAttackers ()
Remove all units in m_attackers list and send them AttackStop()
AttackerSet const & getAttackers () const
bool GetMeleeAttackPoint (Unit *attacker, Position &pos)
bool isAttackingPlayer () const
Unit * GetVictim () const
void CombatStop (bool includingCast=false)
void CombatStopWithPets (bool includingCast=false)
void StopAttackFaction (uint32 faction_id)
void StopAttackingInvalidTarget ()
Unit * SelectNearbyTarget (Unit *exclude=nullptr, float dist=NOMINAL_MELEE_RANGE) const
Unit * SelectNearbyNoTotemTarget (Unit *exclude=nullptr, float dist=NOMINAL_MELEE_RANGE) const
void SendMeleeAttackStop (Unit *victim=nullptr)
Send to the client SMSG_ATTACKSTOP but doesn't clear UNIT_STATE_MELEE_ATTACKING on server side or interrupt spells. Unless you know exactly what you're doing, use AttackStop() or RemoveAllAttackers() instead.
void SendMeleeAttackStart (Unit *victim, Player *sendTo=nullptr)
uint32 GetAttackTime (WeaponAttackType att) const
void SetAttackTime (WeaponAttackType att, uint32 val)
void ApplyAttackTimePercentMod (WeaponAttackType att, float val, bool apply)
void ApplyCastTimePercentMod (float val, bool apply)
void SetImmuneToAll (bool apply, bool keepCombat=false)
bool IsImmuneToAll () const
void SetImmuneToPC (bool apply, bool keepCombat=false)
bool IsImmuneToPC () const
void SetImmuneToNPC (bool apply, bool keepCombat=false)
bool IsImmuneToNPC () const
bool IsEngaged () const
bool IsEngagedBy (Unit const *who) const
bool IsInCombat () const
bool IsInCombatWith (Unit const *who) const
bool IsPetInCombat () const
void CombatStart (Unit *target, bool initialAggro=true)
void CombatStartOnCast (Unit *target, bool initialAggro=true, uint32 duration=0)
void SetInCombatState (bool PvP, Unit *enemy=nullptr, uint32 duration=0)
void SetInCombatWith (Unit *enemy, uint32 duration=0)
void ClearInCombat ()
void ClearInPetCombat ()
uint32 GetCombatTimer () const
void SetCombatTimer (uint32 timer)
bool CanHaveThreatList (bool skipAliveCheck=false) const
void AddThreat (Unit *victim, float fThreat, SpellSchoolMask schoolMask=SPELL_SCHOOL_MASK_NORMAL, SpellInfo const *threatSpell=nullptr)
float ApplyTotalThreatModifier (float fThreat, SpellSchoolMask schoolMask=SPELL_SCHOOL_MASK_NORMAL)
void TauntApply (Unit *victim)
void TauntFadeOut (Unit *taunter)
ThreatMgr & GetThreatMgr ()
ThreatMgr const & GetThreatMgr () const
void addHatedBy (HostileReference *pHostileReference)
void removeHatedBy (HostileReference *)
HostileRefMgr & getHostileRefMgr ()
void SetRedirectThreat (ObjectGuid guid, uint32 pct)
void ResetRedirectThreat ()
void ModifyRedirectThreat (int32 amount)
uint32 GetRedirectThreatPercent ()
Unit * GetRedirectThreatTarget () const
void SetLastDamagedTargetGuid (ObjectGuid const &guid)
ObjectGuid const & GetLastDamagedTargetGuid () const
void AttackerStateUpdate (Unit *victim, WeaponAttackType attType=BASE_ATTACK, bool extra=false, bool ignoreCasting=false)
bool haveOffhandWeapon () const
bool CanDualWield () const
virtual void SetDualWieldMode (DualWieldMode mode)
bool HasMainhandWeapon () const
bool HasOffhandWeapon () const
bool HasRangedWeapon () const
bool hasMainhandWeaponForAttack () const
bool HasMainhandWeaponForAttack () const
bool HasOffhandWeaponForAttack () const
bool HasRangedWeaponForAttack () const
bool CanUseAttackType (WeaponAttackType attacktype) const
void HandleProcExtraAttackFor (Unit *victim, uint32 count)
void SetLastExtraAttackSpell (uint32 spellId)
uint32 GetLastExtraAttackSpell () const
void AddExtraAttacks (uint32 count)
uint8 GetComboPoints (Unit const *who=nullptr) const
uint8 GetComboPoints (ObjectGuid const &guid) const
Unit * GetComboTarget () const
ObjectGuid const GetComboTargetGUID () const
void AddComboPoints (Unit *target, int8 count)
void AddComboPoints (int8 count)
void ClearComboPoints ()
void AddComboPointHolder (Unit *unit)
void RemoveComboPointHolder (Unit *unit)
void ClearComboPointHolders ()
void SetContestedPvP (Player *attackedPlayer=nullptr, bool lookForNearContestedGuards=true)
bool IsContestedGuard () const
bool RespondsToCallForHelp () const
bool IsInSanctuary () const
bool IsPvP () const
bool IsFFAPvP () const
void SetPvP (bool state)
float GetStat (Stats stat) const
void SetStat (Stats stat, int32 val)
Stats GetStatByAuraGroup (UnitMods unitMod) const
float GetCreateStat (Stats stat) const
void SetCreateStat (Stats stat, float val)
float GetPosStat (Stats stat) const
float GetNegStat (Stats stat) const
void InitStatBuffMods ()
bool HandleStatFlatModifier (UnitMods unitMod, UnitModifierFlatType modifierType, float amount, bool apply)
void ApplyStatPctModifier (UnitMods unitMod, UnitModifierPctType modifierType, float amount)
void SetStatFlatModifier (UnitMods unitMod, UnitModifierFlatType modifierType, float val)
void SetStatPctModifier (UnitMods unitMod, UnitModifierPctType modifierType, float val)
float GetFlatModifierValue (UnitMods unitMod, UnitModifierFlatType modifierType) const
float GetPctModifierValue (UnitMods unitMod, UnitModifierPctType modifierType) const
void UpdateUnitMod (UnitMods unitMod)
virtual bool CheckAttackFitToAuraRequirement (WeaponAttackType, AuraEffect const *) const
virtual void UpdateDamageDoneMods (WeaponAttackType attackType, int32 skipEnchantSlot=-1)
void UpdateAllDamageDoneMods ()
void UpdateDamagePctDoneMods (WeaponAttackType attackType)
void UpdateAllDamagePctDoneMods ()
float GetTotalStatValue (Stats stat, float additionalValue=0.0f) const
void SetCanModifyStats (bool modifyStats)
bool CanModifyStats () const
void UpdateStatBuffMod (Stats stat)
uint8 GetLevel () const
uint8 getLevelForTarget (WorldObject const *) const override
void SetLevel (uint8 lvl, bool showLevelChange=true)
uint32 GetHealth () const
uint32 GetMaxHealth () const
float GetHealthPct () const
int32 GetHealthGain (int32 dVal)
uint32 GetCreateHealth () const
bool IsFullHealth () const
bool HealthBelowPct (int32 pct) const
bool HealthBelowPctDamaged (int32 pct, uint32 damage) const
bool HealthAbovePct (int32 pct) const
bool HealthAbovePctHealed (int32 pct, uint32 heal) const
uint32 CountPctFromMaxHealth (int32 pct) const
uint32 CountPctFromCurHealth (int32 pct) const
void SetHealth (uint32 val)
void SetMaxHealth (uint32 val)
void SetFullHealth ()
int32 ModifyHealth (int32 val)
void SetCreateHealth (uint32 val)
Powers getPowerType () const
virtual bool HasActivePowerType (Powers power)
Powers GetPowerTypeByAuraGroup (UnitMods unitMod) const
uint32 GetPower (Powers power) const
uint32 GetMaxPower (Powers power) const
float GetPowerPct (Powers power) const
uint32 GetCreatePowers (Powers power) const
void setPowerType (Powers power)
void SetPower (Powers power, uint32 val, bool withPowerUpdate=true, bool fromRegenerate=false)
void SetMaxPower (Powers power, uint32 val)
int32 ModifyPower (Powers power, int32 val, bool withPowerUpdate=true)
void RewardRage (uint32 damage, uint32 weaponSpeedHitFactor, bool attacker)
uint32 GetCreateMana () const
void SetCreateMana (uint32 val)
bool CanRestoreMana (SpellInfo const *spellInfo) const
void SetLastManaUse (uint32 spellCastTime)
bool IsUnderLastManaUseEffect () const
float GetAPMultiplier (WeaponAttackType attType, bool normalized)
uint32 GetArmor () const
void SetArmor (int32 val)
float GetUnitDodgeChance () const
float GetUnitParryChance () const
float GetUnitBlockChance () const
float GetUnitMissChance (WeaponAttackType attType) const
float GetUnitCriticalChance (WeaponAttackType attackType, Unit const *victim) const
MeleeHitOutcome RollMeleeOutcomeAgainst (Unit const *victim, WeaponAttackType attType) const
MeleeHitOutcome RollMeleeOutcomeAgainst (Unit const *victim, WeaponAttackType attType, int32 crit_chance, int32 miss_chance, int32 dodge_chance, int32 parry_chance, int32 block_chance) const
bool CanApplyResilience () const
uint32 GetShieldBlockValue (uint32 soft_cap, uint32 hard_cap) const
uint32 GetUnitMeleeSkill (Unit const *target=nullptr) const
uint32 GetDefenseSkillValue (Unit const *target=nullptr) const
uint32 GetWeaponSkillValue (WeaponAttackType attType, Unit const *target=nullptr) const
int32 GetMechanicResistChance (SpellInfo const *spell)
uint32 GetResistance (SpellSchoolMask mask) const
uint32 GetResistance (SpellSchools school) const
void SetResistance (SpellSchools school, int32 val)
void UpdateResistanceBuffModsMod (SpellSchools school)
uint16 GetMaxSkillValueForLevel (Unit const *target=nullptr) const
float GetTotalAuraModValue (UnitMods unitMod) const
SpellSchools GetSpellSchoolByAuraGroup (UnitMods unitMod) const
float GetTotalAttackPowerValue (WeaponAttackType attType, Unit *pVictim=nullptr) const
float GetWeaponDamageRange (WeaponAttackType attType, WeaponDamageRange type, uint8 damageIndex=0) const
void SetBaseWeaponDamage (WeaponAttackType attType, WeaponDamageRange damageRange, float value, uint8 damageIndex=0)
virtual void UpdateAllResistances ()
void DealMeleeDamage (CalcDamageInfo *damageInfo, bool durabilityLoss)
void DealSpellDamage (SpellNonMeleeDamage *damageInfo, bool durabilityLoss, Spell const *spell=nullptr)
void DealDamageShieldDamage (Unit *victim)
void KillSelf (bool durabilityLoss=true, WeaponAttackType attackType=BASE_ATTACK, SpellInfo const *spellProto=nullptr, Spell const *spell=nullptr)
uint32 CalculateDamage (WeaponAttackType attType, bool normalized, bool addTotalPct, uint8 itemDamagesMask=0)
void CalculateMeleeDamage (Unit *victim, CalcDamageInfo *damageInfo, WeaponAttackType attackType=BASE_ATTACK, const bool sittingVictim=false)
void CalculateSpellDamageTaken (SpellNonMeleeDamage *damageInfo, int32 damage, SpellInfo const *spellInfo, WeaponAttackType attackType=BASE_ATTACK, bool crit=false)
int32 CalculateSpellDamage (Unit const *target, SpellInfo const *spellProto, uint8 effect_index, int32 const *basePoints=nullptr) const
float CalculateDefaultCoefficient (SpellInfo const *spellInfo, DamageEffectType damagetype) const
uint32 MeleeDamageBonusDone (Unit *pVictim, uint32 damage, WeaponAttackType attType, SpellInfo const *spellProto=nullptr, SpellSchoolMask damageSchoolMask=SPELL_SCHOOL_MASK_NORMAL)
uint32 MeleeDamageBonusTaken (Unit *attacker, uint32 pdamage, WeaponAttackType attType, SpellInfo const *spellProto=nullptr, SpellSchoolMask damageSchoolMask=SPELL_SCHOOL_MASK_NORMAL)
int32 SpellBaseDamageBonusDone (SpellSchoolMask schoolMask)
int32 SpellBaseDamageBonusTaken (SpellSchoolMask schoolMask, bool isDoT=false)
float SpellPctDamageModsDone (Unit *victim, SpellInfo const *spellProto, DamageEffectType damagetype)
uint32 SpellDamageBonusDone (Unit *victim, SpellInfo const *spellProto, uint32 pdamage, DamageEffectType damagetype, uint8 effIndex, float TotalMod=0.0f, uint32 stack=1)
uint32 SpellDamageBonusTaken (Unit *caster, SpellInfo const *spellProto, uint32 pdamage, DamageEffectType damagetype, uint32 stack=1)
int32 CalculateAOEDamageReduction (int32 damage, uint32 schoolMask, bool npcCaster) const
uint32 GetMeleeDamageReduction (uint32 damage) const
uint32 GetRangedDamageReduction (uint32 damage) const
uint32 GetSpellDamageReduction (uint32 damage) const
float GetMeleeCritChanceReduction () const
float GetRangedCritChanceReduction () const
float GetSpellCritChanceReduction () const
uint32 GetMeleeCritDamageReduction (uint32 damage) const
uint32 GetRangedCritDamageReduction (uint32 damage) const
uint32 GetSpellCritDamageReduction (uint32 damage) const
CharmInfo * GetCharmInfo ()
CharmInfo * InitCharmInfo ()
Unit * GetCharmer () const
Unit * GetCharm () const
Unit * GetCharmerOrOwner () const
Unit * GetCharmerOrOwnerOrSelf () const
Player * GetCharmerOrOwnerPlayerOrPlayerItself () const
ObjectGuid GetCharmerOrOwnerGUID () const
ObjectGuid GetCharmerOrOwnerOrOwnGUID () const
Player * GetAffectingPlayer () const
Unit * GetFirstControlled () const
bool IsControlledByPlayer () const
bool IsCreatedByPlayer () const
bool IsCharmedOwnedByPlayerOrPlayer () const
bool IsCharmed () const
bool isPossessed () const
bool isPossessedByPlayer () const
bool isPossessing () const
bool isPossessing (Unit *u) const
void SetCharm (Unit *target, bool apply)
bool SetCharmedBy (Unit *charmer, CharmType type, AuraApplication const *aurApp=nullptr)
void UpdateCharmAI ()
void RemoveCharmedBy (Unit *charmer)
void RemoveCharmAuras ()
void RemoveAllControlled (bool onDeath=false)
void DeleteCharmInfo ()
virtual bool HasSpellItemCooldown (uint32, uint32) const
void BuildCooldownPacket (WorldPacket &data, uint8 flags, uint32 spellId, uint32 cooldown)
void BuildCooldownPacket (WorldPacket &data, uint8 flags, PacketCooldowns const &cooldowns)
Aura * AddAura (uint32 spellId, Unit *target)
Aura * AddAura (SpellInfo const *spellInfo, uint8 effMask, Unit *target)
void SetAuraStack (uint32 spellId, Unit *target, uint32 stack)
int32 GetHighestExclusiveSameEffectSpellGroupValue (AuraEffect const *aurEff, AuraType auraType, bool checkMiscValue=false, int32 miscValue=0) const
bool IsHighestExclusiveAura (Aura const *aura, bool removeOtherAuraApplications=false)
bool IsHighestExclusiveAuraEffect (SpellInfo const *spellInfo, AuraType auraType, int32 effectAmount, uint8 auraEffectMask, bool removeOtherAuraApplications=false)
Aura * _TryStackingOrRefreshingExistingAura (SpellInfo const *newAura, uint8 effMask, Unit *caster, int32 *baseAmount=nullptr, Item *castItem=nullptr, ObjectGuid casterGUID=ObjectGuid::Empty, bool periodicReset=false)
void _AddAura (UnitAura *aura, Unit *caster)
AuraApplication * _CreateAuraApplication (Aura *aura, uint8 effMask)
void _ApplyAuraEffect (Aura *aura, uint8 effIndex)
void _ApplyAura (AuraApplication *aurApp, uint8 effMask)
void _UnapplyAura (AuraApplicationMap::iterator &i, AuraRemoveMode removeMode)
void _UnapplyAura (AuraApplication *aurApp, AuraRemoveMode removeMode)
void _RemoveNoStackAuraApplicationsDueToAura (Aura *aura)
void _RemoveNoStackAurasDueToAura (Aura *aura, bool owned)
bool _IsNoStackAuraDueToAura (Aura *appliedAura, Aura *existingAura) const
void _RegisterAuraEffect (AuraEffect *aurEff, bool apply)
AuraMap & GetOwnedAuras ()
AuraMap const & GetOwnedAuras () const
void RemoveOwnedAura (AuraMap::iterator &i, AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
void RemoveOwnedAura (uint32 spellId, ObjectGuid casterGUID=ObjectGuid::Empty, uint8 reqEffMask=0, AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
void RemoveOwnedAura (Aura *aura, AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
Aura * GetOwnedAura (uint32 spellId, ObjectGuid casterGUID=ObjectGuid::Empty, ObjectGuid itemCasterGUID=ObjectGuid::Empty, uint8 reqEffMask=0, Aura *except=nullptr) const
AuraApplicationMap & GetAppliedAuras ()
AuraApplicationMap const & GetAppliedAuras () const
void RemoveAura (AuraApplicationMap::iterator &i, AuraRemoveMode mode=AURA_REMOVE_BY_DEFAULT)
void RemoveAura (uint32 spellId, ObjectGuid casterGUID=ObjectGuid::Empty, uint8 reqEffMask=0, AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
void RemoveAura (AuraApplication *aurApp, AuraRemoveMode mode=AURA_REMOVE_BY_DEFAULT)
void RemoveAura (Aura *aur, AuraRemoveMode mode=AURA_REMOVE_BY_DEFAULT)
void RemoveBindSightAuras ()
void RemoveAppliedAuras (std::function< bool(AuraApplication const *)> const &check)
void RemoveOwnedAuras (std::function< bool(Aura const *)> const &check)
void RemoveAppliedAuras (uint32 spellId, std::function< bool(AuraApplication const *)> const &check)
void RemoveOwnedAuras (uint32 spellId, std::function< bool(Aura const *)> const &check)
void RemoveAurasDueToSpell (uint32 spellId, ObjectGuid casterGUID=ObjectGuid::Empty, uint8 reqEffMask=0, AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
void RemoveAuraFromStack (uint32 spellId, ObjectGuid casterGUID=ObjectGuid::Empty, AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
void RemoveAurasDueToSpellByDispel (uint32 spellId, uint32 dispellerSpellId, ObjectGuid casterGUID, Unit *dispeller, uint8 chargesRemoved=1)
void RemoveAurasDueToSpellBySteal (uint32 spellId, ObjectGuid casterGUID, Unit *stealer)
void RemoveAurasDueToItemSpell (uint32 spellId, ObjectGuid castItemGuid)
void RemoveAurasByType (AuraType auraType, ObjectGuid casterGUID=ObjectGuid::Empty, Aura *except=nullptr, bool negative=true, bool positive=true)
void RemoveNotOwnSingleTargetAuras ()
void RemoveAurasWithInterruptFlags (uint32 flag, uint32 except=0, bool isAutoshot=false)
void RemoveAurasWithAttribute (uint32 flags)
void RemoveAurasWithFamily (SpellFamilyNames family, uint32 familyFlag1, uint32 familyFlag2, uint32 familyFlag3, ObjectGuid casterGUID)
void RemoveAurasWithMechanic (uint32 mechanic_mask, AuraRemoveMode removemode=AURA_REMOVE_BY_DEFAULT, uint32 except=0)
void RemoveMovementImpairingAuras (bool withRoot)
void RemoveAurasByShapeShift ()
void RemoveAreaAurasDueToLeaveWorld ()
void RemoveAllAuras ()
void RemoveArenaAuras ()
void RemoveAllAurasOnDeath ()
void RemoveAllAurasRequiringDeadTarget ()
void RemoveAllAurasExceptType (AuraType type)
void RemoveEvadeAuras ()
void DelayOwnedAuras (uint32 spellId, ObjectGuid caster, int32 delaytime)
void _RemoveAllAuraStatMods ()
void _ApplyAllAuraStatMods ()
AuraEffectList const & GetAuraEffectsByType (AuraType type) const
AuraList & GetSingleCastAuras ()
AuraList const & GetSingleCastAuras () const
AuraEffect * GetAuraEffect (uint32 spellId, uint8 effIndex, ObjectGuid casterGUID=ObjectGuid::Empty) const
AuraEffect * GetAuraEffectOfRankedSpell (uint32 spellId, uint8 effIndex, ObjectGuid casterGUID=ObjectGuid::Empty) const
AuraEffect * GetAuraEffect (AuraType type, SpellFamilyNames name, uint32 iconId, uint8 effIndex) const
AuraEffect * GetAuraEffect (AuraType type, SpellFamilyNames family, uint32 familyFlag1, uint32 familyFlag2, uint32 familyFlag3, ObjectGuid casterGUID=ObjectGuid::Empty) const
AuraEffect * GetAuraEffectDummy (uint32 spellid) const
AuraEffect * GetDummyAuraEffect (SpellFamilyNames name, uint32 iconId, uint8 effIndex) const
AuraApplication * GetAuraApplication (uint32 spellId, ObjectGuid casterGUID=ObjectGuid::Empty, ObjectGuid itemCasterGUID=ObjectGuid::Empty, uint8 reqEffMask=0, AuraApplication *except=nullptr) const
Aura * GetAura (uint32 spellId, ObjectGuid casterGUID=ObjectGuid::Empty, ObjectGuid itemCasterGUID=ObjectGuid::Empty, uint8 reqEffMask=0) const
AuraApplication * GetAuraApplicationOfRankedSpell (uint32 spellId, ObjectGuid casterGUID=ObjectGuid::Empty, ObjectGuid itemCasterGUID=ObjectGuid::Empty, uint8 reqEffMask=0, AuraApplication *except=nullptr) const
Aura * GetAuraOfRankedSpell (uint32 spellId, ObjectGuid casterGUID=ObjectGuid::Empty, ObjectGuid itemCasterGUID=ObjectGuid::Empty, uint8 reqEffMask=0) const
void GetDispellableAuraList (Unit *caster, uint32 dispelMask, DispelChargesList &dispelList, SpellInfo const *dispelSpell)
bool HasAuraEffect (uint32 spellId, uint8 effIndex, ObjectGuid caster=ObjectGuid::Empty) const
uint32 GetAuraCount (uint32 spellId) const
bool HasAuras (SearchMethod sm, std::vector< uint32 > &spellIds) const
Check if unit has ANY or ALL specified auras.
template<typename... Auras>
bool HasAnyAuras (Auras... spellIds) const
Checks if the unit has ANY specified auras.
template<typename... Auras>
bool HasAllAuras (Auras... spellIds) const
Checks if the unit has ALL specified auras.
bool HasAura (uint32 spellId, ObjectGuid casterGUID=ObjectGuid::Empty, ObjectGuid itemCasterGUID=ObjectGuid::Empty, uint8 reqEffMask=0) const
bool HasAuraType (AuraType auraType) const
bool HasAuraTypeWithCaster (AuraType auratype, ObjectGuid caster) const
bool HasAuraTypeWithMiscvalue (AuraType auratype, int32 miscvalue) const
bool HasAuraTypeWithAffectMask (AuraType auratype, SpellInfo const *affectedSpell) const
bool HasAuraTypeWithValue (AuraType auratype, int32 value) const
bool HasAuraTypeWithTriggerSpell (AuraType auratype, uint32 triggerSpell) const
bool HasNegativeAuraWithInterruptFlag (uint32 flag, ObjectGuid guid=ObjectGuid::Empty)
bool HasVisibleAuraType (AuraType auraType) const
bool HasNegativeAuraWithAttribute (uint32 flag, ObjectGuid guid=ObjectGuid::Empty)
bool HasAuraWithMechanic (uint32 mechanicMask) const
bool HasAuraTypeWithFamilyFlags (AuraType auraType, uint32 familyName, uint32 familyFlags) const
bool HasBreakableByDamageAuraType (AuraType type, uint32 excludeAura=0) const
bool HasBreakableByDamageCrowdControlAura (Unit *excludeCasterChannel=nullptr) const
AuraEffect * IsScriptOverriden (SpellInfo const *spell, int32 script) const
uint32 GetDiseasesByCaster (ObjectGuid casterGUID, uint8 mode=0)
uint32 GetDoTsByCaster (ObjectGuid casterGUID) const
int32 GetTotalAuraModifier (AuraType auratype) const
float GetTotalAuraMultiplier (AuraType auratype) const
int32 GetMaxPositiveAuraModifier (AuraType auratype) const
int32 GetMaxNegativeAuraModifier (AuraType auratype) const
int32 GetTotalAuraModifier (AuraType auratype, std::function< bool(AuraEffect const *)> const &predicate) const
float GetTotalAuraMultiplier (AuraType auraType, std::function< bool(AuraEffect const *)> const &predicate) const
int32 GetMaxPositiveAuraModifier (AuraType auraType, std::function< bool(AuraEffect const *)> const &predicate) const
int32 GetMaxNegativeAuraModifier (AuraType auraType, std::function< bool(AuraEffect const *)> const &predicate) const
int32 GetTotalAuraModifierByMiscMask (AuraType auratype, uint32 misc_mask) const
float GetTotalAuraMultiplierByMiscMask (AuraType auratype, uint32 misc_mask) const
int32 GetMaxPositiveAuraModifierByMiscMask (AuraType auratype, uint32 misc_mask, const AuraEffect *except=nullptr) const
int32 GetMaxNegativeAuraModifierByMiscMask (AuraType auratype, uint32 misc_mask) const
int32 GetTotalAuraModifierByMiscValue (AuraType auratype, int32 misc_value) const
float GetTotalAuraMultiplierByMiscValue (AuraType auratype, int32 misc_value) const
int32 GetMaxPositiveAuraModifierByMiscValue (AuraType auratype, int32 misc_value) const
int32 GetMaxNegativeAuraModifierByMiscValue (AuraType auratype, int32 misc_value) const
int32 GetTotalAuraModifierByAffectMask (AuraType auratype, SpellInfo const *affectedSpell) const
float GetTotalAuraMultiplierByAffectMask (AuraType auratype, SpellInfo const *affectedSpell) const
int32 GetMaxPositiveAuraModifierByAffectMask (AuraType auratype, SpellInfo const *affectedSpell) const
int32 GetMaxNegativeAuraModifierByAffectMask (AuraType auratype, SpellInfo const *affectedSpell) const
VisibleAuraMap const * GetVisibleAuras ()
AuraApplication * GetVisibleAura (uint8 slot)
void SetVisibleAura (uint8 slot, AuraApplication *aur)
void RemoveVisibleAura (uint8 slot)
void ModifyAuraState (AuraStateType flag, bool apply)
uint32 BuildAuraStateUpdateForTarget (Unit *target) const
bool HasAuraState (AuraStateType flag, SpellInfo const *spellProto=nullptr, Unit const *Caster=nullptr) const
bool CanProc ()
void SetCantProc (bool apply)
void ProcDamageAndSpellFor (bool isVictim, Unit *target, uint32 procFlag, uint32 procExtra, WeaponAttackType attType, SpellInfo const *procSpellInfo, uint32 damage, SpellInfo const *procAura=nullptr, int8 procAuraEffectIndex=-1, Spell const *procSpell=nullptr, DamageInfo *damageInfo=nullptr, HealInfo *healInfo=nullptr, uint32 procPhase=2)
void GetProcAurasTriggeredOnEvent (std::list< AuraApplication * > &aurasTriggeringProc, std::list< AuraApplication * > *procAuras, ProcEventInfo eventInfo)
void TriggerAurasProcOnEvent (CalcDamageInfo &damageInfo)
void TriggerAurasProcOnEvent (std::list< AuraApplication * > *myProcAuras, std::list< AuraApplication * > *targetProcAuras, Unit *actionTarget, uint32 typeMaskActor, uint32 typeMaskActionTarget, uint32 spellTypeMask, uint32 spellPhaseMask, uint32 hitMask, Spell *spell, DamageInfo *damageInfo, HealInfo *healInfo)
void TriggerAurasProcOnEvent (ProcEventInfo &eventInfo, std::list< AuraApplication * > &procAuras)
float GetWeaponProcChance () const
float GetPPMProcChance (uint32 WeaponSpeed, float PPM, SpellInfo const *spellProto) const
Player * GetSpellModOwner () const
Spell * GetCurrentSpell (CurrentSpellTypes spellType) const
Spell * GetCurrentSpell (uint32 spellType) const
Spell * GetFirstCurrentCastingSpell () const
Spell * FindCurrentSpellBySpellId (uint32 spell_id) const
int32 GetCurrentSpellCastTime (uint32 spell_id) const
void SetCurrentCastedSpell (Spell *pSpell)
void SetInstantCast (bool set)
bool CanInstantCast () const
bool IsNonMeleeSpellCast (bool withDelayed, bool skipChanneled=false, bool skipAutorepeat=false, bool isAutoshoot=false, bool skipInstant=true) const
void InterruptNonMeleeSpells (bool withDelayed, uint32 spellid=0, bool withInstant=true, bool bySelf=false)
float GetSpellMaxRangeForTarget (Unit const *target, SpellInfo const *spellInfo) const
float GetSpellMinRangeForTarget (Unit const *target, SpellInfo const *spellInfo) const
uint32 GetInterruptMask () const
void AddInterruptMask (uint32 mask)
void UpdateInterruptMask ()
void InterruptSpell (CurrentSpellTypes spellType, bool withDelayed=true, bool withInstant=true, bool bySelf=false)
bool isSpellBlocked (Unit *victim, SpellInfo const *spellProto, WeaponAttackType attackType=BASE_ATTACK)
void FinishSpell (CurrentSpellTypes spellType, bool ok=true)
Unit * GetMagicHitRedirectTarget (Unit *victim, SpellInfo const *spellInfo)
Unit * GetMeleeHitRedirectTarget (Unit *victim, SpellInfo const *spellInfo=nullptr)
float MeleeSpellMissChance (Unit const *victim, WeaponAttackType attType, int32 skillDiff, uint32 spellId) const
SpellMissInfo MeleeSpellHitResult (Unit *victim, SpellInfo const *spell)
SpellMissInfo MagicSpellHitResult (Unit *victim, SpellInfo const *spell)
SpellMissInfo SpellHitResult (Unit *victim, SpellInfo const *spell, bool canReflect=false)
SpellMissInfo SpellHitResult (Unit *victim, Spell const *spell, bool canReflect=false)
void SendHealSpellLog (HealInfo const &healInfo, bool critical=false)
int32 HealBySpell (HealInfo &healInfo, bool critical=false)
int32 SpellBaseHealingBonusDone (SpellSchoolMask schoolMask)
float SpellPctHealingModsDone (Unit *victim, SpellInfo const *spellProto, DamageEffectType damagetype)
uint32 SpellHealingBonusDone (Unit *victim, SpellInfo const *spellProto, uint32 healamount, DamageEffectType damagetype, uint8 effIndex, float TotalMod=0.0f, uint32 stack=1)
uint32 SpellHealingBonusTaken (Unit *caster, SpellInfo const *spellProto, uint32 healamount, DamageEffectType damagetype, uint32 stack=1)
void SendEnergizeSpellLog (Unit *victim, uint32 SpellID, uint32 Damage, Powers powertype)
void EnergizeBySpell (Unit *victim, uint32 SpellID, uint32 Damage, Powers powertype)
void ApplySpellImmune (uint32 spellId, uint32 op, uint32 type, bool apply, SpellImmuneBlockType blockType=SPELL_BLOCK_TYPE_ALL)
void ApplySpellDispelImmunity (SpellInfo const *spellProto, DispelType type, bool apply)
bool IsImmunedToDamage (SpellSchoolMask meleeSchoolMask) const
bool IsImmunedToDamage (SpellInfo const *spellInfo) const
bool IsImmunedToDamage (Spell const *spell) const
bool IsImmunedToSchool (SpellSchoolMask meleeSchoolMask) const
bool IsImmunedToSchool (SpellInfo const *spellInfo) const
bool IsImmunedToSchool (Spell const *spell) const
bool IsImmunedToDamageOrSchool (SpellSchoolMask meleeSchoolMask) const
bool IsImmunedToDamageOrSchool (SpellInfo const *spellInfo) const
bool isBlockCritical ()
float SpellDoneCritChance (Unit const *, SpellInfo const *spellProto, SpellSchoolMask schoolMask, WeaponAttackType attackType, bool skipEffectCheck) const
float SpellTakenCritChance (Unit const *caster, SpellInfo const *spellProto, SpellSchoolMask schoolMask, float doneChance, WeaponAttackType attackType, bool skipEffectCheck) const
float ApplyEffectModifiers (SpellInfo const *spellProto, uint8 effect_index, float value) const
int32 CalcSpellDuration (SpellInfo const *spellProto)
int32 ModSpellDuration (SpellInfo const *spellProto, Unit const *target, int32 duration, bool positive, uint32 effectMask)
void ModSpellCastTime (SpellInfo const *spellProto, int32 &castTime, Spell *spell=nullptr)
float CalculateLevelPenalty (SpellInfo const *spellProto) const
uint32 GetCastingTimeForBonus (SpellInfo const *spellProto, DamageEffectType damagetype, uint32 CastingTime) const
void CastDelayedSpellWithPeriodicAmount (Unit *caster, uint32 spellId, AuraType auraType, int32 addAmount, uint8 effectIndex=0)
SpellCastResult CastSpell (SpellCastTargets const &targets, SpellInfo const *spellInfo, CustomSpellValues const *value, TriggerCastFlags triggerFlags=TRIGGERED_NONE, Item *castItem=nullptr, AuraEffect const *triggeredByAura=nullptr, ObjectGuid originalCaster=ObjectGuid::Empty)
SpellCastResult CastSpell (Unit *victim, uint32 spellId, bool triggered, Item *castItem=nullptr, AuraEffect const *triggeredByAura=nullptr, ObjectGuid originalCaster=ObjectGuid::Empty)
SpellCastResult CastSpell (Unit *victim, uint32 spellId, TriggerCastFlags triggerFlags=TRIGGERED_NONE, Item *castItem=nullptr, AuraEffect const *triggeredByAura=nullptr, ObjectGuid originalCaster=ObjectGuid::Empty)
SpellCastResult CastSpell (Unit *victim, SpellInfo const *spellInfo, bool triggered, Item *castItem=nullptr, AuraEffect const *triggeredByAura=nullptr, ObjectGuid originalCaster=ObjectGuid::Empty)
SpellCastResult CastSpell (Unit *victim, SpellInfo const *spellInfo, TriggerCastFlags triggerFlags=TRIGGERED_NONE, Item *castItem=nullptr, AuraEffect const *triggeredByAura=nullptr, ObjectGuid originalCaster=ObjectGuid::Empty)
SpellCastResult CastSpell (float x, float y, float z, uint32 spellId, bool triggered, Item *castItem=nullptr, AuraEffect const *triggeredByAura=nullptr, ObjectGuid originalCaster=ObjectGuid::Empty)
SpellCastResult CastSpell (GameObject *go, uint32 spellId, bool triggered, Item *castItem=nullptr, AuraEffect *triggeredByAura=nullptr, ObjectGuid originalCaster=ObjectGuid::Empty)
SpellCastResult CastCustomSpell (Unit *victim, uint32 spellId, int32 const *bp0, int32 const *bp1, int32 const *bp2, bool triggered, Item *castItem=nullptr, AuraEffect const *triggeredByAura=nullptr, ObjectGuid originalCaster=ObjectGuid::Empty)
SpellCastResult CastCustomSpell (uint32 spellId, SpellValueMod mod, int32 value, Unit *victim, bool triggered, Item *castItem=nullptr, AuraEffect const *triggeredByAura=nullptr, ObjectGuid originalCaster=ObjectGuid::Empty)
SpellCastResult CastCustomSpell (uint32 spellId, SpellValueMod mod, int32 value, Unit *victim=nullptr, TriggerCastFlags triggerFlags=TRIGGERED_NONE, Item *castItem=nullptr, AuraEffect const *triggeredByAura=nullptr, ObjectGuid originalCaster=ObjectGuid::Empty)
SpellCastResult CastCustomSpell (uint32 spellId, CustomSpellValues const &value, Unit *victim=nullptr, TriggerCastFlags triggerFlags=TRIGGERED_NONE, Item *castItem=nullptr, AuraEffect const *triggeredByAura=nullptr, ObjectGuid originalCaster=ObjectGuid::Empty)
SpellCastResult CastCustomSpell (SpellInfo const *spellInfo, CustomSpellValues const &value, Unit *victim=nullptr, TriggerCastFlags triggerFlags=TRIGGERED_NONE, Item *castItem=nullptr, AuraEffect const *triggeredByAura=nullptr, ObjectGuid originalCaster=ObjectGuid::Empty)
void _RegisterDynObject (DynamicObject *dynObj)
void _UnregisterDynObject (DynamicObject *dynObj)
DynamicObject * GetDynObject (uint32 spellId)
bool RemoveDynObject (uint32 spellId)
void RemoveAllDynObjects ()
GameObject * GetGameObject (uint32 spellId) const
void AddGameObject (GameObject *gameObj)
void RemoveGameObject (GameObject *gameObj, bool del)
void RemoveGameObject (uint32 spellid, bool del)
void RemoveAllGameObjects ()
bool IsPolymorphed () const
bool isFrozen () const
bool IsInFlight () const
bool IsLevitating () const
bool IsWalking () const
bool isMoving () const
bool isTurning () const
bool IsHovering () const
bool isSwimming () const
bool IsFlying () const
bool IsFalling () const
bool IsRooted () const
float GetHoverHeight () const
bool CanFreeMove () const
bool HasLeewayMovement () const
void KnockbackFrom (float x, float y, float speedXY, float speedZ)
void JumpTo (float speedXY, float speedZ, bool forward=true)
void JumpTo (WorldObject *obj, float speedZ)
void UpdateSpeed (UnitMoveType mtype, bool forced)
float GetSpeed (UnitMoveType mtype) const
float GetSpeedRate (UnitMoveType mtype) const
void SetSpeed (UnitMoveType mtype, float rate, bool forced=false)
void SetSpeedRate (UnitMoveType mtype, float rate)
void propagateSpeedChange ()
void SendMonsterMove (float NewPosX, float NewPosY, float NewPosZ, uint32 TransitTime, SplineFlags sf=SPLINEFLAG_WALK_MODE)
void MonsterMoveWithSpeed (float x, float y, float z, float speed)
void SetDisableGravity (bool disable)
void SetCanFly (bool enable)
Add the movement flag: MOVEMENTFLAGCAN_FLY. Generaly only use by players, allowing them to fly by pressing space for example. For creatures, please look for DisableGravity().
void SetWaterWalking (bool enable)
void SetFeatherFall (bool enable)
void SetHover (bool enable)
MotionMaster * GetMotionMaster ()
const MotionMaster * GetMotionMaster () const
bool IsStopped () const
void StopMoving ()
void StopMovingOnCurrentPos ()
virtual void PauseMovement (uint32 timer=0, uint8 slot=0)
Disable the unit movement by clearing UNIT_STATE_MOVING and stopping the spline.
void ResumeMovement (uint32 timer=0, uint8 slot=0)
void SetControlled (bool apply, UnitState state, Unit *source=nullptr, bool isFear=false)
void DisableRotate (bool apply)
void DisableSpline ()
SheathState GetSheath () const
virtual void SetSheath (SheathState sheathed)
uint8 getStandState () const
bool IsSitState () const
bool IsStandState () const
bool IsStandUpOnMovementState () const
void SetStandState (uint8 state)
void SetStandFlags (uint8 flags)
void RemoveStandFlags (uint8 flags)
DeathState getDeathState ()
bool IsAlive () const
bool isDying () const
bool isDead () const
bool HasGhostAura () const
bool HasMountedAura () const
bool HasWaterWalkAura () const
bool HasFeatherFallAura () const
bool HasHoverAura () const
bool HasFlyAura () const
bool HasSpiritOfRedemptionAura () const
bool HasPreventsFleeingAura () const
bool HasPreventDurabilityLossAura () const
bool HasPreventResurectionAura () const
bool HasTransformAura () const
bool HasInterruptRegenAura () const
bool HasNoPVPCreditAura () const
bool HasWaterBreathingAura () const
bool HasIgnoreHitDirectionAura () const
bool HasSpellMagnetAura () const
bool HasOpenStableAura () const
bool HasCloneCasterAura () const
bool HasReflectSpellsAura () const
bool HasDetectAmoreAura () const
bool HasAllowOnlyAbilityAura () const
bool HasPeriodicDummyAura () const
bool HasControlVehicleAura () const
bool HasAOECharmAura () const
bool HasDetectSpellsAura () const
bool HasPacifySilenceAura () const
bool HasSilenceAura () const
bool HasShapeshiftAura () const
bool HasDecreaseSpeedAura () const
bool HasPacifyAura () const
bool HasIgnoreTargetResistAura () const
bool HasIncreaseMountedSpeedAura () const
bool HasIncreaseMountedFlightSpeedAura () const
bool HasThreatAura () const
bool HasAttackerSpellCritChanceAura () const
bool HasUnattackableAura () const
bool HasHealthRegenInCombatAura () const
bool HasRegenDuringCombatAura () const
bool HasFearAura () const
bool HasConfuseAura () const
bool HasRootAura () const
bool HasStunAura () const
bool HasTauntAura () const
bool HasStealthAura () const
bool HasStealthDetectAura () const
bool HasInvisibilityAura () const
bool HasInvisibilityDetectAura () const
bool IsHostileTo (Unit const *unit) const
bool IsHostileToPlayers () const
bool IsFriendlyTo (Unit const *unit) const
bool IsNeutralToAll () const
void ClearAllReactives ()
void StartReactiveTimer (ReactiveType reactive)
void UpdateReactives (uint32 p_time)
DiminishingLevels GetDiminishing (DiminishingGroup group)
void IncrDiminishing (DiminishingGroup group)
float ApplyDiminishingToDuration (DiminishingGroup group, int32 &duration, Unit *caster, DiminishingLevels Level, int32 limitduration)
void ApplyDiminishingAura (DiminishingGroup group, bool apply)
void ClearDiminishings ()
bool IsInPartyWith (Unit const *unit) const
bool IsInRaidWith (Unit const *unit) const
void GetPartyMembers (std::list< Unit * > &units)
Unit * GetNextRandomRaidMemberOrPet (float radius)
void UpdateAuraForGroup (uint8 slot)
ReputationRank GetReactionTo (Unit const *target, bool checkOriginalFaction=false) const
ReputationRank GetFactionReactionTo (FactionTemplateEntry const *factionTemplateEntry, Unit const *target) const
SharedVisionList const & GetSharedVisionList ()
void AddPlayerToVision (Player *player)
void RemovePlayerFromVision (Player *player)
bool HasSharedVision () const
uint32 GetVirtualItemId (uint32 slot) const
void SetVirtualItem (uint32 slot, uint32 itemId)
bool IsMounted () const
uint32 GetMountID () const
void Mount (uint32 mount, uint32 vehicleId=0, uint32 creatureEntry=0)
void Dismount ()
bool IsInDisallowedMountForm () const
void addFollower (FollowerReference *pRef)
void removeFollower (FollowerReference *)
Guardian * GetGuardianPet () const
Minion * GetFirstMinion () const
Creature * GetCompanionPet () const
Pet * CreateTamedPetFrom (Creature *creatureTarget, uint32 spell_id=0)
Pet * CreateTamedPetFrom (uint32 creatureEntry, uint32 spell_id=0)
bool InitTamedPet (Pet *pet, uint8 level, uint32 spell_id)
void SetMinion (Minion *minion, bool apply)
void GetAllMinionsByEntry (std::list< Creature * > &Minions, uint32 entry)
void RemoveAllMinionsByEntry (uint32 entry)
void AddPetAura (PetAura const *petSpell)
void RemovePetAura (PetAura const *petSpell)
void CastPetAura (PetAura const *aura)
bool IsPetAura (Aura const *aura)
void PetSpellFail (SpellInfo const *spellInfo, Unit *target, uint32 result)
void UnsummonAllTotems (bool onDeath=false)
TransportBase * GetDirectTransport () const
bool CreateVehicleKit (uint32 id, uint32 creatureEntry)
Returns the transport this unit is on directly (if on vehicle and transport, return vehicle)
void RemoveVehicleKit ()
Vehicle * GetVehicleKit () const
Vehicle * GetVehicle () const
bool IsOnVehicle (Unit const *vehicle) const
Unit * GetVehicleBase () const
Creature * GetVehicleCreatureBase () const
void EnterVehicle (Unit *base, int8 seatId=-1)
void EnterVehicleUnattackable (Unit *base, int8 seatId=-1)
void ExitVehicle (Position const *exitPosition=nullptr)
void ChangeSeat (int8 seatId, bool next=true)
bool HandleSpellClick (Unit *clicker, int8 seatId=-1)
void _ExitVehicle (Position const *exitPosition=nullptr)
void _EnterVehicle (Vehicle *vehicle, int8 seatId, AuraApplication const *aurApp=nullptr)
void HandleEmoteCommand (uint32 emoteId)
virtual void Talk (std::string_view text, ChatMsg msgType, Language language, float textRange, WorldObject const *target)
virtual void Say (std::string_view text, Language language, WorldObject const *target=nullptr)
virtual void Yell (std::string_view text, Language language, WorldObject const *target=nullptr)
virtual void TextEmote (std::string_view text, WorldObject const *target=nullptr, bool isBossEmote=false)
virtual void Whisper (std::string_view text, Language language, Player *target, bool isBossWhisper=false)
virtual void Talk (uint32 textId, ChatMsg msgType, float textRange, WorldObject const *target)
virtual void Say (uint32 textId, WorldObject const *target=nullptr)
virtual void Yell (uint32 textId, WorldObject const *target=nullptr)
virtual void TextEmote (uint32 textId, WorldObject const *target=nullptr, bool isBossEmote=false)
virtual void Whisper (uint32 textId, Player *target, bool isBossWhisper=false)
ShapeshiftForm GetShapeshiftForm () const
void SetShapeshiftForm (ShapeshiftForm form)
bool IsAttackSpeedOverridenShapeShift () const
bool IsInFeralForm () const
void setTransForm (uint32 spellid)
uint32 getTransForm () const
void DeMorph ()
virtual void RecalculateObjectScale ()
uint32 GetDisplayId () const
uint32 GetNativeDisplayId () const
void RestoreDisplayId ()
void SetNativeDisplayId (uint32 displayId)
uint32 GetModelForForm (ShapeshiftForm form, uint32 spellId)
virtual bool IsInWater () const
virtual bool IsUnderWater () const
void NearTeleportTo (Position &pos, bool casting=false, bool vehicleTeleport=false, bool withPet=false, bool removeTransport=false)
void NearTeleportTo (float x, float y, float z, float orientation, bool casting=false, bool vehicleTeleport=false, bool withPet=false, bool removeTransport=false)
void SetInFront (WorldObject const *target)
void SetFacingTo (float ori)
void SetFacingToObject (WorldObject *object, Milliseconds timed=0ms)
bool isInAccessiblePlaceFor (Creature const *c) const
bool isInFrontInMap (Unit const *target, float distance, float arc=M_PI) const
bool isInBackInMap (Unit const *target, float distance, float arc=M_PI) const
float GetCollisionHeight () const override
Return collision height sent to client.
float GetCollisionWidth () const override
this method gets the diameter of a Unit by DB if any value is defined, otherwise it gets the value by the DBC
float GetCollisionRadius () const override
this method gets the radius of a Unit by DB if any value is defined, otherwise it gets the value by the DBC
void UpdateOrientation (float orientation)
Only server-side orientation update, does not broadcast to client.
void UpdateHeight (float newZ)
Only server-side height update, does not broadcast to client.
virtual bool UpdatePosition (float x, float y, float z, float ang, bool teleport=false)
bool UpdatePosition (const Position &pos, bool teleport=false)
void ProcessPositionDataChanged (PositionFullTerrainStatus const &data) override
virtual void ProcessTerrainStatusUpdate ()
bool IsVisible () const
void SetVisible (bool x)
void SetModelVisible (bool on)
uint32 GetPhaseByAuras () const
void SetPhaseMask (uint32 newPhaseMask, bool update) override
void UpdateObjectVisibility (bool forced=true, bool fromUpdate=false) override
void AddPointedBy (SafeUnitPointer *sup)
void RemovePointedBy (SafeUnitPointer *sup)
void SendAttackStateUpdate (CalcDamageInfo *damageInfo)
void SendAttackStateUpdate (uint32 HitInfo, Unit *target, uint8 SwingType, SpellSchoolMask damageSchoolMask, uint32 Damage, uint32 AbsorbDamage, uint32 Resist, VictimState TargetState, uint32 BlockedAmount)
void SendComboPoints ()
void SendPlaySpellVisual (uint32 id)
void SendPlaySpellImpact (ObjectGuid guid, uint32 id)
void SendPetActionFeedback (uint8 msg) const
-------—Pet responses methods--------------—
void SendPetActionSound (PetAction action) const
void SendPetDismissSound () const
void SendPetAIReaction (ObjectGuid guid) const
void SendPeriodicAuraLog (SpellPeriodicAuraLogInfo *pInfo)
void SendSpellNonMeleeDamageLog (SpellNonMeleeDamage *log)
void SendSpellNonMeleeReflectLog (SpellNonMeleeDamage *log, Unit *attacker)
void SendSpellNonMeleeDamageLog (Unit *target, SpellInfo const *spellInfo, uint32 Damage, SpellSchoolMask damageSchoolMask, uint32 AbsorbedDamage, uint32 Resist, bool PhysicalDamage, uint32 Blocked, bool CriticalHit=false, bool Split=false)
void SendSpellMiss (Unit *target, uint32 spellID, SpellMissInfo missInfo)
void SendSpellDamageResist (Unit *target, uint32 spellId)
void SendSpellDamageImmune (Unit *target, uint32 spellId)
void SendTameFailure (uint8 result)
void SendTeleportPacket (Position &pos)
void SendMovementFlagUpdate (bool self=false)
void SendMovementWaterWalking (Player *sendTo)
void SendMovementFeatherFall (Player *sendTo)
void SendMovementHover (Player *sendTo)
void SendChangeCurrentVictimOpcode (HostileReference *pHostileReference)
void SendClearThreatListOpcode ()
void SendRemoveFromThreatListOpcode (HostileReference *pHostileReference)
void SendThreatListUpdate ()
void SendClearTarget ()
void ExecuteDelayedUnitRelocationEvent ()
void ExecuteDelayedUnitAINotifyEvent ()
void BuildHeartBeatMsg (WorldPacket *data) const
void BuildMovementPacket (ByteBuffer *data) const
void OutDebugInfo () const
std::string GetDebugInfo () const override
Public Member Functions inherited from WorldObject
~WorldObject () override
void _Create (ObjectGuid::LowType guidlow, HighGuid guidhigh, uint32 phaseMask)
void AddToWorld () override
void RemoveFromWorld () override
void GetNearPoint2D (WorldObject const *searcher, float &x, float &y, float distance, float absAngle, Position const *startPos=nullptr) const
void GetNearPoint2D (float &x, float &y, float distance, float absAngle, Position const *startPos=nullptr) const
void GetNearPoint (WorldObject const *searcher, float &x, float &y, float &z, float searcher_size, float distance2d, float absAngle, float controlZ=0, Position const *startPos=nullptr) const
void GetVoidClosePoint (float &x, float &y, float &z, float size, float distance2d=0, float relAngle=0, float controlZ=0) const
bool GetClosePoint (float &x, float &y, float &z, float size, float distance2d=0, float angle=0, WorldObject const *forWho=nullptr, bool force=false) const
void MovePosition (Position &pos, float dist, float angle)
Position GetNearPosition (float dist, float angle)
void MovePositionToFirstCollision (Position &pos, float dist, float angle)
Position GetFirstCollisionPosition (float startX, float startY, float startZ, float destX, float destY)
Position GetFirstCollisionPosition (float destX, float destY, float destZ)
Position GetFirstCollisionPosition (float dist, float angle)
Position GetRandomNearPosition (float radius)
void GetContactPoint (WorldObject const *obj, float &x, float &y, float &z, float distance2d=CONTACT_DISTANCE) const
void GetChargeContactPoint (WorldObject const *obj, float &x, float &y, float &z, float distance2d=CONTACT_DISTANCE) const
float GetObjectSize () const
void UpdateGroundPositionZ (float x, float y, float &z) const
void UpdateAllowedPositionZ (float x, float y, float &z, float *groundZ=nullptr) const
void GetRandomPoint (const Position &srcPos, float distance, float &rand_x, float &rand_y, float &rand_z) const
Position GetRandomPoint (const Position &srcPos, float distance) const
uint32 GetInstanceId () const
uint32 GetPhaseMask () const
bool InSamePhase (WorldObject const *obj) const
bool InSamePhase (uint32 phasemask) const
uint32 GetZoneId () const
uint32 GetAreaId () const
void GetZoneAndAreaId (uint32 &zoneid, uint32 &areaid) const
bool IsOutdoors () const
LiquidData const & GetLiquidData () const
InstanceScript * GetInstanceScript () const
std::string const & GetName () const
void SetName (std::string const &newname)
float GetDistance (WorldObject const *obj) const
float GetDistance (const Position &pos) const
float GetDistance (float x, float y, float z) const
float GetDistance2d (WorldObject const *obj) const
float GetDistance2d (float x, float y) const
float GetDistanceZ (WorldObject const *obj) const
bool IsSelfOrInSameMap (WorldObject const *obj) const
bool IsInMap (WorldObject const *obj) const
bool IsWithinDist3d (float x, float y, float z, float dist) const
bool IsWithinDist3d (const Position *pos, float dist) const
bool IsWithinDist2d (float x, float y, float dist) const
bool IsWithinDist2d (const Position *pos, float dist) const
bool IsWithinDist (WorldObject const *obj, float dist2compare, bool is3D=true, bool incOwnRadius=true, bool incTargetRadius=true) const
bool IsWithinDistInMap (WorldObject const *obj, float dist2compare, bool is3D=true, bool incOwnRadius=true, bool incTargetRadius=true) const
bool IsWithinLOS (float x, float y, float z, VMAP::ModelIgnoreFlags ignoreFlags=VMAP::ModelIgnoreFlags::Nothing, LineOfSightChecks checks=LINEOFSIGHT_ALL_CHECKS) const
bool IsWithinLOSInMap (WorldObject const *obj, VMAP::ModelIgnoreFlags ignoreFlags=VMAP::ModelIgnoreFlags::Nothing, LineOfSightChecks checks=LINEOFSIGHT_ALL_CHECKS, Optional< float > collisionHeight={ }, Optional< float > combatReach={ }) const
Position GetHitSpherePointFor (Position const &dest, Optional< float > collisionHeight={ }, Optional< float > combatReach={ }) const
void GetHitSpherePointFor (Position const &dest, float &x, float &y, float &z, Optional< float > collisionHeight={ }, Optional< float > combatReach={ }) const
bool GetDistanceOrder (WorldObject const *obj1, WorldObject const *obj2, bool is3D=true) const
bool IsInRange (WorldObject const *obj, float minRange, float maxRange, bool is3D=true) const
bool IsInRange2d (float x, float y, float minRange, float maxRange) const
bool IsInRange3d (float x, float y, float z, float minRange, float maxRange) const
bool isInFront (WorldObject const *target, float arc=M_PI) const
bool isInBack (WorldObject const *target, float arc=M_PI) const
bool IsInBetween (WorldObject const *obj1, WorldObject const *obj2, float size=0) const
virtual void SendMessageToSet (WorldPacket const *data, bool self) const
virtual void SendMessageToSetInRange (WorldPacket const *data, float dist, bool self) const
virtual void SendMessageToSet (WorldPacket const *data, Player const *skipped_rcvr) const
void PlayDistanceSound (uint32 sound_id, Player *target=nullptr)
void PlayDirectSound (uint32 sound_id, Player *target=nullptr)
void PlayRadiusSound (uint32 sound_id, float radius)
void PlayDirectMusic (uint32 music_id, Player *target=nullptr)
void PlayRadiusMusic (uint32 music_id, float radius)
template<typename Worker >
void DoForAllVisiblePlayers (Worker &&worker)
template<typename Worker >
void DoForAllVisibleWorldObjects (Worker &&worker)
void DestroyForVisiblePlayers ()
void SendObjectDeSpawnAnim (ObjectGuid guid)
void AddObjectToRemoveList ()
float GetGridActivationRange () const
float GetVisibilityRange () const
virtual float GetSightRange (WorldObject const *target=nullptr) const
bool CanSeeOrDetect (WorldObject const *obj, bool ignoreStealth=false, bool distanceCheck=false, bool checkAlert=false) const
void SendPlayMusic (uint32 Music, bool OnlySelf)
virtual void SetMap (Map *map)
virtual void ResetMap ()
Map * GetMap () const
Map * FindMap () const
void SetZoneScript ()
void ClearZoneScript ()
ZoneScript * GetZoneScript () const
TempSummon * SummonCreature (uint32 id, const Position &pos, TempSummonType spwtype=TEMPSUMMON_MANUAL_DESPAWN, uint32 despwtime=0, uint32 vehId=0, SummonPropertiesEntry const *properties=nullptr, bool visibleBySummonerOnly=false) const
TempSummon * SummonCreature (uint32 id, float x, float y, float z, float ang=0, TempSummonType spwtype=TEMPSUMMON_MANUAL_DESPAWN, uint32 despwtime=0, SummonPropertiesEntry const *properties=nullptr, bool visibleBySummonerOnly=false)
GameObject * SummonGameObject (uint32 entry, float x, float y, float z, float ang, float rotation0, float rotation1, float rotation2, float rotation3, uint32 respawnTime, bool checkTransport=true, GOSummonType summonType=GO_SUMMON_TIMED_OR_CORPSE_DESPAWN)
Creature * SummonTrigger (float x, float y, float z, float ang, uint32 dur, bool setLevel=false, CreatureAI *(*GetAI)(Creature *)=nullptr)
void SummonCreatureGroup (uint8 group, std::list< TempSummon * > *list=nullptr)
Creature * FindNearestCreature (uint32 entry, float range, bool alive=true) const
GameObject * FindNearestGameObject (uint32 entry, float range, bool onlySpawned=false) const
GameObject * FindNearestGameObjectOfType (GameobjectTypes type, float range) const
Player * SelectNearestPlayer (float distance=0) const
void GetGameObjectListWithEntryInGrid (std::list< GameObject * > &lList, uint32 uiEntry, float fMaxSearchRange) const
void GetGameObjectListWithEntryInGrid (std::list< GameObject * > &gameobjectList, std::vector< uint32 > const &entries, float maxSearchRange) const
void GetCreatureListWithEntryInGrid (std::list< Creature * > &lList, uint32 uiEntry, float fMaxSearchRange) const
void GetCreatureListWithEntryInGrid (std::list< Creature * > &creatureList, std::vector< uint32 > const &entries, float maxSearchRange) const
void GetDeadCreatureListInGrid (std::list< Creature * > &lList, float maxSearchRange, bool alive=false) const
void BuildUpdate (UpdateDataMapType &data_map) override
void GetCreaturesWithEntryInRange (std::list< Creature * > &creatureList, float radius, uint32 entry)
void SetPositionDataUpdate ()
void UpdatePositionData ()
void AddToObjectUpdate () override
void RemoveFromObjectUpdate () override
void AddToNotify (uint16 f)
void RemoveFromNotify (uint16 f)
bool isNeedNotify (uint16 f) const
uint16 GetNotifyFlags () const
bool NotifyExecuted (uint16 f) const
void SetNotified (uint16 f)
void ResetAllNotifies ()
bool isActiveObject () const
void setActive (bool isActiveObject)
VisibilityDistanceType GetVisibilityOverrideType () const
bool IsVisibilityOverridden () const
bool IsZoneWideVisible () const
bool IsFarVisible () const
float GetVisibilityOverrideDistance () const
void SetVisibilityDistanceOverride (VisibilityDistanceType type)
bool IsInWintergrasp () const
Transport * GetTransport () const
float GetTransOffsetX () const
float GetTransOffsetY () const
float GetTransOffsetZ () const
float GetTransOffsetO () const
uint32 GetTransTime () const
int8 GetTransSeat () const
void SetTransport (Transport *t)
virtual float GetStationaryX () const
virtual float GetStationaryY () const
virtual float GetStationaryZ () const
virtual float GetStationaryO () const
float GetMapWaterOrGroundLevel (Position pos, float *ground=nullptr) const
float GetMapWaterOrGroundLevel (float x, float y, float z, float *ground=nullptr) const
float GetMapHeight (float x, float y, float z, bool vmap=true, float distanceToSearch=50.0f) const
float GetFloorZ () const
float GetMinHeightInWater () const
Get the minimum height of a object that should be in water to start floating/swim.
void AddAllowedLooter (ObjectGuid guid)
void ResetAllowedLooters ()
void SetAllowedLooters (GuidUnorderedSet const looters)
bool HasAllowedLooter (ObjectGuid guid) const
GuidUnorderedSet const & GetAllowedLooters () const
void RemoveAllowedLooter (ObjectGuid guid)
bool CanBeAddedToMapUpdateList ()
std::string GetDebugInfo () const override
ObjectVisibilityContainer & GetObjectVisibilityContainer ()
ObjectVisibilityContainer const & GetObjectVisibilityContainer () const
Public Member Functions inherited from Object
virtual ~Object ()
bool IsInWorld () const
ObjectGuid GetGUID () const
PackedGuid const & GetPackGUID () const
uint32 GetEntry () const
void SetEntry (uint32 entry)
float GetObjectScale () const
bool HasDynamicFlag (uint32 flag) const
virtual void SetDynamicFlag (uint32 flag)
virtual void RemoveDynamicFlag (uint32 flag)
TypeID GetTypeId () const
bool isType (uint16 mask) const
virtual void BuildCreateUpdateBlockForPlayer (UpdateData *data, Player *target)
void SendUpdateToPlayer (Player *player)
void BuildValuesUpdateBlockForPlayer (UpdateData *data, Player *target)
void BuildOutOfRangeUpdateBlock (UpdateData *data) const
void BuildMovementUpdateBlock (UpdateData *data, uint32 flags=0) const
virtual void DestroyForPlayer (Player *target, bool onDeath=false) const
int32 GetInt32Value (uint16 index) const
uint32 GetUInt32Value (uint16 index) const
uint64 GetUInt64Value (uint16 index) const
float GetFloatValue (uint16 index) const
uint8 GetByteValue (uint16 index, uint8 offset) const
uint16 GetUInt16Value (uint16 index, uint8 offset) const
ObjectGuid GetGuidValue (uint16 index) const
void SetInt32Value (uint16 index, int32 value)
void SetUInt32Value (uint16 index, uint32 value)
void UpdateUInt32Value (uint16 index, uint32 value)
void SetUInt64Value (uint16 index, uint64 value)
void SetFloatValue (uint16 index, float value)
void SetByteValue (uint16 index, uint8 offset, uint8 value)
void SetUInt16Value (uint16 index, uint8 offset, uint16 value)
void SetInt16Value (uint16 index, uint8 offset, int16 value)
void SetGuidValue (uint16 index, ObjectGuid value)
void SetStatFloatValue (uint16 index, float value)
void SetStatInt32Value (uint16 index, int32 value)
bool AddGuidValue (uint16 index, ObjectGuid value)
bool RemoveGuidValue (uint16 index, ObjectGuid value)
void ApplyModUInt32Value (uint16 index, int32 val, bool apply)
void ApplyModInt32Value (uint16 index, int32 val, bool apply)
void ApplyModUInt64Value (uint16 index, int32 val, bool apply)
void ApplyModPositiveFloatValue (uint16 index, float val, bool apply)
void ApplyModSignedFloatValue (uint16 index, float val, bool apply)
void SetFlag (uint16 index, uint32 newFlag)
void RemoveFlag (uint16 index, uint32 oldFlag)
void ToggleFlag (uint16 index, uint32 flag)
bool HasFlag (uint16 index, uint32 flag) const
void ApplyModFlag (uint16 index, uint32 flag, bool apply)
void SetByteFlag (uint16 index, uint8 offset, uint8 newFlag)
void RemoveByteFlag (uint16 index, uint8 offset, uint8 newFlag)
bool HasByteFlag (uint16 index, uint8 offset, uint8 flag) const
void SetFlag64 (uint16 index, uint64 newFlag)
void RemoveFlag64 (uint16 index, uint64 oldFlag)
void ToggleFlag64 (uint16 index, uint64 flag)
bool HasFlag64 (uint16 index, uint64 flag) const
void ApplyModFlag64 (uint16 index, uint64 flag, bool apply)
void ClearUpdateMask (bool remove)
uint16 GetValuesCount () const
void BuildFieldsUpdate (Player *, UpdateDataMapType &)
void SetFieldNotifyFlag (uint16 flag)
void RemoveFieldNotifyFlag (uint16 flag)
void ForceValuesUpdateAtIndex (uint32)
bool IsPlayer () const
Player * ToPlayer ()
Player const * ToPlayer () const
bool IsCreature () const
Creature * ToCreature ()
Creature const * ToCreature () const
bool IsUnit () const
Unit * ToUnit ()
Unit const * ToUnit () const
bool IsGameObject () const
GameObject * ToGameObject ()
GameObject const * ToGameObject () const
bool IsCorpse () const
Corpse * ToCorpse ()
Corpse const * ToCorpse () const
bool IsDynamicObject () const
DynamicObject * ToDynObject ()
DynamicObject const * ToDynObject () const
bool IsItem () const
virtual void Heartbeat ()
template<typename... T>
bool EntryEquals (T... entries) const
Public Member Functions inherited from WorldLocation
WorldLocation (uint32 _mapId=MAPID_INVALID, float x=0.f, float y=0.f, float z=0.f, float o=0.f)
WorldLocation (uint32 mapId, Position const &position)
void WorldRelocate (const WorldLocation &loc)
void WorldRelocate (uint32 mapId=MAPID_INVALID, float x=0.f, float y=0.f, float z=0.f, float o=0.f)
void SetMapId (uint32 mapId)
uint32 GetMapId () const
void GetWorldLocation (uint32 &mapId, float &x, float &y) const
void GetWorldLocation (uint32 &mapId, float &x, float &y, float &z) const
void GetWorldLocation (uint32 &mapId, float &x, float &y, float &z, float &o) const
void GetWorldLocation (WorldLocation *location) const
WorldLocation GetWorldLocation () const
std::string GetDebugInfo () const
Public Member Functions inherited from Position
Position (float x=0, float y=0, float z=0, float o=0)
Position (Position const &loc)
Position (Position &&)=default
Position & operator= (const Position &)=default
Position & operator= (Position &&)=default
bool operator== (Position const &a) const
bool operator!= (Position const &a)
bool operator!= (Position const &a) const
operator G3D::Vector3 () const
void Relocate (float x, float y)
void Relocate (float x, float y, float z)
void Relocate (float x, float y, float z, float orientation)
void Relocate (const Position &pos)
void Relocate (const Position *pos)
void RelocatePolarOffset (float angle, float dist, float z=0.0f)
void RelocateOffset (const Position &offset)
void SetOrientation (float orientation)
float GetPositionX () const
float GetPositionY () const
float GetPositionZ () const
float GetOrientation () const
void GetPosition (float &x, float &y) const
void GetPosition (float &x, float &y, float &z) const
void GetPosition (float &x, float &y, float &z, float &o) const
Position GetPosition () const
Position::PositionXYZStreamer PositionXYZStream ()
Position::PositionXYZOStreamer PositionXYZOStream ()
bool IsPositionValid () const
float GetExactDist2dSq (const float x, const float y) const
float GetExactDist2dSq (Position const &pos) const
float GetExactDist2dSq (Position const *pos) const
float GetExactDist2d (const float x, const float y) const
float GetExactDist2d (Position const &pos) const
float GetExactDist2d (Position const *pos) const
float GetExactDistSq (float x, float y, float z) const
float GetExactDistSq (Position const &pos) const
float GetExactDistSq (Position const *pos) const
float GetExactDist (float x, float y, float z) const
float GetExactDist (Position const &pos) const
float GetExactDist (Position const *pos) const
void GetPositionOffsetTo (const Position &endPos, Position &retOffset) const
Position GetPositionWithOffset (Position const &offset) const
float GetAngle (const Position *pos) const
float GetAngle (float x, float y) const
float GetAbsoluteAngle (float x, float y) const
float GetAbsoluteAngle (Position const &pos) const
float GetAbsoluteAngle (Position const *pos) const
float GetRelativeAngle (const Position *pos) const
float GetRelativeAngle (float x, float y) const
float ToAbsoluteAngle (float relAngle) const
void GetSinCos (float x, float y, float &vsin, float &vcos) const
bool IsInDist2d (float x, float y, float dist) const
bool IsInDist2d (const Position *pos, float dist) const
bool IsInDist (float x, float y, float z, float dist) const
bool IsInDist (const Position *pos, float dist) const
bool IsWithinBox (const Position &center, float xradius, float yradius, float zradius) const
bool HasInArc (float arcangle, const Position *pos, float targetRadius=0.0f) const
bool HasInLine (Position const *pos, float width) const
bool HasInLine (Position const *pos, float objSize, float width) const
std::string ToString () const
Public Member Functions inherited from GridObject< Creature >
bool IsInGrid () const
void AddToGrid (GridRefMgr< Creature > &m)
void RemoveFromGrid ()
Protected Attributes
TotemType m_type
uint32 m_duration
Protected Attributes inherited from Minion
const ObjectGuid m_owner
float m_followAngle
Protected Attributes inherited from Creature
VendorItemCounts m_vendorItemCounts
ObjectGuid m_lootRecipient
ObjectGuid::LowType m_lootRecipientGroup
time_t m_corpseRemoveTime
Timers.
time_t m_respawnTime
time_t m_respawnedTime
uint32 m_respawnDelay
uint32 m_corpseDelay
float m_wanderDistance
uint32 m_boundaryCheckTime
uint16 m_transportCheckTimer
uint32 lootPickPocketRestoreTime
uint32 m_combatPulseTime
uint32 m_combatPulseDelay
ReactStates m_reactState
MovementGeneratorType m_defaultMovementType
ObjectGuid::LowType m_spawnId
For new or temporary creatures is 0 for saved it is lowguid.
uint8 m_equipmentId
int8 m_originalEquipmentId
bool m_alreadyCallForHelp
bool m_AlreadyCallAssistance
bool m_AlreadySearchedAssistance
bool m_regenHealth
bool m_regenPower
bool m_AI_locked
SpellSchoolMask m_meleeDamageSchoolMask
uint32 m_originalEntry
bool m_moveInLineOfSightDisabled
bool m_moveInLineOfSightStrictlyDisabled
Position m_homePosition
Position m_transportHomePosition
bool DisableReputationReward
bool DisableLootReward
CreatureTemplate const * m_creatureInfo
CreatureData const * m_creatureData
float m_detectionDistance
uint16 m_LootMode
float _sparringPct
Protected Attributes inherited from Unit
UnitAI * i_AI
UnitAI * i_disabledAI
uint8 m_realRace
uint8 m_race
bool m_AutoRepeatFirstCast
int32 m_attackTimer [MAX_ATTACK]
float m_createStats [MAX_STATS]
AttackerSet m_attackers
Unit * m_attacking
DeathState m_deathState
int32 m_procDeep
DynObjectList m_dynObj
GameObjectList m_gameObj
uint32 m_transform
Spell * m_currentSpells [CURRENT_MAX_SPELL]
AuraMap m_ownedAuras
AuraApplicationMap m_appliedAuras
AuraList m_removedAuras
AuraMap::iterator m_auraUpdateIterator
uint32 m_removedAurasCount
AuraEffectList m_modAuras [TOTAL_AURAS]
AuraList m_scAuras
AuraApplicationList m_interruptableAuras
AuraStateAurasMap m_auraStateAuras
uint32 m_interruptMask
float m_auraFlatModifiersGroup [UNIT_MOD_END][MODIFIER_TYPE_FLAT_END]
float m_auraPctModifiersGroup [UNIT_MOD_END][MODIFIER_TYPE_PCT_END]
float m_weaponDamage [MAX_ATTACK][MAX_WEAPON_DAMAGE_RANGE][MAX_ITEM_PROTO_DAMAGES]
bool m_canModifyStats
VisibleAuraMap m_visibleAuras
float m_speed_rate [MAX_MOVE_TYPE]
CharmInfo * m_charmInfo
SharedVisionList m_sharedVision
MotionMaster * i_motionMaster
uint32 m_reactiveTimer [MAX_REACTIVE]
int32 m_regenTimer
ThreatMgr m_ThreatMgr
CharmThreatMap _charmThreatInfo
Vehicle * m_vehicle
Vehicle * m_vehicleKit
uint32 m_unitTypeMask
LiquidTypeEntry const * _lastLiquid
bool m_applyResilience
bool _instantCast
Protected Attributes inherited from WorldObject
std::string m_name
bool m_isActive
VisibilityDistanceType _visibilityDistanceOverrideType
ZoneScript * m_zoneScript
uint32 _zoneId
uint32 _areaId
float _floorZ
bool _outdoors
LiquidData _liquidData
bool _updatePositionData
Transport * m_transport
Protected Attributes inherited from Object
uint16 m_objectType
TypeID m_objectTypeId
uint16 m_updateFlag
union {
int32 * m_int32Values
uint32 * m_uint32Values
float * m_floatValues
};
UpdateMask _changesMask
uint16 m_valuesCount
uint16 _fieldNotifyFlags
bool m_objectUpdated
Additional Inherited Members
Public Types inherited from Unit
typedef std::unordered_set< Unit * > AttackerSet
typedef std::set< Unit * > ControlSet
typedef std::multimap< uint32, Aura * > AuraMap
typedef std::pair< AuraMap::const_iterator, AuraMap::const_iterator > AuraMapBounds
typedef std::pair< AuraMap::iterator, AuraMap::iterator > AuraMapBoundsNonConst
typedef std::multimap< uint32, AuraApplication * > AuraApplicationMap
typedef std::pair< AuraApplicationMap::const_iterator, AuraApplicationMap::const_iterator > AuraApplicationMapBounds
typedef std::pair< AuraApplicationMap::iterator, AuraApplicationMap::iterator > AuraApplicationMapBoundsNonConst
typedef std::multimap< AuraStateType, AuraApplication * > AuraStateAurasMap
typedef std::pair< AuraStateAurasMap::const_iterator, AuraStateAurasMap::const_iterator > AuraStateAurasMapBounds
typedef std::vector< AuraEffect * > AuraEffectList
typedef std::list< Aura * > AuraList
typedef std::list< AuraApplication * > AuraApplicationList
typedef std::list< DiminishingReturn > Diminishing
typedef GuidUnorderedSet ComboPointHolderSet
typedef std::map< uint8, AuraApplication * > VisibleAuraMap
typedef std::set< PetAura const * > PetAuraSet
Public Types inherited from UpdatableMapObject
enum UpdateState : uint8 {
NotUpdating ,
PendingAdd ,
Updating
}
Static Public Member Functions inherited from Creature
static float _GetDamageMod (int32 Rank)
Static Public Member Functions inherited from Unit
static void ApplyResilience (Unit const *victim, float *crit, int32 *damage, bool isCrit, CombatRating type)
static float GetEffectiveResistChance (Unit const *owner, SpellSchoolMask schoolMask, Unit const *victim)
static uint32 DealDamage (Unit *attacker, Unit *victim, uint32 damage, CleanDamage const *cleanDamage=nullptr, DamageEffectType damagetype=DIRECT_DAMAGE, SpellSchoolMask damageSchoolMask=SPELL_SCHOOL_MASK_NORMAL, SpellInfo const *spellProto=nullptr, bool durabilityLoss=true, bool allowGM=false, Spell const *spell=nullptr)
static void DealDamageMods (Unit const *victim, uint32 &damage, uint32 *absorb)
static void Kill (Unit *killer, Unit *victim, bool durabilityLoss=true, WeaponAttackType attackType=BASE_ATTACK, SpellInfo const *spellProto=nullptr, Spell const *spell=nullptr)
static bool IsDamageReducedByArmor (SpellSchoolMask damageSchoolMask, SpellInfo const *spellInfo=nullptr, uint8 effIndex=MAX_SPELL_EFFECTS)
static uint32 CalcArmorReducedDamage (Unit const *attacker, Unit const *victim, const uint32 damage, SpellInfo const *spellInfo, uint8 attackerLevel=0, WeaponAttackType attackType=MAX_ATTACK)
static uint32 SpellCriticalDamageBonus (Unit const *caster, SpellInfo const *spellProto, uint32 damage, Unit const *victim)
static void ProcDamageAndSpell (Unit *actor, Unit *victim, uint32 procAttacker, uint32 procVictim, uint32 procEx, uint32 amount, WeaponAttackType attType=BASE_ATTACK, SpellInfo const *procSpellInfo=nullptr, SpellInfo const *procAura=nullptr, int8 procAuraEffectIndex=-1, Spell const *procSpell=nullptr, DamageInfo *damageInfo=nullptr, HealInfo *healInfo=nullptr, uint32 procPhase=2)
static int32 DealHeal (Unit *healer, Unit *victim, uint32 addhealth)
static uint32 SpellCriticalHealingBonus (Unit const *caster, SpellInfo const *spellProto, uint32 damage, Unit const *victim)
static void CalcAbsorbResist (DamageInfo &dmgInfo, bool Splited=false)
static void CalcHealAbsorb (HealInfo &healInfo)
static void HandleSafeUnitPointersOnDelete (Unit *thisUnit)
Static Public Member Functions inherited from Object
static ObjectGuid GetGUID (Object const *o)
Static Public Member Functions inherited from Position
static float NormalizeOrientation (float o)
Public Attributes inherited from TempSummon
const SummonPropertiesEntry *const m_Properties
Public Attributes inherited from Creature
struct {
::Spell const * Spell = nullptr
uint32 Delay = 0
ObjectGuid Target
float Orientation = 0.0f
} _spellFocusInfo
Loot loot
uint32 m_spells [MAX_CREATURE_SPELLS]
CreatureSpellCooldowns m_CreatureSpellCooldowns
uint32 m_ProhibitSchoolTime [7]
uint32 m_groupLootTimer
uint32 lootingGroupLowGUID
float m_SightDistance
float m_CombatDistance
uint32 m_moveCircleMovementTime = MOVE_CIRCLE_CHECK_INTERVAL
uint32 m_moveBackwardsMovementTime = MOVE_BACKWARDS_CHECK_INTERVAL
uint32 m_extendLeashTime = EXTEND_LEASH_CHECK_INTERVAL
Public Attributes inherited from Unit
uint32 m_extraAttacks
DualWieldMode _dualWieldMode
ControlSet m_Controlled
SafeUnitPointer m_movedByPlayer
ObjectGuid m_SummonSlot [MAX_SUMMON_SLOT]
ObjectGuid m_ObjectSlot [MAX_GAMEOBJECT_SLOT]
float m_modMeleeHitChance
float m_modRangedHitChance
float m_modSpellHitChance
int32 m_baseSpellCritChance
float m_threatModifier [MAX_SPELL_SCHOOL]
float m_modAttackSpeedPct [3]
SpellImmuneList m_spellImmune [MAX_SPELL_IMMUNITY]
uint32 m_lastSanctuaryTime
PetAuraSet m_petAuras
bool IsAIEnabled
bool NeedChangeAI
bool m_ControlledByPlayer
bool m_CreatedByPlayer
std::set< SafeUnitPointer * > SafeUnitPointerSet
Position m_last_notify_position
uint32 m_last_notify_mstime
uint16 m_delayed_unit_relocation_timer
uint16 m_delayed_unit_ai_notify_timer
bool bRequestForcedVisibilityUpdate
Movement::MoveSpline * movespline
Public Attributes inherited from WorldObject
FlaggedValuesArray32< int32, uint32, StealthType, TOTAL_STEALTH_TYPES > m_stealth
FlaggedValuesArray32< int32, uint32, StealthType, TOTAL_STEALTH_TYPES > m_stealthDetect
FlaggedValuesArray32< int32, uint32, InvisibilityType, TOTAL_INVISIBILITY_TYPES > m_invisibility
FlaggedValuesArray32< int32, uint32, InvisibilityType, TOTAL_INVISIBILITY_TYPES > m_invisibilityDetect
FlaggedValuesArray32< int32, uint32, ServerSideVisibilityType, TOTAL_SERVERSIDE_VISIBILITY_TYPES > m_serverSideVisibility
FlaggedValuesArray32< int32, uint32, ServerSideVisibilityType, TOTAL_SERVERSIDE_VISIBILITY_TYPES > m_serverSideVisibilityDetect
uint32 LastUsedScriptID
MovementInfo m_movementInfo
ALEEventProcessor * ALEEvents
EventProcessor m_Events
Public Attributes inherited from Object
DataMap CustomData
Public Attributes inherited from WorldLocation
uint32 m_mapId
Public Attributes inherited from Position
float m_positionX = 0
float m_positionY = 0
float m_positionZ = 0
float m_orientation = 0
Static Public Attributes inherited from Creature
static constexpr uint32 MOVE_CIRCLE_CHECK_INTERVAL = 3000
static constexpr uint32 MOVE_BACKWARDS_CHECK_INTERVAL = 2000
static constexpr uint32 EXTEND_LEASH_CHECK_INTERVAL = 3000
Protected Types inherited from Unit
typedef std::list< DynamicObject * > DynObjectList
typedef GuidList GameObjectList
typedef std::map< ObjectGuid, float > CharmThreatMap
Protected Member Functions inherited from Creature
bool CreateFromProto (ObjectGuid::LowType guidlow, uint32 Entry, uint32 vehId, const CreatureData *data=nullptr)
bool InitEntry (uint32 entry, const CreatureData *data=nullptr)
void RegenerateHealth ()
void Regenerate (Powers power)
bool IsInvisibleDueToDespawn () const override
bool CanAlwaysSee (WorldObject const *obj) const override
bool IsAlwaysDetectableFor (WorldObject const *seer) const override
Protected Member Functions inherited from Unit
Unit ()
void BuildValuesUpdate (uint8 updateType, ByteBuffer *data, Player *target) override
void _UpdateSpells (uint32 time)
void _DeleteRemovedAuras ()
void _UpdateAutoRepeatSpell ()
bool CanSparringWith (Unit const *attacker) const
bool IsAlwaysVisibleFor (WorldObject const *seer) const override
: Check if unit is eligible for sparring damages. Work only if attacker and victim are creatures.
bool IsAlwaysDetectableFor (WorldObject const *seer) const override
void SetFeared (bool apply, Unit *fearedBy=nullptr, bool isFear=false)
void SetConfused (bool apply)
void SetStunned (bool apply)
void SetRooted (bool apply, bool stun=false, bool logout=false)
void SendMoveRoot (bool state)
Protected Member Functions inherited from WorldObject
WorldObject ()
void SetLocationMapId (uint32 _mapId)
void SetLocationInstanceId (uint32 _instanceId)
virtual bool IsNeverVisible () const
Protected Member Functions inherited from Object
Object ()
void _InitValues ()
void _Create (ObjectGuid::LowType guidlow, uint32 entry, HighGuid guidhigh)
std::string _ConcatFields (uint16 startIndex, uint16 size) const
bool _LoadIntoDataField (std::string const &data, uint32 startOffset, uint32 count)
uint32 GetUpdateFieldData (Player const *target, uint32 *&flags) const
void BuildMovementUpdate (ByteBuffer *data, uint16 flags) const
void AddToObjectUpdateIfNeeded ()
Protected Member Functions inherited from MovableMapObject
MovableMapObject ()=default
Cell const & GetCurrentCell () const
Protected Member Functions inherited from UpdatableMapObject
UpdatableMapObject ()
Static Protected Member Functions inherited from Creature
static float _GetHealthMod (int32 Rank)
Detailed Description
Constructor & Destructor Documentation
Totem()
Totem::Totem (SummonPropertiesEntry const * properties, ObjectGuid owner) explicit
                                                                      : Minion(properties, owner)
{
    m_unitTypeMask |= UNIT_MASK_TOTEM;
    m_duration = 0;
    m_type = TOTEM_PASSIVE;
}
References m_duration, m_type, Unit::m_unitTypeMask, TOTEM_PASSIVE, and UNIT_MASK_TOTEM.
~Totem()
Totem::~Totem () inline override
{};
Member Function Documentation
GetSpell()
uint32 Totem::GetSpell (uint8 slot = 0) const inline
{ return m_spells[slot]; }
References Creature::m_spells.
Referenced by InitStats(), InitSummon(), Unit::SetMinion(), UnSummon(), and TotemAI::UpdateAI().
GetTotemDuration()
uint32 Totem::GetTotemDuration () const inline
{ return m_duration; }
References m_duration.
GetTotemType()
TotemType Totem::GetTotemType () const inline
{ return m_type; }
References m_type.
Referenced by TotemAI::UpdateAI().
InitStats()
void Totem::InitStats (uint32 duration) override virtual
Reimplemented from Minion.
{
    // client requires SMSG_TOTEM_CREATED to be sent before adding to world and before removing old totem
    // Xinef: Set level for Unit totems
    if (Unit* owner = ObjectAccessor::GetUnit(*this, m_owner))
    {
        uint32 slot = m_Properties->Slot;
        if (owner->IsPlayer() && slot >= SUMMON_SLOT_TOTEM_FIRE && slot < MAX_TOTEM_SLOT)
        {
            WorldPackets::Totem::TotemCreated data;
            data.Totem = GetGUID();
            data.Slot = slot - SUMMON_SLOT_TOTEM_FIRE;
            data.Duration = duration;
            data.SpellID = GetUInt32Value(UNIT_CREATED_BY_SPELL);
            owner->ToPlayer()->SendDirectMessage(data.Write());
            // set display id depending on caster's race
            SetDisplayId(sObjectMgr->GetModelForTotem(SummonSlot(slot), Races(owner->getRace())));
        }
        SetLevel(owner->GetLevel());
    }
    Minion::InitStats(duration);
    // Get spell cast by totem
    if (SpellInfo const* totemSpell = sSpellMgr->GetSpellInfo(GetSpell()))
        if (totemSpell->CalcCastTime())   // If spell has cast time -> its an active totem
            m_type = TOTEM_ACTIVE;
    m_duration = duration;
}
References WorldPackets::Totem::TotemCreated::Duration, Object::GetGUID(), GetSpell(), Object::GetUInt32Value(), ObjectAccessor::GetUnit(), Minion::InitStats(), m_duration, Minion::m_owner, TempSummon::m_Properties, m_type, MAX_TOTEM_SLOT, Creature::SetDisplayId(), Unit::SetLevel(), WorldPackets::Totem::TotemCreated::Slot, SummonPropertiesEntry::Slot, sObjectMgr, WorldPackets::Totem::TotemCreated::SpellID, sSpellMgr, SUMMON_SLOT_TOTEM_FIRE, WorldPackets::Totem::TotemCreated::Totem, TOTEM_ACTIVE, UNIT_CREATED_BY_SPELL, and WorldPackets::Totem::TotemCreated::Write().
InitSummon()
void Totem::InitSummon () override virtual
Reimplemented from TempSummon.
{
    Minion::InitSummon();
    if (m_type == TOTEM_PASSIVE && GetSpell())
    {
        if (TotemSpellIds(GetUInt32Value(UNIT_CREATED_BY_SPELL)) == TotemSpellIds::FireTotemSpell)
        {
            m_Events.AddEventAtOffset([this]()
            {
                CastSpell(this, GetSpell(), true);
            }, 4s);
        }
        else
        {
            CastSpell(this, GetSpell(), true);
        }
    }
    // Some totems can have both instant effect and passive spell
    if (GetSpell(1))
    {
        CastSpell(this, GetSpell(1), true);
    }
    // xinef: this is better than the script, 100% sure to work
    if (GetEntry() == SENTRY_TOTEM_ENTRY)
    {
        SetReactState(REACT_AGGRESSIVE);
        GetOwner()->CastSpell(this, 6277, true);
        // Farsight objects should be active
        setActive(true);
        SetVisibilityDistanceOverride(VisibilityDistanceType::Infinite);
    }
    if (!IsInWater())
    {
        GetMotionMaster()->MoveFall();
    }
}
References EventProcessor::AddEventAtOffset(), Unit::CastSpell(), FireTotemSpell, Object::GetEntry(), Unit::GetMotionMaster(), Minion::GetOwner(), GetSpell(), Object::GetUInt32Value(), Infinite, TempSummon::InitSummon(), Unit::IsInWater(), WorldObject::m_Events, m_type, MotionMaster::MoveFall(), REACT_AGGRESSIVE, SENTRY_TOTEM_ENTRY, WorldObject::setActive(), Creature::SetReactState(), WorldObject::SetVisibilityDistanceOverride(), TOTEM_PASSIVE, and UNIT_CREATED_BY_SPELL.
IsImmunedToSpellEffect()
bool Totem::IsImmunedToSpellEffect (SpellInfo const * spellInfo, uint32 index) const override virtual
Reimplemented from Creature.
{
    // xinef: immune to all positive spells, except of stoneclaw totem absorb, sentry totem bind sight and intervene
    // totems positive spells have unit_caster target
    if (spellInfo->Effects[index].Effect != SPELL_EFFECT_DUMMY &&
            spellInfo->Effects[index].Effect != SPELL_EFFECT_SCRIPT_EFFECT &&
            spellInfo->IsPositive() && spellInfo->Effects[index].TargetA.GetTarget() != TARGET_UNIT_CASTER &&
            spellInfo->Effects[index].TargetA.GetCheckType() != TARGET_CHECK_ENTRY &&
            spellInfo->Id != SPELL_STONECLAW && spellInfo->Id != SPELL_BIND_SIGHT && spellInfo->Id != SPELL_INTERVENE)
        return true;
    // Cyclone shouldn't be casted on totems
    if (spellInfo->Id == SPELL_CYCLONE)
    {
        return true;
    }
    switch (spellInfo->Effects[index].ApplyAuraName)
    {
        // i think its wrong (xinef)
        //case SPELL_AURA_PERIODIC_LEECH:
        case SPELL_AURA_PERIODIC_DAMAGE:
        case SPELL_AURA_PERIODIC_DAMAGE_PERCENT:
        case SPELL_AURA_MOD_FEAR:
        case SPELL_AURA_TRANSFORM:
            return true;
        default:
            break;
    }
    return Creature::IsImmunedToSpellEffect(spellInfo, index);
}
References SpellInfo::Effects, SpellInfo::Id, Creature::IsImmunedToSpellEffect(), SpellInfo::IsPositive(), SPELL_AURA_MOD_FEAR, SPELL_AURA_PERIODIC_DAMAGE, SPELL_AURA_PERIODIC_DAMAGE_PERCENT, SPELL_AURA_TRANSFORM, SPELL_BIND_SIGHT, SPELL_CYCLONE, SPELL_EFFECT_DUMMY, SPELL_EFFECT_SCRIPT_EFFECT, SPELL_INTERVENE, SPELL_STONECLAW, TARGET_CHECK_ENTRY, and TARGET_UNIT_CASTER.
SetTotemDuration()
void Totem::SetTotemDuration (uint32 duration) inline
{ m_duration = duration; }
References m_duration.
UnSummon()
void Totem::UnSummon (Milliseconds msTime = 0ms) override virtual
Reimplemented from TempSummon.
{
    if (msTime > 0ms)
    {
        m_Events.AddEventAtOffset(new ForcedUnsummonDelayEvent(*this), msTime);
        return;
    }
    CombatStop();
    RemoveAurasDueToSpell(GetSpell(), GetGUID());
    if (Unit* owner = GetOwner())
    {
        // clear owner's totem slot
        for (uint8 i = SUMMON_SLOT_TOTEM_FIRE; i < MAX_TOTEM_SLOT; ++i)
        {
            if (owner->m_SummonSlot[i] == GetGUID())
            {
                owner->m_SummonSlot[i].Clear();
                break;
            }
        }
        owner->RemoveAurasDueToSpell(GetSpell(), GetGUID());
        // Remove Sentry Totem Aura
        if (GetEntry() == SENTRY_TOTEM_ENTRY)
            owner->RemoveAurasDueToSpell(static_cast<uint32>(TotemSpellIds::SentryTotemSpell));
        //remove aura all party members too
        if (Player* player = owner->ToPlayer())
        {
            player->SendAutoRepeatCancel(this);
            if (SpellInfo const* spell = sSpellMgr->GetSpellInfo(GetUInt32Value(UNIT_CREATED_BY_SPELL)))
                player->SendCooldownEvent(spell, 0, nullptr, false);
            if (Group* group = player->GetGroup())
            {
                for (GroupReference* itr = group->GetFirstMember(); itr != nullptr; itr = itr->next())
                {
                    Player* target = itr->GetSource();
                    if (target && target->IsInMap(player) && group->SameSubGroup(player, target))
                        target->RemoveAurasDueToSpell(GetSpell(), GetGUID());
                }
            }
        }
    }
    AddObjectToRemoveList();
}
References EventProcessor::AddEventAtOffset(), WorldObject::AddObjectToRemoveList(), Unit::CombatStop(), Object::GetEntry(), Object::GetGUID(), Minion::GetOwner(), GetSpell(), Object::GetUInt32Value(), WorldObject::IsInMap(), WorldObject::m_Events, MAX_TOTEM_SLOT, Unit::RemoveAurasDueToSpell(), SENTRY_TOTEM_ENTRY, SentryTotemSpell, sSpellMgr, SUMMON_SLOT_TOTEM_FIRE, Object::ToPlayer(), and UNIT_CREATED_BY_SPELL.
Referenced by Spell::EffectDestroyAllTotems(), WorldSession::HandleTotemDestroyed(), and Update().
Update()
void Totem::Update (uint32 time) override virtual
Reimplemented from TempSummon.
{
    Unit* owner = GetOwner();
    if (!owner || !owner->IsAlive() || !IsAlive() || m_duration <= time)
    {
        UnSummon();                                         // remove self
        return;
    }
    m_duration -= time;
    Creature::Update(time);
}
References Minion::GetOwner(), Unit::IsAlive(), m_duration, UnSummon(), and Creature::Update().
UpdateAllStats()
bool Totem::UpdateAllStats () inline override virtual
Reimplemented from Creature.
{ return true; }
UpdateArmor()
void Totem::UpdateArmor () inline override virtual
Reimplemented from Creature.
{}
UpdateAttackPowerAndDamage()
void Totem::UpdateAttackPowerAndDamage (bool) inline override virtual
Reimplemented from Creature.
{}
UpdateDamagePhysical()
void Totem::UpdateDamagePhysical (WeaponAttackType) inline override virtual
Reimplemented from Unit.
{}
UpdateMaxHealth()
void Totem::UpdateMaxHealth () inline override virtual
Reimplemented from Creature.
{}
UpdateMaxPower()
void Totem::UpdateMaxPower (Powers) inline override virtual
Reimplemented from Creature.
{}
UpdateResistances()
void Totem::UpdateResistances (uint32) inline override virtual
Reimplemented from Creature.
{}
UpdateStats()
bool Totem::UpdateStats (Stats) inline override virtual
Reimplemented from Creature.
{ return true; }
Member Data Documentation
m_duration
uint32 Totem::m_duration protected
Referenced by GetTotemDuration(), InitStats(), SetTotemDuration(), Totem(), and Update().
m_type
TotemType Totem::m_type protected
Referenced by GetTotemType(), InitStats(), InitSummon(), and Totem().
The documentation for this class was generated from the following files:
azerothcore-wotlk/src/server/game/Entities/Totem/Totem.h
azerothcore-wotlk/src/server/game/Entities/Totem/Totem.cpp