AzerothCore Doxygen
go_midsummer_music::go_midsummer_musicAI Struct Reference
Public Member Functions
go_midsummer_musicAI (GameObject *go)
void UpdateAI (uint32 diff) override
Public Member Functions inherited from GameObjectAI
GameObjectAI (GameObject *go)
virtual ~GameObjectAI ()
virtual void InitializeAI ()
virtual void Reset ()
virtual void DoAction (int32)
virtual void SetGUID (ObjectGuid, int32)
virtual ObjectGuid GetGUID (int32) const
virtual bool GossipHello (Player *, bool)
virtual bool GossipSelect (Player *, uint32, uint32)
virtual bool GossipSelectCode (Player *, uint32, uint32, char const *)
virtual bool QuestAccept (Player *, Quest const *)
virtual bool QuestReward (Player *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *)
virtual void Destroyed (Player *, uint32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void OnGameEvent (bool, uint16)
virtual void OnStateChanged (uint32, Unit *)
virtual void EventInform (uint32)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual bool CanBeSeen (Player const *)
virtual void JustSummoned (Creature *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureEvade (Creature *)
Private Attributes
EventMap _events
Additional Inherited Members
Static Public Member Functions inherited from GameObjectAI
static int32 Permissible (GameObject const *go)
Protected Attributes inherited from GameObjectAI
GameObject *const me
Detailed Description
Constructor & Destructor Documentation
go_midsummer_musicAI()
go_midsummer_music::go_midsummer_musicAI::go_midsummer_musicAI (GameObject * go) inline
                                             : GameObjectAI(go)
        {
            _events.ScheduleEvent(EVENT_MM_START_MUSIC, 1000);
        }
References _events, EVENT_MM_START_MUSIC, and EventMap::ScheduleEvent().
Member Function Documentation
UpdateAI()
void go_midsummer_music::go_midsummer_musicAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from GameObjectAI.
        {
            _events.Update(diff);
            while (uint32 eventId = _events.ExecuteEvent())
            {
                switch (eventId)
                {
                    case EVENT_MM_START_MUSIC:
{
                            if (!IsHolidayActive(HOLIDAY_FIRE_FESTIVAL))
                                break;
                            std::list<Player*> targets;
                            Acore::AnyPlayerInObjectRangeCheck check(me, me->GetVisibilityRange(), false);
                            Acore::PlayerListSearcherWithSharedVision<Acore::AnyPlayerInObjectRangeCheck> searcher(me, targets, check);
                            Cell::VisitObjects(me, searcher, me->GetVisibilityRange());
                            for (Player* player : targets)
{
                                if (player->GetTeamId() == TEAM_HORDE)
{
                                    me->PlayDirectMusic(EVENTMIDSUMMERFIREFESTIVAL_H, player);
                                }
                                else
{
                                    me->PlayDirectMusic(EVENTMIDSUMMERFIREFESTIVAL_A, player);
                                }
                            }
                            _events.ScheduleEvent(EVENT_MM_START_MUSIC, 5000); // Every 5 second's SMSG_PLAY_MUSIC packet (PlayDirectMusic) is pushed to the client (sniffed value)
                            break;
                        }
                    default:
                        break;
                }
            }
        }
References _events, EVENT_MM_START_MUSIC, EVENTMIDSUMMERFIREFESTIVAL_A, EVENTMIDSUMMERFIREFESTIVAL_H, EventMap::ExecuteEvent(), WorldObject::GetVisibilityRange(), HOLIDAY_FIRE_FESTIVAL, IsHolidayActive(), GameObjectAI::me, WorldObject::PlayDirectMusic(), EventMap::ScheduleEvent(), TEAM_HORDE, EventMap::Update(), and Cell::VisitObjects().
Member Data Documentation
_events
EventMap go_midsummer_music::go_midsummer_musicAI::_events private
Referenced by go_midsummer_musicAI(), and UpdateAI().
The documentation for this struct was generated from the following file:
azerothcore-wotlk/src/server/scripts/World/go_scripts.cpp