AzerothCore Doxygen
WaypointMgr Class Reference
#include "WaypointMgr.h"
Public Member Functions
void ReloadPath (uint32 id)
void Load ()
void LoadWaypointAddons ()
WaypointPath const * GetPath (uint32 id) const
Static Public Member Functions
static WaypointMgr * instance ()
Private Member Functions
WaypointMgr ()
Private Attributes
std::unordered_map< uint32, WaypointPath > _waypointStore
Detailed Description
Constructor & Destructor Documentation
WaypointMgr()
WaypointMgr::WaypointMgr () inline private
{ }
Member Function Documentation
GetPath()
WaypointPath const * WaypointMgr::GetPath (uint32 id) const inline
    {
        auto itr = _waypointStore.find(id);
        if (itr != _waypointStore.end())
            return &itr->second;
        return nullptr;
    }
References _waypointStore.
instance()
WaypointMgr * WaypointMgr::instance () static
{
    static WaypointMgr instance;
    return &instance;
}
References instance().
Referenced by instance().
Load()
void WaypointMgr::Load ()
{
    uint32 oldMSTime = getMSTime();
    //                                                0    1         2           3          4            5          6      7      8                 9         10       11
    QueryResult result = WorldDatabase.Query("SELECT id, point, position_x, position_y, position_z, orientation, velocity, delay, smoothTransition, move_type, action, action_chance FROM waypoint_data ORDER BY id, point");
    if (!result)
    {
        LOG_WARN("server.loading", ">> Loaded 0 waypoints. DB table `waypoint_data` is empty!");
        LOG_INFO("server.loading", " ");
        return;
    }
    uint32 count = 0;
    do
    {
        Field* fields = result->Fetch();
        uint32 pathId = fields[0].Get<uint32>();
        float x = fields[2].Get<float>();
        float y = fields[3].Get<float>();
        float z = fields[4].Get<float>();
        std::optional<float> o;
        if (!fields[5].IsNull())
            o = fields[5].Get<float>();
        float velocity = fields[6].Get<float>();
        Acore::NormalizeMapCoord(x);
        Acore::NormalizeMapCoord(y);
        WaypointNode waypoint;
        waypoint.Id = fields[1].Get<uint32>();
        waypoint.X = x;
        waypoint.Y = y;
        waypoint.Z = z;
        if (o.has_value())
            waypoint.Orientation = o;
        waypoint.Velocity = velocity;
        waypoint.Delay = fields[7].Get<uint32>();
        waypoint.SmoothTransition = fields[8].Get<bool>();
        waypoint.MoveType = fields[9].Get<uint32>();
        if (waypoint.MoveType >= WAYPOINT_MOVE_TYPE_MAX)
        {
            LOG_ERROR("sql.sql", "Waypoint {} in waypoint_data has invalid move_type, ignoring", waypoint.Id);
            continue;
        }
        waypoint.EventId = fields[10].Get<uint32>();
        waypoint.EventChance = fields[11].Get<int16>();
        WaypointPath& path = _waypointStore[pathId];
        path.Id = pathId;
        path.Nodes.push_back(std::move(waypoint));
        ++count;
    } while (result->NextRow());
    LOG_INFO("server.loading", ">> Loaded {} waypoints in {} ms", count, GetMSTimeDiffToNow(oldMSTime));
    LOG_INFO("server.loading", " ");
}
References _waypointStore, WaypointNode::Delay, WaypointNode::EventChance, WaypointNode::EventId, Field::Get(), getMSTime(), GetMSTimeDiffToNow(), WaypointNode::Id, WaypointPath::Id, LOG_ERROR, LOG_INFO, LOG_WARN, WaypointNode::MoveType, Acore::NormalizeMapCoord(), WaypointNode::Orientation, WaypointNode::SmoothTransition, WaypointNode::Velocity, WAYPOINT_MOVE_TYPE_MAX, WorldDatabase, WaypointNode::X, WaypointNode::Y, and WaypointNode::Z.
LoadWaypointAddons()
void WaypointMgr::LoadWaypointAddons ()
{
    uint32 oldMSTime = getMSTime();
    //                                               0       1        2                 3          4          5
    QueryResult result = WorldDatabase.Query("SELECT PathID, PointID, SplinePointIndex, PositionX, PositionY, PositionZ FROM waypoint_data_addon ORDER BY PathID, PointID, SplinePointIndex");
    if (!result)
    {
        LOG_INFO("server.loading", ">> Loaded 0 waypoint addon data. DB table `waypoint_data_addon` is empty!");
        LOG_INFO("server.loading", " ");
        return;
    }
    uint32 count = 0;
    do
    {
        Field* fields = result->Fetch();
        uint32 pathId = fields[0].Get<uint32>();
        auto it = _waypointStore.find(pathId);
        if (it == _waypointStore.end())
        {
            LOG_ERROR("sql.sql", "Tried to load waypoint_data_addon data for PathID {} but there is no such path in waypoint_data. Ignoring.", pathId);
            continue;
        }
        WaypointPath& path = it->second;
        uint32 pointId = fields[1].Get<uint32>();
        auto itr = std::find_if(path.Nodes.begin(), path.Nodes.end(), [pointId](WaypointNode const& node)
        {
            return node.Id == pointId;
        });
        if (itr == path.Nodes.end())
        {
            LOG_ERROR("sql.sql", "Tried to load waypoint_data_addon data for PointID {} of PathID {} but there is no such point in waypoint_data. Ignoring.", pointId, pathId);
            continue;
        }
        float x = fields[3].Get<float>();
        float y = fields[4].Get<float>();
        float z = fields[5].Get<float>();
        Acore::NormalizeMapCoord(x);
        Acore::NormalizeMapCoord(y);
        itr->SplinePoints.push_back(G3D::Vector3(x, y, z));
        ++count;
    } while (result->NextRow());
    LOG_INFO("server.loading", ">> Loaded {} waypoint addon data in {} ms", count, GetMSTimeDiffToNow(oldMSTime));
    LOG_INFO("server.loading", " ");
}
References _waypointStore, Field::Get(), getMSTime(), GetMSTimeDiffToNow(), LOG_ERROR, LOG_INFO, WaypointPath::Nodes, Acore::NormalizeMapCoord(), and WorldDatabase.
ReloadPath()
void WaypointMgr::ReloadPath (uint32 id)
{
    auto itr = _waypointStore.find(id);
    if (itr != _waypointStore.end())
        _waypointStore.erase(itr);
    WorldDatabasePreparedStatement* stmt = WorldDatabase.GetPreparedStatement(WORLD_SEL_WAYPOINT_DATA_BY_ID);
    stmt->SetData(0, id);
    PreparedQueryResult result = WorldDatabase.Query(stmt);
    if (!result)
        return;
    std::vector<WaypointNode> values;
    do
    {
        Field* fields = result->Fetch();
        float x = fields[1].Get<float>();
        float y = fields[2].Get<float>();
        float z = fields[3].Get<float>();
        std::optional<float> o;
        if (!fields[4].IsNull())
            o = fields[4].Get<float>();
        float velocity = fields[5].Get<float>();
        Acore::NormalizeMapCoord(x);
        Acore::NormalizeMapCoord(y);
        WaypointNode waypoint;
        waypoint.Id = fields[0].Get<uint32>();
        waypoint.X = x;
        waypoint.Y = y;
        waypoint.Z = z;
        if (o.has_value())
            waypoint.Orientation = o;
        waypoint.Velocity = velocity;
        waypoint.Delay = fields[6].Get<uint32>();
        waypoint.SmoothTransition = fields[7].Get<bool>();
        waypoint.MoveType = fields[8].Get<uint32>();
        if (waypoint.MoveType >= WAYPOINT_MOVE_TYPE_MAX)
        {
            LOG_ERROR("sql.sql", "Waypoint {} in waypoint_data has invalid move_type, ignoring", waypoint.Id);
            continue;
        }
        waypoint.EventId = fields[9].Get<uint32>();
        waypoint.EventChance = fields[10].Get<uint8>();
        values.push_back(std::move(waypoint));
    } while (result->NextRow());
    _waypointStore[id] = WaypointPath(id, std::move(values));
}
References _waypointStore, WaypointNode::Delay, WaypointNode::EventChance, WaypointNode::EventId, Field::Get(), WaypointNode::Id, LOG_ERROR, WaypointNode::MoveType, Acore::NormalizeMapCoord(), WaypointNode::Orientation, PreparedStatementBase::SetData(), WaypointNode::SmoothTransition, WaypointNode::Velocity, WAYPOINT_MOVE_TYPE_MAX, WORLD_SEL_WAYPOINT_DATA_BY_ID, WorldDatabase, WaypointNode::X, WaypointNode::Y, and WaypointNode::Z.
Member Data Documentation
_waypointStore
std::unordered_map<uint32, WaypointPath> WaypointMgr::_waypointStore private
Referenced by GetPath(), Load(), LoadWaypointAddons(), and ReloadPath().
The documentation for this class was generated from the following files:
azerothcore-wotlk/src/server/game/Movement/Waypoints/WaypointMgr.h
azerothcore-wotlk/src/server/game/Movement/Waypoints/WaypointMgr.cpp