AzerothCore Doxygen
WDT_file Class Reference
#include "wdt.h"
Public Member Functions
bool prepareLoadedData () override
WDT_file ()
~WDT_file ()
void free () override
Public Member Functions inherited from FileLoader
uint8 * GetData ()
uint32 GetDataSize ()
FileLoader ()
~FileLoader ()
bool loadFile (std::string const &filename, bool log=true)
uint8 * GetData ()
uint32 GetDataSize ()
FileLoader ()
~FileLoader ()
bool loadFile (std::string const &filename, bool log=true)
Public Attributes
wdt_MPHD * mphd
wdt_MAIN * main
Public Attributes inherited from FileLoader
file_MVER * version
Detailed Description
Constructor & Destructor Documentation
WDT_file()
WDT_file::WDT_file ()
{
    mphd = nullptr;
    main = nullptr;
}
References main, and mphd.
~WDT_file()
WDT_file::~WDT_file ()
{
    free();
}
References free().
Member Function Documentation
free()
void WDT_file::free () override virtual
Reimplemented from FileLoader.
{
    mphd = nullptr;
    main = nullptr;
    FileLoader::free();
}
References FileLoader::free(), main, and mphd.
Referenced by ~WDT_file().
prepareLoadedData()
bool WDT_file::prepareLoadedData () override virtual
Reimplemented from FileLoader.
{
    // Check parent
    if (!FileLoader::prepareLoadedData())
        return false;
    mphd = (wdt_MPHD*)((uint8*)version + version->size + 8);
    if (!mphd->prepareLoadedData())
        return false;
    main = (wdt_MAIN*)((uint8*)mphd + mphd->size + 8);
    if (!main->prepareLoadedData())
        return false;
    return true;
}
References main, mphd, FileLoader::prepareLoadedData(), wdt_MPHD::prepareLoadedData(), wdt_MAIN::prepareLoadedData(), file_MVER::size, wdt_MPHD::size, and FileLoader::version.
Member Data Documentation
main
wdt_MAIN* WDT_file::main
Referenced by ExtractMapsFromMpq(), free(), prepareLoadedData(), and WDT_file().
mphd
wdt_MPHD* WDT_file::mphd
Referenced by free(), prepareLoadedData(), and WDT_file().
The documentation for this class was generated from the following files:
azerothcore-wotlk/src/tools/map_extractor/wdt.h
azerothcore-wotlk/src/tools/map_extractor/wdt.cpp