AzerothCore Doxygen
Random.cpp File Reference
#include "Random.h"
#include "Errors.h"
#include "SFMTRand.h"
#include <memory>
#include <random>
Functions
static SFMTRand * GetRng ()
int32 irand (int32 min, int32 max)
uint32 urand (uint32 min, uint32 max)
uint32 urandms (uint32 min, uint32 max)
float frand (float min, float max)
Milliseconds randtime (Milliseconds min, Milliseconds max)
Seconds randtime (Seconds min, Seconds max)
uint32 rand32 ()
double rand_norm ()
double rand_chance ()
uint32 urandweighted (std::size_t count, double const *chances)
Variables
static thread_local std::unique_ptr< SFMTRand > sfmtRand
static RandomEngine engine
Function Documentation
frand()
float frand (float min, float max)
{
    ASSERT(max >= min);
    std::uniform_real_distribution<float> urd(min, max);
    return urd(engine);
}
References ASSERT, and engine.
Referenced by npc_pos_martin_or_gorkun_second::npc_pos_martin_or_gorkun_secondAI::DoAction(), npc_time_rift::DoSummonAtRift(), Unit::GetMeleeAttackPoint(), FleeingMovementGenerator< T >::GetPoint(), npc_valkyr_shadowguard::npc_valkyr_shadowguardAI::GoSiphon(), go_tadpole_cage::go_tadpole_cageAI::GossipHello(), spell_item_unusual_compass::HandleDummy(), spell_entropius_black_hole_effect::HandlePull(), spell_boss_magus_telestra_gravity_well::HandlePull(), npc_eris_hevenfire::npc_eris_hevenfireAI::JustSummoned(), spell_gen_random_target32::ModDest(), spell_q12308_escape_from_silverbrook_summon_worgen::ModDest(), spell_random_lightning_visual_effect::ModDestHeight(), npc_gunship_boarding_addAI::MovementInform(), SmartScript::ProcessAction(), npc_lake_frog::npc_lake_frogAI::ReceiveEmote(), npc_firework::npc_fireworkAI::Reset(), PassengerController::SelectSpawnPoint(), spell_q10898_skywing::SetDest(), npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI::SummonBroodling(), npc_eris_hevenfire::npc_eris_hevenfireAI::SummonPeasants(), spell_midsummer_fling_torch::ThrowNextTorch(), instance_old_hillsbrad::instance_old_hillsbrad_InstanceMapScript::Update(), npc_scarlet_ghoul::npc_scarlet_ghoulAI::UpdateAI(), boss_arlokk::boss_arlokkAI::UpdateAI(), npc_pos_leader::npc_pos_leaderAI::UpdateAI(), npc_pos_martin_or_gorkun_second::npc_pos_martin_or_gorkun_secondAI::UpdateAI(), and npc_tirions_gambit_tirion::npc_tirions_gambit_tirionAI::UpdateEscortAI().
GetRng()
static SFMTRand * GetRng () static
{
    if (!sfmtRand)
    {
        sfmtRand = std::make_unique<SFMTRand>();
    }
    return sfmtRand.get();
}
References sfmtRand.
Referenced by rand32().
irand()
int32 irand (int32 min, int32 max)
{
    ASSERT(max >= min);
    std::uniform_int_distribution<int32> uid(min, max);
    return uid(engine);
}
References ASSERT, and engine.
Referenced by spell_shadowfang_keep_haunting_spirits_aura::CalcPeriodic(), SpellEffectInfo::CalcValue(), Spell::CheckCast(), Spell::EffectSchoolDMG(), Spell::EffectTeleportUnits(), GetItemEnchantMod(), spell_gen_gadgetzan_transporter_backfire::HandleDummy(), spell_item_flask_of_the_north::HandleDummy(), npc_echo_of_medivh::HandlePieceMoveByAI(), spell_winter_veil_racer_slam_hit::HandleScriptEffect(), spell_dk_bloodworms::HandleSummon(), boss_kologarn_arms::JustDied(), Unit::MagicSpellHitResult(), spell_gen_flurry_of_claws::OnPeriodic(), npc_doomfire_spirit::Reset(), roll_chance_i(), npc_minigob_manabonk::SendMailToPlayer(), boss_janalai::SpawnBombs(), npc_xt002_heart::SpellHitTarget(), boss_general_angerforge::SummonAdds(), boss_akilzon::SummonEagles(), boss_general_angerforge::SummonMedics(), Spell::TakePower(), npc_akilzon_eagle::UpdateAI(), npc_murkdeep::npc_murkdeepAI::UpdateAI(), npc_pos_after_first_boss::npc_pos_after_first_bossAI::UpdateAI(), boss_grobbulus::boss_grobbulusAI::UpdateAI(), boss_thorim_sif::UpdateAI(), violet_hold_trashAI::UpdateAI(), npc_llod_generic::npc_llod_genericAI::UpdateAI(), Player::UpdateSkillPro(), and GameObject::Use().
rand32()
uint32 rand32 ()
{
    return GetRng()->RandomUInt32();
}
References GetRng(), and SFMTRand::RandomUInt32().
Referenced by npc_thrall_bfu::npc_thrall_bfuAI::ActivateValimathrasPortal(), boss_nefarian::KilledUnit(), boss_vaelastrasz::KilledUnit(), RandomEngine::operator()(), npc_varian_wrynn::npc_varian_wrynnAI::SpawnWave(), and npc_thrall_bfu::npc_thrall_bfuAI::SpawnWave().
rand_chance()
double rand_chance ()
{
    std::uniform_real_distribution<double> urd(0.0, 100.0);
    return urd(engine);
}
References engine.
Referenced by GetExplicitDiscoverySpell(), GetItemEnchantMod(), WorldSession::HandleGMResponseResolve(), LootTemplate::LootGroup::Roll(), roll_chance_f(), PoolGroup< T >::SpawnObject(), boss_majordomo::UpdateAI(), and npc_pet_dk_ebon_gargoyle::UpdateAI().
rand_norm()
double rand_norm ()
{
    std::uniform_real_distribution<double> urd;
    return urd(engine);
}
References engine.
Referenced by RandomMovementGenerator< T >::_setRandomLocation(), Unit::CalcAbsorbResist(), SpellImplicitTargetInfo::CalcDirectionAngle(), boss_headless_horseman::DamageTaken(), npc_midsummer_ribbon_pole_target::DoDancingFLameChecks(), RandomMovementGenerator< T >::DoInitialize(), ConfusedMovementGenerator< T >::DoInitialize(), npc_time_rift::DoSummonAtRift(), Spell::EffectStuck(), Spell::EffectTransmitted(), violet_hold_trashAI::EnterEvadeMode(), Unit::GetRandomContactPoint(), WorldObject::GetRandomNearPosition(), WorldObject::GetRandomPoint(), Position::GetSinCos(), npc_valkyr_shadowguard::npc_valkyr_shadowguardAI::GoSiphon(), spell_icc_geist_alarm::HandleEvent(), WorldSession::HandlePetActionHelper(), spell_dreamwalker_summon_portal::HandleScript(), boss_onyxia::HandleWhelpSpam(), spell_q11065_wrangle_some_aether_rays_aura::if(), npc_troll_volunteer::npc_troll_volunteerAI::InitializeAI(), npc_hourglass_of_eternity::npc_hourglass_of_eternityAI::InitializeAI(), boss_keleseth::JustEngagedWith(), boss_high_astromancer_solarian::JustEngagedWith(), boss_auriaya::JustSummoned(), spell_the_lich_king_teleport_to_frostmourne_hc::ModDest(), npc_ulduar_snow_mound::MoveInLineOfSight(), npc_concentrated_ball::npc_concentrated_ballAI::MoveToNextPoint(), Unit::PetSpellFail(), npc_oculus_unstable_sphere::npc_oculus_unstable_sphereAI::PickNewLocation(), Weather::ReGenerate(), boss_anubarak_trial::boss_anubarak_trialAI::Reset(), spell_sindragosa_s_fury::SelectDest(), Spell::SelectImplicitCasterDestTargets(), Spell::SelectImplicitDestDestTargets(), Spell::SelectImplicitTargetDestTargets(), boss_yoggsaron_sara::SpawnTentacle(), npc_pos_leader_second::npc_pos_leader_secondAI::SpellHitTarget(), npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI::SummonBroodling(), boss_yoggsaron_sara::SummonDeathOrbs(), boss_yoggsaron::SummonImmortalGuardian(), instance_old_hillsbrad::instance_old_hillsbrad_InstanceMapScript::Update(), instance_trial_of_the_champion::instance_trial_of_the_champion_InstanceMapScript::Update(), npc_dark_iron_attack_generator::UpdateAI(), npc_time_rift::UpdateAI(), boss_onyxia::UpdateAI(), boss_icehowl::boss_icehowlAI::UpdateAI(), boss_twin_valkyrAI::UpdateAI(), npc_pos_leader::npc_pos_leaderAI::UpdateAI(), boss_sindragosa::boss_sindragosaAI::UpdateAI(), npc_strangulate_vehicle::npc_strangulate_vehicleAI::UpdateAI(), boss_malygos::UpdateAI(), boss_ormorok::UpdateAI(), boss_drakos::boss_drakosAI::UpdateAI(), boss_eregos::boss_eregosAI::UpdateAI(), boss_mimiron::UpdateAI(), npc_ulduar_flames_initial::UpdateAI(), npc_ulduar_expedition_engineer::UpdateAI(), boss_ymiron::boss_ymironAI::UpdateAI(), npc_hourglass_of_eternity::npc_hourglass_of_eternityAI::UpdateAI(), and boss_ichoron::boss_ichoronAI::UpdateAI().
randtime() [1/2]
Milliseconds randtime (Milliseconds min, Milliseconds max)
{
    long long diff = max.count() - min.count();
    ASSERT(diff >= 0);
    ASSERT(diff <= (uint32) - 1);
    return min + Milliseconds(urand(0, diff));
}
References ASSERT, and urand().
Referenced by EventProcessor::AddEventAtOffset(), boss_professor_putricide::boss_professor_putricideAI::ChangePhase(), go_tadpole_cage::go_tadpole_cageAI::GossipHello(), npc_necrotic_shard::HandleShardMinionSpawnerSmall(), boss_volkhan::JustEngagedWith(), boss_hungarfen::JustEngagedWith(), boss_kiljaeden::JustSummoned(), EventMap::Repeat(), EventMap::RescheduleEvent(), EventMap::ScheduleEvent(), boss_volkhan::SpellHitTarget(), npc_medivh_bm::SummonOrcs(), spell_illidari_council_deadly_strike_aura::Update(), boss_gorosh_the_dervish::UpdateAI(), boss_grizzle::UpdateAI(), boss_okthor::UpdateAI(), boss_sartharion::UpdateAI(), boss_the_lich_king::boss_the_lich_kingAI::UpdateAI(), boss_volkhan::UpdateAI(), and boss_yoggsaron_sara::UpdateAI().
randtime() [2/2]
Seconds randtime (Seconds min, Seconds max)
{
    long long diff = max.count() - min.count();
    ASSERT(diff >= 0);
    ASSERT(diff <= (uint32) - 1);
    return min + Seconds(urand(0, diff));
}
References ASSERT, and urand().
urand()
uint32 urand (uint32 min, uint32 max)
{
    ASSERT(max >= min);
    std::uniform_int_distribution<uint32> uid(min, max);
    return uid(engine);
}
References ASSERT, and engine.
Referenced by at_hol_hall_of_watchers::_OnTrigger(), RandomMovementGenerator< T >::_setRandomLocation(), ObjectMgr::AddCreData(), Loot::AddItem(), spell_dk_ghoul_thrash::CalcDamage(), spell_allergies::CalcPeriodic(), spell_item_goblin_gumbo_kettle::CalcPeriodic(), spell_gen_consumption::CalculateDamage(), Unit::CalculateDamage(), npc_minion_spawner::CanSpawnRareMinion(), BattlegroundAV::ChangeMineOwner(), boss_professor_putricide::boss_professor_putricideAI::ChangePhase(), lfg::LFGQueue::CheckCompatibility(), Group::CountTheRoll(), GameObject::Create(), boss_illidan_stormrage::CycleBeamPos(), npc_anubisath_defender::DamageTaken(), npc_infra_green_bomber_generic::npc_infra_green_bomber_genericAI::DamageTaken(), Unit::DealDamage(), boss_razorgore::DoAction(), boss_anetheron::DoAction(), boss_rage_winterchill::DoAction(), npc_hyjal_ground_trash::DoAction(), npc_hyjal_gargoyle::DoAction(), npc_pos_martin_or_gorkun_second::npc_pos_martin_or_gorkun_secondAI::DoAction(), npc_chesspiece::DoAction(), boss_maexxna::boss_maexxnaAI::DoCastWebWrap(), npc_midsummer_ribbon_pole_target::DoFlameCircleChecks(), RandomMovementGenerator< T >::DoInitialize(), ConfusedMovementGenerator< T >::DoInitialize(), Player::DoRandomRoll(), npc_time_rift::DoSelectSummon(), instance_stratholme::instance_stratholme_InstanceMapScript::DoSpawnPlaguedCritters(), boss_skeram::DoTeleport(), WaypointMovementGenerator< Creature >::DoUpdate(), ConfusedMovementGenerator< T >::DoUpdate(), Spell::EffectDispel(), Spell::EffectDummy(), Spell::EffectForceDeselect(), Spell::EffectScriptEffect(), Spell::EffectStealBeneficialBuff(), Spell::EffectTeleportUnits(), Spell::EffectTransmitted(), npc_ravenclaw_apparition::npc_ravenclaw_apparitionAI::EmoteCrowd(), boss_gehennas::ExecuteEvent(), boss_sartharion_tenebron::ExecuteEvent(), boss_sartharion_shadron::ExecuteEvent(), boss_sartharion_vesperon::ExecuteEvent(), spell_blade_dance_targeting::FilterTargets(), spell_deathbringer_blood_nova_targeting::FilterTargetsInitial(), spell_kologarn_focused_eyebeam::FilterTargetsInitial(), spell_ulduar_stone_grip_cast_target::FilterTargetsInitial(), npc_dark_iron_guzzler::FindNextKeg(), boss_darkmaster_gandling::boss_darkmaster_gandlingAI::FindRoom(), Loot::generateMoneyLoot(), ObjectMgr::GeneratePetName(), ObjectMgr::GeneratePetNameLocale(), ObjectMgr::GetCreatureModelRandomGender(), ObjectMgr::GetEquipmentInfo(), npc_firework::npc_fireworkAI::GetFireworkGameObjectId(), Unit::GetMeleeAttackPoint(), Player::GetNextRandomRaidMember(), Unit::GetNextRandomRaidMemberOrPet(), npc_dark_iron_attack_generator::GetRandomBartender(), Creature::GetRandomId(), npc_brewfest_bark_trigger::GetTextFor(), boss_ambassador_flamelash::getValidRandomPosition(), go_ossirian_crystal::go_ossirian_crystalAI::GossipHello(), WorldState::HandleActiveZone(), spell_brewfest_fill_keg::HandleAfterHit(), spell_scourge_disguise_instability::HandleApply(), spell_gen_baby_murloc_passive::HandleApply(), AuraEffect::HandleAuraModShapeshift(), AuraEffect::HandleAuraTransform(), npc_echo_of_medivh::HandleCheat(), Player::HandleDrowning(), spell_fight_fire_bomber::HandleDummy(), spell_gen_focused_bursts::HandleDummy(), spell_hallows_end_candy::HandleDummy(), spell_q12589_shoot_rjr::HandleDummy(), spell_item_gnomish_universal_remote::HandleDummy(), spell_item_gnomish_shrink_ray::HandleDummy(), spell_item_make_a_wish::HandleDummy(), spell_item_net_o_matic::HandleDummy(), spell_item_noggenfogger_elixir::HandleDummy(), spell_item_savory_deviate_delight::HandleDummy(), spell_item_six_demon_bag::HandleDummy(), spell_item_underbelly_elixir::HandleDummy(), spell_mage_polymorph_cast_visual::HandleDummy(), spell_q12634_despawn_fruit_tosser::HandleDummy(), spell_shadowfang_keep_forsaken_skills_aura::HandleDummyTick(), spell_lich_king_vo_blocker::HandleEffectApply(), spell_midsummer_ribbon_pole::HandleEffectApply(), spell_gen_haunted_aura::HandleEffectCalcPeriodic(), spell_hor_gunship_cannon_fire_aura::HandleEffectPeriodic(), spell_pos_empowered_blizzard_aura::HandleEffectPeriodic(), spell_gen_haunted_aura::HandleEffectPeriodic(), spell_valkyr_touch_aura::HandleEffectPeriodic(), boss_warbringer_omrogg::HandleHeadTalk(), spell_magtheridon_quake::HandleHit(), spell_chapter5_return_to_capital::HandleHit(), boss_malygos::HandleIntroSpeech(), spell_yogg_saron_brain_link_aura::HandleOnEffectApply(), spell_gen_haunted::HandleOnEffectHit(), spell_serpentshrine_cavern_coilfang_water::HandlePeriodic(), spell_gen_baby_murloc_passive::HandlePeriodicTimer(), npc_echo_of_medivh::HandlePieceMoveByAI(), spell_item_magic_dust::HandlePreventAura(), spell_kormok_summon_bone_mages::HandleScript(), spell_gen_netherbloom::HandleScript(), spell_gen_upper_deck_create_foam_sword::HandleScript(), spell_item_scroll_of_recall::HandleScript(), spell_gen_elemental_shield::HandleScript(), spell_hallows_end_trick::HandleScript(), spell_putricide_choking_gas_bomb::HandleScript(), spell_gen_elune_candle::HandleScript(), spell_item_dimensional_ripper_area52::HandleScript(), spell_q12698_the_gift_that_keeps_on_giving::HandleScriptEffect(), spell_summon_amanishi_sentries::HandleScriptEffect(), spell_winter_veil_shoot_air_rifle::HandleScriptEffect(), spell_item_mirrens_drinking_hat::HandleScriptEffect(), npc_necrotic_shard::HandleShardMinionSpawnerSmall(), spell_item_draenic_pale_ale::HandleSummon(), Battleground::HandleTriggerBuff(), spell_magic_eater_food::HandleTriggerSpell(), boss_yoggsaron_sara::InformCloud(), BattlegroundSA::Init(), instance_blackrock_depths::Initialize(), npc_troll_volunteer::npc_troll_volunteerAI::InitializeAI(), npc_time_lost_proto_drake::npc_time_lost_proto_drakeAI::InitializeAI(), npc_pet_gen_imp_in_a_bottle::InitializeAI(), npc_wormhole::npc_wormholeAI::InitializeAI(), npc_chesspiece::InitializeCombatSpellsByEntry(), instance_karazhan::instance_karazhan_InstanceMapScript::instance_karazhan_InstanceMapScript(), boss_azuregos::boss_azuregosAI::JustDied(), boss_volazj::JustDied(), npc_ghostly_priest::JustDied(), npc_phantom_mage::JustDied(), npc_shadowy_mercenary::JustDied(), npc_spectral_footman::JustDied(), npc_tortured_rifleman::JustDied(), npc_pallid_horror::JustDied(), npc_webbed_creature::npc_webbed_creatureAI::JustDied(), npc_nerubar_victim::npc_nerubar_victimAI::JustDied(), boss_shade_of_aran::JustEngagedWith(), boss_crone::JustEngagedWith(), boss_priestess_delrissa::JustEngagedWith(), boss_akilzon::JustEngagedWith(), npc_hyjal_ground_trash::JustEngagedWith(), npc_anubisath_defender::JustEngagedWith(), npc_anubisath_warder::JustEngagedWith(), npc_muglash::npc_muglashAI::JustEngagedWith(), boss_ichoron::boss_ichoronAI::JustEngagedWith(), boss_nexusprince_shaffar::JustEngagedWith(), boss_doomwalker::JustEngagedWith(), boss_nazan::JustEngagedWith(), npc_belnistrasz::npc_belnistraszAI::JustEngagedWith(), npc_prospector_remtravel::npc_prospector_remtravelAI::JustEngagedWith(), boss_rotface::boss_rotfaceAI::JustEngagedWith(), boss_steelbreaker::JustEngagedWith(), boss_fathomguard_sharkkis::JustEngagedWith(), npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::JustSummoned(), boss_yoggsaron_brain::JustSummoned(), npc_frosthound::JustSummoned(), boss_gothik::boss_gothikAI::JustSummoned(), boss_epoch::boss_epochAI::KilledUnit(), boss_mal_ganis::boss_mal_ganisAI::KilledUnit(), boss_meathook::boss_meathookAI::KilledUnit(), boss_salramm::boss_salrammAI::KilledUnit(), boss_maiden_of_grief::boss_maiden_of_griefAI::KilledUnit(), boss_sjonnir::boss_sjonnirAI::KilledUnit(), boss_freya_elder_stonebark::KilledUnit(), boss_freya_elder_brightleaf::KilledUnit(), boss_freya_elder_ironbranch::KilledUnit(), boss_kologarn::KilledUnit(), boss_ymiron::boss_ymironAI::KilledUnit(), boss_kelidan_the_breaker::KilledUnit(), boss_sartharion_dragonAI::KilledUnit(), boss_sacrolash::KilledUnit(), boss_alythess::KilledUnit(), boss_hexlord_malacrass::KilledUnit(), boss_volazj::KilledUnit(), boss_sartharion::KilledUnit(), boss_algalon_the_observer::KilledUnit(), boss_auriaya::KilledUnit(), boss_freya::KilledUnit(), boss_xt002::KilledUnit(), boss_exarch_maladaar::KilledUnit(), boss_talon_king_ikiss::KilledUnit(), boss_ambassador_hellmaw::KilledUnit(), boss_blackheart_the_inciter::KilledUnit(), npc_akama_illidan::KilledUnit(), boss_the_maker::KilledUnit(), boss_faerlina::boss_faerlinaAI::KilledUnit(), boss_patchwerk::boss_patchwerkAI::KilledUnit(), boss_thaddius_summon::boss_thaddius_summonAI::KilledUnit(), boss_stormcaller_brundir::KilledUnit(), spell_wailing_souls_periodic_aura::Load(), spell_igb_explosion_main_aura::Load(), Player::LoadFromDB(), Unit::MeleeSpellHitResult(), npc_cw_area_trigger::npc_cw_area_triggerAI::MoveInLineOfSight(), npc_love_in_air_supply_sentry::MoveInLineOfSight(), npc_chesspiece::MovementInform(), npc_concentrated_ball::npc_concentrated_ballAI::MovementInform(), npc_commander_eligor_dawnbringer::npc_commander_eligor_dawnbringerAI::MovementInform(), boss_felmyst::MovementInform(), npc_xt002_scrapbot::MovementInform(), npc_akilzon_eagle::MovementInform(), npc_chesspiece::npc_chesspiece(), npc_corrupted_totem::npc_corrupted_totem(), npc_cos_stratholme_citizien::npc_cos_stratholme_citizienAI::npc_cos_stratholme_citizienAI(), npc_grimstone::npc_grimstone(), npc_pos_icicle_trigger::npc_pos_icicle_triggerAI::npc_pos_icicle_triggerAI(), npc_ravenclaw_apparition::npc_ravenclaw_apparitionAI::npc_ravenclaw_apparitionAI(), npc_scion_of_eternity::npc_scion_of_eternity(), spell_shadowfang_keep_forsaken_skills_aura::OnApply(), spell_item_ashbringer::OnDummyEffect(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnGameObjectCreate(), instance_karazhan::instance_karazhan_InstanceMapScript::OnUnitDeath(), boss_anetheron::PathEndReached(), boss_rage_winterchill::PathEndReached(), npc_hyjal_ground_trash::PathEndReached(), boss_malchezaar::PickTarget(), BattlegroundAV::PostUpdateImpl(), boss_yoggsaron_brain::PrepareChamberIllusion(), Player::PrepareCharmAISpells(), boss_yoggsaron_brain::PrepareIceCrownIllusion(), spell_gen_spectator_cheer_trigger::PrepareSpellScript(), spell_item_titanium_seal_of_dalaran::PrepareSpellScript(), spell_q11653_youre_not_so_big_now::PrepareSpellScript(), boss_yoggsaron_brain::PrepareStormwindIllusion(), SmartScript::ProcessAction(), WaypointMovementGenerator< Creature >::ProcessWaypointArrival(), RAND(), npc_hourglass_of_eternity::npc_hourglass_of_eternityAI::randEntry(), TaskScheduler::RandomDurationBetween(), instance_halls_of_reflection::RandomizeCompositionsAndShow(), Acore::Containers::RandomResize(), boss_alyson_antille::RandomReverseFriendlyList(), npc_hourglass_of_eternity::npc_hourglass_of_eternityAI::randomWhisper(), randtime(), randtime(), SmartScript::RecalcTimer(), Weather::ReGenerate(), boss_drekthar::boss_drektharAI::Reset(), boss_galvangar::boss_galvangarAI::Reset(), boss_vanndar::boss_vanndarAI::Reset(), boss_golemagg::Reset(), npc_echo_of_medivh::Reset(), npc_akilzon_eagle::Reset(), boss_renataki::boss_renatakiAI::Reset(), boss_ossirian::Reset(), npc_injured_draenei::npc_injured_draeneiAI::Reset(), npc_kerlonian::npc_kerlonianAI::Reset(), npc_ringo::npc_ringoAI::Reset(), npc_shadowpriest_sezziz::npc_shadowpriest_sezzizAI::Reset(), npc_twilight_summon::Reset(), npc_swarm_scarab::npc_swarm_scarabAI::Reset(), boss_bjarngrim::Reset(), boss_sjonnir::boss_sjonnirAI::Reset(), npc_algalon_worm_hole::Reset(), boss_auriaya::Reset(), boss_freya::Reset(), npc_ulduar_dark_rune_sentinel::Reset(), boss_yoggsaron_sara::Reset(), boss_palehoof::boss_palehoofAI::Reset(), boss_ymiron::boss_ymironAI::Reset(), boss_ichoron::boss_ichoronAI::Reset(), npc_valiance_keep_cannoneer::npc_valiance_keep_cannoneerAI::Reset(), npc_injured_7th_legion_soldier::npc_injured_7th_legion_soldierAI::Reset(), npc_rodin_lightning_enabler::Reset(), boss_illidan_stormrage::Reset(), npc_firework::npc_fireworkAI::Reset(), npc_spring_rabbit::npc_spring_rabbitAI::Reset(), BattlegroundAV::ResetBGSubclass(), Creature::Respawn(), Unit::RollMeleeOutcomeAgainst(), boss_bjarngrim::RollStance(), npc_shandy_dalaran::npc_shandy_dalaranAI::RollTask(), npc_dark_iron_guzzler::SayText(), boss_julianne::ScheduleCombat(), boss_sjonnir::boss_sjonnirAI::ScheduleTasks(), boss_yoggsaron_constrictor_tentacle::SelectConstrictTarget(), boss_yoggsaron_corruptor_tentacle::SelectCorruptionTarget(), Creature::SelectLevel(), npc_finklestein::npc_finklesteinAI::SelectRandomCode(), Acore::Containers::SelectRandomContainerElement(), Acore::Containers::SelectRandomContainerElementIf(), npc_gothik_trigger::npc_gothik_triggerAI::SelectRandomSkullPile(), ScriptedAI::SelectSpell(), boss_thorim_arena_npcs::SelectT(), ScriptedAI::SelectTargetFromPlayerList(), AutobroadcastMgr::SendAutobroadcasts(), npc_xt002_heart::SendEnergyToCorner(), Player::SendLoot(), brd_ironhand_guardian::SetData(), instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::SetData(), instance_trial_of_the_champion::instance_trial_of_the_champion_InstanceMapScript::SetData(), spell_mother_shahraz_fatal_attraction::SetDest(), FleeingMovementGenerator< T >::SetTargetLocation(), BattlefieldWG::SetupBattlefield(), boss_hexlord_malacrass::SpawnAdds(), boss_thorim::SpawnAnArenaNPC(), boss_thorim::SpawnCommoners(), boss_yoggsaron_sara::SpawnTentacle(), boss_grandmaster_vorpil::spawnVoidTraveler(), boss_freya::SpawnWave(), npc_varian_wrynn::npc_varian_wrynnAI::SpawnWave(), npc_thrall_bfu::npc_thrall_bfuAI::SpawnWave(), npc_pos_leader_second::npc_pos_leader_secondAI::SpellHitTarget(), npc_chesspiece::SpellHitTarget(), npc_still_at_it_trigger::npc_still_at_it_triggerAI::Start(), BattlegroundAB::StartingEventOpenDoors(), BattlegroundEY::StartingEventOpenDoors(), WorldState::StartNewCityAttack(), WorldState::StartNewCityAttackIfTime(), instance_halls_of_reflection::StartNextWave(), npc_grimstone::SummonBoss(), brann_bronzebeard::brann_bronzebeardAI::SummonCreatures(), npc_ravenclaw_apparition::npc_ravenclaw_apparitionAI::SummonCrowd(), boss_yoggsaron_sara::SummonDeathOrbs(), boss_akilzon::SummonEagles(), npc_pallid_horror::SummonFlameshockers(), boss_kelthuzad::boss_kelthuzadAI::SummonHelper(), boss_noth::boss_nothAI::SummonHelper(), boss_yoggsaron::SummonImmortalGuardian(), boss_paletress::boss_paletressAI::SummonMemory(), go_tadpole_cage::go_tadpole_cageAI::SummonTadpoles(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::SummonWaveP1(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::SummonWaveP2(), boss_fankriss::SummonWorms(), TriggerBurningPitch(), boss_archimonde::UnleashSoulCharge(), spell_item_goblin_gumbo_kettle::Update(), instance_blackwing_lair::Update(), instance_trial_of_the_champion::instance_trial_of_the_champion_InstanceMapScript::Update(), instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::Update(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::Update(), instance_naxxramas::Update(), instance_violet_hold::instance_violet_hold_InstanceMapScript::Update(), GameObject::Update(), Creature::Update(), boss_drekthar::boss_drektharAI::UpdateAI(), boss_galvangar::boss_galvangarAI::UpdateAI(), boss_vanndar::boss_vanndarAI::UpdateAI(), boss_ragnaros::UpdateAI(), npc_mc_core_hound::UpdateAI(), npc_echo_of_medivh::UpdateAI(), npc_chesspiece::UpdateAI(), npc_balance_of_light_and_shadow::npc_balance_of_light_and_shadowAI::UpdateAI(), npc_partygoer_pather::UpdateAI(), npc_partygoer::UpdateAI(), npc_akilzon_eagle::UpdateAI(), boss_arlokk::boss_arlokkAI::UpdateAI(), boss_renataki::boss_renatakiAI::UpdateAI(), npc_dark_iron_attack_generator::UpdateAI(), boss_headless_horseman_head::UpdateAI(), boss_salramm::boss_salrammAI::UpdateAI(), npc_cos_stratholme_citizien::npc_cos_stratholme_citizienAI::UpdateAI(), boss_onyxia::UpdateAI(), npc_belnistrasz::npc_belnistraszAI::UpdateAI(), boss_cthun::UpdateAI(), boss_skeram::UpdateAI(), npc_qiraj_war_spawn::npc_qiraj_war_spawnAI::UpdateAI(), npc_shadowpriest_sezziz::npc_shadowpriest_sezzizAI::UpdateAI(), boss_paletress::boss_paletressAI::UpdateAI(), boss_black_knight::boss_black_knightAI::UpdateAI(), npc_toc5_grand_champion_minion::npc_toc5_grand_champion_minionAI::UpdateAI(), boss_grand_champion::boss_grand_championAI::UpdateAI(), boss_anubarak_trial::boss_anubarak_trialAI::UpdateAI(), npc_swarm_scarab::npc_swarm_scarabAI::UpdateAI(), boss_faction_championsAI::UpdateAI(), npc_toc_priest::npc_toc_priestAI::UpdateAI(), npc_toc_shadow_priest::npc_toc_shadow_priestAI::UpdateAI(), npc_snobold_vassal::npc_snobold_vassalAI::UpdateAI(), boss_gormok::boss_gormokAI::UpdateAI(), boss_jormungarAI::UpdateAI(), boss_twin_valkyrAI::UpdateAI(), boss_ick::boss_ickAI::UpdateAI(), npc_pos_leader::npc_pos_leaderAI::UpdateAI(), npc_pos_icicle_trigger::npc_pos_icicle_triggerAI::UpdateAI(), npc_rimefang::npc_rimefangAI::UpdateAI(), boss_gluth::boss_gluthAI::UpdateAI(), boss_kelthuzad::boss_kelthuzadAI::UpdateAI(), boss_sapphiron::boss_sapphironAI::UpdateAI(), boss_malygos::UpdateAI(), boss_stormcaller_brundir::UpdateAI(), boss_freya::UpdateAI(), boss_freya_elder_brightleaf::UpdateAI(), boss_vezax::UpdateAI(), boss_ignis::UpdateAI(), boss_kologarn::UpdateAI(), boss_mimiron::UpdateAI(), npc_ulduar_leviathan_mkii::UpdateAI(), boss_razorscale::UpdateAI(), npc_ulduar_dark_rune_guardian::UpdateAI(), npc_ulduar_dark_rune_watcher::UpdateAI(), npc_ulduar_dark_rune_sentinel::UpdateAI(), boss_thorim_sif::UpdateAI(), boss_thorim_runic_colossus::UpdateAI(), boss_yoggsaron_sara::UpdateAI(), boss_emalon::boss_emalonAI::UpdateAI(), violet_hold_trashAI::UpdateAI(), npc_azure_invader::npc_azure_invaderAI::UpdateAI(), npc_azure_raider::npc_azure_raiderAI::UpdateAI(), npc_azure_sorceror::npc_azure_sorcerorAI::UpdateAI(), npc_valiance_keep_cannoneer::npc_valiance_keep_cannoneerAI::UpdateAI(), npc_minigob_manabonk::UpdateAI(), npc_dalaran_mage::npc_dalaran_mageAI::UpdateAI(), npc_dalaran_warrior::npc_dalaran_warriorAI::UpdateAI(), npc_commander_eligor_dawnbringer::npc_commander_eligor_dawnbringerAI::UpdateAI(), npc_blessed_banner::npc_blessed_bannerAI::UpdateAI(), npc_still_at_it_trigger::npc_still_at_it_triggerAI::UpdateAI(), npc_maghar_captive::npc_maghar_captiveAI::UpdateAI(), npc_pet_hunter_snake_trap::UpdateAI(), go_flames::go_flamesAI::UpdateAI(), go_heat::go_heatAI::UpdateAI(), go_brewfest_music::go_brewfest_musicAI::UpdateAI(), npc_spring_rabbit::npc_spring_rabbitAI::UpdateAI(), boss_ichoron::boss_ichoronAI::UpdateAI(), npc_warmage_coldarra::npc_warmage_coldarraAI::UpdateAI(), PetAI::UpdateAI(), Player::UpdateCharmedAI(), npc_kurenai_captive::npc_kurenai_captiveAI::UpdateEscortAI(), npc_kerlonian::npc_kerlonianAI::UpdateFollowerAI(), npc_tooga::npc_toogaAI::UpdateFollowerAI(), npc_ringo::npc_ringoAI::UpdateFollowerAI(), urandms(), boss_hexlord_malacrass::UseAbility(), and WeatherForcast().
urandms()
uint32 urandms (uint32 min, uint32 max)
{
    ASSERT(std::numeric_limits<uint32>::max() / Milliseconds::period::den >= max);
    return urand(min * Milliseconds::period::den, max * Milliseconds::period::den);
}
References ASSERT, and urand().
Referenced by npc_pet_hunter_snake_trap::InitializeAI().
urandweighted()
uint32 urandweighted (std::size_t count, double const * chances)
{
    std::discrete_distribution<uint32> dd(chances, chances + count);
    return dd(engine);
}
References engine.
Referenced by Acore::Containers::SelectRandomWeightedContainerElement().
Variable Documentation
engine
RandomEngine engine static
Referenced by frand(), RandomEngine::Instance(), irand(), rand_chance(), rand_norm(), urand(), and urandweighted().
sfmtRand
thread_local std::unique_ptr<SFMTRand> sfmtRand static
Referenced by GetRng().