AzerothCore Doxygen
npc_ulduar_flames_initial::npc_ulduar_flames_initialAI Struct Reference
Public Member Functions
npc_ulduar_flames_initialAI (Creature *pCreature)
void DoAction (int32 action) override
void SpreadFlame (float x, float y)
void RemoveFlame (ObjectGuid guid)
void RemoveAll ()
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
Public Member Functions inherited from NullCreatureAI
NullCreatureAI (Creature *c)
void MoveInLineOfSight (Unit *) override
void AttackStart (Unit *) override
void UpdateAI (uint32) override
Use to start attacking a target. Called just before JustEngagedWith()
void EnterEvadeMode (EvadeReason) override
void OnCharmed (bool) override
Called when unit is charmed.
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0s)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void OnSpellCastFinished (SpellInfo const *, SpellFinishReason)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
int32 VisualizeBoundary (uint32 duration, Unit *owner=nullptr, bool fill=false, bool checkZ=false) const
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
virtual void DistancingStarted ()
virtual void DistancingEnded ()
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void Reset ()
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Public Attributes
GuidList FlameList
EventMap events
uint32 CreateTime
Additional Inherited Members
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from NullCreatureAI
static int32 Permissible (Creature const *creature)
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
npc_ulduar_flames_initialAI()
npc_ulduar_flames_initial::npc_ulduar_flames_initialAI::npc_ulduar_flames_initialAI (Creature * pCreature) inline
                                                         : NullCreatureAI(pCreature)
        {
            CreateTime = GameTime::GetGameTime().count();
            events.Reset();
            events.ScheduleEvent(EVENT_FLAMES_SPREAD, 5750ms);
            if (Creature* flame = me->SummonCreature(NPC_FLAMES_SPREAD, me->GetPositionX(), me->GetPositionY(), 364.32f, 0.0f))
            {
                FlameList.push_back(flame->GetGUID());
                flame->CastSpell(flame, SPELL_FLAMES_AURA, true);
            }
        }
References CreateTime, EVENT_FLAMES_SPREAD, FlameList, GameTime::GetGameTime(), Position::GetPositionX(), Position::GetPositionY(), CreatureAI::me, NPC_FLAMES_SPREAD, UnitAI::Reset(), SPELL_FLAMES_AURA, and WorldObject::SummonCreature().
Member Function Documentation
DoAction()
void npc_ulduar_flames_initial::npc_ulduar_flames_initialAI::DoAction (int32 action) inline override virtual
Reimplemented from UnitAI.
        {
            if (action == 1337)
                RemoveAll();
        }
References RemoveAll().
RemoveAll()
void npc_ulduar_flames_initial::npc_ulduar_flames_initialAI::RemoveAll () inline
        {
            for (ObjectGuid const& guid : FlameList)
                if (Creature* c = ObjectAccessor::GetCreature(*me, guid))
                    c->DespawnOrUnsummon();
            FlameList.clear();
            me->DespawnOrUnsummon();
        }
References Creature::DespawnOrUnsummon(), FlameList, ObjectAccessor::GetCreature(), and CreatureAI::me.
Referenced by DoAction(), and UpdateAI().
RemoveFlame()
void npc_ulduar_flames_initial::npc_ulduar_flames_initialAI::RemoveFlame (ObjectGuid guid) inline
        {
            FlameList.remove(guid);
        }
References FlameList.
SpreadFlame()
void npc_ulduar_flames_initial::npc_ulduar_flames_initialAI::SpreadFlame (float x, float y) inline
        {
            if (Creature* flame = me->SummonCreature(NPC_FLAMES_SPREAD, x, y, 364.32f, 0.0f))
            {
                FlameList.push_back(flame->GetGUID());
                if (Creature* c = me->FindNearestCreature(NPC_FLAMES_SPREAD, 10.0f))
                    if (c->GetExactDist2d(flame->GetPositionX(), flame->GetPositionY()) <= 4.0f)
                        return;
                flame->CastSpell(flame, SPELL_FLAMES_AURA, true);
            }
        }
References WorldObject::FindNearestCreature(), FlameList, CreatureAI::me, NPC_FLAMES_SPREAD, SPELL_FLAMES_AURA, and WorldObject::SummonCreature().
Referenced by UpdateAI().
UpdateAI()
void npc_ulduar_flames_initial::npc_ulduar_flames_initialAI::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Implements UnitAI.
        {
            if (InstanceScript* pInstance = me->GetInstanceScript())
                if (pInstance->GetData(TYPE_MIMIRON) != IN_PROGRESS)
                {
                    RemoveAll();
                    return;
                }
            events.Update(diff);
            switch (events.ExecuteEvent())
            {
                case 0:
                    break;
                case EVENT_FLAMES_SPREAD:
                    {
                        if (FlameList.empty())
{
                            me->DespawnOrUnsummon();
                            return;
                        }
                        if (InstanceScript* pInstance = me->GetInstanceScript())
                            if (Creature* mimiron = GetMimiron())
                                if (CreateTime < mimiron->AI()->GetData(10))
{
                                    break;
                                }
                        Creature* last = ObjectAccessor::GetCreature(*me, FlameList.back());
                        if (last)
{
                            float prevdist = 100.0f;
                            Player* target = nullptr;
                            Map::PlayerList const& pl = me->GetMap()->GetPlayers();
                            for( Map::PlayerList::const_iterator itr = pl.begin(); itr != pl.end(); ++itr )
                                if (Player* plr = itr->GetSource())
                                    if (plr->IsAlive() && plr->GetExactDist2d(last) < prevdist && !plr->IsGameMaster())
{
                                        target = plr;
                                        prevdist = plr->GetExactDist2d(last);
                                    }
                            if (target && prevdist >= 4.0f) // no need to spread when player is standing in fire, check distance
{
                                float angle = last->GetAngle(target->GetPositionX(), target->GetPositionY()) - M_PI / 8 + rand_norm() * 2 * M_PI / 8;
                                SpreadFlame(last->GetPositionX() + 7.0f * cos(angle), last->GetPositionY() + 7.0f * std::sin(angle));
                            }
                        }
                        events.Repeat(5750ms);
                    }
                    break;
            }
        }
References MapRefMgr::begin(), Creature::DespawnOrUnsummon(), MapRefMgr::end(), EVENT_FLAMES_SPREAD, FlameList, Position::GetAngle(), ObjectAccessor::GetCreature(), UnitAI::GetData(), Position::GetExactDist2d(), WorldObject::GetInstanceScript(), WorldObject::GetMap(), GetMimiron, Map::GetPlayers(), Position::GetPositionX(), Position::GetPositionY(), IN_PROGRESS, CreatureAI::me, rand_norm(), RemoveAll(), SpreadFlame(), and TYPE_MIMIRON.
Member Data Documentation
CreateTime
uint32 npc_ulduar_flames_initial::npc_ulduar_flames_initialAI::CreateTime
Referenced by npc_ulduar_flames_initialAI().
events
EventMap npc_ulduar_flames_initial::npc_ulduar_flames_initialAI::events
FlameList
GuidList npc_ulduar_flames_initial::npc_ulduar_flames_initialAI::FlameList
Referenced by npc_ulduar_flames_initialAI(), RemoveAll(), RemoveFlame(), SpreadFlame(), and UpdateAI().
The documentation for this struct was generated from the following file:
azerothcore-wotlk/src/server/scripts/Northrend/Ulduar/Ulduar/boss_mimiron.cpp