AzerothCore Doxygen
SpellProcTestData.h File Reference
#include "SpellMgr.h"
#include <map>
#include <vector>
Classes
struct SpellProcTestEntry
Test data entry from spell_proc table with DBC comparison data.
Functions
std::vector< SpellProcTestEntry > GetAllSpellProcTestEntries ()
All spell_proc entries from the database Total: 869 entries.
std::map< uint32_t, std::vector< SpellProcTestEntry > > GroupByProcFlags ()
Group entries by ProcFlags pattern for targeted testing.
std::map< uint32_t, std::vector< SpellProcTestEntry > > GroupByHitMask ()
Group entries by HitMask for targeted testing.
std::map< uint32_t, std::vector< SpellProcTestEntry > > GroupBySpellFamily ()
Group entries by SpellFamilyName for class-specific testing.
Function Documentation
GetAllSpellProcTestEntries()
std::vector< SpellProcTestEntry > GetAllSpellProcTestEntries () inline
All spell_proc entries from the database Total: 869 entries.
{
    return {
        { -66799, 0, 15, 4194304, 0, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -65661, 0, 15, 4194321, 537001988, 0, 16, 1, 2, 0, 0, 0, 100.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -64127, 0, 6, 1, 1, 0, 0, 6, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -63730, 0, 6, 2048, 4, 0, 0, 0, 2, 0, 0, 100, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -63373, 0, 11, 2147483648, 0, 0, 65536, 1, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -63156, 0, 5, 1, 192, 0, 0, 1, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -62764, 0, 9, 0, 268435456, 0, 65536, 4, 2, 0, 0, 0, 100.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -61846, 0, 0, 0, 0, 0, 64, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -61680, 0, 9, 0, 268435456, 0, 0, 1, 2, 2, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -59887, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -59088, 0, 4, 0, 2, 0, 1024, 4, 4, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -58872, 0, 0, 0, 0, 0, 0, 1, 0, 8259, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -57878, 0, 0, 0, 0, 0, 0, 1, 0, 16, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -57470, 0, 6, 1, 0, 0, 0, 0, 2, 0, 0, 15000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -56636, 0, 4, 32, 0, 0, 0, 0, 2, 0, 0, 5800, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -56342, 0, 9, 24, 134217728, 147456, 0, 0, 4, 0, 2, 22000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -55666, 0, 15, 1, 134217728, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -54747, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -54639, 0, 15, 4194304, 65536, 0, 0, 0, 2, 0, 0, 100, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -53709, 2, 10, 16384, 0, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -53695, 0, 10, 8388608, 0, 8, 16, 5, 2, 0, 2, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -53671, 0, 10, 8388608, 0, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -53583, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -53569, 0, 10, 1075838976, 65536, 0, 0, 3, 2, 0, 2, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -53551, 0, 10, 4096, 0, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -53527, 1, 10, 0, 0, 4, 1024, 0, 2, 1, 0, 0, 100.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -53501, 0, 0, 0, 0, 0, 0, 2, 2, 2, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -53486, 0, 10, 8388608, 163840, 0, 0, 0, 2, 2, 2, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -53380, 0, 10, 8388608, 163840, 0, 0, 1, 2, 2, 2, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -53290, 0, 9, 2048, 1, 512, 0, 1, 2, 2, 2, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -53256, 0, 9, 2048, 8388609, 0, 0, 0, 2, 2, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -53234, 0, 9, 131072, 1, 1, 0, 0, 2, 2, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -53228, 0, 9, 32, 16777216, 0, 0, 4, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -53221, 0, 9, 0, 1, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -53215, 0, 9, 1, 0, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -53178, 0, 9, 0, 268435456, 0, 65536, 4, 2, 0, 0, 0, 100.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -52795, 0, 6, 1, 0, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -52127, 0, 0, 0, 0, 0, 0, 1, 0, 0, 2, 3500, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -51940, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -51692, 0, 8, 516, 0, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -51682, 0, 8, 0, 524288, 0, 0, 4, 2, 0, 2, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -51672, 0, 0, 0, 0, 0, 0, 0, 0, 16, 0, 1000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -51664, 0, 8, 131072, 8, 0, 0, 1, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -51634, 0, 0, 0, 0, 0, 0, 1, 2, 2, 2, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -51627, 0, 0, 0, 0, 0, 0, 0, 0, 112, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -51625, 0, 8, 268476416, 0, 0, 0, 5, 2, 0, 2, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -51562, 0, 11, 256, 0, 16, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -51556, 0, 11, 192, 0, 16, 0, 2, 2, 2, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -51525, 0, 11, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -51523, 0, 11, 0, 1, 0, 65536, 0, 2, 0, 0, 0, 50.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -51521, 0, 11, 0, 16777216, 0, 0, 0, 1, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -51474, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -51459, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -50880, 0, 15, 0, 67108864, 0, 0, 0, 2, 0, 2, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -49467, 0, 15, 16, 131072, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -49223, 0, 15, 17, 134348800, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -49219, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -49217, 0, 15, 0, 0, 2, 0, 0, 2, 0, 0, 500, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -49208, 0, 15, 4194304, 65536, 0, 0, 0, 2, 0, 0, 100, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -49200, 126, 0, 0, 0, 0, 0, 1, 0, 0, 2, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -49188, 0, 15, 0, 131072, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -49182, 0, 15, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -49149, 0, 15, 6, 131074, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -49027, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 20000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -49018, 0, 15, 20971520, 0, 0, 0, 1, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -49015, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -49004, 0, 0, 0, 0, 0, 0, 0, 0, 51, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -48988, 0, 0, 0, 0, 0, 0, 1, 2, 2, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -48979, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -48539, 0, 7, 16, 67108864, 0, 262144, 2, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -48516, 0, 7, 5, 0, 0, 0, 0, 2, 2, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -48506, 0, 7, 5, 0, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -48496, 0, 7, 96, 33554434, 0, 0, 0, 2, 2, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -48483, 0, 7, 34816, 1088, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -47580, 0, 6, 0, 0, 64, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -47569, 0, 6, 16384, 0, 0, 16384, 4, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -47516, 0, 6, 6144, 65536, 0, 0, 0, 2, 0, 2, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -47509, 0, 0, 0, 0, 0, 0, 2, 2, 2, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -47263, 32, 5, 0, 0, 0, 0, 0, 2, 2, 0, 20000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -47258, 0, 5, 0, 8388608, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -47245, 0, 5, 2, 0, 0, 262144, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -47230, 0, 0, 0, 0, 0, 0, 1, 2, 0, 2, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -47201, 0, 5, 16393, 262144, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -47195, 0, 5, 2, 0, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -46951, 0, 4, 1024, 64, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -46945, 0, 4, 0, 65536, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -46913, 0, 4, 64, 1028, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -46867, 0, 0, 0, 0, 0, 0, 1, 2, 2, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -46854, 0, 0, 0, 0, 0, 0, 1, 2, 2, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -45234, 0, 0, 0, 0, 0, 0, 1, 0, 2, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -44557, 0, 3, 32, 0, 0, 0, 0, 2, 0, 0, 6000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -44546, 0, 3, 736, 4096, 0, 69632, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -44449, 0, 3, 551686775, 102472, 0, 0, 0, 2, 2, 0, 8, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -44445, 0, 3, 19, 69632, 0, 0, 1, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -44442, 0, 3, 8388608, 64, 0, 0, 0, 2, 0, 0, 1000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -44404, 0, 3, 536870945, 36864, 0, 0, 1, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -41635, 0, 0, 0, 0, 0, 0, 1, 0, 0, 2, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -35541, 0, 0, 0, 0, 0, 8388608, 0, 0, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -35100, 0, 9, 4096, 0, 1, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -34950, 0, 0, 0, 0, 0, 0, 1, 2, 2, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -34935, 0, 0, 0, 0, 0, 0, 1, 0, 1027, 0, 8000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -34914, 0, 6, 8192, 0, 0, 0, 1, 0, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -34753, 0, 6, 6144, 4, 4096, 0, 0, 2, 2, 2, 1, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -34500, 0, 0, 0, 0, 0, 0, 1, 2, 2, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -34497, 0, 9, 395264, 8388609, 513, 0, 1, 2, 2, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -33881, 0, 0, 0, 0, 0, 0, 1, 0, 2, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -33191, 0, 6, 32768, 1024, 64, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -33150, 0, 0, 0, 0, 0, 0, 3, 2, 2, 2, 6000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -33142, 0, 0, 0, 0, 0, 0, 1, 0, 2, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -33076, 0, 0, 0, 0, 0, 664232, 1, 0, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -32385, 0, 5, 1, 262144, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -31876, 0, 10, 8388608, 0, 0, 0, 1, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -31871, 0, 10, 16, 0, 0, 16384, 4, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -31833, 0, 10, 2147483648, 0, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -31785, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -31656, 4, 3, 134217728, 0, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -31641, 0, 0, 0, 0, 0, 680, 0, 0, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -31571, 0, 3, 0, 34, 0, 16384, 7, 4, 0, 2, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -31569, 0, 3, 65536, 0, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -31244, 0, 8, 3801088, 9, 0, 0, 5, 2, 11196, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -31226, 0, 8, 0, 524288, 0, 0, 5, 2, 0, 2, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -31124, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -30881, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 30000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -30701, 28, 0, 0, 0, 0, 664232, 1, 0, 0, 0, 0, 100.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -30675, 0, 11, 3, 0, 0, 0, 1, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -30482, 0, 0, 0, 0, 0, 0, 1, 0, 1027, 2, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -30299, 126, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -30293, 0, 5, 385, 8519872, 0, 0, 1, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -30160, 0, 0, 0, 0, 0, 0, 1, 2, 2, 0, 500, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -29834, 0, 0, 0, 0, 0, 0, 5, 0, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -29723, 0, 4, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -29593, 0, 0, 0, 0, 0, 0, 1, 0, 112, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -29441, 0, 0, 0, 0, 0, 0, 7, 0, 8, 0, 1000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -29074, 20, 3, 0, 0, 0, 0, 0, 2, 2, 0, 8, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -27811, 0, 0, 0, 0, 0, 0, 1, 0, 2, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -27243, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -20925, 0, 0, 0, 0, 0, 0, 0, 0, 64, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -20500, 0, 4, 268435456, 0, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -20335, 0, 10, 8388608, 0, 0, 16, 5, 2, 0, 0, 0, 100.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -20234, 0, 10, 32768, 0, 0, 0, 2, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -20210, 0, 10, 3221225472, 65536, 0, 0, 0, 2, 2, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -20177, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -20049, 0, 0, 0, 0, 0, 0, 1, 2, 2, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -19572, 0, 9, 8388608, 0, 0, 262144, 2, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -19184, 0, 9, 16, 8192, 0, 0, 0, 4, 0, 2, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -18213, 32, 5, 16384, 0, 0, 2, 0, 0, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -18119, 0, 5, 0, 8388608, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -18096, 0, 5, 256, 8388608, 0, 0, 0, 2, 2, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -18094, 0, 5, 10, 0, 0, 0, 1, 2, 0, 0, 6000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -17793, 0, 5, 1, 0, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -17106, 0, 7, 524288, 0, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -16958, 0, 0, 0, 0, 0, 0, 1, 2, 2, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -16952, 0, 7, 233472, 1024, 262144, 0, 0, 2, 2, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -16880, 72, 7, 103, 58720258, 0, 0, 0, 2, 2, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -16689, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -16487, 0, 0, 0, 0, 0, 0, 1, 0, 2, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -16257, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 500, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -16256, 0, 0, 0, 0, 0, 0, 1, 2, 2, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -16180, 0, 11, 448, 0, 16, 0, 2, 2, 2, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -16176, 0, 11, 448, 0, 16, 0, 2, 2, 2, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -15337, 0, 6, 8396800, 2, 0, 0, 1, 2, 2, 2, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -14892, 0, 6, 268443136, 65540, 0, 0, 0, 2, 2, 2, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -14531, 0, 0, 0, 0, 0, 0, 1, 0, 2, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -14186, 0, 8, 1107296782, 2, 0, 0, 0, 2, 2, 2, 500, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -14156, 0, 8, 4063232, 9, 0, 0, 0, 4, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -14143, 0, 8, 1191182854, 2097152, 0, 0, 1, 2, 0, 8, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -13983, 0, 0, 0, 0, 0, 0, 0, 0, 24, 0, 1000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -13754, 0, 8, 16, 0, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -13165, 0, 0, 0, 0, 0, 64, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -12966, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -12834, 0, 0, 0, 0, 0, 0, 1, 2, 2, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -12319, 0, 0, 0, 0, 0, 0, 1, 2, 2, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -12317, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -12311, 0, 4, 2048, 1, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -12298, 0, 0, 0, 0, 0, 0, 0, 0, 112, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -12289, 0, 4, 2, 0, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -12281, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 6000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -11255, 0, 3, 16384, 0, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -11213, 0, 3, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -11185, 0, 3, 128, 0, 0, 65536, 1, 2, 0, 2, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -11180, 16, 3, 0, 0, 0, 0, 0, 2, 3, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -11119, 4, 3, 0, 0, 0, 0, 1, 2, 2, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -11103, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -11095, 0, 3, 16, 0, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -10400, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 8, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -9799, 0, 0, 0, 0, 0, 0, 1, 0, 2, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -9452, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -7302, 0, 0, 0, 0, 0, 0, 1, 0, 1027, 2, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -7001, 0, 0, 0, 0, 0, 0, 1, 0, 0, 2, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -5952, 0, 8, 0, 1, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -1463, 0, 3, 0, 0, 0, 0, 1, 0, 1024, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -1120, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -974, 0, 0, 0, 0, 0, 0, 1, 0, 0, 2, 3500, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -588, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -324, 0, 0, 0, 0, 0, 0, 1, 0, 0, 2, 3500, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { -168, 0, 0, 0, 0, 0, 0, 1, 0, 1027, 2, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 1719, 0, 4, 778044484, 4212549, 0, 0, 1, 2, 0, 8, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 4341, 0, 0, 0, 0, 0, 4096, 1, 1, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 4524, 0, 0, 0, 0, 0, 1048576, 0, 0, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 5118, 0, 0, 0, 0, 0, 0, 1, 0, 0, 2, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 6346, 0, 0, 0, 0, 0, 0, 0, 0, 256, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 7383, 1, 0, 0, 0, 0, 0, 1, 0, 256, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 7434, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 6000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 8178, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 9782, 0, 0, 0, 0, 0, 0, 0, 0, 64, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 9784, 0, 0, 0, 0, 0, 0, 0, 0, 64, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 11129, 4, 3, 146800663, 200776, 0, 0, 1, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 12043, 0, 3, 1631584309, 4096, 0, 0, 7, 1, 0, 8, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 12169, 0, 0, 0, 0, 0, 0, 0, 0, 64, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 12322, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 12328, 0, 4, 0, 0, 0, 0, 1, 2, 0, 2, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 12536, 0, 3, 549591799, 168000, 0, 0, 0, 1, 0, 12, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 12999, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 13000, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 13001, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 13002, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 13159, 0, 0, 0, 0, 0, 0, 1, 0, 0, 2, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 13163, 0, 0, 0, 0, 0, 0, 0, 0, 16, 0, 20000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 13234, 0, 0, 0, 0, 0, 0, 1, 0, 1027, 2, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 15088, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 5000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 15128, 4, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 15277, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 15286, 32, 6, 41984016, 9218, 8, 0, 1, 2, 0, 2, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 15346, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 15600, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 2000, 2.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 16164, 28, 0, 0, 0, 0, 65536, 1, 2, 2, 0, 500, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 16166, 0, 11, 3, 4096, 0, 0, 7, 1, 0, 8, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 16246, 0, 11, 2551185859, 5120, 16, 0, 0, 1, 0, 12, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 16372, 0, 0, 0, 0, 0, 131072, 0, 0, 0, 0, 0, 100.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 16550, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 16620, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 30000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 16624, 0, 0, 0, 0, 0, 0, 0, 0, 64, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 16864, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 6.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 16870, 0, 7, 14924799, 126879699, 263168, 0, 0, 1, 0, 12, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 17116, 0, 7, 268436065, 33554464, 32768, 0, 7, 1, 0, 8, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 17364, 8, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 17495, 0, 0, 0, 0, 0, 0, 0, 0, 64, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 17619, 0, 13, 0, 0, 0, 34816, 7, 0, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 17670, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 17941, 0, 5, 1, 0, 0, 65536, 1, 1, 0, 8, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 18708, 0, 5, 536870912, 0, 0, 0, 0, 1, 0, 8, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 18820, 0, 0, 0, 0, 0, 0, 7, 1, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 20128, 0, 0, 0, 0, 0, 0, 0, 0, 64, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 20131, 0, 0, 0, 0, 0, 0, 0, 0, 64, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 20132, 0, 0, 0, 0, 0, 0, 0, 0, 64, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 20164, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 20165, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 20166, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 20185, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 20186, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 20375, 1, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 20705, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 20784, 0, 0, 0, 0, 0, 0, 1, 2, 2, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 20911, 0, 0, 0, 0, 0, 0, 0, 0, 112, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 21084, 0, 0, 0, 0, 0, 0, 1, 2, 0, 2, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 21185, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 10000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 21882, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 21890, 0, 4, 712396527, 876, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 22007, 0, 3, 2097185, 0, 0, 0, 1, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 22008, 0, 3, 1631584309, 0, 0, 69632, 5, 1, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 22618, 0, 0, 0, 0, 0, 0, 0, 0, 64, 0, 1000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 22648, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 120000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 23547, 0, 0, 0, 0, 0, 0, 0, 0, 32, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 23548, 0, 0, 0, 0, 0, 0, 0, 0, 64, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 23551, 0, 11, 192, 0, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 23552, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 3500, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 23572, 0, 11, 192, 0, 0, 0, 0, 2, 0, 0, 1000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 23578, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 23581, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 23591, 0, 10, 8388608, 0, 0, 16, 0, 2, 0, 2, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 23686, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 23688, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 23689, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 23721, 0, 9, 2048, 0, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 23920, 0, 0, 0, 0, 0, 0, 0, 0, 2048, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 24353, 0, 0, 0, 0, 0, 0, 1, 2, 2, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 24389, 4, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 24658, 0, 0, 0, 0, 0, 87376, 7, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 24905, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 24932, 0, 0, 0, 0, 0, 0, 1, 2, 2, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 25050, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 25669, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 25899, 0, 0, 0, 0, 0, 0, 0, 0, 112, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 26107, 0, 7, 8388608, 268435584, 0, 0, 0, 2, 116, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 26119, 0, 0, 2416967683, 0, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 26128, 0, 0, 0, 0, 0, 0, 0, 2, 8, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 26135, 0, 10, 8388608, 0, 0, 16, 0, 2, 0, 2, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 26169, 0, 6, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 26467, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 26480, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 26605, 0, 0, 0, 0, 0, 0, 1, 2, 2, 2, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 27419, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 27498, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 27521, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 15000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 27539, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 27656, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 27774, 0, 0, 0, 0, 0, 0, 3, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 27787, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 28200, 0, 0, 0, 0, 0, 0, 3, 1, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 28305, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 28716, 0, 7, 16, 0, 0, 262144, 2, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 28719, 0, 7, 32, 0, 0, 0, 2, 2, 2, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 28744, 0, 7, 64, 0, 0, 278528, 2, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 28752, 0, 0, 0, 0, 0, 0, 1, 2, 2, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 28789, 0, 10, 3221225472, 0, 0, 0, 2, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 28802, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 28809, 0, 6, 4096, 0, 0, 0, 2, 2, 2, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 28812, 0, 8, 33554438, 0, 0, 0, 0, 2, 2, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 28816, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 28823, 0, 11, 192, 0, 0, 0, 2, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 28845, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 28847, 0, 7, 32, 0, 0, 0, 2, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 28849, 0, 11, 128, 0, 0, 0, 2, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 29150, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 29307, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 100.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 29385, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 29455, 0, 0, 0, 0, 0, 0, 0, 0, 64, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 29501, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 29601, 0, 0, 0, 0, 0, 0, 0, 2, 0, 4, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 29624, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 29625, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 29626, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 29632, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 29633, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 29634, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 29635, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 29636, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 29637, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 29977, 4, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 30003, 0, 0, 0, 0, 0, 0, 0, 0, 2048, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 30823, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 30937, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 31394, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 31794, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 31801, 0, 0, 0, 0, 0, 0, 1, 2, 0, 2, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 31834, 0, 10, 2147483648, 0, 0, 16384, 2, 1, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 31904, 0, 0, 0, 0, 0, 0, 0, 0, 64, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 32065, 0, 0, 0, 0, 0, 524288, 1, 0, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 32216, 0, 4, 0, 256, 0, 16, 1, 4, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 32409, 0, 0, 0, 8192, 0, 0, 0, 0, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 32587, 0, 0, 0, 0, 0, 0, 0, 0, 64, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 32642, 0, 0, 0, 0, 0, 0, 0, 0, 64, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 32734, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 3500, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 32748, 0, 8, 0, 1, 0, 320, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 32776, 0, 0, 0, 0, 0, 0, 0, 0, 64, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 32777, 0, 0, 0, 0, 0, 0, 0, 0, 64, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 32837, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 35000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 32844, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 32863, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 32885, 0, 0, 0, 0, 0, 0, 1, 0, 2, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 33089, 0, 0, 0, 0, 0, 0, 0, 0, 64, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 33127, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 33297, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 45000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 33299, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 33510, 0, 0, 0, 0, 0, 340, 1, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 33648, 0, 0, 0, 0, 0, 0, 1, 2, 2, 0, 50000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 33719, 0, 0, 0, 0, 0, 0, 0, 0, 2048, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 33746, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 10000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 33757, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 3000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 33759, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 10000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 33953, 0, 0, 0, 0, 0, 279552, 2, 2, 0, 0, 45000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 34074, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 34080, 0, 0, 0, 0, 0, 0, 0, 0, 32, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 34138, 0, 11, 128, 0, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 34139, 0, 10, 1073741824, 0, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 34258, 0, 10, 8388608, 0, 0, 0, 0, 2, 0, 2, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 34262, 0, 10, 8388608, 0, 0, 0, 0, 2, 0, 2, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 34320, 0, 0, 0, 0, 0, 0, 3, 2, 2, 0, 45000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 34355, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 3500, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 34477, 0, 0, 0, 0, 0, 0, 5, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 34584, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 50000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 34586, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 34598, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 50000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 34749, 0, 0, 0, 0, 0, 0, 0, 2, 8, 2, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 34774, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 20000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 34783, 0, 0, 0, 0, 0, 0, 0, 0, 2048, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 34827, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 4000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 34936, 0, 5, 1, 64, 0, 65536, 1, 1, 0, 8, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 35077, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 60000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 35080, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 60000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 35083, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 60000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 35086, 0, 0, 0, 0, 0, 0, 3, 2, 0, 0, 60000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 35121, 0, 0, 0, 0, 0, 0, 1, 2, 2, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 35321, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 35399, 0, 0, 0, 0, 0, 131072, 0, 0, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 36032, 0, 3, 4096, 32768, 0, 0, 0, 1, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 36096, 0, 0, 0, 0, 0, 0, 0, 0, 2048, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 36111, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 36123, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 36541, 4, 0, 0, 0, 0, 0, 1, 0, 0, 2, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 36659, 0, 0, 0, 0, 0, 524288, 1, 0, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 37165, 0, 8, 2098176, 0, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 37168, 0, 8, 4063232, 9, 0, 0, 0, 4, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 37170, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 37173, 0, 8, 750519704, 262, 0, 0, 0, 2, 0, 0, 30000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 37189, 0, 10, 3221225472, 0, 0, 0, 0, 2, 2, 0, 60000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 37193, 0, 0, 0, 0, 0, 0, 0, 0, 64, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 37195, 0, 10, 8388608, 0, 0, 0, 0, 2, 0, 2, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 37197, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 45000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 37213, 0, 0, 0, 0, 0, 0, 1, 2, 2, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 37214, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 37227, 0, 11, 448, 0, 0, 0, 0, 2, 2, 0, 60000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 37237, 0, 11, 1, 0, 0, 0, 0, 2, 2, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 37247, 8, 0, 0, 0, 0, 0, 0, 2, 0, 0, 40000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 37288, 0, 7, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 37295, 0, 7, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 37377, 32, 5, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 37379, 32, 5, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 37381, 0, 0, 0, 0, 0, 0, 1, 2, 0, 2, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 37384, 0, 5, 1, 64, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 37443, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 37447, 0, 3, 0, 256, 0, 16384, 4, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 37514, 0, 0, 0, 0, 0, 0, 0, 0, 32, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 37516, 0, 4, 1024, 0, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 37519, 0, 0, 0, 0, 0, 0, 0, 2, 48, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 37523, 0, 0, 0, 0, 0, 0, 0, 0, 64, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 37528, 0, 4, 4, 0, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 37536, 0, 4, 65536, 0, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 37568, 0, 6, 2048, 0, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 37594, 0, 6, 4096, 0, 0, 0, 2, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 37600, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 37601, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 37603, 0, 6, 32768, 0, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 37604, 0, 6, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 37655, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 50000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 37657, 0, 0, 0, 0, 0, 0, 1, 2, 2, 0, 2500, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 38026, 1, 0, 0, 0, 0, 0, 1, 0, 256, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 38031, 0, 0, 0, 0, 0, 0, 0, 0, 64, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 38164, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 120000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 38252, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 38290, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 38299, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 15000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 38326, 0, 0, 0, 0, 0, 0, 1, 2, 2, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 38327, 0, 0, 0, 0, 0, 0, 1, 2, 2, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 38334, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 50000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 38347, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 45000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 38350, 0, 0, 0, 0, 0, 0, 1, 2, 2, 0, 45000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 38363, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 38394, 0, 5, 6, 0, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 38857, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 39027, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 3500, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 39215, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 39367, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 39372, 48, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 39437, 4, 5, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 39442, 0, 0, 0, 0, 0, 0, 1, 2, 1, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 39443, 0, 0, 0, 0, 0, 0, 1, 2, 2, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 39530, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 39958, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 40000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 40407, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 40438, 0, 6, 32832, 0, 0, 0, 3, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 40442, 0, 7, 20, 1088, 0, 0, 7, 1, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 40444, 0, 0, 0, 0, 0, 0, 0, 0, 64, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 40458, 0, 4, 33554432, 1537, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 40463, 0, 11, 129, 16, 0, 0, 3, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 40470, 0, 10, 3229614080, 0, 0, 0, 3, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 40475, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 40478, 0, 5, 2, 0, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 40482, 0, 0, 0, 0, 0, 0, 1, 2, 2, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 40485, 0, 9, 0, 1, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 40816, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 7000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 40899, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 40971, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 41034, 126, 0, 0, 0, 0, 0, 0, 0, 1024, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 41260, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 10000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 41262, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 10000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 41350, 0, 0, 0, 0, 0, 0, 1, 2, 0, 2, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 41381, 0, 0, 0, 0, 0, 0, 1, 0, 256, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 41393, 0, 0, 0, 0, 0, 0, 1, 0, 32, 0, 15000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 41434, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 45000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 41469, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 41989, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 42083, 0, 0, 0, 0, 0, 0, 1, 2, 2, 0, 45000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 42135, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 90000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 42136, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 90000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 42368, 0, 10, 1073741824, 0, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 42370, 0, 11, 128, 0, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 42770, 0, 0, 0, 0, 0, 0, 5, 0, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 43443, 0, 0, 0, 0, 0, 0, 0, 0, 2048, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 43726, 0, 10, 1073741824, 0, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 43728, 0, 11, 128, 0, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 43737, 0, 7, 0, 1088, 0, 0, 0, 2, 0, 0, 10000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 43739, 0, 7, 2, 0, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 43741, 0, 10, 2147483648, 0, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 43745, 0, 10, 0, 512, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 43748, 0, 11, 2416967680, 0, 0, 0, 0, 2, 0, 0, 10000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 43750, 0, 11, 1, 0, 0, 0, 0, 2, 0, 0, 30000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 43819, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 44141, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 44401, 0, 3, 0, 0, 0, 69632, 5, 1, 0, 8, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 44543, 0, 3, 1049120, 4096, 0, 0, 0, 1, 0, 2, 0, 7.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 44545, 0, 3, 1049120, 4096, 0, 0, 0, 1, 0, 2, 0, 15.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 45054, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 15000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 45057, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 30000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 45092, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 45354, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 45000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 45355, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 45000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 45469, 0, 15, 16, 0, 0, 16, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 45481, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 45000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 45482, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 45000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 45483, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 45000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 45484, 0, 0, 0, 0, 0, 16384, 2, 2, 0, 0, 45000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 46025, 32, 6, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 46092, 0, 10, 1073741824, 0, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 46098, 0, 11, 128, 0, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 46569, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 45000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 46662, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 25000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 46832, 0, 7, 1, 0, 0, 0, 0, 2, 0, 0, 15000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 46910, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 46911, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 46916, 0, 4, 2097152, 0, 0, 0, 0, 4, 0, 2, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 47383, 0, 5, 0, 192, 0, 0, 0, 1, 0, 8, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 47981, 0, 0, 0, 0, 0, 0, 0, 0, 2048, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 48108, 0, 3, 4194304, 0, 0, 65536, 1, 1, 0, 8, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 48504, 0, 0, 0, 0, 0, 0, 1, 0, 0, 2, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 48833, 0, 7, 0, 1088, 0, 0, 0, 2, 0, 0, 10000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 48835, 0, 10, 8388608, 0, 0, 0, 0, 2, 0, 2, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 48837, 0, 11, 2416967680, 0, 0, 0, 0, 2, 0, 0, 10000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 49005, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 49028, 0, 0, 0, 0, 0, 0, 5, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 49194, 0, 15, 0, 0, 1, 0, 1, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 49222, 0, 0, 0, 0, 0, 139944, 1, 0, 0, 0, 2000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 49592, 0, 0, 0, 0, 0, 8528552, 1, 0, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 49622, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 50000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 49796, 0, 15, 2, 131078, 0, 0, 0, 4, 0, 8, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 50240, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 50421, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 50781, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 6000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 50871, 0, 9, 0, 1073741824, 0, 0, 1, 2, 2, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 50908, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 51123, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 51124, 0, 15, 2, 6, 0, 65552, 1, 4, 0, 8, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 51127, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 51128, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 51129, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 51130, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 51209, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 51346, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 10000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 51349, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 10000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 51352, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 10000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 51359, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 10000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 51414, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 45000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 51528, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 51529, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 51530, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 51531, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 51532, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 51698, 0, 0, 0, 0, 0, 0, 3, 4, 2, 0, 1000, 33.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 51700, 0, 0, 0, 0, 0, 0, 3, 4, 2, 0, 1000, 66.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 51701, 0, 0, 0, 0, 0, 0, 3, 4, 2, 0, 1000, 100.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 51915, 0, 0, 0, 0, 0, 16777216, 0, 0, 0, 0, 600000, 100.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 52020, 0, 7, 32768, 1048576, 0, 0, 0, 2, 0, 0, 10000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 52420, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 30000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 52423, 0, 0, 0, 0, 0, 0, 0, 0, 32, 0, 45000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 52437, 1, 4, 536870912, 0, 0, 16, 0, 4, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 52881, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 12000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 52898, 0, 0, 0, 0, 0, 0, 1, 0, 2, 0, 6000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 53257, 0, 9, 0, 268435456, 0, 16, 1, 2, 2, 8, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 53386, 0, 15, 2182250279, 447, 0, 0, 1, 2, 0, 2, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 53397, 0, 0, 0, 0, 0, 0, 1, 2, 2, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 53515, 0, 0, 0, 0, 0, 0, 3, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 53601, 0, 0, 0, 0, 0, 1048576, 0, 0, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 53646, 0, 0, 0, 0, 0, 0, 1, 2, 2, 0, 5000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 53651, 0, 0, 0, 0, 0, 0, 2, 0, 0, 2, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 53736, 0, 0, 0, 0, 0, 0, 1, 2, 0, 2, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 53817, 0, 11, 451, 32768, 0, 0, 0, 1, 0, 8, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 54274, 0, 5, 357, 131264, 0, 0, 0, 1, 0, 8, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 54276, 0, 5, 357, 131264, 0, 0, 0, 1, 0, 8, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 54277, 0, 5, 357, 131264, 0, 0, 0, 1, 0, 8, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 54278, 0, 0, 0, 0, 0, 0, 1, 2, 2, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 54646, 0, 0, 0, 0, 0, 0, 1, 2, 2, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 54695, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 45000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 54707, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 50000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 54738, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 45000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 54741, 0, 3, 4, 0, 0, 65536, 5, 1, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 54748, 0, 0, 0, 0, 0, 0, 0, 0, 259, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 54754, 0, 7, 16, 0, 0, 0, 2, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 54808, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 50000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 54815, 0, 7, 32768, 0, 0, 16, 1, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 54821, 0, 7, 4096, 0, 0, 16, 1, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 54832, 0, 7, 0, 4096, 0, 16384, 4, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 54838, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 45000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 54841, 0, 0, 0, 0, 0, 0, 1, 2, 2, 0, 2500, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 54845, 0, 7, 4, 0, 0, 65536, 1, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 54909, 0, 0, 0, 0, 0, 0, 1, 2, 2, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 54925, 2, 10, 0, 512, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 54937, 0, 10, 2147483648, 0, 0, 0, 2, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 54939, 0, 10, 32768, 0, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 55198, 0, 11, 448, 0, 0, 16384, 2, 2, 2, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 55380, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 40000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 55381, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 15000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 55440, 0, 11, 64, 0, 0, 0, 2, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 55640, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 60000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 55677, 0, 6, 0, 1, 0, 0, 4, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 55680, 0, 6, 512, 0, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 55681, 0, 6, 32768, 0, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 55689, 0, 0, 0, 0, 0, 0, 1, 2, 2, 2, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 55747, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 45000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 55768, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 45000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 55776, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 55000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 56218, 0, 5, 2, 0, 0, 0, 1, 2, 0, 0, 6000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 56249, 0, 5, 0, 0, 1024, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 56355, 0, 0, 0, 0, 0, 0, 0, 0, 64, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 56364, 0, 3, 0, 16777216, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 56372, 0, 3, 0, 128, 0, 16384, 4, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 56374, 0, 3, 0, 16384, 0, 16384, 4, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 56375, 0, 3, 16777216, 0, 0, 65536, 4, 2, 2049, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 56451, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 3500, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 56800, 0, 8, 4, 0, 0, 16, 1, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 56816, 0, 0, 0, 0, 0, 0, 0, 0, 48, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 56817, 0, 15, 0, 536870912, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 56821, 0, 8, 2, 0, 0, 0, 0, 2, 2, 0, 500, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 56841, 0, 9, 2048, 0, 0, 256, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 57345, 0, 0, 0, 0, 0, 0, 3, 2, 0, 0, 45000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 57351, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 57352, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 45000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 57529, 0, 3, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 57531, 0, 3, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 57761, 0, 3, 1, 4096, 0, 65536, 1, 1, 0, 8, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 57870, 0, 9, 8388608, 0, 0, 262144, 2, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 57907, 0, 7, 2, 0, 0, 0, 0, 2, 0, 0, 45000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 57989, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 58357, 0, 4, 64, 0, 0, 0, 0, 2, 2, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 58364, 0, 4, 1024, 0, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 58372, 0, 4, 2, 0, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 58375, 0, 4, 0, 512, 0, 16, 1, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 58386, 0, 0, 0, 0, 0, 0, 0, 2, 32, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 58442, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 30000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 58444, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 5000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 58501, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 30000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 58616, 0, 15, 16777216, 0, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 58620, 0, 15, 4, 0, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 58626, 0, 15, 33554432, 0, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 58642, 0, 15, 0, 134217728, 0, 16, 1, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 58677, 0, 15, 8192, 0, 0, 0, 2, 2, 0, 2, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 58877, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 58901, 0, 0, 0, 0, 0, 0, 1, 2, 2, 0, 50000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 59176, 0, 0, 0, 0, 0, 0, 1, 0, 2, 0, 6000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 59327, 0, 15, 134217728, 0, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 59345, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 45000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 59630, 0, 0, 0, 0, 0, 69648, 5, 1, 0, 2, 35000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 59725, 0, 0, 0, 0, 0, 0, 0, 0, 2048, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 59906, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 59915, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 60061, 0, 0, 0, 0, 0, 294912, 2, 2, 0, 0, 45000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 60063, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 45000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 60066, 0, 0, 0, 0, 0, 0, 1, 2, 2, 0, 50000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 60132, 0, 15, 16, 134348800, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 60170, 0, 5, 6, 0, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 60172, 0, 5, 262144, 0, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 60176, 0, 4, 32, 16, 0, 262144, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 60221, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 50000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 60301, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 45000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 60306, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 45000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 60317, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 45000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 60436, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 45000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 60442, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 45000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 60473, 0, 0, 0, 0, 0, 0, 3, 2, 0, 0, 45000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 60482, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 45000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 60487, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 15000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 60490, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 45000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 60493, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 45000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 60503, 1, 4, 4, 0, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 60519, 0, 0, 0, 0, 0, 0, 3, 2, 0, 0, 50000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 60524, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 60529, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 45000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 60537, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 45000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 60564, 0, 11, 2416967680, 0, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 60571, 0, 11, 2416967680, 0, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 60572, 0, 11, 2416967680, 0, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 60573, 0, 11, 2416967680, 0, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 60574, 0, 11, 2416967680, 0, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 60575, 0, 11, 2416967680, 0, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 60617, 0, 0, 0, 0, 0, 0, 0, 0, 32, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 60710, 0, 7, 2, 0, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 60717, 0, 7, 2, 0, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 60719, 0, 7, 2, 0, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 60722, 0, 7, 2, 0, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 60724, 0, 7, 2, 0, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 60726, 0, 7, 2, 0, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 60770, 0, 11, 1, 0, 0, 0, 0, 2, 0, 0, 30000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 60818, 0, 10, 0, 512, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 60826, 0, 15, 20971520, 0, 0, 0, 0, 2, 0, 0, 45000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 61062, 0, 3, 0, 256, 0, 16384, 4, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 61188, 0, 5, 4, 0, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 61257, 0, 0, 0, 0, 0, 0, 5, 0, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 61324, 0, 10, 0, 131072, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 61356, 0, 0, 0, 0, 0, 0, 1, 2, 2, 0, 45000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 61618, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 45000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 61848, 0, 0, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 62114, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 50000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 62115, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 50000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 62147, 0, 15, 2, 0, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 62259, 0, 15, 33554432, 0, 0, 0, 0, 0, 0, 1, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 62337, 0, 0, 0, 0, 0, 40, 0, 0, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 62459, 0, 15, 4, 0, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 62600, 0, 0, 0, 0, 0, 0, 1, 2, 2, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 62606, 0, 0, 0, 0, 0, 0, 0, 0, 1027, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 63057, 0, 7, 0, 262144, 0, 16384, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 63086, 0, 9, 0, 0, 65536, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 63108, 0, 5, 2, 0, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 63251, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 50000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 63279, 0, 11, 0, 1024, 0, 0, 4, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 63280, 0, 11, 536870912, 0, 0, 0, 0, 1, 0, 2, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 63310, 0, 5, 0, 65536, 0, 65536, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 63320, 0, 5, 2147745792, 0, 32768, 1024, 7, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 63335, 0, 15, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 63611, 0, 0, 0, 0, 0, 0, 1, 2, 0, 1, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 63849, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 64343, 0, 3, 2, 0, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 64411, 0, 0, 0, 0, 0, 279552, 2, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 64415, 0, 0, 0, 0, 0, 279552, 2, 2, 0, 0, 45000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 64440, 0, 0, 0, 0, 0, 0, 0, 0, 32, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 64571, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 10000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 64714, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 45000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 64738, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 50000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 64742, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 45000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 64752, 0, 7, 4096, 256, 2097152, 0, 0, 2, 0, 0, 15000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 64764, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 50000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 64786, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 45000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 64792, 0, 0, 0, 0, 0, 0, 1, 2, 2, 0, 50000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 64823, 0, 7, 4, 0, 0, 65536, 1, 1, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 64824, 0, 7, 2097152, 0, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 64860, 0, 9, 0, 1, 0, 0, 0, 2, 0, 0, 45000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 64867, 0, 3, 536870945, 4096, 0, 0, 0, 2, 0, 0, 45000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 64882, 0, 10, 0, 1048576, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 64890, 0, 10, 0, 65536, 0, 0, 2, 2, 2, 2, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 64908, 0, 6, 8192, 0, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 64912, 0, 6, 1, 0, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 64914, 0, 8, 65536, 0, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 64928, 0, 11, 1, 0, 0, 0, 1, 2, 2, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 64938, 0, 4, 2097216, 0, 0, 0, 0, 2, 2, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 64952, 0, 7, 0, 1088, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 64955, 0, 10, 0, 64, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 64964, 0, 15, 0, 536870912, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 64976, 0, 4, 1, 0, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 64999, 0, 0, 0, 0, 0, 0, 0, 2, 0, 4, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 65002, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 50000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 65005, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 45000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 65007, 0, 0, 0, 0, 0, 81920, 3, 1, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 65013, 0, 0, 0, 0, 0, 0, 1, 2, 2, 0, 50000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 65020, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 45000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 65025, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 45000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 65032, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 66808, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 66865, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3000, 35.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 66889, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 100.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 67115, 0, 15, 20971520, 0, 0, 0, 0, 2, 0, 0, 45000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 67151, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 45000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 67209, 1, 8, 1048576, 0, 0, 0, 0, 2, 0, 0, 15000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 67228, 0, 11, 0, 4096, 0, 0, 1, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 67353, 0, 7, 32768, 1049856, 0, 0, 0, 2, 0, 0, 8000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 67356, 8, 7, 16, 0, 0, 0, 2, 2, 0, 0, 5000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 67361, 0, 7, 2, 0, 0, 0, 1, 2, 0, 0, 6000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 67363, 0, 10, 2147483648, 0, 0, 0, 0, 2, 0, 0, 8000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 67365, 0, 10, 0, 2048, 0, 0, 0, 2, 0, 0, 8000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 67379, 0, 10, 0, 262144, 0, 0, 0, 2, 0, 0, 9000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 67381, 0, 15, 0, 536870912, 0, 0, 0, 2, 0, 0, 10000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 67384, 0, 15, 16, 134348800, 0, 0, 0, 2, 0, 0, 10000, 80.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 67386, 0, 11, 1, 0, 0, 65536, 0, 1, 0, 0, 6000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 67389, 0, 11, 256, 0, 0, 16384, 0, 1, 0, 0, 8000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 67392, 0, 11, 0, 0, 4, 16, 0, 2, 0, 0, 9000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 67530, 0, 0, 0, 0, 0, 40, 0, 0, 0, 0, 5000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 67653, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 50000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 67667, 0, 0, 0, 0, 0, 16384, 2, 1, 0, 0, 45000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 67670, 0, 0, 0, 0, 0, 65536, 1, 1, 0, 0, 45000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 67672, 0, 0, 0, 0, 0, 8388948, 1, 2, 0, 0, 50000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 67698, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 67702, 1, 0, 0, 0, 0, 0, 1, 2, 0, 0, 45000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 67712, 0, 0, 0, 0, 0, 69632, 1, 2, 2, 0, 2000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 67752, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 67758, 0, 0, 0, 0, 0, 69632, 1, 2, 2, 0, 2000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 67771, 1, 0, 0, 0, 0, 0, 1, 2, 0, 0, 45000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 68051, 1, 4, 4, 0, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 68160, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 69739, 0, 0, 0, 0, 0, 0, 7, 2, 0, 0, 50000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 69755, 0, 0, 0, 0, 0, 0, 7, 2, 0, 0, 50000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 69762, 0, 0, 0, 0, 0, 87040, 0, 1, 0, 256, 100, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 70188, 0, 0, 0, 0, 0, 0, 0, 0, 16, 0, 3000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 70388, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 70652, 0, 15, 8, 0, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 70656, 0, 15, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 70664, 0, 7, 16, 0, 0, 0, 2, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 70672, 0, 0, 0, 0, 0, 0, 0, 0, 12287, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 70723, 0, 7, 5, 0, 0, 0, 1, 2, 2, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 70727, 0, 9, 1, 0, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 70730, 0, 9, 16384, 4096, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 70748, 0, 3, 0, 2097152, 0, 1024, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 70756, 0, 10, 0, 65536, 0, 0, 2, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 70761, 0, 10, 0, 0, 1, 1024, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 70770, 0, 6, 2048, 0, 0, 0, 2, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 70803, 0, 8, 4063232, 8, 0, 0, 0, 4, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 70805, 0, 8, 0, 131072, 0, 0, 4, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 70807, 0, 11, 0, 0, 16, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 70808, 0, 11, 256, 0, 0, 0, 2, 2, 2, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 70811, 0, 11, 3, 0, 0, 0, 0, 1, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 70817, 0, 11, 0, 4096, 0, 65536, 1, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 70830, 0, 11, 0, 131072, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 70841, 0, 5, 4, 256, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 70844, 0, 4, 256, 0, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 70854, 0, 4, 0, 16, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 70904, 0, 6, 0, 0, 2048, 2048, 4, 0, 0, 0, 1000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 71162, 0, 5, 0, 192, 0, 0, 0, 1, 0, 8, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 71165, 0, 5, 0, 192, 0, 0, 0, 1, 0, 8, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 71174, 1, 7, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 71176, 0, 7, 2097154, 0, 0, 0, 1, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 71178, 0, 7, 16, 0, 0, 0, 2, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 71186, 0, 10, 0, 32768, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 71191, 0, 10, 0, 65536, 0, 0, 2, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 71194, 0, 10, 0, 1048576, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 71198, 4, 11, 268435456, 0, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 71214, 0, 11, 0, 16, 0, 16, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 71217, 0, 11, 0, 0, 16, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 71226, 0, 15, 16, 134348800, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 71228, 0, 15, 0, 536870912, 0, 0, 0, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 71402, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 45000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 71404, 0, 0, 0, 0, 0, 0, 1, 2, 2, 0, 50000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 71406, 0, 0, 0, 0, 0, 0, 1, 2, 0, 2, 0, 50.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 71519, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 105000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 71540, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 45000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 71545, 0, 0, 0, 0, 0, 0, 1, 2, 0, 2, 0, 50.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 71562, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 105000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 71564, 126, 0, 0, 0, 0, 0, 3, 2, 2, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 71567, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 250, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 71571, 0, 0, 0, 0, 0, 0, 1, 2, 0, 2, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 71573, 0, 0, 0, 0, 0, 0, 1, 2, 0, 2, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 71585, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 50000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 71602, 0, 0, 0, 0, 0, 65536, 1, 1, 0, 0, 45000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 71604, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10000, 100.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 71606, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 100000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 71611, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 45000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 71634, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 30000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 71637, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 100000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 71640, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 30000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 71642, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 45000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 71645, 0, 0, 0, 0, 0, 65536, 1, 1, 0, 0, 45000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 71756, 4, 0, 0, 0, 0, 0, 1, 2, 0, 2, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 71761, 0, 3, 0, 1048576, 0, 0, 5, 2, 256, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 71770, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 71865, 0, 0, 0, 0, 0, 0, 2, 2, 0, 2, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 71868, 0, 0, 0, 0, 0, 0, 2, 2, 0, 2, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 71880, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 71892, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 71903, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 71993, 0, 0, 0, 0, 0, 4, 0, 0, 12287, 0, 3000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 72059, 0, 0, 0, 0, 0, 0, 1, 0, 1027, 2, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 72176, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 72256, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 72413, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 60000, 10.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 72417, 0, 0, 0, 0, 0, 327680, 1, 2, 0, 0, 60000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 72419, 0, 0, 0, 0, 0, 0, 2, 1, 0, 0, 60000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 72455, 0, 0, 0, 0, 0, 0, 0, 0, 12287, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 72673, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10000, 100.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 72674, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10000, 100.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 72675, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10000, 100.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 72782, 4, 0, 0, 0, 0, 0, 1, 2, 0, 2, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 72783, 4, 0, 0, 0, 0, 0, 1, 2, 0, 2, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 72784, 4, 0, 0, 0, 0, 0, 1, 2, 0, 2, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 72832, 0, 0, 0, 0, 0, 0, 0, 0, 12287, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 72833, 0, 0, 0, 0, 0, 0, 0, 0, 12287, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 74396, 84, 3, 685904631, 1151048, 0, 65536, 0, 1, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 75455, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 45000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 75457, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 45000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 75465, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 50000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 75474, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 50000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 75475, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 45000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 75481, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 45000, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 75490, 0, 0, 0, 0, 0, 0, 2, 2, 0, 2, 0, 0.0f, 0.0f, 0, 0, 0, 0, 0 },
        { 75495, 0, 0, 0, 0, 0, 0, 2, 2, 0, 2, 0, 0.0f }
    };
}
Referenced by GroupByHitMask(), GroupByProcFlags(), GroupBySpellFamily(), SpellProcDatabaseTest::SetUp(), SpellProcDBCValidationTest::SetUp(), and SpellProcCoverageStatsTest::SetUp().
GroupByHitMask()
std::map< uint32_t, std::vector< SpellProcTestEntry > > GroupByHitMask () inline
Group entries by HitMask for targeted testing.
{
    std::map<uint32_t, std::vector<SpellProcTestEntry>> grouped;
    for (auto const& entry : GetAllSpellProcTestEntries())
    {
        grouped[entry.HitMask].push_back(entry);
    }
    return grouped;
}
References GetAllSpellProcTestEntries().
GroupByProcFlags()
std::map< uint32_t, std::vector< SpellProcTestEntry > > GroupByProcFlags () inline
Group entries by ProcFlags pattern for targeted testing.
{
    std::map<uint32_t, std::vector<SpellProcTestEntry>> grouped;
    for (auto const& entry : GetAllSpellProcTestEntries())
    {
        grouped[entry.ProcFlags].push_back(entry);
    }
    return grouped;
}
References GetAllSpellProcTestEntries().
GroupBySpellFamily()
std::map< uint32_t, std::vector< SpellProcTestEntry > > GroupBySpellFamily () inline
Group entries by SpellFamilyName for class-specific testing.
{
    std::map<uint32_t, std::vector<SpellProcTestEntry>> grouped;
    for (auto const& entry : GetAllSpellProcTestEntries())
    {
        grouped[entry.SpellFamilyName].push_back(entry);
    }
    return grouped;
}
References GetAllSpellProcTestEntries().