AzerothCore Doxygen
LuaBattleGround Namespace Reference
Functions
int GetName (lua_State *L, BattleGround *bg)
int GetAlivePlayersCountByTeam (lua_State *L, BattleGround *bg)
int GetMap (lua_State *L, BattleGround *bg)
int GetBonusHonorFromKillCount (lua_State *L, BattleGround *bg)
int GetBracketId (lua_State *L, BattleGround *bg)
int GetEndTime (lua_State *L, BattleGround *bg)
int GetFreeSlotsForTeam (lua_State *L, BattleGround *bg)
int GetInstanceId (lua_State *L, BattleGround *bg)
int GetMapId (lua_State *L, BattleGround *bg)
int GetTypeId (lua_State *L, BattleGround *bg)
int GetMaxLevel (lua_State *L, BattleGround *bg)
int GetMinLevel (lua_State *L, BattleGround *bg)
int GetMaxPlayers (lua_State *L, BattleGround *bg)
int GetMinPlayers (lua_State *L, BattleGround *bg)
int GetMaxPlayersPerTeam (lua_State *L, BattleGround *bg)
int GetMinPlayersPerTeam (lua_State *L, BattleGround *bg)
int GetWinner (lua_State *L, BattleGround *bg)
int GetStatus (lua_State *L, BattleGround *bg)
Function Documentation
GetAlivePlayersCountByTeam()
int LuaBattleGround::GetAlivePlayersCountByTeam (lua_State * L, BattleGround * bg)
Returns the amount of alive players in the [BattleGround] by the team ID.
Parameters
[Team] team : team ID
Returns
uint32 count
    {
        uint32 team = Eluna::CHECKVAL<uint32>(L, 2);
#ifndef AZEROTHCORE
        Eluna::Push(L, bg->GetAlivePlayersCountByTeam((Team)team));
#else
        Eluna::Push(L, bg->GetAlivePlayersCountByTeam((TeamId)team));
#endif
        return 1;
    }
References Eluna::Push().
GetBonusHonorFromKillCount()
int LuaBattleGround::GetBonusHonorFromKillCount (lua_State * L, BattleGround * bg)
Returns the bonus honor given by amount of kills in the specific [BattleGround].
Parameters
uint32 kills : amount of kills
Returns
uint32 bonusHonor
    {
        uint32 kills = Eluna::CHECKVAL<uint32>(L, 2);
        Eluna::Push(L, bg->GetBonusHonorFromKill(kills));
        return 1;
    }
References Eluna::Push().
GetBracketId()
int LuaBattleGround::GetBracketId (lua_State * L, BattleGround * bg)
Returns the bracket ID of the specific [BattleGround].
Returns
[BattleGroundBracketId] bracketId
    {
        Eluna::Push(L, bg->GetBracketId());
        return 1;
    }
References Eluna::Push().
GetEndTime()
int LuaBattleGround::GetEndTime (lua_State * L, BattleGround * bg)
Returns the end time of the [BattleGround].
Returns
uint32 endTime
    {
#ifdef CATA
        Eluna::Push(L, bg->GetRemainingTime());
#else
        Eluna::Push(L, bg->GetEndTime());
#endif
        return 1;
    }
References Eluna::Push().
GetFreeSlotsForTeam()
int LuaBattleGround::GetFreeSlotsForTeam (lua_State * L, BattleGround * bg)
Returns the amount of free slots for the selected team in the specific [BattleGround].
Parameters
[Team] team : team ID
Returns
uint32 freeSlots
    {
        uint32 team = Eluna::CHECKVAL<uint32>(L, 2);
#ifndef AZEROTHCORE
        Eluna::Push(L, bg->GetFreeSlotsForTeam((Team)team));
#else
        Eluna::Push(L, bg->GetFreeSlotsForTeam((TeamId)team));
#endif
        return 1;
    }
References Eluna::Push().
GetInstanceId()
int LuaBattleGround::GetInstanceId (lua_State * L, BattleGround * bg)
Returns the instance ID of the [BattleGround].
Returns
uint32 instanceId
    {
        Eluna::Push(L, bg->GetInstanceID());
        return 1;
    }
References Eluna::Push().
GetMap()
int LuaBattleGround::GetMap (lua_State * L, BattleGround * bg)
Returns the [Map] of the [BattleGround].
Returns
[Map] map
    {
        Eluna::Push(L, bg->GetBgMap());
        return 1;
    }
References Eluna::Push().
GetMapId()
int LuaBattleGround::GetMapId (lua_State * L, BattleGround * bg)
Returns the map ID of the [BattleGround].
Returns
uint32 mapId
    {
        Eluna::Push(L, bg->GetMapId());
        return 1;
    }
References Eluna::Push().
GetMaxLevel()
int LuaBattleGround::GetMaxLevel (lua_State * L, BattleGround * bg)
Returns the max allowed [Player] level of the specific [BattleGround].
Returns
uint32 maxLevel
    {
        Eluna::Push(L, bg->GetMaxLevel());
        return 1;
    }
References Eluna::Push().
GetMaxPlayers()
int LuaBattleGround::GetMaxPlayers (lua_State * L, BattleGround * bg)
Returns the maximum allowed [Player] count of the specific [BattleGround].
Returns
uint32 maxPlayerCount
    {
#ifndef AZEROTHCORE
        Eluna::Push(L, bg->GetMaxPlayers());
#else
        Eluna::Push(L, bg->GetMaxPlayersPerTeam() * 2);
#endif
        return 1;
    }
References Eluna::Push().
GetMaxPlayersPerTeam()
int LuaBattleGround::GetMaxPlayersPerTeam (lua_State * L, BattleGround * bg)
Returns the maximum allowed [Player] count per team of the specific [BattleGround].
Returns
uint32 maxTeamPlayerCount
    {
        Eluna::Push(L, bg->GetMaxPlayersPerTeam());
        return 1;
    }
References Eluna::Push().
GetMinLevel()
int LuaBattleGround::GetMinLevel (lua_State * L, BattleGround * bg)
Returns the minimum allowed [Player] level of the specific [BattleGround].
Returns
uint32 minLevel
    {
        Eluna::Push(L, bg->GetMinLevel());
        return 1;
    }
References Eluna::Push().
GetMinPlayers()
int LuaBattleGround::GetMinPlayers (lua_State * L, BattleGround * bg)
Returns the minimum allowed [Player] count of the specific [BattleGround].
Returns
uint32 minPlayerCount
    {
#ifndef AZEROTHCORE
        Eluna::Push(L, bg->GetMinPlayers());
#else
        Eluna::Push(L, bg->GetMaxPlayersPerTeam() * 2);
#endif
        return 1;
    }
References Eluna::Push().
GetMinPlayersPerTeam()
int LuaBattleGround::GetMinPlayersPerTeam (lua_State * L, BattleGround * bg)
Returns the minimum allowed [Player] count per team of the specific [BattleGround].
Returns
uint32 minTeamPlayerCount
    {
        Eluna::Push(L, bg->GetMinPlayersPerTeam());
        return 1;
    }
References Eluna::Push().
GetName()
int LuaBattleGround::GetName (lua_State * L, BattleGround * bg)
Returns the name of the [BattleGround].
Returns
string name
    {
        Eluna::Push(L, bg->GetName());
        return 1;
    }
References Eluna::Push().
GetStatus()
int LuaBattleGround::GetStatus (lua_State * L, BattleGround * bg)
Returns the status of the specific [BattleGround].
Returns
[BattleGroundStatus] status
    {
        Eluna::Push(L, bg->GetStatus());
        return 1;
    }
References Eluna::Push().
GetTypeId()
int LuaBattleGround::GetTypeId (lua_State * L, BattleGround * bg)
Returns the type ID of the [BattleGround].
Returns
[BattleGroundTypeId] typeId
    {
#ifndef AZEROTHCORE
        Eluna::Push(L, bg->GetTypeID());
#else
        Eluna::Push(L, bg->GetBgTypeID());
#endif
        return 1;
    }
References Eluna::Push().
GetWinner()
int LuaBattleGround::GetWinner (lua_State * L, BattleGround * bg)
Returns the winning team of the specific [BattleGround].
Returns
[Team] team
    {
        Eluna::Push(L, bg->GetWinner());
        return 1;
    }
References Eluna::Push().