AzerothCore Doxygen
UpdatableMapObject Class Reference
#include "Object.h"
Public Types
enum UpdateState : uint8 {
NotUpdating ,
PendingAdd ,
Updating
}
Protected Member Functions
UpdatableMapObject ()
Private Member Functions
void SetMapUpdateListOffset (std::size_t const offset)
size_t GetMapUpdateListOffset () const
void SetUpdateState (UpdateState state)
UpdateState GetUpdateState () const
Private Attributes
std::size_t _mapUpdateListOffset
UpdateState _mapUpdateState
Friends
class Map
Detailed Description
Member Enumeration Documentation
UpdateState
enum UpdatableMapObject::UpdateState : uint8
Enumerator
NotUpdating
PendingAdd
Updating
    {
        NotUpdating,
        PendingAdd,
        Updating
    };
Constructor & Destructor Documentation
UpdatableMapObject()
UpdatableMapObject::UpdatableMapObject () inline protected
: _mapUpdateListOffset(0), _mapUpdateState(NotUpdating) { }
Member Function Documentation
GetMapUpdateListOffset()
size_t UpdatableMapObject::GetMapUpdateListOffset () const inline private
    {
        ASSERT(_mapUpdateState == Updating, "Attempted to get update list offset when object is not in map update list");
        return _mapUpdateListOffset;
    }
References _mapUpdateListOffset, _mapUpdateState, ASSERT, and Updating.
Referenced by Map::_RemoveObjectFromUpdateList().
GetUpdateState()
UpdateState UpdatableMapObject::GetUpdateState () const inline private
    {
        return _mapUpdateState;
    }
References _mapUpdateState.
Referenced by Map::_AddObjectToUpdateList(), Map::_RemoveObjectFromUpdateList(), Map::AddObjectToPendingUpdateList(), and Map::RemoveObjectFromMapUpdateList().
SetMapUpdateListOffset()
void UpdatableMapObject::SetMapUpdateListOffset (std::size_t const offset) inline private
    {
        ASSERT(_mapUpdateState == Updating, "Attempted to set update list offset when object is not in map update list");
        _mapUpdateListOffset = offset;
    }
References _mapUpdateListOffset, _mapUpdateState, ASSERT, and Updating.
Referenced by Map::_AddObjectToUpdateList().
SetUpdateState()
void UpdatableMapObject::SetUpdateState (UpdateState state) inline private
    {
        _mapUpdateState = state;
    }
References _mapUpdateState.
Referenced by Map::_AddObjectToUpdateList(), Map::_RemoveObjectFromUpdateList(), and Map::AddObjectToPendingUpdateList().
Friends And Related Symbol Documentation
Map
friend class Map friend
Member Data Documentation
_mapUpdateListOffset
std::size_t UpdatableMapObject::_mapUpdateListOffset private
Referenced by GetMapUpdateListOffset(), and SetMapUpdateListOffset().
_mapUpdateState
UpdateState UpdatableMapObject::_mapUpdateState private
Referenced by GetMapUpdateListOffset(), GetUpdateState(), SetMapUpdateListOffset(), and SetUpdateState().
The documentation for this class was generated from the following file:
azerothcore-wotlk/src/server/game/Entities/Object/Object.h