AzerothCore Doxygen
HealInfoStub Class Reference
Lightweight stub for HealInfo.
#include "DamageHealInfoStub.h"
Public Member Functions
HealInfoStub ()=default
HealInfoStub (uint32_t heal, uint32_t effectiveHeal, uint32_t absorb, SpellInfo const *spellInfo=nullptr)
virtual ~HealInfoStub ()=default
uint32_t GetHeal () const
uint32_t GetEffectiveHeal () const
uint32_t GetAbsorb () const
uint32_t GetOverheal () const
void SetHeal (uint32_t heal)
void SetEffectiveHeal (uint32_t effectiveHeal)
void SetAbsorb (uint32_t absorb)
SpellInfo const * GetSpellInfo () const
void SetSpellInfo (SpellInfo const *spellInfo)
uint32_t GetHitMask () const
void SetHitMask (uint32_t hitMask)
Private Attributes
uint32_t _heal = 0
uint32_t _effectiveHeal = 0
uint32_t _absorb = 0
uint32_t _hitMask = 0
SpellInfo const * _spellInfo = nullptr
Detailed Description
Lightweight stub for HealInfo.
Mirrors the key fields of HealInfo for proc testing.
Constructor & Destructor Documentation
HealInfoStub() [1/2]
HealInfoStub::HealInfoStub () default
HealInfoStub() [2/2]
HealInfoStub::HealInfoStub (uint32_t heal, uint32_t effectiveHeal, uint32_t absorb, SpellInfo const * spellInfo = nullptr) inline
        : _heal(heal)
        , _effectiveHeal(effectiveHeal)
        , _absorb(absorb)
        , _spellInfo(spellInfo)
    {}
~HealInfoStub()
virtual HealInfoStub::~HealInfoStub () virtual default
Member Function Documentation
GetAbsorb()
uint32_t HealInfoStub::GetAbsorb () const inline
{ return _absorb; }
References _absorb.
GetEffectiveHeal()
uint32_t HealInfoStub::GetEffectiveHeal () const inline
{ return _effectiveHeal; }
References _effectiveHeal.
GetHeal()
uint32_t HealInfoStub::GetHeal () const inline
{ return _heal; }
References _heal.
Referenced by HealInfoStubBuilder::WithOverheal().
GetHitMask()
uint32_t HealInfoStub::GetHitMask () const inline
{ return _hitMask; }
References _hitMask.
GetOverheal()
uint32_t HealInfoStub::GetOverheal () const inline
{ return _heal > _effectiveHeal ? _heal - _effectiveHeal : 0; }
References _effectiveHeal, and _heal.
GetSpellInfo()
SpellInfo const * HealInfoStub::GetSpellInfo () const inline
{ return _spellInfo; }
References _spellInfo.
SetAbsorb()
void HealInfoStub::SetAbsorb (uint32_t absorb) inline
{ _absorb = absorb; }
References _absorb.
Referenced by HealInfoStubBuilder::WithAbsorb().
SetEffectiveHeal()
void HealInfoStub::SetEffectiveHeal (uint32_t effectiveHeal) inline
{ _effectiveHeal = effectiveHeal; }
References _effectiveHeal.
Referenced by HealInfoStubBuilder::WithEffectiveHeal(), HealInfoStubBuilder::WithHeal(), ProcTestContext::WithHeal(), and HealInfoStubBuilder::WithOverheal().
SetHeal()
void HealInfoStub::SetHeal (uint32_t heal) inline
{ _heal = heal; }
References _heal.
Referenced by HealInfoStubBuilder::WithHeal(), and ProcTestContext::WithHeal().
SetHitMask()
void HealInfoStub::SetHitMask (uint32_t hitMask) inline
{ _hitMask = hitMask; }
References _hitMask.
Referenced by ProcTestContext::WithCriticalHit(), HealInfoStubBuilder::WithHitMask(), and ProcTestContext::WithNormalHit().
SetSpellInfo()
void HealInfoStub::SetSpellInfo (SpellInfo const * spellInfo) inline
{ _spellInfo = spellInfo; }
References _spellInfo.
Referenced by HealInfoStubBuilder::WithSpellInfo().
Member Data Documentation
_absorb
uint32_t HealInfoStub::_absorb = 0 private
Referenced by GetAbsorb(), and SetAbsorb().
_effectiveHeal
uint32_t HealInfoStub::_effectiveHeal = 0 private
Referenced by GetEffectiveHeal(), GetOverheal(), and SetEffectiveHeal().
_heal
uint32_t HealInfoStub::_heal = 0 private
Referenced by GetHeal(), GetOverheal(), and SetHeal().
_hitMask
uint32_t HealInfoStub::_hitMask = 0 private
Referenced by GetHitMask(), and SetHitMask().
_spellInfo
SpellInfo const* HealInfoStub::_spellInfo = nullptr private
Referenced by GetSpellInfo(), and SetSpellInfo().
The documentation for this class was generated from the following file:
azerothcore-wotlk/src/test/mocks/DamageHealInfoStub.h