AzerothCore Doxygen
boss_flame_leviathan Struct Reference
Public Member Functions
boss_flame_leviathan (Creature *pCreature)
void BindPlayers ()
void RadioSay (uint8 textid)
void ActivateTowers ()
void TurnGates (bool _start, bool _death)
void TurnHealStations (bool _apply)
void ScheduleEvents ()
void SummonTowerHelpers (uint8 towerId)
void JustReachedHome () override
void MoveInLineOfSight (Unit *) override
void JustSummoned (Creature *cr) override
void SummonedCreatureDespawn (Creature *cr) override
void SpellHit (Unit *caster, SpellInfo const *spellInfo) override
void JustDied (Unit *) override
void KilledUnit (Unit *who) override
void SpellHitTarget (Unit *target, SpellInfo const *spell) override
void AttackStart (Unit *who) override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void InitializeAI () override
void Reset () override
uint32 GetData (uint32 param) const override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void DoAction (int32 action) override
Public Member Functions inherited from BossAI
BossAI (Creature *creature, uint32 bossId)
~BossAI () override
bool CanRespawn () override
void OnSpellCastFinished (SpellInfo const *spell, SpellFinishReason reason) override
void DamageTaken (Unit *attacker, uint32 &damage, DamageEffectType damagetype, SpellSchoolMask damageSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void JustSummoned (Creature *summon) override
void SummonedCreatureDespawn (Creature *summon) override
void SummonedCreatureDespawnAll () override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void ScheduleHealthCheckEvent (uint32 healthPct, std::function< void()> exec, bool allowedWhileCasting=true)
Executes a function once the creature reaches the defined health point percent.
void ScheduleHealthCheckEvent (std::initializer_list< uint8 > healthPct, std::function< void()> exec, bool allowedWhileCasting=true)
void ProcessHealthCheck ()
void ScheduleEnrageTimer (uint32 spellId, Milliseconds timer, uint8 textId=0)
virtual void ExecuteEvent (uint32)
virtual void ScheduleTasks ()
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER) override
void JustDied (Unit *) override
void JustReachedHome () override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportPlayer (Unit *unit, Position pos)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool IsUniqueTimedEventDone (uint32 id) const
void SetUniqueTimedEventDone (uint32 id)
void ResetUniqueTimedEvent (uint32 id)
void ClearUniqueTimedEventsDone ()
void ScheduleTimedEvent (Milliseconds timerMin, Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0ms, uint32 uniqueId=0)
void ScheduleTimedEvent (Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0ms, uint32 uniqueId=0)
void ScheduleUniqueTimedEvent (Milliseconds timer, std::function< void()> exec, uint32 uniqueId)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
void SetInvincibility (bool apply)
bool IsInvincible () const
void SetAutoAttackAllowed (bool allow)
bool IsAutoAttackAllowed () const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0ms)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureEvade (Creature *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
int32 VisualizeBoundary (uint32 duration, Unit *owner=nullptr, bool fill=false, bool checkZ=false) const
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
virtual void DistancingStarted ()
virtual void DistancingEnded ()
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid const &, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage to any victim (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Public Attributes
Vehicle * vehicle
uint32 _startTimer
uint32 _speakTimer
uint8 _towersCount
bool _shutdown
uint32 _destroyedTurretCount
Public Attributes inherited from BossAI
float callForHelpRange
InstanceScript *const instance
Public Attributes inherited from ScriptedAI
Creature * me
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from BossAI
void _Reset ()
void _JustEngagedWith ()
void _JustDied ()
void _JustReachedHome ()
void _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
void TeleportCheaters ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from BossAI
SummonList summons
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
boss_flame_leviathan()
boss_flame_leviathan::boss_flame_leviathan (Creature * pCreature) inline
                                              : BossAI(pCreature, BOSS_LEVIATHAN), vehicle(me->GetVehicleKit())
    {
        assert(vehicle);
    }
References vehicle.
Member Function Documentation
ActivateTowers()
void boss_flame_leviathan::ActivateTowers ()
{
    _towersCount = 0;
    me->ResetLootMode();
    for (uint32 i = EVENT_TOWER_OF_LIFE_DESTROYED; i <= EVENT_TOWER_OF_FLAMES_DESTROYED; ++i)
    {
        if (instance->GetData(i))
        {
            ++_towersCount;
            me->AddLootMode(1 << _towersCount);
            switch (i)
            {
                case EVENT_TOWER_OF_LIFE_DESTROYED:
                    me->AddAura(SPELL_TOWER_OF_LIFE, me);
                    events.RescheduleEvent(EVENT_FREYA, 30s);
                    break;
                case EVENT_TOWER_OF_STORM_DESTROYED:
                    me->AddAura(SPELL_TOWER_OF_STORMS, me);
                    events.RescheduleEvent(EVENT_THORIMS_HAMMER, 1min);
                    break;
                case EVENT_TOWER_OF_FROST_DESTROYED:
                    me->AddAura(SPELL_TOWER_OF_FROST, me);
                    events.RescheduleEvent(EVENT_HODIRS_FURY, 20s);
                    break;
                case EVENT_TOWER_OF_FLAMES_DESTROYED:
                    me->AddAura(SPELL_TOWER_OF_FLAMES, me);
                    events.RescheduleEvent(EVENT_MIMIRONS_INFERNO, 42s);
                    break;
            }
        }
    }
}
References _towersCount, Unit::AddAura(), Creature::AddLootMode(), EVENT_FREYA, EVENT_HODIRS_FURY, EVENT_MIMIRONS_INFERNO, EVENT_THORIMS_HAMMER, EVENT_TOWER_OF_FLAMES_DESTROYED, EVENT_TOWER_OF_FROST_DESTROYED, EVENT_TOWER_OF_LIFE_DESTROYED, EVENT_TOWER_OF_STORM_DESTROYED, ZoneScript::GetData(), BossAI::instance, ScriptedAI::me, Creature::ResetLootMode(), SPELL_TOWER_OF_FLAMES, SPELL_TOWER_OF_FROST, SPELL_TOWER_OF_LIFE, and SPELL_TOWER_OF_STORMS.
Referenced by JustEngagedWith().
AttackStart()
void boss_flame_leviathan::AttackStart (Unit * who) inline override virtual
Reimplemented from UnitAI.
    {
        if (Unit* veh = who->GetVehicleBase())
            BossAI::AttackStart(veh);
        else
            BossAI::AttackStart(who);
    }
References UnitAI::AttackStart(), and Unit::GetVehicleBase().
BindPlayers()
void boss_flame_leviathan::BindPlayers ()
{
    me->GetMap()->ToInstanceMap()->PermBindAllPlayers();
}
References WorldObject::GetMap(), ScriptedAI::me, InstanceMap::PermBindAllPlayers(), and Map::ToInstanceMap().
Referenced by JustDied(), and JustEngagedWith().
DoAction()
void boss_flame_leviathan::DoAction (int32 action) inline override virtual
Reimplemented from UnitAI.
    {
        if (action == ACTION_DESTROYED_TURRET)
        {
            ++_destroyedTurretCount;
            if (_destroyedTurretCount == RAID_MODE<uint32>(2, 4))
            {
                _destroyedTurretCount = 0;
                me->CastSpell(me, SPELL_SYSTEMS_SHUTDOWN, true);
            }
        }
    }
References _destroyedTurretCount, ACTION_DESTROYED_TURRET, Unit::CastSpell(), ScriptedAI::me, and SPELL_SYSTEMS_SHUTDOWN.
GetData()
uint32 boss_flame_leviathan::GetData (uint32 param) const inline override virtual
Reimplemented from UnitAI.
    {
        if (param == DATA_GET_TOWER_COUNT)
            return _towersCount;
        if (param == DATA_GET_SHUTDOWN)
            return !_shutdown;
        return 0;
    }
References _shutdown, _towersCount, DATA_GET_SHUTDOWN, and DATA_GET_TOWER_COUNT.
InitializeAI()
void boss_flame_leviathan::InitializeAI () inline override virtual
Reimplemented from UnitAI.
    {
        if (instance->GetBossState(BOSS_LEVIATHAN) == SPECIAL)
        {
            me->SetHomePosition(homePos);
            me->UpdatePosition(homePos);
            me->StopMovingOnCurrentPos();
        }
        BossAI::InitializeAI();
    }
References BOSS_LEVIATHAN, InstanceScript::GetBossState(), homePos, UnitAI::InitializeAI(), BossAI::instance, ScriptedAI::me, Creature::SetHomePosition(), SPECIAL, Unit::StopMovingOnCurrentPos(), and Unit::UpdatePosition().
JustDied()
void boss_flame_leviathan::JustDied (Unit *) override virtual
Reimplemented from CreatureAI.
{
    // Despawn Lashers, do before summons clear
    summons.DoAction(ACTION_DESPAWN_ADDS);
    summons.DespawnAll();
    instance->SetBossState(BOSS_LEVIATHAN, DONE);
    instance->SetData(DATA_VEHICLE_SPAWN, VEHICLE_POS_NONE);
    Talk(FLAME_LEVIATHAN_SAY_DEATH);
    TurnGates(false, true);
    BindPlayers();
}
References ACTION_DESPAWN_ADDS, BindPlayers(), BOSS_LEVIATHAN, DATA_VEHICLE_SPAWN, SummonList::DespawnAll(), SummonList::DoAction(), DONE, FLAME_LEVIATHAN_SAY_DEATH, BossAI::instance, InstanceScript::SetBossState(), ZoneScript::SetData(), BossAI::summons, TurnGates(), and VEHICLE_POS_NONE.
JustEngagedWith()
void boss_flame_leviathan::JustEngagedWith (Unit *) inline override virtual
Called for reaction when initially engaged.
Reimplemented from CreatureAI.
    {
        ScheduleEvents();
        Talk(FLAME_LEVIATHAN_SAY_AGGRO);
        me->setActive(true);
        me->SetHomePosition(homePos);
        TurnHealStations(false);
        ActivateTowers();
        instance->SetBossState(BOSS_LEVIATHAN, SPECIAL);
        BindPlayers();
        me->SetInCombatWithZone();
        if (!_startTimer)
        {
            TurnGates(true, false);
        }
    }
References _startTimer, ActivateTowers(), BindPlayers(), BOSS_LEVIATHAN, FLAME_LEVIATHAN_SAY_AGGRO, homePos, BossAI::instance, ScriptedAI::me, ScheduleEvents(), WorldObject::setActive(), InstanceScript::SetBossState(), Creature::SetHomePosition(), Creature::SetInCombatWithZone(), SPECIAL, TurnGates(), and TurnHealStations().
JustReachedHome()
void boss_flame_leviathan::JustReachedHome () inline override virtual
Reimplemented from CreatureAI.
    {
        _JustReachedHome();
        // For achievement
        instance->SetData(DATA_UNBROKEN_ACHIEVEMENT, 0);
        me->setActive(false);
    }
References BossAI::_JustReachedHome(), DATA_UNBROKEN_ACHIEVEMENT, BossAI::instance, ScriptedAI::me, WorldObject::setActive(), and ZoneScript::SetData().
JustSummoned()
void boss_flame_leviathan::JustSummoned (Creature * cr) inline override virtual
Reimplemented from CreatureAI.
    {
        if (cr->GetEntry() != NPC_FLAME_LEVIATHAN_TURRET && cr->GetEntry() != NPC_SEAT)
            summons.Summon(cr);
    }
References Object::GetEntry(), NPC_FLAME_LEVIATHAN_TURRET, NPC_SEAT, SummonList::Summon(), and BossAI::summons.
KilledUnit()
void boss_flame_leviathan::KilledUnit (Unit * who) override virtual
Reimplemented from CreatureAI.
{
    if (who == me->GetVictim())
        events.RescheduleEvent(EVENT_PURSUE, 0ms);
    if (who->IsPlayer())
        Talk(FLAME_LEVIATHAN_SAY_SLAY);
}
References EVENT_PURSUE, FLAME_LEVIATHAN_SAY_SLAY, Unit::GetVictim(), Object::IsPlayer(), and ScriptedAI::me.
MoveInLineOfSight()
void boss_flame_leviathan::MoveInLineOfSight (Unit *) inline override virtual
Reimplemented from CreatureAI.
{}
RadioSay()
void boss_flame_leviathan::RadioSay (uint8 textid)
{
    if (Creature* r = me->SummonCreature(NPC_BRANN_RADIO, me->GetPositionX() - 150, me->GetPositionY(), me->GetPositionZ(), me->GetOrientation(), TEMPSUMMON_TIMED_DESPAWN, 5000))
    {
        r->AI()->Talk(textid);
    }
}
References Position::GetOrientation(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), ScriptedAI::me, NPC_BRANN_RADIO, WorldObject::SummonCreature(), and TEMPSUMMON_TIMED_DESPAWN.
Referenced by UpdateAI().
Reset()
void boss_flame_leviathan::Reset () inline override virtual
Reimplemented from UnitAI.
    {
        // Special immunity case
        me->CastSpell(me, SPELL_INVIS_AND_STEALTH_DETECT, true);
        me->ApplySpellImmune(0, IMMUNITY_STATE, SPELL_AURA_USE_NORMAL_MOVEMENT_SPEED, true);
        summons.DoAction(ACTION_DESPAWN_ADDS);
        summons.DespawnAll();
        events.Reset();
        _shutdown = false;
        _startTimer = 1;
        _speakTimer = 0;
        _towersCount = 0;
        _destroyedTurretCount = 0;
        if (instance->GetBossState(BOSS_LEVIATHAN) != SPECIAL)
        {
            instance->SetBossState(BOSS_LEVIATHAN, NOT_STARTED);
            me->SetUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
        }
        else
        {
            me->RemoveUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
            instance->SetData(DATA_VEHICLE_SPAWN, VEHICLE_POS_LEVIATHAN);
            _startTimer = 0;
        }
        TurnGates(false, false);
        TurnHealStations(true);
    }
References _destroyedTurretCount, _shutdown, _speakTimer, _startTimer, _towersCount, ACTION_DESPAWN_ADDS, Unit::ApplySpellImmune(), BOSS_LEVIATHAN, Unit::CastSpell(), DATA_VEHICLE_SPAWN, SummonList::DespawnAll(), SummonList::DoAction(), InstanceScript::GetBossState(), IMMUNITY_STATE, BossAI::instance, ScriptedAI::me, NOT_STARTED, Unit::RemoveUnitFlag(), InstanceScript::SetBossState(), ZoneScript::SetData(), Unit::SetUnitFlag(), SPECIAL, SPELL_AURA_USE_NORMAL_MOVEMENT_SPEED, SPELL_INVIS_AND_STEALTH_DETECT, BossAI::summons, TurnGates(), TurnHealStations(), UNIT_FLAG_NON_ATTACKABLE, and VEHICLE_POS_LEVIATHAN.
ScheduleEvents()
void boss_flame_leviathan::ScheduleEvents ()
{
    events.RescheduleEvent(EVENT_MISSILE, 5s);
    events.RescheduleEvent(EVENT_VENT, 20s);
    events.RescheduleEvent(EVENT_SPEED, 15s);
    events.RescheduleEvent(EVENT_SUMMON, 10s);
    events.RescheduleEvent(EVENT_SOUND_BEGINNING, 10s);
    events.RescheduleEvent(EVENT_POSITION_CHECK, 5s);
    events.RescheduleEvent(EVENT_PURSUE, 0ms);
}
References EVENT_MISSILE, EVENT_POSITION_CHECK, EVENT_PURSUE, EVENT_SOUND_BEGINNING, EVENT_SPEED, EVENT_SUMMON, and EVENT_VENT.
Referenced by JustEngagedWith().
SpellHit()
void boss_flame_leviathan::SpellHit (Unit * caster, SpellInfo const * spellInfo) override virtual
Reimplemented from CreatureAI.
{
    if (spellInfo->Id == SPELL_SYSTEMS_SHUTDOWN)
    {
        _shutdown = true; // ACHIEVEMENT
        Talk(FLAME_LEVIATHAN_EMOTE_OVERLOAD);
        Talk(FLAME_LEVIATHAN_EMOTE_REPAIR);
        Talk(FLAME_LEVIATHAN_SAY_OVERLOAD);
        events.DelayEvents(21ms);
        events.ScheduleEvent(EVENT_REINSTALL, 20ms);
    }
    else if (spellInfo->Id == 62522 /*SPELL_ELECTROSHOCK*/)
        me->InterruptNonMeleeSpells(false);
}
References _shutdown, EVENT_REINSTALL, FLAME_LEVIATHAN_EMOTE_OVERLOAD, FLAME_LEVIATHAN_EMOTE_REPAIR, FLAME_LEVIATHAN_SAY_OVERLOAD, SpellInfo::Id, Unit::InterruptNonMeleeSpells(), ScriptedAI::me, and SPELL_SYSTEMS_SHUTDOWN.
SpellHitTarget()
void boss_flame_leviathan::SpellHitTarget (Unit * target, SpellInfo const * spell) override virtual
Reimplemented from CreatureAI.
{
    if (spell->Id != SPELL_PURSUED)
        return;
    for (SeatMap::const_iterator itr = target->GetVehicleKit()->Seats.begin(); itr != target->GetVehicleKit()->Seats.end(); ++itr)
    {
        if (Player* passenger = ObjectAccessor::GetPlayer(*me, itr->second.Passenger.Guid))
        {
            Talk(FLAME_LEVIATHAN_EMOTE_PURSUE, passenger);
            return;
        }
    }
}
References FLAME_LEVIATHAN_EMOTE_PURSUE, ObjectAccessor::GetPlayer(), Unit::GetVehicleKit(), SpellInfo::Id, ScriptedAI::me, Vehicle::Seats, and SPELL_PURSUED.
SummonedCreatureDespawn()
void boss_flame_leviathan::SummonedCreatureDespawn (Creature * cr) inline override virtual
Reimplemented from CreatureAI.
{ summons.Despawn(cr); }
References SummonList::Despawn(), and BossAI::summons.
SummonTowerHelpers()
void boss_flame_leviathan::SummonTowerHelpers (uint8 towerId)
{
    if (towerId == TOWER_OF_LIFE)
    {
        me->SummonCreature(NPC_FREYA_WARD_TARGET, 374, -141, 411, 0, TEMPSUMMON_MANUAL_DESPAWN);
        me->SummonCreature(NPC_FREYA_WARD, 374, -141, 411 + 40, 0, TEMPSUMMON_MANUAL_DESPAWN);
        me->SummonCreature(NPC_FREYA_WARD_TARGET, 382.9f, 74, 411.6f, 0, TEMPSUMMON_MANUAL_DESPAWN);
        me->SummonCreature(NPC_FREYA_WARD, 382.9f, 74, 411.6f + 40, 0, TEMPSUMMON_MANUAL_DESPAWN);
        me->SummonCreature(NPC_FREYA_WARD_TARGET, 159.4f, 64.1f, 409.8f, 0, TEMPSUMMON_MANUAL_DESPAWN);
        me->SummonCreature(NPC_FREYA_WARD, 159.4f, 64.1f, 409.8f + 40, 0, TEMPSUMMON_MANUAL_DESPAWN);
        me->SummonCreature(NPC_FREYA_WARD_TARGET, 157.7f, -140.26f, 409.8f, 0, TEMPSUMMON_MANUAL_DESPAWN);
        me->SummonCreature(NPC_FREYA_WARD, 157.7f, -140.26f, 409.8f + 40, 0, TEMPSUMMON_MANUAL_DESPAWN);
    }
    else if (towerId == TOWER_OF_FROST)
    {
        me->SummonCreature(NPC_HODIRS_FURY_TARGET, 343.4f, -77.5f, 409.8f, 0, TEMPSUMMON_MANUAL_DESPAWN);
        me->SummonCreature(NPC_HODIRS_FURY_TARGET, 222, 41, 409.8f, 0, TEMPSUMMON_MANUAL_DESPAWN);
    }
    else if (towerId == TOWER_OF_FLAMES)
    {
        me->SummonCreature(NPC_MIMIRONS_INFERNO_TARGET, 364.4f, -9.7f, 409.8f, 0, TEMPSUMMON_MANUAL_DESPAWN);
        //me->SummonCreature(NPC_MIMIRONS_INFERNO, 364.4f, -9.7f, 409.8f+40, 0, TEMPSUMMON_MANUAL_DESPAWN);
    }
    else if (towerId == TOWER_OF_STORMS)
    {
        for (uint8 i = 0; i < 8; ++i)
            me->SummonCreature(NPC_THORIM_HAMMER_TARGET, 157 + rand() % 200, -140 + rand() % 200, 409.8f, 0, TEMPSUMMON_TIMED_DESPAWN, 24000);
    }
}
References ScriptedAI::me, NPC_FREYA_WARD, NPC_FREYA_WARD_TARGET, NPC_HODIRS_FURY_TARGET, NPC_MIMIRONS_INFERNO_TARGET, NPC_THORIM_HAMMER_TARGET, WorldObject::SummonCreature(), TEMPSUMMON_MANUAL_DESPAWN, TEMPSUMMON_TIMED_DESPAWN, TOWER_OF_FLAMES, TOWER_OF_FROST, TOWER_OF_LIFE, and TOWER_OF_STORMS.
Referenced by UpdateAI().
TurnGates()
void boss_flame_leviathan::TurnGates (bool _start, bool _death)
{
    if (!instance)
        return;
    if (_start)
    {
        // first one is ALWAYS turned on, unless leviathan is beaten
        GameObject* go = nullptr;
        if ((go = instance->GetGameObject(DATA_LIGHTNING_WALL2)))
            go->SetGoState(GO_STATE_READY);
        if (instance->GetBossState(BOSS_LEVIATHAN) == NOT_STARTED)
            if ((go = instance->GetGameObject(DATA_LEVIATHAN_DOORS)))
                go->SetGoState(GO_STATE_ACTIVE_ALTERNATIVE);
    }
    else
    {
        GameObject* go = nullptr;
        if (_death)
            if ((go = instance->GetGameObject(DATA_LIGHTNING_WALL1)))
                go->SetGoState(GO_STATE_ACTIVE);
        if ((go = instance->GetGameObject(DATA_LIGHTNING_WALL2)))
            go->SetGoState(GO_STATE_ACTIVE);
        if ((go = instance->GetGameObject(DATA_LEVIATHAN_DOORS)))
        {
            if (instance->GetBossState(BOSS_LEVIATHAN) == SPECIAL || instance->GetBossState(BOSS_LEVIATHAN) == DONE)
                go->SetGoState(GO_STATE_ACTIVE_ALTERNATIVE);
            else
                go->SetGoState(GO_STATE_READY);
        }
    }
}
References BOSS_LEVIATHAN, DATA_LEVIATHAN_DOORS, DATA_LIGHTNING_WALL1, DATA_LIGHTNING_WALL2, DONE, InstanceScript::GetBossState(), InstanceScript::GetGameObject(), GO_STATE_ACTIVE, GO_STATE_ACTIVE_ALTERNATIVE, GO_STATE_READY, BossAI::instance, NOT_STARTED, GameObject::SetGoState(), and SPECIAL.
Referenced by JustDied(), JustEngagedWith(), Reset(), and UpdateAI().
TurnHealStations()
void boss_flame_leviathan::TurnHealStations (bool _apply)
{
    if (!instance)
        return;
    GameObject* go = nullptr;
    if (_apply)
    {
        if ((go = instance->GetGameObject(DATA_REPAIR_STATION1)))
            go->SetLootState(GO_READY);
        if ((go = instance->GetGameObject(DATA_REPAIR_STATION2)))
            go->SetLootState(GO_READY);
    }
    else
    {
        if ((go = instance->GetGameObject(DATA_REPAIR_STATION1)))
            go->SetLootState(GO_ACTIVATED);
        if ((go = instance->GetGameObject(DATA_REPAIR_STATION2)))
            go->SetLootState(GO_ACTIVATED);
    }
}
References DATA_REPAIR_STATION1, DATA_REPAIR_STATION2, InstanceScript::GetGameObject(), GO_ACTIVATED, GO_READY, BossAI::instance, and GameObject::SetLootState().
Referenced by JustEngagedWith(), and Reset().
UpdateAI()
void boss_flame_leviathan::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Implements UnitAI.
    {
        // THIS IS USED ONLY FOR FIRST ENGAGE!
        if (_startTimer)
        {
            _startTimer += diff;
            if (_startTimer >= 4000)
            {
                // Colossus dead, players in range
                if (me->FindNearestCreature(NPC_ULDUAR_COLOSSUS, 250.0f, true) || !SelectTargetFromPlayerList(250.0f))
                    _startTimer = 1;
                else
                {
                    _startTimer = 0;
                    _speakTimer = 1;
                }
            }
            return;
        }
        if (_speakTimer)
        {
            _speakTimer += diff;
            if (_speakTimer <= 10000)
            {
                _speakTimer = 10000;
                RadioSay(BRANN_RADIO_SAY_FL_START_0);
            }
            else if (_speakTimer > 16000 && _speakTimer < 20000)
            {
                _speakTimer = 20000;
                RadioSay(BRANN_RADIO_SAY_FL_START_1);
            }
            else if (_speakTimer > 24000 && _speakTimer < 40000)
            {
                _speakTimer = 40000;
                RadioSay(BRANN_RADIO_SAY_FL_START_2);
            }
            else if (_speakTimer > 41000 && _speakTimer < 60000)
            {
                me->RemoveUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
                TurnGates(true, false);
                me->GetMotionMaster()->MovePoint(0, homePos.GetPositionX(), homePos.GetPositionY(), homePos.GetPositionZ(), FORCED_MOVEMENT_NONE, 100.0f);
                _speakTimer = 60000;
            }
            else if (_speakTimer > 63500)
            {
                me->SetInCombatWithZone();
                if (!me->GetVictim())
                {
                    me->CastSpell(me, SPELL_PURSUED, false);
                    events.RescheduleEvent(EVENT_PURSUE, 31s);
                }
                _speakTimer = 0;
            }
            return;
        }
        if (!UpdateVictim())
            return;
        events.Update(diff);
        if (me->HasUnitState(UNIT_STATE_CASTING))
            return;
        switch (events.ExecuteEvent())
        {
            case EVENT_POSITION_CHECK:
                if (me->GetPositionX() > 450 || me->GetPositionX() < 120)
                {
                    EnterEvadeMode();
                    return;
                }
                events.Repeat(5s);
                break;
            case EVENT_PURSUE:
                Talk(FLAME_LEVIATHAN_SAY_PURSUE);
                me->CastSpell(me, SPELL_PURSUED, false);
                events.RescheduleEvent(EVENT_PURSUE, 31s);
                return;
            case EVENT_SPEED:
                me->CastSpell(me, SPELL_GATHERING_SPEED, false);
                events.Repeat(15s);
                return;
            case EVENT_MISSILE:
                me->CastSpell(me, SPELL_MISSILE_BARRAGE, true);
                events.Repeat(4s);
                return;
            case EVENT_VENT:
                me->CastSpell(me, SPELL_FLAME_VENTS, false);
                events.Repeat(20s);
                return;
            case EVENT_SUMMON:
                if (summons.size() < 20)
                    if (Creature* lift = DoSummonFlyer(NPC_MECHANOLIFT, me, 30.0f, 50.0f, 0))
                        lift->GetMotionMaster()->MoveRandom(100);
                events.Repeat(4s);
                return;
            case EVENT_SOUND_BEGINNING:
                if (_towersCount)
                    Talk(FLAME_LEVIATHAN_SAY_HARDMODE);
                else
                    Talk(FLAME_LEVIATHAN_SAY_TOWER_NONE);
                return;
            case EVENT_REINSTALL:
                for (uint8 i = RAID_MODE(0, 2); i < 4; ++i)
                    if (Unit* seat = vehicle->GetPassenger(i))
                        if (seat->IsCreature())
                            seat->ToCreature()->AI()->EnterEvadeMode();
                Talk(FLAME_LEVIATHAN_EMOTE_REACTIVATE);
                return;
            case EVENT_THORIMS_HAMMER:
                SummonTowerHelpers(TOWER_OF_STORMS);
                events.Repeat(1min, 2min);
                Talk(FLAME_LEVIATHAN_EMOTE_STORM);
                Talk(FLAME_LEVIATHAN_SAY_TOWER_STORM);
                return;
            case EVENT_FREYA:
                SummonTowerHelpers(TOWER_OF_LIFE);
                Talk(FLAME_LEVIATHAN_EMOTE_NATURE);
                Talk(FLAME_LEVIATHAN_SAY_TOWER_NATURE);
                return;
            case EVENT_MIMIRONS_INFERNO:
                SummonTowerHelpers(TOWER_OF_FLAMES);
                Talk(FLAME_LEVIATHAN_EMOTE_FLAME);
                Talk(FLAME_LEVIATHAN_SAY_TOWER_FLAME);
                return;
            case EVENT_HODIRS_FURY:
                SummonTowerHelpers(TOWER_OF_FROST);
                Talk(FLAME_LEVIATHAN_EMOTE_FROST);
                Talk(FLAME_LEVIATHAN_SAY_TOWER_FROST);
                return;
        }
        if (me->isAttackReady() && !me->HasUnitState(UNIT_STATE_STUNNED))
        {
            if (me->IsWithinCombatRange(me->GetVictim(), 15.0f))
            {
                me->CastSpell(me->GetVictim(), SPELL_BATTERING_RAM, false);
                me->resetAttackTimer();
            }
        }
    }
References _speakTimer, _startTimer, _towersCount, BRANN_RADIO_SAY_FL_START_0, BRANN_RADIO_SAY_FL_START_1, BRANN_RADIO_SAY_FL_START_2, Unit::CastSpell(), CreatureAI::DoSummonFlyer(), BossAI::EnterEvadeMode(), EVENT_FREYA, EVENT_HODIRS_FURY, EVENT_MIMIRONS_INFERNO, EVENT_MISSILE, EVENT_POSITION_CHECK, EVENT_PURSUE, EVENT_REINSTALL, EVENT_SOUND_BEGINNING, EVENT_SPEED, EVENT_SUMMON, EVENT_THORIMS_HAMMER, EVENT_VENT, WorldObject::FindNearestCreature(), FLAME_LEVIATHAN_EMOTE_FLAME, FLAME_LEVIATHAN_EMOTE_FROST, FLAME_LEVIATHAN_EMOTE_NATURE, FLAME_LEVIATHAN_EMOTE_REACTIVATE, FLAME_LEVIATHAN_EMOTE_STORM, FLAME_LEVIATHAN_SAY_HARDMODE, FLAME_LEVIATHAN_SAY_PURSUE, FLAME_LEVIATHAN_SAY_TOWER_FLAME, FLAME_LEVIATHAN_SAY_TOWER_FROST, FLAME_LEVIATHAN_SAY_TOWER_NATURE, FLAME_LEVIATHAN_SAY_TOWER_NONE, FLAME_LEVIATHAN_SAY_TOWER_STORM, FORCED_MOVEMENT_NONE, Unit::GetMotionMaster(), Vehicle::GetPassenger(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Unit::GetVictim(), Unit::HasUnitState(), homePos, Unit::isAttackReady(), Unit::IsWithinCombatRange(), ScriptedAI::me, MotionMaster::MovePoint(), NPC_MECHANOLIFT, NPC_ULDUAR_COLOSSUS, RadioSay(), ScriptedAI::RAID_MODE(), Unit::RemoveUnitFlag(), Unit::resetAttackTimer(), ScriptedAI::SelectTargetFromPlayerList(), Creature::SetInCombatWithZone(), SummonList::size(), SPELL_BATTERING_RAM, SPELL_FLAME_VENTS, SPELL_GATHERING_SPEED, SPELL_MISSILE_BARRAGE, SPELL_PURSUED, BossAI::summons, SummonTowerHelpers(), TOWER_OF_FLAMES, TOWER_OF_FROST, TOWER_OF_LIFE, TOWER_OF_STORMS, TurnGates(), UNIT_FLAG_NON_ATTACKABLE, UNIT_STATE_CASTING, UNIT_STATE_STUNNED, CreatureAI::UpdateVictim(), and vehicle.
Member Data Documentation
_destroyedTurretCount
uint32 boss_flame_leviathan::_destroyedTurretCount
Referenced by DoAction(), and Reset().
_shutdown
bool boss_flame_leviathan::_shutdown
Referenced by GetData(), Reset(), and SpellHit().
_speakTimer
uint32 boss_flame_leviathan::_speakTimer
Referenced by Reset(), and UpdateAI().
_startTimer
uint32 boss_flame_leviathan::_startTimer
Referenced by JustEngagedWith(), Reset(), and UpdateAI().
_towersCount
uint8 boss_flame_leviathan::_towersCount
Referenced by ActivateTowers(), GetData(), Reset(), and UpdateAI().
vehicle
Vehicle* boss_flame_leviathan::vehicle
Referenced by boss_flame_leviathan(), and UpdateAI().
The documentation for this struct was generated from the following file:
azerothcore-wotlk/src/server/scripts/Northrend/Ulduar/Ulduar/boss_flame_leviathan.cpp