AzerothCore Doxygen
LuaGameObject Namespace Reference
Functions
int HasQuest (lua_State *L, GameObject *go)
int IsSpawned (lua_State *L, GameObject *go)
int IsTransport (lua_State *L, GameObject *go)
int IsActive (lua_State *L, GameObject *go)
int GetDisplayId (lua_State *L, GameObject *go)
int GetGoState (lua_State *L, GameObject *go)
int GetLootState (lua_State *L, GameObject *go)
int GetLootRecipient (lua_State *L, GameObject *go)
int GetLootRecipientGroup (lua_State *L, GameObject *go)
int GetDBTableGUIDLow (lua_State *L, GameObject *go)
int SetGoState (lua_State *L, GameObject *go)
int SetLootState (lua_State *L, GameObject *go)
int AddLoot (lua_State *L, GameObject *go)
int SaveToDB (lua_State *, GameObject *go)
int RemoveFromWorld (lua_State *L, GameObject *go)
int UseDoorOrButton (lua_State *L, GameObject *go)
int Despawn (lua_State *, GameObject *go)
int Respawn (lua_State *, GameObject *go)
int SetRespawnTime (lua_State *L, GameObject *go)
Function Documentation
AddLoot()
int LuaGameObject::AddLoot (lua_State * L, GameObject * go)
Adds an [Item] to the loot of a [GameObject] Requires an gameobject with loot_template set to 0.
Parameters
uint32 entry : The entry of the [Item]
uint32 amount = 1 : amount of the [Item] to add to the loot
Returns
uint32 itemGUIDlow : low GUID of the [Item]
    {
        int i = 1;
        int argAmount = lua_gettop(L);
#if defined TRINITY || defined AZEROTHCORE
        CharacterDatabaseTransaction trans = CharacterDatabase.BeginTransaction();
#endif
        uint8 addedItems = 0;
        while (i + 2 <= argAmount)
        {
            uint32 entry = Eluna::CHECKVAL<uint32>(L, ++i);
            uint32 amount = Eluna::CHECKVAL<uint32>(L, ++i);
#if defined TRINITY || AZEROTHCORE
            ItemTemplate const* item_proto = eObjectMgr->GetItemTemplate(entry);
#else
            ItemTemplate const* item_proto = ObjectMgr::GetItemPrototype(entry);
#endif
            if (!item_proto)
            {
                luaL_error(L, "Item entry %d does not exist", entry);
                continue;
            }
            if (amount < 1 || (item_proto->MaxCount > 0 && amount > uint32(item_proto->MaxCount)))
            {
                luaL_error(L, "Item entry %d has invalid amount %d", entry, amount);
                continue;
            }
            if (Item* item = Item::CreateItem(entry, amount))
            {
#if defined TRINITY || AZEROTHCORE
                item->SaveToDB(trans);
#else
                item->SaveToDB();
#endif
                LootStoreItem storeItem(item->GetEntry(), 0, 100, 0, LOOT_MODE_DEFAULT, 0, item->GetCount(), item->GetCount());
                go->loot.AddItem(storeItem);
#if defined TRINITY || AZEROTHCORE
                Eluna::Push(L, item->GetGUID().GetCounter());
#else
                Eluna::Push(L, item->GetGUIDLow());
#endif
                ++addedItems;
            }
        }
#if defined TRINITY || AZEROTHCORE
        CharacterDatabase.CommitTransaction(trans);
#endif
        return addedItems;
    }
References Loot::AddItem(), CharacterDatabase, Item::CreateItem(), eObjectMgr, GameObject::loot, LOOT_MODE_DEFAULT, lua_gettop(), luaL_error(), ItemTemplate::MaxCount, and Eluna::Push().
Despawn()
int LuaGameObject::Despawn (lua_State * , GameObject * go)
Despawns a [GameObject]
The gameobject may be automatically respawned by the core
    {
        go->SetLootState(GO_JUST_DEACTIVATED);
        return 0;
    }
References GO_JUST_DEACTIVATED, and GameObject::SetLootState().
GetDBTableGUIDLow()
int LuaGameObject::GetDBTableGUIDLow (lua_State * L, GameObject * go)
Returns the guid of the [GameObject] that is used as the ID in the database
Returns
uint32 dbguid
    {
#if defined(TRINITY) || defined(AZEROTHCORE)
        Eluna::Push(L, go->GetSpawnId());
#else
        // on mangos based this is same as lowguid
        Eluna::Push(L, go->GetGUIDLow());
#endif
        return 1;
    }
References GameObject::GetSpawnId(), and Eluna::Push().
GetDisplayId()
int LuaGameObject::GetDisplayId (lua_State * L, GameObject * go)
Returns display ID of the [GameObject]
Returns
uint32 displayId
    {
        Eluna::Push(L, go->GetDisplayId());
        return 1;
    }
References GameObject::GetDisplayId(), and Eluna::Push().
GetGoState()
int LuaGameObject::GetGoState (lua_State * L, GameObject * go)
Returns the state of a [GameObject] Below are client side [GOState]s off of 3.3.5a
enum GOState
{
    GO_STATE_ACTIVE             = 0,                        // show in world as used and not reset (closed door open)
    GO_STATE_READY              = 1,                        // show in world as ready (closed door close)
    GO_STATE_ACTIVE_ALTERNATIVE = 2                         // show in world as used in alt way and not reset (closed door open by cannon fire)
};
Returns
[GOState] goState
    {
        Eluna::Push(L, go->GetGoState());
        return 1;
    }
References GameObject::GetGoState(), and Eluna::Push().
GetLootRecipient()
int LuaGameObject::GetLootRecipient (lua_State * L, GameObject * go)
Returns the [Player] that can loot the [GameObject]
Not the original looter and may be nil.
Returns
[Player] player
    {
        Eluna::Push(L, go->GetLootRecipient());
        return 1;
    }
References GameObject::GetLootRecipient(), and Eluna::Push().
GetLootRecipientGroup()
int LuaGameObject::GetLootRecipientGroup (lua_State * L, GameObject * go)
Returns the [Group] that can loot the [GameObject]
Not the original looter and may be nil.
Returns
[Group] group
    {
#if defined TRINITY || AZEROTHCORE
        Eluna::Push(L, go->GetLootRecipientGroup());
#else
        Eluna::Push(L, go->GetGroupLootRecipient());
#endif
        return 1;
    }
References GameObject::GetLootRecipientGroup(), and Eluna::Push().
GetLootState()
int LuaGameObject::GetLootState (lua_State * L, GameObject * go)
Returns the [LootState] of a [GameObject] Below are [LootState]s off of 3.3.5a
enum LootState
{
    GO_NOT_READY = 0,
    GO_READY,                                               // can be ready but despawned, and then not possible activate until spawn
    GO_ACTIVATED,
    GO_JUST_DEACTIVATED
};
Returns
[LootState] lootState
    {
        Eluna::Push(L, go->getLootState());
        return 1;
    }
References GameObject::getLootState(), and Eluna::Push().
HasQuest()
int LuaGameObject::HasQuest (lua_State * L, GameObject * go)
Returns 'true' if the [GameObject] can give the specified [Quest]
Parameters
uint32 questId : quest entry Id to check
Returns
bool hasQuest
    {
        uint32 questId = Eluna::CHECKVAL<uint32>(L, 2);
#if defined TRINITY || AZEROTHCORE
        Eluna::Push(L, go->hasQuest(questId));
#else
        Eluna::Push(L, go->HasQuest(questId));
#endif
        return 1;
    }
References GameObject::hasQuest(), and Eluna::Push().
IsActive()
int LuaGameObject::IsActive (lua_State * L, GameObject * go)
Returns 'true' if the [GameObject] is active
Returns
bool isActive
    {
        Eluna::Push(L, go->isActiveObject());
        return 1;
    }
References WorldObject::isActiveObject(), and Eluna::Push().
IsSpawned()
int LuaGameObject::IsSpawned (lua_State * L, GameObject * go)
Returns 'true' if the [GameObject] is spawned
Returns
bool isSpawned
    {
        Eluna::Push(L, go->isSpawned());
        return 1;
    }
References GameObject::isSpawned(), and Eluna::Push().
IsTransport()
int LuaGameObject::IsTransport (lua_State * L, GameObject * go)
Returns 'true' if the [GameObject] is a transport
Returns
bool isTransport
    {
        Eluna::Push(L, go->IsTransport());
        return 1;
    }
References GameObject::IsTransport(), and Eluna::Push().
RemoveFromWorld()
int LuaGameObject::RemoveFromWorld (lua_State * L, GameObject * go)
Removes [GameObject] from the world
The object is no longer reachable after this and it is not respawned.
Parameters
bool deleteFromDB : if true, it will delete the [GameObject] from the database
    {
        bool deldb = Eluna::CHECKVAL<bool>(L, 2, false);
        // cs_gobject.cpp copy paste
#if defined TRINITY || AZEROTHCORE
        ObjectGuid ownerGuid = go->GetOwnerGUID();
#else
        ObjectGuid ownerGuid = go->GetOwnerGuid();
#endif
        if (ownerGuid)
        {
            Unit* owner = eObjectAccessor()GetUnit(*go, ownerGuid);
            if (!owner || !ownerGuid.IsPlayer())
                return 0;
            owner->RemoveGameObject(go, false);
        }
        if (deldb)
        {
#ifdef TRINITY
            GameObject::DeleteFromDB(go->GetSpawnId());
#else
            go->DeleteFromDB();
#endif
        }
        go->SetRespawnTime(0);
        go->Delete();
        Eluna::CHECKOBJ<ElunaObject>(L, 1)->Invalidate();
        return 0;
    }
References GameObject::Delete(), GameObject::DeleteFromDB(), eObjectAccessor, GameObject::GetOwnerGUID(), GameObject::GetSpawnId(), ObjectGuid::IsPlayer(), Unit::RemoveGameObject(), and GameObject::SetRespawnTime().
Respawn()
int LuaGameObject::Respawn (lua_State * , GameObject * go)
Respawns a [GameObject]
    {
        go->Respawn();
        return 0;
    }
References GameObject::Respawn().
SaveToDB()
int LuaGameObject::SaveToDB (lua_State * , GameObject * go)
Saves [GameObject] to the database
    {
        go->SaveToDB();
        return 0;
    }
References GameObject::SaveToDB().
SetGoState()
int LuaGameObject::SetGoState (lua_State * L, GameObject * go)
Sets the state of a [GameObject]
enum GOState
{
    GO_STATE_ACTIVE             = 0,                        // show in world as used and not reset (closed door open)
    GO_STATE_READY              = 1,                        // show in world as ready (closed door close)
    GO_STATE_ACTIVE_ALTERNATIVE = 2                         // show in world as used in alt way and not reset (closed door open by cannon fire)
};
Parameters
[GOState] state : all available go states can be seen above
    {
        uint32 state = Eluna::CHECKVAL<uint32>(L, 2, 0);
        if (state == 0)
            go->SetGoState(GO_STATE_ACTIVE);
        else if (state == 1)
            go->SetGoState(GO_STATE_READY);
        else if (state == 2)
        {
#ifdef TRINITY
            go->SetGoState(GO_STATE_DESTROYED);
#else
            go->SetGoState(GO_STATE_ACTIVE_ALTERNATIVE);
#endif
        }
        return 0;
    }
References GO_STATE_ACTIVE, GO_STATE_ACTIVE_ALTERNATIVE, GO_STATE_READY, and GameObject::SetGoState().
SetLootState()
int LuaGameObject::SetLootState (lua_State * L, GameObject * go)
Sets the [LootState] of a [GameObject] Below are [LootState]s off of 3.3.5a
enum LootState
{
    GO_NOT_READY = 0,
    GO_READY,                                               // can be ready but despawned, and then not possible activate until spawn
    GO_ACTIVATED,
    GO_JUST_DEACTIVATED
};
Parameters
[LootState] state : all available loot states can be seen above
    {
        uint32 state = Eluna::CHECKVAL<uint32>(L, 2, 0);
        if (state == 0)
            go->SetLootState(GO_NOT_READY);
        else if (state == 1)
            go->SetLootState(GO_READY);
        else if (state == 2)
            go->SetLootState(GO_ACTIVATED);
        else if (state == 3)
            go->SetLootState(GO_JUST_DEACTIVATED);
        return 0;
    }
References GO_ACTIVATED, GO_JUST_DEACTIVATED, GO_NOT_READY, GO_READY, and GameObject::SetLootState().
SetRespawnTime()
int LuaGameObject::SetRespawnTime (lua_State * L, GameObject * go)
Sets the respawn or despawn time for the gameobject.
Respawn time is also used as despawn time depending on gameobject settings
Parameters
int32 delay = 0 : cooldown time in seconds to respawn or despawn the object. 0 means never
    {
        int32 respawn = Eluna::CHECKVAL<int32>(L, 2);
        go->SetRespawnTime(respawn);
        return 0;
    }
References GameObject::SetRespawnTime().
UseDoorOrButton()
int LuaGameObject::UseDoorOrButton (lua_State * L, GameObject * go)
Activates a door or a button/lever
Parameters
uint32 delay = 0 : cooldown time in seconds to restore the [GameObject] back to normal. 0 for infinite duration
    {
        uint32 delay = Eluna::CHECKVAL<uint32>(L, 2, 0);
        go->UseDoorOrButton(delay);
        return 0;
    }
References GameObject::UseDoorOrButton().