AzerothCore Doxygen
world_script_loader.cpp File Reference
Functions
void AddSC_areatrigger_scripts ()
void AddSC_emerald_dragons ()
void AddSC_generic_creature ()
void AddSC_go_scripts ()
void AddSC_guards ()
void AddSC_item_scripts ()
void AddSC_npc_professions ()
void AddSC_npc_innkeeper ()
void AddSC_npcs_special ()
void AddSC_npc_taxi ()
void AddSC_achievement_scripts ()
void AddSC_chat_log ()
void AddSC_action_ip_logger ()
void AddSC_player_scripts ()
void AddSC_npc_stave_of_ancients ()
void AddSC_server_mail ()
void AddSC_transport_zeppelins ()
void AddSC_suns_reach_reclamation ()
void AddSC_scourge_invasion ()
void AddWorldScripts ()
Function Documentation
AddSC_achievement_scripts()
void AddSC_achievement_scripts ()
{
    new achievement_resilient_victory();
    new achievement_bg_control_all_nodes();
    new achievement_save_the_day();
    new achievement_bg_ic_resource_glut();
    new achievement_bg_ic_glaive_grave();
    new achievement_bg_ic_mowed_down();
    new achievement_bg_sa_artillery();
    new achievement_sickly_gazelle();
    new achievement_everything_counts();
    new achievement_bg_av_perfection();
    new achievement_arena_by_type("achievement_arena_2v2_check", ARENA_TYPE_2v2);
    new achievement_arena_by_type("achievement_arena_3v3_check", ARENA_TYPE_3v3);
    new achievement_arena_by_type("achievement_arena_5v5_check", ARENA_TYPE_5v5);
    new achievement_sa_defense_of_the_ancients();
    new achievement_tilted();
    new achievement_not_even_a_scratch();
    new achievement_killed_exp_or_honor_target();
    new achievement_flirt_with_disaster_perf_check();
    new achievement_fa_la_la_la_ogrila();
}
References ARENA_TYPE_2v2, ARENA_TYPE_3v3, and ARENA_TYPE_5v5.
Referenced by AddWorldScripts().
AddSC_action_ip_logger()
void AddSC_action_ip_logger ()
{
    new AccountActionIpLogger();
    new CharacterActionIpLogger();
    new CharacterDeleteActionIpLogger();
}
Referenced by AddWorldScripts().
AddSC_areatrigger_scripts()
void AddSC_areatrigger_scripts ()
{
    new AreaTrigger_at_coilfang_waterfall();
    new AreaTrigger_at_legion_teleporter();
    new AreaTrigger_at_stormwright_shelf();
    new AreaTrigger_at_scent_larkorwi();
    new AreaTrigger_at_last_rites();
    new AreaTrigger_at_nats_landing();
    new AreaTrigger_at_sentry_point();
    new AreaTrigger_at_brewfest();
    new AreaTrigger_at_area_52_entrance();
}
Referenced by AddWorldScripts().
AddSC_chat_log()
void AddSC_chat_log ()
{
    new ChatLogScript();
}
Referenced by AddWorldScripts().
AddSC_emerald_dragons()
void AddSC_emerald_dragons ()
{
    // helper NPC scripts
    new npc_dream_fog();
    new npc_spirit_shade();
    // dragons
    new boss_ysondre();
    new boss_taerar();
    new boss_emeriss();
    new boss_lethon();
    // dragon spellscripts
    RegisterSpellScript(spell_dream_fog_sleep);
    RegisterSpellScript(spell_mark_of_nature);
    RegisterSpellScript(spell_shadow_bolt_whirl);
};
References RegisterSpellScript.
Referenced by AddWorldScripts().
AddSC_generic_creature()
void AddSC_generic_creature ()
{
    new trigger_periodic;
}
Referenced by AddWorldScripts().
AddSC_go_scripts()
void AddSC_go_scripts ()
{
    new go_seer_of_zebhalak();
    new go_witherbark_totem_bundle();
    new go_arena_ready_marker();
    new go_ethereum_prison();
    new go_ethereum_stasis();
    new go_resonite_cask();
    new go_tadpole_cage();
    new go_flames();
    new go_heat();
    new go_bear_trap();
    new go_duskwither_spire_power_source();
    new go_l70_etc_music();
    new go_brewfest_music();
    new go_pirate_day_music();
    new go_darkmoon_faire_music();
    new go_midsummer_music();
    new go_gilded_brazier();
    //new go_shrine_of_the_birds();
    new go_southfury_moonstone();
    new go_tablet_of_the_seven();
    new go_jump_a_tron();
    new go_sacred_fire_of_life();
    new go_tele_to_dalaran_crystal();
    new go_tele_to_violet_stand();
    new go_fel_crystalforge();
    new go_bashir_crystalforge();
    new go_scourge_cage();
    new go_arcane_prison();
    new go_jotunheim_cage();
    new go_table_theka();
    new go_soulwell();
    new go_dragonflayer_cage();
    new go_amberpine_outhouse();
    new go_hive_pod();
    new go_massive_seaforium_charge();
    new go_veil_skith_cage();
    new go_bells();
}
Referenced by AddWorldScripts().
AddSC_guards()
void AddSC_guards ()
{
    new guard_shattrath_aldor();
    new guard_shattrath_scryer();
}
Referenced by AddWorldScripts().
AddSC_item_scripts()
void AddSC_item_scripts ()
{
    new item_only_for_flight();
    new item_incendiary_explosives();
    new item_mysterious_egg();
    new item_disgusting_jar();
    new item_petrov_cluster_bombs();
    new item_captured_frog();
    new item_generic_limit_chance_above_60();
}
Referenced by AddWorldScripts().
AddSC_npc_innkeeper()
void AddSC_npc_innkeeper ()
{
    new npc_innkeeper;
}
Referenced by AddWorldScripts().
AddSC_npc_professions()
void AddSC_npc_professions ()
{
    new npc_prof_alchemy();
    new npc_prof_blacksmith();
    new npc_engineering_tele_trinket();
    new npc_prof_leather();
    new npc_prof_tailor();
    new go_evil_book_for_dummies();
}
Referenced by AddWorldScripts().
AddSC_npc_stave_of_ancients()
void AddSC_npc_stave_of_ancients ()
{
    new npc_artorius();
    new npc_precious();
    new npc_simone();
    new npc_nelson();
    new npc_franklin();
}
Referenced by AddWorldScripts().
AddSC_npc_taxi()
void AddSC_npc_taxi ()
{
    new npc_taxi;
}
Referenced by AddWorldScripts().
AddSC_npcs_special()
void AddSC_npcs_special ()
{
    new npc_elder_clearwater();
    new npc_riggle_bassbait();
    new npc_target_dummy();
    new npc_training_dummy();
    new npc_venomhide_hatchling();
    new npc_air_force_bots();
    new npc_chicken_cluck();
    new npc_dancing_flames();
    new npc_doctor();
    new npc_injured_patient();
    new npc_garments_of_quests();
    new npc_guardian();
    new npc_sayge();
    new npc_steam_tonk();
    new npc_wormhole();
    new npc_pet_trainer();
    new npc_locksmith();
    new npc_experience();
    new npc_firework();
    new npc_spring_rabbit();
    new npc_stable_master();
    RegisterCreatureAI(npc_arcanite_dragonling);
    RegisterCreatureAI(npc_crashin_thrashin_robot);
    RegisterCreatureAI(npc_controller);
    RegisterCreatureAI(npc_traveler_mammoth_vendor);
}
References npc_doctor::npc_doctor(), and RegisterCreatureAI.
Referenced by AddWorldScripts().
AddSC_player_scripts()
void AddSC_player_scripts ()
{
    new QuestApprenticeAnglerPlayerScript();
}
Referenced by AddWorldScripts().
AddSC_scourge_invasion()
void AddSC_scourge_invasion ()
{
    RegisterGameObjectAI(go_necropolis);
    RegisterCreatureAI(npc_herald_of_the_lich_king);
    RegisterCreatureAI(npc_necropolis);
    RegisterCreatureAI(npc_necropolis_health);
    RegisterCreatureAI(npc_necropolis_proxy);
    RegisterCreatureAI(npc_necropolis_relay);
    RegisterCreatureAI(npc_necrotic_shard);
    RegisterCreatureAI(npc_minion_spawner);
    RegisterCreatureAI(npc_pallid_horror);
    RegisterCreatureAI(npc_cultist_engineer);
    RegisterCreatureAI(npc_flameshocker);
    RegisterSpellScript(spell_communique_trigger);
    RegisterSpellScript(spell_despawner_self);
    RegisterSpellScript(spell_scourge_invasion_scourge_strike);
}
References RegisterCreatureAI, RegisterGameObjectAI, and RegisterSpellScript.
Referenced by AddWorldScripts().
AddSC_server_mail()
void AddSC_server_mail ()
{
    new ServerMailReward();
}
Referenced by AddWorldScripts().
AddSC_suns_reach_reclamation()
void AddSC_suns_reach_reclamation ()
{
    new npc_suns_reach_reclamation();
    new npc_sunwell_gate();
}
Referenced by AddWorldScripts().
AddSC_transport_zeppelins()
void AddSC_transport_zeppelins ()
{
    RegisterGameObjectAI(go_transport_the_iron_eagle);
    RegisterGameObjectAI(go_transport_the_thundercaller);
    RegisterGameObjectAI(go_transport_the_purple_princess);
}
References RegisterGameObjectAI.
Referenced by AddWorldScripts().
AddWorldScripts()
void AddWorldScripts ()
{
    AddSC_areatrigger_scripts();
    AddSC_emerald_dragons();
    AddSC_generic_creature();
    AddSC_go_scripts();
    AddSC_guards();
    AddSC_item_scripts();
    AddSC_npc_professions();
    AddSC_npc_innkeeper();
    AddSC_npcs_special();
    AddSC_npc_taxi();
    AddSC_achievement_scripts();
    AddSC_chat_log(); // location: scripts\World\chat_log.cpp
    AddSC_action_ip_logger(); // location: scripts\World\action_ip_logger.cpp
    AddSC_player_scripts();
    AddSC_npc_stave_of_ancients();
    AddSC_server_mail();
    AddSC_transport_zeppelins();
    AddSC_suns_reach_reclamation();
    AddSC_scourge_invasion();
}
References AddSC_achievement_scripts(), AddSC_action_ip_logger(), AddSC_areatrigger_scripts(), AddSC_chat_log(), AddSC_emerald_dragons(), AddSC_generic_creature(), AddSC_go_scripts(), AddSC_guards(), AddSC_item_scripts(), AddSC_npc_innkeeper(), AddSC_npc_professions(), AddSC_npc_stave_of_ancients(), AddSC_npc_taxi(), AddSC_npcs_special(), AddSC_player_scripts(), AddSC_scourge_invasion(), AddSC_server_mail(), AddSC_suns_reach_reclamation(), and AddSC_transport_zeppelins().