AzerothCore Doxygen
boss_devourer_of_souls Struct Reference
Public Member Functions
boss_devourer_of_souls (Creature *creature)
void Reset () override
uint32 GetData (uint32 id) const override
void JustEngagedWith (Unit *who) override
Called for reaction when initially engaged - this happens after JustEnteredCombat.
void SpellHitTarget (Unit *target, SpellInfo const *spell) override
bool CanAIAttack (Unit const *target) const override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void JustDied (Unit *killer) override
void KilledUnit (Unit *victim) override
void JustSummoned (Creature *summon) override
void EnterEvadeMode (EvadeReason why) override
Public Member Functions inherited from BossAI
BossAI (Creature *creature, uint32 bossId)
~BossAI () override
bool CanRespawn () override
void OnSpellCast (SpellInfo const *spell) override
void OnChannelFinished (SpellInfo const *spell) override
void OnSpellFailed (SpellInfo const *spell) override
void DamageTaken (Unit *attacker, uint32 &damage, DamageEffectType damagetype, SpellSchoolMask damageSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void JustSummoned (Creature *summon) override
void SummonedCreatureDespawn (Creature *summon) override
void SummonedCreatureDespawnAll () override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void ScheduleHealthCheckEvent (uint32 healthPct, std::function< void()> exec, bool allowedWhileCasting=true)
Executes a function once the creature reaches the defined health point percent.
void ScheduleHealthCheckEvent (std::initializer_list< uint8 > healthPct, std::function< void()> exec, bool allowedWhileCasting=true)
void ProcessHealthCheck ()
void ScheduleEnrageTimer (uint32 spellId, Milliseconds timer, uint8 textId=0)
virtual void ExecuteEvent (uint32)
virtual void ScheduleTasks ()
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged - this happens after JustEnteredCombat.
void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER) override
void JustDied (Unit *) override
void JustReachedHome () override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged - this happens after JustEnteredCombat.
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoRewardPlayersInArea ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportPlayer (Unit *unit, Position pos)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool IsUniqueTimedEventDone (uint32 id) const
void SetUniqueTimedEventDone (uint32 id)
void ResetUniqueTimedEvent (uint32 id)
void ClearUniqueTimedEventsDone ()
void ScheduleTimedEvent (Milliseconds timerMin, Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0ms, uint32 uniqueId=0)
void ScheduleTimedEvent (Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0ms, uint32 uniqueId=0)
void ScheduleUniqueTimedEvent (Milliseconds timer, std::function< void()> exec, uint32 uniqueId)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
void SetInvincibility (bool apply)
bool IsInvincible () const
void SetAutoAttackAllowed (bool allow)
bool IsAutoAttackAllowed () const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0ms)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
bool IsEngaged () const
Check if creature is currently engaged in combat.
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool IsEscortNPC (bool=true) const
void JustEnteredCombat (Unit *who) override
Called when the unit enters combat.
virtual void JustStartedThreateningMe (Unit *who)
void EngagementStart (Unit *who)
void EngagementOver ()
void JustExitedCombat () override
Called when the unit leaves combat.
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureEvade (Creature *)
virtual void OnSpellStart (SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void PathEndReached (uint32)
virtual void WaypointPathStarted (uint32)
== Waypoints system =============================
virtual void WaypointStarted (uint32, uint32)
virtual void WaypointReached (uint32, uint32)
virtual void WaypointPathEnded (uint32, uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *attacker)
virtual void OwnerAttacked (Unit *target)
void OnOwnerCombatInteraction (Unit *target)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
int32 VisualizeBoundary (uint32 duration, Unit *owner=nullptr, bool fill=false, bool checkZ=false) const
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
virtual void DistancingStarted ()
virtual void DistancingEnded ()
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid const &, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void EvadeTimerExpired ()
Called when evade timer expires (target unreachable for too long)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage to any victim (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Public Attributes
bool AchievementCompleted = true
Public Attributes inherited from BossAI
float callForHelpRange
InstanceScript *const instance
Public Attributes inherited from ScriptedAI
Creature * me
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from BossAI
void _Reset ()
void _JustEngagedWith ()
void _JustDied ()
void _JustReachedHome ()
void _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
void TeleportCheaters ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from BossAI
SummonList summons
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
bool _isEngaged
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
boss_devourer_of_souls()
boss_devourer_of_souls::boss_devourer_of_souls (Creature * creature) inline
: BossAI(creature, DATA_DEVOURER) { }
Member Function Documentation
CanAIAttack()
bool boss_devourer_of_souls::CanAIAttack (Unit const * target) const inline override virtual
Reimplemented from UnitAI.
{ return target->GetPositionZ() > 706.5f; }
References Position::GetPositionZ().
EnterEvadeMode()
void boss_devourer_of_souls::EnterEvadeMode (EvadeReason why) inline override virtual
Reimplemented from CreatureAI.
    {
        me->SetControlled(false, UNIT_STATE_ROOT);
        me->DisableRotate(false);
        BossAI::EnterEvadeMode(why);
    }
References Unit::DisableRotate(), BossAI::EnterEvadeMode(), ScriptedAI::me, Unit::SetControlled(), and UNIT_STATE_ROOT.
GetData()
uint32 boss_devourer_of_souls::GetData (uint32 id) const inline override virtual
Reimplemented from UnitAI.
    {
        if (id == 1)
            return AchievementCompleted;
        return 0;
    }
References AchievementCompleted.
JustDied()
void boss_devourer_of_souls::JustDied (Unit * killer) inline override virtual
Reimplemented from CreatureAI.
    {
        BossAI::JustDied(killer);
        Talk(SAY_FACE_DEATH);
    }
References BossAI::JustDied(), and SAY_FACE_DEATH.
JustEngagedWith()
void boss_devourer_of_souls::JustEngagedWith (Unit *) inline override virtual
Called for reaction when initially engaged - this happens after JustEnteredCombat.
Reimplemented from CreatureAI.
    {
        BossAI::JustEngagedWith(who);
        Talk(SAY_FACE_AGGRO);
        events.RescheduleEvent(EVENT_SPELL_PHANTOM_BLAST, 5s);
        events.RescheduleEvent(EVENT_SPELL_MIRRORED_SOUL, 9s);
        events.RescheduleEvent(EVENT_SPELL_WELL_OF_SOULS, 6s, 8s);
        events.RescheduleEvent(EVENT_SPELL_UNLEASHED_SOULS, 18s, 20s);
        events.RescheduleEvent(EVENT_SPELL_WAILING_SOULS, 65s);
        // Support for Quest Tempering the Blade
        me->GetMap()->DoForAllPlayers([this](Player* player)
        {
            if (me->FindNearestCreature(NPC_CRUCIBLE_OF_SOULS, 100.0f))
                return;
            uint32 questId = player->GetTeamId() == TEAM_ALLIANCE ? QUEST_TEMPERING_THE_BLADE_A : QUEST_TEMPERING_THE_BLADE_H;
            if (player->GetQuestStatus(questId) == QUEST_STATUS_INCOMPLETE)
                me->SummonCreature(NPC_CRUCIBLE_OF_SOULS, 5672.29f, 2520.69f, 713.44f, 0.96f);
        });
    }
References Map::DoForAllPlayers(), EVENT_SPELL_MIRRORED_SOUL, EVENT_SPELL_PHANTOM_BLAST, EVENT_SPELL_UNLEASHED_SOULS, EVENT_SPELL_WAILING_SOULS, EVENT_SPELL_WELL_OF_SOULS, WorldObject::FindNearestCreature(), WorldObject::GetMap(), Player::GetQuestStatus(), Player::GetTeamId(), BossAI::JustEngagedWith(), ScriptedAI::me, NPC_CRUCIBLE_OF_SOULS, QUEST_STATUS_INCOMPLETE, QUEST_TEMPERING_THE_BLADE_A, QUEST_TEMPERING_THE_BLADE_H, SAY_FACE_AGGRO, WorldObject::SummonCreature(), and TEAM_ALLIANCE.
JustSummoned()
void boss_devourer_of_souls::JustSummoned (Creature * summon) inline override virtual
Reimplemented from CreatureAI.
    {
        if (summon->GetEntry() != NPC_CRUCIBLE_OF_SOULS)
            BossAI::JustSummoned(summon);
        if (summon->GetEntry() == NPC_UNLEASHED_SOUL)
            if (Player* player = summon->SelectNearestPlayer(100.0f))
            {
                summon->AddThreat(player, 100000.0f);
                summon->AI()->AttackStart(player);
            }
    }
References Unit::AddThreat(), Creature::AI(), UnitAI::AttackStart(), Object::GetEntry(), BossAI::JustSummoned(), NPC_CRUCIBLE_OF_SOULS, NPC_UNLEASHED_SOUL, and WorldObject::SelectNearestPlayer().
KilledUnit()
void boss_devourer_of_souls::KilledUnit (Unit * victim) inline override virtual
Reimplemented from CreatureAI.
    {
        if (!victim->IsPlayer())
            return;
        uint8 textId = 0;
        switch (me->GetDisplayId())
        {
            case MODEL_ANGER:
                textId = SAY_FACE_ANGER_SLAY;
                break;
            case MODEL_SORROW:
                textId = SAY_FACE_SORROW_SLAY;
                break;
            case MODEL_DESIRE:
                textId = SAY_FACE_DESIRE_SLAY;
                break;
            default:
                break;
        }
        if (textId)
            Talk(textId);
    }
References Unit::GetDisplayId(), Object::IsPlayer(), ScriptedAI::me, MODEL_ANGER, MODEL_DESIRE, MODEL_SORROW, SAY_FACE_ANGER_SLAY, SAY_FACE_DESIRE_SLAY, and SAY_FACE_SORROW_SLAY.
Reset()
void boss_devourer_of_souls::Reset () inline override virtual
Reimplemented from UnitAI.
    {
        BossAI::Reset();
        AchievementCompleted = true;
        me->SetControlled(false, UNIT_STATE_ROOT);
        me->DisableRotate(false);
        me->SetReactState(REACT_AGGRESSIVE);
    }
References AchievementCompleted, Unit::DisableRotate(), ScriptedAI::me, REACT_AGGRESSIVE, BossAI::Reset(), Unit::SetControlled(), Creature::SetReactState(), and UNIT_STATE_ROOT.
SpellHitTarget()
void boss_devourer_of_souls::SpellHitTarget (Unit * target, SpellInfo const * spell) inline override virtual
Reimplemented from CreatureAI.
    {
        if (spell->Id == SPELL_PHANTOM_BLAST_H)
            AchievementCompleted = false;
        else if (spell->Id == SPELL_WAILING_SOULS_TARGETING)
        {
            me->SetOrientation(me->GetAngle(target));
            me->SetControlled(true, UNIT_STATE_ROOT);
            me->DisableRotate(true);
            me->SetGuidValue(UNIT_FIELD_TARGET, ObjectGuid::Empty);
            me->SetReactState(REACT_PASSIVE);
            me->GetMotionMaster()->Clear(false);
            me->GetMotionMaster()->MoveIdle();
            me->StopMovingOnCurrentPos();
            me->SetFacingToObject(target);
            me->SendMovementFlagUpdate();
            DoCastSelf(SPELL_WAILING_SOULS);
        }
    }
References AchievementCompleted, MotionMaster::Clear(), Unit::DisableRotate(), UnitAI::DoCastSelf(), ObjectGuid::Empty, Position::GetAngle(), Unit::GetMotionMaster(), SpellInfo::Id, ScriptedAI::me, MotionMaster::MoveIdle(), REACT_PASSIVE, Unit::SendMovementFlagUpdate(), Unit::SetControlled(), Unit::SetFacingToObject(), Object::SetGuidValue(), Position::SetOrientation(), Creature::SetReactState(), SPELL_PHANTOM_BLAST_H, SPELL_WAILING_SOULS, SPELL_WAILING_SOULS_TARGETING, Unit::StopMovingOnCurrentPos(), UNIT_FIELD_TARGET, and UNIT_STATE_ROOT.
UpdateAI()
void boss_devourer_of_souls::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Implements UnitAI.
    {
        if (!UpdateVictim())
            return;
        events.Update(diff);
        if (Spell* s = me->GetCurrentSpell(CURRENT_CHANNELED_SPELL))
            if (s->m_spellInfo->Id == SPELL_MIRRORED_SOUL)
            {
                switch (events.ExecuteEvent())
                {
                    case EVENT_SPELL_PHANTOM_BLAST:
                        DoCastVictim(SPELL_PHANTOM_BLAST);
                        events.Repeat(5s);
                        break;
                    default:
                        events.Repeat(1s);
                        break;
                }
                if (!me->GetCurrentSpell(CURRENT_GENERIC_SPELL))
                {
                    me->ClearUnitState(UNIT_STATE_CASTING);
                    DoMeleeAttackIfReady();
                    me->AddUnitState(UNIT_STATE_CASTING);
                }
                return;
            }
        if (me->HasUnitState(UNIT_STATE_CASTING))
            return;
        switch (events.ExecuteEvent())
        {
            case EVENT_SPELL_PHANTOM_BLAST:
                DoCastVictim(SPELL_PHANTOM_BLAST);
                events.Repeat(5s);
                break;
            case EVENT_SPELL_MIRRORED_SOUL:
                if (Unit* target = SelectTarget(SelectTargetMethod::Random, 0, 90.0f, true))
                {
                    DoCast(target, SPELL_MIRRORED_SOUL);
                    me->setAttackTimer(BASE_ATTACK, 2500);
                    Talk(EMOTE_MIRRORED_SOUL);
                }
                events.Repeat(20s, 30s);
                break;
            case EVENT_SPELL_WELL_OF_SOULS:
                if (Unit* target = SelectTarget(SelectTargetMethod::Random, 0, 40.0f, true))
                    DoCast(target, SPELL_WELL_OF_SOULS);
                events.Repeat(25s, 30s);
                events.DelayEventsToMax(4s, 0);
                break;
            case EVENT_SPELL_UNLEASHED_SOULS:
                DoCastSelf(SPELL_UNLEASHED_SOULS);
                Talk(SAY_FACE_UNLEASH_SOUL);
                Talk(EMOTE_UNLEASH_SOUL);
                events.Repeat(30s, 40s);
                events.DelayEventsToMax(5s, 0);
                me->setAttackTimer(BASE_ATTACK, 5500);
                break;
            case EVENT_SPELL_WAILING_SOULS:
                Talk(SAY_FACE_WAILING_SOUL);
                Talk(EMOTE_WAILING_SOUL);
                if (Unit* target = SelectTarget(SelectTargetMethod::Random, 0, 0.0f, true))
                    me->CastCustomSpell(SPELL_WAILING_SOULS_TARGETING, SPELLVALUE_MAX_TARGETS, 1, target);
                events.Repeat(80s);
                events.DelayEventsToMax(20s, 0);
                break;
        }
        DoMeleeAttackIfReady();
    }
References Unit::AddUnitState(), BASE_ATTACK, Unit::CastCustomSpell(), Unit::ClearUnitState(), CURRENT_CHANNELED_SPELL, CURRENT_GENERIC_SPELL, UnitAI::DoCast(), UnitAI::DoCastSelf(), UnitAI::DoCastVictim(), UnitAI::DoMeleeAttackIfReady(), EMOTE_MIRRORED_SOUL, EMOTE_UNLEASH_SOUL, EMOTE_WAILING_SOUL, EVENT_SPELL_MIRRORED_SOUL, EVENT_SPELL_PHANTOM_BLAST, EVENT_SPELL_UNLEASHED_SOULS, EVENT_SPELL_WAILING_SOULS, EVENT_SPELL_WELL_OF_SOULS, Unit::GetCurrentSpell(), Unit::HasUnitState(), ScriptedAI::me, Random, SAY_FACE_UNLEASH_SOUL, SAY_FACE_WAILING_SOUL, UnitAI::SelectTarget(), Unit::setAttackTimer(), SPELL_MIRRORED_SOUL, SPELL_PHANTOM_BLAST, SPELL_UNLEASHED_SOULS, SPELL_WAILING_SOULS_TARGETING, SPELL_WELL_OF_SOULS, SPELLVALUE_MAX_TARGETS, UNIT_STATE_CASTING, and CreatureAI::UpdateVictim().
Member Data Documentation
AchievementCompleted
bool boss_devourer_of_souls::AchievementCompleted = true
Referenced by GetData(), Reset(), and SpellHitTarget().
The documentation for this struct was generated from the following file:
azerothcore-wotlk/src/server/scripts/Northrend/FrozenHalls/ForgeOfSouls/boss_devourer_of_souls.cpp