AzerothCore Doxygen
SimpleCharmedAI Class Reference
#include "UnitAI.h"
Public Member Functions
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
SimpleCharmedAI (Player *player)
Public Member Functions inherited from PlayerAI
PlayerAI (Player *player)
void OnCharmed (bool apply) override
Called when unit is charmed.
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void InitializeAI ()
virtual void Reset ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Additional Inherited Members
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Attributes inherited from PlayerAI
Player *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
SimpleCharmedAI()
SimpleCharmedAI::SimpleCharmedAI (Player * player) inline
: PlayerAI(player) {}
Member Function Documentation
UpdateAI()
void SimpleCharmedAI::UpdateAI (uint32) override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Implements UnitAI.
{
    Creature* charmer = me->GetCharmer()->ToCreature();
    //kill self if charm aura has infinite duration
    if (charmer->IsInEvadeMode())
    {
        Unit::AuraEffectList const& auras = me->GetAuraEffectsByType(SPELL_AURA_MOD_CHARM);
        for (Unit::AuraEffectList::const_iterator iter = auras.begin(); iter != auras.end(); ++iter)
            if ((*iter)->GetCasterGUID() == charmer->GetGUID() && (*iter)->GetBase()->IsPermanent())
            {
                Unit::Kill(charmer, me);
                return;
            }
    }
    if (!charmer->IsInCombat())
        me->GetMotionMaster()->MoveFollow(charmer, PET_FOLLOW_DIST, me->GetFollowAngle());
    Unit* target = me->GetVictim();
    if (!target || !charmer->IsValidAttackTarget(target))
        AttackStart(charmer->SelectNearestTargetInAttackDistance(ATTACK_DISTANCE));
}
References ATTACK_DISTANCE, UnitAI::AttackStart(), Unit::GetAuraEffectsByType(), Unit::GetCharmer(), Unit::GetFollowAngle(), Object::GetGUID(), Unit::GetMotionMaster(), Unit::GetVictim(), Unit::IsInCombat(), Creature::IsInEvadeMode(), Unit::IsValidAttackTarget(), Unit::Kill(), PlayerAI::me, MotionMaster::MoveFollow(), PET_FOLLOW_DIST, Creature::SelectNearestTargetInAttackDistance(), SPELL_AURA_MOD_CHARM, and Object::ToCreature().
The documentation for this class was generated from the following files:
azerothcore-wotlk/src/server/game/AI/CoreAI/UnitAI.h
azerothcore-wotlk/src/server/game/AI/CoreAI/UnitAI.cpp