AzerothCore Doxygen
WorldPackets Namespace Reference
User to World Communication
Namespaces
namespace Bank
namespace Character
namespace Chat
namespace Combat
namespace CombatLog
namespace Guild
namespace LFG
namespace Misc
namespace Pet
namespace Strings
namespace Totem
namespace WorldState
Classes
class Array
class ClientPacket
class CompactArray
class IllegalHyperlinkException
class InvalidHyperlinkException
class InvalidStringValueException
class InvalidUtf8ValueException
class Packet
class PacketArrayMaxCapacityException
class ServerPacket
class String
Functions
void CheckCompactArrayMaskOverflow (std::size_t index, std::size_t limit)
template<typename T >
ByteBuffer & operator<< (ByteBuffer &data, CompactArray< T > const &v)
template<typename T >
ByteBuffer & operator>> (ByteBuffer &data, CompactArray< T > &v)
Function Documentation
CheckCompactArrayMaskOverflow()
void WorldPackets::CheckCompactArrayMaskOverflow (std::size_t index, std::size_t limit)
{
    ASSERT(index < limit, "Attempted to insert {} values into CompactArray but it can only hold {}", index, limit);
}
References ASSERT.
Referenced by WorldPackets::CompactArray< T >::Insert().
operator<<()
template<typename T > ByteBuffer & WorldPackets::operator<< (ByteBuffer & data, CompactArray< T > const & v)
    {
        uint32 mask = v.GetMask();
        data << uint32(mask);
        for (std::size_t i = 0; i < v.GetSize(); ++i)
        {
            if (mask & (1 << i))
            {
                data << v[i];
            }
        }
        return data;
    }
References WorldPackets::CompactArray< T >::GetMask(), and WorldPackets::CompactArray< T >::GetSize().
operator>>()
template<typename T > ByteBuffer & WorldPackets::operator>> (ByteBuffer & data, CompactArray< T > & v)
    {
        uint32 mask;
        data >> mask;
        for (std::size_t index = 0; mask != 0; mask >>= 1, ++index)
        {
            if ((mask & 1) != 0)
            {
                v.Insert(index, data.read<T>());
            }
        }
        return data;
    }
References WorldPackets::CompactArray< T >::Insert(), and ByteBuffer::read().