AzerothCore Doxygen
npc_highlord_darion_mograine::npc_highlord_darion_mograineAI Struct Reference
Public Member Functions
npc_highlord_darion_mograineAI (Creature *creature)
void DoAction (int32 param) override
uint32 GetData (uint32 type) const override
void SendUpdateWorldState (uint32 id, uint32 state)
void SendInitialWorldStates ()
void JustSummoned (Creature *cr) override
void SummonedCreatureDies (Creature *creature, Unit *) override
void JustDied (Unit *) override
void FinishFight ()
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void Reset () override
void JustRespawned () override
Creature * GetEntryFromSummons (uint32 entry)
void MovementInform (uint32 type, uint32 point) override
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
Called at any Damage from any attacker (before damage apply)
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged.
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoAddThreat (Unit *unit, float amount)
void DoModifyThreatByPercent (Unit *unit, int32 pct)
void DoResetThreat (Unit *unit)
void DoResetThreatList ()
float DoGetThreat (Unit *unit)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportPlayer (Unit *unit, Position pos)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool IsUniqueTimedEventDone (uint32 id) const
void SetUniqueTimedEventDone (uint32 id)
void ResetUniqueTimedEvent (uint32 id)
void ClearUniqueTimedEventsDone ()
void ScheduleTimedEvent (Milliseconds timerMin, Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0ms, uint32 uniqueId=0)
void ScheduleTimedEvent (Milliseconds timerMax, std::function< void()> exec, Milliseconds repeatMin, Milliseconds repeatMax=0ms, uint32 uniqueId=0)
void ScheduleUniqueTimedEvent (Milliseconds timer, std::function< void()> exec, uint32 uniqueId)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
void SetInvincibility (bool apply)
bool IsInvincible () const
void SetAutoAttackAllowed (bool allow)
bool IsAutoAttackAllowed () const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0ms)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void OnSpellCastFinished (SpellInfo const *, SpellFinishReason)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void PathEndReached (uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
int32 VisualizeBoundary (uint32 duration, Unit *owner=nullptr, bool fill=false, bool checkZ=false) const
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
virtual void DistancingStarted ()
virtual void DistancingEnded ()
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid const &, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage to any victim (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Public Attributes
EventMap events
SummonList summons
uint32 startTimeRemaining
uint32 defendersRemaining
uint32 scourgeRemaining
uint8 battleStarted
bool resetExecuted
Public Attributes inherited from ScriptedAI
Creature * me
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis {
AXIS_X ,
AXIS_Y
}
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
npc_highlord_darion_mograineAI()
npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::npc_highlord_darion_mograineAI (Creature * creature) inline
                                                           : ScriptedAI(creature), summons(me)
        {
            battleStarted = ENCOUNTER_STATE_NONE;
            me->SetCorpseDelay(3 * 60);
            me->SetRespawnTime(3 * 60);
            resetExecuted = false;
        }
References battleStarted, ENCOUNTER_STATE_NONE, ScriptedAI::me, resetExecuted, Creature::SetCorpseDelay(), and Creature::SetRespawnTime().
Member Function Documentation
DoAction()
void npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::DoAction (int32 param) inline override virtual
Reimplemented from UnitAI.
        {
            if (param == ACTION_START_EVENT && !startTimeRemaining && events.Empty())
            {
                Talk(SAY_LIGHT_OF_DAWN01);
                startTimeRemaining = ENCOUNTER_START_TIME;
                defendersRemaining = ENCOUNTER_TOTAL_DEFENDERS;
                scourgeRemaining = ENCOUNTER_TOTAL_SCOURGE;
                SendInitialWorldStates();
                events.Reset();
                events.ScheduleEvent(EVENT_START_COUNTDOWN_1, 60s);
                events.ScheduleEvent(EVENT_START_COUNTDOWN_2, 120s);
                events.ScheduleEvent(EVENT_START_COUNTDOWN_3, 180s);
                events.ScheduleEvent(EVENT_START_COUNTDOWN_4, 240s);
                events.ScheduleEvent(EVENT_START_COUNTDOWN_5, 300s);
                events.ScheduleEvent(EVENT_START_COUNTDOWN_6, 308s);
                events.ScheduleEvent(EVENT_START_COUNTDOWN_7, 312s);
                events.ScheduleEvent(EVENT_START_COUNTDOWN_8, 316s);
                events.ScheduleEvent(EVENT_START_COUNTDOWN_9, 320s);
                events.ScheduleEvent(EVENT_START_COUNTDOWN_10, 324s);
                events.ScheduleEvent(EVENT_START_COUNTDOWN_11, 332s);
                events.ScheduleEvent(EVENT_START_COUNTDOWN_12, 335s);
                events.ScheduleEvent(EVENT_START_COUNTDOWN_13, 337s + 500ms);
                events.ScheduleEvent(EVENT_START_COUNTDOWN_14, 345s);
            }
        }
References ACTION_START_EVENT, defendersRemaining, ENCOUNTER_START_TIME, ENCOUNTER_TOTAL_DEFENDERS, ENCOUNTER_TOTAL_SCOURGE, EVENT_START_COUNTDOWN_1, EVENT_START_COUNTDOWN_10, EVENT_START_COUNTDOWN_11, EVENT_START_COUNTDOWN_12, EVENT_START_COUNTDOWN_13, EVENT_START_COUNTDOWN_14, EVENT_START_COUNTDOWN_2, EVENT_START_COUNTDOWN_3, EVENT_START_COUNTDOWN_4, EVENT_START_COUNTDOWN_5, EVENT_START_COUNTDOWN_6, EVENT_START_COUNTDOWN_7, EVENT_START_COUNTDOWN_8, EVENT_START_COUNTDOWN_9, SAY_LIGHT_OF_DAWN01, scourgeRemaining, SendInitialWorldStates(), and startTimeRemaining.
FinishFight()
void npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::FinishFight () inline
        {
            if (Creature* tirion = me->SummonCreature(NPC_HIGHLORD_TIRION_FORDRING, LightOfDawnPos[6], TEMPSUMMON_TIMED_OR_CORPSE_DESPAWN, 600000))
            {
                tirion->LoadEquipment(0, true);
                tirion->AI()->Talk(SAY_LIGHT_OF_DAWN25, 4s);
                tirion->m_Events.AddEventAtOffset([&, tirion] {
                    tirion->GetMotionMaster()->MoveWaypoint(NPC_HIGHLORD_TIRION_FORDRING * 10, false);
                }, 14s);
                events.Reset();
                events.ScheduleEvent(EVENT_FINISH_FIGHT_1, 10s);
                events.ScheduleEvent(EVENT_FINISH_FIGHT_2, 20s);
                events.ScheduleEvent(EVENT_FINISH_FIGHT_3, 22s);
                events.ScheduleEvent(EVENT_FINISH_FIGHT_4, 23s);
                events.ScheduleEvent(EVENT_FINISH_FIGHT_5, 24s);
                tirion->SummonGameObject(GO_HOLY_LIGHTNING, 2254.84f, -5298.75f, 82.168f, 1.134f, 0, 0, 0.537102f, 0.843517f, 20);
                tirion->SummonGameObject(GO_HOLY_LIGHTNING, 2296.24f, -5296.44f, 81.9964f, 5.3398f, 0, 0, 0.454395f, -0.8908f, 20);
                tirion->SummonGameObject(GO_HOLY_LIGHTNING, 2314.29f, -5261.78f, 83.1349f, 3.05822f, 0, 0, 0.999131f, 0.0416735f, 20);
                tirion->SummonGameObject(GO_HOLY_LIGHTNING, 2278.43f, -5270.14f, 81.7247f, 0.70988f, 0, 0, 0.347534f, 0.937667f, 20);
            }
        }
References EVENT_FINISH_FIGHT_1, EVENT_FINISH_FIGHT_2, EVENT_FINISH_FIGHT_3, EVENT_FINISH_FIGHT_4, EVENT_FINISH_FIGHT_5, GO_HOLY_LIGHTNING, LightOfDawnPos, ScriptedAI::me, NPC_HIGHLORD_TIRION_FORDRING, SAY_LIGHT_OF_DAWN25, WorldObject::SummonCreature(), and TEMPSUMMON_TIMED_OR_CORPSE_DESPAWN.
Referenced by SummonedCreatureDies().
GetData()
uint32 npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::GetData (uint32 type) const inline override virtual
Reimplemented from UnitAI.
        {
            switch (type)
            {
                case WORLD_STATE_BATTLE_FOR_LIGHTS_HOPE_DEFENDERS_COUNT:
                    return defendersRemaining;
                case WORLD_STATE_BATTLE_FOR_LIGHTS_HOPE_SCOURGE_COUNT:
                    return scourgeRemaining;
                case WORLD_STATE_BATTLE_FOR_LIGHTS_HOPE_SOLDIERS_ENABLE:
                    return me->IsAlive() && (startTimeRemaining || battleStarted);
                case WORLD_STATE_BATTLE_FOR_LIGHTS_HOPE_COUNTDOWN_ENABLE:
                    return me->IsAlive() && startTimeRemaining;
                case WORLD_STATE_BATTLE_FOR_LIGHTS_HOPE_COUNTDOWN_TIME:
                    return startTimeRemaining;
                case WORLD_STATE_BATTLE_FOR_LIGHTS_HOPE_EVENT_BEGIN_ENABLE:
                    return me->IsAlive() && !startTimeRemaining && battleStarted;
            }
            return 0;
        }
References battleStarted, defendersRemaining, Unit::IsAlive(), ScriptedAI::me, scourgeRemaining, startTimeRemaining, WORLD_STATE_BATTLE_FOR_LIGHTS_HOPE_COUNTDOWN_ENABLE, WORLD_STATE_BATTLE_FOR_LIGHTS_HOPE_COUNTDOWN_TIME, WORLD_STATE_BATTLE_FOR_LIGHTS_HOPE_DEFENDERS_COUNT, WORLD_STATE_BATTLE_FOR_LIGHTS_HOPE_EVENT_BEGIN_ENABLE, WORLD_STATE_BATTLE_FOR_LIGHTS_HOPE_SCOURGE_COUNT, and WORLD_STATE_BATTLE_FOR_LIGHTS_HOPE_SOLDIERS_ENABLE.
Referenced by SendInitialWorldStates(), and SummonedCreatureDies().
GetEntryFromSummons()
Creature * npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::GetEntryFromSummons (uint32 entry) inline
        {
            for (SummonList::const_iterator itr = summons.begin(); itr != summons.end(); ++itr)
                if (Creature* summon = ObjectAccessor::GetCreature(*me, *itr))
                    if (summon->GetEntry() == entry)
                        return summon;
            return nullptr;
        }
References SummonList::begin(), SummonList::end(), ObjectAccessor::GetCreature(), ScriptedAI::me, and summons.
Referenced by UpdateAI().
JustDied()
void npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::JustDied (Unit *) inline override virtual
Reimplemented from CreatureAI.
        {
            summons.DespawnAll();
            me->SetCorpseDelay(3 * 60);
            me->SetRespawnTime(3 * 60);
        }
References SummonList::DespawnAll(), ScriptedAI::me, Creature::SetCorpseDelay(), Creature::SetRespawnTime(), and summons.
JustEngagedWith()
void npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::JustEngagedWith (Unit *) inline override virtual
Called for reaction when initially engaged.
Reimplemented from CreatureAI.
        {
            if (battleStarted != ENCOUNTER_STATE_FIGHT)
                return;
            events.RescheduleEvent(EVENT_SPELL_ANTI_MAGIC_ZONE, 15s);
            events.RescheduleEvent(EVENT_SPELL_DEATH_STRIKE, 8s);
            events.RescheduleEvent(EVENT_SPELL_DEATH_EMBRACE, 5s);
            events.RescheduleEvent(EVENT_SPELL_UNHOLY_BLIGHT, 10s);
            events.RescheduleEvent(EVENT_SPELL_DARION_MOD_DAMAGE, 500ms);
        }
References battleStarted, ENCOUNTER_STATE_FIGHT, EVENT_SPELL_ANTI_MAGIC_ZONE, EVENT_SPELL_DARION_MOD_DAMAGE, EVENT_SPELL_DEATH_EMBRACE, EVENT_SPELL_DEATH_STRIKE, and EVENT_SPELL_UNHOLY_BLIGHT.
JustRespawned()
void npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::JustRespawned () inline override virtual
Reimplemented from CreatureAI.
        {
            events.Reset();
            summons.DespawnAll();
            me->SetImmuneToAll(true);
            me->LoadEquipment(1, true);
            me->ReplaceAllNpcFlags(UNIT_NPC_FLAG_GOSSIP | UNIT_NPC_FLAG_QUESTGIVER);
            me->SetStandState(UNIT_STAND_STATE_STAND);
            me->SetVisible(true);
            me->setActive(true);
            me->SetWalk(false);
            battleStarted = ENCOUNTER_STATE_NONE;
            startTimeRemaining = 0;
            defendersRemaining = 0;
            scourgeRemaining = 0;
            SendInitialWorldStates();
            me->SummonCreatureGroup(30);
        }
References battleStarted, defendersRemaining, SummonList::DespawnAll(), ENCOUNTER_STATE_NONE, Creature::LoadEquipment(), ScriptedAI::me, Unit::ReplaceAllNpcFlags(), scourgeRemaining, SendInitialWorldStates(), WorldObject::setActive(), Unit::SetImmuneToAll(), Unit::SetStandState(), Unit::SetVisible(), Creature::SetWalk(), startTimeRemaining, WorldObject::SummonCreatureGroup(), summons, UNIT_NPC_FLAG_GOSSIP, UNIT_NPC_FLAG_QUESTGIVER, and UNIT_STAND_STATE_STAND.
Referenced by Reset().
JustSummoned()
void npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::JustSummoned (Creature * cr) inline override virtual
Reimplemented from CreatureAI.
        {
            summons.Summon(cr);
            if (me->IsInCombat() && cr->GetEntry() != NPC_HIGHLORD_TIRION_FORDRING && battleStarted == ENCOUNTER_STATE_FIGHT)
            {
                Position pos = LightOfDawnFightPos[urand(0, 9)];
                if (Unit* target = cr->SelectNearbyTarget(nullptr, 10.0f))
                    if (target->IsCreature())
                        target->GetMotionMaster()->MoveCharge(pos.GetPositionX(), pos.GetPositionY(), pos.GetPositionZ(), me->GetSpeed(MOVE_RUN));
                cr->GetMotionMaster()->MoveCharge(pos.GetPositionX(), pos.GetPositionY(), pos.GetPositionZ(), me->GetSpeed(MOVE_RUN));
            }
            if (battleStarted == ENCOUNTER_STATE_OUTRO && cr->GetEntry() == NPC_DEFENDER_OF_THE_LIGHT)
            {
                cr->SetReactState(REACT_PASSIVE);
                cr->SetImmuneToAll(true);
                cr->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_STATE_READY1H);
                cr->HandleEmoteCommand(EMOTE_STATE_READY1H);
            }
        }
References battleStarted, EMOTE_STATE_READY1H, ENCOUNTER_STATE_FIGHT, ENCOUNTER_STATE_OUTRO, Object::GetEntry(), Unit::GetMotionMaster(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Unit::GetSpeed(), Unit::HandleEmoteCommand(), Unit::IsInCombat(), LightOfDawnFightPos, ScriptedAI::me, MOVE_RUN, MotionMaster::MoveCharge(), NPC_DEFENDER_OF_THE_LIGHT, NPC_HIGHLORD_TIRION_FORDRING, REACT_PASSIVE, Unit::SelectNearbyTarget(), Unit::SetImmuneToAll(), Creature::SetReactState(), Unit::SetUInt32Value(), SummonList::Summon(), summons, UNIT_NPC_EMOTESTATE, and urand().
MovementInform()
void npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::MovementInform (uint32 type, uint32 point) inline override virtual
Reimplemented from CreatureAI.
        {
            if (type == POINT_MOTION_TYPE && point == 2)
            {
                me->RemoveAurasDueToSpell(SPELL_THE_LIGHT_OF_DAWN);
                Talk(EMOTE_LIGHT_OF_DAWN05);
                events.Reset();
                events.ScheduleEvent(EVENT_OUTRO_SCENE_1, 2s);
                events.ScheduleEvent(EVENT_OUTRO_SCENE_2, 19s);
                events.ScheduleEvent(EVENT_OUTRO_SCENE_3, 38s);
                events.ScheduleEvent(EVENT_OUTRO_SCENE_4, 50s);
                events.ScheduleEvent(EVENT_OUTRO_SCENE_5, 62s);
                events.ScheduleEvent(EVENT_OUTRO_SCENE_6, 68s);
                events.ScheduleEvent(EVENT_OUTRO_SCENE_7, 71s);
                events.ScheduleEvent(EVENT_OUTRO_SCENE_8, 72s);
                events.ScheduleEvent(EVENT_OUTRO_SCENE_9, 74s);
                events.ScheduleEvent(EVENT_OUTRO_SCENE_10, 77s);
                events.ScheduleEvent(EVENT_OUTRO_SCENE_11, 79s);
                events.ScheduleEvent(EVENT_OUTRO_SCENE_12, 82s);
                events.ScheduleEvent(EVENT_OUTRO_SCENE_13, 85s);
                events.ScheduleEvent(EVENT_OUTRO_SCENE_14, 92s);
                events.ScheduleEvent(EVENT_OUTRO_SCENE_15, 98s);
                events.ScheduleEvent(EVENT_OUTRO_SCENE_16, 105s);
                events.ScheduleEvent(EVENT_OUTRO_SCENE_17, 120s);
                events.ScheduleEvent(EVENT_OUTRO_SCENE_18, 131s);
                events.ScheduleEvent(EVENT_OUTRO_SCENE_19, 158s);
            }
        }
References EMOTE_LIGHT_OF_DAWN05, EVENT_OUTRO_SCENE_1, EVENT_OUTRO_SCENE_10, EVENT_OUTRO_SCENE_11, EVENT_OUTRO_SCENE_12, EVENT_OUTRO_SCENE_13, EVENT_OUTRO_SCENE_14, EVENT_OUTRO_SCENE_15, EVENT_OUTRO_SCENE_16, EVENT_OUTRO_SCENE_17, EVENT_OUTRO_SCENE_18, EVENT_OUTRO_SCENE_19, EVENT_OUTRO_SCENE_2, EVENT_OUTRO_SCENE_3, EVENT_OUTRO_SCENE_4, EVENT_OUTRO_SCENE_5, EVENT_OUTRO_SCENE_6, EVENT_OUTRO_SCENE_7, EVENT_OUTRO_SCENE_8, EVENT_OUTRO_SCENE_9, ScriptedAI::me, POINT_MOTION_TYPE, Unit::RemoveAurasDueToSpell(), and SPELL_THE_LIGHT_OF_DAWN.
Reset()
void npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::Reset () inline override virtual
Reimplemented from UnitAI.
        {
            if (resetExecuted)
                return;
            resetExecuted = true;
            JustRespawned();
        }
References JustRespawned(), and resetExecuted.
SendInitialWorldStates()
void npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::SendInitialWorldStates () inline
        {
            SendUpdateWorldState(WORLD_STATE_BATTLE_FOR_LIGHTS_HOPE_DEFENDERS_COUNT, GetData(WORLD_STATE_BATTLE_FOR_LIGHTS_HOPE_DEFENDERS_COUNT));
            SendUpdateWorldState(WORLD_STATE_BATTLE_FOR_LIGHTS_HOPE_SCOURGE_COUNT, GetData(WORLD_STATE_BATTLE_FOR_LIGHTS_HOPE_SCOURGE_COUNT));
            SendUpdateWorldState(WORLD_STATE_BATTLE_FOR_LIGHTS_HOPE_SOLDIERS_ENABLE, GetData(WORLD_STATE_BATTLE_FOR_LIGHTS_HOPE_SOLDIERS_ENABLE));
            SendUpdateWorldState(WORLD_STATE_BATTLE_FOR_LIGHTS_HOPE_COUNTDOWN_ENABLE, GetData(WORLD_STATE_BATTLE_FOR_LIGHTS_HOPE_COUNTDOWN_ENABLE));
            SendUpdateWorldState(WORLD_STATE_BATTLE_FOR_LIGHTS_HOPE_COUNTDOWN_TIME, GetData(WORLD_STATE_BATTLE_FOR_LIGHTS_HOPE_COUNTDOWN_TIME));
            SendUpdateWorldState(WORLD_STATE_BATTLE_FOR_LIGHTS_HOPE_EVENT_BEGIN_ENABLE, GetData(WORLD_STATE_BATTLE_FOR_LIGHTS_HOPE_EVENT_BEGIN_ENABLE));
        }
References GetData(), SendUpdateWorldState(), WORLD_STATE_BATTLE_FOR_LIGHTS_HOPE_COUNTDOWN_ENABLE, WORLD_STATE_BATTLE_FOR_LIGHTS_HOPE_COUNTDOWN_TIME, WORLD_STATE_BATTLE_FOR_LIGHTS_HOPE_DEFENDERS_COUNT, WORLD_STATE_BATTLE_FOR_LIGHTS_HOPE_EVENT_BEGIN_ENABLE, WORLD_STATE_BATTLE_FOR_LIGHTS_HOPE_SCOURGE_COUNT, and WORLD_STATE_BATTLE_FOR_LIGHTS_HOPE_SOLDIERS_ENABLE.
Referenced by DoAction(), and JustRespawned().
SendUpdateWorldState()
void npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::SendUpdateWorldState (uint32 id, uint32 state) inline
        {
            Map::PlayerList const& players = me->GetMap()->GetPlayers();
            if (!players.IsEmpty())
                for (Map::PlayerList::const_iterator itr = players.begin(); itr != players.end(); ++itr)
                    if (Player* player = itr->GetSource())
                        if (player->GetPhaseMask() & 128) // Xinef: client skips players without chapter 5 aura anyway, speedup
                            player->SendUpdateWorldState(id, state);
        }
References MapRefMgr::begin(), MapRefMgr::end(), WorldObject::GetMap(), Map::GetPlayers(), LinkedListHead::IsEmpty(), and ScriptedAI::me.
Referenced by SendInitialWorldStates(), SummonedCreatureDies(), and UpdateAI().
SummonedCreatureDies()
void npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::SummonedCreatureDies (Creature * creature, Unit *) inline override virtual
Reimplemented from CreatureAI.
        {
            // Refill Armies and update counters
            if (battleStarted != ENCOUNTER_STATE_FIGHT)
                return;
            me->m_Events.AddEventAtOffset(new DelayedSummonEvent(me, creature->GetEntry(), *creature), 3s);
            if (creature->GetEntry() >= NPC_RAMPAGING_ABOMINATION)
            {
                --scourgeRemaining;
                SendUpdateWorldState(WORLD_STATE_BATTLE_FOR_LIGHTS_HOPE_SCOURGE_COUNT, GetData(WORLD_STATE_BATTLE_FOR_LIGHTS_HOPE_SCOURGE_COUNT));
            }
            else
            {
                --defendersRemaining;
                SendUpdateWorldState(WORLD_STATE_BATTLE_FOR_LIGHTS_HOPE_DEFENDERS_COUNT, GetData(WORLD_STATE_BATTLE_FOR_LIGHTS_HOPE_DEFENDERS_COUNT));
                if (defendersRemaining == 200)
                    FinishFight();
            }
        }
References EventProcessor::AddEventAtOffset(), battleStarted, defendersRemaining, ENCOUNTER_STATE_FIGHT, FinishFight(), GetData(), Object::GetEntry(), WorldObject::m_Events, ScriptedAI::me, NPC_RAMPAGING_ABOMINATION, scourgeRemaining, SendUpdateWorldState(), WORLD_STATE_BATTLE_FOR_LIGHTS_HOPE_DEFENDERS_COUNT, and WORLD_STATE_BATTLE_FOR_LIGHTS_HOPE_SCOURGE_COUNT.
UpdateAI()
void npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Implements UnitAI.
        {
            events.Update(diff);
            uint32 eventId = events.ExecuteEvent();
            switch (eventId)
            {
                case EVENT_START_COUNTDOWN_1:
                    SendUpdateWorldState(WORLD_STATE_BATTLE_FOR_LIGHTS_HOPE_COUNTDOWN_TIME, 4);
                    break;
                case EVENT_START_COUNTDOWN_2:
                    SendUpdateWorldState(WORLD_STATE_BATTLE_FOR_LIGHTS_HOPE_COUNTDOWN_TIME, 3);
                    break;
                case EVENT_START_COUNTDOWN_3:
                    SendUpdateWorldState(WORLD_STATE_BATTLE_FOR_LIGHTS_HOPE_COUNTDOWN_TIME, 2);
                    break;
                case EVENT_START_COUNTDOWN_4:
                    Talk(SAY_LIGHT_OF_DAWN02);
                    SendUpdateWorldState(WORLD_STATE_BATTLE_FOR_LIGHTS_HOPE_COUNTDOWN_TIME, 1);
                    break;
                case EVENT_START_COUNTDOWN_5:
                    battleStarted = ENCOUNTER_STATE_FIGHT;
                    me->ReplaceAllNpcFlags(UNIT_NPC_FLAG_NONE);
                    Talk(SAY_LIGHT_OF_DAWN04); // Wrong order in DB!
                    SendUpdateWorldState(WORLD_STATE_BATTLE_FOR_LIGHTS_HOPE_COUNTDOWN_TIME, 0);
                    SendUpdateWorldState(WORLD_STATE_BATTLE_FOR_LIGHTS_HOPE_COUNTDOWN_ENABLE, 0);
                    SendUpdateWorldState(WORLD_STATE_BATTLE_FOR_LIGHTS_HOPE_EVENT_BEGIN_ENABLE, 1);
                    break;
                case EVENT_START_COUNTDOWN_6:
                case EVENT_START_COUNTDOWN_7:
                case EVENT_START_COUNTDOWN_8:
                case EVENT_START_COUNTDOWN_9:
                case EVENT_START_COUNTDOWN_10:
                    if (eventId == EVENT_START_COUNTDOWN_6)
                    {
                        Talk(SAY_LIGHT_OF_DAWN05);
                        me->CastSpell(me, SPELL_CAMERA_SHAKE_INIT, true);
                    }
                    else
                        me->CastSpell(me, SPELL_CAMERA_SHAKE, true);
                    me->SummonCreatureGroup(eventId - EVENT_START_COUNTDOWN_6);
                    break;
                case EVENT_START_COUNTDOWN_11:
                    Talk(SAY_LIGHT_OF_DAWN06);
                    break;
                case EVENT_START_COUNTDOWN_12:
                    summons.DoAction(ACTION_PLAY_EMOTE);
                    break;
                case EVENT_START_COUNTDOWN_13:
                    {
                        uint8 first = 1;
                        for (SummonList::const_iterator itr = summons.begin(); itr != summons.end(); ++itr)
{
                            if (Creature* summon = ObjectAccessor::GetCreature(*me, *itr))
{
                                Position pos = LightOfDawnPos[first];
                                summon->SetHomePosition(pos);
                                summon->GetMotionMaster()->MovePoint(1, pos.GetPositionX(), pos.GetPositionY(), pos.GetPositionZ(), FORCED_MOVEMENT_NONE, 0.f, 0.f, true, false);
                            }
                            first = first == 0 ? 1 : 0;
                        }
                        Position pos = LightOfDawnPos[first];
                        me->SetHomePosition(pos);
                        me->SetWalk(false);
                        me->GetMotionMaster()->MovePoint(1, pos.GetPositionX(), pos.GetPositionY(), pos.GetPositionZ(), FORCED_MOVEMENT_NONE, 0.f, 0.f, true, true);
                        DoCastSelf(SPELL_THE_MIGHT_OF_MOGRAINE, true);
                        break;
                    }
                case EVENT_START_COUNTDOWN_14:
                    me->SetImmuneToAll(false);
                    me->SummonCreatureGroup(5);
                    return;
                case EVENT_FINISH_FIGHT_1:
                    summons.DespawnEntry(NPC_DEFENDER_OF_THE_LIGHT);
                    battleStarted = ENCOUNTER_STATE_OUTRO;
                    break;
                case EVENT_FINISH_FIGHT_2:
                    {
                        summons.DespawnEntry(NPC_RAMPAGING_ABOMINATION);
                        summons.DespawnEntry(NPC_ACHERUS_GHOUL);
                        summons.DespawnEntry(NPC_WARRIOR_OF_THE_FROZEN_WASTES);
                        summons.DespawnEntry(NPC_FLESH_BEHEMOTH);
                        summons.DespawnEntry(NPC_DEFENDER_OF_THE_LIGHT);
                        if (Creature* orbaz = GetEntryFromSummons(NPC_ORBAZ_BLOODBANE))
{
                            orbaz->SetReactState(REACT_PASSIVE);
                            orbaz->AI()->Talk(EMOTE_LIGHT_OF_DAWN04);
                            orbaz->GetMotionMaster()->MovePoint(2, LightOfDawnPos[2], FORCED_MOVEMENT_NONE, 0.f, true, true);
                            orbaz->DespawnOrUnsummon(7s);
                        }
                        for (SummonList::const_iterator itr = summons.begin(); itr != summons.end(); ++itr)
                            if (Creature* summon = ObjectAccessor::GetCreature(*me, *itr))
{
                                summon->CombatStop(true);
                                summon->GetThreatMgr().ClearAllThreat();
                                summon->SetUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
                                summon->SetImmuneToAll(true);
                                summon->SetReactState(REACT_PASSIVE);
                                summon->GetMotionMaster()->Clear(false);
                            }
                        me->CombatStop(true);
                        me->GetThreatMgr().ClearAllThreat();
                        me->SetImmuneToAll(true);
                        me->SetReactState(REACT_PASSIVE);
                        me->GetMotionMaster()->Clear(false);
                        // Position main stars
                        summons.DoAction(ACTION_POSITION_NPCS);
                        me->SummonCreature(NPC_DEFENDER_OF_THE_LIGHT, 2276.66f, -5273.60f, 81.86f, 5.14f, TEMPSUMMON_CORPSE_DESPAWN);
                        me->SummonCreature(NPC_DEFENDER_OF_THE_LIGHT, 2272.11f, -5279.08f, 82.01f, 5.69f, TEMPSUMMON_CORPSE_DESPAWN);
                        me->SummonCreature(NPC_DEFENDER_OF_THE_LIGHT, 2285.11f, -5276.73f, 82.08f, 4.23f, TEMPSUMMON_CORPSE_DESPAWN);
                        me->SummonCreature(NPC_DEFENDER_OF_THE_LIGHT, 2290.06f, -5286.41f, 82.51f, 3.16f, TEMPSUMMON_CORPSE_DESPAWN);
                        break;
                    }
                case EVENT_FINISH_FIGHT_3:
                    if (Creature* koltira = GetEntryFromSummons(NPC_KOLTIRA_DEATHWEAVER))
                    {
                        koltira->SetWalk(true);
                        koltira->SetHomePosition(*koltira);
                        koltira->CastSpell(koltira, SPELL_THE_LIGHT_OF_DAWN, false);
                        koltira->GetMotionMaster()->MoveCharge(LightOfDawnPos[3].GetPositionX(), LightOfDawnPos[3].GetPositionY(), LightOfDawnPos[3].GetPositionZ(), 4.0f, 2);
                    }
                    break;
                case EVENT_FINISH_FIGHT_4:
                    if (Creature* thassarin = GetEntryFromSummons(NPC_THASSARIAN))
                    {
                        thassarin->SetWalk(true);
                        thassarin->SetHomePosition(*thassarin);
                        thassarin->CastSpell(thassarin, SPELL_THE_LIGHT_OF_DAWN, false);
                        thassarin->GetMotionMaster()->MoveCharge(LightOfDawnPos[4].GetPositionX(), LightOfDawnPos[4].GetPositionY(), LightOfDawnPos[4].GetPositionZ(), 4.0f, 2);
                    }
                    break;
                case EVENT_FINISH_FIGHT_5:
                    me->SetWalk(true);
                    me->SetHomePosition(*me);
                    me->RemoveAllAuras();
                    me->CastSpell(me, SPELL_THE_LIGHT_OF_DAWN, false);
                    me->GetMotionMaster()->MoveCharge(LightOfDawnPos[5].GetPositionX(), LightOfDawnPos[5].GetPositionY(), LightOfDawnPos[5].GetPositionZ(), 4.0f, 2);
                    if (Creature* tirion = GetEntryFromSummons(NPC_HIGHLORD_TIRION_FORDRING))
                        tirion->AI()->Talk(SAY_LIGHT_OF_DAWN26);
                    break;
                case EVENT_OUTRO_SCENE_1:
                    me->SetStandState(UNIT_STAND_STATE_KNEEL);
                    me->SetFacingTo(4.8f);
                    Talk(SAY_LIGHT_OF_DAWN27);
                    break;
                case EVENT_OUTRO_SCENE_2:
                    if (Creature* tirion = GetEntryFromSummons(NPC_HIGHLORD_TIRION_FORDRING))
                        tirion->AI()->Talk(SAY_LIGHT_OF_DAWN28);
                    break;
                case EVENT_OUTRO_SCENE_3:
                    if (Creature* tirion = GetEntryFromSummons(NPC_HIGHLORD_TIRION_FORDRING))
                        tirion->AI()->Talk(SAY_LIGHT_OF_DAWN29);
                    break;
                case EVENT_OUTRO_SCENE_4:
                    if (Creature* tirion = GetEntryFromSummons(NPC_HIGHLORD_TIRION_FORDRING))
                        tirion->AI()->Talk(SAY_LIGHT_OF_DAWN30);
                    break;
                case EVENT_OUTRO_SCENE_5:
                    me->SetStandState(UNIT_STAND_STATE_STAND);
                    Talk(SAY_LIGHT_OF_DAWN31);
                    break;
                case EVENT_OUTRO_SCENE_6:
                    if (Creature* alex = me->SummonCreature(NPC_HIGHLORD_ALEXANDROS_MOGRAINE, LightOfDawnPos[7].GetPositionX(), LightOfDawnPos[7].GetPositionY(), LightOfDawnPos[7].GetPositionZ(), LightOfDawnPos[7].GetOrientation(), TEMPSUMMON_TIMED_OR_CORPSE_DESPAWN, 300000))
                    {
                        alex->SetUnitFlag(UNIT_FLAG_NOT_SELECTABLE);
                        alex->GetMotionMaster()->MovePoint(0, LightOfDawnPos[8].GetPositionX(), LightOfDawnPos[8].GetPositionY(), LightOfDawnPos[8].GetPositionZ());
                        alex->CastSpell(alex, SPELL_ALEXANDROS_MOGRAINE_SPAWN, true);
                        //alex->AI()->Talk(EMOTE_LIGHT_OF_DAWN06);
                    }
                    break;
                case EVENT_OUTRO_SCENE_7:
                    if (Creature* alex = GetEntryFromSummons(NPC_HIGHLORD_ALEXANDROS_MOGRAINE))
                    {
                        alex->RemoveUnitFlag(UNIT_FLAG_NOT_SELECTABLE);
                        alex->AI()->Talk(SAY_LIGHT_OF_DAWN32);
                        me->SetFacingToObject(alex);
                    }
                    break;
                case EVENT_OUTRO_SCENE_8:
                    Talk(SAY_LIGHT_OF_DAWN33);
                    break;
                case EVENT_OUTRO_SCENE_9:
                    me->SetStandState(UNIT_STAND_STATE_KNEEL);
                    Talk(SAY_LIGHT_OF_DAWN34);
                    break;
                case EVENT_OUTRO_SCENE_10:
                    if (Creature* darion = me->SummonCreature(NPC_DARION_MOGRAINE, LightOfDawnPos[9].GetPositionX(), LightOfDawnPos[9].GetPositionY(), LightOfDawnPos[9].GetPositionZ(), LightOfDawnPos[9].GetOrientation(), TEMPSUMMON_TIMED_OR_CORPSE_DESPAWN, 300000))
                    {
                        darion->AI()->Talk(SAY_LIGHT_OF_DAWN35);
                        darion->SetWalk(false);
                    }
                    break;
                case EVENT_OUTRO_SCENE_11:
                    if (Creature* darion = GetEntryFromSummons(NPC_DARION_MOGRAINE))
                    {
                        //darion->AI()->Talk(EMOTE_LIGHT_OF_DAWN07);
                        darion->GetMotionMaster()->MovePoint(0, LightOfDawnPos[10].GetPositionX(), LightOfDawnPos[10].GetPositionY(), LightOfDawnPos[10].GetPositionZ());
                    }
                    break;
                case EVENT_OUTRO_SCENE_12:
                    if (Creature* darion = GetEntryFromSummons(NPC_DARION_MOGRAINE))
                        darion->AI()->Talk(EMOTE_LIGHT_OF_DAWN08);
                    break;
                case EVENT_OUTRO_SCENE_13:
                    if (Creature* darion = GetEntryFromSummons(NPC_DARION_MOGRAINE))
                        darion->AI()->Talk(SAY_LIGHT_OF_DAWN36);
                    break;
                case EVENT_OUTRO_SCENE_14:
                    if (Creature* alex = GetEntryFromSummons(NPC_HIGHLORD_ALEXANDROS_MOGRAINE))
                        alex->AI()->Talk(SAY_LIGHT_OF_DAWN37);
                    break;
                case EVENT_OUTRO_SCENE_15:
                    if (Creature* darion = GetEntryFromSummons(NPC_DARION_MOGRAINE))
                        darion->AI()->Talk(SAY_LIGHT_OF_DAWN38);
                    break;
                case EVENT_OUTRO_SCENE_16:
                    if (Creature* alex = GetEntryFromSummons(NPC_HIGHLORD_ALEXANDROS_MOGRAINE))
                        alex->AI()->Talk(SAY_LIGHT_OF_DAWN39);
                    if (Creature* tirion = GetEntryFromSummons(NPC_HIGHLORD_TIRION_FORDRING))
                        tirion->GetMotionMaster()->MovePoint(0, LightOfDawnPos[11].GetPositionX(), LightOfDawnPos[11].GetPositionY(), LightOfDawnPos[11].GetPositionZ());
                    break;
                case EVENT_OUTRO_SCENE_17:
                    if (Creature* darion = GetEntryFromSummons(NPC_DARION_MOGRAINE))
                        darion->AI()->Talk(SAY_LIGHT_OF_DAWN40);
                    break;
                case EVENT_OUTRO_SCENE_18:
                    if (Creature* alex = GetEntryFromSummons(NPC_HIGHLORD_ALEXANDROS_MOGRAINE))
                        alex->AI()->Talk(SAY_LIGHT_OF_DAWN41);
                    if (Creature* darion = GetEntryFromSummons(NPC_DARION_MOGRAINE))
                        darion->DespawnOrUnsummon(3s);
                    break;
                case EVENT_OUTRO_SCENE_19:
                    if (Creature* alex = GetEntryFromSummons(NPC_HIGHLORD_ALEXANDROS_MOGRAINE))
                        alex->AI()->Talk(SAY_LIGHT_OF_DAWN42);
                    events.Reset();
                    events.ScheduleEvent(EVENT_OUTRO_SCENE_20, 4s);
                    events.ScheduleEvent(EVENT_OUTRO_SCENE_21, 4s + 500ms);
                    events.ScheduleEvent(EVENT_OUTRO_SCENE_22, 7s);
                    events.ScheduleEvent(EVENT_OUTRO_SCENE_23, 9s);
                    events.ScheduleEvent(EVENT_OUTRO_SCENE_24, 14s);
                    events.ScheduleEvent(EVENT_OUTRO_SCENE_25, 21s + 200ms);
                    events.ScheduleEvent(EVENT_OUTRO_SCENE_26, 22s + 500ms);
                    events.ScheduleEvent(EVENT_OUTRO_SCENE_27, 24s);
                    events.ScheduleEvent(EVENT_OUTRO_SCENE_28, 28s);
                    events.ScheduleEvent(EVENT_OUTRO_SCENE_29, 34s);
                    events.ScheduleEvent(EVENT_OUTRO_SCENE_30, 36s);
                    events.ScheduleEvent(EVENT_OUTRO_SCENE_31, 51s);
                    events.ScheduleEvent(EVENT_OUTRO_SCENE_32, 68s);
                    events.ScheduleEvent(EVENT_OUTRO_SCENE_33, 73s);
                    events.ScheduleEvent(EVENT_OUTRO_SCENE_34, 76s);
                    events.ScheduleEvent(EVENT_OUTRO_SCENE_35, 77s);
                    events.ScheduleEvent(EVENT_OUTRO_SCENE_36, 81s);
                    break;
                case EVENT_OUTRO_SCENE_20:
                    if (Creature* lk = me->SummonCreature(NPC_THE_LICH_KING, LightOfDawnPos[12].GetPositionX(), LightOfDawnPos[12].GetPositionY(), LightOfDawnPos[12].GetPositionZ(), LightOfDawnPos[12].GetOrientation(), TEMPSUMMON_TIMED_OR_CORPSE_DESPAWN, 300000))
                        lk->AI()->Talk(SAY_LIGHT_OF_DAWN43);
                    break;
                case EVENT_OUTRO_SCENE_21:
                    if (Creature* lk = GetEntryFromSummons(NPC_THE_LICH_KING))
                        lk->CastSpell(lk, SPELL_ICEBOUND_VISAGE, true);
                    break;
                case EVENT_OUTRO_SCENE_22:
                    if (Creature* lk = GetEntryFromSummons(NPC_THE_LICH_KING))
                    {
                        lk->AI()->Talk(SAY_LIGHT_OF_DAWN45);
                        if (Creature* alex = GetEntryFromSummons(NPC_HIGHLORD_ALEXANDROS_MOGRAINE))
{
                            alex->RemoveAllAuras();
                            lk->CastSpell(alex, SPELL_SOUL_FEAST_ALEX, false);
                        }
                    }
                    break;
                case EVENT_OUTRO_SCENE_23:
                    if (Creature* alex = GetEntryFromSummons(NPC_HIGHLORD_ALEXANDROS_MOGRAINE))
                    {
                        alex->DespawnOrUnsummon(5s);
                        alex->SetVisible(false);
                    }
                    break;
                case EVENT_OUTRO_SCENE_24:
                    me->SetStandState(UNIT_STAND_STATE_STAND);
                    Talk(SAY_LIGHT_OF_DAWN44);
                    break;
                case EVENT_OUTRO_SCENE_25:
                    if (Creature* lk = GetEntryFromSummons(NPC_THE_LICH_KING))
                        lk->GetMotionMaster()->MovePoint(0, LightOfDawnPos[13].GetPositionX(), LightOfDawnPos[13].GetPositionY(), LightOfDawnPos[13].GetPositionZ());
                    break;
                case EVENT_OUTRO_SCENE_26:
                    me->CastSpell(me, SPELL_MOGRAINE_CHARGE, false);
                    break;
                case EVENT_OUTRO_SCENE_27:
                    if (Creature* lk = GetEntryFromSummons(NPC_THE_LICH_KING))
                    {
                        lk->AI()->Talk(SAY_LIGHT_OF_DAWN46);
                        // Mograine's charge puts him inside the Lich King's collision, so we need to teleport him out
                        // Otherwise, Rebuke will kick him the wrong direction
                        me->NearTeleportTo(2279.7493f, -5258.1f, 80.065f, 4.3419204f);
                        lk->m_Events.AddEventAtOffset([&, lk] {
                            lk->CastSpell(me, SPELL_REBUKE, false);
                        }, 1s);
                    }
                    break;
                case EVENT_OUTRO_SCENE_28:
                    me->SetStandState(UNIT_STAND_STATE_KNEEL);
                    if (Creature* tirion = GetEntryFromSummons(NPC_HIGHLORD_TIRION_FORDRING))
                    {
                        tirion->AI()->Talk(SAY_LIGHT_OF_DAWN47);
                        if (Creature* lk = GetEntryFromSummons(NPC_THE_LICH_KING))
                            tirion->SetFacingToObject(lk);
                    }
                    break;
                case EVENT_OUTRO_SCENE_29:
                    if (Creature* lk = GetEntryFromSummons(NPC_THE_LICH_KING))
                    {
                        lk->HandleEmoteCommand(EMOTE_ONESHOT_LAUGH);
                        lk->PlayDirectSound(14820);
                    }
                    break;
                case EVENT_OUTRO_SCENE_30:
                    if (Creature* lk = GetEntryFromSummons(NPC_THE_LICH_KING))
                        lk->AI()->Talk(SAY_LIGHT_OF_DAWN48);
                    break;
                case EVENT_OUTRO_SCENE_31:
                    if (Creature* lk = GetEntryFromSummons(NPC_THE_LICH_KING))
                        lk->AI()->Talk(SAY_LIGHT_OF_DAWN49);
                    break;
                case EVENT_OUTRO_SCENE_32:
                    if (Creature* lk = GetEntryFromSummons(NPC_THE_LICH_KING))
                    {
                        if (Creature* tirion = GetEntryFromSummons(NPC_HIGHLORD_TIRION_FORDRING))
{
                            lk->CastSpell(lk, SPELL_SOUL_FEAST_TIRION, false);
                            tirion->AI()->Talk(EMOTE_LIGHT_OF_DAWN12);
                        }
                        for (SummonList::const_iterator itr = summons.begin(); itr != summons.end(); ++itr)
                            if (Creature* summon = ObjectAccessor::GetCreature(*me, *itr))
                                if (summon->GetEntry() <= NPC_RIMBLAT_EARTHSHATTER && summon->GetEntry() != NPC_HIGHLORD_TIRION_FORDRING)
{
                                    float o = lk->GetAngle(summon);
                                    summon->RemoveUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
                                    summon->GetMotionMaster()->MovePoint(3, lk->GetPositionX() + 2.0f * cos(o), lk->GetPositionY() + 2.0f * std::sin(o), lk->GetPositionZ());
                                    summon->ToTempSummon()->SetTempSummonType(TEMPSUMMON_MANUAL_DESPAWN);
                                }
                    }
                    break;
                case EVENT_OUTRO_SCENE_33:
                    if (Creature* lk = GetEntryFromSummons(NPC_THE_LICH_KING))
                    {
                        lk->AI()->Talk(SAY_LIGHT_OF_DAWN51);
                        lk->CastSpell(lk, SPELL_APOCALYPSE, true);
                    }
                    break;
                case EVENT_OUTRO_SCENE_34:
                    for (SummonList::const_iterator itr = summons.begin(); itr != summons.end(); ++itr)
                        if (Creature* summon = ObjectAccessor::GetCreature(*me, *itr))
                            if (summon->GetEntry() <= NPC_RIMBLAT_EARTHSHATTER && summon->GetEntry() != NPC_HIGHLORD_TIRION_FORDRING)
                                Unit::Kill(summon, summon);
                    break;
                case EVENT_OUTRO_SCENE_35:
                    Talk(SAY_LIGHT_OF_DAWN52);
                    break;
                case EVENT_OUTRO_SCENE_36:
                    me->SetStandState(UNIT_STAND_STATE_STAND);
                    Talk(SAY_LIGHT_OF_DAWN53);
                    if (Creature* tirion = GetEntryFromSummons(NPC_HIGHLORD_TIRION_FORDRING))
                        me->SetFacingToObject(tirion);
                    events.Reset();
                    events.ScheduleEvent(EVENT_OUTRO_SCENE_37, 1s);
                    events.ScheduleEvent(EVENT_OUTRO_SCENE_38, 5s);
                    events.ScheduleEvent(EVENT_OUTRO_SCENE_39, 7s);
                    events.ScheduleEvent(EVENT_OUTRO_SCENE_40, 9s);
                    events.ScheduleEvent(EVENT_OUTRO_SCENE_41, 13s);
                    events.ScheduleEvent(EVENT_OUTRO_SCENE_42, 16s);
                    events.ScheduleEvent(EVENT_OUTRO_SCENE_43, 17s);
                    events.ScheduleEvent(EVENT_OUTRO_SCENE_44, 19s);
                    events.ScheduleEvent(EVENT_OUTRO_SCENE_45, 25s);
                    events.ScheduleEvent(EVENT_OUTRO_SCENE_46, 32s);
                    events.ScheduleEvent(EVENT_OUTRO_SCENE_47, 42s);
                    events.ScheduleEvent(EVENT_OUTRO_SCENE_48, 52s);
                    events.ScheduleEvent(EVENT_OUTRO_SCENE_49, 54s);
                    events.ScheduleEvent(EVENT_OUTRO_SCENE_50, 58s);
                    events.ScheduleEvent(EVENT_OUTRO_SCENE_51, 65s);
                    events.ScheduleEvent(EVENT_OUTRO_SCENE_52, 70s);
                    events.ScheduleEvent(EVENT_OUTRO_SCENE_53, 84s);
                    break;
                case EVENT_OUTRO_SCENE_37:
                    me->SetUInt32Value(UNIT_VIRTUAL_ITEM_SLOT_ID + 0, uint32(EQUIP_UNEQUIP));
                    me->CastSpell(me, SPELL_THROW_ASHBRINGER, true);
                    break;
                case EVENT_OUTRO_SCENE_38:
                    if (Creature* tirion = GetEntryFromSummons(NPC_HIGHLORD_TIRION_FORDRING))
                    {
                        tirion->RemoveAllAuras();
                        tirion->CastSpell(me, SPELL_REBIRTH_OF_THE_ASHBRINGER, true);
                        tirion->SummonGameObject(GO_LIGHT_OF_DAWN, tirion->GetPositionX(), tirion->GetPositionY(), tirion->GetPositionZ(), tirion->GetOrientation(), 0, 0, 0, 0, 180);
                        tirion->LoadEquipment(1, true);
                    }
                    me->SetStandState(UNIT_STAND_STATE_DEAD);
                    break;
                case EVENT_OUTRO_SCENE_39:
                    if (Creature* tirion = GetEntryFromSummons(NPC_HIGHLORD_TIRION_FORDRING))
                    {
                        tirion->RemoveAllAuras();
                        tirion->HandleEmoteCommand(EMOTE_ONESHOT_ROAR);
                    }
                    break;
                case EVENT_OUTRO_SCENE_40:
                    if (Creature* tirion = GetEntryFromSummons(NPC_HIGHLORD_TIRION_FORDRING))
                        tirion->AI()->Talk(SAY_LIGHT_OF_DAWN54);
                    break;
                case EVENT_OUTRO_SCENE_41:
                    if (Creature* lk = GetEntryFromSummons(NPC_THE_LICH_KING))
                        lk->AI()->Talk(SAY_LIGHT_OF_DAWN55);
                    break;
                case EVENT_OUTRO_SCENE_42:
                    if (Creature* tirion = GetEntryFromSummons(NPC_HIGHLORD_TIRION_FORDRING))
                        tirion->AI()->Talk(SAY_LIGHT_OF_DAWN56);
                    break;
                case EVENT_OUTRO_SCENE_43:
                    if (Creature* tirion = GetEntryFromSummons(NPC_HIGHLORD_TIRION_FORDRING))
                    {
                        tirion->CastSpell(tirion, SPELL_TIRION_CHARGE, true);
                        tirion->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_STATE_READY2H);
                        tirion->SetImmuneToAll(true);
                    }
                    break;
                case EVENT_OUTRO_SCENE_44:
                    if (Creature* lk = GetEntryFromSummons(NPC_THE_LICH_KING))
                        lk->AI()->Talk(SAY_LIGHT_OF_DAWN57);
                    break;
                case EVENT_OUTRO_SCENE_45:
                    if (Creature* lk = GetEntryFromSummons(NPC_THE_LICH_KING))
                        lk->AI()->Talk(SAY_LIGHT_OF_DAWN58);
                    break;
                case EVENT_OUTRO_SCENE_46:
                    if (Creature* lk = GetEntryFromSummons(NPC_THE_LICH_KING))
                        lk->AI()->Talk(SAY_LIGHT_OF_DAWN59);
                    break;
                case EVENT_OUTRO_SCENE_47:
                    if (Creature* lk = GetEntryFromSummons(NPC_THE_LICH_KING))
                    {
                        lk->CastSpell(lk, SPELL_EXIT_TELEPORT_VISUAL, true);
                        lk->DespawnOrUnsummon(1500ms);
                    }
                    if (Creature* tirion = GetEntryFromSummons(NPC_HIGHLORD_TIRION_FORDRING))
                    {
                        float o = me->GetAngle(tirion);
                        tirion->GetMotionMaster()->MovePoint(4, me->GetPositionX() + 2.0f * cos(o), me->GetPositionY() + 2.0f * std::sin(o), me->GetPositionZ(), FORCED_MOVEMENT_NONE, 0.f, 0.f, false);
                        tirion->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_ONESHOT_NONE);
                        tirion->SetFaction(FACTION_FRIENDLY);
                    }
                    break;
                case EVENT_OUTRO_SCENE_48:
                    if (Creature* tirion = GetEntryFromSummons(NPC_HIGHLORD_TIRION_FORDRING))
                        tirion->CastSpell(me, SPELL_LAY_ON_HANDS, false);
                    me->SetStandState(UNIT_STAND_STATE_KNEEL);
                    break;
                case EVENT_OUTRO_SCENE_49:
                    if (Creature* tirion = GetEntryFromSummons(NPC_HIGHLORD_TIRION_FORDRING))
                    {
                        tirion->AI()->Talk(SAY_LIGHT_OF_DAWN60);
                        tirion->SetWalk(true);
                    }
                    break;
                case EVENT_OUTRO_SCENE_50:
                    if (Creature* tirion = GetEntryFromSummons(NPC_HIGHLORD_TIRION_FORDRING))
                        tirion->GetMotionMaster()->MovePoint(4, LightOfDawnPos[14].GetPositionX(), LightOfDawnPos[14].GetPositionY(), LightOfDawnPos[14].GetPositionZ());
                    break;
                case EVENT_OUTRO_SCENE_51:
                    if (Creature* tirion = GetEntryFromSummons(NPC_HIGHLORD_TIRION_FORDRING))
                        tirion->GetMotionMaster()->MovePoint(4, LightOfDawnPos[15].GetPositionX(), LightOfDawnPos[15].GetPositionY(), LightOfDawnPos[15].GetPositionZ());
                    break;
                case EVENT_OUTRO_SCENE_52:
                    if (Creature* tirion = GetEntryFromSummons(NPC_HIGHLORD_TIRION_FORDRING))
                    {
                        tirion->SetFacingToObject(me);
                        tirion->AI()->Talk(SAY_LIGHT_OF_DAWN61);
                    }
                    break;
                case EVENT_OUTRO_SCENE_53:
                    if (Creature* tirion = GetEntryFromSummons(NPC_HIGHLORD_TIRION_FORDRING))
                        tirion->AI()->Talk(SAY_LIGHT_OF_DAWN62);
                    events.Reset();
                    events.ScheduleEvent(EVENT_OUTRO_SCENE_54, 6s);
                    events.ScheduleEvent(EVENT_OUTRO_SCENE_55, 14s);
                    events.ScheduleEvent(EVENT_OUTRO_SCENE_56, 27s);
                    events.ScheduleEvent(EVENT_OUTRO_SCENE_57, 37s);
                    events.ScheduleEvent(EVENT_OUTRO_SCENE_58, 44s);
                    events.ScheduleEvent(EVENT_OUTRO_SCENE_59, 50s);
                    events.ScheduleEvent(EVENT_OUTRO_SCENE_60, 63s);
                    events.ScheduleEvent(EVENT_OUTRO_SCENE_61, 150s);
                    break;
                case EVENT_OUTRO_SCENE_54:
                    if (Creature* tirion = GetEntryFromSummons(NPC_HIGHLORD_TIRION_FORDRING))
                        tirion->AI()->Talk(SAY_LIGHT_OF_DAWN63);
                    break;
                case EVENT_OUTRO_SCENE_55:
                    if (Creature* tirion = GetEntryFromSummons(NPC_HIGHLORD_TIRION_FORDRING))
                        tirion->AI()->Talk(SAY_LIGHT_OF_DAWN64);
                    break;
                case EVENT_OUTRO_SCENE_56:
                    if (Creature* tirion = GetEntryFromSummons(NPC_HIGHLORD_TIRION_FORDRING))
                        tirion->AI()->Talk(SAY_LIGHT_OF_DAWN65);
                    break;
                case EVENT_OUTRO_SCENE_57:
                    if (Creature* tirion = GetEntryFromSummons(NPC_HIGHLORD_TIRION_FORDRING))
                        tirion->AI()->Talk(SAY_LIGHT_OF_DAWN66);
                    break;
                case EVENT_OUTRO_SCENE_58:
                    if (Creature* tirion = GetEntryFromSummons(NPC_HIGHLORD_TIRION_FORDRING))
                        tirion->AI()->Talk(SAY_LIGHT_OF_DAWN67);
                    break;
                case EVENT_OUTRO_SCENE_59:
                    Talk(SAY_LIGHT_OF_DAWN68);
                    me->SetStandState(UNIT_STAND_STATE_STAND);
                    break;
                case EVENT_OUTRO_SCENE_60:
                    {
                        Map::PlayerList const& PlayerList = me->GetMap()->GetPlayers();
                        if (!PlayerList.IsEmpty())
{
                            for (Map::PlayerList::const_iterator i = PlayerList.begin(); i != PlayerList.end(); ++i)
                                if (i->GetSource()->IsAlive() && me->IsWithinDistInMap(i->GetSource(), 100))
                                    i->GetSource()->CastSpell(i->GetSource(), SPELL_THE_LIGHT_OF_DAWN_Q, false);
                        }
                        me->ReplaceAllNpcFlags(UNIT_NPC_FLAG_GOSSIP | UNIT_NPC_FLAG_QUESTGIVER);
                        break;
                    }
                case EVENT_OUTRO_SCENE_61:
                    summons.DespawnAll();
                    me->DespawnOrUnsummon(1ms);
                    events.Reset();
                    return;
            }
            if (battleStarted != ENCOUNTER_STATE_FIGHT)
                return;
            if (!UpdateVictim())
                return;
            switch (eventId)
            {
                case EVENT_SPELL_ANTI_MAGIC_ZONE:
                    DoCast(me, SPELL_ANTI_MAGIC_ZONE1);
                    events.RescheduleEvent(eventId, 30s, 45s);
                    break;
                case EVENT_SPELL_DEATH_STRIKE:
                    DoCastVictim(SPELL_DEATH_STRIKE);
                    events.RescheduleEvent(eventId, 5s, 35s);
                    break;
                case EVENT_SPELL_DEATH_EMBRACE:
                    DoCastVictim(SPELL_DEATH_EMBRACE);
                    events.RescheduleEvent(eventId, 45s, 60s);
                    break;
                case EVENT_SPELL_UNHOLY_BLIGHT:
                    DoCast(me, SPELL_UNHOLY_BLIGHT);
                    events.RescheduleEvent(eventId, 60s);
                    break;
                case EVENT_SPELL_DARION_MOD_DAMAGE:
                    DoCast(me, SPELL_DARION_MOD_DAMAGE);
                    Talk(SAY_LIGHT_OF_DAWN09);
                    events.RescheduleEvent(eventId, 15s, 25s);
                    break;
            }
            DoMeleeAttackIfReady();
        }
References ACTION_PLAY_EMOTE, ACTION_POSITION_NPCS, battleStarted, SummonList::begin(), MapRefMgr::begin(), Unit::CastSpell(), MotionMaster::Clear(), ThreatMgr::ClearAllThreat(), Unit::CombatStop(), SummonList::DespawnAll(), SummonList::DespawnEntry(), Creature::DespawnOrUnsummon(), SummonList::DoAction(), UnitAI::DoCast(), UnitAI::DoCastSelf(), UnitAI::DoCastVictim(), UnitAI::DoMeleeAttackIfReady(), EMOTE_LIGHT_OF_DAWN04, EMOTE_LIGHT_OF_DAWN08, EMOTE_LIGHT_OF_DAWN12, EMOTE_ONESHOT_LAUGH, EMOTE_ONESHOT_NONE, EMOTE_ONESHOT_ROAR, EMOTE_STATE_READY2H, ENCOUNTER_STATE_FIGHT, ENCOUNTER_STATE_OUTRO, SummonList::end(), MapRefMgr::end(), EQUIP_UNEQUIP, EVENT_FINISH_FIGHT_1, EVENT_FINISH_FIGHT_2, EVENT_FINISH_FIGHT_3, EVENT_FINISH_FIGHT_4, EVENT_FINISH_FIGHT_5, EVENT_OUTRO_SCENE_1, EVENT_OUTRO_SCENE_10, EVENT_OUTRO_SCENE_11, EVENT_OUTRO_SCENE_12, EVENT_OUTRO_SCENE_13, EVENT_OUTRO_SCENE_14, EVENT_OUTRO_SCENE_15, EVENT_OUTRO_SCENE_16, EVENT_OUTRO_SCENE_17, EVENT_OUTRO_SCENE_18, EVENT_OUTRO_SCENE_19, EVENT_OUTRO_SCENE_2, EVENT_OUTRO_SCENE_20, EVENT_OUTRO_SCENE_21, EVENT_OUTRO_SCENE_22, EVENT_OUTRO_SCENE_23, EVENT_OUTRO_SCENE_24, EVENT_OUTRO_SCENE_25, EVENT_OUTRO_SCENE_26, EVENT_OUTRO_SCENE_27, EVENT_OUTRO_SCENE_28, EVENT_OUTRO_SCENE_29, EVENT_OUTRO_SCENE_3, EVENT_OUTRO_SCENE_30, EVENT_OUTRO_SCENE_31, EVENT_OUTRO_SCENE_32, EVENT_OUTRO_SCENE_33, EVENT_OUTRO_SCENE_34, EVENT_OUTRO_SCENE_35, EVENT_OUTRO_SCENE_36, EVENT_OUTRO_SCENE_37, EVENT_OUTRO_SCENE_38, EVENT_OUTRO_SCENE_39, EVENT_OUTRO_SCENE_4, EVENT_OUTRO_SCENE_40, EVENT_OUTRO_SCENE_41, EVENT_OUTRO_SCENE_42, EVENT_OUTRO_SCENE_43, EVENT_OUTRO_SCENE_44, EVENT_OUTRO_SCENE_45, EVENT_OUTRO_SCENE_46, EVENT_OUTRO_SCENE_47, EVENT_OUTRO_SCENE_48, EVENT_OUTRO_SCENE_49, EVENT_OUTRO_SCENE_5, EVENT_OUTRO_SCENE_50, EVENT_OUTRO_SCENE_51, EVENT_OUTRO_SCENE_52, EVENT_OUTRO_SCENE_53, EVENT_OUTRO_SCENE_54, EVENT_OUTRO_SCENE_55, EVENT_OUTRO_SCENE_56, EVENT_OUTRO_SCENE_57, EVENT_OUTRO_SCENE_58, EVENT_OUTRO_SCENE_59, EVENT_OUTRO_SCENE_6, EVENT_OUTRO_SCENE_60, EVENT_OUTRO_SCENE_61, EVENT_OUTRO_SCENE_7, EVENT_OUTRO_SCENE_8, EVENT_OUTRO_SCENE_9, EVENT_SPELL_ANTI_MAGIC_ZONE, EVENT_SPELL_DARION_MOD_DAMAGE, EVENT_SPELL_DEATH_EMBRACE, EVENT_SPELL_DEATH_STRIKE, EVENT_SPELL_UNHOLY_BLIGHT, EVENT_START_COUNTDOWN_1, EVENT_START_COUNTDOWN_10, EVENT_START_COUNTDOWN_11, EVENT_START_COUNTDOWN_12, EVENT_START_COUNTDOWN_13, EVENT_START_COUNTDOWN_14, EVENT_START_COUNTDOWN_2, EVENT_START_COUNTDOWN_3, EVENT_START_COUNTDOWN_4, EVENT_START_COUNTDOWN_5, EVENT_START_COUNTDOWN_6, EVENT_START_COUNTDOWN_7, EVENT_START_COUNTDOWN_8, EVENT_START_COUNTDOWN_9, FACTION_FRIENDLY, FORCED_MOVEMENT_NONE, Position::GetAngle(), ObjectAccessor::GetCreature(), GetEntryFromSummons(), WorldObject::GetMap(), Unit::GetMotionMaster(), Position::GetOrientation(), Map::GetPlayers(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Unit::GetThreatMgr(), GO_LIGHT_OF_DAWN, LinkedListHead::IsEmpty(), WorldObject::IsWithinDistInMap(), Unit::Kill(), LightOfDawnPos, ScriptedAI::me, MotionMaster::MoveCharge(), MotionMaster::MovePoint(), Unit::NearTeleportTo(), NPC_ACHERUS_GHOUL, NPC_DARION_MOGRAINE, NPC_DEFENDER_OF_THE_LIGHT, NPC_FLESH_BEHEMOTH, NPC_HIGHLORD_ALEXANDROS_MOGRAINE, NPC_HIGHLORD_TIRION_FORDRING, NPC_KOLTIRA_DEATHWEAVER, NPC_ORBAZ_BLOODBANE, NPC_RAMPAGING_ABOMINATION, NPC_RIMBLAT_EARTHSHATTER, NPC_THASSARIAN, NPC_THE_LICH_KING, NPC_WARRIOR_OF_THE_FROZEN_WASTES, REACT_PASSIVE, Unit::RemoveAllAuras(), Unit::ReplaceAllNpcFlags(), SAY_LIGHT_OF_DAWN02, SAY_LIGHT_OF_DAWN04, SAY_LIGHT_OF_DAWN05, SAY_LIGHT_OF_DAWN06, SAY_LIGHT_OF_DAWN09, SAY_LIGHT_OF_DAWN26, SAY_LIGHT_OF_DAWN27, SAY_LIGHT_OF_DAWN28, SAY_LIGHT_OF_DAWN29, SAY_LIGHT_OF_DAWN30, SAY_LIGHT_OF_DAWN31, SAY_LIGHT_OF_DAWN32, SAY_LIGHT_OF_DAWN33, SAY_LIGHT_OF_DAWN34, SAY_LIGHT_OF_DAWN35, SAY_LIGHT_OF_DAWN36, SAY_LIGHT_OF_DAWN37, SAY_LIGHT_OF_DAWN38, SAY_LIGHT_OF_DAWN39, SAY_LIGHT_OF_DAWN40, SAY_LIGHT_OF_DAWN41, SAY_LIGHT_OF_DAWN42, SAY_LIGHT_OF_DAWN43, SAY_LIGHT_OF_DAWN44, SAY_LIGHT_OF_DAWN45, SAY_LIGHT_OF_DAWN46, SAY_LIGHT_OF_DAWN47, SAY_LIGHT_OF_DAWN48, SAY_LIGHT_OF_DAWN49, SAY_LIGHT_OF_DAWN51, SAY_LIGHT_OF_DAWN52, SAY_LIGHT_OF_DAWN53, SAY_LIGHT_OF_DAWN54, SAY_LIGHT_OF_DAWN55, SAY_LIGHT_OF_DAWN56, SAY_LIGHT_OF_DAWN57, SAY_LIGHT_OF_DAWN58, SAY_LIGHT_OF_DAWN59, SAY_LIGHT_OF_DAWN60, SAY_LIGHT_OF_DAWN61, SAY_LIGHT_OF_DAWN62, SAY_LIGHT_OF_DAWN63, SAY_LIGHT_OF_DAWN64, SAY_LIGHT_OF_DAWN65, SAY_LIGHT_OF_DAWN66, SAY_LIGHT_OF_DAWN67, SAY_LIGHT_OF_DAWN68, SendUpdateWorldState(), Unit::SetFacingTo(), Unit::SetFacingToObject(), Creature::SetHomePosition(), Unit::SetImmuneToAll(), Creature::SetReactState(), Unit::SetStandState(), Unit::SetUInt32Value(), Creature::SetWalk(), SPELL_ALEXANDROS_MOGRAINE_SPAWN, SPELL_ANTI_MAGIC_ZONE1, SPELL_APOCALYPSE, SPELL_CAMERA_SHAKE, SPELL_CAMERA_SHAKE_INIT, SPELL_DARION_MOD_DAMAGE, SPELL_DEATH_EMBRACE, SPELL_DEATH_STRIKE, SPELL_EXIT_TELEPORT_VISUAL, SPELL_ICEBOUND_VISAGE, SPELL_LAY_ON_HANDS, SPELL_MOGRAINE_CHARGE, SPELL_REBIRTH_OF_THE_ASHBRINGER, SPELL_REBUKE, SPELL_SOUL_FEAST_ALEX, SPELL_SOUL_FEAST_TIRION, SPELL_THE_LIGHT_OF_DAWN, SPELL_THE_LIGHT_OF_DAWN_Q, SPELL_THE_MIGHT_OF_MOGRAINE, SPELL_THROW_ASHBRINGER, SPELL_TIRION_CHARGE, SPELL_UNHOLY_BLIGHT, WorldObject::SummonCreature(), WorldObject::SummonCreatureGroup(), summons, TEMPSUMMON_CORPSE_DESPAWN, TEMPSUMMON_MANUAL_DESPAWN, TEMPSUMMON_TIMED_OR_CORPSE_DESPAWN, UNIT_FLAG_NON_ATTACKABLE, UNIT_FLAG_NOT_SELECTABLE, UNIT_NPC_EMOTESTATE, UNIT_NPC_FLAG_GOSSIP, UNIT_NPC_FLAG_NONE, UNIT_NPC_FLAG_QUESTGIVER, UNIT_STAND_STATE_DEAD, UNIT_STAND_STATE_KNEEL, UNIT_STAND_STATE_STAND, UNIT_VIRTUAL_ITEM_SLOT_ID, CreatureAI::UpdateVictim(), WORLD_STATE_BATTLE_FOR_LIGHTS_HOPE_COUNTDOWN_ENABLE, WORLD_STATE_BATTLE_FOR_LIGHTS_HOPE_COUNTDOWN_TIME, and WORLD_STATE_BATTLE_FOR_LIGHTS_HOPE_EVENT_BEGIN_ENABLE.
Member Data Documentation
battleStarted
uint8 npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::battleStarted
Referenced by GetData(), JustEngagedWith(), JustRespawned(), JustSummoned(), npc_highlord_darion_mograineAI(), SummonedCreatureDies(), and UpdateAI().
defendersRemaining
uint32 npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::defendersRemaining
Referenced by DoAction(), GetData(), JustRespawned(), and SummonedCreatureDies().
events
EventMap npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::events
resetExecuted
bool npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::resetExecuted
Referenced by npc_highlord_darion_mograineAI(), and Reset().
scourgeRemaining
uint32 npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::scourgeRemaining
Referenced by DoAction(), GetData(), JustRespawned(), and SummonedCreatureDies().
startTimeRemaining
uint32 npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::startTimeRemaining
Referenced by DoAction(), GetData(), and JustRespawned().
summons
SummonList npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::summons
Referenced by GetEntryFromSummons(), JustDied(), JustRespawned(), JustSummoned(), and UpdateAI().
The documentation for this struct was generated from the following file:
azerothcore-wotlk/src/server/scripts/EasternKingdoms/ScarletEnclave/chapter5.cpp